Add MetricSpecBuilder.
world-federation-of-advertisers/cross-media-measurement pull request #1041
Opened 2023-05-31 17:20 UTC by riemanli

2023-05-31 17:20 UTC, wfa-reviewable commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1041)
<!-- Reviewable:end -->

2023-05-31 17:20 UTC, riemanli commented
Current dependencies on/for this PR:
* main
  * **PR #1041** <a href="https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/1041" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈
    * **PR #1004** <a href="https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/1004" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #1029** <a href="https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/1029" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/1041?utm_source=stack-comment).

2023-06-01 19:10 UTC, tristanvuong2021 requested changes
> Reviewed 4 of 7 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1041)* status: all files reviewed, 2 unresolved discussions (waiting on @jcorilla and @riemanli)

___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricSpecBuilderTest.kt` line 94 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1041#-NWsMA6vCwrI6JS8mmCG:-NWsMA6vCwrI6JS8mmCH:b7zwkls) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8ba16182125040064fb563fedc9f8159bf7b5b4e/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricSpecBuilderTest.kt#L94)):*
> ```Kotlin
>         privacyParams =
>           MetricSpecKt.differentialPrivacyParams {
>             epsilon = METRIC_SPEC_CONFIG.reachParams.privacyParams.epsilon
> ```

The tests testing when all fields are filled shouldn't have the same values as the config. You can't tell whether it passes because it is correct, or because it always uses the config.
___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricSpecBuilderTest.kt` line 276 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1041#-NWsAYVa08Pq8aP5Es4E:-NWsAYVa08Pq8aP5Es4F:b-mhvypb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8ba16182125040064fb563fedc9f8159bf7b5b4e/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricSpecBuilderTest.kt#L276)):*
> ```Kotlin
> 
>   @Test
>   fun `buildMetricSpec throw MetricSpecBuildingException when frequency histogram privacy params is not set`() {
> ```

Test name should be swapped with one below.


<!-- Sent from Reviewable.io -->

2023-06-01 19:27 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1041)* status: 6 of 7 files reviewed, 2 unresolved discussions (waiting on @jcorilla and @tristanvuong2021)

___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricSpecBuilderTest.kt` line 94 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1041#-NWsMA6vCwrI6JS8mmCG:-NWsNVpJ7cpmKbIEym6w:b-b57zg8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8ba16182125040064fb563fedc9f8159bf7b5b4e/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricSpecBuilderTest.kt#L94)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

The tests testing when all fields are filled shouldn't have the same values as the config. You can't tell whether it passes because it is correct, or because it always uses the config.
</blockquote></details>

Thanks for the suggestion! Fixed this and the others. 
___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricSpecBuilderTest.kt` line 276 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1041#-NWsAYVa08Pq8aP5Es4E:-NWsNO3wBtjn5qDNY1cM:b-x8yi3y) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8ba16182125040064fb563fedc9f8159bf7b5b4e/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricSpecBuilderTest.kt#L276)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Test name should be swapped with one below.
</blockquote></details>

Thanks for catching it! Done.


<!-- Sent from Reviewable.io -->

2023-06-01 20:49 UTC, tristanvuong2021 approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1041)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jcorilla)



<!-- Sent from Reviewable.io -->

2023-06-05 16:04 UTC, SanjayVas requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1041)* status: all files reviewed, 2 unresolved discussions (waiting on @jcorilla, @riemanli, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricSpecBuilder.kt` line 27 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1041#-NXBHzhH2VHXL6kNBJYD:-NXBHzhH2VHXL6kNBJYE:b-e08ybq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e594b0a54101eaf643dddc68234eccd2da03fa96/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricSpecBuilder.kt#L27)):*
> ```Kotlin
>   Exception(message, cause)
> 
> class MetricSpecBuilder(private val metricSpecConfig: MetricSpecConfig) {
> ```

I'd hesitate to call this a Builder as it doesn't actually follow the Builder pattern.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricSpecBuilder.kt` line 29 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1041#-NXBI9Rk8rIgC-QObZ01:-NXBI9Rk8rIgC-QObZ02:bf3etrm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e594b0a54101eaf643dddc68234eccd2da03fa96/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricSpecBuilder.kt#L29)):*
> ```Kotlin
> class MetricSpecBuilder(private val metricSpecConfig: MetricSpecConfig) {
>   /**
>    * Builds a [MetricSpec] by checking the given [MetricSpec] and filling unset values with default
> ```

This isn't really being clear that the MetricSpec that's returned is a copy.



_Code quote:_
```Kotlin
filling unset values
```


<!-- Sent from Reviewable.io -->

2023-06-05 16:07 UTC, tristanvuong2021 approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1041)* status: all files reviewed, 2 unresolved discussions (waiting on @jcorilla, @riemanli, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricSpecBuilder.kt` line 27 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1041#-NXBHzhH2VHXL6kNBJYD:-NXBIxei9D2_prsd9P-f:bdijsy6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e594b0a54101eaf643dddc68234eccd2da03fa96/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricSpecBuilder.kt#L27)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I'd hesitate to call this a Builder as it doesn't actually follow the Builder pattern.
</blockquote></details>

What about Factory.


<!-- Sent from Reviewable.io -->

2023-06-05 17:26 UTC, SanjayVas requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1041)* status: all files reviewed, 2 unresolved discussions (waiting on @jcorilla, @riemanli, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricSpecBuilder.kt` line 27 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1041#-NXBHzhH2VHXL6kNBJYD:-NXBZKdu8BVJFoohcHhp:bsp62yy) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e594b0a54101eaf643dddc68234eccd2da03fa96/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricSpecBuilder.kt#L27)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

What about Factory.
</blockquote></details>

Factory implies constructing instances. This is really making a copy of something with additional info. Maybe MetricSpecPopulator?

You could also avoid the verb in the class name and go with `MetricSpecDefaults` and a `specifyDefaults` method.


<!-- Sent from Reviewable.io -->

2023-06-05 21:14 UTC, SanjayVas requested changes
> Reviewed 2 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1041)* status: 2 of 7 files reviewed, 2 unresolved discussions (waiting on @jcorilla, @Marco-Premier, @riemanli, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricSpecDefaults.kt` line 27 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1041#-NXCOenh4PpEk3hkRtZj:-NXCOenh4PpEk3hkRtZk:bwpxzcf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/da1f9e2b0c0b92673ffc7eb9691a56a673fd61cf/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricSpecDefaults.kt#L27)):*
> ```Kotlin
>   Exception(message, cause)
> 
> class MetricSpecDefaults(private val metricSpecConfig: MetricSpecConfig) {
> ```

Sorry for the churn but I just came up with a potentially clearer API: a `withDefaults` extension method. `withX` methods tend to use this pattern of returning a copy with some additional field(s) set.

e.g. `metricSpec.withDefaults(config)`
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricSpecDefaults.kt` line 33 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1041#-NXCNzjqDtJyyJ1TOmZI:-NXCNzjqDtJyyJ1TOmZJ:b-ngbwj1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/da1f9e2b0c0b92673ffc7eb9691a56a673fd61cf/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricSpecDefaults.kt#L33)):*
> ```Kotlin
>    */
>   fun specifyDefaults(metricSpec: MetricSpec): MetricSpec {
>     return metricSpec {
> ```

Shouldn't this be copying the given spec? Same for the other methods.



_Suggestion:_
```Kotlin
metricSpec.copy
```


<!-- Sent from Reviewable.io -->

2023-06-05 21:54 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1041)* status: 2 of 7 files reviewed, 2 unresolved discussions (waiting on @jcorilla, @Marco-Premier, @SanjayVas, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricSpecDefaults.kt` line 27 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1041#-NXCOenh4PpEk3hkRtZj:-NXCXs9aBwIsUCX8mXsu:b-w28h7k) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/da1f9e2b0c0b92673ffc7eb9691a56a673fd61cf/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricSpecDefaults.kt#L27)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Sorry for the churn but I just came up with a potentially clearer API: a `withDefaults` extension method. `withX` methods tend to use this pattern of returning a copy with some additional field(s) set.

e.g. `metricSpec.withDefaults(config)`
</blockquote></details>

I see. That's a good point. Let me replace all `buildX` with `X.withDefaults`.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricSpecDefaults.kt` line 33 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1041#-NXCNzjqDtJyyJ1TOmZI:-NXCY5d-CnQJWwn9JZFh:b-47iiia) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/da1f9e2b0c0b92673ffc7eb9691a56a673fd61cf/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricSpecDefaults.kt#L33)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Shouldn't this be copying the given spec? Same for the other methods.
</blockquote></details>

Sure I can change to use `copy`. I explicitly extracted every value from the spec, so the end result should be the same.


<!-- Sent from Reviewable.io -->

2023-06-05 22:19 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1041)* status: 1 of 7 files reviewed, 2 unresolved discussions (waiting on @jcorilla, @Marco-Premier, @SanjayVas, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricSpecDefaults.kt` line 27 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1041#-NXCOenh4PpEk3hkRtZj:-NXCd4uO15aYMm7XM7uv:b-daned8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/da1f9e2b0c0b92673ffc7eb9691a56a673fd61cf/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricSpecDefaults.kt#L27)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

I see. That's a good point. Let me replace all `buildX` with `X.withDefaults`.
</blockquote></details>

Please see the changes as requested.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricSpecDefaults.kt` line 33 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1041#-NXCNzjqDtJyyJ1TOmZI:-NXCd8Eq4mjozcfO0FjB:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/da1f9e2b0c0b92673ffc7eb9691a56a673fd61cf/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricSpecDefaults.kt#L33)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Sure I can change to use `copy`. I explicitly extracted every value from the spec, so the end result should be the same.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-06-06 15:25 UTC, stevenwarejones approved these changes
> Reviewed 3 of 7 files at r4, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1041)* status: all files reviewed, 2 unresolved discussions (waiting on @jcorilla, @Marco-Premier, @SanjayVas, and @tristanvuong2021)



<!-- Sent from Reviewable.io -->

2023-06-06 17:07 UTC, SanjayVas submitted a review, later dismissed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1041)* status: all files reviewed, 1 unresolved discussion (waiting on @jcorilla, @Marco-Premier, and @riemanli)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricSpecDefaults.kt` line 32 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1041#-NXGeyvG3P8DQ152sIKA:-NXGeyvG3P8DQ152sIKB:byeik3d) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d36dae698ab219155964e4edcbf1d75620476289/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricSpecDefaults.kt#L32)):*
> ```Kotlin
>  */
> fun MetricSpec.withDefaults(metricSpecConfig: MetricSpecConfig): MetricSpec {
>   val source = this
> ```

I believe you can inline this, since `this` inside the builder be the DSL builder for the source.



_Code quote:_
```Kotlin
val source = this
```


<!-- Sent from Reviewable.io -->

2023-06-06 17:52 UTC, tristanvuong2021 approved these changes
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1041)* status: all files reviewed, 1 unresolved discussion (waiting on @jcorilla, @Marco-Premier, and @SanjayVas)



<!-- Sent from Reviewable.io -->

2023-06-06 18:42 UTC, SanjayVas reviewed
Not reviewing other files, just the builder part. Note that the PR description needs to change.

> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1041#-:-NXH058X5jJ9E6aaxKTF:b1bbicq)* status: all files reviewed, 1 unresolved discussion (waiting on @jcorilla, @Marco-Premier, and @riemanli)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricSpecDefaults.kt` line 32 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1041#-NXH-xxlDtuTc8xnF-Cp:-NXH-xxlDtuTc8xnF-Cq:bj5v1mm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f357143724cf2a6ad3f0da85c4e067ba9320772c/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricSpecDefaults.kt#L32)):*
> ```Kotlin
>  */
> fun MetricSpec.withDefaults(metricSpecConfig: MetricSpecConfig): MetricSpec {
>   return this.copy {
> ```

nit: still a redundant `this` qualifier.



_Suggestion:_
```Kotlin
copy
```


<!-- Sent from Reviewable.io -->

2023-06-06 20:17 UTC, riemanli reviewed
Thanks for reminding. Changed.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1041#-:-NXHLZnT6mX-LbWF78SF:baony4g)* status: 6 of 7 files reviewed, all discussions resolved (waiting on @jcorilla, @Marco-Premier, @SanjayVas, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricSpecDefaults.kt` line 32 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1041#-NXH-xxlDtuTc8xnF-Cp:-NXHL8HL2w9vJDK_nsrR:bb6un1j) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f357143724cf2a6ad3f0da85c4e067ba9320772c/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricSpecDefaults.kt#L32)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: still a redundant `this` qualifier.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-06-06 22:05 UTC, SanjayVas reviewed
> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1041)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @jcorilla and @Marco-Premier)



<!-- Sent from Reviewable.io -->

2023-06-06 23:28 UTC, riemanli reviewed
> Reviewed 3 of 7 files at r4, 3 of 4 files at r5, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1041)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jcorilla and @Marco-Premier)



<!-- Sent from Reviewable.io -->

2023-06-06 23:34 UTC, merged