[wip] Add DuchyInfo for duchy-related information
world-federation-of-advertisers/cross-media-measurement pull request #106
Opened 2021-06-11 21:11 UTC by oliver-amzn

Still todo: use the new DuchyInfo object instead of DuchyIds and in the interceptor

2021-06-18 19:05 UTC, corbantek reviewed
> Reviewed 16 of 17 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/106)* status: 16 of 17 files reviewed, 1 unresolved discussion (waiting on @efoxepstein, @oliver-amzn, @SanjayVas, @wangyaopw, and @zachcwc)

___
*[src/main/proto/wfa/measurement/config/duchy_info_config.proto, line 32 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/106#-McVV7tQ3EK92nzgIZuK:-McVV7tQ3EK92nzgIZuL:b-ukszcl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/99febde28326985f9575e61a36c74887cad283ef/src/main/proto/wfa/measurement/config/duchy_info_config.proto#L32)):*
> ```protobuf
> 
>     // The ID of the root certificate of the Duchy
>     string root_cert_id = 3;
> ```

For my own knowledge, where does this ID persist, or where is this root cert stored to be looked up by ID?

Also even though this is internal, would we also want to use the `(google.api.resource_reference).type` like the api repo uses?


<!-- Sent from Reviewable.io -->

2021-06-18 20:07 UTC, wangyaopw reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/106)* status: 16 of 17 files reviewed, 4 unresolved discussions (waiting on @efoxepstein, @oliver-amzn, @SanjayVas, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/common/identity/DuchyInfo.kt, line 22 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/106#-McVfqe0EfiqZZopKGXI:-McVfqe0EfiqZZopKGXJ:b-hiik18) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/99febde28326985f9575e61a36c74887cad283ef/src/main/kotlin/org/wfanet/measurement/common/identity/DuchyInfo.kt#L22)):*
> ```
>   /** Map of CombinedPublicKey resource ID to [Entry]. */
> ```
This comment is not accurate any more.
___
*[src/main/proto/wfa/measurement/config/duchy_info_config.proto, line 29 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/106#-McViottB-in6t08-AgO:-McViottB-in6t08-AgP:b-jkh4q1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/99febde28326985f9575e61a36c74887cad283ef/src/main/proto/wfa/measurement/config/duchy_info_config.proto#L29)):*
> ```protobuf
> 
>     // The hostname of the Duchy
>     string hostname = 2;
> ```

The duchy is just a concept. Each duchy has many services running. I'm not sure if all the services have the same hostName. If not, which service's hostName is used here?
___
*[src/main/proto/wfa/measurement/config/duchy_info_config.proto, line 37 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/106#-McVit2IBsOlWKDRuJIH:-McVit2IBsOlWKDRuJII:b-ys0xxl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/99febde28326985f9575e61a36c74887cad283ef/src/main/proto/wfa/measurement/config/duchy_info_config.proto#L37)):*
> ```protobuf
>   // The list of all the Duchy information in this config message
>   repeated Duchy duchies = 1;
> }
> ```

add a new line at the end?


<!-- Sent from Reviewable.io -->

2021-06-18 20:45 UTC, oliver-amzn reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/106)* status: 16 of 17 files reviewed, 4 unresolved discussions (waiting on @corbantek, @efoxepstein, @SanjayVas, @wangyaopw, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/common/identity/DuchyInfo.kt, line 22 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/106#-McVfqe0EfiqZZopKGXI:-McVps7l57fhOIYtEFW0:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/99febde28326985f9575e61a36c74887cad283ef/src/main/kotlin/org/wfanet/measurement/common/identity/DuchyInfo.kt#L22)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
>   /** Map of CombinedPublicKey resource ID to [Entry]. */
> ```
This comment is not accurate any more.
</blockquote></details>

Done.
___
*[src/main/proto/wfa/measurement/config/duchy_info_config.proto, line 29 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/106#-McViottB-in6t08-AgO:-McVqLVq-A1KBUCaV9mj:bwsi7cg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/99febde28326985f9575e61a36c74887cad283ef/src/main/proto/wfa/measurement/config/duchy_info_config.proto#L29)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

The duchy is just a concept. Each duchy has many services running. I'm not sure if all the services have the same hostName. If not, which service's hostName is used here?
</blockquote></details>

That's a very good question, didn't think of that. I'd defer to Sanjay about what to do here.
___
*[src/main/proto/wfa/measurement/config/duchy_info_config.proto, line 32 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/106#-McVV7tQ3EK92nzgIZuK:-McVr2JJ6soa6IRL7opB:bvd1n3l) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/99febde28326985f9575e61a36c74887cad283ef/src/main/proto/wfa/measurement/config/duchy_info_config.proto#L32)):*
<details><summary><i>Previously, corbantek (Kyle Johnson) wrote…</i></summary><blockquote>

For my own knowledge, where does this ID persist, or where is this root cert stored to be looked up by ID?

Also even though this is internal, would we also want to use the `(google.api.resource_reference).type` like the api repo uses?
</blockquote></details>

This is the ID of the root certificate of the duchy that's used to generate the short-living certs that are used for the TLS connections. 

Not 1oo% sure about the google.api.resource .... type thing. This proto is not for an API call but so the information can be passed via the command line, not sure if it makes sense to add this.
___
*[src/main/proto/wfa/measurement/config/duchy_info_config.proto, line 37 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/106#-McVit2IBsOlWKDRuJIH:-McVpUIN1c_AvvcqYQNJ:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/99febde28326985f9575e61a36c74887cad283ef/src/main/proto/wfa/measurement/config/duchy_info_config.proto#L37)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

add a new line at the end?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-06-19 18:29 UTC, efoxepstein requested changes
> Reviewed 15 of 17 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/106)* status: all files reviewed, 10 unresolved discussions (waiting on @corbantek, @oliver-amzn, @SanjayVas, @wangyaopw, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/common/identity/DuchyIdentity.kt, line 41 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/106#-Mc_UwCD7uFLCqSC7c1U:-Mc_UwCD7uFLCqSC7c1V:b-qotu3w) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a5948dbb3dba470c479be12b58e601d503d8f480/src/main/kotlin/org/wfanet/measurement/common/identity/DuchyIdentity.kt#L41)):*
> ```Kotlin
> data class DuchyIdentity(val id: String) {
>   init {
>     require(DuchyInfo.getByDuchyId(id) != null) {
> ```

Please use `requireNotNull(x)` instead of `require(x != null)`
___
*[src/main/kotlin/org/wfanet/measurement/common/identity/DuchyIdentity.kt, line 105 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/106#-Mc_V8Sv71fvWQxakjEN:-Mc_V8Sv71fvWQxakjEO:b-5suv8t) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a5948dbb3dba470c479be12b58e601d503d8f480/src/main/kotlin/org/wfanet/measurement/common/identity/DuchyIdentity.kt#L105)):*
> ```Kotlin
>     }
> 
>     sslSession.peerCertificates.forEach {
> ```

I prefer a normal for-loop for multi-line bodies. This also makes it more natural to give `it` a better name.
___
*[src/main/kotlin/org/wfanet/measurement/common/identity/DuchyInfo.kt, line 28 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/106#-Mc_WCzjBJL0qUKfVclP:-Mc_WCzjBJL0qUKfVclQ:b-97aaq4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a5948dbb3dba470c479be12b58e601d503d8f480/src/main/kotlin/org/wfanet/measurement/common/identity/DuchyInfo.kt#L28)):*
> ```Kotlin
>     get() = DuchyInfo.entries.map { it.duchyId }.toSet()
> 
>   fun setDuchyInfoFromFlags(flags: DuchyInfoFlags) {
> ```

Since this is within `DuchyInfo`, I wonder if this should just be called like `initializeFromFlags`. Otherwise it's a little stuttery: `DuchyInfo.setDuchyInfoFromFlags`.
___
*[src/main/kotlin/org/wfanet/measurement/common/identity/DuchyInfo.kt, line 46 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/106#-Mc_WeKhDKYehTtSfw-b:-Mc_WeKhDKYehTtSfw-c:b-89a4l7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a5948dbb3dba470c479be12b58e601d503d8f480/src/main/kotlin/org/wfanet/measurement/common/identity/DuchyInfo.kt#L46)):*
> ```Kotlin
>   }
> 
>   fun setDuchyInfoForTest(duchyIds: Set<String>) {
> ```

Ditto
___
*[src/main/kotlin/org/wfanet/measurement/common/identity/DuchyInfo.kt, line 62 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/106#-Mc_WkQF6F_0s-H8Pdj3:-Mc_WkQF6F_0s-H8Pdj4:b-kq42o1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a5948dbb3dba470c479be12b58e601d503d8f480/src/main/kotlin/org/wfanet/measurement/common/identity/DuchyInfo.kt#L62)):*
> ```Kotlin
> }
> 
> class DuchyInfoFlags {
> ```

Is this redundant with `DuchyInfo.Flags`?
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ConfirmDuchyReadiness.kt, line 44 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/106#-Mc_WwFq2dTaduTjAu0w:-Mc_WwFq2dTaduTjAu0x:bi0pg6y) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a5948dbb3dba470c479be12b58e601d503d8f480/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ConfirmDuchyReadiness.kt#L44)):*
> ```Kotlin
> ) : SimpleSpannerWriter<Report>() {
>   override suspend fun TransactionScope.runTransaction(): Report {
>     require(DuchyInfo.getByDuchyId(duchyId) != null) {
> ```

`requireNotNull` please


<!-- Sent from Reviewable.io -->

2021-06-21 15:07 UTC, oliver-amzn reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/106)* status: 9 of 17 files reviewed, 10 unresolved discussions (waiting on @corbantek, @efoxepstein, @SanjayVas, @wangyaopw, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/common/identity/DuchyIdentity.kt, line 41 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/106#-Mc_UwCD7uFLCqSC7c1U:-Mciokc66DHUvJH0r9da:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a5948dbb3dba470c479be12b58e601d503d8f480/src/main/kotlin/org/wfanet/measurement/common/identity/DuchyIdentity.kt#L41)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Please use `requireNotNull(x)` instead of `require(x != null)`
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/common/identity/DuchyIdentity.kt, line 105 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/106#-Mc_V8Sv71fvWQxakjEN:-Mciq0pk6N7IhtSm0rBU:b-wva8qk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a5948dbb3dba470c479be12b58e601d503d8f480/src/main/kotlin/org/wfanet/measurement/common/identity/DuchyIdentity.kt#L105)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

I prefer a normal for-loop for multi-line bodies. This also makes it more natural to give `it` a better name.
</blockquote></details>

Yesss, let me change that.
___
*[src/main/kotlin/org/wfanet/measurement/common/identity/DuchyInfo.kt, line 28 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/106#-Mc_WCzjBJL0qUKfVclP:-Mciovuj7hpf6SCZ2hi7:b36w26z) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a5948dbb3dba470c479be12b58e601d503d8f480/src/main/kotlin/org/wfanet/measurement/common/identity/DuchyInfo.kt#L28)):*
> initializeFromFlags

I like that.
___
*[src/main/kotlin/org/wfanet/measurement/common/identity/DuchyInfo.kt, line 46 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/106#-Mc_WeKhDKYehTtSfw-b:-Mcj66vH8ysdjtEsd4bI:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a5948dbb3dba470c479be12b58e601d503d8f480/src/main/kotlin/org/wfanet/measurement/common/identity/DuchyInfo.kt#L46)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Ditto
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/common/identity/DuchyInfo.kt, line 62 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/106#-Mc_WkQF6F_0s-H8Pdj3:-McipICA3soM3miFcO8Q:b-9j1hew) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a5948dbb3dba470c479be12b58e601d503d8f480/src/main/kotlin/org/wfanet/measurement/common/identity/DuchyInfo.kt#L62)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Is this redundant with `DuchyInfo.Flags`?
</blockquote></details>

Yup, good catch, that was copy-pasta :spaghetti:  leftover, removed DuchyInfo.Flags
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ConfirmDuchyReadiness.kt, line 44 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/106#-Mc_WwFq2dTaduTjAu0w:-Mcipg_o9XwHrG3rRq_I:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a5948dbb3dba470c479be12b58e601d503d8f480/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ConfirmDuchyReadiness.kt#L44)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

`requireNotNull` please
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-06-21 15:17 UTC, efoxepstein requested changes
> Reviewed 8 of 8 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/106)* status: all files reviewed, 4 unresolved discussions (waiting on @corbantek, @SanjayVas, @wangyaopw, and @zachcwc)

___
*[src/main/proto/wfa/measurement/config/duchy_info_config.proto, line 29 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/106#-McViottB-in6t08-AgO:-Mc_X36x7KrNGcC6vIod:bz03sso) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/99febde28326985f9575e61a36c74887cad283ef/src/main/proto/wfa/measurement/config/duchy_info_config.proto#L29)):*
<details><summary><i>Previously, oliver-amzn (Oliver) wrote…</i></summary><blockquote>

That's a very good question, didn't think of that. I'd defer to Sanjay about what to do here.
</blockquote></details>

Paging @sanjayvas

What about a map from gRPC service name to hostname?

Or in practice will we want to have some load balancer in front of all public APIs that gives a single hostname?


<!-- Sent from Reviewable.io -->

2021-06-21 16:03 UTC, wangyaopw requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/106)* status: all files reviewed, 3 unresolved discussions (waiting on @corbantek, @SanjayVas, @wangyaopw, and @zachcwc)

___
*[src/main/proto/wfa/measurement/config/duchy_info_config.proto, line 29 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/106#-McViottB-in6t08-AgO:-McjI04bAVTDjyKiG5r8:brklngq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/99febde28326985f9575e61a36c74887cad283ef/src/main/proto/wfa/measurement/config/duchy_info_config.proto#L29)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Paging @sanjayvas

What about a map from gRPC service name to hostname?

Or in practice will we want to have some load balancer in front of all public APIs that gives a single hostname?
</blockquote></details>

FYI, a duchy currently only has two public facing services.

The MC doesn't see the duchy at all.
The EDP only sees the duchy's RequisitionFulfillmentService.
A duchy only sees the other duchy's ComputationControlService.
The Kingdom doesn't send request to the duchy.


<!-- Sent from Reviewable.io -->

2021-06-21 21:03 UTC, corbantek approved these changes
> Reviewed 1 of 2 files at r2, 8 of 8 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/106)* status: all files reviewed, 3 unresolved discussions (waiting on @oliver-amzn, @SanjayVas, @wangyaopw, and @zachcwc)

___
*[src/main/proto/wfa/measurement/config/duchy_info_config.proto, line 32 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/106#-McVV7tQ3EK92nzgIZuK:-MckN6qx7xWsCCAgYqr6:b-837i4v) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/99febde28326985f9575e61a36c74887cad283ef/src/main/proto/wfa/measurement/config/duchy_info_config.proto#L32)):*
<details><summary><i>Previously, oliver-amzn (Oliver) wrote…</i></summary><blockquote>

This is the ID of the root certificate of the duchy that's used to generate the short-living certs that are used for the TLS connections. 

Not 1oo% sure about the google.api.resource .... type thing. This proto is not for an API call but so the information can be passed via the command line, not sure if it makes sense to add this.
</blockquote></details>

Okay


<!-- Sent from Reviewable.io -->

2021-06-22 00:14 UTC, SanjayVas requested changes
> Reviewed 2 of 17 files at r1, 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/106)* status: all files reviewed, 5 unresolved discussions (waiting on @efoxepstein, @oliver-amzn, @wangyaopw, and @zachcwc)

___
*[src/main/proto/wfa/measurement/config/duchy_info_config.proto, line 29 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/106#-McViottB-in6t08-AgO:-Mcl1W6REKx5T6gBS2C_:b-9k7b8x) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/99febde28326985f9575e61a36c74887cad283ef/src/main/proto/wfa/measurement/config/duchy_info_config.proto#L29)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

FYI, a duchy currently only has two public facing services.

The MC doesn't see the duchy at all.
The EDP only sees the duchy's RequisitionFulfillmentService.
A duchy only sees the other duchy's ComputationControlService.
The Kingdom doesn't send request to the duchy.
</blockquote></details>

This config would be read by anything that's *receiving* RPCs from a Duchy, but this field would only be used by Duchies.

This should be more specific to indicate that it's the ComputationControl service target. The "target" term comes from [ManagedChannelBuilder#forTarget](https://grpc.github.io/grpc-java/javadoc/io/grpc/ManagedChannelBuilder.html#forTarget-java.lang.String-).
___
*[src/main/proto/wfa/measurement/config/duchy_info_config.proto, line 23 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/106#-Mcl2qS05MPR_K75uhKp:-Mcl2qS05MPR_K75uhKq:b-ivqhj9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/92ae9fd1ce4bde0dc422f57431de6c844d8cc332/src/main/proto/wfa/measurement/config/duchy_info_config.proto#L23)):*
> ```
> DuchyInfoConfig
> ```
Maybe something like `DuchyRpcConfig` to be more specific, since we'd have a separate config message for other Duchy info private to the Kingdom (e.g. mapping between internal and external Duchy IDs).
___
*[src/main/proto/wfa/measurement/config/duchy_info_config.proto, line 31 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/106#-Mcl1EOACktt-4Z5umG-:-Mcl1EOACktt-4Z5umG0:b-dsmkz3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/92ae9fd1ce4bde0dc422f57431de6c844d8cc332/src/main/proto/wfa/measurement/config/duchy_info_config.proto#L31)):*
> ```
>     // The ID of the root certificate of the Duchy
>     string root_cert_id = 3;
> ```
Probably want to be more specific and indicate that this is the subject key identifier (SKID) of the Duchy's root certificate. To make that more apparent in the field name, perhaps `root_certificate_skid`. I don't think we've been using the "cert" abbreviation anywhere.


<!-- Sent from Reviewable.io -->

2021-06-22 01:49 UTC, oliver-amzn reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/106)* status: 15 of 17 files reviewed, 4 unresolved discussions (waiting on @corbantek, @efoxepstein, @SanjayVas, @wangyaopw, and @zachcwc)

___
*[src/main/proto/wfa/measurement/config/duchy_info_config.proto, line 29 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/106#-McViottB-in6t08-AgO:-MclINBa-_p6lzorBO81:b-zgkc59) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/99febde28326985f9575e61a36c74887cad283ef/src/main/proto/wfa/measurement/config/duchy_info_config.proto#L29)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This config would be read by anything that's *receiving* RPCs from a Duchy, but this field would only be used by Duchies.

This should be more specific to indicate that it's the ComputationControl service target. The "target" term comes from [ManagedChannelBuilder#forTarget](https://grpc.github.io/grpc-java/javadoc/io/grpc/ManagedChannelBuilder.html#forTarget-java.lang.String-).
</blockquote></details>

Thanks Sanjay, that helps. I'll rename this to computation_control_service_target.
___
*[src/main/proto/wfa/measurement/config/duchy_info_config.proto, line 23 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/106#-Mcl2qS05MPR_K75uhKp:-MclLnbp1ex2j9EGwAVT:b-fdhjge) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/92ae9fd1ce4bde0dc422f57431de6c844d8cc332/src/main/proto/wfa/measurement/config/duchy_info_config.proto#L23)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> DuchyInfoConfig
> ```
Maybe something like `DuchyRpcConfig` to be more specific, since we'd have a separate config message for other Duchy info private to the Kingdom (e.g. mapping between internal and external Duchy IDs).
</blockquote></details>

I _think_ I'm fine with DuchyRpcConfig though I keep thinking we could extend this to be the one place where we configure all the Duchy properties that need configuring.
Let me change it to `DuchyRpcConfig` for now and if we want to broaden the purpose in the future then we can do so.
___
*[src/main/proto/wfa/measurement/config/duchy_info_config.proto, line 31 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/106#-Mcl1EOACktt-4Z5umG-:-MclInKT3ZPw6_82TKJ6:b-tbui69) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/92ae9fd1ce4bde0dc422f57431de6c844d8cc332/src/main/proto/wfa/measurement/config/duchy_info_config.proto#L31)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
>     // The ID of the root certificate of the Duchy
>     string root_cert_id = 3;
> ```
Probably want to be more specific and indicate that this is the subject key identifier (SKID) of the Duchy's root certificate. To make that more apparent in the field name, perhaps `root_certificate_skid`. I don't think we've been using the "cert" abbreviation anywhere.
</blockquote></details>

`root_certificate_skid` sounds good, I'll use that, thanks.


<!-- Sent from Reviewable.io -->

2021-06-22 13:54 UTC, efoxepstein approved these changes
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/106)* status: all files reviewed, 4 unresolved discussions (waiting on @SanjayVas, @wangyaopw, and @zachcwc)



<!-- Sent from Reviewable.io -->

2021-06-22 13:56 UTC, corbantek approved these changes
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/106)* status: all files reviewed, 4 unresolved discussions (waiting on @SanjayVas, @wangyaopw, and @zachcwc)



<!-- Sent from Reviewable.io -->

2021-06-22 16:50 UTC, SanjayVas requested changes
> Reviewed 5 of 17 files at r1, 6 of 8 files at r3, 2 of 2 files at r4, 2 of 2 files at r5, 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/106)* status: all files reviewed, 8 unresolved discussions (waiting on @oliver-amzn, @wangyaopw, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/common/identity/DuchyIdentity.kt, line 90 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/106#-McoavYWBRB82Kzorl3S:-McoavYWBRB82Kzorl3T:b-wewt9m) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7d1cfc70fd0e641c3c52d7d93a205bb9d851e225/src/main/kotlin/org/wfanet/measurement/common/identity/DuchyIdentity.kt#L90)):*
> ```
> DuchyInfoInterceptor
> ```
This name seems a little odd, as it's still just setting Duchy identity. Maybe the name should instead reflect the fact that this comes from TLS? e.g. `DuchyTlsIdentityInterceptor`?
___
*[src/main/kotlin/org/wfanet/measurement/common/identity/DuchyIdentity.kt, line 133 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/106#-Mcoah8b6EMPzYGWJGQt:-Mcoah8b6EMPzYGWJGQu:b-hsrele) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7d1cfc70fd0e641c3c52d7d93a205bb9d851e225/src/main/kotlin/org/wfanet/measurement/common/identity/DuchyIdentity.kt#L133)):*
> ```
> DuchyServerIdentityInterceptor
> ```
Wrong interceptor.
___
*[src/main/kotlin/org/wfanet/measurement/common/identity/DuchyInfo.kt, line 15 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/106#-McoaMffELXYHglwmpUn:-McoaMffELXYHglwmpUo:b-gg5izh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7d1cfc70fd0e641c3c52d7d93a205bb9d851e225/src/main/kotlin/org/wfanet/measurement/common/identity/DuchyInfo.kt#L15)):*
> ```
> grpc
> ```
Package name doesn't match directory structure. I think this is in the right directory, just need to update the package name.
___
*[src/main/kotlin/org/wfanet/measurement/common/identity/DuchyInfo.kt, line 50 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/106#-McobkuG36NL8B8xQ6Ub:-McobkuG36NL8B8xQ6Uc:b1kw14i) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7d1cfc70fd0e641c3c52d7d93a205bb9d851e225/src/main/kotlin/org/wfanet/measurement/common/identity/DuchyInfo.kt#L50)):*
> ```Kotlin
>   }
> 
>   data class Entry(val duchyId: String, val hostName: String, val rootCertId: String)
> ```

Update param names to match proto field renaming.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/server/KingdomDataServer.kt, line 19 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/106#-Mcoc7SN07g1vuNwcp9B:-Mcoc7SO-7jreHMs1daY:b-46mvtm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7d1cfc70fd0e641c3c52d7d93a205bb9d851e225/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/server/KingdomDataServer.kt#L19)):*
> ```
> <<<<<<< HEAD
> ```
Resolve merge conflict markers
___
*[src/main/proto/wfa/measurement/config/duchy_info_config.proto, line 23 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/106#-Mcl2qS05MPR_K75uhKp:-Mco_zXo2TP54Yiy-ms_:b-vfw59w) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/92ae9fd1ce4bde0dc422f57431de6c844d8cc332/src/main/proto/wfa/measurement/config/duchy_info_config.proto#L23)):*
<details><summary><i>Previously, oliver-amzn (Oliver) wrote…</i></summary><blockquote>

I _think_ I'm fine with DuchyRpcConfig though I keep thinking we could extend this to be the one place where we configure all the Duchy properties that need configuring.
Let me change it to `DuchyRpcConfig` for now and if we want to broaden the purpose in the future then we can do so.

</blockquote></details>

Sounds good. You'll want to rename the file as well.


<!-- Sent from Reviewable.io -->

2021-06-22 17:44 UTC, oliver-amzn reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/106)* status: 1 of 18 files reviewed, 8 unresolved discussions (waiting on @corbantek, @efoxepstein, @SanjayVas, @wangyaopw, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/common/identity/DuchyIdentity.kt, line 90 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/106#-McoavYWBRB82Kzorl3S:-McomHTjAnlzLHMMGU73:by3v65k) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7d1cfc70fd0e641c3c52d7d93a205bb9d851e225/src/main/kotlin/org/wfanet/measurement/common/identity/DuchyIdentity.kt#L90)):*
> DuchyTlsIdentityInterceptor

Ok, will change.
___
*[src/main/kotlin/org/wfanet/measurement/common/identity/DuchyIdentity.kt, line 133 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/106#-Mcoah8b6EMPzYGWJGQt:-McomliLA7Z02DTKqoy5:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7d1cfc70fd0e641c3c52d7d93a205bb9d851e225/src/main/kotlin/org/wfanet/measurement/common/identity/DuchyIdentity.kt#L133)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> DuchyServerIdentityInterceptor
> ```
Wrong interceptor.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/common/identity/DuchyInfo.kt, line 15 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/106#-McoaMffELXYHglwmpUn:-Mcomq7v1-aAwaKEvipa:bx7d7ou) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7d1cfc70fd0e641c3c52d7d93a205bb9d851e225/src/main/kotlin/org/wfanet/measurement/common/identity/DuchyInfo.kt#L15)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> grpc
> ```
Package name doesn't match directory structure. I think this is in the right directory, just need to update the package name.
</blockquote></details>

Ugh, good catch, thx!
___
*[src/main/kotlin/org/wfanet/measurement/common/identity/DuchyInfo.kt, line 50 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/106#-McobkuG36NL8B8xQ6Ub:-Mcoo0lV5CxCiJueu6IP:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7d1cfc70fd0e641c3c52d7d93a205bb9d851e225/src/main/kotlin/org/wfanet/measurement/common/identity/DuchyInfo.kt#L50)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Update param names to match proto field renaming.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/server/KingdomDataServer.kt, line 19 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/106#-Mcoc7SN07g1vuNwcp9B:-Mcoo1usEs6h21gyIPoP:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7d1cfc70fd0e641c3c52d7d93a205bb9d851e225/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/server/KingdomDataServer.kt#L19)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> <<<<<<< HEAD
> ```
Resolve merge conflict markers
</blockquote></details>

Done.
___
*[src/main/proto/wfa/measurement/config/duchy_info_config.proto, line 23 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/106#-Mcl2qS05MPR_K75uhKp:-Mcoo_kU98CN_YU_sLe-:bwq6zag) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/92ae9fd1ce4bde0dc422f57431de6c844d8cc332/src/main/proto/wfa/measurement/config/duchy_info_config.proto#L23)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Sounds good. You'll want to rename the file as well.
</blockquote></details>

Ah yes. Done. And changed the bazel build rules as well.


<!-- Sent from Reviewable.io -->

2021-06-22 17:47 UTC, wangyaopw approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/106)* status: 1 of 18 files reviewed, 7 unresolved discussions (waiting on @corbantek, @efoxepstein, @SanjayVas, @wangyaopw, and @zachcwc)



<!-- Sent from Reviewable.io -->

2021-06-22 19:36 UTC, SanjayVas approved these changes
> Reviewed 17 of 17 files at r7.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/106)* status: all files reviewed, 2 unresolved discussions (waiting on @oliver-amzn, @wangyaopw, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/common/identity/DuchyIdentity.kt, line 84 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/106#-McpBvgh8rMp1aOACdAr:-McpBvgh8rMp1aOACdAs:bconmln) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8c1f6d7eebccd60719e74f9b046ff965f5e792f0/src/main/kotlin/org/wfanet/measurement/common/identity/DuchyIdentity.kt#L84)):*
> ```Kotlin
> 
>     for (cert in sslSession.peerCertificates) {
>       if (cert is X509Certificate) {
> ```

nit: prefer having fewer nested statements. e.g.

```
if (cert !is X509Certificate) {
  continue
}
```

```
if (duchyInfo == null) {
  continue
}
```


<!-- Sent from Reviewable.io -->

2021-06-22 22:06 UTC, oliver-amzn reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/106)* status: 17 of 18 files reviewed, 1 unresolved discussion (waiting on @SanjayVas, @wangyaopw, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/common/identity/DuchyIdentity.kt, line 84 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/106#-McpBvgh8rMp1aOACdAr:-McpkhIt41VdAGPzxkuk:b-69kwb6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8c1f6d7eebccd60719e74f9b046ff965f5e792f0/src/main/kotlin/org/wfanet/measurement/common/identity/DuchyIdentity.kt#L84)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: prefer having fewer nested statements. e.g.

```
if (cert !is X509Certificate) {
  continue
}
```

```
if (duchyInfo == null) {
  continue
}
```
</blockquote></details>

Yeah, let me do that, i like that.


<!-- Sent from Reviewable.io -->

2021-06-22 22:32 UTC, merged