Create AcdpParamsConverter and ACDP composition method
world-federation-of-advertisers/cross-media-measurement pull request #1062
Opened 2023-06-13 19:55 UTC by iverson52000

2023-06-22 00:42 UTC, uakyol reviewed
I think we should split this PR into 5 parts
1) Gaussian Noising library changes -> GausianNoiser, Composition, etc...
2) Api related changes -> AcdpParamsConvertor ...
3) Backing store changes -> InMemoryBackingStore ...
4) PBM library changes -> PrivacyBudgetManager, PrivacyBudgetLedger...
5) EdpSimulator Changes

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1062#-:-NYVXhDU8osD1q9Bcx85:b-6gcmt4)* status: 0 of 32 files reviewed, all discussions resolved (waiting on @jiayu-google, @pasin30055, @SanjayVas, and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2023-06-22 17:47 UTC, pasin30055 approved these changes

2023-06-22 17:47 UTC, pasin30055 commented on src/test/kotlin/org/wfanet/measurement/eventdataprovider/noisers/GaussianNoiserTest.kt
> +    val sigma = GaussianNoiser.getSigma(MEASUREMENT_SPEC.reachAndFrequency.reachPrivacyParams)
This is perhaps ok, but I just want to say that it took a long time for me to track down the exact privacy parameters. Maybe hardcode them more clearly here would be easier to read / verify?

2023-06-22 21:46 UTC, iverson52000 commented
This PR only covers 1 and 2. A lot of files are touched because of the renaming `Charge` to `DpCharge`





<!-- Sent from Reviewable.io -->

2023-06-23 03:30 UTC, jiayu-google approved these changes

2023-06-23 03:39 UTC, jiayu-google approved these changes

2023-06-23 03:39 UTC, jiayu-google commented on src/test/kotlin/org/wfanet/measurement/eventdataprovider/noisers/GaussianNoiserTest.kt
> +    assertThat(sigma).isEqualTo(expectedSigma)
Wondering if `isEqualTo` is too strict. Would it possibly fail to due future version changes that affects the utils used in `GaussianNoiser.getSigma`, say, `standardNormalDistribution.cumulativeProbability`

2023-06-23 03:49 UTC, jiayu-google commented on src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/AcdpParamsConverterTest.kt
> +    assertThat(acdpCharge).isEqualTo(expectedAcdpCharge)
Ditto.  Like we may check equality up to 10 digits, or assert diffRatio < 1e-4

2023-06-23 03:53 UTC, jiayu-google commented on src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/AcdpParamsConverterTest.kt
> +    assertThat(acdpCharge).isEqualTo(expectedAcdpCharge)
@pasin30055 wondering in your field, whether you asssert "almost equal" and how many digits you use in unit tests for DP params. Guess it should be strict than other unit tests

2023-06-23 04:19 UTC, uakyol approved these changes
Sorry, just realized. It looks good to me.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1062#-:-NYaTWG5D5r-7oBf6hq1:b-2fpvr9)* status: 0 of 32 files reviewed, 3 unresolved discussions (waiting on @iverson52000, @SanjayVas, and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2023-06-23 21:22 UTC, SanjayVas requested changes
> Reviewed 2 of 32 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1062)* status: 2 of 32 files reviewed, 4 unresolved discussions (waiting on @iverson52000 and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/noisers/GaussianNoiser.kt` line 25 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1062#-NYe6tTX1OsSZyF939Tg:-NYe6tTX1OsSZyF939Th:b-ih0mnb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/909da0527ccec2f9d3d21f3256aaa240d5b2c072/src/main/kotlin/org/wfanet/measurement/eventdataprovider/noisers/GaussianNoiser.kt#L25)):*
> ```Kotlin
> import org.wfanet.measurement.api.v2alpha.DifferentialPrivacyParams
> 
> class GaussianNoiser(privacyParams: DifferentialPrivacyParams, random: Random) : AbstractNoiser() {
> ```

Should this be taking in an API `DifferentialPrivacyParams`? It means that it's bound to this specific version of the public API.

Said another way, anything that specifically deals with a versioned API should either also be versioned or be built to handle multiple API versions. In this case, you might want to create a separate Kotlin data class and let the callers convert to it in a version-specific way.


<!-- Sent from Reviewable.io -->

2023-06-28 17:38 UTC, iverson52000 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1062)* status: 24 of 32 files reviewed, 4 unresolved discussions (waiting on @jiayu-google, @Marco-Premier, @pasin30055, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/noisers/GaussianNoiser.kt` line 25 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1062#-NYe6tTX1OsSZyF939Tg:-NZ23ueD2XJJg4t54Mqj:b-dtied8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/909da0527ccec2f9d3d21f3256aaa240d5b2c072/src/main/kotlin/org/wfanet/measurement/eventdataprovider/noisers/GaussianNoiser.kt#L25)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Should this be taking in an API `DifferentialPrivacyParams`? It means that it's bound to this specific version of the public API.

Said another way, anything that specifically deals with a versioned API should either also be versioned or be built to handle multiple API versions. In this case, you might want to create a separate Kotlin data class and let the callers convert to it in a version-specific way.
</blockquote></details>

Done. Added internal `DpParams` data class.
___
*[`src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/AcdpParamsConverterTest.kt` line 99 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1062#gh-1239292004:-NZ247R69n8bY8VfSyRB:b-jm91fn) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/909da0527ccec2f9d3d21f3256aaa240d5b2c072/src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/AcdpParamsConverterTest.kt#L99)):*
<details><summary><i>Previously, jiayu-google wrote…</i></summary><blockquote>

@pasin30055 wondering in your field, whether you asssert "almost equal" and how many digits you use in unit tests for DP params. Guess it should be strict than other unit tests
</blockquote></details>

Change to using `isWithin` with `TOLERANCE=1E-10`
___
*[`src/test/kotlin/org/wfanet/measurement/eventdataprovider/noisers/GaussianNoiserTest.kt` line 66 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1062#gh-1238836152:-NZ23gZV-vB-C1Lscl2c:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/909da0527ccec2f9d3d21f3256aaa240d5b2c072/src/test/kotlin/org/wfanet/measurement/eventdataprovider/noisers/GaussianNoiserTest.kt#L66)):*
<details><summary><i>Previously, pasin30055 (Pasin Manurangsi) wrote…</i></summary><blockquote>

This is perhaps ok, but I just want to say that it took a long time for me to track down the exact privacy parameters. Maybe hardcode them more clearly here would be easier to read / verify?
</blockquote></details>

Done.
___
*[`src/test/kotlin/org/wfanet/measurement/eventdataprovider/noisers/GaussianNoiserTest.kt` line 69 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1062#gh-1239288116:-NZ23iZ_1JSryxphAiLB:b-jm91fn) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/909da0527ccec2f9d3d21f3256aaa240d5b2c072/src/test/kotlin/org/wfanet/measurement/eventdataprovider/noisers/GaussianNoiserTest.kt#L69)):*
<details><summary><i>Previously, jiayu-google wrote…</i></summary><blockquote>

Wondering if `isEqualTo` is too strict. Would it possibly fail to due future version changes that affects the utils used in `GaussianNoiser.getSigma`, say, `standardNormalDistribution.cumulativeProbability`
</blockquote></details>

Change to using `isWithin` with `TOLERANCE=1E-10`


<!-- Sent from Reviewable.io -->

2023-06-28 18:25 UTC, SanjayVas requested changes
> Reviewed 12 of 32 files at r1, 5 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1062)* status: 29 of 32 files reviewed, 8 unresolved discussions (waiting on @iverson52000, @jiayu-google, @Marco-Premier, @pasin30055, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/noisers/BUILD.bazel` line 17 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1062#-NZ2AqBd5TrG6IavPgXA:-NZ2AqBd5TrG6IavPgXB:bhwpg8w) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ddb88864a957d7a6aef4e6c6a49e9547ae23b664/src/main/kotlin/org/wfanet/measurement/eventdataprovider/noisers/BUILD.bazel#L17)):*
> ```Starlark
>     ],
>     deps = [
>         "//src/main/proto/wfa/measurement/api/v2alpha:differential_privacy_kt_jvm_proto",
> ```

Drop this dependency now that it's no longer used.
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/noisers/GaussianNoiser.kt` line 15 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1062#-NZ2Dnaf-Z_GwMwxVpM2:-NZ2Dnaf-Z_GwMwxVpM3:biryq7p) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ddb88864a957d7a6aef4e6c6a49e9547ae23b664/src/main/kotlin/org/wfanet/measurement/eventdataprovider/noisers/GaussianNoiser.kt#L15)):*
Package names are generally singular rather than being described as a collection of what they contain (ignore how commons.math3 isn't consistent on this, e.g. how it has `distribution` as a singular but `solvers` as plural).

To borrow from [Google Cloud API naming conventions](https://cloud.google.com/apis/design/naming_convention#package_names):
>  Package names **should** use singular component names to avoid mixed singular and plural component names.



_Suggestion:_
```Kotlin
noiser
```
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/BUILD.bazel` line 14 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1062#-NZ2B61N7EQRpcTmMbej:-NZ2B61N7EQRpcTmMbek:bhaqgjs) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ddb88864a957d7a6aef4e6c6a49e9547ae23b664/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/BUILD.bazel#L14)):*
> ```Starlark
>         "//src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration:event_filters",
>         "//src/main/kotlin/org/wfanet/measurement/eventdataprovider/noisers",
>         "//src/main/proto/wfa/measurement/api/v2alpha:differential_privacy_kt_jvm_proto",
> ```

Do we still need these API deps?
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/Composition.kt` line 138 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1062#-NZ2Byp9CX-AUJQqTxgR:-NZ2Byp9CX-AUJQqTxgS:b-b09tku) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ddb88864a957d7a6aef4e6c6a49e9547ae23b664/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/Composition.kt#L138)):*
> ```Kotlin
>     targetEpsilon: Float
>   ): Float {
>     val totalRho = acdpCharges.sumOf { it.rho }
> ```

Specify types explicitly except when obvious (e.g. assigning from a literal, constructor, builder, or factory).



_Code quote:_
```Kotlin
val totalRho
```
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyQuery.kt` line 21 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1062#-NZ2CvRpDm9rljvNe_3h:-NZ2CvRpDm9rljvNe_3i:buglph4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ddb88864a957d7a6aef4e6c6a49e9547ae23b664/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyQuery.kt#L21)):*
> ```Kotlin
> data class DpCharge(val epsilon: Float, val delta: Float)
> 
> /** Represents a ACDP charge in rho and theta that will be made to a privacy budget */
> ```

Define your DP and ACDP abbreviations on `DpCharge` and `AcdpCharge`, respectively.



_Suggestion:_
```Kotlin
/** Represents an Almost Concentrated Differential Privacy (ACDP) charge in rho and theta that will be made to a privacy budget */
```


<!-- Sent from Reviewable.io -->

2023-06-28 21:55 UTC, iverson52000 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1062)* status: 14 of 32 files reviewed, 8 unresolved discussions (waiting on @jiayu-google, @Marco-Premier, @pasin30055, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/BUILD.bazel` line 14 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1062#-NZ2B61N7EQRpcTmMbej:-NZ2zR1m2Y-Nq0r9IPBJ:bs1cvng) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ddb88864a957d7a6aef4e6c6a49e9547ae23b664/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/BUILD.bazel#L14)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Do we still need these API deps?
</blockquote></details>

Done. Drop unused API deps
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/Composition.kt` line 138 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1062#-NZ2Byp9CX-AUJQqTxgR:-NZ2zXQGCCv075XVe-4j:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ddb88864a957d7a6aef4e6c6a49e9547ae23b664/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/Composition.kt#L138)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Specify types explicitly except when obvious (e.g. assigning from a literal, constructor, builder, or factory).
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyQuery.kt` line 21 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1062#-NZ2CvRpDm9rljvNe_3h:-NZ2zYT968hQSucsWH0N:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ddb88864a957d7a6aef4e6c6a49e9547ae23b664/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyQuery.kt#L21)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Define your DP and ACDP abbreviations on `DpCharge` and `AcdpCharge`, respectively.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/noisers/BUILD.bazel` line 17 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1062#-NZ2AqBd5TrG6IavPgXA:-NZ2yywM3ijvLzP052rY:bukzyvv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ddb88864a957d7a6aef4e6c6a49e9547ae23b664/src/main/kotlin/org/wfanet/measurement/eventdataprovider/noisers/BUILD.bazel#L17)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Drop this dependency now that it's no longer used.
</blockquote></details>

Oops miss this. Thanks for the reminder.
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/noisers/GaussianNoiser.kt` line 15 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1062#-NZ2Dnaf-Z_GwMwxVpM2:-NZ2z4Vz3ryb-D6QRfrE:b-kw2fw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ddb88864a957d7a6aef4e6c6a49e9547ae23b664/src/main/kotlin/org/wfanet/measurement/eventdataprovider/noisers/GaussianNoiser.kt#L15)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Package names are generally singular rather than being described as a collection of what they contain (ignore how commons.math3 isn't consistent on this, e.g. how it has `distribution` as a singular but `solvers` as plural).

To borrow from [Google Cloud API naming conventions](https://cloud.google.com/apis/design/naming_convention#package_names):
>  Package names **should** use singular component names to avoid mixed singular and plural component names.
</blockquote></details>

Done. Thanks for the reference. Was confused whether should use singular or plural


<!-- Sent from Reviewable.io -->

2023-06-28 22:57 UTC, SanjayVas requested changes
> Reviewed 7 of 32 files at r1, 18 of 18 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1062)* status: all files reviewed, 4 unresolved discussions (waiting on @iverson52000, @jiayu-google, @Marco-Premier, @pasin30055, and @stevenwarejones)

___
*[`src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/BUILD.bazel` line 106 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1062#-NZ3DIgd4TA8FY3gHVRm:-NZ3DIgd4TA8FY3gHVRn:b71htcl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c130870b7ee99aeeb3f813789ba52bdaafb6c6c7/src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/BUILD.bazel#L106)):*
> ```Starlark
>     deps = [
>         "//src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement:privacy_budget_manager",
>         "//src/main/proto/wfa/measurement/api/v2alpha:differential_privacy_kt_jvm_proto",
> ```

Unused dep?



_Code quote:_
```Starlark
        "//src/main/proto/wfa/measurement/api/v2alpha:differential_privacy_kt_jvm_proto",
```


<!-- Sent from Reviewable.io -->

2023-06-29 20:39 UTC, iverson52000 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1062)* status: 30 of 32 files reviewed, 4 unresolved discussions (waiting on @jiayu-google, @Marco-Premier, @pasin30055, @SanjayVas, and @stevenwarejones)

___
*[`src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/BUILD.bazel` line 106 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1062#-NZ3DIgd4TA8FY3gHVRm:-NZ7sPR63s5ogEGqXONq:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c130870b7ee99aeeb3f813789ba52bdaafb6c6c7/src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/BUILD.bazel#L106)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Unused dep?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-06-29 22:24 UTC, SanjayVas approved these changes
Approved for style.

> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1062#-:-NZ8FX6jBYHIxnkSjcl4:b-bxqgrs)* status: all files reviewed, 3 unresolved discussions (waiting on @jiayu-google, @Marco-Premier, @pasin30055, and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2023-06-29 23:10 UTC, jiayu-google approved these changes
Albert, Pasin and I checked the formula implementation and test results offline.

2023-06-30 03:43 UTC, pasin30055 approved these changes

2023-06-30 16:56 UTC, iverson52000 reviewed
Thanks guys!

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1062#-:-NZCDrS-9yV_kAq0Tfh9:b7n8lk7)* status: all files reviewed, 3 unresolved discussions (waiting on @jiayu-google, @Marco-Premier, @pasin30055, and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2023-07-03 12:49 UTC, Marco-Premier approved these changes
> Reviewed 16 of 18 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1062)* status: all files reviewed, 3 unresolved discussions (waiting on @jiayu-google, @pasin30055, and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2023-07-05 17:29 UTC, iverson52000 reviewed
> Reviewed 12 of 32 files at r1, 15 of 18 files at r3, 3 of 3 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1062)* status: all files reviewed, 3 unresolved discussions (waiting on @jiayu-google, @pasin30055, and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2023-07-05 17:30 UTC, iverson52000 reviewed
> Dismissed @jiayu-google and @pasin30055 from 3 discussions.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1062)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)



<!-- Sent from Reviewable.io -->

2023-07-05 17:32 UTC, merged