Add resource IDs to create requests
world-federation-of-advertisers/cross-media-measurement pull request #1071
Opened 2023-06-20 18:17 UTC by riemanli

2023-06-20 18:18 UTC, wfa-reviewable commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1071)
<!-- Reviewable:end -->

2023-06-20 18:18 UTC, riemanli commented
Current dependencies on/for this PR:
* main
  * **PR #1071** <a href="https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/1071" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/1071?utm_source=stack-comment).

2023-06-27 20:46 UTC, tristanvuong2021 reviewed
> Reviewed 6 of 33 files at r1, 4 of 15 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1071)* status: 10 of 35 files reviewed, all discussions resolved (waiting on @jcorilla and @SanjayVas)



<!-- Sent from Reviewable.io -->

2023-06-27 21:02 UTC, tristanvuong2021 reviewed
> Reviewed 3 of 33 files at r1, 1 of 5 files at r2, 3 of 15 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1071)* status: 17 of 35 files reviewed, all discussions resolved (waiting on @jcorilla and @SanjayVas)



<!-- Sent from Reviewable.io -->

2023-06-27 21:20 UTC, tristanvuong2021 reviewed
> Reviewed 2 of 33 files at r1, 1 of 5 files at r2, 2 of 15 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1071)* status: 22 of 35 files reviewed, all discussions resolved (waiting on @jcorilla and @SanjayVas)



<!-- Sent from Reviewable.io -->

2023-06-27 21:23 UTC, tristanvuong2021 reviewed
> Reviewed 1 of 15 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1071)* status: 23 of 35 files reviewed, all discussions resolved (waiting on @jcorilla and @SanjayVas)



<!-- Sent from Reviewable.io -->

2023-06-27 21:40 UTC, tristanvuong2021 requested changes
> Reviewed 2 of 33 files at r1, 1 of 5 files at r2, 2 of 15 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1071)* status: 28 of 35 files reviewed, 3 unresolved discussions (waiting on @jcorilla, @riemanli, and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/MetricReader.kt` line 205 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1071#-NYymeTmBx_AkdaRBe3H:-NYymeTmBx_AkdaRBe3I:b-gl8f4s) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3edf8e49139e25649958d815a85dc72b3f7378ef/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/MetricReader.kt#L205)):*
> ```Kotlin
>   }
> 
>   /** Throws [MetricNotFoundException] if any Metric not found. */
> ```

Comment should be removed.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/ReportingSetReader.kt` line 133 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1071#-NYymkOI-GGfprt3gOo_:-NYymkOI-GGfprt3gOoa:bt92l8q) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3edf8e49139e25649958d815a85dc72b3f7378ef/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/ReportingSetReader.kt#L133)):*
> ```Kotlin
>       .trimIndent()
> 
>   /** Throws [ReportingSetNotFoundException] if any ReportingSet not found. */
> ```

Comment should be removed
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/v2/ReportsServiceTest.kt` line 706 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1071#-NYyk-4K95ZaTzA3bL6G:-NYyk-4K95ZaTzA3bL6H:b-as3z6n) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3edf8e49139e25649958d815a85dc72b3f7378ef/src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/v2/ReportsServiceTest.kt#L706)):*
> ```Kotlin
> 
>   @Test
>   fun `createReport throws FAILED_PRECONDITION when MC not found`() = runBlocking {
> ```

Don't see the missing externalReportId test.


<!-- Sent from Reviewable.io -->

2023-06-27 21:44 UTC, tristanvuong2021 reviewed
> Reviewed 2 of 33 files at r1, 1 of 15 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1071)* status: 31 of 35 files reviewed, 3 unresolved discussions (waiting on @jcorilla, @riemanli, and @SanjayVas)



<!-- Sent from Reviewable.io -->

2023-06-27 21:56 UTC, tristanvuong2021 requested changes
> Reviewed 2 of 33 files at r1, 1 of 15 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1071)* status: 34 of 35 files reviewed, 6 unresolved discussions (waiting on @jcorilla, @riemanli, and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metrics_service.proto` line 158 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1071#-NYyoM7E-qntFlVxSJS3:-NYyoM7E-qntFlVxSJS4:bdproiz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3edf8e49139e25649958d815a85dc72b3f7378ef/src/main/proto/wfa/measurement/reporting/v2alpha/metrics_service.proto#L158)):*
> ```proto
>   //
>   // This value should be 4-63 characters, and valid characters
>   // are /[a-z][0-9]-/.
> ```

metric_id validation?
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/reporting_sets_service.proto` line 100 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1071#-NYyoK1j7mUTTKpBC9s6:-NYyoK1j7mUTTKpBC9s7:bu2vtp0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3edf8e49139e25649958d815a85dc72b3f7378ef/src/main/proto/wfa/measurement/reporting/v2alpha/reporting_sets_service.proto#L100)):*
> ```proto
>   // This value should be 4-63 characters, and valid characters
>   // are /[a-z][0-9]-/.
>   string reporting_set_id = 2 [(google.api.field_behavior) = REQUIRED];
> ```

reporting_set_id validation?
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/reports_service.proto` line 117 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1071#-NYyoFUh63GcLkPhYdsN:-NYyoFUi60-4xyvqU2v_:b-io69ll) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3edf8e49139e25649958d815a85dc72b3f7378ef/src/main/proto/wfa/measurement/reporting/v2alpha/reports_service.proto#L117)):*
> ```proto
>   //
>   // This value should be 4-63 characters, and valid characters
>   // are /[a-z][0-9]-/.
> ```

report_id validation?


<!-- Sent from Reviewable.io -->

2023-06-27 22:43 UTC, tristanvuong2021 requested changes
> Reviewed 1 of 15 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1071)* status: all files reviewed, 8 unresolved discussions (waiting on @jcorilla, @riemanli, and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateMetrics.kt` line 92 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1071#-NYz0Nrd9y-tbEOw8G2q:-NYz0Nrd9y-tbEOw8G2r:b-91p1vl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3edf8e49139e25649958d815a85dc72b3f7378ef/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateMetrics.kt#L92)):*
> ```Kotlin
> 
>     /**
>      * The following check of ALREADY_EXISTS assumes there is no duplicate metric IDs in the
> ```

How about a check in the internal service to check for duplicate metric ids then.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateMetrics.kt` line 127 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1071#-NYz-q3_35ZjawLJmm3q:-NYz-q3_35ZjawLJmm3r:bbhzsle) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3edf8e49139e25649958d815a85dc72b3f7378ef/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateMetrics.kt#L127)):*
> ```Kotlin
>             }
> 
>             requestId to result.metric
> ```

I don't think this does anything. The check is enough. If the requestId can be found, then it would have been added to the map already.


<!-- Sent from Reviewable.io -->

2023-06-27 23:34 UTC, SanjayVas requested changes
> Reviewed 6 of 33 files at r1, 2 of 15 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1071)* status: all files reviewed, 11 unresolved discussions (waiting on @jcorilla and @riemanli)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 1231 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1071#-NYzC2wl0_K0L1N4NVEH:-NYzC2wl0_K0L1N4NVEI:b-k5xkzt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3edf8e49139e25649958d815a85dc72b3f7378ef/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L1231)):*
> ```Kotlin
>         }
>       }
>     }
> ```

nit: prefer comparing specific types over strings



_Suggestion:_
```Kotlin
    val parentKey = grpcRequireNotNull(MeasurementConsumerKey.fromName(request.parent)) {
      "Parent is either unspecified or invalid."
    }

    val principal: ReportingPrincipal = principalFromCurrentContext

    when (principal) {
      is MeasurementConsumerPrincipal -> {
        if (parentKey != principal.resourceKey) {
          failGrpc(Status.PERMISSION_DENIED) {
            "Cannot create a Metric for another MeasurementConsumer."
          }
        }
      }
    }
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 1242 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1071#-NYzAGWd9txPLIjCVeU8:-NYzAGWd9txPLIjCVeU9:bpehvmg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3edf8e49139e25649958d815a85dc72b3f7378ef/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L1242)):*
> ```Kotlin
>         throw when (e.status.code) {
>             Status.Code.ALREADY_EXISTS ->
>               Status.ALREADY_EXISTS.withDescription("The metric ID already exists.")
> ```

It's not the ID that already exists, but rather a Metric with this ID under this parent (i.e. a Metric with the resulting resource name).



_Suggestion:_
```Kotlin
Metric with ID ${request.metricId} already exists under ${request.parent}
```
___
*[`src/main/resources/reporting/postgres/create-v2-reporting-schema.sql` line 336 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1071#-NYz7im11dfjAmwAqnV8:-NYz7im11dfjAmwAqnV9:b-ykdhpw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3edf8e49139e25649958d815a85dc72b3f7378ef/src/main/resources/reporting/postgres/create-v2-reporting-schema.sql#L336)):*
> ```TSQL
>   ReportId bigint NOT NULL,
> 
>   ExternalReportId text NOT NULL,
> ```

Since we set limits on the length for these fields in the API, we can use a more restrictive data type for them.



_Suggestion:_
```TSQL
varchar(63)
```


<!-- Sent from Reviewable.io -->

2023-06-28 02:49 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1071)* status: 15 of 35 files reviewed, 10 unresolved discussions (waiting on @jcorilla, @SanjayVas, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/MetricReader.kt` line 205 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1071#-NYymeTmBx_AkdaRBe3H:-NYyp9Mb-c9Kkc3oxwMs:b-mws2j5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3edf8e49139e25649958d815a85dc72b3f7378ef/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/MetricReader.kt#L205)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Comment should be removed.
</blockquote></details>

Thanks for pointing it out! Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/ReportingSetReader.kt` line 133 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1071#-NYymkOI-GGfprt3gOo_:-NYypEj27UbvuA4He_wp:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3edf8e49139e25649958d815a85dc72b3f7378ef/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/ReportingSetReader.kt#L133)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Comment should be removed
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateMetrics.kt` line 92 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1071#-NYz0Nrd9y-tbEOw8G2q:-NYzm9Pr5SV290hOzhI1:bdgtpca) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3edf8e49139e25649958d815a85dc72b3f7378ef/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateMetrics.kt#L92)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

How about a check in the internal service to check for duplicate metric ids then.
</blockquote></details>

Added the check in `PostgresMetricsService`.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateMetrics.kt` line 127 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1071#-NYz-q3_35ZjawLJmm3q:-NYzmGBn6TacqPdu36Qy:b-d8ayps) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3edf8e49139e25649958d815a85dc72b3f7378ef/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateMetrics.kt#L127)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

I don't think this does anything. The check is enough. If the requestId can be found, then it would have been added to the map already.
</blockquote></details>

You're right! Thanks for pointing it out. Fixed.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 1231 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1071#-NYzC2wl0_K0L1N4NVEH:-NYzraEM4_UhI7NrlA4e:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3edf8e49139e25649958d815a85dc72b3f7378ef/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L1231)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: prefer comparing specific types over strings
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 1242 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1071#-NYzAGWd9txPLIjCVeU8:-NYzsC9z3raitAdz_SoF:bpu5if0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3edf8e49139e25649958d815a85dc72b3f7378ef/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L1242)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

It's not the ID that already exists, but rather a Metric with this ID under this parent (i.e. a Metric with the resulting resource name).
</blockquote></details>

Thanks for pointing it out. Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/v2/ReportsServiceTest.kt` line 706 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1071#-NYyk-4K95ZaTzA3bL6G:-NYyqIaF-AFtWER5UN2_:b-1ft1ak) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3edf8e49139e25649958d815a85dc72b3f7378ef/src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/v2/ReportsServiceTest.kt#L706)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Don't see the missing externalReportId test.
</blockquote></details>

Thanks for reminding. Added.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metrics_service.proto` line 158 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1071#-NYyoM7E-qntFlVxSJS3:-NYyrzaV2R2doL7gL3Gk:bvm5a6i) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3edf8e49139e25649958d815a85dc72b3f7378ef/src/main/proto/wfa/measurement/reporting/v2alpha/metrics_service.proto#L158)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

metric_id validation?
</blockquote></details>

Thanks for reminding. Added validation on the public side. Does the internal service need to check the resource ID format?
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/reporting_sets_service.proto` line 100 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1071#-NYyoK1j7mUTTKpBC9s6:-NYzeFGE7nR1IT_Gswdy:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3edf8e49139e25649958d815a85dc72b3f7378ef/src/main/proto/wfa/measurement/reporting/v2alpha/reporting_sets_service.proto#L100)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

reporting_set_id validation?
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/reports_service.proto` line 117 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1071#-NYyoFUh63GcLkPhYdsN:-NYzeG_g56ZZmW8xaaPD:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3edf8e49139e25649958d815a85dc72b3f7378ef/src/main/proto/wfa/measurement/reporting/v2alpha/reports_service.proto#L117)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

report_id validation?
</blockquote></details>

Done.
___
*[`src/main/resources/reporting/postgres/create-v2-reporting-schema.sql` line 336 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1071#-NYz7im11dfjAmwAqnV8:-NYzehZgDRT6XqmJQaN4:b-bjudbj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3edf8e49139e25649958d815a85dc72b3f7378ef/src/main/resources/reporting/postgres/create-v2-reporting-schema.sql#L336)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Since we set limits on the length for these fields in the API, we can use a more restrictive data type for them.
</blockquote></details>

Thanks for the suggestion! Done.


<!-- Sent from Reviewable.io -->

2023-06-28 17:32 UTC, SanjayVas requested changes
> Reviewed 5 of 33 files at r1, 8 of 15 files at r3, 17 of 20 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1071)* status: 32 of 35 files reviewed, 21 unresolved discussions (waiting on @jcorilla, @riemanli, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/PostgresMetricsService.kt` line 56 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1071#-NZ1nxEv39imc94pQr4B:-NZ1nxEv39imc94pQr4C:bhgsy70) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9e5b2ba209c16d748ca2a6a42797d6ac2c4cbde9/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/PostgresMetricsService.kt#L56)):*
> ```Kotlin
> ) : MetricsCoroutineImplBase() {
>   override suspend fun createMetric(request: CreateMetricRequest): Metric {
>     grpcRequire(request.externalMetricId.isNotBlank()) { "External metric ID is not set." }
> ```

nit: technically only empty (the default value) means not specified. If it has whitespace it's instead a malformed value (treated similarly as if the ID was the wrong length or had invalid characters).



_Suggestion:_
```Kotlin
isNotEmpty()
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/MeasurementReader.kt` line 56 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1071#-NZ1p8EJ2jWwW-Y_EJqA:-NZ1p8EJ2jWwW-Y_EJqB:bioi84m) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9e5b2ba209c16d748ca2a6a42797d6ac2c4cbde9/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/MeasurementReader.kt#L56)):*
> ```Kotlin
> 
>   private data class PrimitiveReportingSetBasisInfo(
>     val reportingSetId: String,
> ```

This should still be `externalReportingSetId`. In this layer, `reportingSetId` implies the internal ID.



_Suggestion:_
```Kotlin
externalReportingSetId
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/ReportReader.kt` line 203 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1071#-NZ1q-F9CbOEEp-zbv_9:-NZ1q-F9CbOEEp-zbv_A:b-buegqv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9e5b2ba209c16d748ca2a6a42797d6ac2c4cbde9/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/ReportReader.kt#L203)):*
> ```Kotlin
>         if (
>           request.filter.after.createTime != Timestamp.getDefaultInstance() &&
>             request.filter.after.externalReportId == ""
> ```

If the `after` message is set, all fields should be required. Therefore it shouldn't be set in the request from the public service impl unless the public request has a page token.



_Suggestion:_
```Kotlin
          request.filter.hasAfter
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/ReportReader.kt` line 206 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1071#-NZ1qgpe5XiS-SAL57-_:-NZ1qgpe5XiS-SAL57-a:b-md4u57) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9e5b2ba209c16d748ca2a6a42797d6ac2c4cbde9/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/ReportReader.kt#L206)):*
> ```Kotlin
>         ) {
>           // TODO(riemanli): is there a better way?
>           bind("$3", "{")
> ```

Have the SQL itself be different if `hasAfter` is false. See the internal Kingdom [StreamEventGroups](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/06f31c65357b5e0b72de1caab79db64b00c99198/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamEventGroups.kt#L63) implementation as an example.



_Code quote:_
```Kotlin
          // TODO(riemanli): is there a better way?
          bind("$3", "{")
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateMetrics.kt` line 79 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1071#-NZ1rge2Dv7FWlwivPIB:-NZ1rge2Dv7FWlwivPIC:bvjv9jv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9e5b2ba209c16d748ca2a6a42797d6ac2c4cbde9/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateMetrics.kt#L79)):*
> ```Kotlin
>         .measurementConsumerId
> 
>     val existingMetricsMap: MutableMap<String, Metric> = mutableMapOf()
> ```

Unnecessary mutability.

```kotlin
val metricsByCreateRequestId: Map<String, Metric> = 
    MetricReader(transactionContext)
      .readMetricsByRequestId(measurementConsumerId, createMetricRequestIds)
      .toList()
      .associateBy({ it.createMetricRequestId }, { it.metric })
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateMetrics.kt` line 131 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1071#-NZ1tonb5dH0drasMnRd:-NZ1tonb5dH0drasMnRe:b5mpvk4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9e5b2ba209c16d748ca2a6a42797d6ac2c4cbde9/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateMetrics.kt#L131)):*
> ```Kotlin
>         }
>       }
>     }
> ```

nit: Prefer regular for-in loops over `forEach` when not chaining.

Also avoid exposing the mutable collection used for building when possible. In this case [`buildSet`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/build-set.html) would help, but I think it's not available until Kotlin 1.6 we're still on 1.5 at this point :(



_Code quote:_
```Kotlin
    val externalReportingSetIds = mutableSetOf<String>()
    requests.forEach {
      if (!existingMetricsMap.containsKey(it.requestId)) {
        externalReportingSetIds.add(it.metric.externalReportingSetId)
        it.metric.weightedMeasurementsList.forEach { weightedMeasurement ->
          weightedMeasurement.measurement.primitiveReportingSetBasesList.forEach { bases ->
            externalReportingSetIds.add(bases.externalReportingSetId)
          }
        }
      }
    }
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateReport.kt` line 65 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1071#-NZ1whIfAWDH6pbV2TxB:-NZ1whIfAWDH6pbV2TxC:b-u458tm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9e5b2ba209c16d748ca2a6a42797d6ac2c4cbde9/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateReport.kt#L65)):*
> ```Kotlin
>     val report = request.report
> 
>     /** Request IDs take precedence */
> ```

KDoc syntax is for types, functions, and properties. This should be a regular comment.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateReport.kt` line 77 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1071#-NZ1wMll1LvcJOoThglX:-NZ1wMll1LvcJOoThglY:b-u458tm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9e5b2ba209c16d748ca2a6a42797d6ac2c4cbde9/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateReport.kt#L77)):*
> ```Kotlin
>      * If we can't find a report given the request ID but found a report given the external ID,
>      * return Already Exists exception.
>      */
> ```

KDoc syntax is for types, functions, and properties. This should be a regular comment.



_Code quote:_
```Kotlin
    /**
     * If we can't find a report given the request ID but found a report given the external ID,
     * return Already Exists exception.
     */
```
___
*[`src/main/kotlin/org/wfanet/measuremen [...]

2023-06-28 20:15 UTC, tristanvuong2021 reviewed
> Reviewed 19 of 20 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1071)* status: all files reviewed, 15 unresolved discussions (waiting on @jcorilla, @riemanli, and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metrics_service.proto` line 158 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1071#-NZ22-2uDl6_5D9_Bz1E:-NZ2d-3D7qT0wn5Hmb9d:b95f2z2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9e5b2ba209c16d748ca2a6a42797d6ac2c4cbde9/src/main/proto/wfa/measurement/reporting/v2alpha/metrics_service.proto#L158)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Any reason we're deviating from [AIP-122](https://google.aip.dev/122) here and allowing uppercase characters? We deviate in the CMMS API, but we're also using system-generated IDs there.

>   - If resource IDs are user-settable, the API **must** document allowed
>     formats. User-settable resource IDs **should** conform to [RFC-1034][];
>     which restricts to letters, numbers, and hyphen, with the first character
>     a letter, the last a letter or a number, and a 63 character maximum.
>     - Additionally, user-settable resource IDs **should** restrict letters to
>       lower-case (`^[a-z]([a-z0-9-]{0,61}[a-z0-9])?$`).
>     - Characters outside of ASCII **should not** be permitted; however, if
>       Unicode characters are necessary, APIs **must** follow guidance in
>       [AIP-210][].
>     - User-settable IDs **should not** be permitted to be a UUID (or any value
>       that syntactically appears to be a UUID).
</blockquote></details>

If we want to completely match it, we could just use the regex in aip-122.


<!-- Sent from Reviewable.io -->

2023-06-28 20:18 UTC, tristanvuong2021 requested changes
> Reviewed 1 of 20 files at r4.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1071)* status: all files reviewed, 13 unresolved discussions (waiting on @jcorilla, @riemanli, and @SanjayVas)



<!-- Sent from Reviewable.io -->

2023-06-28 23:19 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1071)* status: 17 of 36 files reviewed, 9 unresolved discussions (waiting on @jcorilla, @SanjayVas, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/PostgresMetricsService.kt` line 56 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1071#-NZ1nxEv39imc94pQr4B:-NZ2I2R86weBmEl9vtqa:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9e5b2ba209c16d748ca2a6a42797d6ac2c4cbde9/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/PostgresMetricsService.kt#L56)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: technically only empty (the default value) means not specified. If it has whitespace it's instead a malformed value (treated similarly as if the ID was the wrong length or had invalid characters).
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/MeasurementReader.kt` line 56 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1071#-NZ1p8EJ2jWwW-Y_EJqA:-NZ2IKkVDx1GIOOY7tzd:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9e5b2ba209c16d748ca2a6a42797d6ac2c4cbde9/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/MeasurementReader.kt#L56)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This should still be `externalReportingSetId`. In this layer, `reportingSetId` implies the internal ID.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/ReportReader.kt` line 203 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1071#-NZ1q-F9CbOEEp-zbv_9:-NZ2Imlq4ubXlDMtwK3v:bh5614y) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9e5b2ba209c16d748ca2a6a42797d6ac2c4cbde9/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/ReportReader.kt#L203)):*
> If the `after` message is set, all fields should be required.

I don' think that's what @tristanvuong2021 designed. Tristan could you chime in?
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateMetrics.kt` line 79 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1071#-NZ1rge2Dv7FWlwivPIB:-NZ2f7SID-gQE32v1_T-:bpu5if0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9e5b2ba209c16d748ca2a6a42797d6ac2c4cbde9/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateMetrics.kt#L79)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Unnecessary mutability.

```kotlin
val metricsByCreateRequestId: Map<String, Metric> = 
    MetricReader(transactionContext)
      .readMetricsByRequestId(measurementConsumerId, createMetricRequestIds)
      .toList()
      .associateBy({ it.createMetricRequestId }, { it.metric })
```
</blockquote></details>

Thanks for pointing it out. Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateMetrics.kt` line 131 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1071#-NZ1tonb5dH0drasMnRd:-NZ2hEqdAKwb6rgQIk8-:b-9t75ng) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9e5b2ba209c16d748ca2a6a42797d6ac2c4cbde9/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateMetrics.kt#L131)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: Prefer regular for-in loops over `forEach` when not chaining.

Also avoid exposing the mutable collection used for building when possible. In this case [`buildSet`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/build-set.html) would help, but I think it's not available until Kotlin 1.6 we're still on 1.5 at this point :(
</blockquote></details>

Replaced `forEach`s with nested for-loops
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateReport.kt` line 65 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1071#-NZ1whIfAWDH6pbV2TxB:-NZ2iKZW9dPfTRJw0T75:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9e5b2ba209c16d748ca2a6a42797d6ac2c4cbde9/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateReport.kt#L65)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

KDoc syntax is for types, functions, and properties. This should be a regular comment.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateReport.kt` line 77 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1071#-NZ1wMll1LvcJOoThglX:-NZ2iLP29-SuaKQ9u6yY:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9e5b2ba209c16d748ca2a6a42797d6ac2c4cbde9/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateReport.kt#L77)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

KDoc syntax is for types, functions, and properties. This should be a regular comment.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateReportingSet.kt` line 64 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1071#-NZ1xFMR8kY2Zkxk-t_c:-NZ2iXIC8uYOHaJvTc0h:bpufguf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9e5b2ba209c16d748ca2a6a42797d6ac2c4cbde9/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateReportingSet.kt#L64)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This read seems unnecessary. Won't postgres return some known error code when you try to insert an entry with the same PK?
</blockquote></details>

Good point! Do you know what type of postgres exception I should catch? I can't find the list of exceptions from postgres.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateReportingSet.kt` line 304 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1071#-NZ1yuPH4w9l6r7wwZW5:-NZ2m0Hk0QJQ1Kq92nKp:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9e5b2ba209c16d748ca2a6a42797d6ac2c4cbde9/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateReportingSet.kt#L304)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: can further encapsulate mutability here
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 1457 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1071#-NZ2-IhV99h-tlwzP8pV:-NZ29-sy-L4m2Ksp_zsA:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9e5b2ba209c16d748ca2a6a42797d6ac2c4cbde9/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L1457)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: This is a `Regex` that applies generally to these resource IDs. The fact that we only check it on Cre [...]

2023-06-28 23:30 UTC, tristanvuong2021 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1071)* status: 17 of 36 files reviewed, 9 unresolved discussions (waiting on @jcorilla, @riemanli, and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/ReportReader.kt` line 203 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1071#-NZ1q-F9CbOEEp-zbv_9:-NZ3KdH3AllwZgW9AuCu:bfkrbcz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9e5b2ba209c16d748ca2a6a42797d6ac2c4cbde9/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/ReportReader.kt#L203)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

> If the `after` message is set, all fields should be required.

I don' think that's what @tristanvuong2021 designed. Tristan could you chime in?
</blockquote></details>

The suggestion is good.


<!-- Sent from Reviewable.io -->

2023-06-29 17:12 UTC, tristanvuong2021 reviewed
> Reviewed 13 of 18 files at r5, 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1071)* status: 34 of 36 files reviewed, 9 unresolved discussions (waiting on @jcorilla, @riemanli, and @SanjayVas)



<!-- Sent from Reviewable.io -->

2023-06-29 17:16 UTC, tristanvuong2021 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1071)* status: 34 of 36 files reviewed, 9 unresolved discussions (waiting on @jcorilla, @riemanli, and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateReportingSet.kt` line 64 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1071#-NZ1xFMR8kY2Zkxk-t_c:-NZ78q1_4jcq14OUSJrB:b-yjfdgp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9e5b2ba209c16d748ca2a6a42797d6ac2c4cbde9/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateReportingSet.kt#L64)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Good point! Do you know what type of postgres exception I should catch? I can't find the list of exceptions from postgres.
</blockquote></details>

I believe it would return this: https://github.com/pgjdbc/r2dbc-postgresql/blob/4fa302c1944aa89631b294a135391b4c55dc1495/src/main/java/io/r2dbc/postgresql/ExceptionFactory.java#L160C36-L160C36


<!-- Sent from Reviewable.io -->

2023-06-29 17:17 UTC, tristanvuong2021 reviewed
> Reviewed 1 of 18 files at r5.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1071)* status: 35 of 36 files reviewed, 9 unresolved discussions (waiting on @jcorilla, @riemanli, and @SanjayVas)



<!-- Sent from Reviewable.io -->

2023-06-29 18:29 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1071)* status: 35 of 36 files reviewed, 9 unresolved discussions (waiting on @jcorilla, @SanjayVas, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/ReportReader.kt` line 203 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1071#-NZ1q-F9CbOEEp-zbv_9:-NZ7Dmh28MGgP0n3xLKu:bai9git) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9e5b2ba209c16d748ca2a6a42797d6ac2c4cbde9/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/ReportReader.kt#L203)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

The suggestion is good.
</blockquote></details>

Just want to make sure we are on the same page. With the suggested change, we won't allow `filter.after.externalReportId` to be empty string when `filter.after.createTime` is set. That said, the user can't just set `filter.after.createTime` to get all reports after the time. They need to know which report is the last report when there are several reports created at the same time and set `filter.after.externalReportId` to the last report.


<!-- Sent from Reviewable.io -->

2023-06-29 19:23 UTC, tristanvuong2021 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1071)* status: 33 of 36 files reviewed, 9 unresolved discussions (waiting on @jcorilla, @riemanli, and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/ReportReader.kt` line 203 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1071#-NZ1q-F9CbOEEp-zbv_9:-NZ7afpm6Rr81ui4EFpK:befnsvg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9e5b2ba209c16d748ca2a6a42797d6ac2c4cbde9/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/ReportReader.kt#L203)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Just want to make sure we are on the same page. With the suggested change, we won't allow `filter.after.externalReportId` to be empty string when `filter.after.createTime` is set. That said, the user can't just set `filter.after.createTime` to get all reports after the time. They need to know which report is the last report when there are several reports created at the same time and set `filter.after.externalReportId` to the last report.
</blockquote></details>

The after message will always have both fields set. It hasn't been added yet, but if the user wants to filter by create_time, they can use a filter string the same way it is done for event groups.


<!-- Sent from Reviewable.io -->

2023-06-29 22:24 UTC, SanjayVas reviewed
> Reviewed 15 of 18 files at r5, 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1071)* status: 34 of 36 files reviewed, 3 unresolved discussions (waiting on @jcorilla and @riemanli)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metrics_service.proto` line 158 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1071#-NZ8DQ4UEOisjipVO92r:-NZ8DQ4UEOisjipVO92s:b-if0ro9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9d284451b2074d80e795b0f07cc4b87b413a63df/src/main/proto/wfa/measurement/reporting/v2alpha/metrics_service.proto#L158)):*
> ```proto
>   //
>   // Restricted to letters, numbers, and hyphen, with the first character a
>   // letter, the last a letter or a number, and a 63 character maximum.
> ```

nit: you can make this shorter by just referencing the standard. e.g. "This must conform to RFC 1034, with the additional restriction that all letters must be lower-case."


<!-- Sent from Reviewable.io -->

2023-06-30 00:36 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1071)* status: 26 of 36 files reviewed, 2 unresolved discussions (waiting on @jcorilla, @SanjayVas, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/ReportReader.kt` line 203 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1071#-NZ1q-F9CbOEEp-zbv_9:-NZ8_8MN1KZbDxmS4Luw:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9e5b2ba209c16d748ca2a6a42797d6ac2c4cbde9/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/ReportReader.kt#L203)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

The after message will always have both fields set. It hasn't been added yet, but if the user wants to filter by create_time, they can use a filter string the same way it is done for event groups.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/ReportReader.kt` line 206 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1071#-NZ1qgpe5XiS-SAL57-_:-NZ8_9sM4GHevAulLudI:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9e5b2ba209c16d748ca2a6a42797d6ac2c4cbde9/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/ReportReader.kt#L206)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Have the SQL itself be different if `hasAfter` is false. See the internal Kingdom [StreamEventGroups](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/06f31c65357b5e0b72de1caab79db64b00c99198/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamEventGroups.kt#L63) implementation as an example.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateReportingSet.kt` line 64 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1071#-NZ1xFMR8kY2Zkxk-t_c:-NZ8_AvS79Qu05CGzFgs:b-9wz9ie) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9e5b2ba209c16d748ca2a6a42797d6ac2c4cbde9/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateReportingSet.kt#L64)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

I believe it would return this: https://github.com/pgjdbc/r2dbc-postgresql/blob/4fa302c1944aa89631b294a135391b4c55dc1495/src/main/java/io/r2dbc/postgresql/ExceptionFactory.java#L160C36-L160C36
</blockquote></details>

Thanks for sharing! Done.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metrics_service.proto` line 158 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1071#-NZ8DQ4UEOisjipVO92r:-NZ8a-mEBS5tHMZVrx2f:b47k6nx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9d284451b2074d80e795b0f07cc4b87b413a63df/src/main/proto/wfa/measurement/reporting/v2alpha/metrics_service.proto#L158)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: you can make this shorter by just referencing the standard. e.g. "This must conform to RFC 1034, with the additional restriction that all letters must be lower-case."
</blockquote></details>

Thanks for the suggestion! Done


<!-- Sent from Reviewable.io -->

2023-06-30 00:38 UTC, tristanvuong2021 reviewed
> Reviewed 1 of 18 files at r5.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1071)* status: 26 of 36 files reviewed, 2 unresolved discussions (waiting on @jcorilla and @SanjayVas)



<!-- Sent from Reviewable.io -->

2023-06-30 17:53 UTC, SanjayVas requested changes
> Reviewed 10 of 10 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1071)* status: 34 of 36 files reviewed, 4 unresolved discussions (waiting on @jcorilla and @riemanli)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/ReportReader.kt` line 170 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1071#-NZCP-A73i0KIs84lL4E:-NZCP-A73i0KIs84lL4F:b-8hayib) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f7b17b5f4b72e3f98d8ae4e9ee5269cfc95d73e2/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/ReportReader.kt#L170)):*
> ```Kotlin
>     request: StreamReportsRequest,
>   ): Flow<Result> {
>     val fromClause =
> ```

nit: It's really just the additional predicates in the WHERE clause of the subquery that differ. Not a huge deal, but my instinct would be to minimize the duplication.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/ReportReader.kt` line 181 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1071#-NZCQ0N0Az0Vr17khDD6:-NZCQ0N0Az0Vr17khDD7:b-4hnluw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f7b17b5f4b72e3f98d8ae4e9ee5269cfc95d73e2/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/ReportReader.kt#L181)):*
> ```Kotlin
>               (CreateTime = $3
>               AND ExternalReportId > $4))
>             ORDER BY CreateTime ASC, CmmsMeasurementConsumerId ASC, ExternalReportId ASC
> ```

Do you need the ORDER BY here in the subquery given that you also have it in the outer query?
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/ReportReader.kt` line 222 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1071#-NZCQIh_1oAqMlUnxWb1:-NZCQIh_1oAqMlUnxWb2:b-u5yh6g) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f7b17b5f4b72e3f98d8ae4e9ee5269cfc95d73e2/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/ReportReader.kt#L222)):*
> ```Kotlin
>           bind("$2", request.limit)
>         } else {
>           bind("$2", 50)
> ```

Extract constant



_Code quote:_
```Kotlin
50
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateReportingSet.kt` line 83 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1071#-NZCQVOy-nY4fR_sYBNP:-NZCQVOy-nY4fR_sYBNQ:b-5s91ja) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f7b17b5f4b72e3f98d8ae4e9ee5269cfc95d73e2/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateReportingSet.kt#L83)):*
> ```Kotlin
>     try {
>       transactionContext.executeStatement(statement)
>     } catch (e: Exception) {
> ```

Can you not just catch `R2dbcDataIntegrityViolationException` or `PostgresqlDataIntegrityViolationException` as @tristanvuong2021 pointed out in the other comment?


<!-- Sent from Reviewable.io -->

2023-06-30 18:50 UTC, tristanvuong2021 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1071)* status: 34 of 36 files reviewed, 4 unresolved discussions (waiting on @jcorilla, @riemanli, and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/ReportReader.kt` line 181 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1071#-NZCQ0N0Az0Vr17khDD6:-NZCa3oF9S3cyZ16nXSU:b3nic0x) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f7b17b5f4b72e3f98d8ae4e9ee5269cfc95d73e2/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/ReportReader.kt#L181)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Do you need the ORDER BY here in the subquery given that you also have it in the outer query?
</blockquote></details>

The ORDER BY in the subquery is necessary since that is where the limit is applied.


<!-- Sent from Reviewable.io -->

2023-06-30 18:51 UTC, tristanvuong2021 reviewed
> Reviewed 9 of 10 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1071)* status: 34 of 36 files reviewed, 4 unresolved discussions (waiting on @jcorilla, @riemanli, and @SanjayVas)



<!-- Sent from Reviewable.io -->

2023-06-30 18:53 UTC, tristanvuong2021 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1071)* status: 34 of 36 files reviewed, 3 unresolved discussions (waiting on @jcorilla and @riemanli)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/ReportReader.kt` line 181 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1071#-NZCQ0N0Az0Vr17khDD6:-NZCdY3N4a5VbbLNm-eH:bc4k6e5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f7b17b5f4b72e3f98d8ae4e9ee5269cfc95d73e2/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/ReportReader.kt#L181)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

The ORDER BY in the subquery is necessary since that is where the limit is applied.
</blockquote></details>

Without the ORDER BY in the subquery, it isn't possible to get the next set of rows in the right order.


<!-- Sent from Reviewable.io -->

2023-06-30 21:41 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1071)* status: 32 of 36 files reviewed, 2 unresolved discussions (waiting on @jcorilla, @SanjayVas, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/ReportReader.kt` line 170 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1071#-NZCP-A73i0KIs84lL4E:-NZCe0SZ-6ZpFGWlMbjt:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f7b17b5f4b72e3f98d8ae4e9ee5269cfc95d73e2/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/ReportReader.kt#L170)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: It's really just the additional predicates in the WHERE clause of the subquery that differ. Not a huge deal, but my instinct would be to minimize the duplication.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/ReportReader.kt` line 222 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1071#-NZCQIh_1oAqMlUnxWb1:-NZCe7SVDmfv_OmwMHaq:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f7b17b5f4b72e3f98d8ae4e9ee5269cfc95d73e2/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/ReportReader.kt#L222)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Extract constant
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateReportingSet.kt` line 83 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1071#-NZCQVOy-nY4fR_sYBNP:-NZDEvNgAkETIamC3Jwb:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f7b17b5f4b72e3f98d8ae4e9ee5269cfc95d73e2/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateReportingSet.kt#L83)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Can you not just catch `R2dbcDataIntegrityViolationException` or `PostgresqlDataIntegrityViolationException` as @tristanvuong2021 pointed out in the other comment?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-06-30 21:49 UTC, SanjayVas requested changes
> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1071)* status: 34 of 36 files reviewed, 1 unresolved discussion (waiting on @jcorilla and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateReportingSet.kt` line 83 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1071#-NZCQVOy-nY4fR_sYBNP:-NZDGvxp20PLL7nZyowJ:by4h2oo) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f7b17b5f4b72e3f98d8ae4e9ee5269cfc95d73e2/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateReportingSet.kt#L83)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I meant in lieu of checking the error code.


<!-- Sent from Reviewable.io -->

2023-06-30 21:52 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1071)* status: 34 of 36 files reviewed, 1 unresolved discussion (waiting on @jcorilla and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateReportingSet.kt` line 83 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1071#-NZCQVOy-nY4fR_sYBNP:-NZDHLQ377ncfI_93WlW:bol2io2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f7b17b5f4b72e3f98d8ae4e9ee5269cfc95d73e2/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateReportingSet.kt#L83)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I meant in lieu of checking the error code.
</blockquote></details>

Is only checking `R2dbcDataIntegrityViolationException` enough? Based on this
https://www.postgresql.org/docs/current/errcodes-appendix.html#:~:text=Class%2023%20%E2%80%94%20Integrity,exclusion_violation, Integrity Constraint Violation contains different types of errors.


<!-- Sent from Reviewable.io -->

2023-06-30 21:57 UTC, tristanvuong2021 approved these changes
> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1071)* status: 34 of 36 files reviewed, 1 unresolved discussion (waiting on @jcorilla)



<!-- Sent from Reviewable.io -->

2023-06-30 22:30 UTC, SanjayVas requested changes
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1071)* status: 34 of 36 files reviewed, 1 unresolved discussion (waiting on @jcorilla and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateReportingSet.kt` line 83 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1071#-NZCQVOy-nY4fR_sYBNP:-NZDQEW10KwgnXDEpSlx:b-hmpb31) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f7b17b5f4b72e3f98d8ae4e9ee5269cfc95d73e2/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateReportingSet.kt#L83)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Is only checking `R2dbcDataIntegrityViolationException` enough? Based on this
https://www.postgresql.org/docs/current/errcodes-appendix.html#:~:text=Class%2023%20%E2%80%94%20Integrity,exclusion_violation, Integrity Constraint Violation contains different types of errors.
</blockquote></details>

Ah, didn't realize it was a whole class of errors. Switch to `PostgresqlDataIntegrityViolationException` so you don't need the `is PostgresqlException` check at least.


<!-- Sent from Reviewable.io -->

2023-06-30 22:32 UTC, SanjayVas requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1071)* status: 34 of 36 files reviewed, 1 unresolved discussion (waiting on @jcorilla and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateReportingSet.kt` line 83 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1071#-NZCQVOy-nY4fR_sYBNP:-NZDQhMI6Mapi0_iEDQZ:b-lnsbib) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f7b17b5f4b72e3f98d8ae4e9ee5269cfc95d73e2/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateReportingSet.kt#L83)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Ah, didn't realize it was a whole class of errors. Switch to `PostgresqlDataIntegrityViolationException` so you don't need the `is PostgresqlException` check at least.
</blockquote></details>

Ah, nevermind. Looks like that exception type isn't accessible. Same advice, but catch PostgresqlException.


<!-- Sent from Reviewable.io -->

2023-06-30 22:32 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1071)* status: 34 of 36 files reviewed, 1 unresolved discussion (waiting on @jcorilla and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateReportingSet.kt` line 83 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1071#-NZCQVOy-nY4fR_sYBNP:-NZDQdrs9pEwkmeu3gTW:bit2zez) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f7b17b5f4b72e3f98d8ae4e9ee5269cfc95d73e2/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateReportingSet.kt#L83)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Ah, didn't realize it was a whole class of errors. Switch to `PostgresqlDataIntegrityViolationException` so you don't need the `is PostgresqlException` check at least.
</blockquote></details>

I tried to use `PostgresqlDataIntegrityViolationException`, but I can't find a way to import it. IntelliJ doesn't recognize it either :(


<!-- Sent from Reviewable.io -->

2023-06-30 22:35 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1071)* status: 34 of 36 files reviewed, 1 unresolved discussion (waiting on @jcorilla and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateReportingSet.kt` line 83 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1071#-NZCQVOy-nY4fR_sYBNP:-NZDRA8B189BP5JIzm-i:b-erle9t) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f7b17b5f4b72e3f98d8ae4e9ee5269cfc95d73e2/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateReportingSet.kt#L83)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

I tried to use `PostgresqlDataIntegrityViolationException`, but I can't find a way to import it. IntelliJ doesn't recognize it either :(
</blockquote></details>

`PostgresqlException` is not throwable https://github.com/pgjdbc/r2dbc-postgresql/blob/4fa302c1944aa89631b294a135391b4c55dc1495/src/main/java/io/r2dbc/postgresql/api/PostgresqlException.java


<!-- Sent from Reviewable.io -->

2023-06-30 22:39 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1071)* status: 34 of 36 files reviewed, 1 unresolved discussion (waiting on @jcorilla and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateReportingSet.kt` line 83 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1071#-NZCQVOy-nY4fR_sYBNP:-NZDSJ5pBckCEkrFoZU5:bnyi4r1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f7b17b5f4b72e3f98d8ae4e9ee5269cfc95d73e2/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateReportingSet.kt#L83)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

`PostgresqlException` is not throwable https://github.com/pgjdbc/r2dbc-postgresql/blob/4fa302c1944aa89631b294a135391b4c55dc1495/src/main/java/io/r2dbc/postgresql/api/PostgresqlException.java
</blockquote></details>

The current implementation tries to do what this does: https://github.com/world-federation-of-advertisers/common-jvm/blob/main/src/main/kotlin/org/wfanet/measurement/common/db/r2dbc/postgres/SerializableErrors.kt#L40-L41


<!-- Sent from Reviewable.io -->

2023-06-30 23:09 UTC, SanjayVas approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1071)* status: 34 of 36 files reviewed, all discussions resolved (waiting on @jcorilla and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateReportingSet.kt` line 83 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1071#-NZCQVOy-nY4fR_sYBNP:-NZDZESy65SgN4kJ_jjZ:b-jbz7nc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f7b17b5f4b72e3f98d8ae4e9ee5269cfc95d73e2/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateReportingSet.kt#L83)):*
> `PostgresqlException` is not throwable

Well that's dumb. I guess this is the best we can do.


<!-- Sent from Reviewable.io -->

2023-06-30 23:23 UTC, tristanvuong2021 approved these changes
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1071)* status: 34 of 36 files reviewed, all discussions resolved (waiting on @jcorilla and @Marco-Premier)



<!-- Sent from Reviewable.io -->

2023-07-03 12:48 UTC, Marco-Premier approved these changes
> Reviewed 4 of 33 files at r1, 5 of 15 files at r3, 6 of 20 files at r4, 9 of 18 files at r5, 2 of 4 files at r6, 8 of 10 files at r7, 1 of 2 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1071)* status: 34 of 36 files reviewed, all discussions resolved (waiting on @jcorilla)



<!-- Sent from Reviewable.io -->

2023-07-03 21:23 UTC, riemanli reviewed
> Reviewed 4 of 33 files at r1, 5 of 15 files at r3, 6 of 20 files at r4, 9 of 18 files at r5, 2 of 4 files at r6, 8 of 10 files at r7, 1 of 2 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1071)* status: 34 of 36 files reviewed, all discussions resolved (waiting on @jcorilla)



<!-- Sent from Reviewable.io -->

2023-07-04 08:30 UTC, riemanli reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1071#-:-NZV0ULxEk8f1eTFugLs:bnfp4nl)* status: 34 of 36 files reviewed, all discussions resolved (waiting on @riemanli)



<!-- Sent from Reviewable.io -->

2023-07-04 08:31 UTC, riemanli reviewed
> Reviewed 1 of 2 files at r8.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1071)* status: 34 of 36 files reviewed, all discussions resolved (waiting on @riemanli)



<!-- Sent from Reviewable.io -->

2023-07-04 08:34 UTC, riemanli reviewed
> Reviewed 2 of 10 files at r7.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1071)* status: 34 of 36 files reviewed, all discussions resolved (waiting on @riemanli)



<!-- Sent from Reviewable.io -->

2023-07-04 08:36 UTC, riemanli reviewed
> Reviewed 29 of 33 files at r1, 5 of 5 files at r2, 10 of 15 files at r3, 14 of 20 files at r4, 9 of 18 files at r5, 2 of 4 files at r6.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1071)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @riemanli)



<!-- Sent from Reviewable.io -->

2023-07-04 08:38 UTC, riemanli commented
Due to the recent change in [AIP-133](https://google.aip.dev/133#requiring-client-settable-ids), resource ID in create method now is required.

2023-07-04 08:38 UTC, merged