Add error bars to metric result
world-federation-of-advertisers/cross-media-measurement pull request #1072
Opened 2023-06-20 23:31 UTC by riemanli

2023-06-20 23:31 UTC, wfa-reviewable commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1072)
<!-- Reviewable:end -->

2023-06-20 23:31 UTC, riemanli commented
Current dependencies on/for this PR:
* main
  * **PR #1072** <a href="https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/1072" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/1072?utm_source=stack-comment).

2023-06-21 16:39 UTC, SanjayVas requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1072)* status: all files reviewed, 3 unresolved discussions (waiting on @jcorilla, @riemanli, and @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto` line 132 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1072#-NYTmv8t7F2Or_dTTow1:-NYTmv8t7F2Or_dTTow2:bhtlwvb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2ece04955298e8725fc13aa5223f92267bbdc98a/src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto#L132)):*
> ```proto
> 
> // Error bar of a scalar value
> message ScalarErrorBar {
> ```

Can we use a more accurate term? I know this is what we've been saying in feature discussions, but an error bar refers to the *graphical* representation of error.



_Code quote:_
```proto
ErrorBar
```
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto` line 133 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1072#-NYTnMCh9RCXn3WNCplq:-NYTnMCh9RCXn3WNCplr:b-y34yv9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2ece04955298e8725fc13aa5223f92267bbdc98a/src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto#L133)):*
> ```proto
> // Error bar of a scalar value
> message ScalarErrorBar {
>   double std = 1;
> ```

Is this supposed to be standard error? Standard deviation?

Document this field. (In a public API, all field and types should be documented. api-linter will complain about this). Consider also renaming the field to be more explicit.



_Code quote:_
```proto
double std = 1;
```
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto` line 158 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1072#-NYTnvyVAI_jdpl6n0d9:-NYTnvyVAI_jdpl6n0dA:b-xwzjv8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2ece04955298e8725fc13aa5223f92267bbdc98a/src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto#L158)):*
> ```proto
>       // The result of the bin.
>       BinResult bin_result = 2;
>       // Error bar of the result at this bin
> ```

Will all of these always be set if the bin has a result? If not, document the conditions.


<!-- Sent from Reviewable.io -->

2023-06-21 17:28 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1072)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @jcorilla, @SanjayVas, and @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto` line 132 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1072#-NYTmv8t7F2Or_dTTow1:-NYTuUta3JYu8-iFB76e:b-9v4ca1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2ece04955298e8725fc13aa5223f92267bbdc98a/src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto#L132)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Can we use a more accurate term? I know this is what we've been saying in feature discussions, but an error bar refers to the *graphical* representation of error.
</blockquote></details>

Renamed to `ConfidenceInterval`
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto` line 133 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1072#-NYTnMCh9RCXn3WNCplq:-NYTvMPR8uUXqf12Bzas:b4m4cni) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2ece04955298e8725fc13aa5223f92267bbdc98a/src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto#L133)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Is this supposed to be standard error? Standard deviation?

Document this field. (In a public API, all field and types should be documented. api-linter will complain about this). Consider also renaming the field to be more explicit.
</blockquote></details>

Added document and renamed the field to `standard_deviation`
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto` line 158 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1072#-NYTnvyVAI_jdpl6n0d9:-NYTxxXkEqipg2rhlRL2:b-2amq3i) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2ece04955298e8725fc13aa5223f92267bbdc98a/src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto#L158)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Will all of these always be set if the bin has a result? If not, document the conditions.
</blockquote></details>

Yes, all of them will be set. The calculation of standard deviations in different types of frequency metrics is not trivial, so we decided to provide the standard deviations for those common frequency metrics.


<!-- Sent from Reviewable.io -->

2023-06-21 18:00 UTC, SanjayVas approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1072)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jcorilla and @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto` line 132 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1072#-NYTmv8t7F2Or_dTTow1:-NYU5bVFB3Pff0ys3bkM:bf2djar) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2ece04955298e8725fc13aa5223f92267bbdc98a/src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto#L132)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Renamed to `ConfidenceInterval`
</blockquote></details>

I suppose that's okay, but it's not actually a confidence interval but rather values you need to compute a confidence interval, right? Maybe just `Statistics` (especially if you want to leave it open to add more stats)?

If you're confident (no pun intended) that you really only need standard deviation, I'm also fine with just dropping the wrapper message type.


<!-- Sent from Reviewable.io -->

2023-06-21 19:12 UTC, kungfucraig requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1072)* status: all files reviewed, 1 unresolved discussion (waiting on @chenweiw, @jcorilla, @riemanli, and @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto` line 132 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1072#-NYUMRx83G9Jy8Eb4bb3:-NYUMRx83G9Jy8Eb4bb4:b-jlpuug) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b4b5a9a621d84a890a6a692b28c856b843977a35/src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto#L132)):*
> ```proto
> 
> // Confidence interval of a scalar value
> message ConfidenceInterval {
> ```

I'd expect a confidence interval message to have an upper and lower bound and a percent. 

I understand that we can compute a confidence interval from the standard deviation, but if that's the case, maybe we shouldn't call this confidence interval?


<!-- Sent from Reviewable.io -->

2023-06-21 19:18 UTC, riemanli commented
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto` line 132 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1072#-NYUMRx83G9Jy8Eb4bb3:-NYUNiPzDKng8T5PAyo1:b-1ju9xi) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b4b5a9a621d84a890a6a692b28c856b843977a35/src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto#L132)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

I'd expect a confidence interval message to have an upper and lower bound and a percent. 

I understand that we can compute a confidence interval from the standard deviation, but if that's the case, maybe we shouldn't call this confidence interval?
</blockquote></details>

How about `UnivariateStatistics`?


<!-- Sent from Reviewable.io -->

2023-06-21 20:06 UTC, kungfucraig reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1072)* status: all files reviewed, 1 unresolved discussion (waiting on @chenweiw, @jcorilla, @riemanli, and @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto` line 132 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1072#-NYUMRx83G9Jy8Eb4bb3:-NYUZ4Fv7WGr8TIqd-Ts:b-rrjx6x) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b4b5a9a621d84a890a6a692b28c856b843977a35/src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto#L132)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

How about `UnivariateStatistics`?
</blockquote></details>

I like it :)


<!-- Sent from Reviewable.io -->

2023-06-21 21:25 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1072)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @chenweiw, @jcorilla, @kungfucraig, @SanjayVas, and @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto` line 132 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1072#-NYTmv8t7F2Or_dTTow1:-NYUqDTh9rg-riMjPaFl:b4h8y7p) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2ece04955298e8725fc13aa5223f92267bbdc98a/src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto#L132)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I suppose that's okay, but it's not actually a confidence interval but rather values you need to compute a confidence interval, right? Maybe just `Statistics` (especially if you want to leave it open to add more stats)?

If you're confident (no pun intended) that you really only need standard deviation, I'm also fine with just dropping the wrapper message type.
</blockquote></details>

Thanks for the suggestion! I renamed it to `UnivariateStatistics`.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto` line 132 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1072#-NYUMRx83G9Jy8Eb4bb3:-NYUqD8u2Evj6RlVTNqV:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b4b5a9a621d84a890a6a692b28c856b843977a35/src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto#L132)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

I like it :)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-06-21 21:49 UTC, SanjayVas approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1072)* status: all files reviewed, 2 unresolved discussions (waiting on @chenweiw, @jcorilla, @kungfucraig, @riemanli, and @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto` line 133 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1072#-NYUvj4yAzv6oRonzUQ0:-NYUvUxN5A6AP6SospXH:b-ykc6fz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2bb5e9d05472ad22e266b4273befd7bd130dc832/src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto#L133)):*
> ```proto
> // Statistics of a scalar value
> message UnivariateStatistics {
>   // Used to find different confidence intervals.
> ```

nit: first line of comment should be a summary fragment


<!-- Sent from Reviewable.io -->

2023-06-22 05:24 UTC, Marco-Premier approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1072)* status: all files reviewed, 1 unresolved discussion (waiting on @chenweiw, @jcorilla, @kungfucraig, @SanjayVas, @stevenwarejones, and @tristanvuong2021)



<!-- Sent from Reviewable.io -->

2023-06-22 16:00 UTC, kungfucraig approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1072)* status: all files reviewed, 2 unresolved discussions (waiting on @chenweiw, @jcorilla, @riemanli, @SanjayVas, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto` line 134 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1072#-NYYpOY_6Fu-22Ym98uz:-NYYpOY_6Fu-22Ym98v-:b-pbsg7b) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9e2b48a003900eab01d5d3c912add4a46c71fe13/src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto#L134)):*
> ```proto
> message UnivariateStatistics {
>   // The standard deviation of the associated scalar variable value.
>   //
> ```

Delete the empty line?
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto` line 165 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1072#-NYYpQQ44e71RulLch07:-NYYpQQ44e71RulLch08:b-pbsg7b) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9e2b48a003900eab01d5d3c912add4a46c71fe13/src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto#L165)):*
> ```proto
>       UnivariateStatistics result_statistics = 3;
>       // Statistics of the relative result at this bin.
>       //
> ```

Delete the empty line?


<!-- Sent from Reviewable.io -->

2023-06-22 16:46 UTC, tristanvuong2021 requested changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1072)* status: all files reviewed, 3 unresolved discussions (waiting on @chenweiw, @jcorilla, @riemanli, @SanjayVas, and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto` line 168 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1072#-NYYzbBw-5r8c9LXPo-e:-NYYzbBw-5r8c9LXPo-f:b-u7rzci) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9e2b48a003900eab01d5d3c912add4a46c71fe13/src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto#L168)):*
> ```proto
>       // Relative result = (bin value) / (sum of all bin values)
>       UnivariateStatistics relative_statistics = 4;
>       // Statistics of the result sum from this bin to the last bin.
> ```

Maybe mention whether the start is inclusive or exclusive.


<!-- Sent from Reviewable.io -->

2023-06-22 16:58 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1072)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @chenweiw, @jcorilla, @Marco-Premier, @SanjayVas, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto` line 134 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1072#-NYYpOY_6Fu-22Ym98uz:-NYZ0cRy9rccHon__Usa:b-26jk6o) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9e2b48a003900eab01d5d3c912add4a46c71fe13/src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto#L134)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Delete the empty line?
</blockquote></details>

@SanjayVas please correct me if I am wrong. I remember we intentionally leave a blank between the first line summary and additional explanation.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto` line 168 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1072#-NYYzbBw-5r8c9LXPo-e:-NYZ0tRHEVzP34W_tX3e:b-bjudbj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9e2b48a003900eab01d5d3c912add4a46c71fe13/src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto#L168)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Maybe mention whether the start is inclusive or exclusive.
</blockquote></details>

Thanks for the suggestion! Done.


<!-- Sent from Reviewable.io -->

2023-06-22 17:08 UTC, tristanvuong2021 approved these changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1072)* status: all files reviewed, 2 unresolved discussions (waiting on @chenweiw, @jcorilla, @riemanli, @SanjayVas, and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2023-06-22 17:11 UTC, SanjayVas reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1072)* status: all files reviewed, 2 unresolved discussions (waiting on @chenweiw, @jcorilla, @kungfucraig, @riemanli, and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto` line 134 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1072#-NYYpOY_6Fu-22Ym98uz:-NYZ4Sh--89B3c9hFy8P:bqz4a84) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9e2b48a003900eab01d5d3c912add4a46c71fe13/src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto#L134)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

@SanjayVas please correct me if I am wrong. I remember we intentionally leave a blank between the first line summary and additional explanation.
</blockquote></details>

Yeah, that's correct. We're paralleling the documentation structure of other languages (Kotlin/Java, Python, etc). The first line is a summary fragment, followed by optional paragraphs with more information. Said paragraphs are separated by empty lines.


<!-- Sent from Reviewable.io -->

2023-06-22 18:04 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1072)* status: all files reviewed, 2 unresolved discussions (waiting on @chenweiw, @jcorilla, @kungfucraig, and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto` line 165 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1072#-NYYpQQ44e71RulLch07:-NYZGiMpBBaoujzAiE8U:bbpqllx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9e2b48a003900eab01d5d3c912add4a46c71fe13/src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto#L165)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Delete the empty line?
</blockquote></details>

Keep the empty line as discussed in the other thread.


<!-- Sent from Reviewable.io -->

2023-06-22 18:34 UTC, chenweiw reviewed
Hi Rieman, I made a couple of comments about naming following your suggestion. They are all minor. I will click approve if you think the current/revised naming is ok.

2023-06-22 18:34 UTC, chenweiw commented on src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto
> +message UnivariateStatistics {
Regarding the naming, a statistic is a function mapping a set of values to another value, and statistics can include, e.g., mean, std, variance, etc. Here, it seems we only use it for std? If yes, then maybe just call it UnivariateStandardDeviation? But if we will include more statistics, then the current name is better.

2023-06-22 18:34 UTC, chenweiw commented on src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto
> +    UnivariateStatistics statistics = 2;
Similar to the last comment, the variable name "statistics" might be a little bit confusing.

2023-06-22 18:34 UTC, chenweiw commented on src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto
> +      UnivariateStatistics result_statistics = 3;
Similar to the last comment about the name "statistics" and hereinafter.

2023-06-22 18:34 UTC, chenweiw commented on src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto
> +      UnivariateStatistics cumulative_after_statistics = 5;
In probability, usually "cumulative" means counting from the value at the most left-hand side to the current value (inclusive). But this is very minor.

2023-06-22 18:34 UTC, chenweiw commented on src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto
>  message MetricResult {
Regarding the naming, do you think MetricValue or MetricValues (and hereinafter) is better? As it is very common to say calculating the value of a metric, or metric value, or calculation result. But I do not have a strong preference. You can decide it.

2023-06-22 21:12 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1072)* status: all files reviewed, 7 unresolved discussions (waiting on @chenweiw, @jcorilla, @kungfucraig, and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto` line 132 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1072#gh-1238874542:-NYZrAlQCZaGZ3KubUj3:bhpm1pt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1cdec79919e1554e206fe14b9c459c280a9d985e/src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto#L132)):*
<details><summary><i>Previously, chenweiw wrote…</i></summary><blockquote>

Regarding the naming, a statistic is a function mapping a set of values to another value, and statistics can include, e.g., mean, std, variance, etc. Here, it seems we only use it for std? If yes, then maybe just call it UnivariateStandardDeviation? But if we will include more statistics, then the current name is better.
</blockquote></details>

Here I am trying to make it general in case we need to add some other statistic values in the future.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto` line 140 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1072#gh-1238894673:-NYZs7FP5ql9mkstz4el:b-bm2af1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1cdec79919e1554e206fe14b9c459c280a9d985e/src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto#L140)):*
<details><summary><i>Previously, chenweiw wrote…</i></summary><blockquote>

Regarding the naming, do you think MetricValue or MetricValues (and hereinafter) is better? As it is very common to say calculating the value of a metric, or metric value, or calculation result. But I do not have a strong preference. You can decide it.
</blockquote></details>

I think it makes sense to use `MetricResult` as it contains not only the calculation value but also the statistics of the metric.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto` line 146 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1072#gh-1238875957:-NYZtWET8bWcTfnhoN6Q:b20amfn) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1cdec79919e1554e206fe14b9c459c280a9d985e/src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto#L146)):*
<details><summary><i>Previously, chenweiw wrote…</i></summary><blockquote>

Similar to the last comment, the variable name "statistics" might be a little bit confusing.
</blockquote></details>

Please see my response in the other thread.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto` line 163 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1072#gh-1238877960:-NYZrzPk94Cyw3rufEbR:b20amfn) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1cdec79919e1554e206fe14b9c459c280a9d985e/src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto#L163)):*
<details><summary><i>Previously, chenweiw wrote…</i></summary><blockquote>

Similar to the last comment about the name "statistics" and hereinafter. 
</blockquote></details>

Please see my response in the other thread.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto` line 170 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1072#gh-1238889266:-NYZvppq99upITSUkvRK:bcu0klh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1cdec79919e1554e206fe14b9c459c280a9d985e/src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto#L170)):*
<details><summary><i>Previously, chenweiw wrote…</i></summary><blockquote>

In probability, usually "cumulative" means counting from the value at the most left-hand side to the current value (inclusive). But this is very minor.
</blockquote></details>

I tried to avoid the confusion by adding `after` in the name :P  Is there a better name for it to you knowledge?


<!-- Sent from Reviewable.io -->

2023-06-22 22:17 UTC, chenweiw commented
> I tried to avoid the confusion by adding `after` in the name :P Is there a better name for it to you knowledge?

We can say "Suffix Sum" or "Postfix Sum". I think the former is more widely used.

2023-06-23 08:49 UTC, Marco-Premier approved these changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1072)* status: all files reviewed, 7 unresolved discussions (waiting on @chenweiw, @jcorilla, @kungfucraig, and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2023-06-23 15:26 UTC, kungfucraig requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1072)* status: all files reviewed, 5 unresolved discussions (waiting on @chenweiw, @jcorilla, and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto` line 132 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1072#gh-1238874542:-NYcqe2c0VqgVCZo_2Sm:bw51a5r) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1cdec79919e1554e206fe14b9c459c280a9d985e/src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto#L132)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Here I am trying to make it general in case we need to add some other statistic values in the future.
</blockquote></details>

+1 on future proofing
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto` line 170 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1072#gh-1238889266:-NYcr8Wt7dxL3ESP8ZdS:b-nmc91m) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1cdec79919e1554e206fe14b9c459c280a9d985e/src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto#L170)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

I tried to avoid the confusion by adding `after` in the name :P  Is there a better name for it to you knowledge?
</blockquote></details>

Is it reasonable to return the cumulative stat from the first bin to the current bin vs. the current bin to the last bin and then update the variable names accordingly?


<!-- Sent from Reviewable.io -->

2023-06-23 16:29 UTC, riemanli reviewed
Thanks for the suggestion!

> Dismissed @chenweiw from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1072#-:-NYd4UnwEl-_j07EEfQd:b-h5rv17)* status: all files reviewed, 4 unresolved discussions (waiting on @chenweiw, @jcorilla, and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto` line 170 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1072#gh-1238889266:-NYd2f7N7UydnBRS_hA2:b-jz1ze5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1cdec79919e1554e206fe14b9c459c280a9d985e/src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto#L170)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Is it reasonable to return the cumulative stat from the first bin to the current bin vs. the current bin to the last bin and then update the variable names accordingly?
</blockquote></details>

The main purpose of serving the stats from the current bin to the last bin is for the use case of K+ reach or K+ relative reach. With a reach-freq histogram, the user can compute the K+ reach-freq histogram by doing suffix sum, and `cumulative_after_statistics` (or `suffix_sum_statistics` suggested by Chenwei) can then be used accordingly. 


<!-- Sent from Reviewable.io -->

2023-06-23 17:12 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1072)* status: all files reviewed, 4 unresolved discussions (waiting on @chenweiw, @jcorilla, and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto` line 170 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1072#gh-1238889266:-NYdE8i24_xfX3t7lD33:b-iddgqf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1cdec79919e1554e206fe14b9c459c280a9d985e/src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto#L170)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

The main purpose of serving the stats from the current bin to the last bin is for the use case of K+ reach or K+ relative reach. With a reach-freq histogram, the user can compute the K+ reach-freq histogram by doing suffix sum, and `cumulative_after_statistics` (or `suffix_sum_statistics` suggested by Chenwei) can then be used accordingly. 
</blockquote></details>

Offline discussion: will change the name to indicate the purpose of it is for K+ reach and add comment to explain K+ reach.


<!-- Sent from Reviewable.io -->

2023-06-23 20:16 UTC, kungfucraig approved these changes
> Reviewed 1 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1072)* status: 1 of 3 files reviewed, 4 unresolved discussions (waiting on @chenweiw, @jcorilla, @Marco-Premier, @stevenwarejones, and @tristanvuong2021)



<!-- Sent from Reviewable.io -->

2023-06-23 20:22 UTC, chenweiw approved these changes
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1072)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jcorilla and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2023-06-23 20:51 UTC, SanjayVas approved these changes
> Reviewed 1 of 3 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1072)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jcorilla and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2023-06-26 18:28 UTC, merged