Kingdom supports creating ROLLv2 Measurements.
world-federation-of-advertisers/cross-media-measurement pull request #1097
Opened 2023-07-11 18:40 UTC by renjiezh

2023-07-11 18:40 UTC, wfa-reviewable commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1097)
<!-- Reviewable:end -->

2023-07-11 22:21 UTC, renjiezh commented
Depends on https://github.com/world-federation-of-advertisers/cross-media-measurement-api/pull/157

2023-07-11 22:53 UTC, SanjayVas requested changes
> Reviewed 4 of 30 files at r1, 1 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1097)* status: 5 of 34 files reviewed, 4 unresolved discussions (waiting on @kungfucraig, @ple13, and @renjiezh)

___
*[`src/main/proto/wfa/measurement/internal/kingdom/protocol_config.proto` line 39 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1097#-N_658qe-bPouQ-pME0r:-N_658qe-bPouQ-pME0s:b-e4i4xd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c9fbd79c0ee12e46dee7e92c4c1eef18f95b649b/src/main/proto/wfa/measurement/internal/kingdom/protocol_config.proto#L39)):*
> ```proto
>   }
> 
>   // Configuration for the Liquid Legions v2 R/F protocol.
> ```

I believe this comment is no longer accurate, since this applies to both the reach-only and R/F protocols.



_Suggestion:_
```proto
Liquid Legions v2 protocols
```
___
*[`src/main/proto/wfa/measurement/internal/kingdom/protocol_configs.proto` line 25 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1097#-N_68gYT17ydUVRYtRfl:-N_68gYUCDRHQLt3Lfvp:bar8wb0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c9fbd79c0ee12e46dee7e92c4c1eef18f95b649b/src/main/proto/wfa/measurement/internal/kingdom/protocol_configs.proto#L25)):*
> ```proto
> option java_multiple_files = true;
> 
> // The kingdom local config proto used to initialize the `ProtocolConfig` and
> ```

Do we actually need any changes here?

1. It looks like we actually use the same configuration for both aside from max frequency, which we document as being ignored for RO.
2. Even if we did want different configurations, I assume they can use the same message type.
___
*[`src/main/proto/wfa/measurement/internal/kingdom/protocol_configs.proto` line 27 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1097#-N_65Tvt28aei_BZPifn:-N_65Tvt28aei_BZPifo:b-kafxwe) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c9fbd79c0ee12e46dee7e92c4c1eef18f95b649b/src/main/proto/wfa/measurement/internal/kingdom/protocol_configs.proto#L27)):*
> ```proto
> // The kingdom local config proto used to initialize the `ProtocolConfig` and
> // `DuchyProtocolConfig` for the LLV2 protocol.
> message Llv2ProtocolConfigs {
> ```

Despite the repetition, I think the original name helped avoid confusion between this and the `ProtocolConfig` types. This is message for configuring `ProtocolConfig`s, hence `ProtocolConfigConfig`.
___
*[`src/main/proto/wfa/measurement/internal/kingdom/protocol_configs.proto` line 37 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1097#-N_67n0KBjrQOklscyWl:-N_66HfQ33AancOccBxf:blwiyqw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c9fbd79c0ee12e46dee7e92c4c1eef18f95b649b/src/main/proto/wfa/measurement/internal/kingdom/protocol_configs.proto#L37)):*
> ```proto
> // The kingdom local config proto used to initialize the `ProtocolConfig` and
> // `DuchyProtocolConfig` for the ROLLV2 protocol.
> message Rollv2ProtocolConfigs {
> ```

The protocol name is "Reach-only Liquid Legions v2". If we abbreviate "reach-only" to RO and "Liquid Legions v2" to LLv2, then I think our [camel-casing rules](https://developer.android.com/kotlin/style-guide#camel_case) would make this `RoLlV2`. Maybe it would be better to spell it out to get `ReachOnlyLlV2`? Of course if we do this, then we should also fix the casing on the other message.



_Suggestion:_
```proto
ReachOnlyLlV2
```


<!-- Sent from Reviewable.io -->

2023-07-11 23:13 UTC, renjiezh reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1097)* status: 5 of 34 files reviewed, 4 unresolved discussions (waiting on @kungfucraig, @ple13, and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/internal/kingdom/protocol_configs.proto` line 25 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1097#-N_68gYT17ydUVRYtRfl:-N_6ArE8EHv0TAtTkeix:b-9b7jj4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c9fbd79c0ee12e46dee7e92c4c1eef18f95b649b/src/main/proto/wfa/measurement/internal/kingdom/protocol_configs.proto#L25)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Do we actually need any changes here?

1. It looks like we actually use the same configuration for both aside from max frequency, which we document as being ignored for RO.
2. Even if we did want different configurations, I assume they can use the same message type.
</blockquote></details>

You are right. Rollv2 and llv2 share the same message types exception the max_frequency. I was trying to reuse llv2's message types in `oneof`. I can update here to reuse it as well. 
However, in public api, I avoid to reuse the message type.
___
*[`src/main/proto/wfa/measurement/internal/kingdom/protocol_configs.proto` line 27 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1097#-N_65Tvt28aei_BZPifn:-N_6AGiiB7Gt_v3KATu_:b-tkjcl4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c9fbd79c0ee12e46dee7e92c4c1eef18f95b649b/src/main/proto/wfa/measurement/internal/kingdom/protocol_configs.proto#L27)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Despite the repetition, I think the original name helped avoid confusion between this and the `ProtocolConfig` types. This is message for configuring `ProtocolConfig`s, hence `ProtocolConfigConfig`.
</blockquote></details>

I was thinking that xxxConfigConfig is kinda strange. Then I realize this class is a collection of config values thus rename it to configs. 
I can rename it back to configconfig.


<!-- Sent from Reviewable.io -->

2023-07-12 15:45 UTC, kungfucraig requested changes
> Reviewed 1 of 30 files at r1, 1 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1097)* status: 6 of 34 files reviewed, 5 unresolved discussions (waiting on @ple13, @renjiezh, and @SanjayVas)

___
*[`src/main/k8s/testing/secretfiles/BUILD.bazel` line 174 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1097#-N_9iXI951MA5avqY07H:-N_9iXI951MA5avqY07I:b-d0ufy3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c9fbd79c0ee12e46dee7e92c4c1eef18f95b649b/src/main/k8s/testing/secretfiles/BUILD.bazel#L174)):*
> ```Starlark
>     "aggregator_protocols_setup_config.textproto",
>     "non_aggregator_protocols_setup_config.textproto",
>     "llv2_protocol_configs.textproto",
> ```

Should there be a new line in this file for the rollv2 config?
___
*[`src/main/proto/wfa/measurement/internal/kingdom/protocol_configs.proto` line 27 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1097#-N_65Tvt28aei_BZPifn:-N_9hwWxBn9p2AFN6bpz:b-xq9da6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c9fbd79c0ee12e46dee7e92c4c1eef18f95b649b/src/main/proto/wfa/measurement/internal/kingdom/protocol_configs.proto#L27)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

I was thinking that xxxConfigConfig is kinda strange. Then I realize this class is a collection of config values thus rename it to configs. 
I can rename it back to configconfig.
</blockquote></details>

I'd prefer that we keep the previous name and continue to use that convention. 

And, if we really want to change the convention, it should be in a different PR. 


<!-- Sent from Reviewable.io -->

2023-07-12 18:28 UTC, renjiezh reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1097)* status: 1 of 34 files reviewed, 5 unresolved discussions (waiting on @kungfucraig, @ple13, @renjiezh, and @SanjayVas)

___
*[`src/main/k8s/testing/secretfiles/BUILD.bazel` line 174 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1097#-N_9iXI951MA5avqY07H:-N_A2iQV2Z8mbn9cURcf:b-kuf5sn) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c9fbd79c0ee12e46dee7e92c4c1eef18f95b649b/src/main/k8s/testing/secretfiles/BUILD.bazel#L174)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Should there be a new line in this file for the rollv2 config?
</blockquote></details>

Nice catch! Thanks.
___
*[`src/main/proto/wfa/measurement/internal/kingdom/protocol_config.proto` line 39 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1097#-N_658qe-bPouQ-pME0r:-N_ALy9KDpemIPRiokgV:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c9fbd79c0ee12e46dee7e92c4c1eef18f95b649b/src/main/proto/wfa/measurement/internal/kingdom/protocol_config.proto#L39)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I believe this comment is no longer accurate, since this applies to both the reach-only and R/F protocols.
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/internal/kingdom/protocol_configs.proto` line 25 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1097#-N_68gYT17ydUVRYtRfl:-N_ALyix4dhCxfCB1nPT:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c9fbd79c0ee12e46dee7e92c4c1eef18f95b649b/src/main/proto/wfa/measurement/internal/kingdom/protocol_configs.proto#L25)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

You are right. Rollv2 and llv2 share the same message types exception the max_frequency. I was trying to reuse llv2's message types in `oneof`. I can update here to reuse it as well. 
However, in public api, I avoid to reuse the message type.
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/internal/kingdom/protocol_configs.proto` line 27 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1097#-N_65Tvt28aei_BZPifn:-N_AM0FmALSRMhzRA_r7:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c9fbd79c0ee12e46dee7e92c4c1eef18f95b649b/src/main/proto/wfa/measurement/internal/kingdom/protocol_configs.proto#L27)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

I'd prefer that we keep the previous name and continue to use that convention. 

And, if we really want to change the convention, it should be in a different PR. 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-07-12 19:07 UTC, renjiezh commented on src/main/k8s/testing/secretfiles/rollv2_protocol_config_config.textproto
> +# proto-message: Llv2ProtocolConfigConfig
Comment: reuse

2023-07-12 19:48 UTC, kungfucraig requested changes
> Reviewed 6 of 30 files at r1, 10 of 16 files at r2, 1 of 3 files at r3, 16 of 17 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1097)* status: all files reviewed, 7 unresolved discussions (waiting on @ple13, @renjiezh, and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/system/v1alpha/computation.proto` line 173 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1097#-N_Acmlx6wdVJHPvTndL:-N_Acmly0n3J9NBWTyhZ:b-qte7ke) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8a160a05eacd4cc364588afae75dd509b1b07699/src/main/proto/wfa/measurement/system/v1alpha/computation.proto#L173)):*
> ```proto
>       //
>       // Must only be set when the measurement type is REACH.
>       LiquidLegionsV2 reach_only_liquid_legions_v2 = 2;
> ```

We don't want to use a specific ReachOnly proto here?
___
*[`src/main/k8s/testing/secretfiles/rollv2_protocol_config_config.textproto` line 2 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1097#-N_AQFkT8GPPdWJOipcI:-N_AQFkT8GPPdWJOipcJ:bg9v4b0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/76740fefda3410ab4f68049927f98ff8ea00e46e/src/main/k8s/testing/secretfiles/rollv2_protocol_config_config.textproto#L2)):*
> ```
> # proto-file: src/main/proto/wfa/measurement/internal/kingdom/protocol_config_config.proto
> # proto-message: Llv2ProtocolConfigConfig
> ```

Should this reference the Rollv2ProtocolConfigConfig?


<!-- Sent from Reviewable.io -->

2023-07-12 19:56 UTC, renjiezh reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1097)* status: all files reviewed, 7 unresolved discussions (waiting on @kungfucraig, @ple13, and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/system/v1alpha/computation.proto` line 173 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1097#-N_Acmlx6wdVJHPvTndL:-N_Adqje2F5i2P_70_xo:b-2jlb87) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8a160a05eacd4cc364588afae75dd509b1b07699/src/main/proto/wfa/measurement/system/v1alpha/computation.proto#L173)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

We don't want to use a specific ReachOnly proto here?
</blockquote></details>

There are several places that we could create separated Message type for reach-only protocol. However, llv2's message types contains all fields that reach-only needs. So I try to reuse them as possible by omitting fields like `max_frequency` or `sampling_indicator_size`. We can make change if we find reach-only messages has more fields as it is easy to change the internal proto. (public proto has specific message types for reach-only).
Please let me know if you think it is better to create specific message types for reach-only internal proto. I was just try to reduce the amount of change.


<!-- Sent from Reviewable.io -->

2023-07-12 19:58 UTC, ple13 requested changes
> Reviewed 6 of 30 files at r1, 10 of 16 files at r2, 1 of 3 files at r3, 16 of 17 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1097)* status: all files reviewed, 10 unresolved discussions (waiting on @kungfucraig, @renjiezh, and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/ProtocolConfig.kt` line 1 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1097#-N_AZhyc0jUdblS_js2P:-N_AZhyc0jUdblS_js2Q:bjrz3q8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8a160a05eacd4cc364588afae75dd509b1b07699/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/ProtocolConfig.kt#L1)):*
> ```Kotlin
> // Copyright 2021 The Cross-Media Measurement Authors
> ```

Do we need to change the year?
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt` line 670 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1097#-N_AcKogBEsMMZevgUm-:-N_AcKogBEsMMZevgUm0:b-ivfkaw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8a160a05eacd4cc364588afae75dd509b1b07699/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt#L670)):*
> ```Kotlin
>       @Suppress("WHEN_ENUM_CAN_BE_NULL_IN_JAVA") // Proto enum fields are never null.
>       when (measurementSpecProto.measurementTypeCase) {
>         MeasurementSpec.MeasurementTypeCase.REACH -> {
> ```

Do we want to keep this legacy reach only until the reach only has been fully implemented? It could be useful for testing and for comparison later.
___
*[`src/main/k8s/testing/secretfiles/rollv2_protocol_config_config.textproto` line 2 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1097#-N_AYsS039q4uWzSHzsF:-N_AYsS039q4uWzSHzsG:b4weq71) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8a160a05eacd4cc364588afae75dd509b1b07699/src/main/k8s/testing/secretfiles/rollv2_protocol_config_config.textproto#L2)):*
> ```
> # proto-file: src/main/proto/wfa/measurement/internal/kingdom/protocol_config_config.proto
> # proto-message: Llv2ProtocolConfigConfig
> ```

Is it Llv2ProtocolConfigConfig or Rollv2ProtocolConfigConfig here?


<!-- Sent from Reviewable.io -->

2023-07-12 20:05 UTC, kungfucraig approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1097)* status: all files reviewed, 10 unresolved discussions (waiting on @ple13, @renjiezh, and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/system/v1alpha/computation.proto` line 173 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1097#-N_Acmlx6wdVJHPvTndL:-N_AhJs58cjpzWrHAwl3:b-eofw9o) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8a160a05eacd4cc364588afae75dd509b1b07699/src/main/proto/wfa/measurement/system/v1alpha/computation.proto#L173)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

There are several places that we could create separated Message type for reach-only protocol. However, llv2's message types contains all fields that reach-only needs. So I try to reuse them as possible by omitting fields like `max_frequency` or `sampling_indicator_size`. We can make change if we find reach-only messages has more fields as it is easy to change the internal proto. (public proto has specific message types for reach-only).
Please let me know if you think it is better to create specific message types for reach-only internal proto. I was just try to reduce the amount of change.
</blockquote></details>

I called this out because it was part of an API. @SanjayVas I'll defer to you.


<!-- Sent from Reviewable.io -->

2023-07-12 20:58 UTC, renjiezh reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1097)* status: src/main/k8s/testing/secretfiles/rollv2_protocol_config_config.textproto unreviewed, src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/ProtocolConfig.kt unreviewed, 32 of 34 files reviewed, 8 unresolved discussions (waiting on @kungfucraig, @ple13, @renjiezh, and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/ProtocolConfig.kt` line 1 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1097#-N_AZhyc0jUdblS_js2P:-N_AtLty5_yIOMnGOwEZ:bxq2hv9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8a160a05eacd4cc364588afae75dd509b1b07699/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/ProtocolConfig.kt#L1)):*
<details><summary><i>Previously, ple13 (Phi) wrote…</i></summary><blockquote>

Do we need to change the year?
</blockquote></details>

Done.
Thanks for catching it.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt` line 670 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1097#-N_AcKogBEsMMZevgUm-:-N_AsSgAD5Imbi5Vghje:bcmd4dy) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8a160a05eacd4cc364588afae75dd509b1b07699/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt#L670)):*
<details><summary><i>Previously, ple13 (Phi) wrote…</i></summary><blockquote>

Do we want to keep this legacy reach only until the reach only has been fully implemented? It could be useful for testing and for comparison later.
</blockquote></details>

Sorry I might not fully understand your point. 
The lines below are a if-else statement to determine if we use new protocol or not. So far we will not enable it.
___
*[`src/main/k8s/testing/secretfiles/rollv2_protocol_config_config.textproto` line 2 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1097#-N_AQFkT8GPPdWJOipcI:-N_AtEL5-WGMexDLHEfn:b-963hgs) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/76740fefda3410ab4f68049927f98ff8ea00e46e/src/main/k8s/testing/secretfiles/rollv2_protocol_config_config.textproto#L2)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Should this reference the Rollv2ProtocolConfigConfig?
</blockquote></details>

Added comment to eliminate the confusion.
___
*[`src/main/k8s/testing/secretfiles/rollv2_protocol_config_config.textproto` line 2 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1097#-N_AYsS039q4uWzSHzsF:-N_At9dk0Wl0xjZO94jb:b-963hgs) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8a160a05eacd4cc364588afae75dd509b1b07699/src/main/k8s/testing/secretfiles/rollv2_protocol_config_config.textproto#L2)):*
<details><summary><i>Previously, ple13 (Phi) wrote…</i></summary><blockquote>

Is it Llv2ProtocolConfigConfig or Rollv2ProtocolConfigConfig here?
</blockquote></details>

Added comment to eliminate the confusion.


<!-- Sent from Reviewable.io -->

2023-07-12 21:17 UTC, ple13 approved these changes
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1097)* status: all files reviewed, 5 unresolved discussions (waiting on @kungfucraig, @renjiezh, and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt` line 670 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1097#-N_AcKogBEsMMZevgUm-:-N_AxQLb-_z-rWeDOu3k:by6to5k) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8a160a05eacd4cc364588afae75dd509b1b07699/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt#L670)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

Sorry I might not fully understand your point. 
The lines below are a if-else statement to determine if we use new protocol or not. So far we will not enable it.
</blockquote></details>

Ah sorry. I didn't pay attention to the following lines..


<!-- Sent from Reviewable.io -->

2023-07-12 22:18 UTC, SanjayVas requested changes
> Reviewed 1 of 30 files at r1, 5 of 16 files at r2, 1 of 3 files at r3, 9 of 17 files at r4, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1097)* status: all files reviewed, 3 unresolved discussions (waiting on @kungfucraig and @renjiezh)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/ProtocolConfig.kt` line 1 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1097#-N_B8T2z3F3b36LFClo0:-N_B8T2z3F3b36LFClo1:b21rmuq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9efeb30a758bda72fa0a07192ef26d8b481c31ca/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/ProtocolConfig.kt#L1)):*
> ```Kotlin
> // Copyright 2023 The Cross-Media Measurement Authors
> ```

Why was this file renamed? It still has the same top-level object.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/server/V2alphaPublicApiServer.kt` line 88 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1097#-N_B55gvElKLRkgPYDPD:-N_B55gvElKLRkgPYDPE:b-lvyjo3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9efeb30a758bda72fa0a07192ef26d8b481c31ca/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/server/V2alphaPublicApiServer.kt#L88)):*
Copied from another comment:

> The protocol name is "Reach-only Liquid Legions v2". If we abbreviate "reach-only" to RO and "Liquid Legions v2" to LLv2, then I think our [camel-casing rules](https://developer.android.com/kotlin/style-guide#camel_case) would make this `RoLlV2`. Maybe it would be better to spell it out to get `ReachOnlyLlV2`?

The existing type incorrectly keeps the `v` as lowercase. If we're renaming the other class to follow the proper camel casing rules, then this should be `RoLlV2` (upper) and `roLlV2` (lower). If we're not renaming the other class then this should be `RoLlv2` (upper) and `roLlv2` (lower).



_Code quote:_
```Kotlin
@CommandLine.Mixin rollv2ProtocolConfigFlags: Rollv2ProtocolConfigFlags,
```


<!-- Sent from Reviewable.io -->

2023-07-12 22:37 UTC, kungfucraig reviewed
> Reviewed 1 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1097)* status: all files reviewed, 2 unresolved discussions (waiting on @renjiezh and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/ProtocolConfig.kt` line 1 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1097#-N_B8T2z3F3b36LFClo0:-N_BEy3i5ym1lYttYFtj:bfgaglj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9efeb30a758bda72fa0a07192ef26d8b481c31ca/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/ProtocolConfig.kt#L1)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Why was this file renamed? It still has the same top-level object.
</blockquote></details>

I think it has two top level objects since being renamed.


<!-- Sent from Reviewable.io -->

2023-07-12 22:58 UTC, SanjayVas requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1097)* status: all files reviewed, 2 unresolved discussions (waiting on @kungfucraig and @renjiezh)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/ProtocolConfig.kt` line 1 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1097#-N_B8T2z3F3b36LFClo0:-N_BJl1iA2IiD1fRwgDm:b-bckedk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9efeb30a758bda72fa0a07192ef26d8b481c31ca/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/ProtocolConfig.kt#L1)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

I think it has two top level objects since being renamed.
</blockquote></details>

I think it would be better to have two files then.


<!-- Sent from Reviewable.io -->

2023-07-13 14:45 UTC, kungfucraig requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1097)* status: all files reviewed, 2 unresolved discussions (waiting on @renjiezh and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/ProtocolConfig.kt` line 1 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1097#-N_B8T2z3F3b36LFClo0:-N_Eh_UtAatM4X8gRB6v:bhkvp0a) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9efeb30a758bda72fa0a07192ef26d8b481c31ca/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/ProtocolConfig.kt#L1)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I think it would be better to have two files then.
</blockquote></details>

Fair point. :)


<!-- Sent from Reviewable.io -->

2023-07-13 17:45 UTC, renjiezh reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1097)* status: 16 of 35 files reviewed, 2 unresolved discussions (waiting on @kungfucraig, @ple13, and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/server/V2alphaPublicApiServer.kt` line 88 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1097#-N_B55gvElKLRkgPYDPD:-N_FLpT-0YJ88BoZqEgG:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9efeb30a758bda72fa0a07192ef26d8b481c31ca/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/server/V2alphaPublicApiServer.kt#L88)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Copied from another comment:

> The protocol name is "Reach-only Liquid Legions v2". If we abbreviate "reach-only" to RO and "Liquid Legions v2" to LLv2, then I think our [camel-casing rules](https://developer.android.com/kotlin/style-guide#camel_case) would make this `RoLlV2`. Maybe it would be better to spell it out to get `ReachOnlyLlV2`?

The existing type incorrectly keeps the `v` as lowercase. If we're renaming the other class to follow the proper camel casing rules, then this should be `RoLlV2` (upper) and `roLlV2` (lower). If we're not renaming the other class then this should be `RoLlv2` (upper) and `roLlv2` (lower).
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/ProtocolConfig.kt` line 1 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1097#-N_B8T2z3F3b36LFClo0:-N_FLqsv1LLYBOmj3OIR:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9efeb30a758bda72fa0a07192ef26d8b481c31ca/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/ProtocolConfig.kt#L1)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Fair point. :)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-07-13 18:03 UTC, kungfucraig approved these changes
> Reviewed 19 of 19 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1097)* status: all files reviewed, 2 unresolved discussions (waiting on @SanjayVas)



<!-- Sent from Reviewable.io -->

2023-07-13 21:01 UTC, SanjayVas reviewed
> Reviewed 1 of 30 files at r1, 17 of 19 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1097)* status: all files reviewed, 1 unresolved discussion (waiting on @renjiezh)

___
*[`src/main/proto/wfa/measurement/system/v1alpha/computation.proto` line 173 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1097#-N_Acmlx6wdVJHPvTndL:-N_G1ucc-hpvzfBWWyK9:bk6hg9k) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8a160a05eacd4cc364588afae75dd509b1b07699/src/main/proto/wfa/measurement/system/v1alpha/computation.proto#L173)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

I called this out because it was part of an API. @SanjayVas I'll defer to you.
</blockquote></details>

This is a tricky one. My thought is that if we have the same top-level field, then we don't need separate message types. Since there are two fields here, it makes sense to do separate message types. My inclination would be to factor out what is in common, or compose one inside the other if the R/F protocol config is basically the RO protocol + frequency params.


<!-- Sent from Reviewable.io -->

2023-07-13 21:13 UTC, renjiezh reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1097)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/proto/wfa/measurement/system/v1alpha/computation.proto` line 173 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1097#-N_Acmlx6wdVJHPvTndL:-N_G49Ty5uIR51MXL6iZ:b-4s6enm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8a160a05eacd4cc364588afae75dd509b1b07699/src/main/proto/wfa/measurement/system/v1alpha/computation.proto#L173)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This is a tricky one. My thought is that if we have the same top-level field, then we don't need separate message types. Since there are two fields here, it makes sense to do separate message types. My inclination would be to factor out what is in common, or compose one inside the other if the R/F protocol config is basically the RO protocol + frequency params.
</blockquote></details>

Thanks for sharing the idea. So far the only diff between llv2 and rollv2 is max_fequency here. I feels it is fine for rollv2 to piggyback llv2's message type as they are from the same family of protocols. In the future, if the difference expands, I will do the extraction and refactoring. 


<!-- Sent from Reviewable.io -->

2023-07-14 15:38 UTC, kungfucraig approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1097)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)



<!-- Sent from Reviewable.io -->

2023-07-17 15:59 UTC, renjiezh reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1097)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/proto/wfa/measurement/internal/kingdom/protocol_configs.proto` line 37 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1097#-N_67n0KBjrQOklscyWl:-N_6Bbm3ADqrhBl_qmMB:b-9d70zl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c9fbd79c0ee12e46dee7e92c4c1eef18f95b649b/src/main/proto/wfa/measurement/internal/kingdom/protocol_configs.proto#L37)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The protocol name is "Reach-only Liquid Legions v2". If we abbreviate "reach-only" to RO and "Liquid Legions v2" to LLv2, then I think our [camel-casing rules](https://developer.android.com/kotlin/style-guide#camel_case) would make this `RoLlV2`. Maybe it would be better to spell it out to get `ReachOnlyLlV2`? Of course if we do this, then we should also fix the casing on the other message.
</blockquote></details>

Done.
Renamed.


<!-- Sent from Reviewable.io -->

2023-07-17 16:35 UTC, SanjayVas approved these changes
> Reviewed 3 of 30 files at r1, 3 of 16 files at r2, 4 of 17 files at r4, 2 of 19 files at r7.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1097)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @renjiezh)



<!-- Sent from Reviewable.io -->

2023-07-17 17:30 UTC, Marco-Premier approved these changes
> Reviewed 5 of 30 files at r1, 3 of 16 files at r2, 8 of 17 files at r4, 19 of 19 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1097)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @renjiezh)



<!-- Sent from Reviewable.io -->

2023-07-17 19:25 UTC, merged

2023-07-19 18:54 UTC, SanjayVas commented
This appears to have broken K8s dev configuration.

```
java.io.FileNotFoundException: /var/run/secrets/files/ro_llv2_protocol_config_config.textproto (No such file or directory)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at org.wfanet.measurement.kingdom.deploy.common.RoLlv2ProtocolConfig.initializeFromFlags(RoLlv2ProtocolConfig.kt:45)
	at org.wfanet.measurement.kingdom.deploy.common.server.KingdomDataServer.run(KingdomDataServer.kt:46)
	at org.wfanet.measurement.kingdom.deploy.gcloud.server.SpannerKingdomDataServer.access$run(SpannerKingdomDataServer.kt:28)
	at org.wfanet.measurement.kingdom.deploy.gcloud.server.SpannerKingdomDataServer$run$1$1.invokeSuspend(SpannerKingdomDataServer.kt:43)
	at org.wfanet.measurement.kingdom.deploy.gcloud.server.SpannerKingdomDataServer$run$1$1.invoke(SpannerKingdomDataServer.kt)
	at org.wfanet.measurement.kingdom.deploy.gcloud.server.SpannerKingdomDataServer$run$1$1.invoke(SpannerKingdomDataServer.kt)
	at org.wfanet.measurement.gcloud.spanner.SpannerDatabaseConnector.usingSpanner(SpannerDatabaseConnector.kt:102)
	at org.wfanet.measurement.gcloud.spanner.SpannerDatabaseConnector$usingSpanner$1.invokeSuspend(SpannerDatabaseConnector.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at org.wfanet.measurement.kingdom.deploy.gcloud.server.SpannerKingdomDataServer.run(SpannerKingdomDataServer.kt:37)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1919)
	at picocli.CommandLine.access$1100(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
	at picocli.CommandLine.execute(CommandLine.java:2058)
	at org.wfanet.measurement.common.CommandLinesKt.commandLineMain(CommandLines.kt:44)
	at org.wfanet.measurement.common.CommandLinesKt.commandLineMain$default(CommandLines.kt:39)
	at org.wfanet.measurement.kingdom.deploy.gcloud.server.SpannerKingdomDataServerKt.main(SpannerKingdomDataServer.kt:48)
```

2023-07-19 18:57 UTC, renjiezh commented
> This appears to have broken K8s dev configuration.
> 
> ```
> java.io.FileNotFoundException: /var/run/secrets/files/ro_llv2_protocol_config_config.textproto (No such file or directory)
> 	at java.base/java.io.FileInputStream.open0(Native Method)
> 	at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
> 	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
> 	at org.wfanet.measurement.kingdom.deploy.common.RoLlv2ProtocolConfig.initializeFromFlags(RoLlv2ProtocolConfig.kt:45)
> 	at org.wfanet.measurement.kingdom.deploy.common.server.KingdomDataServer.run(KingdomDataServer.kt:46)
> 	at org.wfanet.measurement.kingdom.deploy.gcloud.server.SpannerKingdomDataServer.access$run(SpannerKingdomDataServer.kt:28)
> 	at org.wfanet.measurement.kingdom.deploy.gcloud.server.SpannerKingdomDataServer$run$1$1.invokeSuspend(SpannerKingdomDataServer.kt:43)
> 	at org.wfanet.measurement.kingdom.deploy.gcloud.server.SpannerKingdomDataServer$run$1$1.invoke(SpannerKingdomDataServer.kt)
> 	at org.wfanet.measurement.kingdom.deploy.gcloud.server.SpannerKingdomDataServer$run$1$1.invoke(SpannerKingdomDataServer.kt)
> 	at org.wfanet.measurement.gcloud.spanner.SpannerDatabaseConnector.usingSpanner(SpannerDatabaseConnector.kt:102)
> 	at org.wfanet.measurement.gcloud.spanner.SpannerDatabaseConnector$usingSpanner$1.invokeSuspend(SpannerDatabaseConnector.kt)
> 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
> 	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
> 	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
> 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
> 	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
> 	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
> 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
> 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
> 	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:284)
> 	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
> 	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
> 	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
> 	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
> 	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
> 	at org.wfanet.measurement.kingdom.deploy.gcloud.server.SpannerKingdomDataServer.run(SpannerKingdomDataServer.kt:37)
> 	at picocli.CommandLine.executeUserObject(CommandLine.java:1919)
> 	at picocli.CommandLine.access$1100(CommandLine.java:145)
> 	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
> 	at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
> 	at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
> 	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
> 	at picocli.CommandLine.execute(CommandLine.java:2058)
> 	at org.wfanet.measurement.common.CommandLinesKt.commandLineMain(CommandLines.kt:44)
> 	at org.wfanet.measurement.common.CommandLinesKt.commandLineMain$default(CommandLines.kt:39)
> 	at org.wfanet.measurement.kingdom.deploy.gcloud.server.SpannerKingdomDataServerKt.main(SpannerKingdomDataServer.kt:48)
> ```

Got it. Let me work on the fix right away.