Convert Key to ResourceName in v2 services
world-federation-of-advertisers/cross-media-measurement pull request #111
Opened 2021-06-17 07:39 UTC by yunyeng

2021-06-17 13:55 UTC, efoxepstein requested changes
> Reviewed 25 of 25 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/111)* status: all files reviewed, 5 unresolved discussions (waiting on @SanjayVas and @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/duchy/service/api/v2alpha/RequisitionFulfillmentService.kt, line 57 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/111#-McPBgnE2tV5CD8x5QAO:-McPBgnE2tV5CD8x5QAP:brhyq6x) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/68d2abecb0d1a0260c3bc62f4c94607fdfe54622/src/main/kotlin/org/wfanet/measurement/duchy/service/api/v2alpha/RequisitionFulfillmentService.kt#L57)):*
> ```Kotlin
>       val header = consumed.item.header
>       val key =
>         RequisitionKeyV2.fromName(header.name)
> ```

Please use `failGrpc(message)` here instead of `throw IllegalArgumentException(message)`
___
*[src/main/kotlin/org/wfanet/measurement/duchy/service/api/v2alpha/utils/ProtocolConfigKey.kt, line 22 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/111#-McPClg_2PcPjoFDlkU5:-McPClg_2PcPjoFDlkU6:bwtsiio) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/68d2abecb0d1a0260c3bc62f4c94607fdfe54622/src/main/kotlin/org/wfanet/measurement/duchy/service/api/v2alpha/utils/ProtocolConfigKey.kt#L22)):*
> ```Kotlin
> 
> /** [ResourceKey] of a ProtocolConfig. */
> data class ProtocolConfigKey(val protocolConfigId: String) : ResourceKey {
> ```

I wonder if we should have a `ParserBasedResourceKey` abstract subclass of `ResourceKey` like:

```
abstract class ParserBasedResourceKey(private val parser: ResourceNameParser) : ResourceKey {
  abstract val nameMap: Map<String, String>
  override fun toName(): String {
    return parser.assembleName(nameMap)
  }
}
```

WDYT?
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepAttemptsService.kt, line 95 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/111#-McPDmY5A_K2GydjBAQg:-McPDmY5A_K2GydjBAQh:b367e8h) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/68d2abecb0d1a0260c3bc62f4c94607fdfe54622/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepAttemptsService.kt#L95)):*
> ```Kotlin
> 
> private fun String.toExchangeStepAttempt(): ExchangeStepAttemptKey {
>   return ExchangeStepAttemptKey.fromName(this)
> ```

maybe `return grpcRequireNotNull(...) { "Could not build ..." }`
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepsService.kt, line 47 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/111#-McPECoV5eIkajpgF_4G:-McPECoV5eIkajpgF_4H:b-3zqjxi) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/68d2abecb0d1a0260c3bc62f4c94607fdfe54622/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepsService.kt#L47)):*
> ```Kotlin
>             PartyCase.DATA_PROVIDER ->
>               externalDataProviderId =
>                 apiIdToExternalId(DataProviderKey.fromName(request.dataProvider)!!.dataProviderId)
> ```

Could you use `grpcRequireNotNull` instead of `!!`? Maybe first pull it out to a variable:

```
val dataProviderKey = grpcRequireNotNull(DataProviderKey.fromName(request.dataProvider))
externalDataProviderId = apiIdToExternalId(dataProviderKey.dataProviderId)
```
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepsService.kt, line 51 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/111#-McPEXpq2Uvye7wfuMd-:-McPEXpq2Uvye7wfuMd0:bb73xfv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/68d2abecb0d1a0260c3bc62f4c94607fdfe54622/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepsService.kt#L51)):*
> ```Kotlin
>               externalModelProviderId =
>                 apiIdToExternalId(
>                   ModelProviderKey.fromName(request.modelProvider)!!.modelProviderId
> ```

Same


<!-- Sent from Reviewable.io -->

2021-06-17 17:46 UTC, yunyeng reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/111)* status: 22 of 25 files reviewed, 5 unresolved discussions (waiting on @efoxepstein, @SanjayVas, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/duchy/service/api/v2alpha/RequisitionFulfillmentService.kt, line 57 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/111#-McPBgnE2tV5CD8x5QAO:-McQ42To4B3yKf8hhMNL:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/68d2abecb0d1a0260c3bc62f4c94607fdfe54622/src/main/kotlin/org/wfanet/measurement/duchy/service/api/v2alpha/RequisitionFulfillmentService.kt#L57)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Please use `failGrpc(message)` here instead of `throw IllegalArgumentException(message)`
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepAttemptsService.kt, line 95 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/111#-McPDmY5A_K2GydjBAQg:-McQ46InDIQLhhyKANHJ:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/68d2abecb0d1a0260c3bc62f4c94607fdfe54622/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepAttemptsService.kt#L95)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

maybe `return grpcRequireNotNull(...) { "Could not build ..." }`
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepsService.kt, line 47 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/111#-McPECoV5eIkajpgF_4G:-McQ47TK2CnWvuXKwJMk:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/68d2abecb0d1a0260c3bc62f4c94607fdfe54622/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepsService.kt#L47)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Could you use `grpcRequireNotNull` instead of `!!`? Maybe first pull it out to a variable:

```
val dataProviderKey = grpcRequireNotNull(DataProviderKey.fromName(request.dataProvider))
externalDataProviderId = apiIdToExternalId(dataProviderKey.dataProviderId)
```
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepsService.kt, line 51 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/111#-McPEXpq2Uvye7wfuMd-:-McQ49vI5eM11AsVzzP2:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/68d2abecb0d1a0260c3bc62f4c94607fdfe54622/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepsService.kt#L51)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Same
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-06-17 17:57 UTC, yunyeng reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/111)* status: 22 of 25 files reviewed, 5 unresolved discussions (waiting on @efoxepstein and @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/duchy/service/api/v2alpha/utils/ProtocolConfigKey.kt, line 22 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/111#-McPClg_2PcPjoFDlkU5:-McQ5m43DJnrJ1-TBe4M:beejmrf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/68d2abecb0d1a0260c3bc62f4c94607fdfe54622/src/main/kotlin/org/wfanet/measurement/duchy/service/api/v2alpha/utils/ProtocolConfigKey.kt#L22)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

I wonder if we should have a `ParserBasedResourceKey` abstract subclass of `ResourceKey` like:

```
abstract class ParserBasedResourceKey(private val parser: ResourceNameParser) : ResourceKey {
  abstract val nameMap: Map<String, String>
  override fun toName(): String {
    return parser.assembleName(nameMap)
  }
}
```

WDYT?
</blockquote></details>

I feel like there are going to be too many files in each utils just to parse a string. We can get back at this again when v2 services are being implemented.


<!-- Sent from Reviewable.io -->

2021-06-17 18:33 UTC, wangyaopw reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/111)* status: 22 of 25 files reviewed, 6 unresolved discussions (waiting on @efoxepstein, @SanjayVas, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/duchy/service/api/v2alpha/RequisitionFulfillmentService.kt, line 59 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/111#-McQD3D33dvLsyqOnFw0:-McQD3D33dvLsyqOnFw1:b4qtrqi) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c408ace52db002c01d971849bddabb6b8e3d55bb/src/main/kotlin/org/wfanet/measurement/duchy/service/api/v2alpha/RequisitionFulfillmentService.kt#L59)):*
> ```
>         "resource_key/fingerprint missing or incomplete in the header."
>       }
> ```
It is not checking resource_key in this line any more. 

changing to "DataProviderParticipationSignature is missing"?


<!-- Sent from Reviewable.io -->

2021-06-17 20:38 UTC, yunyeng reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/111)* status: 22 of 25 files reviewed, 6 unresolved discussions (waiting on @efoxepstein, @SanjayVas, and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/duchy/service/api/v2alpha/RequisitionFulfillmentService.kt, line 59 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/111#-McQD3D33dvLsyqOnFw0:-McQgYYk-pwB9NZp6Gx3:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c408ace52db002c01d971849bddabb6b8e3d55bb/src/main/kotlin/org/wfanet/measurement/duchy/service/api/v2alpha/RequisitionFulfillmentService.kt#L59)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
>         "resource_key/fingerprint missing or incomplete in the header."
>       }
> ```
It is not checking resource_key in this line any more. 

changing to "DataProviderParticipationSignature is missing"?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-06-17 21:00 UTC, efoxepstein approved these changes
> Reviewed 2 of 3 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/111)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @wangyaopw)



<!-- Sent from Reviewable.io -->

2021-06-17 23:57 UTC, wangyaopw approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/111)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2021-06-18 00:32 UTC, SanjayVas reviewed
> Reviewed 2 of 25 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/111)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones and @yunyeng)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/111#-McRXAViE1NeVmu56IsD:-McRXAViE1NeVmu56IsE:b-je46ws) (no related file):*
Do we want #110 to land first?

---


<!-- Sent from Reviewable.io -->

2021-06-18 19:56 UTC, SanjayVas requested changes
> Reviewed 19 of 25 files at r1, 2 of 3 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/111)* status: all files reviewed, 12 unresolved discussions (waiting on @stevenwarejones and @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/duchy/service/api/v2alpha/RequisitionFulfillmentService.kt, line 30 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/111#-McVfCdzCXTHobk7TvoZ:-McVfCdzCXTHobk7Tvo_:bi2kil1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/120bab991923c26d4df6f8de2d8f92124469c422/src/main/kotlin/org/wfanet/measurement/duchy/service/api/v2alpha/RequisitionFulfillmentService.kt#L30)):*
> ```
> RequisitionKeyV2
> ```
`V2` is not a salient distinction between this and the other `RequisitionKey` that's imported. The other comes from the system API.

I'd recommend having this be `RequisitionKey` since this is inside a package specifically for the v2alpha public API, and naming the other one `SystemRequisitionKey`.
___
*[src/main/kotlin/org/wfanet/measurement/duchy/service/api/v2alpha/RequisitionFulfillmentService.kt, line 57 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/111#-McVQ1uI0GsoorPGWCWy:-McVQ1uI0GsoorPGWCWz:bhke7po) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/120bab991923c26d4df6f8de2d8f92124469c422/src/main/kotlin/org/wfanet/measurement/duchy/service/api/v2alpha/RequisitionFulfillmentService.kt#L57)):*
> ```
> RequisitionKeyV2.fromName(header.name) ?: failGrpc { "resource_key/name invalid." }
> ```
nit: `grpcRequireNotNull` does the elvis operator part for you.
___
*[src/main/kotlin/org/wfanet/measurement/duchy/service/api/v2alpha/utils/RequisitionKey.kt, line 15 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/111#-McVeJIj-IL0fC2i5ftb:-McVeJIj-IL0fC2i5ftc:b-x2l29o) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/120bab991923c26d4df6f8de2d8f92124469c422/src/main/kotlin/org/wfanet/measurement/duchy/service/api/v2alpha/utils/RequisitionKey.kt#L15)):*
> ```
> .utils
> ```
Why a separate `utils` subpackage? These are basically replacing proto messages in the same package.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepAttemptsService.kt, line 95 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/111#-McVZMC_4oYR9hLrm-d1:-McVZMC_4oYR9hLrm-d2:b-lc6nuj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/120bab991923c26d4df6f8de2d8f92124469c422/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepAttemptsService.kt#L95)):*
> ```
> toExchangeStepAttempt
> ```
Not actually an attempt, but an attempt key.

As an aside, I know we have these sprinkled through the system but I'm not really a fan of extension methods like this on String. I know it's a bit duplicative, but I'd prefer either something that acts on the specific message type or just inlining the check to each callsite.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepAttemptsService.kt, line 101 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/111#-McVcZOI5ISZpAt3o2He:-McVcZOI5ISZpAt3o2Hf:b-vdaujv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/120bab991923c26d4df6f8de2d8f92124469c422/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepAttemptsService.kt#L101)):*
> ```
> getAttemptNumber()
> ```
nit: could be an `attemptNumber` extension property instead, since it's not doing anything terribly complicated.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepAttemptsService.kt, line 109 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/111#-McVdpsW4Cj7jlPYDVZY:-McVdpsW4Cj7jlPYDVZZ:bttda7a) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/120bab991923c26d4df6f8de2d8f92124469c422/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepAttemptsService.kt#L109)):*
> ```
> toV2Alpha
> ```
nit: this is defined inside of an impl in a v2alpha package, so no need to specify v2alpha in any names.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepAttemptsService.kt, line 122 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/111#-McVcxIQ6tyBJ9BccZ3s:-McVcxIQ6tyBJ9BccZ3t:bfkwmp9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/120bab991923c26d4df6f8de2d8f92124469c422/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepAttemptsService.kt#L122)):*
> ```
> toV2AlphaName
> ```
nit: "to" extension methods implies a conversion to a representation of the same data, which can often be round-tripped. This is only using a subset of the fields.

Since this is a small function only used once by a function that's itself pretty small, you could just inline it.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepsService.kt, line 97 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/111#-McVe2jG10Ogan4WhQKb:-McVe2jG10Ogan4WhQKc:b-ttfy8b) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/120bab991923c26d4df6f8de2d8f92124469c422/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepsService.kt#L97)):*
> ```
> v2AlphaName
> ```
nit: same here re: specifying v2alpha
___
*[src/test/kotlin/org/wfanet/measurement/duchy/service/api/v2alpha/RequisitionFulfillmentServiceTest.kt, line 47 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/111#-McVfPR_8_ZcVdBColJN:-McVfPR_8_ZcVdBColJO:b73fpjj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/120bab991923c26d4df6f8de2d8f92124469c422/src/test/kotlin/org/wfanet/measurement/duchy/service/api/v2alpha/RequisitionFulfillmentServiceTest.kt#L47)):*
> ```
> RequisitionKeyV2
> ```
Same here re: V2
___
*[src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepsServiceTest.kt, line 121 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/111#-McVgRlUAjiY4g5yy4Kn:-McVgRlUAjiY4g5yy4Ko:b-7drh5n) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/120bab991923c26d4df6f8de2d8f92124469c422/src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepsServiceTest.kt#L121)):*
> ```
> dataProviderId
> ```
This is not a data provider ID, but rather a data provider resource name.
___
*[src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepsServiceTest.kt, line 149 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/111#-McVgXf0-40U4CDzDcO8:-McVgXf0-40U4CDzDcO9:b-75mu3v) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/120bab991923c26d4df6f8de2d8f92124469c422/src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepsServiceTest.kt#L149)):*
> ```
> modelProviderId
> ```
Same here. Not an ID.


<!-- Sent from Reviewable.io -->

2021-06-21 03:31 UTC, yunyeng reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/111)* status: 2 of 25 files reviewed, 6 unresolved discussions (waiting on @efoxepstein, @SanjayVas, @stevenwarejones, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/duchy/service/api/v2alpha/RequisitionFulfillmentService.kt, line 30 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/111#-McVfCdzCXTHobk7TvoZ:-McgbmJW8r6g-DxzMPwB:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/120bab991923c26d4df6f8de2d8f92124469c422/src/main/kotlin/org/wfanet/measurement/duchy/service/api/v2alpha/RequisitionFulfillmentService.kt#L30)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> RequisitionKeyV2
> ```
`V2` is not a salient distinction between this and the other `RequisitionKey` that's imported. The other comes from the system API.

I'd recommend having this be `RequisitionKey` since this is inside a package specifically for the v2alpha public API, and naming the other one `SystemRequisitionKey`.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepAttemptsService.kt, line 95 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/111#-McVZMC_4oYR9hLrm-d1:-Mcgbhks0F-5yodJQV8G:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/120bab991923c26d4df6f8de2d8f92124469c422/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepAttemptsService.kt#L95)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> toExchangeStepAttempt
> ```
Not actually an attempt, but an attempt key.

As an aside, I know we have these sprinkled through the system but I'm not really a fan of extension methods like this on String. I know it's a bit duplicative, but I'd prefer either something that acts on the specific message type or just inlining the check to each callsite.
</blockquote></details>

Done.
___
*[src/test/kotlin/org/wfanet/measurement/duchy/service/api/v2alpha/RequisitionFulfillmentServiceTest.kt, line 47 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/111#-McVfPR_8_ZcVdBColJN:-McgbOJYCdFo-OOY5Xg0:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/120bab991923c26d4df6f8de2d8f92124469c422/src/test/kotlin/org/wfanet/measurement/duchy/service/api/v2alpha/RequisitionFulfillmentServiceTest.kt#L47)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> RequisitionKeyV2
> ```
Same here re: V2
</blockquote></details>

Done.
___
*[src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepsServiceTest.kt, line 121 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/111#-McVgRlUAjiY4g5yy4Kn:-McgbKWs7X9I1-kQraVp:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/120bab991923c26d4df6f8de2d8f92124469c422/src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepsServiceTest.kt#L121)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> dataProviderId
> ```
This is not a data provider ID, but rather a data provider resource name.
</blockquote></details>

Done.
___
*[src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepsServiceTest.kt, line 149 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/111#-McVgXf0-40U4CDzDcO8:-McgbJp30SzM1rEwr5TB:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/120bab991923c26d4df6f8de2d8f92124469c422/src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepsServiceTest.kt#L149)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> modelProviderId
> ```
Same here. Not an ID.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-06-21 13:18 UTC, efoxepstein approved these changes
> Reviewed 24 of 24 files at r4.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/111)* status: all files reviewed, 6 unresolved discussions (waiting on @SanjayVas, @stevenwarejones, and @yunyeng)



<!-- Sent from Reviewable.io -->

2021-06-21 18:01 UTC, efoxepstein approved these changes
> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/111)* status: all files reviewed, 6 unresolved discussions (waiting on @SanjayVas, @stevenwarejones, and @yunyeng)



<!-- Sent from Reviewable.io -->

2021-06-21 19:21 UTC, SanjayVas requested changes
> Reviewed 20 of 24 files at r4, 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/111)* status: all files reviewed, 4 unresolved discussions (waiting on @stevenwarejones and @yunyeng)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/111#-McRXAViE1NeVmu56IsD:-McjrOs8BnK89DEKKwDB:bexepvd) (no related file):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Do we want #110 to land first?
</blockquote></details>

From offline discussion with @wangyaopw, sounds like it's a race :P

---
___
*[src/main/kotlin/org/wfanet/measurement/duchy/service/api/v2alpha/RequisitionFulfillmentService.kt, line 56 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/111#-McjrfBy5m_YLEJ8Kels:-McjrfBy5m_YLEJ8Kelt:byvp1oh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/71ecfa971f1d4a6d6dc9d6894345fc283c6c7cf8/src/main/kotlin/org/wfanet/measurement/duchy/service/api/v2alpha/RequisitionFulfillmentService.kt#L56)):*
> ```
> "resource_key/name invalid."
> ```
nit: "Resource name unspecified or invalid" would be more accurate. Key is a construct that's not relevant to the caller.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepAttemptsService.kt, line 43 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/111#-Mcjs30e5hJr7C9Wzm14:-Mcjs30e5hJr7C9Wzm15:b-ipis0w) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/71ecfa971f1d4a6d6dc9d6894345fc283c6c7cf8/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepAttemptsService.kt#L43)):*
> ```
> ExchangeStepAttempt
> ```
Technically an `ExchangeStepAttemptKey`gRPC error messages should be useful to the RPC caller. Something like "Resource name unspecified or invalid"
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepAttemptsService.kt, line 69 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/111#-McjsJRTAQj4jJYKves5:-McjsJRTAQj4jJYKves6:bh3zyc2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/71ecfa971f1d4a6d6dc9d6894345fc283c6c7cf8/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepAttemptsService.kt#L69)):*
> ```
> "Could not build ExchangeStepAttempt from name $this."
> ```
Same here.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepAttemptsService.kt, line 103 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/111#-McjvfUPAropSK1ZY0IX:-McjvfUPAropSK1ZY0IY:b15pem1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/71ecfa971f1d4a6d6dc9d6894345fc283c6c7cf8/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepAttemptsService.kt#L103)):*
> ```
> apiIdToExternalId(exchangeStepAttemptId).toInt()
> ```
Wait a sec, I don't think this is actually right. We should either have a distinct attempt ID that's independent of the attempt number, or actually make it clear that the attempt ID component of the resource name *is* the attempt number.

If the latter, then it should be represented in the resource name transparently as an integer rather than being base64url-encoded. Additionally, there should be a comment explaining this in the proto definition (obviously a separate PR). See how the {duchy} pattern var is documented: https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/44087e4b70e8e078bdfacb36f730b02a44f7463e/src/main/proto/wfa/measurement/system/v1alpha/computation_participant.proto#L31.

@efoxepstein 


<!-- Sent from Reviewable.io -->

2021-06-21 19:41 UTC, efoxepstein approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/111)* status: all files reviewed, 4 unresolved discussions (waiting on @SanjayVas, @stevenwarejones, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepAttemptsService.kt, line 103 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/111#-McjvfUPAropSK1ZY0IX:-Mck4Zi-9xRamVvwxPpk:b-jrl8k9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/71ecfa971f1d4a6d6dc9d6894345fc283c6c7cf8/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepAttemptsService.kt#L103)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> apiIdToExternalId(exchangeStepAttemptId).toInt()
> ```
Wait a sec, I don't think this is actually right. We should either have a distinct attempt ID that's independent of the attempt number, or actually make it clear that the attempt ID component of the resource name *is* the attempt number.

If the latter, then it should be represented in the resource name transparently as an integer rather than being base64url-encoded. Additionally, there should be a comment explaining this in the proto definition (obviously a separate PR). See how the {duchy} pattern var is documented: https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/44087e4b70e8e078bdfacb36f730b02a44f7463e/src/main/proto/wfa/measurement/system/v1alpha/computation_participant.proto#L31.

@efoxepstein 
</blockquote></details>

I prefer transparently storing it as an integer. It's just a number and it seems reasonable that a client should be able to pick it -- no need for it to be opaque. +1 to Sanjay's comment.


<!-- Sent from Reviewable.io -->

2021-06-21 20:39 UTC, yunyeng reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/111)* status: 20 of 25 files reviewed, 3 unresolved discussions (waiting on @efoxepstein, @SanjayVas, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepAttemptsService.kt, line 43 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/111#-Mcjs30e5hJr7C9Wzm14:-MckHvng3GAMujEIu8Su:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/71ecfa971f1d4a6d6dc9d6894345fc283c6c7cf8/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepAttemptsService.kt#L43)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> ExchangeStepAttempt
> ```
Technically an `ExchangeStepAttemptKey`gRPC error messages should be useful to the RPC caller. Something like "Resource name unspecified or invalid"
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepAttemptsService.kt, line 69 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/111#-McjsJRTAQj4jJYKves5:-MckHulX-PvFZqtg2roG:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/71ecfa971f1d4a6d6dc9d6894345fc283c6c7cf8/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepAttemptsService.kt#L69)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> "Could not build ExchangeStepAttempt from name $this."
> ```
Same here.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepAttemptsService.kt, line 103 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/111#-McjvfUPAropSK1ZY0IX:-MckHu6a2nizLLn5Aa42:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/71ecfa971f1d4a6d6dc9d6894345fc283c6c7cf8/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepAttemptsService.kt#L103)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

I prefer transparently storing it as an integer. It's just a number and it seems reasonable that a client should be able to pick it -- no need for it to be opaque. +1 to Sanjay's comment.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-06-22 00:42 UTC, SanjayVas requested changes
> Reviewed 5 of 5 files at r6.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/111)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones and @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepAttemptsService.kt, line 116 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/111#-Mcl97AB5_rpFCZBkUOX:-Mcl97AC69I9jTF9WA9m:b901k38) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3908b1563c8d2d6a71587c24c75af784b0ffc99d/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepAttemptsService.kt#L116)):*
> ```
> exchangeStepId = externalIdToApiId(stepIndex.toLong()),
> ```
I believe stepIndex is similar to attemptNumber in that it's just an integer, not an encoded external ID.


<!-- Sent from Reviewable.io -->

2021-06-22 01:05 UTC, yunyeng reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/111)* status: 21 of 25 files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepAttemptsService.kt, line 116 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/111#-Mcl97AB5_rpFCZBkUOX:-MclExIN-YFM36SPHHGh:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3908b1563c8d2d6a71587c24c75af784b0ffc99d/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepAttemptsService.kt#L116)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> exchangeStepId = externalIdToApiId(stepIndex.toLong()),
> ```
I believe stepIndex is similar to attemptNumber in that it's just an integer, not an encoded external ID.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-06-22 01:06 UTC, SanjayVas approved these changes
> Reviewed 4 of 4 files at r7.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/111)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)



<!-- Sent from Reviewable.io -->

2021-06-22 01:09 UTC, merged