Circulate direct computation methodology from protocol config to measurement result.
world-federation-of-advertisers/cross-media-measurement pull request #1154
Opened 2023-08-05 02:29 UTC by riemanli

2023-08-05 02:29 UTC, wfa-reviewable commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1154)
<!-- Reviewable:end -->

2023-08-05 02:30 UTC, riemanli commented
Current dependencies on/for this PR:
* main
  * **PR #1154** <a href="https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/1154" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/1154?utm_source=stack-comment).

2023-08-07 17:45 UTC, SanjayVas requested changes
> Reviewed 4 of 18 files at r1, 2 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1154)* status: 6 of 21 files reviewed, 3 unresolved discussions (waiting on @renjiezh, @riemanli, and @tristanvuong2021)

___
*[`build/repositories.bzl` line 44 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1154#-NbG4XYuBM07P_qy-LfU:-NbG4XYuBM07P_qy-LfV:b7l53e6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f8b5daf8b9223d20d86d382c1aef57b836b335bc/build/repositories.bzl#L44)):*
> ```Starlark
>         name = "wfa_measurement_proto",
>         repo = "cross-media-measurement-api",
>         sha256 = "642106dd7c10b4c8820c31c3c18f54e7a5b9480adc85b9f6e58b267fd8f7a62e",
> ```

Add a `DO_NOT_SUBMIT` comment as a note to use the release version prior to submitting (merging).
___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/InProcessKingdom.kt` line 210 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1154#-NbG4oGv0k4bqp9KAhGi:-NbG4oGwE-P31ShRyiUy:b28rjpn) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f8b5daf8b9223d20d86d382c1aef57b836b335bc/src/main/kotlin/org/wfanet/measurement/integration/common/InProcessKingdom.kt#L210)):*
> ```Kotlin
>     /** Default deadline for RPCs to internal server in milliseconds. */
>     private const val DEFAULT_INTERNAL_DEADLINE_MILLIS = 30_000L
>     private val measurementNoiseMechanisms: List<ProtocolConfig.NoiseMechanism> =
> ```

Despite not being a compile-time `const`, this should still use `CONST_CASE` since it's immutable and has no behavior.



_Code quote:_
```Kotlin
measurementNoiseMechanisms
```
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/server/V2alphaPublicApiServer.kt` line 208 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1154#-NbG5DqI9RqoufHov7xa:-NbG5DqI9RqoufHov7xb:b-u2l4b4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f8b5daf8b9223d20d86d382c1aef57b836b335bc/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/server/V2alphaPublicApiServer.kt#L208)):*
> ```Kotlin
> private class V2alphaFlags {
>   class DirectNoiseMechanismInput {
>     @CommandLine.Option(
> ```

This should just be a single option of type `List<NoiseMechanism>`. Picocli will convert multiple instances of the option with an enum name into the list for you.


<!-- Sent from Reviewable.io -->

2023-08-09 23:03 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1154)* status: 3 of 22 files reviewed, 3 unresolved discussions (waiting on @renjiezh, @SanjayVas, and @tristanvuong2021)

___
*[`build/repositories.bzl` line 44 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1154#-NbG4XYuBM07P_qy-LfU:-NbHLaMC5hv-oDAAAu2G:b-mwp1wa) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f8b5daf8b9223d20d86d382c1aef57b836b335bc/build/repositories.bzl#L44)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Add a `DO_NOT_SUBMIT` comment as a note to use the release version prior to submitting (merging).
</blockquote></details>

Thanks for reminding. Done.
___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/InProcessKingdom.kt` line 210 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1154#-NbG4oGv0k4bqp9KAhGi:-NbHNTDb1zNHXv5GJOnx:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f8b5daf8b9223d20d86d382c1aef57b836b335bc/src/main/kotlin/org/wfanet/measurement/integration/common/InProcessKingdom.kt#L210)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Despite not being a compile-time `const`, this should still use `CONST_CASE` since it's immutable and has no behavior.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/server/V2alphaPublicApiServer.kt` line 208 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1154#-NbG5DqI9RqoufHov7xa:-NbL7bMU4j3REMLwb_l_:b-64sd6u) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f8b5daf8b9223d20d86d382c1aef57b836b335bc/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/server/V2alphaPublicApiServer.kt#L208)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This should just be a single option of type `List<NoiseMechanism>`. Picocli will convert multiple instances of the option with an enum name into the list for you.
</blockquote></details>

Based on offline discussion, we decided to use Single Value Validation to exclude invalid enum constants.


<!-- Sent from Reviewable.io -->

2023-08-09 23:19 UTC, SanjayVas requested changes
> Reviewed 1 of 18 files at r1, 3 of 9 files at r2, 5 of 11 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1154)* status: 12 of 22 files reviewed, 10 unresolved discussions (waiting on @renjiezh, @riemanli, and @tristanvuong2021)

___
*[`build/repositories.bzl` line 44 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1154#-NbG4XYuBM07P_qy-LfU:-NbRYo5m3I5uDIfeQB84:b-t0vgfr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f8b5daf8b9223d20d86d382c1aef57b836b335bc/build/repositories.bzl#L44)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Thanks for reminding. Done.
</blockquote></details>

Generally we reference the PR in the comment using a similar format as TODOs.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/server/V2alphaPublicApiServer.kt` line 214 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1154#-NbR_sq6EqU40RJ2FEUJ:-NbR_sq6EqU40RJ2FEUK:undefined) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9fc024d1c2c9bf84d39998d79843736b9eb2822c/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/server/V2alphaPublicApiServer.kt#L214)):*
> ```Kotlin
>     private set
> 
>   val directNoiseMechanisms: MutableList<NoiseMechanism> = mutableListOf()
> ```





_Suggestion:_
```Kotlin
lateinit var directNoiseMechanisms: List<NoiseMechanism>
  private set
```
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/server/V2alphaPublicApiServer.kt` line 216 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1154#-NbRZ8hU0EIcVPCjyKtn:-NbRZ8hU0EIcVPCjyKto:b-d8yi74) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9fc024d1c2c9bf84d39998d79843736b9eb2822c/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/server/V2alphaPublicApiServer.kt#L216)):*
> ```Kotlin
>   val directNoiseMechanisms: MutableList<NoiseMechanism> = mutableListOf()
> 
>   @CommandLine.Spec lateinit var spec: CommandLine.Model.CommandSpec // injected by picocli
> ```

Add `private set` to make sure nothing outside of the flags instance can change it.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/server/V2alphaPublicApiServer.kt` line 219 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1154#-NbRa8-yEaaRgxR7PGtY:-NbRa8-yEaaRgxR7PGtZ:bc5xpcn) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9fc024d1c2c9bf84d39998d79843736b9eb2822c/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/server/V2alphaPublicApiServer.kt#L219)):*
> ```Kotlin
> 
>   @CommandLine.Option(
>     names = ["--direct-noise-mechanisms"],
> ```

Singular, since the caller should be specifying it multiple times to get multiple values



_Suggestion:_
```Kotlin
--direct-noise-mechanism
```
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/server/V2alphaPublicApiServer.kt` line 220 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1154#-NbRYz8G8zgNsDvu1KWa:-NbRYz8H1hcnKU_cEuSF:b-rae0em) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9fc024d1c2c9bf84d39998d79843736b9eb2822c/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/server/V2alphaPublicApiServer.kt#L220)):*
> ```Kotlin
>   @CommandLine.Option(
>     names = ["--direct-noise-mechanisms"],
>     split = ",",
> ```

Don't use split. Make the caller specify it multiple times instead.



_Code quote:_
```Kotlin
    split = ",",
```
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/server/V2alphaPublicApiServer.kt` line 252 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1154#-NbRa3hAAdeVKQxokBJJ:-NbRa3hAAdeVKQxokBJK:undefined) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9fc024d1c2c9bf84d39998d79843736b9eb2822c/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/server/V2alphaPublicApiServer.kt#L252)):*
> ```Kotlin
>       }
>     }
>     directNoiseMechanisms += noiseMechanisms
> ```





_Suggestion:_
```Kotlin
directNoiseMechanisms = noiseMechanisms
```
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt` line 124 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1154#-NbRZKDF9m_03NtM6nYm:-NbRZKDF9m_03NtM6nYn:bu4n8tj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9fc024d1c2c9bf84d39998d79843736b9eb2822c/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt#L124)):*
> ```Kotlin
> import org.wfanet.measurement.kingdom.deploy.common.RoLlv2ProtocolConfig
> 
> // (-- TODO(world-federation-of-advertisers/cross-media-measurement-api/issues/160): this value
> ```

Wrong comment/TODO format for a Kotlin property.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt` line 338 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1154#-NbRZdQr0MkXDjcqjgb9:-NbRZdQr0MkXDjcqjgbA:b-gwps8w) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9fc024d1c2c9bf84d39998d79843736b9eb2822c/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt#L338)):*
> ```Kotlin
> 
>     if (source.hasDeterministicCountDistinct()) {
>       deterministicCountDistinct = ProtocolConfigKt.DirectKt.deterministicCountDistinct {}
> ```

Prefer `getDefaultInstance()` as that returns a singleton.



_Suggestion:_
```Kotlin
ProtocolConfig.Direct.DeterministicCountDistinct.getDefaultInstance()
```
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/system/v1alpha/ProtoConversions.kt` line 397 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1154#-NbR__nT2Y1si7bXyDew:-NbR__nT2Y1si7bXyDex:undefined) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9fc024d1c2c9bf84d39998d79843736b9eb2822c/src/main/kotlin/org/wfanet/measurement/kingdom/service/system/v1alpha/ProtoConversions.kt#L397)):*
> ```Kotlin
>     InternalNoiseMechanism.CONTINUOUS_GAUSSIAN,
>     InternalNoiseMechanism.NOISE_MECHANISM_UNSPECIFIED,
>     ProtocolConfig.NoiseMechanism.NONE,
> ```





_Suggestion:_
```Kotlin
InternalNoiseMechanism
```


<!-- Sent from Reviewable.io -->

2023-08-10 00:20 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1154)* status: 8 of 22 files reviewed, 10 unresolved discussions (waiting on @renjiezh, @SanjayVas, and @tristanvuong2021)

___
*[`build/repositories.bzl` line 44 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1154#-NbG4XYuBM07P_qy-LfU:-NbReJuw9JdeMRUV7OIx:b-8l9qrj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f8b5daf8b9223d20d86d382c1aef57b836b335bc/build/repositories.bzl#L44)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Generally we reference the PR in the comment using a similar format as TODOs.
</blockquote></details>

Do you mean this PR or the PR in the cmm-api?
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/server/V2alphaPublicApiServer.kt` line 214 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1154#-NbR_sq6EqU40RJ2FEUJ:-NbReax_0mFKueWwA02T:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9fc024d1c2c9bf84d39998d79843736b9eb2822c/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/server/V2alphaPublicApiServer.kt#L214)):*
> ```Kotlin
>     private set
> 
>   val directNoiseMechanisms: MutableList<NoiseMechanism> = mutableListOf()
> ```

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/server/V2alphaPublicApiServer.kt` line 216 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1154#-NbRZ8hU0EIcVPCjyKtn:-NbRec509_JvnB1_njMc:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9fc024d1c2c9bf84d39998d79843736b9eb2822c/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/server/V2alphaPublicApiServer.kt#L216)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Add `private set` to make sure nothing outside of the flags instance can change it.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/server/V2alphaPublicApiServer.kt` line 219 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1154#-NbRa8-yEaaRgxR7PGtY:-NbRf8eU9QEmxUiX9stb:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9fc024d1c2c9bf84d39998d79843736b9eb2822c/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/server/V2alphaPublicApiServer.kt#L219)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Singular, since the caller should be specifying it multiple times to get multiple values
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/server/V2alphaPublicApiServer.kt` line 220 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1154#-NbRYz8G8zgNsDvu1KWa:-NbRf7NbE0p8pt6hGZbR:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9fc024d1c2c9bf84d39998d79843736b9eb2822c/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/server/V2alphaPublicApiServer.kt#L220)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Don't use split. Make the caller specify it multiple times instead.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/server/V2alphaPublicApiServer.kt` line 252 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1154#-NbRa3hAAdeVKQxokBJJ:-NbRf9fq8vIWbU2KFEdD:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9fc024d1c2c9bf84d39998d79843736b9eb2822c/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/server/V2alphaPublicApiServer.kt#L252)):*
> ```Kotlin
>       }
>     }
>     directNoiseMechanisms += noiseMechanisms
> ```

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt` line 124 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1154#-NbRZKDF9m_03NtM6nYm:-NbRlmDs-lWCnw4xT6aP:b-fkjwlz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9fc024d1c2c9bf84d39998d79843736b9eb2822c/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt#L124)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Wrong comment/TODO format for a Kotlin property.
</blockquote></details>

Fixed based on the [TODO format guide](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/docs/code-style.md#format).
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt` line 338 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1154#-NbRZdQr0MkXDjcqjgb9:-NbRgI8328qXBpzLTZHm:b3w9tt8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9fc024d1c2c9bf84d39998d79843736b9eb2822c/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt#L338)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Prefer `getDefaultInstance()` as that returns a singleton.
</blockquote></details>

Fixed this and the other empty `{}` DSLs
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/system/v1alpha/ProtoConversions.kt` line 397 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1154#-NbR__nT2Y1si7bXyDew:-NbRgkB9Eqoj73_RIZ_y:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9fc024d1c2c9bf84d39998d79843736b9eb2822c/src/main/kotlin/org/wfanet/measurement/kingdom/service/system/v1alpha/ProtoConversions.kt#L397)):*
> ```Kotlin
>     InternalNoiseMechanism.CONTINUOUS_GAUSSIAN,
>     InternalNoiseMechanism.NOISE_MECHANISM_UNSPECIFIED,
>     ProtocolConfig.NoiseMechanism.NONE,
> ```

Done.


<!-- Sent from Reviewable.io -->

2023-08-11 17:36 UTC, SanjayVas requested changes
> Reviewed 4 of 18 files at r1, 3 of 11 files at r3, 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1154)* status: all files reviewed, 5 unresolved discussions (waiting on @renjiezh, @riemanli, and @tristanvuong2021)

___
*[`build/repositories.bzl` line 44 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1154#-NbG4XYuBM07P_qy-LfU:-Nb__sKE7YjVrQYDVsne:b-oapa45) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f8b5daf8b9223d20d86d382c1aef57b836b335bc/build/repositories.bzl#L44)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Do you mean this PR or the PR in the cmm-api?
</blockquote></details>

The API PR. Otherwise it's hard to track down where the commit that's referenced came from.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt` line 124 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1154#-NbRZKDF9m_03NtM6nYm:-Nb_aLRw19r4XqUcuKPM:b-1yhhfd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9fc024d1c2c9bf84d39998d79843736b9eb2822c/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt#L124)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Fixed based on the [TODO format guide](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/docs/code-style.md#format).
</blockquote></details>

It's still incorrect here. This is using the TODO format for a protobuf API definition, not for a Kotlin property. Kotlin properties should be documented using KDoc syntax, and the TODO shouldn't be wrapped in `(--`/`--)`.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt` line 240 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1154#-Nb_dnRE2bYPM9digWXh:-Nb_dnRF0hHQ2Os20zag:b6qxyz0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cf8880c35f13caaaa7a627a80f3a4a2f89a3b29d/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt#L240)):*
> ```Kotlin
>             } else {
>               // For backward compatibility
>               direct = ProtocolConfig.Direct.getDefaultInstance()
> ```

This still needs to specify the options that would have been valid at the time the Measurement was created. This means that the noise mechanisms wouldn't be restricted by the Kingdom flags.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt` line 317 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1154#-Nb_eYO1ASXGdqI1n-oF:-Nb_eYO1ASXGdqI1n-oG:b7kw8an) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cf8880c35f13caaaa7a627a80f3a4a2f89a3b29d/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt#L317)):*
> ```Kotlin
>       ProtocolConfig.MeasurementType.IMPRESSION,
>       ProtocolConfig.MeasurementType.DURATION -> {
>         protocols += protocol { direct = ProtocolConfig.Direct.getDefaultInstance() }
> ```

Doesn't this need to use the same logic of reading the source protocol config if it exists (for Measurements created after this change) or else using a default value (for old Measurements)? Otherwise the returned value won't have any methodologies.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 154 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1154#-Nb_auex4rmy-hsXlayh:-Nb_auex4rmy-hsXlayi:bw3q71p) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cf8880c35f13caaaa7a627a80f3a4a2f89a3b29d/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L154)):*
> ```Kotlin
>   private val privacyBudgetManager: PrivacyBudgetManager,
>   private val trustedCertificates: Map<ByteString, X509Certificate>,
>   private val directNoiseMechanism: DirectNoiseMechanism,
> ```

Do we still want to pick the noise mechanism for the simulator? Now that the options are in the protocol config, I think the simulator should pick from the options based on its own order of preference (e.g. preferring gaussian). Keep in mind that the EDP must refuse the requisition if there's no noise mechanism in the protocol config that it supports.

We can still control which mechanism is used in testing by restricting the options in the protocol config.
___
*[`src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsServiceTest.kt` line 875 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1154#-Nb_cxxC-P1dOMVf28m2:-Nb_cxxC-P1dOMVf28m3:basv6pl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cf8880c35f13caaaa7a627a80f3a4a2f89a3b29d/src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsServiceTest.kt#L875)):*
> ```Kotlin
>       ProtocolConfigKt.direct {
>         noiseMechanisms += ProtocolConfig.NoiseMechanism.GEOMETRIC
>         noiseMechanisms += ProtocolConfig.NoiseMechanism.DISCRETE_GAUSSIAN
> ```

nit: prefer to use valid configurations in tests, unless checking for an error. I believe that direct protocol configs wouldn't specify this value



_Suggestion:_
```Kotlin
CONTINUOUS_GAUSSIAN
```


<!-- Sent from Reviewable.io -->

2023-08-11 22:15 UTC, riemanli commented
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 154 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1154#-Nb_auex4rmy-hsXlayh:-NbaWXD-5D_vwW2S8yGY:b9msp7l) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cf8880c35f13caaaa7a627a80f3a4a2f89a3b29d/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L154)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Do we still want to pick the noise mechanism for the simulator? Now that the options are in the protocol config, I think the simulator should pick from the options based on its own order of preference (e.g. preferring gaussian). Keep in mind that the EDP must refuse the requisition if there's no noise mechanism in the protocol config that it supports.

We can still control which mechanism is used in testing by restricting the options in the protocol config.
</blockquote></details>

Thanks for bringing this aspect. Do you know how noise mechanism selection really works on the EDP side? Do EDPs pick one and only one noise mechanism or do they pick the most preferred and acceptable one from the options? 

For the former scenario, `directNoiseMechanism` in the constructor can indicate that this is the only noise mechanism the EDP wants to use. For the latter, we can change `directNoiseMechanism` to a list of noise mechanisms in the order of preference. 


<!-- Sent from Reviewable.io -->

2023-08-11 22:21 UTC, riemanli commented
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt` line 240 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1154#-Nb_dnRE2bYPM9digWXh:-NbaMAjLEE81ULcTSe4C:b-ago7mu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cf8880c35f13caaaa7a627a80f3a4a2f89a3b29d/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt#L240)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This still needs to specify the options that would have been valid at the time the Measurement was created. This means that the noise mechanisms wouldn't be restricted by the Kingdom flags.
</blockquote></details>

Thanks for pointing it out. I am still working on the requested change. I found out that the request leads to several default direct configs for different measurement types. I wonder if this is the case that we prefer using object configs. WDYT?


<!-- Sent from Reviewable.io -->

2023-08-12 01:07 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1154)* status: 18 of 22 files reviewed, 4 unresolved discussions (waiting on @renjiezh, @SanjayVas, and @tristanvuong2021)

___
*[`build/repositories.bzl` line 44 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1154#-NbG4XYuBM07P_qy-LfU:-NbaDGpwA9wIF8Twnu_e:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f8b5daf8b9223d20d86d382c1aef57b836b335bc/build/repositories.bzl#L44)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The API PR. Otherwise it's hard to track down where the commit that's referenced came from.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt` line 124 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1154#-NbRZKDF9m_03NtM6nYm:-NbaCpl2E4D65fCr5XYU:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9fc024d1c2c9bf84d39998d79843736b9eb2822c/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt#L124)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

It's still incorrect here. This is using the TODO format for a protobuf API definition, not for a Kotlin property. Kotlin properties should be documented using KDoc syntax, and the TODO shouldn't be wrapped in `(--`/`--)`.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt` line 240 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1154#-Nb_dnRE2bYPM9digWXh:-NbbFxsJ45nKJWxM6Kml:b-ctekiw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cf8880c35f13caaaa7a627a80f3a4a2f89a3b29d/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt#L240)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Thanks for pointing it out. I am still working on the requested change. I found out that the request leads to several default direct configs for different measurement types. I wonder if this is the case that we prefer using object configs. WDYT?
</blockquote></details>

Made the changes with hardcoded default configs to move forward. Let me know if that's ok.

To accomplish the requested change, I separated measurement type case to handle differently.

cc @renjiezh 
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt` line 317 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1154#-Nb_eYO1ASXGdqI1n-oF:-NbaVlTs0ST-zGmszmcI:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cf8880c35f13caaaa7a627a80f3a4a2f89a3b29d/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt#L317)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Doesn't this need to use the same logic of reading the source protocol config if it exists (for Measurements created after this change) or else using a default value (for old Measurements)? Otherwise the returned value won't have any methodologies.
</blockquote></details>

Done.
___
*[`src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsServiceTest.kt` line 875 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1154#-Nb_cxxC-P1dOMVf28m2:-NbaFk-cEFY0oF7q53fh:bxx9p3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cf8880c35f13caaaa7a627a80f3a4a2f89a3b29d/src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsServiceTest.kt#L875)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: prefer to use valid configurations in tests, unless checking for an error. I believe that direct protocol configs wouldn't specify this value
</blockquote></details>

Thanks for pointing it out! Fixed.


<!-- Sent from Reviewable.io -->

2023-08-14 18:00 UTC, SanjayVas requested changes
> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1154)* status: all files reviewed, 4 unresolved discussions (waiting on @renjiezh, @riemanli, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt` line 124 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1154#-NbRZKDF9m_03NtM6nYm:-NbpA6FIBndO5yz5E2Oc:b8f450i) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9fc024d1c2c9bf84d39998d79843736b9eb2822c/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt#L124)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Still not quite correct. All KDoc begins with a summary fragment. See https://developer.android.com/kotlin/style-guide#summary_fragment
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt` line 130 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1154#-NbpAMbT9WgUWQ8cY_Q5:-NbpAMbT9WgUWQ8cY_Q6:br7uv3o) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/56e50199fa0cc83d4053f59e569c69e62b2f3897/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt#L130)):*
> ```Kotlin
> const val DEFAULT_MAXIMUM_FREQUENCY_DIRECT_DISTRIBUTION = 20
> 
> val DEFAULT_DIRECT_NOISE_MECHANISMS: List<NoiseMechanism> =
> ```

nit: Public symbols should have KDoc.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt` line 402 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1154#-NbpBEDM4uM8gJmV9xB8:-NbpBEDM4uM8gJmV9xB9:b97xcjx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/56e50199fa0cc83d4053f59e569c69e62b2f3897/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt#L402)):*
> ```Kotlin
>     }
>     InternalProtocolConfig.ProtocolCase.DIRECT -> {
>       error("Direct protocol shouldn't be used when number of data providers is greater than 1.")
> ```

nit: I don't think this error message is quite accurate relative to the nearby code. I don't spot any checks for number of data providers here.



_Suggestion:_
```Kotlin
error("Direct protocol cannot be used for MPC-based Measurements")
```
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 154 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1154#-Nb_auex4rmy-hsXlayh:-NbpBbZkDDrg2XloEMfy:b-jeyxk4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cf8880c35f13caaaa7a627a80f3a4a2f89a3b29d/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L154)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Thanks for bringing this aspect. Do you know how noise mechanism selection really works on the EDP side? Do EDPs pick one and only one noise mechanism or do they pick the most preferred and acceptable one from the options? 

For the former scenario, `directNoiseMechanism` in the constructor can indicate that this is the only noise mechanism the EDP wants to use. For the latter, we can change `directNoiseMechanism` to a list of noise mechanisms in the order of preference. 
</blockquote></details>

The EDP **must** use one of the options defined in the protocol config. If they do not support any of the specified options, they **must** refuse the Requisition.

Therefore the logical way to implement this would be to check the options in the protocol config and pick from the subset that the EDP supports in some preference order. If none are supported by the EDP, refuse the Requisition.


<!-- Sent from Reviewable.io -->

2023-08-15 22:44 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1154)* status: 18 of 26 files reviewed, 3 unresolved discussions (waiting on @iverson52000, @renjiezh, @SanjayVas, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt` line 124 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1154#-NbRZKDF9m_03NtM6nYm:-NbpJHnR7wmT2DjgtdWt:b4foj5a) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9fc024d1c2c9bf84d39998d79843736b9eb2822c/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt#L124)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Still not quite correct. All KDoc begins with a summary fragment. See https://developer.android.com/kotlin/style-guide#summary_fragment
</blockquote></details>

Hope I got it right this time.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt` line 130 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1154#-NbpAMbT9WgUWQ8cY_Q5:-NbpPXrn0_UtSIxsmxN9:bi15axq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/56e50199fa0cc83d4053f59e569c69e62b2f3897/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt#L130)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: Public symbols should have KDoc.
</blockquote></details>

Thanks for pointing it out. Added.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt` line 402 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1154#-NbpBEDM4uM8gJmV9xB8:-NbpQ0mvAGKKyKOkVg_n:b2nhexc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/56e50199fa0cc83d4053f59e569c69e62b2f3897/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt#L402)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: I don't think this error message is quite accurate relative to the nearby code. I don't spot any checks for number of data providers here.
</blockquote></details>

Fix
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 154 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1154#-Nb_auex4rmy-hsXlayh:-NbvMNwf7dPnfqLrd0MJ:b-gurja9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cf8880c35f13caaaa7a627a80f3a4a2f89a3b29d/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L154)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The EDP **must** use one of the options defined in the protocol config. If they do not support any of the specified options, they **must** refuse the Requisition.

Therefore the logical way to implement this would be to check the options in the protocol config and pick from the subset that the EDP supports in some preference order. If none are supported by the EDP, refuse the Requisition.
</blockquote></details>

Done. Once @iverson52000 's #1170 is done, I will modify the noise mechanism selection logic accordingly.


<!-- Sent from Reviewable.io -->

2023-08-15 22:50 UTC, SanjayVas reviewed
> Reviewed 8 of 8 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1154)* status: all files reviewed, 1 unresolved discussion (waiting on @iverson52000, @renjiezh, and @tristanvuong2021)



<!-- Sent from Reviewable.io -->

2023-08-18 21:57 UTC, riemanli reviewed
@iverson52000 would you mind taking a quick look at the changes in the Laplace noiser and ACDP? Thanks

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1154#-:-Nc9dVfo0TiSCj9VzzsS:btddge7)* status: all files reviewed, 1 unresolved discussion (waiting on @iverson52000, @renjiezh, and @tristanvuong2021)



<!-- Sent from Reviewable.io -->

2023-08-21 20:52 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1154)* status: 22 of 27 files reviewed, 1 unresolved discussion (waiting on @iverson52000, @renjiezh, @SanjayVas, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 154 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1154#-Nb_auex4rmy-hsXlayh:-NcOr4xV4c1DzUazq97U:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cf8880c35f13caaaa7a627a80f3a4a2f89a3b29d/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L154)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Done. Once @iverson52000 's #1170 is done, I will modify the noise mechanism selection logic accordingly.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-08-22 18:13 UTC, iverson52000 requested changes
> Reviewed 2 of 18 files at r1, 1 of 8 files at r6, 4 of 12 files at r7.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1154)* status: 23 of 27 files reviewed, 3 unresolved discussions (waiting on @renjiezh, @riemanli, @SanjayVas, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 1410 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1154#-NcTLZ1P0FSUpwx_ztDk:-NcTLZ1P0FSUpwx_ztDl:b-1f0zcn) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ed4cf858cd3f05851d76eeb336cd5549e4bda63d/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L1410)):*
> ```Kotlin
>         DirectNoiseMechanism.CONTINUOUS_GAUSSIAN,
>       )
>     // The ACDP noise mechanisms for reach and frequency are in order of preference.
> ```

More accurate comment "The direct noise mechanisms for ACDP composition in PBM for for reach and frequency in order of preference. Currently ACDP composition only supports CONTINUOUS_GAUSSIAN noise for direct measurements"
___
*[`src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt` line 1191 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1154#-NcTQ97Z479EH6A3f3lC:-NcTQ97Z479EH6A3f3lD:b-96lc7m) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ed4cf858cd3f05851d76eeb336cd5549e4bda63d/src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt#L1191)):*
> ```Kotlin
> 
>   @Test
>   fun `refuses Requisition when directNoiseMechanism is LAPLACE and compositionMechanism is ACDP`() {
> ```

This test looks a bit weird now. The options provided by Kingdom should always be [CONTINUOUS_LAPLACE, CONTINUOUS_GAUSSIAN]? And under ACDP composition, the preferred can only be `CONTINUOUS_GAUSSIAN`.

Maybe modify this test to check if compositionMechanism is ACDP, then `assertThat(result.reach.noiseMechanism == CONTINUOUS_GAUSSIAN)`


<!-- Sent from Reviewable.io -->

2023-08-22 19:02 UTC, SanjayVas requested changes
> Reviewed 7 of 12 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1154)* status: 26 of 27 files reviewed, 8 unresolved discussions (waiting on @renjiezh, @riemanli, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt` line 356 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1154#-NcTPbiN1dsfcGKirb9e:-NcTPbiN1dsfcGKirb9f:b-ewgbhq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ed4cf858cd3f05851d76eeb336cd5549e4bda63d/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt#L356)):*
> ```Kotlin
>       }
>       ProtocolConfig.MeasurementType.POPULATION -> {
>         protocols += protocol { direct = direct {} }
> ```

What did we decide on w.r.t. population methodology? I assume there's really only one methodology since we just return the count of the specified sub-population.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 1158 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1154#-NcT__C95cBImRc3gFtK:-NcT__C95cBImRc3gFtL:btxpx23) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ed4cf858cd3f05851d76eeb336cd5549e4bda63d/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L1158)):*
> ```Kotlin
>    */
>   private fun buildDirectMeasurementResult(
>     requisition: Requisition,
> ```

If the only part of the Requisition we use is the Direct protocol config, pass that as the param instead.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 1217 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1154#-NcTZ8XY-Adzs0EkaP_K:-NcTZ8XY-Adzs0EkaP_L:b-e9b8wj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ed4cf858cd3f05851d76eeb336cd5549e4bda63d/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L1217)):*
> ```Kotlin
>             value = scaledNoisedReachValue
>             this.noiseMechanism = directNoiseMechanism.toProtocolConfigNoiseMechanism()
>             deterministicCountDistinct = deterministicCountDistinct {}
> ```

Use getDefaultInstance() rather than empty DSL builder for empty messages.



_Suggestion:_
```Kotlin
DeterministicCountDistinct.getDefaultInstance()
```
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 1405 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1154#-NcTYGrA4yKJNSbTXwsu:-NcTYGrBCGq61ed-xvhj:bwyarc6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ed4cf858cd3f05851d76eeb336cd5549e4bda63d/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L1405)):*
> ```Kotlin
> 
>     // The noise mechanisms for reach and frequency are in order of preference.
>     private val DIRECT_REACH_AND_FREQUENCY_NOISE_MECHANISM_PREFERENCES =
> ```

nit: This is *okay*, but don't worry about supporting arbitrary preference ordering. It would be fine to hard-code the preference order implicitly into the fulfillment logic:

* If mechanisms contains CONTINUOUS_LAPLACE, use that
* Else if mechanisms contains CONTINUOUS_GAUSSIAN, use that
* Else refuse
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 1429 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1154#-NcTXuRI0hpP5W8tZVWY:-NcTXuRI0hpP5W8tZVWZ:b-c78t9u) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ed4cf858cd3f05851d76eeb336cd5549e4bda63d/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L1429)):*
> ```Kotlin
>  * Converts a [NoiseMechanism] to [DirectNoiseMechanism?].
>  *
>  * Return null when no matched noise mechanism.
> ```

nit: use `@return` tag for this

See https://developer.android.com/kotlin/](https://developer.android.com/kotlin/style-guide#block_tags
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 1431 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1154#-NcTbPXZ2HBB_Q3Ppdc_:-NcTbPXZ2HBB_Q3Ppdca:b-dptnt5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ed4cf858cd3f05851d76eeb336cd5549e4bda63d/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L1431)):*
> ```Kotlin
>  * Return null when no matched noise mechanism.
>  */
> private fun NoiseMechanism.toEdpDirectNoiseMechanism(): DirectNoiseMechanism? {
> ```

It looks like this is called in 4 different places? We should just be able to convert once and pass it along.

Note that we technically only *need* to convert when calling the Noiser. I leave it to you to consider the tradeoffs of converting early (benefit is that we're already restricted to valid mechanisms for Direct protocol, with the downside that we'd may need to pass along the converted versions along with the API messages they come from).

Note that if the API gives us an invalid mechanism for the protocol, the Requisition should be refused with invalid spec since the API documentation specifically indicates that it's an error.


<!-- Sent from Reviewable.io -->

2023-08-22 22:50 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1154)* status: 23 of 27 files reviewed, 7 unresolved discussions (waiting on @iverson52000, @renjiezh, @SanjayVas, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt` line 356 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1154#-NcTPbiN1dsfcGKirb9e:-NcU1lBMDnHMA36mpyai:b-79egv7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ed4cf858cd3f05851d76eeb336cd5549e4bda63d/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt#L356)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

What did we decide on w.r.t. population methodology? I assume there's really only one methodology since we just return the count of the specified sub-population.
</blockquote></details>

It's deterministic count. Added.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 1158 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1154#-NcT__C95cBImRc3gFtK:-NcUJawC5Kalbm6oZA5V:b9jeawe) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ed4cf858cd3f05851d76eeb336cd5549e4bda63d/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L1158)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

If the only part of the Requisition we use is the Direct protocol config, pass that as the param instead.
</blockquote></details>

Done by using a data class to wrap the direct protocol config and the selected noise mechanism.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 1217 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1154#-NcTZ8XY-Adzs0EkaP_K:-NcU3Lij3FYWhdxnWQgl:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ed4cf858cd3f05851d76eeb336cd5549e4bda63d/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L1217)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Use getDefaultInstance() rather than empty DSL builder for empty messages.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 1405 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1154#-NcTYGrA4yKJNSbTXwsu:-NcULWPM9iZ82ihCjCP2:b-3nnd4k) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ed4cf858cd3f05851d76eeb336cd5549e4bda63d/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L1405)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: This is *okay*, but don't worry about supporting arbitrary preference ordering. It would be fine to hard-code the preference order implicitly into the fulfillment logic:

* If mechanisms contains CONTINUOUS_LAPLACE, use that
* Else if mechanisms contains CONTINUOUS_GAUSSIAN, use that
* Else refuse
</blockquote></details>

Would like to keep the current code if it's ok. The if-else would have many branches when taking ACDP into consideration and when options get more.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 1410 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1154#-NcTLZ1P0FSUpwx_ztDk:-NcU3aXJ8sx9ET3ysP1a:b-bjudbj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ed4cf858cd3f05851d76eeb336cd5549e4bda63d/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L1410)):*
<details><summary><i>Previously, iverson52000 (Albert Hsu) wrote…</i></summary><blockquote>

More accurate comment "The direct noise mechanisms for ACDP composition in PBM for for reach and frequency in order of preference. Currently ACDP composition only supports CONTINUOUS_GAUSSIAN noise for direct measurements"
</blockquote></details>

Thanks for the suggestion! Done.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 1429 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1154#-NcTXuRI0hpP5W8tZVWY:-NcU4UAOCIyx1q8Q3uaF:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ed4cf858cd3f05851d76eeb336cd5549e4bda63d/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L1429)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: use `@return` tag for this

See https://developer.android.com/kotlin/](https://developer.android.com/kotlin/style-guide#block_tags
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 1431 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1154#-NcTbPXZ2HBB_Q3Ppdc_:-NcUINmV0ZD_dxThswzo:bkmp09p) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ed4cf858cd3f05851d76eeb336cd5549e4bda63d/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L1431)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

It looks like this is called in 4 different places? We should just be able to convert once and pass it along.

Note that we technically only *need* to convert when calling the Noiser. I leave it to you to consider the tradeoffs of converting early (benefit is that we're already restricted to valid mechanisms for Direct protocol, with the downside that we'd may need to pass along the converted versions along with the API messages they come from).

Note that if the API gives us an invalid mechanism for the protocol, the Requisition should be refused with invalid spec since the API documentation specifically indicates that it's an error.
</blockquote></details>

I converted the noise mechanism up front as suggested. 
___
*[`src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt` line 1191 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1154#-NcTQ97Z479EH6A3f3lC:-NcUMjJS3vqeRm3XScjO:b7s0asu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ed4cf858cd3f05851d76eeb336cd5549e4bda63d/src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt#L1191)):*
> The options provided by Kingdom should always be \[CONTINUOUS\_LAPLACE, CONTINUOUS\_GAUSSIAN\]?

I am not sure if that's a true statement. For an EDP, it should not assume what the options are, right? The code now selects the noise mechanism based on measurement types and composition method. It throw exceptions when no valid options.

Renamed the test name to fit the test better if that solves the issue.


<!-- Sent from Reviewable.io -->

2023-08-22 23:14 UTC, iverson52000 requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1154)* status: 23 of 27 files reviewed, 7 unresolved discussions (waiting on @renjiezh, @riemanli, @SanjayVas, and @tristanvuong2021)

___
*[`src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt` line 1191 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1154#-NcTQ97Z479EH6A3f3lC:-NcUVX3TAtgFwT4v4tbU:b5jnydc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ed4cf858cd3f05851d76eeb336cd5549e4bda63d/src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt#L1191)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

> The options provided by Kingdom should always be \[CONTINUOUS\_LAPLACE, CONTINUOUS\_GAUSSIAN\]?

I am not sure if that's a true statement. For an EDP, it should not assume what the options are, right? The code now selects the noise mechanism based on measurement types and composition method. It throw exceptions when no valid options.

Renamed the test name to fit the test better if that solves the issue.
</blockquote></details>

Got it. Make sense. The `directNoiseMechanism` here could be misleading that it looks like the preferred noiseMechanism selected by EDP but it's not. Maybe rephrase it to "refuses Requisition when directNoiseMechanism option provided by Kingdom is not CONTINUOUS_GAUSSIAN and compositionMechanism is ACDP"?


<!-- Sent from Reviewable.io -->

2023-08-22 23:19 UTC, SanjayVas requested changes
> Reviewed 2 of 12 files at r7, 4 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1154)* status: all files reviewed, 4 unresolved discussions (waiting on @renjiezh, @riemanli, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 145 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1154#-NcUUVAPEpnFCzD1q5UR:-NcUUVAQ4QFk_N8BTPtq:bfz5oqv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1211b030b09539d3a77d6953df11a986db4ffbd3/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L145)):*
> ```Kotlin
> )
> 
> private class RequisitionRefusalException(
> ```

This should ideally still be private to EdpSimulator since it's specific to that class. You may be able to move it to the companion object and put any functions that need to use it but not access instance state there.

See related comment on the extension function.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 1479 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1154#-NcUVxXaAvCXmOmm4giX:-NcUVxXaAvCXmOmm4giY:btyc5ul) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1211b030b09539d3a77d6953df11a986db4ffbd3/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L1479)):*
> ```Kotlin
>  *
>  * @return [DirectNoiseMechanism] when there is a matched.
>  * @throws [RequisitionRefusalException] with SPEC_INVALID when no matched noise mechanism.
> ```

This shouldn't be thrown by an extension method that's not specific to the EdpSimulator class.

Either
1. Move this into the companion object of EdpSimulator so it's clear it's specific to the class (as opposed to any other type that might end up defined in this file).
2. Go back to returning null, and make sure the calling code throws the exception if the returned value is null. e.g.
    ```kotlin
    val directNoiseMechanism: DirectNoiseMechanism = noiseMechanism.toDirectNoiseMechanism() ?: throw RequisitionRefusalException(...)
    ```


<!-- Sent from Reviewable.io -->

2023-08-22 23:47 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1154)* status: 25 of 27 files reviewed, 4 unresolved discussions (waiting on @iverson52000, @renjiezh, @SanjayVas, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 145 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1154#-NcUUVAPEpnFCzD1q5UR:-NcUcJIq1p67WTRmYGh1:bakm1l4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1211b030b09539d3a77d6953df11a986db4ffbd3/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L145)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This should ideally still be private to EdpSimulator since it's specific to that class. You may be able to move it to the companion object and put any functions that need to use it but not access instance state there.

See related comment on the extension function.
</blockquote></details>

Thanks for the suggestions. Moved it back.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 1479 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1154#-NcUVxXaAvCXmOmm4giX:-NcUbIp8DnyixcTAU78l:b-bjvw4r) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1211b030b09539d3a77d6953df11a986db4ffbd3/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L1479)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This shouldn't be thrown by an extension method that's not specific to the EdpSimulator class.

Either
1. Move this into the companion object of EdpSimulator so it's clear it's specific to the class (as opposed to any other type that might end up defined in this file).
2. Go back to returning null, and make sure the calling code throws the exception if the returned value is null. e.g.
    ```kotlin
    val directNoiseMechanism: DirectNoiseMechanism = noiseMechanism.toDirectNoiseMechanism() ?: throw RequisitionRefusalException(...)
    ```
</blockquote></details>

Did a variant of (2). The conversion method returns a nullable `DirectNoiseMechanism`. Since the noise mechanism selection process would throw an exception when there is no matched, I simply filtered out null from the options. Please see the changes.
___
*[`src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt` line 1191 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1154#-NcTQ97Z479EH6A3f3lC:-NcUaO97-Tmnt_MBJ00l:bqthia0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ed4cf858cd3f05851d76eeb336cd5549e4bda63d/src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt#L1191)):*
<details><summary><i>Previously, iverson52000 (Albert Hsu) wrote…</i></summary><blockquote>

Got it. Make sense. The `directNoiseMechanism` here could be misleading that it looks like the preferred noiseMechanism selected by EDP but it's not. Maybe rephrase it to "refuses Requisition when directNoiseMechanism option provided by Kingdom is not CONTINUOUS_GAUSSIAN and compositionMechanism is ACDP"?
</blockquote></details>

SGTM. Done.


<!-- Sent from Reviewable.io -->

2023-08-23 16:28 UTC, iverson52000 approved these changes
> Reviewed 2 of 18 files at r1, 4 of 9 files at r2, 2 of 11 files at r3, 3 of 7 files at r4, 1 of 4 files at r5, 5 of 12 files at r7, 2 of 4 files at r8, 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1154)* status: all files reviewed, 1 unresolved discussion (waiting on @renjiezh, @SanjayVas, @stevenwarejones, and @tristanvuong2021)



<!-- Sent from Reviewable.io -->

2023-08-24 14:33 UTC, stevenwarejones requested changes
> Reviewed 1 of 18 files at r1, 4 of 9 files at r2, 1 of 11 files at r3, 2 of 7 files at r4, 1 of 8 files at r6, 8 of 12 files at r7, 1 of 4 files at r8, 1 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1154)* status: all files reviewed, 3 unresolved discussions (waiting on @renjiezh, @riemanli, @SanjayVas, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/server/V2alphaPublicApiServer.kt` line 237 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1154#-Ncbx_WPEytgmd99G9Ob:-Ncbx_WPEytgmd99G9Oc:b-mx8tw3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/74a43e4994c6dcd61fc30290a8a6f969e4396e14/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/server/V2alphaPublicApiServer.kt#L237)):*
> ```Kotlin
>         NoiseMechanism.CONTINUOUS_GAUSSIAN -> {}
>         NoiseMechanism.GEOMETRIC,
>         NoiseMechanism.DISCRETE_GAUSSIAN -> {
> ```

why are we also not wanting to allow these?
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/system/v1alpha/ProtoConversions.kt` line 394 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1154#-NcbuyF6AVG1cNy_XF9j:-NcbuyF6AVG1cNy_XF9k:benapse) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/74a43e4994c6dcd61fc30290a8a6f969e4396e14/src/main/kotlin/org/wfanet/measurement/kingdom/service/system/v1alpha/ProtoConversions.kt#L394)):*
> ```Kotlin
>     InternalNoiseMechanism.DISCRETE_GAUSSIAN -> NoiseMechanism.DISCRETE_GAUSSIAN
>     InternalNoiseMechanism.CONTINUOUS_LAPLACE,
>     InternalNoiseMechanism.CONTINUOUS_GAUSSIAN,
> ```

why are these invalid?


<!-- Sent from Reviewable.io -->

2023-08-24 17:04 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1154)* status: all files reviewed, 3 unresolved discussions (waiting on @renjiezh, @SanjayVas, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/system/v1alpha/ProtoConversions.kt` line 394 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1154#-NcbuyF6AVG1cNy_XF9j:-NccTy2e5_waEmqBuoAU:b-olkp7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/74a43e4994c6dcd61fc30290a8a6f969e4396e14/src/main/kotlin/org/wfanet/measurement/kingdom/service/system/v1alpha/ProtoConversions.kt#L394)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

why are these invalid?
</blockquote></details>

Good question. The code before this change only used discrete types of noises as shown in https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/60dea185d6de36e245b125ab1d61c338d9f8a0d7/src/main/proto/wfa/measurement/system/v1alpha/computation.proto#L110-L117 

In order not to change the behavior by adding new types, the new types should be treated as errors. 

cc @renjiezh 


<!-- Sent from Reviewable.io -->

2023-08-25 16:56 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1154)* status: all files reviewed, 3 unresolved discussions (waiting on @renjiezh, @SanjayVas, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/server/V2alphaPublicApiServer.kt` line 237 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1154#-Ncbx_WPEytgmd99G9Ob:-Nchbj345RtLpqE3OlbR:b-d6cjfj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/74a43e4994c6dcd61fc30290a8a6f969e4396e14/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/server/V2alphaPublicApiServer.kt#L237)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

why are we also not wanting to allow these?
</blockquote></details>

Discrete types of noise are not supported for direct measurement.


<!-- Sent from Reviewable.io -->

2023-08-31 22:10 UTC, stevenwarejones approved these changes
> Reviewed 3 of 18 files at r1, 1 of 11 files at r3, 1 of 7 files at r4, 1 of 4 files at r5, 1 of 4 files at r8, 1 of 2 files at r9.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1154)* status: all files reviewed, 3 unresolved discussions (waiting on @jiayu-google, @renjiezh, @SanjayVas, and @tristanvuong2021)



<!-- Sent from Reviewable.io -->

2023-09-01 20:34 UTC, stevenwarejones approved these changes
> Reviewed 7 of 7 files at r10.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1154)* status: all files reviewed, 2 unresolved discussions (waiting on @jiayu-google, @renjiezh, @riemanli, @SanjayVas, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/server/V2alphaPublicApiServer.kt` line 237 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1154#-Ncbx_WPEytgmd99G9Ob:-NdHRvJX4t5WfcYykz84:b-6u9nir) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/74a43e4994c6dcd61fc30290a8a6f969e4396e14/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/server/V2alphaPublicApiServer.kt#L237)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Discrete types of noise are not supported for direct measurement.
</blockquote></details>

as discussed, maybe add a note to support discrete later


<!-- Sent from Reviewable.io -->

2023-09-01 21:09 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1154)* status: 26 of 27 files reviewed, 1 unresolved discussion (waiting on @iverson52000, @jiayu-google, @renjiezh, @SanjayVas, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/server/V2alphaPublicApiServer.kt` line 237 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1154#-Ncbx_WPEytgmd99G9Ob:-NdHZtyjB-bGYeiYxV_Y:bb6un1j) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/74a43e4994c6dcd61fc30290a8a6f969e4396e14/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/server/V2alphaPublicApiServer.kt#L237)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

as discussed, maybe add a note to support discrete later
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-09-01 21:48 UTC, riemanli reviewed
> Reviewed 4 of 18 files at r1, 4 of 9 files at r2, 2 of 11 files at r3, 1 of 7 files at r4, 1 of 8 files at r6, 5 of 12 files at r7, 1 of 4 files at r8, 1 of 2 files at r9, 7 of 7 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1154)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jiayu-google, @renjiezh, @SanjayVas, and @tristanvuong2021)



<!-- Sent from Reviewable.io -->

2023-09-01 23:03 UTC, merged