Adding the class ReachOnlyLiquidLegionsV2Mill on the Duchy mill.
world-federation-of-advertisers/cross-media-measurement pull request #1155
Opened 2023-08-06 00:40 UTC by ple13

2023-08-06 00:40 UTC, wfa-reviewable commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1155)
<!-- Reviewable:end -->

2023-08-08 18:38 UTC, renjiezh reviewed
> Reviewed 1 of 22 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1155)* status: 18 of 22 files reviewed, 2 unresolved discussions (waiting on @kungfucraig, @ple13, and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/ReachOnlyLiquidLegionsV2Mill.kt` line 455 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1155#-NbG1f0Q1LgJE4XuicjG:-NbLR30S-D08buWVcSxS:bcnwh21) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8adb7fe18a4274d8a7efa259c09e3e01e310d2d8/src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/ReachOnlyLiquidLegionsV2Mill.kt#L455)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This Mill is exclusively for RO LLv2. I don't think we need to specify this in method names.
</blockquote></details>

It will be helpful to use global text replacement to refactor the function names as the IDEA's refactor won't help for both Kotlin and c++ code at once.


<!-- Sent from Reviewable.io -->

2023-08-08 19:24 UTC, renjiezh requested changes
> Reviewed 14 of 22 files at r1, 7 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1155)* status: all files reviewed, 5 unresolved discussions (waiting on @kungfucraig, @ple13, and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/ReachOnlyLiquidLegionsV2Mill.kt` line 568 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1155#-NbLXb1K0xcsv31nahH6:-NbLXb1K0xcsv31nahH7:bg0p5xh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8adb7fe18a4274d8a7efa259c09e3e01e310d2d8/src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/ReachOnlyLiquidLegionsV2Mill.kt#L568)):*
> ```Kotlin
>             }
>           }
>           liquidLegionsParameters = liquidLegionsSketchParameters {
> ```

nit: Could you help to rename this field to `sketchParameters`.
___
*[`src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/ReachOnlyLiquidLegionsV2MillTest.kt` line 1909 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1155#-NbL_se4C5Gm1F2cTMPN:-NbL_se4C5Gm1F2cTMPO:b-waoonn) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8adb7fe18a4274d8a7efa259c09e3e01e310d2d8/src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/ReachOnlyLiquidLegionsV2MillTest.kt#L1909)):*
> ```Kotlin
>   }
> }
> ```

Could we have a unit test to exercise the parsing of excessive_noise?
___
*[`src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/crypto/BUILD.bazel` line 0 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1155#-NbLYvdDE47j4VAIWQwn:-NbLYvdE5e7i5Gv5KOh-:b-je7kew) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8adb7fe18a4274d8a7efa259c09e3e01e310d2d8/src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/crypto/BUILD.bazel#L0)):*
Does it make sense to have a separated folder for rollv2's mill test like `.../daemon/mill/reachonlyliquidlegionsv2`


<!-- Sent from Reviewable.io -->

2023-08-08 22:15 UTC, kungfucraig requested changes
> Reviewed 15 of 22 files at r1, 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1155)* status: all files reviewed, 7 unresolved discussions (waiting on @ple13 and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/ReachOnlyLiquidLegionsV2Mill.kt` line 460 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1155#-NbMBoVa0d8yXJ9abdji:-NbMBoVbAurb_CNQzqbx:b-i66mts) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8adb7fe18a4274d8a7efa259c09e3e01e310d2d8/src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/ReachOnlyLiquidLegionsV2Mill.kt#L460)):*
> ```Kotlin
>     val rollv2Details = token.computationDetails.reachOnlyLiquidLegionsV2
>     require(AGGREGATOR == rollv2Details.role) { "invalid role for this function." }
>     val (bytes, nextToken) =
> ```

What are the types of these two things? And what do they represent? I'm having a hard time understanding how we're unpacking a tuple out of the CRV, so I assume I'm missing something important. :)
___
*[`src/main/swig/protocol/reachonlyliquidlegionsv2/reach_only_liquid_legions_v2_encryption_utility.swig` line 19 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1155#-NbLG2pY3q6MvFeDHcHR:-NbLG2pZ8mETw08RVxY4:bdsu90z) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8adb7fe18a4274d8a7efa259c09e3e01e310d2d8/src/main/swig/protocol/reachonlyliquidlegionsv2/reach_only_liquid_legions_v2_encryption_utility.swig#L19)):*
> ```
> #include "wfa/measurement/internal/duchy/protocol/liquid_legions_v2/reach_only_liquid_legions_v2_encryption_utility_wrapper.h"
> %}
> ```

Can we factor our and include conversions from: https://sourcegraph.com/github.com/world-federation-of-advertisers/cross-media-measurement/-/blob/src/main/swig/protocol/liquidlegionsv2/liquid_legions_v2_encryption_utility.swig

If so, it'd be nice if the factoring out were in a different PR.


<!-- Sent from Reviewable.io -->

2023-08-08 22:43 UTC, renjiezh reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1155)* status: all files reviewed, 7 unresolved discussions (waiting on @kungfucraig, @ple13, and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/ReachOnlyLiquidLegionsV2Mill.kt` line 460 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1155#-NbMBoVa0d8yXJ9abdji:-NbMI8El9r9TIHalHjDi:b-wz7ee8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8adb7fe18a4274d8a7efa259c09e3e01e310d2d8/src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/ReachOnlyLiquidLegionsV2Mill.kt#L460)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

What are the types of these two things? And what do they represent? I'm having a hard time understanding how we're unpacking a tuple out of the CRV, so I assume I'm missing something important. :)
</blockquote></details>

It is the trick of `existingOutputOr` returning the tuple of `bytestring` and `token`. Function `existingOutputOr` takes a token and a block. It execute the block to get the result of `bytestring`, than update the token with the result. Thus it returns `bytestring` and `new_token` as a pair. 
The CRV operations only produce the `bytestring` though.


<!-- Sent from Reviewable.io -->

2023-08-08 22:46 UTC, renjiezh reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1155)* status: all files reviewed, 7 unresolved discussions (waiting on @kungfucraig, @ple13, and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/ReachOnlyLiquidLegionsV2Mill.kt` line 460 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1155#-NbMBoVa0d8yXJ9abdji:-NbMJg2mDbuDuZ8BM0Ed:bwnfoeh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8adb7fe18a4274d8a7efa259c09e3e01e310d2d8/src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/ReachOnlyLiquidLegionsV2Mill.kt#L460)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

It is the trick of `existingOutputOr` returning the tuple of `bytestring` and `token`. Function `existingOutputOr` takes a token and a block. It execute the block to get the result of `bytestring`, than update the token with the result. Thus it returns `bytestring` and `new_token` as a pair. 
The CRV operations only produce the `bytestring` though.
</blockquote></details>

The name `existingOutput` is because that, it checks if the result is already there. Otherwise it execute the block to get the result. Yeah, the name does not imply the return type which causes the confusion.


<!-- Sent from Reviewable.io -->

2023-08-09 21:15 UTC, ple13 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1155)* status: 18 of 22 files reviewed, 7 unresolved discussions (waiting on @kungfucraig, @renjiezh, and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/ReachOnlyLiquidLegionsV2Mill.kt` line 217 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1155#-NbG1Hs1BAHl8KWVWNcn:-NbQvPMG0dNNq2YcJsK_:bt2vr1b) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8adb7fe18a4274d8a7efa259c09e3e01e310d2d8/src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/ReachOnlyLiquidLegionsV2Mill.kt#L217)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Use Kotlin DSL rather than Java builders for protobufs in new code.
</blockquote></details>

Fixed.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/ReachOnlyLiquidLegionsV2Mill.kt` line 455 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1155#-NbG1f0Q1LgJE4XuicjG:-NbQx0lI9qQeqq4Y9CV7:bt2vr1b) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8adb7fe18a4274d8a7efa259c09e3e01e310d2d8/src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/ReachOnlyLiquidLegionsV2Mill.kt#L455)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

It will be helpful to use global text replacement to refactor the function names as the IDEA's refactor won't help for both Kotlin and c++ code at once.
</blockquote></details>

Fixed.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/ReachOnlyLiquidLegionsV2Mill.kt` line 460 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1155#-NbMBoVa0d8yXJ9abdji:-NbQxC-mAw-_IAmN2Rpj:b-vl354f) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8adb7fe18a4274d8a7efa259c09e3e01e310d2d8/src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/ReachOnlyLiquidLegionsV2Mill.kt#L460)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

The name `existingOutput` is because that, it checks if the result is already there. Otherwise it execute the block to get the result. Yeah, the name does not imply the return type which causes the confusion.
</blockquote></details>

Thanks Renjie for the explanation!
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/ReachOnlyLiquidLegionsV2Mill.kt` line 568 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1155#-NbLXb1K0xcsv31nahH6:-NbR5fWFCrik5yfdYqSz:b-5sanis) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8adb7fe18a4274d8a7efa259c09e3e01e310d2d8/src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/ReachOnlyLiquidLegionsV2Mill.kt#L568)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

nit: Could you help to rename this field to `sketchParameters`.
</blockquote></details>

This change required modifying the c++ code and many other places. I think it's better to have a separate PR that changes it and to do other clean up as well. 
___
*[`src/main/swig/protocol/reachonlyliquidlegionsv2/reach_only_liquid_legions_v2_encryption_utility.swig` line 19 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1155#-NbLG2pY3q6MvFeDHcHR:-NbQzNVF03od8cxnhtgc:bdwu2iq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8adb7fe18a4274d8a7efa259c09e3e01e310d2d8/src/main/swig/protocol/reachonlyliquidlegionsv2/reach_only_liquid_legions_v2_encryption_utility.swig#L19)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Can we factor our and include conversions from: https://sourcegraph.com/github.com/world-federation-of-advertisers/cross-media-measurement/-/blob/src/main/swig/protocol/liquidlegionsv2/liquid_legions_v2_encryption_utility.swig

If so, it'd be nice if the factoring out were in a different PR.
</blockquote></details>

I'll check if it's possible.
___
*[`src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/ReachOnlyLiquidLegionsV2MillTest.kt` line 1909 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1155#-NbL_se4C5Gm1F2cTMPN:-NbQy3hDBAHPIzWudZ_u:baet3hc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8adb7fe18a4274d8a7efa259c09e3e01e310d2d8/src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/ReachOnlyLiquidLegionsV2MillTest.kt#L1909)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

Could we have a unit test to exercise the parsing of excessive_noise?
</blockquote></details>

There are tests for the excessive noise in the PR. The only test is to check that the size of the string reading from input blob is at least 66 bytes (as its length is at least the length of ciphertext (66) plus length of crv (at least 0). The correctness of the parsing is tested with the crypto code, and also with the JNI tests.
___
*[`src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/crypto/BUILD.bazel` line  at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1155#-NbLYvdDE47j4VAIWQwn:-NbQyZW63Y-jHbRaWZoA:b-whjx46) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8adb7fe18a4274d8a7efa259c09e3e01e310d2d8/src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/crypto/BUILD.bazel#L)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

Does it make sense to have a separated folder for rollv2's mill test like `.../daemon/mill/reachonlyliquidlegionsv2`
</blockquote></details>

The code didn't compile when I had them in the same folder. I'm not sure if there is some way around it, but putting them in a separate folder makes it compilable.


<!-- Sent from Reviewable.io -->

2023-08-11 17:13 UTC, SanjayVas approved these changes
> Reviewed 2 of 22 files at r1, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1155)* status: all files reviewed, 6 unresolved discussions (waiting on @kungfucraig, @ple13, and @renjiezh)

___
*[`src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/ReachOnlyLiquidLegionsV2MillTest.kt` line 1 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1155#-Nb__-5u4H30IGyvZjSg:-Nb__-5u4H30IGyvZjSh:b-el4un9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e0e11a3e29ae00e32c1358f5dff50d44c211f16c/src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/ReachOnlyLiquidLegionsV2MillTest.kt#L1)):*
> ```Kotlin
> // Copyright 2023 The Cross-Media Measurement Authors
> ```

I'd prefer if this hadn't just blindly copied the existing R/F LLv2 Mill test as it has a lot of cruft, but I understand the desire for expediency.


<!-- Sent from Reviewable.io -->

2023-08-11 21:00 UTC, renjiezh approved these changes
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1155)* status: all files reviewed, 4 unresolved discussions (waiting on @kungfucraig and @ple13)

___
*[`src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/crypto/ReachOnlyLiquidLegionsV2EncryptionUtilityTest.kt` line 272 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1155#-NbaOJNv9pu6jI5Jtllo:-NbaOJNv9pu6jI5Jtllp:bmesgu5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e0e11a3e29ae00e32c1358f5dff50d44c211f16c/src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/crypto/ReachOnlyLiquidLegionsV2EncryptionUtilityTest.kt#L272)):*
> ```Kotlin
>             combineElGamalPublicKeysRequest {
>                 curveId = CURVE_ID
>                 elGamalKeys.add(DUCHY_1_EL_GAMAL_KEYS.publicKey.toAnySketchElGamalPublicKey())
> ```

nit: `elGamalKeys += DUCHY_1_EL_GAMAL_KEYS.publicKey.toAnySketchElGamalPublicKey()`
We try to use `+=` instead of `.add()`


<!-- Sent from Reviewable.io -->

2023-08-14 14:16 UTC, kungfucraig approved these changes
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1155)* status: all files reviewed, 3 unresolved discussions (waiting on @ple13)

___
*[`src/main/swig/protocol/reachonlyliquidlegionsv2/reach_only_liquid_legions_v2_encryption_utility.swig` line 19 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1155#-NbLG2pY3q6MvFeDHcHR:-NboOxa01Iv43d_mU-bQ:b-39es4f) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8adb7fe18a4274d8a7efa259c09e3e01e310d2d8/src/main/swig/protocol/reachonlyliquidlegionsv2/reach_only_liquid_legions_v2_encryption_utility.swig#L19)):*
<details><summary><i>Previously, ple13 (Phi) wrote…</i></summary><blockquote>

I'll check if it's possible.
</blockquote></details>

We can come back and do this in a follow-up.


<!-- Sent from Reviewable.io -->

2023-08-14 14:17 UTC, kungfucraig approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1155)* status: all files reviewed, 2 unresolved discussions (waiting on @ple13)



<!-- Sent from Reviewable.io -->

2023-08-14 18:21 UTC, ple13 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1155)* status: all files reviewed, 2 unresolved discussions (waiting on @renjiezh and @SanjayVas)

___
*[`src/main/swig/protocol/reachonlyliquidlegionsv2/reach_only_liquid_legions_v2_encryption_utility.swig` line 19 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1155#-NbLG2pY3q6MvFeDHcHR:-NbpGHMY-6Tbghjgtsax:barwgu3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8adb7fe18a4274d8a7efa259c09e3e01e310d2d8/src/main/swig/protocol/reachonlyliquidlegionsv2/reach_only_liquid_legions_v2_encryption_utility.swig#L19)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

We can come back and do this in a follow-up.
</blockquote></details>

Sure. I will have a separate PR to clean this and other stuff up.
___
*[`src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/ReachOnlyLiquidLegionsV2MillTest.kt` line 1 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1155#-Nb__-5u4H30IGyvZjSg:-NbpFomg9YMxHijf0FbF:b-rok2dn) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e0e11a3e29ae00e32c1358f5dff50d44c211f16c/src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/ReachOnlyLiquidLegionsV2MillTest.kt#L1)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I'd prefer if this hadn't just blindly copied the existing R/F LLv2 Mill test as it has a lot of cruft, but I understand the desire for expediency.
</blockquote></details>

Yeah. It is faster this way.
___
*[`src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/crypto/ReachOnlyLiquidLegionsV2EncryptionUtilityTest.kt` line 272 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1155#-NbaOJNv9pu6jI5Jtllo:-NbpFmQREzLNvwdVxo6_:bt2vr1b) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e0e11a3e29ae00e32c1358f5dff50d44c211f16c/src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/crypto/ReachOnlyLiquidLegionsV2EncryptionUtilityTest.kt#L272)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

nit: `elGamalKeys += DUCHY_1_EL_GAMAL_KEYS.publicKey.toAnySketchElGamalPublicKey()`
We try to use `+=` instead of `.add()`
</blockquote></details>

Fixed.


<!-- Sent from Reviewable.io -->

2023-08-15 16:12 UTC, stevenwarejones reviewed
> Reviewed 12 of 22 files at r1, 2 of 7 files at r2, 1 of 4 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1155)* status: all files reviewed, 2 unresolved discussions (waiting on @ple13, @renjiezh, and @SanjayVas)

___
*[`src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/ReachOnlyLiquidLegionsV2MillTest.kt` line 1 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1155#-Nb__-5u4H30IGyvZjSg:-NbtubchANlXWQ_IwAYo:b6u4y8j) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e0e11a3e29ae00e32c1358f5dff50d44c211f16c/src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/ReachOnlyLiquidLegionsV2MillTest.kt#L1)):*
<details><summary><i>Previously, ple13 (Phi) wrote…</i></summary><blockquote>

Yeah. It is faster this way.
</blockquote></details>

how much work would it be to make it an abstract test so we only have to refactor this one time in the future?


<!-- Sent from Reviewable.io -->

2023-08-15 19:27 UTC, ple13 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1155)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @stevenwarejones)

___
*[`src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/ReachOnlyLiquidLegionsV2MillTest.kt` line 1 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1155#-Nb__-5u4H30IGyvZjSg:-Nbuczv80DZ0UivUZk5X:b-qirnaj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e0e11a3e29ae00e32c1358f5dff50d44c211f16c/src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/ReachOnlyLiquidLegionsV2MillTest.kt#L1)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

how much work would it be to make it an abstract test so we only have to refactor this one time in the future?
</blockquote></details>

I think I could make it work. However, as I'm very new to kotlin, it will probably take some time. I think the optimal way is to merge this PR, so that Renjie can submit his integration test and run the benchmarking. I'll have a separate PR to clean this up. What do you think?


<!-- Sent from Reviewable.io -->

2023-08-16 13:31 UTC, stevenwarejones approved these changes
> Reviewed 2 of 22 files at r1, 1 of 7 files at r2, 1 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1155)* status: all files reviewed, 1 unresolved discussion (waiting on @ple13 and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/ReachOnlyLiquidLegionsV2Mill.kt` line 444 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1155#-NbyXXm007zULLXMvf_w:-NbyXXm10NUqWgGZvAAR:b-h5z3cu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/93e40d5b7ddb4d1e70fcc098c37d0a762941a206/src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/ReachOnlyLiquidLegionsV2Mill.kt#L444)):*
> ```Kotlin
> 
>   /** Processes computation in the confirmation phase */
>   private suspend fun confirmationPhase(token: ComputationToken): ComputationToken {
> ```

I'd also like refactoring of the common pieces out of this and `LiquidLegionsV2Mill` as a follow-up
___
*[`src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/ReachOnlyLiquidLegionsV2MillTest.kt` line 1 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1155#-Nb__-5u4H30IGyvZjSg:-NbyWoF-3bFT4xmRcnSL:bb7ohn6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e0e11a3e29ae00e32c1358f5dff50d44c211f16c/src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/ReachOnlyLiquidLegionsV2MillTest.kt#L1)):*
<details><summary><i>Previously, ple13 (Phi) wrote…</i></summary><blockquote>

I think I could make it work. However, as I'm very new to kotlin, it will probably take some time. I think the optimal way is to merge this PR, so that Renjie can submit his integration test and run the benchmarking. I'll have a separate PR to clean this up. What do you think?
</blockquote></details>

sgtm
___
*[`src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/crypto/JniReachOnlyLiquidLegionsV2EncryptionTest.kt` line 33 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1155#-NbyWwBSBkkPxyZ5qsmy:-NbyWwBSBkkPxyZ5qsmz:b-3ip5r1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/93e40d5b7ddb4d1e70fcc098c37d0a762941a206/src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/crypto/JniReachOnlyLiquidLegionsV2EncryptionTest.kt#L33)):*
> ```Kotlin
>           .completeReachOnlySetupPhase(CompleteReachOnlySetupPhaseRequest.getDefaultInstance())
>       }
>     assertThat(e1.message).contains("ECGroup::CreateGroup() - Could not create group.")
> ```

I think the practive we've been adopting is to only check the error type (ie RunTime) and not the message content. fyi @SanjayVas 
___
*[`src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/crypto/JniReachOnlyLiquidLegionsV2EncryptionTest.kt` line 41 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1155#-NbyX3BC4d_AaTdc2Y94:-NbyX3BC4d_AaTdc2Y95:b-7ropln) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/93e40d5b7ddb4d1e70fcc098c37d0a762941a206/src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/crypto/JniReachOnlyLiquidLegionsV2EncryptionTest.kt#L41)):*
> ```Kotlin
>           .combineElGamalPublicKeys(CombineElGamalPublicKeysRequest.getDefaultInstance())
>       }
>     assertThat(e2.message).contains("Keys cannot be empty")
> ```

ditto


<!-- Sent from Reviewable.io -->

2023-08-16 18:44 UTC, ple13 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1155)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/ReachOnlyLiquidLegionsV2Mill.kt` line 444 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1155#-NbyXXm007zULLXMvf_w:-NbzBkfi5v8hpS-Rti96:bwygxsx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/93e40d5b7ddb4d1e70fcc098c37d0a762941a206/src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/ReachOnlyLiquidLegionsV2Mill.kt#L444)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

I'd also like refactoring of the common pieces out of this and `LiquidLegionsV2Mill` as a follow-up
</blockquote></details>

Noted.
___
*[`src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/ReachOnlyLiquidLegionsV2MillTest.kt` line 1 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1155#-Nb__-5u4H30IGyvZjSg:-NbzBlqO4fDhYlZc2PQc:b-ucfkn4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e0e11a3e29ae00e32c1358f5dff50d44c211f16c/src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/ReachOnlyLiquidLegionsV2MillTest.kt#L1)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

sgtm
</blockquote></details>

Thanks.
___
*[`src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/crypto/JniReachOnlyLiquidLegionsV2EncryptionTest.kt` line 33 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1155#-NbyWwBSBkkPxyZ5qsmy:-NbzcvyrCpDECP0C63LQ:b-c9h4ty) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/93e40d5b7ddb4d1e70fcc098c37d0a762941a206/src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/crypto/JniReachOnlyLiquidLegionsV2EncryptionTest.kt#L33)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

I think the practive we've been adopting is to only check the error type (ie RunTime) and not the message content. fyi @SanjayVas
</blockquote></details>

I asked @renjiezh about this and other similar tests. The reason is to verify that the exception originated from the JNI and checking the content helps.
___
*[`src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/crypto/JniReachOnlyLiquidLegionsV2EncryptionTest.kt` line 41 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1155#-NbyX3BC4d_AaTdc2Y94:-Nbzd_Lj9Qe4J_M4Doic:bwygxsx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/93e40d5b7ddb4d1e70fcc098c37d0a762941a206/src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/crypto/JniReachOnlyLiquidLegionsV2EncryptionTest.kt#L41)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Noted.


<!-- Sent from Reviewable.io -->

2023-08-17 00:47 UTC, merged