EDP simulator supports ACDP composition
world-federation-of-advertisers/cross-media-measurement pull request #1170
Opened 2023-08-15 17:47 UTC by iverson52000

Update EDP simulator to support ACDP composition. Currently keep using the old DP_ADVANCED composition with MPC Geometric(Laplace) noise and direct Laplace noise for backward compatibility. Once MPC DP noise is switched to Discrete Gaussian noise in Kingdom, and direct DP noise is switched to Gaussian in EDP simulator, change compositionMechasnim to ACDP and start using ACDP composition in PBM. 

ACDP composition can only be used with MPC discrete Gaussian or direct Gaussian noise. Otherwise, the requisition will be refused. The old DP_ADVANCED PBM ledger and composition methods, old PrivacyBucketCharges BackingStore table should be deprecated/deleted after migration to ACDP is completed/stabilized.

Major changes in this PR:
* Create a new CompositionMechasnim flag(DP_ADVANCED, ACDP) in EdpSimulatorFlags
* EDP simulator supports charging privacy budget in ACDP composition
* Charge privacy budget for direct measurements
* Add EDP simulator unit tests for the new ACDP methods

Rally task link: https://rally1.rallydev.com/#/?detail=/task/704556858935&fdp=true

2023-08-15 18:15 UTC, wfa-reviewable commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1170)
<!-- Reviewable:end -->

2023-08-16 11:57 UTC, RibeiroAna reviewed
> Reviewed 4 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1170)* status: all files reviewed, 5 unresolved discussions (waiting on @iverson52000, @riemanli, @stevenwarejones, and @uakyol)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 697 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1170#-NbyBmGn9Ogb1klg8mBj:-NbyBmGn9Ogb1klg8mBk:bdlnrx5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b9af33afcac3bfecfab627ae551a58b3edf115a6/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L697)):*
> ```Kotlin
>     try {
>       when (compositionMechanism) {
>         CompositionMechanism.DP_ADVANCED ->
> ```

shouldn't we check here if the noise mechanism is LaPlace? 
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 763 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1170#-NbyC870DVCgmjDK1Q3K:-NbyC870DVCgmjDK1Q3L:b-7ropln) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b9af33afcac3bfecfab627ae551a58b3edf115a6/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L763)):*
> ```Kotlin
> 
>     try {
>       when (compositionMechanism) {
> ```

ditto


<!-- Sent from Reviewable.io -->

2023-08-16 13:25 UTC, stevenwarejones requested changes
> Reviewed 7 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1170)* status: all files reviewed, 6 unresolved discussions (waiting on @iverson52000, @riemanli, @SanjayVas, and @uakyol)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 684 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1170#-Nbuq0497kOehWs2UNxR:-NbyVGrF2JFux3LsTlyg:b-tu7f7s) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b9af33afcac3bfecfab627ae551a58b3edf115a6/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L684)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Is "MPC" the right distinction here? I would assume it's specific to the protocol (LLv2 vs. Direct).
</blockquote></details>

why would different budgets exist for different protocols even?
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorFlags.kt` line 116 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1170#-NbyWBne6KKdnnragZ3y:-NbyWBne6KKdnnragZ3z:bqmfqrd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b9af33afcac3bfecfab627ae551a58b3edf115a6/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorFlags.kt#L116)):*
> ```Kotlin
>     names = ["--composition-mechanism"],
>     description = ["Composition mechanism in Privacy Budget Manager"],
>     defaultValue = "DP_ADVANCED",
> ```

if the composition-mechanism and the direct-noise-mechanism can conflict with each other, should we even be offering it as an option? Why not just infer the direct-noise-mechanism from the composition-mechanism and get rid of direct-noise-mechanism?


<!-- Sent from Reviewable.io -->

2023-08-16 16:54 UTC, iverson52000 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1170)* status: all files reviewed, 6 unresolved discussions (waiting on @jiayu-google, @RibeiroAna, @riemanli, @SanjayVas, @stevenwarejones, and @uakyol)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 684 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1170#-Nbuq0497kOehWs2UNxR:-NbzFQCkDnizS13JQrlX:b-tiqywt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b9af33afcac3bfecfab627ae551a58b3edf115a6/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L684)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

why would different budgets exist for different protocols even?
</blockquote></details>

From what I understand, the current process of charging in ACDP for MPC is converting (epsilon, delta, contributorCount) => discrete Gaussian sigma => AcdpCharge(rho, theta). I am not sure if these conversions only apply to LLV2, or it will be the same for other MPC protocol(eg secrete sharing). @jiayu-google do you have any insights on this?
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 697 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1170#-NbyBmGn9Ogb1klg8mBj:-NbzCPhR8ketaZDsi0Ne:b-za5ip9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b9af33afcac3bfecfab627ae551a58b3edf115a6/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L697)):*
<details><summary><i>Previously, RibeiroAna (Ana Ribeiro) wrote…</i></summary><blockquote>

shouldn't we check here if the noise mechanism is LaPlace?
</blockquote></details>

Technically we could use Gaussian noise with DP_ADVANCED composition but it’s just the privacy accounting is not optimized. On the other hand, the ACDP composition is strongly based on the assumption that DP noise should be Gaussian so Laplace noise can not be used at all. And we should be completely retiring DP_ADVANCED composition in the near future.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 763 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1170#-NbyC870DVCgmjDK1Q3K:-NbzCW5eB2Ttfb-Et2uO:b-wfxxxd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b9af33afcac3bfecfab627ae551a58b3edf115a6/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L763)):*
<details><summary><i>Previously, RibeiroAna (Ana Ribeiro) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Answered above
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 827 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1170#-NbupYuo3z1Y7i84YJXl:-NbzCdpM3h9Z7Ukvazn6:b-s0s1l8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b9af33afcac3bfecfab627ae551a58b3edf115a6/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L827)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Is there a reason we charge as part of `generateSketch` as opposed to in `fulfillRequisitionForLiquidLegionsV2Measurement`? Moving it would make it more consistent with the direct fulfillment path.
</blockquote></details>

Not sure if there's any historical reason why we charge as part of `generateSketch`. It makes sense to me to charge on the top inside`fulfillRequisitionForLiquidLegionsV2Measurement` and `fulfillRequisitionForReachOnlyLiquidLegionsV2Measurement`. @uakyol feel free to let us know if you have different point of views
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorFlags.kt` line 116 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1170#-NbyWBne6KKdnnragZ3y:-NbzDU8UCDpxCCVc-4WK:bq4dpuf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b9af33afcac3bfecfab627ae551a58b3edf115a6/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorFlags.kt#L116)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

if the composition-mechanism and the direct-noise-mechanism can conflict with each other, should we even be offering it as an option? Why not just infer the direct-noise-mechanism from the composition-mechanism and get rid of direct-noise-mechanism?
</blockquote></details>

Good point. I was just talking to @riemanli and @SanjayVas  yesterday about this and yes, we will be getting rid of direct-noise-mechanism flag and create supported preferred directNoiseMechanism lists based on the compositionMechanism. Those changes will be part of Rieman's PR https://github.com/world-federation-of-advertisers/cross-media-measurement/pull/1154


<!-- Sent from Reviewable.io -->

2023-08-16 16:56 UTC, riemanli reviewed
> Reviewed 6 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1170)* status: all files reviewed, 6 unresolved discussions (waiting on @iverson52000, @jiayu-google, @RibeiroAna, @SanjayVas, @stevenwarejones, and @uakyol)



<!-- Sent from Reviewable.io -->

2023-08-16 17:32 UTC, iverson52000 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1170)* status: 6 of 8 files reviewed, 6 unresolved discussions (waiting on @jiayu-google, @RibeiroAna, @SanjayVas, @stevenwarejones, and @uakyol)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyQuery.kt` line 76 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1170#-Nbuoc0fBZWPT9Do5aOy:-NbzOVKQ5gL9-uMKnCVB:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b9af33afcac3bfecfab627ae551a58b3edf115a6/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyQuery.kt#L76)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Move these comments to the appropriate enum values.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 827 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1170#-NbupYuo3z1Y7i84YJXl:-NbzOZ0t8DOEn2Kp8N9L:bb6un1j) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b9af33afcac3bfecfab627ae551a58b3edf115a6/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L827)):*
<details><summary><i>Previously, iverson52000 (Albert Hsu) wrote…</i></summary><blockquote>

Not sure if there's any historical reason why we charge as part of `generateSketch`. It makes sense to me to charge on the top inside`fulfillRequisitionForLiquidLegionsV2Measurement` and `fulfillRequisitionForReachOnlyLiquidLegionsV2Measurement`. @uakyol feel free to let us know if you have different point of views
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-08-16 21:18 UTC, iverson52000 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1170)* status: 6 of 12 files reviewed, 6 unresolved discussions (waiting on @RibeiroAna, @SanjayVas, @stevenwarejones, and @uakyol)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 684 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1170#-Nbuq0497kOehWs2UNxR:-Nc-C2zx3UswE-iI3EXu:b-a8bbl7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b9af33afcac3bfecfab627ae551a58b3edf115a6/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L684)):*
<details><summary><i>Previously, jiayu-google wrote…</i></summary><blockquote>

To Albert's question, secret sharing will not change this conversion process. Secret sharing will only change the function form (say, the formula to calculat sigma from epsilon, delta, contributorCount).
</blockquote></details>

So privacy charge under different protocols can be different, but the main difference will happen inside `AcdpParamsConverter.kt` when converting (epsilon, delta, contributorCount) to discrete Gaussian sigma. I have updated the function names in `AcdpParamsConverter.kt` to reflect that. 

For now, I suggest just distinguish `chargeMpcPrivacyBudget` and `chargeDirectPrivacyBudget` in EdpSimulator and see how to charge budget differently when we have new protocols. For example, we could pass `protocol` into `chargeMpcPrivacyBudget` and call different `getAcdpCharge` functions from `AcdpParamsConverter.kt` based on the `protocol`.


<!-- Sent from Reviewable.io -->

2023-08-16 21:23 UTC, SanjayVas requested changes
> Reviewed 2 of 2 files at r2, 2 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1170)* status: 10 of 12 files reviewed, 6 unresolved discussions (waiting on @iverson52000, @RibeiroAna, @stevenwarejones, and @uakyol)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyQuery.kt` line 73 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1170#-Nc-ARcy0VP0EbLCozFV:-Nc-ARcy0VP0EbLCozFW:byk470y) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4c72795efa9f8f491f639529e9a739a12dfa0db9/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyQuery.kt#L73)):*
Use KDoc syntax here, following the [style guide](https://developer.android.com/kotlin/style-guide#documentation).

In particular from the Summary Fragment section:
> This is a fragment–a noun phrase or verb phrase, not a complete sentence. It does not begin with "``A `Foo` is a...``"
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 684 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1170#-Nbuq0497kOehWs2UNxR:-Nc-B4Xe0SebXJpx4djm:b47ot5r) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b9af33afcac3bfecfab627ae551a58b3edf115a6/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L684)):*
<details><summary><i>Previously, iverson52000 (Albert Hsu) wrote…</i></summary><blockquote>

So privacy charge under different protocols can be different, but the main difference will happen inside `AcdpParamsConverter.kt` when converting (epsilon, delta, contributorCount) to discrete Gaussian sigma. I have updated the function names in `AcdpParamsConverter.kt` to reflect that. 

For now, I suggest just distinguish `chargeMpcPrivacyBudget` and `chargeDirectPrivacyBudget` in EdpSimulator and see how to charge budget differently when we have new protocols. For example, we could pass `protocol` into `chargeMpcPrivacyBudget` and call different `getAcdpCharge` functions from `AcdpParamsConverter.kt` based on the `protocol`.
</blockquote></details>

To clarify my concern, it's that we're using MPC vs. non-MPC in places where that's not the salient distinction. The EDP learns the protocol. Each protocol has its own behavior. The fact that all protocols other than `Direct` currently perform an MPC can be considered coincidental, unless that is indeed the salient distinction for PBM.

Unblocking this for now.


<!-- Sent from Reviewable.io -->

2023-08-17 11:50 UTC, RibeiroAna approved these changes
> Reviewed 3 of 8 files at r1, 2 of 2 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1170)* status: all files reviewed, 5 unresolved discussions (waiting on @iverson52000 and @uakyol)



<!-- Sent from Reviewable.io -->

2023-08-17 16:19 UTC, riemanli approved these changes
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1170)* status: all files reviewed, 5 unresolved discussions (waiting on @iverson52000 and @uakyol)



<!-- Sent from Reviewable.io -->

2023-08-17 18:18 UTC, iverson52000 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1170)* status: 8 of 12 files reviewed, 5 unresolved discussions (waiting on @RibeiroAna, @riemanli, @SanjayVas, @stevenwarejones, and @uakyol)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyQuery.kt` line 73 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1170#-Nc-ARcy0VP0EbLCozFV:-Nc3hahM5QHa4gIa1dMa:bwppva0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4c72795efa9f8f491f639529e9a739a12dfa0db9/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyQuery.kt#L73)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Use KDoc syntax here, following the [style guide](https://developer.android.com/kotlin/style-guide#documentation).

In particular from the Summary Fragment section:
> This is a fragment–a noun phrase or verb phrase, not a complete sentence. It does not begin with "``A `Foo` is a...``"
</blockquote></details>

Done. Thanks for the reminder.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 684 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1170#-Nbuq0497kOehWs2UNxR:-Nc3hwSM-Nx797hjHmN_:bdfovd8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b9af33afcac3bfecfab627ae551a58b3edf115a6/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L684)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

To clarify my concern, it's that we're using MPC vs. non-MPC in places where that's not the salient distinction. The EDP learns the protocol. Each protocol has its own behavior. The fact that all protocols other than `Direct` currently perform an MPC can be considered coincidental, unless that is indeed the salient distinction for PBM.

Unblocking this for now.
</blockquote></details>

Given another thought on this, I think it makes more sense to specify the protocol in the name of PBM related functions to be consistent with other EDP simulator methods. Updated the names `chargeLiquidLegionsV2PrivacyBudget` in EdpSimulator.kt and `getLiquidLegionsV2AcdpQuery` in PrivacyQueryMapper.kt


<!-- Sent from Reviewable.io -->

2023-08-17 22:20 UTC, SanjayVas approved these changes
> Reviewed 1 of 4 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1170)* status: all files reviewed, 4 unresolved discussions (waiting on @RibeiroAna, @stevenwarejones, and @uakyol)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyQuery.kt` line 73 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1170#-Nc-ARcy0VP0EbLCozFV:-Nc4_4ar3XIETKGeRFRr:b8ff60e) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4c72795efa9f8f491f639529e9a739a12dfa0db9/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyQuery.kt#L73)):*
<details><summary><i>Previously, iverson52000 (Albert Hsu) wrote…</i></summary><blockquote>

Done. Thanks for the reminder.
</blockquote></details>

nit: These are still using regular comment syntax (`//`) instead of KDoc syntax (`/** */`)


<!-- Sent from Reviewable.io -->

2023-08-18 16:29 UTC, stevenwarejones approved these changes
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1170)* status: all files reviewed, 4 unresolved discussions (waiting on @RibeiroAna and @uakyol)



<!-- Sent from Reviewable.io -->

2023-08-18 16:35 UTC, uakyol approved these changes
> Reviewed 6 of 8 files at r1, 2 of 4 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1170)* status: all files reviewed, 4 unresolved discussions (waiting on @RibeiroAna and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 827 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1170#-NbupYuo3z1Y7i84YJXl:-Nc8V0ir9D6DeC8jPgAt:bb7k0qh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b9af33afcac3bfecfab627ae551a58b3edf115a6/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L827)):*
<details><summary><i>Previously, iverson52000 (Albert Hsu) wrote…</i></summary><blockquote>

Done
</blockquote></details>

lgtm


<!-- Sent from Reviewable.io -->

2023-08-18 16:43 UTC, iverson52000 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1170)* status: 11 of 12 files reviewed, 4 unresolved discussions (waiting on @RibeiroAna, @SanjayVas, @stevenwarejones, and @uakyol)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyQuery.kt` line 73 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1170#-Nc-ARcy0VP0EbLCozFV:-Nc8WDeN3terH16Dig9N:bb6un1j) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4c72795efa9f8f491f639529e9a739a12dfa0db9/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyQuery.kt#L73)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: These are still using regular comment syntax (`//`) instead of KDoc syntax (`/** */`)
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-08-18 19:40 UTC, iverson52000 reviewed
> Dismissed @stevenwarejones from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1170)* status: 11 of 12 files reviewed, 3 unresolved discussions (waiting on @RibeiroAna, @riemanli, @SanjayVas, @stevenwarejones, and @uakyol)



<!-- Sent from Reviewable.io -->

2023-08-18 19:40 UTC, iverson52000 reviewed
> Reviewed 5 of 8 files at r1, 2 of 4 files at r3, 1 of 4 files at r4, 1 of 1 files at r5, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1170)* status: all files reviewed, 3 unresolved discussions (waiting on @RibeiroAna and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2023-08-18 19:41 UTC, iverson52000 reviewed
> Dismissed @RibeiroAna and @stevenwarejones from 2 discussions.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1170)* status: all files reviewed, 2 unresolved discussions (waiting on @RibeiroAna and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2023-08-18 19:41 UTC, iverson52000 reviewed
> Dismissed @RibeiroAna and @stevenwarejones from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1170)* status: all files reviewed, 2 unresolved discussions (waiting on @RibeiroAna)



<!-- Sent from Reviewable.io -->

2023-08-18 19:42 UTC, merged