Store measurement computation details in reporting for error bars
world-federation-of-advertisers/cross-media-measurement pull request #1184
Opened 2023-08-22 22:49 UTC by riemanli

2023-08-22 22:49 UTC, riemanli commented
Current dependencies on/for this PR:
* main
  * **PR #1154** <a href="https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/1154" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.svg" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #1100** <a href="https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/1100" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.svg" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #1107** <a href="https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/1107" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.svg" alt="Graphite" width="10px" height="10px"/></a> 
        * **PR #1184** <a href="https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/1184" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.svg" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/1184?utm_source=stack-comment).

2023-08-22 22:49 UTC, wfa-reviewable commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1184)
<!-- Reviewable:end -->

2023-09-12 15:42 UTC, tristanvuong2021 approved these changes
> Reviewed 5 of 22 files at r1, 17 of 17 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1184)* status: all files reviewed, 1 unresolved discussion (waiting on @riemanli)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 858 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1184#-Ne8zOIGAgupgpGELYZ2:-Ne8zOIGAgupgpGELYZ3:beyyc3x) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7398ca8319da2ee5f03bad112b8a437cf496778e/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L858)):*
> ```Kotlin
>           }
> 
>       val decryptMeasurementResults =
> ```

nit: val decryptedMeasurementResults


<!-- Sent from Reviewable.io -->

2023-09-12 18:45 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1184)* status: 21 of 22 files reviewed, 1 unresolved discussion (waiting on @Marco-Premier, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 858 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1184#-Ne8zOIGAgupgpGELYZ2:-Ne9hYbh86hjG-Wrwl2b:bfhz2u7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7398ca8319da2ee5f03bad112b8a437cf496778e/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L858)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

nit: val decryptedMeasurementResults
</blockquote></details>

Thanks for catching it. Done.


<!-- Sent from Reviewable.io -->

2023-09-12 20:36 UTC, stevenwarejones requested changes
> Reviewed 1 of 17 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1184)* status: 21 of 22 files reviewed, 5 unresolved discussions (waiting on @Marco-Premier, @riemanli, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 890 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1184#-NeA5Yop8gsXslryRc9q:-NeA5Yop8gsXslryRc9r:b-j4qg4w) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fe942223a298cc79c28d20ce18d72788657ebcdf/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L890)):*
> ```Kotlin
>                    *   methodology.
>                    */
>                   Measurement.Result.Reach.MethodologyCase.METHODOLOGY_NOT_SET,
> ```

i don't think this should default to deterministic. it just shouldn't compute error bars if not present
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 927 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1184#-NeA5gmo8pcPh5tEUbY9:-NeA5gmo8pcPh5tEUbYA:b-7ropln) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fe942223a298cc79c28d20ce18d72788657ebcdf/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L927)):*
> ```Kotlin
>                    *   methodology.
>                    */
>                   Measurement.Result.Frequency.MethodologyCase.METHODOLOGY_NOT_SET,
> ```

ditto
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 964 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1184#-NeA5nQ-2iMuRst_lDfD:-NeA5nQ-2iMuRst_lDfE:b-7ropln) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fe942223a298cc79c28d20ce18d72788657ebcdf/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L964)):*
> ```Kotlin
>                    *   methodology.
>                    */
>                   Measurement.Result.Impression.MethodologyCase.METHODOLOGY_NOT_SET,
> ```

ditto
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 985 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1184#-NeA5oA18POQI3sBSQP0:-NeA5oA18POQI3sBSQP1:b-7ropln) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fe942223a298cc79c28d20ce18d72788657ebcdf/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L985)):*
> ```Kotlin
>                    *   methodology.
>                    */
>                   Measurement.Result.WatchDuration.MethodologyCase.METHODOLOGY_NOT_SET,
> ```

ditto
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ProtoConversions.kt` line 662 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1184#-NeA60OI6NWqNpjRH3VK:-NeA60OI6NWqNpjRH3VL:bwd9m1y) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fe942223a298cc79c28d20ce18d72788657ebcdf/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ProtoConversions.kt#L662)):*
> ```Kotlin
>     ProtocolConfig.NoiseMechanism.DISCRETE_GAUSSIAN -> NoiseMechanism.DISCRETE_GAUSSIAN
>     /** TODO(@riemanli): once EDPs incorporate the new API, raise an error for unspecified. */
>     ProtocolConfig.NoiseMechanism.NOISE_MECHANISM_UNSPECIFIED,
> ```

we should have an internal unspecified as well that this maps to


<!-- Sent from Reviewable.io -->

2023-09-12 21:14 UTC, SanjayVas reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1184)* status: 21 of 22 files reviewed, 5 unresolved discussions (waiting on @Marco-Premier, @riemanli, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 890 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1184#-NeA5Yop8gsXslryRc9q:-NeAD66A6_BYzuj0JjZs:b-i0kwvl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fe942223a298cc79c28d20ce18d72788657ebcdf/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L890)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

i don't think this should default to deterministic. it just shouldn't compute error bars if not present
</blockquote></details>

So the point of the API change was to:

1. Make what EDPs should already be doing explicit, i.e. what methodology and noise mechanism every EDP was already assumed to be using.
   * This is why the API change documented what values are assumed if each field is unset.
2. Allow EDPs to choose between different methodologies and noise mechanisms going forward.

Whether the EDP was actually following the assumptions is irrelevant. You'll get the same inaccuracy in variance if the EDP simply states they are using one methodology when they are in fact using another.


<!-- Sent from Reviewable.io -->

2023-09-14 15:51 UTC, stevenwarejones requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1184)* status: 21 of 22 files reviewed, 5 unresolved discussions (waiting on @Marco-Premier, @riemanli, @SanjayVas, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 890 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1184#-NeA5Yop8gsXslryRc9q:-NeJNk464_MKs6gqOpPa:b-7inl1n) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fe942223a298cc79c28d20ce18d72788657ebcdf/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L890)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

So the point of the API change was to:

1. Make what EDPs should already be doing explicit, i.e. what methodology and noise mechanism every EDP was already assumed to be using.
   * This is why the API change documented what values are assumed if each field is unset.
2. Allow EDPs to choose between different methodologies and noise mechanisms going forward.

Whether the EDP was actually following the assumptions is irrelevant. You'll get the same inaccuracy in variance if the EDP simply states they are using one methodology when they are in fact using another.
</blockquote></details>

i'm saying we should not be setting the `deterministicCountDistinct` field in this case


<!-- Sent from Reviewable.io -->

2023-09-14 16:39 UTC, tristanvuong2021 approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1184)* status: all files reviewed, 5 unresolved discussions (waiting on @Marco-Premier, @riemanli, and @SanjayVas)



<!-- Sent from Reviewable.io -->

2023-09-14 23:55 UTC, SanjayVas reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1184)* status: all files reviewed, 5 unresolved discussions (waiting on @Marco-Premier, @riemanli, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 890 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1184#-NeA5Yop8gsXslryRc9q:-NeL4CoB8oyXGBdLa1o_:bxqp76r) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fe942223a298cc79c28d20ce18d72788657ebcdf/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L890)):*
> i'm saying we should not be setting the `deterministicCountDistinct` field in this case

Documentation for the [`methodology` field in `Measurement.Result.Impression`](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/39034b41b30ed85cabf8afe6388bfb956f07af25/src/main/proto/wfa/measurement/api/v2alpha/measurement.proto#L200):

>    // The computation methodology done by data provider.
      //
      // Currently, only direct measurement would populate it. Before all EDPs
      // incorporate the new API, if no methodology is set for the impression
      // result, it is assumed that DeterministicCount is used.

Meaning we've explicitly stated that if the methodology is unspecified it is assumed to be `DeterministicCount`. This, being the only valid methodology, is what all EDPs should have already been doing. It can only possibly be another methodology once we add more values to that oneof.

There is intentionally no way to capture that the EDP used an invalid methodology. We just assume they've been doing it correctly with the understanding that the result (and the corresponding variance) would be inaccurate in that case.


<!-- Sent from Reviewable.io -->

2023-09-18 18:29 UTC, stevenwarejones requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1184)* status: all files reviewed, 5 unresolved discussions (waiting on @Marco-Premier and @riemanli)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 890 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1184#-NeA5Yop8gsXslryRc9q:-NedYXbxCEHJqLFzfTVo:b-xrp26u) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fe942223a298cc79c28d20ce18d72788657ebcdf/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L890)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> i'm saying we should not be setting the `deterministicCountDistinct` field in this case

Documentation for the [`methodology` field in `Measurement.Result.Impression`](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/39034b41b30ed85cabf8afe6388bfb956f07af25/src/main/proto/wfa/measurement/api/v2alpha/measurement.proto#L200):

>    // The computation methodology done by data provider.
      //
      // Currently, only direct measurement would populate it. Before all EDPs
      // incorporate the new API, if no methodology is set for the impression
      // result, it is assumed that DeterministicCount is used.

Meaning we've explicitly stated that if the methodology is unspecified it is assumed to be `DeterministicCount`. This, being the only valid methodology, is what all EDPs should have already been doing. It can only possibly be another methodology once we add more values to that oneof.

There is intentionally no way to capture that the EDP used an invalid methodology. We just assume they've been doing it correctly with the understanding that the result (and the corresponding variance) would be inaccurate in that case.
</blockquote></details>

as discussed, lets map to a custom methodology 


<!-- Sent from Reviewable.io -->

2023-09-18 20:57 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1184)* status: all files reviewed, 5 unresolved discussions (waiting on @kungfucraig, @Marco-Premier, and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ProtoConversions.kt` line 662 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1184#-NeA60OI6NWqNpjRH3VK:-Nee1_b650TUJdJb1RzN:b-cvouec) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fe942223a298cc79c28d20ce18d72788657ebcdf/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ProtoConversions.kt#L662)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

we should have an internal unspecified as well that this maps to
</blockquote></details>

This is similar to the issue we had for methodology fields. The [document in the current API](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/main/src/main/proto/wfa/measurement/api/v2alpha/measurement.proto#L133-L137) states that if unspecified the noise mechanism is `CONTINUOUS_LAPLACE` by default.

If we don't want this, we can remove that document and let the downstream services decide what to do when the mechanism is unspecified. For reporting server, the conversion method here will map unspecified to unspecified, but later the caller will use `CONTINUOUS_LAPLACE` when unspecified is detected.

Wdyt?

CC @kungfucraig @SanjayVas


<!-- Sent from Reviewable.io -->

2023-09-18 21:11 UTC, kungfucraig reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1184)* status: all files reviewed, 5 unresolved discussions (waiting on @Marco-Premier, @riemanli, and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ProtoConversions.kt` line 662 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1184#-NeA60OI6NWqNpjRH3VK:-Nee6oVDEfURemCMpXmr:b-nsmwn5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fe942223a298cc79c28d20ce18d72788657ebcdf/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ProtoConversions.kt#L662)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

This is similar to the issue we had for methodology fields. The [document in the current API](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/main/src/main/proto/wfa/measurement/api/v2alpha/measurement.proto#L133-L137) states that if unspecified the noise mechanism is `CONTINUOUS_LAPLACE` by default.

If we don't want this, we can remove that document and let the downstream services decide what to do when the mechanism is unspecified. For reporting server, the conversion method here will map unspecified to unspecified, but later the caller will use `CONTINUOUS_LAPLACE` when unspecified is detected.

Wdyt?

CC @kungfucraig @SanjayVas
</blockquote></details>

If we pursue the NaN default for the methodologies, then mapping this to UNSPECIFIED would definitely make sense. Basically we're saying, if you don't set this we don't know what you did, and we won't use it for anything (e.g. we will not compute a variance for you). 

Practically speaking, from the point of view of the Measurement Result we'd expect either both or neither of the methodology and nose mechanism to be set.

Anyway, once all EDPs are using this and methodology both then we'll make them both required.


<!-- Sent from Reviewable.io -->

2023-09-18 21:59 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1184)* status: 18 of 22 files reviewed, 5 unresolved discussions (waiting on @Marco-Premier, @SanjayVas, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 890 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1184#-NeA5Yop8gsXslryRc9q:-NeeGI-h9wd9eAmpcKbN:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fe942223a298cc79c28d20ce18d72788657ebcdf/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L890)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

as discussed, lets map to a custom methodology
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 927 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1184#-NeA5gmo8pcPh5tEUbY9:-NeeGK6M701sm12JCpG8:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fe942223a298cc79c28d20ce18d72788657ebcdf/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L927)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 964 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1184#-NeA5nQ-2iMuRst_lDfD:-NeeGKfm1fBABS9cKT9P:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fe942223a298cc79c28d20ce18d72788657ebcdf/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L964)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 985 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1184#-NeA5oA18POQI3sBSQP0:-NeeGLBA6ZsbMIUtji6q:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fe942223a298cc79c28d20ce18d72788657ebcdf/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L985)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ProtoConversions.kt` line 662 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1184#-NeA60OI6NWqNpjRH3VK:-NeeEZd7CuPcUMltTzWW:bakqfz4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fe942223a298cc79c28d20ce18d72788657ebcdf/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ProtoConversions.kt#L662)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

If we pursue the NaN default for the methodologies, then mapping this to UNSPECIFIED would definitely make sense. Basically we're saying, if you don't set this we don't know what you did, and we won't use it for anything (e.g. we will not compute a variance for you). 

Practically speaking, from the point of view of the Measurement Result we'd expect either both or neither of the methodology and nose mechanism to be set.

Anyway, once all EDPs are using this and methodology both then we'll make them both required.
</blockquote></details>

Got it. I will skip the variance calculation if either the noise mechanism or the methodology is unspecified.

Fixed the conversion mapping.


<!-- Sent from Reviewable.io -->

2023-09-20 12:52 UTC, stevenwarejones approved these changes
> Reviewed 3 of 22 files at r1, 1 of 17 files at r2, 3 of 4 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1184)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Marco-Premier and @SanjayVas)



<!-- Sent from Reviewable.io -->

2023-09-20 16:10 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1184)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Marco-Premier and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 890 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1184#-NeA5Yop8gsXslryRc9q:-NekhNyX4P3Em0hrFpFB:b-3vv0pf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fe942223a298cc79c28d20ce18d72788657ebcdf/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L890)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

After another round of discussion, we decided to keep unspecified and won't do variance calculation for it.


<!-- Sent from Reviewable.io -->

2023-09-20 20:18 UTC, kungfucraig reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1184)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Marco-Premier and @SanjayVas)



<!-- Sent from Reviewable.io -->

2023-09-21 13:36 UTC, stevenwarejones approved these changes
> Reviewed 2 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1184)* status: 21 of 22 files reviewed, all discussions resolved (waiting on @Marco-Premier, @SanjayVas, and @tristanvuong2021)



<!-- Sent from Reviewable.io -->

2023-09-21 19:31 UTC, SanjayVas requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1184)* status: 21 of 22 files reviewed, 1 unresolved discussion (waiting on @Marco-Premier, @riemanli, and @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/internal/reporting/v2/measurement.proto` line 99 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1184#-NetD6ra4h3ayD4dunO_:-NetD6ra4h3ayD4dunOa:bfmw50o) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5af075ee7b2f523f2faeed647db5856da0c4ca97/src/main/proto/wfa/measurement/internal/reporting/v2/measurement.proto#L99)):*
> ```proto
>     // Computation configs of the `Measurement` derived from the CMMS public
>     // API.
>     repeated ComputationConfig computation_configs = 3;
> ```

I thought the plan was to avoid having to effectively duplicate the protocol config and methodology info here by just computing whatever we needed when we get each Measurement result. Is that not feasible?


<!-- Sent from Reviewable.io -->

2023-09-21 21:20 UTC, kungfucraig reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1184)* status: 21 of 22 files reviewed, 1 unresolved discussion (waiting on @Marco-Premier, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/internal/reporting/v2/measurement.proto` line 99 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1184#-NetD6ra4h3ayD4dunO_:-NetbHNkBpSg4xgn0FEH:bgcmfq5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5af075ee7b2f523f2faeed647db5856da0c4ca97/src/main/proto/wfa/measurement/internal/reporting/v2/measurement.proto#L99)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

That is a great question. We did discuss that before. However, I rethought about it and have the following reason to store the info:

Theoretically, what you mentioned is feasible for variance calculation. We can compute and save measurement variances when the measurements are succeeded, and later we use the measurement variances to compute metric variances. However, this approach is under some assumptions:
1. `VidSamplingInterval` of every `Measurement` under the same `Metric` is always the same. For example, we can't allow random start of  `VidSamplingInterval` for measurement specs.
2. Decay rate and sketch size specified in `MetricSpec` and so in `MeasurementSpec` are always honored. EDPs can't use values other than what specified in the spec. 
3. Metric variance calculations won't need any additional information other than measurement variances and the parameters mentioned in (1) and (2).

For (1), I remember we mentioned we might want to do it for better privacy budget consumptions. For (2), @stevenwarejones, @kungfucraig and I have discussed this before in this [thread](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/pull/163#pullrequestreview-1594657860) about the possibility that EDPs won't follow the values in spec.

With those consideration, I decided to store computation configs which leaves us a way if any assumption changes.

In worst case if we really don't need it, remove this line in `details` is simple as there is no DB schema change.
</blockquote></details>

Why not take the other approach, which would be, if we end up needing this add it when we do? You know, YAGNI, and all of that... :)


<!-- Sent from Reviewable.io -->

2023-09-21 21:39 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1184)* status: 21 of 22 files reviewed, 1 unresolved discussion (waiting on @Marco-Premier, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/internal/reporting/v2/measurement.proto` line 99 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1184#-NetD6ra4h3ayD4dunO_:-NetdFw172OpnEPn8R4L:b-l82i1k) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5af075ee7b2f523f2faeed647db5856da0c4ca97/src/main/proto/wfa/measurement/internal/reporting/v2/measurement.proto#L99)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Why not take the other approach, which would be, if we end up needing this add it when we do? You know, YAGNI, and all of that... :)
</blockquote></details>

I'm sorry. After inspecting the formulas again, I also found that I really need to know what methodology is used, so I do need to store the methodology info at least.

In this case, do we still want to compute measurement variances upfront? The difference now is storing noise mechanism and parameters of methodologies or not, which I think is pretty minor.


<!-- Sent from Reviewable.io -->

2023-09-21 22:17 UTC, kungfucraig reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1184)* status: 21 of 22 files reviewed, 1 unresolved discussion (waiting on @Marco-Premier, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/internal/reporting/v2/measurement.proto` line 99 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1184#-NetD6ra4h3ayD4dunO_:-NetoFxv95cqzFBPejU_:b-vl55d2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5af075ee7b2f523f2faeed647db5856da0c4ca97/src/main/proto/wfa/measurement/internal/reporting/v2/measurement.proto#L99)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

I'm sorry. After inspecting the formulas again, I also found that I really need to know what methodology is used, so I do need to store the methodology info at least.

In this case, do we still want to compute measurement variances upfront? The difference now is storing noise mechanism and parameters of methodologies or not, which I think is pretty minor.
</blockquote></details>

Yeah it's minor. I don't feel strongly about this. If you want to keep it, that's fine.


<!-- Sent from Reviewable.io -->

2023-09-21 22:30 UTC, SanjayVas reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1184)* status: 21 of 22 files reviewed, 1 unresolved discussion (waiting on @Marco-Premier, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/internal/reporting/v2/measurement.proto` line 99 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1184#-NetD6ra4h3ayD4dunO_:-NetqF8x70u6nVWXurPY:b3koakx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5af075ee7b2f523f2faeed647db5856da0c4ca97/src/main/proto/wfa/measurement/internal/reporting/v2/measurement.proto#L99)):*
> the possibility that EDPs won't follow the values in spec.

If we want to allow this then we'd need to make API change (even if it's just documentation). As currently written, EDPs **must** conform to the spec.

> After inspecting the formulas again, I also found that I really need to know what methodology is used, so I do need to store the methodology info at least.

Still confused by this. Why would we need to store it if we compute it as soon as we get the Measurement result? We should have the entire CMMS Measurement at that point.

That all said, I don't have a strong opinion on storing this if there are other benefits. I was just figuring we could avoid having to duplicate information that's already on the CMMS Measurement resource.


<!-- Sent from Reviewable.io -->

2023-09-21 23:03 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1184)* status: 21 of 22 files reviewed, 1 unresolved discussion (waiting on @Marco-Premier, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/internal/reporting/v2/measurement.proto` line 99 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1184#-NetD6ra4h3ayD4dunO_:-Netx2q2ExO45KLqy2F2:b-ypgk5h) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5af075ee7b2f523f2faeed647db5856da0c4ca97/src/main/proto/wfa/measurement/internal/reporting/v2/measurement.proto#L99)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> the possibility that EDPs won't follow the values in spec.

If we want to allow this then we'd need to make API change (even if it's just documentation). As currently written, EDPs **must** conform to the spec.

> After inspecting the formulas again, I also found that I really need to know what methodology is used, so I do need to store the methodology info at least.

Still confused by this. Why would we need to store it if we compute it as soon as we get the Measurement result? We should have the entire CMMS Measurement at that point.

That all said, I don't have a strong opinion on storing this if there are other benefits. I was just figuring we could avoid having to duplicate information that's already on the CMMS Measurement resource.
</blockquote></details>

Thanks Sanjay for the feedback and digging into this.

One of the steps to compute metric variances is computing the covariance of every two measurements. As we can see in [the functions of covariances](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/main/kotlin/org/wfanet/measurement/measurementconsumer/stats/Covariances.kt), depending on the methodologies of the two measurements, we need to use different functions. Of course we can call `getMeasurement`s again later when computing metric variances to get the info from CMMS, but I think saving this to avoid rpcs would be more beneficial.


<!-- Sent from Reviewable.io -->

2023-09-21 23:41 UTC, SanjayVas requested changes
> Reviewed 1 of 22 files at r1, 1 of 17 files at r2, 1 of 4 files at r4, 1 of 3 files at r6.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1184)* status: 21 of 22 files reviewed, 3 unresolved discussions (waiting on @Marco-Premier, @riemanli, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 859 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1184#-Neu4vc4EIGSHRpRBDQ6:-Neu4vc4EIGSHRpRBDQ7:blpvf2g) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5af075ee7b2f523f2faeed647db5856da0c4ca97/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L859)):*
> ```Kotlin
>           }
> 
>       val decryptedMeasurementResults =
> ```

nit: explicit types where not obvious
___
*[`src/main/proto/wfa/measurement/internal/reporting/v2/measurement.proto` line 99 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1184#-NetD6ra4h3ayD4dunO_:-Neu4d8c0K9I_7-X8336:b-3r22r2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5af075ee7b2f523f2faeed647db5856da0c4ca97/src/main/proto/wfa/measurement/internal/reporting/v2/measurement.proto#L99)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Thanks Sanjay for the feedback and digging into this.

One of the steps to compute metric variances is computing the covariance of every two measurements. As we can see in [the functions of covariances](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/main/kotlin/org/wfanet/measurement/measurementconsumer/stats/Covariances.kt), depending on the methodologies of the two measurements, we need to use different functions. Of course we can call `getMeasurement`s again later when computing metric variances to get the info from CMMS, but I think saving this to avoid rpcs would be more beneficial.
</blockquote></details>

Sounds like this qualifies under "if there are other benefits" then :)
___
*[`src/main/proto/wfa/measurement/internal/reporting/v2/measurement.proto` line 99 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1184#-Neu5s6OAEaI5rW1Mxml:-Neu5s6OAEaI5rW1Mxmm:b6pqrzf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5af075ee7b2f523f2faeed647db5856da0c4ca97/src/main/proto/wfa/measurement/internal/reporting/v2/measurement.proto#L99)):*
> ```proto
>     // Computation configs of the `Measurement` derived from the CMMS public
>     // API.
>     repeated ComputationConfig computation_configs = 3;
> ```

Why is this repeated? Is this to handle the case where we're combining multiple Direct results, e.g. for impressions? If so, how do we know which config each result is mapped to? Should we maybe avoid combining the results in this internal message so that we can put the config alongside the result?
___
*[`src/main/proto/wfa/measurement/internal/reporting/v2/measurement.proto` line 104 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1184#-Neu5fy766VY7dpXWqWj:-Neu5fy766VY7dpXWqWk:bf61x74) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5af075ee7b2f523f2faeed647db5856da0c4ca97/src/main/proto/wfa/measurement/internal/reporting/v2/measurement.proto#L104)):*
> ```proto
> }
> 
> // The mechanism used to generate noise in computations.
> ```

nit: mind pulling these out into a separate file or two?


<!-- Sent from Reviewable.io -->

2023-09-25 18:17 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1184)* status: 14 of 23 files reviewed, 1 unresolved discussion (waiting on @Marco-Premier, @SanjayVas, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 859 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1184#-Neu4vc4EIGSHRpRBDQ6:-NeuA7pfAYgo62ITNjvz:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5af075ee7b2f523f2faeed647db5856da0c4ca97/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L859)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: explicit types where not obvious
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/internal/reporting/v2/measurement.proto` line 99 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1184#-Neu5s6OAEaI5rW1Mxml:-NeuISW49mdFLLcVfVkG:b-39jw80) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5af075ee7b2f523f2faeed647db5856da0c4ca97/src/main/proto/wfa/measurement/internal/reporting/v2/measurement.proto#L99)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Why is this repeated? Is this to handle the case where we're combining multiple Direct results, e.g. for impressions? If so, how do we know which config each result is mapped to? Should we maybe avoid combining the results in this internal message so that we can put the config alongside the result?
</blockquote></details>

Thanks for pointing it out! It's an oversight.

I fixed it as you suggested by refactoring the internal reporting measurement to store a list of `Result`s. In addition, the structure of  the internal `Result` is modified to be the same as the one in the Kingdom.
___
*[`src/main/proto/wfa/measurement/internal/reporting/v2/measurement.proto` line 104 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1184#-Neu5fy766VY7dpXWqWj:-NeuIR2sCI2PMZl-4Gy4:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5af075ee7b2f523f2faeed647db5856da0c4ca97/src/main/proto/wfa/measurement/internal/reporting/v2/measurement.proto#L104)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: mind pulling these out into a separate file or two?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-09-25 18:38 UTC, tristanvuong2021 approved these changes
> Reviewed 1 of 4 files at r4, 9 of 9 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1184)* status: all files reviewed, 2 unresolved discussions (waiting on @Marco-Premier, @riemanli, @SanjayVas, and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/internal/reporting/v2/noise_mechanism.proto` line 36 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1184#-NfCaeyx3GV-xKvtQYsC:-NfCaeyx3GV-xKvtQYsD:b-730rjm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a3cd3732732a71436d04ebf7ffd837de878995fe/src/main/proto/wfa/measurement/internal/reporting/v2/noise_mechanism.proto#L36)):*
> ```proto
>   // Continuous Gaussian.
>   CONTINUOUS_GAUSSIAN = 5;
> }
> ```

nit: new line


<!-- Sent from Reviewable.io -->

2023-09-25 19:43 UTC, kungfucraig reviewed
> Reviewed 1 of 22 files at r1, 2 of 17 files at r2, 3 of 9 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1184)* status: all files reviewed, 2 unresolved discussions (waiting on @Marco-Premier, @riemanli, @SanjayVas, and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2023-09-25 19:45 UTC, SanjayVas approved these changes
> Reviewed 12 of 17 files at r2, 9 of 9 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1184)* status: all files reviewed, 2 unresolved discussions (waiting on @Marco-Premier, @riemanli, and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/internal/reporting/v2/measurement.proto` line 128 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1184#-NfCqthe2F2P-Bid8Lxj:-NfCqthf4PcqeWCwqBpq:b-eu4gx7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a3cd3732732a71436d04ebf7ffd837de878995fe/src/main/proto/wfa/measurement/internal/reporting/v2/measurement.proto#L128)):*
> ```proto
>     //
>     // For reach and frequency, there is only one result. For impression and
>     // watch duration, the result is per data provider.
> ```

nit: this is technically dependent on the protocol rather than the measurement type. LLv2 will give a single result, whereas Direct will give one per DataProvider.



_Code quote:_
```proto
    // For reach and frequency, there is only one result. For impression and
    // watch duration, the result is per data provider.
```


<!-- Sent from Reviewable.io -->

2023-09-25 22:37 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1184)* status: 21 of 23 files reviewed, all discussions resolved (waiting on @kungfucraig, @Marco-Premier, @SanjayVas, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/internal/reporting/v2/measurement.proto` line 128 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1184#-NfCqthe2F2P-Bid8Lxj:-NfDU4kZ-rhtb8Va1D4b:b-hsmsbi) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a3cd3732732a71436d04ebf7ffd837de878995fe/src/main/proto/wfa/measurement/internal/reporting/v2/measurement.proto#L128)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: this is technically dependent on the protocol rather than the measurement type. LLv2 will give a single result, whereas Direct will give one per DataProvider.
</blockquote></details>

Done by explicitly listing the result types. 
___
*[`src/main/proto/wfa/measurement/internal/reporting/v2/noise_mechanism.proto` line 36 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1184#-NfCaeyx3GV-xKvtQYsC:-NfCdw_w2FDP-dbIdgN4:b-896fja) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a3cd3732732a71436d04ebf7ffd837de878995fe/src/main/proto/wfa/measurement/internal/reporting/v2/noise_mechanism.proto#L36)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

nit: new line
</blockquote></details>

Done!


<!-- Sent from Reviewable.io -->

2023-09-25 23:20 UTC, SanjayVas approved these changes
> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1184)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kungfucraig, @Marco-Premier, and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/internal/reporting/v2/measurement.proto` line 128 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1184#-NfCqthe2F2P-Bid8Lxj:-NfDcNI1BYVUkvx6yBlh:b-8zf5e2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a3cd3732732a71436d04ebf7ffd837de878995fe/src/main/proto/wfa/measurement/internal/reporting/v2/measurement.proto#L128)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Done by explicitly listing the result types.
</blockquote></details>

I think it's better not to mention measurement types at all and just stick to mentioning the protocols (LLv2 vs. Direct). Note that "one per DataProvider" is still true for Direct reach or R/F currently; it just happens to be that the Kingdom only uses that protocol when there's a single DataProvider.


<!-- Sent from Reviewable.io -->

2023-09-25 23:47 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1184)* status: 22 of 23 files reviewed, all discussions resolved (waiting on @kungfucraig, @Marco-Premier, @SanjayVas, and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/internal/reporting/v2/measurement.proto` line 128 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1184#-NfCqthe2F2P-Bid8Lxj:-NfDiSZX6g79N-bSWDqH:b-896fja) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a3cd3732732a71436d04ebf7ffd837de878995fe/src/main/proto/wfa/measurement/internal/reporting/v2/measurement.proto#L128)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I think it's better not to mention measurement types at all and just stick to mentioning the protocols (LLv2 vs. Direct). Note that "one per DataProvider" is still true for Direct reach or R/F currently; it just happens to be that the Kingdom only uses that protocol when there's a single DataProvider.
</blockquote></details>

Done!


<!-- Sent from Reviewable.io -->

2023-09-26 00:11 UTC, SanjayVas approved these changes
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1184)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kungfucraig, @Marco-Premier, and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2023-09-26 15:18 UTC, stevenwarejones approved these changes
> Reviewed 12 of 17 files at r2, 7 of 9 files at r7, 1 of 2 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1184)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kungfucraig and @Marco-Premier)



<!-- Sent from Reviewable.io -->

2023-09-26 16:53 UTC, merged