Create Gaussian noise and ACDP composition rollout doc
world-federation-of-advertisers/cross-media-measurement pull request #1185
Opened 2023-08-24 21:09 UTC by iverson52000

Rally task link: https://rally1.rallydev.com/#/?detail=/task/720480906829&fdp=true

2023-08-24 23:48 UTC, SanjayVas requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1185)* status: all files reviewed, 7 unresolved discussions (waiting on @iverson52000, @kungfucraig, @stevenwarejones, and @uakyol)

___
*[`docs/operations/gaussian-noise-and-acdp.md` line 3 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1185#-Ncddfow4uv-TfzrLnV0:-Ncddfow4uv-TfzrLnV1:bytl8dl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/94ded58a76002a4713bbe8303d4a7f7017ae52b1/docs/operations/gaussian-noise-and-acdp.md#L3)):*
> ```Markdown
> # Gaussian Noise and ACDP Composition in PBM
> 
> Use Gaussian Differential Privacy(DP) noise for Multi-Party Computation(MPC) and
> ```

This doc needs to more clearly split the ACDP and Gaussian noise parts, but note their interaction. The important part is that Gaussian noise is enabled as part of the Kingdom configuration, but ACDP is part of the PBM implementation within an EDP's Requisition fulfillment pipeline.
___
*[`docs/operations/gaussian-noise-and-acdp.md` line 18 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1185#-Ncdc2j62JIUlmnLznmk:-Ncdc2j70OiWAHoegMEz:b-1ipmzu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/94ded58a76002a4713bbe8303d4a7f7017ae52b1/docs/operations/gaussian-noise-and-acdp.md#L18)):*
> ```Markdown
> 1.  Change `noise_mechanism` to `DISCRETE_GAUSSIAN` in
>     [llv2_protocol_config_config.textproto](../../src/main/k8s/testing/secretfiles/llv2_protocol_config_config.textproto)
>     in Kingdom for LLV2 based MPC reach and frequency measurement
> ```

This is just linking to the example config used by our `dev` environment. You need to instead mention where this would be in their own Kingdom.



_Suggestion:_
```Markdown
1.  Change `noise_mechanism` to `DISCRETE_GAUSSIAN` in the Kingdom's `Llv2ProtocolConfigConfig`.

    In the `dev` configuration, this is read from the `llv2_protocol_config_config.textproto` file in the `certs-and-configs` Kubernetes secret.
```
___
*[`docs/operations/gaussian-noise-and-acdp.md` line 21 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1185#-NcdvrUL8kU5tPU7kjdu:-NcdvrUL8kU5tPU7kjdv:bwv4knr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/94ded58a76002a4713bbe8303d4a7f7017ae52b1/docs/operations/gaussian-noise-and-acdp.md#L21)):*
> ```Markdown
> 2.  Change `noise_mechanism` to `DISCRETE_GAUSSIAN` in
>     [ro_llv2_protocol_config_config.textproto](../../src/main/k8s/testing/secretfiles/ro_llv2_protocol_config_config.textproto)
>     in Kingdom for LLV2 based MPC reach only measurement
> ```

Don't we also need a step to ensure that CONTINUOUS_GAUSSIAN is enabled for the Direct protocol? Even if it's set in our defaults, you need to make sure that the Kingdom operator didn't change the flag to be CONTINUOUS_LAPLACE only.
___
*[`docs/operations/gaussian-noise-and-acdp.md` line 22 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1185#-NcdcdP67zPteep4Y2Sv:-NcdcdP67zPteep4Y2Sw:bhmq214) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/94ded58a76002a4713bbe8303d4a7f7017ae52b1/docs/operations/gaussian-noise-and-acdp.md#L22)):*
> ```Markdown
>     [ro_llv2_protocol_config_config.textproto](../../src/main/k8s/testing/secretfiles/ro_llv2_protocol_config_config.textproto)
>     in Kingdom for LLV2 based MPC reach only measurement
> 3.  Change `compositionMechanism` flag to `ACDP` in
> ```

This is not actually a required step for enabling this feature. It's just something you need to do in order to run correctness tests after enabling it.

More broadly, EDP simulators are not part of a regular production deployment.
___
*[`docs/operations/gaussian-noise-and-acdp.md` line 28 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1185#-NcdvIl72G0JCXSjZEXD:-NcdvIl72G0JCXSjZEXE:b90j4f1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/94ded58a76002a4713bbe8303d4a7f7017ae52b1/docs/operations/gaussian-noise-and-acdp.md#L28)):*
> ```Markdown
>     provided in
>     `src/main/kotlin/org/wfanet/measurement/eventdataprovider/noiser/GaussianNoiser.kt`
> ```

The final step here should be EDPs switching their PBMs to using ACDP, right? I assume there's no migration, meaning that this effectively resets the ledger for everyone?

Note that this means there will be a gap between when we're using Gaussian for LLv2 and when the EDP is using ACDP for PBM.
___
*[`docs/operations/gaussian-noise-and-acdp.md` line 59 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1185#-NcdeaNuB1eIwYLDFnf5:-NcdeaNuB1eIwYLDFnf6:b5jwt4e) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/94ded58a76002a4713bbe8303d4a7f7017ae52b1/docs/operations/gaussian-noise-and-acdp.md#L59)):*
> ```Markdown
> 
> For MPC Gaussian noise, the config files in the above Rollout Steps are part of
> the testing secrets and are only used by the Halo dev environment. The Kingdom
> ```

This doc should only cover the parts that the Kingdom operator and EDP integrators need to do. We control the dev environment and therefore don't need a rollout doc there. Dev rollout happens automatically on release.



_Code quote:_
```Markdown
For MPC Gaussian noise, the config files in the above Rollout Steps are part of
the testing secrets and are only used by the Halo dev environment. The Kingdom
```
___
*[`docs/operations/gaussian-noise-and-acdp.md` line 72 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1185#-Ncdw_gV-2ovy592B1Nq:-Ncdw_gV-2ovy592B1Nr:b1w2xzl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/94ded58a76002a4713bbe8303d4a7f7017ae52b1/docs/operations/gaussian-noise-and-acdp.md#L72)):*
> ```Markdown
> ## Emergency Rollback
> 
> The Gaussian DP noise and PBM ACDP composition features are designed with
> ```

Aren't the ledgers for ACDP and any existing PBM not compatible (see above comment)? If so, rolling back on the EDP side has the effect of dropping all the privacy charges.


<!-- Sent from Reviewable.io -->

2023-08-25 15:08 UTC, kungfucraig requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1185)* status: all files reviewed, 11 unresolved discussions (waiting on @iverson52000, @SanjayVas, @stevenwarejones, and @uakyol)

___
*[`docs/operations/gaussian-noise-and-acdp.md` line 0 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1185#-NchBfl65b-T4DNYb9Oq:-NchBfl65b-T4DNYb9Or:b-7dugz9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/94ded58a76002a4713bbe8303d4a7f7017ae52b1/docs/operations/gaussian-noise-and-acdp.md#L0)):*
Having some file naming convention like:

rollout-<feature>.md I think would make sense. 

Even doing something like rollout-2023-08-<feature>.md could be helpful. 

@SanjayVas WDYT?

Alternatively a subdirectory of operations called "rollout" might help separate things that are essentially one-of from things that are more on going operations tasks.
___
*[`docs/operations/gaussian-noise-and-acdp.md` line 3 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1185#-NchCPZa-Kjvb0xY1J90:-NchCPZa-Kjvb0xY1J91:b-e4xqtf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/94ded58a76002a4713bbe8303d4a7f7017ae52b1/docs/operations/gaussian-noise-and-acdp.md#L3)):*
> ```Markdown
> # Gaussian Noise and ACDP Composition in PBM
> 
> Use Gaussian Differential Privacy(DP) noise for Multi-Party Computation(MPC) and
> ```

This guide describes how to enable Gaussian Differential Privacy noise for multi-party computations (MPCs) and ... 
___
*[`docs/operations/gaussian-noise-and-acdp.md` line 13 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1185#-NchCtDP5rpedJr0ax6K:-NchCtDP5rpedJr0ax6L:b-f8ky76) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/94ded58a76002a4713bbe8303d4a7f7017ae52b1/docs/operations/gaussian-noise-and-acdp.md#L13)):*
> ```Markdown
> 
> ## Rollout Steps
> ```

You should mention that before starting the Kingdom rollout of gaussian noise that the first rollout step is to ensure that all EDP PBMs in the deployment support gaussian noise, and ideally the full ACDP implementation (or if not that they understand the impact of this).
___
*[`docs/operations/gaussian-noise-and-acdp.md` line 28 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1185#-NcdvIl72G0JCXSjZEXD:-NchD_mA7GNbITLikyAF:b8nh1w4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/94ded58a76002a4713bbe8303d4a7f7017ae52b1/docs/operations/gaussian-noise-and-acdp.md#L28)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The final step here should be EDPs switching their PBMs to using ACDP, right? I assume there's no migration, meaning that this effectively resets the ledger for everyone?

Note that this means there will be a gap between when we're using Gaussian for LLv2 and when the EDP is using ACDP for PBM.
</blockquote></details>

That's the first step. :)
___
*[`docs/operations/gaussian-noise-and-acdp.md` line 31 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1185#-NchDcLUBubdkJIx2lNi:-NchDcLUBubdkJIx2lNj:bg0nr2l) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/94ded58a76002a4713bbe8303d4a7f7017ae52b1/docs/operations/gaussian-noise-and-acdp.md#L31)):*
> ```Markdown
> ## Verification
> 
> When PBM is using ACDP compsoition and `noise_mechanism` passed in
> ```

Please use a complete sentence.


<!-- Sent from Reviewable.io -->

2023-08-25 18:05 UTC, iverson52000 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1185)* status: 0 of 1 files reviewed, 11 unresolved discussions (waiting on @kungfucraig, @SanjayVas, @stevenwarejones, and @uakyol)

___
*[`docs/operations/gaussian-noise-and-acdp.md` line 3 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1185#-NchCPZa-Kjvb0xY1J90:-NchkBgu1PsxaWFRMZD2:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/94ded58a76002a4713bbe8303d4a7f7017ae52b1/docs/operations/gaussian-noise-and-acdp.md#L3)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

This guide describes how to enable Gaussian Differential Privacy noise for multi-party computations (MPCs) and ...
</blockquote></details>

Done.
___
*[`docs/operations/gaussian-noise-and-acdp.md` line 13 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1185#-NchCtDP5rpedJr0ax6K:-Nchotkm4NcMQXD8dR_k:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/94ded58a76002a4713bbe8303d4a7f7017ae52b1/docs/operations/gaussian-noise-and-acdp.md#L13)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

You should mention that before starting the Kingdom rollout of gaussian noise that the first rollout step is to ensure that all EDP PBMs in the deployment support gaussian noise, and ideally the full ACDP implementation (or if not that they understand the impact of this).
</blockquote></details>

Done.
___
*[`docs/operations/gaussian-noise-and-acdp.md` line 18 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1185#-Ncdc2j62JIUlmnLznmk:-NchkCM1EnUZICp9o0AX:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/94ded58a76002a4713bbe8303d4a7f7017ae52b1/docs/operations/gaussian-noise-and-acdp.md#L18)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This is just linking to the example config used by our `dev` environment. You need to instead mention where this would be in their own Kingdom.
</blockquote></details>

Done.
___
*[`docs/operations/gaussian-noise-and-acdp.md` line 21 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1185#-NcdvrUL8kU5tPU7kjdu:-Nchpe4o1z75ls2iayur:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/94ded58a76002a4713bbe8303d4a7f7017ae52b1/docs/operations/gaussian-noise-and-acdp.md#L21)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Don't we also need a step to ensure that CONTINUOUS_GAUSSIAN is enabled for the Direct protocol? Even if it's set in our defaults, you need to make sure that the Kingdom operator didn't change the flag to be CONTINUOUS_LAPLACE only.
</blockquote></details>

Done.
___
*[`docs/operations/gaussian-noise-and-acdp.md` line 22 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1185#-NcdcdP67zPteep4Y2Sv:-NchqZto7HvXXHraelpE:b6qware) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/94ded58a76002a4713bbe8303d4a7f7017ae52b1/docs/operations/gaussian-noise-and-acdp.md#L22)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This is not actually a required step for enabling this feature. It's just something you need to do in order to run correctness tests after enabling it.

More broadly, EDP simulators are not part of a regular production deployment.
</blockquote></details>

Done. Tried to rephrase it to clarify.
___
*[`docs/operations/gaussian-noise-and-acdp.md` line 31 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1185#-NchDcLUBubdkJIx2lNi:-Nchm-F2-HaeTWegVisE:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/94ded58a76002a4713bbe8303d4a7f7017ae52b1/docs/operations/gaussian-noise-and-acdp.md#L31)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Please use a complete sentence.
</blockquote></details>

Done.
___
*[`docs/operations/gaussian-noise-and-acdp.md` line 72 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1185#-Ncdw_gV-2ovy592B1Nq:-NchnC635dbsgdV--FdE:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/94ded58a76002a4713bbe8303d4a7f7017ae52b1/docs/operations/gaussian-noise-and-acdp.md#L72)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Aren't the ledgers for ACDP and any existing PBM not compatible (see above comment)? If so, rolling back on the EDP side has the effect of dropping all the privacy charges.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-08-28 18:02 UTC, SanjayVas reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1185)* status: 0 of 1 files reviewed, 11 unresolved discussions (waiting on @kungfucraig, @stevenwarejones, and @uakyol)

___
*[`docs/operations/gaussian-noise-and-acdp.md` line  at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1185#-NchBfl65b-T4DNYb9Oq:-NcxHzrDADSwlq2rCalv:b-b16bzt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/94ded58a76002a4713bbe8303d4a7f7017ae52b1/docs/operations/gaussian-noise-and-acdp.md#L)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Having some file naming convention like:

rollout-<feature>.md I think would make sense. 

Even doing something like rollout-2023-08-<feature>.md could be helpful. 

@SanjayVas WDYT?

Alternatively a subdirectory of operations called "rollout" might help separate things that are essentially one-of from things that are more on going operations tasks.
</blockquote></details>

The repo shouldn't have one-off rollout info. It should instead only have docs that relate to the state of the *code*.

In this case, the doc should just be about the requirements/steps for enabling these features.


<!-- Sent from Reviewable.io -->

2023-08-28 21:02 UTC, SanjayVas requested changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1185)* status: all files reviewed, 5 unresolved discussions (waiting on @iverson52000, @kungfucraig, @stevenwarejones, and @uakyol)

___
*[`docs/operations/gaussian-noise-and-acdp.md` line 3 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1185#-Ncddfow4uv-TfzrLnV0:-NcxgK-S7qE3ikZKjvZA:bx4ntu8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/94ded58a76002a4713bbe8303d4a7f7017ae52b1/docs/operations/gaussian-noise-and-acdp.md#L3)):*
> under Rollout Steps

This guide shouldn't even have a Rollout Steps section. It's really about how a Kingdom operator would go about enabling EDPs to use ACDP for their PBM.  They do this by configuring the protocols to use/allow Gaussian noise mechanisms. See the other comment regarding naming.

There's really the following discrete parts for the Kingdom operator:

* Configuring MPC protocols to use Gaussian noise
    - Configuring R/F LLv2
    - Configuring RO LLv2
* Allowing the Direct protocol to use Gaussian noise
    - Prerequisite of EDPs reading possible noise mechanisms from ProtocolConfig.

The above are prerequisites to an EDP using ACDP. The EDP additionally needs to actually support and use Gaussian noise if it's allowed for the Direct protocol. Furthermore, the EDP *should* be using ACDP if Gaussian is used for all protocols.
___
*[`docs/operations/gaussian-noise-and-acdp.md` line 22 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1185#-NcdcdP67zPteep4Y2Sv:-NcxedoZ04XAZLk-4kum:b-gxf5u5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/94ded58a76002a4713bbe8303d4a7f7017ae52b1/docs/operations/gaussian-noise-and-acdp.md#L22)):*
<details><summary><i>Previously, iverson52000 (Albert Hsu) wrote…</i></summary><blockquote>

Done. Tried to rephrase it to clarify.
</blockquote></details>

Th EDP simulator isn't actually a reference implementation but a part of the correctness test infrastructure. It's not actually how any EDP should implement requisition fulfillment, but nonetheless can provide some guidance.

I would clarify this as a note for how to simulate an EDP using ACDP in a test environment.
___
*[`docs/operations/gaussian-noise-and-acdp.md` line 28 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1185#-NcdvIl72G0JCXSjZEXD:-NcxwJrl-C2wXWsf1K-M:b-7aj7vz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/94ded58a76002a4713bbe8303d4a7f7017ae52b1/docs/operations/gaussian-noise-and-acdp.md#L28)):*
> That's the first step. :)

I don't believe that's correct. Gaussian being used for LLv2 and allowed for Direct is a prerequisite for an EDP using ACDP.
___
*[`docs/operations/gaussian-noise-and-acdp.md` line 59 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1185#-NcdeaNuB1eIwYLDFnf5:-NcxwiJ2B5W6juhJ7xCo:b-efdbab) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/94ded58a76002a4713bbe8303d4a7f7017ae52b1/docs/operations/gaussian-noise-and-acdp.md#L59)):*
<details><summary><i>Previously, iverson52000 (Albert Hsu) wrote…</i></summary><blockquote>

Got it. How should I rephrase this part? Delete "For MPC Gaussian noise, the config files in the above Rollout Steps are part of
the testing secrets and are only used by the Halo dev environment."?
</blockquote></details>

Yeah. Basically don't even reference the testing files.
___
*[`docs/operations/gaussian-noise-and-acdp.md` line  at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1185#-NchBfl65b-T4DNYb9Oq:-NcxavMy2lUKNPoiQzXp:b-iga3of) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/94ded58a76002a4713bbe8303d4a7f7017ae52b1/docs/operations/gaussian-noise-and-acdp.md#L)):*
> Then we can use a different word instead of rollout, but fundamentally these types of docs are different than basic "how to you set up the system for the first time" types of things

I'm not sure what you mean. `docs/operations` is the directory specifically for operations docs, meaning things you might want to do as part of operating a component. This is specifically for things that you may do after a component is up and running.

To follow the existing naming pattern, maybe this should be `enabling-gaussian-noise.md` or `enabling-acdp-pbm.md`.


<!-- Sent from Reviewable.io -->

2023-08-29 18:05 UTC, iverson52000 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1185)* status: 0 of 2 files reviewed, 5 unresolved discussions (waiting on @kungfucraig, @SanjayVas, @stevenwarejones, and @uakyol)

___
*[`docs/operations/gaussian-noise-and-acdp.md` line 3 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1185#-Ncddfow4uv-TfzrLnV0:-Nd1Rqzk9SDRMURsEhDP:b-b5rd9k) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/94ded58a76002a4713bbe8303d4a7f7017ae52b1/docs/operations/gaussian-noise-and-acdp.md#L3)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> under Rollout Steps

This guide shouldn't even have a Rollout Steps section. It's really about how a Kingdom operator would go about enabling EDPs to use ACDP for their PBM.  They do this by configuring the protocols to use/allow Gaussian noise mechanisms. See the other comment regarding naming.

There's really the following discrete parts for the Kingdom operator:

* Configuring MPC protocols to use Gaussian noise
    - Configuring R/F LLv2
    - Configuring RO LLv2
* Allowing the Direct protocol to use Gaussian noise
    - Prerequisite of EDPs reading possible noise mechanisms from ProtocolConfig.

The above are prerequisites to an EDP using ACDP. The EDP additionally needs to actually support and use Gaussian noise if it's allowed for the Direct protocol. Furthermore, the EDP *should* be using ACDP if Gaussian is used for all protocols.
</blockquote></details>

Done. Restructure the doc and hope it's more clear now.
___
*[`docs/operations/gaussian-noise-and-acdp.md` line 22 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1185#-NcdcdP67zPteep4Y2Sv:-Nd1S1De1T4z58926_rF:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/94ded58a76002a4713bbe8303d4a7f7017ae52b1/docs/operations/gaussian-noise-and-acdp.md#L22)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Th EDP simulator isn't actually a reference implementation but a part of the correctness test infrastructure. It's not actually how any EDP should implement requisition fulfillment, but nonetheless can provide some guidance.

I would clarify this as a note for how to simulate an EDP using ACDP in a test environment.
</blockquote></details>

Done.
___
*[`docs/operations/gaussian-noise-and-acdp.md` line 59 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1185#-NcdeaNuB1eIwYLDFnf5:-Nd1S37I0zkGlosFxWFZ:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/94ded58a76002a4713bbe8303d4a7f7017ae52b1/docs/operations/gaussian-noise-and-acdp.md#L59)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Yeah. Basically don't even reference the testing files.
</blockquote></details>

Done.
___
*[`docs/operations/gaussian-noise-and-acdp.md` line  at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1185#-NchBfl65b-T4DNYb9Oq:-Nd1RiIm4yCAFKS9Fo7O:bmqfef8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/94ded58a76002a4713bbe8303d4a7f7017ae52b1/docs/operations/gaussian-noise-and-acdp.md#L)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> Then we can use a different word instead of rollout, but fundamentally these types of docs are different than basic "how to you set up the system for the first time" types of things

I'm not sure what you mean. `docs/operations` is the directory specifically for operations docs, meaning things you might want to do as part of operating a component. This is specifically for things that you may do after a component is up and running.

To follow the existing naming pattern, maybe this should be `enabling-gaussian-noise.md` or `enabling-acdp-pbm.md`.
</blockquote></details>

Rename file to `enabling-gaussian-noise-and-acdp-pbm.md` to follow existing naming pattern.
___
*[`docs/operations/gaussian-noise-and-acdp.md` line 48 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1185#-NcxNo1VDZI3HSmG8eyT:-Nd1S3tIE-9hDxzyCGFc:b-ycsa8i) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7242e5e1ed6eebeab0514d7b619aa5fd27e6d8ea/docs/operations/gaussian-noise-and-acdp.md#L48)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Can we document some ways to verify this in a running system? These all seem to be about code level verification.

Something I can think of: having EDPs confirm that their requisitions have this, confirming that the protocol config in the DB has this, confirming with Duchy operators that they see it coming though.
</blockquote></details>

I checked and see `MeasurementDetails` in `Measurements` table has protocol config for each measurement. Should we add that as verification here?


<!-- Sent from Reviewable.io -->

2023-08-29 18:56 UTC, kungfucraig requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1185)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @iverson52000, @SanjayVas, @stevenwarejones, and @uakyol)

___
*[`docs/operations/gaussian-noise-and-acdp.md` line 48 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1185#-NcxNo1VDZI3HSmG8eyT:-Nd1dV1o-9ErFlfAOmy3:b4ruo3t) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7242e5e1ed6eebeab0514d7b619aa5fd27e6d8ea/docs/operations/gaussian-noise-and-acdp.md#L48)):*
<details><summary><i>Previously, iverson52000 (Albert Hsu) wrote…</i></summary><blockquote>

I checked and see `MeasurementDetails` in `Measurements` table has protocol config for each measurement. Should we add that as verification here?
</blockquote></details>

That sounds good.


<!-- Sent from Reviewable.io -->

2023-08-29 21:50 UTC, SanjayVas requested changes
> Reviewed 1 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1185)* status: 1 of 2 files reviewed, 6 unresolved discussions (waiting on @iverson52000, @stevenwarejones, and @uakyol)

___
*[`docs/operations/updating-retention-policies.md` line 1 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1185#-Nd2GOrU6qLbNcZm7M9t:-Nd2GOrU6qLbNcZm7M9u:bj4i0c1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/73c0035177c7ce056f67a3fa48e15e3115ccd473/docs/operations/updating-retention-policies.md#L1)):*
> ```Markdown
> # Updating Retention Policies
> ```

nit: I don't think this file was otherwise edited for this PR. Avoid unrelated formatting changes.
___
*[`docs/operations/updating-retention-policies.md` line 100 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1185#-Nd2GXIsAIEXy62CJgPy:-Nd2GXIsAIEXy62CJgPz:b-vffw1o) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/73c0035177c7ce056f67a3fa48e15e3115ccd473/docs/operations/updating-retention-policies.md#L100)):*
> ```Markdown
> ### Human-Readable Duration
> 
> Human-readable format consists of a sequence elements each consisting of a
> ```

The formatter appears to have broken this.
___
*[`docs/operations/enabling-gaussian-noise-and-acdp-pbm.md` line 24 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1185#-Nd2CLWQEC5dyecX_aIs:-Nd2CLWQEC5dyecX_aIt:bc6bn8y) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/73c0035177c7ce056f67a3fa48e15e3115ccd473/docs/operations/enabling-gaussian-noise-and-acdp-pbm.md#L24)):*
> ```Markdown
> Gaussian noise to their direct measurements. The Gaussian noiser implementation
> is provided in
> `src/main/kotlin/org/wfanet/measurement/eventdataprovider/noiser/GaussianNoiser.kt`
> ```

nit: Use a relative link.



_Suggestion:_
```Markdown
[`GaussianNoiser.kt`](../../src/main/kotlin/org/wfanet/measurement/eventdataprovider/noiser/GaussianNoiser.kt)
```
___
*[`docs/operations/enabling-gaussian-noise-and-acdp-pbm.md` line 87 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1185#-Nd2G8UCCJoRKoM5qJAO:-Nd2G8UCCJoRKoM5qJAP:b2v2yqp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/73c0035177c7ce056f67a3fa48e15e3115ccd473/docs/operations/enabling-gaussian-noise-and-acdp-pbm.md#L87)):*
> ```Markdown
> ```
> 
> ## Kingdom Operator and EDP with PBM
> ```

I think you can drop this whole section. It's all covered above.
___
*[`docs/operations/gaussian-noise-and-acdp.md` line 22 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1185#-NcdcdP67zPteep4Y2Sv:-Nd2CmDj1m4BT2qJOemS:b-krvffd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/94ded58a76002a4713bbe8303d4a7f7017ae52b1/docs/operations/gaussian-noise-and-acdp.md#L22)):*
<details><summary><i>Previously, iverson52000 (Albert Hsu) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

This still not quite making it clear that this is not a normal step, but rather something just for test environments. It also references code rather than the command-line option. I was thinking something like:

```markdown
1.  When a Kingdom is configured to use discrete Gaussian noise for MPC
    requisitions, EDPs with PBM should update their requisition fulfillment
    pipelines to use ACDP composition.

    Note: If you have a testing environment with EDP simulators, you can
    update those simulators to use ACDP by setting the value of the
    `--composition-mechanism` option to `ACDP`.
```


<!-- Sent from Reviewable.io -->

2023-08-30 18:11 UTC, kungfucraig approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1185)* status: all files reviewed, 3 unresolved discussions (waiting on @SanjayVas, @stevenwarejones, and @uakyol)



<!-- Sent from Reviewable.io -->

2023-08-30 18:11 UTC, kungfucraig approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1185)* status: all files reviewed, 3 unresolved discussions (waiting on @SanjayVas, @stevenwarejones, and @uakyol)



<!-- Sent from Reviewable.io -->

2023-08-30 21:28 UTC, SanjayVas approved these changes
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1185)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones and @uakyol)



<!-- Sent from Reviewable.io -->

2023-08-30 21:49 UTC, uakyol approved these changes
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1185)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)



<!-- Sent from Reviewable.io -->

2023-08-31 20:35 UTC, stevenwarejones approved these changes
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1185)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @iverson52000)



<!-- Sent from Reviewable.io -->

2023-09-01 16:09 UTC, merged