Create Populations Spanner tables and Service
world-federation-of-advertisers/cross-media-measurement pull request #1206
Opened 2023-09-07 20:30 UTC by jojijac0b

2023-09-07 20:30 UTC, wfa-reviewable commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1206)
<!-- Reviewable:end -->

2023-09-08 13:17 UTC, Marco-Premier requested changes
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1206)* status: all files reviewed, 12 unresolved discussions (waiting on @jojijac0b and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/internal/kingdom/measurement.proto` line 301 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1206#-Ndou_1dCT8D6Zy9zT5u:-Ndou_1dCT8D6Zy9zT5v:b-w1bpck) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/70aeaf6f9710971740ae3ad5f4adbb486e0fbc10/src/main/proto/wfa/measurement/internal/kingdom/measurement.proto#L301)):*
> ```proto
>   ParentMeasurement parent_measurement = 12;
> 
>   fixed64 external_population_id = 13;
> ```

See below comment in ```model_release.proto```.
```fixed64 external_data_provider_id``` is missing.



_Code quote:_
```proto
fixed64 external_population_id = 13;
```
___
*[`src/main/proto/wfa/measurement/internal/kingdom/model_release.proto` line 33 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1206#-NdotzJ71l89nuSKFR5A:-NdotzJ71l89nuSKFR5B:b-2ndc45) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/70aeaf6f9710971740ae3ad5f4adbb486e0fbc10/src/main/proto/wfa/measurement/internal/kingdom/model_release.proto#L33)):*
> ```proto
>   google.protobuf.Timestamp create_time = 4;
> 
>   fixed64 external_population_id = 5;
> ```

I think you are missing ```fixed64 external_data_provider_id```.

Please see below comments. If the table ```Populations``` interleaves ```DataProviders``` you need both external keys to uniquely identify a Population



_Code quote:_
```proto
fixed64 external_population_id = 5;
```
___
*[`src/main/proto/wfa/measurement/internal/kingdom/population.proto` line 25 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1206#-NdovFPlBJTjdb5yUu5S:-NdovFPlBJTjdb5yUu5T:bgg1yex) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/70aeaf6f9710971740ae3ad5f4adbb486e0fbc10/src/main/proto/wfa/measurement/internal/kingdom/population.proto#L25)):*
> ```proto
> 
> message Population {
>   fixed64 external_population_id = 1;
> ```

missing ```fixed64 external_data_provider_id``` 



_Code quote:_
```proto
fixed64 external_population_id = 1;
```
___
*[`src/main/proto/wfa/measurement/internal/kingdom/population.proto` line 48 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1206#-Ndoukjs013spcNwp4T6:-Ndoukjs013spcNwp4T7:b-3qi777) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/70aeaf6f9710971740ae3ad5f4adbb486e0fbc10/src/main/proto/wfa/measurement/internal/kingdom/population.proto#L48)):*
> ```proto
>   // The EventTemplate that this population conforms to.
>   EventTemplate event_template = 5;
> }
> ```

Nit: add new line



_Code quote:_
```proto
}
```
___
*[`src/main/proto/wfa/measurement/internal/kingdom/populations_service.proto` line 33 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1206#-Ndovpaa1zTFnCIrHsDK:-Ndovpaa1zTFnCIrHsDL:boafm6x) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/70aeaf6f9710971740ae3ad5f4adbb486e0fbc10/src/main/proto/wfa/measurement/internal/kingdom/populations_service.proto#L33)):*
> ```proto
> 
> message GetPopulationRequest {
>   fixed64 external_requisition_id = 1;
> ```

why is this ```external_requisition_id```?
I thought it would be 

```
fixed64 external_data_provider_id = 1;
fixed64 external_population_id = 2;
```



_Code quote:_
```proto
fixed64 external_requisition_id = 1;
```
___
*[`src/main/resources/kingdom/spanner/add-model-releases-population.sql` line 18 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1206#-Ndoj8DwAsJn9qLE1h9P:-Ndoj8DwAsJn9qLE1h9Q:b-9y5zqz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/70aeaf6f9710971740ae3ad5f4adbb486e0fbc10/src/main/resources/kingdom/spanner/add-model-releases-population.sql#L18)):*
> ```TSQL
> 
> -- changeset jojijacob:4 dbms:cloudspanner
> START BATCH DDL;
> ```

No need for BATCH DDL when there's only one statement to run.
I'd rather move all the updates for the 3 tables in a single file (since they are correlated to the same change) and do use ```BATCH DDL``` in there.



_Code quote:_
```TSQL
START BATCH DDL;
```
___
*[`src/main/resources/kingdom/spanner/add-model-releases-population.sql` line 21 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1206#-NdohNg15OErejc2ga9I:-NdohNg15OErejc2ga9J:b-99perl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/70aeaf6f9710971740ae3ad5f4adbb486e0fbc10/src/main/resources/kingdom/spanner/add-model-releases-population.sql#L21)):*
> ```TSQL
> 
> ALTER TABLE ModelReleases
>     ADD COLUMN PopulationId INT64 NOT NULL;
> ```

Is this a FOREIGN KEY that points to the new ```Populations``` table?

If so it needs to be explicitly defined:

```
FOREIGN KEY (PopulationId, DataProviderId)  
  REFERENCES Populations(PopulationId, DataProviderId)
```

Note that Populations table interleaves in DataProvider table which means that the foreign key also has ``` DataProviderId``` since a Population is unique for a given DataProvider



_Code quote:_
```TSQL
ADD COLUMN PopulationId INT64 NOT NULL;
```
___
*[`src/main/resources/kingdom/spanner/add-model-releases-population.sql` line 23 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1206#-NdohFn40kjrI4tqfmWd:-NdohFn40kjrI4tqfmWe:b25l7al) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/70aeaf6f9710971740ae3ad5f4adbb486e0fbc10/src/main/resources/kingdom/spanner/add-model-releases-population.sql#L23)):*
> ```TSQL
>     ADD COLUMN PopulationId INT64 NOT NULL;
> 
> RUN BATCH;
> ```

nit: add new line



_Code quote:_
```TSQL
RUN BATCH;
```
___
*[`src/main/resources/kingdom/spanner/add-requisitions-population.sql` line 18 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1206#-NdojRvg7hCb_mJ5hsip:-NdojRvg7hCb_mJ5hsiq:bpvevg6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/70aeaf6f9710971740ae3ad5f4adbb486e0fbc10/src/main/resources/kingdom/spanner/add-requisitions-population.sql#L18)):*
> ```TSQL
> 
> -- changeset jojijacob:4 dbms:cloudspanner
> START BATCH DDL;
> ```

Same comment for ModelReleases table



_Code quote:_
```TSQL
START BATCH DDL;
```
___
*[`src/main/resources/kingdom/spanner/add-requisitions-population.sql` line 21 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1206#-Ndoj3Km4Q4ntlFz9_cq:-Ndoj3Km4Q4ntlFz9_cr:bpvevg6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/70aeaf6f9710971740ae3ad5f4adbb486e0fbc10/src/main/resources/kingdom/spanner/add-requisitions-population.sql#L21)):*
> ```TSQL
> 
> ALTER TABLE Requisitions
>     ADD COLUMN PopulationId INT64 NOT NULL;
> ```

Same comment for ModelReleases table



_Code quote:_
```TSQL
ADD COLUMN PopulationId INT64 NOT NULL;
```
___
*[`src/main/resources/kingdom/spanner/add-requisitions-population.sql` line 23 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1206#-NdohI844KjOu4fcrCuT:-NdohI854umW6qMUFD5E:b25l7al) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/70aeaf6f9710971740ae3ad5f4adbb486e0fbc10/src/main/resources/kingdom/spanner/add-requisitions-population.sql#L23)):*
> ```TSQL
>     ADD COLUMN PopulationId INT64 NOT NULL;
> 
> RUN BATCH;
> ```

nit: add new line



_Code quote:_
`` [...]

2023-09-08 14:10 UTC, stevenwarejones reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1206)* status: all files reviewed, 12 unresolved discussions (waiting on @jojijac0b and @Marco-Premier)

___
*[`src/main/resources/kingdom/spanner/create-population-schema.sql` line 23 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1206#-NdojZH34tnkp9cd6v1i:-Ndp77w47exFIFZ2yN-Y:bg05d3i) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/70aeaf6f9710971740ae3ad5f4adbb486e0fbc10/src/main/resources/kingdom/spanner/create-population-schema.sql#L23)):*
<details><summary><i>Previously, Marco-Premier (marcopremier) wrote…</i></summary><blockquote>

@stevenwarejones  is this table a child of ```DataProviders```? I thought that the blob was provided by a ```ModelProviders```?
</blockquote></details>

yes - its a child of DataProviders - a ModelProvider, in the future, may access this resource in order to build and provider their model


<!-- Sent from Reviewable.io -->

2023-09-08 14:12 UTC, stevenwarejones reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1206)* status: all files reviewed, 13 unresolved discussions (waiting on @jojijac0b and @Marco-Premier)

___
*[`src/main/proto/wfa/measurement/internal/kingdom/populations_service.proto` line 34 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1206#-Ndp7Uft3MgM_TMvtn-Y:-Ndp7Uft3MgM_TMvtn-Z:b4aca8f) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/70aeaf6f9710971740ae3ad5f4adbb486e0fbc10/src/main/proto/wfa/measurement/internal/kingdom/populations_service.proto#L34)):*
> ```proto
> message GetPopulationRequest {
>   fixed64 external_requisition_id = 1;
> }
> ```

we also need a ListPopulationRequest that lists all the populations for a DataProvider imo


<!-- Sent from Reviewable.io -->

2023-09-12 12:24 UTC, Marco-Premier requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1206)* status: 0 of 7 files reviewed, 18 unresolved discussions (waiting on @jojijac0b)

___
*[`src/main/proto/wfa/measurement/internal/kingdom/populations_service.proto` line 31 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1206#-Ne8GhXV5tyD4mCahe4p:-Ne8GhXV5tyD4mCahe4q:b-111u9o) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/455ecb403b264305c5d5b7c1cd979d5e1b20c5d2/src/main/proto/wfa/measurement/internal/kingdom/populations_service.proto#L31)):*
> ```proto
>   rpc GetPopulation(GetPopulationRequest) returns (Population);
> 
>   rpc StreamPopulation(StreamPopulationRequest) returns (stream Population);
> ```

```StreamPopulations``` add missing 's'. It's plural



_Code quote:_
```proto
StreamPopulation
```
___
*[`src/main/proto/wfa/measurement/internal/kingdom/populations_service.proto` line 39 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1206#-Ne8Iym4BCkpWBvZIE5x:-Ne8Iym4BCkpWBvZIE5y:bi57pyj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/455ecb403b264305c5d5b7c1cd979d5e1b20c5d2/src/main/proto/wfa/measurement/internal/kingdom/populations_service.proto#L39)):*
> ```proto
> }
> 
> message StreamPopulationRequest {
> ```

```external_data_provider_id``` is not enough to perform pagination.

There is an existing proto message that can be used: ```AfterFilter```.
There are some examples in the code that uses it, you can be found here in model_line_service.proto

https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/main/proto/wfa/measurement/internal/kingdom/model_lines_service.proto#L38

So the message will look like:

```
message StreamPopulationsRequest {
  message AfterFilter {
    ...
    AfterFilter after = X;
  }
  message Filter {
    ...
  }
  int32 limit = Y;
}
```




_Code quote:_
```proto
message StreamPopulationRequest {
```
___
*[`src/main/proto/wfa/measurement/internal/kingdom/populations_service.proto` line 39 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1206#-Ne8K-xD-xH8mJ2rFF47:-Ne8K-xD-xH8mJ2rFF48:b-emqt6s) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/455ecb403b264305c5d5b7c1cd979d5e1b20c5d2/src/main/proto/wfa/measurement/internal/kingdom/populations_service.proto#L39)):*
> ```proto
> }
> 
> message StreamPopulationRequest {
> ```

```StreamPopulationsRequest``` missing 's', it's plural



_Code quote:_
```proto
StreamPopulationRequest
```
___
*[`src/main/resources/kingdom/spanner/create-population-schema.sql` line 45 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1206#-Ne8KpUMDQFcuSYtxwM_:-Ne8KpUMDQFcuSYtxwMa:b-ctcnhx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/455ecb403b264305c5d5b7c1cd979d5e1b20c5d2/src/main/resources/kingdom/spanner/create-population-schema.sql#L45)):*
> ```TSQL
> 
> ALTER TABLE Requisitions
>     ADD COLUMN PopulationId INT64 NOT NULL;
> ```

@stevenwarejones , do we have to update ```requisition``` proto message as well here: https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/main/proto/wfa/measurement/system/v1alpha/requisition.proto

Requisitions are created by the Kingdom at measurement creation time, where does the kingdom retrieve what population a requisition is linked to?



_Code quote:_
```TSQL
ALTER TABLE Requisitions
    ADD COLUMN PopulationId INT64 NOT NULL;
```
___
*[`src/main/resources/kingdom/spanner/create-population-schema.sql` line 48 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1206#-Ne8KF6q4Id_e2iz01sP:-Ne8KF6q4Id_e2iz01sQ:b6s2f1n) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/455ecb403b264305c5d5b7c1cd979d5e1b20c5d2/src/main/resources/kingdom/spanner/create-population-schema.sql#L48)):*
> ```TSQL
> 
> ALTER TABLE ModelReleases
>     ADD COLUMN PopulationId INT64 NOT NULL;
> ```

I think it's still missing foreign key here @jojijac0b ?



_Code quote:_
```TSQL
ALTER TABLE Requisitions
    ADD COLUMN PopulationId INT64 NOT NULL;

ALTER TABLE ModelReleases
    ADD COLUMN PopulationId INT64 NOT NULL;
```


<!-- Sent from Reviewable.io -->

2023-09-18 21:00 UTC, stevenwarejones requested changes
> Reviewed 6 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1206)* status: 6 of 7 files reviewed, 19 unresolved discussions (waiting on @jojijac0b and @Marco-Premier)

___
*[`src/main/proto/wfa/measurement/internal/kingdom/measurement.proto` line 142 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1206#-Nedt3p7-wmxbBDAtt95:-Nedt3p7-wmxbBDAtt96:b-gy76l3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/455ecb403b264305c5d5b7c1cd979d5e1b20c5d2/src/main/proto/wfa/measurement/internal/kingdom/measurement.proto#L142)):*
> ```proto
>     bytes encrypted_result = 4;
>   }
>   repeated ResultInfo results = 11;
> ```

this is where the population result is store. We don't need to have a separate field.
___
*[`src/main/proto/wfa/measurement/internal/kingdom/measurement.proto` line 158 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1206#-Nedt7fSDjbQBbVLe9bh:-Nedt7fSDjbQBbVLe9bi:b-vpqm47) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/455ecb403b264305c5d5b7c1cd979d5e1b20c5d2/src/main/proto/wfa/measurement/internal/kingdom/measurement.proto#L158)):*
> ```proto
>   string etag = 14;
> 
>   message Population {
> ```

see my other message - delete
___
*[`src/main/resources/kingdom/spanner/create-population-schema.sql` line 45 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1206#-Ne8KpUMDQFcuSYtxwM_:-Nee51aS8K4Nh0XvTaCf:bohjhn) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/455ecb403b264305c5d5b7c1cd979d5e1b20c5d2/src/main/resources/kingdom/spanner/create-population-schema.sql#L45)):*
<details><summary><i>Previously, Marco-Premier (marcopremier) wrote…</i></summary><blockquote>

@stevenwarejones , do we have to update ```requisition``` proto message as well here: https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/main/proto/wfa/measurement/system/v1alpha/requisition.proto

Requisitions are created by the Kingdom at measurement creation time, where does the kingdom retrieve what population a requisition is linked to?
</blockquote></details>

this shouldn't be here. the population is store inside the encrypted measurement.result.


<!-- Sent from Reviewable.io -->

2023-09-19 18:37 UTC, jojijac0b reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1206)* status: 3 of 8 files reviewed, 18 unresolved discussions (waiting on @Marco-Premier and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/internal/kingdom/model_release.proto` line 33 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1206#-NdotzJ71l89nuSKFR5A:-NdqA69RDjYjj6M1b_0R:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/70aeaf6f9710971740ae3ad5f4adbb486e0fbc10/src/main/proto/wfa/measurement/internal/kingdom/model_release.proto#L33)):*
<details><summary><i>Previously, Marco-Premier (marcopremier) wrote…</i></summary><blockquote>

I think you are missing ```fixed64 external_data_provider_id```.

Please see below comments. If the table ```Populations``` interleaves ```DataProviders``` you need both external keys to uniquely identify a Population
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/internal/kingdom/population.proto` line 25 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1206#-NdovFPlBJTjdb5yUu5S:-NdqANpo9NBl1Y_2ljGV:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/70aeaf6f9710971740ae3ad5f4adbb486e0fbc10/src/main/proto/wfa/measurement/internal/kingdom/population.proto#L25)):*
<details><summary><i>Previously, Marco-Premier (marcopremier) wrote…</i></summary><blockquote>

missing ```fixed64 external_data_provider_id```
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/internal/kingdom/populations_service.proto` line 33 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1206#-Ndovpaa1zTFnCIrHsDK:-NdqAY_NDlfuG6uc7Hw5:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/70aeaf6f9710971740ae3ad5f4adbb486e0fbc10/src/main/proto/wfa/measurement/internal/kingdom/populations_service.proto#L33)):*
<details><summary><i>Previously, Marco-Premier (marcopremier) wrote…</i></summary><blockquote>

why is this ```external_requisition_id```?
I thought it would be 

```
fixed64 external_data_provider_id = 1;
fixed64 external_population_id = 2;
```
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/internal/kingdom/populations_service.proto` line 39 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1206#-Ne8K-xD-xH8mJ2rFF47:-NeihLMA6Wjx8UIHtlKL:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/455ecb403b264305c5d5b7c1cd979d5e1b20c5d2/src/main/proto/wfa/measurement/internal/kingdom/populations_service.proto#L39)):*
<details><summary><i>Previously, Marco-Premier (marcopremier) wrote…</i></summary><blockquote>

```StreamPopulationsRequest``` missing 's', it's plural
</blockquote></details>

Done.
___
*[`src/main/resources/kingdom/spanner/create-population-schema.sql` line 45 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1206#-Ne8KpUMDQFcuSYtxwM_:-Neih90O-D9_VIPLcKtB:bss4a2b) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/455ecb403b264305c5d5b7c1cd979d5e1b20c5d2/src/main/resources/kingdom/spanner/create-population-schema.sql#L45)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

this shouldn't be here. the population is store inside the encrypted measurement.result.
</blockquote></details>

Removed.
___
*[`src/main/resources/kingdom/spanner/create-population-schema.sql` line 48 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1206#-Ne8KF6q4Id_e2iz01sP:-NeihBj85dhHXwiWhrot:b-o8l0di) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/455ecb403b264305c5d5b7c1cd979d5e1b20c5d2/src/main/resources/kingdom/spanner/create-population-schema.sql#L48)):*
<details><summary><i>Previously, Marco-Premier (marcopremier) wrote…</i></summary><blockquote>

I think it's still missing foreign key here @jojijac0b ?
</blockquote></details>

Created new file to add foreign key to ModelReleases
___
*[`src/main/proto/wfa/measurement/internal/kingdom/measurement.proto` line 301 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1206#-Ndou_1dCT8D6Zy9zT5u:-Ndq9kWb3s0oi8HVH2RF:bg1b5ob) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/70aeaf6f9710971740ae3ad5f4adbb486e0fbc10/src/main/proto/wfa/measurement/internal/kingdom/measurement.proto#L301)):*
<details><summary><i>Previously, Marco-Premier (marcopremier) wrote…</i></summary><blockquote>

See below comment in ```model_release.proto```.
```fixed64 external_data_provider_id``` is missing.
</blockquote></details>

removing external_population_id as this will be provided in the requisition_spec


<!-- Sent from Reviewable.io -->

2023-09-20 17:06 UTC, jojijac0b reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1206)* status: 6 of 10 files reviewed, 19 unresolved discussions (waiting on @Marco-Premier and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/internal/kingdom/population.proto` line 42 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1206#-NemaWayEgCBMmpNBIob:-NenYX23DLh599TQu3Vp:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d8ecc2cdded825c39ca283e997f1b8f4e85b94ea/src/main/proto/wfa/measurement/internal/kingdom/population.proto#L42)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

i'd prefer this message type get pulled into its own file since I think it will be later used by other messages outside this file as well
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/internal/kingdom/populations_service.proto` line 31 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1206#-Ne8GhXV5tyD4mCahe4p:-NenRO2_7n9aQIAzP211:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/455ecb403b264305c5d5b7c1cd979d5e1b20c5d2/src/main/proto/wfa/measurement/internal/kingdom/populations_service.proto#L31)):*
<details><summary><i>Previously, Marco-Premier (marcopremier) wrote…</i></summary><blockquote>

```StreamPopulations``` add missing 's'. It's plural
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/internal/kingdom/populations_service.proto` line 39 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1206#-Ne8Iym4BCkpWBvZIE5x:-NenRLcDDz9jUkZWPQDH:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/455ecb403b264305c5d5b7c1cd979d5e1b20c5d2/src/main/proto/wfa/measurement/internal/kingdom/populations_service.proto#L39)):*
<details><summary><i>Previously, Marco-Premier (marcopremier) wrote…</i></summary><blockquote>

```external_data_provider_id``` is not enough to perform pagination.

There is an existing proto message that can be used: ```AfterFilter```.
There are some examples in the code that uses it, you can be found here in model_line_service.proto

https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/main/proto/wfa/measurement/internal/kingdom/model_lines_service.proto#L38

So the message will look like:

```
message StreamPopulationsRequest {
  message AfterFilter {
    ...
    AfterFilter after = X;
  }
  message Filter {
    ...
  }
  int32 limit = Y;
}
```

</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-09-20 17:07 UTC, jojijac0b reviewed
It looks like the Population data is already mentioned in the comments here

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1206#-:-NenYepR9gnbaIK5s2Aa:b-ln9dha)* status: 6 of 10 files reviewed, 19 unresolved discussions (waiting on @Marco-Premier and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2023-09-20 18:39 UTC, stevenwarejones requested changes
Add the comment here: https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2cceea41f671d90f3332ada971910c86e0f7fa63/src/main/proto/wfa/measurement/internal/kingdom/protocol_config.proto#L86

> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1206#-:-NensqQo8dCuhI4QYSp9:bbavd10)* status: all files reviewed, 16 unresolved discussions (waiting on @jojijac0b and @Marco-Premier)



<!-- Sent from Reviewable.io -->

2023-09-21 13:30 UTC, stevenwarejones approved these changes
Just get Marco and Sanjay to approve

> Reviewed 7 of 7 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1206#-:-NervpH-3UqXVlucTfUr:bqwkcpa)* status: all files reviewed, 16 unresolved discussions (waiting on @jojijac0b and @Marco-Premier)



<!-- Sent from Reviewable.io -->

2023-09-22 18:29 UTC, jojijac0b reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1206)* status: 12 of 13 files reviewed, 15 unresolved discussions (waiting on @Marco-Premier, @SanjayVas, and @stevenwarejones)

___
*[`src/main/resources/kingdom/spanner/add-model-releases-population.sql` line 18 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1206#-Ndoj8DwAsJn9qLE1h9P:-Ney8hdt8hHjdmgZDXKb:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/70aeaf6f9710971740ae3ad5f4adbb486e0fbc10/src/main/resources/kingdom/spanner/add-model-releases-population.sql#L18)):*
<details><summary><i>Previously, Marco-Premier (marcopremier) wrote…</i></summary><blockquote>

No need for BATCH DDL when there's only one statement to run.
I'd rather move all the updates for the 3 tables in a single file (since they are correlated to the same change) and do use ```BATCH DDL``` in there.
</blockquote></details>

Done.
___
*[`src/main/resources/kingdom/spanner/add-model-releases-population.sql` line 21 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1206#-NdohNg15OErejc2ga9I:-Ney8i6S8QFtGDQ9mDpY:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/70aeaf6f9710971740ae3ad5f4adbb486e0fbc10/src/main/resources/kingdom/spanner/add-model-releases-population.sql#L21)):*
<details><summary><i>Previously, Marco-Premier (marcopremier) wrote…</i></summary><blockquote>

Is this a FOREIGN KEY that points to the new ```Populations``` table?

If so it needs to be explicitly defined:

```
FOREIGN KEY (PopulationId, DataProviderId)  
  REFERENCES Populations(PopulationId, DataProviderId)
```

Note that Populations table interleaves in DataProvider table which means that the foreign key also has ``` DataProviderId``` since a Population is unique for a given DataProvider
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-09-25 15:50 UTC, jojijac0b reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1206)* status: 12 of 13 files reviewed, 14 unresolved discussions (waiting on @Marco-Premier, @SanjayVas, and @stevenwarejones)

___
*[`src/main/resources/kingdom/spanner/add-requisitions-population.sql` line 18 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1206#-NdojRvg7hCb_mJ5hsip:-NfC1K7S71dzOzuZTBz2:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/70aeaf6f9710971740ae3ad5f4adbb486e0fbc10/src/main/resources/kingdom/spanner/add-requisitions-population.sql#L18)):*
<details><summary><i>Previously, Marco-Premier (marcopremier) wrote…</i></summary><blockquote>

Same comment for ModelReleases table
</blockquote></details>

Done.
___
*[`src/main/resources/kingdom/spanner/add-requisitions-population.sql` line 21 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1206#-Ndoj3Km4Q4ntlFz9_cq:-NfC1JjM7DK4UiGtUb_l:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/70aeaf6f9710971740ae3ad5f4adbb486e0fbc10/src/main/resources/kingdom/spanner/add-requisitions-population.sql#L21)):*
<details><summary><i>Previously, Marco-Premier (marcopremier) wrote…</i></summary><blockquote>

Same comment for ModelReleases table
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-09-25 19:34 UTC, SanjayVas requested changes
> Reviewed 2 of 7 files at r2, 1 of 5 files at r3, 1 of 4 files at r4, 5 of 7 files at r5, 1 of 1 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1206)* status: all files reviewed, 21 unresolved discussions (waiting on @jojijac0b and @Marco-Premier)

___
*[`src/main/proto/wfa/measurement/internal/kingdom/event_template.proto` line 22 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1206#-NfCksbpAE2_OXkhP9r-:-NfCksbpAE2_OXkhP9r0:b9c286) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/89ecdacaa344ce0516f4baabf550880a1f06ba4e/src/main/proto/wfa/measurement/internal/kingdom/event_template.proto#L22)):*
> ```proto
> option java_multiple_files = true;
> 
> message EventTemplate {
> ```

If you're going to extract this message, also update the internal EventGroup definition.
___
*[`src/main/proto/wfa/measurement/internal/kingdom/measurement.proto` line 266 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1206#-NfCfyq367WDYHn9mhb3:-NfCfyq367WDYHn9mhb4:b7k1ixk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/89ecdacaa344ce0516f4baabf550880a1f06ba4e/src/main/proto/wfa/measurement/internal/kingdom/measurement.proto#L266)):*
> ```proto
>     // Set when `Requisition` state is FULFILLED and the
>     // `measurement_spec` `measurement_type` of the Parent
>     // `Measurement` is Impression or Duration or Population.
> ```

This can be simplified to just mentioning the Direct protocol rather than trying[^1] to enumerate all the cases where that protocol is used.

"Encrypted `SignedData` containing the `Measurement.Result` for this `Requisition`. Set when `Requisition` state is `FULFILLED` and the protocol is `Direct`.

[^1]: It cannot actually enumerate all the cases as the Kingdom can have logic that dynamically determines which protocol(s) may be used.



_Code quote:_
```proto
    // Encrypted `SignedData`containing the data for a population
    // measurement or a direct and volumetric event measurement.
    // Set when `Requisition` state is FULFILLED and the
    // `measurement_spec` `measurement_type` of the Parent
    // `Measurement` is Impression or Duration or Population.
```
___
*[`src/main/proto/wfa/measurement/internal/kingdom/model_release.proto` line 33 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1206#-NdotzJ71l89nuSKFR5A:-NfChwh0EH5OQpRXj5k1:b-7qtuav) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/70aeaf6f9710971740ae3ad5f4adbb486e0fbc10/src/main/proto/wfa/measurement/internal/kingdom/model_release.proto#L33)):*
> If the table `Populations` interleaves `DataProviders` you need both external keys to uniquely identify a Population

As an FYI, it's not actually conditioned on the table interleaving as the internal API does not prescribe that part of the DB implementation. It's really that the public API only guarantees uniqueness of each resource ID in the context of its parent. Our internal API design reflects this, as the resource IDs are just encoded versions of the external IDs.
___
*[`src/main/resources/kingdom/spanner/create-population-schema.sql` line 48 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1206#-Ne8KF6q4Id_e2iz01sP:-NfClvXh5LHZBiXy_miB:bw49i3k) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/455ecb403b264305c5d5b7c1cd979d5e1b20c5d2/src/main/resources/kingdom/spanner/create-population-schema.sql#L48)):*
<details><summary><i>Previously, jojijac0b wrote…</i></summary><blockquote>

Created new file to add foreign key to ModelReleases
</blockquote></details>

It looks like the other changeset also adds the column, so we don't even need this ALTER TABLE here. Since the resulting change only has a single DDL statement, there's no benefit to running it in a batch.

That said, we do prefer batching related things in a single changeset so I'd recommend doing this in one file/changeset. The resulting schema update process will run faster that way.
___
*[`src/main/resources/kingdom/spanner/create-population-schema.sql` line 1 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1206#-NfCnLRJALnYA__MSeEE:-NfCnLRJALnYA__MSeEF:b-97vaxh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/89ecdacaa344ce0516f4baabf550880a1f06ba4e/src/main/resources/kingdom/spanner/create-population-schema.sql#L1)):*
> ```TSQL
> -- liquibase formatted sql
> ```

Missing changes to `changelog.yaml` to include these changesets.
___
*[`src/main/resources/kingdom/spanner/create-population-schema.sql` line 17 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1206#-NfCmUWnARyCOg2KNvyP:-NfCmUWo--fuaHqA0_TG:b-pt5vdy) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/89ecdacaa344ce0516f4baabf550880a1f06ba4e/src/main/resources/kingdom/spanner/create-population-schema.sql#L17)):*
> ```TSQL
> -- limitations under the License.
> 
> -- changeset marcopremier:5 dbms:cloudspanner
> ```

This should be the author and the changeset ID. For this changelog, we use sequential integers starting at 1. This is the 14th entry in the changelog.



_Suggestion:_
```TSQL
jojijac0b:14
```
___
*[`src/main/resources/kingdom/spanner/create-population-schema.sql` line 19 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1206#-NfClSMjC2R_lnxUVBdy:-NfClSMjC2R_lnxUVBdz:b-k1yd9n) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/89ecdacaa344ce0516f4baabf550880a1f06ba4e/src/main/resources/kingdom/spanner/create-population-schema.sql#L19)):*
> ```TSQL
> -- changeset marcopremier:5 dbms:cloudspanner
> 
> -- Cloud Spanner database schema for the Kingdom StateTransitionMeasurementLogEntries table.
> ```

Inaccurate, as is the file name. This isn't creating a whole schema, just adding a table.



_Code quote:_
```TSQL
Cloud Spanner database schema for the Kingdom StateTransitionMeasurementLogEntries table.
```
___
*[`src/main/resources/kingdom/spanner/update-model-releases-foreign-key.sql` line 16 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1206#-NfCnDak-mntAUKuPIzr:-NfCnDal1d0y6xEnXdeN:undefined) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/89ecdacaa344ce0516f4baabf550880a1f06ba4e/src/main/resources/kingdom/spanner/update-model-releases-foreign-key.sql#L16)):*
> ```TSQL
> -- See the License for the specific language governing permissions and
> -- limitations under the License.
> -- changeset marcopremier:9 dbms:cloudspanner
> ```





_Suggestion:_
```TSQL
jojijac0b:15
```
___
*[`src/main/resources/kingdom/spanner/update-model-releases-foreign-key.sql` line 28 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1206#-NfCoG_KBQTHFPSACqNE:-NfCoG_KBQTHFPSACqNF:bz1pjza) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/89ecdacaa344ce0516f4baabf550880a1f06ba4e/src/main/resources/kingdom/spanner/update-model-releases-foreign-key.sql#L28)):*
> ```TSQL
>     FOREIGN KEY (Population) REFERENCES Populations(PopulationId),
> ) PRIMARY KEY (ModelProviderId, ModelSuiteId, ModelReleaseId),
>   INTERLEAVE IN PARENT ModelSuites ON DELETE CASCADE;
> ```

Why is this dropping and re-adding a whole table? Columns and table constraints can be added using ALTER TABLE statements. See https://cloud.google.com/spanner/docs/reference/standard-sql/data-definition-language#alter_table



_Code quote:_
```TSQL
DROP TABLE ModelReleases;
CREATE TABLE Mode [...]

2023-09-26 19:48 UTC, jojijac0b reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1206)* status: 7 of 16 files reviewed, 21 unresolved discussions (waiting on @Marco-Premier, @SanjayVas, and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/internal/kingdom/event_template.proto` line 22 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1206#-NfCksbpAE2_OXkhP9r-:-NfI17sn86aUj2fhNEca:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/89ecdacaa344ce0516f4baabf550880a1f06ba4e/src/main/proto/wfa/measurement/internal/kingdom/event_template.proto#L22)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

If you're going to extract this message, also update the internal EventGroup definition.
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/internal/kingdom/measurement.proto` line 266 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1206#-NfCfyq367WDYHn9mhb3:-NfI18gOEJiZbsPaOOJv:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/89ecdacaa344ce0516f4baabf550880a1f06ba4e/src/main/proto/wfa/measurement/internal/kingdom/measurement.proto#L266)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This can be simplified to just mentioning the Direct protocol rather than trying[^1] to enumerate all the cases where that protocol is used.

"Encrypted `SignedData` containing the `Measurement.Result` for this `Requisition`. Set when `Requisition` state is `FULFILLED` and the protocol is `Direct`.

[^1]: It cannot actually enumerate all the cases as the Kingdom can have logic that dynamically determines which protocol(s) may be used.
</blockquote></details>

Done.
___
*[`src/main/resources/kingdom/spanner/create-population-schema.sql` line 48 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1206#-Ne8KF6q4Id_e2iz01sP:-NfI0wt5DwIaHrWM7EN-:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/455ecb403b264305c5d5b7c1cd979d5e1b20c5d2/src/main/resources/kingdom/spanner/create-population-schema.sql#L48)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

It looks like the other changeset also adds the column, so we don't even need this ALTER TABLE here. Since the resulting change only has a single DDL statement, there's no benefit to running it in a batch.

That said, we do prefer batching related things in a single changeset so I'd recommend doing this in one file/changeset. The resulting schema update process will run faster that way.
</blockquote></details>

Done.
___
*[`src/main/resources/kingdom/spanner/create-population-schema.sql` line 1 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1206#-NfCnLRJALnYA__MSeEE:-NfI1Dr30z8GILbRexkr:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/89ecdacaa344ce0516f4baabf550880a1f06ba4e/src/main/resources/kingdom/spanner/create-population-schema.sql#L1)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Missing changes to `changelog.yaml` to include these changesets.
</blockquote></details>

Done.
___
*[`src/main/resources/kingdom/spanner/create-population-schema.sql` line 17 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1206#-NfCmUWnARyCOg2KNvyP:-NfI1-WJ2yR_Zww73KZl:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/89ecdacaa344ce0516f4baabf550880a1f06ba4e/src/main/resources/kingdom/spanner/create-population-schema.sql#L17)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This should be the author and the changeset ID. For this changelog, we use sequential integers starting at 1. This is the 14th entry in the changelog.
</blockquote></details>

Done.
___
*[`src/main/resources/kingdom/spanner/create-population-schema.sql` line 19 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1206#-NfClSMjC2R_lnxUVBdy:-NfI1-A8Dkf23JW_S0P4:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/89ecdacaa344ce0516f4baabf550880a1f06ba4e/src/main/resources/kingdom/spanner/create-population-schema.sql#L19)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Inaccurate, as is the file name. This isn't creating a whole schema, just adding a table.
</blockquote></details>

Done.
___
*[`src/main/resources/kingdom/spanner/update-model-releases-foreign-key.sql` line 28 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1206#-NfCoG_KBQTHFPSACqNE:-NfI1GY_50TFdUUECLxB:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/89ecdacaa344ce0516f4baabf550880a1f06ba4e/src/main/resources/kingdom/spanner/update-model-releases-foreign-key.sql#L28)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Why is this dropping and re-adding a whole table? Columns and table constraints can be added using ALTER TABLE statements. See https://cloud.google.com/spanner/docs/reference/standard-sql/data-definition-language#alter_table
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-09-26 21:45 UTC, stevenwarejones requested changes
> Reviewed 1 of 1 files at r6, 8 of 9 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1206)* status: 15 of 16 files reviewed, 22 unresolved discussions (waiting on @jojijac0b, @Marco-Premier, and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt` line 517 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1206#-NfIRnyZ-s8BX6CaoaqZ:-NfIRnyZ-s8BX6Caoaq_:b-porqd7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b988817d15c966a3f7eabd2a0a5f3e4a8b57b644/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt#L517)):*
> ```Kotlin
>       eventTemplates.addAll(
>         this@toInternal.eventTemplatesList.map { event ->
>           org.wfanet.measurement.internal.kingdom.eventTemplate { fullyQualifiedType = event.type }
> ```

import this at the top


<!-- Sent from Reviewable.io -->

2023-09-26 22:51 UTC, SanjayVas requested changes
> Reviewed 9 of 9 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1206)* status: all files reviewed, 17 unresolved discussions (waiting on @jojijac0b, @Marco-Premier, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt` line 517 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1206#-NfIRnyZ-s8BX6CaoaqZ:-NfIeglEC1clH2H7zPcp:bh1h833) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b988817d15c966a3f7eabd2a0a5f3e4a8b57b644/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt#L517)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

import this at the top
</blockquote></details>

More specifically, with the alias `internalEventTemplate` to distinguish it from the public API DSL builder.
___
*[`src/main/resources/kingdom/spanner/create-population-schema.sql` line 3 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1206#-NfIfHoADhgA0GfUpovF:-NfIfHoB7HXeqaZKVdZp:b2vfebm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b988817d15c966a3f7eabd2a0a5f3e4a8b57b644/src/main/resources/kingdom/spanner/create-population-schema.sql#L3)):*
> ```TSQL
> -- liquibase formatted sql
> 
> -- Copyright 2022 The Cross-Media Measurement Authors
> ```

This should be the year the file was first written



_Suggestion:_
```TSQL
2023
```
___
*[`src/main/resources/kingdom/spanner/create-population-schema.sql` line 46 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1206#-NfIfV7G1AE4FGeiYaQa:-NfIfV7G1AE4FGeiYaQb:b-xwxwep) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b988817d15c966a3f7eabd2a0a5f3e4a8b57b644/src/main/resources/kingdom/spanner/create-population-schema.sql#L46)):*
> ```TSQL
> ALTER TABLE ModelReleases
>     ADD COLUMN PopulationId INT64 NOT NULL;
>     FOREIGN KEY (Population) REFERENCES Populations(PopulationId);
> ```

I don't think this is the right syntax. If I'm reading the docs correctly, you need two separate ALTER TABLE statements.

See https://cloud.google.com/spanner/docs/reference/standard-sql/data-definition-language#alter_table



_Suggestion:_
```TSQL
ALTER TABLE ModelReleases ADD COLUMN PopulationId INT64 NOT NULL;
ALTER TABLE ModelReleases ADD FOREIGN KEY (PopulationId) REFERENCES Populations(PopulationId);
```


<!-- Sent from Reviewable.io -->

2023-09-27 16:53 UTC, jojijac0b reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1206)* status: 14 of 16 files reviewed, 17 unresolved discussions (waiting on @Marco-Premier, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt` line 517 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1206#-NfIRnyZ-s8BX6CaoaqZ:-NfMYQzMCh4wOgheDJ0L:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b988817d15c966a3f7eabd2a0a5f3e4a8b57b644/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt#L517)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

More specifically, with the alias `internalEventTemplate` to distinguish it from the public API DSL builder.
</blockquote></details>

Done.
___
*[`src/main/resources/kingdom/spanner/create-population-schema.sql` line 3 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1206#-NfIfHoADhgA0GfUpovF:-NfMYUK98MfgHPmq7LOb:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b988817d15c966a3f7eabd2a0a5f3e4a8b57b644/src/main/resources/kingdom/spanner/create-population-schema.sql#L3)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This should be the year the file was first written
</blockquote></details>

Done.
___
*[`src/main/resources/kingdom/spanner/create-population-schema.sql` line 46 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1206#-NfIfV7G1AE4FGeiYaQa:-NfMYbhR-M6_CItM7QVS:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b988817d15c966a3f7eabd2a0a5f3e4a8b57b644/src/main/resources/kingdom/spanner/create-population-schema.sql#L46)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I don't think this is the right syntax. If I'm reading the docs correctly, you need two separate ALTER TABLE statements.

See https://cloud.google.com/spanner/docs/reference/standard-sql/data-definition-language#alter_table
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-09-27 17:33 UTC, SanjayVas approved these changes
> Reviewed 1 of 2 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1206)* status: all files reviewed, 15 unresolved discussions (waiting on @Marco-Premier and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2023-09-27 17:37 UTC, SanjayVas requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1206)* status: all files reviewed, 16 unresolved discussions (waiting on @jojijac0b, @Marco-Premier, and @stevenwarejones)

___
*[`src/main/resources/kingdom/spanner/create-population-schema.sql` line 44 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1206#-NfMhBgy8tlYEq3-NUJs:-NfMhBgy8tlYEq3-NUJt:b8j5wo0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ad5839f383aeac1276443782bca697706d86625f/src/main/resources/kingdom/spanner/create-population-schema.sql#L44)):*
> ```TSQL
>   INTERLEAVE IN PARENT DataProviders ON DELETE CASCADE;
> 
> ALTER TABLE ModelReleases ADD COLUMN PopulationId INT64; -- population used in model release
> ```

Oh, I see now why you were dropping and re-creating the table: adding non-null columns. Assuming it's incorrect to have any existing ModelRelease without a Population then dropping and re-creating the table is correct. Sorry for the churn.


<!-- Sent from Reviewable.io -->

2023-09-27 21:55 UTC, jojijac0b reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1206)* status: 15 of 16 files reviewed, 16 unresolved discussions (waiting on @Marco-Premier, @SanjayVas, and @stevenwarejones)

___
*[`src/main/resources/kingdom/spanner/create-population-schema.sql` line 44 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1206#-NfMhBgy8tlYEq3-NUJs:-NfNcnTTA2BP4ailoop5:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ad5839f383aeac1276443782bca697706d86625f/src/main/resources/kingdom/spanner/create-population-schema.sql#L44)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Oh, I see now why you were dropping and re-creating the table: adding non-null columns. Assuming it's incorrect to have any existing ModelRelease without a Population then dropping and re-creating the table is correct. Sorry for the churn.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-09-28 00:32 UTC, SanjayVas approved these changes
> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1206)* status: all files reviewed, 15 unresolved discussions (waiting on @Marco-Premier and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2023-09-28 14:58 UTC, Marco-Premier approved these changes
> Reviewed 2 of 7 files at r2, 1 of 5 files at r3, 3 of 7 files at r5, 1 of 1 files at r6, 7 of 9 files at r8, 1 of 2 files at r9, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1206)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)



<!-- Sent from Reviewable.io -->

2023-09-29 14:15 UTC, stevenwarejones approved these changes
> Reviewed 1 of 9 files at r8, 1 of 2 files at r9, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1206)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jojijac0b)



<!-- Sent from Reviewable.io -->

2023-09-29 20:33 UTC, stevenwarejones approved these changes
> Reviewed 5 of 5 files at r12, 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1206)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jojijac0b)



<!-- Sent from Reviewable.io -->

2023-10-02 16:22 UTC, merged