Add Reporting V2 Report Scheduling Protos
world-federation-of-advertisers/cross-media-measurement pull request #1234
Opened 2023-09-20 16:20 UTC by tristanvuong2021

2023-09-20 16:20 UTC, wfa-reviewable commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1234)
<!-- Reviewable:end -->

2023-09-20 17:49 UTC, SanjayVas requested changes
> Reviewed 2 of 12 files at r1, 2 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1234)* status: 4 of 12 files reviewed, 5 unresolved discussions (waiting on @kungfucraig, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/report_schedule.proto` line 74 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1234#-NenfakW4u2X3kYuuVDz:-NenfakW4u2X3kYuuVE-:b-8sr9eg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c8899ecf3af576e7c923a06ba81e64a67aee8547/src/main/proto/wfa/measurement/reporting/v2alpha/report_schedule.proto#L74)):*
> ```proto
>       // then it will be coerced to the end of the month. Cannot be les than 1.
>       //
>       // Required.
> ```

Use the field_behavior annotation instead of a comment here.



_Code quote:_
```proto
// Required.
```
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/report_schedule.proto` line 89 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1234#-NenfrhzC0CBRMXL5VKo:-Nenfri-9C-cNPROM1zy:bxn9y2u) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c8899ecf3af576e7c923a06ba81e64a67aee8547/src/main/proto/wfa/measurement/reporting/v2alpha/report_schedule.proto#L89)):*
> ```proto
>   // Defines the time interval that a `Report` will cover.
>   message ReportWindow {
>     // `count` represents how much of the `increment` to go back.
> ```

Document this on the fields themselves.

Note that to pass the API linter, every type and field needs to be documented.



_Code quote:_
```proto
// `count` represents how much of the `increment` to go back.
```
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/report_schedule_iteration.proto` line 27 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1234#-Neng44u4DTx466bvYLH:-Neng44vCP7LNL3_OVPE:b-i7trm4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c8899ecf3af576e7c923a06ba81e64a67aee8547/src/main/proto/wfa/measurement/reporting/v2alpha/report_schedule_iteration.proto#L27)):*
> ```proto
> 
> // Resource representing the creation of a single `Report` based on a schedule.
> message ReportScheduleIteration {
> ```

I thought we ended up on ScheduledReport in the discussion? I suppose iterations is fine though.



_Code quote:_
```proto
ReportScheduleIteration
```
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/report_schedule_iteration.proto` line 30 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1234#-NengBTT91ZcG2tIHu2e:-NengBTT91ZcG2tIHu2f:bp0qnp0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c8899ecf3af576e7c923a06ba81e64a67aee8547/src/main/proto/wfa/measurement/reporting/v2alpha/report_schedule_iteration.proto#L30)):*
> ```proto
>   option (google.api.resource) = {
>     type: "reporting.halo-cmm.org/ReportScheduleIteration"
>     pattern: "measurementConsumers/{measurement_consumer}/reportSchedules/{report_schedule}/reportScheduleIterations/{report_schedule_iteration}"
> ```

You can shorten the name of nested collections. See https://google.aip.dev/122#collection-identifiers



_Suggestion:_
```proto
iterations
```
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/report_schedule_iteration.proto` line 42 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1234#-Nengjr74QnVH2jv3wKo:-Nengjr74QnVH2jv3wKp:b-xutw9l) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c8899ecf3af576e7c923a06ba81e64a67aee8547/src/main/proto/wfa/measurement/reporting/v2alpha/report_schedule_iteration.proto#L42)):*
> ```proto
>     DATA_NOT_AVAILABLE = 1;
>     // Grpc call failed when attempting `Report` creation.
>     GRPC_FAILURE = 2;
> ```

These sound like error reasons rather than states. See naming guidance on active states in https://google.aip.dev/216#common-states



_Suggestion:_
```proto
    // Data is not yet available for `Report` creation.
    WAITING_FOR_DATA_AVAILABILITY = 1;
    // Grpc call failed when attempting `Report` creation.
    RETRYING_REPORT_CREATION = 2;
```


<!-- Sent from Reviewable.io -->

2023-09-20 18:57 UTC, stevenwarejones requested changes
> Reviewed 3 of 12 files at r1, 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1234)* status: 11 of 12 files reviewed, 12 unresolved discussions (waiting on @kungfucraig and @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/internal/reporting/v2/report_schedule.proto` line 39 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1234#-NentxNP3gIKOJJ73J9F:-NentxNP3gIKOJJ73J9G:bxi0sb1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c8899ecf3af576e7c923a06ba81e64a67aee8547/src/main/proto/wfa/measurement/internal/reporting/v2/report_schedule.proto#L39)):*
> ```proto
> 
>     message Weekly {
>       google.type.DayOfWeek day_of_Week = 1;
> ```

nit: `day_of_week`
___
*[`src/main/proto/wfa/measurement/internal/reporting/v2/report_schedule.proto` line 73 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1234#-NenwrPX7BxfSw4u21bq:-NenwrPX7BxfSw4u21br:bsm6pwa) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c8899ecf3af576e7c923a06ba81e64a67aee8547/src/main/proto/wfa/measurement/internal/reporting/v2/report_schedule.proto#L73)):*
> ```proto
> 
>   enum State {
>     // Default value used if the state is omitted.
> ```

do we need these comments if they are on the external API already?
___
*[`src/main/proto/wfa/measurement/internal/reporting/v2/report_schedule_iteration.proto` line 46 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1234#-NenwuXAA1wT7kFZGh3n:-NenwuXAA1wT7kFZGh3o:bsm6pwa) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c8899ecf3af576e7c923a06ba81e64a67aee8547/src/main/proto/wfa/measurement/internal/reporting/v2/report_schedule_iteration.proto#L46)):*
> ```proto
> 
>   // Only incremented when state transitions to `GRPC_FAILURE` or
>   // `REPORT_CREATED`. Output-only.
> ```

do we need these comments if they are on the external API already?
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/report_schedule.proto` line 66 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1234#-NenusQmBUexDz4AGgwm:-NenusQmBUexDz4AGgwn:b-7ropln) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c8899ecf3af576e7c923a06ba81e64a67aee8547/src/main/proto/wfa/measurement/reporting/v2alpha/report_schedule.proto#L66)):*
> ```proto
> 
>     message Weekly {
>       google.type.DayOfWeek day_of_Week = 1
> ```

ditto
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/report_schedule.proto` line 94 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1234#-NenuvOc21aqClFhFfxV:-NenuvOc21aqClFhFfxW:b51yz3n) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c8899ecf3af576e7c923a06ba81e64a67aee8547/src/main/proto/wfa/measurement/reporting/v2alpha/report_schedule.proto#L94)):*
> ```proto
> 
>       enum Increment {
>         // Default value used if the state is omitted.
> ```

.... Should not be used.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/report_schedule.proto` line 105 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1234#-NenuysPA16g0WGAabUk:-NenuysPA16g0WGAabUl:b-805nf5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c8899ecf3af576e7c923a06ba81e64a67aee8547/src/main/proto/wfa/measurement/reporting/v2alpha/report_schedule.proto#L105)):*
> ```proto
>     // How far back the `Report` covers. Anchored on start hour. Required.
>     oneof window {
>       TrailingWindow trailing_window = 1;
> ```

add a comment for this field as well
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/report_schedule_iteration.proto` line 37 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1234#-Nenv9qMCx-6aFZM7zmH:-Nenv9qMCx-6aFZM7zmI:b-4f3s11) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c8899ecf3af576e7c923a06ba81e64a67aee8547/src/main/proto/wfa/measurement/reporting/v2alpha/report_schedule_iteration.proto#L37)):*
> ```proto
> 
>   enum State {
>     // Default value used if the state is omitted.
> ```

.... Should not be used
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/report_schedule_iteration.proto` line 49 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1234#-NenvRxe6AcOf4oxyOJv:-NenvRxe6AcOf4oxyOJw:bunn0ik) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c8899ecf3af576e7c923a06ba81e64a67aee8547/src/main/proto/wfa/measurement/reporting/v2alpha/report_schedule_iteration.proto#L49)):*
> ```proto
> 
>   // Only incremented when state transitions to `GRPC_FAILURE` or
>   // `REPORT_CREATED`.
> ```

a state of `WAITING_FOR_DATA_AVAILABILITY` does not increment the attempt number.


<!-- Sent from Reviewable.io -->

2023-09-20 20:35 UTC, tristanvuong2021 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1234)* status: 7 of 12 files reviewed, 11 unresolved discussions (waiting on @kungfucraig, @SanjayVas, and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/internal/reporting/v2/report_schedule.proto` line 73 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1234#-NenwrPX7BxfSw4u21bq:-NeoDHmOCVQkmOx8OcXg:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c8899ecf3af576e7c923a06ba81e64a67aee8547/src/main/proto/wfa/measurement/internal/reporting/v2/report_schedule.proto#L73)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

do we need these comments if they are on the external API already?
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/internal/reporting/v2/report_schedule_iteration.proto` line 46 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1234#-NenwuXAA1wT7kFZGh3n:-NeoDIXv5Z1SRlc2ckgg:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c8899ecf3af576e7c923a06ba81e64a67aee8547/src/main/proto/wfa/measurement/internal/reporting/v2/report_schedule_iteration.proto#L46)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

do we need these comments if they are on the external API already?
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/report_schedule.proto` line 66 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1234#-NenusQmBUexDz4AGgwm:-NeoD4ew6TyLsv1pyfuJ:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c8899ecf3af576e7c923a06ba81e64a67aee8547/src/main/proto/wfa/measurement/reporting/v2alpha/report_schedule.proto#L66)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/report_schedule.proto` line 74 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1234#-NenfakW4u2X3kYuuVDz:-NeoDa0nDdYQllB74KaQ:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c8899ecf3af576e7c923a06ba81e64a67aee8547/src/main/proto/wfa/measurement/reporting/v2alpha/report_schedule.proto#L74)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Use the field_behavior annotation instead of a comment here.
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/report_schedule.proto` line 89 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1234#-NenfrhzC0CBRMXL5VKo:-NeoGKVK181n3MywSpi8:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c8899ecf3af576e7c923a06ba81e64a67aee8547/src/main/proto/wfa/measurement/reporting/v2alpha/report_schedule.proto#L89)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Document this on the fields themselves.

Note that to pass the API linter, every type and field needs to be documented.
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/report_schedule.proto` line 94 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1234#-NenuvOc21aqClFhFfxV:-NeoEXxRCJSt5_l94Urh:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c8899ecf3af576e7c923a06ba81e64a67aee8547/src/main/proto/wfa/measurement/reporting/v2alpha/report_schedule.proto#L94)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

.... Should not be used.
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/report_schedule.proto` line 105 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1234#-NenuysPA16g0WGAabUk:-NeoGJKO0eQ-Jfsw2E5T:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c8899ecf3af576e7c923a06ba81e64a67aee8547/src/main/proto/wfa/measurement/reporting/v2alpha/report_schedule.proto#L105)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

add a comment for this field as well
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/report_schedule_iteration.proto` line 30 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1234#-NengBTT91ZcG2tIHu2e:-NeoEwdV-6B3oZRe_MC7:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c8899ecf3af576e7c923a06ba81e64a67aee8547/src/main/proto/wfa/measurement/reporting/v2alpha/report_schedule_iteration.proto#L30)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

You can shorten the name of nested collections. See https://google.aip.dev/122#collection-identifiers
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/report_schedule_iteration.proto` line 37 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1234#-Nenv9qMCx-6aFZM7zmH:-NeoEL_T9WrcDKV1G-4f:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c8899ecf3af576e7c923a06ba81e64a67aee8547/src/main/proto/wfa/measurement/reporting/v2alpha/report_schedule_iteration.proto#L37)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

.... Should not be used
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/report_schedule_iteration.proto` line 42 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1234#-Nengjr74QnVH2jv3wKo:-NeoEG61BNE0QQT0pDfx:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c8899ecf3af576e7c923a06ba81e64a67aee8547/src/main/proto/wfa/measurement/reporting/v2alpha/report_schedule_iteration.proto#L42)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

These sound like error reasons rather than states. See naming guidance on active states in https://google.aip.dev/216#common-states
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/report_schedule_iteration.proto` line 49 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1234#-NenvRxe6AcOf4oxyOJv:-NeoFNVvE8SHc-a4pQtT:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c8899ecf3af576e7c923a06ba81e64a67aee8547/src/main/proto/wfa/measurement/reporting/v2alpha/report_schedule_iteration.proto#L49)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

a state of `WAITING_FOR_DATA_AVAILABILITY` does not increment the attempt number.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-09-20 21:55 UTC, stevenwarejones approved these changes
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1234)* status: all files reviewed, 4 unresolved discussions (waiting on @kungfucraig and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/internal/reporting/v2/report_schedule_iteration.proto` line 46 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1234#-NenwuXAA1wT7kFZGh3n:-Neo_Oh_Bzd-CtUgsZ5E:b-85wfd9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c8899ecf3af576e7c923a06ba81e64a67aee8547/src/main/proto/wfa/measurement/internal/reporting/v2/report_schedule_iteration.proto#L46)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

not seeing this change


<!-- Sent from Reviewable.io -->

2023-09-20 22:00 UTC, stevenwarejones requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1234)* status: all files reviewed, 6 unresolved discussions (waiting on @kungfucraig, @SanjayVas, and @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/report_schedule_iteration.proto` line 46 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1234#-Neoa_6K4edj7O64c62B:-Neoa_6K4edj7O64c62C:b4rnh2u) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a340e9ad93e6655c0ad9cd5552ceea976858c843/src/main/proto/wfa/measurement/reporting/v2alpha/report_schedule_iteration.proto#L46)):*
> ```proto
>     REPORT_CREATED = 3;
>   }
>   State state = 2;
> ```

should be output only


<!-- Sent from Reviewable.io -->

2023-09-20 22:13 UTC, tristanvuong2021 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1234)* status: 9 of 12 files reviewed, 6 unresolved discussions (waiting on @kungfucraig, @SanjayVas, and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/internal/reporting/v2/report_schedule_iteration.proto` line 46 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1234#-NenwuXAA1wT7kFZGh3n:-NeocKsD56ryRUIg1v4k:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c8899ecf3af576e7c923a06ba81e64a67aee8547/src/main/proto/wfa/measurement/internal/reporting/v2/report_schedule_iteration.proto#L46)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

not seeing this change
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/report_schedule_iteration.proto` line 46 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1234#-Neoa_6K4edj7O64c62B:-NeodW2X-AbZyGCB3PXM:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a340e9ad93e6655c0ad9cd5552ceea976858c843/src/main/proto/wfa/measurement/reporting/v2alpha/report_schedule_iteration.proto#L46)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

should be output only
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-09-21 13:33 UTC, stevenwarejones approved these changes
> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1234)* status: 10 of 12 files reviewed, 4 unresolved discussions (waiting on @kungfucraig and @SanjayVas)



<!-- Sent from Reviewable.io -->

2023-09-21 16:22 UTC, tristanvuong2021 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1234)* status: 6 of 12 files reviewed, 14 unresolved discussions (waiting on @kungfucraig, @SanjayVas, and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/report.proto` line 110 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1234#-NesJNsO3jFMQtSkyxU-:-NesYAf66RQ4xFQUsZ7v:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f946de151ce9a1df6b2e2ba0a523ac2c4a98d852/src/main/proto/wfa/measurement/reporting/v2alpha/report.proto#L110)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

This comment is a bit mysterious. Maybe it should explicitly say that this field is not required if the report is being used as a schedule template?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-09-21 16:48 UTC, stevenwarejones approved these changes
> Reviewed 1 of 2 files at r5, 1 of 1 files at r6, 5 of 5 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1234)* status: all files reviewed, 14 unresolved discussions (waiting on @kungfucraig, @SanjayVas, and @tristanvuong2021)



<!-- Sent from Reviewable.io -->

2023-09-21 17:05 UTC, kungfucraig requested changes
> Reviewed 1 of 1 files at r6, 5 of 5 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1234)* status: all files reviewed, 6 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/internal/reporting/v2/report_schedule_iterations_service.proto` line 61 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1234#-NesgMF-C1IiVVgo4JYF:-NesgMF04tSo1ijqfyTF:b-5zhujw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/71af98ab29d5a0f46c6bc621bf84501519214a56/src/main/proto/wfa/measurement/internal/reporting/v2/report_schedule_iterations_service.proto#L61)):*
> ```proto
>     string cmms_measurement_consumer_id = 1;
>     string external_report_schedule_id = 2;
>     // Skips to results with a `report_creation_time` less than this.
> ```

This is used when checking for a ready report? If so maybe used modified time vs. creation time?


<!-- Sent from Reviewable.io -->

2023-09-21 19:56 UTC, SanjayVas requested changes
> Reviewed 1 of 2 files at r5, 2 of 5 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1234)* status: all files reviewed, 7 unresolved discussions (waiting on @stevenwarejones and @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/report_schedule.proto` line 102 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1234#-NesJbj-6X7KV4eM3j8p:-NetDwIoCydX_OmwPJ58:bocmzte) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f946de151ce9a1df6b2e2ba0a523ac2c4a98d852/src/main/proto/wfa/measurement/reporting/v2alpha/report_schedule.proto#L102)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

I think there is a case to be made that window is optional and defaults to the frequency if unspecified.

@SanjayVas @stevenwarejones WDYT?
</blockquote></details>

I think I prefer to be explicit even if it results in some minor duplication in the case where the window happens to be the same duration as the duration between iterations.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/report_schedule.proto` line 139 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1234#-NetFzcX1dmqhOc_FiT0:-NetFzcX1dmqhOc_FiT1:b1up4nb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/71af98ab29d5a0f46c6bc621bf84501519214a56/src/main/proto/wfa/measurement/reporting/v2alpha/report_schedule.proto#L139)):*
> ```proto
>       [(google.api.field_behavior) = OUTPUT_ONLY];
>   // When the state of this `ReportSchedule` transitioned to `STOPPED`.
>   google.protobuf.Timestamp stop_time = 13
> ```

Stopped is a terminal state. Therefore we don't need a separate timestamp, as update_time cannot be changed after the state is transitioned to STOPPED.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/report_schedule_iteration.proto` line 47 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1234#-NetGVg_EVJFsTW783__:-NetGVga767bDZ0dwDKs:bnvir2u) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/71af98ab29d5a0f46c6bc621bf84501519214a56/src/main/proto/wfa/measurement/reporting/v2alpha/report_schedule_iteration.proto#L47)):*
> ```proto
>     REPORT_CREATED = 3;
>     // `Report` is in a terminal state. Terminal state.
>     REPORT_READY = 4;
> ```

nit: The comment says the report is in a terminal state, but this is saying READY. Maybe COMPLETE would be more accurate?



_Code quote:_
```proto
    // `Report` is in a terminal state. Terminal state.
    REPORT_READY = 4;
```
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/report_schedule_iteration.proto` line 47 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1234#-NetGuO-5kUTBu5tdnE9:-NetGuO-5kUTBu5tdnEA:b-6x7phk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/71af98ab29d5a0f46c6bc621bf84501519214a56/src/main/proto/wfa/measurement/reporting/v2alpha/report_schedule_iteration.proto#L47)):*
> ```proto
>     REPORT_CREATED = 3;
>     // `Report` is in a terminal state. Terminal state.
>     REPORT_READY = 4;
> ```

Do we need to track this state here? I would think just having REPORT_CREATED be the terminal state would be sufficient rather than having to sync this state with the Report state.



_Code quote:_
```proto
REPORT_READY
```
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/report_schedule_iteration.proto` line 57 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1234#-NetHXiH1kdQjs3_ahi_:-NetHXiH1kdQjs3_ahia:b-vqn5px) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/71af98ab29d5a0f46c6bc621bf84501519214a56/src/main/proto/wfa/measurement/reporting/v2alpha/report_schedule_iteration.proto#L57)):*
> ```proto
> 
>   // Only set when state is `REPORT_CREATED`.
>   string report_name = 4 [(google.api.field_behavior) = OUTPUT_ONLY];
> ```

This should just be `report`. See https://google.aip.dev/122#fields-representing-another-resource



_Suggestion:_
```proto
report
```
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/report_schedule_iteration.proto` line 61 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1234#-NetIDu4ElpI4z2zZ6pd:-NetIDu4ElpI4z2zZ6pe:bvsod36) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/71af98ab29d5a0f46c6bc621bf84501519214a56/src/main/proto/wfa/measurement/reporting/v2alpha/report_schedule_iteration.proto#L61)):*
> ```proto
>   // Scheduled time for `Report` creation for this iteration.
>   google.protobuf.Timestamp report_creation_time = 5
>       [(google.api.field_behavior) = OUTPUT_ONLY];
> ```

I think what you actually want to capture here is the "event" time for the iteration, i.e. the end of the final time interval covered in the Report.



_Code quote:_
```proto
  // Scheduled time for `Report` creation for this iteration.
  google.protobuf.Timestamp report_creation_time = 5
      [(google.api.field_behavior) = OUTPUT_ONLY];
```


<!-- Sent from Reviewable.io -->

2023-09-21 20:18 UTC, tristanvuong2021 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1234)* status: 6 of 12 files reviewed, 6 unresolved discussions (waiting on @kungfucraig, @SanjayVas, and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/internal/reporting/v2/report_schedule_iterations_service.proto` line 61 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1234#-NesgMF-C1IiVVgo4JYF:-NetNYDE08ZkZRHmAbgV:bnafwg1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/71af98ab29d5a0f46c6bc621bf84501519214a56/src/main/proto/wfa/measurement/internal/reporting/v2/report_schedule_iterations_service.proto#L61)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

This is used when checking for a ready report? If so maybe used modified time vs. creation time?
</blockquote></details>

I renamed the field so it is more clear. It is meant to be from newest to oldest based on the scheduling order.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/report_schedule.proto` line 139 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1234#-NetFzcX1dmqhOc_FiT0:-NetMtrxAggIcPqAh_K-:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/71af98ab29d5a0f46c6bc621bf84501519214a56/src/main/proto/wfa/measurement/reporting/v2alpha/report_schedule.proto#L139)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Stopped is a terminal state. Therefore we don't need a separate timestamp, as update_time cannot be changed after the state is transitioned to STOPPED.
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/report_schedule_iteration.proto` line 47 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1234#-NetGuO-5kUTBu5tdnE9:-NetN-A48oOqUy82-Zmb:b-7q6b84) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/71af98ab29d5a0f46c6bc621bf84501519214a56/src/main/proto/wfa/measurement/reporting/v2alpha/report_schedule_iteration.proto#L47)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Do we need to track this state here? I would think just having REPORT_CREATED be the terminal state would be sufficient rather than having to sync this state with the Report state.
</blockquote></details>

It wouldn't be needed. Could just check the report state directly once the report is available.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/report_schedule_iteration.proto` line 57 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1234#-NetHXiH1kdQjs3_ahi_:-NetN6XS-oEpbionFFju:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/71af98ab29d5a0f46c6bc621bf84501519214a56/src/main/proto/wfa/measurement/reporting/v2alpha/report_schedule_iteration.proto#L57)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This should just be `report`. See https://google.aip.dev/122#fields-representing-another-resource
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/report_schedule_iteration.proto` line 61 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1234#-NetIDu4ElpI4z2zZ6pd:-NetNWhW0UUnI0pxhLId:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/71af98ab29d5a0f46c6bc621bf84501519214a56/src/main/proto/wfa/measurement/reporting/v2alpha/report_schedule_iteration.proto#L61)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I think what you actually want to capture here is the "event" time for the iteration, i.e. the end of the final time interval covered in the Report.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-09-21 21:34 UTC, kungfucraig approved these changes
> Reviewed 6 of 6 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1234)* status: all files reviewed, 5 unresolved discussions (waiting on @SanjayVas and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/report_schedule.proto` line 102 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1234#-NesJbj-6X7KV4eM3j8p:-NeteWrv7cOy8lm9tNwN:b32wwp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f946de151ce9a1df6b2e2ba0a523ac2c4a98d852/src/main/proto/wfa/measurement/reporting/v2alpha/report_schedule.proto#L102)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I think I prefer to be explicit even if it results in some minor duplication in the case where the window happens to be the same duration as the duration between iterations.
</blockquote></details>

sg


<!-- Sent from Reviewable.io -->

2023-09-21 22:37 UTC, tristanvuong2021 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1234)* status: all files reviewed, 5 unresolved discussions (waiting on @SanjayVas and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/report_schedule.proto` line 102 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1234#-NesJbj-6X7KV4eM3j8p:-NetszDD-lX3JUB80h5B:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f946de151ce9a1df6b2e2ba0a523ac2c4a98d852/src/main/proto/wfa/measurement/reporting/v2alpha/report_schedule.proto#L102)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

sg
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-09-22 14:53 UTC, kungfucraig approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1234)* status: all files reviewed, 4 unresolved discussions (waiting on @SanjayVas and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2023-09-25 17:52 UTC, SanjayVas requested changes
> Reviewed 1 of 12 files at r1, 1 of 8 files at r2, 1 of 3 files at r4, 1 of 5 files at r7, 1 of 1 files at r8, 5 of 6 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1234)* status: 11 of 12 files reviewed, 1 unresolved discussion (waiting on @kungfucraig, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/reports_service.proto` line 44 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1234#-NfCSQpu8Jgc4slFu3D1:-NfCSQpv4ie3gnVIFfY5:b-9wmzjk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/39009125ab842a3a69f34af255ae0c7d97582885/src/main/proto/wfa/measurement/reporting/v2alpha/reports_service.proto#L44)):*
> ```proto
>       get: "/v2alpha/{parent=measurementConsumers/*}/reports"
>       additional_bindings {
>         get: "/v2alpha/{parent=measurementConsumers/*/reportSchedules/*}/reports"
> ```

I take it this is for listing Reports created by a given ReportSchedule? If you want to do it this way, I believe you also need to add this pattern to the Report resource.

The alternative is to have an optional `report_schedule` field on `Report` that indicates which schedule (if any) it was created from. Then one can just specify that field in the request filter.


<!-- Sent from Reviewable.io -->

2023-09-25 20:33 UTC, tristanvuong2021 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1234)* status: 9 of 13 files reviewed, 1 unresolved discussion (waiting on @kungfucraig, @SanjayVas, and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/reports_service.proto` line 44 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1234#-NfCSQpu8Jgc4slFu3D1:-NfD1z0GDeE1I-UqjAFJ:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/39009125ab842a3a69f34af255ae0c7d97582885/src/main/proto/wfa/measurement/reporting/v2alpha/reports_service.proto#L44)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I take it this is for listing Reports created by a given ReportSchedule? If you want to do it this way, I believe you also need to add this pattern to the Report resource.

The alternative is to have an optional `report_schedule` field on `Report` that indicates which schedule (if any) it was created from. Then one can just specify that field in the request filter.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-09-25 23:16 UTC, SanjayVas approved these changes
> Reviewed 1 of 1 files at r10, 4 of 4 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1234)* status: all files reviewed, 1 unresolved discussion (waiting on @kungfucraig, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/internal/reporting/v2/report_schedule.proto` line 80 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1234#-NfDbqsU4bApyvpchhvm:-NfDbqsU4bApyvpchhvn:b-37awzh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ca826347f567d2039c1e317a56da068d90a1b8d7/src/main/proto/wfa/measurement/internal/reporting/v2/report_schedule.proto#L80)):*
> ```proto
> 
>   message Details {
>     string display_name = 1;
> ```

nit: while this is technically okay as we indicated that DB changes might be coming in the release notes, it would be safer not to unnecessarily make incompatible changes to a message type that is persisted


<!-- Sent from Reviewable.io -->

2023-09-25 23:47 UTC, tristanvuong2021 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1234)* status: all files reviewed, 1 unresolved discussion (waiting on @kungfucraig, @SanjayVas, and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/internal/reporting/v2/report_schedule.proto` line 80 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1234#-NfDbqsU4bApyvpchhvm:-NfDiqntAGZcfkbj1t1n:b-9bms26) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ca826347f567d2039c1e317a56da068d90a1b8d7/src/main/proto/wfa/measurement/internal/reporting/v2/report_schedule.proto#L80)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: while this is technically okay as we indicated that DB changes might be coming in the release notes, it would be safer not to unnecessarily make incompatible changes to a message type that is persisted
</blockquote></details>

In this case, the tables for report scheduling don't exist yet.


<!-- Sent from Reviewable.io -->

2023-09-25 23:49 UTC, merged