Restrict metric set operations based on metric types
world-federation-of-advertisers/cross-media-measurement pull request #1247
Opened 2023-09-22 05:06 UTC by riemanli

2023-09-22 05:06 UTC, wfa-reviewable commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1247)
<!-- Reviewable:end -->

2023-09-22 05:06 UTC, riemanli commented
Current dependencies on/for this PR:
* main
  * **PR #1226** <a href="https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/1226" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #1233** <a href="https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/1233" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #1184** <a href="https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/1184" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #1247** <a href="https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/1247" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/1247?utm_source=stack-comment).

2023-09-22 18:33 UTC, tristanvuong2021 approved these changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1247)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @riemanli)



<!-- Sent from Reviewable.io -->

2023-09-22 18:44 UTC, tristanvuong2021 approved these changes

2023-09-25 17:42 UTC, SanjayVas requested changes
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1247)* status: all files reviewed, 1 unresolved discussion (waiting on @riemanli)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1247#-NfCQ_wZ4Cw64y7x2RjO:-NfCQ_wZ4Cw64y7x2RjP:bxsvo8j) (no related file):*
Why a logged warning (which only Reporting service operators will see)? Shouldn't this be an error in Metric creation, or is there some value in getting a result despite the inaccuracy?

___


<!-- Sent from Reviewable.io -->

2023-09-25 17:56 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1247)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1247#-NfCQ_wZ4Cw64y7x2RjO:-NfCSEXFEhsaqLZUYVu2:bxb3u15) (no related file):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Why a logged warning (which only Reporting service operators will see)? Shouldn't this be an error in Metric creation, or is there some value in getting a result despite the inaccuracy?
</blockquote></details>

For Frequency Histogram, the result accuracy is not guaranteed if the operation is other than union, so I think it makes sense to raise an error. For Impression Count and Watch Duration, their metric values are correct. It's just that we don't support the variances when operations are not union-only. I can modify the documentation to make this more clear. As for the warning, is there a way to let the user see the stdout warning?

___


<!-- Sent from Reviewable.io -->

2023-09-25 18:22 UTC, SanjayVas requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1247)* status: all files reviewed, 1 unresolved discussion (waiting on @riemanli)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1247#-NfCQ_wZ4Cw64y7x2RjO:-NfCYdEw8PqY7u82lGC_:b-yj26cx) (no related file):*
> For Impression Count and Watch Duration, their metric values are correct. It's just that we don't support the variances when operations are not union-only.

Maybe just document this on the variance output fields then?

> As for the warning, is there a way to let the user see the stdout warning?

An API user can only see the API output, which is either a successful response message or an error status.

___


<!-- Sent from Reviewable.io -->

2023-09-25 22:38 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1247)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @tristanvuong2021)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1247#-NfCQ_wZ4Cw64y7x2RjO:-NfDThoMECwJEHns38mI:bs7wumx) (no related file):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> For Impression Count and Watch Duration, their metric values are correct. It's just that we don't support the variances when operations are not union-only.

Maybe just document this on the variance output fields then?

> As for the warning, is there a way to let the user see the stdout warning?

An API user can only see the API output, which is either a successful response message or an error status.
</blockquote></details>

Done. 

___


<!-- Sent from Reviewable.io -->

2023-09-25 23:29 UTC, SanjayVas approved these changes
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1247)* status: all files reviewed, 2 unresolved discussions (waiting on @riemanli)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 1400 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1247#-NfDd_K88maVWeTWKRXI:-NfDd_K88maVWeTWKRXJ:b29fpf4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6fb319f3ab2bae9a2f6f5b935fea221e08db4366/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L1400)):*
> ```Kotlin
>   companion object {
>     private val RESOURCE_ID_REGEX = Regex("^[a-z]([a-z0-9-]{0,61}[a-z0-9])?$")
>     private val logger: Logger = Logger.getLogger(this::class.java.name)
> ```

nit: unused
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto` line 204 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1247#-NfDe8n_5Ia77nHMg0Ea:-NfDe8n_5Ia77nHMg0Eb:b5rnxwc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6fb319f3ab2bae9a2f6f5b935fea221e08db4366/src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto#L204)):*
> ```proto
>     // Univariate statistics of the impression value above.
>     //
>     // If any CMMS impression measurements used in the metric don't have noise
> ```

nit: can probably simplify this by saying "Only set when all of the set operations for the result are unions and all source`Measurement`s contain sufficient information to calculate univariate statistics."


<!-- Sent from Reviewable.io -->

2023-09-25 23:47 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1247)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 1400 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1247#-NfDd_K88maVWeTWKRXI:-NfDilHPCu9nDCsYLmFE:b8ykr3y) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6fb319f3ab2bae9a2f6f5b935fea221e08db4366/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L1400)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: unused
</blockquote></details>

Thanks for pointing it out. Removed.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto` line 204 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1247#-NfDe8n_5Ia77nHMg0Ea:-NfDjD_u378K8kqQESPJ:b-22mamj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6fb319f3ab2bae9a2f6f5b935fea221e08db4366/src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto#L204)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: can probably simplify this by saying "Only set when all of the set operations for the result are unions and all source`Measurement`s contain sufficient information to calculate univariate statistics."
</blockquote></details>

Thanks for the suggestion! Fixed.


<!-- Sent from Reviewable.io -->

2023-09-26 00:10 UTC, SanjayVas approved these changes
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1247)* status: all files reviewed, 1 unresolved discussion (waiting on @Marco-Premier and @riemanli)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto` line 204 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1247#-NfDe8n_5Ia77nHMg0Ea:-NfDoT9S0lC0kB9IdZy6:b-wajnp5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6fb319f3ab2bae9a2f6f5b935fea221e08db4366/src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto#L204)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Thanks for the suggestion! Fixed.
</blockquote></details>

Can use similar phrasing (without the restriction on set operations) for the stats fields in other result types.


<!-- Sent from Reviewable.io -->

2023-09-26 04:03 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1247)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @Marco-Premier and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto` line 204 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1247#-NfDe8n_5Ia77nHMg0Ea:-NfEUnt5-GhQNU0OXivJ:b-896fja) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6fb319f3ab2bae9a2f6f5b935fea221e08db4366/src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto#L204)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Can use similar phrasing (without the restriction on set operations) for the stats fields in other result types.
</blockquote></details>

Done!


<!-- Sent from Reviewable.io -->

2023-09-26 15:56 UTC, Marco-Premier approved these changes
> Reviewed 1 of 3 files at r2, 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1247)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)



<!-- Sent from Reviewable.io -->

2023-09-26 19:34 UTC, merged