Added an event filter field to MetricCalculationSpec.
world-federation-of-advertisers/cross-media-measurement pull request #1250
Opened 2023-09-25 17:23 UTC by kungfucraig

Allow for an event filter on MetricCalculationSpec in order to allow ReportingSets to be used without filters. This is in response to a request from @mariolamassaavedra.

2023-09-25 17:23 UTC, wfa-reviewable commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1250)
<!-- Reviewable:end -->

2023-09-25 17:32 UTC, riemanli approved these changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1250)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)



<!-- Sent from Reviewable.io -->

2023-09-25 23:32 UTC, SanjayVas requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1250)* status: all files reviewed, 1 unresolved discussion (waiting on @kungfucraig and @Marco-Premier)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/report.proto` line 70 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1250#-NfDfxcY4E2eVt3_r8fR:-NfDfxcY4E2eVt3_r8fS:b-zbxpzb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9887c826a310362e22141c95f84aacb0b31fab9e/src/main/proto/wfa/measurement/reporting/v2alpha/report.proto#L70)):*
> ```proto
>     // present on the ReportingSet provided as part of the
>     // ReportingMetricEntry below.
>     string filter = 5;
> ```

Add IMMUTABLE field behavior annotation.


<!-- Sent from Reviewable.io -->

2023-09-25 23:33 UTC, SanjayVas reviewed
nit: PR description should be an imperative sentence. See https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/docs/dev-standards.md#pull-request-description

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1250#-:-NfDgEnRDFYd1XdDTl0y:bfkip48)* status: all files reviewed, 1 unresolved discussion (waiting on @kungfucraig and @Marco-Premier)



<!-- Sent from Reviewable.io -->

2023-09-26 21:27 UTC, kungfucraig reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1250)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @Marco-Premier, @riemanli, and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/report.proto` line 70 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1250#-NfDfxcY4E2eVt3_r8fR:-NfIO1tkExZCOpYkJRnO:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9887c826a310362e22141c95f84aacb0b31fab9e/src/main/proto/wfa/measurement/reporting/v2alpha/report.proto#L70)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Add IMMUTABLE field behavior annotation.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-09-27 00:20 UTC, SanjayVas approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1250)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Marco-Premier)



<!-- Sent from Reviewable.io -->

2023-09-27 16:24 UTC, Marco-Premier approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1250)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kungfucraig)



<!-- Sent from Reviewable.io -->

2023-09-27 20:16 UTC, merged