Added tags, which are a map of key value pairs of strings, to report and reporting set.
world-federation-of-advertisers/cross-media-measurement pull request #1251
Opened 2023-09-25 17:34 UTC by kungfucraig

Tags are intended to help UIs and other rich clients make connections between display artifacts and reporting artifacts without having to write code to interpret the structure of reports or reporting sets.

2023-09-25 17:34 UTC, wfa-reviewable commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1251)
<!-- Reviewable:end -->

2023-09-25 18:15 UTC, riemanli requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1251)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @kungfucraig and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/report.proto` line 48 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1251#-NfCXvP61ommnXIkl0Qn:-NfCXvP61ommnXIkl0Qo:b-pfmfu9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/df6f6a5fb95b543be6757fa6ee1c1ba317218053/src/main/proto/wfa/measurement/reporting/v2alpha/report.proto#L48)):*
> ```proto
>   // A map of arbitrary key-value pairs to support tagging of Reports
>   // for upstream use by UIs and other rich clients.
>   map<string, string> tags = 8;
> ```

We used this [map format](https://protobuf.dev/programming-guides/proto3/#backwards) before for backwards compatibility. Should we still do it or it's ok to use `Map`?  cc @SanjayVas 


<!-- Sent from Reviewable.io -->

2023-09-25 23:37 UTC, SanjayVas requested changes
nit: PR description should be an imperative sentence. See https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/docs/dev-standards.md#pull-request-description

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1251#-:-NfDgLfEDt2yetlfjAf-:bfkip48)* status: all files reviewed, 3 unresolved discussions (waiting on @kungfucraig, @Marco-Premier, and @riemanli)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/report.proto` line 48 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1251#-NfCXvP61ommnXIkl0Qn:-NfDgOC901WxTJATjqeI:bnhhfkl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/df6f6a5fb95b543be6757fa6ee1c1ba317218053/src/main/proto/wfa/measurement/reporting/v2alpha/report.proto#L48)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

We used this [map format](https://protobuf.dev/programming-guides/proto3/#backwards) before for backwards compatibility. Should we still do it or it's ok to use `Map`?  cc @SanjayVas
</blockquote></details>

We only use that for cases where it's necessary, e.g. to add a protobuf annotation to the key field. We should use the native map type instead whenever possible.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/report.proto` line 48 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1251#-NfDgb2A1NfTygeiFUA_:-NfDgb2A1NfTygeiFUAa:byl025w) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/df6f6a5fb95b543be6757fa6ee1c1ba317218053/src/main/proto/wfa/measurement/reporting/v2alpha/report.proto#L48)):*
> ```proto
>   // A map of arbitrary key-value pairs to support tagging of Reports
>   // for upstream use by UIs and other rich clients.
>   map<string, string> tags = 8;
> ```

Add IMMUTABLE field behavior.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/reporting_set.proto` line 41 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1251#-NfDgh4NBVgfIMon3lZ6:-NfDgh4NBVgfIMon3lZ7:b-s070t3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/df6f6a5fb95b543be6757fa6ee1c1ba317218053/src/main/proto/wfa/measurement/reporting/v2alpha/reporting_set.proto#L41)):*
> ```proto
>   // A map of arbitrary key-value pairs to support tagging of ReportingSets
>   // for upstream use by UIs and other rich clients.
>   map<string, string> tags = 8;
> ```

Add IMMUTABLE field behavior. Note that `ReportingSet`s are inherently immutable after creation, but it's still better to explicitly annotate.


<!-- Sent from Reviewable.io -->

2023-09-26 21:25 UTC, kungfucraig reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1251)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @Marco-Premier, @riemanli, and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/report.proto` line 48 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1251#-NfDgb2A1NfTygeiFUA_:-NfGyF6k3TUae6nVu8dP:bntms41) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/df6f6a5fb95b543be6757fa6ee1c1ba317218053/src/main/proto/wfa/measurement/reporting/v2alpha/report.proto#L48)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Add IMMUTABLE field behavior.
</blockquote></details>

I'm not sure I agree with this field being immutable, but I suppose we can relax the constraint if it ever becomes an issue.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/reporting_set.proto` line 41 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1251#-NfDgh4NBVgfIMon3lZ6:-NfGyXpF4LE6L8GKT8c_:b2nreh6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/df6f6a5fb95b543be6757fa6ee1c1ba317218053/src/main/proto/wfa/measurement/reporting/v2alpha/reporting_set.proto#L41)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Add IMMUTABLE field behavior. Note that `ReportingSet`s are inherently immutable after creation, but it's still better to explicitly annotate.
</blockquote></details>

Same as above.


<!-- Sent from Reviewable.io -->

2023-09-26 22:51 UTC, riemanli approved these changes
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1251)* status: all files reviewed, 2 unresolved discussions (waiting on @Marco-Premier and @SanjayVas)



<!-- Sent from Reviewable.io -->

2023-09-27 00:22 UTC, SanjayVas approved these changes
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1251)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Marco-Premier)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/report.proto` line 48 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1251#-NfDgb2A1NfTygeiFUA_:-NfJ-fA8394LoFxVGVNt:b-rv1rc3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/df6f6a5fb95b543be6757fa6ee1c1ba317218053/src/main/proto/wfa/measurement/reporting/v2alpha/report.proto#L48)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

I'm not sure I agree with this field being immutable, but I suppose we can relax the constraint if it ever becomes an issue.
</blockquote></details>

Our current design is that Reports cannot be changed by the user after creation. We can indeed relax that later if we want to change that design decision.


<!-- Sent from Reviewable.io -->

2023-09-27 16:24 UTC, Marco-Premier approved these changes
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1251)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kungfucraig)



<!-- Sent from Reviewable.io -->

2023-09-27 22:59 UTC, merged