Add metric variance calculations
world-federation-of-advertisers/cross-media-measurement pull request #1253
Opened 2023-09-26 05:18 UTC by riemanli

2023-09-26 05:18 UTC, wfa-reviewable commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1253)
<!-- Reviewable:end -->

2023-09-26 05:18 UTC, riemanli commented
Current dependencies on/for this PR:
* main
  * **PR #1226** <a href="https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/1226" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #1233** <a href="https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/1233" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #1184** <a href="https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/1184" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #1247** <a href="https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/1247" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
        * **PR #1252** <a href="https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/1252" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
          * **PR #1253** <a href="https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/1253" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/1253?utm_source=stack-comment).

2023-09-29 17:08 UTC, jiayu-google approved these changes
I confirm that the formula implementation and test results are correct. Thank you Rieman.

> Reviewed 8 of 8 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1253#-:-NfWuJ4B8utzC1LIHyoK:b-5r7kpq)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kungfucraig)



<!-- Sent from Reviewable.io -->

2023-10-03 20:01 UTC, SanjayVas requested changes
> Reviewed 2 of 8 files at r2, 1 of 3 files at r3, 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1253)* status: all files reviewed, 6 unresolved discussions (waiting on @riemanli)

___
*[`src/main/kotlin/org/wfanet/measurement/measurementconsumer/stats/Covariances.kt` line 22 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1253#-Nfr0xAw96-9epqhLnEk:-Nfr0xAw96-9epqhLnEl:b-49to3e) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1e532eebb9a35e665edfcc1a5e6d0210f752fd9e/src/main/kotlin/org/wfanet/measurement/measurementconsumer/stats/Covariances.kt#L22)):*
> ```Kotlin
> import kotlin.math.min
> 
> class MeasurementSketchParamsNotMatchException(message: String? = null, cause: Throwable? = null) :
> ```

If this exception is only used by the Covariances object, put it inside that object. If it's used by other symbols in this package, move it to a separate file.
___
*[`src/main/kotlin/org/wfanet/measurement/measurementconsumer/stats/MetricStatistics.kt` line 19 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1253#-Nfr2V6I8rLGgkSAvlXd:-Nfr2V6I8rLGgkSAvlXe:bpbo540) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1e532eebb9a35e665edfcc1a5e6d0210f752fd9e/src/main/kotlin/org/wfanet/measurement/measurementconsumer/stats/MetricStatistics.kt#L19)):*
> ```Kotlin
> package org.wfanet.measurement.measurementconsumer.stats
> 
> sealed interface BaseMethodology
> ```

Drop the unnecessary "base" prefix everywhere.



_Suggestion:_
```Kotlin
Methodology
```
___
*[`src/main/kotlin/org/wfanet/measurement/measurementconsumer/stats/Variances.kt` line 28 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1253#-Nfr36fZ68ccFB3mmk82:-Nfr36fZ68ccFB3mmk83:b3tamdz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1e532eebb9a35e665edfcc1a5e6d0210f752fd9e/src/main/kotlin/org/wfanet/measurement/measurementconsumer/stats/Variances.kt#L28)):*
> ```Kotlin
> import org.wfanet.measurement.eventdataprovider.privacybudgetmanagement.AcdpParamsConverter
> 
> class UnsupportedMethodologyException(message: String? = null, cause: Throwable? = null) :
> ```

Same note here re: where to define the exception.
___
*[`src/main/kotlin/org/wfanet/measurement/measurementconsumer/stats/Variances.kt` line 437 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1253#-Nfr4LFiBqeUauZIMTad:-Nfr4LFiBqeUauZIMTae:by9at2e) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1e532eebb9a35e665edfcc1a5e6d0210f752fd9e/src/main/kotlin/org/wfanet/measurement/measurementconsumer/stats/Variances.kt#L437)):*
> ```Kotlin
>     if (params.totalReach < 0.0) {
>       throw IllegalArgumentException("The total reach value cannot be negative.")
>     }
> ```

nit: use precondition functions



_Suggestion:_
```Kotlin
    require(params.totalReach >= 0.0) {
      "The total reach value cannot be negative."
    }
```
___
*[`src/test/kotlin/org/wfanet/measurement/measurementconsumer/stats/VariancesTest.kt` line 21 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1253#-Nfr5rhe6fZfM-szz94-:-Nfr5rhe6fZfM-szz940:bp43jv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1e532eebb9a35e665edfcc1a5e6d0210f752fd9e/src/test/kotlin/org/wfanet/measurement/measurementconsumer/stats/VariancesTest.kt#L21)):*
> ```Kotlin
> import com.google.common.truth.Truth.assertThat
> import kotlin.math.abs
> import org.junit.Assert.assertThrows
> ```

Use `kotlin.test.assertFailsWith` instead for tests written in Kotlin



_Code quote:_
```Kotlin
import org.junit.Assert.assertThrows
```
___
*[`src/test/kotlin/org/wfanet/measurement/measurementconsumer/stats/VariancesTest.kt` line 2925 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1253#-Nfr66NAEXVBa-6BWh_m:-Nfr66NBEI6VJbVMylPL:b-o58vay) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1e532eebb9a35e665edfcc1a5e6d0210f752fd9e/src/test/kotlin/org/wfanet/measurement/measurementconsumer/stats/VariancesTest.kt#L2925)):*
> ```Kotlin
>     val expect = 19836.523148381533
>     val percentageError = percentageError(variance, expect)
>     assertThat(percentageError).isLessThan(ERROR_TOLERANCE)
> ```

nit: write this using built-in support in Truth for floating point tolerances (e.g. `assertThat(actual).isWithin(tolerance).of(expected)` or add a custom subject (e.g. [FuzzyLongSubject](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/main/kotlin/org/wfanet/measurement/api/v2alpha/testing/FuzzyLongSubject.kt)). Making this change will result in clearer error messages, as opposed to something like "Expected 0.006 is less than 0.005"



_Code quote:_
```Kotlin
    val percentageError = percentageError(variance, expect)
    assertThat(percentageError).isLessThan(ERROR_TOLERANCE)
```


<!-- Sent from Reviewable.io -->

2023-10-04 00:11 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1253)* status: 5 of 11 files reviewed, 5 unresolved discussions (waiting on @jiayu-google and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/measurementconsumer/stats/Covariances.kt` line 22 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1253#-Nfr0xAw96-9epqhLnEk:-NfrsRcZA9yR5-8G7liI:b-gky0dk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1e532eebb9a35e665edfcc1a5e6d0210f752fd9e/src/main/kotlin/org/wfanet/measurement/measurementconsumer/stats/Covariances.kt#L22)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

If this exception is only used by the Covariances object, put it inside that object. If it's used by other symbols in this package, move it to a separate file.
</blockquote></details>

Removed this exception and use `IllegalArgumentException` instead.
___
*[`src/main/kotlin/org/wfanet/measurement/measurementconsumer/stats/MetricStatistics.kt` line 19 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1253#-Nfr2V6I8rLGgkSAvlXd:-NfrKYMs2D3wzbjPiSCb:bee1pul) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1e532eebb9a35e665edfcc1a5e6d0210f752fd9e/src/main/kotlin/org/wfanet/measurement/measurementconsumer/stats/MetricStatistics.kt#L19)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Drop the unnecessary "base" prefix everywhere.
</blockquote></details>

The reason I prefixed with "base" is because the classes/objects are not exactly the methodologies in the kingdom protocol config. Instead, they are more like an aggregation of one common methodology.
___
*[`src/main/kotlin/org/wfanet/measurement/measurementconsumer/stats/Variances.kt` line 28 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1253#-Nfr36fZ68ccFB3mmk82:-NfrsXzo43D3qJGQJc9T:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1e532eebb9a35e665edfcc1a5e6d0210f752fd9e/src/main/kotlin/org/wfanet/measurement/measurementconsumer/stats/Variances.kt#L28)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Same note here re: where to define the exception.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/measurementconsumer/stats/Variances.kt` line 437 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1253#-Nfr4LFiBqeUauZIMTad:-NfrSd3JAvGEaVFES5tZ:b-wysxsf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1e532eebb9a35e665edfcc1a5e6d0210f752fd9e/src/main/kotlin/org/wfanet/measurement/measurementconsumer/stats/Variances.kt#L437)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: use precondition functions
</blockquote></details>

Fixed this and others.
___
*[`src/test/kotlin/org/wfanet/measurement/measurementconsumer/stats/VariancesTest.kt` line 21 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1253#-Nfr5rhe6fZfM-szz94-:-NfrjcS5D_UpJaPCD47M:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1e532eebb9a35e665edfcc1a5e6d0210f752fd9e/src/test/kotlin/org/wfanet/measurement/measurementconsumer/stats/VariancesTest.kt#L21)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Use `kotlin.test.assertFailsWith` instead for tests written in Kotlin
</blockquote></details>

Done.
___
*[`src/test/kotlin/org/wfanet/measurement/measurementconsumer/stats/VariancesTest.kt` line 2925 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1253#-Nfr66NAEXVBa-6BWh_m:-Nfrzwxy1fB2AheWBz-3:b-xu0uci) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1e532eebb9a35e665edfcc1a5e6d0210f752fd9e/src/test/kotlin/org/wfanet/measurement/measurementconsumer/stats/VariancesTest.kt#L2925)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: write this using built-in support in Truth for floating point tolerances (e.g. `assertThat(actual).isWithin(tolerance).of(expected)` or add a custom subject (e.g. [FuzzyLongSubject](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/main/kotlin/org/wfanet/measurement/api/v2alpha/testing/FuzzyLongSubject.kt)). Making this change will result in clearer error messages, as opposed to something like "Expected 0.006 is less than 0.005"
</blockquote></details>

Thanks for the suggestion. Done.


<!-- Sent from Reviewable.io -->

2023-10-04 17:44 UTC, SanjayVas approved these changes
> Reviewed 6 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1253)* status: all files reviewed, 2 unresolved discussions (waiting on @riemanli)

___
*[`src/main/kotlin/org/wfanet/measurement/measurementconsumer/stats/MetricStatistics.kt` line 19 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1253#-Nfr2V6I8rLGgkSAvlXd:-Nfvl9Ep91-Mqoo5O4FL:b-hgdaqj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1e532eebb9a35e665edfcc1a5e6d0210f752fd9e/src/main/kotlin/org/wfanet/measurement/measurementconsumer/stats/MetricStatistics.kt#L19)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

The reason I prefixed with "base" is because the classes/objects are not exactly the methodologies in the kingdom protocol config. Instead, they are more like an aggregation of one common methodology.
</blockquote></details>

I don't think that's of particular relevance here as long as it's obvious which of these classes to use. This package has no dependencies on the public API.

Leaving this a nit to unblock.
___
*[`src/test/kotlin/org/wfanet/measurement/measurementconsumer/stats/CovariancesTest.kt` line 507 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1253#-NfvmAyuBNA66a8dzERx:-NfvmAyuBNA66a8dzERy:b-5wigcw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3ad0ba1579f710c51dbb3e19bfa289053eb848e6/src/test/kotlin/org/wfanet/measurement/measurementconsumer/stats/CovariancesTest.kt#L507)):*
> ```Kotlin
> 
>   companion object {
>     fun computeErrorTolerance(estimate: Double, truth: Double): Double {
> ```

nit: the common terminology is "actual" (the value returned by the SUT) and "expected".



_Code quote:_
```Kotlin
estimate: Double, truth: Double
```


<!-- Sent from Reviewable.io -->

2023-10-04 18:53 UTC, SanjayVas approved these changes
> Reviewed 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1253)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jiayu-google)



<!-- Sent from Reviewable.io -->

2023-10-04 22:23 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1253)* status: all files reviewed, 1 unresolved discussion (waiting on @jiayu-google and @Marco-Premier)

___
*[`src/main/kotlin/org/wfanet/measurement/measurementconsumer/stats/MetricStatistics.kt` line 36 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1253#-Nfwm8sp1lmOVfAC-cnF:-Nfwm8sp1lmOVfAC-cnG:b-uvohd4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1bad5ec31f7d601f14913328db5160746e08cf95/src/main/kotlin/org/wfanet/measurement/measurementconsumer/stats/MetricStatistics.kt#L36)):*
> ```Kotlin
>   val decayRate: Double,
>   val sketchSize: Double,
>   val samplingIndicatorSize: Double
> ```

@jiayu-google  should sketch size and sampling indicator size be `Long` or `Double` based on their properties?



_Code quote:_
```Kotlin
  val sketchSize: Double,
  val samplingIndicatorSize: Double
```


<!-- Sent from Reviewable.io -->

2023-10-05 08:04 UTC, Marco-Premier approved these changes
> Reviewed 2 of 8 files at r2, 2 of 7 files at r4, 2 of 6 files at r5, 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1253)* status: all files reviewed, 1 unresolved discussion (waiting on @jiayu-google)



<!-- Sent from Reviewable.io -->

2023-10-05 17:35 UTC, jiayu-google approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1253#-:-Ng-u8QE9G1kfsLmlHwJ:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @riemanli)

___
*[`src/main/kotlin/org/wfanet/measurement/measurementconsumer/stats/MetricStatistics.kt` line 36 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1253#-Nfwm8sp1lmOVfAC-cnF:-Ng-tdRi0bSEdRXpXUp-:b-2mp85x) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1bad5ec31f7d601f14913328db5160746e08cf95/src/main/kotlin/org/wfanet/measurement/measurementconsumer/stats/MetricStatistics.kt#L36)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

@jiayu-google  should sketch size and sampling indicator size be `Long` or `Double` based on their properties?
</blockquote></details>

Long. good catch


<!-- Sent from Reviewable.io -->

2023-10-05 18:21 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1253)* status: 7 of 11 files reviewed, all discussions resolved (waiting on @Marco-Premier and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/measurementconsumer/stats/MetricStatistics.kt` line 36 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1253#-Nfwm8sp1lmOVfAC-cnF:-Ng03eaNBzycb117f3Bl:b26vfiu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ff0e32941b540a7138aed70ae0ab1510a0c2715c/src/main/kotlin/org/wfanet/measurement/measurementconsumer/stats/MetricStatistics.kt#L36)):*
<details><summary><i>Previously, jiayu-google wrote…</i></summary><blockquote>

Long. good catch
</blockquote></details>

Fixed. PTAL. Thanks!


<!-- Sent from Reviewable.io -->

2023-10-05 20:35 UTC, jiayu-google approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1253#-:-Ng0YC751DOcERZ1aTi6:bnfp4nl)* status: 7 of 11 files reviewed, all discussions resolved (waiting on @Marco-Premier and @SanjayVas)



<!-- Sent from Reviewable.io -->

2023-10-05 20:38 UTC, riemanli reviewed
@Marco-Premier @SanjayVas I fixed the type of `SketchSize` and `SamplingIndicatorSize` from `Double` to `Long`. Please take another look when you have time. Thanks!

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1253#-:-Ng0Yd2UBZ13Rlb6geMJ:byprd9h)* status: 7 of 11 files reviewed, all discussions resolved (waiting on @Marco-Premier and @SanjayVas)



<!-- Sent from Reviewable.io -->

2023-10-05 21:42 UTC, SanjayVas approved these changes
> Reviewed 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1253)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Marco-Premier)



<!-- Sent from Reviewable.io -->

2023-10-10 09:27 UTC, Marco-Premier approved these changes
> Reviewed 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1253)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @riemanli)



<!-- Sent from Reviewable.io -->

2023-10-10 09:28 UTC, Marco-Premier approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1253)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @riemanli)



<!-- Sent from Reviewable.io -->

2023-10-10 17:20 UTC, merged