Implement Internal MeasurementConsumers Service
world-federation-of-advertisers/cross-media-measurement pull request #126
Opened 2021-06-25 01:47 UTC by uakyol

2021-06-25 01:47 UTC, uakyol commented
part of #103

2021-06-25 02:03 UTC, uakyol commented
I need help with :  

Should the MeasurementConsumer from getMeasurementConsumer have the preferred_certificate?

2021-06-25 21:23 UTC, wangyaopw reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/126)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @uakyol)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementConsumersService.kt, line 35 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/126#-Md41FET0hpE7lw5X3S0:-Md41FET0hpE7lw5X3S1:b8izn0l) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f90c277b43f8405837f98a14f2a93f90ab653bef/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementConsumersService.kt#L35)):*
> ```
> MeasurementConsumer
> ```

As a service implementation, I guess it is best to have some basic request validations here. (For example, checking if required fields are set). So we can return a more meaningful customized error message to the caller, and not just propagate the errors from the spannerWriter back.


<!-- Sent from Reviewable.io -->

2021-06-28 03:00 UTC, uakyol reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/126)* status: 0 of 13 files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementConsumersService.kt, line 35 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/126#-Md41FET0hpE7lw5X3S0:-MdFYXRR1t8EQJL11cRT:b-fcoit6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f90c277b43f8405837f98a14f2a93f90ab653bef/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementConsumersService.kt#L35)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
> MeasurementConsumer
> ```

As a service implementation, I guess it is best to have some basic request validations here. (For example, checking if required fields are set). So we can return a more meaningful customized error message to the caller, and not just propagate the errors from the spannerWriter back.
</blockquote></details>

I am open to this but as a reference point, we didn't have this practice in the services before: https://github.com/world-federation-of-advertisers/cross-media-measurement/tree/main/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal . Would love to have a discussion and  settle upon exactly what we want since we have 8 services like this. I would vote for leaving this as is other than some edge cases for important fields.


<!-- Sent from Reviewable.io -->

2021-06-28 16:47 UTC, stevenwarejones commented
Please add a non-googler

2021-06-28 17:17 UTC, wangyaopw reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/126)* status: 0 of 13 files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @uakyol)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementConsumersService.kt, line 35 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/126#-Md41FET0hpE7lw5X3S0:-MdIbQe76fJKYWeiRLBB:bpdkwsy) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f90c277b43f8405837f98a14f2a93f90ab653bef/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementConsumersService.kt#L35)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

I am open to this but as a reference point, we didn't have this practice in the services before: https://github.com/world-federation-of-advertisers/cross-media-measurement/tree/main/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal . Would love to have a discussion and  settle upon exactly what we want since we have 8 services like this. I would vote for leaving this as is other than some edge cases for important fields.
</blockquote></details>

Yep, a discussion is fine.

just want to point out that we are now writing code for production. We can not simply follow whatever way the proof of concept code does.


<!-- Sent from Reviewable.io -->

2021-06-28 21:09 UTC, SanjayVas requested changes
> Reviewed 2 of 5 files at r1, 11 of 11 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/126)* status: all files reviewed, 9 unresolved discussions (waiting on @oliver-amzn, @uakyol, and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/common/identity/testing/DeterministicIdGenerator.kt, line 22 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/126#-MdJLy-d4EJen7r6aPvx:-MdJLy-d4EJen7r6aPvy:bpn0lhn) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2a8ee8a4379c40834e4458cf76186ba6cdcb7d5d/src/main/kotlin/org/wfanet/measurement/common/identity/testing/DeterministicIdGenerator.kt#L22)):*
> ```
> idSeed
> ```
nit: the term "seed" is generally used in the context of RNG. Perhaps initialId (which also implies that you post-increment in the getter)?

Comment copied from #123. 
___
*[src/main/kotlin/org/wfanet/measurement/common/identity/testing/DeterministicIdGenerator.kt, line 22 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/126#-MdJM9jlDVH9UliKgRkl:-MdJM9jlDVH9UliKgRkm:b-3u6ccu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2a8ee8a4379c40834e4458cf76186ba6cdcb7d5d/src/main/kotlin/org/wfanet/measurement/common/identity/testing/DeterministicIdGenerator.kt#L22)):*
> ```
> DeterministicIdGenerator
> ```
`FixedIdGenerator` is also deterministic. Maybe `IncrementingIdGenerator`?

Comment copied from #123. 
___
*[src/main/kotlin/org/wfanet/measurement/common/identity/testing/DeterministicIdGenerator.kt, line 22 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/126#-MdJQ6lH7vIuCf1GdeOa:-MdJQ6lI-UPYoyUVOWOo:bf8eark) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2a8ee8a4379c40834e4458cf76186ba6cdcb7d5d/src/main/kotlin/org/wfanet/measurement/common/identity/testing/DeterministicIdGenerator.kt#L22)):*
> ```
> iter
> ```
This isn't an iterator or an iterable. I think what you're referring to is the increment.

This should also probably have a default of 1. Otherwise, the default instance isn't meaningfully different than `FixedIdGenerator`.

Comment copied from #123. 
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementConsumersService.kt, line 35 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/126#-Md41FET0hpE7lw5X3S0:-MdJMJMP8ySPiPiRWOW-:b-hevrlh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f90c277b43f8405837f98a14f2a93f90ab653bef/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementConsumersService.kt#L35)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

Yep, a discussion is fine.

just want to point out that we are now writing code for production. We can not simply follow whatever way the proof of concept code does.
</blockquote></details>

IMO service implementation is the right place to validate request arguments. We should be doing it somewhere, and it makes more sense to do it here than in the Writer.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementConsumersService.kt, line 47 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/126#-MdJMseO-SXiPH8Tur-X:-MdJMseO-SXiPH8Tur-Y:b97dzq3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2a8ee8a4379c40834e4458cf76186ba6cdcb7d5d/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementConsumersService.kt#L47)):*
> ```
> FAILED_PRECONDITION
> ```
`NOT_FOUND`
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementConsumerReader.kt, line 24 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/126#-MdJNAFw3mxwtHGsmP7j:-MdJNAFw3mxwtHGsmP7k:bb5lyr8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2a8ee8a4379c40834e4458cf76186ba6cdcb7d5d/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementConsumerReader.kt#L24)):*
> ```Kotlin
>   data class Result(val measurementConsumer: MeasurementConsumer, val measurementConsumerId: Long)
> 
>   // override val baseSql: String =
> ```

Drop commented-out code.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementConsumerReader.kt, line 60 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/126#-MdJRdq5DxQU34qruQ_6:-MdJRdq5DxQU34qruQ_7:b38mwdg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2a8ee8a4379c40834e4458cf76186ba6cdcb7d5d/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementConsumerReader.kt#L60)):*
> ```Kotlin
>         details =
>           struct.getProtoMessage("MeasurementConsumerDetails", MeasurementConsumer.Details.parser())
>       }
> ```

Doesn't this need to fill in the `preferred_certificate` field using the columns from the Certificates table?
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurementConsumer.kt, line 58 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/126#-MdJQMgn7kG7YKs_0t_l:-MdJQMgn7kG7YKs_0t_m:b8cb0ls) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2a8ee8a4379c40834e4458cf76186ba6cdcb7d5d/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurementConsumer.kt#L58)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
>     return measurementConsumer
>       .toBuilder()
>       .setExternalMeasurementConsumerId(externalMeasurementConsumerId.value)
>       .setExternalPublicKeyCertificateId(externalMeasurementConsumerCertificateId.value)
>       .build()
> ```
</details>

I think you also need to specify the generated external IDs of submessages, e.g. within the `preferred_certificate` submessage.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementConsumersServiceTest.kt, line 65 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/126#-MdJRAr570UXDWsqfOE3:-MdJR4aS9KhjOZmxcdoL:bk6x2yr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2a8ee8a4379c40834e4458cf76186ba6cdcb7d5d/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementConsumersServiceTest.kt#L65)):*
> ```Kotlin
>           .build()
>       )
> ```

This should be verifying that the appropriate fields are set in the created MC (e.g. the generated ID fields). A separate test method for `Get` should verify that the created and gotten ones match.


<!-- Sent from Reviewable.io -->

2021-06-30 20:38 UTC, uakyol reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/126)* status: 8 of 13 files reviewed, 9 unresolved discussions (waiting on @oliver-amzn, @SanjayVas, and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementConsumersService.kt, line 35 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/126#-Md41FET0hpE7lw5X3S0:-MdTd-BQ2IIIv0HWWw7Q:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f90c277b43f8405837f98a14f2a93f90ab653bef/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementConsumersService.kt#L35)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

IMO service implementation is the right place to validate request arguments. We should be doing it somewhere, and it makes more sense to do it here than in the Writer.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementConsumersService.kt, line 47 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/126#-MdJMseO-SXiPH8Tur-X:-MdJWwrgE0zrxGwPBU5D:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2a8ee8a4379c40834e4458cf76186ba6cdcb7d5d/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementConsumersService.kt#L47)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> FAILED_PRECONDITION
> ```
`NOT_FOUND`
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementConsumerReader.kt, line 24 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/126#-MdJNAFw3mxwtHGsmP7j:-MdJW9NlAHoEBuoYyQ6N:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2a8ee8a4379c40834e4458cf76186ba6cdcb7d5d/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementConsumerReader.kt#L24)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Drop commented-out code.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementConsumerReader.kt, line 60 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/126#-MdJRdq5DxQU34qruQ_6:-MdJWEvcAKMNFWDc0Qth:bbqp0pv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2a8ee8a4379c40834e4458cf76186ba6cdcb7d5d/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementConsumerReader.kt#L60)):*
> preferred_certificate
thank you. 
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurementConsumer.kt, line 58 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/126#-MdJQMgn7kG7YKs_0t_l:-MdJic50DX0mbcgW_b1L:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2a8ee8a4379c40834e4458cf76186ba6cdcb7d5d/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurementConsumer.kt#L58)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
>     return measurementConsumer
>       .toBuilder()
>       .setExternalMeasurementConsumerId(externalMeasurementConsumerId.value)
>       .setExternalPublicKeyCertificateId(externalMeasurementConsumerCertificateId.value)
>       .build()
> ```
I think you also need to specify the generated external IDs of submessages, e.g. within the `preferred_certificate` submessage.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementConsumersServiceTest.kt, line 65 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/126#-MdJRAr570UXDWsqfOE3:-MdTd50oEzJ54jJUerdr:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2a8ee8a4379c40834e4458cf76186ba6cdcb7d5d/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementConsumersServiceTest.kt#L65)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This should be verifying that the appropriate fields are set in the created MC (e.g. the generated ID fields). A separate test method for `Get` should verify that the created and gotten ones match.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/common/identity/testing/DeterministicIdGenerator.kt, line 22 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/126#-MdJLy-d4EJen7r6aPvx:-MdJWVwt6mXMnqn9S-M5:bcp3fji) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2a8ee8a4379c40834e4458cf76186ba6cdcb7d5d/src/main/kotlin/org/wfanet/measurement/common/identity/testing/DeterministicIdGenerator.kt#L22)):*
> setExternalMeasurementConsumerId
sorry I thought I deleted this.
___
*[src/main/kotlin/org/wfanet/measurement/common/identity/testing/DeterministicIdGenerator.kt, line 22 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/126#-MdJM9jlDVH9UliKgRkl:-MdJWYyJ26p3woKi36ex:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2a8ee8a4379c40834e4458cf76186ba6cdcb7d5d/src/main/kotlin/org/wfanet/measurement/common/identity/testing/DeterministicIdGenerator.kt#L22)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> DeterministicIdGenerator
> ```
`FixedIdGenerator` is also deterministic. Maybe `IncrementingIdGenerator`?

Comment copied from #123. 
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/common/identity/testing/DeterministicIdGenerator.kt, line 22 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/126#-MdJQ6lH7vIuCf1GdeOa:-MdJWZFX4C9X94dV3cC9:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2a8ee8a4379c40834e4458cf76186ba6cdcb7d5d/src/main/kotlin/org/wfanet/measurement/common/identity/testing/DeterministicIdGenerator.kt#L22)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> iter
> ```
This isn't an iterator or an iterable. I think what you're referring to is the increment.

This should also probably have a default of 1. Otherwise, the default instance isn't meaningfully different than `FixedIdGenerator`.

Comment copied from #123. 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-01 00:08 UTC, SanjayVas requested changes
> Reviewed 1 of 1 files at r3, 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/126)* status: all files reviewed, 3 unresolved discussions (waiting on @oliver-amzn, @uakyol, and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementConsumersService.kt, line 39 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/126#-MdULSQ42evSgM8HyAR8:-MdULSQ42evSgM8HyAR9:b-dfnsl7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ad84891d49c09af25054e05f88b27c77c8a03591/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementConsumersService.kt#L39)):*
> ```
> request.hasDetails()
> ```
nit: you don't technically need the hasDetails check if you're checking the fields inside of it. Proto message accessors always return default values if unset.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementConsumersServiceTest.kt, line 98 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/126#-MdUNwZ68UMuD9jDWBcu:-MdUNwZ68UMuD9jDWBcv:b-5zu4ng) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ad84891d49c09af25054e05f88b27c77c8a03591/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementConsumersServiceTest.kt#L98)):*
> ```Kotlin
>       measurementConsumersService.createMeasurementConsumer(measurementConsumer)
> 
>     assertThat(createdMeasurementConsumer)
> ```

I don't think this is checking that the ID fields are set appropriately.


<!-- Sent from Reviewable.io -->

2021-07-01 03:37 UTC, uakyol reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/126)* status: 11 of 13 files reviewed, 3 unresolved discussions (waiting on @oliver-amzn, @SanjayVas, and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementConsumersService.kt, line 39 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/126#-MdULSQ42evSgM8HyAR8:-MdV5iGI2gcQehX9L87j:b-zcjvte) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ad84891d49c09af25054e05f88b27c77c8a03591/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementConsumersService.kt#L39)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> request.hasDetails()
> ```
nit: you don't technically need the hasDetails check if you're checking the fields inside of it. Proto message accessors always return default values if unset.
</blockquote></details>

Thanks
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementConsumersServiceTest.kt, line 98 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/126#-MdUNwZ68UMuD9jDWBcu:-MdV5W4BBDvNt_HKAXMQ:bxhn7sd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ad84891d49c09af25054e05f88b27c77c8a03591/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementConsumersServiceTest.kt#L98)):*
> ```
> assertThat(createdMeasurementConsumer)
> ```
yes, thanks for catching this. I just made sure the ID fields are assigned and equal to each other for the top level MC and the Cert it contains. Does this look good?


<!-- Sent from Reviewable.io -->

2021-07-01 18:21 UTC, SanjayVas requested changes
> Reviewed 2 of 2 files at r5, 3 of 3 files at r6.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/126)* status: all files reviewed, 2 unresolved discussions (waiting on @oliver-amzn, @uakyol, and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementConsumersServiceTest.kt, line 98 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/126#-MdUNwZ68UMuD9jDWBcu:-MdYEvV56foGI6mbpjvn:bl6wwwv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ad84891d49c09af25054e05f88b27c77c8a03591/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementConsumersServiceTest.kt#L98)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

> ```
> assertThat(createdMeasurementConsumer)
> ```
yes, thanks for catching this. I just made sure the ID fields are assigned and equal to each other for the top level MC and the Cert it contains. Does this look good?
</blockquote></details>

This logic depends on having an ID generator that doesn't return 0. What you ideally want is a way for this base class to provide the ID generator used to construct the service impl instance.

Perhaps instead of having an overridable property for the service instance, have an abstract method for instantiating the service that takes in an ID generator. Then have a concrete implementation of the property here.

e.g., something like
```
abstract class MeasurementConsumersServiceTest<T : MeasurementConsumersCoroutineImplBase> {

  protected val idGenerator = // init some ID generator

  protected lateinit var service: T
    private set

  protected abstract fun newService(idGenerator: IdGenerator): T

  @Before
  fun initService() {
    service = newService(idGenerator)
  }
```


<!-- Sent from Reviewable.io -->

2021-07-01 20:14 UTC, uakyol reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/126)* status: 10 of 13 files reviewed, 2 unresolved discussions (waiting on @oliver-amzn, @SanjayVas, and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementConsumersServiceTest.kt, line 98 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/126#-MdUNwZ68UMuD9jDWBcu:-MdYh7Yk98LFULCVJz4H:b-vyq64g) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ad84891d49c09af25054e05f88b27c77c8a03591/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementConsumersServiceTest.kt#L98)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This logic depends on having an ID generator that doesn't return 0. What you ideally want is a way for this base class to provide the ID generator used to construct the service impl instance.

Perhaps instead of having an overridable property for the service instance, have an abstract method for instantiating the service that takes in an ID generator. Then have a concrete implementation of the property here.

e.g., something like
```
abstract class MeasurementConsumersServiceTest<T : MeasurementConsumersCoroutineImplBase> {

  protected val idGenerator = // init some ID generator

  protected lateinit var service: T
    private set

  protected abstract fun newService(idGenerator: IdGenerator): T

  @Before
  fun initService() {
    service = newService(idGenerator)
  }
```
</blockquote></details>

Thanks a lot for helping with this. I changed it, hope this works.


<!-- Sent from Reviewable.io -->

2021-07-01 22:56 UTC, SanjayVas requested changes
> Reviewed 3 of 3 files at r7.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/126)* status: all files reviewed, 3 unresolved discussions (waiting on @oliver-amzn, @uakyol, and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementConsumersServiceTest.kt, line 112 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/126#-MdZFUcL-yZlcPxXxXQr:-MdZFUcL-yZlcPxXxXQs:b-g6s4dy) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f2d49fef4aea6ac3392a076d044c75d2d0501b31/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementConsumersServiceTest.kt#L112)):*
> ```
> idGenerator.generateExternalId().value
> ```
Make constants for the IDs you're going to use and pass them to FixedIdGenerator. This way if we change to some deterministic dynamic ID generator, we can just switch the ID values we're checking against.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementConsumersServiceTest.kt, line 115 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/126#-MdZGXi8DAZeIiqzZFsu:-MdZGXi8DAZeIiqzZFsv:bv1hrgi) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f2d49fef4aea6ac3392a076d044c75d2d0501b31/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementConsumersServiceTest.kt#L115)):*
> ```Kotlin
>     assertThat(createdMeasurementConsumer.preferredCertificate.externalMeasurementConsumerId)
>       .isEqualTo(createdMeasurementConsumer.externalMeasurementConsumerId)
>     assertThat(createdMeasurementConsumer)
> ```

Isn't there also a generated certificate ID?


<!-- Sent from Reviewable.io -->

2021-07-01 23:01 UTC, wangyaopw reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/126)* status: all files reviewed, 3 unresolved discussions (waiting on @oliver-amzn and @uakyol)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementConsumersServiceTest.kt, line 117 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/126#-MdZI8V1AYGQRaX1ohC7:-MdZI8V1AYGQRaX1ohC8:b57iv6u) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f2d49fef4aea6ac3392a076d044c75d2d0501b31/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementConsumersServiceTest.kt#L117)):*
> ```Kotlin
>     assertThat(createdMeasurementConsumer)
>       .comparingExpectedFieldsOnly()
>       .isEqualTo(measurementConsumer)
> ```

One assert should be enough, i.e.
```
 assertThat(createdMeasurementConsumer).isEqualTo(
    measurementConsumer.toBuilder.apply{
       // set all additional expected fields.
    }.build()
```


<!-- Sent from Reviewable.io -->

2021-07-01 23:19 UTC, uakyol reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/126)* status: 12 of 13 files reviewed, 3 unresolved discussions (waiting on @oliver-amzn, @SanjayVas, and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementConsumersServiceTest.kt, line 112 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/126#-MdZFUcL-yZlcPxXxXQr:-MdZMibp754VO5cwdlbO:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f2d49fef4aea6ac3392a076d044c75d2d0501b31/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementConsumersServiceTest.kt#L112)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> idGenerator.generateExternalId().value
> ```
Make constants for the IDs you're going to use and pass them to FixedIdGenerator. This way if we change to some deterministic dynamic ID generator, we can just switch the ID values we're checking against.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementConsumersServiceTest.kt, line 115 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/126#-MdZGXi8DAZeIiqzZFsu:-MdZMjEeDVwq9Fl68Q_j:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f2d49fef4aea6ac3392a076d044c75d2d0501b31/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementConsumersServiceTest.kt#L115)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Isn't there also a generated certificate ID?
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementConsumersServiceTest.kt, line 117 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/126#-MdZI8V1AYGQRaX1ohC7:-MdZMjgN2Iny9UiJ0Jhs:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f2d49fef4aea6ac3392a076d044c75d2d0501b31/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementConsumersServiceTest.kt#L117)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

One assert should be enough, i.e.
```
 assertThat(createdMeasurementConsumer).isEqualTo(
    measurementConsumer.toBuilder.apply{
       // set all additional expected fields.
    }.build()
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-01 23:24 UTC, wangyaopw approved these changes
> Reviewed 1 of 5 files at r1, 3 of 11 files at r2, 1 of 4 files at r4, 1 of 2 files at r5, 3 of 3 files at r6, 2 of 3 files at r7, 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/126)* status: all files reviewed, 3 unresolved discussions (waiting on @oliver-amzn, @SanjayVas, and @wangyaopw)



<!-- Sent from Reviewable.io -->

2021-07-02 00:33 UTC, SanjayVas approved these changes
> Reviewed 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/126)* status: all files reviewed, 1 unresolved discussion (waiting on @oliver-amzn and @wangyaopw)



<!-- Sent from Reviewable.io -->

2021-07-08 21:14 UTC, zachcwc approved these changes
> Reviewed 1 of 5 files at r1, 3 of 11 files at r2, 1 of 4 files at r4, 1 of 2 files at r5, 2 of 3 files at r6, 2 of 3 files at r7, 1 of 1 files at r8, 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/126)* status: all files reviewed, 1 unresolved discussion (waiting on @oliver-amzn and @wangyaopw)



<!-- Sent from Reviewable.io -->

2021-07-09 19:09 UTC, merged