Implement refactoring of custom direct methodology
world-federation-of-advertisers/cross-media-measurement pull request #1265
Opened 2023-09-29 17:34 UTC by riemanli

2023-09-29 17:34 UTC, wfa-reviewable commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1265)
<!-- Reviewable:end -->

2023-10-04 21:56 UTC, tristanvuong2021 approved these changes
> Reviewed 2 of 5 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1265)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)



<!-- Sent from Reviewable.io -->

2023-10-05 14:59 UTC, stevenwarejones requested changes
> Reviewed 2 of 5 files at r1, 3 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1265)* status: all files reviewed, 1 unresolved discussion (waiting on @riemanli)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ProtoConversions.kt` line 831 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1265#-Ng-LKMCBiI8vPhiQz7R:-Ng-LKMCBiI8vPhiQz7S:b-yrwjva) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/75e2ccd49db47cf7dc879f201b04c20c82190ce3/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ProtoConversions.kt#L831)):*
> ```Kotlin
>       }
>       CustomDirectMethodology.VarianceCase.VARIANCE_NOT_SET -> {
>         error("Variance in CustomDirectMethodology is not set.")
> ```

should this really throw an error? Shouldn't the partial results still be revealed to the advertiser?


<!-- Sent from Reviewable.io -->

2023-10-05 16:35 UTC, riemanli commented
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ProtoConversions.kt` line 831 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1265#-Ng-LKMCBiI8vPhiQz7R:-Ng-fstZDTHca7elOn6a:b-dla5zp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/75e2ccd49db47cf7dc879f201b04c20c82190ce3/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ProtoConversions.kt#L831)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

should this really throw an error? Shouldn't the partial results still be revealed to the advertiser?
</blockquote></details>

The user can choose not to set `CustomDirectMethodology` during the transition. But if `CustomDirectMethodology` is set, its required fields should be specified.


<!-- Sent from Reviewable.io -->

2023-10-05 17:26 UTC, stevenwarejones approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1265)* status: all files reviewed, 1 unresolved discussion (waiting on @riemanli)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ProtoConversions.kt` line 831 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1265#-Ng-LKMCBiI8vPhiQz7R:-Ng-rz9UD6_IX3rhpy-a:b9bfmdy) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/75e2ccd49db47cf7dc879f201b04c20c82190ce3/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ProtoConversions.kt#L831)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

The user can choose not to set `CustomDirectMethodology` during the transition. But if `CustomDirectMethodology` is set, its required fields should be specified.
</blockquote></details>

i guess its okay since the oneof field that includes `CustomDirectMetholody` is not required.


<!-- Sent from Reviewable.io -->

2023-10-05 20:32 UTC, merged