Implement logic for Population Service
world-federation-of-advertisers/cross-media-measurement pull request #1268
Opened 2023-10-02 17:49 UTC by jojijac0b

- Creates SpannerPopulationsService
- Implements Create, Get, And Stream methods
- Creates tests

2023-10-02 17:49 UTC, wfa-reviewable commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1268)
<!-- Reviewable:end -->

2023-10-03 00:01 UTC, tristanvuong2021 requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1268)* status: 8 of 9 files reviewed, 11 unresolved discussions (waiting on @jojijac0b, @Marco-Premier, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamPopulations.kt` line 36 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1268#-NfmpF_e4Io35dknHAT3:-Nfmn15i2a6Wtdav4-r9:b-caz03k) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/766df810d7fd9d1719f71bbc8b0eac933c1d8f88/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamPopulations.kt#L36)):*
> ```Kotlin
>     if (filter.externalDataProviderId != 0L) {
>       conjuncts.add("ExternalDataProviderId = @${EXTERNAL_DATA_PROVIDER_ID}")
>       bind(EXTERNAL_DATA_PROVIDER_ID to filter.externalDataProviderId)
> ```

EXTERNAL_DATA_PROVIDER_ID is bound here and in the after block to different variables. Need to create another parameter string.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/PopulationsServiceTest.kt` line 183 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1268#-NfmpcXIA_O301NKKzRR:-NfmpcXIA_O301NKKzRS:b-agqfrt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/766df810d7fd9d1719f71bbc8b0eac933c1d8f88/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/PopulationsServiceTest.kt#L183)):*
> ```Kotlin
>   }
> 
>   fun `streamPopulations succeeds`() = runBlocking {
> ```

Missing test with after filter


<!-- Sent from Reviewable.io -->

2023-10-03 18:08 UTC, jojijac0b reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1268)* status: 6 of 9 files reviewed, 10 unresolved discussions (waiting on @Marco-Premier, @SanjayVas, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerPopulationsService.kt` line 40 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1268#-NflbHci6V0IneByM5Ri:-Nfq_Xu45r0hIi3go3Zx:b-oddk1o) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/766df810d7fd9d1719f71bbc8b0eac933c1d8f88/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerPopulationsService.kt#L40)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This doesn't make sense. The `after` field is for pagination. The request for the page won't have it set.
</blockquote></details>

@SanjayVas it looks like this is done in some other streaming functions to ensure the after field has all required fields set(i need to add a check for extrenalDataProviderId and populationId if I keep this check). Is it still unneeded as this After filter is in StreamPopulationsRequest?

StreamPopulationsRequest: https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c98743fc690ec1e50f577945ab0de64ca85951c5/src/main/proto/wfa/measurement/internal/kingdom/populations_service.proto#L39C1-L39C35

Other Spanner service using this approach: https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c98743fc690ec1e50f577945ab0de64ca85951c5/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerModelSuitesService.kt#L63
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamPopulations.kt` line 19 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1268#-NflcLaz-OiPc_1pDiLZ:-NfnkZO1B_az1RUc9ZtJ:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/766df810d7fd9d1719f71bbc8b0eac933c1d8f88/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamPopulations.kt#L19)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Are you sure you want this in ascending CreateTime order? Aren't we most likely to want to see/use the more recent Populations?

Note that whatever order we have here, make sure to document it on the API method definition. See StreamCertificates as an example.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamPopulations.kt` line 36 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1268#-NfmpF_e4Io35dknHAT3:-Nfnoqf5Cr-Hwnh7HQ6O:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/766df810d7fd9d1719f71bbc8b0eac933c1d8f88/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamPopulations.kt#L36)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

EXTERNAL_DATA_PROVIDER_ID is bound here and in the after block to different variables. Need to create another parameter string.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamPopulations.kt` line 65 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1268#-NfleTOy-niwXk-g9KR1:-NfnpJ0i8dCPeJRu_C4f:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/766df810d7fd9d1719f71bbc8b0eac933c1d8f88/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamPopulations.kt#L65)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

These should be private.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/PopulationsServiceTest.kt` line 90 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1268#-NflgGUW-0tBZkZ9zkiX:-NfoC4hVDxH2nmDBf_Y_:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/766df810d7fd9d1719f71bbc8b0eac933c1d8f88/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/PopulationsServiceTest.kt#L90)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Add separate assertions for the fields you're ignoring here. e.g.

```kotlin
assertThat(createdPopulation.createTime.seconds).isGreaterThan(0)
assertThat(createdPopulation.externalPopulationId).isNotEqualTo(population.externalPopulationId)
```
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/PopulationsServiceTest.kt` line 183 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1268#-NfmpcXIA_O301NKKzRR:-NfoC3_D4E2Fe675eO-f:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/766df810d7fd9d1719f71bbc8b0eac933c1d8f88/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/PopulationsServiceTest.kt#L183)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Missing test with after filter
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-03 19:18 UTC, tristanvuong2021 requested changes
> Reviewed 4 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1268)* status: 6 of 9 files reviewed, 9 unresolved discussions (waiting on @jojijac0b, @Marco-Premier, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/PopulationsServiceTest.kt` line 276 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1268#-Nfqxnfy0gb-84QGmSC7:-Nfqxnfy0gb-84QGmSC8:b-1qjr42) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/efc7d6bce94fcd1bde6d897d420ee7560f9229ed/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/PopulationsServiceTest.kt#L276)):*
> ```Kotlin
>       filter {
>         externalDataProviderId = dataProvider.externalDataProviderId
>         after = afterFilter {
> ```

Since the external ids are random, population1's id isn't guaranteed to be the smallest. Dropping it from the afterFilter message and just setting externalDataProviderId and createTime would be consistent.


<!-- Sent from Reviewable.io -->

2023-10-03 21:07 UTC, SanjayVas requested changes
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1268)* status: all files reviewed, 7 unresolved discussions (waiting on @jojijac0b, @Marco-Premier, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerPopulationsService.kt` line 40 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1268#-NflbHci6V0IneByM5Ri:-NfrKfP-7bpfYN_A1MEh:b-l6qagu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/766df810d7fd9d1719f71bbc8b0eac933c1d8f88/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerPopulationsService.kt#L40)):*
<details><summary><i>Previously, jojijac0b wrote…</i></summary><blockquote>

@SanjayVas it looks like this is done in some other streaming functions to ensure the after field has all required fields set(i need to add a check for extrenalDataProviderId and populationId if I keep this check). Is it still unneeded as this After filter is in StreamPopulationsRequest?

StreamPopulationsRequest: https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c98743fc690ec1e50f577945ab0de64ca85951c5/src/main/proto/wfa/measurement/internal/kingdom/populations_service.proto#L39C1-L39C35

Other Spanner service using this approach: https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c98743fc690ec1e50f577945ab0de64ca85951c5/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerModelSuitesService.kt#L63
</blockquote></details>

Sorry, I missed the "hasAfter" part of the check.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamPopulations.kt` line 42 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1268#-NfrLQZO0vi6uG5Q_Gn4:-NfrLQZO0vi6uG5Q_Gn5:b-6puj4w) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/efc7d6bce94fcd1bde6d897d420ee7560f9229ed/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamPopulations.kt#L42)):*
> ```Kotlin
>       conjuncts.add(
>         """
>           Populations.CreateTime > @${CREATED_AFTER} OR (
> ```

You need to switch the direction on the CreateTime check if using descending ordering. It's not actually "created after". The "after" in the name is indicating that you want the elements *after* the one in the ordering identified by the (CreateTime, ExternalDataProviderId, ExternalPopulationId) tuple.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/PopulationsServiceTest.kt` line 89 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1268#-NfrMGfw64gkfbS3Uw-y:-NfrMGfw64gkfbS3Uw-z:bw5eyn8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/efc7d6bce94fcd1bde6d897d420ee7560f9229ed/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/PopulationsServiceTest.kt#L89)):*
> ```Kotlin
>         }
>       )
>     Truth.assertThat(response.createTime.seconds).isGreaterThan(0L)
> ```

Remove redundant qualification (Truth.assertThat is already imported).



_Suggestion:_
```Kotlin
assertThat
```


<!-- Sent from Reviewable.io -->

2023-10-04 02:15 UTC, jojijac0b reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1268)* status: 7 of 9 files reviewed, 6 unresolved discussions (waiting on @Marco-Premier, @SanjayVas, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamPopulations.kt` line 42 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1268#-NfrLQZO0vi6uG5Q_Gn4:-NfsSTJW-5VV59PA1Z6M:b-j3bczz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/efc7d6bce94fcd1bde6d897d420ee7560f9229ed/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamPopulations.kt#L42)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

You need to switch the direction on the CreateTime check if using descending ordering. It's not actually "created after". The "after" in the name is indicating that you want the elements *after* the one in the ordering identified by the (CreateTime, ExternalDataProviderId, ExternalPopulationId) tuple.
</blockquote></details>

@SanjayVas The sorting is done after the WHERE clause so wouldn't this mean that we can still leave the direction of this check as-is?
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/PopulationReader.kt` line 59 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1268#-Nflf4kk-IIPxLQV26N2:-NfsSDpX6f0qae-Untov:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/766df810d7fd9d1719f71bbc8b0eac933c1d8f88/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/PopulationReader.kt#L59)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Use Kotlin DSL builders in all new code.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/PopulationsServiceTest.kt` line 67 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1268#-NflfwbW0-XhA8aiCq-l:-NfsSDFoDpCiU09BGzli:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/766df810d7fd9d1719f71bbc8b0eac933c1d8f88/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/PopulationsServiceTest.kt#L67)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

These can be private constants. Make these private, use CONST_CASE, and put them in the companion object. Use the `const` keyword when applicable.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/PopulationsServiceTest.kt` line 82 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1268#-Nflg_G96OULz4QSjbbb:-NfsSCbP4b9uaB1erCMz:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/766df810d7fd9d1719f71bbc8b0eac933c1d8f88/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/PopulationsServiceTest.kt#L82)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Use Kotlin DSL builder
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/PopulationsServiceTest.kt` line 89 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1268#-NfrMGfw64gkfbS3Uw-y:-NfsSBUr83uQvEkZbGTk:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/efc7d6bce94fcd1bde6d897d420ee7560f9229ed/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/PopulationsServiceTest.kt#L89)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Remove redundant qualification (Truth.assertThat is already imported).
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/PopulationsServiceTest.kt` line 276 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1268#-Nfqxnfy0gb-84QGmSC7:-NfsSIxd79hKlNpXrKtd:b-mvg5z7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/efc7d6bce94fcd1bde6d897d420ee7560f9229ed/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/PopulationsServiceTest.kt#L276)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Since the external ids are random, population1's id isn't guaranteed to be the smallest. Dropping it from the afterFilter message and just setting externalDataProviderId and createTime would be consistent.
</blockquote></details>

@tristanvuong2021 We cannot leave that field empty as there is a check for externalDataProviderId and externalPopulationId in streamPopulations method.


<!-- Sent from Reviewable.io -->

2023-10-04 02:17 UTC, tristanvuong2021 requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1268)* status: 7 of 9 files reviewed, 6 unresolved discussions (waiting on @jojijac0b, @Marco-Premier, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/PopulationsServiceTest.kt` line 276 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1268#-Nfqxnfy0gb-84QGmSC7:-NfsTIDh2gaITlrpS_Qy:bwbbs9q) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/efc7d6bce94fcd1bde6d897d420ee7560f9229ed/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/PopulationsServiceTest.kt#L276)):*
<details><summary><i>Previously, jojijac0b wrote…</i></summary><blockquote>

@tristanvuong2021 We cannot leave that field empty as there is a check for externalDataProviderId and externalPopulationId in streamPopulations method.
</blockquote></details>

Then just set it to 1. The generator creates much larger numbers.


<!-- Sent from Reviewable.io -->

2023-10-04 17:49 UTC, SanjayVas requested changes
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1268)* status: all files reviewed, 2 unresolved discussions (waiting on @jojijac0b, @Marco-Premier, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamPopulations.kt` line 42 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1268#-NfrLQZO0vi6uG5Q_Gn4:-NfvmgPG6IrcxS6iDOdi:bqyfgjk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/efc7d6bce94fcd1bde6d897d420ee7560f9229ed/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamPopulations.kt#L42)):*
<details><summary><i>Previously, jojijac0b wrote…</i></summary><blockquote>

@SanjayVas The sorting is done after the WHERE clause so wouldn't this mean that we can still leave the direction of this check as-is?
</blockquote></details>

No. The `after` tuple is effectively identifying an element within an ordered list, and you need to ensure the next set of results starts at and includes elements only *after* that element. Therefore the condition needs to apply the same comparison as the one that defines the ordering.


<!-- Sent from Reviewable.io -->

2023-10-04 19:32 UTC, jojijac0b reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1268)* status: all files reviewed, 2 unresolved discussions (waiting on @Marco-Premier, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/PopulationsServiceTest.kt` line 276 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1268#-Nfqxnfy0gb-84QGmSC7:-NfwAME8EZwHdO1ytqEn:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/efc7d6bce94fcd1bde6d897d420ee7560f9229ed/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/PopulationsServiceTest.kt#L276)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Then just set it to 1. The generator creates much larger numbers.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-04 21:22 UTC, jojijac0b reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1268)* status: 6 of 9 files reviewed, 2 unresolved discussions (waiting on @Marco-Premier, @SanjayVas, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamPopulations.kt` line 42 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1268#-NfrLQZO0vi6uG5Q_Gn4:-NfwZRU81nqNg54iwkiQ:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/efc7d6bce94fcd1bde6d897d420ee7560f9229ed/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamPopulations.kt#L42)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

No. The `after` tuple is effectively identifying an element within an ordered list, and you need to ensure the next set of results starts at and includes elements only *after* that element. Therefore the condition needs to apply the same comparison as the one that defines the ordering.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-05 18:31 UTC, jojijac0b reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1268)* status: 7 of 9 files reviewed, 3 unresolved discussions (waiting on @Marco-Premier, @SanjayVas, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamPopulations.kt` line 42 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1268#-NfwdctwDjtf3L83cqty:-Ng05zlr6sqP3E5BZxsq:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8bb0fea4115eedfaa627d493c10b03caee8d3f46/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamPopulations.kt#L42)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Rename this since it's misleading (it's not actually created after, but rather the CreateTime component of the after tuple).
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/PopulationsServiceTest.kt` line 276 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1268#-Nfqxnfy0gb-84QGmSC7:-Ng061VE5lfhzuFWh4C5:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/efc7d6bce94fcd1bde6d897d420ee7560f9229ed/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/PopulationsServiceTest.kt#L276)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> Then just set it to 1. The generator creates much larger numbers.

It's random, so it's not really safe to rely on that. I'd recommend switching the test to use SequentialIdGenerator so you can guarantee something about the ID generation.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-05 21:35 UTC, SanjayVas reviewed
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1268)* status: all files reviewed, 2 unresolved discussions (waiting on @jojijac0b, @Marco-Premier, @stevenwarejones, and @tristanvuong2021)



<!-- Sent from Reviewable.io -->

2023-10-06 18:21 UTC, jojijac0b reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1268)* status: 5 of 9 files reviewed, 2 unresolved discussions (waiting on @Marco-Premier, @SanjayVas, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/PopulationsServiceTest.kt` line 257 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1268#-NfwepCj3gzLf9AG2s11:-Ng5DEN27HX_uW9CI8hX:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8bb0fea4115eedfaa627d493c10b03caee8d3f46/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/PopulationsServiceTest.kt#L257)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This is underspecified. We should expect exact elements in order, verifying that the resulting list started at the right element. This means using an after filter that would skip at least one element.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-09 12:54 UTC, Marco-Premier approved these changes
> Reviewed 5 of 9 files at r1, 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1268)* status: all files reviewed, 2 unresolved discussions (waiting on @SanjayVas, @stevenwarejones, and @tristanvuong2021)



<!-- Sent from Reviewable.io -->

2023-10-09 18:17 UTC, SanjayVas requested changes
> Reviewed 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1268)* status: all files reviewed, 3 unresolved discussions (waiting on @jojijac0b, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamPopulations.kt` line 49 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1268#-NgKacCA8ahOyBMXI_xj:-NgKacCA8ahOyBMXI_xk:bvr1cwu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bb1cf13269b856beb5c58de75aa248e939957b9d/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamPopulations.kt#L49)):*
> ```Kotlin
>               Populations.ExternalPopulationId > @${EXTERNAL_POPULATION_ID}
>             )
>           )
> ```

It's still a little hard to read this as it doesn't follow the way a comparison is normally written for an ordering. The ordering is (CreateTime DESC, ExternalDataProviderId ASC, ExternalPopulationId ASC). That means the condition is (psuedocode, fix column and param names):

```
CreateTime < @createTime OR (
  CreateTime = @createTime AND DataProviderId > @dataProviderId
) OR (
  CreateTime = @createTime AND DataProviderId = @dataProviderId AND PopulationId > @populationId
)
```



_Code quote:_
```Kotlin
          Populations.CreateTime < @${CREATE_TIME} OR (
            Populations.CreateTime = @${CREATE_TIME} AND (
              DataProviders.ExternalDataProviderId = @${AFTER_EXTERNAL_DATA_PROVIDER_ID} AND
                Populations.ExternalPopulationId > @${EXTERNAL_POPULATION_ID}
            ) OR (
              Populations.ExternalPopulationId > @${EXTERNAL_POPULATION_ID}
            )
          )
```
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/PopulationsServiceTest.kt` line 251 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1268#-NgKdBZ-Ey956vj9syAQ:-NgKdBZ-Ey956vj9syAR:b-yhi2pn) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bb1cf13269b856beb5c58de75aa248e939957b9d/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/PopulationsServiceTest.kt#L251)):*
> ```Kotlin
>           externalDataProviderId = dataProvider.externalDataProviderId
>           externalPopulationId = population1.externalPopulationId
>           createTime = timestamp { seconds = population1.createTime.seconds }
> ```

Use the actual Timestamp. Just using the seconds is incorrect.

1. Timestamp supports nanosecond granularity
2. Spanner supports microsecond granularity for commit timestamps.



_Suggestion:_
```Kotlin
createTime = population1.createTime
```


<!-- Sent from Reviewable.io -->

2023-10-10 17:13 UTC, jojijac0b reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1268)* status: 7 of 9 files reviewed, 3 unresolved discussions (waiting on @Marco-Premier, @SanjayVas, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamPopulations.kt` line 49 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1268#-NgKacCA8ahOyBMXI_xj:-NgPZz615SHEh-zg17QA:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bb1cf13269b856beb5c58de75aa248e939957b9d/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamPopulations.kt#L49)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

It's still a little hard to read this as it doesn't follow the way a comparison is normally written for an ordering. The ordering is (CreateTime DESC, ExternalDataProviderId ASC, ExternalPopulationId ASC). That means the condition is (psuedocode, fix column and param names):

```
CreateTime < @createTime OR (
  CreateTime = @createTime AND DataProviderId > @dataProviderId
) OR (
  CreateTime = @createTime AND DataProviderId = @dataProviderId AND PopulationId > @populationId
)
```
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/PopulationsServiceTest.kt` line 251 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1268#-NgKdBZ-Ey956vj9syAQ:-NgP_1pOAfpcoHGwOcTn:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bb1cf13269b856beb5c58de75aa248e939957b9d/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/PopulationsServiceTest.kt#L251)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Use the actual Timestamp. Just using the seconds is incorrect.

1. Timestamp supports nanosecond granularity
2. Spanner supports microsecond granularity for commit timestamps.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-10 17:51 UTC, SanjayVas requested changes
> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1268)* status: all files reviewed, 2 unresolved discussions (waiting on @jojijac0b, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/PopulationsServiceTest.kt` line 250 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1268#-NgPhR7OEnFlOn-qd9bc:-NgPhR7PCjTlZ0GhNX1c:b-eun944) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c2136bce0bcf7019e383e8968fd255efcf66f627/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/PopulationsServiceTest.kt#L250)):*
> ```Kotlin
>           externalDataProviderId = dataProvider.externalDataProviderId
>           externalPopulationId = population1.externalPopulationId
>           createTime = population2.createTime
> ```

Shouldn't this all come from population3? If the normal order is (3, 2, 1) and we're trying to indicate we want results after 3 then we should populate the entire after tuple from population3.



_Code quote:_
```Kotlin
          externalDataProviderId = dataProvider.externalDataProviderId
          externalPopulationId = population1.externalPopulationId
          createTime = population2.createTime
```


<!-- Sent from Reviewable.io -->

2023-10-10 18:40 UTC, jojijac0b reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1268)* status: 8 of 9 files reviewed, 2 unresolved discussions (waiting on @SanjayVas, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/PopulationsServiceTest.kt` line 250 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1268#-NgPhR7OEnFlOn-qd9bc:-NgPsxUy0w4Lw5pUwweR:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c2136bce0bcf7019e383e8968fd255efcf66f627/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/PopulationsServiceTest.kt#L250)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Shouldn't this all come from population3? If the normal order is (3, 2, 1) and we're trying to indicate we want results after 3 then we should populate the entire after tuple from population3.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-10 18:57 UTC, SanjayVas approved these changes
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1268)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones and @tristanvuong2021)



<!-- Sent from Reviewable.io -->

2023-10-10 22:37 UTC, tristanvuong2021 approved these changes
> Reviewed 6 of 6 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1268)* status: all files reviewed, 2 unresolved discussions (waiting on @jojijac0b and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/PopulationsServiceTest.kt` line 47 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1268#-NgQisTTBpSnhnB2Fj-I:-NgQisTUEDkd5nYgv6ML:b9xv87z) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/89c4474f63e60cbae91b1c33b0fd093718d01152/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/PopulationsServiceTest.kt#L47)):*
> ```Kotlin
> import org.wfanet.measurement.internal.kingdom.streamPopulationsRequest
> 
> private const val RANDOM_SEED = 1
> ```

nit: RANDOM_SEED looks unused.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/PopulationsServiceTest.kt` line 244 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1268#-NgQj05c4bwbojFFqj_K:-NgQj05c4bwbojFFqj_L:bdkjv8d) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/89c4474f63e60cbae91b1c33b0fd093718d01152/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/PopulationsServiceTest.kt#L244)):*
> ```Kotlin
>         population {
>           externalDataProviderId = dataProvider.externalDataProviderId
>           externalDataProviderId = dataProvider.externalDataProviderId
> ```

nit: line is duplicated


<!-- Sent from Reviewable.io -->

2023-10-11 19:48 UTC, merged