Implement Internal Metric Calculation Specs Service
world-federation-of-advertisers/cross-media-measurement pull request #1278
Opened 2023-10-04 22:01 UTC by tristanvuong2021

2023-10-04 22:01 UTC, wfa-reviewable commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1278)
<!-- Reviewable:end -->

2023-10-04 22:51 UTC, SanjayVas reviewed
It's very odd to do the internal service changes without the DB schema updates as you're basically making an assumption about what the DB schema will be.

My instinct is to add the new specs table and the internal service for that table w/tests, and then future PRs can go about integrating Reports with the new specs table/service.

> Reviewed 1 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1278#-:-Nfws55E2EKyntgLPGtb:b-3mnwfo)* status: 1 of 17 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-10-04 23:39 UTC, tristanvuong2021 reviewed
There is already a MetricCalculationSpecs table. What I could do is call it something like MetricCalculationSpecs2 then add a TODO to change it once everything else is ready.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1278#-:-Nfx2k785jh5pXj1R25f:bkhetro)* status: 1 of 17 files reviewed, all discussions resolved (waiting on @SanjayVas)



<!-- Sent from Reviewable.io -->

2023-10-05 15:06 UTC, kungfucraig requested changes
Do you have a proto for the external service yet?

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1278#-:-Ng-Mwv9BJO0f-VSHxK2:b-t8551p)* status: 1 of 17 files reviewed, all discussions resolved (waiting on @SanjayVas)



<!-- Sent from Reviewable.io -->

2023-10-05 16:56 UTC, tristanvuong2021 reviewed
I don't. I will do it now then have 2 PRs out for this, one for public and one for internal.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1278#-:-Ng-l8LsDisOVdO2iGkd:b-ud7zqf)* status: 1 of 17 files reviewed, all discussions resolved (waiting on @SanjayVas)



<!-- Sent from Reviewable.io -->

2023-10-05 21:40 UTC, SanjayVas reviewed
> There is already a MetricCalculationSpecs table. What I could do is call it something like MetricCalculationSpecs2 then add a TODO to change it once everything else is ready.

Oh. And that existing one has each row as a child of Report. I'm honestly thinking it might be best to bite the bullet and do one big PR for the whole breaking change, including the schema update to drop the existing MetricCalculationSpecs and add the new one.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1278#-:-Ng0lG145Me8ro_OXPlY:b4iw8eh)* status: 1 of 17 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2023-10-30 21:39 UTC, SanjayVas requested changes
> Reviewed 10 of 52 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1278)* status: 11 of 54 files reviewed, 5 unresolved discussions (waiting on @tristanvuong2021)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1278#-Ni1WT8UANCifWtDcrfK:-Ni1WT8UANCifWtDcrfL:bmzjk4n) (no related file):*
Indicate in the PR description that this mutates existing Liquibase changesets, meaning the DB needs to be dropped and re-created.

___
___
*[`src/main/proto/wfa/measurement/internal/reporting/v2/metric_calculation_specs_service.proto` line 32 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1278#-Ni1VehRCNIQUzoRzFfH:-Ni1VehRCNIQUzoRzFfI:b-1mj7ea) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cdbe3e1b98feed2b2d2803b746b58e94811a2c63/src/main/proto/wfa/measurement/internal/reporting/v2/metric_calculation_specs_service.proto#L32)):*
> ```proto
>       returns (MetricCalculationSpec);
> 
>   rpc ListMetricCalculationSpecs(ListMetricCalculationSpecsRequest)
> ```

Document the method so you can indicate the order of responses, as that is linked to the pagination implementation.
___
*[`src/main/proto/wfa/measurement/internal/reporting/v2/metric_calculation_specs_service.proto` line 52 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1278#-Ni1V0eC5D079urzs6xc:-Ni1V0eC5D079urzs6xd:bi5xq3a) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cdbe3e1b98feed2b2d2803b746b58e94811a2c63/src/main/proto/wfa/measurement/internal/reporting/v2/metric_calculation_specs_service.proto#L52)):*
> ```proto
> 
> message ListMetricCalculationSpecsRequest {
>   message Filter {
> ```

nit: The use of a Filter message here is a little confusing since we don't use it to implement filtering as per the public API. Maybe just separate fields for the parent CMMS MC ID and the after key?
___
*[`src/main/proto/wfa/measurement/internal/reporting/v2/metric_calculation_specs_service.proto` line 64 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1278#-Ni1Uh6DEhgXLwckcvS3:-Ni1Uh6EBQOyyBmO0id-:b-hlgoay) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cdbe3e1b98feed2b2d2803b746b58e94811a2c63/src/main/proto/wfa/measurement/internal/reporting/v2/metric_calculation_specs_service.proto#L64)):*
> ```proto
> 
> message ListMetricCalculationSpecsResponse {
>   repeated MetricCalculationSpec metric_calculation_specs = 1;
> ```

If we're doing List methods with a specific response rather than streaming individual entities for the internal API now, we don't need to deal with the limits of the streaming API. e.g. we can handle page tokens in the internal method, or at least include a separate boolean field in the response to indicate whether there are more results (as opposed to having to request one extra element that we throw away).
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric_calculation_spec.proto` line 47 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1278#-Ni1TCF4803Zy352N6qT:-Ni1TCF4803Zy352N6qU:b-e2fp28) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cdbe3e1b98feed2b2d2803b746b58e94811a2c63/src/main/proto/wfa/measurement/reporting/v2alpha/metric_calculation_spec.proto#L47)):*
> ```proto
> 
>   // A collection of metrics.
>   repeated MetricSpec metric_specs = 3 [(google.api.field_behavior) = REQUIRED];
> ```

This should also be IMMUTABLE.


<!-- Sent from Reviewable.io -->

2023-10-31 14:45 UTC, kungfucraig reviewed
> Reviewed 2 of 52 files at r4.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1278)* status: 11 of 54 files reviewed, 5 unresolved discussions (waiting on @tristanvuong2021)



<!-- Sent from Reviewable.io -->

2023-10-31 21:48 UTC, tristanvuong2021 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1278)* status: 9 of 56 files reviewed, 4 unresolved discussions (waiting on @kungfucraig and @SanjayVas)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1278#-Ni1WT8UANCifWtDcrfK:-Ni6MtLP7NOV2OYoaP-m:b-896fix) (no related file):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Indicate in the PR description that this mutates existing Liquibase changesets, meaning the DB needs to be dropped and re-created.
</blockquote></details>

Done.

___
___
*[`src/main/proto/wfa/measurement/internal/reporting/v2/metric_calculation_specs_service.proto` line 32 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1278#-Ni1VehRCNIQUzoRzFfH:-Ni6MFj-EqlZOPN8plaF:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cdbe3e1b98feed2b2d2803b746b58e94811a2c63/src/main/proto/wfa/measurement/internal/reporting/v2/metric_calculation_specs_service.proto#L32)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Document the method so you can indicate the order of responses, as that is linked to the pagination implementation.
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/internal/reporting/v2/metric_calculation_specs_service.proto` line 64 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1278#-Ni1Uh6DEhgXLwckcvS3:-Ni6hU4k-5OH7191C6Jo:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cdbe3e1b98feed2b2d2803b746b58e94811a2c63/src/main/proto/wfa/measurement/internal/reporting/v2/metric_calculation_specs_service.proto#L64)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

If we're doing List methods with a specific response rather than streaming individual entities for the internal API now, we don't need to deal with the limits of the streaming API. e.g. we can handle page tokens in the internal method, or at least include a separate boolean field in the response to indicate whether there are more results (as opposed to having to request one extra element that we throw away).
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric_calculation_spec.proto` line 47 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1278#-Ni1TCF4803Zy352N6qT:-Ni6MbsJ1PLmwt7KSbII:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cdbe3e1b98feed2b2d2803b746b58e94811a2c63/src/main/proto/wfa/measurement/reporting/v2alpha/metric_calculation_spec.proto#L47)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This should also be IMMUTABLE.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-11-01 00:30 UTC, SanjayVas requested changes
> Reviewed 7 of 52 files at r4, 4 of 9 files at r6, 3 of 11 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1278)* status: 22 of 56 files reviewed, 6 unresolved discussions (waiting on @kungfucraig and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/MetricCalculationSpecReader.kt` line 63 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1278#-Ni7BsoF6z7oC4iJiKt-:-Ni7BsoF6z7oC4iJiKt0:b-c1657d) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2bb9da70a298e097bd91935ce8590c765eebf6af/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/MetricCalculationSpecReader.kt#L63)):*
> ```Kotlin
>   ): Result? {
>     val sql =
>       StringBuilder(
> ```

What do we gain by using a StringBuilder here? We're concatenating the strings already before passing to its constructor and never calling `append`.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateMetricCalculationSpec.kt` line 43 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1278#-Ni7HNZQ5SHCjgmfwT-A:-Ni7HNZR97t6AUSHfyzc:b941c13) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2bb9da70a298e097bd91935ce8590c765eebf6af/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateMetricCalculationSpec.kt#L43)):*
> ```Kotlin
>     val externalMetricCalculationSpecId = request.externalMetricCalculationSpecId
> 
>     val measurementConsumerId =
> ```

nit: explicit types
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateMetricCalculationSpec.kt` line 62 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1278#-Ni7HSK7A3fSSnXFKRSk:-Ni7HSK80aPTDW5MvRlh:b941c13) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2bb9da70a298e097bd91935ce8590c765eebf6af/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateMetricCalculationSpec.kt#L62)):*
> ```Kotlin
>     }
> 
>     val metricCalculationSpecId = idGenerator.generateInternalId()
> ```

nit: explicit types
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateReportSchedule.kt` line 106 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1278#-Ni79eag0urGHEs1lQzt:-Ni79eag0urGHEs1lQzu:b-msoorp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2bb9da70a298e097bd91935ce8590c765eebf6af/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateReportSchedule.kt#L106)):*
> ```Kotlin
>         externalMetricCalculationSpecIds += it.externalMetricCalculationSpecId
>       }
>     }
> ```

nit: avoid unnecessary mutability (`buildSet` was added in Kotlin 1.6 and we're on 1.8 now)



_Suggestion:_
```Kotlin
    val externalMetricCalculationSpecIds: Set<String> = buildSet {
      for (reportingMetricCalculationSpec in
        reportSchedule.details.reportTemplate.reportingMetricEntriesMap.values) {
        reportingMetricCalculationSpec.metricCalculationSpecReportingMetricsList.forEach {
          add(it.externalMetricCalculationSpecId)
        }
      }
    }
```
___
*[`src/main/proto/wfa/measurement/internal/reporting/v2/metric_calculation_specs_service.proto` line 32 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1278#-Ni1VehRCNIQUzoRzFfH:-Ni6xUAl50XFgDNLWQom:b-15g0mh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cdbe3e1b98feed2b2d2803b746b58e94811a2c63/src/main/proto/wfa/measurement/internal/reporting/v2/metric_calculation_specs_service.proto#L32)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't see any method documentation added here?
___
*[`src/main/proto/wfa/measurement/internal/reporting/v2/metric_calculation_specs_service.proto` line 62 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1278#-Ni6x6ZaBfdCO_FzWBco:-Ni6x6ZaBfdCO_FzWBcp:bibch2m) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2bb9da70a298e097bd91935ce8590c765eebf6af/src/main/proto/wfa/measurement/internal/reporting/v2/metric_calculation_specs_service.proto#L62)):*
> ```proto
>   // Ordered by `external_metric_calculation_spec_id`, ascending.
>   repeated MetricCalculationSpec metric_calculation_specs = 1;
>   bool hasMoreThanLimit = 2;
> ```

Use snake_case. Also avoid the `has` prefix for boolean proto fields.



_Suggestion:_
```proto
// Whether there would have been more results returned if not for the request limit.
bool limited = 2;
```


<!-- Sent from Reviewable.io -->

2023-11-01 18:42 UTC, tristanvuong2021 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1278)* status: 15 of 60 files reviewed, 3 unresolved discussions (waiting on @kungfucraig and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/MetricCalculationSpecReader.kt` line 63 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1278#-Ni7BsoF6z7oC4iJiKt-:-NiBBOe18RgHBGHEYIPP:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2bb9da70a298e097bd91935ce8590c765eebf6af/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/MetricCalculationSpecReader.kt#L63)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

What do we gain by using a StringBuilder here? We're concatenating the strings already before passing to its constructor and never calling `append`.
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/internal/reporting/v2/metric_calculation_specs_service.proto` line 32 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1278#-Ni1VehRCNIQUzoRzFfH:-NiB0P6t-NbXfzv9EOjx:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cdbe3e1b98feed2b2d2803b746b58e94811a2c63/src/main/proto/wfa/measurement/internal/reporting/v2/metric_calculation_specs_service.proto#L32)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I don't see any method documentation added here?
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/internal/reporting/v2/metric_calculation_specs_service.proto` line 62 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1278#-Ni6x6ZaBfdCO_FzWBco:-NiB-9P43Lf0TP0w5fOx:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2bb9da70a298e097bd91935ce8590c765eebf6af/src/main/proto/wfa/measurement/internal/reporting/v2/metric_calculation_specs_service.proto#L62)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Use snake_case. Also avoid the `has` prefix for boolean proto fields.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-11-02 19:40 UTC, kungfucraig approved these changes
The external API definitions lgtm. I'm going to skip reviewing the rest.

> Reviewed 1 of 52 files at r4, 1 of 11 files at r7.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1278#-:-NiGXdpj9o6dKTh7hm_B:b-r6qigb)* status: 15 of 60 files reviewed, 4 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric_calculation_spec.proto` line 74 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1278#-NiGY3i6DPw8cO3Lm56U:-NiGY3i6DPw8cO3Lm56V:b-vi80rc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a8103f2d93c773c434b8de169303bd708a69d436/src/main/proto/wfa/measurement/reporting/v2alpha/metric_calculation_spec.proto#L74)):*
> ```proto
>   repeated Grouping groupings = 5 [(google.api.field_behavior) = IMMUTABLE];
> 
>   // Whether the results for a given time interval is cumulative with those of
> ```

Can you add that the time interval definitions are part of Report?


<!-- Sent from Reviewable.io -->

2023-11-06 20:37 UTC, SanjayVas requested changes
> Reviewed 1 of 17 files at r1, 1 of 9 files at r2, 6 of 52 files at r4, 2 of 9 files at r6, 4 of 11 files at r7, 9 of 15 files at r9, 2 of 3 files at r10, 2 of 3 files at r12, 6 of 11 files at r13, 4 of 4 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1278)* status: 50 of 60 files reviewed, 10 unresolved discussions (waiting on @kungfucraig and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/MetricCalculationSpecReader.kt` line 63 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1278#-Ni7BsoF6z7oC4iJiKt-:-NiaGCCKCaIPruSKtYPq:b8i8368) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2bb9da70a298e097bd91935ce8590c765eebf6af/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/MetricCalculationSpecReader.kt#L63)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I still see the StringBuilder in use here.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/ReportReader.kt` line 132 at r14](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1278#-NiaHWfhAwlATsd-j1Dy:-NiaHWfiA60jyQcppzQb:b-wmh1jd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6ffd2cf410fb18add9872c49139175385f9c0ce3/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/ReportReader.kt#L132)):*
> ```Kotlin
>             AND CreateReportRequestId = $2
>           """
>         )
> ```

Use of StringBuilder here doesn't help much with efficiency and just hurts readability. You mainly want to use StringBuilder when doing multiple concatenations (e.g. in a loop or with conditionals). This could just use a single multiline string with a template expression.



_Suggestion:_
```Kotlin
    val sql =
      """
      FROM
        MeasurementConsumers
        JOIN Reports USING(MeasurementConsumerId)
        $baseSqlJoins
      WHERE
        Reports.MeasurementConsumerId = $1
        AND CreateReportRequestId = $2
      """
        .trimIndent()
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/ReportReader.kt` line 148 at r14](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1278#-NiaIea65YU5OA9y9x71:-NiaIea79JYoHWX6cAcH:bpxhdbq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6ffd2cf410fb18add9872c49139175385f9c0ce3/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/ReportReader.kt#L148)):*
> ```Kotlin
>   ): Result? {
>     val sql =
>       StringBuilder(baseSqlSelect)
> ```

Same here re: StringBuilder
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/ReportReader.kt` line 211 at r14](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1278#-NiaIsVD2htUQ4snE-ZI:-NiaIiO_DxbsRNWJNm6e:bmtqk2x) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6ffd2cf410fb18add9872c49139175385f9c0ce3/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/ReportReader.kt#L211)):*
> ```Kotlin
>     val sql =
>       StringBuilder(baseSqlSelect)
>         .append("\n")
> ```

Use `appendLine` extension rather than appending newline characters manually.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/ReportScheduleIterationReader.kt` line 86 at r14](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1278#-NiaIyO10nf54oFoezwe:-NiaIyO10nf54oFoezwf:b9jnluq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6ffd2cf410fb18add9872c49139175385f9c0ce3/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/ReportScheduleIterationReader.kt#L86)):*
> ```Kotlin
>          AND ExternalReportScheduleId = $2
>          AND ExternalReportScheduleIterationId = $3
>         """
> ```

Keep the `trimIndent()` on all of these multiline strings to avoid introducing unintentional leading whitespace.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricCalculationSpecKey.kt` line 28 at r14](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1278#-NiaJovz1wWMJHw6FjYK:-NiaJovz1wWMJHw6FjYL:b-zicxt9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6ffd2cf410fb18add9872c49139175385f9c0ce3/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricCalculationSpecKey.kt#L28)):*
> ```Kotlin
> 
> /** [ResourceKey] of a MetricCalculationSpec. */
> data class MetricCalculationSpecKey(
> ```

If you add a `MeasurementConsumerKey` and have this implement `ChildResourceKey`, then you can simplify auth checks by just checking that the principal resource key matches the `parentKey`.

See src/main/kotlin/org/wfanet/measurement/api/v2alpha/DataProviderRecurringExchangeKey.kt for an example.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/v2/MetricCalculationSpecsServiceTest.kt` line 107 at r14](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1278#-NiaL0FTBPXJ6slg0C80:-NiaL0FTBPXJ6slg0C81:b45h) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6ffd2cf410fb18add9872c49139175385f9c0ce3/src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/v2/MetricCalculationSpecsServiceTest.kt#L107)):*
> ```Kotlin
> 
>   @Test
>   fun `createReportSchedule throws INVALID_ARGUMENT when missing external ID`() = runBlocking {
> ```





_Suggestion:_
```Kotlin
createMetricCalculationSpec
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/v2/MetricCalculationSpecsServiceTest.kt` line 124 at r14](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1278#-NiaL339-ZnVbqkKFdcQ:-NiaL339-ZnVbqkKFdcR:undefined) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6ffd2cf410fb18add9872c49139175385f9c0ce3/src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/v2/MetricCalculationSpecsServiceTest.kt#L124)):*
> ```Kotlin
> 
>   @Test
>   fun `createReportSchedule throws INVALID_ARGUMENT when no reporting metric entries`() =
> ```





_Suggestion:_
```Kotlin
createMetricCalculationSpec
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/v2/MetricCalculationSpecsServiceTest.kt` line 296 at r14](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1278#-NiaL7k72HpZF1ErSTeq:-NiaL7k72HpZF1ErSTer:b-837s95) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6ffd2cf410fb18add9872c49139175385f9c0ce3/src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/v2/MetricCalculationSpecsServiceTest.kt#L296)):*
> ```Kotlin
> 
>   @Test
>   fun `listReportSchedules lists 1 schedule when after id is specified`() = runBlocking {
> ```

MetricCalculationSpecs, not schedules


<!-- Sent from Reviewable.io -->

2023-11-07 21:59 UTC, tristanvuong2021 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1278)* status: 37 of 70 files reviewed, 10 unresolved discussions (waiting on @kungfucraig and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/MetricCalculationSpecReader.kt` line 63 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1278#-Ni7BsoF6z7oC4iJiKt-:-Niejtce6mNGHcS4LMNH:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2bb9da70a298e097bd91935ce8590c765eebf6af/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/MetricCalculationSpecReader.kt#L63)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I still see the StringBuilder in use here.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/ReportReader.kt` line 132 at r14](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1278#-NiaHWfhAwlATsd-j1Dy:-NietBdYB-E8UOYOxbJz:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bd043fb939b6e98c9d0f951c2b6b7bfc855c7c05/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/ReportReader.kt#L132)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Use of StringBuilder here doesn't help much with efficiency and just hurts readability. You mainly want to use StringBuilder when doing multiple concatenations (e.g. in a loop or with conditionals). This could just use a single multiline string with a template expression.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/ReportReader.kt` line 148 at r14](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1278#-NiaIea65YU5OA9y9x71:-NietC4w8dyvTLyGmHf8:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bd043fb939b6e98c9d0f951c2b6b7bfc855c7c05/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/ReportReader.kt#L148)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Same here re: StringBuilder
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/ReportReader.kt` line 211 at r14](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1278#-NiaIsVD2htUQ4snE-ZI:-NietJPC2nQ7zjm88hgA:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bd043fb939b6e98c9d0f951c2b6b7bfc855c7c05/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/ReportReader.kt#L211)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Use `appendLine` extension rather than appending newline characters manually.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/ReportScheduleIterationReader.kt` line 86 at r14](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1278#-NiaIyO10nf54oFoezwe:-NietLEA3_xg4a5Cw6ZX:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bd043fb939b6e98c9d0f951c2b6b7bfc855c7c05/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/ReportScheduleIterationReader.kt#L86)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Keep the `trimIndent()` on all of these multiline strings to avoid introducing unintentional leading whitespace.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricCalculationSpecKey.kt` line 28 at r14](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1278#-NiaJovz1wWMJHw6FjYK:-NifLfUK6s0rHiO3UBTh:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bd043fb939b6e98c9d0f951c2b6b7bfc855c7c05/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricCalculationSpecKey.kt#L28)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

If you add a `MeasurementConsumerKey` and have this implement `ChildResourceKey`, then you can simplify auth checks by just checking that the principal resource key matches the `parentKey`.

See src/main/kotlin/org/wfanet/measurement/api/v2alpha/DataProviderRecurringExchangeKey.kt for an example.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/v2/MetricCalculationSpecsServiceTest.kt` line 107 at r14](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1278#-NiaL0FTBPXJ6slg0C80:-NiexBh-AfNuIlSJDwMd:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bd043fb939b6e98c9d0f951c2b6b7bfc855c7c05/src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/v2/MetricCalculationSpecsServiceTest.kt#L107)):*
> ```Kotlin
> 
>   @Test
>   fun `createReportSchedule throws INVALID_ARGUMENT when missing external ID`() = runBlocking {
> ```

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/v2/MetricCalculationSpecsServiceTest.kt` line 124 at r14](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1278#-NiaL339-ZnVbqkKFdcQ:-NiexCDTEQcReBRK64V1:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bd043fb939b6e98c9d0f951c2b6b7bfc855c7c05/src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/v2/MetricCalculationSpecsServiceTest.kt#L124)):*
> ```Kotlin
> 
>   @Test
>   fun `createReportSchedule throws INVALID_ARGUMENT when no reporting metric entries`() =
> ```

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/v2/MetricCalculationSpecsServiceTest.kt` line 296 at r14](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1278#-NiaL7k72HpZF1ErSTeq:-NiexK69DY1EfDYOYXZ-:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bd043fb939b6e98c9d0f951c2b6b7bfc855c7c05/src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/v2/MetricCalculationSpecsServiceTest.kt#L296)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

MetricCalculationSpecs, not schedules
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric_calculation_spec.proto` line 74 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1278#-NiGY3i6DPw8cO3Lm56U:-Niexq81AHx6F9dpbXHc:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a8103f2d93c773c434b8de169303bd708a69d436/src/main/proto/wfa/measurement/reporting/v2alpha/metric_calculation_spec.proto#L74)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Can you add that the time interval definitions are part of Report?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-11-07 22:44 UTC, SanjayVas approved these changes
> Reviewed 7 of 52 files at r4, 1 of 9 files at r6, 1 of 15 files at r9, 2 of 11 files at r13, 10 of 23 files at r15, 13 of 13 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1278)* status: all files reviewed, 1 unresolved discussion (waiting on @kungfucraig)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/ReportReader.kt` line 211 at r14](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1278#-NiaIsVD2htUQ4snE-ZI:-NifwlcG4LKvNr7STjFZ:b-b0ilqw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bd043fb939b6e98c9d0f951c2b6b7bfc855c7c05/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/ReportReader.kt#L211)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

nit: I think you misunderstood this slightly. There's an `appendLine` extension that takes in a string, which appends that string followed by the end of line sequence. Instead of `append(str).appendLine()` you can just have `appendLine(str)`.


<!-- Sent from Reviewable.io -->

2023-11-08 16:04 UTC, kungfucraig approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1278)* status: 69 of 70 files reviewed, all discussions resolved (waiting on @SanjayVas)



<!-- Sent from Reviewable.io -->

2023-11-10 14:44 UTC, stevenwarejones approved these changes
> Reviewed 1 of 17 files at r1, 1 of 9 files at r2, 22 of 52 files at r4, 5 of 9 files at r6, 4 of 11 files at r7, 4 of 15 files at r9, 2 of 3 files at r12, 5 of 11 files at r13, 3 of 4 files at r14, 10 of 23 files at r15, 12 of 13 files at r16, 1 of 1 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1278)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)



<!-- Sent from Reviewable.io -->

2023-11-11 00:52 UTC, merged