Link public and internal APIs for Populations service. Write tests.
world-federation-of-advertisers/cross-media-measurement pull request #1291
Opened 2023-10-12 17:46 UTC by jojijac0b

Link public and internal APIs

2023-10-12 17:46 UTC, wfa-reviewable commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1291)
<!-- Reviewable:end -->

2023-10-12 18:02 UTC, stevenwarejones requested changes
> Reviewed 6 of 12 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1291)* status: all files reviewed, 3 unresolved discussions (waiting on @jojijac0b, @Marco-Premier, and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/PopulationsService.kt` line 103 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1291#-Ng_1FDm5ha-iW9TgDR_:-Ng_1FDm5ha-iW9TgDRa:bp2er4s) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6ea53b0aceef0537159bf2fcae46265b65041ebf/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/PopulationsService.kt#L103)):*
> ```Kotlin
>         }
>       }
>       is MeasurementConsumerPrincipal -> {}
> ```

MCs shouldn't have access
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/PopulationsService.kt` line 104 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1291#-Ng_1I151uUgAPNrCMPu:-Ng_1I151uUgAPNrCMPv:b-7so6xx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6ea53b0aceef0537159bf2fcae46265b65041ebf/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/PopulationsService.kt#L104)):*
> ```Kotlin
>       }
>       is MeasurementConsumerPrincipal -> {}
>       is ModelProviderPrincipal -> {}
> ```

i think for now all MPs should have access to the population data. But we may need to refine this in the future. @SanjayVas - not sure what you'd suggest about how a population provider allow access to the population to only certain MPs.... add a new field of repeated ModelProvider to the Population resource? That seems a little messy to manage it that way.

Either way, I think this is fine as-is and we can refine this later
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/PopulationsService.kt` line 138 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1291#-Ng_1eqX20U92crOl-Ur:-Ng_1eqX20U92crOl-Us:b-7ropln) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6ea53b0aceef0537159bf2fcae46265b65041ebf/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/PopulationsService.kt#L138)):*
> ```Kotlin
>         }
>       }
>       is MeasurementConsumerPrincipal -> {}
> ```

ditto
___
*[`src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/PopulationsServiceTest.kt` line 213 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1291#-Ng_2-Uc1VWmHFwLhaUX:-Ng_2-Uc1VWmHFwLhaUY:b-bllhj0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6ea53b0aceef0537159bf2fcae46265b65041ebf/src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/PopulationsServiceTest.kt#L213)):*
> ```Kotlin
> 
>   @Test
>   fun `getPopulation returns population when measurement consumer caller is found`() {
> ```

I think this should throw an error


<!-- Sent from Reviewable.io -->

2023-10-12 18:43 UTC, stevenwarejones reviewed
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1291)* status: all files reviewed, 2 unresolved discussions (waiting on @jojijac0b, @Marco-Premier, and @SanjayVas)



<!-- Sent from Reviewable.io -->

2023-10-12 18:54 UTC, jojijac0b reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1291)* status: 11 of 12 files reviewed, 2 unresolved discussions (waiting on @Marco-Premier, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/PopulationsService.kt` line 103 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1291#-Ng_1FDm5ha-iW9TgDR_:-Ng_EQSC6PCnOmo6mBmx:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6ea53b0aceef0537159bf2fcae46265b65041ebf/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/PopulationsService.kt#L103)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

MCs shouldn't have access
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/PopulationsService.kt` line 138 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1291#-Ng_1eqX20U92crOl-Ur:-Ng_EQ4P8LhAjMaNZaYf:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6ea53b0aceef0537159bf2fcae46265b65041ebf/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/PopulationsService.kt#L138)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-12 19:49 UTC, SanjayVas requested changes
> Reviewed 6 of 12 files at r1, 4 of 6 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1291)* status: 11 of 12 files reviewed, 9 unresolved discussions (waiting on @jojijac0b, @Marco-Premier, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/PopulationKey.kt` line 22 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1291#-Ng_9sTG5RPFdQqxRcct:-Ng_9sTG5RPFdQqxRccu:b-smkiqj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fd0e8d42ce2043c912737df46ce566f6af8557a0/src/main/kotlin/org/wfanet/measurement/api/v2alpha/PopulationKey.kt#L22)):*
> ```Kotlin
> import org.wfanet.measurement.common.api.ResourceKey
> 
> private val parser = ResourceNameParser("dataProviders/{data_provider}/populations/{population}")
> ```

Move `parser` into the companion object. See the [style guide](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/docs/code-style.md#kotlin).

Some of our existing ResourceKey impls do not follow this, but newer ones do.
___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/PopulationKey.kt` line 25 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1291#-Ng_BCGOEd1Fbj0tPAo1:-Ng_BCGOEd1Fbj0tPAo2:b-dhmyrk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fd0e8d42ce2043c912737df46ce566f6af8557a0/src/main/kotlin/org/wfanet/measurement/api/v2alpha/PopulationKey.kt#L25)):*
> ```Kotlin
> 
> /** [ResourceKey] of a Model Suite. */
> data class PopulationKey(val dataProviderId: String, val populationId: String) : ResourceKey {
> ```

Implement ChildResourceKey, with the parent key as the val in the primary constructor. You can then add a val for `dataProviderId` that just delegates to the parent key, with a secondary constructor that just takes in the IDs. See `DataProviderRecurringExchangeKey` for an example.



_Suggestion:_
```Kotlin
ChildResourceKey
```
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/BUILD.bazel` line 438 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1291#-Ng_CKO2AetFCjUgUWzp:-Ng_CKO2AetFCjUgUWzq:b-82w2cj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fd0e8d42ce2043c912737df46ce566f6af8557a0/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/BUILD.bazel#L438)):*
> ```Starlark
>     deps = [
>         ":proto_conversions",
>         "//src/main/kotlin/org/wfanet/measurement/api:public_api_version",
> ```

I'm not seeing this dep used in the the source file.

Make sure that `deps` contains only the deps that are directly referenced by your code (while not relying on transitive deps). See the [style guide](https://bazel.build/build/style-guide#dependencies).



_Code quote:_
```Starlark
"//src/main/kotlin/org/wfanet/measurement/api:public_api_version",
```
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/PopulationsService.kt` line 103 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1291#-Ng_1FDm5ha-iW9TgDR_:-Ng_FoEB3D7d9aYf7obq:b-1egsfj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6ea53b0aceef0537159bf2fcae46265b65041ebf/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/PopulationsService.kt#L103)):*
<details><summary><i>Previously, jojijac0b wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Is that right? It looks like in the MeasurementSpec the MC specifies the ModeLine even for POPULATION Measurements. I would expect a reference to the Population, in which case the MC would need to be able to read Population resources so it figure out which one to reference.

What was the reason for specifying ModelLine rather than Population for POPULATION MeasurementSpec? Are POPULATION Measurements intended to take something about the rollout into account?
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/PopulationsService.kt` line 104 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1291#-Ng_1I151uUgAPNrCMPu:-Ng_Kh_f6Jy0P3PH2Qn2:boln547) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6ea53b0aceef0537159bf2fcae46265b65041ebf/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/PopulationsService.kt#L104)):*
> add a new field of repeated ModelProvider to the Population resource?

That actually seems reasonable if you want the PDP to control which MPs are allowed to use it. We'd check access to the Population both here and in CreateModelRelease.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/PopulationsService.kt` line 97 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1291#-Ng_EoQn-liiLkCkYmWI:-Ng_EoQn-liiLkCkYmWJ:bxx66kx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7791a080949e9abf1bcb6ebfb6f6c9fa9f5f3bd6/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/PopulationsService.kt#L97)):*
> ```Kotlin
>       }
> 
>     when (val principal: MeasurementPrincipal = principalFromCurrentContext) {
> ```

Follow [AIP-211](https://google.aip.dev/211). We haven't yet updated all of our service implementations to handle this properly yet, but many have been updated. See src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepsService.kt for an example.

Specifically, the format of the error message should be  "Permission `{p}` denied on resource `{r}` (or it might not exist)." Note that for List, what you're operating on is the resource collection.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/PopulationsService.kt` line 99 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1291#-Ng_FU1v9KzHF4GqfsN_:-Ng_FU1v9KzHF4GqfsNa:bfqw2zg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7791a080949e9abf1bcb6ebfb6f6c9fa9f5f3bd6/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/PopulationsService.kt#L99)):*
> ```Kotlin
>     when (val principal: MeasurementPrincipal = principalFromCurrentContext) {
>       is DataProviderPrincipal -> {
>         if (principal.resourceKey.dataProviderId != key.dataProviderId) {
> ```

Utilize the fact that `PopulationKey` should implement `ChildResourceKey`



_Suggestion:_
```Kotlin
principal.resourceKey != key.parentKey
```
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt` line 838 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1291#-Ng_OHC330W_-dDqgDE2:-Ng_OHC330W_-dDqgDE3:bu77ptv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7791a080949e9abf1bcb6ebfb6f6c9fa9f5f3bd6/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt#L838)):*
> ```Kotlin
> /** Converts a public [Population] to an internal [InternalPopulation] */
> fun Population.toInternal(dataProviderKey: DataProviderKey): InternalPopulation {
>   val publicPopulation = this
> ```

nit: copy naming pattern from other methods



_Suggestion:_
```Kotlin
source
```
___
*[`src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/PopulationsServiceTest.kt` line 390 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1291#-Ng_Oa1S54ypAkMYEq4t:-Ng_Oa1S54ypAkMYEq4u:b-jbnidv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7791a080949e9abf1bcb6ebfb6f6c9fa9f5f3bd6/src/test/kotlin/org/wfanet/measuremen [...]

2023-10-12 21:52 UTC, stevenwarejones requested changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1291)* status: all files reviewed, 8 unresolved discussions (waiting on @jojijac0b, @kungfucraig, and @Marco-Premier)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/PopulationsService.kt` line 103 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1291#-Ng_1FDm5ha-iW9TgDR_:-Ng_rNvN3moyZ1DydxY0:b-nohp1d) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6ea53b0aceef0537159bf2fcae46265b65041ebf/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/PopulationsService.kt#L103)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Is that right? It looks like in the MeasurementSpec the MC specifies the ModeLine even for POPULATION Measurements. I would expect a reference to the Population, in which case the MC would need to be able to read Population resources so it figure out which one to reference.

What was the reason for specifying ModelLine rather than Population for POPULATION MeasurementSpec? Are POPULATION Measurements intended to take something about the rollout into account?
</blockquote></details>

In the current design, the MC only needs specify a ModelLine whether specifying an event or a population measurement.

The Population Data Provider can then query that ModelLine to see which population it refers to and thus fulfill the requisition. The MC need not know the population resource that was used.

cc: @kungfucraig @Marco-Premier 
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/PopulationsService.kt` line 104 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1291#-Ng_1I151uUgAPNrCMPu:-Ng_rojf0GJ4z5Npjr4w:bcr9lgs) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6ea53b0aceef0537159bf2fcae46265b65041ebf/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/PopulationsService.kt#L104)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> add a new field of repeated ModelProvider to the Population resource?

That actually seems reasonable if you want the PDP to control which MPs are allowed to use it. We'd check access to the Population both here and in CreateModelRelease.
</blockquote></details>

yeah - maybe add that as a todo 
```
// TODO(joji...) Once the population resource has a field to limit access to only certain MPs, update this permission as well.
```



<!-- Sent from Reviewable.io -->

2023-10-24 23:13 UTC, jojijac0b reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1291)* status: 7 of 12 files reviewed, 7 unresolved discussions (waiting on @kungfucraig, @Marco-Premier, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/PopulationKey.kt` line 22 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1291#-Ng_9sTG5RPFdQqxRcct:-Nh30QqwA6_FRy62VpT2:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fd0e8d42ce2043c912737df46ce566f6af8557a0/src/main/kotlin/org/wfanet/measurement/api/v2alpha/PopulationKey.kt#L22)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Move `parser` into the companion object. See the [style guide](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/docs/code-style.md#kotlin).

Some of our existing ResourceKey impls do not follow this, but newer ones do.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/PopulationKey.kt` line 25 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1291#-Ng_BCGOEd1Fbj0tPAo1:-Nh8fGVp3PAfUHJ1VJu6:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fd0e8d42ce2043c912737df46ce566f6af8557a0/src/main/kotlin/org/wfanet/measurement/api/v2alpha/PopulationKey.kt#L25)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Implement ChildResourceKey, with the parent key as the val in the primary constructor. You can then add a val for `dataProviderId` that just delegates to the parent key, with a secondary constructor that just takes in the IDs. See `DataProviderRecurringExchangeKey` for an example.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/BUILD.bazel` line 438 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1291#-Ng_CKO2AetFCjUgUWzp:-Nh30j6EA1WX69FKfGb2:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fd0e8d42ce2043c912737df46ce566f6af8557a0/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/BUILD.bazel#L438)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I'm not seeing this dep used in the the source file.

Make sure that `deps` contains only the deps that are directly referenced by your code (while not relying on transitive deps). See the [style guide](https://bazel.build/build/style-guide#dependencies).
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/PopulationsService.kt` line 104 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1291#-Ng_1I151uUgAPNrCMPu:-Nh8p-YR5iKIwqx-kOu-:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6ea53b0aceef0537159bf2fcae46265b65041ebf/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/PopulationsService.kt#L104)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

yeah - maybe add that as a todo 
```
// TODO(joji...) Once the population resource has a field to limit access to only certain MPs, update this permission as well.
```

</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/PopulationsService.kt` line 97 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1291#-Ng_EoQn-liiLkCkYmWI:-Nh8oJl6BLeKPVATf2NA:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7791a080949e9abf1bcb6ebfb6f6c9fa9f5f3bd6/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/PopulationsService.kt#L97)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Follow [AIP-211](https://google.aip.dev/211). We haven't yet updated all of our service implementations to handle this properly yet, but many have been updated. See src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepsService.kt for an example.

Specifically, the format of the error message should be  "Permission `{p}` denied on resource `{r}` (or it might not exist)." Note that for List, what you're operating on is the resource collection.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt` line 838 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1291#-Ng_OHC330W_-dDqgDE2:-Nh8p0dh35o8SklDp6K7:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7791a080949e9abf1bcb6ebfb6f6c9fa9f5f3bd6/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt#L838)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: copy naming pattern from other methods
</blockquote></details>

Done.
___
*[`src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/PopulationsServiceTest.kt` line 390 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1291#-Ng_Oa1S54ypAkMYEq4t:-NhYxfz-5hiQQunGI9TH:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7791a080949e9abf1bcb6ebfb6f6c9fa9f5f3bd6/src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/PopulationsServiceTest.kt#L390)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Add tests that verify the following pagination behaviors from [AIP-158](https://google.aip.dev/158):

1. The response has next_page_token when the internal response indicates that the result count > page_size.
2. The internal request is populated correctly when the request has a page token.
3. The method results in an INVALID_ARGUMENT status when a request for a subsequent page differs from the request from the previous page other than by page_size or page_token.
    * I'm not sure if your implementation actually handles this. See [the check in the ExchangeStepsService impl](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/82f6c90f37c5944e736b9674ca74e74a5fc87565/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepsService.kt#L222) as an example.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-24 23:54 UTC, stevenwarejones approved these changes
> Reviewed 5 of 5 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1291)* status: all files reviewed, 6 unresolved discussions (waiting on @jojijac0b, @Marco-Premier, and @SanjayVas)



<!-- Sent from Reviewable.io -->

2023-10-25 16:00 UTC, jojijac0b reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1291)* status: 11 of 12 files reviewed, 6 unresolved discussions (waiting on @Marco-Premier, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/PopulationsService.kt` line 99 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1291#-Ng_FU1v9KzHF4GqfsN_:-NhbZEc22oUq5HnDyYat:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7791a080949e9abf1bcb6ebfb6f6c9fa9f5f3bd6/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/PopulationsService.kt#L99)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Utilize the fact that `PopulationKey` should implement `ChildResourceKey`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-25 16:18 UTC, SanjayVas requested changes
> Reviewed 2 of 5 files at r7, 1 of 4 files at r9, 3 of 3 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1291)* status: all files reviewed, 6 unresolved discussions (waiting on @jojijac0b and @Marco-Premier)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/PopulationsService.kt` line 73 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1291#-Nhb_wH985OctUrdMy4o:-Nhb_wH985OctUrdMy4p:b858tr0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1f238f1b3cfe0fae49af00ad6beffb65cfda32ef/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/PopulationsService.kt#L73)):*
> ```Kotlin
> 
>   override suspend fun createPopulation(request: CreatePopulationRequest): Population {
>     fun permissionDeniedStatus() = Permission.CREATE.deniedStatus("${request.parent}")
> ```

CreatePopulation technically applies to the `populations` resource collection.



_Suggestion:_
```Kotlin
${request.parent}/populations
```
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/PopulationsService.kt` line 82 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1291#-Nhba52f5FP5VcbANvP8:-Nhba52f5FP5VcbANvP9:bifd3d) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1f238f1b3cfe0fae49af00ad6beffb65cfda32ef/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/PopulationsService.kt#L82)):*
> ```Kotlin
>       }
> 
>     when (authenticatedPrincipal) {
> ```

nit: you can just unconditionally check whether `authenticatedPrincipal.resourceKey` matches `parentKey`. The `when` is unnecessary here.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/PopulationsService.kt` line 142 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1291#-NhbanfF2FmYCCSwpsVY:-NhbanfG5-jmS0E3Mgmm:bg310bh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1f238f1b3cfe0fae49af00ad6beffb65cfda32ef/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/PopulationsService.kt#L142)):*
> ```Kotlin
>     grpcRequire(request.pageSize >= 0) { "Page size cannot be less than 0" }
> 
>     fun permissionDeniedStatus() = Permission.LIST.deniedStatus("${request.parent}")
> ```

Technically List applies to the `populations` resource collection.



_Suggestion:_
```Kotlin
${request.parent}/populations
```
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/PopulationsService.kt` line 264 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1291#-NhbbE2k2jdpt3ZGH9yC:-NhbbE2l7nBakyM03Xab:b-g1ssrk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1f238f1b3cfe0fae49af00ad6beffb65cfda32ef/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/PopulationsService.kt#L264)):*
> ```Kotlin
>    * * A Population cannot be read by any other principal.
>    */
>   private fun MeasurementPrincipal.isAuthorizedToGet(dataProviderKey: DataProviderKey): Boolean {
> ```

Shouldn't this be the PopulationKey? That's what the KDoc implies.



_Code quote:_
```Kotlin
dataProviderKey: DataProviderKey
```
___
*[`src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/PopulationsServiceTest.kt` line 398 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1291#-NhbbwLY99NRx7YIdhRV:-NhbbwLZC14M_lZOLFGZ:bojwd06) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1f238f1b3cfe0fae49af00ad6beffb65cfda32ef/src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/PopulationsServiceTest.kt#L398)):*
> ```Kotlin
>       )
> 
>     assertThat(result).ignoringRepeatedFieldOrder().isEqualTo(expected)
> ```

The order of resources in the response matters. Don't ignore it here.



_Code quote:_
```Kotlin
ignoringRepeatedFieldOrder()
```
___
*[`src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/PopulationsServiceTest.kt` line 483 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1291#-NhbcB_d1pBp1Z1m-T98:-NhbcB_eAUt0VOZQ-wkP:biblv06) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1f238f1b3cfe0fae49af00ad6beffb65cfda32ef/src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/PopulationsServiceTest.kt#L483)):*
> ```Kotlin
>         }
>       }
>     Truth.assertThat(exception.status.code).isEqualTo(Status.Code.INVALID_ARGUMENT)
> ```

nit: add an import for this



_Code quote:_
```Kotlin
 Truth.assertThat
```


<!-- Sent from Reviewable.io -->

2023-10-26 00:53 UTC, jojijac0b reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1291)* status: all files reviewed, 4 unresolved discussions (waiting on @Marco-Premier and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/PopulationsService.kt` line 73 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1291#-Nhb_wH985OctUrdMy4o:-NhdRFYR9pg9QMdH5RlY:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1f238f1b3cfe0fae49af00ad6beffb65cfda32ef/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/PopulationsService.kt#L73)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

CreatePopulation technically applies to the `populations` resource collection.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/PopulationsService.kt` line 82 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1291#-Nhba52f5FP5VcbANvP8:-NhdRGyr-S_dzaJmNLCv:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1f238f1b3cfe0fae49af00ad6beffb65cfda32ef/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/PopulationsService.kt#L82)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: you can just unconditionally check whether `authenticatedPrincipal.resourceKey` matches `parentKey`. The `when` is unnecessary here.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/PopulationsService.kt` line 142 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1291#-NhbanfF2FmYCCSwpsVY:-NhdRMmN8xGgN62Myxbm:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1f238f1b3cfe0fae49af00ad6beffb65cfda32ef/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/PopulationsService.kt#L142)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Technically List applies to the `populations` resource collection.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/PopulationsService.kt` line 264 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1291#-NhbbE2k2jdpt3ZGH9yC:-NhdRssm07gr-Yla0TeD:bai7izy) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1f238f1b3cfe0fae49af00ad6beffb65cfda32ef/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/PopulationsService.kt#L264)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Shouldn't this be the PopulationKey? That's what the KDoc implies.
</blockquote></details>

Removing this function as it is never used.
___
*[`src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/PopulationsServiceTest.kt` line 398 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1291#-NhbbwLY99NRx7YIdhRV:-NhdSAa80X4GYwIq1fsL:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1f238f1b3cfe0fae49af00ad6beffb65cfda32ef/src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/PopulationsServiceTest.kt#L398)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The order of resources in the response matters. Don't ignore it here.
</blockquote></details>

Done.
___
*[`src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/PopulationsServiceTest.kt` line 483 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1291#-NhbcB_d1pBp1Z1m-T98:-NhdSXal3NPVxK24QuUX:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1f238f1b3cfe0fae49af00ad6beffb65cfda32ef/src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/PopulationsServiceTest.kt#L483)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: add an import for this
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-26 20:12 UTC, stevenwarejones approved these changes
> Reviewed 3 of 3 files at r10, 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1291)* status: all files reviewed, 4 unresolved discussions (waiting on @Marco-Premier and @SanjayVas)



<!-- Sent from Reviewable.io -->

2023-10-31 17:34 UTC, Marco-Premier approved these changes
> Reviewed 2 of 12 files at r1, 3 of 6 files at r2, 1 of 5 files at r7, 3 of 3 files at r10, 2 of 2 files at r11, 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1291)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jojijac0b)



<!-- Sent from Reviewable.io -->

2023-10-31 20:45 UTC, merged