Create Dynamic Clipping library for impression and duration measurements
world-federation-of-advertisers/cross-media-measurement pull request #1320
Opened 2023-11-06 17:57 UTC by iverson52000

### Background
* For impression/duration measurements, we have to set an impression/duration cap to guarantee differential privacy
* Currently, the measurement consumers(MC) select the cap, but it's challenging for MCs since the optimal cap should be chosen based on the frequency/duration distribution
* The Dynamic Clipping library allows the EDP to automatically optimize the cap for each campaign and to achieve higher accuracy than using a fixed cap, based on the frequency distribution of the events

### Need to Know
The Dynamic Clipping library is provided as a reference implementation for EDP to potentially improve impression/duration measurement accuracy. It is an optional EDP feature, and will require additional local market approval for deployment in production.

### Reference
https://docs.google.com/document/d/1vboqbbHOqblYhooYCwAJ2fyqBCZOILFKmxtCm_O-kaY/edit

Rally task link: https://rally1.rallydev.com/#/?detail=/task/729250522061&fdp=true

2023-11-06 17:58 UTC, wfa-reviewable commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1320)
<!-- Reviewable:end -->

2023-11-06 18:03 UTC, iverson52000 reviewed
@SanjayVas Feel free to review code style when you have capacity. Thanks!

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1320#-:-Ni_n4f53JSAHPWZCxHu:b-45gbf9)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @chenweiw, @SanjayVas, @stevenwarejones, and @uakyol)



<!-- Sent from Reviewable.io -->

2023-11-06 23:20 UTC, chenweiw approved these changes
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1320)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas, @stevenwarejones, and @uakyol)



<!-- Sent from Reviewable.io -->

2023-11-07 00:00 UTC, SanjayVas requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1320)* status: all files reviewed, 8 unresolved discussions (waiting on @iverson52000, @stevenwarejones, and @uakyol)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/directmeasurement/BUILD.bazel` line 3 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1320#-NiazQYM55qmTllmsxNv:-NiazQYM55qmTllmsxNw:byrihsz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/638b2211149bbf5be533d959f43ae010d2b6102a/src/main/kotlin/org/wfanet/measurement/eventdataprovider/directmeasurement/BUILD.bazel#L3)):*
> ```Starlark
> load("@io_bazel_rules_kotlin//kotlin:jvm.bzl", "kt_jvm_library")
> 
> package(default_visibility = [
> ```

A library that's meant to be used by anyone should have public visibility.
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/directmeasurement/DynamicClipper.kt` line 14 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1320#-Nib-XYFDotEXLewM1Ci:-Nib-XYFDotEXLewM1Cj:b-p2jhss) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/638b2211149bbf5be533d959f43ae010d2b6102a/src/main/kotlin/org/wfanet/measurement/eventdataprovider/directmeasurement/DynamicClipper.kt#L14)):*
> ```Kotlin
>  * the License.
>  */
> package org.wfanet.measurement.eventdataprovider.directmeasurement
> ```

nit: better package name. For example, consider whether we want to directly reference the concepts of Measurement resources and the Direct protocol. Ideally have a short, concise name. Perhaps `differentialprivacy`?



_Code quote:_
```Kotlin
directmeasurement
```
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/directmeasurement/DynamicClipper.kt` line 29 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1320#-Nib-DOB8XTmZ7kTX2BX:-Nib-DOB8XTmZ7kTX2BY:bbaacrb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/638b2211149bbf5be533d959f43ae010d2b6102a/src/main/kotlin/org/wfanet/measurement/eventdataprovider/directmeasurement/DynamicClipper.kt#L29)):*
> ```Kotlin
>  * @param threshold Optimized dynamic impression/duration cutoff threshold.
>  */
> data class DynamicClipResult(val noisedCumulativeHistogramList: List<Double>, val threshold: Int)
> ```

If these types are only ever used/returned by this class, remove the prefixes and nest them inside the class.
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/directmeasurement/DynamicClipper.kt` line 32 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1320#-Nib2CCIDmoDlgmL-GBk:-Nib2CCIDmoDlgmL-GBl:b8920gb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/638b2211149bbf5be533d959f43ae010d2b6102a/src/main/kotlin/org/wfanet/measurement/eventdataprovider/directmeasurement/DynamicClipper.kt#L32)):*
> ```Kotlin
> 
> /** Dynamic Clipping only supports impression and duration measurements */
> enum class DynamicClipMeasurementType {
> ```

It looks like this enum might be used for mode switching, which is a code smell. See comment re: strong typing below.
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/directmeasurement/DynamicClipper.kt` line 45 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1320#-Nib3TtQDdVMmM-73q6-:-Nib3TtQDdVMmM-73q60:bzh1nu1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/638b2211149bbf5be533d959f43ae010d2b6102a/src/main/kotlin/org/wfanet/measurement/eventdataprovider/directmeasurement/DynamicClipper.kt#L45)):*
> ```Kotlin
>  *   event query. For impression, the list index is frequency of impression. For duration, the list
>  *   index is watch duration in seconds. The list element is histogram bar which is data counts. The
>  *   first element should be zero which means 0 impression/duration has 0 count.
> ```

Use a Map rather than a List so we don't need to rely on conditional interpretations of the list index.

Also prefer to be strongly typed whenever possible, e.g. use `java.time.Duration` for durations rather than primitive numeric types. This may require some refactoring, e.g. having separate methods for impression vs. duration histograms rather than trying to take in a common type in the constructor.



_Code quote:_
```Kotlin
 * @param histogramList An impression or duration frequency histogram converted from the labeled
 *   event query. For impression, the list index is frequency of impression. For duration, the list
 *   index is watch duration in seconds. The list element is histogram bar which is data counts. The
 *   first element should be zero which means 0 impression/duration has 0 count.
```
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/directmeasurement/DynamicClipper.kt` line 49 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1320#-Niazh6n6Zpoha36RzhS:-Niazh6o-1KEAdFTxVeM:b-d96jyf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/638b2211149bbf5be533d959f43ae010d2b6102a/src/main/kotlin/org/wfanet/measurement/eventdataprovider/directmeasurement/DynamicClipper.kt#L49)):*
> ```Kotlin
>  * @param maxThreshold The maximum threshold in the cumulativeHistogramList.
>  */
> class DynamicClipper(
> ```

nit: prefer nouns over verbs for class names, especially when they don't have a single method that matches the verb.



_Suggestion:_
```Kotlin
DynamicClipping
```
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/directmeasurement/DynamicClipper.kt` line 57 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1320#-Nib1gBk5f1UV97g02Ig:-Nib1gBk5f1UV97g02Ih:b-9xfrpv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/638b2211149bbf5be533d959f43ae010d2b6102a/src/main/kotlin/org/wfanet/measurement/eventdataprovider/directmeasurement/DynamicClipper.kt#L57)):*
> ```Kotlin
>       DynamicClipMeasurementType.IMPRESSION -> IMPRESSION_MAX_THRESHOLD
>       DynamicClipMeasurementType.DURATION -> DURATION_MAX_THRESHOLD
>     },
> ```

nit: extract this to a `defaultMaxThreshold(measurementType)` function in the companion object



_Code quote:_
```Kotlin
    when (measurementType) {
      DynamicClipMeasurementType.IMPRESSION -> IMPRESSION_MAX_THRESHOLD
      DynamicClipMeasurementType.DURATION -> DURATION_MAX_THRESHOLD
    },
```
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/directmeasurement/DynamicClipper.kt` line 77 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1320#-Nib-73w7nJDpK67Vbbj:-Nib-73x3GdVBKk1MIAl:bbxnhdd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/638b2211149bbf5be533d959f43ae010d2b6102a/src/main/kotlin/org/wfanet/measurement/eventdataprovider/directmeasurement/DynamicClipper.kt#L77)):*
> ```Kotlin
>    * @return [DynamicClipResult] Data class of noisedCumulativeHistogramList and threshold.
>    */
>   fun runTwoPhaseDynamicClipping(): DynamicClipResult {
> ```

nit: better name. "Run" is a non-specific verb. Perhaps something like `computeCappedHistogram`?

If the intent of mentioning "two-phase" is that there might be other algorithms, we'd likely instead want to represent that by having a single interface with a separate impl for each algorithm.



_Code quote:_
```Kotlin
runTwoPhaseDynamicClipping
```


<!-- Sent from Reviewable.io -->

2023-11-08 00:10 UTC, uakyol requested changes
> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1320)* status: all files reviewed, 9 unresolved discussions (waiting on @iverson52000 and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/directmeasurement/DynamicClipper.kt` line 165 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1320#-Nig5uhz6ltRLVZa0owA:-Nig5uhz6ltRLVZa0owB:budbpej) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/638b2211149bbf5be533d959f43ae010d2b6102a/src/main/kotlin/org/wfanet/measurement/eventdataprovider/directmeasurement/DynamicClipper.kt#L165)):*
> ```Kotlin
>     val noisedCumulativeHistogramList = MutableList(cumulativeHistogramList.size) { 0.0 }
> 
>     for (i in cumulativeHistogramList.indices) {
> ```

would this not work?

`val noisedCumulativeHistogramList =  cumulativeHistogramList.map{it +normalDistribution.sample() }`


<!-- Sent from Reviewable.io -->

2023-11-08 17:42 UTC, iverson52000 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1320)* status: 0 of 4 files reviewed, 4 unresolved discussions (waiting on @chenweiw, @SanjayVas, @stevenwarejones, and @uakyol)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/directmeasurement/BUILD.bazel` line 3 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1320#-NiazQYM55qmTllmsxNv:-NieuocOE9CKStUAVoef:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/638b2211149bbf5be533d959f43ae010d2b6102a/src/main/kotlin/org/wfanet/measurement/eventdataprovider/directmeasurement/BUILD.bazel#L3)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

A library that's meant to be used by anyone should have public visibility.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/directmeasurement/DynamicClipper.kt` line 29 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1320#-Nib-DOB8XTmZ7kTX2BX:-NiexJpJ-4cjtSUoXIOM:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/638b2211149bbf5be533d959f43ae010d2b6102a/src/main/kotlin/org/wfanet/measurement/eventdataprovider/directmeasurement/DynamicClipper.kt#L29)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

If these types are only ever used/returned by this class, remove the prefixes and nest them inside the class.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/directmeasurement/DynamicClipper.kt` line 45 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1320#-Nib3TtQDdVMmM-73q6-:-Nik08Dh0mub7PxjwYp-:b-fay8cl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/638b2211149bbf5be533d959f43ae010d2b6102a/src/main/kotlin/org/wfanet/measurement/eventdataprovider/directmeasurement/DynamicClipper.kt#L45)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Use a Map rather than a List so we don't need to rely on conditional interpretations of the list index.

Also prefer to be strongly typed whenever possible, e.g. use `java.time.Duration` for durations rather than primitive numeric types. This may require some refactoring, e.g. having separate methods for impression vs. duration histograms rather than trying to take in a common type in the constructor.
</blockquote></details>

Done. Change the input from `List` to `Map` and pass in the method `computeImpressionCappedHistogram(frequencyMap: Map<Long, Long>)` instead of passing in the constructor. We are focusing on the implementation for impression for now, updated the PR title and the method name. cc @chenweiw 
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/directmeasurement/DynamicClipper.kt` line 165 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1320#-Nig5uhz6ltRLVZa0owA:-NijzbNKBeKm1ZvLAART:bkshl6f) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/638b2211149bbf5be533d959f43ae010d2b6102a/src/main/kotlin/org/wfanet/measurement/eventdataprovider/directmeasurement/DynamicClipper.kt#L165)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

would this not work?

`val noisedCumulativeHistogramList =  cumulativeHistogramList.map{it +normalDistribution.sample() }`
</blockquote></details>

Done. Yes it works thanks!


<!-- Sent from Reviewable.io -->

2023-11-08 17:58 UTC, SanjayVas requested changes
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1320)* status: all files reviewed, 2 unresolved discussions (waiting on @iverson52000, @stevenwarejones, and @uakyol)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/directmeasurement/DynamicClipper.kt` line 29 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1320#-Nib-DOB8XTmZ7kTX2BX:-Nik4OQ68ZqpbWr-Sivt:b4ucvjo) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/638b2211149bbf5be533d959f43ae010d2b6102a/src/main/kotlin/org/wfanet/measurement/eventdataprovider/directmeasurement/DynamicClipper.kt#L29)):*
<details><summary><i>Previously, iverson52000 (Albert Hsu) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I still see DynamicClipMeasurementType instead of DynamingClipping.MeasurementType.


<!-- Sent from Reviewable.io -->

2023-11-08 18:22 UTC, iverson52000 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1320)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @SanjayVas, @stevenwarejones, and @uakyol)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/directmeasurement/DynamicClipper.kt` line 29 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1320#-Nib-DOB8XTmZ7kTX2BX:-Nik9bqv2M8uoqTq31qa:b-bp7uwp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/638b2211149bbf5be533d959f43ae010d2b6102a/src/main/kotlin/org/wfanet/measurement/eventdataprovider/directmeasurement/DynamicClipper.kt#L29)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I still see DynamicClipMeasurementType instead of DynamingClipping.MeasurementType.
</blockquote></details>

Done. Oops missed this. Thanks!


<!-- Sent from Reviewable.io -->

2023-11-08 18:53 UTC, uakyol reviewed
> Reviewed 2 of 4 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1320)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2023-11-08 18:57 UTC, SanjayVas approved these changes
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1320)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)



<!-- Sent from Reviewable.io -->

2023-11-10 14:50 UTC, stevenwarejones reviewed
> Reviewed 2 of 4 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1320)* status: all files reviewed, 1 unresolved discussion (waiting on @iverson52000)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/differentialprivacy/DynamicClipping.kt` line 232 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1320#-Nith5Fy-3VIKJ4JJTgr:-Nith5Fy-3VIKJ4JJTgs:b-fzdtfb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0868abdd6547e3f4ddbba000dc4dea7340f47afb/src/main/kotlin/org/wfanet/measurement/eventdataprovider/differentialprivacy/DynamicClipping.kt#L232)):*
> ```Kotlin
>   companion object {
>     // The default max thresholds are based on analysis result and are subject to change.
>     private const val IMPRESSION_MAX_THRESHOLD = 200
> ```

do we have input from TV on these?


<!-- Sent from Reviewable.io -->

2023-11-13 01:40 UTC, iverson52000 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1320)* status: all files reviewed, 1 unresolved discussion (waiting on @chenweiw)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/differentialprivacy/DynamicClipping.kt` line 232 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1320#-Nith5Fy-3VIKJ4JJTgr:-Nj5KFLc88bj-Oey1b3a:b-lvpr3x) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0868abdd6547e3f4ddbba000dc4dea7340f47afb/src/main/kotlin/org/wfanet/measurement/eventdataprovider/differentialprivacy/DynamicClipping.kt#L232)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

do we have input from TV on these?
</blockquote></details>

Will defter to @chenweiw to answer


<!-- Sent from Reviewable.io -->

2023-11-13 17:08 UTC, chenweiw reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1320)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/differentialprivacy/DynamicClipping.kt` line 232 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1320#-Nith5Fy-3VIKJ4JJTgr:-Nj8dIq93PaonqGZ2JP6:bkdfzz8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0868abdd6547e3f4ddbba000dc4dea7340f47afb/src/main/kotlin/org/wfanet/measurement/eventdataprovider/differentialprivacy/DynamicClipping.kt#L232)):*
<details><summary><i>Previously, iverson52000 (Albert Hsu) wrote…</i></summary><blockquote>

Will defter to @chenweiw to answer
</blockquote></details>

For alpha, no. Only video ads are considered for alpha. Generally, the threshold is tunable parameter.


<!-- Sent from Reviewable.io -->

2023-11-13 18:25 UTC, chenweiw reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1320)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/differentialprivacy/DynamicClipping.kt` line 232 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1320#-Nith5Fy-3VIKJ4JJTgr:-Nj8o1tM-Gbk7QsKXTkz:bbe1s6u) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0868abdd6547e3f4ddbba000dc4dea7340f47afb/src/main/kotlin/org/wfanet/measurement/eventdataprovider/differentialprivacy/DynamicClipping.kt#L232)):*
<details><summary><i>Previously, chenweiw wrote…</i></summary><blockquote>

For alpha, no. Only video ads are considered for alpha. Generally, the threshold is tunable parameter.
</blockquote></details>

Correction to my previous comment: For alpha 1.5.1 and before, no TV. From alpha 1.5.2 and after, TV will be integrated. 


<!-- Sent from Reviewable.io -->

2023-11-14 02:32 UTC, iverson52000 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1320)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/differentialprivacy/DynamicClipping.kt` line 232 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1320#-Nith5Fy-3VIKJ4JJTgr:-NjAe28KCEEgsStNAXrS:bvdu8nb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0868abdd6547e3f4ddbba000dc4dea7340f47afb/src/main/kotlin/org/wfanet/measurement/eventdataprovider/differentialprivacy/DynamicClipping.kt#L232)):*
<details><summary><i>Previously, chenweiw wrote…</i></summary><blockquote>

Correction to my previous comment: For alpha 1.5.1 and before, no TV. From alpha 1.5.2 and after, TV will be integrated.
</blockquote></details>

Thanks Chenwei. And yes we have the `maxThreshold` param passed in the constructor to be tunable 


<!-- Sent from Reviewable.io -->

2023-11-14 18:45 UTC, uakyol approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1320)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)



<!-- Sent from Reviewable.io -->

2023-11-14 20:32 UTC, stevenwarejones approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1320)* status: all files reviewed, 1 unresolved discussion (waiting on @chenweiw)



<!-- Sent from Reviewable.io -->

2023-11-14 20:38 UTC, chenweiw approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1320)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @iverson52000)



<!-- Sent from Reviewable.io -->

2023-11-15 02:07 UTC, merged