Allow custom methodology not to provide variance but with a reason
world-federation-of-advertisers/cross-media-measurement pull request #1322
Opened 2023-11-06 23:55 UTC by riemanli

2023-11-06 23:55 UTC, wfa-reviewable commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1322)
<!-- Reviewable:end -->

2023-11-06 23:55 UTC, riemanli commented
Current dependencies on/for this PR:
* main
  * **PR #1322** <a href="https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/1322" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/1322?utm_source=stack-comment).

2023-11-10 17:27 UTC, tristanvuong2021 requested changes
> Reviewed 5 of 8 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1322)* status: all files reviewed, 3 unresolved discussions (waiting on @riemanli)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 1974 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1322#-Niu6-vf2xyGClq5EpMz:-Niu6-vg06zZi7YB5qk7:bkz6476) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d5810ab906dd962a56de1880a491d552fe7953fd/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L1974)):*
> ```Kotlin
>         CustomDirectMethodology.Variance.TypeCase.UNAVAILABLE -> {
>           throw MeasurementVarianceNotComputableException(
>             "Watch duration computed from a custom methodology doesn't have variance."
> ```

Error message should be about impression
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 2198 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1322#-Niu67TC4vcoMJVKt-sW:-Niu67TC4vcoMJVKt-sX:bk2qo3n) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d5810ab906dd962a56de1880a491d552fe7953fd/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L2198)):*
> ```Kotlin
>         CustomDirectMethodology.Variance.TypeCase.UNAVAILABLE -> {
>           throw MeasurementVarianceNotComputableException(
>             "Watch duration computed from a custom methodology doesn't have variance."
> ```

Error message should be about frequency
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 2368 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1322#-Niu6ETW5H_rnd9kEHxm:-Niu6ETW5H_rnd9kEHxn:bepmzh6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d5810ab906dd962a56de1880a491d552fe7953fd/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L2368)):*
> ```Kotlin
>         CustomDirectMethodology.Variance.TypeCase.UNAVAILABLE -> {
>           throw MeasurementVarianceNotComputableException(
>             "Watch duration computed from a custom methodology doesn't have variance."
> ```

Error message should be about reach


<!-- Sent from Reviewable.io -->

2023-11-10 18:26 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1322)* status: 7 of 8 files reviewed, 3 unresolved discussions (waiting on @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 1974 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1322#-Niu6-vf2xyGClq5EpMz:-NiuTp1z5YbwAWX8gRu6:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d5810ab906dd962a56de1880a491d552fe7953fd/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L1974)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Error message should be about impression
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 2198 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1322#-Niu67TC4vcoMJVKt-sW:-NiuTbSFEfTAZJQtdH6L:b9cedjm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d5810ab906dd962a56de1880a491d552fe7953fd/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L2198)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Error message should be about frequency
</blockquote></details>

Done. Thanks for catching it!
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 2368 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1322#-Niu6ETW5H_rnd9kEHxm:-NiuTj-U5NkEEjwVJvBh:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d5810ab906dd962a56de1880a491d552fe7953fd/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L2368)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Error message should be about reach
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-11-10 18:28 UTC, tristanvuong2021 approved these changes
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1322)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @riemanli)



<!-- Sent from Reviewable.io -->

2023-11-10 18:55 UTC, stevenwarejones approved these changes
> Reviewed 4 of 8 files at r1, 2 of 3 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1322)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Marco-Premier)



<!-- Sent from Reviewable.io -->

2023-11-10 21:17 UTC, stevenwarejones approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1322)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Marco-Premier)



<!-- Sent from Reviewable.io -->

2023-11-11 01:18 UTC, tristanvuong2021 approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1322)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Marco-Premier)



<!-- Sent from Reviewable.io -->

2023-11-11 18:19 UTC, merged