Add a metric reuse mechanism based on timed ReportingMetricEntries
world-federation-of-advertisers/cross-media-measurement pull request #1347
Opened 2023-11-22 02:18 UTC by riemanli

2023-11-22 02:18 UTC, wfa-reviewable commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1347)
<!-- Reviewable:end -->

2023-11-22 02:18 UTC, riemanli commented
Current dependencies on/for this PR:
* main
  * **PR #1347** <a href="https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/1347?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/1347?utm_source=stack-comment).

2023-11-27 18:46 UTC, SanjayVas requested changes
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1347)* status: all files reviewed, 4 unresolved discussions (waiting on @riemanli)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/MetricReader.kt` line 230 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1347#-NkH2Au-7KFKEU3hH2y6:-NkH2Au-7KFKEU3hH2y7:b-k669h2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/491a555f7b45eab43ef4347bc59794a2e2b4cd8c/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/MetricReader.kt#L230)):*
> ```Kotlin
>           LEFT JOIN MetricCalculationSpecReportingMetrics
>             ON Metrics.MeasurementConsumerId = MetricCalculationSpecReportingMetrics.MeasurementConsumerId
>             AND Metrics.MetricId = MetricCalculationSpecReportingMetrics.MetricId
> ```

nit: keep consistent indentation for FROM clause



_Suggestion:_
```Kotlin
          FROM
            MeasurementConsumers
            JOIN Metrics USING(MeasurementConsumerId)
            $baseSqlJoins
            LEFT JOIN MetricCalculationSpecReportingMetrics ON
              Metrics.MeasurementConsumerId = MetricCalculationSpecReportingMetrics.MeasurementConsumerId
              AND Metrics.MetricId = MetricCalculationSpecReportingMetrics.MetricId
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/MetricReader.kt` line 234 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1347#-NkH2lZ9EN8cyg_9RWBs:-NkH2lZ9EN8cyg_9RWBt:b-u54b3z) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/491a555f7b45eab43ef4347bc59794a2e2b4cd8c/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/MetricReader.kt#L234)):*
> ```Kotlin
>             AND Metrics.ReportingSetId = $2
>             AND MetricCalculationSpecReportingMetrics.MetricCalculationSpecId = $3
>             AND
> ```

nit: append the `AND` when you append the additional conjunct so this reads clearer. The hanging `AND` here looks like a bug at first glance without careful reading.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateReport.kt` line 118 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1347#-NkH439hDSm0DCy5DssT:-NkH439iBBGyDR3VrF-p:b-k34t1w) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/491a555f7b45eab43ef4347bc59794a2e2b4cd8c/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateReport.kt#L118)):*
> ```Kotlin
> 
>     // External ID to MetricCalculationSpecReader.Result
>     val metricCalculationSpecReaderResultMap: Map<String, MetricCalculationSpecReader.Result> =
> ```

nit: accurate naming can avoid the need for explanatory comments. Names also need not be maximally verbose (e.g. the "ReaderResult" part).



_Suggestion:_
```Kotlin
    val metricCalculationSpecsByExternalId: Map<String, MetricCalculationSpecReader.Result> =
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/v2/ReportsServiceTest.kt` line 505 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1347#-NkH5K7r6vRoXXo4bj7l:-NkH5K7r6vRoXXo4bj7m:b-c9oauz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/491a555f7b45eab43ef4347bc59794a2e2b4cd8c/src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/v2/ReportsServiceTest.kt#L505)):*
> ```Kotlin
> 
>   @Test
>   fun `createReport returns report after report metrics have been created`() = runBlocking {
> ```

This doesn't really tell me what the method is testing. I assume it's verifying that the existing metrics get reused?



_Suggestion:_
```Kotlin
reuses existing metrics
```


<!-- Sent from Reviewable.io -->

2023-11-27 23:46 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1347)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/MetricReader.kt` line 230 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1347#-NkH2Au-7KFKEU3hH2y6:-NkHAElDC4Pp8AqlAldt:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/491a555f7b45eab43ef4347bc59794a2e2b4cd8c/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/MetricReader.kt#L230)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: keep consistent indentation for FROM clause
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/MetricReader.kt` line 234 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1347#-NkH2lZ9EN8cyg_9RWBs:-NkHA_Fo0CYaZasLidrr:b3d58kq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/491a555f7b45eab43ef4347bc59794a2e2b4cd8c/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/MetricReader.kt#L234)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: append the `AND` when you append the additional conjunct so this reads clearer. The hanging `AND` here looks like a bug at first glance without careful reading.
</blockquote></details>

Got it. Done. 
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/v2/ReportsServiceTest.kt` line 505 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1347#-NkH5K7r6vRoXXo4bj7l:-NkHBpp-80dv-N7Ul-wK:bpu5ien) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/491a555f7b45eab43ef4347bc59794a2e2b4cd8c/src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/v2/ReportsServiceTest.kt#L505)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This doesn't really tell me what the method is testing. I assume it's verifying that the existing metrics get reused?
</blockquote></details>

Thanks for pointing it out. Done!


<!-- Sent from Reviewable.io -->

2023-11-28 18:09 UTC, SanjayVas approved these changes
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1347)* status: all files reviewed, 1 unresolved discussion (waiting on @riemanli)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateReport.kt` line 118 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1347#-NkH439hDSm0DCy5DssT:-NkM6Q179MEJHqw3Myn9:b-1eipqe) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/491a555f7b45eab43ef4347bc59794a2e2b4cd8c/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateReport.kt#L118)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Thanks for the advice! Should the value name be singular or plural, i.e. metricCalculationSpec**s**ByExternalId vs metricCalculationSpecByExternalId?
</blockquote></details>

I've tended to go with plural as that indicates it's a collection.


<!-- Sent from Reviewable.io -->

2023-11-28 18:42 UTC, kungfucraig requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1347)* status: all files reviewed, 2 unresolved discussions (waiting on @riemanli)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/v2/ReportsServiceTest.kt` line 616 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1347#-NkMEId_BF5ovGTfnoA7:-NkMEId_BF5ovGTfnoA8:bz1vryr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7d4e4ec88c9fb291910304846a49f077dceba68b/src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/v2/ReportsServiceTest.kt#L616)):*
> ```Kotlin
>       )
> 
>     for (entry in createdReportReusingMetrics.reportingMetricEntriesMap.entries) {
> ```

I'm trying to understand if this loop tests that the metrics were actually reused. If it does I'm not sure how it's achieving that. Could you add some comments to explain?


<!-- Sent from Reviewable.io -->

2023-11-28 18:45 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1347)* status: all files reviewed, 2 unresolved discussions (waiting on @kungfucraig)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/v2/ReportsServiceTest.kt` line 616 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1347#-NkMEId_BF5ovGTfnoA7:-NkMEkF01b6qB3LWgIGa:bch0o66) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7d4e4ec88c9fb291910304846a49f077dceba68b/src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/v2/ReportsServiceTest.kt#L616)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

I'm trying to understand if this loop tests that the metrics were actually reused. If it does I'm not sure how it's achieving that. Could you add some comments to explain?
</blockquote></details>

This loop doesn't check metric reuse but creation of a report instead. The check for metric reuse is the `assertThat` at the end.


<!-- Sent from Reviewable.io -->

2023-11-28 18:49 UTC, kungfucraig requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1347)* status: all files reviewed, 2 unresolved discussions (waiting on @riemanli and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/v2/ReportsServiceTest.kt` line 616 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1347#-NkMEId_BF5ovGTfnoA7:-NkMFUCs6n_kkF3bUhif:b-ao7a5m) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7d4e4ec88c9fb291910304846a49f077dceba68b/src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/v2/ReportsServiceTest.kt#L616)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

This loop doesn't check metric reuse but creation of a report instead. The check for metric reuse is the `assertThat` at the end.
</blockquote></details>

Okay. I see, and the last check does it on the basis of this field (https://sourcegraph.com/github.com/world-federation-of-advertisers/cross-media-measurement@5327f5695b70fc2b62b8e1aa1b21544c38538749/-/blob/src/main/proto/wfa/measurement/reporting/v1alpha/report.proto?L87) being the same?


<!-- Sent from Reviewable.io -->

2023-11-28 18:52 UTC, riemanli commented
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/v2/ReportsServiceTest.kt` line 616 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1347#-NkMEId_BF5ovGTfnoA7:-NkMGMf15x_xxeh8GdLK:bcx28m5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7d4e4ec88c9fb291910304846a49f077dceba68b/src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/v2/ReportsServiceTest.kt#L616)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Okay. I see, and the last check does it on the basis of this field (https://sourcegraph.com/github.com/world-federation-of-advertisers/cross-media-measurement@5327f5695b70fc2b62b8e1aa1b21544c38538749/-/blob/src/main/proto/wfa/measurement/reporting/v1alpha/report.proto?L87) being the same?
</blockquote></details>

Something like that, but it's checking this [field](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/main/proto/wfa/measurement/internal/reporting/v2/report.proto#L74). Note that we don't add metric reuse for V1. 


<!-- Sent from Reviewable.io -->

2023-11-28 23:28 UTC, kungfucraig requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1347)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @riemanli and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/v2/ReportsServiceTest.kt` line 616 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1347#-NkMEId_BF5ovGTfnoA7:-NkNEvNp6LrGaOLNPic3:byprmlr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7d4e4ec88c9fb291910304846a49f077dceba68b/src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/v2/ReportsServiceTest.kt#L616)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Something like that, but it's checking this [field](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/main/proto/wfa/measurement/internal/reporting/v2/report.proto#L74). Note that we don't add metric reuse for V1.
</blockquote></details>

Checking reporting metric entires, doesn't help does it? That's telling you if reuse should happen, but it doesn't prove that reuse did happen. For that you'd need to see that the same set of Metrics was used in the results.

Tristan has a task to add Metric references to the Result object. Until that happens I don't see we have enough information in Report to prove Metrics were reused.

Maybe we can inspect the Metric API, or maybe we have to wait for the feature Tristan is adding to check this?


<!-- Sent from Reviewable.io -->

2023-11-28 23:39 UTC, riemanli commented
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/v2/ReportsServiceTest.kt` line 616 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1347#-NkMEId_BF5ovGTfnoA7:-NkNG6b_79_4KwYQbehL:bdy3spy) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7d4e4ec88c9fb291910304846a49f077dceba68b/src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/v2/ReportsServiceTest.kt#L616)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Checking reporting metric entires, doesn't help does it? That's telling you if reuse should happen, but it doesn't prove that reuse did happen. For that you'd need to see that the same set of Metrics was used in the results.

Tristan has a task to add Metric references to the Result object. Until that happens I don't see we have enough information in Report to prove Metrics were reused.

Maybe we can inspect the Metric API, or maybe we have to wait for the feature Tristan is adding to check this?
</blockquote></details>

Great question. When create a report, the external metric IDs are not set until the metrics are created. Based on this, the testing flow is as follows:
1. Create `Report1`.
2. Submit create metric requests for all the metrics used in `Report1`.
3. Retrieve `Report1`. At this point, `Report1` should have all external metric IDs in `ReportingMetricEntries`.
4. Create `Report2` using the same report resource. At this point, if there is no metric reuse, `Report2` shouldn't have any external metric IDs and thus has different `ReportingMetricEntries` from what `Report1` has. If `Report1.ReportingMetricEntries` is equal to `Report2.ReportingMetricEntries`, it proves metric reuse happened during report creation.


<!-- Sent from Reviewable.io -->

2023-12-01 13:28 UTC, riemanli commented
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateReport.kt` line 146 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1347#-Nk_Yr5xDS7SBjsTHkZQ:-Nk_Yr5xDS7SBjsTHkZR:btzkojw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/935df4e9b086465e8d386daceb4323a0c0e228d0/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateReport.kt#L146)):*
> ```Kotlin
>     // Find existing sets of metrics for each ReportingMetricEntry from
>     // report.reportingMetricEntriesMap.
>     val deferred =
> ```

@SanjayVas I tried to optimize the iterated queries by using async but the performance is not improved. Am I doing anything wrong with the async code below?


<!-- Sent from Reviewable.io -->

2023-12-01 19:18 UTC, SanjayVas reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1347)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @riemanli)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateReport.kt` line 146 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1347#-Nk_Yr5xDS7SBjsTHkZQ:-Nkam14JAr1R-5mC-aor:b-kuxxby) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/935df4e9b086465e8d386daceb4323a0c0e228d0/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateReport.kt#L146)):*
The async code looks like it should indeed make the calls to `readReportingMetricsByTimedReportingMetricEntry` in parallel, meaning the queries themselves should be done in parallel (up to the parallelism limit of the DB connections).

Note that this will result in `n` simultaneous connections, as the connection needs to stay open until the Flow is consumed. What you probably want is to have a single query that returns all of the results rather than making `n` separate queries.

> the performance is not improved

Are you sure this (executing the queries) is the bottleneck?


<!-- Sent from Reviewable.io -->

2023-12-02 06:31 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1347)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @kungfucraig and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateReport.kt` line 146 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1347#-Nk_Yr5xDS7SBjsTHkZQ:-Nkc-uPA3k68WyBSY0As:btvhaq7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/935df4e9b086465e8d386daceb4323a0c0e228d0/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateReport.kt#L146)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The async code looks like it should indeed make the calls to `readReportingMetricsByTimedReportingMetricEntry` in parallel, meaning the queries themselves should be done in parallel (up to the parallelism limit of the DB connections).

Note that this will result in `n` simultaneous connections, as the connection needs to stay open until the Flow is consumed. What you probably want is to have a single query that returns all of the results rather than making `n` separate queries.

> the performance is not improved

Are you sure this (executing the queries) is the bottleneck?
</blockquote></details>

After a deeper investigation, I found two things
1. The iterated queries of metric reuse are no longer the bottleneck after I pruned the join statement in the query. It's the existing report creation taking a lot of time. A data point from my experiment: 
* Number of metrics in a report: 4320
* Number of metrics reused: 4320
* Execution time of metric reuse: 230 ms
* Execution time of report creation: 2 **secs**

2. In addition, I followed what you suggested to use a single query that returns all of the results. This further improves the performance a bit. 230ms => 200ms.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateReport.kt` line 382 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1347#-NkdD3fSA37BRbYGKKS1:-NkdD3fSA37BRbYGKKS2:b-3aagni) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/af434a995c812c75d19f953bc742e8c20f4a821b/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateReport.kt#L382)):*
> ```Kotlin
>           // Note that metric reuse mechanism won't produce the same order of `ReportingMetric`
>           // internally, but this won't impact any immutable fields in public resources.
>           reportingMetricMap.getValue(metricCalculationSpecReportingMetricKey).forEach {
> ```

Should've pointed this out earlier, but I hope this is ok: Due to the fact that we are reusing a set of metrics based on `MetricCalculationSpec`, we are not able to know the order of the internal `ReportingMetric`s. Note that `ReportingMetric` is only in internal resource and its order won't impact any immutable fields of public resources. 

@SanjayVas @kungfucraig Please let me know what you think.



_Code quote:_
```Kotlin
          // Note that metric reuse mechanism won't produce the same order of `ReportingMetric`
          // internally, but this won't impact any immutable fields in public resources.
          reportingMetricMap.getValue(metricCalculationSpecReportingMetricKey).forEach {
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/v2/ReportsServiceTest.kt` line 616 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1347#-NkMEId_BF5ovGTfnoA7:-NkdAs8oEKA9yGOEp7wa:b784mal) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7d4e4ec88c9fb291910304846a49f077dceba68b/src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/v2/ReportsServiceTest.kt#L616)):*
> Can you have your test check for R1.RME = R2.RME?

I can do something slightly different because the order of `ReportingMetrics` is not guaranteed. PTAL at the new version.


<!-- Sent from Reviewable.io -->

2023-12-04 19:42 UTC, SanjayVas approved these changes
> Reviewed 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1347)* status: all files reviewed, 2 unresolved discussions (waiting on @kungfucraig)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateReport.kt` line 146 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1347#-Nk_Yr5xDS7SBjsTHkZQ:-NkqKSY1C1Kjp3tZmooj:bjqrjc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/935df4e9b086465e8d386daceb4323a0c0e228d0/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateReport.kt#L146)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

After a deeper investigation, I found two things
1. The iterated queries of metric reuse are no longer the bottleneck after I pruned the join statement in the query. It's the existing report creation taking a lot of time. A data point from my experiment: 
* Number of metrics in a report: 4320
* Number of metrics reused: 4320
* Execution time of metric reuse: 230 ms
* Execution time of report creation: 2 **secs**

2. In addition, I followed what you suggested to use a single query that returns all of the results. This further improves the performance a bit. 230ms => 200ms.
</blockquote></details>

This might be okay then. Tristan is working on improving Report creation, as he found that the remaining bottleneck is having to make multiple calls to the CMMS API. In theory switching to batch methods on the CMMS API should bring this down.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateReport.kt` line 382 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1347#-NkdD3fSA37BRbYGKKS1:-NkqKs383GkXBGs5-LGq:b-wiyppn) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/af434a995c812c75d19f953bc742e8c20f4a821b/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateReport.kt#L382)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Should've pointed this out earlier, but I hope this is ok: Due to the fact that we are reusing a set of metrics based on `MetricCalculationSpec`, we are not able to know the order of the internal `ReportingMetric`s. Note that `ReportingMetric` is only in internal resource and its order won't impact any immutable fields of public resources. 

@SanjayVas @kungfucraig Please let me know what you think.
</blockquote></details>

Totally fine as long as order isn't part of the API. I'd personally recommend documenting when this is or is not the case (e.g. the public APIs have an UNORDERED_LIST field behavior).


<!-- Sent from Reviewable.io -->

2023-12-04 20:40 UTC, kungfucraig approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1347)* status: all files reviewed, 3 unresolved discussions (waiting on @riemanli)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/v2/ReportsServiceTest.kt` line 616 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1347#-NkMEId_BF5ovGTfnoA7:-NkpXtnp5IHhIRstD59C:b-kcm8m0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7d4e4ec88c9fb291910304846a49f077dceba68b/src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/v2/ReportsServiceTest.kt#L616)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

> Can you have your test check for R1.RME = R2.RME?

I can do something slightly different because the order of `ReportingMetrics` is not guaranteed. PTAL at the new version.
</blockquote></details>

I think I'm still confused. Shouldn't we be checking that the Metrics 
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/v2/ReportsServiceTest.kt` line 679 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1347#-NkqYjTN3_1l_Xk1ODic:-NkqYjTN3_1l_Xk1ODid:bkgxv01) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/af434a995c812c75d19f953bc742e8c20f4a821b/src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/v2/ReportsServiceTest.kt#L679)):*
> ```Kotlin
>     // internally. This won't impact any immutable fields in public resources.
>     for (entry in createdReportReusingMetrics.reportingMetricEntriesMap.entries) {
>       val expectedReportingMetricCalculationSpec =
> ```

expectedReportingMetrics ?


<!-- Sent from Reviewable.io -->

2023-12-11 23:55 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1347)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @kungfucraig and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateReport.kt` line 146 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1347#-Nk_Yr5xDS7SBjsTHkZQ:-NlNNG33BjBGCVb8qFit:b-qx665v) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/935df4e9b086465e8d386daceb4323a0c0e228d0/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateReport.kt#L146)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This might be okay then. Tristan is working on improving Report creation, as he found that the remaining bottleneck is having to make multiple calls to the CMMS API. In theory switching to batch methods on the CMMS API should bring this down.
</blockquote></details>

The analysis I did above is just for internal report creation. There is no call to CMM.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/v2/ReportsServiceTest.kt` line 616 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1347#-NkMEId_BF5ovGTfnoA7:-NlNPe_CA-v_BrPKVV4M:b-fy9efk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7d4e4ec88c9fb291910304846a49f077dceba68b/src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/v2/ReportsServiceTest.kt#L616)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

I think I'm still confused. Shouldn't we be checking that the Metrics
</blockquote></details>

Resolved offline. 

Here is the explanation: When a report creation request is submitted through the public reports service by a MC, what the public RPC function does first is call the internal reports service to insert an initial internal report to the DB. Without any metric reuse, the internal reports service populates `createMetricRequestId` into this initial internal report, and the public reports service can then use the IDs to submit metric creation requests. If metric reuse happens during the insertion of the initial internal report, both `createMetricRequestId` and `externalMetricId` of the reused metric will be populated into the internal report. 

As a result, in the unit test I check the occurrence of metric reuse by checking whether `reportingMetricEntriesMap` of the second report is the same as the one in the first report.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/v2/ReportsServiceTest.kt` line 679 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1347#-NkqYjTN3_1l_Xk1ODic:-NlNPLx7DM8LPr7QiqES:b-zyokx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/af434a995c812c75d19f953bc742e8c20f4a821b/src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/v2/ReportsServiceTest.kt#L679)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

expectedReportingMetrics ?
</blockquote></details>

`expectedReportingMetricCalculationSpec` is correct because the type of the value in the map is `ReportingMetricCalculationSpec`. See https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/af434a995c812c75d19f953bc742e8c20f4a821b/src/main/proto/wfa/measurement/internal/reporting/v2/report.proto.

I changed it to `expected` to be more concise and less confusing anyway. 


<!-- Sent from Reviewable.io -->

2023-12-12 15:44 UTC, stevenwarejones approved these changes
> Reviewed 3 of 4 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1347)* status: all files reviewed, 2 unresolved discussions (waiting on @kungfucraig and @SanjayVas)



<!-- Sent from Reviewable.io -->

2023-12-12 23:41 UTC, kungfucraig approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1347)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)



<!-- Sent from Reviewable.io -->

2023-12-13 00:44 UTC, merged