Jojijacob add population fields to reporting api
world-federation-of-advertisers/cross-media-measurement pull request #1354
Opened 2023-12-05 17:47 UTC by jojijac0b

Add population fields to reporting api.

2023-12-05 17:47 UTC, wfa-reviewable commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1354)
<!-- Reviewable:end -->

2023-12-05 17:50 UTC, jojijac0b commented
There will be build error as the changes made in cross-media-measurement-api have not been pulled in yet. 

pr: https://github.com/world-federation-of-advertisers/cross-media-measurement-api/pull/193

2023-12-05 19:15 UTC, stevenwarejones requested changes
> Reviewed 4 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1354)* status: 4 of 13 files reviewed, 6 unresolved discussions (waiting on @jojijac0b and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/measurementconsumer/MeasurementConsumerSimulator.kt` line 566 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1354#-NkvNaaa5zCVB87m8IaX:-NkvNaaa5zCVB87m8IaY:b-gtk1ug) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/57ea39a3271d27b60568d2fbf843da1f8c4026d6/src/main/kotlin/org/wfanet/measurement/loadtest/measurementconsumer/MeasurementConsumerSimulator.kt#L566)):*
> ```Kotlin
>         error("Protocol is not set")
>       }
>       else -> {
> ```

why is this needed? isn't the when exhaustive?
___
*[`src/main/proto/wfa/measurement/internal/reporting/v2/metric.proto` line 51 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1354#-NkvOedL6-LcbmzJ3Nno:-NkvOedL6-LcbmzJ3Nnp:b-fbdsdj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/57ea39a3271d27b60568d2fbf843da1f8c4026d6/src/main/proto/wfa/measurement/internal/reporting/v2/metric.proto#L51)):*
> ```proto
> 
>   message PopulationCountParams {
>     DifferentialPrivacyParams privacy_params = 1;
> ```

see may other comments about not needing these fields
___
*[`src/main/proto/wfa/measurement/reporting/bff/v1alpha/metric.proto` line 105 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1354#-NkvOiZJChQJy59NXvho:-NkvOiZJChQJy59NXvhp:bo6z35t) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/57ea39a3271d27b60568d2fbf843da1f8c4026d6/src/main/proto/wfa/measurement/reporting/bff/v1alpha/metric.proto#L105)):*
> ```proto
>     //
>     // Total population used to calculate this metric
>     int32 population_count = 2;
> ```

see may other comments about not needing these fields - @tristanvuong2021 - do we need to cover reportin/bff/v1alpha
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto` line 98 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1354#-NkvOOri98mCAzv06Tz4:-NkvOOri98mCAzv06Tz5:b-2pkja8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/57ea39a3271d27b60568d2fbf843da1f8c4026d6/src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto#L98)):*
> ```proto
>   message PopulationCountParams {
>     // Differential privacy parameters.
>     DifferentialPrivacyParams privacy_params = 1
> ```

I don't believe we need privacy params.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto` line 103 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1354#-NkvOQgH29zZA9FQWwoW:-NkvOQgH29zZA9FQWwoX:bbpjwy5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/57ea39a3271d27b60568d2fbf843da1f8c4026d6/src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto#L103)):*
> ```proto
>     //
>     // Total population used to calculate this metric
>     int64 population_count = 2;
> ```

see my other comment on the public api - I don't see what the purpose of this is and am confused about what it is.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto` line 242 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1354#-NkvODKm-Q4m8cahVzjk:-NkvODKm-Q4m8cahVzjl:blj4ast) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/57ea39a3271d27b60568d2fbf843da1f8c4026d6/src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto#L242)):*
> ```proto
>     // Univariate statistics of the population value above.
>     //
>     // Only set when all of the set operations for the result are unions and all
> ```

This comment is incorrect.
```
Only available in the Population Data Provider provides the population variance.
```



<!-- Sent from Reviewable.io -->

2023-12-13 00:53 UTC, stevenwarejones reviewed
> Reviewed 1 of 5 files at r5, 3 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1354)* status: 13 of 15 files reviewed, 3 unresolved discussions (waiting on @jojijac0b, @kungfucraig, and @tristanvuong2021)



<!-- Sent from Reviewable.io -->

2023-12-13 16:03 UTC, jojijac0b reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1354)* status: 11 of 15 files reviewed, 3 unresolved discussions (waiting on @kungfucraig, @SanjayVas, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/reporting/bff/v1alpha/metric.proto` line 179 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1354#-Nkzp7Tx1I9icCcPGxE9:-NlYuc0q7SuxQSru2Cfb:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4d24334c6de90b405d9c4563243d36c1db80f768/src/main/proto/wfa/measurement/reporting/bff/v1alpha/metric.proto#L179)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/internal/reporting/measurement.proto` line 81 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1354#-Nl--R4C-7jn-PMxWgiv:-NlYugqUBae61l8KSELz:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4d24334c6de90b405d9c4563243d36c1db80f768/src/main/proto/wfa/measurement/internal/reporting/measurement.proto#L81)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

I think this is v1 report. No need to update v1 report.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-12-14 21:37 UTC, stevenwarejones requested changes
> Reviewed 1 of 5 files at r6, 2 of 2 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1354)* status: 14 of 15 files reviewed, 2 unresolved discussions (waiting on @jojijac0b, @kungfucraig, @SanjayVas, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 1610 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1354#-NkzoXgu6B2zwwtpz5Be:-NleFqtlDXawPu32UQx9:b-3vyb80) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4d24334c6de90b405d9c4563243d36c1db80f768/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L1610)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

shouldn't this just be
```
populationCount = calculatePopulationResult(metric.weightedMeasurementsList.single())
```
Since there will only be one item in this list? I can't image a scenario when there wouldn't be @tristanvuong2021 @kungfucraig
</blockquote></details>

per slack conversation, lets just assume a single element with weight 1 for now.


<!-- Sent from Reviewable.io -->

2023-12-14 23:26 UTC, tristanvuong2021 reviewed
> Reviewed 2 of 12 files at r2, 2 of 3 files at r3, 1 of 2 files at r4, 2 of 5 files at r5, 3 of 5 files at r6, 2 of 2 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1354)* status: 14 of 15 files reviewed, 3 unresolved discussions (waiting on @jojijac0b, @kungfucraig, and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/reporting/bff/v1alpha/metric.proto` line 105 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1354#-NkvOiZJChQJy59NXvho:-NleTc06AbhDZPzeuhVN:bcrk26l) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/57ea39a3271d27b60568d2fbf843da1f8c4026d6/src/main/proto/wfa/measurement/reporting/bff/v1alpha/metric.proto#L105)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

see may other comments about not needing these fields - @tristanvuong2021 - do we need to cover reportin/bff/v1alpha
</blockquote></details>

This doesn't need to be covered right now.
___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsServiceTest.kt` line 7524 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1354#-NleZW439QUM1zypWy-v:-NleZW439QUM1zypWy-w:b-o5nzyf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/53ebff6a77558b97f5e91eba0158d60c6874ca5f/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsServiceTest.kt#L7524)):*
> ```Kotlin
>       )
> 
>   capturedMeasurementRequests.forEach { capturedMeasurementRequest ->
> ```

nit: Don't need a loop here since you are only capturing 1 request.


<!-- Sent from Reviewable.io -->

2023-12-14 23:56 UTC, tristanvuong2021 requested changes
> Reviewed 1 of 5 files at r6.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1354)* status: all files reviewed, 4 unresolved discussions (waiting on @jojijac0b, @kungfucraig, @riemanli, and @SanjayVas)

___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsServiceTest.kt` line 1318 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1354#-NlekRTK7NLe7ku0JAqe:-NlekRTK7NLe7ku0JAqf:bw94jne) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/53ebff6a77558b97f5e91eba0158d60c6874ca5f/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsServiceTest.kt#L1318)):*
> ```Kotlin
>     measurementSpec =
>       signMeasurementSpec(
>         POPULATION_MEASUREMENT_SPEC.copy {
> ```

Why is the POPULATION_MEASUREMENT_SPEC created then modified here instead of just using it as is.


<!-- Sent from Reviewable.io -->

2023-12-15 17:08 UTC, kungfucraig requested changes
> Reviewed 1 of 5 files at r5, 2 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1354)* status: all files reviewed, 6 unresolved discussions (waiting on @jojijac0b, @riemanli, and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/internal/reporting/v2/measurement.proto` line 123 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1354#-NliRVbR3F1bFfVQVlBM:-NliRVbR3F1bFfVQVlBN:be1jumy) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/53ebff6a77558b97f5e91eba0158d60c6874ca5f/src/main/proto/wfa/measurement/internal/reporting/v2/measurement.proto#L123)):*
> ```proto
>       int64 value = 1;
> 
>       oneof methodology {
> ```

@riemanli Does methodology make sense for Population? I'm apt to say it does not.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto` line 237 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1354#-NliRgVlE6k4ZMO1z4iq:-NliRgVlE6k4ZMO1z4ir:bhkl8wv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/53ebff6a77558b97f5e91eba0158d60c6874ca5f/src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto#L237)):*
> ```proto
>     // Only available if the Population Data Provider provides the population
>     // variance.
>     UnivariateStatistics univariate_statistics = 2;
> ```

@riemanli Similar to the methodology field above. I don't think this makes sense.


<!-- Sent from Reviewable.io -->

2023-12-18 15:12 UTC, stevenwarejones reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1354)* status: all files reviewed, 6 unresolved discussions (waiting on @jojijac0b, @kungfucraig, @riemanli, and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/internal/reporting/v2/measurement.proto` line 123 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1354#-NliRVbR3F1bFfVQVlBM:-NlxTXl-9-8q88wa7W69:b5qi1rg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/53ebff6a77558b97f5e91eba0158d60c6874ca5f/src/main/proto/wfa/measurement/internal/reporting/v2/measurement.proto#L123)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

@riemanli Does methodology make sense for Population? I'm apt to say it does not.
</blockquote></details>

it will have a custom methodology always, probably. It might be nice if they reported the variance.

What if we only have the custom_direct_methodology field right now and drop the deterministic_count?
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto` line 237 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1354#-NliRgVlE6k4ZMO1z4iq:-NlxTv8nCxbn0g62PObu:b2q4kut) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/53ebff6a77558b97f5e91eba0158d60c6874ca5f/src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto#L237)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

@riemanli Similar to the methodology field above. I don't think this makes sense.
</blockquote></details>

the PDP could still report the variance of the population measurement, right?


<!-- Sent from Reviewable.io -->

2023-12-21 02:40 UTC, riemanli requested changes
> Reviewed 2 of 12 files at r2, 2 of 3 files at r3, 1 of 2 files at r4, 2 of 5 files at r5, 3 of 5 files at r6, 1 of 2 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1354)* status: all files reviewed, 19 unresolved discussions (waiting on @jojijac0b, @kungfucraig, @SanjayVas, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/MetricReader.kt` line 398 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1354#-Nm-91R4B-1EFUCl5JuN:-Nm-91R4B-1EFUCl5JuO:brbo8f7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/53ebff6a77558b97f5e91eba0158d60c6874ca5f/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/MetricReader.kt#L398)):*
> ```Kotlin
> 
>         val metricSpec = metricSpec {
>           when (metricType) {
> ```

'when' expression must be exhaustive. Add necessary 'POPULATION_COUNT' branch explicitly.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/MetricReader.kt` line 749 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1354#-Nm9E_FAEevLnwJCiVLV:-Nm9E_FAEevLnwJCiVLW:b-7ropln) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/53ebff6a77558b97f5e91eba0158d60c6874ca5f/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/MetricReader.kt#L749)):*
> ```Kotlin
>               }
>               MetricSpec.TypeCase.POPULATION_COUNT -> {
>                 populationCount = MetricSpecKt.populationCountParams {  }
> ```

ditto



_Code quote:_
```Kotlin
populationCount = MetricSpecKt.populationCountParams {  }
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateMetrics.kt` line 250 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1354#-Nm9DxC0Cu8sW0hi7wS7:-Nm9DxC0Cu8sW0hi7wS8:b1tq5le) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/53ebff6a77558b97f5e91eba0158d60c6874ca5f/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateMetrics.kt#L250)):*
> ```Kotlin
>                   bind<Long?>("$20", null)
>                 }
>                 MetricSpec.TypeCase.POPULATION_COUNT -> {}
> ```

I don't think this would work as the row `DifferentialPrivacyEpsilon` and the row `DifferentialPrivacyDelta` are `NOT NULL`. 

cc @tristanvuong2021 



_Code quote:_
```Kotlin
MetricSpec.TypeCase.POPULATION_COUNT -> {}
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricSpecDefaults.kt` line 54 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1354#-Nm-5LrW-aJIdG25ihH8:-Nm-5LrW-aJIdG25ihH9:buussz9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/53ebff6a77558b97f5e91eba0158d60c6874ca5f/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricSpecDefaults.kt#L54)):*
> ```Kotlin
>         MetricSpec.TypeCase.POPULATION_COUNT -> {
>           populationCount = MetricSpecKt.populationCountParams {}
>           MetricSpecConfigKt.vidSamplingInterval {}
> ```

We prefer to use `*.getDefaultInstance()` instead. For example, `MetricSpec.PopulationCountParams.getDefaultInstance()`.



_Code quote:_
```Kotlin
          populationCount = MetricSpecKt.populationCountParams {}
          MetricSpecConfigKt.vidSamplingInterval {}
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 1610 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1354#-NkzoXgu6B2zwwtpz5Be:-Nm5ZQ94E-9j6ZI4X-Iv:bi9y9r7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4d24334c6de90b405d9c4563243d36c1db80f768/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L1610)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

per slack conversation, lets just assume a single element with weight 1 for now.
</blockquote></details>

If so, I would suggest to explain this in the API and also at where the implement code is.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 491 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1354#-Nm5WHwF8l5j738t__5I:-Nm5WHwF8l5j738t__5J:b-7ropln) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/53ebff6a77558b97f5e91eba0158d60c6874ca5f/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L491)):*
> ```Kotlin
>           }
>           InternalMetricSpec.TypeCase.POPULATION_COUNT -> {
>             population = MeasurementSpecKt.population { }
> ```

ditto



_Code quote:_
```Kotlin
population = MeasurementSpecKt.population { }
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 499 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1354#-Nm5WRuO40n_6jG4VbD3:-Nm5WRuO40n_6jG4VbD4:b-kno3pq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/53ebff6a77558b97f5e91eba0158d60c6874ca5f/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L499)):*
> ```Kotlin
>         }
>         vidSamplingInterval = metricSpec.vidSamplingInterval.toCmmsVidSamplingInterval()
>         //TODO: jojijac0b add modelLine
> ```

Please follow our [TODO format](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/docs/code-style.md#format), i.e. `// TODO(@jojijac0b): <description>`



_Code quote:_
```Kotlin
//TODO: jojijac0b add modelLine
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 1766 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1354#-Nm5aJus10Q8VCsRXFN9:-Nm5aJus10Q8VCsRXFNA:b667clv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/53ebff6a77558b97f5e91eba0158d60c6874ca5f/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L1766)):*
> ```Kotlin
>   }
>   return populationCountResult {
>     value = weightedMeasurements.first().measurement.details.resultsList.first().population.value
> ```

Would be nice to have a comment explaining why only using the first one.



_Code quote:_
```Kotlin
weightedMeasurements.first()
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 1766 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1354#-Nm5aTB14af7lbhHhs3u:-Nm5aTB14af7lbhHhs3v:b-gpg4y9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/53ebff6a77558b97f5e91eba0158d60c6874ca5f/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L1766)):*
> ```Kotlin
>   }
>   return populationCountResult {
>     value = weightedMeasurements.first().measurement.details.resultsList.first().population.value
> ```

I would suggest still using `aggregateResults` even there is only one result in the list.



_Code quote:_
```Kotlin
measurement.details.resultsList.first()
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ProtoConversions.kt` line 168 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1354#-Nm9AoA_-en-1B045osM:-Nm9AoA_-en-1B045osN:b-7ropln) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/53ebff6a7 [...]

2023-12-21 20:28 UTC, jojijac0b reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1354)* status: 8 of 15 files reviewed, 18 unresolved discussions (waiting on @kungfucraig, @riemanli, @SanjayVas, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/MetricReader.kt` line 398 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1354#-Nm-91R4B-1EFUCl5JuN:-NmCt4RkBgKvULbUIpNA:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/53ebff6a77558b97f5e91eba0158d60c6874ca5f/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/MetricReader.kt#L398)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

'when' expression must be exhaustive. Add necessary 'POPULATION_COUNT' branch explicitly.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/MetricReader.kt` line 749 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1354#-Nm9E_FAEevLnwJCiVLV:-NmCzZfH9Gs6ARkpdLre:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/53ebff6a77558b97f5e91eba0158d60c6874ca5f/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/MetricReader.kt#L749)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateMetrics.kt` line 250 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1354#-Nm9DxC0Cu8sW0hi7wS7:-NmCsvlQEc4U1ZhPydDd:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/53ebff6a77558b97f5e91eba0158d60c6874ca5f/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateMetrics.kt#L250)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

I don't think this would work as the row `DifferentialPrivacyEpsilon` and the row `DifferentialPrivacyDelta` are `NOT NULL`. 

cc @tristanvuong2021
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricSpecDefaults.kt` line 54 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1354#-Nm-5LrW-aJIdG25ihH8:-NmCsn93AD5dVKQcRCct:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/53ebff6a77558b97f5e91eba0158d60c6874ca5f/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricSpecDefaults.kt#L54)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

We prefer to use `*.getDefaultInstance()` instead. For example, `MetricSpec.PopulationCountParams.getDefaultInstance()`.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 491 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1354#-Nm5WHwF8l5j738t__5I:-NmCsmBL3R6-LfN-Vs4I:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/53ebff6a77558b97f5e91eba0158d60c6874ca5f/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L491)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 499 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1354#-Nm5WRuO40n_6jG4VbD3:-NmCzanI21KRXgYlv5DW:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/53ebff6a77558b97f5e91eba0158d60c6874ca5f/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L499)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Please follow our [TODO format](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/docs/code-style.md#format), i.e. `// TODO(@jojijac0b): <description>`
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 1766 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1354#-Nm5aJus10Q8VCsRXFN9:-NmCsbtaD1u0Zogl0t0o:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/53ebff6a77558b97f5e91eba0158d60c6874ca5f/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L1766)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Would be nice to have a comment explaining why only using the first one.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 1766 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1354#-Nm5aTB14af7lbhHhs3u:-NmCscJp6gIovH_IuEEc:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/53ebff6a77558b97f5e91eba0158d60c6874ca5f/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L1766)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

I would suggest still using `aggregateResults` even there is only one result in the list.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ProtoConversions.kt` line 168 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1354#-Nm9AoA_-en-1B045osM:-NmCsY6L3J7nZtKZD0nj:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/53ebff6a77558b97f5e91eba0158d60c6874ca5f/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ProtoConversions.kt#L168)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ProtoConversions.kt` line 316 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1354#-Nm9AzAr0h2ESJreBSmF:-NmCsWZ0EGwVUYoyjVjm:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/53ebff6a77558b97f5e91eba0158d60c6874ca5f/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ProtoConversions.kt#L316)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ProtoConversions.kt` line 324 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1354#-Nm9B1pR6wXru2MHRYSo:-NmCsVSbDHFUiaj-YBIP:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/53ebff6a77558b97f5e91eba0158d60c6874ca5f/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ProtoConversions.kt#L324)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ProtoConversions.kt` line 411 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1354#-Nm9Bcct-FYZlI02wrUv:-NmCsU0g5vz2CFjxh7iq:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/53ebff6a7755 [...]

2023-12-21 23:29 UTC, tristanvuong2021 requested changes
> Reviewed 2 of 6 files at r10, 4 of 6 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1354)* status: 12 of 15 files reviewed, 21 unresolved discussions (waiting on @jojijac0b, @kungfucraig, @riemanli, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/MetricReader.kt` line 751 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1354#-NmDgbLl8By4shfJAgIc:-NmDgbLl8By4shfJAgId:b-gqp7z6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ecc9f12620c615bd94651902c456eb37cd56addc/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/MetricReader.kt#L751)):*
> ```Kotlin
>                   }
>               }
>               MetricSpec.TypeCase.POPULATION_COUNT -> {
> ```

Test missing for changes to this file.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateMetrics.kt` line 252 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1354#-NmDgeXS2ElgKBGZg2GZ:-NmDgeXS2ElgKBGZg2G_:b-2txgkw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ecc9f12620c615bd94651902c456eb37cd56addc/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateMetrics.kt#L252)):*
> ```Kotlin
>                 }
>                 MetricSpec.TypeCase.POPULATION_COUNT -> {
>                   bind("$9", DifferentialPrivacyParams.getDefaultInstance().epsilon)
> ```

Test missing for changes to this file
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ProtoConversions.kt` line 426 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1354#-NmDfXIn-ZvAK3NHeXGH:-NmDfXIo1jBc8-c4K0Zh:b-dracst) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ecc9f12620c615bd94651902c456eb37cd56addc/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ProtoConversions.kt#L426)):*
> ```Kotlin
>     if (source.hasPopulation()) {
>       // Methodology in protocolCOnfig is not set for Population so it is not needed to convert to
>       // internal Populaiton
> ```

nit: Populaition should be Population
___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsServiceTest.kt` line 7464 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1354#-NmDhTXz9KDFMyi-yonH:-NmDhTXz9KDFMyi-yonI:b-pt1krk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ecc9f12620c615bd94651902c456eb37cd56addc/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsServiceTest.kt#L7464)):*
> ```Kotlin
> 
>   @Test
>   fun `createMetric creates CMMS measurements for population`() = runBlocking {
> ```

Need test for when CMMS measurement with Population result is retrieved.


<!-- Sent from Reviewable.io -->

2023-12-22 02:49 UTC, riemanli reviewed
> Reviewed 3 of 6 files at r10, 4 of 6 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1354)* status: 14 of 15 files reviewed, 8 unresolved discussions (waiting on @jojijac0b, @kungfucraig, @SanjayVas, @stevenwarejones, and @tristanvuong2021)



<!-- Sent from Reviewable.io -->

2023-12-27 18:24 UTC, jojijac0b reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1354)* status: 11 of 16 files reviewed, 7 unresolved discussions (waiting on @kungfucraig, @riemanli, @SanjayVas, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/MetricReader.kt` line 751 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1354#-NmDgbLl8By4shfJAgIc:-NmgVzWg2riVGeQw6sB_:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ecc9f12620c615bd94651902c456eb37cd56addc/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/MetricReader.kt#L751)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Test missing for changes to this file.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateMetrics.kt` line 252 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1354#-NmDgeXS2ElgKBGZg2GZ:-NmgVyZb6fOUYKd5Imwk:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ecc9f12620c615bd94651902c456eb37cd56addc/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateMetrics.kt#L252)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Test missing for changes to this file
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 1610 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1354#-NkzoXgu6B2zwwtpz5Be:-NmgW13t8yBTppG5-prr:bxeicv5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4d24334c6de90b405d9c4563243d36c1db80f768/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L1610)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

If so, I would suggest to explain this in the API and also at where the implement code is.
</blockquote></details>

Coments explaining this added in calculatePopulationResult() 
___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsServiceTest.kt` line 7464 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1354#-NmDhTXz9KDFMyi-yonH:-NmgVthe5yE4BRdwVnz6:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ecc9f12620c615bd94651902c456eb37cd56addc/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsServiceTest.kt#L7464)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Need test for when CMMS measurement with Population result is retrieved.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-12-28 18:34 UTC, tristanvuong2021 requested changes
> Reviewed 2 of 6 files at r12, 4 of 4 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1354)* status: all files reviewed, 5 unresolved discussions (waiting on @jojijac0b, @kungfucraig, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/v2/MetricsServiceTest.kt` line 525 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1354#-NmlgXLC0SD8WFwmjXAD:-NmlgXLD4PuyqKNuOsbb:bhzx558) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/111a728c69475bb9c036091378cb20cb43193bf5/src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/v2/MetricsServiceTest.kt#L525)):*
> ```Kotlin
>       )
> 
>     assertThat(createdMetric.externalMetricId).isNotEqualTo(0)
> ```

I noticed that this needs to be fixed in other tests in this file as well, which should be done in another PR, but externalMetricId is a string so the assertion should be that it is not empty.


<!-- Sent from Reviewable.io -->

2023-12-28 20:31 UTC, jojijac0b reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1354)* status: 15 of 16 files reviewed, 5 unresolved discussions (waiting on @kungfucraig, @SanjayVas, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/v2/MetricsServiceTest.kt` line 525 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1354#-NmlgXLC0SD8WFwmjXAD:-Nmm6w8ZB9Qzz510Y0aA:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/111a728c69475bb9c036091378cb20cb43193bf5/src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/v2/MetricsServiceTest.kt#L525)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

I noticed that this needs to be fixed in other tests in this file as well, which should be done in another PR, but externalMetricId is a string so the assertion should be that it is not empty.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-12-28 20:31 UTC, tristanvuong2021 approved these changes
> Reviewed 1 of 1 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1354)* status: all files reviewed, 4 unresolved discussions (waiting on @kungfucraig, @SanjayVas, and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2024-01-02 20:20 UTC, kungfucraig requested changes
> Reviewed 1 of 6 files at r12.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1354)* status: 13 of 17 files reviewed, 4 unresolved discussions (waiting on @riemanli, @SanjayVas, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/internal/reporting/v2/measurement.proto` line 123 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1354#-NliRVbR3F1bFfVQVlBM:-NnAoyzp5tONJjw_EAS9:bspltv3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/53ebff6a77558b97f5e91eba0158d60c6874ca5f/src/main/proto/wfa/measurement/internal/reporting/v2/measurement.proto#L123)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

@kungfucraig @stevenwarejones could you provide the final decision from the eng discussion meeting?
</blockquote></details>

We decided to drop methodology for Population as it won't be useful today, and it would be easy to add in the future should it become necessary.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto` line 237 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1354#-NliRgVlE6k4ZMO1z4iq:-NlxbC563ZKeiZ3nR-QI:bspltv3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/53ebff6a77558b97f5e91eba0158d60c6874ca5f/src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto#L237)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

@kungfucraig @stevenwarejones could you provide the final decision from the eng discussion meeting?
</blockquote></details>

We decided to drop methodology for Population as it won't be useful today, and it would be easy to add in the future should it become necessary.


<!-- Sent from Reviewable.io -->

2024-01-02 20:34 UTC, riemanli commented
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto` line 237 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1354#-NliRgVlE6k4ZMO1z4iq:-NnAsJwa-ADuJEDisqk9:b-gsydib) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/53ebff6a77558b97f5e91eba0158d60c6874ca5f/src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto#L237)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

We decided to drop methodology for Population as it won't be useful today, and it would be easy to add in the future should it become necessary.
</blockquote></details>

I assume this also means that `UnivariateStatistics` is dropped as well.


<!-- Sent from Reviewable.io -->

2024-01-02 20:34 UTC, riemanli reviewed
> Reviewed 2 of 4 files at r13.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1354)* status: 13 of 17 files reviewed, 4 unresolved discussions (waiting on @kungfucraig, @SanjayVas, @stevenwarejones, and @tristanvuong2021)



<!-- Sent from Reviewable.io -->

2024-01-02 21:55 UTC, kungfucraig requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1354)* status: 13 of 17 files reviewed, 4 unresolved discussions (waiting on @riemanli, @SanjayVas, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto` line 237 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1354#-NliRgVlE6k4ZMO1z4iq:-NnBA9KO42r_IRtHLv5p:b-ht0ukm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/53ebff6a77558b97f5e91eba0158d60c6874ca5f/src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto#L237)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

I assume this also means that `UnivariateStatistics` is dropped as well.
</blockquote></details>

That's right.


<!-- Sent from Reviewable.io -->

2024-01-03 00:24 UTC, stevenwarejones requested changes
> Reviewed 1 of 6 files at r10, 4 of 6 files at r12, 2 of 4 files at r13, 4 of 4 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1354)* status: all files reviewed, 9 unresolved discussions (waiting on @jojijac0b, @kungfucraig, @SanjayVas, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateMetrics.kt` line 193 at r15](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1354#-NnBfz8s5GjQUpKySiXg:-NnBfz8t8F8H-gLCsR2w:b-gwb8go) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ce0b7da535d18bc7afeb1a10e9bb3852306d7c18/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateMetrics.kt#L193)):*
> ```Kotlin
>             val vidSamplingIntervalStart =
>               if (it.metric.metricSpec.typeCase == MetricSpec.TypeCase.POPULATION_COUNT)
>                 MetricSpec.VidSamplingInterval.getDefaultInstance().start
> ```

just make it equal to`0` which is the default
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateMetrics.kt` line 197 at r15](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1354#-NnBg3yt-ZnY2LR_H_j-:-NnBg3yt-ZnY2LR_H_j0:b-7ropln) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ce0b7da535d18bc7afeb1a10e9bb3852306d7c18/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateMetrics.kt#L197)):*
> ```Kotlin
>             val vidSamplingIntervalWidth =
>               if (it.metric.metricSpec.typeCase == MetricSpec.TypeCase.POPULATION_COUNT)
>                 MetricSpec.VidSamplingInterval.getDefaultInstance().width
> ```

ditto
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateMetrics.kt` line 259 at r15](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1354#-NnBg65i4p5nvyyL7B7L:-NnBg65i4p5nvyyL7B7M:b-7ropln) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ce0b7da535d18bc7afeb1a10e9bb3852306d7c18/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateMetrics.kt#L259)):*
> ```Kotlin
>                 }
>                 MetricSpec.TypeCase.POPULATION_COUNT -> {
>                   bind("$9", MetricSpec.DifferentialPrivacyParams.getDefaultInstance().epsilon)
> ```

ditto
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateMetrics.kt` line 260 at r15](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1354#-NnBg78JDEn7LPo4eN9E:-NnBg78JDEn7LPo4eN9F:b-7ropln) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ce0b7da535d18bc7afeb1a10e9bb3852306d7c18/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateMetrics.kt#L260)):*
> ```Kotlin
>                 MetricSpec.TypeCase.POPULATION_COUNT -> {
>                   bind("$9", MetricSpec.DifferentialPrivacyParams.getDefaultInstance().epsilon)
>                   bind("$10", MetricSpec.DifferentialPrivacyParams.getDefaultInstance().delta)
> ```

ditto
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ProtoConversions.kt` line 425 at r15](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1354#-NnBgceB6j7wQjrLqMND:-NnBgceB6j7wQjrLqMNE:b-l1355x) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ce0b7da535d18bc7afeb1a10e9bb3852306d7c18/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/ProtoConversions.kt#L425)):*
> ```Kotlin
>     }
>     if (source.hasPopulation()) {
>       // Methodology in protocolCOnfig is not set for Population so it is not needed to convert to
> ```

nit: spelling on `protocolConfig`
___
*[`src/main/proto/wfa/measurement/internal/reporting/v2/measurement.proto` line 123 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1354#-NliRVbR3F1bFfVQVlBM:-NnBh1Sl9ExFG7NQRY_b:b-9a9h1a) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/53ebff6a77558b97f5e91eba0158d60c6874ca5f/src/main/proto/wfa/measurement/internal/reporting/v2/measurement.proto#L123)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

We decided to drop methodology for Population as it won't be useful today, and it would be easy to add in the future should it become necessary.
</blockquote></details>

@jojijac0b - lets drop fields 3 & 4 for now
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto` line 237 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1354#-NliRgVlE6k4ZMO1z4iq:-NnBhATI7u1A6zQR6ur3:bi87q9b) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/53ebff6a77558b97f5e91eba0158d60c6874ca5f/src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto#L237)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

That's right.
</blockquote></details>

@jojijac0b - drop field 2


<!-- Sent from Reviewable.io -->

2024-01-03 13:36 UTC, stevenwarejones approved these changes
> Reviewed 4 of 4 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1354)* status: all files reviewed, 3 unresolved discussions (waiting on @jojijac0b, @kungfucraig, and @SanjayVas)



<!-- Sent from Reviewable.io -->

2024-01-03 15:09 UTC, stevenwarejones approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1354)* status: all files reviewed, 3 unresolved discussions (waiting on @jojijac0b, @kungfucraig, and @SanjayVas)



<!-- Sent from Reviewable.io -->

2024-01-03 17:05 UTC, kungfucraig approved these changes
> Reviewed 2 of 4 files at r16.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1354)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)



<!-- Sent from Reviewable.io -->

2024-01-03 18:00 UTC, jojijac0b reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1354)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateMetrics.kt` line 193 at r15](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1354#-NnBfz8s5GjQUpKySiXg:-NnCCIPnDM78VuR6qHmd:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ce0b7da535d18bc7afeb1a10e9bb3852306d7c18/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateMetrics.kt#L193)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

just make it equal to`0` which is the default
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateMetrics.kt` line 197 at r15](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1354#-NnBg3yt-ZnY2LR_H_j-:-NnCCIim8nqvMLBM5P0F:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ce0b7da535d18bc7afeb1a10e9bb3852306d7c18/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateMetrics.kt#L197)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateMetrics.kt` line 259 at r15](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1354#-NnBg65i4p5nvyyL7B7L:-NnCCOk83_FDNcDu-Exj:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ce0b7da535d18bc7afeb1a10e9bb3852306d7c18/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateMetrics.kt#L259)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateMetrics.kt` line 260 at r15](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1354#-NnBg78JDEn7LPo4eN9E:-NnCCP0K7jF2wrH9Jqe7:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ce0b7da535d18bc7afeb1a10e9bb3852306d7c18/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateMetrics.kt#L260)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/internal/reporting/v2/measurement.proto` line 123 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1354#-NliRVbR3F1bFfVQVlBM:-NnCCnLQ1SP0Qb0eyvNr:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/53ebff6a77558b97f5e91eba0158d60c6874ca5f/src/main/proto/wfa/measurement/internal/reporting/v2/measurement.proto#L123)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

@jojijac0b - lets drop fields 3 & 4 for now
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto` line 237 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1354#-NliRgVlE6k4ZMO1z4iq:-NnCCxwPCTpxaG0P-8HT:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/53ebff6a77558b97f5e91eba0158d60c6874ca5f/src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto#L237)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

@jojijac0b - drop field 2
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-01-03 18:08 UTC, riemanli requested changes
> Reviewed 3 of 4 files at r15, 4 of 4 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1354)* status: all files reviewed, 9 unresolved discussions (waiting on @jojijac0b and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/v2/MetricsServiceTest.kt` line 496 at r16](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1354#-NnFKbWp8tgrRQL-r_pN:-NnFKbWp8tgrRQL-r_pO:blra6ky) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/315cb02dcff67819d81545c53cd34f8614d9f82e/src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/v2/MetricsServiceTest.kt#L496)):*
> ```Kotlin
>         endTime = timestamp { seconds = 100 }
>       }
>       metricSpec = metricSpec { populationCount = MetricSpecKt.populationCountParams {} }
> ```

nit: Use `getDefaultInstance()`



_Code quote:_
```Kotlin
MetricSpecKt.populationCountParams {}
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/v2/MetricsServiceTest.kt` line 2384 at r16](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1354#-NnFKlVcArdJiKhgfZuY:-NnFKlVcArdJiKhgfZuZ:b-iipjm8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/315cb02dcff67819d81545c53cd34f8614d9f82e/src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/v2/MetricsServiceTest.kt#L2384)):*
> ```Kotlin
>           endTime = timestamp { seconds = 100 }
>         }
>         metricSpec = metricSpec { populationCount = MetricSpecKt.populationCountParams {} }
> ```

nit: ditto



_Code quote:_
```Kotlin
populationCount = MetricSpecKt.populationCountParams {}
```
___
*[`src/main/proto/wfa/measurement/internal/reporting/v2/measurement.proto` line 123 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1354#-NliRVbR3F1bFfVQVlBM:-NnFRJLo6uHeOqDDjpBA:btm8ksv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/53ebff6a77558b97f5e91eba0158d60c6874ca5f/src/main/proto/wfa/measurement/internal/reporting/v2/measurement.proto#L123)):*
<details><summary><i>Previously, jojijac0b wrote…</i></summary><blockquote>

Done.
</blockquote></details>

If we drop methodology for `Population`, we should also modify this 
https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2c253dcd79af726be9d8bb3470d3409854ce98e7/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt#L1090-L1099

Based on the decision, it should be using default direct message, i.e. no noise mechanism is allowed and no methodology is allowed. Need to be careful if this violates any check through out the system.
___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsServiceTest.kt` line 335 at r16](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1354#-NnFKp3eCQrbGTjYhHRY:-NnFKp3eCQrbGTjYhHRZ:b-iipjm8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/315cb02dcff67819d81545c53cd34f8614d9f82e/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsServiceTest.kt#L335)):*
> ```Kotlin
>     }
> 
>   populationCountParams = MetricSpecConfigKt.populationCountParams {}
> ```

nit: ditto



_Code quote:_
```Kotlin
MetricSpecConfigKt.populationCountParams {}
```
___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsServiceTest.kt` line 1306 at r16](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1354#-NnFKqnfAOpL2hQrVDZc:-NnFKqnfAOpL2hQrVDZd:b-iipjm8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/315cb02dcff67819d81545c53cd34f8614d9f82e/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsServiceTest.kt#L1306)):*
> ```Kotlin
>     )
> 
>   population = MeasurementSpecKt.population {}
> ```

nit: ditto



_Code quote:_
```Kotlin
MeasurementSpecKt.population {}
```
___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsServiceTest.kt` line 1308 at r16](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1354#-NnFKrrd7KNMTxMlofht:-NnFKrrd7KNMTxMlofhu:b-iipjm8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/315cb02dcff67819d81545c53cd34f8614d9f82e/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsServiceTest.kt#L1308)):*
> ```Kotlin
>   population = MeasurementSpecKt.population {}
> 
>   vidSamplingInterval = MeasurementSpecKt.vidSamplingInterval {}
> ```

nit: ditto



_Code quote:_
```Kotlin
MeasurementSpecKt.vidSamplingInterval {}
```
___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsServiceTest.kt` line 1365 at r16](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1354#-NnFKtbR2Lz2IG6YP602:-NnFKtbR2Lz2IG6YP603:b-iipjm8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/315cb02dcff67819d81545c53cd34f8614d9f82e/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsServiceTest.kt#L1365)):*
> ```Kotlin
> 
> private val POPULATION_METRIC_SPEC: MetricSpec = metricSpec {
>   populationCount = populationCountParams {}
> ```

nit: ditto



_Code quote:_
```Kotlin
populationCountParams {}
```
___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsServiceTest.kt` line 1684 at r16](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1354#-NnFKx-J3iP32m3H9Pqe:-NnFKx-J3iP32m3H9Pqf:b-iipjm8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/315cb02dcff67819d81545c53cd34f8614d9f82e/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsServiceTest.kt#L1684)):*
> ```Kotlin
>   timeInterval = TIME_INTERVAL
>   metricSpec = internalMetricSpec {
>     populationCount = InternalMetricSpecKt.populationCountParams {}
> ```

nit: ditto



_Code quote:_
```Kotlin
InternalMetricSpecKt.populationCountParams {}
```
___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsServiceTest.kt` line 1993 at r16](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1354#-NnFL2RQ4tOCfK1zktRz:-NnFL2RQ4tOCfK1zktS-:b-iipjm8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/315cb02dcff67819d81545c53cd34f8614d9f82e/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsServiceTest.kt#L1993)):*
> ```Kotlin
>         .toName()
>     state = Metric.State.RUNNING
>     metricSpec = metricSpec { populationCount = populationCountParams {} }
> ```

nit: ditto



_Code quote:_
```Kotlin
populationCount = populationCountParams {}
```


<!-- Sent from Reviewable.io -->

2024-01-03 20:54 UTC, riemanli requested changes
> Reviewed 1 of 3 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1354)* status: 16 of 18 files reviewed, 2 unresolved discussions (waiting on @jojijac0b, @SanjayVas, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt` line 1099 at r17](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1354#-NnG5HZr5s29J8-QTbRm:-NnG5HZr5s29J8-QTbRn:bj8o8yo) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2c253dcd79af726be9d8bb3470d3409854ce98e7/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt#L1099)):*
> ```Kotlin
>               }
>           }
>         }
> ```

I think you need to keep `protocolConfig` and set `direct` with default instance.
cc. @stevenwarejones @kungfucraig 



_Code quote:_
```Kotlin
          protocolConfig = internalProtocolConfig {
            direct =
              InternalProtocolConfigKt.direct {
                noiseMechanisms += internalNoiseMechanisms
                deterministicCount =
                  InternalProtocolConfig.Direct.DeterministicCount.getDefaultInstance()
              }
          }
        }
```


<!-- Sent from Reviewable.io -->

2024-01-04 00:53 UTC, stevenwarejones requested changes
> Reviewed 3 of 3 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1354)* status: all files reviewed, 2 unresolved discussions (waiting on @kungfucraig, @riemanli, and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt` line 1099 at r17](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1354#-NnG5HZr5s29J8-QTbRm:-NnGwv67AcKAXw0ZRSuc:bp9dips) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2c253dcd79af726be9d8bb3470d3409854ce98e7/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt#L1099)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

I think you need to keep `protocolConfig` and set `direct` with default instance.
cc. @stevenwarejones @kungfucraig
</blockquote></details>

agree
```
protocolConfig = internalProtocolConfig {
            direct = InternalProtocolConfig.Direct.getDefaultInstance()
          }
```



<!-- Sent from Reviewable.io -->

2024-01-04 15:13 UTC, kungfucraig approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1354)* status: all files reviewed, 2 unresolved discussions (waiting on @riemanli and @SanjayVas)



<!-- Sent from Reviewable.io -->

2024-01-04 15:14 UTC, kungfucraig reviewed
FYI: My approval is for the proto changes only. I did not review the Kotlin code.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1354#-:-NnK1Tny7_qD6hA5sVge:b-dez9a3)* status: all files reviewed, 2 unresolved discussions (waiting on @riemanli and @SanjayVas)



<!-- Sent from Reviewable.io -->

2024-01-04 16:34 UTC, jojijac0b reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1354)* status: 17 of 18 files reviewed, 2 unresolved discussions (waiting on @riemanli, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt` line 1099 at r17](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1354#-NnG5HZr5s29J8-QTbRm:-NnKIrpI3snlEFkfgMy6:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2c253dcd79af726be9d8bb3470d3409854ce98e7/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt#L1099)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

agree
```
protocolConfig = internalProtocolConfig {
            direct = InternalProtocolConfig.Direct.getDefaultInstance()
          }
```

</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-01-04 18:29 UTC, riemanli requested changes
> Reviewed 1 of 1 files at r18, 2 of 2 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1354)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt` line 1099 at r17](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1354#-NnG5HZr5s29J8-QTbRm:-NnKinl6--4X3N-Pfo-Q:bieeu69) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2c253dcd79af726be9d8bb3470d3409854ce98e7/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt#L1099)):*
<details><summary><i>Previously, jojijac0b wrote…</i></summary><blockquote>

Done.
</blockquote></details>

CI failed with `MeasurementsServiceTest`. Could you check if the change breaks any test or if any test needs to be modified?


<!-- Sent from Reviewable.io -->

2024-01-04 19:32 UTC, jojijac0b reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1354)* status: 14 of 19 files reviewed, 1 unresolved discussion (waiting on @riemanli, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt` line 1099 at r17](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1354#-NnG5HZr5s29J8-QTbRm:-NnKxhbeAhw9h_W4oyNn:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2c253dcd79af726be9d8bb3470d3409854ce98e7/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt#L1099)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

CI failed with `MeasurementsServiceTest`. Could you check if the change breaks any test or if any test needs to be modified?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-01-04 23:06 UTC, riemanli approved these changes
> Reviewed 5 of 5 files at r20, 1 of 1 files at r21, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1354)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SanjayVas and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2024-01-05 00:08 UTC, stevenwarejones approved these changes
> Reviewed 1 of 1 files at r18, 4 of 5 files at r20, 1 of 1 files at r21, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1354)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)



<!-- Sent from Reviewable.io -->

2024-01-05 00:08 UTC, stevenwarejones approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1354#-:-NnLwtW824i_8lhlIeq8:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)



<!-- Sent from Reviewable.io -->

2024-01-05 21:03 UTC, merged