Fix normalizing frequency distribution
world-federation-of-advertisers/cross-media-measurement pull request #1389
Opened 2024-01-04 00:41 UTC by riemanli

2024-01-04 00:41 UTC, wfa-reviewable commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1389)
<!-- Reviewable:end -->

2024-01-04 00:41 UTC, riemanli commented
Current dependencies on/for this PR:
* `main`
  * **PR #1389** <a href="https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/1389?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/1389?utm_source=stack-comment).

2024-01-04 18:02 UTC, renjiezh requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1389)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @jiayu-google, @kungfucraig, and @riemanli)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 1236 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1389#-NnKd-GJ2uCciLvN3iz0:-NnKd-GJ2uCciLvN3iz1:b-m4k2x) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/524c4b25a8e55b71661a2e8a6da1f6bf062ce3c7/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L1236)):*
> ```Kotlin
>       getPublisherNoiser(privacyParams, directNoiseMechanism, random)
> 
>     return reachValue + reachNoiser.sample().toInt()
> ```

Do we need to cap the reachValue here? Seems the noise sampled could be negative and cause reach < 0.


<!-- Sent from Reviewable.io -->

2024-01-04 18:19 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1389)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @jiayu-google and @kungfucraig)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 1236 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1389#-NnKd-GJ2uCciLvN3iz0:-NnKe32X27P6JlQ6LwyC:b-qddbke) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/524c4b25a8e55b71661a2e8a6da1f6bf062ce3c7/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L1236)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

Do we need to cap the reachValue here? Seems the noise sampled could be negative and cause reach < 0.
</blockquote></details>

We are kinda debating that. Some pros and cons.
Pros: 
1. We already cap direct frequency.
2. We can get reasonable outputs from EDPs.

Cons:
1. Downstream services can't obtain the "raw" outputs.
2. The capping is only for direct. For MPC EDP doesn't cap, which makes it inconsistent.

I am now leaning toward cap the negative reach values as we are already doing it for direct frequency in this PR.

@jiayu-google @kungfucraig WDYT?


<!-- Sent from Reviewable.io -->

2024-01-04 18:27 UTC, jiayu-google reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1389)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @kungfucraig)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 1236 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1389#-NnKd-GJ2uCciLvN3iz0:-NnKhtOTAhJbqYqDEnaa:b-3n5oer) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/524c4b25a8e55b71661a2e8a6da1f6bf062ce3c7/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L1236)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

We are kinda debating that. Some pros and cons.
Pros: 
1. We already cap direct frequency.
2. We can get reasonable outputs from EDPs.

Cons:
1. Downstream services can't obtain the "raw" outputs.
2. The capping is only for direct. For MPC EDP doesn't cap, which makes it inconsistent.

I am now leaning toward cap the negative reach values as we are already doing it for direct frequency in this PR.

@jiayu-google @kungfucraig WDYT?
</blockquote></details>

yes, now I'm also leaning towards capping the negative reaches. Another reason is that we always cap negative reaches in MPC.

On a barely related note, we should NOT cap impressions. This is because if we cap the daily impressions, we can get a cumulative bias for cumulative impressions. 


<!-- Sent from Reviewable.io -->

2024-01-04 19:33 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1389)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @kungfucraig)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 1236 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1389#-NnKd-GJ2uCciLvN3iz0:-NnKxvjNC720piGBWigb:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/524c4b25a8e55b71661a2e8a6da1f6bf062ce3c7/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L1236)):*
<details><summary><i>Previously, jiayu-google wrote…</i></summary><blockquote>

yes, now I'm also leaning towards capping the negative reaches. Another reason is that we always cap negative reaches in MPC.

On a barely related note, we should NOT cap impressions. This is because if we cap the daily impressions, we can get a cumulative bias for cumulative impressions.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-01-04 19:47 UTC, renjiezh reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1389)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @jiayu-google and @kungfucraig)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 1236 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1389#-NnKd-GJ2uCciLvN3iz0:-NnL-rmA1-7YVE77jZbB:b-e79t0v) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/524c4b25a8e55b71661a2e8a6da1f6bf062ce3c7/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L1236)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

nit: is this way better?
`max(0, reachValue + reachNoiser.sample().toInt())`


<!-- Sent from Reviewable.io -->

2024-01-04 21:31 UTC, renjiezh approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 3 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1389#-:-NnLNrvB7DWD3YISVGEd:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jiayu-google and @kungfucraig)



<!-- Sent from Reviewable.io -->

2024-01-04 22:01 UTC, jiayu-google approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1389#-:-NnLUlDm8K3ph2_eZSuE:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @kungfucraig)



<!-- Sent from Reviewable.io -->

2024-01-05 16:48 UTC, kungfucraig approved these changes
> Reviewed 2 of 3 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1389)* status: all files reviewed, 1 unresolved discussion (waiting on @Marco-Premier, @riemanli, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 1236 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1389#-NnKd-GJ2uCciLvN3iz0:-NnPWB5z4n1qGJcw8GqZ:bb7ohn6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/524c4b25a8e55b71661a2e8a6da1f6bf062ce3c7/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L1236)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Done
</blockquote></details>

sgtm
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 1517 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1389#-NnPWXPu8VOzDKfaddqc:-NnPWXPu8VOzDKfaddqd:bogs6v4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/93e9e35ab371255743c0aa674f94f153aa39b088/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L1517)):*
> ```Kotlin
>     measurementResult: Measurement.Result
>   ) {
>     val requisitionCertificateKey =
> ```

Undo this extraneous change?


<!-- Sent from Reviewable.io -->

2024-01-05 17:34 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1389)* status: all files reviewed, 1 unresolved discussion (waiting on @Marco-Premier and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 1517 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1389#-NnPWXPu8VOzDKfaddqc:-NnPezzP4nOVkr3BnTEi:bacp6qf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/93e9e35ab371255743c0aa674f94f153aa39b088/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L1517)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Undo this extraneous change?
</blockquote></details>

This unused variable causes a warning. Unless we will open a PR specifically to remove it, I think it's ok to be removed in this PR. This variable was introduced in #1313 by @stevenwarejones. If it's ok, let's let Steven make the judgement call. 


<!-- Sent from Reviewable.io -->

2024-01-05 17:59 UTC, kungfucraig approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1389)* status: all files reviewed, 1 unresolved discussion (waiting on @Marco-Premier and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 1517 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1389#-NnPWXPu8VOzDKfaddqc:-NnPlpZzE-joU5h3uIAH:b32wwp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/93e9e35ab371255743c0aa674f94f153aa39b088/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L1517)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

This unused variable causes a warning. Unless we will open a PR specifically to remove it, I think it's ok to be removed in this PR. This variable was introduced in #1313 by @stevenwarejones. If it's ok, let's let Steven make the judgement call.
</blockquote></details>

sg


<!-- Sent from Reviewable.io -->

2024-01-05 17:59 UTC, kungfucraig approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1389)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Marco-Premier and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2024-01-05 21:40 UTC, riemanli reviewed
Adding a new change of rounding noise added to the frequency

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1389#-:-NnQZMyzDQqdWI7jHb5-:b8ytjc)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @jiayu-google, @kungfucraig, @Marco-Premier, @renjiezh, and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2024-01-05 23:06 UTC, kungfucraig approved these changes
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1389)* status: all files reviewed, 1 unresolved discussion (waiting on @jiayu-google, @Marco-Premier, @riemanli, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 1261 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1389#-NnQsByYE4GddGJv5g4i:-NnQsByYE4GddGJv5g4j:b-wjuxc8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9513a7511d581c176e9b46a43354a31fc4e5d823/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L1261)):*
> ```Kotlin
>       frequencyMap.mapValues { (_, percentage) ->
>         // Round the noise for privacy.
>         val noisedCount: Int =
> ```

You can add them first and then round if you want, though either way is fine I suppose.


<!-- Sent from Reviewable.io -->

2024-01-05 23:08 UTC, jiayu-google approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1389#-:-NnQsj4t8wCkQ3holNU0:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @Marco-Premier, @riemanli, and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2024-01-05 23:10 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1389)* status: all files reviewed, 1 unresolved discussion (waiting on @kungfucraig, @Marco-Premier, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 1261 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1389#-NnQsByYE4GddGJv5g4i:-NnQsNcR43Gs6tHMy6SC:b-ehtsct) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9513a7511d581c176e9b46a43354a31fc4e5d823/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L1261)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

You can add them first and then round if you want, though either way is fine I suppose.
</blockquote></details>

Trying to avoid possible incorrect rounding due to numerical error. Maybe I am being too cautious :)


<!-- Sent from Reviewable.io -->

2024-01-08 17:57 UTC, kungfucraig approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1389)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Marco-Premier and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2024-01-08 19:07 UTC, stevenwarejones approved these changes
> Reviewed 2 of 3 files at r1, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1389)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Marco-Premier)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 1517 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1389#-NnPWXPu8VOzDKfaddqc:-NneT9uQ5CGxMprI0QpU:bb7ohn6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/93e9e35ab371255743c0aa674f94f153aa39b088/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L1517)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

sg
</blockquote></details>

sgtm


<!-- Sent from Reviewable.io -->

2024-01-08 20:00 UTC, merged