Implement Internal Certificates Service
world-federation-of-advertisers/cross-media-measurement pull request #139
Opened 2021-07-02 01:45 UTC by uakyol

2021-07-12 05:26 UTC, uakyol commented
I need help with Duchies.

1) In measurements.sdl, we defined duchyids as ints : https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl#L275

But the proto messages are strings : https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/main/proto/wfa/measurement/internal/kingdom/certificate.proto#L28

How should we make the conversion between these fields.

2) We were thinking about having a duchies table or a config file. Did we end up making a decision on that?

2021-07-12 15:27 UTC, SanjayVas commented
> 1. In measurements.sdl, we defined duchyids as ints : https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/measurement.sdl#L275
>
> But the proto messages are strings : https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/main/proto/wfa/measurement/internal/kingdom/certificate.proto#L28

The internal IDs are ints and the external IDs are strings. There isn't a conversion, but rather a mapping.
 
> 2. We were thinking about having a duchies table or a config file. Did we end up making a decision on that?

Yes, we'll have a config file. It hasn't been added yet. You can do so as part of this PR. It would be similar to [DuchyRpcConfig](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b899f8bd4d2641709569f32be90198516cd68a1d/src/main/proto/wfa/measurement/config/duchy_rpc_config.proto), but primarily consist of a mapping of external ID to internal ID.

2021-07-16 17:36 UTC, uakyol commented
Thank you for the explanation @SanjayVas . If you don't mind, I decided to add TODOs here and leave the duchy part for the next PR. It is better to do this piecemeal.

2021-07-16 19:36 UTC, SanjayVas requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139)* status: 0 of 29 files reviewed, 3 unresolved discussions (waiting on @uakyol and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerCertificatesService.kt, line 31 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139#-Meko9AB8SNkL-WfJaNI:-Meko9AB8SNkL-WfJaNJ:b-80r1ng) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2f2a7951c1f167d07c4d467c633dc5d893a09b9a/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerCertificatesService.kt#L31)):*
> ```
> private const val DATA_PROVIDER = "DataProvider"
> private const val MEASUREMENT_CONSUMER = "MeasurementConsumer"
> private const val DUCHY = "Duchy"
> ```
This should be an enum with a string property (don't use `name` or `value` as those concepts already exist with enums).
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerCertificatesService.kt, line 36 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139#-Mekme89DbS-BXpJt94Y:-Mekme8A95dtiSN_T30q:b-2tkejw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2f2a7951c1f167d07c4d467c633dc5d893a09b9a/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerCertificatesService.kt#L36)):*
> ```Kotlin
> 
> class SpannerCertificatesService(
>   val clock: Clock,
> ```

Do these properties need to be public?
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/CertificateReader.kt, line 56 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139#-MeknQDC0qE1H0_27G3d:-MeknQDC0qE1H0_27G3e:bo93lts) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2f2a7951c1f167d07c4d467c633dc5d893a09b9a/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/CertificateReader.kt#L56)):*
> ```
> "External${resourceName}Id"
> ```
1. This makes me think that `resourceName` is misnamed, as a resource name would be something like `measurementConsumers/acbd123`.
2. Resources are a public/system API concept, and not something that the internal service layer cares about. Maybe what you care about is the name of the table, so something like `ownerTable`?


<!-- Sent from Reviewable.io -->

2021-07-19 23:21 UTC, uakyol reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139)* status: 0 of 29 files reviewed, 3 unresolved discussions (waiting on @oliver-amzn, @SanjayVas, @wangyaopw, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerCertificatesService.kt, line 31 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139#-Meko9AB8SNkL-WfJaNI:-Mf03N0s-gC0sJWGYbvr:bn3d3ms) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2f2a7951c1f167d07c4d467c633dc5d893a09b9a/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerCertificatesService.kt#L31)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> private const val DATA_PROVIDER = "DataProvider"
> private const val MEASUREMENT_CONSUMER = "MeasurementConsumer"
> private const val DUCHY = "Duchy"
> ```
This should be an enum with a string property (don't use `name` or `value` as those concepts already exist with enums).
</blockquote></details>

thanks, I added the Enum class in CertificateReader since both the writer and the service depends on it. Also named it Owner, I can change it if it sounds too generic
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerCertificatesService.kt, line 36 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139#-Mekme89DbS-BXpJt94Y:-Mel0dkC0JuwnjWDfS9W:b8pd1t8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2f2a7951c1f167d07c4d467c633dc5d893a09b9a/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerCertificatesService.kt#L36)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Do these properties need to be public?
</blockquote></details>

definitely not. I changed it here. Also changed the others in #156 
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/CertificateReader.kt, line 56 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139#-MeknQDC0qE1H0_27G3d:-Mel0oP3-cLwUHAXkAHH:b-bz564a) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2f2a7951c1f167d07c4d467c633dc5d893a09b9a/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/CertificateReader.kt#L56)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> "External${resourceName}Id"
> ```
1. This makes me think that `resourceName` is misnamed, as a resource name would be something like `measurementConsumers/acbd123`.
2. Resources are a public/system API concept, and not something that the internal service layer cares about. Maybe what you care about is the name of the table, so something like `ownerTable`?
</blockquote></details>

thank you yes, ownerTable sounds better


<!-- Sent from Reviewable.io -->

2021-07-21 21:24 UTC, wangyaopw requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139)* status: 0 of 29 files reviewed, 6 unresolved discussions (waiting on @oliver-amzn, @SanjayVas, @uakyol, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/CertificateReader.kt, line 60 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139#-Mf9swAI6HqZJtUxatw1:-Mf9swAI6HqZJtUxatw2:b-rse2j4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9b095c88982fb90d97ab79ad938254e6b0bdb8dc/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/CertificateReader.kt#L60)):*
<details><summary><i alt="summary">Quoted 11 lines of code…</i></summary>

> ```
>     if (owner == Owner.MEASUREMENT_CONSUMER) {
>       return certificateBuilder
>         .setExternalMeasurementConsumerId(struct.getLong(externalResourceIdColumn))
>         .build()
>     }
>     if (owner == Owner.DATA_PROVIDER) {
>       return certificateBuilder
>         .setExternalDataProviderId(struct.getLong(externalResourceIdColumn))
>         .build()
>     }
>     return TODO("uakyol implement duchy support after duchy config is implemented")
> ```
</details>


maybe

```
return certificateBuilder.apply{
  when(owner) {
     Owner.MEASUREMENT_CONSUMER -> externalMeasurementConsumerId = struct.getLong(externalResourceIdColumn)
     Owner.DATA_PROVIDER -> externalDataProviderId = struct.getLong(externalResourceIdColumn)
     Owner.DUCHY -> TODO
}.build() 
```
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/DataProviderReader.kt, line 57 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139#-Mf9vDlv1HQbc31U0PQE:-Mf9vDlv1HQbc31U0PQF:b-uhqaht) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9b095c88982fb90d97ab79ad938254e6b0bdb8dc/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/DataProviderReader.kt#L57)):*
> ```
> details = struct.getProtoMessage("DataProviderDetails", DataProvider.Details.parser())
> ```
is this line redundant?
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/CertificatesServiceTest.kt, line 128 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139#-Mf9ww392li_lHMVyG45:-Mf9ww392li_lHMVyG46:b78sius) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9b095c88982fb90d97ab79ad938254e6b0bdb8dc/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/CertificatesServiceTest.kt#L128)):*
> ```
> getCertificate fails
> ```

I feel "createCertificate fails due to owner not_found" is more interesting. can you add one test for it?


<!-- Sent from Reviewable.io -->

2021-07-21 23:17 UTC, SanjayVas requested changes
> Reviewed 1 of 29 files at r1, 1 of 3 files at r4, 5 of 9 files at r6.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139)* status: 7 of 29 files reviewed, 15 unresolved discussions (waiting on @oliver-amzn, @SanjayVas, @uakyol, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerCertificatesService.kt, line 31 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139#-Meko9AB8SNkL-WfJaNI:-Mf9uiF-E9Tw5_D1rcz6:b5nut7z) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2f2a7951c1f167d07c4d467c633dc5d893a09b9a/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerCertificatesService.kt#L31)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

thanks, I added the Enum class in CertificateReader since both the writer and the service depends on it. Also named it Owner, I can change it if it sounds too generic
</blockquote></details>

The name would be fine for being declared inside of CertificateReader. It's not the best place given that CreateCertificate doesn't seem to depend on CertificateReader for any other reason. I'd personally put it in the `common` package and therefore name it CertificateOwner, but up to you if you want to change it.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerCertificatesService.kt, line 44 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139#-Mf9vvQn3xeFSr_G-bnG:-Mf9vvQn3xeFSr_G-bnH:b2yky60) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9b095c88982fb90d97ab79ad938254e6b0bdb8dc/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerCertificatesService.kt#L44)):*
> ```Kotlin
>     if (request.hasExternalDataProviderId()) {
>       return Owner.DATA_PROVIDER
>     } else {
> ```

You should be able to switch on the oneof case using `when`.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerCertificatesService.kt, line 58 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139#-Mf9xoQh3KSvFTMFpGv5:-Mf9xoQh3KSvFTMFpGv6:b-x8qf6q) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9b095c88982fb90d97ab79ad938254e6b0bdb8dc/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerCertificatesService.kt#L58)):*
> ```
> ${request.externalCertificateId}
> ```
Don't expose int external IDs in gRPC status.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateCertificate.kt, line 32 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139#-Mf9uaESEGWEaVSh4fV_:-Mf9uaESEGWEaVSh4fVa:b-w5681t) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9b095c88982fb90d97ab79ad938254e6b0bdb8dc/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateCertificate.kt#L32)):*
> ```
> private const val DATA_PROVIDER = "DataProvider"
> private const val MEASUREMENT_CONSUMER = "MeasurementConsumer"
> private const val DUCHY = "Duchy"
> ```
Remove
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateCertificate.kt, line 38 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139#-MfAIaFTDBnsegaXRRJh:-MfAIaFTDBnsegaXRRJi:bvh62dr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9b095c88982fb90d97ab79ad938254e6b0bdb8dc/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateCertificate.kt#L38)):*
> ```
> String
> ```
Should be the enum type. Don't drop down to the table name string until the last possible moment.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateCertificate.kt, line 60 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139#-MfAGy5R3H-8ik6xVX-w:-MfAGy5R3H-8ik6xVX-x:b-ayar07) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9b095c88982fb90d97ab79ad938254e6b0bdb8dc/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateCertificate.kt#L60)):*
> ```
> InternalResource
> ```
Resource is a word we've been using only in reference to the resource-oriented APIs, where it's sometimes used as an adjective to distinguish from something internal. e.g. a resource ID is an external API ID. Therefore, there's no such thing as an "internal resource".

Following your existing name, what I think what you want here is Owner. In that case, you may want to rename your enum to something like OwnerType.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateCertificate.kt, line 61 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139#-MfAJB4jCquVPUy26JAx:-MfAJB4jCquVPUy26JAy:bm7nnvp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9b095c88982fb90d97ab79ad938254e6b0bdb8dc/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateCertificate.kt#L61)):*
> ```
> if (certificate.hasExternalMeasurementConsumerId()) {
> ```
Same here re: switching on oneof case.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/CertificatesServiceTest.kt, line 85 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139#-MfAKVy6DNg27wMIaKuv:-MfAKVy6DNg27wMIaKuw:b-eud4v2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9b095c88982fb90d97ab79ad938254e6b0bdb8dc/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/CertificatesServiceTest.kt#L85)):*
> ```
> setX509Der
> ```
Use Kotlin property syntax
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/CertificatesServiceTest.kt, line 88 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139#-MfAK_jD5pR8OrcFHQo8:-MfAK_jD5pR8OrcFHQo9:bqyguw2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9b095c88982fb90d97ab79ad938254e6b0bdb8dc/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/CertificatesServiceTest.kt#L88)):*
> ```
> 2
> ```
nit: The actual value doesn't matter for a test, but this would technically be `v2alpha`. Using correct-looking values would be less confusing for a reader.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/CertificatesServiceTest.kt, line 252 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139#-MfAL17TBDLybVMDIzE0:-MfAL17TBDLybVMDIzE1:b-a0gqsk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9b095c88982fb90d97ab79ad938254e6b0bdb8dc/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/CertificatesServiceTest.kt#L252)):*
> ```
> certificateRead
> ```
nit: confusing naming, as you have `createdCertificate` but `certificateRead` rather than `readCertificate`.

Personally I'd just call this one `certificate` as it's a complete certificate, and refer to the one being passed to `createCertificate` as `request`.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/CertificatesServiceTest.kt, line 266 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139#-MfAK6pw6I-ajKeFdL6x:-MfAK6pw6I-ajKeFdL6y:b-cii19b) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9b095c88982fb90d97ab79ad938254e6b0bdb8dc/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/test [...]

2021-07-21 23:19 UTC, SanjayVas reviewed
> Reviewed 18 of 23 files at r2, 2 of 9 files at r6.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139)* status: 27 of 29 files reviewed, 15 unresolved discussions (waiting on @oliver-amzn, @SanjayVas, @uakyol, and @zachcwc)



<!-- Sent from Reviewable.io -->

2021-07-21 23:21 UTC, SanjayVas reviewed
> Reviewed 2 of 9 files at r6.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139)* status: all files reviewed, 14 unresolved discussions (waiting on @oliver-amzn, @uakyol, and @zachcwc)



<!-- Sent from Reviewable.io -->

2021-07-22 21:39 UTC, uakyol reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139)* status: 24 of 29 files reviewed, 13 unresolved discussions (waiting on @oliver-amzn, @SanjayVas, @uakyol, @wangyaopw, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerCertificatesService.kt, line 31 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139#-Meko9AB8SNkL-WfJaNI:-MfF6ij850YJQPHWNlA_:b-4sa0eb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2f2a7951c1f167d07c4d467c633dc5d893a09b9a/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerCertificatesService.kt#L31)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The name would be fine for being declared inside of CertificateReader. It's not the best place given that CreateCertificate doesn't seem to depend on CertificateReader for any other reason. I'd personally put it in the `common` package and therefore name it CertificateOwner, but up to you if you want to change it.
</blockquote></details>

I realize I forgot to add the case if there is a certificate that has the same subjectKeyIdentifier inserted before. I  will need to add the ALREADY_EXISTS case for that. So this might actually need to depend on the Reader. I wanted to ask that. Do you think it is better to 1) call the reader at the beginning create with readwithSubjectKeyIdentifier() or something like that and fail if exists or 2) Try to insert with Create without reading and let it throw. The second one will have a harder error handling, since we are calling execute from the Service, I probably will need to write a execute wrapper that throws a KingdomInternalException.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerCertificatesService.kt, line 44 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139#-Mf9vvQn3xeFSr_G-bnG:-MfEuY_y0ws1Fq-NXM8P:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9b095c88982fb90d97ab79ad938254e6b0bdb8dc/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerCertificatesService.kt#L44)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

You should be able to switch on the oneof case using `when`.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerCertificatesService.kt, line 58 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139#-Mf9xoQh3KSvFTMFpGv5:-MfEhI3K2RBzHY-PlM2J:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9b095c88982fb90d97ab79ad938254e6b0bdb8dc/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerCertificatesService.kt#L58)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> ${request.externalCertificateId}
> ```
Don't expose int external IDs in gRPC status.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/CertificateReader.kt, line 60 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139#-Mf9swAI6HqZJtUxatw1:-MfEk0o88N2K1cNYrQlR:bz2xhrr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9b095c88982fb90d97ab79ad938254e6b0bdb8dc/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/CertificateReader.kt#L60)):*
> return certificateBuilder.apply{
>   when(owner) {
>      Owner.MEASUREMENT_CONSUMER -> externalMeasurementConsumerId = struct.getLong(externalResourceIdColumn)
>      Owner.DATA_PROVIDER -> externalDataProviderId = struct.getLong(externalResourceIdColumn)
>      Owner.DUCHY -> TODO
> }.build() 
Thank you so much!
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateCertificate.kt, line 32 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139#-Mf9uaESEGWEaVSh4fV_:-MfEhVcX1jXMCLDTrELv:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9b095c88982fb90d97ab79ad938254e6b0bdb8dc/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateCertificate.kt#L32)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> private const val DATA_PROVIDER = "DataProvider"
> private const val MEASUREMENT_CONSUMER = "MeasurementConsumer"
> private const val DUCHY = "Duchy"
> ```
Remove
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateCertificate.kt, line 38 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139#-MfAIaFTDBnsegaXRRJh:-MfEie8z7oV-VIg0IEbB:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9b095c88982fb90d97ab79ad938254e6b0bdb8dc/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateCertificate.kt#L38)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> String
> ```
Should be the enum type. Don't drop down to the table name string until the last possible moment.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateCertificate.kt, line 60 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139#-MfAGy5R3H-8ik6xVX-w:-MfEieaz5ne5_kb-NW56:b-1cyu7w) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9b095c88982fb90d97ab79ad938254e6b0bdb8dc/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateCertificate.kt#L60)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> InternalResource
> ```
Resource is a word we've been using only in reference to the resource-oriented APIs, where it's sometimes used as an adjective to distinguish from something internal. e.g. a resource ID is an external API ID. Therefore, there's no such thing as an "internal resource".

Following your existing name, what I think what you want here is Owner. In that case, you may want to rename your enum to something like OwnerType.
</blockquote></details>

thank you
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateCertificate.kt, line 61 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139#-MfAJB4jCquVPUy26JAx:-MfExwwUCCdbugusIKR9:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9b095c88982fb90d97ab79ad938254e6b0bdb8dc/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateCertificate.kt#L61)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> if (certificate.hasExternalMeasurementConsumerId()) {
> ```
Same here re: switching on oneof case.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/CertificatesServiceTest.kt, line 85 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139#-MfAKVy6DNg27wMIaKuv:-MfEl8tsCVrp-ivN0YeB:b-e5ytgc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9b095c88982fb90d97ab79ad938254e6b0bdb8dc/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/CertificatesServiceTest.kt#L85)):*
> Use Kotlin property syntax
thanks
___
*[src/main/kotlin/org/wfanet/measur [...]

2021-07-22 22:52 UTC, SanjayVas requested changes
> Reviewed 4 of 5 files at r7, 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139)* status: all files reviewed, 5 unresolved discussions (waiting on @oliver-amzn, @SanjayVas, @uakyol, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerCertificatesService.kt, line 31 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139#-Meko9AB8SNkL-WfJaNI:-MfFM4Xg9ifkcIJPD8pw:bgdzfw4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2f2a7951c1f167d07c4d467c633dc5d893a09b9a/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerCertificatesService.kt#L31)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

I realize I forgot to add the case if there is a certificate that has the same subjectKeyIdentifier inserted before. I  will need to add the ALREADY_EXISTS case for that. So this might actually need to depend on the Reader. I wanted to ask that. Do you think it is better to 1) call the reader at the beginning create with readwithSubjectKeyIdentifier() or something like that and fail if exists or 2) Try to insert with Create without reading and let it throw. The second one will have a harder error handling, since we are calling execute from the Service, I probably will need to write a execute wrapper that throws a KingdomInternalException.
</blockquote></details>

Fewer underlying sequential Spanner RPCs is better. This means that if you can do it without a separate read, you should. This is why I have mentioned before re: custom exceptions is that you'd likely need to be able to throw these internal exceptions from `execute`, since that's the function that knows enough detail to throw such an exception.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/CertificateReader.kt, line 26 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139#-MfFNyye2c8QbSgHL8dV:-MfFNyye2c8QbSgHL8dW:b6i2ymy) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8e738d2b06e575c88919319158df2b8a068582e1/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/CertificateReader.kt#L26)):*
> ```
> OwnerType
> ```
Now that we've swapped to switching on `ParentCase` and we know that the reader/writer layer speaks the internal service messages, it becomes a bit more apparent that we don't actually need a separate enum.

We can just use ParentCase as the enum type, with a function that gives us the table name for that parent.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateCertificate.kt, line 60 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139#-MfAGy5R3H-8ik6xVX-w:-MfFP8DpDZ4FXw4RJvjX:bzch1r) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9b095c88982fb90d97ab79ad938254e6b0bdb8dc/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateCertificate.kt#L60)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

thank you
</blockquote></details>

Looking at it again, it appears you don't actually need the data class. You already know what the owner type is from the instance property, and you can therefore get the table name from that in the `createCertificateMapTableMutation` method.


<!-- Sent from Reviewable.io -->

2021-07-23 16:36 UTC, uakyol reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139)* status: 28 of 29 files reviewed, 5 unresolved discussions (waiting on @oliver-amzn, @SanjayVas, @uakyol, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/CertificateReader.kt, line 26 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139#-MfFNyye2c8QbSgHL8dV:-MfJArHL-Vhy8c3oGREY:bpenp8v) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8e738d2b06e575c88919319158df2b8a068582e1/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/CertificateReader.kt#L26)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> OwnerType
> ```
Now that we've swapped to switching on `ParentCase` and we know that the reader/writer layer speaks the internal service messages, it becomes a bit more apparent that we don't actually need a separate enum.

We can just use ParentCase as the enum type, with a function that gives us the table name for that parent.
</blockquote></details>

if we do it like that, then we need to implement the error handling for the missing external_id field in the reader/writer. We will need another KingdomInternalMessage and another error handling task for the service. Do you think it is a good tradeoff to keep the proto validation to the service and keep reader/writer clean by using these extra enum/data class
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateCertificate.kt, line 60 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139#-MfAGy5R3H-8ik6xVX-w:-MfJCxSNAxBlXTOpXuHx:bvs55d0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9b095c88982fb90d97ab79ad938254e6b0bdb8dc/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateCertificate.kt#L60)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Looking at it again, it appears you don't actually need the data class. You already know what the owner type is from the instance property, and you can therefore get the table name from that in the `createCertificateMapTableMutation` method.
</blockquote></details>

Thank you


<!-- Sent from Reviewable.io -->

2021-07-23 18:40 UTC, uakyol reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139)* status: 28 of 29 files reviewed, 5 unresolved discussions (waiting on @oliver-amzn, @SanjayVas, @uakyol, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/CertificateReader.kt, line 26 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139#-MfFNyye2c8QbSgHL8dV:-MfJecpZ1ifXas3FBEJk:bugmw1c) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8e738d2b06e575c88919319158df2b8a068582e1/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/CertificateReader.kt#L26)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

if we do it like that, then we need to implement the error handling for the missing external_id field in the reader/writer. We will need another KingdomInternalMessage and another error handling task for the service. Do you think it is a good tradeoff to keep the proto validation to the service and keep reader/writer clean by using these extra enum/data class
</blockquote></details>

sorry just the extra enum I mean


<!-- Sent from Reviewable.io -->

2021-07-23 21:53 UTC, SanjayVas requested changes
> Reviewed 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139)* status: all files reviewed, 4 unresolved discussions (waiting on @oliver-amzn, @uakyol, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/CertificateReader.kt, line 26 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139#-MfFNyye2c8QbSgHL8dV:-MfKLHZR9YMV9I-u2zYy:bm0g8il) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8e738d2b06e575c88919319158df2b8a068582e1/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/CertificateReader.kt#L26)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

sorry just the extra enum I mean
</blockquote></details>

I'd still check for missing field in the service first to throw an INVALID_ARGUMENT gRPC exception. Then in reader/writer level, you can assume it's an error pass one that's invalid and just use `require` precondition. You don't have to catch this exception from the service since you should have already checked, and it therefore represents a programming error.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateCertificate.kt, line 60 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139#-MfAGy5R3H-8ik6xVX-w:-MfKLs-zAqXD1CCfBW8g:b-l3utwm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9b095c88982fb90d97ab79ad938254e6b0bdb8dc/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateCertificate.kt#L60)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

Thank you
</blockquote></details>

Rename function to match the change.


<!-- Sent from Reviewable.io -->

2021-07-24 00:14 UTC, uakyol reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139)* status: 25 of 32 files reviewed, 4 unresolved discussions (waiting on @oliver-amzn, @SanjayVas, @uakyol, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerCertificatesService.kt, line 31 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139#-Meko9AB8SNkL-WfJaNI:-MfKq5Ru1yMpgIancIHT:bj507ou) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2f2a7951c1f167d07c4d467c633dc5d893a09b9a/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerCertificatesService.kt#L31)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Fewer underlying sequential Spanner RPCs is better. This means that if you can do it without a separate read, you should. This is why I have mentioned before re: custom exceptions is that you'd likely need to be able to throw these internal exceptions from `execute`, since that's the function that knows enough detail to throw such an exception.
</blockquote></details>

Thank you, added it as discussed
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateCertificate.kt, line 60 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139#-MfAGy5R3H-8ik6xVX-w:-MfKqO27CVLt072Fqfqi:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9b095c88982fb90d97ab79ad938254e6b0bdb8dc/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateCertificate.kt#L60)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Rename function to match the change.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/CertificatesServiceTest.kt, line 266 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139#-MfAK6pw6I-ajKeFdL6x:-MfKqCUZ0Nb8dkBIrQk-:b-7r28g6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9b095c88982fb90d97ab79ad938254e6b0bdb8dc/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/CertificatesServiceTest.kt#L266)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I *think* you can make this a protected data class defined inside of the test class. This way you don't need to redefine T, and can also just pick a generic name like `Services`.
</blockquote></details>

thanks, moved it


<!-- Sent from Reviewable.io -->

2021-07-24 00:26 UTC, SanjayVas requested changes
> Reviewed 7 of 7 files at r10.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139)* status: all files reviewed, 6 unresolved discussions (waiting on @oliver-amzn, @uakyol, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerCertificatesService.kt, line 72 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139#-MfKriNYCc23EepyqPtk:-MfKrZXzC73LXb_i9faL:b-fvsqec) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cec73176c441c765b68018f12af04b709fcebe9d/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerCertificatesService.kt#L72)):*
> ```
>  else -> failGrpc(Status.UNKNOWN) {""}
> ```
It should be better to leave off the else branch, as then the when can be exhaustive against the enum (trigger a compilation error if a case isn't handled).
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerEventGroupsService.kt, line 45 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139#-MfKrrSO7hgbsCbbhYm4:-MfKrrSO7hgbsCbbhYm5:buo9nmt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cec73176c441c765b68018f12af04b709fcebe9d/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerEventGroupsService.kt#L45)):*
> ```Kotlin
>         KingdomInternalException.Code.DATA_PROVIDER_NOT_FOUND ->
>           failGrpc(Status.NOT_FOUND) { "DataProvider not found" }
>         else -> failGrpc(Status.UNKNOWN) {""}
> ```

Same here
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/common/KingdomInternalException.kt, line 20 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139#-MfKryF749QWeM37pb1q:-MfKryF749QWeM37pb1r:b-ddesxi) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cec73176c441c765b68018f12af04b709fcebe9d/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/common/KingdomInternalException.kt#L20)):*
> ```Kotlin
>   enum class Code {
>     /** Unknown, used to report exceptions that are not specifically programmed to be caught. */
>     UNKNOWN,
> ```

I don't think we need this value. We should always have a known error code.

This is different than protobuf enums where we need to worry about backwards-compatibility over the wire.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateCertificate.kt, line 115 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139#-MfKsBsc7h7dKcjaz4VG:-MfKsBsc7h7dKcjaz4VH:b-2qbfhg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cec73176c441c765b68018f12af04b709fcebe9d/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateCertificate.kt#L115)):*
> ```Kotlin
>             KingdomInternalException.Code.CERT_SUBJECT_KEY_ID_ALREADY_EXISTS
>           )
>         else -> throw KingdomInternalException(KingdomInternalException.Code.UNKNOWN)
> ```

Just let the Spanner exception bubble up in this case and don't catch it. The default gRPC behavior for an unhandled exception should kick in.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/SpannerWriter.kt, line 70 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139#-MfKspzmCwu5BOU6cHN2:-MfKspznA5-c5JcERGFi:b7rzylq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cec73176c441c765b68018f12af04b709fcebe9d/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/SpannerWriter.kt#L70)):*
> ```Kotlin
>    * @return the output of [buildResult]
>    */
>   open suspend fun execute(
> ```

Tagging @efoxepstein for an extra opinion as the original author of this class. For background, I asked @uakyol to throw a custom exception if needed from readers/writers with its own error code enum that the service layer could use to determine the appropriate gRPC error code. We should also document exceptions that we expect the caller may want to catch. In order to document those specific exception conditions, these public methods need to be overridable.

WDYT?


<!-- Sent from Reviewable.io -->

2021-07-26 20:30 UTC, efoxepstein reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139)* status: all files reviewed, 6 unresolved discussions (waiting on @oliver-amzn, @uakyol, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/SpannerWriter.kt, line 70 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139#-MfKspzmCwu5BOU6cHN2:-MfZUMAp1BhMffmdmbkH:b-mal3ia) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bda58be686c4d2af2202bd329a3eb07a5f5a59c9/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/SpannerWriter.kt#L70)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Tagging @efoxepstein for an extra opinion as the original author of this class. For background, I asked @uakyol to throw a custom exception if needed from readers/writers with its own error code enum that the service layer could use to determine the appropriate gRPC error code. We should also document exceptions that we expect the caller may want to catch. In order to document those specific exception conditions, these public methods need to be overridable.

WDYT?
</blockquote></details>

Could we get away with passing an `onFailure` callback in the concrete class's constructor?

```
val fooWriter = FooWriter(...) { e: SomeSpecificExceptionType ->
  throw gRpcWhatever
}
```


<!-- Sent from Reviewable.io -->

2021-07-26 21:46 UTC, uakyol reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139)* status: all files reviewed, 6 unresolved discussions (waiting on @oliver-amzn, @SanjayVas, @uakyol, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/SpannerWriter.kt, line 70 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139#-MfKspzmCwu5BOU6cHN2:-MfZla--5AP9VvDvSYCw:b-v29fs8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bda58be686c4d2af2202bd329a3eb07a5f5a59c9/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/SpannerWriter.kt#L70)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Could we get away with passing an `onFailure` callback in the concrete class's constructor?

```
val fooWriter = FooWriter(...) { e: SomeSpecificExceptionType ->
  throw gRpcWhatever
}
```
</blockquote></details>

This constructor will be called in the service definition which is not Spanner specific. So if I understand your suggestion correctly, "SomeSpecificExceptionType" cannot be passed to the constructor in the service since it doesn't know about Spanner specific exceptions.


<!-- Sent from Reviewable.io -->

2021-07-26 21:51 UTC, SanjayVas reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139)* status: all files reviewed, 6 unresolved discussions (waiting on @efoxepstein, @oliver-amzn, @uakyol, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/SpannerWriter.kt, line 70 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139#-MfKspzmCwu5BOU6cHN2:-MfZkVSi0Uzo79j-bX4o:b-1i8b6z) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bda58be686c4d2af2202bd329a3eb07a5f5a59c9/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/SpannerWriter.kt#L70)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

This constructor will be called in the service definition which is not Spanner specific. So if I understand your suggestion correctly, "SomeSpecificExceptionType" cannot be passed to the constructor in the service since it doesn't know about Spanner specific exceptions.
</blockquote></details>

Hmm. It does avoiding overriding just for documentation purposes. My main concern would be making sure we could maintain the same execution context as `catch` for the exception handler such that we could allow non-local returns. I don't think we can mark a constructor with `inline` to get that behavior.

I'd prefer to just allow the methods to be overridable if we can't keep the same execution context.


<!-- Sent from Reviewable.io -->

2021-07-26 22:09 UTC, efoxepstein reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139)* status: all files reviewed, 6 unresolved discussions (waiting on @oliver-amzn, @SanjayVas, @uakyol, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/SpannerWriter.kt, line 70 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139#-MfKspzmCwu5BOU6cHN2:-MfZqWBx2c1n4-6Ht4Vp:b-99mbyw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bda58be686c4d2af2202bd329a3eb07a5f5a59c9/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/SpannerWriter.kt#L70)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Hmm. It does avoiding overriding just for documentation purposes. My main concern would be making sure we could maintain the same execution context as `catch` for the exception handler such that we could allow non-local returns. I don't think we can mark a constructor with `inline` to get that behavior.

I'd prefer to just allow the methods to be overridable if we can't keep the same execution context.
</blockquote></details>

@uakyol if a SpannerWriter is not Spanner specific, what is it?

@sanjayvas why do you need the same execution context? It seems like the use case here is to throw an exception, not return early. 

```
try {
  val writer = FooWriter()...) { e: SomeSpecificExceptionType ->
    throw SomeOtherExceptionType()
  }
catch (e: SomeOtherExceptionType) {
  doWhateverYouWantBecauseYouHaveTheRightExecutionContext()
}
```


<!-- Sent from Reviewable.io -->

2021-07-26 22:11 UTC, SanjayVas reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139)* status: all files reviewed, 6 unresolved discussions (waiting on @efoxepstein, @oliver-amzn, @uakyol, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/SpannerWriter.kt, line 70 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139#-MfKspzmCwu5BOU6cHN2:-MfZrhxTCdC33DUJN-38:b-qvxelm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bda58be686c4d2af2202bd329a3eb07a5f5a59c9/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/SpannerWriter.kt#L70)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

@uakyol if a SpannerWriter is not Spanner specific, what is it?

@sanjayvas why do you need the same execution context? It seems like the use case here is to throw an exception, not return early. 

```
try {
  val writer = FooWriter()...) { e: SomeSpecificExceptionType ->
    throw SomeOtherExceptionType()
  }
catch (e: SomeOtherExceptionType) {
  doWhateverYouWantBecauseYouHaveTheRightExecutionContext()
}
```
</blockquote></details>

Ah, that's a good workaround if we need it. Error callback in constructor SGTM.


<!-- Sent from Reviewable.io -->

2021-07-26 22:52 UTC, efoxepstein requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139)* status: all files reviewed, 6 unresolved discussions (waiting on @oliver-amzn, @uakyol, and @zachcwc)



<!-- Sent from Reviewable.io -->

2021-07-27 20:11 UTC, uakyol reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139)* status: 25 of 32 files reviewed, 6 unresolved discussions (waiting on @efoxepstein, @oliver-amzn, @SanjayVas, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerCertificatesService.kt, line 72 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139#-MfKriNYCc23EepyqPtk:-Mf_Adzn2Jcbv35y2oq8:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bda58be686c4d2af2202bd329a3eb07a5f5a59c9/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerCertificatesService.kt#L72)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
>  else -> failGrpc(Status.UNKNOWN) {""}
> ```
It should be better to leave off the else branch, as then the when can be exhaustive against the enum (trigger a compilation error if a case isn't handled).
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerEventGroupsService.kt, line 45 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139#-MfKrrSO7hgbsCbbhYm4:-Mf_Aj6f0eSRrxK7ZHUO:b-8wuq38) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bda58be686c4d2af2202bd329a3eb07a5f5a59c9/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerEventGroupsService.kt#L45)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Same here
</blockquote></details>

if I leave off the else branch here, it does not compile because I am not handling the CERT_SUBJECT_KEY_ID_ALREADY_EXISTS case. What would you like me to do?
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/common/KingdomInternalException.kt, line 20 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139#-MfKryF749QWeM37pb1q:-Mf_AJHCE5pkvKicvYrO:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bda58be686c4d2af2202bd329a3eb07a5f5a59c9/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/common/KingdomInternalException.kt#L20)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I don't think we need this value. We should always have a known error code.

This is different than protobuf enums where we need to worry about backwards-compatibility over the wire.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/CertificateReader.kt, line 26 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139#-MfFNyye2c8QbSgHL8dV:-Mfa-AnN9cjUcaKuEFJP:b1qkrlk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8e738d2b06e575c88919319158df2b8a068582e1/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/CertificateReader.kt#L26)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I'd still check for missing field in the service first to throw an INVALID_ARGUMENT gRPC exception. Then in reader/writer level, you can assume it's an error pass one that's invalid and just use `require` precondition. You don't have to catch this exception from the service since you should have already checked, and it therefore represents a programming error.
</blockquote></details>

Done, I added the check in the service and did not add the require precondition in reader/writer. Also, used else case for the duchies. Since the service is guarding the existence of these fields, this should have the same effect with your suggestion. wdyt?
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateCertificate.kt, line 115 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139#-MfKsBsc7h7dKcjaz4VG:-Mf_AvLN4kkHv2WllWa2:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bda58be686c4d2af2202bd329a3eb07a5f5a59c9/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateCertificate.kt#L115)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Just let the Spanner exception bubble up in this case and don't catch it. The default gRPC behavior for an unhandled exception should kick in.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/SpannerWriter.kt, line 70 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139#-MfKspzmCwu5BOU6cHN2:-Mfd__Hl7D48IJ9dLH1-:b-qbxi6l) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bda58be686c4d2af2202bd329a3eb07a5f5a59c9/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/SpannerWriter.kt#L70)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Ah, that's a good workaround if we need it. Error callback in constructor SGTM.
</blockquote></details>

After offline sync with @efoxepstein we converged on adding an open handleSpannerException func. 


<!-- Sent from Reviewable.io -->

2021-07-27 20:16 UTC, wangyaopw reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139)* status: 25 of 32 files reviewed, 6 unresolved discussions (waiting on @efoxepstein, @oliver-amzn, @SanjayVas, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerEventGroupsService.kt, line 45 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139#-MfKrrSO7hgbsCbbhYm4:-MfdaukJ33li67hUzCxC:b-egvhn0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bda58be686c4d2af2202bd329a3eb07a5f5a59c9/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerEventGroupsService.kt#L45)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

if I leave off the else branch here, it does not compile because I am not handling the CERT_SUBJECT_KEY_ID_ALREADY_EXISTS case. What would you like me to do?
</blockquote></details>

failGrpc(Status. INTERNAL) {"Unexpected internal exception."}


<!-- Sent from Reviewable.io -->

2021-07-27 20:37 UTC, uakyol reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139)* status: 24 of 32 files reviewed, 6 unresolved discussions (waiting on @efoxepstein, @oliver-amzn, @SanjayVas, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerEventGroupsService.kt, line 45 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139#-MfKrrSO7hgbsCbbhYm4:-MfdfllGEPNh1Owd3ath:b-u0qyr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bda58be686c4d2af2202bd329a3eb07a5f5a59c9/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerEventGroupsService.kt#L45)):*
> "Unexpected internal exception."
Thanks, changed it. Based on offline sync with Yao, it seems the issue is listing all the cases rather than relying on else.


<!-- Sent from Reviewable.io -->

2021-07-27 20:53 UTC, uakyol reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139)* status: 24 of 32 files reviewed, 6 unresolved discussions (waiting on @efoxepstein, @oliver-amzn, @SanjayVas, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerEventGroupsService.kt, line 45 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139#-MfKrrSO7hgbsCbbhYm4:-MfdjVyT6ek-qTMmu6KB:b2s1ei2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bda58be686c4d2af2202bd329a3eb07a5f5a59c9/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerEventGroupsService.kt#L45)):*
> 
Thanks, changed it. Based on offline sync with Yao, it seems the issue is listing all the cases rather than relying on else.


<!-- Sent from Reviewable.io -->

2021-07-27 21:14 UTC, efoxepstein requested changes
> Reviewed 1 of 3 files at r4, 2 of 9 files at r6, 1 of 7 files at r10, 7 of 7 files at r11, 1 of 1 files at r12.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139)* status: all files reviewed, 12 unresolved discussions (waiting on @oliver-amzn, @SanjayVas, @uakyol, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/CertificateReader.kt, line 53 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139#-Mfdm5nb4VRufpDRfFH6:-Mfdm5nb4VRufpDRfFH7:b-9bmb2y) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/30e7966ec7f24f82888984b27d3266e9756dacfd/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/CertificateReader.kt#L53)):*
> ```Kotlin
>     Result(buildCertificate(struct), struct.getLong("CertificateId"))
> 
>   private fun getTableName(): String {
> ```

Maybe just inline this into the `tableName` property?

```
private val tableName: String
init {
  tableName = when(request.parentCase) { ... }
}
```
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/CertificateReader.kt, line 67 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139#-MfdmVBv6T0C7t2clr4F:-MfdmVBw-tpXoe8eTtUB:b-rhh3n9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/30e7966ec7f24f82888984b27d3266e9756dacfd/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/CertificateReader.kt#L67)):*
> ```Kotlin
>     val externalResourceIdColumn = "External${tableName}Id"
>     println("externalResourceIdColumnexternalResourceIdColumnexternalResourceIdColumn")
>     println(externalResourceIdColumn)
> ```

Delete printlns?
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateCertificate.kt, line 36 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139#-MfdmfXs8ieTK-0eDsYU:-MfdmfXs8ieTK-0eDsYV:b-89a4l7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/30e7966ec7f24f82888984b27d3266e9756dacfd/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateCertificate.kt#L36)):*
> ```Kotlin
> class CreateCertificate(private val certificate: Certificate) :
>   SpannerWriter<Certificate, Certificate>() {
>   private val ownerTableName = getTableName()
> ```

Ditto
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/SpannerWriter.kt, line 80 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139#-MfdnIDPBpiNI8_gu66T:-MfdnIDPBpiNI8_gu66U:b-lk2gvp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/30e7966ec7f24f82888984b27d3266e9756dacfd/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/SpannerWriter.kt#L80)):*
> ```Kotlin
>     val runner = databaseClient.readWriteTransaction()
>     val transactionResult: T? =
>       try {
> ```

Can you pull this try-catch out to a helper function? `private suspend fun runTransaction(runner, idGenerator, clock): T?` maybe?
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/SpannerWriter.kt, line 86 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139#-Mfdn4qi4yYbKcoug42m:-Mfdn4qj8Tsng3-UVkeF:b32bohy) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/30e7966ec7f24f82888984b27d3266e9756dacfd/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/SpannerWriter.kt#L86)):*
> ```Kotlin
>         }
>       } catch (e: SpannerException) {
>         handleSpannerException(e)
> ```

What about just letting `handleSpannerException` return `T?`. You can remove the `null` after this and it makes the API a little more flexible.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/SpannerWriter.kt, line 105 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139#-Mfdnl8s96oPXQZwWiNT:-Mfdnl8s96oPXQZwWiNU:b-y235sb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/30e7966ec7f24f82888984b27d3266e9756dacfd/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/SpannerWriter.kt#L105)):*
> ```Kotlin
> /** A [SpannerWriter] whose result is the non-null transaction result. */
> abstract class SimpleSpannerWriter<T : Any> : SpannerWriter<T, T>() {
>   override fun ResultScope<T>.buildResult(): T {
> ```

Revert this change? The whole point of SimpleSpannerWriter is that it does `buildResult` for you
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/CertificatesServiceTest.kt, line 95 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139#-MfdoDCs2W_119bF6Bz-:-MfdoDCs2W_119bF6Bz0:bbqprjx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/30e7966ec7f24f82888984b27d3266e9756dacfd/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/CertificatesServiceTest.kt#L95)):*
> ```Kotlin
>           detailsBuilder.apply {
>                 apiVersion = "v2alpha"
>             publicKey = PUBLIC_KEY
> ```

Weird formatting


<!-- Sent from Reviewable.io -->

2021-07-27 21:55 UTC, uakyol reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139)* status: 28 of 32 files reviewed, 12 unresolved discussions (waiting on @efoxepstein, @oliver-amzn, @SanjayVas, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/CertificateReader.kt, line 53 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139#-Mfdm5nb4VRufpDRfFH6:-MfduXAhDWI8dotyR72o:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/30e7966ec7f24f82888984b27d3266e9756dacfd/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/CertificateReader.kt#L53)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Maybe just inline this into the `tableName` property?

```
private val tableName: String
init {
  tableName = when(request.parentCase) { ... }
}
```
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/CertificateReader.kt, line 67 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139#-MfdmVBv6T0C7t2clr4F:-MfduKa1DK3zSvWtjiME:b-k73z76) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/30e7966ec7f24f82888984b27d3266e9756dacfd/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/CertificateReader.kt#L67)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Delete printlns?
</blockquote></details>

thanks
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateCertificate.kt, line 36 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139#-MfdmfXs8ieTK-0eDsYU:-MfdvQ6O9rmZtloCcHBY:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/30e7966ec7f24f82888984b27d3266e9756dacfd/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateCertificate.kt#L36)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Ditto
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/SpannerWriter.kt, line 80 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139#-MfdnIDPBpiNI8_gu66T:-MfdwZ3Q6ZdELfjz6End:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/30e7966ec7f24f82888984b27d3266e9756dacfd/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/SpannerWriter.kt#L80)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Can you pull this try-catch out to a helper function? `private suspend fun runTransaction(runner, idGenerator, clock): T?` maybe?
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/SpannerWriter.kt, line 86 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139#-Mfdn4qi4yYbKcoug42m:-MfdxsVqA8qCJ-VENLbi:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/30e7966ec7f24f82888984b27d3266e9756dacfd/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/SpannerWriter.kt#L86)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

What about just letting `handleSpannerException` return `T?`. You can remove the `null` after this and it makes the API a little more flexible.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/SpannerWriter.kt, line 105 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139#-Mfdnl8s96oPXQZwWiNT:-MfduiA6BouOoAwufY6i:bimu7fx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/30e7966ec7f24f82888984b27d3266e9756dacfd/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/SpannerWriter.kt#L105)):*
> ```
> SimpleSpannerWriter
> ```

Im so sorry, don't know how this happened, thanks for catching this.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/CertificatesServiceTest.kt, line 95 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139#-MfdoDCs2W_119bF6Bz-:-MfdvPGl0K8NYycAzcd1:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/30e7966ec7f24f82888984b27d3266e9756dacfd/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/CertificatesServiceTest.kt#L95)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Weird formatting
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-27 22:02 UTC, efoxepstein approved these changes
> Reviewed 4 of 4 files at r13.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139)* status: all files reviewed, 5 unresolved discussions (waiting on @oliver-amzn, @SanjayVas, and @zachcwc)



<!-- Sent from Reviewable.io -->

2021-07-28 00:05 UTC, SanjayVas requested changes
> Reviewed 3 of 7 files at r11, 1 of 1 files at r12, 4 of 4 files at r13.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139)* status: all files reviewed, 3 unresolved discussions (waiting on @oliver-amzn, @uakyol, @wangyaopw, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerCertificatesService.kt, line 40 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139#-MfeKBYU20guJpGxYrNl:-MfeKBYV1n6WotugZs-y:bgj7i0o) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d4fe966494d00b290c7a42e4ba6e89e5c029f393/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerCertificatesService.kt#L40)):*
> ```
>       request.hasExternalDataProviderId() ||
>         request.hasExternalMeasurementConsumerId() ||
>         request.hasExternalDuchyId()
> ```
nit: could more concisely check whether it's ParentCase.PARENTCASE_NOT_SET
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerEventGroupsService.kt, line 45 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139#-MfKrrSO7hgbsCbbhYm4:-MfeKn2_70IAvHXIisfC:b5m0h5q) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bda58be686c4d2af2202bd329a3eb07a5f5a59c9/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerEventGroupsService.kt#L45)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

> 
Thanks, changed it. Based on offline sync with Yao, it seems the issue is listing all the cases rather than relying on else.
</blockquote></details>

Yes, should exhaustively list all cases (even those that this method doesn't expect).

Just rethrow for the ones you don't expect. gRPC will automatically convert to an error with internal status.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/CertificateReader.kt, line 26 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139#-MfFNyye2c8QbSgHL8dV:-MfeLIfG0CcIx1trMKEb:b-hksjs2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8e738d2b06e575c88919319158df2b8a068582e1/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/CertificateReader.kt#L26)):*
> did not add the require precondition in reader/writer

Sorry, you're right. You'd end up throwing the IllegalArgumentException in the right condition rather than using `require`.

> Also, used else case for the duchies. Since the service is guarding the existence of these fields, this should have the same effect with your suggestion. wdyt?

This should still be an exhaustive `when` and throw an IllegalArgumentException. The difference from guarding in the service is that you don't need this to throw an internal exception for this case that the service should catch. Instead, you're throwing an exception that indicates that there's a programming error which the service need not catch (as it should never happen).
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/SpannerWriter.kt, line 70 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139#-MfKspzmCwu5BOU6cHN2:-MfeOT-j-BaLtzEWzppL:b-u2r96p) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bda58be686c4d2af2202bd329a3eb07a5f5a59c9/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/SpannerWriter.kt#L70)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

After offline sync with @efoxepstein we converged on adding an open handleSpannerException func. 
</blockquote></details>

I see how this allows CreateCertificate throw the `KingdomInternalException` under the right conditions, but I don't think this alone implements the entire solution. What's missing is communicating the conditions under which `KingdomInternalException` is thrown to the caller of `execute` (i.e. the service).

Recall the broad concept is that this reader/writer structure abstracts the actual Spanner interactions away from the service implementation. Therefore, the readers/writers for Kingdom internal services need to handle specific SpannerExceptions and convert them to something the service understands and can act on (i.e. KingdomInternalException). In order to do this, the service needs to know under which conditions it should expect a KingdomInternalException. Normally you'd do this by documenting the method that could throw the exception. I guess in this case since each of these types only exposes one key method (e.g. execute) then you can document this in the reader/writer constructor.


<!-- Sent from Reviewable.io -->

2021-07-28 00:25 UTC, zachcwc approved these changes
> Reviewed 1 of 29 files at r1, 1 of 3 files at r4, 2 of 9 files at r6, 1 of 7 files at r10, 3 of 7 files at r11, 1 of 1 files at r12, 4 of 4 files at r13.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139)* status: all files reviewed, 3 unresolved discussions (waiting on @oliver-amzn, @uakyol, and @wangyaopw)



<!-- Sent from Reviewable.io -->

2021-07-28 04:33 UTC, uakyol reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139)* status: 28 of 32 files reviewed, 3 unresolved discussions (waiting on @efoxepstein, @oliver-amzn, @SanjayVas, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerCertificatesService.kt, line 40 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139#-MfeKBYU20guJpGxYrNl:-MffNKB78RafzEiwSST3:b-gmejgd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d4fe966494d00b290c7a42e4ba6e89e5c029f393/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerCertificatesService.kt#L40)):*
> ParentCase.PARENTCASE_NOT_SET
thank you, looks better now
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerEventGroupsService.kt, line 45 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139#-MfKrrSO7hgbsCbbhYm4:-MffJw7b5p-SeI8Jwf1p:b-k73z76) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bda58be686c4d2af2202bd329a3eb07a5f5a59c9/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerEventGroupsService.kt#L45)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Yes, should exhaustively list all cases (even those that this method doesn't expect).

Just rethrow for the ones you don't expect. gRPC will automatically convert to an error with internal status.
</blockquote></details>

thanks
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/CertificateReader.kt, line 26 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139#-MfFNyye2c8QbSgHL8dV:-MffLwJ81ofbr_Z1dpMs:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8e738d2b06e575c88919319158df2b8a068582e1/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/CertificateReader.kt#L26)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> did not add the require precondition in reader/writer

Sorry, you're right. You'd end up throwing the IllegalArgumentException in the right condition rather than using `require`.

> Also, used else case for the duchies. Since the service is guarding the existence of these fields, this should have the same effect with your suggestion. wdyt?

This should still be an exhaustive `when` and throw an IllegalArgumentException. The difference from guarding in the service is that you don't need this to throw an internal exception for this case that the service should catch. Instead, you're throwing an exception that indicates that there's a programming error which the service need not catch (as it should never happen).
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-28 16:44 UTC, efoxepstein requested changes
> Reviewed 4 of 4 files at r14.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139)* status: all files reviewed, 5 unresolved discussions (waiting on @oliver-amzn, @SanjayVas, and @uakyol)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerCertificatesService.kt, line 65 at r14](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139#-MfhzAUj16IgM1GeBOkG:-MfhzAUj16IgM1GeBOkH:b-ep9gv5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a308c5621f1222bbc7986993080cf5b021500e1d/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerCertificatesService.kt#L65)):*
> ```Kotlin
>       "GetCertificateRequest is missing parent field"
>     }
>     
> ```

Is this a literal `...` in the code or is Reviewable being weird for me?
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateCertificate.kt, line 45 at r14](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139#-MfhyhByBpPW_dzcK25o:-MfhyhBzCJc1Jm-txQTx:bd50vcm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a308c5621f1222bbc7986993080cf5b021500e1d/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateCertificate.kt#L45)):*
> ```Kotlin
>         Certificate.ParentCase.EXTERNAL_DUCHY_ID -> "Duchy"
>         Certificate.ParentCase.PARENT_NOT_SET ->
>           throw IllegalArgumentException("Parent field of Certificate is not set")
> ```

Use `error` in Kotlin
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/SpannerWriter.kt, line 70 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139#-MfKspzmCwu5BOU6cHN2:-MfhzHrrDJ75n4jZmEY9:bbpzqik) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bda58be686c4d2af2202bd329a3eb07a5f5a59c9/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/SpannerWriter.kt#L70)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I see how this allows CreateCertificate throw the `KingdomInternalException` under the right conditions, but I don't think this alone implements the entire solution. What's missing is communicating the conditions under which `KingdomInternalException` is thrown to the caller of `execute` (i.e. the service).

Recall the broad concept is that this reader/writer structure abstracts the actual Spanner interactions away from the service implementation. Therefore, the readers/writers for Kingdom internal services need to handle specific SpannerExceptions and convert them to something the service understands and can act on (i.e. KingdomInternalException). In order to do this, the service needs to know under which conditions it should expect a KingdomInternalException. Normally you'd do this by documenting the method that could throw the exception. I guess in this case since each of these types only exposes one key method (e.g. execute) then you can document this in the reader/writer constructor.
</blockquote></details>

Agreed -- document `CreateCertificate` at the class level. Probably also document `SpannerWriter::execute` that it will bubble up anything that `handleSpannerException` throws.


<!-- Sent from Reviewable.io -->

2021-07-28 16:55 UTC, SanjayVas reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139)* status: all files reviewed, 5 unresolved discussions (waiting on @efoxepstein, @oliver-amzn, @SanjayVas, and @uakyol)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateCertificate.kt, line 45 at r14](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139#-MfhyhByBpPW_dzcK25o:-Mfi1YhF-iZYpx3_QaIF:b-9hoy85) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a308c5621f1222bbc7986993080cf5b021500e1d/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateCertificate.kt#L45)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Use `error` in Kotlin
</blockquote></details>

`error` results in an `IllegalStateException` rather than an `IllegalArgumentException`. For the latter, you either need to throw directly or use `require`.


<!-- Sent from Reviewable.io -->

2021-07-28 18:18 UTC, SanjayVas approved these changes
> Reviewed 4 of 4 files at r14.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139)* status: all files reviewed, 1 unresolved discussion (waiting on @efoxepstein and @oliver-amzn)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerCertificatesService.kt, line 65 at r14](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139#-MfhzAUj16IgM1GeBOkG:-MfiKUDf73MDGXA7OfZC:b-38xxbg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a308c5621f1222bbc7986993080cf5b021500e1d/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerCertificatesService.kt#L65)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Is this a literal `...` in the code or is Reviewable being weird for me?
</blockquote></details>

Weird. I see it too, but only in Reviewable. Not there in GitHub UI.


<!-- Sent from Reviewable.io -->

2021-07-28 18:19 UTC, SanjayVas requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139)* status: all files reviewed, 2 unresolved discussions (waiting on @efoxepstein, @oliver-amzn, and @SanjayVas)



<!-- Sent from Reviewable.io -->

2021-07-28 18:44 UTC, efoxepstein approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139)* status: all files reviewed, 1 unresolved discussion (waiting on @oliver-amzn and @SanjayVas)



<!-- Sent from Reviewable.io -->

2021-07-28 21:10 UTC, uakyol reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139)* status: 29 of 32 files reviewed, 1 unresolved discussion (waiting on @efoxepstein, @oliver-amzn, @SanjayVas, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateCertificate.kt, line 45 at r14](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139#-MfhyhByBpPW_dzcK25o:-MfiwxvX-11ofGIcm_jh:b-8d3oxb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a308c5621f1222bbc7986993080cf5b021500e1d/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateCertificate.kt#L45)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

`error` results in an `IllegalStateException` rather than an `IllegalArgumentException`. For the latter, you either need to throw directly or use `require`.
</blockquote></details>

I am keeping it this way then, since we already know that we are in PARENT_NOT_SET in that line and don't need to check again with require
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/SpannerWriter.kt, line 70 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139#-MfKspzmCwu5BOU6cHN2:-MfivcHJ-eHWCgujeUi7:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bda58be686c4d2af2202bd329a3eb07a5f5a59c9/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/SpannerWriter.kt#L70)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Agreed -- document `CreateCertificate` at the class level. Probably also document `SpannerWriter::execute` that it will bubble up anything that `handleSpannerException` throws.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-28 22:03 UTC, SanjayVas requested changes
> Reviewed 1 of 3 files at r15, 3 of 3 files at r16.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139)* status: all files reviewed, 1 unresolved discussion (waiting on @oliver-amzn and @uakyol)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateCertificate.kt, line 35 at r16](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139#-Mfj71i49BabV-i1uWL7:-Mfj71i49BabV-i1uWL8:bcyqrlc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/60069f7f56e8523e340b2a6e17c55b327650437e/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateCertificate.kt#L35)):*
> ```Kotlin
> 
> /**
>  * @throws KingdomInternalException if subjectKeyIdentifier of [certificate] collides with a
> ```

Don't use `@throws`, as that implies the constructor does the throwing. Rather, describe that it throws this exception when executed. Additionally, specify which code(s) it may be thrown with. Finally, this should just be one paragraph in the [KDoc for this class](https://developer.android.com/kotlin/style-guide#documentation) (i.e. if you're documenting something that uses KDoc, write the whole KDoc block).


<!-- Sent from Reviewable.io -->

2021-07-28 23:13 UTC, uakyol reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139)* status: 31 of 32 files reviewed, 1 unresolved discussion (waiting on @oliver-amzn and @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateCertificate.kt, line 35 at r16](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139#-Mfj71i49BabV-i1uWL7:-MfjOEnZDhqEApebOQSM:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/60069f7f56e8523e340b2a6e17c55b327650437e/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateCertificate.kt#L35)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Don't use `@throws`, as that implies the constructor does the throwing. Rather, describe that it throws this exception when executed. Additionally, specify which code(s) it may be thrown with. Finally, this should just be one paragraph in the [KDoc for this class](https://developer.android.com/kotlin/style-guide#documentation) (i.e. if you're documenting something that uses KDoc, write the whole KDoc block).
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-28 23:15 UTC, SanjayVas approved these changes
> Reviewed 1 of 1 files at r17.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @oliver-amzn)



<!-- Sent from Reviewable.io -->

2021-07-28 23:30 UTC, wangyaopw approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139)* status: all files reviewed, 2 unresolved discussions (waiting on @oliver-amzn and @uakyol)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerCertificatesService.kt, line 39 at r17](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139#-MfjS5zC4XedFpbKjbA-:-MfjS5zDBrc0JK36IyjK:b-hnrja7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cc38da4dbbf661b4694fb476e8851754a29f2d4a/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerCertificatesService.kt#L39)):*
> ```Kotlin
> ) : CertificatesCoroutineImplBase() {
>   override suspend fun createCertificate(request: Certificate): Certificate {
> ```

nit: no newline here
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerCertificatesService.kt, line 61 at r17](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139#-MfjS8SM9DjM5wQhIttz:-MfjS8SM9DjM5wQhItu-:b-hnrja7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cc38da4dbbf661b4694fb476e8851754a29f2d4a/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerCertificatesService.kt#L61)):*
> ```Kotlin
> 
>   override suspend fun getCertificate(request: GetCertificateRequest): Certificate {
> ```

nit: no newline here


<!-- Sent from Reviewable.io -->

2021-07-28 23:31 UTC, wangyaopw approved these changes
> Reviewed 1 of 3 files at r4, 2 of 9 files at r6, 1 of 7 files at r10, 2 of 7 files at r11, 1 of 4 files at r13, 1 of 4 files at r14, 1 of 3 files at r15, 2 of 3 files at r16, 1 of 1 files at r17.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139)* status: all files reviewed, 2 unresolved discussions (waiting on @oliver-amzn and @uakyol)



<!-- Sent from Reviewable.io -->

2021-07-28 23:46 UTC, uakyol reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139#-:-MfjVfJV9WvlefbCqLmR:bnfp4nl)* status: 31 of 32 files reviewed, all discussions resolved (waiting on @oliver-amzn, @SanjayVas, and @wangyaopw)



<!-- Sent from Reviewable.io -->

2021-07-28 23:46 UTC, wangyaopw approved these changes
> Reviewed 1 of 1 files at r19.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/139)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @oliver-amzn)



<!-- Sent from Reviewable.io -->

2021-07-28 23:47 UTC, merged