Add impression implementation to EDP simulator
world-federation-of-advertisers/cross-media-measurement pull request #1413
Opened 2024-01-11 00:48 UTC by riemanli

2024-01-11 00:48 UTC, wfa-reviewable commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1413)
<!-- Reviewable:end -->

2024-01-11 00:48 UTC, riemanli commented
Current dependencies on/for this PR:
* `main`
  * **PR #1413** <a href="https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/1413?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/1413?utm_source=stack-comment).

2024-01-11 18:04 UTC, jiayu-google requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1413)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @kungfucraig, @riemanli, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/MeasurementResults.kt` line 55 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1413#-Nntfpic5GAWPqnPDwMZ:-Nntfpic5GAWPqnPDwM_:b-rx4ftk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/858c11522e15a2513d2f550f656a368ffc356d76/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/MeasurementResults.kt#L55)):*
> ```Kotlin
>   /** Computes impression using the "deterministic count" methodology. */
>   fun computeImpression(sampledVids: Iterable<Long>, maxFrequency: Int): Long {
>     val eventsPerVid: Map<Long, Int> = sampledVids.groupingBy { it }.eachCount()
> ```

If we cap each entry of `eventsPerVid` at `maxFrequency` and then sum `eventsPerVid` up, we *directly* obtain the total number of impressions. WDYT of this option?


<!-- Sent from Reviewable.io -->

2024-01-11 18:07 UTC, kungfucraig approved these changes
I reviewed the tests, the behavior we are implementing is as desired. I will defer to @tristanvuong2021 on the implementation.

> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1413#-:-Nnth61D5Z1tc3WDw2GG:bog4ksq)* status: 1 of 5 files reviewed, 1 unresolved discussion (waiting on @riemanli and @tristanvuong2021)



<!-- Sent from Reviewable.io -->

2024-01-11 19:01 UTC, jiayu-google approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>
I confirm that the computation is implemented correctly --- it will output the correct impression measurement result and variance.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1413#-:-Nntt2qo-6JmW5IbUH65:bw8wa68)* status: 1 of 5 files reviewed, all discussions resolved (waiting on @tristanvuong2021)



<!-- Sent from Reviewable.io -->

2024-01-12 00:09 UTC, tristanvuong2021 requested changes
> Reviewed 1 of 5 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1413)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @jiayu-google, @kungfucraig, and @riemanli)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 1396 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1413#-NnuzymHA2fQW_cqAabI:-NnuzymHA2fQW_cqAabJ:b-k5yfsh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6959fd0f528256d39f6d7bc20d9cd0884ab089dd/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L1396)):*
> ```Kotlin
>           )
>         val scaledNoisedImpressionCount =
>           (sampledNoisedImpressionCount / measurementSpec.vidSamplingInterval.width).toLong()
> ```

Does this mean that a smaller width means a bigger impression count?


<!-- Sent from Reviewable.io -->

2024-01-12 00:21 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1413)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @jiayu-google, @kungfucraig, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 1396 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1413#-NnuzymHA2fQW_cqAabI:-Nnv-fqD54k2S52LbuLr:bzij33l) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6959fd0f528256d39f6d7bc20d9cd0884ab089dd/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L1396)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Does this mean that a smaller width means a bigger impression count?
</blockquote></details>

If the width is smaller, the sampled impression will be smaller too, but it will be scaled back to the magnitude it should be. 
For example, if the true impression is 100 and the sampling width is 0.1 (10% of the whole width), we will sample "roughly" 10% VIDs to compute the sampled impression. The sampled impression might be around 10 (100 * 10%). Let's assume the sample is 11. Since it's sampling, we need to scale it back to its original size. Thus we estimate the impression by 11 / 10% = 110. 


<!-- Sent from Reviewable.io -->

2024-01-12 02:58 UTC, tristanvuong2021 requested changes
> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1413)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @kungfucraig and @riemanli)

___
*[`src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt` line 2369 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1413#-NnvahI35KT6gkIw-gyY:-NnvadY77zGTYh-WhdnP:b-hf7fxv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6959fd0f528256d39f6d7bc20d9cd0884ab089dd/src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt#L2369)):*
> ```Kotlin
>     // Reach VIDs [18000001, 18001000] once and VIDs [18001001, 18002000] twice for one day. The
>     // event lasts for two days. 2 * (1000 + 1000 * 2) = 6000.
>     assertThat(result).impressionValue().isWithin(1.0 / vidSamplingWidth).of(5780L)
> ```

How is this calculated. Comment says 6000, but this is 5780.


<!-- Sent from Reviewable.io -->

2024-01-12 15:29 UTC, tristanvuong2021 requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1413)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @kungfucraig and @riemanli)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/measurementconsumer/MeasurementConsumerSimulator.kt` line 791 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1413#-NnyH8gU1lw0yxjASq5e:-NnyH8gU1lw0yxjASq5f:bxn6uja) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6959fd0f528256d39f6d7bc20d9cd0884ab089dd/src/main/kotlin/org/wfanet/measurement/loadtest/measurementconsumer/MeasurementConsumerSimulator.kt#L791)):*
> ```Kotlin
>       MeasurementSpec.MeasurementTypeCase.REACH_AND_FREQUENCY ->
>         getExpectedReachAndFrequencyResult(measurementInfo)
>       MeasurementSpec.MeasurementTypeCase.IMPRESSION -> getExpectedImpressionResult(measurementInfo)
> ```

I don't think getExpectedImpressionResult will ever be hit. You are accurately checking things by checking each individual result and never the sum of the results.


<!-- Sent from Reviewable.io -->

2024-01-12 15:29 UTC, tristanvuong2021 reviewed
> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1413)* status: all files reviewed, 2 unresolved discussions (waiting on @kungfucraig and @riemanli)



<!-- Sent from Reviewable.io -->

2024-01-13 01:37 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1413)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @kungfucraig and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/measurementconsumer/MeasurementConsumerSimulator.kt` line 791 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1413#-NnyH8gU1lw0yxjASq5e:-NnylwBj0Tckr_fe1Bl6:bjpoz5y) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6959fd0f528256d39f6d7bc20d9cd0884ab089dd/src/main/kotlin/org/wfanet/measurement/loadtest/measurementconsumer/MeasurementConsumerSimulator.kt#L791)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

I don't think getExpectedImpressionResult will ever be hit. You are accurately checking things by checking each individual result and never the sum of the results.
</blockquote></details>

I can remove it if that's desired. What's the expected behavior for the impression branch here? 
___
*[`src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt` line 2369 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1413#-NnvahI35KT6gkIw-gyY:-No-MHfL3vwOKgjMqmPP:b1vvfs5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6959fd0f528256d39f6d7bc20d9cd0884ab089dd/src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt#L2369)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

How is this calculated. Comment says 6000, but this is 5780.
</blockquote></details>

Thanks for catching that. This is incorrectly copied from the other test. Fixed the comment. 
Right now the expected value is hardcoded. In my next PR, I will will add code to compute the expected value from sampled VIDs for all types of measurements except duration.


<!-- Sent from Reviewable.io -->

2024-01-18 00:50 UTC, tristanvuong2021 reviewed
> Reviewed 1 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1413)* status: all files reviewed, 1 unresolved discussion (waiting on @kungfucraig)



<!-- Sent from Reviewable.io -->

2024-01-18 00:54 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1413)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @kungfucraig and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/measurementconsumer/MeasurementConsumerSimulator.kt` line 791 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1413#-NnyH8gU1lw0yxjASq5e:-NoP2k9t6XrykS1twnp_:b-xly5cy) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6959fd0f528256d39f6d7bc20d9cd0884ab089dd/src/main/kotlin/org/wfanet/measurement/loadtest/measurementconsumer/MeasurementConsumerSimulator.kt#L791)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

I can remove it if that's desired. What's the expected behavior for the impression branch here?
</blockquote></details>

Removed `getExpectedImpressionResult` and raised an error if the impression branch is reached.


<!-- Sent from Reviewable.io -->

2024-01-18 01:38 UTC, tristanvuong2021 approved these changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1413)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @kungfucraig)



<!-- Sent from Reviewable.io -->

2024-01-19 17:58 UTC, stevenwarejones approved these changes
> Reviewed 1 of 5 files at r1, 1 of 1 files at r3, 1 of 1 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1413)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @kungfucraig)



<!-- Sent from Reviewable.io -->

2024-01-23 19:58 UTC, riemanli reviewed
> Reviewed 1 of 5 files at r1, 1 of 1 files at r3, 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1413)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @kungfucraig)



<!-- Sent from Reviewable.io -->

2024-01-23 19:58 UTC, merged