Implement Internal EventGroups Service
world-federation-of-advertisers/cross-media-measurement pull request #143
Opened 2021-07-08 01:58 UTC by uakyol

2021-07-08 18:52 UTC, wangyaopw requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/143)* status: 0 of 15 files reviewed, 2 unresolved discussions (waiting on @SanjayVas and @uakyol)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerEventGroupsService.kt, line 43 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/143#-Me6R0Dm7lAzEOLDLw2_:-Me6R0Dm7lAzEOLDLw2a:b-4l7vwp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/35682c6088d834ea9ff0afb906f35f398053fef6/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerEventGroupsService.kt#L43)):*
> ```
>  println(e)
> ```
delete
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerEventGroupsService.kt, line 45 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/143#-Me6RKiw2Ewf1bPIsl18:-Me6RKiw2Ewf1bPIsl19:b95q2f2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/35682c6088d834ea9ff0afb906f35f398053fef6/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerEventGroupsService.kt#L45)):*
> ```
> NOT_FOUND
> ```
are IllegalArgumentExceptions always caused by NOT_FOUND?

`throw Status.NOT_FOUND.withCause(e).asRuntimeException()`?


<!-- Sent from Reviewable.io -->

2021-07-08 19:51 UTC, uakyol reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/143)* status: 0 of 15 files reviewed, 2 unresolved discussions (waiting on @SanjayVas and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerEventGroupsService.kt, line 43 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/143#-Me6R0Dm7lAzEOLDLw2_:-Me6e3gC5nUPeb-V8wr0:b-k73z76) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/35682c6088d834ea9ff0afb906f35f398053fef6/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerEventGroupsService.kt#L43)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
>  println(e)
> ```
delete
</blockquote></details>

thanks
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerEventGroupsService.kt, line 45 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/143#-Me6RKiw2Ewf1bPIsl18:-Me6f6GQCO3PokUASkgH:b-k73z76) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/35682c6088d834ea9ff0afb906f35f398053fef6/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerEventGroupsService.kt#L45)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
> NOT_FOUND
> ```
are IllegalArgumentExceptions always caused by NOT_FOUND?

`throw Status.NOT_FOUND.withCause(e).asRuntimeException()`?
</blockquote></details>

thanks


<!-- Sent from Reviewable.io -->

2021-07-08 20:51 UTC, wangyaopw reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/143)* status: 0 of 15 files reviewed, 3 unresolved discussions (waiting on @oliver-amzn, @SanjayVas, @uakyol, @wangyaopw, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerEventGroupsService.kt, line 43 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/143#-Me6sm6s7hgY4cvwrYfc:-Me6sm6s7hgY4cvwrYfd:bikfylw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9516198bb71e3579c263f6579460f29c2f0a493a/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerEventGroupsService.kt#L43)):*
> ```
>       throw StatusRuntimeException(
>         throw Status.NOT_FOUND.withCause(e).asRuntimeException()
>       )
> ```
just one throw ? 
`throw Status.NOT_FOUND.withCause(e).asRuntimeException()`


<!-- Sent from Reviewable.io -->

2021-07-08 23:13 UTC, uakyol reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/143)* status: 0 of 15 files reviewed, 3 unresolved discussions (waiting on @oliver-amzn, @SanjayVas, @wangyaopw, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerEventGroupsService.kt, line 43 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/143#-Me6sm6s7hgY4cvwrYfc:-Me7OS1f4d5dZEJGCl7o:b1farrt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9516198bb71e3579c263f6579460f29c2f0a493a/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerEventGroupsService.kt#L43)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
>       throw StatusRuntimeException(
>         throw Status.NOT_FOUND.withCause(e).asRuntimeException()
>       )
> ```
just one throw ? 
`throw Status.NOT_FOUND.withCause(e).asRuntimeException()`

</blockquote></details>

:man_facepalming: thanks!


<!-- Sent from Reviewable.io -->

2021-07-08 23:22 UTC, SanjayVas requested changes
> Reviewed 4 of 15 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/143)* status: 4 of 15 files reviewed, 5 unresolved discussions (waiting on @oliver-amzn, @SanjayVas, @uakyol, @wangyaopw, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerEventGroupsService.kt, line 45 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/143#-Me6RKiw2Ewf1bPIsl18:-Me7NkEHDjdyrkwcdtmS:b-mfu7tm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/35682c6088d834ea9ff0afb906f35f398053fef6/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerEventGroupsService.kt#L45)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

thanks
</blockquote></details>

This question still stands. Is this method known to throw `IllegalArgumentException` only on a condition that would mean that the parent is not found? If so, override `execute` on the writer in CreateEventGroup to document the condition(s) under which IllegalArgumentException is thrown using `@throws`. Additionally, add a message indicating specifically what isn't found.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerEventGroupsService.kt, line 41 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/143#-Me7M_wI78AY-sT0L3Tp:-Me7M_wI78AY-sT0L3Tq:bp7vgpj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9516198bb71e3579c263f6579460f29c2f0a493a/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerEventGroupsService.kt#L41)):*
> ```
> throw e.wrappedException ?: e
> ```
Why is this here? If we care about the fact that execute can throw a SpannerException, we should know something about the condition under which it was thrown so we can throw a StatusRuntimeException with a better code than the default. The `execute` method should also be documented with `@throws` describing the condition(s) under which SpannerException is thrown in this case.

Additionally, is there something about the wrapped exception that we care about unwrapping here?
___
*[src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateDataProviderLegacyTest.kt, line 1 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/143#-Me7QUhl1UhXr_SRdfzA:-Me7QUhl1UhXr_SRdfzB:bno8unt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0a020af63a2c9149e7f6f2f2728fff1f880571d5/src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateDataProviderLegacyTest.kt#L1)):*
> ```Kotlin
> // Copyright 2020 The Cross-Media Measurement Authors
> ```

Shouldn't this be in the parent PR?


<!-- Sent from Reviewable.io -->

2021-07-09 20:51 UTC, oliver-amzn requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/143)* status: 0 of 16 files reviewed, 7 unresolved discussions (waiting on @SanjayVas, @uakyol, @wangyaopw, and @zachcwc)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/143#-MeBZ3CM8qsO9_uFwii4:-MeBZ3CM8qsO9_uFwii5:bwpz11d) (no related file):*
Naming question: EventGroupReader vs CreateEventGroup - can/should this be consistent and be e.g. EventGroupCreator or GetEventGroup ? 

---
___
*[src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateLegacyDataProviderTest.kt, line 33 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/143#-MeC1N-D2y96wtBDCOoG:-MeC1N-F7-sMfWQttL8t:b-6tsg1i) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2fb1b2224a2d949590442039cd112f3c5ac718ba/src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateLegacyDataProviderTest.kt#L33)):*
> ```Kotlin
> 
> @RunWith(JUnit4::class)
> <<<<<<< HEAD:src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateLegacyDataProviderTest.kt
> ```

Got some merge artifacts here


<!-- Sent from Reviewable.io -->

2021-07-12 17:13 UTC, wangyaopw requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/143)* status: 0 of 16 files reviewed, 7 unresolved discussions (waiting on @SanjayVas, @uakyol, @wangyaopw, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateEventGroup.kt, line 31 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/143#-MeQgMjKBMa--ZF5ewAf:-MeQgMjKBMa--ZF5ewAg:b-5tgut1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/681773127bbd8ef2f3a6437dd7cc62ddba1683ad/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateEventGroup.kt#L31)):*
> ```
> MeasurementConsumerReader
> ```
 if any of these read() can find nothing, an error could be returned.
for example,

https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/main/kotlin/org/wfanet/measurement/duchy/deploy/gcloud/spanner/computation/GcpSpannerComputationsDatabaseTransactor.kt#L183

You can convert all failure cases to appropriate errors, and then in the service implementation, you don't need to wrap an exception, or catch and rethrow another exception.


<!-- Sent from Reviewable.io -->

2021-07-13 04:37 UTC, uakyol reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/143)* status: 0 of 36 files reviewed, 7 unresolved discussions (waiting on @oliver-amzn, @SanjayVas, @wangyaopw, and @zachcwc)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/143#-MeBZ3CM8qsO9_uFwii4:-MeCDONd-7FfAgtArhsT:bclxscc) (no related file):*
<details><summary><i>Previously, oliver-amzn (Oliver) wrote…</i></summary><blockquote>

Naming question: EventGroupReader vs CreateEventGroup - can/should this be consistent and be e.g. EventGroupCreator or GetEventGroup ? 
</blockquote></details>

We ended up having this naming convention from the previous implementation : https://github.com/world-federation-of-advertisers/cross-media-measurement/tree/main/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers . I don't have a strong view on this but if we want to change this I would vote to do it in another refactor PR and keep consistency for now 

---
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerEventGroupsService.kt, line 45 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/143#-Me6RKiw2Ewf1bPIsl18:-MeSUF5b0ikQoalWVbqL:bale7uy) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/35682c6088d834ea9ff0afb906f35f398053fef6/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerEventGroupsService.kt#L45)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This question still stands. Is this method known to throw `IllegalArgumentException` only on a condition that would mean that the parent is not found? If so, override `execute` on the writer in CreateEventGroup to document the condition(s) under which IllegalArgumentException is thrown using `@throws`. Additionally, add a message indicating specifically what isn't found.
</blockquote></details>

thank you. I went with throwing StatusRuntimeException in the creator. I am not sure if this is ok with you. If we don't want to throw status runtime here but only illegalArgument, then, I can change it to your proposal. 
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerEventGroupsService.kt, line 41 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/143#-Me7M_wI78AY-sT0L3Tp:-MeSQ-IfDuXKkKQ1Z7nv:byxoj01) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9516198bb71e3579c263f6579460f29c2f0a493a/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerEventGroupsService.kt#L41)):*
> IllegalArgumentException
shouldn't be here thanks for noticing
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateEventGroup.kt, line 31 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/143#-MeQgMjKBMa--ZF5ewAf:-MeSTt0eCuvGzepnY9eC:b-5etuxs) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/681773127bbd8ef2f3a6437dd7cc62ddba1683ad/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateEventGroup.kt#L31)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
> MeasurementConsumerReader
> ```
 if any of these read() can find nothing, an error could be returned.
for example,

https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/main/kotlin/org/wfanet/measurement/duchy/deploy/gcloud/spanner/computation/GcpSpannerComputationsDatabaseTransactor.kt#L183

You can convert all failure cases to appropriate errors, and then in the service implementation, you don't need to wrap an exception, or catch and rethrow another exception.
</blockquote></details>

Thanks for the help Yao, I went with throwing StatusRuntimeException in the creator. 
___
*[src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateLegacyDataProviderTest.kt, line 33 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/143#-MeC1N-D2y96wtBDCOoG:-MeCDKPp5BFzgBsOzWYV:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2fb1b2224a2d949590442039cd112f3c5ac718ba/src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateLegacyDataProviderTest.kt#L33)):*
<details><summary><i>Previously, oliver-amzn (Oliver) wrote…</i></summary><blockquote>

Got some merge artifacts here
</blockquote></details>

Done.
___
*[src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateDataProviderLegacyTest.kt, line 1 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/143#-Me7QUhl1UhXr_SRdfzA:-Me7digq1M5zMD5o5kfM:b-bxhrft) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0a020af63a2c9149e7f6f2f2728fff1f880571d5/src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateDataProviderLegacyTest.kt#L1)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Shouldn't this be in the parent PR?
</blockquote></details>

thanks for catching I resolved this conflict with parent


<!-- Sent from Reviewable.io -->

2021-07-13 11:13 UTC, oliver-amzn reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/143)* status: 0 of 36 files reviewed, 5 unresolved discussions (waiting on @SanjayVas, @wangyaopw, and @zachcwc)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/143#-MeBZ3CM8qsO9_uFwii4:-MeUZSJzBSujdXxS8UsM:bgn1by8) (no related file):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

We ended up having this naming convention from the previous implementation : https://github.com/world-federation-of-advertisers/cross-media-measurement/tree/main/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers . I don't have a strong view on this but if we want to change this I would vote to do it in another refactor PR and keep consistency for now 
</blockquote></details>

Makes sense, leave it as is.

---


<!-- Sent from Reviewable.io -->

2021-07-13 15:27 UTC, wangyaopw approved these changes
> Reviewed 2 of 33 files at r9, 4 of 13 files at r11, 8 of 20 files at r12, 1 of 3 files at r14.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/143)* status: 15 of 36 files reviewed, 7 unresolved discussions (waiting on @SanjayVas, @uakyol, @wangyaopw, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerEventGroupsService.kt, line 37 at r14](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/143#-MeVPmst-fI6TaqSWApl:-MeVPmst-fI6TaqSWApm:b-nwsvec) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/71d04ca248577357a644a824c00ae1d565d9dc97/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerEventGroupsService.kt#L37)):*
> ```
>   }
>   override suspend fun getEventGroup(request: GetEventGroupRequest): EventGroup {
> ```
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerEventGroupsService.kt, line 37 at r14](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/143#-MeVPo4vBkqzR7wNy8en:-MeVPo4vBkqzR7wNy8eo:bnxccq3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/71d04ca248577357a644a824c00ae1d565d9dc97/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerEventGroupsService.kt#L37)):*
> ```Kotlin
>     return CreateEventGroup(request).execute(client, idGenerator, clock)
>   }
>   override suspend fun getEventGroup(request: GetEventGroupRequest): EventGroup {
> ```

one newline above this function?, i.e.,
```
{

override xxx
}
```
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerEventGroupsService.kt, line 42 at r14](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/143#-MeVSbGQCiUdbL1oKpLF:-MeVSbGQCiUdbL1oKpLG:bd5fl6o) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/71d04ca248577357a644a824c00ae1d565d9dc97/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerEventGroupsService.kt#L42)):*
> ```
> ${request.externalEventGroupId}
> ```

just a concern here. The error message is using the long externalEventGroupId, which is not the base64UrlEncoded string used in the resourceName. So the publicApi needs to translate the error message before sending back to the user.

maybe don't include any id and just say EventGroup doesn't exist? or maybe use the resourceName everywhere in the errors? 

@sanjayvas  WDYT?


<!-- Sent from Reviewable.io -->

2021-07-13 19:12 UTC, SanjayVas requested changes
> Reviewed 2 of 13 files at r11, 3 of 20 files at r12, 1 of 3 files at r14.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/143)* status: 15 of 36 files reviewed, 7 unresolved discussions (waiting on @SanjayVas, @uakyol, @wangyaopw, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerEventGroupsService.kt, line 45 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/143#-Me6RKiw2Ewf1bPIsl18:-MeWDKrG2lvJzRr59kiH:bh3byzh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/35682c6088d834ea9ff0afb906f35f398053fef6/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerEventGroupsService.kt#L45)):*
> I went with throwing StatusRuntimeException in the creator. I am not sure if this is ok with you.

It is not. Only service impls should throw StatusRuntimeException.

Note that you may need to add a custom exception type if you need to pass more information from readers/writers to the service layer so it can determine the appropriate status code and message.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerEventGroupsService.kt, line 42 at r14](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/143#-MeVSbGQCiUdbL1oKpLF:-MeWF1TL27Nf5_8is7XZ:brhe802) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/71d04ca248577357a644a824c00ae1d565d9dc97/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerEventGroupsService.kt#L42)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
> ${request.externalEventGroupId}
> ```

just a concern here. The error message is using the long externalEventGroupId, which is not the base64UrlEncoded string used in the resourceName. So the publicApi needs to translate the error message before sending back to the user.

maybe don't include any id and just say EventGroup doesn't exist? or maybe use the resourceName everywhere in the errors? 

@sanjayvas  WDYT?
</blockquote></details>

Correct. Don't expose the integer IDs to the public API service caller. The resource name or the string IDs are fine. It's also not necessary to include it in the error message for a Get call, since that information is in the request.

Note that this also means you don't want to blindly include the error message from an internal exception in the StatusRuntimeException unless you know it doesn't contain sensitive/internal info.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateEventGroup.kt, line 31 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/143#-MeQgMjKBMa--ZF5ewAf:-MeWES9b3xdhihHcCU1Y:bebih5z) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/681773127bbd8ef2f3a6437dd7cc62ddba1683ad/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateEventGroup.kt#L31)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

Thanks for the help Yao, I went with throwing StatusRuntimeException in the creator. 
</blockquote></details>

Please fix based on other comment. Readers/writers should be unaware that they're called from gRPC services, and therefore should not throw StatusRuntimeException.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateEventGroup.kt, line 38 at r14](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/143#-MeWGOAO6n1tMvLycMJN:-MeWGOAO6n1tMvLycMJO:b-m8ixwi) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/71d04ca248577357a644a824c00ae1d565d9dc97/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateEventGroup.kt#L38)):*
> ```
> Status.NOT_FOUND
> ```
This case would be `INVALID_ARGUMENT`, not `NOT_FOUND`. `NOT_FOUND` is for if the resource you're acting on isn't found (which could be the case if the parent resource is not found, since it by definition means that the child resource cannot be).


<!-- Sent from Reviewable.io -->

2021-07-13 20:35 UTC, wangyaopw reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/143)* status: 15 of 36 files reviewed, 7 unresolved discussions (waiting on @SanjayVas, @uakyol, @wangyaopw, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerEventGroupsService.kt, line 45 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/143#-Me6RKiw2Ewf1bPIsl18:-MeWZxbO7gtZzp0OgsL7:b-brhjsn) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/35682c6088d834ea9ff0afb906f35f398053fef6/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerEventGroupsService.kt#L45)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> I went with throwing StatusRuntimeException in the creator. I am not sure if this is ok with you.

It is not. Only service impls should throw StatusRuntimeException.

Note that you may need to add a custom exception type if you need to pass more information from readers/writers to the service layer so it can determine the appropriate status code and message.
</blockquote></details>

actually I was thinking of using error(""something) instead of failGrpc() inside the spanner reader/writer, is that OK?


<!-- Sent from Reviewable.io -->

2021-07-13 20:50 UTC, uakyol reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/143)* status: 6 of 37 files reviewed, 7 unresolved discussions (waiting on @SanjayVas, @wangyaopw, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerEventGroupsService.kt, line 45 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/143#-Me6RKiw2Ewf1bPIsl18:-MeWcHhD9LoLXKsluJto:b-qo4gq3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/35682c6088d834ea9ff0afb906f35f398053fef6/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerEventGroupsService.kt#L45)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

actually I was thinking of using error(""something) instead of failGrpc() inside the spanner reader/writer, is that OK?
</blockquote></details>

I implemented a new error type as suggested by Sanjay to distinguish from any other error. 
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerEventGroupsService.kt, line 37 at r14](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/143#-MeVPmst-fI6TaqSWApl:-MeWN16J9dKBTIpWelsn:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/71d04ca248577357a644a824c00ae1d565d9dc97/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerEventGroupsService.kt#L37)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
>   }
>   override suspend fun getEventGroup(request: GetEventGroupRequest): EventGroup {
> ```

</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerEventGroupsService.kt, line 37 at r14](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/143#-MeVPo4vBkqzR7wNy8en:-MeWN0yK2uTLU9Thxf5D:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/71d04ca248577357a644a824c00ae1d565d9dc97/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerEventGroupsService.kt#L37)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

one newline above this function?, i.e.,
```
{

override xxx
}
```
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerEventGroupsService.kt, line 42 at r14](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/143#-MeVSbGQCiUdbL1oKpLF:-MeWcRigEZWYyvHShdhO:bczzrhq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/71d04ca248577357a644a824c00ae1d565d9dc97/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerEventGroupsService.kt#L42)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Correct. Don't expose the integer IDs to the public API service caller. The resource name or the string IDs are fine. It's also not necessary to include it in the error message for a Get call, since that information is in the request.

Note that this also means you don't want to blindly include the error message from an internal exception in the StatusRuntimeException unless you know it doesn't contain sensitive/internal info.
</blockquote></details>

Took out the error message, we just have enums that convey the information now
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateEventGroup.kt, line 31 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/143#-MeQgMjKBMa--ZF5ewAf:-MeWNGAr3IVj8mdlKIya:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/681773127bbd8ef2f3a6437dd7cc62ddba1683ad/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateEventGroup.kt#L31)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Please fix based on other comment. Readers/writers should be unaware that they're called from gRPC services, and therefore should not throw StatusRuntimeException.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateEventGroup.kt, line 38 at r14](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/143#-MeWGOAO6n1tMvLycMJN:-MeWcXUP8h-nMQ0_VSEx:b-idflxc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/71d04ca248577357a644a824c00ae1d565d9dc97/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateEventGroup.kt#L38)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> Status.NOT_FOUND
> ```
This case would be `INVALID_ARGUMENT`, not `NOT_FOUND`. `NOT_FOUND` is for if the resource you're acting on isn't found (which could be the case if the parent resource is not found, since it by definition means that the child resource cannot be).
</blockquote></details>

thanks. 
___
*[src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateDataProviderLegacyTest.kt, line 1 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/143#-Me7QUhl1UhXr_SRdfzA:-MeWM_cEDV1T_7Fwy8HJ:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0a020af63a2c9149e7f6f2f2728fff1f880571d5/src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateDataProviderLegacyTest.kt#L1)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

thanks for catching I resolved this conflict with parent
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-13 21:22 UTC, SanjayVas requested changes
> Reviewed 4 of 28 files at r15.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/143)* status: 10 of 37 files reviewed, 9 unresolved discussions (waiting on @oliver-amzn, @SanjayVas, @uakyol, @wangyaopw, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerEventGroupsService.kt, line 42 at r14](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/143#-MeVSbGQCiUdbL1oKpLF:-MeWidZA90hEQsVrSVD5:b-47g6dg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/71d04ca248577357a644a824c00ae1d565d9dc97/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerEventGroupsService.kt#L42)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

Took out the error message, we just have enums that convey the information now
</blockquote></details>

Looks like it's still showing `"No EventGroup with externalId ${request.externalEventGroupId}"` as the message.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerEventGroupsService.kt, line 45 at r15](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/143#-MeWhwru4IFPQ4uo3B80:-MeWhwru4IFPQ4uo3B81:b-pastzk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d2d6c6300dd40d1f374e15da84ec43c105e6f643/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerEventGroupsService.kt#L45)):*
> ```
> INVALID_ARGUMENT
> ```
This one should be `NOT_FOUND`, since DataProvider is a parent of EventGroup.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/common/KingdomInternalException.kt, line 19 at r15](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/143#-MeWipZV8J4eM4c4SMMk:-MeWipZV8J4eM4c4SMMl:b76lrn0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d2d6c6300dd40d1f374e15da84ec43c105e6f643/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/common/KingdomInternalException.kt#L19)):*
> ```
> KingdomInternalExceptionCode
> ```
Can just define this as `Code` inside of the exception class.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt, line 108 at r15](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/143#-MeWk-xz8Qjlrn1smBbV:-MeWk-xz8Qjlrn1smBbW:bx23wj6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d2d6c6300dd40d1f374e15da84ec43c105e6f643/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt#L108)):*
<details><summary><i alt="summary">Quoted 8 lines of code…</i></summary>

> ```
>     // We make sure that the externalMeasurementConsumerId is correct.
>     val measurementConsumerRead =
>       measurementConsumersService.getMeasurementConsumer(
>         GetMeasurementConsumerRequest.newBuilder()
>           .setExternalMeasurementConsumerId(externalMeasurementConsumerId.value)
>           .build()
>       )
>     assertThat(measurementConsumerRead).isEqualTo(createdMeasurementConsumer)
> ```
</details>

Don't do these assertions here. They're covered in the tests for MeasurementConsumers and DataProviders services.


<!-- Sent from Reviewable.io -->

2021-07-13 22:26 UTC, uakyol reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/143)* status: 7 of 37 files reviewed, 9 unresolved discussions (waiting on @oliver-amzn, @SanjayVas, @wangyaopw, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerEventGroupsService.kt, line 42 at r14](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/143#-MeVSbGQCiUdbL1oKpLF:-MeWsFrLC_uYKyeACcD4:b-k73z76) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/71d04ca248577357a644a824c00ae1d565d9dc97/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerEventGroupsService.kt#L42)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Looks like it's still showing `"No EventGroup with externalId ${request.externalEventGroupId}"` as the message.
</blockquote></details>

thanks
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerEventGroupsService.kt, line 45 at r15](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/143#-MeWhwru4IFPQ4uo3B80:-MeWsrx_DMor0DILw1zd:b-k73z76) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d2d6c6300dd40d1f374e15da84ec43c105e6f643/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerEventGroupsService.kt#L45)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> INVALID_ARGUMENT
> ```
This one should be `NOT_FOUND`, since DataProvider is a parent of EventGroup.
</blockquote></details>

thanks
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/common/KingdomInternalException.kt, line 19 at r15](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/143#-MeWipZV8J4eM4c4SMMk:-MeWsccg2Wq3fVZaCYSV:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d2d6c6300dd40d1f374e15da84ec43c105e6f643/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/common/KingdomInternalException.kt#L19)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> KingdomInternalExceptionCode
> ```
Can just define this as `Code` inside of the exception class.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt, line 108 at r15](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/143#-MeWk-xz8Qjlrn1smBbV:-MeWtUzm-GZqP39wydFe:byibtnp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d2d6c6300dd40d1f374e15da84ec43c105e6f643/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt#L108)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
>     // We make sure that the externalMeasurementConsumerId is correct.
>     val measurementConsumerRead =
>       measurementConsumersService.getMeasurementConsumer(
>         GetMeasurementConsumerRequest.newBuilder()
>           .setExternalMeasurementConsumerId(externalMeasurementConsumerId.value)
>           .build()
>       )
>     assertThat(measurementConsumerRead).isEqualTo(createdMeasurementConsumer)
> ```
Don't do these assertions here. They're covered in the tests for MeasurementConsumers and DataProviders services.
</blockquote></details>

sure, took them out


<!-- Sent from Reviewable.io -->

2021-07-13 23:14 UTC, SanjayVas approved these changes
> Reviewed 1 of 26 files at r8, 1 of 13 files at r11, 2 of 20 files at r12, 3 of 28 files at r15, 4 of 4 files at r16.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/143)* status: 15 of 37 files reviewed, 6 unresolved discussions (waiting on @oliver-amzn, @uakyol, @wangyaopw, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt, line 43 at r16](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/143#-MeX7RwNEKsUtW2ZX8MQ:-MeX7RwNEKsUtW2ZX8MR:b-jr5i27) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e6ab9b15a8c330857e2f4f72bf4e3636ecce85f0/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt#L43)):*
> ```
> FIXED_GENERATED_INTERNAL_ID
> ```
nit: How can this be both fixed and generated?
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt, line 95 at r16](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/143#-MeX6JEg4XVfzAsE026n:-MeX6JEh51eVUG7JLMxA:b5te5ha) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e6ab9b15a8c330857e2f4f72bf4e3636ecce85f0/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt#L95)):*
> ```
>     copyIdGenerator.generateInternalId()
> ```
Can do this in a follow-up PR, but maybe instead of having to keep a parallel generator you can make an IdGenerator that wraps another one and saves/exposes the generated IDs.


<!-- Sent from Reviewable.io -->

2021-07-14 00:01 UTC, uakyol reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/143)* status: 15 of 37 files reviewed, 4 unresolved discussions (waiting on @oliver-amzn, @wangyaopw, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt, line 95 at r16](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/143#-MeX6JEg4XVfzAsE026n:-MeXJAnxA2onFyiZ9ma0:bjgai2z) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e6ab9b15a8c330857e2f4f72bf4e3636ecce85f0/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt#L95)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
>     copyIdGenerator.generateInternalId()
> ```
Can do this in a follow-up PR, but maybe instead of having to keep a parallel generator you can make an IdGenerator that wraps another one and saves/exposes the generated IDs.
</blockquote></details>

ok will take it up in a follow-up PR


<!-- Sent from Reviewable.io -->

2021-07-14 00:12 UTC, SanjayVas approved these changes
> Reviewed 2 of 13 files at r11, 20 of 28 files at r15, 1 of 1 files at r17.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/143)* status: all files reviewed, 4 unresolved discussions (waiting on @wangyaopw and @zachcwc)



<!-- Sent from Reviewable.io -->

2021-07-14 05:54 UTC, uakyol reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/143)* status: all files reviewed, 4 unresolved discussions (waiting on @wangyaopw and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt, line 95 at r16](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/143#-MeX6JEg4XVfzAsE026n:-MeY_4tf5uxB2eb1uIag:bkkzs39) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e6ab9b15a8c330857e2f4f72bf4e3636ecce85f0/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt#L95)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

ok will take it up in a follow-up PR
</blockquote></details>

taking up in #149 (Implement ParallelIdGenerator and don't expose externalIds)     


<!-- Sent from Reviewable.io -->

2021-07-14 22:49 UTC, wangyaopw requested changes

2021-07-14 22:49 UTC, wangyaopw commented on src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateEventGroup.kt
> +        set("ProvidedEventGroupId" to eventGroup.providedEventGroupId)
The ProvidedEventGroupId is used for idempotency.

so somewhere it needs to check if an eventGroup with the same ProvidedEventGroupId exist or not. If yes, no need to create a new one, just return the existing one.

2021-07-15 05:39 UTC, uakyol reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/143)* status: 34 of 37 files reviewed, 5 unresolved discussions (waiting on @SanjayVas, @wangyaopw, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateEventGroup.kt, line 59 at r17](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/143#-Me2pdBhWBFdjc427OPt-r17-59:-MecfBkp1TPvW9RynR0H:b-regoxl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a6d7917009677b1d98c425039451a102a85cb220/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateEventGroup.kt#L59)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

The ProvidedEventGroupId is used for idempotency.

so somewhere it needs to check if an eventGroup with the same ProvidedEventGroupId exist or not. If yes, no need to create a new one, just return the existing one. 
</blockquote></details>

Thanks a lot for catching this Yao. I implemented it, let me know if this looks good.


<!-- Sent from Reviewable.io -->

2021-07-15 17:21 UTC, wangyaopw reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/143)* status: 34 of 37 files reviewed, 3 unresolved discussions (waiting on @SanjayVas, @uakyol, @wangyaopw, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateEventGroup.kt, line 57 at r18](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/143#-MefACdvA-6oOQLbXSTR:-MefACdw2yX2xQvm8M8H:b-whnz89) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/091a4ba967cdde6823d6fd6bb6c53bccb9042f90/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateEventGroup.kt#L57)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>     val existing = findExistingEventGroup(dataProviderId)
>     if (existing != null) {
>       return existing
>     }
> ```
</details>


maybe 

```
return findExistingEventGroup(dataProviderId) ?: createNewEventGroup(dataProviderId, measurementConsumerId)
```

where createNewEventGroup() is a helper method including the rest of codes you wrote


<!-- Sent from Reviewable.io -->

2021-07-15 18:25 UTC, uakyol reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/143)* status: 8 of 37 files reviewed, 3 unresolved discussions (waiting on @SanjayVas, @wangyaopw, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateEventGroup.kt, line 57 at r18](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/143#-MefACdvA-6oOQLbXSTR:-MefPaQD0CSge2vXlqZV:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/091a4ba967cdde6823d6fd6bb6c53bccb9042f90/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateEventGroup.kt#L57)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
>     val existing = findExistingEventGroup(dataProviderId)
>     if (existing != null) {
>       return existing
>     }
> ```

maybe 

```
return findExistingEventGroup(dataProviderId) ?: createNewEventGroup(dataProviderId, measurementConsumerId)
```

where createNewEventGroup() is a helper method including the rest of codes you wrote
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-15 18:30 UTC, wangyaopw approved these changes
> Reviewed 1 of 29 files at r21.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/143)* status: 9 of 37 files reviewed, 3 unresolved discussions (waiting on @SanjayVas, @wangyaopw, and @zachcwc)



<!-- Sent from Reviewable.io -->

2021-07-16 17:00 UTC, oliver-amzn approved these changes
> Reviewed 10 of 29 files at r21.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/143)* status: 19 of 37 files reviewed, all discussions resolved (waiting on @SanjayVas and @zachcwc)



<!-- Sent from Reviewable.io -->

2021-07-16 18:27 UTC, merged