Implement the shuffle phase of the HMSS protocol.
world-federation-of-advertisers/cross-media-measurement pull request #1437
Opened 2024-01-23 21:26 UTC by ple13

2024-01-23 21:27 UTC, wfa-reviewable commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1437)
<!-- Reviewable:end -->

2024-01-23 22:37 UTC, renjiezh requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1437)* status: 0 of 8 files reviewed, 3 unresolved discussions (waiting on @kungfucraig, @ple13, and @SanjayVas)

___
*[`src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/honest_majority_share_shuffle_utility.cc` line 155 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1437#-NosKkJQDUMat4sAB7TE:-NosKkJQDUMat4sAB7TF:bdpfbq0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6bb31452a826d046f715d5c3f728d872fb76d0d3/src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/honest_majority_share_shuffle_utility.cc#L155)):*
> ```cpp
>         if (request.sketch_shares().Get(i).data().values().size() !=
>             request.sketch_params().register_count()) {
>           return absl::InvalidArgumentError("Invalid input size.");
> ```

Printing with the index `i` helps to debug.
___
*[`src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/honest_majority_share_shuffle_utility.cc` line 161 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1437#-NosNV9t3u_2MV-f_Sfl:-NosNV9t3u_2MV-f_Sfm:bd1ugvr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6bb31452a826d046f715d5c3f728d872fb76d0d3/src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/honest_majority_share_shuffle_utility.cc#L161)):*
> ```cpp
>           // request.sketch_shares().Get(i).data().values(j)) is not greater
>           // than 2^{32}-1.
>           combined_sketch[j] =
> ```

How about reusing these lines with the case of kSeed below? That means `switch` only returns the vector(actually `absl::Span`) from data or seed. 
___
*[`src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/honest_majority_share_shuffle_utility.cc` line 214 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1437#-NosRtBSAnWbekjOiChT:-NosRtBSAnWbekjOiChU:bcogl7u) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6bb31452a826d046f715d5c3f728d872fb76d0d3/src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/honest_majority_share_shuffle_utility.cc#L214)):*
> ```cpp
>     // Worker 1: rand_vec_1 || rand_vec_2 <-- PRNG(seed).
>     // Worker 2: rand_vec_2 || rand_vec_2 <-- PRNG(seed).
>     // Worker 1 obtains shares: {first_local_noise_share ||
> ```

can we reformat these comments
```
// Worker 1 obtains shares: 
// {first_local_noise_share || second_local_noise_share} 
// = {(noise_registers_1 - rand_vec_1) || rand_vec_2}.
//  Worker 2 obtains shares: 
// {first_local_noise_share || second_local_noise_share} 
// = {rand_vec_1 || (noise_registers_2 - rand_vec_2)}.
```


<!-- Sent from Reviewable.io -->

2024-01-23 23:14 UTC, SanjayVas requested changes
> Reviewed 4 of 8 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1437)* status: all files reviewed, 11 unresolved discussions (waiting on @kungfucraig and @ple13)

___
*[`src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/honest_majority_share_shuffle_utility.h` line 21 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1437#-NosNyeB-hJWhimuHicm:-NosNyeB-hJWhimuHicn:b-os2bg6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6bb31452a826d046f715d5c3f728d872fb76d0d3/src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/honest_majority_share_shuffle_utility.h#L21)):*
> ```objc
> #include "wfa/measurement/internal/duchy/protocol/honest_majority_share_shuffle_methods.pb.h"
> 
> namespace wfa::measurement::internal::duchy::protocol::liquid_legions_v2 {
> ```

Shouldn't this be in a sibling package instead of under LLv2?



_Code quote:_
```objc
liquid_legions_v
```
___
*[`src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/honest_majority_share_shuffle_utility.cc` line 61 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1437#-NosY8X1BaxaSODE-8YN:-NosY8X1BaxaSODE-8YO:ba4ntlt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6bb31452a826d046f715d5c3f728d872fb76d0d3/src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/honest_majority_share_shuffle_utility.cc#L61)):*
> ```cpp
>       (1 + sketch_param.maximum_frequency());
>   // Sets all noise registers to the sentinel value (q-1).
>   std::vector<uint32_t> ret(total_noise_registers_count,
> ```

nit: prefer descriptive names. I derived the suggested name from the function name.



_Suggestion:_
```cpp
noise_registers
```
___
*[`src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/honest_majority_share_shuffle_utility.cc` line 77 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1437#-NosWRDZAkMXnHpTR7XN:-NosWRDZAkMXnHpTR7XO:b-u907ah) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6bb31452a826d046f715d5c3f728d872fb76d0d3/src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/honest_majority_share_shuffle_utility.cc#L77)):*
> ```cpp
> }
> 
> absl::StatusOr<PrngSeed> GetPrngSeedFromString(const std::string& seed_str) {
> ```

nit: Shouldn't these factory functions be class-level on PrngSeed rather than here, e.g. `PrngSeed::FromString(seed_str)`? Or is this encoding more specific to the HMSS protocol?
___
*[`src/main/proto/wfa/measurement/internal/duchy/protocol/honest_majority_share_shuffle_methods.proto` line 60 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1437#-NosZ0pF77OIxO-Q245i:-NosZ0pG08gph2QY23pt:b-rfgl6w) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6bb31452a826d046f715d5c3f728d872fb76d0d3/src/main/proto/wfa/measurement/internal/duchy/protocol/honest_majority_share_shuffle_methods.proto#L60)):*
> ```proto
>   // order.
>   message SketchShare {
>     message UInt32Array {
> ```

Don't use "array" as that implies a specific implementation which is not always (or in this case likely never) true for protobuf generated code. Since you're defining this as a nested message type, you can use a less generic type name.



_Suggestion:_
```proto
ShareData
```
___
*[`src/main/proto/wfa/measurement/internal/duchy/protocol/honest_majority_share_shuffle_methods.proto` line 77 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1437#-Nos_Bit8VR-X0hSkY-6:-Nos_Bit8VR-X0hSkY-7:bxz3pa3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6bb31452a826d046f715d5c3f728d872fb76d0d3/src/main/proto/wfa/measurement/internal/duchy/protocol/honest_majority_share_shuffle_methods.proto#L77)):*
> ```proto
>   // Combination of sketches. It is combined, noisy, and shuffled.
>   repeated uint32 combined_sketch = 1;
>   // The CPU time of processing the request.
> ```

Use specific types where available rather than primitives. In this case, the appropriate type would be google.protobuf.Duration.
___
*[`src/main/proto/wfa/measurement/internal/duchy/protocol/honest_majority_share_shuffle_methods.proto` line 78 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1437#-Nos_eo_2FvOpTBJdTgT:-Nos_eo_2FvOpTBJdTgU:bdi1196) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6bb31452a826d046f715d5c3f728d872fb76d0d3/src/main/proto/wfa/measurement/internal/duchy/protocol/honest_majority_share_shuffle_methods.proto#L78)):*
> ```proto
>   repeated uint32 combined_sketch = 1;
>   // The CPU time of processing the request.
>   int64 elapsed_cpu_time_millis = 2;
> ```

Do we perhaps want to extract a common `MethodStats` type for response messages?
___
*[`src/main/proto/wfa/measurement/internal/duchy/protocol/share_shuffle_sketch_params.proto` line 40 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1437#-Nosa4lOECZAdGhiYRMI:-Nosa4lPC8eotxcTEZq9:b-8iufa9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6bb31452a826d046f715d5c3f728d872fb76d0d3/src/main/proto/wfa/measurement/internal/duchy/protocol/share_shuffle_sketch_params.proto#L40)):*
> ```proto
> 
>   // The modulus used in the MPC protocol. It is required to be greater than or
>   // equal to (2 + maximum_frequency).
> ```

The error message in code says this is 1+max rather than 2+max. Which is correct?



_Code quote:_
```proto
2 + maximum_frequency
```
___
*[`src/test/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/honest_majority_share_shuffle_utility_test.cc` line 67 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1437#-NosaJY03lv4u-reGhbo:-NosaJY03lv4u-reGhbp:b-g59pb5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6bb31452a826d046f715d5c3f728d872fb76d0d3/src/test/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/honest_majority_share_shuffle_utility_test.cc#L67)):*
> ```cpp
>     CompleteShufflePhaseResponse;
> 
> constexpr int kEDPCount = 5;
> ```

nit: follow established rules for camel-casing w.r.t. acronyms and initialisms.



_Suggestion:_
```cpp
kEdpCount
```


<!-- Sent from Reviewable.io -->

2024-01-24 00:45 UTC, kungfucraig requested changes
> Reviewed 2 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1437)* status: all files reviewed, 13 unresolved discussions (waiting on @ple13 and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/internal/duchy/protocol/honest_majority_share_shuffle_methods.proto` line 36 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1437#-NosvCSu7wYpRIlboPip:-NosvCSu7wYpRIlboPiq:bn54pz1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6bb31452a826d046f715d5c3f728d872fb76d0d3/src/main/proto/wfa/measurement/internal/duchy/protocol/honest_majority_share_shuffle_methods.proto#L36)):*
> ```proto
> 
>   // Common random seed between the workers.
>   bytes common_random_seed = 2;
> ```

What's the thinking behind this change?
___
*[`src/main/proto/wfa/measurement/internal/duchy/protocol/honest_majority_share_shuffle_methods.proto` line 77 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1437#-Nos_Bit8VR-X0hSkY-6:-Nosuril8eVkarNVYR1H:bb76mt9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6bb31452a826d046f715d5c3f728d872fb76d0d3/src/main/proto/wfa/measurement/internal/duchy/protocol/honest_majority_share_shuffle_methods.proto#L77)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Use specific types where available rather than primitives. In this case, the appropriate type would be google.protobuf.Duration.
</blockquote></details>

Why 
___
*[`src/main/proto/wfa/measurement/internal/duchy/protocol/honest_majority_share_shuffle_methods.proto` line 78 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1437#-Nos_eo_2FvOpTBJdTgT:-NosusefEhcbGlR0_RZP:b-il3pvb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6bb31452a826d046f715d5c3f728d872fb76d0d3/src/main/proto/wfa/measurement/internal/duchy/protocol/honest_majority_share_shuffle_methods.proto#L78)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Do we perhaps want to extract a common `MethodStats` type for response messages?
</blockquote></details>

Why do we want these kinds of things in our responses at all? This is exactly the kind of information that open telemetry collects automatically. And if it's not, let's say it's some detailed processing information, then maybe the Duchy should store that locally in the computation stats table?
___
*[`src/main/proto/wfa/measurement/internal/duchy/protocol/share_shuffle_sketch_params.proto` line 37 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1437#-NosvK6n1AJbBvavtJgC:-NosvK6n1AJbBvavtJgD:b-vj0e6q) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6bb31452a826d046f715d5c3f728d872fb76d0d3/src/main/proto/wfa/measurement/internal/duchy/protocol/share_shuffle_sketch_params.proto#L37)):*
> ```proto
>   // of a sketch, and p the number of EDPs, the maximum frequency of the
>   // combined sketch is (1 + pN).
>   int32 maximum_frequency = 3;
> ```

call it "maximum_combined_frequency?"


<!-- Sent from Reviewable.io -->

2024-01-24 00:49 UTC, SanjayVas requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1437)* status: all files reviewed, 13 unresolved discussions (waiting on @kungfucraig and @ple13)

___
*[`src/main/proto/wfa/measurement/internal/duchy/protocol/honest_majority_share_shuffle_methods.proto` line 77 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1437#-Nos_Bit8VR-X0hSkY-6:-NosvkP34IE6AmpHbzS6:bd1wfuh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6bb31452a826d046f715d5c3f728d872fb76d0d3/src/main/proto/wfa/measurement/internal/duchy/protocol/honest_majority_share_shuffle_methods.proto#L77)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Why
</blockquote></details>

The common name for the code smell is "Primitive Obsession". It's the same reason one should use e.g. `java.time.Duration` in Java code instead of an integer milliseconds field.

While this isn't a public API, I believe the recommendation from [AIP-142](https://google.aip.dev/142#durations) makes sense for any protobuf API.


<!-- Sent from Reviewable.io -->

2024-01-24 00:53 UTC, kungfucraig reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1437)* status: all files reviewed, 13 unresolved discussions (waiting on @ple13 and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/internal/duchy/protocol/honest_majority_share_shuffle_methods.proto` line 77 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1437#-Nos_Bit8VR-X0hSkY-6:-NosxEttEQto0mG5VwkP:btsww80) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6bb31452a826d046f715d5c3f728d872fb76d0d3/src/main/proto/wfa/measurement/internal/duchy/protocol/honest_majority_share_shuffle_methods.proto#L77)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The common name for the code smell is "Primitive Obsession". It's the same reason one should use e.g. `java.time.Duration` in Java code instead of an integer milliseconds field.

While this isn't a public API, I believe the recommendation from [AIP-142](https://google.aip.dev/142#durations) makes sense for any protobuf API.
</blockquote></details>

Lol. I didn't mean to type that there. Sorry about that. :)


<!-- Sent from Reviewable.io -->

2024-01-24 00:54 UTC, SanjayVas requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1437)* status: all files reviewed, 13 unresolved discussions (waiting on @ple13)

___
*[`src/main/proto/wfa/measurement/internal/duchy/protocol/honest_majority_share_shuffle_methods.proto` line 78 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1437#-Nos_eo_2FvOpTBJdTgT:-NoswlrH-LPEBqmH3V_J:bktdt9r) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6bb31452a826d046f715d5c3f728d872fb76d0d3/src/main/proto/wfa/measurement/internal/duchy/protocol/honest_majority_share_shuffle_methods.proto#L78)):*
I'll leave @ple13 to give the actual answer, but my guess was that we wanted to know the CPU time specifically from the JNI C++ method. I'm not sure we can measure that from the JVM end, so it needs to be here in the JNI interface.

> maybe the Duchy should store that locally in the computation stats table?

I think you'd need this returned from the C++ method in order to write it to said table.


<!-- Sent from Reviewable.io -->

2024-01-24 00:55 UTC, kungfucraig reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1437)* status: all files reviewed, 13 unresolved discussions (waiting on @ple13 and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/internal/duchy/protocol/honest_majority_share_shuffle_methods.proto` line 78 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1437#-Nos_eo_2FvOpTBJdTgT:-NosxVF08spJa4swpqqf:by3a4ew) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6bb31452a826d046f715d5c3f728d872fb76d0d3/src/main/proto/wfa/measurement/internal/duchy/protocol/honest_majority_share_shuffle_methods.proto#L78)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I'll leave @ple13 to give the actual answer, but my guess was that we wanted to know the CPU time specifically from the JNI C++ method. I'm not sure we can measure that from the JVM end, so it needs to be here in the JNI interface.

> maybe the Duchy should store that locally in the computation stats table?

I think you'd need this returned from the C++ method in order to write it to said table.
</blockquote></details>

Right, sorry. I was just looking at the protos and lost track this was the JNI interface. 


<!-- Sent from Reviewable.io -->

2024-01-24 20:09 UTC, ple13 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1437)* status: 4 of 8 files reviewed, 11 unresolved discussions (waiting on @kungfucraig, @renjiezh, and @SanjayVas)

___
*[`src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/honest_majority_share_shuffle_utility.h` line 21 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1437#-NosNyeB-hJWhimuHicm:-Nox2JmIEOedkWvVb2cF:b-77xn0n) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6bb31452a826d046f715d5c3f728d872fb76d0d3/src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/honest_majority_share_shuffle_utility.h#L21)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Shouldn't this be in a sibling package instead of under LLv2?
</blockquote></details>

 It does make more sense to have a sibling package instead of putting it under LLv2. I'll rearrange it.
___
*[`src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/honest_majority_share_shuffle_utility.cc` line 61 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1437#-NosY8X1BaxaSODE-8YN:-Not_VRl0jXb6oXOAxXC:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6bb31452a826d046f715d5c3f728d872fb76d0d3/src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/honest_majority_share_shuffle_utility.cc#L61)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: prefer descriptive names. I derived the suggested name from the function name.
</blockquote></details>

Done.
___
*[`src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/honest_majority_share_shuffle_utility.cc` line 77 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1437#-NosWRDZAkMXnHpTR7XN:-Nowfv4s1xGFXGZuEsE_:bewya3f) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6bb31452a826d046f715d5c3f728d872fb76d0d3/src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/honest_majority_share_shuffle_utility.cc#L77)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: Shouldn't these factory functions be class-level on PrngSeed rather than here, e.g. `PrngSeed::FromString(seed_str)`? Or is this encoding more specific to the HMSS protocol?
</blockquote></details>

PrngSeed is a proto message.  I checked if it's possible to declare a member function for proto message, but it's not supported. I think we can have overloaded functions in any_sketch that can take either a string or a PrngSeed, then no conversion is needed. WDYT?
___
*[`src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/honest_majority_share_shuffle_utility.cc` line 155 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1437#-NosKkJQDUMat4sAB7TE:-NowoVsT-oeV9k0amzOU:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6bb31452a826d046f715d5c3f728d872fb76d0d3/src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/honest_majority_share_shuffle_utility.cc#L155)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

Printing with the index `i` helps to debug.
</blockquote></details>

Done.
___
*[`src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/honest_majority_share_shuffle_utility.cc` line 161 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1437#-NosNV9t3u_2MV-f_Sfl:-NowsigkBdkoqmIBG2Lf:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6bb31452a826d046f715d5c3f728d872fb76d0d3/src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/honest_majority_share_shuffle_utility.cc#L161)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

How about reusing these lines with the case of kSeed below? That means `switch` only returns the vector(actually `absl::Span`) from data or seed.
</blockquote></details>

Done.
___
*[`src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/honest_majority_share_shuffle_utility.cc` line 214 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1437#-NosRtBSAnWbekjOiChT:-NowpMKD5bizegQqOJXC:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6bb31452a826d046f715d5c3f728d872fb76d0d3/src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/honest_majority_share_shuffle_utility.cc#L214)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

can we reformat these comments
```
// Worker 1 obtains shares: 
// {first_local_noise_share || second_local_noise_share} 
// = {(noise_registers_1 - rand_vec_1) || rand_vec_2}.
//  Worker 2 obtains shares: 
// {first_local_noise_share || second_local_noise_share} 
// = {rand_vec_1 || (noise_registers_2 - rand_vec_2)}.
```
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/internal/duchy/protocol/honest_majority_share_shuffle_methods.proto` line 36 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1437#-NosvCSu7wYpRIlboPip:-NotZU9TB3FZHZcS8Alr:b-tim5a0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6bb31452a826d046f715d5c3f728d872fb76d0d3/src/main/proto/wfa/measurement/internal/duchy/protocol/honest_majority_share_shuffle_methods.proto#L36)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

What's the thinking behind this change?
</blockquote></details>

The workers combine the own/peer's seeds before the shuffle phase and have written the combined common seed to the computation details. So in the shuffle phase, we should just read the common seed and use it directly instead of own/peer's seeds separately.
___
*[`src/main/proto/wfa/measurement/internal/duchy/protocol/honest_majority_share_shuffle_methods.proto` line 60 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1437#-NosZ0pF77OIxO-Q245i:-Not_l3gElYybDqNLGRd:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6bb31452a826d046f715d5c3f728d872fb76d0d3/src/main/proto/wfa/measurement/internal/duchy/protocol/honest_majority_share_shuffle_methods.proto#L60)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Don't use "array" as that implies a specific implementation which is not always (or in this case likely never) true for protobuf generated code. Since you're defining this as a nested message type, you can use a less generic type name.
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/internal/duchy/protocol/honest_majority_share_shuffle_methods.proto` line 77 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1437#-Nos_Bit8VR-X0hSkY-6:-Nox0qiR2gND2yDLHaO7:btt77lo) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6bb31452a826d046f715d5c3f728d872fb76d0d3/src/main/proto/wfa/measurement/internal/duchy/protocol/honest_majority_share_shuffle_methods.proto#L77)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Lol. I didn't mean to type that there. Sorry about that. :)
</blockquote></details>

The current primitive type is compatible with the way we do logging (for example https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f38a8c573fe4c5555cefb4a9c02ec88cd546468b/src/main/kotlin/org/wfanet/meas [...]

2024-01-24 20:54 UTC, SanjayVas requested changes
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1437)* status: all files reviewed, 8 unresolved discussions (waiting on @kungfucraig, @ple13, and @renjiezh)

___
*[`src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/honest_majority_share_shuffle_utility.cc` line 77 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1437#-NosWRDZAkMXnHpTR7XN:-NoxEGOL0ouhlzJIEEQb:b-bpeh34) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6bb31452a826d046f715d5c3f728d872fb76d0d3/src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/honest_majority_share_shuffle_utility.cc#L77)):*
> PrngSeed is a proto message

Ah, I wasn't aware. That's reason enough, no need to do anything else.
___
*[`src/main/proto/wfa/measurement/internal/duchy/protocol/honest_majority_share_shuffle_methods.proto` line 77 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1437#-Nos_Bit8VR-X0hSkY-6:-NoxElH-0S5UlmW5Anng:b-em5osk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6bb31452a826d046f715d5c3f728d872fb76d0d3/src/main/proto/wfa/measurement/internal/duchy/protocol/honest_majority_share_shuffle_methods.proto#L77)):*
> it's better just to use google.protobuf.Duration, then do a conversion when we log

This. Basically you use specific types wherever you can, and convert to primitives as-needed at the edges.


<!-- Sent from Reviewable.io -->

2024-01-24 21:17 UTC, renjiezh requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1437)* status: all files reviewed, 6 unresolved discussions (waiting on @kungfucraig, @ple13, and @SanjayVas)

___
*[`src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/honest_majority_share_shuffle_utility.cc` line 161 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1437#-NosNV9t3u_2MV-f_Sfl:-NoxJ9WFCJlOoGjgAYfx:b-fsetz9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6bb31452a826d046f715d5c3f728d872fb76d0d3/src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/honest_majority_share_shuffle_utility.cc#L161)):*
<details><summary><i>Previously, ple13 (Phi) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

`share_vector` will copy the content from `sketch_shares`. We might use `absl::Span<uint32_t> share_vector` instead. 
___
*[`src/main/proto/wfa/measurement/internal/duchy/protocol/honest_majority_share_shuffle_methods.proto` line 78 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1437#-Nos_eo_2FvOpTBJdTgT:-NowOpGc6yHFHL4Pe_sJ:bryyafc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6bb31452a826d046f715d5c3f728d872fb76d0d3/src/main/proto/wfa/measurement/internal/duchy/protocol/honest_majority_share_shuffle_methods.proto#L78)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Right, sorry. I was just looking at the protos and lost track this was the JNI interface.
</blockquote></details>

I will revisit the metrics related part. We could currently leave it like this.


<!-- Sent from Reviewable.io -->

2024-01-24 23:36 UTC, renjiezh reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1437)* status: all files reviewed, 5 unresolved discussions (waiting on @kungfucraig, @ple13, and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/internal/duchy/protocol/honest_majority_share_shuffle_methods.proto` line 36 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1437#-NosvCSu7wYpRIlboPip:-NoxkhaE8Wx89LvCVkqy:b18m81u) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6bb31452a826d046f715d5c3f728d872fb76d0d3/src/main/proto/wfa/measurement/internal/duchy/protocol/honest_majority_share_shuffle_methods.proto#L36)):*
<details><summary><i>Previously, ple13 (Phi) wrote…</i></summary><blockquote>

The workers combine the own/peer's seeds before the shuffle phase and have written the combined common seed to the computation details. So in the shuffle phase, we should just read the common seed and use it directly instead of own/peer's seeds separately.
</blockquote></details>

For shuffle, yes I understand. But for noise, does that mean worker_1 and worker_2 will use the same random seed? I was thinking they are using different seeds for noise and use the same seed(combined seed) for shuffle.
thus:
```
// Worker 1: rand_vec_1 || rand_vec_2 <-- PRNG(seed_1).
// = {(noise_registers_1 - rand_vec_1_from_seed_1 ) || rand_vec_2_from_seed_2}.
// Worker 2: rand_vec_2 || rand_vec_2 <-- PRNG(seed_2).
// = {rand_vec_1_from_seed_1 || (noise_registers_2 - rand_vec_2_from_seed_2)}.
```


<!-- Sent from Reviewable.io -->

2024-01-25 11:01 UTC, ple13 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1437)* status: all files reviewed, 5 unresolved discussions (waiting on @kungfucraig, @renjiezh, and @SanjayVas)

___
*[`src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/honest_majority_share_shuffle_utility.cc` line 161 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1437#-NosNV9t3u_2MV-f_Sfl:-NozuBWW9hArA1mXl7LH:b-elzk9w) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6bb31452a826d046f715d5c3f728d872fb76d0d3/src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/honest_majority_share_shuffle_utility.cc#L161)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

`share_vector` will copy the content from `sketch_shares`. We might use `absl::Span<uint32_t> share_vector` instead.
</blockquote></details>

absl::Span is not compatible with repeated fields. [go/totw/145](https://goto.google.com/totw/145) suggests using gtl::AnySpan, however, I'm not sure we want to (or can) depend on gtl.
___
*[`src/main/proto/wfa/measurement/internal/duchy/protocol/honest_majority_share_shuffle_methods.proto` line 36 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1437#-NosvCSu7wYpRIlboPip:-Nozh2Zm75NlEilmKs3U:b-2jitv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6bb31452a826d046f715d5c3f728d872fb76d0d3/src/main/proto/wfa/measurement/internal/duchy/protocol/honest_majority_share_shuffle_methods.proto#L36)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

For shuffle, yes I understand. But for noise, does that mean worker_1 and worker_2 will use the same random seed? I was thinking they are using different seeds for noise and use the same seed(combined seed) for shuffle.
thus:
```
// Worker 1: rand_vec_1 || rand_vec_2 <-- PRNG(seed_1).
// = {(noise_registers_1 - rand_vec_1_from_seed_1 ) || rand_vec_2_from_seed_2}.
// Worker 2: rand_vec_2 || rand_vec_2 <-- PRNG(seed_2).
// = {rand_vec_1_from_seed_1 || (noise_registers_2 - rand_vec_2_from_seed_2)}.
```
</blockquote></details>

That's not correct. Both workers need to use the same seed(s) to generate the correlated randomness.

In our protocol (https://docs.google.com/document/d/1GScG9yVc5OpZBrD0S717ADHTiLT118WNB2rsQkA_KFU/edit?tab=t.0#heading=h.v3cdopv556i1), workers have 2 seeds {own_seed, peer_seed} as you mentioned. 

The protocol according to the document is:
// Worker 1: rand_vec_1 || rand_vec_2 <-- PRNG(own_seed) || PRNG(peer_seed)
// Worker 2: rand_vec_1 || rand_vec_2 <-- PRNG(peer_seed) || PRNG(own_seed)

Then they use the random vectors to get the share of the noise. This, however, requires 2 PRNGs. We can optimize it by having both workers do the following:

// Worker 1 & 2: rand_vec_1 || rand_vec_2 <-- PRNG(own_seed \XOR peer_seed)

So, we only need 1 PRNG. The code is much cleaner and achieves the same goal that is to generate the same common random vector {rand_vec_1 || rand_vec_2}.
___
*[`src/main/proto/wfa/measurement/internal/duchy/protocol/honest_majority_share_shuffle_methods.proto` line 77 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1437#-Nos_Bit8VR-X0hSkY-6:-Nozu718EYgtVeYq86P7:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6bb31452a826d046f715d5c3f728d872fb76d0d3/src/main/proto/wfa/measurement/internal/duchy/protocol/honest_majority_share_shuffle_methods.proto#L77)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> it's better just to use google.protobuf.Duration, then do a conversion when we log

This. Basically you use specific types wherever you can, and convert to primitives as-needed at the edges.
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/internal/duchy/protocol/honest_majority_share_shuffle_methods.proto` line 78 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1437#-Nos_eo_2FvOpTBJdTgT:-Nozu7t1ClgUTg5--MuV:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6bb31452a826d046f715d5c3f728d872fb76d0d3/src/main/proto/wfa/measurement/internal/duchy/protocol/honest_majority_share_shuffle_methods.proto#L78)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

I will revisit the metrics related part. We could currently leave it like this.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-01-25 18:51 UTC, SanjayVas reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1437)* status: 6 of 9 files reviewed, 5 unresolved discussions (waiting on @kungfucraig and @renjiezh)

___
*[`src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/honest_majority_share_shuffle_utility.cc` line 161 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1437#-NosNV9t3u_2MV-f_Sfl:-Np0wZ_uCr8qYMODVyK2:b-mj58ld) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6bb31452a826d046f715d5c3f728d872fb76d0d3/src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/honest_majority_share_shuffle_utility.cc#L161)):*
<details><summary><i>Previously, ple13 (Phi) wrote…</i></summary><blockquote>

absl::Span is not compatible with repeated fields. [go/totw/145](https://goto.google.com/totw/145) suggests using gtl::AnySpan, however, I'm not sure we want to (or can) depend on gtl.
</blockquote></details>

gtl is fully Google-internal, as it that specific TotW. The public ones are at https://abseil.io/tips/ (you'll notice that 145 isn't there).

I do not believe there's any equivalent interface that works for both std::vector and google::protobuf::RepeatedField.


<!-- Sent from Reviewable.io -->

2024-01-25 19:13 UTC, renjiezh requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1437)* status: 6 of 9 files reviewed, 5 unresolved discussions (waiting on @kungfucraig and @SanjayVas)

___
*[`src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/honest_majority_share_shuffle_utility.cc` line 161 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1437#-NosNV9t3u_2MV-f_Sfl:-Np0yBEf0tArrmUtWHms:bjr57qs) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6bb31452a826d046f715d5c3f728d872fb76d0d3/src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/honest_majority_share_shuffle_utility.cc#L161)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

gtl is fully Google-internal, as it that specific TotW. The public ones are at https://abseil.io/tips/ (you'll notice that 145 isn't there).

I do not believe there's any equivalent interface that works for both std::vector and google::protobuf::RepeatedField.
</blockquote></details>

In this case, `Span` won't help. Could we rollback the change according to my previous comment and avoid extra copy here. Sorry about the trouble.
___
*[`src/main/proto/wfa/measurement/internal/duchy/protocol/honest_majority_share_shuffle_methods.proto` line 36 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1437#-NosvCSu7wYpRIlboPip:-Np10O1b7SC_2yi-v4Mb:bc2x1mr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6bb31452a826d046f715d5c3f728d872fb76d0d3/src/main/proto/wfa/measurement/internal/duchy/protocol/honest_majority_share_shuffle_methods.proto#L36)):*
<details><summary><i>Previously, ple13 (Phi) wrote…</i></summary><blockquote>

That's not correct. Both workers need to use the same seed(s) to generate the correlated randomness.

In our protocol (https://docs.google.com/document/d/1GScG9yVc5OpZBrD0S717ADHTiLT118WNB2rsQkA_KFU/edit?tab=t.0#heading=h.v3cdopv556i1), workers have 2 seeds {own_seed, peer_seed} as you mentioned. 

The protocol according to the document is:
// Worker 1: rand_vec_1 || rand_vec_2 <-- PRNG(own_seed) || PRNG(peer_seed)
// Worker 2: rand_vec_1 || rand_vec_2 <-- PRNG(peer_seed) || PRNG(own_seed)

Then they use the random vectors to get the share of the noise. This, however, requires 2 PRNGs. We can optimize it by having both workers do the following:

// Worker 1 & 2: rand_vec_1 || rand_vec_2 <-- PRNG(own_seed \XOR peer_seed)

So, we only need 1 PRNG. The code is much cleaner and achieves the same goal that is to generate the same common random vector {rand_vec_1 || rand_vec_2}.
</blockquote></details>

I see. Thanks for the thorough explanation.


<!-- Sent from Reviewable.io -->

2024-01-25 20:43 UTC, ple13 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1437)* status: 6 of 9 files reviewed, 5 unresolved discussions (waiting on @kungfucraig, @renjiezh, and @SanjayVas)

___
*[`src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/honest_majority_share_shuffle_utility.h` line 21 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1437#-NosNyeB-hJWhimuHicm:-Np1LZgr0G_g5m6zXhtF:b-2kccvy) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6bb31452a826d046f715d5c3f728d872fb76d0d3/src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/honest_majority_share_shuffle_utility.h#L21)):*
<details><summary><i>Previously, ple13 (Phi) wrote…</i></summary><blockquote>

It does make more sense to have a sibling package instead of putting it under LLv2. I'll rearrange it.
</blockquote></details>

Would it be okay if I have the restructure done in another PR?
___
*[`src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/honest_majority_share_shuffle_utility.cc` line 161 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1437#-NosNV9t3u_2MV-f_Sfl:-Np1LmepDYbAi2CY2wPz:bk43mgf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6bb31452a826d046f715d5c3f728d872fb76d0d3/src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/honest_majority_share_shuffle_utility.cc#L161)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

In this case, `Span` won't help. Could we rollback the change according to my previous comment and avoid extra copy here. Sorry about the trouble.
</blockquote></details>

I'm leaning toward paying for an extra copy. In exchange, the code is cleaner, and more robust. We have a single size check for both cases (share is a vector, share is expanded from a seed). WDYT?
___
*[`src/main/proto/wfa/measurement/internal/duchy/protocol/honest_majority_share_shuffle_methods.proto` line 36 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1437#-NosvCSu7wYpRIlboPip:-Np1Fjcv7bHdonEyPgcq:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6bb31452a826d046f715d5c3f728d872fb76d0d3/src/main/proto/wfa/measurement/internal/duchy/protocol/honest_majority_share_shuffle_methods.proto#L36)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

I see. Thanks for the thorough explanation.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-01-25 20:52 UTC, SanjayVas requested changes
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1437)* status: all files reviewed, 4 unresolved discussions (waiting on @kungfucraig, @ple13, and @renjiezh)

___
*[`src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/honest_majority_share_shuffle_utility.h` line 21 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1437#-NosNyeB-hJWhimuHicm:-Np1O9fS0oJs1gXLKvSS:b-bdupqt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6bb31452a826d046f715d5c3f728d872fb76d0d3/src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/honest_majority_share_shuffle_utility.h#L21)):*
<details><summary><i>Previously, ple13 (Phi) wrote…</i></summary><blockquote>

Would it be okay if I have the restructure done in another PR?
</blockquote></details>

Sure, just leave a TODO here if you plan on merging this first.


<!-- Sent from Reviewable.io -->

2024-01-25 21:31 UTC, ple13 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1437)* status: 8 of 9 files reviewed, 4 unresolved discussions (waiting on @kungfucraig, @renjiezh, and @SanjayVas)

___
*[`src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/honest_majority_share_shuffle_utility.h` line 21 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1437#-NosNyeB-hJWhimuHicm:-Np1Wp9r2yDOy1AaDyZn:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6bb31452a826d046f715d5c3f728d872fb76d0d3/src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/honest_majority_share_shuffle_utility.h#L21)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Sure, just leave a TODO here if you plan on merging this first.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-01-25 22:18 UTC, SanjayVas approved these changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1437)* status: all files reviewed, 3 unresolved discussions (waiting on @kungfucraig and @renjiezh)



<!-- Sent from Reviewable.io -->

2024-01-25 23:01 UTC, renjiezh reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1437)* status: all files reviewed, 2 unresolved discussions (waiting on @kungfucraig)

___
*[`src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/honest_majority_share_shuffle_utility.cc` line 161 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1437#-NosNV9t3u_2MV-f_Sfl:-Np1qf0P-0iyLO6tpbyG:b-wsatcg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6bb31452a826d046f715d5c3f728d872fb76d0d3/src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/honest_majority_share_shuffle_utility.cc#L161)):*
<details><summary><i>Previously, ple13 (Phi) wrote…</i></summary><blockquote>

I'm leaning toward paying for an extra copy. In exchange, the code is cleaner, and more robust. We have a single size check for both cases (share is a vector, share is expanded from a seed). WDYT?
</blockquote></details>

Sounds good. But let's keep it in mind in case we want to squeeze for more performance gain.


<!-- Sent from Reviewable.io -->

2024-01-25 23:13 UTC, kungfucraig requested changes
> Reviewed 2 of 8 files at r1, 1 of 4 files at r2, 1 of 4 files at r3, 3 of 3 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1437)* status: all files reviewed, 4 unresolved discussions (waiting on @ple13)

___
*[`src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/honest_majority_share_shuffle_utility.h` line 21 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1437#-Np1oBbBCs5KlPBJAf65:-Np1oBbBCs5KlPBJAf66:b-fcxna0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/35539399ba2399ee034747d44783bdcbd6c723da/src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/honest_majority_share_shuffle_utility.h#L21)):*
> ```objc
> #include "wfa/measurement/internal/duchy/protocol/honest_majority_share_shuffle_methods.pb.h"
> 
> // TODO(@ple13): Move the HMSS protocol to a sibling folder of LLv2.
> ```

Why not just do this now? I guess if other files have already been created like this it makes more sense to have the todo... 
___
*[`src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/honest_majority_share_shuffle_utility.cc` line 51 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1437#-Np1plqF2kHLcRlUd8r3:-Np1plqF2kHLcRlUd8r4:bcvbnvr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/35539399ba2399ee034747d44783bdcbd6c723da/src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/honest_majority_share_shuffle_utility.cc#L51)):*
> ```cpp
> using ::wfa::measurement::common::crypto::SecureShuffleWithSeed;
> 
> absl::StatusOr<std::vector<uint32_t>> GenerateNoiseRegisters(
> ```

What do you think of extracting the helper functions to a header file and writing unit tests for them? GenerateNoiseRegisters seems especially worthy of this.
___
*[`src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/honest_majority_share_shuffle_utility.cc` line 152 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1437#-Np1tINQ9gjXvBzOPAqh:-Np1tINQ9gjXvBzOPAqi:bvq7w9r) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/35539399ba2399ee034747d44783bdcbd6c723da/src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/honest_majority_share_shuffle_utility.cc#L152)):*
> ```cpp
>   const int sketch_size = request.sketch_params().register_count();
> 
>   // Combines the input shares.
> ```

Consider adding a helper function called "CombineShares," and test it independently.
___
*[`src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/honest_majority_share_shuffle_utility.cc` line 221 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1437#-Np1siOh6ftuwF9vxFds:-Np1siOh6ftuwF9vxFdt:bj70lrv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/35539399ba2399ee034747d44783bdcbd6c723da/src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/honest_majority_share_shuffle_utility.cc#L221)):*
> ```cpp
>     // {first_local_noise_share ||second_local_noise_share}
>     // = {rand_vec_1 || (noise_registers_2 - rand_vec_2)}.
>     if (request.order() == CompleteShufflePhaseRequest::FIRST) {
> ```

I think you could have a helper function that both branches could call that would commonalize a lot of the code. Moreover, that helper function could be extracted to a header file and unit tested. :)


<!-- Sent from Reviewable.io -->

2024-02-02 20:35 UTC, SanjayVas requested changes
> Reviewed 20 of 20 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1437)* status: all files reviewed, 5 unresolved discussions (waiting on @kungfucraig and @ple13)

___
*[`src/main/cc/wfa/measurement/internal/duchy/protocol/share_shuffle/honest_majority_share_shuffle_utility.cc` line 184 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1437#-NpfW_Ga-9xWQmHZwiJ8:-NpfW_Ga-9xWQmHZwiJ9:b7k4aph) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/26abf8269ae3753c46724546bdd1f4a09642bbbd/src/main/cc/wfa/measurement/internal/duchy/protocol/share_shuffle/honest_majority_share_shuffle_utility.cc#L184)):*
> ```cpp
>                                           combined_sketch.end());
>   int64_t elapsed_cpu_time_millis = timer.ElapsedMillis();
>   response.mutable_elapsed_cpu_time()->set_seconds(elapsed_cpu_time_millis /
> ```

Don't manipulate `Duration` messages manually. Use [`google::protobuf::util::TimeUtil`](https://protobuf.dev/reference/cpp/api-docs/google.protobuf.util.time_util/)


<!-- Sent from Reviewable.io -->

2024-02-06 18:19 UTC, ple13 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1437)* status: 20 of 22 files reviewed, 1 unresolved discussion (waiting on @kungfucraig and @SanjayVas)

___
*[`src/main/cc/wfa/measurement/internal/duchy/protocol/share_shuffle/honest_majority_share_shuffle_utility.cc` line 184 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1437#-NpfW_Ga-9xWQmHZwiJ8:-Npzc_av5rYNO1pn1R46:b-qwqhb7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/26abf8269ae3753c46724546bdd1f4a09642bbbd/src/main/cc/wfa/measurement/internal/duchy/protocol/share_shuffle/honest_majority_share_shuffle_utility.cc#L184)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Don't manipulate `Duration` messages manually. Use [`google::protobuf::util::TimeUtil`](https://protobuf.dev/reference/cpp/api-docs/google.protobuf.util.time_util/)
</blockquote></details>

I had the issue with Timestamp.pb.h (bazel complains that it was compiled with an old protoc version) even after changing the rules_proto to 6.0.0-rc2. I will use int64 here temporarily with a TODO. WDYT?


<!-- Sent from Reviewable.io -->

2024-02-07 19:53 UTC, renjiezh approved these changes
> Reviewed 1 of 4 files at r3, 19 of 20 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1437)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)



<!-- Sent from Reviewable.io -->

2024-02-09 17:48 UTC, SanjayVas requested changes
> Reviewed 1 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1437)* status: all files reviewed, 1 unresolved discussion (waiting on @ple13 and @stevenwarejones)

___
*[`src/main/cc/wfa/measurement/internal/duchy/protocol/share_shuffle/honest_majority_share_shuffle_utility.cc` line 184 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1437#-NpfW_Ga-9xWQmHZwiJ8:-NqDymN_B1CotQ5oiIdD:b4p77s3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/26abf8269ae3753c46724546bdd1f4a09642bbbd/src/main/cc/wfa/measurement/internal/duchy/protocol/share_shuffle/honest_majority_share_shuffle_utility.cc#L184)):*
<details><summary><i>Previously, ple13 (Phi) wrote…</i></summary><blockquote>

I had the issue with Timestamp.pb.h (bazel complains that it was compiled with an old protoc version) even after changing the rules_proto to 6.0.0-rc2. I will use int64 here temporarily with a TODO. WDYT?
</blockquote></details>

I'd rather stick with Duration done manually and have a TODO to use TimeUtil once we can resolve the dependency issue.


<!-- Sent from Reviewable.io -->

2024-02-09 17:49 UTC, SanjayVas requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1437)* status: all files reviewed, 1 unresolved discussion (waiting on @ple13 and @stevenwarejones)

___
*[`src/main/cc/wfa/measurement/internal/duchy/protocol/share_shuffle/honest_majority_share_shuffle_utility.cc` line 184 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1437#-NpfW_Ga-9xWQmHZwiJ8:-NqDz1jKBW-e7o5ixjao:b1xjedo) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/26abf8269ae3753c46724546bdd1f4a09642bbbd/src/main/cc/wfa/measurement/internal/duchy/protocol/share_shuffle/honest_majority_share_shuffle_utility.cc#L184)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I'd rather stick with Duration done manually and have a TODO to use TimeUtil once we can resolve the dependency issue.
</blockquote></details>

Oh wait sorry, the issue you're having is with the Duration header itself? Let me investigate.


<!-- Sent from Reviewable.io -->

2024-02-09 17:57 UTC, ple13 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1437)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @stevenwarejones)

___
*[`src/main/cc/wfa/measurement/internal/duchy/protocol/share_shuffle/honest_majority_share_shuffle_utility.cc` line 184 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1437#-NpfW_Ga-9xWQmHZwiJ8:-NqDzh5O7lTEj8YbImT_:b-pa8gur) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/26abf8269ae3753c46724546bdd1f4a09642bbbd/src/main/cc/wfa/measurement/internal/duchy/protocol/share_shuffle/honest_majority_share_shuffle_utility.cc#L184)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Oh wait sorry, the issue you're having is with the Duration header itself? Let me investigate.
</blockquote></details>

Yes, whenever I had `#include <google/protobuf/util/time_util.h>`, bazel complains that the protoc version is not compatible with `/usr/include/google/protobuf/timestamp.pb.h`


<!-- Sent from Reviewable.io -->

2024-02-09 18:25 UTC, SanjayVas requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1437)* status: all files reviewed, 1 unresolved discussion (waiting on @ple13 and @stevenwarejones)

___
*[`src/main/cc/wfa/measurement/internal/duchy/protocol/share_shuffle/honest_majority_share_shuffle_utility.cc` line 184 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1437#-NpfW_Ga-9xWQmHZwiJ8:-NqE0R6M9kvbVd5pnhQi:b2jj7mf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/26abf8269ae3753c46724546bdd1f4a09642bbbd/src/main/cc/wfa/measurement/internal/duchy/protocol/share_shuffle/honest_majority_share_shuffle_utility.cc#L184)):*
<details><summary><i>Previously, ple13 (Phi) wrote…</i></summary><blockquote>

Yes, whenever I had `#include <google/protobuf/util/time_util.h>`, bazel complains that the protoc version is not compatible with `/usr/include/google/protobuf/timestamp.pb.h`
</blockquote></details>

Hmm, I'm not having this problem when I test locally.

Steps:

1. Create a cc_proto_library target for duration_proto, having your library depend on it
    
    ```
    cc_proto_library(
        name = "duration_cc_proto",
        deps = ["@com_google_protobuf//:duration_proto"],
    )
    ```
2. Add another dep to `"@com_google_protobuf//:protobuf".
3. Add includes for duration and time util

    ```cc
    #include "google/protobuf/duration.pb.h"
    #include "google/protobuf/util/time_util.h"
    ```

I tested this out on liquid_legions_v2_encryption_utility.cc and was able to build without issue.


<!-- Sent from Reviewable.io -->

2024-02-09 19:46 UTC, ple13 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1437)* status: 19 of 22 files reviewed, 1 unresolved discussion (waiting on @kungfucraig, @renjiezh, @SanjayVas, and @stevenwarejones)

___
*[`src/main/cc/wfa/measurement/internal/duchy/protocol/share_shuffle/honest_majority_share_shuffle_utility.cc` line 184 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1437#-NpfW_Ga-9xWQmHZwiJ8:-NqEP3diDxjZiYEySNy4:b-4pvezj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/26abf8269ae3753c46724546bdd1f4a09642bbbd/src/main/cc/wfa/measurement/internal/duchy/protocol/share_shuffle/honest_majority_share_shuffle_utility.cc#L184)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Hmm, I'm not having this problem when I test locally.

Steps:

1. Create a cc_proto_library target for duration_proto, having your library depend on it
    
    ```
    cc_proto_library(
        name = "duration_cc_proto",
        deps = ["@com_google_protobuf//:duration_proto"],
    )
    ```
2. Add another dep to `"@com_google_protobuf//:protobuf".
3. Add includes for duration and time util

    ```cc
    #include "google/protobuf/duration.pb.h"
    #include "google/protobuf/util/time_util.h"
    ```

I tested this out on liquid_legions_v2_encryption_utility.cc and was able to build without issue.
</blockquote></details>

Thanks!! This worked!


<!-- Sent from Reviewable.io -->

2024-02-09 20:00 UTC, SanjayVas requested changes
> Reviewed 3 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1437)* status: all files reviewed, 2 unresolved discussions (waiting on @ple13 and @stevenwarejones)

___
*[`src/main/cc/wfa/measurement/internal/duchy/protocol/share_shuffle/BUILD.bazel` line 39 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1437#-NqERv8Q2D6PNSHi8SgU:-NqERv8Q2D6PNSHi8SgV:b-o576ts) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3a1d99ed5d81b27487855f1531e6602cd430f6a8/src/main/cc/wfa/measurement/internal/duchy/protocol/share_shuffle/BUILD.bazel#L39)):*
> ```Starlark
> )
> 
> cc_proto_library(
> ```

nit: put this under src/main/proto/google/protobuf instead
___
*[`src/main/cc/wfa/measurement/internal/duchy/protocol/share_shuffle/honest_majority_share_shuffle_utility.cc` line 186 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1437#-NqESAyr91XAzd1r3lqE:-NqESAyr91XAzd1r3lqF:bcq48os) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3a1d99ed5d81b27487855f1531e6602cd430f6a8/src/main/cc/wfa/measurement/internal/duchy/protocol/share_shuffle/honest_majority_share_shuffle_utility.cc#L186)):*
> ```cpp
>                                           combined_sketch.end());
>   *response.mutable_elapsed_cpu_duration() =
>       google::protobuf::util::TimeUtil::MicrosecondsToDuration(
> ```

Wrong unit



_Suggestion:_
```cpp
MillisecondsToDuration
```


<!-- Sent from Reviewable.io -->

2024-02-09 20:35 UTC, ple13 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1437)* status: 20 of 23 files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @stevenwarejones)

___
*[`src/main/cc/wfa/measurement/internal/duchy/protocol/share_shuffle/BUILD.bazel` line 39 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1437#-NqERv8Q2D6PNSHi8SgU:-NqE_8GW6kJf2SixJHjp:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3a1d99ed5d81b27487855f1531e6602cd430f6a8/src/main/cc/wfa/measurement/internal/duchy/protocol/share_shuffle/BUILD.bazel#L39)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: put this under src/main/proto/google/protobuf instead
</blockquote></details>

Done.
___
*[`src/main/cc/wfa/measurement/internal/duchy/protocol/share_shuffle/honest_majority_share_shuffle_utility.cc` line 186 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1437#-NqESAyr91XAzd1r3lqE:-NqEXe020fJsi_N4ziju:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3a1d99ed5d81b27487855f1531e6602cd430f6a8/src/main/cc/wfa/measurement/internal/duchy/protocol/share_shuffle/honest_majority_share_shuffle_utility.cc#L186)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Wrong unit
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-02-09 20:54 UTC, SanjayVas requested changes
> Reviewed 3 of 3 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1437)* status: all files reviewed, 1 unresolved discussion (waiting on @ple13 and @stevenwarejones)

___
*[`src/main/proto/google/protobuf/BUILD.bazel` line 1 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1437#-NqEdDnz1PmJYpdDwxpT:-NqEdDo--GSKtax76uFJ:bbmcwzy) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e5670e152547776807432c03d837feae8f7b06e9/src/main/proto/google/protobuf/BUILD.bazel#L1)):*
> ```Starlark
> load("@rules_cc//cc:defs.bzl", "cc_library")
> ```

You need to load cc_proto_library from rules_cc. The Bazel builtin rules are deprecated.


<!-- Sent from Reviewable.io -->

2024-02-09 21:03 UTC, ple13 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1437)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @stevenwarejones)

___
*[`src/main/proto/google/protobuf/BUILD.bazel` line 1 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1437#-NqEdDnz1PmJYpdDwxpT:-NqEfGBB6spvPTEPLCr5:b-it77k2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e5670e152547776807432c03d837feae8f7b06e9/src/main/proto/google/protobuf/BUILD.bazel#L1)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

You need to load cc_proto_library from rules_cc. The Bazel builtin rules are deprecated.
</blockquote></details>

I had that before, and that caused a lint error (saying that it's not needed).


<!-- Sent from Reviewable.io -->

2024-02-09 21:03 UTC, SanjayVas requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1437)* status: all files reviewed, 1 unresolved discussion (waiting on @ple13 and @stevenwarejones)

___
*[`src/main/proto/google/protobuf/BUILD.bazel` line 1 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1437#-NqEdDnz1PmJYpdDwxpT:-NqEfhZu-F2MyNQEqtxR:b-2ndyof) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e5670e152547776807432c03d837feae8f7b06e9/src/main/proto/google/protobuf/BUILD.bazel#L1)):*
<details><summary><i>Previously, ple13 (Phi) wrote…</i></summary><blockquote>

I had that before, and that caused a lint error (saying that it's not needed).
</blockquote></details>

What you had before was loading cc_library, not cc_proto_library


<!-- Sent from Reviewable.io -->

2024-02-09 21:07 UTC, ple13 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1437)* status: 22 of 23 files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @stevenwarejones)

___
*[`src/main/proto/google/protobuf/BUILD.bazel` line 1 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1437#-NqEdDnz1PmJYpdDwxpT:-NqEgJdB7iX4Qn5ELeip:bhr75o8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e5670e152547776807432c03d837feae8f7b06e9/src/main/proto/google/protobuf/BUILD.bazel#L1)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

What you had before was loading cc_library, not cc_proto_library
</blockquote></details>

Ah :(. I've fixed it.


<!-- Sent from Reviewable.io -->

2024-02-09 22:15 UTC, SanjayVas approved these changes
> Reviewed 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1437)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)



<!-- Sent from Reviewable.io -->

2024-02-12 21:56 UTC, stevenwarejones approved these changes
> Reviewed 1 of 4 files at r3, 18 of 20 files at r6, 1 of 3 files at r9, 2 of 3 files at r10, 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1437)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ple13)



<!-- Sent from Reviewable.io -->

2024-02-14 14:25 UTC, benjaminkreuter approved these changes

2024-02-14 17:55 UTC, merged