Fix wrong assignment in computeMetricVariance for Frequency
world-federation-of-advertisers/cross-media-measurement pull request #1464
Opened 2024-02-06 01:38 UTC by riemanli

2024-02-06 01:38 UTC, wfa-reviewable commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1464)
<!-- Reviewable:end -->

2024-02-06 01:38 UTC, riemanli commented
Current dependencies on/for this PR:
* `main`
  * **PR #1464** <a href="https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/1464?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/1464?utm_source=stack-comment).

2024-02-06 18:56 UTC, jiayu-google requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1464)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @chenweiw and @riemanli)

___
*[`src/test/kotlin/org/wfanet/measurement/measurementconsumer/stats/VariancesTest.kt` line 3354 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1464#-NpzlpxwBjbxW0mfBv_T:-NpzlpxwBjbxW0mfBv_U:byu494e) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fb6f13f32f702efadaf5aa671627eebb9a1fa360/src/test/kotlin/org/wfanet/measurement/measurementconsumer/stats/VariancesTest.kt#L3354)):*
> ```Kotlin
>     val maximumFrequency = 5
>     val relativeFrequencyDistribution =
>       (1..maximumFrequency).associateWith { (maximumFrequency - it) / 10.0 }
> ```

where is 10.0 from?


<!-- Sent from Reviewable.io -->

2024-02-06 19:15 UTC, chenweiw commented on src/test/kotlin/org/wfanet/measurement/measurementconsumer/stats/VariancesTest.kt
> +      (1..maximumFrequency).associateWith { (maximumFrequency - it) / 10.0 }
Line 3354: what does this line mean?

2024-02-06 19:20 UTC, chenweiw commented on src/test/kotlin/org/wfanet/measurement/measurementconsumer/stats/VariancesTest.kt
> +
I'm trying to understand the number of the four lists in line 3388--3409. Where do these expected values come from?

2024-02-06 19:22 UTC, chenweiw commented on src/main/kotlin/org/wfanet/measurement/measurementconsumer/stats/Variances.kt
> +        frequencyVariances.kPlusRelativeVariances.mapValues { coefficient * it.value },
So this addressed the issue that we discussed yesterday -- the stds of rk and rk+ estimations are always equal. Am I right?

2024-02-06 19:23 UTC, chenweiw reviewed
Hi Rieman, I just made a couple of minor comments.

2024-02-06 22:04 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1464)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @chenweiw and @jiayu-google)

___
*[`src/main/kotlin/org/wfanet/measurement/measurementconsumer/stats/Variances.kt` line 630 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1464#gh-1480431974:-Nq-QICN-EneTeMwmIho:blph1wa) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fb6f13f32f702efadaf5aa671627eebb9a1fa360/src/main/kotlin/org/wfanet/measurement/measurementconsumer/stats/Variances.kt#L630)):*
<details><summary><i>Previously, chenweiw wrote…</i></summary><blockquote>

So this addressed the issue that we discussed yesterday -- the stds of rk and rk+ estimations are always equal. Am I right?
</blockquote></details>

Yes. The fix here is using the correct field in `frequencyVariances`
___
*[`src/test/kotlin/org/wfanet/measurement/measurementconsumer/stats/VariancesTest.kt` line 3354 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1464#-NpzlpxwBjbxW0mfBv_T:-Nq-QlJVEusL92yMh4nv:b-swwfa) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fb6f13f32f702efadaf5aa671627eebb9a1fa360/src/test/kotlin/org/wfanet/measurement/measurementconsumer/stats/VariancesTest.kt#L3354)):*
<details><summary><i>Previously, jiayu-google wrote…</i></summary><blockquote>

where is 10.0 from?
</blockquote></details>

10.0 is the normalization term
___
*[`src/test/kotlin/org/wfanet/measurement/measurementconsumer/stats/VariancesTest.kt` line 3354 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1464#gh-1480423683:-Nq-QrBv9fThIYIixT7k:b-hbwqg6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fb6f13f32f702efadaf5aa671627eebb9a1fa360/src/test/kotlin/org/wfanet/measurement/measurementconsumer/stats/VariancesTest.kt#L3354)):*
<details><summary><i>Previously, chenweiw wrote…</i></summary><blockquote>

Line 3354: what does this line mean?
</blockquote></details>

It creates a frequency distribution of [(5 - 1) / 10, (5 - 2) / 10, (5 - 3) / 10, (5 - 4) / 10, (5 - 5) / 10] = [0.4, 0.3, 0.2, 0.1, 0]
___
*[`src/test/kotlin/org/wfanet/measurement/measurementconsumer/stats/VariancesTest.kt` line 3412 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1464#gh-1480429757:-Nq-RLNt0H8Bx-vzc49E:b6e0477) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fb6f13f32f702efadaf5aa671627eebb9a1fa360/src/test/kotlin/org/wfanet/measurement/measurementconsumer/stats/VariancesTest.kt#L3412)):*
<details><summary><i>Previously, chenweiw wrote…</i></summary><blockquote>

I'm trying to understand the number of the four lists in line 3388--3409. Where do these expected values come from?
</blockquote></details>

These values are generated from the Colab notebook you and Jiayu wrote. Basically, I use the notebook as a ground truth generator to ensure the code in prod works the same as the code in the Colab notebook.


<!-- Sent from Reviewable.io -->

2024-02-06 22:13 UTC, chenweiw approved these changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1464)* status: all files reviewed, 1 unresolved discussion (waiting on @jiayu-google)



<!-- Sent from Reviewable.io -->

2024-02-06 22:17 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1464)* status: all files reviewed, 1 unresolved discussion (waiting on @jiayu-google and @Marco-Premier)

___
*[`src/test/kotlin/org/wfanet/measurement/measurementconsumer/stats/VariancesTest.kt` line 3354 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1464#-NpzlpxwBjbxW0mfBv_T:-Nq-Uha46XNY3DaSvov3:b9p6sry) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fb6f13f32f702efadaf5aa671627eebb9a1fa360/src/test/kotlin/org/wfanet/measurement/measurementconsumer/stats/VariancesTest.kt#L3354)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

10.0 is the normalization term
</blockquote></details>

It creates a frequency distribution of \[(5 - 1) / 10, (5 - 2) / 10, (5 - 3) / 10, (5 - 4) / 10, (5 - 5) / 10\] = \[0.4, 0.3, 0.2, 0.1, 0\]


<!-- Sent from Reviewable.io -->

2024-02-08 18:11 UTC, Marco-Premier approved these changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1464)* status: all files reviewed, 1 unresolved discussion (waiting on @jiayu-google and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2024-02-08 23:03 UTC, stevenwarejones approved these changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1464)* status: all files reviewed, 1 unresolved discussion (waiting on @jiayu-google)



<!-- Sent from Reviewable.io -->

2024-02-12 05:55 UTC, riemanli reviewed
> Dismissed @jiayu-google from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1464)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jiayu-google)



<!-- Sent from Reviewable.io -->

2024-02-12 21:17 UTC, merged