Cherrypick: Standalone px decrypt (#1473)
world-federation-of-advertisers/cross-media-measurement pull request #1481
Opened 2024-02-15 20:09 UTC by jonmolle

Adds a tool for a standalone panel exchange private query decryption job.

2024-02-15 20:29 UTC, SanjayVas approved these changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1481)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)



<!-- Sent from Reviewable.io -->

2024-02-15 21:24 UTC, stevenwarejones requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1481)* status: all files reviewed, 1 unresolved discussion (waiting on @jonmolle)

___
*[`src/main/kotlin/org/wfanet/panelmatch/client/tools/BeamJobsMain.kt` line 28 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1481#-Nqie0au6vo9OvrIPU-c:-Nqie0au6vo9OvrIPU-d:b-3wzbdh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5dcef60fbdb0802d07149727105b9cb4e98a1f82/src/main/kotlin/org/wfanet/panelmatch/client/tools/BeamJobsMain.kt#L28)):*
> ```Kotlin
> import org.apache.beam.sdk.options.PipelineOptionsFactory
> import org.apache.beam.sdk.options.SdkHarnessOptions
> import org.wfanet.measurement.api.v2alpha.CanonicalExchangeStepAttemptKey
> ```

this didn't exist in 0.4


<!-- Sent from Reviewable.io -->

2024-02-16 13:28 UTC, stevenwarejones requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1481)* status: all files reviewed, 1 unresolved discussion (waiting on @jonmolle)

___
*[`src/main/kotlin/org/wfanet/panelmatch/client/tools/BeamJobsMain.kt` line 28 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1481#-Nqie0au6vo9OvrIPU-c:-Nqm5aSs8IfKMsofZs5F:bw7q1dt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5dcef60fbdb0802d07149727105b9cb4e98a1f82/src/main/kotlin/org/wfanet/panelmatch/client/tools/BeamJobsMain.kt#L28)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

this didn't exist in 0.4
</blockquote></details>

you'll need to use just `ExchangeDateKey` here instead.


<!-- Sent from Reviewable.io -->

2024-02-16 20:52 UTC, stevenwarejones approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1481)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @SanjayVas)



<!-- Sent from Reviewable.io -->

2024-02-16 20:54 UTC, SanjayVas approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1481)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jonmolle)



<!-- Sent from Reviewable.io -->

2024-02-16 20:56 UTC, jonmolle reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1481)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/panelmatch/client/tools/BeamJobsMain.kt` line 28 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1481#-Nqie0au6vo9OvrIPU-c:-NqngqzEClizLiS7H7xy:bcibfdd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5dcef60fbdb0802d07149727105b9cb4e98a1f82/src/main/kotlin/org/wfanet/panelmatch/client/tools/BeamJobsMain.kt#L28)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

you'll need to use just `ExchangeDateKey` here instead.
</blockquote></details>

Yeah, exchangestepattemptkey, but same idea


<!-- Sent from Reviewable.io -->

2024-02-16 21:24 UTC, stevenwarejones approved these changes
> Reviewed 1 of 2 files at r1, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1481)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jonmolle)



<!-- Sent from Reviewable.io -->

2024-02-26 19:01 UTC, stevenwarejones requested changes
i don't think this is needed any more.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1481#-:-Nramfkb5YAGIiD2jyFi:bgj9y2w)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jonmolle)



<!-- Sent from Reviewable.io -->

2026-05-07 18:09 UTC, closed without merging