Increase test timeout for K8s test workflow.
world-federation-of-advertisers/cross-media-measurement pull request #1505
Opened 2024-02-27 02:17 UTC by SanjayVas

When running against a test cloud environment, the sketch size and number of events means that R/F tests using LLv2 may take up to an hour.

2024-02-27 02:17 UTC, wfa-reviewable commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1505)
<!-- Reviewable:end -->

2024-02-27 15:33 UTC, stevenwarejones requested changes
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1505)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/measurementconsumer/MeasurementConsumerSimulator.kt` line 1048 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1505#-NrfBL7C2Xb0e7IsCVC8:-NrfBL7D7qDWIkF9kOmW:bur5z33) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d7876c0cb6a659114d5f796185acf78834d43ed6/src/main/kotlin/org/wfanet/measurement/loadtest/measurementconsumer/MeasurementConsumerSimulator.kt#L1048)):*
> ```Kotlin
>   private suspend inline fun <T> pollForResult(getResult: () -> T, done: (T) -> Boolean): T {
>     val backoff =
>       ExponentialBackoff(initialDelay = initialResultPollingDelay, randomnessFactor = 0.0)
> ```

do you want a lower multiplier? It might only be checking every 15 minutes by the time its done.


<!-- Sent from Reviewable.io -->

2024-02-27 18:11 UTC, SanjayVas reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1505)* status: 8 of 10 files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/measurementconsumer/MeasurementConsumerSimulator.kt` line 1048 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1505#-NrfBL7C2Xb0e7IsCVC8:-Nrfk1O48uZl9X7mdcSy:ba5ziqk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d7876c0cb6a659114d5f796185acf78834d43ed6/src/main/kotlin/org/wfanet/measurement/loadtest/measurementconsumer/MeasurementConsumerSimulator.kt#L1048)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

do you want a lower multiplier? It might only be checking every 15 minutes by the time its done.
</blockquote></details>

I added a cap instead.

The backoff is to balance the fact that some tests might be quite short, while others might take awhile and generate a lot of log spam.


<!-- Sent from Reviewable.io -->

2024-02-28 14:33 UTC, stevenwarejones approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1505)* status: 8 of 10 files reviewed, all discussions resolved

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/measurementconsumer/MeasurementConsumerSimulator.kt` line 1048 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1505#-NrfBL7C2Xb0e7IsCVC8:-Nrk7Z207-B3CBEkb1mn:b1w2afe) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d7876c0cb6a659114d5f796185acf78834d43ed6/src/main/kotlin/org/wfanet/measurement/loadtest/measurementconsumer/MeasurementConsumerSimulator.kt#L1048)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I added a cap instead.

The backoff is to balance the fact that some tests might be quite short, while others might take awhile and generate a lot of log spam.
</blockquote></details>

i agree. I like the cap just as well. The coerce could be added to the ExponentialBackoff as well.


<!-- Sent from Reviewable.io -->

2024-02-28 17:38 UTC, merged