Implement HonestMajorityShareShuffle mill
world-federation-of-advertisers/cross-media-measurement pull request #1506
Opened 2024-02-28 00:12 UTC by renjiezh

2024-02-28 00:12 UTC, wfa-reviewable commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1506)
<!-- Reviewable:end -->

2024-03-25 19:31 UTC, SanjayVas requested changes
> Reviewed 5 of 43 files at r1, 42 of 54 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1506)* status: 46 of 59 files reviewed, 9 unresolved discussions (waiting on @ple13 and @renjiezh)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/MillBase.kt` line 540 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1506#-NtqnD-U9Lbs_pHSRYbU:-NtqnD-U9Lbs_pHSRYbV:bx6dsh6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1ecbcff91b58580ee71e4ec2c6b8dcbf3ac6e070/src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/MillBase.kt#L540)):*
> ```Kotlin
>   }
> 
>   /** Send encrypted result of Computation to the Kingdom. */
> ```

This should live next to the other sendResultToKingdom overload
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/shareshuffle/BUILD.bazel` line 3 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1506#-NtqnlbWBoDEhWQNbfut:-NtqnlbWBoDEhWQNbfuu:b-dyo4gy) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1ecbcff91b58580ee71e4ec2c6b8dcbf3ac6e070/src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/shareshuffle/BUILD.bazel#L3)):*
> ```Starlark
> load("@wfa_rules_kotlin_jvm//kotlin:defs.bzl", "kt_jvm_library")
> 
> package(default_visibility = ["//visibility:public"])
> ```

Restrict visibility to where needed rather than using public.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/shareshuffle/HonestMajorityShareShuffleMill.kt` line 139 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1506#-NtqvBuFEwz01da0pNr6:-NtqvBuFEwz01da0pNr7:bsz29l5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1ecbcff91b58580ee71e4ec2c6b8dcbf3ac6e070/src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/shareshuffle/HonestMajorityShareShuffleMill.kt#L139)):*
> ```Kotlin
> 
>   private fun nextStage(token: ComputationToken): Stage {
>     require(token.computationDetails.hasHonestMajorityShareShuffle()) {
> ```

nit: this is a private function and it appears the only public entry point is `processComputationImpl`, which already has this check
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/shareshuffle/HonestMajorityShareShuffleMill.kt` line 146 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1506#-NtqutUC8t5SOBdsXeK2:-NtqutUC8t5SOBdsXeK3:b-al53k2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1ecbcff91b58580ee71e4ec2c6b8dcbf3ac6e070/src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/shareshuffle/HonestMajorityShareShuffleMill.kt#L146)):*
> ```Kotlin
>     val role = token.computationDetails.honestMajorityShareShuffle.role
> 
>     val nextStages =
> ```

This looks like it can be extracted to a constant.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/shareshuffle/HonestMajorityShareShuffleMill.kt` line 223 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1506#-NtqyoNR-RGTymMLoEuL:-NtqyoNR-RGTymMLoEuM:bycm68q) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1ecbcff91b58580ee71e4ec2c6b8dcbf3ac6e070/src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/shareshuffle/HonestMajorityShareShuffleMill.kt#L223)):*
> ```Kotlin
> 
>   private fun peerDuchyStub(participants: List<String>): ComputationControlCoroutineStub {
>     // The last participant is the aggregator.
> ```

Is there a reason that we don't just have two separate fields in `HonestMajorityShareShuffle.ComputationDetails`?
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/shareshuffle/HonestMajorityShareShuffleMill.kt` line 301 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1506#-NtqzjpY-beM67jFylbu:-NtqzjpY-beM67jFylbv:b-jfozx3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1ecbcff91b58580ee71e4ec2c6b8dcbf3ac6e070/src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/shareshuffle/HonestMajorityShareShuffleMill.kt#L301)):*
> ```Kotlin
>   }
> 
>   private fun combineRandomSeeds(seed1: ByteString, seed2: ByteString): ByteString {
> ```

This is just an XOR on ByteStrings. Write this as an infix `xor` operator in `common` with a TODO to move it to common-jvm. You can then write

```kotlin
val combinedSeed = seed1 xor seed2
```
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/shareshuffle/crypto/BUILD.bazel` line 6 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1506#-Ntr1opy4UMrVfGtN2Kr:-Ntr1opy4UMrVfGtN2Ks:undefined) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1ecbcff91b58580ee71e4ec2c6b8dcbf3ac6e070/src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/shareshuffle/crypto/BUILD.bazel#L6)):*
> ```Starlark
> 
> kt_jvm_library(
>     name = "honestmajorityshareshuffle",
> ```





_Suggestion:_
```Starlark
honest_majority_share_shuffle_cryptor
```
___
*[`src/main/proto/wfa/measurement/system/v1alpha/computation.proto` line 198 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1506#-Ntqx-F7EPtyijn6uDOH:-Ntqx-F80FzCFaQB6kXy:bluyrct) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/66edb76cb728adc7b0ab3354ef7eb8e506160e3a/src/main/proto/wfa/measurement/system/v1alpha/computation.proto#L198)):*
> ```proto
>       // Reach-only Liquid Legions v2 config.
>       //
>       // Must only be set when the measurement type is REACH.
> ```

Why drop the measurement type restriction comments? I believe I left this comment on a previous PR. 

I would expect every item in this oneof to have "May only be set when Measurement type..."
___
*[`src/main/proto/wfa/measurement/system/v1alpha/requisition.proto` line 81 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1506#-NtqxbWE1cfz83wWTRlw:-NtqxbWE1cfz83wWTRlx:biu8gun) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1ecbcff91b58580ee71e4ec2c6b8dcbf3ac6e070/src/main/proto/wfa/measurement/system/v1alpha/requisition.proto#L81)):*
> ```proto
>   // (-- api-linter: core::0141::forbidden-types=disabled
>   //     aip.dev/not-precedent: This is a random 64-bit value. --)
>   int64 nonce = 6 [(google.api.field_behavior) = OUTPUT_ONLY];
> ```

The nonce is a `fixed64` copied from the public API. I don't think you want to switch it to a different type here.


<!-- Sent from Reviewable.io -->

2024-03-25 23:59 UTC, renjiezh reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1506)* status: 41 of 59 files reviewed, 8 unresolved discussions (waiting on @ple13 and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/MillBase.kt` line 540 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1506#-NtqnD-U9Lbs_pHSRYbU:-Nts2U-A6myZOxuTqeIT:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1ecbcff91b58580ee71e4ec2c6b8dcbf3ac6e070/src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/MillBase.kt#L540)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This should live next to the other sendResultToKingdom overload
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/shareshuffle/BUILD.bazel` line 3 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1506#-NtqnlbWBoDEhWQNbfut:-Nts1w2k9KgoLgtDcuyh:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1ecbcff91b58580ee71e4ec2c6b8dcbf3ac6e070/src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/shareshuffle/BUILD.bazel#L3)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Restrict visibility to where needed rather than using public.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/shareshuffle/HonestMajorityShareShuffleMill.kt` line 146 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1506#-NtqutUC8t5SOBdsXeK2:-Nts1uw44qHf1njIgdkB:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1ecbcff91b58580ee71e4ec2c6b8dcbf3ac6e070/src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/shareshuffle/HonestMajorityShareShuffleMill.kt#L146)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This looks like it can be extracted to a constant.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/shareshuffle/HonestMajorityShareShuffleMill.kt` line 223 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1506#-NtqyoNR-RGTymMLoEuL:-Nts1wv32ppUn2aq_IiJ:bgt18jj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1ecbcff91b58580ee71e4ec2c6b8dcbf3ac6e070/src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/shareshuffle/HonestMajorityShareShuffleMill.kt#L223)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Is there a reason that we don't just have two separate fields in `HonestMajorityShareShuffle.ComputationDetails`?
</blockquote></details>

Good point. Let me see if there is better way to handle this.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/shareshuffle/HonestMajorityShareShuffleMill.kt` line 301 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1506#-NtqzjpY-beM67jFylbu:-Nts23OCDOQSg6s2jriw:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1ecbcff91b58580ee71e4ec2c6b8dcbf3ac6e070/src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/shareshuffle/HonestMajorityShareShuffleMill.kt#L301)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This is just an XOR on ByteStrings. Write this as an infix `xor` operator in `common` with a TODO to move it to common-jvm. You can then write

```kotlin
val combinedSeed = seed1 xor seed2
```
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/shareshuffle/crypto/BUILD.bazel` line 6 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1506#-Ntr1opy4UMrVfGtN2Kr:-Nts24ciCxBClbINAwR0:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1ecbcff91b58580ee71e4ec2c6b8dcbf3ac6e070/src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/shareshuffle/crypto/BUILD.bazel#L6)):*
> ```Starlark
> 
> kt_jvm_library(
>     name = "honestmajorityshareshuffle",
> ```

Done.
___
*[`src/main/proto/wfa/measurement/system/v1alpha/computation.proto` line 198 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1506#-Ntqx-F7EPtyijn6uDOH:-Nts28mB2e1zM5Bg4dY5:bs290mv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/66edb76cb728adc7b0ab3354ef7eb8e506160e3a/src/main/proto/wfa/measurement/system/v1alpha/computation.proto#L198)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Why drop the measurement type restriction comments? I believe I left this comment on a previous PR. 

I would expect every item in this oneof to have "May only be set when Measurement type..."
</blockquote></details>

Done.
Sorry. It is done by wrongly merging.
___
*[`src/main/proto/wfa/measurement/system/v1alpha/requisition.proto` line 81 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1506#-NtqxbWE1cfz83wWTRlw:-Nts2RnB05xZK8xJoPob:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1ecbcff91b58580ee71e4ec2c6b8dcbf3ac6e070/src/main/proto/wfa/measurement/system/v1alpha/requisition.proto#L81)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The nonce is a `fixed64` copied from the public API. I don't think you want to switch it to a different type here.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-03-25 23:59 UTC, renjiezh reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1506)* status: 41 of 59 files reviewed, 8 unresolved discussions (waiting on @ple13 and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/system/v1alpha/computation.proto` line 198 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1506#-Ntqx-F7EPtyijn6uDOH:-Nts2ZZABYhDgJ7t32YN:bb7qx2e) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/66edb76cb728adc7b0ab3354ef7eb8e506160e3a/src/main/proto/wfa/measurement/system/v1alpha/computation.proto#L198)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

Done.
Sorry. It is done by wrongly merging.
</blockquote></details>

was*


<!-- Sent from Reviewable.io -->

2024-03-26 00:47 UTC, SanjayVas requested changes
> Reviewed 2 of 54 files at r2, 3 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1506)* status: 46 of 59 files reviewed, 8 unresolved discussions (waiting on @ple13 and @renjiezh)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/shareshuffle/HonestMajorityShareShuffleMill.kt` line 301 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1506#-NtqzjpY-beM67jFylbu:-Nts3V0i88Wi_wESAIVj:b-thezkx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1ecbcff91b58580ee71e4ec2c6b8dcbf3ac6e070/src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/shareshuffle/HonestMajorityShareShuffleMill.kt#L301)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

Done.
</blockquote></details>

You didn't do the first part of this: moving it to `org.wfanet.measurement.common`in this repo and defining it as an infix operator. The TODO is just to get it over to common-jvm instead later.

```kotlin
package org.wfanet.measurement.common

infix fun xor(other: ByteString): ByteString {
  // ...
}
```
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/shareshuffle/HonestMajorityShareShuffleMill.kt` line 139 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1506#-Nts2yG89myJS7dGS-2B:-Nts2yG89myJS7dGS-2C:bgiu4t7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c0eb0655c635adc44cd031af66f15503f4bb5a59/src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/shareshuffle/HonestMajorityShareShuffleMill.kt#L139)):*
> ```Kotlin
>     )
> 
>   private val stageTransitions =
> ```

This can be a constant since it's immutable and does not depend on class state (i.e. defined as `STAGE_TRANSITIONS` in the companion object)
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/shareshuffle/HonestMajorityShareShuffleMill.kt` line 346 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1506#-NtsCads7XUSAfGhduvT:-NtsCadt80UzigZUWFvP:bqrjfft) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c0eb0655c635adc44cd031af66f15503f4bb5a59/src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/shareshuffle/HonestMajorityShareShuffleMill.kt#L346)):*
> ```Kotlin
>     try {
>       verifyRandomSeed(signedMessage, x509Certificate, trustedIssuer)
>     } catch (e: Exception) {
> ```

verifyRandomSeed documents which exception types it throws. Catch those.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/shareshuffle/HonestMajorityShareShuffleMill.kt` line 347 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1506#-NtsAWzVAql8YWmxWtbS:-NtsAWzVAql8YWmxWtbT:b5m2428) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c0eb0655c635adc44cd031af66f15503f4bb5a59/src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/shareshuffle/HonestMajorityShareShuffleMill.kt#L347)):*
> ```Kotlin
>       verifyRandomSeed(signedMessage, x509Certificate, trustedIssuer)
>     } catch (e: Exception) {
>       throw PermanentErrorException(e.message)
> ```

Pass the cause



_Suggestion:_
```Kotlin
PermanentErrorException(e.message, e)
```
___
*[`src/main/proto/wfa/measurement/internal/duchy/config/data_provider_cert_config.proto` line 23 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1506#-NtsD4_f1Ya9szQB0ggR:-NtsD4_f1Ya9szQB0ggS:b-6j6z3m) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c0eb0655c635adc44cd031af66f15503f4bb5a59/src/main/proto/wfa/measurement/internal/duchy/config/data_provider_cert_config.proto#L23)):*
> ```proto
> 
> // Data Provider certificate configuration.
> message DataProviderCertConfig {
> ```

Don't we have this info in Duchy config already by virtue of having the EDPs in the AKID mapping file?


<!-- Sent from Reviewable.io -->

2024-03-26 20:26 UTC, renjiezh reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1506)* status: 44 of 61 files reviewed, 8 unresolved discussions (waiting on @ple13 and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/shareshuffle/HonestMajorityShareShuffleMill.kt` line 301 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1506#-NtqzjpY-beM67jFylbu:-NtvuWymB6bCbuz21gTl:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1ecbcff91b58580ee71e4ec2c6b8dcbf3ac6e070/src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/shareshuffle/HonestMajorityShareShuffleMill.kt#L301)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

You didn't do the first part of this: moving it to `org.wfanet.measurement.common`in this repo and defining it as an infix operator. The TODO is just to get it over to common-jvm instead later.

```kotlin
package org.wfanet.measurement.common

infix fun xor(other: ByteString): ByteString {
  // ...
}
```
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/shareshuffle/HonestMajorityShareShuffleMill.kt` line 139 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1506#-Nts2yG89myJS7dGS-2B:-NtvuW-b-P0nzHCriZ6Y:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c0eb0655c635adc44cd031af66f15503f4bb5a59/src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/shareshuffle/HonestMajorityShareShuffleMill.kt#L139)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This can be a constant since it's immutable and does not depend on class state (i.e. defined as `STAGE_TRANSITIONS` in the companion object)
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/shareshuffle/HonestMajorityShareShuffleMill.kt` line 346 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1506#-NtsCads7XUSAfGhduvT:-NtvuXjd7ZTcwHujgRen:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c0eb0655c635adc44cd031af66f15503f4bb5a59/src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/shareshuffle/HonestMajorityShareShuffleMill.kt#L346)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

verifyRandomSeed documents which exception types it throws. Catch those.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/shareshuffle/HonestMajorityShareShuffleMill.kt` line 347 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1506#-NtsAWzVAql8YWmxWtbS:-NtwR2Yx85Mg7XFtkVAf:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c0eb0655c635adc44cd031af66f15503f4bb5a59/src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/shareshuffle/HonestMajorityShareShuffleMill.kt#L347)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Pass the cause
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/internal/duchy/config/data_provider_cert_config.proto` line 23 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1506#-NtsD4_f1Ya9szQB0ggR:-NtvunFmDqED5hbJkOK2:b-p95a8x) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c0eb0655c635adc44cd031af66f15503f4bb5a59/src/main/proto/wfa/measurement/internal/duchy/config/data_provider_cert_config.proto#L23)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Don't we have this info in Duchy config already by virtue of having the EDPs in the AKID mapping file?
</blockquote></details>

Removed. This file is outdated.


<!-- Sent from Reviewable.io -->

2024-03-26 21:31 UTC, renjiezh reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1506)* status: 44 of 61 files reviewed, 8 unresolved discussions (waiting on @ple13 and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/shareshuffle/HonestMajorityShareShuffleMill.kt` line 223 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1506#-NtqyoNR-RGTymMLoEuL:-NtweLRFBKlc1-4-_8Ee:b-du0x0u) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1ecbcff91b58580ee71e4ec2c6b8dcbf3ac6e070/src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/shareshuffle/HonestMajorityShareShuffleMill.kt#L223)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

Good point. Let me see if there is better way to handle this.
</blockquote></details>

After revisit the config and its usage, I realize that we don't even need the `participants` fields. And `workerStubs` can be a map from role to stub. I will update this in next PR adding config and binary.


<!-- Sent from Reviewable.io -->

2024-03-26 22:03 UTC, SanjayVas requested changes
> Reviewed 5 of 54 files at r2, 3 of 5 files at r5, 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1506)* status: 53 of 61 files reviewed, 7 unresolved discussions (waiting on @ple13 and @renjiezh)

___
*[`src/main/kotlin/org/wfanet/measurement/common/BitwiseOperations.kt` line 23 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1506#-Ntwkwgu4USs3AstJSEW:-Ntwkwgu4USs3AstJSEX:b8jwj95) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7ce9b8c8213288ca9a48429abaed6c41220d99a0/src/main/kotlin/org/wfanet/measurement/common/BitwiseOperations.kt#L23)):*
> ```Kotlin
> import kotlin.experimental.xor
> 
> object BitwiseOperations {
> ```

This shouldn't be declared inside of an object since it's an extension/operator.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/shareshuffle/HonestMajorityShareShuffleMill.kt` line 327 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1506#-NtwlPTT4H4wn3S9ELia:-NtwlPTT4H4wn3S9ELib:b-t5xp2f) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7ce9b8c8213288ca9a48429abaed6c41220d99a0/src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/shareshuffle/HonestMajorityShareShuffleMill.kt#L327)):*
> ```Kotlin
>     try {
>       verifyRandomSeed(signedMessage, x509Certificate, trustedIssuer)
>     } catch (e: Exception) {
> ```

Separate catches for the exception types rather than catching Exception and using `when`
___
*[`src/main/proto/wfa/measurement/internal/duchy/protocol/honest_majority_share_shuffle.proto` line 175 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1506#-NtwludxBF65V0JVWvJp:-NtwludxBF65V0JVWvJq:bgkd6es) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7ce9b8c8213288ca9a48429abaed6c41220d99a0/src/main/proto/wfa/measurement/internal/duchy/protocol/honest_majority_share_shuffle.proto#L175)):*
> ```proto
>     message SecretSeed {
>       // Corresponding external requisition id.
>       string requisition_id = 1;
> ```

If this is an external ID from the internal Duchy API, then call this external_requisition_id. If this is the ID segment of a Requisition from the CMMS public or system API, document it as such.



_Code quote:_
```proto
requisition_id
```
___
*[`src/main/proto/wfa/measurement/internal/duchy/protocol/honest_majority_share_shuffle.proto` line 184 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1506#-Ntwm9ooEkLGAFIsyrWR:-Ntwm9ooEkLGAFIsyrWS:b92lb79) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7ce9b8c8213288ca9a48429abaed6c41220d99a0/src/main/proto/wfa/measurement/internal/duchy/protocol/honest_majority_share_shuffle.proto#L184)):*
> ```proto
>       int64 register_count = 3;
> 
>       // Resource name of the `Certificate` belonging to the parent
> ```

Document which API this is a resource name from. Also, how do you know which API version?


<!-- Sent from Reviewable.io -->

2024-03-27 18:21 UTC, renjiezh reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1506)* status: 57 of 61 files reviewed, 6 unresolved discussions (waiting on @ple13 and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/common/BitwiseOperations.kt` line 23 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1506#-Ntwkwgu4USs3AstJSEW:-Nu08G06El8EFfynIYIr:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7ce9b8c8213288ca9a48429abaed6c41220d99a0/src/main/kotlin/org/wfanet/measurement/common/BitwiseOperations.kt#L23)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This shouldn't be declared inside of an object since it's an extension/operator.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/shareshuffle/HonestMajorityShareShuffleMill.kt` line 162 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1506#-Nu-dGlM2obPt3EY3rNq:-Nu07BluBESXMq7sKN2H:blcctid) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0ef90812c28a2b53d2ee712fdabfd760e4cbd127/src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/shareshuffle/HonestMajorityShareShuffleMill.kt#L162)):*
<details><summary><i>Previously, ple13 (Phi) wrote…</i></summary><blockquote>

Do we only set the participant params here?
</blockquote></details>

Sorry I might not get your point. This function calls the system api setParticipantRequisitionParams to the kingdom.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/shareshuffle/HonestMajorityShareShuffleMill.kt` line 265 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1506#-Nu-lEinCQZgbiTYsIEh:-Nu07X0UDqRWCNJV_lPp:bocde4n) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7ce9b8c8213288ca9a48429abaed6c41220d99a0/src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/shareshuffle/HonestMajorityShareShuffleMill.kt#L265)):*
<details><summary><i>Previously, ple13 (Phi) wrote…</i></summary><blockquote>

Do we now send the seeds in the body chunk instead of the header?
</blockquote></details>

Yes.
For both ShufflePhaseInput (from setupPhase) and AggregationPhaseInput(from shufflePhase), all the data are serialized into the body chunks.
On the contrast, for requisition fulfillment, the seed is in the header. The is to make it easier to parse the seed by requisition fulfillment service. 
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/shareshuffle/HonestMajorityShareShuffleMill.kt` line 327 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1506#-NtwlPTT4H4wn3S9ELia:-Nu08J87EZ7lpJzfGOKQ:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7ce9b8c8213288ca9a48429abaed6c41220d99a0/src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/shareshuffle/HonestMajorityShareShuffleMill.kt#L327)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Separate catches for the exception types rather than catching Exception and using `when`
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/internal/duchy/protocol/honest_majority_share_shuffle.proto` line 175 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1506#-NtwludxBF65V0JVWvJp:-Nu06gfj0JOZw0gSJBWI:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7ce9b8c8213288ca9a48429abaed6c41220d99a0/src/main/proto/wfa/measurement/internal/duchy/protocol/honest_majority_share_shuffle.proto#L175)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

If this is an external ID from the internal Duchy API, then call this external_requisition_id. If this is the ID segment of a Requisition from the CMMS public or system API, document it as such.
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/internal/duchy/protocol/honest_majority_share_shuffle.proto` line 184 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1506#-Ntwm9ooEkLGAFIsyrWR:-Nu06hWt87eHypDA_vaG:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7ce9b8c8213288ca9a48429abaed6c41220d99a0/src/main/proto/wfa/measurement/internal/duchy/protocol/honest_majority_share_shuffle.proto#L184)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Document which API this is a resource name from. Also, how do you know which API version?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-03-27 19:18 UTC, ple13 approved these changes
> Reviewed 1 of 2 files at r3, 2 of 2 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1506)* status: all files reviewed, 4 unresolved discussions (waiting on @SanjayVas)



<!-- Sent from Reviewable.io -->

2024-03-27 20:00 UTC, SanjayVas requested changes
> Reviewed 2 of 2 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1506)* status: all files reviewed, 1 unresolved discussion (waiting on @renjiezh)

___
*[`src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/shareshuffle/HonestMajorityShareShuffleMillTest.kt` line 359 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1506#-Nu0Up0y3XATTzgC096-:-Nu0Up0y3XATTzgC0960:bhzd8e6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c692f3aa3c8efa9b9a3803481b422d568ff23b7c/src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/shareshuffle/HonestMajorityShareShuffleMillTest.kt#L359)):*
> ```Kotlin
>     val trustedCertificates = duchyCertificates + dataProviderCertificates
> 
>     firstWorkerMill =
> ```

Can we not do this test with a single Mill instance? We can extract out functions for initializing the Mill if we need different configurations for different test methods.


<!-- Sent from Reviewable.io -->

2024-03-27 23:54 UTC, renjiezh reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1506)* status: 60 of 61 files reviewed, 1 unresolved discussion (waiting on @ple13 and @SanjayVas)

___
*[`src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/shareshuffle/HonestMajorityShareShuffleMillTest.kt` line 359 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1506#-Nu0Up0y3XATTzgC096-:-Nu1KaBXEtjDm3T7_JPB:b-jut9d5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c692f3aa3c8efa9b9a3803481b422d568ff23b7c/src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/shareshuffle/HonestMajorityShareShuffleMillTest.kt#L359)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Can we not do this test with a single Mill instance? We can extract out functions for initializing the Mill if we need different configurations for different test methods.
</blockquote></details>

Done.
Good idea.


<!-- Sent from Reviewable.io -->

2024-03-28 00:15 UTC, SanjayVas approved these changes
> Reviewed 1 of 43 files at r1, 2 of 54 files at r2, 3 of 7 files at r4, 1 of 5 files at r5, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1506)* status: all files reviewed, 1 unresolved discussion (waiting on @renjiezh)

___
*[`src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/shareshuffle/HonestMajorityShareShuffleMillTest.kt` line 342 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1506#-Nu1OK9Z3m2YqikTGbLq:-Nu1OK9_5DI_sWeVkD57:b-wktogb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/afc4972806f6d4d5c85909d7468d827e96658943/src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/shareshuffle/HonestMajorityShareShuffleMillTest.kt#L342)):*
> ```Kotlin
> 
>   private fun createHmssMill(duchyName: String): HonestMajorityShareShuffleMill {
>     DuchyInfo.setForTest(setOf(DUCHY_ONE_NAME, DUCHY_TWO_NAME, DUCHY_THREE_NAME))
> ```

nit: this can probably be in its own `@Before` method


<!-- Sent from Reviewable.io -->

2024-04-02 21:02 UTC, stevenwarejones approved these changes
> Reviewed 5 of 43 files at r1, 43 of 54 files at r2, 5 of 7 files at r4, 3 of 5 files at r5, 2 of 2 files at r8, 1 of 1 files at r9, 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1506)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Marco-Premier)



<!-- Sent from Reviewable.io -->

2024-04-04 06:19 UTC, renjiezh reviewed
> Reviewed 4 of 43 files at r1, 41 of 54 files at r2, 5 of 7 files at r4, 3 of 5 files at r5, 2 of 2 files at r8, 1 of 1 files at r9, 2 of 2 files at r11, 3 of 3 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1506)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Marco-Premier)



<!-- Sent from Reviewable.io -->

2024-04-04 06:19 UTC, merged