Add the function to generate hmss sketch.
world-federation-of-advertisers/cross-media-measurement pull request #1509
Opened 2024-02-28 18:39 UTC by ple13

2024-02-28 19:08 UTC, SanjayVas requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509)* status: 0 of 2 files reviewed, 13 unresolved discussions (waiting on @kungfucraig, @ple13, and @renjiezh)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 205 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509#-Nrl4Q8mDg_siuQpfct7:-Nrl4Q8mDg_siuQpfct8:b-ijaoen) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4316c15610a85bc281ab0de58ed3e838004e7ed1/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L205)):*
> ```Kotlin
>    * Generates the hash of (vid + salt)
>    */
>   fun generateHash(vid: Int, salt: ByteString): String {
> ```

Shouldn't VIDs be `Long`s (64-bit integer) not `Int` (32-bit integer)?



_Code quote:_
```Kotlin
Int
```
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 205 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509#-Nrl6DFe5CfUTF6Lv1PS:-Nrl6DFe5CfUTF6Lv1PT:b-1n5x9k) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4316c15610a85bc281ab0de58ed3e838004e7ed1/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L205)):*
> ```Kotlin
>    * Generates the hash of (vid + salt)
>    */
>   fun generateHash(vid: Int, salt: ByteString): String {
> ```

This should be private.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 206 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509#-Nrl4quyCaOnp9RWIDwz:-Nrl4quzBHcwI_voRB7C:brrcceh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4316c15610a85bc281ab0de58ed3e838004e7ed1/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L206)):*
> ```Kotlin
>    */
>   fun generateHash(vid: Int, salt: ByteString): String {
>     val hashInput = ByteString.copyFromUtf8(vid.toString()).concat(salt)
> ```

Do you really want to use the UTF8-encoded value of the number as a string instead of the binary encoding of the number?



_Suggestion:_
```Kotlin
vid.toByteString(ByteOrder.BIG_ENDIAN).concat(salt)
```
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 207 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509#-Nrl5rSX08JZ3aBmb2jv:-Nrl5rSYC-8_7dJ2IYJo:bno235i) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4316c15610a85bc281ab0de58ed3e838004e7ed1/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L207)):*
> ```Kotlin
>   fun generateHash(vid: Int, salt: ByteString): String {
>     val hashInput = ByteString.copyFromUtf8(vid.toString()).concat(salt)
>     return HexString(Hashing.hashSha256(hashInput)).toString()
> ```

Why not use the ByteString? Meaning what is the purpose of converting this to a String of hex digits?



_Code quote:_
```Kotlin
HexString(Hashing.hashSha256(hashInput)).toString()
```
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 216 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509#-Nrl6EfoEAVb85AA5iNH:-Nrl6EfoEAVb85AA5iNI:b-1n5x9k) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4316c15610a85bc281ab0de58ed3e838004e7ed1/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L216)):*
> ```Kotlin
>    * sorted array.
>    */
>   fun generateVidMap(
> ```

This should be private.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 528 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509#-Nrl2uzgDgyAa2ZLbqmZ:-Nrl2uzgDgyAa2ZLbqm_:b5ayf91) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4316c15610a85bc281ab0de58ed3e838004e7ed1/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L528)):*
> ```Kotlin
>             trustedIssuer,
>           )
> ```

Why are whitespace changes being introduced for all these `when` blocks?
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 1029 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509#-Nrl4D8Y4RAp1iXpBi2x:-Nrl4D8Z2WcuKN3WCx0G:bhutiwu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4316c15610a85bc281ab0de58ed3e838004e7ed1/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L1029)):*
> ```Kotlin
>   }
> 
>   private fun IsInSelectedIntervals(
> ```

lowerCamelCase for function names. See https://developer.android.com/kotlin/style-guide



_Code quote:_
```Kotlin
IsInSelectedIntervals
```
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 1031 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509#-Nrl3xqy0vfIPxp3U-gP:-Nrl3xqy0vfIPxp3U-gQ:b4c7zcc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4316c15610a85bc281ab0de58ed3e838004e7ed1/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L1031)):*
> ```Kotlin
>   private fun IsInSelectedIntervals(
>     index: Long,
>     intervals: List<Pair<Int, Int>>,
> ```

I'm assuming these are meant to be ranges? Use Kotlin's IntRange or LongRange type to represent a closed range. See https://kotlinlang.org/docs/ranges.html. In general, avoid Pair when there's a more suitable type.

If you use `List<LongRange>`, then you can rewrite this as just

```kotlin
intervals.any { index in it }
```



_Code quote:_
```Kotlin
intervals: List<Pair<Int, Int>>,
```
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 1041 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509#-Nrl6Gun6807L5K6KbQe:-Nrl6Gun6807L5K6KbQf:b-1n5x9k) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4316c15610a85bc281ab0de58ed3e838004e7ed1/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L1041)):*
> ```Kotlin
>   }
> 
>   fun generateHmssSketch(
> ```

This should be private.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 1042 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509#-Nrl2UxF3rHehHy1iLB7:-Nrl2UxF3rHehHy1iLB8:b-8kube3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4316c15610a85bc281ab0de58ed3e838004e7ed1/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L1042)):*
> ```Kotlin
> 
>   fun generateHmssSketch(
>     vidUniverseSize: Int,
> ```

Shouldn't this be a `Long` (64-bit integer)?



_Code quote:_
```Kotlin
Int
```
___
*[`src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt` line 2517 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509#-Nrl6JZy2aduRt0wKkg1:-Nrl6JZy2aduRt0wKkg2:b-pps92j) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4316c15610a85bc281ab0de58ed3e838004e7ed1/src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt#L2517)):*
> ```Kotlin
> 
>   @Test
>   fun `the function generateHash works properly`() {
> ```

This should be a private implementation detail function, and therefore not tested directly.
___
*[`src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt` line 2545 at r1](https://reviewable.io/rev [...]

2024-03-04 14:23 UTC, kungfucraig requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509)* status: 0 of 2 files reviewed, 17 unresolved discussions (waiting on @ple13, @renjiezh, and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 205 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509#-Nrl4Q8mDg_siuQpfct7:-Ns8kqwt1DreVUxbDa9w:b32v57) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4316c15610a85bc281ab0de58ed3e838004e7ed1/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L205)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Shouldn't VIDs be `Long`s (64-bit integer) not `Int` (32-bit integer)?
</blockquote></details>

+1
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 216 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509#-Nrl6EfoEAVb85AA5iNH:-Ns8l7nA2lxvag0C_I0P:bpq5a8q) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4316c15610a85bc281ab0de58ed3e838004e7ed1/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L216)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This should be private.
</blockquote></details>

I think we want this function in the any sketch library as well as the hashing function.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 217 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509#-Ns8q6AuAtd6w1ZcrfFQ:-Ns8q6AuAtd6w1ZcrfFR:bflrbwq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4316c15610a85bc281ab0de58ed3e838004e7ed1/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L217)):*
> ```Kotlin
>    */
>   fun generateVidMap(
>     salt: ByteString,
> ```

We can keep the salt parameter, but I'd expect it to be an empty string in practice.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 218 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509#-Ns8lJwQ1A66tYGDVqdc:-Ns8lJwQ1A66tYGDVqdd:b-qy3jfs) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4316c15610a85bc281ab0de58ed3e838004e7ed1/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L218)):*
> ```Kotlin
>   fun generateVidMap(
>     salt: ByteString,
>     minVid: Int,
> ```

You should not assume that VIDs have a continuous range.

Can you operate on the proto defined herein: https://docs.google.com/document/d/1TwzhtRmRqD8Fu_ziamG8kuIDQ4h4g3AMeKVUT4ilkM4/edit?tab=t.0

The proto in this doc has not been merged, but you could add it. I think it should live near the VID model repo, but will defer to @SanjayVas on that part. Joji may be adding it for his work soon, so you may want to sync with him as well.


For the synthetic event specs you might want to transform the synthetic population into the proto lined above. 
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 1041 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509#-Nrl6Gun6807L5K6KbQe:-Ns8mc126Cq7fQe7pDoU:b-s0v829) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4316c15610a85bc281ab0de58ed3e838004e7ed1/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L1041)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This should be private.
</blockquote></details>

Put it in any sketch too?
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 1050 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509#-Ns8mo5v2pBuxvew_83b:-Ns8mkLZDPIp8y89A4eY:biflmc0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4316c15610a85bc281ab0de58ed3e838004e7ed1/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L1050)):*
> ```Kotlin
> 
>     logger.info("Generating HMSS Sketch...")
>     val vidMap = generateVidMap(salt, 0, vidUniverseSize - 1)
> ```

Cache the map?

Assuming this works on the synthetic event groups I think you need to process the corresponding population.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 1052 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509#-Ns8nCcy1FAy25NiSMYC:-Ns8nCcy1FAy25NiSMYD:b-2zxyyy) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4316c15610a85bc281ab0de58ed3e838004e7ed1/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L1052)):*
> ```Kotlin
>     val vidMap = generateVidMap(salt, 0, vidUniverseSize - 1)
> 
>     val sketchSize: Int = (measurementSpec.vidSamplingInterval.width * vidUniverseSize).toInt()
> ```

In general this may not provide the right size array. You may need to find the number of vids in the sampling interval and size the array accordingly. 

The VIDs should be uniformly allocated, but I think there are lots of opportunities for "off by one" (e.g. this will take the floor of the number in parens).


If you maintain a sorted list of VIDs with their normalized hash value then two binary searches would get you what you need, the index of start and the index of end.

Wdyt?


<!-- Sent from Reviewable.io -->

2024-03-05 19:27 UTC, renjiezh reviewed
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509)* status: 0 of 2 files reviewed, 17 unresolved discussions (waiting on @ple13, @renjiezh, and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 213 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509#-NsEnJs9CxmhM4ILq6F-:-NsEnJs9CxmhM4ILq6F0:bxeulcy) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4316c15610a85bc281ab0de58ed3e838004e7ed1/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L213)):*
> ```Kotlin
>    * Generates the map (vid, bucket index) for vid in the range [minVid, maxVid].
>    * Each vid is concatenated with a `salt`, then the sha256 of the combined string is computed.
>    * The vid's are sorted based on its hash value. The bucket index of a vid is its located in the
> ```

typo `location`


<!-- Sent from Reviewable.io -->

2024-03-12 23:05 UTC, ple13 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509)* status: 0 of 8 files reviewed, 17 unresolved discussions (waiting on @kungfucraig and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 205 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509#-Nrl4Q8mDg_siuQpfct7:-NsoTJyT9UF_Osz9iS-t:b-wik2r1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4316c15610a85bc281ab0de58ed3e838004e7ed1/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L205)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Updated. vid now has type Long.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 205 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509#-Nrl6DFe5CfUTF6Lv1PS:-NsoTTBq6YYNlWqmrYLd:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4316c15610a85bc281ab0de58ed3e838004e7ed1/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L205)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This should be private.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 206 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509#-Nrl4quyCaOnp9RWIDwz:-NsoTUPO0Lj2bfSG7M6c:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4316c15610a85bc281ab0de58ed3e838004e7ed1/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L206)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Do you really want to use the UTF8-encoded value of the number as a string instead of the binary encoding of the number?
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 207 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509#-Nrl5rSX08JZ3aBmb2jv:-NsoTXK1-Xg9tycxO03P:b-3i8ri9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4316c15610a85bc281ab0de58ed3e838004e7ed1/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L207)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Why not use the ByteString? Meaning what is the purpose of converting this to a String of hex digits?
</blockquote></details>

I wanted to convert it to BigInteger later. And the conversion takes a string as input.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 216 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509#-Nrl6EfoEAVb85AA5iNH:-NsoTzf-2X9SpPg3pqjF:byezwi) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4316c15610a85bc281ab0de58ed3e838004e7ed1/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L216)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

I think we want this function in the any sketch library as well as the hashing function.
</blockquote></details>

I've created an object for the vid map generator. I will move this to any-sketch later.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 217 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509#-Ns8q6AuAtd6w1ZcrfFQ:-NsoUBOwEOo7vbdG4Drx:bwygxsx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4316c15610a85bc281ab0de58ed3e838004e7ed1/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L217)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

We can keep the salt parameter, but I'd expect it to be an empty string in practice.
</blockquote></details>

Noted.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 218 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509#-Ns8lJwQ1A66tYGDVqdc:-NsoUDZsCKYk_xIyaDgG:b-1p1gbg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4316c15610a85bc281ab0de58ed3e838004e7ed1/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L218)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

You should not assume that VIDs have a continuous range.

Can you operate on the proto defined herein: https://docs.google.com/document/d/1TwzhtRmRqD8Fu_ziamG8kuIDQ4h4g3AMeKVUT4ilkM4/edit?tab=t.0

The proto in this doc has not been merged, but you could add it. I think it should live near the VID model repo, but will defer to @SanjayVas on that part. Joji may be adding it for his work soon, so you may want to sync with him as well.


For the synthetic event specs you might want to transform the synthetic population into the proto lined above.
</blockquote></details>

Done. The vid range is replaced with List<Long>.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 528 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509#-Nrl2uzgDgyAa2ZLbqmZ:-NsoUK2TAIAuQw9caq1y:b-gtau3b) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4316c15610a85bc281ab0de58ed3e838004e7ed1/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L528)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Why are whitespace changes being introduced for all these `when` blocks?
</blockquote></details>

The Intellj I used produced the wrong format..
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 1029 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509#-Nrl4D8Y4RAp1iXpBi2x:-NsoUWF62hy5dI8jEdJO:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4316c15610a85bc281ab0de58ed3e838004e7ed1/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L1029)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

lowerCamelCase for function names. See https://developer.android.com/kotlin/style-guide
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 1031 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509#-Nrl3xqy0vfIPxp3U-gP:-NsoWJg69p3ik1gpmA_l:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4316c15610a85bc281ab0de58ed3e838004e7ed1/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L1031)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I'm assuming these are meant to be ranges? Use Kotlin's IntRange or LongRange type to represent a closed range. See https://kotlinlang.org/docs/ranges.html. In general, avoid Pair when there's a more suitable type.

If you use `List<LongRange>`, then you can rewrite this as just

```kotlin
intervals.any { index in it }
```
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 1041 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/c [...]

2024-03-13 17:08 UTC, SanjayVas requested changes
> Reviewed 3 of 8 files at r2, 2 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509)* status: 5 of 8 files reviewed, 15 unresolved discussions (waiting on @kungfucraig and @ple13)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 207 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509#-Nrl5rSX08JZ3aBmb2jv:-Nssik5r6I-uRc4p7zo2:b-1agr8s) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4316c15610a85bc281ab0de58ed3e838004e7ed1/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L207)):*
<details><summary><i>Previously, ple13 (Phi) wrote…</i></summary><blockquote>

I wanted to convert it to BigInteger later. And the conversion takes a string as input.
</blockquote></details>

The string that BigInteger expects is a string representation of an integer, e.g. "1234". BigInteger also has a constructor that takes a byte array containing a two's complement binary representation in big-endian byte order[^1]. This is what you'd actually want to call.

[^1]: https://docs.oracle.com/javase/8/docs/api/java/math/BigInteger.html#BigInteger-byte:A-
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 528 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509#-Nrl2uzgDgyAa2ZLbqmZ:-NssjQoNB25rRQ0hNvu8:bnrk10d) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4316c15610a85bc281ab0de58ed3e838004e7ed1/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L528)):*
<details><summary><i>Previously, ple13 (Phi) wrote…</i></summary><blockquote>

The Intellj I used produced the wrong format..
</blockquote></details>

It was probably not configured correctly. We use ktfmt[^1]. To get IntelliJ to format correctly, you'll need to install the ktfmt plugin and configure it to use Google style.

[^1]: https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/docs/code-style.md#kotlin-1
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/ShareShuffleSketchGenerator.kt` line 30 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509#-NsskX8j028sgo-RG5Pb:-NsskX8j028sgo-RG5Pc:b-jhdsyw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8b3437b1b718ae9c16b15b21f73e9c025699beaf/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/ShareShuffleSketchGenerator.kt#L30)):*
> ```Kotlin
> ) {
> 
>   /** Generates a [Sketch] for the specified [eventGroupSpecs]. */
> ```

This does not generate a `Sketch` object



_Code quote:_
```Kotlin
[Sketch]
```
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/ShareShuffleSketchGenerator.kt` line 100 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509#-Nsskkew7qdGEa4YAEXE:-Nsskkew7qdGEa4YAEXF:undefined) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8b3437b1b718ae9c16b15b21f73e9c025699beaf/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/ShareShuffleSketchGenerator.kt#L100)):*
> ```Kotlin
>    */
>   private fun lowerBound(sortedList: List<Double>, target: Double): Int {
>     require(sortedList.size > 0) { "Input list cannot be empty." }
> ```





_Suggestion:_
```Kotlin
sortedList.isNotEmpty()
```
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/VidToIndexMapGenerator.kt` line 26 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509#-Nssl6sd5hUBIzc2JBBv:-Nssl6sd5hUBIzc2JBBw:b-jheoew) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8b3437b1b718ae9c16b15b21f73e9c025699beaf/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/VidToIndexMapGenerator.kt#L26)):*
> ```Kotlin
> import org.wfanet.measurement.common.toByteString
> 
> object VidToIndexMapGenerator {
> ```

This seems like an implementation detail of HMSS sketch generation to me. Unless it would be used anywhere else, this should probably be private functionality of that class and not be tested directly. See https://testing.googleblog.com/2015/01/testing-on-toilet-prefer-testing-public.html
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/VidToIndexMapGenerator.kt` line 34 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509#-Nssht8BDFKxv9ioH0eC:-Nssht8BDFKxv9ioH0eD:bvtl27x) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8b3437b1b718ae9c16b15b21f73e9c025699beaf/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/VidToIndexMapGenerator.kt#L34)):*
> ```Kotlin
> 
>   /**
>    * Generates the map (vid, (bucket index, normalized hash)) for all vids in the vid universe. Each
> ```

nit: format this according to https://developer.android.com/kotlin/style-guide#documentation

In particular, a summary fragment followed by optional detail paragraphs
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/VidToIndexMapGenerator.kt` line 39 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509#-NssiGmfAfmfljHPi3ts:-NssiGmfAfmfljHPi3tt:b-c1ts2d) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8b3437b1b718ae9c16b15b21f73e9c025699beaf/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/VidToIndexMapGenerator.kt#L39)):*
> ```Kotlin
>    * sorted array.
>    */
>   fun generateMapping(salt: ByteString, vidUniverse: List<Long>): Map<Long, Pair<Int, Double>> {
> ```

Avoid Pair. Create your own data class instead.



_Code quote:_
```Kotlin
Pair<Int, Double>
```
___
*[`src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/ShareShuffleSketchGeneratorTest.kt` line 55 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509#-Nssm8MO2L5HzgO2d2rR:-Nssm8MPC1TjYs1pPabb:b-fj8vlo) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8b3437b1b718ae9c16b15b21f73e9c025699beaf/src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/ShareShuffleSketchGeneratorTest.kt#L55)):*
> ```Kotlin
> class ShareShuffleSketchGeneratorTest {
>   @Test
>   fun `vid sampling interval in the middle of the unit interval and contains no vid fails`() {
> ```

nit: test method names should actually describe what is being verified rather than just stating "succeeds" and "fails" (this is an antipattern that needs to be cleaned up in a lot of our tests). You generally also want to reference the method under test.

e.g. "generate throws IllegalArgumentException when ..."



_Code quote:_
```Kotlin
fails
```


<!-- Sent from Reviewable.io -->

2024-03-14 15:59 UTC, kungfucraig requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509)* status: 5 of 8 files reviewed, 18 unresolved discussions (waiting on @ple13 and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 987 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509#-NsxceEL4r6rpUTDZTdn:-NsxceEL4r6rpUTDZTdo:br51ews) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8b3437b1b718ae9c16b15b21f73e9c025699beaf/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L987)):*
> ```Kotlin
>   }
> 
>   private fun generateShareShuffleSketch(
> ```

Where is this called from?
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/ShareShuffleSketchGenerator.kt` line 34 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509#-NsxcL093JiHAmDhw6Qf:-NsxcL093JiHAmDhw6Qg:b-qno3k8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8b3437b1b718ae9c16b15b21f73e9c025699beaf/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/ShareShuffleSketchGenerator.kt#L34)):*
> ```Kotlin
>     require(vidUniverse.size > 0) { "The vid universe size must be positive." }
> 
>     val vidToIndexMap = VidToIndexMapGenerator.generateMapping(salt, vidUniverse)
> ```

You could initialize this during construction and retain it.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/ShareShuffleSketchGenerator.kt` line 35 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509#-NsxczJG9CcfNUjKTlXF:-NsxczJG9CcfNUjKTlXG:b4se98r) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8b3437b1b718ae9c16b15b21f73e9c025699beaf/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/ShareShuffleSketchGenerator.kt#L35)):*
> ```Kotlin
> 
>     val vidToIndexMap = VidToIndexMapGenerator.generateMapping(salt, vidUniverse)
>     val sortedNormalizedHashValues = vidToIndexMap.values.toList().map { it.second }
> ```

Same here re: initialize.

What is causing the list to be sorted? 
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/ShareShuffleSketchGenerator.kt` line 42 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509#-NsxdRCC8cY068BcdJe1:-NsxdRCC8cY068BcdJe2:b-ppgk95) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8b3437b1b718ae9c16b15b21f73e9c025699beaf/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/ShareShuffleSketchGenerator.kt#L42)):*
> ```Kotlin
>     val isWrappedAround = (samplingIntervalEnd > 1.0)
> 
>     if (samplingIntervalEnd > 1.0) {
> ```

if ( isWrappedAround)
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/ShareShuffleSketchGenerator.kt` line 53 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509#-NsxdkGFDUvA3sLseKBW:-NsxdkGFDUvA3sLseKBX:bhyuc3d) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8b3437b1b718ae9c16b15b21f73e9c025699beaf/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/ShareShuffleSketchGenerator.kt#L53)):*
> ```Kotlin
> 
>     if (!isWrappedAround) {
>       if (start <= end) {
> ```

!isWrappedAround implies start <= end, doesn't it? 

Also I don't see a matching else here, and falling through would trigger the assertion below.


<!-- Sent from Reviewable.io -->

2024-03-14 22:04 UTC, kungfucraig requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509)* status: 5 of 8 files reviewed, 20 unresolved discussions (waiting on @ple13 and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/VidToIndexMapGenerator.kt` line 26 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509#-Nssl6sd5hUBIzc2JBBv:-NsxqjSDC6_xMTMkPEiw:b-2v1yfi) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8b3437b1b718ae9c16b15b21f73e9c025699beaf/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/VidToIndexMapGenerator.kt#L26)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This seems like an implementation detail of HMSS sketch generation to me. Unless it would be used anywhere else, this should probably be private functionality of that class and not be tested directly. See https://testing.googleblog.com/2015/01/testing-on-toilet-prefer-testing-public.html
</blockquote></details>

It's complicated in it's own right and needs to be tested independently. Mark as internal?
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/VidToIndexMapGenerator.kt` line 35 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509#-Nsxsb74BQhnVYh22MW-:-Nsxsb74BQhnVYh22MW0:b4efa82) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8b3437b1b718ae9c16b15b21f73e9c025699beaf/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/VidToIndexMapGenerator.kt#L35)):*
> ```Kotlin
>   /**
>    * Generates the map (vid, (bucket index, normalized hash)) for all vids in the vid universe. Each
>    * vid is concatenated with a `salt`, then the sha256 of the combined string is computed. The
> ```

Map doesn't provide any sorting guarantees. If you want that you need to use SortedMap.

https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/-map/
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/VidToIndexMapGenerator.kt` line 50 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509#-NsxsKLdAXhy5MYILU2D:-NsxsKLdAXhy5MYILU2E:b-a6bqt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8b3437b1b718ae9c16b15b21f73e9c025699beaf/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/VidToIndexMapGenerator.kt#L50)):*
> ```Kotlin
> 
>     // Sorts by the hash values. There are no collisions due to the use of secure cryptography hash.
>     hashes.sortBy { it.second }
> ```

I don't think this is needed.


<!-- Sent from Reviewable.io -->

2024-03-14 22:05 UTC, kungfucraig requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509)* status: 5 of 8 files reviewed, 21 unresolved discussions (waiting on @ple13 and @SanjayVas)

___
*[`src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/ShareShuffleSketchGeneratorTest.kt` line 55 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509#-NsyzqX52yJSfUIUV8Kq:-NsyzqX52yJSfUIUV8Kr:bgo9o58) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8b3437b1b718ae9c16b15b21f73e9c025699beaf/src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/ShareShuffleSketchGeneratorTest.kt#L55)):*
> ```Kotlin
> class ShareShuffleSketchGeneratorTest {
>   @Test
>   fun `vid sampling interval in the middle of the unit interval and contains no vid fails`() {
> ```

If the interval doesn't contain a VID and we get an empty sketch I don't think that's an error.


<!-- Sent from Reviewable.io -->

2024-03-15 20:02 UTC, ple13 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509)* status: 2 of 8 files reviewed, 21 unresolved discussions (waiting on @kungfucraig and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 207 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509#-Nrl5rSX08JZ3aBmb2jv:-Nt253gX0FAh0iiXnVNb:b-li86pw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4316c15610a85bc281ab0de58ed3e838004e7ed1/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L207)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The string that BigInteger expects is a string representation of an integer, e.g. "1234". BigInteger also has a constructor that takes a byte array containing a two's complement binary representation in big-endian byte order[^1]. This is what you'd actually want to call.

[^1]: https://docs.oracle.com/javase/8/docs/api/java/math/BigInteger.html#BigInteger-byte:A-
</blockquote></details>

Thanks. I've updated the code to avoid the string conversion.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 528 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509#-Nrl2uzgDgyAa2ZLbqmZ:-Nsy7LVs7y0XEdkQnq7C:b-ucfkn4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4316c15610a85bc281ab0de58ed3e838004e7ed1/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L528)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

It was probably not configured correctly. We use ktfmt[^1]. To get IntelliJ to format correctly, you'll need to install the ktfmt plugin and configure it to use Google style.

[^1]: https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/docs/code-style.md#kotlin-1
</blockquote></details>

Thanks.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 987 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509#-NsxceEL4r6rpUTDZTdn:-Nsy7RIUD2O39QsztQ_k:b-qh5ov1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8b3437b1b718ae9c16b15b21f73e9c025699beaf/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L987)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Where is this called from?
</blockquote></details>

The function that calls this has not been implemented yet. I can remove this function from this PR to avoid confusion.  WDYT?
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/ShareShuffleSketchGenerator.kt` line 30 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509#-NsskX8j028sgo-RG5Pb:-Nsy7v1kD7J6z1WSYEMk:b-iu8lbp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8b3437b1b718ae9c16b15b21f73e9c025699beaf/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/ShareShuffleSketchGenerator.kt#L30)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Since we are not using the AnySketch class, we don't want to use Sketch for this. However, your comment about the comment stands. :)
</blockquote></details>

I've changed it to `frequency vector`.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/ShareShuffleSketchGenerator.kt` line 34 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509#-NsxcL093JiHAmDhw6Qf:-Nt2TsnS8gD4B9ZIXyMr:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8b3437b1b718ae9c16b15b21f73e9c025699beaf/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/ShareShuffleSketchGenerator.kt#L34)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

You could initialize this during construction and retain it.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/ShareShuffleSketchGenerator.kt` line 35 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509#-NsxczJG9CcfNUjKTlXF:-Nt25txRCC0FZaVa9ggL:b-1cep5g) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8b3437b1b718ae9c16b15b21f73e9c025699beaf/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/ShareShuffleSketchGenerator.kt#L35)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Same here re: initialize.

What is causing the list to be sorted?
</blockquote></details>

Thanks for catching this. It turns out that the sorted order may not be preserved even if it's created from a sorted map. I've updated the code to make sure that the list is sorted.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/ShareShuffleSketchGenerator.kt` line 42 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509#-NsxdRCC8cY068BcdJe1:-Nsy8YFoAJx4V92LWIax:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8b3437b1b718ae9c16b15b21f73e9c025699beaf/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/ShareShuffleSketchGenerator.kt#L42)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

if ( isWrappedAround)
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/ShareShuffleSketchGenerator.kt` line 46 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509#-Nsu34b-5XVOpS6lItyI:-Nt2SzZG9i_beM7-eDpN:bw3lppl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8b3437b1b718ae9c16b15b21f73e9c025699beaf/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/ShareShuffleSketchGenerator.kt#L46)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Extract lines 46-67 into a separate function so this can be tested separately?
</blockquote></details>

I think we do not test these functions directly. However, I will add tests to test them indirectly.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/ShareShuffleSketchGenerator.kt` line 53 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509#-NsxdkGFDUvA3sLseKBW:-Nt2QQnO1nb471MbHnMf:bi3bapt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8b3437b1b718ae9c16b15b21f73e9c025699beaf/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/ShareShuffleSketchGenerator.kt#L53)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

!isWrappedAround implies start <= end, doesn't it? 

Also I don't see a matching else here, and falling through would trigger the assertion below.
</blockquote></details>

The function upperBound returns the first index where the value is greater than the target value. So the sketch will include indices in `[start, end = upperBound(interval.end) - 1]`. When x[i - 1] < interval.start < interval.end < x[i], then start = i, and, end = (i-1). I added an else block to return an empty array in case the sketch size is 0.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/ShareShuffleSketchGenerator.kt` line 100 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509#-Nsskkew7qdGEa4YAEXE:-NsvjlZ40E2MQ2usl08y:b-896fix) ([raw file](https://github.com/world-federation-of-a [...]

2024-03-15 22:01 UTC, kungfucraig requested changes
> Reviewed 1 of 8 files at r2, 4 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509)* status: 7 of 8 files reviewed, 17 unresolved discussions (waiting on @ple13 and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 987 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509#-NsxceEL4r6rpUTDZTdn:-Nt32bYeEpB97rfWcnAA:b-4dwz26) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8b3437b1b718ae9c16b15b21f73e9c025699beaf/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L987)):*
<details><summary><i>Previously, ple13 (Phi) wrote…</i></summary><blockquote>

The function that calls this has not been implemented yet. I can remove this function from this PR to avoid confusion.  WDYT?
</blockquote></details>

It's fine. Go ahead and keep it. Just wanted to make sure I wasn't missing anything.

Presumably the next PR will make use of it. :)
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/ShareShuffleSketchGenerator.kt` line 53 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509#-NsxdkGFDUvA3sLseKBW:-Nt34p0Q8j3bKGwrzDOL:bvu6v84) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8b3437b1b718ae9c16b15b21f73e9c025699beaf/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/ShareShuffleSketchGenerator.kt#L53)):*
<details><summary><i>Previously, ple13 (Phi) wrote…</i></summary><blockquote>

The function upperBound returns the first index where the value is greater than the target value. So the sketch will include indices in `[start, end = upperBound(interval.end) - 1]`. When x[i - 1] < interval.start < interval.end < x[i], then start = i, and, end = (i-1). I added an else block to return an empty array in case the sketch size is 0.
</blockquote></details>

The else is an extreme corner case, but I see how we could get there. Thanks for the explanation.

Could we check for start == end above and throw an error (sampling interval too small) instead? 
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/ShareShuffleSketchGenerator.kt` line 26 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509#-Nt33FS5CmahaIEtdMIs:-Nt33FS5CmahaIEtdMIt:b-19gka) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/601b5f6e62c529bbca7b42b6970777edad4115f2/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/ShareShuffleSketchGenerator.kt#L26)):*
> ```Kotlin
>   private val vidUniverse: List<Long>,
>   private val salt: ByteString,
>   private var vidToIndexMap: Map<Long, IndexedValue>,
> ```

I think you should declare this inside of the class, in which case you can move the "isEmpty" check in the init block. Similar to what you've done with sortedNormalizedHashValues.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/ShareShuffleSketchGenerator.kt` line 30 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509#-Nt348BAB_EhFeWgQim4:-Nt348BAB_EhFeWgQim5:b-p6i39) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/601b5f6e62c529bbca7b42b6970777edad4115f2/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/ShareShuffleSketchGenerator.kt#L30)):*
> ```Kotlin
>   private val vidSamplingInterval: MeasurementSpec.VidSamplingInterval,
> ) {
>   var sortedNormalizedHashValues: List<Double>
> ```

Can you make this a val? My Kotlin is not so good, so maybe this is not possible?
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/ShareShuffleSketchGenerator.kt` line 104 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509#-Nt35X9iAaPhMGsBJZT2:-Nt35X9iAaPhMGsBJZT3:b-9dig80) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/601b5f6e62c529bbca7b42b6970777edad4115f2/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/ShareShuffleSketchGenerator.kt#L104)):*
> ```Kotlin
>    * implementation is based on the c++ std::lower_bound.
>    */
>   private fun lowerBound(sortedList: List<Double>, target: Double): Int {
> ```

@SanjayVas Can these two bound functions be declared internal so @ple13 can write some tests for them?
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/VidToIndexMapGenerator.kt` line 26 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509#-Nssl6sd5hUBIzc2JBBv:-Nt35got6wZALtK1pQX4:b5hz5dh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8b3437b1b718ae9c16b15b21f73e9c025699beaf/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/VidToIndexMapGenerator.kt#L26)):*
<details><summary><i>Previously, ple13 (Phi) wrote…</i></summary><blockquote>

This object is potentially used in the pre-processing phase where the EDPs pre-compute the sha256 for all the VIDs in the VID universe. In the correct EDP implementation, EDP only calls this function when the cache doesn't exist. Given the complexity of this function, I think we should make it a separate object and test it properly.
</blockquote></details>

+1 to keeping it independent. If we mark it "internal" it will not be visible outside the package.
___
*[`src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/VidToIndexMapGeneratorTest.kt` line 25 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509#-Nt377wFEoqfPuPGHVRR:-Nt377wFEoqfPuPGHVRS:b-q0ig0x) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/601b5f6e62c529bbca7b42b6970777edad4115f2/src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/VidToIndexMapGeneratorTest.kt#L25)):*
> ```Kotlin
> 
> @RunWith(JUnit4::class)
> class VidToIndexMapGeneratorTest {
> ```

Can you add a simple test with an empty salt that succeeds?


<!-- Sent from Reviewable.io -->

2024-03-15 22:01 UTC, kungfucraig reviewed
> Reviewed 1 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509)* status: all files reviewed, 17 unresolved discussions (waiting on @ple13 and @SanjayVas)



<!-- Sent from Reviewable.io -->

2024-03-15 22:06 UTC, SanjayVas requested changes
> Reviewed 2 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509)* status: all files reviewed, 10 unresolved discussions (waiting on @ple13)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/VidToIndexMapGenerator.kt` line 26 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509#-Nssl6sd5hUBIzc2JBBv:-Nt37_a04a6w5xGyQHdY:b-e3tbr5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8b3437b1b718ae9c16b15b21f73e9c025699beaf/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/VidToIndexMapGenerator.kt#L26)):*
> If we mark it "internal" it will not be visible outside the package.

Close. It will not be visible outside of the compilation unit (i.e. the kt_jvm_library). Kotlin's "internal" is not the same as Java's default "package-private".

> This object is potentially used in the pre-processing phase where the EDPs pre-compute the sha256 for all the VIDs in the VID universe.

This is the important part. This is therefore not an implementation detail of ShareShuffleSketchGenerator since it's called before that.
___
*[`src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/ShareShuffleSketchGeneratorTest.kt` line 54 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509#-Nt38UFA31hvldS0sly2:-Nt38UFB32kMd_4Kkh9W:b2hqvp3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/601b5f6e62c529bbca7b42b6970777edad4115f2/src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/ShareShuffleSketchGeneratorTest.kt#L54)):*
> ```Kotlin
> class ShareShuffleSketchGeneratorTest {
>   @Test
>   fun `ShareShuffleSketchGenerator returns non-wrapped around sketch with correct range`() {
> ```

Refer to the method under test, not the class. Consider if this class had more than one public method.



_Suggestion:_
```Kotlin
generate
```


<!-- Sent from Reviewable.io -->

2024-03-18 18:42 UTC, ple13 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509)* status: 5 of 8 files reviewed, 10 unresolved discussions (waiting on @kungfucraig and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 987 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509#-NsxceEL4r6rpUTDZTdn:-NtF1aqRB6eAOKiWAAQm:buikaw5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8b3437b1b718ae9c16b15b21f73e9c025699beaf/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L987)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

It's fine. Go ahead and keep it. Just wanted to make sure I wasn't missing anything.

Presumably the next PR will make use of it. :)
</blockquote></details>

Yeah. This function will be used in the next PR.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/ShareShuffleSketchGenerator.kt` line 53 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509#-NsxdkGFDUvA3sLseKBW:-NtF-SJh6c5QIu45lKg1:b-4mhauk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8b3437b1b718ae9c16b15b21f73e9c025699beaf/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/ShareShuffleSketchGenerator.kt#L53)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

The else is an extreme corner case, but I see how we could get there. Thanks for the explanation.

Could we check for start == end above and throw an error (sampling interval too small) instead?
</blockquote></details>

In that case I think we can throw an error if the sketch size is 0. This will also cover the case where wrap around happens. I've updated the code.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/ShareShuffleSketchGenerator.kt` line 26 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509#-Nt33FS5CmahaIEtdMIs:-NtEwXesEmAGKgZzzbW9:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/601b5f6e62c529bbca7b42b6970777edad4115f2/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/ShareShuffleSketchGenerator.kt#L26)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

I think you should declare this inside of the class, in which case you can move the "isEmpty" check in the init block. Similar to what you've done with sortedNormalizedHashValues.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/ShareShuffleSketchGenerator.kt` line 30 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509#-Nt348BAB_EhFeWgQim4:-NtCdD2T4cef3_pUKlGI:bebx84f) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/601b5f6e62c529bbca7b42b6970777edad4115f2/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/ShareShuffleSketchGenerator.kt#L30)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Can you make this a val? My Kotlin is not so good, so maybe this is not possible?
</blockquote></details>

Yeah. I've made it a val.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/ShareShuffleSketchGenerator.kt` line 104 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509#-Nt35X9iAaPhMGsBJZT2:-NtHqbZDB9E-3Rf8BOjL:bdk9j49) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/601b5f6e62c529bbca7b42b6970777edad4115f2/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/ShareShuffleSketchGenerator.kt#L104)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

@SanjayVas Can these two bound functions be declared internal so @ple13 can write some tests for them?
</blockquote></details>

Can I declare a helper class in which these functions are public ones, then we test them?
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/VidToIndexMapGenerator.kt` line 26 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509#-Nssl6sd5hUBIzc2JBBv:-NtEwbOR4_dRDg49hCad:bu41scc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8b3437b1b718ae9c16b15b21f73e9c025699beaf/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/VidToIndexMapGenerator.kt#L26)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> If we mark it "internal" it will not be visible outside the package.

Close. It will not be visible outside of the compilation unit (i.e. the kt_jvm_library). Kotlin's "internal" is not the same as Java's default "package-private".

> This object is potentially used in the pre-processing phase where the EDPs pre-compute the sha256 for all the VIDs in the VID universe.

This is the important part. This is therefore not an implementation detail of ShareShuffleSketchGenerator since it's called before that.
</blockquote></details>

Thanks. I'll keep it as a separate object then.
___
*[`src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/ShareShuffleSketchGeneratorTest.kt` line 54 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509#-Nt38UFA31hvldS0sly2:-NtF1ibN6hAepqi1zZS7:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/601b5f6e62c529bbca7b42b6970777edad4115f2/src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/ShareShuffleSketchGeneratorTest.kt#L54)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Refer to the method under test, not the class. Consider if this class had more than one public method.
</blockquote></details>

Done.
___
*[`src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/VidToIndexMapGeneratorTest.kt` line 25 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509#-Nt377wFEoqfPuPGHVRR:-NtAg8iGB-GG75_1auq2:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/601b5f6e62c529bbca7b42b6970777edad4115f2/src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/VidToIndexMapGeneratorTest.kt#L25)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Can you add a simple test with an empty salt that succeeds?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-03-18 19:06 UTC, SanjayVas requested changes
> Reviewed 1 of 8 files at r2, 1 of 5 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509)* status: all files reviewed, 7 unresolved discussions (waiting on @kungfucraig and @ple13)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/ShareShuffleSketchGenerator.kt` line 104 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509#-Nt35X9iAaPhMGsBJZT2:-NtHsmtN9lSzNxc06gis:by6hlxp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/601b5f6e62c529bbca7b42b6970777edad4115f2/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/ShareShuffleSketchGenerator.kt#L104)):*
<details><summary><i>Previously, ple13 (Phi) wrote…</i></summary><blockquote>

Can I declare a helper class in which these functions are public ones, then we test them?
</blockquote></details>

Can't this just call [`Collections.binarySearch`](https://docs.oracle.com/javase%2F7%2Fdocs%2Fapi%2F%2F/java/util/Collections.html#binarySearch(java.util.List,%20T)) from the Java standard library?

See https://stackoverflow.com/questions/15603832/java-equivalent-of-c-equal-range-or-lower-bound-upper-bound
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/ShareShuffleSketchGenerator.kt` line 26 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509#-NtHsZ2VDYsGYK1BDq6D:-NtHsZ2VDYsGYK1BDq6E:bqw0m36) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2b43302811b003126a5aaf77ad33d8df13e88431/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/ShareShuffleSketchGenerator.kt#L26)):*
> ```Kotlin
>   private val vidUniverse: List<Long>,
>   private val salt: ByteString,
>   private val inputVidToIndexMap: Map<Long, IndexedValue>,
> ```

Does this need to be a property, or can it just be a constructor argument? It looks like it's only read by the init block.


<!-- Sent from Reviewable.io -->

2024-03-18 20:53 UTC, kungfucraig reviewed
> Reviewed 2 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509)* status: all files reviewed, 2 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/ShareShuffleSketchGenerator.kt` line 26 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509#-NtHsZ2VDYsGYK1BDq6D:-NtI2jQk02-eYmWbtaqj:bkdd1xs) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2b43302811b003126a5aaf77ad33d8df13e88431/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/ShareShuffleSketchGenerator.kt#L26)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Does this need to be a property, or can it just be a constructor argument? It looks like it's only read by the init block.
</blockquote></details>

My question is more the opposite. What's the case for passing it in at all vs. building it in the constructor?


<!-- Sent from Reviewable.io -->

2024-03-19 19:13 UTC, ple13 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509)* status: 7 of 8 files reviewed, 2 unresolved discussions (waiting on @kungfucraig and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/ShareShuffleSketchGenerator.kt` line 104 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509#-Nt35X9iAaPhMGsBJZT2:-NtMsiWVD_rKcT5JFkwe:b-pkv0hr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/601b5f6e62c529bbca7b42b6970777edad4115f2/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/ShareShuffleSketchGenerator.kt#L104)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Can't this just call [`Collections.binarySearch`](https://docs.oracle.com/javase%2F7%2Fdocs%2Fapi%2F%2F/java/util/Collections.html#binarySearch(java.util.List,%20T)) from the Java standard library?

See https://stackoverflow.com/questions/15603832/java-equivalent-of-c-equal-range-or-lower-bound-upper-bound
</blockquote></details>

We can call Collections.binarySearch. However, we need to process its return value to get the lower bound and upper bound too. I think some tests are still needed, but we could have more confidence in our implementation.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/ShareShuffleSketchGenerator.kt` line 26 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509#-NtHsZ2VDYsGYK1BDq6D:-NtI2xZt089zwKzCzA36:bgfobes) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2b43302811b003126a5aaf77ad33d8df13e88431/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/ShareShuffleSketchGenerator.kt#L26)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

My question is more the opposite. What's the case for passing it in at all vs. building it in the constructor?
</blockquote></details>

I think this depends on how we will read the cached vid map. If we decide to read it when creating the ShareShuffleSketchGenerator object, then we do not need to pass the inputVidToIndexMap as an argument. If we read it before creating the ShareShuffleSketchGenerator object, then we don't need to call the function to generate the map inside the init block at all (with the assumption that the vid map has been read/computed).


<!-- Sent from Reviewable.io -->

2024-03-19 19:30 UTC, kungfucraig approved these changes
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/ShareShuffleSketchGenerator.kt` line 26 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509#-NtHsZ2VDYsGYK1BDq6D:-NtNAAuxAJvkcBkxC7U-:brngcqq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2b43302811b003126a5aaf77ad33d8df13e88431/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/ShareShuffleSketchGenerator.kt#L26)):*
<details><summary><i>Previously, ple13 (Phi) wrote…</i></summary><blockquote>

I think this depends on how we will read the cached vid map. If we decide to read it when creating the ShareShuffleSketchGenerator object, then we do not need to pass the inputVidToIndexMap as an argument. If we read it before creating the ShareShuffleSketchGenerator object, then we don't need to call the function to generate the map inside the init block at all (with the assumption that the vid map has been read/computed).
</blockquote></details>

Let's keep it for now. We're going to have to refactor once we build the reusable libraries anyway. We'll know more about the overall usage then.


<!-- Sent from Reviewable.io -->

2024-03-19 20:14 UTC, SanjayVas reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509)* status: all files reviewed, 1 unresolved discussion (waiting on @ple13)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/ShareShuffleSketchGenerator.kt` line 104 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509#-Nt35X9iAaPhMGsBJZT2:-NtNK8xAB2GVReOzCfR1:ba8a2st) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/601b5f6e62c529bbca7b42b6970777edad4115f2/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/ShareShuffleSketchGenerator.kt#L104)):*
<details><summary><i>Previously, ple13 (Phi) wrote…</i></summary><blockquote>

We can call Collections.binarySearch. However, we need to process its return value to get the lower bound and upper bound too. I think some tests are still needed, but we could have more confidence in our implementation.
</blockquote></details>

We already depend on Guava, so there's also `SortedLists.binarySearch`. My assumption is that the existing KeyPresentBehavior values can distinguish lower vs. upper bound.


<!-- Sent from Reviewable.io -->

2024-03-19 20:36 UTC, ple13 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509)* status: 7 of 8 files reviewed, 1 unresolved discussion (waiting on @kungfucraig and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/ShareShuffleSketchGenerator.kt` line 104 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509#-Nt35X9iAaPhMGsBJZT2:-NtNMZzl-vODy27-DvxQ:bf4hs7b) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/601b5f6e62c529bbca7b42b6970777edad4115f2/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/ShareShuffleSketchGenerator.kt#L104)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

We already depend on Guava, so there's also `SortedLists.binarySearch`. My assumption is that the existing KeyPresentBehavior values can distinguish lower vs. upper bound.
</blockquote></details>

Thanks. I've updated the code. If the list does not contain duplicated values, then we can infer the lower/upper bound directly from the return value. However, if the list has multiple elements that are equal to target, we need to search for the first/last index as binarySearch can return any of them.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/ShareShuffleSketchGenerator.kt` line 26 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509#-NtHsZ2VDYsGYK1BDq6D:-NtNQAjZ1OddzkedG-ag:b-7xtei2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2b43302811b003126a5aaf77ad33d8df13e88431/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/ShareShuffleSketchGenerator.kt#L26)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Let's keep it for now. We're going to have to refactor once we build the reusable libraries anyway. We'll know more about the overall usage then.
</blockquote></details>

Yeah.


<!-- Sent from Reviewable.io -->

2024-03-19 20:40 UTC, SanjayVas reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509)* status: 7 of 8 files reviewed, 1 unresolved discussion (waiting on @kungfucraig)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/ShareShuffleSketchGenerator.kt` line 104 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509#-Nt35X9iAaPhMGsBJZT2:-NtNRDvRC5ZXRE_a3ez6:b68ivdi) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/601b5f6e62c529bbca7b42b6970777edad4115f2/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/ShareShuffleSketchGenerator.kt#L104)):*
> However, if the list has multiple elements that are equal to target, we need to search for the first/last index as binarySearch can return any of them.

The `KeyPresentBehavior` of `SortedLists.binarySearch` controls this. The point I'm making is that we can avoid writing this code ourselves and therefore avoid having to write tests for it.


<!-- Sent from Reviewable.io -->

2024-03-20 19:18 UTC, ple13 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509)* status: 7 of 8 files reviewed, 1 unresolved discussion (waiting on @kungfucraig and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/ShareShuffleSketchGenerator.kt` line 104 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509#-Nt35X9iAaPhMGsBJZT2:-NtSHTyD6Y9iGy4bdSRT:b-345qyq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/601b5f6e62c529bbca7b42b6970777edad4115f2/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/ShareShuffleSketchGenerator.kt#L104)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> However, if the list has multiple elements that are equal to target, we need to search for the first/last index as binarySearch can return any of them.

The `KeyPresentBehavior` of `SortedLists.binarySearch` controls this. The point I'm making is that we can avoid writing this code ourselves and therefore avoid having to write tests for it.
</blockquote></details>

As SortedLists is still a private class, I've move the lowerBound and upper bound functions to common, and have tests for them.


<!-- Sent from Reviewable.io -->

2024-03-26 07:32 UTC, ple13 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509)* status: 6 of 14 files reviewed, 2 unresolved discussions (waiting on @kungfucraig and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/ShareShuffleSketchGenerator.kt` line 26 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509#-NtHsZ2VDYsGYK1BDq6D:-Nttd8quDVvMaOY5gqjI:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2b43302811b003126a5aaf77ad33d8df13e88431/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/ShareShuffleSketchGenerator.kt#L26)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

My point is that the code as written right now passes `inputVidToIndexMap` in to the constructor and only uses it to build the `vidToIndexMap` property. It is never read as a property after that point.

My suggestion is to replace

```kotlin
private val inputVidToIndexMap: Map<Long, IndexedValue>,
```

with

```kotlin
inputVidToIndexMap: Map<Long, IndexedValue>,
```

Obviously this can be changed later, but we shouldn't leave unnecessary properties around speculatively.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/common/SortedListUtils.kt` line 1 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509#-Ntqychg16eJkLNLMiGB:-Nttd7hJ8G3mxJGqEZmI:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/93a14d0d452ab09a6fdba85199698b779387bbf8/src/main/kotlin/org/wfanet/measurement/loadtest/common/SortedListUtils.kt#L1)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Call this file SortedLists.kt and put it in measurement.common with a TODO to move it to common-jvm.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-03-26 18:38 UTC, SanjayVas approved these changes
> Reviewed 8 of 8 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @kungfucraig)



<!-- Sent from Reviewable.io -->

2024-03-26 21:32 UTC, renjiezh reviewed
> Reviewed 1 of 2 files at r1, 1 of 6 files at r8.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509)* status: all files reviewed, 1 unresolved discussion (waiting on @kungfucraig and @ple13)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/VidToIndexMapGenerator.kt` line 38 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509#-NtwfOQy3qLri4Qkyi8A:-NtwfOQy3qLri4Qkyi8B:b-fvunxm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/44c7b6c146db8f383394f3b81a0d518f06efdaa8/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/VidToIndexMapGenerator.kt#L38)):*
> ```Kotlin
>    *
>    * Each vid is concatenated with a `salt`, then the sha256 of the combined string is computed. The
>    * vid's are sorted based on its hash value. The bucket index of a vid is its located in the
> ```

nip: typo "location" instead of "located"


<!-- Sent from Reviewable.io -->

2024-03-27 03:22 UTC, ple13 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509)* status: 13 of 14 files reviewed, 1 unresolved discussion (waiting on @kungfucraig, @renjiezh, and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/VidToIndexMapGenerator.kt` line 38 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509#-NtwfOQy3qLri4Qkyi8A:-NtxvScS3KcdVyBet9JA:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/44c7b6c146db8f383394f3b81a0d518f06efdaa8/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/VidToIndexMapGenerator.kt#L38)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

nip: typo "location" instead of "located"
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-04-01 21:49 UTC, kungfucraig approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509#-:-NuQcyI82SMRW4FsQjYW:bnfp4nl)* status: 13 of 14 files reviewed, 1 unresolved discussion (waiting on @Marco-Premier, @renjiezh, @SanjayVas, and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2024-04-02 20:57 UTC, stevenwarejones requested changes
> Reviewed 1 of 8 files at r2, 1 of 5 files at r4, 5 of 8 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509)* status: 13 of 14 files reviewed, 4 unresolved discussions (waiting on @kungfucraig, @Marco-Premier, @ple13, @renjiezh, and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 983 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509#-NuVZJ327423hrUQ2Yu2:-NuVZJ327423hrUQ2Yu3:b-fps4ml) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/62b9f0d7f837736786dbf8a98680407f604be118/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L983)):*
> ```Kotlin
>   private fun logShareShuffleSketchDetails(sketch: IntArray) {
>     for (register in sketch) {
>       logger.log(Level.INFO) { "${register}" }
> ```

this is potentially a lot of logs, right?
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/ShareShuffleSketchGenerator.kt` line 45 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509#-NuV_ptf-Amhlc_Kj8h8:-NuV_ptf-Amhlc_Kj8h9:b-cvhpi5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/62b9f0d7f837736786dbf8a98680407f604be118/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/ShareShuffleSketchGenerator.kt#L45)):*
> ```Kotlin
>     require(vidUniverse.isNotEmpty()) { "The vid universe size must be positive." }
> 
>     var samplingIntervalEnd: Double =
> ```

I'd prefer a single val
```
val samplingIntervalEnd = if (vidSamplingInterval.start + vidSamplingInterval.width > 1) .... else ...
```

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/ShareShuffleSketchGenerator.kt` line 48 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509#-NuVaNj52zOs99o56MIK:-NuVaNj52zOs99o56MIL:bir6ymj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/62b9f0d7f837736786dbf8a98680407f604be118/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/ShareShuffleSketchGenerator.kt#L48)):*
> ```Kotlin
>       (vidSamplingInterval.start + vidSamplingInterval.width).toDouble()
> 
>     val isWrappedAround = (samplingIntervalEnd > 1.0)
> ```

i was not aware that we supported wrap around use cases. When did that change?


<!-- Sent from Reviewable.io -->

2024-04-02 21:02 UTC, renjiezh reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509)* status: 13 of 14 files reviewed, 3 unresolved discussions (waiting on @kungfucraig, @Marco-Premier, @ple13, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/ShareShuffleSketchGenerator.kt` line 48 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509#-NuVaNj52zOs99o56MIK:-NuVb4Gv8LsQAuvahUYC:b-wbhft5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/62b9f0d7f837736786dbf8a98680407f604be118/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/ShareShuffleSketchGenerator.kt#L48)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

i was not aware that we supported wrap around use cases. When did that change?
</blockquote></details>

I will add the support in following PRs for both Kingdom and Duchy. 


<!-- Sent from Reviewable.io -->

2024-04-02 21:03 UTC, stevenwarejones requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509)* status: 13 of 14 files reviewed, 3 unresolved discussions (waiting on @kungfucraig, @Marco-Premier, @ple13, and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/ShareShuffleSketchGenerator.kt` line 48 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509#-NuVaNj52zOs99o56MIK:-NuVbunX4AfUx8x89DVW:b-xozmua) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/62b9f0d7f837736786dbf8a98680407f604be118/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/ShareShuffleSketchGenerator.kt#L48)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

I will add the support in following PRs for both Kingdom and Duchy.
</blockquote></details>

@kungfucraig - did this change as a req at some point?


<!-- Sent from Reviewable.io -->

2024-04-02 23:49 UTC, kungfucraig reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509)* status: 13 of 14 files reviewed, 3 unresolved discussions (waiting on @Marco-Premier, @ple13, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/ShareShuffleSketchGenerator.kt` line 48 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509#-NuVaNj52zOs99o56MIK:-NuWCSaq8MQSp5ZhCdGx:bjfgsjn) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/62b9f0d7f837736786dbf8a98680407f604be118/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/ShareShuffleSketchGenerator.kt#L48)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

@kungfucraig - did this change as a req at some point?
</blockquote></details>

We want to add wrapping support for HM Shuffle. It was discussed here: https://docs.google.com/document/d/1MSkk48_q3si7A2zzo7hZaIQKol5g0HqvKzGYGb2_J5I/edit?resourcekey=0-liMTknKG1ZhwK1ifPMZI2A&tab=t.0#heading=h.o8meywigtv7y

Ultimately this change is because it will provide more uniform usage of the privacy budget across the entire interval. 


<!-- Sent from Reviewable.io -->

2024-04-03 16:06 UTC, ple13 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509)* status: 12 of 14 files reviewed, 3 unresolved discussions (waiting on @kungfucraig, @Marco-Premier, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 983 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509#-NuVZJ327423hrUQ2Yu2:-NuXD2_n85mjJIqVMD_Z:byulrpz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/62b9f0d7f837736786dbf8a98680407f604be118/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L983)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

this is potentially a lot of logs, right?
</blockquote></details>

Yes, the log could be large (e.g. O(10MB)).
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/ShareShuffleSketchGenerator.kt` line 45 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509#-NuV_ptf-Amhlc_Kj8h8:-NuXFqwJ94BL_dEU5_m-:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/62b9f0d7f837736786dbf8a98680407f604be118/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/ShareShuffleSketchGenerator.kt#L45)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

I'd prefer a single val
```
val samplingIntervalEnd = if (vidSamplingInterval.start + vidSamplingInterval.width > 1) .... else ...
```

</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-04-03 22:05 UTC, stevenwarejones requested changes
> Reviewed 1 of 8 files at r2, 2 of 3 files at r5, 2 of 8 files at r9, 1 of 1 files at r10, 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509)* status: all files reviewed, 2 unresolved discussions (waiting on @Marco-Premier, @ple13, and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 983 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509#-NuVZJ327423hrUQ2Yu2:-Nu_yGqrE0S_Kwt695mv:bhemtrg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/62b9f0d7f837736786dbf8a98680407f604be118/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L983)):*
<details><summary><i>Previously, ple13 (Phi) wrote…</i></summary><blockquote>

Yes, the log could be large (e.g. O(10MB)).
</blockquote></details>

wouldn't it be better to log these together or not log them at all or only log x%?
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/ShareShuffleSketchGenerator.kt` line 48 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509#-NuVaNj52zOs99o56MIK:-Nu_y_qdAhCc7OtJhS_p:bwkez63) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/62b9f0d7f837736786dbf8a98680407f604be118/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/ShareShuffleSketchGenerator.kt#L48)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

We want to add wrapping support for HM Shuffle. It was discussed here: https://docs.google.com/document/d/1MSkk48_q3si7A2zzo7hZaIQKol5g0HqvKzGYGb2_J5I/edit?resourcekey=0-liMTknKG1ZhwK1ifPMZI2A&tab=t.0#heading=h.o8meywigtv7y

Ultimately this change is because it will provide more uniform usage of the privacy budget across the entire interval.
</blockquote></details>

this makes a lot of sense
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/VidToIndexMapGenerator.kt` line 52 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509#-Nu_zTMK143S6vvnnMmO:-Nu_zTMK143S6vvnnMmP:b-k3jkyd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c70a83877fb994c33809041f68d8dad2f2e1c4c9/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/VidToIndexMapGenerator.kt#L52)):*
> ```Kotlin
>     }
> 
>     // Sorts by the hash values. There are no collisions due to the use of secure cryptography hash.
> ```

why can't there be collisions? A secure cryptography has can still collide.


<!-- Sent from Reviewable.io -->

2024-04-04 16:25 UTC, ple13 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509)* status: 13 of 14 files reviewed, 2 unresolved discussions (waiting on @Marco-Premier, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 983 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509#-NuVZJ327423hrUQ2Yu2:-Nuds3C7B6fUBZh801K4:bejwq9v) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/62b9f0d7f837736786dbf8a98680407f604be118/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L983)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

wouldn't it be better to log these together or not log them at all or only log x%?
</blockquote></details>

I think this is up to the EDP to decide how much they want to log.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/VidToIndexMapGenerator.kt` line 52 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509#-Nu_zTMK143S6vvnnMmO:-NudpaY_CmqPY42c42Fn:bgvkh0z) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c70a83877fb994c33809041f68d8dad2f2e1c4c9/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/VidToIndexMapGenerator.kt#L52)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

why can't there be collisions? A secure cryptography has can still collide.
</blockquote></details>

Yeah, there is still a negligible chance of collision, but it's very small. The chance of collision for a pair is ~2^{-256}, so even if we have 2^40 items, the chance of having 1 collision is still smaller than 2^{-128}. I've updated the text to reflect this.


<!-- Sent from Reviewable.io -->

2024-04-04 19:47 UTC, kungfucraig reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509)* status: 13 of 14 files reviewed, 2 unresolved discussions (waiting on @Marco-Premier, @ple13, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/VidToIndexMapGenerator.kt` line 52 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509#-Nu_zTMK143S6vvnnMmO:-NuedAjE80PnAsC0wmLq:b-hn5x1j) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c70a83877fb994c33809041f68d8dad2f2e1c4c9/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/VidToIndexMapGenerator.kt#L52)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

I don't think we need the secondary collision logic. My main problem was with the comment - not the logic. I think its fine to just have a simpler comment that we sort by hash value. The comment about secure cryptography is kind of irrelevant imo.
</blockquote></details>

The secondary compare doesn't hurt and costs nothing unless the first key collides.


<!-- Sent from Reviewable.io -->

2024-04-04 19:48 UTC, kungfucraig reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509)* status: 13 of 14 files reviewed, 2 unresolved discussions (waiting on @Marco-Premier, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 983 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509#-NuVZJ327423hrUQ2Yu2:-Nuedoap7Nshq7qbUsG0:beaji8n) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/62b9f0d7f837736786dbf8a98680407f604be118/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L983)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

okay - I guess this is just a simulator. please change the log level here to FINEST
</blockquote></details>

Let's keep this as INFO to be consistent with the LLv2 logging.


<!-- Sent from Reviewable.io -->

2024-04-05 20:45 UTC, stevenwarejones approved these changes
> Reviewed 1 of 1 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509)* status: all files reviewed, 1 unresolved discussion (waiting on @kungfucraig, @Marco-Premier, @ple13, and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 983 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509#-NuVZJ327423hrUQ2Yu2:-NujyySz2q5tiXOk9YeJ:blag53c) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/62b9f0d7f837736786dbf8a98680407f604be118/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L983)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Let's keep this as INFO to be consistent with the LLv2 logging.
</blockquote></details>

Please open a github issue to support logging other than info.


<!-- Sent from Reviewable.io -->

2024-04-05 20:54 UTC, renjiezh approved these changes
> Reviewed 2 of 8 files at r2, 1 of 5 files at r4, 2 of 3 files at r5, 7 of 8 files at r9, 1 of 1 files at r12, 1 of 1 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509)* status: all files reviewed, 1 unresolved discussion (waiting on @kungfucraig, @Marco-Premier, @ple13, and @SanjayVas)



<!-- Sent from Reviewable.io -->

2024-04-05 21:45 UTC, kungfucraig reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509)* status: all files reviewed, 1 unresolved discussion (waiting on @Marco-Premier, @ple13, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 983 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509#-NuVZJ327423hrUQ2Yu2:-NukDBkcCmgjoVtkOclI:b-tptun) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/62b9f0d7f837736786dbf8a98680407f604be118/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L983)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

Please open a github issue to support logging other than info.
</blockquote></details>

https://github.com/world-federation-of-advertisers/cross-media-measurement/issues/1559


<!-- Sent from Reviewable.io -->

2024-04-05 21:46 UTC, ple13 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Marco-Premier and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 983 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509#-NuVZJ327423hrUQ2Yu2:-NukDHqtECkncGJrrOl4:b-ucfknh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/62b9f0d7f837736786dbf8a98680407f604be118/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L983)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

https://github.com/world-federation-of-advertisers/cross-media-measurement/issues/1559
</blockquote></details>

Thanks!


<!-- Sent from Reviewable.io -->

2024-04-05 23:20 UTC, ple13 reviewed
> Reviewed 2 of 8 files at r2, 1 of 5 files at r4, 2 of 3 files at r5, 6 of 8 files at r9, 1 of 1 files at r12, 1 of 1 files at r14, 1 of 1 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1509)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Marco-Premier and @SanjayVas)



<!-- Sent from Reviewable.io -->

2024-04-05 23:21 UTC, merged