Renjiez hmss system api protocol config
world-federation-of-advertisers/cross-media-measurement pull request #1513
Opened 2024-03-04 19:01 UTC by renjiezh

2024-03-05 18:29 UTC, SanjayVas requested changes
> Reviewed 4 of 31 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1513)* status: 4 of 31 files reviewed, 4 unresolved discussions (waiting on @ple13 and @renjiezh)

___
*[`MODULE.bazel` line 129 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1513#-NsEr8e6BmB5sLc-Nasd:-NsEr8e6BmB5sLc-Nase:b-ucuc1j) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f280895a948232f99340a700ac7e8fa3334fb0d7/MODULE.bazel#L129)):*
> ```Starlark
> bazel_dep(
>     name = "common-jvm",
>     version = "0.75.1",
> ```

Shouldn't this also depend on the fix for Tink key ID, since it is using PrivateKeyStore?
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt` line 78 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1513#-NsEqsqo56_DZLgrjGvV:-NsEqsqp4yez4-53h_Oz:b-4a5c2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f280895a948232f99340a700ac7e8fa3334fb0d7/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt#L78)):*
> ```Kotlin
>   private val systemComputationsClient: SystemComputationsCoroutineStub,
>   private val systemComputationParticipantClient: SystemComputationParticipantsCoroutineStub,
>   private val privateKetStorageClient: PrivateKeyStore<TinkKeyId, TinkPrivateKeyHandle>,
> ```

1. "key" is misspelled
2. StorageClient is a different interface



_Suggestion:_
```Kotlin
privateKeyStore
```
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/HonestMajorityShareShuffleStarter.kt` line 27 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1513#-NsErYzd4SrEgKaz7hCN:-NsErYzeEIZGL8GXsbu1:b-ubg9rt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f280895a948232f99340a700ac7e8fa3334fb0d7/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/HonestMajorityShareShuffleStarter.kt#L27)):*
> ```Kotlin
> import org.wfanet.measurement.common.crypto.tink.TinkKeyId
> import org.wfanet.measurement.common.crypto.tink.TinkPrivateKeyHandle
> import org.wfanet.measurement.common.crypto.tink.TinkPrivateKeyHandle.Companion.generateHpke
> ```

nit: call as `TinkPrivateKeyHandle.generateHpke()` rather than importing the function from the companion object.



_Code quote:_
```Kotlin
import org.wfanet.measurement.common.crypto.tink.TinkPrivateKeyHandle.Companion.generateHpke
```
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/HonestMajorityShareShuffleStarter.kt` line 67 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1513#-NsErKvX0Y2O5HqaLyug:-NsErKvX0Y2O5HqaLyuh:undefined) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f280895a948232f99340a700ac7e8fa3334fb0d7/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/HonestMajorityShareShuffleStarter.kt#L67)):*
> ```Kotlin
>     honestMajorityShareShuffleSetupConfig: HonestMajorityShareShuffleSetupConfig,
>     blobStorageBucket: String,
>     privateKetStorageClient: PrivateKeyStore<TinkKeyId, TinkPrivateKeyHandle>,
> ```





_Suggestion:_
```Kotlin
privateKeyStore
```


<!-- Sent from Reviewable.io -->

2024-03-05 21:53 UTC, SanjayVas requested changes
> Reviewed 26 of 31 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1513)* status: all files reviewed, 9 unresolved discussions (waiting on @ple13 and @renjiezh)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/testing/PrivateKeyClientPlaceholder.kt` line 37 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1513#-NsFZ9ib53NqD_BICyA_:-NsFZ9icD-7-9GYqeG2k:bszpisf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f280895a948232f99340a700ac7e8fa3334fb0d7/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/testing/PrivateKeyClientPlaceholder.kt#L37)):*
> ```Kotlin
>  * @TODO(@renjiez): replace the placeholder with tink key and storage by configuration.
>  */
> object PrivateKeyClientPlaceholder {
> ```

Use TinkKeyStorageProvider instead of making your own placeholder object. You can just pass FakeKmsClient to that.
___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/BUILD.bazel` line 131 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1513#-NsF_Py1-DCP7xIeZQM3:-NsF_Py1-DCP7xIeZQM4:b-1rp7r9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f280895a948232f99340a700ac7e8fa3334fb0d7/src/main/kotlin/org/wfanet/measurement/integration/common/BUILD.bazel#L131)):*
> ```Starlark
> kt_jvm_library(
>     name = "in_process_duchy",
>     testonly = True,  #TODO(@renjiez): delete testonly after removing PrivateKeyClientPlaceholder.
> ```

This is already testonly. See the package declaration.
___
*[`src/main/proto/wfa/measurement/internal/duchy/computations_service.proto` line 97 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1513#-NsF__cpC7Fcg1hwsC81:-NsF__cpC7Fcg1hwsC82:boata4r) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f280895a948232f99340a700ac7e8fa3334fb0d7/src/main/proto/wfa/measurement/internal/duchy/computations_service.proto#L97)):*
> ```proto
>   // The global identifier of the computation,
>   string global_computation_id = 2;
>   // The initial stage of the computation.
> ```

Avoid renumbering fields in messages that are already in use.
___
*[`src/main/proto/wfa/measurement/internal/duchy/config/protocols_setup_config.proto` line 62 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1513#-NsFaW3tBAbXDkExDbbp:-NsFaW3tBAbXDkExDbbq:b-bzcp79) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f280895a948232f99340a700ac7e8fa3334fb0d7/src/main/proto/wfa/measurement/internal/duchy/config/protocols_setup_config.proto#L62)):*
> ```proto
>   //
>   // For HonestMajorityShareShuffle only. This duchy needs to exchange seeds,
>   // add noise, and shuffle. It sends data to the peer non-aggregator secondly.
> ```

I'm not quite understanding the distinction between first and second here.

Additionally, is there any way to pass this information separately so we don't have to add roles that overlap with NON_AGGREGATOR?



_Code quote:_
```proto
It sends data to the peer non-aggregator secondly.
```
___
*[`src/main/proto/wfa/measurement/system/v1alpha/computation.proto` line 171 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1513#-NsF_qYJ6G65cLQ7kX3e:-NsF_qYJ6G65cLQ7kX3f:bumvxo4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f7e13915dc3888089175c08846bc2fc92ae87adb/src/main/proto/wfa/measurement/system/v1alpha/computation.proto#L171)):*
> ```proto
>       // Liquid Legions v2 config.
>       //
>       // May only be set when the measurement type is REACH_AND_FREQUENCY.
> ```

nit: Why remove the comments about valid Measurement types?


<!-- Sent from Reviewable.io -->

2024-03-05 23:08 UTC, renjiezh reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1513)* status: 18 of 31 files reviewed, 7 unresolved discussions (waiting on @ple13, @renjiezh, and @SanjayVas)

___
*[`MODULE.bazel` line 129 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1513#-NsEr8e6BmB5sLc-Nasd:-NsFrmabBlxG6El1gLP1:b-nru59m) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f280895a948232f99340a700ac7e8fa3334fb0d7/MODULE.bazel#L129)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Shouldn't this also depend on the fix for Tink key ID, since it is using PrivateKeyStore?
</blockquote></details>

Working on it.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt` line 78 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1513#-NsEqsqo56_DZLgrjGvV:-NsFf1Hv90vL2F4UhhRy:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f280895a948232f99340a700ac7e8fa3334fb0d7/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt#L78)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

1. "key" is misspelled
2. StorageClient is a different interface
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/HonestMajorityShareShuffleStarter.kt` line 67 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1513#-NsErKvX0Y2O5HqaLyug:-NsFeCD14y8zsjfN97re:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f280895a948232f99340a700ac7e8fa3334fb0d7/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/HonestMajorityShareShuffleStarter.kt#L67)):*
> ```Kotlin
>     honestMajorityShareShuffleSetupConfig: HonestMajorityShareShuffleSetupConfig,
>     blobStorageBucket: String,
>     privateKetStorageClient: PrivateKeyStore<TinkKeyId, TinkPrivateKeyHandle>,
> ```

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/BUILD.bazel` line 131 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1513#-NsF_Py1-DCP7xIeZQM3:-NsFegGI1tc_sIWmG-Vd:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f280895a948232f99340a700ac7e8fa3334fb0d7/src/main/kotlin/org/wfanet/measurement/integration/common/BUILD.bazel#L131)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This is already testonly. See the package declaration.
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/internal/duchy/computations_service.proto` line 97 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1513#-NsF__cpC7Fcg1hwsC81:-NsFeyxe7IWXw0HIgoga:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f280895a948232f99340a700ac7e8fa3334fb0d7/src/main/proto/wfa/measurement/internal/duchy/computations_service.proto#L97)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Avoid renumbering fields in messages that are already in use.
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/internal/duchy/config/protocols_setup_config.proto` line 62 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1513#-NsFaW3tBAbXDkExDbbp:-NsFkWvTBBf0FtZLa-DK:b-uwnsjl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f280895a948232f99340a700ac7e8fa3334fb0d7/src/main/proto/wfa/measurement/internal/duchy/config/protocols_setup_config.proto#L62)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I'm not quite understanding the distinction between first and second here.

Additionally, is there any way to pass this information separately so we don't have to add roles that overlap with NON_AGGREGATOR?
</blockquote></details>

In LLv2, both non-aggregators are doing the same job. The only difference is the order of their execution in the loop. The extra information to differentiate them is the duchy name (or its hash value). 
However, in HMSS, two workers have very different behaviors, especially to serialize the interactive execution of SETUP phase. As there are only two non-aggregators in HMSS, separate their role could make the implementation and debugging easier. 
The only issue is the overlapping regarding the name. I have added comments to emphasize the context. In the config file, there are three roles for llv2, rollv2 and hmss respectively. So they are not really overlapped.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/testing/PrivateKeyClientPlaceholder.kt` line 37 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1513#-NsFZ9ib53NqD_BICyA_:-NsFjWjg8ZIEySVm9-KM:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f280895a948232f99340a700ac7e8fa3334fb0d7/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/testing/PrivateKeyClientPlaceholder.kt#L37)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Use TinkKeyStorageProvider instead of making your own placeholder object. You can just pass FakeKmsClient to that.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-03-06 04:08 UTC, ple13 requested changes
> Reviewed 18 of 31 files at r1, 12 of 13 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1513)* status: 30 of 31 files reviewed, 14 unresolved discussions (waiting on @renjiezh and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/HonestMajorityShareShuffleStarter.kt` line 81 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1513#-NsGnRN43wvUus3Dt8O4:-NsGnRN43wvUus3Dt8O5:b-chkvir) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d3c08789836f541cb19ed4c53a583d6ecb0956d0/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/HonestMajorityShareShuffleStarter.kt#L81)):*
> ```Kotlin
>           participants += systemComputation.computationParticipantsList.map { it.key.duchyId }
>           if (role != RoleInComputation.AGGREGATOR) {
>             commonRandomSeed = generateRandomSeed()
> ```

The name commonRandomSeed could be misleading. It's only a partial random seed at this point.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/HonestMajorityShareShuffleStarter.kt` line 84 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1513#-NsGn5OX3uCulY-f0tmA:-NsGn5OX3uCulY-f0tmB:b4rlm21) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d3c08789836f541cb19ed4c53a583d6ecb0956d0/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/HonestMajorityShareShuffleStarter.kt#L84)):*
> ```Kotlin
> 
>             val privateKeyHandle = TinkPrivateKeyHandle.generateHpke()
>             val privateKeyId = storePrivateKey(privateKetStorageClient, privateKeyHandle)
> ```

Typo on privateKetStorageClient.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/HonestMajorityShareShuffleStarter.kt` line 132 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1513#-NsGpwBCCuq-82o1uqJw:-NsGpwBD5XISfUH2PuTX:bwtqlcl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d3c08789836f541cb19ed4c53a583d6ecb0956d0/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/HonestMajorityShareShuffleStarter.kt#L132)):*
> ```Kotlin
>     @Suppress("WHEN_ENUM_CAN_BE_NULL_IN_JAVA") // Proto enum fields are never null.
>     when (stage) {
>       // Expect WAIT_TO_START for the first non-aggregator duchy.
> ```

We will have both workers to receive requisitions from the edps, right? Or are we only implement the case where just one worker receives them?
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/HonestMajorityShareShuffleStarter.kt` line 147 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1513#-NsGqZ5CELme9moMx5MZ:-NsGqZ5CELme9moMx5M_:b-khk7t2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d3c08789836f541cb19ed4c53a583d6ecb0956d0/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/HonestMajorityShareShuffleStarter.kt#L147)):*
> ```Kotlin
>         error("[id=${token.globalComputationId}]: Computation is not ready to start. stage=$stage.")
>       }
>       // Log and skip for future Stage
> ```

stages



_Code quote:_
```Kotlin
Stage
```
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/db/computation/HonestMajorityShareShuffleProtocol.kt` line 96 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1513#-NsGsiK-01pLP000TWZU:-NsGsiK09D8g_BWJx4H7:b8oc8cg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d3c08789836f541cb19ed4c53a583d6ecb0956d0/src/main/kotlin/org/wfanet/measurement/duchy/db/computation/HonestMajorityShareShuffleProtocol.kt#L96)):*
> ```Kotlin
>         return when (stage) {
>           WAIT_ON_SHUFFLE_INPUT_PHASE_ONE -> details.role == RoleInComputation.FIRST_NON_AGGREGATOR
>           WAIT_TO_START,
> ```

Same about WAIT_TO_START. Should both workers go through this phase to obtain the requisitions?
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/system/v1alpha/ProtoConversions.kt` line 313 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1513#-NsGv5Lx0T-N4IgCrYek:-NsGv5Lx0T-N4IgCrYel:b-qt1lj3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d3c08789836f541cb19ed4c53a583d6ecb0956d0/src/main/kotlin/org/wfanet/measurement/kingdom/service/system/v1alpha/ProtoConversions.kt#L313)):*
> ```Kotlin
>       mpcProtocolConfig {
>         honestMajorityShareShuffle = honestMajorityShareShuffle {
>           sketchParams = shareShuffleSketchParams {
> ```

Missing maximum_frequency?
___
*[`src/main/proto/wfa/measurement/system/v1alpha/computation.proto` line 170 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1513#-NsGwRn21qyTwi3jy_Cr:-NsGwRn21qyTwi3jy_Cs:b5kad6s) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d3c08789836f541cb19ed4c53a583d6ecb0956d0/src/main/proto/wfa/measurement/system/v1alpha/computation.proto#L170)):*
> ```proto
>     message HonestMajorityShareShuffle {
>       // Parameters for HonestMajorityShareShuffle sketch.
>       message ShareShuffleSketchParams {
> ```

Do we need maximum_frequency here?


<!-- Sent from Reviewable.io -->

2024-03-06 18:41 UTC, SanjayVas requested changes
> Reviewed 13 of 13 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1513)* status: all files reviewed, 10 unresolved discussions (waiting on @renjiezh)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/herald/HeraldDaemon.kt` line 147 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1513#-NsK28eKCqAiArD73e_V:-NsK28eKCqAiArD73e_W:b-mn65ak) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d3c08789836f541cb19ed4c53a583d6ecb0956d0/src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/herald/HeraldDaemon.kt#L147)):*
> ```Kotlin
>   // TODO(@renjiez): Use real PrivateKeyStore when enabling HMSS.
>   val keyUri = "fake-kms://kek"
>   val privateKeyHandle = KeysetHandle.generateNew(KeyTemplates.get("AES128_GCM"))
> ```

Even for temporary usage, don't we want to read this KEK from somewhere and write to some actual persistent storage? Otherwise you'll lose all the keys on every restart. Even for simple tests pods can end up restarting.
___
*[`src/main/proto/wfa/measurement/internal/duchy/config/protocols_setup_config.proto` line 62 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1513#-NsFaW3tBAbXDkExDbbp:-NsK39201NJZmPztUv0R:b-d11f8n) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f280895a948232f99340a700ac7e8fa3334fb0d7/src/main/proto/wfa/measurement/internal/duchy/config/protocols_setup_config.proto#L62)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

In LLv2, both non-aggregators are doing the same job. The only difference is the order of their execution in the loop. The extra information to differentiate them is the duchy name (or its hash value). 
However, in HMSS, two workers have very different behaviors, especially to serialize the interactive execution of SETUP phase. As there are only two non-aggregators in HMSS, separate their role could make the implementation and debugging easier. 
The only issue is the overlapping regarding the name. I have added comments to emphasize the context. In the config file, there are three roles for llv2, rollv2 and hmss respectively. So they are not really overlapped.
</blockquote></details>

Can you clarify the first vs. second behavior in the comments here? It's not really clear what "It sends data to the peer non-aggregator secondly." means.
___
*[`src/main/proto/wfa/measurement/system/v1alpha/computation.proto` line 201 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1513#-NsK3MJH14G_siwOv12r:-NsK3MJH14G_siwOv12s:bnz015w) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d3c08789836f541cb19ed4c53a583d6ecb0956d0/src/main/proto/wfa/measurement/system/v1alpha/computation.proto#L201)):*
> ```proto
>       LiquidLegionsV2 reach_only_liquid_legions_v2 = 2;
> 
>       // Honest Majority Share Shuffle config.
> ```

nit: Add comment on valid Measurement types.


<!-- Sent from Reviewable.io -->

2024-03-07 19:36 UTC, renjiezh reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1513)* status: 26 of 31 files reviewed, 8 unresolved discussions (waiting on @ple13 and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/HonestMajorityShareShuffleStarter.kt` line 81 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1513#-NsGnRN43wvUus3Dt8O4:-NsPM1QEDZD0cL0pKuEA:b-ayr9pe) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d3c08789836f541cb19ed4c53a583d6ecb0956d0/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/HonestMajorityShareShuffleStarter.kt#L81)):*
<details><summary><i>Previously, ple13 (Phi) wrote…</i></summary><blockquote>

The name commonRandomSeed could be misleading. It's only a partial random seed at this point.
</blockquote></details>

Done.
Renamed into `random_seed`.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/HonestMajorityShareShuffleStarter.kt` line 132 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1513#-NsGpwBCCuq-82o1uqJw:-NsMKsXr-A_ZpNK6KSJS:b8smltm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d3c08789836f541cb19ed4c53a583d6ecb0956d0/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/HonestMajorityShareShuffleStarter.kt#L132)):*
<details><summary><i>Previously, ple13 (Phi) wrote…</i></summary><blockquote>

We will have both workers to receive requisitions from the edps, right? Or are we only implement the case where just one worker receives them?
</blockquote></details>

Protocol description updated.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/HonestMajorityShareShuffleStarter.kt` line 147 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1513#-NsGqZ5CELme9moMx5MZ:-NsPLlA9DER0pfSgfbOp:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d3c08789836f541cb19ed4c53a583d6ecb0956d0/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/HonestMajorityShareShuffleStarter.kt#L147)):*
<details><summary><i>Previously, ple13 (Phi) wrote…</i></summary><blockquote>

stages
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/db/computation/HonestMajorityShareShuffleProtocol.kt` line 96 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1513#-NsGsiK-01pLP000TWZU:-NsPLmHd5TLwrMEAL3re:b8smltm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d3c08789836f541cb19ed4c53a583d6ecb0956d0/src/main/kotlin/org/wfanet/measurement/duchy/db/computation/HonestMajorityShareShuffleProtocol.kt#L96)):*
<details><summary><i>Previously, ple13 (Phi) wrote…</i></summary><blockquote>

Same about WAIT_TO_START. Should both workers go through this phase to obtain the requisitions?
</blockquote></details>

Protocol description updated.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/herald/HeraldDaemon.kt` line 147 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1513#-NsK28eKCqAiArD73e_V:-NsPNfh94PvTfqznADED:b-ry029p) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d3c08789836f541cb19ed4c53a583d6ecb0956d0/src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/herald/HeraldDaemon.kt#L147)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Even for temporary usage, don't we want to read this KEK from somewhere and write to some actual persistent storage? Otherwise you'll lose all the keys on every restart. Even for simple tests pods can end up restarting.
</blockquote></details>

Yes. It will be done in following PRs which includes binary file, feature flag, and config files to enable HMSS. Here is just a placeholder to make sure it can be compiled for LLv2.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/system/v1alpha/ProtoConversions.kt` line 313 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1513#-NsGv5Lx0T-N4IgCrYek:-NsPM6Q-1X42EdNV9ICf:bgjxy8m) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d3c08789836f541cb19ed4c53a583d6ecb0956d0/src/main/kotlin/org/wfanet/measurement/kingdom/service/system/v1alpha/ProtoConversions.kt#L313)):*
<details><summary><i>Previously, ple13 (Phi) wrote…</i></summary><blockquote>

Missing maximum_frequency?
</blockquote></details>

maximum_frequency can be found in measurement_spec
___
*[`src/main/proto/wfa/measurement/internal/duchy/config/protocols_setup_config.proto` line 62 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1513#-NsFaW3tBAbXDkExDbbp:-NsPMBH_7xjFd6GQeY_9:b-lhpw3w) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f280895a948232f99340a700ac7e8fa3334fb0d7/src/main/proto/wfa/measurement/internal/duchy/config/protocols_setup_config.proto#L62)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Can you clarify the first vs. second behavior in the comments here? It's not really clear what "It sends data to the peer non-aggregator secondly." means.
</blockquote></details>

Protocol description updated. Details of differences between these two roles are explained there. Here I only emphasize that the first non-aggregator starts computing and the second follows.
___
*[`src/main/proto/wfa/measurement/system/v1alpha/computation.proto` line 170 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1513#-NsGwRn21qyTwi3jy_Cr:-NsPKDljBR38jfb7qkpz:bfyg3mg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d3c08789836f541cb19ed4c53a583d6ecb0956d0/src/main/proto/wfa/measurement/system/v1alpha/computation.proto#L170)):*
<details><summary><i>Previously, ple13 (Phi) wrote…</i></summary><blockquote>

Do we need maximum_frequency here?
</blockquote></details>

maximum_frequency can be found in measurement_spec.


<!-- Sent from Reviewable.io -->

2024-03-07 21:34 UTC, ple13 approved these changes
> Reviewed 5 of 5 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1513)* status: all files reviewed, 2 unresolved discussions (waiting on @renjiezh and @SanjayVas)



<!-- Sent from Reviewable.io -->

2024-03-07 22:23 UTC, stevenwarejones reviewed
> Reviewed 15 of 31 files at r1, 9 of 13 files at r3, 5 of 5 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1513)* status: all files reviewed, 3 unresolved discussions (waiting on @renjiezh and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/herald/HeraldDaemon.kt` line 149 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1513#-NsQ-A6V7Qpp2jWRrvPM:-NsQ-A6V7Qpp2jWRrvPN:b-badoe1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fb436c7926a86a61b2227e77531173cc0de8b749/src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/herald/HeraldDaemon.kt#L149)):*
> ```Kotlin
>   val privateKeyHandle = KeysetHandle.generateNew(KeyTemplates.get("AES128_GCM"))
>   val aead = privateKeyHandle.getPrimitive(Aead::class.java)
>   val fakeKmsClient = FakeKmsClient().also { it.setAead(keyUri, aead) }
> ```

can you pull the kmsClient variable out into a private variable that will later be configured by flags you mention above?


<!-- Sent from Reviewable.io -->

2024-03-07 22:43 UTC, renjiezh reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1513)* status: all files reviewed, 3 unresolved discussions (waiting on @SanjayVas and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/herald/HeraldDaemon.kt` line 149 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1513#-NsQ-A6V7Qpp2jWRrvPM:-NsQ2qDN328Y9ghkHTYS:b-6myo5e) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fb436c7926a86a61b2227e77531173cc0de8b749/src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/herald/HeraldDaemon.kt#L149)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

can you pull the kmsClient variable out into a private variable that will later be configured by flags you mention above?
</blockquote></details>

Thanks for the suggestion. `HeraldDeamon` will be refactored into a class in following PRs, which makes this part of code nicer.  Flags will be updated as well. I wonder if we can leave this as a temporary workaround to avoid expansion of this PR. 
The future PR I referred to is the PR adding execution binary and feature flag for HMSS.


<!-- Sent from Reviewable.io -->

2024-03-07 22:58 UTC, renjiezh reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1513)* status: 31 of 32 files reviewed, 3 unresolved discussions (waiting on @ple13, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/herald/HeraldDaemon.kt` line 149 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1513#-NsQ-A6V7Qpp2jWRrvPM:-NsQ7S3T4B20d_e1gQTH:bb9o5j4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fb436c7926a86a61b2227e77531173cc0de8b749/src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/herald/HeraldDaemon.kt#L149)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

Thanks for the suggestion. `HeraldDeamon` will be refactored into a class in following PRs, which makes this part of code nicer.  Flags will be updated as well. I wonder if we can leave this as a temporary workaround to avoid expansion of this PR. 
The future PR I referred to is the PR adding execution binary and feature flag for HMSS.
</blockquote></details>

By the way, this `privateKeyStore` here is just a placeholder before we enable HMSS.


<!-- Sent from Reviewable.io -->

2024-03-08 19:02 UTC, SanjayVas reviewed
> Reviewed 5 of 5 files at r4, 3 of 3 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1513)* status: all files reviewed, 2 unresolved discussions (waiting on @renjiezh and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2024-03-08 20:17 UTC, stevenwarejones approved these changes
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1513)* status: all files reviewed, 2 unresolved discussions (waiting on @renjiezh)



<!-- Sent from Reviewable.io -->

2024-03-08 22:17 UTC, renjiezh reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1513)* status: 29 of 32 files reviewed, 2 unresolved discussions (waiting on @ple13, @SanjayVas, and @stevenwarejones)

___
*[`MODULE.bazel` line 129 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1513#-NsEr8e6BmB5sLc-Nasd:-NsV882_56apBsHzA1EU:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f280895a948232f99340a700ac7e8fa3334fb0d7/MODULE.bazel#L129)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

Working on it.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-03-08 22:27 UTC, SanjayVas approved these changes
> Reviewed 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1513)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)



<!-- Sent from Reviewable.io -->

2024-03-11 12:52 UTC, stevenwarejones approved these changes
> Reviewed 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1513)* status: all files reviewed, 1 unresolved discussion (waiting on @renjiezh)



<!-- Sent from Reviewable.io -->

2024-03-11 17:56 UTC, renjiezh reviewed
> Reviewed 15 of 31 files at r1, 8 of 13 files at r3, 4 of 5 files at r4, 1 of 3 files at r5, 1 of 1 files at r6, 1 of 3 files at r7, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1513)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)



<!-- Sent from Reviewable.io -->

2024-03-11 18:42 UTC, merged