Create Population Data Provider
world-federation-of-advertisers/cross-media-measurement pull request #1527
Opened 2024-03-18 19:27 UTC by jojijac0b

Create Population Data Provider w/ tests

2024-03-18 19:27 UTC, wfa-reviewable commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527)
<!-- Reviewable:end -->

2024-03-19 13:11 UTC, stevenwarejones requested changes
> Reviewed 1 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527)* status: all files reviewed, 9 unresolved discussions (waiting on @jojijac0b)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/PdpSimulator.kt` line 1 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-NtLiQ5-7Uq1Bw1owcEy:-NtLiQ5-7Uq1Bw1owcEz:bb6ht39) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/964ce0e9499d9c7163fb129fed3973f7039fbdad/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/PdpSimulator.kt#L1)):*
> ```Kotlin
> // Copyright 2021 The Cross-Media Measurement Authors
> ```

2024
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/PdpSimulator.kt` line 281 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-NtLl7PpBMiackks6ptu:-NtLl7PpBMiackks6ptv:b-m04wdl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/964ce0e9499d9c7163fb129fed3973f7039fbdad/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/PdpSimulator.kt#L281)):*
> ```Kotlin
>         modelRolloutsStub.listModelRollouts(
>           listModelRolloutsRequest { parent = measurementSpecModelLineName }
>         )
> ```

i don't think this method is guaranteed to return this sorted. You should sort them yourself imo.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/PdpSimulator.kt` line 291 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-NtLlFq64DITXdNfY72G:-NtLlFq64DITXdNfY72H:bwhu077) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/964ce0e9499d9c7163fb129fed3973f7039fbdad/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/PdpSimulator.kt#L291)):*
> ```Kotlin
> 
>     // Retrieves latest ModelRollout from list.
>     val latestModelRollout = listModelRolloutsResponse.modelRolloutsList[0]
> ```

.modelRolloutsList.first()
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/PdpSimulator.kt` line 314 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-NtLm-A40XDJyuUkVxLN:-NtLm-A40XDJyuUkVxLO:bpxm9pd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/964ce0e9499d9c7163fb129fed3973f7039fbdad/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/PdpSimulator.kt#L314)):*
> ```Kotlin
>   ) {
>     // Calculates total sum by running the populationBucketsList through a program that will filter
>     // out irrelevant populations and sum the relevant ones.
> ```

`.... that will sum matching populations` I think is simpler
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/PdpSimulator.kt` line 352 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-NtLnKKy2ZyS25hpZlFH:-NtLnKKy2ZyS25hpZlFI:b-2bd3kx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/964ce0e9499d9c7163fb129fed3973f7039fbdad/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/PdpSimulator.kt#L352)):*
> ```Kotlin
>           // find better way to do this
>           &&
>             Timestamp.parseFrom(it.validStartTime.toByteString()).seconds >=
> ```

this won't work. See the javadocs on DateTime -- https://cloud.google.com/java/docs/reference/proto-google-common-protos/latest/com.google.type.DateTime -- or I think its fine to make both of these Timestamps.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/PdpSimulator.kt` line 354 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-NtLoWdd7vIctqNDXGPW:-NtLoWdd7vIctqNDXGPX:b2givgv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/964ce0e9499d9c7163fb129fed3973f7039fbdad/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/PdpSimulator.kt#L354)):*
> ```Kotlin
>             Timestamp.parseFrom(it.validStartTime.toByteString()).seconds >=
>               requisitionIntervalStartTime.seconds &&
>             Timestamp.parseFrom(it.validEndTime.toByteString()).seconds >=
> ```

there is a scenario where validEndTime is not set (open-ended) - that should return true as well.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/PdpSimulator.kt` line 357 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-NtLmZuq0Ff2SimCqSgr:-NtLmZuq0Ff2SimCqSgs:b-utr2y5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/964ce0e9499d9c7163fb129fed3973f7039fbdad/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/PdpSimulator.kt#L357)):*
> ```Kotlin
>               requisitionIntervalEndTime.seconds
>         }
>         .distinct()
> ```

you should assume they are already distinct.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/PdpSimulator.kt` line 359 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-NtLoyzs8aAOy8K6E65k:-NtLoyzs8aAOy8K6E65l:bh9vwkh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/964ce0e9499d9c7163fb129fed3973f7039fbdad/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/PdpSimulator.kt#L359)):*
> ```Kotlin
>         .distinct()
> 
>     for (populationBucket in validPopulationBucketsList) {
> ```

```
return validPopulationBucketsList.sumBy {
      val program = EventFilters.compileProgram(TestEvent.getDescriptor(), filterExpression)

      // Use program to check if Person field in the PopulationBucket contains the filterExpression.
      if (EventFilters.matches(populationBucket.event, program)) {
        populationBucket.populationSize
      } else {
        0L
      }

}
```

___
*[`src/main/proto/wfa/measurement/api/v2alpha/populations/testing/population_bucket.proto` line 36 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-NtLoNmg4O2OTqTY0qzu:-NtLoNmg4O2OTqTY0qzv:b-1fcwhz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/964ce0e9499d9c7163fb129fed3973f7039fbdad/src/main/proto/wfa/measurement/api/v2alpha/populations/testing/population_bucket.proto#L36)):*
> ```proto
>     (google.api.field_behavior) = UNORDERED_LIST
>   ];
>   google.type.DateTime valid_start_time = 4;
> ```

see my earlier comment - I think its fine to make these Timestamp for convenience


<!-- Sent from Reviewable.io -->

2024-03-19 17:16 UTC, stevenwarejones requested changes
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527)* status: all files reviewed, 4 unresolved discussions (waiting on @jojijac0b)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/PdpSimulator.kt` line 293 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-NtMZ2gP9SwhlXMhRo9V:-NtMZ2gP9SwhlXMhRo9W:b-8cy1tu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ffba8c5210a5b68ee670995e0b75059ad1318d96/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/PdpSimulator.kt#L293)):*
> ```Kotlin
>     val sortedModelRolloutsList =
>       listModelRolloutsResponse.modelRolloutsList.sortedWith { a, b ->
>         Timestamps.compare(a.updateTime, b.updateTime) * -1
> ```

you should use the oneof of `rollout_deploy_period` not `updateTime` here

also, can't you just do listModelRolloutsResponse.modelRolloutsList.sortedWith(TimeStamps.comparator
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/PdpSimulator.kt` line 355 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-NtMhNo92iTGQbBi9Gl-:-NtMhNo92iTGQbBi9Gl0:btjpmul) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ffba8c5210a5b68ee670995e0b75059ad1318d96/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/PdpSimulator.kt#L355)):*
> ```Kotlin
>       populationBucketsList.filter {
>         it.modelReleasesList.contains(modelRelease.name) &&
>           Timestamps.compare(it.validStartTime, requisitionIntervalStartTime) >= 0 &&
> ```

the start time needs to be less than the requisitionIntervalEndTime. the validendTime needs to be null or greater than the validStartTime 


<!-- Sent from Reviewable.io -->

2024-03-25 16:32 UTC, kungfucraig requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527)* status: 2 of 13 files reviewed, 5 unresolved discussions (waiting on @jojijac0b, @SanjayVas, and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/populations/testing/population_bucket.proto` line 27 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-NtqRvhj8wBuizDQybtY:-NtqRvhj8wBuizDQybtZ:b-liet4x) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6d4cbb0d8916877c0319c686ccbfe8329f11bddb/src/main/proto/wfa/measurement/api/v2alpha/populations/testing/population_bucket.proto#L27)):*
> ```proto
> option java_multiple_files = true;
> 
> message PopulationBucket {
> ```

Can we use the population spec in this PR instead? https://github.com/world-federation-of-advertisers/cross-media-measurement-api/pull/206


<!-- Sent from Reviewable.io -->

2024-03-25 17:37 UTC, kungfucraig requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527)* status: 2 of 13 files reviewed, 5 unresolved discussions (waiting on @jojijac0b, @SanjayVas, and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/populations/testing/population_bucket.proto` line 27 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-NtqRvhj8wBuizDQybtY:-NtqfsGZBrxz1X75uunz:binwvkl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6d4cbb0d8916877c0319c686ccbfe8329f11bddb/src/main/proto/wfa/measurement/api/v2alpha/populations/testing/population_bucket.proto#L27)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Can we use the population spec in this PR instead? https://github.com/world-federation-of-advertisers/cross-media-measurement-api/pull/206
</blockquote></details>

After talking with @stevenwarejones I'm going to make some updates to my PR. I'll ping this comment when it's ready. Hopefully later today.


<!-- Sent from Reviewable.io -->

2024-03-25 22:51 UTC, kungfucraig requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527)* status: 2 of 13 files reviewed, 5 unresolved discussions (waiting on @jojijac0b, @SanjayVas, and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/populations/testing/population_bucket.proto` line 27 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-NtqRvhj8wBuizDQybtY:-Ntrnpwl9OrCJI2aNHX9:bw55f8j) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6d4cbb0d8916877c0319c686ccbfe8329f11bddb/src/main/proto/wfa/measurement/api/v2alpha/populations/testing/population_bucket.proto#L27)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

After talking with @stevenwarejones I'm going to make some updates to my PR. I'll ping this comment when it's ready. Hopefully later today.
</blockquote></details>

It's been updated.


<!-- Sent from Reviewable.io -->

2024-03-25 23:34 UTC, SanjayVas requested changes
> Reviewed 1 of 3 files at r3, 2 of 11 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527)* status: 4 of 13 files reviewed, 12 unresolved discussions (waiting on @jojijac0b, @kungfucraig, and @stevenwarejones)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-Ntrs-tb32pUd4PJOmw8:-Ntrs-tb32pUd4PJOmw9:b-p8zf5u) (no related file):*
Check in the root cert and root private key for pdp1 as well.

___
___
*[`src/main/k8s/testing/secretfiles/BUILD.bazel` line 48 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-Ntrs7nz5gQSAt2fUIdU:-Ntrs7nz5gQSAt2fUIdV:by4kjem) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6d4cbb0d8916877c0319c686ccbfe8329f11bddb/src/main/k8s/testing/secretfiles/BUILD.bazel#L48)):*
> ```Starlark
>     srcs = [
>         "aggregator_root.pem",
>         "kingdom_root.pem",
> ```

Add pdp1_root.pem here too, as the MC will need to trust the PDP in order to verify signed results.
___
*[`src/main/k8s/testing/secretfiles/BUILD.bazel` line 217 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-NtrrWWY2WDmLzHPlLDU:-NtrrWWY2WDmLzHPlLDV:b-iscdmo) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6d4cbb0d8916877c0319c686ccbfe8329f11bddb/src/main/k8s/testing/secretfiles/BUILD.bazel#L217)):*
> ```Starlark
>     "pdp1_enc_private.tink",
>     "pdp1_enc_public.tink",
>     "pdp1_result_cs_cert.der",
> ```

You don't need a separate result cert here. Note that the only EDP with a separate result cert is edp1, and that's just for a corresponding test.
___
*[`src/main/k8s/testing/secretfiles/pdp1_cs_cert.der` line 0 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-NtrslMP3CuVJZicEfKr:-NtrslMP3CuVJZicEfKs:b-dixiyq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6d4cbb0d8916877c0319c686ccbfe8329f11bddb/src/main/k8s/testing/secretfiles/pdp1_cs_cert.der#L0)):*
I downloaded and checked and this file looks like it is just a copy of edp1_cs_cert.der. That won't work - each entity must have its own root cert with a unique ID. You'll need to generate a new root cert and key, and then generate all the corresponding certs with 10-year expiration.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/PdpSimulator.kt` line 137 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-NtruCA83-5x9OVcRkFC:-NtruCA83-5x9OVcRkFD:bacg0dv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6d4cbb0d8916877c0319c686ccbfe8329f11bddb/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/PdpSimulator.kt#L137)):*
> ```Kotlin
>     Exception(message, cause)
> 
>   private fun verifySpecifications(
> ```

This function and the supporting data classes appear to be identical to those in EdpSimulator.

Extract common code to a separate library so it can be shared. If need be, this could be an abstract `DataProviderSimulator` base class as EDP and PDP are just two types of Data Providers.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/PdpSimulator.kt` line 226 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-NtrwUEY8HByPV9kS_gN:-NtrwUEY8HByPV9kS_gO:b1t6rbi) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6d4cbb0d8916877c0319c686ccbfe8329f11bddb/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/PdpSimulator.kt#L226)):*
> ```Kotlin
>       try {
>         logger.info("Processing requisition ${requisition.name}...")
> ```

Why was the TODO from the original version of this function from EdpSimulator.kt removed? It still applies here, just with PDP instead of EDP.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/PdpSimulator.kt` line 323 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-Ntrx0xJ1FgF-yJllSMq:-Ntrx0xJ1FgF-yJllSMr:bhqyv4n) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6d4cbb0d8916877c0319c686ccbfe8329f11bddb/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/PdpSimulator.kt#L323)):*
> through a program that will sum matching populations.

What? Is this talking about the CEL program? That doesn't do any aggregation, it's an implementation detail of how the CEL library we're using for filtration.



_Code quote:_
```Kotlin
    // Calculates total sum by running the populationBucketsList through a program that will sum
    // matching populations.
```


<!-- Sent from Reviewable.io -->

2024-03-25 23:35 UTC, SanjayVas commented
Attaching a diff of EdpSimulator.kt to PdpSimulator.kt since it's clear that the latter is based on the former.

[Simulator.patch.txt](https://github.com/world-federation-of-advertisers/cross-media-measurement/files/14750527/Simulator.patch.txt)

2024-03-26 16:20 UTC, stevenwarejones reviewed
> Reviewed 8 of 11 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527)* status: 11 of 13 files reviewed, 12 unresolved discussions (waiting on @jojijac0b, @kungfucraig, and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/PdpSimulator.kt` line 323 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-Ntrx0xJ1FgF-yJllSMq:-NtvRmiHBjyWFEPjpB9F:bkb3axf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6d4cbb0d8916877c0319c686ccbfe8329f11bddb/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/PdpSimulator.kt#L323)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> through a program that will sum matching populations.

What? Is this talking about the CEL program? That doesn't do any aggregation, it's an implementation detail of how the CEL library we're using for filtration.
</blockquote></details>

Maybe `Filters populationBucketsList through a CEL program and sums the result.`


<!-- Sent from Reviewable.io -->

2024-03-27 15:28 UTC, kungfucraig requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527)* status: 11 of 13 files reviewed, 13 unresolved discussions (waiting on @jojijac0b, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/PdpSimulator.kt` line 92 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-Nu-WaxUDAwiYZ0rELyV:-Nu-WaxUDAwiYZ0rELyW:b-jess8v) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6d4cbb0d8916877c0319c686ccbfe8329f11bddb/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/PdpSimulator.kt#L92)):*
> ```Kotlin
> 
> /** A simulator handling PDP businesses. */
> class PdpSimulator(
> ```

Why would the simulator be any different than the production PDP?


<!-- Sent from Reviewable.io -->

2024-04-08 14:17 UTC, jojijac0b reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527)* status: 10 of 13 files reviewed, 13 unresolved discussions (waiting on @kungfucraig, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/PdpSimulator.kt` line 281 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-NtLl7PpBMiackks6ptu:-Nuy0pREBcnZtmRCMYlx:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/964ce0e9499d9c7163fb129fed3973f7039fbdad/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/PdpSimulator.kt#L281)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

i don't think this method is guaranteed to return this sorted. You should sort them yourself imo.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/PdpSimulator.kt` line 359 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-NtLoyzs8aAOy8K6E65k:-Nuy-u7f-VDe4fYyopOD:b-sliyb9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/964ce0e9499d9c7163fb129fed3973f7039fbdad/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/PdpSimulator.kt#L359)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

```
return validPopulationBucketsList.sumBy {
      val program = EventFilters.compileProgram(TestEvent.getDescriptor(), filterExpression)

      // Use program to check if Person field in the PopulationBucket contains the filterExpression.
      if (EventFilters.matches(populationBucket.event, program)) {
        populationBucket.populationSize
      } else {
        0L
      }

}
```

</blockquote></details>

sumBy is deprecated so used sumOf instead
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/PdpSimulator.kt` line 293 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-NtMZ2gP9SwhlXMhRo9V:-Nuy0oD-BuouZl0CJI2D:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ffba8c5210a5b68ee670995e0b75059ad1318d96/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/PdpSimulator.kt#L293)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

you should use the oneof of `rollout_deploy_period` not `updateTime` here

also, can't you just do listModelRolloutsResponse.modelRolloutsList.sortedWith(TimeStamps.comparator
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/PdpSimulator.kt` line 355 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-NtMhNo92iTGQbBi9Gl-:-Nuy0LE54tLFnM_DsGTT:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ffba8c5210a5b68ee670995e0b75059ad1318d96/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/PdpSimulator.kt#L355)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

the start time needs to be less than the requisitionIntervalEndTime. the validendTime needs to be null or greater than the validStartTime
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/PdpSimulator.kt` line 226 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-NtrwUEY8HByPV9kS_gN:-Nuy144v4F50V46zU5tQ:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6d4cbb0d8916877c0319c686ccbfe8329f11bddb/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/PdpSimulator.kt#L226)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Why was the TODO from the original version of this function from EdpSimulator.kt removed? It still applies here, just with PDP instead of EDP.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/PdpSimulator.kt` line 323 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-Ntrx0xJ1FgF-yJllSMq:-Nuy0iqh3tHh5q2ZALq2:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6d4cbb0d8916877c0319c686ccbfe8329f11bddb/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/PdpSimulator.kt#L323)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

Maybe `Filters populationBucketsList through a CEL program and sums the result.`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-04-08 18:30 UTC, SanjayVas reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527)* status: 9 of 18 files reviewed, 11 unresolved discussions (waiting on @jojijac0b, @kungfucraig, and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2024-04-08 22:39 UTC, stevenwarejones requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527)* status: 9 of 18 files reviewed, 13 unresolved discussions (waiting on @jojijac0b, @kungfucraig, and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/populations/testing/population_bucket.proto` line 32 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-Nuzqpg24sc6zFWa3UkW:-Nuzqpg24sc6zFWa3UkX:b-76rgu1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/19907b14a99bc214226938fdeb4dddc495eb774f/src/main/proto/wfa/measurement/api/v2alpha/populations/testing/population_bucket.proto#L32)):*
> ```proto
>   uint64 population_size = 2;
>   // Model Releases for which this population size is valid.
>   repeated string model_releases = 3 [
> ```

since model_releases map to populations, lets just use Population here

https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/7c8702ed832c51fdcc2b22917ee4a91c0fb11377/src/main/proto/wfa/measurement/api/v2alpha/model_release.proto#L44
___
*[`src/main/proto/wfa/measurement/api/v2alpha/populations/testing/population_bucket.proto` line 37 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-NuzrFnG5vJLiyeGXEdy:-NuzrFnG5vJLiyeGXEdz:bsixm7n) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/19907b14a99bc214226938fdeb4dddc495eb774f/src/main/proto/wfa/measurement/api/v2alpha/populations/testing/population_bucket.proto#L37)):*
> ```proto
>   ];
>   google.protobuf.Timestamp valid_start_time = 4;
>   google.protobuf.Timestamp valid_end_time = 5;
> ```

@kungfucraig - I think you mentioned  you thought we didn't need these fields but I can't remember why.


<!-- Sent from Reviewable.io -->

2024-04-10 13:54 UTC, jojijac0b reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527)* status: 9 of 18 files reviewed, 13 unresolved discussions (waiting on @kungfucraig, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/PdpSimulator.kt` line 137 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-NtruCA83-5x9OVcRkFC:-Nv7G-yf-t-Xqi8uMN41:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6d4cbb0d8916877c0319c686ccbfe8329f11bddb/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/PdpSimulator.kt#L137)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This function and the supporting data classes appear to be identical to those in EdpSimulator.

Extract common code to a separate library so it can be shared. If need be, this could be an abstract `DataProviderSimulator` base class as EDP and PDP are just two types of Data Providers.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-04-10 14:05 UTC, jojijac0b reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527)* status: 9 of 18 files reviewed, 13 unresolved discussions (waiting on @kungfucraig, @SanjayVas, and @stevenwarejones)

___
*[`src/main/k8s/testing/secretfiles/pdp1_cs_cert.der` line  at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-NtrslMP3CuVJZicEfKr:-Nv7IxQ_Ab-NH-tgyYMH:b-uqnj3o) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6d4cbb0d8916877c0319c686ccbfe8329f11bddb/src/main/k8s/testing/secretfiles/pdp1_cs_cert.der#L)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I downloaded and checked and this file looks like it is just a copy of edp1_cs_cert.der. That won't work - each entity must have its own root cert with a unique ID. You'll need to generate a new root cert and key, and then generate all the corresponding certs with 10-year expiration.
</blockquote></details>

Can I reuse the edp cs certs and keys for this? Or would you recommend creating new ones for pdp. Is there any drawback to using the edp files?


<!-- Sent from Reviewable.io -->

2024-04-10 17:54 UTC, SanjayVas requested changes
> Reviewed 6 of 11 files at r4, 5 of 8 files at r6, 1 of 3 files at r7, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527)* status: 17 of 18 files reviewed, 14 unresolved discussions (waiting on @jojijac0b, @kungfucraig, and @stevenwarejones)

___
*[`src/main/k8s/testing/secretfiles/pdp1_cs_cert.der` line  at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-NtrslMP3CuVJZicEfKr:-Nv7vHdoDdIMuxqaBGyq:bwxuxv9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6d4cbb0d8916877c0319c686ccbfe8329f11bddb/src/main/k8s/testing/secretfiles/pdp1_cs_cert.der#L)):*
<details><summary><i>Previously, jojijac0b wrote…</i></summary><blockquote>

Can I reuse the edp cs certs and keys for this? Or would you recommend creating new ones for pdp. Is there any drawback to using the edp files?
</blockquote></details>

Each entity must have its own root CA certificate. This is because we map the subject key identifier (SKID) of the root certificate to the entity, for example when authenticating via mTLS.

I believe you could theoretically have an EDP also be a PDP, in which case you'd just reference that EDP's certs directly rather than creating copies. I wouldn't recommend that though as they are more likely to be separate entities in practice (EDPs tend to be ad publishers and PDPs tend to be related to census providers).
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 477 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-Nv83g_lAYd6Wd4KWJxk:-Nv83g_lAYd6Wd4KWJxl:bk0ic7y) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f3b56cfd9044587353caaa450387c54b8a1db226/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L477)):*
> ```Kotlin
>             )
>           }
> ```

Can you put the TODO here that was originally in `verifySpecifications` before that function was moved?

```kotlin
// TODO(@uakyol): Validate that collection interval is not outside of privacy landscape.
```
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/PdpSimulator.kt` line 281 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-NtLl7PpBMiackks6ptu:-Nv85D2R2I3Td1ybOwnZ:bk0g97c) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/964ce0e9499d9c7163fb129fed3973f7039fbdad/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/PdpSimulator.kt#L281)):*
It technically is documented as being returned ordered, but by a field that does not exist in the message. The actual implementation appears to order ascending by either `gradual_rollout_period.start_date` or `instant_rollout_date`, depending on which is set. The API documentation should be fixed accordingly.

> ```protobuf
>   // Lists `ModelRollout`s for a given ModelLine. It returns an sorted list by
>   // rollout_start_time ASC.
> ```

https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/7c8702ed832c51fdcc2b22917ee4a91c0fb11377/src/main/proto/wfa/measurement/api/v2alpha/model_rollouts_service.proto#L39
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/PdpSimulator.kt` line 190 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-Nv88EbU08Or1C14xqF_:-Nv88EbU08Or1C14xqFa:b-4099wz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f3b56cfd9044587353caaa450387c54b8a1db226/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/PdpSimulator.kt#L190)):*
> ```Kotlin
>     val measurementResult =
>       MeasurementKt.result {
>         population = MeasurementKt.ResultKt.population { value = populationSum }
> ```

Also specify the methodology.


<!-- Sent from Reviewable.io -->

2024-04-11 23:42 UTC, SanjayVas requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527)* status: 17 of 18 files reviewed, 15 unresolved discussions (waiting on @jojijac0b, @kungfucraig, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/DataProviderSimulator.kt` line 93 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-NvEXK4FBcBXCEk4KaQG:-NvEXK4FBcBXCEk4KaQH:bsos6nj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f3b56cfd9044587353caaa450387c54b8a1db226/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/DataProviderSimulator.kt#L93)):*
> ```Kotlin
>   /** A sequence of operations done in the simulator. */
>   suspend fun run() {
>     dataProvidersStub.replaceDataAvailabilityInterval(
> ```

This is specific to EDPs and not applicable to PDPs.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/PdpSimulator.kt` line 92 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-Nu-WaxUDAwiYZ0rELyV:-NvEWBT4CIiBnAkufPfW:bz8uxws) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6d4cbb0d8916877c0319c686ccbfe8329f11bddb/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/PdpSimulator.kt#L92)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Why would the simulator be any different than the production PDP?
</blockquote></details>

Good point. @jojijac0b , can you extract out both the shared code and what is currently called the PdpSimulator to a non-test package? Probably rename it to `PdpFulfillmentDaemon` or something.
___
*[`src/main/proto/wfa/measurement/api/v2alpha/populations/testing/population_bucket.proto` line 27 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-NtqRvhj8wBuizDQybtY:-NvEWpKg-eN9MNuTIUJa:bgv5iwm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6d4cbb0d8916877c0319c686ccbfe8329f11bddb/src/main/proto/wfa/measurement/api/v2alpha/populations/testing/population_bucket.proto#L27)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

It's been updated.
</blockquote></details>

Given how long PopulationSpec has been in the API, I agree that this PR should be migrated over to it before merging at this point.


<!-- Sent from Reviewable.io -->

2024-04-18 13:48 UTC, stevenwarejones requested changes
> Reviewed 6 of 8 files at r6, 1 of 3 files at r7, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527)* status: all files reviewed, 13 unresolved discussions (waiting on @jojijac0b, @kungfucraig, and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 191 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-NvlPyKK3rjbjR2esB6Z:-NvlPyKL0BSEAyCvJ62z:bwhcpg5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/baaf158c241f64cac126e23049d949c483a151d8/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L191)):*
> ```Kotlin
> 
>   /** A sequence of operations done in the simulator. */
>   suspend fun run() {
> ```

as Sanjay stated - restore this here
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/PdpSimulator.kt` line 355 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-NtMhNo92iTGQbBi9Gl-:-NvlSa1v8zekjd1XHcUm:b5k1kxg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ffba8c5210a5b68ee670995e0b75059ad1318d96/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/PdpSimulator.kt#L355)):*
<details><summary><i>Previously, jojijac0b wrote…</i></summary><blockquote>

Done.
</blockquote></details>

i don't think we need this logic anymore since we are just mapping populationIds 
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/PdpSimulator.kt` line 55 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-NvlQmgw0sPF3RA-GCfj:-NvlQmgw0sPF3RA-GCfk:bmrkcq1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f3b56cfd9044587353caaa450387c54b8a1db226/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/PdpSimulator.kt#L55)):*
> ```Kotlin
>   private val modelRolloutsStub: ModelRolloutsCoroutineStub,
>   private val modelReleasesStub: ModelReleasesCoroutineStub,
>   private val populationBucketsList: List<PopulationBucket>,
> ```

as discussed, change to
```
: Map<PopulationKey, PopulationSpec>
```

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/PdpSimulator.kt` line 190 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-Nv88EbU08Or1C14xqF_:-NvlS6FN71GpWog8TVtt:b-tfpe2d) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f3b56cfd9044587353caaa450387c54b8a1db226/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/PdpSimulator.kt#L190)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Also specify the methodology.
</blockquote></details>

yeah - just use DeterministicSum
___
*[`src/main/proto/wfa/measurement/api/v2alpha/populations/testing/population_bucket.proto` line 32 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-Nuzqpg24sc6zFWa3UkW:-NvlSndT3drut2pknDUN:b-35d73l) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/19907b14a99bc214226938fdeb4dddc495eb774f/src/main/proto/wfa/measurement/api/v2alpha/populations/testing/population_bucket.proto#L32)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

since model_releases map to populations, lets just use Population here

https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/7c8702ed832c51fdcc2b22917ee4a91c0fb11377/src/main/proto/wfa/measurement/api/v2alpha/model_release.proto#L44
</blockquote></details>

correction: as discussed - just remove this file and use populationSpec instead


<!-- Sent from Reviewable.io -->

2024-05-09 09:40 UTC, jojijac0b reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527)* status: 9 of 19 files reviewed, 13 unresolved discussions (waiting on @kungfucraig, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/DataProviderSimulator.kt` line 93 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-NvEXK4FBcBXCEk4KaQG:-NxIspuC30zZ_owzfatF:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f3b56cfd9044587353caaa450387c54b8a1db226/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/DataProviderSimulator.kt#L93)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This is specific to EDPs and not applicable to PDPs.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 477 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-Nv83g_lAYd6Wd4KWJxk:-NxImRqA3DEWua07AL61:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f3b56cfd9044587353caaa450387c54b8a1db226/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L477)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Can you put the TODO here that was originally in `verifySpecifications` before that function was moved?

```kotlin
// TODO(@uakyol): Validate that collection interval is not outside of privacy landscape.
```
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/api/v2alpha/populations/testing/population_bucket.proto` line 27 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-NtqRvhj8wBuizDQybtY:-NxIuIWjBm6VDL693nGF:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6d4cbb0d8916877c0319c686ccbfe8329f11bddb/src/main/proto/wfa/measurement/api/v2alpha/populations/testing/population_bucket.proto#L27)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Given how long PopulationSpec has been in the API, I agree that this PR should be migrated over to it before merging at this point.
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/api/v2alpha/populations/testing/population_bucket.proto` line 32 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-Nuzqpg24sc6zFWa3UkW:-NxIuJkv5iHyrhe9zOKr:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/19907b14a99bc214226938fdeb4dddc495eb774f/src/main/proto/wfa/measurement/api/v2alpha/populations/testing/population_bucket.proto#L32)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

correction: as discussed - just remove this file and use populationSpec instead
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/PdpSimulator.kt` line 355 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-NtMhNo92iTGQbBi9Gl-:-NxIuGqS432UMegwGG6_:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ffba8c5210a5b68ee670995e0b75059ad1318d96/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/PdpSimulator.kt#L355)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

i don't think we need this logic anymore since we are just mapping populationIds
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/PdpSimulator.kt` line 92 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-Nu-WaxUDAwiYZ0rELyV:-NxRiN0lBNap_axSKYAp:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6d4cbb0d8916877c0319c686ccbfe8329f11bddb/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/PdpSimulator.kt#L92)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Good point. @jojijac0b , can you extract out both the shared code and what is currently called the PdpSimulator to a non-test package? Probably rename it to `PdpFulfillmentDaemon` or something.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/PdpSimulator.kt` line 55 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-NvlQmgw0sPF3RA-GCfj:-NxImQEW2z7CfE3A3AIy:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f3b56cfd9044587353caaa450387c54b8a1db226/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/PdpSimulator.kt#L55)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

as discussed, change to
```
: Map<PopulationKey, PopulationSpec>
```

</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-09 15:14 UTC, kungfucraig requested changes
> Reviewed 5 of 11 files at r4, 2 of 8 files at r6, 1 of 3 files at r7, 1 of 2 files at r8.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527)* status: 9 of 19 files reviewed, 18 unresolved discussions (waiting on @jojijac0b, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/populationdataprovider/daemon/PdpFulfillmentDaemon.kt` line 44 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-NxP4IMv-Oka1_Q-5_29:-NxP4IMv-Oka1_Q-5_2A:bw7nfhs) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/780f181b6797fd0a8ef8addcf4a486026304c8bb/src/main/kotlin/org/wfanet/measurement/populationdataprovider/daemon/PdpFulfillmentDaemon.kt#L44)):*
> ```Kotlin
> import org.wfanet.measurement.loadtest.dataprovider.DataProviderSimulator
> 
> /** A simulator handling PDP businesses. */
> ```

Update the comment.
___
*[`src/main/kotlin/org/wfanet/measurement/populationdataprovider/daemon/PdpFulfillmentDaemon.kt` line 52 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-NxP6A-B0uR9S7zwgFg_:-NxP6A-B0uR9S7zwgFga:bw1a471) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/780f181b6797fd0a8ef8addcf4a486026304c8bb/src/main/kotlin/org/wfanet/measurement/populationdataprovider/daemon/PdpFulfillmentDaemon.kt#L52)):*
> ```Kotlin
>   trustedCertificates: Map<ByteString, X509Certificate>,
>   measurementConsumerName: String,
>   private val populationSpecMap: Map<PopulationKey, PopulationSpec>,
> ```

You may want to run the PopulationSpecs through the PopulationSpecValidator.
___
*[`src/main/kotlin/org/wfanet/measurement/populationdataprovider/daemon/PdpFulfillmentDaemon.kt` line 53 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-NxP5Tv42J2z5zTkZTqD:-NxP5Tv53k5Wm7GzNCcb:bbyhzqp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/780f181b6797fd0a8ef8addcf4a486026304c8bb/src/main/kotlin/org/wfanet/measurement/populationdataprovider/daemon/PdpFulfillmentDaemon.kt#L53)):*
> ```Kotlin
>   measurementConsumerName: String,
>   private val populationSpecMap: Map<PopulationKey, PopulationSpec>,
>   private val populationId: PopulationKey
> ```

Why pass both the map and the populationID when you could pass the PopulationSpec by itself?

Or maybe pass the populationId to one of the functions instead of the constructor?
___
*[`src/main/kotlin/org/wfanet/measurement/populationdataprovider/daemon/PdpFulfillmentDaemon.kt` line 55 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-NxP4s1zBugcgUkWxcvL:-NxP4s1zBugcgUkWxcvM:byjaesv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/780f181b6797fd0a8ef8addcf4a486026304c8bb/src/main/kotlin/org/wfanet/measurement/populationdataprovider/daemon/PdpFulfillmentDaemon.kt#L55)):*
> ```Kotlin
>   private val populationId: PopulationKey
> ) :
>   DataProviderSimulator(
> ```

I don't think you want to inherit simulator for a non-simulator. Perhaps "DataProviderSimulator" needs to be renamed? It's fine for the EDPSimualtor to inherit from a non-simulator base class.
___
*[`src/main/kotlin/org/wfanet/measurement/populationdataprovider/daemon/PdpFulfillmentDaemon.kt` line 180 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-NxSuS0wAkPc_TZagl_O:-NxSuS0wAkPc_TZagl_P:b-jjfsid) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/780f181b6797fd0a8ef8addcf4a486026304c8bb/src/main/kotlin/org/wfanet/measurement/populationdataprovider/daemon/PdpFulfillmentDaemon.kt#L180)):*
> ```Kotlin
>    */
>   private fun isValidAttributesList(attributeList: List<Any>, filterExpression: String): Boolean {
>     val program = EventFilters.compileProgram(TestEvent.getDescriptor(), filterExpression)
> ```

This code should not use TestEvent directly. It needs to interrogate the "Any" and use what is pointed to by that.

You should also add some checks to ensure that all subpopulations are using the same types.


<!-- Sent from Reviewable.io -->

2024-05-09 21:10 UTC, SanjayVas requested changes
> Reviewed 3 of 8 files at r9, 7 of 10 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527)* status: 16 of 19 files reviewed, 20 unresolved discussions (waiting on @jojijac0b and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/BUILD.bazel` line 320 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-NxU9GJ494q2nOWSgj8Y:-NxU9GJ494q2nOWSgj8Z:bx7zgvk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/780f181b6797fd0a8ef8addcf4a486026304c8bb/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/BUILD.bazel#L320)):*
> ```Starlark
> )
> 
> kt_jvm_library(
> ```

This needs to be moved out to some non-testonly package so that the PDP daemon can depend on it.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/DataProviderSimulator.kt` line 156 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-NxU9_ka44yOmNcuTiHz:-NxU9_kbAmQ4Gf9H2RGF:b-9fjgae) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/780f181b6797fd0a8ef8addcf4a486026304c8bb/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/DataProviderSimulator.kt#L156)):*
> ```Kotlin
>     }
> 
>     // TODO(@uakyol): Validate that collection interval is not outside of privacy landscape.
> ```

The TODO is specific to EDPs. Move it to the call site in EdpSimulator.
___
*[`src/main/kotlin/org/wfanet/measurement/populationdataprovider/daemon/BUILD.bazel` line 8 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-NxU98938KkUwJzNq3w-:-NxU98947q6wNRHtxw0_:bh24j74) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/780f181b6797fd0a8ef8addcf4a486026304c8bb/src/main/kotlin/org/wfanet/measurement/populationdataprovider/daemon/BUILD.bazel#L8)):*
> ```Starlark
> 
> package(
>     default_testonly = True,
> ```

This should not be testonly.
___
*[`src/main/kotlin/org/wfanet/measurement/populationdataprovider/daemon/PdpFulfillmentDaemon.kt` line 45 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-NxUAFYH9P1L-OOtLFxv:-NxUAFYH9P1L-OOtLFxw:bkz3ybc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/780f181b6797fd0a8ef8addcf4a486026304c8bb/src/main/kotlin/org/wfanet/measurement/populationdataprovider/daemon/PdpFulfillmentDaemon.kt#L45)):*
> ```Kotlin
> 
> /** A simulator handling PDP businesses. */
> class PdpFulfillmentDaemon(
> ```

nit: By convention, the class ending in "Daemon" should be runnable from the command-line, i.e. have a call to commandLineMain. Maybe call this PopulationRequisitionFulfiller and have another Daemon class as the runner? See the Herald vs. HeraldDaemon split.


<!-- Sent from Reviewable.io -->

2024-05-13 13:59 UTC, jojijac0b reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527)* status: 14 of 20 files reviewed, 20 unresolved discussions (waiting on @SanjayVas and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/BUILD.bazel` line 320 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-NxU9GJ494q2nOWSgj8Y:-NxmE-meBMcq6mi74nuN:bmzpx24) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/780f181b6797fd0a8ef8addcf4a486026304c8bb/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/BUILD.bazel#L320)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This needs to be moved out to some non-testonly package so that the PDP daemon can depend on it.
</blockquote></details>

I set the testonly flag to False for this specific library. Should I still move it to another package?
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/DataProviderSimulator.kt` line 156 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-NxU9_ka44yOmNcuTiHz:-NxmEitzCcsohufZ9K57:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/780f181b6797fd0a8ef8addcf4a486026304c8bb/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/DataProviderSimulator.kt#L156)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The TODO is specific to EDPs. Move it to the call site in EdpSimulator.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/populationdataprovider/daemon/BUILD.bazel` line 8 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-NxU98938KkUwJzNq3w-:-NxmEOtcD-TUeivV-FrY:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/780f181b6797fd0a8ef8addcf4a486026304c8bb/src/main/kotlin/org/wfanet/measurement/populationdataprovider/daemon/BUILD.bazel#L8)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This should not be testonly.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-13 21:04 UTC, SanjayVas requested changes
> Reviewed 2 of 3 files at r11, 2 of 2 files at r12.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527)* status: 15 of 20 files reviewed, 18 unresolved discussions (waiting on @jojijac0b and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/BUILD.bazel` line 320 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-NxU9GJ494q2nOWSgj8Y:-NxnkZDKBwwO9PR0L0Iz:b-72yhxy) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/780f181b6797fd0a8ef8addcf4a486026304c8bb/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/BUILD.bazel#L320)):*
<details><summary><i>Previously, jojijac0b wrote…</i></summary><blockquote>

I set the testonly flag to False for this specific library. Should I still move it to another package?
</blockquote></details>

Yes, as everything under the loadtest package should be testonly.
___
*[`src/main/proto/wfa/measurement/api/v2alpha/event_templates/testing/BUILD.bazel` line 5 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-Nxnl0XFDrqi-KjoAcT7:-Nxnl0XFDrqi-KjoAcT8:bud01i6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/86c7bd73216a5dcb30528664df6b35b5bb1690c4/src/main/proto/wfa/measurement/api/v2alpha/event_templates/testing/BUILD.bazel#L5)):*
> ```Starlark
> 
> package(
>     default_testonly = True,
> ```

Anything in a `testing` package should remain testonly.


<!-- Sent from Reviewable.io -->

2024-05-21 13:46 UTC, jojijac0b reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527)* status: 8 of 21 files reviewed, 18 unresolved discussions (waiting on @kungfucraig, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/BUILD.bazel` line 320 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-NxU9GJ494q2nOWSgj8Y:-NyNR5Np5RC1yjt0ityM:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/780f181b6797fd0a8ef8addcf4a486026304c8bb/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/BUILD.bazel#L320)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Yes, as everything under the loadtest package should be testonly.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 191 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-NvlPyKK3rjbjR2esB6Z:-NyNR3AQ1Ojf9c7z5mBH:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/baaf158c241f64cac126e23049d949c483a151d8/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L191)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

as Sanjay stated - restore this here
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/populationdataprovider/daemon/PdpFulfillmentDaemon.kt` line 44 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-NxP4IMv-Oka1_Q-5_29:-NyNPe6P-RaoP5WMvn2V:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/780f181b6797fd0a8ef8addcf4a486026304c8bb/src/main/kotlin/org/wfanet/measurement/populationdataprovider/daemon/PdpFulfillmentDaemon.kt#L44)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Update the comment.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/populationdataprovider/daemon/PdpFulfillmentDaemon.kt` line 52 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-NxP6A-B0uR9S7zwgFg_:-NyNPla67F8-VPp_DU8R:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/780f181b6797fd0a8ef8addcf4a486026304c8bb/src/main/kotlin/org/wfanet/measurement/populationdataprovider/daemon/PdpFulfillmentDaemon.kt#L52)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

You may want to run the PopulationSpecs through the PopulationSpecValidator.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/populationdataprovider/daemon/PdpFulfillmentDaemon.kt` line 55 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-NxP4s1zBugcgUkWxcvL:-NyM6Zqc4nEEnnnqtEkD:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/780f181b6797fd0a8ef8addcf4a486026304c8bb/src/main/kotlin/org/wfanet/measurement/populationdataprovider/daemon/PdpFulfillmentDaemon.kt#L55)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

I don't think you want to inherit simulator for a non-simulator. Perhaps "DataProviderSimulator" needs to be renamed? It's fine for the EDPSimualtor to inherit from a non-simulator base class.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-21 13:48 UTC, jojijac0b reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527)* status: 8 of 21 files reviewed, 18 unresolved discussions (waiting on @kungfucraig, @SanjayVas, and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/event_templates/testing/BUILD.bazel` line 5 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-Nxnl0XFDrqi-KjoAcT7:-NyQOv4B0T1-iuApHnOG:b-2ys7iv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/86c7bd73216a5dcb30528664df6b35b5bb1690c4/src/main/proto/wfa/measurement/api/v2alpha/event_templates/testing/BUILD.bazel#L5)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Anything in a `testing` package should remain testonly.
</blockquote></details>

I need to check if the attributes in the population spec are of type Person so this is needed in PdpRequisitionFulfiller. How can I use this? Should I move it? 


<!-- Sent from Reviewable.io -->

2024-05-21 19:08 UTC, SanjayVas requested changes
> Reviewed 6 of 11 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527)* status: 14 of 21 files reviewed, 23 unresolved discussions (waiting on @jojijac0b, @kungfucraig, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/InProcessEdpSimulator.kt` line 51 at r14](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-NyRY0pp5FSbpMsGIWaK:-NyRY0pp5FSbpMsGIWaL:bgnz2lx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9337ba0de65f9d7126c2695140997a8ea713a61f/src/main/kotlin/org/wfanet/measurement/integration/common/InProcessEdpSimulator.kt#L51)):*
> ```Kotlin
> import org.wfanet.measurement.eventdataprovider.privacybudgetmanagement.PrivacyBudgetManager
> import org.wfanet.measurement.eventdataprovider.privacybudgetmanagement.testing.TestPrivacyBucketMapper
> import org.wfanet.measurement.populationdataprovider.DataProviderData
> ```

Why is this Event DataProvider simulator depending on something from a Population DataProvider package?
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/BUILD.bazel` line 136 at r14](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-NyRWG5s4B5YtgOImHnA:-NyRWG5s4B5YtgOImHnB:bcwufrg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9337ba0de65f9d7126c2695140997a8ea713a61f/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/BUILD.bazel#L136)):*
> ```Starlark
>     name = "measurement_results",
>     srcs = ["MeasurementResults.kt"],
>     testonly = False,
> ```

This must be testonly, or else it needs to be moved to another package.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorRunner.kt` line 38 at r14](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-NyRYEQMBJ0tmFzV7Zv7:-NyRYEQMBJ0tmFzV7Zv8:b-di0oiu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9337ba0de65f9d7126c2695140997a8ea713a61f/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorRunner.kt#L38)):*
> ```Kotlin
> import org.wfanet.measurement.common.throttler.MinimumIntervalThrottler
> import org.wfanet.measurement.loadtest.config.PrivacyBudgets.createNoOpPrivacyBudgetManager
> import org.wfanet.measurement.populationdataprovider.DataProviderData
> ```

Same here re: Event DataProvider code depending on something from a Population DataProvider package.
___
*[`src/main/proto/wfa/measurement/api/v2alpha/event_templates/testing/BUILD.bazel` line 5 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-Nxnl0XFDrqi-KjoAcT7:-NyRWORy3EIGPDzQzztR:b8abf2n) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/86c7bd73216a5dcb30528664df6b35b5bb1690c4/src/main/proto/wfa/measurement/api/v2alpha/event_templates/testing/BUILD.bazel#L5)):*
> I need to check if the attributes in the population spec are of type Person

You in fact do not need to do this. The population requisition fulfiller must work for *any* event template types. This is why we use fields of type `Any`. The types are not known until runtime and are controlled by passing in the appropriate FileDescriptorSet via a command-line option. See Craig's comment about not referencing TestEvent directly.

These are all *test* messages and should only be used in *tests*.
___
*[`src/main/kotlin/org/wfanet/measurement/populationdataprovider/DataProviderRequisitionFulfiller.kt` line 15 at r14](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-NyRYNRLCBFQm5PiTUQj:-NyRYNRLCBFQm5PiTUQk:bi7x4o9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9337ba0de65f9d7126c2695140997a8ea713a61f/src/main/kotlin/org/wfanet/measurement/populationdataprovider/DataProviderRequisitionFulfiller.kt#L15)):*
> ```Kotlin
> // limitations under the License.
> 
> package org.wfanet.measurement.populationdataprovider
> ```

Isn't this the base class for both Event and Population? If so, it shouldn't be in the Population package.
___
*[`src/main/kotlin/org/wfanet/measurement/populationdataprovider/DataProviderRequisitionFulfiller.kt` line 71 at r14](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-NyRXWoM8x495McaL--v:-NyRXWoM8x495McaL--w:bhfguav) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9337ba0de65f9d7126c2695140997a8ea713a61f/src/main/kotlin/org/wfanet/measurement/populationdataprovider/DataProviderRequisitionFulfiller.kt#L71)):*
> ```Kotlin
> )
> 
> abstract class DataProviderRequisitionFulfiller(
> ```

nit: maybe just `RequisitionFulfiller`, since only DataProviders can fulfill Requisitions?



_Suggestion:_
```Kotlin
RequisitionFulfiller
```
___
*[`src/main/kotlin/org/wfanet/measurement/populationdataprovider/PdpRequisitionFulfiller.kt` line 46 at r14](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-NyRXfyx6XXu_pgQStq6:-NyRXfyx6XXu_pgQStq7:bmmok59) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9337ba0de65f9d7126c2695140997a8ea713a61f/src/main/kotlin/org/wfanet/measurement/populationdataprovider/PdpRequisitionFulfiller.kt#L46)):*
> ```Kotlin
> 
> /** A requisition fulfiller for PDP businesses. */
> class PdpRequisitionFulfiller(
> ```

nit: maybe PopulationRequisitionFulfiller, to indicate which types of requisitions are being fulfilled?



_Suggestion:_
```Kotlin
PopulationRequisitionFulfiller
```


<!-- Sent from Reviewable.io -->

2024-05-22 13:51 UTC, stevenwarejones requested changes
> Reviewed 3 of 8 files at r9, 3 of 10 files at r10, 1 of 3 files at r11, 10 of 11 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527)* status: 20 of 21 files reviewed, 23 unresolved discussions (waiting on @jojijac0b, @kungfucraig, and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/populationdataprovider/PdpRequisitionFulfiller.kt` line 112 at r14](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-NyVYRco7cdHpoQA_0KX:-NyVYRco7cdHpoQA_0KY:bq8l0wt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9337ba0de65f9d7126c2695140997a8ea713a61f/src/main/kotlin/org/wfanet/measurement/populationdataprovider/PdpRequisitionFulfiller.kt#L112)):*
> ```Kotlin
> 
>         val populationSpec = populationSpecMap.getValue(populationId)
>         val populationSpecValidator = PopulationSpecValidator.validateVidRangesList(populationSpec)
> ```

you should also validate that all the population fields are set here
___
*[`src/main/kotlin/org/wfanet/measurement/populationdataprovider/PdpRequisitionFulfiller.kt` line 168 at r14](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-NyVYq-J6sTia-ckUzRG:-NyVYq-J6sTia-ckUzRH:b-n7omyh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9337ba0de65f9d7126c2695140997a8ea713a61f/src/main/kotlin/org/wfanet/measurement/populationdataprovider/PdpRequisitionFulfiller.kt#L168)):*
> ```Kotlin
>       val attributesList = it.attributesList
>       val vidRanges = it.vidRangesList
>       val shouldSumPopulation = isValidAttributesList(attributesList, filterExpression)
> ```

you should be populating your testEvent proto with all these population and then filtering  
___
*[`src/main/kotlin/org/wfanet/measurement/populationdataprovider/daemon/PdpFulfillmentDaemon.kt` line 180 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-NxSuS0wAkPc_TZagl_O:-NyVZ3lH5uqs3ofb0-ka:b-ivfo4u) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/780f181b6797fd0a8ef8addcf4a486026304c8bb/src/main/kotlin/org/wfanet/measurement/populationdataprovider/daemon/PdpFulfillmentDaemon.kt#L180)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

This code should not use TestEvent directly. It needs to interrogate the "Any" and use what is pointed to by that.

You should also add some checks to ensure that all subpopulations are using the same types.
</blockquote></details>

yes, add it to the key on your PopulationId map since event population may map to different Event protos


<!-- Sent from Reviewable.io -->

2024-05-23 14:24 UTC, jojijac0b reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527)* status: 10 of 22 files reviewed, 20 unresolved discussions (waiting on @kungfucraig, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/InProcessEdpSimulator.kt` line 51 at r14](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-NyRY0pp5FSbpMsGIWaK:-Ny_iMBJ0L1BvAmYTbmn:b-5s3lln) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9337ba0de65f9d7126c2695140997a8ea713a61f/src/main/kotlin/org/wfanet/measurement/integration/common/InProcessEdpSimulator.kt#L51)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Why is this Event DataProvider simulator depending on something from a Population DataProvider package?
</blockquote></details>

Moved RequisitionFulfiller(fka DataProviderRequisitionFulfiller), which contains DataProviderData, to its own dataprovider package.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/BUILD.bazel` line 136 at r14](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-NyRWG5s4B5YtgOImHnA:-Ny__GRLD0onMinZArje:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9337ba0de65f9d7126c2695140997a8ea713a61f/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/BUILD.bazel#L136)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This must be testonly, or else it needs to be moved to another package.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorRunner.kt` line 38 at r14](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-NyRYEQMBJ0tmFzV7Zv7:-Ny_idm34szLS0wg9KJw:b-5s3lln) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9337ba0de65f9d7126c2695140997a8ea713a61f/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorRunner.kt#L38)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Same here re: Event DataProvider code depending on something from a Population DataProvider package.
</blockquote></details>

Moved RequisitionFulfiller(fka DataProviderRequisitionFulfiller), which contains DataProviderData, to its own dataprovider package.
___
*[`src/main/proto/wfa/measurement/api/v2alpha/event_templates/testing/BUILD.bazel` line 5 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-Nxnl0XFDrqi-KjoAcT7:-Ny_p0Ze9pCehXUPwv1D:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/86c7bd73216a5dcb30528664df6b35b5bb1690c4/src/main/proto/wfa/measurement/api/v2alpha/event_templates/testing/BUILD.bazel#L5)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> I need to check if the attributes in the population spec are of type Person

You in fact do not need to do this. The population requisition fulfiller must work for *any* event template types. This is why we use fields of type `Any`. The types are not known until runtime and are controlled by passing in the appropriate FileDescriptorSet via a command-line option. See Craig's comment about not referencing TestEvent directly.

These are all *test* messages and should only be used in *tests*.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/populationdataprovider/DataProviderRequisitionFulfiller.kt` line 15 at r14](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-NyRYNRLCBFQm5PiTUQj:-Ny_ifYL-XyBvlEVYbfa:b-5s3lln) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9337ba0de65f9d7126c2695140997a8ea713a61f/src/main/kotlin/org/wfanet/measurement/populationdataprovider/DataProviderRequisitionFulfiller.kt#L15)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Isn't this the base class for both Event and Population? If so, it shouldn't be in the Population package.
</blockquote></details>

Moved RequisitionFulfiller(fka DataProviderRequisitionFulfiller), which contains DataProviderData, to its own dataprovider package.
___
*[`src/main/kotlin/org/wfanet/measurement/populationdataprovider/daemon/PdpFulfillmentDaemon.kt` line 53 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-NxP5Tv42J2z5zTkZTqD:-Ny_oVSQ-1pgGS1Lh9kp:b-1n9hgv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/780f181b6797fd0a8ef8addcf4a486026304c8bb/src/main/kotlin/org/wfanet/measurement/populationdataprovider/daemon/PdpFulfillmentDaemon.kt#L53)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Why pass both the map and the populationID when you could pass the PopulationSpec by itself?

Or maybe pass the populationId to one of the functions instead of the constructor?
</blockquote></details>

Getting the population from the model release of the model line's(provided by the measurement spec) latest model rollout.


<!-- Sent from Reviewable.io -->

2024-05-23 15:29 UTC, stevenwarejones requested changes
> Reviewed 1 of 6 files at r15, 11 of 11 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527)* status: all files reviewed, 30 unresolved discussions (waiting on @jojijac0b, @kungfucraig, and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfiller.kt` line 68 at r16](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-Ny_yfSAAowGJI5aBxQs:-Ny_yfSAAowGJI5aBxQt:b-nyzzyi) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c6494be790d4d4aefe346a0f2523d379125d0b96/src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfiller.kt#L68)):*
> ```Kotlin
>   private val modelRolloutsStub: ModelRolloutsCoroutineStub,
>   private val modelReleasesStub: ModelReleasesCoroutineStub,
>   private val populationSpecMap: Map<PopulationKey, PopulationInfo>,
> ```

nit: rename `populationSpecMap` to `populationInfoMap`
___
*[`src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfiller.kt` line 126 at r16](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-Ny_ypyL76tiNPLf6SRn:-Ny_ypyL76tiNPLf6SRo:b-165xvb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c6494be790d4d4aefe346a0f2523d379125d0b96/src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfiller.kt#L126)):*
> ```Kotlin
>         val modelRelease = getModelRelease(measurementSpec)
> 
>         val populationId = PopulationKey.fromName(modelRelease.population)
> ```

combine this and the next line
```
val populationKey = requireNotNull(...) {
  ...
}
```

___
*[`src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfiller.kt` line 179 at r16](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-Ny_zEi42EluWgkUF_St:-Ny_zEi42EluWgkUF_Su:b-4143pn) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c6494be790d4d4aefe346a0f2523d379125d0b96/src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfiller.kt#L179)):*
> ```Kotlin
> 
>     // Sort list of ModelRollouts by descending updateTime.
>     val sortedModelRolloutsList =
> ```

@marco-premier - can you take a look at this logic?
___
*[`src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfiller.kt` line 264 at r16](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-Nya3GIp0FaRUWm_9lI9:-Nya3GIp0FaRUWm_9lIA:bpw6kht) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c6494be790d4d4aefe346a0f2523d379125d0b96/src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfiller.kt#L264)):*
> ```Kotlin
> 
>       // Ensure attribute is a field in the event descriptor.
>       if(!isAttributeFieldInEvent(attributeMessage, eventDescriptor)){
> ```

you can just use require for these to
___
*[`src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfiller.kt` line 265 at r16](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-Nya3MtVBFLWK4tYbSJ3:-Nya3MtVBFLWK4tYbSJ4:bphdvbu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c6494be790d4d4aefe346a0f2523d379125d0b96/src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfiller.kt#L265)):*
> ```Kotlin
>       // Ensure attribute is a field in the event descriptor.
>       if(!isAttributeFieldInEvent(attributeMessage, eventDescriptor)){
>         throw InvalidSpecException("Attribute is not part of Event Descriptor")
> ```

can you add a test that throws this error
___
*[`src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfiller.kt` line 270 at r16](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-Nya3PGrEwLUvKJqpQCd:-Nya3PGrEwLUvKJqpQCe:bphdvbu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c6494be790d4d4aefe346a0f2523d379125d0b96/src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfiller.kt#L270)):*
> ```Kotlin
>       // Validate attribute message with descriptor from type registry.
>       if(!isValidAttribute(attributeMessage, attributeDescriptor)){
>         throw InvalidSpecException("Invalid Subpopulation Attribute")
> ```

can you add a test that throws this error
___
*[`src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfiller.kt` line 310 at r16](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-Nya-1oi3RpcWS8isk_f:-Nya-1oj6SXSOAXk2eJo:bus2wue) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c6494be790d4d4aefe346a0f2523d379125d0b96/src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfiller.kt#L310)):*
> ```Kotlin
> 
>   private fun createAttributeMessage(attribute: Any, attributeDescriptor: Descriptor): Message {
>     val attributeMessage = DynamicMessage.parseFrom(attributeDescriptor, attribute.toByteString()).toBuilder()
> ```

See my other comment. You don't need a builder. Also, you should reading the value field of the Any
```
val attributeMessage = DynamicMessage.parseFrom(attributeDescriptor, attribute.value)
```

___
*[`src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfiller.kt` line 313 at r16](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-Nya-_Gd9MvSO5ai0k8H:-Nya-_Gd9MvSO5ai0k8I:b-3uciw1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c6494be790d4d4aefe346a0f2523d379125d0b96/src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfiller.kt#L313)):*
> ```Kotlin
> 
>     attributeDescriptor.fields.forEach {
>       attributeMessage.setField(it, attribute.unpackSameTypeAs(attributeMessage.build()).getField(it))
> ```

instead of setting the fields here, they should already all be set when you unpack. Instead, here, you should be validating that all the population fields are set.
___
*[`src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfiller.kt` line 316 at r16](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-Nya163uEZW_CWcpEep4:-Nya163uEZW_CWcpEep5:b-6oapnv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c6494be790d4d4aefe346a0f2523d379125d0b96/src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfiller.kt#L316)):*
> ```Kotlin
>     }
> 
>     return attributeMessage.build()
> ```

no need to build.
___
*[`src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/PdpSimulatorTest.kt` line 322 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-Nya28MoCONhV3rCr08N:-Nya28MoCONhV3rCr08O:bq6ygde) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/19907b14a99bc214226938fdeb4dddc495eb774f/src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/PdpSimulatorTest.kt#L322)):*
> ```Kotlin
>           RequisitionSpecKt.population {
>             filter = eventFilter { expression = "person.gender == ${Person.Gender.MALE_VALUE}" }
>             interval = interval {
> ```

we should have a test with an invalid interval (ie there is no modelRelease for that range) or at least one that maps to a population id.
___
*[`src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/PopulationRequisitionFul [...]

2024-05-23 18:41 UTC, SanjayVas reviewed
> Reviewed 1 of 10 files at r10, 1 of 11 files at r14, 1 of 6 files at r15, 8 of 11 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527)* status: all files reviewed, 25 unresolved discussions (waiting on @jojijac0b and @kungfucraig)



<!-- Sent from Reviewable.io -->

2024-05-30 19:37 UTC, stevenwarejones requested changes
> Reviewed 3 of 5 files at r17, 2 of 3 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527)* status: 22 of 23 files reviewed, 17 unresolved discussions (waiting on @jojijac0b, @kungfucraig, and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfiller.kt` line 60 at r18](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-Nz9u1-a1FkjbVTKts-v:-Nz9u1-a1FkjbVTKts-w:b-94lsnv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/df34e9c3eff8ff381dc29c411ba42a328dd03d92/src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfiller.kt#L60)):*
> ```Kotlin
>   val eventDescriptor: Descriptor,
>   val typeRegistry: TypeRegistry,
>   val attributeClassMap: Map<String, Class<Message>>,
> ```

@SanjayVas - is there a way to derive the Class of the Message from the TypeRegistry? I didnt' see any methods that could do that.
___
*[`src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfiller.kt` line 213 at r18](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-Nz9z9D67LIblJS1DZQQ:-Nz9z9D67LIblJS1DZQR:bwu0xo8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/df34e9c3eff8ff381dc29c411ba42a328dd03d92/src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfiller.kt#L213)):*
> ```Kotlin
> 
>     // CEL program that will check the event against the filter expression
>     val program = EventFilters.compileProgram(populationInfo.eventDescriptor, filterExpression)
> ```

I was thinking we would use the same filter as for event filtering. I would think we'd need to pass in the operativeFields here
```
val program = EventFilters.compileProgram(populationInfo.eventDescriptor, filterExpression, operativeFields)
```
For now, you could just have the operativeFields in the PopulationInfo data class since there is one set per event template.
```
val operativeFields = listOf("person.ageGroup.value", person.socialGradeGroup.value", "person.genderGroup.value")
```
Add add a test with a filter that includes non-operative fields
```
person.gender == ${Person.Gender.FEMALE_VALUE} && other_field.value == other_value"
```

___
*[`src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfiller.kt` line 261 at r18](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-Nz9uXXHBP66sQS1-mpY:-Nz9uXXHBP66sQS1-mpZ:bxyrlb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/df34e9c3eff8ff381dc29c411ba42a328dd03d92/src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfiller.kt#L261)):*
> ```Kotlin
> 
>       // If the attribute type is not a field in the event message, it is not valid.
>       val isAttributeFieldInEvent = eventDescriptor.fields.any {
> ```

do you need this check since later on you are doing
```
      val fieldDescriptor = eventDescriptor.fields.first {eventField ->
        eventField.messageType.name === attributeDescriptor.name
      }
```

___
*[`src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfiller.kt` line 270 at r18](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-Nz9w4Uc9echbHVMSvsU:-Nz9w4Uc9echbHVMSvsV:b4q72xi) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/df34e9c3eff8ff381dc29c411ba42a328dd03d92/src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfiller.kt#L270)):*
> ```Kotlin
> 
>       // If the population_attribute option in the attribute message is set to true, we do not allow the value to be unspecified.
>       val isValidAttribute = attributeMessage.allFields.keys.containsAll(requiredAttributes)
> ```

again, you can just wrap this in a require.

However, I don't think this actually will find if the fields are set since any unspecified fields will be included here, right? At least that's how I thought it worked.

Instead, I would iterate through all the fields and if any field has the default value, then throw an error.

Not sure how your test is passing here.


<!-- Sent from Reviewable.io -->

2024-05-31 09:24 UTC, Marco-Premier requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527)* status: 22 of 23 files reviewed, 18 unresolved discussions (waiting on @jojijac0b, @kungfucraig, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfiller.kt` line 162 at r18](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-NzCsfyR3OD9w-I89AVH:-NzCsfyR3OD9w-I89AVI:b-2vx1i6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/df34e9c3eff8ff381dc29c411ba42a328dd03d92/src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfiller.kt#L162)):*
> ```Kotlin
>    */
>   private suspend fun getModelRelease(measurementSpec: MeasurementSpec): ModelRelease {
>     val measurementSpecModelLineName = measurementSpec.modelLine
> ```

Does this ```measurementSpec.modelLine``` consider model_outages already?
Not sure if this is the case @stevenwarejones @SanjayVas  but if a measurement spans across one or more model outage, the whole report should use the HoldbackModelLine so I believe also population data should reflect this accordingly?
Check:
1) comments here: https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/main/src/main/proto/wfa/measurement/api/v2alpha/model_line.proto#L88 
2) ```message ModelOutage``` section here: https://docs.google.com/document/d/1tzzcO00za4Fo9eeofEBZuEgdTkES9saMN2y4WUaGXjs/edit



_Code quote:_
```Kotlin
val measurementSpecModelLineName = measurementSpec.modelLine
```


<!-- Sent from Reviewable.io -->

2024-05-31 17:12 UTC, jojijac0b reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527)* status: 22 of 23 files reviewed, 18 unresolved discussions (waiting on @kungfucraig, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfiller.kt` line 265 at r16](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-Nya3MtVBFLWK4tYbSJ3:-Nz6Oa_-7Uv1XBdCab5w:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c6494be790d4d4aefe346a0f2523d379125d0b96/src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfiller.kt#L265)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

can you add a test that throws this error
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfiller.kt` line 270 at r16](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-Nya3PGrEwLUvKJqpQCd:-Nz6OhpiCho0D9BdD68z:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c6494be790d4d4aefe346a0f2523d379125d0b96/src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfiller.kt#L270)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

can you add a test that throws this error
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfiller.kt` line 270 at r18](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-Nz9w4Uc9echbHVMSvsU:-NzEc_KzEnMcx-HS5UmA:bfbcxt0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/df34e9c3eff8ff381dc29c411ba42a328dd03d92/src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfiller.kt#L270)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

again, you can just wrap this in a require.

However, I don't think this actually will find if the fields are set since any unspecified fields will be included here, right? At least that's how I thought it worked.

Instead, I would iterate through all the fields and if any field has the default value, then throw an error.

Not sure how your test is passing here.
</blockquote></details>

When I tested, if the field is unspecified(enum value 0), the field is not populated in the message. So this will just check to ensure all the fields are set.


<!-- Sent from Reviewable.io -->

2024-05-31 19:47 UTC, stevenwarejones reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527)* status: 22 of 23 files reviewed, 15 unresolved discussions (waiting on @jojijac0b, @kungfucraig, and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfiller.kt` line 270 at r18](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-Nz9w4Uc9echbHVMSvsU:-NzFBJc3EkKwpYiOWl_M:b-wmvsyz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/df34e9c3eff8ff381dc29c411ba42a328dd03d92/src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfiller.kt#L270)):*
<details><summary><i>Previously, jojijac0b wrote…</i></summary><blockquote>

When I tested, if the field is unspecified(enum value 0), the field is not populated in the message. So this will just check to ensure all the fields are set.
</blockquote></details>

@SanjayVas 


<!-- Sent from Reviewable.io -->

2024-06-04 18:43 UTC, jojijac0b reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527)* status: 21 of 23 files reviewed, 15 unresolved discussions (waiting on @kungfucraig, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfiller.kt` line 213 at r18](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-Nz9z9D67LIblJS1DZQQ:-NzZSlWk4IuYbWcYb6RR:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/df34e9c3eff8ff381dc29c411ba42a328dd03d92/src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfiller.kt#L213)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

I was thinking we would use the same filter as for event filtering. I would think we'd need to pass in the operativeFields here
```
val program = EventFilters.compileProgram(populationInfo.eventDescriptor, filterExpression, operativeFields)
```
For now, you could just have the operativeFields in the PopulationInfo data class since there is one set per event template.
```
val operativeFields = listOf("person.ageGroup.value", person.socialGradeGroup.value", "person.genderGroup.value")
```
Add add a test with a filter that includes non-operative fields
```
person.gender == ${Person.Gender.FEMALE_VALUE} && other_field.value == other_value"
```

</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfiller.kt` line 261 at r18](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-Nz9uXXHBP66sQS1-mpY:-NzZRkCQ8nNsWkLuaY8w:bhdo0aq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/df34e9c3eff8ff381dc29c411ba42a328dd03d92/src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfiller.kt#L261)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

do you need this check since later on you are doing
```
      val fieldDescriptor = eventDescriptor.fields.first {eventField ->
        eventField.messageType.name === attributeDescriptor.name
      }
```

</blockquote></details>

This is to ensure the message type of the attribute is a valid field in the event message. The second check is to ensure that the message type itself is valid. This will handle the case when an attribute is valid, but it is not compatible with the event type specified by the event descriptor in PopulationInfo. If this is an edge case that will never happen, I can remove.


<!-- Sent from Reviewable.io -->

2024-06-05 20:20 UTC, jojijac0b reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527)* status: 18 of 25 files reviewed, 15 unresolved discussions (waiting on @kungfucraig, @SanjayVas, and @stevenwarejones)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-Ntrs-tb32pUd4PJOmw8:-Nze2gDb1hzFF-4KtMhu:b-896fix) (no related file):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Check in the root cert and root private key for pdp1 as well.
</blockquote></details>

Done.

___
___
*[`src/main/k8s/testing/secretfiles/BUILD.bazel` line 48 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-Ntrs7nz5gQSAt2fUIdU:-Nze2eVF93Rj5_fDL3m8:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6d4cbb0d8916877c0319c686ccbfe8329f11bddb/src/main/k8s/testing/secretfiles/BUILD.bazel#L48)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Add pdp1_root.pem here too, as the MC will need to trust the PDP in order to verify signed results.
</blockquote></details>

Done.
___
*[`src/main/k8s/testing/secretfiles/BUILD.bazel` line 217 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-NtrrWWY2WDmLzHPlLDU:-Nze2i4gB-6faGBQOtd0:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6d4cbb0d8916877c0319c686ccbfe8329f11bddb/src/main/k8s/testing/secretfiles/BUILD.bazel#L217)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

You don't need a separate result cert here. Note that the only EDP with a separate result cert is edp1, and that's just for a corresponding test.
</blockquote></details>

Done.
___
*[`src/main/k8s/testing/secretfiles/pdp1_cs_cert.der` line  at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-NtrslMP3CuVJZicEfKr:-Nze2jRC0QkOY4L9wvZb:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6d4cbb0d8916877c0319c686ccbfe8329f11bddb/src/main/k8s/testing/secretfiles/pdp1_cs_cert.der#L)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Each entity must have its own root CA certificate. This is because we map the subject key identifier (SKID) of the root certificate to the entity, for example when authenticating via mTLS.

I believe you could theoretically have an EDP also be a PDP, in which case you'd just reference that EDP's certs directly rather than creating copies. I wouldn't recommend that though as they are more likely to be separate entities in practice (EDPs tend to be ad publishers and PDPs tend to be related to census providers).
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-06-06 12:53 UTC, stevenwarejones reviewed
> Reviewed 3 of 5 files at r20, 7 of 7 files at r21, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527)* status: 24 of 25 files reviewed, 13 unresolved discussions (waiting on @jojijac0b, @kungfucraig, and @SanjayVas)

___
*[`src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/PopulationRequisitionFulfillerTest.kt` line 623 at r20](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-Nze3ToLC9M66W-L_Qn1:-Nzhb0U_3zudoi6UL6UU:b2yy3g1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/92e00a3d7d29fc4c11ee2bf31b6838470fd6779c/src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/PopulationRequisitionFulfillerTest.kt#L623)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

can you add a test with a field not in the attributes list and ignored since its not one of the operative fields?
```
filter = eventFilter { expression = "person.gender == ${Person.Gender.FEMALE_VALUE} && abc == xyz" }
```

</blockquote></details>

for clarification, this would be a copy of a valid test that returns a result with extra fields in the expression that are ignored since they aren't operative fields


<!-- Sent from Reviewable.io -->

2024-06-06 15:28 UTC, kungfucraig reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527)* status: 24 of 25 files reviewed, 12 unresolved discussions (waiting on @jojijac0b, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfiller.kt` line 133 at r16](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-NyfXv1kBuNa0d_BJk3C:-Nzi9IOh-SorKhsA9vg9:b3db75o) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c6494be790d4d4aefe346a0f2523d379125d0b96/src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfiller.kt#L133)):*
<details><summary><i>Previously, jojijac0b wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I think you'll want the caller of this class to do the validation as well (when the Info Map is created) so that any config failures happen early.


<!-- Sent from Reviewable.io -->

2024-06-06 22:17 UTC, stevenwarejones requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527)* status: 24 of 25 files reviewed, 12 unresolved discussions (waiting on @jojijac0b, @kungfucraig, and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfiller.kt` line 213 at r18](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-Nz9z9D67LIblJS1DZQQ:-NzjbU_m5Ymp8FnXmfpI:b-qb2uoa) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/df34e9c3eff8ff381dc29c411ba42a328dd03d92/src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfiller.kt#L213)):*
<details><summary><i>Previously, jojijac0b wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I'm not seeing this last point done yet (which is duplicated in another comment)


<!-- Sent from Reviewable.io -->

2024-06-07 01:13 UTC, SanjayVas requested changes
> Reviewed 1 of 10 files at r10, 1 of 11 files at r16, 3 of 5 files at r17, 5 of 5 files at r20, 6 of 7 files at r21, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527)* status: 24 of 25 files reviewed, 10 unresolved discussions (waiting on @jojijac0b, @kungfucraig, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/BUILD.bazel` line 14 at r21](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-NzkArA8-WHZzG8ohbbC:-NzkArA8-WHZzG8ohbbD:b-r1t233) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cc11e2522d7c110c5c225348b8986552850efed6/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/BUILD.bazel#L14)):*
> ```Starlark
>         "//src/test/kotlin/org/wfanet/measurement/integration:__subpackages__",
>         "//src/test/kotlin/org/wfanet/measurement/loadtest:__subpackages__",
>         "//src/main/kotlin/org/wfanet/measurement/populationdataprovider:__subpackages__",
> ```

Nothing from here should be visible to populationdataprovider.
___
*[`src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfiller.kt` line 60 at r18](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-Nz9u1-a1FkjbVTKts-v:-NzkD26Y7KAa-3Z8m93P:b-qt96x6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/df34e9c3eff8ff381dc29c411ba42a328dd03d92/src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfiller.kt#L60)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

@SanjayVas - is there a way to derive the Class of the Message from the TypeRegistry? I didnt' see any methods that could do that.
</blockquote></details>

The actual classes **cannot** be known at compile time, as the descriptors are loaded in from a FileDescriptorSet at runtime. You need to use the Descriptor types. That is to say that I don't think you can call `unpack`. Instead you need to parse the message into a DynamicMessage using the descriptor from the type registry

```kotlin
val descriptor = typeRegistry.getDescriptorForTypeUrl(attribute.typeUrl)
val message = DynamicMessage.parseFrom(descriptor, attribute.data)
```
___
*[`src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfiller.kt` line 59 at r21](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-NzkC6Yo8QDYE3tUtP50:-NzkC6Yo8QDYE3tUtP51:b-n3l3oe) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cc11e2522d7c110c5c225348b8986552850efed6/src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfiller.kt#L59)):*
> ```Kotlin
>   val populationSpec: PopulationSpec,
>   val eventDescriptor: Descriptor,
>   val typeRegistry: TypeRegistry,
> ```

There should be a single type registry loaded from the FileDescriptorSet passed in at runtime, not a separate one for each Population.


<!-- Sent from Reviewable.io -->

2024-06-07 13:10 UTC, stevenwarejones reviewed
> Reviewed 1 of 2 files at r19.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527)* status: all files reviewed, 10 unresolved discussions (waiting on @jojijac0b and @kungfucraig)



<!-- Sent from Reviewable.io -->

2024-06-12 13:17 UTC, jojijac0b reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527)* status: 22 of 25 files reviewed, 10 unresolved discussions (waiting on @kungfucraig, @SanjayVas, and @stevenwarejones)

___
*[`src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/PopulationRequisitionFulfillerTest.kt` line 623 at r20](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-Nze3ToLC9M66W-L_Qn1:-O-B_iU06T30Z7PODVS0:b-nhacf7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/92e00a3d7d29fc4c11ee2bf31b6838470fd6779c/src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/PopulationRequisitionFulfillerTest.kt#L623)):*
<details><summary><i>Previously, jojijac0b wrote…</i></summary><blockquote>

Done.
</blockquote></details>

The current behavior returns an error if the expression in the filter is not in the operative fields. This is thrown when the program is being compiled in EventFilters. I wrote a test to validate this behavior.


<!-- Sent from Reviewable.io -->

2024-06-12 14:50 UTC, stevenwarejones requested changes
> Reviewed 2 of 3 files at r22, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527)* status: 24 of 25 files reviewed, 10 unresolved discussions (waiting on @jojijac0b, @kungfucraig, and @SanjayVas)

___
*[`src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/PopulationRequisitionFulfillerTest.kt` line 680 at r22](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-O-BuCyV5NkF93_MVqv7:-O-BuCyV5NkF93_MVqv8:b-lhue9o) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b8c5bdcfc560d1f79a3d9f14a38fa6a0702fd02b/src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/PopulationRequisitionFulfillerTest.kt#L680)):*
> ```Kotlin
>         population =
>           RequisitionSpecKt.population {
>             filter = eventFilter { expression = "person.gender == ${Person.Gender.FEMALE_VALUE} && other_field.value == other_value" }
> ```

one more test.... can you create one with a filter for an test event field that is not part of the population spec...
```
expression = "person.gender == ${Person.Gender.FEMALE_VALUE} && bannerField.viewable == true"
```
that this should have the same output as
```
expression = "person.gender == ${Person.Gender.FEMALE_VALUE}"
```


<!-- Sent from Reviewable.io -->

2024-06-12 17:55 UTC, SanjayVas requested changes
> Reviewed 1 of 3 files at r22, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527)* status: 24 of 25 files reviewed, 11 unresolved discussions (waiting on @jojijac0b, @kungfucraig, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfiller.kt` line 59 at r21](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-NzkC6Yo8QDYE3tUtP50:-O-CYMc34GW2Ucrap46h:b-p581mg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cc11e2522d7c110c5c225348b8986552850efed6/src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfiller.kt#L59)):*
<details><summary><i>Previously, jojijac0b wrote…</i></summary><blockquote>

Type Registry is created from the FileDescriptorSet which is passed in to the constructor.
</blockquote></details>

You can have the caller build/pass the TypeRegistry instead. This way tests can build the registry using compiled-in protobuf descriptors, but the runner can load in the FileDescriptorSets from the command line.

Basically, loading from FileDescriptorSets is a feature of running on the command line.
___
*[`src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfiller.kt` line 130 at r22](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-O-CZ4OvEM6biJ6yMoQ1:-O-CZ4OvEM6biJ6yMoQ2:b-j73wo6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b8c5bdcfc560d1f79a3d9f14a38fa6a0702fd02b/src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfiller.kt#L130)):*
> ```Kotlin
>         logger.log(Level.INFO, "RequisitionSpec:\n$requisitionSpec")
> 
>         val modelRelease = getModelRelease(measurementSpec)
> ```

Explicit types where not obvious (e.g. calling a constructor/builder). See https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/docs/code-style.md#kotlin

Unfortunately a lot of our existing code doesn't fully adhere to this, but trying to be better on new code.
___
*[`src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/PopulationRequisitionFulfillerTest.kt` line 198 at r22](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-O-CZvO-0LBEVja1S0EA:-O-CZvO-0LBEVja1S0EB:b36vxps) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b8c5bdcfc560d1f79a3d9f14a38fa6a0702fd02b/src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/PopulationRequisitionFulfillerTest.kt#L198)):*
> ```Kotlin
> }
> 
> val ATTRIBUTE_1 = PERSON_1.pack()
> ```

Make all of these private and move them to the companion object. See https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/docs/code-style.md#kotlin
___
*[`src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/PopulationRequisitionFulfillerTest.kt` line 376 at r22](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-O-C_5Ay3m--HNATzrdv:-O-C_5Ay3m--HNATzrdw:b-g1j0sm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b8c5bdcfc560d1f79a3d9f14a38fa6a0702fd02b/src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/PopulationRequisitionFulfillerTest.kt#L376)):*
> ```Kotlin
> 
>   @Test
>   fun `gets correct population of all 18-34 age range`() {
> ```

nit: Test method format is something like "[SUT] verbs X [for/when Y]". So perhaps "fulfills requisition for 18-34 age range". We can leave off the "executeRequisitionFulfillingWorkflow" as the SUT because that's the only public method.


<!-- Sent from Reviewable.io -->

2024-06-12 18:21 UTC, stevenwarejones reviewed
> Reviewed 1 of 3 files at r22.
> Dismissed @Marco-Premier from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527)* status: all files reviewed, 10 unresolved discussions (waiting on @jojijac0b, @kungfucraig, and @SanjayVas)



<!-- Sent from Reviewable.io -->

2024-06-13 16:40 UTC, jojijac0b reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527)* status: all files reviewed, 10 unresolved discussions (waiting on @kungfucraig, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfiller.kt` line 59 at r21](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-NzkC6Yo8QDYE3tUtP50:-O-H3lKLDh12k4qf_kaf:b-b57bs8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cc11e2522d7c110c5c225348b8986552850efed6/src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfiller.kt#L59)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

You can have the caller build/pass the TypeRegistry instead. This way tests can build the registry using compiled-in protobuf descriptors, but the runner can load in the FileDescriptorSets from the command line.

Basically, loading from FileDescriptorSets is a feature of running on the command line.
</blockquote></details>

Done. Will add FileDescriptorSets logic to next PR creating the daemon.
___
*[`src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfiller.kt` line 130 at r22](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-O-CZ4OvEM6biJ6yMoQ1:-O-HECtY7yI-LBgVOMeF:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b8c5bdcfc560d1f79a3d9f14a38fa6a0702fd02b/src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfiller.kt#L130)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Explicit types where not obvious (e.g. calling a constructor/builder). See https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/docs/code-style.md#kotlin

Unfortunately a lot of our existing code doesn't fully adhere to this, but trying to be better on new code.
</blockquote></details>

Done.
___
*[`src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/PopulationRequisitionFulfillerTest.kt` line 198 at r22](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-O-CZvO-0LBEVja1S0EA:-O-HBKbq-TMA5l52FVTU:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b8c5bdcfc560d1f79a3d9f14a38fa6a0702fd02b/src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/PopulationRequisitionFulfillerTest.kt#L198)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Make all of these private and move them to the companion object. See https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/docs/code-style.md#kotlin
</blockquote></details>

Done.
___
*[`src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/PopulationRequisitionFulfillerTest.kt` line 680 at r22](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-O-BuCyV5NkF93_MVqv7:-O-HSu4X1JwyjqQivjto:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b8c5bdcfc560d1f79a3d9f14a38fa6a0702fd02b/src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/PopulationRequisitionFulfillerTest.kt#L680)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

one more test.... can you create one with a filter for an test event field that is not part of the population spec...
```
expression = "person.gender == ${Person.Gender.FEMALE_VALUE} && bannerField.viewable == true"
```
that this should have the same output as
```
expression = "person.gender == ${Person.Gender.FEMALE_VALUE}"
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-06-13 18:37 UTC, stevenwarejones approved these changes
> Reviewed 8 of 8 files at r23, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527)* status: all files reviewed, 9 unresolved discussions (waiting on @jojijac0b, @kungfucraig, and @SanjayVas)



<!-- Sent from Reviewable.io -->

2024-06-13 19:16 UTC, SanjayVas requested changes
> Reviewed 5 of 8 files at r23, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527)* status: all files reviewed, 10 unresolved discussions (waiting on @jojijac0b, @kungfucraig, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfiller.kt` line 57 at r23](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-O-Hk8mo5KPgJdFhWksH:-O-HjDFP9n7zS3v2DOHF:b-tnvy9n) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9c6ad2fb2d73ab912a6421f7a8096eefb4703b1d/src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfiller.kt#L57)):*
> ```Kotlin
> data class PopulationInfo(
>   val populationSpec: PopulationSpec,
>   val eventDescriptor: Descriptor,
> ```

I assume this is the descriptor of some Event message that contains a field for the EventTemplate specified in the PopulationSpec? If so, maybe call it `eventMessageDescriptor` and add a KDoc for the field.

If you want to do it this way, your eventual daemon will need a command line option specifying the Event message type for each PopulationSpec. A better solution would be dynamically generating an Event message type for each EventTemplate by building a DescriptorProto.
___
*[`src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfiller.kt` line 58 at r23](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-O-HiqlG7AyfUBkDC1Ie:-O-HiqlG7AyfUBkDC1If:b-lq8csz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9c6ad2fb2d73ab912a6421f7a8096eefb4703b1d/src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfiller.kt#L58)):*
> ```Kotlin
>   val populationSpec: PopulationSpec,
>   val eventDescriptor: Descriptor,
>   val operativeFields: Set<String>,
> ```

The caller shouldn't need to pass in the operative fields here. These can instead be read from the annotations on the corresponding event template descriptor. That descriptor can be obtained from the type registry.


<!-- Sent from Reviewable.io -->

2024-06-18 15:22 UTC, Marco-Premier reviewed
> Reviewed 3 of 7 files at r21, 6 of 8 files at r23.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527)* status: all files reviewed, 10 unresolved discussions (waiting on @jojijac0b, @kungfucraig, @SanjayVas, and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2024-06-18 15:22 UTC, Marco-Premier approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-:-O-fwOqE3zA24xiNGkT3:bnfp4nl)* status: all files reviewed, 10 unresolved discussions (waiting on @jojijac0b, @kungfucraig, @SanjayVas, and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2024-06-18 16:47 UTC, kungfucraig reviewed
> Reviewed 1 of 5 files at r17, 2 of 5 files at r20, 2 of 7 files at r21, 6 of 8 files at r23.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527)* status: all files reviewed, 9 unresolved discussions (waiting on @jojijac0b, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/PopulationSpecValidator.kt` line 160 at r23](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-O-fx4Sh3X1x8UbGGD5v:-O-fx4Sh3X1x8UbGGD5w:b-j07hcm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9c6ad2fb2d73ab912a6421f7a8096eefb4703b1d/src/main/kotlin/org/wfanet/measurement/api/v2alpha/PopulationSpecValidator.kt#L160)):*
> ```Kotlin
> }
> 
> fun VidRange.size(): Long {
> ```

nit: Docs?
___
*[`src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfiller.kt` line 57 at r23](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-O-Hk8mo5KPgJdFhWksH:-O-gAC8C73m5Q_QtvkV-:brdejsa) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9c6ad2fb2d73ab912a6421f7a8096eefb4703b1d/src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfiller.kt#L57)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I assume this is the descriptor of some Event message that contains a field for the EventTemplate specified in the PopulationSpec? If so, maybe call it `eventMessageDescriptor` and add a KDoc for the field.

If you want to do it this way, your eventual daemon will need a command line option specifying the Event message type for each PopulationSpec. A better solution would be dynamically generating an Event message type for each EventTemplate by building a DescriptorProto.
</blockquote></details>

I think we'll need to support multiple Event Message types - e.g. one for display and one for video. Unless it's adequate that the population fields are the same.
___
*[`src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfiller.kt` line 58 at r23](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-O-HiqlG7AyfUBkDC1Ie:-O-gEhV35FQSboXNcQi8:b32v57) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9c6ad2fb2d73ab912a6421f7a8096eefb4703b1d/src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfiller.kt#L58)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The caller shouldn't need to pass in the operative fields here. These can instead be read from the annotations on the corresponding event template descriptor. That descriptor can be obtained from the type registry.
</blockquote></details>

+1


<!-- Sent from Reviewable.io -->

2024-06-18 17:10 UTC, SanjayVas requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527)* status: all files reviewed, 9 unresolved discussions (waiting on @jojijac0b, @kungfucraig, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfiller.kt` line 57 at r23](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-O-Hk8mo5KPgJdFhWksH:-O-gJaWf5--tFLT3vBzY:bpxn283) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9c6ad2fb2d73ab912a6421f7a8096eefb4703b1d/src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfiller.kt#L57)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

I think we'll need to support multiple Event Message types - e.g. one for display and one for video. Unless it's adequate that the population fields are the same.
</blockquote></details>

It's one event template per PopulationSpec. It just needs to be wrapped in an event message so that the same filter can be used for event vs. population Requisitions.


<!-- Sent from Reviewable.io -->

2024-06-18 17:25 UTC, kungfucraig requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527)* status: all files reviewed, 10 unresolved discussions (waiting on @jojijac0b, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfiller.kt` line 57 at r23](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-O-Hk8mo5KPgJdFhWksH:-O-gMc3E2pfIlIWBpH_h:bjlh9hq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9c6ad2fb2d73ab912a6421f7a8096eefb4703b1d/src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfiller.kt#L57)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

It's one event template per PopulationSpec. It just needs to be wrapped in an event message so that the same filter can be used for event vs. population Requisitions.
</blockquote></details>

Just to make sure we're on the same page... A example of this would be Person, right?

https://sourcegraph.com/github.com/world-federation-of-advertisers/cross-media-measurement/-/blob/src/main/proto/wfa/measurement/api/v2alpha/event_templates/testing/person.proto

And if so, this isn't really a complete event message it's a subset of an event message. Maybe we can have a better name, or maybe it's just a question of adequate documentation.

@jojijac0b You should really have some KDoc for this structure. :)
___
*[`src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/PopulationRequisitionFulfillerTest.kt` line 209 at r23](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-O-gMPyzCX2G2eYmsWml:-O-gMPyzCX2G2eYmsWmm:b7lbyrj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9c6ad2fb2d73ab912a6421f7a8096eefb4703b1d/src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/PopulationRequisitionFulfillerTest.kt#L209)):*
> ```Kotlin
>   }
> 
>   @Test
> ```

Can you add a test that filters are two population attributes (e.g. person.gender = X && person.age = Y)?


<!-- Sent from Reviewable.io -->

2024-06-18 17:30 UTC, SanjayVas requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527)* status: all files reviewed, 10 unresolved discussions (waiting on @jojijac0b and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfiller.kt` line 57 at r23](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-O-Hk8mo5KPgJdFhWksH:-O-gO5t-DK2g935cmpfz:b-fafjb6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9c6ad2fb2d73ab912a6421f7a8096eefb4703b1d/src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfiller.kt#L57)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Just to make sure we're on the same page... A example of this would be Person, right?

https://sourcegraph.com/github.com/world-federation-of-advertisers/cross-media-measurement/-/blob/src/main/proto/wfa/measurement/api/v2alpha/event_templates/testing/person.proto

And if so, this isn't really a complete event message it's a subset of an event message. Maybe we can have a better name, or maybe it's just a question of adequate documentation.

@jojijac0b You should really have some KDoc for this structure. :)
</blockquote></details>

Yes, Person is an event template. The filter in the Requisition needs to apply at the event message level though, meaning some message with a `person` field. Therefore you need a wrapper event message type to pass to the CEL library. This type can be created dynamically for each template.


<!-- Sent from Reviewable.io -->

2024-06-18 18:15 UTC, stevenwarejones reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527)* status: all files reviewed, 9 unresolved discussions (waiting on @jojijac0b and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfiller.kt` line 57 at r23](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-O-Hk8mo5KPgJdFhWksH:-O-gXilZ3ujr0ZrcKwIK:b1b6w47) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9c6ad2fb2d73ab912a6421f7a8096eefb4703b1d/src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfiller.kt#L57)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Yes, Person is an event template. The filter in the Requisition needs to apply at the event message level though, meaning some message with a `person` field. Therefore you need a wrapper event message type to pass to the CEL library. This type can be created dynamically for each template.
</blockquote></details>

in the data class above, I believe that eventDescriptor corresponds to _the message_ that contains fields for each of messages you are referring to - so in this case, test_event.proto, not person.proto - https://sourcegraph.com/github.com/world-federation-of-advertisers/cross-media-measurement/-/blob/src/main/proto/wfa/measurement/api/v2alpha/event_templates/testing/test_event.proto

The fields within are populated from the populationSpec
___
*[`src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfiller.kt` line 58 at r23](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-O-HiqlG7AyfUBkDC1Ie:-O-gYM5xCaZRbY5qlAaE:b6rn1ms) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9c6ad2fb2d73ab912a6421f7a8096eefb4703b1d/src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfiller.kt#L58)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

+1
</blockquote></details>

This is a relatively small ask @jojijac0b and I think it makes sense here to just derive the operative Fields from the fields within the eventDescriptor that are annotated as population fields.


<!-- Sent from Reviewable.io -->

2024-06-18 23:12 UTC, jojijac0b reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527)* status: 23 of 25 files reviewed, 8 unresolved discussions (waiting on @kungfucraig, @Marco-Premier, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfiller.kt` line 58 at r23](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-O-HiqlG7AyfUBkDC1Ie:-O-hbicdBsg5djIJJ8Ji:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9c6ad2fb2d73ab912a6421f7a8096eefb4703b1d/src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfiller.kt#L58)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

This is a relatively small ask @jojijac0b and I think it makes sense here to just derive the operative Fields from the fields within the eventDescriptor that are annotated as population fields.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-06-18 23:46 UTC, SanjayVas requested changes
> Reviewed 1 of 2 files at r24, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527)* status: 24 of 25 files reviewed, 8 unresolved discussions (waiting on @jojijac0b and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfiller.kt` line 270 at r18](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-Nz9w4Uc9echbHVMSvsU:-O-hgTk-2aqQOWOl1diY:bl71m3f) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/df34e9c3eff8ff381dc29c411ba42a328dd03d92/src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfiller.kt#L270)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

@SanjayVas
</blockquote></details>

This is correct; fields without explicit field presence that are set to their default value will not show up in the allFields collection.

See https://github.com/protocolbuffers/protobuf/issues/4503
___
*[`src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfiller.kt` line 259 at r24](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-O-hem56EpKreq1xF8yB:-O-hem571OiBWg1Bk_34:bedvzxj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fef3de98c481ade2aa72d0f2457b2df0a679542d/src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfiller.kt#L259)):*
> ```Kotlin
>    * attribute set to true will be returned.
>    */
>   private fun getPopulationOperativeFields(eventMessageDescriptor: Descriptor): Set<String> {
> ```

You can technically build just from the template descriptor. You don't need the whole event message descriptor.



_Code quote:_
```Kotlin
eventMessageDescriptor: Descriptor
```
___
*[`src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfiller.kt` line 261 at r24](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-O-hdx-w6bQGK57BznlD:-O-hdx-xDBrcshK5nqNY:b-jio7th) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fef3de98c481ade2aa72d0f2457b2df0a679542d/src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfiller.kt#L261)):*
> ```Kotlin
>   private fun getPopulationOperativeFields(eventMessageDescriptor: Descriptor): Set<String> {
>     return eventMessageDescriptor.fields.flatMap {
>       it.messageType.fields.map { jt ->
> ```

Use a descriptive/meaningful name



_Suggestion:_
```Kotlin
templateFieldDescriptor
```
___
*[`src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfiller.kt` line 263 at r24](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-O-hfncZ6FMXtKg75lAK:-O-hfncZ6FMXtKg75lAL:b46e82i) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fef3de98c481ade2aa72d0f2457b2df0a679542d/src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfiller.kt#L263)):*
> ```Kotlin
>       it.messageType.fields.map { jt ->
>         if(jt.options.getExtension(EventAnnotationsProto.templateField).populationAttribute){
>           "${jt.containingType.name}.${jt.name}"
> ```

This should be the field name within the event message, not the name of the containing type. You can get this from the `event_template` message option.



_Code quote:_
```Kotlin
${jt.containingType.name}
```


<!-- Sent from Reviewable.io -->

2024-06-20 14:47 UTC, stevenwarejones approved these changes
> Reviewed 1 of 2 files at r24, 2 of 2 files at r25, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527)* status: all files reviewed, 8 unresolved discussions (waiting on @jojijac0b and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfiller.kt` line 270 at r18](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-Nz9w4Uc9echbHVMSvsU:-O-q6IGv9_Im1U6jJTD4:bb69o1y) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/df34e9c3eff8ff381dc29c411ba42a328dd03d92/src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfiller.kt#L270)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This is correct; fields without explicit field presence that are set to their default value will not show up in the allFields collection.

See https://github.com/protocolbuffers/protobuf/issues/4503
</blockquote></details>

#thx


<!-- Sent from Reviewable.io -->

2024-06-20 15:55 UTC, jojijac0b reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527)* status: 23 of 25 files reviewed, 7 unresolved discussions (waiting on @kungfucraig, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfiller.kt` line 259 at r24](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-O-hem56EpKreq1xF8yB:-O-pu9T10xTA1Px-I0Et:bcvyvck) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fef3de98c481ade2aa72d0f2457b2df0a679542d/src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfiller.kt#L259)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

You can technically build just from the template descriptor. You don't need the whole event message descriptor.
</blockquote></details>

Right now I need to filter through all the fields of the event message descriptor because there is no way to identify an event template that is used for population(i.e. population_attribute = true). This is only done within the fields of the event template itself. I can add population_attribute extension to the Person field in test_event.proto and modify this logic in another pr if you think this should be done. 
___
*[`src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfiller.kt` line 261 at r24](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-O-hdx-w6bQGK57BznlD:-O-q1sZU4i1Daj1R2HZc:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fef3de98c481ade2aa72d0f2457b2df0a679542d/src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfiller.kt#L261)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Use a descriptive/meaningful name
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfiller.kt` line 263 at r24](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-O-hfncZ6FMXtKg75lAK:-O-pz_T6954D2ohmr0ps:b18o7bp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fef3de98c481ade2aa72d0f2457b2df0a679542d/src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfiller.kt#L263)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This should be the field name within the event message, not the name of the containing type. You can get this from the `event_template` message option.
</blockquote></details>

Rewrote logic to be more readable. Getting the name from the eventTemplate.
___
*[`src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/PopulationRequisitionFulfillerTest.kt` line 209 at r23](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-O-gMPyzCX2G2eYmsWml:-O-qLXcv1gXqHsbMnTw2:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9c6ad2fb2d73ab912a6421f7a8096eefb4703b1d/src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/PopulationRequisitionFulfillerTest.kt#L209)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Can you add a test that filters are two population attributes (e.g. person.gender = X && person.age = Y)?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-06-20 15:55 UTC, jojijac0b reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527)* status: 23 of 25 files reviewed, 7 unresolved discussions (waiting on @kungfucraig, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfiller.kt` line 133 at r16](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-NyfXv1kBuNa0d_BJk3C:-O-qM-Cb-J1SddktHGWk:b9fwbg9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c6494be790d4d4aefe346a0f2523d379125d0b96/src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfiller.kt#L133)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

I think you'll want the caller of this class to do the validation as well (when the Info Map is created) so that any config failures happen early.
</blockquote></details>

I can do validation in the daemon as well in the next PR


<!-- Sent from Reviewable.io -->

2024-06-20 15:56 UTC, jojijac0b reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527)* status: 23 of 25 files reviewed, 7 unresolved discussions (waiting on @kungfucraig, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfiller.kt` line 57 at r23](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-O-Hk8mo5KPgJdFhWksH:-O-qM5os5CpULZBtLaAl:b-c19m3e) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9c6ad2fb2d73ab912a6421f7a8096eefb4703b1d/src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfiller.kt#L57)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

in the data class above, I believe that eventDescriptor corresponds to _the message_ that contains fields for each of messages you are referring to - so in this case, test_event.proto, not person.proto - https://sourcegraph.com/github.com/world-federation-of-advertisers/cross-media-measurement/-/blob/src/main/proto/wfa/measurement/api/v2alpha/event_templates/testing/test_event.proto

The fields within are populated from the populationSpec
</blockquote></details>

Added Kdoc to describe this data class


<!-- Sent from Reviewable.io -->

2024-06-21 16:35 UTC, stevenwarejones approved these changes
> Reviewed 2 of 2 files at r26, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527)* status: all files reviewed, 7 unresolved discussions (waiting on @kungfucraig and @SanjayVas)



<!-- Sent from Reviewable.io -->

2024-06-21 23:42 UTC, kungfucraig approved these changes
> Reviewed 1 of 10 files at r10, 1 of 2 files at r25.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527)* status: all files reviewed, 6 unresolved discussions (waiting on @SanjayVas)



<!-- Sent from Reviewable.io -->

2024-06-25 18:13 UTC, SanjayVas requested changes
> Reviewed 1 of 2 files at r25, 1 of 2 files at r26, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527)* status: all files reviewed, 3 unresolved discussions (waiting on @jojijac0b)

___
*[`src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfiller.kt` line 259 at r24](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-O-hem56EpKreq1xF8yB:-O0FZIbv9vd_Tr9yLi9t:b3kss03) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fef3de98c481ade2aa72d0f2457b2df0a679542d/src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfiller.kt#L259)):*
<details><summary><i>Previously, jojijac0b wrote…</i></summary><blockquote>

Right now I need to filter through all the fields of the event message descriptor because there is no way to identify an event template that is used for population(i.e. population_attribute = true). This is only done within the fields of the event template itself. I can add population_attribute extension to the Person field in test_event.proto and modify this logic in another pr if you think this should be done.
</blockquote></details>

My point is that since each Population only uses one template, you don't need the whole event message descriptor here. Just the specific template descriptor should be sufficient.
___
*[`src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfiller.kt` line 66 at r26](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-O0F_8Pi0g4i4wDwTwqb:-O0F_8Pi0g4i4wDwTwqc:b-cptd5w) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/96c8d17149ca1462c51bcb7fac853fd0c245a3f0/src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfiller.kt#L66)):*
> ```Kotlin
> data class PopulationInfo(
>   val populationSpec: PopulationSpec,
>   val eventMessageDescriptor: Descriptor,
> ```

Repeating this from the other comment thread:

If you have the caller pass in an Event message descriptor here, then your eventual daemon will need a command line option specifying the Event message type for each PopulationSpec. Furthermore, the FileDescriptorSet will need to contain the entire event message type.

A better solution would be dynamically generating an Event message type for each EventTemplate by building a DescriptorProto. That solution would not work for the EDP simulator because that needs to fill out all templates, but each Population only references a single event template.

Feel free to leave this as a TODO to fix in the daemon PR if it's getting too complicated here.


<!-- Sent from Reviewable.io -->

2024-06-26 00:40 UTC, stevenwarejones approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527)* status: all files reviewed, 3 unresolved discussions (waiting on @jojijac0b and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfiller.kt` line 259 at r24](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-O-hem56EpKreq1xF8yB:-O0Gz71sBcSWC9e05Ymo:b-5als3e) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fef3de98c481ade2aa72d0f2457b2df0a679542d/src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfiller.kt#L259)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

My point is that since each Population only uses one template, you don't need the whole event message descriptor here. Just the specific template descriptor should be sufficient.
</blockquote></details>

that makes sense. add a todo for this @jojijac0b 
___
*[`src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfiller.kt` line 66 at r26](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-O0F_8Pi0g4i4wDwTwqb:-O0GytGFC5-xFWD0Yf5m:bax4pej) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/96c8d17149ca1462c51bcb7fac853fd0c245a3f0/src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfiller.kt#L66)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Repeating this from the other comment thread:

If you have the caller pass in an Event message descriptor here, then your eventual daemon will need a command line option specifying the Event message type for each PopulationSpec. Furthermore, the FileDescriptorSet will need to contain the entire event message type.

A better solution would be dynamically generating an Event message type for each EventTemplate by building a DescriptorProto. That solution would not work for the EDP simulator because that needs to fill out all templates, but each Population only references a single event template.

Feel free to leave this as a TODO to fix in the daemon PR if it's getting too complicated here.
</blockquote></details>

I think lets leave this as a todo for now and tackle in July.


<!-- Sent from Reviewable.io -->

2024-06-26 15:38 UTC, stevenwarejones reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527)* status: 24 of 25 files reviewed, 3 unresolved discussions (waiting on @jojijac0b, @kungfucraig, @Marco-Premier, and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfiller.kt` line 66 at r26](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-O0F_8Pi0g4i4wDwTwqb:-O0KBXN-Dzb_UHtLQfyc:b4oo5x6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/96c8d17149ca1462c51bcb7fac853fd0c245a3f0/src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfiller.kt#L66)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

I think lets leave this as a todo for now and tackle in July.
</blockquote></details>

so, I thought about this some more. The current requirement is that the eventFilter and the populationFilter will be identical. If that's the case, then the populationFilter will contain fields not present in the PopulationSpec. I'd prefer to keep this as-is without a todo for that reason.


<!-- Sent from Reviewable.io -->

2024-06-26 16:03 UTC, SanjayVas approved these changes
> Reviewed 1 of 2 files at r26, 5 of 5 files at r27, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jojijac0b)

___
*[`src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfiller.kt` line 66 at r26](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527#-O0F_8Pi0g4i4wDwTwqb:-O0KHFR-Dyi2P7IDhCpr:bnfir8z) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/96c8d17149ca1462c51bcb7fac853fd0c245a3f0/src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfiller.kt#L66)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

so, I thought about this some more. The current requirement is that the eventFilter and the populationFilter will be identical. If that's the case, then the populationFilter will contain fields not present in the PopulationSpec. I'd prefer to keep this as-is without a todo for that reason.
</blockquote></details>

If we're passing in an Event message descriptor, it should be a single one for all templates then. Regardless, approving this for now and it can be handled later.


<!-- Sent from Reviewable.io -->

2024-06-28 17:37 UTC, stevenwarejones approved these changes
> Reviewed 2 of 5 files at r27, 10 of 10 files at r28, 1 of 1 files at r29, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1527)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jojijac0b)



<!-- Sent from Reviewable.io -->

2024-06-28 17:37 UTC, merged