Add CreateUiReport to the CLI
world-federation-of-advertisers/cross-media-measurement pull request #1535
Opened 2024-03-25 13:59 UTC by bdomen-ggl

Update the Reporting CLI tool to create a UI readable report. It is moderately hardcoded to limit the amount of configuration required by the user. There are a number of steps to complete this process:
1. Create 3 primitive Reporting Sets (with a number of event groups).
2. Create 1 union Reporting Set - the union of all 3 primitives.
3. Create 3 unique Reporting Sets (difference between the union and the union of the other two. eg. unique A = ABC - BC)
4. Create 1 metric calculation spec for the primitives.
5. Create 1 metric calculation spec for the composites.
6. Create a report mapping the reporting sets and metric calculation specs and include the other report parameters (like date range and frequency).

All the reporting sets and the report will be tagged appropriately so the Reporting BFF can process the report correctly.

2024-03-25 22:23 UTC, SanjayVas requested changes
> Reviewed 1 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1535)* status: 1 of 3 files reviewed, 10 unresolved discussions (waiting on @bdomen-ggl)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/tools/README.md` line 150 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1535#-Ntrcg9R1uOwamUNXqOg:-Ntrcg9R1uOwamUNXqOh:bn75j8l) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f9eb2278a6229cb4f02f105f56c48a38802ec30c/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/tools/README.md#L150)):*
> ```Markdown
> ```
> 
> There currently needs to be three groups of primitive reporting sets defined by the arg group: --cmms-event-group, --primitive-rs-id, and --primitive-rs-display-name. You can pass in multiple event groups, but be sure to specify them first. There is a parsing issue if they are specified later in the arg group. This is similar to creating a reporting set.
> ```

Does it have to be 3, or can we easily extend to *n*?  Note that the classic example often only has 2 primitive reporting sets: "TV" and "Digital".



_Code quote:_
```Markdown
three groups of primitive reporting sets
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/tools/README.md` line 150 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1535#-Ntrchha2lR1bosIoCiV:-NtrcWE21yQWxW44Bxmr:bxo0mjq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f9eb2278a6229cb4f02f105f56c48a38802ec30c/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/tools/README.md#L150)):*
> ```Markdown
> ```
> 
> There currently needs to be three groups of primitive reporting sets defined by the arg group: --cmms-event-group, --primitive-rs-id, and --primitive-rs-display-name. You can pass in multiple event groups, but be sure to specify them first. There is a parsing issue if they are specified later in the arg group. This is similar to creating a reporting set.
> ```

I think it would be simpler to just have this be --reporting-set-id and --reporting-set-display-name. We can derive the names and IDs for everything else from these.

Let's say your three reporting sets are `instagram`, `youtube`, and `tv` with display names "Instagram", "YouTube", and "Television". The union set ID could then be `union-instagram-youtube-tv` with a display name of something like "Instagram U YouTube U Television" or "Union (Instagram, YouTube, Television)"
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/tools/README.md` line 156 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1535#-NtreNIQ4LT-HwT1yfmQ:-NtreNIQ4LT-HwT1yfmR:bs1q9b0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f9eb2278a6229cb4f02f105f56c48a38802ec30c/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/tools/README.md#L156)):*
> ```Markdown
> The unique reporting sets are created automatically from the primitives and union. They are not explicitly used in the UI and require no input. They are post-fixed with "unique."
> 
> The actual values of the metric calculation specs are hardcoded for user simplicity as the combinations have to be very specific. What the user will define are the ids and names for the specs. There are two different configurations of specs so they each need to be defined: --prim-metric-id and --prim-metric-display-name as well as --comp-metric-id and --comp-metric-display-name. These aren't use in the UI so they can be any valid value for creation purposes.
> ```

Same idea here. I don't think we need the user to give us these. If we're hard-coding them anyway, we can give them predictable IDs. This is especially true if they can be reused, so we can just check if they already exist and create if needed.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/tools/Reporting.kt` line 295 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1535#-NtrXpcYAmCmVI6egXNp:-NtrXpcZEXQ-66xoOsXQ:b-xsyuy4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f9eb2278a6229cb4f02f105f56c48a38802ec30c/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/tools/Reporting.kt#L295)):*
> ```Kotlin
>     @CommandLine.Option(
>       names = ["--cmms-event-group"],
>       description = ["List of CMMS EventGroup resource names"],
> ```

Indicate that it the option can be specified multiple times rather than describing it as a list



_Suggestion:_
```Kotlin
EventGroup resource name from the CMMS API. This can be specified multiple times
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/tools/Reporting.kt` line 403 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1535#-NtrYu6FBfU00hRwwI4C:-NtrYu6FBfU00hRwwI4D:b-xwqhbt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f9eb2278a6229cb4f02f105f56c48a38802ec30c/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/tools/Reporting.kt#L403)):*
> ```Kotlin
> 
>     @CommandLine.Option(
>       names = ["--day-of-the-week"],
> ```

nit: take out the "the" to match the common phrase as well as the request field name



_Suggestion:_
```Kotlin
--day-of-week
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/tools/Reporting.kt` line 412 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1535#-NtrZPPO1tRAVNd_O6by:-NtrZPPO1tRAVNd_O6bz:brjec4k) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f9eb2278a6229cb4f02f105f56c48a38802ec30c/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/tools/Reporting.kt#L412)):*
> ```Kotlin
>         ],
>     )
>     var dayOfTheWeek: Int = 0
> ```

Use the DayOfWeek enum, not an Int



_Code quote:_
```Kotlin
Int
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/tools/Reporting.kt` line 437 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1535#-Ntr_ByyDu6qGHr_5wh2:-Ntr_Byz292Zy6s4ZvWP:b32x3wz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f9eb2278a6229cb4f02f105f56c48a38802ec30c/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/tools/Reporting.kt#L437)):*
> ```Kotlin
>   class ReportingIntervalInput {
>     @CommandLine.Option(
>       names = ["--reporting-interval-report-start-time"],
> ```

nit: match fields names in the request message when applicable. Qualifiers may be omitted when unambiguous.



_Suggestion:_
```Kotlin
--report-start
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/tools/Reporting.kt` line 441 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1535#-NtrZmFjCRQWFdbhgrbr:-NtrZmFjCRQWFdbhgrbs:b-v8od71) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f9eb2278a6229cb4f02f105f56c48a38802ec30c/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/tools/Reporting.kt#L441)):*
> ```Kotlin
>       required = true,
>     )
>     lateinit var reportingIntervalReportStartTime: LocalDateTime
> ```

We need to let the caller specify the time zone (IANA database time zone ID), picking some reasonable default (e.g. `ZoneId.systemDefault()`) Perhaps `--report-time-zone`?
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/tools/Reporting.kt` line 677 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/15 [...]

2024-03-28 14:10 UTC, bdomen-ggl reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1535)* status: 0 of 3 files reviewed, 9 unresolved discussions (waiting on @SanjayVas)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1535#-Ntv7Ff9DQ3XlVwefTuV:-Ntv7Ff9DQ3XlVwefTuW:b-8gp7xx) (no related file):*
@SanjayVas I was just thinking. I should move these to experimental/... shouldn't I?

___
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/tools/README.md` line 150 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1535#-Ntrcg9R1uOwamUNXqOg:-Ntv6V1E0UR8VA0cH5_K:bn6hsjq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f9eb2278a6229cb4f02f105f56c48a38802ec30c/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/tools/README.md#L150)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Does it have to be 3, or can we easily extend to *n*?  Note that the classic example often only has 2 primitive reporting sets: "TV" and "Digital".
</blockquote></details>

The way I coded it for the CLI is to be exactly 3 for simplicity (both for users and coding) based off of the demo, but it could be extended. I was trying to keep the logic simple for now so we wouldn't have to worry about the edge conditions of one or two reporting sets and adding extra complication since it's already getting complicated.

In general, I think 1 would be weird since A, unique A, and union are all the same. I think anything greater than 1 should be OK in the UI.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/tools/README.md` line 150 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1535#-Ntrchha2lR1bosIoCiV:-NtvMtYW2CgrU7MEWOi8:b87rust) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f9eb2278a6229cb4f02f105f56c48a38802ec30c/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/tools/README.md#L150)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I think it would be simpler to just have this be --reporting-set-id and --reporting-set-display-name. We can derive the names and IDs for everything else from these.

Let's say your three reporting sets are `instagram`, `youtube`, and `tv` with display names "Instagram", "YouTube", and "Television". The union set ID could then be `union-instagram-youtube-tv` with a display name of something like "Instagram U YouTube U Television" or "Union (Instagram, YouTube, Television)"
</blockquote></details>

Done.

OK, that makes sense. So all the reporting sets will be derived from the base id and display name from the primitives. I still need the event groups, right?

I removed the union and replaced it by deriving names and display names for all from the primitives.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/tools/README.md` line 156 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1535#-NtreNIQ4LT-HwT1yfmQ:-NtvMzF23HrswldINbLo:bqmqjm3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f9eb2278a6229cb4f02f105f56c48a38802ec30c/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/tools/README.md#L156)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Same idea here. I don't think we need the user to give us these. If we're hard-coding them anyway, we can give them predictable IDs. This is especially true if they can be reused, so we can just check if they already exist and create if needed.
</blockquote></details>

Done 

Yeah makes sense. In terms of checking for existence, I imagine I could use like a random hash to lessen the likelihood of conflicts, so I'm not doing something like checking incrementals like name-1, name-2, etc.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/tools/Reporting.kt` line 295 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1535#-NtrXpcYAmCmVI6egXNp:-Ntvx_UC8Ino2iFkhy0J:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f9eb2278a6229cb4f02f105f56c48a38802ec30c/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/tools/Reporting.kt#L295)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Indicate that it the option can be specified multiple times rather than describing it as a list
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/tools/Reporting.kt` line 403 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1535#-NtrYu6FBfU00hRwwI4C:-NtvWxapEWGaMEvMS5B2:b-owj13u) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f9eb2278a6229cb4f02f105f56c48a38802ec30c/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/tools/Reporting.kt#L403)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: take out the "the" to match the common phrase as well as the request field name
</blockquote></details>

Done.

I copied from the metric calculation spec command for consistency. I should have copied it from the report command. Also updated day of the month.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/tools/Reporting.kt` line 412 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1535#-NtrZPPO1tRAVNd_O6by:-Nu0-61V3wNDCPkN1ckn:b-odjq1t) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f9eb2278a6229cb4f02f105f56c48a38802ec30c/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/tools/Reporting.kt#L412)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Use the DayOfWeek enum, not an Int
</blockquote></details>

Done

This is an Int in Metric Calculation Spec. Maybe we should update that one too later.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/tools/Reporting.kt` line 437 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1535#-Ntr_ByyDu6qGHr_5wh2:-NtvX5ty4Pd9iD9FWAsM:br1w5ou) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f9eb2278a6229cb4f02f105f56c48a38802ec30c/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/tools/Reporting.kt#L437)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: match fields names in the request message when applicable. Qualifiers may be omitted when unambiguous.
</blockquote></details>

Done.

Also changed --report-end.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/tools/Reporting.kt` line 441 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1535#-NtrZmFjCRQWFdbhgrbr:-NtvbycVCyRJZ8Z3tJ4h:bkmormt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f9eb2278a6229cb4f02f105f56c48a38802ec30c/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/tools/Reporting.kt#L441)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

We need to let the caller specify the time zone (IANA database time zone ID), picking some reasonable default (e.g. `ZoneId.systemDefault()`) Perhaps `--report-time-zone`?
</blockquote></details>

Done

Sure, I can add it and specify a default. Added it below.
___
*[`src/main/kotlin/org/wf [...]

2024-03-28 20:03 UTC, SanjayVas requested changes
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1535)* status: all files reviewed, 4 unresolved discussions (waiting on @bdomen-ggl)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1535#-Ntv7Ff9DQ3XlVwefTuV:-Nu5dPiH4knR1InNTgFA:bmy52o8) (no related file):*
<details><summary><i>Previously, bdomen-ggl wrote…</i></summary><blockquote>

@SanjayVas I was just thinking. I should move these to experimental/... shouldn't I?
</blockquote></details>

I don't know how you would do that, as the CLI itself lives outside of it. I don't think it's necessary to move it. You'll just need to get a cross-company reviewer.

___
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/tools/README.md` line 150 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1535#-Ntrcg9R1uOwamUNXqOg:-Nu5a4Vc0k6pkAVWTk_t:bmdjl1v) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f9eb2278a6229cb4f02f105f56c48a38802ec30c/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/tools/README.md#L150)):*
<details><summary><i>Previously, bdomen-ggl wrote…</i></summary><blockquote>

The way I coded it for the CLI is to be exactly 3 for simplicity (both for users and coding) based off of the demo, but it could be extended. I was trying to keep the logic simple for now so we wouldn't have to worry about the edge conditions of one or two reporting sets and adding extra complication since it's already getting complicated.

In general, I think 1 would be weird since A, unique A, and union are all the same. I think anything greater than 1 should be OK in the UI.
</blockquote></details>

To clarify, does the UI support *n* where *n* >= 2? Or does the UI only support exactly 3 right now?

If the UI supports *n*, then this CLI should support *n*.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/tools/README.md` line 150 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1535#-Ntrchha2lR1bosIoCiV:-Nu5aKLe81jxVogHXBmZ:b73mrqa) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f9eb2278a6229cb4f02f105f56c48a38802ec30c/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/tools/README.md#L150)):*
<details><summary><i>Previously, bdomen-ggl wrote…</i></summary><blockquote>

Done.

OK, that makes sense. So all the reporting sets will be derived from the base id and display name from the primitives. I still need the event groups, right?

I removed the union and replaced it by deriving names and display names for all from the primitives.
</blockquote></details>

Yes, event groups definitely are still needed.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/tools/README.md` line 150 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1535#-Nu5aVBLAndfCXg6gkeU:-Nu5aVBLAndfCXg6gkeV:bnj4jow) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/df52c84fc6ce864891fd47c7ecf3ef41de33151b/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/tools/README.md#L150)):*
> ```Markdown
> The union and unique reporting sets are created automatically from the provided reporting sets. Ids and display names are derived.
> 
> The user will not specify metric calculation specs although they will be automatically created. They are not used in the UI.
> ```

I don't think this statement is correct, as I believe it previously applied to the IDs.



_Code quote:_
```Markdown
They are not used in the UI.
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/tools/Reporting.kt` line 403 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1535#-NtrYu6FBfU00hRwwI4C:-Nu5bHJH1YzUEiTEJZE5:b-ore237) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f9eb2278a6229cb4f02f105f56c48a38802ec30c/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/tools/Reporting.kt#L403)):*
> I copied from the metric calculation spec command for consistency.

Not sure what you mean. MetricCalculationSpec.MetricFrequencySpec is what I was referring to. The fields there are named `day_of_week` and `day_of_month`
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/tools/Reporting.kt` line 412 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1535#-NtrZPPO1tRAVNd_O6by:-Nu5b-j3CIS_hkk4mrY_:b-lo5bu8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f9eb2278a6229cb4f02f105f56c48a38802ec30c/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/tools/Reporting.kt#L412)):*
> This is an Int in Metric Calculation Spec.

No it's not. https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/986f376424242ace8998dc91038a38e7f71e2a8e/src/main/proto/wfa/measurement/reporting/v2alpha/metric_calculation_spec.proto#L85
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/tools/Reporting.kt` line 384 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1535#-Nu5bcPm8KOb9shQQ_6n:-Nu5bcPm8KOb9shQQ_6o:b-sm0f6y) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/df52c84fc6ce864891fd47c7ecf3ef41de33151b/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/tools/Reporting.kt#L384)):*
> ```Kotlin
>     @CommandLine.Option(
>       names = ["--report-time-zone"],
>       description = ["IANA Time zone"],
> ```

Document that if not specified, the default of the system running this tool is used.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/tools/Reporting.kt` line 396 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1535#-Nu5bohE2MYHhECZRGlf:-Nu5bohE2MYHhECZRGlg:b8j9um6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/df52c84fc6ce864891fd47c7ecf3ef41de33151b/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/tools/Reporting.kt#L396)):*
> ```Kotlin
>   @CommandLine.Option(
>     names = ["--grouping"],
>     description = ["Each grouping is a list of comma-separated predicates"],
> ```

We don't ever want to rely on splitting. We always want collection items to be specified multiple times instead.


<!-- Sent from Reviewable.io -->

2024-03-29 16:01 UTC, bdomen-ggl reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1535)* status: 1 of 3 files reviewed, 4 unresolved discussions (waiting on @SanjayVas)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1535#-Ntv7Ff9DQ3XlVwefTuV:-Nu9vIgh7Hcgm-i2x-VX:b56d48m) (no related file):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I don't know how you would do that, as the CLI itself lives outside of it. I don't think it's necessary to move it. You'll just need to get a cross-company reviewer.
</blockquote></details>

Thanks, didn't think about it before and just dawned on me this week. Thought it made sense to put the new command here, but thought I'd double check.

___
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/tools/README.md` line 150 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1535#-Ntrcg9R1uOwamUNXqOg:-Nu5o6hL-NahcYJPqswP:b-cvp1mj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f9eb2278a6229cb4f02f105f56c48a38802ec30c/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/tools/README.md#L150)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

To clarify, does the UI support *n* where *n* >= 2? Or does the UI only support exactly 3 right now?

If the UI supports *n*, then this CLI should support *n*.
</blockquote></details>

Done

UI technically supports n >= 0 (although 0 and 1 would be really weird). I'll go ahead and update to support n >= 2.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/tools/README.md` line 150 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1535#-Nu5aVBLAndfCXg6gkeU:-Nu5oKeR-tgrvsKt8qpa:br6okfr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/df52c84fc6ce864891fd47c7ecf3ef41de33151b/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/tools/README.md#L150)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I don't think this statement is correct, as I believe it previously applied to the IDs.
</blockquote></details>

Done?

Metric calculation specs aren't used in the UI or the BFF. They are only used to build out the report. I can just remove this block if that helps reduce confusion, but thought it might be useful to let the user know the metric calculation specs are being created too.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/tools/Reporting.kt` line 403 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1535#-NtrYu6FBfU00hRwwI4C:-Nu5oeUG-8_X9Xmo7CS4:bex7ix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f9eb2278a6229cb4f02f105f56c48a38802ec30c/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/tools/Reporting.kt#L403)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> I copied from the metric calculation spec command for consistency.

Not sure what you mean. MetricCalculationSpec.MetricFrequencySpec is what I was referring to. The fields there are named `day_of_week` and `day_of_month`
</blockquote></details>

Sorry, this is specifically what I copied:
https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/tools/Reporting.kt#L531

This is from the CreateMetricCalculationSpecCommand args. Also that arg uses an Int for day of the week and not the enum.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/tools/Reporting.kt` line 412 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1535#-NtrZPPO1tRAVNd_O6by:-Nu5pCnfDwYt05EVWrKw:bsudd7q) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f9eb2278a6229cb4f02f105f56c48a38802ec30c/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/tools/Reporting.kt#L412)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> This is an Int in Metric Calculation Spec.

No it's not. https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/986f376424242ace8998dc91038a38e7f71e2a8e/src/main/proto/wfa/measurement/reporting/v2alpha/metric_calculation_spec.proto#L85
</blockquote></details>

Sorry, I was referencing the command, not the proto (same link I linked above):
https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/tools/Reporting.kt#L531.

I was generally trying to copy code from existing commands for consistency in both code and usage.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/tools/Reporting.kt` line 384 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1535#-Nu5bcPm8KOb9shQQ_6n:-Nu9l5nUEdSs_jjLflvo:bb6un1j) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/df52c84fc6ce864891fd47c7ecf3ef41de33151b/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/tools/Reporting.kt#L384)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Document that if not specified, the default of the system running this tool is used.
</blockquote></details>

Done
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/tools/Reporting.kt` line 396 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1535#-Nu5bohE2MYHhECZRGlf:-Nu5pZZB2JvzwVbSSCmU:b-qrw58r) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/df52c84fc6ce864891fd47c7ecf3ef41de33151b/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/tools/Reporting.kt#L396)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

We don't ever want to rely on splitting. We always want collection items to be specified multiple times instead.
</blockquote></details>

In progress

Sure, I'll refactor this. I copied it from the --grouping arg in the CreateCalculationMetricSpecCommand.
https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/tools/Reporting.kt#L509

Also noted from the README:
https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/tools/README.md?plain=1#L177-L178

I'll take a look today on how to replicate this behavior in args (from the create metric calculation specs section in the README), but might need some help next week. 
```
  --grouping='person.gender == 1,person.gender == 2' \
  --grouping='person.age_group == 1,person.age_group == 2' \
```


<!-- Sent from Reviewable.io -->

2024-04-03 14:29 UTC, bdomen-ggl reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1535)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/tools/README.md` line 150 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1535#-Nu5aVBLAndfCXg6gkeU:-NuQJ7r86P_keqEWEowh:b86niqo) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/df52c84fc6ce864891fd47c7ecf3ef41de33151b/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/tools/README.md#L150)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I think it's misleading to say they aren't used, since they are part of a Report. It's fine to mention they are created.
</blockquote></details>

Done

Oh I see. I'll redo that then. I meant it wasn't used explicitly in the UI or BFF code, not that it wasn't used at all. I'll reword to just say they're created.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/tools/Reporting.kt` line 384 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1535#-Nu5bcPm8KOb9shQQ_6n:-NuQJRKk6-3Lhu8Kaij8:bunehyx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/df52c84fc6ce864891fd47c7ecf3ef41de33151b/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/tools/Reporting.kt#L384)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I don't see any change to the description here.
</blockquote></details>

Done

Oh sorry, thought you meant "document" => README. I'll update this too.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/tools/Reporting.kt` line 396 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1535#-Nu5bohE2MYHhECZRGlf:-NuUb54wESbMIORccxvq:bevslfm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/df52c84fc6ce864891fd47c7ecf3ef41de33151b/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/tools/Reporting.kt#L396)):*
<details><summary><i>Previously, bdomen-ggl wrote…</i></summary><blockquote>

In progress

Sure, I'll refactor this. I copied it from the --grouping arg in the CreateCalculationMetricSpecCommand.
https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/tools/Reporting.kt#L509

Also noted from the README:
https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/tools/README.md?plain=1#L177-L178

I'll take a look today on how to replicate this behavior in args (from the create metric calculation specs section in the README), but might need some help next week. 
```
  --grouping='person.gender == 1,person.gender == 2' \
  --grouping='person.age_group == 1,person.age_group == 2' \
```
</blockquote></details>

Done

Created an arg group with --has-group to indicate a new list for the parser and --grouping to indicate a single predicate to add to the list of predicates for this group.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/tools/Reporting.kt` line 338 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1535#-NuPrhDP-sgPPdiE9fif:-NuQJGoc7osxnHwLSPCg:bm5sljn) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7e868da5692e0c50c40338004e652449e13e0da9/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/tools/Reporting.kt#L338)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: Don't need a multiline string here
</blockquote></details>

Done

I'll try that again. IIRC the linter suggested this. I have a couple other lints I need to fix anyways.


<!-- Sent from Reviewable.io -->

2024-04-03 18:07 UTC, SanjayVas requested changes
> Reviewed 2 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1535)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @bdomen-ggl)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/tools/Reporting.kt` line 396 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1535#-Nu5bohE2MYHhECZRGlf:-Nu_7Y6y4_SMvUnuP2A2:btvtznr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/df52c84fc6ce864891fd47c7ecf3ef41de33151b/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/tools/Reporting.kt#L396)):*
<details><summary><i>Previously, bdomen-ggl wrote…</i></summary><blockquote>

Done

Created an arg group with --has-group to indicate a new list for the parser and --grouping to indicate a single predicate to add to the list of predicates for this group.
</blockquote></details>

Let's go with `--grouping` for the boolean and `--predicate` for the predicate. This way the command line would look something like

```
--grouping \
--predicate='person.gender == 1' \
--predicate='person.gender == 2' \
--grouping \
--predicate='person.age_group == 1' \
--predicate='person.age_group == 2' \
```

This structure more closely matches the request message.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/tools/Reporting.kt` line 338 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1535#-NuPrhDP-sgPPdiE9fif:-Nu_7QYg278XGUFbem_t:b-yrxnqa) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7e868da5692e0c50c40338004e652449e13e0da9/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/tools/Reporting.kt#L338)):*
<details><summary><i>Previously, bdomen-ggl wrote…</i></summary><blockquote>

Done

I'll try that again. IIRC the linter suggested this. I have a couple other lints I need to fix anyways.
</blockquote></details>

```kotlin
["Day of the week for weekly frequency."]
```


<!-- Sent from Reviewable.io -->

2024-04-03 21:07 UTC, bdomen-ggl reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1535)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/tools/Reporting.kt` line 396 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1535#-Nu5bohE2MYHhECZRGlf:-Nu_ktuM79tix_A32o7I:bi7xh9f) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/df52c84fc6ce864891fd47c7ecf3ef41de33151b/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/tools/Reporting.kt#L396)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Let's go with `--grouping` for the boolean and `--predicate` for the predicate. This way the command line would look something like

```
--grouping \
--predicate='person.gender == 1' \
--predicate='person.gender == 2' \
--grouping \
--predicate='person.age_group == 1' \
--predicate='person.age_group == 2' \
```

This structure more closely matches the request message.
</blockquote></details>

Done

Got it, that sounds good. Updated the variables too.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/tools/Reporting.kt` line 338 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1535#-NuPrhDP-sgPPdiE9fif:-Nu_kqaP26e_2lYkjr27:buha4h2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7e868da5692e0c50c40338004e652449e13e0da9/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/tools/Reporting.kt#L338)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

```kotlin
["Day of the week for weekly frequency."]
```
</blockquote></details>

Thanks, not sure what's up with the linter here.


<!-- Sent from Reviewable.io -->

2024-04-03 21:45 UTC, SanjayVas requested changes
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1535)* status: all files reviewed, 1 unresolved discussion (waiting on @bdomen-ggl)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/tools/README.md` line 150 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1535#-Ntrcg9R1uOwamUNXqOg:-Nu_uvGG2UY9Mbz5JSsk:b-u5jv5i) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f9eb2278a6229cb4f02f105f56c48a38802ec30c/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/tools/README.md#L150)):*
<details><summary><i>Previously, bdomen-ggl wrote…</i></summary><blockquote>

Done

UI technically supports n >= 0 (although 0 and 1 would be really weird). I'll go ahead and update to support n >= 2.
</blockquote></details>

Note that docs still say "three groups" here.


<!-- Sent from Reviewable.io -->

2024-04-08 17:47 UTC, bdomen-ggl reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1535)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/tools/README.md` line 150 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1535#-Ntrcg9R1uOwamUNXqOg:-Nuer2-TAToqzgbtpwpV:b5ui21g) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f9eb2278a6229cb4f02f105f56c48a38802ec30c/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/tools/README.md#L150)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Note that docs still say "three groups" here.
</blockquote></details>

Thanks.

And sorry forgot to hit "publish"


<!-- Sent from Reviewable.io -->

2024-04-08 18:24 UTC, SanjayVas approved these changes
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1535)* status: all files reviewed, 1 unresolved discussion (waiting on @bdomen-ggl)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/tools/README.md` line 151 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1535#-Nuyx7c20gsZ3z6hTSiH:-Nuyx7c36Y_PXYfZ0eyo:b2ni8l0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/df1577dc25e6b18570226a4301e3060454d96076/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/tools/README.md#L151)):*
> ```Markdown
> ```
> 
> There currently needs to be at least two groups of primitive reporting sets defined by the arg group: --cmms-event-group, --reporting-set-id, and --reporting-set-display-name. You can pass in multiple event groups, but be sure to specify the display name or id first. There is a parsing issue if the id and display name are specified later in the arg group. This is similar to creating a reporting set.
> ```

nit



_Suggestion:_
```Markdown
ID
```


<!-- Sent from Reviewable.io -->

2024-04-09 15:01 UTC, bdomen-ggl reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1535)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/tools/README.md` line 151 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1535#-Nuyx7c20gsZ3z6hTSiH:-Nv2N6Pl5sqLJh5o1YYX:b-ni9y8p) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/df1577dc25e6b18570226a4301e3060454d96076/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/tools/README.md#L151)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit
</blockquote></details>

Done

There as another one below I updated too.


<!-- Sent from Reviewable.io -->

2024-04-09 17:18 UTC, SanjayVas approved these changes
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1535)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @bdomen-ggl)



<!-- Sent from Reviewable.io -->

2024-04-10 16:26 UTC, stevenwarejones approved these changes
> Reviewed 2 of 3 files at r6, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1535)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @bdomen-ggl)



<!-- Sent from Reviewable.io -->

2024-04-11 14:36 UTC, merged