Add requisition fulfillment for hmss.
world-federation-of-advertisers/cross-media-measurement pull request #1567
Opened 2024-04-12 18:36 UTC by ple13

2024-04-12 18:36 UTC, wfa-reviewable commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567)
<!-- Reviewable:end -->

2024-04-12 18:41 UTC, SanjayVas requested changes
> Reviewed 3 of 19 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567)* status: 3 of 19 files reviewed, 1 unresolved discussion (waiting on @kungfucraig, @ple13, and @renjiezh)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/BigQueryEdpSimulatorRunner.kt` line 65 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567#-NvIaseWDvrADgpWl3Kb:-NvIaseWDvrADgpWl3Kc:b-329ki2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/745f02483163d6def23766d2e1565478c9ad2b4f/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/BigQueryEdpSimulatorRunner.kt#L65)):*
> ```Kotlin
>     private set
> 
>   @set:CommandLine.Option(
> ```

This appears to be from #1562. If that PR is intended to be merged separately, set that PR branch as the base of this PR. This way the PR will only show diffs from your code.

Do not merge until that PR has been merged, which will result in the base of this PR automatically being set back to `main`.


<!-- Sent from Reviewable.io -->

2024-04-12 21:40 UTC, ple13 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567)* status: 3 of 19 files reviewed, 1 unresolved discussion (waiting on @kungfucraig, @renjiezh, and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/BigQueryEdpSimulatorRunner.kt` line 65 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567#-NvIaseWDvrADgpWl3Kb:-NvJFIJa69b1xqisK_rK:bs6o3j4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/745f02483163d6def23766d2e1565478c9ad2b4f/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/BigQueryEdpSimulatorRunner.kt#L65)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This appears to be from #1562. If that PR is intended to be merged separately, set that PR branch as the base of this PR. This way the PR will only show diffs from your code.

Do not merge until that PR has been merged, which will result in the base of this PR automatically being set back to `main`.
</blockquote></details>

Renjie has merged the PR and these diffs have gone.


<!-- Sent from Reviewable.io -->

2024-04-12 22:55 UTC, SanjayVas requested changes
> Reviewed 4 of 19 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567)* status: 7 of 19 files reviewed, 8 unresolved discussions (waiting on @kungfucraig, @ple13, and @renjiezh)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 182 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567#-NvJLhtKBNmb2-xSO3ME:-NvJLhtKBNmb2-xSO3MF:b-gqkazc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/26799c7c8320cad87110b2c66cdfb78cee0368fb/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L182)):*
> ```Kotlin
>   private val eventGroupMetadataDescriptorsStub: EventGroupMetadataDescriptorsCoroutineStub,
>   private val requisitionsStub: RequisitionsCoroutineStub,
>   private val requisitionFulfillmentStubMap: Map<String, RequisitionFulfillmentCoroutineStub>,
> ```

nit: The type/name is not sufficient to disambiguate what the map key is. There are a few options for this that can be used in combination:

1. Add documentation
2. Use a more specific strong type, such as `DuchyKey`.
3. Rename the property to be clearer. e.g. `requisitionFulfillmentStubsByDuchyName` (if continuing to use String)
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 199 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567#-NvJNOmF3_dpC8E_ETV3:-NvJNOmF3_dpC8E_ETV4:b2ni8l0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/26799c7c8320cad87110b2c66cdfb78cee0368fb/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L199)):*
> ```Kotlin
>   private val logSketchDetails: Boolean = false,
> ) {
>   // In the simulation, the Vid universe is obtained from event query. However, in the actual
> ```

nit



_Suggestion:_
```Kotlin
simulator, the VID universe
```
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 200 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567#-NvJOYMc4AJyAgVjbLRX:-NvJOYMc4AJyAgVjbLRY:b2ni8l0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/26799c7c8320cad87110b2c66cdfb78cee0368fb/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L200)):*
> ```Kotlin
> ) {
>   // In the simulation, the Vid universe is obtained from event query. However, in the actual
>   // implementation, the Edp must get it from the Vid model.
> ```

nit



_Suggestion:_
```Kotlin
the EDP must get it from the VID model
```
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 206 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567#-NvJOpWp9tMr6gz6kw0z:-NvJOpWp9tMr6gz6kw1-:b-oqhe02) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/26799c7c8320cad87110b2c66cdfb78cee0368fb/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L206)):*
> ```Kotlin
>   private val salt: ByteString = ByteString.EMPTY
> 
>   // Computes the vid to index map for the vid universe if not provided.
> ```

When would this be provided in the constructor vs. when would it be generated? Why not always generate?
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 499 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567#-NvJP0GC9tvzU7bbd-Yi:-NvJP0GC9tvzU7bbd-Yj:b-u5rn81) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/26799c7c8320cad87110b2c66cdfb78cee0368fb/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L499)):*
> ```Kotlin
>   ) {
>     require(
>       protocol == ProtocolConfig.Protocol.ProtocolCase.LIQUID_LEGIONS_V2 ||
> ```

nit: at this point could extract a constant `Set` with the supports protocol enums and just do

```kotlin
protocol in SUPPORTED_PROTOCOLS
```
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 1396 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567#-NvJV5hE7y2BDejGjVdb:-NvJV5hE7y2BDejGjVdc:b-33u5yk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/26799c7c8320cad87110b2c66cdfb78cee0368fb/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L1396)):*
> ```Kotlin
>   }
> 
>   private suspend fun fulfillHmssRequisition(
> ```

There are two functions here with similar names, this and `fulfillRequisitionForHmssMeasurement`.

From looking at existing code, I'm assuming this function is equivalent to `fulfillRequisition` but taking into account the need to fulfill at two different Duchies? Perhaps just make this an overload of `fulfillRequisition`, since it is doing effectively the same thing. To make the two functions more similar, you can change the other overload to take in the Requisition instead of just its resource name. Then the two signature would differ by the fact that one has single data ByteString and this has the seed and vector.



_Code quote:_
```Kotlin
fulfillHmssRequisition
```
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorRunner.kt` line 82 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567#-NvJVyqWDqsQsUd_UTe8:-NvJVyqWDqsQsUd_UTe9:b-n258jr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/26799c7c8320cad87110b2c66cdfb78cee0368fb/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorRunner.kt#L82)):*
> ```Kotlin
>         )
>       )
>     // TODO(@ple13): Update the requisition fulfillment stub map when multiple fulfillment targets
> ```

This TODO should be handled in this PR. Otherwise the simulator will be claiming it supports HMSS but cannot in fact fulfill those requisitions.


<!-- Sent from Reviewable.io -->

2024-04-15 04:24 UTC, renjiezh requested changes
> Reviewed 11 of 19 files at r1, 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567)* status: all files reviewed, 12 unresolved discussions (waiting on @kungfucraig, @ple13, and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/api/v2alpha/PrivacyQueryMapper.kt` line 133 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567#-NvUqGEp5ovXD9iicXjG:-NvUqGEp5ovXD9iicXjH:bmzlc2y) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/26799c7c8320cad87110b2c66cdfb78cee0368fb/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/api/v2alpha/PrivacyQueryMapper.kt#L133)):*
> ```Kotlin
>             )
> 
>           AcdpParamsConverter.getLlv2AcdpCharge(dpParams, contributorCount)
> ```

Rename `getLlv2AcdpCharge`. E.g. getAcdpCharge()
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 1309 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567#-NvUyyxIEssYdXBpyZtb:-NvUyyxIEssYdXBpyZtc:b-cairqt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/26799c7c8320cad87110b2c66cdfb78cee0368fb/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L1309)):*
> ```Kotlin
>   }
> 
>   private suspend fun getDuchyWithoutPublicKey(requisition: Requisition): String {
> ```

I wonder if we can move these checks into the function `verifyDuchyEntries()`? So that we only find the public key here. This helps us to fail the action earlier without charging budget.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 1368 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567#-NvUxQ4h4NcjhnKdvQHW:-NvUxQ4h4NcjhnKdvQHX:bto63ht) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/26799c7c8320cad87110b2c66cdfb78cee0368fb/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L1368)):*
> ```Kotlin
> 
>     val secretShareGeneratorRequest =
>       SecretShareGeneratorRequest.newBuilder()
> ```

use dsl instead of builder. It is like this:
```
val secretShareGeneratorRequest = secretShareGeneratorRequest {
  data += frequencyVector
  ringModulus = protocolConfig.sketchParams.ringModulus
}
```
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 1396 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567#-NvJV5hE7y2BDejGjVdb:-NvUy-ga54A-RY3XLvsD:b-ovwaw7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/26799c7c8320cad87110b2c66cdfb78cee0368fb/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L1396)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

There are two functions here with similar names, this and `fulfillRequisitionForHmssMeasurement`.

From looking at existing code, I'm assuming this function is equivalent to `fulfillRequisition` but taking into account the need to fulfill at two different Duchies? Perhaps just make this an overload of `fulfillRequisition`, since it is doing effectively the same thing. To make the two functions more similar, you can change the other overload to take in the Requisition instead of just its resource name. Then the two signature would differ by the fact that one has single data ByteString and this has the seed and vector.
</blockquote></details>

Good idea.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 1428 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567#-NvUyDvl0e6d0-8uRMbc:-NvUyDvl0e6d0-8uRMbd:brpln3q) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/26799c7c8320cad87110b2c66cdfb78cee0368fb/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L1428)):*
> ```Kotlin
>     try {
>       val requisitionFulfillmentStub =
>         requisitionFulfillmentStubMap.get(getDuchyWithoutPublicKey(requisition))
> ```

Here could be 
```
map.getOrElse { throw(...) }
```
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorRunner.kt` line 82 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567#-NvJVyqWDqsQsUd_UTe8:-NvUrK3Q04o-8yWTif3v:b1jw4kp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/26799c7c8320cad87110b2c66cdfb78cee0368fb/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorRunner.kt#L82)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This TODO should be handled in this PR. Otherwise the simulator will be claiming it supports HMSS but cannot in fact fulfill those requisitions.
</blockquote></details>

I will finish this part in my PR along with .cue files updated. I feel a TODO is fine here. 
With this PR, EdpSimulator is still not ready to fulfill HMSS requisitions by lacking of executable and configuration updated. Besides, we need capability as a feature flag to enable it. 


<!-- Sent from Reviewable.io -->

2024-04-15 15:21 UTC, SanjayVas requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567)* status: all files reviewed, 12 unresolved discussions (waiting on @kungfucraig, @ple13, and @renjiezh)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorRunner.kt` line 82 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567#-NvJVyqWDqsQsUd_UTe8:-NvXKMrsCIZANkB_1AjX:bhedafl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/26799c7c8320cad87110b2c66cdfb78cee0368fb/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorRunner.kt#L82)):*
> Besides, we need capability as a feature flag to enable it.

The state of HMSS enablement in the Kingdom is irrelevant to the EDP simulator behavior. The simulator should not claim to support a protocol (i.e. attempt to fulfill Requisitions with that protocol) if it cannot.

> I will finish this part in my PR along with .cue files updated.

Can we have whatever PR is needed to support this (i.e. plumbing in multiple fulfillment service targets) go in first?


<!-- Sent from Reviewable.io -->

2024-04-16 20:15 UTC, kungfucraig requested changes
> Reviewed 7 of 19 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567)* status: all files reviewed, 14 unresolved discussions (waiting on @ple13, @renjiezh, and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 207 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567#-NvcXI0J2mQsYLruD5wt:-NvcXI0J2mQsYLruD5wu:b-v9pkvj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/26799c7c8320cad87110b2c66cdfb78cee0368fb/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L207)):*
> ```Kotlin
> 
>   // Computes the vid to index map for the vid universe if not provided.
>   private val vidToIndexMap =
> ```

Don't we need one of these per EventQuery and for the synthetic event spec case, per Synthetic Population? Or perhaps we instantiate this class per fulfillment? 

Ideally we'd only build this IndexMaps once for the lifetime of the simulator.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 1003 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567#-NvcW3gd3pPkp31X7wF1:-NvcW3gd3pPkp31X7wF2:b-acdka1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/26799c7c8320cad87110b2c66cdfb78cee0368fb/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L1003)):*
> ```Kotlin
>           )
>         }
>         PrivacyBudgetManagerExceptionType.INCORRECT_NOISE_MECHANISM -> {
> ```

Given the error checking above, this should not be possible, should it?


<!-- Sent from Reviewable.io -->

2024-04-23 04:22 UTC, ple13 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567)* status: 12 of 23 files reviewed, 10 unresolved discussions (waiting on @kungfucraig, @renjiezh, and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/api/v2alpha/PrivacyQueryMapper.kt` line 133 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567#-NvUqGEp5ovXD9iicXjG:-Nw67fFo5eqXn8MoKZnV:bvnjh1u) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/26799c7c8320cad87110b2c66cdfb78cee0368fb/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/api/v2alpha/PrivacyQueryMapper.kt#L133)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

Rename `getLlv2AcdpCharge`. E.g. getAcdpCharge()
</blockquote></details>

+1 that we need to change the names to make them accurate (for example, the implementation seems to be dependent on the noise type, not the protocol type, and needs to be fixed). However, I suggest that the naming should be done in another PR (possible when we add the support for binomial noise). I'll add a TODO to keep track of it. WDYT?
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 182 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567#-NvJLhtKBNmb2-xSO3ME:-Nw6IL2DCGBhmL2Qix3G:b-hx0950) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/26799c7c8320cad87110b2c66cdfb78cee0368fb/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L182)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: The type/name is not sufficient to disambiguate what the map key is. There are a few options for this that can be used in combination:

1. Add documentation
2. Use a more specific strong type, such as `DuchyKey`.
3. Rename the property to be clearer. e.g. `requisitionFulfillmentStubsByDuchyName` (if continuing to use String)
</blockquote></details>

Done. I've updated the name to requisitionFulfillmentStubsByDuchyName.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 199 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567#-NvJNOmF3_dpC8E_ETV3:-Nw5aofY0TdXxPrdPWIG:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/26799c7c8320cad87110b2c66cdfb78cee0368fb/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L199)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 200 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567#-NvJOYMc4AJyAgVjbLRX:-NvmcrE-6hBs2-zi-Hhf:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/26799c7c8320cad87110b2c66cdfb78cee0368fb/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L200)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 206 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567#-NvJOpWp9tMr6gz6kw0z:-Nw6fJGc3uSWIeiPxjKG:b8vzf5p) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/26799c7c8320cad87110b2c66cdfb78cee0368fb/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L206)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

When would this be provided in the constructor vs. when would it be generated? Why not always generate?
</blockquote></details>

Ideally we want the vidToIndexMap to be pre-computed or read from a file as the computation of the map is time consuming. The EDP simulator will just pick it up and uses the map for all requisitions.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 207 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567#-NvcXI0J2mQsYLruD5wt:-Nw5f3-o0h6Bsz5ptTbv:b-9rf7qv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/26799c7c8320cad87110b2c66cdfb78cee0368fb/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L207)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Don't we need one of these per EventQuery and for the synthetic event spec case, per Synthetic Population? Or perhaps we instantiate this class per fulfillment? 

Ideally we'd only build this IndexMaps once for the lifetime of the simulator.
</blockquote></details>

Thanks for pointing this out. I added inputVidUniverse to the constructor, and the EDP only computes the vidUniverse if not provided and inputVidToIndex map is empty.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 499 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567#-NvJP0GC9tvzU7bbd-Yi:-Nw6ft5FDY6RyznPuu5V:b-nm9tdz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/26799c7c8320cad87110b2c66cdfb78cee0368fb/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L499)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: at this point could extract a constant `Set` with the supports protocol enums and just do

```kotlin
protocol in SUPPORTED_PROTOCOLS
```
</blockquote></details>

Done. Kotlin only supports set<T> where T is a primitive type.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 1003 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567#-NvcW3gd3pPkp31X7wF1:-Nvme3-jAb6-RW3e2jI3:b-ki2gbf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/26799c7c8320cad87110b2c66cdfb78cee0368fb/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L1003)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Given the error checking above, this should not be possible, should it?
</blockquote></details>

This is the caught exception if the check for noise type fails.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 1309 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567#-NvUyyxIEssYdXBpyZtb:-Nw6Q-HAE2M3fgPW0ax7:b-q6xpm5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/26799c7c8320cad87110b2c66cdfb78cee0368fb/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L1309)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

I wonder if we can move these checks into the function `verifyDuchyEntries()`? So that we only find the public key here. This helps us to fail the action earlier without charging budget.
</blockquote></details>

Yeah, this is a good idea.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 1368 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567#-NvUxQ4h4NcjhnKdvQHW:-Nvme_Xk4yD1rgTDMFr3:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/26799c7c8320cad87110b2c66cdfb78cee0368fb/src/main/kotlin/org/wfanet/me [...]

2024-04-23 18:39 UTC, SanjayVas requested changes
> Reviewed 10 of 13 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567)* status: 20 of 23 files reviewed, 13 unresolved discussions (waiting on @kungfucraig, @ple13, @renjiezh, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/AcdpParamsConverter.kt` line 27 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567#-NwB8SrX1obMFq5MXYe2:-NwB8SrX1obMFq5MXYe3:b4wxabp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/25b63bb0f7287193b4536c87967109d2190ad719/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/AcdpParamsConverter.kt#L27)):*
> ```Kotlin
> import org.wfanet.measurement.eventdataprovider.noiser.GaussianNoiser
> 
> // TODO(@ple13): Refactor the AcdpParamsConverter object to take the noise type into account.
> ```

nit: move this TODO into the KDoc block for the object.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 182 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567#-NvJLhtKBNmb2-xSO3ME:-NwB8nm83yBBe72sRXQf:b1ewau2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/26799c7c8320cad87110b2c66cdfb78cee0368fb/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L182)):*
<details><summary><i>Previously, ple13 (Phi) wrote…</i></summary><blockquote>

Done. I've updated the name to requisitionFulfillmentStubsByDuchyName.
</blockquote></details>

I believe this was changed in #1574 which has already been merged. Please sync this PR branch.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 206 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567#-NvJOpWp9tMr6gz6kw0z:-NwB9EsA7yWUsmSJRqLX:b-7qu0h2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/26799c7c8320cad87110b2c66cdfb78cee0368fb/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L206)):*
<details><summary><i>Previously, ple13 (Phi) wrote…</i></summary><blockquote>

Ideally we want the vidToIndexMap to be pre-computed or read from a file as the computation of the map is time consuming. The EDP simulator will just pick it up and uses the map for all requisitions.
</blockquote></details>

So then why does this ever allow it to be omitted? Just trying to avoid having unnecessary branching paths.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 499 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567#-NvJP0GC9tvzU7bbd-Yi:-NwB9zYn8CTJhRRzckTJ:bxm4ro4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/26799c7c8320cad87110b2c66cdfb78cee0368fb/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L499)):*
> Kotlin only supports set where T is a primitive type.

This is definitely not true. Perhaps you were confused with the fact that the `const` keyword only applies to compile-time constants? Not all constants need the `const` keyword.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 560 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567#-NwBAQUNESUhww-kFvF9:-NwBAQUNESUhww-kFvFA:bnqoixc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/25b63bb0f7287193b4536c87967109d2190ad719/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L560)):*
> ```Kotlin
>    * Verify duchy entries.
>    *
>    * For each duchy entry, verifies its certificate. Return true for valid or false for invalid. If
> ```

This is not how this method behaves. It throws a `RequisitionRefusalException` if it's invalid.



_Code quote:_
```Kotlin
Return true for valid or false for invalid.
```
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 590 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567#-NwBB01l2CR9rREwTOPa:-NwBB01l2CR9rREwTOPb:b-46ts1v) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/25b63bb0f7287193b4536c87967109d2190ad719/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L590)):*
> ```Kotlin
>         )
>         throw RequisitionRefusalException(
>           Requisition.Refusal.Justification.UNFULFILLABLE,
> ```

UNFULFILLABLE is for cases where the failure is on the DataProvider end, meaning something is wrong in the EDP's system but the Requisition is itself valid. See the [enum value documentation](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/7c8702ed832c51fdcc2b22917ee4a91c0fb11377/src/main/proto/wfa/measurement/api/v2alpha/requisition.proto#L234).



_Suggestion:_
```Kotlin
SPEC_INVALID
```
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 1372 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567#-NwBCv83AzfZJ7UdJtQ0:-NwBCv83AzfZJ7UdJtQ1:bsm6d1d) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/25b63bb0f7287193b4536c87967109d2190ad719/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L1372)):*
> ```Kotlin
>         requisitionFulfillmentStubsByDuchyName.getOrElse(getDuchyWithoutPublicKey(requisition)) {
>           throw RuntimeException("Requisition fulfillment stub not found.")
>         }
> ```

1. Elvis operator is preferred over getOrElse here
2. RuntimeException and Exception aren't meaningfully different in Kotlin. Just use Exception, unless writing something that is meant to be called from Java.



_Suggestion:_
```Kotlin
      val requisitionFulfillmentStub =
        requisitionFulfillmentStubsByDuchyName[getDuchyWithoutPublicKey(requisition)] ?: throw Exception("Requisition fulfillment stub not found.")
```
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 1388 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567#-NwBE3ix2EzhmgH7eWca:-NwBE3ix2EzhmgH7eWcb:b-ajkmvi) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/25b63bb0f7287193b4536c87967109d2190ad719/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L1388)):*
> ```Kotlin
>     }
> 
>     return publicKeyList.first()
> ```

Can be rewritten more concisely with `singleOrNull`. Also prefer keeping specific types, keeping basic type access/conversion until the last moment.



_Suggestion:_
```Kotlin
    return requisition.duchiesList
        .singleOrNull { it.value.honestMajorityShareShuffle.hasPublicKey() }?.map { it.key } ?: throw IllegalArgumentException("Expected exactly one Duchy entry with an HMSS encryption public key.")
```


<!-- Sent from Reviewable.io -->

2024-04-23 22:56 UTC, kungfucraig reviewed
> Reviewed 2 of 19 files at r1, 11 of 13 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567)* status: 21 of 23 files reviewed, 12 unresolved discussions (waiting on @ple13, @renjiezh, @SanjayVas, and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2024-04-23 22:58 UTC, kungfucraig reviewed
I'm going to take a pass on reviewing this in detail as I think I'll add much value beyond Sanjay and Renjie.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567#-:-NwCATyo0wcThWjtGbnx:b-hywdt4)* status: 21 of 23 files reviewed, 11 unresolved discussions (waiting on @ple13, @renjiezh, @SanjayVas, and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2024-04-24 19:50 UTC, ple13 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567)* status: 19 of 24 files reviewed, 10 unresolved discussions (waiting on @kungfucraig, @renjiezh, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/AcdpParamsConverter.kt` line 27 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567#-NwB8SrX1obMFq5MXYe2:-NwGXKJTBY1wz3jy0rPu:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/25b63bb0f7287193b4536c87967109d2190ad719/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/AcdpParamsConverter.kt#L27)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: move this TODO into the KDoc block for the object.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 182 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567#-NvJLhtKBNmb2-xSO3ME:-NwBr-KXAy1LXXb4XONs:b1dopa0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/26799c7c8320cad87110b2c66cdfb78cee0368fb/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L182)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I believe this was changed in #1574 which has already been merged. Please sync this PR branch.
</blockquote></details>

Yeah, Renjie has the mapping DuchyId to stub. However, it's more convenient to have the mapping DuchyName to stub as the DuchyName is the same as the DuchyEntry's key.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 206 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567#-NvJOpWp9tMr6gz6kw0z:-NwGZM6x5zXNKDocQhdu:b-3mjft9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/26799c7c8320cad87110b2c66cdfb78cee0368fb/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L206)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

So then why does this ever allow it to be omitted? Just trying to avoid having unnecessary branching paths.
</blockquote></details>

I've updated the code to have vidToIndexMap to be initialized from inputVidToIndexMap only. In the actual deployment, we either pass a non-empty inputVidToIndexMap, or have the EdpSimulator read the map from a file. We had the branch to compute the map before, but this requires too much memory and causes the integration tests to fail (as the map is computed even from Llv2 protocols).
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 499 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567#-NvJP0GC9tvzU7bbd-Yi:-NwBrJ9l-5fDzlq_dm7M:b-ntwjpf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/26799c7c8320cad87110b2c66cdfb78cee0368fb/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L499)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> Kotlin only supports set where T is a primitive type.

This is definitely not true. Perhaps you were confused with the fact that the `const` keyword only applies to compile-time constants? Not all constants need the `const` keyword.
</blockquote></details>

Yeah, I meant kotlin complains when there is the constant keyword.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 560 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567#-NwBAQUNESUhww-kFvF9:-NwGY7lFDlvZL8kQGs05:b1pun28) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/25b63bb0f7287193b4536c87967109d2190ad719/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L560)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This is not how this method behaves. It throws a `RequisitionRefusalException` if it's invalid.
</blockquote></details>

I've updated the comment to make it consistent with the function's behavior.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 590 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567#-NwBB01l2CR9rREwTOPa:-NwBrnbr60eyBGVdyZFo:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/25b63bb0f7287193b4536c87967109d2190ad719/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L590)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

UNFULFILLABLE is for cases where the failure is on the DataProvider end, meaning something is wrong in the EDP's system but the Requisition is itself valid. See the [enum value documentation](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/7c8702ed832c51fdcc2b22917ee4a91c0fb11377/src/main/proto/wfa/measurement/api/v2alpha/requisition.proto#L234).
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 1372 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567#-NwBCv83AzfZJ7UdJtQ0:-NwBsGAZCene0bJ73Txg:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/25b63bb0f7287193b4536c87967109d2190ad719/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L1372)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

1. Elvis operator is preferred over getOrElse here
2. RuntimeException and Exception aren't meaningfully different in Kotlin. Just use Exception, unless writing something that is meant to be called from Java.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 1388 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567#-NwBE3ix2EzhmgH7eWca:-NwGMnkk6CKwWtr6j6CO:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/25b63bb0f7287193b4536c87967109d2190ad719/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L1388)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Can be rewritten more concisely with `singleOrNull`. Also prefer keeping specific types, keeping basic type access/conversion until the last moment.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-04-24 21:00 UTC, SanjayVas requested changes
> Reviewed 1 of 19 files at r1, 1 of 13 files at r3, 3 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567)* status: 22 of 24 files reviewed, 10 unresolved discussions (waiting on @ple13, @renjiezh, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 206 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567#-NvJOpWp9tMr6gz6kw0z:-NwGmmr64iSOIOuI5jAW:bp4rcib) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/26799c7c8320cad87110b2c66cdfb78cee0368fb/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L206)):*
<details><summary><i>Previously, ple13 (Phi) wrote…</i></summary><blockquote>

I've updated the code to have vidToIndexMap to be initialized from inputVidToIndexMap only. In the actual deployment, we either pass a non-empty inputVidToIndexMap, or have the EdpSimulator read the map from a file. We had the branch to compute the map before, but this requires too much memory and causes the integration tests to fail (as the map is computed even from Llv2 protocols).
</blockquote></details>

The property still has a default value, implying it's optional.

My point is that we shouldn't have two ways to initialize it here and instead have it always passed in. It's the calling code that can be responsible for how to populate the map.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 200 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567#-NwGmbDR3egDy1ye-KMk:-NwGmbDR3egDy1ye-KMl:btgq0os) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4a295118ab16fb75c3fb2f79dc08063e4510c129/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L200)):*
> ```Kotlin
>   private val logSketchDetails: Boolean = false,
> ) {
>   // Initializes the vidToIndexMap.
> ```

Use KDoc syntax for properties.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 202 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567#-NwGnANa3I4qFyOO917g:-NwGnANa3I4qFyOO917h:bq15x8g) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4a295118ab16fb75c3fb2f79dc08063e4510c129/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L202)):*
> ```Kotlin
>   // Initializes the vidToIndexMap.
>   //
>   // TODO(@ple13): Ensure that the vidToIndexMap has been properly initialized at this point (either
> ```

This TODO is not accurate (or at least it's in the wrong place). As per the other comment, the only option is to pass a `inputVidToIndexMap`. Any file reading or computation can be handled in the corresponding EdpSimulatorRunner, as that's the class that would e.g. have a flag specifying a file to read from.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 1382 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567#-NwGpFR35Ei5lR-3U5Hu:-NwGpFR35Ei5lR-3U5Hv:bjvlbho) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4a295118ab16fb75c3fb2f79dc08063e4510c129/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L1382)):*
> ```Kotlin
>       ?: throw IllegalArgumentException(
>         "Expected exactly one Duchy entry with an HMSS encryption public key."
>       )
> ```

nit: use a variable to avoid having a lot of null-safe chaining



_Suggestion:_
```Kotlin
    val honestMajorityShareShuffle = requisition.duchiesList
      .map { it.value.honestMajorityShareShuffle }
      .singleOrNull { it.hasPublicKey() }
      ?: throw IllegalArgumentException(
        "Expected exactly one Duchy entry with an HMSS encryption public key."
      )
    return honestMajorityShareShuffle.publicKey
```


<!-- Sent from Reviewable.io -->

2024-04-29 16:15 UTC, ple13 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567)* status: 21 of 24 files reviewed, 9 unresolved discussions (waiting on @renjiezh, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 206 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567#-NvJOpWp9tMr6gz6kw0z:-NweV8CH-7G8Cl41gpe-:byf21ka) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/26799c7c8320cad87110b2c66cdfb78cee0368fb/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L206)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The property still has a default value, implying it's optional.

My point is that we shouldn't have two ways to initialize it here and instead have it always passed in. It's the calling code that can be responsible for how to populate the map.
</blockquote></details>

I've updated the code to have it passed in.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 200 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567#-NwGmbDR3egDy1ye-KMk:-NweVMr8-OwWMFMsloV1:b69kmyu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4a295118ab16fb75c3fb2f79dc08063e4510c129/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L200)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Use KDoc syntax for properties.
</blockquote></details>

This code has been removed.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 202 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567#-NwGnANa3I4qFyOO917g:-NweVVvH9evYhypgagu7:b69kmyu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4a295118ab16fb75c3fb2f79dc08063e4510c129/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L202)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This TODO is not accurate (or at least it's in the wrong place). As per the other comment, the only option is to pass a `inputVidToIndexMap`. Any file reading or computation can be handled in the corresponding EdpSimulatorRunner, as that's the class that would e.g. have a flag specifying a file to read from.
</blockquote></details>

This code has been removed.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 1382 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567#-NwGpFR35Ei5lR-3U5Hu:-NwLNvk64-EuWpF8kxIt:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4a295118ab16fb75c3fb2f79dc08063e4510c129/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L1382)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: use a variable to avoid having a lot of null-safe chaining
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-04-29 17:49 UTC, SanjayVas requested changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567)* status: 22 of 24 files reviewed, 12 unresolved discussions (waiting on @ple13, @renjiezh, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 206 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567#-NvJOpWp9tMr6gz6kw0z:-NweunlnDyeW_30x4Azg:bw7p3gn) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/26799c7c8320cad87110b2c66cdfb78cee0368fb/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L206)):*
<details><summary><i>Previously, ple13 (Phi) wrote…</i></summary><blockquote>

I've updated the code to have it passed in.
</blockquote></details>

I still see the default value for the constructor param.

```kotlin
private val vidToIndexMap: Map<Long, IndexedValue> = emptyMap()
```
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 200 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567#-Nwev0UQADmVlu06LDuv:-Nwev0UQADmVlu06LDuw:bb3m652) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/131e5c6a21808519a2e286ffa12ea90226b2086f/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L200)):*
> ```Kotlin
>   private val logSketchDetails: Boolean = false,
> ) {
>   private val SUPPORTED_PROTOCOLS =
> ```

Define this in the companion object since it's not an instance property.
___
*[`src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt` line 210 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567#-Nwevk79-mQprJaWTTz1:-Nwevk79-mQprJaWTTz2:b-he1rlj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/131e5c6a21808519a2e286ffa12ea90226b2086f/src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt#L210)):*
> ```Kotlin
> }
> 
> // private val DUCHY1_ENCRYPTION_PUBLIC_KEY = encryptionPublicKey {
> ```

Remove commented-out code.
___
*[`src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt` line 244 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567#-NwewGCnDlxZ7PnIUbLN:-NwewGCnDlxZ7PnIUbLO:undefined) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/131e5c6a21808519a2e286ffa12ea90226b2086f/src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt#L244)):*
> ```Kotlin
>       .thenReturn(DUCHY_ONE_CERTIFICATE)
>     onBlocking { getCertificate(eq(getCertificateRequest { name = DUCHY_TWO_CERTIFICATE.name })) }
>       .thenReturn(DUCHY_ONE_CERTIFICATE)
> ```





_Suggestion:_
```Kotlin
DUCHY_TWO_CERTIFICATE
```
___
*[`src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt` line 663 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567#-NwexgmUB4XSVEYKg9kq:-NwexgmV3_b5XMd-wGjx:b2ni8l0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/131e5c6a21808519a2e286ffa12ea90226b2086f/src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt#L663)):*
> ```Kotlin
> 
>   @Test
>   fun `refuses Hmss requisition due to invaild number of duchy entries`() {
> ```

nit



_Suggestion:_
```Kotlin
HMSS Requisition due to invalid
```
___
*[`src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt` line 860 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567#-Nwexs2u01TTQF1p1Nrv:-Nwexs2u01TTQF1p1Nrw:bpu3hpx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/131e5c6a21808519a2e286ffa12ea90226b2086f/src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt#L860)):*
> ```Kotlin
> 
>   @Test
>   fun `fulfills Hmss reach and frequency requisition without precomputed vid to index map`() {
> ```

The precomputed map must always be specified. Therefore I would expect this test to fail.
___
*[`src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt` line 1449 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567#-Nwey6vqChVVWYtEVUMt:-Nwey6vqChVVWYtEVUMu:b-2kyig2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/131e5c6a21808519a2e286ffa12ea90226b2086f/src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt#L1449)):*
> ```Kotlin
>   @Test
>   fun `refuses requisition when DuchyEntry verification fails`() {
> ```

Why were all of these swapped? The refusal tests were using a mock since refusal should happen before the EventQuery is called.


<!-- Sent from Reviewable.io -->

2024-04-29 17:49 UTC, SanjayVas requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567)* status: 22 of 24 files reviewed, 13 unresolved discussions (waiting on @ple13, @renjiezh, and @stevenwarejones)

___
*[`src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt` line 3149 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567#-NweySmi7qMw4QwtFJSd:-NweySmi7qMw4QwtFJSe:bf7ztad) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/131e5c6a21808519a2e286ffa12ea90226b2086f/src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt#L3149)):*
> ```Kotlin
>     }
> 
>     private val duchyEntryOne = duchyEntry {
> ```

Use CONST_CASE for constants like this.



_Code quote:_
```Kotlin
duchyEntryOne
```


<!-- Sent from Reviewable.io -->

2024-04-30 15:20 UTC, ple13 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567)* status: 19 of 24 files reviewed, 12 unresolved discussions (waiting on @kungfucraig, @renjiezh, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 206 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567#-NvJOpWp9tMr6gz6kw0z:-NwfS7Q74ljx2-fIDTK4:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/26799c7c8320cad87110b2c66cdfb78cee0368fb/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L206)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I still see the default value for the constructor param.

```kotlin
private val vidToIndexMap: Map<Long, IndexedValue> = emptyMap()
```
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 200 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567#-Nwev0UQADmVlu06LDuv:-NwfSItm1j6pJHTarRvX:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/131e5c6a21808519a2e286ffa12ea90226b2086f/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L200)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Define this in the companion object since it's not an instance property.
</blockquote></details>

Done.
___
*[`src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt` line 210 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567#-Nwevk79-mQprJaWTTz1:-NwfSVf61hKmhccoBY4f:bs7wumx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/131e5c6a21808519a2e286ffa12ea90226b2086f/src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt#L210)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Remove commented-out code.
</blockquote></details>

Done. 
___
*[`src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt` line 244 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567#-NwewGCnDlxZ7PnIUbLN:-NwfSny652ZQwWKfE8zX:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/131e5c6a21808519a2e286ffa12ea90226b2086f/src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt#L244)):*
> ```Kotlin
>       .thenReturn(DUCHY_ONE_CERTIFICATE)
>     onBlocking { getCertificate(eq(getCertificateRequest { name = DUCHY_TWO_CERTIFICATE.name })) }
>       .thenReturn(DUCHY_ONE_CERTIFICATE)
> ```

Done.
___
*[`src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt` line 663 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567#-NwexgmUB4XSVEYKg9kq:-NwfT2xU9w1bve0AOIiK:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/131e5c6a21808519a2e286ffa12ea90226b2086f/src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt#L663)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit
</blockquote></details>

Done.
___
*[`src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt` line 860 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567#-Nwexs2u01TTQF1p1Nrv:-NwfXHe22tqysHlNwPis:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/131e5c6a21808519a2e286ffa12ea90226b2086f/src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt#L860)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The precomputed map must always be specified. Therefore I would expect this test to fail.
</blockquote></details>

Done.
___
*[`src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt` line 1449 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567#-Nwey6vqChVVWYtEVUMt:-NwfUOFRC2Ot6SNQ-UMk:b-jitmhr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/131e5c6a21808519a2e286ffa12ea90226b2086f/src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt#L1449)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Why were all of these swapped? The refusal tests were using a mock since refusal should happen before the EventQuery is called.
</blockquote></details>

I've put the mock object back. I planned to have the EdpSimulator to compute the vidToIndexMap using eventQuery before. It's not the case any more as vidToIndexMap will always be passed in.
___
*[`src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt` line 3149 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567#-NweySmi7qMw4QwtFJSd:-NwfWo2j05D7M4aWPLCX:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/131e5c6a21808519a2e286ffa12ea90226b2086f/src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt#L3149)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Use CONST_CASE for constants like this.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-04-30 20:20 UTC, SanjayVas requested changes
> Reviewed 8 of 8 files at r2, 1 of 13 files at r3, 3 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567)* status: 23 of 24 files reviewed, 8 unresolved discussions (waiting on @ple13, @renjiezh, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 836 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567#-NwkdXHL4InE42DBf6GU:-NwkdXHL4InE42DBf6GV:b33l8cd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/394e2e5a35689a98469db7cec90c9a625cefd19a/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L836)):*
> ```Kotlin
>             )
>             throw RequisitionRefusalException(
>               Requisition.Refusal.Justification.SPEC_INVALID,
> ```

This is a case where the EDP *should* be able to fulfill, but is unable due to a configuration error on its end.

Note that this technically represents a programming error, meaning it would be correct to throw an exception from the constructor and not allow the EdpSimulator to start rather than handling it here.



_Suggestion:_
```Kotlin
UNFULFILLABLE
```


<!-- Sent from Reviewable.io -->

2024-04-30 20:41 UTC, ple13 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567)* status: 22 of 24 files reviewed, 8 unresolved discussions (waiting on @renjiezh, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 836 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567#-NwkdXHL4InE42DBf6GU:-NwkiW-8ACAVkHgPmPqv:b-8b569i) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/394e2e5a35689a98469db7cec90c9a625cefd19a/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L836)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This is a case where the EDP *should* be able to fulfill, but is unable due to a configuration error on its end.

Note that this technically represents a programming error, meaning it would be correct to throw an exception from the constructor and not allow the EdpSimulator to start rather than handling it here.
</blockquote></details>

Thanks, I've updated it. Currently we only need the vidToIndexMap for HMSS requisition fulfillment, so checking for a map in the constructor will cause issues for LLV2 requisition fulfillment.


<!-- Sent from Reviewable.io -->

2024-04-30 22:10 UTC, SanjayVas requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567)* status: 22 of 24 files reviewed, 9 unresolved discussions (waiting on @ple13, @renjiezh, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 836 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567#-NwkdXHL4InE42DBf6GU:-Nwl-XaL0s7oP6pC-TUK:blw4zqi) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/394e2e5a35689a98469db7cec90c9a625cefd19a/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L836)):*
<details><summary><i>Previously, ple13 (Phi) wrote…</i></summary><blockquote>

Thanks, I've updated it. Currently we only need the vidToIndexMap for HMSS requisition fulfillment, so checking for a map in the constructor will cause issues for LLV2 requisition fulfillment.
</blockquote></details>

This PR is to update the EDP simulator so that it supports fulfilling HMSS Requisitions. That means it should *always* supports fulfilling said Requisitions. This in turn means that vidToIndexMap must never be empty.

Another option is to make it so that the capability is conditional based on whether a vidToIndexMap is passed in.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 214 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567#-Nwl2fwd-kPR7QPIWOQX:-Nwl2fwd-kPR7QPIWOQY:b-41fyba) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e6ffc2246593fa4143080e6780dea38dcd620ea4/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L214)):*
> ```Kotlin
>         }
>       }
>     )
> ```

Need to also update the EDP capabilities here to indicate whether HMSS is supported.


<!-- Sent from Reviewable.io -->

2024-05-01 05:16 UTC, ple13 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567)* status: 22 of 24 files reviewed, 9 unresolved discussions (waiting on @renjiezh, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 836 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567#-NwkdXHL4InE42DBf6GU:-NwmSqsA8Hl24cxNb7zJ:b35q6e6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/394e2e5a35689a98469db7cec90c9a625cefd19a/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L836)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This PR is to update the EDP simulator so that it supports fulfilling HMSS Requisitions. That means it should *always* supports fulfilling said Requisitions. This in turn means that vidToIndexMap must never be empty.

Another option is to make it so that the capability is conditional based on whether a vidToIndexMap is passed in.
</blockquote></details>

There is a reason that I didn't plan to enforce a non-empty vidToIndexMap at the constructor level at the moment.

If we require vidToIndexMap to be always non-empty when being passed in, then in the EdpSimulatorRunner and InProcessEdpSimulator, vidToIndexMap is needed to be specified. The vidToIndexMap is computed from vidUniverse, which is currently extracted from the synthetic eventQuery dataset. One of the datasets is very large (> 30M vids) and causes the computation to take so long that the integration tests time-out and does not pass github build-and-test check. Even though none of these tests execute HMSS protocol, and a fake non-empty vidToIndexMap can be provided to make the check pass, I'm afraid that this will lead to confusion. Currently Renjie is updating the datasets to make their size smaller, and to have HMSS included in the integration tests. Once it's done, checking vidToIndexMap at the constructor level will be okay. If it's okay, I'll leave a TODO and will check for a non-empty vidToIndexMap at the constructor level when smaller datasets are used.

The passed in vidToIndexMap is to make the requisition fulfillment more efficient. We can have EdpSimulator to support HMSS without the need to specify vidToIndexMap in the constructor. Instead, the map can be computed when generating the frequency vector. Then later, we can update the EdpSimulator to use a cached vidToIndexMap or to read it from a file when it's okay to do so without causing github build-and-test to fail (due to time out).

So, I think about 3 options:
1. Keep the code as it is now, but have a TODO to check the vidToIndexMap at the constructor when it is possible (when all datasets have reasonable size so that integration tests do not time-out).
2. Check for non-empty vidToIndexMap in the constructor, however, a small fake vidToIndexMap will be used in EdpSimulatorRunner and InProcessEdpSimulator is used to avoid github build-and-test time-out issue.
3. Remove vidToIndexMap from the constructor and have it computed on the fly for every HMSS requisition fulfillment. Update the EdpSimulator later to have it passed in the constructor later when smaller datasets are used in the integration tests.

WDYT? Please let me know if you have other suggestions.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 214 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567#-Nwl2fwd-kPR7QPIWOQX:-NwmYoxm8tX5-6e8KquO:beqrsf4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e6ffc2246593fa4143080e6780dea38dcd620ea4/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L214)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Need to also update the EDP capabilities here to indicate whether HMSS is supported.
</blockquote></details>

The function executeRequisitionFulfillingWorkflow() will call the function fulfillRequisitionForHmssMeasurement when the protocol type is HMSS. Did you mean this, or did you mean that we need to document it as well?


<!-- Sent from Reviewable.io -->

2024-05-01 18:32 UTC, SanjayVas requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567)* status: 22 of 24 files reviewed, 9 unresolved discussions (waiting on @ple13, @renjiezh, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 836 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567#-NwkdXHL4InE42DBf6GU:-NwpPacn0VJgcmB4J3jH:b4x6yy) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/394e2e5a35689a98469db7cec90c9a625cefd19a/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L836)):*
> There is a reason that I didn't plan to enforce a non-empty vidToIndexMap at the constructor level at the moment.
> 
> If we require vidToIndexMap to be always non-empty when being passed in, then in the EdpSimulatorRunner and InProcessEdpSimulator, vidToIndexMap is needed to be specified. The vidToIndexMap is computed from vidUniverse, which is currently extracted from the synthetic eventQuery dataset. One of the datasets is very large (> 30M vids) and causes the computation to take so long that the integration tests time-out and does not pass github build-and-test check

Yes, I was aware of this. My suggestion is none of the 3 you've indicated, and instead to make it so that the map is optional in the constructor but that the simulator will treat it as if the EDP does not have the capability to fulfill HMSS Requisitions.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 214 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567#-Nwl2fwd-kPR7QPIWOQX:-NwpQ00FCjKc_qUetGOc:b-o5qgo9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e6ffc2246593fa4143080e6780dea38dcd620ea4/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L214)):*
<details><summary><i>Previously, ple13 (Phi) wrote…</i></summary><blockquote>

The function executeRequisitionFulfillingWorkflow() will call the function fulfillRequisitionForHmssMeasurement when the protocol type is HMSS. Did you mean this, or did you mean that we need to document it as well?
</blockquote></details>

I mean calling `dataProvidersStub.replaceDataProviderCapabilities`, setting the `honest_majority_share_shuffle_supported` field appropriately.


<!-- Sent from Reviewable.io -->

2024-05-01 22:10 UTC, ple13 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567)* status: 22 of 24 files reviewed, 9 unresolved discussions (waiting on @renjiezh, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 836 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567#-NwkdXHL4InE42DBf6GU:-NwqBfhg3dAueqC5qHUt:bt4f7sm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/394e2e5a35689a98469db7cec90c9a625cefd19a/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L836)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> There is a reason that I didn't plan to enforce a non-empty vidToIndexMap at the constructor level at the moment.
> 
> If we require vidToIndexMap to be always non-empty when being passed in, then in the EdpSimulatorRunner and InProcessEdpSimulator, vidToIndexMap is needed to be specified. The vidToIndexMap is computed from vidUniverse, which is currently extracted from the synthetic eventQuery dataset. One of the datasets is very large (> 30M vids) and causes the computation to take so long that the integration tests time-out and does not pass github build-and-test check

Yes, I was aware of this. My suggestion is none of the 3 you've indicated, and instead to make it so that the map is optional in the constructor but that the simulator will treat it as if the EDP does not have the capability to fulfill HMSS Requisitions.
</blockquote></details>

Thanks for explaining this. I wasn't aware that Edp can set the capability for hmss requisition fulfillment. I've updated the PR to allow default value of emptyMap for vidToIndexMap and setting the capabilities depending on whether the map is empty or not.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 214 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567#-Nwl2fwd-kPR7QPIWOQX:-NwqC3yW-rqThTWOhAc9:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e6ffc2246593fa4143080e6780dea38dcd620ea4/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L214)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I mean calling `dataProvidersStub.replaceDataProviderCapabilities`, setting the `honest_majority_share_shuffle_supported` field appropriately.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-01 22:52 UTC, SanjayVas requested changes
> Reviewed 1 of 2 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567)* status: all files reviewed, 6 unresolved discussions (waiting on @ple13, @renjiezh, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 836 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567#-NwkdXHL4InE42DBf6GU:-NwqLUU36Hnlu8jGkBRv:b2qbwax) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/394e2e5a35689a98469db7cec90c9a625cefd19a/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L836)):*
<details><summary><i>Previously, ple13 (Phi) wrote…</i></summary><blockquote>

Thanks for explaining this. I wasn't aware that Edp can set the capability for hmss requisition fulfillment. I've updated the PR to allow default value of emptyMap for vidToIndexMap and setting the capabilities depending on whether the map is empty or not.
</blockquote></details>

This can now go back to being SPEC_INVALID, as it means the Kingdom chose this protocol despite the EDP indicating that it's not supported.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 190 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567#-NwqL7tp0j5fBIq3IX1o:-NwqL7tp0j5fBIq3IX1p:b-v6ehg2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/740f4834e301bb4078badade4fa92670318c0f01/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L190)):*
> ```Kotlin
>   private val privacyBudgetManager: PrivacyBudgetManager,
>   private val trustedCertificates: Map<ByteString, X509Certificate>,
>   private val vidToIndexMap: Map<Long, IndexedValue> = emptyMap(),
> ```

nit: document that the simulator will support the HMSS protocol iff this is non-empty.


<!-- Sent from Reviewable.io -->

2024-05-02 10:12 UTC, ple13 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567)* status: 22 of 24 files reviewed, 5 unresolved discussions (waiting on @renjiezh, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 836 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567#-NwkdXHL4InE42DBf6GU:-NwsmRjfETVxBylMYuLw:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/394e2e5a35689a98469db7cec90c9a625cefd19a/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L836)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This can now go back to being SPEC_INVALID, as it means the Kingdom chose this protocol despite the EDP indicating that it's not supported.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 190 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567#-NwqL7tp0j5fBIq3IX1o:-NwsmNYG7WIX5jkEmvk-:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/740f4834e301bb4078badade4fa92670318c0f01/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L190)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: document that the simulator will support the HMSS protocol iff this is non-empty.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-02 15:39 UTC, SanjayVas approved these changes
> Reviewed 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567)* status: all files reviewed, 4 unresolved discussions (waiting on @renjiezh and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2024-05-03 20:26 UTC, renjiezh approved these changes
> Reviewed 8 of 13 files at r3, 2 of 4 files at r4, 2 of 4 files at r6, 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)



<!-- Sent from Reviewable.io -->

2024-05-03 20:32 UTC, kungfucraig approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567#-:-Nx-95AT7qjAtPn8DEH3:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)



<!-- Sent from Reviewable.io -->

2024-05-07 05:05 UTC, ple13 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567)* status: 20 of 24 files reviewed, 8 unresolved discussions (waiting on @renjiezh, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/api/v2alpha/PrivacyQueryMapper.kt` line 110 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567#-NxDuggXBZMYMNgECKMY:-NxFjsTj-tErORXYyz52:b-qdp4z7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/560e1ba3fd66b32a6df9e029631630ecd5bebb53/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/api/v2alpha/PrivacyQueryMapper.kt#L110)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

doesn't just retuning getLiquidLegionsV2AcdpQuery( work for now?
</blockquote></details>

There are a few reasons why I added a separate function for HMSS.
1. Currently HMSS does not support reach only yet.
2. For reach and frequency, HMSS only supports a single (epsilon, delta) for both reach and frequency. However, the config allows separated Params for them. We need extra checks in HMSS to make sure that the Params are the same.
___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/InProcessEdpSimulator.kt` line 115 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567#-NxE2aY3-0-xnPuk-9nb:-NxFo7hV44CgpKADSxRe:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/560e1ba3fd66b32a6df9e029631630ecd5bebb53/src/main/kotlin/org/wfanet/measurement/integration/common/InProcessEdpSimulator.kt#L115)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

can you add a todo here to support HMMS?
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 849 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567#-NxE3_CLEyBFw1ymH3lt:-NxFkqss3K0LdHUD7szp:b-fn3fdj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/560e1ba3fd66b32a6df9e029631630ecd5bebb53/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L849)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

this should throw on init if hmms is in SUPPORTED_PROTOCOLS and vidToIndexMap is empty... not here
</blockquote></details>

Yeah, ideally we should reject it in init. However there is an issue with the current integration tests. The current dataset used in the integration tests is too large. As a result, the computation of the vidToIndexMap has memory/timeout issues and causes the github's build-and-test to fail.

While waiting for a smaller dataset to be uploaded, the temporary solution is to have the EdpSimulator throws an exception if it is fulfilling requisition for HMSS but the map is empty. We also have the HMSS capabilities set depending on whether the map is empty or not and send it to the Kingdom so that the Kingdom knows what to do.

The name SUPPORTED_PROTOCOLS could be a bit misleading for now, but this will be resolved when the smaller dataset is ready.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 1159 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567#-NxE4C2f60Kj08sS19jA:-NxFlb9h7H7HEmgPD9g7:be7e61r) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/560e1ba3fd66b32a6df9e029631630ecd5bebb53/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L1159)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

why are we supporting the case where the map is empty? Isn't that erroneous?
</blockquote></details>

We can remove it here. When the map is empty, this code won't be reached.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorRunner.kt` line 117 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567#-NxE4bdLETTNPh1fuX2K:-NxFm2Jg1jI3bXZ9gSJy:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/560e1ba3fd66b32a6df9e029631630ecd5bebb53/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorRunner.kt#L117)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

ditto on the todo to add support for hmms
</blockquote></details>

Done.
___
*[`src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt` line 851 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567#-NxE4t_T4dPi5cdBj90A:-NxFmd_O8RIxuJEwOnKe:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/560e1ba3fd66b32a6df9e029631630ecd5bebb53/src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt#L851)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

delete
</blockquote></details>

Done.
___
*[`src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt` line 852 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567#-NxE51ZWC8Jbuf6Ls8vk:-NxFmkPxEuG3aB8aQfH7:b-is2bn2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/560e1ba3fd66b32a6df9e029631630ecd5bebb53/src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt#L852)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

can you add something to verify the reach as well as average frequency or something like that?
</blockquote></details>

Currently we don't have the function to generate shares from seed in Kotlin. So we cannot combine the sketch shares to check the reach/frequency. However, we do have unit tests for functions that generate the frequency vector (https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0a3647e4f404536eb6ffef037dfa31c0f327da9b/src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/ShareShuffleSketchGeneratorTest.kt#L291), and the function that generate the shares from the sketch (https://github.com/world-federation-of-advertisers/any-sketch/blob/main/src/test/cc/frequency_count/generate_secret_shares_test.cc).
___
*[`src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt` line 856 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567#-NxE4iDq9oV9jZn_FlOs:-NxFnsmW06Y2WIIjspUn:b-qr3ejm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/560e1ba3fd66b32a6df9e029631630ecd5bebb53/src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt#L856)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

this should happen on init imo if hmms is listed as a supported protocol
</blockquote></details>

As discussed in EdpSimulator.kt, this will be fixed when a smaller dataset is used.


<!-- Sent from Reviewable.io -->

2024-05-07 17:20 UTC, SanjayVas requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567)* status: 19 of 24 files reviewed, 8 unresolved discussions (waiting on @kungfucraig, @renjiezh, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 849 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567#-NxE3_CLEyBFw1ymH3lt:-NxJ39P89_a2F8fqg7kQ:b21nyy9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/560e1ba3fd66b32a6df9e029631630ecd5bebb53/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L849)):*
Simple fix: have SUPPORTED_PROTOCOLS not be a constant and instead be dependent on whether vidToIndexMap is set.

> The name SUPPORTED_PROTOCOLS could be a bit misleading for now, but this will be resolved when the smaller dataset is ready.

All the details about the issue with integration tests and the dataset size are irrelevant. Each PR must be correct and complete on its own.


<!-- Sent from Reviewable.io -->

2024-05-07 18:10 UTC, stevenwarejones requested changes
> Reviewed 8 of 8 files at r2, 1 of 13 files at r3, 6 of 6 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567)* status: all files reviewed, 4 unresolved discussions (waiting on @kungfucraig, @ple13, @renjiezh, and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 849 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567#-NxE3_CLEyBFw1ymH3lt:-NxJEI0x9otR2nRNhIEh:b-zdf7et) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/560e1ba3fd66b32a6df9e029631630ecd5bebb53/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L849)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Simple fix: have SUPPORTED_PROTOCOLS not be a constant and instead be dependent on whether vidToIndexMap is set.

> The name SUPPORTED_PROTOCOLS could be a bit misleading for now, but this will be resolved when the smaller dataset is ready.

All the details about the issue with integration tests and the dataset size are irrelevant. Each PR must be correct and complete on its own.
</blockquote></details>

can't we just pass in empty for the integration tests for now and not have hmss integration tests and do what Sanjay said and have the supported protocols be based on the passed in args
___
*[`src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt` line 852 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567#-NxE51ZWC8Jbuf6Ls8vk:-NxJEkMV9ee8GDP_iNVP:bjlu5ss) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/560e1ba3fd66b32a6df9e029631630ecd5bebb53/src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt#L852)):*
<details><summary><i>Previously, ple13 (Phi) wrote…</i></summary><blockquote>

Currently we don't have the function to generate shares from seed in Kotlin. So we cannot combine the sketch shares to check the reach/frequency. However, we do have unit tests for functions that generate the frequency vector (https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0a3647e4f404536eb6ffef037dfa31c0f327da9b/src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/ShareShuffleSketchGeneratorTest.kt#L291), and the function that generate the shares from the sketch (https://github.com/world-federation-of-advertisers/any-sketch/blob/main/src/test/cc/frequency_count/generate_secret_shares_test.cc).
</blockquote></details>

can you add a TODO then?


<!-- Sent from Reviewable.io -->

2024-05-07 19:18 UTC, ple13 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567)* status: 22 of 24 files reviewed, 4 unresolved discussions (waiting on @kungfucraig, @renjiezh, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 849 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567#-NxE3_CLEyBFw1ymH3lt:-NxJKse4CLbPnMZAL43M:bjc5mih) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/560e1ba3fd66b32a6df9e029631630ecd5bebb53/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L849)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

can't we just pass in empty for the integration tests for now and not have hmss integration tests and do what Sanjay said and have the supported protocols be based on the passed in args
</blockquote></details>

Thanks for the suggestion. I've updated it.
___
*[`src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt` line 852 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567#-NxE51ZWC8Jbuf6Ls8vk:-NxJKxpW7DMA4QM6oR-O:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/560e1ba3fd66b32a6df9e029631630ecd5bebb53/src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt#L852)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

can you add a TODO then?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-07 19:41 UTC, SanjayVas requested changes
> Reviewed 3 of 6 files at r10, 1 of 2 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567)* status: 23 of 24 files reviewed, 7 unresolved discussions (waiting on @kungfucraig, @ple13, @renjiezh, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/InProcessEdpSimulator.kt` line 115 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567#-NxJUhTA0qb4c15oVEYv:-NxJUhTA0qb4c15oVEYw:b5z6un8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0bf1bc59f043d10f123dbc1f5fa84adfe74c9c1c/src/main/kotlin/org/wfanet/measurement/integration/common/InProcessEdpSimulator.kt#L115)):*
> ```Kotlin
>         ),
>       trustedCertificates = trustedCertificates,
>       /**
> ```

nit: incorrect use of KDoc syntax. KDoc blocks are for type, property, and function declarations.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 504 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567#-NxJVGXnEcal7QGG8lrY:-NxJVGXnEcal7QGG8lrZ:bjcb97u) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0bf1bc59f043d10f123dbc1f5fa84adfe74c9c1c/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L504)):*
> ```Kotlin
>     protocol: ProtocolConfig.Protocol.ProtocolCase,
>   ) {
>     val SUPPORTED_PROTOCOLS = buildSet {
> ```

This is now a local variable and not a constant. Therefore it should use `lowerCamelCase`.



_Suggestion:_
```Kotlin
supportedProtocols
```
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 511 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567#-NxJVeMCB70BWPKADmMW:-NxJVeMCB70BWPKADmMX:bljptkh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0bf1bc59f043d10f123dbc1f5fa84adfe74c9c1c/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L511)):*
> ```Kotlin
>       }
>     }
>     require(protocol in SUPPORTED_PROTOCOLS) { "Unsupported protocol $protocol" }
> ```

This is the wrong place for this check, as it's not actually checking anything related to the DuchyEntry. Instead it's checking the ProtocolConfig. This should be checked first and should result in the Requisition being refused.


<!-- Sent from Reviewable.io -->

2024-05-07 22:16 UTC, stevenwarejones approved these changes
Sanjay's comments cover all my remaining issues with this PR. once he's approved it, I'm good.

> Reviewed 1 of 2 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567#-:-NxK78H01GjoSqWVcKdY:bbhl9jv)* status: all files reviewed, 4 unresolved discussions (waiting on @kungfucraig, @ple13, and @renjiezh)



<!-- Sent from Reviewable.io -->

2024-05-08 12:56 UTC, stevenwarejones approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567)* status: all files reviewed, 3 unresolved discussions (waiting on @kungfucraig, @ple13, and @renjiezh)



<!-- Sent from Reviewable.io -->

2024-05-08 13:35 UTC, ple13 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567)* status: 20 of 24 files reviewed, 3 unresolved discussions (waiting on @kungfucraig, @renjiezh, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/InProcessEdpSimulator.kt` line 115 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567#-NxJUhTA0qb4c15oVEYv:-NxNOwBS7S0698xwjbfr:b-qo62uj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0bf1bc59f043d10f123dbc1f5fa84adfe74c9c1c/src/main/kotlin/org/wfanet/measurement/integration/common/InProcessEdpSimulator.kt#L115)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: incorrect use of KDoc syntax. KDoc blocks are for type, property, and function declarations.
</blockquote></details>

I've moved the Todo outside of the function call.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 504 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567#-NxJVGXnEcal7QGG8lrY:-NxNP1vS7mKKX35dsz56:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0bf1bc59f043d10f123dbc1f5fa84adfe74c9c1c/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L504)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This is now a local variable and not a constant. Therefore it should use `lowerCamelCase`.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 511 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567#-NxJVeMCB70BWPKADmMW:-NxNP3AF37AhK8CS7PHn:bknjjph) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0bf1bc59f043d10f123dbc1f5fa84adfe74c9c1c/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L511)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This is the wrong place for this check, as it's not actually checking anything related to the DuchyEntry. Instead it's checking the ProtocolConfig. This should be checked first and should result in the Requisition being refused.
</blockquote></details>

I've added a function verifyProtocolConfig to check if a protocol is supported.


<!-- Sent from Reviewable.io -->

2024-05-08 21:49 UTC, renjiezh approved these changes
> Reviewed 2 of 6 files at r10, 4 of 4 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567)* status: all files reviewed, 1 unresolved discussion (waiting on @kungfucraig and @ple13)



<!-- Sent from Reviewable.io -->

2024-05-08 22:43 UTC, ple13 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567)* status: 22 of 24 files reviewed, all discussions resolved (waiting on @kungfucraig, @renjiezh, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 826 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567#-NxOKXD-6MJLlGHxJlJg:-NxPIfCT7giuWsdQV0lk:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/646be29bf619b275ffa8d811bd1fbffd69a026ff/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L826)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: can extract a `protocolConfig` local variable since it's passed to two functions.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-08 23:17 UTC, ple13 reviewed
> Reviewed 2 of 19 files at r1, 8 of 8 files at r2, 6 of 13 files at r3, 2 of 4 files at r4, 3 of 4 files at r13, 3 of 3 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1567)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @kungfucraig)



<!-- Sent from Reviewable.io -->

2024-05-08 23:17 UTC, merged