Implement FrequencyVectorBuilder
world-federation-of-advertisers/cross-media-measurement pull request #1604
Opened 2024-05-03 16:24 UTC by kungfucraig

2024-05-03 16:24 UTC, wfa-reviewable commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1604)
<!-- Reviewable:end -->

2024-05-03 20:07 UTC, SanjayVas requested changes
> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1604)* status: 3 of 4 files reviewed, 6 unresolved discussions (waiting on @kungfucraig and @renjiezh)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/FrequencyVectorBuilder.kt` line 19 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1604#-Nx--Fof2eGHwIG1XqzR:-Nx--Fof2eGHwIG1XqzS:bk67wky) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/563921d439836c76a434277e0b0d1e9a4df7b0a8/src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/FrequencyVectorBuilder.kt#L19)):*
> ```Kotlin
> import org.wfanet.frequencycount.FrequencyVector
> import org.wfanet.frequencycount.frequencyVector
> import org.wfanet.measurement.api.v2alpha.MeasurementSpec
> ```

If this library is going to depend on a versioned API, it should also be versioned (e.g. adding a v2alpha subpackage).

Alternatives:
1. Do not depend on a specific API and instead use separate data structures, in which case the calling code can provide the appropriate conversion.
2. Commit to a policy of only ever supporting one API version in this library, meaning the library will cease to work with any old API version after being updated to a new one.
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/FrequencyVectorBuilder.kt` line 39 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1604#-Nwzy1Wa9CGSSRC-E_73:-Nwzy1Wb-ichO-p8qBsY:b5d2j9w) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/563921d439836c76a434277e0b0d1e9a4df7b0a8/src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/FrequencyVectorBuilder.kt#L39)):*
> ```Kotlin
>  * filter the inputs to [increment] and [incrementAll].
>  *
>  * @param populationSpec [PopulationSpec] for the population being measured
> ```

nit: you don't need to include the type info a second time, as it's already noted in the function signature



_Suggestion:_
```Kotlin
@param populationSpec specification of the population being measured
```
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/FrequencyVectorBuilder.kt` line 73 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1604#-Nx-0IpP2Ge6lNXJdNZo:-Nx-0IpP2Ge6lNXJdNZp:br9scyj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/563921d439836c76a434277e0b0d1e9a4df7b0a8/src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/FrequencyVectorBuilder.kt#L73)):*
> ```Kotlin
>     get() = frequencyData.size
> 
>   init {
> ```

nit: Prefer using multiple granular `init` blocks. e.g. put the `init` block that sets the `maxFrequency` property right after the declaration of that property.
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/FrequencyVectorBuilder.kt` line 144 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1604#-NwzyalH7oNFrDfsoq8o:-NwzyalI7vM7qTXDV5xU:b-wietsd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/563921d439836c76a434277e0b0d1e9a4df7b0a8/src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/FrequencyVectorBuilder.kt#L144)):*
> ```Kotlin
>   /** Build a FrequencyVector. */
>   fun build(): FrequencyVector =
>     FrequencyVector.newBuilder()!!.addAllData(frequencyData.asList()).build()
> ```

Use Kotlin DSL. Kotlin code should never need to interact with a Java protobuf builder.



_Suggestion:_
```Kotlin
frequencyVector {
  data += frequencyData.asList()
}
```
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/FrequencyVectorBuilder.kt` line 211 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1604#-Nx-27bO2v5YNWaGNT6E:-Nx-27bO2v5YNWaGNT6F:b-2o62xm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/563921d439836c76a434277e0b0d1e9a4df7b0a8/src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/FrequencyVectorBuilder.kt#L211)):*
> ```Kotlin
>     }
>   }
> }
> ```

nit: this also looks like a good choice for being a receiver property rather than a function. Also, shouldn't this a be Long rather than an Int, e.g. in the event of covering a global or multi-country population with a size >2B? Finally, you can use `sumOf` rather than a temporary var.



_Suggestion:_
```Kotlin
}

val PopulationSpec.size: Long {
  get() = populationSpec.subpopulationsList.sumOf { subPop -> subPop.vidRangesList.sumOf { (it.startVid..it.endVidInclusive).count() } }
}
```
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/VidIndexMap.kt` line 33 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1604#-Nx-3MlyA2HFeG5TFEZc:-Nx-3MlyA2HFeG5TFEZd:b-sceecw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/563921d439836c76a434277e0b0d1e9a4df7b0a8/src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/VidIndexMap.kt#L33)):*
> ```Kotlin
> 
>   /** The number of VIDs managed by this VidIndexMap */
>   val size: Int
> ```

Same question here. Don't we need to support VID counts up to planet population?



_Suggestion:_
```Kotlin
  val size: Long
```


<!-- Sent from Reviewable.io -->

2024-05-03 20:49 UTC, kungfucraig reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1604)* status: 1 of 4 files reviewed, 4 unresolved discussions (waiting on @renjiezh and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/FrequencyVectorBuilder.kt` line 19 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1604#-Nx--Fof2eGHwIG1XqzR:-Nx-42j-6C2ms1qG5_pF:bbpryfx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/563921d439836c76a434277e0b0d1e9a4df7b0a8/src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/FrequencyVectorBuilder.kt#L19)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

If this library is going to depend on a versioned API, it should also be versioned (e.g. adding a v2alpha subpackage).

Alternatives:
1. Do not depend on a specific API and instead use separate data structures, in which case the calling code can provide the appropriate conversion.
2. Commit to a policy of only ever supporting one API version in this library, meaning the library will cease to work with any old API version after being updated to a new one.
</blockquote></details>

This will become inconsistent with the VidIndexMap. I'll add a TODO and do it for both of them later.
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/FrequencyVectorBuilder.kt` line 73 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1604#-Nx-0IpP2Ge6lNXJdNZo:-Nx-4gtI5j93q7_vGX5r:b-88efu7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/563921d439836c76a434277e0b0d1e9a4df7b0a8/src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/FrequencyVectorBuilder.kt#L73)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: Prefer using multiple granular `init` blocks. e.g. put the `init` block that sets the `maxFrequency` property right after the declaration of that property.
</blockquote></details>

Cool! Didn't know that was a thing.
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/FrequencyVectorBuilder.kt` line 144 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1604#-NwzyalH7oNFrDfsoq8o:-Nx-5wD_70gvn-6Pbmuh:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/563921d439836c76a434277e0b0d1e9a4df7b0a8/src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/FrequencyVectorBuilder.kt#L144)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Use Kotlin DSL. Kotlin code should never need to interact with a Java protobuf builder.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/VidIndexMap.kt` line 33 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1604#-Nx-3MlyA2HFeG5TFEZc:-Nx-7MFtBvK0iC5fYPsI:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/563921d439836c76a434277e0b0d1e9a4df7b0a8/src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/VidIndexMap.kt#L33)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Same question here. Don't we need to support VID counts up to planet population?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-03 21:19 UTC, SanjayVas requested changes
> Reviewed 1 of 4 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1604)* status: all files reviewed, 4 unresolved discussions (waiting on @kungfucraig and @renjiezh)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/FrequencyVectorBuilder.kt` line 24 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1604#-Nx-GM2g-abm62B5g6fG:-Nx-GM2g-abm62B5g6fH:b4fi9wq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ad8e01d3824248ac91bf85bc67acc7b9e9893c8b/src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/FrequencyVectorBuilder.kt#L24)):*
> ```Kotlin
> import org.wfanet.measurement.api.v2alpha.PopulationSpecValidator.validateVidRangesList
> 
> // TODO(@kungfucraig): Move this into a utility class.
> ```

nit: move the TODO into the KDoc. Additionally, it wouldn't be moved into a class since it's an extension property. Perhaps you mean to move it into a separate file and/or package?
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/FrequencyVectorBuilder.kt` line 215 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1604#-Nx-HMrZ1mwsf2-i2-gD:-Nx-HMrZ1mwsf2-i2-gE:bzi6inq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ad8e01d3824248ac91bf85bc67acc7b9e9893c8b/src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/FrequencyVectorBuilder.kt#L215)):*
> ```Kotlin
>     other.frequencyData.forEachIndexed { i: Int, freq: Int ->
>       frequencyData[i] = minOf(freq + frequencyData[i], maxFrequency)
>     }
> ```

For extra credit, you can add a function that provides Kotlin DSL syntax for this builder so it can be used more idiomatically.

Something like

```kotlin
companion object {
  fun build(populationSpec: PopulationSpec, measurementSpec: MeasurementSpec, bind: FrequencyVectorBuilder.() -> Unit): FrequencyVector = FrequencyVectorBuilder(populationSpec, measurementSpec).apply(bind).build()
}
```

This can then be called like

```kotlin
FrequencyVectorBuilder.build(populationSpec, measurementSpec) {
  increment(x)
  increment(y)
}
```
___
*[`src/test/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/FrequencyVectorBuilderTest.kt` line 34 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1604#-Nx-JiSz1NOU5y1IWSAQ:-Nx-JiSz1NOU5y1IWSAR:bzehxjc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ad8e01d3824248ac91bf85bc67acc7b9e9893c8b/src/test/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/FrequencyVectorBuilderTest.kt#L34)):*
> ```Kotlin
> @RunWith(JUnit4::class)
> class FrequencyVectorBuilderTest {
>   private val startingVid = 100_000L
> ```

Define all of these as constants in the companion object of the test using CONST_CASE. Note that only some of these can be compile-time constants using the `const` keyword.
___
*[`src/test/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/FrequencyVectorBuilderTest.kt` line 189 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1604#-Nx-J2hs-3oEYMLLHaeU:-Nx-J2hs-3oEYMLLHaeV:bnjuui7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ad8e01d3824248ac91bf85bc67acc7b9e9893c8b/src/test/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/FrequencyVectorBuilderTest.kt#L189)):*
> ```Kotlin
> 
>   @Test
>   fun `create frequency vector for reach over full interval`() {
> ```

nit: standard test method format is "SUT <verb>s X [for/when Y]", e.g. "build returns FrequencyVector for reach over full interval" or "constructor throws IllegalArgumentException when sampling interval is invalid"


<!-- Sent from Reviewable.io -->

2024-05-03 23:40 UTC, kungfucraig reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1604)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @renjiezh and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/FrequencyVectorBuilder.kt` line 215 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1604#-Nx-HMrZ1mwsf2-i2-gD:-Nx-N8tB5VXhsT-4bteM:b-1apgvj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ad8e01d3824248ac91bf85bc67acc7b9e9893c8b/src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/FrequencyVectorBuilder.kt#L215)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

For extra credit, you can add a function that provides Kotlin DSL syntax for this builder so it can be used more idiomatically.

Something like

```kotlin
companion object {
  fun build(populationSpec: PopulationSpec, measurementSpec: MeasurementSpec, bind: FrequencyVectorBuilder.() -> Unit): FrequencyVector = FrequencyVectorBuilder(populationSpec, measurementSpec).apply(bind).build()
}
```

This can then be called like

```kotlin
FrequencyVectorBuilder.build(populationSpec, measurementSpec) {
  increment(x)
  increment(y)
}
```
</blockquote></details>

Thanks. This is cool.
___
*[`src/test/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/FrequencyVectorBuilderTest.kt` line 34 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1604#-Nx-JiSz1NOU5y1IWSAQ:-Nx-i5In8J0RVb_RJ6-k:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ad8e01d3824248ac91bf85bc67acc7b9e9893c8b/src/test/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/FrequencyVectorBuilderTest.kt#L34)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Define all of these as constants in the companion object of the test using CONST_CASE. Note that only some of these can be compile-time constants using the `const` keyword.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-03 23:45 UTC, SanjayVas reviewed
> Reviewed 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1604)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @kungfucraig, @renjiezh, and @stevenwarejones)

___
*[`src/test/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/FrequencyVectorBuilderTest.kt` line 33 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1604#-Nx-q8ZGCsMI9Hf7iH6_:-Nx-q8ZGCsMI9Hf7iH6a:bn5ezuf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/29327f09b228ee190d9d0bb3288fea19d87cb113/src/test/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/FrequencyVectorBuilderTest.kt#L33)):*
> ```Kotlin
> @RunWith(JUnit4::class)
> class FrequencyVectorBuilderTest {
>   companion object {
> ```

nit: typically the companion object goes at the end of a class definition (yes, I know this means the constants end up at the bottom rather than the top...)


<!-- Sent from Reviewable.io -->

2024-05-03 23:45 UTC, SanjayVas approved these changes
> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1604)* status: all files reviewed, 1 unresolved discussion (waiting on @kungfucraig, @renjiezh, and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2024-05-06 20:10 UTC, stevenwarejones requested changes
> Reviewed 1 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1604)* status: all files reviewed, 3 unresolved discussions (waiting on @kungfucraig and @renjiezh)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/FrequencyVectorBuilder.kt` line 72 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1604#-NxE5Raw47g7Z-XkWRIJ:-NxE5Raw47g7Z-XkWRIK:bb6pqkx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/29327f09b228ee190d9d0bb3288fea19d87cb113/src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/FrequencyVectorBuilder.kt#L72)):*
>=2?
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/FrequencyVectorBuilder.kt` line 108 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1604#-NxE5krM5eqc9CO7p1bD:-NxE5krM5eqc9CO7p1bE:bqbhbvq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/29327f09b228ee190d9d0bb3288fea19d87cb113/src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/FrequencyVectorBuilder.kt#L108)):*
> ```Kotlin
>     validateVidRangesList(populationSpec).getOrThrow()
>     val populationSizeLong = populationSpec.size
>     require(populationSizeLong > Int.MIN_VALUE || populationSizeLong < Int.MAX_VALUE) {
> ```

why must the population size be in that range? and why convert it to Int?


<!-- Sent from Reviewable.io -->

2024-05-06 21:53 UTC, kungfucraig reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1604)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @renjiezh, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/FrequencyVectorBuilder.kt` line 72 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1604#-NxE5Raw47g7Z-XkWRIJ:-NxEslbN9dskHq7kd-uA:bp88hlm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/29327f09b228ee190d9d0bb3288fea19d87cb113/src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/FrequencyVectorBuilder.kt#L72)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

>=2?
</blockquote></details>

I don't know what you mean by this comment. Are you asking me to write ">2" instead?
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/FrequencyVectorBuilder.kt` line 108 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1604#-NxE5krM5eqc9CO7p1bD:-NxErUpTEffjN12qz_yl:bhn6uzq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/29327f09b228ee190d9d0bb3288fea19d87cb113/src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/FrequencyVectorBuilder.kt#L108)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

why must the population size be in that range? and why convert it to Int?
</blockquote></details>

The Population Size is a Long.

In practice we have this Frequency Vector which is proportional to the population size. Arrays are indexed with Ints, so it's convenient to have an Int.


If we ever have an extremely large population this entire Frequency Vector method will completely break down. So that's an issue in and of itself, but one that we are acknowledging and ignoring. For the foreseeable future what we are doing is fine.


<!-- Sent from Reviewable.io -->

2024-05-06 21:58 UTC, kungfucraig reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1604)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @renjiezh, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/FrequencyVectorBuilder.kt` line 72 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1604#-NxE5Raw47g7Z-XkWRIJ:-NxEuU3pCg46E3ng-SBQ:b-evo29r) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/29327f09b228ee190d9d0bb3288fea19d87cb113/src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/FrequencyVectorBuilder.kt#L72)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

I don't know what you mean by this comment. Are you asking me to write ">2" instead?
</blockquote></details>

Sorry, >0?


<!-- Sent from Reviewable.io -->

2024-05-07 18:14 UTC, stevenwarejones requested changes
> Reviewed 1 of 2 files at r2, 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1604)* status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @kungfucraig, @renjiezh, and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/FrequencyVectorBuilder.kt` line 72 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1604#-NxE5Raw47g7Z-XkWRIJ:-NxJF-_Q0dfImyOvzEXD:b8vyg9i) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/29327f09b228ee190d9d0bb3288fea19d87cb113/src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/FrequencyVectorBuilder.kt#L72)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Sorry, >0?
</blockquote></details>

sorry, typo - I meant >=2 - I think we want to not allow cases where its r&f but its maxFreq is 1 -- meaning it should be a reach-only measurement
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/FrequencyVectorBuilder.kt` line 108 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1604#-NxE5krM5eqc9CO7p1bD:-NxJFLRE2mx8gdy_iZIR:b-abros3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/29327f09b228ee190d9d0bb3288fea19d87cb113/src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/FrequencyVectorBuilder.kt#L108)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

The Population Size is a Long.

In practice we have this Frequency Vector which is proportional to the population size. Arrays are indexed with Ints, so it's convenient to have an Int.


If we ever have an extremely large population this entire Frequency Vector method will completely break down. So that's an issue in and of itself, but one that we are acknowledging and ignoring. For the foreseeable future what we are doing is fine.
</blockquote></details>

yes - what you wrote is exactly what I was thinking. can you throw an error for large population sizes?
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/VidIndexMap.kt` line 52 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1604#-NxJFuaZ4BzUb9TZwS6B:-NxJFuaZ4BzUb9TZwS6C:bpzaz3v) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8da7657ecbedcfd76e14d1ba506a75b820515313/src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/VidIndexMap.kt#L52)):*
> ```Kotlin
>  * @throws [PopulationSpecValidationException] if the [populationSpec] is invalid
>  */
> class InMemoryVidIndexMap(
> ```

can you pull this out to its own file?


<!-- Sent from Reviewable.io -->

2024-05-07 19:41 UTC, kungfucraig reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1604)* status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @renjiezh, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/FrequencyVectorBuilder.kt` line 72 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1604#-NxE5Raw47g7Z-XkWRIJ:-NxJXmGI9yhHgPWd02ZU:bjivrp7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/29327f09b228ee190d9d0bb3288fea19d87cb113/src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/FrequencyVectorBuilder.kt#L72)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

sorry, typo - I meant >=2 - I think we want to not allow cases where its r&f but its maxFreq is 1 -- meaning it should be a reach-only measurement
</blockquote></details>

Setting the max frequency to 1 is not incorrect. The APIs do not explicitly disallow this either.
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/FrequencyVectorBuilder.kt` line 108 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1604#-NxE5krM5eqc9CO7p1bD:-NxJZVVZ8-2KGEvDwSDV:b1guw8f) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/29327f09b228ee190d9d0bb3288fea19d87cb113/src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/FrequencyVectorBuilder.kt#L108)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

yes - what you wrote is exactly what I was thinking. can you throw an error for large population sizes?
</blockquote></details>

That's exactly what this is doing. I don't want to introduce some other arbitrary constant though.
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/VidIndexMap.kt` line 52 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1604#-NxJFuaZ4BzUb9TZwS6B:-NxJZgjJ7XUsLtGwYHMG:b-u1vy19) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8da7657ecbedcfd76e14d1ba506a75b820515313/src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/VidIndexMap.kt#L52)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

can you pull this out to its own file?
</blockquote></details>

Not in this PR.


<!-- Sent from Reviewable.io -->

2024-05-07 19:54 UTC, stevenwarejones requested changes
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1604)* status: all files reviewed, 3 unresolved discussions (waiting on @kungfucraig and @renjiezh)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/FrequencyVectorBuilder.kt` line 108 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1604#-NxE5krM5eqc9CO7p1bD:-NxJaxjP95Qkdh8T5-MU:b-kmj42l) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/29327f09b228ee190d9d0bb3288fea19d87cb113/src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/FrequencyVectorBuilder.kt#L108)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

That's exactly what this is doing. I don't want to introduce some other arbitrary constant though.
</blockquote></details>

the error message you have is not intuitive. Why would someone put in a negative population size? Maybe just put
```
require(populationSizeLong >= 0 || populationSizeLong < UInt.MAX_VALUE) {
```

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/VidIndexMap.kt` line 52 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1604#-NxJFuaZ4BzUb9TZwS6B:-NxJbeQvA4ddpMzHZ7S8:bjlu5ss) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8da7657ecbedcfd76e14d1ba506a75b820515313/src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/VidIndexMap.kt#L52)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Not in this PR.
</blockquote></details>

can you add a TODO then?


<!-- Sent from Reviewable.io -->

2024-05-07 19:58 UTC, stevenwarejones requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1604)* status: all files reviewed, 4 unresolved discussions (waiting on @kungfucraig and @renjiezh)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/FrequencyVectorBuilder.kt` line 111 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1604#-NxJcGEv-xm3BEqoF8Vz:-NxJcGEv-xm3BEqoF8W-:bgmd1ck) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8da7657ecbedcfd76e14d1ba506a75b820515313/src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/FrequencyVectorBuilder.kt#L111)):*
> ```Kotlin
>       "population size must be > Int.MIN_VALUE and < Int.MAX_VALUE"
>     }
>     val populationSize = populationSizeLong.toInt()
> ```

I'm not actually sure how `toInt` works in practice when the number Int.MAX_VALUE < X < UInt.MAX_VALUE

does it need to first be converted to UInt to preserve that range?
```
val populationSize = populationSizeLong.toUInt().toInt()
```



<!-- Sent from Reviewable.io -->

2024-05-07 20:08 UTC, kungfucraig reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1604)* status: 2 of 4 files reviewed, 4 unresolved discussions (waiting on @renjiezh, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/FrequencyVectorBuilder.kt` line 108 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1604#-NxE5krM5eqc9CO7p1bD:-NxJek5e4MkLvcDqiBel:blum1sl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/29327f09b228ee190d9d0bb3288fea19d87cb113/src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/FrequencyVectorBuilder.kt#L108)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

the error message you have is not intuitive. Why would someone put in a negative population size? Maybe just put
```
require(populationSizeLong >= 0 || populationSizeLong < UInt.MAX_VALUE) {
```

</blockquote></details>

Not using UInt because we end up using all of this to drive array indexes and UInt gets in the way.
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/FrequencyVectorBuilder.kt` line 111 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1604#-NxJcGEv-xm3BEqoF8Vz:-NxJevHTDWH3FdwmEJdx:b-ji4hgj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8da7657ecbedcfd76e14d1ba506a75b820515313/src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/FrequencyVectorBuilder.kt#L111)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

I'm not actually sure how `toInt` works in practice when the number Int.MAX_VALUE < X < UInt.MAX_VALUE

does it need to first be converted to UInt to preserve that range?
```
val populationSize = populationSizeLong.toUInt().toInt()
```

</blockquote></details>

See above. I'm not using UInt.
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/VidIndexMap.kt` line 52 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1604#-NxJFuaZ4BzUb9TZwS6B:-NxJejCNC_PIB2Gj1pMF:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8da7657ecbedcfd76e14d1ba506a75b820515313/src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/VidIndexMap.kt#L52)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

can you add a TODO then?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-05-07 20:40 UTC, stevenwarejones approved these changes
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1604)* status: all files reviewed, 1 unresolved discussion (waiting on @kungfucraig and @renjiezh)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/FrequencyVectorBuilder.kt` line 108 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1604#-NxE5krM5eqc9CO7p1bD:-NxJm0XY7eBnwXSl5KBy:b-8y0vyu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/29327f09b228ee190d9d0bb3288fea19d87cb113/src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/FrequencyVectorBuilder.kt#L108)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Not using UInt because we end up using all of this to drive array indexes and UInt gets in the way.
</blockquote></details>

technically, since you support negative indices, I believe you could change your error message to allow populationSize up to UInt.MAX_VALUE
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/FrequencyVectorBuilder.kt` line 111 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1604#-NxJcGEv-xm3BEqoF8Vz:-NxJlvIaAzEmwj2weYkv:b-fefsqy) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8da7657ecbedcfd76e14d1ba506a75b820515313/src/main/kotlin/org/wfanet/measurement/eventdataprovider/shareshuffle/FrequencyVectorBuilder.kt#L111)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

See above. I'm not using UInt.
</blockquote></details>

tested this out locally and it doesn't make a difference


<!-- Sent from Reviewable.io -->

2024-05-07 21:05 UTC, kungfucraig reviewed
> Reviewed 1 of 4 files at r1, 1 of 1 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1604)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @renjiezh and @SanjayVas)



<!-- Sent from Reviewable.io -->

2024-05-07 21:21 UTC, merged