Implement CreateCertificate and GetCertificate for Duchies
world-federation-of-advertisers/cross-media-measurement pull request #167
Opened 2021-07-25 23:13 UTC by uakyol

2021-07-26 17:51 UTC, wangyaopw requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/167)* status: 0 of 9 files reviewed, 2 unresolved discussions (waiting on @SanjayVas and @uakyol)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/DuchyIds.kt, line 51 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/167#-MfYvw2h2FnmTHSFjSt1:-MfYvw2h2FnmTHSFjSt2:b-t9jz42) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e1f529521742887bfb953da5e1e5b8b8f3d95fa3/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/DuchyIds.kt#L51)):*
> ```Kotlin
> 
>   fun setForTest(duchyIds: List<String>) {
>     entries = duchyIds.mapIndexed { idx, value -> DuchyIds.Entry(idx.toLong(), value) }
> ```

also add `require(!DuchyIds::entries.isInitialized)`? 
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateCertificate.kt, line 87 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/167#-MfYuVRA26mqbdastV3j:-MfYuVRA26mqbdastV3k:bipml1w) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e1f529521742887bfb953da5e1e5b8b8f3d95fa3/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateCertificate.kt#L87)):*
> ```
> Long
> ```
Maybe refactor the duchyID to use type `InternalId` for internalDuchyId, so it is more consistent here.


<!-- Sent from Reviewable.io -->

2021-07-26 19:41 UTC, SanjayVas requested changes
> Reviewed 3 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/167)* status: 3 of 9 files reviewed, 6 unresolved discussions (waiting on @uakyol)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/167#-MfZKNhJ8Ad_UwqF6g8N:-MfZKNhJ8Ad_UwqF6g8O:b-end71g) (no related file):*
It seems like I'm reviewing code here I've already reviewed in another PR and having to leave the same comments. Please do not do this. Layer your PRs appropriately to avoid it.

---
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerCertificatesService.kt, line 74 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/167#-MfZJHrn41klch6MqJ_W:-MfZJHrn41klch6MqJ_X:b3c7xmy) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e1f529521742887bfb953da5e1e5b8b8f3d95fa3/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerCertificatesService.kt#L74)):*
> ```Kotlin
>         KingdomInternalException.Code.DUCHY_NOT_FOUND ->
>           failGrpc(Status.INVALID_ARGUMENT) { "Duchy not found" }
>         else -> failGrpc(Status.UNKNOWN) { "" }
> ```

I thought I had already left a comment on this, but use exhaustive `when` by leaving out the `else` case.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/common/KingdomInternalException.kt, line 20 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/167#-MfZJUCSDIAe_rpBO2Re:-MfZJUCTB9ZAJ1Ye1-B0:bwwqnv1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e1f529521742887bfb953da5e1e5b8b8f3d95fa3/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/common/KingdomInternalException.kt#L20)):*
> ```
>     UNKNOWN,
> ```
I also thought I had left a comment on this, but drop the `UNKNOWN` value from here. Unknown errors can just bubble up via the cause since all exceptions are unchecked in Kotlin.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/CertificateReader.kt, line 27 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/167#-MfZK8tH0ZA3DAlyeiO3:-MfZK8tH0ZA3DAlyeiO4:bmspyqm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e1f529521742887bfb953da5e1e5b8b8f3d95fa3/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/CertificateReader.kt#L27)):*
> ```Kotlin
>   data class Result(val certificate: Certificate, val certificateId: Long)
> 
>   enum class OwnerType(val tableName: String) {
> ```

I thought this was gone, using ParentCase instead?


<!-- Sent from Reviewable.io -->

2021-07-26 23:27 UTC, uakyol reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/167)* status: 3 of 9 files reviewed, 6 unresolved discussions (waiting on @SanjayVas and @uakyol)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/167#-MfZKNhJ8Ad_UwqF6g8N:-Mf_73498a0aGNrRNqfi:bstlfkf) (no related file):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

It seems like I'm reviewing code here I've already reviewed in another PR and having to leave the same comments. Please do not do this. Layer your PRs appropriately to avoid it.
</blockquote></details>

Those PR comments are not resolved yet, and these changes are not implementing the changes you commented on. I thought it would save us time to review them in parallel, resolve the other PR changes since there is an active discussion going on there. What do you think is the best way to address such a situation? Should I stop making linked changes and don't start a PR until the one before is finished?

---
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerCertificatesService.kt, line 74 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/167#-MfZJHrn41klch6MqJ_W:-Mf_6Hzc2n7eW5eNLZhM:b-ex94rl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e1f529521742887bfb953da5e1e5b8b8f3d95fa3/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerCertificatesService.kt#L74)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I thought I had already left a comment on this, but use exhaustive `when` by leaving out the `else` case.
</blockquote></details>

This was not changed from the previous PR, I am going to address that and bubble that up. 
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/common/KingdomInternalException.kt, line 20 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/167#-MfZJUCSDIAe_rpBO2Re:-Mf_7Pu61Vs6jyvOeoib:b7zvl07) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e1f529521742887bfb953da5e1e5b8b8f3d95fa3/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/common/KingdomInternalException.kt#L20)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
>     UNKNOWN,
> ```
I also thought I had left a comment on this, but drop the `UNKNOWN` value from here. Unknown errors can just bubble up via the cause since all exceptions are unchecked in Kotlin.
</blockquote></details>

Again, this is not changed from the previous PR, I looked here to make sure I am not touching that line: https://github.com/world-federation-of-advertisers/cross-media-measurement/pull/167/files#diff-74e12f00f6eb36f077888a2ea404e3a0e2c252aec5e1844813f1edf7366092f3R32 . I think I did it wrong, should have done changes sequentially.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/CertificateReader.kt, line 27 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/167#-MfZK8tH0ZA3DAlyeiO3:-Mf_6Rg4-xtbO0fwWbHh:bavslb0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e1f529521742887bfb953da5e1e5b8b8f3d95fa3/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/CertificateReader.kt#L27)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I thought this was gone, using ParentCase instead?
</blockquote></details>

I was waiting the conversation in the other PR to be resolved. I'll move it there. 


<!-- Sent from Reviewable.io -->

2021-07-27 00:13 UTC, SanjayVas reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/167)* status: 3 of 9 files reviewed, 6 unresolved discussions (waiting on @SanjayVas and @uakyol)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/167#-MfZKNhJ8Ad_UwqF6g8N:-Mf_EwaZ1T3d3QHX9UH9:boavbpg) (no related file):*
> these changes are not implementing the changes you commented on

Ah, you're right and I missed that. The PRs are indeed stacked properly. However (see below)

> Those PR comments are not resolved yet,

That means that code is actively in flux. You shouldn't send new code for review that depends on it. If you've already sent out a new PR where the base PR gets comments that would require change propagation, then you should mark that later PR as draft/WIP (which you've now done) until those comments get resolved. This way no reviewer is trying to review additional code when thing are still actively changing.

> I thought it would save us time to review them in parallel

Well, technically dependent PRs are not reviewed entirely in parallel. That is to say as a reviewer of multiple PRs that are dependent on each other, I likely need to review the base PR first so I have the context for the later PRs (as opposed to relying exclusively on knowledge of the existing submitted code). Normally if I see a stack of PRs and I have comments on the base one, I hold off on reviewing the later ones until the changes are made so I'm not trying to review something that has an unstable base. I don't expect a PR author to send another dependent PR while in this state.

---


<!-- Sent from Reviewable.io -->

2021-07-30 09:39 UTC, uakyol reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/167)* status: 0 of 12 files reviewed, 6 unresolved discussions (waiting on @SanjayVas and @wangyaopw)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/167#-MfZKNhJ8Ad_UwqF6g8N:-MfqdcRk0-eXQQX-I1oy:bwt97pc) (no related file):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> these changes are not implementing the changes you commented on

Ah, you're right and I missed that. The PRs are indeed stacked properly. However (see below)

> Those PR comments are not resolved yet,

That means that code is actively in flux. You shouldn't send new code for review that depends on it. If you've already sent out a new PR where the base PR gets comments that would require change propagation, then you should mark that later PR as draft/WIP (which you've now done) until those comments get resolved. This way no reviewer is trying to review additional code when thing are still actively changing.

> I thought it would save us time to review them in parallel

Well, technically dependent PRs are not reviewed entirely in parallel. That is to say as a reviewer of multiple PRs that are dependent on each other, I likely need to review the base PR first so I have the context for the later PRs (as opposed to relying exclusively on knowledge of the existing submitted code). Normally if I see a stack of PRs and I have comments on the base one, I hold off on reviewing the later ones until the changes are made so I'm not trying to review something that has an unstable base. I don't expect a PR author to send another dependent PR while in this state.


</blockquote></details>

Thank you for the explanation. Resuming this review since the parent PRs are merged and changes reflected to this.

---
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/DuchyIds.kt, line 51 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/167#-MfYvw2h2FnmTHSFjSt1:-MfqdsWi3q_5U_Vv0YnG:bcupyzm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e1f529521742887bfb953da5e1e5b8b8f3d95fa3/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/DuchyIds.kt#L51)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

also add `require(!DuchyIds::entries.isInitialized)`? 
</blockquote></details>

Since this is a global object, this is tricky and I couldn't make it work. In pursuit of making it work though, I implelemeted DuchyIDSetter. That doesn't solve this either. note that, a similar implementation does not have this check: https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/main/kotlin/org/wfanet/measurement/common/identity/DuchyInfo.kt#L46

I think this makes sense, since for test, we overwrite the old entries for each test case. wdyt?
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateCertificate.kt, line 87 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/167#-MfYuVRA26mqbdastV3j:-Mfqdz0KEMKgFP17T0D7:b-h8lpjy) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e1f529521742887bfb953da5e1e5b8b8f3d95fa3/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateCertificate.kt#L87)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
> Long
> ```
Maybe refactor the duchyID to use type `InternalId` for internalDuchyId, so it is more consistent here.
</blockquote></details>

I think we don't need to wrap longs to Internal Ids in the creator, it was a waste. I changed this to Long rather than changing DuchyIds to InternalId, wdyt?


<!-- Sent from Reviewable.io -->

2021-07-30 18:51 UTC, wangyaopw requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/167)* status: 0 of 14 files reviewed, 6 unresolved discussions (waiting on @SanjayVas and @uakyol)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/DuchyIds.kt, line 51 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/167#-MfYvw2h2FnmTHSFjSt1:-Mfsjzml0cXGKcIxZaEA:bs8g1y7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e1f529521742887bfb953da5e1e5b8b8f3d95fa3/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/DuchyIds.kt#L51)):*
> ```
> initializeFromFlags
> ```
initializeFromFlags() and setForTest() are just two functions with different names. There is really no reason one can have this line, but the other cannot.

wherever setForTest() is called,  initializeFromFlags() shouldn't be called before that.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateCertificate.kt, line 87 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/167#-MfYuVRA26mqbdastV3j:-MfsicKm0Xj4QULIMVgZ:b7l3511) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e1f529521742887bfb953da5e1e5b8b8f3d95fa3/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateCertificate.kt#L87)):*
> ```
> internalCertificateId
> ```
In this function, the internalOwnerId is `Long`, but the internalCertificateId is `InternalId`. Better to use both Long and both InternalId for consistency.

But I've no opinion about whether the wrapping is a waste or not. 


<!-- Sent from Reviewable.io -->

2021-07-30 18:53 UTC, wangyaopw requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/167)* status: 0 of 14 files reviewed, 6 unresolved discussions (waiting on @SanjayVas and @uakyol)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateCertificate.kt, line 87 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/167#-MfYuVRA26mqbdastV3j:-MfskqUF0_Ec6S6dAxtJ:b-ym9px5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e1f529521742887bfb953da5e1e5b8b8f3d95fa3/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateCertificate.kt#L87)):*
> both Long and both InternalId
both Long or both InternalId


<!-- Sent from Reviewable.io -->

2021-07-30 21:58 UTC, SanjayVas requested changes
> Reviewed 1 of 9 files at r2, 1 of 9 files at r3, 12 of 12 files at r4.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/167)* status: all files reviewed, 7 unresolved discussions (waiting on @uakyol and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerCertificatesService.kt, line 56 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/167#-MftD6i-60MV3xN-ObZr:-MftD6i-60MV3xN-ObZs:ba1w4y1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3be9e8e3c809d7a7d69a1cca2cbade84b83c8afc/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerCertificatesService.kt#L56)):*
> ```
> INVALID_ARGUMENT
> ```
In this case, NOT_FOUND is fine since what isn't found is the parent (same is true for EDP and MC).
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerCertificatesService.kt, line 56 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/167#-MftE83W5PiqOmUUOO4n:-MftE83W5PiqOmUUOO4o:b-conrid) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3be9e8e3c809d7a7d69a1cca2cbade84b83c8afc/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerCertificatesService.kt#L56)):*
> ```Kotlin
>           }
>         KingdomInternalException.Code.DUCHY_NOT_FOUND ->
>           failGrpc(Status.INVALID_ARGUMENT) { "Duchy not found" }
> ```

When we're failing the RPC due to an internal exception, we should be including the cause in the StatusRuntimeException (e.g. using `Status.withCause`). The causal information isn't transmitted to the client, but can be useful for debugging (e.g. it can be propagated by the in-process channel we use for integration testing).

Leaving this as an optional comment here because if we want to do it "correctly" (i.e. via updating failGrpc), we'd have do so in another repo.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerEventGroupsService.kt, line 46 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/167#-MftHwX96JCE-dpNwJbv:-MftHwXA3b55fdqvsMR7:b-ygm914) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3be9e8e3c809d7a7d69a1cca2cbade84b83c8afc/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerEventGroupsService.kt#L46)):*
> ```Kotlin
>           failGrpc(Status.NOT_FOUND) { "DataProvider not found" }
>         KingdomInternalException.Code.CERT_SUBJECT_KEY_ID_ALREADY_EXISTS -> throw e
>         KingdomInternalException.Code.DUCHY_NOT_FOUND -> throw e
> ```

nit: combine all of the values we don't handle and just rethrow into one case
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/CertificateReader.kt, line 46 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/167#-MftMtzk5xUXgNTFT75g:-MftMtzlEiCkXWGkVqBl:b4e8nh5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3be9e8e3c809d7a7d69a1cca2cbade84b83c8afc/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/CertificateReader.kt#L46)):*
> ```
> Resource
> ```
nit: Avoid overloading "resource" term from resource-oriented APIs
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/CertificateReader.kt, line 84 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/167#-MftNWBQE3VDUC64ajJw:-MftNWBQE3VDUC64ajJx:bd72nr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3be9e8e3c809d7a7d69a1cca2cbade84b83c8afc/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/CertificateReader.kt#L84)):*
> ```Kotlin
>       GetCertificateRequest.ParentCase.EXTERNAL_MEASUREMENT_CONSUMER_ID -> tabledResourceBaseSql
>       GetCertificateRequest.ParentCase.PARENT_NOT_SET ->
>         throw IllegalArgumentException("Parent field of GetCertificateRequest is not set")
> ```

nit: this one can use `error`/IllegalStateException instead, as at this point it's checking class state rather than an argument. (The argument is for the constructor, hence why an IllegalArgumentException there.)
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateCertificate.kt, line 87 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/167#-MfYuVRA26mqbdastV3j:-MftPov531GtoCCXMI-Q:bezwfp3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e1f529521742887bfb953da5e1e5b8b8f3d95fa3/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateCertificate.kt#L87)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> both Long and both InternalId
both Long or both InternalId
</blockquote></details>

Wrapping isn't a waste IMO unless it's an expensive operation. Better to use specific types whenever possible, especially for function params.

Agree that regardless, should be consistent.


<!-- Sent from Reviewable.io -->

2021-08-03 20:52 UTC, uakyol reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/167)* status: 9 of 14 files reviewed, 4 unresolved discussions (waiting on @SanjayVas, @uakyol, and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/DuchyIds.kt, line 51 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/167#-MfYvw2h2FnmTHSFjSt1:-MgCmSeT5WFKpTmGyxJn:buqwsh3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e1f529521742887bfb953da5e1e5b8b8f3d95fa3/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/DuchyIds.kt#L51)):*
> initializeFromFlags
based on offline sync: initializeFromFlags is never called in these test cases. Leaving this as is.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerCertificatesService.kt, line 56 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/167#-MftD6i-60MV3xN-ObZr:-MgCZeGB-EoQgPY0m_t-:b-vhoyqk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3be9e8e3c809d7a7d69a1cca2cbade84b83c8afc/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerCertificatesService.kt#L56)):*
> NOT_FOUND
thanks


<!-- Sent from Reviewable.io -->

2021-08-03 20:53 UTC, uakyol reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/167)* status: 9 of 14 files reviewed, 3 unresolved discussions (waiting on @SanjayVas and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerCertificatesService.kt, line 56 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/167#-MftE83W5PiqOmUUOO4n:-MgCmbTiCEDGK-mcuzru:b-9pm531) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3be9e8e3c809d7a7d69a1cca2cbade84b83c8afc/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerCertificatesService.kt#L56)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

When we're failing the RPC due to an internal exception, we should be including the cause in the StatusRuntimeException (e.g. using `Status.withCause`). The causal information isn't transmitted to the client, but can be useful for debugging (e.g. it can be propagated by the in-process channel we use for integration testing).

Leaving this as an optional comment here because if we want to do it "correctly" (i.e. via updating failGrpc), we'd have do so in another repo.
</blockquote></details>

It seems like next step is to open a github issue. I can do that if that's what you had in mind.


<!-- Sent from Reviewable.io -->

2021-08-03 20:54 UTC, uakyol reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/167)* status: 9 of 14 files reviewed, 2 unresolved discussions (waiting on @SanjayVas and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateCertificate.kt, line 87 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/167#-MfYuVRA26mqbdastV3j:-MgCmo3oD_nyT0WOl-8j:b-i3pc8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e1f529521742887bfb953da5e1e5b8b8f3d95fa3/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateCertificate.kt#L87)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Wrapping isn't a waste IMO unless it's an expensive operation. Better to use specific types whenever possible, especially for function params.

Agree that regardless, should be consistent.
</blockquote></details>

Made them long, Consistent now.


<!-- Sent from Reviewable.io -->

2021-08-03 21:44 UTC, wangyaopw approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/167)* status: 9 of 14 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateCertificate.kt, line 87 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/167#-MfYuVRA26mqbdastV3j:-MgCx9dKAd8hckKy6ywa:bfi3tav) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e1f529521742887bfb953da5e1e5b8b8f3d95fa3/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateCertificate.kt#L87)):*
> ```
> InternalId
> ```
LGTM

but I would personally choose to use `InternalId` here, since `InternalId` is used in other places, for example
https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateCertificate.kt#L74

Not a big deal anyway, I am pretty sure the codebase also uses `long` in other places too.


<!-- Sent from Reviewable.io -->

2021-08-04 00:30 UTC, SanjayVas requested changes
> Reviewed 3 of 5 files at r5, 2 of 2 files at r6, 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/167)* status: all files reviewed, 4 unresolved discussions (waiting on @oliver-amzn, @uakyol, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerCertificatesService.kt, line 56 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/167#-MftE83W5PiqOmUUOO4n:-MgDV_8f7S64PbH6jfaL:b-q02jlz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3be9e8e3c809d7a7d69a1cca2cbade84b83c8afc/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerCertificatesService.kt#L56)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

It seems like next step is to open a github issue. I can do that if that's what you had in mind.
</blockquote></details>

Yes, and a TODO here referencing it.

See https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/docs/code-style.md#format
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/CertificateReader.kt, line 25 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/167#-MgDX19rB1RyHXJMwi8Z:-MgDX19s5EkHkjUo3U1p:b8sfsa) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6a63a5863c908558ec807f69e333c029c9862c1b/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/CertificateReader.kt#L25)):*
> ```
> val request
> ```
private
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/CertificateReader.kt, line 27 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/167#-MgDXDDrBLd-lhEY4GGr:-MgDXDDrBLd-lhEY4GGs:b8gifl5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6a63a5863c908558ec807f69e333c029c9862c1b/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/CertificateReader.kt#L27)):*
> ```Kotlin
> class CertificateReader(val request: GetCertificateRequest) :
>   SpannerReader<CertificateReader.Result>() {
>   data class Result(val certificate: Certificate, val certificateId: Long)
> ```

nit: add blank lines to separate the data class declaration
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/CertificateReader.kt, line 76 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/167#-MgDWl7HCTWB-0tPq_rr:-MgDWl7HCTWB-0tPq_rs:b-v98le8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6a63a5863c908558ec807f69e333c029c9862c1b/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/CertificateReader.kt#L76)):*
> ```Kotlin
>           """.trimIndent()
> 
>   override val baseSql: String = constructBaseSql()
> ```

Don't call instance methods constructor/property initializers. You can use static functions instead. This way you can't unintentionally reference a property that may not yet have been initialized.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/CertificatesServiceTest.kt, line 204 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/167#-MgDY8by1lQMyjJGxQbb:-MgDY8by1lQMyjJGxQbc:b8ibcux) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6a63a5863c908558ec807f69e333c029c9862c1b/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/CertificatesServiceTest.kt#L204)):*
> ```
> NOT_FOUND
> ```
You're already checking the status code, so including it in the message check is redundant.

Since this is using `contains`, just check for the relevant part.


<!-- Sent from Reviewable.io -->

2021-08-05 00:14 UTC, oliver-amzn reviewed
> Reviewed 1 of 9 files at r2, 4 of 12 files at r4, 3 of 5 files at r5, 1 of 2 files at r6, 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/167)* status: all files reviewed, 5 unresolved discussions (waiting on @uakyol and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/common/KingdomInternalException.kt, line 25 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/167#-MgIbubo92_KBpeiQzgg:-MgIbubo92_KBpeiQzgh:b5gcxt2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6a63a5863c908558ec807f69e333c029c9862c1b/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/common/KingdomInternalException.kt#L25)):*
> ```
> DUCHY
> ```

nit: "Duchy"


<!-- Sent from Reviewable.io -->

2021-08-05 14:31 UTC, uakyol reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/167)* status: 10 of 14 files reviewed, 3 unresolved discussions (waiting on @oliver-amzn, @SanjayVas, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/CertificateReader.kt, line 25 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/167#-MgDX19rB1RyHXJMwi8Z:-MgEkQjtB9QnW_ihhCV9:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6a63a5863c908558ec807f69e333c029c9862c1b/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/CertificateReader.kt#L25)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> val request
> ```
private
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/CertificateReader.kt, line 76 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/167#-MgDWl7HCTWB-0tPq_rr:-MgEo-qm5bwhNgWFeGLO:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6a63a5863c908558ec807f69e333c029c9862c1b/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/CertificateReader.kt#L76)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Don't call instance methods constructor/property initializers. You can use static functions instead. This way you can't unintentionally reference a property that may not yet have been initialized.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/CertificatesServiceTest.kt, line 204 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/167#-MgDY8by1lQMyjJGxQbb:-MgEkow2CPKewIJNLX6m:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6a63a5863c908558ec807f69e333c029c9862c1b/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/CertificatesServiceTest.kt#L204)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> NOT_FOUND
> ```
You're already checking the status code, so including it in the message check is redundant.

Since this is using `contains`, just check for the relevant part.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-05 17:14 UTC, SanjayVas approved these changes
> Reviewed 4 of 4 files at r8.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/167)* status: all files reviewed, 2 unresolved discussions (waiting on @uakyol and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerCertificatesService.kt, line 42 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/167#-MgMIV0y29184tDZkGzX:-MgMIV0y29184tDZkGzY:b-edg60t) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/95384f1a84de740534e5818efa31ae5195d8a536/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerCertificatesService.kt#L42)):*
> ```Kotlin
>       "Certificate is missing parent field"
>     }
>     // TODO(world-federation-of-advertisers/cross-media-measurement#178)
> ```

You're missing the action part of this TODO.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/CertificateReader.kt, line 42 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/167#-MgMIeC43eVqX3eFezxz:-MgMIeC43eVqX3eFezy-:b-4nsjm7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/95384f1a84de740534e5818efa31ae5195d8a536/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/CertificateReader.kt#L42)):*
> ```Kotlin
>   }
> 
>   companion object {
> ```

nit: companion object is normally defined at the end of a class


<!-- Sent from Reviewable.io -->

2021-08-11 20:14 UTC, oliver-amzn approved these changes
> Reviewed 1 of 9 files at r3, 1 of 4 files at r8, 2 of 3 files at r9, 1 of 1 files at r10, 2 of 5 files at r11, 1 of 1 files at r12, 4 of 4 files at r14.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/167)* status: all files reviewed, 2 unresolved discussions (waiting on @uakyol and @zachcwc)



<!-- Sent from Reviewable.io -->

2021-08-11 21:06 UTC, uakyol reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/167#-:-Mgr1MqK06I2wu3nTkJa:bnfp4nl)* status: 11 of 14 files reviewed, all discussions resolved (waiting on @oliver-amzn and @zachcwc)



<!-- Sent from Reviewable.io -->

2021-08-11 21:07 UTC, uakyol reviewed
> Reviewed 1 of 3 files at r9, 1 of 5 files at r11, 3 of 3 files at r15.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/167)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zachcwc)



<!-- Sent from Reviewable.io -->

2021-08-11 21:11 UTC, merged