Add HMSS in process tests.
world-federation-of-advertisers/cross-media-measurement pull request #1691
Opened 2024-07-16 19:42 UTC by ple13

2024-07-16 19:42 UTC, wfa-reviewable commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1691)
<!-- Reviewable:end -->

2024-07-24 01:19 UTC, renjiezh requested changes
> Reviewed 2 of 9 files at r1, 18 of 18 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1691)* status: all files reviewed, 5 unresolved discussions (waiting on @kungfucraig, @ple13, and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/utils/ComputationConversions.kt` line 272 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1691#-O2XGw9w8k1JUcjK10Cc:-O2XGw9w8k1JUcjK10Cd:br6vk38) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/49c153b0fc4c874e1c55deb4cf19cca6854678ce/src/main/kotlin/org/wfanet/measurement/duchy/daemon/utils/ComputationConversions.kt#L272)):*
> ```Kotlin
>           is LiquidLegionsSketchMethodology,
>           is LiquidLegionsV2Methodology,
>           null -> {}
> ```

use suppress instead of `null -> `
E.g. [link](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/628614749e9818cc63051134e3aeb736aba68762/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ReachOnlyLiquidLegionsV2Starter.kt#L157)
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/utils/ComputationConversions.kt` line 288 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1691#-O2XHGHNBHwrZzgGpRB0:-O2XHGHNBHwrZzgGpRB1:b-rqxvo7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/49c153b0fc4c874e1c55deb4cf19cca6854678ce/src/main/kotlin/org/wfanet/measurement/duchy/daemon/utils/ComputationConversions.kt#L288)):*
> ```Kotlin
>           is LiquidLegionsSketchMethodology,
>           is LiquidLegionsV2Methodology,
>           null -> {}
> ```

ditto.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/utils/ComputationConversions.kt` line 314 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1691#-O2XHHWS7UCDMZIxJJvw:-O2XHHWS7UCDMZIxJJvx:b-rqxvo7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/49c153b0fc4c874e1c55deb4cf19cca6854678ce/src/main/kotlin/org/wfanet/measurement/duchy/daemon/utils/ComputationConversions.kt#L314)):*
> ```Kotlin
>           is LiquidLegionsSketchMethodology,
>           is LiquidLegionsV2Methodology,
>           null -> {}
> ```

ditto.
___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/InProcessDuchy.kt` line 203 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1691#-O2XHiGx7QP7AXxqfhv7:-O2XHiGyDldIvWGDoS7L:brne3pc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/49c153b0fc4c874e1c55deb4cf19cca6854678ce/src/main/kotlin/org/wfanet/measurement/integration/common/InProcessDuchy.kt#L203)):*
> ```Kotlin
>       ) {
>         val protocolsSetupConfig =
>           if (externalDuchyId == AGGREGATOR_NAME) {
> ```

nit: 
```
when (externalDuchyId) {
  AGGREGATOR_NAME -> //..
  //..
}
```
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/measurementconsumer/MeasurementConsumerSimulator.kt` line 692 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1691#-O2XJ9jgDnBVF-tJlhKE:-O2XJ9jgDnBVF-tJlhKF:b-q6g0ja) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/49c153b0fc4c874e1c55deb4cf19cca6854678ce/src/main/kotlin/org/wfanet/measurement/loadtest/measurementconsumer/MeasurementConsumerSimulator.kt#L692)):*
> ```Kotlin
>           val dataProvider = getDataProvider(it.key)
>           keyToDataProviderMap.put(it.key, dataProvider)
>           if (useEdpsWithHmssCabapilityOnly)
> ```

nit: I am surprised that ktfmt does not complain for this.
```
if () {
} else {
}
``` 


<!-- Sent from Reviewable.io -->

2024-07-24 18:02 UTC, SanjayVas requested changes
> Reviewed 2 of 9 files at r1, 16 of 18 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1691)* status: all files reviewed, 17 unresolved discussions (waiting on @kungfucraig, @ple13, and @renjiezh)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/HonestMajorityShareShuffleStarter.kt` line 51 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1691#-O2_kvS27NGhs-1n282u:-O2_kvS27NGhs-1n282v:b-lfdj5w) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/49c153b0fc4c874e1c55deb4cf19cca6854678ce/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/HonestMajorityShareShuffleStarter.kt#L51)):*
KDoc syntax for properties. This also means describing the property itself in the summary fragment before describing the details in the additional data. e.g.

> Minimum epsilon value for reach noise.
>
> This value is chosen due to memory constraints.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/HonestMajorityShareShuffleStarter.kt` line 213 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1691#-O2_kpA54jlC5g2OK80m:-O2_kpA54jlC5g2OK80n:b-q4vudy) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/49c153b0fc4c874e1c55deb4cf19cca6854678ce/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/HonestMajorityShareShuffleStarter.kt#L213)):*
> ```Kotlin
>           measurementSpec.reachAndFrequency.reachPrivacyParams.toDuchyDifferentialPrivacyParams()
>         require(reachDpParams.delta > 0) { "Reach privacy delta must be greater than 0" }
>         require(reachDpParams.epsilon > MIN_REACH_EPSILON) {
> ```

"Minimum" implies that this check should be `>=`



_Suggestion:_
```Kotlin
reachDpParams.epsilon >= MIN_REACH_EPSILON
```
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/LiquidLegionsV2Starter.kt` line 52 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1691#-O2_oWDD4YQLFG-EmpsY:-O2_oWDD4YQLFG-EmpsZ:b1n5dsb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/49c153b0fc4c874e1c55deb4cf19cca6854678ce/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/LiquidLegionsV2Starter.kt#L52)):*
> ```Kotlin
> import org.wfanet.measurement.system.v1alpha.ComputationParticipant as SystemComputationParticipant
> 
> // Restricts the amount of reach noise due to memory constraint.
> ```

KDoc syntax for properties. 
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ReachOnlyLiquidLegionsV2Starter.kt` line 49 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1691#-O2_oVHiDHLDthjEsrau:-O2_oVHiDHLDthjEsrav:b1n5dsb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/49c153b0fc4c874e1c55deb4cf19cca6854678ce/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ReachOnlyLiquidLegionsV2Starter.kt#L49)):*
> ```Kotlin
> import org.wfanet.measurement.system.v1alpha.ComputationParticipant
> 
> // Restricts the amount of reach noise due to memory constraint.
> ```

KDoc syntax for properties. 
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/shareshuffle/HonestMajorityShareShuffleMill.kt` line 555 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1691#-O2_oA6eEHRtXiBCGzwO:-O2_oA6eEHRtXiBCGzwP:b-zbzgk7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/49c153b0fc4c874e1c55deb4cf19cca6854678ce/src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/shareshuffle/HonestMajorityShareShuffleMill.kt#L555)):*
> ```Kotlin
>           ),
>         )
>       else -> error("Unsupported measurement type $measurementType")
> ```

Use an exhaustive `when` rather than having an else branch.
___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/Configs.kt` line 59 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1691#-O2_oh_M4O7t9JIdfKk2:-O2_oh_M4O7t9JIdfKk3:b-r97p8m) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/49c153b0fc4c874e1c55deb4cf19cca6854678ce/src/main/kotlin/org/wfanet/measurement/integration/common/Configs.kt#L59)):*
> ```Kotlin
>     ProtocolsSetupConfig.getDefaultInstance(),
>   )
> val NON_AGGREGATOR_PROTOCOLS_SETUP_CONFIG: ProtocolsSetupConfig =
> ```

Now that we have explicit configs for worker1 and worker2, can this be dropped?
___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/Configs.kt` line 93 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1691#-O2_qLaPE4hiryhB_sUd:-O2_qLaPE4hiryhB_sUe:bmqgphv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/49c153b0fc4c874e1c55deb4cf19cca6854678ce/src/main/kotlin/org/wfanet/measurement/integration/common/Configs.kt#L93)):*
> ```Kotlin
> val AGGREGATOR_NAME =
>   AGGREGATOR_PROTOCOLS_SETUP_CONFIG.honestMajorityShareShuffle.aggregatorDuchyId!!
> val WORKER_ONE_NAME =
> ```

nit: be consistent with constants we have elsewhere, e.g. in `org.wfanet.measurement.kingdom.service.internal.testing`



_Suggestion:_
```Kotlin
WORKER1_NAME
```
___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/Configs.kt` line 100 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1691#-O2_pXEY8M-XQf0OGzSh:-O2_pXEY8M-XQf0OGzSi:bcouljs) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/49c153b0fc4c874e1c55deb4cf19cca6854678ce/src/main/kotlin/org/wfanet/measurement/integration/common/Configs.kt#L100)):*
> ```Kotlin
> val DUCHY_ID_CONFIG: DuchyIdConfig =
>   loadTextProto("duchy_id_config.textproto", DuchyIdConfig.getDefaultInstance())
> val ALL_DUCHY_NAMES = DUCHY_ID_CONFIG.duchiesList.map { it.externalDuchyId }
> ```

nit: add a check here to ensure that duchy_id_config.textproto and aggregator_protocols_setup_config.textproto are consistent, i.e. that the former contains all the external Duchy IDs that are in the latter.



_Suggestion:_
```Kotlin
DUCHY_ID_CONFIG.duchiesList.map { it.externalDuchyId }.also { check(it.containsAll(listOf(AGGREGATOR_NAME, WORKER_ONE_NAME, WORKER_TWO_NAME))) }
```
___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/Configs.kt` line 116 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1691#-O2_qdFE11r5W_0n0PoH:-O2_qdFE11r5W_0n0PoI:b-pdkekj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/49c153b0fc4c874e1c55deb4cf19cca6854678ce/src/main/kotlin/org/wfanet/measurement/integration/common/Configs.kt#L116)):*
> ```Kotlin
>   }
> 
> val ALL_HMSS_EDP_DISPLAY_NAMES = listOf("edp1", "edp2")
> ```

nit: add some documentation for these properties so it's clear what they mean. I assume the HMSS EDPs also support LLv2 (as currently all EDPs **must** support LLv2, though that will change in the future likely using a negative capability)
___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/InProcessEdpSimulator.kt` line 91 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1691#-O2_rjL32gwcirM14XWX:-O2_rjL32gwcirM14XWY:bwawva6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/49c153b0fc4c874e1c55deb4cf19cca6854678ce/src/main/kotlin/org/wfanet/measurement/integration/common/InProcessEdpSimulator.kt#L91)):*
> ```Kotlin
>           (vidRangeStart until vidRangeEndExclusive).asSequence()
>         )
>       } else emptyMap()
> ```

nit: if using braces for one branch of an `if`, use them for all branches
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/measurementconsum [...]

2024-07-24 21:34 UTC, kungfucraig requested changes
> Reviewed 1 of 9 files at r1, 13 of 18 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1691)* status: all files reviewed, 18 unresolved discussions (waiting on @ple13 and @renjiezh)

___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/InProcessLifeOfAMeasurementIntegrationTest.kt` line 126 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1691#-O2aebsF4fV6uO7p-_pb:-O2aebsF4fV6uO7p-_pc:bujw10w) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/49c153b0fc4c874e1c55deb4cf19cca6854678ce/src/main/kotlin/org/wfanet/measurement/integration/common/InProcessLifeOfAMeasurementIntegrationTest.kt#L126)):*
> ```Kotlin
> 
>   @Test
>   fun `create a Hmss RF measurement and check the result is equal to the expected result`() =
> ```

How can you ensure that HMSS was actually used for the test? Same for LLv2 above.


<!-- Sent from Reviewable.io -->

2024-07-25 21:38 UTC, ple13 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1691)* status: 8 of 23 files reviewed, 12 unresolved discussions (waiting on @kungfucraig, @renjiezh, and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/HonestMajorityShareShuffleStarter.kt` line 51 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1691#-O2_kvS27NGhs-1n282u:-O2fWybn6H2Mi_s3L6mJ:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/49c153b0fc4c874e1c55deb4cf19cca6854678ce/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/HonestMajorityShareShuffleStarter.kt#L51)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

KDoc syntax for properties. This also means describing the property itself in the summary fragment before describing the details in the additional data. e.g.

> Minimum epsilon value for reach noise.
>
> This value is chosen due to memory constraints.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/HonestMajorityShareShuffleStarter.kt` line 213 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1691#-O2_kpA54jlC5g2OK80m:-O2fXWII5svLMNO2VFmf:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/49c153b0fc4c874e1c55deb4cf19cca6854678ce/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/HonestMajorityShareShuffleStarter.kt#L213)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

"Minimum" implies that this check should be `>=`
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/LiquidLegionsV2Starter.kt` line 52 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1691#-O2_oWDD4YQLFG-EmpsY:-O2fXXsq7qOAxgSJcOq3:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/49c153b0fc4c874e1c55deb4cf19cca6854678ce/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/LiquidLegionsV2Starter.kt#L52)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

KDoc syntax for properties.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ReachOnlyLiquidLegionsV2Starter.kt` line 49 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1691#-O2_oVHiDHLDthjEsrau:-O2fXZ1xE0-W_X8c1pjc:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/49c153b0fc4c874e1c55deb4cf19cca6854678ce/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ReachOnlyLiquidLegionsV2Starter.kt#L49)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

KDoc syntax for properties.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/shareshuffle/HonestMajorityShareShuffleMill.kt` line 555 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1691#-O2_oA6eEHRtXiBCGzwO:-O2fYxkp-8J9wa4ixPIL:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/49c153b0fc4c874e1c55deb4cf19cca6854678ce/src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/shareshuffle/HonestMajorityShareShuffleMill.kt#L555)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Use an exhaustive `when` rather than having an else branch.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/utils/ComputationConversions.kt` line 272 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1691#-O2XGw9w8k1JUcjK10Cc:-O2fLzxvBhpslcfZZcnG:bguxu9n) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/49c153b0fc4c874e1c55deb4cf19cca6854678ce/src/main/kotlin/org/wfanet/measurement/duchy/daemon/utils/ComputationConversions.kt#L272)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

use suppress instead of `null -> `
E.g. [link](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/628614749e9818cc63051134e3aeb736aba68762/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ReachOnlyLiquidLegionsV2Starter.kt#L157)
</blockquote></details>

We've exhausted all the branches, so null is not needed here.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/utils/ComputationConversions.kt` line 288 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1691#-O2XHGHNBHwrZzgGpRB0:-O2fM71fD2sHhGbYGFXH:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/49c153b0fc4c874e1c55deb4cf19cca6854678ce/src/main/kotlin/org/wfanet/measurement/duchy/daemon/utils/ComputationConversions.kt#L288)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

ditto.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/utils/ComputationConversions.kt` line 314 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1691#-O2XHHWS7UCDMZIxJJvw:-O2fM8JB9ePRIpu-Fc_N:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/49c153b0fc4c874e1c55deb4cf19cca6854678ce/src/main/kotlin/org/wfanet/measurement/duchy/daemon/utils/ComputationConversions.kt#L314)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

ditto.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/Configs.kt` line 59 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1691#-O2_oh_M4O7t9JIdfKk2:-O2fMyjvCR_RaxxCc7n-:butokbk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/49c153b0fc4c874e1c55deb4cf19cca6854678ce/src/main/kotlin/org/wfanet/measurement/integration/common/Configs.kt#L59)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Now that we have explicit configs for worker1 and worker2, can this be dropped?
</blockquote></details>

Yeah, this is not used in the tests anymore.
___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/Configs.kt` line 93 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1691#-O2_qLaPE4hiryhB_sUd:-O2fNHsTDCLAHhpg5IEC:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/49c153b0fc4c874e1c55deb4cf19cca6854678ce/src/main/kotlin/org/wfanet/measurement/integration/common/Configs.kt#L93)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: be consistent with constants we have elsewhere, e.g. in `org.wfanet.measurement.kingdom.service.internal.testing`
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/Configs.kt` line 100 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1691#-O2_pXEY8M-XQf0OGzSh:-O2fO3WTCap31JnKXOyh:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/49c153b0fc4c874e1c55deb4cf19cca6854678ce/src/main/kotlin/org/wfanet/measurement/integration/common/Configs.kt#L100)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: add a check here to ensure that duchy_id_config.textproto and aggregator_protocols_setup_config.textproto are consistent, i.e. that the former contains all the external Duchy IDs that are in the latter.
</blockquote></de [...]

2024-07-25 23:38 UTC, SanjayVas requested changes
> Reviewed 13 of 15 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1691)* status: 21 of 23 files reviewed, 11 unresolved discussions (waiting on @kungfucraig, @ple13, and @renjiezh)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/HonestMajorityShareShuffleStarter.kt` line 51 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1691#-O2_kvS27NGhs-1n282u:-O2gDq3l7NT7LMahgtqt:b57hxc3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/49c153b0fc4c874e1c55deb4cf19cca6854678ce/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/HonestMajorityShareShuffleStarter.kt#L51)):*
<details><summary><i>Previously, ple13 (Phi) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

This is still not using KDoc syntax. See https://developer.android.com/kotlin/style-guide#documentation

```
/**
 * This is KDoc syntax.
 *
 * Note the double stars on the first line.
 */
```
___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/InProcessDuchy.kt` line 208 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1691#-O2gEfbh0olYvYxR1Xt3:-O2gEfbh0olYvYxR1Xt4:b41sqm0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4909bc9204003ca8f4202e1cd4f77a6a2cb74581/src/main/kotlin/org/wfanet/measurement/integration/common/InProcessDuchy.kt#L208)):*
> ```Kotlin
>             WORKER2_NAME -> WORKER2_PROTOCOLS_SETUP_CONFIG
>             else -> {
>               throw IllegalArgumentException(
> ```

nit: IllegalStateException (or use the `error` convenience function, which does the same thing) since this isn't an error about an argument to this function.



_Code quote:_
```Kotlin
IllegalArgumentException
```
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/measurementconsumer/MeasurementConsumerSimulator.kt` line 704 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1691#-O2gF0WZC99tTTxoyI_P:-O2gF0WZC99tTTxoyI_Q:bsfzy52) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4909bc9204003ca8f4202e1cd4f77a6a2cb74581/src/main/kotlin/org/wfanet/measurement/loadtest/measurementconsumer/MeasurementConsumerSimulator.kt#L704)):*
> ```Kotlin
>     newMeasurementSpec:
>       (packedMeasurementPublicKey: ProtoAny, nonceHashes: List<ByteString>) -> MeasurementSpec,
>     capabilities: DataProvider.Capabilities,
> ```

nit: call this requiredCapabilities so it's clear this is saying which capabilities are required. You can also default this to DataProvider.Capabilities.getDefaultInstance() for convenience.



_Suggestion:_
```Kotlin
requiredCapabilities: DataProvider.Capabilities = DataProvider.Capabilities.getDefaultInstance(),
```
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/measurementconsumer/MeasurementConsumerSimulator.kt` line 728 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1691#-O2gFQP158OXFKlUstWs:-O2gFQP158OXFKlUstWt:b-qn12kr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4909bc9204003ca8f4202e1cd4f77a6a2cb74581/src/main/kotlin/org/wfanet/measurement/loadtest/measurementconsumer/MeasurementConsumerSimulator.kt#L728)):*
> ```Kotlin
>           val dataProvider =
>             keyToDataProviderMap[it.key]
>               ?: throw NoSuchElementException("Data provider key not found: ${it.key}")
> ```

Using getValue will throw this exception for you.



_Suggestion:_
```Kotlin
            keyToDataProviderMap.getValue(it.key)
```


<!-- Sent from Reviewable.io -->

2024-07-26 18:57 UTC, ple13 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1691)* status: 16 of 23 files reviewed, 9 unresolved discussions (waiting on @kungfucraig, @renjiezh, and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/HonestMajorityShareShuffleStarter.kt` line 51 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1691#-O2_kvS27NGhs-1n282u:-O2kKktV5ZRggZI-zg0d:boyexbg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/49c153b0fc4c874e1c55deb4cf19cca6854678ce/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/HonestMajorityShareShuffleStarter.kt#L51)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This is still not using KDoc syntax. See https://developer.android.com/kotlin/style-guide#documentation

```
/**
 * This is KDoc syntax.
 *
 * Note the double stars on the first line.
 */
```
</blockquote></details>

Done. Thanks.
___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/InProcessDuchy.kt` line 208 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1691#-O2gEfbh0olYvYxR1Xt3:-O2kLW9n-_72alHs-M1g:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4909bc9204003ca8f4202e1cd4f77a6a2cb74581/src/main/kotlin/org/wfanet/measurement/integration/common/InProcessDuchy.kt#L208)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: IllegalStateException (or use the `error` convenience function, which does the same thing) since this isn't an error about an argument to this function.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/measurementconsumer/MeasurementConsumerSimulator.kt` line 704 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1691#-O2gF0WZC99tTTxoyI_P:-O2kMlo04ddQUwMcQjTi:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4909bc9204003ca8f4202e1cd4f77a6a2cb74581/src/main/kotlin/org/wfanet/measurement/loadtest/measurementconsumer/MeasurementConsumerSimulator.kt#L704)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: call this requiredCapabilities so it's clear this is saying which capabilities are required. You can also default this to DataProvider.Capabilities.getDefaultInstance() for convenience.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/measurementconsumer/MeasurementConsumerSimulator.kt` line 728 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1691#-O2gFQP158OXFKlUstWs:-O2kMjZO7ViZ7ntitYNA:boyexbg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4909bc9204003ca8f4202e1cd4f77a6a2cb74581/src/main/kotlin/org/wfanet/measurement/loadtest/measurementconsumer/MeasurementConsumerSimulator.kt#L728)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Using getValue will throw this exception for you.
</blockquote></details>

Done. Thanks.


<!-- Sent from Reviewable.io -->

2024-07-26 19:15 UTC, SanjayVas approved these changes
> Reviewed 2 of 15 files at r3, 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1691)* status: all files reviewed, 4 unresolved discussions (waiting on @kungfucraig and @renjiezh)



<!-- Sent from Reviewable.io -->

2024-07-26 19:38 UTC, kungfucraig approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1691)* status: all files reviewed, 3 unresolved discussions (waiting on @renjiezh)



<!-- Sent from Reviewable.io -->

2024-07-26 19:55 UTC, renjiezh approved these changes
> Reviewed 10 of 15 files at r3, 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1691)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ple13)



<!-- Sent from Reviewable.io -->

2024-07-26 21:29 UTC, merged

2024-07-31 22:27 UTC, SanjayVas commented
I'm investigating this interesting failure:

```
1) create a Hmss RF measurement and check the result is equal to the expected result(org.wfanet.measurement.integration.deploy.gcloud.GCloudSpannerInProcessLifeOfAMeasurementIntegrationTest)
expected: HONEST_MAJORITY_SHARE_SHUFFLE
but was : DIRECT
	at org.wfanet.measurement.loadtest.measurementconsumer.MeasurementConsumerSimulator.testReachAndFrequency(MeasurementConsumerSimulator.kt:264)
	at org.wfanet.measurement.loadtest.measurementconsumer.MeasurementConsumerSimulator$testReachAndFrequency$1.invokeSuspend(MeasurementConsumerSimulator.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at org.wfanet.measurement.integration.common.InProcessLifeOfAMeasurementIntegrationTest.create a Hmss RF measurement and check the result is equal to the expected result(InProcessLifeOfAMeasurementIntegrationTest.kt:131)
```

2024-07-31 22:52 UTC, SanjayVas commented
Filed #1728 for the above.