Write Metrics to BigQuery
world-federation-of-advertisers/cross-media-measurement pull request #1696
Opened 2024-07-18 19:23 UTC by tristanvuong2021

2024-07-18 19:23 UTC, wfa-reviewable commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696)
<!-- Reviewable:end -->

2024-07-31 20:34 UTC, SanjayVas requested changes
> Reviewed 7 of 22 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696)* status: 7 of 22 files reviewed, 6 unresolved discussions (waiting on @kungfucraig and @tristanvuong2021)

___
*[`MODULE.bazel` line 296 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696#-O39Sco3C-PCUIomQ-1S:-O39Sco3C-PCUIomQ-1T:b-yr5xly) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f583e42b55032c910db35b7d7024ee6d751abeca/MODULE.bazel#L296)):*
> ```Starlark
> )
> 
> archive_override(
> ```

Until this has a release version, add a DO_NOT_SUBMIT comment referencing the source PR so it's easy to find what changes this is pulling in.
___
*[`.github/workflows/deploy-kingdom.yml` line 15 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696#-O39SrL53-iL_qkS2UIK:-O39SrL53-iL_qkS2UIL:bixzj3g) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f583e42b55032c910db35b7d7024ee6d751abeca/.github/workflows/deploy-kingdom.yml#L15)):*
> ```YAML
> # limitations under the License.
> 
> name: Deploy Kingdom
> ```

We don't want a separate workflow for this since the Terraform affects all clusters. The separate Terraform and Kingdom K8s workflows are fine.
___
*[`.github/workflows/push-kingdom-images.yml` line 15 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696#-O39T3jVCjrx2Iih1aQR:-O39T3jVCjrx2Iih1aQS:b36i3lt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f583e42b55032c910db35b7d7024ee6d751abeca/.github/workflows/push-kingdom-images.yml#L15)):*
> ```YAML
> # limitations under the License.
> 
> name: Build and push kingdom container images
> ```

We don't want to have to maintain a separate workflow for this. Pushing all images at once is fine.
___
*[`.github/workflows/terraform-cmms.yml` line 98 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696#-O39TNmS3QJ-tM1KNNha:-O39TNmS3QJ-tM1KNNhb:b-nbwnii) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b97e4cfef883d77ba5faaec4647c4bf47e01f0d4/.github/workflows/terraform-cmms.yml#L98)):*
> ```YAML
>       working-directory: ${{ env.GCLOUD_MODULE_PATH }}
>       run: terraform apply -input=false tfplan
> ```

Why is this removed? We need to Terraform AWS as well...
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/job/OperationalMetricsJob.kt` line 64 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696#-O39U0NfCB0gY8X-nuUt:-O39U0NfCB0gY8X-nuUu:b-fgqfou) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f583e42b55032c910db35b7d7024ee6d751abeca/src/main/kotlin/org/wfanet/measurement/kingdom/job/OperationalMetricsJob.kt#L64)):*
> ```Kotlin
> import org.wfanet.measurement.kingdom.deploy.gcloud.spanner.queries.StreamMeasurements
> 
> class OperationalMetricsJob(
> ```

"Job" should be at the same level as "Server" or "Daemon", meaning the class name ending in "Job" should be the one with the main function.

Maybe call this one "OperationalMetricsExport" and rename the "Executor" to "OperationalMetricsExportJob"? I'd also expect a class with a name ending in Executor to implement `java.util.Executor`.



_Suggestion:_
```Kotlin
OperationalMetricsExport
```
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/job/OperationalMetricsJob.kt` line 125 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696#-O39Ul5u-0Rjqo6er6u5:-O39Ul5u-0Rjqo6er6u6:bif4t52) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f583e42b55032c910db35b7d7024ee6d751abeca/src/main/kotlin/org/wfanet/measurement/kingdom/job/OperationalMetricsJob.kt#L125)):*
> ```Kotlin
> 
>       try {
>         StreamMeasurements(
> ```

Only the internal API server may have DB access. This must call the internal API instead.


<!-- Sent from Reviewable.io -->

2024-08-01 16:26 UTC, tristanvuong2021 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696)* status: 4 of 26 files reviewed, 6 unresolved discussions (waiting on @kungfucraig and @SanjayVas)

___
*[`MODULE.bazel` line 296 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696#-O39Sco3C-PCUIomQ-1S:-O3DkmPK-t3x1gcWS-ZH:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f583e42b55032c910db35b7d7024ee6d751abeca/MODULE.bazel#L296)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Until this has a release version, add a DO_NOT_SUBMIT comment referencing the source PR so it's easy to find what changes this is pulling in.
</blockquote></details>

Done.
___
*[`.github/workflows/deploy-kingdom.yml` line 15 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696#-O39SrL53-iL_qkS2UIK:-O3DknOYADJFdHAgYp7f:bbu9v8g) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f583e42b55032c910db35b7d7024ee6d751abeca/.github/workflows/deploy-kingdom.yml#L15)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

We don't want a separate workflow for this since the Terraform affects all clusters. The separate Terraform and Kingdom K8s workflows are fine.
</blockquote></details>

this is for testing
___
*[`.github/workflows/push-kingdom-images.yml` line 15 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696#-O39T3jVCjrx2Iih1aQR:-O3DkpfHD-jtgOKpnVLE:bbu9v8g) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f583e42b55032c910db35b7d7024ee6d751abeca/.github/workflows/push-kingdom-images.yml#L15)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

We don't want to have to maintain a separate workflow for this. Pushing all images at once is fine.
</blockquote></details>

this is for testing
___
*[`.github/workflows/terraform-cmms.yml` line 98 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696#-O39TNmS3QJ-tM1KNNha:-O3DkrNW1KrwcMXppnSB:bbu9v8g) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b97e4cfef883d77ba5faaec4647c4bf47e01f0d4/.github/workflows/terraform-cmms.yml#L98)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Why is this removed? We need to Terraform AWS as well...
</blockquote></details>

this is for testing
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/job/OperationalMetricsJob.kt` line 64 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696#-O39U0NfCB0gY8X-nuUt:-O3Dktv3BVBoSuUQUTCx:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f583e42b55032c910db35b7d7024ee6d751abeca/src/main/kotlin/org/wfanet/measurement/kingdom/job/OperationalMetricsJob.kt#L64)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

"Job" should be at the same level as "Server" or "Daemon", meaning the class name ending in "Job" should be the one with the main function.

Maybe call this one "OperationalMetricsExport" and rename the "Executor" to "OperationalMetricsExportJob"? I'd also expect a class with a name ending in Executor to implement `java.util.Executor`.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/job/OperationalMetricsJob.kt` line 125 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696#-O39Ul5u-0Rjqo6er6u5:-O3DkuRyBijkRGP_hbMf:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f583e42b55032c910db35b7d7024ee6d751abeca/src/main/kotlin/org/wfanet/measurement/kingdom/job/OperationalMetricsJob.kt#L125)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Only the internal API server may have DB access. This must call the internal API instead.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-08-01 18:39 UTC, SanjayVas requested changes
> Reviewed 1 of 22 files at r1, 14 of 21 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696)* status: 16 of 27 files reviewed, 16 unresolved discussions (waiting on @kungfucraig and @tristanvuong2021)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696#-O3E832M4l3zcALo20VW:-O3E832N1KijA5IhyeDZ:bmkffd0) (no related file):*
Add DO_NOT_SUBMIT comments for the testing parts so it's clear they are not intended to be submitted/merged.

___
___
*[`imports/java/com/google/cloud/bigquerystorage/BUILD.bazel` line 1 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696#-O3E1_ss6wxnd9k3lrmE:-O3E1_ss6wxnd9k3lrmF:biatxqg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/afeea426d99033939001594010c0f21ed64460f7/imports/java/com/google/cloud/bigquerystorage/BUILD.bazel#L1)):*
> ```Starlark
> package(default_visibility = ["//visibility:public"])
> ```

The Bazel package path should correspond to the Java package. This provides classes in `com.google.cloud.bigquery.storage`, so this should be defined in `//imports/java/com/google/cloud/bigquery/storage`
___
*[`src/main/docker/images.bzl` line 157 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696#-O3E2AKkEoLBledh51Op:-O3E2AKkEoLBledh51Oq:blax8go) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/afeea426d99033939001594010c0f21ed64460f7/src/main/docker/images.bzl#L157)):*
> ```Starlark
>         name = "kingdom_operational_metrics_export_image",
>         image = "//src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/job:operational_metrics_export_job_image",
>         repository = _PREFIX + "/kingdom/operational-metrics",
> ```

nit: maybe add "bigquery" in here in case we add another impl that exports elsewhere?



_Suggestion:_
```Starlark
/kingdom/bigquery-operational-metrics
```
___
*[`src/main/k8s/dev/kingdom_gke.cue` line 49 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696#-O3E8ezx9NysknblEE4r:-O3E8ezx9NysknblEE4s:b-hsmi7d) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/afeea426d99033939001594010c0f21ed64460f7/src/main/k8s/dev/kingdom_gke.cue#L49)):*
> ```CUE
> 	requests: {
> 		cpu:    "20m"
> 		memory: "256Mi"
> ```

Did you actually look at JVM metrics to determine this value (e.g. looking at the heap memory after GC, determining the appropriate value for max heap, and then computing what the resulting overall container memory usage would be at max heap)? I couldn't find anything for this CronJob in Metrics Explorer on dev...
___
*[`src/main/k8s/dev/kingdom_gke.cue` line 138 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696#-O3E421L22X9pxbeEPfa:-O3E421L22X9pxbeEPfb:b-ri8wov) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/afeea426d99033939001594010c0f21ed64460f7/src/main/k8s/dev/kingdom_gke.cue#L138)):*
> ```CUE
> 	}
> 
> 	networkPolicies: {
> ```

Don't you also need to update the internal server network policy to let operational metrics jobs call it?
___
*[`src/main/k8s/dev/kingdom_gke.cue` line 142 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696#-O3E3x4J0wpdVvn6XG7A:-O3E3x4K6tn-BKY6rFEq:b-c4uxcl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/afeea426d99033939001594010c0f21ed64460f7/src/main/k8s/dev/kingdom_gke.cue#L142)):*
> ```CUE
> 			_app_label: "operational-metrics-app"
> 			_egresses: {
> 				// Need to send external traffic to Spanner and BigQuery.
> ```

No longer true



_Code quote:_
```CUE
Spanner and
```
___
*[`src/main/proto/wfa/measurement/internal/kingdom/operational_metrics.proto` line 17 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696#-O3E5Sr-7opKAqr3O1vW:-O3E5Sr-7opKAqr3O1vX:b-ltmp4b) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/afeea426d99033939001594010c0f21ed64460f7/src/main/proto/wfa/measurement/internal/kingdom/operational_metrics.proto#L17)):*
> ```proto
> syntax = "proto3";
> 
> package wfa.measurement.internal.kingdom;
> ```

Put these in another package (or maybe just a subpackage) to make it clearer that they are not part of the Kingdom internal API.
___
*[`src/main/proto/wfa/measurement/internal/kingdom/operational_metrics.proto` line 22 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696#-O3E69Gu3NDte7zlu46l:-O3E69Gu3NDte7zlu46m:b-qepenu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/afeea426d99033939001594010c0f21ed64460f7/src/main/proto/wfa/measurement/internal/kingdom/operational_metrics.proto#L22)):*
> ```proto
> option java_multiple_files = true;
> 
> message MeasurementData {
> ```

nit: I'm not a fan of "Data" suffixes. Any chance of coming up with a better naming scheme?



_Code quote:_
```proto
MeasurementData
```
___
*[`src/main/proto/wfa/measurement/internal/kingdom/operational_metrics.proto` line 27 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696#-O3EAGfw6zhfYhKYj3cM:-O3EAGfw6zhfYhKYj3cN:bmk0bfy) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/afeea426d99033939001594010c0f21ed64460f7/src/main/proto/wfa/measurement/internal/kingdom/operational_metrics.proto#L27)):*
> ```proto
> 
>   bool is_direct = 3;
>   // `REACH_AND_FREQUENCY`, `REACH`, `IMPRESSION`, `DURATION`, or `POPULATION`
> ```

Does BigQuery not support protobuf enums?
___
*[`src/main/proto/wfa/measurement/internal/kingdom/operational_metrics.proto` line 34 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696#-O3E9pGg5-p1i9lnQB7W:-O3E9pGg5-p1i9lnQB7X:bmqb7gj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/afeea426d99033939001594010c0f21ed64460f7/src/main/proto/wfa/measurement/internal/kingdom/operational_metrics.proto#L34)):*
> ```proto
> 
>   // in microseconds
>   int64 create_time = 6;
> ```

Does BigQuery not support more specific types for times in protobufs?
___
*[`src/main/proto/wfa/measurement/internal/kingdom/operational_metrics.proto` line 39 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696#-O3EAihD74mxxXR6nFGQ:-O3EAihD74mxxXR6nFGR:b5r9g3d) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/afeea426d99033939001594010c0f21ed64460f7/src/main/proto/wfa/measurement/internal/kingdom/operational_metrics.proto#L39)):*
> ```proto
>   // in milliseconds
>   int64 update_time_minus_create_time = 8;
>   int64 update_time_minus_create_time_squared = 9;
> ```

Why do we need to persist these rather than letting them be computed by the query? Math on the fields of a single record should be trivial to accomplish in query language.



_Code quote:_
```proto
  int64 update_time_minus_create_time = 8;
  int64 update_time_minus_create_time_squared = 9;
```
___
*[`src/main/terraform/gcloud/cmms/kingdom.tf` line 40 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696#-O3E6d159dZXD5M2R-56:-O3E6d159dZXD5M2R-57:b-eame5l) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/afeea426d99033939001594010c0f21ed64460f7/src/main/terraform/gcloud/cmms/kingdom.tf#L40)):*
> ```HCL
> }
> 
> resource "google_bigquery_dataset" "operational_metrics" {
> ```

This is the Terraform config exclusively for test environments. This either needs to be moved into a module (preferred) or duplicated in the example config (if [...]

2024-08-01 21:06 UTC, tristanvuong2021 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696)* status: 9 of 29 files reviewed, 14 unresolved discussions (waiting on @kungfucraig and @SanjayVas)

___
*[`src/main/k8s/dev/kingdom_gke.cue` line 49 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696#-O3E8ezx9NysknblEE4r:-O3EINF47DLjHxN0ACU4:b-hdxlx8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/afeea426d99033939001594010c0f21ed64460f7/src/main/k8s/dev/kingdom_gke.cue#L49)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Did you actually look at JVM metrics to determine this value (e.g. looking at the heap memory after GC, determining the appropriate value for max heap, and then computing what the resulting overall container memory usage would be at max heap)? I couldn't find anything for this CronJob in Metrics Explorer on dev...
</blockquote></details>

I just quickly deployed it multiple times and increased it until it stopped crashing
___
*[`src/main/k8s/dev/kingdom_gke.cue` line 138 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696#-O3E421L22X9pxbeEPfa:-O3EIX6915wSChOcWO12:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/afeea426d99033939001594010c0f21ed64460f7/src/main/k8s/dev/kingdom_gke.cue#L138)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Don't you also need to update the internal server network policy to let operational metrics jobs call it?
</blockquote></details>

Done.
___
*[`src/main/k8s/dev/kingdom_gke.cue` line 142 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696#-O3E3x4J0wpdVvn6XG7A:-O3EIWno1eU4FN9Yb2Fq:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/afeea426d99033939001594010c0f21ed64460f7/src/main/k8s/dev/kingdom_gke.cue#L142)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

No longer true
</blockquote></details>

Done.
___
*[`src/main/terraform/gcloud/cmms/kingdom.tf` line 40 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696#-O3E6d159dZXD5M2R-56:-O3EZB4o90uHAy4Maq27:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/afeea426d99033939001594010c0f21ed64460f7/src/main/terraform/gcloud/cmms/kingdom.tf#L40)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This is the Terraform config exclusively for test environments. This either needs to be moved into a module (preferred) or duplicated in the example config (if it's something that should differ per environment).
</blockquote></details>

Done.
___
*[`imports/java/com/google/cloud/bigquerystorage/BUILD.bazel` line 1 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696#-O3E1_ss6wxnd9k3lrmE:-O3EI2Wm5bw7aUrXHBUb:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/afeea426d99033939001594010c0f21ed64460f7/imports/java/com/google/cloud/bigquerystorage/BUILD.bazel#L1)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The Bazel package path should correspond to the Java package. This provides classes in `com.google.cloud.bigquery.storage`, so this should be defined in `//imports/java/com/google/cloud/bigquery/storage`
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/job/OperationalMetricsExport.kt` line 17 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696#-O3E9Xj84Wi4QUMOT9lX:-O3EJa2uApyVsD99RdZL:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/afeea426d99033939001594010c0f21ed64460f7/src/main/kotlin/org/wfanet/measurement/kingdom/job/OperationalMetricsExport.kt#L17)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This needs to be in the deploy/gcloud package since it directly references a gcloud API.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/job/OperationalMetricsExport.kt` line 232 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696#-O3E7dcWBXLHdBQ5BkPF:-O3EJqf89xhT8zVDI_8M:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/afeea426d99033939001594010c0f21ed64460f7/src/main/kotlin/org/wfanet/measurement/kingdom/job/OperationalMetricsExport.kt#L232)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Either log or throw, not both
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/job/OperationalMetricsExport.kt` line 236 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696#-O3E7i240g3HI3XRxQ88:-O3EJrZ09z7suht-UWNi:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/afeea426d99033939001594010c0f21ed64460f7/src/main/kotlin/org/wfanet/measurement/kingdom/job/OperationalMetricsExport.kt#L236)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This exporter is unaware of the fact that the Kingdom internal service impl uses Spanner.
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/internal/kingdom/operational_metrics.proto` line 17 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696#-O3E5Sr-7opKAqr3O1vW:-O3ELEu--xZiA3sbpwmu:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/afeea426d99033939001594010c0f21ed64460f7/src/main/proto/wfa/measurement/internal/kingdom/operational_metrics.proto#L17)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Put these in another package (or maybe just a subpackage) to make it clearer that they are not part of the Kingdom internal API.
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/internal/kingdom/operational_metrics.proto` line 27 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696#-O3EAGfw6zhfYhKYj3cM:-O3ELE2M9IXQdPXD1kWO:b-lqvs0a) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/afeea426d99033939001594010c0f21ed64460f7/src/main/proto/wfa/measurement/internal/kingdom/operational_metrics.proto#L27)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Does BigQuery not support protobuf enums?
</blockquote></details>

It gets stored as a string. It just makes things easier for me to do the conversion myself.
___
*[`src/main/proto/wfa/measurement/internal/kingdom/operational_metrics.proto` line 34 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696#-O3E9pGg5-p1i9lnQB7W:-O3ELxvT1ufnSGKoOVA3:b-z4j0p2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/afeea426d99033939001594010c0f21ed64460f7/src/main/proto/wfa/measurement/internal/kingdom/operational_metrics.proto#L34)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Does BigQuery not support more specific types for times in protobufs?
</blockquote></details>

It gets translated to a bigquery timestamp when ingested.
___
*[`src/main/proto/wfa/measurement/internal/kingdom/operational_metrics.proto` line 39 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-meas [...]

2024-08-02 19:45 UTC, SanjayVas requested changes
> Reviewed 1 of 21 files at r2, 13 of 16 files at r4, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696)* status: 27 of 30 files reviewed, 11 unresolved discussions (waiting on @kungfucraig and @tristanvuong2021)

___
*[`src/main/k8s/dev/kingdom_gke.cue` line 49 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696#-O3E8ezx9NysknblEE4r:-O3JSYBPDGwFzFxo2_ZX:b-okuix8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/afeea426d99033939001594010c0f21ed64460f7/src/main/k8s/dev/kingdom_gke.cue#L49)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

I just quickly deployed it multiple times and increased it until it stopped crashing
</blockquote></details>

Now that we have monitoring, the way you want to do this is look at the K8s memory used, JVM heap memory used, and JVM heap memory used since last GC. Using those values you can determine the overhead for the container on top of the heap, as well as the min heap value. You can then pick appropriate values, leaving a little headroom.

Example: Over the last 3 hours on dev, container memory appears to cap at ~249Mi. At this time, the JVM heap was at ~44Mi. This means overhead is ~205Mi. The highest used heap after GC value I observed is 30Mi. This appears to be all while max heap was set to 64Mi. If leaving the max heap at this value, the safe value for container memory limit must be above 64 + 205 = 269Mi. Alternatively, keep the container memory limit at 256Mi by reducing the JVM max heap below 51Mi, but no lower than 30Mi. I'd recommend doing that, with 32 + 16 = 48Mi for the heap.

Of course, this all assumes that we're not going to need to process anything bigger than what was observed in the last 3 hours, i.e. that we were able to hit the max batch size. I assume that's not actually true.
___
*[`src/main/k8s/dev/kingdom_gke.cue` line 130 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696#-O3JV6MyCimLppQ90AT9:-O3JV6MyCimLppQ90ATA:b-ijb03t) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a3cba88a3d3f070ed61b893a5bbd749bab494301/src/main/k8s/dev/kingdom_gke.cue#L130)):*
> ```CUE
> 			spec: {
> 				concurrencyPolicy: "Forbid"
> 				schedule:          "*/5 * * * *" // Hourly, 30 minutes past the hour
> ```

I assume this was changed for testing, but the comment does not match the schedule value.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/job/OperationalMetricsExport.kt` line 159 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696#-O3J_hAU7q99mMeS15Fr:-O3J_hAV4o-Uu0QPF_Je:bm4ygj8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a3cba88a3d3f070ed61b893a5bbd749bab494301/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/job/OperationalMetricsExport.kt#L159)):*
> ```Kotlin
>               isDirect = measurement.details.protocolConfig.hasDirect()
>               measurementType = measurementTypeCase.name
>               state = measurement.state.name
> ```

It's not safe to persist types from an API. You must use your own enum and convert to/from the API using `when` statements. Otherwise the already written data will be unreadable if e.g. an API enum is renamed.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/job/OperationalMetricsExport.kt` line 280 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696#-O3JXZ0j66qJoJL34a5j:-O3JXZ0k1eHkVn8cJQNW:b-tkzcii) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a3cba88a3d3f070ed61b893a5bbd749bab494301/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/job/OperationalMetricsExport.kt#L280)):*
> ```Kotlin
>     private val protoSchema: ProtoSchema,
>   ) : DataWriter() {
>     private lateinit var streamWriter: StreamWriter
> ```

Why is this lateinit? I don't see a case where this will ever not be initialized, as it's initialized in the constructor via an init block. Therefore this can just be a regular var.



_Code quote:_
```Kotlin
private lateinit var streamWriter: StreamWriter
```
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/job/OperationalMetricsExport.kt` line 287 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696#-O3JX0H_6__gl_MGAcCN:-O3JX0H_6__gl_MGAcCO:b-q327c3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a3cba88a3d3f070ed61b893a5bbd749bab494301/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/job/OperationalMetricsExport.kt#L287)):*
> ```Kotlin
>     }
> 
>     fun close() {
> ```

This looks like it should be implementing the AutoCloseable interface.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/job/OperationalMetricsExport.kt` line 313 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696#-O3JVkfd5WSvUFeZk-kL:-O3JVkfd5WSvUFeZk-kM:bogsbb2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a3cba88a3d3f070ed61b893a5bbd749bab494301/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/job/OperationalMetricsExport.kt#L313)):*
> ```Kotlin
>      * @throws IllegalStateException if append fails and is no longer retriable
>      */
>     override suspend fun appendRows(protoRows: ProtoRows): Deferred<Unit> {
> ```

nit: functions that return Deferred are named with the suffix "async" by convention
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/job/OperationalMetricsExport.kt` line 315 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696#-O3JWRm_8fwzAIK_x_pK:-O3JWCO358Pl0W_S458H:b-z67nd3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a3cba88a3d3f070ed61b893a5bbd749bab494301/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/job/OperationalMetricsExport.kt#L315)):*
> ```Kotlin
>     override suspend fun appendRows(protoRows: ProtoRows): Deferred<Unit> {
>       return coroutineScope {
>         async {
> ```

Since the `async `is wrapped a `coroutineScope`, I believe it means that the Deferred will be completed before the function returns. That's usually not what you want when returning a Deferred.

Functions that return Deferred tend not to be themselves suspending. They generally are wrapping non-coroutine code (e.g. callbacks), and use CompletableDeferred and/or a background coroutineScope underneath.

This instead appears to be wrapping blocking I/O. This means it should either be a non-suspending function annotated with `@Blocking` or a suspending function that uses a CoroutineContext annotated with `@BlockingExecutor`. The caller can then choose if it wants to run it in a separate coroutine scope.
___
*[`src/main/proto/wfa/measurement/internal/kingdom/operational_metrics.proto` line 17 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696#-O3E5Sr-7opKAqr3O1vW:-O3JZAszBrg9qybl5Zmb:b-j66e6m) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/afeea426d99033939001594010c0f21ed64460f7/src/main/proto/wfa/measurement/internal/kingdom/operational_metrics.proto#L17)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

You changed the Java package but not the proto package.
___
*[`src/main/proto/wfa/measurement/internal/kingdom/operational_metrics.proto` line 34 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696#-O3E9pGg5-p1i9lnQB7W:-O3JZMJeC [...]

2024-08-02 20:55 UTC, tristanvuong2021 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696)* status: 27 of 30 files reviewed, 11 unresolved discussions (waiting on @kungfucraig and @SanjayVas)

___
*[`src/main/k8s/dev/kingdom_gke.cue` line 130 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696#-O3JV6MyCimLppQ90AT9:-O3JrYJN7XU7HjGvtcjH:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a3cba88a3d3f070ed61b893a5bbd749bab494301/src/main/k8s/dev/kingdom_gke.cue#L130)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I assume this was changed for testing, but the comment does not match the schedule value.
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/internal/kingdom/operational_metrics.proto` line 34 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696#-O3E9pGg5-p1i9lnQB7W:-O3JrbLoCSSfrkfIPqRO:by22a2y) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/afeea426d99033939001594010c0f21ed64460f7/src/main/proto/wfa/measurement/internal/kingdom/operational_metrics.proto#L34)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

If that's the case and you need to use ints, then put the unit in the field name. e.g. `create_time_usec`
</blockquote></details>

The proto field name needs to match the BigQuery field name. The BigQuery field is not in microseconds. It looks like a datetime.


<!-- Sent from Reviewable.io -->

2024-08-02 21:55 UTC, tristanvuong2021 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696)* status: 14 of 31 files reviewed, 10 unresolved discussions (waiting on @kungfucraig and @SanjayVas)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696#-O3E832M4l3zcALo20VW:-O3JzI3b0hZOzPQr_8vY:b-896fix) (no related file):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Add DO_NOT_SUBMIT comments for the testing parts so it's clear they are not intended to be submitted/merged.
</blockquote></details>

Done.

___
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/job/OperationalMetricsExport.kt` line 159 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696#-O3J_hAU7q99mMeS15Fr:-O3K-Bqs3NIPtWRDHN0-:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a3cba88a3d3f070ed61b893a5bbd749bab494301/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/job/OperationalMetricsExport.kt#L159)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

It's not safe to persist types from an API. You must use your own enum and convert to/from the API using `when` statements. Otherwise the already written data will be unreadable if e.g. an API enum is renamed.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/job/OperationalMetricsExport.kt` line 280 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696#-O3JXZ0j66qJoJL34a5j:-O3Ju1ED9LxTyGXSwaq9:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a3cba88a3d3f070ed61b893a5bbd749bab494301/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/job/OperationalMetricsExport.kt#L280)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Why is this lateinit? I don't see a case where this will ever not be initialized, as it's initialized in the constructor via an init block. Therefore this can just be a regular var.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/job/OperationalMetricsExport.kt` line 287 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696#-O3JX0H_6__gl_MGAcCN:-O3Juzs82a3fxGy0r2ME:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a3cba88a3d3f070ed61b893a5bbd749bab494301/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/job/OperationalMetricsExport.kt#L287)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This looks like it should be implementing the AutoCloseable interface.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/job/OperationalMetricsExport.kt` line 315 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696#-O3JWRm_8fwzAIK_x_pK:-O3Jz7R_6y5v51LVJv8L:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a3cba88a3d3f070ed61b893a5bbd749bab494301/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/job/OperationalMetricsExport.kt#L315)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Since the `async `is wrapped a `coroutineScope`, I believe it means that the Deferred will be completed before the function returns. That's usually not what you want when returning a Deferred.

Functions that return Deferred tend not to be themselves suspending. They generally are wrapping non-coroutine code (e.g. callbacks), and use CompletableDeferred and/or a background coroutineScope underneath.

This instead appears to be wrapping blocking I/O. This means it should either be a non-suspending function annotated with `@Blocking` or a suspending function that uses a CoroutineContext annotated with `@BlockingExecutor`. The caller can then choose if it wants to run it in a separate coroutine scope.
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/internal/kingdom/operational_metrics.proto` line 17 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696#-O3E5Sr-7opKAqr3O1vW:-O3Jt-a1CApeBS58pnUi:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/afeea426d99033939001594010c0f21ed64460f7/src/main/proto/wfa/measurement/internal/kingdom/operational_metrics.proto#L17)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

You changed the Java package but not the proto package.
</blockquote></details>

Done.
___
*[`src/test/kotlin/org/wfanet/measurement/kingdom/job/OperationalMetricsExportTest.kt` line 103 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696#-O3EDXXw1t5cc_bUbvKr:-O3JzAbrCxMkXb5S8U_3:b-7dkn2i) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/afeea426d99033939001594010c0f21ed64460f7/src/test/kotlin/org/wfanet/measurement/kingdom/job/OperationalMetricsExportTest.kt#L103)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This is mocking part of the subject under test (SUT), making the test invalid. You'd need to mock the BigQueryWriteClient instead.
</blockquote></details>

Still figuring this out because BigQueryWriteClient has final methods.


<!-- Sent from Reviewable.io -->

2024-08-04 01:44 UTC, kungfucraig requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696)* status: 14 of 31 files reviewed, 16 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

___
*[`src/main/terraform/gcloud/modules/kingdom/main.tf` line 107 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696#-O3Q06YLDhQ9ApbDidUj:-O3Q06YLDhQ9ApbDidUk:b-9krayw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a3cba88a3d3f070ed61b893a5bbd749bab494301/src/main/terraform/gcloud/modules/kingdom/main.tf#L107)):*
> ```HCL
>     "type": "TIMESTAMP",
>     "mode": "REQUIRED"
>   }
> ```

Add a column that is "update_time - create_time" (in seconds) and call it something like "completion_duration_seconds"
Add another column with value (update_time-create_time)^2 and call it "completion_duration_seconds_squared"

Together these make it much cheaper to compute averages and standard deviations for completion times. 
___
*[`src/main/terraform/gcloud/modules/kingdom/main.tf` line 141 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696#-O3Q0ylp5tX3STTwBxiK:-O3Q0ylp5tX3STTwBxiL:b-46ity0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a3cba88a3d3f070ed61b893a5bbd749bab494301/src/main/terraform/gcloud/modules/kingdom/main.tf#L141)):*
> ```HCL
>     "mode": "REQUIRED"
>   },
>   {
> ```

Also include the human readable data provider name.
___
*[`src/main/terraform/gcloud/modules/kingdom/main.tf` line 174 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696#-O3Q16EO7jDxz2lgIzXF:-O3Q16EO7jDxz2lgIzXG:bai57zq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a3cba88a3d3f070ed61b893a5bbd749bab494301/src/main/terraform/gcloud/modules/kingdom/main.tf#L174)):*
> ```HCL
>     "mode": "REQUIRED"
>   }
> ]
> ```

Similar to above include the (update_time-create_time) and (update_time-create_time)^2 in seconds.
___
*[`src/main/terraform/gcloud/modules/kingdom/main.tf` line 190 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696#-O3Q1MPG7aoVP9v9-qrL:-O3Q1MPG7aoVP9v9-qrM:b-4xvnv9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a3cba88a3d3f070ed61b893a5bbd749bab494301/src/main/terraform/gcloud/modules/kingdom/main.tf#L190)):*
> ```HCL
>   }
> 
>   schema = <<EOF
> ```

It looks like this table will give us per duchy numbers per state transition, but it's not clear we can compute end to end computation times from it.

Is it possible to encode the succeeded state, say by noting the presence of the measurement result and writing the measurement's update time as the succeeded time?
___
*[`src/main/terraform/gcloud/modules/kingdom/main.tf` line 240 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696#-O3Q1Z3o1Ub6e7IZYJFX:-O3Q1Z3o1Ub6e7IZYJFY:b-17346c) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a3cba88a3d3f070ed61b893a5bbd749bab494301/src/main/terraform/gcloud/modules/kingdom/main.tf#L240)):*
> ```HCL
>     "mode": "REQUIRED"
>   }
> ]
> ```

Same as above include (update_time-create_time) and the square of it in seconds.
___
*[`src/main/terraform/gcloud/modules/kingdom/main.tf` line 245 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696#-O3Q2X-b9VCqi7acoZlH:-O3Q2X-b9VCqi7acoZlI:b-fm2243) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a3cba88a3d3f070ed61b893a5bbd749bab494301/src/main/terraform/gcloud/modules/kingdom/main.tf#L245)):*
> ```HCL
> }
> 
> resource "google_bigquery_table" "latest_measurement_read" {
> ```

What's this for?


<!-- Sent from Reviewable.io -->

2024-08-05 18:29 UTC, SanjayVas requested changes
> Reviewed 1 of 21 files at r2, 10 of 14 files at r6, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696)* status: 27 of 31 files reviewed, 14 unresolved discussions (waiting on @kungfucraig and @tristanvuong2021)

___
*[`imports/java/org/mockito/BUILD.bazel` line 4 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696#-O3YRPmG2EZgLq46v-YV:-O3YRPmH3sdaYT-mMhan:b2qbre4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c6adbaf2f539de2b49b8db73d38c538f752a6bd8/imports/java/org/mockito/BUILD.bazel#L4)):*
This isn't the main artifact for the org.mockito package, so it shouldn't use the default target name for the package.

Note also that this is supposedly included by default in newer versions of Mockito (5.0.0+). From https://javadoc.io/doc/org.mockito/mockito-core/latest/org/mockito/Mockito.html#mockito-inline: 

> Be aware that starting from 5.0.0 the [inline mock maker](https://javadoc.io/static/org.mockito/mockito-core/5.12.0/org/mockito/Mockito.html#39) became the default mock maker and this artifact may be abolished in future versions.

Therefore it may be better to just upgrade our Mockito version.



_Suggestion:_
```Starlark
inline
```
___
*[`src/main/proto/wfa/measurement/internal/kingdom/measurements_service.proto` line 115 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696#-O3YnBCV65XgGgTktgKZ:-O3YnBCV65XgGgTktgK_:b-9v8uga) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c6adbaf2f539de2b49b8db73d38c538f752a6bd8/src/main/proto/wfa/measurement/internal/kingdom/measurements_service.proto#L115)):*
> ```proto
>   Measurement.View measurement_view = 3;
>   // Determines which key to use for order.
>   Measurement.View order_by_measurement_view = 4;
> ```

This doesn't make sense. All of the results from a single call must use the view specified by the `measurement_view` field above. A single call must never have more than one view in the result.
___
*[`src/main/terraform/gcloud/modules/kingdom/main.tf` line 107 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696#-O3Q06YLDhQ9ApbDidUj:-O3YlN5P91B_9Ii-yTSL:b-oxyppk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a3cba88a3d3f070ed61b893a5bbd749bab494301/src/main/terraform/gcloud/modules/kingdom/main.tf#L107)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Add a column that is "update_time - create_time" (in seconds) and call it something like "completion_duration_seconds"
Add another column with value (update_time-create_time)^2 and call it "completion_duration_seconds_squared"

Together these make it much cheaper to compute averages and standard deviations for completion times.
</blockquote></details>

@tristanvuong2021 had these before and removed them when I asked if they were needed since I believe they can be trivially computed as part of the query. (The trivial part here being how easy it is to write a query that computes them, not the cost of said computation).
___
*[`src/main/terraform/gcloud/modules/kingdom/main.tf` line 141 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696#-O3Q0ylp5tX3STTwBxiK:-O3YlzStEkuRYgnKObAr:bswwx8i) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a3cba88a3d3f070ed61b893a5bbd749bab494301/src/main/terraform/gcloud/modules/kingdom/main.tf#L141)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Also include the human readable data provider name.
</blockquote></details>

What happens if the EDP display name changes? Do we need to migrate existing rows, or do we just start writing the new name on new rows?
___
*[`src/main/terraform/gcloud/modules/kingdom/main.tf` line 245 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696#-O3Q2X-b9VCqi7acoZlH:-O3YmXQk0wdR4mW5b8ld:b-apxakb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a3cba88a3d3f070ed61b893a5bbd749bab494301/src/main/terraform/gcloud/modules/kingdom/main.tf#L245)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

What's this for?
</blockquote></details>

I presume it's to avoid having to read the entire history every time, and instead just read anything that's been updated since the given timestamp.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/job/OperationalMetricsExport.kt` line 425 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696#-O3YjFw974qDPmy9cv9F:-O3YjFwA46u1EDG7D45H:b8r8mkr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c6adbaf2f539de2b49b8db73d38c538f752a6bd8/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/job/OperationalMetricsExport.kt#L425)):*
> ```Kotlin
>      * @throws IllegalStateException if append fails and is no longer retriable
>      */
>     fun asyncAppendRows(scope: CoroutineScope, protoRows: ProtoRows): Deferred<Unit> {
> ```

Don't take in a CoroutineScope.

There are three options here, in order of preference:

1. If this doesn't call any suspending functions, just have it be non-coroutine code and annotate the function with `@Blocking`. This signals to calling coroutine code to use a CoroutineContext that has a suitable dispatcher.
2. Just have this be a suspending function rather than returning Deferred. If the caller wants to create a separate coroutine for is (e.g. using async or launch), they can choose to do so.
3. Have this class manage the coroutine scope

Note that for options 2 or 3, there should be an optional CoroutineContext passed in the constructor annotated with `@BlockingExecutor`. That context needs to be used for any blocking calls. This can be defaulted to `Dispatchers.IO`.



_Code quote:_
```Kotlin
scope: CoroutineScope,
```


<!-- Sent from Reviewable.io -->

2024-08-05 20:21 UTC, tristanvuong2021 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696)* status: 27 of 31 files reviewed, 14 unresolved discussions (waiting on @kungfucraig and @SanjayVas)

___
*[`imports/java/org/mockito/BUILD.bazel` line 4 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696#-O3YRPmG2EZgLq46v-YV:-O3ZBnre8ebYcj-KKZ4G:bbl3k93) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c6adbaf2f539de2b49b8db73d38c538f752a6bd8/imports/java/org/mockito/BUILD.bazel#L4)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This isn't the main artifact for the org.mockito package, so it shouldn't use the default target name for the package.

Note also that this is supposedly included by default in newer versions of Mockito (5.0.0+). From https://javadoc.io/doc/org.mockito/mockito-core/latest/org/mockito/Mockito.html#mockito-inline: 

> Be aware that starting from 5.0.0 the [inline mock maker](https://javadoc.io/static/org.mockito/mockito-core/5.12.0/org/mockito/Mockito.html#39) became the default mock maker and this artifact may be abolished in future versions.

Therefore it may be better to just upgrade our Mockito version.
</blockquote></details>

mockito 5 requires kotlin to generate java 11 bytecode. right now, we generate java 8.
___
*[`src/main/proto/wfa/measurement/internal/kingdom/measurements_service.proto` line 115 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696#-O3YnBCV65XgGgTktgKZ:-O3ZBvpp9gOKASoQMwGT:bfcro9x) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c6adbaf2f539de2b49b8db73d38c538f752a6bd8/src/main/proto/wfa/measurement/internal/kingdom/measurements_service.proto#L115)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This doesn't make sense. All of the results from a single call must use the view specified by the `measurement_view` field above. A single call must never have more than one view in the result.
</blockquote></details>

Each measurement in the result still has the same view. What changes is the order of the results.


<!-- Sent from Reviewable.io -->

2024-08-05 21:27 UTC, SanjayVas requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696)* status: 27 of 31 files reviewed, 12 unresolved discussions (waiting on @kungfucraig and @tristanvuong2021)

___
*[`imports/java/org/mockito/BUILD.bazel` line 4 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696#-O3YRPmG2EZgLq46v-YV:-O3ZP7tC4X9N0QQaXKcW:bonk2m) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c6adbaf2f539de2b49b8db73d38c538f752a6bd8/imports/java/org/mockito/BUILD.bazel#L4)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

mockito 5 requires kotlin to generate java 11 bytecode. right now, we generate java 8.
</blockquote></details>

We actually generate Java 9 and run on Java 17 at the moment. See .bazelrc.

I have no problems switching to targeting Java 11. I'd recommend a separate prefactoring PR for updating Mockito and switching to Java 11.
___
*[`src/main/proto/wfa/measurement/internal/kingdom/measurements_service.proto` line 115 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696#-O3YnBCV65XgGgTktgKZ:-O3ZORHi1FXduhUUSeSj:b-k0f2ev) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c6adbaf2f539de2b49b8db73d38c538f752a6bd8/src/main/proto/wfa/measurement/internal/kingdom/measurements_service.proto#L115)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Each measurement in the result still has the same view. What changes is the order of the results.
</blockquote></details>

**All** measurements from a single call to StreamMeasurements must have the same view. If that's not the case currently, it's a bug.

Given the above, there's no sense in ordering by view since there will only be one.


<!-- Sent from Reviewable.io -->

2024-08-05 22:02 UTC, kungfucraig requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696)* status: 27 of 31 files reviewed, 11 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

___
*[`src/main/terraform/gcloud/modules/kingdom/main.tf` line 107 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696#-O3Q06YLDhQ9ApbDidUj:-O3ZYTs-6L7RWikwLMYM:b27gujh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a3cba88a3d3f070ed61b893a5bbd749bab494301/src/main/terraform/gcloud/modules/kingdom/main.tf#L107)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

@tristanvuong2021 had these before and removed them when I asked if they were needed since I believe they can be trivially computed as part of the query. (The trivial part here being how easy it is to write a query that computes them, not the cost of said computation).
</blockquote></details>

We discussed offline. They are here for a time optimization not a code optimization. 
___
*[`src/main/terraform/gcloud/modules/kingdom/main.tf` line 141 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696#-O3Q0ylp5tX3STTwBxiK:-O3ZYeBv9D6Yrn6jbbsC:b-x9hvo3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a3cba88a3d3f070ed61b893a5bbd749bab494301/src/main/terraform/gcloud/modules/kingdom/main.tf#L141)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

What happens if the EDP display name changes? Do we need to migrate existing rows, or do we just start writing the new name on new rows?
</blockquote></details>

I think the latter and the dashboard owner will have to deal with it.  Also, I think we could write the dashboard queries to aggregate on the IDs and pick the display name from a more recent row.

Do we think the names will change in practice?


<!-- Sent from Reviewable.io -->

2024-08-05 22:07 UTC, SanjayVas reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696)* status: 27 of 31 files reviewed, 11 unresolved discussions (waiting on @kungfucraig and @tristanvuong2021)

___
*[`src/main/terraform/gcloud/modules/kingdom/main.tf` line 141 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696#-O3Q0ylp5tX3STTwBxiK:-O3Z_4O_0AtO7wU0OXfu:b-6kt4ye) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a3cba88a3d3f070ed61b893a5bbd749bab494301/src/main/terraform/gcloud/modules/kingdom/main.tf#L141)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

I think the latter and the dashboard owner will have to deal with it.  Also, I think we could write the dashboard queries to aggregate on the IDs and pick the display name from a more recent row.

Do we think the names will change in practice?
</blockquote></details>

In the short term, impossible (we never got around to adding an update method to the public API :P ). Long term? I'm guessing infrequently, except perhaps early in the lifecycle since people tend to make mistakes when first registering things.


<!-- Sent from Reviewable.io -->

2024-08-05 22:41 UTC, kungfucraig requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696)* status: 27 of 31 files reviewed, 11 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

___
*[`src/main/terraform/gcloud/modules/kingdom/main.tf` line 141 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696#-O3Q0ylp5tX3STTwBxiK:-O3ZgcwPBTkuJBXsIfTA:b-xva9pp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a3cba88a3d3f070ed61b893a5bbd749bab494301/src/main/terraform/gcloud/modules/kingdom/main.tf#L141)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

In the short term, impossible (we never got around to adding an update method to the public API :P ). Long term? I'm guessing infrequently, except perhaps early in the lifecycle since people tend to make mistakes when first registering things.
</blockquote></details>

Sounds like we're good including the field and accepting whatever churn may occur.


<!-- Sent from Reviewable.io -->

2024-08-09 22:14 UTC, tristanvuong2021 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696)* status: 15 of 33 files reviewed, 11 unresolved discussions (waiting on @kungfucraig and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/internal/kingdom/measurements_service.proto` line 115 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696#-O3YnBCV65XgGgTktgKZ:-O3tBUSg4KY1UtR0wJPf:b20eiig) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c6adbaf2f539de2b49b8db73d38c538f752a6bd8/src/main/proto/wfa/measurement/internal/kingdom/measurements_service.proto#L115)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

**All** measurements from a single call to StreamMeasurements must have the same view. If that's not the case currently, it's a bug.

Given the above, there's no sense in ordering by view since there will only be one.
</blockquote></details>

I renamed it to clarify what it does.
___
*[`src/main/terraform/gcloud/modules/kingdom/main.tf` line 107 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696#-O3Q06YLDhQ9ApbDidUj:-O3tBYv48a5cOMzrx_rl:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a3cba88a3d3f070ed61b893a5bbd749bab494301/src/main/terraform/gcloud/modules/kingdom/main.tf#L107)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

We discussed offline. They are here for a time optimization not a code optimization.
</blockquote></details>

Done.
___
*[`src/main/terraform/gcloud/modules/kingdom/main.tf` line 141 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696#-O3Q0ylp5tX3STTwBxiK:-O3tBJ35AX-gYAPG6jw3:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a3cba88a3d3f070ed61b893a5bbd749bab494301/src/main/terraform/gcloud/modules/kingdom/main.tf#L141)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Sounds like we're good including the field and accepting whatever churn may occur.
</blockquote></details>

Done.
___
*[`src/main/terraform/gcloud/modules/kingdom/main.tf` line 174 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696#-O3Q16EO7jDxz2lgIzXF:-O3tBJld1_1hfu9mCiOd:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a3cba88a3d3f070ed61b893a5bbd749bab494301/src/main/terraform/gcloud/modules/kingdom/main.tf#L174)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Similar to above include the (update_time-create_time) and (update_time-create_time)^2 in seconds.
</blockquote></details>

Done.
___
*[`src/main/terraform/gcloud/modules/kingdom/main.tf` line 240 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696#-O3Q1Z3o1Ub6e7IZYJFX:-O3tBPA710D2ALJMuCiW:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a3cba88a3d3f070ed61b893a5bbd749bab494301/src/main/terraform/gcloud/modules/kingdom/main.tf#L240)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Same as above include (update_time-create_time) and the square of it in seconds.
</blockquote></details>

Done.
___
*[`imports/java/org/mockito/BUILD.bazel` line 4 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696#-O3YRPmG2EZgLq46v-YV:-O3tBS2A9vS3c-KRcYzn:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c6adbaf2f539de2b49b8db73d38c538f752a6bd8/imports/java/org/mockito/BUILD.bazel#L4)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

We actually generate Java 9 and run on Java 17 at the moment. See .bazelrc.

I have no problems switching to targeting Java 11. I'd recommend a separate prefactoring PR for updating Mockito and switching to Java 11.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/job/OperationalMetricsExport.kt` line 425 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696#-O3YjFw974qDPmy9cv9F:-O3tBTdC3B5NSPWvLz1j:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c6adbaf2f539de2b49b8db73d38c538f752a6bd8/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/job/OperationalMetricsExport.kt#L425)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Don't take in a CoroutineScope.

There are three options here, in order of preference:

1. If this doesn't call any suspending functions, just have it be non-coroutine code and annotate the function with `@Blocking`. This signals to calling coroutine code to use a CoroutineContext that has a suitable dispatcher.
2. Just have this be a suspending function rather than returning Deferred. If the caller wants to create a separate coroutine for is (e.g. using async or launch), they can choose to do so.
3. Have this class manage the coroutine scope

Note that for options 2 or 3, there should be an optional CoroutineContext passed in the constructor annotated with `@BlockingExecutor`. That context needs to be used for any blocking calls. This can be defaulted to `Dispatchers.IO`.
</blockquote></details>

Done.
___
*[`src/test/kotlin/org/wfanet/measurement/kingdom/job/OperationalMetricsExportTest.kt` line 103 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696#-O3EDXXw1t5cc_bUbvKr:-O3tBaFo-nosBQ72Unaf:bxy18u6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/afeea426d99033939001594010c0f21ed64460f7/src/test/kotlin/org/wfanet/measurement/kingdom/job/OperationalMetricsExportTest.kt#L103)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Still figuring this out because BigQueryWriteClient has final methods.
</blockquote></details>

I ended up having to mock StreamWriter. Mocking BigQueryWriteClient doesn't help because StreamWriter just uses the passed-in client to read its settings and test that the connection works. Appending uses a client created by an underlying ConnectionWorker.


<!-- Sent from Reviewable.io -->

2024-08-10 01:14 UTC, tristanvuong2021 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696)* status: 15 of 33 files reviewed, 11 unresolved discussions (waiting on @kungfucraig and @SanjayVas)

___
*[`src/test/kotlin/org/wfanet/measurement/kingdom/job/OperationalMetricsExportTest.kt` line 103 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696#-O3EDXXw1t5cc_bUbvKr:-O3tqMIf7pi5N59VKfYC:ba4bwem) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/afeea426d99033939001594010c0f21ed64460f7/src/test/kotlin/org/wfanet/measurement/kingdom/job/OperationalMetricsExportTest.kt#L103)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

I ended up having to mock StreamWriter. Mocking BigQueryWriteClient doesn't help because StreamWriter just uses the passed-in client to read its settings and test that the connection works. Appending uses a client created by an underlying ConnectionWorker.
</blockquote></details>

Actually, had to add back in BigQueryWriteClient mock to pass tests on GitHub.


<!-- Sent from Reviewable.io -->

2024-08-12 18:05 UTC, SanjayVas requested changes
> Reviewed 4 of 18 files at r8, 1 of 6 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696)* status: 20 of 33 files reviewed, 15 unresolved discussions (waiting on @kungfucraig and @tristanvuong2021)

___
*[`.bazelrc` line 15 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696#-O46_7MuEei6YsYtQWsR:-O46_7MuEei6YsYtQWsS:b-s7yvhs) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a3510b9af23ad531bbf04e3450cfe4bdddb17be4/.bazelrc#L15)):*
> ```
> build --java_runtime_version=remotejdk_17
> 
> # Target Java 11.
> ```

This should be done in a separate prefactoring PR.
___
*[`src/main/k8s/dev/kingdom_gke.cue` line 126 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696#-O46_Fzd0-_cjUISp_s5:-O46_Fzd0-_cjUISp_s6:bx1nmee) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a3510b9af23ad531bbf04e3450cfe4bdddb17be4/src/main/k8s/dev/kingdom_gke.cue#L126)):*
> ```CUE
> 					"--internal-api-target=" + (#Target & {name: "gcp-kingdom-data-server"}).target,
> 					"--internal-api-cert-host=localhost",
> 					"--internal-api-default-deadline=60s",
> ```

You shouldn't need to increase this. If you do, it implies something else is wrong.
___
*[`src/main/proto/wfa/measurement/internal/kingdom/measurements_service.proto` line 115 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696#-O3YnBCV65XgGgTktgKZ:-O46aOPe-OfnbmXY81ej:bw3wofc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c6adbaf2f539de2b49b8db73d38c538f752a6bd8/src/main/proto/wfa/measurement/internal/kingdom/measurements_service.proto#L115)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

I renamed it to clarify what it does.
</blockquote></details>

This is still not clear from the API definition. In what way is the ordering different if the caller passes MEASUREMENT vs. passing COMPUTATION?

Right now the API definition isn't super clear on what the ordering is, but you can guess it by the way the `after` filter is written. The `after` filter must always operate as documented regardless of any other field that modifies the order. Since `update_time` is part of that filter, this means that `update_time` **must** be part of the ordering. It also states that the `measurement` field is used for the DEFAULT view and that the `computation` field is used for the COMPUTATION view.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/job/OperationalMetricsExport.kt` line 85 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696#-O46dFVN-V4clg4414_T:-O46dFVO-UM--bg0ELwr:b-2xyyw3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a3510b9af23ad531bbf04e3450cfe4bdddb17be4/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/job/OperationalMetricsExport.kt#L85)):*
> ```Kotlin
>   private val requisitionsTableId: String,
>   private val computationParticipantsTableId: String,
>   private val createStreamWriterFunc:
> ```

If you're going to do it this way, the default implementation should be public and defined outside of this class. You may want to define this as a `StreamWriterFactory` [functional interface](https://kotlinlang.org/docs/fun-interfaces.html), where you can have a `StreamWriterFactoryImpl` as the default implementation.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/job/OperationalMetricsExport.kt` line 193 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696#-O46hyovBGTYyh88aEkD:-O46hyovBGTYyh88aEkE:breoy7c) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a3510b9af23ad531bbf04e3450cfe4bdddb17be4/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/job/OperationalMetricsExport.kt#L193)):*
> ```Kotlin
> 
>     // Map of externalDataProviderId to DataProvider
>     val dataProvidersMap: HashMap<Long, DataProvider> = hashMapOf()
> ```

Does this specifically need to be a HashMap (as opposed to using mutableMapOf())? If so, does the HashMap interface need to be exposed (as opposed to having the variable type be `MutableMap`)?



_Suggestion:_
```Kotlin
val dataProvidersByExternalId: MutableMap<Long, DataProvider> = mutableMapOf()
```
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/job/OperationalMetricsExport.kt` line 462 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696#-O46kkBJC3ztqLXsGNX2:-O46kkBJC3ztqLXsGNX3:b8khzw7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a3510b9af23ad531bbf04e3450cfe4bdddb17be4/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/job/OperationalMetricsExport.kt#L462)):*
> ```Kotlin
>       val tableName = TableName.of(projectId, datasetId, tableId)
>       return StreamWriter.newBuilder(tableName.toString() + DEFAULT_STREAM_PATH, client)
>         .setExecutorProvider(FixedExecutorProvider.create(Executors.newScheduledThreadPool(1)))
> ```

This should come from a flag. See `--spanner-transaction-max-threads` for an example.


<!-- Sent from Reviewable.io -->

2024-08-13 01:55 UTC, tristanvuong2021 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696)* status: 19 of 34 files reviewed, 15 unresolved discussions (waiting on @kungfucraig and @SanjayVas)

___
*[`.bazelrc` line 15 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696#-O46_7MuEei6YsYtQWsR:-O4854uw4xsSPTTJRxCJ:b-b1g9rf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a3510b9af23ad531bbf04e3450cfe4bdddb17be4/.bazelrc#L15)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This should be done in a separate prefactoring PR.
</blockquote></details>

In progress now.
___
*[`src/main/k8s/dev/kingdom_gke.cue` line 126 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696#-O46_Fzd0-_cjUISp_s5:-O48RAtp6Gp9npGFEWIO:b-jgg5hq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a3510b9af23ad531bbf04e3450cfe4bdddb17be4/src/main/k8s/dev/kingdom_gke.cue#L126)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

You shouldn't need to increase this. If you do, it implies something else is wrong.
</blockquote></details>

I will have to come up with a new index then.
___
*[`src/main/proto/wfa/measurement/internal/kingdom/measurements_service.proto` line 115 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696#-O3YnBCV65XgGgTktgKZ:-O48RNDy6wlabgxwAWsA:boc58h9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c6adbaf2f539de2b49b8db73d38c538f752a6bd8/src/main/proto/wfa/measurement/internal/kingdom/measurements_service.proto#L115)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This is still not clear from the API definition. In what way is the ordering different if the caller passes MEASUREMENT vs. passing COMPUTATION?

Right now the API definition isn't super clear on what the ordering is, but you can guess it by the way the `after` filter is written. The `after` filter must always operate as documented regardless of any other field that modifies the order. Since `update_time` is part of that filter, this means that `update_time` **must** be part of the ordering. It also states that the `measurement` field is used for the DEFAULT view and that the `computation` field is used for the COMPUTATION view.
</blockquote></details>

Updated the documentation again.
___
*[`src/main/terraform/gcloud/modules/kingdom/main.tf` line 141 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696#-O3Q0ylp5tX3STTwBxiK:-O47oHK29_sAf1Oeov5x:bbwyzad) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a3cba88a3d3f070ed61b893a5bbd749bab494301/src/main/terraform/gcloud/modules/kingdom/main.tf#L141)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I added it, but it turns out the Data provider display name doesn't exist internally.
___
*[`src/main/terraform/gcloud/modules/kingdom/main.tf` line 190 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696#-O3Q1MPG7aoVP9v9-qrL:-O485Bzq4qCiGSTBkcn4:bi92xix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a3cba88a3d3f070ed61b893a5bbd749bab494301/src/main/terraform/gcloud/modules/kingdom/main.tf#L190)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

It looks like this table will give us per duchy numbers per state transition, but it's not clear we can compute end to end computation times from it.

Is it possible to encode the succeeded state, say by noting the presence of the measurement result and writing the measurement's update time as the succeeded time?
</blockquote></details>

If that time is necessary, that is already in the measurements table. I realized that I am unsure about the purpose of this table. I understand measurements and requisitions, but not this.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/job/OperationalMetricsExport.kt` line 85 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696#-O46dFVN-V4clg4414_T:-O4702Yw71zZJEaMwo4p:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a3510b9af23ad531bbf04e3450cfe4bdddb17be4/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/job/OperationalMetricsExport.kt#L85)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

If you're going to do it this way, the default implementation should be public and defined outside of this class. You may want to define this as a `StreamWriterFactory` [functional interface](https://kotlinlang.org/docs/fun-interfaces.html), where you can have a `StreamWriterFactoryImpl` as the default implementation.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/job/OperationalMetricsExport.kt` line 193 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696#-O46hyovBGTYyh88aEkD:-O46pVI42Zl9WoHHbn9_:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a3510b9af23ad531bbf04e3450cfe4bdddb17be4/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/job/OperationalMetricsExport.kt#L193)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Does this specifically need to be a HashMap (as opposed to using mutableMapOf())? If so, does the HashMap interface need to be exposed (as opposed to having the variable type be `MutableMap`)?
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/job/OperationalMetricsExport.kt` line 462 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696#-O46kkBJC3ztqLXsGNX2:-O46pVr931qE8bi3ZoM8:b-9eupld) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a3510b9af23ad531bbf04e3450cfe4bdddb17be4/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/job/OperationalMetricsExport.kt#L462)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This should come from a flag. See `--spanner-transaction-max-threads` for an example.
</blockquote></details>

I am only writing to the stream one batch at a time so I don't need more than 1 thread.


<!-- Sent from Reviewable.io -->

2024-08-13 17:13 UTC, tristanvuong2021 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696)* status: 18 of 34 files reviewed, 15 unresolved discussions (waiting on @kungfucraig and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/internal/kingdom/measurements_service.proto` line 115 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696#-O3YnBCV65XgGgTktgKZ:-O4BieWx7-bGg7RDZz-z:b7fi1oo) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c6adbaf2f539de2b49b8db73d38c538f752a6bd8/src/main/proto/wfa/measurement/internal/kingdom/measurements_service.proto#L115)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Updated the documentation again.
</blockquote></details>

I came up with a new solution that involves modifying ComputationKey.


<!-- Sent from Reviewable.io -->

2024-08-13 18:13 UTC, SanjayVas requested changes
> Reviewed 2 of 6 files at r9, 5 of 10 files at r10, 5 of 9 files at r11, 5 of 5 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696)* status: all files reviewed, 11 unresolved discussions (waiting on @kungfucraig and @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/internal/kingdom/measurements_service.proto` line 115 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696#-O3YnBCV65XgGgTktgKZ:-O4Bt2AS2KM3MyLdyr-3:bgrxdkx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c6adbaf2f539de2b49b8db73d38c538f752a6bd8/src/main/proto/wfa/measurement/internal/kingdom/measurements_service.proto#L115)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

I came up with a new solution that involves modifying ComputationKey.
</blockquote></details>

I'm still not understanding why you need to change anything here. Measurements with a computation ID are uniquely keyed by that computation ID, so adding any other field to ComputationKey doesn't make sense. Note that the COMPUTATION view is mainly intended for calls from the Duchy via the system API, where the Duchy doesn't get to know the MC ID and Measurement ID. Therefore the "after" key cannot contain those fields.

I see two options:

1. Read all Measurements using MEASUREMENT view and persist that last read item key. Do a separate batch read for the COMPUTATION view for any Measurement that has a computation ID.
2. Do two separate reads: one for Measurements without a computation ID using MEASUREMENT view and one for Measurements with a computation ID using COMPUTATION view. Persist two different last read item keys. Note that you may need to update the filter if there's no already a way to filter based on the presence of a computation ID.

(2) is more efficient. I think either option requires some change to the internal API.
___
*[`src/main/terraform/gcloud/modules/kingdom/main.tf` line 141 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696#-O3Q0ylp5tX3STTwBxiK:-O4BtJtJA72OK63Rdywk:b-77qgmo) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a3cba88a3d3f070ed61b893a5bbd749bab494301/src/main/terraform/gcloud/modules/kingdom/main.tf#L141)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

I added it, but it turns out the Data provider display name doesn't exist internally.
</blockquote></details>

Ah, yes. #1048 has not yet been fixed.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/job/OperationalMetricsExport.kt` line 425 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696#-O3YjFw974qDPmy9cv9F:-O4BlkjI6-IcFrfCFsCl:be5y6em) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c6adbaf2f539de2b49b8db73d38c538f752a6bd8/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/job/OperationalMetricsExport.kt#L425)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

This is still taking in a scope and returning a Deferred, meaning it's using none of the options mentioned above. Note that if you go with any option other than (1), you need to justify it.


<!-- Sent from Reviewable.io -->

2024-08-13 18:34 UTC, tristanvuong2021 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696)* status: all files reviewed, 11 unresolved discussions (waiting on @kungfucraig and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/internal/kingdom/measurements_service.proto` line 115 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696#-O3YnBCV65XgGgTktgKZ:-O4C0-dR85SWb-h6l2OS:b-5npt8s) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c6adbaf2f539de2b49b8db73d38c538f752a6bd8/src/main/proto/wfa/measurement/internal/kingdom/measurements_service.proto#L115)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I'm still not understanding why you need to change anything here. Measurements with a computation ID are uniquely keyed by that computation ID, so adding any other field to ComputationKey doesn't make sense. Note that the COMPUTATION view is mainly intended for calls from the Duchy via the system API, where the Duchy doesn't get to know the MC ID and Measurement ID. Therefore the "after" key cannot contain those fields.

I see two options:

1. Read all Measurements using MEASUREMENT view and persist that last read item key. Do a separate batch read for the COMPUTATION view for any Measurement that has a computation ID.
2. Do two separate reads: one for Measurements without a computation ID using MEASUREMENT view and one for Measurements with a computation ID using COMPUTATION view. Persist two different last read item keys. Note that you may need to update the filter if there's no already a way to filter based on the presence of a computation ID.

(2) is more efficient. I think either option requires some change to the internal API.
</blockquote></details>

In this case, I will have to add an index then. We currently only have an index that covers UpdateTime, ExternalComputationId, but not UpdateTime, ExternalMeasurementConsumerId, ExternalMeasurementId
___
*[`src/main/terraform/gcloud/modules/kingdom/main.tf` line 141 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696#-O3Q0ylp5tX3STTwBxiK:-O4C-snWCH5CfQdRG5ET:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a3cba88a3d3f070ed61b893a5bbd749bab494301/src/main/terraform/gcloud/modules/kingdom/main.tf#L141)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Ah, yes. #1048 has not yet been fixed.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-08-13 18:47 UTC, SanjayVas requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696)* status: all files reviewed, 11 unresolved discussions (waiting on @kungfucraig and @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/internal/kingdom/measurements_service.proto` line 115 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696#-O3YnBCV65XgGgTktgKZ:-O4C2HIX6H2P_yhsUfMV:b-iq2o6i) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c6adbaf2f539de2b49b8db73d38c538f752a6bd8/src/main/proto/wfa/measurement/internal/kingdom/measurements_service.proto#L115)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

In this case, I will have to add an index then. We currently only have an index that covers UpdateTime, ExternalComputationId, but not UpdateTime, ExternalMeasurementConsumerId, ExternalMeasurementId
</blockquote></details>

If it's too inefficient without the index, then that should already be the case already for paginated calls with the MEASUREMENT view. In case it wasn't clear, the COMPUTATION view is never valid for Measurements without a computation ID. It would be correct for the internal API to throw an error if you try to use that view for non-MPC Measurements.


<!-- Sent from Reviewable.io -->

2024-08-13 23:35 UTC, tristanvuong2021 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696)* status: all files reviewed, 11 unresolved discussions (waiting on @kungfucraig and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/internal/kingdom/measurements_service.proto` line 115 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696#-O3YnBCV65XgGgTktgKZ:-O4C5D6N6iAXE0EGhAqP:b-f9hl6y) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c6adbaf2f539de2b49b8db73d38c538f752a6bd8/src/main/proto/wfa/measurement/internal/kingdom/measurements_service.proto#L115)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

If it's too inefficient without the index, then that should already be the case already for paginated calls with the MEASUREMENT view. In case it wasn't clear, the COMPUTATION view is never valid for Measurements without a computation ID. It would be correct for the internal API to throw an error if you try to use that view for non-MPC Measurements.
</blockquote></details>

I realized that default view doesn't include Requisitions. For two separate calls to work, I need to update default view to include Requisitions.


<!-- Sent from Reviewable.io -->

2024-08-13 23:36 UTC, tristanvuong2021 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696)* status: all files reviewed, 11 unresolved discussions (waiting on @kungfucraig and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/internal/kingdom/measurements_service.proto` line 115 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696#-O3YnBCV65XgGgTktgKZ:-O4D5Knd1yz2pCKtyHZB:b-l0taq4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c6adbaf2f539de2b49b8db73d38c538f752a6bd8/src/main/proto/wfa/measurement/internal/kingdom/measurements_service.proto#L115)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

I realized that default view doesn't include Requisitions. For two separate calls to work, I need to update default view to include Requisitions.
</blockquote></details>

Or I could do StreamMeasurements twice and StreamRequisitions.


<!-- Sent from Reviewable.io -->

2024-08-13 23:41 UTC, tristanvuong2021 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696)* status: all files reviewed, 11 unresolved discussions (waiting on @kungfucraig and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/internal/kingdom/measurements_service.proto` line 115 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696#-O3YnBCV65XgGgTktgKZ:-O4D6H1JD9S4AJ-cB23s:b-vrht4k) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c6adbaf2f539de2b49b8db73d38c538f752a6bd8/src/main/proto/wfa/measurement/internal/kingdom/measurements_service.proto#L115)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Or I could do StreamMeasurements twice and StreamRequisitions.
</blockquote></details>

Nevermind, StreamRequisitions is optimized for Data Providers and can't be used in its current state for this.


<!-- Sent from Reviewable.io -->

2024-08-13 23:43 UTC, tristanvuong2021 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696)* status: all files reviewed, 11 unresolved discussions (waiting on @kungfucraig and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/internal/kingdom/measurements_service.proto` line 115 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696#-O3YnBCV65XgGgTktgKZ:-O4D6sKCDKS6TBZZLk8i:b-yk3njw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c6adbaf2f539de2b49b8db73d38c538f752a6bd8/src/main/proto/wfa/measurement/internal/kingdom/measurements_service.proto#L115)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Nevermind, StreamRequisitions is optimized for Data Providers and can't be used in its current state for this.
</blockquote></details>

I will make a new requisitions method for this.


<!-- Sent from Reviewable.io -->

2024-08-14 18:57 UTC, SanjayVas requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696)* status: all files reviewed, 11 unresolved discussions (waiting on @kungfucraig and @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/internal/kingdom/measurements_service.proto` line 115 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696#-O3YnBCV65XgGgTktgKZ:-O4HE8UV7VXR6jWPHIMT:b601v3o) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c6adbaf2f539de2b49b8db73d38c538f752a6bd8/src/main/proto/wfa/measurement/internal/kingdom/measurements_service.proto#L115)):*
> I realized that default view doesn't include Requisitions. For two separate calls to work, I need to update default view to include Requisitions.

Don't do this.

> Or I could do StreamMeasurements twice and StreamRequisitions.

Yes.

> Nevermind, StreamRequisitions is optimized for Data Providers and can't be used in its current state for this.
> I will make a new requisitions method for this.

Can you give more detail about this? It looks like what you need is to get Requisitions for each Measurement. The way the method is currently written, this means a separate call for each Measurement. I would assume that extracting a MeasurementKey message and repeating that in StreamRequisitionsRequest.Filter would be sufficient to make it so that you could get Requisitions for multiple Measurements at once.


<!-- Sent from Reviewable.io -->

2024-08-14 18:59 UTC, SanjayVas requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696)* status: all files reviewed, 11 unresolved discussions (waiting on @kungfucraig and @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/internal/kingdom/measurements_service.proto` line 115 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696#-O3YnBCV65XgGgTktgKZ:-O4HFPG0CtKDFyJl0kOL:b7mvz3b) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c6adbaf2f539de2b49b8db73d38c538f752a6bd8/src/main/proto/wfa/measurement/internal/kingdom/measurements_service.proto#L115)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> I realized that default view doesn't include Requisitions. For two separate calls to work, I need to update default view to include Requisitions.

Don't do this.

> Or I could do StreamMeasurements twice and StreamRequisitions.

Yes.

> Nevermind, StreamRequisitions is optimized for Data Providers and can't be used in its current state for this.
> I will make a new requisitions method for this.

Can you give more detail about this? It looks like what you need is to get Requisitions for each Measurement. The way the method is currently written, this means a separate call for each Measurement. I would assume that extracting a MeasurementKey message and repeating that in StreamRequisitionsRequest.Filter would be sufficient to make it so that you could get Requisitions for multiple Measurements at once.
</blockquote></details>

Alternatively, you can add another view that also includes Requisitions.


<!-- Sent from Reviewable.io -->

2024-08-16 18:11 UTC, SanjayVas reviewed
> Reviewed 14 of 14 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696)* status: all files reviewed, 8 unresolved discussions (waiting on @kungfucraig and @tristanvuong2021)

___
*[`src/main/k8s/dev/kingdom_gke.cue` line 49 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696#-O3E8ezx9NysknblEE4r:-O4RNQ4q0XLINvQJ7iuR:bhlt7rz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/afeea426d99033939001594010c0f21ed64460f7/src/main/k8s/dev/kingdom_gke.cue#L49)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

I changed it to almost the minimum. 224Mi memory causes OOMkilled, but 232Mi is fine.
</blockquote></details>

By my previous math, you probably want 256Mi if you're doing 48Mi heap. The idea is that if this starts consuming too much memory, we want a heap size error from the JVM rather than an OOMKilled from K8s.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurements.kt` line 158 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696#-O4RN-Gd4g_NY6DwoLBd:-O4RN-Gd4g_NY6DwoLBe:b7me82t) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/23675f7d808e475f806be53501b9a40ab3009dcd/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurements.kt#L158)):*
> ```Kotlin
>             conjuncts.add(
>               """
>               CASE
> ```

nit: maybe leave a comment about how this is more efficient due to lack of short-circuiting behavior for boolean operations?
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/job/OperationalMetricsExport.kt` line 460 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696#-O4RMmrNBuF23tm7eDid:-O4RMmrNBuF23tm7eDie:b4tefni) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/23675f7d808e475f806be53501b9a40ab3009dcd/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/job/OperationalMetricsExport.kt#L460)):*
> ```Kotlin
>      *
>      * @param protoRows protos representing the rows to write.
>      * @returns Unit
> ```

nit: don't need an `@return` for Unit


<!-- Sent from Reviewable.io -->

2024-08-19 20:39 UTC, stevenwarejones approved these changes
> Reviewed 1 of 22 files at r1, 4 of 21 files at r2, 5 of 16 files at r4, 1 of 4 files at r5, 2 of 14 files at r6, 1 of 18 files at r8, 1 of 6 files at r9, 5 of 10 files at r10, 2 of 5 files at r12, 11 of 14 files at r13, 3 of 3 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696)* status: all files reviewed, 6 unresolved discussions (waiting on @kungfucraig and @SanjayVas)



<!-- Sent from Reviewable.io -->

2024-08-21 15:36 UTC, tristanvuong2021 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696)* status: 29 of 36 files reviewed, 6 unresolved discussions (waiting on @kungfucraig, @SanjayVas, and @stevenwarejones)

___
*[`.bazelrc` line 15 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696#-O46_7MuEei6YsYtQWsR:-O4p_EL39NENb8msWDEu:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a3510b9af23ad531bbf04e3450cfe4bdddb17be4/.bazelrc#L15)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

In progress now.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-08-23 00:11 UTC, tristanvuong2021 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696)* status: 23 of 36 files reviewed, 6 unresolved discussions (waiting on @kungfucraig, @SanjayVas, and @stevenwarejones)

___
*[`src/main/terraform/gcloud/modules/kingdom/main.tf` line 190 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696#-O3Q1MPG7aoVP9v9-qrL:-O4wZ_cM-fsDo3S8JwHG:b-6kxymj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a3cba88a3d3f070ed61b893a5bbd749bab494301/src/main/terraform/gcloud/modules/kingdom/main.tf#L190)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

If that time is necessary, that is already in the measurements table. I realized that I am unsure about the purpose of this table. I understand measurements and requisitions, but not this.
</blockquote></details>

Deleted computation participants table after discussion.


<!-- Sent from Reviewable.io -->

2024-08-23 20:26 UTC, kungfucraig approved these changes
> Reviewed 2 of 14 files at r13, 1 of 6 files at r17.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696)* status: 24 of 36 files reviewed, 3 unresolved discussions (waiting on @SanjayVas, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt` line 403 at r17](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696#-O5-uezA12WdibFui59q:-O5-uezA12WdibFui59r:boip2qt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/024b88b9648f05f5d61684d7958b866dfd4fd03c/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt#L403)):*
> ```Kotlin
>         .trimIndent()
> 
>     private val FULL_VIEW_SQL =
> ```

As part of testing, can we look at the query plans for the various queries we run?


<!-- Sent from Reviewable.io -->

2024-09-09 16:40 UTC, tristanvuong2021 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696)* status: 23 of 36 files reviewed, 3 unresolved discussions (waiting on @kungfucraig, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt` line 403 at r17](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696#-O5-uezA12WdibFui59q:-O6MdYPyAR266-y9zHvB:bu50ij) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/024b88b9648f05f5d61684d7958b866dfd4fd03c/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt#L403)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

As part of testing, can we look at the query plans for the various queries we run?
</blockquote></details>

I did look at it. That is why I made query changes in StreamMeasurements.kt.


<!-- Sent from Reviewable.io -->

2024-09-09 16:41 UTC, tristanvuong2021 reviewed
> Dismissed @SanjayVas and @kungfucraig from 2 discussions.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696)* status: 23 of 36 files reviewed, 1 unresolved discussion (waiting on @kungfucraig, @SanjayVas, and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2024-09-10 16:48 UTC, tristanvuong2021 reviewed
> Reviewed 1 of 22 files at r1, 4 of 21 files at r2, 5 of 16 files at r4, 1 of 4 files at r5, 4 of 10 files at r10, 1 of 5 files at r12, 3 of 14 files at r13, 1 of 3 files at r14, 5 of 8 files at r16, 5 of 6 files at r17, 2 of 5 files at r18, 2 of 3 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696)* status: 35 of 36 files reviewed, 1 unresolved discussion (waiting on @kungfucraig, @SanjayVas, and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2024-09-13 19:46 UTC, tristanvuong2021 reviewed
> Reviewed 1 of 3 files at r19, 4 of 4 files at r20, all commit messages.
> Dismissed @kungfucraig from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)



<!-- Sent from Reviewable.io -->

2024-09-13 19:56 UTC, tristanvuong2021 reviewed
> Dismissed @SanjayVas from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)



<!-- Sent from Reviewable.io -->

2024-09-13 20:03 UTC, tristanvuong2021 reviewed
> Dismissed @SanjayVas from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)



<!-- Sent from Reviewable.io -->

2024-09-13 21:21 UTC, SanjayVas requested changes
> Reviewed 1 of 3 files at r14, 8 of 8 files at r16, 5 of 6 files at r17, 2 of 5 files at r18, 3 of 3 files at r19, 4 of 4 files at r20, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696)* status: all files reviewed, 2 unresolved discussions (waiting on @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt` line 403 at r17](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696#-O5Jfl1p3EQoPwGixNb8:-O5Jew7M00uhAvl2HmlP:b-m6v75g) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/024b88b9648f05f5d61684d7958b866dfd4fd03c/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt#L403)):*
> ```Kotlin
>         .trimIndent()
> 
>     private val FULL_VIEW_SQL =
> ```

I thought COMPUTATIONS and FULL give the same result, meaning they use the same query aside from ordering (which isn't part of this constant).
___
*[`src/main/proto/wfa/measurement/internal/kingdom/bigquerytables/operational_metrics_dataset.proto` line 58 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696#-O6hFVZZ1F7g0fAxkjXX:-O6hFVZZ1F7g0fAxkjXY:b-etv0a) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a3cba88a3d3f070ed61b893a5bbd749bab494301/src/main/proto/wfa/measurement/internal/kingdom/bigquerytables/operational_metrics_dataset.proto#L58)):*
> ```proto
> }
> 
> message ComputationParticipantsTableRow {
> ```

Doesn't this need to get added back in? DuchyMeasurmentLogEntries includes non-error entries with the stages.


<!-- Sent from Reviewable.io -->

2024-09-13 21:33 UTC, tristanvuong2021 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696)* status: all files reviewed, 2 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt` line 403 at r17](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696#-O5Jfl1p3EQoPwGixNb8:-O6hHuxdBN0NNNWnsCCa:b-tlbzij) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/024b88b9648f05f5d61684d7958b866dfd4fd03c/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt#L403)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I thought COMPUTATIONS and FULL give the same result, meaning they use the same query aside from ordering (which isn't part of this constant).
</blockquote></details>

The query is the same aside from ordering, but the building of the result isn't. Although it is only a small difference right now, I will need to include all the log entries. The result of the computation view only includes errors.
___
*[`src/main/proto/wfa/measurement/internal/kingdom/bigquerytables/operational_metrics_dataset.proto` line 58 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696#-O6hFVZZ1F7g0fAxkjXX:-O6hIM7X61fRLFHwdAtW:b-1o8frm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a3cba88a3d3f070ed61b893a5bbd749bab494301/src/main/proto/wfa/measurement/internal/kingdom/bigquerytables/operational_metrics_dataset.proto#L58)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Doesn't this need to get added back in? DuchyMeasurmentLogEntries includes non-error entries with the stages.
</blockquote></details>

I was planning to follow up this PR with a new table. This PR has been alive for awhile and I can see some new discussions regarding the new table.


<!-- Sent from Reviewable.io -->

2024-09-13 21:55 UTC, SanjayVas approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1696)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)



<!-- Sent from Reviewable.io -->

2024-09-13 23:28 UTC, merged