Prepare example Kingdom-less exchange daemon for GKE.
world-federation-of-advertisers/cross-media-measurement pull request #1698
Opened 2024-07-22 18:17 UTC by robinsons

Summary:
* Creates `.cue` files for deploying Kingdom-less daemon to GKE.
* Adds Kingdom-less daemon flags.
    * Uses `@ArgGroup` to ensure mutual exclusitivity between Kingdom-based flags and Kingdom-less flags.
    * Updates the example daemon main class to build the correct type of `ApiClient` and `CertificateManager` based on which group of flags was set.
* Several other tweaks to make the deployment work:
    * Factory function for building a shared storage client needed to be `suspend`ing.
    * Explicitly call `withDefaultCredentails()` when building `GcpKmsClient`. This used to happen by default, but seems to have been (inadvertently?) removed.
    * In `KingdomlessApiClient.kt`, make sure that `ExchangeWorkflowDependencyGraph` is built in step order. The dependency graph will throw if e.g. you try to mark a step as completed before its prerequisite steps.

2024-07-22 18:17 UTC, wfa-reviewable commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1698)
<!-- Reviewable:end -->

2024-07-26 21:23 UTC, stevenwarejones requested changes
> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1698)* status: all files reviewed, 1 unresolved discussion (waiting on @robinsons)

___
*[`src/main/kotlin/org/wfanet/panelmatch/client/launcher/KingdomlessApiClient.kt` line 639 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1698#-O2kvLwMC4aXd_sBfT1T:-O2kvLwMC4aXd_sBfT1U:ba44q4x) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/40a3ae8d6808005287d97e7c7dec413a4f630440/src/main/kotlin/org/wfanet/panelmatch/client/launcher/KingdomlessApiClient.kt#L639)):*
> ```Kotlin
>       try {
>         return block()
>       } catch (e: Exception) {
> ```

this should only retry nonfatal exceptions


<!-- Sent from Reviewable.io -->

2024-07-26 22:14 UTC, robinsons reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1698)* status: 9 of 11 files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/panelmatch/client/launcher/KingdomlessApiClient.kt` line 639 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1698#-O2kvLwMC4aXd_sBfT1T:-O2l5h8m5TWjFu88D2BV:b-g4q1dk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/40a3ae8d6808005287d97e7c7dec413a4f630440/src/main/kotlin/org/wfanet/panelmatch/client/launcher/KingdomlessApiClient.kt#L639)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

this should only retry nonfatal exceptions
</blockquote></details>

Updated to allow the caller to do some very basic exception handling and suppress specific exception types.


<!-- Sent from Reviewable.io -->

2024-07-29 21:40 UTC, stevenwarejones approved these changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1698)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @robinsons)



<!-- Sent from Reviewable.io -->

2024-07-29 21:55 UTC, merged