Add missing fields to internal Measurement/Requisition.
world-federation-of-advertisers/cross-media-measurement pull request #170
Opened 2021-07-27 23:07 UTC by SanjayVas

These were needed to populate the matching public API messages. The Requistion fields that are denormalized from the parent Measurement are now not populated for the NORMALIZED Requisition view.

2021-07-27 23:08 UTC, SanjayVas commented
CC @uakyol @tristanvuong2021 as this relates to both #103 and #11.

2021-07-28 16:31 UTC, wangyaopw approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/170)* status: 0 of 7 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[src/main/proto/wfa/measurement/internal/kingdom/requisition.proto, line 105 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/170#-MfhwGkw2B3UNX7IChf6:-MfhwGkw2B3UNX7IChf7:blc2ov4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1079993f358188a3e7b904e17b7a3d0ed61c6aa6/src/main/proto/wfa/measurement/internal/kingdom/requisition.proto#L105)):*
> ```
> external_duchy_certificate_id 
> ```
nit: add comment to clarify that this certificate is used to verified the signature in the protocol?
 
It seems that we need to update the public api requisition to contain a oneOf protocol too. 
https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/main/src/main/proto/wfa/measurement/api/v2alpha/requisition.proto#L85


<!-- Sent from Reviewable.io -->

2021-07-28 18:31 UTC, SanjayVas reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/170)* status: 0 of 7 files reviewed, all discussions resolved (waiting on @SanjayVas)

___
*[src/main/proto/wfa/measurement/internal/kingdom/requisition.proto, line 105 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/170#-MfhwGkw2B3UNX7IChf6:-MfiNTl34mZf93eLhwaD:b-w408dc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5b144224b9931e44caa4ef7c4dc8ac0004ccf77c/src/main/proto/wfa/measurement/internal/kingdom/requisition.proto#L105)):*
Done.

> It seems that we need to update the public api requisition to contain a oneOf protocol too.

Yeah, I'll make that change in the public API.


<!-- Sent from Reviewable.io -->

2021-07-28 19:25 UTC, SanjayVas reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/170)* status: 0 of 7 files reviewed, all discussions resolved (waiting on @kungfucraig, @oliver-amzn, @stevenwarejones, and @zachcwc)

___
*[src/main/proto/wfa/measurement/internal/kingdom/requisition.proto, line 105 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/170#-MfhwGkw2B3UNX7IChf6:-Mfi_0XR41S8Oz6y0xl8:bnmabfv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5b144224b9931e44caa4ef7c4dc8ac0004ccf77c/src/main/proto/wfa/measurement/internal/kingdom/requisition.proto#L105)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Done.

> It seems that we need to update the public api requisition to contain a oneOf protocol too.

Yeah, I'll make that change in the public API.
</blockquote></details>

See https://github.com/world-federation-of-advertisers/cross-media-measurement-api/pull/36


<!-- Sent from Reviewable.io -->

2021-07-28 20:03 UTC, kungfucraig approved these changes
> Reviewed 1 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/170)* status: 1 of 7 files reviewed, all discussions resolved (waiting on @oliver-amzn, @stevenwarejones, and @zachcwc)



<!-- Sent from Reviewable.io -->

2021-07-28 20:44 UTC, stevenwarejones requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/170)* status: 1 of 7 files reviewed, 1 unresolved discussion (waiting on @oliver-amzn, @SanjayVas, and @zachcwc)

___
*[src/main/proto/wfa/measurement/internal/kingdom/measurement.proto, line 93 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/170#-MfiquRs0nQZhajFfEV9:-MfiquRs0nQZhajFfEVA:b-phzc2w) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/150c33cc6c353e011a822ffd478a80d48b9e7ebc/src/main/proto/wfa/measurement/internal/kingdom/measurement.proto#L93)):*
> ```protobuf
>     bytes data_provider_public_key_signature = 3;
> 
>     bytes encrypted_requisition_spec = 4;
> ```

I believe the hash of this is what is passed around for the protos for duchy and system internal apis


<!-- Sent from Reviewable.io -->

2021-07-28 21:23 UTC, SanjayVas reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/170)* status: 1 of 7 files reviewed, 1 unresolved discussion (waiting on @oliver-amzn, @stevenwarejones, and @zachcwc)

___
*[src/main/proto/wfa/measurement/internal/kingdom/measurement.proto, line 93 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/170#-MfiquRs0nQZhajFfEV9:-MfiyMcL5L_wTlUOBSAe:bv4j65c) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/150c33cc6c353e011a822ffd478a80d48b9e7ebc/src/main/proto/wfa/measurement/internal/kingdom/measurement.proto#L93)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

I believe the hash of this is what is passed around for the protos for duchy and system internal apis
</blockquote></details>

This message is mapping to `Measurement.DataProviderEntry.Value` from the v2alpha public API. For the Spanner DB schema, this data would actually get persisted in the Requisitions table in the serialized `Requisition.Details` column.

Service impls that need to include a hash of this in a response can compute said hash on demand.


<!-- Sent from Reviewable.io -->

2021-07-28 21:32 UTC, stevenwarejones approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/170)* status: 1 of 7 files reviewed, all discussions resolved (waiting on @oliver-amzn and @zachcwc)



<!-- Sent from Reviewable.io -->

2021-07-28 21:36 UTC, oliver-amzn approved these changes
> Reviewed 6 of 7 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/170)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zachcwc)



<!-- Sent from Reviewable.io -->

2021-07-28 22:05 UTC, merged