Implement ExchangeStepsService claimReadyExchangeStep
world-federation-of-advertisers/cross-media-measurement pull request #171
Opened 2021-07-28 20:44 UTC by yunyeng

2021-07-28 22:25 UTC, efoxepstein requested changes
> Reviewed 16 of 24 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/171)* status: 16 of 24 files reviewed, 11 unresolved discussions (waiting on @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/ExchangeReader.kt, line 29 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/171#-Mfj7Tgp7EYyhbgQ4B1K:-Mfj7Tgp7EYyhbgQ4B1L:bytkuk5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b716d5a44e066cb9c511b38d0483d73903f7d770/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/ExchangeReader.kt#L29)):*
> ```Kotlin
>   SpannerReader<ExchangeReader.Result>() {
>   data class Result(
>     val recurringExchange: RecurringExchange,
> ```

It seems very weird to me that an `ExchangeReader` would now return an exchange. Should this be renamed to `RecurringExchangeReader`?
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/testing/KingdomDatabaseTestBase.kt, line 428 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/171#-Mfj7e35-oMnH9gkB4ti:-Mfj7e35-oMnH9gkB4tj:b-5vq3aw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b716d5a44e066cb9c511b38d0483d73903f7d770/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/testing/KingdomDatabaseTestBase.kt#L428)):*
> ```Kotlin
>   }
> 
>   protected fun readAllExchangesInSpanner(): List<RecurringExchange> = runBlocking {
> ```

`readAllRecurringExchangesInSpanner`?
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/ExchangeStepsService.kt, line 40 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/171#-Mfj9YLj9YnIEd572EHo:-Mfj9YLj9YnIEd572EHp:b-rayupc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b716d5a44e066cb9c511b38d0483d73903f7d770/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/ExchangeStepsService.kt#L40)):*
> ```Kotlin
> import org.wfanet.measurement.kingdom.deploy.gcloud.spanner.writers.UpdateRecurringExchange
> import org.wfanet.measurement.kingdom.service.api.v2alpha.toLocalDate
> import org.wfanet.measurement.kingdom.service.api.v2alpha.toProtoDate
> ```

If these helpers are applicable outside of `v2alpha` them put them in `common`
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/ExchangeStepsService.kt, line 42 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/171#-Mfj8daW1CzRA8fj2xu7:-Mfj8daW1CzRA8fj2xu8:b-5ru82g) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b716d5a44e066cb9c511b38d0483d73903f7d770/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/ExchangeStepsService.kt#L42)):*
> ```Kotlin
> import org.wfanet.measurement.kingdom.service.api.v2alpha.toProtoDate
> 
> class ExchangeStepsService(private val client: AsyncDatabaseClient) :
> ```

I think this should be called `SpannerExchangeStepsService` and be in `kingdom/deploy/gcloud/spanner` -- see https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerEventGroupsService.kt for example.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/ExchangeStepsService.kt, line 104 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/171#-MfjAANY-TnrdS5vb3Ih:-MfjAANY-TnrdS5vb3Ii:bzc0nk7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b716d5a44e066cb9c511b38d0483d73903f7d770/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/ExchangeStepsService.kt#L104)):*
> ```Kotlin
>           else emptyList(),
>         states = listOf(RecurringExchange.State.ACTIVE),
>         nextExchangeDate = LocalDate.now().toProtoDate() // NOW
> ```

Please rename the `nextExchangeDate` parameter to `nextExchangeDateBefore`
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/ExchangeStepsService.kt, line 106 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/171#-MfjAftM6L-tOXlShs5u:-MfjAftM6L-tOXlShs5v:b-v7rtnm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b716d5a44e066cb9c511b38d0483d73903f7d770/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/ExchangeStepsService.kt#L106)):*
> ```Kotlin
>         nextExchangeDate = LocalDate.now().toProtoDate() // NOW
>       )
>     StreamExchanges(streamFilter, 0).execute(client.singleUse()).collect {
> ```

What is the zero for? Can you write `StreamExchanges(streamFilter, foo=0)`
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/ExchangeStepsService.kt, line 125 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/171#-MfjARaT8NFB-C_-BP7Z:-MfjARaT8NFB-C_-BP7_:b8abzjz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b716d5a44e066cb9c511b38d0483d73903f7d770/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/ExchangeStepsService.kt#L125)):*
> ```Kotlin
>         nextExchangeDate.applyCronSchedule(recurringExchange.details.cronSchedule)
> 
>       // Update recurring exchange with new next exchange date. It's state doesn't change.
> ```

"It's" -> "Its"
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/ExchangeStepsService.kt, line 132 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/171#-MfjAzFfCSiL6agytEmk:-MfjAzFfCSiL6agytEml:bth2gmz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b716d5a44e066cb9c511b38d0483d73903f7d770/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/ExchangeStepsService.kt#L132)):*
> ```Kotlin
>           state = recurringExchange.state
>         )
>         .execute(client)
> ```

I think you need to create the exchange and update the recurringexchange in the same transaction? Would bad things happen if the first transaction succeeded and the second failed? You probably also want to create the exchange steps in the same transaction too.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/ExchangeStepsService.kt, line 149 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/171#-MfjB_p22dhW6xhDpHW-:-MfjB_p22dhW6xhDpHW0:b-lnbna4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b716d5a44e066cb9c511b38d0483d73903f7d770/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/ExchangeStepsService.kt#L149)):*
> ```Kotlin
>     request: ClaimReadyExchangeStepRequest
>   ): ClaimReadyExchangeStepResponse {
>     grpcRequire(request.hasExternalDataProviderId() || request.hasExternalModelProviderId()) {
> ```

better to check `request.partyCase == PartyCase.PARTY_NOT_SET`
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/ExchangeStepsService.kt, line 200 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/171#-MfjCdZ73QFN22hZgjny:-MfjCdZ73QFN22hZgjnz:b-keozf1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b716d5a44e066cb9c511b38d0483d73903f7d770/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/ExchangeStepsService.kt#L200)):*
> ```Kotlin
>     // Finally, update the Step's status to IN_PROGRESS before return to client.
>     val updatedStep =
>       UpdateExchangeStepState(
> ```

Can you just create it in state IN_PROGRESS?
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/ExchangeStepsService.kt, line 215 at r1](https://reviewable.io/review [...]

2021-07-29 22:50 UTC, yunyeng reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/171)* status: 2 of 40 files reviewed, 11 unresolved discussions (waiting on @efoxepstein)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/testing/KingdomDatabaseTestBase.kt, line 428 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/171#-Mfj7e35-oMnH9gkB4ti:-MfoSWtuEgFwzvgNF_Uf:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b716d5a44e066cb9c511b38d0483d73903f7d770/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/testing/KingdomDatabaseTestBase.kt#L428)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

`readAllRecurringExchangesInSpanner`?
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/ExchangeStepsService.kt, line 40 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/171#-Mfj9YLj9YnIEd572EHo:-MfoSYOr9fzkWhh64EQr:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b716d5a44e066cb9c511b38d0483d73903f7d770/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/ExchangeStepsService.kt#L40)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

If these helpers are applicable outside of `v2alpha` them put them in `common`
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/ExchangeStepsService.kt, line 42 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/171#-Mfj8daW1CzRA8fj2xu7:-MfoSXs85soeJ8j13Hii:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b716d5a44e066cb9c511b38d0483d73903f7d770/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/ExchangeStepsService.kt#L42)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

I think this should be called `SpannerExchangeStepsService` and be in `kingdom/deploy/gcloud/spanner` -- see https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerEventGroupsService.kt for example.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/ExchangeStepsService.kt, line 104 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/171#-MfjAANY-TnrdS5vb3Ih:-MfoSZ0Q4UPEVR7JkvhC:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b716d5a44e066cb9c511b38d0483d73903f7d770/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/ExchangeStepsService.kt#L104)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Please rename the `nextExchangeDate` parameter to `nextExchangeDateBefore`
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/ExchangeStepsService.kt, line 106 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/171#-MfjAftM6L-tOXlShs5u:-MfoS_Ud1S2DN_73mTxz:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b716d5a44e066cb9c511b38d0483d73903f7d770/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/ExchangeStepsService.kt#L106)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

What is the zero for? Can you write `StreamExchanges(streamFilter, foo=0)`
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/ExchangeStepsService.kt, line 125 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/171#-MfjARaT8NFB-C_-BP7Z:-MfoSZGaCzfuUpeT_uZr:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b716d5a44e066cb9c511b38d0483d73903f7d770/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/ExchangeStepsService.kt#L125)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

"It's" -> "Its"
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/ExchangeStepsService.kt, line 132 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/171#-MfjAzFfCSiL6agytEmk:-MfoSa_37YQkMnaPP-fQ:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b716d5a44e066cb9c511b38d0483d73903f7d770/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/ExchangeStepsService.kt#L132)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

I think you need to create the exchange and update the recurringexchange in the same transaction? Would bad things happen if the first transaction succeeded and the second failed? You probably also want to create the exchange steps in the same transaction too.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/ExchangeStepsService.kt, line 149 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/171#-MfjB_p22dhW6xhDpHW-:-MfoSaluCYI1hGgQFsuF:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b716d5a44e066cb9c511b38d0483d73903f7d770/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/ExchangeStepsService.kt#L149)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

better to check `request.partyCase == PartyCase.PARTY_NOT_SET`
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/ExchangeStepsService.kt, line 200 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/171#-MfjCdZ73QFN22hZgjny:-MfoSbK43rzrhUn4fWRt:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b716d5a44e066cb9c511b38d0483d73903f7d770/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/ExchangeStepsService.kt#L200)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Can you just create it in state IN_PROGRESS?
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/ExchangeStepsService.kt, line 215 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/171#-MfjCkvJ6BgOlJcWSKVR:-MfoSb6y9hhrPait5-26:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b716d5a44e066cb9c511b38d0483d73903f7d770/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/ExchangeStepsService.kt#L215)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

It's probably ideal to just do everything in a single transaction. Maybe just make a ClaimReadyExchangeStep subclass of SpannerWriter to contain all of the logic. Trying to create reusable components is likely to add too much complexity. 
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/ExchangeReader.kt, line 29 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/171#-Mfj7Tgp7EYyhbgQ4B1K:-MfoSVXv8XDLDVf1gAyn:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b716d5a44e066cb9c511b38d0483d73903f7d770/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/Exch [...]

2021-07-29 22:55 UTC, efoxepstein requested changes
> Reviewed 12 of 26 files at r2, 4 of 15 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/171)* status: 18 of 40 files reviewed, 21 unresolved discussions (waiting on @efoxepstein and @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/common/BUILD.bazel, line 9 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/171#-MfoPJAD140_I1mNZYEn:-MfoPJAD140_I1mNZYEo:bd6fmgg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a06777e6868b2264653b08be34ffbb6bd126abee/src/main/kotlin/org/wfanet/measurement/common/BUILD.bazel#L9)):*
> ```Starlark
> 
> kt_jvm_library(
>     name = "util",
> ```

Please rename this to just `common` and set `srcs = glob(["*.kt"])`
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamExchanges.kt, line 34 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/171#-MfoPgw41OlmQiJLU4wr:-MfoPgw41OlmQiJLU4ws:b-voisgj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a06777e6868b2264653b08be34ffbb6bd126abee/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamExchanges.kt#L34)):*
> ```Kotlin
>  * @param limit how many [Exchange]s to return -- if zero, there is no limit
>  */
> class StreamExchanges(filter: StreamExchangesFilter, limit: Long = 0) :
> ```

`StreamRecurringExchanges`?
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ClaimReadyExchangeStep.kt, line 62 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/171#-MfoQ33Y1RGIOf0d34U_:-MfoQ33Y1RGIOf0d34Ua:by0hmp3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a06777e6868b2264653b08be34ffbb6bd126abee/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ClaimReadyExchangeStep.kt#L62)):*
> ```Kotlin
>     try {
>       // Check if any READY | READY_TO_RETRY Exchange Step exists.
>       return findReadyExchangeStep()
> ```

Since it's expected behavior that this might not find anything, it shouldn't throw an exception. Can you just have it return null if it can't find anything? 
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ClaimReadyExchangeStep.kt, line 68 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/171#-MfoQdHO9iZUQXl9n2kz:-MfoQdHO9iZUQXl9n2l-:b-dtxt4c) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a06777e6868b2264653b08be34ffbb6bd126abee/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ClaimReadyExchangeStep.kt#L68)):*
> ```Kotlin
>       val firstReadyStep = createExchangesAndSteps()
>       if (firstReadyStep.exchangeStep == null || firstReadyStep.recurringExchangeId == null) {
>         throw Status.NOT_FOUND.withDescription("No Exchange Steps were found.").asRuntimeException()
> ```

This also isn't an error. I'd suggest just changing the class to return `Result?`. (If for some reason SpannerWriter doesn't like nullable results, then just allow the `step` and `attempt` within it to be null.)
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ClaimReadyExchangeStep.kt, line 102 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/171#-MfoRVhZ4zyvbLJjAyxJ:-MfoRVhZ4zyvbLJjAyxK:brvqbmj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a06777e6868b2264653b08be34ffbb6bd126abee/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ClaimReadyExchangeStep.kt#L102)):*
> ```Kotlin
>     val exchangeStepResult =
>       try {
>         GetExchangeStep(stepFilter).executeSingle(transactionContext)
> ```

As mentioned above, this shouldn't throw.

As an alternative, just run `val exchangeStepResult = GetExchangeStep(stepFilter).execute().singleOrNull() ?: return null`
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ClaimReadyExchangeStep.kt, line 137 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/171#-MfoS5_F0-3rQWLM_oOM:-MfoS5_F0-3rQWLM_oON:b-dl7ygg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a06777e6868b2264653b08be34ffbb6bd126abee/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ClaimReadyExchangeStep.kt#L137)):*
> ```Kotlin
>       streamExchangesFilter(
>         externalModelProviderIds =
>           if (externalModelProviderId == null) emptyList()
> ```

Since you do this multiple times in this file, maybe just do it once and make instance variables:

```
private val externalModelProviderIds = if (externalModelProviderId == null) emptyList() else listOf(...)
```
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ClaimReadyExchangeStep.kt, line 143 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/171#-MfoSLyl0Q8xJpTei4tV:-MfoSLymCloVMvc-n_G6:b-mpgzq3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a06777e6868b2264653b08be34ffbb6bd126abee/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ClaimReadyExchangeStep.kt#L143)):*
> ```Kotlin
>           else listOf(ExternalId(externalDataProviderId)),
>         states = listOf(RecurringExchange.State.ACTIVE),
>         nextExchangeDateBefore = LocalDate.now().toProtoDate() // NOW
> ```

This will ignore things for TODAY because it uses "less-than" not "less-than-or-equal", right? Should we just set nextExchangeDateBefore to tomorrow?
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ClaimReadyExchangeStep.kt, line 147 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/171#-MfoSXX1-vRG2BMoGcXl:-MfoSXX2-3RCPWgyIXwd:bfmayn9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ccfd8c2253edfd1cac639e2f5c07676385eb9410/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ClaimReadyExchangeStep.kt#L147)):*
> ```Kotlin
>     val streamResult =
>       try {
>         StreamExchanges(streamFilter, limit = 1).executeSingle(transactionContext)
> ```

Ditto -- use `.execute().singleOrNull() ?: return null`
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ClaimReadyExchangeStep.kt, line 198 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/171#-MfoSvZ-CD5b23pRG89W:-MfoSvZ-CD5b23pRG89X:b-kyp8zl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ccfd8c2253edfd1cac639e2f5c07676385eb9410/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ClaimReadyExchangeStep.kt#L198)):*
> ```Kotlin
>     externalRecurringExchangeId: Long,
>     modelProviderId: Long,
>     externalModelProviderId: Long?,
> ```

This shouldn't need to be a parameter, I don't think, since it can read the instance variable
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ClaimReadyExchangeStep.kt, line 200 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/171#-MfoT-7h9gzAND61IqDL:-MfoT-7h9gzAND61IqDM:b-89a4l7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ccfd8c2253edfd1cac639e2f5c07676385eb9410/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ClaimReadyExchangeStep.kt#L200)):*
> ```Kotlin
>     externalModelProviderId: Long?,
>     dataProviderId: Long,
>     externalDataProviderId: Long?,
> ```

Ditto


<!-- Sent from Reviewable.io -->

2021-07-29 22:58 UTC, efoxepstein requested changes
> Reviewed 1 of 24 files at r1, 10 of 26 files at r2, 11 of 15 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/171)* status: all files reviewed, 11 unresolved discussions (waiting on @yunyeng)

___
*[src/test/kotlin/org/wfanet/measurement/common/DateUtilTest.kt, line 24 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/171#-MfoTqHlCyEYyiI81PvB:-MfoTqHlCyEYyiI81PvC:bmev512) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ccfd8c2253edfd1cac639e2f5c07676385eb9410/src/test/kotlin/org/wfanet/measurement/common/DateUtilTest.kt#L24)):*
> ```Kotlin
> import org.junit.runner.RunWith
> import org.junit.runners.JUnit4
> import org.wfanet.measurement.kingdom.service.api.v2alpha.toLocalDate
> ```

This doesn't look right


<!-- Sent from Reviewable.io -->

2021-07-30 02:47 UTC, yunyeng reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/171)* status: 29 of 43 files reviewed, 11 unresolved discussions (waiting on @efoxepstein)

___
*[src/main/kotlin/org/wfanet/measurement/common/BUILD.bazel, line 9 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/171#-MfoPJAD140_I1mNZYEn:-MfpIZzJAmLtzrfDmp9x:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a06777e6868b2264653b08be34ffbb6bd126abee/src/main/kotlin/org/wfanet/measurement/common/BUILD.bazel#L9)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Please rename this to just `common` and set `srcs = glob(["*.kt"])`
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ClaimReadyExchangeStep.kt, line 62 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/171#-MfoQ33Y1RGIOf0d34U_:-MfpIbvr3Fa5anfaigTv:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a06777e6868b2264653b08be34ffbb6bd126abee/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ClaimReadyExchangeStep.kt#L62)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Since it's expected behavior that this might not find anything, it shouldn't throw an exception. Can you just have it return null if it can't find anything? 
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ClaimReadyExchangeStep.kt, line 68 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/171#-MfoQdHO9iZUQXl9n2kz:-MfpIcmr0WLpXW6viVsV:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a06777e6868b2264653b08be34ffbb6bd126abee/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ClaimReadyExchangeStep.kt#L68)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

This also isn't an error. I'd suggest just changing the class to return `Result?`. (If for some reason SpannerWriter doesn't like nullable results, then just allow the `step` and `attempt` within it to be null.)
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ClaimReadyExchangeStep.kt, line 102 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/171#-MfoRVhZ4zyvbLJjAyxJ:-MfpIdP47m4eFJQ_lIyF:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a06777e6868b2264653b08be34ffbb6bd126abee/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ClaimReadyExchangeStep.kt#L102)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

As mentioned above, this shouldn't throw.

As an alternative, just run `val exchangeStepResult = GetExchangeStep(stepFilter).execute().singleOrNull() ?: return null`
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ClaimReadyExchangeStep.kt, line 137 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/171#-MfoS5_F0-3rQWLM_oOM:-MfpIe-c4wAyqtxMGXZk:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a06777e6868b2264653b08be34ffbb6bd126abee/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ClaimReadyExchangeStep.kt#L137)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Since you do this multiple times in this file, maybe just do it once and make instance variables:

```
private val externalModelProviderIds = if (externalModelProviderId == null) emptyList() else listOf(...)
```
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ClaimReadyExchangeStep.kt, line 143 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/171#-MfoSLyl0Q8xJpTei4tV:-MfpIe_DDtsfJBgwEmCM:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a06777e6868b2264653b08be34ffbb6bd126abee/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ClaimReadyExchangeStep.kt#L143)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

This will ignore things for TODAY because it uses "less-than" not "less-than-or-equal", right? Should we just set nextExchangeDateBefore to tomorrow?
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ClaimReadyExchangeStep.kt, line 147 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/171#-MfoSXX1-vRG2BMoGcXl:-MfpIf3_AtBATSDxghrx:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ccfd8c2253edfd1cac639e2f5c07676385eb9410/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ClaimReadyExchangeStep.kt#L147)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Ditto -- use `.execute().singleOrNull() ?: return null`
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ClaimReadyExchangeStep.kt, line 198 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/171#-MfoSvZ-CD5b23pRG89W:-MfpIfXeEQWN9jS2SChl:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ccfd8c2253edfd1cac639e2f5c07676385eb9410/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ClaimReadyExchangeStep.kt#L198)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

This shouldn't need to be a parameter, I don't think, since it can read the instance variable
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ClaimReadyExchangeStep.kt, line 200 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/171#-MfoT-7h9gzAND61IqDL:-MfpIfttCgUT5f2mQ4yf:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ccfd8c2253edfd1cac639e2f5c07676385eb9410/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ClaimReadyExchangeStep.kt#L200)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Ditto
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamExchanges.kt, line 34 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/171#-MfoPgw41OlmQiJLU4wr:-MfpIb7zCSxkki319I_d:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a06777e6868b2264653b08be34ffbb6bd126abee/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamExchanges.kt#L34)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

`StreamRecurringExchanges`?
</blockquote></details>

Done.
___
*[src/test/kotlin/org/wfanet/measurement/common/DateUtilTest.kt, line 24 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/171#-MfoTqHlCyEYyiI81PvB:-MfpIgLX-B8NYeBUtm0q:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ccfd8c2253edfd1cac639e2f5c07676385eb9410/s [...]

2021-07-30 03:28 UTC, efoxepstein requested changes
> Reviewed 15 of 15 files at r4.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/171)* status: all files reviewed, 1 unresolved discussion (waiting on @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerExchangeStepsService.kt, line 50 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/171#-MfpQindEvchBHZfTE4A:-MfpQingEeA8tlr9dxOl:b-hjusr2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/70f0d41665a7106008b646ee1a812a670ff22c43/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerExchangeStepsService.kt#L50)):*
> ```Kotlin
>       .apply {
>         exchangeStep = result.step
>         attemptNumber = result.attempt!!.attemptNumber
> ```

This'll throw nullpointerexception if attempt is null. Instead, see if it's null and if it is, return maybe an empty response


<!-- Sent from Reviewable.io -->

2021-07-30 03:28 UTC, efoxepstein approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/171#-:-MfpSCjm78LxLFbiqz2z:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @yunyeng)



<!-- Sent from Reviewable.io -->

2021-07-30 04:04 UTC, yunyeng reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/171)* status: 42 of 43 files reviewed, 1 unresolved discussion (waiting on @efoxepstein)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerExchangeStepsService.kt, line 50 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/171#-MfpQindEvchBHZfTE4A:-Mfp_Vy6COcGHTKBlca6:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/70f0d41665a7106008b646ee1a812a670ff22c43/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerExchangeStepsService.kt#L50)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

This'll throw nullpointerexception if attempt is null. Instead, see if it's null and if it is, return maybe an empty response
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-07-30 04:21 UTC, efoxepstein approved these changes
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/171)* status: all files reviewed, 1 unresolved discussion (waiting on @oliver-amzn, @stevenwarejones, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerExchangeStepsService.kt, line 47 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/171#-MfpceY11e-VHIxT26cN:-MfpceY257gi1k6SGXKX:b-bqlxdp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a581f18f712ab3cfc0acd972f03beccff204d9ed/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerExchangeStepsService.kt#L47)):*
> ```Kotlin
>         .execute(client)
> 
>     if (result.step == null || result.attempt == null) {
> ```

It's a little weird to do an ||, because we expect them to be either both null or both not null. Maybe as a sanity check, throw some exception if one is null but the other isn't.

`require((foo==null) == (bar==null))`


<!-- Sent from Reviewable.io -->

2021-07-30 19:56 UTC, yunyeng reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/171)* status: 40 of 43 files reviewed, 1 unresolved discussion (waiting on @efoxepstein, @oliver-amzn, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerExchangeStepsService.kt, line 47 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/171#-MfpceY11e-VHIxT26cN:-MfszJL-DlgQfXlolqrY:b18cjuj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a581f18f712ab3cfc0acd972f03beccff204d9ed/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerExchangeStepsService.kt#L47)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

It's a little weird to do an ||, because we expect them to be either both null or both not null. Maybe as a sanity check, throw some exception if one is null but the other isn't.

`require((foo==null) == (bar==null))`
</blockquote></details>

This is done in the ClaimReadyExchangeStep class.


<!-- Sent from Reviewable.io -->

2021-07-30 21:03 UTC, wangyaopw requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/171)* status: 40 of 43 files reviewed, 4 unresolved discussions (waiting on @efoxepstein, @oliver-amzn, @stevenwarejones, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerExchangeStepsService.kt, line 36 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/171#-Mft8tAWEUqZs5BCIGiw:-Mft8tAWEUqZs5BCIGix:b-c6tcvp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b64b1893a1a7006710aa9baa4582da81c57e466b/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerExchangeStepsService.kt#L36)):*
> ```
> "INVALID_ARGUMENT: Data Provider id OR Model Provider id must be provided."
> ```
nit: `external_data_provider_id or external_model_provider_id must be provided.

`grpcRequire` is already throwing INVALID_ARGUMENT error, no need to have this in the error message again.
and prefers to use the name of field in the proto directly instead of descriptive words.
___
*[src/main/kotlin/org/wfanet/measurement/common/DateUtil.kt, line 15 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/171#-Mft7xZB83pwh9svdJiz:-Mft7xZB83pwh9svdJj-:ba7emkc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b64b1893a1a7006710aa9baa4582da81c57e466b/src/main/kotlin/org/wfanet/measurement/common/DateUtil.kt#L15)):*
> ```Kotlin
> // limitations under the License.
> 
> package org.wfanet.measurement.common
> ```

I think we are trying to avoid common code in cmms. This could be moved to the common-jvm repo.

We can keep it in the original place and add a TODO to use the common-jvm one when it is added.
___
*[src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ClaimReadyExchangeStepTest.kt, line 139 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/171#-MftCOZBD5QLnaVSbJD3:-MftCOZBD5QLnaVSbJD4:bll1g2e) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b64b1893a1a7006710aa9baa4582da81c57e466b/src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ClaimReadyExchangeStepTest.kt#L139)):*
> ```
> ClaimReadyExchangeStepTest : KingdomDatabaseTestBase() {
> ```

According to previous discussion with Ugur and Sanjay, all the other kingdom internal APIs don't test the spanner reader/writers directly, but instead test all behaviors in the service level, i.e., in those SpannerXXXServiceTest.kt.
https://github.com/world-federation-of-advertisers/cross-media-measurement/tree/main/src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner

Not sure if we want to make this consistent across the repo.


<!-- Sent from Reviewable.io -->

2021-07-30 21:08 UTC, wangyaopw requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/171)* status: 40 of 43 files reviewed, 4 unresolved discussions (waiting on @efoxepstein, @oliver-amzn, @stevenwarejones, and @yunyeng)

___
*[src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ClaimReadyExchangeStepTest.kt, line 139 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/171#-MftCOZBD5QLnaVSbJD3:-MftEd_N3-t-h6pB-pwl:bi3zf1p) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b64b1893a1a7006710aa9baa4582da81c57e466b/src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ClaimReadyExchangeStepTest.kt#L139)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
> ClaimReadyExchangeStepTest : KingdomDatabaseTestBase() {
> ```

According to previous discussion with Ugur and Sanjay, all the other kingdom internal APIs don't test the spanner reader/writers directly, but instead test all behaviors in the service level, i.e., in those SpannerXXXServiceTest.kt.
https://github.com/world-federation-of-advertisers/cross-media-measurement/tree/main/src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner

Not sure if we want to make this consistent across the repo.
</blockquote></details>

sorry, by service level tests, I am referring to those under
https://github.com/world-federation-of-advertisers/cross-media-measurement/tree/main/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing


<!-- Sent from Reviewable.io -->

2021-08-02 13:35 UTC, efoxepstein requested changes
> Reviewed 3 of 3 files at r6.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/171)* status: all files reviewed, 4 unresolved discussions (waiting on @oliver-amzn, @stevenwarejones, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ClaimReadyExchangeStep.kt, line 59 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/171#-Mg63QdP2PFPfipWa8ke:-Mg63QdP2PFPfipWa8kf:bmeompm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b64b1893a1a7006710aa9baa4582da81c57e466b/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ClaimReadyExchangeStep.kt#L59)):*
> ```Kotlin
>     val recurringExchangeId: Long?
>   )
>   data class InternalResult(val step: ExchangeStep?, val attempt: ExchangeStepAttempt?)
> ```

Can InternalResult just hold a `Result?`?
Also out of curiosity why doesn't SpannerWriter support null outputs?


<!-- Sent from Reviewable.io -->

2021-08-02 17:20 UTC, stevenwarejones requested changes
> Reviewed 3 of 24 files at r1, 8 of 26 files at r2, 8 of 15 files at r3, 12 of 15 files at r4, 2 of 3 files at r6.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/171)* status: all files reviewed, 5 unresolved discussions (waiting on @oliver-amzn, @wangyaopw, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ClaimReadyExchangeStep.kt, line 77 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/171#-Mg6r-ck-Lk5ipwXxwwj:-Mg6r-ck-Lk5ipwXxwwk:b16lpdq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b64b1893a1a7006710aa9baa4582da81c57e466b/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ClaimReadyExchangeStep.kt#L77)):*
> ```Kotlin
>     }
> 
>     // If not, create Exchanges and ExchangeSteps from the request.
> ```

whats the use case for creating an exchange and exchangeSteps from the request if an exchange step doesn't already exist?
___
*[src/main/kotlin/org/wfanet/measurement/common/DateUtil.kt, line 15 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/171#-Mft7xZB83pwh9svdJiz:-Mg6q7qx1a74EXYU-8qD:bgzkqoc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b64b1893a1a7006710aa9baa4582da81c57e466b/src/main/kotlin/org/wfanet/measurement/common/DateUtil.kt#L15)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

I think we are trying to avoid common code in cmms. This could be moved to the common-jvm repo.

We can keep it in the original place and add a TODO to use the common-jvm one when it is added.
</blockquote></details>

If these are things common just for this repo, I don't think they should be moved to common-jvm.


<!-- Sent from Reviewable.io -->

2021-08-02 17:29 UTC, efoxepstein reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/171)* status: all files reviewed, 5 unresolved discussions (waiting on @oliver-amzn, @stevenwarejones, @wangyaopw, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ClaimReadyExchangeStep.kt, line 77 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/171#-Mg6r-ck-Lk5ipwXxwwj:-Mg6twPe1S8JUWN3QIXP:b-s4kalp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b64b1893a1a7006710aa9baa4582da81c57e466b/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ClaimReadyExchangeStep.kt#L77)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

whats the use case for creating an exchange and exchangeSteps from the request if an exchange step doesn't already exist?
</blockquote></details>

This is "instantiating" a RecurringExchange if it's ready to be instantiated.

The comment would be more accurate as something like:

```
// Look for a RecurringExchange that is due for instantiation as an Exchange.
// If there are any, pick an arbitrary one, create an Exchange and the corresponding
// ExchangeSteps, and then see if any of those are ready.
```


<!-- Sent from Reviewable.io -->

2021-08-02 17:43 UTC, stevenwarejones requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/171)* status: all files reviewed, 5 unresolved discussions (waiting on @efoxepstein, @oliver-amzn, @wangyaopw, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ClaimReadyExchangeStep.kt, line 77 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/171#-Mg6r-ck-Lk5ipwXxwwj:-Mg6xXBb4FydnVceHUnR:b-khulpo) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b64b1893a1a7006710aa9baa4582da81c57e466b/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ClaimReadyExchangeStep.kt#L77)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

This is "instantiating" a RecurringExchange if it's ready to be instantiated.

The comment would be more accurate as something like:

```
// Look for a RecurringExchange that is due for instantiation as an Exchange.
// If there are any, pick an arbitrary one, create an Exchange and the corresponding
// ExchangeSteps, and then see if any of those are ready.
```
</blockquote></details>

lets update the comment to something like that then


<!-- Sent from Reviewable.io -->

2021-08-02 18:34 UTC, yunyeng reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/171)* status: 34 of 45 files reviewed, 4 unresolved discussions (waiting on @efoxepstein, @oliver-amzn, @stevenwarejones, and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ClaimReadyExchangeStep.kt, line 59 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/171#-Mg63QdP2PFPfipWa8ke:-Mg780qsDTgDF5Q2nXzt:bvtcpzj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b64b1893a1a7006710aa9baa4582da81c57e466b/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ClaimReadyExchangeStep.kt#L59)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Can InternalResult just hold a `Result?`?
Also out of curiosity why doesn't SpannerWriter support null outputs?
</blockquote></details>

Removed InternalResult.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ClaimReadyExchangeStep.kt, line 77 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/171#-Mg6r-ck-Lk5ipwXxwwj:-Mg78AIC2hjgO8qzsK2y:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b64b1893a1a7006710aa9baa4582da81c57e466b/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ClaimReadyExchangeStep.kt#L77)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

lets update the comment to something like that then
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/common/DateUtil.kt, line 15 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/171#-Mft7xZB83pwh9svdJiz:-Mg77uS04WFSurYtY8DS:bv0d45m) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b64b1893a1a7006710aa9baa4582da81c57e466b/src/main/kotlin/org/wfanet/measurement/common/DateUtil.kt#L15)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

If these are things common just for this repo, I don't think they should be moved to common-jvm.
</blockquote></details>

Moved to common-jvm. I believe that code are used by multiple repos.
___
*[src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ClaimReadyExchangeStepTest.kt, line 139 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/171#-MftCOZBD5QLnaVSbJD3:-Mg78BoZ2qgdiFKptHYc:b-d5ev5x) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b64b1893a1a7006710aa9baa4582da81c57e466b/src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ClaimReadyExchangeStepTest.kt#L139)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

sorry, by service level tests, I am referring to those under
https://github.com/world-federation-of-advertisers/cross-media-measurement/tree/main/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing
</blockquote></details>

This was discussed offline. I will update the tests once we have the RecurringExchange.get/create methods for test helpers.


<!-- Sent from Reviewable.io -->

2021-08-02 18:39 UTC, stevenwarejones approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/171)* status: 30 of 45 files reviewed, 3 unresolved discussions (waiting on @efoxepstein, @oliver-amzn, @stevenwarejones, and @wangyaopw)



<!-- Sent from Reviewable.io -->

2021-08-02 18:48 UTC, efoxepstein requested changes
> Reviewed 3 of 11 files at r7.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/171)* status: 33 of 45 files reviewed, 3 unresolved discussions (waiting on @efoxepstein, @oliver-amzn, @stevenwarejones, @wangyaopw, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ClaimReadyExchangeStep.kt, line 59 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/171#-Mg63QdP2PFPfipWa8ke:-Mg7Atl01OvakDbVM3VB:b-sg7fud) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b64b1893a1a7006710aa9baa4582da81c57e466b/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ClaimReadyExchangeStep.kt#L59)):*
<details><summary><i>Previously, yunyeng (Yunus Yen) wrote…</i></summary><blockquote>

Removed InternalResult.
</blockquote></details>

I don't really like this because it permits states where one but not both of the things are null. How about:

```
class ClaimReadyExchangeStep(...): SpannerWriter<Result, Optional<Result>> {
  data class Result(val step: ExchangeStep, val attemptNumber: Int)
  ...
}
```


<!-- Sent from Reviewable.io -->

2021-08-02 19:27 UTC, yunyeng reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/171)* status: 32 of 45 files reviewed, 3 unresolved discussions (waiting on @efoxepstein, @oliver-amzn, @stevenwarejones, and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ClaimReadyExchangeStep.kt, line 59 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/171#-Mg63QdP2PFPfipWa8ke:-Mg7KOboAzv5e1fo-s49:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b64b1893a1a7006710aa9baa4582da81c57e466b/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ClaimReadyExchangeStep.kt#L59)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

I don't really like this because it permits states where one but not both of the things are null. How about:

```
class ClaimReadyExchangeStep(...): SpannerWriter<Result, Optional<Result>> {
  data class Result(val step: ExchangeStep, val attemptNumber: Int)
  ...
}
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-02 20:31 UTC, efoxepstein requested changes
> Reviewed 6 of 11 files at r7, 4 of 4 files at r8, 3 of 3 files at r9.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/171)* status: all files reviewed, 3 unresolved discussions (waiting on @oliver-amzn, @wangyaopw, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ClaimReadyExchangeStep.kt, line 61 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/171#-Mg7YzGj5cxaRb_DN__M:-Mg7YzGj5cxaRb_DN__N:b-2qxe4c) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1c4ed2986a0c8293a3bdca3990c3ffda05a9e2f6/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ClaimReadyExchangeStep.kt#L61)):*
> ```Kotlin
>     val recurringExchangeId: Long?
>   )
>   data class Result(val step: ExchangeStep?, val attemptNumber: Int?)
> ```

Why are `step` and `attemptNumber` still nullable?


<!-- Sent from Reviewable.io -->

2021-08-02 20:42 UTC, stevenwarejones approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/171)* status: all files reviewed, 3 unresolved discussions (waiting on @oliver-amzn, @wangyaopw, and @yunyeng)



<!-- Sent from Reviewable.io -->

2021-08-02 20:53 UTC, yunyeng reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/171)* status: 43 of 45 files reviewed, 3 unresolved discussions (waiting on @efoxepstein, @oliver-amzn, and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ClaimReadyExchangeStep.kt, line 61 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/171#-Mg7YzGj5cxaRb_DN__M:-Mg7dAlQDd_dTSPzRN_s:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1c4ed2986a0c8293a3bdca3990c3ffda05a9e2f6/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ClaimReadyExchangeStep.kt#L61)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Why are `step` and `attemptNumber` still nullable?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-02 22:09 UTC, efoxepstein approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r10.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/171#-:-Mg7uTCi4J3qSE3d34ww:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @oliver-amzn, @wangyaopw, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ClaimReadyExchangeStep.kt, line 49 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/171#-Mg7p_E-EP6EIEUYC8_y:-Mg7p_E-EP6EIEUYC8_z:b-kuupz6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/04a00cedbf3f0c8d4e2c7412325524c19620ffa6/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ClaimReadyExchangeStep.kt#L49)):*
> ```Kotlin
>   private val externalModelProviderId: Long?,
>   private val externalDataProviderId: Long?
> ) : SpannerWriter<Result?, Optional<Result>>() {
> ```

Out of curiosity (and I won't block the PR with this) but does it work to change the second parameter to `Result?` too instead of `Optional<Result>`?


<!-- Sent from Reviewable.io -->

2021-08-02 23:29 UTC, yunyeng reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/171)* status: all files reviewed, 3 unresolved discussions (waiting on @efoxepstein, @oliver-amzn, and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ClaimReadyExchangeStep.kt, line 49 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/171#-Mg7p_E-EP6EIEUYC8_y:-Mg8Bk3J7T1CjXvR1YRk:bc712bh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/04a00cedbf3f0c8d4e2c7412325524c19620ffa6/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ClaimReadyExchangeStep.kt#L49)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Out of curiosity (and I won't block the PR with this) but does it work to change the second parameter to `Result?` too instead of `Optional<Result>`?
</blockquote></details>

SpannerWriter says buildResult always returns non-null type.


<!-- Sent from Reviewable.io -->

2021-08-02 23:30 UTC, efoxepstein approved these changes
> Reviewed 1 of 1 files at r11.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/171)* status: all files reviewed, 2 unresolved discussions (waiting on @oliver-amzn and @wangyaopw)



<!-- Sent from Reviewable.io -->

2021-08-02 23:34 UTC, yunyeng reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/171)* status: all files reviewed, 2 unresolved discussions (waiting on @oliver-amzn and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/common/DateUtil.kt, line 15 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/171#-Mft7xZB83pwh9svdJiz:-Mg8Cxem-R79khNn6g8G:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b64b1893a1a7006710aa9baa4582da81c57e466b/src/main/kotlin/org/wfanet/measurement/common/DateUtil.kt#L15)):*
<details><summary><i>Previously, yunyeng (Yunus Yen) wrote…</i></summary><blockquote>

Moved to common-jvm. I believe that code are used by multiple repos.
</blockquote></details>

Done.
___
*[src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ClaimReadyExchangeStepTest.kt, line 139 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/171#-MftCOZBD5QLnaVSbJD3:-Mg8Cylb5A8QPpIcVPRM:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b64b1893a1a7006710aa9baa4582da81c57e466b/src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ClaimReadyExchangeStepTest.kt#L139)):*
<details><summary><i>Previously, yunyeng (Yunus Yen) wrote…</i></summary><blockquote>

This was discussed offline. I will update the tests once we have the RecurringExchange.get/create methods for test helpers.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-02 23:37 UTC, efoxepstein approved these changes
> Dismissed @wangyaopw from 2 discussions.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/171)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @oliver-amzn)



<!-- Sent from Reviewable.io -->

2021-08-02 23:37 UTC, efoxepstein approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/171)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @oliver-amzn)



<!-- Sent from Reviewable.io -->

2021-08-02 23:38 UTC, yunyeng reviewed
> Reviewed 2 of 24 files at r1, 4 of 26 files at r2, 7 of 15 files at r3, 7 of 15 files at r4, 6 of 11 files at r7, 3 of 4 files at r8, 1 of 3 files at r9, 2 of 2 files at r10, 1 of 1 files at r11.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/171)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @oliver-amzn)



<!-- Sent from Reviewable.io -->

2021-08-03 16:18 UTC, wangyaopw approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/171)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @oliver-amzn)



<!-- Sent from Reviewable.io -->

2021-08-03 17:13 UTC, merged