implement public Requisitions service
world-federation-of-advertisers/cross-media-measurement pull request #172
Opened 2021-07-30 23:52 UTC by tristanvuong2021

2021-08-02 21:26 UTC, SanjayVas requested changes
> Reviewed 8 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/172)* status: 8 of 9 files reviewed, 10 unresolved discussions (waiting on @tristanvuong2021)

___
*[WORKSPACE, line 61 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/172#-Mg6sQWv9YlYFFXtxrUE:-Mg6sQWw5OOErCombWeI:bd8zol8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/112767d1e7f0aaee6fe70b369a4771f3a0da6ba3/WORKSPACE#L61)):*
> ```Starlark
> wfa_repo_archive(
>     name = "wfa_measurement_proto",
>     commit = "7c954985a7e2e44b6a82c6039e61ae80137be6e9",
> ```

Use version when updating now. I went ahead and created an initial v0.1.0 release.

See how wfa_common_jvm is defined for an example.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt, line 40 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/172#-Mg7eu42AohKEIJCqDhS:-Mg7eu42AohKEIJCqDhT:b-92nu3c) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/112767d1e7f0aaee6fe70b369a4771f3a0da6ba3/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt#L40)):*
> ```
> State
> ```
nit: keep all the non-qualified conflicting imports from the same package, in this case the public v2alpha one.

e.g. it's okay to import `org.wfanet.measurement.api.v2alpha.Requisition.State` but the Kingdom internal one should be qualified using `InternalRequisition.State` or be imported with an `InternalState` alias.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt, line 55 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/172#-Mg6xgDj4oDbjybj-Ujt:-Mg6x2wECxnddZ6CD-Mu:b-xuzosz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/112767d1e7f0aaee6fe70b369a4771f3a0da6ba3/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt#L55)):*
> ```Kotlin
>     val pageSize =
>       when {
>         request.pageSize < 1 -> 1
> ```

We probably want a default page size that's bigger than 1. I realized we forgot to pick/document default and max sizes in the service declaration.

1000 is probably fine for a max. Maybe 50-100 for a default?
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt, line 60 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/172#-Mg7GGsNDOIAVTkoVhPH:-Mg7GGsNDOIAVTkoVhPI:bvhn375) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/112767d1e7f0aaee6fe70b369a4771f3a0da6ba3/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt#L60)):*
> ```Kotlin
>       }
> 
>     /**
> ```

nit: Use regular comments rather than KDoc syntax for local variables.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt, line 61 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/172#-Mg7jVtHBskYopclbPwC:-Mg7jVtHBskYopclbPwD:bu2zinq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/112767d1e7f0aaee6fe70b369a4771f3a0da6ba3/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt#L61)):*
> ```
> StreamRequisitionsRequest filter depends on whether the page token is present or not
> ```
This is incorrect. Instead, the user is expected to keep the filter the same across requests for subsequent pages. Therefore, it is safe to just use the filter params from the request.

See https://google.aip.dev/158
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt, line 66 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/172#-Mg7G-UtBFstDpMbX2AJ:-Mg7G-UtBFstDpMbX2AK:bogu5t3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/112767d1e7f0aaee6fe70b369a4771f3a0da6ba3/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt#L66)):*
> ```Kotlin
>      */
>     val streamRequest =
>       StreamRequisitionsRequest.newBuilder()
> ```

Did you not also want to define a `buildStreamRequisitionsRequest` function?
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt, line 151 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/172#-Mg7chQpBetuy-GBUWYt:-Mg7chQpBetuy-GBUWYu:buynmgo) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/112767d1e7f0aaee6fe70b369a4771f3a0da6ba3/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt#L151)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>     name = externalIdToApiId(externalRequisitionId)
>     measurement = externalIdToApiId(externalMeasurementId)
>     measurementConsumerCertificate =
>       externalIdToApiId(parentMeasurement.externalMeasurementConsumerCertificateId)
> ```
</details>

These are all resource names, not IDs. Use the corresponding Key types to construct them.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt, line 206 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/172#-Mg7fmoh5F5Aer1nvm9T:-Mg7fmoh5F5Aer1nvm9U:bn0ij1n) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/112767d1e7f0aaee6fe70b369a4771f3a0da6ba3/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt#L206)):*
> ```Kotlin
>     InternalRefusal.Justification.UNFULFILLABLE -> Refusal.Justification.UNFULFILLABLE
>     InternalRefusal.Justification.DECLINED -> Refusal.Justification.DECLINED
>     else -> Refusal.Justification.JUSTIFICATION_UNSPECIFIED
> ```

Use exhaustive `when` expression for these enums (i.e. no `else` branch), so that we get a compilation error if a case isn't explicitly covered.

See https://kotlinlang.org/docs/control-flow.html#when-expression
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt, line 273 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/172#-Mg7dFBO57RriW5ayI1j:-Mg7dFBO57RriW5ayI1k:b-7koyl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/112767d1e7f0aaee6fe70b369a4771f3a0da6ba3/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt#L273)):*
> ```
> MutableMap.MutableEntry
> ```
Since you're not mutating and `MutableEntry` is extended from `Entry`, this can be `Map.Entry`.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt, line 281 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/172#-Mg7i5r826ensTRwP3AX:-Mg7i5r826ensTRwP3AY:b-ernfox) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/112767d1e7f0aaee6fe70b369a4771f3a0da6ba3/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt#L281)):*
> ```Kotlin
> 
> internal inline fun buildPageToken(fill: (@Builder PageToken.Builder).() -> Unit) =
>   PageToken.newBuilder().apply(fill).build().toByteArray().base64UrlEncode()
> ```

Internal service proto messages can evolve independently from the public API. Therefore, round-tripping a serialized internal message is unsafe. Instead, the way you construct a page token must be stable for a given public API version.

Since the filter is expected to be the same across requests for different pages, you can just serialize and enco [...]

2021-08-03 17:52 UTC, tristanvuong2021 commented
___
*[WORKSPACE, line 61 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/172#-Mg6sQWv9YlYFFXtxrUE:-MgC8063ESXvmDPpYfUc:bovbvuq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/112767d1e7f0aaee6fe70b369a4771f3a0da6ba3/WORKSPACE#L61)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Use version when updating now. I went ahead and created an initial v0.1.0 release.

See how wfa_common_jvm is defined for an example.
</blockquote></details>

Swapped out commit with version.


<!-- Sent from Reviewable.io -->

2021-08-03 17:52 UTC, tristanvuong2021 commented
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt, line 40 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/172#-Mg7eu42AohKEIJCqDhS:-MgC8Gs49alrvMZILUDC:bulrmns) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/112767d1e7f0aaee6fe70b369a4771f3a0da6ba3/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt#L40)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> State
> ```
nit: keep all the non-qualified conflicting imports from the same package, in this case the public v2alpha one.

e.g. it's okay to import `org.wfanet.measurement.api.v2alpha.Requisition.State` but the Kingdom internal one should be qualified using `InternalRequisition.State` or be imported with an `InternalState` alias.
</blockquote></details>

Used InternalState.


<!-- Sent from Reviewable.io -->

2021-08-03 17:53 UTC, tristanvuong2021 commented
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt, line 55 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/172#-Mg6xgDj4oDbjybj-Ujt:-MgC8N1TANTvAswS5P9R:b-jm46dg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/112767d1e7f0aaee6fe70b369a4771f3a0da6ba3/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt#L55)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

We probably want a default page size that's bigger than 1. I realized we forgot to pick/document default and max sizes in the service declaration.

1000 is probably fine for a max. Maybe 50-100 for a default?
</blockquote></details>

Set the min page size to 50.


<!-- Sent from Reviewable.io -->

2021-08-03 17:53 UTC, tristanvuong2021 commented
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt, line 61 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/172#-Mg7jVtHBskYopclbPwC:-MgC8Zbl7Q7ZWRJ901QB:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/112767d1e7f0aaee6fe70b369a4771f3a0da6ba3/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt#L61)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> StreamRequisitionsRequest filter depends on whether the page token is present or not
> ```
This is incorrect. Instead, the user is expected to keep the filter the same across requests for subsequent pages. Therefore, it is safe to just use the filter params from the request.

See https://google.aip.dev/158
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-03 17:54 UTC, tristanvuong2021 commented
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt, line 66 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/172#-Mg7G-UtBFstDpMbX2AJ:-MgC8dOf2-uRxDaD874l:b-1wy4j2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/112767d1e7f0aaee6fe70b369a4771f3a0da6ba3/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt#L66)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Did you not also want to define a `buildStreamRequisitionsRequest` function?
</blockquote></details>

I defined a buildStreamRequisitionsRequest function.


<!-- Sent from Reviewable.io -->

2021-08-03 17:55 UTC, tristanvuong2021 commented
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt, line 281 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/172#-Mg7i5r826ensTRwP3AX:-MgC8xzgD87lSPd3W7NR:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/112767d1e7f0aaee6fe70b369a4771f3a0da6ba3/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt#L281)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Internal service proto messages can evolve independently from the public API. Therefore, round-tripping a serialized internal message is unsafe. Instead, the way you construct a page token must be stable for a given public API version.

Since the filter is expected to be the same across requests for different pages, you can just serialize and encode the `created_after` timestamp.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-03 17:56 UTC, tristanvuong2021 commented
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt, line 273 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/172#-Mg7dFBO57RriW5ayI1j:-MgC91Qs8JlebaeUU1Mo:bkauwde) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/112767d1e7f0aaee6fe70b369a4771f3a0da6ba3/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt#L273)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> MutableMap.MutableEntry
> ```
Since you're not mutating and `MutableEntry` is extended from `Entry`, this can be `Map.Entry`.
</blockquote></details>

Changed to Map.Entry.


<!-- Sent from Reviewable.io -->

2021-08-03 17:56 UTC, tristanvuong2021 commented
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt, line 206 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/172#-Mg7fmoh5F5Aer1nvm9T:-MgC9CdqB-CSZMbbaYre:b8k633o) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/112767d1e7f0aaee6fe70b369a4771f3a0da6ba3/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt#L206)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Use exhaustive `when` expression for these enums (i.e. no `else` branch), so that we get a compilation error if a case isn't explicitly covered.

See https://kotlinlang.org/docs/control-flow.html#when-expression


</blockquote></details>

Got rid of else branches.


<!-- Sent from Reviewable.io -->

2021-08-03 17:57 UTC, tristanvuong2021 commented
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt, line 151 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/172#-Mg7chQpBetuy-GBUWYt:-MgC9M0gDvPEWFv4yqmf:blryw6i) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/112767d1e7f0aaee6fe70b369a4771f3a0da6ba3/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt#L151)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
>     name = externalIdToApiId(externalRequisitionId)
>     measurement = externalIdToApiId(externalMeasurementId)
>     measurementConsumerCertificate =
>       externalIdToApiId(parentMeasurement.externalMeasurementConsumerCertificateId)
> ```
These are all resource names, not IDs. Use the corresponding Key types to construct them.
</blockquote></details>

Created Resource Keys with the Ids to get the names.


<!-- Sent from Reviewable.io -->

2021-08-03 18:00 UTC, tristanvuong2021 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/172)* status: 6 of 9 files reviewed, 8 unresolved discussions (waiting on @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt, line 55 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/172#-Mg6xgDj4oDbjybj-Ujt:-MgC9mg_6g3PwGZTi7eZ:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/112767d1e7f0aaee6fe70b369a4771f3a0da6ba3/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt#L55)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Set the min page size to 50.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt, line 151 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/172#-Mg7chQpBetuy-GBUWYt:-MgC9kHD49iDkqtXeqd8:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/112767d1e7f0aaee6fe70b369a4771f3a0da6ba3/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt#L151)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Created Resource Keys with the Ids to get the names.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt, line 206 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/172#-Mg7fmoh5F5Aer1nvm9T:-MgC9jds5c_enVXxZb9c:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/112767d1e7f0aaee6fe70b369a4771f3a0da6ba3/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt#L206)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Got rid of else branches.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt, line 273 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/172#-Mg7dFBO57RriW5ayI1j:-MgC9iu48wvOuSBBAAAU:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/112767d1e7f0aaee6fe70b369a4771f3a0da6ba3/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt#L273)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Changed to Map.Entry.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-03 19:24 UTC, SanjayVas requested changes
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/172)* status: all files reviewed, 5 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt, line 55 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/172#-Mg6xgDj4oDbjybj-Ujt:-MgCImdc1NXJUe06ykps:bdg7t4w) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/112767d1e7f0aaee6fe70b369a4771f3a0da6ba3/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt#L55)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Sorry, what I meant was to pick something like 50 or 100 for the default, but keep 1000 for the max.

These are default and max rather than min and max.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt, line 210 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/172#-MgCMmEu6x1hO3OC2Zvr:-MgCMmEu6x1hO3OC2Zvs:bgoj98g) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f467e01082bc04facdc6433348103abde230ac42/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt#L210)):*
> ```Kotlin
>     InternalRefusal.Justification.JUSTIFICATION_UNSPECIFIED ->
>       Refusal.Justification.JUSTIFICATION_UNSPECIFIED
>     InternalRefusal.Justification.UNRECOGNIZED -> Refusal.Justification.UNRECOGNIZED
> ```

UNRECOGNIZED can never be set explicitly and only comes from proto parsing. Map both `JUSTIFICATION_UNSPECIFIED` and `UNRECOGNIZED` to `JUSTIFICATION_UNSPECIFIED`.
___
*[src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsServiceTest.kt, line 140 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/172#-MgCRPrwDPIleeEf-oJ3:-MgCRPrwDPIleeEf-oJ4:b-s4ufex) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f467e01082bc04facdc6433348103abde230ac42/src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsServiceTest.kt#L140)):*
> ```Kotlin
>   }
>   val entry = INTERNAL_REQUISITION.duchiesMap[DUCHIES_MAP_KEY]
>   if (entry != null) {
> ```

Since this is coming from a constant, you know this cannot happen. Just coerce to non-null using `!!`.
___
*[src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsServiceTest.kt, line 159 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/172#-MgCRdGT7os57oOcEVUw:-MgCRdGT7os57oOcEVUx:b-mk54h0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f467e01082bc04facdc6433348103abde230ac42/src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsServiceTest.kt#L159)):*
> ```Kotlin
>   }
>   state = State.FULFILLED
>   refusal = Refusal.getDefaultInstance()
> ```

Just leave this unset, as `refusal` should only be set when state is `REFUSED`.


<!-- Sent from Reviewable.io -->

2021-08-03 21:03 UTC, tristanvuong2021 commented
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt, line 55 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/172#-Mg6xgDj4oDbjybj-Ujt:-MgCopsN2HBfahWWQ_1A:b-l7hq83) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/112767d1e7f0aaee6fe70b369a4771f3a0da6ba3/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt#L55)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Sorry, what I meant was to pick something like 50 or 100 for the default, but keep 1000 for the max.

These are default and max rather than min and max.
</blockquote></details>

I added a default in addition to a min.


<!-- Sent from Reviewable.io -->

2021-08-03 21:04 UTC, tristanvuong2021 commented
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt, line 210 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/172#-MgCMmEu6x1hO3OC2Zvr:-MgCpBi76RYlYsAw7A7V:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f467e01082bc04facdc6433348103abde230ac42/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt#L210)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

UNRECOGNIZED can never be set explicitly and only comes from proto parsing. Map both `JUSTIFICATION_UNSPECIFIED` and `UNRECOGNIZED` to `JUSTIFICATION_UNSPECIFIED`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-03 21:04 UTC, tristanvuong2021 commented
___
*[src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsServiceTest.kt, line 140 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/172#-MgCRPrwDPIleeEf-oJ3:-MgCpEIgDQwy8Jnj7Lll:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f467e01082bc04facdc6433348103abde230ac42/src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsServiceTest.kt#L140)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Since this is coming from a constant, you know this cannot happen. Just coerce to non-null using `!!`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-03 21:04 UTC, tristanvuong2021 commented
___
*[src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsServiceTest.kt, line 159 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/172#-MgCRdGT7os57oOcEVUw:-MgCpFl09NhAlDkeb0vA:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f467e01082bc04facdc6433348103abde230ac42/src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsServiceTest.kt#L159)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Just leave this unset, as `refusal` should only be set when state is `REFUSED`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-04 00:12 UTC, SanjayVas requested changes
> Reviewed 4 of 4 files at r4, 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/172)* status: all files reviewed, 2 unresolved discussions (waiting on @tristanvuong2021)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt, line 210 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/172#-MgCMmEu6x1hO3OC2Zvr:-MgDS0u2B_iRa9KYuQMm:bkf1qnp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f467e01082bc04facdc6433348103abde230ac42/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt#L210)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

You did the others and missed this one.
___
*[src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsServiceTest.kt, line 140 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/172#-MgCRPrwDPIleeEf-oJ3:-MgDSYbj-GiPlnPN5Vrb:b-zbno2g) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f467e01082bc04facdc6433348103abde230ac42/src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsServiceTest.kt#L140)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

nit: Move the coercion up so that `entry` has a non-nullable type.
___
*[src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsServiceTest.kt, line 205 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/172#-MgDUJSNA5feU-XtRzdE:-MgDT9bq8LSGS0JH8hGs:brtcrpm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/567411776742775abe70289773bf2893bb07c6f5/src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsServiceTest.kt#L205)):*
> ```Kotlin
>         buildStreamRequisitionsRequest {
>           limit = 2
>           filter = StreamRequisitionsRequest.Filter.getDefaultInstance()
> ```

Add a check to make sure this case isn't hit: Either the parent data provider must be specified or the measurement.


<!-- Sent from Reviewable.io -->

2021-08-04 01:07 UTC, tristanvuong2021 commented
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt, line 210 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/172#-MgCMmEu6x1hO3OC2Zvr:-MgDgy1O7eDevRawaFA3:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f467e01082bc04facdc6433348103abde230ac42/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt#L210)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

You did the others and missed this one.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-04 01:08 UTC, tristanvuong2021 commented
___
*[src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsServiceTest.kt, line 205 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/172#-MgDUJSNA5feU-XtRzdE:-MgDh5PE2u1EPJzd_clg:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/567411776742775abe70289773bf2893bb07c6f5/src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsServiceTest.kt#L205)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Add a check to make sure this case isn't hit: Either the parent data provider must be specified or the measurement.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-04 17:36 UTC, SanjayVas approved these changes
> Reviewed 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/172)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)



<!-- Sent from Reviewable.io -->

2021-08-04 18:38 UTC, tristanvuong2021 commented
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt, line 61 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/172#-MgHMTJp7hlWTEJdx277:-MgHSGGO-69sLw3ssFNI:b5mi7hv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/184d124a3e7f27cf2b1db351c80ff9be4c77adfa/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt#L61)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> request.parent.equals(WILDCARD)
> ```
The entire parent resource name won't be the wildcard character, but rather the DataProvider ID segment within the resource name.

What this means it that `parent` field should always be specified, but may have the form `dataProviders/-`. This means you'll need to parse that field into a DataProviderKey before checking for the wildcard character.
</blockquote></details>

Parsed it first now.


<!-- Sent from Reviewable.io -->

2021-08-04 20:40 UTC, SanjayVas approved these changes
> Reviewed 2 of 2 files at r8.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/172)* status: all files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt, line 66 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/172#-MgHtFfw11WIPXvWkPA6:-MgHtFfw11WIPXvWkPA7:b-tqw4n9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3da36e2df2b05a38bd3bd0deea11f84d2f7211e6/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt#L66)):*
> ```
> request.parent.isNotBlank()
> ```
nit: parent cannot be blank here, as that's checked when parsing it to a resource key


<!-- Sent from Reviewable.io -->

2021-08-05 01:36 UTC, oliver-amzn approved these changes
> Reviewed 3 of 9 files at r1, 3 of 4 files at r4, 1 of 2 files at r8, 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/172)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)



<!-- Sent from Reviewable.io -->

2021-08-05 17:12 UTC, merged