Implement Create and Get Methods for Internal Measurements Service
world-federation-of-advertisers/cross-media-measurement pull request #173
Opened 2021-08-01 04:40 UTC by uakyol

2021-08-05 14:41 UTC, uakyol commented
@SanjayVas working on this PR, it became massive and I decided to split in to 2 parts. This is Part 1. It includes almost complete implementations of:
- CreateMeasurement
- MeasurementReader
- SpannerMeasurementService
- Measurement 

These implementations are not complete because they don't include:
- Populating all the fields of Requisition to the DB
- Reading  all the fields of Requisition and ComputationParticipants from the DB
- Parallel Id generator to be used in tests. 

I added TODOs for each of them in the code and will work on them on couple of separate PRs. These will be involved as well and will make this one really hard to submit. 

Wdyt?

2021-08-05 16:32 UTC, wangyaopw requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/173)* status: 0 of 15 files reviewed, 5 unresolved discussions (waiting on @SanjayVas and @uakyol)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementsService.kt, line 45 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/173#-MgM3kpA6-v31BaxYDAm:-MgM3kpB3JGr5kk7pbno:b7g15ed) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9f9d408036fadd584bc9d095efa0588e7fc3f99e/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementsService.kt#L45)):*
> ```
> KingdomInternalException.Code.CERT_SUBJECT_KEY_ID_ALREADY_EXISTS -> throw e
> ```
nit:move all those that throw e to the end
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt, line 31 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/173#-MgM6apM9_rOTUSyCno6:-MgM6apM9_rOTUSyCno7:b6uyjg8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9f9d408036fadd584bc9d095efa0588e7fc3f99e/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt#L31)):*
> ```
> val measurementId: Long
> ```
is `measurementId` used anywhere in the result? if not, maybe don't return it?
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt, line 103 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/173#-MgM5JoSBYznR9nWR0vX:-MgM5JoSBYznR9nWR0vY:bhia1gc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9f9d408036fadd584bc9d095efa0588e7fc3f99e/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt#L103)):*
> ```Kotlin
>         providedMeasurementId = struct.getString("ProvidedMeasurementId")
>         details = struct.getProtoMessage("MeasurementDetails", Measurement.Details.parser())
>         createTime = struct.getTimestamp("CreateTime").toProto()
> ```

The measurement is missing update_time, external_measurement_consumer_certificate_id, external_protocol_config_id, sate, details_json,

it is best to set the fields following their order in the proto definition, so you know which one is missing.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt, line 107 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/173#-MgM5tD9CKlHg2CAPq1u:-MgM5tD9CKlHg2CAPq1v:bcal18b) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9f9d408036fadd584bc9d095efa0588e7fc3f99e/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt#L107)):*
> ```
> commonMeasurement.build()
> ```
default view should also include the data_providers 
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurement.kt, line 61 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/173#-MgM829K9pUFsswH_5CR:-MgM829K9pUFsswH_5CS:b-2r378j) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9f9d408036fadd584bc9d095efa0588e7fc3f99e/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurement.kt#L61)):*
> ```
>  measurement.getDataProvidersMap()
> ```
maybe use `measurement.getDataProvidersMap().forEach{}` similar to how you create the duchies


<!-- Sent from Reviewable.io -->

2021-08-05 18:50 UTC, SanjayVas requested changes
Sure. Just come up with a better subject than "Thing - Part 1", and clarify what's missing in the body.

> Reviewed 15 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/173#-:-MgMZNmmD3CoMo-4jl8Z:bdlqbh3)* status: all files reviewed, 18 unresolved discussions (waiting on @uakyol)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/DuchyIds.kt, line 24 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/173#-MgMVnfF2qGiFQstYenC:-MgMVnfF2qGiFQstYenD:bbgi8ro) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9f9d408036fadd584bc9d095efa0588e7fc3f99e/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/DuchyIds.kt#L24)):*
> ```Kotlin
>   private lateinit var entries: List<Entry>
> 
>   fun getEntries() = entries
> ```

Just make the entries property public with a private setter rather than introducing an accessor function.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt, line 31 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/173#-MgMY1y3BkAqYa-39zD_:-MgMY1y3BkAqYa-39zDa:b-4347kv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9f9d408036fadd584bc9d095efa0588e7fc3f99e/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt#L31)):*
> ```Kotlin
> class MeasurementReader(private val view: Measurement.View) :
>   SpannerReader<MeasurementReader.Result>() {
>   data class Result(val measurement: Measurement, val measurementId: Long)
> ```

nit: blank lines to separate data class
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt, line 33 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/173#-MgMXobp3TKZZG-mzBVh:-MgMXobq9fqXC7aXxH52:b-tvkd0h) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9f9d408036fadd584bc9d095efa0588e7fc3f99e/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt#L33)):*
> ```Kotlin
>   data class Result(val measurement: Measurement, val measurementId: Long)
> 
>   companion object {
> ```

nit: put companion object at end of class
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt, line 96 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/173#-MgMYmghD3Vh9WxlZ5hB:-MgMYmghD3Vh9WxlZ5hC:b2nt41x) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9f9d408036fadd584bc9d095efa0588e7fc3f99e/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt#L96)):*
> ```Kotlin
> 
>   private fun buildMeasurement(struct: Struct): Measurement {
>     val commonMeasurement =
> ```

What's the "common" part mean here? Is it meant to be what's in common between the views? If so, this is inaccurate as it's a builder which gets conditionally mutated with the non-common fields later.

Perhaps just `measurementBuilder`? That name would make the type obvious, as otherwise you should specify the type explicitly here for clarity.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt, line 109 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/173#-MgMXFTx7bLHJ29rbx3s:-MgMXFTx7bLHJ29rbx3t:b-112hcg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9f9d408036fadd584bc9d095efa0588e7fc3f99e/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt#L109)):*
> ```
> TODO(@google.com uakyol)
> ```
Wrong format. Preferred one would be `TODO(@uakyol)` to refer to your GitHub username
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt, line 153 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/173#-MgMYWbU5kFnPSScPuEw:-MgMYWbU5kFnPSScPuEx:b9j8ufy) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9f9d408036fadd584bc9d095efa0588e7fc3f99e/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt#L153)):*
> ```
> this.
> ```
nit: is the `this.` qualification necessary here?
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/BUILD.bazel, line 12 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/173#-MgMZqmD6vSFAfu22dO-:-MgMZqmD6vSFAfu22dO0:bi1v6y0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9f9d408036fadd584bc9d095efa0588e7fc3f99e/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/BUILD.bazel#L12)):*
> ```Starlark
>     srcs = glob(
>         ["*.kt"],
>         exclude = [
> ```

nit: you can create a separate constant list for the legacy sources and reuse that rather than listing them all twice.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurement.kt, line 57 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/173#-MgM_4hf7ROCgbQuop-4:-MgM_4hf7ROCgbQuop-5:b85z9yz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9f9d408036fadd584bc9d095efa0588e7fc3f99e/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurement.kt#L57)):*
> ```
> measurment
> ```
nit: measurement
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurement.kt, line 86 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/173#-MgM_ebv01brpI26Phx3:-MgM_ebv01brpI26Phx4:bn6nqiv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9f9d408036fadd584bc9d095efa0588e7fc3f99e/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurement.kt#L86)):*
> ```Kotlin
>   }
> 
>   private suspend fun TransactionScope.createNewMeasurement(
> ```

If you generate the internal ID in the caller and pass it in, then you don't need a data class to return it along with the Measurement
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurement.kt, line 129 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/173#-MgM_pJW1EnkYzZcJw8a:-MgM_pJW1EnkYzZcJw8b:b8edeci) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9f9d408036fadd584bc9d095efa0588e7fc3f99e/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurement.kt#L129)):*
> ```Kotlin
>         set("DuchyId" to duchyId)
>         set("State" to ComputationParticipant.State.CREATED)
>         // set("ParticipantDetails" to measurement.details)
> ```

Don't submit commented code
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt, line 105 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/173#-MgMaLiM7PMSOofiFxkl:-MgMaLiM7PMSOofiFxkm:bmfj97e) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9f9d408036fadd584bc9d095efa0588e7fc3f99e/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt#L105)):*
> ```
> 2
> ```
nit: v2alpha
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt, line 294 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measu [...]

2021-08-05 21:32 UTC, uakyol reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/173)* status: 3 of 22 files reviewed, 11 unresolved discussions (waiting on @SanjayVas and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/DuchyIds.kt, line 24 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/173#-MgMVnfF2qGiFQstYenC:-MgMr1nk4XiL_fgw7Q9k:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9f9d408036fadd584bc9d095efa0588e7fc3f99e/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/DuchyIds.kt#L24)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Just make the entries property public with a private setter rather than introducing an accessor function.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt, line 31 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/173#-MgM6apM9_rOTUSyCno6:-MgNCmD7CsEQIA4yldlC:boq2cbc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9f9d408036fadd584bc9d095efa0588e7fc3f99e/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt#L31)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
> val measurementId: Long
> ```
is `measurementId` used anywhere in the result? if not, maybe don't return it?
</blockquote></details>

I was using it later but removed the data class per Sanjay's other comment.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt, line 96 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/173#-MgMYmghD3Vh9WxlZ5hB:-MgMou-qBkWLBJw9IRRV:b-dl1njv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9f9d408036fadd584bc9d095efa0588e7fc3f99e/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt#L96)):*
> measurementBuilder
thank you
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt, line 103 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/173#-MgM5JoSBYznR9nWR0vX:-MgNC1bdA5UlgPZb1bZq:b-898wwt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9f9d408036fadd584bc9d095efa0588e7fc3f99e/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt#L103)):*
> Thanks Yao, will tackle that at a later PR. added TODO
Thanks Yao, will tackle that at a later PR. added TODO
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt, line 107 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/173#-MgM5tD9CKlHg2CAPq1u:-MgMpzvR6CYYSaTlewqO:bvhhm04) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9f9d408036fadd584bc9d095efa0588e7fc3f99e/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt#L107)):*
> ```
>  // TODO(@google.com uakyol): populate all the relevant fields for a requisition.
> ```
Thanks Yao, will tackle that at a later PR. added TODO
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt, line 109 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/173#-MgMXFTx7bLHJ29rbx3s:-MgMmbJX3c6GcrdjwWwM:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9f9d408036fadd584bc9d095efa0588e7fc3f99e/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt#L109)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> TODO(@google.com uakyol)
> ```
Wrong format. Preferred one would be `TODO(@uakyol)` to refer to your GitHub username
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurement.kt, line 61 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/173#-MgM829K9pUFsswH_5CR:-MgMp8Tm2Bm2HIm7mSMT:b-p78g11) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9f9d408036fadd584bc9d095efa0588e7fc3f99e/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurement.kt#L61)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
>  measurement.getDataProvidersMap()
> ```
maybe use `measurement.getDataProvidersMap().forEach{}` similar to how you create the duchies
</blockquote></details>

I tried this a lot I get the error that I can not call suspend functions from forEach. Still couldn't figure out why the other works and not this. Do you know why?
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurement.kt, line 86 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/173#-MgM_ebv01brpI26Phx3:-MgNDC2M5exmT_1y_Uj0:b-bfl8um) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9f9d408036fadd584bc9d095efa0588e7fc3f99e/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurement.kt#L86)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

If you generate the internal ID in the caller and pass it in, then you don't need a data class to return it along with the Measurement
</blockquote></details>

I see thanks
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurement.kt, line 129 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/173#-MgM_pJW1EnkYzZcJw8a:-MgMnPPF3IyWjVqxTiiI:b-1cyu7w) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9f9d408036fadd584bc9d095efa0588e7fc3f99e/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurement.kt#L129)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Don't submit commented code
</blockquote></details>

thank you
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt, line 294 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/173#-MgMb0rLDyNe54M_yEiQ:-MgMtWzR9bZZF1NzFCTB:by4995h) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9f9d408036fadd584bc9d095efa0588e7fc3f99e/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt#L294)):*
> SUT
I was thinking the same. We should not impose with these tests an order on the generation of these ids. Thank you for explaining it and giving a solution. I changed the code to reflect this. 

Lets talk about this: For the requisition, as you can see I populated the externalMeasurementId, externalMeasurementConsumerId and externalRequisitionId. 
However, since in the test, we don't have access to externalRequisitonId, I only match the other 2 fields by using comparingExpectedFieldsOnly(). Does this look good to you? 
I can maybe add an additional check that externalRequisitionId != 0. That's the best we can do I think without knowing that id.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/LegacyCreateRequisition.kt, line 42 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/173#-MgMWhrq5UmrdgH7lda [...]

2021-08-05 22:13 UTC, wangyaopw requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/173)* status: 3 of 22 files reviewed, 10 unresolved discussions (waiting on @SanjayVas, @uakyol, and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt, line 103 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/173#-MgM5JoSBYznR9nWR0vX:-MgNMZCG1ZzN0m1fIrlq:b-k151b8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9f9d408036fadd584bc9d095efa0588e7fc3f99e/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt#L103)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

> Thanks Yao, will tackle that at a later PR. added TODO
Thanks Yao, will tackle that at a later PR. added TODO
</blockquote></details>

Is there a technical reason that these can not be added in this PR? Breaking different methods to PRs make sense. But I feel it is best to get the same method completed done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurement.kt, line 61 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/173#-MgM829K9pUFsswH_5CR:-MgNMGlh5LvpcHzFlj4E:b-ch7cjw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9f9d408036fadd584bc9d095efa0588e7fc3f99e/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurement.kt#L61)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

I tried this a lot I get the error that I can not call suspend functions from forEach. Still couldn't figure out why the other works and not this. Do you know why?
</blockquote></details>

Try
```
 measurement.dataProvidersMap.forEach {
      val dataProviderId =
        DataProviderReader()
          .readExternalIdOrNull(transactionContext, ExternalId(it.key))
          ?.dataProviderId
          ?: throw KingdomInternalException(KingdomInternalException.Code.DATA_PROVIDER_NOT_FOUND)
      createRequisition(
        it.key,
        measurementConsumerId,
        measurementId,
        dataProviderId
      )
    }
```


<!-- Sent from Reviewable.io -->

2021-08-05 23:13 UTC, SanjayVas requested changes
> Reviewed 19 of 19 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/173)* status: all files reviewed, 6 unresolved discussions (waiting on @SanjayVas, @uakyol, and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt, line 50 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/173#-MgNZmmtDm8317IOHgMr:-MgNZmmtDm8317IOHgMs:bb3ur1y) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d9925c6584b715288212544538b46d299e2af514/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt#L50)):*
> ```
> TODO(@google.com uakyol)
> ```
Incorrect TODO format, here and elsewhere

`TODO(@uakyol)` instead
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt, line 294 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/173#-MgMb0rLDyNe54M_yEiQ:-MgN_VHnCvJOVCzqu5Kv:bstv4cs) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9f9d408036fadd584bc9d095efa0588e7fc3f99e/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt#L294)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

> SUT
I was thinking the same. We should not impose with these tests an order on the generation of these ids. Thank you for explaining it and giving a solution. I changed the code to reflect this. 

Lets talk about this: For the requisition, as you can see I populated the externalMeasurementId, externalMeasurementConsumerId and externalRequisitionId. 
However, since in the test, we don't have access to externalRequisitonId, I only match the other 2 fields by using comparingExpectedFieldsOnly(). Does this look good to you? 
I can maybe add an additional check that externalRequisitionId != 0. That's the best we can do I think without knowing that id.
</blockquote></details>

Basically that's what I meant. Drop the fields that you don't know the value of and use `comparingExpectedFieldsOnly`, then add additional checks for those fields. e.g. making sure they're set, which ones should be the same, which ones should not be the same, etc.


<!-- Sent from Reviewable.io -->

2021-08-05 23:58 UTC, wangyaopw reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/173)* status: all files reviewed, 6 unresolved discussions (waiting on @SanjayVas, @uakyol, and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt, line 31 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/173#-MgM6apM9_rOTUSyCno6:-MgNjzn0AQavEq1bdvLJ:big08lm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9f9d408036fadd584bc9d095efa0588e7fc3f99e/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt#L31)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

I was using it later but removed the data class per Sanjay's other comment.
</blockquote></details>

I am a little confused now. Did you remove the data class or not? it is still in this file.


<!-- Sent from Reviewable.io -->

2021-08-06 17:08 UTC, uakyol reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/173)* status: 20 of 22 files reviewed, 6 unresolved discussions (waiting on @SanjayVas and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt, line 31 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/173#-MgM6apM9_rOTUSyCno6:-MgOn2XE0aYd698wWlkh:bfv2qod) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9f9d408036fadd584bc9d095efa0588e7fc3f99e/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt#L31)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

I am a little confused now. Did you remove the data class or not? it is still in this file.
</blockquote></details>

Ah, sorry Yao, I still am not used to Reviewable UI, I thought we were talking about CreateMeasurement. Yes, measurementId is not used here. I just added it since it is a pattern with these Readers. We use it when a creator needs to get the internal id of a resource. Every single other Reader follow this pattern. I can keep it or leave it wdyt?
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt, line 103 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/173#-MgM5JoSBYznR9nWR0vX:-MgOnktsBBWg3viu4kU3:bihyc5y) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9f9d408036fadd584bc9d095efa0588e7fc3f99e/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt#L103)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

Is there a technical reason that these can not be added in this PR? Breaking different methods to PRs make sense. But I feel it is best to get the same method completed done.
</blockquote></details>

There is no technical reason and I agree that it would be the better scenario to finish the method here. The main reason is I have lots of questions about how we are going to construct/read/write these fields and I think it will be involved. I just want to make sure this big chunk of code doesnt get stuck. I felt it is like seperation of concerns  1st PR : Deals with the skeleton to read/write to db / service implementation / test skeleton 2nd PR : Actual logic to fill the fields. Wdyt? If you feel strongly, I can try to tackle the second part here.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt, line 50 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/173#-MgNZmmtDm8317IOHgMr:-MgOlqaID5EztV-hZ3OE:bozqn87) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d9925c6584b715288212544538b46d299e2af514/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt#L50)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> TODO(@google.com uakyol)
> ```
Incorrect TODO format, here and elsewhere

`TODO(@uakyol)` instead
</blockquote></details>

:facepalm: thanks
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurement.kt, line 61 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/173#-MgM829K9pUFsswH_5CR:-MgOmXFI4I6Jog4rfMoR:b39fqb4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9f9d408036fadd584bc9d095efa0588e7fc3f99e/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurement.kt#L61)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

Try
```
 measurement.dataProvidersMap.forEach {
      val dataProviderId =
        DataProviderReader()
          .readExternalIdOrNull(transactionContext, ExternalId(it.key))
          ?.dataProviderId
          ?: throw KingdomInternalException(KingdomInternalException.Code.DATA_PROVIDER_NOT_FOUND)
      createRequisition(
        it.key,
        measurementConsumerId,
        measurementId,
        dataProviderId
      )
    }
```
</blockquote></details>

worked, thank you so much!
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt, line 294 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/173#-MgMb0rLDyNe54M_yEiQ:-MgRQhGwCbg9MJoBcDxo:b-slzo7x) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9f9d408036fadd584bc9d095efa0588e7fc3f99e/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt#L294)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Basically that's what I meant. Drop the fields that you don't know the value of and use `comparingExpectedFieldsOnly`, then add additional checks for those fields. e.g. making sure they're set, which ones should be the same, which ones should not be the same, etc.
</blockquote></details>

thank you! 


<!-- Sent from Reviewable.io -->

2021-08-06 17:27 UTC, wangyaopw approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/173)* status: 20 of 22 files reviewed, 5 unresolved discussions (waiting on @SanjayVas, @uakyol, and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt, line 31 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/173#-MgM6apM9_rOTUSyCno6:-MgRVBxA-0-i5E0iJxtm:br4r30b) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9f9d408036fadd584bc9d095efa0588e7fc3f99e/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt#L31)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

Ah, sorry Yao, I still am not used to Reviewable UI, I thought we were talking about CreateMeasurement. Yes, measurementId is not used here. I just added it since it is a pattern with these Readers. We use it when a creator needs to get the internal id of a resource. Every single other Reader follow this pattern. I can keep it or leave it wdyt?
</blockquote></details>

we can keep it. doesn't hurt anyway
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt, line 103 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/173#-MgM5JoSBYznR9nWR0vX:-MgRUqN-8alXu5gyM_73:b-dr6lzr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9f9d408036fadd584bc9d095efa0588e7fc3f99e/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt#L103)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

There is no technical reason and I agree that it would be the better scenario to finish the method here. The main reason is I have lots of questions about how we are going to construct/read/write these fields and I think it will be involved. I just want to make sure this big chunk of code doesnt get stuck. I felt it is like seperation of concerns  1st PR : Deals with the skeleton to read/write to db / service implementation / test skeleton 2nd PR : Actual logic to fill the fields. Wdyt? If you feel strongly, I can try to tackle the second part here.
</blockquote></details>

sgtm. I was thinking that you only planned to add the requisions and computationParticipants the part two.


<!-- Sent from Reviewable.io -->

2021-08-06 19:16 UTC, SanjayVas requested changes
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/173)* status: all files reviewed, 2 unresolved discussions (waiting on @oliver-amzn, @uakyol, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurement.kt, line 64 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/173#-MgRsoWsBkKpC-CNvYob:-MgRseb6-FStJZvxt_rx:bf409s6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/31c6dfee625d1f7c3546285da29380ba3dc76e4f/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurement.kt#L64)):*
> ```
> ExternalId(it.key)
> ```
nit: For clarity, extract this to a variable and use its `value` property where needed below
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt, line 294 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/173#-MgMb0rLDyNe54M_yEiQ:-MgRt8iy9B3Y30fMW3y5:bb0xb6a) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9f9d408036fadd584bc9d095efa0588e7fc3f99e/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt#L294)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

thank you! 
</blockquote></details>

Are you still working on this part?


<!-- Sent from Reviewable.io -->

2021-08-06 19:54 UTC, uakyol reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/173)* status: all files reviewed, 2 unresolved discussions (waiting on @oliver-amzn, @SanjayVas, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurement.kt, line 64 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/173#-MgRsoWsBkKpC-CNvYob:-MgS0Qc12DgixnErnjf8:b-cbplcj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/31c6dfee625d1f7c3546285da29380ba3dc76e4f/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurement.kt#L64)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> ExternalId(it.key)
> ```
nit: For clarity, extract this to a variable and use its `value` property where needed below
</blockquote></details>

sorry Sanjay I couldn't understand this comment. ExternalId(it.key) is only used for this readExternalIdOrNull function. And that func needs an ExternalId not a long which is what you get when you do ex_id.value. Can you help me understand what you meant.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt, line 294 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/173#-MgMb0rLDyNe54M_yEiQ:-MgS-nvw-PP6gDcR1Lk-:b-5903vw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9f9d408036fadd584bc9d095efa0588e7fc3f99e/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt#L294)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Are you still working on this part?
</blockquote></details>

I want to leave it as is for now and add finish the test in the next PR where I populate the fields. wdyt?


<!-- Sent from Reviewable.io -->

2021-08-06 21:38 UTC, SanjayVas requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/173)* status: all files reviewed, 2 unresolved discussions (waiting on @oliver-amzn, @uakyol, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurement.kt, line 64 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/173#-MgRsoWsBkKpC-CNvYob:-MgSO-h78GQ-pcUMZjIS:b-1mpp1b) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/31c6dfee625d1f7c3546285da29380ba3dc76e4f/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurement.kt#L64)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

sorry Sanjay I couldn't understand this comment. ExternalId(it.key) is only used for this readExternalIdOrNull function. And that func needs an ExternalId not a long which is what you get when you do ex_id.value. Can you help me understand what you meant.
</blockquote></details>

```
val externalDataProviderId = ExternalId(it.key)
```

Then later in the `createRequisition` call:

```
createRequisition(externalDataProviderId.value, measurementConsumerId, measurementId, dataProviderId)
```
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt, line 294 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/173#-MgMb0rLDyNe54M_yEiQ:-MgSNssPCd8c2LjF-BUK:bp3zfe0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9f9d408036fadd584bc9d095efa0588e7fc3f99e/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt#L294)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

I want to leave it as is for now and add finish the test in the next PR where I populate the fields. wdyt?
</blockquote></details>

That's okay as long as you update this TODO to be accurate.


<!-- Sent from Reviewable.io -->

2021-08-09 18:05 UTC, uakyol reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/173)* status: 20 of 22 files reviewed, 1 unresolved discussion (waiting on @oliver-amzn, @SanjayVas, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt, line 294 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/173#-MgMb0rLDyNe54M_yEiQ:-Mgg4PAo0VO3zVBlZKBz:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9f9d408036fadd584bc9d095efa0588e7fc3f99e/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt#L294)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

That's okay as long as you update this TODO to be accurate.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-09 19:02 UTC, SanjayVas approved these changes
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/173)* status: all files reviewed, 4 unresolved discussions (waiting on @oliver-amzn, @uakyol, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt, line 48 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/173#-MggFhAt8FUKaZPrhvE7:-MggFhAt8FUKaZPrhvE8:b-ciom1o) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9f9d408036fadd584bc9d095efa0588e7fc3f99e/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt#L48)):*
> ```Kotlin
> private val TEST_INSTANT = Instant.ofEpochMilli(123456789L)
> private const val EXTERNAL_MEASUREMENT_CONSUMER_ID = 123L
> private const val FIXED_INTERNAL_ID = 2345L
> ```

Unused?
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt, line 102 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/173#-MggFX9Q5LFfpIzb8cfS:-MggFX9Q5LFfpIzb8cfT:b80u0xg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9f9d408036fadd584bc9d095efa0588e7fc3f99e/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt#L102)):*
> ```Kotlin
>             notValidAfterBuilder.seconds = 23456
>             subjectKeyIdentifier = PREFERRED_MC_SUBJECT_KEY_IDENTIFIER
>             detailsBuilder.setX509Der(PREFERRED_MC_CERTIFICATE_DER)
> ```

nit: property syntax
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt, line 238 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/173#-MggH-0C3CX_pog4YnE0:-MggH-0C3CX_pog4YnE1:bt087wp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d01a8893c52989227833ca7bfca0605b799f5fe3/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt#L238)):*
> ```Kotlin
>           }
>           .build()
>       )
> ```

Also add some verification that the external measurement ID and external computation ID in `createdMeasurement` have been set.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt, line 301 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/173#-MggHQ1Z07lXOqUMgXbv:-MggHQ1Z07lXOqUMgXbw:b-n9r22o) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d01a8893c52989227833ca7bfca0605b799f5fe3/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt#L301)):*
> ```Kotlin
>         .apply {
>           clearDataProviders()
>           addAllRequisitions(
> ```

nit: use `addXXXBuilder` instead of this pattern of `addAllXXX` + `listOf` + `XXX.newBuilder()`


<!-- Sent from Reviewable.io -->

2021-08-10 20:49 UTC, uakyol reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/173)* status: 6 of 23 files reviewed, 1 unresolved discussion (waiting on @oliver-amzn, @SanjayVas, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt, line 238 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/173#-MggH-0C3CX_pog4YnE0:-MglomGi5xg-1lxH6WTV:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d01a8893c52989227833ca7bfca0605b799f5fe3/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt#L238)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Also add some verification that the external measurement ID and external computation ID in `createdMeasurement` have been set.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-10 23:13 UTC, SanjayVas approved these changes
> Reviewed 16 of 17 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/173)* status: 22 of 23 files reviewed, all discussions resolved (waiting on @oliver-amzn and @zachcwc)



<!-- Sent from Reviewable.io -->

2021-08-11 20:28 UTC, oliver-amzn requested changes
> Reviewed 2 of 16 files at r1, 2 of 19 files at r2, 1 of 2 files at r3, 1 of 2 files at r4, 5 of 17 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/173)* status: 22 of 23 files reviewed, 2 unresolved discussions (waiting on @uakyol and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt, line 50 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/173#-MgqtA6e8Y9-ARgQJk24:-MgqtA6e8Y9-ARgQJk25:b-mh1s31) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/df3deb98b770ef6efce27ee6aea3882af85b7c87/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt#L50)):*
> ```Kotlin
> 
>   private fun buildMeasurement(struct: Struct): Measurement {
>     // TODO(@uakyol): populate all the relevant fields for a measurement.
> ```

What fields are still missing? 
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt, line 114 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/173#-MgqtIRd1Rthem0Rlk_7:-MgqtIRd1Rthem0Rlk_8:by98rys) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/df3deb98b770ef6efce27ee6aea3882af85b7c87/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt#L114)):*
> ```Kotlin
>     return withBuilder {
>         appendClause("WHERE $externalIdColumn = @external_id")
>         appendClause("GROUP BY 1, 2, 3, 4, 5, 6, 7, 8")
> ```

What's this about? 
(I'm familiar with regular SQL group by but have not seen this before)


<!-- Sent from Reviewable.io -->

2021-08-11 20:31 UTC, wangyaopw reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/173)* status: 22 of 23 files reviewed, 2 unresolved discussions (waiting on @oliver-amzn, @uakyol, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt, line 50 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/173#-MgqtA6e8Y9-ARgQJk24:-MgquGTJDaBDlrWRN4aL:b-vz4l9n) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/df3deb98b770ef6efce27ee6aea3882af85b7c87/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt#L50)):*
<details><summary><i>Previously, oliver-amzn (Oliver) wrote…</i></summary><blockquote>

What fields are still missing? 
</blockquote></details>

Too many to list here. We'll check the proto fields one by one when Ugur removes this TODO


<!-- Sent from Reviewable.io -->

2021-08-11 22:02 UTC, oliver-amzn reviewed
> Reviewed 1 of 5 files at r6.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/173)* status: 18 of 23 files reviewed, 1 unresolved discussion (waiting on @oliver-amzn, @SanjayVas, @uakyol, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt, line 50 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/173#-MgqtA6e8Y9-ARgQJk24:-MgrE34b-z67efFReckT:b44tpx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/df3deb98b770ef6efce27ee6aea3882af85b7c87/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt#L50)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

Too many to list here. We'll check the proto fields one by one when Ugur removes this TODO
</blockquote></details>

👍


<!-- Sent from Reviewable.io -->

2021-08-11 22:15 UTC, uakyol reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/173)* status: 18 of 23 files reviewed, 1 unresolved discussion (waiting on @oliver-amzn, @SanjayVas, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt, line 114 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/173#-MgqtIRd1Rthem0Rlk_7:-MgrGv99DEQsf0sBH-Z3:b-pjrac6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/df3deb98b770ef6efce27ee6aea3882af85b7c87/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt#L114)):*
<details><summary><i>Previously, oliver-amzn (Oliver) wrote…</i></summary><blockquote>

What's this about? 
(I'm familiar with regular SQL group by but have not seen this before)
</blockquote></details>

It basically groups by all the fields except by the aggregated field. the numbers are the order of the selected columns


<!-- Sent from Reviewable.io -->

2021-08-11 22:19 UTC, oliver-amzn reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/173)* status: 18 of 23 files reviewed, all discussions resolved (waiting on @oliver-amzn, @SanjayVas, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt, line 114 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/173#-MgqtIRd1Rthem0Rlk_7:-MgrI3KVCjUGky7UQzdi:b-ke6do3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/df3deb98b770ef6efce27ee6aea3882af85b7c87/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt#L114)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

It basically groups by all the fields except by the aggregated field. the numbers are the order of the selected columns
</blockquote></details>

Interesting. Thanks for explaining!


<!-- Sent from Reviewable.io -->

2021-08-11 23:13 UTC, SanjayVas approved these changes
> Reviewed 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/173)* status: 22 of 23 files reviewed, all discussions resolved (waiting on @zachcwc)



<!-- Sent from Reviewable.io -->

2021-08-12 19:31 UTC, wangyaopw approved these changes
> Reviewed 1 of 16 files at r1, 2 of 19 files at r2, 5 of 6 files at r7, 2 of 4 files at r8, 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/173)* status: 22 of 23 files reviewed, all discussions resolved (waiting on @oliver-amzn and @zachcwc)



<!-- Sent from Reviewable.io -->

2021-08-12 21:32 UTC, oliver-amzn approved these changes
> Reviewed 4 of 6 files at r7, 2 of 4 files at r8, 1 of 2 files at r10, 1 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/173)* status: 21 of 23 files reviewed, all discussions resolved (waiting on @wangyaopw and @zachcwc)



<!-- Sent from Reviewable.io -->

2021-08-12 21:43 UTC, SanjayVas requested changes
> Reviewed 4 of 6 files at r7, 2 of 4 files at r8, 1 of 2 files at r10, 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/173)* status: 22 of 23 files reviewed, 8 unresolved discussions (waiting on @oliver-amzn, @uakyol, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt, line 110 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/173#-MgwCvMdBB7RHLyzfJOy:-MgwCvMeCjryuoxRstMJ:bu6mm2h) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2ff4a355ead3a1be83eb68f807417a0caf861a15/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt#L110)):*
> ```Kotlin
>   }
> 
>   suspend fun readExternalIdWithGroupByOrNull(
> ```

Where is this used? I'm not spotting it.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt, line 137 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/173#-MgwCPTA5xOCi99tqc65:-MgwCPTA5xOCi99tqc66:b-dgl23w) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2ff4a355ead3a1be83eb68f807417a0caf861a15/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt#L137)):*
> ```Kotlin
>       Measurements.CreateTime,
>       MeasurementConsumers.ExternalMeasurementConsumerId,
>     MeasurementConsumerCertificates.ExternalMeasurementConsumerCertificateId
> ```

nit: match indentation
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurement.kt, line 64 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/173#-MgwEo6Y7uyKpmncBKhl:-MgwEo6Y7uyKpmncBKhm:b-uybgqt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2ff4a355ead3a1be83eb68f807417a0caf861a15/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurement.kt#L64)):*
> ```Kotlin
>     val measurementId = idGenerator.generateInternalId().value
> 
>     val measuermentConsumerGetCertificateRequest =
> ```

Long method: extract function for getting MC certificate external ID.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurement.kt, line 66 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/173#-MgwECUW7-KO0Tr4eNBL:-MgwECUW7-KO0Tr4eNBM:b6jd0vf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2ff4a355ead3a1be83eb68f807417a0caf861a15/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurement.kt#L66)):*
> ```
> .also
> ```
nit: Looks like you could use `apply` here instead
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurement.kt, line 73 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/173#-MgwE77UAULvCwhpOtJ4:-MgwE77UAULvCwhpOtJ5:b-eyw94) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2ff4a355ead3a1be83eb68f807417a0caf861a15/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurement.kt#L73)):*
> ```
> measuerment
> ```
nit: `measurement`
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurement.kt, line 73 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/173#-MgwHCj4BCiKMTtjD_-a:-MgwHCj4BCiKMTtjD_-b:b-pl2yge) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2ff4a355ead3a1be83eb68f807417a0caf861a15/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurement.kt#L73)):*
> ```Kotlin
> 
>     val measurementConsumerCertificateId =
>       CertificateReader(measuermentConsumerGetCertificateRequest)
> ```

Wait, I think I missed when CertificateReader switched to taking in the whole request. Doesn't it just need ParentCase? It doesn't make sense to give it the request and then have to pass the ID from the request again in `readExternalIdOrNull`.

Also I don't think that the signature of `readExternalIdOrNull` works for Certificate, as you also need to specify the external parent ID a the external certificate ID is only guaranteed to be unique for a given parent. This is true for any table with more than one ID in the external version of its primary key, so the reader should probably just extend from BaseSpannerReader rather than SpannerReader.

You can leave a TODO in CertificateReader and fix that separately if this PR is getting too big.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurement.kt, line 87 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/173#-MgwFMjNDLfEBH9u4Q0s:-MgwFMjNDLfEBH9u4Q0t:bzcltw5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2ff4a355ead3a1be83eb68f807417a0caf861a15/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurement.kt#L87)):*
> ```
> (k, v)
> ```
nit: prefer descriptive variables names. Very easy to lose track of what these are inside the loop.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurement.kt, line 208 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/173#-MgwGHKGBJlaZ77DX82H:-MgwGHKH9omGjvzLRQM6:bbgnvp4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2ff4a355ead3a1be83eb68f807417a0caf861a15/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurement.kt#L208)):*
> ```Kotlin
> 
>     val groupByClause = """
>       GROUP BY 1, 2, 3, 4, 5, 6, 7, 8, 9
> ```

Why do we need a GROUP BY? What aggregation is being done?


<!-- Sent from Reviewable.io -->

2021-08-16 10:45 UTC, uakyol reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/173)* status: 9 of 25 files reviewed, 6 unresolved discussions (waiting on @oliver-amzn, @SanjayVas, @wangyaopw, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt, line 110 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/173#-MgwCvMdBB7RHLyzfJOy:-MhDTaqo0bqzzVGHe4YQ:b-l02aai) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2ff4a355ead3a1be83eb68f807417a0caf861a15/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt#L110)):*
> ```
> readExternalIdWithGroupByOrNull
> ```
it was used in the SpannerMeasurementService : https://github.com/world-federation-of-advertisers/cross-media-measurement/pull/173/files#diff-4da8911df6fa330dea082bddf3ae624720e5750aa7cef6d2f6e43eface67ae29R58 . But based on your comment on group by, I realized this is unnecessary and took it out.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurement.kt, line 64 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/173#-MgwEo6Y7uyKpmncBKhl:-MhDWCd30S6y9FZFCy9n:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2ff4a355ead3a1be83eb68f807417a0caf861a15/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurement.kt#L64)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Long method: extract function for getting MC certificate external ID.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurement.kt, line 73 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/173#-MgwE77UAULvCwhpOtJ4:-MhDULcYAtlD1X7XVBQ8:b8zgs1w) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2ff4a355ead3a1be83eb68f807417a0caf861a15/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurement.kt#L73)):*
> measuerment
thanks
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurement.kt, line 73 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/173#-MgwHCj4BCiKMTtjD_-a:-MhDY64yEdIjaZayUMEa:biu35fz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2ff4a355ead3a1be83eb68f807417a0caf861a15/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurement.kt#L73)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Wait, I think I missed when CertificateReader switched to taking in the whole request. Doesn't it just need ParentCase? It doesn't make sense to give it the request and then have to pass the ID from the request again in `readExternalIdOrNull`.

Also I don't think that the signature of `readExternalIdOrNull` works for Certificate, as you also need to specify the external parent ID a the external certificate ID is only guaranteed to be unique for a given parent. This is true for any table with more than one ID in the external version of its primary key, so the reader should probably just extend from BaseSpannerReader rather than SpannerReader.

You can leave a TODO in CertificateReader and fix that separately if this PR is getting too big.
</blockquote></details>

readExternalIdOrNull  : Thank you. Yes, makes sense. I missed that, I added a TODO in CertificateReader. 
CertificateReader and ParentCase:  I never switched it. this was what we implemented. I agree, this doesn't make sense. added a TODO there too.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurement.kt, line 87 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/173#-MgwFMjNDLfEBH9u4Q0s:-MhDUxMO85r84Y3UNZP3:b-cvqv1a) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2ff4a355ead3a1be83eb68f807417a0caf861a15/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurement.kt#L87)):*
> (k, v)
thanks
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurement.kt, line 208 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/173#-MgwGHKGBJlaZ77DX82H:-MhDX20d5jzglwSlypY8:bbyki8f) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2ff4a355ead3a1be83eb68f807417a0caf861a15/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurement.kt#L208)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Why do we need a GROUP BY? What aggregation is being done?
</blockquote></details>

Thanks a lot for spotting this. I had thought for the ARRAY aggregation in the MeasurementReader we would need this, but I was wrong. 


<!-- Sent from Reviewable.io -->

2021-08-17 17:22 UTC, SanjayVas approved these changes
> Reviewed 4 of 4 files at r12, 3 of 3 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/173)* status: 23 of 24 files reviewed, all discussions resolved (waiting on @zachcwc)



<!-- Sent from Reviewable.io -->

2021-08-17 17:32 UTC, uakyol reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 16 files at r1, 1 of 19 files at r2, 1 of 17 files at r5, 1 of 6 files at r7, 1 of 4 files at r8, 2 of 2 files at r11, 4 of 4 files at r12, 3 of 3 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/173#-:-MhK9nnU9OShYLgZOfXh:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zachcwc)



<!-- Sent from Reviewable.io -->

2021-08-17 17:55 UTC, uakyol reviewed
> Reviewed 3 of 3 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/173)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zachcwc)



<!-- Sent from Reviewable.io -->

2021-08-17 17:56 UTC, merged