fix: Wait for EDP simulator to initialize before considering it ready
world-federation-of-advertisers/cross-media-measurement pull request #1732
Opened 2024-08-02 17:27 UTC by SanjayVas

This introduces a health check to the EDP simulator, where it is considered healthy only after its initialization items (e.g. updating capabilities). This is used by a Kubernetes startup probe.

Fixes #1728

2024-08-02 17:27 UTC, wfa-reviewable commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1732)
<!-- Reviewable:end -->

2024-08-02 19:49 UTC, ple13 requested changes
My understanding is that EDPs can declare healthy with or without a health file, but a file is needed for Kubernetes to do the probe, is it right? In the configuration, it looks like the probe command looks for a fixed filename, should we instantiate it with the provided health-file?

> Reviewed 7 of 11 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1732#-:-O3Jc3uw3R8FJNi8CmsD:bu2wtx5)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/k8s/edp_simulator.cue` line 87 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1732#-O3JbPqN4cztlH1QWAGh:-O3JbPqN4cztlH1QWAGi:bexty0t) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c57bd54ae7dc9040a3850b7e8aa040dd16212559/src/main/k8s/edp_simulator.cue#L87)):*
> ```CUE
> 					args: ["/bin/sh", "-c", "while true; do sleep 30; done"]
> 					startupProbe: {
> 						exec: command: ["cat", "/run/probe/healthy"]
> ```

Is it possible not to hard-code the file name?


<!-- Sent from Reviewable.io -->

2024-08-02 19:58 UTC, SanjayVas reviewed
We do instantiate it with the value of the `--health-file` option if specified.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1732#-:-O3JeunwCa7KCmYoG7TD:b-vym38m)* status: 10 of 11 files reviewed, 1 unresolved discussion (waiting on @ple13)

___
*[`src/main/k8s/edp_simulator.cue` line 87 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1732#-O3JbPqN4cztlH1QWAGh:-O3JdIh95Mcmw9AdMLDK:bhcznvg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c57bd54ae7dc9040a3850b7e8aa040dd16212559/src/main/k8s/edp_simulator.cue#L87)):*
<details><summary><i>Previously, ple13 (Phi) wrote…</i></summary><blockquote>

Is it possible not to hard-code the file name?
</blockquote></details>

This isn't hard-coding, as it's in the K8s config rather than the compiled code. It's passed to the simulator via a command line option. The key issues are that:

1. The file path must be the same for both the `--health-file` option and the probe.
2. The file must be in a volume mount that's shared by both the main container and the sidecar. By default we create emptyDir volume mounts at `/run/<name>`.

I extracted a `HealthFile` CUE alias to make (1) more clear.


<!-- Sent from Reviewable.io -->

2024-08-02 20:00 UTC, ple13 approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1732)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)



<!-- Sent from Reviewable.io -->

2024-08-05 18:49 UTC, stevenwarejones approved these changes
> Reviewed 7 of 11 files at r1, 3 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1732)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)



<!-- Sent from Reviewable.io -->

2024-08-05 18:49 UTC, stevenwarejones approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1732)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/test/kotlin/org/wfanet/measurement/integration/k8s/EmptyClusterCorrectnessTest.kt` line 269 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1732#-O3Ys1ToECcD9T1ZZrld:-O3Ys1ToECcD9T1ZZrle:b-845vea) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fb9cc35e60ff26bfeec5dac9abab8b7b688ddd63/src/test/kotlin/org/wfanet/measurement/integration/k8s/EmptyClusterCorrectnessTest.kt#L269)):*
> ```Kotlin
>         .also {
>           try {
>             eventGroupsClient.waitForEventGroups(
> ```

thx for cleaning this up


<!-- Sent from Reviewable.io -->

2024-08-05 18:52 UTC, stevenwarejones requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1732)* status: all files reviewed, 2 unresolved discussions (waiting on @SanjayVas)

___
*[`src/test/kotlin/org/wfanet/measurement/integration/k8s/EmptyClusterCorrectnessTest.kt` line 498 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1732#-O3YsW2T4-y21Bbul00K:-O3YsW2U2Snqbq23lgrg:bw23tq9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fb9cc35e60ff26bfeec5dac9abab8b7b688ddd63/src/test/kotlin/org/wfanet/measurement/integration/k8s/EmptyClusterCorrectnessTest.kt#L498)):*
> ```Kotlin
>     val chainedRule = chainRulesSequentially(tempDir, Images(), measurementSystem)
> 
>     private suspend fun EventGroupsGrpcKt.EventGroupsCoroutineStub.waitForEventGroups(
> ```

was looking at this a same time. How does this update ensure that the event groups were created before proceeding?


<!-- Sent from Reviewable.io -->

2024-08-05 18:59 UTC, SanjayVas reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1732)* status: all files reviewed, 2 unresolved discussions (waiting on @stevenwarejones)

___
*[`src/test/kotlin/org/wfanet/measurement/integration/k8s/EmptyClusterCorrectnessTest.kt` line 269 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1732#-O3Ys1ToECcD9T1ZZrld:-O3Yt21s13GSRB4rkNdA:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fb9cc35e60ff26bfeec5dac9abab8b7b688ddd63/src/test/kotlin/org/wfanet/measurement/integration/k8s/EmptyClusterCorrectnessTest.kt#L269)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

thx for cleaning this up
</blockquote></details>

Done.
___
*[`src/test/kotlin/org/wfanet/measurement/integration/k8s/EmptyClusterCorrectnessTest.kt` line 498 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1732#-O3YsW2T4-y21Bbul00K:-O3Yt50K3NjRU4kDNjAF:bsv8zct) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fb9cc35e60ff26bfeec5dac9abab8b7b688ddd63/src/test/kotlin/org/wfanet/measurement/integration/k8s/EmptyClusterCorrectnessTest.kt#L498)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

was looking at this a same time. How does this update ensure that the event groups were created before proceeding?
</blockquote></details>

We already wait for deployments to be ready (see `waitUntilDeploymentsComplete`). In the case of EDP simulator deployments, the EdpSimulatorRunner startup looks like this:

1. Ensure event groups
2. Update data availability
3. Update capabilities
4. Set healthy to true
5. Poll for Requisitions


<!-- Sent from Reviewable.io -->

2024-08-06 14:18 UTC, stevenwarejones approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1732)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

___
*[`src/test/kotlin/org/wfanet/measurement/integration/k8s/EmptyClusterCorrectnessTest.kt` line 498 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1732#-O3YsW2T4-y21Bbul00K:-O3c2TA0AA6dLs1qVu16:by4bx31) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fb9cc35e60ff26bfeec5dac9abab8b7b688ddd63/src/test/kotlin/org/wfanet/measurement/integration/k8s/EmptyClusterCorrectnessTest.kt#L498)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

We already wait for deployments to be ready (see `waitUntilDeploymentsComplete`). In the case of EDP simulator deployments, the EdpSimulatorRunner startup looks like this:

1. Ensure event groups
2. Update data availability
3. Update capabilities
4. Set healthy to true
5. Poll for Requisitions
</blockquote></details>

thx for the clarification


<!-- Sent from Reviewable.io -->

2024-08-06 15:59 UTC, merged