Add ExchangeStepsHierarchy class to update ExchangeSteps
world-federation-of-advertisers/cross-media-measurement pull request #176
Opened 2021-08-04 00:05 UTC by yunyeng

2021-08-04 03:41 UTC, efoxepstein requested changes
> Reviewed 2 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/176)* status: 2 of 5 files reviewed, 3 unresolved discussions (waiting on @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/common/ExchangeStepsHierarchy.kt, line 22 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/176#-MgE7TfV6w--Q80XRX0h:-MgE7TfV6w--Q80XRX0i:b-2tk8ho) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0d2e5b19247fba0e9c2b932b708bd9bd40227103/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/common/ExchangeStepsHierarchy.kt#L22)):*
> ```Kotlin
> 
> /** Class that creates and updates set of [ExchangeStep]s based on a [ExchangeWorkflow]. */
> class ExchangeStepsHierarchy(
> ```

This name doesn't really make sense to me -- but before renaming it, I have a different suggestion.

I can think of two valid use cases for this:

1. When creating a new Exchange, list the initial state for each Step.
2. After updating a step, list the new states for each Step.

Right now, the implementation is kind of mixing two concerns: creating ExchangeStep protos and dealing with the dependencies between them. It's also a little complicated.

So, my recommendation would just be to define a function:

```
fun findReadyExchangeSteps(workflow: ExchangeWorkflow, completedStepIndexes: Set<Int>): List<ExchangeWorkflow.Step> {
  return workflow.stepsList.filter { step -> step.prerequisiteStepIndicesList.all { it in completedStepIndexes } }
}
```

You can build `completedStepIndexes` as something like `SELECT ExchangeSteps.StepIndex FROM ExchangeSteps WHERE ExchangeSteps.State = SUCCESS`.

Then you can use the results of `findReadyExchangeSteps` in mutations like:

```
for (index in findReadyExchangeSteps(...)) {
  updateMutationBuilder("ExchangeSteps")
    .set("RecurringExchangeId" to ...)
    .set("Date" to...)
    .set("StepIndex" to index)
    .set("State" to READY)
    .build()
    .bufferTo(...)
}
```

Does this make sense?
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/common/ExchangeStepsHierarchy.kt, line 27 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/176#-MgDVQZM7XzZkO9ct2Sb:-MgDVQZN4HYdip1QF7QK:b-ozvamx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0d2e5b19247fba0e9c2b932b708bd9bd40227103/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/common/ExchangeStepsHierarchy.kt#L27)):*
> ```Kotlin
> ) {
>   private val map = mutableMapOf<Int, ExchangeStep>()
>   private var workflow: ExchangeWorkflow = ExchangeWorkflow.getDefaultInstance()
> ```

You can assign this directly:

```
private val workflow: ExchangeWorkflow = recurringExchange.details.exchangeWorkflow
init {
  require(workflow.isValid()) { ... }
}
```
___
*[src/main/proto/wfa/measurement/internal/kingdom/recurring_exchange_details.proto, line 28 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/176#-MgE9EHl72GoOgWU70HA:-MgE9EHl72GoOgWU70HB:b6suevp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/de4ffdc4ae02ca6184c3a01ff30ed7b3f7f3611f/src/main/proto/wfa/measurement/internal/kingdom/recurring_exchange_details.proto#L28)):*
> ```protobuf
>   string cron_schedule = 1;
> 
>   // Serialized ExchangeWorkflow proto from the public API.
> ```

We need to store this too.


<!-- Sent from Reviewable.io -->

2021-08-04 03:41 UTC, efoxepstein reviewed
> Reviewed 3 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/176)* status: all files reviewed, 3 unresolved discussions (waiting on @yunyeng)



<!-- Sent from Reviewable.io -->

2021-08-04 18:58 UTC, yunyeng reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/176)* status: 2 of 7 files reviewed, 3 unresolved discussions (waiting on @efoxepstein)

___
*[src/main/proto/wfa/measurement/internal/kingdom/recurring_exchange_details.proto, line 28 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/176#-MgE9EHl72GoOgWU70HA:-MgHWxdM6X5tkBzDpj_v:bqm4kob) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/de4ffdc4ae02ca6184c3a01ff30ed7b3f7f3611f/src/main/proto/wfa/measurement/internal/kingdom/recurring_exchange_details.proto#L28)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

We need to store this too.
</blockquote></details>

Acked.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/common/ExchangeStepsHierarchy.kt, line 22 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/176#-MgE7TfV6w--Q80XRX0h:-MgHWmms1JR4yIqR9B-D:bp7883h) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0d2e5b19247fba0e9c2b932b708bd9bd40227103/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/common/ExchangeStepsHierarchy.kt#L22)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

This name doesn't really make sense to me -- but before renaming it, I have a different suggestion.

I can think of two valid use cases for this:

1. When creating a new Exchange, list the initial state for each Step.
2. After updating a step, list the new states for each Step.

Right now, the implementation is kind of mixing two concerns: creating ExchangeStep protos and dealing with the dependencies between them. It's also a little complicated.

So, my recommendation would just be to define a function:

```
fun findReadyExchangeSteps(workflow: ExchangeWorkflow, completedStepIndexes: Set<Int>): List<ExchangeWorkflow.Step> {
  return workflow.stepsList.filter { step -> step.prerequisiteStepIndicesList.all { it in completedStepIndexes } }
}
```

You can build `completedStepIndexes` as something like `SELECT ExchangeSteps.StepIndex FROM ExchangeSteps WHERE ExchangeSteps.State = SUCCESS`.

Then you can use the results of `findReadyExchangeSteps` in mutations like:

```
for (index in findReadyExchangeSteps(...)) {
  updateMutationBuilder("ExchangeSteps")
    .set("RecurringExchangeId" to ...)
    .set("Date" to...)
    .set("StepIndex" to index)
    .set("State" to READY)
    .build()
    .bufferTo(...)
}
```

Does this make sense?
</blockquote></details>

Acked. I will add this in the next PR when tackling the finishExchangeSetpAttempt.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/common/ExchangeStepsHierarchy.kt, line 27 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/176#-MgDVQZM7XzZkO9ct2Sb:-MgHWwEwCrsGNuWVmi61:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0d2e5b19247fba0e9c2b932b708bd9bd40227103/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/common/ExchangeStepsHierarchy.kt#L27)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

You can assign this directly:

```
private val workflow: ExchangeWorkflow = recurringExchange.details.exchangeWorkflow
init {
  require(workflow.isValid()) { ... }
}
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-04 20:43 UTC, yunyeng reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/176)* status: 1 of 7 files reviewed, 3 unresolved discussions (waiting on @efoxepstein)

___
*[src/main/proto/wfa/measurement/internal/kingdom/recurring_exchange_details.proto, line 28 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/176#-MgE9EHl72GoOgWU70HA:-MgHu5DjDuz-ucIPMrg-:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/de4ffdc4ae02ca6184c3a01ff30ed7b3f7f3611f/src/main/proto/wfa/measurement/internal/kingdom/recurring_exchange_details.proto#L28)):*
<details><summary><i>Previously, yunyeng (Yunus Yen) wrote…</i></summary><blockquote>

Acked.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-04 22:43 UTC, efoxepstein requested changes
> Reviewed 5 of 5 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/176)* status: all files reviewed, 2 unresolved discussions (waiting on @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ClaimReadyExchangeStep.kt, line 186 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/176#-MgHusNj4KNuAXviRy9s:-MgHusNj4KNuAXviRy9t:bruplcp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d8039d3cc8ff2d1338ecac377a6b454205abf253/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ClaimReadyExchangeStep.kt#L186)):*
> ```Kotlin
>     val workflow = recurringExchange.details.exchangeWorkflow
>     var firstStep: ExchangeStep? = null
>     workflow.stepsList.forEach { step ->
> ```

Since the body of this loop is really big, can you pull it out to a helper function? If the helper function returns the ExchangeStep proto after creating it, you can just do this here:

```
for (step in workflow.stepsList) { yourHelperFunction(it, ...) }
```

I'm proposing NOT returning anything from this step and setting ALL of them to READY or BLOCKED. Instead, this function will return nothing and in `runTransaction` you can just call `findReadyExchangeStep` again (if you want to do RYW -- see https://g3doc.corp.google.com/spanner/g3doc/userguide/transactions.md?cl=head#read-your-writes) or it's maybe just better to just return an empty Optional after this and let the client call again.

Basically, we want to simplify this as much as possible.
___
*[src/main/proto/wfa/measurement/internal/kingdom/recurring_exchange_details.proto, line 37 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/176#-MgIJDA_CN7helslLhWf:-MgIJDA_CN7helslLhWg:b-9snp3g) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d8039d3cc8ff2d1338ecac377a6b454205abf253/src/main/proto/wfa/measurement/internal/kingdom/recurring_exchange_details.proto#L37)):*
> ```protobuf
>   // This is serialized because DataProviders and ModelProviders will sign the
>   // ExchangeWorkflow to keep a record that they agreed to it.
>   bytes external_exchange_workflow = 3;
> ```

While you're here, can you also add this?

```
  // Version the public API for `external_exchange_workflow`.
  string api_version = 1;
```


<!-- Sent from Reviewable.io -->

2021-08-05 22:19 UTC, yunyeng reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/176)* status: 4 of 14 files reviewed, 2 unresolved discussions (waiting on @efoxepstein)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ClaimReadyExchangeStep.kt, line 186 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/176#-MgHusNj4KNuAXviRy9s:-MgNOOKh0yLj7ubmaMIj:b-mkwdb0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d8039d3cc8ff2d1338ecac377a6b454205abf253/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ClaimReadyExchangeStep.kt#L186)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Since the body of this loop is really big, can you pull it out to a helper function? If the helper function returns the ExchangeStep proto after creating it, you can just do this here:

```
for (step in workflow.stepsList) { yourHelperFunction(it, ...) }
```

I'm proposing NOT returning anything from this step and setting ALL of them to READY or BLOCKED. Instead, this function will return nothing and in `runTransaction` you can just call `findReadyExchangeStep` again (if you want to do RYW -- see https://g3doc.corp.google.com/spanner/g3doc/userguide/transactions.md?cl=head#read-your-writes) or it's maybe just better to just return an empty Optional after this and let the client call again.

Basically, we want to simplify this as much as possible.
</blockquote></details>

Separated logic of finding and creating steps. PTAL
___
*[src/main/proto/wfa/measurement/internal/kingdom/recurring_exchange_details.proto, line 37 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/176#-MgIJDA_CN7helslLhWf:-MgNOJBd32iL4H0QjP49:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d8039d3cc8ff2d1338ecac377a6b454205abf253/src/main/proto/wfa/measurement/internal/kingdom/recurring_exchange_details.proto#L37)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

While you're here, can you also add this?

```
  // Version the public API for `external_exchange_workflow`.
  string api_version = 1;
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-05 22:44 UTC, efoxepstein requested changes
> Reviewed 11 of 11 files at r4.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/176)* status: all files reviewed, 7 unresolved discussions (waiting on @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerExchangeStepsService.kt, line 48 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/176#-MgNQzb9ESBJ5bM5kB1H:-MgNQzbA0WEdnStbgWhx:b-nml5d8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/25234c3ae0326847587491ab13a319fbf9012f70/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerExchangeStepsService.kt#L48)):*
> ```Kotlin
>       if (request.hasExternalDataProviderId()) request.externalDataProviderId else null
> 
>     var result =
> ```

Would anything break if you just deleted this call to `FindReadyExchangeStep` and just relied on the next one?
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerExchangeStepsService.kt, line 72 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/176#-MgNRFFYAgWen8bVoviu:-MgNRFFYAgWen8bVoviv:bgcaa1k) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/25234c3ae0326847587491ab13a319fbf9012f70/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerExchangeStepsService.kt#L72)):*
> ```Kotlin
>         .execute(client, idGenerator, clock)
> 
>     grpcRequire(result.isPresent) { failGrpc(Status.NOT_FOUND) { "ExchangeStep not found" } }
> ```

This is not an error. Most of the time there will be no work to do. Instead:

```
if (!result.isPresent) return ClaimReadyExchangeStep.getDefaultInstance()`
```
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerExchangeStepsService.kt, line 77 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/176#-MgNRWAC54hUi4YBkd1A:-MgNRWAD4koh6aiPwAT7:byj6b8g) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/25234c3ae0326847587491ab13a319fbf9012f70/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerExchangeStepsService.kt#L77)):*
> ```Kotlin
>   }
> 
>   private fun Result.buildResponse(): ClaimReadyExchangeStepResponse {
> ```

Maybe `toClaimReadyExchangeStepResponse()` would be a better name
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateExchangesAndSteps.kt, line 55 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/176#-MgNS1x4-Fbv6QPxyUTP:-MgNS1x4-Fbv6QPxyUTQ:b4gfw3d) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/25234c3ae0326847587491ab13a319fbf9012f70/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateExchangesAndSteps.kt#L55)):*
> ```Kotlin
>   override suspend fun TransactionScope.runTransaction() {
>     // First, retrieve a single Recurring Exchange based on the filter below.
>     val streamFilter =
> ```

Can you pull everything before `recurringExchange` out to a helper function? So here you can just write:

```
val recurringExchangeResult: StreamRecurringExchanges.Result = findRecurringExchange()
```
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateExchangesAndSteps.kt, line 64 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/176#-MgNSKvsBtHwv8nIIXvJ:-MgNSKvsBtHwv8nIIXvK:b8gpf1q) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/25234c3ae0326847587491ab13a319fbf9012f70/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateExchangesAndSteps.kt#L64)):*
> ```Kotlin
>     val streamResult =
>       StreamRecurringExchanges(streamFilter, limit = 1).execute(transactionContext).singleOrNull()
>         ?: throw IllegalArgumentException("No Recurring Exchange was found.")
> ```

Note that this isn't really an error -- we don't want to crash if there's no work to do. Just return instead.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateExchangesAndSteps.kt, line 142 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/176#-MgNSlF4E8XPYcGwvOGV:-MgNSlF4E8XPYcGwvOGW:besbvyf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/25234c3ae0326847587491ab13a319fbf9012f70/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateExchangesAndSteps.kt#L142)):*
> ```Kotlin
> 
>     val statement: Statement =
>       Statement.newBuilder(sql)
> ```

Did we pull in the fancy builders for this yet? If not it's fine
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateExchangesAndSteps.kt, line 240 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/176#-MgNTUmRDhu3aBJbs6K1:-MgNTUmRDhu3aBJbs6K2:bfw0vm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/25234c3ae0326847587491ab13a319fbf9012f70/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateExchangesAndSteps.kt#L240)):*
> ```Kotlin
> }
> 
> internal fun Date.applyCronSchedule(cronSchedule: String): Date {
> ```

Can you put a TODO here that we're still deciding on the format for cronSchedule? Maybe file a GH issue too and put a link to it


<!-- Sent from Reviewable.io -->

2021-08-05 23:23 UTC, yunyeng reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/176)* status: 11 of 15 files reviewed, 7 unresolved discussions (waiting on @cs-sswaminathan, @efoxepstein, @kgaynor, @stevenwarejones, and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerExchangeStepsService.kt, line 48 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/176#-MgNQzb9ESBJ5bM5kB1H:-MgNbhsYEnth3FeTwFCU:b-1d008y) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/25234c3ae0326847587491ab13a319fbf9012f70/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerExchangeStepsService.kt#L48)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Would anything break if you just deleted this call to `FindReadyExchangeStep` and just relied on the next one?
</blockquote></details>

If we try to create the same exchange but since this is the only place that does that, should be ok.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerExchangeStepsService.kt, line 72 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/176#-MgNRFFYAgWen8bVoviu:-MgNbvgG1FlSKOEsfiyi:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/25234c3ae0326847587491ab13a319fbf9012f70/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerExchangeStepsService.kt#L72)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

This is not an error. Most of the time there will be no work to do. Instead:

```
if (!result.isPresent) return ClaimReadyExchangeStep.getDefaultInstance()`
```
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerExchangeStepsService.kt, line 77 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/176#-MgNRWAC54hUi4YBkd1A:-MgNbwJX1lSf4Tth5yIL:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/25234c3ae0326847587491ab13a319fbf9012f70/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerExchangeStepsService.kt#L77)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Maybe `toClaimReadyExchangeStepResponse()` would be a better name
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateExchangesAndSteps.kt, line 55 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/176#-MgNS1x4-Fbv6QPxyUTP:-MgNbxTk6ny1GdXShFMt:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/25234c3ae0326847587491ab13a319fbf9012f70/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateExchangesAndSteps.kt#L55)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Can you pull everything before `recurringExchange` out to a helper function? So here you can just write:

```
val recurringExchangeResult: StreamRecurringExchanges.Result = findRecurringExchange()
```
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateExchangesAndSteps.kt, line 64 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/176#-MgNSKvsBtHwv8nIIXvJ:-MgNbzZw9B3PwWpSxlvy:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/25234c3ae0326847587491ab13a319fbf9012f70/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateExchangesAndSteps.kt#L64)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Note that this isn't really an error -- we don't want to crash if there's no work to do. Just return instead.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateExchangesAndSteps.kt, line 142 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/176#-MgNSlF4E8XPYcGwvOGV:-MgNc0fX70itWAGOVVuo:b-7sdqu2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/25234c3ae0326847587491ab13a319fbf9012f70/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateExchangesAndSteps.kt#L142)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Did we pull in the fancy builders for this yet? If not it's fine
</blockquote></details>

We did, I need to create new version of common-jvm and update here. Added TODO, will do that in next PR.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateExchangesAndSteps.kt, line 240 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/176#-MgNTUmRDhu3aBJbs6K1:-MgNcAer3M0TelJ7PvUb:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/25234c3ae0326847587491ab13a319fbf9012f70/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateExchangesAndSteps.kt#L240)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Can you put a TODO here that we're still deciding on the format for cronSchedule? Maybe file a GH issue too and put a link to it
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-05 23:25 UTC, efoxepstein approved these changes
> Reviewed 4 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/176)* status: all files reviewed, 1 unresolved discussion (waiting on @cs-sswaminathan, @kgaynor, @stevenwarejones, @wangyaopw, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateExchangesAndSteps.kt, line 95 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/176#-MgNcX3aCaWBcHdZECdv:-MgNcX3aCaWBcHdZECdw:b3w3hob) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2723b7826cf92a981ea6e4f89a22d0b651efb221/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateExchangesAndSteps.kt#L95)):*
> ```Kotlin
> 
>   private suspend fun TransactionScope.findRecurringExchange(): RecurringExchangeReader.Result? {
>     // First, retrieve a single Recurring Exchange based on the filter below.
> ```

Supernit: it's a little weird that now this comment starts with `First`. I'd just delete the comment as the function name makes it pretty clear what it does


<!-- Sent from Reviewable.io -->

2021-08-06 00:17 UTC, wangyaopw requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/176)* status: all files reviewed, 3 unresolved discussions (waiting on @cs-sswaminathan, @kgaynor, @stevenwarejones, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FindReadyExchangeStep.kt, line 37 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/176#-MgNnqsI37gm6y9z2OyZ:-MgNnqsI37gm6y9z2Oy_:b-c40jrc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2723b7826cf92a981ea6e4f89a22d0b651efb221/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FindReadyExchangeStep.kt#L37)):*
> ```
> FindReadyExchangeStep
> ```
The world `find` sounds like a read only operation to me. Is there any reason changing `claim` to `find`?
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FindReadyExchangeStep.kt, line 40 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/176#-MgNoMgD-MiMdEEBZ9Cs:-MgNoMgD-MiMdEEBZ9Ct:bpd5c7n) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2723b7826cf92a981ea6e4f89a22d0b651efb221/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FindReadyExchangeStep.kt#L40)):*
> ```
> Optional<Result>
> ```
just curious, does `Result?` work here? I haven't see any usage of Optional in our codebase yet. 


<!-- Sent from Reviewable.io -->

2021-08-06 01:00 UTC, yunyeng reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/176)* status: 10 of 15 files reviewed, 3 unresolved discussions (waiting on @cs-sswaminathan, @efoxepstein, @kgaynor, @stevenwarejones, and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateExchangesAndSteps.kt, line 95 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/176#-MgNcX3aCaWBcHdZECdv:-MgNySsr-nSl2pj5sCY_:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2723b7826cf92a981ea6e4f89a22d0b651efb221/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateExchangesAndSteps.kt#L95)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Supernit: it's a little weird that now this comment starts with `First`. I'd just delete the comment as the function name makes it pretty clear what it does
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FindReadyExchangeStep.kt, line 37 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/176#-MgNnqsI37gm6y9z2OyZ:-MgNy5Q7-nvtnXnTcLRq:b-gslenf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2723b7826cf92a981ea6e4f89a22d0b651efb221/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FindReadyExchangeStep.kt#L37)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
> FindReadyExchangeStep
> ```
The world `find` sounds like a read only operation to me. Is there any reason changing `claim` to `find`?
</blockquote></details>

Separated the logic but yes that makes sense. Renamed it to claim.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FindReadyExchangeStep.kt, line 40 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/176#-MgNoMgD-MiMdEEBZ9Cs:-MgNyCY27HiGoERDM1Pv:b-nd9o87) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2723b7826cf92a981ea6e4f89a22d0b651efb221/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FindReadyExchangeStep.kt#L40)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
> Optional<Result>
> ```
just curious, does `Result?` work here? I haven't see any usage of Optional in our codebase yet. 
</blockquote></details>

SpannerWriter doesn't allow null value to return. If we are really strict about Optional, I can return Result(null, null) and check the insides in the service? 


<!-- Sent from Reviewable.io -->

2021-08-06 14:13 UTC, stevenwarejones requested changes
> Reviewed 2 of 11 files at r4, 1 of 6 files at r6.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/176)* status: 11 of 15 files reviewed, 5 unresolved discussions (waiting on @cs-sswaminathan, @efoxepstein, @kgaynor, @wangyaopw, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerExchangeStepsService.kt, line 63 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/176#-MgQn6v81UAcdAYW2pQR:-MgQn6v81UAcdAYW2pQS:b7u8t9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/81143d144002b4cf1bcb62f191df49aa573b44ee/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerExchangeStepsService.kt#L63)):*
> ```Kotlin
>     }
> 
>     return ClaimReadyExchangeStepResponse.getDefaultInstance()
> ```

so if no exchange is ready, it just returns the default instance?
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateExchangesAndSteps.kt, line 218 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/176#-MgQnXyi4A0ai_SbemZZ:-MgQnXyj0C2ZpZicPdqi:b-b2tulg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/81143d144002b4cf1bcb62f191df49aa573b44ee/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateExchangesAndSteps.kt#L218)):*
> ```Kotlin
> internal fun Date.applyCronSchedule(cronSchedule: String): Date {
>   return when (cronSchedule) {
>     "DAILY" -> this.toLocalDate().plusDays(1).toProtoDate()
> ```

I think these should be renamed to the typical `@daily`, `@weekly` -- https://www.freebsd.org/cgi/man.cgi?crontab%285%29


<!-- Sent from Reviewable.io -->

2021-08-06 14:40 UTC, efoxepstein approved these changes
> Reviewed 5 of 6 files at r6.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/176)* status: all files reviewed, 4 unresolved discussions (waiting on @cs-sswaminathan, @kgaynor, @stevenwarejones, @wangyaopw, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerExchangeStepsService.kt, line 63 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/176#-MgQn6v81UAcdAYW2pQR:-MgQtLCB35nLT4oRu_Et:b-xnud43) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/81143d144002b4cf1bcb62f191df49aa573b44ee/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerExchangeStepsService.kt#L63)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

so if no exchange is ready, it just returns the default instance?
</blockquote></details>

Correct -- we don't want an error code. We could explicitly model this by making the response a oneof between a NoWork case and the current response body but this seems pretty reasonable too to me. We'll need to update client code to compare the response to the default instance
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FindReadyExchangeStep.kt, line 40 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/176#-MgNoMgD-MiMdEEBZ9Cs:-MgQtsEp9JFMAHPPwNMG:b-remc6p) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2723b7826cf92a981ea6e4f89a22d0b651efb221/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FindReadyExchangeStep.kt#L40)):*
<details><summary><i>Previously, yunyeng (Yunus Yen) wrote…</i></summary><blockquote>

SpannerWriter doesn't allow null value to return. If we are really strict about Optional, I can return Result(null, null) and check the insides in the service? 
</blockquote></details>

I prefer Optional to nulls inside of Result


<!-- Sent from Reviewable.io -->

2021-08-06 15:24 UTC, stevenwarejones requested changes
> Reviewed 1 of 5 files at r1, 1 of 11 files at r4, 1 of 4 files at r5, 1 of 6 files at r6.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/176)* status: all files reviewed, 3 unresolved discussions (waiting on @cs-sswaminathan, @kgaynor, @wangyaopw, and @yunyeng)



<!-- Sent from Reviewable.io -->

2021-08-06 17:07 UTC, yunyeng reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/176)* status: 13 of 15 files reviewed, 3 unresolved discussions (waiting on @cs-sswaminathan, @efoxepstein, @kgaynor, @stevenwarejones, and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateExchangesAndSteps.kt, line 218 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/176#-MgQnXyi4A0ai_SbemZZ:-MgRQlOBBz5q3xT7zS4B:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/81143d144002b4cf1bcb62f191df49aa573b44ee/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateExchangesAndSteps.kt#L218)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

I think these should be renamed to the typical `@daily`, `@weekly` -- https://www.freebsd.org/cgi/man.cgi?crontab%285%29
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-06 17:09 UTC, stevenwarejones approved these changes
> Reviewed 1 of 11 files at r4.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/176)* status: 13 of 15 files reviewed, 3 unresolved discussions (waiting on @cs-sswaminathan, @efoxepstein, @kgaynor, @stevenwarejones, and @wangyaopw)



<!-- Sent from Reviewable.io -->

2021-08-06 17:19 UTC, wangyaopw approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/176)* status: 13 of 15 files reviewed, 2 unresolved discussions (waiting on @cs-sswaminathan, @efoxepstein, @kgaynor, @stevenwarejones, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FindReadyExchangeStep.kt, line 40 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/176#-MgNoMgD-MiMdEEBZ9Cs:-MgRTQZa1BmI2ubW-0YE:b32wwp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2723b7826cf92a981ea6e4f89a22d0b651efb221/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FindReadyExchangeStep.kt#L40)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

I prefer Optional to nulls inside of Result
</blockquote></details>

sg


<!-- Sent from Reviewable.io -->

2021-08-06 17:36 UTC, yunyeng reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/176)* status: 12 of 17 files reviewed, 2 unresolved discussions (waiting on @cs-sswaminathan, @efoxepstein, @kgaynor, @stevenwarejones, and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FindReadyExchangeStep.kt, line 40 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/176#-MgNoMgD-MiMdEEBZ9Cs:-MgRXJyL0sgkqaIfuBdo:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2723b7826cf92a981ea6e4f89a22d0b651efb221/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FindReadyExchangeStep.kt#L40)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

sg
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-06 17:40 UTC, efoxepstein approved these changes
> Reviewed 2 of 2 files at r7, 3 of 3 files at r8.
> Dismissed @stevenwarejones from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/176)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @cs-sswaminathan and @kgaynor)



<!-- Sent from Reviewable.io -->

2021-08-06 17:41 UTC, merged