feat: Call noise correction python binary from kotlin.
world-federation-of-advertisers/cross-media-measurement pull request #1803
Opened 2024-09-12 18:16 UTC by ple13

2024-09-12 18:16 UTC, wfa-reviewable commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1803)
<!-- Reviewable:end -->

2024-09-13 17:32 UTC, SanjayVas requested changes
> Reviewed 4 of 9 files at r1, 3 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1803)* status: 7 of 9 files reviewed, 4 unresolved discussions (waiting on @kungfucraig and @ple13)

___
*[`experimental/dp_consistency/src/main/kotlin/tools/BUILD.bazel` line 7 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1803#-O6gQwtU3_w87NoAydUD:-O6gQwtU3_w87NoAydUE:b-5ae441) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0fa5b2549f29022c848a53f231c30c066b57bfff/experimental/dp_consistency/src/main/kotlin/tools/BUILD.bazel#L7)):*
> ```Starlark
>     srcs = ["CorrectOriginReport.kt"],
>     data = [
>         "//experimental/dp_consistency/src/main/python/tools:correct_origin_report",
> ```

This needs to be in `resources` rather than `data` so it gets embedded in the final JAR. This means you need to use `ClassLoader.getJarResourcePath` from common-jvm and copy the file out to a temp location on the local file system before running.
___
*[`experimental/dp_consistency/src/main/kotlin/tools/CorrectOriginReport.kt` line 19 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1803#-O6gQ4MADC8kjsnG16u6:-O6gQ4MADC8kjsnG16u7:b-51z78n) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0fa5b2549f29022c848a53f231c30c066b57bfff/experimental/dp_consistency/src/main/kotlin/tools/CorrectOriginReport.kt#L19)):*
> ```Kotlin
> import java.util.logging.Logger
> 
> class CorrectOriginReport {
> ```

Add KDoc to all public symbols
___
*[`experimental/dp_consistency/src/main/kotlin/tools/CorrectOriginReport.kt` line 20 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1803#-O6gPzNC3cS4RoWCPKlE:-O6gPzNC3cS4RoWCPKlF:b-xdszab) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0fa5b2549f29022c848a53f231c30c066b57bfff/experimental/dp_consistency/src/main/kotlin/tools/CorrectOriginReport.kt#L20)):*
> ```Kotlin
> 
> class CorrectOriginReport {
>   fun correctReport(inputPath: String, unnoisedEdp: String, outputPath: String) {
> ```

Use specific types, e.g. Path or File.



_Code quote:_
```Kotlin
String
```
___
*[`experimental/dp_consistency/src/test/kotlin/tools/CorrectOriginReportTest.kt` line 30 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1803#-O6gQpZ3B5_zjsNhM-dl:-O6gQpZ3B5_zjsNhM-dm:beewmff) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0fa5b2549f29022c848a53f231c30c066b57bfff/experimental/dp_consistency/src/test/kotlin/tools/CorrectOriginReportTest.kt#L30)):*
> ```Kotlin
>     val reportCorrector: CorrectOriginReport = CorrectOriginReport()
>     val outputPath =
>       "experimental/dp_consistency/src/test/kotlin/tools/example_origin_corrected_report.xlsx"
> ```

I thought we were operating on the JSON serialization of a `Report` message?


<!-- Sent from Reviewable.io -->

2024-09-16 21:04 UTC, ple13 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1803)* status: 5 of 9 files reviewed, 4 unresolved discussions (waiting on @kungfucraig and @SanjayVas)

___
*[`experimental/dp_consistency/src/main/kotlin/tools/BUILD.bazel` line 7 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1803#-O6gQwtU3_w87NoAydUD:-O6w_okI8b-zRtnMy9n_:b-irl9jq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0fa5b2549f29022c848a53f231c30c066b57bfff/experimental/dp_consistency/src/main/kotlin/tools/BUILD.bazel#L7)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This needs to be in `resources` rather than `data` so it gets embedded in the final JAR. This means you need to use `ClassLoader.getJarResourcePath` from common-jvm and copy the file out to a temp location on the local file system before running.
</blockquote></details>

I've replaced `data` with `resources`. The code still works without ClassLoader.getJarResourcePath. I tried to load the binary with ClassLoader.getJarResourcePath, but keep seeing the error "invalid ELF headler". I had a look at this PR and notice that there is the java_native_libraries rule to handle native library, but it didn't work for the python binary. I wonder if we need to have new rules for python to make it work with ClassLoader.getJarResourcePath?
___
*[`experimental/dp_consistency/src/main/kotlin/tools/CorrectOriginReport.kt` line 19 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1803#-O6gQ4MADC8kjsnG16u6:-O6wbZMm1VpWpL9Is5Vl:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0fa5b2549f29022c848a53f231c30c066b57bfff/experimental/dp_consistency/src/main/kotlin/tools/CorrectOriginReport.kt#L19)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Add KDoc to all public symbols
</blockquote></details>

Done.
___
*[`experimental/dp_consistency/src/main/kotlin/tools/CorrectOriginReport.kt` line 20 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1803#-O6gPzNC3cS4RoWCPKlE:-O6wbXh-08cRbpA5WaqH:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0fa5b2549f29022c848a53f231c30c066b57bfff/experimental/dp_consistency/src/main/kotlin/tools/CorrectOriginReport.kt#L20)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Use specific types, e.g. Path or File.
</blockquote></details>

Done.
___
*[`experimental/dp_consistency/src/test/kotlin/tools/CorrectOriginReportTest.kt` line 30 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1803#-O6gQpZ3B5_zjsNhM-dl:-O6wbNOD55nbytGuGrck:bt64o1q) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0fa5b2549f29022c848a53f231c30c066b57bfff/experimental/dp_consistency/src/test/kotlin/tools/CorrectOriginReportTest.kt#L30)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I thought we were operating on the JSON serialization of a `Report` message?
</blockquote></details>

This will be in the next PR. This PR is to load a python binary and runs it in kotlin.


<!-- Sent from Reviewable.io -->

2024-09-16 21:43 UTC, SanjayVas requested changes
> Reviewed 1 of 9 files at r1, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1803)* status: 7 of 9 files reviewed, 4 unresolved discussions (waiting on @kungfucraig and @ple13)

___
*[`experimental/dp_consistency/src/main/kotlin/tools/BUILD.bazel` line 7 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1803#-O6gQwtU3_w87NoAydUD:-O6wjyv84SbFmONZMRvj:babvw25) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0fa5b2549f29022c848a53f231c30c066b57bfff/experimental/dp_consistency/src/main/kotlin/tools/BUILD.bazel#L7)):*
> I've replaced `data` with `resources`. The code still works without ClassLoader.getJarResourcePath

I'm willing to bet this would fail after a `bazel clean`, as removing it from `data` means that it is no longer copied into the runfiles tree.

> I had a look at this PR and notice that there is the java\_native\_libraries rule to handle native library, but it didn't work for the python binary. I wonder if we need to have new rules for python to make it work with ClassLoader.getJarResourcePath?

No, because we're not embedding a C++ native shared library. Instead, we're embedding a self-executing Python archive. The issue here is probably that you're not using the "python ZIP" as the resource and instead using the default output of py_binary. I believe this will just embed the top-level class, where you actually need to embed all py deps (and even a Python interpreter).

The way to get the python zip is to use the `python_zip_file` output group. e.g.

```starlark
filegroup(
    name = "correct_origin_report_pyzip",
    srcs = ["//experimental/dp_consistency/src/main/python/tools:correct_origin_report"],
    output_group = "python_zip_file",
)
```
___
*[`experimental/dp_consistency/src/main/kotlin/tools/CorrectOriginReport.kt` line 31 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1803#-O6wmMq09Q_YfNccccWe:-O6wmMq09Q_YfNccccWf:b-v9020g) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/178b19a432ef1893ec50c96a5b8f35135bc93825/experimental/dp_consistency/src/main/kotlin/tools/CorrectOriginReport.kt#L31)):*
> ```Kotlin
>    *
>    * @param inputPath The path to the input report.
>    * @param unnoisedEdp The list of EDPs that do not add noise to their measurements.
> ```

1. This says a list but the type is `String`
2. How are the EDPs referenced? Meaning is this a list of DataProvider resource names?



_Code quote:_
```Kotlin
The list of EDPs
```
___
*[`experimental/dp_consistency/src/test/kotlin/tools/CorrectOriginReportTest.kt` line 30 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1803#-O6gQpZ3B5_zjsNhM-dl:-O6wl9lF1aKgJ-AetyDy:bybwfzt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0fa5b2549f29022c848a53f231c30c066b57bfff/experimental/dp_consistency/src/test/kotlin/tools/CorrectOriginReportTest.kt#L30)):*
<details><summary><i>Previously, ple13 (Phi) wrote…</i></summary><blockquote>

This will be in the next PR. This PR is to load a python binary and runs it in kotlin.
</blockquote></details>

The binary it should load is the one that operates on the JSON file. Meaning we shouldn't be checking in a test Excel spreadsheet.
___
*[`experimental/dp_consistency/src/test/kotlin/tools/example_origin_report.xlsx` line 0 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1803#-O6wlOzbDPg2xzvIZFY1:-O6wlLco6C6RF2jdCRZt:b-tyxpvt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/178b19a432ef1893ec50c96a5b8f35135bc93825/experimental/dp_consistency/src/test/kotlin/tools/example_origin_report.xlsx#L0)):*
This must be in JSON format.


<!-- Sent from Reviewable.io -->

2024-09-17 15:38 UTC, kungfucraig requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1803)* status: 7 of 9 files reviewed, 5 unresolved discussions (waiting on @ple13 and @SanjayVas)

___
*[`experimental/dp_consistency/src/main/kotlin/tools/CorrectOriginReport.kt` line 25 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1803#-O7-cgKY3tap8To57MRr:-O7-cgKY3tap8To57MRs:b5jrgyk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/875164caa8b5572a0bc1f1fc653a7647e0e5f943/experimental/dp_consistency/src/main/kotlin/tools/CorrectOriginReport.kt#L25)):*
> ```Kotlin
>  * This depends on the python library correct_origin_report for noise correction.
>  */
> class CorrectOriginReport {
> ```

Is this the inteface we expect Origin to interact with?


<!-- Sent from Reviewable.io -->

2024-10-02 20:18 UTC, ple13 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1803)* status: 2 of 20 files reviewed, 5 unresolved discussions (waiting on @kungfucraig and @SanjayVas)

___
*[`experimental/dp_consistency/src/main/kotlin/tools/BUILD.bazel` line 7 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1803#-O6gQwtU3_w87NoAydUD:-O8DqTNWDeYbYM10e37d:b-lnoa7t) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0fa5b2549f29022c848a53f231c30c066b57bfff/experimental/dp_consistency/src/main/kotlin/tools/BUILD.bazel#L7)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> I've replaced `data` with `resources`. The code still works without ClassLoader.getJarResourcePath

I'm willing to bet this would fail after a `bazel clean`, as removing it from `data` means that it is no longer copied into the runfiles tree.

> I had a look at this PR and notice that there is the java\_native\_libraries rule to handle native library, but it didn't work for the python binary. I wonder if we need to have new rules for python to make it work with ClassLoader.getJarResourcePath?

No, because we're not embedding a C++ native shared library. Instead, we're embedding a self-executing Python archive. The issue here is probably that you're not using the "python ZIP" as the resource and instead using the default output of py_binary. I believe this will just embed the top-level class, where you actually need to embed all py deps (and even a Python interpreter).

The way to get the python zip is to use the `python_zip_file` output group. e.g.

```starlark
filegroup(
    name = "correct_origin_report_pyzip",
    srcs = ["//experimental/dp_consistency/src/main/python/tools:correct_origin_report"],
    output_group = "python_zip_file",
)
```
</blockquote></details>

When I tried to load the binary or zip file with Runtime.getRuntime().load(/path/to/binary), it complains that the ELF header is not valid. It looks like the issue is due to incorrect dependencies used. I'm fixing this.
Detailed error message:
"java.lang.UnsatisfiedLinkError: /some/path/native8861144412253610922correct_origin_report: invalid ELF header
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:232)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2394)
	at java.base/java.lang.Runtime.load0(Runtime.java:755)
	at java.base/java.lang.System.load(System.java:1957)
	at org.wfanet.measurement.common.ClassLoaderResourcesKt.load(ClassLoaderResources.kt:59)
	at experimental.dp_consistency.src.main.kotlin.tools.CorrectOriginReport.<clinit>(CorrectOriginReport.kt:159)
	at experimental.dp_consistency.src.test.kotlin.tools.CorrectOriginReportTest.run correct report successfully(CorrectOriginReportTest.kt:161)"
___
*[`experimental/dp_consistency/src/main/kotlin/tools/CorrectOriginReport.kt` line 31 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1803#-O6wmMq09Q_YfNccccWe:-O8Dr39E676lB2_ZH4NG:b-n8zqiz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/178b19a432ef1893ec50c96a5b8f35135bc93825/experimental/dp_consistency/src/main/kotlin/tools/CorrectOriginReport.kt#L31)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

1. This says a list but the type is `String`
2. How are the EDPs referenced? Meaning is this a list of DataProvider resource names?
</blockquote></details>

This has been changed. When reading the report directly, we will get the standard deviation for each of the measurement. So we do not need a list of unnoised edps any more.
___
*[`experimental/dp_consistency/src/main/kotlin/tools/CorrectOriginReport.kt` line 25 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1803#-O7-cgKY3tap8To57MRr:-O8DqjvT6a4jchJFiFUQ:btlksdv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/875164caa8b5572a0bc1f1fc653a7647e0e5f943/experimental/dp_consistency/src/main/kotlin/tools/CorrectOriginReport.kt#L25)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Is this the inteface we expect Origin to interact with?
</blockquote></details>

They requested that the input is a json representation of the report and the corrected report also in json format.
___
*[`experimental/dp_consistency/src/test/kotlin/tools/CorrectOriginReportTest.kt` line 30 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1803#-O6gQpZ3B5_zjsNhM-dl:-O8DrOb92G3uJ3XUusS7:bjxelm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0fa5b2549f29022c848a53f231c30c066b57bfff/experimental/dp_consistency/src/test/kotlin/tools/CorrectOriginReportTest.kt#L30)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The binary it should load is the one that operates on the JSON file. Meaning we shouldn't be checking in a test Excel spreadsheet.
</blockquote></details>

Done. Now the binary read a report in JSON format.
___
*[`experimental/dp_consistency/src/test/kotlin/tools/example_origin_report.xlsx` line  at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1803#-O6wlOzbDPg2xzvIZFY1:-O8DrV7u8_tDHfwMkFTk:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/178b19a432ef1893ec50c96a5b8f35135bc93825/experimental/dp_consistency/src/test/kotlin/tools/example_origin_report.xlsx#L)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This must be in JSON format.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-10-02 22:47 UTC, SanjayVas requested changes
> Reviewed 2 of 18 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1803)* status: 4 of 20 files reviewed, 5 unresolved discussions (waiting on @kungfucraig and @ple13)

___
*[`experimental/dp_consistency/src/main/kotlin/tools/BUILD.bazel` line 7 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1803#-O6gQwtU3_w87NoAydUD:-O8EP1d_0uPc0PHn1Hjr:b-9zwuys) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0fa5b2549f29022c848a53f231c30c066b57bfff/experimental/dp_consistency/src/main/kotlin/tools/BUILD.bazel#L7)):*
<details><summary><i>Previously, ple13 (Phi) wrote…</i></summary><blockquote>

When I tried to load the binary or zip file with Runtime.getRuntime().load(/path/to/binary), it complains that the ELF header is not valid. It looks like the issue is due to incorrect dependencies used. I'm fixing this.
Detailed error message:
"java.lang.UnsatisfiedLinkError: /some/path/native8861144412253610922correct_origin_report: invalid ELF header
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:232)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2394)
	at java.base/java.lang.Runtime.load0(Runtime.java:755)
	at java.base/java.lang.System.load(System.java:1957)
	at org.wfanet.measurement.common.ClassLoaderResourcesKt.load(ClassLoaderResources.kt:59)
	at experimental.dp_consistency.src.main.kotlin.tools.CorrectOriginReport.<clinit>(CorrectOriginReport.kt:159)
	at experimental.dp_consistency.src.test.kotlin.tools.CorrectOriginReportTest.run correct report successfully(CorrectOriginReportTest.kt:161)"
</blockquote></details>

You're calling the wrong function. Call `ClassLoader.getJarResourcePath` and copy out the file the same way that `Runtime.load` does. You don't actually want to call `Runtime.load` as that is for loading a native library, where all you're trying to do is extract a file from the JAR.
___
*[`experimental/dp_consistency/src/test/kotlin/tools/CorrectOriginReportTest.kt` line 172 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1803#-O8EOdQp-kUBuYtWFrcD:-O8EOdQp-kUBuYtWFrcE:bkm03oe) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ed8654e2dc8abe52cdb525230c5c624600529dcf/experimental/dp_consistency/src/test/kotlin/tools/CorrectOriginReportTest.kt#L172)):*
> ```Kotlin
>     val measurementFrequencyInSeconds = 604800L // 7 days has 604800 seconds.
>     val REPORT_TEMPLATE =
>       """
> ```

Don't have giant textproto or JSON strings in the test. Put these in files referenced in the `data` attribute and load them from `Runfiles`.


<!-- Sent from Reviewable.io -->

2024-10-02 23:25 UTC, SanjayVas requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1803)* status: 4 of 20 files reviewed, 9 unresolved discussions (waiting on @kungfucraig and @ple13)

___
*[`experimental/dp_consistency/src/main/kotlin/tools/CorrectOriginReport.kt` line 15 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1803#-O8EPuag1Wixfmz4i271:-O8EPuah1Z1_Q63rQXjw:bj40kzd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/178b19a432ef1893ec50c96a5b8f35135bc93825/experimental/dp_consistency/src/main/kotlin/tools/CorrectOriginReport.kt#L15)):*
> ```Kotlin
> // limitations under the License.
> 
> package experimental.dp_consistency.src.main.kotlin.tools
> ```

nit: We use the `tools` package name to refer to CLI tools by convention.



_Code quote:_
```Kotlin
tools
```
___
*[`experimental/dp_consistency/src/main/kotlin/tools/CorrectOriginReport.kt` line 27 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1803#-O8EWxuF24IuDRET4xI1:-O8EWxuF24IuDRET4xI2:b93gr9t) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ed8654e2dc8abe52cdb525230c5c624600529dcf/experimental/dp_consistency/src/main/kotlin/tools/CorrectOriginReport.kt#L27)):*
> ```Kotlin
> import org.wfanet.measurement.reporting.v2alpha.report
> 
> /** Corrects noisy measurements in a report using the Python library `correct_origin_report`. */
> ```

nit: implementation detail that doesn't belong in public class documentation



_Code quote:_
```Kotlin
using the Python library `correct_origin_report`
```
___
*[`experimental/dp_consistency/src/main/kotlin/tools/CorrectOriginReport.kt` line 28 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1803#-O8EQhEx8yg1liD_ayuD:-O8EQ69001Yn1tcNCKd_:bwlw368) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ed8654e2dc8abe52cdb525230c5c624600529dcf/experimental/dp_consistency/src/main/kotlin/tools/CorrectOriginReport.kt#L28)):*
> ```Kotlin
> 
> /** Corrects noisy measurements in a report using the Python library `correct_origin_report`. */
> class CorrectOriginReport {
> ```

nit: I mentioned this on the chat thread: I thought we agreed to stop using "correct" or "correction" as that implies that our Report is incorrect when it's not. IIUC this is just doing consistency adjustments. I'm not happy that we've continued to use the phrase "noise correction" in meetings.

@kungfucraig 
___
*[`experimental/dp_consistency/src/main/kotlin/tools/ReportConverter.kt` line 31 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1803#-O8EXrdF48wC_2CFt_nm:-O8EXrdF48wC_2CFt_nn:b-6pcwox) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ed8654e2dc8abe52cdb525230c5c624600529dcf/experimental/dp_consistency/src/main/kotlin/tools/ReportConverter.kt#L31)):*
> ```Kotlin
> data class SetOperationSummary(val isCumulative: Boolean, val setOperation: String)
> 
> fun getReportFromJsonString(reportAsJsonString: String): Report {
> ```

Group these into a ReportConversion object rather than polluting the namespace with symbols. See https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/docs/code-style.md#kotlin (the advice for constants and static properties also applies to non-extension functions)


<!-- Sent from Reviewable.io -->

2024-10-04 18:07 UTC, ple13 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1803)* status: 3 of 22 files reviewed, 9 unresolved discussions (waiting on @kungfucraig and @SanjayVas)

___
*[`experimental/dp_consistency/src/test/kotlin/tools/CorrectOriginReportTest.kt` line 172 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1803#-O8EOdQp-kUBuYtWFrcD:-O8ItrZ689K1WkQUGCvg:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ed8654e2dc8abe52cdb525230c5c624600529dcf/experimental/dp_consistency/src/test/kotlin/tools/CorrectOriginReportTest.kt#L172)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Don't have giant textproto or JSON strings in the test. Put these in files referenced in the `data` attribute and load them from `Runfiles`.
</blockquote></details>

Done.
___
*[`experimental/dp_consistency/src/main/kotlin/tools/BUILD.bazel` line 7 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1803#-O6gQwtU3_w87NoAydUD:-O8IoRsKBG5M6DMNi4Lq:b9o8z88) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0fa5b2549f29022c848a53f231c30c066b57bfff/experimental/dp_consistency/src/main/kotlin/tools/BUILD.bazel#L7)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

You're calling the wrong function. Call `ClassLoader.getJarResourcePath` and copy out the file the same way that `Runtime.load` does. You don't actually want to call `Runtime.load` as that is for loading a native library, where all you're trying to do is extract a file from the JAR.
</blockquote></details>

Thanks a lot. I copied the package to the local directory and it works.
___
*[`experimental/dp_consistency/src/main/kotlin/tools/CorrectOriginReport.kt` line 15 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1803#-O8EPuag1Wixfmz4i271:-O8NhUb5A4fVYs0HGwWr:b-sy0iag) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/178b19a432ef1893ec50c96a5b8f35135bc93825/experimental/dp_consistency/src/main/kotlin/tools/CorrectOriginReport.kt#L15)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: We use the `tools` package name to refer to CLI tools by convention.
</blockquote></details>

I've updated the package name to `reporting`.
___
*[`experimental/dp_consistency/src/main/kotlin/tools/CorrectOriginReport.kt` line 27 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1803#-O8EWxuF24IuDRET4xI1:-O8NhauL7qIhJNRulemE:b26gvwm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ed8654e2dc8abe52cdb525230c5c624600529dcf/experimental/dp_consistency/src/main/kotlin/tools/CorrectOriginReport.kt#L27)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: implementation detail that doesn't belong in public class documentation
</blockquote></details>

I've removed the implement details.
___
*[`experimental/dp_consistency/src/main/kotlin/tools/CorrectOriginReport.kt` line 28 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1803#-O8EQhEx8yg1liD_ayuD:-O8NhgS3Ad01_t22S_V0:b-nuieg5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ed8654e2dc8abe52cdb525230c5c624600529dcf/experimental/dp_consistency/src/main/kotlin/tools/CorrectOriginReport.kt#L28)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: I mentioned this on the chat thread: I thought we agreed to stop using "correct" or "correction" as that implies that our Report is incorrect when it's not. IIUC this is just doing consistency adjustments. I'm not happy that we've continued to use the phrase "noise correction" in meetings.

@kungfucraig
</blockquote></details>

Name is updated to `ReportPostProcessing`.
___
*[`experimental/dp_consistency/src/main/kotlin/tools/ReportConverter.kt` line 31 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1803#-O8EXrdF48wC_2CFt_nm:-O8ItoaF2z56OWCOWDxV:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ed8654e2dc8abe52cdb525230c5c624600529dcf/experimental/dp_consistency/src/main/kotlin/tools/ReportConverter.kt#L31)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Group these into a ReportConversion object rather than polluting the namespace with symbols. See https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/docs/code-style.md#kotlin (the advice for constants and static properties also applies to non-extension functions)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-10-04 19:00 UTC, SanjayVas requested changes
> Reviewed 2 of 13 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1803)* status: 5 of 22 files reviewed, 13 unresolved discussions (waiting on @kungfucraig and @ple13)

___
*[`experimental/dp_consistency/src/main/kotlin/reporting/BUILD.bazel` line 5 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1803#-O8Nocdj5L8RProhjC_7:-O8Nocdj5L8RProhjC_8:b-dxclks) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2f3aca63d5316db43ac15bb4b37144e7a6a85d7a/experimental/dp_consistency/src/main/kotlin/reporting/BUILD.bazel#L5)):*
> ```Starlark
> package(default_visibility = ["//visibility:public"])
> 
> kt_jvm_binary(
> ```

We're providing a library, not a binary. This means there should also not be a `main` function.
___
*[`experimental/dp_consistency/src/main/kotlin/reporting/ReportConverter.kt` line 1 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1803#-O8No-ZW2xhNHXXWSLxz:-O8No-ZW2xhNHXXWSLy-:btcxjcg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2f3aca63d5316db43ac15bb4b37144e7a6a85d7a/experimental/dp_consistency/src/main/kotlin/reporting/ReportConverter.kt#L1)):*
> ```Kotlin
> // Copyright 2024 The Cross-Media Measurement Authors
> ```

Rename this file ReportConversion to match the top level object.
___
*[`experimental/dp_consistency/src/main/kotlin/reporting/ReportConverter.kt` line 58 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1803#-O8No5iT0bxf0hwY4A-f:-O8No5iT0bxf0hwY4A-g:b-fpodcg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2f3aca63d5316db43ac15bb4b37144e7a6a85d7a/experimental/dp_consistency/src/main/kotlin/reporting/ReportConverter.kt#L58)):*
> ```Kotlin
> }
> 
> fun getMeasurementPolicy(tag: String): String {
> ```

All of the non-extension functions need to be moved inside an object. For this file, that means the ReportConversion object above.
___
*[`experimental/dp_consistency/src/main/kotlin/reporting/ReportPostProcessing.kt` line 15 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1803#-O8Nq4KK7MD3s3KD6dU3:-O8Nq4KK7MD3s3KD6dU4:b-w72fw5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2f3aca63d5316db43ac15bb4b37144e7a6a85d7a/experimental/dp_consistency/src/main/kotlin/reporting/ReportPostProcessing.kt#L15)):*
> ```Kotlin
> // limitations under the License.
> 
> package experimental.dp_consistency.src.main.kotlin.reporting
> ```

1. Kotlin packages mirror the directory structure under src/main/kotlin or src/test/kotlin
2. The package path should mirror wherever this will end up when graduated out of experimental. This would be some package under `org.wfanet.measurement.reporting`



_Suggestion:_
```Kotlin
package org.wfanet.measurement.reporting.postprocessing
```
___
*[`experimental/dp_consistency/src/main/kotlin/reporting/ReportPostProcessing.kt` line 35 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1803#-O8Np6c4BRraSr1AGMXu:-O8Np6c5EJXTcx2Mjr8p:bar1v56) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2f3aca63d5316db43ac15bb4b37144e7a6a85d7a/experimental/dp_consistency/src/main/kotlin/reporting/ReportPostProcessing.kt#L35)):*
> ```Kotlin
> 
> /** Corrects noisy measurements in a report. */
> class ReportPostProcessing {
> ```

There doesn't appear to be any instance state, so this could be an object.



_Suggestion:_
```Kotlin
object
```
___
*[`experimental/dp_consistency/src/main/kotlin/reporting/ReportPostProcessing.kt` line 37 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1803#-O8NtPKf-2nHt4yfbSa9:-O8NtPKg2UAiEOjYuUPM:b-h28rva) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2f3aca63d5316db43ac15bb4b37144e7a6a85d7a/experimental/dp_consistency/src/main/kotlin/reporting/ReportPostProcessing.kt#L37)):*
> ```Kotlin
> class ReportPostProcessing {
>   /**
>    * Corrects the inconsistent measurements in the [reportAsJsonString] and returns a corrected
> ```

nit: use KDoc tags (e.g. `@param`, `@return`) as appropriate.

I'd expect the param to be described as "standard JSON serialization of a Report message".
___
*[`experimental/dp_consistency/src/main/kotlin/reporting/ReportPostProcessing.kt` line 40 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1803#-O8NqxMG1J8dRztkXG7N:-O8NqxMG1J8dRztkXG7O:b-qieyy) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2f3aca63d5316db43ac15bb4b37144e7a6a85d7a/experimental/dp_consistency/src/main/kotlin/reporting/ReportPostProcessing.kt#L40)):*
> ```Kotlin
>    * report in JSON format.
>    */
>   fun processReport(reportAsJsonString: String): String {
> ```

nit: Since the parameter type is not specific (i.e. `String`), indicate the JSON part in the function name rather than the parameter name.

If we had a specific type here, then we could just make all functions overloads of `processReport`. Instead, just the protobuf one would be called `processReport` and anything that deals with strings would need a different name. e.g. if we added something that used an unparsed XML string, it would be named `processReportXml`.



_Suggestion:_
```Kotlin
  fun processReportJson(report: String): String {
```
___
*[`experimental/dp_consistency/src/main/kotlin/reporting/ReportPostProcessing.kt` line 46 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1803#-O8NsQVV9yq688L_veJi:-O8NsQVWCCGlbgpsqtfH:bos3zh5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2f3aca63d5316db43ac15bb4b37144e7a6a85d7a/experimental/dp_consistency/src/main/kotlin/reporting/ReportPostProcessing.kt#L46)):*
> ```Kotlin
>     for (reportSummary in reportSummaries) {
>       correctedMeasurementsMap.putAll(
>         processReportSummary(JsonFormat.printer().print(reportSummary))
> ```

JSON should only be used a the edges. We should immediately convert to protobuf.

I'd expect this function to call a `processReport` function that takes and returns a Report message.


<!-- Sent from Reviewable.io -->

2024-10-04 19:03 UTC, SanjayVas requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1803)* status: 5 of 22 files reviewed, 14 unresolved discussions (waiting on @kungfucraig and @ple13)

___
*[`experimental/dp_consistency/src/main/kotlin/reporting/ReportPostProcessing.kt` line 164 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1803#-O8NuLgv45Snrtui3arl:-O8NtvVx59U68Ks9MG7a:b-scow1h) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2f3aca63d5316db43ac15bb4b37144e7a6a85d7a/experimental/dp_consistency/src/main/kotlin/reporting/ReportPostProcessing.kt#L164)):*
> ```Kotlin
>     init {
>       // Copies python zip package from JAR to local directory.
>       Files.copy(
> ```

Don't assume that any directory other than tmp is writable. This should be copied to a temporary file and deleted on exit.


<!-- Sent from Reviewable.io -->

2024-10-04 21:30 UTC, kungfucraig requested changes
> Reviewed 1 of 9 files at r1, 8 of 18 files at r5, 9 of 13 files at r6, 3 of 5 files at r7.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1803)* status: 20 of 22 files reviewed, 17 unresolved discussions (waiting on @ple13 and @SanjayVas)

___
*[`experimental/dp_consistency/src/main/kotlin/reporting/ReportConverter.kt` line 27 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1803#-O8MxReKBWWPxuKsoWwS:-O8MxReKBWWPxuKsoWwT:b-xju08o) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a7f6dff3c34c73196021c3b81b0dac21decd9521/experimental/dp_consistency/src/main/kotlin/reporting/ReportConverter.kt#L27)):*
> ```Kotlin
> import org.wfanet.measurement.reporting.v2alpha.report
> 
> data class ReportingSetSummary(val measurementPolicy: String, val dataProviders: List<String>)
> ```

measurementPolicy is one of AMI, Custom, or MRC? 
___
*[`experimental/dp_consistency/src/main/kotlin/reporting/ReportConverter.kt` line 31 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1803#-O8MxaPq5VbptmcCC6zJ:-O8MxIu_2fhFI3xoJ9TI:b-bjpaea) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a7f6dff3c34c73196021c3b81b0dac21decd9521/experimental/dp_consistency/src/main/kotlin/reporting/ReportConverter.kt#L31)):*
> ```Kotlin
> data class SetOperationSummary(val isCumulative: Boolean, val setOperation: String)
> 
> object ReportConversion {
> ```

The file name should match the name of the object given it's the only object in the file.
___
*[`experimental/dp_consistency/src/main/kotlin/reporting/ReportPostProcessing.kt` line 46 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1803#-O8NsQVV9yq688L_veJi:-O8OQH_WDrVsNStiesv9:b-je7um5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2f3aca63d5316db43ac15bb4b37144e7a6a85d7a/experimental/dp_consistency/src/main/kotlin/reporting/ReportPostProcessing.kt#L46)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

JSON should only be used a the edges. We should immediately convert to protobuf.

I'd expect this function to call a `processReport` function that takes and returns a Report message.
</blockquote></details>

Ultimately this JSON blob is getting sent to Python, but we could send a text proto instead.
___
*[`experimental/dp_consistency/src/main/kotlin/reporting/ReportPostProcessing.kt` line 62 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1803#-O8OQfiS07XWpCvaYTAm:-O8OQfiS07XWpCvaYTAn:b-zi9amg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2f3aca63d5316db43ac15bb4b37144e7a6a85d7a/experimental/dp_consistency/src/main/kotlin/reporting/ReportPostProcessing.kt#L62)):*
> ```Kotlin
>     logger.info { "Start processing report.." }
>     val processBuilder =
>       ProcessBuilder("python3", resourcePath.name, "--report_summary=$reportSummaryAsJsonString")
> ```

What are the limits on the size of a command line argument, and will this overrun them?
___
*[`experimental/dp_consistency/src/main/python/tools/post_process_origin_report.py` line 113 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1803#-O8OR9ZN6xAuEajsBONz:-O8OR9ZO3x4Idct3ZAcN:b-tao81h) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2f3aca63d5316db43ac15bb4b37144e7a6a85d7a/experimental/dp_consistency/src/main/python/tools/post_process_origin_report.py#L113)):*
> ```Python
> # set operations (cumulative and union).
> # TODO(@ple13): Extend the function to support custom measurements and composite
> #  set operations such as difference, incremental.
> ```

So no support for unique reach yet?


<!-- Sent from Reviewable.io -->

2024-10-07 17:27 UTC, SanjayVas requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1803)* status: 20 of 22 files reviewed, 18 unresolved discussions (waiting on @kungfucraig and @ple13)

___
*[`experimental/dp_consistency/src/main/kotlin/reporting/ReportPostProcessing.kt` line 46 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1803#-O8NsQVV9yq688L_veJi:-O8bzcDj3yHxC7o1or21:b-9nwiqr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2f3aca63d5316db43ac15bb4b37144e7a6a85d7a/experimental/dp_consistency/src/main/kotlin/reporting/ReportPostProcessing.kt#L46)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Ultimately this JSON blob is getting sent to Python, but we could send a text proto instead.
</blockquote></details>

I don't see a reason not to use binary proto for the Python executable given that it'll never be used directly. 

To clarify, the issue is that the JSON is not just being passed through to the Python executable. It's being parsed here, and once parsed it shouldn't be converted back to JSON until the end of the operation.
___
*[`experimental/dp_consistency/src/main/kotlin/reporting/ReportPostProcessing.kt` line 62 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1803#-O8c-W2MDLiDZpq56R6g:-O8c-W2MDLiDZpq56R6h:b-qa3c2s) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2f3aca63d5316db43ac15bb4b37144e7a6a85d7a/experimental/dp_consistency/src/main/kotlin/reporting/ReportPostProcessing.kt#L62)):*
> ```Kotlin
>     logger.info { "Start processing report.." }
>     val processBuilder =
>       ProcessBuilder("python3", resourcePath.name, "--report_summary=$reportSummaryAsJsonString")
> ```

I thought the pyzip was executable on its own.



_Code quote:_
```Kotlin
"python3",
```


<!-- Sent from Reviewable.io -->

2024-10-07 20:57 UTC, ple13 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1803)* status: 13 of 22 files reviewed, 16 unresolved discussions (waiting on @kungfucraig and @SanjayVas)

___
*[`experimental/dp_consistency/src/main/kotlin/reporting/BUILD.bazel` line 5 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1803#-O8Nocdj5L8RProhjC_7:-O8cZfbDCk73AItzIn6b:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2f3aca63d5316db43ac15bb4b37144e7a6a85d7a/experimental/dp_consistency/src/main/kotlin/reporting/BUILD.bazel#L5)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

We're providing a library, not a binary. This means there should also not be a `main` function.
</blockquote></details>

Done.
___
*[`experimental/dp_consistency/src/main/kotlin/reporting/ReportConverter.kt` line 27 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1803#-O8MxReKBWWPxuKsoWwS:-O8cVn7qCe9UaCdLshrk:b-ddgnw7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a7f6dff3c34c73196021c3b81b0dac21decd9521/experimental/dp_consistency/src/main/kotlin/reporting/ReportConverter.kt#L27)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

measurementPolicy is one of AMI, Custom, or MRC?
</blockquote></details>

Yes, the measurement policy is one of these.
___
*[`experimental/dp_consistency/src/main/kotlin/reporting/ReportConverter.kt` line 31 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1803#-O8MxaPq5VbptmcCC6zJ:-O8c8pnZ1OdValqcyyf2:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a7f6dff3c34c73196021c3b81b0dac21decd9521/experimental/dp_consistency/src/main/kotlin/reporting/ReportConverter.kt#L31)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

The file name should match the name of the object given it's the only object in the file.
</blockquote></details>

Done.
___
*[`experimental/dp_consistency/src/main/kotlin/reporting/ReportConverter.kt` line 1 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1803#-O8No-ZW2xhNHXXWSLxz:-O8c8eUE6NyTaBa8-qLc:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2f3aca63d5316db43ac15bb4b37144e7a6a85d7a/experimental/dp_consistency/src/main/kotlin/reporting/ReportConverter.kt#L1)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Rename this file ReportConversion to match the top level object.
</blockquote></details>

Done.
___
*[`experimental/dp_consistency/src/main/kotlin/reporting/ReportConverter.kt` line 58 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1803#-O8No5iT0bxf0hwY4A-f:-O8cVlhQ1Ta_A6l6up28:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2f3aca63d5316db43ac15bb4b37144e7a6a85d7a/experimental/dp_consistency/src/main/kotlin/reporting/ReportConverter.kt#L58)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

All of the non-extension functions need to be moved inside an object. For this file, that means the ReportConversion object above.
</blockquote></details>

Done.
___
*[`experimental/dp_consistency/src/main/kotlin/reporting/ReportPostProcessing.kt` line 15 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1803#-O8Nq4KK7MD3s3KD6dU3:-O8cTrWrEDMZUifHun_l:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2f3aca63d5316db43ac15bb4b37144e7a6a85d7a/experimental/dp_consistency/src/main/kotlin/reporting/ReportPostProcessing.kt#L15)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

1. Kotlin packages mirror the directory structure under src/main/kotlin or src/test/kotlin
2. The package path should mirror wherever this will end up when graduated out of experimental. This would be some package under `org.wfanet.measurement.reporting`
</blockquote></details>

Done.
___
*[`experimental/dp_consistency/src/main/kotlin/reporting/ReportPostProcessing.kt` line 35 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1803#-O8Np6c4BRraSr1AGMXu:-O8cWFQx8rvcfVJtQKJk:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2f3aca63d5316db43ac15bb4b37144e7a6a85d7a/experimental/dp_consistency/src/main/kotlin/reporting/ReportPostProcessing.kt#L35)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

There doesn't appear to be any instance state, so this could be an object.
</blockquote></details>

Done.
___
*[`experimental/dp_consistency/src/main/kotlin/reporting/ReportPostProcessing.kt` line 37 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1803#-O8NtPKf-2nHt4yfbSa9:-O8cZVW56Yljh9Gqtstn:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2f3aca63d5316db43ac15bb4b37144e7a6a85d7a/experimental/dp_consistency/src/main/kotlin/reporting/ReportPostProcessing.kt#L37)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: use KDoc tags (e.g. `@param`, `@return`) as appropriate.

I'd expect the param to be described as "standard JSON serialization of a Report message".
</blockquote></details>

Done.
___
*[`experimental/dp_consistency/src/main/kotlin/reporting/ReportPostProcessing.kt` line 40 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1803#-O8NqxMG1J8dRztkXG7N:-O8cY6AB5ngnd9gnTH2r:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2f3aca63d5316db43ac15bb4b37144e7a6a85d7a/experimental/dp_consistency/src/main/kotlin/reporting/ReportPostProcessing.kt#L40)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: Since the parameter type is not specific (i.e. `String`), indicate the JSON part in the function name rather than the parameter name.

If we had a specific type here, then we could just make all functions overloads of `processReport`. Instead, just the protobuf one would be called `processReport` and anything that deals with strings would need a different name. e.g. if we added something that used an unparsed XML string, it would be named `processReportXml`.
</blockquote></details>

Done.
___
*[`experimental/dp_consistency/src/main/kotlin/reporting/ReportPostProcessing.kt` line 46 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1803#-O8NsQVV9yq688L_veJi:-O8cYHDV7ZYHJr8gEJjQ:b-a4c3kb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2f3aca63d5316db43ac15bb4b37144e7a6a85d7a/experimental/dp_consistency/src/main/kotlin/reporting/ReportPostProcessing.kt#L46)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I don't see a reason not to use binary proto for the Python executable given that it'll never be used directly. 

To clarify, the issue is that the JSON is not just being passed through to the Python executable. It's being parsed here, and once parsed it shouldn't be converted back to JSON until the end of the operation.
</blockquote></details>

I've added a function `processReport` that takes input as a report proto, and output a report proto.
___
*[`experimental/dp_consistency/src/main/kotlin/reporting/ReportPostProcessing.kt` line 62 at r7](https://reviewable.io [...]

2024-10-07 21:17 UTC, SanjayVas requested changes
> Reviewed 3 of 18 files at r5, 5 of 9 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1803)* status: 17 of 22 files reviewed, 11 unresolved discussions (waiting on @kungfucraig and @ple13)

___
*[`experimental/dp_consistency/src/main/python/tools/BUILD.bazel` line 1 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1803#-O8cp66y1G_jhBHWMCrB:-O8cp66y1G_jhBHWMCrC:blz24g0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ffa54a0d4ff54867bb7d8abb0e2f5f3d28c26e22/experimental/dp_consistency/src/main/python/tools/BUILD.bazel#L1)):*
> ```Starlark
> load("@pip//:requirements.bzl", "requirement")
> ```

This should mirror the Kotlin package path. e.g. be under `src/main/python/wfa/measurement/reporting/processing`. (The top-level package would always be `wfa`, except for JVM languages where the convention is to reverse a domain that you own. Hence Kotlin uses `org.wfanet`.)
___
*[`experimental/dp_consistency/src/main/kotlin/reporting/ReportPostProcessing.kt` line 46 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1803#-O8NsQVV9yq688L_veJi:-O8cmSlH3ZXDwxXy1wn7:b-hrl5ew) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2f3aca63d5316db43ac15bb4b37144e7a6a85d7a/experimental/dp_consistency/src/main/kotlin/reporting/ReportPostProcessing.kt#L46)):*
<details><summary><i>Previously, ple13 (Phi) wrote…</i></summary><blockquote>

I've added a function `processReport` that takes input as a report proto, and output a report proto.
</blockquote></details>

This comment is not resolved as this still converted to JSON again. This means that `processReportSummary` and the Python executable must operate on binary protobuf.
___
*[`experimental/dp_consistency/src/main/kotlin/reporting/ReportPostProcessing.kt` line 62 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1803#-O8OQfiS07XWpCvaYTAm:-O8cm8mU9Tqcjg16nI6-:b-9d907) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2f3aca63d5316db43ac15bb4b37144e7a6a85d7a/experimental/dp_consistency/src/main/kotlin/reporting/ReportPostProcessing.kt#L62)):*
<details><summary><i>Previously, ple13 (Phi) wrote…</i></summary><blockquote>

It looks like this depends on the OS. For linux, we can check the max length using the cli `xargs --show-limits`. It looks like the limit on the argument length is a bit less than 2MB.
`xargs --show-limits
Your environment variables take up 4425 bytes
POSIX upper limit on argument length (this system): 2090679
POSIX smallest allowable upper limit on argument length (all systems): 4096
Maximum length of command we could actually use: 2086254
Size of command buffer we are actually using: 131072
Maximum parallelism (--max-procs must be no greater): 2147483647`
</blockquote></details>

I believe what @kungfucraig was implying was that the data should be read from stdin to avoid any issues with length limits.
___
*[`experimental/dp_consistency/src/main/kotlin/reporting/ReportPostProcessing.kt` line 62 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1803#-O8c-W2MDLiDZpq56R6g:-O8cnm4Y9M-U3fDQQ5Jw:b-qpxoi6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2f3aca63d5316db43ac15bb4b37144e7a6a85d7a/experimental/dp_consistency/src/main/kotlin/reporting/ReportPostProcessing.kt#L62)):*
<details><summary><i>Previously, ple13 (Phi) wrote…</i></summary><blockquote>

It didn't work without `python3` even after explicitly setting the zip to be executable.
</blockquote></details>

Looks like this is a bug. See https://github.com/bazelbuild/bazel/issues/17629

Add a todo referencing that bug. e.g.

```kotlin
// TODO(bazelbuild/bazel#17629): Execute the Python zip directly once this is fixed.
```
___
*[`experimental/dp_consistency/src/main/kotlin/reporting/ReportPostProcessing.kt` line 35 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1803#-O8cm07K--Z8Js1u17a0:-O8cm07K--Z8Js1u17a1:b2s2xsp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ffa54a0d4ff54867bb7d8abb0e2f5f3d28c26e22/experimental/dp_consistency/src/main/kotlin/reporting/ReportPostProcessing.kt#L35)):*
> ```Kotlin
> /** Corrects noisy measurements in a report. */
> object ReportPostProcessing {
>   val logger: Logger = Logger.getLogger(this::class.java.name)
> ```

It looks like these properties can be private
___
*[`experimental/dp_consistency/src/test/kotlin/reporting/BUILD.bazel` line 1 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1803#-O8cpjgzDZ1lQaFNB8fG:-O8cpjh-B_4oRF-SfBJy:b-xusze) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ffa54a0d4ff54867bb7d8abb0e2f5f3d28c26e22/experimental/dp_consistency/src/test/kotlin/reporting/BUILD.bazel#L1)):*
> ```Starlark
> load("@wfa_rules_kotlin_jvm//kotlin:defs.bzl", "kt_jvm_test")
> ```

The package path under src/test must mirror the package path under src/main


<!-- Sent from Reviewable.io -->

2024-10-08 10:34 UTC, ple13 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1803)* status: 4 of 34 files reviewed, 11 unresolved discussions (waiting on @kungfucraig and @SanjayVas)

___
*[`experimental/dp_consistency/src/main/kotlin/reporting/ReportPostProcessing.kt` line 46 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1803#-O8NsQVV9yq688L_veJi:-O8f35AqCjoHnCa0iL39:b-le0o30) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2f3aca63d5316db43ac15bb4b37144e7a6a85d7a/experimental/dp_consistency/src/main/kotlin/reporting/ReportPostProcessing.kt#L46)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This comment is not resolved as this still converted to JSON again. This means that `processReportSummary` and the Python executable must operate on binary protobuf.
</blockquote></details>

ah I see. I've updated the code.
___
*[`experimental/dp_consistency/src/main/kotlin/reporting/ReportPostProcessing.kt` line 62 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1803#-O8OQfiS07XWpCvaYTAm:-O8fSN268JgFzHXI9c6j:b-nmtctl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2f3aca63d5316db43ac15bb4b37144e7a6a85d7a/experimental/dp_consistency/src/main/kotlin/reporting/ReportPostProcessing.kt#L62)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I believe what @kungfucraig was implying was that the data should be read from stdin to avoid any issues with length limits.
</blockquote></details>

Thanks for the clarification. I've updated the python code to read the input from stdin other than taking an argument.
___
*[`experimental/dp_consistency/src/main/kotlin/reporting/ReportPostProcessing.kt` line 62 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1803#-O8c-W2MDLiDZpq56R6g:-O8f6qEVBonj73noRI1f:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2f3aca63d5316db43ac15bb4b37144e7a6a85d7a/experimental/dp_consistency/src/main/kotlin/reporting/ReportPostProcessing.kt#L62)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Looks like this is a bug. See https://github.com/bazelbuild/bazel/issues/17629

Add a todo referencing that bug. e.g.

```kotlin
// TODO(bazelbuild/bazel#17629): Execute the Python zip directly once this is fixed.
```
</blockquote></details>

Done.
___
*[`experimental/dp_consistency/src/main/kotlin/reporting/ReportPostProcessing.kt` line 35 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1803#-O8cm07K--Z8Js1u17a0:-O8ctAQD8l4XOWWt2Sjt:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ffa54a0d4ff54867bb7d8abb0e2f5f3d28c26e22/experimental/dp_consistency/src/main/kotlin/reporting/ReportPostProcessing.kt#L35)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

It looks like these properties can be private
</blockquote></details>

Done.
___
*[`experimental/dp_consistency/src/main/python/tools/BUILD.bazel` line 1 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1803#-O8cp66y1G_jhBHWMCrB:-O8fNbFo9PTEv603es60:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ffa54a0d4ff54867bb7d8abb0e2f5f3d28c26e22/experimental/dp_consistency/src/main/python/tools/BUILD.bazel#L1)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This should mirror the Kotlin package path. e.g. be under `src/main/python/wfa/measurement/reporting/processing`. (The top-level package would always be `wfa`, except for JVM languages where the convention is to reverse a domain that you own. Hence Kotlin uses `org.wfanet`.)
</blockquote></details>

Done.
___
*[`experimental/dp_consistency/src/test/kotlin/reporting/BUILD.bazel` line 1 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1803#-O8cpjgzDZ1lQaFNB8fG:-O8fN_Lk-zg-K6mMdW-z:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ffa54a0d4ff54867bb7d8abb0e2f5f3d28c26e22/experimental/dp_consistency/src/test/kotlin/reporting/BUILD.bazel#L1)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The package path under src/test must mirror the package path under src/main
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-10-08 15:44 UTC, kungfucraig approved these changes
> Reviewed 1 of 9 files at r8, 30 of 30 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1803)* status: all files reviewed, 7 unresolved discussions (waiting on @SanjayVas)

___
*[`experimental/dp_consistency/src/main/kotlin/reporting/ReportConverter.kt` line 27 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1803#-O8MxReKBWWPxuKsoWwS:-O8gedhq2-KRLv9CUU5v:byykuz6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a7f6dff3c34c73196021c3b81b0dac21decd9521/experimental/dp_consistency/src/main/kotlin/reporting/ReportConverter.kt#L27)):*
<details><summary><i>Previously, ple13 (Phi) wrote…</i></summary><blockquote>

Yes, the measurement policy is one of these.
</blockquote></details>

A bit of documentation for the data classes would be helpful.
___
*[`experimental/dp_consistency/src/main/kotlin/reporting/ReportPostProcessing.kt` line 46 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1803#-O8NsQVV9yq688L_veJi:-O8gf1Yr-BRbiv0ywS5z:b-i4qi5t) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2f3aca63d5316db43ac15bb4b37144e7a6a85d7a/experimental/dp_consistency/src/main/kotlin/reporting/ReportPostProcessing.kt#L46)):*
<details><summary><i>Previously, ple13 (Phi) wrote…</i></summary><blockquote>

ah I see. I've updated the code.
</blockquote></details>

I'm happy either way, but the text proto has a major benefit of being readable and it's not big, so... 


<!-- Sent from Reviewable.io -->

2024-10-09 10:41 UTC, ple13 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1803)* status: 22 of 34 files reviewed, 4 unresolved discussions (waiting on @kungfucraig and @SanjayVas)

___
*[`experimental/dp_consistency/src/main/kotlin/org/wfanet/measurement/reporting/postprocess/ReportPostProcessing.kt` line 96 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1803#-O8iZSBh-Jq75ySq6xJd:-O8kAmxa7Ebz6pLmE1UH:boyexbg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0315e9481aedfcc395aa6fe082975595aa79f855/experimental/dp_consistency/src/main/kotlin/org/wfanet/measurement/reporting/postprocess/ReportPostProcessing.kt#L96)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Use a try-with-resources construct to guarantee `close` gets called. In Kotlin, this is the `use` function.
</blockquote></details>

Done. Thanks.
___
*[`experimental/dp_consistency/src/main/kotlin/reporting/ReportConverter.kt` line 27 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1803#-O8MxReKBWWPxuKsoWwS:-O8kFgn3EMmJP3DvoOQg:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a7f6dff3c34c73196021c3b81b0dac21decd9521/experimental/dp_consistency/src/main/kotlin/reporting/ReportConverter.kt#L27)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

A bit of documentation for the data classes would be helpful.
</blockquote></details>

Done.
___
*[`experimental/dp_consistency/src/main/kotlin/reporting/ReportPostProcessing.kt` line 46 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1803#-O8NsQVV9yq688L_veJi:-O8kFeDvCNxJzMPCQ-Nu:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2f3aca63d5316db43ac15bb4b37144e7a6a85d7a/experimental/dp_consistency/src/main/kotlin/reporting/ReportPostProcessing.kt#L46)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This is still not correct. processReportSummary must take in a param of type `ReportSummary`, not `String`.

> I'm happy either way, but the text proto has a major benefit of being readable and it's not big, so...

There's no opportunity for a human to read it.
</blockquote></details>

Done.
___
*[`experimental/dp_consistency/src/main/proto/wfa/measurement/internal/reporting/report_summary.proto` line 1 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1803#-O8iZwu7B_VmSe7Pe6ni:-O8kFaYe8e7_87fm0k8K:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0315e9481aedfcc395aa6fe082975595aa79f855/experimental/dp_consistency/src/main/proto/wfa/measurement/internal/reporting/report_summary.proto#L1)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

`internal/reporting` is for the internal Reporting API. You probably want this to be under `wfa/measurement/reporting/postprocess`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-10-09 20:28 UTC, SanjayVas requested changes
> Reviewed 2 of 13 files at r6, 3 of 30 files at r9, 7 of 12 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1803)* status: 29 of 34 files reviewed, 3 unresolved discussions (waiting on @kungfucraig and @ple13)

___
*[`experimental/dp_consistency/src/main/kotlin/org/wfanet/measurement/reporting/postprocess/ReportPostProcessing.kt` line 95 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1803#-O8mvock06Jn3j3gJQ4S:-O8mvock06Jn3j3gJQ4T:bwtirs3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/688d85fe0d3b8f066a1f7d454e6f16e9d08e578c/experimental/dp_consistency/src/main/kotlin/org/wfanet/measurement/reporting/postprocess/ReportPostProcessing.kt#L95)):*
> ```Kotlin
>       writer.write(Base64.getEncoder().encodeToString(reportSummary.toByteArray()))
>       writer.flush()
>     }
> ```

Don't base64 encode. Just write the bytes.



_Suggestion:_
```Kotlin
    reportSummary.writeTo(process.outputStream)
```
___
*[`experimental/dp_consistency/src/test/kotlin/org/wfanet/measurement/reporting/postprocess/ReportPostProcessingTest.kt` line 32 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1803#-O8mxO6X8KhSNhc7a53I:-O8mxO6X8KhSNhc7a53J:ba9aa6k) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/688d85fe0d3b8f066a1f7d454e6f16e9d08e578c/experimental/dp_consistency/src/test/kotlin/org/wfanet/measurement/reporting/postprocess/ReportPostProcessingTest.kt#L32)):*
> ```Kotlin
>     val reportAsJson =
>       Files.readString(
>         File(
> ```

This file is not guaranteed to be in this location. You need to use Runfiles to read it. Ignore the deprecation warning, as it's blocked on a bug outside of our control in rules_kotlin.
___
*[`experimental/dp_consistency/src/test/python/wfa/measurement/reporting/postprocess/tools/example_origin_report.xlsx` line 0 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1803#-O8mxnVL5XksJovqj03t:-O8mxnVM44mm5sgrlRAS:b-80k576) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/688d85fe0d3b8f066a1f7d454e6f16e9d08e578c/experimental/dp_consistency/src/test/python/wfa/measurement/reporting/postprocess/tools/example_origin_report.xlsx#L0)):*
Delete this file


<!-- Sent from Reviewable.io -->

2024-10-10 17:14 UTC, ple13 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1803)* status: 26 of 34 files reviewed, 3 unresolved discussions (waiting on @kungfucraig and @SanjayVas)

___
*[`experimental/dp_consistency/src/main/kotlin/org/wfanet/measurement/reporting/postprocess/ReportPostProcessing.kt` line 95 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1803#-O8mvock06Jn3j3gJQ4S:-O8n9uuXA2Bxf2khCUJG:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/688d85fe0d3b8f066a1f7d454e6f16e9d08e578c/experimental/dp_consistency/src/main/kotlin/org/wfanet/measurement/reporting/postprocess/ReportPostProcessing.kt#L95)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Don't base64 encode. Just write the bytes.
</blockquote></details>

Done.
___
*[`experimental/dp_consistency/src/test/kotlin/org/wfanet/measurement/reporting/postprocess/ReportPostProcessingTest.kt` line 32 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1803#-O8mxO6X8KhSNhc7a53I:-O8r1byo9-FpcTwM3l5m:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/688d85fe0d3b8f066a1f7d454e6f16e9d08e578c/experimental/dp_consistency/src/test/kotlin/org/wfanet/measurement/reporting/postprocess/ReportPostProcessingTest.kt#L32)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This file is not guaranteed to be in this location. You need to use Runfiles to read it. Ignore the deprecation warning, as it's blocked on a bug outside of our control in rules_kotlin.
</blockquote></details>

Done.
___
*[`experimental/dp_consistency/src/test/python/wfa/measurement/reporting/postprocess/tools/example_origin_report.xlsx` line  at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1803#-O8mxnVL5XksJovqj03t:-O8rOPGs29-ASgPI3hoj:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/688d85fe0d3b8f066a1f7d454e6f16e9d08e578c/experimental/dp_consistency/src/test/python/wfa/measurement/reporting/postprocess/tools/example_origin_report.xlsx#L)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Delete this file
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-10-10 18:52 UTC, SanjayVas requested changes
> Reviewed 2 of 12 files at r10, 4 of 6 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1803)* status: 32 of 34 files reviewed, 5 unresolved discussions (waiting on @kungfucraig and @ple13)

___
*[`experimental/dp_consistency/src/main/kotlin/org/wfanet/measurement/reporting/postprocess/ReportConversion.kt` line 45 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1803#-O8riNds23zpaiw1cYUg:-O8riNds23zpaiw1cYUh:bb76mu4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/363ffdab631e38a3ffa144013e5fcc6da7f09537/experimental/dp_consistency/src/main/kotlin/org/wfanet/measurement/reporting/postprocess/ReportConversion.kt#L45)):*
> ```Kotlin
>       try {
>         val protoBuilder = Report.newBuilder()
>         JsonFormat.parser().ignoringUnknownFields().merge(reportAsJsonString, protoBuilder)
> ```

Why?



_Code quote:_
```Kotlin
ignoringUnknownFields()
```
___
*[`experimental/dp_consistency/src/main/kotlin/org/wfanet/measurement/reporting/postprocess/ReportConversion.kt` line 47 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1803#-O8ri9smAauiCa0T9Uhb:-O8ri9smAauiCa0T9Uhc:b-d3cx9l) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/363ffdab631e38a3ffa144013e5fcc6da7f09537/experimental/dp_consistency/src/main/kotlin/org/wfanet/measurement/reporting/postprocess/ReportConversion.kt#L47)):*
> ```Kotlin
>         JsonFormat.parser().ignoringUnknownFields().merge(reportAsJsonString, protoBuilder)
>         protoBuilder.build()
>       } catch (e: InvalidProtocolBufferException) {
> ```

Bubble up the exception rather than hiding it. Passing an invalid message should indeed be an error.
___
*[`experimental/dp_consistency/src/main/kotlin/org/wfanet/measurement/reporting/postprocess/ReportConversion.kt` line 95 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1803#-O8rig-SAO1xLkRcYI0S:-O8rig-TBwNWQun3-Qyh:bllvzap) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/363ffdab631e38a3ffa144013e5fcc6da7f09537/experimental/dp_consistency/src/main/kotlin/org/wfanet/measurement/reporting/postprocess/ReportConversion.kt#L95)):*
> ```Kotlin
> 
> fun Report.toReportSummaries(): List<ReportSummary> {
>   require(this.state == Report.State.SUCCEEDED) { "Unsucceeded report is not supported." }
> ```

nit: redundant qualifier, here and elsewhere.

We only use the qualifier when necessary



_Code quote:_
```Kotlin
this.
```
___
*[`experimental/dp_consistency/src/test/kotlin/org/wfanet/measurement/reporting/postprocess/ReportConversionTest.kt` line 91 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1803#-O8rkk-vET4Yl3AYyEUV:-O8rkk-vET4Yl3AYyEUW:b-rkp63w) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/363ffdab631e38a3ffa144013e5fcc6da7f09537/experimental/dp_consistency/src/test/kotlin/org/wfanet/measurement/reporting/postprocess/ReportConversionTest.kt#L91)):*
> ```Kotlin
> 
>   companion object {
>     private val REPORT_WITH_UNSPECIFIED_STATE =
> ```

Extract these to separate data files.
___
*[`experimental/dp_consistency/src/test/kotlin/org/wfanet/measurement/reporting/postprocess/ReportPostProcessingTest.kt` line 32 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1803#-O8mxO6X8KhSNhc7a53I:-O8rkrMS0sbYllPXO4Cf:bvuh764) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/688d85fe0d3b8f066a1f7d454e6f16e9d08e578c/experimental/dp_consistency/src/test/kotlin/org/wfanet/measurement/reporting/postprocess/ReportPostProcessingTest.kt#L32)):*
<details><summary><i>Previously, ple13 (Phi) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

This is still not correct. By "use Runfiles" I meant the functions defined in Runfiles.kt in common-jvm. Specifically, `org.wfanet.measurement.common.getRuntimePath`. The function is marked as deprecated, but we can't actually fix it until another issue is resolved (see #1530) which is why I said to ignore the deprecation warning.


<!-- Sent from Reviewable.io -->

2024-10-10 20:04 UTC, ple13 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1803)* status: 27 of 37 files reviewed, 4 unresolved discussions (waiting on @kungfucraig and @SanjayVas)

___
*[`experimental/dp_consistency/src/main/kotlin/org/wfanet/measurement/reporting/postprocess/ReportConversion.kt` line 45 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1803#-O8riNds23zpaiw1cYUg:-O8rmarW8A6_NsC5DN1P:bss4a2b) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/363ffdab631e38a3ffa144013e5fcc6da7f09537/experimental/dp_consistency/src/main/kotlin/org/wfanet/measurement/reporting/postprocess/ReportConversion.kt#L45)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Why?
</blockquote></details>

Removed.
___
*[`experimental/dp_consistency/src/main/kotlin/org/wfanet/measurement/reporting/postprocess/ReportConversion.kt` line 47 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1803#-O8ri9smAauiCa0T9Uhb:-O8rntnJ9fejQo0DYi8o:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/363ffdab631e38a3ffa144013e5fcc6da7f09537/experimental/dp_consistency/src/main/kotlin/org/wfanet/measurement/reporting/postprocess/ReportConversion.kt#L47)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Bubble up the exception rather than hiding it. Passing an invalid message should indeed be an error.
</blockquote></details>

Done.
___
*[`experimental/dp_consistency/src/main/kotlin/org/wfanet/measurement/reporting/postprocess/ReportConversion.kt` line 95 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1803#-O8rig-SAO1xLkRcYI0S:-O8roCdnErPFBZE2Hwh4:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/363ffdab631e38a3ffa144013e5fcc6da7f09537/experimental/dp_consistency/src/main/kotlin/org/wfanet/measurement/reporting/postprocess/ReportConversion.kt#L95)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: redundant qualifier, here and elsewhere.

We only use the qualifier when necessary
</blockquote></details>

Done.
___
*[`experimental/dp_consistency/src/test/kotlin/org/wfanet/measurement/reporting/postprocess/ReportConversionTest.kt` line 91 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1803#-O8rkk-vET4Yl3AYyEUV:-O8rvMVp6L26VarVe2rr:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/363ffdab631e38a3ffa144013e5fcc6da7f09537/experimental/dp_consistency/src/test/kotlin/org/wfanet/measurement/reporting/postprocess/ReportConversionTest.kt#L91)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Extract these to separate data files.
</blockquote></details>

Done.
___
*[`experimental/dp_consistency/src/test/kotlin/org/wfanet/measurement/reporting/postprocess/ReportPostProcessingTest.kt` line 32 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1803#-O8mxO6X8KhSNhc7a53I:-O8rvNpc4Qa0j8EZQ7Cn:boyexbg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/688d85fe0d3b8f066a1f7d454e6f16e9d08e578c/experimental/dp_consistency/src/test/kotlin/org/wfanet/measurement/reporting/postprocess/ReportPostProcessingTest.kt#L32)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This is still not correct. By "use Runfiles" I meant the functions defined in Runfiles.kt in common-jvm. Specifically, `org.wfanet.measurement.common.getRuntimePath`. The function is marked as deprecated, but we can't actually fix it until another issue is resolved (see #1530) which is why I said to ignore the deprecation warning.
</blockquote></details>

Done. Thanks.


<!-- Sent from Reviewable.io -->

2024-10-10 20:28 UTC, SanjayVas requested changes
> Reviewed 1 of 30 files at r9, 8 of 8 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1803)* status: 35 of 37 files reviewed, 3 unresolved discussions (waiting on @kungfucraig and @ple13)

___
*[`experimental/dp_consistency/src/test/kotlin/org/wfanet/measurement/reporting/postprocess/BUILD.bazel` line 29 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1803#-O8s5-m4AF2XwYaFg7kv:-O8s5-m50HSCOXOmkuy1:b-det715) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/babc055128c3ba6da8a9ec47c60da05006f76166/experimental/dp_consistency/src/test/kotlin/org/wfanet/measurement/reporting/postprocess/BUILD.bazel#L29)):*
> ```Starlark
>     srcs = ["ReportConversionTest.kt"],
>     data = [
>         "//experimental/dp_consistency/src/test/kotlin/org/wfanet/measurement/reporting/postprocess:report_with_failed_measurement.json",
> ```

Isn't this file in the same package? You can just reference the file names directly, or even create a filegroup for convenience.

```BUILD
filegroup(
    name = "sample_reports",
    srcs = glob(["*.json"]),
)
```

then you can just reference `:sample_reports`.



_Code quote:_
```Starlark
//experimental/dp_consistency/src/test/kotlin/org/wfanet/measurement/reporting/postprocess:report_with_failed_measurement.json
```
___
*[`experimental/dp_consistency/src/test/kotlin/org/wfanet/measurement/reporting/postprocess/ReportConversionTest.kt` line 36 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1803#-O8s5vq0Bm_JTf_JYd63:-O8s5vq0Bm_JTf_JYd64:b-bth19r) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/babc055128c3ba6da8a9ec47c60da05006f76166/experimental/dp_consistency/src/test/kotlin/org/wfanet/measurement/reporting/postprocess/ReportConversionTest.kt#L36)):*
> ```Kotlin
>   fun `report as json string is successfully converted to report summary proto`() {
>     val reportFile = TEST_DATA_RUNTIME_DIR.resolve("sample_report_small.json").toFile()
>     val reportAsJson = Files.readString(reportFile.toPath())
> ```

Use the `File.readText` extension.



_Suggestion:_
```Kotlin
    val reportFile = TEST_DATA_RUNTIME_DIR.resolve("sample_report_small.json").toFile()
    val reportAsJson = reportFile.readText()
```


<!-- Sent from Reviewable.io -->

2024-10-10 20:40 UTC, ple13 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1803)* status: 32 of 37 files reviewed, 3 unresolved discussions (waiting on @kungfucraig and @SanjayVas)

___
*[`experimental/dp_consistency/src/test/kotlin/org/wfanet/measurement/reporting/postprocess/BUILD.bazel` line 29 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1803#-O8s5-m4AF2XwYaFg7kv:-O8s7bBD9ewW9op150Ht:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/babc055128c3ba6da8a9ec47c60da05006f76166/experimental/dp_consistency/src/test/kotlin/org/wfanet/measurement/reporting/postprocess/BUILD.bazel#L29)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Isn't this file in the same package? You can just reference the file names directly, or even create a filegroup for convenience.

```BUILD
filegroup(
    name = "sample_reports",
    srcs = glob(["*.json"]),
)
```

then you can just reference `:sample_reports`.
</blockquote></details>

Done.
___
*[`experimental/dp_consistency/src/test/kotlin/org/wfanet/measurement/reporting/postprocess/ReportConversionTest.kt` line 36 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1803#-O8s5vq0Bm_JTf_JYd63:-O8s8e-R8gHEOkSHCUt3:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/babc055128c3ba6da8a9ec47c60da05006f76166/experimental/dp_consistency/src/test/kotlin/org/wfanet/measurement/reporting/postprocess/ReportConversionTest.kt#L36)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Use the `File.readText` extension.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-10-10 21:00 UTC, SanjayVas approved these changes
Approved for BUILD and Kotlin code. Assuming someone else is looking at the Python.

> Reviewed 2 of 13 files at r6, 3 of 3 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1803#-:-O8sDrCT9mAvC3deZS0V:bs5jzbz)* status: 35 of 37 files reviewed, all discussions resolved (waiting on @kungfucraig)



<!-- Sent from Reviewable.io -->

2024-10-11 14:24 UTC, kungfucraig approved these changes
I looked at the Python, and the the touch points between Kotlin and it.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1803#-:-O8vxeap8ZuZ9yuK3tpE:by3nxe)* status: 35 of 37 files reviewed, all discussions resolved (waiting on @ple13)



<!-- Sent from Reviewable.io -->

2024-10-11 14:28 UTC, ple13 reviewed
Thanks.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1803#-:-O8vylrY28VyFryWIGdJ:b-ucfkn4)* status: 35 of 37 files reviewed, all discussions resolved (waiting on @kungfucraig)



<!-- Sent from Reviewable.io -->

2024-10-11 14:31 UTC, ple13 reviewed
> Reviewed 1 of 18 files at r5, 2 of 13 files at r6, 1 of 9 files at r8, 16 of 30 files at r9, 4 of 12 files at r10, 5 of 6 files at r11, 5 of 8 files at r12, 3 of 3 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1803)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @ple13)



<!-- Sent from Reviewable.io -->

2024-10-11 14:31 UTC, merged