Create and implement the resource setup job.
world-federation-of-advertisers/cross-media-measurement pull request #181
Opened 2021-08-05 23:30 UTC by wangyaopw

2021-08-06 13:44 UTC, stevenwarejones requested changes
> Reviewed 12 of 23 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/181)* status: 12 of 23 files reviewed, 3 unresolved discussions (waiting on @corbantek, @oliver-amzn, @SanjayVas, @wangyaopw, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/server/ComputationsServer.kt, line 37 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/181#-MgQeU6vAI9dN6LBfrkb:-MgQeU6vAI9dN6LBfrkc:b-jlshgg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7158451002b816599611a9ecbccb8ea015cae422/src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/server/ComputationsServer.kt#L37)):*
> ```Kotlin
> import org.wfanet.measurement.internal.duchy.ComputationStageDetails
> import org.wfanet.measurement.internal.duchy.ComputationTypeEnum.ComputationType
> import org.wfanet.measurement.kingdom.deploy.common.SystemApiFlags
> ```

why is the duchy pulling in kingdom flags?
___
*[src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetupImpl.kt, line 65 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/181#-MgQhAnqDiYmHysENQvK:-MgQhAnqDiYmHysENQvL:b-p7sepu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7158451002b816599611a9ecbccb8ea015cae422/src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetupImpl.kt#L65)):*
> ```Kotlin
>       EncryptionPublicKey.newBuilder()
>         .apply {
>           type = EC_P256
> ```

shouldn't this get read in instead of being hard-coded?
___
*[src/test/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetupImplTest.kt, line 47 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/181#-MgQgfB752LSCgs1bokS:-MgQgfB752LSCgs1bokT:bcd33ma) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7158451002b816599611a9ecbccb8ea015cae422/src/test/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetupImplTest.kt#L47)):*
> ```Kotlin
> import org.wfanet.measurement.common.toByteString
> import org.wfanet.measurement.consent.crypto.keystore.testing.InMemoryKeyStore
> import org.wfanet.measurement.consent.crypto.verifySignature
> ```

@sanjayvas - I wasn't thinking we were wanting to expose this function outside of consent-signaling


<!-- Sent from Reviewable.io -->

2021-08-06 16:18 UTC, wangyaopw reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/181)* status: 12 of 23 files reviewed, 3 unresolved discussions (waiting on @corbantek, @oliver-amzn, @SanjayVas, @stevenwarejones, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/server/ComputationsServer.kt, line 37 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/181#-MgQeU6vAI9dN6LBfrkb:-MgRCuUw9MvmRAvCMpj6:byx5l5g) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7158451002b816599611a9ecbccb8ea015cae422/src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/server/ComputationsServer.kt#L37)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

why is the duchy pulling in kingdom flags?
</blockquote></details>

These are the flags for kingdom service targets. Duchies need to call kingdom system APIs
___
*[src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetupImpl.kt, line 65 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/181#-MgQhAnqDiYmHysENQvK:-MgRF9zXArdsZjYdw-sa:bv1svc2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7158451002b816599611a9ecbccb8ea015cae422/src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetupImpl.kt#L65)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

shouldn't this get read in instead of being hard-coded?
</blockquote></details>

good point. Add a TODO for this. I'll add the converting helper method to the common-jvm repo.
___
*[src/test/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetupImplTest.kt, line 47 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/181#-MgQgfB752LSCgs1bokS:-MgRFQj87X0FIP6tQkbv:bjqo77s) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7158451002b816599611a9ecbccb8ea015cae422/src/test/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetupImplTest.kt#L47)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

@sanjayvas - I wasn't thinking we were wanting to expose this function outside of consent-signaling
</blockquote></details>

good point too, I'll use the mc client to do this when the code is in.


<!-- Sent from Reviewable.io -->

2021-08-06 16:41 UTC, corbantek requested changes
> Reviewed 18 of 23 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/181)* status: 19 of 23 files reviewed, 5 unresolved discussions (waiting on @oliver-amzn, @SanjayVas, @stevenwarejones, @wangyaopw, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetupImpl.kt, line 80 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/181#-MgRJRb97DSAB_R9GcVv:-MgRJRb97DSAB_R9GcVw:b-2e5ouu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b77e8e188c06330963be144fea774c97c431dc11/src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetupImpl.kt#L80)):*
> ```Kotlin
>                 encryptionPublicKey,
>                 privateKeyHandle,
>                 dataProviderContent.consentSignalCertificateDer
> ```

This topic came up in my review https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/12 about whether we should pass in the bytes here or javax.security.cert.X509Certificate (by using the org.wfanet.measurement.common.crypto.readCertificate() function)

Would like your input in my review and I can update we decide to change
___
*[src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetupImpl.kt, line 109 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/181#-MgRKZtACB-4dBHbnRea:-MgRKZtACB-4dBHbnReb:bbxgkzp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b77e8e188c06330963be144fea774c97c431dc11/src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetupImpl.kt#L109)):*
> ```Kotlin
>                 encryptionPublicKey,
>                 privateKeyHandle,
>                 measurementConsumerContent.consentSignalCertificateDer
> ```

Same comment as above
___
*[src/test/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetupImplTest.kt, line 47 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/181#-MgQgfB752LSCgs1bokS:-MgRKok905N6v1-Ry650:b-n35ixl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7158451002b816599611a9ecbccb8ea015cae422/src/test/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetupImplTest.kt#L47)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

good point too, I'll use the mc client to do this when the code is in.
</blockquote></details>

This is available for review in https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/12


<!-- Sent from Reviewable.io -->

2021-08-06 17:08 UTC, stevenwarejones requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/181)* status: 19 of 23 files reviewed, 4 unresolved discussions (waiting on @oliver-amzn, @SanjayVas, @stevenwarejones, @wangyaopw, and @zachcwc)

___
*[src/test/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetupImplTest.kt, line 47 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/181#-MgQgfB752LSCgs1bokS:-MgRR1Kj2fGq3rpuhtUS:b1a26fm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7158451002b816599611a9ecbccb8ea015cae422/src/test/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetupImplTest.kt#L47)):*
<details><summary><i>Previously, corbantek (Kyle Johnson) wrote…</i></summary><blockquote>

This is available for review in https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/12
</blockquote></details>

can you add a TODO if this is going to land before Kyle's?


<!-- Sent from Reviewable.io -->

2021-08-06 19:04 UTC, SanjayVas requested changes
> Reviewed 9 of 23 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/181)* status: 19 of 23 files reviewed, 7 unresolved discussions (waiting on @oliver-amzn, @SanjayVas, @stevenwarejones, @wangyaopw, and @zachcwc)

___
*[WORKSPACE, line 75 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/181#-MgRobR-5jMhqu0UBhh7:-MgRobR01-E_52_L8sv3:b-6f2beo) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b77e8e188c06330963be144fea774c97c431dc11/WORKSPACE#L75)):*
> ```Starlark
> wfa_repo_archive(
>     name = "wfa_consent_signaling_client",
>     commit = "57d8ddc5ff442f0a6adda3405c0fe0393788aef1",
> ```

nit: create a new v0.1.0 release for this and use `version` instead of `commit`
___
*[WORKSPACE, line 98 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/181#-MgRp0qTEqA6nN7ShXXM:-MgRp0qTEqA6nN7ShXXN:b-wutugw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b77e8e188c06330963be144fea774c97c431dc11/WORKSPACE#L98)):*
> ```Starlark
>     repo = "common-jvm",
>     sha256 = "b3b5f3c0090dd7cc731ab0173e1bc0b14ff2f0a74b7dbf178c3f1c0473a55c29",
>     version = "0.5.0",
> ```

Can we do this upgrade in a separate PR first, since the WORKSPACE target setup is different starting in v0.4.0?
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/ServiceFlags.kt, line 19 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/181#-MgRpo3P3L6zfTpJUMYh:-MgRpo3P3L6zfTpJUMYi:b-1ckgco) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b77e8e188c06330963be144fea774c97c431dc11/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/ServiceFlags.kt#L19)):*
> ```Kotlin
> import picocli.CommandLine
> 
> class SystemApiFlags {
> ```

This is not the right place to define these, since `duchy` package shouldn't depend on `kingdom` package.

Since the Duchy is the only thing that calls the System API, the flags for that can be defined there. In this repo, the only thing that calls the public API is the correctness test, so that would be the appropriate place to define those.


<!-- Sent from Reviewable.io -->

2021-08-06 22:10 UTC, wangyaopw reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/181)* status: 0 of 27 files reviewed, 6 unresolved discussions (waiting on @corbantek, @oliver-amzn, @SanjayVas, @stevenwarejones, @wangyaopw, and @zachcwc)

___
*[WORKSPACE, line 75 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/181#-MgRobR-5jMhqu0UBhh7:-MgSUuKF9DYRx0kSzI70:bb6un1j) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b77e8e188c06330963be144fea774c97c431dc11/WORKSPACE#L75)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: create a new v0.1.0 release for this and use `version` instead of `commit`
</blockquote></details>

Done
___
*[WORKSPACE, line 98 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/181#-MgRp0qTEqA6nN7ShXXM:-MgSVpOI9XyBdePb5K5t:b-ig95qs) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b77e8e188c06330963be144fea774c97c431dc11/WORKSPACE#L98)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Can we do this upgrade in a separate PR first, since the WORKSPACE target setup is different starting in v0.4.0?
</blockquote></details>

pulled in enfreck's pr https://github.com/world-federation-of-advertisers/cross-media-measurement/pull/184.
Once her PR is in, the diff would be much cleaner.
___
*[src/test/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetupImplTest.kt, line 47 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/181#-MgQgfB752LSCgs1bokS:-MgSW3fz26xpiyCGYA4Q:by48mrr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7158451002b816599611a9ecbccb8ea015cae422/src/test/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetupImplTest.kt#L47)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

can you add a TODO if this is going to land before Kyle's?
</blockquote></details>

Added a TODO where this method is called.


<!-- Sent from Reviewable.io -->

2021-08-06 22:11 UTC, wangyaopw reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/181)* status: 0 of 27 files reviewed, 6 unresolved discussions (waiting on @corbantek, @oliver-amzn, @SanjayVas, @stevenwarejones, @wangyaopw, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/ServiceFlags.kt, line 19 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/181#-MgRpo3P3L6zfTpJUMYh:-MgSWFBG7zmGj8A0m3Cn:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b77e8e188c06330963be144fea774c97c431dc11/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/common/ServiceFlags.kt#L19)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This is not the right place to define these, since `duchy` package shouldn't depend on `kingdom` package.

Since the Duchy is the only thing that calls the System API, the flags for that can be defined there. In this repo, the only thing that calls the public API is the correctness test, so that would be the appropriate place to define those.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-08-07 00:19 UTC, SanjayVas requested changes
> Reviewed 26 of 26 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/181)* status: all files reviewed, 10 unresolved discussions (waiting on @oliver-amzn, @SanjayVas, @stevenwarejones, @wangyaopw, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/loadtest/ServiceFlags.kt, line 19 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/181#-MgSxBme-TnFmw30zKB6:-MgSpAJT45HYv4C0L43Q:bqvfft9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2cd0017d23f8bcfa10861c446370301b08d9ef29/src/main/kotlin/org/wfanet/measurement/loadtest/ServiceFlags.kt#L19)):*
> ```Kotlin
> import picocli.CommandLine
> 
> class KingdomV2alphaPublicApiFlags {
> ```

minor: I don't *think* we'd do a correctness test with multiple public API versions, so this probably isn't necessary. Could rename later if it comes up.
___
*[src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetupFlag.kt, line 22 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/181#-MgSqrP79Pd8uj9T-6z4:-MgSqrP83PGpfoVlxUf7:bqxko9r) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2cd0017d23f8bcfa10861c446370301b08d9ef29/src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetupFlag.kt#L22)):*
> ```Kotlin
> import picocli.CommandLine
> 
> class ResourceSetupFlag {
> ```

nit: `Flags`
___
*[src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetupFlag.kt, line 88 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/181#-MgSs5mU-If-wX44QGzj:-MgSrkiw6UaxhuAjUiot:b-6msqrk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2cd0017d23f8bcfa10861c446370301b08d9ef29/src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetupFlag.kt#L88)):*
> ```Kotlin
>     required = false
>   )
>   lateinit var runId: String
> ```

Could this be uninitialized if not specified? If it can't, then I assume it ends up defaulting to empty string?

Perhaps
```
var runId: String = <initialize from timestamp>
  private set
```
to avoid that potential issue.
___
*[src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetupImpl.kt, line 44 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/181#-MgSwNk44KzPVMOSK56Q:-MgSwNk44KzPVMOSK56R:b40hvzj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2cd0017d23f8bcfa10861c446370301b08d9ef29/src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetupImpl.kt#L44)):*
> ```Kotlin
>     logger.info("Starting with RunID: $runId ...")
> 
>     // Step 1: Create the EDPs via the internal API.
> ```

This says internal API, but looks like it's calling the public API.
___
*[src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetupImpl.kt, line 62 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/181#-MgSvjb04VHBwyQX0a34:-MgSvjb04VHBwyQX0a35:b-px1oo4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2cd0017d23f8bcfa10861c446370301b08d9ef29/src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetupImpl.kt#L62)):*
> ```Kotlin
> 
>   override suspend fun createDataProvider(dataProviderContent: EntityContent): DataProvider {
>     // TODO: use common-jvm helper method to do the conversion.
> ```

Which conversion? I assume not between any service protos, since common-jvm shouldn't depend on any of them.
___
*[src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetupRunner.kt, line 32 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/181#-MgSwYtT7O_zBL0qhIyw:-MgSwYtT7O_zBL0qhIyx:b-cky6lp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2cd0017d23f8bcfa10861c446370301b08d9ef29/src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetupRunner.kt#L32)):*
> ```Kotlin
> 
> @CommandLine.Command(
>   name = "run_resource_setup_job",
> ```

nit: JVM command/binary names are usually UpperCamelCase.


<!-- Sent from Reviewable.io -->

2021-08-07 01:15 UTC, wangyaopw reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/181)* status: 22 of 27 files reviewed, 8 unresolved discussions (waiting on @oliver-amzn, @SanjayVas, @stevenwarejones, @wangyaopw, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/loadtest/ServiceFlags.kt, line 19 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/181#-MgSxBme-TnFmw30zKB6:-MgT7uqv7C-SV4fFujI0:bzbargp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2cd0017d23f8bcfa10861c446370301b08d9ef29/src/main/kotlin/org/wfanet/measurement/loadtest/ServiceFlags.kt#L19)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

minor: I don't *think* we'd do a correctness test with multiple public API versions, so this probably isn't necessary. Could rename later if it comes up.
</blockquote></details>

Deleted v2lpha.
___
*[src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetupImpl.kt, line 44 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/181#-MgSwNk44KzPVMOSK56Q:-MgT91bF7VWAdh3V2DkU:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2cd0017d23f8bcfa10861c446370301b08d9ef29/src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetupImpl.kt#L44)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This says internal API, but looks like it's calling the public API.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetupImpl.kt, line 62 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/181#-MgSvjb04VHBwyQX0a34:-MgT94f2BCs-gKMUlB74:b-s880uf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2cd0017d23f8bcfa10861c446370301b08d9ef29/src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetupImpl.kt#L62)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Which conversion? I assume not between any service protos, since common-jvm shouldn't depend on any of them.
</blockquote></details>

parsing a DER encoded public key bytes to EncryptionPublicKey proto.

If common-jvm is not the right place, then we can put it in the consent-signaling-client repo
___
*[src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetupFlag.kt, line 22 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/181#-MgSqrP79Pd8uj9T-6z4:-MgT8EhW4jhmOyc9OaRo:bb6un1j) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2cd0017d23f8bcfa10861c446370301b08d9ef29/src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetupFlag.kt#L22)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: `Flags`
</blockquote></details>

Done
___
*[src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetupFlag.kt, line 88 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/181#-MgSs5mU-If-wX44QGzj:-MgT8fby1lMHBm9XVquq:b1enjox) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2cd0017d23f8bcfa10861c446370301b08d9ef29/src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetupFlag.kt#L88)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Could this be uninitialized if not specified? If it can't, then I assume it ends up defaulting to empty string?

Perhaps
```
var runId: String = <initialize from timestamp>
  private set
```
to avoid that potential issue.
</blockquote></details>

In the impl, it checks `flags.runId.isBlank()`, so defaulting to empty doesn't matter.


<!-- Sent from Reviewable.io -->

2021-08-07 07:00 UTC, wangyaopw reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/181)* status: 22 of 27 files reviewed, 8 unresolved discussions (waiting on @oliver-amzn, @SanjayVas, @stevenwarejones, @wangyaopw, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetupImpl.kt, line 65 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/181#-MgQhAnqDiYmHysENQvK:-MgUOStx85faf5XQJM2n:b9hspl9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7158451002b816599611a9ecbccb8ea015cae422/src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetupImpl.kt#L65)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

good point. Add a TODO for this. I'll add the converting helper method to the common-jvm repo.
</blockquote></details>

well, after another thought, I deleted the TODO. This is creating the publicKey, the creator knows exactly what type of key it is creating, so it just sets the type directly. No need to parse the DER file. 
___
*[src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetupImpl.kt, line 62 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/181#-MgSvjb04VHBwyQX0a34:-MgUP2m4DXlCxB4WHlLL:bh5lfvu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2cd0017d23f8bcfa10861c446370301b08d9ef29/src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetupImpl.kt#L62)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

parsing a DER encoded public key bytes to EncryptionPublicKey proto.

If common-jvm is not the right place, then we can put it in the consent-signaling-client repo
</blockquote></details>

This TODO comes from Steven's comment about whether we should hardcode the type here.

After another thought, I deleted the TODO. This is creating the publicKey, the creator knows exactly what type of key it is creating, so it just sets the type directly. No need to parse the DER file. 


<!-- Sent from Reviewable.io -->

2021-08-09 15:12 UTC, stevenwarejones requested changes
> Reviewed 10 of 26 files at r5, 3 of 5 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/181)* status: 25 of 27 files reviewed, 9 unresolved discussions (waiting on @oliver-amzn, @SanjayVas, @stevenwarejones, @wangyaopw, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/loadtest/BUILD.bazel, line 8 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/181#-MgfT03A5BBVQrI0HXHb:-MgfT03A5BBVQrI0HXHc:b233pt0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/915cc23e5f4e86de666fe32229cb7396cd7b86c9/src/main/kotlin/org/wfanet/measurement/loadtest/BUILD.bazel#L8)):*
> ```Starlark
> ])
> 
> kt_jvm_library(
> ```

are all of these supposed to be testonly?
___
*[src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetupImpl.kt, line 62 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/181#-MgSvjb04VHBwyQX0a34:-MgfT89244LLSkH-0RN1:bi3vx68) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2cd0017d23f8bcfa10861c446370301b08d9ef29/src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetupImpl.kt#L62)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

This TODO comes from Steven's comment about whether we should hardcode the type here.

After another thought, I deleted the TODO. This is creating the publicKey, the creator knows exactly what type of key it is creating, so it just sets the type directly. No need to parse the DER file. 
</blockquote></details>

isn't it convenient to just parse it vs needing the creator to pass it in?


<!-- Sent from Reviewable.io -->

2021-08-09 15:37 UTC, wangyaopw reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/181)* status: 25 of 27 files reviewed, 9 unresolved discussions (waiting on @oliver-amzn, @SanjayVas, @stevenwarejones, @wangyaopw, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/loadtest/BUILD.bazel, line 8 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/181#-MgfT03A5BBVQrI0HXHb:-MgfXIZNBwf8nMijvbbO:bb05pad) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/915cc23e5f4e86de666fe32229cb7396cd7b86c9/src/main/kotlin/org/wfanet/measurement/loadtest/BUILD.bazel#L8)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

are all of these supposed to be testonly?
</blockquote></details>

They have some test-only dependencies, for example, the inmemoryKeyStore, so it has to be test only.

and yes, this code is purely for the correctnessTest, so it can be testonly.
___
*[src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetupImpl.kt, line 62 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/181#-MgSvjb04VHBwyQX0a34:-MgfXkmMAL69JF4quRpc:bdn50a2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2cd0017d23f8bcfa10861c446370301b08d9ef29/src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetupImpl.kt#L62)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

isn't it convenient to just parse it vs needing the creator to pass it in?
</blockquote></details>

That is parsing the bytes to get a known information. I am not sure if it is convenient or just an extra work.

also, this is test code, everything is set, which means it is fine to hardcode it I feel.


<!-- Sent from Reviewable.io -->

2021-08-09 18:21 UTC, SanjayVas requested changes
> Reviewed 4 of 5 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/181)* status: all files reviewed, 6 unresolved discussions (waiting on @oliver-amzn, @SanjayVas, @stevenwarejones, @wangyaopw, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetupImpl.kt, line 62 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/181#-MgSvjb04VHBwyQX0a34:-MgfyaBM4GLH0AzuyNEs:bbm2aj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2cd0017d23f8bcfa10861c446370301b08d9ef29/src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetupImpl.kt#L62)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

That is parsing the bytes to get a known information. I am not sure if it is convenient or just an extra work.

also, this is test code, everything is set, which means it is fine to hardcode it I feel.
</blockquote></details>

Hard-coding key type is fine for now in this test, but I do expect that we'll want some functionality that parses the `AlgorithmIdentifier` from the `SubjectPublicKeyInfo` for the production path for validation purposes. Once we have that, we should update this code to use it. Therefore, I think a TODO is appropriate.

That functionality should indeed be defined in consent-signaling-client rather than common-jvm if the intent is to convert to an `EncryptionPublicKey`.
___
*[src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetupFlag.kt, line 88 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/181#-MgSs5mU-If-wX44QGzj:-Mgfxoaa8plGQAA6lAub:bhtutpq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2cd0017d23f8bcfa10861c446370301b08d9ef29/src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetupFlag.kt#L88)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

In the impl, it checks `flags.runId.isBlank()`, so defaulting to empty doesn't matter.
</blockquote></details>

Okay, so the behavior is defaulting to empty? I didn't know if it just left it uninitialized instead.

Regardless, I think it's clearer to do the timestamp defaulting as described here.


<!-- Sent from Reviewable.io -->

2021-08-09 18:43 UTC, wangyaopw reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/181)* status: 10 of 27 files reviewed, 6 unresolved discussions (waiting on @oliver-amzn, @SanjayVas, @stevenwarejones, @wangyaopw, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetupImpl.kt, line 62 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/181#-MgSvjb04VHBwyQX0a34:-MggDVAO7XxwBuails7D:b-3aqjc4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2cd0017d23f8bcfa10861c446370301b08d9ef29/src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetupImpl.kt#L62)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Hard-coding key type is fine for now in this test, but I do expect that we'll want some functionality that parses the `AlgorithmIdentifier` from the `SubjectPublicKeyInfo` for the production path for validation purposes. Once we have that, we should update this code to use it. Therefore, I think a TODO is appropriate.

That functionality should indeed be defined in consent-signaling-client rather than common-jvm if the intent is to convert to an `EncryptionPublicKey`.
</blockquote></details>

Added todo back
___
*[src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetupFlag.kt, line 88 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/181#-MgSs5mU-If-wX44QGzj:-MggDT4mCw_TMRLWMSDk:bb6un1j) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2cd0017d23f8bcfa10861c446370301b08d9ef29/src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetupFlag.kt#L88)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Okay, so the behavior is defaulting to empty? I didn't know if it just left it uninitialized instead.

Regardless, I think it's clearer to do the timestamp defaulting as described here.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2021-08-09 19:05 UTC, SanjayVas approved these changes
> Reviewed 1 of 17 files at r9, 16 of 16 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/181)* status: all files reviewed, 5 unresolved discussions (waiting on @oliver-amzn, @stevenwarejones, @wangyaopw, and @zachcwc)



<!-- Sent from Reviewable.io -->

2021-08-09 21:35 UTC, wangyaopw reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/181)* status: all files reviewed, 5 unresolved discussions (waiting on @corbantek, @oliver-amzn, @stevenwarejones, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetupImpl.kt, line 65 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/181#-MgQhAnqDiYmHysENQvK:-Mggpn1v9KE6s35xUYJF:b-iwda8k) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7158451002b816599611a9ecbccb8ea015cae422/src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetupImpl.kt#L65)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

well, after another thought, I deleted the TODO. This is creating the publicKey, the creator knows exactly what type of key it is creating, so it just sets the type directly. No need to parse the DER file. 
</blockquote></details>

Added back
___
*[src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetupImpl.kt, line 80 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/181#-MgRJRb97DSAB_R9GcVv:-MggpkmP8ZULkyGJ5r3S:bp3tak) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b77e8e188c06330963be144fea774c97c431dc11/src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetupImpl.kt#L80)):*
<details><summary><i>Previously, corbantek (Kyle Johnson) wrote…</i></summary><blockquote>

This topic came up in my review https://reviewable.io/reviews/world-federation-of-advertisers/consent-signaling-client/12 about whether we should pass in the bytes here or javax.security.cert.X509Certificate (by using the org.wfanet.measurement.common.crypto.readCertificate() function)

Would like your input in my review and I can update we decide to change
</blockquote></details>

I'll update the code when I update the consent-signal-client version.
___
*[src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetupImpl.kt, line 109 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/181#-MgRKZtACB-4dBHbnRea:-MggpafA9Vnx41VBpCDQ:bp3tak) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b77e8e188c06330963be144fea774c97c431dc11/src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetupImpl.kt#L109)):*
<details><summary><i>Previously, corbantek (Kyle Johnson) wrote…</i></summary><blockquote>

Same comment as above
</blockquote></details>

I'll update the code when I update the consent-signal-client version.


<!-- Sent from Reviewable.io -->

2021-08-09 22:15 UTC, corbantek approved these changes
> Reviewed 1 of 17 files at r9, 16 of 16 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/181)* status: all files reviewed, 3 unresolved discussions (waiting on @oliver-amzn, @stevenwarejones, and @zachcwc)



<!-- Sent from Reviewable.io -->

2021-08-09 23:13 UTC, wangyaopw reviewed
> Dismissed @stevenwarejones from 3 discussions.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/181)* status: 25 of 27 files reviewed, all discussions resolved (waiting on @corbantek, @oliver-amzn, @SanjayVas, and @zachcwc)



<!-- Sent from Reviewable.io -->

2021-08-09 23:14 UTC, wangyaopw reviewed
> Reviewed 10 of 26 files at r5, 15 of 16 files at r10, 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/181)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @oliver-amzn and @zachcwc)



<!-- Sent from Reviewable.io -->

2021-08-09 23:36 UTC, merged

2021-08-19 20:57 UTC, wangyaopw commented
https://rally1.rallydev.com/#/604612930531d/userstories?detail=%2Fuserstory%2F606023913651&view=2c2927c0-626b-4740-8620-af2a93b7d623