Create Population Requisition Fulfiller Daemon.
world-federation-of-advertisers/cross-media-measurement pull request #1820
Opened 2024-09-19 01:50 UTC by jojijac0b

Creates daemon for Population Requisition Fulfiller

2024-09-19 01:50 UTC, wfa-reviewable commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1820)
<!-- Reviewable:end -->

2024-09-19 17:51 UTC, SanjayVas requested changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1820)* status: all files reviewed, 5 unresolved discussions (waiting on @jojijac0b, @kungfucraig, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfillerDaemon.kt` line 143 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1820#-O7AMuP-0AF9hhhQZasO:-O7AMuP-0AF9hhhQZasP:undefined) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/50fb3a027a99a34def4a880b9f6e30de5d8fde42/src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfillerDaemon.kt#L143)):*
> ```Kotlin
>   @CommandLine.Option(
>     names = ["--event-message-descriptor-set"],
>     description = ["Serialized DescriptorSet for the event message and its dependencies."],
> ```





_Suggestion:_
```Kotlin
FileDescriptorSet
```
___
*[`src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfillerDaemon.kt` line 143 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1820#-O7AMwzPED__EAVOsc4Q:-O7AMwzPED__EAVOsc4R:b-21hko5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/50fb3a027a99a34def4a880b9f6e30de5d8fde42/src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfillerDaemon.kt#L143)):*
> ```Kotlin
>   @CommandLine.Option(
>     names = ["--event-message-descriptor-set"],
>     description = ["Serialized DescriptorSet for the event message and its dependencies."],
> ```

Document this this can be specified multiple times.
___
*[`src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfillerDaemon.kt` line 150 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1820#-O7AMh6rBZeowxyW3Rgj:-O7AMh6rBZeowxyW3Rgk:ba1ab30) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/50fb3a027a99a34def4a880b9f6e30de5d8fde42/src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfillerDaemon.kt#L150)):*
> ```Kotlin
>   @Option(
>     names = ["--pdp-data"],
>     description = ["The Population DataProvider's public API resource name."],
> ```

Description doesn't match type



_Code quote:_
```Kotlin
"The Population DataProvider's public API resource name."
```
___
*[`src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfillerDaemon.kt` line 156 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1820#-O7AN6EREkxMBstFQbhk:-O7AN6EREkxMBstFQbhl:b-o5n2ha) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/50fb3a027a99a34def4a880b9f6e30de5d8fde42/src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfillerDaemon.kt#L156)):*
> ```Kotlin
> 
>   @Option(
>     names = ["--measurement-consumer-name"],
> ```

The other flags for resource names end in `resource-name`. Have them all be consistent.
___
*[`src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfillerDaemon.kt` line 172 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1820#-O7ANpTc6DBbTvK6jaDL:-O7ANpTd6PIlFX30-w_p:b-uvbglb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/50fb3a027a99a34def4a880b9f6e30de5d8fde42/src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfillerDaemon.kt#L172)):*
> ```Kotlin
>     required = true,
>   )
>   private lateinit var populationInfoFileMap: Map<String, List<File>>
> ```

Do not do this. We never want repeated elements in a flag value, and instead want flags to be specified multiple times. This means having separate `--population-spec` flag for the specs and another for the descriptors.

Note that I'm also confused on what FileDescriptorSet this is supposed to be, since there's already a flag for the FileDescriptorSet for the event message which will therefore contain all event template descriptors.



_Code quote:_
```Kotlin
List<File>
```


<!-- Sent from Reviewable.io -->

2024-09-19 19:21 UTC, stevenwarejones requested changes
If you wanted to add a test @jojijac0b , it would be something like this
```
val args = arrayOf(<flags>)
val daemon = PopulationRequisitionFulfillerDaemon()
val cmd = picocli.CommandLine(daemon)
val exitCode = cmd.execute(*args)
assertThat(exitCode).isEqualTo(0)
<assert other things>
```
I'm not sure what you'd actually test though since you need other components in order to properly test. That's what the correctness test is for.

> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1820#-:-O7AhxaI0--5XFE3sUe0:b-a0wqbl)* status: all files reviewed, 7 unresolved discussions (waiting on @jojijac0b, @kungfucraig, and @option)

___
*[`src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfillerDaemon.kt` line 153 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1820#-O7AbZCU29H-R1YeHExc:-O7AbZCU29H-R1YeHExd:b9lhxva) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/50fb3a027a99a34def4a880b9f6e30de5d8fde42/src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfillerDaemon.kt#L153)):*
> ```Kotlin
>     required = true,
>   )
>   private lateinit var pdpDataFile: File
> ```

what is this used for?
___
*[`src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfillerDaemon.kt` line 160 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1820#-O7ActEm4USE8ec7n_W8:-O7ActEm4USE8ec7n_W9:b-z5kchk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/50fb3a027a99a34def4a880b9f6e30de5d8fde42/src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfillerDaemon.kt#L160)):*
> ```Kotlin
>     required = true,
>   )
>   private lateinit var measurementConsumerName: String
> ```

can someone remind me why the measurement consumer name is a flag that is passed in here? That doesn't make any sense to me. I must be missing something. It feels like simulator code that should not be part of the abstract RequisitionFulfiller - https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d711fd96d6ceb10d3796cdbe681095c7a99a775a/src/main/kotlin/org/wfanet/measurement/dataprovider/RequisitionFulfiller.kt#L78
___
*[`src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfillerDaemon.kt` line 172 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1820#-O7ANpTc6DBbTvK6jaDL:-O7Ae8bz9OmVT5E6K8It:b-gnbg4o) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/50fb3a027a99a34def4a880b9f6e30de5d8fde42/src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfillerDaemon.kt#L172)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Do not do this. We never want repeated elements in a flag value, and instead want flags to be specified multiple times. This means having separate `--population-spec` flag for the specs and another for the descriptors.

Note that I'm also confused on what FileDescriptorSet this is supposed to be, since there's already a flag for the FileDescriptorSet for the event message which will therefore contain all event template descriptors.
</blockquote></details>

This is for populating `Map<PopulationKey, PopulationInfo>`, right? PopulationInfo contains both `PopulationSpec` and a `Descriptor`. I would think we'd want repeating argument groups to capture this right? https://picocli.info/#_repeating_composite_argument_groups

Something like
```
    @ArgGroup(exclusive = false, multiplicity = "1..*")
    List<PopulationKeyAndInfo> populationKeyAndInfo

    static class PopulationKeyAndInfo {
        @Option(names = "--population-key", required = true)
        String populationKey

        @ArgGroup(exclusive = false, multiplicity=1)
        PopulationInfo populationInfo
    }

    static class PopulationInfo {
        @Option(names = "--population-spec", required = true)
        private lateinit var populationSpecFile File;
        @Option(names = "--event-message-descriptor", required = true)
        private lateinit var eventMessageDescriptorFile File;
    }
```



<!-- Sent from Reviewable.io -->

2024-09-19 19:22 UTC, stevenwarejones requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1820)* status: all files reviewed, 7 unresolved discussions (waiting on @jojijac0b, @kungfucraig, and @option)

___
*[`src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfillerDaemon.kt` line 160 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1820#-O7ActEm4USE8ec7n_W8:-O7Aj1HDA-qBQN4KgNwP:b-wmvsyz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/50fb3a027a99a34def4a880b9f6e30de5d8fde42/src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfillerDaemon.kt#L160)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

can someone remind me why the measurement consumer name is a flag that is passed in here? That doesn't make any sense to me. I must be missing something. It feels like simulator code that should not be part of the abstract RequisitionFulfiller - https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d711fd96d6ceb10d3796cdbe681095c7a99a775a/src/main/kotlin/org/wfanet/measurement/dataprovider/RequisitionFulfiller.kt#L78
</blockquote></details>

@SanjayVas 


<!-- Sent from Reviewable.io -->

2024-09-19 21:16 UTC, SanjayVas reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1820)* status: all files reviewed, 7 unresolved discussions (waiting on @jojijac0b, @kungfucraig, @option, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfillerDaemon.kt` line 160 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1820#-O7ActEm4USE8ec7n_W8:-O7B6zeNCTxbXeaU5GgB:bd6x2or) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/50fb3a027a99a34def4a880b9f6e30de5d8fde42/src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfillerDaemon.kt#L160)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

@SanjayVas
</blockquote></details>

The event requisition fulfiller (EDP simulator) explicitly only works for a single MC. There's indeed no need to have this be the case for the population requisition fulfiller. Furthermore, the value isn't even used by the base RequisitionFulfiller and is instead used in its subclasses.


<!-- Sent from Reviewable.io -->

2024-09-19 22:10 UTC, kungfucraig reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1820)* status: all files reviewed, 8 unresolved discussions (waiting on @jojijac0b, @option, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfillerDaemon.kt` line 241 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1820#-O7BKM9BCGXRw114tNBG:-O7BKM9BCGXRw114tNBH:be82798) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/50fb3a027a99a34def4a880b9f6e30de5d8fde42/src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfillerDaemon.kt#L241)):*
> ```Kotlin
>   }
> 
>   private fun buildTypeRegistry(): TypeRegistry {
> ```

I'd recommend putting these in another file and writing unit tests for them.


<!-- Sent from Reviewable.io -->

2024-09-23 20:32 UTC, stevenwarejones requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1820)* status: all files reviewed, 8 unresolved discussions (waiting on @jojijac0b and @option)

___
*[`src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfillerDaemon.kt` line 160 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1820#-O7ActEm4USE8ec7n_W8:-O7V_56tDk-TEcuAKtp3:b-y9079l) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/50fb3a027a99a34def4a880b9f6e30de5d8fde42/src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfillerDaemon.kt#L160)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The event requisition fulfiller (EDP simulator) explicitly only works for a single MC. There's indeed no need to have this be the case for the population requisition fulfiller. Furthermore, the value isn't even used by the base RequisitionFulfiller and is instead used in its subclasses.
</blockquote></details>

agreed. please factor this out of the abstract class (I think we all missed that when previously reviewed) and only include it in the edp simulator @jojijac0b 


<!-- Sent from Reviewable.io -->

2024-09-24 19:12 UTC, jojijac0b reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1820)* status: 1 of 6 files reviewed, 8 unresolved discussions (waiting on @kungfucraig, @option, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfillerDaemon.kt` line 143 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1820#-O7AMuP-0AF9hhhQZasO:-O7AsWK2BX1csN-Fi9i0:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/50fb3a027a99a34def4a880b9f6e30de5d8fde42/src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfillerDaemon.kt#L143)):*
> ```Kotlin
>   @CommandLine.Option(
>     names = ["--event-message-descriptor-set"],
>     description = ["Serialized DescriptorSet for the event message and its dependencies."],
> ```

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfillerDaemon.kt` line 150 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1820#-O7AMh6rBZeowxyW3Rgj:-O7AsX4bE-_WsTsey-UD:ba3dfob) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/50fb3a027a99a34def4a880b9f6e30de5d8fde42/src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfillerDaemon.kt#L150)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Description doesn't match type
</blockquote></details>

Removed
___
*[`src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfillerDaemon.kt` line 153 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1820#-O7AbZCU29H-R1YeHExc:-O7AsY7sE_LyBNDdQRBE:b-gq88sp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/50fb3a027a99a34def4a880b9f6e30de5d8fde42/src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfillerDaemon.kt#L153)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

what is this used for?
</blockquote></details>

Removed as this information is gathered from the "flags" flag
___
*[`src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfillerDaemon.kt` line 160 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1820#-O7ActEm4USE8ec7n_W8:-O7VTqrVDNXsYRp07H0Q:b-99tlw9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/50fb3a027a99a34def4a880b9f6e30de5d8fde42/src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfillerDaemon.kt#L160)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The event requisition fulfiller (EDP simulator) explicitly only works for a single MC. There's indeed no need to have this be the case for the population requisition fulfiller. Furthermore, the value isn't even used by the base RequisitionFulfiller and is instead used in its subclasses.
</blockquote></details>

Removed MeasurementConsumerName parameter from RequisitionFulfiller superclass. It is now only used in the EDPSimulator sub-class
___
*[`src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfillerDaemon.kt` line 172 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1820#-O7ANpTc6DBbTvK6jaDL:-O7VIsXLAvGkZmyrY5YV:b3nr322) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/50fb3a027a99a34def4a880b9f6e30de5d8fde42/src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfillerDaemon.kt#L172)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

This is for populating `Map<PopulationKey, PopulationInfo>`, right? PopulationInfo contains both `PopulationSpec` and a `Descriptor`. I would think we'd want repeating argument groups to capture this right? https://picocli.info/#_repeating_composite_argument_groups

Something like
```
    @ArgGroup(exclusive = false, multiplicity = "1..*")
    List<PopulationKeyAndInfo> populationKeyAndInfo

    static class PopulationKeyAndInfo {
        @Option(names = "--population-key", required = true)
        String populationKey

        @ArgGroup(exclusive = false, multiplicity=1)
        PopulationInfo populationInfo
    }

    static class PopulationInfo {
        @Option(names = "--population-spec", required = true)
        private lateinit var populationSpecFile File;
        @Option(names = "--event-message-descriptor", required = true)
        private lateinit var eventMessageDescriptorFile File;
    }
```

</blockquote></details>

Uses @ArgGroup


<!-- Sent from Reviewable.io -->

2024-09-24 19:55 UTC, SanjayVas requested changes
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1820)* status: all files reviewed, 6 unresolved discussions (waiting on @jojijac0b, @option, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfillerDaemon.kt` line 172 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1820#-O7ANpTc6DBbTvK6jaDL:-O7__O4s6MQBEcU1gu9v:b-lgqwto) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/50fb3a027a99a34def4a880b9f6e30de5d8fde42/src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfillerDaemon.kt#L172)):*
<details><summary><i>Previously, jojijac0b wrote…</i></summary><blockquote>

Uses @ArgGroup
</blockquote></details>

What I'm getting at is that this overlaps the top-level `--event-message-descriptor-set` option. I think what you actually want is having the FileDescriptorSet files passed to that option, and have a string `--event-message-type-url` for each PopulationSpec . You can use the type URL to look up the Descriptor from the loaded FileDescriptorSets.


<!-- Sent from Reviewable.io -->

2024-09-25 16:45 UTC, stevenwarejones requested changes
> Reviewed 4 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1820)* status: all files reviewed, 7 unresolved discussions (waiting on @jojijac0b and @option)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 199 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1820#-O7e2pxr-nPjvEknx9WH:-O7e2pxr-nPjvEknx9WI:bvezweo) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ca6a28b895ac0ec1a08327766c32446921176555/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L199)):*
> ```Kotlin
>   }
> 
>   val measurementConsumerKey =
> ```

this can be private right?
___
*[`src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfillerDaemon.kt` line 158 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1820#-O7e3c_PBkQnIZPhI0qv:-O7e3c_PBkQnIZPhI0qw:bon964d) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ca6a28b895ac0ec1a08327766c32446921176555/src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfillerDaemon.kt#L158)):*
> ```Kotlin
> 
>     @CommandLine.ArgGroup(exclusive = false, multiplicity = "1")
>     lateinit var populationInfo: PopulationInfo
> ```

is it supported to pass in data classes this way?


<!-- Sent from Reviewable.io -->

2024-11-21 19:29 UTC, jojijac0b reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1820)* status: 5 of 6 files reviewed, 7 unresolved discussions (waiting on @option, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfillerDaemon.kt` line 172 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1820#-O7ANpTc6DBbTvK6jaDL:-O7ea9Y47yb-4Nb259gZ:bcagfbf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/50fb3a027a99a34def4a880b9f6e30de5d8fde42/src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfillerDaemon.kt#L172)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

What I'm getting at is that this overlaps the top-level `--event-message-descriptor-set` option. I think what you actually want is having the FileDescriptorSet files passed to that option, and have a string `--event-message-type-url` for each PopulationSpec . You can use the type URL to look up the Descriptor from the loaded FileDescriptorSets.
</blockquote></details>

Done. Changed the eventMessageDescriptorFile to eventMessageTypeUrl(of type string). The buildPopulationInfoMap() method will use the type registry built using the eventMessageDescriptorSetFiles input and this eventMessageTypeUrl to get the descriptor for that PopulationInfo object.


<!-- Sent from Reviewable.io -->

2024-11-21 20:37 UTC, jojijac0b reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1820)* status: 3 of 6 files reviewed, 7 unresolved discussions (waiting on @option, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfillerDaemon.kt` line 143 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1820#-O7AMwzPED__EAVOsc4Q:-OCFRNum7algon5x8_Jh:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/50fb3a027a99a34def4a880b9f6e30de5d8fde42/src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfillerDaemon.kt#L143)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Document this this can be specified multiple times.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfillerDaemon.kt` line 156 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1820#-O7AN6EREkxMBstFQbhk:-OCFRPWU5uovAjJob0jv:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/50fb3a027a99a34def4a880b9f6e30de5d8fde42/src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfillerDaemon.kt#L156)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The other flags for resource names end in `resource-name`. Have them all be consistent.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-11-21 20:43 UTC, jojijac0b reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1820)* status: 3 of 6 files reviewed, 7 unresolved discussions (waiting on @option, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfillerDaemon.kt` line 158 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1820#-O7e3c_PBkQnIZPhI0qv:-OCFSMw1BeA1oJz0NV-M:b2nm9lu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ca6a28b895ac0ec1a08327766c32446921176555/src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfillerDaemon.kt#L158)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

is it supported to pass in data classes this way?
</blockquote></details>

This is referencing the PopulationInfo class below. I believe it is possible. I see a similar design here: https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/63d2dc5d7605ef4b79e5cfeb111d0b3ffa8567d8/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/tools/Reporting.kt#L225


<!-- Sent from Reviewable.io -->

2024-11-21 21:46 UTC, stevenwarejones reviewed
> Reviewed 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1820)* status: 5 of 6 files reviewed, 6 unresolved discussions (waiting on @kungfucraig, @option, and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfillerDaemon.kt` line 241 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1820#-O7BKM9BCGXRw114tNBG:-OCFfuy08BrvbyCX5_nj:b-cazwxf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/50fb3a027a99a34def4a880b9f6e30de5d8fde42/src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfillerDaemon.kt#L241)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

I'd recommend putting these in another file and writing unit tests for them.
</blockquote></details>

we've done this plenty of times without writing unit tests
https://github.com/search?q=repo%3Aworld-federation-of-advertisers%2Fcross-media-measurement%20buildtyperegistry&type=code


<!-- Sent from Reviewable.io -->

2024-11-22 02:12 UTC, SanjayVas requested changes
> Reviewed 1 of 1 files at r5, 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1820)* status: all files reviewed, 9 unresolved discussions (waiting on @jojijac0b, @kungfucraig, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfillerDaemon.kt` line 156 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1820#-O7AN6EREkxMBstFQbhk:-OCG_nqZ98aB0thA0Wjo:b-3dr3v4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/50fb3a027a99a34def4a880b9f6e30de5d8fde42/src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfillerDaemon.kt#L156)):*
<details><summary><i>Previously, jojijac0b wrote…</i></summary><blockquote>

Done.
</blockquote></details>

The intent was for this to be `--population-resource-name` instead of `--population-key`.
___
*[`src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfillerDaemon.kt` line 158 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1820#-O7e3c_PBkQnIZPhI0qv:-OCGcB5iA1Skl4ZYAw9j:bvdh19p) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ca6a28b895ac0ec1a08327766c32446921176555/src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfillerDaemon.kt#L158)):*
> is it supported to pass in data classes this way?

This usage is supported because it isn't a data class, but rather another type containing flags that's mixed in.
___
*[`src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfillerDaemon.kt` line 141 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1820#-OCGbW6TDzmxd202pPJU:-OCGbW6TDzmxd202pPJV:b-xwus6l) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0a45475f8af149b5bde8d2cce1165637fe5898c8/src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfillerDaemon.kt#L141)):*
> ```Kotlin
>     private set
> 
>   @Option(
> ```

Why are some flags defined here and some in the Flags class above? You don't need a separate Flags class if it's just used in one place. You move all the properties from `PopulationRequisitionFulfillerFlags` here, switching them to be private rather than being public with `private set`.
___
*[`src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfillerDaemon.kt` line 149 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1820#-OCGccfnDtE051n-Zy26:-OCGccfnDtE051n-Zy27:b3evac9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0a45475f8af149b5bde8d2cce1165637fe5898c8/src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfillerDaemon.kt#L149)):*
> ```Kotlin
> 
>   @CommandLine.ArgGroup(exclusive = false, multiplicity = "1..*")
>   lateinit var populationKeyAndInfo: List<PopulationKeyAndInfo>
> ```

`private lateinit var` and drop the `private set`
___
*[`src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfillerDaemon.kt` line 152 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1820#-OCGc2WW9P-E6WHzo6FL:-OCGc2WW9P-E6WHzo6FM:b-c3asor) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0a45475f8af149b5bde8d2cce1165637fe5898c8/src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfillerDaemon.kt#L152)):*
> ```Kotlin
>     private set
> 
>   class PopulationKeyAndInfo {
> ```

nit: I believe this class can be private and still be used by 
___
*[`src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfillerDaemon.kt` line 200 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1820#-OCGaLbADYlOWjHc_6nl:-OCGaLbADYlOWjHc_6nm:b1bewjb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0a45475f8af149b5bde8d2cce1165637fe5898c8/src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfillerDaemon.kt#L200)):*
> ```Kotlin
>       )
> 
>     val channelTarget = flags.target
> ```

nit: specify types when not obvious, i.e. when not calling a constructor or well-known factory function
___
*[`src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfillerDaemon.kt` line 203 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1820#-OCGaAiJ85-bn6occMHL:-OCGaAiJ85-bn6occMHM:bbu36k3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0a45475f8af149b5bde8d2cce1165637fe5898c8/src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfillerDaemon.kt#L203)):*
> ```Kotlin
>     val channelCertHost = flags.certHost
> 
>     val certificatesChannel = buildMutualTlsChannel(channelTarget, clientCerts, channelCertHost)
> ```

Share a single channel for all stubs pointing to the same target. See https://grpc.io/docs/guides/performance/#general


<!-- Sent from Reviewable.io -->

2024-11-25 21:49 UTC, jojijac0b reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1820)* status: 5 of 6 files reviewed, 7 unresolved discussions (waiting on @kungfucraig, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfillerDaemon.kt` line 156 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1820#-O7AN6EREkxMBstFQbhk:-OC_ErIFEQMgQ801DyDh:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/50fb3a027a99a34def4a880b9f6e30de5d8fde42/src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfillerDaemon.kt#L156)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The intent was for this to be `--population-resource-name` instead of `--population-key`.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfillerDaemon.kt` line 141 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1820#-OCGbW6TDzmxd202pPJU:-OC_DAC47LRoPtdzHsE4:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0a45475f8af149b5bde8d2cce1165637fe5898c8/src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfillerDaemon.kt#L141)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Why are some flags defined here and some in the Flags class above? You don't need a separate Flags class if it's just used in one place. You move all the properties from `PopulationRequisitionFulfillerFlags` here, switching them to be private rather than being public with `private set`.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfillerDaemon.kt` line 149 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1820#-OCGccfnDtE051n-Zy26:-OC_EPPOAmbBoYD0Yc4A:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0a45475f8af149b5bde8d2cce1165637fe5898c8/src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfillerDaemon.kt#L149)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

`private lateinit var` and drop the `private set`
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfillerDaemon.kt` line 203 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1820#-OCGaAiJ85-bn6occMHL:-OC_HDjp9SLmfFADUTnq:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0a45475f8af149b5bde8d2cce1165637fe5898c8/src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfillerDaemon.kt#L203)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Share a single channel for all stubs pointing to the same target. See https://grpc.io/docs/guides/performance/#general
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-11-26 00:19 UTC, SanjayVas requested changes
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1820)* status: all files reviewed, 6 unresolved discussions (waiting on @jojijac0b, @kungfucraig, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfillerDaemon.kt` line 49 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1820#-OC_odUW4sgE3PoEOXhM:-OC_odUXD7upubC1FKpQ:b-ououi) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a89be9d0b53e43bfe3c0aa040bd91c969924141c/src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfillerDaemon.kt#L49)):*
> ```Kotlin
> 
> class PopulationRequisitionFulfillerDaemon : Runnable {
>   @Command(
> ```

The `@Command` annotation goes on the class.
___
*[`src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfillerDaemon.kt` line 139 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1820#-OC_ouf4C6x-8d2P7Kli:-OC_ouf4C6x-8d2P7Klj:big2isv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a89be9d0b53e43bfe3c0aa040bd91c969924141c/src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfillerDaemon.kt#L139)):*
> ```Kotlin
>   private class PopulationKeyAndInfo {
>     @Option(names = ["--population-resource-name"], required = true)
>     lateinit var populationKey: String
> ```

Rename this too



_Suggestion:_
```Kotlin
populationResourceName
```


<!-- Sent from Reviewable.io -->

2024-11-26 14:48 UTC, jojijac0b reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1820)* status: 5 of 6 files reviewed, 6 unresolved discussions (waiting on @kungfucraig, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfillerDaemon.kt` line 241 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1820#-O7BKM9BCGXRw114tNBG:-OCcwQLNE3Y9GZQ96GXe:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/50fb3a027a99a34def4a880b9f6e30de5d8fde42/src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfillerDaemon.kt#L241)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

we've done this plenty of times without writing unit tests
https://github.com/search?q=repo%3Aworld-federation-of-advertisers%2Fcross-media-measurement%20buildtyperegistry&type=code
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfillerDaemon.kt` line 158 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1820#-O7e3c_PBkQnIZPhI0qv:-OCcwPZkAUyYRbr-rW_6:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ca6a28b895ac0ec1a08327766c32446921176555/src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfillerDaemon.kt#L158)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> is it supported to pass in data classes this way?

This usage is supported because it isn't a data class, but rather another type containing flags that's mixed in.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfillerDaemon.kt` line 49 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1820#-OC_odUW4sgE3PoEOXhM:-OCcwM_mBUcjpCfbTnlO:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a89be9d0b53e43bfe3c0aa040bd91c969924141c/src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfillerDaemon.kt#L49)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The `@Command` annotation goes on the class.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfillerDaemon.kt` line 139 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1820#-OC_ouf4C6x-8d2P7Kli:-OCcwOHsA49ZWlScbYp5:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a89be9d0b53e43bfe3c0aa040bd91c969924141c/src/main/kotlin/org/wfanet/measurement/populationdataprovider/PopulationRequisitionFulfillerDaemon.kt#L139)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Rename this too
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-11-26 17:02 UTC, SanjayVas approved these changes
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1820)* status: all files reviewed, 3 unresolved discussions (waiting on @kungfucraig and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2024-11-26 21:15 UTC, kungfucraig approved these changes
> Reviewed 5 of 5 files at r6, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1820)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jojijac0b)



<!-- Sent from Reviewable.io -->

2024-11-26 21:22 UTC, merged

2024-12-23 10:25 UTC, mikkokotila commented
Added `feat` prefix to the title.