ControlPlane initial proto definitions.
world-federation-of-advertisers/cross-media-measurement pull request #1843
Opened 2024-10-09 16:23 UTC by Marco-Premier

2024-10-09 16:23 UTC, wfa-reviewable commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1843)
<!-- Reviewable:end -->

2024-10-09 18:53 UTC, stevenwarejones requested changes
Needs a bazel build

> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1843#-:-O8mbpgtCX-UDdWmW4pP:b-pdqcqf)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @kungfucraig, @Marco-Premier, and @SanjayVas)

___
*[`confidential_computing/control_plane/src/main/proto/wfa/controlplane/work_item.proto` line 21 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1843#-O8mc-In5l8dSfmyfVgP:-O8mc-In5l8dSfmyfVgQ:bfd78ik) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/386f5b4d23aae919a3594e5efb7de0919f81e62e/confidential_computing/control_plane/src/main/proto/wfa/controlplane/work_item.proto#L21)):*
> ```proto
> import "google/protobuf/any.proto";
> 
> option java_package = "org.wfanet.controlplane";
> ```

wdyt about org.wfanet.securecomputation ?


<!-- Sent from Reviewable.io -->

2024-10-10 17:33 UTC, SanjayVas requested changes
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1843)* status: 1 of 2 files reviewed, 5 unresolved discussions (waiting on @kungfucraig, @Marco-Premier, and @stevenwarejones)

___
*[`confidential_computing/control_plane/src/main/proto/wfa/controlplane/work_item.proto` line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1843#-O8rQsjp1vJsARtuKi1F:-O8rQsjp1vJsARtuKi1G:b-tsz37c) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/386f5b4d23aae919a3594e5efb7de0919f81e62e/confidential_computing/control_plane/src/main/proto/wfa/controlplane/work_item.proto#L1)):*
> ```proto
> // Copyright 2024 The Cross-Media Measurement Authors
> ```

Follow existing directory structure. This is a Halo component, meaning it's a sibling to the Kingdom or Duchy. (The "top-level" part of "new top-level directory" meant under "measurement", as that's the Halo root).

Note that I think that `panelmatch` should have been under `measurement` as well. The `wfa` package is for the WFA in general, and the `measurement` subpackage of that is for Halo.

As an aside, if we were to start again we'd probably have Halo be the root package as we ended up getting the Halo name and halo-cmm.org domain later on.
___
*[`confidential_computing/control_plane/src/main/proto/wfa/controlplane/work_item.proto` line 17 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1843#-O8rST9R2fb-lJBA34wQ:-O8rST9R2fb-lJBA34wR:b-rkr7x6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/386f5b4d23aae919a3594e5efb7de0919f81e62e/confidential_computing/control_plane/src/main/proto/wfa/controlplane/work_item.proto#L17)):*
> ```proto
> syntax = "proto3";
> 
> package wfa.controlplane;
> ```

This is a public API that must follow the AIPs. Therefore it must be versioned, so there should be a v1alpha leaf package.
___
*[`confidential_computing/control_plane/src/main/proto/wfa/controlplane/work_item.proto` line 26 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1843#-O8rTz7b1HMUPMH-d7au:-O8rTz7b1HMUPMH-d7av:bw9mq36) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/386f5b4d23aae919a3594e5efb7de0919f81e62e/confidential_computing/control_plane/src/main/proto/wfa/controlplane/work_item.proto#L26)):*
> ```proto
> message WorkItem {
>     option (google.api.resource) = {
>         type: "halo.wfanet.org/WorkItem"
> ```

Use the new halo-cmm.org domain like how we do in the Reporting API. The subdomain identifies the API.

We could also add an additional subdomain for confidential-computing if we'll have more APIs underneath it, e.g. `control-plane.confidential-computing.halo-cmm.org`.



_Suggestion:_
```proto
control-plane.halo-cmm.org/WorkItem
```
___
*[`confidential_computing/control_plane/src/main/proto/wfa/controlplane/work_item.proto` line 37 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1843#-O8rTeXW6-9bFU7nySFw:-O8rTeXW6-9bFU7nySFx:b-7nk06g) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/386f5b4d23aae919a3594e5efb7de0919f81e62e/confidential_computing/control_plane/src/main/proto/wfa/controlplane/work_item.proto#L37)):*
> ```proto
>     // The queue identifier into which this `WorkItem` must be enqueued.
>     // Available queue identifiers are specified in a configuration file.
>     string queue_identifier = 2;
> ```

Queues should be their own resource type so that this can be a resource reference. It's just that it's a resource type without a Create method, as it comes purely from configuration.


<!-- Sent from Reviewable.io -->

2024-10-11 13:50 UTC, Marco-Premier reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1843)* status: 0 of 4 files reviewed, 5 unresolved discussions (waiting on @kungfucraig, @SanjayVas, and @stevenwarejones)

___
*[`confidential_computing/control_plane/src/main/proto/wfa/controlplane/work_item.proto` line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1843#-O8rQsjp1vJsARtuKi1F:-O8vM3bR2zltXraKp3Uu:b80lpdd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/386f5b4d23aae919a3594e5efb7de0919f81e62e/confidential_computing/control_plane/src/main/proto/wfa/controlplane/work_item.proto#L1)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Follow existing directory structure. This is a Halo component, meaning it's a sibling to the Kingdom or Duchy. (The "top-level" part of "new top-level directory" meant under "measurement", as that's the Halo root).

Note that I think that `panelmatch` should have been under `measurement` as well. The `wfa` package is for the WFA in general, and the `measurement` subpackage of that is for Halo.

As an aside, if we were to start again we'd probably have Halo be the root package as we ended up getting the Halo name and halo-cmm.org domain later on.
</blockquote></details>

I'm not sure I follow @SanjayVas , are you suggesting to put thi proto definitions under this package:
https://github.com/world-federation-of-advertisers/cross-media-measurement/tree/main/src/main/proto/wfa/measurement?

If that's the case I thought we agreed to have a mono-repo but with dedicated folder for all secure computation related code?

What are your thoughts @stevenwarejones ?
___
*[`confidential_computing/control_plane/src/main/proto/wfa/controlplane/work_item.proto` line 17 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1843#-O8rST9R2fb-lJBA34wQ:-O8vKfY68QYeRX58g73U:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/386f5b4d23aae919a3594e5efb7de0919f81e62e/confidential_computing/control_plane/src/main/proto/wfa/controlplane/work_item.proto#L17)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This is a public API that must follow the AIPs. Therefore it must be versioned, so there should be a v1alpha leaf package.
</blockquote></details>

Done.
___
*[`confidential_computing/control_plane/src/main/proto/wfa/controlplane/work_item.proto` line 21 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1843#-O8mc-In5l8dSfmyfVgP:-O8vL8XuCu6XDMJU9Slw:b-5tuctg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/386f5b4d23aae919a3594e5efb7de0919f81e62e/confidential_computing/control_plane/src/main/proto/wfa/controlplane/work_item.proto#L21)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

wdyt about org.wfanet.securecomputation ?
</blockquote></details>

I used `org.wfanet.securecomputation.controlplane.v1alpha` because I thought that we may have other sub-packages under `securecomputation` in future?

Let me know what you think
___
*[`confidential_computing/control_plane/src/main/proto/wfa/controlplane/work_item.proto` line 26 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1843#-O8rTz7b1HMUPMH-d7au:-O8rYvoj4c2vBeN-MykT:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/386f5b4d23aae919a3594e5efb7de0919f81e62e/confidential_computing/control_plane/src/main/proto/wfa/controlplane/work_item.proto#L26)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Use the new halo-cmm.org domain like how we do in the Reporting API. The subdomain identifies the API.

We could also add an additional subdomain for confidential-computing if we'll have more APIs underneath it, e.g. `control-plane.confidential-computing.halo-cmm.org`.
</blockquote></details>

Done.
___
*[`confidential_computing/control_plane/src/main/proto/wfa/controlplane/work_item.proto` line 37 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1843#-O8rTeXW6-9bFU7nySFw:-O8rZw1I-dpJTYh8_VR1:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/386f5b4d23aae919a3594e5efb7de0919f81e62e/confidential_computing/control_plane/src/main/proto/wfa/controlplane/work_item.proto#L37)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Queues should be their own resource type so that this can be a resource reference. It's just that it's a resource type without a Create method, as it comes purely from configuration.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-10-11 14:15 UTC, stevenwarejones reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1843)* status: 0 of 4 files reviewed, 5 unresolved discussions (waiting on @kungfucraig and @SanjayVas)

___
*[`confidential_computing/control_plane/src/main/proto/wfa/controlplane/work_item.proto` line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1843#-O8rQsjp1vJsARtuKi1F:-O8vuNdw0zLiUyURq96m:b-xgv169) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/386f5b4d23aae919a3594e5efb7de0919f81e62e/confidential_computing/control_plane/src/main/proto/wfa/controlplane/work_item.proto#L1)):*
<details><summary><i>Previously, Marco-Premier (marcopremier) wrote…</i></summary><blockquote>

I'm not sure I follow @SanjayVas , are you suggesting to put thi proto definitions under this package:
https://github.com/world-federation-of-advertisers/cross-media-measurement/tree/main/src/main/proto/wfa/measurement?

If that's the case I thought we agreed to have a mono-repo but with dedicated folder for all secure computation related code?

What are your thoughts @stevenwarejones ?
</blockquote></details>

One issue is that we don't want the control plane and the TEE SDK to consume anything other than common.

Both @Marco-Premier and I had understood @kungfucraig 's comment to be a top-level folder similar to what Marco has.

I think there's a couple good reason to put it in a separate top level folder:
1. We don't want it to consume any-sketch or vid-labeling.... stuff in this folder https://github.com/world-federation-of-advertisers/cross-media-measurement/tree/main/src/main/proto/wfa which is not even under measurement.
2. Its completely separate from Measurement and arguably it can be used for non-measurement Halo use cases.


<!-- Sent from Reviewable.io -->

2024-10-11 14:45 UTC, kungfucraig requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1843)* status: 0 of 4 files reviewed, 7 unresolved discussions (waiting on @Marco-Premier, @SanjayVas, and @stevenwarejones)

___
*[`secure_computation/control_plane/src/main/proto/wfa/controlplane/v1alpha/queue.proto` line 17 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1843#-O8w0FqKCtor0ZLYEF8B:-O8w0FqKCtor0ZLYEF8C:b16bbur) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c0a70aed9ad4965b06a36fb32884bc010e80b5b8/secure_computation/control_plane/src/main/proto/wfa/controlplane/v1alpha/queue.proto#L17)):*
> ```proto
> syntax = "proto3";
> 
> package wfa.controlplane.v1alpha;
> ```

Can you update the proto package and directory to be a mirror of whatever the java package is? (i.e. wfa/securecomput[e|ation]/controlplane/v1alpha/...)
___
*[`confidential_computing/control_plane/src/main/proto/wfa/controlplane/work_item.proto` line 21 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1843#-O8mc-In5l8dSfmyfVgP:-O8vzZAR0fJTl4Ib4B7n:b-y0n56e) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/386f5b4d23aae919a3594e5efb7de0919f81e62e/confidential_computing/control_plane/src/main/proto/wfa/controlplane/work_item.proto#L21)):*
<details><summary><i>Previously, Marco-Premier (marcopremier) wrote…</i></summary><blockquote>

I used `org.wfanet.securecomputation.controlplane.v1alpha` because I thought that we may have other sub-packages under `securecomputation` in future?

Let me know what you think
</blockquote></details>

I like `org.wfanet.securecomputation.controlplane.v1alpha` 

If you want to shorten it, s/securecomputation/securecompute
___
*[`confidential_computing/control_plane/src/main/proto/wfa/controlplane/work_item.proto` line 26 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1843#-O8rTz7b1HMUPMH-d7au:-O8w--GOC-wwjCTEdNHC:b-c6om16) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/386f5b4d23aae919a3594e5efb7de0919f81e62e/confidential_computing/control_plane/src/main/proto/wfa/controlplane/work_item.proto#L26)):*
<details><summary><i>Previously, Marco-Premier (marcopremier) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Can we drop the hyphens from the subdomains, or is that the convention we've already adopted?
___
*[`confidential_computing/control_plane/src/main/proto/wfa/controlplane/work_item.proto` line 37 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1843#-O8rTeXW6-9bFU7nySFw:-O8w-jPhBTcz-rC9Kutl:b6ftfqv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/386f5b4d23aae919a3594e5efb7de0919f81e62e/confidential_computing/control_plane/src/main/proto/wfa/controlplane/work_item.proto#L37)):*
<details><summary><i>Previously, Marco-Premier (marcopremier) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Per https://google.aip.dev/122

I think you want this to be "string queue = 2;"
___
*[`secure_computation/control_plane/src/main/proto/wfa/controlplane/v1alpha/work_items_service.proto` line 1 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1843#-O8w13P241FqImneRl7o:-O8w13P241FqImneRl7p:bb6ht39) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c0a70aed9ad4965b06a36fb32884bc010e80b5b8/secure_computation/control_plane/src/main/proto/wfa/controlplane/v1alpha/work_items_service.proto#L1)):*
> ```proto
> // Copyright 2021 The Cross-Media Measurement Authors
> ```

2024


<!-- Sent from Reviewable.io -->

2024-10-11 18:06 UTC, SanjayVas requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1843)* status: 0 of 4 files reviewed, 7 unresolved discussions (waiting on @kungfucraig, @Marco-Premier, and @stevenwarejones)

___
*[`confidential_computing/control_plane/src/main/proto/wfa/controlplane/work_item.proto` line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1843#-O8rQsjp1vJsARtuKi1F:-O8wioGk663CGp3roHr-:b-91cnrh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/386f5b4d23aae919a3594e5efb7de0919f81e62e/confidential_computing/control_plane/src/main/proto/wfa/controlplane/work_item.proto#L1)):*
> Both @Marco-Premier and I had understood @kungfucraig 's comment to be a top-level folder similar to what Marco has.

This was clearly a misunderstanding. Nothing should have a separate folder at the root of the repo, only at the root Halo package.

> We don't want it to consume any-sketch or vid-labeling.... stuff in this folder https://github.com/world-federation-of-advertisers/cross-media-measurement/tree/main/src/main/proto/wfa which is not even under measurement.

There's no reason that being a sibling to other Halo components implies that this would depend on or be used by those other component packages.

> Its completely separate from Measurement and arguably it can be used for non-measurement Halo use cases.

There's no such thing as a non-measurement Halo use case.  The whole Halo project is for measurement in general. The full name of Halo is "Halo Cross-Media Measurement", hence why this repo is named `cross-media-measurement` and the domain is halo-cmm.org. As I stated above, the intent was that the `measurement` package means Halo, where the parent `wfa` package means all of the WFA. This is why I'm stating that e.g. `panelmatch` is also at the wrong level and should have been under `measurement`.


<!-- Sent from Reviewable.io -->

2024-10-11 21:07 UTC, stevenwarejones requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1843)* status: 0 of 4 files reviewed, 6 unresolved discussions (waiting on @kungfucraig, @Marco-Premier, and @SanjayVas)

___
*[`secure_computation/control_plane/src/main/proto/wfa/controlplane/v1alpha/work_items_service.proto` line 17 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1843#-O8xP2e97wlHlZyVBjz_:-O8xP2eAEBJ3AK72wYsd:b-zb6yzw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c0a70aed9ad4965b06a36fb32884bc010e80b5b8/secure_computation/control_plane/src/main/proto/wfa/controlplane/v1alpha/work_items_service.proto#L17)):*
> ```proto
> syntax = "proto3";
> 
> package wfa.controlplane.v1alpha;
> ```

ditto on craig's comment about the package namespace


<!-- Sent from Reviewable.io -->

2024-10-16 10:02 UTC, Marco-Premier reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1843)* status: 0 of 4 files reviewed, 6 unresolved discussions (waiting on @kungfucraig, @SanjayVas, and @stevenwarejones)

___
*[`secure_computation/control_plane/src/main/proto/wfa/controlplane/v1alpha/queue.proto` line 17 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1843#-O8w0FqKCtor0ZLYEF8B:-O9Ji9yzAV_DobsecYTS:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c0a70aed9ad4965b06a36fb32884bc010e80b5b8/secure_computation/control_plane/src/main/proto/wfa/controlplane/v1alpha/queue.proto#L17)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Can you update the proto package and directory to be a mirror of whatever the java package is? (i.e. wfa/securecomput[e|ation]/controlplane/v1alpha/...)
</blockquote></details>

Done.
___
*[`confidential_computing/control_plane/src/main/proto/wfa/controlplane/work_item.proto` line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1843#-O8rQsjp1vJsARtuKi1F:-O9Ji6qJ6UkhVQmmLRHx:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/386f5b4d23aae919a3594e5efb7de0919f81e62e/confidential_computing/control_plane/src/main/proto/wfa/controlplane/work_item.proto#L1)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I think you may be conflating the `measurement` package as being for the CMMS/PRFE as opposed to all of Halo in general.
</blockquote></details>

Done.
___
*[`confidential_computing/control_plane/src/main/proto/wfa/controlplane/work_item.proto` line 37 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1843#-O8rTeXW6-9bFU7nySFw:-O9JhO6_ArIIPaDatDQ5:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/386f5b4d23aae919a3594e5efb7de0919f81e62e/confidential_computing/control_plane/src/main/proto/wfa/controlplane/work_item.proto#L37)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Per https://google.aip.dev/122

I think you want this to be "string queue = 2;"
</blockquote></details>

Done.
___
*[`secure_computation/control_plane/src/main/proto/wfa/controlplane/v1alpha/work_items_service.proto` line 1 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1843#-O8w13P241FqImneRl7o:-O9Ji3uD711pkbWtQbFr:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c0a70aed9ad4965b06a36fb32884bc010e80b5b8/secure_computation/control_plane/src/main/proto/wfa/controlplane/v1alpha/work_items_service.proto#L1)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

2024
</blockquote></details>

Done.
___
*[`secure_computation/control_plane/src/main/proto/wfa/controlplane/v1alpha/work_items_service.proto` line 17 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1843#-O8xP2e97wlHlZyVBjz_:-O9Ji06Z5b6qVDPaBPzX:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c0a70aed9ad4965b06a36fb32884bc010e80b5b8/secure_computation/control_plane/src/main/proto/wfa/controlplane/v1alpha/work_items_service.proto#L17)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

ditto on craig's comment about the package namespace
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-10-16 16:38 UTC, Marco-Premier reviewed
Done. Sorry for the mistake. I flag that `measurement/api/v2alpha/event_group_metadata/...` still uses the `_`

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1843#-:-O9L8Ygh8oPzeiSdVUck:b4xiflg)* status: 0 of 4 files reviewed, 6 unresolved discussions (waiting on @kungfucraig, @SanjayVas, and @stevenwarejones)

___
*[`confidential_computing/control_plane/src/main/proto/wfa/controlplane/work_item.proto` line 17 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1843#-O8rST9R2fb-lJBA34wQ:-O9L8pWH4ZhGC8PH9Gnf:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/386f5b4d23aae919a3594e5efb7de0919f81e62e/confidential_computing/control_plane/src/main/proto/wfa/controlplane/work_item.proto#L17)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

wfa.measurement.securecomputation.controlplane ?
</blockquote></details>

Done.
___
*[`confidential_computing/control_plane/src/main/proto/wfa/controlplane/work_item.proto` line 21 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1843#-O9L-9_f2uNw-Znpsr-h:-O9L8q3F3yb3-MAq2LmR:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/386f5b4d23aae919a3594e5efb7de0919f81e62e/confidential_computing/control_plane/src/main/proto/wfa/controlplane/work_item.proto#L21)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Same as above.
</blockquote></details>

Done.
___
*[`confidential_computing/control_plane/src/main/proto/wfa/controlplane/work_item.proto` line 37 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1843#-O8rTeXW6-9bFU7nySFw:-O9LAUkZ37p0xIqbT8m4:bxkzslt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/386f5b4d23aae919a3594e5efb7de0919f81e62e/confidential_computing/control_plane/src/main/proto/wfa/controlplane/work_item.proto#L37)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

I think the AIP wants this to be called just "queue"
</blockquote></details>

I'm not sure I follow @kungfucraig . I read the AIP and section `### Fields representing another resource` which indicates the resource name to be string.

Isn't `string queue = 2;` correct? Can you please suggest what you mean by `this to be called just "queue"`?

thanks


<!-- Sent from Reviewable.io -->

2024-10-16 17:47 UTC, kungfucraig approved these changes
> Reviewed 1 of 4 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1843)* status: all files reviewed, 5 unresolved discussions (waiting on @Marco-Premier, @SanjayVas, and @stevenwarejones)

___
*[`confidential_computing/control_plane/src/main/proto/wfa/controlplane/work_item.proto` line 37 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1843#-O8rTeXW6-9bFU7nySFw:-O9LQB1O27TTem7vu8_J:bqi0j3r) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/386f5b4d23aae919a3594e5efb7de0919f81e62e/confidential_computing/control_plane/src/main/proto/wfa/controlplane/work_item.proto#L37)):*
<details><summary><i>Previously, Marco-Premier (marcopremier) wrote…</i></summary><blockquote>

I'm not sure I follow @kungfucraig . I read the AIP and section `### Fields representing another resource` which indicates the resource name to be string.

Isn't `string queue = 2;` correct? Can you please suggest what you mean by `this to be called just "queue"`?

thanks
</blockquote></details>

I read: "queue_identifier" before. Looks good now. Sorry for any confusion.
___
*[`src/main/proto/wfa/measurement/securecomputation/controlplane/v1alpha/work_items_service.proto` line 30 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1843#-O9LR0pS8cx0kT554o3X:-O9LR0pS8cx0kT554o3Y:bhcq5e7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c9b574b07df9cf7d92265ca2dc1284ea767846a8/src/main/proto/wfa/measurement/securecomputation/controlplane/v1alpha/work_items_service.proto#L30)):*
> ```proto
>     //
>     // Enqueues the `WorkItem` into the appropriate queue.
>     // Results in PERMISSION_DENIED if the queue_identifier specified in the `WorkItem`
> ```

nit: s/queue_identifier/queue


<!-- Sent from Reviewable.io -->

2024-10-16 20:29 UTC, stevenwarejones approved these changes
> Reviewed 2 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1843)* status: all files reviewed, 4 unresolved discussions (waiting on @Marco-Premier and @SanjayVas)

___
*[`confidential_computing/control_plane/src/main/proto/wfa/controlplane/work_item.proto` line 37 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1843#-O8rTeXW6-9bFU7nySFw:-O9M00df8HH08j_ISsqD:b-xhpik3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/386f5b4d23aae919a3594e5efb7de0919f81e62e/confidential_computing/control_plane/src/main/proto/wfa/controlplane/work_item.proto#L37)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

I read: "queue_identifier" before. Looks good now. Sorry for any confusion.
</blockquote></details>

I'd prefer a queue message type
```
message queue {
    string name;
}
```



<!-- Sent from Reviewable.io -->

2024-10-16 20:35 UTC, kungfucraig approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1843)* status: all files reviewed, 4 unresolved discussions (waiting on @Marco-Premier and @SanjayVas)

___
*[`confidential_computing/control_plane/src/main/proto/wfa/controlplane/work_item.proto` line 37 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1843#-O8rTeXW6-9bFU7nySFw:-O9M1HjyDtZ2m6w4w3RX:b-y4rk5i) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/386f5b4d23aae919a3594e5efb7de0919f81e62e/confidential_computing/control_plane/src/main/proto/wfa/controlplane/work_item.proto#L37)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

I'd prefer a queue message type
```
message queue {
    string name;
}
```

</blockquote></details>

Can we just follow the AIP for this? https://google.aip.dev/122#fields-representing-another-resource


<!-- Sent from Reviewable.io -->

2024-10-16 22:36 UTC, SanjayVas requested changes
> Reviewed 1 of 4 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1843)* status: all files reviewed, 3 unresolved discussions (waiting on @Marco-Premier)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1843#-O9MSyiV-JPKIpHzHOWG:-O9MSyiV-JPKIpHzHOWH:b3agdd2) (no related file):*
Add this as an included path in src/main/proto/api-linter.yaml and update .github/workflows/api-lint.yml to lint this API.

___


<!-- Sent from Reviewable.io -->

2024-10-17 17:10 UTC, Marco-Premier reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1843)* status: 1 of 7 files reviewed, 2 unresolved discussions (waiting on @kungfucraig, @SanjayVas, and @stevenwarejones)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1843#-O9MSyiV-JPKIpHzHOWG:-O9QSO3JBN7kmLwVgb0o:b-896fix) (no related file):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Add this as an included path in src/main/proto/api-linter.yaml and update .github/workflows/api-lint.yml to lint this API.
</blockquote></details>

Done.

___


<!-- Sent from Reviewable.io -->

2024-10-17 17:21 UTC, SanjayVas requested changes
> Reviewed 5 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1843)* status: 6 of 7 files reviewed, 5 unresolved discussions (waiting on @kungfucraig, @Marco-Premier, and @stevenwarejones)

___
*[`MODULE.bazel.lock` line 2505 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1843#-O9QTo1uAFBDIzA_n2Ue:-O9QTo1uAFBDIzA_n2Uf:b60p585) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f012a1666a1c9521c8cdecef99a1cfd2db1f5307/MODULE.bazel.lock#L2505)):*
> ```JSON
>         ]
>       },
>       "os:osx,arch:aarch64": {
> ```

This shouldn't have needed changing in this PR as MODULE.bazel was not updated.
___
*[`src/main/proto/api-linter.yaml` line 51 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1843#-O9QUCeoCmMC9jdN7fxX:-O9QUCep4U056by-EOzj:bmb7wrx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f012a1666a1c9521c8cdecef99a1cfd2db1f5307/src/main/proto/api-linter.yaml#L51)):*
> ```YAML
>   - 'wfa/measurement/securecomputation/controlplane/v1*/*.proto'
>   disabled_rules:
>   - 'core::0133::request-id-field'
> ```

nit: would you mind documenting why each of these is disabled like is done for the system API?
___
*[`src/main/proto/api-linter.yaml` line 54 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1843#-O9QUTgk1GuQLJdb01Ww:-O9QUTgk1GuQLJdb01Wx:b-dts54k) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f012a1666a1c9521c8cdecef99a1cfd2db1f5307/src/main/proto/api-linter.yaml#L54)):*
> ```YAML
>   - 'core::0121::resource-must-support-get'
>   - 'core::0121::resource-must-support-list'
>   - 'core::0203::field-behavior-required'
> ```

New APIs should not disable this rule. As documented above, it's only disabled for the other API as the corresponding AIP and rule were added later.



_Code quote:_
```YAML
  - 'core::0203::field-behavior-required'
```
___
*[`confidential_computing/control_plane/src/main/proto/wfa/controlplane/work_item.proto` line 37 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1843#-O8rTeXW6-9bFU7nySFw:-O9QUqOX7gQL0950EGpv:bz3r7ou) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/386f5b4d23aae919a3594e5efb7de0919f81e62e/confidential_computing/control_plane/src/main/proto/wfa/controlplane/work_item.proto#L37)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Can we just follow the AIP for this? https://google.aip.dev/122#fields-representing-another-resource
</blockquote></details>

To clarify my above statement, this means making a `Queue` resource type and adding a resource reference annotation here.


<!-- Sent from Reviewable.io -->

2024-10-18 16:44 UTC, kungfucraig approved these changes
> Reviewed 2 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1843)* status: all files reviewed, 5 unresolved discussions (waiting on @Marco-Premier and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2024-10-18 17:36 UTC, stevenwarejones reviewed
> Reviewed 1 of 4 files at r3, 3 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1843)* status: all files reviewed, 5 unresolved discussions (waiting on @Marco-Premier and @SanjayVas)

___
*[`MODULE.bazel.lock` line 2505 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1843#-O9QTo1uAFBDIzA_n2Ue:-O9VgFlO1rccyY-jrmrg:b-o2gff5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f012a1666a1c9521c8cdecef99a1cfd2db1f5307/MODULE.bazel.lock#L2505)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This shouldn't have needed changing in this PR as MODULE.bazel was not updated.
</blockquote></details>

I'm guessing this was added this he compiled it on a mac? If that's the case, this will keep popping up and I suggest just keeping it.


<!-- Sent from Reviewable.io -->

2024-10-18 18:02 UTC, SanjayVas requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1843)* status: all files reviewed, 5 unresolved discussions (waiting on @Marco-Premier and @stevenwarejones)

___
*[`MODULE.bazel.lock` line 2505 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1843#-O9QTo1uAFBDIzA_n2Ue:-O9Vmem688xzm0qgicXm:b4hdqrl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f012a1666a1c9521c8cdecef99a1cfd2db1f5307/MODULE.bazel.lock#L2505)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

I'm guessing this was added this he compiled it on a mac? If that's the case, this will keep popping up and I suggest just keeping it.
</blockquote></details>

This project is never intended to be compiled on a Mac, so this should in fact not be added.


<!-- Sent from Reviewable.io -->

2024-10-21 12:10 UTC, Marco-Premier reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1843)* status: 2 of 8 files reviewed, 4 unresolved discussions (waiting on @kungfucraig, @SanjayVas, and @stevenwarejones)

___
*[`MODULE.bazel.lock` line 2505 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1843#-O9QTo1uAFBDIzA_n2Ue:-O9ixqqFDcrucJefAtMU:b-f25enb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f012a1666a1c9521c8cdecef99a1cfd2db1f5307/MODULE.bazel.lock#L2505)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This project is never intended to be compiled on a Mac, so this should in fact not be added.
</blockquote></details>

Reset file to its original content
___
*[`src/main/proto/api-linter.yaml` line 54 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1843#-O9QUTgk1GuQLJdb01Ww:-O9i71QyDU5vGwOA6hSo:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f012a1666a1c9521c8cdecef99a1cfd2db1f5307/src/main/proto/api-linter.yaml#L54)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

New APIs should not disable this rule. As documented above, it's only disabled for the other API as the corresponding AIP and rule were added later.
</blockquote></details>

Done.
___
*[`confidential_computing/control_plane/src/main/proto/wfa/controlplane/work_item.proto` line 37 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1843#-O8rTeXW6-9bFU7nySFw:-O9ixuso6RyJdl5CIQDj:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/386f5b4d23aae919a3594e5efb7de0919f81e62e/confidential_computing/control_plane/src/main/proto/wfa/controlplane/work_item.proto#L37)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

To clarify my above statement, this means making a `Queue` resource type and adding a resource reference annotation here.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-10-21 17:22 UTC, SanjayVas approved these changes
> Reviewed 6 of 6 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1843)* status: all files reviewed, 1 unresolved discussion (waiting on @Marco-Premier and @stevenwarejones)

___
*[`MODULE.bazel.lock` line 2505 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1843#-O9QTo1uAFBDIzA_n2Ue:-O9k574v47VZtAM4qyOo:b-yg01po) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f012a1666a1c9521c8cdecef99a1cfd2db1f5307/MODULE.bazel.lock#L2505)):*
<details><summary><i>Previously, Marco-Premier (marcopremier) wrote…</i></summary><blockquote>

Reset file to its original content
</blockquote></details>

Still seeing some diffs here.


<!-- Sent from Reviewable.io -->

2024-10-22 07:31 UTC, Marco-Premier reviewed
> Reviewed 1 of 4 files at r3, 1 of 6 files at r5, 2 of 6 files at r6, 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1843)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)



<!-- Sent from Reviewable.io -->

2024-10-22 09:21 UTC, merged