Measurement prober unit test
world-federation-of-advertisers/cross-media-measurement pull request #1848
Opened 2024-10-10 06:04 UTC by roaminggypsy

Draft

TODO:
1. update BUILD
2. rebase after metric creation and publication logic is merged
3. how to mock privateKeyDerFile
4. do we want to verify metrics or OpenTelemetry for each test case
5. does it make sense to make run() return Measurement?
6. what other cases and functions need to be tested? remember we want to test the interface, not the implementation

2024-10-10 06:05 UTC, wfa-reviewable commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1848)
<!-- Reviewable:end -->

2024-10-17 23:29 UTC, SanjayVas requested changes
> Reviewed 2 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1848)* status: 2 of 5 files reviewed, 1 unresolved discussion (waiting on @roaminggypsy)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/batch/MeasurementSystemProber.kt` line 107 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1848#-O9Rnb0A6Ml2vSr2K-wh:-O9Rnb0A6Ml2vSr2K-wi:b-pfgx6z) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bc2432915485a1c1072486324a8b3d06a4f8738b/src/main/kotlin/org/wfanet/measurement/kingdom/batch/MeasurementSystemProber.kt#L107)):*
> ```Kotlin
>       .build()
> 
>   suspend fun run(): Measurement? {
> ```

This should not return a Measurement just for testing.

You can determine when a Measurement has been created in the test by hooking into the measurements service mock and capturing the value when its called. See Mockito's ArgumentCaptor.


<!-- Sent from Reviewable.io -->

2024-10-17 23:31 UTC, SanjayVas requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1848)* status: 2 of 5 files reviewed, 4 unresolved discussions (waiting on @roaminggypsy)

___
*[`src/test/kotlin/org/wfanet/measurement/kingdom/batch/MeasurementSystemProberTest.kt` line 138 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1848#-O9RoLax2ZhyyaQdPHLB:-O9RoLayD-MUTf7Nt9wc:b-goxry2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bc2432915485a1c1072486324a8b3d06a4f8738b/src/test/kotlin/org/wfanet/measurement/kingdom/batch/MeasurementSystemProberTest.kt#L138)):*
> ```Kotlin
>   fun `run creates a new prober measurement when there is no previous prober measurement`(): Unit =
>     runBlocking {
>       `when`(measurementsMock.listMeasurements(anyOrNull())).thenReturn(listMeasurementsResponse {})
> ```

MockitoKotlin adds a `whenever` alias so you don't need to escape the keyword



_Suggestion:_
```Kotlin
whenever
```
___
*[`src/test/kotlin/org/wfanet/measurement/kingdom/batch/MeasurementSystemProberTest.kt` line 138 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1848#-O9RoZPkExh4x0Nkyf2I:-O9RoZPkExh4x0Nkyf2J:biit1bq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bc2432915485a1c1072486324a8b3d06a4f8738b/src/test/kotlin/org/wfanet/measurement/kingdom/batch/MeasurementSystemProberTest.kt#L138)):*
> ```Kotlin
>   fun `run creates a new prober measurement when there is no previous prober measurement`(): Unit =
>     runBlocking {
>       `when`(measurementsMock.listMeasurements(anyOrNull())).thenReturn(listMeasurementsResponse {})
> ```

The argument cannot be null



_Suggestion:_
```Kotlin
any()
```
___
*[`src/test/kotlin/org/wfanet/measurement/kingdom/batch/MeasurementSystemProberTest.kt` line 140 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1848#-O9RoBbk-gmFLP-mLQTa:-O9RoBblCE8P4E7TWQWq:b11kwyi) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bc2432915485a1c1072486324a8b3d06a4f8738b/src/test/kotlin/org/wfanet/measurement/kingdom/batch/MeasurementSystemProberTest.kt#L140)):*
> ```Kotlin
>       `when`(measurementsMock.listMeasurements(anyOrNull())).thenReturn(listMeasurementsResponse {})
>       val measurement = prober.run()
>       Truth.assertThat(measurement).isNotNull()
> ```

Add an import for this function so you can just call it as `assertThat` to be consistent with all other tests.



_Code quote:_
```Kotlin
Truth.assertThat
```


<!-- Sent from Reviewable.io -->

2024-10-22 06:41 UTC, roaminggypsy reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1848)* status: 2 of 5 files reviewed, 4 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/batch/MeasurementSystemProber.kt` line 107 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1848#-O9Rnb0A6Ml2vSr2K-wh:-O9lKjBU4JDfc19-GT5E:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bc2432915485a1c1072486324a8b3d06a4f8738b/src/main/kotlin/org/wfanet/measurement/kingdom/batch/MeasurementSystemProber.kt#L107)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This should not return a Measurement just for testing.

You can determine when a Measurement has been created in the test by hooking into the measurements service mock and capturing the value when its called. See Mockito's ArgumentCaptor.
</blockquote></details>

Done.
___
*[`src/test/kotlin/org/wfanet/measurement/kingdom/batch/MeasurementSystemProberTest.kt` line 138 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1848#-O9RoLax2ZhyyaQdPHLB:-O9lWQn4DerfxCxwjO5t:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bc2432915485a1c1072486324a8b3d06a4f8738b/src/test/kotlin/org/wfanet/measurement/kingdom/batch/MeasurementSystemProberTest.kt#L138)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

MockitoKotlin adds a `whenever` alias so you don't need to escape the keyword
</blockquote></details>

Done.
___
*[`src/test/kotlin/org/wfanet/measurement/kingdom/batch/MeasurementSystemProberTest.kt` line 138 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1848#-O9RoZPkExh4x0Nkyf2I:-O9lWlaVCYiIaWiIaQE5:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bc2432915485a1c1072486324a8b3d06a4f8738b/src/test/kotlin/org/wfanet/measurement/kingdom/batch/MeasurementSystemProberTest.kt#L138)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The argument cannot be null
</blockquote></details>

Done.
___
*[`src/test/kotlin/org/wfanet/measurement/kingdom/batch/MeasurementSystemProberTest.kt` line 140 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1848#-O9RoBbk-gmFLP-mLQTa:-O9lWFN18U1lxALIWL7v:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bc2432915485a1c1072486324a8b3d06a4f8738b/src/test/kotlin/org/wfanet/measurement/kingdom/batch/MeasurementSystemProberTest.kt#L140)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Add an import for this function so you can just call it as `assertThat` to be consistent with all other tests.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-10-22 20:49 UTC, SanjayVas requested changes
> Reviewed 1 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1848)* status: 3 of 5 files reviewed, 8 unresolved discussions (waiting on @roaminggypsy)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1848#-O9pwyvy7Yqpjp3R5SJW:-O9pwyvy7Yqpjp3R5SJX:b-yh4fam) (no related file):*
Follow the Conventional Commits specification for PR descriptions. See https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/docs/dev-standards.md#pull-request-description

___
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/batch/MeasurementSystemProber.kt` line 262 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1848#-O9pxU-76N4InKgiMwp0:-O9pxU-76N4InKgiMwp1:b-xpr05a) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e03ba25da1d88220b8b66e9a306089284cd485ef/src/main/kotlin/org/wfanet/measurement/kingdom/batch/MeasurementSystemProber.kt#L262)):*
> ```Kotlin
>   }
> 
>   suspend fun getLastUpdatedMeasurement(): Measurement? {
> ```

This should be private. It's not part of the public API, which should consist solely of `run`. See https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/docs/code-style.md#general
___
*[`src/test/kotlin/org/wfanet/measurement/kingdom/batch/MeasurementSystemProberTest.kt` line 143 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1848#-O9pxrU09pyTGCH6DOBq:-O9pxrU09pyTGCH6DOBr:undefined) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e03ba25da1d88220b8b66e9a306089284cd485ef/src/test/kotlin/org/wfanet/measurement/kingdom/batch/MeasurementSystemProberTest.kt#L143)):*
> ```Kotlin
>   fun `run creates a new prober measurement when there is no previous prober measurement`(): Unit =
>     runBlocking {
>       whenever(measurementsMock.listMeasurements(any())).thenReturn(listMeasurementsResponse {})
> ```





_Suggestion:_
```Kotlin
ListMeasurmentResponse.getDefaultInstance()
```
___
*[`src/test/kotlin/org/wfanet/measurement/kingdom/batch/MeasurementSystemProberTest.kt` line 150 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1848#-O9pxxOF0PiPipXHxhyA:-O9pxxOF0PiPipXHxhyB:b5babg4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e03ba25da1d88220b8b66e9a306089284cd485ef/src/test/kotlin/org/wfanet/measurement/kingdom/batch/MeasurementSystemProberTest.kt#L150)):*
> ```Kotlin
>           }
>           .firstValue
>       assertThat(createMeasurementRequest).isNotNull()
> ```

Actually verify that the create request is correct. You'll want to import `com.google.common.truth.extensions.proto.ProtoTruth.assertThat` for protobuf message assertions.
___
*[`src/test/kotlin/org/wfanet/measurement/kingdom/batch/MeasurementSystemProberTest.kt` line 198 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1848#-O9pyD1v-pJqKsuZP0jn:-O9pyD1v-pJqKsuZP0jo:by67ewy) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e03ba25da1d88220b8b66e9a306089284cd485ef/src/test/kotlin/org/wfanet/measurement/kingdom/batch/MeasurementSystemProberTest.kt#L198)):*
> ```Kotlin
>     private val DURATION_BETWEEN_MEASUREMENT = Duration.ofDays(1)
>     private val MEASUREMENT_LOOKBACK_DURATION = Duration.ofDays(1)
>     private val CLOCK = Mockito.mock<Clock>()
> ```

Don't mock Clock. Use a fake clock instance if needed. e.g. `org.wfanet.measurement.common.testing.TestClockWithNamedInstants`.
___
*[`src/test/kotlin/org/wfanet/measurement/kingdom/batch/MeasurementSystemProberTest.kt` line 198 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1848#-O9pyis102roVvmKr61D:-O9pyis102roVvmKr61E:b-b0nsfb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e03ba25da1d88220b8b66e9a306089284cd485ef/src/test/kotlin/org/wfanet/measurement/kingdom/batch/MeasurementSystemProberTest.kt#L198)):*
> ```Kotlin
>     private val DURATION_BETWEEN_MEASUREMENT = Duration.ofDays(1)
>     private val MEASUREMENT_LOOKBACK_DURATION = Duration.ofDays(1)
>     private val CLOCK = Mockito.mock<Clock>()
> ```

This is not a constant, but rather an object with state



_Suggestion:_
```Kotlin
clock
```
___
*[`src/test/kotlin/org/wfanet/measurement/kingdom/batch/MeasurementSystemProberTest.kt` line 217 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1848#-O9pz1_4AwXui8-z4fKJ:-O9pz1_4AwXui8-z4fKK:b-mpo6xs) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e03ba25da1d88220b8b66e9a306089284cd485ef/src/test/kotlin/org/wfanet/measurement/kingdom/batch/MeasurementSystemProberTest.kt#L217)):*
> ```Kotlin
>     }
> 
>     val NOW = Instant.now()
> ```

Only have constants here that are commonly useful/reusable across test methods. Otherwise just define what you need in the given test method.
___
*[`src/test/kotlin/org/wfanet/measurement/kingdom/batch/MeasurementSystemProberTest.kt` line 218 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1848#-O9pyyQ_-VybKxJq7r_Z:-O9pyyQ_-VybKxJq7r__:b-dd83gr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e03ba25da1d88220b8b66e9a306089284cd485ef/src/test/kotlin/org/wfanet/measurement/kingdom/batch/MeasurementSystemProberTest.kt#L218)):*
> ```Kotlin
> 
>     val NOW = Instant.now()
>     val OLD_FINISHED_MEASUREMENT = measurement {
> ```

Everything in this companion object should be private


<!-- Sent from Reviewable.io -->

2024-10-22 22:11 UTC, roaminggypsy reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1848)* status: 3 of 5 files reviewed, 8 unresolved discussions (waiting on @SanjayVas)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1848#-O9pwyvy7Yqpjp3R5SJW:-O9qH6Av1_iFJo9xvld8:b-896fix) (no related file):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Follow the Conventional Commits specification for PR descriptions. See https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/docs/dev-standards.md#pull-request-description
</blockquote></details>

Done.

___
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/batch/MeasurementSystemProber.kt` line 262 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1848#-O9pxU-76N4InKgiMwp0:-O9q-54HEJ_kSbaM1pkE:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e03ba25da1d88220b8b66e9a306089284cd485ef/src/main/kotlin/org/wfanet/measurement/kingdom/batch/MeasurementSystemProber.kt#L262)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This should be private. It's not part of the public API, which should consist solely of `run`. See https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/docs/code-style.md#general
</blockquote></details>

Done.
___
*[`src/test/kotlin/org/wfanet/measurement/kingdom/batch/MeasurementSystemProberTest.kt` line 143 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1848#-O9pxrU09pyTGCH6DOBq:-O9q-C0R30MJ8rgHslkF:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e03ba25da1d88220b8b66e9a306089284cd485ef/src/test/kotlin/org/wfanet/measurement/kingdom/batch/MeasurementSystemProberTest.kt#L143)):*
> ```Kotlin
>   fun `run creates a new prober measurement when there is no previous prober measurement`(): Unit =
>     runBlocking {
>       whenever(measurementsMock.listMeasurements(any())).thenReturn(listMeasurementsResponse {})
> ```

Done.
___
*[`src/test/kotlin/org/wfanet/measurement/kingdom/batch/MeasurementSystemProberTest.kt` line 150 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1848#-O9pxxOF0PiPipXHxhyA:-O9q1Y8D1A5GGdAyMIL0:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e03ba25da1d88220b8b66e9a306089284cd485ef/src/test/kotlin/org/wfanet/measurement/kingdom/batch/MeasurementSystemProberTest.kt#L150)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Actually verify that the create request is correct. You'll want to import `com.google.common.truth.extensions.proto.ProtoTruth.assertThat` for protobuf message assertions.
</blockquote></details>

Done.
___
*[`src/test/kotlin/org/wfanet/measurement/kingdom/batch/MeasurementSystemProberTest.kt` line 198 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1848#-O9pyD1v-pJqKsuZP0jn:-O9q0sjFCtKBbwY9k4g-:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e03ba25da1d88220b8b66e9a306089284cd485ef/src/test/kotlin/org/wfanet/measurement/kingdom/batch/MeasurementSystemProberTest.kt#L198)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Don't mock Clock. Use a fake clock instance if needed. e.g. `org.wfanet.measurement.common.testing.TestClockWithNamedInstants`.
</blockquote></details>

Done.
___
*[`src/test/kotlin/org/wfanet/measurement/kingdom/batch/MeasurementSystemProberTest.kt` line 198 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1848#-O9pyis102roVvmKr61D:-O9q-WnZ0MIwIfeq3FEU:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e03ba25da1d88220b8b66e9a306089284cd485ef/src/test/kotlin/org/wfanet/measurement/kingdom/batch/MeasurementSystemProberTest.kt#L198)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This is not a constant, but rather an object with state
</blockquote></details>

Done.
___
*[`src/test/kotlin/org/wfanet/measurement/kingdom/batch/MeasurementSystemProberTest.kt` line 217 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1848#-O9pz1_4AwXui8-z4fKJ:-O9qFX3sAbNd-XnhFVdB:bs7wumb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e03ba25da1d88220b8b66e9a306089284cd485ef/src/test/kotlin/org/wfanet/measurement/kingdom/batch/MeasurementSystemProberTest.kt#L217)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Only have constants here that are commonly useful/reusable across test methods. Otherwise just define what you need in the given test method.
</blockquote></details>

Done.
___
*[`src/test/kotlin/org/wfanet/measurement/kingdom/batch/MeasurementSystemProberTest.kt` line 218 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1848#-O9pyyQ_-VybKxJq7r_Z:-O9q-LgpCjGMGv23K-O1:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e03ba25da1d88220b8b66e9a306089284cd485ef/src/test/kotlin/org/wfanet/measurement/kingdom/batch/MeasurementSystemProberTest.kt#L218)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Everything in this companion object should be private
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-10-22 23:18 UTC, SanjayVas requested changes
> Reviewed 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1848)* status: 4 of 5 files reviewed, 4 unresolved discussions (waiting on @roaminggypsy)

___
*[`src/test/kotlin/org/wfanet/measurement/kingdom/batch/MeasurementSystemProberTest.kt` line 150 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1848#-O9pxxOF0PiPipXHxhyA:-O9qVQy-034kWvZzPOXL:b-7fi27y) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e03ba25da1d88220b8b66e9a306089284cd485ef/src/test/kotlin/org/wfanet/measurement/kingdom/batch/MeasurementSystemProberTest.kt#L150)):*
<details><summary><i>Previously, roaminggypsy (Lin) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

What I meant was to verify the contents of `createMeasurementRequest`, e.g. `assertThat(createMeasurementRequest).isEqualTo(createMeasurementRequest { foo = bar })`

There's in fact a helper function that will handle the captor part for you and return a ProtoSubject that you can call `isEqualTo` on. See `org.wfanet.measurement.common.testing.verifyProtoArgument`
___
*[`src/test/kotlin/org/wfanet/measurement/kingdom/batch/MeasurementSystemProberTest.kt` line 92 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1848#-O9qUmM35ylwvrr1xRy3:-O9qUmM4BQNZ9Jd0Jkna:b-mel6df) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bf65d930235b694174d6cd0917cb50e71f5a6f43/src/test/kotlin/org/wfanet/measurement/kingdom/batch/MeasurementSystemProberTest.kt#L92)):*
> ```Kotlin
>     }
>   }
>   private val listRequisitionsResponse: ListRequisitionsResponse = listRequisitionsResponse {}
> ```

These ones *are* constants (even if they can't use the `const` keyword). Notice how they are immutable objects where the only methods are accessors.



_Code quote:_
```Kotlin
  private val durationBetweenMeasurement = Duration.ofDays(1)

  private val listEventGroupsResponse: ListEventGroupsResponse = listEventGroupsResponse {
    eventGroups += eventGroup {
      name = EVENT_GROUP_NAME
      measurementConsumer = MEASUREMENT_CONSUMER_NAME
      eventGroupReferenceId = "aaa"
      measurementConsumerPublicKey = MEASUREMENT_CONSUMER.publicKey.message
      encryptedMetadata =
        MC_ENCRYPTION_PUBLIC_KEY.toPublicKeyHandle()
          .encryptMessage(EventGroup.Metadata.getDefaultInstance().pack())
    }
  }
  private val listRequisitionsResponse: ListRequisitionsResponse = listRequisitionsResponse {}
```
___
*[`src/test/kotlin/org/wfanet/measurement/kingdom/batch/MeasurementSystemProberTest.kt` line 202 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1848#-O9qWPJ3679kANG16XnM:-O9qWPJ3679kANG16XnN:b-yy2xvr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bf65d930235b694174d6cd0917cb50e71f5a6f43/src/test/kotlin/org/wfanet/measurement/kingdom/batch/MeasurementSystemProberTest.kt#L202)):*
> ```Kotlin
>       .thenReturn(listMeasurementsResponse { measurements += newFinishedMeasurement })
>     prober.run()
>     verify(measurementsMock, Mockito.never()).createMeasurement(any())
> ```

nit: import this function



_Code quote:_
```Kotlin
Mockito.never()
```


<!-- Sent from Reviewable.io -->

2024-10-23 18:51 UTC, roaminggypsy reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1848)* status: 4 of 5 files reviewed, 3 unresolved discussions (waiting on @roaminggypsy and @SanjayVas)

___
*[`src/test/kotlin/org/wfanet/measurement/kingdom/batch/MeasurementSystemProberTest.kt` line 150 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1848#-O9pxxOF0PiPipXHxhyA:-O9rwJHV6EL-S6PrHHNA:bjujotv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e03ba25da1d88220b8b66e9a306089284cd485ef/src/test/kotlin/org/wfanet/measurement/kingdom/batch/MeasurementSystemProberTest.kt#L150)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

What I meant was to verify the contents of `createMeasurementRequest`, e.g. `assertThat(createMeasurementRequest).isEqualTo(createMeasurementRequest { foo = bar })`

There's in fact a helper function that will handle the captor part for you and return a ProtoSubject that you can call `isEqualTo` on. See `org.wfanet.measurement.common.testing.verifyProtoArgument`
</blockquote></details>

Mostly updated but RequisitionSpec and MeasurementSpec is not covered in this upload.
Having a hard time finding out why these two spec cause differences in the test (I'm guessing randomness of NONCE, NONCE_HASH, signing, or the time of clock)
___
*[`src/test/kotlin/org/wfanet/measurement/kingdom/batch/MeasurementSystemProberTest.kt` line 92 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1848#-O9qUmM35ylwvrr1xRy3:-O9qZdvg8fVCaq759vX5:by5pb6t) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bf65d930235b694174d6cd0917cb50e71f5a6f43/src/test/kotlin/org/wfanet/measurement/kingdom/batch/MeasurementSystemProberTest.kt#L92)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

These ones *are* constants (even if they can't use the `const` keyword). Notice how they are immutable objects where the only methods are accessors.
</blockquote></details>

Done. I also moved 'now' back to companion object because 1) [Instant is immutable](https://docs.oracle.com/javase/8/docs/api/?java/time/Instant.html) 2) 'now' is reused in two test cases


<!-- Sent from Reviewable.io -->

2024-10-23 22:05 UTC, roaminggypsy reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1848)* status: 3 of 5 files reviewed, 3 unresolved discussions (waiting on @SanjayVas)

___
*[`src/test/kotlin/org/wfanet/measurement/kingdom/batch/MeasurementSystemProberTest.kt` line 150 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1848#-O9pxxOF0PiPipXHxhyA:-O9vOscqE3vMhyR3METe:bp5r9g3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e03ba25da1d88220b8b66e9a306089284cd485ef/src/test/kotlin/org/wfanet/measurement/kingdom/batch/MeasurementSystemProberTest.kt#L150)):*
<details><summary><i>Previously, roaminggypsy (Lin) wrote…</i></summary><blockquote>

Mostly updated but RequisitionSpec and MeasurementSpec is not covered in this upload.
Having a hard time finding out why these two spec cause differences in the test (I'm guessing randomness of NONCE, NONCE_HASH, signing, or the time of clock)
</blockquote></details>

Updated: ignoring measurement spec and requisition spec field during comparisons, similar to [MeasurementSystemTest](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d41374dc534ad9b1deb42ed41cf2fbdd19634bf5/src/test/kotlin/org/wfanet/measurement/api/v2alpha/tools/MeasurementSystemTest.kt#L837)


<!-- Sent from Reviewable.io -->

2024-10-23 23:58 UTC, SanjayVas requested changes
> Reviewed 1 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1848)* status: 4 of 5 files reviewed, 4 unresolved discussions (waiting on @roaminggypsy)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1848#-O9pwyvy7Yqpjp3R5SJW:-O9vGBXT4JpqCqUXP7ZE:b-271y1k) (no related file):*
<details><summary><i>Previously, roaminggypsy (Lin) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

This should use `test` rather than `feat`.

___
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/batch/MeasurementSystemProber.kt` line 89 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1848#-O9vlbv308-mr4bVo9hW:-O9vlbv308-mr4bVo9hX:b1gcxzv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/47bcabfa035c75932468f24178218139a8ed3dcf/src/main/kotlin/org/wfanet/measurement/kingdom/batch/MeasurementSystemProber.kt#L89)):*
> ```Kotlin
>   private val requisitionsStub: RequisitionsGrpcKt.RequisitionsCoroutineStub,
>   private val clock: Clock = Clock.systemUTC(),
>   private val secureRandom: SecureRandom = SecureRandom.getInstance("SHA1PRNG"),
> ```

nit: you don't need to specify the algorithm



_Suggestion:_
```Kotlin
SecureRandom()
```
___
*[`src/test/kotlin/org/wfanet/measurement/kingdom/batch/MeasurementSystemProberTest.kt` line 92 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1848#-O9qUmM35ylwvrr1xRy3:-O9vhEG-5eUsBLAKA-ka:b-ie1fzt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bf65d930235b694174d6cd0917cb50e71f5a6f43/src/test/kotlin/org/wfanet/measurement/kingdom/batch/MeasurementSystemProberTest.kt#L92)):*
> I also moved 'now' back to companion object because 1) Instant is immutable 2) 'now' is reused in two test cases

Is it important/desired that it's the same instant across test methods, as opposed to being the instant the test method itself started? Recall the JUnit instantiates the test object for each method, but all the static (companion object) fields may only be initialized once at JVM startup.
___
*[`src/test/kotlin/org/wfanet/measurement/kingdom/batch/MeasurementSystemProberTest.kt` line 98 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1848#-O9vkpW96k-8TQUrF0gO:-O9vkpW96k-8TQUrF0gP:bjp69wb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/47bcabfa035c75932468f24178218139a8ed3dcf/src/test/kotlin/org/wfanet/measurement/kingdom/batch/MeasurementSystemProberTest.kt#L98)):*
> ```Kotlin
> @RunWith(JUnit4::class)
> class MeasurementSystemProberTest {
>   private val randomMock: SecureRandom = mock()
> ```

It looks like you use the same simple stubbing in every case. Just create a fixed random impl instead. Since it's always the same value, you move the definition to the companion object.



_Suggestion:_
```Kotlin
private val fixedRandom = object : SecureRandom() {
  override fun nextLong(): Long = NONCE
}
```
___
*[`src/test/kotlin/org/wfanet/measurement/kingdom/batch/MeasurementSystemProberTest.kt` line 236 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1848#-O9vn3gt-RdBICJ3wCYE:-O9vmxS2CgwGYjNgqphC:bobkggj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/47bcabfa035c75932468f24178218139a8ed3dcf/src/test/kotlin/org/wfanet/measurement/kingdom/batch/MeasurementSystemProberTest.kt#L236)):*
> ```Kotlin
>       .thenReturn(listMeasurementsResponse { measurements += unfinishedMeasurement })
>     prober.run()
>     verify(measurementsMock, never()).createMeasurement(any())
> ```

Doesn't this also need to verify the other part of the prober behavior? i.e. that it exports some metrics? See https://github.com/world-federation-of-advertisers/common-jvm/blob/main/src/test/kotlin/org/wfanet/measurement/common/InstrumentationTest.kt for an example of how to use InMemoryMetricExporter. Your verification can probably be a little simpler as you don't need to deal with async value recording.


<!-- Sent from Reviewable.io -->

2024-10-24 22:27 UTC, roaminggypsy reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1848)* status: 2 of 5 files reviewed, 3 unresolved discussions (waiting on @SanjayVas)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1848#-O9pwyvy7Yqpjp3R5SJW:-O9wtfduBEUhjCEl622l:b-896fix) (no related file):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This should use `test` rather than `feat`.
</blockquote></details>

Done.

___
___
*[`src/test/kotlin/org/wfanet/measurement/kingdom/batch/MeasurementSystemProberTest.kt` line 98 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1848#-O9vkpW96k-8TQUrF0gO:-O9wxxp14qm71KQvGSAM:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/47bcabfa035c75932468f24178218139a8ed3dcf/src/test/kotlin/org/wfanet/measurement/kingdom/batch/MeasurementSystemProberTest.kt#L98)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

It looks like you use the same simple stubbing in every case. Just create a fixed random impl instead. Since it's always the same value, you move the definition to the companion object.
</blockquote></details>

Done.
___
*[`src/test/kotlin/org/wfanet/measurement/kingdom/batch/MeasurementSystemProberTest.kt` line 236 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1848#-O9vn3gt-RdBICJ3wCYE:-OA-aTiH7Y-exfxhmWF4:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/47bcabfa035c75932468f24178218139a8ed3dcf/src/test/kotlin/org/wfanet/measurement/kingdom/batch/MeasurementSystemProberTest.kt#L236)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Doesn't this also need to verify the other part of the prober behavior? i.e. that it exports some metrics? See https://github.com/world-federation-of-advertisers/common-jvm/blob/main/src/test/kotlin/org/wfanet/measurement/common/InstrumentationTest.kt for an example of how to use InMemoryMetricExporter. Your verification can probably be a little simpler as you don't need to deal with async value recording.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-10-24 23:37 UTC, SanjayVas approved these changes
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1848)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @roaminggypsy)



<!-- Sent from Reviewable.io -->

2024-10-28 12:25 UTC, stevenwarejones approved these changes
> Reviewed 2 of 5 files at r1, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1848)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @roaminggypsy)



<!-- Sent from Reviewable.io -->

2024-10-28 16:57 UTC, merged