Mark v2alpha Builder annotation as internal.
world-federation-of-advertisers/cross-media-measurement pull request #188
Opened 2021-08-10 00:15 UTC by SanjayVas

This uses the `associates` attribute of `kt_jvm_library` to combine multiple targets in the same Kotlin package into a single Kotlin module. This allows us to treat Kotlin's internal visibility more like Java's default/package-private visibility, without having to use a single Bazel target.

2021-08-10 16:56 UTC, efoxepstein requested changes
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/188)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/BUILD.bazel, line 19 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/188#-MgkysG5AFbU3Od_aPGq:-MgkysG5AFbU3Od_aPGr:b-7yksrq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/467b3d17b18b30a0e4d414d64bb26d9689b3a280/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/BUILD.bazel#L19)):*
> ```Starlark
>     name = "certificates",
>     srcs = ["Certificates.kt"],
>     associates = [":builder"],
> ```

I'm a little worried about the depth of magic here. Imagine a newcomer who's a Java expert but is new to Kotlin who wants to understand what's going on. They need to read about:

1. `associates`
2. `@DslMarker`
3. `internal`
4. `annotation class`
5. The DSL that you've defined

I guess I wonder if it's worth it to have marginally more convenient ways to build protos.


<!-- Sent from Reviewable.io -->

2021-08-10 16:56 UTC, efoxepstein approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/188#-:-MgkzXBr5Uh7gsLlGRlC:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)



<!-- Sent from Reviewable.io -->

2021-08-10 21:11 UTC, SanjayVas reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/188)* status: all files reviewed, 1 unresolved discussion (waiting on @efoxepstein)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/BUILD.bazel, line 19 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/188#-MgkysG5AFbU3Od_aPGq:-Mgl2gygAW1I1Dl-x_ik:b-mjx6mp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/467b3d17b18b30a0e4d414d64bb26d9689b3a280/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/BUILD.bazel#L19)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

I'm a little worried about the depth of magic here. Imagine a newcomer who's a Java expert but is new to Kotlin who wants to understand what's going on. They need to read about:

1. `associates`
2. `@DslMarker`
3. `internal`
4. `annotation class`
5. The DSL that you've defined

I guess I wonder if it's worth it to have marginally more convenient ways to build protos.
</blockquote></details>

I am actually expecting that we may want to expand our usage of `internal`/`associates`. There are places I've seen where something would have been declared package-private if it were written in Java instead of Kotlin. Similarly, the type-safe builder and `@DslMarker` concepts may be used elsewhere in the codebase in the future.

Therefore, this isn't about convenience for building protos specifically.


<!-- Sent from Reviewable.io -->

2021-08-10 21:29 UTC, efoxepstein requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/188)* status: all files reviewed, 1 unresolved discussion (waiting on @corbantek, @oliver-amzn, @SanjayVas, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/BUILD.bazel, line 19 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/188#-MgkysG5AFbU3Od_aPGq:-MglxGvx7f2ALXFJ5X-p:bge9eor) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/467b3d17b18b30a0e4d414d64bb26d9689b3a280/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/BUILD.bazel#L19)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I am actually expecting that we may want to expand our usage of `internal`/`associates`. There are places I've seen where something would have been declared package-private if it were written in Java instead of Kotlin. Similarly, the type-safe builder and `@DslMarker` concepts may be used elsewhere in the codebase in the future.

Therefore, this isn't about convenience for building protos specifically.
</blockquote></details>

OOC, why do we bother with separate kt_jvm_libraries in this package? `v2alpha_public_api_server` is the only non-test target that uses any of them and it pulls them all in. Regardless of usage of `associates` elsewhere, I feel like it'd be simpler here to just have a single `v2alpha` rule that globs all the kt files.


<!-- Sent from Reviewable.io -->

2021-08-10 22:02 UTC, SanjayVas reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/188)* status: all files reviewed, 1 unresolved discussion (waiting on @corbantek, @efoxepstein, @oliver-amzn, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/BUILD.bazel, line 19 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/188#-MgkysG5AFbU3Od_aPGq:-Mgm-rmV-zWzf8r-ZEj5:b-vcu794) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/467b3d17b18b30a0e4d414d64bb26d9689b3a280/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/BUILD.bazel#L19)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

OOC, why do we bother with separate kt_jvm_libraries in this package? `v2alpha_public_api_server` is the only non-test target that uses any of them and it pulls them all in. Regardless of usage of `associates` elsewhere, I feel like it'd be simpler here to just have a single `v2alpha` rule that globs all the kt files.
</blockquote></details>

1. Granular targets are preferred over globbing everything in a package to keep the deps minimal when there's a chance they'll be used separately. The main reason to previously advocate globbing for Kotlin was because of the `internal` vs. package-private problem IMO. It'd be better if we had tooling to help manage deps (e.g. unused_deps for Java), and it's possible we might get that eventually (e.g. now that rules_kotlin has things like [strict dependency enforcement](https://github.com/bazelbuild/rules_kotlin/pull/438).
2. Originally, the architecture had separate Server targets. That said, the test targets are still separate.


<!-- Sent from Reviewable.io -->

2021-08-10 22:10 UTC, efoxepstein requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/188)* status: all files reviewed, 1 unresolved discussion (waiting on @corbantek, @oliver-amzn, @SanjayVas, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/BUILD.bazel, line 19 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/188#-MgkysG5AFbU3Od_aPGq:-Mgm4g5W1ZOVHnBIyzla:bol6eyr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/467b3d17b18b30a0e4d414d64bb26d9689b3a280/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/BUILD.bazel#L19)):*
> when there's a chance

YAGNI

> test targets

This doesn't really count as usage, I don't think.

Here's my philosophical argument for combining them: this package provides (or will provide) a complete implementation of the v2alpha API. That is a singular, atomic Thing-with-a-capital-T that needn't be parceled out into whatever services it happens to consist of.

My practical argument is that since we're still actively developing this code, it makes refactoring easier and reduces the amount of boilerplate to combine them.


<!-- Sent from Reviewable.io -->

2021-08-19 23:25 UTC, efoxepstein reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/188)* status: all files reviewed, 2 unresolved discussions (waiting on @SanjayVas)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/188#-MhVj-2R5oBowlGJqos6:-MhVj-2S-RI0AqQPcBJX:b-8dwq1c) (no related file):*
Should this be closed?

---


<!-- Sent from Reviewable.io -->

2021-08-23 15:11 UTC, SanjayVas commented
Obsoleted by kt_jvm_proto_library.

2021-08-23 15:11 UTC, closed without merging