Implement population requisition fulfiller test in InProcessLifeOfAMeasurementIntegrationTest.
world-federation-of-advertisers/cross-media-measurement pull request #1911
Opened 2024-11-12 18:53 UTC by jojijac0b

Implement population requisition fulfiller test in InProcessLifeOfAMeasurementIntegrationTest.

2024-11-12 18:53 UTC, wfa-reviewable commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1911)
<!-- Reviewable:end -->

2024-11-12 21:51 UTC, SanjayVas requested changes
I took the liberty of updating the PR description to follow https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/docs/dev-standards.md#pull-request-description. In particular:

1. Following Conventional Commits
2. Removing duplication of PR title in commit body

> Reviewed 7 of 19 files at r1, 1 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1911#-:-OBWw0xF7Jfj3kWJIPZn:bk87t82)* status: 7 of 20 files reviewed, 11 unresolved discussions (waiting on @jojijac0b and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/measurementconsumer/MeasurementConsumerSimulator.kt` line 181 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1911#-OBX4HKy7MZE_aDdoYpX:-OBX4HKy7MZE_aDdoYpY:b1ee3y) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c9e689fd3b11390a046562c99a117e65f9898a78/src/main/kotlin/org/wfanet/measurement/loadtest/measurementconsumer/MeasurementConsumerSimulator.kt#L181)):*
> ```Kotlin
>     val measurementSpec: MeasurementSpec,
>     val requisitions: List<RequisitionInfo>,
>     val populationInfo: PopulationInfo,
> ```

This is info for any specific Measurement. This is implying all Measurements will have a PopulationInfo and need a TypeRegistry, and furthermore that different Measurements will have different values for these. Is this true?

If this is only true for population measurements, then you may want to have a PopulationMeasurementInfo that either inherits from or composes a MeasurementInfo.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/measurementconsumer/MeasurementConsumerSimulator.kt` line 1260 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1911#-OBX75vL3fKbEX8zqRK6:-OBX75vL3fKbEX8zqRK7:by0o8hp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c9e689fd3b11390a046562c99a117e65f9898a78/src/main/kotlin/org/wfanet/measurement/loadtest/measurementconsumer/MeasurementConsumerSimulator.kt#L1260)):*
> ```Kotlin
>   private suspend fun buildRequisitionInfo(
>     dataProvider: DataProvider,
>     eventGroups: List<EventGroup>,
> ```

Population requisitions will not have event groups. Just have two separate methods.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/measurementconsumer/MeasurementConsumerSimulator.kt` line 1352 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1911#-OBX7cneBKoicY2-Gz4-:-OBX7cneBKoicY2-Gz40:b-qj2ru3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c9e689fd3b11390a046562c99a117e65f9898a78/src/main/kotlin/org/wfanet/measurement/loadtest/measurementconsumer/MeasurementConsumerSimulator.kt#L1352)):*
> ```Kotlin
> 
>     private val DEFAULT_POPULATION_DATA = PopulationData(
>       populationDataProviderName = "dataProviders/AAAAAAAAAHs",
> ```

I don't think this can be true for any MeasurementSimulator instance since the class is only used in integration tests with a real random ID generator.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetup.kt` line 72 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1911#-OBX84p50k0Gn_we7MIk:-OBX84p50k0Gn_we7MIl:bptn1q5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c9e689fd3b11390a046562c99a117e65f9898a78/src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetup.kt#L72)):*
> ```Kotlin
> import java.time.Instant
> import org.wfanet.measurement.common.toProtoTime
> import org.wfanet.measurement.internal.kingdom.DataProvider
> ```

This is already imported with the alias `InternalDataProvider`. Note that any code that deals with both the internal and public APIs will use import aliases for internal API symbols.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetup.kt` line 208 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1911#-OBXAfcnEQZLb7t8-j1W:-OBX9fBS65WcCCL97j9X:b-22w37j) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c9e689fd3b11390a046562c99a117e65f9898a78/src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetup.kt#L208)):*
> ```Kotlin
>       )
>     }
> ```

FYI you'll eventually want to create the resources needed for population measurements here for including it in the K8s correctness test in addition to the in-process integration test.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetup.kt` line 313 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1911#-OBX8nHh1ZdNnmh-MuYy:-OBX8nHh1ZdNnmh-MuYz:b1p2em3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c9e689fd3b11390a046562c99a117e65f9898a78/src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetup.kt#L313)):*
> ```Kotlin
> 
>   /** Create a modelSuite. */
>   suspend fun createModelSuite(modelProvider: ModelProvider): org.wfanet.measurement.internal.kingdom.ModelSuite {
> ```

This class should call the public API when possible. It only calls internal API for cases where resource creation is not self-service and would be handled by the Kingdom operator.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/MeasurementResults.kt` line 67 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1911#-OBX2nbT6Yp25Y7dkaJw:-OBX2nbU7c71eZDRuFzX:b-4gjplp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c9e689fd3b11390a046562c99a117e65f9898a78/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/MeasurementResults.kt#L67)):*
> ```Kotlin
>   /** Computes population using the "deterministic count" methodology. */
>   fun computePopulation(populationInfo: PopulationInfo, program: Program, typeRegistry: TypeRegistry): Long {
>     return PopulationRequisitionFulfiller.computePopulation(populationInfo, program, typeRegistry)
> ```

Invert this; move the functionality here and call it from PopulationRequisiionFulfiller.
___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/Configs.kt` line 43 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1911#-OBWwWut7pk-q9OkmmB0:-OBWwWut7pk-q9OkmmB1:b40s2px) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c9e689fd3b11390a046562c99a117e65f9898a78/src/main/kotlin/org/wfanet/measurement/integration/common/Configs.kt#L43)):*
> ```Kotlin
> import org.wfanet.measurement.common.getRuntimePath
> import org.wfanet.measurement.common.pack
> //import org.wfanet.measurement.common.pack
> ```

Remove commented-out code
___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/Configs.kt` line 178 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1911#-OBWwbofBI6Quwh6nNLA:-OBWwbofBI6Quwh6nNLB:befptsq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c9e689fd3b11390a046562c99a117e65f9898a78/src/main/kotlin/org/wfanet/measurement/integration/common/Configs.kt#L178)):*
> ```Kotlin
> 
> /** Builds a PopulationInfo used by PopulationRequisitionFulfiller. */
> @Blocking
> ```

Does this actually make any blocking calls, e.g. filesystem I/O?



_Code quote:_
```Kotlin
@Blocking
```
___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/Configs.kt` line 179 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1911#-OBWwxKsDJj-JLT5AlL7:-OBWwxKt9MbTpnDWR7U_:b592b2z) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c9e689fd3b11390a046562 [...]

2024-11-14 15:53 UTC, stevenwarejones reviewed
> Reviewed 1 of 19 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1911)* status: 8 of 20 files reviewed, 11 unresolved discussions (waiting on @jojijac0b and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetup.kt` line 313 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1911#-OBX8nHh1ZdNnmh-MuYy:-OBfN-AD-atvKxQxrOcJ:b-selvj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c9e689fd3b11390a046562c99a117e65f9898a78/src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetup.kt#L313)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This class should call the public API when possible. It only calls internal API for cases where resource creation is not self-service and would be handled by the Kingdom operator.
</blockquote></details>

@SanjayVas - I agree with you, but imo, to do this correctly, Joji would need to create a ModelProviderSimulator that creates the necessary resources. In order to keep the PRs small-ish, I'd prefer he add TODOs here and code that as an immediate follow-up after this merges. Wdyt?


<!-- Sent from Reviewable.io -->

2024-11-14 16:50 UTC, jojijac0b reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1911)* status: 6 of 21 files reviewed, 11 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/Configs.kt` line 43 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1911#-OBWwWut7pk-q9OkmmB0:-OBfWcLt31Nuh1Qir-3Y:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c9e689fd3b11390a046562c99a117e65f9898a78/src/main/kotlin/org/wfanet/measurement/integration/common/Configs.kt#L43)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Remove commented-out code
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/Configs.kt` line 178 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1911#-OBWwbofBI6Quwh6nNLA:-OBfWimN4kIgOZ1phrWy:byz0apx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c9e689fd3b11390a046562c99a117e65f9898a78/src/main/kotlin/org/wfanet/measurement/integration/common/Configs.kt#L178)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Does this actually make any blocking calls, e.g. filesystem I/O?
</blockquote></details>

Done. Removed Function in favor of using synthetic_population_spec_large.textproto
___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/Configs.kt` line 179 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1911#-OBWwxKsDJj-JLT5AlL7:-OBfWr-02kl2MCY632Q6:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c9e689fd3b11390a046562c99a117e65f9898a78/src/main/kotlin/org/wfanet/measurement/integration/common/Configs.kt#L179)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Why not use an existing test population such as https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/main/k8s/testing/data/synthetic_population_spec_large.textproto?
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/Configs.kt` line 238 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1911#-OBWwlbQ1oblVxw7Kyem:-OBfWrog3t5ANa1Uja2r:bo2c12) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c9e689fd3b11390a046562c99a117e65f9898a78/src/main/kotlin/org/wfanet/measurement/integration/common/Configs.kt#L238)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Same here
</blockquote></details>

Done. Removed function in favor of using TypeRegistry.newBuilder().add(listOf(Person.getDescriptor(), Dummy.getDescriptor())).build()
___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/Configs.kt` line 239 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1911#-OBX0PszAdkOOHjC9yst:-OBfXWTE6ubk3IV016ho:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c9e689fd3b11390a046562c99a117e65f9898a78/src/main/kotlin/org/wfanet/measurement/integration/common/Configs.kt#L239)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I don't think this function belongs here since it's not specifically related to test configs for integration tests. It's also trivial to write, and is furthermore more idiomatically written as 

```kotlin
TypeRegistry.newBuilder().add(descriptorList).build()
```

Since there's already an `add` overload for `Iterable<Descriptors.Descriptor>`.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/MeasurementResults.kt` line 67 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1911#-OBX2nbT6Yp25Y7dkaJw:-OBfWAnt0t3uiA9Cnvgb:b9ujudn) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c9e689fd3b11390a046562c99a117e65f9898a78/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/MeasurementResults.kt#L67)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Invert this; move the functionality here and call it from PopulationRequisiionFulfiller.
</blockquote></details>

Is this possible? Because MeasurementResults is in a test only package while PopulationRequisitionFulfiller is not.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/measurementconsumer/MeasurementConsumerSimulator.kt` line 181 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1911#-OBX4HKy7MZE_aDdoYpX:-OBfXoYyB_Bd1YH9-aCs:b-3pgovb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c9e689fd3b11390a046562c99a117e65f9898a78/src/main/kotlin/org/wfanet/measurement/loadtest/measurementconsumer/MeasurementConsumerSimulator.kt#L181)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This is info for any specific Measurement. This is implying all Measurements will have a PopulationInfo and need a TypeRegistry, and furthermore that different Measurements will have different values for these. Is this true?

If this is only true for population measurements, then you may want to have a PopulationMeasurementInfo that either inherits from or composes a MeasurementInfo.
</blockquote></details>

Done. Created PopulationMeasurementInfo which contains population measurement specific fields along with MeasurementInfo
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/measurementconsumer/MeasurementConsumerSimulator.kt` line 1260 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1911#-OBX75vL3fKbEX8zqRK6:-OBfXzk_92BdjZTbTYwj:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c9e689fd3b11390a046562c99a117e65f9898a78/src/main/kotlin/org/wfanet/measurement/loadtest/measurementconsumer/MeasurementConsumerSimulator.kt#L1260)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Population requisitions will not have event groups. Just have two separate methods.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/measurementconsumer/MeasurementConsumerSimulator.kt` line 1352 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1911#-OBX7cneBKoicY2-Gz4-:-OBfY0-Q3y2LS0jQ8YCc:bs7wumx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c9e689fd3b11390a046562c99a117e65f9898a78/src/main/kotlin/org/wfanet/measurement/loadtest/measurementconsumer/MeasurementConsumerSimulator.kt#L1352)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I don't think this can be true for any MeasurementSimulator instance since the class is only used in integration tests with a real random ID generator.
</blockquote></details>

Done. 
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetup.kt` line 72 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1911#-OBX84p50k0Gn_we7MIk:-OBfY8aJ1zpCM4OuUdo7:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c9e689fd3b11390a046562c99a117e65f9898a78/src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetup.kt#L72)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This is already imported with the alias `InternalDataProvider`. Note that any code [...]

2024-11-14 18:18 UTC, stevenwarejones reviewed
> Reviewed 4 of 19 files at r1, 5 of 7 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1911)* status: 14 of 21 files reviewed, 11 unresolved discussions (waiting on @SanjayVas)



<!-- Sent from Reviewable.io -->

2024-11-14 23:50 UTC, stevenwarejones reviewed
> Reviewed 4 of 19 files at r1, 2 of 5 files at r2, 1 of 3 files at r5, 1 of 7 files at r7.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1911)* status: 20 of 21 files reviewed, 3 unresolved discussions (waiting on @jojijac0b and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetup.kt` line 313 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1911#-OBX8nHh1ZdNnmh-MuYy:-OBh4UObApASmLOEgUrq:b-a4fbk6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c9e689fd3b11390a046562c99a117e65f9898a78/src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetup.kt#L313)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The point is that this class is only intended to create the minimal set of resources necessary to bootstrap the Kingdom. That is to say just what's needed for the Kingdom config files. I believe that's just creating the ModelProvider so that it can be entered in `authority_key_identifier_to_principal_map.textproto`.

> Joji would need to create a ModelProviderSimulator that creates the necessary resources

I'm not certain that's the right approach at the moment. I think that the test method itself can just create the child model resources, since those don't have uniqueness issues like ModelProvider which needs to have a unique root certificate ID.
</blockquote></details>

so, you're fine with the test itself creating the resources using the internal api?
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateModelSuite.kt` line 36 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1911#-OBh3yLM2QTtRpFRGJbq:-OBh3yLM2QTtRpFRGJbr:b-l6mwxj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e47ecf94e7f8dca691f424d642d64bbefd5c94f0/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateModelSuite.kt#L36)):*
> ```Kotlin
>     val modelProviderId: InternalId =
>       readModelProviderId(ExternalId(modelSuite.externalModelProviderId))
>     println("JOJI IN CREATE MODEL SUITE $modelProviderId")
> ```

remove


<!-- Sent from Reviewable.io -->

2024-11-15 00:00 UTC, SanjayVas requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1911)* status: 20 of 21 files reviewed, 3 unresolved discussions (waiting on @jojijac0b and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetup.kt` line 313 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1911#-OBX8nHh1ZdNnmh-MuYy:-OBh6B8z7VK3kboR5RrE:bhafwcd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c9e689fd3b11390a046562c99a117e65f9898a78/src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetup.kt#L313)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

so, you're fine with the test itself creating the resources using the internal api?
</blockquote></details>

No, that should use the public API.

To summarize:

1. Only create the ModelProvider in ResourceSetup
2. Create anything else needed in the test using the public API


<!-- Sent from Reviewable.io -->

2024-11-15 22:36 UTC, jojijac0b reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1911)* status: 15 of 21 files reviewed, 3 unresolved discussions (waiting on @SanjayVas and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/measurementconsumer/MeasurementConsumerSimulator.kt` line 1352 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1911#-OBX7cneBKoicY2-Gz4-:-OBlx8SX-pWPesJvVoij:b3qp6v9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c9e689fd3b11390a046562c99a117e65f9898a78/src/main/kotlin/org/wfanet/measurement/loadtest/measurementconsumer/MeasurementConsumerSimulator.kt#L1352)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Sorry, what I'm saying is you cannot have a default PopulationData here since it cannot be valid. PopulationData instances can only exist once you have known resources created. What this means is that the constructor parameter has to be required with no default.
</blockquote></details>

Removed as it is no loner needed. PopulationData will be passed to the testPopulation() method.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetup.kt` line 313 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1911#-OBX8nHh1ZdNnmh-MuYy:-OBlxIS-8a3dC3ipbfrC:b-bw1bzk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c9e689fd3b11390a046562c99a117e65f9898a78/src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetup.kt#L313)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

No, that should use the public API.

To summarize:

1. Only create the ModelProvider in ResourceSetup
2. Create anything else needed in the test using the public API
</blockquote></details>

Done. ModelSuite, ModelRelease, ModelRollout, and ModelLine resources are now created in the InProcessLifeOfAMeasurement population test. ModelProvider and Population are created in InProcessCmmsComponents. Population is created there because it will be passed to InProcessPopulationRequisitionFulfiller. The same population is used in the population test in InProcessLifeOfAMeasurement


<!-- Sent from Reviewable.io -->

2024-11-15 22:36 UTC, jojijac0b reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1911)* status: 15 of 21 files reviewed, 3 unresolved discussions (waiting on @SanjayVas and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateModelSuite.kt` line 36 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1911#-OBh3yLM2QTtRpFRGJbq:-OBly9gl4b4hVSYbiohH:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e47ecf94e7f8dca691f424d642d64bbefd5c94f0/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateModelSuite.kt#L36)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

remove
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-11-18 16:20 UTC, stevenwarejones reviewed
> Reviewed 3 of 7 files at r8, 8 of 11 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1911)* status: 18 of 21 files reviewed, 2 unresolved discussions (waiting on @SanjayVas)



<!-- Sent from Reviewable.io -->

2024-11-18 20:48 UTC, SanjayVas requested changes
> Reviewed 1 of 19 files at r1, 1 of 5 files at r2, 3 of 7 files at r8, 11 of 11 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1911)* status: all files reviewed, 12 unresolved discussions (waiting on @jojijac0b)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt` line 741 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1911#-OC-zZP0DcAZrPg1-mnr:-OC-zZP0DcAZrPg1-mns:b411kvl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/559edde30601fd0625e06c5683827c312acdb5db/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt#L741)):*
> ```Kotlin
>       }
>     }
>     if (source.rolloutFreezeTime !== Timestamp.getDefaultInstance()) {
> ```

Use protobuf message field presence



_Suggestion:_
```Kotlin
!source.hasRolloutFreezeTime()
```
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt` line 814 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1911#-OC-zsTj2pEIA06gHBho:-OC-zsTj2pEIA06gHBhp:b411kvl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/559edde30601fd0625e06c5683827c312acdb5db/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt#L814)):*
> ```Kotlin
>     }
> 
>     if (publicModelRollout.rolloutFreezeDate !== Date.getDefaultInstance()) {
> ```

Use protobuf message field presence



_Suggestion:_
```Kotlin
!publicModelRollout.hasRolloutFreezeDate()
```
___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/InProcessPopulationRequisitionFulfiller.kt` line 96 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1911#-OC-z5--8s9QGNQqxuT6:-OC-z5--8s9QGNQqxuT7:b-3ov07p) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/559edde30601fd0625e06c5683827c312acdb5db/src/main/kotlin/org/wfanet/measurement/integration/common/InProcessPopulationRequisitionFulfiller.kt#L96)):*
> ```Kotlin
>   }
> 
>   private val internalCertificatesClient by lazy {
> ```

Don't rebuild clients here that you can just expose from InProcessKingdom.
___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/InProcessPopulationRequisitionFulfiller.kt` line 117 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1911#-OC-ynOw7ONwhqzUGuds:-OC-yjtN3zZ2Q_0Y6RUZ:b-ql4712) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/559edde30601fd0625e06c5683827c312acdb5db/src/main/kotlin/org/wfanet/measurement/integration/common/InProcessPopulationRequisitionFulfiller.kt#L117)):*
> ```Kotlin
>   }
> 
>   private val internalDataServer =
> ```

These servers are already built as part of InProcessKingdom. The relevant gRPC channels are exposed from that.
___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/InProcessLifeOfAMeasurementIntegrationTest.kt` line 123 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1911#-OC-yGv265eORu6UF7GI:-OC-yGv265eORu6UF7GJ:bfva5as) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/559edde30601fd0625e06c5683827c312acdb5db/src/main/kotlin/org/wfanet/measurement/integration/common/InProcessLifeOfAMeasurementIntegrationTest.kt#L123)):*
> ```Kotlin
>   private lateinit var modelProviderName: String
> 
>   private lateinit var populationDataProviderName: String
> ```

You don't need lateinit vars for these since they can be directly accessed from `inProcessCmmsComponents`.



_Code quote:_
```Kotlin
  private lateinit var modelProviderName: String

  private lateinit var populationDataProviderName: String
```
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/BUILD.bazel` line 108 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1911#-OC0-HPQ1XxZF_Z4czhX:-OC0-HPQ1XxZF_Z4czhY:bmsmyhd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/559edde30601fd0625e06c5683827c312acdb5db/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/BUILD.bazel#L108)):*
> ```Starlark
>     deps = [
>         "//src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration:event_filters",
>         "//src/main/proto/wfa/measurement/api/v2alpha:population_spec_kt_jvm_proto",
> ```

I don't see these deps used. What you do need are the deps that contain TypeRegistry and CEL program.



_Code quote:_
```Starlark
        "//src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration:event_filters",
        "//src/main/proto/wfa/measurement/api/v2alpha:population_spec_kt_jvm_proto",
```
___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/InProcessCmmsComponents.kt` line 170 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1911#-OC-vt2kBARgRBrjGzcS:-OC-vt2kBARgRBrjGzcT:bx36l3x) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/559edde30601fd0625e06c5683827c312acdb5db/src/main/kotlin/org/wfanet/measurement/integration/common/InProcessCmmsComponents.kt#L170)):*
> ```Kotlin
>   private lateinit var populationKey: PopulationKey
>   private lateinit var populationInfo: PopulationInfo
>   private lateinit var populationInfoMap: Map<PopulationKey, PopulationInfo>
> ```

Why do we have a map if we also have a single key and info?
___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/InProcessCmmsComponents.kt` line 172 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1911#-OC-w2Gw5ivtKLUrb5bw:-OC-w2Gw5ivtKLUrb5bx:b-uh8odp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/559edde30601fd0625e06c5683827c312acdb5db/src/main/kotlin/org/wfanet/measurement/integration/common/InProcessCmmsComponents.kt#L172)):*
> ```Kotlin
>   private lateinit var populationInfoMap: Map<PopulationKey, PopulationInfo>
>   private lateinit var typeRegistry: TypeRegistry
>   private lateinit var internalModelProviderName: String
> ```

This is a resource name. See below comment about properties for using this as an explicit backing field (hence why it has an underscore)



_Suggestion:_
```Kotlin
_modelProviderResourceName
```
___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/InProcessCmmsComponents.kt` line 246 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1911#-OC-vd87DjE2VxjPDYwg:-OC-vd87DjE2VxjPDYwh:bemk36z) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/559edde30601fd0625e06c5683827c312acdb5db/src/main/kotlin/org/wfanet/measurement/integration/common/InProcessCmmsComponents.kt#L246)):*
> ```Kotlin
>     val population = resourceSetup.createInternalPopulation(internalDataProvider)
>     populationKey =
>       PopulationKey.fromName(population.toPopulation().name) ?: PopulationKey.defaultValue
> ```

It would be an error for this to be null since our own code created it.



_Suggestion:_
```Kotlin
PopulationKey.fromName(population.toPopulation().name)!!
```
___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/InProcessCmmsComponents.kt` line 289 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1911#-OC-wOUq7DjRNbhN5jXl:-OC-wOUq7DjRNbhN5jXm:b-wzb4lr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/559edde30601fd0625e06c5683827c312acdb5db/src/main/kotlin/org/wfanet/measurement/integration/common/InProcessCmmsComponents.kt#L289)):*
> ```Kotlin
>   fun getModelProviderName(): String {
>     return internalModelProviderName
>   [...]

2024-11-19 19:40 UTC, jojijac0b reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1911)* status: 14 of 21 files reviewed, 11 unresolved discussions (waiting on @SanjayVas and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/InProcessCmmsComponents.kt` line 170 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1911#-OC-vt2kBARgRBrjGzcS:-OC4eFFQBQcwQQVhIbno:b-bij47t) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/559edde30601fd0625e06c5683827c312acdb5db/src/main/kotlin/org/wfanet/measurement/integration/common/InProcessCmmsComponents.kt#L170)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Why do we have a map if we also have a single key and info?
</blockquote></details>

We need a map to pass to the InProcessPopulationRequisitionFulfiller. Made a change to delete the populationInfoMap variable and create the map when InProcessPopulationRequisitionFulfiller in initialized 
___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/InProcessCmmsComponents.kt` line 172 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1911#-OC-w2Gw5ivtKLUrb5bw:-OC4IHaf23wk1lGgi8ch:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/559edde30601fd0625e06c5683827c312acdb5db/src/main/kotlin/org/wfanet/measurement/integration/common/InProcessCmmsComponents.kt#L172)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This is a resource name. See below comment about properties for using this as an explicit backing field (hence why it has an underscore)
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/InProcessCmmsComponents.kt` line 246 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1911#-OC-vd87DjE2VxjPDYwg:-OC4MPKg2cEUOn-j8Gh7:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/559edde30601fd0625e06c5683827c312acdb5db/src/main/kotlin/org/wfanet/measurement/integration/common/InProcessCmmsComponents.kt#L246)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

It would be an error for this to be null since our own code created it.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/InProcessCmmsComponents.kt` line 289 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1911#-OC-wOUq7DjRNbhN5jXl:-OC4IJG33G53vQciv9c4:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/559edde30601fd0625e06c5683827c312acdb5db/src/main/kotlin/org/wfanet/measurement/integration/common/InProcessCmmsComponents.kt#L289)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Have these be properties rather than accessor functions
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/InProcessLifeOfAMeasurementIntegrationTest.kt` line 123 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1911#-OC-yGv265eORu6UF7GI:-OC4dOxH3-2gpAe1MeVH:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/559edde30601fd0625e06c5683827c312acdb5db/src/main/kotlin/org/wfanet/measurement/integration/common/InProcessLifeOfAMeasurementIntegrationTest.kt#L123)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

You don't need lateinit vars for these since they can be directly accessed from `inProcessCmmsComponents`.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/InProcessPopulationRequisitionFulfiller.kt` line 96 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1911#-OC-z5--8s9QGNQqxuT6:-OC4IKrOAdmiyEOS6mN3:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/559edde30601fd0625e06c5683827c312acdb5db/src/main/kotlin/org/wfanet/measurement/integration/common/InProcessPopulationRequisitionFulfiller.kt#L96)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Don't rebuild clients here that you can just expose from InProcessKingdom.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/InProcessPopulationRequisitionFulfiller.kt` line 117 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1911#-OC-ynOw7ONwhqzUGuds:-OC4ILfL1m5j8LBxywq8:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/559edde30601fd0625e06c5683827c312acdb5db/src/main/kotlin/org/wfanet/measurement/integration/common/InProcessPopulationRequisitionFulfiller.kt#L117)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

These servers are already built as part of InProcessKingdom. The relevant gRPC channels are exposed from that.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt` line 741 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1911#-OC-zZP0DcAZrPg1-mnr:-OC4IlVJEoToytZH2pHz:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/559edde30601fd0625e06c5683827c312acdb5db/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt#L741)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Use protobuf message field presence
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt` line 814 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1911#-OC-zsTj2pEIA06gHBho:-OC4Ik_VApq3RJo05Y_f:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/559edde30601fd0625e06c5683827c312acdb5db/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt#L814)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Use protobuf message field presence
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/BUILD.bazel` line 108 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1911#-OC0-HPQ1XxZF_Z4czhX:-OC4LvMG2n7LLg_f8Iae:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/559edde30601fd0625e06c5683827c312acdb5db/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/BUILD.bazel#L108)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I don't see these deps used. What you do need are the deps that contain TypeRegistry and CEL program.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 192 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1911#-OC0-rQG8RIleCO5yT-V:-OC4MB4iA84uTbv3Hbrr:b7t85zg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/559edde30601fd0625e06c5683827c312acdb5db/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L192)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I don't see how this could be used, since it's private and not referenced in this file.
</blo [...]

2024-11-19 20:40 UTC, SanjayVas requested changes
> Reviewed 7 of 7 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1911)* status: all files reviewed, 2 unresolved discussions (waiting on @jojijac0b)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 192 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1911#-OC0-rQG8RIleCO5yT-V:-OC58ep2AHdDQOLad8st:b-kbr1wi) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/559edde30601fd0625e06c5683827c312acdb5db/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L192)):*
<details><summary><i>Previously, jojijac0b wrote…</i></summary><blockquote>

It's used to filter through requisitions in the executeRequisitionFulfillingWorkflow() method.
</blockquote></details>

It's not though. That function doesn't reference this property, and instead creates its own MeasurementKey.
___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/InProcessCmmsComponents.kt` line 257 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1911#-OC583Hc6ANTWIDtErjZ:-OC583Hd--gFILa_XuKC:b6i8cxt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9da6f4d6c4ab59c15a695ec4f92abdb450209c3c/src/main/kotlin/org/wfanet/measurement/integration/common/InProcessCmmsComponents.kt#L257)):*
> ```Kotlin
>   }
> 
>   fun getTypeRegistry(): TypeRegistry {
> ```

nit: same here re: having this be a property


<!-- Sent from Reviewable.io -->

2024-11-20 16:17 UTC, jojijac0b reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1911)* status: 19 of 21 files reviewed, 2 unresolved discussions (waiting on @SanjayVas and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 192 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1911#-OC0-rQG8RIleCO5yT-V:-OC9L3w49oIwrlwoj5ej:b-32pjdu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/559edde30601fd0625e06c5683827c312acdb5db/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L192)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

It's not though. That function doesn't reference this property, and instead creates its own MeasurementKey.
</blockquote></details>

See comment below
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 556 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1911#-OC9KOAI3oJkggwe2bI5:-OC9KOAI3oJkggwe2bI6:b-w42wu5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9da6f4d6c4ab59c15a695ec4f92abdb450209c3c/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L556)):*
> ```Kotlin
>       getRequisitions().filter {
>         checkNotNull(MeasurementKey.fromName(it.measurement)).measurementConsumerId ==
>           measurementConsumerKey.measurementConsumerId
> ```

measurementConsumerKey that is created above is used here


<!-- Sent from Reviewable.io -->

2024-11-20 18:22 UTC, SanjayVas approved these changes
> Reviewed 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1911)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 192 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1911#-OC0-rQG8RIleCO5yT-V:-OC9nqW-5Vnr8-fs8G7P:bsyx9lw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/559edde30601fd0625e06c5683827c312acdb5db/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L192)):*
<details><summary><i>Previously, jojijac0b wrote…</i></summary><blockquote>

See comment below
</blockquote></details>

Oh I see what it is. This was moved from the base class. That's why it didn't appear in my diff.


<!-- Sent from Reviewable.io -->

2024-11-21 18:04 UTC, stevenwarejones approved these changes
> Reviewed 1 of 11 files at r9, 1 of 7 files at r10, 1 of 2 files at r11, 4 of 8 files at r12, 4 of 4 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1911)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)



<!-- Sent from Reviewable.io -->

2024-11-21 19:04 UTC, merged