fix: Read all EventGroups from MC simulator rather than stopping at first page
world-federation-of-advertisers/cross-media-measurement pull request #1927
Opened 2024-11-18 22:43 UTC by SanjayVas

The MC simulator was only reading the first page of results from ListEventGroups. This means that in environments with more EventGroups, not all test EventGroups would be read. This is exacerbated by #1916, as the default page size is now smaller.

2024-11-18 22:43 UTC, wfa-reviewable commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1927)
<!-- Reviewable:end -->

2024-11-18 22:44 UTC, SanjayVas commented
Depends on #1923

2024-11-19 14:31 UTC, stevenwarejones requested changes
> Reviewed 2 of 6 files at r1, 2 of 14 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1927)* status: 4 of 20 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/common/api/grpc/ListResources.kt` line 67 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1927#-OC3pBLUDUOEi6JDTKqQ:-OC3pBLUDUOEi6JDTKqR:b-nwr0p5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c21917ab186cc0ce408a120a77099f7985a89b5b/src/main/kotlin/org/wfanet/measurement/common/api/grpc/ListResources.kt#L67)):*
> ```Kotlin
> 
>       val resourceList: ResourceList<T> = list(nextPageToken, remaining)
>       require(resourceList.size <= remaining) {
> ```

should this really be required here and throw an error? this is a problem with the list that is passed in..... meaning an API that returned too many items. I'd prefer it took only that many elements if there are too many.


<!-- Sent from Reviewable.io -->

2024-11-19 18:01 UTC, SanjayVas reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1927)* status: 4 of 20 files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/common/api/grpc/ListResources.kt` line 67 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1927#-OC3pBLUDUOEi6JDTKqQ:-OC4_O9_EgKabkuugWB9:b-2k5n61) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c21917ab186cc0ce408a120a77099f7985a89b5b/src/main/kotlin/org/wfanet/measurement/common/api/grpc/ListResources.kt#L67)):*
> I'd prefer it took only that many elements if there are too many.

That wouldn't work, as the returned next page token wouldn't have the right value to get subsequent items.


<!-- Sent from Reviewable.io -->

2024-11-21 22:03 UTC, SanjayVas reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1927)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 369 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1927#-OCFcJza0hDKXt55msMK:-OCFiwSjC2EiB5wNNF4q:b-v2b7vv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/673ba6f900a0762cd007f46e34efc83e9e1d6efa/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L369)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

I'd prefer you prefilter instead of unncessarily fetching all event groups.... something like 

```
eturn eventGroupsStub
      .listResources(
          limit = 1
) { pageToken ->
        val response =
          try {
            listEventGroups(
              listEventGroupsRequest {
                parent = edpData.name
                filter =
                  ListEventGroupsRequestKt.filter {
                    measurementConsumers += measurementConsumerName
                  }
                this.pageToken = pageToken
              }
            )
          } catch (e: StatusException) {
            throw Exception("Error listing EventGroups", e)
          }
        ResourceList(
response.eventGroupsList.filter { it.eventGroupReferenceId == eventGroupReferenceId }, 
response.nextPageToken
)
      }
      .flattenConcat()
```

</blockquote></details>

That would be less efficient as it means making a call for one EventGroup at a time rather than batching by the default page size. This will still stop making calls once we get a response that contains the event group.


<!-- Sent from Reviewable.io -->

2024-11-21 23:52 UTC, SanjayVas reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1927)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 369 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1927#-OCFcJza0hDKXt55msMK:-OCG4dhH1ghMh7w9fp92:b8lj1jv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e026654bcd7035f642145036ef15edd67b76505b/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L369)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

That would be less efficient as it means making a call for one EventGroup at a time rather than batching by the default page size. This will still stop making calls once we get a response that contains the event group.
</blockquote></details>

To clarify, what I mean is that the implementation in this PR will already stop making requests once it gets a response that has an EventGroup that has the specified reference ID. This is because `Flow.flattenConcat` is an *intermediate* Flow operator analogous to [`Sequence.flatten`](https://kotlinlang.org/api/core/kotlin-stdlib/kotlin.sequences/flatten.html).

Your suggestion does not add any benefit and furthermore does not meet the constraint of never returning more items than `limit` since EventGroup reference IDs are not yet guaranteed to be unique (see #1913). In order to meet that constraint, it would have to pass the `remaining` value as the `pageSize` in the request resulting in the non-batching behavior I mentioned.


<!-- Sent from Reviewable.io -->

2024-11-22 16:44 UTC, stevenwarejones approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1927)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 369 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1927#-OCFcJza0hDKXt55msMK:-OCJjuy77oB7YcQaIJRb:bk5wxjg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7b4e9220c88e41a373478eeca1cbbfae6e80008a/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L369)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

To clarify, what I mean is that the implementation in this PR will already stop making requests once it gets a response that has an EventGroup that has the specified reference ID. This is because `Flow.flattenConcat` is an *intermediate* Flow operator analogous to [`Sequence.flatten`](https://kotlinlang.org/api/core/kotlin-stdlib/kotlin.sequences/flatten.html).

Your suggestion does not add any benefit and furthermore does not meet the constraint of never returning more items than `limit` since EventGroup reference IDs are not yet guaranteed to be unique (see #1913). In order to meet that constraint, it would have to pass the `remaining` value as the `pageSize` in the request resulting in the non-batching behavior I mentioned.
</blockquote></details>

I was not aware that Flow.flattenConcat would end up causing the requests to stop once an event group is found.

However, I think you're misunderstanding what what I suggested... I'm suggesting that the listPredicate itself filter out non-matching resource names. That means that it will always return either 1 or 0 items. If it finds no matches, it returns 0 items. Otherwise, it returns 1. Once once is returned, there is no need to continue. I think this is a little more straightforward. The reader may read your code and make the same assumption I did.


<!-- Sent from Reviewable.io -->

2024-11-22 17:24 UTC, merged