feat: Add flag for specifying the the VID model line
world-federation-of-advertisers/cross-media-measurement pull request #1931
Opened 2024-11-20 23:20 UTC by kungfucraig

Support VID Model Line rollout using Reporting Server flags. Two flags are added:

–default-vid-model-line=<String>
Specifies the VID model line value to be used for the “model_line” field in MeasurementSpec This in turn determines what VID model line that EDPs will use to fulfill Requisitions. If empty EDPs must agree offline what the default is. Once enabled we encourage that this case become an error.

–measurement-consumer-vid-model-lines=Map<String, String>
A map of MC names to model lines. When a Metric is created, if the Metric is for an MC present in this map, then the model line provided as the value will be used for the  “model_line” field in MeasurementSpec.

2024-11-20 23:20 UTC, wfa-reviewable commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1931)
<!-- Reviewable:end -->

2024-11-20 23:46 UTC, SanjayVas requested changes
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1931)* status: all files reviewed, 7 unresolved discussions (waiting on @kungfucraig)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/common/ReportingApiServerFlags.kt` line 58 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1931#-OCAuGjBD6fnS3OJne3I:-OCAuGjCAwnvoRH0h_CK:b9ac3q3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/12518354f5fc1bd8838bbfe0d33bbbdd1c346531/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/common/ReportingApiServerFlags.kt#L58)):*
> ```Kotlin
> 
>   @CommandLine.Option(
>     names = ["--measurement-consumer-model-lines"],
> ```

Singular flag name



_Suggestion:_
```Kotlin
--measurement-consumer-model-line
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/common/ReportingApiServerFlags.kt` line 61 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1931#-OCAtQYNEltF5FB18TAK:-OCAtQYNEltF5FB18TAL:b-y11jmk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/12518354f5fc1bd8838bbfe0d33bbbdd1c346531/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/common/ReportingApiServerFlags.kt#L61)):*
> ```Kotlin
>     description =
>       [
>         "A map of measurement consumer names to model lines. This map indicates which model line " +
> ```

Document that this is a key-value pair and that it can be specified multiple times. See `--event-group-spec` in SyntheticGeneratorEdpSimulatorRunner.kt as an example.

The flag usage is that you'd specify the flags multiple times, once for each key-value pair.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/common/ReportingApiServerFlags.kt` line 61 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1931#-OCAv27h6ItOOFEfSX-g:-OCAv27h6ItOOFEfSX-h:b83iyph) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/12518354f5fc1bd8838bbfe0d33bbbdd1c346531/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/common/ReportingApiServerFlags.kt#L61)):*
> ```Kotlin
>     description =
>       [
>         "A map of measurement consumer names to model lines. This map indicates which model line " +
> ```

nit: be more explicit that this is a resource name



_Suggestion:_
```Kotlin
resource name
```
___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsServiceTest.kt` line 493 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1931#-OCAvoDVEY_QPQ5eMVsB:-OCAvoDVEY_QPQ5eMVsC:b-7s4sqq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/12518354f5fc1bd8838bbfe0d33bbbdd1c346531/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsServiceTest.kt#L493)):*
> ```Kotlin
>   )
> 
> private val DEFAULT_VID_MODEL_LINE = "the-model-line"
> ```

const
___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsServiceTest.kt` line 495 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1931#-OCAvu3KAF5W6lP_5qct:-OCAvu3KAF5W6lP_5qcu:bhpmkzg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/12518354f5fc1bd8838bbfe0d33bbbdd1c346531/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsServiceTest.kt#L495)):*
> ```Kotlin
> private val DEFAULT_VID_MODEL_LINE = "the-model-line"
> private val MEASUREMENT_CONSUMER_MODEL_LINES =
>   mapOf<String, String>(MEASUREMENT_CONSUMERS.values.first().name to "mc-model-line")
> ```

nit: prefer specifying the property type and letting it use type inference for the builder types



_Suggestion:_
```Kotlin
private val MEASUREMENT_CONSUMER_MODEL_LINES: Map<String, String> =
  mapOf(MEASUREMENT_CONSUMERS.values.first().name to "mc-model-line")
```
___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsServiceTest.kt` line 2461 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1931#-OCAwO724y6MLthRHBHG:-OCAwO724y6MLthRHBHH:b-a1heet) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/12518354f5fc1bd8838bbfe0d33bbbdd1c346531/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsServiceTest.kt#L2461)):*
> ```Kotlin
>       )
>   }
> ```

Ideally you want a test that creates a Metric using a different MC so that you can verify that `DEFAULT_VID_MODEL_LINE` is used
___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsServiceTest.kt` line 2527 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1931#-OCAxRgd91gCqILxxaIN:-OCAxRgd91gCqILxxaIO:b-7khogb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/12518354f5fc1bd8838bbfe0d33bbbdd1c346531/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsServiceTest.kt#L2527)):*
> ```Kotlin
>         createMeasurementRequest.measurement.measurementSpec.unpack()
>       assertThat(measurementSpec)
>         .isEqualTo(
> ```

Shouldn't this be failing since it doesn't check that the model line is set?


<!-- Sent from Reviewable.io -->

2024-11-21 00:38 UTC, kungfucraig reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1931)* status: 2 of 4 files reviewed, 5 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/common/ReportingApiServerFlags.kt` line 58 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1931#-OCAuGjBD6fnS3OJne3I:-OCB7dCR9ZC8ycjQ8N__:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/12518354f5fc1bd8838bbfe0d33bbbdd1c346531/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/common/ReportingApiServerFlags.kt#L58)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Singular flag name
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/common/ReportingApiServerFlags.kt` line 61 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1931#-OCAtQYNEltF5FB18TAK:-OCB8pyeCibHv0kgjlN-:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/12518354f5fc1bd8838bbfe0d33bbbdd1c346531/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/common/ReportingApiServerFlags.kt#L61)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Document that this is a key-value pair and that it can be specified multiple times. See `--event-group-spec` in SyntheticGeneratorEdpSimulatorRunner.kt as an example.

The flag usage is that you'd specify the flags multiple times, once for each key-value pair.
</blockquote></details>

Done.
___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsServiceTest.kt` line 493 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1931#-OCAvoDVEY_QPQ5eMVsB:-OCB5RbFAI_PCH5_5nAV:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/12518354f5fc1bd8838bbfe0d33bbbdd1c346531/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsServiceTest.kt#L493)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

const
</blockquote></details>

Done.
___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsServiceTest.kt` line 2461 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1931#-OCAwO724y6MLthRHBHG:-OCB4zXqBN6eNDLaay-I:b-uelyjv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/12518354f5fc1bd8838bbfe0d33bbbdd1c346531/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsServiceTest.kt#L2461)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Ideally you want a test that creates a Metric using a different MC so that you can verify that `DEFAULT_VID_MODEL_LINE` is used
</blockquote></details>

That what I mentioned on chat. The setup for an MC is onerous. On a side, I expect we'd see this MC setup code copied and pasted in a lot of places by now and having some test utilities could be a nice thing. In our spare time I suppose... 

Anyway, I built a second service that doesn't have the MC map to test the default model line behavior. That seems to work.
___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsServiceTest.kt` line 2527 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1931#-OCAxRgd91gCqILxxaIN:-OCB6aORC8LHMycXv1DH:bp19e53) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/12518354f5fc1bd8838bbfe0d33bbbdd1c346531/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsServiceTest.kt#L2527)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Shouldn't this be failing since it doesn't check that the model line is set?
</blockquote></details>

No, it's comparing to modified copy of UNION_ALL_BUT_LAST SPEC, which is a copy of the BASE SPEC, which sets the model line.


<!-- Sent from Reviewable.io -->

2024-11-21 18:29 UTC, SanjayVas requested changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1931)* status: all files reviewed, 1 unresolved discussion (waiting on @kungfucraig)

___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsServiceTest.kt` line 2463 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1931#-OCEyvZY7TWRJ8wJbCnZ:-OCEyvZY7TWRJ8wJbCn_:b-1qew4e) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7673fd63c112b6f3551ce39b46521607a67d40c4/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsServiceTest.kt#L2463)):*
> ```Kotlin
> 
>     // create a second service with an empty measurement consumer model line map
>     service2 =
> ```

This will create the second service for every test method. You want to instead create this service as a local variable within the test method that uses it.


<!-- Sent from Reviewable.io -->

2024-11-21 19:45 UTC, kungfucraig reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1931)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsServiceTest.kt` line 2463 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1931#-OCEyvZY7TWRJ8wJbCnZ:-OCFFXTS0546w33oe7Sn:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7673fd63c112b6f3551ce39b46521607a67d40c4/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsServiceTest.kt#L2463)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This will create the second service for every test method. You want to instead create this service as a local variable within the test method that uses it.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-11-21 19:47 UTC, SanjayVas approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1931)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @kungfucraig)



<!-- Sent from Reviewable.io -->

2024-11-26 18:43 UTC, kungfucraig reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1931)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/common/ReportingApiServerFlags.kt` line 58 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1931#-OCdZWgT5-XUBqTH9iDy:-OCdlQeZ55iCvWpNRuye:bsu23vn) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3570c2b8ddc18f9ce20756cea7f05e8f0d7e4d24/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/common/ReportingApiServerFlags.kt#L58)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

this feels pretty arduous to maintain. 

A different design would automatically set the default for a MC the first time they run a measurement and store that value to continue using until updated at some point in the future.
</blockquote></details>

This flag is only meant to enable safe model rollouts. Specifically it is to allow a specific test MC to have a new model enabled before the model is enabled as the default for all MCs. HMSS has an almost identical configuration, and I anticipate we'll use this pattern a lot in the future (i.e. default config with per MC overrides to test rollouts).

Also note that, the use of the VID Model Repo will replace this entire PR.


<!-- Sent from Reviewable.io -->

2024-11-26 20:12 UTC, stevenwarejones requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1931)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @kungfucraig and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/common/ReportingApiServerFlags.kt` line 58 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1931#-OCdZWgT5-XUBqTH9iDy:-OCe5S4s3-ZF8IySuauK:bwogaga) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3570c2b8ddc18f9ce20756cea7f05e8f0d7e4d24/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/common/ReportingApiServerFlags.kt#L58)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

This flag is only meant to enable safe model rollouts. Specifically it is to allow a specific test MC to have a new model enabled before the model is enabled as the default for all MCs. HMSS has an almost identical configuration, and I anticipate we'll use this pattern a lot in the future (i.e. default config with per MC overrides to test rollouts).

Also note that, the use of the VID Model Repo will replace this entire PR.
</blockquote></details>

this requires restarting the reporting server each time then, right? That also seems kind of messy here. Shouldn't this be set when the individual report is requested then?


<!-- Sent from Reviewable.io -->

2024-11-26 20:26 UTC, kungfucraig reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1931)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/common/ReportingApiServerFlags.kt` line 58 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1931#-OCdZWgT5-XUBqTH9iDy:-OCe7phV5tOywoC7GxQu:b-r3wbmo) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3570c2b8ddc18f9ce20756cea7f05e8f0d7e4d24/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/common/ReportingApiServerFlags.kt#L58)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

this requires restarting the reporting server each time then, right? That also seems kind of messy here. Shouldn't this be set when the individual report is requested then?
</blockquote></details>

It does require a restart and it's fine. This is a simple temporary fix for something that will happen a handful of times before the VID Model Repo comes on line, which is the proper solution to this problem. 


<!-- Sent from Reviewable.io -->

2024-11-26 21:39 UTC, stevenwarejones requested changes
> Reviewed 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1931)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @kungfucraig and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/common/ReportingApiServerFlags.kt` line 58 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1931#-OCdZWgT5-XUBqTH9iDy:-OCeOpM9BEy6GYAacPbM:b-7n35ox) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3570c2b8ddc18f9ce20756cea7f05e8f0d7e4d24/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/common/ReportingApiServerFlags.kt#L58)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

It does require a restart and it's fine. This is a simple temporary fix for something that will happen a handful of times before the VID Model Repo comes on line, which is the proper solution to this problem.
</blockquote></details>

can you add TODO to remove this once the VID Model repo comes online?

I'm a little confused how the Model Repo will address this same issue.


<!-- Sent from Reviewable.io -->

2024-11-27 19:34 UTC, kungfucraig reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1931)* status: 3 of 6 files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/common/ReportingApiServerFlags.kt` line 58 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1931#-OCdZWgT5-XUBqTH9iDy:-OCecTh36lEIEHQXm-jI:bdwy8jp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3570c2b8ddc18f9ce20756cea7f05e8f0d7e4d24/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/common/ReportingApiServerFlags.kt#L58)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

can you add TODO to remove this once the VID Model repo comes online?

I'm a little confused how the Model Repo will address this same issue.
</blockquote></details>

Added the TODO. 

Happy to discuss how this gets addressed long-term offline.


<!-- Sent from Reviewable.io -->

2024-12-02 14:14 UTC, stevenwarejones reviewed
> Reviewed 1 of 4 files at r1, 1 of 1 files at r3, 1 of 2 files at r4, 1 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1931)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 545 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1931#-OD6i4uc0QlOgG5-49dw:-OD6i4ud-99XYbvYWn4A:bwmtssi) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/26ce63e06ee04513d85293ce7a858ab1cf8ad9e7/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L545)):*
> ```Kotlin
>             }
>         }
>         // TODO(@jojijac0b): Complete support for VID Model Line
> ```

@jojijac0b - FYI


<!-- Sent from Reviewable.io -->

2024-12-02 18:44 UTC, stevenwarejones approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1931)* status: 5 of 6 files reviewed, all discussions resolved (waiting on @SanjayVas)



<!-- Sent from Reviewable.io -->

2024-12-02 23:05 UTC, kungfucraig reviewed
> Reviewed 1 of 4 files at r1, 1 of 1 files at r3, 2 of 2 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1931)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)



<!-- Sent from Reviewable.io -->

2024-12-03 18:40 UTC, stevenwarejones approved these changes
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1931)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)



<!-- Sent from Reviewable.io -->

2024-12-06 23:22 UTC, kungfucraig reviewed
> Reviewed 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1931)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)



<!-- Sent from Reviewable.io -->

2024-12-06 23:22 UTC, merged