feat: Adds the definition of basic report.
world-federation-of-advertisers/cross-media-measurement pull request #1942
Opened 2024-12-01 23:35 UTC by kungfucraig

2024-12-01 23:36 UTC, wfa-reviewable commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942)
<!-- Reviewable:end -->

2024-12-06 21:51 UTC, stevenwarejones reviewed
> Reviewed 1 of 3 files at r1, 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @kungfucraig, @mariolamassaavedra, @SanjayVas, and @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/media_type.proto` line 29 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-ODSwO9e113jqqpfKJw_:-ODSwO9f5Zkge2UfhrwT:b-3pmloj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ed6840e2c8f370b46d5699b2ec4c13d6599e770d/src/main/proto/wfa/measurement/reporting/v2alpha/media_type.proto#L29)):*
> ```proto
> // CROSS_MEDIA is used when the artifact encompases more that one
> // of the other types.
> enum MediaType {
> ```

Are these validated by Alex and Hannah?


<!-- Sent from Reviewable.io -->

2024-12-06 21:52 UTC, stevenwarejones reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @kungfucraig, @mariolamassaavedra, @SanjayVas, and @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/media_type.proto` line 29 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-ODSwO9e113jqqpfKJw_:-ODSxMwQEQUqVvbEbWj8:blc1kzv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ed6840e2c8f370b46d5699b2ec4c13d6599e770d/src/main/proto/wfa/measurement/reporting/v2alpha/media_type.proto#L29)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

Are these validated by Alex and Hannah?
</blockquote></details>

Also - isn't there some talk of sub-categories as well?


<!-- Sent from Reviewable.io -->

2024-12-06 21:53 UTC, stevenwarejones reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @kungfucraig, @mariolamassaavedra, @SanjayVas, and @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/basic_report.proto` line 56 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-ODSxgDe6CBmOTlEoO9k:-ODSxgDe6CBmOTlEoO9l:b-7qzytr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ed6840e2c8f370b46d5699b2ec4c13d6599e770d/src/main/proto/wfa/measurement/reporting/v2alpha/basic_report.proto#L56)):*
> ```proto
>   // be reported on. Event Groups may span Data Providers and Media Types.
>   // Subsets of these can be reported on and are determined by PageSpec.
>   string campaign_group = 3;
> ```

is this the reporting_set_resource_name?
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/basic_report.proto` line 235 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-ODSxZKr7uk_jC20B4Xz:-ODSxZKr7uk_jC20B4Y-:b2eckg1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ed6840e2c8f370b46d5699b2ec4c13d6599e770d/src/main/proto/wfa/measurement/reporting/v2alpha/basic_report.proto#L235)):*
> ```proto
>       // Discuss: There should probably be an option for week over week unique
>       // too? Should check the modeling API proposal to see if that's necessary.
>       // bool unique = 3;
> ```

did you mean to comment this out?


<!-- Sent from Reviewable.io -->

2024-12-06 21:55 UTC, stevenwarejones reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @kungfucraig, @mariolamassaavedra, @SanjayVas, and @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/media_type.proto` line 29 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-ODSwO9e113jqqpfKJw_:-ODSxrEhCEW8eTm8q0fy:bd2y3zm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ed6840e2c8f370b46d5699b2ec4c13d6599e770d/src/main/proto/wfa/measurement/reporting/v2alpha/media_type.proto#L29)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

Also - isn't there some talk of sub-categories as well?
</blockquote></details>

I'd prefer to not have Other as an option since this list is likely to grow. The definition of other will be reduced over time possibly leading to some confusion.


<!-- Sent from Reviewable.io -->

2024-12-06 22:01 UTC, kungfucraig reviewed
@stevenwarejones This definition should support Phase I and Phase II. My plan is to cull this to the set of things necessary for Phase I before merging, but I'd like to get buy-in on Phase II since the definitions for Phase I need to be compatible with Phase II.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-:-ODSz4hACJfJYlnx3OCC:btrq8vt)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @mariolamassaavedra, @SanjayVas, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/basic_report.proto` line 56 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-ODSxgDe6CBmOTlEoO9k:-ODSyjBfATB8aK7pizu8:b-rn0wwr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ed6840e2c8f370b46d5699b2ec4c13d6599e770d/src/main/proto/wfa/measurement/reporting/v2alpha/basic_report.proto#L56)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

is this the reporting_set_resource_name?
</blockquote></details>

It's the name of a reporting set, yes. However, it's not any old reporting set, it has a particular structure (see comment), which is why the term campaign group is used.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/basic_report.proto` line 235 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-ODSxZKr7uk_jC20B4Xz:-ODSygRrAC-1MGjZAbFj:bb77ufg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ed6840e2c8f370b46d5699b2ec4c13d6599e770d/src/main/proto/wfa/measurement/reporting/v2alpha/basic_report.proto#L235)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

did you mean to comment this out?
</blockquote></details>

Yes.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/media_type.proto` line 29 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-ODSwO9e113jqqpfKJw_:-ODSxH0ACSY3b1TPUEuN:b9ni9dh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ed6840e2c8f370b46d5699b2ec4c13d6599e770d/src/main/proto/wfa/measurement/reporting/v2alpha/media_type.proto#L29)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

I'd prefer to not have Other as an option since this list is likely to grow. The definition of other will be reduced over time possibly leading to some confusion.
</blockquote></details>

No, but let's work under the assumption that this list can grow and that the market config can choose to use a subset of these.

There is talk of sub-categories, but it's not clear that the sub-categories are being used to drive reporting behavior.

The good news is that we don't need this for Phase I.


<!-- Sent from Reviewable.io -->

2024-12-06 22:03 UTC, kungfucraig reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @mariolamassaavedra, @SanjayVas, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/media_type.proto` line 29 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-ODSwO9e113jqqpfKJw_:-ODSzaEG9fZsvYtIb79Y:boo45r4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ed6840e2c8f370b46d5699b2ec4c13d6599e770d/src/main/proto/wfa/measurement/reporting/v2alpha/media_type.proto#L29)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

No, but let's work under the assumption that this list can grow and that the market config can choose to use a subset of these.

There is talk of sub-categories, but it's not clear that the sub-categories are being used to drive reporting behavior.

The good news is that we don't need this for Phase I.
</blockquote></details>

Note that "Other" is an existing media type in the current Origin report. Given that I think we have to have it here.


<!-- Sent from Reviewable.io -->

2024-12-10 23:43 UTC, tristanvuong2021 requested changes
> Reviewed 1 of 3 files at r1, 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942)* status: 2 of 3 files reviewed, 6 unresolved discussions (waiting on @kungfucraig, @mariolamassaavedra, @SanjayVas, and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/basic_report.proto` line 84 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-ODmpz2E0QvpSYQVbApC:-ODmpz2E0QvpSYQVbApD:b-tvs2dj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ed6840e2c8f370b46d5699b2ec4c13d6599e770d/src/main/proto/wfa/measurement/reporting/v2alpha/basic_report.proto#L84)):*
> ```proto
>   ReportingInterval reporting_interval = 4;
> 
>   // Specification of for custom viewability and completion filter.
> ```

nit: Is there a word missing here or is the of extra?
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/basic_report.proto` line 149 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-ODmx4is-Cy0bujQNH7r:-ODmx4is-Cy0bujQNH7s:bre8ny4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ed6840e2c8f370b46d5699b2ec4c13d6599e770d/src/main/proto/wfa/measurement/reporting/v2alpha/basic_report.proto#L149)):*
> ```proto
>   message Filter {
>     message Term {
>       // The name of event template (aka dimension) to filter on
> ```

Is this supposed to be event template field
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/basic_report.proto` line 363 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-ODmuEmpCWLjOmVuh--L:-ODmtXUG-jQwj1sOy_Vo:b-4t5fl5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ed6840e2c8f370b46d5699b2ec4c13d6599e770d/src/main/proto/wfa/measurement/reporting/v2alpha/basic_report.proto#L363)):*
> ```proto
>       // The qualification filter used when computing the result.
>       oneof qualification_filter {
>         string name = 6;
> ```

What is the name here


<!-- Sent from Reviewable.io -->

2024-12-11 18:39 UTC, SanjayVas requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942)* status: 2 of 3 files reviewed, 7 unresolved discussions (waiting on @kungfucraig, @mariolamassaavedra, and @stevenwarejones)

___
*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-ODqyjqF1rvLeIESu2Uk:-ODqyjqG4TdPmIdCRTd8:b6nikr7) (no related file):*
The API lint GitHub workflow does not currently cover this API. I'm willing to bet there are other API lint errors elsewhere in the API definition. For now, just make sure that you run the linter yourself using `tools/api-lint` to make sure that this PR does not introduce any new lint warnings. I've included the initial findings below. The main issue is that every symbol must be documented.


```yaml
- file_path: wfa/measurement/reporting/v2alpha/basic_report.proto
  problems:
    - message: '"value" should have only leading (not trailing) public comments.'
      location:
        start_position:
            line_number: 152
            column_number: 7
        end_position:
            line_number: 152
            column_number: 23
        path: wfa/measurement/reporting/v2alpha/basic_report.proto
      rule_id: core::0192::only-leading-comments
      rule_doc_uri: https://linter.aip.dev/192/only-leading-comments
    - message: '"cumulative" should have only leading (not trailing) public comments.'
      location:
        start_position:
            line_number: 226
            column_number: 7
        end_position:
            line_number: 226
            column_number: 26
        path: wfa/measurement/reporting/v2alpha/basic_report.proto
      rule_id: core::0192::only-leading-comments
      rule_doc_uri: https://linter.aip.dev/192/only-leading-comments
    - message: '"DATA_PROVIDER" should have only leading (not trailing) public comments.'
      location:
        start_position:
            line_number: 166
            column_number: 5
        end_position:
            line_number: 166
            column_number: 22
        path: wfa/measurement/reporting/v2alpha/basic_report.proto
      rule_id: core::0192::only-leading-comments
      rule_doc_uri: https://linter.aip.dev/192/only-leading-comments
    - message: Resources should declare plural.
      location:
        start_position:
            line_number: 39
            column_number: 3
        end_position:
            line_number: 42
            column_number: 4
        path: wfa/measurement/reporting/v2alpha/basic_report.proto
      rule_id: core::0123::resource-plural
      rule_doc_uri: https://linter.aip.dev/123/resource-plural
    - message: The first enum value should be "REPORTING_UNIT_TYPE_UNSPECIFIED"
      suggestion: REPORTING_UNIT_TYPE_UNSPECIFIED
      location:
        start_position:
            line_number: 164
            column_number: 5
        end_position:
            line_number: 164
            column_number: 30
        path: wfa/measurement/reporting/v2alpha/basic_report.proto
      rule_id: core::0126::unspecified
      rule_doc_uri: https://linter.aip.dev/126/unspecified
    - message: Fields should not use the `_name` suffix.
      suggestion: dimension
      location:
        start_position:
            line_number: 140
            column_number: 21
        end_position:
            line_number: 140
            column_number: 34
        path: wfa/measurement/reporting/v2alpha/basic_report.proto
      rule_id: core::0122::name-suffix
      rule_doc_uri: https://linter.aip.dev/122/name-suffix
    - message: Fields should not use the `_name` suffix.
      suggestion: dimension
      location:
        start_position:
            line_number: 150
            column_number: 14
        end_position:
            line_number: 150
            column_number: 27
        path: wfa/measurement/reporting/v2alpha/basic_report.proto
      rule_id: core::0122::name-suffix
      rule_doc_uri: https://linter.aip.dev/122/name-suffix
    - message: Fields should not use the `_name` suffix.
      suggestion: dimension
      location:
        start_position:
            line_number: 369
            column_number: 16
        end_position:
            line_number: 369
            column_number: 29
        path: wfa/measurement/reporting/v2alpha/basic_report.proto
      rule_id: core::0122::name-suffix
      rule_doc_uri: https://linter.aip.dev/122/name-suffix
    - message: 'Resources should declare singular: "basicReport"'
      location:
        start_position:
            line_number: 39
            column_number: 3
        end_position:
            line_number: 42
            column_number: 4
        path: wfa/measurement/reporting/v2alpha/basic_report.proto
      rule_id: core::0123::resource-singular
      rule_doc_uri: https://linter.aip.dev/123/resource-singular
    - message: resource name field must have field_behavior IDENTIFIER
      location:
        start_position:
            line_number: 45
            column_number: 3
        end_position:
            line_number: 45
            column_number: 18
        path: wfa/measurement/reporting/v2alpha/basic_report.proto
      rule_id: core::0203::resource-name-identifier
      rule_doc_uri: https://linter.aip.dev/203/resource-name-identifier
    - message: Missing comment over "reporting_interval".
      location:
        start_position:
            line_number: 82
            column_number: 21
        end_position:
            line_number: 82
            column_number: 38
        path: wfa/measurement/reporting/v2alpha/basic_report.proto
      rule_id: core::0192::has-comments
      rule_doc_uri: https://linter.aip.dev/192/has-comments
    - message: Missing comment over "viewability".
      location:
        start_position:
            line_number: 103
            column_number: 13
        end_position:
            line_number: 103
            column_number: 23
        path: wfa/measurement/reporting/v2alpha/basic_report.proto
      rule_id: core::0192::has-comments
      rule_doc_uri: https://linter.aip.dev/192/has-comments
    - message: Missing comment over "completion".
      location:
        start_position:
            line_number: 104
            column_number: 13
        end_position:
            line_number: 104
            column_number: 22
        path: wfa/measurement/reporting/v2alpha/basic_report.proto
      rule_id: core::0192::has-comments
      rule_doc_uri: https://linter.aip.dev/192/has-comments
    - message: Missing comment over "fraction".
      location:
        start_position:
            line_number: 99
            column_number: 15
        end_position:
            line_number: 99
            column_number: 22
        path: wfa/measurement/reporting/v2alpha/basic_report.proto
      rule_id: core::0192::has-comments
      rule_doc_uri: https://linter.aip.dev/192/has-comments
    - message: Missing comment over "quantile".
      location:
        start_position:
            line_number: 100
            column_number: 18
        end_position:
            line_number: 100
            column_number: 25
        path: wfa/measurement/reporting/v2alpha/basic_report.proto
      rule_id: core::0192::has-comments
      rule_doc_uri: https://linter.aip.dev/192/has-comments
    - message: Missing comment over "Term".
      location:
        start_position:
            line_number: 148
            column_number: 13
        end_position:
            line_number: 148
            column_number: 16
        path: wfa/measurement/reporting/v2alpha/basic_report.proto
      rule_id: core::0192::has-comments
      rule_doc_uri: https://linter.aip.dev/192/has-comments
    - message: Missing comment over "longitudinal_options".
      location:
        start_position:
            line_number: 237
            column_number: 25
        end_position:
            line_number: 237
            column_number: 44
        path: wfa/measurement/reporting/v2alpha/basic_report.proto
      rule_id:  [...]

2024-12-11 19:02 UTC, kungfucraig reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942)* status: 2 of 3 files reviewed, 7 unresolved discussions (waiting on @mariolamassaavedra, @SanjayVas, and @stevenwarejones)

___
*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-ODqyjqF1rvLeIESu2Uk:-ODr5G7I3jAL5IiUv7Fw:b-j55vu3) (no related file):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The API lint GitHub workflow does not currently cover this API. I'm willing to bet there are other API lint errors elsewhere in the API definition. For now, just make sure that you run the linter yourself using `tools/api-lint` to make sure that this PR does not introduce any new lint warnings. I've included the initial findings below. The main issue is that every symbol must be documented.


```yaml
- file_path: wfa/measurement/reporting/v2alpha/basic_report.proto
  problems:
    - message: '"value" should have only leading (not trailing) public comments.'
      location:
        start_position:
            line_number: 152
            column_number: 7
        end_position:
            line_number: 152
            column_number: 23
        path: wfa/measurement/reporting/v2alpha/basic_report.proto
      rule_id: core::0192::only-leading-comments
      rule_doc_uri: https://linter.aip.dev/192/only-leading-comments
    - message: '"cumulative" should have only leading (not trailing) public comments.'
      location:
        start_position:
            line_number: 226
            column_number: 7
        end_position:
            line_number: 226
            column_number: 26
        path: wfa/measurement/reporting/v2alpha/basic_report.proto
      rule_id: core::0192::only-leading-comments
      rule_doc_uri: https://linter.aip.dev/192/only-leading-comments
    - message: '"DATA_PROVIDER" should have only leading (not trailing) public comments.'
      location:
        start_position:
            line_number: 166
            column_number: 5
        end_position:
            line_number: 166
            column_number: 22
        path: wfa/measurement/reporting/v2alpha/basic_report.proto
      rule_id: core::0192::only-leading-comments
      rule_doc_uri: https://linter.aip.dev/192/only-leading-comments
    - message: Resources should declare plural.
      location:
        start_position:
            line_number: 39
            column_number: 3
        end_position:
            line_number: 42
            column_number: 4
        path: wfa/measurement/reporting/v2alpha/basic_report.proto
      rule_id: core::0123::resource-plural
      rule_doc_uri: https://linter.aip.dev/123/resource-plural
    - message: The first enum value should be "REPORTING_UNIT_TYPE_UNSPECIFIED"
      suggestion: REPORTING_UNIT_TYPE_UNSPECIFIED
      location:
        start_position:
            line_number: 164
            column_number: 5
        end_position:
            line_number: 164
            column_number: 30
        path: wfa/measurement/reporting/v2alpha/basic_report.proto
      rule_id: core::0126::unspecified
      rule_doc_uri: https://linter.aip.dev/126/unspecified
    - message: Fields should not use the `_name` suffix.
      suggestion: dimension
      location:
        start_position:
            line_number: 140
            column_number: 21
        end_position:
            line_number: 140
            column_number: 34
        path: wfa/measurement/reporting/v2alpha/basic_report.proto
      rule_id: core::0122::name-suffix
      rule_doc_uri: https://linter.aip.dev/122/name-suffix
    - message: Fields should not use the `_name` suffix.
      suggestion: dimension
      location:
        start_position:
            line_number: 150
            column_number: 14
        end_position:
            line_number: 150
            column_number: 27
        path: wfa/measurement/reporting/v2alpha/basic_report.proto
      rule_id: core::0122::name-suffix
      rule_doc_uri: https://linter.aip.dev/122/name-suffix
    - message: Fields should not use the `_name` suffix.
      suggestion: dimension
      location:
        start_position:
            line_number: 369
            column_number: 16
        end_position:
            line_number: 369
            column_number: 29
        path: wfa/measurement/reporting/v2alpha/basic_report.proto
      rule_id: core::0122::name-suffix
      rule_doc_uri: https://linter.aip.dev/122/name-suffix
    - message: 'Resources should declare singular: "basicReport"'
      location:
        start_position:
            line_number: 39
            column_number: 3
        end_position:
            line_number: 42
            column_number: 4
        path: wfa/measurement/reporting/v2alpha/basic_report.proto
      rule_id: core::0123::resource-singular
      rule_doc_uri: https://linter.aip.dev/123/resource-singular
    - message: resource name field must have field_behavior IDENTIFIER
      location:
        start_position:
            line_number: 45
            column_number: 3
        end_position:
            line_number: 45
            column_number: 18
        path: wfa/measurement/reporting/v2alpha/basic_report.proto
      rule_id: core::0203::resource-name-identifier
      rule_doc_uri: https://linter.aip.dev/203/resource-name-identifier
    - message: Missing comment over "reporting_interval".
      location:
        start_position:
            line_number: 82
            column_number: 21
        end_position:
            line_number: 82
            column_number: 38
        path: wfa/measurement/reporting/v2alpha/basic_report.proto
      rule_id: core::0192::has-comments
      rule_doc_uri: https://linter.aip.dev/192/has-comments
    - message: Missing comment over "viewability".
      location:
        start_position:
            line_number: 103
            column_number: 13
        end_position:
            line_number: 103
            column_number: 23
        path: wfa/measurement/reporting/v2alpha/basic_report.proto
      rule_id: core::0192::has-comments
      rule_doc_uri: https://linter.aip.dev/192/has-comments
    - message: Missing comment over "completion".
      location:
        start_position:
            line_number: 104
            column_number: 13
        end_position:
            line_number: 104
            column_number: 22
        path: wfa/measurement/reporting/v2alpha/basic_report.proto
      rule_id: core::0192::has-comments
      rule_doc_uri: https://linter.aip.dev/192/has-comments
    - message: Missing comment over "fraction".
      location:
        start_position:
            line_number: 99
            column_number: 15
        end_position:
            line_number: 99
            column_number: 22
        path: wfa/measurement/reporting/v2alpha/basic_report.proto
      rule_id: core::0192::has-comments
      rule_doc_uri: https://linter.aip.dev/192/has-comments
    - message: Missing comment over "quantile".
      location:
        start_position:
            line_number: 100
            column_number: 18
        end_position:
            line_number: 100
            column_number: 25
        path: wfa/measurement/reporting/v2alpha/basic_report.proto
      rule_id: core::0192::has-comments
      rule_doc_uri: https://linter.aip.dev/192/has-comments
    - message: Missing comment over "Term".
      location:
        start_position:
            line_number: 148
            column_number: 13
        end_position:
            line_number: 148
            column_number: 16
        path: wfa/measurement/reporting/v2alpha/basic_report.proto
      rule_id: core::0192::has-comments
      rule_doc_uri: https://linter.aip.dev/192/has-comments
    - message: Missing comment over "longitudinal_options".
      location:
        start_position:
            line_number: 237
            column_number: 25
        end_position:
            line_number: 237
            column_number: 44
        path: wfa/m [...]

2024-12-11 19:04 UTC, SanjayVas requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942)* status: 2 of 3 files reviewed, 16 unresolved discussions (waiting on @kungfucraig, @mariolamassaavedra, and @stevenwarejones)

___
*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-ODqyjqF1rvLeIESu2Uk:-ODr5g5m8yVOwaQcJoee:b-rtegmh) (no related file):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

I will lint it and add annotations, etc once we agree on the substance.
</blockquote></details>

Some annotations are an important part of said substance. Namely, resource references and field behaviors.


<!-- Sent from Reviewable.io -->

2024-12-15 23:08 UTC, kungfucraig reviewed
Will add services either in a follow-up or in this PR once the resource definitions are agreed to.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-:-OEBXaz60EOiq_YonWUX:b-d3s9wp)* status: 0 of 7 files reviewed, 13 unresolved discussions (waiting on @mariolamassaavedra, @SanjayVas, @stevenwarejones, and @tristanvuong2021)

___
*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-ODqyjqF1rvLeIESu2Uk:-OEBWRTv7fTg9AQsJsD-:b-6yxt75) (no related file):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Some annotations are an important part of said substance. Namely, resource references and field behaviors.
</blockquote></details>

I added annotations. Will lint on a future revision and before merge.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/basic_report.proto` line 56 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-ODSxgDe6CBmOTlEoO9k:-OEBWqIw1pIBtrVAjnvS:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ed6840e2c8f370b46d5699b2ec4c13d6599e770d/src/main/proto/wfa/measurement/reporting/v2alpha/basic_report.proto#L56)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

A resource_reference annotation would make this clearer.
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/basic_report.proto` line 88 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-ODr0aqUDRxyhwKRzEwx:-ODsOt8gDAAahaxbNI0D:bfoefjz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ed6840e2c8f370b46d5699b2ec4c13d6599e770d/src/main/proto/wfa/measurement/reporting/v2alpha/basic_report.proto#L88)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Is there a meaningful difference between unspecified and zero? Is it something like whether video playback even started?
</blockquote></details>

It's just a default that will cause an error to ensure the user sets a value explicitly. Defaulting to zero would make the default custom filter look like "all measured impressions," which is not a great behavior.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/basic_report.proto` line 122 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-ODr27Jf6wewvwvwBA3D:-ODx3pZj6cACq9fwbZRz:b7sh3yx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ed6840e2c8f370b46d5699b2ec4c13d6599e770d/src/main/proto/wfa/measurement/reporting/v2alpha/basic_report.proto#L122)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Rather than having these be special strings, I think we can have ImpressionFilter be a separate resource type and have these be resource references. The resource itself need not have Create methods and can just come from a config file.

This allows for discoverability of the supported filters for a Reporting system instance (market).
</blockquote></details>

Good idea. Added resource.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/basic_report.proto` line 139 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-ODr16OL0mWDsmB_fLf-:-ODsQJNi2B7PPWQoV7Oo:b-wxch2n) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ed6840e2c8f370b46d5699b2ec4c13d6599e770d/src/main/proto/wfa/measurement/reporting/v2alpha/basic_report.proto#L139)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

1. How is the common template identified? Is there going to be a new field in the template annotation?
2. Need to be more specific on the format here. For example, is this a field name within the common template, or is this a field path on the event message? (`age_group` vs. `common.age_group`)

Maybe `dimension_field` or `dimension_field_name` to be clearer?
</blockquote></details>

I will explore the first question in a forthcoming design doc. 

For the second point, I update the comments.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/basic_report.proto` line 149 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-ODmx4is-Cy0bujQNH7r:-ODx4Qax43UozqnAtdaA:be28xxj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ed6840e2c8f370b46d5699b2ec4c13d6599e770d/src/main/proto/wfa/measurement/reporting/v2alpha/basic_report.proto#L149)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Is this supposed to be event template field
</blockquote></details>

Yes. Updated.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/basic_report.proto` line 152 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-ODr2vH4CIxmHANjDMIg:-ODx4hse4oueeQyuuIQR:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ed6840e2c8f370b46d5699b2ec4c13d6599e770d/src/main/proto/wfa/measurement/reporting/v2alpha/basic_report.proto#L152)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I assume field types other than string should be supported. This should use a structure like `FieldValue` in `simulator_synthetic_data_spec.proto`.
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/basic_report.proto` line 179 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-ODr3d-85LCMc7zKrWxx:-ODx6sQrAsrMUr6PbYxj:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ed6840e2c8f370b46d5699b2ec4c13d6599e770d/src/main/proto/wfa/measurement/reporting/v2alpha/basic_report.proto#L179)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Add a resource reference annotation here. You can use "*" as the type if multiple resource types are supported. See the `protected_resource` field on `wfa.measurement.access.v1alpha.Policy` for an example.
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/basic_report.proto` line 363 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-ODmuEmpCWLjOmVuh--L:-OEBXPDp8hiatYLX0le8:b-fczf8l) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ed6840e2c8f370b46d5699b2ec4c13d6599e770d/src/main/proto/wfa/measurement/reporting/v2alpha/basic_report.proto#L363)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

What is the name here
</blockquote></details>

See page.proto
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/basic_report.proto` line 363 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-ODr4jiM87SVp2Xa0x5r:-OEBXPX21dSr6Dxd6Zms:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ed6840e2c8f370b46d5699b2ec4c13d6599e770d/src/main/proto/wfa/measurement/reporting/v2alpha/basic_report.proto#L363)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This cannot be called `name` since it is not the resource name of the message in which it is defined.

From [AIP-122](https://google.aip.dev/122):

> Fields **must not** be called `name` except for this purpose. For other use cases, either use a different term or prepend an adjective (for example: `display_name`).
</blockquote></details>

Done.
___
*[`src/main/proto/w [...]

2024-12-16 18:00 UTC, kungfucraig reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942)* status: 0 of 7 files reviewed, 13 unresolved discussions (waiting on @mariolamassaavedra, @SanjayVas, @stevenwarejones, and @tristanvuong2021)

___
*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-ODqyjqF1rvLeIESu2Uk:-OEFcEwvC1IXoh9lMZeX:bksu7fb) (no related file):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

I added annotations. Will lint on a future revision and before merge.
</blockquote></details>

Lint is complete.


<!-- Sent from Reviewable.io -->

2024-12-16 23:56 UTC, SanjayVas requested changes
> Reviewed 1 of 7 files at r4, 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942)* status: 6 of 7 files reviewed, 13 unresolved discussions (waiting on @kungfucraig, @mariolamassaavedra, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/page.proto` line 82 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-OEGpd4V6WUKSBtnzEvu:-OEGpd4V6WUKSBtnzEvv:bri0kve) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fdfc3ece1f70eeae5e4528460c39b29e16bb12c5/src/main/proto/wfa/measurement/reporting/v2alpha/page.proto#L82)):*
nit: Use similar language as that on `SyntheticPopulationSpec.population_fields`.

> Field paths use `.` as the traveral operator. For example, if there is a field in the `common` template named `age_group`, then the field path would be `common.age_group`.



_Code quote:_
```proto
    // For example, if there is an event tempalte field in common
    // named "age_group" then this value should be common.age_group
```
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/media_type.proto` line 33 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-ODr5ILU0BknZnLg0e7f:-OEGs2Wa1j6bQ7yEtBii:b-awvpeq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ed6840e2c8f370b46d5699b2ec4c13d6599e770d/src/main/proto/wfa/measurement/reporting/v2alpha/media_type.proto#L33)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

So... I think we actually end up with an enum on the Event Group side that doesn't have CROSS_MEDIA.
</blockquote></details>

Yes, the fact that the CMMS API will have its own enum is a given. My point is that I don't think I like having a value in an enum that essentially means "some unspecified combination of the other enum values". Meaning I think the two enums should have the same set of values, and that `CROSS_MEDIA` would never be a valid valid for an enum that's referring to a singular media type.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/reporting_common.proto` line 27 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-OEGoKur8h-EEpwwpXpY:-OEGoKur8h-EEpwwpXpZ:b1om1st) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fdfc3ece1f70eeae5e4528460c39b29e16bb12c5/src/main/proto/wfa/measurement/reporting/v2alpha/reporting_common.proto#L27)):*
> ```proto
> 
> // Specifies the units to report on.
> message ReportingUnit {
> ```

nit: use separate files if there's not a clearer concept for how these top-level definitions are related
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/reporting_common.proto` line 152 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-OEGrMmUE0IZRwihAZJ5:-OEGrMmUE0IZRwihAZJ6:b-ielg68) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fdfc3ece1f70eeae5e4528460c39b29e16bb12c5/src/main/proto/wfa/measurement/reporting/v2alpha/reporting_common.proto#L152)):*
> ```proto
> //
> // TODO(@kungfucraig) Introduce REPORTING_SET for Phase III
> enum ReportingUnitType {
> ```

I thought we were dropping this enum, and instead having the `components` field have a resource reference of type `halo.wfanet.org/DataProvider` for `BasicReport` and type `reporting.halo-cmm.org/ReportingSet` for the `AdvancedReport` query.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/basic_report.proto` line 42 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-OEGilCwCkfcuBx0D786:-OEGilCwCkfcuBx0D787:b-1jhmsg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fdfc3ece1f70eeae5e4528460c39b29e16bb12c5/src/main/proto/wfa/measurement/reporting/v2alpha/basic_report.proto#L42)):*
> ```proto
>   // Resource name.
>   string name = 1 [
>     (google.api.field_behavior) = IMMUTABLE,
> ```

The `name` field should only have the IDENTIFIER behavior. This inherently implies immutability _after_ creation. The subtlety here is that the name field isn't specified in Create requests.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/basic_report.proto` line 93 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-OEGpMDQ-2hK0wQVJlxC:-OEGpMDR9j4nRzpyr2Kr:bppldan) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fdfc3ece1f70eeae5e4528460c39b29e16bb12c5/src/main/proto/wfa/measurement/reporting/v2alpha/basic_report.proto#L93)):*
> ```proto
>   // The set of filters for this report.
>   //
>   // An entry in this map must exist for every ReportingMediaType used in
> ```

I don't think this is a map



_Suggestion:_
```proto
set
```
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/page.proto` line 31 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-OEGo2TJ6fdm5SXYFVCT:-OEGo2TJ6fdm5SXYFVCU:b-tj9eo4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fdfc3ece1f70eeae5e4528460c39b29e16bb12c5/src/main/proto/wfa/measurement/reporting/v2alpha/page.proto#L31)):*
> ```proto
> // Defines the Frequency, Groupings, and Filters for calculating
> // a set of Metrics
> message CalculationSpec {
> ```

nit: Move this to its own file if it's used in more than one message. Otherwise nest it inside of the sole message type its used inside of.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/page.proto` line 112 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-OEGqPVv0TV10kwSAjyB:-OEGqPVv0TV10kwSAjyC:bsq89kv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fdfc3ece1f70eeae5e4528460c39b29e16bb12c5/src/main/proto/wfa/measurement/reporting/v2alpha/page.proto#L112)):*
> ```proto
>       message FieldValue {
>         oneof value {
>           // Used when the event template field is a string or enum
> ```

Use a different field for enums to be explicit, even if you want to use the string name as the value instead of the number. e.g.

```proto
// Name of the value for a field with an enum type.
string enum_value = 2 [(google.api.field_behavior) = IMMUTABLE];
```



_Code quote:_
```proto
or enum
```


<!-- Sent from Reviewable.io -->

2024-12-17 01:19 UTC, kungfucraig reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942)* status: 2 of 19 files reviewed, 11 unresolved discussions (waiting on @mariolamassaavedra, @SanjayVas, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/basic_report.proto` line 93 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-OEGpMDQ-2hK0wQVJlxC:-OEHBTkl-BFUg1m6050S:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fdfc3ece1f70eeae5e4528460c39b29e16bb12c5/src/main/proto/wfa/measurement/reporting/v2alpha/basic_report.proto#L93)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I don't think this is a map
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/page.proto` line 31 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-OEGo2TJ6fdm5SXYFVCT:-OEHBCbF-DJPU3U7ia30:b-24tir5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fdfc3ece1f70eeae5e4528460c39b29e16bb12c5/src/main/proto/wfa/measurement/reporting/v2alpha/page.proto#L31)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: Move this to its own file if it's used in more than one message. Otherwise nest it inside of the sole message type its used inside of.
</blockquote></details>

This is used by two message in this file. The items in this file are very closely related.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/page.proto` line 82 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-OEGpd4V6WUKSBtnzEvu:-OEHB9UYBMDruxs8gflQ:b-t5uspa) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fdfc3ece1f70eeae5e4528460c39b29e16bb12c5/src/main/proto/wfa/measurement/reporting/v2alpha/page.proto#L82)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: Use similar language as that on `SyntheticPopulationSpec.population_fields`.

> Field paths use `.` as the traveral operator. For example, if there is a field in the `common` template named `age_group`, then the field path would be `common.age_group`.
</blockquote></details>

Leaving this unresolved and will update later.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/page.proto` line 112 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-OEGqPVv0TV10kwSAjyB:-OEHB7n_2afrTTZenZMY:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fdfc3ece1f70eeae5e4528460c39b29e16bb12c5/src/main/proto/wfa/measurement/reporting/v2alpha/page.proto#L112)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Use a different field for enums to be explicit, even if you want to use the string name as the value instead of the number. e.g.

```proto
// Name of the value for a field with an enum type.
string enum_value = 2 [(google.api.field_behavior) = IMMUTABLE];
```
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/media_type.proto` line 33 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-ODr5ILU0BknZnLg0e7f:-OEGyu8H72x2lVw5Yh2V:b-4i346l) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ed6840e2c8f370b46d5699b2ec4c13d6599e770d/src/main/proto/wfa/measurement/reporting/v2alpha/media_type.proto#L33)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Yes, the fact that the CMMS API will have its own enum is a given. My point is that I don't think I like having a value in an enum that essentially means "some unspecified combination of the other enum values". Meaning I think the two enums should have the same set of values, and that `CROSS_MEDIA` would never be a valid valid for an enum that's referring to a singular media type.
</blockquote></details>

Updated an added FilterType. I was trying to use the same enum for both, but splitting them works out pretty well.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/reporting_common.proto` line 27 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-OEGoKur8h-EEpwwpXpY:-OEH-4NLB08fSzGbmNuB:bot0erq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fdfc3ece1f70eeae5e4528460c39b29e16bb12c5/src/main/proto/wfa/measurement/reporting/v2alpha/reporting_common.proto#L27)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: use separate files if there's not a clearer concept for how these top-level definitions are related
</blockquote></details>

Split this file up.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/reporting_common.proto` line 152 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-OEGrMmUE0IZRwihAZJ5:-OEGyKAJ2qTecTKbgYzA:b-5x41mw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fdfc3ece1f70eeae5e4528460c39b29e16bb12c5/src/main/proto/wfa/measurement/reporting/v2alpha/reporting_common.proto#L152)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I thought we were dropping this enum, and instead having the `components` field have a resource reference of type `halo.wfanet.org/DataProvider` for `BasicReport` and type `reporting.halo-cmm.org/ReportingSet` for the `AdvancedReport` query.
</blockquote></details>

Agreed offline to drop it. And it's gone...


<!-- Sent from Reviewable.io -->

2024-12-17 16:11 UTC, tristanvuong2021 requested changes
> Reviewed 1 of 7 files at r4, 1 of 5 files at r6, 8 of 17 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942)* status: 10 of 19 files reviewed, 10 unresolved discussions (waiting on @kungfucraig, @mariolamassaavedra, @SanjayVas, and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/basic_reports_service.proto` line 57 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-OEKNYZ-3BQ1Bq4WTP4Y:-OEKNYZ-3BQ1Bq4WTP4Z:b-iay5e2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6eb9bd50de75263ee5b07915223edec6b04b7db4/src/main/proto/wfa/measurement/reporting/v2alpha/basic_reports_service.proto#L57)):*
> ```proto
> 
> // Request mesage for 'GetListBasicReport' method
> message ListBasicReportsRequest {
> ```

Realized we should add a parent field for the MeasurementConsumer


<!-- Sent from Reviewable.io -->

2024-12-17 16:27 UTC, tristanvuong2021 reviewed
> Reviewed 5 of 17 files at r7.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942)* status: 15 of 19 files reviewed, 10 unresolved discussions (waiting on @kungfucraig, @mariolamassaavedra, @SanjayVas, and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2024-12-17 20:16 UTC, SanjayVas requested changes
> Reviewed 17 of 17 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942)* status: all files reviewed, 12 unresolved discussions (waiting on @kungfucraig, @mariolamassaavedra, and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/basic_reports_service.proto` line 62 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-OELE-VEA7gav_7U7llB:-OELE-VEA7gav_7U7llC:b-5zbmp0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6eb9bd50de75263ee5b07915223edec6b04b7db4/src/main/proto/wfa/measurement/reporting/v2alpha/basic_reports_service.proto#L62)):*
> ```proto
>     // Return BasicReports that were created after this time.
>     google.protobuf.Timestamp created_after = 1
>         [(google.api.field_behavior) = REQUIRED];
> ```

nit: It seems a bit odd to say that this field is required. I know that currently Filter only has one field, therefore if it's specified technically that one field is required. We generally expect to be able to add more fields to Filter, so I think you can just a document that at least one child field must be set.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/impression_qualification_filter_spec.proto` line 34 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-OELEWb10QG-A2jRc4II:-OELEWb10QG-A2jRc4IJ:b2ni8l0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6eb9bd50de75263ee5b07915223edec6b04b7db4/src/main/proto/wfa/measurement/reporting/v2alpha/impression_qualification_filter_spec.proto#L34)):*
> ```proto
>   //
>   // Generally, a Filter with a given Filter Type is applied to a Reporting Unit
>   // when the type matches that of the Reporting Media Type. However, a filer
> ```

nit



_Suggestion:_
```proto
filter
```
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/impression_qualification_filter_spec.proto` line 73 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-OELEfl9DYD5iz4-S1c9:-OELEfl9DYD5iz4-S1cA:baae1pi) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6eb9bd50de75263ee5b07915223edec6b04b7db4/src/main/proto/wfa/measurement/reporting/v2alpha/impression_qualification_filter_spec.proto#L73)):*
> ```proto
>   // Specify a percent as a fraction or as a quantile
>   message Percent {
>     oneof value {
> ```

nit: document the oneof as required. You can't use a field behavior annotation for this, so it is purely documentation to indicate that one of the fields must be set.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/impression_qualification_filters_service.proto` line 30 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-OELEvxnDYV8bYbOj7SB:-OELEvxnDYV8bYbOj7SC:b-gtxsas) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6eb9bd50de75263ee5b07915223edec6b04b7db4/src/main/proto/wfa/measurement/reporting/v2alpha/impression_qualification_filters_service.proto#L30)):*
> ```proto
> 
> // Service for managing 'BasicReport' resources.
> service BasicReports {
> ```

This whole file appears to just be a copy of `basic_reports_service.proto` rather than defining a service for ImpressionQualificationFilter resources.



_Suggestion:_
```proto
ImpressionQualificationFilters
```
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/reporting_unit.proto` line 32 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-OELFXQm0b0pP3gQo-uq:-OELFXQm0b0pP3gQo-ur:brk45vf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6eb9bd50de75263ee5b07915223edec6b04b7db4/src/main/proto/wfa/measurement/reporting/v2alpha/reporting_unit.proto#L32)):*
> ```proto
>   // For use with BasicReport these must be Data Provider resource names
>   // For use with AdvancedReport these must be Reporting Set resource names
>   repeated string components = 2 [
> ```

nit: renumber fields so they are not sparse initially



_Code quote:_
```proto
2
```
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/reporting_unit.proto` line 60 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-OELFkUzEZI_WwaD9pUR:-OELFkUzEZI_WwaD9pUS:b-759afy) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6eb9bd50de75263ee5b07915223edec6b04b7db4/src/main/proto/wfa/measurement/reporting/v2alpha/reporting_unit.proto#L60)):*
> ```proto
> // ReportingMediaType is used to designate how reporting artifacts
> // should be interpreted for reporting.
> enum ReportingMediaType {
> ```

Why does this need to be prefixed with "Reporting"? You don't need to worry about conflicting with symbols from other APIs/packages.



_Suggestion:_
```proto
MediaType
```


<!-- Sent from Reviewable.io -->

2024-12-18 00:47 UTC, kungfucraig reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942)* status: 11 of 19 files reviewed, 7 unresolved discussions (waiting on @mariolamassaavedra, @SanjayVas, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/basic_report.proto` line 42 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-OEGilCwCkfcuBx0D786:-OELR-sZ64EAuE7Svphc:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fdfc3ece1f70eeae5e4528460c39b29e16bb12c5/src/main/proto/wfa/measurement/reporting/v2alpha/basic_report.proto#L42)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The `name` field should only have the IDENTIFIER behavior. This inherently implies immutability _after_ creation. The subtlety here is that the name field isn't specified in Create requests.
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/basic_reports_service.proto` line 57 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-OEKNYZ-3BQ1Bq4WTP4Y:-OELUi7R1lEpdCuLXYab:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6eb9bd50de75263ee5b07915223edec6b04b7db4/src/main/proto/wfa/measurement/reporting/v2alpha/basic_reports_service.proto#L57)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Realized we should add a parent field for the MeasurementConsumer
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/basic_reports_service.proto` line 62 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-OELE-VEA7gav_7U7llB:-OELTKKEBIcOm9E_4-Rs:b-k4n788) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6eb9bd50de75263ee5b07915223edec6b04b7db4/src/main/proto/wfa/measurement/reporting/v2alpha/basic_reports_service.proto#L62)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: It seems a bit odd to say that this field is required. I know that currently Filter only has one field, therefore if it's specified technically that one field is required. We generally expect to be able to add more fields to Filter, so I think you can just a document that at least one child field must be set.
</blockquote></details>

If/when we add the additional field we should tag this optional and document it as you suggest.

https://google.aip.dev/203#backwards-compatibility
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/impression_qualification_filters_service.proto` line 30 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-OELEvxnDYV8bYbOj7SB:-OELUEE57rNM9rUjLUlM:b-lyyiq0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6eb9bd50de75263ee5b07915223edec6b04b7db4/src/main/proto/wfa/measurement/reporting/v2alpha/impression_qualification_filters_service.proto#L30)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This whole file appears to just be a copy of `basic_reports_service.proto` rather than defining a service for ImpressionQualificationFilter resources.
</blockquote></details>

Sorry about that. It wasn't supposed to make the last revision, but it's updated now.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/reporting_unit.proto` line 60 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-OELFkUzEZI_WwaD9pUR:-OELUnsL3G2GWg_x2pJp:b-r2vsce) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6eb9bd50de75263ee5b07915223edec6b04b7db4/src/main/proto/wfa/measurement/reporting/v2alpha/reporting_unit.proto#L60)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Why does this need to be prefixed with "Reporting"? You don't need to worry about conflicting with symbols from other APIs/packages.
</blockquote></details>

It doesn't need to be. The disambiguation seemed like it could be useful for conversation.


<!-- Sent from Reviewable.io -->

2024-12-18 21:45 UTC, SanjayVas requested changes
> Reviewed 15 of 15 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942)* status: all files reviewed, 13 unresolved discussions (waiting on @kungfucraig, @mariolamassaavedra, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/impression_qualification_filters_service.proto` line 36 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-OEQgWFa4ma41ysJpCNs:-OEQgWFa4ma41ysJpCNt:undefined) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1650045fad3b3543e7ea2170880e066609372cf8/src/main/proto/wfa/measurement/reporting/v2alpha/impression_qualification_filters_service.proto#L36)):*
> ```proto
>       returns (ImpressionQualificationFilter) {
>     option (google.api.http) = {
>       get: "/v2alpha/{name=impressionQualificationFilters/*}"
> ```





_Suggestion:_
```proto
"/v2alpha/{name=measurementConsumers/*/impressionQualificationFilters/*}"
```
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/impression_qualification_filters_service.proto` line 41 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-OEQglHt4Rws1yldo69F:-OEQglHt4Rws1yldo69G:b-loemsn) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1650045fad3b3543e7ea2170880e066609372cf8/src/main/proto/wfa/measurement/reporting/v2alpha/impression_qualification_filters_service.proto#L41)):*
> ```proto
>   }
> 
>   // Ordered by filter type and name in ascending order.
> ```

The first line needs to be summary fragment describing the method.



_Suggestion:_
```proto
  // Lists `ImpressionQualification` resources ordered by filter type and name in ascending order.
```
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/impression_qualification_filters_service.proto` line 52 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-OEQh3mzCEtQt1qOvO5T:-OEQh3mzCEtQt1qOvO5U:bwwjr4n) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1650045fad3b3543e7ea2170880e066609372cf8/src/main/proto/wfa/measurement/reporting/v2alpha/impression_qualification_filters_service.proto#L52)):*
> ```proto
> }
> 
> // Request mesage for 'GetImpressionQualificationFilter' method
> ```

nit: typo here and elsewhere



_Suggestion:_
```proto
message
```
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/impression_qualification_filters_service.proto` line 65 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-OEQi2AW3koBBhBS6DPb:-OEQi2AW3koBBhBS6DPc:bgkmsoy) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1650045fad3b3543e7ea2170880e066609372cf8/src/main/proto/wfa/measurement/reporting/v2alpha/impression_qualification_filters_service.proto#L65)):*
> ```proto
> // Request mesage for 'ListImpressionQualificationFilter' method
> message ListImpressionQualificationFiltersRequest {
>   // Message for specifying filters for listing ImpressionQualificationFilters.
> ```

nit: you should have the same phrasing we do on structured filter message types in the CMMS API



_Suggestion:_
```proto
  // Filter criteria. Repeated fields are treated as logical ORs, and multiple
  // fields specified as logical ANDs.
```
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/impression_qualification_filters_service.proto` line 69 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-OEQhXuw5gfG1DEKeNBn:-OEQhXuw5gfG1DEKeNBo:bc8oi7i) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1650045fad3b3543e7ea2170880e066609372cf8/src/main/proto/wfa/measurement/reporting/v2alpha/impression_qualification_filters_service.proto#L69)):*
> ```proto
>   // At least one of the following criteria must be specified.
>   message Filter {
>     // Returns impression qualification filters with the given filter type.
> ```

nit: Verb phrases are for methods, not fields (this shouldn't start with "Returns")



_Suggestion:_
```proto
// Filter matching the `filter_type` field.
```
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/basic_reports_service.proto` line 61 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-OEQdwmLB-ziyWtPuhsm:-OEQdwmLB-ziyWtPuhsn:bfgd99) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1650045fad3b3543e7ea2170880e066609372cf8/src/main/proto/wfa/measurement/reporting/v2alpha/basic_reports_service.proto#L61)):*
> ```proto
> }
> 
> // Request mesage for 'ListBasicReport' method
> ```

nit: backticks for symbols, not single quotes. Also typos



_Suggestion:_
```proto
// Request message for `ListBasicReports` method
```
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/basic_reports_service.proto` line 63 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-OEQeq1p-vlMKysODTNM:-OEQeq1p-vlMKysODTNN:bnuriye) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1650045fad3b3543e7ea2170880e066609372cf8/src/main/proto/wfa/measurement/reporting/v2alpha/basic_reports_service.proto#L63)):*
> ```proto
> // Request mesage for 'ListBasicReport' method
> message ListBasicReportsRequest {
>   // List the Basic Reports of the given parent.
> ```

nit: describe the field, not the action



_Suggestion:_
```proto
// Resource name of the parent `MeasurementConsumer`.
```
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/basic_reports_service.proto` line 68 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-OEQfHKA-uTUbHDvSSnv:-OEQfHKA-uTUbHDvSSnw:b-uua510) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1650045fad3b3543e7ea2170880e066609372cf8/src/main/proto/wfa/measurement/reporting/v2alpha/basic_reports_service.proto#L68)):*
> ```proto
>     (google.api.resource_reference) = {
>       type: "reporting.halo-cmm.org/MeasurementConsumer"
>     }
> ```

You use `child_type` for the `parent` field. See https://google.aip.dev/132

I suppose using `type` is also fine if there's only one valid parent, but then it should be `halo.wfanet.org/MeasurementConsumer` since the parent is a `MeasurementConsumer` from the CMMS API (Reporting doesn't have its own MeasurementConsumer resource type).



_Suggestion:_
```proto
    (google.api.resource_reference) = {
      child_type: "reporting.halo-cmm.org/BasicReport"
    }
```
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/basic_reports_service.proto` line 77 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-OEQe5vd2P7FqdTybtUN:-OEQe5veCOrHA84eh7FP:bs9wg13) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1650045fad3b3543e7ea2170880e066609372cf8/src/main/proto/wfa/measurement/reporting/v2alpha/basic_reports_service.proto#L77)):*
> ```proto
>     //  -- api-linter: core::0142::time-field-names=disabled
>     //     aip.dev/not-precedent: Using a preposition and not ending with "time"
>     //  is natural here. --)
> ```

nit: the explanation we use elsewhere is that we use structured filters instead of the AIP-160 filtering language. These inherently need relative timestamps. See https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/main/src/main/proto/wfa/measurement/api/v2alpha/measurements_service.proto for examples



_Code quote:_
```proto
    //     aip.dev/not-precedent: Using a preposition and not ending with "time"
    //  is natural here. --)
```


<!-- Sent from Reviewable.io -->

2024-12-18 22:29 UTC, kungfucraig reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942)* status: 16 of 19 files reviewed, 7 unresolved discussions (waiting on @mariolamassaavedra, @SanjayVas, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/basic_reports_service.proto` line 68 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-OEQfHKA-uTUbHDvSSnv:-OEQpSDm3vTpB5LjLTVn:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1650045fad3b3543e7ea2170880e066609372cf8/src/main/proto/wfa/measurement/reporting/v2alpha/basic_reports_service.proto#L68)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

You use `child_type` for the `parent` field. See https://google.aip.dev/132

I suppose using `type` is also fine if there's only one valid parent, but then it should be `halo.wfanet.org/MeasurementConsumer` since the parent is a `MeasurementConsumer` from the CMMS API (Reporting doesn't have its own MeasurementConsumer resource type).
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/impression_qualification_filters_service.proto` line 41 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-OEQglHt4Rws1yldo69F:-OEQqAdt-un1OivG_pFy:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1650045fad3b3543e7ea2170880e066609372cf8/src/main/proto/wfa/measurement/reporting/v2alpha/impression_qualification_filters_service.proto#L41)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The first line needs to be summary fragment describing the method.
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/impression_qualification_filters_service.proto` line 36 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-OEQgWFa4ma41ysJpCNs:-OEQnSc87THRofPZhzp3:b-wv1rdc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1650045fad3b3543e7ea2170880e066609372cf8/src/main/proto/wfa/measurement/reporting/v2alpha/impression_qualification_filters_service.proto#L36)):*
> ```proto
>       returns (ImpressionQualificationFilter) {
>     option (google.api.http) = {
>       get: "/v2alpha/{name=impressionQualificationFilters/*}"
> ```

These are part of the system configuration and should be global not scoped by MC.


<!-- Sent from Reviewable.io -->

2024-12-18 23:28 UTC, SanjayVas requested changes
> Reviewed 1 of 3 files at r9, 2 of 3 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942)* status: 18 of 19 files reviewed, 5 unresolved discussions (waiting on @kungfucraig, @mariolamassaavedra, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/impression_qualification_filters_service.proto` line 36 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-OEQgWFa4ma41ysJpCNs:-OER4p7J9LKLG1Cjeefl:b-ah6i7h) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1650045fad3b3543e7ea2170880e066609372cf8/src/main/proto/wfa/measurement/reporting/v2alpha/impression_qualification_filters_service.proto#L36)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

These are part of the system configuration and should be global not scoped by MC.
</blockquote></details>

Then the pattern in the List method instead needs to not have parent.


<!-- Sent from Reviewable.io -->

2024-12-19 23:55 UTC, kungfucraig reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942)* status: 17 of 19 files reviewed, 5 unresolved discussions (waiting on @mariolamassaavedra, @SanjayVas, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/impression_qualification_filters_service.proto` line 36 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-OEQgWFa4ma41ysJpCNs:-OEWL8gnEYQam5u_QWpY:b-8jn5j6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1650045fad3b3543e7ea2170880e066609372cf8/src/main/proto/wfa/measurement/reporting/v2alpha/impression_qualification_filters_service.proto#L36)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Then the pattern in the List method instead needs to not have parent.
</blockquote></details>

Hopefully that does it.


<!-- Sent from Reviewable.io -->

2024-12-20 00:22 UTC, SanjayVas approved these changes
> Reviewed 1 of 3 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942)* status: all files reviewed, 4 unresolved discussions (waiting on @mariolamassaavedra, @stevenwarejones, and @tristanvuong2021)



<!-- Sent from Reviewable.io -->

2024-12-20 16:23 UTC, tristanvuong2021 reviewed
> Reviewed 11 of 15 files at r8, 1 of 3 files at r9, 1 of 3 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942)* status: all files reviewed, 3 unresolved discussions (waiting on @mariolamassaavedra and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2024-12-20 16:26 UTC, tristanvuong2021 approved these changes
> Reviewed 1 of 15 files at r8, 1 of 3 files at r10.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942)* status: all files reviewed, 3 unresolved discussions (waiting on @mariolamassaavedra and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2025-01-02 20:43 UTC, kungfucraig reviewed
Made several updates based upon my design work on Phase III and Advanced Report.

> Reviewed 1 of 5 files at r6, 1 of 17 files at r7, 1 of 3 files at r10, 16 of 18 files at r12, 3 of 3 files at r13, 1 of 1 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-:-OFcf9w9AGQ9SA9yo1V9:bjbpdx6)* status: all files reviewed, 3 unresolved discussions (waiting on @mariolamassaavedra and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2025-01-02 22:40 UTC, stevenwarejones requested changes
> Reviewed 1 of 15 files at r8, 1 of 3 files at r10, 1 of 1 files at r11, 6 of 18 files at r12, 1 of 1 files at r14.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942)* status: all files reviewed, 5 unresolved discussions (waiting on @kungfucraig and @mariolamassaavedra)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/page.proto` line 66 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-OFbgb-c5VoxFllUgkYH:-OFbgb-d6GjAsLg9f0SQ:b-utqsy6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ea2e849906bef880e4c39bd7f15e80eba25da81f/src/main/proto/wfa/measurement/reporting/v2alpha/page.proto#L66)):*
> ```proto
>     CUMULATIVE = 1;
>     // Compute non-cumulative metrics
>     NON_CUMULATIVE = 2;
> ```

is this always a binary choice? If so, wouldn't a boolean be better?
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/page.proto` line 128 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-OFbhGRW2pq5AzqGWCm1:-OFbhGRW2pq5AzqGWCm2:b-4duwrw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ea2e849906bef880e4c39bd7f15e80eba25da81f/src/main/proto/wfa/measurement/reporting/v2alpha/page.proto#L128)):*
> ```proto
>     // The term that defines the filter criteria.
>     //
>     // May be extended to a disjunction of terms in the future.
> ```

would this comment better fit along with the existing comment on the `filters` field?
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/page.proto` line 174 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-OFbiyyk7Q4psphJwIYf:-OFbiyyk7Q4psphJwIYg:b-6yn73w) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ea2e849906bef880e4c39bd7f15e80eba25da81f/src/main/proto/wfa/measurement/reporting/v2alpha/page.proto#L174)):*
> ```proto
>       // The k plus reach up to the frequency specified. Value must be
>       // positive.
>       int32 k_plus_reach = 3 [(google.api.field_behavior) = IMMUTABLE];
> ```

should this be a repeated for multiple k+ reaches? 2+, 3+, 4+ etc?
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/page.proto` line 179 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-OFbjBBvBEP80aSkSqIg:-OFbjBBvBEP80aSkSqIh:b-7ropln) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ea2e849906bef880e4c39bd7f15e80eba25da81f/src/main/proto/wfa/measurement/reporting/v2alpha/page.proto#L179)):*
> ```proto
>       // k_plus_reach, in which case if specified the percent k+
>       // reach values are also computed.
>       bool percent_k_plus_reach = 4 [(google.api.field_behavior) = IMMUTABLE];
> ```

ditto


<!-- Sent from Reviewable.io -->

2025-01-02 23:32 UTC, kungfucraig reviewed
> Reviewed 1 of 3 files at r13, 1 of 1 files at r15.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942)* status: all files reviewed, 5 unresolved discussions (waiting on @mariolamassaavedra and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/page.proto` line 66 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-OFbgb-c5VoxFllUgkYH:-OFdKoxuEbDdRWlma5Qt:b-3ew707) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ea2e849906bef880e4c39bd7f15e80eba25da81f/src/main/proto/wfa/measurement/reporting/v2alpha/page.proto#L66)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

is this always a binary choice? If so, wouldn't a boolean be better?
</blockquote></details>

It was previous a boolean. It's kind of weird as a boolean, because you'll have something called "cumulative" and it not being set means compute non-cumulative metrics. The boolean would make more sense if it mean compute cumulative metrics in addition to non-cumulative metrics.

I think this helps us keep our options open too, in the unlikely case we end up with a third value.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/page.proto` line 128 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-OFbhGRW2pq5AzqGWCm1:-OFdLWbRDNzjXmCayo3f:brp0xk7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ea2e849906bef880e4c39bd7f15e80eba25da81f/src/main/proto/wfa/measurement/reporting/v2alpha/page.proto#L128)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

would this comment better fit along with the existing comment on the `filters` field?
</blockquote></details>

Given that this is the field that would be become repeated, I'm not so sure.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/page.proto` line 174 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-OFbiyyk7Q4psphJwIYf:-OFdLjI68JSBPkpaQHF2:beuylba) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ea2e849906bef880e4c39bd7f15e80eba25da81f/src/main/proto/wfa/measurement/reporting/v2alpha/page.proto#L174)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

should this be a repeated for multiple k+ reaches? 2+, 3+, 4+ etc?
</blockquote></details>

This is the field that is indicating what metrics to compute, not the values of the metrics.

If the value is 4, we compute 1+, 2+, 3+, 4+. The results structure is an array of int32.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/page.proto` line 179 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-OFbjBBvBEP80aSkSqIg:-OFdM3I94swg9_UNuJf0:b5fqavi) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ea2e849906bef880e4c39bd7f15e80eba25da81f/src/main/proto/wfa/measurement/reporting/v2alpha/page.proto#L179)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Same story.


<!-- Sent from Reviewable.io -->

2025-01-03 16:30 UTC, stevenwarejones requested changes
> Reviewed 1 of 5 files at r6, 1 of 17 files at r7, 8 of 18 files at r12, 2 of 3 files at r13, 1 of 1 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942)* status: all files reviewed, 6 unresolved discussions (waiting on @kungfucraig and @mariolamassaavedra)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/page.proto` line 174 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-OFbiyyk7Q4psphJwIYf:-OFgxdb95smwjSfBi_lk:b-3snn10) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ea2e849906bef880e4c39bd7f15e80eba25da81f/src/main/proto/wfa/measurement/reporting/v2alpha/page.proto#L174)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

This is the field that is indicating what metrics to compute, not the values of the metrics.

If the value is 4, we compute 1+, 2+, 3+, 4+. The results structure is an array of int32.
</blockquote></details>

makes sense. I misread the comment previously. Are there scenarios where an advertiser would only want 3+ reach and nothing else?
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/reporting_unit.proto` line 46 at r15](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-OFgzw2LDjJzWc8sfBxz:-OFgzw2M6u0k_Qkp_YEn:bw2m9je) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/091a868bba8c30554e6ecf7f5def9367d4620058/src/main/proto/wfa/measurement/reporting/v2alpha/reporting_unit.proto#L46)):*
> ```proto
> 
>   // The MediaType filters that were applied to the components.
>   repeated MediaType reported_media_types = 3 [
> ```

maybe I'm misunderstanding but a ReportingUnit should have results on all Media Types within a set of Event Groups preferable. Or imo, the Basic Report should strongly encourage that.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/reporting_impression_qualification_filter.proto` line 36 at r15](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-OFgzDQTCzULKILpnAgv:-OFgzDQTCzULKILpnAgw:bjguwqh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/091a868bba8c30554e6ecf7f5def9367d4620058/src/main/proto/wfa/measurement/reporting/v2alpha/reporting_impression_qualification_filter.proto#L36)):*
> ```proto
> //      are defined as the intersection of the reporting unit's actual Media
> //      Types and the report's Media Type filters. This is called the scoped
> //      Media Type. For exmaple, if the Event Gruops of the reporting
> ```

`Groups`

Also - there is not Media Type field on Event Group yet - https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/main/src/main/proto/wfa/measurement/api/v2alpha/event_group.proto
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/page.proto` line 223 at r15](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-OFgxynZD4Y9aVbCWc1q:-OFgxynZD4Y9aVbCWc1r:b-myc138) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/091a868bba8c30554e6ecf7f5def9367d4620058/src/main/proto/wfa/measurement/reporting/v2alpha/page.proto#L223)):*
> ```proto
> 
>     // The impressions associated with the unique reach.
>     // Phase III
> ```

nit: can you put TODO before all the future Phase stuff?
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/page.proto` line 359 at r15](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-OFgyq1L9RY4ugy2O9Qm:-OFgyq1L9RY4ugy2O9Qn:b7q0tgl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/091a868bba8c30554e6ecf7f5def9367d4620058/src/main/proto/wfa/measurement/reporting/v2alpha/page.proto#L359)):*
> ```proto
>   message ResultValue {
>     // The size of the population for the filters/grouping specified
>     int32 population_size = 9 [(google.api.field_behavior) = IMMUTABLE];
> ```

i assume we aren't going to worry about the over 2B problem?
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/page.proto` line 373 at r15](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-OFgyQ58767NIcLH7EWq:-OFgyQ58767NIcLH7EWr:bz7hu46) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/091a868bba8c30554e6ecf7f5def9367d4620058/src/main/proto/wfa/measurement/reporting/v2alpha/page.proto#L373)):*
> ```proto
>         repeated int32 k_plus_reach = 3
>             [(google.api.field_behavior) = IMMUTABLE];
>         // The perecent k+ reach
> ```

`percent`
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/page.proto` line 377 at r15](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-OFgyVo4A2-TYnhA0TMB:-OFgyVo4A2-TYnhA0TMC:bt3kmom) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/091a868bba8c30554e6ecf7f5def9367d4620058/src/main/proto/wfa/measurement/reporting/v2alpha/page.proto#L377)):*
> ```proto
>             [(google.api.field_behavior) = IMMUTABLE];
>         // The frequency historam where the index is frequency-1
>         repeated float frequency_histogram = 5
> ```

wouldn't a map be a better structure here?
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/page.proto` line 417 at r15](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-OFgywFx2j06Sb6xhecj:-OFgywFx2j06Sb6xheck:b-cd7540) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/091a868bba8c30554e6ecf7f5def9367d4620058/src/main/proto/wfa/measurement/reporting/v2alpha/page.proto#L417)):*
> ```proto
> 
>         // The unique reach
>         int32 unique_rech = 2 [(google.api.field_behavior) = IMMUTABLE];
> ```

`unique_reach`
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/impression_qualification_filter_spec.proto` line 40 at r15](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-OFgxHtZEfx4IqW5F3GN:-OFgxHtZEfx4IqW5F3GO:bdlm58c) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/091a868bba8c30554e6ecf7f5def9367d4620058/src/main/proto/wfa/measurement/reporting/v2alpha/impression_qualification_filter_spec.proto#L40)):*
> ```proto
> 
>   // Specifies a quantile
>   enum Quantile {
> ```

is this part of the MRC standard? 


<!-- Sent from Reviewable.io -->

2025-01-03 17:52 UTC, kungfucraig reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942)* status: all files reviewed, 6 unresolved discussions (waiting on @mariolamassaavedra and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/impression_qualification_filter_spec.proto` line 40 at r15](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-OFgxHtZEfx4IqW5F3GN:-OFhHYI4EpSI_5KXHpHg:b1m7wk3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/091a868bba8c30554e6ecf7f5def9367d4620058/src/main/proto/wfa/measurement/reporting/v2alpha/impression_qualification_filter_spec.proto#L40)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

is this part of the MRC standard?
</blockquote></details>

What do you mean?

I'd view having quantile as just syntactic sugar over specifying it as a fraction in the oneof below.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/page.proto` line 66 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-OFbgb-c5VoxFllUgkYH:-OFhHQHt9oSI3H0OS5Zk:bw5zfin) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ea2e849906bef880e4c39bd7f15e80eba25da81f/src/main/proto/wfa/measurement/reporting/v2alpha/page.proto#L66)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

It was previous a boolean. It's kind of weird as a boolean, because you'll have something called "cumulative" and it not being set means compute non-cumulative metrics. The boolean would make more sense if it mean compute cumulative metrics in addition to non-cumulative metrics.

I think this helps us keep our options open too, in the unlikely case we end up with a third value.
</blockquote></details>

It also requires that the user choose which they want vs. accepting a default.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/page.proto` line 174 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-OFbiyyk7Q4psphJwIYf:-OFhEQLM1KyKEmPu8e6t:b-ib6dgw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ea2e849906bef880e4c39bd7f15e80eba25da81f/src/main/proto/wfa/measurement/reporting/v2alpha/page.proto#L174)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

makes sense. I misread the comment previously. Are there scenarios where an advertiser would only want 3+ reach and nothing else?
</blockquote></details>

Maybe, but the complexity of the interface that is engendered by that doesn't seem worth it, especially since the system will compute the frequency histogram from 1 to 3 as a by product anyway. 

We are also moving toward precomputing a suite (i.e. a complete data cube) of metrics vs. requesting them one by one. See https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1988
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/page.proto` line 223 at r15](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-OFgxynZD4Y9aVbCWc1q:-OFhExz07zDscBHZTovN:bivc5gg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/091a868bba8c30554e6ecf7f5def9367d4620058/src/main/proto/wfa/measurement/reporting/v2alpha/page.proto#L223)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

nit: can you put TODO before all the future Phase stuff?
</blockquote></details>

I'll add a TODO and comment the fields out. Sound good?
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/page.proto` line 359 at r15](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-OFgyq1L9RY4ugy2O9Qm:-OFhF9NECkaziMGKkRbd:b-3fli8r) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/091a868bba8c30554e6ecf7f5def9367d4620058/src/main/proto/wfa/measurement/reporting/v2alpha/page.proto#L359)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

i assume we aren't going to worry about the over 2B problem?
</blockquote></details>

I can make it an int64 if you want, but a lot of other things will break before this does.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/page.proto` line 377 at r15](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-OFgyVo4A2-TYnhA0TMB:-OFhGaMf2hQWPYCF4oPd:b-sv37sl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/091a868bba8c30554e6ecf7f5def9367d4620058/src/main/proto/wfa/measurement/reporting/v2alpha/page.proto#L377)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

wouldn't a map be a better structure here?
</blockquote></details>

I'd say no. It's harder to work with and introduces the failure mode of a key not being present.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/reporting_impression_qualification_filter.proto` line 36 at r15](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-OFgzDQTCzULKILpnAgv:-OFhFZFt0fhc_UISfT72:b-nvuq2m) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/091a868bba8c30554e6ecf7f5def9367d4620058/src/main/proto/wfa/measurement/reporting/v2alpha/reporting_impression_qualification_filter.proto#L36)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

`Groups`

Also - there is not Media Type field on Event Group yet - https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/main/src/main/proto/wfa/measurement/api/v2alpha/event_group.proto
</blockquote></details>

Not yet, but there will be.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/reporting_unit.proto` line 46 at r15](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-OFgzw2LDjJzWc8sfBxz:-OFhFlVIEdvmyKFH40Ft:bjr2ceb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/091a868bba8c30554e6ecf7f5def9367d4620058/src/main/proto/wfa/measurement/reporting/v2alpha/reporting_unit.proto#L46)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

maybe I'm misunderstanding but a ReportingUnit should have results on all Media Types within a set of Event Groups preferable. Or imo, the Basic Report should strongly encourage that.
</blockquote></details>

The Reporting Unit may not have results for all media types. Two examples:
1) If a user creates a video only report, only results for video will be present.
2) When the underlying event groups don't contain events for all media types

See the "MediaType" filter on basic report and the comments on Reporting Impressing Qualification Filter.


<!-- Sent from Reviewable.io -->

2025-01-03 18:22 UTC, SanjayVas requested changes
> Reviewed 6 of 18 files at r12, 1 of 3 files at r13, 1 of 1 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942)* status: all files reviewed, 13 unresolved discussions (waiting on @kungfucraig, @mariolamassaavedra, and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/impression_qualification_filter.proto` line 29 at r15](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-OFhKJqQ1LgodFKB5Hv0:-OFhKJqQ1LgodFKB5Hv1:bb6x6qu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/091a868bba8c30554e6ecf7f5def9367d4620058/src/main/proto/wfa/measurement/reporting/v2alpha/impression_qualification_filter.proto#L29)):*
> ```proto
> // Resource representing an Impression Qualification Filter
> //
> // An ImpressionQualificationFilter (IRF) is a named collection of
> ```

IQF?



_Code quote:_
```proto
IRF
```
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/page.proto` line 30 at r15](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-OFhMqPi53rEBh763Fx4:-OFhMqPi53rEBh763Fx5:b-7sj33l) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/091a868bba8c30554e6ecf7f5def9367d4620058/src/main/proto/wfa/measurement/reporting/v2alpha/page.proto#L30)):*
> ```proto
> option java_outer_classname = "PageProto";
> 
> // Defines the windowing criteria for a set of Metrics including the time
> ```

nit: Describe what the symbol *is*, not what it *does*



_Suggestion:_
```proto
Specification of
```
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/page.proto` line 475 at r15](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-OFhO6RwEdheJcYVtYWy:-OFhO6RxBC0xQTgSbsgF:b-a63ovj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/091a868bba8c30554e6ecf7f5def9367d4620058/src/main/proto/wfa/measurement/reporting/v2alpha/page.proto#L475)):*
> ```proto
>   //
>   // This is either the resource name of an ImpressionQualificationResource or
>   // the string "custom" indicating that custom filters were applied.
> ```

Don't use a `map` type for this. Resource names fields need resource reference annotations. This means breaking it out into a repeated message with `key` and `value` fields so you can annotate the `key` field.

Split out the "custom" one to a separate optional field rather than using a magic/sentinel string.



_Code quote:_
```proto
  // This is either the resource name of an ImpressionQualificationResource or
  // the string "custom" indicating that custom filters were applied.
```
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric_frequency_spec.proto` line 34 at r15](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-OFhLqXG5sVHkE2mTwhG:-OFhLqXG5sVHkE2mTwhH:bf3djv4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/091a868bba8c30554e6ecf7f5def9367d4620058/src/main/proto/wfa/measurement/reporting/v2alpha/metric_frequency_spec.proto#L34)):*
> ```proto
>   // report partial weeks will reported for the first and/or last value
>   // in the result set.
>   message Weekly {
> ```

Why is this a separate message type? Why not

```proto
// The day of the week that metrics should be calculated with respect to. If not specified, metrics will not be calculated on a weekly basis.
google.type.DayOfWeek weekly_start_day = 1;
```
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric_frequency_spec.proto` line 43 at r15](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-OFhMXc36oNhCf-dyxke:-OFhMXc4ATNnzWTF3n6M:brbgbz9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/091a868bba8c30554e6ecf7f5def9367d4620058/src/main/proto/wfa/measurement/reporting/v2alpha/metric_frequency_spec.proto#L43)):*
> ```proto
>   // Report metrics weekly
>   Weekly weekly = 1 [(google.api.field_behavior) = IMMUTABLE];
>   // Report metrics across the entire reporting_interval
> ```

nit: The summary fragment should say what the symbol *is*, not what it *does*.



_Suggestion:_
```proto
Whether to report metrics across the entire `reporting_interval`.
```
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/basic_report.proto` line 65 at r15](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-OFhJiA5BXFNoDmKgXDa:-OFhJiA61KIbun9KZM-Z:b-4a4v9u) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/091a868bba8c30554e6ecf7f5def9367d4620058/src/main/proto/wfa/measurement/reporting/v2alpha/basic_report.proto#L65)):*
> ```proto
>   // The set of Media Types to filter the campaign_group on.
>   //
>   // These are applied as to the campaign group disjunctively.
> ```

nit: I don't understand this statement
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/basic_report.proto` line 87 at r15](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-OFhK0ik2pCPOGXhzEbM:-OFhK0il5hPB_-Wkxs86:bd0tipr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/091a868bba8c30554e6ecf7f5def9367d4620058/src/main/proto/wfa/measurement/reporting/v2alpha/basic_report.proto#L87)):*
> ```proto
>   ];
> 
>   // The results for each Page Definitions in the same order as the definitions.
> ```

Is this supposed to be referring to `page_specs`? If so, reference the field.



_Suggestion:_
```proto
  // The result for each item in `page_specs` in the same order.
```


<!-- Sent from Reviewable.io -->

2025-01-03 19:32 UTC, kungfucraig reviewed
> Reviewed 4 of 6 files at r16.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942)* status: 18 of 21 files reviewed, 10 unresolved discussions (waiting on @mariolamassaavedra, @SanjayVas, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/basic_report.proto` line 87 at r15](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-OFhK0ik2pCPOGXhzEbM:-OFhZK9rDg9fNIoL00uQ:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/091a868bba8c30554e6ecf7f5def9367d4620058/src/main/proto/wfa/measurement/reporting/v2alpha/basic_report.proto#L87)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Is this supposed to be referring to `page_specs`? If so, reference the field.
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/impression_qualification_filter.proto` line 29 at r15](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-OFhKJqQ1LgodFKB5Hv0:-OFhZQVuD4FxsCIU50ro:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/091a868bba8c30554e6ecf7f5def9367d4620058/src/main/proto/wfa/measurement/reporting/v2alpha/impression_qualification_filter.proto#L29)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

IQF?
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric_frequency_spec.proto` line 34 at r15](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-OFhLqXG5sVHkE2mTwhG:-OFhZXng777K9LaBd0j7:bqmv9b0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/091a868bba8c30554e6ecf7f5def9367d4620058/src/main/proto/wfa/measurement/reporting/v2alpha/metric_frequency_spec.proto#L34)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Why is this a separate message type? Why not

```proto
// The day of the week that metrics should be calculated with respect to. If not specified, metrics will not be calculated on a weekly basis.
google.type.DayOfWeek weekly_start_day = 1;
```
</blockquote></details>

The only reason to have it as a separate message to to provide flexibility in the future. I could go either way on this. If you feel strongly about it I'll change it.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/page.proto` line 475 at r15](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-OFhO6RwEdheJcYVtYWy:-OFhcARF0BjGL-PPCcpK:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/091a868bba8c30554e6ecf7f5def9367d4620058/src/main/proto/wfa/measurement/reporting/v2alpha/page.proto#L475)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Don't use a `map` type for this. Resource names fields need resource reference annotations. This means breaking it out into a repeated message with `key` and `value` fields so you can annotate the `key` field.

Split out the "custom" one to a separate optional field rather than using a magic/sentinel string.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2025-01-03 20:03 UTC, SanjayVas requested changes
> Reviewed 2 of 18 files at r12, 1 of 1 files at r14, 3 of 6 files at r16, 1 of 1 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942)* status: 19 of 21 files reviewed, 10 unresolved discussions (waiting on @kungfucraig, @mariolamassaavedra, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric_frequency_spec.proto` line 34 at r15](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-OFhLqXG5sVHkE2mTwhG:-OFhhoY09W08rZGMUa6j:b-47daq1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/091a868bba8c30554e6ecf7f5def9367d4620058/src/main/proto/wfa/measurement/reporting/v2alpha/metric_frequency_spec.proto#L34)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

The only reason to have it as a separate message to to provide flexibility in the future. I could go either way on this. If you feel strongly about it I'll change it.
</blockquote></details>

Depends on how likely you think this is to change, just like any other field. If you don't think it's likely, then avoid speculative code. Either way, the documentation needs to be updated a bit. Specifically, since this isn't a boolean field then you need to instead document what the field is and what happens when it's not specified.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/page.proto` line 474 at r17](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-OFhiShJ1qR7WJmueqij:-OFhiShJ1qR7WJmueqik:booiyek) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7e59110ab6adc8f92a34ab907cf81fe924144a8b/src/main/proto/wfa/measurement/reporting/v2alpha/page.proto#L474)):*
> ```proto
>   // that was applied when computing it.
>   message PageAndFilter {
>     // The filter. Required.
> ```

Did you want this to behave like a map, i.e. that you don't have duplicate keys? If so, I'd recommend both documenting that and also changing the structure a bit to make it more clear.

```proto
// Entry for the `pages` map.
message PagesMapEntry {
  // Map entry key.
  string key = 1 [
    (google.api.resource_reference) = {
      type: "reporting.halo-cmm.org/ImpressionQualificationFilter"
    },
    (google.api.field_behavior) = IMMUTABLE,
    (google.api.field_behavior) = REQUIRED
  ];

  // Map entry value.
  Page value = 2 [(google.api.field_behavior) = IMMUTABLE, (google.api.field_behavior) = REQUIRED];
}

// Map of `ImpressionQualificationFilter` to `Page`.
repeated PagesMapEntry pages = 1  [(google.api.field_behavior) = IMMUTABLE];

// The `Page` entry for a custom filter.
Page custom_filter_page = 2  [(google.api.field_behavior) = IMMUTABLE, (google.api.field_behavior) = OPTIONAL];
```
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/basic_report.proto` line 67 at r17](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-OFhgw-T2MyXwBt9VkyP:-OFhgw-T2MyXwBt9VkyQ:bz1ceoq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7e59110ab6adc8f92a34ab907cf81fe924144a8b/src/main/proto/wfa/measurement/reporting/v2alpha/basic_report.proto#L67)):*
> ```proto
>   repeated MediaType media_types = 5 [
>     (google.api.field_behavior) = REQUIRED,
>     (google.api.field_behavior) = IMMUTABLE
> ```

The comment describes this as a set. If this means that the order also doesn't matter, add the `UNORDERED_LIST` field behavior.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/impression_qualification_filters_service.proto` line 69 at r17](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-OFhhaoeBKJclL5BxgM5:-OFhhaoeBKJclL5BxgM6:b-3m8ayj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7e59110ab6adc8f92a34ab907cf81fe924144a8b/src/main/proto/wfa/measurement/reporting/v2alpha/impression_qualification_filters_service.proto#L69)):*
> ```proto
>   // If unspecified, at most 50 filters will be returned.
>   // The maximum value is 100; values above 100 will be coerced to 100.
>   int32 page_size = 2 [(google.api.field_behavior) = OPTIONAL];
> ```

nit: collapse field tag numbers


<!-- Sent from Reviewable.io -->

2025-01-03 20:34 UTC, kungfucraig reviewed
> Reviewed 2 of 6 files at r16, 3 of 4 files at r18, 1 of 1 files at r19.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942)* status: all files reviewed, 9 unresolved discussions (waiting on @mariolamassaavedra, @SanjayVas, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/basic_report.proto` line 67 at r17](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-OFhgw-T2MyXwBt9VkyP:-OFhocHL4c27swC3Ld6Q:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7e59110ab6adc8f92a34ab907cf81fe924144a8b/src/main/proto/wfa/measurement/reporting/v2alpha/basic_report.proto#L67)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The comment describes this as a set. If this means that the order also doesn't matter, add the `UNORDERED_LIST` field behavior.
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric_frequency_spec.proto` line 34 at r15](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-OFhLqXG5sVHkE2mTwhG:-OFhp-FT8fS8BeqDVeNJ:bo8wj9e) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/091a868bba8c30554e6ecf7f5def9367d4620058/src/main/proto/wfa/measurement/reporting/v2alpha/metric_frequency_spec.proto#L34)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Depends on how likely you think this is to change, just like any other field. If you don't think it's likely, then avoid speculative code. Either way, the documentation needs to be updated a bit. Specifically, since this isn't a boolean field then you need to instead document what the field is and what happens when it's not specified.
</blockquote></details>

Removed it. 
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/page.proto` line 474 at r17](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-OFhiShJ1qR7WJmueqij:-OFhlNiw6E2yrb_yE52Q:b-a9aenw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7e59110ab6adc8f92a34ab907cf81fe924144a8b/src/main/proto/wfa/measurement/reporting/v2alpha/page.proto#L474)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Did you want this to behave like a map, i.e. that you don't have duplicate keys? If so, I'd recommend both documenting that and also changing the structure a bit to make it more clear.

```proto
// Entry for the `pages` map.
message PagesMapEntry {
  // Map entry key.
  string key = 1 [
    (google.api.resource_reference) = {
      type: "reporting.halo-cmm.org/ImpressionQualificationFilter"
    },
    (google.api.field_behavior) = IMMUTABLE,
    (google.api.field_behavior) = REQUIRED
  ];

  // Map entry value.
  Page value = 2 [(google.api.field_behavior) = IMMUTABLE, (google.api.field_behavior) = REQUIRED];
}

// Map of `ImpressionQualificationFilter` to `Page`.
repeated PagesMapEntry pages = 1  [(google.api.field_behavior) = IMMUTABLE];

// The `Page` entry for a custom filter.
Page custom_filter_page = 2  [(google.api.field_behavior) = IMMUTABLE, (google.api.field_behavior) = OPTIONAL];
```
</blockquote></details>

We can do it that way, but I'm not convinced this is an improvement over the use of map<string, Page> with the sentinel value and no annotation.


<!-- Sent from Reviewable.io -->

2025-01-03 20:51 UTC, SanjayVas reviewed
> Reviewed 5 of 18 files at r12, 1 of 3 files at r13, 2 of 6 files at r16, 3 of 4 files at r18, 1 of 1 files at r19.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942)* status: all files reviewed, 8 unresolved discussions (waiting on @kungfucraig, @mariolamassaavedra, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/page.proto` line 474 at r17](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-OFhiShJ1qR7WJmueqij:-OFhsiot6j0q53sG0x-s:b-4g8k39) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7e59110ab6adc8f92a34ab907cf81fe924144a8b/src/main/proto/wfa/measurement/reporting/v2alpha/page.proto#L474)):*
> I'm not convinced this is an improvement over the use of map<string, Page> with the sentinel value and no annotation.

The use of the sentinel value and the lack of annotation are, in decreasing order of importance, the precise factors that make that option unviable.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/reporting_impression_qualification_filter.proto` line 62 at r19](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-OFhthmJCYK0zWp_przk:-OFhthmJCYK0zWp_przl:b-uemlu8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ba57118222b01e518c21c7876387eac470598869/src/main/proto/wfa/measurement/reporting/v2alpha/reporting_impression_qualification_filter.proto#L62)):*
> ```proto
>   // Specifies which filter to use. Required.
>   oneof filter {
>     // Specifies an ImpressionQualificationFilter.
> ```

nit: the old comment was better, as again the summary fragment of a type or field should not be a verb phrase. The only place a verb phrase should appear in a summary fragment documenting a symbol in a protobuf API definition is on a method.

This means that starting a field or message documentation with "Specifies" or "Defines" is never correct.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/reporting_interval.proto` line 28 at r19](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-OFhuiMMD5_7wUvPJo-l:-OFhuiMMD5_7wUvPJo-m:b1nd5mf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ba57118222b01e518c21c7876387eac470598869/src/main/proto/wfa/measurement/reporting/v2alpha/reporting_interval.proto#L28)):*
> ```proto
> 
> // The time interval over which Metrics are generated. This interval is
> // closed on both sides.
> ```

nit: the interval isn't actually closed on both sides, it's just that the end is specified as an inclusive date despite the interval being over time. It's actually forming an interval of `[start time, end time)`.

It may be clearer to describe it this way rather than saying that the end date is inclusive w.r.t. date but exclusive w.r.t. time.



_Code quote:_
```proto
// The time interval over which Metrics are generated. This interval is
// closed on both sides.
```


<!-- Sent from Reviewable.io -->

2025-01-03 20:59 UTC, stevenwarejones requested changes
> Reviewed 3 of 6 files at r16, 3 of 4 files at r18, 1 of 1 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942)* status: all files reviewed, 6 unresolved discussions (waiting on @kungfucraig, @mariolamassaavedra, and @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/impression_qualification_filter_spec.proto` line 40 at r15](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-OFgxHtZEfx4IqW5F3GN:-OFhuojt8x67nQ6-6yAE:b-xpk8y2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/091a868bba8c30554e6ecf7f5def9367d4620058/src/main/proto/wfa/measurement/reporting/v2alpha/impression_qualification_filter_spec.proto#L40)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

What do you mean?

I'd view having quantile as just syntactic sugar over specifying it as a fraction in the oneof below.
</blockquote></details>

Why quintile over quartiles? just wondering if one or the other is a formal/informal standard.

I see more references to using deciles or quartiles for completion. I can't find any references for using segments for viewability.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/impression_qualification_filter_spec.proto` line 66 at r19](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-OFhvrPvE832QGhl64fd:-OFhvrPvE832QGhl64fe:b-2g2vgu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ba57118222b01e518c21c7876387eac470598869/src/main/proto/wfa/measurement/reporting/v2alpha/impression_qualification_filter_spec.proto#L66)):*
> ```proto
>   }
> 
>   // Specifies the viewpability filter
> ```

This is a little confusing to me how viewability percent works. Viewability depends on two dimensions: % viewed and time.


<!-- Sent from Reviewable.io -->

2025-01-03 21:05 UTC, stevenwarejones requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942)* status: all files reviewed, 6 unresolved discussions (waiting on @kungfucraig, @mariolamassaavedra, and @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/reporting_unit.proto` line 46 at r15](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-OFgzw2LDjJzWc8sfBxz:-OFhy4VC05s9NHGk-583:brzptt7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/091a868bba8c30554e6ecf7f5def9367d4620058/src/main/proto/wfa/measurement/reporting/v2alpha/reporting_unit.proto#L46)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

The Reporting Unit may not have results for all media types. Two examples:
1) If a user creates a video only report, only results for video will be present.
2) When the underlying event groups don't contain events for all media types

See the "MediaType" filter on basic report and the comments on Reporting Impressing Qualification Filter.
</blockquote></details>

Its my understanding that a Basic Report will need to include data from all the media types of the included Event Groups. If the user  wants results from only one Media Type:
1. We'd need to flag errors if one of the included Event Groups does not contain that Media Type
2. Possibly only allow Media Type to be filtered out outside the Basic Report. wdyt?


<!-- Sent from Reviewable.io -->

2025-01-03 21:06 UTC, stevenwarejones requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942)* status: all files reviewed, 6 unresolved discussions (waiting on @kungfucraig, @mariolamassaavedra, and @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/reporting_unit.proto` line 46 at r15](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-OFgzw2LDjJzWc8sfBxz:-OFhzOga9J5stqFqSwxK:berejlo) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/091a868bba8c30554e6ecf7f5def9367d4620058/src/main/proto/wfa/measurement/reporting/v2alpha/reporting_unit.proto#L46)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

Its my understanding that a Basic Report will need to include data from all the media types of the included Event Groups. If the user  wants results from only one Media Type:
1. We'd need to flag errors if one of the included Event Groups does not contain that Media Type
2. Possibly only allow Media Type to be filtered out outside the Basic Report. wdyt?
</blockquote></details>

Media Type filtering seems more like an Advanced Report feature to me.


<!-- Sent from Reviewable.io -->

2025-01-03 22:44 UTC, kungfucraig reviewed
> Reviewed 2 of 2 files at r20, 1 of 2 files at r21.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942)* status: 20 of 21 files reviewed, 5 unresolved discussions (waiting on @mariolamassaavedra, @SanjayVas, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/impression_qualification_filter_spec.proto` line 40 at r15](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-OFgxHtZEfx4IqW5F3GN:-OFi8IWz7rT1dAVkGQgp:b-toko20) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/091a868bba8c30554e6ecf7f5def9367d4620058/src/main/proto/wfa/measurement/reporting/v2alpha/impression_qualification_filter_spec.proto#L40)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

Why quintile over quartiles? just wondering if one or the other is a formal/informal standard.

I see more references to using deciles or quartiles for completion. I can't find any references for using segments for viewability.
</blockquote></details>

These map to the Origin event template for percent completion: https://github.com/world-federation-of-advertisers/uk-pilot-event-templates/blob/main/src/main/proto/halo_cmm/uk/pilot/video_template.proto 

It's unrelated to the PR, but using booleans instead of floats for those event templates needs to be discussed. 
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/impression_qualification_filter_spec.proto` line 66 at r19](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-OFhvrPvE832QGhl64fd:-OFiKS2y3_jLYwQJD3pt:b-5xu0yu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ba57118222b01e518c21c7876387eac470598869/src/main/proto/wfa/measurement/reporting/v2alpha/impression_qualification_filter_spec.proto#L66)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

This is a little confusing to me how viewability percent works. Viewability depends on two dimensions: % viewed and time.
</blockquote></details>

Let's discuss this on Monday. I think we need to improve the event templates. See: https://github.com/world-federation-of-advertisers/uk-pilot-event-templates/blob/main/src/main/proto/halo_cmm/uk/pilot/display_template.proto#L24
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/reporting_interval.proto` line 28 at r19](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-OFhuiMMD5_7wUvPJo-l:-OFiGO-sEuKB2saP1zRA:b-rw3n51) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ba57118222b01e518c21c7876387eac470598869/src/main/proto/wfa/measurement/reporting/v2alpha/reporting_interval.proto#L28)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: the interval isn't actually closed on both sides, it's just that the end is specified as an inclusive date despite the interval being over time. It's actually forming an interval of `[start time, end time)`.

It may be clearer to describe it this way rather than saying that the end date is inclusive w.r.t. date but exclusive w.r.t. time.
</blockquote></details>

Decided to drop the second sentence. The documentation of the individual fields is adequate to describe what is going on.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/reporting_unit.proto` line 46 at r15](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-OFgzw2LDjJzWc8sfBxz:-OFiGhKeE_pJDFZ4GbhB:b-epfhb0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/091a868bba8c30554e6ecf7f5def9367d4620058/src/main/proto/wfa/measurement/reporting/v2alpha/reporting_unit.proto#L46)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

Media Type filtering seems more like an Advanced Report feature to me.
</blockquote></details>

Let's discuss Monday. I'm open to dropping it.


<!-- Sent from Reviewable.io -->

2025-01-06 18:21 UTC, stevenwarejones requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942)* status: 20 of 21 files reviewed, 5 unresolved discussions (waiting on @kungfucraig, @mariolamassaavedra, and @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/page.proto` line 231 at r19](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-OFwqImo5Tl07FZ2wGoX:-OFwqImo5Tl07FZ2wGoY:b-rocq97) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ba57118222b01e518c21c7876387eac470598869/src/main/proto/wfa/measurement/reporting/v2alpha/page.proto#L231)):*
> ```proto
>     // For cumulative metrics this is the same as unique_reach.
>     // Phase III
>     bool new_unique_reach = 4 [(google.api.field_behavior) = IMMUTABLE];
> ```

why are all these deleted now?


<!-- Sent from Reviewable.io -->

2025-01-06 18:51 UTC, SanjayVas approved these changes
> Reviewed 1 of 18 files at r12, 1 of 2 files at r20, 2 of 2 files at r21, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942)* status: all files reviewed, 5 unresolved discussions (waiting on @kungfucraig, @mariolamassaavedra, @stevenwarejones, and @tristanvuong2021)



<!-- Sent from Reviewable.io -->

2025-01-07 23:26 UTC, SanjayVas requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942)* status: 19 of 21 files reviewed, 6 unresolved discussions (waiting on @kungfucraig, @mariolamassaavedra, @stevenwarejones, and @tristanvuong2021)

___
*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-OG24aWi8626p6RRs8ND:-OG24aWj7_Rj1EHDxJ2H:b-8ze75d) (no related file):*
I assume this PR is now just for Phase II, where #1993 is Phase I? If so, make sure you base this PR branch on `kungfucraig/mcapiphaseone` and set the base branch on the PR in GitHub. That way this PR only shows the diffs from Phase II.


<!-- Sent from Reviewable.io -->

2025-01-08 02:58 UTC, kungfucraig reviewed
> Reviewed 1 of 2 files at r22, 18 of 19 files at r23, 1 of 1 files at r24, 2 of 2 files at r25, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942)* status: all files reviewed, 6 unresolved discussions (waiting on @mariolamassaavedra, @SanjayVas, @stevenwarejones, and @tristanvuong2021)

___
*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-OG24aWi8626p6RRs8ND:-OG2jpYe8PKhhP6EzDCa:b-5otw3k) (no related file):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I assume this PR is now just for Phase II, where #1993 is Phase I? If so, make sure you base this PR branch on `kungfucraig/mcapiphaseone` and set the base branch on the PR in GitHub. That way this PR only shows the diffs from Phase II.
</blockquote></details>

Done. There are still some odd artifacts hanging around, which I cannot explain or seem to get rid of, but it's pretty clean wrt the upstream branch.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/page.proto` line 231 at r19](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1942#-OFwqImo5Tl07FZ2wGoX:-OG2czrY4rw-HEKT_Cyo:boy8a4v) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ba57118222b01e518c21c7876387eac470598869/src/main/proto/wfa/measurement/reporting/v2alpha/page.proto#L231)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

why are all these deleted now?
</blockquote></details>

See the phase III PR.


<!-- Sent from Reviewable.io -->

2025-01-08 18:20 UTC, kungfucraig commented
See: https://github.com/world-federation-of-advertisers/cross-media-measurement/pull/1994

2025-01-08 18:20 UTC, closed without merging