feat: Adds the Google PubSub terraform script.
world-federation-of-advertisers/cross-media-measurement pull request #1946
Opened 2024-12-03 08:38 UTC by Marco-Premier

2024-12-03 08:38 UTC, wfa-reviewable commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1946)
<!-- Reviewable:end -->

2024-12-03 19:56 UTC, SanjayVas requested changes
PR titles should be imperative sentences (e.g. "Add" not "Adds"). I took the liberty of fixing this one for you. See https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/docs/dev-standards.md#pull-request-description

> Reviewed 2 of 6 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1946#-:-ODCzrnJB9702ZFLXegC:b-dp2de1)* status: all files reviewed, 3 unresolved discussions (waiting on @kungfucraig, @Marco-Premier, and @stevenwarejones)

___
*[`src/main/terraform/gcloud/examples/control-plane/main.tf` line 1 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1946#-ODD06d_Ae3iK7XTFaXW:-ODD06d_Ae3iK7XTFaXX:b-e58szm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e2a081472d5be9f75ed87ba1100e66368e6bb21f/src/main/terraform/gcloud/examples/control-plane/main.tf#L1)):*
> ```HCL
> # Copyright 2024 The Cross-Media Measurement Authors
> ```

It's premature to add this example, as the example should be for a specific usage/component such as the EDP aggregator or TEE Duchy. Meaning that we'd e.g. have another module for the EDP aggregator that uses the TEE control plane module, and the example would be for that.
___
*[`src/main/terraform/gcloud/control-plane/main.tf` line 1 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1946#-ODD-Qg-4byLkIpe3_D2:-ODD-Qg-4byLkIpe3_D3:b-jo5ebv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e2a081472d5be9f75ed87ba1100e66368e6bb21f/src/main/terraform/gcloud/control-plane/main.tf#L1)):*
> ```HCL
> # Copyright 2023 The Cross-Media Measurement Authors
> ```

This should be part of the `cmms` root module, which covers everything we put into Halo test environments.
___
*[`src/main/terraform/gcloud/modules/control-plane/main.tf` line 1 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1946#-ODD-lUU7awOdjL-t8l6:-ODD-lUU7awOdjL-t8l7:b1u400o) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e2a081472d5be9f75ed87ba1100e66368e6bb21f/src/main/terraform/gcloud/modules/control-plane/main.tf#L1)):*
> ```HCL
> # Copyright 2024 The Cross-Media Measurement Authors
> ```

This module name is too generic. Control plane for what?


<!-- Sent from Reviewable.io -->

2024-12-04 17:01 UTC, Marco-Premier reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1946)* status: all files reviewed, 3 unresolved discussions (waiting on @kungfucraig, @SanjayVas, and @stevenwarejones)

___
*[`src/main/terraform/gcloud/control-plane/main.tf` line 1 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1946#-ODD-Qg-4byLkIpe3_D2:-ODHXkKxCIRZ72vcT8pa:b60k7yc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e2a081472d5be9f75ed87ba1100e66368e6bb21f/src/main/terraform/gcloud/control-plane/main.tf#L1)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This should be part of the `cmms` root module, which covers everything we put into Halo test environments.
</blockquote></details>

I created a secure_computation.tf file where I will add in following PRs all infra needed for the secure computation kotlin package.

i.e.

- storages
- pubsub
- cloud functions
- mig

I thought also to `edp_aggregator` as a name but I think that mig for instance is not really part of that, wyt?
___
*[`src/main/terraform/gcloud/examples/control-plane/main.tf` line 1 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1946#-ODD06d_Ae3iK7XTFaXW:-ODHYD052P93yZ-Sfi8R:bb71kmx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e2a081472d5be9f75ed87ba1100e66368e6bb21f/src/main/terraform/gcloud/examples/control-plane/main.tf#L1)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

It's premature to add this example, as the example should be for a specific usage/component such as the EDP aggregator or TEE Duchy. Meaning that we'd e.g. have another module for the EDP aggregator that uses the TEE control plane module, and the example would be for that.
</blockquote></details>

Okay
___
*[`src/main/terraform/gcloud/modules/control-plane/main.tf` line 1 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1946#-ODD-lUU7awOdjL-t8l6:-ODHaVvQAEqDggLjBQZO:b544fzl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e2a081472d5be9f75ed87ba1100e66368e6bb21f/src/main/terraform/gcloud/modules/control-plane/main.tf#L1)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This module name is too generic. Control plane for what?
</blockquote></details>

Renamed it to `pubsub`, I'll create other modules for:

- mig
- cloud functions 


<!-- Sent from Reviewable.io -->

2024-12-04 19:22 UTC, SanjayVas requested changes
> Reviewed 7 of 7 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1946)* status: all files reviewed, 5 unresolved discussions (waiting on @kungfucraig, @Marco-Premier, and @stevenwarejones)

___
*[`src/main/terraform/gcloud/control-plane/main.tf` line 1 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1946#-ODD-Qg-4byLkIpe3_D2:-ODI-jaf26r-V6Zu640H:b-e207l6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e2a081472d5be9f75ed87ba1100e66368e6bb21f/src/main/terraform/gcloud/control-plane/main.tf#L1)):*
This is fine for now, but I do actually think we'll end up with separate modules or examples for the EDP aggregator vs. the TEE-based Duchy. While we'll want to exercise everything in Halo test environments, different entities may want to deploy these separately. For example, an EDP hosting their own private aggregator instance.

> I thought also to `edp_aggregator` as a name but I think that mig for instance is not really part of that, wyt?

I haven't kept up on the scaling discussion in the design doc, but I thought that one of the options was to have each queue responsible for spinning up its own MIGs dynamically. At the very least, I assumed there would be a separate MIG for each queue since each queue processes a different type of workload and therefore has its own VM requirements.
___
*[`src/main/terraform/gcloud/modules/pubsub/main.tf` line 1 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1946#-ODI4Rzv9Of9QB2co6p2:-ODI4Rzw495YEbgtgkNl:buegafb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/951275a4b62c96887548c181b68df49235b2bcc0/src/main/terraform/gcloud/modules/pubsub/main.tf#L1)):*
> ```HCL
> # Copyright 2024 The Cross-Media Measurement Authors
> ```

This looks like it's intended to be a generic reusable module for pubsub subscriptions, in which case it should have a README.md file. By Terraform convention, externally reusable modules have READMEs. This is also noted in the [README for the `modules` directory](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/main/terraform/gcloud/modules/README.md).
___
*[`src/main/terraform/gcloud/cmms/secure_computation.tf` line 15 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1946#-ODI-Sxi4PQ0dyDwd2ZA:-ODI-Sxj5uEdatbPjQQ8:b-ribmjo) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/951275a4b62c96887548c181b68df49235b2bcc0/src/main/terraform/gcloud/cmms/secure_computation.tf#L15)):*
> ```HCL
> # limitations under the License.
> 
> terraform {
> ```

Leave out the backend and provider since these are already defined in main.tf. In particular, this uses the same TF state as the rest of the root module.
___
*[`src/main/terraform/gcloud/modules/pubsub/variables.tf` line 17 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1946#-ODI33D94JWtq_y4X2_f:-ODI33D94JWtq_y4X2_g:b-v69d0r) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/951275a4b62c96887548c181b68df49235b2bcc0/src/main/terraform/gcloud/modules/pubsub/variables.tf#L17)):*
> ```HCL
> variable "topic_name" {
>   description = "Name of the Pub/Sub topic"
>   type        = string
> ```

I assume you want `nullable = false` here to indicate that it's required and non-null.
___
*[`src/main/terraform/gcloud/modules/pubsub/variables.tf` line 34 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1946#-ODI2onLD5ztz6fJaLhW:-ODI2onLD5ztz6fJaLhX:b7qe9ny) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/951275a4b62c96887548c181b68df49235b2bcc0/src/main/terraform/gcloud/modules/pubsub/variables.tf#L34)):*
> ```HCL
>   description = "The duration (in seconds) for which Pub/Sub retains unacknowledged messages."
>   type        = string
>   default     = "86400s"
> ```

Why do we have our own defaults for these optional fields? Meaning is there a reason that Halo Pub/Sub topic/subscription pairs want these specific values, or can we instead just rely on the defaults from the resource type (i.e. make these default to null)?

Note that this module name indicates that it's generically for Pub/Sub, so it should only have defaults that differ from those in the resource if they can apply generally to most Pub/Sub subscriptions that Halo would use (including those not for TEE).


<!-- Sent from Reviewable.io -->

2024-12-09 17:17 UTC, Marco-Premier reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1946)* status: 4 of 8 files reviewed, 5 unresolved discussions (waiting on @kungfucraig, @SanjayVas, and @stevenwarejones)

___
*[`src/main/terraform/gcloud/modules/pubsub/main.tf` line 1 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1946#-ODI4Rzv9Of9QB2co6p2:-ODQ9c2wCxMF99H2H5_1:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/951275a4b62c96887548c181b68df49235b2bcc0/src/main/terraform/gcloud/modules/pubsub/main.tf#L1)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This looks like it's intended to be a generic reusable module for pubsub subscriptions, in which case it should have a README.md file. By Terraform convention, externally reusable modules have READMEs. This is also noted in the [README for the `modules` directory](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/main/terraform/gcloud/modules/README.md).
</blockquote></details>

Done.
___
*[`src/main/terraform/gcloud/cmms/secure_computation.tf` line 15 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1946#-ODI-Sxi4PQ0dyDwd2ZA:-ODQ6nhl1odm1o6qCfxD:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/951275a4b62c96887548c181b68df49235b2bcc0/src/main/terraform/gcloud/cmms/secure_computation.tf#L15)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Leave out the backend and provider since these are already defined in main.tf. In particular, this uses the same TF state as the rest of the root module.
</blockquote></details>

Done.
___
*[`src/main/terraform/gcloud/control-plane/main.tf` line 1 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1946#-ODD-Qg-4byLkIpe3_D2:-ODQ66in0OVwjIdnappo:b-fxcji8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e2a081472d5be9f75ed87ba1100e66368e6bb21f/src/main/terraform/gcloud/control-plane/main.tf#L1)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This is fine for now, but I do actually think we'll end up with separate modules or examples for the EDP aggregator vs. the TEE-based Duchy. While we'll want to exercise everything in Halo test environments, different entities may want to deploy these separately. For example, an EDP hosting their own private aggregator instance.

> I thought also to `edp_aggregator` as a name but I think that mig for instance is not really part of that, wyt?

I haven't kept up on the scaling discussion in the design doc, but I thought that one of the options was to have each queue responsible for spinning up its own MIGs dynamically. At the very least, I assumed there would be a separate MIG for each queue since each queue processes a different type of workload and therefore has its own VM requirements.
</blockquote></details>

that's is what we agreed upon yes, 1 mig per queue/app-version. 
___
*[`src/main/terraform/gcloud/modules/pubsub/variables.tf` line 17 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1946#-ODI33D94JWtq_y4X2_f:-ODQ90l9659V6PsczHc1:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/951275a4b62c96887548c181b68df49235b2bcc0/src/main/terraform/gcloud/modules/pubsub/variables.tf#L17)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I assume you want `nullable = false` here to indicate that it's required and non-null.
</blockquote></details>

Done.
___
*[`src/main/terraform/gcloud/modules/pubsub/variables.tf` line 34 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1946#-ODI2onLD5ztz6fJaLhW:-ODQ8QZy6UOBr-8rR_z7:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/951275a4b62c96887548c181b68df49235b2bcc0/src/main/terraform/gcloud/modules/pubsub/variables.tf#L34)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Why do we have our own defaults for these optional fields? Meaning is there a reason that Halo Pub/Sub topic/subscription pairs want these specific values, or can we instead just rely on the defaults from the resource type (i.e. make these default to null)?

Note that this module name indicates that it's generically for Pub/Sub, so it should only have defaults that differ from those in the resource if they can apply generally to most Pub/Sub subscriptions that Halo would use (including those not for TEE).
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2025-01-10 13:20 UTC, Marco-Premier reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1946)* status: 4 of 8 files reviewed, 5 unresolved discussions (waiting on @kungfucraig, @SanjayVas, and @stevenwarejones)

___
*[`src/main/terraform/gcloud/modules/pubsub/variables.tf` line 27 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1946#-ODgs6Be8EimNjvEwO9X:-OGFJeutBcYc1B7Nxxc5:br0j19d) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/05a604dde6bf6c5b40a95541a3696d2b65f807a7/src/main/terraform/gcloud/modules/pubsub/variables.tf#L27)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

It looks like you having this applying to the subscription, but the field could also apply to the topic. Want to qualify it? 
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/pubsub_topic

Or maybe we should have a separate modules for subscription and topic registration?

They seem fairly independent, and this is how TF has it anyway.
</blockquote></details>

I'm open to this but the 2 `message_retention_duration` works at different level. The one for the sub indicates for how long a message is kept in the queue waiting for a subscriber to process it (7days as default).

The one at topic level is used to enable the "seek feature" (https://cloud.google.com/pubsub/docs/replay-overview) which enables messages to be stored and let subscription to seek back for a particular message even after it was acknowledge.

Since we don't have this feature enable, shall we use a single module for now? I'd like to minimize fragmentation and have a single module for pubsub as long as it covers our use cases.


<!-- Sent from Reviewable.io -->

2025-01-10 23:12 UTC, kungfucraig requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1946)* status: 4 of 8 files reviewed, 5 unresolved discussions (waiting on @SanjayVas and @stevenwarejones)

___
*[`src/main/terraform/gcloud/modules/pubsub/variables.tf` line 27 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1946#-ODgs6Be8EimNjvEwO9X:-OGHU0C_Bq7_CU-PrVdV:b-vlsc8n) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/05a604dde6bf6c5b40a95541a3696d2b65f807a7/src/main/terraform/gcloud/modules/pubsub/variables.tf#L27)):*
<details><summary><i>Previously, Marco-Premier (marcopremier) wrote…</i></summary><blockquote>

I'm open to this but the 2 `message_retention_duration` works at different level. The one for the sub indicates for how long a message is kept in the queue waiting for a subscriber to process it (7days as default).

The one at topic level is used to enable the "seek feature" (https://cloud.google.com/pubsub/docs/replay-overview) which enables messages to be stored and let subscription to seek back for a particular message even after it was acknowledge.

Since we don't have this feature enable, shall we use a single module for now? I'd like to minimize fragmentation and have a single module for pubsub as long as it covers our use cases.
</blockquote></details>

I don't have a deep understanding of TF best practices and practical implications of this decision. However, convoluting things tends to lead to problems. @SanjayVas wdyt?


<!-- Sent from Reviewable.io -->

2025-01-14 00:35 UTC, SanjayVas requested changes
> Reviewed 1 of 4 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1946)* status: 7 of 8 files reviewed, 2 unresolved discussions (waiting on @Marco-Premier and @stevenwarejones)

___
*[`src/main/terraform/gcloud/modules/pubsub/variables.tf` line 34 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1946#-ODI2onLD5ztz6fJaLhW:-OGXC9P36pDvtqrx6zFM:bltlljm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/951275a4b62c96887548c181b68df49235b2bcc0/src/main/terraform/gcloud/modules/pubsub/variables.tf#L34)):*
<details><summary><i>Previously, Marco-Premier (marcopremier) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not having our own defaults doesn't mean copying other default values, but rather having these be nullable and defaulting to null so we get the default from the underlying resource type.

At that point, I'm not terribly certain I'm seeing the usefulness of this module over just using the underlying resources. Our other modules do something, such as combining resources that are used together (e.g. service account and membership for workload identity users) or setting our opinionated values (e.g. settings we want on *every* cluster or node pool)


<!-- Sent from Reviewable.io -->

2025-01-15 10:34 UTC, Marco-Premier reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1946)* status: 5 of 8 files reviewed, 2 unresolved discussions (waiting on @SanjayVas and @stevenwarejones)

___
*[`src/main/terraform/gcloud/modules/pubsub/variables.tf` line 34 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1946#-ODI2onLD5ztz6fJaLhW:-OGdWbjU2JAv0eFuE7pg:bozdpjw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/951275a4b62c96887548c181b68df49235b2bcc0/src/main/terraform/gcloud/modules/pubsub/variables.tf#L34)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Not having our own defaults doesn't mean copying other default values, but rather having these be nullable and defaulting to null so we get the default from the underlying resource type.

At that point, I'm not terribly certain I'm seeing the usefulness of this module over just using the underlying resources. Our other modules do something, such as combining resources that are used together (e.g. service account and membership for workload identity users) or setting our opinionated values (e.g. settings we want on *every* cluster or node pool)
</blockquote></details>

my bad! I wasn't sure that null was treated as missing value in order to fallback to terraform default values


<!-- Sent from Reviewable.io -->

2025-01-15 22:03 UTC, SanjayVas approved these changes
> Reviewed 1 of 4 files at r4, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1946)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)



<!-- Sent from Reviewable.io -->

2025-01-17 13:49 UTC, stevenwarejones approved these changes
> Reviewed 1 of 6 files at r1, 2 of 4 files at r2, 4 of 7 files at r3, 1 of 4 files at r4, 1 of 2 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1946)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/terraform/gcloud/modules/pubsub/variables.tf` line 27 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1946#-ODgs6Be8EimNjvEwO9X:-OGoWYncDmKywQnt6R6-:b-5zsm14) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/05a604dde6bf6c5b40a95541a3696d2b65f807a7/src/main/terraform/gcloud/modules/pubsub/variables.tf#L27)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

I don't have a deep understanding of TF best practices and practical implications of this decision. However, convoluting things tends to lead to problems. @SanjayVas wdyt?
</blockquote></details>

so, this is for subscription right? just rename to `subscription_queue_retention_period` or `subscription_message_retention_period1?


<!-- Sent from Reviewable.io -->

2025-01-17 13:59 UTC, Marco-Premier reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1946)* status: 6 of 8 files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @stevenwarejones)

___
*[`src/main/terraform/gcloud/modules/pubsub/variables.tf` line 27 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1946#-ODgs6Be8EimNjvEwO9X:-OGoYTeN0pq6817Vznfs:bozrmyu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/05a604dde6bf6c5b40a95541a3696d2b65f807a7/src/main/terraform/gcloud/modules/pubsub/variables.tf#L27)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

so, this is for subscription right? just rename to `subscription_queue_retention_period` or `subscription_message_retention_period1?
</blockquote></details>

Exactly, this indicates for how long a message (default 7 days) is retained in the subscription queue waiting to be acked.
If after this period the message still has o receive an acknowledge it is removed from the queue (and so not deliverable anymore).


<!-- Sent from Reviewable.io -->

2025-01-22 13:58 UTC, Marco-Premier reviewed
> Dismissed @kungfucraig from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1946)* status: 6 of 8 files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2025-01-22 13:58 UTC, Marco-Premier reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1946#-:-OHDIcMsCg5uX-GXRx1D:bnfp4nl)* status: 6 of 8 files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2025-01-22 16:37 UTC, kungfucraig approved these changes
> Reviewed 2 of 7 files at r3, 1 of 4 files at r4, 1 of 2 files at r5, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1946)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Marco-Premier)



<!-- Sent from Reviewable.io -->

2025-01-23 13:59 UTC, merged