feat: Report processor switches to osqp when highs solver fails to converge.
world-federation-of-advertisers/cross-media-measurement pull request #1976
Opened 2024-12-18 21:31 UTC by ple13

2024-12-18 21:31 UTC, wfa-reviewable commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1976)
<!-- Reviewable:end -->

2024-12-19 22:19 UTC, kungfucraig requested changes
You should have some tests.

> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1976#-:-OEVzv-M4ihqHutSQaSU:b-r7h9p4)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @ple13)

___
*[`src/main/python/wfa/measurement/reporting/postprocessing/noiseninja/solver.py` line 155 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1976#-OEVzfTe5sp0V1KsEjAL:-OEVzfTf8BzfQaUhAFdK:bsus6yo) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0faca73fdcb2df54bf71f4bffc22273d55c04a1f/src/main/python/wfa/measurement/reporting/postprocessing/noiseninja/solver.py#L155)):*
> ```Python
>   def _solve_with_initial_value(self, solver_name, x0) -> Solution:
>     problem = self._problem()
>     solution = solve_problem(problem, solver=solver_name, initvals=x0, verbose=False)
> ```

nit: Maybe just write out "initial_values" 

Otherwise at least put an underscore between the words.
___
*[`src/main/python/wfa/measurement/reporting/postprocessing/noiseninja/solver.py` line 158 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1976#-OEW-FGg8rNbd5k9hM_Q:-OEW-FGg8rNbd5k9hM_R:baxccx1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0faca73fdcb2df54bf71f4bffc22273d55c04a1f/src/main/python/wfa/measurement/reporting/postprocessing/noiseninja/solver.py#L158)):*
> ```Python
>     return solution
> 
>   def _problem(self):
> ```

While you're in here you may as well add some logging about each attempt.
___
*[`src/main/python/wfa/measurement/reporting/postprocessing/noiseninja/solver.py` line 189 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1976#-OEW-8Dh6n8R115Gx2YS:-OEW-8Dh6n8R115Gx2YT:bbpbp12) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0faca73fdcb2df54bf71f4bffc22273d55c04a1f/src/main/python/wfa/measurement/reporting/postprocessing/noiseninja/solver.py#L189)):*
> ```Python
>           attempt_count += 1
> 
>       # If the highs solver does not converge, switch to the osqp solver which
> ```

So solve with HIGHS for 10 attempts and if those fail, try just once with OSPQ?


<!-- Sent from Reviewable.io -->

2024-12-20 16:12 UTC, kungfucraig requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1976)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @ple13)

___
*[`src/main/python/wfa/measurement/reporting/postprocessing/noiseninja/solver.py` line 189 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1976#-OEW-8Dh6n8R115Gx2YS:-OEZjNRn-H9wXJAfoDUi:bqzdtkj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0faca73fdcb2df54bf71f4bffc22273d55c04a1f/src/main/python/wfa/measurement/reporting/postprocessing/noiseninja/solver.py#L189)):*
<details><summary><i>Previously, ple13 (Phi) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Sorry. My comment was ambiguous. 

Why try 10 times with the other one and just once with this one? 

With respect to the comment you added, you noted it was more robust, so you should explain why we don't use it to start with.


<!-- Sent from Reviewable.io -->

2025-01-08 00:58 UTC, kungfucraig requested changes
> Reviewed 1 of 2 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1976)* status: all files reviewed, 3 unresolved discussions (waiting on @ple13 and @stevenwarejones)

___
*[`src/main/python/wfa/measurement/reporting/postprocessing/noiseninja/solver.py` line 158 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1976#-OEW-FGg8rNbd5k9hM_Q:-OG2P9ve46DBE505hEDg:b32wwp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0faca73fdcb2df54bf71f4bffc22273d55c04a1f/src/main/python/wfa/measurement/reporting/postprocessing/noiseninja/solver.py#L158)):*
<details><summary><i>Previously, ple13 (Phi) wrote…</i></summary><blockquote>

I have the PR#1878 to handle the log. I'll have the logs included in that PR (after this PR has been merged). WDYT?
</blockquote></details>

sg
___
*[`src/main/python/wfa/measurement/reporting/postprocessing/noiseninja/solver.py` line 189 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1976#-OEW-8Dh6n8R115Gx2YS:-OG2Pn0UBzAywPymBZ7X:b-783o3z) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0faca73fdcb2df54bf71f4bffc22273d55c04a1f/src/main/python/wfa/measurement/reporting/postprocessing/noiseninja/solver.py#L189)):*
<details><summary><i>Previously, ple13 (Phi) wrote…</i></summary><blockquote>

I'm sorry I didn't explain this better. The reason why I didn't try 10 times is because I thought the osqp solver was deterministic given the initial values. However, it is also a randomization process due to some non-deterministic internal states. I've added more comments to explain why we go for the highs solver first even though osqp is more robust (page 3 in https://arxiv.org/pdf/1711.08013 discusses first-order method (like osqp) vs others and suggests that osqp is less accurate.)
</blockquote></details>

Thanks for the updated documentation.
___
*[`src/main/python/wfa/measurement/reporting/postprocessing/noiseninja/solver.py` line 158 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1976#-OG2PcuF61GM8keh31WU:-OG2PcuF61GM8keh31WV:b2v043g) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/731182b642ca02db714ff33be1c8cc14b1502eb5/src/main/python/wfa/measurement/reporting/postprocessing/noiseninja/solver.py#L158)):*
> ```Python
>     self.h.append([0])
> 
>   def _solve_with_initial_value(self, solver_name, initial_values) -> Solution:
> ```

Add type annotations for args.
___
*[`src/main/python/wfa/measurement/reporting/postprocessing/noiseninja/solver.py` line 179 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1976#-OG2PE1u7g7i16MkQvxa:-OG2PE1u7g7i16MkQvxb:b-70jcno) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/731182b642ca02db714ff33be1c8cc14b1502eb5/src/main/python/wfa/measurement/reporting/postprocessing/noiseninja/solver.py#L179)):*
> ```Python
>     attempt_count = 0
>     while attempt_count < MAX_ATTEMPTS:
>       # TODO: check if qpsolvers is thread safe,
> ```

I would not expect it to be thread safe, but how are you calling it in parallel? 

Can this TODO be addressed before merging?


<!-- Sent from Reviewable.io -->

2025-01-09 01:09 UTC, jojijac0b approved these changes
> Reviewed 1 of 2 files at r3, 2 of 3 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1976)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)



<!-- Sent from Reviewable.io -->

2025-01-09 19:01 UTC, merged