feat: implement Roles public api
world-federation-of-advertisers/cross-media-measurement pull request #1980
Opened 2024-12-20 02:02 UTC by roaminggypsy

2024-12-20 02:02 UTC, wfa-reviewable commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1980)
<!-- Reviewable:end -->

2024-12-20 19:18 UTC, SanjayVas requested changes
> Reviewed 4 of 6 files at r1, 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1980)* status: 5 of 6 files reviewed, 6 unresolved discussions (waiting on @roaminggypsy)

___
*[`src/main/kotlin/org/wfanet/measurement/access/service/v1alpha/RolesService.kt` line 64 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1980#-OE_T8hn49OvemV5DX0u:-OE_T8hn49OvemV5DX0v:b-prog9k) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a6600fd11b62e9d4d1516fe54f6f433d5e508d4d/src/main/kotlin/org/wfanet/measurement/access/service/v1alpha/RolesService.kt#L64)):*
> ```Kotlin
>           .asStatusRuntimeException(Status.Code.INVALID_ARGUMENT)
> 
>     val internalResponse =
> ```

nit: specify types when not obvious/redundant (i.e. when the type isn't mentioned on the right side of the assignment)



_Suggestion:_
```Kotlin
val internalResponse: InternalRole
```
___
*[`src/main/kotlin/org/wfanet/measurement/access/service/v1alpha/RolesService.kt` line 68 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1980#-OE_Tbxc4DfrlWdsgWT8:-OE_Tbxc4DfrlWdsgWT9:b-eodr2t) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a6600fd11b62e9d4d1516fe54f6f433d5e508d4d/src/main/kotlin/org/wfanet/measurement/access/service/v1alpha/RolesService.kt#L68)):*
> ```Kotlin
>         internalRolesStub.getRole(internalGetRoleRequest { roleResourceId = key.roleId })
>       } catch (e: StatusException) {
>         val exception: StatusRuntimeException =
> ```

nit: unnecessary variable. You can just throw the result of the `when` expression.
___
*[`src/main/kotlin/org/wfanet/measurement/access/service/v1alpha/RolesService.kt` line 99 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1980#-OE_S-9_-IXcb3pNnp-v:-OE_S-9a0_k2HEaxqHcS:b4z8377) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a6600fd11b62e9d4d1516fe54f6f433d5e508d4d/src/main/kotlin/org/wfanet/measurement/access/service/v1alpha/RolesService.kt#L99)):*
> ```Kotlin
>   override suspend fun listRoles(request: ListRolesRequest): ListRolesResponse {
>     if (request.pageSize < 0) {
>       throw InvalidFieldValueException("page_size")
> ```

nit: Pass more information when you can



_Suggestion:_
```Kotlin
InvalidFieldValueException("page_size") { fieldName -> "$fieldName cannot be negative" }
```
___
*[`src/main/kotlin/org/wfanet/measurement/access/service/v1alpha/RolesService.kt` line 104 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1980#-OE_RPgl1om6zxNGyy_o:-OE_R5v08oxF6_Yw2Kpq:b-o6lsxk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a6600fd11b62e9d4d1516fe54f6f433d5e508d4d/src/main/kotlin/org/wfanet/measurement/access/service/v1alpha/RolesService.kt#L104)):*
> ```Kotlin
> 
>     if (request.pageToken.isNotEmpty()) {
>       if (!ResourceIds.RFC_1034_REGEX.matches(request.pageToken)) {
> ```

The regex is for the resource ID (`role_id` field in `CreateRoleRequest`), not the page token. The page token string should be a base64url-encoded serialized `ListRolesPageToken` message (though this fact is opaque to the public API caller).
___
*[`src/main/kotlin/org/wfanet/measurement/access/service/v1alpha/RolesService.kt` line 108 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1980#-OE_SSAVA3yPqV3wna67:-OE_SSAVA3yPqV3wna68:b75ar20) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a6600fd11b62e9d4d1516fe54f6f433d5e508d4d/src/main/kotlin/org/wfanet/measurement/access/service/v1alpha/RolesService.kt#L108)):*
> ```Kotlin
>           .asStatusRuntimeException(Status.Code.INVALID_ARGUMENT)
>       }
>       getRole(getRoleRequest { name = "roles/${request.pageToken}" })
> ```

Why is this calling getRole? The page token isn't a role ID.
___
*[`src/test/kotlin/org/wfanet/measurement/access/service/v1alpha/RolesServiceTest.kt` line 56 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1980#-OE_UF5sCbbiaqrhUCbP:-OE_UF5sCbbiaqrhUCbQ:bkrsymr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a6600fd11b62e9d4d1516fe54f6f433d5e508d4d/src/test/kotlin/org/wfanet/measurement/access/service/v1alpha/RolesServiceTest.kt#L56)):*
> ```Kotlin
> import org.wfanet.measurement.common.grpc.testing.mockService
> import org.wfanet.measurement.common.testing.verifyProtoArgument
> import org.wfanet.measurement.internal.access.ListRolesPageTokenKt.after as internalListRolesPageTokenAfter
> ```

Don't add aliases for functions inside of types. Instead, add an alias for the containing type.

You would then use this as `InternalListRolesPageTokenKt.after`



_Suggestion:_
```Kotlin
import org.wfanet.measurement.internal.access.ListRolesPageTokenKt as InternalListRolesPageTokenKt
```


<!-- Sent from Reviewable.io -->

2024-12-24 00:02 UTC, roaminggypsy reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1980)* status: 4 of 6 files reviewed, 3 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/access/service/v1alpha/RolesService.kt` line 104 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1980#-OE_RPgl1om6zxNGyy_o:-OEpxEl62MZsEWKpyGxT:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a6600fd11b62e9d4d1516fe54f6f433d5e508d4d/src/main/kotlin/org/wfanet/measurement/access/service/v1alpha/RolesService.kt#L104)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The regex is for the resource ID (`role_id` field in `CreateRoleRequest`), not the page token. The page token string should be a base64url-encoded serialized `ListRolesPageToken` message (though this fact is opaque to the public API caller).
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/access/service/v1alpha/RolesService.kt` line 108 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1980#-OE_SSAVA3yPqV3wna67:-OEpxEzy-k1sPHvH6adC:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a6600fd11b62e9d4d1516fe54f6f433d5e508d4d/src/main/kotlin/org/wfanet/measurement/access/service/v1alpha/RolesService.kt#L108)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Why is this calling getRole? The page token isn't a role ID.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-12-24 00:05 UTC, roaminggypsy reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1980)* status: 4 of 6 files reviewed, 3 unresolved discussions (waiting on @SanjayVas)

___
*[`src/test/kotlin/org/wfanet/measurement/access/service/v1alpha/RolesServiceTest.kt` line 56 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1980#-OE_UF5sCbbiaqrhUCbP:-OEpydh9DOvFB6YuJ-dn:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a6600fd11b62e9d4d1516fe54f6f433d5e508d4d/src/test/kotlin/org/wfanet/measurement/access/service/v1alpha/RolesServiceTest.kt#L56)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Don't add aliases for functions inside of types. Instead, add an alias for the containing type.

You would then use this as `InternalListRolesPageTokenKt.after`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-12-24 00:23 UTC, SanjayVas requested changes
> Reviewed 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1980)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @roaminggypsy)

___
*[`src/main/kotlin/org/wfanet/measurement/access/service/v1alpha/RolesService.kt` line 106 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1980#-OEq0WW82aOQWGb79WGz:-OEq0WW82aOQWGb79WH-:b-otbh35) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8840874633fc171ba52216a8cf072d9c020c684e/src/main/kotlin/org/wfanet/measurement/access/service/v1alpha/RolesService.kt#L106)):*
> ```Kotlin
>           pageSize = request.pageSize
>           if (request.pageToken.isNotEmpty()) {
>             pageToken = internalListRolesPageToken { request.pageToken }
> ```

What you have is equivalent to InternalListRolesPageToken.getDefaultInstance()

You need to decode from base64 URL and then deserialize into a page token message. You probably want to throw an InvalidFieldValueException if you get an IOException or InvalidProtocolBufferException.



_Suggestion:_
```Kotlin
InternalListRolesPageToken.parseFrom(request.pageToken.base64UrlDecode())
```
___
*[`src/main/kotlin/org/wfanet/measurement/access/service/v1alpha/RolesService.kt` line 114 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1980#-OEq0I5gEexi-MdszWVa:-OEq0I5gEexi-MdszWVb:undefined) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8840874633fc171ba52216a8cf072d9c020c684e/src/main/kotlin/org/wfanet/measurement/access/service/v1alpha/RolesService.kt#L114)):*
> ```Kotlin
>       roles += internalResponse.rolesList.map { it.toRole() }
>       if (internalResponse.hasNextPageToken()) {
>         nextPageToken = internalResponse.nextPageToken.after.roleResourceId
> ```





_Suggestion:_
```Kotlin
nextPageToken = internalResponse.nextPageToken.toByteString().base64UrlEncode()
```


<!-- Sent from Reviewable.io -->

2024-12-27 00:08 UTC, roaminggypsy reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1980)* status: 4 of 6 files reviewed, 2 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/access/service/v1alpha/RolesService.kt` line 106 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1980#-OEq0WW82aOQWGb79WGz:-OF4QvxmAPBux0z7kFsY:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8840874633fc171ba52216a8cf072d9c020c684e/src/main/kotlin/org/wfanet/measurement/access/service/v1alpha/RolesService.kt#L106)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

What you have is equivalent to InternalListRolesPageToken.getDefaultInstance()

You need to decode from base64 URL and then deserialize into a page token message. You probably want to throw an InvalidFieldValueException if you get an IOException or InvalidProtocolBufferException.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/access/service/v1alpha/RolesService.kt` line 114 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1980#-OEq0I5gEexi-MdszWVa:-OF4QwLX8vE_z7MfPxiN:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8840874633fc171ba52216a8cf072d9c020c684e/src/main/kotlin/org/wfanet/measurement/access/service/v1alpha/RolesService.kt#L114)):*
> ```Kotlin
>       roles += internalResponse.rolesList.map { it.toRole() }
>       if (internalResponse.hasNextPageToken()) {
>         nextPageToken = internalResponse.nextPageToken.after.roleResourceId
> ```

Done.


<!-- Sent from Reviewable.io -->

2025-01-02 18:10 UTC, SanjayVas requested changes
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1980)* status: all files reviewed, 3 unresolved discussions (waiting on @roaminggypsy)

___
*[`src/main/kotlin/org/wfanet/measurement/access/service/v1alpha/RolesService.kt` line 106 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1980#-OFcBovgAG-whAb5y9bY:-OFcBovgAG-whAb5y9bZ:b-j19ap0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3c6b5ec222492f1d2d34dcae88e7191a68eb8359/src/main/kotlin/org/wfanet/measurement/access/service/v1alpha/RolesService.kt#L106)):*
> ```Kotlin
> 
>     val internalPageToken: InternalListRolesPageToken? =
>       if (request.pageToken.isEmpty()) null
> ```

Use curly braces on if blocks. The only case when you can omit them is when the entire if expression fits on one line. See https://developer.android.com/kotlin/style-guide#braces
___
*[`src/main/kotlin/org/wfanet/measurement/access/service/v1alpha/RolesService.kt` line 111 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1980#-OFcBgXN1Fh7BxvC80ar:-OFcBgXN1Fh7BxvC80as:b-5n6kz0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3c6b5ec222492f1d2d34dcae88e7191a68eb8359/src/main/kotlin/org/wfanet/measurement/access/service/v1alpha/RolesService.kt#L111)):*
> ```Kotlin
>           InternalListRolesPageToken.parseFrom(request.pageToken.base64UrlDecode())
>         } catch (e: IOException) {
>           throw InvalidFieldValueException("page_token")
> ```

Specify the caught exception as the cause of the thrown one



_Suggestion:_
```Kotlin
InvalidFieldValueException("page_token", e)
```
___
*[`src/main/kotlin/org/wfanet/measurement/access/service/v1alpha/RolesService.kt` line 113 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1980#-OFcCAK35o3m-g0GOKiS:-OFcCAK35o3m-g0GOKiT:bkoc792) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3c6b5ec222492f1d2d34dcae88e7191a68eb8359/src/main/kotlin/org/wfanet/measurement/access/service/v1alpha/RolesService.kt#L113)):*
> ```Kotlin
>           throw InvalidFieldValueException("page_token")
>             .asStatusRuntimeException(Status.Code.INVALID_ARGUMENT)
>         } catch (e: InvalidProtocolBufferException) {
> ```

InvalidProtocolBufferException extends IOException, so no need to catch it separately if you're not going to handle it differently. Also note that this block will never be hit since you catch IOException first.


<!-- Sent from Reviewable.io -->

2025-01-02 21:59 UTC, roaminggypsy reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1980)* status: 5 of 6 files reviewed, 3 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/access/service/v1alpha/RolesService.kt` line 106 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1980#-OFcBovgAG-whAb5y9bY:-OFcwDkeDswr4IsTKx_-:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3c6b5ec222492f1d2d34dcae88e7191a68eb8359/src/main/kotlin/org/wfanet/measurement/access/service/v1alpha/RolesService.kt#L106)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Use curly braces on if blocks. The only case when you can omit them is when the entire if expression fits on one line. See https://developer.android.com/kotlin/style-guide#braces
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/access/service/v1alpha/RolesService.kt` line 111 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1980#-OFcBgXN1Fh7BxvC80ar:-OFcwGix8i4qDwpyRcsL:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3c6b5ec222492f1d2d34dcae88e7191a68eb8359/src/main/kotlin/org/wfanet/measurement/access/service/v1alpha/RolesService.kt#L111)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Specify the caught exception as the cause of the thrown one
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/access/service/v1alpha/RolesService.kt` line 113 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1980#-OFcCAK35o3m-g0GOKiS:-OFcwg1M0dG1_tVMRy_q:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3c6b5ec222492f1d2d34dcae88e7191a68eb8359/src/main/kotlin/org/wfanet/measurement/access/service/v1alpha/RolesService.kt#L113)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

InvalidProtocolBufferException extends IOException, so no need to catch it separately if you're not going to handle it differently. Also note that this block will never be hit since you catch IOException first.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2025-01-02 22:17 UTC, SanjayVas approved these changes
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1980)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @roaminggypsy)



<!-- Sent from Reviewable.io -->

2025-01-03 16:15 UTC, stevenwarejones approved these changes
> Reviewed 4 of 6 files at r1, 1 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1980)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @roaminggypsy)



<!-- Sent from Reviewable.io -->

2025-01-06 18:15 UTC, stevenwarejones approved these changes
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1980)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @roaminggypsy)



<!-- Sent from Reviewable.io -->

2025-01-07 19:47 UTC, merged