style: Address lint errors in metric and metric_service
world-federation-of-advertisers/cross-media-measurement pull request #1981
Opened 2024-12-20 15:37 UTC by kungfucraig

2024-12-20 15:37 UTC, wfa-reviewable commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1981)
<!-- Reviewable:end -->

2024-12-20 19:36 UTC, SanjayVas requested changes
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1981)* status: all files reviewed, 1 unresolved discussion (waiting on @jojijac0b and @kungfucraig)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto` line 236 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1981#-OE_YpL03ySocc6SB06A:-OE_YpL03ySocc6SB06B:b-tab08v) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/609d56efb53c517f0abfd4ccb69eaf7c5350cfe2/src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto#L236)):*
> ```proto
>     // Only set when all source Measurements contain sufficient information to
>     // calculate univariate statistics.
>     // (-- api-linter: core::0140::abbreviations=disabled
> ```

FYI I filed https://github.com/googleapis/api-linter/issues/1453 for this one. It surprised me that the linter complained, and indeed I can find no mention of this in the corresponding AIP.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto` line 348 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1981#-OE_ZKrJBlc2z93Ofv8n:-OE_ZKrJBlc2z93Ofv8o:bs07d6y) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/609d56efb53c517f0abfd4ccb69eaf7c5350cfe2/src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto#L348)):*
> ```proto
>   }
> 
>   // The metric result. At least one value is required.
> ```

It's not actually "at least one" as it's a oneof, meaning you can't specify more than one. You can just say "Required".



_Code quote:_
```proto
At least one
```


<!-- Sent from Reviewable.io -->

2024-12-20 21:35 UTC, kungfucraig reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1981)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @jojijac0b and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto` line 348 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1981#-OE_ZKrJBlc2z93Ofv8n:-OE_znknCx-Qg39Wk8Al:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/609d56efb53c517f0abfd4ccb69eaf7c5350cfe2/src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto#L348)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

It's not actually "at least one" as it's a oneof, meaning you can't specify more than one. You can just say "Required".
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-12-20 21:35 UTC, kungfucraig reviewed
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1981)* status: all files reviewed, 1 unresolved discussion (waiting on @jojijac0b and @SanjayVas)



<!-- Sent from Reviewable.io -->

2024-12-20 21:36 UTC, kungfucraig reviewed
> Reviewed 2 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1981)* status: all files reviewed, 1 unresolved discussion (waiting on @jojijac0b and @SanjayVas)



<!-- Sent from Reviewable.io -->

2024-12-20 21:36 UTC, SanjayVas approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1981)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @jojijac0b)



<!-- Sent from Reviewable.io -->

2025-01-30 21:23 UTC, kungfucraig reviewed
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/1981)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @kungfucraig)



<!-- Sent from Reviewable.io -->

2025-01-30 21:44 UTC, merged