Remote unnecessary fields from Kingdom internal API.
world-federation-of-advertisers/cross-media-measurement pull request #206
Opened 2021-08-19 18:46 UTC by SanjayVas

2021-08-19 19:41 UTC, wangyaopw requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/206)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @kungfucraig and @SanjayVas)

___
*[src/main/proto/wfa/measurement/internal/kingdom/computation_participant.proto, line 34 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/206#-MhUvKuvAs1B_RX_Fzy-:-MhUvKuw8QIogJ6bD52l:b-psi4t0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4930b10e9c38c2940071856156dbf4cfd2c512be/src/main/proto/wfa/measurement/internal/kingdom/computation_participant.proto#L34)):*
> ```
> create_time
> ```
is the idea that createTime of computationParticipant always the same as that of the parent measurement?
___
*[src/main/proto/wfa/measurement/internal/kingdom/requisition.proto, line 25 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/206#-MhUveJ369KTg50Dw8Mk:-MhUveJ44yUaSXWgNtS6:bissxqv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4930b10e9c38c2940071856156dbf4cfd2c512be/src/main/proto/wfa/measurement/internal/kingdom/requisition.proto#L25)):*
> ```
> Requisition 
> ```
do we need updata_time in Requisition?


<!-- Sent from Reviewable.io -->

2021-08-19 22:59 UTC, SanjayVas reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/206)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @kungfucraig and @wangyaopw)

___
*[src/main/proto/wfa/measurement/internal/kingdom/computation_participant.proto, line 34 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/206#-MhUvKuvAs1B_RX_Fzy-:-MhVbG3f-nhjciyCB1hZ:bc3mz3c) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4930b10e9c38c2940071856156dbf4cfd2c512be/src/main/proto/wfa/measurement/internal/kingdom/computation_participant.proto#L34)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
> create_time
> ```
is the idea that createTime of computationParticipant always the same as that of the parent measurement?
</blockquote></details>

Yep. We could denormalize if needed, but no code was using that field either.
___
*[src/main/proto/wfa/measurement/internal/kingdom/requisition.proto, line 25 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/206#-MhUveJ369KTg50Dw8Mk:-MhVczOQ-CQAcmphQexZ:bwipjqm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4930b10e9c38c2940071856156dbf4cfd2c512be/src/main/proto/wfa/measurement/internal/kingdom/requisition.proto#L25)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
> Requisition 
> ```
do we need updata_time in Requisition?
</blockquote></details>

Good point. I'll send a separate PR to swap create_time to update_time here.


<!-- Sent from Reviewable.io -->

2021-08-19 23:05 UTC, wangyaopw approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/206#-:-MhVeHMi7WToQsp1dSl8:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kungfucraig)



<!-- Sent from Reviewable.io -->

2021-08-20 15:00 UTC, kungfucraig requested changes
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/206)* status: all files reviewed, 1 unresolved discussion (waiting on @corbantek, @oliver-amzn, @SanjayVas, and @zachcwc)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/206#-MhZ3yipBXycgMjKTdif:-MhZ3yipBXycgMjKTdig:b-x76hxj) (no related file):*
Why were these fields deemed unnecessary?

---


<!-- Sent from Reviewable.io -->

2021-08-20 15:53 UTC, corbantek approved these changes
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/206)* status: all files reviewed, 1 unresolved discussion (waiting on @oliver-amzn, @SanjayVas, and @zachcwc)



<!-- Sent from Reviewable.io -->

2021-08-20 16:30 UTC, SanjayVas reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/206)* status: all files reviewed, 1 unresolved discussion (waiting on @kungfucraig, @oliver-amzn, and @zachcwc)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/206#-MhZ3yipBXycgMjKTdif:-MhZMUZr69X6SH_L01iY:b-hrep90) (no related file):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Why were these fields deemed unnecessary?
</blockquote></details>

The `details_json` fields were added unintentionally. This doesn't make sense to be in a protobuf API, and we only have it in Spanner to help with debugging to avoid having to do protobuf deserialization.

As discussed in Yao's comment, ComputationParticipant doesn't need its own `create_time` field as it's created as part of the `Measurement`. Additionally, we don't use the create time of the ComputationParticipant for anything.

---


<!-- Sent from Reviewable.io -->

2021-08-23 16:02 UTC, kungfucraig approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/206)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @oliver-amzn, @SanjayVas, and @zachcwc)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/206#-MhZ3yipBXycgMjKTdif:-Mhnjuuq7G3Y6GMiV6xS:bvba25o) (no related file):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The `details_json` fields were added unintentionally. This doesn't make sense to be in a protobuf API, and we only have it in Spanner to help with debugging to avoid having to do protobuf deserialization.

As discussed in Yao's comment, ComputationParticipant doesn't need its own `create_time` field as it's created as part of the `Measurement`. Additionally, we don't use the create time of the ComputationParticipant for anything.


</blockquote></details>

Thanks. Can you add this to the overall PR description?

---


<!-- Sent from Reviewable.io -->

2021-08-23 16:41 UTC, SanjayVas reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/206)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @kungfucraig, @oliver-amzn, and @zachcwc)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/206#-MhZ3yipBXycgMjKTdif:-MhnskQvCHu5C3wSQIbT:b-896fix) (no related file):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Thanks. Can you add this to the overall PR description?
</blockquote></details>

Done.

---


<!-- Sent from Reviewable.io -->

2021-08-23 18:09 UTC, oliver-amzn approved these changes
> Reviewed 5 of 5 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/206)* status: all files reviewed, 2 unresolved discussions (waiting on @kungfucraig, @SanjayVas, and @zachcwc)

___
*[src/main/proto/wfa/measurement/internal/kingdom/requisitions_service.proto, line 88 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/206#-MhoBrHe-dE_lpHl3EIg:-MhoBrHe-dE_lpHl3EIh:bhgub10) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5032a8383dedee6b880f10285a7e7b4111b4ed54/src/main/proto/wfa/measurement/internal/kingdom/requisitions_service.proto#L88)):*
> ```
> PageToken
> ```

This isn't anywhere at all? 


<!-- Sent from Reviewable.io -->

2021-08-23 18:09 UTC, oliver-amzn approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/206)* status: all files reviewed, 2 unresolved discussions (waiting on @kungfucraig, @SanjayVas, and @zachcwc)

___
*[src/main/proto/wfa/measurement/internal/kingdom/requisitions_service.proto, line 88 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/206#-MhoBrHe-dE_lpHl3EIg:-MhoBzMZE1j6l7K4HYNF:bmunzrp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5032a8383dedee6b880f10285a7e7b4111b4ed54/src/main/proto/wfa/measurement/internal/kingdom/requisitions_service.proto#L88)):*
<details><summary><i>Previously, oliver-amzn (Oliver) wrote…</i></summary><blockquote>

> ```
> PageToken
> ```

This isn't anywhere at all? 
</blockquote></details>

*isn't used anywhere at all?


<!-- Sent from Reviewable.io -->

2021-08-23 19:53 UTC, SanjayVas reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/206)* status: all files reviewed, 2 unresolved discussions (waiting on @kungfucraig, @oliver-amzn, and @zachcwc)

___
*[src/main/proto/wfa/measurement/internal/kingdom/requisitions_service.proto, line 88 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/206#-MhoBrHe-dE_lpHl3EIg:-MhoYppv77_XznzjUeKL:b-b3a4kr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5032a8383dedee6b880f10285a7e7b4111b4ed54/src/main/proto/wfa/measurement/internal/kingdom/requisitions_service.proto#L88)):*
<details><summary><i>Previously, oliver-amzn (Oliver) wrote…</i></summary><blockquote>

*isn't used anywhere at all?
</blockquote></details>

Correct. It was unintentionally added in PR #172 and should have been dropped as part of resolving https://github.com/world-federation-of-advertisers/cross-media-measurement/pull/172#issuecomment-892045540


<!-- Sent from Reviewable.io -->

2021-08-23 23:24 UTC, oliver-amzn approved these changes
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/206)* status: all files reviewed, 1 unresolved discussion (waiting on @kungfucraig and @zachcwc)

___
*[src/main/proto/wfa/measurement/internal/kingdom/requisitions_service.proto, line 88 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/206#-MhoBrHe-dE_lpHl3EIg:-MhpJym25ArDHVkKqvt1:b44tpx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5032a8383dedee6b880f10285a7e7b4111b4ed54/src/main/proto/wfa/measurement/internal/kingdom/requisitions_service.proto#L88)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Correct. It was unintentionally added in PR #172 and should have been dropped as part of resolving https://github.com/world-federation-of-advertisers/cross-media-measurement/pull/172#issuecomment-892045540
</blockquote></details>

👍


<!-- Sent from Reviewable.io -->

2021-08-23 23:36 UTC, SanjayVas reviewed
> Dismissed @kungfucraig from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/206)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zachcwc)



<!-- Sent from Reviewable.io -->

2021-08-23 23:36 UTC, merged

2021-09-15 16:44 UTC, SanjayVas commented
This is for #103