Implement SetMeasurementResult for kingdom internal MeasurementService
world-federation-of-advertisers/cross-media-measurement pull request #236
Opened 2021-08-28 09:12 UTC by uakyol

2021-08-30 20:13 UTC, wangyaopw requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/236)* status: 0 of 8 files reviewed, 4 unresolved discussions (waiting on @oliver-amzn, @SanjayVas, @uakyol, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementsService.kt, line 50 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/236#-MiNdn3E8k4bCu3jykwQ:-MiNdn3E8k4bCu3jykwR:b-q63j1d) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/afa4ced53c3cd2570d908061d09b0ede1acc61b3/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementsService.kt#L50)):*
<details><summary><i alt="summary">Quoted 8 lines of code…</i></summary>

> ```
>         KingdomInternalException.Code.MEASUREMENT_CONSUMER_NOT_FOUND ->
>           failGrpc(Status.NOT_FOUND) { "MeasurementConsumer not found" }
>         KingdomInternalException.Code.DATA_PROVIDER_NOT_FOUND ->
>           failGrpc(Status.INVALID_ARGUMENT) { "DataProvider not found" }
>         KingdomInternalException.Code.DUCHY_NOT_FOUND ->
>           failGrpc(Status.INVALID_ARGUMENT) { "Duchy not found" }
>         KingdomInternalException.Code.CERTIFICATE_NOT_FOUND ->
>           failGrpc(Status.INVALID_ARGUMENT) { "Certificate not found" }
> ```
</details>


why a mixed NOT_FOUND and INVALID_ARGUMENT?
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementsService.kt, line 78 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/236#-MiNdG7P0lLqqh4tYlkg:-MiNdG7P0lLqqh4tYlkh:bpznktq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/afa4ced53c3cd2570d908061d09b0ede1acc61b3/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementsService.kt#L78)):*
> ```
>         KingdomInternalException.Code.MEASUREMENT_NOT_FOUND ->
>           failGrpc(Status.NOT_FOUND) { "Measurement not found" }
> ```

Only MEASUREMENT_NOT_FOUND is possible for this method I think.

All others should just `throw e`
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/SetMeasurementResult.kt, line 41 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/236#-MiNeNxDBDbTRc7lqtnB:-MiNeNxDBDbTRc7lqtnC:b-p75b8j) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/afa4ced53c3cd2570d908061d09b0ede1acc61b3/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/SetMeasurementResult.kt#L41)):*
> ```
> measurementResult
> ```

The name is a little misleading. It is same as the `measurementResult` in the method name, but apparently it is a different type.

maybe use something like `existingMeasurement`?
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt, line 364 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/236#-MiNgAkt-qxdf8HlI1uX:-MiNgAkt-qxdf8HlI1uY:b-nt0dbt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/afa4ced53c3cd2570d908061d09b0ede1acc61b3/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt#L364)):*
> ```
> setMeasurementResult
> ```

Is it possible to use src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/Population.kt to create the measurement now?


<!-- Sent from Reviewable.io -->

2021-08-30 20:41 UTC, wangyaopw requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/236)* status: 0 of 8 files reviewed, 6 unresolved discussions (waiting on @oliver-amzn, @SanjayVas, @uakyol, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementsService.kt, line 63 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/236#-MiNmhWdDZTF0kSI-wde:-MiNmhWdDZTF0kSI-wdf:b-5fui8u) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/afa4ced53c3cd2570d908061d09b0ede1acc61b3/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementsService.kt#L63)):*
> ```Kotlin
>   override suspend fun getMeasurementByComputationId(
>     request: GetMeasurementByComputationIdRequest
>   ): Measurement {
> ```

add `grpcRequire(request.measurementView == COMPUTATION_VIEW)` here

The method is called by DUCHY, all responses should use the `COMPUTATION_VIEW`.

If you'd like to fix this and its test in another PR, just add to TODO here.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/SetMeasurementResult.kt, line 42 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/236#-MiNmBIl8ai7HPBjffKL:-MiNmBIl8ai7HPBjffKM:bt0ivj3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/afa4ced53c3cd2570d908061d09b0ede1acc61b3/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/SetMeasurementResult.kt#L42)):*
> ```
> DEFAULT)
> ```

The method is called by DUCHY, all responses should use the `COMPUTATION_VIEW`.


<!-- Sent from Reviewable.io -->

2021-08-31 12:40 UTC, uakyol reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/236)* status: 0 of 8 files reviewed, 6 unresolved discussions (waiting on @oliver-amzn, @SanjayVas, @wangyaopw, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementsService.kt, line 50 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/236#-MiNdn3E8k4bCu3jykwQ:-MiR2qPxA2J--kYkpg-0:b-f3jun8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/afa4ced53c3cd2570d908061d09b0ede1acc61b3/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementsService.kt#L50)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
>         KingdomInternalException.Code.MEASUREMENT_CONSUMER_NOT_FOUND ->
>           failGrpc(Status.NOT_FOUND) { "MeasurementConsumer not found" }
>         KingdomInternalException.Code.DATA_PROVIDER_NOT_FOUND ->
>           failGrpc(Status.INVALID_ARGUMENT) { "DataProvider not found" }
>         KingdomInternalException.Code.DUCHY_NOT_FOUND ->
>           failGrpc(Status.INVALID_ARGUMENT) { "Duchy not found" }
>         KingdomInternalException.Code.CERTIFICATE_NOT_FOUND ->
>           failGrpc(Status.INVALID_ARGUMENT) { "Certificate not found" }
> ```

why a mixed NOT_FOUND and INVALID_ARGUMENT?
</blockquote></details>

you are right, thanks for potinting out. Changed based on your other comment.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementsService.kt, line 63 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/236#-MiNmhWdDZTF0kSI-wde:-MiRBm272PBfoAeuvrXN:b4lh8fs) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/afa4ced53c3cd2570d908061d09b0ede1acc61b3/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementsService.kt#L63)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

add `grpcRequire(request.measurementView == COMPUTATION_VIEW)` here

The method is called by DUCHY, all responses should use the `COMPUTATION_VIEW`.

If you'd like to fix this and its test in another PR, just add to TODO here.
</blockquote></details>

Thanks for pointing out. Fixed and added the test in this PR
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementsService.kt, line 78 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/236#-MiNdG7P0lLqqh4tYlkg:-MiR3CRoE1qxjXbxzZnv:b3kbimj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/afa4ced53c3cd2570d908061d09b0ede1acc61b3/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementsService.kt#L78)):*
> MEASUREMENT_NOT_FOUND
thank you
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/SetMeasurementResult.kt, line 41 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/236#-MiNeNxDBDbTRc7lqtnB:-MiR3QzS2fs41-KYbWGn:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/afa4ced53c3cd2570d908061d09b0ede1acc61b3/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/SetMeasurementResult.kt#L41)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
> measurementResult
> ```

The name is a little misleading. It is same as the `measurementResult` in the method name, but apparently it is a different type.

maybe use something like `existingMeasurement`?
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/SetMeasurementResult.kt, line 42 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/236#-MiNmBIl8ai7HPBjffKL:-MiR3cic5gDsgjgmUK19:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/afa4ced53c3cd2570d908061d09b0ede1acc61b3/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/SetMeasurementResult.kt#L42)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
> DEFAULT)
> ```

The method is called by DUCHY, all responses should use the `COMPUTATION_VIEW`.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt, line 364 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/236#-MiNgAkt-qxdf8HlI1uX:-MiRD5AT65zPnLVIimoJ:bqx4d9f) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/afa4ced53c3cd2570d908061d09b0ede1acc61b3/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt#L364)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
> setMeasurementResult
> ```

Is it possible to use src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/Population.kt to create the measurement now?
</blockquote></details>

this test needs a redo for all of these cases. But I don't want to tackle this now. I'll refactor all these later.


<!-- Sent from Reviewable.io -->

2021-08-31 16:07 UTC, wangyaopw submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/236)* status: 0 of 8 files reviewed, 2 unresolved discussions (waiting on @oliver-amzn, @SanjayVas, @uakyol, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementsService.kt, line 50 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/236#-MiNdn3E8k4bCu3jykwQ:-MiRwtV465AFnSiJ86Ux:b-rs2yxm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/afa4ced53c3cd2570d908061d09b0ede1acc61b3/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementsService.kt#L50)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

you are right, thanks for potinting out. Changed based on your other comment.
</blockquote></details>

There are still both NOT_FOUND and INVALID_ARGUMENT.

```
failGrpc(Status.NOT_FOUND) { "MeasurementConsumer not found" }
failGrpc(Status.INVALID_ARGUMENT) { "DataProvider not found" }
...
```
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt, line 364 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/236#-MiNgAkt-qxdf8HlI1uX:-MiRxXGvAsTIK26BFj4Z:bg8qgps) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/afa4ced53c3cd2570d908061d09b0ede1acc61b3/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt#L364)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

this test needs a redo for all of these cases. But I don't want to tackle this now. I'll refactor all these later.
</blockquote></details>

Adding a TODO?


<!-- Sent from Reviewable.io -->

2021-08-31 21:38 UTC, SanjayVas reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/236)* status: 0 of 8 files reviewed, 2 unresolved discussions (waiting on @oliver-amzn, @uakyol, @wangyaopw, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementsService.kt, line 50 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/236#-MiNdn3E8k4bCu3jykwQ:-MiT7i7BCycjp05hhVPs:bftcpw8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/afa4ced53c3cd2570d908061d09b0ede1acc61b3/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementsService.kt#L50)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

There are still both NOT_FOUND and INVALID_ARGUMENT.

```
failGrpc(Status.NOT_FOUND) { "MeasurementConsumer not found" }
failGrpc(Status.INVALID_ARGUMENT) { "DataProvider not found" }
...
```

</blockquote></details>

If I understand canonical code usage correct, NOT_FOUND is correct if the parent isn't found (e.g. parent MeasurementConsumer not found when dealing with Measurement). INVALID_ARGUMENT is correct when something else specified in the request isn't found.


<!-- Sent from Reviewable.io -->

2021-08-31 21:45 UTC, SanjayVas reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/236)* status: 0 of 8 files reviewed, 2 unresolved discussions (waiting on @oliver-amzn, @uakyol, @wangyaopw, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementsService.kt, line 50 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/236#-MiNdn3E8k4bCu3jykwQ:-MiT8v5D71ym6jA8pJN-:b-8lzqeq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/afa4ced53c3cd2570d908061d09b0ede1acc61b3/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementsService.kt#L50)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

If I understand canonical code usage correct, NOT_FOUND is correct if the parent isn't found (e.g. parent MeasurementConsumer not found when dealing with Measurement). INVALID_ARGUMENT is correct when something else specified in the request isn't found.
</blockquote></details>

There's an argument that the latter conditions should be FAILED_PRECONDITION instead, as the request itself could theoretically eventually succeed if entities with those IDs were created (see https://github.com/grpc/grpc/blob/master/doc/statuscodes.md).


<!-- Sent from Reviewable.io -->

2021-08-31 22:03 UTC, SanjayVas requested changes
> Reviewed 5 of 8 files at r1, 2 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/236)* status: 7 of 8 files reviewed, 6 unresolved discussions (waiting on @oliver-amzn, @uakyol, @wangyaopw, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementsService.kt, line 65 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/236#-MiTAl4xE3Z8qw8boKww:-MiTAl4xE3Z8qw8boKwx:b-iwyr0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4733231f7f760670076a2e470a4acfc021f615f7/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementsService.kt#L65)):*
> ```
>     grpcRequire(request.measurementView == Measurement.View.COMPUTATION){
>         "getMeasurementByComputationId can only be with COMPUTATION View"
>       }
> ```

If we have this view field available in the request, we should respect it. If we want this to always return a specific view, then the field instead should be dropped from the request and the method should be documented that it always returns this view.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt, line 34 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/236#-MiTC7h-20MY07V2q_CV:-MiTC7h-20MY07V2q_CW:b-vgqv0c) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4733231f7f760670076a2e470a4acfc021f615f7/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt#L34)):*
> ```Kotlin
>   SpannerReader<MeasurementReader.Result>() {
> 
>   data class Result(
> ```

Are the internal IDs even used, or could the result of this reader just be `Measurement`?
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/SetMeasurementResult.kt, line 29 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/236#-MiTCoRg-vgPopNUpz-d:-MiTCoRg-vgPopNUpz-e:b-sw5syy) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4733231f7f760670076a2e470a4acfc021f615f7/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/SetMeasurementResult.kt#L29)):*
> ```Kotlin
> import org.wfanet.measurement.kingdom.deploy.gcloud.spanner.readers.MeasurementReader
> 
> private val NEXT_MEASUREMENT_STATE = Measurement.State.SUCCEEDED
> ```

nit: blank line after
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/SetMeasurementResult.kt, line 42 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/236#-MiTD0c-7H2qBjFdCK7H:-MiTD0c-7H2qBjFdCK7I:b-ff89qe) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4733231f7f760670076a2e470a4acfc021f615f7/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/SetMeasurementResult.kt#L42)):*
> ```Kotlin
> 
>     val existingMeasurement =
>       MeasurementReader(Measurement.View.COMPUTATION)
> ```

The default view for Measurement is `DEFAULT` unless otherwise specified (e.g. via a request field or the method documentation). Either use the default or update the method, depending on what we actually need.


<!-- Sent from Reviewable.io -->

2021-08-31 22:24 UTC, SanjayVas reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/236)* status: 7 of 8 files reviewed, 6 unresolved discussions (waiting on @oliver-amzn, @uakyol, @wangyaopw, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementsService.kt, line 50 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/236#-MiNdn3E8k4bCu3jykwQ:-MiTI_p99xVXumxxPHXc:byc3q99) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/afa4ced53c3cd2570d908061d09b0ede1acc61b3/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementsService.kt#L50)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

There's an argument that the latter conditions should be FAILED_PRECONDITION instead, as the request itself could theoretically eventually succeed if entities with those IDs were created (see https://github.com/grpc/grpc/blob/master/doc/statuscodes.md).
</blockquote></details>

Sorry, I believe my previous statement is incorrect. Even parent not being found should be FAILED_PRECONDITION. This way, a [PreconditionFailure](https://github.com/googleapis/api-common-protos/blob/37d5125da5c90f2124d15908a54a32ed3f470bc2/google/rpc/error_details.proto#L140) can be passed in the error details so that the public service has enough information to handle it.


<!-- Sent from Reviewable.io -->

2021-09-01 11:08 UTC, uakyol reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/236)* status: 6 of 8 files reviewed, 5 unresolved discussions (waiting on @oliver-amzn, @SanjayVas, @wangyaopw, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementsService.kt, line 65 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/236#-MiTAl4xE3Z8qw8boKww:-MiW0AUb5l_jDw3Z8tk6:b-tquo4k) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4733231f7f760670076a2e470a4acfc021f615f7/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementsService.kt#L65)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
>     grpcRequire(request.measurementView == Measurement.View.COMPUTATION){
>         "getMeasurementByComputationId can only be with COMPUTATION View"
>       }
> ```

If we have this view field available in the request, we should respect it. If we want this to always return a specific view, then the field instead should be dropped from the request and the method should be documented that it always returns this view.
</blockquote></details>

@wangyaopw can you help? Are you sure we don't want DEFAULT view here?
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt, line 34 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/236#-MiTC7h-20MY07V2q_CV:-MiW154tAFe-Pqg7ogO7:b-kxk0sv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4733231f7f760670076a2e470a4acfc021f615f7/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt#L34)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Are the internal IDs even used, or could the result of this reader just be `Measurement`?
</blockquote></details>

yes, they are used in SetMeasurementResult.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/SetMeasurementResult.kt, line 42 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/236#-MiTD0c-7H2qBjFdCK7H:-MiW0YnSBOtQLDmVChSE:b-kja40z) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4733231f7f760670076a2e470a4acfc021f615f7/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/SetMeasurementResult.kt#L42)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The default view for Measurement is `DEFAULT` unless otherwise specified (e.g. via a request field or the method documentation). Either use the default or update the method, depending on what we actually need.
</blockquote></details>

@wangyaopw need help here. I changed based on your comment. Do we want to support both or just computation?
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt, line 364 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/236#-MiNgAkt-qxdf8HlI1uX:-MiW0wkzBTfepw3u0xek:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/afa4ced53c3cd2570d908061d09b0ede1acc61b3/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt#L364)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

Adding a TODO?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-09-01 17:56 UTC, SanjayVas reviewed
> Reviewed 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/236)* status: 7 of 8 files reviewed, 4 unresolved discussions (waiting on @oliver-amzn, @SanjayVas, @wangyaopw, and @zachcwc)



<!-- Sent from Reviewable.io -->

2021-09-02 17:05 UTC, SanjayVas requested changes
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/236)* status: all files reviewed, 6 unresolved discussions (waiting on @oliver-amzn, @uakyol, @wangyaopw, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementsService.kt, line 65 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/236#-MiTAl4xE3Z8qw8boKww:-MibNPgg8CojbBLllhbj:buwqlfr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4733231f7f760670076a2e470a4acfc021f615f7/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementsService.kt#L65)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

Thanks for bringing this up. I am tackling this in https://github.com/world-federation-of-advertisers/cross-media-measurement/pull/238 since that is where reading is done and this is just setting the measurement Result.
</blockquote></details>

Regardless of whether another PR is going to drop the request view field, you should at least revert the change in this PR that requires it to be a specific value.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt, line 98 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/236#-MibOxT-63vi8t2XHlll:-MibOxT-63vi8t2XHllm:b-w81xd1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d076e9e9fbfef5fe622f5dc3175f45a19b42aca7/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt#L98)):*
> ```
> ans
> ```
nit: and
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt, line 394 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/236#-MibPcroDme7UGTV943o:-MibPcroDme7UGTV943p:b20d3ur) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d076e9e9fbfef5fe622f5dc3175f45a19b42aca7/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt#L394)):*
> ```Kotlin
>       val externalDataProviderId = dataProvider.externalDataProviderId
>       val externalDataProviderCertificateId = dataProvider.certificate.externalCertificateId
>       val measurement =
> ```

Why do we need to insert a measurement at all for this test case? This is just testing whether setMeasurementResult fails when specifying a computation ID for a Measurement that doesn't exist (which is more accurate than saying "wrong ID").
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt, line 443 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/236#-MibQaEYEXJj2xkOWarG:-MibQC-UEmSeYVUW_TRo:b-my8uu9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d076e9e9fbfef5fe622f5dc3175f45a19b42aca7/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt#L443)):*
> ```Kotlin
>       val externalDataProviderCertificateId = dataProvider.certificate.externalCertificateId
> 
>       val measurement = measurement {
> ```

What is this used for?

You should only have two `Measurement`s you need to reference: the created one and the response from the SUT. You shouldn't need to reference the partial `Measurement` that serves as the create request anywhere in this test case (though this doesn't even appear to be that).
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt, line 479 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/236#-MibRHX41VTCGilq1a4r:-MibRHX41VTCGilq1a4s:bd004ha) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d076e9e9fbfef5fe622f5dc3175f45a19b42aca7/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt#L479)):*
<details><summary><i alt="summary">Quoted 19 lines of code…</i></summary>

> ```
>       val expectedMeasurementDetails =
>         measurement.details.copy {
>           this.aggregatorCertificate = request.aggregatorCertificate
>           this.resultPublicKey = request.resultPublicKey
>           this.encryptedResult = request.encryptedResult
>         }
>       assertThat(measurementWithResult.state).isEqualTo(Measurement.State.SUCCEEDED)
>       assertThat(measurementWithResult.details).isEqualTo(expectedMeasurementDetails)
>       assertThat(measurementWithResult.updateTime.seconds).isGreaterThan(0L)
>       assertThat(measurementWithResult)
>         .ignoringFields(
>           Measurement.DETAILS_FIELD_NUMBER,
>           Measurement.UPDATE_TIME_FIELD_NUMBER,
>           Measurement.DATA_PROVIDERS_FIELD_NUMBER,
>           Measurement.STATE_FIELD_NUMBER,
>           Measurement.REQUISITIONS_FIELD_NUMBER,
>           Measurement.COMPUTATION_PARTICIPANTS_FIELD_NUMBER
>         )
>         .isEqualTo(createdMeasurement)
> ```
</details>

I think you should be able to do this much more clearly in two assertions:
1. response `updateTime` is greater than created `updateTime`.
2. response equals an expected measurement value, ignoring the fields where we don't know the expected value (e.g. updateTime).


<!-- Sent from Reviewable.io -->

2021-09-02 23:47 UTC, uakyol reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/236)* status: 4 of 8 files reviewed, 5 unresolved discussions (waiting on @oliver-amzn, @SanjayVas, @wangyaopw, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementsService.kt, line 65 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/236#-MiTAl4xE3Z8qw8boKww:-Micmt2k8KwVfu5EVWRe:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4733231f7f760670076a2e470a4acfc021f615f7/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementsService.kt#L65)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Regardless of whether another PR is going to drop the request view field, you should at least revert the change in this PR that requires it to be a specific value.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt, line 394 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/236#-MibPcroDme7UGTV943o:-MicoHVI5avY5CAJ71I2:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d076e9e9fbfef5fe622f5dc3175f45a19b42aca7/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt#L394)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Why do we need to insert a measurement at all for this test case? This is just testing whether setMeasurementResult fails when specifying a computation ID for a Measurement that doesn't exist (which is more accurate than saying "wrong ID").
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt, line 443 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/236#-MibQaEYEXJj2xkOWarG:-Micp5_2ByVupm6YzQka:b-17pkqx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d076e9e9fbfef5fe622f5dc3175f45a19b42aca7/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt#L443)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

What is this used for?

You should only have two `Measurement`s you need to reference: the created one and the response from the SUT. You shouldn't need to reference the partial `Measurement` that serves as the create request anywhere in this test case (though this doesn't even appear to be that).
</blockquote></details>

you are right, thanks for catching.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt, line 479 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/236#-MibRHX41VTCGilq1a4r:-Micrdrh7D4MJFxa1c26:b-op9rw7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d076e9e9fbfef5fe622f5dc3175f45a19b42aca7/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt#L479)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
>       val expectedMeasurementDetails =
>         measurement.details.copy {
>           this.aggregatorCertificate = request.aggregatorCertificate
>           this.resultPublicKey = request.resultPublicKey
>           this.encryptedResult = request.encryptedResult
>         }
>       assertThat(measurementWithResult.state).isEqualTo(Measurement.State.SUCCEEDED)
>       assertThat(measurementWithResult.details).isEqualTo(expectedMeasurementDetails)
>       assertThat(measurementWithResult.updateTime.seconds).isGreaterThan(0L)
>       assertThat(measurementWithResult)
>         .ignoringFields(
>           Measurement.DETAILS_FIELD_NUMBER,
>           Measurement.UPDATE_TIME_FIELD_NUMBER,
>           Measurement.DATA_PROVIDERS_FIELD_NUMBER,
>           Measurement.STATE_FIELD_NUMBER,
>           Measurement.REQUISITIONS_FIELD_NUMBER,
>           Measurement.COMPUTATION_PARTICIPANTS_FIELD_NUMBER
>         )
>         .isEqualTo(createdMeasurement)
> ```
I think you should be able to do this much more clearly in two assertions:
1. response `updateTime` is greater than created `updateTime`.
2. response equals an expected measurement value, ignoring the fields where we don't know the expected value (e.g. updateTime).
</blockquote></details>

thank you. for 1 -  seconds didn't cut it, went to nanos. 


<!-- Sent from Reviewable.io -->

2021-09-02 23:58 UTC, SanjayVas requested changes
> Reviewed 3 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/236)* status: 7 of 8 files reviewed, 5 unresolved discussions (waiting on @oliver-amzn, @SanjayVas, @uakyol, @wangyaopw, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementsService.kt, line 65 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/236#-MiTAl4xE3Z8qw8boKww:-MicvJH40CeiBaj4B4hb:bx6w1kn) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4733231f7f760670076a2e470a4acfc021f615f7/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementsService.kt#L65)):*
> ```
>  return MeasurementReader(Measurement.View.COMPUTATION)
> ```
Revert this line too
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt, line 479 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/236#-MibRHX41VTCGilq1a4r:-Micw4WM-QFADp7-8kBt:bx5mrtb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d076e9e9fbfef5fe622f5dc3175f45a19b42aca7/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt#L479)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

thank you. for 1 -  seconds didn't cut it, went to nanos. 
</blockquote></details>

I don't think this condition will always be true, as `nanos` is the remainder from `seconds`. e.g. 5 seconds 1 nanos is greater than 4 seconds 9 nanos.

Use the `toInstant` conversion extension and compare those.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt, line 315 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/236#-MicvmnM-f9OPt9uB-kT:-MicvjSd6FVsKmyt53Vc:b-qm3sf5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/aac4fea62e1f0f181fa1034a030c4b34371a337a/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt#L315)):*
> ```
>         Measurement.DATA_PROVIDERS_FIELD_NUMBER,
> ```
Don't ignore this field, since you know that the expected value is empty.


<!-- Sent from Reviewable.io -->

2021-09-03 00:10 UTC, uakyol reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/236)* status: 6 of 8 files reviewed, 5 unresolved discussions (waiting on @oliver-amzn, @SanjayVas, @wangyaopw, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementsService.kt, line 65 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/236#-MiTAl4xE3Z8qw8boKww:-MicyOi68LAr1ODrgZD5:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4733231f7f760670076a2e470a4acfc021f615f7/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementsService.kt#L65)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
>  return MeasurementReader(Measurement.View.COMPUTATION)
> ```
Revert this line too
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt, line 479 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/236#-MibRHX41VTCGilq1a4r:-Micyqu-4rV3Eqa9hChb:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d076e9e9fbfef5fe622f5dc3175f45a19b42aca7/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt#L479)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I don't think this condition will always be true, as `nanos` is the remainder from `seconds`. e.g. 5 seconds 1 nanos is greater than 4 seconds 9 nanos.

Use the `toInstant` conversion extension and compare those.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt, line 315 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/236#-MicvmnM-f9OPt9uB-kT:-MiczYZaA9Gg0SjuInrA:b-k73z76) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/aac4fea62e1f0f181fa1034a030c4b34371a337a/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt#L315)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
>         Measurement.DATA_PROVIDERS_FIELD_NUMBER,
> ```
Don't ignore this field, since you know that the expected value is empty.
</blockquote></details>

thanks


<!-- Sent from Reviewable.io -->

2021-09-03 00:17 UTC, SanjayVas requested changes
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/236)* status: all files reviewed, 2 unresolved discussions (waiting on @oliver-amzn, @uakyol, @wangyaopw, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt, line 315 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/236#-MicvmnM-f9OPt9uB-kT:-Mid-YNn44WRPHLiRQis:b49sgcv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/aac4fea62e1f0f181fa1034a030c4b34371a337a/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt#L315)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

thanks
</blockquote></details>

Since you're not specifying COMPUTATION view here, so you should actually not ignore any fields. (What you probably want to do is specify COMPUTATION view).


<!-- Sent from Reviewable.io -->

2021-09-03 00:23 UTC, uakyol reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/236)* status: 7 of 8 files reviewed, 2 unresolved discussions (waiting on @oliver-amzn, @SanjayVas, @wangyaopw, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt, line 315 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/236#-MicvmnM-f9OPt9uB-kT:-Mid1Mpv-B8J90BE9syg:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/aac4fea62e1f0f181fa1034a030c4b34371a337a/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt#L315)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Since you're not specifying COMPUTATION view here, so you should actually not ignore any fields. (What you probably want to do is specify COMPUTATION view).
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-09-03 00:30 UTC, SanjayVas approved these changes
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/236)* status: all files reviewed, 1 unresolved discussion (waiting on @oliver-amzn, @wangyaopw, and @zachcwc)



<!-- Sent from Reviewable.io -->

2021-09-03 16:14 UTC, oliver-amzn approved these changes
> Reviewed 3 of 8 files at r1, 1 of 3 files at r4, 2 of 4 files at r5, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/236)* status: all files reviewed, 1 unresolved discussion (waiting on @wangyaopw and @zachcwc)



<!-- Sent from Reviewable.io -->

2021-09-03 16:16 UTC, uakyol reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 8 files at r1, 1 of 3 files at r4, 2 of 4 files at r5, 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/236#-:-MigRcN_6Kqx0PjeOc0Z:bnfp4nl)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @wangyaopw and @zachcwc)



<!-- Sent from Reviewable.io -->

2021-09-03 16:21 UTC, uakyol reviewed
> Dismissed @wangyaopw from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/236)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @SanjayVas and @zachcwc)



<!-- Sent from Reviewable.io -->

2021-09-03 16:21 UTC, uakyol reviewed
> Dismissed @SanjayVas from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/236)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @zachcwc)



<!-- Sent from Reviewable.io -->

2021-09-03 16:23 UTC, uakyol reviewed
> Reviewed 1 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/236)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @zachcwc)



<!-- Sent from Reviewable.io -->

2021-09-03 16:23 UTC, uakyol reviewed
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/236)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zachcwc)



<!-- Sent from Reviewable.io -->

2021-09-03 16:25 UTC, merged

2021-09-15 16:46 UTC, SanjayVas commented
This is for #103.