Add consent-signaling and check signatures
world-federation-of-advertisers/cross-media-measurement pull request #244
Opened 2021-09-01 00:29 UTC by oliver-amzn

@wangyaopw - not sure how to sign the encrypted sketch before uploading it to kingdom and couldn't find anything in the consent-signaling repo - any pointers for me?

2021-09-01 17:47 UTC, wangyaopw reviewed
we don't need to sign the encrypted sketch. It is not part of the consent signaling story.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/244#-:-MiXSwIG8Z4o4Eo1ElFM:b-u8t0ku)* status: 0 of 6 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-09-01 18:10 UTC, wangyaopw requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/244)* status: 0 of 6 files reviewed, 8 unresolved discussions (waiting on @oliver-amzn)

___
*[src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2Mill.kt, line 28 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/244#-MiXWI2OC7s5Bd4a06NH:-MiXWI2OC7s5Bd4a06NI:b3t3bms) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e255974ea0df6c47ba9e5917f447fbc742c3a573/src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2Mill.kt#L28)):*
> ```
> dataprovider
> ```
Use duchy.verifyElGamalPublicKey
___
*[src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt, line 48 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/244#-MiXX07T9DjC0aHohb-H:-MiXX07UDBH1OAVRn_hW:b56hy6j) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e255974ea0df6c47ba9e5917f447fbc742c3a573/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L48)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>   // The id of the MC's consent signaling private key in keyStore
>   val consentSignalingPrivateKeyId: String,
>   // The id of the MC's encryption private key in keyStore
>   val encryptionPrivateKeyId: String
> ```
</details>

Typo? Is this `DataProviderData`?

EDP simulator shouldn't need private key of the MC.
___
*[src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt, line 196 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/244#-MiXX_pc60I8lRW8NcpW:-MiXX_pg4yZNBXHvn5Bi:b-24slx2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e255974ea0df6c47ba9e5917f447fbc742c3a573/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L196)):*
<details><summary><i alt="summary">Quoted 14 lines of code…</i></summary>

> ```
>     @CommandLine.Option(
>       names = ["--mc-consent-signaling-key-der-file"],
>       description = ["The MC's consent signaling private key (DER format) file."],
>       required = true
>     )
>     lateinit var mcCsPrivateKeyDerFile: File
>       private set
>     @CommandLine.Option(
>       names = ["--mc-encryption-private-key-der-file"],
>       description = ["The MC's encryption private key (DER format) file."],
>       required = true
>     )
>     lateinit var mcEncPrivateKeyDerFile: File
>       private set
> ```
</details>

shouldn't need this two
___
*[src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/RequisitionFulfillmentWorkflow.kt, line 72 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/244#-MiXVTkW8xDokqTdZTpo:-MiXVTkW8xDokqTdZTpp:b40rjcw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e255974ea0df6c47ba9e5917f447fbc742c3a573/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/RequisitionFulfillmentWorkflow.kt#L72)):*
> ```
> sketchStore: SketchStore,
> ```
write the serialized sketch proto (before encryption) to the sketchStore. Use the requisition resource name as the key.
___
*[src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/RequisitionFulfillmentWorkflow.kt, line 163 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/244#-MiXYJZs7idHQUwt8HNv:-MiXYJZs7idHQUwt8HNw:b9rqp4o) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e255974ea0df6c47ba9e5917f447fbc742c3a573/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/RequisitionFulfillmentWorkflow.kt#L163)):*
> ```
> getMeasurementConsumer(measurementConsumerData.name)
> ```
The mc's certificate name is included in the Requisition. Maybe call getCertificate() in the CertificateApi?
___
*[src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/RequisitionFulfillmentWorkflow.kt, line 166 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/244#-MiXUbOa7RkUn6O__kC2:-MiXUbOa7RkUn6O__kC3:b3f1qyd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e255974ea0df6c47ba9e5917f447fbc742c3a573/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/RequisitionFulfillmentWorkflow.kt#L166)):*
> ```
> do we need to decrypt the measurement spec?
> ```
No. MeasurementSpec is not encrypted. Only requisitionSpec is encrypted.
___
*[src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/RequisitionFulfillmentWorkflow.kt, line 176 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/244#-MiXUuse76-ne3gXubdq:-MiXUuse76-ne3gXubdr:b-vwoj3w) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e255974ea0df6c47ba9e5917f447fbc742c3a573/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/RequisitionFulfillmentWorkflow.kt#L176)):*
> ```
> return
> ```
log the error before return?
___
*[src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/RequisitionFulfillmentWorkflow.kt, line 217 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/244#-MiXV-0K342UVQaKELJi:-MiXV-0K342UVQaKELJj:b-2oiqoe) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e255974ea0df6c47ba9e5917f447fbc742c3a573/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/RequisitionFulfillmentWorkflow.kt#L217)):*
> ```
> // todo(ohardt): still got to sign the sketch before uploading it
> ```
No need to sign the sketch. The sketch is just a ByteString of cipher words.


<!-- Sent from Reviewable.io -->

2021-09-02 00:43 UTC, oliver-amzn reviewed
👍

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/244#-:-MiYx1OVBHvniWHiXq7m:b44tpx)* status: 0 of 6 files reviewed, 8 unresolved discussions (waiting on @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2Mill.kt, line 28 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/244#-MiXWI2OC7s5Bd4a06NH:-MiYonHi7-VpdK5KfKrf:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e255974ea0df6c47ba9e5917f447fbc742c3a573/src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2Mill.kt#L28)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
> dataprovider
> ```
Use duchy.verifyElGamalPublicKey
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt, line 48 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/244#-MiXX07T9DjC0aHohb-H:-MiYpgeT2zomxVdoYCfu:bymajb0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e255974ea0df6c47ba9e5917f447fbc742c3a573/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L48)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
>   // The id of the MC's consent signaling private key in keyStore
>   val consentSignalingPrivateKeyId: String,
>   // The id of the MC's encryption private key in keyStore
>   val encryptionPrivateKeyId: String
> ```
Typo? Is this `DataProviderData`?

EDP simulator shouldn't need private key of the MC.

</blockquote></details>

You're right, removing this and passing mc resource name directly to Workflow
___
*[src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt, line 196 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/244#-MiXX_pc60I8lRW8NcpW:-MiYppGnEWHMq6HEQJ_Y:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e255974ea0df6c47ba9e5917f447fbc742c3a573/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L196)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
>     @CommandLine.Option(
>       names = ["--mc-consent-signaling-key-der-file"],
>       description = ["The MC's consent signaling private key (DER format) file."],
>       required = true
>     )
>     lateinit var mcCsPrivateKeyDerFile: File
>       private set
>     @CommandLine.Option(
>       names = ["--mc-encryption-private-key-der-file"],
>       description = ["The MC's encryption private key (DER format) file."],
>       required = true
>     )
>     lateinit var mcEncPrivateKeyDerFile: File
>       private set
> ```
shouldn't need this two
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/RequisitionFulfillmentWorkflow.kt, line 72 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/244#-MiXVTkW8xDokqTdZTpo:-MiYpyWW3QU4bOFq5EbO:b-qr20p5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e255974ea0df6c47ba9e5917f447fbc742c3a573/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/RequisitionFulfillmentWorkflow.kt#L72)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
> sketchStore: SketchStore,
> ```
write the serialized sketch proto (before encryption) to the sketchStore. Use the requisition resource name as the key.
</blockquote></details>

Line 212-214
```
    val blobKey = "sketch/for-req-${requisition.name}"
    sketchStore.write(blobKey, sketch.toByteString().asBufferedFlow(1024))

```

Isn't that what you're asking for? The sketch is not encrypted yet at that point. Or should the key be just the requisition name (e.g. remove the prefix I got right now)? 
___
*[src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/RequisitionFulfillmentWorkflow.kt, line 163 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/244#-MiXYJZs7idHQUwt8HNv:-MiYu95O-nBU0kXdTVMR:b93wrng) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e255974ea0df6c47ba9e5917f447fbc742c3a573/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/RequisitionFulfillmentWorkflow.kt#L163)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
> getMeasurementConsumer(measurementConsumerData.name)
> ```
The mc's certificate name is included in the Requisition. Maybe call getCertificate() in the CertificateApi?
</blockquote></details>

You mean `requisitionSpec.measurementPublicKey` ? 

And then how do I convert the cert from `getCertificate()` to an X509Cert ? 
___
*[src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/RequisitionFulfillmentWorkflow.kt, line 166 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/244#-MiXUbOa7RkUn6O__kC2:-MiYp0koDkGM4ZdNOAeF:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e255974ea0df6c47ba9e5917f447fbc742c3a573/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/RequisitionFulfillmentWorkflow.kt#L166)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
> do we need to decrypt the measurement spec?
> ```
No. MeasurementSpec is not encrypted. Only requisitionSpec is encrypted.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/RequisitionFulfillmentWorkflow.kt, line 176 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/244#-MiXUuse76-ne3gXubdq:-MiYrIef7toR-oCcQ3P6:b-rzhz7e) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e255974ea0df6c47ba9e5917f447fbc742c3a573/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/RequisitionFulfillmentWorkflow.kt#L176)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
> return
> ```
log the error before return?
</blockquote></details>

Good idea, done for both, reqSpec and measureSpec.
___
*[src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/RequisitionFulfillmentWorkflow.kt, line 217 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/244#-MiXV-0K342UVQaKELJi:-MiYp3g7E3usnPG8CW1d:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e255974ea0df6c47ba9e5917f447fbc742c3a573/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/RequisitionFulfillmentWorkflow.kt#L217)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
> // todo(ohardt): still got to sign the sketch before uploading it
> ```
No need to sign the sketch. The sketch is just a ByteString of cipher words.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-09-02 01:52 UTC, efoxepstein requested changes
> Reviewed 2 of 6 files at r1, 2 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/244)* status: 5 of 6 files reviewed, 9 unresolved discussions (waiting on @corbantek, @oliver-amzn, @SanjayVas, @wangyaopw, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/RequisitionFulfillmentWorkflow.kt, line 65 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/244#-MiZC5RC8aM6ZBtwrvHP:-MiZC5RC8aM6ZBtwrvHQ:b511vi8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2422a10e0363eb0ad3ab03d4109b65bb6123ac0f/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/RequisitionFulfillmentWorkflow.kt#L65)):*
> ```Kotlin
> import org.wfanet.measurement.loadtest.storage.SketchStore
> 
> val EDP_PRIVATE_KEY_HANDLE_KEY = "edp-private-consent-signaling-key"
> ```

Const val?


<!-- Sent from Reviewable.io -->

2021-09-02 13:57 UTC, oliver-amzn reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/244)* status: 5 of 6 files reviewed, 9 unresolved discussions (waiting on @corbantek, @efoxepstein, @SanjayVas, @wangyaopw, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/RequisitionFulfillmentWorkflow.kt, line 65 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/244#-MiZC5RC8aM6ZBtwrvHP:-Miamx_59vP6f-7K1J5h:b-rxszum) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2422a10e0363eb0ad3ab03d4109b65bb6123ac0f/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/RequisitionFulfillmentWorkflow.kt#L65)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Const val?
</blockquote></details>

const val!


<!-- Sent from Reviewable.io -->

2021-09-02 14:27 UTC, corbantek reviewed
> Reviewed 2 of 6 files at r1, 3 of 3 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/244)* status: 3 of 6 files reviewed, 9 unresolved discussions (waiting on @corbantek, @efoxepstein, @SanjayVas, @wangyaopw, and @zachcwc)



<!-- Sent from Reviewable.io -->

2021-09-02 15:51 UTC, wangyaopw requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/244)* status: 2 of 6 files reviewed, 6 unresolved discussions (waiting on @corbantek, @efoxepstein, @oliver-amzn, @SanjayVas, @wangyaopw, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/RequisitionFulfillmentWorkflow.kt, line 72 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/244#-MiXVTkW8xDokqTdZTpo:-Mib9tyM7i2khigBm_uy:bp1x8cs) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e255974ea0df6c47ba9e5917f447fbc742c3a573/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/RequisitionFulfillmentWorkflow.kt#L72)):*
>  sketchStore.write(blobKey, sketch.toByteString().asBufferedFlow(1024))

The prefix is added automatically by the sketchStore. Just use 
 ````
sketchStore.write(requisition.name, sketch.toByteString().asBufferedFlow(1024))
````
___
*[src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/RequisitionFulfillmentWorkflow.kt, line 163 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/244#-MiXYJZs7idHQUwt8HNv:-MibAeqd8_I3j9WGArHo:bwvmld8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e255974ea0df6c47ba9e5917f447fbc742c3a573/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/RequisitionFulfillmentWorkflow.kt#L163)):*
<details><summary><i>Previously, oliver-amzn (Oliver) wrote…</i></summary><blockquote>

I think I figured it out, using `readCertificate()` for the conversion - let me know if that's correct.
</blockquote></details>

mc's certificate name is `requisition.measurementConsumerCertificate`
___
*[src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/RequisitionFulfillmentWorkflow.kt, line 65 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/244#-MiZC5RC8aM6ZBtwrvHP:-Mib9Q5X5juFjbCgbDwQ:bzhx7xc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2422a10e0363eb0ad3ab03d4109b65bb6123ac0f/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/RequisitionFulfillmentWorkflow.kt#L65)):*
<details><summary><i>Previously, oliver-amzn (Oliver) wrote…</i></summary><blockquote>

const val!
</blockquote></details>

`private const val` :smile: 
___
*[src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/RequisitionFulfillmentWorkflow.kt, line 172 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/244#-MibArHi3i0lCVWg_u4e:-MibArHi3i0lCVWg_u4f:b12j6em) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/edc062dd0f98231e5544d2f5534bf24a087eb46c/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/RequisitionFulfillmentWorkflow.kt#L172)):*
> ```
> decryptedRequisitionSpec.measurementPublicKey.toString()
> ```
`requisition.measurementConsumerCertificate`
___
*[src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/RequisitionFulfillmentWorkflow.kt, line 181 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/244#-MibAzpv66AIDBxzPb9z:-MibAzpv66AIDBxzPbA-:bmmx4o7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/edc062dd0f98231e5544d2f5534bf24a087eb46c/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/RequisitionFulfillmentWorkflow.kt#L181)):*
> ```
> invalid measurementSpec
> ```
nit: maybe something like `RequisititionFulfillmentWorkflow failed due to: invalid measurementSpec`


<!-- Sent from Reviewable.io -->

2021-09-02 16:10 UTC, oliver-amzn reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/244)* status: 2 of 6 files reviewed, 5 unresolved discussions (waiting on @corbantek, @efoxepstein, @SanjayVas, @wangyaopw, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/RequisitionFulfillmentWorkflow.kt, line 72 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/244#-MiXVTkW8xDokqTdZTpo:-MibE-Pr2mK6IVWVU38i:bkvp35h) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e255974ea0df6c47ba9e5917f447fbc742c3a573/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/RequisitionFulfillmentWorkflow.kt#L72)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

>  sketchStore.write(blobKey, sketch.toByteString().asBufferedFlow(1024))

The prefix is added automatically by the sketchStore. Just use 
 ````
sketchStore.write(requisition.name, sketch.toByteString().asBufferedFlow(1024))
````
</blockquote></details>

Beautiful ,thx!
___
*[src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/RequisitionFulfillmentWorkflow.kt, line 163 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/244#-MiXYJZs7idHQUwt8HNv:-MibELPGA_irrfTFKTXd:b4c9lyr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e255974ea0df6c47ba9e5917f447fbc742c3a573/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/RequisitionFulfillmentWorkflow.kt#L163)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

mc's certificate name is `requisition.measurementConsumerCertificate`
</blockquote></details>

:thumbsup: 
___
*[src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/RequisitionFulfillmentWorkflow.kt, line 65 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/244#-MiZC5RC8aM6ZBtwrvHP:-MibDtRc0fJicF_1BjS-:b-3gb8y2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2422a10e0363eb0ad3ab03d4109b65bb6123ac0f/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/RequisitionFulfillmentWorkflow.kt#L65)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

`private const val` :smile: 
</blockquote></details>

eh, it's used in EdpSimulator.kt so can't make it private :-/
___
*[src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/RequisitionFulfillmentWorkflow.kt, line 172 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/244#-MibArHi3i0lCVWg_u4e:-MibEWHs0PC98Far7q_9:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/edc062dd0f98231e5544d2f5534bf24a087eb46c/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/RequisitionFulfillmentWorkflow.kt#L172)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
> decryptedRequisitionSpec.measurementPublicKey.toString()
> ```
`requisition.measurementConsumerCertificate`
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/RequisitionFulfillmentWorkflow.kt, line 181 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/244#-MibAzpv66AIDBxzPb9z:-MibEd4N5zBW6J05BW_W:b2yi7ho) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/edc062dd0f98231e5544d2f5534bf24a087eb46c/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/RequisitionFulfillmentWorkflow.kt#L181)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
> invalid measurementSpec
> ```
nit: maybe something like `RequisititionFulfillmentWorkflow failed due to: invalid measurementSpec`
</blockquote></details>

I like it. Done


<!-- Sent from Reviewable.io -->

2021-09-02 17:07 UTC, efoxepstein requested changes
> Reviewed 1 of 3 files at r5, 2 of 3 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/244)* status: all files reviewed, 6 unresolved discussions (waiting on @oliver-amzn, @SanjayVas, @wangyaopw, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/RequisitionFulfillmentWorkflow.kt, line 65 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/244#-MiZC5RC8aM6ZBtwrvHP:-MibLvIw62z0Kwmtry1t:b-hw6fh4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2422a10e0363eb0ad3ab03d4109b65bb6123ac0f/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/RequisitionFulfillmentWorkflow.kt#L65)):*
<details><summary><i>Previously, oliver-amzn (Oliver) wrote…</i></summary><blockquote>

eh, it's used in EdpSimulator.kt so can't make it private :-/
</blockquote></details>

If it's public, can you please add a KDoc comment to it?
___
*[src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/RequisitionFulfillmentWorkflow.kt, line 75 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/244#-MibMFJf3iFrRzngsrTX:-MibMFJg9n0LnFxp3nj6:b-blijq7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ff607339ce535fff925ad43162167fd0a6e6d790/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/RequisitionFulfillmentWorkflow.kt#L75)):*
> ```Kotlin
>   private val mcResourceName: String,
>   private val measurementConsumersClient: MeasurementConsumersCoroutineStub,
>   private val certificateServiceStub: CertificatesGrpcKt.CertificatesCoroutineStub
> ```

Could you import the CertificateCoroutineStub class itself for consistence with the other CoroutineStubs?


<!-- Sent from Reviewable.io -->

2021-09-02 18:06 UTC, oliver-amzn reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/244)* status: 5 of 6 files reviewed, 6 unresolved discussions (waiting on @efoxepstein, @wangyaopw, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/RequisitionFulfillmentWorkflow.kt, line 65 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/244#-MiZC5RC8aM6ZBtwrvHP:-MibgBxG3FJF1-wFMIHK:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2422a10e0363eb0ad3ab03d4109b65bb6123ac0f/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/RequisitionFulfillmentWorkflow.kt#L65)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

If it's public, can you please add a KDoc comment to it?
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/RequisitionFulfillmentWorkflow.kt, line 75 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/244#-MibMFJf3iFrRzngsrTX:-MibgAtb6magcgf_T56w:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ff607339ce535fff925ad43162167fd0a6e6d790/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/RequisitionFulfillmentWorkflow.kt#L75)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Could you import the CertificateCoroutineStub class itself for consistence with the other CoroutineStubs?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-09-02 18:09 UTC, wangyaopw approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/244)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @efoxepstein and @zachcwc)



<!-- Sent from Reviewable.io -->

2021-09-02 18:14 UTC, wangyaopw reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/244)* status: 5 of 6 files reviewed, 3 unresolved discussions (waiting on @efoxepstein, @oliver-amzn, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/RequisitionFulfillmentWorkflow.kt, line 82 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/244#-MibhQnW6VZhmFLfTGzE:-MibhQnX4suyyZbwvzqk:bff6c9m) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5bf933318b4a6621694059517394634a5daad705/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/RequisitionFulfillmentWorkflow.kt#L82)):*
> ```Kotlin
> 
>     val anySketch: AnySketch = SketchProtos.toAnySketch(sketchConfig)
> ```

So here you need to flags: 1. `per-edp-reach`, 2. `universe_size`.

and then generate `per-edp-reach` random numbers from 1~`universe_size`


<!-- Sent from Reviewable.io -->

2021-09-02 18:39 UTC, oliver-amzn reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/244)* status: 5 of 6 files reviewed, 3 unresolved discussions (waiting on @efoxepstein, @wangyaopw, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/RequisitionFulfillmentWorkflow.kt, line 82 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/244#-MibhQnW6VZhmFLfTGzE:-Mibnl_lCUfSxtwYZxPt:bicp7g4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5bf933318b4a6621694059517394634a5daad705/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/RequisitionFulfillmentWorkflow.kt#L82)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

So here you need to flags: 1. `per-edp-reach`, 2. `universe_size`.

and then generate `per-edp-reach` random numbers from 1~`universe_size`
</blockquote></details>

And that are Simulator flags, right? 

Let me add that


<!-- Sent from Reviewable.io -->

2021-09-02 19:39 UTC, efoxepstein approved these changes
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/244)* status: all files reviewed, 1 unresolved discussion (waiting on @wangyaopw and @zachcwc)



<!-- Sent from Reviewable.io -->

2021-09-02 19:45 UTC, wangyaopw reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/244)* status: all files reviewed, 1 unresolved discussion (waiting on @oliver-amzn and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/RequisitionFulfillmentWorkflow.kt, line 82 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/244#-MibhQnW6VZhmFLfTGzE:-Mic1ZiB535f54l-CqPq:bpxa60x) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5bf933318b4a6621694059517394634a5daad705/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/RequisitionFulfillmentWorkflow.kt#L82)):*
<details><summary><i>Previously, oliver-amzn (Oliver) wrote…</i></summary><blockquote>

And that are Simulator flags, right? 

Let me add that
</blockquote></details>

yes. that is for resolving `todo(@ohardt): make random`


<!-- Sent from Reviewable.io -->

2021-09-02 23:50 UTC, wangyaopw approved these changes
> Reviewed 1 of 6 files at r1, 1 of 1 files at r4, 1 of 3 files at r5, 2 of 3 files at r6, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/244)* status: all files reviewed, 1 unresolved discussion (waiting on @oliver-amzn and @zachcwc)



<!-- Sent from Reviewable.io -->

2021-09-03 13:20 UTC, oliver-amzn reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/244)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @efoxepstein, @wangyaopw, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/RequisitionFulfillmentWorkflow.kt, line 82 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/244#-MibhQnW6VZhmFLfTGzE:-MifnvN53oLmGErN_VxJ:b-896fja) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5bf933318b4a6621694059517394634a5daad705/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/RequisitionFulfillmentWorkflow.kt#L82)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

yes. that is for resolving `todo(@ohardt): make random`
</blockquote></details>

Done!
___
*[src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/RequisitionFulfillmentWorkflow.kt, line 217 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/244#-MifnynKCHDgDbCDHE6X:-MifnynKCHDgDbCDHE6Y:b9wek4i) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/248efb2efa3814a6a64a1bee3dd485b3026dfe64/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/RequisitionFulfillmentWorkflow.kt#L217)):*
> ```Kotlin
> 
> private fun AnySketchElGamalPublicKey.toV2ElGamalPublicKey(): ElGamalPublicKey {
>   val that = this
> ```

@wangyaopw @efoxepstein  - my IDE showed that `this` wasn't used in the previous assignment below. Is that correct? Is there a better way to do this? Or was this always right and IntelliJ is wrong?  


<!-- Sent from Reviewable.io -->

2021-09-03 15:24 UTC, wangyaopw requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/244)* status: 4 of 6 files reviewed, 2 unresolved discussions (waiting on @efoxepstein, @oliver-amzn, @wangyaopw, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/RequisitionFulfillmentWorkflow.kt, line 83 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/244#-MigDmyP-2_0QO_Mi6cA:-MigDmyP-2_0QO_Mi6cB:bl200n6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/248efb2efa3814a6a64a1bee3dd485b3026dfe64/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/RequisitionFulfillmentWorkflow.kt#L83)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
>     for (i in 1..sketchGenerationParams.universeSize) {
>       anySketch.insert(
>         123,
>         mapOf("frequency" to (1..sketchGenerationParams.reach).random().toLong())
>       )
>     }
> ```
</details>

The correct code is
```
     for (i in 1..sketchGenerationParams.reach) {
       anySketch.insert(
         Random.nextInt(1, sketchGenerationParams.universeSize+1),
         mapOf("frequency" to 1L)
       )
     }
```
it is inserting `sketchGenerationParams.reach` users to the anySketch, the user's id is in the range of [1,sketchGenerationParams.universeSize]. It is fine if the user ids have duplicates, since this is just test data.
___
*[src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/RequisitionFulfillmentWorkflow.kt, line 217 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/244#-MifnynKCHDgDbCDHE6X:-MigFY4hEj5hDBHnEDBD:bxqg589) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/248efb2efa3814a6a64a1bee3dd485b3026dfe64/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/RequisitionFulfillmentWorkflow.kt#L217)):*
<details><summary><i>Previously, oliver-amzn (Oliver) wrote…</i></summary><blockquote>

@wangyaopw @efoxepstein  - my IDE showed that `this` wasn't used in the previous assignment below. Is that correct? Is there a better way to do this? Or was this always right and IntelliJ is wrong?  
</blockquote></details>

the current code looks right to me.


<!-- Sent from Reviewable.io -->

2021-09-03 15:29 UTC, oliver-amzn reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/244)* status: 4 of 6 files reviewed, 2 unresolved discussions (waiting on @efoxepstein, @wangyaopw, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/RequisitionFulfillmentWorkflow.kt, line 83 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/244#-MigDmyP-2_0QO_Mi6cA:-MigGEY16P8UE3zjHvlv:b-jyaabo) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/248efb2efa3814a6a64a1bee3dd485b3026dfe64/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/RequisitionFulfillmentWorkflow.kt#L83)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
>     for (i in 1..sketchGenerationParams.universeSize) {
>       anySketch.insert(
>         123,
>         mapOf("frequency" to (1..sketchGenerationParams.reach).random().toLong())
>       )
>     }
> ```
The correct code is
```
     for (i in 1..sketchGenerationParams.reach) {
       anySketch.insert(
         Random.nextInt(1, sketchGenerationParams.universeSize+1),
         mapOf("frequency" to 1L)
       )
     }
```
it is inserting `sketchGenerationParams.reach` users to the anySketch, the user's id is in the range of [1,sketchGenerationParams.universeSize]. It is fine if the user ids have duplicates, since this is just test data.
</blockquote></details>

Ohhhh, ok, that makes sense, thanks!
___
*[src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/RequisitionFulfillmentWorkflow.kt, line 217 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/244#-MifnynKCHDgDbCDHE6X:-MigGp3M061gJIXBOJo0:bpjges) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/248efb2efa3814a6a64a1bee3dd485b3026dfe64/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/RequisitionFulfillmentWorkflow.kt#L217)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

the current code looks right to me.
</blockquote></details>

Hmm, ok, rolling back my `that` change.


<!-- Sent from Reviewable.io -->

2021-09-03 15:31 UTC, wangyaopw reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/244)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @efoxepstein, @wangyaopw, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/RequisitionFulfillmentWorkflow.kt, line 217 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/244#-MifnynKCHDgDbCDHE6X:-MigHAkI-MBWszV7BCD7:b53oy8b) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/248efb2efa3814a6a64a1bee3dd485b3026dfe64/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/RequisitionFulfillmentWorkflow.kt#L217)):*
<details><summary><i>Previously, oliver-amzn (Oliver) wrote…</i></summary><blockquote>

Hmm, ok, rolling back my `that` change.
</blockquote></details>

oh no, I mean your code with `val that = this` looks right to me


<!-- Sent from Reviewable.io -->

2021-09-03 15:33 UTC, oliver-amzn reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/244)* status: 4 of 6 files reviewed, all discussions resolved (waiting on @efoxepstein, @wangyaopw, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/RequisitionFulfillmentWorkflow.kt, line 217 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/244#-MifnynKCHDgDbCDHE6X:-MigHffP1suZSOhz_Q2D:b-mzkfwj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/248efb2efa3814a6a64a1bee3dd485b3026dfe64/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/RequisitionFulfillmentWorkflow.kt#L217)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

oh no, I mean your code with `val that = this` looks right to me
</blockquote></details>

Ooooops, bringing that back.


<!-- Sent from Reviewable.io -->

2021-09-03 15:43 UTC, wangyaopw approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/244)* status: 4 of 6 files reviewed, all discussions resolved (waiting on @efoxepstein, @wangyaopw, and @zachcwc)



<!-- Sent from Reviewable.io -->

2021-09-03 15:46 UTC, wangyaopw approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/244)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @efoxepstein, @oliver-amzn, @wangyaopw, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/BUILD.bazel, line 48 at r14](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/244#-MigKfwp1MzHiYwNGv7y:-MigKfwp1MzHiYwNGv7z:b-vamuql) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/25a97a5464b02ae6e0b9345b842ece2939bfd51d/src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/BUILD.bazel#L48)):*
> ```
> "@wfa_consent_signaling_client//src/main/kotlin/org/wfanet/measurement/consent/client/dataprovider",
> ```
delete


<!-- Sent from Reviewable.io -->

2021-09-03 15:48 UTC, oliver-amzn reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/244)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @efoxepstein, @wangyaopw, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/BUILD.bazel, line 48 at r14](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/244#-MigKfwp1MzHiYwNGv7y:-MigLCr341xs694YgRxA:b-babttn) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/25a97a5464b02ae6e0b9345b842ece2939bfd51d/src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/BUILD.bazel#L48)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
> "@wfa_consent_signaling_client//src/main/kotlin/org/wfanet/measurement/consent/client/dataprovider",
> ```
delete
</blockquote></details>

Why? Where's a whole bunch of imports like
`import org.wfanet.measurement.consent.client.dataprovider.verifyRequisitionSpec`


<!-- Sent from Reviewable.io -->

2021-09-03 15:50 UTC, wangyaopw approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/244)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @efoxepstein, @oliver-amzn, @wangyaopw, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/BUILD.bazel, line 48 at r14](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/244#-MigKfwp1MzHiYwNGv7y:-MigLYRl2ka2gQueJwIY:b-2gdpw6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/25a97a5464b02ae6e0b9345b842ece2939bfd51d/src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/BUILD.bazel#L48)):*
<details><summary><i>Previously, oliver-amzn (Oliver) wrote…</i></summary><blockquote>

Why? Where's a whole bunch of imports like
`import org.wfanet.measurement.consent.client.dataprovider.verifyRequisitionSpec`
</blockquote></details>

This is in the mill, which doesn't call anything from the dataprovider client library.


<!-- Sent from Reviewable.io -->

2021-09-03 15:56 UTC, oliver-amzn reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/244)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @efoxepstein, @wangyaopw, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/BUILD.bazel, line 48 at r14](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/244#-MigKfwp1MzHiYwNGv7y:-MigMmyk1JEu8qEtQCLk:b-zfqnir) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/25a97a5464b02ae6e0b9345b842ece2939bfd51d/src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/BUILD.bazel#L48)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

This is in the mill, which doesn't call anything from the dataprovider client library.
</blockquote></details>

Hmm? I'm looking at lines 56-58 in RequisitionWorkflow


<!-- Sent from Reviewable.io -->

2021-09-03 15:59 UTC, wangyaopw approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/244)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @efoxepstein, @oliver-amzn, @wangyaopw, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/BUILD.bazel, line 48 at r14](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/244#-MigKfwp1MzHiYwNGv7y:-MigNcm88lb7f4TfiWZf:byxr3ro) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/25a97a5464b02ae6e0b9345b842ece2939bfd51d/src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/BUILD.bazel#L48)):*
<details><summary><i>Previously, oliver-amzn (Oliver) wrote…</i></summary><blockquote>

Hmm? I'm looking at lines 56-58 in RequisitionWorkflow
</blockquote></details>

This comment is in `src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/BUILD.bazel`


<!-- Sent from Reviewable.io -->

2021-09-03 16:03 UTC, oliver-amzn reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/244)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @efoxepstein, @wangyaopw, and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/BUILD.bazel, line 48 at r14](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/244#-MigKfwp1MzHiYwNGv7y:-MigORyn2fcpwlBigWEe:b-pivi5g) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/25a97a5464b02ae6e0b9345b842ece2939bfd51d/src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/BUILD.bazel#L48)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

This comment is in `src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/BUILD.bazel`
</blockquote></details>

:facepalm: - my bad, that's what happens when you respond to PRs while in a meeting.


<!-- Sent from Reviewable.io -->

2021-09-03 16:43 UTC, efoxepstein approved these changes
> Reviewed 1 of 2 files at r10, 1 of 1 files at r14, 1 of 1 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/244)* status: all files reviewed, 1 unresolved discussion (waiting on @wangyaopw and @zachcwc)



<!-- Sent from Reviewable.io -->

2021-09-03 18:19 UTC, oliver-amzn reviewed
> Dismissed @wangyaopw from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/244)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @zachcwc)



<!-- Sent from Reviewable.io -->

2021-09-03 18:20 UTC, oliver-amzn reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/244#-:-MigsruLE0f3vVX64yYG:bnfp4nl)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @oliver-amzn)



<!-- Sent from Reviewable.io -->

2021-09-03 18:21 UTC, oliver-amzn reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r4, 1 of 3 files at r5, 1 of 3 files at r6, 1 of 2 files at r10, 1 of 1 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/244#-:-MigtAqN4upxSqqZ_8KR:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @oliver-amzn)



<!-- Sent from Reviewable.io -->

2021-09-03 18:21 UTC, merged