Delete all kingdom daemons which are not useful in the v2alpha design.
world-federation-of-advertisers/cross-media-measurement pull request #27
Opened 2021-04-23 18:08 UTC by wangyaopw

The correctnesstest is not touched since it is not set to run in the git action and it is a little hard to determine which part would still be useful in the future. So just keep it as is.

2021-04-23 19:32 UTC, SanjayVas requested changes
> Reviewed 22 of 22 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/27)* status: all files reviewed, 1 unresolved discussion (waiting on @wangyaopw and @zachcwc)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/27#-MZ-CvDOAj8noIHLp8c6:-MZ-CvDOAj8noIHLp8c7:b-bus3xl) (no related file):*
Can you also delete the Correctness Test, since that's broken by this change and we'll be rewriting it against v2alpha when it's working end-to-end?

---


<!-- Sent from Reviewable.io -->

2021-04-23 20:05 UTC, wangyaopw reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/27)* status: 21 of 41 files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @zachcwc)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/27#-MZ-CvDOAj8noIHLp8c6:-MZ-KeR55G--rEJn6clF:b-896fix) (no related file):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Can you also delete the Correctness Test, since that's broken by this change and we'll be rewriting it against v2alpha when it's working end-to-end?
</blockquote></details>

Done.

---


<!-- Sent from Reviewable.io -->

2021-04-24 00:36 UTC, SanjayVas approved these changes
> Reviewed 20 of 20 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/27)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zachcwc)



<!-- Sent from Reviewable.io -->

2021-04-27 02:32 UTC, zachcwc approved these changes

2021-04-27 15:34 UTC, merged

2021-04-27 15:44 UTC, zachcwc approved these changes