Define a MetaDataDuchyIdInterceptor.
world-federation-of-advertisers/cross-media-measurement pull request #291
Opened 2021-09-24 22:31 UTC by wangyaopw

This will be used in the in-memory integrationTest, which uses InProcessChannel and has no TLS conext

https://rally1.rallydev.com/#/604612930531d/userstories?detail=%2Ftask%2F609964597029&view=2c2927c0-626b-4740-8620-af2a93b7d623

2021-09-24 23:32 UTC, SanjayVas requested changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/291)* status: all files reviewed, 2 unresolved discussions (waiting on @efoxepstein and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/common/identity/testing/MetadataDuchyIdInterceptor.kt, line 42 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/291#-MkP89JKDTYvLtRWoMzE:-MkP89JL-keEZK0XAllq:b-djqaoq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ad9779fdaa2e6a1b32688bc835e9853b5878a49d/src/main/kotlin/org/wfanet/measurement/common/identity/testing/MetadataDuchyIdInterceptor.kt#L42)):*
> ```
> MetaDataDuchyIdInterceptor
> ```
nit: `Metadata` rather than `MetaData` to match the type
___
*[src/main/kotlin/org/wfanet/measurement/common/identity/testing/MetadataDuchyIdInterceptor.kt, line 48 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/291#-MkP8WtL7MDw74uSmjE-:-MkP8WtL7MDw74uSmjE0:b-a1zh0a) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ad9779fdaa2e6a1b32688bc835e9853b5878a49d/src/main/kotlin/org/wfanet/measurement/common/identity/testing/MetadataDuchyIdInterceptor.kt#L48)):*
> ```
> error { "no duchy Id in the header" }
> ```
Since this doesn't happen in our normal execution context, I think you want to use `call.close` instead.


<!-- Sent from Reviewable.io -->

2021-09-24 23:32 UTC, efoxepstein requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/291)* status: all files reviewed, 3 unresolved discussions (waiting on @SanjayVas and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/common/identity/testing/MetadataDuchyIdInterceptor.kt, line 42 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/291#-MkP8Cqv3AQ8O5o1swyp:-MkP8Cqw6vzDHZLqJ_Cx:byscew0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ad9779fdaa2e6a1b32688bc835e9853b5878a49d/src/main/kotlin/org/wfanet/measurement/common/identity/testing/MetadataDuchyIdInterceptor.kt#L42)):*
> ```Kotlin
>  * On the client side, use [withDuchyId].
>  */
> class MetaDataDuchyIdInterceptor : ServerInterceptor {
> ```

`Metadata` please (no capital D)


<!-- Sent from Reviewable.io -->

2021-09-24 23:57 UTC, wangyaopw reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/291)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @efoxepstein and @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/common/identity/testing/MetadataDuchyIdInterceptor.kt, line 42 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/291#-MkP8Cqv3AQ8O5o1swyp:-MkPEI6z3_hSPNX0TNCU:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ad9779fdaa2e6a1b32688bc835e9853b5878a49d/src/main/kotlin/org/wfanet/measurement/common/identity/testing/MetadataDuchyIdInterceptor.kt#L42)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

`Metadata` please (no capital D)
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/common/identity/testing/MetadataDuchyIdInterceptor.kt, line 48 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/291#-MkP8WtL7MDw74uSmjE-:-MkPEJ1g3AH4c2pp_Yr7:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ad9779fdaa2e6a1b32688bc835e9853b5878a49d/src/main/kotlin/org/wfanet/measurement/common/identity/testing/MetadataDuchyIdInterceptor.kt#L48)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> error { "no duchy Id in the header" }
> ```
Since this doesn't happen in our normal execution context, I think you want to use `call.close` instead.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-09-25 00:23 UTC, SanjayVas approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/291)* status: all files reviewed, 1 unresolved discussion (waiting on @efoxepstein)



<!-- Sent from Reviewable.io -->

2021-09-25 02:39 UTC, efoxepstein approved these changes
> Reviewed 1 of 2 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/291)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @oliver-amzn)



<!-- Sent from Reviewable.io -->

2021-09-27 18:15 UTC, oliver-amzn approved these changes
> Reviewed 1 of 2 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/291)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @corbantek and @duliomatos1)



<!-- Sent from Reviewable.io -->

2021-09-27 19:40 UTC, merged