Add the InProcessEdpSimulator and integrationTestBase.
world-federation-of-advertisers/cross-media-measurement pull request #292
Opened 2021-09-24 22:40 UTC by wangyaopw

2021-09-24 23:37 UTC, efoxepstein requested changes
> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/292)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @wangyaopw)

___
*[src/test/kotlin/org/wfanet/measurement/integration/common/InProcessLifeOfAMeasurementIntegrationTestBase.kt, line 52 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/292#-MkP9W5n7MbVKjCg9cXA:-MkP9W5n7MbVKjCg9cXB:b-jw40e5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9f56d8ee4c47f0d50a43db0f40485e0700f43ba9/src/test/kotlin/org/wfanet/measurement/integration/common/InProcessLifeOfAMeasurementIntegrationTestBase.kt#L52)):*
> ```Kotlin
> private const val MC_ENCRYPTION_PRIVATE_KEY_ID = "mc-enc-private-key"
> private val OUTPUT_DP_PARAMS =
>   DifferentialPrivacyParams.newBuilder()
> ```

Use Kotlin DSL?


<!-- Sent from Reviewable.io -->

2021-09-25 00:01 UTC, wangyaopw reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/292)* status: 11 of 12 files reviewed, 1 unresolved discussion (waiting on @efoxepstein and @SanjayVas)

___
*[src/test/kotlin/org/wfanet/measurement/integration/common/InProcessLifeOfAMeasurementIntegrationTestBase.kt, line 52 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/292#-MkP9W5n7MbVKjCg9cXA:-MkPFI__AWQNFUCBGA4y:b-vpqjov) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9f56d8ee4c47f0d50a43db0f40485e0700f43ba9/src/test/kotlin/org/wfanet/measurement/integration/common/InProcessLifeOfAMeasurementIntegrationTestBase.kt#L52)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Use Kotlin DSL?
</blockquote></details>

oops, sure. This part copy/pasted.


<!-- Sent from Reviewable.io -->

2021-09-25 00:22 UTC, SanjayVas requested changes
> Reviewed 12 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/292)* status: 11 of 12 files reviewed, 11 unresolved discussions (waiting on @efoxepstein, @SanjayVas, and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt, line 186 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/292#-MkP9meT3ACXNZ7LgET2:-MkP9meUBnyZ78wE4pQi:b-m62a2e) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9f56d8ee4c47f0d50a43db0f40485e0700f43ba9/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L186)):*
> ```
> BYTES_PER_MIB
> ```
This should use the underlying `StorageClient`'s `defaultBufferSizeBytes`. The `Store` base class has a `write` overload that will buffer a `ByteString` for you.
___
*[src/test/kotlin/org/wfanet/measurement/integration/common/InProcessDuchy.kt, line 204 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/292#-MkPBmik8e9lJjerAeW9:-MkPBmik8e9lJjerAeWA:b-j03ki8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9f56d8ee4c47f0d50a43db0f40485e0700f43ba9/src/test/kotlin/org/wfanet/measurement/integration/common/InProcessDuchy.kt#L204)):*
> ```
> RequisitionFulfillmentApi
> ```
nit: there's nothing called this
___
*[src/test/kotlin/org/wfanet/measurement/integration/common/InProcessEdpSimulator.kt, line 36 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/292#-MkPDwdt-6dUty0-Gc0l:-MkPDwdt-6dUty0-Gc0m:bi5c9p6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9f56d8ee4c47f0d50a43db0f40485e0700f43ba9/src/test/kotlin/org/wfanet/measurement/integration/common/InProcessEdpSimulator.kt#L36)):*
> ```
>  TestRule
> ```
This doesn't look like a TestRule
___
*[src/test/kotlin/org/wfanet/measurement/integration/common/InProcessEdpSimulator.kt, line 56 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/292#-MkPHmeO-0AeQoxMxT7j:-MkPHmeO-0AeQoxMxT7k:b-vn59zg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9f56d8ee4c47f0d50a43db0f40485e0700f43ba9/src/test/kotlin/org/wfanet/measurement/integration/common/InProcessEdpSimulator.kt#L56)):*
<details><summary><i alt="summary">Quoted 9 lines of code…</i></summary>

> ```
>       val edpData = createEdpData(displayName, edpName)
>       keyStore.storePrivateKeyDer(
>         edpData.encryptionPrivateKeyId,
>         loadTestCertDerFile("${displayName}_enc_private.der")
>       )
>       keyStore.storePrivateKeyDer(
>         edpData.consentSignalingPrivateKeyId,
>         loadTestCertDerFile("${displayName}_cs_private.der")
>       )
> ```
</details>

nit: I think we should prefer to do the parts we can in the current scope using `runBlocking`. This way we get exceptions in the current thread and know at least those parts are done when the function returns.
___
*[src/test/kotlin/org/wfanet/measurement/integration/common/InProcessKingdom.kt, line 129 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/292#-MkPCUXV0e4fHbgIXyNB:-MkPCUXV0e4fHbgIXyNC:b1k3kol) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9f56d8ee4c47f0d50a43db0f40485e0700f43ba9/src/test/kotlin/org/wfanet/measurement/integration/common/InProcessKingdom.kt#L129)):*
> ```
> APIs
> ```
nit: just API. In AIP terminology, an API is made up of a set of services.
___
*[src/test/kotlin/org/wfanet/measurement/integration/common/InProcessLifeOfAMeasurementIntegrationTestBase.kt, line 65 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/292#-MkPCpwv66i4tl5idLaG:-MkPCpwv66i4tl5idLaH:b2rgcnw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9f56d8ee4c47f0d50a43db0f40485e0700f43ba9/src/test/kotlin/org/wfanet/measurement/integration/common/InProcessLifeOfAMeasurementIntegrationTestBase.kt#L65)):*
> ```
> Base
> ```
nit: I think the more common pattern is either to just have the base one have no suffix or prefix it with `Abstract`. The former is usually used when prefixing subclasses with the differentiating factor. See the naming scheme we use for our `Server` classes.
___
*[src/test/kotlin/org/wfanet/measurement/integration/common/InProcessLifeOfAMeasurementIntegrationTestBase.kt, line 83 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/292#-MkPFPXV0IOf0QMqxV-O:-MkPFPXV0IOf0QMqxV-P:bjm8xee) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9f56d8ee4c47f0d50a43db0f40485e0700f43ba9/src/test/kotlin/org/wfanet/measurement/integration/common/InProcessLifeOfAMeasurementIntegrationTestBase.kt#L83)):*
> ```Kotlin
>     get() = kingdomDataServicesRule.value
> 
>   val kingdom: InProcessKingdom =
> ```

protected?
___
*[src/test/kotlin/org/wfanet/measurement/integration/common/InProcessLifeOfAMeasurementIntegrationTestBase.kt, line 107 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/292#-MkPEs_qCAXuDnr33m7C:-MkPEs_qCAXuDnr33m7D:bg4od6l) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9f56d8ee4c47f0d50a43db0f40485e0700f43ba9/src/test/kotlin/org/wfanet/measurement/integration/common/InProcessLifeOfAMeasurementIntegrationTestBase.kt#L107)):*
> ```
> duchies[1]
> ```
Do all EDPs need to use the same Duchy for the test to work? If not, should we make sure all of the non-aggregator Duchies get used?
___
*[src/test/kotlin/org/wfanet/measurement/integration/common/InProcessLifeOfAMeasurementIntegrationTestBase.kt, line 192 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/292#-MkPGjpI4k_cj_ysue2_:-MkPGjpI4k_cj_ysue2a:b8gxjyz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9f56d8ee4c47f0d50a43db0f40485e0700f43ba9/src/test/kotlin/org/wfanet/measurement/integration/common/InProcessLifeOfAMeasurementIntegrationTestBase.kt#L192)):*
> ```
> edpDisplayNameToResourceNameMap[it.displayName]!!
> ```
use `getValue(it.displayName)` instead of coercing to non-null
___
*[src/test/kotlin/org/wfanet/measurement/integration/common/InProcessLifeOfAMeasurementIntegrationTestBase.kt, line 195 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/292#-MkPJPKRBPoS_ngJNwwT:-MkPJPKRBPoS_ngJNwwU:b-8nak63) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9f56d8ee4c47f0d50a43db0f40485e0700f43ba9/src/test/kotlin/org/wfanet/measurement/integration/common/InProcessLifeOfAMeasurementIntegrationTestBase.kt#L195)):*
> ```Kotlin
>     }
> 
>     // Wait for 1s to make sure all EDPs finish creating eventGroups before the test starts.
> ```

Maybe poll for this condition with an overall timeout? This way:
1. The test may be able to start sooner than 1s
2. The error will be clearer


<!-- Sent from Reviewable.io -->

2021-09-25 02:40 UTC, efoxepstein approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/292)* status: all files reviewed, 10 unresolved discussions (waiting on @SanjayVas and @wangyaopw)



<!-- Sent from Reviewable.io -->

2021-09-25 03:11 UTC, wangyaopw reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/292)* status: all files reviewed, 5 unresolved discussions (waiting on @efoxepstein and @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt, line 186 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/292#-MkP9meT3ACXNZ7LgET2:-MkPphNo8TDy51_Xr4HM:b7pfvgx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9f56d8ee4c47f0d50a43db0f40485e0700f43ba9/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L186)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> BYTES_PER_MIB
> ```
This should use the underlying `StorageClient`'s `defaultBufferSizeBytes`. The `Store` base class has a `write` overload that will buffer a `ByteString` for you.
</blockquote></details>

`SketchStore` doesn't inherit from the `Store` base class yet. Added a TODO to fix that in a separate PR.
___
*[src/test/kotlin/org/wfanet/measurement/integration/common/InProcessDuchy.kt, line 204 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/292#-MkPBmik8e9lJjerAeW9:-MkPq7Lw20AkCwtojXpC:bb7f2mf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9f56d8ee4c47f0d50a43db0f40485e0700f43ba9/src/test/kotlin/org/wfanet/measurement/integration/common/InProcessDuchy.kt#L204)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> RequisitionFulfillmentApi
> ```
nit: there's nothing called this
</blockquote></details>

done
___
*[src/test/kotlin/org/wfanet/measurement/integration/common/InProcessEdpSimulator.kt, line 36 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/292#-MkPDwdt-6dUty0-Gc0l:-MkPqJI48zW6mowGfzQn:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9f56d8ee4c47f0d50a43db0f40485e0700f43ba9/src/test/kotlin/org/wfanet/measurement/integration/common/InProcessEdpSimulator.kt#L36)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
>  TestRule
> ```
This doesn't look like a TestRule
</blockquote></details>

Done.
___
*[src/test/kotlin/org/wfanet/measurement/integration/common/InProcessEdpSimulator.kt, line 56 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/292#-MkPHmeO-0AeQoxMxT7j:-MkPqeVS-4JVtjurMiZf:bb7f2mf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9f56d8ee4c47f0d50a43db0f40485e0700f43ba9/src/test/kotlin/org/wfanet/measurement/integration/common/InProcessEdpSimulator.kt#L56)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
>       val edpData = createEdpData(displayName, edpName)
>       keyStore.storePrivateKeyDer(
>         edpData.encryptionPrivateKeyId,
>         loadTestCertDerFile("${displayName}_enc_private.der")
>       )
>       keyStore.storePrivateKeyDer(
>         edpData.consentSignalingPrivateKeyId,
>         loadTestCertDerFile("${displayName}_cs_private.der")
>       )
> ```
nit: I think we should prefer to do the parts we can in the current scope using `runBlocking`. This way we get exceptions in the current thread and know at least those parts are done when the function returns.
</blockquote></details>

done
___
*[src/test/kotlin/org/wfanet/measurement/integration/common/InProcessKingdom.kt, line 129 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/292#-MkPCUXV0e4fHbgIXyNB:-MkPqnDx0ccDb4pBBhtM:bb6un1j) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9f56d8ee4c47f0d50a43db0f40485e0700f43ba9/src/test/kotlin/org/wfanet/measurement/integration/common/InProcessKingdom.kt#L129)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> APIs
> ```
nit: just API. In AIP terminology, an API is made up of a set of services.
</blockquote></details>

Done
___
*[src/test/kotlin/org/wfanet/measurement/integration/common/InProcessLifeOfAMeasurementIntegrationTestBase.kt, line 65 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/292#-MkPCpwv66i4tl5idLaG:-MkPrGQl8TsOtED9JiMu:bb6un1j) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9f56d8ee4c47f0d50a43db0f40485e0700f43ba9/src/test/kotlin/org/wfanet/measurement/integration/common/InProcessLifeOfAMeasurementIntegrationTestBase.kt#L65)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> Base
> ```
nit: I think the more common pattern is either to just have the base one have no suffix or prefix it with `Abstract`. The former is usually used when prefixing subclasses with the differentiating factor. See the naming scheme we use for our `Server` classes.
</blockquote></details>

Done
___
*[src/test/kotlin/org/wfanet/measurement/integration/common/InProcessLifeOfAMeasurementIntegrationTestBase.kt, line 83 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/292#-MkPFPXV0IOf0QMqxV-O:-MkPriqEBeXvk6s1H03a:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9f56d8ee4c47f0d50a43db0f40485e0700f43ba9/src/test/kotlin/org/wfanet/measurement/integration/common/InProcessLifeOfAMeasurementIntegrationTestBase.kt#L83)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

protected?
</blockquote></details>

Done.
___
*[src/test/kotlin/org/wfanet/measurement/integration/common/InProcessLifeOfAMeasurementIntegrationTestBase.kt, line 107 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/292#-MkPEs_qCAXuDnr33m7C:-MkPrlL06ShO3S5Tmi1d:b-qaonmi) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9f56d8ee4c47f0d50a43db0f40485e0700f43ba9/src/test/kotlin/org/wfanet/measurement/integration/common/InProcessLifeOfAMeasurementIntegrationTestBase.kt#L107)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> duchies[1]
> ```
Do all EDPs need to use the same Duchy for the test to work? If not, should we make sure all of the non-aggregator Duchies get used?
</blockquote></details>

It is kind of intentional. This covers the case that a duchy receives no requisition and only provides noise to the computations.
___
*[src/test/kotlin/org/wfanet/measurement/integration/common/InProcessLifeOfAMeasurementIntegrationTestBase.kt, line 192 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/292#-MkPGjpI4k_cj_ysue2_:-MkPsANF1as3AZptZk0q:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9f56d8ee4c47f0d50a43db0f40485e0700f43ba9/src/test/kotlin/org/wfanet/measurement/integration/common/InProcessLifeOfAMeasurementIntegrationTestBase.kt#L192)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> edpDisplayNameToResourceNameMap[it.displayName]!!
> ```
use `getValue(it.displayName)` instead of coercing to non-null
</blockquote></details>

Done.
___
*[src/test/kotlin/org/wfanet/measurement/integration/common/InProcessLifeOfAMeasurementIntegrationTestBase.kt, line 195 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/292#-MkPJPKRBPoS_ngJNwwT:-MkPvxL10__sNlQGqCZF:b-95txdl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9f56d8ee4c47f0d50a43db0f40485e0700f43ba9/src/test/kotlin/org/wfanet/measurement/i [...]

2021-09-27 13:49 UTC, efoxepstein approved these changes
> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/292)* status: all files reviewed, 5 unresolved discussions (waiting on @oliver-amzn and @SanjayVas)



<!-- Sent from Reviewable.io -->

2021-09-27 16:27 UTC, oliver-amzn approved these changes
> Reviewed 7 of 12 files at r1, 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/292)* status: all files reviewed, 5 unresolved discussions (waiting on @SanjayVas)



<!-- Sent from Reviewable.io -->

2021-09-29 22:40 UTC, SanjayVas requested changes
> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/292)* status: all files reviewed, 2 unresolved discussions (waiting on @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt, line 186 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/292#-MkP9meT3ACXNZ7LgET2:-MknhYg62UOdNlv1Y8vY:b-j92kdm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9f56d8ee4c47f0d50a43db0f40485e0700f43ba9/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L186)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

`SketchStore` doesn't inherit from the `Store` base class yet. Added a TODO to fix that in a separate PR.
</blockquote></details>

Would you mind adding a TODO here as well to use the other `write` overload rather than specifying buffer size yourself?
___
*[src/test/kotlin/org/wfanet/measurement/integration/common/InProcessEdpSimulator.kt, line 56 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/292#-MkPHmeO-0AeQoxMxT7j:-MknKbFcDMFtIwnezj1U:bahczue) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9f56d8ee4c47f0d50a43db0f40485e0700f43ba9/src/test/kotlin/org/wfanet/measurement/integration/common/InProcessEdpSimulator.kt#L56)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

done
</blockquote></details>

This changed it to a suspend function instead, which is confusing for a function that starts another coroutine in the global scope. Note that my suggestion was also flawed in that it was suggesting doing some work blocking the current thread and then kicking off background work without giving the caller any handle on that coroutine (see [The reason to avoid GlobalScope](https://elizarov.medium.com/the-reason-to-avoid-globalscope-835337445abc))

You tend to either want a function to block or suspend until the operation is done **OR** return immediately and continue running in the background. The former is done either as a regular function (blocking) or as a suspend function (suspending). The latter is generally done by having the function be a coroutine builder by having it be a non-suspending function that is an extension on `CoroutineScope`. See [Explicit concurrency](https://elizarov.medium.com/explicit-concurrency-67a8e8fd9b25) for a deeper explanation.

We should probably have this function just be suspending, and have the calling test define a separate CoroutineScope to ensure that things get launched and cleaned up properly.

e.g.
```
suspend fun start(edpName: String, mcName: String) { ... }
```

and in the test:
```
private val backgroundScope = CoroutineScope(EmptyCoroutineContext)
```

```
for (edpSim in edpSimulators) {
  backgroundScope.launch { edpSim.start(...) }
}
```


<!-- Sent from Reviewable.io -->

2021-09-29 23:23 UTC, wangyaopw reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/292)* status: 11 of 13 files reviewed, 1 unresolved discussion (waiting on @efoxepstein, @oliver-amzn, and @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt, line 186 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/292#-MkP9meT3ACXNZ7LgET2:-MknqaNBET9BElLv4oz7:bb7f2mf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9f56d8ee4c47f0d50a43db0f40485e0700f43ba9/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L186)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Would you mind adding a TODO here as well to use the other `write` overload rather than specifying buffer size yourself?
</blockquote></details>

done
___
*[src/test/kotlin/org/wfanet/measurement/integration/common/InProcessEdpSimulator.kt, line 56 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/292#-MkPHmeO-0AeQoxMxT7j:-MknrgeD2LJsrp76ihJ6:bb7f2mf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9f56d8ee4c47f0d50a43db0f40485e0700f43ba9/src/test/kotlin/org/wfanet/measurement/integration/common/InProcessEdpSimulator.kt#L56)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This changed it to a suspend function instead, which is confusing for a function that starts another coroutine in the global scope. Note that my suggestion was also flawed in that it was suggesting doing some work blocking the current thread and then kicking off background work without giving the caller any handle on that coroutine (see [The reason to avoid GlobalScope](https://elizarov.medium.com/the-reason-to-avoid-globalscope-835337445abc))

You tend to either want a function to block or suspend until the operation is done **OR** return immediately and continue running in the background. The former is done either as a regular function (blocking) or as a suspend function (suspending). The latter is generally done by having the function be a coroutine builder by having it be a non-suspending function that is an extension on `CoroutineScope`. See [Explicit concurrency](https://elizarov.medium.com/explicit-concurrency-67a8e8fd9b25) for a deeper explanation.

We should probably have this function just be suspending, and have the calling test define a separate CoroutineScope to ensure that things get launched and cleaned up properly.

e.g.
```
suspend fun start(edpName: String, mcName: String) { ... }
```

and in the test:
```
private val backgroundScope = CoroutineScope(EmptyCoroutineContext)
```

```
for (edpSim in edpSimulators) {
  backgroundScope.launch { edpSim.start(...) }
}
```
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2021-09-29 23:46 UTC, SanjayVas requested changes
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/292)* status: all files reviewed, 1 unresolved discussion (waiting on @wangyaopw)

___
*[src/test/kotlin/org/wfanet/measurement/integration/common/InProcessEdpSimulator.kt, line 56 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/292#-MkPHmeO-0AeQoxMxT7j:-Mknx-BW2HWvKB2c6qEj:bkybpe9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9f56d8ee4c47f0d50a43db0f40485e0700f43ba9/src/test/kotlin/org/wfanet/measurement/integration/common/InProcessEdpSimulator.kt#L56)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

done
</blockquote></details>

You still need to drop the GlobalScope.launch from here.


<!-- Sent from Reviewable.io -->

2021-09-29 23:57 UTC, wangyaopw reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/292)* status: 11 of 13 files reviewed, 1 unresolved discussion (waiting on @efoxepstein, @oliver-amzn, and @SanjayVas)

___
*[src/test/kotlin/org/wfanet/measurement/integration/common/InProcessEdpSimulator.kt, line 56 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/292#-MkPHmeO-0AeQoxMxT7j:-Mknytq30x-cCA5f4Am3:b-osnxdk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9f56d8ee4c47f0d50a43db0f40485e0700f43ba9/src/test/kotlin/org/wfanet/measurement/integration/common/InProcessEdpSimulator.kt#L56)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

You still need to drop the GlobalScope.launch from here.
</blockquote></details>

oh, yep. Done

By the way, in the InprocessDuchy, we are doing

```
  private val heraldRule = CloseableResource {
    GlobalScope.launchAsAutoCloseable { xxxx}
}
```

Do we need to also switch it to a backgroundScope?


<!-- Sent from Reviewable.io -->

2021-09-30 00:15 UTC, SanjayVas requested changes
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/292)* status: all files reviewed, 1 unresolved discussion (waiting on @wangyaopw)

___
*[src/test/kotlin/org/wfanet/measurement/integration/common/InProcessEdpSimulator.kt, line 56 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/292#-MkPHmeO-0AeQoxMxT7j:-Mko1O093Z6WRCJ2gOWp:b-t97n8s) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9f56d8ee4c47f0d50a43db0f40485e0700f43ba9/src/test/kotlin/org/wfanet/measurement/integration/common/InProcessEdpSimulator.kt#L56)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

oh, yep. Done

By the way, in the InprocessDuchy, we are doing

```
  private val heraldRule = CloseableResource {
    GlobalScope.launchAsAutoCloseable { xxxx}
}
```

Do we need to also switch it to a backgroundScope?
</blockquote></details>

Yeah. We really shouldn't be using `GlobalScope` anywhere. The only place I could think of where it could make any kind of sense is in a `main` function.


<!-- Sent from Reviewable.io -->

2021-09-30 00:27 UTC, wangyaopw reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/292)* status: 10 of 13 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[src/test/kotlin/org/wfanet/measurement/integration/common/InProcessEdpSimulator.kt, line 56 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/292#-MkPHmeO-0AeQoxMxT7j:-Mko502T458PR9tMMTg2:b24ogak) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9f56d8ee4c47f0d50a43db0f40485e0700f43ba9/src/test/kotlin/org/wfanet/measurement/integration/common/InProcessEdpSimulator.kt#L56)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Yeah. We really shouldn't be using `GlobalScope` anywhere. The only place I could think of where it could make any kind of sense is in a `main` function.
</blockquote></details>

Not sure how the `heraldRule` can use the backgroundScope defined in the test, so I moved those backgroundScopes inside the components.


<!-- Sent from Reviewable.io -->

2021-09-30 01:11 UTC, SanjayVas requested changes
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/292)* status: all files reviewed, 2 unresolved discussions (waiting on @after and @wangyaopw)

___
*[src/test/kotlin/org/wfanet/measurement/integration/common/InProcessDuchy.kt, line 162 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/292#-Mko9o4xA5oPd4vl02hH:-Mko9o4y5WIbaxxckLfL:bn0y39d) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1cb021534a258b9545628399b9a37f8ec27fdc8c/src/test/kotlin/org/wfanet/measurement/integration/common/InProcessDuchy.kt#L162)):*
> ```
> launchAsAutoCloseable
> ```
Just `launch` here, since you don't do anything with the returned AutoCloseable.
___
*[src/test/kotlin/org/wfanet/measurement/integration/common/InProcessEdpSimulator.kt, line 56 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/292#-MkPHmeO-0AeQoxMxT7j:-Mko9L8I50NlGBisAy3V:b-70zcur) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9f56d8ee4c47f0d50a43db0f40485e0700f43ba9/src/test/kotlin/org/wfanet/measurement/integration/common/InProcessEdpSimulator.kt#L56)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

Not sure how the `heraldRule` can use the backgroundScope defined in the test, so I moved those backgroundScopes inside the components.
</blockquote></details>

I suppose that's fine, as long as the scope eventually gets cancelled to make sure no coroutines end up running forever.

Since InProcessDuchy is a TestRule, it should cancel the scope as part of the statement returned by `apply`. For InProcessEdpSimulator, maybe make it an AutoCloseable and cancel the scope on close. Then you can call close on all of the simulator's in the test's @After.


<!-- Sent from Reviewable.io -->

2021-09-30 13:28 UTC, oliver-amzn approved these changes
> Reviewed 1 of 2 files at r4, 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/292)* status: all files reviewed, 2 unresolved discussions (waiting on @after and @wangyaopw)



<!-- Sent from Reviewable.io -->

2021-09-30 17:25 UTC, oliver-amzn approved these changes
> Reviewed 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/292)* status: all files reviewed, 2 unresolved discussions (waiting on @after and @SanjayVas)



<!-- Sent from Reviewable.io -->

2021-09-30 17:32 UTC, SanjayVas requested changes
> Reviewed 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/292)* status: all files reviewed, 1 unresolved discussion (waiting on @after)

___
*[src/test/kotlin/org/wfanet/measurement/integration/common/InProcessEdpSimulator.kt, line 56 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/292#-MkPHmeO-0AeQoxMxT7j:-MkrkTSc9DBHkEAit_ih:bj37s16) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9f56d8ee4c47f0d50a43db0f40485e0700f43ba9/src/test/kotlin/org/wfanet/measurement/integration/common/InProcessEdpSimulator.kt#L56)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

Done
</blockquote></details>

I see the changes to cancel the EDP sim's scope, but not `InProcessDuchy`'s scope. I assume you need to change the `apply` method there?


<!-- Sent from Reviewable.io -->

2021-09-30 21:15 UTC, wangyaopw reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/292)* status: 12 of 13 files reviewed, 1 unresolved discussion (waiting on @after, @oliver-amzn, and @SanjayVas)

___
*[src/test/kotlin/org/wfanet/measurement/integration/common/InProcessEdpSimulator.kt, line 56 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/292#-MkPHmeO-0AeQoxMxT7j:-MksYSQp7825-ZtWgoak:bik505u) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9f56d8ee4c47f0d50a43db0f40485e0700f43ba9/src/test/kotlin/org/wfanet/measurement/integration/common/InProcessEdpSimulator.kt#L56)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I see the changes to cancel the EDP sim's scope, but not `InProcessDuchy`'s scope. I assume you need to change the `apply` method there?
</blockquote></details>

sure, updated the InProcessDuchy.apply().


<!-- Sent from Reviewable.io -->

2021-09-30 22:09 UTC, oliver-amzn approved these changes
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/292)* status: all files reviewed, 1 unresolved discussion (waiting on @after and @SanjayVas)



<!-- Sent from Reviewable.io -->

2021-09-30 23:44 UTC, SanjayVas approved these changes
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/292)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wangyaopw)



<!-- Sent from Reviewable.io -->

2021-09-30 23:57 UTC, merged