Fix the blobpath.
world-federation-of-advertisers/cross-media-measurement pull request #340
Opened 2021-10-29 18:32 UTC by wangyaopw

The `/` in the prefix results in an additional folder with empty name.
The `SketchStore` is missing a `/` in front of the blobKey.

2021-10-29 19:05 UTC, stevenwarejones approved these changes
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/340)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)



<!-- Sent from Reviewable.io -->

2021-10-29 19:47 UTC, SanjayVas requested changes
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/340)* status: all files reviewed, 1 unresolved discussion (waiting on @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/loadtest/storage/SketchStore.kt, line 38 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/340#-MnC_IZe6TU2LKhFxJ9C:-MnC_IZe6TU2LKhFxJ9D:b-88gdfq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d05323cc67b614ad0383def2a4d78cc17a96b05a/src/main/kotlin/org/wfanet/measurement/loadtest/storage/SketchStore.kt#L38)):*
> ```
> "/$context"
> ```
I had put the slash prefix in Store impls because I wanted it to be consistent with how we generate the private/real blob key. If real blob keys don't start with slashes, these shouldn't either. Therefore, we should fix Store to join the private prefix and the generated key with a slash, and stop having generateBlobKey return values with an initial slash.


<!-- Sent from Reviewable.io -->

2021-10-29 20:28 UTC, wangyaopw reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/340)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/loadtest/storage/SketchStore.kt, line 38 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/340#-MnC_IZe6TU2LKhFxJ9C:-MnCjD6N6-4IomU_z8NV:bnk02jl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d05323cc67b614ad0383def2a4d78cc17a96b05a/src/main/kotlin/org/wfanet/measurement/loadtest/storage/SketchStore.kt#L38)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> "/$context"
> ```
I had put the slash prefix in Store impls because I wanted it to be consistent with how we generate the private/real blob key. If real blob keys don't start with slashes, these shouldn't either. Therefore, we should fix Store to join the private prefix and the generated key with a slash, and stop having generateBlobKey return values with an initial slash.
</blockquote></details>

https://github.com/world-federation-of-advertisers/common-jvm/pull/54

I'll update the common-jvm version (in this PR) when the above PR is merged.


<!-- Sent from Reviewable.io -->

2021-10-29 21:20 UTC, SanjayVas approved these changes
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/340)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wangyaopw)



<!-- Sent from Reviewable.io -->

2021-11-01 21:34 UTC, wangyaopw reviewed
oops. Pushed a wrong commit to this branch.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/340#-:-MnSQ91n2YrNrWZTjv3u:b-1pq8m3)* status: 0 of 4 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-11-01 21:36 UTC, wangyaopw reviewed
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/340)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wangyaopw)



<!-- Sent from Reviewable.io -->

2021-11-05 01:22 UTC, merged