Add pg-embedded to test a minimal postgres schema validation
world-federation-of-advertisers/cross-media-measurement pull request #354
Opened 2021-11-10 19:49 UTC by duliomatos1

This is more of a request for comments and to:
* Make sure github's CI will be able to run embedded postgres in testing
* Help decide if we want to go the route of using embedded postgres for unit testing
* Find a simple way for testing schema migration from Spanner to Postgres

2021-11-11 23:19 UTC, efoxepstein requested changes
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/354)* status: all files reviewed, 7 unresolved discussions (waiting on @chipingyeh, @duliomatos1, @SanjayVas, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/aws/postgres/exchange.sdl, line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/354#-MoGHfD0CbDMBpfllvuR:-MoGHfD0CbDMBpfllvuS:b-i6yfny) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/02c31ab3c98e886266ddf557f29a28eb8b9784a8/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/aws/postgres/exchange.sdl#L1)):*
> ```
> -- Copyright 2020 The Cross-Media Measurement Authors
> ```

Is `.sdl` a common file extension for postgres schemas?
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/aws/postgres/exchange.sdl, line 16 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/354#-MoGHkew6ItfDlXvWy2J:-MoGHkew6ItfDlXvWy2K:b-c2si84) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/02c31ab3c98e886266ddf557f29a28eb8b9784a8/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/aws/postgres/exchange.sdl#L16)):*
> ```
> 
> 
> -- minimal port of a table from exchange.sql to use in testing
> ```

Nit: `exchange.sdl`? Maybe give the full path to disambiguate?
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/aws/postgres/exchange.sdl, line 16 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/354#-MoGHoOO4OTM0LMmA_VR:-MoGHoOO4OTM0LMmA_VS:bjcflea) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/02c31ab3c98e886266ddf557f29a28eb8b9784a8/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/aws/postgres/exchange.sdl#L16)):*
> ```
> 
> 
> -- minimal port of a table from exchange.sql to use in testing
> ```

If this is for testing only, can you move it into a `testing` subdirector?
___
*[src/test/kotlin/org/wfanet/measurement/kingdom/deploy/aws/postgres/AwsKingdomSchemaTest.kt, line 30 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/354#-MoG9WuS0kMWMiSCy8KU:-MoG9WuS0kMWMiSCy8KV:b-ge1h8c) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/02c31ab3c98e886266ddf557f29a28eb8b9784a8/src/test/kotlin/org/wfanet/measurement/kingdom/deploy/aws/postgres/AwsKingdomSchemaTest.kt#L30)):*
> ```Kotlin
> 
>   @Test fun `kingdom schema is valid sql for postgres`() {
>     val pg = EmbeddedPostgres.start()
> ```

In the long run, we'll want to wrap this in a TestRule (and include tear-down too) -- but this isn't necessary now
___
*[src/test/kotlin/org/wfanet/measurement/kingdom/deploy/aws/postgres/Schemata.kt, line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/354#-MoGHAYQ2NS5z_uA-aTQ:-MoGHAYR20lkzfEGNdmn:b-f6venv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/02c31ab3c98e886266ddf557f29a28eb8b9784a8/src/test/kotlin/org/wfanet/measurement/kingdom/deploy/aws/postgres/Schemata.kt#L1)):*
> ```Kotlin
> // Copyright 2020 The Cross-Media Measurement Authors
> ```

Can you move this file to `src/main/`? Our convention is to only have test files in `src/test`.


<!-- Sent from Reviewable.io -->

2021-11-11 23:41 UTC, SanjayVas requested changes
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/354)* status: all files reviewed, 8 unresolved discussions (waiting on @chipingyeh, @duliomatos1, @efoxepstein, and @stevenwarejones)

___
*[imports/java/com/opentable/components/BUILD.bazel, line 4 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/354#-MoGMA_NC32vqEckv-DI:-MoGMA_NC32vqEckv-DJ:b6vln5j) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/02c31ab3c98e886266ddf557f29a28eb8b9784a8/imports/java/com/opentable/components/BUILD.bazel#L4)):*
> ```Starlark
> 
> alias(
>     name = "otj_pg_embedded",
> ```

The import path should match the Java package path that's defined. The package path appears to be `com.opentable.db.postgres`, therefore the file should be `imports/java/com/opentable/db/postgres/BUILD.bazel`.

Unless there are more targets defining different subsets, the target name should match the package name. In this case, `postgres`.
___
*[src/test/kotlin/org/wfanet/measurement/kingdom/deploy/aws/postgres/AwsKingdomSchemaTest.kt, line 30 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/354#-MoG9WuS0kMWMiSCy8KU:-MoGL82l2RL6WM3Ln694:biz4ork) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/02c31ab3c98e886266ddf557f29a28eb8b9784a8/src/test/kotlin/org/wfanet/measurement/kingdom/deploy/aws/postgres/AwsKingdomSchemaTest.kt#L30)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

In the long run, we'll want to wrap this in a TestRule (and include tear-down too) -- but this isn't necessary now
</blockquote></details>

There's already a JUnit4 rule. Please use that.

```
@Rule
public SingleInstancePostgresRule pg = EmbeddedPostgresRules.singleInstance();
```
___
*[src/test/kotlin/org/wfanet/measurement/kingdom/deploy/aws/postgres/Schemata.kt, line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/354#-MoGHAYQ2NS5z_uA-aTQ:-MoGLFUT34Ut8TpNDlgk:b65r9nr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/02c31ab3c98e886266ddf557f29a28eb8b9784a8/src/test/kotlin/org/wfanet/measurement/kingdom/deploy/aws/postgres/Schemata.kt#L1)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Can you move this file to `src/main/`? Our convention is to only have test files in `src/test`.
</blockquote></details>

If it's only used within the same package and isn't complex enough to possibly need its own test, then it's okay for test infra to be in `src/test` tree. That said, I assume this will be used by more than one package (off the top of my head the schema test, the internal service impl tests, and the integration tests are all in different packages).


<!-- Sent from Reviewable.io -->

2021-11-18 19:52 UTC, efoxepstein requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/354)* status: all files reviewed, 8 unresolved discussions (waiting on @chipingyeh, @duliomatos1, @SanjayVas, and @stevenwarejones)

___
*[src/test/kotlin/org/wfanet/measurement/kingdom/deploy/aws/postgres/AwsKingdomSchemaTest.kt, line 30 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/354#-MoG9WuS0kMWMiSCy8KU:-MooagEk2cp4aHV5FCWw:b-8pwuun) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/02c31ab3c98e886266ddf557f29a28eb8b9784a8/src/test/kotlin/org/wfanet/measurement/kingdom/deploy/aws/postgres/AwsKingdomSchemaTest.kt#L30)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

There's already a JUnit4 rule. Please use that.

```
@Rule
public SingleInstancePostgresRule pg = EmbeddedPostgresRules.singleInstance();
```
</blockquote></details>

Perfect, please use this
___
*[src/test/kotlin/org/wfanet/measurement/kingdom/deploy/aws/postgres/Schemata.kt, line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/354#-MoGHAYQ2NS5z_uA-aTQ:-Mooal2_9L2RnLioF3c6:b862y6k) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/02c31ab3c98e886266ddf557f29a28eb8b9784a8/src/test/kotlin/org/wfanet/measurement/kingdom/deploy/aws/postgres/Schemata.kt#L1)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

If it's only used within the same package and isn't complex enough to possibly need its own test, then it's okay for test infra to be in `src/test` tree. That said, I assume this will be used by more than one package (off the top of my head the schema test, the internal service impl tests, and the integration tests are all in different packages).
</blockquote></details>

Yeah, this should see some reuse


<!-- Sent from Reviewable.io -->

2021-12-07 15:14 UTC, duliomatos1 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/354)* status: 1 of 8 files reviewed, 7 unresolved discussions (waiting on @chipingyeh, @duliomatos1, @efoxepstein, @SanjayVas, and @stevenwarejones)

___
*[src/test/kotlin/org/wfanet/measurement/kingdom/deploy/aws/postgres/AwsKingdomSchemaTest.kt, line 30 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/354#-MoG9WuS0kMWMiSCy8KU:-MqGiC1RC1ljIbzCdw-6:bb7f2mf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/02c31ab3c98e886266ddf557f29a28eb8b9784a8/src/test/kotlin/org/wfanet/measurement/kingdom/deploy/aws/postgres/AwsKingdomSchemaTest.kt#L30)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Perfect, please use this
</blockquote></details>

done
___
*[imports/java/com/opentable/components/BUILD.bazel, line 4 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/354#-MoGMA_NC32vqEckv-DI:-MqGfjGdDdvAyJkvAkjB:bb7f2mf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/02c31ab3c98e886266ddf557f29a28eb8b9784a8/imports/java/com/opentable/components/BUILD.bazel#L4)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The import path should match the Java package path that's defined. The package path appears to be `com.opentable.db.postgres`, therefore the file should be `imports/java/com/opentable/db/postgres/BUILD.bazel`.

Unless there are more targets defining different subsets, the target name should match the package name. In this case, `postgres`.
</blockquote></details>

done
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/aws/postgres/exchange.sdl, line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/354#-MoGHfD0CbDMBpfllvuR:-ModHw-D4qZDXTSnlAmv:b-v5g9s5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/02c31ab3c98e886266ddf557f29a28eb8b9784a8/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/aws/postgres/exchange.sdl#L1)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Is `.sdl` a common file extension for postgres schemas?
</blockquote></details>

actually could be sql, was just following the same convention from Spanner. Done
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/aws/postgres/exchange.sdl, line 16 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/354#-MoGHkew6ItfDlXvWy2J:-ModIS6X05A-h40XR9Iz:bb7f2mf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/02c31ab3c98e886266ddf557f29a28eb8b9784a8/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/aws/postgres/exchange.sdl#L16)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Nit: `exchange.sdl`? Maybe give the full path to disambiguate?
</blockquote></details>

done
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/aws/postgres/exchange.sdl, line 16 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/354#-MoGHoOO4OTM0LMmA_VR:-ModIQQ47zr1R_pnZUtr:bb7f2mf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/02c31ab3c98e886266ddf557f29a28eb8b9784a8/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/aws/postgres/exchange.sdl#L16)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

If this is for testing only, can you move it into a `testing` subdirector?
</blockquote></details>

done
___
*[src/test/kotlin/org/wfanet/measurement/kingdom/deploy/aws/postgres/Schemata.kt, line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/354#-MoGHAYQ2NS5z_uA-aTQ:-ModJlOKExvQhT7Cx7mt:bb7f2mf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/02c31ab3c98e886266ddf557f29a28eb8b9784a8/src/test/kotlin/org/wfanet/measurement/kingdom/deploy/aws/postgres/Schemata.kt#L1)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Yeah, this should see some reuse
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2021-12-07 15:22 UTC, efoxepstein approved these changes
> Reviewed 6 of 6 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/354)* status: all files reviewed, 4 unresolved discussions (waiting on @chipingyeh, @duliomatos1, @SanjayVas, and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2021-12-07 16:13 UTC, duliomatos1 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/354)* status: 5 of 9 files reviewed, 5 unresolved discussions (waiting on @chipingyeh, @duliomatos1, @efoxepstein, @SanjayVas, and @stevenwarejones)

___
*[third_party/rbe_configs/cc/BUILD, line 42 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/354#-MqKesVsDtg7CFcMNpDd:-MqKesVtCmZA7vS1uTyF:b-iv022v) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/487f102ba92e3ad6c35e23b6c390739241ecc92e/third_party/rbe_configs/cc/BUILD#L42)):*
> ```Starlark
>     name = "compiler_deps",
>     srcs = glob(
>         ["extra_tools/**"],
> ```

automatic changes from buildifier in this file


<!-- Sent from Reviewable.io -->

2021-12-07 16:14 UTC, duliomatos1 reviewed
> Dismissed @SanjayVas from 2 discussions.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/354)* status: 5 of 9 files reviewed, 3 unresolved discussions (waiting on @chipingyeh, @duliomatos1, @efoxepstein, @SanjayVas, and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2021-12-07 17:13 UTC, efoxepstein requested changes
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/354)* status: all files reviewed, 3 unresolved discussions (waiting on @chipingyeh, @duliomatos1, @SanjayVas, and @stevenwarejones)

___
*[third_party/rbe_configs/cc/BUILD, line 42 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/354#-MqKesVsDtg7CFcMNpDd:-MqKsYpJ5ARkgZjXwkhN:bj8t3ow) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/487f102ba92e3ad6c35e23b6c390739241ecc92e/third_party/rbe_configs/cc/BUILD#L42)):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

automatic changes from buildifier in this file
</blockquote></details>

Please don't run buildifier on `third_party`


<!-- Sent from Reviewable.io -->

2021-12-07 17:44 UTC, duliomatos1 reviewed
> Dismissed @efoxepstein from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/354)* status: 8 of 9 files reviewed, 2 unresolved discussions (waiting on @chipingyeh, @duliomatos1, @efoxepstein, @SanjayVas, and @stevenwarejones)

___
*[third_party/rbe_configs/cc/BUILD, line 42 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/354#-MqKesVsDtg7CFcMNpDd:-MqKt0kM612xWNxYB8Jf:b-sjl7pg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/487f102ba92e3ad6c35e23b6c390739241ecc92e/third_party/rbe_configs/cc/BUILD#L42)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

Please don't run buildifier on `third_party`
</blockquote></details>

Done. Reverted


<!-- Sent from Reviewable.io -->

2021-12-07 19:47 UTC, wangyaopw reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/354)* status: 8 of 9 files reviewed, 3 unresolved discussions (waiting on @chipingyeh, @duliomatos1, @efoxepstein, @SanjayVas, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/aws/postgres/BUILD.bazel, line 13 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/354#-MqLQFOnEH6q3wLBWgpY:-MqLQFOnEH6q3wLBWgpZ:b-j9aeq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a15d55759e68ec77a4a73a84d22c3635f84821ff/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/aws/postgres/BUILD.bazel#L13)):*
> ```Starlark
>         "@wfa_common_jvm//src/main/kotlin/org/wfanet/measurement/common",
>     ],
> )
> ```

Is postgres aws specific thing? if not, shouldn't we put it somewhere outside the `aws` directory?


<!-- Sent from Reviewable.io -->

2021-12-07 21:40 UTC, efoxepstein approved these changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/354)* status: all files reviewed, 3 unresolved discussions (waiting on @chipingyeh, @duliomatos1, @SanjayVas, and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2021-12-08 21:46 UTC, duliomatos1 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/354)* status: all files reviewed, 3 unresolved discussions (waiting on @chipingyeh, @duliomatos1, @SanjayVas, @stevenwarejones, and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/aws/postgres/BUILD.bazel, line 13 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/354#-MqLQFOnEH6q3wLBWgpY:-MqR-UyHA0LFHd2O8LnM:b6bpkl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/165f72b562bbc110128ae7ec6be9a187a0a73aab/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/aws/postgres/BUILD.bazel#L13)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

Is postgres aws specific thing? if not, shouldn't we put it somewhere outside the `aws` directory?
</blockquote></details>

This is specific to postgres/aws, there's a file with the same name for Spanner in another dir


<!-- Sent from Reviewable.io -->

2021-12-08 21:56 UTC, wangyaopw reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/354)* status: all files reviewed, 2 unresolved discussions (waiting on @chipingyeh, @duliomatos1, @SanjayVas, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/aws/postgres/BUILD.bazel, line 13 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/354#-MqLQFOnEH6q3wLBWgpY:-MqL_Os77UZoYjHSYC6c:b32wwp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/165f72b562bbc110128ae7ec6be9a187a0a73aab/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/aws/postgres/BUILD.bazel#L13)):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

This is specific to postgres/aws, there's a file with the same name for Spanner in another dir
</blockquote></details>

sg


<!-- Sent from Reviewable.io -->

2021-12-09 18:59 UTC, SanjayVas requested changes
> Reviewed 3 of 6 files at r2, 1 of 1 files at r3, 3 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/354)* status: all files reviewed, 4 unresolved discussions (waiting on @chipingyeh, @duliomatos1, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/aws/postgres/BUILD.bazel, line 6 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/354#-MqVXX46CY86i8WiTtb6:-MqVXX46CY86i8WiTtb7:b-v0tpal) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/165f72b562bbc110128ae7ec6be9a187a0a73aab/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/aws/postgres/BUILD.bazel#L6)):*
> ```
> schema
> ```
nit: use `schemata` for the rule name as well, or rename the file to `Schema` (matching singular vs. plural)
___
*[src/test/kotlin/org/wfanet/measurement/kingdom/deploy/aws/postgres/Schemata.kt, line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/354#-MoGHAYQ2NS5z_uA-aTQ:-MqVXmheC4tPFKAV5S0U:badk4ez) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/02c31ab3c98e886266ddf557f29a28eb8b9784a8/src/test/kotlin/org/wfanet/measurement/kingdom/deploy/aws/postgres/Schemata.kt#L1)):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

done
</blockquote></details>

This file still appears to be in a non-testing package?

To clarify, any production schema definition can be in a non-testing package of the `main` tree, as we'd also be using it as documentation of the production DB. This Kotlin file however should be in a `testing` package of the `main` tree, as it's only used in tests.


<!-- Sent from Reviewable.io -->

2021-12-09 20:45 UTC, duliomatos1 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/354)* status: all files reviewed, 4 unresolved discussions (waiting on @chipingyeh, @duliomatos1, @SanjayVas, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/aws/postgres/BUILD.bazel, line 6 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/354#-MqVXX46CY86i8WiTtb6:-MqVvRIg4DYWCO3MFSqZ:bizomyp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/165f72b562bbc110128ae7ec6be9a187a0a73aab/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/aws/postgres/BUILD.bazel#L6)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> schema
> ```
nit: use `schemata` for the rule name as well, or rename the file to `Schema` (matching singular vs. plural)
</blockquote></details>

will go for the first, "schemata"
___
*[src/test/kotlin/org/wfanet/measurement/kingdom/deploy/aws/postgres/Schemata.kt, line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/354#-MoGHAYQ2NS5z_uA-aTQ:-MqVvmh0-v1gpqXvWWHP:b-smgxco) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/02c31ab3c98e886266ddf557f29a28eb8b9784a8/src/test/kotlin/org/wfanet/measurement/kingdom/deploy/aws/postgres/Schemata.kt#L1)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This file still appears to be in a non-testing package?

To clarify, any production schema definition can be in a non-testing package of the `main` tree, as we'd also be using it as documentation of the production DB. This Kotlin file however should be in a `testing` package of the `main` tree, as it's only used in tests.
</blockquote></details>

I've understood we should move to `src/main` but didn' t get to also include within a `testing` package there. Wil move to `src/main/kotlin/org/wfanet/measurement/kingdom/deploy/aws/postgres/testing/Schemata.kt`


<!-- Sent from Reviewable.io -->

2021-12-10 14:19 UTC, duliomatos1 reviewed
> Dismissed @SanjayVas from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/354)* status: 5 of 9 files reviewed, 2 unresolved discussions (waiting on @chipingyeh, @duliomatos1, @efoxepstein, @SanjayVas, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/aws/postgres/BUILD.bazel, line 6 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/354#-MqVXX46CY86i8WiTtb6:-MqZhah8C01K9jxk5n8k:bb6un1j) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/165f72b562bbc110128ae7ec6be9a187a0a73aab/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/aws/postgres/BUILD.bazel#L6)):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

will go for the first, "schemata"
</blockquote></details>

Done
___
*[src/test/kotlin/org/wfanet/measurement/kingdom/deploy/aws/postgres/Schemata.kt, line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/354#-MoGHAYQ2NS5z_uA-aTQ:-MqZhUKd6qLm_eGS2DSG:bb6un1j) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/02c31ab3c98e886266ddf557f29a28eb8b9784a8/src/test/kotlin/org/wfanet/measurement/kingdom/deploy/aws/postgres/Schemata.kt#L1)):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

I've understood we should move to `src/main` but didn' t get to also include within a `testing` package there. Wil move to `src/main/kotlin/org/wfanet/measurement/kingdom/deploy/aws/postgres/testing/Schemata.kt`
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2021-12-10 15:56 UTC, efoxepstein approved these changes
> Reviewed 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/354)* status: all files reviewed, 2 unresolved discussions (waiting on @chipingyeh, @duliomatos1, and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2021-12-10 18:01 UTC, SanjayVas approved these changes
> Reviewed 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/354)* status: all files reviewed, 2 unresolved discussions (waiting on @chipingyeh, @duliomatos1, and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2021-12-10 18:26 UTC, wangyaopw approved these changes
> Reviewed 1 of 7 files at r1, 1 of 6 files at r2, 1 of 1 files at r3, 1 of 4 files at r4, 3 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/354)* status: all files reviewed, 2 unresolved discussions (waiting on @chipingyeh, @duliomatos1, and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2021-12-10 18:54 UTC, merged