Change format of event group page token.
world-federation-of-advertisers/cross-media-measurement pull request #384
Opened 2021-11-22 23:04 UTC by tristanvuong2021

2021-11-29 17:01 UTC, wangyaopw requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/384)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @tristanvuong2021 and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamEventGroups.kt, line 54 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/384#-MpgarHW5Y3lZTSBMJSx:-MpgarHW5Y3lZTSBMJSy:b-2m9rop) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d0695874ec44e12bbe75880aa72be329c45cb3ee/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamEventGroups.kt#L54)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>           (ExternalDataProviderId >= @$EXTERNAL_DATA_PROVIDER_ID_AFTER
>           AND ((ExternalDataProviderId > @$EXTERNAL_DATA_PROVIDER_ID_AFTER)
>           OR (ExternalDataProviderId = @$EXTERNAL_DATA_PROVIDER_ID_AFTER
>           AND ExternalEventGroupId > @$EXTERNAL_EVENT_GROUP_ID_AFTER)))
> ```
</details>


isn't this the same as 

```
(
ExternalDataProviderId > @$EXTERNAL_DATA_PROVIDER_ID_AFTER) 
OR (ExternalDataProviderId = @$EXTERNAL_DATA_PROVIDER_ID_AFTER AND 
ExternalEventGroupId > @$EXTERNAL_EVENT_GROUP_ID_AFTER)
)
```
?
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt, line 168 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/384#-MpgbweE6ZbnEi6ERVVd:-MpgbweE6ZbnEi6ERVVe:blmhnqx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d0695874ec44e12bbe75880aa72be329c45cb3ee/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt#L168)):*
> ```
> eventGroupPageToken.toByteArray().base64UrlEncode()
> ```
PageToken should only be set if there are remaining elements not returned yet.

One way of doing that is 
1. try to get limit+1 items.
2. if the query returns limit+1 items, return the first limit items and set the `nextPageToken`
3. if the query returns less than limit+1 items, return all of them and don't set the `nextPageToken`.


<!-- Sent from Reviewable.io -->

2021-11-29 22:14 UTC, tristanvuong2021 commented
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt, line 168 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/384#-MpgbweE6ZbnEi6ERVVd:-MphI8MXAeRkBk25R8de:brve343) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d0695874ec44e12bbe75880aa72be329c45cb3ee/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt#L168)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
> eventGroupPageToken.toByteArray().base64UrlEncode()
> ```
PageToken should only be set if there are remaining elements not returned yet.

One way of doing that is 
1. try to get limit+1 items.
2. if the query returns limit+1 items, return the first limit items and set the `nextPageToken`
3. if the query returns less than limit+1 items, return all of them and don't set the `nextPageToken`.
</blockquote></details>

Used the suggested method.


<!-- Sent from Reviewable.io -->

2021-11-29 22:20 UTC, tristanvuong2021 commented
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamEventGroups.kt, line 54 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/384#-MpgarHW5Y3lZTSBMJSx:-MphlzeKBDOKDMaZ7pRN:b-g968zr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d0695874ec44e12bbe75880aa72be329c45cb3ee/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamEventGroups.kt#L54)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
>           (ExternalDataProviderId >= @$EXTERNAL_DATA_PROVIDER_ID_AFTER
>           AND ((ExternalDataProviderId > @$EXTERNAL_DATA_PROVIDER_ID_AFTER)
>           OR (ExternalDataProviderId = @$EXTERNAL_DATA_PROVIDER_ID_AFTER
>           AND ExternalEventGroupId > @$EXTERNAL_EVENT_GROUP_ID_AFTER)))
> ```

isn't this the same as 

```
(
ExternalDataProviderId > @$EXTERNAL_DATA_PROVIDER_ID_AFTER) 
OR (ExternalDataProviderId = @$EXTERNAL_DATA_PROVIDER_ID_AFTER AND 
ExternalEventGroupId > @$EXTERNAL_EVENT_GROUP_ID_AFTER)
)
```
?
</blockquote></details>

I suppose this is premature optimization. I switched to the simpler version.


<!-- Sent from Reviewable.io -->

2021-11-29 22:35 UTC, wangyaopw requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/384)* status: 0 of 5 files reviewed, 6 unresolved discussions (waiting on @tristanvuong2021 and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt, line 105 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/384#-MphlewHBPoHYGw9YGOU:-MphlewI1gz7mrmM6Ri1:b82y7of) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/168ca3b514774f5cc0259c7ac279deaf6d221718/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt#L105)):*
> ```
> limit = pageSize
> ```
limit = pageSize + 1
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt, line 143 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/384#-MphliWS5RVxu2XfvU5e:-MphliWS5RVxu2XfvU5f:b-39qp1i) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/168ca3b514774f5cc0259c7ac279deaf6d221718/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt#L143)):*
> ```
>           // get 1 more than the actual page size for deciding whether or not to set page token
>           this@streamEventGroupsRequest.limit += 1
> ```
just do `limit = pageSize + 1` above
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt, line 156 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/384#-MphmgCX5qFxb2QWOG5-:-MphmgCX5qFxb2QWOG50:btgtmtb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/168ca3b514774f5cc0259c7ac279deaf6d221718/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt#L156)):*
<details><summary><i alt="summary">Quoted 21 lines of code…</i></summary>

> ```
>       // nothing for next page so page token isn't set
>       if (results.size < streamRequest.limit) {
>         eventGroups += results.map(InternalEventGroup::toEventGroup)
>         // next page has at least 1 result so page token is set
>       } else {
>         eventGroups +=
>           results.subList(0, streamRequest.limit - 1).map(InternalEventGroup::toEventGroup)
>         val eventGroupPageToken = eventGroupPageToken {
>           this.pageSize = streamRequest.limit - 1
>           externalDataProviderId = streamRequest.filter.externalDataProviderId
>           for (externalMeasurementConsumerId in
>             streamRequest.filter.externalMeasurementConsumerIdsList.sortedDescending()) {
>             externalMeasurementConsumerIds += externalMeasurementConsumerId
>           }
>           lastEventGroup =
>             previousPageEnd {
>               externalDataProviderId = results.last().externalDataProviderId
>               externalEventGroupId = results.last().externalEventGroupId
>             }
>         }
>         nextPageToken = eventGroupPageToken.toByteArray().base64UrlEncode()
> ```
</details>


How about

```
eventGroups += results.subList(0,  min(results.size, pageSize)).map(InternalEventGroup::toEventGroup)
if (results.size == pageSize+1) {
        val eventGroupPageToken = eventGroupPageToken {
          this.pageSize = pageSize
          externalDataProviderId = streamRequest.filter.externalDataProviderId
          externalMeasurementConsumerIds += streamRequest.filter.externalMeasurementConsumerIdsList
          lastEventGroup =
            previousPageEnd {
              externalDataProviderId = results[pageSize-1].externalDataProviderId
              externalEventGroupId = results[pageSize-1].externalEventGroupId
            }
        }
        nextPageToken = eventGroupPageToken.toByteArray().base64UrlEncode()
} 
```

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt, line 167 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/384#-Mpho7L58QOzVZwpWCfv:-Mpho7L58QOzVZwpWCfw:b-xpr1uj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/168ca3b514774f5cc0259c7ac279deaf6d221718/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt#L167)):*
> ```
> sortedDescending(
> ```
why sorting here?
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt, line 172 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/384#-Mpho-4E1_kUpxZMn7no:-Mpho-4E1_kUpxZMn7np:b-4kubar) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/168ca3b514774f5cc0259c7ac279deaf6d221718/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt#L172)):*
> ```
>  results.last()
> ```
Here should use the last returned eventGroup. `results.last()` is not returned.

You may need to update your test


<!-- Sent from Reviewable.io -->

2021-11-29 22:39 UTC, wangyaopw requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/384)* status: 0 of 5 files reviewed, 7 unresolved discussions (waiting on @tristanvuong2021 and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt, line 323 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/384#-MphqLB33G5hZSu4Iqu4:-Mphoy-w92OKassJ6Gg3:btomx58) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/168ca3b514774f5cc0259c7ac279deaf6d221718/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt#L323)):*
> ```
> assertThat(eventGroups).hasSize(1)
> ```
Only asserting size is not enough. Assert the result is equal to the expected result, i.e., contains the expected eventGroup and pagetoken.

Same for the second result.


<!-- Sent from Reviewable.io -->

2021-11-29 23:50 UTC, tristanvuong2021 commented
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt, line 143 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/384#-MphliWS5RVxu2XfvU5e:-MphvVU27cpjMfLTU19-:b-hjace7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/168ca3b514774f5cc0259c7ac279deaf6d221718/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt#L143)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
>           // get 1 more than the actual page size for deciding whether or not to set page token
>           this@streamEventGroupsRequest.limit += 1
> ```
just do `limit = pageSize + 1` above
</blockquote></details>

I need more than just that above since I may use the page token's page size instead. Added some extra +1's when checking the page token.


<!-- Sent from Reviewable.io -->

2021-11-29 23:53 UTC, tristanvuong2021 commented
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt, line 167 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/384#-Mpho7L58QOzVZwpWCfv:-Mpi6P5ZBmlwTObKggvf:bemmrmk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/168ca3b514774f5cc0259c7ac279deaf6d221718/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt#L167)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
> sortedDescending(
> ```
why sorting here?
</blockquote></details>

Think this is from some testing I was doing. Removed.


<!-- Sent from Reviewable.io -->

2021-11-29 23:56 UTC, tristanvuong2021 commented
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt, line 156 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/384#-MphmgCX5qFxb2QWOG5-:-Mpi6rcuEMZhsniCexNF:b-jqfj3s) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/168ca3b514774f5cc0259c7ac279deaf6d221718/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt#L156)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
>       // nothing for next page so page token isn't set
>       if (results.size < streamRequest.limit) {
>         eventGroups += results.map(InternalEventGroup::toEventGroup)
>         // next page has at least 1 result so page token is set
>       } else {
>         eventGroups +=
>           results.subList(0, streamRequest.limit - 1).map(InternalEventGroup::toEventGroup)
>         val eventGroupPageToken = eventGroupPageToken {
>           this.pageSize = streamRequest.limit - 1
>           externalDataProviderId = streamRequest.filter.externalDataProviderId
>           for (externalMeasurementConsumerId in
>             streamRequest.filter.externalMeasurementConsumerIdsList.sortedDescending()) {
>             externalMeasurementConsumerIds += externalMeasurementConsumerId
>           }
>           lastEventGroup =
>             previousPageEnd {
>               externalDataProviderId = results.last().externalDataProviderId
>               externalEventGroupId = results.last().externalEventGroupId
>             }
>         }
>         nextPageToken = eventGroupPageToken.toByteArray().base64UrlEncode()
> ```

How about

```
eventGroups += results.subList(0,  min(results.size, pageSize)).map(InternalEventGroup::toEventGroup)
if (results.size == pageSize+1) {
        val eventGroupPageToken = eventGroupPageToken {
          this.pageSize = pageSize
          externalDataProviderId = streamRequest.filter.externalDataProviderId
          externalMeasurementConsumerIds += streamRequest.filter.externalMeasurementConsumerIdsList
          lastEventGroup =
            previousPageEnd {
              externalDataProviderId = results[pageSize-1].externalDataProviderId
              externalEventGroupId = results[pageSize-1].externalEventGroupId
            }
        }
        nextPageToken = eventGroupPageToken.toByteArray().base64UrlEncode()
} 
```

</blockquote></details>

Used the limit of the stream request instead of pageSize because pageSize is not necessarily the final limit depending on the page token in the request.


<!-- Sent from Reviewable.io -->

2021-11-29 23:56 UTC, tristanvuong2021 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/384)* status: 0 of 5 files reviewed, 7 unresolved discussions (waiting on @tristanvuong2021 and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt, line 105 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/384#-MphlewHBPoHYGw9YGOU:-Mpi5Yz70uVjuVswOiiL:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/168ca3b514774f5cc0259c7ac279deaf6d221718/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt#L105)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
> limit = pageSize
> ```
limit = pageSize + 1
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt, line 172 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/384#-Mpho-4E1_kUpxZMn7no:-Mpi6N_c8E_6U14V79K0:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/168ca3b514774f5cc0259c7ac279deaf6d221718/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt#L172)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
>  results.last()
> ```
Here should use the last returned eventGroup. `results.last()` is not returned.

You may need to update your test
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-30 16:58 UTC, wangyaopw requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/384)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @tristanvuong2021 and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt, line 143 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/384#-MphliWS5RVxu2XfvU5e:-MpllK79AMIU1vmmzSBT:bvap4y1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/168ca3b514774f5cc0259c7ac279deaf6d221718/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt#L143)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

I need more than just that above since I may use the page token's page size instead. Added some extra +1's when checking the page token.
</blockquote></details>

How about adding a helper method to convert the public request to an internal pageToken.

`ListEventGroupsRequest.toEventGroupPageToken()` If there is a token in the request, use it, otherwise, build an initial token from it. This extension method will also take care of validating the request.

Then you can have another method `EventGroupPageToken.toStreamEventGroupsRequest()`.


<!-- Sent from Reviewable.io -->

2021-11-30 18:36 UTC, tristanvuong2021 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/384)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt, line 143 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/384#-MphliWS5RVxu2XfvU5e:-Mpm7VU2-ZEPDrkCXOv1:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/168ca3b514774f5cc0259c7ac279deaf6d221718/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt#L143)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

How about adding a helper method to convert the public request to an internal pageToken.

`ListEventGroupsRequest.toEventGroupPageToken()` If there is a token in the request, use it, otherwise, build an initial token from it. This extension method will also take care of validating the request.

Then you can have another method `EventGroupPageToken.toStreamEventGroupsRequest()`.

</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt, line 323 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/384#-MphqLB33G5hZSu4Iqu4:-Mpm7W456snhmzmdGKhK:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/168ca3b514774f5cc0259c7ac279deaf6d221718/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt#L323)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
> assertThat(eventGroups).hasSize(1)
> ```
Only asserting size is not enough. Assert the result is equal to the expected result, i.e., contains the expected eventGroup and pagetoken.

Same for the second result.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-30 18:57 UTC, wangyaopw requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/384)* status: 0 of 5 files reviewed, 4 unresolved discussions (waiting on @tristanvuong2021 and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt, line 101 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/384#-Mpm86tjEnrs5TMplqoT:-Mpm86tjEnrs5TMplqoU:b-9lcq8e) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f27c1b08a9962e750ba2852f3e9066d41aa1a8e9/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt#L101)):*
> ```
> streamRequest.limit - 1
> ```
use `eventGroupPageToken.pageSize` here, easier to understand I think
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt, line 213 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/384#-Mpm8rVw20De9lXOs-w8:-Mpm8rVw20De9lXOs-w9:b-jx04nh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f27c1b08a9962e750ba2852f3e9066d41aa1a8e9/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt#L213)):*
<details><summary><i alt="summary">Quoted 50 lines of code…</i></summary>

> ```
>   val newEventGroupPageToken = eventGroupPageToken {
>     pageSize =
>       when {
>         source.pageSize < MIN_PAGE_SIZE -> DEFAULT_PAGE_SIZE
>         source.pageSize > MAX_PAGE_SIZE -> MAX_PAGE_SIZE
>         else -> source.pageSize
>       }
> 
>     if (parentKey.dataProviderId != WILDCARD) {
>       externalDataProviderId = apiIdToExternalId(parentKey.dataProviderId)
>     }
> 
>     externalMeasurementConsumerIds +=
>       source.filter.measurementConsumersList.map { measurementConsumerName ->
>         grpcRequireNotNull(MeasurementConsumerKey.fromName(measurementConsumerName)) {
>           "Measurement consumer name in filter invalid"
>         }
>           .let { key -> apiIdToExternalId(key.measurementConsumerId) }
>       }
> 
>     lastEventGroup = EventGroupPageToken.PreviousPageEnd.getDefaultInstance()
>   }
> 
>   if (source.pageToken.isNotBlank()) {
>     val oldEventGroupPageToken = EventGroupPageToken.parseFrom(source.pageToken.base64UrlDecode())
> 
>     grpcRequire(
>       newEventGroupPageToken.externalDataProviderId == oldEventGroupPageToken.externalDataProviderId
>     ) { "Arguments must be kept the same when using a page token" }
> 
>     grpcRequire(
>       newEventGroupPageToken.externalMeasurementConsumerIdsList.containsAll(
>         oldEventGroupPageToken.externalMeasurementConsumerIdsList
>       ) &&
>         oldEventGroupPageToken.externalMeasurementConsumerIdsList.containsAll(
>           newEventGroupPageToken.externalMeasurementConsumerIdsList
>         )
>     ) { "Arguments must be kept the same when using a page token" }
> 
>     return if (source.pageSize != 0 &&
>         source.pageSize >= MIN_PAGE_SIZE &&
>         source.pageSize <= MAX_PAGE_SIZE
>     ) {
>       oldEventGroupPageToken.copy { pageSize = newEventGroupPageToken.pageSize }
>     } else {
>       oldEventGroupPageToken
>     }
>   } else {
>     return newEventGroupPageToken
>   }
> ```
</details>

This is a little hard to follow.

maybe doing it in this way

```
return if (source.pageToken.isNotBlank()) { 
    val tokenFromRequest = EventGroupPageToken.parseFrom(source.pageToken.base64UrlDecode())
    // 1.  validate the token and other fields in the request
    /// 2. update pageSize if needed.
    tokenFromRequest
} else {
    // construct a new one from public request
}
```
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt, line 323 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/384#-MphqLB33G5hZSu4Iqu4:-MpmAonfDy_TfvJthz7_:bnm7ipc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/168ca3b514774f5cc0259c7ac279deaf6d221718/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt#L323)):*
> ```
> containsAnyOf(eventGroup1, eventGroup2)
> ```
If you use `FixedIdGenerator`, you can check against a specific eventGroup


<!-- Sent from Reviewable.io -->

2021-11-30 20:10 UTC, tristanvuong2021 commented
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt, line 323 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/384#-MphqLB33G5hZSu4Iqu4:-MpmSTJJAvEOEAIrnMVH:bzdl05z) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/168ca3b514774f5cc0259c7ac279deaf6d221718/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt#L323)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
> containsAnyOf(eventGroup1, eventGroup2)
> ```
If you use `FixedIdGenerator`, you can check against a specific eventGroup


</blockquote></details>

I decided not to used a FixedIdGenerator, I would have to change a lot more than just this to get it to work since some tests create 3 certificates and each one would need a different id so I would be constantly changing the ids.


<!-- Sent from Reviewable.io -->

2021-11-30 20:10 UTC, tristanvuong2021 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/384)* status: 0 of 5 files reviewed, 4 unresolved discussions (waiting on @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt, line 101 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/384#-Mpm86tjEnrs5TMplqoT:-MpmSS564mMsE3dNeoPU:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f27c1b08a9962e750ba2852f3e9066d41aa1a8e9/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt#L101)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
> streamRequest.limit - 1
> ```
use `eventGroupPageToken.pageSize` here, easier to understand I think
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt, line 213 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/384#-Mpm8rVw20De9lXOs-w8:-MpmSSfV2CjHtkKYsQNT:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f27c1b08a9962e750ba2852f3e9066d41aa1a8e9/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt#L213)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
>   val newEventGroupPageToken = eventGroupPageToken {
>     pageSize =
>       when {
>         source.pageSize < MIN_PAGE_SIZE -> DEFAULT_PAGE_SIZE
>         source.pageSize > MAX_PAGE_SIZE -> MAX_PAGE_SIZE
>         else -> source.pageSize
>       }
> 
>     if (parentKey.dataProviderId != WILDCARD) {
>       externalDataProviderId = apiIdToExternalId(parentKey.dataProviderId)
>     }
> 
>     externalMeasurementConsumerIds +=
>       source.filter.measurementConsumersList.map { measurementConsumerName ->
>         grpcRequireNotNull(MeasurementConsumerKey.fromName(measurementConsumerName)) {
>           "Measurement consumer name in filter invalid"
>         }
>           .let { key -> apiIdToExternalId(key.measurementConsumerId) }
>       }
> 
>     lastEventGroup = EventGroupPageToken.PreviousPageEnd.getDefaultInstance()
>   }
> 
>   if (source.pageToken.isNotBlank()) {
>     val oldEventGroupPageToken = EventGroupPageToken.parseFrom(source.pageToken.base64UrlDecode())
> 
>     grpcRequire(
>       newEventGroupPageToken.externalDataProviderId == oldEventGroupPageToken.externalDataProviderId
>     ) { "Arguments must be kept the same when using a page token" }
> 
>     grpcRequire(
>       newEventGroupPageToken.externalMeasurementConsumerIdsList.containsAll(
>         oldEventGroupPageToken.externalMeasurementConsumerIdsList
>       ) &&
>         oldEventGroupPageToken.externalMeasurementConsumerIdsList.containsAll(
>           newEventGroupPageToken.externalMeasurementConsumerIdsList
>         )
>     ) { "Arguments must be kept the same when using a page token" }
> 
>     return if (source.pageSize != 0 &&
>         source.pageSize >= MIN_PAGE_SIZE &&
>         source.pageSize <= MAX_PAGE_SIZE
>     ) {
>       oldEventGroupPageToken.copy { pageSize = newEventGroupPageToken.pageSize }
>     } else {
>       oldEventGroupPageToken
>     }
>   } else {
>     return newEventGroupPageToken
>   }
> ```
This is a little hard to follow.

maybe doing it in this way

```
return if (source.pageToken.isNotBlank()) { 
    val tokenFromRequest = EventGroupPageToken.parseFrom(source.pageToken.base64UrlDecode())
    // 1.  validate the token and other fields in the request
    /// 2. update pageSize if needed.
    tokenFromRequest
} else {
    // construct a new one from public request
}
```

</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-11-30 21:02 UTC, wangyaopw requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/384)* status: 0 of 5 files reviewed, 3 unresolved discussions (waiting on @tristanvuong2021 and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt, line 88 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/384#-MpmdvHr8LI0Rgu16ujR:-MpmdvHr8LI0Rgu16ujS:b-1w0afi) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/83c892ae8c66ec7fe4523280f9e712484363089f/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt#L88)):*
> ```
>     // limit is 1 more than the desired page size to determine whether or not a next page exists
>     val streamRequest = eventGroupPageToken.toStreamEventGroupsRequest()
> ```
delete
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt, line 92 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/384#-MpmdJaT-ViuJ-n4Nz9k:-MpmdJaT-ViuJ-n4Nz9l:bfr0iuf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/83c892ae8c66ec7fe4523280f9e712484363089f/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt#L92)):*
> ```
> streamRequest
> ```
inline `eventGroupPageToken.toStreamEventGroupsRequest()`
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt, line 109 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/384#-MpmdRVB3-ZgDsCm-LSD:-MpmdRVCDOoZPq91ids5:bkeaho2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/83c892ae8c66ec7fe4523280f9e712484363089f/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt#L109)):*
<details><summary><i alt="summary">Quoted 10 lines of code…</i></summary>

> ```
>         val pageToken = eventGroupPageToken {
>           this.pageSize = eventGroupPageToken.pageSize
>           externalDataProviderId = streamRequest.filter.externalDataProviderId
>           externalMeasurementConsumerIds += streamRequest.filter.externalMeasurementConsumerIdsList
>           lastEventGroup =
>             previousPageEnd {
>               externalDataProviderId = results[results.lastIndex - 1].externalDataProviderId
>               externalEventGroupId = results[results.lastIndex - 1].externalEventGroupId
>             }
>         }
> ```
</details>


just update the lastEventGroup inside the created eventGroupPageToken in line 87. All other fields are the same.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt, line 323 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/384#-MphqLB33G5hZSu4Iqu4:-Mpme0ZnAHBlE6GdP4bq:b32wwp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/168ca3b514774f5cc0259c7ac279deaf6d221718/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt#L323)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

I decided not to used a FixedIdGenerator, I would have to change a lot more than just this to get it to work since some tests create 3 certificates and each one would need a different id so I would be constantly changing the ids.
</blockquote></details>

sg


<!-- Sent from Reviewable.io -->

2021-11-30 21:03 UTC, wangyaopw approved these changes
> Reviewed 1 of 5 files at r1, 1 of 3 files at r2, 2 of 3 files at r3, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/384)* status: all files reviewed, 3 unresolved discussions (waiting on @tristanvuong2021)



<!-- Sent from Reviewable.io -->

2021-11-30 21:49 UTC, tristanvuong2021 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/384)* status: 4 of 5 files reviewed, 3 unresolved discussions (waiting on @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt, line 88 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/384#-MpmdvHr8LI0Rgu16ujR:-MpmonxaBjrk_8kDQ08W:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/83c892ae8c66ec7fe4523280f9e712484363089f/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt#L88)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
>     // limit is 1 more than the desired page size to determine whether or not a next page exists
>     val streamRequest = eventGroupPageToken.toStreamEventGroupsRequest()
> ```
delete
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt, line 92 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/384#-MpmdJaT-ViuJ-n4Nz9k:-MpmonYsDfxyd3NybtIW:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/83c892ae8c66ec7fe4523280f9e712484363089f/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt#L92)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
> streamRequest
> ```
inline `eventGroupPageToken.toStreamEventGroupsRequest()`
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt, line 109 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/384#-MpmdRVB3-ZgDsCm-LSD:-MpmomX7BhjRRswK5y9W:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/83c892ae8c66ec7fe4523280f9e712484363089f/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt#L109)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
>         val pageToken = eventGroupPageToken {
>           this.pageSize = eventGroupPageToken.pageSize
>           externalDataProviderId = streamRequest.filter.externalDataProviderId
>           externalMeasurementConsumerIds += streamRequest.filter.externalMeasurementConsumerIdsList
>           lastEventGroup =
>             previousPageEnd {
>               externalDataProviderId = results[results.lastIndex - 1].externalDataProviderId
>               externalEventGroupId = results[results.lastIndex - 1].externalEventGroupId
>             }
>         }
> ```

just update the lastEventGroup inside the created eventGroupPageToken in line 87. All other fields are the same.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-12-02 16:25 UTC, stevenwarejones approved these changes
> Reviewed 1 of 5 files at r1, 1 of 3 files at r2, 2 of 3 files at r3, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/384)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)



<!-- Sent from Reviewable.io -->

2021-12-02 17:35 UTC, merged