Change measurement page token.
world-federation-of-advertisers/cross-media-measurement pull request #391
Opened 2021-12-03 18:15 UTC by tristanvuong2021

2021-12-04 20:52 UTC, wangyaopw requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/391)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021 and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurements.kt, line 33 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/391#-Mq6C87VE-TAhXNpQLRh:-Mq6C87VE-TAhXNpQLRi:b-c2ktg4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/78de999578100a16bee7ddf81606bbd321d102c0/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurements.kt#L33)):*
> ```
> "ORDER BY ExternalMeasurementId ASC"
> ```
Also order by updateTime. The system API needs to send the measurements in the ascend timestamp order to duchies.
```ORDER BY UpdateTime ASC,  ExternalMeasurementId ASC```

Note: this was already a bug in the old code.


<!-- Sent from Reviewable.io -->

2021-12-06 17:57 UTC, wangyaopw requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/391)* status: 0 of 5 files reviewed, 4 unresolved discussions (waiting on @tristanvuong2021 and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt, line 260 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/391#-MqFmBQ807BYhxosPZhh:-MqFmBQ807BYhxosPZhi:b-myr9o1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/78de999578100a16bee7ddf81606bbd321d102c0/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt#L260)):*
<details><summary><i alt="summary">Quoted 13 lines of code…</i></summary>

> ```
>     when (state) {
>       State.AWAITING_REQUISITION_FULFILLMENT -> {
>         internalStatesList.add(InternalState.PENDING_REQUISITION_PARAMS)
>         internalStatesList.add(InternalState.PENDING_REQUISITION_FULFILLMENT)
>       }
>       State.COMPUTING -> {
>         internalStatesList.add(InternalState.PENDING_PARTICIPANT_CONFIRMATION)
>         internalStatesList.add(InternalState.PENDING_COMPUTATION)
>       }
>       State.SUCCEEDED -> internalStatesList.add(InternalState.SUCCEEDED)
>       State.FAILED -> internalStatesList.add(InternalState.FAILED)
>       State.CANCELLED -> internalStatesList.add(InternalState.CANCELLED)
>       State.STATE_UNSPECIFIED, State.UNRECOGNIZED ->
> ```
</details>

move this as as extension function `State.toInternalState(): InternalState` inside `v2alpha/ProtoConversions.kt`.

then here just use

```
return this.map{it.ToInternalState()}
```
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt, line 293 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/391#-MqFmUAG0NRMuDk9nIWS:-MqFmUAG0NRMuDk9nIWT:byae6tt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/78de999578100a16bee7ddf81606bbd321d102c0/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt#L293)):*
> ```
> source.pageSize in 1..MAX_PAGE_SIZE
> ```
I guess `source.pageSize>0 && source.pageSize <= MAX_PAGE_SIZE` is more efficient.
___
*[src/main/proto/wfa/measurement/internal/kingdom/measurements_service.proto, line 97 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/391#-MqFpKWW7SXprBmjByDI:-MqFoWz14ZjtdZVHYdwV:b-12hlpg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/78de999578100a16bee7ddf81606bbd321d102c0/src/main/proto/wfa/measurement/internal/kingdom/measurements_service.proto#L97)):*
> ```protobuf
> }
> 
> message MeasurementPageToken {
> ```

I feel this shouldn't reside in the internal measurements_service.proto file. It is not part of the internal serive, it is used purely in the public API.


<!-- Sent from Reviewable.io -->

2021-12-06 18:03 UTC, wangyaopw requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/391)* status: 0 of 5 files reviewed, 4 unresolved discussions (waiting on @tristanvuong2021 and @wangyaopw)

___
*[src/main/proto/wfa/measurement/internal/kingdom/measurements_service.proto, line 97 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/391#-MqFpKWW7SXprBmjByDI:-MqFuYq5-ZkiSDT5-kiL:b-psq7ep) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/78de999578100a16bee7ddf81606bbd321d102c0/src/main/proto/wfa/measurement/internal/kingdom/measurements_service.proto#L97)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

I feel this shouldn't reside in the internal measurements_service.proto file. It is not part of the internal serive, it is used purely in the public API.
</blockquote></details>

@sanjayvas  


<!-- Sent from Reviewable.io -->

2021-12-06 18:09 UTC, wangyaopw requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/391)* status: 0 of 5 files reviewed, 4 unresolved discussions (waiting on @tristanvuong2021 and @wangyaopw)

___
*[src/main/proto/wfa/measurement/internal/kingdom/measurements_service.proto, line 97 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/391#-MqFpKWW7SXprBmjByDI:-MqFvsmR2rjzXF2SNGfx:b-e4n4rs) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/78de999578100a16bee7ddf81606bbd321d102c0/src/main/proto/wfa/measurement/internal/kingdom/measurements_service.proto#L97)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

@sanjayvas  
</blockquote></details>

Maybe put all pageToken inside `cross-media-measurement/src/main/proto/wfa/measurement/api/v2alpha/PageToken.proto`


<!-- Sent from Reviewable.io -->

2021-12-07 20:25 UTC, tristanvuong2021 commented
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurements.kt, line 33 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/391#-Mq6C87VE-TAhXNpQLRh:-MqLZT64D6s-yQHFwtol:b-9rvyux) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3f753eba6526aa9934d409df050c074f35930fd4/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurements.kt#L33)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
> "ORDER BY ExternalMeasurementId ASC"
> ```
Also order by updateTime. The system API needs to send the measurements in the ascend timestamp order to duchies.
```ORDER BY UpdateTime ASC,  ExternalMeasurementId ASC```

Note: this was already a bug in the old code.
</blockquote></details>

It wouldn't make sense to order by both since that would mess up the pages when using a page token. So I made order by updatetime default and order by id an option.


<!-- Sent from Reviewable.io -->

2021-12-07 20:26 UTC, tristanvuong2021 commented
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt, line 293 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/391#-MqFmUAG0NRMuDk9nIWS:-MqLZmQG5KXa85J1wuTT:b-9ato2t) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3f753eba6526aa9934d409df050c074f35930fd4/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt#L293)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
> source.pageSize in 1..MAX_PAGE_SIZE
> ```
I guess `source.pageSize>0 && source.pageSize <= MAX_PAGE_SIZE` is more efficient.
</blockquote></details>

I looked it up and the implementation of the ... actually does that.


<!-- Sent from Reviewable.io -->

2021-12-07 20:26 UTC, tristanvuong2021 commented
___
*[src/main/proto/wfa/measurement/internal/kingdom/measurements_service.proto, line 97 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/391#-MqFpKWW7SXprBmjByDI:-MqLZyAR8KTkiS4nlOC2:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3f753eba6526aa9934d409df050c074f35930fd4/src/main/proto/wfa/measurement/internal/kingdom/measurements_service.proto#L97)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

Maybe put all pageToken inside `cross-media-measurement/src/main/proto/wfa/measurement/api/v2alpha/PageToken.proto`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-12-07 20:49 UTC, wangyaopw requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/391)* status: 0 of 12 files reviewed, 2 unresolved discussions (waiting on @tristanvuong2021 and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurements.kt, line 33 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/391#-Mq6C87VE-TAhXNpQLRh:-MqLcq8d0ksvzPgWF0UF:b-1v43to) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3f753eba6526aa9934d409df050c074f35930fd4/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurements.kt#L33)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

It wouldn't make sense to order by both since that would mess up the pages when using a page token. So I made order by updatetime default and order by id an option.
</blockquote></details>

We need to order by both for the system API to work.

It is no different from what you did here for the eventGroups https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamEventGroups.kt#L29

The query will be 
```
updated_after > @$UPDATED_AFTER  or (updated_after = @$UPDATED_AFTER & externalMeasurementId > @$EXTERNAL_MEASUREMENT_ID)
```


<!-- Sent from Reviewable.io -->

2021-12-07 20:51 UTC, wangyaopw requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/391)* status: 0 of 12 files reviewed, 3 unresolved discussions (waiting on @tristanvuong2021 and @wangyaopw)

___
*[src/main/proto/wfa/measurement/api/v2alpha/page_token.proto, line 40 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/391#-MqLeIoa9IaP-7u6zrha:-MqLeIoa9IaP-7u6zrhb:biwfe4s) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7117f8f7b9ffaa6b3bf6410f90005861c89ef777/src/main/proto/wfa/measurement/api/v2alpha/page_token.proto#L40)):*
> ```
> fixed64 external_measurement_id = 1;
> ```
add `update_time` in `PreviousPageEnd`


<!-- Sent from Reviewable.io -->

2021-12-07 22:52 UTC, tristanvuong2021 commented
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurements.kt, line 33 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/391#-Mq6C87VE-TAhXNpQLRh:-MqM4_9J9L0ygyo8YdJ_:b-1bwgt6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3f753eba6526aa9934d409df050c074f35930fd4/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurements.kt#L33)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

We need to order by both for the system API to work.

It is no different from what you did here for the eventGroups https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamEventGroups.kt#L29

The query will be 
```
updated_after > @$UPDATED_AFTER  or (updated_after = @$UPDATED_AFTER & externalMeasurementId > @$EXTERNAL_MEASUREMENT_ID)
```
</blockquote></details>

UpdateTime changes though so it is a bit different. Guess it is fine though, if it matters, it could be changed later to only order by both if update time is specifically set in the public api filter.


<!-- Sent from Reviewable.io -->

2021-12-07 23:19 UTC, tristanvuong2021 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/391)* status: 0 of 12 files reviewed, 3 unresolved discussions (waiting on @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt, line 260 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/391#-MqFmBQ807BYhxosPZhh:-MqLZleOECdYpW_-WmN6:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3f753eba6526aa9934d409df050c074f35930fd4/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt#L260)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
>     when (state) {
>       State.AWAITING_REQUISITION_FULFILLMENT -> {
>         internalStatesList.add(InternalState.PENDING_REQUISITION_PARAMS)
>         internalStatesList.add(InternalState.PENDING_REQUISITION_FULFILLMENT)
>       }
>       State.COMPUTING -> {
>         internalStatesList.add(InternalState.PENDING_PARTICIPANT_CONFIRMATION)
>         internalStatesList.add(InternalState.PENDING_COMPUTATION)
>       }
>       State.SUCCEEDED -> internalStatesList.add(InternalState.SUCCEEDED)
>       State.FAILED -> internalStatesList.add(InternalState.FAILED)
>       State.CANCELLED -> internalStatesList.add(InternalState.CANCELLED)
>       State.STATE_UNSPECIFIED, State.UNRECOGNIZED ->
> ```
move this as as extension function `State.toInternalState(): InternalState` inside `v2alpha/ProtoConversions.kt`.

then here just use

```
return this.map{it.ToInternalState()}
```
</blockquote></details>

Done.
___
*[src/main/proto/wfa/measurement/api/v2alpha/page_token.proto, line 40 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/391#-MqLeIoa9IaP-7u6zrha:-MqMBTBL9588KFtr9UPI:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7117f8f7b9ffaa6b3bf6410f90005861c89ef777/src/main/proto/wfa/measurement/api/v2alpha/page_token.proto#L40)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
> fixed64 external_measurement_id = 1;
> ```
add `update_time` in `PreviousPageEnd`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-12-07 23:35 UTC, wangyaopw requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/391)* status: 0 of 12 files reviewed, 4 unresolved discussions (waiting on @tristanvuong2021 and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurements.kt, line 63 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/391#-MqMD9bRCm8TGfs-ti4N:-MqMD9bSCXEQupJ0qj_U:btro4rj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/382e88ca2faf824ebbec1a2e217b9dd094db4f79/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurements.kt#L63)):*
> ```
>  > 0L
> ```
Should be `!= 0L`
fixed64 can be negative.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt, line 279 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/391#-MqMExdp3G73zYvaBOV6:-MqMExdp3G73zYvaBOV7:bayu4af) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/382e88ca2faf824ebbec1a2e217b9dd094db4f79/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt#L279)):*
> ```
> lastMeasurement = MeasurementPageToken.PreviousPageEnd.getDefaultInstance()
> ```
delete
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt, line 295 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/391#-MqMEatDAIm_06HfFPDj:-MqMEatDAIm_06HfFPDk:bgq3h9z) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/382e88ca2faf824ebbec1a2e217b9dd094db4f79/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt#L295)):*
> ```
>  externalMeasurementIdAfter = source.lastMeasurement.externalMeasurementId
> ```
here should be something like
```
 if source.hasPreviousPageEnd() {
   updateAfter = xxx
    externalMeasurementIdAfter = xxx
}
```


<!-- Sent from Reviewable.io -->

2021-12-07 23:37 UTC, wangyaopw requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/391)* status: 0 of 12 files reviewed, 5 unresolved discussions (waiting on @tristanvuong2021 and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt, line 91 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/391#-MqMFFkm3uz1mL-W6Bl3:-MqMFFkm3uz1mL-W6Bl4:bi3rkyy) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/382e88ca2faf824ebbec1a2e217b9dd094db4f79/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt#L91)):*
> ```
> fun List<State>.toInternalState(): List<InternalMeasurement.State> {
> ```

For the helper method, we only need `fun State.toInternalState(): InternalMeasurement.State`

The converting a list happens at the user of this helper method


<!-- Sent from Reviewable.io -->

2021-12-07 23:42 UTC, wangyaopw requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/391)* status: 0 of 12 files reviewed, 9 unresolved discussions (waiting on @tristanvuong2021 and @wangyaopw)

___
*[src/main/proto/wfa/measurement/api/v2alpha/page_token.proto, line 25 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/391#-MqMFyO28s76fbb08R0M:-MqMFyO3C76oJz9eBoLk:bz9dfr6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/382e88ca2faf824ebbec1a2e217b9dd094db4f79/src/main/proto/wfa/measurement/api/v2alpha/page_token.proto#L25)):*
> ```
> EventGroupPageToken 
> ```
ListEventGroupsPageToken
___
*[src/main/proto/wfa/measurement/api/v2alpha/page_token.proto, line 30 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/391#-MqMGCUsDV4S6wtexK79:-MqMGCUsDV4S6wtexK7A:bhdzkln) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/382e88ca2faf824ebbec1a2e217b9dd094db4f79/src/main/proto/wfa/measurement/api/v2alpha/page_token.proto#L30)):*
> ```
>     fixed64 external_event_group_id = 1;
>     fixed64 external_data_provider_id = 2;
> ```
can you switch these two? external_data_provider_id is the parent.

fixed64 external_data_provider_id = 1;
fixed64 external_event_group_id = 2;
___
*[src/main/proto/wfa/measurement/api/v2alpha/page_token.proto, line 36 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/391#-MqMG2FZ1AVEv0LNhNcB:-MqMG2FZ1AVEv0LNhNcC:b-k44080) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/382e88ca2faf824ebbec1a2e217b9dd094db4f79/src/main/proto/wfa/measurement/api/v2alpha/page_token.proto#L36)):*
> ```
> MeasurementPageToken
> ```
ListMeasurementsPageToken
___
*[src/main/proto/wfa/measurement/internal/kingdom/measurements_service.proto, line 63 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/391#-MqMGV853KLLn90IPTg_:-MqMGV853KLLn90IPTga:b7udnpa) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/382e88ca2faf824ebbec1a2e217b9dd094db4f79/src/main/proto/wfa/measurement/internal/kingdom/measurements_service.proto#L63)):*
> ```
>  // for next page token
> ```

 // For next page token. Both fields need to be set in order to work.


<!-- Sent from Reviewable.io -->

2021-12-07 23:45 UTC, wangyaopw requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/391)* status: 0 of 12 files reviewed, 9 unresolved discussions (waiting on @tristanvuong2021 and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurements.kt, line 33 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/391#-Mq6C87VE-TAhXNpQLRh:-MqMGuzP5sZqXTcmdtkS:b-mbiay) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3f753eba6526aa9934d409df050c074f35930fd4/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurements.kt#L33)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

UpdateTime changes though so it is a bit different. Guess it is fine though, if it matters, it could be changed later to only order by both if update time is specifically set in the public api filter.
</blockquote></details>

System API needs to get the latest measurement, so if a measurement is updated during the RPC, we send it back again.
Public API doesn't care I think. User would notice that the state of the measurement has changed,


<!-- Sent from Reviewable.io -->

2021-12-08 00:13 UTC, tristanvuong2021 commented
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurements.kt, line 63 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/391#-MqMD9bRCm8TGfs-ti4N:-MqMNjjU1WnSmsm8EbHf:bwmny2z) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/382e88ca2faf824ebbec1a2e217b9dd094db4f79/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurements.kt#L63)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
>  > 0L
> ```
Should be `!= 0L`
fixed64 can be negative.
</blockquote></details>

fixed64 can be negative, but external ids aren't allowed to be negative.


<!-- Sent from Reviewable.io -->

2021-12-08 00:13 UTC, tristanvuong2021 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/391)* status: 0 of 12 files reviewed, 9 unresolved discussions (waiting on @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurements.kt, line 33 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/391#-Mq6C87VE-TAhXNpQLRh:-MqMNiau6H2rpOQieOsM:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3f753eba6526aa9934d409df050c074f35930fd4/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurements.kt#L33)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

System API needs to get the latest measurement, so if a measurement is updated during the RPC, we send it back again.
Public API doesn't care I think. User would notice that the state of the measurement has changed,
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt, line 279 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/391#-MqMExdp3G73zYvaBOV6:-MqMNdgHEY_xOF6J2XWA:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/382e88ca2faf824ebbec1a2e217b9dd094db4f79/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt#L279)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
> lastMeasurement = MeasurementPageToken.PreviousPageEnd.getDefaultInstance()
> ```
delete
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt, line 295 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/391#-MqMEatDAIm_06HfFPDj:-MqMNeEp1yV2RGOBqme4:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/382e88ca2faf824ebbec1a2e217b9dd094db4f79/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt#L295)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
>  externalMeasurementIdAfter = source.lastMeasurement.externalMeasurementId
> ```
here should be something like
```
 if source.hasPreviousPageEnd() {
   updateAfter = xxx
    externalMeasurementIdAfter = xxx
}
```
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt, line 91 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/391#-MqMFFkm3uz1mL-W6Bl3:-MqMNepQ2X05NKAwaKVd:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/382e88ca2faf824ebbec1a2e217b9dd094db4f79/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt#L91)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
> fun List<State>.toInternalState(): List<InternalMeasurement.State> {
> ```

For the helper method, we only need `fun State.toInternalState(): InternalMeasurement.State`

The converting a list happens at the user of this helper method
</blockquote></details>

Done.
___
*[src/main/proto/wfa/measurement/api/v2alpha/page_token.proto, line 25 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/391#-MqMFyO28s76fbb08R0M:-MqMNfUMBzjjUyiFq8Cd:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/382e88ca2faf824ebbec1a2e217b9dd094db4f79/src/main/proto/wfa/measurement/api/v2alpha/page_token.proto#L25)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
> EventGroupPageToken 
> ```
ListEventGroupsPageToken
</blockquote></details>

Done.
___
*[src/main/proto/wfa/measurement/api/v2alpha/page_token.proto, line 30 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/391#-MqMGCUsDV4S6wtexK79:-MqMNftE7LGJ-RocevNc:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/382e88ca2faf824ebbec1a2e217b9dd094db4f79/src/main/proto/wfa/measurement/api/v2alpha/page_token.proto#L30)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
>     fixed64 external_event_group_id = 1;
>     fixed64 external_data_provider_id = 2;
> ```
can you switch these two? external_data_provider_id is the parent.

fixed64 external_data_provider_id = 1;
fixed64 external_event_group_id = 2;

</blockquote></details>

Done.
___
*[src/main/proto/wfa/measurement/api/v2alpha/page_token.proto, line 36 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/391#-MqMG2FZ1AVEv0LNhNcB:-MqMNgdA-cdjpFY8aMn8:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/382e88ca2faf824ebbec1a2e217b9dd094db4f79/src/main/proto/wfa/measurement/api/v2alpha/page_token.proto#L36)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
> MeasurementPageToken
> ```
ListMeasurementsPageToken
</blockquote></details>

Done.
___
*[src/main/proto/wfa/measurement/internal/kingdom/measurements_service.proto, line 63 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/391#-MqMGV853KLLn90IPTg_:-MqMNhBQ53UnMnb6pplL:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/382e88ca2faf824ebbec1a2e217b9dd094db4f79/src/main/proto/wfa/measurement/internal/kingdom/measurements_service.proto#L63)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
>  // for next page token
> ```

 // For next page token. Both fields need to be set in order to work.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-12-08 00:48 UTC, wangyaopw requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/391)* status: 0 of 12 files reviewed, 2 unresolved discussions (waiting on @tristanvuong2021 and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt, line 293 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/391#-MqMVPcoAcEa4ERCWGXk:-MqMVPcoAcEa4ERCWGXl:b-ch06dd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d99805b3a104513e6df586871884a7be61f46cc3/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt#L293)):*
> ```
>         for (state in source.statesList) {
>           states += state.toInternalState()
>         }
> ```
`states += source.statesList.map{it.toInternalState()}`
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt, line 91 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/391#-MqMFFkm3uz1mL-W6Bl3:-MqMV40FEhuRlCPqSVxH:be5wm3d) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/382e88ca2faf824ebbec1a2e217b9dd094db4f79/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt#L91)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

You are still returning a list.


<!-- Sent from Reviewable.io -->

2021-12-08 00:53 UTC, tristanvuong2021 commented
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt, line 91 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/391#-MqMFFkm3uz1mL-W6Bl3:-MqMWcYZ2bloGNgQB03k:b8goxxj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/382e88ca2faf824ebbec1a2e217b9dd094db4f79/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt#L91)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

You are still returning a list.
</blockquote></details>

I can make the caller not a list, but my mapping is from 1 to many in some cases so I have to return a list.


<!-- Sent from Reviewable.io -->

2021-12-08 01:35 UTC, wangyaopw approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/391)* status: 0 of 12 files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021 and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt, line 91 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/391#-MqMFFkm3uz1mL-W6Bl3:-MqMeUfxDYUtOv9g_GCx:b-67s1sy) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/382e88ca2faf824ebbec1a2e217b9dd094db4f79/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt#L91)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

I can make the caller not a list, but my mapping is from 1 to many in some cases so I have to return a list.
</blockquote></details>

oh, I see. In that case,  maybe just do
```
return when (this) {
    State.AWAITING_REQUISITION_FULFILLMENT -> 
      listOf(InternalState.PENDING_REQUISITION_PARAMS, InternalState.PENDING_REQUISITION_FULFILLMENT)
     State.xxx
      ...
}
```
return `listOf(InternalState.STATE_UNSPECIFIED)` for the last case. This is just a helper method, there is no grpc to fail.


<!-- Sent from Reviewable.io -->

2021-12-08 01:40 UTC, wangyaopw reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/391)* status: 0 of 12 files reviewed, 2 unresolved discussions (waiting on @tristanvuong2021 and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt, line 770 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/391#-MqMgcpqByDEJ2yEjX5L:-MqMgcpqByDEJ2yEjX5M:b-pcgn8u) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d99805b3a104513e6df586871884a7be61f46cc3/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt#L770)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
>     if (measurement1.externalMeasurementId < measurement2.externalMeasurementId) {
>       assertThat(measurements)
>         .comparingExpectedFieldsOnly()
>         .containsExactly(measurement1, measurement2)
>         .inOrder()
> ```
</details>

since measurement1 is created before measurement2, it should always be in the front.


<!-- Sent from Reviewable.io -->

2021-12-08 02:10 UTC, tristanvuong2021 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/391)* status: 0 of 12 files reviewed, 2 unresolved discussions (waiting on @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt, line 91 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/391#-MqMFFkm3uz1mL-W6Bl3:-MqMna4q-vXib4rsjCpQ:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/382e88ca2faf824ebbec1a2e217b9dd094db4f79/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt#L91)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

oh, I see. In that case,  maybe just do
```
return when (this) {
    State.AWAITING_REQUISITION_FULFILLMENT -> 
      listOf(InternalState.PENDING_REQUISITION_PARAMS, InternalState.PENDING_REQUISITION_FULFILLMENT)
     State.xxx
      ...
}
```
return `listOf(InternalState.STATE_UNSPECIFIED)` for the last case. This is just a helper method, there is no grpc to fail.



</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt, line 770 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/391#-MqMgcpqByDEJ2yEjX5L:-MqMnb-y02D76Toue4nv:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d99805b3a104513e6df586871884a7be61f46cc3/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt#L770)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

> ```
>     if (measurement1.externalMeasurementId < measurement2.externalMeasurementId) {
>       assertThat(measurements)
>         .comparingExpectedFieldsOnly()
>         .containsExactly(measurement1, measurement2)
>         .inOrder()
> ```
since measurement1 is created before measurement2, it should always be in the front.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-12-08 02:34 UTC, wangyaopw approved these changes
> Reviewed 2 of 12 files at r2, 2 of 7 files at r3, 5 of 7 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/391)* status: all files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt, line 770 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/391#-MqMgcpqByDEJ2yEjX5L:-MqMt-hz4WN2rpjUVoW8:b-t736wj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d99805b3a104513e6df586871884a7be61f46cc3/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt#L770)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

do you want to delete the `if` in the beginning?


<!-- Sent from Reviewable.io -->

2021-12-08 02:51 UTC, tristanvuong2021 commented
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt, line 770 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/391#-MqMgcpqByDEJ2yEjX5L:-MqMwzMG42alO2_C_1jG:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d99805b3a104513e6df586871884a7be61f46cc3/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt#L770)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

do you want to delete the `if` in the beginning?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-12-08 17:54 UTC, wangyaopw approved these changes
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/391)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @chipingyeh and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2021-12-09 22:05 UTC, stevenwarejones approved these changes
> Reviewed 2 of 12 files at r2, 2 of 7 files at r3, 5 of 7 files at r4, 2 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/391)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @chipingyeh)



<!-- Sent from Reviewable.io -->

2021-12-09 22:43 UTC, tristanvuong2021 reviewed
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/391)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @chipingyeh)



<!-- Sent from Reviewable.io -->

2021-12-09 22:44 UTC, merged