Move SelfIssuedIdToken and refactor to use Tink jwt.
world-federation-of-advertisers/cross-media-measurement pull request #403
Opened 2021-12-14 19:33 UTC by tristanvuong2021

2021-12-14 22:28 UTC, SanjayVas requested changes
> Reviewed 3 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/403)* status: 3 of 9 files reviewed, 8 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

___
*[build/repositories.bzl, line 68 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/403#-MquyaKMAl711BiqnUG2:-MquyaKMAl711BiqnUG3:b-wcbc8a) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/af37e7858d34bc00e10d0cb64ec8e411852b05da/build/repositories.bzl#L68)):*
> ```Starlark
>     wfa_repo_archive(
>         name = "wfa_consent_signaling_client",
>         commit = "e45aa52a6d1e198e8b091b72b06cf77b3a0adb4d",
> ```

Add TODO indicating which PR this is waiting for there to be a release for.
___
*[src/main/kotlin/org/wfanet/measurement/common/SelfIssuedIdToken.kt, line 19 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/403#-MquyrVd35N7FAR2v1Xf:-MquyrVd35N7FAR2v1Xg:b-tlbak5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/af37e7858d34bc00e10d0cb64ec8e411852b05da/src/main/kotlin/org/wfanet/measurement/common/SelfIssuedIdToken.kt#L19)):*
> ```
> org.wfanet.measurement.common
> ```
This should be in org.wfanet.measurement.common.crypto.tink
___
*[src/main/kotlin/org/wfanet/measurement/common/SelfIssuedIdToken.kt, line 40 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/403#-MquyxXK47vSNyuyyyH7:-MquyxXK47vSNyuyyyH8:b9ky1xz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/af37e7858d34bc00e10d0cb64ec8e411852b05da/src/main/kotlin/org/wfanet/measurement/common/SelfIssuedIdToken.kt#L40)):*
> ```
> Throws
> ```
Use `@throws`. See https://kotlinlang.org/docs/kotlin-doc.html#throws-class-exception-class
___
*[src/main/kotlin/org/wfanet/measurement/common/SelfIssuedIdToken.kt, line 47 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/403#-MquzR1r2y1Tq35tB0GT:-MquzR1r2y1Tq35tB0GU:b1slzpo) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/af37e7858d34bc00e10d0cb64ec8e411852b05da/src/main/kotlin/org/wfanet/measurement/common/SelfIssuedIdToken.kt#L47)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
>     val queryParamMap = mutableMapOf<String, String>()
> 
>     for (queryParam in uri.query.split("&")) {
>       val keyValue = queryParam.split("=")
>       queryParamMap[keyValue[0]] = keyValue[1]
>     }
> ```
</details>

This function is too long. You can e.g. extract a function to build the query map from the URI. Try to extract other parts into private functions.
___
*[src/main/kotlin/org/wfanet/measurement/common/SelfIssuedIdToken.kt, line 57 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/403#-MquziQcB26bqQSyIQA5:-MquziQd2QOXqcVfcKw4:b-yn75ri) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/af37e7858d34bc00e10d0cb64ec8e411852b05da/src/main/kotlin/org/wfanet/measurement/common/SelfIssuedIdToken.kt#L57)):*
> ```
> JwtSignatureConfig.register()
> ```
This should be called once for the application, not for each method call.
___
*[src/main/kotlin/org/wfanet/measurement/common/SelfIssuedIdToken.kt, line 61 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/403#-Mqv-l-a5L7N27dYA9Rm:-Mqv-l-bCUjSP7fYzRL3:b-ujcek7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/af37e7858d34bc00e10d0cb64ec8e411852b05da/src/main/kotlin/org/wfanet/measurement/common/SelfIssuedIdToken.kt#L61)):*
> ```Kotlin
>     var privateKeysetHandle: KeysetHandle? = null
>     try {
>       privateKeysetHandle = KeysetHandle.generateNew(KeyTemplates.get("JWT_RS256_2048_F4_RAW"))
> ```

This key should be passed in as a `TinkPrivateKeyHandle`, as someone needs to be able to generate later tokens using the same stored key. You'll likely want to modify that to class to add a `signJwt` method.
___
*[src/main/kotlin/org/wfanet/measurement/common/SelfIssuedIdToken.kt, line 62 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/403#-Mqv-La8E7sPkOPXh9EX:-Mqv-La8E7sPkOPXh9EY:bgkr20x) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/af37e7858d34bc00e10d0cb64ec8e411852b05da/src/main/kotlin/org/wfanet/measurement/common/SelfIssuedIdToken.kt#L62)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>     } catch (ex: GeneralSecurityException) {
>       val stack = ex.stackTrace
>       println(stack)
>     }
> ```
</details>

Just let these bubble up
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerAccountsService.kt, line 19 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/403#-Mqv2mQk21O-kj9IiG2s:-Mqv2mQm667kVn7c22xg:b-svnag6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/af37e7858d34bc00e10d0cb64ec8e411852b05da/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerAccountsService.kt#L19)):*
> ```
> com.google.crypto.tink.jwt.JwkSetConverter
> ```
Nothing from com.google.crypto.tink should be exposed outside of org.wfanet.measurement.common.crypto.tink.


<!-- Sent from Reviewable.io -->

2021-12-15 01:07 UTC, tristanvuong2021 commented
___
*[src/main/kotlin/org/wfanet/measurement/common/SelfIssuedIdToken.kt, line 61 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/403#-Mqv-l-a5L7N27dYA9Rm:-Mqvc8K_8rzGYJjhM-WR:b-l2yf4o) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/af37e7858d34bc00e10d0cb64ec8e411852b05da/src/main/kotlin/org/wfanet/measurement/common/SelfIssuedIdToken.kt#L61)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This key should be passed in as a `TinkPrivateKeyHandle`, as someone needs to be able to generate later tokens using the same stored key. You'll likely want to modify that to class to add a `signJwt` method.
</blockquote></details>

I created two versions of generateIdToken, one that takes in a KeysetHandle and one that generates it.


<!-- Sent from Reviewable.io -->

2021-12-15 01:07 UTC, tristanvuong2021 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/403)* status: 0 of 10 files reviewed, 8 unresolved discussions (waiting on @SanjayVas)

___
*[build/repositories.bzl, line 68 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/403#-MquyaKMAl711BiqnUG2:-MqvIM3wD99LDj205vBz:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/af37e7858d34bc00e10d0cb64ec8e411852b05da/build/repositories.bzl#L68)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Add TODO indicating which PR this is waiting for there to be a release for.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerAccountsService.kt, line 19 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/403#-Mqv2mQk21O-kj9IiG2s:-MqvcMcc7CsIO8BaVH6q:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/af37e7858d34bc00e10d0cb64ec8e411852b05da/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerAccountsService.kt#L19)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> com.google.crypto.tink.jwt.JwkSetConverter
> ```
Nothing from com.google.crypto.tink should be exposed outside of org.wfanet.measurement.common.crypto.tink.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/common/SelfIssuedIdToken.kt, line 19 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/403#-MquyrVd35N7FAR2v1Xf:-Mqvc-Cz74Eiyyr0PG_F:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/af37e7858d34bc00e10d0cb64ec8e411852b05da/src/main/kotlin/org/wfanet/measurement/common/SelfIssuedIdToken.kt#L19)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> org.wfanet.measurement.common
> ```
This should be in org.wfanet.measurement.common.crypto.tink
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/common/SelfIssuedIdToken.kt, line 40 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/403#-MquyxXK47vSNyuyyyH7:-Mqvc-dw5eZbhCd0jo6l:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/af37e7858d34bc00e10d0cb64ec8e411852b05da/src/main/kotlin/org/wfanet/measurement/common/SelfIssuedIdToken.kt#L40)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> Throws
> ```
Use `@throws`. See https://kotlinlang.org/docs/kotlin-doc.html#throws-class-exception-class
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/common/SelfIssuedIdToken.kt, line 47 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/403#-MquzR1r2y1Tq35tB0GT:-Mqvc0Bd8LLOgq6xilBj:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/af37e7858d34bc00e10d0cb64ec8e411852b05da/src/main/kotlin/org/wfanet/measurement/common/SelfIssuedIdToken.kt#L47)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
>     val queryParamMap = mutableMapOf<String, String>()
> 
>     for (queryParam in uri.query.split("&")) {
>       val keyValue = queryParam.split("=")
>       queryParamMap[keyValue[0]] = keyValue[1]
>     }
> ```
This function is too long. You can e.g. extract a function to build the query map from the URI. Try to extract other parts into private functions.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/common/SelfIssuedIdToken.kt, line 57 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/403#-MquziQcB26bqQSyIQA5:-Mqvc0m8CbXGR6228QLZ:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/af37e7858d34bc00e10d0cb64ec8e411852b05da/src/main/kotlin/org/wfanet/measurement/common/SelfIssuedIdToken.kt#L57)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> JwtSignatureConfig.register()
> ```
This should be called once for the application, not for each method call.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/common/SelfIssuedIdToken.kt, line 62 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/403#-Mqv-La8E7sPkOPXh9EX:-MqvcLcJ9Oa5w2g7SsNC:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/af37e7858d34bc00e10d0cb64ec8e411852b05da/src/main/kotlin/org/wfanet/measurement/common/SelfIssuedIdToken.kt#L62)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
>     } catch (ex: GeneralSecurityException) {
>       val stack = ex.stackTrace
>       println(stack)
>     }
> ```
Just let these bubble up
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-12-16 00:36 UTC, SanjayVas requested changes
> Reviewed 3 of 8 files at r2, 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/403)* status: 5 of 12 files reviewed, 9 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

___
*[src/main/kotlin/org/wfanet/measurement/common/crypto/tink/SelfIssuedIdToken.kt, line 42 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/403#-Mr-d3zq5ijhCgrZn0bO:-Mr-d3zq5ijhCgrZn0bP:bb6aa3z) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a8de0ab654719f4078ff17faaa956f2770dd30b1/src/main/kotlin/org/wfanet/measurement/common/crypto/tink/SelfIssuedIdToken.kt#L42)):*
> ```
> class SelfIssuedIdToken private constructor() {
>   companion object {
> ```
Rather than an uninstantiable class with everything in the companion object, you can just use an [object declaration](https://kotlinlang.org/docs/object-declarations.html#object-declarations-overview). e.g.

```
object SelfIssuedIdTokens {
  private const val STATE = "state"
  private const val NONCE = "nonce"
  private const val SELF_ISSUED_ISSUER = "https://self-issued.me"
  private val HEADER: String = JsonObject().apply {
      addProperty("typ", "JWT")
      addProperty("alg", "RS256")
    }.toString()

  init {
    JwtSignatureConfig.register()
  }

  // ...
}
```

Also this should be `SelfIssuedIdTokens`, as it's not a class that represents a single token.
___
*[src/main/kotlin/org/wfanet/measurement/common/crypto/tink/SelfIssuedIdToken.kt, line 76 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/403#-Mr-eGWj4-W6O8HwjAvc:-Mr-eGWj4-W6O8HwjAvd:b-euyz6w) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a8de0ab654719f4078ff17faaa956f2770dd30b1/src/main/kotlin/org/wfanet/measurement/common/crypto/tink/SelfIssuedIdToken.kt#L76)):*
> ```Kotlin
>      */
>     fun generateIdToken(
>       privateKeysetHandle: KeysetHandle,
> ```

This is still exposing Tink objects. We should use our own key handle wrapper type.
___
*[src/main/kotlin/org/wfanet/measurement/common/crypto/tink/SelfIssuedIdToken.kt, line 161 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/403#-Mr-eWdj5btbefjYGFtj:-Mr-eWdj5btbefjYGFtk:b-gd2l53) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a8de0ab654719f4078ff17faaa956f2770dd30b1/src/main/kotlin/org/wfanet/measurement/common/crypto/tink/SelfIssuedIdToken.kt#L161)):*
> ```Kotlin
>     }
> 
>     /** Validates the signature, the header, and the following claims: issuer and audience. */
> ```

What happens when it's not valid?


<!-- Sent from Reviewable.io -->

2021-12-16 17:02 UTC, tristanvuong2021 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/403)* status: 1 of 13 files reviewed, 9 unresolved discussions (waiting on @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/common/crypto/tink/SelfIssuedIdToken.kt, line 42 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/403#-Mr-d3zq5ijhCgrZn0bO:-Mr3BRjnE1E_0vO4cREV:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a8de0ab654719f4078ff17faaa956f2770dd30b1/src/main/kotlin/org/wfanet/measurement/common/crypto/tink/SelfIssuedIdToken.kt#L42)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
> class SelfIssuedIdToken private constructor() {
>   companion object {
> ```
Rather than an uninstantiable class with everything in the companion object, you can just use an [object declaration](https://kotlinlang.org/docs/object-declarations.html#object-declarations-overview). e.g.

```
object SelfIssuedIdTokens {
  private const val STATE = "state"
  private const val NONCE = "nonce"
  private const val SELF_ISSUED_ISSUER = "https://self-issued.me"
  private val HEADER: String = JsonObject().apply {
      addProperty("typ", "JWT")
      addProperty("alg", "RS256")
    }.toString()

  init {
    JwtSignatureConfig.register()
  }

  // ...
}
```

Also this should be `SelfIssuedIdTokens`, as it's not a class that represents a single token.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/common/crypto/tink/SelfIssuedIdToken.kt, line 76 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/403#-Mr-eGWj4-W6O8HwjAvc:-Mr3BPv4DX9BXyMvfcWo:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a8de0ab654719f4078ff17faaa956f2770dd30b1/src/main/kotlin/org/wfanet/measurement/common/crypto/tink/SelfIssuedIdToken.kt#L76)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This is still exposing Tink objects. We should use our own key handle wrapper type.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/common/crypto/tink/SelfIssuedIdToken.kt, line 161 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/403#-Mr-eWdj5btbefjYGFtj:-Mr3BQuYBomLVQj1e-dZ:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a8de0ab654719f4078ff17faaa956f2770dd30b1/src/main/kotlin/org/wfanet/measurement/common/crypto/tink/SelfIssuedIdToken.kt#L161)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

What happens when it's not valid?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-12-16 19:31 UTC, SanjayVas requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/403)* status: 1 of 13 files reviewed, 10 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

___
*[src/main/kotlin/org/wfanet/measurement/common/crypto/tink/BUILD.bazel, line 9 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/403#-Mr3iWrT8SAsL4orbgMO:-Mr3iWrT8SAsL4orbgMP:b-whkcwj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/177a6ab68e85256b167d094304ebefe585e94ed7/src/main/kotlin/org/wfanet/measurement/common/crypto/tink/BUILD.bazel#L9)):*
> ```Starlark
> 
> kt_jvm_library(
>     name = "self_issued_id_tokens",
> ```

Sorry, I just realized this is a new file. This should be in common-jvm rather than cross-media-measurement.


<!-- Sent from Reviewable.io -->

2021-12-23 16:57 UTC, tristanvuong2021 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/403)* status: 0 of 13 files reviewed, 10 unresolved discussions (waiting on @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/common/crypto/tink/BUILD.bazel, line 9 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/403#-Mr3iWrT8SAsL4orbgMO:-MrcDMuKCwfbcJaiOBbv:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e33a5eaaf4dff1e6624825362de7af748333e34f/src/main/kotlin/org/wfanet/measurement/common/crypto/tink/BUILD.bazel#L9)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Sorry, I just realized this is a new file. This should be in common-jvm rather than cross-media-measurement.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-12-23 23:55 UTC, SanjayVas requested changes
> Reviewed 1 of 7 files at r7, 1 of 2 files at r9, 1 of 4 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/403)* status: 3 of 16 files reviewed, 16 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/BUILD.bazel, line 13 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/403#-Mrdd-iY0Mlg2cbOsWnv:-Mrdd-iY0Mlg2cbOsWnw:b42l7hh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/27f17cf987a08e84c74823d89ff2c73ef0820403/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/BUILD.bazel#L13)):*
> ```Starlark
>     ],
>     deps = KINGDOM_INTERNAL_PROTOS + [
>         "@wfa_common_jvm//src/main/kotlin/org/wfanet/measurement/common/crypto/tink:tink",
> ```

nit: the `:tink` is unnecessary as it's the default target for the package



_Code quote:_
```Starlark
:tink
```
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerAccountsService.kt, line 190 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/403#-MrdgucRAXSev_gZBkC9:-MrdgucRAXSev_gZBkCA:b-2suc8w) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/27f17cf987a08e84c74823d89ff2c73ef0820403/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerAccountsService.kt#L190)):*
> ```Kotlin
>     val parsedValidatedIdToken =
>       try {
>         validateIdToken(idToken) ?: failGrpc(Status.PERMISSION_DENIED) { "Id token is invalid" }
> ```

It's weird that validateIdToken throws in some cases and returns null in others, but we don't treat them differently.

Maybe validateIdToken should just always throw GeneralSecurityException on validation errors?



_Code quote:_
```Kotlin
?: failGrpc(Status.PERMISSION_DENIED) { "Id token is invalid" }
```
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerAccountsService.kt, line 191 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/403#-MrdgIaQ7re34Vrmos_y:-MrdgIaQ7re34Vrmos_z:bisv776) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/27f17cf987a08e84c74823d89ff2c73ef0820403/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerAccountsService.kt#L191)):*
> ```Kotlin
>       try {
>         validateIdToken(idToken) ?: failGrpc(Status.PERMISSION_DENIED) { "Id token is invalid" }
>       } catch (ex: Exception) {
> ```

Use specific exception types that we know of, and let unknown ones result in the automatic gRPC UNKNOWN. In this case, I believe it's GeneralSecurityException.



_Code quote:_
```Kotlin
Exception
```
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerAccountsService.kt, line 192 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/403#-MrdhKgB56YzvOCqh5ES:-MrdhKgB56YzvOCqh5ET:b6865eh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/27f17cf987a08e84c74823d89ff2c73ef0820403/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerAccountsService.kt#L192)):*
> ```Kotlin
>         validateIdToken(idToken) ?: failGrpc(Status.PERMISSION_DENIED) { "Id token is invalid" }
>       } catch (ex: Exception) {
>         failGrpc(Status.PERMISSION_DENIED) { "Id token is invalid" }
> ```

Since we have an exception, prefer preserving the information so we can see it if/when we add a logging interceptor.

```
throw Status.PERMISSION_DENIED.withCause(ex).withDescription("ID token is invalid").asRuntimeException()
```
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerAccountsService.kt, line 216 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/403#-MrdgUt983032eIABbmN:-MrdgUt983032eIABbmO:bc7lh11) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/27f17cf987a08e84c74823d89ff2c73ef0820403/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerAccountsService.kt#L216)):*
> ```Kotlin
>   }
> 
>   /** Returns the issuer and subject if the idToken is valid and null otherwise. */
> ```

Document that this throws GeneralSecurityException if the ID Token can't be verified.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerAccountsService.kt, line 239 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/403#-MrddkRs-MMEWbkExVF9:-MrddkRs-MMEWbkExVFA:b-799x7k) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/27f17cf987a08e84c74823d89ff2c73ef0820403/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerAccountsService.kt#L239)):*
> ```Kotlin
>         redirectUri = REDIRECT_URI,
>         idToken = idToken,
>         verifier = publicJwkHandle.verifier
> ```

Sorry, should have caught this in the common-jvm PR. `JwtPublicKeyVerify` is another real Tink type that need not be exposed outside of our common.crypto.tink package. `validateJwt` should take in the `PublicJwkHandle`, which should expose a `verifyAndDecode` method.


<!-- Sent from Reviewable.io -->

2022-01-07 17:32 UTC, tristanvuong2021 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/403)* status: 1 of 16 files reviewed, 14 unresolved discussions (waiting on @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerAccountsService.kt, line 191 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/403#-MrdgIaQ7re34Vrmos_y:-MspaE2O3t8Dj81xzc_2:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/27f17cf987a08e84c74823d89ff2c73ef0820403/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerAccountsService.kt#L191)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Use specific exception types that we know of, and let unknown ones result in the automatic gRPC UNKNOWN. In this case, I believe it's GeneralSecurityException.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerAccountsService.kt, line 192 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/403#-MrdhKgB56YzvOCqh5ES:-MspaD8SDcMlClqresz7:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/27f17cf987a08e84c74823d89ff2c73ef0820403/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerAccountsService.kt#L192)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Since we have an exception, prefer preserving the information so we can see it if/when we add a logging interceptor.

```
throw Status.PERMISSION_DENIED.withCause(ex).withDescription("ID token is invalid").asRuntimeException()
```
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerAccountsService.kt, line 216 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/403#-MrdgUt983032eIABbmN:-MspaC1rBSp-5_HvmFqx:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/27f17cf987a08e84c74823d89ff2c73ef0820403/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerAccountsService.kt#L216)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Document that this throws GeneralSecurityException if the ID Token can't be verified.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerAccountsService.kt, line 239 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/403#-MrddkRs-MMEWbkExVF9:-MspaCQf4wGo_zFPR0Y2:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/27f17cf987a08e84c74823d89ff2c73ef0820403/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerAccountsService.kt#L239)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Sorry, should have caught this in the common-jvm PR. `JwtPublicKeyVerify` is another real Tink type that need not be exposed outside of our common.crypto.tink package. `validateJwt` should take in the `PublicJwkHandle`, which should expose a `verifyAndDecode` method.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-10 22:46 UTC, SanjayVas requested changes
> Reviewed 1 of 9 files at r1, 1 of 8 files at r2, 3 of 7 files at r7, 2 of 3 files at r10, 2 of 4 files at r11, 3 of 6 files at r13, 4 of 4 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/403)* status: all files reviewed, 2 unresolved discussions (waiting on @tristanvuong2021)

___
*[build/repositories.bzl, line 28 at r14](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/403#-Mt58s7z5TvEc2kw8M8x:-Mt58s7z5TvEc2kw8M8y:b-ye3e7i) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/67f9899bdd7865497dfa557f1020c3ca7a36ae09/build/repositories.bzl#L28)):*
> ```Starlark
>         repo = "common-jvm",
>         sha256 = "b72ef7919abde6f10766b8c9eb7f29c470b090fd62cce82272b60dbdc4981fe4",
>         #version = "0.25.1",
> ```

Add TODO referencing PR that needs to be merged/released.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerAccountsService.kt, line 275 at r14](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/403#-Mt59V6OC4coVYUs58ra:-Mt59V6OC4coVYUs58rb:b6g3caw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/67f9899bdd7865497dfa557f1020c3ca7a36ae09/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerAccountsService.kt#L275)):*
> ```Kotlin
> 
>     if (tokenParts.size != 3) {
>       throw GeneralSecurityException()
> ```

nit: since we have relevant information, might as well include it in exception message


<!-- Sent from Reviewable.io -->

2022-01-11 19:23 UTC, tristanvuong2021 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/403)* status: 14 of 16 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[build/repositories.bzl, line 28 at r14](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/403#-Mt58s7z5TvEc2kw8M8x:-Mt9a16yB9-7zz_ANcMT:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8a3b445148d9f48866c6de822fd31649a49f38d6/build/repositories.bzl#L28)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Add TODO referencing PR that needs to be merged/released.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-11 22:10 UTC, SanjayVas approved these changes
> Reviewed 2 of 2 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/403)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)



<!-- Sent from Reviewable.io -->

2022-01-12 14:21 UTC, stevenwarejones reviewed
> Reviewed 1 of 9 files at r1, 1 of 3 files at r10, 1 of 4 files at r11, 3 of 6 files at r13, 2 of 4 files at r14, 2 of 2 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/403)* status: all files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerAccountsService.kt, line 295 at r15](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/403#-MtDbwDPDjYKPjEvd80_:-MtDbwDPDjYKPjEvd80a:bj7xmre) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ecb8c140968870b042d30e779cd090df7255747a/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerAccountsService.kt#L295)):*
> ```Kotlin
> 
>     val verifiedJwt =
>       validateJwt(redirectUri = REDIRECT_URI, idToken = idToken, publicJwkHandle = publicJwkHandle)
> ```

how are we using the REDIRECT_URI?


<!-- Sent from Reviewable.io -->

2022-01-12 17:17 UTC, tristanvuong2021 commented
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerAccountsService.kt, line 295 at r15](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/403#-MtDbwDPDjYKPjEvd80_:-MtEHIlU8Hd7NpWU25R-:b-88ogcv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ecb8c140968870b042d30e779cd090df7255747a/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerAccountsService.kt#L295)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

how are we using the REDIRECT_URI?
</blockquote></details>

Using REDIRECT_URI like this is actually wrong. To fix this, I will be moving this validation over to the public service. However, it is enough work that I will do it in a separate PR.


<!-- Sent from Reviewable.io -->

2022-01-12 17:56 UTC, stevenwarejones approved these changes
> Reviewed 1 of 1 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/403)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)



<!-- Sent from Reviewable.io -->

2022-01-12 17:59 UTC, merged