Chipingyeh update spanner eventgroups
world-federation-of-advertisers/cross-media-measurement pull request #406
Opened 2021-12-16 15:53 UTC by chipingyeh

2021-12-16 17:35 UTC, robinsons requested changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/406)* status: all files reviewed, 6 unresolved discussions (waiting on @chipingyeh and @stevenwarejones)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/406#-Mr3Ir5H1cYxFuT877nw:-Mr3Ir5H1cYxFuT877nx:b-r0d251) (no related file):*
There should be some tests to update, right?

---
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/EventGroupReader.kt, line 36 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/406#-Mr3DNblEBOL_dNkJpgP:-Mr3DNblEBOL_dNkJpgQ:b9jy6uw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/57002992af5b7df522c493d49f8ee5e4d6a5859e/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/EventGroupReader.kt#L36)):*
> ```Kotlin
>       EventGroups.CreateTime,
>       EventGroups.EventGroupDetails,
>       EventGroups.EventGroupDetailsJson,
> ```

nit: I don't believe we need to select the JSON representation, since all of that info is already in the `EventGroupDetails` column.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/EventGroupReader.kt, line 89 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/406#-Mr3Dpbt9RM9CcBo2o5D:-Mr3Dpbt9RM9CcBo2o5E:b-yzs5am) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/57002992af5b7df522c493d49f8ee5e4d6a5859e/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/EventGroupReader.kt#L89)):*
> ```Kotlin
> 
>   private fun buildEventGroup(struct: Struct): EventGroup =
>     EventGroup.newBuilder()
> ```

Also need to populate `externalMeasurementConsumerCertificateId` (if it exists) and `updateTime`.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateEventGroup.kt, line 67 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/406#-Mr3F1V1EF4q_8hPb8EV:-Mr3F1V1EF4q_8hPb8EW:b-2y7mun) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/57002992af5b7df522c493d49f8ee5e4d6a5859e/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateEventGroup.kt#L67)):*
> ```Kotlin
>     dataProviderId: Long,
>     measurementConsumerId: Long,
>     eventGroup: EventGroup
> ```

Note that `eventGroup` is already available as an instance variable of the `CreateEventGroup` class, so there's no need to pass it as an argument here.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateEventGroup.kt, line 76 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/406#-Mr3GzwuENpE1G3WIy_x:-Mr3GzwuENpE1G3WIy_y:b-dfoumv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/57002992af5b7df522c493d49f8ee5e4d6a5859e/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateEventGroup.kt#L76)):*
> ```Kotlin
>       set("ExternalEventGroupId" to externalEventGroupId)
>       set("MeasurementConsumerId" to measurementConsumerId)
>       set("MeasurementConsumerCertificateId" to eventGroup.externalMeasurementConsumerCertificateId)
> ```

Could you do something [like this](https://sourcegraph.com/github.com/world-federation-of-advertisers/cross-media-measurement@e4d6a586ea1a53c1a3f71eb6ee9f676dc1c1239b/-/blob/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurement.kt?L150-159) to validate that the certificate exists? Since there is a foreign key to the certificate, we'll get a Spanner exception if it doesn't exist. We try to avoid that by throwing a `KingdomInternalException` with an appropriate error code, instead.

It'd also be good to update the comment on this class, once we've added this new error.

(Note that the linked example is reading data provider certificates, but we'll want to read MC instead.)
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateEventGroup.kt, line 81 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/406#-Mr3IXWL9ZDWZUuMuzDV:-Mr3IXWL9ZDWZUuMuzDW:b9k5otz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/57002992af5b7df522c493d49f8ee5e4d6a5859e/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateEventGroup.kt#L81)):*
> ```Kotlin
>         set("ProvidedEventGroupId" to eventGroup.providedEventGroupId)
>       }
>       set("CreateTime" to Value.COMMIT_TIMESTAMP)
> ```

Also need to set `UpdateTime`.


<!-- Sent from Reviewable.io -->

2021-12-16 19:17 UTC, stevenwarejones reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/406)* status: all files reviewed, 6 unresolved discussions (waiting on @chipingyeh and @robinsons)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/EventGroupReader.kt, line 36 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/406#-Mr3DNblEBOL_dNkJpgP:-Mr3fJFVEo1g5K2c-bND:b-v3w7af) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/57002992af5b7df522c493d49f8ee5e4d6a5859e/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/EventGroupReader.kt#L36)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

nit: I don't believe we need to select the JSON representation, since all of that info is already in the `EventGroupDetails` column.
</blockquote></details>

+1 unless we want it for debugging


<!-- Sent from Reviewable.io -->

2021-12-16 19:18 UTC, stevenwarejones reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/406)* status: all files reviewed, 6 unresolved discussions (waiting on @chipingyeh and @robinsons)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/406#-Mr3Ir5H1cYxFuT877nw:-Mr3fb4ABj8GkseQ3s2l:bosj4hk) (no related file):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

There should be some tests to update, right?
</blockquote></details>

Yeah - there are failing tests too.

---


<!-- Sent from Reviewable.io -->

2021-12-17 20:04 UTC, chipingyeh reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/406)* status: 0 of 3 files reviewed, 5 unresolved discussions (waiting on @robinsons and @stevenwarejones)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/406#-Mr3Ir5H1cYxFuT877nw:-Mr8slhn8QpWWu2hAS6M:b-9uy30o) (no related file):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

Yeah - there are failing tests too.
</blockquote></details>

Updated existing tests.

---
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/EventGroupReader.kt, line 36 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/406#-Mr3DNblEBOL_dNkJpgP:-Mr42_sg9xQ14Fr5G6jS:bvjoea9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/57002992af5b7df522c493d49f8ee5e4d6a5859e/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/EventGroupReader.kt#L36)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

+1 unless we want it for debugging
</blockquote></details>

Removed - had been referencing DataProviderReader.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/EventGroupReader.kt, line 89 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/406#-Mr3Dpbt9RM9CcBo2o5D:-Mr43SXF1IPObqXL_B8H:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/57002992af5b7df522c493d49f8ee5e4d6a5859e/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/EventGroupReader.kt#L89)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

Also need to populate `externalMeasurementConsumerCertificateId` (if it exists) and `updateTime`.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateEventGroup.kt, line 67 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/406#-Mr3F1V1EF4q_8hPb8EV:-Mr44xXk4xHvzJF6hWg0:b-clh693) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/57002992af5b7df522c493d49f8ee5e4d6a5859e/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateEventGroup.kt#L67)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

Note that `eventGroup` is already available as an instance variable of the `CreateEventGroup` class, so there's no need to pass it as an argument here.
</blockquote></details>

Good point, updated.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateEventGroup.kt, line 76 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/406#-Mr3GzwuENpE1G3WIy_x:-Mr47ghx8XOY1aPNoBrX:btdpv6i) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/57002992af5b7df522c493d49f8ee5e4d6a5859e/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateEventGroup.kt#L76)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

Could you do something [like this](https://sourcegraph.com/github.com/world-federation-of-advertisers/cross-media-measurement@e4d6a586ea1a53c1a3f71eb6ee9f676dc1c1239b/-/blob/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurement.kt?L150-159) to validate that the certificate exists? Since there is a foreign key to the certificate, we'll get a Spanner exception if it doesn't exist. We try to avoid that by throwing a `KingdomInternalException` with an appropriate error code, instead.

It'd also be good to update the comment on this class, once we've added this new error.

(Note that the linked example is reading data provider certificates, but we'll want to read MC instead.)
</blockquote></details>

Thanks for the reference -- done. I realize null-checking isn't great, lmk if an alternate method is preferred.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateEventGroup.kt, line 81 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/406#-Mr3IXWL9ZDWZUuMuzDV:-Mr45SuU1TCAS-j3IcMi:b-b6o9wa) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/57002992af5b7df522c493d49f8ee5e4d6a5859e/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateEventGroup.kt#L81)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

Also need to set `UpdateTime`.
</blockquote></details>

Hadn't been sure on that -- done.


<!-- Sent from Reviewable.io -->

2021-12-20 17:56 UTC, robinsons requested changes
> Reviewed 2 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/406)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @chipingyeh and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateEventGroup.kt, line 76 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/406#-Mr3GzwuENpE1G3WIy_x:-MrNwucA48A0ZUlPa2uG:b-p5ieeg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/57002992af5b7df522c493d49f8ee5e4d6a5859e/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateEventGroup.kt#L76)):*
<details><summary><i>Previously, chipingyeh wrote…</i></summary><blockquote>

Thanks for the reference -- done. I realize null-checking isn't great, lmk if an alternate method is preferred.
</blockquote></details>

I think it's probably OK here.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateEventGroup.kt, line 76 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/406#-MrNtqSd5rdZKIxhpYfi:-MrNtqSe-qUyV-R-ZlU-:b6vjo8w) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/26c0acd7ee04695a2dda67c3c9c88f5072d9f4db/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateEventGroup.kt#L76)):*
> ```Kotlin
>           CertificateReader(CertificateReader.ParentType.MEASUREMENT_CONSUMER)
>             .bindWhereClause(
>               ExternalId(measurementConsumerId),
> ```

I believe that `measurementConsumerId` is an internal identifier (though I'm not 100% positive).
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt, line 54 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/406#-MrNyoUA1yYiGLKupuGz:-MrNyoUA1yYiGLKupuH-:b-rdpvg6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/26c0acd7ee04695a2dda67c3c9c88f5072d9f4db/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt#L54)):*
> ```Kotlin
> 
> @RunWith(JUnit4::class)
> abstract class EventGroupsServiceTest<T : EventGroupsCoroutineImplBase> {
> ```

Can you also add tests for the MC certificate? We probably want three: a success case; a case where the certificate is invalid; and a case where the certificat is not found.


<!-- Sent from Reviewable.io -->

2021-12-21 21:43 UTC, chipingyeh reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/406)* status: 1 of 6 files reviewed, 2 unresolved discussions (waiting on @robinsons and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateEventGroup.kt, line 76 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/406#-MrNtqSd5rdZKIxhpYfi:-MrOMAwQ2l6D8dJil8fF:b-e5g6fr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/26c0acd7ee04695a2dda67c3c9c88f5072d9f4db/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateEventGroup.kt#L76)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

I believe that `measurementConsumerId` is an internal identifier (though I'm not 100% positive).
</blockquote></details>

I think you're right, and Certificate only seems to take in external ids -- updated.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt, line 54 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/406#-MrNyoUA1yYiGLKupuGz:-MrThmS94XRxrjZgqpVb:b-tk69z2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/26c0acd7ee04695a2dda67c3c9c88f5072d9f4db/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt#L54)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

Can you also add tests for the MC certificate? We probably want three: a success case; a case where the certificate is invalid; and a case where the certificat is not found.
</blockquote></details>

Sorry for the delay, used an incorrect approach to test for the correct certificate for a while. I'm having trouble figuring out how to create an invalid certificate - it doesn't seem like setting the `notValidAfter` field to 0 does anything. Would you have any tips here?
Additionally, adding the certificatesService seemed to cause some other tests to fail somewhat flakily. Would appreciate a 2nd thought on if there's any teardown or such I should be doing.


<!-- Sent from Reviewable.io -->

2021-12-21 21:52 UTC, chipingyeh reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/406)* status: 1 of 6 files reviewed, 2 unresolved discussions (waiting on @robinsons, @SanjayVas, and @stevenwarejones)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/406#-MrTyg9Y0-n8XcrkYdjc:-MrTyg9Y0-n8XcrkYdjd:bpin5n0) (no related file):*
Adding Sanjay since I think Stephen is out.

---


<!-- Sent from Reviewable.io -->

2021-12-21 23:48 UTC, robinsons requested changes
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/406)* status: all files reviewed, 2 unresolved discussions (waiting on @chipingyeh, @SanjayVas, and @stevenwarejones)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/406#-MrUId413WuiW7J3n8dA:-MrUId413WuiW7J3n8dB:be8kzbi) (no related file):*
I know you're still taking care of some test oddities, but could you take a look at the linter findings before merging? Thanks!

---
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt, line 54 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/406#-MrNyoUA1yYiGLKupuGz:-MrUMAdj7oX399nG5KQg:bnqhohz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/26c0acd7ee04695a2dda67c3c9c88f5072d9f4db/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt#L54)):*
<details><summary><i>Previously, chipingyeh wrote…</i></summary><blockquote>

Sorry for the delay, used an incorrect approach to test for the correct certificate for a while. I'm having trouble figuring out how to create an invalid certificate - it doesn't seem like setting the `notValidAfter` field to 0 does anything. Would you have any tips here?
Additionally, adding the certificatesService seemed to cause some other tests to fail somewhat flakily. Would appreciate a 2nd thought on if there's any teardown or such I should be doing.
</blockquote></details>

For the invalid certificate, maybe there's something weird about creating a copy. Instead, can you try specifying `notValidBefore` and `notValidAfter` at the time you call [`createMeasurementConsumer()`](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/Population.kt#L74-L96)? I got this idea from this test [here](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt#L209-L214).

Which other tests are being flaky? I don't mind taking a look. I would expect the only impact to be on the SpannerEventGroupsServiceTest, which you've already updated and *should* work once we can get the right setup for the invalid certificate test. 


<!-- Sent from Reviewable.io -->

2021-12-22 00:06 UTC, SanjayVas requested changes
> Chipingyeh update spanner eventgroups

I assume you're aware now that the username prefix is for the branch name, not the PR title. You'll want to update this, as it becomes the default title for the final merge message.

> Reviewed 1 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/406#-:-MrU0OoR3jNfYeb3Bc4h:b3du9zm)* status: all files reviewed, 4 unresolved discussions (waiting on @chipingyeh, @robinsons, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/common/BUILD.bazel, line 6 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/406#-MrU1dmqC7nCJ6BaDiz2:-MrU1dmqC7nCJ6BaDiz3:bgwnydn) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3c4f94a1adc48edcd3f0be604b4ea96c57cffa83/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/common/BUILD.bazel#L6)):*
> ```Starlark
>     "//src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner:__subpackages__",
>     "//src/test/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner:__subpackages__",
>     "//src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing:__subpackages__",
> ```

This is incorrect. Nothing from a `gcloud` deploy package tree should be exposed outside of `gcloud`-specific package trees.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt, line 54 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/406#-MrNyoUA1yYiGLKupuGz:-MrU4Bbx2X_r8f-pclfz:bflnocb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/26c0acd7ee04695a2dda67c3c9c88f5072d9f4db/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt#L54)):*
I assume by invalid certificate, Stephen meant one where the current time is outside of the validity period. The certificates service probably shouldn't let you create a certificate that's already invalid, and if it does you shouldn't rely on that behavior for this test.

The current Spanner implementation uses the `CURRENT_TIMESTAMP` DB function to determine whether a certificate is outside of its validity period. I'm actually not certain of the benefit of this. I think we assumed that `CURRENT_TIMESTAMP` had some guarantees w.r.t. transaction commit timestamps, but I'm not sure that's actually true. Therefore, it may be better to use a Clock instance for cases when we're not comparing to commit timestamps. This way, we can pass in some non-system Clock implementation so we can control whether a certificate is considered expired.

> Additionally, adding the certificatesService seemed to cause some other tests to fail somewhat flakily. Would appreciate a 2nd thought on if there's any teardown or such I should be doing.

This shouldn't be happening. Each test method run is using a fresh DB instance.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt, line 47 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/406#-MrU1uub2TgdOzfp106Q:-MrU1uub2TgdOzfp106R:b-90rys1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3c4f94a1adc48edcd3f0be604b4ea96c57cffa83/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt#L47)):*
> ```Kotlin
> import org.wfanet.measurement.internal.kingdom.eventGroup
> import org.wfanet.measurement.internal.kingdom.streamEventGroupsRequest
> import org.wfanet.measurement.kingdom.deploy.gcloud.spanner.common.KingdomInternalException
> ```

This is in a `gcloud`/`spanner` package. This means it shouldn't be referenced from the test base.

That said, I don't think that this exception needs to be specific to the Spanner implementation. You can move it over to the `kingdom.service.internal` package.


<!-- Sent from Reviewable.io -->

2021-12-22 00:07 UTC, SanjayVas reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/406)* status: all files reviewed, 4 unresolved discussions (waiting on @chipingyeh, @robinsons, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt, line 54 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/406#-MrNyoUA1yYiGLKupuGz:-MrUSagn4dc462bFmR3E:b-9uu82i) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/26c0acd7ee04695a2dda67c3c9c88f5072d9f4db/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt#L54)):*
> The certificates service probably shouldn't let you create a certificate that's already invalid, and if it does you shouldn't rely on that behavior for this test.

Sorry, this is incorrect. It should always allow you to add certificates that are e.g. not yet valid for future use.


<!-- Sent from Reviewable.io -->

2021-12-22 17:02 UTC, chipingyeh reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/406)* status: 5 of 6 files reviewed, 4 unresolved discussions (waiting on @chipingyeh, @robinsons, @SanjayVas, and @stevenwarejones)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/406#-MrUId413WuiW7J3n8dA:-MrY1ZYzBO62IVBIl58w:b-gebr7x) (no related file):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

I know you're still taking care of some test oddities, but could you take a look at the linter findings before merging? Thanks!
</blockquote></details>

Will do -- I hadn't addressed it yet since the code will likely still change from open comments.

---
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt, line 54 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/406#-MrNyoUA1yYiGLKupuGz:-MrXtuQ7Al3XxaEyw46O:b2o9swn) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/26c0acd7ee04695a2dda67c3c9c88f5072d9f4db/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt#L54)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> The certificates service probably shouldn't let you create a certificate that's already invalid, and if it does you shouldn't rely on that behavior for this test.

Sorry, this is incorrect. It should always allow you to add certificates that are e.g. not yet valid for future use.
</blockquote></details>

That was it, thank you! I had been manually setting the test certificate field without realizing those fields were tied to the test MC. Did some more testing locally and there don't seem to be flaky failures if I clear the cache each time, so it might be a quirk with my setup.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt, line 47 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/406#-MrU1uub2TgdOzfp106Q:-MrXzgQ53008-4XJOZgW:bljbjr2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3c4f94a1adc48edcd3f0be604b4ea96c57cffa83/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt#L47)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This is in a `gcloud`/`spanner` package. This means it shouldn't be referenced from the test base.

That said, I don't think that this exception needs to be specific to the Spanner implementation. You can move it over to the `kingdom.service.internal` package.
</blockquote></details>

The default visibility of [that package](https://sourcegraph.com/github.com/world-federation-of-advertisers/cross-media-measurement/-/blob/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/BUILD.bazel) still seems to be currently limited to `..deploy/gcloud/spanner` packages -- would you recommend expanding that visibility? If so I can create another PR for it and update all the affected files.


<!-- Sent from Reviewable.io -->

2021-12-22 18:51 UTC, SanjayVas requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/406)* status: 5 of 6 files reviewed, 4 unresolved discussions (waiting on @chipingyeh, @robinsons, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt, line 47 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/406#-MrU1uub2TgdOzfp106Q:-MrYTnyi6o20-9iJqR6K:ba3cc09) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3c4f94a1adc48edcd3f0be604b4ea96c57cffa83/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt#L47)):*
<details><summary><i>Previously, chipingyeh wrote…</i></summary><blockquote>

The default visibility of [that package](https://sourcegraph.com/github.com/world-federation-of-advertisers/cross-media-measurement/-/blob/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/BUILD.bazel) still seems to be currently limited to `..deploy/gcloud/spanner` packages -- would you recommend expanding that visibility? If so I can create another PR for it and update all the affected files.
</blockquote></details>

Yes, it's fine to expand that package's visibility.


<!-- Sent from Reviewable.io -->

2021-12-22 19:11 UTC, SanjayVas requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/406)* status: 5 of 6 files reviewed, 5 unresolved discussions (waiting on @chipingyeh, @robinsons, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt, line 47 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/406#-MrU1uub2TgdOzfp106Q:-MrYXpnP1Ei4guwh8kz0:b-k88zca) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3c4f94a1adc48edcd3f0be604b4ea96c57cffa83/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt#L47)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Yes, it's fine to expand that package's visibility.
</blockquote></details>

Actually wait, it doesn't make sense to use this exception in one of these tests at all. `KingdomInternalException` is never thrown by the service implementation, and is instead only thrown by the layer below. Therefore, it is indeed specific to the Spanner implementation and shouldn't be moved.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt, line 161 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/406#-MrYYPZ9ASb5yzNMHhU7:-MrYYPZ9ASb5yzNMHhU8:b87wtv6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/12a2417e9d1c7eed8e892a8fe5b489cd50070cbc/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt#L161)):*
> ```Kotlin
> 
>     val exception =
>       assertFailsWith<KingdomInternalException> { eventGroupsService.createEventGroup(eventGroup) }
> ```

createEventGroup (or any gRPC service method) should never throw a KingdomInternalException. It should only throw `StatusRuntimeException`.


<!-- Sent from Reviewable.io -->

2021-12-22 21:50 UTC, chipingyeh reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/406)* status: 2 of 7 files reviewed, 4 unresolved discussions (waiting on @robinsons, @SanjayVas, and @stevenwarejones)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/406#-MrUId413WuiW7J3n8dA:-MrZ-RSQ6QM3jvDn_9cg:bb6un1j) (no related file):*
<details><summary><i>Previously, chipingyeh wrote…</i></summary><blockquote>

Will do -- I hadn't addressed it yet since the code will likely still change from open comments.
</blockquote></details>

Done

---
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt, line 47 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/406#-MrU1uub2TgdOzfp106Q:-MrZ6KQe91ZbwWV7i8ue:b-h0g7sy) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3c4f94a1adc48edcd3f0be604b4ea96c57cffa83/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt#L47)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Actually wait, it doesn't make sense to use this exception in one of these tests at all. `KingdomInternalException` is never thrown by the service implementation, and is instead only thrown by the layer below. Therefore, it is indeed specific to the Spanner implementation and shouldn't be moved.
</blockquote></details>

I see this now, thanks -- updated. Let me know if the status codes align as expected.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt, line 161 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/406#-MrYYPZ9ASb5yzNMHhU7:-MrZ6UW84LOXywEpjxt0:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/12a2417e9d1c7eed8e892a8fe5b489cd50070cbc/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt#L161)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

createEventGroup (or any gRPC service method) should never throw a KingdomInternalException. It should only throw `StatusRuntimeException`.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/common/BUILD.bazel, line 6 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/406#-MrU1dmqC7nCJ6BaDiz2:-MrZ6ZIN2bAdXY--DPjA:bss4a2b) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3c4f94a1adc48edcd3f0be604b4ea96c57cffa83/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/common/BUILD.bazel#L6)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This is incorrect. Nothing from a `gcloud` deploy package tree should be exposed outside of `gcloud`-specific package trees.
</blockquote></details>

Removed.


<!-- Sent from Reviewable.io -->

2021-12-22 23:49 UTC, SanjayVas requested changes
> Reviewed 1 of 3 files at r2, 1 of 5 files at r3, 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/406)* status: all files reviewed, 4 unresolved discussions (waiting on @chipingyeh, @robinsons, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateEventGroup.kt, line 72 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/406#-MrZN6b6AUneYXh-BGXE:-MrZN6b6AUneYXh-BGXF:b1npl9j) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d3731c2be1aa742b4c8491668fdace5e3c1a5454/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateEventGroup.kt#L72)):*
> ```Kotlin
>     val externalEventGroupId = idGenerator.generateExternalId()
>     val measurementConsumerCertificateId =
>       if (eventGroup.externalMeasurementConsumerCertificateId > 0L) {
> ```

This looks like a good candidate for extracting a method.



_Code quote:_
```Kotlin
      if (eventGroup.externalMeasurementConsumerCertificateId > 0L) {
        val reader =
          CertificateReader(CertificateReader.ParentType.MEASUREMENT_CONSUMER)
            .bindWhereClause(
              ExternalId(eventGroup.externalMeasurementConsumerId),
              ExternalId(eventGroup.externalMeasurementConsumerCertificateId)
            )

        reader.execute(transactionContext).singleOrNull()?.let {
          if (!it.isValid) {
            throw KingdomInternalException(KingdomInternalException.Code.CERTIFICATE_IS_INVALID)
          } else it.certificateId
        }
          ?: throw KingdomInternalException(KingdomInternalException.Code.CERTIFICATE_NOT_FOUND)
      } else null
```
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt, line 164 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/406#-MrZT3s71qLViMHUYX5e:-MrZT3s71qLViMHUYX5f:bwfx4be) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d3731c2be1aa742b4c8491668fdace5e3c1a5454/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt#L164)):*
> ```Kotlin
>     assertThat(exception)
>       .hasMessageThat()
>       .contains("NOT_FOUND: MeasurementConsumer certificate not found")
> ```

Copying my comment from another PR:

I'm not a fan of checking exception messages in tests unless you really need to in order to differentiate.

Since this is a base test class, the tests here form a contract that all implementations must follow. Ideally you want to allow maximum flexibility for error messages, so if you're checking the exception message then only check the substring(s) that the message *must* contain.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt, line 181 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/406#-MrZXULw7e-1Joc8t1_o:-MrZXULw7e-1Joc8t1_p:b5m0vjh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d3731c2be1aa742b4c8491668fdace5e3c1a5454/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt#L181)):*
> ```Kotlin
>       population.createDataProvider(dataProvidersService).externalDataProviderId
> 
>     val certificate =
> ```

`createMeasurementConsumer` also creates the Certificate for that MC. What this is doing is creating *another* Certificate with a different ID.

I doubt you need a Certificates service instance nor the `CERTIFICATE` constant in this test.


<!-- Sent from Reviewable.io -->

2021-12-23 20:20 UTC, chipingyeh reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/406)* status: 4 of 7 files reviewed, 4 unresolved discussions (waiting on @robinsons, @SanjayVas, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateEventGroup.kt, line 72 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/406#-MrZN6b6AUneYXh-BGXE:-MrcW_tOEP0dOznmJFg-:b-azpd9f) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d3731c2be1aa742b4c8491668fdace5e3c1a5454/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateEventGroup.kt#L72)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This looks like a good candidate for extracting a method.
</blockquote></details>

I'd kept it here since it's only used in one place, but I don't mind moving it -- done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt, line 164 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/406#-MrZT3s71qLViMHUYX5e:-MrceqskE4jtDtrNZSbW:b-6tahpa) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d3731c2be1aa742b4c8491668fdace5e3c1a5454/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt#L164)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Copying my comment from another PR:

I'm not a fan of checking exception messages in tests unless you really need to in order to differentiate.

Since this is a base test class, the tests here form a contract that all implementations must follow. Ideally you want to allow maximum flexibility for error messages, so if you're checking the exception message then only check the substring(s) that the message *must* contain.
</blockquote></details>

Alright, I've reduced the message checking to that of the error code only.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt, line 181 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/406#-MrZXULw7e-1Joc8t1_o:-MrcgXOzAuLiKBJDTOIY:b-pl9tis) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d3731c2be1aa742b4c8491668fdace5e3c1a5454/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt#L181)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

`createMeasurementConsumer` also creates the Certificate for that MC. What this is doing is creating *another* Certificate with a different ID.

I doubt you need a Certificates service instance nor the `CERTIFICATE` constant in this test.
</blockquote></details>

Ah, that's right. Removed both.


<!-- Sent from Reviewable.io -->

2021-12-23 22:50 UTC, SanjayVas requested changes
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/406)* status: all files reviewed, 8 unresolved discussions (waiting on @chipingyeh, @robinsons, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateEventGroup.kt, line 71 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/406#-MrdKcZC-1kyzqZaMfNR:-MrdKcZC-1kyzqZaMfNS:bvfde2n) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/67980bafe9c9eb60f4de3aa98ad785c243676d9c/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateEventGroup.kt#L71)):*
> ```Kotlin
>     measurementConsumerId: Long
>   ): EventGroup {
>     val internalEventGroupId = idGenerator.generateInternalId()
> ```

nit: Specify the type explicitly where it's not immediately clear from the context.

e.g. `InternalId` and `ExternalId` so we know they're not `Long`s, and `InternalId?` to be clear that it's nullable.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateEventGroup.kt, line 113 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/406#-MrdJQIE8eaJqqX-MciB:-MrdJQIE8eaJqqX-MciC:bvt1bmq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/67980bafe9c9eb60f4de3aa98ad785c243676d9c/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateEventGroup.kt#L113)):*
> ```Kotlin
>     transactionContext: AsyncDatabaseClient.TransactionContext
>   ): InternalId? {
>     return if (measurementConsumerCertificateId > 0L) {
> ```

Reduce nesting using guard clauses (see https://testing.googleblog.com/2017/06/code-health-reduce-nesting-reduce.html).

e.g.
```
if (measurementConsumerCertificateId == 0L) {
  return null
}

// ...
```

Though actually this check should be done outside the call, as the only time when we know to check `0` to mean unspecified is when reading a proto field. Function arguments should be assumed to be valid values (often enforced by precondition checks).
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateEventGroup.kt, line 135 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/406#-MrdNhGc00B5_LaUxHmU:-MrdNhGc00B5_LaUxHmV:bwjpznf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/67980bafe9c9eb60f4de3aa98ad785c243676d9c/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateEventGroup.kt#L135)):*
> ```Kotlin
>       eventGroup
>     } else {
>       eventGroup
> ```

nit: switch new proto code to use Kotlin DSL builders. In this case, use `eventGroup.copy {}` rather than `eventGroup.toBuilder`. See https://developers.google.com/protocol-buffers/docs/reference/kotlin-generated#message
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt, line 164 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/406#-MrZT3s71qLViMHUYX5e:-MrdOfZf3T9OxgPpF2Gn:bsa7onm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d3731c2be1aa742b4c8491668fdace5e3c1a5454/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt#L164)):*
<details><summary><i>Previously, chipingyeh wrote…</i></summary><blockquote>

Alright, I've reduced the message checking to that of the error code only.
</blockquote></details>

Not sure there's a huge value in checking the code prefix in the description given that it's forced to be there by the StatusRuntimeException implementation.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt, line 50 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/406#-MrdQSLQ3gP0znbGPdaS:-MrdQSLQ3gP0znbGPdaT:brmtmb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/67980bafe9c9eb60f4de3aa98ad785c243676d9c/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt#L50)):*
> ```Kotlin
> private const val PROVIDED_EVENT_GROUP_ID = "ProvidedEventGroupId"
> private val DETAILS = details {
>   apiVersion = "v2Alpha"
> ```

Use `Version.V2_ALPHA.string` from `org.wfanet.measurement.api`.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt, line 207 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/406#-MrdRJ9y4hdsaF9UaOdt:-MrdRJ9y4hdsaF9UaOdu:bmspuse) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/67980bafe9c9eb60f4de3aa98ad785c243676d9c/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt#L207)):*
> ```Kotlin
>           .toBuilder()
>           .also {
>             it.externalEventGroupId = createdEventGroup.externalEventGroupId
> ```

I know this part was already there before your PR, but you're basically comparing parts of the actual value to itself here.

What I'd recommend doing is explicitly ignoring fields that you can't directly compare, and then adding assertions based on what you do know about those fields.

e.g.
```
assertThat(createdEventGroup)
  .ignoringFields(EventGroup.EXTERNAL_EVENT_GROUP_ID_FIELD_NUMBER, EventGroup.CREATE_TIME_FIELD_NUMBER, EventGroup.UPDATE_TIME_FIELD_NUMBER)
  .isEqualTo(eventGroup)
assertThat(createdEventGroup.externalEventGroupId).isGreaterThan(0)
assertThat(createdEventGroup.createTime.seconds).isGreaterThan(0)
assertThat(createdEventGroup.updateTime).isEqualTo(createdEventGroup.createTime)
```
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt, line 210 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/406#-MrdRght9jip8jVKJ2Z-:-MrdRght9jip8jVKJ2Z0:b-lln88v) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/67980bafe9c9eb60f4de3aa98ad785c243676d9c/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt#L210)):*
> ```Kotlin
>             it.createTime = createdEventGroup.createTime
>             it.updateTime = createdEventGroup.createTime
>             it.details = DETAILS
> ```

Details should already be set in the request `eventGroup`.


<!-- Sent from Reviewable.io -->

2021-12-28 16:32 UTC, chipingyeh reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/406)* status: 5 of 7 files reviewed, 7 unresolved discussions (waiting on @robinsons, @SanjayVas, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateEventGroup.kt, line 71 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/406#-MrdKcZC-1kyzqZaMfNR:-Ms0gw6bBAhNMsORSVmy:bvlkjpb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/67980bafe9c9eb60f4de3aa98ad785c243676d9c/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateEventGroup.kt#L71)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: Specify the type explicitly where it's not immediately clear from the context.

e.g. `InternalId` and `ExternalId` so we know they're not `Long`s, and `InternalId?` to be clear that it's nullable.
</blockquote></details>

This is outside of the changes in my PR, but I've gone ahead and updated the names.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateEventGroup.kt, line 113 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/406#-MrdJQIE8eaJqqX-MciB:-Ms0iTJN63LkfKk4CREW:b-fkebrg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/67980bafe9c9eb60f4de3aa98ad785c243676d9c/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateEventGroup.kt#L113)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Reduce nesting using guard clauses (see https://testing.googleblog.com/2017/06/code-health-reduce-nesting-reduce.html).

e.g.
```
if (measurementConsumerCertificateId == 0L) {
  return null
}

// ...
```

Though actually this check should be done outside the call, as the only time when we know to check `0` to mean unspecified is when reading a proto field. Function arguments should be assumed to be valid values (often enforced by precondition checks).
</blockquote></details>

Moved check to outside of the function.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateEventGroup.kt, line 135 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/406#-MrdNhGc00B5_LaUxHmU:-Ms0jG2s9CoL8J1o0FFh:b-7crw9o) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/67980bafe9c9eb60f4de3aa98ad785c243676d9c/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateEventGroup.kt#L135)):*
> https://developers.google.com/protocol-buffers/docs/reference/kotlin-generated#message
Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt, line 164 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/406#-MrZT3s71qLViMHUYX5e:-Ms0kDsACqDgws2RCBcy:bd6aswg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d3731c2be1aa742b4c8491668fdace5e3c1a5454/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt#L164)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Not sure there's a huge value in checking the code prefix in the description given that it's forced to be there by the StatusRuntimeException implementation.
</blockquote></details>

I've updated it to check part of the message I included, feel free to suggest specifics if you feel otherwise.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt, line 50 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/406#-MrdQSLQ3gP0znbGPdaS:-Ms0jWUsAdPcVGnjsVBK:b6uuwpa) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/67980bafe9c9eb60f4de3aa98ad785c243676d9c/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt#L50)):*
> Version.V2_ALPHA.string
Good call -- done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt, line 207 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/406#-MrdRJ9y4hdsaF9UaOdt:-Ms0oCAg64rdzyfnOhYs:bhb8dc4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/67980bafe9c9eb60f4de3aa98ad785c243676d9c/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt#L207)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I know this part was already there before your PR, but you're basically comparing parts of the actual value to itself here.

What I'd recommend doing is explicitly ignoring fields that you can't directly compare, and then adding assertions based on what you do know about those fields.

e.g.
```
assertThat(createdEventGroup)
  .ignoringFields(EventGroup.EXTERNAL_EVENT_GROUP_ID_FIELD_NUMBER, EventGroup.CREATE_TIME_FIELD_NUMBER, EventGroup.UPDATE_TIME_FIELD_NUMBER)
  .isEqualTo(eventGroup)
assertThat(createdEventGroup.externalEventGroupId).isGreaterThan(0)
assertThat(createdEventGroup.createTime.seconds).isGreaterThan(0)
assertThat(createdEventGroup.updateTime).isEqualTo(createdEventGroup.createTime)
```
</blockquote></details>

Sounds fine -- updated.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt, line 210 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/406#-MrdRght9jip8jVKJ2Z-:-Ms0nonRAnfpQnDkJMQF:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/67980bafe9c9eb60f4de3aa98ad785c243676d9c/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt#L210)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Details should already be set in the request `eventGroup`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-04 18:23 UTC, robinsons approved these changes
> Reviewed 1 of 5 files at r5, 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/406)* status: all files reviewed, 6 unresolved discussions (waiting on @chipingyeh, @SanjayVas, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateEventGroup.kt, line 71 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/406#-MrdKcZC-1kyzqZaMfNR:-MsaEJNkB4r_o1FPzyGA:bw2yzzs) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/67980bafe9c9eb60f4de3aa98ad785c243676d9c/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateEventGroup.kt#L71)):*
<details><summary><i>Previously, chipingyeh wrote…</i></summary><blockquote>

This is outside of the changes in my PR, but I've gone ahead and updated the names.
</blockquote></details>

IIUC, rather than changing the variable name, Sanjay is actually suggesting to specify the type explicitly, e.g.

`val internalEventGroupId: InternalId = idGenerator.generateInternalId()`

This way the reader knows it's an `InternalId` rather than a raw ID, like a `Long` or a `String`.


<!-- Sent from Reviewable.io -->

2022-01-04 19:59 UTC, chipingyeh reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/406)* status: 6 of 7 files reviewed, 5 unresolved discussions (waiting on @robinsons, @SanjayVas, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateEventGroup.kt, line 71 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/406#-MrdKcZC-1kyzqZaMfNR:-Msaf1Wt3pOLD8SAPg9m:bcr5s2o) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/67980bafe9c9eb60f4de3aa98ad785c243676d9c/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateEventGroup.kt#L71)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

IIUC, rather than changing the variable name, Sanjay is actually suggesting to specify the type explicitly, e.g.

`val internalEventGroupId: InternalId = idGenerator.generateInternalId()`

This way the reader knows it's an `InternalId` rather than a raw ID, like a `Long` or a `String`.
</blockquote></details>

Got it, thanks!


<!-- Sent from Reviewable.io -->

2022-01-05 21:44 UTC, robinsons approved these changes
> Reviewed 1 of 1 files at r8, 1 of 74 files at r10, 2 of 43 files at r13, 2 of 2 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/406)* status: 6 of 142 files reviewed, 5 unresolved discussions (waiting on @robinsons, @SanjayVas, and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2022-01-10 18:02 UTC, SanjayVas reviewed
> Reviewed 1 of 43 files at r13, 2 of 2 files at r16, 3 of 3 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/406)* status: 6 of 142 files reviewed, all discussions resolved (waiting on @robinsons, @SanjayVas, and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2022-01-10 18:07 UTC, SanjayVas approved these changes
> Reviewed 136 of 138 files at r15, 1 of 2 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/406)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)



<!-- Sent from Reviewable.io -->

2022-01-10 18:50 UTC, stevenwarejones approved these changes
> Reviewed 1 of 3 files at r2, 2 of 5 files at r5, 1 of 43 files at r13, 3 of 3 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/406)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @chipingyeh)



<!-- Sent from Reviewable.io -->

2022-01-10 18:52 UTC, merged