Implement internal UpdateEventGroup
world-federation-of-advertisers/cross-media-measurement pull request #413
Opened 2022-01-06 17:46 UTC by chipingyeh

2022-01-06 22:15 UTC, robinsons requested changes
> Reviewed 1 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/413)* status: 1 of 3 files reviewed, 8 unresolved discussions (waiting on @chipingyeh and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/UpdateEventGroup.kt, line 38 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/413#-MskpW3A3UN97eIH7BLO:-MskpW3A3UN97eIH7BLP:blyv47d) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2955ec7883e5596e05c7609a36ea8dbd34b8b76d/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/UpdateEventGroup.kt#L38)):*
> ```Kotlin
>         .readByExternalId(transactionContext, eventGroup.externalEventGroupId)
>         ?.eventGroup
>         ?: throw KingdomInternalException(KingdomInternalException.Code.ACCOUNT_NOT_FOUND)
> ```

The `ACCOUNT_NOT_FOUND` code is specific to the `Account` resource. We should make a new error code for `EVENT_GROUP_NOT_FOUND`.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/UpdateEventGroup.kt, line 41 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/413#-MslC-WK0rsJGBvoGPpu:-MslC-WK0rsJGBvoGPpv:b-5ktyux) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2955ec7883e5596e05c7609a36ea8dbd34b8b76d/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/UpdateEventGroup.kt#L41)):*
> ```Kotlin
>     if (internalEventGroup.externalDataProviderId != eventGroup.externalDataProviderId) {
>       throw KingdomInternalException(KingdomInternalException.Code.DATA_PROVIDER_NOT_FOUND)
>     }
> ```

Something was bothering me about this snippet of code, and I think it's that `readByExternalId()` is not defined as it should be. The `EventGroup` resource is a child of `DataProvider`, so it doesn't make sense to read using only `externalEventGroupId`, because this ID is not necessarily unique among all `EventGroup`s.

I think what we want to do is add `externalDataProviderId` as an additional parameter to `readByExternalId()`. This way you don't have to do the bit where you compare `internalEventGroup.externalDataProviderId` and ` eventGroup.externalDataProviderId`, because the read will only return an `EventGroup` if *both* the data provider and event group IDs match.



_Code quote:_
```Kotlin
    val internalEventGroup =
      EventGroupReader()
        .readByExternalId(transactionContext, eventGroup.externalEventGroupId)
        ?.eventGroup
        ?: throw KingdomInternalException(KingdomInternalException.Code.ACCOUNT_NOT_FOUND)
    if (internalEventGroup.externalDataProviderId != eventGroup.externalDataProviderId) {
      throw KingdomInternalException(KingdomInternalException.Code.DATA_PROVIDER_NOT_FOUND)
    }
```
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/UpdateEventGroup.kt, line 44 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/413#-MslIQtu5impAATaBpYY:-MslIQtu5impAATaBpYZ:bqqxpwf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2955ec7883e5596e05c7609a36ea8dbd34b8b76d/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/UpdateEventGroup.kt#L44)):*
> ```Kotlin
>     if (internalEventGroup.externalMeasurementConsumerId != eventGroup.externalMeasurementConsumerId
>     ) {
>       throw KingdomInternalException(KingdomInternalException.Code.MEASUREMENT_CONSUMER_NOT_FOUND)
> ```

`MEASUREMENT_CONSUMER_NOT_FOUND` doesn't feel entirely appropriate here. The real issue is the field is immutable, so changing it is not permitted. We should probably have a new error code for this, either something generic like `EVENT_GROUP_MODIFICATION_INVALID` to catch all manner of `INVALID_ARGUMENT`-like errors, or something more specific to this scenario, like `EVENT_GROUP_MEASUREMENT_CONSUMER_IS_INVALID`.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/UpdateEventGroup.kt, line 54 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/413#-MslKjHgBfF5ZqLAc22s:-MslKjHgBfF5ZqLAc22t:b-jmpncv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2955ec7883e5596e05c7609a36ea8dbd34b8b76d/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/UpdateEventGroup.kt#L54)):*
> ```Kotlin
>         )
>         ?.dataProviderId
>         ?: throw KingdomInternalException(KingdomInternalException.Code.DATA_PROVIDER_NOT_FOUND)
> ```

Instead of doing this extra read just to get the internal data provider ID, we can add the ID to the existing `EventGroupReader.Result` data class. Since this ID is part of the primary key of the `EventGroups` table, it's perfectly reasonable to include it there.



_Code quote:_
```Kotlin
    val dataProviderId =
      DataProviderReader()
        .readByExternalDataProviderId(
          transactionContext,
          ExternalId(eventGroup.externalDataProviderId)
        )
        ?.dataProviderId
        ?: throw KingdomInternalException(KingdomInternalException.Code.DATA_PROVIDER_NOT_FOUND)
```
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/UpdateEventGroup.kt, line 65 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/413#-MslNvEHDhy19cPWAztO:-MslNvEHDhy19cPWAztP:b-jaqx7l) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2955ec7883e5596e05c7609a36ea8dbd34b8b76d/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/UpdateEventGroup.kt#L65)):*
> ```Kotlin
>     val internalEventGroupId =
>       EventGroupReader()
>         .readByExternalId(transactionContext, eventGroup.externalEventGroupId)
> ```

We don't need to do this read twice. Instead, further up where we read the `EventGroup`, let's just save a reference to the entire `EventGroupReader.Result`.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/UpdateEventGroup.kt, line 92 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/413#-MslMyhoBVePO0t1PEkM:-MslMyhoBVePO0t1PEkN:b-wj0srx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2955ec7883e5596e05c7609a36ea8dbd34b8b76d/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/UpdateEventGroup.kt#L92)):*
> ```Kotlin
>   }
> 
>   private suspend fun checkValidCertificate(
> ```

This is a copy of the same function from #406, right? After one of these PRs is merged, when you're rebasing the other, could you put this function in a common place so that it's not duplicated?
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt, line 217 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/413#-MslS05DAA16N47CU4Wl:-MslS05EEwgRbLMVT22U:bueheba) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2955ec7883e5596e05c7609a36ea8dbd34b8b76d/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt#L217)):*
> ```Kotlin
>       )
>   }
> ```

We should add tests like you have in #406 for not found and invalid MC certificates.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt, line 294 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/413#-MslRHo_4QpzAH3FbTYb:-MslRHo_4QpzAH3FbTYc:b-qxbs29) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2955ec7883e5596e05c7609a36ea8dbd34b8b76d/src/main/kotlin/org/wfanet/ [...]

2022-01-07 21:18 UTC, chipingyeh reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/413)* status: 0 of 14 files reviewed, 8 unresolved discussions (waiting on @robinsons and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/UpdateEventGroup.kt, line 38 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/413#-MskpW3A3UN97eIH7BLO:-MslW6ANBf2LJcW3bhE7:b-t574cs) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2955ec7883e5596e05c7609a36ea8dbd34b8b76d/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/UpdateEventGroup.kt#L38)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

The `ACCOUNT_NOT_FOUND` code is specific to the `Account` resource. We should make a new error code for `EVENT_GROUP_NOT_FOUND`.
</blockquote></details>

I initially did this, only to find that I would need to update several other files that rely on exhaustively listing out the errors, [for example](https://sourcegraph.com/github.com/world-federation-of-advertisers/cross-media-measurement/-/blob/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerAccountsService.kt?L77). It seems like this is what some other PRs do, so I've gone ahead and updated it.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/UpdateEventGroup.kt, line 41 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/413#-MslC-WK0rsJGBvoGPpu:-Mspy38p7_igpb9aoLQw:bd2k9w9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2955ec7883e5596e05c7609a36ea8dbd34b8b76d/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/UpdateEventGroup.kt#L41)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

Something was bothering me about this snippet of code, and I think it's that `readByExternalId()` is not defined as it should be. The `EventGroup` resource is a child of `DataProvider`, so it doesn't make sense to read using only `externalEventGroupId`, because this ID is not necessarily unique among all `EventGroup`s.

I think what we want to do is add `externalDataProviderId` as an additional parameter to `readByExternalId()`. This way you don't have to do the bit where you compare `internalEventGroup.externalDataProviderId` and ` eventGroup.externalDataProviderId`, because the read will only return an `EventGroup` if *both* the data provider and event group IDs match.
</blockquote></details>

This makes sense and helps make the validation easier -- updated.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/UpdateEventGroup.kt, line 44 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/413#-MslIQtu5impAATaBpYY:-MspqFol9vuG-AFQZkT_:bmilhd6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2955ec7883e5596e05c7609a36ea8dbd34b8b76d/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/UpdateEventGroup.kt#L44)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

`MEASUREMENT_CONSUMER_NOT_FOUND` doesn't feel entirely appropriate here. The real issue is the field is immutable, so changing it is not permitted. We should probably have a new error code for this, either something generic like `EVENT_GROUP_MODIFICATION_INVALID` to catch all manner of `INVALID_ARGUMENT`-like errors, or something more specific to this scenario, like `EVENT_GROUP_MEASUREMENT_CONSUMER_IS_INVALID`.
</blockquote></details>

I opted for a generic error due to the file-updating burden mentioned above.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/UpdateEventGroup.kt, line 54 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/413#-MslKjHgBfF5ZqLAc22s:-Msq1ChA3B6t5NJ_cArG:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2955ec7883e5596e05c7609a36ea8dbd34b8b76d/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/UpdateEventGroup.kt#L54)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

Instead of doing this extra read just to get the internal data provider ID, we can add the ID to the existing `EventGroupReader.Result` data class. Since this ID is part of the primary key of the `EventGroups` table, it's perfectly reasonable to include it there.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/UpdateEventGroup.kt, line 65 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/413#-MslNvEHDhy19cPWAztO:-Msq1Yuf1whA76pKB6gS:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2955ec7883e5596e05c7609a36ea8dbd34b8b76d/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/UpdateEventGroup.kt#L65)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

We don't need to do this read twice. Instead, further up where we read the `EventGroup`, let's just save a reference to the entire `EventGroupReader.Result`.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/UpdateEventGroup.kt, line 92 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/413#-MslMyhoBVePO0t1PEkM:-Msq1cdA08bP2cbQhk-n:b4sgtuj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2955ec7883e5596e05c7609a36ea8dbd34b8b76d/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/UpdateEventGroup.kt#L92)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

This is a copy of the same function from #406, right? After one of these PRs is merged, when you're rebasing the other, could you put this function in a common place so that it's not duplicated?
</blockquote></details>

Can do -- is there a file you would suggest placing it in? I had mostly put some logic from this [file](https://sourcegraph.com/github.com/world-federation-of-advertisers/cross-media-measurement/-/blob/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurement.kt?L100) into a single function.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt, line 217 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/413#-MslS05DAA16N47CU4Wl:-MsqOAtKE1f4F072GUuF:bbxzykk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2955ec7883e5596e05c7609a36ea8dbd34b8b76d/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt#L217)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

We should add tests like you have in #406 for not found and invalid MC certificates.
</blockquote></details>

I added a couple tests, but had issues creating an invalid certificate to update the EventGroup with (CertificateReader cannot find the certificate when running the test). Would appreciate any tips here.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt, line 294 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/413#-MslRHo_4QpzAH3FbTYb:-MsqO9XdDZe2mNJtyy5T:b-s0ro35) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2955ec7883e5596e05c7609a36ea8dbd34b8b76d/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt#L294)):*
<details><summary><i>Previously, rob [...]

2022-01-07 22:20 UTC, robinsons requested changes
> Reviewed 14 of 14 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/413)* status: all files reviewed, 6 unresolved discussions (waiting on @chipingyeh and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerEventGroupsService.kt, line 79 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/413#-MsqZHXl1gCTKi8fzQwH:-MsqZHXmCstU4pO_PF9Z:bti0a6v) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/29b09431fee7aae7f7e3e8ef09b11f1eada241c3/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerEventGroupsService.kt#L79)):*
> ```Kotlin
>           failGrpc(Status.INVALID_ARGUMENT) { "EventGroup modification param is invalid" }
>         KingdomInternalException.Code.DATA_PROVIDER_NOT_FOUND ->
>           failGrpc(Status.INVALID_ARGUMENT) { "DataProvider not found" }
> ```

I don't think we need this special arm for `DATA_PROVIDER_NOT_FOUND`. It would manifest as `EVENT_GROUP_NOT_FOUND`, because `EventGroup` is a child of `DataProvider`.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/EventGroupReader.kt, line 70 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/413#-MsqUpHp3biSqATWD2lW:-MsqUpHp3biSqATWD2lX:bwviyax) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/29b09431fee7aae7f7e3e8ef09b11f1eada241c3/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/EventGroupReader.kt#L70)):*
> ```Kotlin
>   }
> 
>   suspend fun readByExternalId(
> ```

Since we've added an additional ID to read by, can the method name be changed to `readByExternalIds()` (plural)? This appears to be consistent with other reader classes.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/EventGroupReader.kt, line 73 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/413#-MsqTa23DS-tp_vlFKnw:-MsqTa23DS-tp_vlFKnx:b-s43dru) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/29b09431fee7aae7f7e3e8ef09b11f1eada241c3/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/EventGroupReader.kt#L73)):*
> ```Kotlin
>     readContext: AsyncDatabaseClient.ReadContext,
>     externalEventGroupId: Long,
>     externalDataProviderId: Long,
> ```

It would be a bit more intuitive to change the order of these arguments. The reason is that `EventGroup` is a child resource of `DataProvider`, and this is reflected in the order of parts in the resource name, `dataProviders/{data_provider_id}/eventGroups/{event_group_id}`, as well as the order of the primary key elements in the `EventGroups` table. This gives callers a reason to expect that the ID parts would be passed in a certain order, and they might pass them in the incorrect order if they didn't pay attention to the method's parameter names.



_Code quote:_
```Kotlin
    externalEventGroupId: Long,
    externalDataProviderId: Long,
```
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/UpdateEventGroup.kt, line 92 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/413#-MslMyhoBVePO0t1PEkM:-MsqXKsn0p6dnRRd46vr:b-ynames) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2955ec7883e5596e05c7609a36ea8dbd34b8b76d/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/UpdateEventGroup.kt#L92)):*
<details><summary><i>Previously, chipingyeh wrote…</i></summary><blockquote>

Can do -- is there a file you would suggest placing it in? I had mostly put some logic from this [file](https://sourcegraph.com/github.com/world-federation-of-advertisers/cross-media-measurement/-/blob/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurement.kt?L100) into a single function.
</blockquote></details>

This would be a good question to ask Sanjay on Slack next week when he's back. I poked around a bit but didn't see another similar case.

I could think of a couple options:
1. Make a base class `EventGroupSpannerWriter` to hold common logic.
2. Create a file `EventGroups.kt` with helper/extension functions.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt, line 217 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/413#-MslS05DAA16N47CU4Wl:-Msq_xsaCpVATgFtGuII:b-cqrd31) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2955ec7883e5596e05c7609a36ea8dbd34b8b76d/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt#L217)):*
<details><summary><i>Previously, chipingyeh wrote…</i></summary><blockquote>

I added a couple tests, but had issues creating an invalid certificate to update the EventGroup with (CertificateReader cannot find the certificate when running the test). Would appreciate any tips here.
</blockquote></details>

Try creating the invalid certificate the same way as in #406, by creating it at the time you call `createMeasurementConsumer()`. But don't specify this invalid certificate ID when calling `createEventGroup()`: only set it when calling `updateEventGroup()`. Maybe that will work.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt, line 294 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/413#-MslRHo_4QpzAH3FbTYb:-Msqb4OnCb4aJcYMCIaW:bc7aulg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2955ec7883e5596e05c7609a36ea8dbd34b8b76d/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt#L294)):*
<details><summary><i>Previously, chipingyeh wrote…</i></summary><blockquote>

Added a test for this.
</blockquote></details>

Thanks!

For context, the reason I asked is that I'm personally unsure on the behavior of `set()` when building the Spanner mutation, specifically for those columns that **aren't** set due to the surrounding if-statements (like `providedEventGroupId`). I don't know if skipping a call to `set()` will (a) implicitly set the column to `NULL`, or (b) leave the column unchanged. If it's (b), then the new test will fail once it's merged with #406.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt, line 423 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/413#-Msqaaqm61Fi8gzh36Rb:-Msqaaqm61Fi8gzh36Rc:bwn5ydy) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/29b09431fee7aae7f7e3e8ef09b11f1eada241c3/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt#L423)):*
> ```Kotlin
>           this.externalDataProviderId = externalDataProviderId
>           this.externalMeasurementConsumerId = externalMeasurementConsumerId
>           this.externalMeasurementConsumerCertificateId = 5L
> ```

This value, `5L`, needs to be a real certificate ID, doesn't it? It should be `measurementConsumer.certificate.externalCertificateId`. Setting it to an arbitrary value won't work once #406 is merged.


<!-- Sent from Reviewable.io -->

2022-01-10 17:09 UTC, chipingyeh reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/413)* status: 9 of 14 files reviewed, 6 unresolved discussions (waiting on @chipingyeh, @robinsons, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerEventGroupsService.kt, line 79 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/413#-MsqZHXl1gCTKi8fzQwH:-Mt3iIAX36N1FFiLPXgi:b-rkmkbe) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/29b09431fee7aae7f7e3e8ef09b11f1eada241c3/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerEventGroupsService.kt#L79)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

I don't think we need this special arm for `DATA_PROVIDER_NOT_FOUND`. It would manifest as `EVENT_GROUP_NOT_FOUND`, because `EventGroup` is a child of `DataProvider`.
</blockquote></details>

Good point - I'd accounted for this in my test but didn't remove this line -- done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/EventGroupReader.kt, line 70 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/413#-MsqUpHp3biSqATWD2lW:-Mt3jIKo-GN33jDB2_XU:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/29b09431fee7aae7f7e3e8ef09b11f1eada241c3/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/EventGroupReader.kt#L70)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

Since we've added an additional ID to read by, can the method name be changed to `readByExternalIds()` (plural)? This appears to be consistent with other reader classes.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/EventGroupReader.kt, line 73 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/413#-MsqTa23DS-tp_vlFKnw:-Mt3jRoC-2h9hsoHwHhC:b-n6mz3w) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/29b09431fee7aae7f7e3e8ef09b11f1eada241c3/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/EventGroupReader.kt#L73)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

It would be a bit more intuitive to change the order of these arguments. The reason is that `EventGroup` is a child resource of `DataProvider`, and this is reflected in the order of parts in the resource name, `dataProviders/{data_provider_id}/eventGroups/{event_group_id}`, as well as the order of the primary key elements in the `EventGroups` table. This gives callers a reason to expect that the ID parts would be passed in a certain order, and they might pass them in the incorrect order if they didn't pay attention to the method's parameter names.
</blockquote></details>

Sure, that makes sense -- done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/UpdateEventGroup.kt, line 92 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/413#-MslMyhoBVePO0t1PEkM:-Mt3wM0-9mBJWhU0K_Ey:b8bj0jt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2955ec7883e5596e05c7609a36ea8dbd34b8b76d/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/UpdateEventGroup.kt#L92)):*
> Make a base class EventGroupSpannerWriter to hold common logic.
> Create a file EventGroups.kt with helper/extension functions.
Will do -- may send back review for other feedback in the meantime.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt, line 217 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/413#-MslS05DAA16N47CU4Wl:-Mt3v7rm0k84Pjr8KtI2:bhcu5ao) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2955ec7883e5596e05c7609a36ea8dbd34b8b76d/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt#L217)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

Try creating the invalid certificate the same way as in #406, by creating it at the time you call `createMeasurementConsumer()`. But don't specify this invalid certificate ID when calling `createEventGroup()`: only set it when calling `updateEventGroup()`. Maybe that will work.
</blockquote></details>

That worked, thank you -- uncommented test.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt, line 294 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/413#-MslRHo_4QpzAH3FbTYb:-Mt3mZyZCJc-OmdG-xNO:bpcrgal) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2955ec7883e5596e05c7609a36ea8dbd34b8b76d/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt#L294)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

Thanks!

For context, the reason I asked is that I'm personally unsure on the behavior of `set()` when building the Spanner mutation, specifically for those columns that **aren't** set due to the surrounding if-statements (like `providedEventGroupId`). I don't know if skipping a call to `set()` will (a) implicitly set the column to `NULL`, or (b) leave the column unchanged. If it's (b), then the new test will fail once it's merged with #406.
</blockquote></details>

That's fair - I did a quick test for (b) where I made a `getEventGroup()` call after `updateEventGroup()` and providedEventGroup was indeed unmodified. Would you recommend removing the if-statement checks for `UpdateEventGroup` then, to allow for clearing of non-required fields?
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt, line 423 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/413#-Msqaaqm61Fi8gzh36Rb:-Mt3mUye1XrJ0tt2zFsK:b-8vryic) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/29b09431fee7aae7f7e3e8ef09b11f1eada241c3/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt#L423)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

This value, `5L`, needs to be a real certificate ID, doesn't it? It should be `measurementConsumer.certificate.externalCertificateId`. Setting it to an arbitrary value won't work once #406 is merged.
</blockquote></details>

Yes I think that's correct -- done.


<!-- Sent from Reviewable.io -->

2022-01-10 17:27 UTC, robinsons requested changes
> Reviewed 3 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/413)* status: 12 of 14 files reviewed, 2 unresolved discussions (waiting on @chipingyeh, @robinsons, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt, line 294 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/413#-MslRHo_4QpzAH3FbTYb:-Mt406BD9STHo4iAnwzZ:b-uzbhpm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2955ec7883e5596e05c7609a36ea8dbd34b8b76d/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt#L294)):*
<details><summary><i>Previously, chipingyeh wrote…</i></summary><blockquote>

That's fair - I did a quick test for (b) where I made a `getEventGroup()` call after `updateEventGroup()` and providedEventGroup was indeed unmodified. Would you recommend removing the if-statement checks for `UpdateEventGroup` then, to allow for clearing of non-required fields?
</blockquote></details>

Ah, yeah, in that case I guess we should explicitly set those values to null.


<!-- Sent from Reviewable.io -->

2022-01-10 19:14 UTC, chipingyeh reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/413)* status: 8 of 16 files reviewed, 2 unresolved discussions (waiting on @chipingyeh, @robinsons, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/UpdateEventGroup.kt, line 92 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/413#-MslMyhoBVePO0t1PEkM:-Mt4JWi69cVvG0WoASeW:bhlwgd8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2955ec7883e5596e05c7609a36ea8dbd34b8b76d/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/UpdateEventGroup.kt#L92)):*
<details><summary><i>Previously, chipingyeh wrote…</i></summary><blockquote>

> Make a base class EventGroupSpannerWriter to hold common logic.
> Create a file EventGroups.kt with helper/extension functions.
Will do -- may send back review for other feedback in the meantime.
</blockquote></details>

Created EventGroups.kt and opted to put it in `/writers` since putting it in `/common` would result in a circular dependency on `/reader`.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt, line 294 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/413#-MslRHo_4QpzAH3FbTYb:-Mt4Ceni8cjhMDa8dorC:b1rs2kt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2955ec7883e5596e05c7609a36ea8dbd34b8b76d/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt#L294)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

Ah, yeah, in that case I guess we should explicitly set those values to null.
</blockquote></details>

Removed the if-statements - I feel the current method of checking mutations is somewhat incomplete since we are effectively testing the `buildResult` function which just builds off the original input. Do you think a `getEventGroup()` call would be advised for these tests, so we're checking the actual db values?


<!-- Sent from Reviewable.io -->

2022-01-10 20:53 UTC, stevenwarejones requested changes
> Reviewed 6 of 14 files at r2, 1 of 5 files at r3, 4 of 7 files at r4.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/413)* status: 13 of 16 files reviewed, 3 unresolved discussions (waiting on @chipingyeh and @robinsons)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/UpdateEventGroup.kt, line 39 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/413#-Mt4j6_DCIz_jXu4cnvK:-Mt4j6_DCIz_jXu4cnvL:bf6x6dk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/35b0521dcfe6fb9931da3b532139513e3c6cf1d8/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/UpdateEventGroup.kt#L39)):*
> ```Kotlin
>         eventGroup.externalMeasurementConsumerId
>     ) {
>       throw KingdomInternalException(KingdomInternalException.Code.EVENT_GROUP_MODIFICATION_INVALID)
> ```

Is this the right name for this error? Maybe just EVENT_GROUP_INVALID_ARGS?


<!-- Sent from Reviewable.io -->

2022-01-10 21:36 UTC, robinsons requested changes
> Reviewed 1 of 5 files at r3, 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/413)* status: all files reviewed, 4 unresolved discussions (waiting on @chipingyeh)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/EventGroups.kt, line 26 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/413#-Mt4uJ7mEUQodEpx9J5z:-Mt4uJ7mEUQodEpx9J6-:bcbv510) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/35b0521dcfe6fb9931da3b532139513e3c6cf1d8/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/EventGroups.kt#L26)):*
> ```Kotlin
> class EventGroups {
>   companion object {
>     suspend fun checkValidCertificate(
> ```

Kotlin lets us define this function at the top-level, without an enclosing `class` or `companion object`. I believe that we generally prefer to do that where possible.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/UpdateEventGroup.kt, line 55 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/413#-Mt4pqdh71b_EOfnzB43:-Mt4pqdh71b_EOfnzB44:bxj71xy) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/35b0521dcfe6fb9931da3b532139513e3c6cf1d8/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/UpdateEventGroup.kt#L55)):*
> ```Kotlin
>       set("EventGroupId" to internalEventGroupResult.internalEventGroupId.value)
>       set("MeasurementConsumerCertificateId" to measurementConsumerCertificateId)
>       set("ProvidedEventGroupId" to eventGroup.providedEventGroupId)
> ```

We should set `ProvidedEventGroupId` to `NULL` if the value is blank.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt, line 294 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/413#-MslRHo_4QpzAH3FbTYb:-Mt4scWw9U_eUwXeNO-q:b-bgrla6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2955ec7883e5596e05c7609a36ea8dbd34b8b76d/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt#L294)):*
<details><summary><i>Previously, chipingyeh wrote…</i></summary><blockquote>

Removed the if-statements - I feel the current method of checking mutations is somewhat incomplete since we are effectively testing the `buildResult` function which just builds off the original input. Do you think a `getEventGroup()` call would be advised for these tests, so we're checking the actual db values?
</blockquote></details>

Hm, I see what you're saying. I think it's OK because our Spanner utilities have been written so that the thing you build in `runTransaction()` is either committed and returned, or it results in a `SpannerException`.

But if you still have concerns, you could verify this with a single test. Just add a test that utilizes `updateEventGroup()`, then calls `getEventGroup()`, and asserts that the values are equal. As long as that test passes, then we can conclude that the others are good, too.


<!-- Sent from Reviewable.io -->

2022-01-10 22:10 UTC, chipingyeh reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/413)* status: 13 of 16 files reviewed, 3 unresolved discussions (waiting on @robinsons and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/EventGroups.kt, line 26 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/413#-Mt4uJ7mEUQodEpx9J5z:-Mt4z7FI4pF4sItQ6jhY:btdneyi) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/35b0521dcfe6fb9931da3b532139513e3c6cf1d8/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/EventGroups.kt#L26)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

Kotlin lets us define this function at the top-level, without an enclosing `class` or `companion object`. I believe that we generally prefer to do that where possible.
</blockquote></details>

Good to know -- done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/UpdateEventGroup.kt, line 39 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/413#-Mt4j6_DCIz_jXu4cnvK:-Mt4yZv68DoWjWx-S32m:b-b11zya) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/35b0521dcfe6fb9931da3b532139513e3c6cf1d8/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/UpdateEventGroup.kt#L39)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

Is this the right name for this error? Maybe just EVENT_GROUP_INVALID_ARGS?
</blockquote></details>

This is from the list from the [KingdomInternalException](https://sourcegraph.com/github.com/world-federation-of-advertisers/cross-media-measurement/-/blob/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/common/KingdomInternalException.kt?L17:7) class, and we added a new code for this type of error.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/UpdateEventGroup.kt, line 55 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/413#-Mt4pqdh71b_EOfnzB43:-Mt4yTm4EXsPzRonz3DJ:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/35b0521dcfe6fb9931da3b532139513e3c6cf1d8/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/UpdateEventGroup.kt#L55)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

We should set `ProvidedEventGroupId` to `NULL` if the value is blank.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt, line 294 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/413#-MslRHo_4QpzAH3FbTYb:-Mt501yQ1pt5yrDsWrJt:b67bhc8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2955ec7883e5596e05c7609a36ea8dbd34b8b76d/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt#L294)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

Hm, I see what you're saying. I think it's OK because our Spanner utilities have been written so that the thing you build in `runTransaction()` is either committed and returned, or it results in a `SpannerException`.

But if you still have concerns, you could verify this with a single test. Just add a test that utilizes `updateEventGroup()`, then calls `getEventGroup()`, and asserts that the values are equal. As long as that test passes, then we can conclude that the others are good, too.
</blockquote></details>

Fair point, I'll leave as-is for now.


<!-- Sent from Reviewable.io -->

2022-01-10 23:14 UTC, robinsons requested changes
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/413)* status: all files reviewed, 4 unresolved discussions (waiting on @chipingyeh, @robinsons, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/EventGroups.kt, line 24 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/413#-Mt5Cgx04d9W2HslFNaX:-Mt5Cgx04d9W2HslFNaY:b-rnad5j) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e29fcd789bd3591876478131c2cbc33c6e537e16/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/EventGroups.kt#L24)):*
> ```Kotlin
> import org.wfanet.measurement.kingdom.deploy.gcloud.spanner.readers.CertificateReader
> 
> suspend fun checkValidCertificate(
> ```

nit: Now that this is in its own class, as opposed to a private function, I would add a short comment. Just something like "Checks that a given Measurement Consumer certificate exists and is valid, and returns its ID if so."
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/UpdateEventGroup.kt, line 51 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/413#-Mt5EAVA2dxPixajcX9t:-Mt5EAVA2dxPixajcX9u:b-klq6fy) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e29fcd789bd3591876478131c2cbc33c6e537e16/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/UpdateEventGroup.kt#L51)):*
> ```Kotlin
>           ?.value
>       else null
>     val providedEventGroupId = eventGroup.providedEventGroupId ?: null
> ```

Protobuf fields are never null, so the `?:` operator doesn't have an effect here. I think we want something like

```kotlin
val providedEventGroupId =
  if (eventGroup.providedEventGroupId.isNotBlank()) {
    eventGroup.providedEventGroupId
  } else null
```

Then, in the mutation building logic, we don't need an if-statement. The idea is that we *want* to set the column to `NULL` if the `eventGroup.providedEventGroupId` is an empty string (rather than setting the column to empty string, which could be taken to have a different meaning).


<!-- Sent from Reviewable.io -->

2022-01-11 15:45 UTC, chipingyeh reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/413)* status: 14 of 16 files reviewed, 4 unresolved discussions (waiting on @robinsons and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/EventGroups.kt, line 24 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/413#-Mt5Cgx04d9W2HslFNaX:-Mt8iPg1CS3rZT9-vDPW:b-aciigy) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e29fcd789bd3591876478131c2cbc33c6e537e16/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/EventGroups.kt#L24)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

nit: Now that this is in its own class, as opposed to a private function, I would add a short comment. Just something like "Checks that a given Measurement Consumer certificate exists and is valid, and returns its ID if so."
</blockquote></details>

Updated with a comment.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/UpdateEventGroup.kt, line 51 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/413#-Mt5EAVA2dxPixajcX9t:-Mt8j70q1oBjh0hrA6vs:b3b1n67) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e29fcd789bd3591876478131c2cbc33c6e537e16/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/UpdateEventGroup.kt#L51)):*
> if (eventGroup.providedEventGroupId.isNotBlank()) {
>     eventGroup.providedEventGroupId
>   } else null
Good call, thanks -- done.


<!-- Sent from Reviewable.io -->

2022-01-11 16:54 UTC, robinsons approved these changes
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/413)* status: all files reviewed, 2 unresolved discussions (waiting on @stevenwarejones and @throws)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/EventGroups.kt, line 24 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/413#-Mt5Cgx04d9W2HslFNaX:-Mt92gM982SKU4hLYQtv:b-djxuoy) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e29fcd789bd3591876478131c2cbc33c6e537e16/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/EventGroups.kt#L24)):*
<details><summary><i>Previously, chipingyeh wrote…</i></summary><blockquote>

Updated with a comment.
</blockquote></details>

Please move the @throws to its own line within the comment.


<!-- Sent from Reviewable.io -->

2022-01-11 18:27 UTC, stevenwarejones requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/413)* status: all files reviewed, 2 unresolved discussions (waiting on @chipingyeh and @throws)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/UpdateEventGroup.kt, line 39 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/413#-Mt4j6_DCIz_jXu4cnvK:-Mt9O79S7WBa1mlMuwVG:b-2m29yx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/35b0521dcfe6fb9931da3b532139513e3c6cf1d8/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/UpdateEventGroup.kt#L39)):*
<details><summary><i>Previously, chipingyeh wrote…</i></summary><blockquote>

This is from the list from the [KingdomInternalException](https://sourcegraph.com/github.com/world-federation-of-advertisers/cross-media-measurement/-/blob/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/common/KingdomInternalException.kt?L17:7) class, and we added a new code for this type of error.
</blockquote></details>

Thats not what I meant. I meant possibly just rename it to EVENT_GROUP_INVALID_ARGS


<!-- Sent from Reviewable.io -->

2022-01-11 19:05 UTC, chipingyeh reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/413)* status: 4 of 16 files reviewed, 1 unresolved discussion (waiting on @robinsons and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/EventGroups.kt, line 24 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/413#-Mt5Cgx04d9W2HslFNaX:-Mt9WhWj78mIyBzcNLQO:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e29fcd789bd3591876478131c2cbc33c6e537e16/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/EventGroups.kt#L24)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

Please move the @throws to its own line within the comment.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/UpdateEventGroup.kt, line 39 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/413#-Mt4j6_DCIz_jXu4cnvK:-Mt9WoDpAq8lNtrDnqxT:bfd234u) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/35b0521dcfe6fb9931da3b532139513e3c6cf1d8/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/UpdateEventGroup.kt#L39)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

Thats not what I meant. I meant possibly just rename it to EVENT_GROUP_INVALID_ARGS
</blockquote></details>

I don't mind either way -- renamed.


<!-- Sent from Reviewable.io -->

2022-01-11 19:09 UTC, robinsons approved these changes
> Reviewed 12 of 12 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/413)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)



<!-- Sent from Reviewable.io -->

2022-01-11 21:49 UTC, stevenwarejones requested changes
> Reviewed 1 of 7 files at r4, 1 of 3 files at r5, 11 of 12 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/413)* status: all files reviewed, 1 unresolved discussion (waiting on @chipingyeh)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/UpdateEventGroup.kt, line 39 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/413#-Mt4j6_DCIz_jXu4cnvK:-MtA6SZX9VVfvv3PqjRT:b-ms3mqg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/35b0521dcfe6fb9931da3b532139513e3c6cf1d8/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/UpdateEventGroup.kt#L39)):*
<details><summary><i>Previously, chipingyeh wrote…</i></summary><blockquote>

I don't mind either way -- renamed.
</blockquote></details>

I think you forgot to update this one


<!-- Sent from Reviewable.io -->

2022-01-11 22:59 UTC, stevenwarejones approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/413)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @chipingyeh)



<!-- Sent from Reviewable.io -->

2022-01-11 23:16 UTC, merged