Add authorization to event groups, requisitions, and certificates service.
world-federation-of-advertisers/cross-media-measurement pull request #417
Opened 2022-01-12 18:54 UTC by tristanvuong2021

2022-01-12 19:34 UTC, wangyaopw requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/417)* status: 0 of 31 files reviewed, 5 unresolved discussions (waiting on @tristanvuong2021 and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/integration/common/InProcessEdpSimulator.kt, line 58 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/417#-MtEkEE99Q0nrJyze0JF:-MtEkEE99Q0nrJyze0JG:b-6ptlyf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b16aaefe799aca0f7a6ece958c6abdc9e85b45e5/src/main/kotlin/org/wfanet/measurement/integration/common/InProcessEdpSimulator.kt#L58)):*
> ```Kotlin
>   private lateinit var edpName: String
> 
>   fun start(edpName: String, mcName: String, apiAuthenticationKey: String) {
> ```

EDP uses mTLS. No ApiKey is needed for in the EdpSimulator.



_Code quote:_
```Kotlin
, apiAuthenticationKey
```
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/CertificatesService.kt, line 70 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/417#-MtElAx-2zidhgxadVEw:-MtElAx-2zidhgxadVEx:bokem9r) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b16aaefe799aca0f7a6ece958c6abdc9e85b45e5/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/CertificatesService.kt#L70)):*
> ```Kotlin
> 
>           val measurementConsumer =
>             ApiKeyConstants.CONTEXT_MEASUREMENT_CONSUMER_KEY.get()
> ```

GetCertificate can be called by EDP, duchy or MC. Only the calls from MC use ApiKey.

EDP and duchy can also call to get a MC's certificate.



_Code quote:_
```Kotlin
  ApiKeyConstants.CONTEXT_MEASUREMENT_CONSUME
```
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt, line 103 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/417#-MtElbFJ7QUI1GwWfmax:-MtElbFJ7QUI1GwWfmay:b-5ysmev) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b16aaefe799aca0f7a6ece958c6abdc9e85b45e5/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt#L103)):*
> ```Kotlin
>     val listEventGroupsPageToken = request.toListEventGroupPageToken()
> 
>     val measurementConsumer =
> ```

same here.

EDP can call listEventGroups, and no ApiKey is used for these calls.



_Code quote:_
```Kotlin
val measurementConsumer =
```
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt, line 79 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/417#-MtEm9-x6ESoUKYW7-BD:-MtEm9-x6ESoUKYW7-BE:b-9ls3uo) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b16aaefe799aca0f7a6ece958c6abdc9e85b45e5/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt#L79)):*
> ```Kotlin
>     request: ListRequisitionsRequest
>   ): ListRequisitionsResponse {
>     val measurementConsumer =
> ```

same here.

EDPs also call listRequisition
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementConsumersService.kt, line 94 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/417#-MtElmXHBMdSRaH7ItFA:-MtElmXHBMdSRaH7ItFB:bohgs4x) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b16aaefe799aca0f7a6ece958c6abdc9e85b45e5/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementConsumersService.kt#L94)):*
> ```Kotlin
>     request: GetMeasurementConsumerRequest
>   ): MeasurementConsumer {
>     val measurementConsumer =
> ```

Same here, EDP can also call getMeasurementConsumer.



_Code quote:_
```Kotlin
al measurementConsumer =
```


<!-- Sent from Reviewable.io -->

2022-01-18 17:08 UTC, tristanvuong2021 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/417)* status: 0 of 53 files reviewed, 5 unresolved discussions (waiting on @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/CertificatesService.kt, line 70 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/417#-MtElAx-2zidhgxadVEw:-Mti9Omq12nBiWd8LunR:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b16aaefe799aca0f7a6ece958c6abdc9e85b45e5/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/CertificatesService.kt#L70)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

GetCertificate can be called by EDP, duchy or MC. Only the calls from MC use ApiKey.

EDP and duchy can also call to get a MC's certificate.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt, line 103 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/417#-MtElbFJ7QUI1GwWfmax:-Mti98xqE6jPHW4tkax9:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b16aaefe799aca0f7a6ece958c6abdc9e85b45e5/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt#L103)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

same here.

EDP can call listEventGroups, and no ApiKey is used for these calls.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementConsumersService.kt, line 94 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/417#-MtElmXHBMdSRaH7ItFA:-Mti99s-8gCTLrP-IlVw:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b16aaefe799aca0f7a6ece958c6abdc9e85b45e5/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementConsumersService.kt#L94)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

Same here, EDP can also call getMeasurementConsumer.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt, line 79 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/417#-MtEm9-x6ESoUKYW7-BD:-Mti9BQw6Gp_lmGHapts:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b16aaefe799aca0f7a6ece958c6abdc9e85b45e5/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/RequisitionsService.kt#L79)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

same here.

EDPs also call listRequisition
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/integration/common/InProcessEdpSimulator.kt, line 58 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/417#-MtEkEE99Q0nrJyze0JF:-Mti9D1oBLF-r31Hdenz:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b16aaefe799aca0f7a6ece958c6abdc9e85b45e5/src/main/kotlin/org/wfanet/measurement/integration/common/InProcessEdpSimulator.kt#L58)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

EDP uses mTLS. No ApiKey is needed for in the EdpSimulator.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-24 21:18 UTC, wangyaopw requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/417)* status: 0 of 38 files reviewed, 6 unresolved discussions (waiting on @SanjayVas, @tristanvuong2021, and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/common/identity/DuchyIdentity.kt, line 95 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/417#-MuCwQMx5uqJUGn7TzEE:-MuCwQMx5uqJUGn7TzEF:b-akpydl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/af02ce9237e1c3aa65751894f630c544dd674700/src/main/kotlin/org/wfanet/measurement/common/identity/DuchyIdentity.kt#L95)):*
> ```Kotlin
>         Context.current()
>           .withValue(DUCHY_IDENTITY_CONTEXT_KEY, DuchyIdentity(duchyInfo.duchyId))
>           .withValue(PRINCIPAL_CONTEXT_KEY, Principal.Duchy(DuchyKey(duchyInfo.duchyId)))
> ```

This is just a duplication of `DUCHY_IDENTITY_CONTEXT_KEY`, they serve the same purpose.

I don't think we need to add duchy as another principal. Duchy only calls the system API, and the authentication is already taken care. 

Your changes only apply to the public API. EDP, MP, MC are the ones calling it.

In other words, this PR shouldn't need to touch any duchy related code.



_Code quote:_
```Kotlin
PRINCIPAL_CONTEXT_KEY
```


<!-- Sent from Reviewable.io -->

2022-01-24 21:57 UTC, tristanvuong2021 commented
___
*[src/main/kotlin/org/wfanet/measurement/common/identity/DuchyIdentity.kt, line 95 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/417#-MuCwQMx5uqJUGn7TzEE:-MuD4Pko4GJtCgqe_vqd:bx2d6mu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/af02ce9237e1c3aa65751894f630c544dd674700/src/main/kotlin/org/wfanet/measurement/common/identity/DuchyIdentity.kt#L95)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

This is just a duplication of `DUCHY_IDENTITY_CONTEXT_KEY`, they serve the same purpose.

I don't think we need to add duchy as another principal. Duchy only calls the system API, and the authentication is already taken care. 

Your changes only apply to the public API. EDP, MP, MC are the ones calling it.

In other words, this PR shouldn't need to touch any duchy related code.
</blockquote></details>

Duchy certificate creation is required through. ResourceSetup even has createDuchyCertificate that uses the public API.


<!-- Sent from Reviewable.io -->

2022-01-24 22:56 UTC, wangyaopw requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/417)* status: 0 of 38 files reviewed, 6 unresolved discussions (waiting on @SanjayVas, @tristanvuong2021, and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/common/identity/DuchyIdentity.kt, line 95 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/417#-MuCwQMx5uqJUGn7TzEE:-MuDH7_j-Ok3mSdHetWo:bi2hal9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/af02ce9237e1c3aa65751894f630c544dd674700/src/main/kotlin/org/wfanet/measurement/common/identity/DuchyIdentity.kt#L95)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Duchy certificate creation is required through. ResourceSetup even has createDuchyCertificate that uses the public API.
</blockquote></details>

oh, well. that is right.

In that case, why not just using the existing `DUCHY_IDENTITY_CONTEXT_KEY` to check if the caller is a duchy?


<!-- Sent from Reviewable.io -->

2022-01-24 23:09 UTC, SanjayVas requested changes
> Reviewed 38 of 38 files at r3, 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/417)* status: all files reviewed, 8 unresolved discussions (waiting on @tristanvuong2021 and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/CertificatesService.kt, line 70 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/417#-MtElAx-2zidhgxadVEw:-MuD9s-j4-NApGIQaC9R:b-cuyh7f) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b16aaefe799aca0f7a6ece958c6abdc9e85b45e5/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/CertificatesService.kt#L70)):*
> EDP and duchy can also call to get a MC's certificate.

@wangyaopw Why/how would Duchy get MC's certificate? They intentionally don't know the MC ID.
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/CertificatesService.kt, line 111 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/417#-MuDAMNCDJomvsaPdVUw:-MuDAMNCDJomvsaPdVUx:b-efljm2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/af02ce9237e1c3aa65751894f630c544dd674700/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/CertificatesService.kt#L111)):*
> ```Kotlin
> 
>           when (principal.resourceKey) {
>             is ModelProviderKey -> {}
> ```

Did you confirm this with Eli? Just any MP should be able to get an MP cert, and nobody else can?
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt, line 164 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/417#-MuDFKLcDQQhHVUDWzbI:-MuDFKLcDQQhHVUDWzbJ:b-7fy3rh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/af02ce9237e1c3aa65751894f630c544dd674700/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt#L164)):*
> ```Kotlin
>       is MeasurementConsumerKey -> {
>         val externalMeasurementConsumerId = apiIdToExternalId(resourceKey.measurementConsumerId)
>         if (listEventGroupsPageToken.externalMeasurementConsumerIdsList.isNotEmpty()) {
> ```

MC can only list their own EventGroups, meaning MC *must* have this filter set. (We can't just check the MC in the returned event group as that otherwise potentially gives the MC information about other MCs)


<!-- Sent from Reviewable.io -->

2022-01-24 23:09 UTC, wangyaopw reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/417)* status: all files reviewed, 7 unresolved discussions (waiting on @tristanvuong2021 and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/common/identity/DuchyIdentity.kt, line 95 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/417#-MuCwQMx5uqJUGn7TzEE:-MuDL0uq98jTQn4-Ws1z:bniquch) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/af02ce9237e1c3aa65751894f630c544dd674700/src/main/kotlin/org/wfanet/measurement/common/identity/DuchyIdentity.kt#L95)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

oh, well. that is right.

In that case, why not just using the existing `DUCHY_IDENTITY_CONTEXT_KEY` to check if the caller is a duchy?
</blockquote></details>

ok. So I guess my suggestion is don't touch the DuchyIdentity class.

If the duchy is calling the public API, then, it is just a principal. In that case, it should set its identity using`withPrincipal` like how EDP does.


<!-- Sent from Reviewable.io -->

2022-01-25 00:09 UTC, tristanvuong2021 commented
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/CertificatesService.kt, line 111 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/417#-MuDAMNCDJomvsaPdVUw:-MuDZ5kdDXFXdI_Faow4:b-pape9s) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/af02ce9237e1c3aa65751894f630c544dd674700/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/CertificatesService.kt#L111)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Did you confirm this with Eli? Just any MP should be able to get an MP cert, and nobody else can?
</blockquote></details>

Fixed. Asked Eli about model provider here.


<!-- Sent from Reviewable.io -->

2022-01-25 00:09 UTC, tristanvuong2021 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/417)* status: 34 of 38 files reviewed, 7 unresolved discussions (waiting on @SanjayVas and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt, line 164 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/417#-MuDFKLcDQQhHVUDWzbI:-MuDZCiU95RM4HuefhbA:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/af02ce9237e1c3aa65751894f630c544dd674700/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt#L164)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

MC can only list their own EventGroups, meaning MC *must* have this filter set. (We can't just check the MC in the returned event group as that otherwise potentially gives the MC information about other MCs)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-25 00:17 UTC, SanjayVas requested changes
> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/417)* status: all files reviewed, 6 unresolved discussions (waiting on @tristanvuong2021 and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/CertificatesService.kt, line 108 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/417#-MuD_JRR0VTdZjzT6_a0:-MuD_JRR0VTdZjzT6_a1:b-r1vjcu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/13904faadf51c4f2feb80e2a7cfd6bbd95c475a9/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/CertificatesService.kt#L108)):*
> ```Kotlin
>         }
>         is ModelProviderCertificateKey ->
>           externalModelProviderId = apiIdToExternalId(key.modelProviderId)
> ```

What's this used for?



_Code quote:_
```Kotlin
          externalModelProviderId = apiIdToExternalId(key.modelProviderId)
```


<!-- Sent from Reviewable.io -->

2022-01-25 00:23 UTC, tristanvuong2021 commented
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/CertificatesService.kt, line 108 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/417#-MuD_JRR0VTdZjzT6_a0:-MuDbO31BEKbTRHsJayv:bchz2oe) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/13904faadf51c4f2feb80e2a7cfd6bbd95c475a9/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/CertificatesService.kt#L108)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

What's this used for?
</blockquote></details>

The whole when block is inside a builder for the internal request.


<!-- Sent from Reviewable.io -->

2022-01-25 00:33 UTC, wangyaopw reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/417)* status: all files reviewed, 5 unresolved discussions (waiting on @SanjayVas, @tristanvuong2021, and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/CertificatesService.kt, line 70 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/417#-MtElAx-2zidhgxadVEw:-MuDd1727a-bjp9S5qDw:b-u7q1up) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b16aaefe799aca0f7a6ece958c6abdc9e85b45e5/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/CertificatesService.kt#L70)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> EDP and duchy can also call to get a MC's certificate.

@wangyaopw Why/how would Duchy get MC's certificate? They intentionally don't know the MC ID.
</blockquote></details>

Well, I guess I shouldn't include Duchy in my comment. 

My point was Duchy can also call this service, for example, createCertificate for itself.


<!-- Sent from Reviewable.io -->

2022-01-25 00:35 UTC, tristanvuong2021 commented
___
*[src/main/kotlin/org/wfanet/measurement/common/identity/DuchyIdentity.kt, line 95 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/417#-MuCwQMx5uqJUGn7TzEE:-MuDcNLB1GiMUZCFIo7Y:bcsmldh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/af02ce9237e1c3aa65751894f630c544dd674700/src/main/kotlin/org/wfanet/measurement/common/identity/DuchyIdentity.kt#L95)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

ok. So I guess my suggestion is don't touch the DuchyIdentity class.

If the duchy is calling the public API, then, it is just a principal. In that case, it should set its identity using`withPrincipal` like how EDP does.
</blockquote></details>

I can remove the changes to the metaduchy interceptor because it is true I don't need to change that, but isn't the principal mapping file not for duchy? I could either keep the DuchyIdentity as is or copy the way DuchyIdentity checks the authority key identifiers to the principal server interceptor so the principal server interceptor could check both the mapping file as well as the duchy info config.


<!-- Sent from Reviewable.io -->

2022-01-25 01:16 UTC, tristanvuong2021 commented
___
*[src/main/kotlin/org/wfanet/measurement/common/identity/DuchyIdentity.kt, line 95 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/417#-MuCwQMx5uqJUGn7TzEE:-MuDel0vELIk5TGxeq1H:b-ze9yu5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/af02ce9237e1c3aa65751894f630c544dd674700/src/main/kotlin/org/wfanet/measurement/common/identity/DuchyIdentity.kt#L95)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

I can remove the changes to the metaduchy interceptor because it is true I don't need to change that, but isn't the principal mapping file not for duchy? I could either keep the DuchyIdentity as is or copy the way DuchyIdentity checks the authority key identifiers to the principal server interceptor so the principal server interceptor could check both the mapping file as well as the duchy info config.
</blockquote></details>

@wangyaopw Went with undoing DuchyIdentity and adding a duchy principal check to the PrincipalServerInterceptor.


<!-- Sent from Reviewable.io -->

2022-01-25 18:54 UTC, SanjayVas approved these changes
> Reviewed 8 of 8 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/417)* status: all files reviewed, 6 unresolved discussions (waiting on @stevenwarejones, @tristanvuong2021, and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/api/v2alpha/BUILD.bazel, line 45 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/417#-MuHX_bWAWQ-TgV7HG9J:-MuHX_bWAWQ-TgV7HG9K:bicm5ch) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c624134f5b16df264f5a28dd27c2996ac4249bab/src/main/kotlin/org/wfanet/measurement/api/v2alpha/BUILD.bazel#L45)):*
> ```Starlark
>         "//src/main/kotlin/org/wfanet/measurement/common/identity",
>         "//src/main/proto/wfa/measurement/api/v2alpha:duchy_java_proto",
>         "//src/main/proto/wfa/measurement/api/v2alpha:model_provider_java_proto",
> ```

Switch these to use the kt_jvm_proto instead of java_proto so we can use Kotlin DSL builders for them.
___
*[src/main/kotlin/org/wfanet/measurement/api/v2alpha/PrincipalServerInterceptor.kt, line 93 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/417#-MuH_C1l0F4NFV5WzCrj:-MuH_C1l0F4NFV5WzCrk:b-63ee26) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c624134f5b16df264f5a28dd27c2996ac4249bab/src/main/kotlin/org/wfanet/measurement/api/v2alpha/PrincipalServerInterceptor.kt#L93)):*
> ```Kotlin
>  * gRPC [ServerInterceptor] to extract a [Principal] from a request.
>  *
>  * Currently, this only supports deriving the [Principal] from an X509 cert's authority key
> ```

nit: verify whether the KDoc for this is still accurate and make any necessary changes
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/CertificatesService.kt, line 108 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/417#-MuD_JRR0VTdZjzT6_a0:-MuH_Xko-vS6aH-2wZk5:b-uk9ni) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/13904faadf51c4f2feb80e2a7cfd6bbd95c475a9/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/CertificatesService.kt#L108)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

The whole when block is inside a builder for the internal request.
</blockquote></details>

Oh, didn't spot that. Thanks for the clarification.


<!-- Sent from Reviewable.io -->

2022-01-26 15:11 UTC, tristanvuong2021 commented
___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/CertificatesService.kt, line 70 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/417#-MtElAx-2zidhgxadVEw:-MuLwAu519vG_pCK8sGY:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b16aaefe799aca0f7a6ece958c6abdc9e85b45e5/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/CertificatesService.kt#L70)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

Well, I guess I shouldn't include Duchy in my comment. 

My point was Duchy can also call this service, for example, createCertificate for itself.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-26 20:32 UTC, tristanvuong2021 reviewed
> Dismissed @wangyaopw from 4 discussions.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/417)* status: 37 of 41 files reviewed, all discussions resolved (waiting on @SanjayVas, @stevenwarejones, and @wangyaopw)



<!-- Sent from Reviewable.io -->

2022-01-26 21:30 UTC, wangyaopw requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/417)* status: 37 of 41 files reviewed, 2 unresolved discussions (waiting on @SanjayVas, @stevenwarejones, and @tristanvuong2021)

___
*[src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt, line 109 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/417#-MuNH-Jc0G5aFXnkqc47:-MuNH-Jc0G5aFXnkqc48:b-i3ztqz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c093bbb75128bb9e70f1303f2ebb283db00a8ace/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L109)):*
> ```Kotlin
>     val eventGroup =
>       eventGroupsStub
>         .withPrincipalName(edpData.name)
> ```

We shouldn't need this.

The publicApi should get principal for this EDP from the TLS certificate.

In otherwise, we don't want the EDP to claim who it is.

@sanjayvas is this true?



_Code quote:_
```Kotlin
.withPrincipalName(edpData.name)
```
___
*[src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetup.kt, line 187 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/417#-MuNHP7U-KDEJY312xQc:-MuNHP7U-KDEJY312xQd:brdcss6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c093bbb75128bb9e70f1303f2ebb283db00a8ace/src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetup.kt#L187)):*
> ```Kotlin
>       certificate = certificate { x509Der = duchyCert.consentSignalCertificateDer }
>     }
>     return certificatesClient.withPrincipalName(name).createCertificate(request)
> ```

This is fine for now. Add a TODO to create duchyCertificate via the internal API. I'll clean this up after this PR is in.

this resourceSetupJob doesn't run as the duchies, and shouldn't be identified as the duchies.


<!-- Sent from Reviewable.io -->

2022-01-26 22:10 UTC, tristanvuong2021 commented
___
*[src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt, line 109 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/417#-MuNH-Jc0G5aFXnkqc47:-MuNQv_f7yFfRN2VHH2u:bgtrf3b) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c093bbb75128bb9e70f1303f2ebb283db00a8ace/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L109)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

We shouldn't need this.

The publicApi should get principal for this EDP from the TLS certificate.

In otherwise, we don't want the EDP to claim who it is.

@sanjayvas is this true?
</blockquote></details>

InProcessLifeOfAMeasurementIntegrationTest requires this, which uses metadata instead of the cert.


<!-- Sent from Reviewable.io -->

2022-01-26 22:11 UTC, SanjayVas reviewed
> Reviewed 2 of 2 files at r7, 1 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/417)* status: 40 of 41 files reviewed, 2 unresolved discussions (waiting on @SanjayVas, @stevenwarejones, @tristanvuong2021, and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt, line 109 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/417#-MuNH-Jc0G5aFXnkqc47:-MuNQFr01olhgGaDNB6P:b-uc0qog) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c093bbb75128bb9e70f1303f2ebb283db00a8ace/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L109)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

InProcessLifeOfAMeasurementIntegrationTest requires this, which uses metadata instead of the cert.
</blockquote></details>

Correct. We should only be using `withPrincipalName` in tests where we can't set up mTLS. For this one, I believe we do indeed specify the client cert, correct? Then all that matters is that the right AKID<->EDP name mapping exists.


<!-- Sent from Reviewable.io -->

2022-01-26 22:28 UTC, tristanvuong2021 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/417)* status: 39 of 41 files reviewed, 2 unresolved discussions (waiting on @SanjayVas, @stevenwarejones, and @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetup.kt, line 187 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/417#-MuNHP7U-KDEJY312xQc:-MuNVARVAztiHcuD5bgC:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c093bbb75128bb9e70f1303f2ebb283db00a8ace/src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetup.kt#L187)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

This is fine for now. Add a TODO to create duchyCertificate via the internal API. I'll clean this up after this PR is in.

this resourceSetupJob doesn't run as the duchies, and shouldn't be identified as the duchies.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-26 22:33 UTC, wangyaopw approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/417)* status: 39 of 41 files reviewed, 1 unresolved discussion (waiting on @SanjayVas, @stevenwarejones, and @tristanvuong2021)

___
*[src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt, line 109 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/417#-MuNH-Jc0G5aFXnkqc47:-MuNVkdY9HYbTXc1qpW6:b-uydi67) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c093bbb75128bb9e70f1303f2ebb283db00a8ace/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L109)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Correct. We should only be using `withPrincipalName` in tests where we can't set up mTLS. For this one, I believe we do indeed specify the client cert, correct? Then all that matters is that the right AKID<->EDP name mapping exists.
</blockquote></details>

If InProcessLifeOfAMeasurementIntegrationTest need this. we need to add it somewhere in the InProcessEdpSimulator.

You can add a TODO above line 109 here to get rid of it 


<!-- Sent from Reviewable.io -->

2022-01-26 22:44 UTC, tristanvuong2021 commented
___
*[src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt, line 109 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/417#-MuNH-Jc0G5aFXnkqc47:-MuNYzID65_-8G6YJvil:bb3qaoy) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c093bbb75128bb9e70f1303f2ebb283db00a8ace/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L109)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

If InProcessLifeOfAMeasurementIntegrationTest need this. we need to add it somewhere in the InProcessEdpSimulator.

You can add a TODO above line 109 here to get rid of it 
</blockquote></details>

@wangyaopw I actually realized there is an easy way to fix this.


<!-- Sent from Reviewable.io -->

2022-01-27 00:59 UTC, stevenwarejones approved these changes
> Reviewed 8 of 38 files at r3, 2 of 4 files at r5, 4 of 8 files at r6, 2 of 2 files at r7, 2 of 2 files at r8, 1 of 1 files at r9, 3 of 3 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/417)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)



<!-- Sent from Reviewable.io -->

2022-01-27 01:09 UTC, merged