Promote ExchangeStep to a table and internal entity type.
world-federation-of-advertisers/cross-media-measurement pull request #42
Opened 2021-04-29 21:00 UTC by efoxepstein

Previously, the plan was to just infer ExchangeSteps, but it seems
simpler and more performant to just explicitly represent them.

2021-04-30 01:06 UTC, yunyeng commented on src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/kingdom.sdl
>  CREATE TABLE ExchangeStepAttempts (
Do we not have to store ExchangeStepAttempt.State in the table?

2021-04-30 01:07 UTC, yunyeng commented on src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/kingdom.sdl
>    Date                 DATE NOT NULL,
Why Date not Timestamp ? I am assuming there will be multiple attempts in the same date.

2021-04-30 23:05 UTC, yunyeng approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/42)* status: 0 of 6 files reviewed, all discussions resolved (waiting on @stevenwarejones)



<!-- Sent from Reviewable.io -->

2021-05-03 19:58 UTC, stevenwarejones requested changes
> Reviewed 5 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/42)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @efoxepstein)

___
*[src/main/proto/wfa/measurement/internal/kingdom/exchange_step_attempt.proto, line 60 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/42#-MZnn7A9AmoQjOuhpCB5:-MZnn7A9AmoQjOuhpCB6:b-5j98oz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/28d290e715c3f0e8f9ac723c187882457d863078/src/main/proto/wfa/measurement/internal/kingdom/exchange_step_attempt.proto#L60)):*
> ```protobuf
>     TEMPORARILY_FAILED = 3;
> 
>     // The attempt has failed permanently and the step should not be retried.
> ```

what do you think instead to call it `UP_FOR_RETRY` .... `TEMPORARILY FAILED` does seem to actively communicate what I think you want it to communicate.
___
*[src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepAttemptsServiceTest.kt, line 233 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/42#-MZnnSh0Amf7J8b3CVXN:-MZnnSh0Amf7J8b3CVXO:bz5dy87) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/28d290e715c3f0e8f9ac723c187882457d863078/src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepAttemptsServiceTest.kt#L233)):*
> ```Kotlin
>             stepIndex = STEP_INDEX
>             attemptNumber = ATTEMPT_NUMBER
>             state = InternalExchangeStepAttempt.State.TEMPORARILY_FAILED
> ```

see other comment about `TEMPORARILY FAILED`


<!-- Sent from Reviewable.io -->

2021-05-03 20:22 UTC, efoxepstein reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/42)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @stevenwarejones)

___
*[src/main/proto/wfa/measurement/internal/kingdom/exchange_step_attempt.proto, line 60 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/42#-MZnn7A9AmoQjOuhpCB5:-MZnsuCE3A6uuyLBewA-:b6h4rxl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/28d290e715c3f0e8f9ac723c187882457d863078/src/main/proto/wfa/measurement/internal/kingdom/exchange_step_attempt.proto#L60)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

what do you think instead to call it `UP_FOR_RETRY` .... `TEMPORARILY FAILED` does seem to actively communicate what I think you want it to communicate.
</blockquote></details>

To be consistent with github.com/world-federation-of-advertisers/cross-media-measurement-api/pull/21, I'll change this to FAILED and FAILED_STEP. Sound good?
___
*[src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepAttemptsServiceTest.kt, line 233 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/42#-MZnnSh0Amf7J8b3CVXN:-MZntMME44EYcGDbunOI:bsjte78) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/28d290e715c3f0e8f9ac723c187882457d863078/src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepAttemptsServiceTest.kt#L233)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

see other comment about `TEMPORARILY FAILED`
</blockquote></details>

See above comment.


<!-- Sent from Reviewable.io -->

2021-05-03 21:37 UTC, stevenwarejones approved these changes
> Reviewed 1 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/42)* status: 3 of 6 files reviewed, 1 unresolved discussion (waiting on @efoxepstein and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepAttemptsService.kt, line 163 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/42#-MZo9ITr9heeInHCQZO0:-MZo9ITr9heeInHCQZO1:b-o4vjjv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dca3445b228e5fafe46c30eca18ebe485e8718c3/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ExchangeStepAttemptsService.kt#L163)):*
> ```Kotlin
>     // TODO: update public API version to support new [ExchangeStepAttempt] states.
>     InternalExchangeStepAttempt.State.FAILED -> ExchangeStepAttempt.State.FAILED
>     InternalExchangeStepAttempt.State.FAILED_STEP -> ExchangeStepAttempt.State.FAILED
> ```

i like this better


<!-- Sent from Reviewable.io -->

2021-05-03 21:42 UTC, merged