Add Correctness Test Labeled Event proto.
world-federation-of-advertisers/cross-media-measurement pull request #43
Opened 2021-05-01 16:27 UTC by yunyeng

2021-05-03 08:22 UTC, wangyaopw requested changes
I don't think we need such details in the correctnessTest.

The big query or whatever query would generate a list of VID for each EDP. The input to the correctness test would be these VID lists. The query language doesn't need the proto definition I think.

2021-05-03 18:35 UTC, kungfucraig reviewed
This is the schema for the big query table. When we parse the CSV we can use the proto to ensure that the values in the column conform to the set of enum values in the schema. This will prevent problems.

Maybe this is not the right place to put this?

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/43#-:-MZnVdHACH--Y6g2Ws7a:b-xv94xb)* status: 0 of 2 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2021-05-05 18:04 UTC, wangyaopw approved these changes

2021-05-05 18:04 UTC, wangyaopw commented on src/main/proto/wfa/measurement/internal/loadtest/labeled_event.proto
> +  google.type.Date date = 8;
does the sheet have this column?

2021-05-05 18:05 UTC, yunyeng commented on src/main/proto/wfa/measurement/internal/loadtest/labeled_event.proto
> +  google.type.Date date = 8;
Yes

2021-05-05 18:08 UTC, wangyaopw commented on src/main/proto/wfa/measurement/internal/loadtest/labeled_event.proto
> +  enum Sex {
{sex, age, social grad} is only used inside the sheet to get the query parameters. The data in the sheet only contains the integer demographics. In the query we will also use the integer values. So it seems that there is no need to parse the integers back to {sex, age, social grad}

2021-05-05 18:12 UTC, wangyaopw commented on src/main/proto/wfa/measurement/internal/loadtest/labeled_event.proto
> +  enum Sex {
nvw, I see the updated sheet now.

2021-05-05 18:16 UTC, yunyeng reviewed
Directory should be ok. There is already another proto in the same place that CorrectnessTest uses for output.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/43#-:-MZxipE75M_ayEfN6Qip:b-sujhb6)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @wangyaopw and @yunyeng)



<!-- Sent from Reviewable.io -->

2021-05-05 18:22 UTC, kungfucraig requested changes

2021-05-05 18:22 UTC, kungfucraig commented on src/main/proto/wfa/measurement/internal/loadtest/labeled_event.proto
> +  enum Sex {
Please use SEX_UNSPECIFIED = 0 and then add the other two.

2021-05-05 18:22 UTC, kungfucraig commented on src/main/proto/wfa/measurement/internal/loadtest/labeled_event.proto
> +    // Ages between 18 to 34 inclusive.
Same here. AGE_GROUP_UNSPECIFIED = 0

2021-05-05 18:22 UTC, kungfucraig commented on src/main/proto/wfa/measurement/internal/loadtest/labeled_event.proto
> +  Sex gender = 3;
Either "Sex sex" or rename enum to Gender.

2021-05-05 18:22 UTC, kungfucraig commented on src/main/proto/wfa/measurement/internal/loadtest/labeled_event.proto
> +    ABC1 = 0;
Same SOCIAL_GRADE_UNSPECIFIED

2021-05-05 18:22 UTC, kungfucraig commented on src/main/proto/wfa/measurement/internal/loadtest/labeled_event.proto
> +    INCOMPLETE = 0;
Same

2021-05-05 18:47 UTC, yunyeng reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/43)* status: 0 of 2 files reviewed, 6 unresolved discussions (waiting on @kungfucraig and @wangyaopw)

___
*[src/main/proto/wfa/measurement/internal/loadtest/labeled_event.proto, line 33 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/43#-MZckQ40lbAtYekt3Mw2-r1-33:-MZxqjmC7qxV7lDBHamB:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/47944b6a902ae86b66c29d12d19c558931da81cd/src/main/proto/wfa/measurement/internal/loadtest/labeled_event.proto#L33)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Please use SEX_UNSPECIFIED = 0 and then add the other two.
</blockquote></details>

Done.
___
*[src/main/proto/wfa/measurement/internal/loadtest/labeled_event.proto, line 38 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/43#-MZckQ40lbAtYekt3Mw2-r1-38:-MZxqmnA7yR-ixORdqjY:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/47944b6a902ae86b66c29d12d19c558931da81cd/src/main/proto/wfa/measurement/internal/loadtest/labeled_event.proto#L38)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Either "Sex sex" or rename enum to Gender.
</blockquote></details>

Done.
___
*[src/main/proto/wfa/measurement/internal/loadtest/labeled_event.proto, line 42 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/43#-MZckQ40lbAtYekt3Mw2-r1-42:-MZxqnVy2c5igmfF607M:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/47944b6a902ae86b66c29d12d19c558931da81cd/src/main/proto/wfa/measurement/internal/loadtest/labeled_event.proto#L42)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Same here. AGE_GROUP_UNSPECIFIED = 0
</blockquote></details>

Done.
___
*[src/main/proto/wfa/measurement/internal/loadtest/labeled_event.proto, line 56 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/43#-MZckQ40lbAtYekt3Mw2-r1-56:-MZxqnsl4YEN4MnSYbMA:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/47944b6a902ae86b66c29d12d19c558931da81cd/src/main/proto/wfa/measurement/internal/loadtest/labeled_event.proto#L56)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Same SOCIAL_GRADE_UNSPECIFIED
</blockquote></details>

Done.
___
*[src/main/proto/wfa/measurement/internal/loadtest/labeled_event.proto, line 64 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/43#-MZckQ40lbAtYekt3Mw2-r1-64:-MZxqoFg-xHBOua1FRu3:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/47944b6a902ae86b66c29d12d19c558931da81cd/src/main/proto/wfa/measurement/internal/loadtest/labeled_event.proto#L64)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Same
</blockquote></details>

Done.
___
*[src/main/proto/wfa/measurement/internal/loadtest/labeled_event.proto, line 73 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/43#-MZckQ40lbAtYekt3Mw2-r1-73:-MZxqosO04KtjZFMyQTG:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/47944b6a902ae86b66c29d12d19c558931da81cd/src/main/proto/wfa/measurement/internal/loadtest/labeled_event.proto#L73)):*
<details><summary><i>Previously, yunyeng (Yunus Yen) wrote…</i></summary><blockquote>

Yes
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-05-06 15:10 UTC, kungfucraig approved these changes

2021-05-06 15:10 UTC, merged