Implement EventTemplateTypeRegistry
world-federation-of-advertisers/cross-media-measurement pull request #437
Opened 2022-02-03 23:22 UTC by chipingyeh

2022-02-03 23:30 UTC, chipingyeh commented
*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/437#-Mv0tfJj42CPDW6UA2Wy:-Mv0tfJj42CPDW6UA2Wz:bgispho) (no related file):*
This uses the 3rd party [reflections](https://github.com/ronmamo/reflections) library as the only one I could get to read classes from a package correctly. I also opted to put this code in `cross-media-measurement` for now to maintain the original `common-jvm`'s lack of dependencies on other repos (`cross-media-measurement-api`'s `event_group_annotations` in this case).

---


<!-- Sent from Reviewable.io -->

2022-02-04 15:22 UTC, stevenwarejones requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/437)* status: 0 of 17 files reviewed, 2 unresolved discussions (waiting on @chipingyeh and @robinsons)

___
*[src/main/kotlin/org/wfanet/measurement/api/v2alpha/event_templates/test_video_template.proto, line 32 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/437#-Mv4K2B-57S8HSh_zl-3:-Mv4K2B-57S8HSh_zl-4:b4z0n04) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/15350f4bc3688e974ee8a4c849c5a1f79b3638f3/src/main/kotlin/org/wfanet/measurement/api/v2alpha/event_templates/test_video_template.proto#L32)):*
> ```protobuf
> }
> 
> message TestVideoTemplate {
> ```

shouldn't this go in cross-media-measurement-api?


<!-- Sent from Reviewable.io -->

2022-02-04 22:41 UTC, robinsons requested changes
> Reviewed 2 of 2 files at r2, 1 of 14 files at r3, 1 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/437)* status: 4 of 17 files reviewed, 11 unresolved discussions (waiting on @chipingyeh, @robinsons, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventTemplateTypeRegistry.kt, line 23 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/437#-Mv5lGmR1uXNgKaE0US-:-Mv5lGmR1uXNgKaE0US0:bfrc3qu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/15350f4bc3688e974ee8a4c849c5a1f79b3638f3/src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventTemplateTypeRegistry.kt#L23)):*
> ```Kotlin
> 
> class EventTemplateTypeRegistry(private val packageName: String) {
>   private var templates: Map<String, Descriptor> = mapOf<String, Descriptor>()
> ```

I would recommend using `TypeRegistry` [1] to hold the templates. One key advantage is that as you construct it, it automatically adds to the registry any other messages in the `.proto` file, as well as in any transitively included files. I think this will be useful because templates will have dependencies on field types that are declared in other files, and it's reasonable to imagine that folks may end up using this registry to fetch event field descriptors in addition to template descriptors.

[1] https://developers.google.com/protocol-buffers/docs/reference/java/com/google/protobuf/TypeRegistry
___
*[src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventTemplateTypeRegistry.kt, line 27 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/437#-Mv5kMfY8W9U97MDVyou:-Mv5kMfY8W9U97MDVyov:b-qjr5za) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/15350f4bc3688e974ee8a4c849c5a1f79b3638f3/src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventTemplateTypeRegistry.kt#L27)):*
> ```Kotlin
>   init {
>     loadTemplates()
>   }
> ```

Instead of having non-final state (i.e. `var`), I would recommend using a companion object to construct the `EventTemplateTypeRegistry`. Something like this

```
class EventTemplateTypeRegistry private constructor(private val registry: TypeRegistry) {
  ...

  companion object {
    createRegistryForPackagePrefix(prefix: String): EventTemplateTypeRegistry {
      ...
    }
  }
}
```




_Code quote:_
```Kotlin
  private var templates: Map<String, Descriptor> = mapOf<String, Descriptor>()

  init {
    loadTemplates()
  }
```
___
*[src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventTemplateTypeRegistry.kt, line 35 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/437#-Mv5jv1U5gyuX46vOSCx:-Mv5jv1U5gyuX46vOSCy:b-txp3y3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/15350f4bc3688e974ee8a4c849c5a1f79b3638f3/src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventTemplateTypeRegistry.kt#L35)):*
> ```Kotlin
> 
>   /** Returns the current templates map. */
>   fun getTemplates(): Map<String, Descriptor> {
> ```

IMO the internal registry (currently a map) should be an implementation detail of this class. Could we change this method to be more like

```
fun getDescriptorForType(messageType: String): Descriptor {
  ...
}
```
___
*[src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventTemplateTypeRegistry.kt, line 41 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/437#-Mv5mlpGESCR20zFVORW:-Mv5mlpGESCR20zFVORX:bdjqchz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/15350f4bc3688e974ee8a4c849c5a1f79b3638f3/src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventTemplateTypeRegistry.kt#L41)):*
> ```Kotlin
>   private fun loadTemplates() {
>     val tempMap = mutableMapOf<String, Descriptor>()
>     val reflections = Reflections(packageName, SubTypes.filterResultsBy { true })
> ```

I'm not familiar with `Reflections`: will it include subpackages of `packageName`?

I seem to recall that in our dev connect, you were considering a different approach for this. Did that not pan out in the end?
___
*[src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventTemplateTypeRegistry.kt, line 42 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/437#-Mv5nKvBDTh553ewP-Vw:-Mv5nKvBDTh553ewP-Vx:b-n4xuhc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/15350f4bc3688e974ee8a4c849c5a1f79b3638f3/src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventTemplateTypeRegistry.kt#L42)):*
> ```Kotlin
>     val tempMap = mutableMapOf<String, Descriptor>()
>     val reflections = Reflections(packageName, SubTypes.filterResultsBy { true })
>     val classes: Set<Class<*>> = reflections.getSubTypesOf(Object::class.java)
> ```

We can be a bit more restrictive and use `Message:class.java`, so that we don't end up loading every type in the package.
___
*[src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventTemplateTypeRegistry.kt, line 43 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/437#-Mv5n_xHD8LZL_c1iSlf:-Mv5n_xHD8LZL_c1iSlg:b-k3n9em) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/15350f4bc3688e974ee8a4c849c5a1f79b3638f3/src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventTemplateTypeRegistry.kt#L43)):*
> ```Kotlin
>     val reflections = Reflections(packageName, SubTypes.filterResultsBy { true })
>     val classes: Set<Class<*>> = reflections.getSubTypesOf(Object::class.java)
>     for (c in classes.filter { c -> c.simpleName.endsWith("Template") }) {
> ```

I think we should do this in a way that doesn't rely on assumptions about naming convention.

What we can do instead is get the message descriptor, and then check if its message options has our custom extension. That would look something like this:

```
val descriptor = ... // get descriptor reflectively
val isEventTemplate = descriptor.options.hasExtension(EventAnnotations.eventTemplate)
```
___
*[src/main/kotlin/org/wfanet/measurement/api/v2alpha/event_templates/test_banner_template.proto, line 1 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/437#-Mv5paug5L9HJBuprMSj:-Mv5paug5L9HJBuprMSk:bxff33l) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/15350f4bc3688e974ee8a4c849c5a1f79b3638f3/src/main/kotlin/org/wfanet/measurement/api/v2alpha/event_templates/test_banner_template.proto#L1)):*
> ```protobuf
> // Copyright 2021 The Cross-Media Measurement Authors
> ```

Please put `.proto` files under `src/main/proto/...` instead of `src/main/kotlin/...`.
___
*[src/main/kotlin/org/wfanet/measurement/api/v2alpha/event_templates/test_banner_template.proto, line 21 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/437#-Mv5qKzi24d_WZ6djG8r:-Mv5qKzi24d_WZ6djG8s:b-rmefyy) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/15350f4bc3688e974ee8a4c849c5a1f79b3638f3/src/main/kotlin/org/wfanet/measurement/api/v2alpha/event_templates/test_banner_template.proto#L21)):*
> ```protobuf
> option java_package = "org.wfanet.measurement.api.v2alpha.eventtemplates";
> option java_multiple_files = true;
> import "wfa/measurement/api/v2alpha/event_annotations.proto";
> ```

Imports should come before file options. See https://developers.google.com/protocol-buffers/docs/style#file_structure
___
*[src/main/kotlin/org/wfanet/measurement/api/v2alpha/event_templates/test_video_template.proto, line 26 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/437#-Mv5qklQ7IZa3M9QZ1KX:-Mv5qklQ7IZa3M9QZ1KY:bmh9ji3) ([raw file](https://github.com/world-federation-of-ad [...]

2022-02-09 22:40 UTC, chipingyeh reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/437)* status: 3 of 17 files reviewed, 11 unresolved discussions (waiting on @robinsons and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventTemplateTypeRegistry.kt, line 23 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/437#-Mv5lGmR1uXNgKaE0US-:-MvKwK9z4_6l9T9sbt2E:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/15350f4bc3688e974ee8a4c849c5a1f79b3638f3/src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventTemplateTypeRegistry.kt#L23)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

I would recommend using `TypeRegistry` [1] to hold the templates. One key advantage is that as you construct it, it automatically adds to the registry any other messages in the `.proto` file, as well as in any transitively included files. I think this will be useful because templates will have dependencies on field types that are declared in other files, and it's reasonable to imagine that folks may end up using this registry to fetch event field descriptors in addition to template descriptors.

[1] https://developers.google.com/protocol-buffers/docs/reference/java/com/google/protobuf/TypeRegistry
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventTemplateTypeRegistry.kt, line 27 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/437#-Mv5kMfY8W9U97MDVyou:-MvVPGar6wKy7pZnLWpQ:bw13k6w) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/15350f4bc3688e974ee8a4c849c5a1f79b3638f3/src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventTemplateTypeRegistry.kt#L27)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

Instead of having non-final state (i.e. `var`), I would recommend using a companion object to construct the `EventTemplateTypeRegistry`. Something like this

```
class EventTemplateTypeRegistry private constructor(private val registry: TypeRegistry) {
  ...

  companion object {
    createRegistryForPackagePrefix(prefix: String): EventTemplateTypeRegistry {
      ...
    }
  }
}
```

</blockquote></details>

Updated -- I wasn't sure how to not use a `var` since the registry would be need to be constructed from a builder. Is this what you were thinking?
___
*[src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventTemplateTypeRegistry.kt, line 35 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/437#-Mv5jv1U5gyuX46vOSCx:-MvKwLCG0ueCXt3fBl_X:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/15350f4bc3688e974ee8a4c849c5a1f79b3638f3/src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventTemplateTypeRegistry.kt#L35)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

IMO the internal registry (currently a map) should be an implementation detail of this class. Could we change this method to be more like

```
fun getDescriptorForType(messageType: String): Descriptor {
  ...
}
```
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventTemplateTypeRegistry.kt, line 41 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/437#-Mv5mlpGESCR20zFVORW:-MvUBMD21l-GWd9b4KVz:b-njnddq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/15350f4bc3688e974ee8a4c849c5a1f79b3638f3/src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventTemplateTypeRegistry.kt#L41)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

I'm not familiar with `Reflections`: will it include subpackages of `packageName`?

I seem to recall that in our dev connect, you were considering a different approach for this. Did that not pan out in the end?
</blockquote></details>

Yes, I did some tests and it does include the subpackages -- added a test to demonstrate this. I had the most success with this library than the native Java ones.
___
*[src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventTemplateTypeRegistry.kt, line 42 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/437#-Mv5nKvBDTh553ewP-Vw:-MvKwREnENvkECJIl3o1:b-fohime) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/15350f4bc3688e974ee8a4c849c5a1f79b3638f3/src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventTemplateTypeRegistry.kt#L42)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

We can be a bit more restrictive and use `Message:class.java`, so that we don't end up loading every type in the package.
</blockquote></details>

Good point -- done.
___
*[src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventTemplateTypeRegistry.kt, line 43 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/437#-Mv5n_xHD8LZL_c1iSlf:-MvVOvQ0DBFIiJY8ymlZ:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/15350f4bc3688e974ee8a4c849c5a1f79b3638f3/src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventTemplateTypeRegistry.kt#L43)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

I think we should do this in a way that doesn't rely on assumptions about naming convention.

What we can do instead is get the message descriptor, and then check if its message options has our custom extension. That would look something like this:

```
val descriptor = ... // get descriptor reflectively
val isEventTemplate = descriptor.options.hasExtension(EventAnnotations.eventTemplate)
```
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/api/v2alpha/event_templates/test_banner_template.proto, line 1 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/437#-Mv5paug5L9HJBuprMSj:-MvL48xU24ykqLV1nLsE:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/15350f4bc3688e974ee8a4c849c5a1f79b3638f3/src/main/kotlin/org/wfanet/measurement/api/v2alpha/event_templates/test_banner_template.proto#L1)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

Please put `.proto` files under `src/main/proto/...` instead of `src/main/kotlin/...`.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/api/v2alpha/event_templates/test_banner_template.proto, line 21 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/437#-Mv5qKzi24d_WZ6djG8r:-MvL4Kk3Afrj_5EJ5roi:b-qpau4w) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/15350f4bc3688e974ee8a4c849c5a1f79b3638f3/src/main/kotlin/org/wfanet/measurement/api/v2alpha/event_templates/test_banner_template.proto#L21)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

Imports should come before file options. See https://developers.google.com/protocol-buffers/docs/style#file_structure
</blockquote></details>

Done; surprised linting didn't catch that.
___
*[src/main/kotlin/org/wfanet/measurement/api/v2alpha/event_templates/test_video_template.proto, line 26 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/437#-Mv5qklQ7IZa3M9QZ1KX:-MvQ7vGpBqWSp0CwjxVw:bqnc6a) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/15350f4bc3688e974ee8a4c849c5a1f79b3638f3/src/main/kotlin/org/wfanet/measurement/api/v2alpha/event_templates/test_video_template.proto#L26)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

This makes me remember that `enum` types will also need to be able to provide the metadata from [...]

2022-02-10 23:54 UTC, robinsons requested changes
> Reviewed 1 of 14 files at r3, 5 of 6 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/437)* status: 9 of 17 files reviewed, 11 unresolved discussions (waiting on @chipingyeh and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventTemplateTypeRegistry.kt, line 27 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/437#-Mv5kMfY8W9U97MDVyou:-Mv_tRZK4jy3agBxa-8r:b-ut46a8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/15350f4bc3688e974ee8a4c849c5a1f79b3638f3/src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventTemplateTypeRegistry.kt#L27)):*
<details><summary><i>Previously, chipingyeh wrote…</i></summary><blockquote>

Updated -- I wasn't sure how to not use a `var` since the registry would be need to be constructed from a builder. Is this what you were thinking?
</blockquote></details>

Yeah, in the snippet I provided above, the `TypeRegistry` becomes the input to the constructor, rather than `packageName: String`. In the companion object, `createRegistryForPackagePrefix()` is essentially a factory method that builds the `TypeRegistry` and passes it when constructing `EventTemplateTypeRegistry`.

In other words, the logic that's in `loadTemplates()` just gets moved into `createRegistryForPackagePrefix()`.
___
*[src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventTemplateTypeRegistry.kt, line 35 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/437#-Mv5jv1U5gyuX46vOSCx:-Mv_vzox8dVTQLCoDXMB:b9o6fxr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/15350f4bc3688e974ee8a4c849c5a1f79b3638f3/src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventTemplateTypeRegistry.kt#L35)):*
<details><summary><i>Previously, chipingyeh wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Nice. You can also remove the `// return templates` comment.
___
*[src/test/kotlin/org/wfanet/measurement/api/v2alpha/EventTemplateTypeRegistryTest.kt, line 32 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/437#-Mva1Vsb5F_mWQt02qGU:-Mva1Vsc1JLc_IiHHbBV:b-tn10hs) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a18860621e516f47f63a43ccb77f3b009acdf6d0/src/test/kotlin/org/wfanet/measurement/api/v2alpha/EventTemplateTypeRegistryTest.kt#L32)):*
> ```Kotlin
>     assertThat(
>         typeRegistry.getDescriptorForType(
>             "org.wfa.measurement.api.v2alpha.eventtemplates.TestBannerTemplate"
> ```

nit: Could store the template names as constants for brevity.



_Code quote:_
```Kotlin
"org.wfa.measurement.api.v2alpha.eventtemplates.TestBannerTemplate"
```
___
*[src/test/kotlin/org/wfanet/measurement/api/v2alpha/EventTemplateTypeRegistryTest.kt, line 52 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/437#-Mva255h2Ph3vnFga-LN:-Mva255h2Ph3vnFga-LO:b-tl1iv9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a18860621e516f47f63a43ccb77f3b009acdf6d0/src/test/kotlin/org/wfanet/measurement/api/v2alpha/EventTemplateTypeRegistryTest.kt#L52)):*
> ```Kotlin
> 
>     assertThat(
>         typeRegistry
> ```

nit / optional: Consider reducing the duplicate code by making a helper extension function:

```
private fun EventTemplateTypeRegistry.getEventTemplateForType(messageType: String) =
  getDescriptorForType(messageType).options.getExtension(EventAnnotations.eventTemplate)
```

Then these assertion bodies are reduced to just `typeRegistry.getEventTemplateForType(<type>).displayName`.



_Code quote:_
```Kotlin
        typeRegistry
          .getDescriptorForType("org.wfa.measurement.api.v2alpha.eventtemplates.TestBannerTemplate")
          .options
          .getExtension(EventAnnotations.eventTemplate)
```
___
*[src/main/proto/wfa/measurement/api/v2alpha/event_templates/BUILD.bazel, line 5 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/437#-Mva-FLV5AW_HYTG915F:-Mva-FLV5AW_HYTG915G:b2jnnc2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a18860621e516f47f63a43ccb77f3b009acdf6d0/src/main/proto/wfa/measurement/api/v2alpha/event_templates/BUILD.bazel#L5)):*
> ```Starlark
> load("@wfa_common_jvm//build/kt_jvm_proto:defs.bzl", "kt_jvm_proto_library")
> 
> package(default_visibility = ["//visibility:public"])
> ```

Since these event templates are purely for tests, I would put them in a /testing subdirectory and then add `default_testonly = True` to this `package` rule.
___
*[src/main/proto/wfa/measurement/api/v2alpha/event_templates/BUILD.bazel, line 8 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/437#-Mva-bYMCv_bS0Pc9_zA:-Mva-bYMCv_bS0Pc9_zB:b-1z3p7a) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a18860621e516f47f63a43ccb77f3b009acdf6d0/src/main/proto/wfa/measurement/api/v2alpha/event_templates/BUILD.bazel#L8)):*
> ```Starlark
> 
> proto_library(
>     name = "event_templates",
> ```

When we make proto library rules, we give the names a `_proto` suffix. So `event_templates_proto` here, and below we would have `event_templates_java_proto` and `event_templates_kt_jvm_proto`.
___
*[src/main/proto/wfa/measurement/api/v2alpha/event_templates/test_banner_template.proto, line 17 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/437#-Mv_y4567sPMKKnXVk_g:-Mv_y4567sPMKKnXVk_h:bgkc5ec) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a18860621e516f47f63a43ccb77f3b009acdf6d0/src/main/proto/wfa/measurement/api/v2alpha/event_templates/test_banner_template.proto#L17)):*
> ```protobuf
> syntax = "proto3";
> 
> package org.wfa.measurement.api.v2alpha.eventtemplates;
> ```

It looks like the package declaration uses `eventtemplates` while the file path uses `event_templates`. Can you change one or the other so that they match?
___
*[src/main/proto/wfa/measurement/api/v2alpha/event_templates/test_video_template.proto, line 17 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/437#-Mv_zLuXDOXZflTpyGkm:-Mv_zLuXDOXZflTpyGkn:b-yigt86) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a18860621e516f47f63a43ccb77f3b009acdf6d0/src/main/proto/wfa/measurement/api/v2alpha/event_templates/test_video_template.proto#L17)):*
> ```protobuf
> syntax = "proto3";
> 
> package org.wfa.measurement.api.v2alpha.eventtemplates;
> ```

Same thing here regarding `eventtemplates` vs. `event_templates`.
___
*[src/main/proto/wfa/measurement/api/v2alpha/event_templates/test_video_template.proto, line 19 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/437#-Mv_zsD87J5ls325WVg_:-Mv_zsD87J5ls325WVga:blyvot4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a18860621e516f47f63a43ccb77f3b009acdf6d0/src/main/proto/wfa/measurement/api/v2alpha/event_templates/test_video_template.proto#L19)):*
> ```protobuf
> package org.wfa.measurement.api.v2alpha.eventtemplates;
> 
> import "google/protobuf/descriptor.proto";
> ```

Is this import used?


<!-- Sent from Reviewable.io -->

2022-02-11 20:07 UTC, chipingyeh reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/437)* status: 4 of 17 files reviewed, 11 unresolved discussions (waiting on @robinsons and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventTemplateTypeRegistry.kt, line 27 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/437#-Mv5kMfY8W9U97MDVyou:-Mve5llV2IHgvcAOlfbf:bpt0dep) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/15350f4bc3688e974ee8a4c849c5a1f79b3638f3/src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventTemplateTypeRegistry.kt#L27)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

Yeah, in the snippet I provided above, the `TypeRegistry` becomes the input to the constructor, rather than `packageName: String`. In the companion object, `createRegistryForPackagePrefix()` is essentially a factory method that builds the `TypeRegistry` and passes it when constructing `EventTemplateTypeRegistry`.

In other words, the logic that's in `loadTemplates()` just gets moved into `createRegistryForPackagePrefix()`.
</blockquote></details>

Ah that makes sense -- updated.
___
*[src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventTemplateTypeRegistry.kt, line 35 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/437#-Mv5jv1U5gyuX46vOSCx:-Mve5Z9D25aMpI0PGMdS:b-yvt125) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/15350f4bc3688e974ee8a4c849c5a1f79b3638f3/src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventTemplateTypeRegistry.kt#L35)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

Nice. You can also remove the `// return templates` comment.
</blockquote></details>

Done. Also updated the comment.
___
*[src/test/kotlin/org/wfanet/measurement/api/v2alpha/EventTemplateTypeRegistryTest.kt, line 32 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/437#-Mva1Vsb5F_mWQt02qGU:-MveGdTh7bB5JeyztEC3:b5yu2u5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a18860621e516f47f63a43ccb77f3b009acdf6d0/src/test/kotlin/org/wfanet/measurement/api/v2alpha/EventTemplateTypeRegistryTest.kt#L32)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

nit: Could store the template names as constants for brevity.
</blockquote></details>

Great idea -- done.
___
*[src/test/kotlin/org/wfanet/measurement/api/v2alpha/EventTemplateTypeRegistryTest.kt, line 52 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/437#-Mva255h2Ph3vnFga-LN:-MveHe5J9cnryP6a26Yj:bav9rok) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a18860621e516f47f63a43ccb77f3b009acdf6d0/src/test/kotlin/org/wfanet/measurement/api/v2alpha/EventTemplateTypeRegistryTest.kt#L52)):*
> private fun EventTemplateTypeRegistry.getEventTemplateForType(messageType: String) =
>   getDescriptorForType(messageType).options.getExtension(EventAnnotations.eventTemplate)
I like that -- done.
___
*[src/main/proto/wfa/measurement/api/v2alpha/event_templates/BUILD.bazel, line 5 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/437#-Mva-FLV5AW_HYTG915F:-Mve6JAa7nfbAzsRLVfu:bqkzxiy) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a18860621e516f47f63a43ccb77f3b009acdf6d0/src/main/proto/wfa/measurement/api/v2alpha/event_templates/BUILD.bazel#L5)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

Since these event templates are purely for tests, I would put them in a /testing subdirectory and then add `default_testonly = True` to this `package` rule.
</blockquote></details>

Done. I also had to add a "testonly" attribute to the BUILD entry of EventTemplateTypeRegistry since it depends on the these.
___
*[src/main/proto/wfa/measurement/api/v2alpha/event_templates/BUILD.bazel, line 8 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/437#-Mva-bYMCv_bS0Pc9_zA:-Mve72ThE9tJZCNCjFEr:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a18860621e516f47f63a43ccb77f3b009acdf6d0/src/main/proto/wfa/measurement/api/v2alpha/event_templates/BUILD.bazel#L8)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

When we make proto library rules, we give the names a `_proto` suffix. So `event_templates_proto` here, and below we would have `event_templates_java_proto` and `event_templates_kt_jvm_proto`.
</blockquote></details>

Done.
___
*[src/main/proto/wfa/measurement/api/v2alpha/event_templates/test_banner_template.proto, line 17 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/437#-Mv_y4567sPMKKnXVk_g:-MveF9mm20ElNIbk-m_1:b-vl9hui) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a18860621e516f47f63a43ccb77f3b009acdf6d0/src/main/proto/wfa/measurement/api/v2alpha/event_templates/test_banner_template.proto#L17)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

It looks like the package declaration uses `eventtemplates` while the file path uses `event_templates`. Can you change one or the other so that they match?
</blockquote></details>

Done -- opted for event_templates.
___
*[src/main/proto/wfa/measurement/api/v2alpha/event_templates/test_video_template.proto, line 17 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/437#-Mv_zLuXDOXZflTpyGkm:-MveFDbr2l806WlpFTTR:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a18860621e516f47f63a43ccb77f3b009acdf6d0/src/main/proto/wfa/measurement/api/v2alpha/event_templates/test_video_template.proto#L17)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

Same thing here regarding `eventtemplates` vs. `event_templates`.
</blockquote></details>

Done.
___
*[src/main/proto/wfa/measurement/api/v2alpha/event_templates/test_video_template.proto, line 19 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/437#-Mv_zsD87J5ls325WVg_:-MveFI-86YyH31byj8U5:b1kkvx7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a18860621e516f47f63a43ccb77f3b009acdf6d0/src/main/proto/wfa/measurement/api/v2alpha/event_templates/test_video_template.proto#L19)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

Is this import used?
</blockquote></details>

It is not -- removed.


<!-- Sent from Reviewable.io -->

2022-02-11 23:53 UTC, robinsons requested changes
> Reviewed 6 of 6 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/437)* status: 10 of 17 files reviewed, 6 unresolved discussions (waiting on @chipingyeh and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventTemplateTypeRegistry.kt, line 27 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/437#-Mvf6kM4-J38Ta1x-Qrd:-Mvf6kM4-J38Ta1x-Qre:b-tum7xn) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ef054441f477a95d058a91b2e87909c84ae749b2/src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventTemplateTypeRegistry.kt#L27)):*
> ```Kotlin
> 
>   /**
>    * Returns the Descriptor for a fully qualified message type. Throws an exception if message is
> ```

Can you indicate what exception it throws? Or alternatively change the return type to `Descriptor?`, and handle the exception internally. Then this function would never throw, and Kotlin would force callers to handle the case where the descriptor is null.
___
*[build/cue/BUILD.bazel, line 0 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/437#-MvfC-ob8e7RtxOcFVgI:-MvfC-ob8e7RtxOcFVgJ:bd617j2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ab371ec7a51ee2aff279dc00cf8daa8f6f66ea7a/build/cue/BUILD.bazel#L0)):*
I'm seeing a number of additional unrelated files. You might need to do some Git magic so that it stops tracking these files as part of your PR.
___
*[src/main/proto/wfa/measurement/api/v2alpha/event_templates/BUILD.bazel, line 5 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/437#-Mva-FLV5AW_HYTG915F:-Mvf8DmdAsspefyZFpqh:bgwt5mx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a18860621e516f47f63a43ccb77f3b009acdf6d0/src/main/proto/wfa/measurement/api/v2alpha/event_templates/BUILD.bazel#L5)):*
<details><summary><i>Previously, chipingyeh wrote…</i></summary><blockquote>

Done. I also had to add a "testonly" attribute to the BUILD entry of EventTemplateTypeRegistry since it depends on the these.
</blockquote></details>

The event template registry shouldn't be be testonly, or else it will only be possible to use it in tests, which isn't what we want.

The issue is that the type registry is currently depending on these event template protos directly, which it shouldn't be. The type registry will have access to any class that is compiled with the binary, regardless of whether the registry's build target has a direct dependency on those classes. In our case, that means that the type registry gets access to our test templates because the templates should be a dependency of the test class, `EventTemplateTypeRegistryTest.kt`.
___
*[src/main/proto/wfa/measurement/api/v2alpha/event_templates/test_banner_template.proto, line 17 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/437#-Mv_y4567sPMKKnXVk_g:-Mvf9dbVCBtNmGaGJzln:b-ul6kyg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a18860621e516f47f63a43ccb77f3b009acdf6d0/src/main/proto/wfa/measurement/api/v2alpha/event_templates/test_banner_template.proto#L17)):*
<details><summary><i>Previously, chipingyeh wrote…</i></summary><blockquote>

Done -- opted for event_templates.
</blockquote></details>

event_templates SGTM.

However, the standard pattern is for the /testing directory to be the final directory in the path, e.g. `org.wfa.measurement.api.v2alpha.event_templates.testing`. The rationale is that production sources and their test-only counterparts should be as close to each other as possible. It also keeps /testing directories from growing their own hierarchies, because each /testing directory is specific to its parent package.


<!-- Sent from Reviewable.io -->

2022-02-14 17:34 UTC, robinsons requested changes
> Reviewed 7 of 7 files at r4, 1 of 6 files at r6, 6 of 7 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/437)* status: 16 of 17 files reviewed, 4 unresolved discussions (waiting on @chipingyeh, @robinsons, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventTemplateTypeRegistry.kt, line 27 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/437#-Mvf6kM4-J38Ta1x-Qrd:-MvtDg_u185_vKv2_muc:b3ytvem) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ef054441f477a95d058a91b2e87909c84ae749b2/src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventTemplateTypeRegistry.kt#L27)):*
<details><summary><i>Previously, chipingyeh wrote…</i></summary><blockquote>

In my testing this throws a `NullPointerException` if it cannot find the message (rather than just returning `null`). I've updated the comment to reflect this.
</blockquote></details>

FWIW, it would return `null` if we changed the return type to `Descriptor?` (according to the documentation for `TypeRegistry` [1]). The reason we get a NPE right now is because Kotlin won't put `null` into a non-nullable type like `Descriptor`.

[1] https://developers.google.com/protocol-buffers/docs/reference/java/com/google/protobuf/TypeRegistry.html#find-java.lang.String-
___
*[src/main/proto/wfa/measurement/api/v2alpha/event_templates/BUILD.bazel, line 5 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/437#-Mva-FLV5AW_HYTG915F:-MvtGba9E5ER5zXj0XE1:bkk3ugm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a18860621e516f47f63a43ccb77f3b009acdf6d0/src/main/proto/wfa/measurement/api/v2alpha/event_templates/BUILD.bazel#L5)):*
<details><summary><i>Previously, chipingyeh wrote…</i></summary><blockquote>

This makes sense. I removed the dependency and tried to directly add the `event_annotations_proto` library from `cross-media-measurement-api` (for use in line 42), but it is now failing with `@wfa_measurement_proto//src/main/proto/wfa/measurement/api/v2alpha:event_annotations_proto does not have mandatory providers: 'JavaInfo'`. It seems like I'll have to add a java/kt library to that BUILD config -- but there are no kt_jvm_libraries currently in that [BUILD](https://sourcegraph.com/github.com/world-federation-of-advertisers/cross-media-measurement-api/-/blob/src/main/proto/wfa/measurement/api/v2alpha/BUILD.bazel?L17) file, possibly by design.
What would be the best approach you suggest here?
</blockquote></details>

You're right, `cross-media-measurement-api` only has `proto_library` rules by design. The pattern we've been following is to place the `java_proto_library` and `kt_jvm_proto_library` rules in `cross-media-measurement` (not `-api`). See this build file [1].

[1] https://sourcegraph.com/github.com/world-federation-of-advertisers/cross-media-measurement@e6d4a2d624b06a81d931c29caed675eb8b48a62b/-/blob/src/main/proto/wfa/measurement/api/v2alpha/BUILD.bazel
___
*[src/main/proto/wfa/measurement/api/v2alpha/event_templates/test_banner_template.proto, line 17 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/437#-Mv_y4567sPMKKnXVk_g:-MvtFhU69GSVGB2LdYIz:b-hgyjfj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a18860621e516f47f63a43ccb77f3b009acdf6d0/src/main/proto/wfa/measurement/api/v2alpha/event_templates/test_banner_template.proto#L17)):*
<details><summary><i>Previously, chipingyeh wrote…</i></summary><blockquote>

That makes sense -- done.
</blockquote></details>

Please also change the `java_package` below -- both in this file as well as in `test_video_template.proto`.


<!-- Sent from Reviewable.io -->

2022-02-14 20:50 UTC, chipingyeh reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/437)* status: 11 of 18 files reviewed, 4 unresolved discussions (waiting on @robinsons and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventTemplateTypeRegistry.kt, line 27 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/437#-Mvf6kM4-J38Ta1x-Qrd:-MvtvRGIAJ2CDxlLVsRk:b-hhtrkj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ef054441f477a95d058a91b2e87909c84ae749b2/src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventTemplateTypeRegistry.kt#L27)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

FWIW, it would return `null` if we changed the return type to `Descriptor?` (according to the documentation for `TypeRegistry` [1]). The reason we get a NPE right now is because Kotlin won't put `null` into a non-nullable type like `Descriptor`.

[1] https://developers.google.com/protocol-buffers/docs/reference/java/com/google/protobuf/TypeRegistry.html#find-java.lang.String-
</blockquote></details>

I see, thanks for the note. I've updated it to return `Descriptor?` with an appropriate comment.
___
*[src/main/proto/wfa/measurement/api/v2alpha/event_templates/BUILD.bazel, line 5 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/437#-Mva-FLV5AW_HYTG915F:-Mvten520NN99TqSpx4a:b-5tioyv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a18860621e516f47f63a43ccb77f3b009acdf6d0/src/main/proto/wfa/measurement/api/v2alpha/event_templates/BUILD.bazel#L5)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

You're right, `cross-media-measurement-api` only has `proto_library` rules by design. The pattern we've been following is to place the `java_proto_library` and `kt_jvm_proto_library` rules in `cross-media-measurement` (not `-api`). See this build file [1].

[1] https://sourcegraph.com/github.com/world-federation-of-advertisers/cross-media-measurement@e6d4a2d624b06a81d931c29caed675eb8b48a62b/-/blob/src/main/proto/wfa/measurement/api/v2alpha/BUILD.bazel
</blockquote></details>

Thanks for the reference -- done.
___
*[src/main/proto/wfa/measurement/api/v2alpha/event_templates/test_banner_template.proto, line 17 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/437#-Mv_y4567sPMKKnXVk_g:-MvtvlIP8radLZaTEyen:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a18860621e516f47f63a43ccb77f3b009acdf6d0/src/main/proto/wfa/measurement/api/v2alpha/event_templates/test_banner_template.proto#L17)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

Please also change the `java_package` below -- both in this file as well as in `test_video_template.proto`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-02-14 21:37 UTC, robinsons approved these changes
> Reviewed 1 of 7 files at r8, 6 of 6 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/437)* status: all files reviewed, 2 unresolved discussions (waiting on @stevenwarejones)



<!-- Sent from Reviewable.io -->

2022-02-16 17:38 UTC, stevenwarejones requested changes
> Reviewed 2 of 2 files at r2, 1 of 14 files at r3, 2 of 6 files at r6, 3 of 7 files at r8, 5 of 6 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/437)* status: all files reviewed, 2 unresolved discussions (waiting on @chipingyeh, @robinsons, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventTemplateTypeRegistry.kt, line 42 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/437#-Mw2b1F_8FM7-SjLWlvg:-Mw2b1F_8FM7-SjLWlvh:b-godkie) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/43fbb4865acc28b902fa2552092ee8f52eca9934/src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventTemplateTypeRegistry.kt#L42)):*
> ```Kotlin
>       for (c in classes) {
>         try {
>           val descriptor = ReflectionUtils.invoke(c.getMethod("getDescriptor"), c) as Descriptor
> ```

I prefer
```
val message = c as Message
val descriptor:Descriptor = message.descriptorForType
```


<!-- Sent from Reviewable.io -->

2022-02-16 18:57 UTC, stevenwarejones approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/437)* status: all files reviewed, 2 unresolved discussions (waiting on @chipingyeh, @robinsons, and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2022-02-16 20:03 UTC, stevenwarejones reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/437)* status: all files reviewed, 2 unresolved discussions (waiting on @chipingyeh, @robinsons, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventTemplateTypeRegistry.kt, line 42 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/437#-Mw2b1F_8FM7-SjLWlvg:-Mw37VNB8uSA6-7VttRS:bi5rwgm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/43fbb4865acc28b902fa2552092ee8f52eca9934/src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventTemplateTypeRegistry.kt#L42)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

but you don't have to cast at all if you do it that way
</blockquote></details>

Actually, you can avoid the cast entirely if you do it this way
```
      for (c in classes) {
        try {
          val constructor = c.getDeclaredConstructor()
          constructor.isAccessible = true
          val descriptor:Descriptor = constructor.newInstance().descriptorForType
          if (descriptor.options.hasExtension(EventAnnotations.eventTemplate)) {
            registryBuilder.add(descriptor)
          }
        } catch (e: InstantiationException) {}
      }
```



_Code quote:_
```Kotlin
catch (e: NoSuchMethodException) {}
```


<!-- Sent from Reviewable.io -->

2022-02-16 21:31 UTC, stevenwarejones approved these changes
> Reviewed 2 of 3 files at r10, 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/437)* status: all files reviewed, 1 unresolved discussion (waiting on @robinsons)



<!-- Sent from Reviewable.io -->

2022-02-16 21:32 UTC, merged