Add PanelMatch ResourceSetup Deployment Doc
world-federation-of-advertisers/cross-media-measurement pull request #441
Opened 2022-02-14 19:26 UTC by yunyeng

2022-02-14 22:05 UTC, SanjayVas requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/441)* status: 0 of 4 files reviewed, 4 unresolved discussions (waiting on @stevenwarejones and @yunyeng)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/441#-MvuFEaY7KYJtrPN2c3p:-MvuFEaZ9iiq1ypVBuCN:b-lqqyyf) (no related file):*
I'm slightly confused why we would have a deployment doc for resource setup for Panel Match. Resource setup jobs are just for running a test, e.g. the correctness test. Nobody should be deploying them individually unless in the context of said test.

If this is for a test, then we should instead have instructions for running that test locally step-by-step as we do in https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/main/k8s/local/README.md. If this is not for a test, then no resource setup job should even exist for panel match. Instead, the Kingdom operator should be using the CreateResource tool to manually add each resource. Perhaps we need to update that tool to cover any missing resource types and add an operations doc for Kingdom operators on how to use it (e.g. updating the secrets and configmap after adding an EDP or MP resource)?

---
___
*[docs/gke/panelmatch-deployment.md, line 17 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/441#-MvuEYYL4JL1Og7OmOPU:-MvuEYYL4JL1Og7OmOPV:b-i2vhkm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b5d0d5ce22ba6d11cd93176c5b57e1a5258216d2/docs/gke/panelmatch-deployment.md#L17)):*
> ```Markdown
> 
> ## Step 0. Before You Start
> ```

Might also want to link machine-setup.md. It's referenced by kingdom-deployment.md, but good to reference it again since the person reading this may not have been the one that deployed the Kingdom.
___
*[docs/gke/panelmatch-deployment.md, line 49 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/441#-MvuErrM2VGPPk9300we:-MvuErrM2VGPPk9300wf:btmq78h) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b5d0d5ce22ba6d11cd93176c5b57e1a5258216d2/docs/gke/panelmatch-deployment.md#L49)):*
> ```Markdown
> 
> ```shell
> bazel test src/...
> ```

nit: `bazel test //src/...`. While `src/...` as the target path will technically work, it's not the proper format.



_Code quote:_
```Markdown
bazel test src/...
```
___
*[docs/gke/panelmatch-deployment.md, line 51 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/441#-MvuEqqj9u3WPMF2ymHv:-MvuEqqj9u3WPMF2ymHw:b-d2ibi9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b5d0d5ce22ba6d11cd93176c5b57e1a5258216d2/docs/gke/panelmatch-deployment.md#L51)):*
> ```Markdown
> bazel test src/...
> ```
> ```

Drop this, as it's assumed that operators will modify their commands as-needed per https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/docs/gke/machine-setup.md.



_Code quote:_
```Markdown
or

```shell
tools/bazel-container test src/...
```

depending on your machine OS.

Read this
[page](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/docs/building.md)
for more details if you have trouble building/testing the codes.
```


<!-- Sent from Reviewable.io -->

2022-02-15 00:12 UTC, yunyeng reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/441)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @SanjayVas and @stevenwarejones)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/441#-MvuFEaY7KYJtrPN2c3p:-Mvuhx5o2rfOScyhJOr8:b-6pay5a) (no related file):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I'm slightly confused why we would have a deployment doc for resource setup for Panel Match. Resource setup jobs are just for running a test, e.g. the correctness test. Nobody should be deploying them individually unless in the context of said test.

If this is for a test, then we should instead have instructions for running that test locally step-by-step as we do in https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/main/k8s/local/README.md. If this is not for a test, then no resource setup job should even exist for panel match. Instead, the Kingdom operator should be using the CreateResource tool to manually add each resource. Perhaps we need to update that tool to cover any missing resource types and add an operations doc for Kingdom operators on how to use it (e.g. updating the secrets and configmap after adding an EDP or MP resource)?
</blockquote></details>

This is to set up resources before Panel Match Daemon deployment. I gave it a title Panel Match deployment, since we can put the daemons configuration here as well?

Yao's ResourceSetup follows same pattern. How about we submit this and create an issue to replace it with CLI tool? Currently, tool is missing MP and RecurringExchange creations.

---
___
*[docs/gke/panelmatch-deployment.md, line 51 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/441#-MvuEqqj9u3WPMF2ymHv:-Mvuhuj_0ytgEW88714v:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b5d0d5ce22ba6d11cd93176c5b57e1a5258216d2/docs/gke/panelmatch-deployment.md#L51)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Drop this, as it's assumed that operators will modify their commands as-needed per https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/docs/gke/machine-setup.md.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-02-15 01:25 UTC, SanjayVas requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/441)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @SanjayVas, @stevenwarejones, and @yunyeng)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/441#-MvuFEaY7KYJtrPN2c3p:-MvuwaqVCd68b4--S-se:b-irqd1q) (no related file):*
<details><summary><i>Previously, yunyeng (Yunus Yen) wrote…</i></summary><blockquote>

This is to set up resources before Panel Match Daemon deployment. I gave it a title Panel Match deployment, since we can put the daemons configuration here as well?

Yao's ResourceSetup follows same pattern. How about we submit this and create an issue to replace it with CLI tool? Currently, tool is missing MP and RecurringExchange creations.
</blockquote></details>

Isn't the Panel Match daemon run by an EDP or MP? That's a different entity than the Kingdom operator who would be creating EDP/MP resources. (Not sure who is supposed to create the RecurringExchange. There's a public service that's unimplemented.)

The process would be as follows:
* EDP sends their certs to Kingdom operator, who creates the resource and updates their configs, giving the resource name back.
* Same as above for MP.
* Someone (???) sets up RecurringExchange in Kingdom. I guess right now this has to be Kingdom operator since public service is not implemented. Gets this resource name to EDP/MP.
* EDP runs their own daemon.
* MP runs their own daemon.

EDP, MP, and Kingdom each run not only in separate clusters, they may run in entirely different clouds projects on different providers.

So the question is again, is this for some test where one entity is acting as all three of these? That's the only case where having a resource setup job for those resources makes sense.

---


<!-- Sent from Reviewable.io -->

2022-02-15 01:28 UTC, SanjayVas requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/441)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @SanjayVas, @stevenwarejones, and @yunyeng)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/441#-MvuFEaY7KYJtrPN2c3p:-MvuzKHcEFFPyFMu1u_M:bbs6mo2) (no related file):*
> Yao's ResourceSetup follows same pattern.

That's because it's used for the correctness test. Otherwise it doesn't make sense to create specifically-named fake EDPs, Duchies, and MC.

---


<!-- Sent from Reviewable.io -->

2022-02-18 19:33 UTC, stevenwarejones approved these changes
> Reviewed 3 of 4 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/441)* status: all files reviewed, 2 unresolved discussions (waiting on @SanjayVas and @yunyeng)



<!-- Sent from Reviewable.io -->

2026-05-15 16:21 UTC, closed without merging