Event filter CEL expression validation
world-federation-of-advertisers/cross-media-measurement pull request #451
Opened 2022-02-23 17:47 UTC by duliomatos1

Adds a validator of Event Filtering expressions that will use the Common Expression Language.
It validates that the expression fits Halo's limitations in terms of structure and operators that are allowed.
(type validation will be in the next component, an Evaluator, that will interpret the fields referenced in the expression).

Note: this is on top of @uakyol's PR, so we can have feedback on how both workflows work together

2022-02-23 18:58 UTC, uakyol commented
Which PR are you referring to Dulio? I don't have any outstanding ones and this is asking to merge into main





<!-- Sent from Reviewable.io -->

2022-02-23 19:46 UTC, duliomatos1 reviewed
I should rebase into main then, I think I've based on this last wekk

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/451#-:-Mwc6cRyBT2Tb_B-axFL:b3q5cpr)* status: 0 of 9 files reviewed, all discussions resolved (waiting on @chipingyeh and @uakyol)



<!-- Sent from Reviewable.io -->

2022-02-24 03:28 UTC, uakyol requested changes
Looks really good Dulio, thanks for putting this together! Just have some minor comments.

Thinking more about this, I think it makes more sense to do type checking here. I left a comment on how I think we can do it. It should be an easy add. 

However, I know this was out of scope when we first talked so feel free to put a todo and I would be happy tackle it in an upcoming PR. 

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/451#-:-MwdhPz_22agw-1WjQSk:bdc52h9)* status: 0 of 9 files reviewed, 15 unresolved discussions (waiting on @chipingyeh and @duliomatos1)

___
*[.gitignore, line 12 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/451#-Mwc5-yiACEPDZs0rH2-:-Mwc5-yiACEPDZs0rH20:b5xm9xy) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c41da6a5c080d180f81aca6541051a43efcb4639/.gitignore#L12)):*
> ```ignore
> *.iml
> 
> # VIM swap files
> ```

Would you mind splitting this to another PR and add @sanjayvas as a reviewer?



_Code quote:_
```ignore
# VIM swap files
```
___
*[src/main/kotlin/org/wfanet/measurement/eventDataProvider/eventFiltration/validation/EventFilterValidationException.kt, line 9 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/451#-Mwdfp2Y2OjmPYgdio-Z:-Mwdfp2Y2OjmPYgdio-_:b-82x822) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2c27ed4ee74d4e820a933563e0b0214faa8b7352/src/main/kotlin/org/wfanet/measurement/eventDataProvider/eventFiltration/validation/EventFilterValidationException.kt#L9)):*
> ```Kotlin
>     this.code = code
>   }
>   enum class Code {
> ```

This is great, thanks for thinking about errors and outlining them clearly.
___
*[src/main/kotlin/org/wfanet/measurement/eventDataProvider/eventFiltration/validation/EventFilterValidationException.kt, line 10 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/451#-MwdkBrZ8UTQB0XJvkh8:-MwdkBrZ8UTQB0XJvkh9:bq6u2mh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2c27ed4ee74d4e820a933563e0b0214faa8b7352/src/main/kotlin/org/wfanet/measurement/eventDataProvider/eventFiltration/validation/EventFilterValidationException.kt#L10)):*
> ```Kotlin
>   }
>   enum class Code {
>     // An expression that cannot be interpreted as a valid CEL
> ```

would you mind formatting the comments like this: https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/common/KingdomInternalException.kt#L29
___
*[src/main/kotlin/org/wfanet/measurement/eventDataProvider/eventFiltration/validation/EventFilterValidator.kt, line 9 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/451#-Mwc5b9h3LO5b9MFrkwi:-Mwc5b9h3LO5b9MFrkwj:b-hw4lts) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c41da6a5c080d180f81aca6541051a43efcb4639/src/main/kotlin/org/wfanet/measurement/eventDataProvider/eventFiltration/validation/EventFilterValidator.kt#L9)):*
> ```Kotlin
> 
> object EventFilterValidator {
>   private val leafOnlyOperators =
> ```

how about private val LEAF_ONLY_OPERATORS and move it out of the Object. Here is something I found in the repo that is dealing with list constants : https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/main/kotlin/org/wfanet/measurement/kingdom/service/system/v1alpha/ComputationsService.kt#L126
___
*[src/main/kotlin/org/wfanet/measurement/eventDataProvider/eventFiltration/validation/EventFilterValidator.kt, line 18 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/451#-Mwc5gt7Cy1ca4_I1wz-:-Mwc5gt7Cy1ca4_I1wz0:b-7ropln) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c41da6a5c080d180f81aca6541051a43efcb4639/src/main/kotlin/org/wfanet/measurement/eventDataProvider/eventFiltration/validation/EventFilterValidator.kt#L18)):*
> ```Kotlin
>       "@in",
>     )
>   private val booleanOperators =
> ```

ditto
___
*[src/main/kotlin/org/wfanet/measurement/eventDataProvider/eventFiltration/validation/EventFilterValidator.kt, line 23 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/451#-Mwc5kS49wyL8TVDl1SY:-Mwc5kS49wyL8TVDl1SZ:bd6kb0t) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c41da6a5c080d180f81aca6541051a43efcb4639/src/main/kotlin/org/wfanet/measurement/eventDataProvider/eventFiltration/validation/EventFilterValidator.kt#L23)):*
> ```Kotlin
>       "_&&_",
>       "_||_",
>     )
> ```

nit: having a new line between these would help
___
*[src/main/kotlin/org/wfanet/measurement/eventDataProvider/eventFiltration/validation/EventFilterValidator.kt, line 24 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/451#-Mwc5hw_4lGU9IThDZZF:-Mwc5hw_4lGU9IThDZZG:b-7ropln) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c41da6a5c080d180f81aca6541051a43efcb4639/src/main/kotlin/org/wfanet/measurement/eventDataProvider/eventFiltration/validation/EventFilterValidator.kt#L24)):*
> ```Kotlin
>       "_||_",
>     )
>   private val allowedOperators = leafOnlyOperators + booleanOperators
> ```

ditto
___
*[src/main/kotlin/org/wfanet/measurement/eventDataProvider/eventFiltration/validation/EventFilterValidator.kt, line 35 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/451#-Mwd7TKLEplOiZlY5j-h:-Mwd7TKLEplOiZlY5j-i:b-yniodu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2c27ed4ee74d4e820a933563e0b0214faa8b7352/src/main/kotlin/org/wfanet/measurement/eventDataProvider/eventFiltration/validation/EventFilterValidator.kt#L35)):*
> ```Kotlin
>       )
>     }
>     if (!right.hasIdentExpr() && !right.hasListExpr()) {
> ```

We don't want to have this complexity for now. : 

https://docs.google.com/document/d/1ov9r4QNwlr9iBGFjimYqj4fOn9F9_QsWGtAUjRN0KsA/edit?resourcekey=0-my5bliWCnEtWOlkDG8kX-Q#heading=h.c7defwo7qgpc 

namely, we don't want to be able to compare 2 variables. Always compare variables to constants. 
___
*[src/main/kotlin/org/wfanet/measurement/eventDataProvider/eventFiltration/validation/EventFilterValidator.kt, line 82 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/451#-Mwdl75J8MAs-l2JdZ0q:-Mwdl75J8MAs-l2JdZ0r:b6xqthg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2c27ed4ee74d4e820a933563e0b0214faa8b7352/src/main/kotlin/org/wfanet/measurement/eventDataProvider/eventFiltration/validation/EventFilterValidator.kt#L82)):*
> ```Kotlin
>   private fun failOnVariableOutsideLeaf(args: List<Expr>) {
>     val hasIndent = args.find { it.hasIdentExpr() } != null
>     val hasCallExpr = args.find { it.hasCallExpr() } != null
> ```

nit: hasCallExpr is used in both failOnVariableOutsideLeaf and failOnInvalidOperationOutsideLeaf . consider extracting this to antoher function and wrapping those function calls in an if?
___
*[src/main/kotlin/org/wfanet/measurement/eventDataProvider/eventFiltration/validation/EventFilterValidator.kt, line 122 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/451#-Mwd8azlAZAxx_mOG0Yg:-Mwd8azlAZAxx_mOG0Yh:bfj0xls) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2c27ed4ee74d4e820a933563e0b0214faa8b7352/src/main/kotlin/org/wfanet/measurement/eventDataProvider/eventFiltration/validation/EventFilterValidator.kt#L122)):*
> ```Kotlin
>       }
>     } else {
>       failOnSingleToplevelValue(level)
> ```

consider calling this in the validate before calli [...]

2022-02-24 17:51 UTC, duliomatos1 reviewed
Yeah, let's add the type checking here, seems natural to do

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/451#-:-Mwgqu5ACQBfpTa89Br8:bfmzkkb)* status: 0 of 9 files reviewed, 14 unresolved discussions (waiting on @chipingyeh, @duliomatos1, @SanjayVas, and @uakyol)

___
*[.gitignore, line 12 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/451#-Mwc5-yiACEPDZs0rH2-:-MwgpkCS0Gx6CAktTwFd:b-bmyoe3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c41da6a5c080d180f81aca6541051a43efcb4639/.gitignore#L12)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

Would you mind splitting this to another PR and add @sanjayvas as a reviewer?
</blockquote></details>

no problem
___
*[src/main/kotlin/org/wfanet/measurement/eventDataProvider/eventFiltration/validation/EventFilterValidationException.kt, line 10 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/451#-MwdkBrZ8UTQB0XJvkh8:-Mwgpo7F9o4_6p1I-PJq:b-wtspaw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2c27ed4ee74d4e820a933563e0b0214faa8b7352/src/main/kotlin/org/wfanet/measurement/eventDataProvider/eventFiltration/validation/EventFilterValidationException.kt#L10)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

would you mind formatting the comments like this: https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/common/KingdomInternalException.kt#L29
</blockquote></details>

sure thing
___
*[src/main/kotlin/org/wfanet/measurement/eventDataProvider/eventFiltration/validation/EventFilterValidator.kt, line 9 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/451#-Mwc5b9h3LO5b9MFrkwi:-MwgprhF1LtPb0Bn53QN:b-g6kjmm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c41da6a5c080d180f81aca6541051a43efcb4639/src/main/kotlin/org/wfanet/measurement/eventDataProvider/eventFiltration/validation/EventFilterValidator.kt#L9)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

how about private val LEAF_ONLY_OPERATORS and move it out of the Object. Here is something I found in the repo that is dealing with list constants : https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/main/kotlin/org/wfanet/measurement/kingdom/service/system/v1alpha/ComputationsService.kt#L126
</blockquote></details>

good suggestion
___
*[src/main/kotlin/org/wfanet/measurement/eventDataProvider/eventFiltration/validation/EventFilterValidator.kt, line 23 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/451#-Mwc5kS49wyL8TVDl1SY:-Mwgqiv_0-Lf4Idnh8MS:b32wtd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c41da6a5c080d180f81aca6541051a43efcb4639/src/main/kotlin/org/wfanet/measurement/eventDataProvider/eventFiltration/validation/EventFilterValidator.kt#L23)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

nit: having a new line between these would help
</blockquote></details>

ok
___
*[src/main/kotlin/org/wfanet/measurement/eventDataProvider/eventFiltration/validation/EventFilterValidator.kt, line 82 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/451#-Mwdl75J8MAs-l2JdZ0q:-Mwgq6G9Ei1mt14oxHBQ:b-pqov82) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2c27ed4ee74d4e820a933563e0b0214faa8b7352/src/main/kotlin/org/wfanet/measurement/eventDataProvider/eventFiltration/validation/EventFilterValidator.kt#L82)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

nit: hasCallExpr is used in both failOnVariableOutsideLeaf and failOnInvalidOperationOutsideLeaf . consider extracting this to antoher function and wrapping those function calls in an if?
</blockquote></details>

makes sense
___
*[src/main/kotlin/org/wfanet/measurement/eventDataProvider/eventFiltration/validation/EventFilterValidator.kt, line 122 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/451#-Mwd8azlAZAxx_mOG0Yg:-MwgqDWR4EuNQ_HtVJ7n:b32wtd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2c27ed4ee74d4e820a933563e0b0214faa8b7352/src/main/kotlin/org/wfanet/measurement/eventDataProvider/eventFiltration/validation/EventFilterValidator.kt#L122)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

consider calling this in the validate before calling validateExpr. This way, you can get rid of the level argument which seems to be only used for the top level.
</blockquote></details>

ok
___
*[src/main/kotlin/org/wfanet/measurement/eventDataProvider/eventFiltration/validation/EventFilterValidator.kt, line 127 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/451#-MwcOfo2AOQX_UZEKSGB:-MwgqHeVE_QDrw6ZGD-R:b-dkei28) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2c27ed4ee74d4e820a933563e0b0214faa8b7352/src/main/kotlin/org/wfanet/measurement/eventDataProvider/eventFiltration/validation/EventFilterValidator.kt#L127)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

Dulio, thinking more about this, I think it makes more sense to do type checking here as well. So perhaps we can have 

fun validate(celExpression: String, env: Env) // env is cel-java environment with types defined.
</blockquote></details>

yeah, I was expecting to validate the typing as well, would be natural to do here. No problem in introducing it in this PR
___
*[src/main/kotlin/org/wfanet/measurement/eventDataProvider/eventFiltration/validation/EventFilterValidator.kt, line 128 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/451#-MwctuXv5YDiqHGQfVYt:-MwgqaF4-fcYTgfAOELc:bb7efny) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2c27ed4ee74d4e820a933563e0b0214faa8b7352/src/main/kotlin/org/wfanet/measurement/eventDataProvider/eventFiltration/validation/EventFilterValidator.kt#L128)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

and for this line, we don't use the parser but use compile instead. This will return the AST as well
</blockquote></details>

cool


<!-- Sent from Reviewable.io -->

2022-02-24 22:59 UTC, uakyol requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/451)* status: 0 of 9 files reviewed, 16 unresolved discussions (waiting on @chipingyeh, @duliomatos1, @SanjayVas, and @uakyol)

___
*[src/main/kotlin/org/wfanet/measurement/eventDataProvider/eventFiltration/validation/EventFilterValidationException.kt, line 1 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/451#-MwhvM4UD4yYywf6F8Wf:-MwhvM4UD4yYywf6F8Wg:b6ws954) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2c27ed4ee74d4e820a933563e0b0214faa8b7352/src/main/kotlin/org/wfanet/measurement/eventDataProvider/eventFiltration/validation/EventFilterValidationException.kt#L1)):*
> ```Kotlin
> package org.wfanet.measurement.eventDataProvider.eventFiltration.validation
> ```

We need these copyright comments at top of files : https://developer.android.com/kotlin/style-guide 

https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/common/KingdomInternalException.kt#L1
___
*[src/main/kotlin/org/wfanet/measurement/eventDataProvider/eventFiltration/validation/EventFilterValidator.kt, line 127 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/451#-MwhxAGi2-xYcW8OSkR_:-MwhxAGi2-xYcW8OSkRa:bakkp32) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2c27ed4ee74d4e820a933563e0b0214faa8b7352/src/main/kotlin/org/wfanet/measurement/eventDataProvider/eventFiltration/validation/EventFilterValidator.kt#L127)):*
> ```Kotlin
>   }
> 
>   fun validate(celExpression: String) {
> ```

Would be good to have a Kdoc like this one :https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ConfirmComputationParticipant.kt#L33


<!-- Sent from Reviewable.io -->

2022-02-24 23:24 UTC, uakyol commented
___
*[src/main/kotlin/org/wfanet/measurement/eventDataProvider/eventFiltration/validation/EventFilterValidator.kt, line 103 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/451#-Mwi0QJh3IoxIuhe9SDF:-Mwi0QJh3IoxIuhe9SDG:b-9pu0w8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2c27ed4ee74d4e820a933563e0b0214faa8b7352/src/main/kotlin/org/wfanet/measurement/eventDataProvider/eventFiltration/validation/EventFilterValidator.kt#L103)):*
> ```Kotlin
> 
>   private fun validateExpr(expr: Expr, level: Int) {
>     if (expr.hasCallExpr()) {
> ```

Nit:  maybe we can simplify as below. This way we get rid of else and I guess we can write return validateInOperator(callExpr) wdyt? Also, to match how you tackled other fail functions, you can do the same for UNSUPPORTED_OPERATION - extracting it to failOnNotAllowedOperator



_Code snippet:_
```Kotlin
  private fun validateExpr(expr: Expr) {
    
    if (!expr.hasCallExpr()) {
      return failOnListOutsideInOperator(expr)
    } 
    
    val callExpr: Expr.Call = expr.callExpr
    val operator = callExpr.function
    failOnNotAllowedOperator(operator)
    
    if (operator == "@in") {
        return validateInOperator(callExpr)
    }
    
    failOnVariableOutsideLeaf(callExpr.argsList)
    failOnInvalidOperationOutsideLeaf(callExpr)
    for (arg in callExpr.argsList) {
      validateExpr(arg)
    }
  }
```


<!-- Sent from Reviewable.io -->

2022-02-25 16:34 UTC, duliomatos1 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/451)* status: 0 of 9 files reviewed, 17 unresolved discussions (waiting on @chipingyeh, @duliomatos1, @SanjayVas, and @uakyol)

___
*[src/main/kotlin/org/wfanet/measurement/eventDataProvider/eventFiltration/validation/EventFilterValidator.kt, line 35 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/451#-Mwd7TKLEplOiZlY5j-h:-MwliaNGEzWygSMg9k_7:bf646ps) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2c27ed4ee74d4e820a933563e0b0214faa8b7352/src/main/kotlin/org/wfanet/measurement/eventDataProvider/eventFiltration/validation/EventFilterValidator.kt#L35)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

We don't want to have this complexity for now. : 

https://docs.google.com/document/d/1ov9r4QNwlr9iBGFjimYqj4fOn9F9_QsWGtAUjRN0KsA/edit?resourcekey=0-my5bliWCnEtWOlkDG8kX-Q#heading=h.c7defwo7qgpc 

namely, we don't want to be able to compare 2 variables. Always compare variables to constants. 
</blockquote></details>

this is actually comparing variable to a list of constant. Ex. v in [1, 3, 5]


<!-- Sent from Reviewable.io -->

2022-02-28 17:01 UTC, stevenwarejones reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/451)* status: 5 of 9 files reviewed, 21 unresolved discussions (waiting on @chipingyeh, @duliomatos1, @SanjayVas, and @uakyol)

___
*[src/main/kotlin/org/wfanet/measurement/eventDataProvider/eventFiltration/validation/EventFilterValidator.kt, line 127 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/451#-MwcOfo2AOQX_UZEKSGB:-Mx0GpAf9D3ogW6SQv2Q:bdgx1b1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2c27ed4ee74d4e820a933563e0b0214faa8b7352/src/main/kotlin/org/wfanet/measurement/eventDataProvider/eventFiltration/validation/EventFilterValidator.kt#L127)):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

yeah, I was expecting to validate the typing as well, would be natural to do here. No problem in introducing it in this PR
</blockquote></details>

i'm also fine making it a follow-up to keep these PRs as slim as possible


<!-- Sent from Reviewable.io -->

2022-03-02 05:05 UTC, uakyol commented
___
*[src/test/kotlin/org/wfanet/measurement/eventDataProvider/eventFiltration/validation/EventFilterValidatorTest.kt, line 11 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/451#-MwdeQCFAs_dEy9BjN1V:-Mx8-qUC53-oAwpPudbr:b-8vmsow) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2c27ed4ee74d4e820a933563e0b0214faa8b7352/src/test/kotlin/org/wfanet/measurement/eventDataProvider/eventFiltration/validation/EventFilterValidatorTest.kt#L11)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

If you end up deciding to do the type checking in this PR, it would be great to have a test case that passes in an env that has its declerations from a protobuf. Since that will be how that env will be created most of the time. here are some examples: https://github.com/projectnessie/cel-java/blob/main/core/src/test/java/org/projectnessie/cel/checker/CheckerTest.java#L420
</blockquote></details>

I played around with this, here is something I came up with that works. Hope it saves you some time:



_Code snippet:_
```Kotlin
    val TEMPLATE_PREFIX = "org.wfa.measurement.api.v2alpha.event_templates.testing"
    
    // These fields are made up
    val expression : String = "(vt.name == \"something\") && (bt.age > 5)" 

    val dpType:Type = Decls.newObjectType("$TEMPLATE_PREFIX.TestVideoTemplate");
    val btType:Type = Decls.newObjectType("$TEMPLATE_PREFIX.TestBannerTemplate");
    val reg:TypeRegistry = ProtoTypeRegistry.newRegistry(TestVideoTemplate.getDefaultInstance(), TestBannerTemplate.getDefaultInstance());

    val env:Env =
        newEnv(
            EnvOption.customTypeAdapter(reg),
            EnvOption.customTypeProvider(reg),
            EnvOption.declarations(Decls.newVar("vt", dpType), Decls.newVar("bt", btType)));

    val astAndIssues: AstIssuesTuple =  env.compile(expression)
    val prg:Program = env.program(astAndIssues.getAst());
    println(astAndIssues.getIssues().toString())
    println(astAndIssues.getAst())
    val out: EvalResult = prg.eval(hashMapOf("vt" to testVideoTemplate{name  = "something"}, "bt" to testBannerTemplate{age  = 10}))
```


<!-- Sent from Reviewable.io -->

2022-03-03 15:46 UTC, duliomatos1 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/451)* status: 5 of 9 files reviewed, 21 unresolved discussions (waiting on @chipingyeh, @duliomatos1, @SanjayVas, and @uakyol)

___
*[src/test/kotlin/org/wfanet/measurement/eventDataProvider/eventFiltration/validation/EventFilterValidatorTest.kt, line 11 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/451#-MwdeQCFAs_dEy9BjN1V:-MxFQzmK60XkD2cEuS14:bm5mc9o) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2c27ed4ee74d4e820a933563e0b0214faa8b7352/src/test/kotlin/org/wfanet/measurement/eventDataProvider/eventFiltration/validation/EventFilterValidatorTest.kt#L11)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

I played around with this, here is something I came up with that works. Hope it saves you some time:
</blockquote></details>

We should be able to validate if the leaf comparisons have the same typing on both sides of the operation. In this example we should validate vt.name is a string and bt.age is a int. Makes sense? Those types on the comparison would be either a string or some number type


<!-- Sent from Reviewable.io -->

2022-03-03 17:29 UTC, duliomatos1 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/451)* status: 5 of 9 files reviewed, 21 unresolved discussions (waiting on @chipingyeh, @duliomatos1, @SanjayVas, and @uakyol)

___
*[src/test/kotlin/org/wfanet/measurement/eventDataProvider/eventFiltration/validation/EventFilterValidatorTest.kt, line 11 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/451#-MwdeQCFAs_dEy9BjN1V:-MxFp-jL6-kAxL5teOCp:b-oixc32) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2c27ed4ee74d4e820a933563e0b0214faa8b7352/src/test/kotlin/org/wfanet/measurement/eventDataProvider/eventFiltration/validation/EventFilterValidatorTest.kt#L11)):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

We should be able to validate if the leaf comparisons have the same typing on both sides of the operation. In this example we should validate vt.name is a string and bt.age is a int. Makes sense? Those types on the comparison would be either a string or some number type
</blockquote></details>

`compile()` actually does type validation, which is perfect


<!-- Sent from Reviewable.io -->

2022-03-03 18:53 UTC, duliomatos1 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/451)* status: 0 of 9 files reviewed, 21 unresolved discussions (waiting on @chipingyeh, @duliomatos1, @SanjayVas, @stevenwarejones, and @uakyol)

___
*[src/main/kotlin/org/wfanet/measurement/eventDataProvider/eventFiltration/validation/EventFilterValidationException.kt, line 3 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/451#-Mx07swPBRfR7BX94up6:-MxG60ewEVEHufOU-6m6:b-klqz4j) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2c27ed4ee74d4e820a933563e0b0214faa8b7352/src/main/kotlin/org/wfanet/measurement/eventDataProvider/eventFiltration/validation/EventFilterValidationException.kt#L3)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

wdyt about
```
class EventFilterValidationException(
  val code: Code,
  override val message: String
) : Exception(message) {
```

</blockquote></details>

yeah, changing to this syntax is better


<!-- Sent from Reviewable.io -->

2022-03-03 18:56 UTC, duliomatos1 reviewed
> Dismissed @uakyol from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/451)* status: 0 of 9 files reviewed, 18 unresolved discussions (waiting on @chipingyeh, @duliomatos1, @SanjayVas, @stevenwarejones, and @uakyol)

___
*[src/main/kotlin/org/wfanet/measurement/eventDataProvider/eventFiltration/validation/EventFilterValidationException.kt, line 1 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/451#-MwhvM4UD4yYywf6F8Wf:-MxG7U9Y3-pIKggsuEhH:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2c27ed4ee74d4e820a933563e0b0214faa8b7352/src/main/kotlin/org/wfanet/measurement/eventDataProvider/eventFiltration/validation/EventFilterValidationException.kt#L1)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

We need these copyright comments at top of files : https://developer.android.com/kotlin/style-guide 

https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/common/KingdomInternalException.kt#L1
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/eventDataProvider/eventFiltration/validation/EventFilterValidationException.kt, line 6 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/451#-Mx08DNI3XK8gVPTOFrN:-MxG7Qb13G2SzhZMWVJz:b-5mw4c9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2c27ed4ee74d4e820a933563e0b0214faa8b7352/src/main/kotlin/org/wfanet/measurement/eventDataProvider/eventFiltration/validation/EventFilterValidationException.kt#L6)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

what is the use case for two constructors?
</blockquote></details>

Done. Removed
___
*[src/main/kotlin/org/wfanet/measurement/eventDataProvider/eventFiltration/validation/EventFilterValidator.kt, line 127 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/451#-MwhxAGi2-xYcW8OSkR_:-MxG7aRg51rapHRqeh_N:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2c27ed4ee74d4e820a933563e0b0214faa8b7352/src/main/kotlin/org/wfanet/measurement/eventDataProvider/eventFiltration/validation/EventFilterValidator.kt#L127)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

Would be good to have a Kdoc like this one :https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/ConfirmComputationParticipant.kt#L33
</blockquote></details>

Done.
___
*[src/test/kotlin/org/wfanet/measurement/eventDataProvider/eventFiltration/validation/EventFilterValidatorTest.kt, line 21 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/451#-Mwc6jb8CpCZMf-D9v02:-MxG7nq12-FGiPbTR_eJ:b-7rl0jd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c41da6a5c080d180f81aca6541051a43efcb4639/src/test/kotlin/org/wfanet/measurement/eventDataProvider/eventFiltration/validation/EventFilterValidatorTest.kt#L21)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

supernit:  rather than 'it fails on invalid operation' ,  'fails on invalid operation' is enough. Total supernit though :) feel free to keep as is if you like. Ditto for other test cases.
</blockquote></details>

done.


<!-- Sent from Reviewable.io -->

2022-03-03 19:05 UTC, uakyol commented
___
*[src/test/kotlin/org/wfanet/measurement/eventDataProvider/eventFiltration/validation/EventFilterValidatorTest.kt, line 11 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/451#-MwdeQCFAs_dEy9BjN1V:-MxG9iHx-JocVISB_8Uj:b-xdq0it) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2c27ed4ee74d4e820a933563e0b0214faa8b7352/src/test/kotlin/org/wfanet/measurement/eventDataProvider/eventFiltration/validation/EventFilterValidatorTest.kt#L11)):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

`compile()` actually does type validation, which is perfect
</blockquote></details>

Yes correct, and yes compile should do this. You don't have to use 2 diferent protos btw, for testing, 1 should be enough, just wanted to show we can union them too.


<!-- Sent from Reviewable.io -->

2022-03-03 19:11 UTC, uakyol requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/451)* status: 0 of 9 files reviewed, 11 unresolved discussions (waiting on @chipingyeh, @duliomatos1, @SanjayVas, @stevenwarejones, and @uakyol)

___
*[src/main/kotlin/org/wfanet/measurement/eventDataProvider/eventFiltration/validation/EventFilterValidationException.kt, line 1 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/451#-MxGAJ4K-L5Ymwb9EePR:-MxGAJ4K-L5Ymwb9EePS:bb6ht37) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/af252753c6c7cad521774a6affa016a48d2bcbbb/src/main/kotlin/org/wfanet/measurement/eventDataProvider/eventFiltration/validation/EventFilterValidationException.kt#L1)):*
> ```Kotlin
> // Copyright 2020 The Cross-Media Measurement Authors
> ```

2022
___
*[src/main/kotlin/org/wfanet/measurement/eventDataProvider/eventFiltration/validation/EventFilterValidationException.kt, line 13 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/451#-MxGAOJj9hju5ZhJ-6QU:-MxGAOJj9hju5ZhJ-6QV:bs6gz5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/af252753c6c7cad521774a6affa016a48d2bcbbb/src/main/kotlin/org/wfanet/measurement/eventDataProvider/eventFiltration/validation/EventFilterValidationException.kt#L13)):*
> ```Kotlin
> // WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
> // See the License for the specific language governing permissions and
> // limitations under the License.
> ```

new line please
___
*[src/main/kotlin/org/wfanet/measurement/eventDataProvider/eventFiltration/validation/EventFilterValidator.kt, line 35 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/451#-Mwd7TKLEplOiZlY5j-h:-MxGB0mO2fB1mhxN9msD:b-uv2qut) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2c27ed4ee74d4e820a933563e0b0214faa8b7352/src/main/kotlin/org/wfanet/measurement/eventDataProvider/eventFiltration/validation/EventFilterValidator.kt#L35)):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

this is actually comparing variable to a list of constant. Ex. v in [1, 3, 5]
</blockquote></details>

Ah I see, sorry misunderstood. Thanks for clarification


<!-- Sent from Reviewable.io -->

2022-03-04 13:23 UTC, duliomatos1 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/451)* status: 0 of 9 files reviewed, 11 unresolved discussions (waiting on @chipingyeh, @duliomatos1, @SanjayVas, @stevenwarejones, and @uakyol)

___
*[src/main/kotlin/org/wfanet/measurement/eventDataProvider/eventFiltration/validation/EventFilterValidationException.kt, line 1 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/451#-MxGAJ4K-L5Ymwb9EePR:-MxK4QGcBluWuFpd2_d9:bp909ve) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/af252753c6c7cad521774a6affa016a48d2bcbbb/src/main/kotlin/org/wfanet/measurement/eventDataProvider/eventFiltration/validation/EventFilterValidationException.kt#L1)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

2022
</blockquote></details>

oops, probably have more files with this problem
___
*[src/test/kotlin/org/wfanet/measurement/eventDataProvider/eventFiltration/validation/EventFilterValidatorTest.kt, line 11 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/451#-MwdeQCFAs_dEy9BjN1V:-MxK4_7oBjHB4LjG47w1:b-cebma3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2c27ed4ee74d4e820a933563e0b0214faa8b7352/src/test/kotlin/org/wfanet/measurement/eventDataProvider/eventFiltration/validation/EventFilterValidatorTest.kt#L11)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

Yes correct, and yes compile should do this. You don't have to use 2 diferent protos btw, for testing, 1 should be enough, just wanted to show we can union them too.
</blockquote></details>

I've figured TestVideoTemplate would be enough. I've wanted to create a test with a field from each template but TestBannerTemplate didn't have fields. How about I add a field to it, add a new test, and keep both?


<!-- Sent from Reviewable.io -->

2022-03-04 13:52 UTC, duliomatos1 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/451)* status: 0 of 9 files reviewed, 11 unresolved discussions (waiting on @chipingyeh, @duliomatos1, @SanjayVas, @stevenwarejones, and @uakyol)

___
*[src/test/kotlin/org/wfanet/measurement/eventDataProvider/eventFiltration/validation/EventFilterValidatorTest.kt, line 11 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/451#-MwdeQCFAs_dEy9BjN1V:-MxKBstU-UmCE-P5QgXF:bmzifj8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2c27ed4ee74d4e820a933563e0b0214faa8b7352/src/test/kotlin/org/wfanet/measurement/eventDataProvider/eventFiltration/validation/EventFilterValidatorTest.kt#L11)):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

I've figured TestVideoTemplate would be enough. I've wanted to create a test with a field from each template but TestBannerTemplate didn't have fields. How about I add a field to it, add a new test, and keep both?
</blockquote></details>

I'll remove the second proto from testing unless it makes sense for a new test case


<!-- Sent from Reviewable.io -->

2022-03-04 14:07 UTC, duliomatos1 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/451)* status: 0 of 9 files reviewed, 11 unresolved discussions (waiting on @chipingyeh, @duliomatos1, @SanjayVas, @stevenwarejones, and @uakyol)

___
*[src/test/kotlin/org/wfanet/measurement/eventDataProvider/eventFiltration/validation/EventFilterValidatorTest.kt, line 68 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/451#-MwdewaOAo12J6kD-Zbs:-MxKFLTw5oMwNcLcf0jc:brnmt9o) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2c27ed4ee74d4e820a933563e0b0214faa8b7352/src/test/kotlin/org/wfanet/measurement/eventDataProvider/eventFiltration/validation/EventFilterValidatorTest.kt#L68)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

+1
</blockquote></details>

done. Added as another test case


<!-- Sent from Reviewable.io -->

2022-03-04 18:10 UTC, duliomatos1 reviewed
> Dismissed @uakyol from 2 discussions.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/451)* status: 8 of 9 files reviewed, 6 unresolved discussions (waiting on @chipingyeh, @duliomatos1, @SanjayVas, @stevenwarejones, and @uakyol)

___
*[src/main/kotlin/org/wfanet/measurement/eventDataProvider/eventFiltration/validation/EventFilterValidationException.kt, line 13 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/451#-MxGAOJj9hju5ZhJ-6QU:-MxL6oMd8GupBQYjd6Hm:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/af252753c6c7cad521774a6affa016a48d2bcbbb/src/main/kotlin/org/wfanet/measurement/eventDataProvider/eventFiltration/validation/EventFilterValidationException.kt#L13)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

new line please
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/eventDataProvider/eventFiltration/validation/EventFilterValidator.kt, line 127 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/451#-MwcOfo2AOQX_UZEKSGB:-MxL6r4w6wGbA-CPkcIO:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2c27ed4ee74d4e820a933563e0b0214faa8b7352/src/main/kotlin/org/wfanet/measurement/eventDataProvider/eventFiltration/validation/EventFilterValidator.kt#L127)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

i'm also fine making it a follow-up to keep these PRs as slim as possible
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-03-05 01:02 UTC, uakyol requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/451)* status: 8 of 9 files reviewed, 3 unresolved discussions (waiting on @chipingyeh, @duliomatos1, @SanjayVas, and @stevenwarejones)

___
*[src/test/kotlin/org/wfanet/measurement/eventDataProvider/eventFiltration/validation/EventFilterValidatorTest.kt, line 11 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/451#-MwdeQCFAs_dEy9BjN1V:-MxM_HKsABDP-eY75zqN:b-h0g1pe) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2c27ed4ee74d4e820a933563e0b0214faa8b7352/src/test/kotlin/org/wfanet/measurement/eventDataProvider/eventFiltration/validation/EventFilterValidatorTest.kt#L11)):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

I'll remove the second proto from testing unless it makes sense for a new test case
</blockquote></details>

Sounds great Dulio, however, I don't see the changes here. Did you add them or were you commenting to say that you will add them. 
If latter is the case, it is preferable to comment when you made the change so that the reviewer can see the code together with the comment. Sorry if you already made the change and I am somehow missing. 
___
*[src/test/kotlin/org/wfanet/measurement/eventDataProvider/eventFiltration/validation/EventFilterValidatorTest.kt, line 68 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/451#-MwdewaOAo12J6kD-Zbs:-MxM__Zx4wJooEu8YLxx:b-d3xo2b) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2c27ed4ee74d4e820a933563e0b0214faa8b7352/src/test/kotlin/org/wfanet/measurement/eventDataProvider/eventFiltration/validation/EventFilterValidatorTest.kt#L68)):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

done. Added as another test case
</blockquote></details>

Hey Dulio, sorry which is the one you added?


<!-- Sent from Reviewable.io -->

2022-03-07 14:12 UTC, duliomatos1 reviewed
> Dismissed @uakyol from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/451)* status: 8 of 9 files reviewed, 4 unresolved discussions (waiting on @chipingyeh, @SanjayVas, @stevenwarejones, and @uakyol)

___
*[src/test/kotlin/org/wfanet/measurement/eventDataProvider/eventFiltration/validation/EventFilterValidatorTest.kt, line 11 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/451#-MwdeQCFAs_dEy9BjN1V:-MxZgzQy2_J_wcURpEH8:bqptwzq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2c27ed4ee74d4e820a933563e0b0214faa8b7352/src/test/kotlin/org/wfanet/measurement/eventDataProvider/eventFiltration/validation/EventFilterValidatorTest.kt#L11)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

Sounds great Dulio, however, I don't see the changes here. Did you add them or were you commenting to say that you will add them. 
If latter is the case, it is preferable to comment when you made the change so that the reviewer can see the code together with the comment. Sorry if you already made the change and I am somehow missing. 
</blockquote></details>

I've removed all references to `TestBannerTemplate` and changed the only test case that used it previously (`fails on inexistant template field`) to just use `TestVideoTemplate` instead
___
*[src/test/kotlin/org/wfanet/measurement/eventDataProvider/eventFiltration/validation/EventFilterValidatorTest.kt, line 68 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/451#-MwdewaOAo12J6kD-Zbs:-MxZgf-O--HG0Ipjsk1X:b-tr70mr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2c27ed4ee74d4e820a933563e0b0214faa8b7352/src/test/kotlin/org/wfanet/measurement/eventDataProvider/eventFiltration/validation/EventFilterValidatorTest.kt#L68)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

Hey Dulio, sorry which is the one you added?
</blockquote></details>

`fails on comparing int to boolean conditional`



_Code quote:_
```Kotlin
`fails on comparing int to boolean conditional`
```
___
*[src/test/kotlin/org/wfanet/measurement/eventDataProvider/eventFiltration/validation/EventFilterValidatorTest.kt, line 50 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/451#-MxZhUHB2tICKMcYRaph:-MxZhUHB2tICKMcYRapi:b-721hh1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f9505fe07ab37a47dee602e76fad0f40c09be4da/src/test/kotlin/org/wfanet/measurement/eventDataProvider/eventFiltration/validation/EventFilterValidatorTest.kt#L50)):*
> ```Kotlin
>     var typeRegistry: ProtoTypeRegistry =
>       ProtoTypeRegistry.newRegistry(
>         TestVideoTemplate.getDefaultInstance(),
> ```

@uakyol, not using `TestBannerTemplate`anymore in any test
___
*[src/test/kotlin/org/wfanet/measurement/eventDataProvider/eventFiltration/validation/EventFilterValidatorTest.kt, line 90 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/451#-MxZgNTtB1qyun3xAxTk:-MxZgNTtB1qyun3xAxTl:bd9m6lj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f9505fe07ab37a47dee602e76fad0f40c09be4da/src/test/kotlin/org/wfanet/measurement/eventDataProvider/eventFiltration/validation/EventFilterValidatorTest.kt#L90)):*
@uakyol this is the new test case following your suggestion

> another case I can think of is something like ( age && (date>5) ) this would fail on FIELD_COMPARISON_OUTSIDE_LEAF, which is great.
If we implement type checking, Cel should fail on this because it will type check and realize age is not a bool.


<!-- Sent from Reviewable.io -->

2022-03-07 17:41 UTC, uakyol approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/451#-:-Mx_T50h9CjnHiW91Xqj:bnfp4nl)* status: 7 of 9 files reviewed, 4 unresolved discussions (waiting on @chipingyeh, @duliomatos1, @SanjayVas, and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2022-03-07 18:52 UTC, duliomatos1 reviewed
> Dismissed @uakyol from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/451)* status: 7 of 9 files reviewed, 2 unresolved discussions (waiting on @chipingyeh, @SanjayVas, and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2022-03-07 22:20 UTC, stevenwarejones approved these changes
> Reviewed 1 of 7 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/451)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @chipingyeh and @SanjayVas)



<!-- Sent from Reviewable.io -->

2022-03-07 23:28 UTC, merged