Ensure an exchange step is not its own prerequisite.
world-federation-of-advertisers/cross-media-measurement pull request #489
Opened 2022-03-21 16:08 UTC by robinsons

In general, exchange steps should not have the same blob key in both their input map and output map, as this causes the step to be its own prerequisite and thus can never enter a READY state. The only exception is CopyFromPreviousExchangeStep which must have the same input and output blob key in order to work correctly. For this type of step, explicitly remove its index from the prerequisite indices so that it can be properly scheduled.

2022-03-21 17:40 UTC, efoxepstein requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/489)* status: all files reviewed, 1 unresolved discussion (waiting on @robinsons, @stevenwarejones, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt, line 428 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/489#-MyhZCx6365NZE176IzO:-MyhZCx795pFcKZ6szHJ:bfceamj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ed452e196ad4247f023970de7bbe43ce2f55ed76/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt#L428)):*
> ```Kotlin
>               indices
>             }
>             .filter { it != index }
> ```

To avoid cycles, can we just enforce that `it < index` (and thus require the steps to be topologically sorted)?


<!-- Sent from Reviewable.io -->

2022-03-21 17:41 UTC, efoxepstein approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/489#-:-MyhZL81E69P4ZMcIyjJ:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @robinsons, @stevenwarejones, and @yunyeng)



<!-- Sent from Reviewable.io -->

2022-03-21 20:00 UTC, robinsons reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/489)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @efoxepstein, @stevenwarejones, and @yunyeng)

___
*[src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt, line 428 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/489#-MyhZCx6365NZE176IzO:-Myi3HJFBNbW2vjEeCu8:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ed452e196ad4247f023970de7bbe43ce2f55ed76/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt#L428)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

To avoid cycles, can we just enforce that `it < index` (and thus require the steps to be topologically sorted)?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-03-21 20:26 UTC, yunyeng approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/489)* status: all files reviewed, 1 unresolved discussion (waiting on @efoxepstein and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2022-03-22 00:01 UTC, stevenwarejones approved these changes
can you add a test?

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/489#-:-MyivUfV9BTucPgf37y9:b5747ax)* status: all files reviewed, 1 unresolved discussion (waiting on @efoxepstein)



<!-- Sent from Reviewable.io -->

2022-03-22 18:29 UTC, robinsons reviewed
There wasn't an existing one, so I added test cases just for `ExchangeWorkflow.toInternal()` and made sure to hit the added functionality introduced by this PR.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/489#-:-Mymshg4EmYEkr94c17Q:b-copdps)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @efoxepstein, @stevenwarejones, and @yunyeng)



<!-- Sent from Reviewable.io -->

2022-03-22 18:30 UTC, robinsons reviewed
> Reviewed 1 of 1 files at r2, 2 of 2 files at r3, all commit messages.
> Dismissed @efoxepstein from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/489)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @robinsons)



<!-- Sent from Reviewable.io -->

2022-03-22 18:30 UTC, merged