Replace 3rd party Reflections library with google.common.reflect
world-federation-of-advertisers/cross-media-measurement pull request #490
Opened 2022-03-21 18:54 UTC by chipingyeh

2022-03-21 22:14 UTC, robinsons requested changes
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/490)* status: all files reviewed, 3 unresolved discussions (waiting on @chipingyeh, @SanjayVas, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventTemplateTypeRegistry.kt, line 35 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/490#-MyiRPCkDkbEqXsMERHa:-MyiRPCl64OOo6MdvJeE:b-lbhnqu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6c95b73fed8c51bde256914d3c64dcbacd2b41c0/src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventTemplateTypeRegistry.kt#L35)):*
> ```Kotlin
>   companion object {
>     /**
>      * Creates a Type Registry for all Messages in a classpath @prefix. All utilized templates
> ```

nit: is `@prefix` supposed to be `[prefix]`?
___
*[src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventTemplateTypeRegistry.kt, line 44 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/490#-MyiX9qqCgJbKRJ4V6-5:-MyiX9qqCgJbKRJ4V6-6:b5o38t4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6c95b73fed8c51bde256914d3c64dcbacd2b41c0/src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventTemplateTypeRegistry.kt#L44)):*
> ```Kotlin
>       for (c in classes) {
>         try {
>           val constructor = c.load().getDeclaredConstructor() as Constructor<out Message>
> ```

We can avoid a blind type cast if we check the type:

```
val clazz = c.load()
if (!Message::class.java.isAssignableFrom(clazz)) {
  continue
}
```

I believe that with this and my next comment combined, we can remove the `catch` blocks.
___
*[src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventTemplateTypeRegistry.kt, line 45 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/490#-MyiVMiJ8eFxLXpNNwrX:-MyiVMiJ8eFxLXpNNwrY:be06t32) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6c95b73fed8c51bde256914d3c64dcbacd2b41c0/src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventTemplateTypeRegistry.kt#L45)):*
If we have to explicitly set `isAccessible` to true, IMO we shouldn't be using that constructor. The class might be designed for instantiation via some other mechanism, and calling a private constructor could leave some important initialization step undone.

I'd prefer if we used the static function `getDescriptor()`. Quoting from the protobuf docs [1]

>  ... the wrapper class itself will have the following API (assuming the wrapper class is named Foo and was generated from foo.proto):
>```
> public final class Foo {
>  private Foo() {}  // Not instantiable.
>
>  /** Returns a FileDescriptor message describing the contents of {@code foo.proto}. */
>  public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor();
>  /** Adds all extensions defined in {@code foo.proto} to the given registry. */
>  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry);
>  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry);
>
>  // (Nested classes omitted)
>}
>```

In other words, `getDescriptor()` is guaranteed to be present and will give you the message's `FileDescriptor`, from which you can obtain all of the message descriptors in the `.proto` file.

[1] https://developers.google.com/protocol-buffers/docs/reference/java-generated?hl=en#invocation


<!-- Sent from Reviewable.io -->

2022-03-21 23:09 UTC, SanjayVas requested changes
> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/490)* status: all files reviewed, 7 unresolved discussions (waiting on @chipingyeh and @stevenwarejones)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/490#-MyiiYPjE49DYCxkIFJE:-MyiiYPjE49DYCxkIFJF:b-o2rcli) (no related file):*
Would it maybe make more sense to change the design of this such that we have a static property that is a TypeRegistry for all event templates in the classpath? This way the caller need not know the Java packages for the messages, only the fully qualified protobuf names (as I believe that's what `TypeRegistry.find` uses). The caller simply needs to have the library depend on the relevant template Java classes.

---
___
*[src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventTemplateTypeRegistry.kt, line 35 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/490#-Myifk0o7emHmuteNbcA:-Myifk0o7emHmuteNbcB:b-ugj98o) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6c95b73fed8c51bde256914d3c64dcbacd2b41c0/src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventTemplateTypeRegistry.kt#L35)):*
> ```Kotlin
>   companion object {
>     /**
>      * Creates a Type Registry for all Messages in a classpath @prefix. All utilized templates
> ```

nit: `[Message]s`



_Code quote:_
```Kotlin
Messages
```
___
*[src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventTemplateTypeRegistry.kt, line 38 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/490#-MyifLeT3nQ_n3y2D7z5:-MyifLeT3nQ_n3y2D7z6:b-m8je5h) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6c95b73fed8c51bde256914d3c64dcbacd2b41c0/src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventTemplateTypeRegistry.kt#L38)):*
> ```Kotlin
>      * should be included in this classpath.
>      */
>     fun createRegistryForPackagePrefix(prefix: String): EventTemplateTypeRegistry {
> ```

Is there a particular reason this is its own class? Couldn't we just e.g. have this be a utility function in an `EventTemplates` object which returns a `TypeRegistry` instance?

Though see my other comment on overall design.



_Code quote:_
```Kotlin
EventTemplateTypeRegistry
```
___
*[src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventTemplateTypeRegistry.kt, line 38 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/490#-Myifrft7a9f-IG0cnAy:-Myifrft7a9f-IG0cnAz:b-39yco2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6c95b73fed8c51bde256914d3c64dcbacd2b41c0/src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventTemplateTypeRegistry.kt#L38)):*
> ```Kotlin
>      * should be included in this classpath.
>      */
>     fun createRegistryForPackagePrefix(prefix: String): EventTemplateTypeRegistry {
> ```

Make it clear that this is the Java package (or its ancestor) of the protobuf Message, rather than the protobuf package.

Though see my other comment on overall design.



_Code quote:_
```Kotlin
prefix
```


<!-- Sent from Reviewable.io -->

2022-03-22 15:18 UTC, robinsons reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/490)* status: all files reviewed, 7 unresolved discussions (waiting on @chipingyeh, @SanjayVas, and @stevenwarejones)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/490#-MyiiYPjE49DYCxkIFJE:-Mym79Ew9z7oy73fNCi6:bnc7yun) (no related file):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Would it maybe make more sense to change the design of this such that we have a static property that is a TypeRegistry for all event templates in the classpath? This way the caller need not know the Java packages for the messages, only the fully qualified protobuf names (as I believe that's what `TypeRegistry.find` uses). The caller simply needs to have the library depend on the relevant template Java classes.
</blockquote></details>

Yeah, that sounds like a good simplification. I can't think of a reason why the caller wouldn't want to have access to all the templates on the classpath.

---
___
*[src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventTemplateTypeRegistry.kt, line 38 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/490#-MyifLeT3nQ_n3y2D7z5:-Mym7ruo0Vtn-Bft25eL:ba44d9a) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6c95b73fed8c51bde256914d3c64dcbacd2b41c0/src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventTemplateTypeRegistry.kt#L38)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Is there a particular reason this is its own class? Couldn't we just e.g. have this be a utility function in an `EventTemplates` object which returns a `TypeRegistry` instance?

Though see my other comment on overall design.
</blockquote></details>

One of our goals was to make things as easy as possible for clients, which to me means that they deal with message descriptors as little as possible. Hence why we created the `EventTemplate` and `EventField` classes to wrap the descriptor and provide access to the underlying extension options as simple properties. This is why we decided on a wrapper class for the `TypeRegistry`.

That said, the same can be achieved with a global `EventTemplates` singleton. I would just say, let's not have it return a `TypeRegistry`, but return an `EventTemplate` instead.


<!-- Sent from Reviewable.io -->

2022-03-22 18:37 UTC, SanjayVas reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/490)* status: all files reviewed, 7 unresolved discussions (waiting on @chipingyeh, @robinsons, @SanjayVas, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventTemplateTypeRegistry.kt, line 38 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/490#-MyifLeT3nQ_n3y2D7z5:-MymulLv0uOcssWkEdIs:b-5lzjll) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6c95b73fed8c51bde256914d3c64dcbacd2b41c0/src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventTemplateTypeRegistry.kt#L38)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

One of our goals was to make things as easy as possible for clients, which to me means that they deal with message descriptors as little as possible. Hence why we created the `EventTemplate` and `EventField` classes to wrap the descriptor and provide access to the underlying extension options as simple properties. This is why we decided on a wrapper class for the `TypeRegistry`.

That said, the same can be achieved with a global `EventTemplates` singleton. I would just say, let's not have it return a `TypeRegistry`, but return an `EventTemplate` instead.
</blockquote></details>

SGTM. Thanks for the background.


<!-- Sent from Reviewable.io -->

2022-03-25 17:37 UTC, chipingyeh reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/490)* status: 3 of 7 files reviewed, 5 unresolved discussions (waiting on @robinsons, @SanjayVas, and @stevenwarejones)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/490#-MyiiYPjE49DYCxkIFJE:-Myy8cy3Ct3VjDUjnQcD:b-g9w819) (no related file):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

Yeah, that sounds like a good simplification. I can't think of a reason why the caller wouldn't want to have access to all the templates on the classpath.
</blockquote></details>

I updated the design to primarily use companion objects -- before I fix the other tests, is this what was intended?

---
___
*[src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventTemplateTypeRegistry.kt, line 38 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/490#-Myifrft7a9f-IG0cnAy:-Myy8Xa38FUQc38XR13q:b11v39b) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6c95b73fed8c51bde256914d3c64dcbacd2b41c0/src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventTemplateTypeRegistry.kt#L38)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Make it clear that this is the Java package (or its ancestor) of the protobuf Message, rather than the protobuf package.

Though see my other comment on overall design.
</blockquote></details>

Updated the comment - how does that sound?
___
*[src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventTemplateTypeRegistry.kt, line 44 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/490#-MyiX9qqCgJbKRJ4V6-5:-MyxzIDZ6sW7oKW4ffLw:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6c95b73fed8c51bde256914d3c64dcbacd2b41c0/src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventTemplateTypeRegistry.kt#L44)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

We can avoid a blind type cast if we check the type:

```
val clazz = c.load()
if (!Message::class.java.isAssignableFrom(clazz)) {
  continue
}
```

I believe that with this and my next comment combined, we can remove the `catch` blocks.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventTemplateTypeRegistry.kt, line 45 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/490#-MyiVMiJ8eFxLXpNNwrX:-MyxzJEMBvC_xXSNjF8F:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6c95b73fed8c51bde256914d3c64dcbacd2b41c0/src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventTemplateTypeRegistry.kt#L45)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

If we have to explicitly set `isAccessible` to true, IMO we shouldn't be using that constructor. The class might be designed for instantiation via some other mechanism, and calling a private constructor could leave some important initialization step undone.

I'd prefer if we used the static function `getDescriptor()`. Quoting from the protobuf docs [1]

>  ... the wrapper class itself will have the following API (assuming the wrapper class is named Foo and was generated from foo.proto):
>```
> public final class Foo {
>  private Foo() {}  // Not instantiable.
>
>  /** Returns a FileDescriptor message describing the contents of {@code foo.proto}. */
>  public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor();
>  /** Adds all extensions defined in {@code foo.proto} to the given registry. */
>  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry);
>  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry);
>
>  // (Nested classes omitted)
>}
>```

In other words, `getDescriptor()` is guaranteed to be present and will give you the message's `FileDescriptor`, from which you can obtain all of the message descriptors in the `.proto` file.

[1] https://developers.google.com/protocol-buffers/docs/reference/java-generated?hl=en#invocation
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-03-25 22:44 UTC, SanjayVas requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/490)* status: 3 of 7 files reviewed, 5 unresolved discussions (waiting on @chipingyeh, @robinsons, @SanjayVas, and @stevenwarejones)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/490#-MyiiYPjE49DYCxkIFJE:-Mz2Crlf7jmUfil4Avgc:b2mb02g) (no related file):*
<details><summary><i>Previously, chipingyeh wrote…</i></summary><blockquote>

I updated the design to primarily use companion objects -- before I fix the other tests, is this what was intended?
</blockquote></details>

Close. Rather than empty classes with companion objects, you can just declare them as singleton objects directly. See https://kotlinlang.org/docs/object-declarations.html#object-declarations-overview

e.g.

```
object EventTemplates {
  private val typeRegistry: TypeRegistry

  init {
    // Initialize the type registry with all event templates in the class path.
  }

  fun getDescriptorForType(messageName: String): Descriptor? = typeRegistry.find(messageName)
}
```

The other part of this was that it's all templates on the classpath, not just those under a specific Java package. Also note that we want to get the descriptor given a fully-qualified protobuf message name, not the fully-qualified Java class name.

---


<!-- Sent from Reviewable.io -->

2022-03-28 14:58 UTC, chipingyeh reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/490)* status: 3 of 7 files reviewed, 5 unresolved discussions (waiting on @robinsons, @SanjayVas, and @stevenwarejones)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/490#-MyiiYPjE49DYCxkIFJE:-MzG04_94w6o_vEKXda5:b-b4v3su) (no related file):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Close. Rather than empty classes with companion objects, you can just declare them as singleton objects directly. See https://kotlinlang.org/docs/object-declarations.html#object-declarations-overview

e.g.

```
object EventTemplates {
  private val typeRegistry: TypeRegistry

  init {
    // Initialize the type registry with all event templates in the class path.
  }

  fun getDescriptorForType(messageName: String): Descriptor? = typeRegistry.find(messageName)
}
```

The other part of this was that it's all templates on the classpath, not just those under a specific Java package. Also note that we want to get the descriptor given a fully-qualified protobuf message name, not the fully-qualified Java class name.
</blockquote></details>

When you mention "classpath" do you mean the classpath of the executing file or one that is specified by the caller? There's several methods in Guava that take in a specific package name, but the classpath methods search only on the current classpath (which is likely different from that of the templates). Additionally, what's the distinction between the fully-qualified protobuf message name and fully-qualified Java class name?

---


<!-- Sent from Reviewable.io -->

2022-03-28 18:32 UTC, SanjayVas requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/490)* status: 3 of 7 files reviewed, 5 unresolved discussions (waiting on @chipingyeh, @robinsons, @SanjayVas, and @stevenwarejones)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/490#-MyiiYPjE49DYCxkIFJE:-MzGkvD80359kOxPT_ov:beg37od) (no related file):*
Class path here meaning current class path, which should be the same one the templates are in if they are compile-time dependencies. This is the class path that can be obtained from the system class loader. (Note that I'm referring to the Java concept of a class path, not necessarily the Guava `ClassPath` class). Basically what I'm suggesting is to not limit your search to a specific Java package, but rather look at all available `Message`s with the event template marker annotation.

> Additionally, what's the distinction between the fully-qualified protobuf message name and fully-qualified Java class name?

The former has a package name that comes from the `package` specifier in the protobuf definition. The latter has a package name that comes from the `java_package` option in the protobuf definition. For example, we use `wfa.measurement` as the top-level protobuf package for our messages, but `org.wfanet.measurement` for the top-level Java package. See https://developers.google.com/protocol-buffers/docs/proto3#packages

---


<!-- Sent from Reviewable.io -->

2022-03-28 21:25 UTC, chipingyeh reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/490)* status: 2 of 14 files reviewed, 5 unresolved discussions (waiting on @robinsons, @SanjayVas, and @stevenwarejones)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/490#-MyiiYPjE49DYCxkIFJE:-MzH4AwS7coenNE5CeZA:bbzi1hw) (no related file):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Class path here meaning current class path, which should be the same one the templates are in if they are compile-time dependencies. This is the class path that can be obtained from the system class loader. (Note that I'm referring to the Java concept of a class path, not necessarily the Guava `ClassPath` class). Basically what I'm suggesting is to not limit your search to a specific Java package, but rather look at all available `Message`s with the event template marker annotation.

> Additionally, what's the distinction between the fully-qualified protobuf message name and fully-qualified Java class name?

The former has a package name that comes from the `package` specifier in the protobuf definition. The latter has a package name that comes from the `java_package` option in the protobuf definition. For example, we use `wfa.measurement` as the top-level protobuf package for our messages, but `org.wfanet.measurement` for the top-level Java package. See https://developers.google.com/protocol-buffers/docs/proto3#packages
</blockquote></details>

Thanks the explanation, it makes sense now -- updated the logic as well as return value for `getEventTemplateForType` as discussed below. If that looks good I can go ahead and delete the original `EventTemplateTypeRegistry` files and fix the integration test after the next review. Note that I had to slightly modify the test since there's no functions for accessing non-`EventField` fields in an EventTemplate atm.

---


<!-- Sent from Reviewable.io -->

2022-03-28 23:46 UTC, SanjayVas requested changes
> Reviewed 3 of 12 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/490)* status: 5 of 14 files reviewed, 9 unresolved discussions (waiting on @chipingyeh, @robinsons, @SanjayVas, and @stevenwarejones)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/490#-MyiiYPjE49DYCxkIFJE:-MzHv32s3u00XmbG8jT9:b-fstn87) (no related file):*
<details><summary><i>Previously, chipingyeh wrote…</i></summary><blockquote>

Thanks the explanation, it makes sense now -- updated the logic as well as return value for `getEventTemplateForType` as discussed below. If that looks good I can go ahead and delete the original `EventTemplateTypeRegistry` files and fix the integration test after the next review. Note that I had to slightly modify the test since there's no functions for accessing non-`EventField` fields in an EventTemplate atm.
</blockquote></details>

Yeah, this approach is looking better. Left some minor comments.

---
___
*[src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventTemplates.kt, line 29 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/490#-MzHsh_HEuTkLR7Ug56r:-MzHsh_HEuTkLR7Ug56s:boz22yg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c4b404b24e4ac1328c4e631fcf42b5f31076f410/src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventTemplates.kt#L29)):*
> ```Kotlin
>   }
> 
>   private fun initializeTypeRegistry(): TypeRegistry {
> ```

nit: just have this be the body of the `init` block. This way you're not calling a method that technically has access to members before they're initialized.



_Code quote:_
```Kotlin
private fun initializeTypeRegistry
```
___
*[src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventTemplates.kt, line 43 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/490#-MzHrYpm4IGvO-hOspeW:-MzHrYpm4IGvO-hOspeX:b-6gfcad) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c4b404b24e4ac1328c4e631fcf42b5f31076f410/src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventTemplates.kt#L43)):*
> ```Kotlin
>           registryBuilder.add(descriptor)
>         }
>       } catch (e: Exception) {} catch (e: Error) {}
> ```

Don't just ignore errors. Our default so far has been to just let these propagate up.



_Code quote:_
```Kotlin
catch (e: Exception) {} catch (e: Error) {}
```
___
*[src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventTemplates.kt, line 54 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/490#-MzHtU2U-wCkZ9swSnOR:-MzHtU2U-wCkZ9swSnOS:b-ad4dqb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c4b404b24e4ac1328c4e631fcf42b5f31076f410/src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventTemplates.kt#L54)):*
> ```Kotlin
>    */
>   fun getEventTemplateForType(messageName: String): EventTemplate? {
>     return EventTemplate(typeRegistry.find(messageName))
> ```

AFAICT this doesn't handle `find` returning `null`.

I assume you want something like:

```
val descriptor = typeRegistry.find(messageName)
if (descriptor == null) {
  return null
}

return EventTemplate(descriptor)
```
___
*[src/test/kotlin/org/wfanet/measurement/api/v2alpha/EventTemplatesTest.kt, line 22 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/490#-MzHulHh-_VR-n52AmuU:-MzHulHh-_VR-n52AmuV:bktg8kq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c4b404b24e4ac1328c4e631fcf42b5f31076f410/src/test/kotlin/org/wfanet/measurement/api/v2alpha/EventTemplatesTest.kt#L22)):*
> ```Kotlin
> import org.junit.runners.JUnit4
> 
> private const val CLASS_PATH = "wfa.measurement.api.v2alpha.event_templates.testing"
> ```

Rename this as it's rather confusing. This isn't a class path at all.

Perhaps `PROTO_PACKAGE`?



_Code quote:_
```Kotlin
CLASS_PATH
```


<!-- Sent from Reviewable.io -->

2022-03-29 20:24 UTC, chipingyeh reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/490)* status: 2 of 16 files reviewed, 7 unresolved discussions (waiting on @chipingyeh, @robinsons, @SanjayVas, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventTemplates.kt, line 43 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/490#-MzHrYpm4IGvO-hOspeW:-MzLBn0l8Uh4GbfJGN4M:b-32jom6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c4b404b24e4ac1328c4e631fcf42b5f31076f410/src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventTemplates.kt#L43)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Don't just ignore errors. Our default so far has been to just let these propagate up.
</blockquote></details>

This was to originally catch a `java.lang.NoClassDefFoundError: META-INF/versions/9/module-info is not a class because access_flag ACC_MODULE is set` error that was being thrown whenever `c.load()` was called while iterating through the classes. There was an additional `UnsupportedClassVersionError` during the integration test. I've updated it to just catch the two `Errors` that show up in a normal run to allow the loop to complete successfully.
___
*[src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventTemplates.kt, line 54 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/490#-MzHtU2U-wCkZ9swSnOR:-MzLCHkA3rvaUS8BMuGK:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c4b404b24e4ac1328c4e631fcf42b5f31076f410/src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventTemplates.kt#L54)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

AFAICT this doesn't handle `find` returning `null`.

I assume you want something like:

```
val descriptor = typeRegistry.find(messageName)
if (descriptor == null) {
  return null
}

return EventTemplate(descriptor)
```
</blockquote></details>

Done.
___
*[src/test/kotlin/org/wfanet/measurement/api/v2alpha/EventTemplatesTest.kt, line 22 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/490#-MzHulHh-_VR-n52AmuU:-MzLCnzPDj66NvXETfUo:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c4b404b24e4ac1328c4e631fcf42b5f31076f410/src/test/kotlin/org/wfanet/measurement/api/v2alpha/EventTemplatesTest.kt#L22)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Rename this as it's rather confusing. This isn't a class path at all.

Perhaps `PROTO_PACKAGE`?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-03-29 21:41 UTC, SanjayVas requested changes
> Reviewed 1 of 8 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/490)* status: 3 of 16 files reviewed, 7 unresolved discussions (waiting on @chipingyeh, @robinsons, @SanjayVas, and @stevenwarejones)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/490#-MzMaTaL6Jj3S6oI4rkb:-MzMaTaM4ZDQsBZmkuZl:b-gqx4ov) (no related file):*
My apologies. Apparently Guava's ClassPath is no longer recommended by the Guava authors. They specifically [recommend using ClassGraph instead](https://guava.dev/releases/snapshot-jre/api/docs/com/google/common/reflect/ClassPath.html). I'm fine following this recommendation given that it seems to be a vetted dependency.

ClassGraph does have a nicer API for [finding all classes that extend a specific class](https://github.com/classgraph/classgraph/wiki/Code-examples#get-class-references-for-subclasses-of-comxyzcontrol).

---
___
*[src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventTemplates.kt, line 43 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/490#-MzHrYpm4IGvO-hOspeW:-MzMY26SAjWuoJtz2kp1:bhjt2cm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c4b404b24e4ac1328c4e631fcf42b5f31076f410/src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventTemplates.kt#L43)):*
<details><summary><i>Previously, chipingyeh wrote…</i></summary><blockquote>

This was to originally catch a `java.lang.NoClassDefFoundError: META-INF/versions/9/module-info is not a class because access_flag ACC_MODULE is set` error that was being thrown whenever `c.load()` was called while iterating through the classes. There was an additional `UnsupportedClassVersionError` during the integration test. I've updated it to just catch the two `Errors` that show up in a normal run to allow the loop to complete successfully.
</blockquote></details>

This still has`catch (e: Exception) {}`.

I'd like to avoid this if possible. Perhaps a blacklist (e.g. known problematic class names) rather than swallowing errors? Otherwise, we won't know when we get e.g. a NoClassDefFoundError when it's not expected. See above note on whether we should be using a different approach altogether to potentially avoid issues like this (which I believe is related to attempting to load classes from the module path).


<!-- Sent from Reviewable.io -->

2022-03-30 20:58 UTC, chipingyeh reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/490)* status: 3 of 16 files reviewed, 7 unresolved discussions (waiting on @robinsons, @SanjayVas, and @stevenwarejones)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/490#-MzMaTaL6Jj3S6oI4rkb:-MzRZ4MJETyyy6gNVl4S:b-nq7hia) (no related file):*
> finding all classes that extend a specific class
I haven't been able to get ClassGraph to detect the test templates despite doing a simple `ClassGraph().enableAllInfo().scan()`. Is it alright if I add a TODO here and focus on some of the other features of M2 first?

---
___
*[src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventTemplates.kt, line 43 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/490#-MzHrYpm4IGvO-hOspeW:-MzRbMk4-SnJNBC6x6BD:bdfwji6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c4b404b24e4ac1328c4e631fcf42b5f31076f410/src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventTemplates.kt#L43)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This still has`catch (e: Exception) {}`.

I'd like to avoid this if possible. Perhaps a blacklist (e.g. known problematic class names) rather than swallowing errors? Otherwise, we won't know when we get e.g. a NoClassDefFoundError when it's not expected. See above note on whether we should be using a different approach altogether to potentially avoid issues like this (which I believe is related to attempting to load classes from the module path).
</blockquote></details>

There are a lot of classes which currently trigger an Exception or Error at the moment, possibly too many to list -- I've attached a partial screenshot for reference. Is there another approach that would work here? I'm also okay adding a TODO to address this in the future.
![image.png](https://files.reviewableusercontent.io/images/reviewable/92889345/qwoSr8wabKa3FSYULhjoFztU/image.png)


<!-- Sent from Reviewable.io -->

2022-04-01 21:09 UTC, chipingyeh reviewed
Going to go ahead and merge since the original comments were made in a file that is now deleted.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/490#-:-MzaxWUS6DUKjZOVh_Ss:bgeajci)* status: 12 of 16 files reviewed, 2 unresolved discussions (waiting on @chipingyeh, @robinsons, @SanjayVas, and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2022-04-01 21:09 UTC, chipingyeh reviewed
> Reviewed 4 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/490)* status: all files reviewed, 2 unresolved discussions (waiting on @robinsons, @SanjayVas, and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2022-04-01 21:10 UTC, chipingyeh reviewed
> Dismissed @robinsons from 2 discussions.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/490)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @robinsons, @SanjayVas, and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2022-04-01 21:11 UTC, chipingyeh reviewed
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/490)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @robinsons, @SanjayVas, and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2022-04-01 21:51 UTC, robinsons approved these changes
> Reviewed 2 of 12 files at r3, 2 of 4 files at r4, 7 of 8 files at r5, 1 of 1 files at r6, 4 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/490)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2022-04-01 21:56 UTC, chipingyeh reviewed
> Reviewed 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/490)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2022-04-01 22:01 UTC, merged