Add event filtering
world-federation-of-advertisers/cross-media-measurement pull request #491
Opened 2022-03-22 16:35 UTC by duliomatos1

Creates an event filtering library that will match a CEL expression to an event Message
* Event Message's are defined as proto's that have all valid event templates as optional fields
* The name of the template field, within the event message, is used for reference by variables in the CEL expression
* The EventFilter only needs a default Event Message to initialize the CEL environment, and compile the expression

2022-03-22 19:06 UTC, SanjayVas requested changes
> Reviewed 3 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/491)* status: 3 of 10 files reviewed, 9 unresolved discussions (waiting on @chipingyeh, @duliomatos1, @stevenwarejones, and @uakyol)

___
*[src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/filter/EventFilter.kt, line 15 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/491#-MymzG8B395Uc2hlTfXl:-MymzG8B395Uc2hlTfXm:biy2ulc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/75ff82bec8e617ecb21361b8139cb8e30ecaca62/src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/filter/EventFilter.kt#L15)):*
> ```Kotlin
> // limitations under the License.
> 
> package org.wfanet.measurement.eventdataprovider.eventfiltration.filter
> ```

Do we need a separate filter subpackage? Just trying to see if this package hierarchy can be flattened.



_Code quote:_
```Kotlin
filter
```
___
*[src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/filter/EventFilter.kt, line 36 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/491#-Myn-Zsf0aSHK_NU59Mb:-Myn-Zsf0aSHK_NU59Mc:b56u930) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/75ff82bec8e617ecb21361b8139cb8e30ecaca62/src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/filter/EventFilter.kt#L36)):*
> ```Kotlin
>   private val program: Program
>   init {
>     val env = envForEventMessage(eventMessage)
> ```

Don't call instance methods from init. Any function you call from init should be static (e.g. in companion object).



_Code quote:_
```Kotlin
envForEventMessage(eventMessage)
```
___
*[src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/filter/EventFilter.kt, line 41 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/491#-MymzZnyDqMDgdjMdYxe:-MymzZnyDqMDgdjMdYxf:b-fybx21) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/75ff82bec8e617ecb21361b8139cb8e30ecaca62/src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/filter/EventFilter.kt#L41)):*
> ```Kotlin
>   }
> 
>   private fun tryCompile(env: Env, celExpr: String): Ast {
> ```

`try` prefix implies there's a regular `compile` that throws an exception and that this is a version that doesn't.



_Code quote:_
```Kotlin
tryCompile
```
___
*[src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/filter/EventFilter.kt, line 46 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/491#-Myn-6Qh-4tob2mu4GI5:-Myn-6Qh-4tob2mu4GI6:b-2jo200) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/75ff82bec8e617ecb21361b8139cb8e30ecaca62/src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/filter/EventFilter.kt#L46)):*
> ```Kotlin
>       astAndIssues = env.compile(celExpr)
>     } catch (e: Exception) {
>       throw EventFilterException(EventFilterException.Code.INVALID_CEL_EXPRESSION)
> ```

Document what exceptions are thrown under what conditions



_Code quote:_
```Kotlin
EventFilterException
```
___
*[src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/filter/EventFilter.kt, line 57 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/491#-Myn-PJX1gLQvrAuMOso:-Myn-PJX1gLQvrAuMOsp:bz9fju5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/75ff82bec8e617ecb21361b8139cb8e30ecaca62/src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/filter/EventFilter.kt#L57)):*
> ```Kotlin
>   }
> 
>   private fun envForEventMessage(eventMessage: Message): Env {
> ```

https://developer.android.com/kotlin/style-guide#function_names



_Code quote:_
```Kotlin
envForEventMessage
```
___
*[src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/filter/EventFilter.kt, line 78 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/491#-Myn-x_b9fjnIXwBqtJw:-Myn-x_c2EbHguV81nTL:b-ozgbhj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/75ff82bec8e617ecb21361b8139cb8e30ecaca62/src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/filter/EventFilter.kt#L78)):*
> ```Kotlin
> 
>   fun matches(event: Message): Boolean {
>     val variables = event.allFields.entries.associate { it.key.name to it.value }
> ```

Specify types explicitly wherever it's not obvious. e.g. it's not immediately obvious here what the types of `variables`, `result`, and `value` should be.


<!-- Sent from Reviewable.io -->

2022-03-22 19:08 UTC, SanjayVas reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/491)* status: 3 of 10 files reviewed, 9 unresolved discussions (waiting on @chipingyeh, @duliomatos1, @stevenwarejones, and @uakyol)

___
*[src/main/proto/wfa/measurement/api/v2alpha/event_templates/testing/test_banner_template.proto, line 39 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/491#-MymUehM0qHsO1wFx9T0:-Myn0Uen7riv089t4yb5:b-jyowfd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/75ff82bec8e617ecb21361b8139cb8e30ecaca62/src/main/proto/wfa/measurement/api/v2alpha/event_templates/testing/test_banner_template.proto#L39)):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

I think @uakyol had another name for this test template, I'll fix it
</blockquote></details>

You probably want to set your disposition for this comment to "Working" rather than "Blocking". Similarly, don't forget to flip it to "Resolved" when you've actually done it. The latter part applies for any comment: make sure to set as "Resolved" when you're done, as that's what lets reviewers know that it's ready to be looked at again.


<!-- Sent from Reviewable.io -->

2022-03-23 14:10 UTC, duliomatos1 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/491)* status: 3 of 10 files reviewed, 9 unresolved discussions (waiting on @chipingyeh, @SanjayVas, @stevenwarejones, and @uakyol)

___
*[src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/filter/EventFilter.kt, line 15 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/491#-MymzG8B395Uc2hlTfXl:-Myr5P-f7fCdZUXf-zH1:b-hzwfvo) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/75ff82bec8e617ecb21361b8139cb8e30ecaca62/src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/filter/EventFilter.kt#L15)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Do we need a separate filter subpackage? Just trying to see if this package hierarchy can be flattened.
</blockquote></details>

we don't need really, I agree with you
___
*[src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/filter/EventFilter.kt, line 36 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/491#-Myn-Zsf0aSHK_NU59Mb:-Myr5Y0P7D5bkq_CMqG1:bf9jpon) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/75ff82bec8e617ecb21361b8139cb8e30ecaca62/src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/filter/EventFilter.kt#L36)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Don't call instance methods from init. Any function you call from init should be static (e.g. in companion object).
</blockquote></details>

I shall move those methods to the companion object
___
*[src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/filter/EventFilter.kt, line 41 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/491#-MymzZnyDqMDgdjMdYxe:-Myr5g6x21t0IamtE-Zs:bny4g66) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/75ff82bec8e617ecb21361b8139cb8e30ecaca62/src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/filter/EventFilter.kt#L41)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

`try` prefix implies there's a regular `compile` that throws an exception and that this is a version that doesn't.
</blockquote></details>

maybe just `compileExpr`?
___
*[src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/filter/EventFilter.kt, line 46 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/491#-Myn-6Qh-4tob2mu4GI5:-Myr5ezHCvZJJ3qCFref:bb7oryy) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/75ff82bec8e617ecb21361b8139cb8e30ecaca62/src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/filter/EventFilter.kt#L46)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Document what exceptions are thrown under what conditions
</blockquote></details>

sure
___
*[src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/filter/EventFilter.kt, line 57 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/491#-Myn-PJX1gLQvrAuMOso:-Myr6A942PKwX3_yGvhS:b-z8yavh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/75ff82bec8e617ecb21361b8139cb8e30ecaca62/src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/filter/EventFilter.kt#L57)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

https://developer.android.com/kotlin/style-guide#function_names
</blockquote></details>

could be just `createEnv()`
___
*[src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/filter/EventFilter.kt, line 78 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/491#-Myn-x_b9fjnIXwBqtJw:-Myr5wuv-zQjhe25Oc3g:b-wtspaw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/75ff82bec8e617ecb21361b8139cb8e30ecaca62/src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/filter/EventFilter.kt#L78)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Specify types explicitly wherever it's not obvious. e.g. it's not immediately obvious here what the types of `variables`, `result`, and `value` should be.
</blockquote></details>

sure thing


<!-- Sent from Reviewable.io -->

2022-03-23 17:11 UTC, uakyol requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/491)* status: 3 of 10 files reviewed, 10 unresolved discussions (waiting on @chipingyeh, @duliomatos1, @SanjayVas, @stevenwarejones, and @uakyol)

___
*[src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/filter/EventFilter.kt, line 15 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/491#-MymzG8B395Uc2hlTfXl:-MyoVEHm8WnMFyBMN2J7:b-bild2h) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/75ff82bec8e617ecb21361b8139cb8e30ecaca62/src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/filter/EventFilter.kt#L15)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Do we need a separate filter subpackage? Just trying to see if this package hierarchy can be flattened.
</blockquote></details>

I agree with Sanjay. My thinking is that :
          - we should have eventfiltration/validation (which we have) that has the validation code -> This is the current state.
          - we should NOT have eventfiltration/filter . The filtration code should live under eventfiltration/    directly.
___
*[src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/filter/EventFilter.kt, line 33 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/491#-MyoW-7zDGqOnlYFPyh-:-MyoW-7zDGqOnlYFPyh0:bcj3bsf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/75ff82bec8e617ecb21361b8139cb8e30ecaca62/src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/filter/EventFilter.kt#L33)):*
> ```Kotlin
>  * `event_annotations.proto`.
>  */
> class EventFilter(celExpr: String, eventMessage: Message) {
> ```

Dulio, I think we made a mistake designing this together with the validator. A better way this works is that we don't call compile twice : once for validation and second time here. 

I see 2 ways of doing this:

1) Add a  "fun compile(celExpression: String, env: Env) : Program" function to Validator and call it from here. This way, this EventFilter will throw not just INVALID_CEL_EXPRESSION but all the detailed errors you wrote in validator which is much better

2) Add compile function to validator (same as #1) and then make this EventFilter stateless -  you can use the same pattern in the validator - and it should just have the function matches(program, event) which takes in the program already compiled from the validator. 

p.s. environment creation function you wrote is great. Perhaps even a better way is to have "fun compileWithEventMessage(celExpression: String, eventMessage: Message) : Program" in the Validator. - I would prefer this.

@sanjayvas wdyt about adding  "compile" to the validator? 


<!-- Sent from Reviewable.io -->

2022-03-23 17:37 UTC, SanjayVas requested changes
> Reviewed 1 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/491)* status: 4 of 10 files reviewed, 10 unresolved discussions (waiting on @chipingyeh, @duliomatos1, @SanjayVas, @stevenwarejones, and @uakyol)

___
*[src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/filter/EventFilter.kt, line 15 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/491#-MymzG8B395Uc2hlTfXl:-MyrpoK18MR3UNUvlHfT:b-mhkusc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/75ff82bec8e617ecb21361b8139cb8e30ecaca62/src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/filter/EventFilter.kt#L15)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

I agree with Sanjay. My thinking is that :
          - we should have eventfiltration/validation (which we have) that has the validation code -> This is the current state.
          - we should NOT have eventfiltration/filter . The filtration code should live under eventfiltration/    directly.


</blockquote></details>

As long as the package hierarchy follows one of two patterns:
1. Parent package can depend on child packages but not the other way around. Child packages should not be accessible outside of the parent package.
2. Child packages can depend on the parent package, but not the other way around. This is the more common pattern we follow. See the `storage` package in common-jvm for a clear example.
___
*[src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/filter/EventFilter.kt, line 33 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/491#-MyoW-7zDGqOnlYFPyh-:-MyrpUEI2yU7CEtb29D_:b-jfnxxt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/75ff82bec8e617ecb21361b8139cb8e30ecaca62/src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/filter/EventFilter.kt#L33)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

Dulio, I think we made a mistake designing this together with the validator. A better way this works is that we don't call compile twice : once for validation and second time here. 

I see 2 ways of doing this:

1) Add a  "fun compile(celExpression: String, env: Env) : Program" function to Validator and call it from here. This way, this EventFilter will throw not just INVALID_CEL_EXPRESSION but all the detailed errors you wrote in validator which is much better

2) Add compile function to validator (same as #1) and then make this EventFilter stateless -  you can use the same pattern in the validator - and it should just have the function matches(program, event) which takes in the program already compiled from the validator. 

p.s. environment creation function you wrote is great. Perhaps even a better way is to have "fun compileWithEventMessage(celExpression: String, eventMessage: Message) : Program" in the Validator. - I would prefer this.

@sanjayvas wdyt about adding  "compile" to the validator? 
</blockquote></details>

As long as the dependencies between packages follow a clear pattern (see above), I don't have a strong opinion.


<!-- Sent from Reviewable.io -->

2022-03-23 18:03 UTC, uakyol commented
___
*[src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/filter/EventFilter.kt, line 33 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/491#-MyoW-7zDGqOnlYFPyh-:-MyrwbZu4pxjOPawqsrH:b-jqfpch) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/75ff82bec8e617ecb21361b8139cb8e30ecaca62/src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/filter/EventFilter.kt#L33)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

As long as the dependencies between packages follow a clear pattern (see above), I don't have a strong opinion.
</blockquote></details>

ok, this would mean we will go with "1. Parent package can depend on child packages but not the other way around. Child packages should not be accessible outside of the parent package."

@duliomatos1 wdyt?


<!-- Sent from Reviewable.io -->

2022-03-23 20:10 UTC, uakyol commented
___
*[src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/filter/EventFilter.kt, line 33 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/491#-MyoW-7zDGqOnlYFPyh-:-MysO_prEQryb5_C10LJ:bl6xz78) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/75ff82bec8e617ecb21361b8139cb8e30ecaca62/src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/filter/EventFilter.kt#L33)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

ok, this would mean we will go with "1. Parent package can depend on child packages but not the other way around. Child packages should not be accessible outside of the parent package."

@duliomatos1 wdyt?
</blockquote></details>

just to clarify my point about environment creation function:  I meant you can move it in to the validator and call it privately from "fun compileWithEventMessage(celExpression: String, eventMessage: Message) : Program"


<!-- Sent from Reviewable.io -->

2022-03-24 16:51 UTC, duliomatos1 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/491)* status: 4 of 10 files reviewed, 8 unresolved discussions (waiting on @chipingyeh, @duliomatos1, @SanjayVas, @stevenwarejones, and @uakyol)

___
*[src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/filter/EventFilter.kt, line 33 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/491#-MyoW-7zDGqOnlYFPyh-:-MywoXFJ851cCalA7_uk:b-8zqq68) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/75ff82bec8e617ecb21361b8139cb8e30ecaca62/src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/filter/EventFilter.kt#L33)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

just to clarify my point about environment creation function:  I meant you can move it in to the validator and call it privately from "fun compileWithEventMessage(celExpression: String, eventMessage: Message) : Program"
</blockquote></details>

cool. Yeah, it makes much more sense to have the filter take the output from validation, and move the compile function there as `compileWithEventMessage()`, I'll follow this path


<!-- Sent from Reviewable.io -->

2022-03-25 20:08 UTC, stevenwarejones requested changes
> Reviewed 9 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/491)* status: 9 of 10 files reviewed, 15 unresolved discussions (waiting on @chipingyeh, @duliomatos1, @SanjayVas, and @uakyol)

___
*[src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/filter/EventFilter.kt, line 41 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/491#-MymzZnyDqMDgdjMdYxe:-Mz1eSsxEWnAKDkASgBs:bn10fjh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/75ff82bec8e617ecb21361b8139cb8e30ecaca62/src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/filter/EventFilter.kt#L41)):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

maybe just `compileExpr`?
</blockquote></details>

compileFromCel?
___
*[src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/filter/EventFilter.kt, line 78 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/491#-Myn-x_b9fjnIXwBqtJw:-Mz1ejlwEqURHvxFp94f:b32v57) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/75ff82bec8e617ecb21361b8139cb8e30ecaca62/src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/filter/EventFilter.kt#L78)):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

sure thing
</blockquote></details>

+1
___
*[src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/filter/EventFilterException.kt, line 27 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/491#-Mz1evuI4_C37GXaZh2l:-Mz1evuI4_C37GXaZh2m:bm43tp4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/75ff82bec8e617ecb21361b8139cb8e30ecaca62/src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/filter/EventFilterException.kt#L27)):*
> ```Kotlin
> 
>    /** Filter evaluation is not a boolean */
>    INVALID_EVALUATION_RESULT,
> ```

how about just `INVALID_RESULT`?
___
*[src/test/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/filter/EventFilterTest.kt, line 31 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/491#-Mz1fuwQ8K9_LaDZTZSo:-Mz1fuwQ8K9_LaDZTZSp:b-pqifj5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/75ff82bec8e617ecb21361b8139cb8e30ecaca62/src/test/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/filter/EventFilterTest.kt#L31)):*
> ```Kotlin
> class EventFilterTest {
>   private fun exampleEventWithAge(): Message {
>     val eventBuilder = TestEvent.newBuilder()
> ```

testEvent {}
___
*[src/test/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/filter/EventFilterTest.kt, line 32 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/491#-Mz1fJ7VBIwD3lb0Km0p:-Mz1fJ7VBIwD3lb0Km0q:b-huerhr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/75ff82bec8e617ecb21361b8139cb8e30ecaca62/src/test/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/filter/EventFilterTest.kt#L32)):*
> ```Kotlin
>   private fun exampleEventWithAge(): Message {
>     val eventBuilder = TestEvent.newBuilder()
>     val videoAd =
> ```

```
val videoAd = testVideoTemplate {
 age = ageRange{ value =  AgeRange.Value.AGE_18_TO_24}
}
```
___
*[src/test/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/filter/EventFilterTest.kt, line 72 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/491#-Mz1fikH17qON-2pd1l9:-Mz1fikH17qON-2pd1lA:b-pqifj5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/75ff82bec8e617ecb21361b8139cb8e30ecaca62/src/test/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/filter/EventFilterTest.kt#L72)):*
> ```Kotlin
>       EventFilter(
>         " video_ad.age.value == 1",
>         TestEvent.getDefaultInstance(),
> ```

testEvent {}
___
*[src/test/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/filter/EventFilterTest.kt, line 74 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/491#-Mz1fpa2B6dzx56Ct8En:-Mz1fpa2B6dzx56Ct8Eo:b-pqifj5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/75ff82bec8e617ecb21361b8139cb8e30ecaca62/src/test/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/filter/EventFilterTest.kt#L74)):*
> ```Kotlin
>         TestEvent.getDefaultInstance(),
>       )
>     val event = TestEvent.newBuilder().build()
> ```

testEvent {}
___
*[src/test/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/filter/EventFilterTest.kt, line 83 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/491#-Mz1fk5B2P7nx6QMADci:-Mz1fk5B2P7nx6QMADcj:b-7ropln) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/75ff82bec8e617ecb21361b8139cb8e30ecaca62/src/test/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/filter/EventFilterTest.kt#L83)):*
> ```Kotlin
>       EventFilter(
>         "+",
>         TestEvent.getDefaultInstance(),
> ```

ditto
___
*[src/test/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/filter/EventFilterTest.kt, line 93 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/491#-Mz1fdqj21pk2e9bDTzZ:-Mz1fdqj21pk2e9bDTz_:b-r86q51) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/75ff82bec8e617ecb21361b8139cb8e30ecaca62/src/test/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/filter/EventFilterTest.kt#L93)):*
> ```Kotlin
>       EventFilter(
>         "video_ad.age.value",
>         TestEvent.getDefaultInstance(),
> ```

`testEvent {}`


<!-- Sent from Reviewable.io -->

2022-04-01 15:09 UTC, duliomatos1 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/491)* status: 1 of 18 files reviewed, 13 unresolved discussions (waiting on @chipingyeh, @duliomatos1, @SanjayVas, @stevenwarejones, and @uakyol)

___
*[src/main/proto/wfa/measurement/api/v2alpha/event_templates/testing/test_banner_template.proto, line 39 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/491#-MymUehM0qHsO1wFx9T0:-Mz_eeod758hqKPzPDZd:bb7f2mf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/75ff82bec8e617ecb21361b8139cb8e30ecaca62/src/main/proto/wfa/measurement/api/v2alpha/event_templates/testing/test_banner_template.proto#L39)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

You probably want to set your disposition for this comment to "Working" rather than "Blocking". Similarly, don't forget to flip it to "Resolved" when you've actually done it. The latter part applies for any comment: make sure to set as "Resolved" when you're done, as that's what lets reviewers know that it's ready to be looked at again.
</blockquote></details>

done
___
*[src/main/proto/wfa/measurement/api/v2alpha/event_templates/testing/test_event.proto, line 17 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/491#-MymV-t71s1lbd8DEvTI:-Mz_elC67Tg2vz_DVysw:b4iap4k) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/75ff82bec8e617ecb21361b8139cb8e30ecaca62/src/main/proto/wfa/measurement/api/v2alpha/event_templates/testing/test_event.proto#L17)):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

I understand now that we should remove this `org.` prefix. I'll remove from the Test Templates as well
</blockquote></details>

done. Removed from `java_package`
___
*[src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/filter/EventFilter.kt, line 41 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/491#-MymzZnyDqMDgdjMdYxe:-Mz_P8y7AwaqUDmF7n_O:bycoosx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/75ff82bec8e617ecb21361b8139cb8e30ecaca62/src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/filter/EventFilter.kt#L41)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

compileFromCel?
</blockquote></details>

ended up removing this fun by making `EventFilter` stateless. It has now only `compileProgram(celExpr: String, defaultEventMessage: Message): Program` and `fun matches(event: Message, program: Program): Boolean`
___
*[src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/filter/EventFilterException.kt, line 27 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/491#-Mz1evuI4_C37GXaZh2l:-Mz_eSHTD8oGZrAuNM0P:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/75ff82bec8e617ecb21361b8139cb8e30ecaca62/src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/filter/EventFilterException.kt#L27)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

how about just `INVALID_RESULT`?
</blockquote></details>

Done.
___
*[src/test/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/filter/EventFilterTest.kt, line 31 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/491#-Mz1fuwQ8K9_LaDZTZSo:-Mz_ez_KEBNsdZKuh3Lu:b-5a02gi) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/75ff82bec8e617ecb21361b8139cb8e30ecaca62/src/test/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/filter/EventFilterTest.kt#L31)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

testEvent {}
</blockquote></details>

How do I enabled the proto builders DSL? Is there a target to build it?


<!-- Sent from Reviewable.io -->

2022-04-01 15:31 UTC, duliomatos1 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/491)* status: 1 of 18 files reviewed, 14 unresolved discussions (waiting on @chipingyeh, @duliomatos1, @SanjayVas, @stevenwarejones, and @uakyol)

___
*[src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt, line 129 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/491#-Mz_jzcx4-0XSmuKW1bD:-Mz_jzcx4-0XSmuKW1bE:by3z87m) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/20aad2319c4f03cbc1ad69172db94520c7aa0ee2/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L129)):*
> ```Kotlin
>         createEventGroupRequest {
>           parent = edpData.name
>           eventGroup =
> ```

I may be running an older version of ktfmt (0.29) locally, let me check


<!-- Sent from Reviewable.io -->

2022-04-01 16:33 UTC, stevenwarejones requested changes
> Reviewed 12 of 17 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/491)* status: 13 of 18 files reviewed, 13 unresolved discussions (waiting on @chipingyeh, @duliomatos1, @SanjayVas, @stevenwarejones, and @uakyol)

___
*[src/test/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/filter/EventFilterTest.kt, line 31 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/491#-Mz1fuwQ8K9_LaDZTZSo:-Mz_yIx2-D9Etd24W_Ib:b-2rplnp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/75ff82bec8e617ecb21361b8139cb8e30ecaca62/src/test/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/filter/EventFilterTest.kt#L31)):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

How do I enabled the proto builders DSL? Is there a target to build it?
</blockquote></details>

import org.wfanet.measurement.api.v2alpha.event_templates.testing.testEvent



_Code quote:_
```Kotlin
import org.wfanet.measurement.api.v2alpha.event_templates.testing.TestEvent
```


<!-- Sent from Reviewable.io -->

2022-04-01 16:41 UTC, SanjayVas requested changes
> Reviewed 9 of 17 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/491)* status: 14 of 18 files reviewed, 18 unresolved discussions (waiting on @chipingyeh, @duliomatos1, @SanjayVas, @stevenwarejones, and @uakyol)

___
*[src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/EventFilter.kt, line 25 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/491#-Mz_y_LS6Jx5S6pbOtFD:-Mz_y_LS6Jx5S6pbOtFE:bqmk9pq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/20aad2319c4f03cbc1ad69172db94520c7aa0ee2/src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/EventFilter.kt#L25)):*
> ```Kotlin
> import org.wfanet.measurement.eventdataprovider.eventfiltration.validation.EventFilterValidator
> 
> object EventFilter {
> ```

nit: `EventFilters` or `EventFiltration`, as I assume by the static nature that these are util functions that apply to any filter rather than just one.



_Code quote:_
```Kotlin
EventFilter
```
___
*[src/main/proto/wfa/measurement/api/v2alpha/event_templates/testing/test_event.proto, line 17 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/491#-Mza-3i502jd_j3-k9CY:-Mza-3i502jd_j3-k9CZ:ble5yrk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/20aad2319c4f03cbc1ad69172db94520c7aa0ee2/src/main/proto/wfa/measurement/api/v2alpha/event_templates/testing/test_event.proto#L17)):*
> ```protobuf
> syntax = "proto3";
> 
> package org.wfa.measurement.api.v2alpha.event_templates.testing;
> ```

Drop `org` here



_Code quote:_
```protobuf
org.wfa
```
___
*[src/main/proto/wfa/measurement/api/v2alpha/event_templates/testing/test_event.proto, line 22 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/491#-Mza-9Ss5z5dcv99oZN2:-Mza-9Ss5z5dcv99oZN3:b-1u9wnc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/20aad2319c4f03cbc1ad69172db94520c7aa0ee2/src/main/proto/wfa/measurement/api/v2alpha/event_templates/testing/test_event.proto#L22)):*
> ```protobuf
> import "wfa/measurement/api/v2alpha/event_templates/testing/test_video_template.proto";
> 
> option java_package = "wfanet.measurement.api.v2alpha.event_templates.testing";
> ```

Add `org` here



_Code quote:_
```protobuf
wfanet
```
___
*[src/main/proto/wfa/measurement/api/v2alpha/event_templates/testing/test_video_template.proto, line 17 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/491#-Mz_zms790VlYdRf5cfY:-Mz_zms790VlYdRf5cfZ:b-tycqqm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/20aad2319c4f03cbc1ad69172db94520c7aa0ee2/src/main/proto/wfa/measurement/api/v2alpha/event_templates/testing/test_video_template.proto#L17)):*
> ```protobuf
> syntax = "proto3";
> 
> package org.wfa.measurement.api.v2alpha.event_templates.testing;
> ```

These packages are still not correct.

The protobuf package should start with `wfa.measurement`. The Java package should start with `org.wfanet.measurement`.



_Code quote:_
```protobuf
org.wfa.measurement
```
___
*[src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/EventFilterException.kt, line 23 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/491#-Mz_yyUS6u7z5S1RAgX4:-Mz_yyUS6u7z5S1RAgX5:bwjc7fh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/20aad2319c4f03cbc1ad69172db94520c7aa0ee2/src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/EventFilterException.kt#L23)):*
> ```Kotlin
>     EVALUATION_ERROR,
> 
>     /** Filter evaluation is not a boolean */
> ```

nit: sounds awkward. Maybe "Filter expression does not evaluate to a boolean"?



_Code quote:_
```Kotlin
is not a boolean
```


<!-- Sent from Reviewable.io -->

2022-04-01 17:43 UTC, duliomatos1 reviewed
> Dismissed @SanjayVas from 4 discussions.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/491)* status: 14 of 18 files reviewed, 14 unresolved discussions (waiting on @chipingyeh, @duliomatos1, @SanjayVas, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/filter/EventFilter.kt, line 15 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/491#-MymzG8B395Uc2hlTfXl:-MzaCyTS6i6XzQTN449S:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/75ff82bec8e617ecb21361b8139cb8e30ecaca62/src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/filter/EventFilter.kt#L15)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

As long as the package hierarchy follows one of two patterns:
1. Parent package can depend on child packages but not the other way around. Child packages should not be accessible outside of the parent package.
2. Child packages can depend on the parent package, but not the other way around. This is the more common pattern we follow. See the `storage` package in common-jvm for a clear example.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/filter/EventFilter.kt, line 36 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/491#-Myn-Zsf0aSHK_NU59Mb:-MzaD7h8-latUaOopcln:bp3vn7s) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/75ff82bec8e617ecb21361b8139cb8e30ecaca62/src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/filter/EventFilter.kt#L36)):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

I shall move those methods to the companion object
</blockquote></details>

Done. (moved to stateless)
___
*[src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/filter/EventFilter.kt, line 41 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/491#-MymzZnyDqMDgdjMdYxe:-MzaCzuj9GQBv-fRCpHj:bb7f2mf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/75ff82bec8e617ecb21361b8139cb8e30ecaca62/src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/filter/EventFilter.kt#L41)):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

ended up removing this fun by making `EventFilter` stateless. It has now only `compileProgram(celExpr: String, defaultEventMessage: Message): Program` and `fun matches(event: Message, program: Program): Boolean`
</blockquote></details>

done
___
*[src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/filter/EventFilter.kt, line 46 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/491#-Myn-6Qh-4tob2mu4GI5:-MzaD1_k4p62rjD39wLb:bb7f2mf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/75ff82bec8e617ecb21361b8139cb8e30ecaca62/src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/filter/EventFilter.kt#L46)):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

sure
</blockquote></details>

done
___
*[src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/filter/EventFilter.kt, line 57 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/491#-Myn-PJX1gLQvrAuMOso:-MzaD3R06kzNUvcEqrB8:b-7rl0jd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/75ff82bec8e617ecb21361b8139cb8e30ecaca62/src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/filter/EventFilter.kt#L57)):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

could be just `createEnv()`
</blockquote></details>

done.
___
*[src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/filter/EventFilter.kt, line 78 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/491#-Myn-x_b9fjnIXwBqtJw:-MzaDA4x9knSjonLkhPA:b-7rl0jd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/75ff82bec8e617ecb21361b8139cb8e30ecaca62/src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/filter/EventFilter.kt#L78)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

+1
</blockquote></details>

done.
___
*[src/test/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/filter/EventFilterTest.kt, line 31 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/491#-Mz1fuwQ8K9_LaDZTZSo:-MzaDK_tE6toyztX6mbY:b-lbrrnc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/75ff82bec8e617ecb21361b8139cb8e30ecaca62/src/test/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/filter/EventFilterTest.kt#L31)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

import org.wfanet.measurement.api.v2alpha.event_templates.testing.testEvent
</blockquote></details>

cool, thx. will fix it now.


<!-- Sent from Reviewable.io -->

2022-04-01 17:59 UTC, duliomatos1 reviewed
> Dismissed @SanjayVas from 2 discussions.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/491)* status: 14 of 18 files reviewed, 12 unresolved discussions (waiting on @chipingyeh, @duliomatos1, @SanjayVas, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/EventFilter.kt, line 25 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/491#-Mz_y_LS6Jx5S6pbOtFD:-MzaGt_k52YXLNCi3fZz:b1g1q9b) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/20aad2319c4f03cbc1ad69172db94520c7aa0ee2/src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/EventFilter.kt#L25)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: `EventFilters` or `EventFiltration`, as I assume by the static nature that these are util functions that apply to any filter rather than just one.
</blockquote></details>

got the other way around. Will fix
___
*[src/main/proto/wfa/measurement/api/v2alpha/event_templates/testing/test_video_template.proto, line 17 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/491#-Mz_zms790VlYdRf5cfY:-MzaEcYn-oUgs5eRO1nH:b-q8jzb0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/20aad2319c4f03cbc1ad69172db94520c7aa0ee2/src/main/proto/wfa/measurement/api/v2alpha/event_templates/testing/test_video_template.proto#L17)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

These packages are still not correct.

The protobuf package should start with `wfa.measurement`. The Java package should start with `org.wfanet.measurement`.
</blockquote></details>

got it
___
*[src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/filter/EventFilter.kt, line 57 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/491#-Myn-PJX1gLQvrAuMOso:-MzaEMYL3-GVwkD1vjLY:bg8lm1b) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/75ff82bec8e617ecb21361b8139cb8e30ecaca62/src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/filter/EventFilter.kt#L57)):*
> import org.wfanet.measurement.api.v2alpha.event_templates.testing.TestEvent
> 3 MINUTES AGO
> duliomatos1Dulio Matos


<!-- Sent from Reviewable.io -->

2022-04-01 17:59 UTC, duliomatos1 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/491)* status: 14 of 18 files reviewed, 12 unresolved discussions (waiting on @chipingyeh, @duliomatos1, @SanjayVas, and @stevenwarejones)

___
*[src/main/proto/wfa/measurement/api/v2alpha/event_templates/testing/test_event.proto, line 17 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/491#-Mza-3i502jd_j3-k9CY:-MzaH3_G3Fh5e8Dn-BxL:b-2p4tq4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/20aad2319c4f03cbc1ad69172db94520c7aa0ee2/src/main/proto/wfa/measurement/api/v2alpha/event_templates/testing/test_event.proto#L17)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Drop `org` here
</blockquote></details>

got the other way around on fixing the prefixes. Will fix


<!-- Sent from Reviewable.io -->

2022-04-01 18:03 UTC, duliomatos1 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/491)* status: 14 of 18 files reviewed, 12 unresolved discussions (waiting on @chipingyeh, @duliomatos1, @SanjayVas, @stevenwarejones, and @uakyol)

___
*[src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/EventFilter.kt, line 25 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/491#-Mz_y_LS6Jx5S6pbOtFD:-MzaHEBUEcvTxgP3GJ5H:bjz1f1x) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/20aad2319c4f03cbc1ad69172db94520c7aa0ee2/src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/EventFilter.kt#L25)):*
> got the other way around. Will fix
wrong comment.

Yeah, EventFilters seems to be a good suggestion.

@uakyol being stateless the caller needs to keep a program var around. We can go back on just storing this var if you think it's better to encapsulate. (looks fine to me as stateless, it's explicit)
___
*[src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/EventFilterException.kt, line 23 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/491#-Mz_yyUS6u7z5S1RAgX4:-MzaHA8U18fiQhQJc7iq:bb7oryy) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/20aad2319c4f03cbc1ad69172db94520c7aa0ee2/src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/EventFilterException.kt#L23)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: sounds awkward. Maybe "Filter expression does not evaluate to a boolean"?
</blockquote></details>

sure


<!-- Sent from Reviewable.io -->

2022-04-04 13:57 UTC, duliomatos1 reviewed
> Dismissed @SanjayVas and @stevenwarejones from 6 discussions.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/491)* status: 2 of 19 files reviewed, 3 unresolved discussions (waiting on @chipingyeh, @duliomatos1, @SanjayVas, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt, line 129 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/491#-Mz_jzcx4-0XSmuKW1bD:-MzorHVcA9VvESIBM5_p:b-7rl0jd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/20aad2319c4f03cbc1ad69172db94520c7aa0ee2/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L129)):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

I may be running an older version of ktfmt (0.29) locally, let me check
</blockquote></details>

done.
___
*[src/main/proto/wfa/measurement/api/v2alpha/event_templates/testing/test_event.proto, line 17 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/491#-Mza-3i502jd_j3-k9CY:-MzoheX94D3dyVdJtidg:bb7f2mf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/20aad2319c4f03cbc1ad69172db94520c7aa0ee2/src/main/proto/wfa/measurement/api/v2alpha/event_templates/testing/test_event.proto#L17)):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

got the other way around on fixing the prefixes. Will fix
</blockquote></details>

done
___
*[src/main/proto/wfa/measurement/api/v2alpha/event_templates/testing/test_event.proto, line 22 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/491#-Mza-9Ss5z5dcv99oZN2:-MzohgTo8JhuUYnSdsNp:b-7rl0jd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/20aad2319c4f03cbc1ad69172db94520c7aa0ee2/src/main/proto/wfa/measurement/api/v2alpha/event_templates/testing/test_event.proto#L22)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Add `org` here
</blockquote></details>

done.
___
*[src/main/proto/wfa/measurement/api/v2alpha/event_templates/testing/test_video_template.proto, line 17 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/491#-Mz_zms790VlYdRf5cfY:-Mzohht_2Ivn621CcCAS:b-7rl0jd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/20aad2319c4f03cbc1ad69172db94520c7aa0ee2/src/main/proto/wfa/measurement/api/v2alpha/event_templates/testing/test_video_template.proto#L17)):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

got it
</blockquote></details>

done.
___
*[src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/EventFilter.kt, line 25 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/491#-Mz_y_LS6Jx5S6pbOtFD:-MzorEmu6l3k0E0B4Q1r:b-7rl0jd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/20aad2319c4f03cbc1ad69172db94520c7aa0ee2/src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/EventFilter.kt#L25)):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

> got the other way around. Will fix
wrong comment.

Yeah, EventFilters seems to be a good suggestion.

@uakyol being stateless the caller needs to keep a program var around. We can go back on just storing this var if you think it's better to encapsulate. (looks fine to me as stateless, it's explicit)
</blockquote></details>

done.
___
*[src/test/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/filter/EventFilterTest.kt, line 72 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/491#-Mz1fikH17qON-2pd1l9:-MzokHHFBHCHp_LpLURj:b-7rl0jd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/75ff82bec8e617ecb21361b8139cb8e30ecaca62/src/test/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/filter/EventFilterTest.kt#L72)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

testEvent {}
</blockquote></details>

done.
___
*[src/test/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/filter/EventFilterTest.kt, line 74 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/491#-Mz1fpa2B6dzx56Ct8En:-MzokJx75JTgLx_iZ99b:b-7rl0jd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/75ff82bec8e617ecb21361b8139cb8e30ecaca62/src/test/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/filter/EventFilterTest.kt#L74)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

testEvent {}
</blockquote></details>

done.
___
*[src/test/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/filter/EventFilterTest.kt, line 83 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/491#-Mz1fk5B2P7nx6QMADci:-MzokQfV7BQU47iqlu9v:b-7rl0jd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/75ff82bec8e617ecb21361b8139cb8e30ecaca62/src/test/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/filter/EventFilterTest.kt#L83)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

done.
___
*[src/test/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/filter/EventFilterTest.kt, line 93 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/491#-Mz1fdqj21pk2e9bDTzZ:-MzokVhI6lYkxRrk1aLM:b-7rl0jd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/75ff82bec8e617ecb21361b8139cb8e30ecaca62/src/test/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/filter/EventFilterTest.kt#L93)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

`testEvent {}`
</blockquote></details>

done.


<!-- Sent from Reviewable.io -->

2022-04-04 13:59 UTC, duliomatos1 reviewed
> Dismissed @stevenwarejones from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/491)* status: 2 of 19 files reviewed, all discussions resolved (waiting on @chipingyeh, @SanjayVas, and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2022-04-04 17:39 UTC, uakyol reviewed
Can you please sync this to main Dulio? I want to pull and work on this branch but there are so many conflicts.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/491#-:-Mzh5i-D3oY_7TE_-Ojc:b-evvbsc)* status: 2 of 19 files reviewed, all discussions resolved (waiting on @chipingyeh, @SanjayVas, and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2022-04-04 18:19 UTC, duliomatos1 reviewed
sure! It has probably changed again after this morning.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/491#-:-MzpnIkmDXWeIUqf72LY:bbpr5c1)* status: 2 of 19 files reviewed, all discussions resolved (waiting on @chipingyeh, @SanjayVas, and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2022-04-04 18:29 UTC, duliomatos1 reviewed
actually, it was updated earlier today, commit 1609a75f4ee544003cad5f645d55d2502d00982b is on top of origin/main

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/491#-:-MzppW9u5HbwmT9lZHeI:b-2bpotv)* status: 2 of 19 files reviewed, all discussions resolved (waiting on @chipingyeh, @SanjayVas, and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2022-04-04 19:49 UTC, SanjayVas requested changes
> Reviewed 2 of 17 files at r2, 6 of 14 files at r3, 9 of 9 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/491)* status: all files reviewed, 3 unresolved discussions (waiting on @chipingyeh and @duliomatos1)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/491#-Mzq6BMu7KXHQNehqjjb:-Mzq6BMu7KXHQNehqjjc:bed9pmv) (no related file):*
Since you decided on using the structure where the parent `eventfiltration` depends on its children and not the other way around, update the BUILD files to ensure that the child targets are not visible outside of the parent package. The idea is that e.g. the only way someone can access `EventFilterValidator` is via `EventFilters.

---
___
*[src/test/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/EventFiltersTest.kt, line 57 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/491#-MzpxlxB-MdPY1aVMU6S:-MzpxlxB-MdPY1aVMU6T:b4afkt7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1609a75f4ee544003cad5f645d55d2502d00982b/src/test/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/EventFiltersTest.kt#L57)):*
> ```Kotlin
>   }
> 
>   private fun assertThatFailsWithCode(
> ```

nit: `assertFailsWithCode`, since `assertThat` is for assertion functions that take in a subject.



_Code quote:_
```Kotlin
assertThatFailsWithCode
```
___
*[src/test/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/EventFiltersTest.kt, line 57 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/491#-Mzpy47PC1m5z6K6avGd:-Mzpy47PC1m5z6K6avGe:b-x3bonf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1609a75f4ee544003cad5f645d55d2502d00982b/src/test/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/EventFiltersTest.kt#L57)):*
> ```Kotlin
>   }
> 
>   private fun assertThatFailsWithCode(
> ```

Small functions that are intended to execute lambdas like this should be declared inline. See https://kotlinlang.org/docs/inline-functions.html



_Code quote:_
```Kotlin
 private fun 
```


<!-- Sent from Reviewable.io -->

2022-04-04 20:03 UTC, uakyol approved these changes
Ah thank you

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/491#-:-Mzq9rj73K4rJ6Ebths7:b-um1q97)* status: all files reviewed, 3 unresolved discussions (waiting on @chipingyeh and @duliomatos1)



<!-- Sent from Reviewable.io -->

2022-04-04 23:34 UTC, duliomatos1 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/491)* status: all files reviewed, 3 unresolved discussions (waiting on @chipingyeh, @duliomatos1, and @SanjayVas)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/491#-Mzq6BMu7KXHQNehqjjb:-MzqvTtf--Tf56IrCDO5:b-7j86r0) (no related file):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Since you decided on using the structure where the parent `eventfiltration` depends on its children and not the other way around, update the BUILD files to ensure that the child targets are not visible outside of the parent package. The idea is that e.g. the only way someone can access `EventFilterValidator` is via `EventFilters.
</blockquote></details>

sure.

---


<!-- Sent from Reviewable.io -->

2022-04-05 19:34 UTC, duliomatos1 reviewed
> Dismissed @SanjayVas from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/491)* status: 14 of 21 files reviewed, 1 unresolved discussion (waiting on @chipingyeh, @SanjayVas, and @stevenwarejones)

___
*[src/test/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/EventFiltersTest.kt, line 57 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/491#-MzpxlxB-MdPY1aVMU6S:-MzvCFAUBRACyPzHIazm:b-7rl0jd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1609a75f4ee544003cad5f645d55d2502d00982b/src/test/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/EventFiltersTest.kt#L57)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: `assertFailsWithCode`, since `assertThat` is for assertion functions that take in a subject.
</blockquote></details>

done.
___
*[src/test/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/EventFiltersTest.kt, line 57 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/491#-Mzpy47PC1m5z6K6avGd:-MzvCENm8WGMIoBBsVlQ:b-7rl0jd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1609a75f4ee544003cad5f645d55d2502d00982b/src/test/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/EventFiltersTest.kt#L57)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Small functions that are intended to execute lambdas like this should be declared inline. See https://kotlinlang.org/docs/inline-functions.html
</blockquote></details>

done.


<!-- Sent from Reviewable.io -->

2022-04-05 19:37 UTC, duliomatos1 reviewed
> Dismissed @SanjayVas from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/491)* status: 14 of 21 files reviewed, all discussions resolved (waiting on @chipingyeh, @SanjayVas, and @stevenwarejones)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/491#-Mzq6BMu7KXHQNehqjjb:-MzvD4Yy5yvYbSiBv1qP:bhemq0l) (no related file):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

sure.
</blockquote></details>

done. Set the package default visibility to private and added visibility only to parent package and test package. I've made a new fun `EventFilters.compile()` just forward to the validator as in`EventFilterValidator.compile()` 

---


<!-- Sent from Reviewable.io -->

2022-04-05 21:19 UTC, SanjayVas requested changes
> Reviewed 4 of 6 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/491)* status: 18 of 21 files reviewed, 3 unresolved discussions (waiting on @chipingyeh, @duliomatos1, and @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/validation/EventFilterValidator.kt, line 48 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/491#-Mzv_D9NACnR9lo7YcG8:-Mzv_D9NACnR9lo7YcG9:b-9yg5li) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/abf01cdafbf586f9715d745288adbf90c6dfe507/src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/validation/EventFilterValidator.kt#L48)):*
> ```Kotlin
>     if (!left.hasIdentExpr() && !left.hasSelectExpr()) {
>       throw EventFilterValidationException(
>           EventFilterValidationException.Code.INVALID_VALUE_TYPE,
> ```

This formatting looks off. Are you making sure to pass `--google-style` to `ktfmt` as mentioned in https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/docs/code-style.md#kotlin-1 ?

Please fix, as it's hard to tell which diffs are just from reformatting.
___
*[src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/validation/EventFilterValidator.kt, line 189 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/491#-Mzv_rLx59kj6JEXHR9L:-Mzv_rLx59kj6JEXHR9M:ba0tugi) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/abf01cdafbf586f9715d745288adbf90c6dfe507/src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/validation/EventFilterValidator.kt#L189)):*
> ```Kotlin
> }
> 
> private val LEAF_ONLY_OPERATORS =
> ```

nit: constants tend to go at the top of their declaring scope
___
*[src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/EventFilters.kt, line 49 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/491#-MzvYzp37oajnVS9DsZx:-MzvYzp37oajnVS9DsZy:b-nf2fl8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/abf01cdafbf586f9715d745288adbf90c6dfe507/src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/EventFilters.kt#L49)):*
> ```Kotlin
>    * Validates an Event Filtering CEL expression according to Halo rules.
>    *
>    * Throws a [EventFilterValidationException] on [compile] with the following codes:
> ```

nit: if this is just the whole list of codes, there's no need to enumerate them

The reason we list codes for KingdomInternalException is because most methods only use a small subset of the possible codes, so it's a way to document which ones should be handled by the caller.


<!-- Sent from Reviewable.io -->

2022-04-06 00:42 UTC, duliomatos1 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/491)* status: 18 of 21 files reviewed, 3 unresolved discussions (waiting on @chipingyeh, @duliomatos1, and @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/validation/EventFilterValidator.kt, line 48 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/491#-Mzv_D9NACnR9lo7YcG8:-MzwHP_PDGX7fEu-wuz5:b-x9n1x7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/abf01cdafbf586f9715d745288adbf90c6dfe507/src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/validation/EventFilterValidator.kt#L48)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This formatting looks off. Are you making sure to pass `--google-style` to `ktfmt` as mentioned in https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/docs/code-style.md#kotlin-1 ?

Please fix, as it's hard to tell which diffs are just from reformatting.
</blockquote></details>

I have a script that runs `java -jar ~/code/ktfmt/core/target/ktfmt-0.29-SNAPSHOT-jar-with-dependencies.jar --google-style $@` at each changed file but not sure why it diverges. I can try the intellij plugin
___
*[src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/EventFilters.kt, line 49 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/491#-MzvYzp37oajnVS9DsZx:-MzwH59LDszjNZd-faMr:bj8pssh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/abf01cdafbf586f9715d745288adbf90c6dfe507/src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/EventFilters.kt#L49)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: if this is just the whole list of codes, there's no need to enumerate them

The reason we list codes for KingdomInternalException is because most methods only use a small subset of the possible codes, so it's a way to document which ones should be handled by the caller.
</blockquote></details>

got it. Will simplify


<!-- Sent from Reviewable.io -->

2022-04-06 00:49 UTC, SanjayVas requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/491)* status: 18 of 21 files reviewed, 3 unresolved discussions (waiting on @chipingyeh, @duliomatos1, and @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/validation/EventFilterValidator.kt, line 48 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/491#-Mzv_D9NACnR9lo7YcG8:-MzwKl_AB6DDjdJknOLh:bh7e3vm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/abf01cdafbf586f9715d745288adbf90c6dfe507/src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/validation/EventFilterValidator.kt#L48)):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

I have a script that runs `java -jar ~/code/ktfmt/core/target/ktfmt-0.29-SNAPSHOT-jar-with-dependencies.jar --google-style $@` at each changed file but not sure why it diverges. I can try the intellij plugin
</blockquote></details>

That's an old `ktfmt` version. We went to ktfmt 0.32 back in [actions v1.6.2](https://github.com/world-federation-of-advertisers/actions/releases/tag/v1.6.2), and bumped up again to ktfmt 0.34 in [actions v1.6.3](https://github.com/world-federation-of-advertisers/actions/releases/tag/v1.6.3)


<!-- Sent from Reviewable.io -->

2022-04-06 00:51 UTC, duliomatos1 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/491)* status: 18 of 21 files reviewed, 2 unresolved discussions (waiting on @chipingyeh, @duliomatos1, and @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/validation/EventFilterValidator.kt, line 48 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/491#-Mzv_D9NACnR9lo7YcG8:-MzwLWjrAayVkt8q83qQ:bvnttx4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/abf01cdafbf586f9715d745288adbf90c6dfe507/src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/validation/EventFilterValidator.kt#L48)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

That's an old `ktfmt` version. We went to ktfmt 0.32 back in [actions v1.6.2](https://github.com/world-federation-of-advertisers/actions/releases/tag/v1.6.2), and bumped up again to ktfmt 0.34 in [actions v1.6.3](https://github.com/world-federation-of-advertisers/actions/releases/tag/v1.6.3)
</blockquote></details>

thx, I'll update to keep in sync
___
*[src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/EventFilters.kt, line 49 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/491#-MzvYzp37oajnVS9DsZx:-MzwK0ig9lmWbRAR9M2k:b-7rl0jd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/abf01cdafbf586f9715d745288adbf90c6dfe507/src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/EventFilters.kt#L49)):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

got it. Will simplify
</blockquote></details>

done.


<!-- Sent from Reviewable.io -->

2022-04-06 01:25 UTC, duliomatos1 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/491)* status: 15 of 21 files reviewed, 1 unresolved discussion (waiting on @chipingyeh and @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/validation/EventFilterValidator.kt, line 48 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/491#-Mzv_D9NACnR9lo7YcG8:-MzwTQs54LxQohbF0MeY:b-7rl0jd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/abf01cdafbf586f9715d745288adbf90c6dfe507/src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/validation/EventFilterValidator.kt#L48)):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

thx, I'll update to keep in sync
</blockquote></details>

done.
___
*[src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/validation/EventFilterValidator.kt, line 189 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/491#-Mzv_rLx59kj6JEXHR9L:-MzwTNWl79T2YrFdzVXL:b-7rl0jd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/abf01cdafbf586f9715d745288adbf90c6dfe507/src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/validation/EventFilterValidator.kt#L189)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: constants tend to go at the top of their declaring scope
</blockquote></details>

done.


<!-- Sent from Reviewable.io -->

2022-04-06 01:25 UTC, duliomatos1 reviewed
> Dismissed @SanjayVas from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/491)* status: 15 of 21 files reviewed, all discussions resolved (waiting on @chipingyeh and @SanjayVas)



<!-- Sent from Reviewable.io -->

2022-04-07 13:18 UTC, stevenwarejones requested changes
> Reviewed 1 of 17 files at r2, 3 of 14 files at r3, 1 of 9 files at r4, 3 of 6 files at r6, 4 of 5 files at r8.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/491)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @chipingyeh)

___
*[src/test/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/filter/EventFilterTest.kt, line 72 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/491#-Mz1fikH17qON-2pd1l9:-N-3ADbj8CJeI0rXSXX_:bz9tosq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/75ff82bec8e617ecb21361b8139cb8e30ecaca62/src/test/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/filter/EventFilterTest.kt#L72)):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

done.
</blockquote></details>

note seeing this change


<!-- Sent from Reviewable.io -->

2022-04-07 13:27 UTC, duliomatos1 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/491)* status: 20 of 21 files reviewed, all discussions resolved (waiting on @chipingyeh, @SanjayVas, and @stevenwarejones)

___
*[src/test/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/filter/EventFilterTest.kt, line 72 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/491#-Mz1fikH17qON-2pd1l9:-N-3BtXJ4nI7XKEvCJqw:b-3h9o4m) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/75ff82bec8e617ecb21361b8139cb8e30ecaca62/src/test/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/filter/EventFilterTest.kt#L72)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

note seeing this change
</blockquote></details>

now really done. 


<!-- Sent from Reviewable.io -->

2022-04-07 20:05 UTC, stevenwarejones approved these changes
> Reviewed 1 of 1 files at r7, 1 of 5 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/491)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @chipingyeh)



<!-- Sent from Reviewable.io -->

2022-04-08 12:46 UTC, merged