Implement skeletons of Panel Match public APIs.
world-federation-of-advertisers/cross-media-measurement pull request #5
Opened 2021-03-30 18:09 UTC by efoxepstein

This just adds the basic Kotlin classes and some tests that expect the
services to throw NotImplementedErrors. Future commits will fill in the
logic.

See issue world-federation-of-advertisers/cross-media-measurement#3.

2021-03-30 19:46 UTC, SanjayVas requested changes
> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/5)* status: all files reviewed, 1 unresolved discussion (waiting on @AlekseiS, @efoxepstein, @oliver-amzn, and @zasadnyy)

___
*[third_party/rbe_configs/cc/tools/cpp/empty.cc, line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/5#-MX3en_H0ySFO1PRFD1x:-MX3en_H0ySFO1PRFD1y:bdq4i26) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a9cf47c802b95fceb245c95ddbd131588e70f655/third_party/rbe_configs/cc/tools/cpp/empty.cc#L1)):*
> ```cpp
> // Copyright 2021 The Cross-Media Measurement Authors
> ```

Don't format or add invalid copyright/license headers to third-party code.


<!-- Sent from Reviewable.io -->

2021-03-31 04:24 UTC, efoxepstein reviewed
> Dismissed @SanjayVas from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/5)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @AlekseiS, @oliver-amzn, and @zasadnyy)

___
*[third_party/rbe_configs/cc/tools/cpp/empty.cc, line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/5#-MX3en_H0ySFO1PRFD1x:-MX5WaYYD4i2ruCi08e5:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a9cf47c802b95fceb245c95ddbd131588e70f655/third_party/rbe_configs/cc/tools/cpp/empty.cc#L1)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Don't format or add invalid copyright/license headers to third-party code.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-03-31 16:47 UTC, SanjayVas approved these changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/5)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @AlekseiS and @zasadnyy)



<!-- Sent from Reviewable.io -->

2021-03-31 16:47 UTC, SanjayVas approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/5)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @AlekseiS and @zasadnyy)



<!-- Sent from Reviewable.io -->

2021-04-01 17:54 UTC, merged