Add reporting API
world-federation-of-advertisers/cross-media-measurement pull request #504
Opened 2022-03-30 17:19 UTC by riemanli

2022-03-30 19:09 UTC, SanjayVas requested changes
> Reviewed 1 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/504)* status: 1 of 7 files reviewed, 5 unresolved discussions (waiting on @riemanli and @SanjayVas)

___
*[src/main/proto/wfa/measurement/reporting/v1alpha/event_group.proto, line 28 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/504#-MzRAXOK2R_FIZsW6sRW:-MzRAXOK2R_FIZsW6sRX:b-pa47qp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/21d2a7b518a12a56a1c1f275fa461324cd59b381/src/main/proto/wfa/measurement/reporting/v1alpha/event_group.proto#L28)):*
> ```protobuf
> message EventGroup {
>   option (google.api.resource) = {
>     type: "halo.wfanet.org/EventGroup"
> ```

This is the name of the type from the public API. We need different types for the reporting API. Since we have a new domain now (halo-cmm.org), we can use a subdomain of that.

e.g. `reporting.halo-cmm.org/EventGroup`.



_Code quote:_
```protobuf
halo.wfanet.org/EventGroup
```
___
*[src/main/proto/wfa/measurement/reporting/v1alpha/event_group.proto, line 29 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/504#-MzRB7lz7OuyMciFo5-6:-MzRB7lz7OuyMciFo5-7:b-lmdlfw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/21d2a7b518a12a56a1c1f275fa461324cd59b381/src/main/proto/wfa/measurement/reporting/v1alpha/event_group.proto#L29)):*
> ```protobuf
>   option (google.api.resource) = {
>     type: "halo.wfanet.org/EventGroup"
>     pattern: "/measurementConsumers/{measurement_consumer}/dataProviders/{data_provider}/eventGroups/{event_group}"
> ```

Patterns don't have a leading slash



_Code quote:_
```protobuf
/
```
___
*[src/main/proto/wfa/measurement/reporting/v1alpha/event_group_specifier.proto, line 24 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/504#-MzRBeHR77KVfTZQ6Km6:-MzRBeHR77KVfTZQ6Km7:bvk5hrw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/21d2a7b518a12a56a1c1f275fa461324cd59b381/src/main/proto/wfa/measurement/reporting/v1alpha/event_group_specifier.proto#L24)):*
> ```protobuf
> option java_multiple_files = true;
> 
> // Specification for a `EventGroup`. Immutable.
> ```

This is not a specification for an EventGroup in the same way that e.g. `RequisitionSpec` in the CMMS API is a specification for a Requisition.

This is a structure that contains per-EventGroup parameters. I'm not sure that giving this structure a name/type is even useful. Perhaps just define `EventGroupEntry`, and anywhere that wants to use it can include a repeated field of that type.



_Code quote:_
```protobuf
Specification for a `EventGroup`
```
___
*[src/main/proto/wfa/measurement/reporting/v1alpha/event_groups_service.proto, line 49 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/504#-MzRCOhpC-NUgO--0z2Q:-MzRCOhpC-NUgO--0z2R:b14gyjh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/21d2a7b518a12a56a1c1f275fa461324cd59b381/src/main/proto/wfa/measurement/reporting/v1alpha/event_groups_service.proto#L49)):*
> ```protobuf
>   // Filter criteria. Repeated fields are treated as logical ORs, and multiple
>   // fields specified as logical ANDs.
>   message Filter {
> ```

We're following https://google.aip.dev/160 for this API, which means that `filter` should be a string field that contains a CEL expression.



_Code quote:_
```protobuf
message Filter
```
___
*[src/main/proto/wfa/measurement/reporting/v1alpha/reports_service.proto, line 103 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/504#-MzRDhIL7kaUO21jxKqE:-MzRDhIL7kaUO21jxKqF:bs1qthv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/21d2a7b518a12a56a1c1f275fa461324cd59b381/src/main/proto/wfa/measurement/reporting/v1alpha/reports_service.proto#L103)):*
> ```protobuf
>   Report report = 2 [(google.api.field_behavior) = REQUIRED];
> 
>   repeated EventGroupSpecifier event_group_specifiers = 3;
> ```

Create requests just contain the resource message and the parent if it's not a top-level resource. These field go inside of `Report`.



_Code quote:_
```protobuf
  repeated EventGroupSpecifier event_group_specifiers = 3;

  ReportParameter report_parameter = 4;
```


<!-- Sent from Reviewable.io -->

2022-03-30 22:44 UTC, riemanli commented on src/main/proto/wfa/measurement/reporting/v1alpha/event_group.proto
> +    pattern: "measurementConsumers/{measurement_consumer}/dataProviders/{data_provider}/eventGroups/{event_group}"
@SanjayVas Does the pattern look reasonable to you?

2022-03-30 22:47 UTC, riemanli commented on src/main/proto/wfa/measurement/reporting/v1alpha/event_group.proto
> +  string data_provider = 2 [(google.api.resource_reference).type =
I added `data_provider` as your example in previous discussion, but now I can't remember the reason. Is `data_provider` in the `EventGroup` necessary for listing event groups?

2022-03-31 18:28 UTC, riemanli commented on src/main/proto/wfa/measurement/reporting/v1alpha/report_parameter.proto
> +option java_package = "com.src.main.proto.wfa.measurement.reporting.v1alpha";
@SanjayVas I modified `package` and `java_package` based on API Linter's suggestion, but it's different from the format we have in other .proto. Will that be an issue?

2022-04-01 00:24 UTC, SanjayVas reviewed
> Reviewed 1 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/504)* status: 1 of 7 files reviewed, 8 unresolved discussions (waiting on @riemanli and @SanjayVas)

___
*[src/main/proto/wfa/measurement/reporting/v1alpha/event_group.proto, line 29 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/504#-MzQpj_TzJiteCRurbbc-r2-29:-MzXU7GB2fl87ELOmIua:b-nm5k9p) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/19a0b47b6fcabbe93dbb1c3c1d268e315a8336c7/src/main/proto/wfa/measurement/reporting/v1alpha/event_group.proto#L29)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

@SanjayVas Does the pattern look reasonable to you?
</blockquote></details>

Yes. Like all resources in this API, it's under a single MeasurementConsumer. Since we're reusing IDs from the CMMS API and CMMS EventGroups IDs are only unique for a given DataProvider, then this pretty much is what the pattern *has* to be.
___
*[src/main/proto/wfa/measurement/reporting/v1alpha/event_group.proto, line 37 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/504#-MzQpj_TzJiteCRurbbc-r2-37:-MzXSGWw5SW0RbKDau87:b-n4axr0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/19a0b47b6fcabbe93dbb1c3c1d268e315a8336c7/src/main/proto/wfa/measurement/reporting/v1alpha/event_group.proto#L37)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

@SanjayVas  I added `data_provider` as your example in our discussion before, but now I can't remember the reason. Is `data_provider` in the `EventGroup` necessary for listing event groups?
</blockquote></details>

This is to allow filtering by data provider in ListEventGroups. e.g. `data_provider = dataProviders/123 OR data_provider = dataProviders/456`

Note that the above implies using a wildcard ID to list across multiple DataProviders. If listing for a single DataProvider, one would just specify that EDP's ID in the parent field of the request.
___
*[src/main/proto/wfa/measurement/reporting/v1alpha/report_parameter.proto, line 19 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/504#-MzQpj_TzJiteCRurbbg-r3-19:-MzXVLnN4fPVfhDxuAcz:b-iycd4z) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d29a94c24498ae07aa8cab0704db104993d3084c/src/main/proto/wfa/measurement/reporting/v1alpha/report_parameter.proto#L19)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

@SanjayVas I modified `package` and `java_package` based on API Linter's suggestion, but it's different from the format we have in other .proto. Will that be an issue?
</blockquote></details>

Yes, it's a problem. We should disable the linter rule, as doesn't understand that we strip the "src/main/proto" from our import path so the package really starts under that directory.


<!-- Sent from Reviewable.io -->

2022-04-01 00:56 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/504)* status: 1 of 7 files reviewed, 6 unresolved discussions (waiting on @riemanli and @SanjayVas)

___
*[src/main/proto/wfa/measurement/reporting/v1alpha/event_group.proto, line 28 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/504#-MzRAXOK2R_FIZsW6sRW:-MzXUkM-2yuy4IS8AXOP:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/21d2a7b518a12a56a1c1f275fa461324cd59b381/src/main/proto/wfa/measurement/reporting/v1alpha/event_group.proto#L28)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This is the name of the type from the public API. We need different types for the reporting API. Since we have a new domain now (halo-cmm.org), we can use a subdomain of that.

e.g. `reporting.halo-cmm.org/EventGroup`.
</blockquote></details>

Done.
___
*[src/main/proto/wfa/measurement/reporting/v1alpha/event_group.proto, line 29 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/504#-MzRB7lz7OuyMciFo5-6:-MzXUpsG6T2RQIF-qvxg:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/21d2a7b518a12a56a1c1f275fa461324cd59b381/src/main/proto/wfa/measurement/reporting/v1alpha/event_group.proto#L29)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Patterns don't have a leading slash
</blockquote></details>

Done.
___
*[src/main/proto/wfa/measurement/reporting/v1alpha/event_group.proto, line 37 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/504#-MzQpj_TzJiteCRurbbc-r2-37:-MzXYm_--cpAR1dJspAq:brac29n) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/19a0b47b6fcabbe93dbb1c3c1d268e315a8336c7/src/main/proto/wfa/measurement/reporting/v1alpha/event_group.proto#L37)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This is to allow filtering by data provider in ListEventGroups. e.g. `data_provider = dataProviders/123 OR data_provider = dataProviders/456`

Note that the above implies using a wildcard ID to list across multiple DataProviders. If listing for a single DataProvider, one would just specify that EDP's ID in the parent field of the request.
</blockquote></details>

Could you confirm if my understanding described below is correct?

Let's say `reporting.EventGroups.ListEventGroups` takes a list of `DataProviders` for a given MC. In this case, the function will call `cmm-api.EventGroups.ListEventGroups` with the wildcard ID `-` to get all event groups across all data providers available to that MC. Then, the function stores each of the event groups to a `reporting.EventGroup` respectively, and filters the set of `reporting.EventGroups` based on the list of `DataProviders`.
___
*[src/main/proto/wfa/measurement/reporting/v1alpha/event_groups_service.proto, line 49 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/504#-MzRCOhpC-NUgO--0z2Q:-MzXVW2TDfmPxttiI4Gb:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/21d2a7b518a12a56a1c1f275fa461324cd59b381/src/main/proto/wfa/measurement/reporting/v1alpha/event_groups_service.proto#L49)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

We're following https://google.aip.dev/160 for this API, which means that `filter` should be a string field that contains a CEL expression.
</blockquote></details>

Done.
___
*[src/main/proto/wfa/measurement/reporting/v1alpha/report_parameter.proto, line 19 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/504#-MzQpj_TzJiteCRurbbg-r3-19:-MzXXnRW2FPyF6czgbLM:blfzbjj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d29a94c24498ae07aa8cab0704db104993d3084c/src/main/proto/wfa/measurement/reporting/v1alpha/report_parameter.proto#L19)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Yes, it's a problem. We should disable the linter rule, as doesn't understand that we strip the "src/main/proto" from our import path so the package really starts under that directory.
</blockquote></details>

OK. Got it!
___
*[src/main/proto/wfa/measurement/reporting/v1alpha/reports_service.proto, line 103 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/504#-MzRDhIL7kaUO21jxKqE:-MzXVpepBH2JUuSvLKEY:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/21d2a7b518a12a56a1c1f275fa461324cd59b381/src/main/proto/wfa/measurement/reporting/v1alpha/reports_service.proto#L103)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Create requests just contain the resource message and the parent if it's not a top-level resource. These field go inside of `Report`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-04-01 00:58 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/504)* status: 1 of 7 files reviewed, 6 unresolved discussions (waiting on @riemanli and @SanjayVas)

___
*[src/main/proto/wfa/measurement/reporting/v1alpha/event_group_specifier.proto, line 24 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/504#-MzRBeHR77KVfTZQ6Km6:-MzXc5NX5eSqDdT5euux:b-xb75ez) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/21d2a7b518a12a56a1c1f275fa461324cd59b381/src/main/proto/wfa/measurement/reporting/v1alpha/event_group_specifier.proto#L24)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This is not a specification for an EventGroup in the same way that e.g. `RequisitionSpec` in the CMMS API is a specification for a Requisition.

This is a structure that contains per-EventGroup parameters. I'm not sure that giving this structure a name/type is even useful. Perhaps just define `EventGroupEntry`, and anywhere that wants to use it can include a repeated field of that type.
</blockquote></details>

Removed the wrong comment for now. Will add a correct one later.


<!-- Sent from Reviewable.io -->

2022-04-01 19:31 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/504)* status: 1 of 8 files reviewed, 7 unresolved discussions (waiting on @SanjayVas)

___
*[api-linter.yaml, line 1 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/504#-Mzaa_ZLDdtNRO5meyae:-Mzaa_ZLDdtNRO5meyaf:bnds1eu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/048ee22b2b6ee34bea5532dbe88f3aa62d212dbb/api-linter.yaml#L1)):*
> ```YAML
> - included_paths:
> ```

@sanjayvas Is the root directory the right place for this .yaml?  
Also, I got the linter error complaining about missing license headers. What license header should I put here?
___
*[src/main/proto/wfa/measurement/reporting/v1alpha/event_group_specifier.proto, line 24 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/504#-MzRBeHR77KVfTZQ6Km6:-Mzab1hsEghxNlg7jzwy:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/21d2a7b518a12a56a1c1f275fa461324cd59b381/src/main/proto/wfa/measurement/reporting/v1alpha/event_group_specifier.proto#L24)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Removed the wrong comment for now. Will add a correct one later.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-04-01 21:55 UTC, SanjayVas requested changes
> Reviewed 2 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/504)* status: 3 of 8 files reviewed, 5 unresolved discussions (waiting on @riemanli and @SanjayVas)

___
*[api-linter.yaml, line 1 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/504#-Mzaa_ZLDdtNRO5meyae:-Mzb0Ijb0L6UVF55Sd9k:bcb8p96) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/048ee22b2b6ee34bea5532dbe88f3aa62d212dbb/api-linter.yaml#L1)):*
> Is the root directory the right place for this .yaml?

Does the config file format allow separate rules for separate paths? I just want to make sure we have the flexibility to use different rules for different API versions if needed. If it does, I'm thinking maybe the src/main/proto folder. Additionally, if we run the API linter from there then I think we can avoid disabling the proto-package rule, at the cost of needing to crawl up the path to get at the generated descriptor sets.

For license headers, use the [addlicense tool](https://github.com/google/addlicense) to add these for you. It covers most filetypes that need licenses. The author should be "The Cross-Media Measurement Authors" and the license type should be `apache`.
___
*[src/main/proto/wfa/measurement/reporting/v1alpha/event_group.proto, line 37 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/504#-MzQpj_TzJiteCRurbbc-r2-37:-Mzb4c7L0BdYA4Z-Rc3y:bk84spd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/19a0b47b6fcabbe93dbb1c3c1d268e315a8336c7/src/main/proto/wfa/measurement/reporting/v1alpha/event_group.proto#L37)):*
> Let's say `reporting.EventGroups.ListEventGroups` takes a list of `DataProviders` for a given MC.

I assume you mean that the request to `reporting.EventGroups.ListEventGroups` would have `parent: "measurementConsumers/abc123/dataProviders/-"` and `filter: "dataProvider = dataProviders/a1 OR dataProvider = dataProviders/b2"`

>  In this case, the function will call `cmm-api.EventGroups.ListEventGroups` with the wildcard ID `-` to get all event groups across all data providers available to that MC. Then, the function stores each of the event groups to a `reporting.EventGroup` respectively, and filters the set of `reporting.EventGroups` based on the list of `DataProviders`.

Yeah, that's about right.
___
*[src/main/proto/wfa/measurement/reporting/v1alpha/event_groups_service.proto, line 49 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/504#-MzRCOhpC-NUgO--0z2Q:-Mzb72pnCMFqik01FhUo:b-9ooep2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/21d2a7b518a12a56a1c1f275fa461324cd59b381/src/main/proto/wfa/measurement/reporting/v1alpha/event_groups_service.proto#L49)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not quite. Ditch the wrapping message. Just `string filter = 4`


<!-- Sent from Reviewable.io -->

2022-04-01 22:28 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/504)* status: 2 of 9 files reviewed, 5 unresolved discussions (waiting on @SanjayVas)

___
*[src/main/proto/wfa/measurement/reporting/v1alpha/event_group.proto, line 37 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/504#-MzQpj_TzJiteCRurbbc-r2-37:-MzbCNxh4dzM1M3gnvO9:b-sdydiz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/19a0b47b6fcabbe93dbb1c3c1d268e315a8336c7/src/main/proto/wfa/measurement/reporting/v1alpha/event_group.proto#L37)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> Let's say `reporting.EventGroups.ListEventGroups` takes a list of `DataProviders` for a given MC.

I assume you mean that the request to `reporting.EventGroups.ListEventGroups` would have `parent: "measurementConsumers/abc123/dataProviders/-"` and `filter: "dataProvider = dataProviders/a1 OR dataProvider = dataProviders/b2"`

>  In this case, the function will call `cmm-api.EventGroups.ListEventGroups` with the wildcard ID `-` to get all event groups across all data providers available to that MC. Then, the function stores each of the event groups to a `reporting.EventGroup` respectively, and filters the set of `reporting.EventGroups` based on the list of `DataProviders`.

Yeah, that's about right.
</blockquote></details>

Thanks for confirming that!
___
*[src/main/proto/wfa/measurement/reporting/v1alpha/event_groups_service.proto, line 49 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/504#-MzRCOhpC-NUgO--0z2Q:-MzbEO2_30QJQRm-cmIQ:b-k60k39) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/21d2a7b518a12a56a1c1f275fa461324cd59b381/src/main/proto/wfa/measurement/reporting/v1alpha/event_groups_service.proto#L49)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Not quite. Ditch the wrapping message. Just `string filter = 4`
</blockquote></details>

Sorry that's an accident click. Real modified this time.
___
*[api-linter.yaml, line 1 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/504#-Mzaa_ZLDdtNRO5meyae:-Mzb8QhY457jn26cwBHm:b-tsibr8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/048ee22b2b6ee34bea5532dbe88f3aa62d212dbb/api-linter.yaml#L1)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> Is the root directory the right place for this .yaml?

Does the config file format allow separate rules for separate paths? I just want to make sure we have the flexibility to use different rules for different API versions if needed. If it does, I'm thinking maybe the src/main/proto folder. Additionally, if we run the API linter from there then I think we can avoid disabling the proto-package rule, at the cost of needing to crawl up the path to get at the generated descriptor sets.

For license headers, use the [addlicense tool](https://github.com/google/addlicense) to add these for you. It covers most filetypes that need licenses. The author should be "The Cross-Media Measurement Authors" and the license type should be `apache`.
</blockquote></details>

Yes, it allows separate paths with different rules. See this [example](https://github.com/temporalio/api/blob/master/api-linter.yaml).

That's a good idea. Another benefit of moving the yaml file to `src/main/proto` is that `proto-path=src/main/proto` is no longer needed when we run the API linter.


<!-- Sent from Reviewable.io -->

2022-04-04 18:35 UTC, SanjayVas requested changes
> Reviewed 1 of 7 files at r3, 3 of 6 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/504)* status: all files reviewed, 2 unresolved discussions (waiting on @riemanli)

___
*[src/main/proto/wfa/measurement/reporting/v1alpha/BUILD.bazel, line 28 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/504#-MzpYKyz6AA9radjIMA4:-MzpYKyz6AA9radjIMA5:b-d60kjj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2fc8d5de498168e0b6055ef1ab6d03a4d6dfdd3c/src/main/proto/wfa/measurement/reporting/v1alpha/BUILD.bazel#L28)):*
> ```Starlark
>     name = "event_group_kt_jvm_proto",
>     srcs = [":event_group_proto"],
>     visibility = ["//visibility:public"],
> ```

Can just set the default package visibility be public, since this is a public API.



_Code quote:_
```Starlark
"//visibility:public"
```
___
*[src/main/proto/wfa/measurement/reporting/v1alpha/event_groups_service.proto, line 19 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/504#-MzpZ8ti1Ckq9cqzorZ5:-MzpZ8ti1Ckq9cqzorZ6:b-3qomne) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2fc8d5de498168e0b6055ef1ab6d03a4d6dfdd3c/src/main/proto/wfa/measurement/reporting/v1alpha/event_groups_service.proto#L19)):*
> ```protobuf
> package wfa.measurement.reporting.v1alpha;
> 
> // google.api.method_signature
> ```

This type of documentation is very uncommon. It's somewhat assumed that the authors ensure that only used dependencies are imported.


<!-- Sent from Reviewable.io -->

2022-04-05 20:12 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/504)* status: 6 of 9 files reviewed, 2 unresolved discussions (waiting on @SanjayVas)

___
*[src/main/proto/wfa/measurement/reporting/v1alpha/BUILD.bazel, line 28 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/504#-MzpYKyz6AA9radjIMA4:-MzvKs1M2-Ys-qNVu-X_:b-xu0uci) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2fc8d5de498168e0b6055ef1ab6d03a4d6dfdd3c/src/main/proto/wfa/measurement/reporting/v1alpha/BUILD.bazel#L28)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Can just set the default package visibility be public, since this is a public API.
</blockquote></details>

Thanks for the suggestion. Done.
___
*[src/main/proto/wfa/measurement/reporting/v1alpha/event_groups_service.proto, line 19 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/504#-MzpZ8ti1Ckq9cqzorZ5:-MzvL2LS91D1bvKw-zL5:bqx2g44) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2fc8d5de498168e0b6055ef1ab6d03a4d6dfdd3c/src/main/proto/wfa/measurement/reporting/v1alpha/event_groups_service.proto#L19)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This type of documentation is very uncommon. It's somewhat assumed that the authors ensure that only used dependencies are imported.
</blockquote></details>

You're right. They're removed now.


<!-- Sent from Reviewable.io -->

2022-05-04 16:15 UTC, SanjayVas requested changes
> Reviewed 3 of 7 files at r7, 8 of 8 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/504)* status: all files reviewed, 7 unresolved discussions (waiting on @riemanli)

___
*[`src/main/proto/wfa/measurement/reporting/v1alpha/event_group.proto` line 41 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/504#-N1Em7ZMA3urSixQ3AnI:-N1Em7ZMA3urSixQ3AnJ:b-dlw330) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/041d3a593f3c84086890986fef94720b46e53b33/src/main/proto/wfa/measurement/reporting/v1alpha/event_group.proto#L41)):*
> ```protobuf
>     (google.api.field_behavior) = IMMUTABLE,
>     (google.api.resource_reference).type = "halo.wfanet.org/DataProvider"
>   ];
> ```

Add `event_group_reference_id` field from CMMS API.
___
*[`src/main/proto/wfa/measurement/reporting/v1alpha/metric.proto` line 43 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/504#-N1EmqzM61Z_xndSVhfA:-N1EmqzM61Z_xndSVhfB:brvxy1o) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/041d3a593f3c84086890986fef94720b46e53b33/src/main/proto/wfa/measurement/reporting/v1alpha/metric.proto#L43)):*
> ```protobuf
>   // Parameters that are used to generate `Reach Curve` metric.
>   message ReachCurveParams {
>     // Number of points that should be plotted on the reach curve
> ```

Leave this out for now. Let's only keep the items that we know we're planning on implementing. The oneof structure is intended to be able to support adding new types in the future.



_Code quote:_
```protobuf
  // Parameters that are used to generate `Reach Curve` metric.
  message ReachCurveParams {
    // Number of points that should be plotted on the reach curve
    int32 number_plotting_points = 1;

    // Maximum impression count that should be plotted
    int64 max_impression_count = 2;
  }
```
___
*[`src/main/proto/wfa/measurement/reporting/v1alpha/metric.proto` line 104 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/504#-N1EnKsfA8K5zzCvNv-r:-N1EnKsfA8K5zzCvNv-s:b-pfisdd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/041d3a593f3c84086890986fef94720b46e53b33/src/main/proto/wfa/measurement/reporting/v1alpha/metric.proto#L104)):*
> ```protobuf
>   }
> 
>   // A setOperation associated with a name.
> ```

nit: `` `SetOperation` ``



_Code quote:_
```protobuf
setOperation
```
___
*[`src/main/proto/wfa/measurement/reporting/v1alpha/metric.proto` line 115 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/504#-N1EoYVSBbvP2Ff8v2px:-N1EoYVSBbvP2Ff8v2py:b-vdhdo0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/041d3a593f3c84086890986fef94720b46e53b33/src/main/proto/wfa/measurement/reporting/v1alpha/metric.proto#L115)):*
> ```protobuf
>   }
> 
>   // A list of named setOperations on which the same metric will be applied.
> ```

nit: same here



_Code quote:_
```protobuf
setOperations
```
___
*[`src/main/proto/wfa/measurement/reporting/v1alpha/report.proto` line 43 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/504#-N1EokyoCmygAaITU29g:-N1EokyoCmygAaITU29h:bjeungo) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/041d3a593f3c84086890986fef94720b46e53b33/src/main/proto/wfa/measurement/reporting/v1alpha/report.proto#L43)):*
> ```protobuf
>   }];
> 
>   // Map of EventGroup to filter predicate.
> ```

nit: this is actually the map entry



_Code quote:_
```protobuf
Map of EventGroup to filter predicate.
```
___
*[`src/main/proto/wfa/measurement/reporting/v1alpha/report.proto` line 57 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/504#-N1Eoo-xDANOKkjjROmq:-N1Eoo-xDANOKkjjROmr:b3yky3c) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/041d3a593f3c84086890986fef94720b46e53b33/src/main/proto/wfa/measurement/reporting/v1alpha/report.proto#L57)):*
> ```protobuf
>   }
> 
>   // A list of maps of EventGroup to filter predicate.
> ```

nit: this is the map itself



_Code quote:_
```protobuf
  // A list of maps of EventGroup to filter predicate.
```
___
*[`src/main/proto/wfa/measurement/reporting/v1alpha/report.proto` line 69 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/504#-N1Ep5dw0YVKHQ6CQqQn:-N1Ep5dw0YVKHQ6CQqQo:bvpd44l) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/041d3a593f3c84086890986fef94720b46e53b33/src/main/proto/wfa/measurement/reporting/v1alpha/report.proto#L69)):*
> ```protobuf
>   }
> 
>   // A List of metrics that are included in `Report`.
> ```

nit: you can just say "The metrics that are"

Saying it's a List implies ordering.



_Code quote:_
```protobuf
A List of metrics
```


<!-- Sent from Reviewable.io -->

2022-05-04 16:28 UTC, SanjayVas requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/504)* status: all files reviewed, 7 unresolved discussions (waiting on @riemanli)

___
*[`src/main/proto/wfa/measurement/reporting/v1alpha/event_group.proto` line 41 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/504#-N1Em7ZMA3urSixQ3AnI:-N1EtepQ9RJIgcxm0BIw:b-k424cr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/041d3a593f3c84086890986fef94720b46e53b33/src/main/proto/wfa/measurement/reporting/v1alpha/event_group.proto#L41)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Add `event_group_reference_id` field from CMMS API.
</blockquote></details>

Also add event templates, and a TODO for adding metadata.


<!-- Sent from Reviewable.io -->

2022-05-04 20:17 UTC, riemanli commented
*[`src/main/proto/wfa/measurement/reporting/v1alpha/event_group.proto` line 41 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/504#-N1Em7ZMA3urSixQ3AnI:-N1Fhnvz5OziTEtCDhf0:bahfstv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/041d3a593f3c84086890986fef94720b46e53b33/src/main/proto/wfa/measurement/reporting/v1alpha/event_group.proto#L41)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Also add event templates, and a TODO for adding metadata.
</blockquote></details>

Added `event_group_reference_id ` and `event_templates`. Please let me know if it looks good to you.


<!-- Sent from Reviewable.io -->

2022-05-04 20:19 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/504)* status: 10 of 13 files reviewed, 7 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/proto/wfa/measurement/reporting/v1alpha/metric.proto` line 43 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/504#-N1EmqzM61Z_xndSVhfA:-N1FiBRc4F9AZHl_3Ukt:bss4a2b) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/041d3a593f3c84086890986fef94720b46e53b33/src/main/proto/wfa/measurement/reporting/v1alpha/metric.proto#L43)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Leave this out for now. Let's only keep the items that we know we're planning on implementing. The oneof structure is intended to be able to support adding new types in the future.
</blockquote></details>

Removed.
___
*[`src/main/proto/wfa/measurement/reporting/v1alpha/metric.proto` line 104 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/504#-N1EnKsfA8K5zzCvNv-r:-N1FiDC3-QNi4QQIioI4:b-cszsw0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/041d3a593f3c84086890986fef94720b46e53b33/src/main/proto/wfa/measurement/reporting/v1alpha/metric.proto#L104)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: `` `SetOperation` ``
</blockquote></details>

Modified.
___
*[`src/main/proto/wfa/measurement/reporting/v1alpha/metric.proto` line 115 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/504#-N1EoYVSBbvP2Ff8v2px:-N1FiF-n3ZQYJ8A1QmD1:b-cszsw0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/041d3a593f3c84086890986fef94720b46e53b33/src/main/proto/wfa/measurement/reporting/v1alpha/metric.proto#L115)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: same here
</blockquote></details>

Modified.
___
*[`src/main/proto/wfa/measurement/reporting/v1alpha/report.proto` line 43 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/504#-N1EokyoCmygAaITU29g:-N1FiHMt2oPpnlqv_0RI:b-ml0l1s) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/041d3a593f3c84086890986fef94720b46e53b33/src/main/proto/wfa/measurement/reporting/v1alpha/report.proto#L43)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: this is actually the map entry
</blockquote></details>

Modified the comment.
___
*[`src/main/proto/wfa/measurement/reporting/v1alpha/report.proto` line 57 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/504#-N1Eoo-xDANOKkjjROmq:-N1FiLl_9k2KhXkGQh7O:b-cszsw0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/041d3a593f3c84086890986fef94720b46e53b33/src/main/proto/wfa/measurement/reporting/v1alpha/report.proto#L57)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: this is the map itself
</blockquote></details>

Modified.
___
*[`src/main/proto/wfa/measurement/reporting/v1alpha/report.proto` line 69 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/504#-N1Ep5dw0YVKHQ6CQqQn:-N1FiOEz7Ppjp3-LHT6D:b-cszsw0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/041d3a593f3c84086890986fef94720b46e53b33/src/main/proto/wfa/measurement/reporting/v1alpha/report.proto#L69)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: you can just say "The metrics that are"

Saying it's a List implies ordering.
</blockquote></details>

Modified.


<!-- Sent from Reviewable.io -->

2022-05-05 19:12 UTC, SanjayVas approved these changes
> Reviewed 3 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/504)* status: all files reviewed, 1 unresolved discussion (waiting on @riemanli)

___
*[`src/main/proto/wfa/measurement/reporting/v1alpha/event_group.proto` line 55 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/504#-N1KcSveAoVaqCz_it0d:-N1KcSveAoVaqCz_it0e:bhdz9eo) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6dce5ffcca13bd4e1b7f8145225182af0b82d2b4/src/main/proto/wfa/measurement/reporting/v1alpha/event_group.proto#L55)):*
> ```protobuf
>     string type = 1 [(google.api.field_behavior) = REQUIRED];
> 
>     // TODO(@SanjayVas) Add metadata
> ```

nit: `@chipingyeh`



_Code quote:_
```protobuf
@SanjayVas
```


<!-- Sent from Reviewable.io -->

2022-05-05 21:35 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/504)* status: 12 of 13 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/proto/wfa/measurement/reporting/v1alpha/event_group.proto` line 55 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/504#-N1KcSveAoVaqCz_it0d:-N1L8Wo6As-I3zy8fLJS:b-cszsw0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6dce5ffcca13bd4e1b7f8145225182af0b82d2b4/src/main/proto/wfa/measurement/reporting/v1alpha/event_group.proto#L55)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: `@chipingyeh`
</blockquote></details>

Modified.


<!-- Sent from Reviewable.io -->

2022-05-05 22:08 UTC, riemanli commented
Hi @chipingyeh, this is the PR for the API design of the reporting server. Would you mind if I ask you to be our external reviewer for this PR?

Looking forward to hearing from you soon. Thank you.

2022-05-06 20:46 UTC, chipingyeh approved these changes
> Reviewed 1 of 3 files at r5, 1 of 7 files at r7, 5 of 8 files at r8, 2 of 3 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/504)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)



<!-- Sent from Reviewable.io -->

2022-05-09 16:38 UTC, merged