WIP: Support impression set operations for reach.
world-federation-of-advertisers/cross-media-measurement pull request #518
Opened 2022-04-07 19:13 UTC by SanjayVas

2022-04-07 23:56 UTC, riemanli requested changes
> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/518)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @riemanli and @SanjayVas)

___
*[src/main/proto/wfa/measurement/reporting/v1alpha/metric_set.proto, line 27 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/518#-N-5QiVA9fj8dGERxYSr:-N-5QiVA9fj8dGERxYSs:b3xpg1g) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1d8624f9b2bfd9cc5ab2e075a7b9aa6779de6ca9/src/main/proto/wfa/measurement/reporting/v1alpha/metric_set.proto#L27)):*
> ```protobuf
> 
> // A metric set using data from the Cross-Media Measurement System.
> message MetricSet {
> ```

Could you explain the concept of `MetricSet` and provide some example use case about `SetOperation` and `SetSpec`?


<!-- Sent from Reviewable.io -->

2022-04-08 00:16 UTC, rmirisola commented on src/main/proto/wfa/measurement/reporting/v1alpha/metric_set.proto
> +    TimeInterval time_interval = 4;
Should this be a repeated field?

2022-04-08 00:16 UTC, rmirisola commented on src/main/proto/wfa/measurement/reporting/v1alpha/metric_set.proto
> +        Type operation = 1;
Did you mean SetOperation instead of Type?

2022-04-08 00:16 UTC, rmirisola commented on src/main/proto/wfa/measurement/reporting/v1alpha/metric_set.proto
> +message MetricSet {
Is the idea that a Report will be N MetricSets? are we defining are Report elsewhere/later?

2022-04-08 00:16 UTC, rmirisola commented on src/main/proto/wfa/measurement/reporting/v1alpha/metric_set.proto
> +      string filter = 3;
I wonder if this should live at the MetricSet level instead, or initially, we could add a lower level one later.

2022-04-08 00:49 UTC, SanjayVas reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/518)* status: 3 of 4 files reviewed, 5 unresolved discussions (waiting on @riemanli, @rmirisola, and @SanjayVas)

___
*[src/main/proto/wfa/measurement/reporting/v1alpha/metric_set.proto, line 27 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/518#-N-5QiVA9fj8dGERxYSr:-N-5cLjM4Ocvu4x9P4bZ:bgfaalb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1d8624f9b2bfd9cc5ab2e075a7b9aa6779de6ca9/src/main/proto/wfa/measurement/reporting/v1alpha/metric_set.proto#L27)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Could you explain the concept of `MetricSet` and provide some example use case about `SetOperation` and `SetSpec`?
</blockquote></details>

Will do. The plan is to give examples of what `MetricSet`s would look like for building some of the ANA mockup reports.
___
*[src/main/proto/wfa/measurement/reporting/v1alpha/metric_set.proto, line 27 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/518#-N-57A_LGbilPFw-9Mmt-r1-27:-N-5cZ662upsg3Vm10fS:bb77ufg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1d8624f9b2bfd9cc5ab2e075a7b9aa6779de6ca9/src/main/proto/wfa/measurement/reporting/v1alpha/metric_set.proto#L27)):*
<details><summary><i>Previously, rmirisola wrote…</i></summary><blockquote>

Is the idea that a Report will be N MetricSets? are we defining are Report elsewhere/later?
</blockquote></details>

Yes.
___
*[src/main/proto/wfa/measurement/reporting/v1alpha/metric_set.proto, line 60 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/518#-N-57A_LGbilPFw-9Mmt-r1-60:-N-5caUFAWJULCaJdXxi:b7jrw1x) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1d8624f9b2bfd9cc5ab2e075a7b9aa6779de6ca9/src/main/proto/wfa/measurement/reporting/v1alpha/metric_set.proto#L60)):*
<details><summary><i>Previously, rmirisola wrote…</i></summary><blockquote>

Should this be a repeated field?
</blockquote></details>

You can either compute over a single time interval, or a repeated set of consecutive intervals. Is there a reason to allow multiple non-consecutive unequal intervals?
___
*[src/main/proto/wfa/measurement/reporting/v1alpha/metric_set.proto, line 92 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/518#-N-57A_LGbilPFw-9Mmt-r1-92:-N-5csA9-KQvPQZyBe1k:b-xc6qbi) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1d8624f9b2bfd9cc5ab2e075a7b9aa6779de6ca9/src/main/proto/wfa/measurement/reporting/v1alpha/metric_set.proto#L92)):*
<details><summary><i>Previously, rmirisola wrote…</i></summary><blockquote>

I wonder if this should live at the MetricSet level instead, or initially, we could add a lower level one later.
</blockquote></details>

This is specifically to allow for a set in the venn diagram to be defined by properties of the event. e.g. to determine the incremental reach of a given demographic.
___
*[src/main/proto/wfa/measurement/reporting/v1alpha/metric_set.proto, line 97 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/518#-N-57A_LGbilPFw-9Mmt-r1-97:-N-5dOnwBb7QQTOIqEfh:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1d8624f9b2bfd9cc5ab2e075a7b9aa6779de6ca9/src/main/proto/wfa/measurement/reporting/v1alpha/metric_set.proto#L97)):*
<details><summary><i>Previously, rmirisola wrote…</i></summary><blockquote>

Did you mean SetOperation instead of Type?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-04-08 16:28 UTC, SanjayVas commented
Sample MetricSet for "Cross-Media" column of Frequency Histogram in ANA Mockup (assuming it's users that saw the ad on both channels):

```
# proto-file: src/main/proto/wfa/measurement/reporting/v1alpha/metric_set.proto
# proto-message: MetricSet
measurement_consumer: "measurementConsumers/comScore"
event_group_filters {
  key: "measurementConsumers/comScore/dataProviders/digitalEdp1/eventGroups/campaign1"
  value: "age_bucket = AgeBucket.18_34 && is_viewable = true"
}
event_group_filters {
  key: "measurementConsumers/comScore/dataProviders/tvEdp1/eventGroups/campaign1"
  value: "age_bucket = AgeBucket.18_34"
}
metrics: FREQUENCY_HISTOGRAM
time_interval {
  start_time {
    seconds: 1649380087
  }
  end_time {
    seconds: 1649466487
  }
}
set_operation {
  type: INTERSECTION
  lhs {
    spec {
      display_name: "Digital"
      event_groups: "measurementConsumers/comScore/dataProviders/digitalEdp1/eventGroups/campaign1"
    }
  }
  rhs {
    spec {
      display_name: "TV"
      event_groups: "measurementConsumers/comScore/dataProviders/tvEdp1/eventGroups/campaign1"
    }
  }
}
```

Sample MetricSet for daily cumulative reach across all EDPs:

```
# proto-file: src/main/proto/wfa/measurement/reporting/v1alpha/metric_set.proto
# proto-message: MetricSet
measurement_consumer: "measurementConsumers/comScore"
event_group_filters {
  key: "measurementConsumers/comScore/dataProviders/digitalEdp1/eventGroups/campaign1"
  value: "age_bucket = AgeBucket.18_34 && is_viewable = true"
}
event_group_filters {
  key: "measurementConsumers/comScore/dataProviders/tvEdp1/eventGroups/campaign1"
  value: "age_bucket = AgeBucket.18_34"
}
metrics: REACH
repeated_time_interval {
  start_time {
    seconds: 1649380087
  }
  increment {
    seconds: 86400  # One standard day.
  }
  num_intervals: 30
  cumulative: true
}
set_operation {
  type: UNION
  lhs {
    spec {
      display_name: "All"
      event_groups: "measurementConsumers/comScore/dataProviders/digitalEdp1/eventGroups/campaign1"
      event_groups: "measurementConsumers/comScore/dataProviders/tvEdp1/eventGroups/campaign1"
    }
  }
}
```

2022-04-08 16:56 UTC, rmirisola requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/518)* status: 3 of 4 files reviewed, 5 unresolved discussions (waiting on @riemanli, @rmirisola, and @SanjayVas)

___
*[src/main/proto/wfa/measurement/reporting/v1alpha/metric_set.proto, line 60 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/518#-N-57A_LGbilPFw-9Mmt-r1-60:-N-956Uv2xRZY9-Bp_3c:b-2jjrud) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1d8624f9b2bfd9cc5ab2e075a7b9aa6779de6ca9/src/main/proto/wfa/measurement/reporting/v1alpha/metric_set.proto#L60)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

You can either compute over a single time interval, or a repeated set of consecutive intervals. Is there a reason to allow multiple non-consecutive unequal intervals?
</blockquote></details>

Say you want to compute last day, last week and last month's reach


<!-- Sent from Reviewable.io -->

2022-04-08 18:50 UTC, riemanli requested changes
> Reviewed 1 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/518)* status: all files reviewed, 7 unresolved discussions (waiting on @rmirisola and @SanjayVas)

___
*[src/main/proto/wfa/measurement/reporting/v1alpha/metric_set.proto, line 28 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/518#-N-9Q6j0-f0Sc0T_x_Qj:-N-9Q6j0-f0Sc0T_x_Qk:b-8af193) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3a2ff2c1a16621aff30edecba4294f261cb8b9f9/src/main/proto/wfa/measurement/reporting/v1alpha/metric_set.proto#L28)):*
> ```protobuf
> // A metric set using data from the Cross-Media Measurement System.
> message MetricSet {
>   string measurement_consumer = 1 [(google.api.resource_reference) = {
> ```

Are MC and `EventGroupFilter` the same over `metric_sets` in a report? If so, should they be moved to `Report` level?
___
*[src/main/proto/wfa/measurement/reporting/v1alpha/metric_set.proto, line 57 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/518#-N-9QvyKBDDAS-WRDlYD:-N-9QvyKBDDAS-WRDlYE:b6kaibm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3a2ff2c1a16621aff30edecba4294f261cb8b9f9/src/main/proto/wfa/measurement/reporting/v1alpha/metric_set.proto#L57)):*
> ```protobuf
>     WATCH_DURATION = 5;
>   }
>   repeated Metric metrics = 3 [(google.api.field_behavior) = REQUIRED];
> ```

I don't see metric specific parameters here. Are they going to be defined at `Report` level?


<!-- Sent from Reviewable.io -->

2022-04-08 18:52 UTC, riemanli commented
*[src/main/proto/wfa/measurement/reporting/v1alpha/metric_set.proto, line 57 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/518#-N-9QvyKBDDAS-WRDlYD:-N-9W5_o4lbAW3GDaIoA:br6wlgr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3a2ff2c1a16621aff30edecba4294f261cb8b9f9/src/main/proto/wfa/measurement/reporting/v1alpha/metric_set.proto#L57)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

I don't see metric specific parameters here. Are they going to be defined at `Report` level?
</blockquote></details>

If so, that means we assume metric specific parameters are the same in one report.


<!-- Sent from Reviewable.io -->

2022-04-09 00:04 UTC, SanjayVas reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/518)* status: 1 of 7 files reviewed, 7 unresolved discussions (waiting on @riemanli, @rmirisola, and @SanjayVas)

___
*[src/main/proto/wfa/measurement/reporting/v1alpha/metric_set.proto, line 60 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/518#-N-57A_LGbilPFw-9Mmt-r1-60:-N-AcaFf59sZQ4iT9Jql:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1d8624f9b2bfd9cc5ab2e075a7b9aa6779de6ca9/src/main/proto/wfa/measurement/reporting/v1alpha/metric_set.proto#L60)):*
<details><summary><i>Previously, rmirisola (Raimundo Mirisola) wrote…</i></summary><blockquote>

Say you want to compute last day, last week and last month's reach
</blockquote></details>

Done.
___
*[src/main/proto/wfa/measurement/reporting/v1alpha/metric_set.proto, line 28 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/518#-N-9Q6j0-f0Sc0T_x_Qj:-N-AcejhAxImVCp1p7XY:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3a2ff2c1a16621aff30edecba4294f261cb8b9f9/src/main/proto/wfa/measurement/reporting/v1alpha/metric_set.proto#L28)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Are MC and `EventGroupFilter` the same over `metric_sets` in a report? If so, should they be moved to `Report` level?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-04-11 17:06 UTC, riemanli requested changes
> Reviewed 4 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/518)* status: 5 of 7 files reviewed, 6 unresolved discussions (waiting on @riemanli, @rmirisola, and @SanjayVas)

___
*[src/main/proto/wfa/measurement/reporting/v1alpha/metric_set.proto, line 57 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/518#-N-9QvyKBDDAS-WRDlYD:-N-OYm-v8VS6iS3Jh3Xd:bik3uzh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3a2ff2c1a16621aff30edecba4294f261cb8b9f9/src/main/proto/wfa/measurement/reporting/v1alpha/metric_set.proto#L57)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

If so, that means we assume metric specific parameters are the same in one report.
</blockquote></details>

In the previous design, we treat `available privacy budget` as one of the report types. With this new design, do we want to include `available privacy budget` here as a metric? 


<!-- Sent from Reviewable.io -->

2022-04-11 17:25 UTC, SanjayVas reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/518)* status: 5 of 7 files reviewed, 6 unresolved discussions (waiting on @riemanli, @rmirisola, and @SanjayVas)

___
*[src/main/proto/wfa/measurement/reporting/v1alpha/metric_set.proto, line 57 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/518#-N-9QvyKBDDAS-WRDlYD:-N-OdPJp7Io7I_KvRhuj:b-atu1on) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3a2ff2c1a16621aff30edecba4294f261cb8b9f9/src/main/proto/wfa/measurement/reporting/v1alpha/metric_set.proto#L57)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

In the previous design, we treat `available privacy budget` as one of the report types. With this new design, do we want to include `available privacy budget` here as a metric? 
</blockquote></details>

Which option did we decide on for privacy budget info for M3?

If it's a query, is "available privacy budget" asking for all buckets? Would we rather have an estimated cost for a given report? If doing estimated cost for a report, the way to handle it in the API IMO would be to have Reports not immediately start, and have it be a different report type that takes in an existing Report resource name as a parameter.


<!-- Sent from Reviewable.io -->

2022-04-11 17:32 UTC, riemanli requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/518)* status: 5 of 7 files reviewed, 6 unresolved discussions (waiting on @riemanli, @rmirisola, and @SanjayVas)

___
*[src/main/proto/wfa/measurement/reporting/v1alpha/metric_set.proto, line 57 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/518#-N-9QvyKBDDAS-WRDlYD:-N-OewggENV2CuDUJc_f:b-6u8pjf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3a2ff2c1a16621aff30edecba4294f261cb8b9f9/src/main/proto/wfa/measurement/reporting/v1alpha/metric_set.proto#L57)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Which option did we decide on for privacy budget info for M3?

If it's a query, is "available privacy budget" asking for all buckets? Would we rather have an estimated cost for a given report? If doing estimated cost for a report, the way to handle it in the API IMO would be to have Reports not immediately start, and have it be a different report type that takes in an existing Report resource name as a parameter.
</blockquote></details>

I might be wrong, but I remember in the meeting with Comscore, they were interested in the privacy budget features. @rmirisola is "available privacy budget" required for M3?


<!-- Sent from Reviewable.io -->

2022-04-12 01:07 UTC, matthewclegg requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/518)* status: 4 of 7 files reviewed, 8 unresolved discussions (waiting on @matthewclegg, @riemanli, @rmirisola, and @SanjayVas)

___
*[src/main/proto/wfa/measurement/reporting/v1alpha/metric_set.proto, line 42 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/518#-N-QHH-L5Wy6eX3mAMYm:-N-QHH-L5Wy6eX3mAMYn:bnp2f6l) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9a3737e360f560bfedf18a8e512dac1875738351/src/main/proto/wfa/measurement/reporting/v1alpha/metric_set.proto#L42)):*
> ```protobuf
>   }
> 
>   oneof metric {
> ```

I would make this repeated.
___
*[src/main/proto/wfa/measurement/reporting/v1alpha/metric_set.proto, line 101 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/518#-N-QHOQ91yzaS5gzFG1I:-N-QHOQ91yzaS5gzFG1J:b-rekmih) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9a3737e360f560bfedf18a8e512dac1875738351/src/main/proto/wfa/measurement/reporting/v1alpha/metric_set.proto#L101)):*
> ```protobuf
>     string display_name = 1 [(google.api.field_behavior) = REQUIRED];
> 
>     SetOperation set_operation = 2;
> ```

Overall, I like this structure, but I think it should be refactored so that the specification of the data sources (event groups) is independent of the specification of the computations that are to be performed on the data.


<!-- Sent from Reviewable.io -->

2022-04-12 17:45 UTC, SanjayVas reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/518)* status: 4 of 7 files reviewed, 8 unresolved discussions (waiting on @matthewclegg, @riemanli, @rmirisola, and @SanjayVas)

___
*[src/main/proto/wfa/measurement/reporting/v1alpha/metric_set.proto, line 42 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/518#-N-QHH-L5Wy6eX3mAMYm:-N-Trc-6-KGeBfC9Pfpg:b-jg11oz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9a3737e360f560bfedf18a8e512dac1875738351/src/main/proto/wfa/measurement/reporting/v1alpha/metric_set.proto#L42)):*
<details><summary><i>Previously, matthewclegg (Matthew Clegg) wrote…</i></summary><blockquote>

I would make this repeated.
</blockquote></details>

It was previously repeated. In the discussion session with @rmirisola and @riemanli, we decided to have this not be repeated in favor of repeating NamedSetOperation below. The idea is to have fewer repeated dimensions within MetricSet to make things simpler, and have multiple metrics be handled by repeating the MetricSet itself in the Report.
___
*[src/main/proto/wfa/measurement/reporting/v1alpha/metric_set.proto, line 101 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/518#-N-QHOQ91yzaS5gzFG1I:-N-Trx5h5-k3n99UGmU3:bgamv83) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9a3737e360f560bfedf18a8e512dac1875738351/src/main/proto/wfa/measurement/reporting/v1alpha/metric_set.proto#L101)):*
<details><summary><i>Previously, matthewclegg (Matthew Clegg) wrote…</i></summary><blockquote>

Overall, I like this structure, but I think it should be refactored so that the specification of the data sources (event groups) is independent of the specification of the computations that are to be performed on the data.
</blockquote></details>

Yes, I was thinking about making that change. Possibly having the set definitions as a resource (bringing back a version of the "reporting group" concept). Basically SetSpec here would turn into the ReportingGroup resource, such that you define your ReportingGroups and then just reference them by resource name here.

@rmirisola WDYT?


<!-- Sent from Reviewable.io -->

2022-04-12 22:49 UTC, SanjayVas commented
From discussion with @riemanli, pulled the time interval specification up to the `Report` level. This way all `Metric`s (renamed from `MetricSet`) in a `Report` cover the same time intervals. If you want to cover different ones, you need to run a separate Report.

2022-04-13 01:09 UTC, riemanli requested changes
> Reviewed 1 of 4 files at r1, 2 of 2 files at r4, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/518)* status: all files reviewed, 9 unresolved discussions (waiting on @riemanli, @rmirisola, and @SanjayVas)

___
*[src/main/proto/wfa/measurement/reporting/v1alpha/metric.proto, line 47 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/518#-N-VRqca-eoJxcqDLuYk:-N-VRqcb0WioxdfG7--p:b5ikpsp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/df03c5b5a79e2f99582431407f9942822364cf79/src/main/proto/wfa/measurement/reporting/v1alpha/metric.proto#L47)):*
> ```protobuf
>     WatchDurationParams watch_duration = 4;
>     ReachParams reach_curve = 5;
>   }
> ```

Provide a more comprehensive list of metrics here for reference. Not all of them needs to be implemented for M3.

* Reach
* Reach percent
* GRPs/TRPs
* Average frequency
* Exposure duration
* Average duration
* Impressions
* Population
* Watch time
* Frequency histogram
* Reach curves


<!-- Sent from Reviewable.io -->

2022-04-13 17:58 UTC, SanjayVas reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/518)* status: all files reviewed, 9 unresolved discussions (waiting on @riemanli, @rmirisola, and @SanjayVas)

___
*[src/main/proto/wfa/measurement/reporting/v1alpha/metric.proto, line 47 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/518#-N-VRqca-eoJxcqDLuYk:-N-Z2jN_1vijgVwLtQ9Y:b-wp1gpj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/df03c5b5a79e2f99582431407f9942822364cf79/src/main/proto/wfa/measurement/reporting/v1alpha/metric.proto#L47)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Provide a more comprehensive list of metrics here for reference. Not all of them needs to be implemented for M3.

* Reach
* Reach percent
* GRPs/TRPs
* Average frequency
* Exposure duration
* Average duration
* Impressions
* Population
* Watch time
* Frequency histogram
* Reach curves
</blockquote></details>

1. I'm pretty sure a lot of these aren't actually different metric types and can be computed from metric results. e.g. I believe average frequency can be computed from a frequency histogram. We shouldn't be adding metric types that are things that the user can do in a report spreadsheet.
2. I'm against putting anything into this API that won't be implemented in M3. One of the reasons for the oneof structure is to allow new metric types to be added later, as adding a field to a oneof is a backwards-compatible change.


<!-- Sent from Reviewable.io -->

2022-04-13 21:31 UTC, riemanli requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/518)* status: all files reviewed, 9 unresolved discussions (waiting on @rmirisola and @SanjayVas)

___
*[src/main/proto/wfa/measurement/reporting/v1alpha/metric.proto, line 47 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/518#-N-VRqca-eoJxcqDLuYk:-N-ZpbQY-A_oxihw5XKf:bqrfan2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/df03c5b5a79e2f99582431407f9942822364cf79/src/main/proto/wfa/measurement/reporting/v1alpha/metric.proto#L47)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

1. I'm pretty sure a lot of these aren't actually different metric types and can be computed from metric results. e.g. I believe average frequency can be computed from a frequency histogram. We shouldn't be adding metric types that are things that the user can do in a report spreadsheet.
2. I'm against putting anything into this API that won't be implemented in M3. One of the reasons for the oneof structure is to allow new metric types to be added later, as adding a field to a oneof is a backwards-compatible change.
</blockquote></details>

Understood.


<!-- Sent from Reviewable.io -->

2022-04-18 20:22 UTC, SanjayVas reviewed
Renamed `SetSpec` to `ReportingSet` and made it a separate resource type.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/518#-:-N-yKiUj5UsNMNb6pbgb:b-q6k05a)* status: 3 of 9 files reviewed, 9 unresolved discussions (waiting on @matthewclegg, @riemanli, @rmirisola, and @SanjayVas)



<!-- Sent from Reviewable.io -->

2022-04-18 20:25 UTC, SanjayVas reviewed
> Dismissed @riemanli from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/518)* status: 3 of 9 files reviewed, 8 unresolved discussions (waiting on @riemanli, @rmirisola, and @SanjayVas)

___
*[src/main/proto/wfa/measurement/reporting/v1alpha/metric_set.proto, line 57 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/518#-N-9QvyKBDDAS-WRDlYD:-N-yKxD382n9uhDJI8ry:bjmgv3k) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3a2ff2c1a16621aff30edecba4294f261cb8b9f9/src/main/proto/wfa/measurement/reporting/v1alpha/metric_set.proto#L57)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

I might be wrong, but I remember in the meeting with Comscore, they were interested in the privacy budget features. @rmirisola is "available privacy budget" required for M3?
</blockquote></details>

Whether it's required is still TBD. We may be able to avoid it depending on the expected privacy costs of the queries in the ANA proof-of-concept. As a result, I've left it out for now.


<!-- Sent from Reviewable.io -->

2022-04-19 21:17 UTC, riemanli approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 6 of 6 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/518#-:-N02epzh9phaAWYVbsec:bnfp4nl)* status: all files reviewed, 8 unresolved discussions (waiting on @rmirisola and @SanjayVas)



<!-- Sent from Reviewable.io -->

2022-04-19 22:53 UTC, merged