Privacy Bucket Mapper implementation
world-federation-of-advertisers/cross-media-measurement pull request #519
Opened 2022-04-08 00:15 UTC by uakyol

2022-04-10 23:38 UTC, uakyol commented
First pass is ready for review, however, there are a few unanswered questions : 

1) I think the PrivacyBucket definition is actually wrong. It should have list of age ranges etc... 
2) We should have 300 vid buckets. Should they be in the range 0..1 ?
3) We need Timezone to get from time in requisition spec to date in Privacy Bucket mapping. 
4) Where do we get the MCId? It doesn't seem to be in measurement or requisition specs.

2022-04-11 21:21 UTC, SanjayVas reviewed
> We need Timezone to get from time in requisition spec to date in Privacy Bucket mapping.

Are we intending to use civil calendar days or 24h days? The former means a day might have 23 or 25 hours at DST transitions in that timezone in cast that matters.

> Where do we get the MCId? It doesn't seem to be in measurement or requisition specs.

The Measurement resource is owned by the MeasurementConsumer, so the Measurement resource name starts with the MeasurementConsumer resource name. e.g. `measurementConsumers/bIlI8Sh5-V4/measurements/airk7teGDBs`.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/519#-:-N-PS1z11hAJRn6CV_ib:bqftsgp)* status: 0 of 24 files reviewed, all discussions resolved (waiting on @duliomatos1 and @matthewclegg)



<!-- Sent from Reviewable.io -->

2022-04-11 21:45 UTC, uakyol reviewed
thanks so much Sanjay, decided to split this PR into 2 and these questions should have been on the other one. : https://github.com/world-federation-of-advertisers/cross-media-measurement/pull/524 . Let's continue the discussion there.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/519#-:-N-P_Qbt6inuv5g07XTY:bdexzr7)* status: 0 of 24 files reviewed, all discussions resolved (waiting on @duliomatos1 and @matthewclegg)



<!-- Sent from Reviewable.io -->

2022-04-12 21:57 UTC, SanjayVas requested changes
> Reviewed 1 of 21 files at r2, 1 of 1 files at r10, 1 of 1 files at r11.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/519)* status: 2 of 24 files reviewed, 15 unresolved discussions (waiting on @duliomatos1, @matthewclegg, @SanjayVas, and @uakyol)

___
*[src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/EventFilters.kt, line 31 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/519#-N-Ue4Sp-9fjJxl-h6f4:-N-Ue4Sp-9fjJxl-h6f5:b-s4e7yt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3a9cf0e3abd42cdd9e30a877a0f520796c34f858/src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/EventFilters.kt#L31)):*
> ```Kotlin
>    * should be filtered or not, based on the filtering CEL expression.
>    *
>    * @param defaultEventMessage is a protobuf Message default instance for a message that contains
> ```

nit: `default instance for a [Message]`



_Code quote:_
```Kotlin
is a protobuf Message default instance for a message
```
___
*[src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/EventFilters.kt, line 34 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/519#-N-Ubqn95fr9_KPeNf4v:-N-Ubqn95fr9_KPeNf4w:b2kgyk7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3a9cf0e3abd42cdd9e30a877a0f520796c34f858/src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/EventFilters.kt#L34)):*
> ```Kotlin
>    * each type of event template as fields. See `event_annotations.proto`.
>    *
>    * @param operativeFields are fields in this cel expression that will be kept after the
> ```

nit: drop

The format is `@param <name> <summary fragment>`



_Code quote:_
```Kotlin
are 
```
___
*[src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/EventFilters.kt, line 36 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/519#-N-UbEp53skRN8r6Vh2p:-N-UbEp53skRN8r6Vh2q:b-epicfj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3a9cf0e3abd42cdd9e30a877a0f520796c34f858/src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/EventFilters.kt#L36)):*
> ```Kotlin
>    * @param operativeFields are fields in this cel expression that will be kept after the
>    * normalization operation. If provided, the expression is normalized by bubbling down all the
>    * negation operations to the leafs by appliying De Morgan's laws recursively and by setting all
> ```

`applying`



_Code quote:_
```Kotlin
appliying
```
___
*[src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/EventFilters.kt, line 39 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/519#-N-UdrVM5rlH6CbCwATS:-N-UdrVM5rlH6CbCwATT:b-tollsi) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3a9cf0e3abd42cdd9e30a877a0f520796c34f858/src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/EventFilters.kt#L39)):*
> ```Kotlin
>    * the leaf comparison nodes (e.g. x == 47 ) that contain any field other than the operative
>    * fields to true.
>    *
> ```

nit: blank lines between param
___
*[src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/EventFilters.kt, line 40 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/519#-N-UdfF0Du6C5u3yD9N7:-N-UdfF0Du6C5u3yD9N8:b-lxuq6q) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3a9cf0e3abd42cdd9e30a877a0f520796c34f858/src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/EventFilters.kt#L40)):*
> ```Kotlin
>    * fields to true.
>    *
>    * Throws a [EventFilterValidationException].
> ```

Use `@throws`, and explain the condition(s) under which the exception is thrown.



_Code quote:_
```Kotlin

   * Throws a [EventFilterValidationException].
```
___
*[src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/validation/EventFilterValidator.kt, line 14 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/519#-N-Ug3X_-_DqJliqK9NH:-N-Ug3X_-_DqJliqK9NI:b-knwo3r) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3a9cf0e3abd42cdd9e30a877a0f520796c34f858/src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/validation/EventFilterValidator.kt#L14)):*
> ```Kotlin
>  * the License.
>  */
> package org.wfanet.measurement.eventdataprovider.eventfiltration.validation
> ```

I thought we already had a discussion about flattening out this structure. There doesn't seem to be much need for a `validation` subpackage if it just has the functions for validation and an exception. You can even put the exception in the same source file as this since it's only thrown from here.

Additionally, we always refer to EDP as just `DataProvider` in code (the "event" part is implied). Therefore the package should be `dataprovider` rather than `eventdataprovider`.

It's fine to do these cleanups in a separate PR.



_Code quote:_
```Kotlin
eventdataprovider.eventfiltration.validation
```
___
*[src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/validation/EventFilterValidator.kt, line 30 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/519#-N-Ujn8V24IKUWXiJd7L:-N-Ujn8V24IKUWXiJd7M:b7xsgoe) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3a9cf0e3abd42cdd9e30a877a0f520796c34f858/src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/validation/EventFilterValidator.kt#L30)):*
> ```Kotlin
> import org.projectnessie.cel.common.types.pb.ProtoTypeRegistry
> 
> private const val NOT_OPERATOR = "!_"
> ```

What's with the underscores? Are we using them as some kind of sentinel, or are they significant to the underlying CEL library/language?

If the former, seems it's getting into the "stringly typed" code smell (encoding extra information in a string rather then using more specific types/data structures).



_Code quote:_
```Kotlin
_
```
___
*[src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/validation/EventFilterValidator.kt, line 62 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/519#-N-Uf8A-71G3sBv63aK0:-N-Uf8A-71G3sBv63aK1:bonskkt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3a9cf0e3abd42cdd9e30a877a0f520796c34f858/src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/validation/EventFilterValidator.kt#L62)):*
> ```Kotlin
>  * * [EventFilterValidationException.Code.FIELD_COMPARISON_OUTSIDE_LEAF]
>  */
> object EventFilterValidator {
> ```

nit: `EventFilterValidator` sounds like a class with state. Maybe `EventFilterValidation`?

Fine to handle rename in a separate PR, perhaps along with package cleanup.



_Code quote:_
```Kotlin
EventFilterValidator
```
___
*[src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/validation/EventFilterValidator.kt, line 167 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/519#-N-UhVJq6c9eINn0OVf4:-N-UhVJq6c9eINn0OVf5:bl3t9jh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3a9cf0e3abd42cdd9e30a877a0f520796c34f858/src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/validation/EventFilterValidator.kt#L167)):*
> ```Kotlin
>   }
> 
>   fun validateExpression(expr: Expr) {
> ```

nit: `expression`

We tend to use more verbose names in JVM languages



_Code quote:_
```Kotlin
expr
```
___
*[src/main/kotlin/org/wfanet/measurement/eventdata [...]

2022-04-13 04:10 UTC, uakyol reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/519)* status: 0 of 24 files reviewed, 13 unresolved discussions (waiting on @duliomatos1, @matthewclegg, @param, and @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/EventFilters.kt, line 34 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/519#-N-Ubqn95fr9_KPeNf4v:-N-VLJNjDYsAFA0LgnBe:brvbj0h) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3a9cf0e3abd42cdd9e30a877a0f520796c34f858/src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/EventFilters.kt#L34)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: drop

The format is `@param <name> <summary fragment>`
</blockquote></details>

I dropped are. Is that what you mean. I thought this honors the format : @param <name> <summary fragment> . ?
___
*[src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/EventFilters.kt, line 36 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/519#-N-UbEp53skRN8r6Vh2p:-N-VLAKiCXeXrT4FQC_2:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3a9cf0e3abd42cdd9e30a877a0f520796c34f858/src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/EventFilters.kt#L36)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

`applying`
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/EventFilters.kt, line 39 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/519#-N-UdrVM5rlH6CbCwATS:-N-VPg1B482U18laB3FJ:b-3i4mkk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3a9cf0e3abd42cdd9e30a877a0f520796c34f858/src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/EventFilters.kt#L39)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: blank lines between param
</blockquote></details>

Im sorry couldn't understand this comment. there already is a blank line between params.
___
*[src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/EventFilters.kt, line 40 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/519#-N-UdfF0Du6C5u3yD9N7:-N-VMGHM4qKLBc1TsVOw:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3a9cf0e3abd42cdd9e30a877a0f520796c34f858/src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/EventFilters.kt#L40)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Use `@throws`, and explain the condition(s) under which the exception is thrown.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/validation/EventFilterValidator.kt, line 14 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/519#-N-Ug3X_-_DqJliqK9NH:-N-V95KM4SlYgzSFvYZp:b-7fesft) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3a9cf0e3abd42cdd9e30a877a0f520796c34f858/src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/validation/EventFilterValidator.kt#L14)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I thought we already had a discussion about flattening out this structure. There doesn't seem to be much need for a `validation` subpackage if it just has the functions for validation and an exception. You can even put the exception in the same source file as this since it's only thrown from here.

Additionally, we always refer to EDP as just `DataProvider` in code (the "event" part is implied). Therefore the package should be `dataprovider` rather than `eventdataprovider`.

It's fine to do these cleanups in a separate PR.
</blockquote></details>

thanks will do
___
*[src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/validation/EventFilterValidator.kt, line 30 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/519#-N-Ujn8V24IKUWXiJd7L:-N-V9-iM00EB_GpkM6HV:bfi1z23) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3a9cf0e3abd42cdd9e30a877a0f520796c34f858/src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/validation/EventFilterValidator.kt#L30)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

What's with the underscores? Are we using them as some kind of sentinel, or are they significant to the underlying CEL library/language?

If the former, seems it's getting into the "stringly typed" code smell (encoding extra information in a string rather then using more specific types/data structures).
</blockquote></details>

they are significant to CEL library/language
___
*[src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/validation/EventFilterValidator.kt, line 62 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/519#-N-Uf8A-71G3sBv63aK0:-N-V93lABrC2qummfNSA:bjsyhxz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3a9cf0e3abd42cdd9e30a877a0f520796c34f858/src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/validation/EventFilterValidator.kt#L62)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: `EventFilterValidator` sounds like a class with state. Maybe `EventFilterValidation`?

Fine to handle rename in a separate PR, perhaps along with package cleanup.
</blockquote></details>

thanks, will do
___
*[src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/validation/EventFilterValidator.kt, line 174 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/519#-N-UeoT53SZ1GoM88a-n:-N-VNWBy9lJrn8oDPLZ9:b5ht9o0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3a9cf0e3abd42cdd9e30a877a0f520796c34f858/src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/validation/EventFilterValidator.kt#L174)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Expand the abbreviation and/or document the function to explain what this is doing.
</blockquote></details>

Expanded the abbreviation, the documentation is at EventFilters level. I can copy that here too?
___
*[src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/validation/EventFilterValidator.kt, line 174 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/519#-N-Uhuss-8N27NJ4FI8N:-N-VNdpw3nuQsnUeM6cj:bl37r47) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3a9cf0e3abd42cdd9e30a877a0f520796c34f858/src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/validation/EventFilterValidator.kt#L174)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: `to` functions tend to be implemented as methods or extensions. In this case, this could be `fun Expr.toNnf(operativeFields: Set<String>, negate: Boolean = false): Expr`
</blockquote></details>

awesome thank you
___
*[src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/validation/EventFilterValidator.kt, line 274 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/519#-N-Uj0ik48rwiHwQg4MF:-N-VNroH6_cwuX5ED62_:b-7oh93d) ([raw file](ht [...]

2022-04-13 18:18 UTC, SanjayVas approved these changes
> Reviewed 9 of 21 files at r2, 2 of 6 files at r3, 9 of 9 files at r9, 4 of 4 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/519)* status: all files reviewed, 2 unresolved discussions (waiting on @duliomatos1, @matthewclegg, and @uakyol)

___
*[src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/EventFilters.kt, line 34 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/519#-N-Ubqn95fr9_KPeNf4v:-N-Z44Ch2rUbhf9eSyk5:b-d2m5es) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3a9cf0e3abd42cdd9e30a877a0f520796c34f858/src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/EventFilters.kt#L34)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

I dropped are. Is that what you mean. I thought this honors the format : @param <name> <summary fragment> . ?
</blockquote></details>

Yes, I meant dropping the "are".

I was trying to clarify that the format is not `@param <sentence that starts with param name>`, i.e. that the param name is not part of the description.
___
*[src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/EventFilters.kt, line 44 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/519#-N-Z4tO44EQtXmXHSI9g:-N-Z4tO44EQtXmXHSI9h:b3yyd8t) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c626d021d0d1341c86fd8b8e2acafcc18b6d61de/src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/EventFilters.kt#L44)):*
> ```Kotlin
>    * @throws [EventFilterValidationException] if [celExpr] is not valid. with the following codes:
>    * * [EventFilterValidationException.Code.INVALID_CEL_EXPRESSION]
>    * * [EventFilterValidationException.Code.INVALID_VALUE_TYPE]
> ```

Is this just all the codes? If so, there's no need to specify the exhaustive list here. The main reason to list out the codes is so the caller knows which subset they need to handle.

Note that if the codes used by different functions form disjoint sets, that's a strong indicator that the disjoint code sets should be in different exception types (possibly extending from the same base).

Effective Java Chapter 4 Item 23 "Prefer class hierarchies to tagged classes" likely applies here, with the addition that Kotlin has sealed classes to make this even better.



_Code quote:_
```Kotlin
   * * [EventFilterValidationException.Code.INVALID_CEL_EXPRESSION]
   * * [EventFilterValidationException.Code.INVALID_VALUE_TYPE]
   * * [EventFilterValidationException.Code.UNSUPPORTED_OPERATION]
   * * [EventFilterValidationException.Code.EXPRESSION_IS_NOT_CONDITIONAL]
   * * [EventFilterValidationException.Code.INVALID_OPERATION_OUTSIDE_LEAF]
   * * [EventFilterValidationException.Code.FIELD_COMPARISON_OUTSIDE_LEAF]
```
___
*[src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/validation/EventFilterValidator.kt, line 174 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/519#-N-UeoT53SZ1GoM88a-n:-N-Z6gwcA698IAmy8Z3U:bw6m3pt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3a9cf0e3abd42cdd9e30a877a0f520796c34f858/src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/validation/EventFilterValidator.kt#L174)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

Expanded the abbreviation, the documentation is at EventFilters level. I can copy that here too?
</blockquote></details>

No need to copy if it exists there, since this is a private function that I assumed is called from there.
___
*[src/main/proto/wfa/measurement/api/v2alpha/event_templates/testing/test_video_template.proto, line 49 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/519#-N-Z7aUw1F9iDphCqzxU:-N-Z7aUw1F9iDphCqzxV:b-ywsisn) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c626d021d0d1341c86fd8b8e2acafcc18b6d61de/src/main/proto/wfa/measurement/api/v2alpha/event_templates/testing/test_video_template.proto#L49)):*
> ```protobuf
>     };
> 
>     google.protobuf.Duration value = 1;
> ```

Just as a thought, is there any reason why we can't just have the `event_field` annotation on the field itself rather than having to wrap it in a message? I know we originally just said we were going to wrap everything, but I don't remember if the reason we did that is no longer relevant.  @robinsons


<!-- Sent from Reviewable.io -->

2022-04-13 19:44 UTC, duliomatos1 approved these changes
> Reviewed 9 of 21 files at r2, 2 of 6 files at r3, 9 of 9 files at r9, 4 of 4 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/519)* status: all files reviewed, 2 unresolved discussions (waiting on @matthewclegg and @uakyol)



<!-- Sent from Reviewable.io -->

2022-04-14 23:44 UTC, duliomatos1 approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/519)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @matthewclegg)



<!-- Sent from Reviewable.io -->

2022-04-18 16:30 UTC, duliomatos1 approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/519)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @matthewclegg)



<!-- Sent from Reviewable.io -->

2022-04-20 19:15 UTC, uakyol reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/519)* status: 23 of 24 files reviewed, all discussions resolved (waiting on @duliomatos1, @matthewclegg, and @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/EventFilters.kt, line 34 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/519#-N-Ubqn95fr9_KPeNf4v:-N-ZLAH01oLZ_rMkmJKM:b-thazcz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3a9cf0e3abd42cdd9e30a877a0f520796c34f858/src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/EventFilters.kt#L34)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Yes, I meant dropping the "are".

I was trying to clarify that the format is not `@param <sentence that starts with param name>`, i.e. that the param name is not part of the description.
</blockquote></details>

ah thanks
___
*[src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/validation/EventFilterValidator.kt, line 174 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/519#-N-UeoT53SZ1GoM88a-n:-N-ZLDXc9bY7D60QkfAS:b-k73z76) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3a9cf0e3abd42cdd9e30a877a0f520796c34f858/src/main/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/validation/EventFilterValidator.kt#L174)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

No need to copy if it exists there, since this is a private function that I assumed is called from there.
</blockquote></details>

thanks


<!-- Sent from Reviewable.io -->

2022-04-20 19:15 UTC, uakyol reviewed
> Reviewed 1 of 4 files at r13, 1 of 1 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/519)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @matthewclegg and @SanjayVas)



<!-- Sent from Reviewable.io -->

2022-04-20 19:22 UTC, merged