Add postgres schema and test for privacy budget ledger
world-federation-of-advertisers/cross-media-measurement pull request #520
Opened 2022-04-08 12:09 UTC by duliomatos1

* Creates a schema for the Privacy Bucket Ledger backing store using postgresql notation
* Run the schema and a basic write/read as a basic test, under a postgres docker test harness already implemented in the project

2022-04-08 13:38 UTC, duliomatos1 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/520)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @SanjayVas, @stevenwarejones, and @uakyol)

___
*[src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql, line 21 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/520#-N-8LWlM6ecu7kTontmz:-N-8MoggE0fs97E6JdAU:b-si90jx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/99ff3574e8258a9d0404f50a4195e455b0b04e31/src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql#L21)):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

I'm following the initial design, but we can change this type to `date`
</blockquote></details>

@uakyol we can connect to talk about the design

Looking at the currently implemented backing store I think this table should probably reflect exactly what
is implemented in these data classes, right?
```
data class PrivacyBudgetLedgerEntry(
  val rowId: Long,
  val transactionId: Long,
  val privacyBucketGroup: PrivacyBucketGroup,
  val privacyCharge: PrivacyCharge,
  val repetitionCount: Int
)

data class PrivacyCharge(val epsilon: Float, val delta: Float)

data class PrivacyBucketGroup(
  val measurementConsumerId: String,
  val startingDate: LocalDate,
  val endingDate: LocalDate,
  val ageGroup: AgeGroup,
  val gender: Gender,
  val vidSampleStart: Float,
  val vidSampleWidth: Float
)
```


<!-- Sent from Reviewable.io -->

2022-04-08 16:51 UTC, duliomatos1 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/520)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @SanjayVas, @stevenwarejones, and @uakyol)

___
*[src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql, line 21 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/520#-N-8LWlM6ecu7kTontmz:-N-9-IbjAFipSI4NnmpL:b-40y30x) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/99ff3574e8258a9d0404f50a4195e455b0b04e31/src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql#L21)):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

@uakyol we can connect to talk about the design

Looking at the currently implemented backing store I think this table should probably reflect exactly what
is implemented in these data classes, right?
```
data class PrivacyBudgetLedgerEntry(
  val rowId: Long,
  val transactionId: Long,
  val privacyBucketGroup: PrivacyBucketGroup,
  val privacyCharge: PrivacyCharge,
  val repetitionCount: Int
)

data class PrivacyCharge(val epsilon: Float, val delta: Float)

data class PrivacyBucketGroup(
  val measurementConsumerId: String,
  val startingDate: LocalDate,
  val endingDate: LocalDate,
  val ageGroup: AgeGroup,
  val gender: Gender,
  val vidSampleStart: Float,
  val vidSampleWidth: Float
)
```
</blockquote></details>

I wonder if it's more effective to have a separate PrivacyGroupTable, referenced by LedgerEntries, instead of having the `by_bucket` index. Don't know if it's practical without changing the BackingStore interfaces to reference buckets by ID though. Wdyt, @uakyol?


<!-- Sent from Reviewable.io -->

2022-04-08 19:04 UTC, duliomatos1 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/520)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @SanjayVas, @stevenwarejones, and @uakyol)

___
*[src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql, line 21 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/520#-N-8LWlM6ecu7kTontmz:-N-9YwI_-lmYpApU7eXk:b-ywihrs) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/99ff3574e8258a9d0404f50a4195e455b0b04e31/src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql#L21)):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

I wonder if it's more effective to have a separate PrivacyGroupTable, referenced by LedgerEntries, instead of having the `by_bucket` index. Don't know if it's practical without changing the BackingStore interfaces to reference buckets by ID though. Wdyt, @uakyol?
</blockquote></details>

e.g. it would help on finding intersecting ledger entries


<!-- Sent from Reviewable.io -->

2022-04-08 21:46 UTC, SanjayVas reviewed
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/520)* status: all files reviewed, 4 unresolved discussions (waiting on @duliomatos1, @stevenwarejones, and @uakyol)

___
*[src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql, line 17 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/520#-N-9zq7e8mZC0AVENClk:-N-9zq7e8mZC0AVENCll:bn11w74) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/99ff3574e8258a9d0404f50a4195e455b0b04e31/src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql#L17)):*
> ```TSQL
> CREATE TABLE LedgerEntries (
>    -- A unique key associated with this row to allow for subsequent updates and deletions.
>    id serial PRIMARY KEY,
> ```

nit: prefer associating the primary key ID with the table name for easier join clauses. e.g. `LedgerEntryId`



_Code quote:_
```TSQL
id
```
___
*[src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql, line 19 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/520#-N-9zmZ92LFhxvurGtjX:-N-9zmZ92LFhxvurGtjY:bg8cmrx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/99ff3574e8258a9d0404f50a4195e455b0b04e31/src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql#L19)):*
> ```TSQL
>    id serial PRIMARY KEY,
>    -- Which Measurement Consumer this PrivacyBucket belongs to.
>    measurementConsumerId integer NOT NULL,
> ```

nit: column names tend to be UpperCamelCase



_Code quote:_
```TSQL
measurementConsumerId
```
___
*[src/test/kotlin/org/wfanet/measurement/integration/postgres/PrivacyBudgetPostgresSchemaTest.kt, line 34 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/520#-N-A-noj0ZySoO1nR5Iu:-N-A-noj0ZySoO1nR5Iv:b-iy6i5r) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/99ff3574e8258a9d0404f50a4195e455b0b04e31/src/test/kotlin/org/wfanet/measurement/integration/postgres/PrivacyBudgetPostgresSchemaTest.kt#L34)):*
> ```Kotlin
>   @Test
>   fun `privacy budget ledger sql file is valid for postgres`() {
>     val conn = pg.embeddedPostgres.postgresDatabase.connection
> ```

nit: explicit types when not obvious. e.g. are these JDBC types?



_Code quote:_
```Kotlin
    val conn = pg.embeddedPostgres.postgresDatabase.connection
    val statement = conn.createStatement()
```


<!-- Sent from Reviewable.io -->

2022-04-08 23:32 UTC, duliomatos1 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/520)* status: all files reviewed, 4 unresolved discussions (waiting on @duliomatos1, @SanjayVas, @stevenwarejones, and @uakyol)

___
*[src/test/kotlin/org/wfanet/measurement/integration/postgres/PrivacyBudgetPostgresSchemaTest.kt, line 34 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/520#-N-A-noj0ZySoO1nR5Iu:-N-AWOr---0iPURtWo6L:bb7oryy) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/99ff3574e8258a9d0404f50a4195e455b0b04e31/src/test/kotlin/org/wfanet/measurement/integration/postgres/PrivacyBudgetPostgresSchemaTest.kt#L34)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: explicit types when not obvious. e.g. are these JDBC types?
</blockquote></details>

sure


<!-- Sent from Reviewable.io -->

2022-04-08 23:35 UTC, duliomatos1 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/520)* status: all files reviewed, 5 unresolved discussions (waiting on @duliomatos1, @SanjayVas, @stevenwarejones, and @uakyol)

___
*[src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql, line 19 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/520#-N-9zmZ92LFhxvurGtjX:-N-AWu5F5l5jxlj_O_6z:bossve) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/99ff3574e8258a9d0404f50a4195e455b0b04e31/src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql#L19)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: column names tend to be UpperCamelCase
</blockquote></details>

cool, will follow that
___
*[src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql, line 33 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/520#-N-AWo748SyWnX7astVU:-N-AWo748SyWnX7astVV:brewz99) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/99ff3574e8258a9d0404f50a4195e455b0b04e31/src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql#L33)):*
> ```TSQL
>    epsilon real NOT NULL,
>    -- How many times this charge is applied to this Privacy Bucket.
>    repetition_count integer NOT NULL
> ```

ditto, UpperCamelCase


<!-- Sent from Reviewable.io -->

2022-04-08 23:35 UTC, duliomatos1 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/520)* status: all files reviewed, 5 unresolved discussions (waiting on @SanjayVas, @stevenwarejones, and @uakyol)

___
*[src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql, line 17 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/520#-N-9zq7e8mZC0AVENClk:-N-AX4Po2ougRlauTbW0:bb7efny) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/99ff3574e8258a9d0404f50a4195e455b0b04e31/src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql#L17)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: prefer associating the primary key ID with the table name for easier join clauses. e.g. `LedgerEntryId`
</blockquote></details>

cool


<!-- Sent from Reviewable.io -->

2022-04-08 23:38 UTC, duliomatos1 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/520)* status: all files reviewed, 6 unresolved discussions (waiting on @SanjayVas, @stevenwarejones, and @uakyol)

___
*[src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql, line 15 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/520#-N-AXkZi9nfpDhPcjs-3:-N-AXkZi9nfpDhPcjs-4:beldar6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/99ff3574e8258a9d0404f50a4195e455b0b04e31/src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql#L15)):*
> ```TSQL
> -- limitations under the License.
> 
> CREATE TABLE LedgerEntries (
> ```

@sanjayvas we do use plural for table names in the project, right?


<!-- Sent from Reviewable.io -->

2022-04-08 23:41 UTC, duliomatos1 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/520)* status: all files reviewed, 6 unresolved discussions (waiting on @SanjayVas, @stevenwarejones, and @uakyol)

___
*[src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql, line 21 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/520#-N-8LWlM6ecu7kTontmz:-N-AXvJa8v3KFVxkwVml:bmpkxky) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/99ff3574e8258a9d0404f50a4195e455b0b04e31/src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql#L21)):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

e.g. it would help on finding intersecting ledger entries
</blockquote></details>

BTW I probably can propose a better schema as I implement `PostgresLedgerBackingStore` in a next PR, maybe leave the discussion there, and talk on our next connect.


<!-- Sent from Reviewable.io -->

2022-04-08 23:44 UTC, duliomatos1 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/520)* status: all files reviewed, 8 unresolved discussions (waiting on @SanjayVas, @stevenwarejones, and @uakyol)

___
*[src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql, line 36 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/520#-N-AYwUpETerPJqBIv7D:-N-AYwUpETerPJqBIv7E:b-vt3hhc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/99ff3574e8258a9d0404f50a4195e455b0b04e31/src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql#L36)):*
> ```TSQL
> );
> -- Used to query a privacy bucket efficiently.
> CREATE UNIQUE INDEX by_bucket ON LedgerEntries (measurementConsumerId, date, age, gender, vid);
> ```

`by_bucket` -> `LedgerEntriesByBucket`
___
*[src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql, line 38 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/520#-N-AZ7jSE7Orzou3nnkL:-N-AZ7jSE7Orzou3nnkM:b-7ropln) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/99ff3574e8258a9d0404f50a4195e455b0b04e31/src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql#L38)):*
> ```TSQL
> CREATE UNIQUE INDEX by_bucket ON LedgerEntries (measurementConsumerId, date, age, gender, vid);
> -- Used to update the repetition_count for a delta and epsilon pair efficiently.
> CREATE UNIQUE INDEX by_charge ON LedgerEntries (delta, epsilon);
> ```

ditto


<!-- Sent from Reviewable.io -->

2022-04-09 00:08 UTC, SanjayVas reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/520)* status: all files reviewed, 8 unresolved discussions (waiting on @duliomatos1, @SanjayVas, @stevenwarejones, and @uakyol)

___
*[src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql, line 15 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/520#-N-AXkZi9nfpDhPcjs-3:-N-AdUNk9cpIZ_2mvx_k:b-okvi9x) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/99ff3574e8258a9d0404f50a4195e455b0b04e31/src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql#L15)):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

@sanjayvas we do use plural for table names in the project, right?
</blockquote></details>

Yes, that's correct. Plural for the table name, and singular for the prefix of the ID column for that table.


<!-- Sent from Reviewable.io -->

2022-04-09 00:36 UTC, duliomatos1 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/520)* status: all files reviewed, 8 unresolved discussions (waiting on @duliomatos1, @SanjayVas, @stevenwarejones, and @uakyol)

___
*[src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql, line 15 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/520#-N-AXkZi9nfpDhPcjs-3:-N-AjvwiCTcKTeQEqAwc:bkjxpv0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/99ff3574e8258a9d0404f50a4195e455b0b04e31/src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql#L15)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Yes, that's correct. Plural for the table name, and singular for the prefix of the ID column for that table.
</blockquote></details>

alright


<!-- Sent from Reviewable.io -->

2022-04-09 00:47 UTC, duliomatos1 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/520)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @SanjayVas, @stevenwarejones, and @uakyol)

___
*[src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql, line 15 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/520#-N-AXkZi9nfpDhPcjs-3:-N-AlkUvAjq7ld5WC33F:bb7f2mf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/99ff3574e8258a9d0404f50a4195e455b0b04e31/src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql#L15)):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

alright
</blockquote></details>

done
___
*[src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql, line 17 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/520#-N-9zq7e8mZC0AVENClk:-N-AlotN7ncSJkStQvEs:bb7f2mf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/99ff3574e8258a9d0404f50a4195e455b0b04e31/src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql#L17)):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

cool
</blockquote></details>

done
___
*[src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql, line 19 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/520#-N-9zmZ92LFhxvurGtjX:-N-AlpyV8xDNN4rkr4C3:bb7f2mf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/99ff3574e8258a9d0404f50a4195e455b0b04e31/src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql#L19)):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

cool, will follow that
</blockquote></details>

done
___
*[src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql, line 33 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/520#-N-AWo748SyWnX7astVU:-N-AmR_j5HioIp0bIcop:bb7f2mf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/99ff3574e8258a9d0404f50a4195e455b0b04e31/src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql#L33)):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

ditto, UpperCamelCase
</blockquote></details>

done
___
*[src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql, line 36 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/520#-N-AYwUpETerPJqBIv7D:-N-AmSazAR-yQN5J4dv8:bb7f2mf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/99ff3574e8258a9d0404f50a4195e455b0b04e31/src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql#L36)):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

`by_bucket` -> `LedgerEntriesByBucket`
</blockquote></details>

done
___
*[src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql, line 38 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/520#-N-AZ7jSE7Orzou3nnkL:-N-AmTZ89KSFJs7zqYq-:bb7f2mf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/99ff3574e8258a9d0404f50a4195e455b0b04e31/src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql#L38)):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

done
___
*[src/test/kotlin/org/wfanet/measurement/integration/postgres/PrivacyBudgetPostgresSchemaTest.kt, line 34 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/520#-N-A-noj0ZySoO1nR5Iu:-N-AmVZh8QpnSzDPBTaM:bb7f2mf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/99ff3574e8258a9d0404f50a4195e455b0b04e31/src/test/kotlin/org/wfanet/measurement/integration/postgres/PrivacyBudgetPostgresSchemaTest.kt#L34)):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

sure
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2022-04-11 17:21 UTC, SanjayVas approved these changes
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/520)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones and @uakyol)



<!-- Sent from Reviewable.io -->

2022-04-11 19:02 UTC, stevenwarejones approved these changes
> Reviewed 4 of 5 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/520)* status: all files reviewed, 1 unresolved discussion (waiting on @uakyol)



<!-- Sent from Reviewable.io -->

2022-04-11 19:59 UTC, duliomatos1 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/520)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @uakyol)

___
*[src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql, line 21 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/520#-N-8LWlM6ecu7kTontmz:-N-P-cFj5gsTkypsUYUX:b-cku7l8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/99ff3574e8258a9d0404f50a4195e455b0b04e31/src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql#L21)):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

BTW I probably can propose a better schema as I implement `PostgresLedgerBackingStore` in a next PR, maybe leave the discussion there, and talk on our next connect.
</blockquote></details>

done. As we talked, keeping the ledger as a single table.


<!-- Sent from Reviewable.io -->

2022-04-12 20:16 UTC, uakyol requested changes
Looks great Dulio, I think you looked here for reference : https://docs.google.com/document/d/1bSv_RLPudqhkwh5LjUnMinzkcZAOU-HPydh-2ODWbTg/edit  . 
Sorry, somethings there have changed and I needed to have updated them. 

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/520#-:-N-UPGwz4ETt-9RENhtZ:bsqlsad)* status: all files reviewed, 4 unresolved discussions (waiting on @duliomatos1)

___
*[src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql, line 19 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/520#-N-UNFDbEMJmhwc6VqVS:-N-UNFDcAqSvsRSt5CBt:bnvimqs) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5b1dfaccdc20cdf28928b4ead2972f8b941a3c02/src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql#L19)):*
> ```TSQL
>    LedgerEntryId serial PRIMARY KEY,
>    -- Which Measurement Consumer this PrivacyBucket belongs to.
>    MeasurementConsumerId integer NOT NULL,
> ```

MeasurementConsumerId is a string not an integer.
___
*[src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql, line 23 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/520#-N-UMbgn4VOzlZj9sDkY:-N-UMbgo0gXgQDJa_Ijk:bxmga4z) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5b1dfaccdc20cdf28928b4ead2972f8b941a3c02/src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql#L23)):*
> ```TSQL
>    Date varchar(10) NOT NULL,
>    -- Age for this PrivacyBucket.
>    Age integer NOT NULL,
> ```

I am guessing this should be :

AgeGroup varchar(10)

Since we use enums for this: https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBucketGroup.kt#L18
___
*[src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql, line 27 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/520#-N-UN-Gl05wpxF6NsPQw:-N-UN-Gl05wpxF6NsPQx:b-301nsn) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5b1dfaccdc20cdf28928b4ead2972f8b941a3c02/src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql#L27)):*
> ```TSQL
>    Gender varchar(10) NOT NULL,
>    -- Vid of this PrivacyBucket.
>    Vid real NOT NULL,
> ```

Lets put a comment that this denotes the vid range from Vid + 0.01 .
___
*[src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql, line 36 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/520#-N-UO--86Wm-b9QxNOGp:-N-UO--86Wm-b9QxNOGq:b-ix2zff) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5b1dfaccdc20cdf28928b4ead2972f8b941a3c02/src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql#L36)):*
> ```TSQL
> );
> -- Used to query a privacy bucket efficiently.
> CREATE UNIQUE INDEX LedgerEntriesByBucket ON LedgerEntries (MeasurementConsumerId, Date, Age, Gender, Vid);
> ```

Maybe Just combine these 2 indexes?  
Since you are keeping just 1 table, to update the repetition count, you will need all (MeasurementConsumerId, Date, Age, Gender, Vid, Delta, Epsilon)


<!-- Sent from Reviewable.io -->

2022-04-13 16:31 UTC, SanjayVas reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/520)* status: all files reviewed, 4 unresolved discussions (waiting on @duliomatos1 and @uakyol)

___
*[src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql, line 23 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/520#-N-UMbgn4VOzlZj9sDkY:-N-Yktn93sNSBM8YTW-I:b-h82qpv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5b1dfaccdc20cdf28928b4ead2972f8b941a3c02/src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql#L23)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

I am guessing this should be :

AgeGroup varchar(10)

Since we use enums for this: https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBucketGroup.kt#L18
</blockquote></details>

If you're encoding a protobuf enum into a DB table, it should be an int.


<!-- Sent from Reviewable.io -->

2022-04-13 17:39 UTC, duliomatos1 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/520)* status: all files reviewed, 4 unresolved discussions (waiting on @uakyol)

___
*[src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql, line 19 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/520#-N-UNFDbEMJmhwc6VqVS:-N-YpHjkBA0moO9Q5fHZ:bi9zbfg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5b1dfaccdc20cdf28928b4ead2972f8b941a3c02/src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql#L19)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

MeasurementConsumerId is a string not an integer.
</blockquote></details>

yeah I've noticed while working on the BackingStore implementation, the next PR, so I would like to change some fields here. How about:

```
CREATE TYPE Gender AS ENUM ('M', 'F');
CREATE TYPE AgeGroup AS ENUM ('18_34', '35_54', '55+');

-- This sequence will be referenced as `TransactionId` field at `LedgerEntries` table
-- being incremented only at the start of any transaction.
-- This will allow for transaction rollback functionality after a commit.
-- The special value of 0 is reserved for merged transactions.
CREATE SEQUENCE LedgerEntriesTransactionIdSeq AS bigint START WITH 100;

CREATE TABLE LedgerEntries (
    -- A unique key associated with this row to allow for subsequent updates and deletions.
    LedgerEntryId bigserial PRIMARY KEY,
    -- Which Measurement Consumer this PrivacyBucket belongs to.
    MeasurementConsumerId text NOT NULL,
    -- ID for the transaction this entry belongs to.
    TransactionId bigint NOT NULL,
    -- Day for this PrivacyBucket. DD-MM-YYYY.
    Date Date NOT NULL,
    -- Age for this PrivacyBucket.
    AgeGroup AgeGroup NOT NULL,
    -- Gender for this PrivacyBucket.
    Gender Gender NOT NULL,
    -- Vid of this PrivacyBucket.
    Vid real NOT NULL,
    -- Delta for the charge of this ledger entry.
    Delta real NOT NULL,
    -- Epsilon for the charge of this ledger entry.
    Epsilon real NOT NULL,
    -- How many times this charge is applied to this Privacy Bucket.
    RepetitionCount integer NOT NULL
);
-- Used to query a privacy bucket efficiently.
CREATE UNIQUE INDEX LedgerEntriesByBucket ON LedgerEntries (MeasurementConsumerId, Date, AgeGroup, Gender, Vid);
-- Used to update the RepetitionCount for a Delta and Epsilon pair efficiently.
CREATE UNIQUE INDEX LedgerEntriesByCharge ON LedgerEntries (Delta, Epsilon);
-- Used to rollback transactions
CREATE INDEX LedgerEntriesByTransaction ON LedgerEntries (TransactionId);
```

Notice I've changed Gender and AgeGroup to enum to better match the implementation.
Also added TransactionId and a sequence to control it's generation.
___
*[src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql, line 23 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/520#-N-UMbgn4VOzlZj9sDkY:-N-YpfPb4Nu--GoB4MGz:b-ofq02x) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5b1dfaccdc20cdf28928b4ead2972f8b941a3c02/src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql#L23)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

If you're encoding a protobuf enum into a DB table, it should be an int.
</blockquote></details>

There's a way to use the postgres enum, I've proposed above. It isn't stored as a string, so it's efficient
___
*[src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql, line 27 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/520#-N-UN-Gl05wpxF6NsPQw:-N-YqWhn78dY3cuu9ROc:b-4bvcpw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5b1dfaccdc20cdf28928b4ead2972f8b941a3c02/src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql#L27)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

Lets put a comment that this denotes the vid range from Vid + 0.01 .
</blockquote></details>

sure. What's the better way to explain? How about also naming it `VidStart` instead?
___
*[src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql, line 36 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/520#-N-UO--86Wm-b9QxNOGp:-N-Yquq2D0_NC5e4TE8j:b-5sylsx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5b1dfaccdc20cdf28928b4ead2972f8b941a3c02/src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql#L36)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

Maybe Just combine these 2 indexes?  
Since you are keeping just 1 table, to update the repetition count, you will need all (MeasurementConsumerId, Date, Age, Gender, Vid, Delta, Epsilon)
</blockquote></details>

Yeah, looking at `PrivacyBudgetLedger.chargePrivacyBucketGroups()` right now it uses `findIntersectingLedgerEntries()` and does another search to find a matching `privacyCharge`, and I see what you mean: we could do this in one pass by having this new index.

We probably will need to change the interface of `PrivacyBudgetLedger`, maybe creating a `increaseRepetitionCount()` that will update the repetitionCount directly


<!-- Sent from Reviewable.io -->

2022-04-13 17:52 UTC, SanjayVas reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/520)* status: all files reviewed, 4 unresolved discussions (waiting on @uakyol)

___
*[src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql, line 23 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/520#-N-UMbgn4VOzlZj9sDkY:-N-Z0cWX3lgZOLg_jpgp:bvcapto) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5b1dfaccdc20cdf28928b4ead2972f8b941a3c02/src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql#L23)):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

There's a way to use the postgres enum, I've proposed above. It isn't stored as a string, so it's efficient
</blockquote></details>

For all of our other DB layer interactions, we've chosen to just stick the proto enum int value into the DB rather than using the DB's enum type. That way we don't have to keep the protobuf enums and the DB enums in sync.

That said I don't know if that advice applies here, especially since the representation appears to be a Kotlin class rather than a protobuf message. Everywhere else we wrap our persistence access in gRPC services to allow for alternate persistence implementations (that might use totally different schemata).


<!-- Sent from Reviewable.io -->

2022-04-13 19:18 UTC, duliomatos1 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/520)* status: all files reviewed, 4 unresolved discussions (waiting on @uakyol)

___
*[src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql, line 23 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/520#-N-UMbgn4VOzlZj9sDkY:-N-ZJg-H5QZ2wLHxOajt:b-pgpbfd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5b1dfaccdc20cdf28928b4ead2972f8b941a3c02/src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql#L23)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

For all of our other DB layer interactions, we've chosen to just stick the proto enum int value into the DB rather than using the DB's enum type. That way we don't have to keep the protobuf enums and the DB enums in sync.

That said I don't know if that advice applies here, especially since the representation appears to be a Kotlin class rather than a protobuf message. Everywhere else we wrap our persistence access in gRPC services to allow for alternate persistence implementations (that might use totally different schemata).
</blockquote></details>

Yeah it probably doesn't apply here as it is now. Wdyt @uakyol ?


<!-- Sent from Reviewable.io -->

2022-04-13 23:51 UTC, duliomatos1 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/520)* status: 3 of 5 files reviewed, 4 unresolved discussions (waiting on @SanjayVas, @stevenwarejones, and @uakyol)

___
*[src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql, line 23 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/520#-N-UMbgn4VOzlZj9sDkY:-N-_KF2r0b63jsWPbsvW:b6qn7ks) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5b1dfaccdc20cdf28928b4ead2972f8b941a3c02/src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql#L23)):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

Yeah it probably doesn't apply here as it is now. Wdyt @uakyol ?
</blockquote></details>

Done. Changed to postgres enum, matching the `.name` property  value of the kotlin enums, let me know if this works @uakyol
___
*[src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql, line 27 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/520#-N-UN-Gl05wpxF6NsPQw:-N-_JtxD9nKx8rFWwBf5:boy1svi) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5b1dfaccdc20cdf28928b4ead2972f8b941a3c02/src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql#L27)):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

sure. What's the better way to explain? How about also naming it `VidStart` instead?
</blockquote></details>

Done. Lmk if it's clear now
___
*[src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql, line 36 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/520#-N-UO--86Wm-b9QxNOGp:-N-_K6K7A2pXMQvKSUi3:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5b1dfaccdc20cdf28928b4ead2972f8b941a3c02/src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql#L36)):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

Yeah, looking at `PrivacyBudgetLedger.chargePrivacyBucketGroups()` right now it uses `findIntersectingLedgerEntries()` and does another search to find a matching `privacyCharge`, and I see what you mean: we could do this in one pass by having this new index.

We probably will need to change the interface of `PrivacyBudgetLedger`, maybe creating a `increaseRepetitionCount()` that will update the repetitionCount directly
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-04-14 00:46 UTC, duliomatos1 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/520)* status: 3 of 5 files reviewed, 4 unresolved discussions (waiting on @SanjayVas, @stevenwarejones, and @uakyol)

___
*[src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql, line 36 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/520#-N-UO--86Wm-b9QxNOGp:-N-_WE9BEo_oXYfkzAWr:bpvnvor) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5b1dfaccdc20cdf28928b4ead2972f8b941a3c02/src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql#L36)):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

@uakyol I can see the current test for the backing store, which should serve as a basis, would fail because it tries to add the same entry twice https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7142de8fe88378caa92f654dd4c8b4afa7664015/src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/InMemoryBackingStoreTest.kt#L72-L73.

Since entries in the definition here are unique, how to solve that?
Are we changing to have one entry per bucket based on our last dev connect? If so `findIntersectingLedgerEntries()` should at most return one entry


<!-- Sent from Reviewable.io -->

2022-04-14 16:35 UTC, uakyol requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/520)* status: 3 of 5 files reviewed, 3 unresolved discussions (waiting on @duliomatos1, @SanjayVas, @stevenwarejones, and @uakyol)

___
*[src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql, line 23 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/520#-N-UMbgn4VOzlZj9sDkY:-N-cux_J39o8VBtH6wHu:b4n52ib) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5b1dfaccdc20cdf28928b4ead2972f8b941a3c02/src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql#L23)):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

Done. Changed to postgres enum, matching the `.name` property  value of the kotlin enums, let me know if this works @uakyol
</blockquote></details>

sounds great to me
___
*[src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql, line 36 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/520#-N-UO--86Wm-b9QxNOGp:-N-cvBhf12cuVfCl-MXW:bt6sndl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5b1dfaccdc20cdf28928b4ead2972f8b941a3c02/src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql#L36)):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

@uakyol I can see the current test for the backing store, which should serve as a basis, would fail because it tries to add the same entry twice https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7142de8fe88378caa92f654dd4c8b4afa7664015/src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/InMemoryBackingStoreTest.kt#L72-L73.

Since entries in the definition here are unique, how to solve that?
Are we changing to have one entry per bucket based on our last dev connect? If so `findIntersectingLedgerEntries()` should at most return one entry

</blockquote></details>

I see, thank you for catching this
You are right, we should split these. Since LedgerEntriesByTransaction is not a unique index, this should work. What do you think?


<!-- Sent from Reviewable.io -->

2022-04-14 16:36 UTC, uakyol requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/520)* status: 3 of 5 files reviewed, 3 unresolved discussions (waiting on @duliomatos1, @SanjayVas, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql, line 19 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/520#-N-UNFDbEMJmhwc6VqVS:-N-cvXXVBLEWRvOAAD9U:b-ligtpf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5b1dfaccdc20cdf28928b4ead2972f8b941a3c02/src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql#L19)):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

yeah I've noticed while working on the BackingStore implementation, the next PR, so I would like to change some fields here. How about:

```
CREATE TYPE Gender AS ENUM ('M', 'F');
CREATE TYPE AgeGroup AS ENUM ('18_34', '35_54', '55+');

-- This sequence will be referenced as `TransactionId` field at `LedgerEntries` table
-- being incremented only at the start of any transaction.
-- This will allow for transaction rollback functionality after a commit.
-- The special value of 0 is reserved for merged transactions.
CREATE SEQUENCE LedgerEntriesTransactionIdSeq AS bigint START WITH 100;

CREATE TABLE LedgerEntries (
    -- A unique key associated with this row to allow for subsequent updates and deletions.
    LedgerEntryId bigserial PRIMARY KEY,
    -- Which Measurement Consumer this PrivacyBucket belongs to.
    MeasurementConsumerId text NOT NULL,
    -- ID for the transaction this entry belongs to.
    TransactionId bigint NOT NULL,
    -- Day for this PrivacyBucket. DD-MM-YYYY.
    Date Date NOT NULL,
    -- Age for this PrivacyBucket.
    AgeGroup AgeGroup NOT NULL,
    -- Gender for this PrivacyBucket.
    Gender Gender NOT NULL,
    -- Vid of this PrivacyBucket.
    Vid real NOT NULL,
    -- Delta for the charge of this ledger entry.
    Delta real NOT NULL,
    -- Epsilon for the charge of this ledger entry.
    Epsilon real NOT NULL,
    -- How many times this charge is applied to this Privacy Bucket.
    RepetitionCount integer NOT NULL
);
-- Used to query a privacy bucket efficiently.
CREATE UNIQUE INDEX LedgerEntriesByBucket ON LedgerEntries (MeasurementConsumerId, Date, AgeGroup, Gender, Vid);
-- Used to update the RepetitionCount for a Delta and Epsilon pair efficiently.
CREATE UNIQUE INDEX LedgerEntriesByCharge ON LedgerEntries (Delta, Epsilon);
-- Used to rollback transactions
CREATE INDEX LedgerEntriesByTransaction ON LedgerEntries (TransactionId);
```

Notice I've changed Gender and AgeGroup to enum to better match the implementation.
Also added TransactionId and a sequence to control it's generation.
</blockquote></details>

I really like this. The point Sanjay is making is valid, but I think he is ok with going with Enums here since the corresponding ones are kotlin enums. This is definitely more clear to read


<!-- Sent from Reviewable.io -->

2022-04-14 17:11 UTC, duliomatos1 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/520)* status: 3 of 5 files reviewed, 3 unresolved discussions (waiting on @duliomatos1, @SanjayVas, @stevenwarejones, and @uakyol)

___
*[src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql, line 36 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/520#-N-UO--86Wm-b9QxNOGp:-N-d06gFB1u-XcGimcDF:b-vdkygj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5b1dfaccdc20cdf28928b4ead2972f8b941a3c02/src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql#L36)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

I see, thank you for catching this
You are right, we should split these. Since LedgerEntriesByTransaction is not a unique index, this should work. What do you think?

</blockquote></details>

I can remove the `UNIQUE` in this `LedgerEntriesByBucket` or split it back, both should work


<!-- Sent from Reviewable.io -->

2022-04-14 17:13 UTC, uakyol requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/520)* status: 3 of 5 files reviewed, 3 unresolved discussions (waiting on @duliomatos1, @SanjayVas, and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql, line 36 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/520#-N-UO--86Wm-b9QxNOGp:-N-d36Sc4gbdoQU0PEUv:bhy7z7z) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5b1dfaccdc20cdf28928b4ead2972f8b941a3c02/src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql#L36)):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

I can remove the `UNIQUE` in this `LedgerEntriesByBucket` or split it back, both should work
</blockquote></details>

oh yea, just remove the UNIQUE


<!-- Sent from Reviewable.io -->

2022-04-14 18:12 UTC, duliomatos1 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/520)* status: 3 of 5 files reviewed, 3 unresolved discussions (waiting on @duliomatos1, @SanjayVas, @stevenwarejones, and @uakyol)

___
*[src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql, line 23 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/520#-N-UMbgn4VOzlZj9sDkY:-N-dGSaq0acuqwv3b_tH:b-nrx0kq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5b1dfaccdc20cdf28928b4ead2972f8b941a3c02/src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql#L23)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

sounds great to me
</blockquote></details>

Done. Then
___
*[src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql, line 36 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/520#-N-UO--86Wm-b9QxNOGp:-N-dFCp83BNHnMXPUx05:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5b1dfaccdc20cdf28928b4ead2972f8b941a3c02/src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql#L36)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

oh yea, just remove the UNIQUE
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-04-14 18:28 UTC, uakyol approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/520)* status: 3 of 5 files reviewed, all discussions resolved (waiting on @SanjayVas and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2022-04-14 19:51 UTC, stevenwarejones approved these changes
> Reviewed 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/520)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)



<!-- Sent from Reviewable.io -->

2022-04-14 20:02 UTC, uakyol approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/520)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)



<!-- Sent from Reviewable.io -->

2022-04-14 20:15 UTC, merged