Implement EventGroupMetadata parser
world-federation-of-advertisers/cross-media-measurement pull request #531
Opened 2022-04-13 22:06 UTC by chipingyeh

2022-04-15 00:18 UTC, robinsons requested changes
> Reviewed 1 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/531)* status: 1 of 7 files reviewed, 4 unresolved discussions (waiting on @chipingyeh and @stevenwarejones)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/531#-N-eXsNZDK84NfK17uYS:-N-eXsNZDK84NfK17uYT:b-wsmfeu) (no related file):*
IIUC, the approach here is that every time someone calls `convertToDynamicMessage()`, we are incrementally adding to the `registryBuilder`. As I mention below, I'm a bit reluctant to go with an approach that accepts mutable, non-final state, especially because I don't think it's really needed in this case.

As an exercise, I wrote out what I thought would be a common flow for creating and using an `EventGroupMetadataParser`. Let me know what you think of this:

```
// Example potential sequence for parsing a set of event group metadata.

val response: ListEventGroupsResponse = eventGroupsService.listEventGroups(
  listEventGroupsRequest {
    parent = "dataProviders/foo"
  }
)

// Assumes the existence of a decryptMetadata() function.
val plaintextMetadata: List<EventGroup.Metadata> =
  response
    .eventGroupsList
    .map { decryptMetadata(it.encryptedMetadata) }

// Note: May want to add a ListEventGroupMetadataDescriptors RPC to simplify this.
val eventGroupMetadataDescriptors: List<EventGroupMetadataDescriptor> =
  plaintextMetadata
    .distinctBy { it.eventGroupMetadataDescriptor }
    .map { metadata ->
      eventGroupMetadataDescriptorsService.getEventGroupMetadataDescriptor(
        getEventGroupMetadataDescriptorRequest {
          name = metadata.eventGroupMetadataDescriptor
        }
      )
    }
    
val parser = EventGroupMetadataParser(eventGroupMetadataDescriptors)
val parsedMetadata: List<DynamicMessage?> = plaintextMetadata.map { parser.parse(it) }
```

In this example, all of the parser's internal state can be final and immutable. When initializing a new parser, we pass all of the `EventGroupMetadataDescriptor`s that we ever intend to use with this parser instance, so that everything can be set up at instantiation time.

My understanding is that it's OK for the parser to be short-lived. All it needs to do is parse the metadata for a set of event groups from 1 or more EDP, and then the parsed metadata can be handed off to some other place that builds requisition filters.

---
___
*[src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventGroupMetadataParser.kt, line 28 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/531#-N-eWNuq7ENb3PRTERsV:-N-eWNuq7ENb3PRTERsW:b-5f5g8k) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/15881f0544d0a60b39b59fdcdccf3516798cf565/src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventGroupMetadataParser.kt#L28)):*
> ```Kotlin
>   private lateinit var fileDescriptorProtoMap: Map<String, FileDescriptorProto>
>   private var fileDescriptorMap: MutableMap<String, FileDescriptor> = mutableMapOf()
>   private var registryBuilder = TypeRegistry.newBuilder()
> ```

It's generally a good idea to steer away from mutable and non-final state, as it can render your object non-thread safe unless you're being very careful. Specifically, this applies to usage of `MutableMap` and `var` instead of `val`.

I understand that this is a result of the approach you're taking, so see above discussion about overall approach.



_Code quote:_
```Kotlin
  private lateinit var typeRegistry: TypeRegistry
  private lateinit var fileDescriptorProtoMap: Map<String, FileDescriptorProto>
  private var fileDescriptorMap: MutableMap<String, FileDescriptor> = mutableMapOf()
  private var registryBuilder = TypeRegistry.newBuilder()
```
___
*[src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventGroupMetadataParser.kt, line 70 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/531#-N-eWo6UBVBtaX56Iif7:-N-eWo6V9ni9_nUWGXCf:bmlt5l0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/15881f0544d0a60b39b59fdcdccf3516798cf565/src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventGroupMetadataParser.kt#L70)):*
> ```Kotlin
>   fun convertToDynamicMessage(
>     message: com.google.protobuf.Any,
>     fileDescriptorSet: FileDescriptorSet
> ```

IMO, since this parser is intended for parsing `EventGroup.Metadatata` from an `EventGroupMetadataDescriptor`, then our inputs should match those types. As an example of a potential use case, in the long-term we'll likely add support for things like metadata versioning, and so these more specific types will be useful to pass along versioning information.



_Code quote:_
```Kotlin
    message: com.google.protobuf.Any,
    fileDescriptorSet: FileDescriptorSet
```
___
*[src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventGroupMetadataParser.kt, line 76 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/531#-N-eUc_52xxEIguOqq4q:-N-eUc_52xxEIguOqq4r:b66ccc7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/15881f0544d0a60b39b59fdcdccf3516798cf565/src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventGroupMetadataParser.kt#L76)):*
> ```Kotlin
>     val messageName = message.typeUrl.split("/")[1]
> 
>     return DynamicMessage.parseFrom(typeRegistry.find(messageName), message.value)
> ```

Since we have a `typeUrl`, we can just use `TypeRegistry.getDescriptorForTypeUrl()` [1].

[1] https://developers.google.com/protocol-buffers/docs/reference/java/com/google/protobuf/TypeRegistry.html#getDescriptorForTypeUrl-java.lang.String-


<!-- Sent from Reviewable.io -->

2022-04-15 21:42 UTC, chipingyeh reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/531)* status: 0 of 7 files reviewed, 4 unresolved discussions (waiting on @robinsons and @stevenwarejones)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/531#-N-eXsNZDK84NfK17uYS:-N-j6DBx44BxUjlu1ruT:b-pfqkc) (no related file):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

IIUC, the approach here is that every time someone calls `convertToDynamicMessage()`, we are incrementally adding to the `registryBuilder`. As I mention below, I'm a bit reluctant to go with an approach that accepts mutable, non-final state, especially because I don't think it's really needed in this case.

As an exercise, I wrote out what I thought would be a common flow for creating and using an `EventGroupMetadataParser`. Let me know what you think of this:

```
// Example potential sequence for parsing a set of event group metadata.

val response: ListEventGroupsResponse = eventGroupsService.listEventGroups(
  listEventGroupsRequest {
    parent = "dataProviders/foo"
  }
)

// Assumes the existence of a decryptMetadata() function.
val plaintextMetadata: List<EventGroup.Metadata> =
  response
    .eventGroupsList
    .map { decryptMetadata(it.encryptedMetadata) }

// Note: May want to add a ListEventGroupMetadataDescriptors RPC to simplify this.
val eventGroupMetadataDescriptors: List<EventGroupMetadataDescriptor> =
  plaintextMetadata
    .distinctBy { it.eventGroupMetadataDescriptor }
    .map { metadata ->
      eventGroupMetadataDescriptorsService.getEventGroupMetadataDescriptor(
        getEventGroupMetadataDescriptorRequest {
          name = metadata.eventGroupMetadataDescriptor
        }
      )
    }
    
val parser = EventGroupMetadataParser(eventGroupMetadataDescriptors)
val parsedMetadata: List<DynamicMessage?> = plaintextMetadata.map { parser.parse(it) }
```

In this example, all of the parser's internal state can be final and immutable. When initializing a new parser, we pass all of the `EventGroupMetadataDescriptor`s that we ever intend to use with this parser instance, so that everything can be set up at instantiation time.

My understanding is that it's OK for the parser to be short-lived. All it needs to do is parse the metadata for a set of event groups from 1 or more EDP, and then the parsed metadata can be handed off to some other place that builds requisition filters.
</blockquote></details>

Thanks for the in-depth explanation, it's very helpful. This was a mistake on my part, as I intended for initializeTypeRegistry to only be called once and consequent `convertToDynamicMessage()` calls to be separate. I've updated the functions so that the typeRegistry isn't re-populated on each parse call and they take in the appropriate params.

---
___
*[src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventGroupMetadataParser.kt, line 28 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/531#-N-eWNuq7ENb3PRTERsV:-N-j79L2-t2sJjuuzUag:byqb911) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/15881f0544d0a60b39b59fdcdccf3516798cf565/src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventGroupMetadataParser.kt#L28)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

It's generally a good idea to steer away from mutable and non-final state, as it can render your object non-thread safe unless you're being very careful. Specifically, this applies to usage of `MutableMap` and `var` instead of `val`.

I understand that this is a result of the approach you're taking, so see above discussion about overall approach.
</blockquote></details>

I wanted to keep a mutableMap open to detect duplicate processing -- I tentatively moved the variables to inside the function to be separate for each `eventGroupMetadataDescriptor` although this would result in a lot of duplication from being parameters in a recursive function. What do you think?
___
*[src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventGroupMetadataParser.kt, line 70 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/531#-N-eWo6UBVBtaX56Iif7:-N-j5Ic5AoucxvXJ9G4a:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/15881f0544d0a60b39b59fdcdccf3516798cf565/src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventGroupMetadataParser.kt#L70)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

IMO, since this parser is intended for parsing `EventGroup.Metadatata` from an `EventGroupMetadataDescriptor`, then our inputs should match those types. As an example of a potential use case, in the long-term we'll likely add support for things like metadata versioning, and so these more specific types will be useful to pass along versioning information.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventGroupMetadataParser.kt, line 76 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/531#-N-eUc_52xxEIguOqq4q:-N-j5G6S3wkskLaOr3UJ:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/15881f0544d0a60b39b59fdcdccf3516798cf565/src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventGroupMetadataParser.kt#L76)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

Since we have a `typeUrl`, we can just use `TypeRegistry.getDescriptorForTypeUrl()` [1].

[1] https://developers.google.com/protocol-buffers/docs/reference/java/com/google/protobuf/TypeRegistry.html#getDescriptorForTypeUrl-java.lang.String-
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-04-19 16:25 UTC, robinsons requested changes
> Reviewed 1 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/531)* status: 1 of 7 files reviewed, 9 unresolved discussions (waiting on @chipingyeh and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventGroupMetadataParser.kt, line 28 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/531#-N-eWNuq7ENb3PRTERsV:-N01_2K94lqy2hI6UCuL:bbe4mtu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/15881f0544d0a60b39b59fdcdccf3516798cf565/src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventGroupMetadataParser.kt#L28)):*
<details><summary><i>Previously, chipingyeh wrote…</i></summary><blockquote>

I wanted to keep a mutableMap open to detect duplicate processing -- I tentatively moved the variables to inside the function to be separate for each `eventGroupMetadataDescriptor` although this would result in a lot of duplication from being parameters in a recursive function. What do you think?
</blockquote></details>

Looks pretty good. I'd still prefer for the `TypeRegistry` to not be a `var`. What you could do is make a companion object with a `create(eventGroupMetadataDescriptors: List<EventGroupMetadataDescriptor>)` method, and basically just transplant the logic from `init` into there. Then the `TypeRegistry` can be passed into the parser already fully built.
___
*[src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventGroupMetadataParser.kt, line 22 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/531#-N01RDzP4mCZtTCVquxV:-N01RDzP4mCZtTCVquxW:b-5hq3f3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/572ccbd802923c579f925a0817d545ba35706f54/src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventGroupMetadataParser.kt#L22)):*
> ```Kotlin
> import com.google.protobuf.TypeRegistry
> import org.wfanet.measurement.api.v2alpha.EventGroup.Metadata
> import org.wfanet.measurement.internal.kingdom.EventGroupMetadataDescriptor
> ```

Should be using the v2alpha version of this. Keep in mind that the Kingdom is almost certainly not going to parse event group metadata (it doesn't have the decryption key), so this parser is going to be used by the MC.



_Code quote:_
```Kotlin
import org.wfanet.measurement.internal.kingdom.EventGroupMetadataDescriptor
```
___
*[src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventGroupMetadataParser.kt, line 32 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/531#-N-jJjjWEdSlryu5bLH5:-N-jJjjWEdSlryu5bLH6:bwvb0hh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/572ccbd802923c579f925a0817d545ba35706f54/src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventGroupMetadataParser.kt#L32)):*
> ```Kotlin
>       val fileList: List<FileDescriptorProto> =
>         eventGroupMetadataDescriptor.details.descriptorSet.fileList
>       val fileDescriptorProtoMap = fileList.map { it.name to it }.toMap()
> ```

Can do `fileList.associateBy { it.name }`.
___
*[src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventGroupMetadataParser.kt, line 35 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/531#-N01a1au4TVjpJcwAOVq:-N01a1au4TVjpJcwAOVr:b-het8c8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/572ccbd802923c579f925a0817d545ba35706f54/src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventGroupMetadataParser.kt#L35)):*
> ```Kotlin
>       val fileDescriptorMap: MutableMap<String, FileDescriptor> = mutableMapOf()
>       for (proto in fileList) {
>         buildFileDescriptors(proto, fileDescriptorMap, fileDescriptorProtoMap, registryBuilder)
> ```

Hm, it feels like `buildFileDescriptors()` has too much responsibility. Basically it's both building the descriptors _and_ populating the registry. It effectively has two return values: the built descriptor (used by recursive calls) and the registry (which is an "output parameter"). Could this be restructured to decouple those two things?
___
*[src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventGroupMetadataParser.kt, line 42 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/531#-N-jLtEbBYt-HtJD4DSc:-N-jLtEbBYt-HtJD4DSd:bqte51k) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/572ccbd802923c579f925a0817d545ba35706f54/src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventGroupMetadataParser.kt#L42)):*
> ```Kotlin
>   }
> 
>   private fun buildFileDescriptors(
> ```

Throughout this function, prefer to use Kotlin-style getters, e.g. `proto.name` instead of `proto.getName()` and `proto.dependencyList` instead of `proto.getDependencyList()`.
___
*[src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventGroupMetadataParser.kt, line 45 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/531#-N01R0VH2BYq1049F0-H:-N01R0VH2BYq1049F0-I:b-t525fx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/572ccbd802923c579f925a0817d545ba35706f54/src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventGroupMetadataParser.kt#L45)):*
> ```Kotlin
>     proto: FileDescriptorProto,
>     fileDescriptorMap: MutableMap<String, FileDescriptor>,
>     fileDescriptorProtoMap: Map<String, FileDescriptorProto>,
> ```

Can these be called something like `builtFileDescriptors` and `unbuiltFileDescriptors`? I think that it would make the code a bit clearer to read, since it makes their purpose more obvious.



_Code quote:_
```Kotlin
    fileDescriptorMap: MutableMap<String, FileDescriptor>,
    fileDescriptorProtoMap: Map<String, FileDescriptorProto>,
```
___
*[src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventGroupMetadataParser.kt, line 48 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/531#-N-z9A1Q5XVhwfPQ8sYr:-N-z9A1REtRy-3iGWXi3:balpkp3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/572ccbd802923c579f925a0817d545ba35706f54/src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventGroupMetadataParser.kt#L48)):*
> ```Kotlin
>     registryBuilder: TypeRegistry.Builder
>   ): FileDescriptor {
>     if (fileDescriptorMap[proto.getName()] != null) return fileDescriptorMap[proto.getName()]!!
> ```

Recommend using `in` for presence checks (e.g. `proto.name in fileDescriptorMap`) and `getValue()` to get a non-nullable type to avoid using `!!`.
___
*[src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventGroupMetadataParser.kt, line 51 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/531#-N-jMMJm1IUJ97U9Pm4h:-N-jMMJm1IUJ97U9Pm4i:b-attonl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/572ccbd802923c579f925a0817d545ba35706f54/src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventGroupMetadataParser.kt#L51)):*
> ```Kotlin
> 
>     var dependenciesList: MutableList<FileDescriptor> = mutableListOf()
>     for (dependencyByteName in proto.getDependencyList().asByteStringList()) {
> ```

Why are we iterating over the names as byte strings? Shouldn't this work just as well:

```
for (dependencyName in proto.dependencyList) {
 ...
}
```
___
*[src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventGroupMetadataParser.kt, line 75 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/531#-N01Zg4y9hOk9aCWOQQs:-N01Zg4y9hOk9aCWOQQt:bcn8omv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/572ccbd802923c579f925a0817d545ba35706f54/src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventGroupMetadataParser.kt#L75)):*
> ```Kotlin
>   }
> 
>   /** Returns t [...]

2022-04-19 22:11 UTC, chipingyeh reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/531)* status: 0 of 7 files reviewed, 9 unresolved discussions (waiting on @robinsons and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventGroupMetadataParser.kt, line 28 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/531#-N-eWNuq7ENb3PRTERsV:-N02mDjI9Z5RPZOy8OQ0:b-dims0a) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/15881f0544d0a60b39b59fdcdccf3516798cf565/src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventGroupMetadataParser.kt#L28)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

Looks pretty good. I'd still prefer for the `TypeRegistry` to not be a `var`. What you could do is make a companion object with a `create(eventGroupMetadataDescriptors: List<EventGroupMetadataDescriptor>)` method, and basically just transplant the logic from `init` into there. Then the `TypeRegistry` can be passed into the parser already fully built.
</blockquote></details>

It turns out you can initialize a `val` in the constructor, so simply changing `var` to `val` works too. What do you think?
___
*[src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventGroupMetadataParser.kt, line 22 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/531#-N01RDzP4mCZtTCVquxV:-N02oC6Y4Rnp7N4T_MoE:b-jtre3z) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/572ccbd802923c579f925a0817d545ba35706f54/src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventGroupMetadataParser.kt#L22)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

Should be using the v2alpha version of this. Keep in mind that the Kingdom is almost certainly not going to parse event group metadata (it doesn't have the decryption key), so this parser is going to be used by the MC.
</blockquote></details>

Ah, yes. Turns out I don't need it here -- updated the test.
___
*[src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventGroupMetadataParser.kt, line 32 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/531#-N-jJjjWEdSlryu5bLH5:-N02kKrX0X-ZqSZT6b4W:b-wdj8z5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/572ccbd802923c579f925a0817d545ba35706f54/src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventGroupMetadataParser.kt#L32)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

Can do `fileList.associateBy { it.name }`.
</blockquote></details>

Nice, thanks.
___
*[src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventGroupMetadataParser.kt, line 35 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/531#-N01a1au4TVjpJcwAOVq:-N02pgZa-rdCBuTHtfj2:bg0mifp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/572ccbd802923c579f925a0817d545ba35706f54/src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventGroupMetadataParser.kt#L35)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

Hm, it feels like `buildFileDescriptors()` has too much responsibility. Basically it's both building the descriptors _and_ populating the registry. It effectively has two return values: the built descriptor (used by recursive calls) and the registry (which is an "output parameter"). Could this be restructured to decouple those two things?
</blockquote></details>

Hmm, I could only return the final `FileDescriptor` and then have another function to populate the registry by traversing through the (now `FileDescriptor`-built) tree again. It'd require an extra traversal but decouple the actions -- what do you think?
___
*[src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventGroupMetadataParser.kt, line 42 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/531#-N-jLtEbBYt-HtJD4DSc:-N02jwaYC_0aHI65qqWI:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/572ccbd802923c579f925a0817d545ba35706f54/src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventGroupMetadataParser.kt#L42)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

Throughout this function, prefer to use Kotlin-style getters, e.g. `proto.name` instead of `proto.getName()` and `proto.dependencyList` instead of `proto.getDependencyList()`.
</blockquote></details>

Done.
___
*[src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventGroupMetadataParser.kt, line 45 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/531#-N01R0VH2BYq1049F0-H:-N02rYEl3NbY697mv-0a:b48o60o) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/572ccbd802923c579f925a0817d545ba35706f54/src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventGroupMetadataParser.kt#L45)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

Can these be called something like `builtFileDescriptors` and `unbuiltFileDescriptors`? I think that it would make the code a bit clearer to read, since it makes their purpose more obvious.
</blockquote></details>

The `fileDescriptorProtoMap` is just the `FileDescriptorProto`s taken from the initial MetadataDescriptor list and doesn't change; I've gone ahead and renamed `fileDescriptorMap` to `builtFileDescriptorMap` though.
___
*[src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventGroupMetadataParser.kt, line 48 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/531#-N-z9A1Q5XVhwfPQ8sYr:-N02jZIB6CKiuuCHb_IV:bu2mcne) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/572ccbd802923c579f925a0817d545ba35706f54/src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventGroupMetadataParser.kt#L48)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

Recommend using `in` for presence checks (e.g. `proto.name in fileDescriptorMap`) and `getValue()` to get a non-nullable type to avoid using `!!`.
</blockquote></details>

Thanks for the tip! Done.
___
*[src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventGroupMetadataParser.kt, line 51 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/531#-N-jMMJm1IUJ97U9Pm4h:-N02j4CPA6En0nYuU-xV:b92p7cn) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/572ccbd802923c579f925a0817d545ba35706f54/src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventGroupMetadataParser.kt#L51)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

Why are we iterating over the names as byte strings? Shouldn't this work just as well:

```
for (dependencyName in proto.dependencyList) {
 ...
}
```
</blockquote></details>

Yes, good point. Done.
___
*[src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventGroupMetadataParser.kt, line 75 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/531#-N01Zg4y9hOk9aCWOQQs:-N02idQhDODlvZIM6UEd:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/572ccbd802923c579f925a0817d545ba35706f54/src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventGroupMetadataParser.kt#L75)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

Can you use Kotlin's doc linking by wrapping types in `[` and `]`? Example

```
/** Returns the [DynamicMessage] from an [EventGroup.Metadata] message. */
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-04-22 00:13 UTC, robinsons requested changes
> Reviewed 3 of 7 files at r1, 3 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/531)* status: 6 of 7 files reviewed, 7 unresolved discussions (waiting on @chipingyeh and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventGroupMetadataParser.kt, line 28 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/531#-N-eWNuq7ENb3PRTERsV:-N0DQ9Tr9A4Za8VmVLfN:bb73djm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/15881f0544d0a60b39b59fdcdccf3516798cf565/src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventGroupMetadataParser.kt#L28)):*
<details><summary><i>Previously, chipingyeh wrote…</i></summary><blockquote>

It turns out you can initialize a `val` in the constructor, so simply changing `var` to `val` works too. What do you think?
</blockquote></details>

SGTM
___
*[src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventGroupMetadataParser.kt, line 35 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/531#-N01a1au4TVjpJcwAOVq:-N0DQVXJ5leAEVgVArS0:bk388y5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/572ccbd802923c579f925a0817d545ba35706f54/src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventGroupMetadataParser.kt#L35)):*
<details><summary><i>Previously, chipingyeh wrote…</i></summary><blockquote>

Hmm, I could only return the final `FileDescriptor` and then have another function to populate the registry by traversing through the (now `FileDescriptor`-built) tree again. It'd require an extra traversal but decouple the actions -- what do you think?
</blockquote></details>

Basically yes, but I don't think that two traversal are required (not in the sense of a tree traversal). I'm imagining a short `init`, something like this

```
val registryBuilder = TypeRegistry.newBuilder()
eventGroupMetadataDescriptors
  .flatMap { buildFileDescriptors(it) }
  .flatMap { it.messageTypes }
  .forEach { registryBuilder.add(it) }
typeRegistry = registryBuilder.build()
```

Here, `buildFileDescriptors()` is an overload of the existing method that basically does what your `init` is currently doing, except it returns a list of built `FileDescriptor`s for a single `EventGroupMetadataDescriptor`. Internally it calls your existing `buildFileDescriptors()` that does the recursive traversal.

That should just be one traversal (per `EventGroupMetadataDescriptor`), then a sequential iteration through all of built `FileDescriptor`s .
___
*[src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventGroupMetadataParser.kt, line 50 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/531#-N0DUs3l1UEYyR05HhOJ:-N0DUs3l1UEYyR05HhOK:bigttvd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/726602e28b6d32b5d5a1cb84f2d82aed76b76b0d/src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventGroupMetadataParser.kt#L50)):*
> ```Kotlin
>     var dependenciesList: MutableList<FileDescriptor> = mutableListOf()
>     for (dependencyName in proto.dependencyList) {
>       if (builtFileDescriptorMap[dependencyName] != null) {
> ```

nit: similar to the above suggestion, you could use `dependencyName in builtFileDescriptorMap`.



_Code quote:_
```Kotlin
builtFileDescriptorMap[dependencyName] != null
```
___
*[src/main/proto/wfa/measurement/api/v2alpha/event_group_metadata/testing/test_metadata_message_2.proto, line 24 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/531#-N0D_U-A0_ccBjpTZlYs:-N0D_U-A0_ccBjpTZlYt:b6qdbcg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/726602e28b6d32b5d5a1cb84f2d82aed76b76b0d/src/main/proto/wfa/measurement/api/v2alpha/event_group_metadata/testing/test_metadata_message_2.proto#L24)):*
> ```protobuf
> option java_multiple_files = true;
> 
> message TestMetadataMessage2 {
> ```

No action required: Just passing along some advice about test data that I've found useful over the years. When you name things like `TestThing1` and `TestThing2`, it makes it harder to differentiate between them, as a coder, reviewer, and maintainer. It's easy to miss bugs because things look so similar.

It can help to give things distinguishable names. Say you're coming up with names for user events, then assign the events names of users, e.g. `aliceEvent` and `bobEvent` instead of `event1` and `event2`. Likewise with the test message types here, they could have names of fake EDPs, e.g. `AcmeMetadata` or `WidgetCorpMetadata`.
___
*[src/test/kotlin/org/wfanet/measurement/api/v2alpha/EventGroupMetadataParserTest.kt, line 32 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/531#-N0DVr8m3da99bsxPwz9:-N0DVr8m3da99bsxPwzA:birq1bg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/726602e28b6d32b5d5a1cb84f2d82aed76b76b0d/src/test/kotlin/org/wfanet/measurement/api/v2alpha/EventGroupMetadataParserTest.kt#L32)):*
> ```Kotlin
> import org.wfanet.measurement.api.v2alpha.event_group_metadata.testing.testMetadataMessage2
> 
> private const val API_VERSION = "v2alpha"
> ```

Looks like this is unused.
___
*[src/test/kotlin/org/wfanet/measurement/api/v2alpha/EventGroupMetadataParserTest.kt, line 33 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/531#-N0DVm9c9wnGU1V4TuZQ:-N0DVm9c9wnGU1V4TuZR:bjk2xw6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/726602e28b6d32b5d5a1cb84f2d82aed76b76b0d/src/test/kotlin/org/wfanet/measurement/api/v2alpha/EventGroupMetadataParserTest.kt#L33)):*
> ```Kotlin
> 
> private const val API_VERSION = "v2alpha"
> val TEST_MESSAGE = testMetadataMessage2 {
> ```

All of these top-level values can be `private`.
___
*[src/test/kotlin/org/wfanet/measurement/api/v2alpha/EventGroupMetadataParserTest.kt, line 54 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/531#-N0DXYhECToSTytn-LM-:-N0DXYhECToSTytn-LM0:b-d3unjg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/726602e28b6d32b5d5a1cb84f2d82aed76b76b0d/src/test/kotlin/org/wfanet/measurement/api/v2alpha/EventGroupMetadataParserTest.kt#L54)):*
> ```Kotlin
> 
> @RunWith(JUnit4::class)
> class EventGroupMetadataParserTest {
> ```

Could you add a test that makes sure parser returns `null` when given something it can't parse? Just to make sure it doesn't throw.

Note that if you're adding another test, a lot of your variables in your current test could be pulled out as top-level values to be re-used in both tests.
___
*[src/test/kotlin/org/wfanet/measurement/api/v2alpha/EventGroupMetadataParserTest.kt, line 63 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/531#-N0DWqOKDjBVopUa2fse:-N0DWqOKDjBVopUa2fsf:b4xsose) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/726602e28b6d32b5d5a1cb84f2d82aed76b76b0d/src/test/kotlin/org/wfanet/measurement/api/v2alpha/EventGroupMetadataParserTest.kt#L63)):*
> ```Kotlin
>     val eventGroupMetadataDescriptor2 = eventGroupMetadataDescriptor {
>       name = NAME
>       descriptorSet = TEST_MESSAGE.getDescriptorForType().getFileDescriptorSet()
> ```

Should this be `TEST_MESSAGE_2.getDescriptorForType().getFileDescriptorSet()`?

But actually, both messages are the same type, so I'm not sure why we're initializing the parser with the descriptor for both of them (since it's the same).



_Code quote:_
```Kotlin
      descriptorSet = TEST_MESSAGE.getDescriptorForType().getFileDescriptorSet()
```
___
*[src/test/kotlin/org/wfanet/measurement/api/v2alpha/EventGroupMetadataParserTest.kt, line 73 at r3](https://reviewable.io [...]

2022-04-22 18:56 UTC, chipingyeh reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/531)* status: 4 of 7 files reviewed, 6 unresolved discussions (waiting on @robinsons and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventGroupMetadataParser.kt, line 35 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/531#-N01a1au4TVjpJcwAOVq:-N0GlPfF18fF6zWzABgB:benuftk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/572ccbd802923c579f925a0817d545ba35706f54/src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventGroupMetadataParser.kt#L35)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

Basically yes, but I don't think that two traversal are required (not in the sense of a tree traversal). I'm imagining a short `init`, something like this

```
val registryBuilder = TypeRegistry.newBuilder()
eventGroupMetadataDescriptors
  .flatMap { buildFileDescriptors(it) }
  .flatMap { it.messageTypes }
  .forEach { registryBuilder.add(it) }
typeRegistry = registryBuilder.build()
```

Here, `buildFileDescriptors()` is an overload of the existing method that basically does what your `init` is currently doing, except it returns a list of built `FileDescriptor`s for a single `EventGroupMetadataDescriptor`. Internally it calls your existing `buildFileDescriptors()` that does the recursive traversal.

That should just be one traversal (per `EventGroupMetadataDescriptor`), then a sequential iteration through all of built `FileDescriptor`s .
</blockquote></details>

Thanks for the tip on `flatMap`, I like this approach -- updated.
___
*[src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventGroupMetadataParser.kt, line 50 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/531#-N0DUs3l1UEYyR05HhOJ:-N0HMVFX6EPcdm6Xhb31:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/726602e28b6d32b5d5a1cb84f2d82aed76b76b0d/src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventGroupMetadataParser.kt#L50)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

nit: similar to the above suggestion, you could use `dependencyName in builtFileDescriptorMap`.
</blockquote></details>

Done.
___
*[src/main/proto/wfa/measurement/api/v2alpha/event_group_metadata/testing/test_metadata_message_2.proto, line 24 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/531#-N0D_U-A0_ccBjpTZlYs:-N0HYoUSCFF73Grl-0gu:b-ecpsg0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/726602e28b6d32b5d5a1cb84f2d82aed76b76b0d/src/main/proto/wfa/measurement/api/v2alpha/event_group_metadata/testing/test_metadata_message_2.proto#L24)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

No action required: Just passing along some advice about test data that I've found useful over the years. When you name things like `TestThing1` and `TestThing2`, it makes it harder to differentiate between them, as a coder, reviewer, and maintainer. It's easy to miss bugs because things look so similar.

It can help to give things distinguishable names. Say you're coming up with names for user events, then assign the events names of users, e.g. `aliceEvent` and `bobEvent` instead of `event1` and `event2`. Likewise with the test message types here, they could have names of fake EDPs, e.g. `AcmeMetadata` or `WidgetCorpMetadata`.
</blockquote></details>

That's fair. I might find it confusing to use custom names if I didn't explicitly know it was for testing (i.e. miss the "testing" directory), so I just opted to slightly modify `TestMetadataMessage2` to be `TestParentMetadataMessage` instead since it includes a reference to the other message.
___
*[src/test/kotlin/org/wfanet/measurement/api/v2alpha/EventGroupMetadataParserTest.kt, line 32 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/531#-N0DVr8m3da99bsxPwz9:-N0Gidy50t3sRvswkWTe:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/726602e28b6d32b5d5a1cb84f2d82aed76b76b0d/src/test/kotlin/org/wfanet/measurement/api/v2alpha/EventGroupMetadataParserTest.kt#L32)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

Looks like this is unused.
</blockquote></details>

Done.
___
*[src/test/kotlin/org/wfanet/measurement/api/v2alpha/EventGroupMetadataParserTest.kt, line 33 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/531#-N0DVm9c9wnGU1V4TuZQ:-N0Gii-e4en2FIApgoNW:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/726602e28b6d32b5d5a1cb84f2d82aed76b76b0d/src/test/kotlin/org/wfanet/measurement/api/v2alpha/EventGroupMetadataParserTest.kt#L33)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

All of these top-level values can be `private`.
</blockquote></details>

Done.
___
*[src/test/kotlin/org/wfanet/measurement/api/v2alpha/EventGroupMetadataParserTest.kt, line 54 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/531#-N0DXYhECToSTytn-LM-:-N0HXxpr9CNA9b54FKZ8:b-jcj0ur) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/726602e28b6d32b5d5a1cb84f2d82aed76b76b0d/src/test/kotlin/org/wfanet/measurement/api/v2alpha/EventGroupMetadataParserTest.kt#L54)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

Could you add a test that makes sure parser returns `null` when given something it can't parse? Just to make sure it doesn't throw.

Note that if you're adding another test, a lot of your variables in your current test could be pulled out as top-level values to be re-used in both tests.
</blockquote></details>

Done. It doesn't seem like class functions (`getFileDescriptorSet()`) can be called in top-level variables, so I just redefined `eventGroupMetadataDescriptor` in the new test.
___
*[src/test/kotlin/org/wfanet/measurement/api/v2alpha/EventGroupMetadataParserTest.kt, line 63 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/531#-N0DWqOKDjBVopUa2fse:-N0HOloq2wwhxeM3zXjA:boh241h) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/726602e28b6d32b5d5a1cb84f2d82aed76b76b0d/src/test/kotlin/org/wfanet/measurement/api/v2alpha/EventGroupMetadataParserTest.kt#L63)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

Should this be `TEST_MESSAGE_2.getDescriptorForType().getFileDescriptorSet()`?

But actually, both messages are the same type, so I'm not sure why we're initializing the parser with the descriptor for both of them (since it's the same).
</blockquote></details>

Good catch - TEST_MESSAGE should've been the other message type.
___
*[src/test/kotlin/org/wfanet/measurement/api/v2alpha/EventGroupMetadataParserTest.kt, line 73 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/531#-N0DYDzP5NLGmwOAb6lj:-N0GjJUZ2jOpoUipRwNn:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/726602e28b6d32b5d5a1cb84f2d82aed76b76b0d/src/test/kotlin/org/wfanet/measurement/api/v2alpha/EventGroupMetadataParserTest.kt#L73)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

Looks like this should match the `name` field on `eventGroupMetadataDescriptor2`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-04-22 20:27 UTC, robinsons requested changes
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/531)* status: all files reviewed, 1 unresolved discussion (waiting on @chipingyeh and @stevenwarejones)

___
*[src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventGroupMetadataParser.kt, line 41 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/531#-N0Hp6qt5XXHS2r4tm3w:-N0Hp6qt5XXHS2r4tm3x:blwqg3q) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3c14613f5e526f4dd54abacb7d17f6cd5c370f7f/src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventGroupMetadataParser.kt#L41)):*
> ```Kotlin
>     val fileDescriptorProtoMap = fileList.associateBy { it.name }
>     val fileDescriptorList: MutableList<FileDescriptor> = mutableListOf()
>     for (proto in fileList) {
> ```

This comment doesn't affect the correctness of the solution, but it is something that we could fix up in a future PR.

The way this code is structured, we're going to end up building a lot of descriptors multiple times. Imagine a scenario like below, where `A..G` are file descriptors with the indicated dependency graph.

```
A
|-- B
|   `-- C
|
|-- D
|   |-- E
|   `-- F
|
`-- G
```

If `M` is an event group metadata message inside of `A`, then `M`'s `EventGroupMetadataDescriptor` must contain all of `A` thru `G`. In other words, the loop `for (proto in fileList)` will be called for each of those file descriptors.

To build `A` the recursive call ends up building descriptors in this order: `C-B-E-F-D-G-A`.

Then when we build `B`, we end up building `C-B` from scratch, because the previous `builtFileDescriptorMap` is discarded. Same idea with the remaining file descriptors, with the end result being that we build each file descriptor a number of times equal to its level in the dependency tree (with `A` being at level 1).

Now, I don't imagine this will be a big deal in practice, because I would expect that event group metadata messages use mostly primitives or have relatively shallow dependency trees. But I think it would be good to drop a TODO in here with an associated [issue](https://github.com/world-federation-of-advertisers/cross-media-measurement/issues) to come back and address this at some point.
___
*[src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventGroupMetadataParser.kt, line 45 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/531#-N0HlpiI8sfgw_97somu:-N0HlpiI8sfgw_97somv:b9vjciy) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3c14613f5e526f4dd54abacb7d17f6cd5c370f7f/src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventGroupMetadataParser.kt#L45)):*
> ```Kotlin
>         buildFileDescriptors(
>           proto,
>           /*buildFileDescriptorMap=*/ mutableMapOf(),
> ```

Instead of `/*someParamName=*/`, in Kotlin you can just write the param name. In this case,

```
buildFileDescriptors(
  proto = proto,
  builtFileDescriptorMap = mutableMapOf(),
  fileDescriptorProtoMap = fileDescriptorProtoMap
)
```
___
*[src/test/kotlin/org/wfanet/measurement/api/v2alpha/EventGroupMetadataParserTest.kt, line 95 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/531#-N0HwBS22di8NHruJFW_:-N0HwBS22di8NHruJFWa:bfpix2a) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3c14613f5e526f4dd54abacb7d17f6cd5c370f7f/src/test/kotlin/org/wfanet/measurement/api/v2alpha/EventGroupMetadataParserTest.kt#L95)):*
> ```Kotlin
>     assertFailsWith<NullPointerException> {
>       parser.convertToDynamicMessage(PARENT_EVENT_GROUP_METADATA)
>     }
> ```

The return type of `convertToDynamicMessage()` is `DynamicMessage?`, so I would expect it to return null instead of throwing an exception. Looks like we need to make sure that `DynamicMessage.parseFrom()` is not called with a null descriptor. Something like

```
// inside of convertToDynamicMessage()
val descriptor = typeRegistry.getDescriptorForTypeUrl(...) ?: return null
return DynamicMessage.parseFrom(...)
```



_Code quote:_
```Kotlin
    assertFailsWith<NullPointerException> {
      parser.convertToDynamicMessage(PARENT_EVENT_GROUP_METADATA)
    }
```


<!-- Sent from Reviewable.io -->

2022-04-25 18:16 UTC, chipingyeh reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/531)* status: 5 of 7 files reviewed, 1 unresolved discussion (waiting on @robinsons and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventGroupMetadataParser.kt` line 41 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/531#-N0Hp6qt5XXHS2r4tm3w:-N0WtwuJDfurd6MV-yX5:b-qm2kzp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3c14613f5e526f4dd54abacb7d17f6cd5c370f7f/src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventGroupMetadataParser.kt#L41)):*
<details><summary><i>Previously, robinsons wrote…</i></summary><blockquote>

This comment doesn't affect the correctness of the solution, but it is something that we could fix up in a future PR.

The way this code is structured, we're going to end up building a lot of descriptors multiple times. Imagine a scenario like below, where `A..G` are file descriptors with the indicated dependency graph.

```
A
|-- B
|   `-- C
|
|-- D
|   |-- E
|   `-- F
|
`-- G
```

If `M` is an event group metadata message inside of `A`, then `M`'s `EventGroupMetadataDescriptor` must contain all of `A` thru `G`. In other words, the loop `for (proto in fileList)` will be called for each of those file descriptors.

To build `A` the recursive call ends up building descriptors in this order: `C-B-E-F-D-G-A`.

Then when we build `B`, we end up building `C-B` from scratch, because the previous `builtFileDescriptorMap` is discarded. Same idea with the remaining file descriptors, with the end result being that we build each file descriptor a number of times equal to its level in the dependency tree (with `A` being at level 1).

Now, I don't imagine this will be a big deal in practice, because I would expect that event group metadata messages use mostly primitives or have relatively shallow dependency trees. But I think it would be good to drop a TODO in here with an associated [issue](https://github.com/world-federation-of-advertisers/cross-media-measurement/issues) to come back and address this at some point.
</blockquote></details>

Thanks for the detailed explanation once again. What if I just moved the `builtFileDescriptorMap` outside of the loop, so it persists through the iterations? This way repeated dependencies wouldn't be rebuilt.
___
*[`src/test/kotlin/org/wfanet/measurement/api/v2alpha/EventGroupMetadataParserTest.kt` line 95 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/531#-N0HwBS22di8NHruJFW_:-N0WFSkU2JVc6bsZWD2p:b-wus7yy) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3c14613f5e526f4dd54abacb7d17f6cd5c370f7f/src/test/kotlin/org/wfanet/measurement/api/v2alpha/EventGroupMetadataParserTest.kt#L95)):*
> val descriptor = typeRegistry.getDescriptorForTypeUrl(...) ?: return null
> return DynamicMessage.parseFrom(...)
Good point -- done.


<!-- Sent from Reviewable.io -->

2022-04-26 15:55 UTC, robinsons approved these changes
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/531)* status: all files reviewed, 1 unresolved discussion (waiting on @chipingyeh and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventGroupMetadataParser.kt` line 41 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/531#-N0Hp6qt5XXHS2r4tm3w:-N0aZvqECSjX5XcPjT5f:bb73djm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3c14613f5e526f4dd54abacb7d17f6cd5c370f7f/src/main/kotlin/org/wfanet/measurement/api/v2alpha/EventGroupMetadataParser.kt#L41)):*
<details><summary><i>Previously, chipingyeh wrote…</i></summary><blockquote>

Thanks for the detailed explanation once again. What if I just moved the `builtFileDescriptorMap` outside of the loop, so it persists through the iterations? This way repeated dependencies wouldn't be rebuilt.
</blockquote></details>

SGTM
___
*[`src/test/kotlin/org/wfanet/measurement/api/v2alpha/EventGroupMetadataParserTest.kt` line 93 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/531#-N0a_CrEB5OqxfaU5E93:-N0a_CrEB5OqxfaU5E94:b351i7s) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/22ff48093ad734bb9898a17ff958f5d931ed409b/src/test/kotlin/org/wfanet/measurement/api/v2alpha/EventGroupMetadataParserTest.kt#L93)):*
> ```Kotlin
>     val parser = EventGroupMetadataParser(listOf(eventGroupMetadataDescriptor))
> 
>     assertNull(parser.convertToDynamicMessage(PARENT_EVENT_GROUP_METADATA))
> ```

nit: We can use the Google Truth API, `assertThat(thing).isNull()`


<!-- Sent from Reviewable.io -->

2022-04-27 14:39 UTC, chipingyeh reviewed
> Reviewed 2 of 7 files at r1, 2 of 4 files at r3, 1 of 3 files at r4, 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/531)* status: 6 of 7 files reviewed, all discussions resolved (waiting on @chipingyeh, @robinsons, and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2022-04-27 14:40 UTC, chipingyeh reviewed
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/531)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @robinsons and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2022-04-27 14:40 UTC, merged