Create postgres backing store for the privacy budget management ledger
world-federation-of-advertisers/cross-media-measurement pull request #533
Opened 2022-04-15 04:51 UTC by duliomatos1

Adds a new class `PostgresBackingStore`, which implements a `PrivacyBudgetLedgerBackingStore` that uses a single JDBC Connection, and implements transactions natively through SQL. In addition:
* Makes the BackingStore and TransactionContext implement Closeable (to make sure transactions are either commited or rolledback and connections are closed)
* Transactions can't be nested (given the limitation of one SQL transaction per JDBC connection) - ideally each thread should use it's own  `PostgresBackingStore` instance, so the test simulates this
* Adds `PostgresBackingStoreTest`, based on the changes listed above. It uses `EmbeddedPostgres` to run the tests.

2022-04-18 19:39 UTC, duliomatos1 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/533)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @matthewclegg, @SanjayVas, and @uakyol)

___
*[src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PostgresBackingStoreTest.kt, line 76 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/533#-N-yAJ7nAnaDs6T7AfMX:-N-yAJ7nAnaDs6T7AfMY:b-hq4egm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7fd7b13950497a27d7287c76f313e56b41116d23/src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PostgresBackingStoreTest.kt#L76)):*
> ```Kotlin
>   @Test(timeout = 15000)
>   fun `findIntersectingEntries works as expected`() {
>     createBackingStore(true).use { backingStore: PrivacyBudgetLedgerBackingStore ->
> ```

I think I can create a base test to be re-used by all backing store tests, a new test would only need to implement a `createBackingStore`


<!-- Sent from Reviewable.io -->

2022-04-18 23:06 UTC, duliomatos1 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/533)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @matthewclegg, @SanjayVas, and @uakyol)

___
*[src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/BUILD.bazel, line 25 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/533#-N-ya7xuCLeuCWJN8klw:-N-ya7xv6nmdCBl-mVLx:bhvahba) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7fd7b13950497a27d7287c76f313e56b41116d23/src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/BUILD.bazel#L25)):*
> ```Starlark
> )
> 
> kt_jvm_test(
> ```

Guys, can I simplify and make this BUILD file have just a single `glob("*.kt")` rule? I've seem an example of this in `panel-exchange-client/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/`
___
*[src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PostgresBackingStoreTest.kt, line 76 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/533#-N-yAJ7nAnaDs6T7AfMX:-N-yvIcm4rzmvoNhO_fs:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7fd7b13950497a27d7287c76f313e56b41116d23/src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PostgresBackingStoreTest.kt#L76)):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

I think I can create a base test to be re-used by all backing store tests, a new test would only need to implement a `createBackingStore`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-04-19 21:05 UTC, SanjayVas reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/533)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @matthewclegg and @uakyol)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/533#-N02dBap0QFl4i0M31Ca:-N02dBap0QFl4i0M31Cb:b-i9cxfg) (no related file):*
Waiting for Ugur to take an initial pass.

---


<!-- Sent from Reviewable.io -->

2022-04-19 21:38 UTC, duliomatos1 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/533)* status: 0 of 8 files reviewed, 4 unresolved discussions (waiting on @matthewclegg and @uakyol)

___
*[src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PostgresBackingStore.kt, line 170 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/533#-N02csBk3CAGZFDshnT4:-N02csBk3CAGZFDshnT5:b2kgmpy) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5c1f192b9a078b3ceb24820e756bc3ef70894b37/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PostgresBackingStore.kt#L170)):*
> ```Kotlin
>   }
> 
>   override fun updateLedgerEntry(privacyBudgetLedgerEntry: PrivacyBudgetLedgerEntry) {
> ```

I'm not really sure about this update function. It has too much power by being able to update a previous entry and overriding the transaction system.
Do we expect that e.g.`undoPreviousTransaction()` works after an `updateLedgerEntry()`?
We can make the backing stores implement `chargePrivacyBucketGroups()` directly and do without this function I would believe
___
*[src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PostgresBackingStore.kt, line 204 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/533#-N02hdPk0vgtz-Cy9KdU:-N02hdPk0vgtz-Cy9KdV:b-gm2m9f) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5c1f192b9a078b3ceb24820e756bc3ef70894b37/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PostgresBackingStore.kt#L204)):*
> ```Kotlin
>   }
> 
>   override fun mergePreviousTransaction(previousTransactionId: Long) {
> ```

Will `mergePreviousTransaction()` be used after a request has been fulfilled?
___
*[src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PostgresBackingStore.kt, line 220 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/533#-N02gjmr3v0Bnt_kkZPX:-N02gjmr3v0Bnt_kkZPY:b-ooohbi) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5c1f192b9a078b3ceb24820e756bc3ef70894b37/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PostgresBackingStore.kt#L220)):*
> ```Kotlin
>   }
> 
>   override fun undoPreviousTransaction(previousTransactionId: Long) {
> ```

What's the current use case of `undoPreviousTransaction()`? Would this be to return a privacy budget that wasn't really used for some reason?


<!-- Sent from Reviewable.io -->

2022-04-19 21:39 UTC, duliomatos1 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/533)* status: 0 of 8 files reviewed, 4 unresolved discussions (waiting on @matthewclegg and @uakyol)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/533#-N02dBap0QFl4i0M31Ca:-N02kxnk1HMhs7AQP7_O:b-7j86r0) (no related file):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Waiting for Ugur to take an initial pass.
</blockquote></details>

sure.

---


<!-- Sent from Reviewable.io -->

2022-04-20 19:26 UTC, duliomatos1 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/533)* status: 0 of 8 files reviewed, 4 unresolved discussions (waiting on @matthewclegg and @uakyol)

___
*[src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PostgresBackingStore.kt, line 204 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/533#-N02hdPk0vgtz-Cy9KdU:-N07QapbE6Spt3D4-jy2:b-fi3l6u) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5c1f192b9a078b3ceb24820e756bc3ef70894b37/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PostgresBackingStore.kt#L204)):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

Will `mergePreviousTransaction()` be used after a request has been fulfilled?
</blockquote></details>

I'm proposing a more complex `mergePreviousTransaction()` that does elimininates repeated entries by increasing repetition count. I'll include a comprehensive test and make `InMemoryBackingStore` do the same so we can mandate that all implementations eliminate repeated entries.


<!-- Sent from Reviewable.io -->

2022-04-20 21:47 UTC, duliomatos1 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/533)* status: 0 of 8 files reviewed, 4 unresolved discussions (waiting on @matthewclegg and @uakyol)

___
*[src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PostgresBackingStore.kt, line 204 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/533#-N02hdPk0vgtz-Cy9KdU:-N07wFxFBdfWvdVwrR78:b-43sw6h) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5c1f192b9a078b3ceb24820e756bc3ef70894b37/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PostgresBackingStore.kt#L204)):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

I'm proposing a more complex `mergePreviousTransaction()` that does elimininates repeated entries by increasing repetition count. I'll include a comprehensive test and make `InMemoryBackingStore` do the same so we can mandate that all implementations eliminate repeated entries.
</blockquote></details>

See #538 


<!-- Sent from Reviewable.io -->

2022-04-21 21:17 UTC, uakyol requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/533)* status: 0 of 8 files reviewed, 6 unresolved discussions (waiting on @duliomatos1 and @matthewclegg)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/533#-N02dBap0QFl4i0M31Ca:-N07_HJr7ZdOnbY0hb9T:b6ptdqx) (no related file):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

sure.
</blockquote></details>

I was out sick for most this week, thanks for the wait Dulio. 

I think we will need to tweak the api. While trying to use it internally, we realized the PBM supporting idempotent keys for each transaction is an important win. So, the caller of the PBM would support a unique id for a charge operation and later on can use that same key to rollback that operation if necessary. The most straightforward way to to do this is that the caller provides the requisitionId. 

This however, imposes that the ledger backing store should be immutable. So each charge should be a new row and thus, the repetition_count field will no longer work unfortunately. Therefore, we should have 2 tables and normalize.

I realize this is a lot of changes and you have about a week left before vacation. So my suggestion is to submit this PR by :

1) Not implementing and adding a todo for undoPreviousTransaction, its not being used anywhere yet.
2) Leaving updateLedgerEntry logic as you implemented.
3) mergePreviousTransaction is not being used anywhere right now, so lets put a TODO there too,


And once this is submitted, I will implement the idempotency.

What do you think of this plan?

This PR does all the important work, I'll just change this file, the Api and the in-memory implementation a little to make them immutable.

---
___
*[src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PostgresBackingStore.kt, line 170 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/533#-N02csBk3CAGZFDshnT4:-N0CrqnVEx1XeQF0vfY7:b-kyij9s) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5c1f192b9a078b3ceb24820e756bc3ef70894b37/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PostgresBackingStore.kt#L170)):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

I'm not really sure about this update function. It has too much power by being able to update a previous entry and overriding the transaction system.
Do we expect that e.g.`undoPreviousTransaction()` works after an `updateLedgerEntry()`?
We can make the backing stores implement `chargePrivacyBucketGroups()` directly and do without this function I would believe
</blockquote></details>

You are right Dulio, I agree. Per my comments above, if the ledger is immutable, updateLedgerEntry would be gone. 
___
*[src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PostgresBackingStore.kt, line 204 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/533#-N02hdPk0vgtz-Cy9KdU:-N0Cvwh33qxH4iJ360-3:b-c8pbrs) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5c1f192b9a078b3ceb24820e756bc3ef70894b37/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PostgresBackingStore.kt#L204)):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

See #538 
</blockquote></details>

This sounds great Dulio, thank you for putting this together. However, to keep the ledger immutable, we probably will change this so I would propose to put a TODO in my name for me to tackle later.
___
*[src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PostgresBackingStore.kt, line 220 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/533#-N02gjmr3v0Bnt_kkZPX:-N0Crb6-0i3uU69V1GU1:be11wd0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5c1f192b9a078b3ceb24820e756bc3ef70894b37/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PostgresBackingStore.kt#L220)):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

What's the current use case of `undoPreviousTransaction()`? Would this be to return a privacy budget that wasn't really used for some reason?
</blockquote></details>

There is none yet. Per my comments above , when the ledger is immutable, this function will essentially insert a negative charge to the ledger. For now, lets leave this function empty with a TODO(@uakyol) : Implement this function as part of making the ledger immutable. 
___
*[src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PostgresBackingStore.kt, line 239 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/533#-N0CyFsoBoFemovFU3m2:-N0CyFsoBoFemovFU3m3:bq0ncok) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5c1f192b9a078b3ceb24820e756bc3ef70894b37/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PostgresBackingStore.kt#L239)):*
> ```Kotlin
>   }
> 
>   override fun close() {
> ```

sounds good
___
*[src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/AbstractPrivacyBudgetLedgerStoreTest.kt, line 20 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/533#-N0CyKJD-0Im4oUSAeTq:-N0CyKJD-0Im4oUSAeTr:b-b3g4c) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8c04392bc79cdd1c388f3cf67251136440fcbf77/src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/AbstractPrivacyBudgetLedgerStoreTest.kt#L20)):*
> ```Kotlin
> import org.junit.Test
> 
> abstract class AbstractPrivacyBudgetLedgerStoreTest {
> ```

This is great thank you!
___
*[src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/BUILD.bazel, line 25 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/533#-N-ya7xuCLeuCWJN8klw:-N0Crzo9Eq7R58W56I_I:btn4dc8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7fd7b13950497a27d7287c76f313e56b41116d23/src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/BUILD.bazel#L25)):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

Guys, can I simplify and make this BUILD file have just a single `glob("*.kt")` rule? I've seem an example of this in `panel-exchange-client/src/main/kotlin/org/wfanet/panelmatch/client/privatemembership/testing/`
</blockquote></details>

we want to be able to test these classes separately, so probably not a good idea.


<!-- Sent from Reviewable.io -->

2022-04-22 13:53 UTC, duliomatos1 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/533)* status: 0 of 8 files reviewed, 6 unresolved discussions (waiting on @duliomatos1, @matthewclegg, and @uakyol)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/533#-N02dBap0QFl4i0M31Ca:-N0GWvWC2SW8rUTXzp4k:b67b5m3) (no related file):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

I was out sick for most this week, thanks for the wait Dulio. 

I think we will need to tweak the api. While trying to use it internally, we realized the PBM supporting idempotent keys for each transaction is an important win. So, the caller of the PBM would support a unique id for a charge operation and later on can use that same key to rollback that operation if necessary. The most straightforward way to to do this is that the caller provides the requisitionId. 

This however, imposes that the ledger backing store should be immutable. So each charge should be a new row and thus, the repetition_count field will no longer work unfortunately. Therefore, we should have 2 tables and normalize.

I realize this is a lot of changes and you have about a week left before vacation. So my suggestion is to submit this PR by :

1) Not implementing and adding a todo for undoPreviousTransaction, its not being used anywhere yet.
2) Leaving updateLedgerEntry logic as you implemented.
3) mergePreviousTransaction is not being used anywhere right now, so lets put a TODO there too,


And once this is submitted, I will implement the idempotency.

What do you think of this plan?

This PR does all the important work, I'll just change this file, the Api and the in-memory implementation a little to make them immutable.



</blockquote></details>

Yeah it makes sense to me. Undoing a transaction and merging the repetition count were not straightforward in the initial API, wasn't seeing the benefit of the added complexity, being immutable seems to be a much better design.

---
___
*[src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PostgresBackingStore.kt, line 204 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/533#-N02hdPk0vgtz-Cy9KdU:-N0GXpoQ5tqb9p8EM0J3:bkjxpv0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5c1f192b9a078b3ceb24820e756bc3ef70894b37/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PostgresBackingStore.kt#L204)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

This sounds great Dulio, thank you for putting this together. However, to keep the ledger immutable, we probably will change this so I would propose to put a TODO in my name for me to tackle later.
</blockquote></details>

alright
___
*[src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PostgresBackingStore.kt, line 220 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/533#-N02gjmr3v0Bnt_kkZPX:-N0GXk86DG-MvNnYVzfJ:bob6hyg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5c1f192b9a078b3ceb24820e756bc3ef70894b37/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PostgresBackingStore.kt#L220)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

There is none yet. Per my comments above , when the ledger is immutable, this function will essentially insert a negative charge to the ledger. For now, lets leave this function empty with a TODO(@uakyol) : Implement this function as part of making the ledger immutable. 
</blockquote></details>

perfect
___
*[src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/BUILD.bazel, line 25 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/533#-N-ya7xuCLeuCWJN8klw:-N0GXnh72cnhFuNYjX_-:bb7efny) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7fd7b13950497a27d7287c76f313e56b41116d23/src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/BUILD.bazel#L25)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

we want to be able to test these classes separately, so probably not a good idea.
</blockquote></details>

cool


<!-- Sent from Reviewable.io -->

2022-04-22 13:54 UTC, duliomatos1 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/533)* status: 0 of 8 files reviewed, 6 unresolved discussions (waiting on @duliomatos1, @matthewclegg, and @uakyol)

___
*[src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PostgresBackingStore.kt, line 170 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/533#-N02csBk3CAGZFDshnT4:-N0GYBkg5w53Nsky-rlc:bjugzjg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5c1f192b9a078b3ceb24820e756bc3ef70894b37/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PostgresBackingStore.kt#L170)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

You are right Dulio, I agree. Per my comments above, if the ledger is immutable, updateLedgerEntry would be gone. 
</blockquote></details>

cool, that's way better


<!-- Sent from Reviewable.io -->

2022-04-22 16:49 UTC, duliomatos1 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/533)* status: 0 of 8 files reviewed, 3 unresolved discussions (waiting on @duliomatos1, @matthewclegg, and @uakyol)

___
*[src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PostgresBackingStore.kt, line 170 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/533#-N02csBk3CAGZFDshnT4:-N0HA79H89cR_nsYVbY4:bl8x3yy) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5c1f192b9a078b3ceb24820e756bc3ef70894b37/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PostgresBackingStore.kt#L170)):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

cool, that's way better
</blockquote></details>

Done. Added a TODO as well
___
*[src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PostgresBackingStore.kt, line 204 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/533#-N02hdPk0vgtz-Cy9KdU:-N0HAA5r8hvjJ6lxIxCo:b-gabz46) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5c1f192b9a078b3ceb24820e756bc3ef70894b37/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PostgresBackingStore.kt#L204)):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

alright
</blockquote></details>

Done. No need to keep this implementation
___
*[src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PostgresBackingStore.kt, line 220 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/533#-N02gjmr3v0Bnt_kkZPX:-N0HADEr-P60IwIyQuyq:b-7oiuq4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5c1f192b9a078b3ceb24820e756bc3ef70894b37/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PostgresBackingStore.kt#L220)):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

perfect
</blockquote></details>

Done. No need to keep this implementation.


<!-- Sent from Reviewable.io -->

2022-04-25 15:11 UTC, duliomatos1 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/533)* status: 0 of 8 files reviewed, 4 unresolved discussions (waiting on @duliomatos1, @matthewclegg, and @uakyol)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PostgresBackingStore.kt` line 219 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/533#-N0WG1KX7sfJ08KAkkcz:-N0WG1KX7sfJ08KAkkd-:bizskgl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/61414619088983badfefbeea0908f257c90dbe39/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PostgresBackingStore.kt#L219)):*
> ```Kotlin
> 
>   override fun close() {
>     connection.rollback()
> ```

to be clear, this rollback will cancel any transaction that is still opened - there was no commit() before the transactionContext is closed - so we're able to start a new transaction cleanly


<!-- Sent from Reviewable.io -->

2022-04-25 18:36 UTC, uakyol approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/533)* status: 0 of 8 files reviewed, 4 unresolved discussions (waiting on @duliomatos1, @matthewclegg, and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2022-04-25 19:24 UTC, SanjayVas requested changes
> Reviewed 3 of 6 files at r1, 3 of 4 files at r2, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/533)* status: all files reviewed, 11 unresolved discussions (waiting on @duliomatos1, @matthewclegg, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PostgresBackingStore.kt` line 14 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/533#-N0X3K7nAZXRRxEdStt-:-N0X3K7nAZXRRxEdStt0:bxog4ec) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/61414619088983badfefbeea0908f257c90dbe39/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PostgresBackingStore.kt#L14)):*
> ```Kotlin
>  * the License.
>  */
> package org.wfanet.measurement.eventdataprovider.privacybudgetmanagement
> ```

Our convention has been to put anything that relies on a specific stack into a subpackage under a `deploy` package. e.g. `deploy.postgres` for the Postgres-based implementation. This way it's very obvious once you're getting into something with specific dependencies that might have alternate implementations.
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PostgresBackingStore.kt` line 24 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/533#-N0X3yki0cbZSDlajB8Q:-N0X3yki0cbZSDlajB8R:bw3u62u) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/61414619088983badfefbeea0908f257c90dbe39/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PostgresBackingStore.kt#L24)):*
> ```Kotlin
> class PostgresBackingStore(private val connection: Connection) : PrivacyBudgetLedgerBackingStore {
>   init {
>     connection.autoCommit = false
> ```

Should be a `require` checking this rather than setting it on a connection that's technically owned by the caller.



_Code quote:_
```Kotlin
connection.autoCommit = false
```
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PostgresBackingStore.kt` line 105 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/533#-N0X5c8U4N54ZXUgknMn:-N0X5c8U4N54ZXUgknMo:bv3kvub) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/61414619088983badfefbeea0908f257c90dbe39/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PostgresBackingStore.kt#L105)):*
> ```Kotlin
>       statement.setString(4, privacyBucketGroup.gender.string)
>       statement.setFloat(5, privacyBucketGroup.vidSampleStart)
>       statement.executeQuery().use { rs: ResultSet ->
> ```

Can you add a TODO to do all the blocking IO in another dispatcher w/coroutines? We avoid doing any blocking IO in the main thread/dispatcher.

It probably doesn't need to go this far since the JDBC API is inherently synchronous, but we wrote our own [coroutine wrapper around the Spanner client](https://github.com/world-federation-of-advertisers/common-jvm/blob/main/src/main/kotlin/org/wfanet/measurement/gcloud/spanner/AsyncDatabaseClient.kt) for this reason. For JDBC, I think the best we can do is just making sure all the IO is happening in the Kotlin equivalent of "background threads".



_Code quote:_
```Kotlin
statement.executeQuery()
```
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetLedgerBackingStore.kt` line 34 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/533#-N0X8l1k3bHQziGsP_5l:-N0X8l1k3bHQziGsP_5m:bflmj0q) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/61414619088983badfefbeea0908f257c90dbe39/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetLedgerBackingStore.kt#L34)):*
> ```Kotlin
> 
> /** Manages the persistence of privacy budget data. */
> interface PrivacyBudgetLedgerBackingStore : Closeable {
> ```

Closeable is the old interface. Use `AutoCloseable`.



_Code quote:_
```Kotlin
Closeable
```
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetManagerException.kt` line 17 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/533#-N0X9-6Z2bFQ8E_ylah4:-N0X9-6Z2bFQ8E_ylah5:b1xjltm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/61414619088983badfefbeea0908f257c90dbe39/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetManagerException.kt#L17)):*
> ```Kotlin
> 
> enum class PrivacyBudgetManagerExceptionType(val errorMessage: String) {
>   PRIVACY_BUDGET_EXCEEDED("The available privacy budget was exceeded"),
> ```

Doesn't need to be handled in this PR, but what's the primary reason for using an enum vs. a sealed exception class hierarchy here?

See Effective Java 3rd Ed, item 23 "Prefer class hierarchies to tagged classes".
___
*[`src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/AbstractPrivacyBudgetLedgerStoreTest.kt` line 22 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/533#-N0XAKDs6ygzJcYLGmo8:-N0XAKDs6ygzJcYLGmo9:b-g99vjq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/61414619088983badfefbeea0908f257c90dbe39/src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/AbstractPrivacyBudgetLedgerStoreTest.kt#L22)):*
> ```Kotlin
> abstract class AbstractPrivacyBudgetLedgerStoreTest {
>   protected abstract fun createBackingStore(
>     createSchema: Boolean = false
> ```

It looks like this parameter is always true?



_Code quote:_
```Kotlin
createSchema: Boolean = false
```
___
*[`src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/AbstractPrivacyBudgetLedgerStoreTest.kt` line 26 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/533#-N0X9d4_EFe4UCNdesl4:-N0X9d4_EFe4UCNdesl5:b-w709g9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/61414619088983badfefbeea0908f257c90dbe39/src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/AbstractPrivacyBudgetLedgerStoreTest.kt#L26)):*
> ```Kotlin
> 
>   @Test(timeout = 15000)
>   fun `findIntersectingEntries works as expected`() {
> ```

Be more specific than "works as expected" and actually describe the behavior the test is validating. Split it into multiple test methods if needed to test different conditions.



_Code quote:_
```Kotlin
works as expected
```


<!-- Sent from Reviewable.io -->

2022-04-25 20:03 UTC, duliomatos1 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/533)* status: all files reviewed, 11 unresolved discussions (waiting on @duliomatos1, @matthewclegg, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PostgresBackingStore.kt` line 14 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/533#-N0X3K7nAZXRRxEdStt-:-N0XIA9G7RVLWzWYf4H1:b-q8jzb0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/61414619088983badfefbeea0908f257c90dbe39/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PostgresBackingStore.kt#L14)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Our convention has been to put anything that relies on a specific stack into a subpackage under a `deploy` package. e.g. `deploy.postgres` for the Postgres-based implementation. This way it's very obvious once you're getting into something with specific dependencies that might have alternate implementations.
</blockquote></details>

got it
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PostgresBackingStore.kt` line 24 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/533#-N0X3yki0cbZSDlajB8Q:-N0XIojK5DTgCfc7_M8H:ba01bue) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/61414619088983badfefbeea0908f257c90dbe39/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PostgresBackingStore.kt#L24)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Should be a `require` checking this rather than setting it on a connection that's technically owned by the caller.
</blockquote></details>

Good point. Actually if we go on the `require()` route, I would prepend any method implemented here with this check
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PostgresBackingStore.kt` line 105 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/533#-N0X5c8U4N54ZXUgknMn:-N0XHuIN92vkCMz_eZ6w:b-80tlqk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/61414619088983badfefbeea0908f257c90dbe39/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PostgresBackingStore.kt#L105)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Can you add a TODO to do all the blocking IO in another dispatcher w/coroutines? We avoid doing any blocking IO in the main thread/dispatcher.

It probably doesn't need to go this far since the JDBC API is inherently synchronous, but we wrote our own [coroutine wrapper around the Spanner client](https://github.com/world-federation-of-advertisers/common-jvm/blob/main/src/main/kotlin/org/wfanet/measurement/gcloud/spanner/AsyncDatabaseClient.kt) for this reason. For JDBC, I think the best we can do is just making sure all the IO is happening in the Kotlin equivalent of "background threads".
</blockquote></details>

Sure.
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetLedgerBackingStore.kt` line 34 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/533#-N0X8l1k3bHQziGsP_5l:-N0XHhVz1QELYsKPwciQ:brecqzj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/61414619088983badfefbeea0908f257c90dbe39/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetLedgerBackingStore.kt#L34)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Closeable is the old interface. Use `AutoCloseable`.
</blockquote></details>

got it. Thanks


<!-- Sent from Reviewable.io -->

2022-04-25 20:21 UTC, duliomatos1 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/533)* status: all files reviewed, 11 unresolved discussions (waiting on @duliomatos1, @matthewclegg, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PostgresBackingStore.kt` line 24 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/533#-N0X3yki0cbZSDlajB8Q:-N0XLw8tC8YiZpSxBrAK:bzct9y9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/61414619088983badfefbeea0908f257c90dbe39/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PostgresBackingStore.kt#L24)):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

Good point. Actually if we go on the `require()` route, I would prepend any method implemented here with this check
</blockquote></details>

I'm on the fence here if it's not valuable to do this configuration here, and still have the `require()` on the methods. Another option is to pass an interface that has a `getConnection()` method, instead of the opened connection, so the backing store will own the connection completely


<!-- Sent from Reviewable.io -->

2022-04-25 20:30 UTC, duliomatos1 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/533)* status: all files reviewed, 11 unresolved discussions (waiting on @duliomatos1, @matthewclegg, @SanjayVas, @stevenwarejones, and @uakyol)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetManagerException.kt` line 17 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/533#-N0X9-6Z2bFQ8E_ylah4:-N0XP4PmAcDH4s_YUKea:b-96dgdp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/61414619088983badfefbeea0908f257c90dbe39/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetManagerException.kt#L17)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Doesn't need to be handled in this PR, but what's the primary reason for using an enum vs. a sealed exception class hierarchy here?

See Effective Java 3rd Ed, item 23 "Prefer class hierarchies to tagged classes".
</blockquote></details>

I've remembered your comment in another PR when I saw this class :-). Maybe have a TODO here to refactor this? (and the same for other instances where we're not using exception hierarchies). @uakyol wdyt?


<!-- Sent from Reviewable.io -->

2022-04-25 20:38 UTC, duliomatos1 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/533)* status: all files reviewed, 11 unresolved discussions (waiting on @duliomatos1, @matthewclegg, @SanjayVas, @stevenwarejones, and @uakyol)

___
*[`src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/AbstractPrivacyBudgetLedgerStoreTest.kt` line 22 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/533#-N0XAKDs6ygzJcYLGmo8:-N0XPqDoBv7jIhHdSUYG:b-kk4436) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/61414619088983badfefbeea0908f257c90dbe39/src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/AbstractPrivacyBudgetLedgerStoreTest.kt#L22)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

It looks like this parameter is always true?
</blockquote></details>

I've actually removed the tests that used this param because we're not implementing mergePreviousTransaction / undoPreviousTransaction anymore as the ledger will be made immutable, but it will have to be available once we do implement, to be able to test more than one transaction at the same time.
___
*[`src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/AbstractPrivacyBudgetLedgerStoreTest.kt` line 26 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/533#-N0X9d4_EFe4UCNdesl4:-N0XQZhCC0S9DO0eFNfX:bz71crm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/61414619088983badfefbeea0908f257c90dbe39/src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/AbstractPrivacyBudgetLedgerStoreTest.kt#L26)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Be more specific than "works as expected" and actually describe the behavior the test is validating. Split it into multiple test methods if needed to test different conditions.
</blockquote></details>

I've moved these existing test cases over to this abstract class but you're right. Let me improve these descriptions.


<!-- Sent from Reviewable.io -->

2022-04-25 21:49 UTC, duliomatos1 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/533)* status: all files reviewed, 11 unresolved discussions (waiting on @duliomatos1, @matthewclegg, @SanjayVas, @stevenwarejones, and @uakyol)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PostgresBackingStore.kt` line 24 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/533#-N0X3yki0cbZSDlajB8Q:-N0Xgkxs7z1xDfAjI-Cn:b-jarbih) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/61414619088983badfefbeea0908f257c90dbe39/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PostgresBackingStore.kt#L24)):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

I'm on the fence here if it's not valuable to do this configuration here, and still have the `require()` on the methods. Another option is to pass an interface that has a `getConnection()` method, instead of the opened connection, so the backing store will own the connection completely
</blockquote></details>

Basically passing a `ConnectionProvider` interface


<!-- Sent from Reviewable.io -->

2022-04-25 21:50 UTC, SanjayVas reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/533)* status: all files reviewed, 11 unresolved discussions (waiting on @duliomatos1, @matthewclegg, @SanjayVas, @stevenwarejones, and @uakyol)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/533#-N0Xh-cXDXlG0mM4P8w1:-N0Xh-cXDXlG0mM4P8w2:b5do7ja) (no related file):*
Reminder to avoid replying to comments when there's no action for the reviewer to take. See https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/docs/dev-standards.md#code-review-workflow

I pinged you a couple times about this in the #code-review channel on Slack.

---


<!-- Sent from Reviewable.io -->

2022-04-26 18:04 UTC, duliomatos1 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/533)* status: 2 of 11 files reviewed, 8 unresolved discussions (waiting on @duliomatos1, @matthewclegg, @SanjayVas, @stevenwarejones, and @uakyol)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetLedgerBackingStore.kt` line 34 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/533#-N0X8l1k3bHQziGsP_5l:-N0akKB5-QnShQlfgw5o:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/61414619088983badfefbeea0908f257c90dbe39/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetLedgerBackingStore.kt#L34)):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

got it. Thanks
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetManagerException.kt` line 17 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/533#-N0X9-6Z2bFQ8E_ylah4:-N0akLuWBbixPRg1aZ2w:b-seeysh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/61414619088983badfefbeea0908f257c90dbe39/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetManagerException.kt#L17)):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

I've remembered your comment in another PR when I saw this class :-). Maybe have a TODO here to refactor this? (and the same for other instances where we're not using exception hierarchies). @uakyol wdyt?
</blockquote></details>

Done. Added TODO
___
*[`src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/AbstractPrivacyBudgetLedgerStoreTest.kt` line 22 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/533#-N0XAKDs6ygzJcYLGmo8:-N0akPlrC0Zdel8HG0e1:b76u3kb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/61414619088983badfefbeea0908f257c90dbe39/src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/AbstractPrivacyBudgetLedgerStoreTest.kt#L22)):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

I've actually removed the tests that used this param because we're not implementing mergePreviousTransaction / undoPreviousTransaction anymore as the ledger will be made immutable, but it will have to be available once we do implement, to be able to test more than one transaction at the same time.
</blockquote></details>

Done. Keeping as is for the reason above
___
*[`src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/AbstractPrivacyBudgetLedgerStoreTest.kt` line 26 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/533#-N0X9d4_EFe4UCNdesl4:-N0ar2ujBGy8BN0J-d9r:b-ewf7ek) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/61414619088983badfefbeea0908f257c90dbe39/src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/AbstractPrivacyBudgetLedgerStoreTest.kt#L26)):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

I've moved these existing test cases over to this abstract class but you're right. Let me improve these descriptions.
</blockquote></details>

Done. @uakyol may also change these in another opened PR that changes the original test.
___
*[`src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/BUILD.bazel` line 25 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/533#-N-ya7xuCLeuCWJN8klw:-N0akVUfA7yjX1D2VYZz:b32wtd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7fd7b13950497a27d7287c76f313e56b41116d23/src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/BUILD.bazel#L25)):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

cool
</blockquote></details>

ok
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PostgresBackingStore.kt` line 14 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/533#-N0X3K7nAZXRRxEdStt-:-N0ajNIB-nbWyqPl_LAr:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/61414619088983badfefbeea0908f257c90dbe39/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PostgresBackingStore.kt#L14)):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

got it
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PostgresBackingStore.kt` line 24 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/533#-N0X3yki0cbZSDlajB8Q:-N0ajPBNERcWg1rAXisy:byqbj2q) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/61414619088983badfefbeea0908f257c90dbe39/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PostgresBackingStore.kt#L24)):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

Basically passing a `ConnectionProvider` interface
</blockquote></details>

Done. Passing a `getConnection` function, and documenting the ownership concerns.
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PostgresBackingStore.kt` line 105 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/533#-N0X5c8U4N54ZXUgknMn:-N0anY-z9MQUY3WV9uaC:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/61414619088983badfefbeea0908f257c90dbe39/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PostgresBackingStore.kt#L105)):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

Sure.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-04-27 00:33 UTC, SanjayVas requested changes
> Reviewed 4 of 9 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/533)* status: 6 of 11 files reviewed, 9 unresolved discussions (waiting on @duliomatos1, @matthewclegg, @SanjayVas, @stevenwarejones, and @uakyol)

___
*[`imports/kotlin/kotlin/BUILD.bazel` line 4 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/533#-N0cAjkm2dKkainWnl1M:-N0cAjkm2dKkainWnl1N:bwox70a) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c7f1f459211c10a695f803cc4995d8ba9d3521a6/imports/kotlin/kotlin/BUILD.bazel#L4)):*
> ```Starlark
> 
> alias(
>     name = "stdlib_jdk7",
> ```

Import already exists in common-jvm.
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/deploy/postgres/BUILD.bazel` line 9 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/533#-N0cB4t0DlOXWYObSQek:-N0cB4t0DlOXWYObSQel:bho3otb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c7f1f459211c10a695f803cc4995d8ba9d3521a6/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/deploy/postgres/BUILD.bazel#L9)):*
> ```Starlark
> 
> kt_jvm_library(
>     name = "privacy_budget_manager_postgres",
> ```

Just `postgres_backing_store`, or glob all srcs and use the default target name for the package.



_Code quote:_
```Starlark
privacy_budget_manager_postgres
```
___
*[`src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/AbstractPrivacyBudgetLedgerStoreTest.kt` line 22 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/533#-N0XAKDs6ygzJcYLGmo8:-N0cPoTw0vwr27V2lp9g:b-vhzqkk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/61414619088983badfefbeea0908f257c90dbe39/src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/AbstractPrivacyBudgetLedgerStoreTest.kt#L22)):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

Done. Keeping as is for the reason above
</blockquote></details>

The tests should be implemented such that all of the test functions can be executed in parallel. I don't think what you've described works that way.
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/deploy/postgres/PostgresBackingStore.kt` line 34 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/533#-N0cPaVS4QS113kmt0jL:-N0cPaVS4QS113kmt0jM:b28x513) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c7f1f459211c10a695f803cc4995d8ba9d3521a6/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/deploy/postgres/PostgresBackingStore.kt#L34)):*
> ```Kotlin
>  * the backing store and should not be used outside this backing store.
>  */
> class PostgresBackingStore(getConnection: () -> Connection) : PrivacyBudgetLedgerBackingStore {
> ```

nit: `connect` or `createConnection` or something to avoid implying that this isn't instantiating a new connection.



_Code quote:_
```Kotlin
getConnection
```
___
*[`src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/deploy/postgres/PostgresBackingStoreTest.kt` line 70 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/533#-N0cQn65B63GIT-pLewQ:-N0cQn65B63GIT-pLewR:b4048xn) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c7f1f459211c10a695f803cc4995d8ba9d3521a6/src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/deploy/postgres/PostgresBackingStoreTest.kt#L70)):*
> ```Kotlin
>       }
>     }
>     return PostgresBackingStore { connection }
> ```

By the contract for the constructor, this must create a new connection every time.



_Code quote:_
```Kotlin
{ connection }
```


<!-- Sent from Reviewable.io -->

2022-04-27 13:55 UTC, duliomatos1 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/533)* status: 6 of 11 files reviewed, 9 unresolved discussions (waiting on @duliomatos1, @matthewclegg, @SanjayVas, @stevenwarejones, and @uakyol)

___
*[`src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/AbstractPrivacyBudgetLedgerStoreTest.kt` line 22 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/533#-N0XAKDs6ygzJcYLGmo8:-N0fFKQK0eRuX2WMmcik:b-9wic32) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/61414619088983badfefbeea0908f257c90dbe39/src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/AbstractPrivacyBudgetLedgerStoreTest.kt#L22)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The tests should be implemented such that all of the test functions can be executed in parallel. I don't think what you've described works that way.
</blockquote></details>

I mean, in the same test we will need to instantiate two different transactions at the same time, each transaction will be using a separate backing store. When instantiating the second backing store, the test should not recreate the schema. I can be more explicit and separate the schema creation from the backing store creation, wdyt?
___
*[`src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/deploy/postgres/PostgresBackingStoreTest.kt` line 70 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/533#-N0cQn65B63GIT-pLewQ:-N0fGJSZBSG_ZPDbJTSG:bar7xh2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c7f1f459211c10a695f803cc4995d8ba9d3521a6/src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/deploy/postgres/PostgresBackingStoreTest.kt#L70)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

By the contract for the constructor, this must create a new connection every time.
</blockquote></details>

Yeah. I think that we could break this contract intentionally in unit testing so make it lighter (avoiding a opening a lot of connections), but this may be premature optimization. I could either comment the intention here, or pass a real connection creator. Wdyt?


<!-- Sent from Reviewable.io -->

2022-04-27 16:28 UTC, duliomatos1 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/533)* status: 9 of 11 files reviewed, 9 unresolved discussions (waiting on @duliomatos1, @matthewclegg, @SanjayVas, and @uakyol)

___
*[`imports/kotlin/kotlin/BUILD.bazel` line 4 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/533#-N0cAjkm2dKkainWnl1M:-N0fSiyz8UerEj1G45sl:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c7f1f459211c10a695f803cc4995d8ba9d3521a6/imports/kotlin/kotlin/BUILD.bazel#L4)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Import already exists in common-jvm.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/deploy/postgres/BUILD.bazel` line 9 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/533#-N0cB4t0DlOXWYObSQek:-N0fS3b_7IfXmWZfysQh:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c7f1f459211c10a695f803cc4995d8ba9d3521a6/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/deploy/postgres/BUILD.bazel#L9)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Just `postgres_backing_store`, or glob all srcs and use the default target name for the package.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/deploy/postgres/PostgresBackingStore.kt` line 34 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/533#-N0cPaVS4QS113kmt0jL:-N0fT7No1X1c3YDd_1nR:b-20h36) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c7f1f459211c10a695f803cc4995d8ba9d3521a6/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/deploy/postgres/PostgresBackingStore.kt#L34)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: `connect` or `createConnection` or something to avoid implying that this isn't instantiating a new connection.
</blockquote></details>

Done. `createConnection()`
___
*[`src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/deploy/postgres/PostgresBackingStoreTest.kt` line 70 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/533#-N0cQn65B63GIT-pLewQ:-N0fqE3PD57Bt8sYxPdx:b-5le0t8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c7f1f459211c10a695f803cc4995d8ba9d3521a6/src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/deploy/postgres/PostgresBackingStoreTest.kt#L70)):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

Yeah. I think that we could break this contract intentionally in unit testing so make it lighter (avoiding a opening a lot of connections), but this may be premature optimization. I could either comment the intention here, or pass a real connection creator. Wdyt?
</blockquote></details>

Done. Included a comment but let me know if you think it's better to go on the route of creating many connections for the tests


<!-- Sent from Reviewable.io -->

2022-04-27 16:41 UTC, duliomatos1 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/533)* status: 4 of 11 files reviewed, 9 unresolved discussions (waiting on @duliomatos1, @matthewclegg, @SanjayVas, @stevenwarejones, and @uakyol)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/deploy/postgres/BUILD.bazel` line 9 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/533#-N0cB4t0DlOXWYObSQek:-N0ftIhK01W9UhUoo3YP:bmdmmcw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c7f1f459211c10a695f803cc4995d8ba9d3521a6/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/deploy/postgres/BUILD.bazel#L9)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

i think you can just call it `postgres`
</blockquote></details>

I'll use glob() and  name it postgres then.


<!-- Sent from Reviewable.io -->

2022-04-27 17:01 UTC, duliomatos1 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/533)* status: 4 of 11 files reviewed, 9 unresolved discussions (waiting on @duliomatos1, @matthewclegg, @SanjayVas, @stevenwarejones, and @uakyol)

___
*[`src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/AbstractPrivacyBudgetLedgerStoreTest.kt` line 1 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/533#-N0fpCAzAzJSXXioZUdd:-N0fx9Gg3cs-GfqRp91I:b1w03jk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c7f1f459211c10a695f803cc4995d8ba9d3521a6/src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/AbstractPrivacyBudgetLedgerStoreTest.kt#L1)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

this file and probably the InMemoryBackingStore should go in main/.../testing/ eg `src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/testing`
</blockquote></details>

These and `PostgresBackingStoreTest` as well? (under `src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/deploy/postgres/testing`)


<!-- Sent from Reviewable.io -->

2022-04-27 19:16 UTC, SanjayVas requested changes
> Reviewed 1 of 9 files at r5, 2 of 7 files at r7.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/533)* status: 7 of 11 files reviewed, 6 unresolved discussions (waiting on @duliomatos1, @matthewclegg, @SanjayVas, and @stevenwarejones)

___
*[`src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/AbstractPrivacyBudgetLedgerStoreTest.kt` line 22 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/533#-N0XAKDs6ygzJcYLGmo8:-N0gMOGD4RyiHMIcZqfr:b-npr1qb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/61414619088983badfefbeea0908f257c90dbe39/src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/AbstractPrivacyBudgetLedgerStoreTest.kt#L22)):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

I mean, in the same test we will need to instantiate two different transactions at the same time, each transaction will be using a separate backing store. When instantiating the second backing store, the test should not recreate the schema. I can be more explicit and separate the schema creation from the backing store creation, wdyt?
</blockquote></details>

Yeah, I basically want to separate the concepts of creating a backing store instance vs. creating the schema in the DB.

More clearly, the schema creation shouldn't be controllable by any individual test method. Your test lifecycle functions should ensure that the DB is set up and has the appropriate (empty) schema before the test method executes.
___
*[`src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/deploy/postgres/PostgresBackingStoreTest.kt` line 70 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/533#-N0cQn65B63GIT-pLewQ:-N0gM8N-7_dw6b5nKZGP:b5snehq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c7f1f459211c10a695f803cc4995d8ba9d3521a6/src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/deploy/postgres/PostgresBackingStoreTest.kt#L70)):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

Done. Included a comment but let me know if you think it's better to go on the route of creating many connections for the tests
</blockquote></details>

It's fine for testing. 

I originally was concerned with the possibility of a single connection being shared concurrently by multiple PostgresBackingStore instances, but I guess Bazel's implementation of test sharding uses a separate JVM instance per shard. It's not using e.g. JUnit's parallelization features to run test methods in parallel on the same JVM.


<!-- Sent from Reviewable.io -->

2022-04-27 19:52 UTC, stevenwarejones reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/533)* status: 7 of 11 files reviewed, 6 unresolved discussions (waiting on @duliomatos1, @matthewclegg, @SanjayVas, and @stevenwarejones)

___
*[`src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/AbstractPrivacyBudgetLedgerStoreTest.kt` line 1 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/533#-N0fpCAzAzJSXXioZUdd:-N0g_FMZ13Abm_0iEaRW:bt83mwx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c7f1f459211c10a695f803cc4995d8ba9d3521a6/src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/AbstractPrivacyBudgetLedgerStoreTest.kt#L1)):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

These and `PostgresBackingStoreTest` as well? (under `src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/deploy/postgres/testing`)
</blockquote></details>

resolved over chat


<!-- Sent from Reviewable.io -->

2022-04-28 01:47 UTC, stevenwarejones approved these changes
> Reviewed 5 of 8 files at r8, 1 of 2 files at r9, 1 of 1 files at r10, 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/533)* status: 12 of 13 files reviewed, 6 unresolved discussions (waiting on @duliomatos1, @matthewclegg, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/testing/InMemoryBackingStore.kt` line 14 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/533#-N0hq0Df00VngVg5ohG7:-N0hq0Df00VngVg5ohG8:b-bsidjd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6b87c49e313c0f0c4d268f92cb44eaad894d3b75/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/testing/InMemoryBackingStore.kt#L14)):*
> ```Kotlin
>  * the License.
>  */
> package org.wfanet.measurement.eventdataprovider.privacybudgetmanagement
> ```

`org.wfanet.measurement.eventdataprovider.privacybudgetmanagement.testing`



_Code quote:_
```Kotlin
rg.wfanet.measurement.eventdataprovider.privacybudgetmanagement
```


<!-- Sent from Reviewable.io -->

2022-04-28 02:40 UTC, duliomatos1 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/533)* status: 8 of 15 files reviewed, 6 unresolved discussions (waiting on @duliomatos1, @matthewclegg, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/deploy/postgres/BUILD.bazel` line 9 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/533#-N0cB4t0DlOXWYObSQek:-N0hjBxuEjZX-4pE1hIc:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c7f1f459211c10a695f803cc4995d8ba9d3521a6/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/deploy/postgres/BUILD.bazel#L9)):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

I'll use glob() and  name it postgres then.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/testing/InMemoryBackingStore.kt` line 14 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/533#-N0hq0Df00VngVg5ohG7:-N0i0iYcEJW516xlLxK8:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6b87c49e313c0f0c4d268f92cb44eaad894d3b75/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/testing/InMemoryBackingStore.kt#L14)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

`org.wfanet.measurement.eventdataprovider.privacybudgetmanagement.testing`
</blockquote></details>

Done.
___
*[`src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/AbstractPrivacyBudgetLedgerStoreTest.kt` line 22 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/533#-N0XAKDs6ygzJcYLGmo8:-N0hziJP1iCoZmvpK83u:b-f8hsl0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/61414619088983badfefbeea0908f257c90dbe39/src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/AbstractPrivacyBudgetLedgerStoreTest.kt#L22)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Yeah, I basically want to separate the concepts of creating a backing store instance vs. creating the schema in the DB.

More clearly, the schema creation shouldn't be controllable by any individual test method. Your test lifecycle functions should ensure that the DB is set up and has the appropriate (empty) schema before the test method executes.
</blockquote></details>

Done. Actually it looks better now by separating concerns and using test lifecycle properly, thanks for the suggestion.
___
*[`src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/deploy/postgres/PostgresBackingStoreTest.kt` line 70 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/533#-N0cQn65B63GIT-pLewQ:-N0i0pMS2CufLXoDxi93:b2oj6s3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c7f1f459211c10a695f803cc4995d8ba9d3521a6/src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/deploy/postgres/PostgresBackingStoreTest.kt#L70)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

It's fine for testing. 

I originally was concerned with the possibility of a single connection being shared concurrently by multiple PostgresBackingStore instances, but I guess Bazel's implementation of test sharding uses a separate JVM instance per shard. It's not using e.g. JUnit's parallelization features to run test methods in parallel on the same JVM.
</blockquote></details>

Done. Actually looks better by using a real `createConnection()`.


<!-- Sent from Reviewable.io -->

2022-04-28 19:54 UTC, SanjayVas approved these changes
> Reviewed 1 of 7 files at r7, 3 of 8 files at r8, 1 of 2 files at r9, 1 of 2 files at r11, 1 of 3 files at r12, 5 of 5 files at r13, 1 of 1 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/533)* status: all files reviewed, 4 unresolved discussions (waiting on @duliomatos1 and @matthewclegg)

___
*[`src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/deploy/postgres/PostgresBackingStoreTest.kt` line 53 at r14](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/533#-N0ligoQDW3FvV4eccW9:-N0ligoQDW3FvV4eccWA:b-7emf8t) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6896a09319740cc07cd76152adc532861b89c032/src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/deploy/postgres/PostgresBackingStoreTest.kt#L53)):*
> ```Kotlin
>   }
> 
>   private val createConnection = { embeddedPostgres.getDatabase(PG_USER_NAME, TEST_DB).connection }
> ```

nit: define this as a function instead, and then use a function reference (`::createConnection`) to pass it to the constructor.



_Code quote:_
```Kotlin
val
```


<!-- Sent from Reviewable.io -->

2022-04-28 20:05 UTC, duliomatos1 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/533)* status: 14 of 15 files reviewed, 2 unresolved discussions (waiting on @matthewclegg, @SanjayVas, and @uakyol)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PostgresBackingStore.kt` line 239 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/533#-N0CyFsoBoFemovFU3m2:-N0lli-A-SlQro-MDyTf:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5c1f192b9a078b3ceb24820e756bc3ef70894b37/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PostgresBackingStore.kt#L239)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

sounds good
</blockquote></details>

Done.
___
*[`src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/AbstractPrivacyBudgetLedgerStoreTest.kt` line 20 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/533#-N0CyKJD-0Im4oUSAeTq:-N0lkEnt-NAdaLJ9E6Jr:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8c04392bc79cdd1c388f3cf67251136440fcbf77/src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/AbstractPrivacyBudgetLedgerStoreTest.kt#L20)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

This is great thank you!
</blockquote></details>

Done.
___
*[`src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/deploy/postgres/PostgresBackingStoreTest.kt` line 53 at r14](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/533#-N0ligoQDW3FvV4eccW9:-N0lkGvI23ALaDLNhFhn:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6896a09319740cc07cd76152adc532861b89c032/src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/deploy/postgres/PostgresBackingStoreTest.kt#L53)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: define this as a function instead, and then use a function reference (`::createConnection`) to pass it to the constructor.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-04-28 20:09 UTC, duliomatos1 reviewed
> Dismissed @uakyol from 2 discussions.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/533)* status: 14 of 15 files reviewed, all discussions resolved (waiting on @matthewclegg and @SanjayVas)



<!-- Sent from Reviewable.io -->

2022-04-28 20:10 UTC, duliomatos1 reviewed
> Reviewed 1 of 1 files at r15.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/533)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @matthewclegg)



<!-- Sent from Reviewable.io -->

2022-04-28 20:12 UTC, duliomatos1 reviewed
> Reviewed 1 of 9 files at r5, 1 of 7 files at r7, 3 of 8 files at r8, 1 of 2 files at r9, 1 of 2 files at r11, 1 of 3 files at r12, 4 of 5 files at r13, 1 of 1 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/533)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @matthewclegg)



<!-- Sent from Reviewable.io -->

2022-04-28 20:12 UTC, merged