Update EDP simulator to charge Privacy Budget for Requisition
world-federation-of-advertisers/cross-media-measurement pull request #542
Opened 2022-04-26 21:03 UTC by uakyol

2022-04-28 17:47 UTC, SanjayVas requested changes
> Reviewed 17 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/542)* status: all files reviewed, 7 unresolved discussions (waiting on @uakyol)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyLandscape.kt` line 24 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/542#-N0lDdu92to9ByNDP9gA:-N0lDdu92to9ByNDP9gB:b1fl7rl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a765346144f426e053ee7a192e04abfff0d28bbb/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyLandscape.kt#L24)):*
> ```Kotlin
>   val genders = Gender.values().toSet()
>   // There are 300 Vid intervals in the range [0, 1)
>   val vids: List<Float> = (0..1).map { (Math.round((it / 300f) * 1000.0) / 1000.0).toFloat() }
> ```

I think if you keep all the operands as floats (e.g. 1000f), you might get float precision all the way through and not need to convert?



_Code quote:_
```Kotlin
toFloat()
```
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyLandscape.kt` line 24 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/542#-N0lDzkA25JJPnvvwV56:-N0lDzkA25JJPnvvwV57:b5ylz8y) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a765346144f426e053ee7a192e04abfff0d28bbb/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyLandscape.kt#L24)):*
> ```Kotlin
>   val genders = Gender.values().toSet()
>   // There are 300 Vid intervals in the range [0, 1)
>   val vids: List<Float> = (0..1).map { (Math.round((it / 300f) * 1000.0) / 1000.0).toFloat() }
> ```

Just double-checking what this is doing. IIUC, doesn't this result in a List containing `[0f, 0f]`?

0 / 300 = 0
round(1 / 300) = 0
___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/BUILD.bazel` line 93 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/542#-N0lF5ddB2Hz0vURnjTr:-N0lF5ddB2Hz0vURnjTs:b-mvp8we) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a765346144f426e053ee7a192e04abfff0d28bbb/src/main/kotlin/org/wfanet/measurement/integration/common/BUILD.bazel#L93)):*
> ```Starlark
>     deps = [
>         ":configs",
>                 "//src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/testing",
> ```

nit: weird formatting
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 282 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/542#-N0lFpID4qsI-u2G2v1a:-N0lFpID4qsI-u2G2v1b:bp18ovg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a765346144f426e053ee7a192e04abfff0d28bbb/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L282)):*
> ```Kotlin
>       refuseRequisition(
>         requisitionName,
>         Requisition.Refusal.Justification.SPECIFICATION_INVALID,
> ```

Wrong refusal info. `INSUFFICIENT_PRIVACY_BUDGET`



_Code quote:_
```Kotlin
        Requisition.Refusal.Justification.SPECIFICATION_INVALID,
        "Invalid requisitionSpec"
```
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulator.kt` line 467 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/542#-N0lGa1x-p3DseQ0esnu:-N0lGa1x-p3DseQ0esnv:biehvu3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a765346144f426e053ee7a192e04abfff0d28bbb/src/main/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulator.kt#L467)):*
> ```Kotlin
> 
>   private fun createFilterExpression(): String =
>     eventTemplateFilters.values.reduce { acc, string -> "$acc && $string" }
> ```

Why not just a simple string join?



_Code quote:_
```Kotlin
reduce
```
___
*[`src/main/proto/wfa/measurement/loadtest/config/BUILD.bazel` line 13 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/542#-N0lGtBO1H5s_7jKsPXc:-N0lGtBO1H5s_7jKsPXd:b-6nanq4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a765346144f426e053ee7a192e04abfff0d28bbb/src/main/proto/wfa/measurement/loadtest/config/BUILD.bazel#L13)):*
> ```Starlark
> proto_library(
>     name = "loadtest_event_proto",
>     srcs = glob(["*.proto"]),
> ```

proto_library rules should generally have a single source.



_Code quote:_
```Starlark
glob(["*.proto"])
```
___
*[`src/main/proto/wfa/measurement/loadtest/config/loadtest_event.proto` line 23 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/542#-N0lH3phEJtj4UR3tpis:-N0lH3phEJtj4UR3tpit:bdr27tc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a765346144f426e053ee7a192e04abfff0d28bbb/src/main/proto/wfa/measurement/loadtest/config/loadtest_event.proto#L23)):*
> ```protobuf
> 
> message LoadTestEvent {
>   // Wheter or not this event can be filtered by the privacy bucket filter.
> ```

Whether



_Code quote:_
```protobuf
Wheter or not
```


<!-- Sent from Reviewable.io -->

2022-04-28 23:41 UTC, uakyol reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/542)* status: 7 of 23 files reviewed, 6 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyLandscape.kt` line 24 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/542#-N0lDzkA25JJPnvvwV56:-N0m3EkW9Vxuq4tOdrqV:b5zx4zd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a765346144f426e053ee7a192e04abfff0d28bbb/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyLandscape.kt#L24)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Just double-checking what this is doing. IIUC, doesn't this result in a List containing `[0f, 0f]`?

0 / 300 = 0
round(1 / 300) = 0
</blockquote></details>

you are right. Thankfully, PrivacyBudgetManagerTest also caught it. changed it to this. Took me about 2 hours, kotlin has a weird rounding behaviour. Because of that, just multiplying each num by range did not work since it provided uneven ranges and this caused same bucket to be charged twice. I think this is much cleaner and it is correct wdyt?
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyLandscape.kt` line 24 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/542#-N0lDdu92to9ByNDP9gA:-N0m6f1p47HYz4d8DT_S:b3ykpyg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a765346144f426e053ee7a192e04abfff0d28bbb/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyLandscape.kt#L24)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I think if you keep all the operands as floats (e.g. 1000f), you might get float precision all the way through and not need to convert?
</blockquote></details>

thank you you are right. see below also
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 282 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/542#-N0lFpID4qsI-u2G2v1a:-N0lq_0082BQZ6b8Ecyr:b-1cyu7w) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a765346144f426e053ee7a192e04abfff0d28bbb/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L282)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Wrong refusal info. `INSUFFICIENT_PRIVACY_BUDGET`
</blockquote></details>

thank you
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulator.kt` line 467 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/542#-N0lGa1x-p3DseQ0esnu:-N0m8EYv3Lu2d29t7WGj:b-tn44u1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a765346144f426e053ee7a192e04abfff0d28bbb/src/main/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulator.kt#L467)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Why not just a simple string join?
</blockquote></details>

much better thank you
___
*[`src/main/proto/wfa/measurement/loadtest/config/BUILD.bazel` line 13 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/542#-N0lGtBO1H5s_7jKsPXc:-N0lr1iKDXSsqkBz1NM1:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a765346144f426e053ee7a192e04abfff0d28bbb/src/main/proto/wfa/measurement/loadtest/config/BUILD.bazel#L13)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

proto_library rules should generally have a single source.
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/loadtest/config/loadtest_event.proto` line 23 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/542#-N0lH3phEJtj4UR3tpis:-N0m74-_Eds_-EcSgkWS:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a765346144f426e053ee7a192e04abfff0d28bbb/src/main/proto/wfa/measurement/loadtest/config/loadtest_event.proto#L23)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Whether
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-04-29 18:12 UTC, SanjayVas requested changes
> Reviewed 1 of 1 files at r2, 16 of 16 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/542)* status: all files reviewed, 2 unresolved discussions (waiting on @stevenwarejones and @uakyol)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyLandscape.kt` line 19 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/542#-N0qVTO77TEeW9fT7XJw:-N0qVTO77TEeW9fT7XJx:b-7zt9m2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6b938e96539eb5322db66df2c82cc122ce6debe4/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyLandscape.kt#L19)):*
> ```Kotlin
> 
> object PrivacyLandscape {
>   const val PRIVACY_BUCKET_VID_SAMPLE_WIDTH = 0.0033f
> ```

Why not `1f / 300f` to get more precision?



_Code quote:_
```Kotlin
0.0033f
```
___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/BUILD.bazel` line 93 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/542#-N0lF5ddB2Hz0vURnjTr:-N0qVpci8LLPKOpoRvF4:b-fw12bo) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a765346144f426e053ee7a192e04abfff0d28bbb/src/main/kotlin/org/wfanet/measurement/integration/common/BUILD.bazel#L93)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: weird formatting
</blockquote></details>

Still off. Same-package deps should be sorted above other package deps. Did you run `buildifier`?



_Code quote:_
```Starlark
 ":in_process_kingdom",
```
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 282 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/542#-N0lFpID4qsI-u2G2v1a:-N0qVyhO8xtpORucHTay:br4olw4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a765346144f426e053ee7a192e04abfff0d28bbb/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L282)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

thank you
</blockquote></details>

Update the message too.


<!-- Sent from Reviewable.io -->

2022-04-29 19:10 UTC, uakyol reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/542)* status: 18 of 23 files reviewed, 2 unresolved discussions (waiting on @SanjayVas and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyLandscape.kt` line 19 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/542#-N0qVTO77TEeW9fT7XJw:-N0qg1n24tidqNiS675v:bige4np) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6b938e96539eb5322db66df2c82cc122ce6debe4/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyLandscape.kt#L19)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Why not `1f / 300f` to get more precision?
</blockquote></details>

sure. thanks
___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/BUILD.bazel` line 93 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/542#-N0lF5ddB2Hz0vURnjTr:-N0qdeQrCb0Yb1Y3tkSB:brw79ix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a765346144f426e053ee7a192e04abfff0d28bbb/src/main/kotlin/org/wfanet/measurement/integration/common/BUILD.bazel#L93)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Still off. Same-package deps should be sorted above other package deps. Did you run `buildifier`?
</blockquote></details>

no I run the linter in cider, but it seems like it passes the lint check in github. Anyway, I put it above manually and ran again, it sorted as you said.  
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 282 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/542#-N0lFpID4qsI-u2G2v1a:-N0qe0u98e-5YU6hvtRb:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a765346144f426e053ee7a192e04abfff0d28bbb/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L282)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Update the message too.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-04-29 21:37 UTC, SanjayVas requested changes
> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/542)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones and @uakyol)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyLandscape.kt` line 25 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/542#-N0r9Q_u7Dldc5EESlib:-N0r9Q_u7Dldc5EESlic:bgsl56v) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/89f0011720d3329b453fd4ebbeb3de03839504bc/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyLandscape.kt#L25)):*
> ```Kotlin
>   val genders = Gender.values().toSet()
> 
>   // There are 300 Vid intervals in the range [0, 1). The last interval has a little larger length -
> ```

Is this still accurate with the precision change?



_Code quote:_
```Kotlin
  // There are 300 Vid intervals in the range [0, 1). The last interval has a little larger length -
  // [0.986 1) all others have length 0.0033
```
___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/BUILD.bazel` line 93 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/542#-N0lF5ddB2Hz0vURnjTr:-N0rDjNjEombA1OG_XRj:bdm5eso) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a765346144f426e053ee7a192e04abfff0d28bbb/src/main/kotlin/org/wfanet/measurement/integration/common/BUILD.bazel#L93)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

no I run the linter in cider, but it seems like it passes the lint check in github. Anyway, I put it above manually and ran again, it sorted as you said.  
</blockquote></details>

I figured it out. Buildifier ignores order of deps when it's not a single list. The concatenation with `ALL_CMMS_SERVICES` is what's doing that in this case. I might try to clean this up later.


<!-- Sent from Reviewable.io -->

2022-05-02 01:33 UTC, uakyol reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/542)* status: 22 of 23 files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyLandscape.kt` line 25 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/542#-N0r9Q_u7Dldc5EESlib:-N11OYZ373qJ1J_mFu7h:be12iz8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/89f0011720d3329b453fd4ebbeb3de03839504bc/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyLandscape.kt#L25)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Is this still accurate with the precision change?
</blockquote></details>

yea you are right. 1/300 works better. Keeping 0.986 seems fine I think. 


<!-- Sent from Reviewable.io -->

2022-05-02 16:58 UTC, SanjayVas requested changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/542)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones and @uakyol)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyLandscape.kt` line 25 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/542#-N0r9Q_u7Dldc5EESlib:-N14fB6o52ulCCOe_gvf:be0u7px) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/89f0011720d3329b453fd4ebbeb3de03839504bc/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyLandscape.kt#L25)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

yea you are right. 1/300 works better. Keeping 0.986 seems fine I think. 
</blockquote></details>

I don't think`0.986` is accurate after the change though. Adding `1f / 300f` 299 times in Kotlin gives `0.99666584`. More concretely, I don't think the final bucket is actually meaningfully larger if using the more accurate width.

Note that due to how math with floats works, you get a more accurate answer by multiplying rather than adding: `1f / 300f * 299` gives `0.99666667`. Are you sure that you want to generate this as a constant list ahead of time rather than just having the number of intervals as an additional constant and having calling code just multiply out to get the appropriate interval?


<!-- Sent from Reviewable.io -->

2022-05-02 17:20 UTC, stevenwarejones requested changes
> Reviewed 5 of 17 files at r1, 1 of 1 files at r2, 11 of 16 files at r3, 3 of 5 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/542)* status: all files reviewed, 2 unresolved discussions (waiting on @uakyol)

___
*[`src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/InMemoryBackingStoreTest.kt` line 14 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/542#-N14m4S42tPHYg96FZE2:-N14m4S42tPHYg96FZE3:b-58nci9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/82232f26f8b52b26e24e0ed88aad535b064b4d21/src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/InMemoryBackingStoreTest.kt#L14)):*
> ```Kotlin
>  * the License.
>  */
> package org.wfanet.measurement.eventdataprovider.privacybudgetmanagement
> ```

I disagree with this change. Doesn't this belong in testing only? @sanjayvas 


<!-- Sent from Reviewable.io -->

2022-05-02 17:23 UTC, uakyol reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/542)* status: all files reviewed, 2 unresolved discussions (waiting on @SanjayVas and @uakyol)

___
*[`src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/InMemoryBackingStoreTest.kt` line 14 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/542#-N14m4S42tPHYg96FZE2:-N14moLXEAKVTjeOM4Vn:b-l98ew7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/82232f26f8b52b26e24e0ed88aad535b064b4d21/src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/InMemoryBackingStoreTest.kt#L14)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

I disagree with this change. Doesn't this belong in testing only? @sanjayvas 
</blockquote></details>

So  InMemoryBackingStore is a valid backing store that can be used in production. In fact, we are considering using this internally.  


<!-- Sent from Reviewable.io -->

2022-05-02 17:32 UTC, uakyol reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/542)* status: 22 of 23 files reviewed, 2 unresolved discussions (waiting on @SanjayVas and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyLandscape.kt` line 25 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/542#-N0r9Q_u7Dldc5EESlib:-N14o6mAAWyODvK7c8nk:b-5ese2v) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/89f0011720d3329b453fd4ebbeb3de03839504bc/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyLandscape.kt#L25)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I don't think`0.986` is accurate after the change though. Adding `1f / 300f` 299 times in Kotlin gives `0.99666584`. More concretely, I don't think the final bucket is actually meaningfully larger if using the more accurate width.

Note that due to how math with floats works, you get a more accurate answer by multiplying rather than adding: `1f / 300f * 299` gives `0.99666667`. Are you sure that you want to generate this as a constant list ahead of time rather than just having the number of intervals as an additional constant and having calling code just multiply out to get the appropriate interval?
</blockquote></details>

you are right about `0.99666584` . So sorry I didn't double check. In terms of multiplication vs constant generation, I would rather have constant generation just due to the fact that its set in stone in this file and no arithmetic operation can mess with the intervals. If you feel strongly, i can change this though.


<!-- Sent from Reviewable.io -->

2022-05-02 17:32 UTC, SanjayVas reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/542)* status: 22 of 23 files reviewed, 2 unresolved discussions (waiting on @SanjayVas and @stevenwarejones)

___
*[`src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/InMemoryBackingStoreTest.kt` line 14 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/542#-N14m4S42tPHYg96FZE2:-N14nwRyA6ZjHPkm7LuU:b-kiqn1z) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/82232f26f8b52b26e24e0ed88aad535b064b4d21/src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/InMemoryBackingStoreTest.kt#L14)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

So  InMemoryBackingStore is a valid backing store that can be used in production. In fact, we are considering using this internally.  
</blockquote></details>

Took a deeper look, the main concern I'd have is that `InMemoryBackingStore` appears to currently have its mutable `ledger` property publicly accessible. If that's needed for testing, it should only be in a testing subclass. Other than that, I believe `InMemoryBackingStore` need not be test-only (though it'll likely need some way to be persisted to be more broadly useful).

One case where I believe we're planning on using this in non-test code is for a tool to estimate budget given a set of queries.


<!-- Sent from Reviewable.io -->

2022-05-02 17:35 UTC, SanjayVas requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/542)* status: 22 of 23 files reviewed, 2 unresolved discussions (waiting on @SanjayVas, @stevenwarejones, and @uakyol)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyLandscape.kt` line 25 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/542#-N0r9Q_u7Dldc5EESlib:-N14pSh2-beUew8K8Zyz:b-vmf1w7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/89f0011720d3329b453fd4ebbeb3de03839504bc/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyLandscape.kt#L25)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

you are right about `0.99666584` . So sorry I didn't double check. In terms of multiplication vs constant generation, I would rather have constant generation just due to the fact that its set in stone in this file and no arithmetic operation can mess with the intervals. If you feel strongly, i can change this though.
</blockquote></details>

If you really want to do an up-front constant, then at least calculate these more accurately using multiplication rather than addition.


<!-- Sent from Reviewable.io -->

2022-05-02 18:05 UTC, uakyol reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/542)* status: 22 of 23 files reviewed, 2 unresolved discussions (waiting on @SanjayVas, @stevenwarejones, and @uakyol)

___
*[`src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/InMemoryBackingStoreTest.kt` line 14 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/542#-N14m4S42tPHYg96FZE2:-N14u_aRCwfvEw7lVYQW:b-9gtrac) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/82232f26f8b52b26e24e0ed88aad535b064b4d21/src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/InMemoryBackingStoreTest.kt#L14)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Took a deeper look, the main concern I'd have is that `InMemoryBackingStore` appears to currently have its mutable `ledger` property publicly accessible. If that's needed for testing, it should only be in a testing subclass. Other than that, I believe `InMemoryBackingStore` need not be test-only (though it'll likely need some way to be persisted to be more broadly useful).

One case where I believe we're planning on using this in non-test code is for a tool to estimate budget given a set of queries.
</blockquote></details>

I am only using that ledger property in EDPSimulatorTest here : https://github.com/world-federation-of-advertisers/cross-media-measurement/pull/542/files#diff-48c684b749f8f0485a883ac50766c28f65390efefb8eaed8cf72228ddd591906R350 . This is a nice to have. Maybe a good solution is to leave this in non-testing folder, with ledger property private, this can have additional features later. And add another simpler, TestInMemoryBackingStore in the testing dir without mergePreviousTransaction and undoPreviousTransaction functions, just for testing. what do you all think?


<!-- Sent from Reviewable.io -->

2022-05-02 18:41 UTC, stevenwarejones requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/542)* status: 22 of 23 files reviewed, 2 unresolved discussions (waiting on @SanjayVas, @stevenwarejones, and @uakyol)

___
*[`src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/InMemoryBackingStoreTest.kt` line 14 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/542#-N14m4S42tPHYg96FZE2:-N153qnjApx8v6yz81pY:bn81j4f) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/82232f26f8b52b26e24e0ed88aad535b064b4d21/src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/InMemoryBackingStoreTest.kt#L14)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

I am only using that ledger property in EDPSimulatorTest here : https://github.com/world-federation-of-advertisers/cross-media-measurement/pull/542/files#diff-48c684b749f8f0485a883ac50766c28f65390efefb8eaed8cf72228ddd591906R350 . This is a nice to have. Maybe a good solution is to leave this in non-testing folder, with ledger property private, this can have additional features later. And add another simpler, TestInMemoryBackingStore in the testing dir without mergePreviousTransaction and undoPreviousTransaction functions, just for testing. what do you all think?
</blockquote></details>

I'd prefer to keep the postgres backing store in the simulator and keep the in memory backing store test-only


<!-- Sent from Reviewable.io -->

2022-05-02 18:43 UTC, stevenwarejones requested changes
> Reviewed 1 of 17 files at r1, 1 of 5 files at r4, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/542)* status: all files reviewed, 3 unresolved discussions (waiting on @SanjayVas and @uakyol)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 301 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/542#-N15482J1xvakKQv48t_:-N15482J1xvakKQv48ta:bnus0o) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/38f84228735892da8d0195acb4d4e1c970e98a1d/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L301)):*
> ```Kotlin
> 
>     populateAnySketch(
>       requisitionSpec.eventGroupsList[0].value.filter,
> ```

can you make a TODO to populate the sketch based on all the event groups?


<!-- Sent from Reviewable.io -->

2022-05-02 18:45 UTC, SanjayVas reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/542)* status: all files reviewed, 3 unresolved discussions (waiting on @SanjayVas, @stevenwarejones, and @uakyol)

___
*[`src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/InMemoryBackingStoreTest.kt` line 14 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/542#-N14m4S42tPHYg96FZE2:-N153kGz9G82LiBjR45f:b-c9cp4g) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/82232f26f8b52b26e24e0ed88aad535b064b4d21/src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/InMemoryBackingStoreTest.kt#L14)):*
That's precisely what I'm suggesting: having `InMemoryBackingStore` be in a regular package with private `ledger`, and having a `TestInMemoryBackingStore` that extends from it expose the ledger for tests.

> I'd prefer to keep the postgres backing store in the simulator and keep the in memory backing store test-only

As I mentioned, we are strongly considering using the in-memory version in production:
1. For a CLI tool for privacy budget estimation.
2. In Google's requisition fulfiller for the ComScore PoC, with additional features for serialization. (We believe we can run this with a singleton task for the PoC).


<!-- Sent from Reviewable.io -->

2022-05-02 18:50 UTC, uakyol reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/542)* status: 22 of 23 files reviewed, 3 unresolved discussions (waiting on @SanjayVas and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 301 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/542#-N15482J1xvakKQv48t_:-N155gm02ZCdzu9Pye40:bf72bc8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/38f84228735892da8d0195acb4d4e1c970e98a1d/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L301)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

can you make a TODO to populate the sketch based on all the event groups?
</blockquote></details>

ah sure, thanks.
___
*[`src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/InMemoryBackingStoreTest.kt` line 14 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/542#-N14m4S42tPHYg96FZE2:-N154tIHCgxLsPdsTDdR:b-7i9282) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/82232f26f8b52b26e24e0ed88aad535b064b4d21/src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/InMemoryBackingStoreTest.kt#L14)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

That's precisely what I'm suggesting: having `InMemoryBackingStore` be in a regular package with private `ledger`, and having a `TestInMemoryBackingStore` that extends from it expose the ledger for tests.

> I'd prefer to keep the postgres backing store in the simulator and keep the in memory backing store test-only

As I mentioned, we are strongly considering using the in-memory version in production:
1. For a CLI tool for privacy budget estimation.
2. In Google's requisition fulfiller for the ComScore PoC, with additional features for serialization. (We believe we can run this with a singleton task for the PoC).
</blockquote></details>

@stevenwarejones 
  
 We can put the Postgres backing store in the simulator however, since we wont have access to its internal state EDPSimulatorTest wouldn't properly test if the exact buckets needed to be charged are charged correctly.


<!-- Sent from Reviewable.io -->

2022-05-02 18:51 UTC, uakyol reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/542)* status: 22 of 23 files reviewed, 3 unresolved discussions (waiting on @SanjayVas and @stevenwarejones)

___
*[`src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/InMemoryBackingStoreTest.kt` line 14 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/542#-N14m4S42tPHYg96FZE2:-N1568kT9pYzB2amwnOR:b-8s55ks) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/82232f26f8b52b26e24e0ed88aad535b064b4d21/src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/InMemoryBackingStoreTest.kt#L14)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

@stevenwarejones 
  
 We can put the Postgres backing store in the simulator however, since we wont have access to its internal state EDPSimulatorTest wouldn't properly test if the exact buckets needed to be charged are charged correctly.
</blockquote></details>

rather, we would need to charge the whole PBM again and see if it fails for the buckets that are full.


<!-- Sent from Reviewable.io -->

2022-05-02 19:01 UTC, SanjayVas reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/542)* status: 22 of 23 files reviewed, 3 unresolved discussions (waiting on @SanjayVas and @stevenwarejones)

___
*[`src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/InMemoryBackingStoreTest.kt` line 14 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/542#-N14m4S42tPHYg96FZE2:-N157DOv7x2Dv-7pFAo1:bsgpups) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/82232f26f8b52b26e24e0ed88aad535b064b4d21/src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/InMemoryBackingStoreTest.kt#L14)):*
> I'd prefer to keep the postgres backing store in the simulator and keep the in memory backing store test-only

I realized I may have misunderstood the intent of this statement. The simulator is a testing use case. It's listed as a `testonly` library. Switching the simulator to use the Postgres implementation is an entirely separate point.

The simulators aren't really designed to have any state that persists across runs. We can consider changing that, but it should be a separate discussion outside of this PR.


<!-- Sent from Reviewable.io -->

2022-05-02 20:18 UTC, stevenwarejones requested changes
> Reviewed 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/542)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @SanjayVas and @uakyol)

___
*[`src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/InMemoryBackingStoreTest.kt` line 14 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/542#-N14m4S42tPHYg96FZE2:-N15PoMV0HyfWCZPYqIY:br248vs) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/82232f26f8b52b26e24e0ed88aad535b064b4d21/src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/InMemoryBackingStoreTest.kt#L14)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> I'd prefer to keep the postgres backing store in the simulator and keep the in memory backing store test-only

I realized I may have misunderstood the intent of this statement. The simulator is a testing use case. It's listed as a `testonly` library. Switching the simulator to use the Postgres implementation is an entirely separate point.

The simulators aren't really designed to have any state that persists across runs. We can consider changing that, but it should be a separate discussion outside of this PR.
</blockquote></details>

I think the main point I want to make is that no one should actually deploy this with an inmemorybacking store, right? If so, then it should be a testing only package. I think if the simulator is marked as testonly, then, it too, could use the in memory back store or the post gres one.


<!-- Sent from Reviewable.io -->

2022-05-02 20:55 UTC, uakyol reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/542)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @SanjayVas and @stevenwarejones)

___
*[`src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/InMemoryBackingStoreTest.kt` line 14 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/542#-N14m4S42tPHYg96FZE2:-N15YAQPDJTBSoxTSZJF:b-ur3wu2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/82232f26f8b52b26e24e0ed88aad535b064b4d21/src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/InMemoryBackingStoreTest.kt#L14)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

I think the main point I want to make is that no one should actually deploy this with an inmemorybacking store, right? If so, then it should be a testing only package. I think if the simulator is marked as testonly, then, it too, could use the in memory back store or the post gres one.
</blockquote></details>

I am not sure about that Steven, people can deploy it why not? For example we do want to deploy it using this InMemory store. Anther reason this is marked non test is that it is used in the KIND Correctness test https://github.com/world-federation-of-advertisers/cross-media-measurement/pull/542/files#diff-aa5148637fca2c1325654d2248ac3aad7906355f77f8f1d2b09e04c7223d2b62R56  . If we mark it as test only, we need to use the postgres implementation in KIND which I don't think we want to do. 


<!-- Sent from Reviewable.io -->

2022-05-02 21:04 UTC, SanjayVas approved these changes
> Reviewed 1 of 1 files at r7, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/542)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[`src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/InMemoryBackingStoreTest.kt` line 14 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/542#-N14m4S42tPHYg96FZE2:-N15_Bb90J8tX_hFghZ5:bpvyfv0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/82232f26f8b52b26e24e0ed88aad535b064b4d21/src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/InMemoryBackingStoreTest.kt#L14)):*
> I think the main point I want to make is that no one should actually deploy this with an inmemorybacking store, right? 

Incorrect. It's totally valid to use in production, and in fact as I mentioned before we're strongly considering doing so at Google (with a serializer) at least for the ComScore PoC if not going forward. We're also planning on using it for the CLI tool, which is again a non-testing use case.


<!-- Sent from Reviewable.io -->

2022-05-02 21:20 UTC, stevenwarejones requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/542)* status: all files reviewed, 1 unresolved discussion (waiting on @uakyol)

___
*[`src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/InMemoryBackingStoreTest.kt` line 14 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/542#-N14m4S42tPHYg96FZE2:-N15d64A9NBTlUQuRgLd:b-c8ilvy) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/82232f26f8b52b26e24e0ed88aad535b064b4d21/src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/InMemoryBackingStoreTest.kt#L14)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> I think the main point I want to make is that no one should actually deploy this with an inmemorybacking store, right? 

Incorrect. It's totally valid to use in production, and in fact as I mentioned before we're strongly considering doing so at Google (with a serializer) at least for the ComScore PoC if not going forward. We're also planning on using it for the CLI tool, which is again a non-testing use case.
</blockquote></details>

An in-memory store is not persistent. How can you use a non-persistent store in production?


<!-- Sent from Reviewable.io -->

2022-05-02 21:38 UTC, uakyol reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/542)* status: 22 of 23 files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @stevenwarejones)

___
*[`src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/InMemoryBackingStoreTest.kt` line 14 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/542#-N14m4S42tPHYg96FZE2:-N15hHCICBq40S7pQAzo:bglduwh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/82232f26f8b52b26e24e0ed88aad535b064b4d21/src/test/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/InMemoryBackingStoreTest.kt#L14)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

An in-memory store is not persistent. How can you use a non-persistent store in production?
</blockquote></details>

Updated based on slack conversation.


<!-- Sent from Reviewable.io -->

2022-05-02 21:47 UTC, stevenwarejones approved these changes
> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/542)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)



<!-- Sent from Reviewable.io -->

2022-05-02 21:51 UTC, merged