Make Privacy Budget Manager Immutable
world-federation-of-advertisers/cross-media-measurement pull request #562
Opened 2022-05-12 21:54 UTC by uakyol

2022-05-13 16:54 UTC, stevenwarejones requested changes
> Reviewed 3 of 19 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/562)* status: 3 of 19 files reviewed, 8 unresolved discussions (waiting on @SanjayVas and @uakyol)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetLedger.kt` line 79 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/562#-N1yJ1Ww2Uj1tGTq2F71:-N1yJ1Ww2Uj1tGTq2F72:b-b33g20) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/37ec2708077ad0088a8e2b2c583e0f1debf206fc/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetLedger.kt#L79)):*
> ```Kotlin
>     }
> 
>     // Then check if charing the buckets would exceed privacy budget
> ```

charing?
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetLedgerBackingStore.kt` line 72 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/562#-N1yJJftARoOgBR3CBmu:-N1yJJftARoOgBR3CBmv:b-jqk2yq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/37ec2708077ad0088a8e2b2c583e0f1debf206fc/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetLedgerBackingStore.kt#L72)):*
> ```Kotlin
>   ): List<PrivacyBudgetLedgerEntry>
> 
>   /** Adds a new row to the PrivacyBudgetLedger specifying a charge to a privacy budget. */
> ```

this comment needs updating, right?
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetLedgerBackingStore.kt` line 82 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/562#-N1yJ9ozBdipU84Ta2hn:-N1yJ9ozBdipU84Ta2ho:b4y1wv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/37ec2708077ad0088a8e2b2c583e0f1debf206fc/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetLedgerBackingStore.kt#L82)):*
> ```Kotlin
>   fun shouldProcess(referenceKey: String, isPositive: Boolean): Boolean
> 
>   // TODO(@uakyol) : expose reference entries for replayability pourpouses.
> ```

nit: purposes
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetManager.kt` line 49 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/562#-N1yJ_0U2srPFTjLFAmC:-N1yJ_0U2srPFTjLFAmD:b-vq5ciz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/37ec2708077ad0088a8e2b2c583e0f1debf206fc/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetManager.kt#L49)):*
> ```Kotlin
>   val ledger = PrivacyBudgetLedger(backingStore, maximumPrivacyBudget, maximumTotalDelta)
> 
>   private fun getPrivacyQuery(
> ```

needs kdoc
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetManager.kt` line 107 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/562#-N1yJhi_6VR92P9vil9W:-N1yJhi_6VR92P9vil9X:b5qro) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/37ec2708077ad0088a8e2b2c583e0f1debf206fc/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetManager.kt#L107)):*
> ```Kotlin
>   }
> 
>   // TODO(@uakyol) : make this function public for then poupouse of replays.
> ```

nit: purpose
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetManager.kt` line 141 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/562#-N1yJpI78JB4Y1kbxN_D:-N1yJpI78JB4Y1kbxN_E:bbu16s8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/37ec2708077ad0088a8e2b2c583e0f1debf206fc/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetManager.kt#L141)):*
> ```Kotlin
> }
> 
> // TODO(@uakyol): Update time conversion after getting alignment on civil calendar days.
> ```

i'm not sure I understand the TODO here
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/deploy/postgres/PostgresBackingStore.kt` line 207 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/562#-N1yKf6G7-11vPQytbfa:-N1yKf6H-fczd4VxJN2Y:b-r1epm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/37ec2708077ad0088a8e2b2c583e0f1debf206fc/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/deploy/postgres/PostgresBackingStore.kt#L207)):*
> ```Kotlin
>       statement.setFloat(6, privacyCharge.delta)
>       statement.setFloat(7, privacyCharge.epsilon)
>       statement.setInt(8, 1) // RepetitionCount
> ```

if RepititionCount is always 1, why aren't we just setting it directly in the sql
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/deploy/postgres/PostgresBackingStore.kt` line 208 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/562#-N1yKEBcB5Tg4pT1HBoK:-N1yKEBcB5Tg4pT1HBoL:ble74c2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/37ec2708077ad0088a8e2b2c583e0f1debf206fc/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/deploy/postgres/PostgresBackingStore.kt#L208)):*
> ```Kotlin
>       statement.setFloat(7, privacyCharge.epsilon)
>       statement.setInt(8, 1) // RepetitionCount
>       statement.setInt(9, if (positiveCharge) 1 else -1) // RepetitionCount
> ```

`// RepititionCount` comment is incorrect
I'm also missing where this fills into the statement.


<!-- Sent from Reviewable.io -->

2022-05-16 19:19 UTC, uakyol reviewed
@stevenwarejones something weird is going on with Reviewable with this PR. None of your comments appear here but they appear in github ui. I copied your comments from there and answered them. Hope this works.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/562#-:-N2DFHXH37otJGYC0fx0:b8qxw0r)* status: 0 of 19 files reviewed, 8 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetLedger.kt` line 79 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/562#-N2DFiAP9RA--TOksaLa:-N2DFiAP9RA--TOksaLb:b-bugz1o) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/37ec2708077ad0088a8e2b2c583e0f1debf206fc/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetLedger.kt#L79)):*
> ```Kotlin
>     }
> 
>     // Then check if charing the buckets would exceed privacy budget
> ```

@stevenwarejones "charing?"

ugur :  done
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetLedgerBackingStore.kt` line 72 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/562#-N2DFsQt4REQXG6BgMgG:-N2DFsQt4REQXG6BgMgH:b-u72u99) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/37ec2708077ad0088a8e2b2c583e0f1debf206fc/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetLedgerBackingStore.kt#L72)):*
> ```Kotlin
>   ): List<PrivacyBudgetLedgerEntry>
> 
>   /** Adds a new row to the PrivacyBudgetLedger specifying a charge to a privacy budget. */
> ```

@stevenwarejones : "this comment needs updating, right?"

Ugur :  yes, thank you. Updated
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetLedgerBackingStore.kt` line 82 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/562#-N2DGH4PCSgvTG1W3yBo:-N2DGH4PCSgvTG1W3yBp:b-d66icu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/37ec2708077ad0088a8e2b2c583e0f1debf206fc/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetLedgerBackingStore.kt#L82)):*
> ```Kotlin
>   fun shouldProcess(referenceKey: String, isPositive: Boolean): Boolean
> 
>   // TODO(@uakyol) : expose reference entries for replayability pourpouses.
> ```

@stevenwarejones : "nit: purposes"

ugur : thanks
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetManager.kt` line 49 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/562#-N2DI9RI0tRFNYy5nxDi:-N2DI9RI0tRFNYy5nxDj:b-n865gm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/37ec2708077ad0088a8e2b2c583e0f1debf206fc/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetManager.kt#L49)):*
> ```Kotlin
>   val ledger = PrivacyBudgetLedger(backingStore, maximumPrivacyBudget, maximumTotalDelta)
> 
>   private fun getPrivacyQuery(
> ```

@stevenwarejones  : "needs kdoc"

ugur: thanks, added.



_Code quote:_
```Kotlin
getPrivacyQuery
```
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetManager.kt` line 107 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/562#-N2DHrcE1UcJ4H_puduz:-N2DHrcE1UcJ4H_pudv-:bpzsvrp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/37ec2708077ad0088a8e2b2c583e0f1debf206fc/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetManager.kt#L107)):*
> ```Kotlin
>   }
> 
>   // TODO(@uakyol) : make this function public for then poupouse of replays.
> ```

@stevenwarejones  : "nit: purpose"

ugur : my purpose is to spell this word correctly next time  :laughing: 



_Code quote:_
```Kotlin
poupouse
```
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetManager.kt` line 141 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/562#-N2DGVbDAm6Mr-tkRek3:-N2DGVbDAm6Mr-tkRek4:beeu04c) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/37ec2708077ad0088a8e2b2c583e0f1debf206fc/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetManager.kt#L141)):*
> ```Kotlin
> }
> 
> // TODO(@uakyol): Update time conversion after getting alignment on civil calendar days.
> ```

@stevenwarejones : "i'm not sure I understand the TODO here"

This comment was from before. I just moved the code from another file. Basically, this refers to times expressed as timestamps in the requisition proto but the PBM needs dates, so timezones com into play. I intend to talk about this in a halo meeting soon



_Code quote:_
```Kotlin
time
```
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/deploy/postgres/PostgresBackingStore.kt` line 207 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/562#-N2DGvDYEDOc11sPWvTl:-N2DGvDYEDOc11sPWvTm:b2y6t9e) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/37ec2708077ad0088a8e2b2c583e0f1debf206fc/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/deploy/postgres/PostgresBackingStore.kt#L207)):*
> ```Kotlin
>       statement.setFloat(6, privacyCharge.delta)
>       statement.setFloat(7, privacyCharge.epsilon)
>       statement.setInt(8, 1) // RepetitionCount
> ```

@stevenwarejones : "if RepititionCount is always 1, why aren't we just setting it directly in the sql"

ugur: you are right. changed it.
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/deploy/postgres/PostgresBackingStore.kt` line 208 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/562#-N2DHE1NBql7n73vj-Fq:-N2DHE1NBql7n73vj-Fr:b-j1b2qy) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/37ec2708077ad0088a8e2b2c583e0f1debf206fc/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/deploy/postgres/PostgresBackingStore.kt#L208)):*
> ```Kotlin
>       statement.setFloat(7, privacyCharge.epsilon)
>       statement.setInt(8, 1) // RepetitionCount
>       statement.setInt(9, if (positiveCharge) 1 else -1) // RepetitionCount
> ```

@stevenwarejones : "

// RepititionCount comment is incorrect
I'm also missing where this fills into the statement.
"

ugur: this is for the second part of the sql statement : "DO
         UPDATE SET RepetitionCount = ? + LedgerEntries.RepetitionCount;" 

So when the same bucket is found, we don not insert a duplicate but increase the RepetitionCount. I updated the comment with 'update repetition count' . 


<!-- Sent from Reviewable.io -->

2022-05-16 20:41 UTC, SanjayVas requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/562)* status: 0 of 19 files reviewed, 11 unresolved discussions (waiting on @SanjayVas and @uakyol)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/InMemoryBackingStore.kt` line 36 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/562#-N2DZf6w5PJTqikokKxo:-N2DZf6w5PJTqikokKxp:bws05hk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2de3ae8adfdec51cfd60d309db630b91567f49cd/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/InMemoryBackingStore.kt#L36)):*
> ```Kotlin
>  */
> class InMemoryBackingStore : PrivacyBudgetLedgerBackingStore {
>   val balanceLedger:
> ```

I thought we agreed to have this property only accessible in a `testing` subclass?
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/InMemoryBackingStore.kt` line 62 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/562#-N2D_4_w9lHuR1qy-S_q:-N2D_4_w9lHuR1qy-S_r:b-vh7lcr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2de3ae8adfdec51cfd60d309db630b91567f49cd/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/InMemoryBackingStore.kt#L62)):*
> ```Kotlin
>   // Adds a new row to the ledger referencing an element that caused charges to the store this key
>   // is usually the requisitionId.
>   private fun addReferenceEntry(referenceKey: String, isPositive: Boolean) {
> ```

nit: I thought after the terminology discussion that you were going to use "refund" rather than "positive"?

Financial systems similarly use other terms than positive/negative to avoid confusion.



_Code quote:_
```Kotlin
isPositive
```
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetLedgerBackingStore.kt` line 31 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/562#-N2DaDJn8zAyeNRU8rKJ:-N2DaDJn8zAyeNRU8rKK:b-lhfpk9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2de3ae8adfdec51cfd60d309db630b91567f49cd/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetLedgerBackingStore.kt#L31)):*
> ```Kotlin
> )
> 
> data class PrivacyBudgetReferenceEntry(
> ```

I'm slightly confused on the naming. Isn't this (the immutable thing) the ledger entry, and the other one not the ledger entry since it has the repetition count? (I assume the repetition count is mutable).



_Code quote:_
```Kotlin
PrivacyBudgetReferenceEntry
```


<!-- Sent from Reviewable.io -->

2022-05-16 22:37 UTC, uakyol reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/562)* status: 0 of 20 files reviewed, 11 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/InMemoryBackingStore.kt` line 36 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/562#-N2DZf6w5PJTqikokKxo:-N2DvKRY4aRIpMAgDXC9:b-d3dy03) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2de3ae8adfdec51cfd60d309db630b91567f49cd/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/InMemoryBackingStore.kt#L36)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I thought we agreed to have this property only accessible in a `testing` subclass?
</blockquote></details>

You are so right! I am sorry, yes this slipped through apparently in that big PR. Thanks for noticing, fixed.
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/InMemoryBackingStore.kt` line 62 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/562#-N2D_4_w9lHuR1qy-S_q:-N2DtBeW--1SHOmLOfBs:b-4t2iep) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2de3ae8adfdec51cfd60d309db630b91567f49cd/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/InMemoryBackingStore.kt#L62)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: I thought after the terminology discussion that you were going to use "refund" rather than "positive"?

Financial systems similarly use other terms than positive/negative to avoid confusion.
</blockquote></details>

yeah, you are right, thanks for reminding. changed to isRefund and flipped the bit logic throughout 
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetLedgerBackingStore.kt` line 31 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/562#-N2DaDJn8zAyeNRU8rKJ:-N2Ddz9RAm23GOqbJKsH:bkjygqt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2de3ae8adfdec51cfd60d309db630b91567f49cd/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetLedgerBackingStore.kt#L31)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I'm slightly confused on the naming. Isn't this (the immutable thing) the ledger entry, and the other one not the ledger entry since it has the repetition count? (I assume the repetition count is mutable).
</blockquote></details>

Yeah, I was confused too and this is the best I came up with. This: "PrivacyBudgetReferenceEntry" basically the thing that represents the measurement and requisition specs that created multiple charges. The ledger entries are individual charges to each bucket, hence they are immutable. I know this kind of goes against they being the "ledger" entries. Maybe a better way to name this is to call the individual aggregations on buckets (the ones with the repetition count) "PrivacyBudgetBalanceEntries" and rename the  PrivacyBudgetReferenceEntry ->  PrivacyBudgetLedgerEntry . This would be confusing too though, because we would be mainly operating on PrivacyBudgetBalanceEntries , the PrivacyBudgetLedgerEntries would only be there for replays etc ... wdyt?


<!-- Sent from Reviewable.io -->

2022-05-16 22:38 UTC, uakyol reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/562)* status: 0 of 20 files reviewed, 11 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetLedgerBackingStore.kt` line 31 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/562#-N2DaDJn8zAyeNRU8rKJ:-N2E0RjKA2m0QJigkvQU:bvglayx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2de3ae8adfdec51cfd60d309db630b91567f49cd/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetLedgerBackingStore.kt#L31)):*
> The ledger entries are individual charges to each bucket, hence they are immutable
sorry I meant hence they are mutable (because of the repetition count)


<!-- Sent from Reviewable.io -->

2022-05-17 17:30 UTC, SanjayVas requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/562)* status: 0 of 20 files reviewed, 9 unresolved discussions (waiting on @SanjayVas and @uakyol)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetLedgerBackingStore.kt` line 31 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/562#-N2DaDJn8zAyeNRU8rKJ:-N2I161b91tNxZNFXFtV:bzb1ite) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2de3ae8adfdec51cfd60d309db630b91567f49cd/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetLedgerBackingStore.kt#L31)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

> The ledger entries are individual charges to each bucket, hence they are immutable
sorry I meant hence they are mutable (because of the repetition count)
</blockquote></details>

There are two things to represent: the current balance and the ledger. The latter only exists for replays, and is a list of timestamped transactions. Everything else is representing the current balance for each "account" (bucket group?). The main interesting point in this case is that a single ledger entry applies to multiple "accounts".


<!-- Sent from Reviewable.io -->

2022-05-18 17:11 UTC, SanjayVas requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/562)* status: 0 of 20 files reviewed, 9 unresolved discussions (waiting on @SanjayVas and @uakyol)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/InMemoryBackingStore.kt` line 36 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/562#-N2N8DJa1qyryzn8th9h:-N2N8DJa1qyryzn8th9i:biqyp0f) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dc6309d4459ce8bb56c16bacfae8f269ecdd2b8d/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/InMemoryBackingStore.kt#L36)):*
> ```Kotlin
>  */
> open class InMemoryBackingStore : PrivacyBudgetLedgerBackingStore {
>   protected val balanceLedger:
> ```

Still confused at this. The ledger (list of transactions that affect balance) is not the thing that holds balances. There's only one ledger, and there's another structure that holds current balances which is not a ledger.



_Code quote:_
```Kotlin
balanceLedger
```


<!-- Sent from Reviewable.io -->

2022-05-18 18:48 UTC, uakyol reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/562)* status: 0 of 20 files reviewed, 9 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/InMemoryBackingStore.kt` line 36 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/562#-N2N8DJa1qyryzn8th9h:-N2NUnVX-_bWVk5BDni1:b-ovkrtm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dc6309d4459ce8bb56c16bacfae8f269ecdd2b8d/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/InMemoryBackingStore.kt#L36)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Still confused at this. The ledger (list of transactions that affect balance) is not the thing that holds balances. There's only one ledger, and there's another structure that holds current balances which is not a ledger.
</blockquote></details>

right, what do you think is a good name? How about 'balances'?


<!-- Sent from Reviewable.io -->

2022-05-18 21:25 UTC, SanjayVas requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/562)* status: 0 of 20 files reviewed, 9 unresolved discussions (waiting on @SanjayVas and @uakyol)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/InMemoryBackingStore.kt` line 36 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/562#-N2N8DJa1qyryzn8th9h:-N2O2zMvB7T9DVpeBgvl:b32w49) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dc6309d4459ce8bb56c16bacfae8f269ecdd2b8d/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/InMemoryBackingStore.kt#L36)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

right, what do you think is a good name? How about 'balances'?
</blockquote></details>

SG


<!-- Sent from Reviewable.io -->

2022-05-19 03:36 UTC, uakyol reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/562)* status: 0 of 20 files reviewed, 9 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/InMemoryBackingStore.kt` line 36 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/562#-N2N8DJa1qyryzn8th9h:-N2PNup94NiKSZp0OTsA:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dc6309d4459ce8bb56c16bacfae8f269ecdd2b8d/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/InMemoryBackingStore.kt#L36)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

SG
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-05-19 21:36 UTC, SanjayVas requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/562)* status: 0 of 20 files reviewed, 14 unresolved discussions (waiting on @SanjayVas and @uakyol)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/562#-N2TBzYn9ftp-joa3gYb:-N2TBzYn9ftp-joa3gYc:b7d8m29) (no related file):*
Added more comments re: naming and documentation. Sorry to push so much on this, but I feel like getting all the concepts nailed down and cleaned up first is important.

___
___
*[`src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql` line 24 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/562#-N2TAKqH46PVNJ6T5XUL:-N2TAKqH46PVNJ6T5XUM:b9bhds6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dd789d8f142e3dd8b77dad20f8c0067cc98f460c/src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql#L24)):*
> ```TSQL
> CREATE SEQUENCE LedgerEntriesTransactionIdSeq AS bigint START WITH 100;
> 
> CREATE TABLE LedgerEntries (
> ```

Rename this since it's not a table of ledger entries



_Code quote:_
```TSQL
LedgerEntries
```
___
*[`src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql` line 46 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/562#-N2TCySx6_T_3dkDeDmJ:-N2TCySx6_T_3dkDeDmK:b-cygrz1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dd789d8f142e3dd8b77dad20f8c0067cc98f460c/src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql#L46)):*
> ```TSQL
>   ON LedgerEntries
>   (MeasurementConsumerId, Date, AgeGroup, Gender, VidStart, Delta, Epsilon);
> ```

Shouldn't there be something that links balances w/ledger entries? e.g. to answer the query "Tell me all the ledger entries that affected this balance"?

Not a strict requirement, but you usually want to encode all the relationships in a relational DB with foreign keys.
___
*[`src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql` line 47 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/562#-N2TAOIV1oc7X2t9TGXM:-N2TAOIV1oc7X2t9TGXN:b-l0tlt0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dd789d8f142e3dd8b77dad20f8c0067cc98f460c/src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql#L47)):*
> ```TSQL
>   (MeasurementConsumerId, Date, AgeGroup, Gender, VidStart, Delta, Epsilon);
> 
> CREATE TABLE ReferenceEntries (
> ```

Rename this to be `LedgerEntries`



_Code quote:_
```TSQL
ReferenceEntries
```
___
*[`src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql` line 47 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/562#-N2TDUVf-pIM9dVVaVwR:-N2TDUVf-pIM9dVVaVwS:b-mc1vtt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dd789d8f142e3dd8b77dad20f8c0067cc98f460c/src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql#L47)):*
> ```TSQL
>   (MeasurementConsumerId, Date, AgeGroup, Gender, VidStart, Delta, Epsilon);
> 
> CREATE TABLE ReferenceEntries (
> ```

Also add MeasurementConsumerId to this table. Whatever we'd use for the reference ID (requisition ID or measurement ID) is only guaranteed by the API to be unique for a given MC, not globally unique.
___
*[`src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql` line 48 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/562#-N2TAbSc7e75S2BkNLON:-N2TAbSc7e75S2BkNLOO:b-wj72qc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dd789d8f142e3dd8b77dad20f8c0067cc98f460c/src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql#L48)):*
> ```TSQL
> 
> CREATE TABLE ReferenceEntries (
>     -- Reference to the element that caused charges.
> ```

Something like "ID from an external system that uniquely identifies the source all charges in a transaction for a given MeasurementConsumer." 



_Code quote:_
```TSQL
Reference to the element that caused charges.
```
___
*[`src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql` line 49 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/562#-N2TAaEd9M7AAjkngB4N:-N2TAaEd9M7AAjkngB4O:b7wvsrk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dd789d8f142e3dd8b77dad20f8c0067cc98f460c/src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql#L49)):*
> ```TSQL
> CREATE TABLE ReferenceEntries (
>     -- Reference to the element that caused charges.
>     ReferenceKey text NOT NULL,
> ```

nit: `referenceId` to match how we refer to the same concept elsewhere.



_Code quote:_
```TSQL
ReferenceKey
```


<!-- Sent from Reviewable.io -->

2022-05-19 21:40 UTC, SanjayVas requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/562)* status: 0 of 20 files reviewed, 15 unresolved discussions (waiting on @SanjayVas and @uakyol)

___
*[`src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql` line 23 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/562#-N2TFP327Mj6W3Wk7Dix:-N2TFP327Mj6W3Wk7Diy:b-9pof7i) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dd789d8f142e3dd8b77dad20f8c0067cc98f460c/src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql#L23)):*
> ```TSQL
> -- The special value of 0 is reserved for merged transactions.
> CREATE SEQUENCE LedgerEntriesTransactionIdSeq AS bigint START WITH 100;
> ```

Where are the primary keys for these tables defined? Usually you want some PK that's internal to your system.


<!-- Sent from Reviewable.io -->

2022-05-23 20:55 UTC, uakyol reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/562)* status: 0 of 20 files reviewed, 14 unresolved discussions (waiting on @SanjayVas)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/562#-N2TBzYn9ftp-joa3gYb:-N2mPlfN5lcmSGGoMeI0:bw30nre) (no related file):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Added more comments re: naming and documentation. Sorry to push so much on this, but I feel like getting all the concepts nailed down and cleaned up first is important.
</blockquote></details>

No, thanks a lot for your help. These are important, appreciate it.

___
___
*[`src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql` line 23 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/562#-N2TFP327Mj6W3Wk7Dix:-N2mfDdt6stw5No61aJs:bsgaptv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dd789d8f142e3dd8b77dad20f8c0067cc98f460c/src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql#L23)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Where are the primary keys for these tables defined? Usually you want some PK that's internal to your system.
</blockquote></details>

There are no Primary keys since I don't think we would ever need one. The (bucket, params) pair and (mc_id, reference_id, isRefund) pairs specifies the rows absolutely- (there is no other way we would want to get those rows)  But I can be wrong, if you feel strongly,  I can add.
___
*[`src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql` line 24 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/562#-N2TAKqH46PVNJ6T5XUL:-N2mPMfKEqD_hDT9qb3H:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dd789d8f142e3dd8b77dad20f8c0067cc98f460c/src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql#L24)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Rename this since it's not a table of ledger entries
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql` line 46 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/562#-N2TCySx6_T_3dkDeDmJ:-N2mdpBk1xKGNPC4yjj8:bdn3xkw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dd789d8f142e3dd8b77dad20f8c0067cc98f460c/src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql#L46)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Shouldn't there be something that links balances w/ledger entries? e.g. to answer the query "Tell me all the ledger entries that affected this balance"?

Not a strict requirement, but you usually want to encode all the relationships in a relational DB with foreign keys.
</blockquote></details>

So as of this implementation, "Tell me all the ledger entries that affected this balance" would never be used for refunds or charges of refunds. If there is a refund for example, the code just does bucket mapping, filtering and decreases the repetition_counts for those balances. Want to be on the same page with our understanding. If we want to do it that way, we would need quite a lot of changes and we would need to add something like LedgerEntryToBalances table since the relationship is many-to-many
___
*[`src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql` line 47 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/562#-N2TAOIV1oc7X2t9TGXM:-N2mPPDH9dTXeiWihr-R:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dd789d8f142e3dd8b77dad20f8c0067cc98f460c/src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql#L47)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Rename this to be `LedgerEntries`
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql` line 47 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/562#-N2TDUVf-pIM9dVVaVwR:-N2mPTCiCopiSKlyORC0:b-sk16tg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dd789d8f142e3dd8b77dad20f8c0067cc98f460c/src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql#L47)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Also add MeasurementConsumerId to this table. Whatever we'd use for the reference ID (requisition ID or measurement ID) is only guaranteed by the API to be unique for a given MC, not globally unique.
</blockquote></details>

oh, that is important thank you
___
*[`src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql` line 48 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/562#-N2TAbSc7e75S2BkNLON:-N2mPgLL79_frtvVOS9n:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dd789d8f142e3dd8b77dad20f8c0067cc98f460c/src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql#L48)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Something like "ID from an external system that uniquely identifies the source all charges in a transaction for a given MeasurementConsumer." 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-05-24 22:15 UTC, uakyol reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/562)* status: 0 of 20 files reviewed, 10 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql` line 23 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/562#-N2TFP327Mj6W3Wk7Dix:-N2s-MxPCRGgTCDQObD5:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dd789d8f142e3dd8b77dad20f8c0067cc98f460c/src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql#L23)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

You should always indicate some primary key, which is a tuple of columns. I'm actually surprised Postgres lets you create a table without one. PKs are what you use to establish the relationships between tables in an RDBMS.

The tuples you mention could be used as "natural keys". What we've done so far in our DB design has been to use "surrogate keys", where we have some IDs internal to the DB system that we use as keys. There are multiple articles online about the differences and tradeoffs between the two.

Regardless of whether you wish to add surrogate keys, you should declare a PK for each table. If you're going to use the natural keys, the PK declaration will remove the need for a unique index.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql` line 46 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/562#-N2TCySx6_T_3dkDeDmJ:-N2rcof_DhJ9aRBAtqe3:b-wxvf1y) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dd789d8f142e3dd8b77dad20f8c0067cc98f460c/src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql#L46)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> So as of this implementation, "Tell me all the ledger entries that affected this balance" would never be used for refunds or charges of refunds.

I agree that it wouldn't be used by the current application code, but it doesn't mean that the relationship shouldn't be encoded such that someone could do ad-hoc queries.

> If we want to do it that way, we would need quite a lot of changes and we would need to add something like LedgerEntryToBalances table since the relationship is many-to-many

Yes, that's why I noted that it's not a strict requirement. That said, one usually wants to take advantage of the relational nature of an RDBMS when designing the schema.
</blockquote></details>

ok, I added a TODO because I think we need to discuss the space implications of this. I will have a followup PR btw, to add replay ability, I'll address it there
___
*[`src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql` line 55 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/562#-N2r1VU3DtL4SNdtRjNz:-N2rcaDN9s2Kwx78df_B:by6btpn) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0833aeb0b5f65642dc3ceb2e745d7021be43b8ad/src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql#L55)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I'm not sure why you'd want this index, since querying by ReferenceId alone could give you entries for multiple MCs since it's only guaranteed to be unique for a given MC.
</blockquote></details>

sorry. How does this look?


<!-- Sent from Reviewable.io -->

2022-05-25 01:00 UTC, SanjayVas reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/562)* status: 0 of 20 files reviewed, 13 unresolved discussions (waiting on @SanjayVas and @uakyol)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetLedgerBackingStore.kt` line 38 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/562#-N2scRqR0CkHgugIITOD:-N2scRqR0CkHgugIITOE:b-kbto0h) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1e986841bb0354ecd8a0755243c8667d90e9e662/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetLedgerBackingStore.kt#L38)):*
> ```Kotlin
> data class PrivacyBudgetLedgerEntry(
>   val measurementConsumerId: String,
>   val referenceKey: String,
> ```

nit: `referenceId` everywhere for consistency

Though maybe we should just explicitly say `requisitionId`, depending on if this is supposed to be a generic PBM library vs. one that's tightly coupled to the CMMS API. I thought it was supposed to be generic, but there's parts of the library that explicitly depend on the public API protos.

If it's supposed to be a generic library, then it should have its own structures and calling code should be responsible for mapping between the public API and the PBM API.



_Code quote:_
```Kotlin
referenceKey
```
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyQuery.kt` line 32 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/562#-N2sd9xfC_K87xGKSNSu:-N2sd9xfC_K87xGKSNSv:b-9kxu31) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1e986841bb0354ecd8a0755243c8667d90e9e662/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyQuery.kt#L32)):*
> ```Kotlin
> 
> /** Represents a privacy filter for one event group. */
> data class PrivacyEventGroupSpec(
> ```

nit: don't need to prefix everything with "Privacy" when already in a privacy-related namespace. This is known as the "Smurf naming convention" anti-pattern.

As a guide, use the prefix when it's necessary for disambiguation or it's part of the name (in which case it's not really a prefix).



_Code quote:_
```Kotlin
Privacy
```
___
*[`src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql` line 21 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/562#-N2sYIn69j6_54st1_Ed:-N2sYIn69j6_54st1_Ee:bhu6vit) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1e986841bb0354ecd8a0755243c8667d90e9e662/src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql#L21)):*
> ```TSQL
> AS ENUM('18_34', '35_54', '55+');
> 
> CREATE TABLE BalanceEntries(
> ```

nit: `Balances` is probably cleaner.

I assume the main reason for the "Entries" suffix on the other table is to give it a plural name.



_Code quote:_
```TSQL
BalanceEntries
```
___
*[`src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql` line 33 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/562#-N2s_3Zb5kl6s6q-HK_1:-N2s_3Zb5kl6s6q-HK_2:b13h6ta) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1e986841bb0354ecd8a0755243c8667d90e9e662/src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql#L33)):*
> ```TSQL
>   VidStart real NOT NULL,
>   -- Delta for the charge of this ledger entry.
>   Delta real NOT NULL,
> ```

Just for my own understanding, does having balances with different values for these for the same bucket make sense? If not, shouldn't we be preventing that?



_Code quote:_
```TSQL
  -- Delta for the charge of this ledger entry.
  Delta real NOT NULL,
  -- Epsilon for the charge of this ledger entry.
  Epsilon real NOT NULL,
```
___
*[`src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql` line 55 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/562#-N2scJF4-BXOuzM21bqj:-N2scJF4-BXOuzM21bqk:b-a5c0ej) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1e986841bb0354ecd8a0755243c8667d90e9e662/src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql#L55)):*
> ```TSQL
> -- Used to query references quickly
> CREATE
>   INDEX LedgerEntriesByKey
> ```

nit: ByReferenceId



_Code quote:_
```TSQL
ByKey
```


<!-- Sent from Reviewable.io -->

2022-05-25 21:36 UTC, SanjayVas requested changes
> Reviewed 3 of 16 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/562)* status: 3 of 22 files reviewed, 13 unresolved discussions (waiting on @SanjayVas and @uakyol)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/InMemoryBackingStore.kt` line 37 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/562#-N2x2iJo6Gbpwm-_sqVe:-N2x2iJo6Gbpwm-_sqVf:b-6bke5c) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cbbeb93e8c050265dfd188f8af8b48528abdb5b8/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/InMemoryBackingStore.kt#L37)):*
> ```Kotlin
> open class InMemoryBackingStore : PrivacyBudgetLedgerBackingStore {
>   protected val balances:
>     MutableMap<PrivacyBucketGroup, MutableMap<Charge, PrivacyBudgetBalanceEntry>> =
> ```

nit: Wouldn't a map of bucket group to a map of charge to count be sufficient?



_Code quote:_
```Kotlin
    MutableMap<PrivacyBucketGroup, MutableMap<Charge, PrivacyBudgetBalanceEntry>> =
    mutableMapOf()
```
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetLedgerBackingStore.kt` line 88 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/562#-N2x6tNz5hlVCnEEZ-0T:-N2x6tO-9Fv8VjQL03RZ:bchl2fd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cbbeb93e8c050265dfd188f8af8b48528abdb5b8/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetLedgerBackingStore.kt#L88)):*
> ```Kotlin
>   )
> 
>   /** Checks if the charges with the [referenceId] should be processed. */
> ```

Document that this can return an inaccurate result if having multiple in-flight entries with the same (MC ID, reference ID). This is because we only check that `isRefund` is the opposite of the most recent recorded ledger entry for that tuple.
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetLedgerBackingStore.kt` line 89 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/562#-N2x69iqC8CaSZNqlWVu:-N2x69iqC8CaSZNqlWVv:bwwh51w) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cbbeb93e8c050265dfd188f8af8b48528abdb5b8/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetLedgerBackingStore.kt#L89)):*
> ```Kotlin
> 
>   /** Checks if the charges with the [referenceId] should be processed. */
>   fun shouldProcess(referenceId: String, isRefund: Boolean): Boolean
> ```

Doesn't this need the MC ID?
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetLedgerBackingStore.kt` line 89 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/562#-N2x6BD82Z3Bjm80SwNR:-N2x6BD82Z3Bjm80SwNS:b-nxcqe9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cbbeb93e8c050265dfd188f8af8b48528abdb5b8/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetLedgerBackingStore.kt#L89)):*
> ```Kotlin
> 
>   /** Checks if the charges with the [referenceId] should be processed. */
>   fun shouldProcess(referenceId: String, isRefund: Boolean): Boolean
> ```

nit: Maybe flip and rename to`hasLedgerEntry` to make it clear that the condition is whether there's an existing ledger entry?



_Code quote:_
```Kotlin
shouldProcess
```
___
*[`src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql` line 33 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/562#-N2s_3Zb5kl6s6q-HK_1:-N2wgOC02jkenAya2uAm:baituvx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1e986841bb0354ecd8a0755243c8667d90e9e662/src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql#L33)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

Yes, that is how the advanced composition (aggregation of charges) works. Here is the piece of code that handles that: https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetLedger.kt#L155 if there are different Delta/Epsilon pairs for the same bucket, they should be in different rows.
</blockquote></details>

Okay, so attempting to apply the the banking analogy here: An "account" would be a privacy bucket for a given MC. The "balance" for an account is made up of multiple (epsilon, delta, count) tuples.

If this is correct, then a single row isn't a single account balance and the table should probably be called something different? It looks like the term you use elsewhere is "charge". The way I'd personally represent the balance is using two tables: `PrivacyBuckets` with MC ID and the dimension fields, and `PrivacyBucketCharges` to represent the 1:many relationship of buckets:charges. Of course if you're using a natural key for `PrivacyBuckets`, then each charge row would effectively contain an entire bucket row.

Sorry for the churn as I develop my understanding of how PBM works. Would you mind renaming the table again to `PrivacyBucketCharges` if my above understanding is correct, since each row isn't technically a whole balance.


<!-- Sent from Reviewable.io -->

2022-05-25 22:28 UTC, uakyol reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/562)* status: 2 of 22 files reviewed, 13 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/InMemoryBackingStore.kt` line 37 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/562#-N2x2iJo6Gbpwm-_sqVe:-N2xDT9R3xKlA0yG-EEW:b-w7oypw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7d12bee2677829146dd984db0cb99f4bbdb85a50/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/InMemoryBackingStore.kt#L37)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: Wouldn't a map of bucket group to a map of charge to count be sufficient?
</blockquote></details>

right, but then you need to reconstruct PrivacyBudgetBalanceEntry for each call. I prefer to leave it this way since size is not an issue for in memory case which will be used for a single MC. wdyt?
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetLedgerBackingStore.kt` line 88 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/562#-N2x6tNz5hlVCnEEZ-0T:-N2xBk4P6yh3z6oexAhI:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7d12bee2677829146dd984db0cb99f4bbdb85a50/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetLedgerBackingStore.kt#L88)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Document that this can return an inaccurate result if having multiple in-flight entries with the same (MC ID, reference ID). This is because we only check that `isRefund` is the opposite of the most recent recorded ledger entry for that tuple.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetLedgerBackingStore.kt` line 89 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/562#-N2x69iqC8CaSZNqlWVu:-N2xBkQNDafI86xBQ11J:bx008ce) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7d12bee2677829146dd984db0cb99f4bbdb85a50/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetLedgerBackingStore.kt#L89)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Doesn't this need the MC ID?
</blockquote></details>

great catch, thank you! Missed this. Also added a test for multiple MCs
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetLedgerBackingStore.kt` line 89 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/562#-N2x6BD82Z3Bjm80SwNR:-N2xCpWV3KA4M1GGuYW0:bq1zq3h) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7d12bee2677829146dd984db0cb99f4bbdb85a50/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetLedgerBackingStore.kt#L89)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: Maybe flip and rename to`hasLedgerEntry` to make it clear that the condition is whether there's an existing ledger entry?
</blockquote></details>

It might be misleading since there might be a ledger entry, but we should process this . Example :   
1st query -> (MC1, Requisition1, refund=false)
2nd query -> (MC1, Requisition1, refund=true)
3rd query -> (MC1, Requisition1, refund=false) ===> this ledgerEntry exists but should be processed.
___
*[`src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql` line 33 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/562#-N2s_3Zb5kl6s6q-HK_1:-N2xHUNRCbX0g0vdt49n:b-i34yop) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1e986841bb0354ecd8a0755243c8667d90e9e662/src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql#L33)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Okay, so attempting to apply the the banking analogy here: An "account" would be a privacy bucket for a given MC. The "balance" for an account is made up of multiple (epsilon, delta, count) tuples.

If this is correct, then a single row isn't a single account balance and the table should probably be called something different? It looks like the term you use elsewhere is "charge". The way I'd personally represent the balance is using two tables: `PrivacyBuckets` with MC ID and the dimension fields, and `PrivacyBucketCharges` to represent the 1:many relationship of buckets:charges. Of course if you're using a natural key for `PrivacyBuckets`, then each charge row would effectively contain an entire bucket row.

Sorry for the churn as I develop my understanding of how PBM works. Would you mind renaming the table again to `PrivacyBucketCharges` if my above understanding is correct, since each row isn't technically a whole balance.
</blockquote></details>

thank you. Yes, I renamed it to PrivacyBucketCharges and put a TODO to consider normalization since this PR is blocking multiple other work, I'd be happy to address that on an upcoming PR. wdyt?


<!-- Sent from Reviewable.io -->

2022-05-26 18:21 UTC, SanjayVas reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/562)* status: 2 of 22 files reviewed, 11 unresolved discussions (waiting on @SanjayVas and @uakyol)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/InMemoryBackingStore.kt` line 37 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/562#-N2x2iJo6Gbpwm-_sqVe:-N30YZwn981CyuHumQbU:bvtqb8o) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7d12bee2677829146dd984db0cb99f4bbdb85a50/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/InMemoryBackingStore.kt#L37)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

right, but then you need to reconstruct PrivacyBudgetBalanceEntry for each call. I prefer to leave it this way since size is not an issue for in memory case which will be used for a single MC. wdyt?
</blockquote></details>

If it's just for the in-memory impl, than no big deal.
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetLedgerBackingStore.kt` line 89 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/562#-N2x6BD82Z3Bjm80SwNR:-N30YrAF-5Sp-pAeLBao:bp7wr2w) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7d12bee2677829146dd984db0cb99f4bbdb85a50/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetLedgerBackingStore.kt#L89)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

It might be misleading since there might be a ledger entry, but we should process this . Example :   
1st query -> (MC1, Requisition1, refund=false)
2nd query -> (MC1, Requisition1, refund=true)
3rd query -> (MC1, Requisition1, refund=false) ===> this ledgerEntry exists but should be processed.
</blockquote></details>

I think the language would still be correct since a ledger entry is actually (MC ID, Reference ID, refund, timestamp). Hence why this is an approximation, as you're doing the lookup without a timestamp. The implementation can be described as "see if there's an existing ledger entry by assuming that the timestamp is either 1. that of the most recent entry if the most recent entry with (MC ID, Reference ID) also has the same value for isRefund, or 2. now"

Hence why the description states that it might be inaccurate in cases where there are in-flight requests with opposite values of isRefund, as the assumption re: the timestamp may not be correct.


<!-- Sent from Reviewable.io -->

2022-05-27 18:30 UTC, SanjayVas requested changes
> Reviewed 1 of 19 files at r1, 1 of 16 files at r8, 6 of 13 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/562)* status: 9 of 22 files reviewed, 16 unresolved discussions (waiting on @SanjayVas, @stevenwarejones, and @uakyol)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetLedger.kt` line 136 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/562#-N35hRKJATSfITzbqY5O:-N35hRKK2p483aZ6JU9y:b698yup) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b5f5db2d1418fda72f7fca94f8e06ca8a48ce131/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetLedger.kt#L136)):*
> ```Kotlin
>    */
>   private fun privacyBudgetIsExceeded(
>     ledgerEntries: Set<PrivacyBudgetBalanceEntry>,
> ```

`balanceEntries`



_Code quote:_
```Kotlin
ledgerEntries
```
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetLedgerBackingStore.kt` line 79 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/562#-N35hibaDrQRDWC1hEaV:-N35hibaDrQRDWC1hEaW:b-kjvy4j) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b5f5db2d1418fda72f7fca94f8e06ca8a48ce131/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetLedgerBackingStore.kt#L79)):*
> ```Kotlin
> 
>   /**
>    * Adds new rows to the PrivacyBudgetLedger specifying a charge to a privacy budget, adds the
> ```

nit: entries, as an implementation isn't necessarily using DB rows



_Code quote:_
```Kotlin
 rows
```
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetLedgerBackingStore.kt` line 80 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/562#-N35hus0EOBBp9ZKBLK9:-N35hus0EOBBp9ZKBLKA:bfcuhln) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b5f5db2d1418fda72f7fca94f8e06ca8a48ce131/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetLedgerBackingStore.kt#L80)):*
> ```Kotlin
>   /**
>    * Adds new rows to the PrivacyBudgetLedger specifying a charge to a privacy budget, adds the
>    * privacyReference that created these charges
> ```

nit: use KDoc references where applicable, so `[reference]`.



_Code quote:_
```Kotlin
privacyReference
```
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetLedgerBackingStore.kt` line 89 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/562#-N35i3jX0L9FP1r8mF9X:-N35i3jX0L9FP1r8mF9Y:b3x6ee2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b5f5db2d1418fda72f7fca94f8e06ca8a48ce131/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetLedgerBackingStore.kt#L89)):*
> ```Kotlin
> 
>   /**
>    * See if there's an existing ledger entry by assuming that the timestamp is either
> ```

Follow [style guide](https://developer.android.com/kotlin/style-guide#documentation) section on documentation.

In particular, have a brief summary fragment followed optionally by paragraphs with more details. The summary fragment would be something like `Returns whether this backing store has a ledger entry for [reference].`
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/testing/AbstractPrivacyBudgetLedgerStoreTest.kt` line 149 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/562#-N35jcTD-hlMU08Eijn3:-N35jcTD-hlMU08Eijn4:b-rgm8d3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b5f5db2d1418fda72f7fca94f8e06ca8a48ce131/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/testing/AbstractPrivacyBudgetLedgerStoreTest.kt#L149)):*
> ```Kotlin
> 
>   @Test(timeout = 15000)
>   fun `addLedgerEntries works for different MCs with the same referenceId`() {
> ```

"works" is a smell when it comes to tests. What state/behavior is being verified?



_Code quote:_
```Kotlin
 works
```
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/testing/AbstractPrivacyBudgetLedgerStoreTest.kt` line 173 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/562#-N35liaTBiDZkOUiTJPY:-N35liaTBiDZkOUiTJPZ:baac1in) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b5f5db2d1418fda72f7fca94f8e06ca8a48ce131/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/testing/AbstractPrivacyBudgetLedgerStoreTest.kt#L173)):*
> ```Kotlin
>         assertThat(matchingLedgerEntries.size).isEqualTo(1)
> 
>         assertThat(matchingLedgerEntries[0].repetitionCount).isEqualTo(1)
> ```

These should be separate tests. e.g. one test to verify that a ledger entry gets added, another to verify that adding a second entry increments the repetition count, etc.
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/testing/AbstractPrivacyBudgetLedgerStoreTest.kt` line 234 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/562#-N35j8l450moEc1PSoxH:-N35j8l450moEc1PSoxI:b4a1gua) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b5f5db2d1418fda72f7fca94f8e06ca8a48ce131/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/testing/AbstractPrivacyBudgetLedgerStoreTest.kt#L234)):*
> ```Kotlin
> 
>   @Test(timeout = 15000)
>   fun `hasLedgerEntry works correctly`() {
> ```

"works" or "works correctly" is a smell when it comes to tests.

This should be two or more separate test methods, of the form `hasLedgerEntry return X when Y`



_Code quote:_
```Kotlin
works correctly
```


<!-- Sent from Reviewable.io -->

2022-05-29 05:27 UTC, uakyol reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/562)* status: 5 of 22 files reviewed, 12 unresolved discussions (waiting on @SanjayVas and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/testing/AbstractPrivacyBudgetLedgerStoreTest.kt` line 149 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/562#-N35jcTD-hlMU08Eijn3:-N3DFqXHAOs2L049Z8fR:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b5f5db2d1418fda72f7fca94f8e06ca8a48ce131/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/testing/AbstractPrivacyBudgetLedgerStoreTest.kt#L149)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

"works" is a smell when it comes to tests. What state/behavior is being verified?
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/testing/AbstractPrivacyBudgetLedgerStoreTest.kt` line 173 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/562#-N35liaTBiDZkOUiTJPY:-N3DEeTRDtuadPtDI35H:b5n5ln3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b5f5db2d1418fda72f7fca94f8e06ca8a48ce131/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/testing/AbstractPrivacyBudgetLedgerStoreTest.kt#L173)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

These should be separate tests. e.g. one test to verify that a ledger entry gets added, another to verify that adding a second entry increments the repetition count, etc.
</blockquote></details>

I already have those tests above. I am trying to test here that 2 MCs do not mess with each other's repetition counts even if the requisitionIds are the same. How would you write this test?



_Code quote:_
```Kotlin
addLedgerEntries works for different MCs with the same referenceId
```
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/testing/AbstractPrivacyBudgetLedgerStoreTest.kt` line 234 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/562#-N35j8l450moEc1PSoxH:-N3DGfJcCvtt-bRQDQFB:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b5f5db2d1418fda72f7fca94f8e06ca8a48ce131/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/testing/AbstractPrivacyBudgetLedgerStoreTest.kt#L234)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

"works" or "works correctly" is a smell when it comes to tests.

This should be two or more separate test methods, of the form `hasLedgerEntry return X when Y`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-05-31 16:43 UTC, SanjayVas requested changes
> Reviewed 4 of 5 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/562)* status: 9 of 22 files reviewed, 11 unresolved discussions (waiting on @SanjayVas, @stevenwarejones, and @uakyol)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/testing/AbstractPrivacyBudgetLedgerStoreTest.kt` line 173 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/562#-N35liaTBiDZkOUiTJPY:-N3PymMs-jZPuZbSHKQg:b-or3adk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b5f5db2d1418fda72f7fca94f8e06ca8a48ce131/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/testing/AbstractPrivacyBudgetLedgerStoreTest.kt#L173)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

I already have those tests above. I am trying to test here that 2 MCs do not mess with each other's repetition counts even if the requisitionIds are the same. How would you write this test?
</blockquote></details>

So a test of made up of thee parts: setup, calling the Subject Under Test (SUT) method, and verification. If this is what you want to test, then it should be

1. Setup: Add a ledger entry to one MC.
2. Call addLedgerEntries for second MC.
3. Verify that they both have a value of `1` for their repetition count.

You shouldn't verify anything beyond what the test method is focused on, and rely on the fact that you have the other parts already covered in other tests.

Possibly relevant reading: https://testing.googleblog.com/2018/06/testing-on-toilet-keep-tests-focused.html


<!-- Sent from Reviewable.io -->

2022-05-31 18:10 UTC, uakyol reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/562)* status: 9 of 22 files reviewed, 9 unresolved discussions (waiting on @SanjayVas and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/testing/AbstractPrivacyBudgetLedgerStoreTest.kt` line 173 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/562#-N35liaTBiDZkOUiTJPY:-N3QD3Re22AHy50neUvB:bl8n7ow) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b5f5db2d1418fda72f7fca94f8e06ca8a48ce131/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/testing/AbstractPrivacyBudgetLedgerStoreTest.kt#L173)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

So a test of made up of thee parts: setup, calling the Subject Under Test (SUT) method, and verification. If this is what you want to test, then it should be

1. Setup: Add a ledger entry to one MC.
2. Call addLedgerEntries for second MC.
3. Verify that they both have a value of `1` for their repetition count.

You shouldn't verify anything beyond what the test method is focused on, and rely on the fact that you have the other parts already covered in other tests.

Possibly relevant reading: https://testing.googleblog.com/2018/06/testing-on-toilet-keep-tests-focused.html
</blockquote></details>

thank you for the explanation, updated



_Code quote:_
```Kotlin
addLedgerEntries
```


<!-- Sent from Reviewable.io -->

2022-05-31 20:20 UTC, stevenwarejones reviewed
> Reviewed 3 of 19 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/562)* status: 9 of 22 files reviewed, 17 unresolved discussions (waiting on @duliomatos1, @SanjayVas, and @uakyol)



<!-- Sent from Reviewable.io -->

2022-05-31 20:29 UTC, uakyol reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/562)* status: 9 of 22 files reviewed, 5 unresolved discussions (waiting on @duliomatos1, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetLedger.kt` line 79 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/562#-N1yJ1Ww2Uj1tGTq2F71:-N3QnMVV51S105Lw0ab5:boma5vr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/37ec2708077ad0088a8e2b2c583e0f1debf206fc/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetLedger.kt#L79)):*
> charing
Done
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetManager.kt` line 107 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/562#-N1yJhi_6VR92P9vil9W:-N3QnWMlBmZQVwKnx2pt:b-xnyk8h) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/37ec2708077ad0088a8e2b2c583e0f1debf206fc/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetManager.kt#L107)):*
> my purpose is to spell this word correctly next time  😆
my purpose is to spell this word correctly next time 😆
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetManager.kt` line 141 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/562#-N1yJpI78JB4Y1kbxN_D:-N3Qn_pQ6LhbelrcuHtX:b-vwgt73) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/37ec2708077ad0088a8e2b2c583e0f1debf206fc/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetManager.kt#L141)):*
> This comment was from before. I just moved the code from another file. Basically, this refers to times expressed as timestamps in the requisition proto but the PBM needs dates, so timezones com into play. I intend to talk about this in a halo meeting soon
This comment was from before. I just moved the code from another file. Basically, this refers to times expressed as timestamps in the requisition proto but the PBM needs dates, so timezones com into play. I intend to talk about this in a halo meeting soon
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/deploy/postgres/PostgresBackingStore.kt` line 207 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/562#-N1yKf6G7-11vPQytbfa:-N3QndqwBKcqpl1Zkq5l:b-zfqrzx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/37ec2708077ad0088a8e2b2c583e0f1debf206fc/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/deploy/postgres/PostgresBackingStore.kt#L207)):*
> you are right. changed it.
you are right. changed it.
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/deploy/postgres/PostgresBackingStore.kt` line 208 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/562#-N1yKEBcB5Tg4pT1HBoK:-N3QnfRv2_4qphaCGZG_:b-tpn1mh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/37ec2708077ad0088a8e2b2c583e0f1debf206fc/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/deploy/postgres/PostgresBackingStore.kt#L208)):*
> ugur: this is for the second part of the sql statement : "DO
> UPDATE SET RepetitionCount = ? + LedgerEntries.RepetitionCount;"
> So when the same bucket is found, we don not insert a duplicate but increase the RepetitionCount. I updated the comment with 'update repetition count' .

ugur: this is for the second part of the sql statement : "DO
UPDATE SET RepetitionCount = ? + LedgerEntries.RepetitionCount;"

So when the same bucket is found, we don not insert a duplicate but increase the RepetitionCount. I updated the comment with 'update repetition count' .


<!-- Sent from Reviewable.io -->

2022-06-01 19:47 UTC, SanjayVas requested changes
> Reviewed 2 of 19 files at r1, 1 of 16 files at r8, 1 of 5 files at r9, 2 of 8 files at r10, 6 of 13 files at r11, 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/562)* status: all files reviewed, 11 unresolved discussions (waiting on @duliomatos1, @SanjayVas, @stevenwarejones, and @uakyol)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/deploy/postgres/PostgresBackingStore.kt` line 32 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/562#-N3VhRyLAuJ9OWnktxLg:-N3VhRyLAuJ9OWnktxLh:bgpb5fa) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a94bfa63b1cac0a68447f02b5349b5089926bbb1/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/deploy/postgres/PostgresBackingStore.kt#L32)):*
> ```Kotlin
>  * A [PrivacyBudgetLedgerBackingStore] implemented in Postgres compatible SQL.
>  *
>  * @param createConnection is a function that creates a postgres JDBC connection that will be owned
> ```

Add a TODO to redesign this to reduce connection lifetime, e.g. using a Connection for a single transaction/operation and then closing it.

If using a connection pool, closing a Connection will not close the underlying socket and just allow the connection to be released to the pool.



_Code quote:_
```Kotlin
 * @param createConnection is a function that creates a postgres JDBC connection that will be owned
 * by the backing store and should not be used outside this backing store.
```
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/testing/AbstractPrivacyBudgetLedgerStoreTest.kt` line 101 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/562#-N3Vb41b3_JYAHKJkKhp:-N3Vb41b3_JYAHKJkKhq:bhcm1rf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a94bfa63b1cac0a68447f02b5349b5089926bbb1/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/testing/AbstractPrivacyBudgetLedgerStoreTest.kt#L101)):*
> ```Kotlin
>         )
> 
>         val intersectingEntry = txContext.findIntersectingBalanceEntries(bucket1)
> ```

nit: explicit type since it's not obvious
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/testing/AbstractPrivacyBudgetLedgerStoreTest.kt` line 101 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/562#-N3Vb8RCBXqKco3hggEk:-N3Vb8RCBXqKco3hggEl:b-3xbhax) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a94bfa63b1cac0a68447f02b5349b5089926bbb1/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/testing/AbstractPrivacyBudgetLedgerStoreTest.kt#L101)):*
> ```Kotlin
>         )
> 
>         val intersectingEntry = txContext.findIntersectingBalanceEntries(bucket1)
> ```

nit `intersectingEntries` since it's a collection



_Code quote:_
```Kotlin
intersectingEntry
```
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/testing/AbstractPrivacyBudgetLedgerStoreTest.kt` line 102 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/562#-N3VbSzl3x3CQJcdvlbC:-N3VbSzl3x3CQJcdvlbD:b-i5l5fj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a94bfa63b1cac0a68447f02b5349b5089926bbb1/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/testing/AbstractPrivacyBudgetLedgerStoreTest.kt#L102)):*
Use the more specific subject methods from Truth. e.g. 

```
assertThat(intersectingEntry).hasSize(1)From
```

From truth.dev:
> If you’re using an IDE with autocompletion, it will suggest a list of assertions you can make about the given type. If not, consult the API docs. For example, if you’re looking for assertions about a Map, look at the documentation for MapSubject, available at truth.dev/MapSubject.

Therefore see https://truth.dev/IterableSubject
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/testing/TestInMemoryBackingStore.kt` line 19 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/562#-N3VdGo-AcwfHmFbeU2w:-N3VdGo-AcwfHmFbeU2x:b-7pns3r) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a94bfa63b1cac0a68447f02b5349b5089926bbb1/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/testing/TestInMemoryBackingStore.kt#L19)):*
> ```Kotlin
> 
> class TestInMemoryBackingStore : InMemoryBackingStore() {
>   fun getBalance() = balances.toMap()
> ```

nit: `getBalances`



_Code quote:_
```Kotlin
getBalance
```
___
*[`src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql` line 14 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/562#-N3VfE8iARtusZAYXfYz:-N3VfE8iARtusZAYXfZ-:b6nbxy6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a94bfa63b1cac0a68447f02b5349b5089926bbb1/src/main/kotlin/org/wfanet/measurement/integration/deploy/postgres/ledger.sql#L14)):*
> ```TSQL
> -- See the License for the specific language governing permissions and
> -- limitations under the License.
> ```

Add a TODO to migrate this to Liquibase changelog format.


<!-- Sent from Reviewable.io -->

2022-06-01 23:18 UTC, uakyol reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/562)* status: 17 of 22 files reviewed, 7 unresolved discussions (waiting on @duliomatos1, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/InMemoryBackingStore.kt` line 79 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/562#-N3W06xD-M12xNzFnxKp:-N3WQVt_CkGIDrOF0pbR:b-pblwr0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a94bfa63b1cac0a68447f02b5349b5089926bbb1/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/InMemoryBackingStore.kt#L79)):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

shouldn't this chain end with `?: false`?

I assume `hasLedgerEntry()` should return false when no entry is found for the subsequent checks
But testing this assumption in an unit test, it would fail:
```
diff --git a/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/testing/AbstractPrivacyBudgetLedgerStoreTest.kt b/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/testing/AbstractPrivacyBudgetLedgerStoreTest.kt
index 66cfe074..2761f157 100644
--- a/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/testing/AbstractPrivacyBudgetLedgerStoreTest.kt
+++ b/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/testing/AbstractPrivacyBudgetLedgerStoreTest.kt
@@ -228,6 +228,15 @@ abstract class AbstractPrivacyBudgetLedgerStoreTest {
     newBackingStore.close()
   }
 
+  @Test(timeout = 15000)
+  fun `hasLedgerEntry returns false when ledger is empty`() {
+    val backingStore = createBackingStore()
+    val txContext1 = backingStore.startTransaction()
+    assertThat(
+      txContext1.hasLedgerEntry(Reference(MEASUREMENT_CONSUMER_ID, "RequisitioId1", false))
+    ).isFalse()
+  }
+
   @Test(timeout = 15000)
   fun `hasLedgerEntry returns true when ledger entry with same isRefund is found false o w`() {
     val backingStore = createBackingStore()
```

```
There was 1 failure:
1) hasLedgerEntry returns false when ledger is empty(org.wfanet.measurement.eventdataprovider.privacybudgetmanagement.InMemoryBackingStoreTest)
expected to be false
```
</blockquote></details>

you are right. Thanks for investigating and finding this Dulio! What happened was that this function was named shouldProcess before. I changed it based on a comment to hasLedgerEntry so the implication is wrong, I should have flipped the bits. The code executes correctly but semantics are wrong I flipped the logic throughout. Also added your test, thanks


<!-- Sent from Reviewable.io -->

2022-06-02 00:22 UTC, SanjayVas requested changes
> Reviewed 1 of 3 files at r14, 4 of 4 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/562)* status: all files reviewed, 4 unresolved discussions (waiting on @duliomatos1, @stevenwarejones, and @uakyol)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/deploy/postgres/PostgresBackingStore.kt` line 32 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/562#-N3VhRyLAuJ9OWnktxLg:-N3Wm6wWBAQCX9UvhKmv:b-q33tnz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a94bfa63b1cac0a68447f02b5349b5089926bbb1/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/deploy/postgres/PostgresBackingStore.kt#L32)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't see the TODO?
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/testing/TestInMemoryBackingStore.kt` line 19 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/562#-N3VdGo-AcwfHmFbeU2w:-N3WmL5E6tYWewMsEJrI:b-hm1vsh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a94bfa63b1cac0a68447f02b5349b5089926bbb1/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/testing/TestInMemoryBackingStore.kt#L19)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

can't do that since it conflicts with the getter name of the variable in the parent.
</blockquote></details>

Then `getBalancesMap` or something. `getBalance` is incorrect for a collection.


<!-- Sent from Reviewable.io -->

2022-06-02 02:47 UTC, uakyol reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/562)* status: 19 of 22 files reviewed, 3 unresolved discussions (waiting on @duliomatos1, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/deploy/postgres/PostgresBackingStore.kt` line 32 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/562#-N3VhRyLAuJ9OWnktxLg:-N3XFL_oCsBvOZ-LtGgw:bqsaor3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a94bfa63b1cac0a68447f02b5349b5089926bbb1/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/deploy/postgres/PostgresBackingStore.kt#L32)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I don't see the TODO?
</blockquote></details>

sorry, pressed undo apparently before pushing


<!-- Sent from Reviewable.io -->

2022-06-02 16:11 UTC, stevenwarejones approved these changes
> Reviewed 2 of 19 files at r1, 3 of 16 files at r8, 1 of 5 files at r9, 1 of 8 files at r10, 6 of 13 files at r11, 1 of 5 files at r12, 1 of 3 files at r14, 3 of 4 files at r15, 3 of 3 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/562)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/testing/TestInMemoryBackingStore.kt` line 14 at r16](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/562#-N3_Ae5K332jMCd6o41q:-N3_Ae5L6DWGeO6qtAmc:b-9vjsot) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7ccfd1a7f50f67ba42ec2ce08a4c2f16e4ec1148/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/testing/TestInMemoryBackingStore.kt#L14)):*
> ```Kotlin
>  * the License.
>  */
> package org.wfanet.measurement.eventdataprovider.privacybudgetmanagement.testing
> ```

nit: This test should go in the same namespace as the InMemoryBackingStore


<!-- Sent from Reviewable.io -->

2022-06-02 17:44 UTC, SanjayVas approved these changes
> Reviewed 3 of 3 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/562)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @uakyol)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/deploy/postgres/PostgresBackingStore.kt` line 36 at r16](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/562#-N3ZBvCU11ZTiVsDzrY9:-N3_Vb88EH7oucB2U-IS:bxsg818) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7ccfd1a7f50f67ba42ec2ce08a4c2f16e4ec1148/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/deploy/postgres/PostgresBackingStore.kt#L36)):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

makes sense. We could also move to use an implementation of a connection pool
</blockquote></details>

FYI Tristan is working on using [R2DBC](https://r2dbc.io/) instead of JDBC for the Reporting server's usage of Postgres. I think everything related to a Connection would still be the same, but the connection pool implementation might be slightly different.


<!-- Sent from Reviewable.io -->

2022-06-02 20:14 UTC, merged