Reporting schema and internal protos.
world-federation-of-advertisers/cross-media-measurement pull request #564
Opened 2022-05-17 00:23 UTC by tristanvuong2021

2022-05-18 18:24 UTC, SanjayVas requested changes
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/564)* status: all files reviewed, 9 unresolved discussions (waiting on @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/reporting.sql` line 26 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/564#-N2NHQZ31KlGacWdpBgK:-N2NHQZ31KlGacWdpBgL:b-8eha0u) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9cb9b9b20bc33add0f66dfa2b535ba563be79c05/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/reporting.sql#L26)):*
> ```TSQL
> --   └── ReportingSets
> 
> CREATE TABLE IF NOT EXISTS Reports (
> ```

Now that changes to use Liquibase have been submitted, define the schema using Liquibase changeset format, leaving out the `IF NOT EXISTS`. Put it under `src/main/resources/reporting/postgres`. Example: https://github.com/world-federation-of-advertisers/cross-media-measurement/tree/main/src/main/resources/kingdom/spanner



_Code quote:_
```TSQL
CREATE TABLE IF NOT EXISTS
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/reporting.sql` line 35 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/564#-N2NIo_gABSQeyOm11K6:-N2NIo_gABSQeyOm11K7:b16huxj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9cb9b9b20bc33add0f66dfa2b535ba563be79c05/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/reporting.sql#L35)):*
> ```TSQL
>   -- protobuf enum encoded as an integer.
>   State smallint NOT NULL,
>   Result text,
> ```

Do we maybe want to store the result as an internal proto in ReportDetails, and generate CSV from it on demand?
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/reporting.sql` line 58 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/564#-N2NKL-49pfO09yJbOYg:-N2NKL-49pfO09yJbOYh:b-2n822t) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9cb9b9b20bc33add0f66dfa2b535ba563be79c05/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/reporting.sql#L58)):*
> ```TSQL
>   EndNanos integer,
> 
>   CONSTRAINT fk_report FOREIGN KEY(MeasurementConsumerReferenceId, ReportId)
> ```

I don't think you need to use a named constraint. Just do it the same way we do in our Spanner schemata:

```
FOREIGN KEY (MeasurementConsumerReferenceId, ReportId) REFERENCES Reports(MeasurementConsumerReferenceId, ReportId)
```

See https://www.postgresql.org/docs/current/ddl-constraints.html#DDL-CONSTRAINTS-FK



_Code quote:_
```TSQL
  CONSTRAINT fk_report FOREIGN KEY(MeasurementConsumerReferenceId, ReportId)
    REFERENCES Reports(MeasurementConsumerReferenceId, ReportId)
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/reporting.sql` line 84 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/564#-N2NKopD0ozt9ZXO5Pwe:-N2NKopE7b-waGM1XaFR:brvnr75) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9cb9b9b20bc33add0f66dfa2b535ba563be79c05/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/reporting.sql#L84)):*
> ```TSQL
> 
>   -- Array of direct child SetOperation IDs
>   SetOperations bigint[],
> ```

This relationship is already represented in the `SetOperations` table. I don't think we want to maintain a two-way relationship, especially as this way can't have a FOREIGN KEY constraint associated with it.



_Code quote:_
```TSQL
  -- Array of direct child SetOperation IDs
  SetOperations bigint[],
```
___
*[`src/main/proto/wfa/measurement/internal/reporting/all_protos.bzl` line 16 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/564#-N2NL5xp0-3DcshnWyoT:-N2NL5xp0-3DcshnWyoU:b-isfm08) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9cb9b9b20bc33add0f66dfa2b535ba563be79c05/src/main/proto/wfa/measurement/internal/reporting/all_protos.bzl#L16)):*
> ```Starlark
> 
> """Provides convenience lists of proto targets from this Bazel package."""
> ```

I still prefer actually listing out the specific targets where needed. If you really want convenient collections, use `java_library` targets that export these instead. See https://github.com/world-federation-of-advertisers/cross-media-measurement/pull/550
___
*[`src/main/proto/wfa/measurement/internal/reporting/metric.proto` line 52 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/564#-N2NO38b3LvvkWF_UmUH:-N2NO38b3LvvkWF_UmUI:b-zepazu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9cb9b9b20bc33add0f66dfa2b535ba563be79c05/src/main/proto/wfa/measurement/internal/reporting/metric.proto#L52)):*
> ```protobuf
>     Type type = 1;
> 
>     message ReportingSetId {
> ```

Maybe `ReportingSetKey` to distinguish from the `ReportingSetId` column.



_Code quote:_
```protobuf
ReportingSetId 
```
___
*[`src/main/proto/wfa/measurement/internal/reporting/metric.proto` line 53 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/564#-N2NOoAI1rk_mTCZnh8x:-N2NOoAI1rk_mTCZnh8y:b-cldtmy) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9cb9b9b20bc33add0f66dfa2b535ba563be79c05/src/main/proto/wfa/measurement/internal/reporting/metric.proto#L53)):*
> ```protobuf
> 
>     message ReportingSetId {
>       // `MeasurementConsumer` API ID from the kingdom.
> ```

nit: Instead of "API ID from the kingdom", use "ID from the CMMS public API"



_Code quote:_
```protobuf
API ID from the kingdom.
```
___
*[`src/main/proto/wfa/measurement/internal/reporting/reporting_set.proto` line 28 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/564#-N2NOSMVBXdykIzdDc8D:-N2NOSMVBXdykIzdDc8E:b-oce6fy) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9cb9b9b20bc33add0f66dfa2b535ba563be79c05/src/main/proto/wfa/measurement/internal/reporting/reporting_set.proto#L28)):*
> ```protobuf
>   fixed64 external_reporting_set_id = 2;
> 
>   // List of `EventGroup` resource names.
> ```

The internal API should represent these using their ID components.



_Code quote:_
```protobuf
List of `EventGroup` resource names.
```
___
*[`src/main/proto/wfa/measurement/internal/common/macros.bzl` line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/564#-N2NPMJdC8lgGiiEXAde:-N2NPMJdC8lgGiiEXAdf:b-fim58c) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9cb9b9b20bc33add0f66dfa2b535ba563be79c05/src/main/proto/wfa/measurement/internal/common/macros.bzl#L1)):*
> ```Starlark
> # Copyright 2022 The Cross-Media Measurement Authors
> ```

Renaming the file shouldn't change copyright date.



_Code quote:_
```Starlark
2022
```


<!-- Sent from Reviewable.io -->

2022-05-19 14:26 UTC, tristanvuong2021 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/564)* status: 2 of 12 files reviewed, 7 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/proto/wfa/measurement/internal/reporting/metric.proto` line 52 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/564#-N2NO38b3LvvkWF_UmUH:-N2NXu-C3NhME6Ko4Z7d:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9cb9b9b20bc33add0f66dfa2b535ba563be79c05/src/main/proto/wfa/measurement/internal/reporting/metric.proto#L52)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Maybe `ReportingSetKey` to distinguish from the `ReportingSetId` column.
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/internal/reporting/reporting_set.proto` line 28 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/564#-N2NOSMVBXdykIzdDc8D:-N2Rhca95CBhADQxAN_c:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9cb9b9b20bc33add0f66dfa2b535ba563be79c05/src/main/proto/wfa/measurement/internal/reporting/reporting_set.proto#L28)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The internal API should represent these using their ID components.
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/internal/reporting/all_protos.bzl` line 16 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/564#-N2NL5xp0-3DcshnWyoT:-N2NXnXSBwukuz96DObd:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9cb9b9b20bc33add0f66dfa2b535ba563be79c05/src/main/proto/wfa/measurement/internal/reporting/all_protos.bzl#L16)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I still prefer actually listing out the specific targets where needed. If you really want convenient collections, use `java_library` targets that export these instead. See https://github.com/world-federation-of-advertisers/cross-media-measurement/pull/550
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/reporting.sql` line 26 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/564#-N2NHQZ31KlGacWdpBgK:-N2NWVFB67iIM5dq-uzu:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9cb9b9b20bc33add0f66dfa2b535ba563be79c05/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/reporting.sql#L26)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Now that changes to use Liquibase have been submitted, define the schema using Liquibase changeset format, leaving out the `IF NOT EXISTS`. Put it under `src/main/resources/reporting/postgres`. Example: https://github.com/world-federation-of-advertisers/cross-media-measurement/tree/main/src/main/resources/kingdom/spanner
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/reporting.sql` line 58 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/564#-N2NKL-49pfO09yJbOYg:-N2NXPv0Af75OWKglYUv:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9cb9b9b20bc33add0f66dfa2b535ba563be79c05/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/reporting.sql#L58)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I don't think you need to use a named constraint. Just do it the same way we do in our Spanner schemata:

```
FOREIGN KEY (MeasurementConsumerReferenceId, ReportId) REFERENCES Reports(MeasurementConsumerReferenceId, ReportId)
```

See https://www.postgresql.org/docs/current/ddl-constraints.html#DDL-CONSTRAINTS-FK
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/reporting.sql` line 84 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/564#-N2NKopD0ozt9ZXO5Pwe:-N2NYVN-Dv-CuKWxtHBK:b-e0m3fc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9cb9b9b20bc33add0f66dfa2b535ba563be79c05/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/reporting.sql#L84)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This relationship is already represented in the `SetOperations` table. I don't think we want to maintain a two-way relationship, especially as this way can't have a FOREIGN KEY constraint associated with it.
</blockquote></details>

That was for storing the roots of the tree, but I could add a boolean column in SetOperations that is true if it is a root.
___
*[`src/main/proto/wfa/measurement/internal/common/macros.bzl` line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/564#-N2NPMJdC8lgGiiEXAde:-N2NXZ9FCj4QJEBGVSZ1:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9cb9b9b20bc33add0f66dfa2b535ba563be79c05/src/main/proto/wfa/measurement/internal/common/macros.bzl#L1)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Renaming the file shouldn't change copyright date.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-05-23 23:49 UTC, SanjayVas requested changes
> Reviewed 10 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/564)* status: all files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)

___
*[`src/main/resources/reporting/postgres/create-reporting-schema.sql` line 152 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/564#-N2nJXhkA3IIDa7TojJt:-N2nJXhkA3IIDa7TojJu:bgfetl8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ee8ffddc43e90eac122ef464d51cf010c89c20a8/src/main/resources/reporting/postgres/create-reporting-schema.sql#L152)):*
> ```TSQL
> 
>   -- Whether SetOperation is a root SetOperation of a Metric.
>   root boolean NOT NULL,
> ```

UpperCamelCase for column names



_Code quote:_
```TSQL
root
```


<!-- Sent from Reviewable.io -->

2022-05-24 00:07 UTC, SanjayVas requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/564)* status: all files reviewed, 4 unresolved discussions (waiting on @tristanvuong2021)

___
*[`src/main/resources/reporting/postgres/create-reporting-schema.sql` line 105 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/564#-N2nK0BA2LQa2m0IRGHm:-N2nK0BA2LQa2m0IRGHn:b-lvj6nm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ee8ffddc43e90eac122ef464d51cf010c89c20a8/src/main/resources/reporting/postgres/create-reporting-schema.sql#L105)):*
> ```TSQL
>   MeasurementReferenceId text NOT NULL,
>   ReportId bigint NOT NULL,
> ```

Do you perhaps want to cache measurement state / failure info here?

@riemanli Maybe we want an output-only field in the Report resource that shows this for each Measurement?
___
*[`src/main/resources/reporting/postgres/create-reporting-schema.sql` line 106 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/564#-N2nMMW4ERjvwbyq9I7a:-N2nMMW4ERjvwbyq9I7b:b-1lgtab) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ee8ffddc43e90eac122ef464d51cf010c89c20a8/src/main/resources/reporting/postgres/create-reporting-schema.sql#L106)):*
> ```TSQL
>   ReportId bigint NOT NULL,
> 
>   -- NULL value allowed to represent a measurement that hasn't succeeded.
> ```

Maybe add a "last synced" timestamp to indicate when we last got an update from the Kingdom.


This could be used for throttling calls to the Kingdom if we decide to implement that in the future. If adding throttling, might also need some locking mechanism with a timeout to avoid multiple in-flight checks.
___
*[`src/main/resources/reporting/postgres/create-reporting-schema.sql` line 107 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/564#-N2nKtIL9Y5al1WZzRn1:-N2nKtIL9Y5al1WZzRn2:brd12n5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ee8ffddc43e90eac122ef464d51cf010c89c20a8/src/main/resources/reporting/postgres/create-reporting-schema.sql#L107)):*
> ```TSQL
> 
>   -- NULL value allowed to represent a measurement that hasn't succeeded.
>   Result bytea,
> ```

Document what this is, e.g. what serialized type. Note that we probably don't want to store anything directly from the public API, and should instead come up with our own internal messages to represent things like results. (Otherwise we gotta keep track of the API version).



_Code quote:_
```TSQL
  Result bytea,
```


<!-- Sent from Reviewable.io -->

2022-05-24 16:19 UTC, tristanvuong2021 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/564)* status: 10 of 12 files reviewed, 4 unresolved discussions (waiting on @riemanli and @SanjayVas)

___
*[`src/main/resources/reporting/postgres/create-reporting-schema.sql` line 105 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/564#-N2nK0BA2LQa2m0IRGHm:-N2qqOJR89uq-M1Kin_Q:bu6eef6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ee8ffddc43e90eac122ef464d51cf010c89c20a8/src/main/resources/reporting/postgres/create-reporting-schema.sql#L105)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Do you perhaps want to cache measurement state / failure info here?

@riemanli Maybe we want an output-only field in the Report resource that shows this for each Measurement?
</blockquote></details>

Added state.
___
*[`src/main/resources/reporting/postgres/create-reporting-schema.sql` line 106 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/564#-N2nMMW4ERjvwbyq9I7a:-N2qqRzb1yRNEmS0vF8y:b-ja58kf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ee8ffddc43e90eac122ef464d51cf010c89c20a8/src/main/resources/reporting/postgres/create-reporting-schema.sql#L106)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Maybe add a "last synced" timestamp to indicate when we last got an update from the Kingdom.


This could be used for throttling calls to the Kingdom if we decide to implement that in the future. If adding throttling, might also need some locking mechanism with a timeout to avoid multiple in-flight checks.
</blockquote></details>

Added a timestamp for the ReportMeasurements table, although maybe this could go in the Reports table instead.
___
*[`src/main/resources/reporting/postgres/create-reporting-schema.sql` line 107 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/564#-N2nKtIL9Y5al1WZzRn1:-N2qr0o457I-FS2VmCfU:b3cimw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ee8ffddc43e90eac122ef464d51cf010c89c20a8/src/main/resources/reporting/postgres/create-reporting-schema.sql#L107)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Document what this is, e.g. what serialized type. Note that we probably don't want to store anything directly from the public API, and should instead come up with our own internal messages to represent things like results. (Otherwise we gotta keep track of the API version).
</blockquote></details>

The result is encrypted though. Should it be decrypted, transformed into our internal messages, then stored?
___
*[`src/main/resources/reporting/postgres/create-reporting-schema.sql` line 152 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/564#-N2nJXhkA3IIDa7TojJt:-N2qr-jyAmIAdCTUeFg3:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ee8ffddc43e90eac122ef464d51cf010c89c20a8/src/main/resources/reporting/postgres/create-reporting-schema.sql#L152)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

UpperCamelCase for column names
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-05-24 19:41 UTC, SanjayVas requested changes
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/564)* status: all files reviewed, 4 unresolved discussions (waiting on @riemanli and @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/internal/reporting/report.proto` line 74 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/564#-N2rYNLD7n4P9_2xp5Vn:-N2rYNLE0QIurlMofIST:b-ol0182) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/52340f9d2f6138e75fb66ecc60ce9b1e26983d69/src/main/proto/wfa/measurement/internal/reporting/report.proto#L74)):*
> ```protobuf
>     enum State {
>       STATE_UNSPECIFIED = 0;
>       IN_PROGRESS = 1;
> ```

nit: maybe `PENDING` to mirror what we'd do in the public reporting API.

See https://google.aip.dev/216#active-states



_Code quote:_
```protobuf
IN_PROGRESS
```
___
*[`src/main/proto/wfa/measurement/internal/reporting/reports_service.proto` line 1 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/564#-N2r3EwT5JwZyYHkQB8p:-N2rYkeJ7b71BvpK1NRK:bkaiq54) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/51c5fb3a6ca6b5aa4cc54010df1288451766b78b/src/main/proto/wfa/measurement/internal/reporting/reports_service.proto#L1)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Added a new method.
</blockquote></details>

The internal services should just wrap the DB. It doesn't do any calls to other APIs, as that should be done by the public services. Therefore, a "refresh" method wouldn't work. You'd instead need methods that do simple CRUD.
___
*[`src/main/resources/reporting/postgres/create-reporting-schema.sql` line 107 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/564#-N2nKtIL9Y5al1WZzRn1:-N2r_TpmCcVY-3XHMZGL:bb77ufg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ee8ffddc43e90eac122ef464d51cf010c89c20a8/src/main/resources/reporting/postgres/create-reporting-schema.sql#L107)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

The result is encrypted though. Should it be decrypted, transformed into our internal messages, then stored?
</blockquote></details>

Yes.
___
*[`src/main/resources/reporting/postgres/create-reporting-schema.sql` line 112 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/564#-N2rZvDq3mynJM4TZLlG:-N2rZvDq3mynJM4TZLlH:b4kevhr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/52340f9d2f6138e75fb66ecc60ce9b1e26983d69/src/main/resources/reporting/postgres/create-reporting-schema.sql#L112)):*
> ```TSQL
>   Result bytea,
>   -- Timestamp in UTC.
>   LastSynced timestamptz NOT NULL,
> ```

I don't think we want to worry about timezones here, and just implicitly use UTC.



_Code quote:_
```TSQL
timestamptz
```


<!-- Sent from Reviewable.io -->

2022-05-24 19:48 UTC, tristanvuong2021 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/564)* status: 11 of 12 files reviewed, 4 unresolved discussions (waiting on @riemanli, @SanjayVas, and @tristanvuong2021)

___
*[`src/main/resources/reporting/postgres/create-reporting-schema.sql` line 112 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/564#-N2rZvDq3mynJM4TZLlG:-N2rb28y4dkVAyFk9B-0:b-lqo4r5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/52340f9d2f6138e75fb66ecc60ce9b1e26983d69/src/main/resources/reporting/postgres/create-reporting-schema.sql#L112)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I don't think we want to worry about timezones here, and just implicitly use UTC.
</blockquote></details>

This type interprets the timestamp as UTC. Timestamps are stored the same either way.


<!-- Sent from Reviewable.io -->

2022-05-24 20:10 UTC, tristanvuong2021 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/564)* status: 9 of 12 files reviewed, 3 unresolved discussions (waiting on @riemanli and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/internal/reporting/reports_service.proto` line 1 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/564#-N2r3EwT5JwZyYHkQB8p:-N2rgHdF9SpWQOXA2Aij:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/51c5fb3a6ca6b5aa4cc54010df1288451766b78b/src/main/proto/wfa/measurement/internal/reporting/reports_service.proto#L1)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The internal services should just wrap the DB. It doesn't do any calls to other APIs, as that should be done by the public services. Therefore, a "refresh" method wouldn't work. You'd instead need methods that do simple CRUD.
</blockquote></details>

Done.
___
*[`src/main/resources/reporting/postgres/create-reporting-schema.sql` line 107 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/564#-N2nKtIL9Y5al1WZzRn1:-N2rgKaD5n-DsbPNGnhX:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ee8ffddc43e90eac122ef464d51cf010c89c20a8/src/main/resources/reporting/postgres/create-reporting-schema.sql#L107)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Yes.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-05-24 23:07 UTC, SanjayVas requested changes
> Reviewed 3 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/564)* status: all files reviewed, 2 unresolved discussions (waiting on @riemanli and @tristanvuong2021)

___
*[`src/main/resources/reporting/postgres/create-reporting-schema.sql` line 112 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/564#-N2rZvDq3mynJM4TZLlG:-N2sIXqIBTQMU1hKdFch:b-gaadr3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/52340f9d2f6138e75fb66ecc60ce9b1e26983d69/src/main/resources/reporting/postgres/create-reporting-schema.sql#L112)):*
From https://www.postgresql.org/docs/current/datatype-datetime.html:
> timestamptz is accepted as an abbreviation for timestamp with time zone; this is a PostgreSQL extension.

I assume we want just `timestamp`, which is "timestamp without timezone".
___
*[`src/main/resources/reporting/postgres/create-reporting-schema.sql` line 101 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/564#-N2sJ8ys-wMrnqAIZpZI:-N2sJ8yt7YGh7zw-A1ED:b-uzjdxy) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/453c9ddf1edda1cb7a8577bdfd1144284e0cad84/src/main/resources/reporting/postgres/create-reporting-schema.sql#L101)):*
> ```TSQL
> 
> -- changeset tristanvuong2021:create-report-measurements-table dbms:postgresql
> CREATE TABLE ReportMeasurements (
> ```

Can't a single measurement be shared by multiple reports from the same MC? If so, we'd need a separate `Measurements` table and use this table to represent the many:many relationship.


<!-- Sent from Reviewable.io -->

2022-05-24 23:46 UTC, tristanvuong2021 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/564)* status: 11 of 12 files reviewed, 2 unresolved discussions (waiting on @riemanli and @SanjayVas)

___
*[`src/main/resources/reporting/postgres/create-reporting-schema.sql` line 112 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/564#-N2rZvDq3mynJM4TZLlG:-N2sRyjL-GyENlYO-Aqw:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/52340f9d2f6138e75fb66ecc60ce9b1e26983d69/src/main/resources/reporting/postgres/create-reporting-schema.sql#L112)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

From https://www.postgresql.org/docs/current/datatype-datetime.html:
> timestamptz is accepted as an abbreviation for timestamp with time zone; this is a PostgreSQL extension.

I assume we want just `timestamp`, which is "timestamp without timezone".
</blockquote></details>

Done.
___
*[`src/main/resources/reporting/postgres/create-reporting-schema.sql` line 101 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/564#-N2sJ8ys-wMrnqAIZpZI:-N2sSfB280iC5z5eGjIE:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/453c9ddf1edda1cb7a8577bdfd1144284e0cad84/src/main/resources/reporting/postgres/create-reporting-schema.sql#L101)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Can't a single measurement be shared by multiple reports from the same MC? If so, we'd need a separate `Measurements` table and use this table to represent the many:many relationship.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-05-25 18:56 UTC, SanjayVas requested changes
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/564)* status: all files reviewed, 2 unresolved discussions (waiting on @riemanli and @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/internal/reporting/reports_service.proto` line 52 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/564#-N2wZEgJ1mK5eexPyTpT:-N2wZEgJ1mK5eexPyTpU:b6pcrue) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e0692cef02834c8737cb61d914b3772c679d5abb/src/main/proto/wfa/measurement/internal/reporting/reports_service.proto#L52)):*
> ```protobuf
> }
> 
> message UpdateReportMeasurementRequest {
> ```

Since Measurements can be shared across reports, this should be an `UpdateMeasurementRequest` that doesn't take in a `report_id`. Calling this method may result in the state of one or more `Report`s changing.

You may want to split out Measurement as its own entity rather than `MeasurementInfo` in `Report`, creating a separate service.
___
*[`src/main/resources/reporting/postgres/create-reporting-schema.sql` line 127 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/564#-N2wZ51e2srZAM9jd5qn:-N2wZ51e2srZAM9jd5qo:bbfoou3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e0692cef02834c8737cb61d914b3772c679d5abb/src/main/resources/reporting/postgres/create-reporting-schema.sql#L127)):*
> ```TSQL
>   FOREIGN KEY(MeasurementConsumerReferenceId, ReportId)
>       REFERENCES Reports(MeasurementConsumerReferenceId, ReportId),
>   FOREIGN KEY(MeasurementConsumerReferenceId, MeasurementConsumerReferenceId)
> ```

`MeasurementReferenceId`



_Code quote:_
```TSQL
MeasurementConsumerReferenceId
```


<!-- Sent from Reviewable.io -->

2022-05-25 21:08 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/564)* status: all files reviewed, 2 unresolved discussions (waiting on @tristanvuong2021)

___
*[`src/main/resources/reporting/postgres/create-reporting-schema.sql` line 105 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/564#-N2nK0BA2LQa2m0IRGHm:-N2x-lRJ9yOaMEWWROiH:bbo2djr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ee8ffddc43e90eac122ef464d51cf010c89c20a8/src/main/resources/reporting/postgres/create-reporting-schema.sql#L105)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Added state.
</blockquote></details>

@sanjayvas Do you mean `Report` contains the results of all measurement requests that are needed to form the report itself? If so, I think we can show only the failed measurement requests, so the measurement consumer can see which measurement requests caused the report creation failed. WDYT?


<!-- Sent from Reviewable.io -->

2022-05-25 21:41 UTC, SanjayVas reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/564)* status: all files reviewed, 2 unresolved discussions (waiting on @tristanvuong2021)

___
*[`src/main/resources/reporting/postgres/create-reporting-schema.sql` line 105 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/564#-N2nK0BA2LQa2m0IRGHm:-N2x8n9d7enWhRlmPMWn:b-ugfr4y) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ee8ffddc43e90eac122ef464d51cf010c89c20a8/src/main/resources/reporting/postgres/create-reporting-schema.sql#L105)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

@sanjayvas Do you mean `Report` contains the results of all measurement requests that are needed to form the report itself? If so, I think we can show only the failed measurement requests, so the measurement consumer can see which measurement requests caused the report creation failed. WDYT?
</blockquote></details>

Yes, we should probably update the `Report` message in the public API to contain failed measurement info. This isn't strictly required, but a nice-to-have. Right now I'm mostly concerned with at least having the data available in the DB so we can make that API change.


<!-- Sent from Reviewable.io -->

2022-05-25 22:23 UTC, riemanli commented
*[`src/main/resources/reporting/postgres/create-reporting-schema.sql` line 105 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/564#-N2nK0BA2LQa2m0IRGHm:-N2xIV4r9GwGIja8Oq2D:b2rwvuh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ee8ffddc43e90eac122ef464d51cf010c89c20a8/src/main/resources/reporting/postgres/create-reporting-schema.sql#L105)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Yes, we should probably update the `Report` message in the public API to contain failed measurement info. This isn't strictly required, but a nice-to-have. Right now I'm mostly concerned with at least having the data available in the DB so we can make that API change.
</blockquote></details>

Got it. I agree it's a nice-to-have feature. 


<!-- Sent from Reviewable.io -->

2022-05-26 02:26 UTC, tristanvuong2021 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/564)* status: 8 of 14 files reviewed, 2 unresolved discussions (waiting on @riemanli and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/internal/reporting/reports_service.proto` line 52 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/564#-N2wZEgJ1mK5eexPyTpT:-N2yAv234aNRdabto_9W:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e0692cef02834c8737cb61d914b3772c679d5abb/src/main/proto/wfa/measurement/internal/reporting/reports_service.proto#L52)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Since Measurements can be shared across reports, this should be an `UpdateMeasurementRequest` that doesn't take in a `report_id`. Calling this method may result in the state of one or more `Report`s changing.

You may want to split out Measurement as its own entity rather than `MeasurementInfo` in `Report`, creating a separate service.
</blockquote></details>

Done.
___
*[`src/main/resources/reporting/postgres/create-reporting-schema.sql` line 127 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/564#-N2wZ51e2srZAM9jd5qn:-N2yAxcCCZ9U1ZORzC93:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e0692cef02834c8737cb61d914b3772c679d5abb/src/main/resources/reporting/postgres/create-reporting-schema.sql#L127)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

`MeasurementReferenceId`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-05-26 19:32 UTC, tristanvuong2021 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/564)* status: 12 of 14 files reviewed, 2 unresolved discussions (waiting on @SanjayVas and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/internal/reporting/measurements_service.proto` line 45 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/564#-N30crhTDNKSp05XPCvX:-N30qie9DShNGw1Hr1Uz:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/75e2a734d06aaadf42ee58a038f13432ac74b5ce/src/main/proto/wfa/measurement/internal/reporting/measurements_service.proto#L45)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Actually, having separate methods for the two state transitions would be cleaner, as the result should only be set when transitioning to `SUCCEEDED` and the failure info only if transitioning to `FAILED`.

Maybe `SucceedMeasurement`/`FailMeasurement` or `SetMeasurementResult`/`SetMeasurementFailure`?
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/internal/reporting/report.proto` line 67 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/564#-N30dhYjDMaJDKSeXUog:-N30qkD16fVLAFjiOi93:bfseo3g) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/75e2a734d06aaadf42ee58a038f13432ac74b5ce/src/main/proto/wfa/measurement/internal/reporting/report.proto#L67)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: indicate that this is output-only.
</blockquote></details>

I was thinking this actually wouldn't be output-only since the measurements used in the report need to be set on initial report creation.


<!-- Sent from Reviewable.io -->

2022-05-26 19:34 UTC, tristanvuong2021 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/564)* status: 12 of 14 files reviewed, 2 unresolved discussions (waiting on @SanjayVas and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/internal/reporting/report.proto` line 67 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/564#-N30dhYjDMaJDKSeXUog:-N30r7pB7iFfxMD86gmz:bvqeatz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/75e2a734d06aaadf42ee58a038f13432ac74b5ce/src/main/proto/wfa/measurement/internal/reporting/report.proto#L67)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

I was thinking this actually wouldn't be output-only since the measurements used in the report need to be set on initial report creation.
</blockquote></details>

Think I will make this output-only, but add a new field to the create request that is just a list of ids.


<!-- Sent from Reviewable.io -->

2022-05-26 23:54 UTC, SanjayVas requested changes
> Reviewed 1 of 2 files at r11, 2 of 2 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/564)* status: all files reviewed, 2 unresolved discussions (waiting on @stevenwarejones and @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/internal/reporting/measurements_service.proto` line 53 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/564#-N31mWG41O6b9QMnD2eT:-N31mWG41O6b9QMnD2eU:brkbokd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/012eb467c4102f9e092896f9e4dd7cd2957dfd30/src/main/proto/wfa/measurement/internal/reporting/measurements_service.proto#L53)):*
> ```protobuf
>   string measurement_reference_id = 2;
> 
>   Measurement.State state = 3;
> ```

Leave state out, as it's implied to be SUCCEEDED.



_Code quote:_
```protobuf
  Measurement.State state = 3;
```
___
*[`src/main/proto/wfa/measurement/internal/reporting/measurements_service.proto` line 63 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/564#-N31mZBn3X3zvEgLkq-U:-N31mZBn3X3zvEgLkq-V:b-bir67b) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/012eb467c4102f9e092896f9e4dd7cd2957dfd30/src/main/proto/wfa/measurement/internal/reporting/measurements_service.proto#L63)):*
> ```protobuf
>   string measurement_reference_id = 2;
> 
>   Measurement.State state = 3;
> ```

Ditto, but FAILED.



_Code quote:_
```protobuf
  Measurement.State state = 3;
```


<!-- Sent from Reviewable.io -->

2022-05-27 00:12 UTC, tristanvuong2021 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/564)* status: 13 of 14 files reviewed, 2 unresolved discussions (waiting on @SanjayVas and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/internal/reporting/measurements_service.proto` line 53 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/564#-N31mWG41O6b9QMnD2eT:-N31qxMOBasGHDgZBB6z:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/012eb467c4102f9e092896f9e4dd7cd2957dfd30/src/main/proto/wfa/measurement/internal/reporting/measurements_service.proto#L53)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Leave state out, as it's implied to be SUCCEEDED.
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/internal/reporting/measurements_service.proto` line 63 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/564#-N31mZBn3X3zvEgLkq-U:-N31qxtKBCpORaPtYfwy:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/012eb467c4102f9e092896f9e4dd7cd2957dfd30/src/main/proto/wfa/measurement/internal/reporting/measurements_service.proto#L63)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Ditto, but FAILED.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-05-27 18:08 UTC, SanjayVas approved these changes
> Reviewed 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/564)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)



<!-- Sent from Reviewable.io -->

2022-05-31 20:41 UTC, tristanvuong2021 reviewed
No, this is the full design.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/564#-:-N3QqRBH153hlnbAHysr:bjcxo)* status: 12 of 14 files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/internal/reporting/measurements_service.proto` line 51 at r14](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/564#-N3QkSaT-n_Gq-8WLIIs:-N3QpkfG4XRhIBnhUArr:b-jzhja5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7b67cf7c73abdad43dde50a91a9ebe7223db0a8a/src/main/proto/wfa/measurement/internal/reporting/measurements_service.proto#L51)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

doesn't a Measurement already reference a specific MC already? Why do we need to specify it here?
</blockquote></details>

It is not the full resource name. The measurement consumer reference id just contains the measurement consumer part and the measurement reference id just contains the measurement part.


<!-- Sent from Reviewable.io -->

2022-06-02 16:21 UTC, stevenwarejones requested changes
> Reviewed 5 of 10 files at r2, 2 of 2 files at r12, 2 of 2 files at r14.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/564)* status: all files reviewed, 2 unresolved discussions (waiting on @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/internal/reporting/metric.proto` line 29 at r14](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/564#-N3_BNWUCYvDNo3rlRyV:-N3_BNWUCYvDNo3rlRyW:b-cd0tm3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e43f6a2a3ce0c9afc0e68ddd14da55d8cd319500/src/main/proto/wfa/measurement/internal/reporting/metric.proto#L29)):*
> ```protobuf
>   }
>   message ImpressionCountParams {}
>   message WatchDurationParams {}
> ```

doesn't this need max_watch_duration?
___
*[`src/main/proto/wfa/measurement/internal/reporting/report.proto` line 76 at r14](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/564#-N3_Bedr8of5L4CWIHG_:-N3_Bedr8of5L4CWIHGa:b51j7gv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e43f6a2a3ce0c9afc0e68ddd14da55d8cd319500/src/main/proto/wfa/measurement/internal/reporting/report.proto#L76)):*
> ```protobuf
> 
>     // Result in CSV format. Set only when `state` is `SUCCEEDED`. Output-only.
>     string result = 2;
> ```

why the decision to use csv here?


<!-- Sent from Reviewable.io -->

2022-06-02 17:52 UTC, stevenwarejones requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/564)* status: all files reviewed, 2 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/internal/reporting/report.proto` line 76 at r14](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/564#-N3_Bedr8of5L4CWIHG_:-N3_Y0bLBFebW2ZEf98C:b-b26a3r) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e43f6a2a3ce0c9afc0e68ddd14da55d8cd319500/src/main/proto/wfa/measurement/internal/reporting/report.proto#L76)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This comes from requirements docs such as [Halo PRD: Reporting](https://docs.google.com/document/d/1mU1TZon8moODiVA3R89yUBGpnOt_wytPcupZkHsdIws/edit?usp=sharing).

That said, I've recommended having a proto representation internally that we convert to CSV on-demand.
</blockquote></details>

yeah - that's the funny part to me. Feels like it should stay proto internally and only be converted to csv on the external API, right?


<!-- Sent from Reviewable.io -->

2022-06-02 19:01 UTC, riemanli commented
*[`src/main/proto/wfa/measurement/internal/reporting/metric.proto` line 68 at r14](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/564#-N3_krruEPGH4ocZZtuc:-N3_krruEPGH4ocZZtud:bd669d7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e43f6a2a3ce0c9afc0e68ddd14da55d8cd319500/src/main/proto/wfa/measurement/internal/reporting/metric.proto#L68)):*
> ```protobuf
>     Operand rhs = 3;
> 
>     string display_name = 4;
> ```

Is this the replacement of `NamedSetOperation.display_name` in the external reporting API?  Is `display_name` of the top-level set operation the only one being set?


<!-- Sent from Reviewable.io -->

2022-06-06 16:40 UTC, tristanvuong2021 commented
*[`src/main/proto/wfa/measurement/internal/reporting/metric.proto` line 68 at r14](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/564#-N3_krruEPGH4ocZZtuc:-N3tsrjW8Ngy8fEJiKgS:b-a7gy4b) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5089007707c5b22dbb065bd9494efd84a766286a/src/main/proto/wfa/measurement/internal/reporting/metric.proto#L68)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Is this the replacement of `NamedSetOperation.display_name` in the external reporting API?  Is `display_name` of the top-level set operation the only one being set?
</blockquote></details>

I changed it now.


<!-- Sent from Reviewable.io -->

2022-06-06 16:40 UTC, tristanvuong2021 commented
*[`src/main/proto/wfa/measurement/internal/reporting/report.proto` line 76 at r14](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/564#-N3_Bedr8of5L4CWIHG_:-N3tsux-2PKaQHKEQ4p-:b-ql5uxf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5089007707c5b22dbb065bd9494efd84a766286a/src/main/proto/wfa/measurement/internal/reporting/report.proto#L76)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

yeah - that's the funny part to me. Feels like it should stay proto internally and only be converted to csv on the external API, right?
</blockquote></details>

Created a result proto.


<!-- Sent from Reviewable.io -->

2022-06-06 16:46 UTC, tristanvuong2021 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/564)* status: 9 of 14 files reviewed, 3 unresolved discussions (waiting on @riemanli, @SanjayVas, and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/internal/reporting/metric.proto` line 29 at r14](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/564#-N3_BNWUCYvDNo3rlRyV:-N3tuAVQE1DdFiLiio6e:b-6xrxoj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5089007707c5b22dbb065bd9494efd84a766286a/src/main/proto/wfa/measurement/internal/reporting/metric.proto#L29)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

doesn't this need max_watch_duration?
</blockquote></details>

I am not sure, right now it doesn't seem like a 1 to 1 between the public reporting version of the messages here and the measurement spec. I need to clarify.


<!-- Sent from Reviewable.io -->

2022-06-06 19:57 UTC, stevenwarejones requested changes
> Reviewed 1 of 5 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/564)* status: 10 of 14 files reviewed, 3 unresolved discussions (waiting on @riemanli, @SanjayVas, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/internal/reporting/report.proto` line 76 at r14](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/564#-N3_Bedr8of5L4CWIHG_:-N3u_z_r-kk0jiZaiLle:b-59belh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5089007707c5b22dbb065bd9494efd84a766286a/src/main/proto/wfa/measurement/internal/reporting/report.proto#L76)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Created a result proto.
</blockquote></details>

why not just have a proto message that represents each row of the csv and then repeat that message for the internal representation of the csv?


<!-- Sent from Reviewable.io -->

2022-06-06 21:10 UTC, stevenwarejones reviewed
> Reviewed 2 of 5 files at r15, 1 of 1 files at r20.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/564)* status: 13 of 14 files reviewed, 3 unresolved discussions (waiting on @riemanli, @SanjayVas, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/internal/reporting/report.proto` line 76 at r14](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/564#-N3_Bedr8of5L4CWIHG_:-N3uqaDbECphmeWcixXX:buxxn3d) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5089007707c5b22dbb065bd9494efd84a766286a/src/main/proto/wfa/measurement/internal/reporting/report.proto#L76)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

@stevenwarejones I initially decided on a list of rows, but switched to columns because it matches the way calculations are done on a list of set operations for a metric, which is by columns. Seems easier to create the result that way if the proto is a list of columns as well.
</blockquote></details>

can you add that as a comment?


<!-- Sent from Reviewable.io -->

2022-06-06 23:07 UTC, tristanvuong2021 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/564)* status: 12 of 14 files reviewed, 2 unresolved discussions (waiting on @riemanli, @SanjayVas, and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/internal/reporting/metric.proto` line 29 at r14](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/564#-N3_BNWUCYvDNo3rlRyV:-N3vGU3j8ktHixe8XoRJ:bxxiui2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5089007707c5b22dbb065bd9494efd84a766286a/src/main/proto/wfa/measurement/internal/reporting/metric.proto#L29)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

I am not sure, right now it doesn't seem like a 1 to 1 between the public reporting version of the messages here and the measurement spec. I need to clarify.
</blockquote></details>

Updated here. Will need to update the measurement spec as well.


<!-- Sent from Reviewable.io -->

2022-06-06 23:23 UTC, riemanli reviewed
> Reviewed 1 of 2 files at r21, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/564)* status: 13 of 14 files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/internal/reporting/metric.proto` line 29 at r14](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/564#-N3_BNWUCYvDNo3rlRyV:-N3vK-Gn3_j-LXfN612g:b-24zy6g) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5089007707c5b22dbb065bd9494efd84a766286a/src/main/proto/wfa/measurement/internal/reporting/metric.proto#L29)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Updated here. Will need to update the measurement spec as well.
</blockquote></details>

Based on Matthew's feedback, I think `maximum_frequency_per_user` should be added to `WatchDurationParams`.


<!-- Sent from Reviewable.io -->

2022-06-07 00:27 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/564)* status: 13 of 14 files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/internal/reporting/metric.proto` line 29 at r14](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/564#-N3_BNWUCYvDNo3rlRyV:-N3vYP-c5inYyljVzRJu:b-c2n5js) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5089007707c5b22dbb065bd9494efd84a766286a/src/main/proto/wfa/measurement/internal/reporting/metric.proto#L29)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Based on Matthew's feedback, I think `maximum_frequency_per_user` should be added to `WatchDurationParams`.
</blockquote></details>

Note that `maximum_watch_duration` = `maximum_frequency_per_user` * `maximum_watch_duration_per_user`


<!-- Sent from Reviewable.io -->

2022-06-07 20:13 UTC, tristanvuong2021 commented
*[`src/main/proto/wfa/measurement/internal/reporting/metric.proto` line 76 at r22](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/564#-N3zjan41QSWjczDF0Mq:-N3zmph-75hiXfCO5vCZ:b-bb91sv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/173d2aabf43797333ba8c5929cc981f229183365/src/main/proto/wfa/measurement/internal/reporting/metric.proto#L76)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I'm not super keen on referring to "row" here. Where does this name come from?
</blockquote></details>

It is the name of the row that the data will be in the resultst able.


<!-- Sent from Reviewable.io -->

2022-06-07 20:33 UTC, stevenwarejones approved these changes
> Reviewed 1 of 2 files at r21, 1 of 1 files at r22, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/564)* status: all files reviewed, 3 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/internal/reporting/report.proto` line 83 at r22](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/564#-N3zcHgc4MBT-iD4cyzm:-N3zrhW36nghK9fdhou4:b32v57) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/173d2aabf43797333ba8c5929cc981f229183365/src/main/proto/wfa/measurement/internal/reporting/report.proto#L83)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: maybe "header" instead of "name" to match what this is commonly called in spreadsheet apps
</blockquote></details>

+1


<!-- Sent from Reviewable.io -->

2022-06-07 21:14 UTC, SanjayVas requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/564)* status: all files reviewed, 3 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/internal/reporting/metric.proto` line 76 at r22](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/564#-N3zjan41QSWjczDF0Mq:-N4--1jhBLhK1eIjh6xm:bh2pv0e) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/173d2aabf43797333ba8c5929cc981f229183365/src/main/proto/wfa/measurement/internal/reporting/metric.proto#L76)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

It is the name of the row that the data will be in the resultst able.
</blockquote></details>

Right, but where does that row name come from? I'm guessing for scalar set operations, one axis uses the NamedSetOperation display_name for headers. Where do the other axis headers come from? Do we need a display_name on Metric?

For histograms, I assume the histogram values give you that axis.


<!-- Sent from Reviewable.io -->

2022-06-07 21:18 UTC, tristanvuong2021 commented
*[`src/main/proto/wfa/measurement/internal/reporting/metric.proto` line 76 at r22](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/564#-N3zjan41QSWjczDF0Mq:-N4-0tlx48RgZc_itdW1:buy0d41) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/173d2aabf43797333ba8c5929cc981f229183365/src/main/proto/wfa/measurement/internal/reporting/metric.proto#L76)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Right, but where does that row name come from? I'm guessing for scalar set operations, one axis uses the NamedSetOperation display_name for headers. Where do the other axis headers come from? Do we need a display_name on Metric?

For histograms, I assume the histogram values give you that axis.
</blockquote></details>

Oh, the row names are from the report time intervals.


<!-- Sent from Reviewable.io -->

2022-06-07 21:46 UTC, SanjayVas requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/564)* status: all files reviewed, 4 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/internal/reporting/metric.proto` line 76 at r22](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/564#-N3zjan41QSWjczDF0Mq:-N4-6Mqe0gye_wZtVr1s:bkzmvvb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/173d2aabf43797333ba8c5929cc981f229183365/src/main/proto/wfa/measurement/internal/reporting/metric.proto#L76)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Oh, the row names are from the report time intervals.
</blockquote></details>

Gotcha. Is this also true for histograms? If not, can we have this explicitly be a time interval instead?
___
*[`src/main/proto/wfa/measurement/internal/reporting/metric.proto` line 86 at r22](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/564#-N4-7GGIA3HCDA1Mfe-J:-N4-7GGIA3HCDA1Mfe-K:b-f5vlvd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/173d2aabf43797333ba8c5929cc981f229183365/src/main/proto/wfa/measurement/internal/reporting/metric.proto#L86)):*
> ```protobuf
>   }
> 
>   message SetOperationCalculation {
> ```

Why not just `NamedSetOperation` like the public API? No need to change the name just because it contains extra fields.



_Code quote:_
```protobuf
SetOperationCalculation
```


<!-- Sent from Reviewable.io -->

2022-06-07 22:10 UTC, riemanli approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/564)* status: all files reviewed, 4 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/internal/reporting/metric.proto` line 76 at r22](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/564#-N3zjan41QSWjczDF0Mq:-N4-As6_C7XnmudQVxrF:b-jrbr0l) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/173d2aabf43797333ba8c5929cc981f229183365/src/main/proto/wfa/measurement/internal/reporting/metric.proto#L76)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Gotcha. Is this also true for histograms? If not, can we have this explicitly be a time interval instead?
</blockquote></details>

FYI, the report formulation for scalar tables currently is designed as
```
Time               metric_display_name1        metric_display_name2 ...
"01/01-01/02"      <some value>                <some value>
"01/02-01/03"      <some value>                <some value>
...
"01/30-01/31"      <some value>                <some value>
```

And for histogram
```
Time               frequency  metric_display_name1        metric_display_name2 ...
"01/01-01/02"          1      <some value>                <some value>
"01/01-01/02"          2      <some value>                <some value>
...
"01/02-01/03"          1      <some value>                <some value>
"01/02-01/03"          2      <some value>                <some value>
...
```
___
*[`src/main/proto/wfa/measurement/internal/reporting/metric.proto` line 86 at r22](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/564#-N4-7GGIA3HCDA1Mfe-J:-N4-CctJ3J93I3HzSapU:b-ba7jcz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/173d2aabf43797333ba8c5929cc981f229183365/src/main/proto/wfa/measurement/internal/reporting/metric.proto#L86)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Why not just `NamedSetOperation` like the public API? No need to change the name just because it contains extra fields.
</blockquote></details>

Sounds good to me.


<!-- Sent from Reviewable.io -->

2022-06-07 22:56 UTC, tristanvuong2021 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/564)* status: 11 of 14 files reviewed, 3 unresolved discussions (waiting on @riemanli, @SanjayVas, and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/internal/reporting/metric.proto` line 86 at r22](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/564#-N4-7GGIA3HCDA1Mfe-J:-N4-N_9fAzwPOCfgVIiI:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ece54b40cb2831a1620e55ca9ec028f241024c09/src/main/proto/wfa/measurement/internal/reporting/metric.proto#L86)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Sounds good to me.
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/internal/reporting/report.proto` line 83 at r22](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/564#-N3zczC7EX4PaTsTgY1R:-N4-NXvCBxYxKkg2alzt:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ece54b40cb2831a1620e55ca9ec028f241024c09/src/main/proto/wfa/measurement/internal/reporting/report.proto#L83)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Do these need to be maps? A `repeated` in proto3 effectively maps to a list, which is already an ordered, indexed collection. The main reason to use a `map` instead is e.g. if it's sparse or the indices are not integers.

Basically a table is a matrix, or a list of lists. You can either have a list of rows where each row has a list of columns, or vice-versa. The headers are a special row and column that get split out to avoid repeating them on whichever list is the nested one.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-06-08 22:11 UTC, SanjayVas requested changes
> Reviewed 2 of 3 files at r23, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/564)* status: 13 of 14 files reviewed, 2 unresolved discussions (waiting on @riemanli, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/internal/reporting/metric.proto` line 76 at r22](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/564#-N3zjan41QSWjczDF0Mq:-N44LjZ23Z1Dc57tAc4w:bu6f8dq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ece54b40cb2831a1620e55ca9ec028f241024c09/src/main/proto/wfa/measurement/internal/reporting/metric.proto#L76)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

FYI, the report formulation for scalar tables currently is designed as
```
Time               metric_display_name1        metric_display_name2 ...
"01/01-01/02"      <some value>                <some value>
"01/02-01/03"      <some value>                <some value>
...
"01/030-01/31"      <some value>                <some value>
```

And for histogram
```
Time               frequency  metric_display_name1        metric_display_name2 ...
"01/01-01/02"          1      <some value>                <some value>
"01/01-01/02"          2      <some value>                <some value>
...
"01/02-01/03"          1      <some value>                <some value>
"01/02-01/03"          2      <some value>                <some value>
...
```
</blockquote></details>

Thanks for the info.

In light of that, I think that this should indeed be a time interval. We can hold off on converting to a row header until we build the final result. Everything here should avoid the terminology used for the result tables.
___
*[`src/main/resources/reporting/postgres/create-reporting-schema.sql` line 90 at r23](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/564#-N44MekfBbFDgPiI8-uP:-N44Mekg9w16ANm81YNU:b-38cp2m) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2f748c72e5b066b1174bf3b146b4c894ca19d948/src/main/resources/reporting/postgres/create-reporting-schema.sql#L90)):*
> ```TSQL
> 
> -- changeset tristanvuong2021:create-row-names-table dbms:postgresql
> CREATE TABLE RowNames (
> ```

Can we find a better way to describe this than referring to the output row. You stated above that each of these corresponds to a time interval?



_Code quote:_
```TSQL
RowNames 
```


<!-- Sent from Reviewable.io -->

2022-06-09 00:07 UTC, tristanvuong2021 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/564)* status: 10 of 15 files reviewed, 2 unresolved discussions (waiting on @riemanli, @SanjayVas, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/internal/reporting/metric.proto` line 76 at r22](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/564#-N3zjan41QSWjczDF0Mq:-N44mSLzA2QgG9jV5TAM:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ece54b40cb2831a1620e55ca9ec028f241024c09/src/main/proto/wfa/measurement/internal/reporting/metric.proto#L76)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Thanks for the info.

In light of that, I think that this should indeed be a time interval. We can hold off on converting to a row header until we build the final result. Everything here should avoid the terminology used for the result tables.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-06-09 16:30 UTC, tristanvuong2021 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/564)* status: 10 of 15 files reviewed, 2 unresolved discussions (waiting on @riemanli, @SanjayVas, and @stevenwarejones)

___
*[`src/main/resources/reporting/postgres/create-reporting-schema.sql` line 90 at r23](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/564#-N44MekfBbFDgPiI8-uP:-N48IG3MDtEjhEBb3UTX:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2f748c72e5b066b1174bf3b146b4c894ca19d948/src/main/resources/reporting/postgres/create-reporting-schema.sql#L90)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Can we find a better way to describe this than referring to the output row. You stated above that each of these corresponds to a time interval?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-06-09 17:47 UTC, merged