Simple Report CLI tool
world-federation-of-advertisers/cross-media-measurement pull request #571
Opened 2022-05-20 21:12 UTC by renjiezh

2022-05-23 23:44 UTC, SanjayVas requested changes
> Reviewed 1 of 5 files at r1, 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/571)* status: 2 of 6 files reviewed, 6 unresolved discussions (waiting on @renjiezh, @riemanli, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/tools/SimpleReport.kt` line 90 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/571#-N2nE22pDwdugLXZXMTA:-N2nE22pDwdugLXZXMTB:bgc5iwj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/322e86a4ef04cbfd59d85e0df07626f31eb4b3c4/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/tools/SimpleReport.kt#L90)):*
> ```Kotlin
> 
>   @CommandLine.Option(
>     names = ["--measurement-consumer-name"],
> ```

nit: Leave off `-name` to more closely match the API (here and on similar options)



_Code quote:_
```Kotlin
-name
```
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/tools/SimpleReport.kt` line 138 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/571#-N2nGG9j-VIOKNP5vg7D:-N2nGG9j-VIOKNP5vg7E:b-2mhecl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/322e86a4ef04cbfd59d85e0df07626f31eb4b3c4/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/tools/SimpleReport.kt#L138)):*
> ```Kotlin
> 
>     @CommandLine.Option(
>       names = ["--event-filter-start-time"],
> ```

This has nothing to do with the filter



_Code quote:_
```Kotlin
-filter
```
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/tools/SimpleReport.kt` line 140 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/571#-N2nG3jd2UTskATrqpTS:-N2nG3jd2UTskATrqpTT:bej87ra) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/322e86a4ef04cbfd59d85e0df07626f31eb4b3c4/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/tools/SimpleReport.kt#L140)):*
> ```Kotlin
>       names = ["--event-filter-start-time"],
>       description = ["Start time of EventFilter range"],
>       required = false,
> ```

Time interval is required.



_Code quote:_
```Kotlin
required = false,
```
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/tools/SimpleReport.kt` line 142 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/571#-N2nGlDe0McV2YVeH1gp:-N2nGlDe0McV2YVeH1gq:bmag7u5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/322e86a4ef04cbfd59d85e0df07626f31eb4b3c4/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/tools/SimpleReport.kt#L142)):*
> ```Kotlin
>       required = false,
>     )
>     var eventFilterStartTime: Long = 0L
> ```

Use a more appropriate data time (e.g. `Instant`).

We also shouldn't make the user mess with epoch time and instead use human-readable strings. Picocli has a [built-in converter](https://picocli.info/#_built_in_types) for this that calls `parse`, or you could [register a custom converter](https://github.com/world-federation-of-advertisers/common-jvm/blob/4d553254bddaae1895e128081ff1db3cd19c4704/src/main/kotlin/org/wfanet/measurement/common/CommandLines.kt#L51) like we do [for Duration](https://github.com/world-federation-of-advertisers/common-jvm/blob/main/src/main/kotlin/org/wfanet/measurement/common/Durations.kt).



_Code quote:_
```Kotlin
Long
```
___
*[`src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/tools/SimpleReportTest.kt` line 132 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/571#-N2nDJma2F_6lpn-FLOY:-N2nDJma2F_6lpn-FLOZ:btjh8gu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/322e86a4ef04cbfd59d85e0df07626f31eb4b3c4/src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/tools/SimpleReportTest.kt#L132)):*
> ```Kotlin
>       val serverCerts =
>         SigningCerts.fromPemFiles(
>           certificateFile = File("$SECRETS_DIR/kingdom_tls.pem"),
> ```

```
SECRETS_DIR.resolve("kingdom_tls.pem").toFile()
```



_Code quote:_
```Kotlin
File("$SECRETS_DIR/kingdom_tls.pem")
```
___
*[`src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/tools/SimpleReportTest.kt` line 163 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/571#-N2nD4-z2G70BgiaGwr5:-N2nD40-EJfE2X1is6zK:b-4zk647) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/322e86a4ef04cbfd59d85e0df07626f31eb4b3c4/src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/tools/SimpleReportTest.kt#L163)):*
> ```Kotlin
>       --measurement-ref-id=9999
>       --data-provider-name=dataProviders/1
>       --event-group-name=dataProviders/1/eventGroups/1 --event-filter-expression=abcd
> ```

nit: just write this as a list literal to begin with using `listOf` rather than splitting a string.



_Code quote:_
```Kotlin
    val input =
      """
      --tls-cert-file=$SECRETS_DIR/mc_tls.pem
      --tls-key-file=$SECRETS_DIR/mc_tls.key
      --cert-collection-file=$SECRETS_DIR/kingdom_root.pem
      --api-target=$HOST:$PORT
      --api-cert-host=localhost
      create
      --measurement-consumer-name=measurementConsumers/777
      --private-key-der-file=$SECRETS_DIR/mc_cs_private.der
      --measurement-ref-id=9999
      --data-provider-name=dataProviders/1
      --event-group-name=dataProviders/1/eventGroups/1 --event-filter-expression=abcd
      --event-filter-start-time=100 --event-filter-end-time=200
      --event-group-name=dataProviders/1/eventGroups/2 --event-filter-expression=efgh
      --event-filter-start-time=300 --event-filter-end-time=400
      --data-provider-name=dataProviders/2
      --event-group-name=dataProviders/2/eventGroups/1 --event-filter-expression=ijk
      --event-filter-start-time=400 --event-filter-end-time=500
      """.trimIndent()

    val args = input.split(" ", "\n").toTypedArray()
```


<!-- Sent from Reviewable.io -->

2022-05-24 19:22 UTC, renjiezh reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/571)* status: 1 of 6 files reviewed, 4 unresolved discussions (waiting on @riemanli, @SanjayVas, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/tools/SimpleReport.kt` line 138 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/571#-N2nGG9j-VIOKNP5vg7D:-N2nUlo3EnDA3CGpJ-qV:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/322e86a4ef04cbfd59d85e0df07626f31eb4b3c4/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/tools/SimpleReport.kt#L138)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This has nothing to do with the filter
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/tools/SimpleReport.kt` line 140 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/571#-N2nG3jd2UTskATrqpTS:-N2nUmU6E1ZMjnKHvxmZ:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/322e86a4ef04cbfd59d85e0df07626f31eb4b3c4/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/tools/SimpleReport.kt#L140)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Time interval is required.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/tools/SimpleReport.kt` line 142 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/571#-N2nGlDe0McV2YVeH1gp:-N2rVzcR5po8XW8B2L0Y:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/322e86a4ef04cbfd59d85e0df07626f31eb4b3c4/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/tools/SimpleReport.kt#L142)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Use a more appropriate data time (e.g. `Instant`).

We also shouldn't make the user mess with epoch time and instead use human-readable strings. Picocli has a [built-in converter](https://picocli.info/#_built_in_types) for this that calls `parse`, or you could [register a custom converter](https://github.com/world-federation-of-advertisers/common-jvm/blob/4d553254bddaae1895e128081ff1db3cd19c4704/src/main/kotlin/org/wfanet/measurement/common/CommandLines.kt#L51) like we do [for Duration](https://github.com/world-federation-of-advertisers/common-jvm/blob/main/src/main/kotlin/org/wfanet/measurement/common/Durations.kt).
</blockquote></details>

Done.
___
*[`src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/tools/SimpleReportTest.kt` line 132 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/571#-N2nDJma2F_6lpn-FLOY:-N2nu1DVCPip_X6nflpZ:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/322e86a4ef04cbfd59d85e0df07626f31eb4b3c4/src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/tools/SimpleReportTest.kt#L132)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

```
SECRETS_DIR.resolve("kingdom_tls.pem").toFile()
```
</blockquote></details>

Done.
___
*[`src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/tools/SimpleReportTest.kt` line 163 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/571#-N2nD4-z2G70BgiaGwr5:-N2nu1njCAyjh-UmZkDl:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/322e86a4ef04cbfd59d85e0df07626f31eb4b3c4/src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/tools/SimpleReportTest.kt#L163)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: just write this as a list literal to begin with using `listOf` rather than splitting a string.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-05-24 20:20 UTC, tristanvuong2021 requested changes
> Reviewed 2 of 5 files at r1, 2 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/571)* status: 5 of 6 files reviewed, 5 unresolved discussions (waiting on @renjiezh, @riemanli, and @SanjayVas)

___
*[`src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/tools/README.md` line 1 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/571#-N2riLKs9fL_Q3EYUPvp:-N2riLKs9fL_Q3EYUPvq:b1pi1bv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/83eff739b9c965c78ec0c10f9ef43a4a8d8bc0fb/src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/tools/README.md#L1)):*
> ```Markdown
> # Simple Report CLI tool
> ```

Maybe move the README to the src package instead of the test.


<!-- Sent from Reviewable.io -->

2022-05-24 20:23 UTC, renjiezh reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/571)* status: 5 of 6 files reviewed, 5 unresolved discussions (waiting on @riemanli, @SanjayVas, and @tristanvuong2021)

___
*[`src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/tools/README.md` line 1 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/571#-N2riLKs9fL_Q3EYUPvp:-N2rjEupEBsDeD1Oqcbz:b6rs0kz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/83eff739b9c965c78ec0c10f9ef43a4a8d8bc0fb/src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/tools/README.md#L1)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Maybe move the README to the src package instead of the test.
</blockquote></details>

Done.
Nice catch.


<!-- Sent from Reviewable.io -->

2022-05-24 22:18 UTC, tristanvuong2021 reviewed
> Reviewed 1 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/571)* status: 5 of 6 files reviewed, 4 unresolved discussions (waiting on @riemanli, @SanjayVas, and @tristanvuong2021)



<!-- Sent from Reviewable.io -->

2022-05-24 22:20 UTC, tristanvuong2021 approved these changes
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/571)* status: all files reviewed, 4 unresolved discussions (waiting on @riemanli and @SanjayVas)



<!-- Sent from Reviewable.io -->

2022-05-25 18:50 UTC, SanjayVas requested changes
> Reviewed 2 of 5 files at r1, 1 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/571)* status: all files reviewed, 4 unresolved discussions (waiting on @renjiezh and @riemanli)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/tools/SimpleReport.kt` line 142 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/571#-N2nGlDe0McV2YVeH1gp:-N2wMO9u7G4b07PvdS4T:bj3pvsy) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/322e86a4ef04cbfd59d85e0df07626f31eb4b3c4/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/tools/SimpleReport.kt#L142)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Specify the actual desired type (`Instant` I assume), not `String`. Register a converter in common-jvm if needed (though I believe `Instant` has a built-in converter for ISO-8601 format).
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/tools/SimpleReport.kt` line 122 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/571#-N2wLWs3-ty2uqq_G_s0:-N2wLWs3-ty2uqq_G_s1:b-3z2e8y) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/22b1259d503f070e95361f4b399eaaf6d3e981ac/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/tools/SimpleReport.kt#L122)):*
> ```Kotlin
>       required = true,
>     )
>     lateinit var name: String
> ```

Add `private set` to all of these so that they are only ever initialized by Picocli.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/tools/SimpleReport.kt` line 145 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/571#-N2wLi4O8HzcUjABc6OD:-N2wLi4O8HzcUjABc6OE:b-647hy8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/22b1259d503f070e95361f4b399eaaf6d3e981ac/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/tools/SimpleReport.kt#L145)):*
> ```Kotlin
>       required = false,
>     )
>     var eventFilter: String = ""
> ```

You should still be able to use `lateinit var` here. Picocli will initialize it to the default specified in `@Option`.



_Code quote:_
```Kotlin
var eventFilter: String = ""
```
___
*[`src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/tools/SimpleReportTest.kt` line 214 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/571#-N2wW_ICE8XPAdZeml4r:-N2wW_ICE8XPAdZeml4s:b3x5ys9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/22b1259d503f070e95361f4b399eaaf6d3e981ac/src/test/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/tools/SimpleReportTest.kt#L214)):*
> ```Kotlin
>         measurementSpec {
>           measurementPublicKey = MEASUREMENT_PUBLIC_KEY
>           this.nonceHashes.addAll(nonceHashes)
> ```

nit: prefer `+=` operator for add/addAll, as that's the idiomatic Kotlin approach



_Code quote:_
```Kotlin
.addAll(
```


<!-- Sent from Reviewable.io -->

2022-05-25 20:12 UTC, renjiezh reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/571)* status: 5 of 6 files reviewed, 3 unresolved discussions (waiting on @riemanli, @SanjayVas, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/tools/SimpleReport.kt` line 142 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/571#-N2nGlDe0McV2YVeH1gp:-N2woLjp4U8y-dNp6Kkg:b-9xt562) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/322e86a4ef04cbfd59d85e0df07626f31eb4b3c4/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/tools/SimpleReport.kt#L142)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Specify the actual desired type (`Instant` I assume), not `String`. Register a converter in common-jvm if needed (though I believe `Instant` has a built-in converter for ISO-8601 format).
</blockquote></details>

Done. Good idea.
Instant is for utc format. OffsetDateTime works for ISO-8601.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/tools/SimpleReport.kt` line 122 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/571#-N2wLWs3-ty2uqq_G_s0:-N2wlWoL2Q8aTG6btp0C:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/22b1259d503f070e95361f4b399eaaf6d3e981ac/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/tools/SimpleReport.kt#L122)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Add `private set` to all of these so that they are only ever initialized by Picocli.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/tools/SimpleReport.kt` line 145 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/571#-N2wLi4O8HzcUjABc6OD:-N2wlXaB4RCR5k_1CqcS:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/22b1259d503f070e95361f4b399eaaf6d3e981ac/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/tools/SimpleReport.kt#L145)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

You should still be able to use `lateinit var` here. Picocli will initialize it to the default specified in `@Option`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-05-25 21:51 UTC, SanjayVas requested changes
> Reviewed 1 of 3 files at r3, 1 of 1 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/571)* status: all files reviewed (commit messages unreviewed), 3 unresolved discussions (waiting on @chipingyeh, @renjiezh, and @riemanli)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/tools/SimpleReport.kt` line 142 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/571#-N2nGlDe0McV2YVeH1gp:-N2xA3b6EzDtpOskDJxt:b-vt3wd1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/322e86a4ef04cbfd59d85e0df07626f31eb4b3c4/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/tools/SimpleReport.kt#L142)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

Done. Good idea.
Instant is for utc format. OffsetDateTime works for ISO-8601.
</blockquote></details>

`Instant` is the right type for a timestamp in Java. The Picocli converter calls `Instant.parse`, which parses from ISO-8601 format. My understanding is that it will convert whatever is presented into time since epoch UTC.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/tools/SimpleReport.kt` line 15 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/571#-N2xBLh5-ixduDg291eB:-N2xBLh6DUugKgCefPeL:b-r9qsj6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/af45bbbf5fa27a7ca4bab64863a5a51bc8a99a8f/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/tools/SimpleReport.kt#L15)):*
> ```Kotlin
> // limitations under the License.
> 
> package org.wfanet.measurement.kingdom.service.api.v2alpha.tools
> ```

This should probably be in `org.wfanet.measurement.api.v2alpha.tools` instead. While it happens to only deal with the CMMS API methods that are served by the Kingdom, it's dealing with the CMMS  API in general.



_Code quote:_
```Kotlin
package org.wfanet.measurement.kingdom.service.api.v2alpha.tools
```
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/tools/SimpleReport.kt` line 67 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/571#-N2xBkcE856gTqokREuG:-N2xBkcE856gTqokREuH:b-oojba4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/af45bbbf5fa27a7ca4bab64863a5a51bc8a99a8f/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/tools/SimpleReport.kt#L67)):*
> ```Kotlin
> class ApiFlags {
>   @CommandLine.Option(
>     names = ["--api-target"],
> ```

nit: `--kingdom-public-api-target`. Technically part of the public API is served by the Duchy.



_Code quote:_
```Kotlin
--api-target
```


<!-- Sent from Reviewable.io -->

2022-05-25 22:32 UTC, renjiezh reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/571)* status: 1 of 8 files reviewed, 1 unresolved discussion (waiting on @chipingyeh, @riemanli, @SanjayVas, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/tools/SimpleReport.kt` line 142 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/571#-N2nGlDe0McV2YVeH1gp:-N2xE43t1pjmKqYyL0nj:b-ryc14j) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/322e86a4ef04cbfd59d85e0df07626f31eb4b3c4/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/tools/SimpleReport.kt#L142)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

`Instant` is the right type for a timestamp in Java. The Picocli converter calls `Instant.parse`, which parses from ISO-8601 format. My understanding is that it will convert whatever is presented into time since epoch UTC.
</blockquote></details>

Failed to parse ISO-8601 into Instant. As this doc said it only parses UTC. (`instant.toString()` gives an ISO-8601 though)
https://docs.oracle.com/javase/8/docs/api/java/time/Instant.html#parse-java.lang.CharSequence-


<!-- Sent from Reviewable.io -->

2022-05-26 18:04 UTC, SanjayVas requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/571)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @chipingyeh, @renjiezh, @riemanli, @SanjayVas, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/tools/SimpleReport.kt` line 142 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/571#-N2nGlDe0McV2YVeH1gp:-N30H8Z2ECz2860RBb3p:bi7wzll) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/322e86a4ef04cbfd59d85e0df07626f31eb4b3c4/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/tools/SimpleReport.kt#L142)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

Failed to parse ISO-8601 into Instant. As this doc said it only parses UTC. (`instant.toString()` gives an ISO-8601 though)
https://docs.oracle.com/javase/8/docs/api/java/time/Instant.html#parse-java.lang.CharSequence-
</blockquote></details>

Ah, I see that it only supports UTC as the timezone. The timestamp is still in ISO-8601 format, it's just required to have UTC as the specified timestamp rather than supporting arbitrary offsets. I think that's fine.

If we really want to support arbitrary timezones, I'd prefer `ZonedDateTime` over `OffsetDateTime`. While its string format doesn't strictly adhere to ISO-8601, it's safer to use zone info rather than just an offset. Alternatively, use `LocalDateTime` and have a separate flag for the zone ID (as a single flag that would apply to all timestamps, optional and defaulting to UTC).


<!-- Sent from Reviewable.io -->

2022-05-26 18:27 UTC, renjiezh reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/571)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @chipingyeh, @riemanli, @SanjayVas, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/tools/SimpleReport.kt` line 142 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/571#-N2nGlDe0McV2YVeH1gp:-N30bdez4aefteK4fjIb:b-cp3ahb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/322e86a4ef04cbfd59d85e0df07626f31eb4b3c4/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/tools/SimpleReport.kt#L142)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Ah, I see that it only supports UTC as the timezone. The timestamp is still in ISO-8601 format, it's just required to have UTC as the specified timestamp rather than supporting arbitrary offsets. I think that's fine.

If we really want to support arbitrary timezones, I'd prefer `ZonedDateTime` over `OffsetDateTime`. While its string format doesn't strictly adhere to ISO-8601, it's safer to use zone info rather than just an offset. Alternatively, use `LocalDateTime` and have a separate flag for the zone ID (as a single flag that would apply to all timestamps, optional and defaulting to UTC).
</blockquote></details>

Done. Now use UTC format 


<!-- Sent from Reviewable.io -->

2022-05-26 19:12 UTC, SanjayVas approved these changes
> Reviewed 5 of 8 files at r6, 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/571)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @chipingyeh and @riemanli)



<!-- Sent from Reviewable.io -->

2022-05-26 22:24 UTC, riemanli requested changes
> Reviewed 3 of 8 files at r6, 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/571)* status: all files reviewed, 1 unresolved discussion (waiting on @chipingyeh and @renjiezh)

___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/README.md` line 73 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/571#-N31RXyYE94cSDFo7mcC:-N31RXyYE94cSDFo7mcD:bitiz2r) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7d9604c7add58f05cb400990af52f2b567ac0d8a/src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/README.md#L73)):*
> ```Markdown
> 
>   Assuming you have a private key for `MeasurementConsumer` containing
>   [`mc_cs_private.der`](../../../../../../../k8s/testing/secretfiles/mc_cs_private.tink)
> ```

The link doesn't work. I think there is one `../` missing.


<!-- Sent from Reviewable.io -->

2022-05-26 22:48 UTC, renjiezh reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/571)* status: 7 of 8 files reviewed, 1 unresolved discussion (waiting on @chipingyeh, @riemanli, and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/README.md` line 73 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/571#-N31RXyYE94cSDFo7mcC:-N31YWKB6t3Epe_m5SNz:b-3vcg5k) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7d9604c7add58f05cb400990af52f2b567ac0d8a/src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/README.md#L73)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

The link doesn't work. I think there is one `../` missing.
</blockquote></details>

Done.
Nice catch. Thanks.


<!-- Sent from Reviewable.io -->

2022-05-26 22:50 UTC, riemanli approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/571#-:-N31ZB0MA4W_IQvWx-IS:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @chipingyeh)



<!-- Sent from Reviewable.io -->

2022-05-31 20:27 UTC, renjiezh reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/571)* status: 7 of 8 files reviewed, 3 unresolved discussions (waiting on @chipingyeh, @riemanli, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/SimpleReport.kt` line 198 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/571#-N3Qj_iC9V5YQn3neHRp:-N3QmAhU0OY1GmoPDCxE:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d6e1c4a21c47d042db8a31f9a4f525d5dfcff590/src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/SimpleReport.kt#L198)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

this should be generated using SecureRandom
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/SimpleReport.kt` line 260 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/571#-N3QiJb33Chw5223G0-W:-N3Qk9tNEofupf-Hosvm:b65ulzp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d6e1c4a21c47d042db8a31f9a4f525d5dfcff590/src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/SimpleReport.kt#L260)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

i think these should be input params
</blockquote></details>

This is a temporary placeholder. I will address it in the next PR
___
*[`src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/SimpleReport.kt` line 261 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/571#-N3QiLsP9vP3Qflobew8:-N3QkIp865kVuxno8yyq:bk6vdmf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d6e1c4a21c47d042db8a31f9a4f525d5dfcff590/src/main/kotlin/org/wfanet/measurement/api/v2alpha/tools/SimpleReport.kt#L261)):*
> This is a temporary placeholder. I will address it in the next PR


<!-- Sent from Reviewable.io -->

2022-06-01 16:38 UTC, renjiezh reviewed
Thanks

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/571#-:-N3V7JFj55avJaEB7hTk:b-zcjvte)* status: 7 of 8 files reviewed, all discussions resolved (waiting on @riemanli, @SanjayVas, and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2022-06-01 16:39 UTC, merged