Implement internal reporting sets service.
world-federation-of-advertisers/cross-media-measurement pull request #578
Opened 2022-05-31 18:33 UTC by tristanvuong2021

2022-06-01 00:53 UTC, SanjayVas requested changes
> Reviewed 3 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/578)* status: 3 of 14 files reviewed, 4 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

___
*[`build/repositories.bzl` line 28 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/578#-N3RYmdk9FL6aUg8_lHa:-N3RYmdk9FL6aUg8_lHb:b-7irnr9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4ef24aae3e3b392d8ada2ac41088e2f2548316a3/build/repositories.bzl#L28)):*
> ```Starlark
>         repo = "common-jvm",
>         sha256 = "582b69430c32e9247eef53b1d33ff519fd96bd525e7cc58850e859140788f813",
>         #version = "0.35.0",
> ```

Add a comment indicating which PR you're waiting for so it's easier to keep track.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/ReportingSetEventGroupReader.kt` line 9 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/578#-N3RaqOxAdJ4YVfW2vkj:-N3RaqOxAdJ4YVfW2vkk:b-8ao1ic) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4ef24aae3e3b392d8ada2ac41088e2f2548316a3/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/ReportingSetEventGroupReader.kt#L9)):*
> ```Kotlin
> import org.wfanet.measurement.internal.reporting.ReportingSetKt
> 
> class ReportingSetEventGroupReader {
> ```

If you're going to copy the Reader/Writer pattern we use for Spanner in the Kingdom, then you should have the appropriate commonalities split out into interfaces and/or base classes.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/ReportingSetEventGroupReader.kt` line 22 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/578#-N3RjuOe-qTqRbjxXXEC:-N3RjuOe-qTqRbjxXXED:bbepokt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4ef24aae3e3b392d8ada2ac41088e2f2548316a3/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/ReportingSetEventGroupReader.kt#L22)):*
> ```Kotlin
>     """
> 
>   fun translate(rs: ResultSet): Result = Result(buildEventGroupKey(rs))
> ```

Document that this translates the current row of a `ResultSet`.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/ReportingSetEventGroupReader.kt` line 28 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/578#-N3Rc2gGEnDSe-f8B1AK:-N3Rc2gGEnDSe-f8B1AL:b-b5k5hv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4ef24aae3e3b392d8ada2ac41088e2f2548316a3/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/ReportingSetEventGroupReader.kt#L28)):*
> ```Kotlin
>     measurementConsumerReferenceId: String,
>     reportingSetId: InternalId
>   ): List<Result> {
> ```

We don't want to force the caller to read all rows into memory at once.

Ideally we'd use coroutines and return a Flow. The JDBC API is all blocking, so you'd need to wrap the blocking calls using `withContext`. As a result, we should probably be using R2DBC instead of JDBC. See https://github.com/pgjdbc/r2dbc-postgresql



_Code quote:_
```Kotlin
List<Result>
```


<!-- Sent from Reviewable.io -->

2022-06-06 18:34 UTC, tristanvuong2021 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/578)* status: 0 of 16 files reviewed, 4 unresolved discussions (waiting on @SanjayVas)

___
*[`build/repositories.bzl` line 28 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/578#-N3RYmdk9FL6aUg8_lHa:-N3uHz_H6ZS83vIv_eXJ:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4ef24aae3e3b392d8ada2ac41088e2f2548316a3/build/repositories.bzl#L28)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Add a comment indicating which PR you're waiting for so it's easier to keep track.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/ReportingSetEventGroupReader.kt` line 9 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/578#-N3RaqOxAdJ4YVfW2vkj:-N3uI-Q47Zl-u3GeAuPa:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4ef24aae3e3b392d8ada2ac41088e2f2548316a3/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/ReportingSetEventGroupReader.kt#L9)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

If you're going to copy the Reader/Writer pattern we use for Spanner in the Kingdom, then you should have the appropriate commonalities split out into interfaces and/or base classes.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/ReportingSetEventGroupReader.kt` line 22 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/578#-N3RjuOe-qTqRbjxXXEC:-N3uI0Gk2Sdw6PcBMBhf:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4ef24aae3e3b392d8ada2ac41088e2f2548316a3/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/ReportingSetEventGroupReader.kt#L22)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Document that this translates the current row of a `ResultSet`.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/ReportingSetEventGroupReader.kt` line 28 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/578#-N3Rc2gGEnDSe-f8B1AK:-N3uI13a8kr0phhdbmz7:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4ef24aae3e3b392d8ada2ac41088e2f2548316a3/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/ReportingSetEventGroupReader.kt#L28)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

We don't want to force the caller to read all rows into memory at once.

Ideally we'd use coroutines and return a Flow. The JDBC API is all blocking, so you'd need to wrap the blocking calls using `withContext`. As a result, we should probably be using R2DBC instead of JDBC. See https://github.com/pgjdbc/r2dbc-postgresql
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-06-06 19:31 UTC, SanjayVas requested changes
> Reviewed 4 of 14 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/578)* status: 4 of 16 files reviewed, 6 unresolved discussions (waiting on @duliomatos1, @SanjayVas, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/PostgresReportingSetsService.kt` line 17 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/578#-N3uSKm14ZHgLJ7ScXJ9:-N3uSKm14ZHgLJ7ScXJA:b-b5bv7q) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/79648057d9d250ce8e16af0f468e922e449b5e78/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/PostgresReportingSetsService.kt#L17)):*
> ```Kotlin
> class PostgresReportingSetsService(
>   private val idGenerator: IdGenerator,
>   private val getConnection: () -> Mono<Connection>
> ```

Convert Reactor/Reactive usage to idiomatic Kotlin types as early as possible. This means that this code should avoid references to `Mono` where possible.

This should be 
```
private val getConnection: suspend () -> Connection
```

Underneath it can be implemented as a function that wraps `Mono.awaitFirst()`



_Code quote:_
```Kotlin
private val getConnection: () -> Mono<Connection>
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/PostgresReportingSetsService.kt` line 25 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/578#-N3uSryx-_QnE0R7iJC3:-N3uSryy0Q15IF4TChWC:b-qhsilc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/79648057d9d250ce8e16af0f468e922e449b5e78/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/PostgresReportingSetsService.kt#L25)):*
> ```Kotlin
>       return monoResult.awaitFirst()
>     } finally {
>       connection.close()
> ```

`Connection` implements `Closeable`, so you can use Kotlin's `use` extension. See https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.io/use.html.



_Code quote:_
```Kotlin
connection.close()
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/PostgresReader.kt` line 34 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/578#-N3uU6Jo5ouTKd9A82Yc:-N3uU6Jo5ouTKd9A82Yd:b-u6ide1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/79648057d9d250ce8e16af0f468e922e449b5e78/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/PostgresReader.kt#L34)):*
> ```Kotlin
> 
>   /** Executes the query. */
>   fun execute(connection: Connection, statement: Statement): Flux<T> {
> ```

`Flow`



_Code quote:_
```Kotlin
Flux
```


<!-- Sent from Reviewable.io -->

2022-06-06 20:03 UTC, SanjayVas requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/578)* status: 3 of 16 files reviewed, 6 unresolved discussions (waiting on @duliomatos1, @SanjayVas, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/PostgresReportingSetsService.kt` line 25 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/578#-N3uSryx-_QnE0R7iJC3:-N3ub8cJ48R75MlTS4ey:b9mhd5j) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/79648057d9d250ce8e16af0f468e922e449b5e78/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/PostgresReportingSetsService.kt#L25)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

It implements the r2dbc spi closeable, not the standard closeable. https://r2dbc.io/spec/0.8.0.RC1/api/io/r2dbc/spi/Closeable.html
</blockquote></details>

Ah. I see that this close returns a publisher. Therefore, the right thing to do is wait for the publisher.


<!-- Sent from Reviewable.io -->

2022-06-06 20:16 UTC, tristanvuong2021 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/578)* status: 2 of 16 files reviewed, 6 unresolved discussions (waiting on @duliomatos1, @SanjayVas, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/PostgresReportingSetsService.kt` line 17 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/578#-N3uSKm14ZHgLJ7ScXJ9:-N3ucfQUA3wlYsf2fuTg:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/79648057d9d250ce8e16af0f468e922e449b5e78/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/PostgresReportingSetsService.kt#L17)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Convert Reactor/Reactive usage to idiomatic Kotlin types as early as possible. This means that this code should avoid references to `Mono` where possible.

This should be 
```
private val getConnection: suspend () -> Connection
```

Underneath it can be implemented as a function that wraps `Mono.awaitFirst()`
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/PostgresReader.kt` line 34 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/578#-N3uU6Jo5ouTKd9A82Yc:-N3ue6js0D5mXEZEKdeS:b1gpxpp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/79648057d9d250ce8e16af0f468e922e449b5e78/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/PostgresReader.kt#L34)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

`Flow`
</blockquote></details>

I tried it and remembered that it doesn't work. Kotlin doesn't allow asFlow here. Probably because of generics.


<!-- Sent from Reviewable.io -->

2022-06-06 22:01 UTC, tristanvuong2021 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/578)* status: 2 of 16 files reviewed, 6 unresolved discussions (waiting on @duliomatos1 and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/PostgresReportingSetsService.kt` line 25 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/578#-N3uSryx-_QnE0R7iJC3:-N3v1G2G479loTV4tTt8:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/79648057d9d250ce8e16af0f468e922e449b5e78/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/PostgresReportingSetsService.kt#L25)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Ah. I see that this close returns a publisher. Therefore, the right thing to do is wait for the publisher.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-06-07 19:42 UTC, tristanvuong2021 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/578)* status: 5 of 16 files reviewed, 7 unresolved discussions (waiting on @duliomatos1, @SanjayVas, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/PostgresReader.kt` line 34 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/578#-N3zK6F42OIPpfWkJYG4:-N3zeAag-0iX4DlD4DIA:b-7eio39) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/79648057d9d250ce8e16af0f468e922e449b5e78/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/PostgresReader.kt#L34)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Don't need to take in the statement here if `builder` is a `Statement`.
</blockquote></details>

Think I will just get rid of the builder instead. A Statement can only be created from a connection. It isn't something that can be created on its own.


<!-- Sent from Reviewable.io -->

2022-06-07 19:50 UTC, tristanvuong2021 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/578)* status: 5 of 16 files reviewed, 7 unresolved discussions (waiting on @duliomatos1, @SanjayVas, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/PostgresReader.kt` line 25 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/578#-N3zFhSW3ygN5RNuubPO:-N3zhsv83CkQd7ujxqK_:bpdesqt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/79648057d9d250ce8e16af0f468e922e449b5e78/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/PostgresReader.kt#L25)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I think this needs a bit more design work. Like JDBC, R2DBC has a mutable `Connection` object with transaction state. What we want is something like a transaction context that allows the caller to execute multiple queries/statements in the same transaction, while preventing the caller from messing with the connection state in any other way.

Our base code should handle getting a connection, starting a transaction with the right properties (e.g. setting isolation level), committing or rolling back the transaction, and closing the connection.
</blockquote></details>

Then I should switch back to passing a mono instead of the connection.


<!-- Sent from Reviewable.io -->

2022-06-07 19:53 UTC, tristanvuong2021 commented
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/PostgresReader.kt` line 25 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/578#-N3zFhSW3ygN5RNuubPO:-N3ziU7qEqTWlXkde4hV:b-1inhh1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/79648057d9d250ce8e16af0f468e922e449b5e78/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/PostgresReader.kt#L25)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Then I should switch back to passing a mono instead of the connection.
</blockquote></details>

Actually, the base code should call the connection factory code then.


<!-- Sent from Reviewable.io -->

2022-06-10 00:45 UTC, tristanvuong2021 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/578)* status: 0 of 16 files reviewed, 7 unresolved discussions (waiting on @duliomatos1 and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/PostgresReader.kt` line 28 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/578#-N3zHKcZ6AhhI52pWfhi:-N4A3gJT271E_A76DJp-:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/79648057d9d250ce8e16af0f468e922e449b5e78/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/PostgresReader.kt#L28)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I think this is trying to copy the pattern from SpannerReader. Ideally we want the subclass to be forced to build the entire statement, and then have `execute` just execute said statement. Unfortunately, R2DBC's `Statement` is mutable rather than having a separate builder. Regardless, the closest equivalent to Spanner's statement builder is `Statement`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-06-10 23:14 UTC, SanjayVas requested changes
> Reviewed 4 of 12 files at r7, 3 of 6 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/578)* status: 7 of 16 files reviewed, 4 unresolved discussions (waiting on @duliomatos1 and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/PostgresReader.kt` line 25 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/578#-N4EaZw19Z8sAxnFn4eR:-N4EaZw19Z8sAxnFn4eS:b-rcqns6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0d56636dee8c3fd39a974f3ebfd9a71dacfc5665/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/PostgresReader.kt#L25)):*
> ```Kotlin
> /** Abstraction for reading from Postgres. */
> abstract class PostgresReader<T : Any> {
>   protected abstract val baseSql: String
> ```

nit: this doesn't need to be a required part of  the interface, since
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/PostgresReader.kt` line 31 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/578#-N4EbhYf2L7F4j_RKkwg:-N4EbhYf2L7F4j_RKkwh:baacdqg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0d56636dee8c3fd39a974f3ebfd9a71dacfc5665/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/PostgresReader.kt#L31)):*
> ```Kotlin
> 
>   /** Executes the query. */
>   suspend fun execute(readContext: ReadContext, builder: StatementBuilder): Flow<T> {
> ```

The caller shouldn't be able to mess with the statement.

You need to decide on a pattern here: either you have a public `execute` as the *only* method you can use to get results (which forces your response processing through translate), or you basically drop the Reader interface and use ReadContext directly.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/ReportingSetEventGroupReader.kt` line 53 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/578#-N4Ds4U2Ch_fD3vypUMA:-N4Ds4U2Ch_fD3vypUMB:bvthxs5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2dee9cb2a58cdac03df2e3babd1d32615557c89f/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/ReportingSetEventGroupReader.kt#L53)):*
> ```Kotlin
>           baseSql +
>             """
>         WHERE MeasurementConsumerReferenceId = CAST($1 AS text)
> ```

Is this actually needed? The r2dbc-postgresql documentation seems to imply that the Java `String` type gets mapped to `text` by default.



_Code quote:_
```Kotlin
CAST($1 AS text)
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/ReportingSetReader.kt` line 96 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/578#-N4EYYKy9kpz9gWXY2f3:-N4EYYKz5VPXikeQ8PTX:b-en5ys9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0d56636dee8c3fd39a974f3ebfd9a71dacfc5665/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/ReportingSetReader.kt#L96)):*
> ```Kotlin
>       }
> 
>       readContext.close()
> ```

This should be in a `finally` block so it gets closed even if there's an error.



_Code quote:_
```Kotlin
readContext.close()
```


<!-- Sent from Reviewable.io -->

2022-06-10 23:42 UTC, tristanvuong2021 commented
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/ReportingSetEventGroupReader.kt` line 53 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/578#-N4Ds4U2Ch_fD3vypUMA:-N4EzWpM0d8PsCBXJwTA:b-onjdsi) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2dee9cb2a58cdac03df2e3babd1d32615557c89f/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/ReportingSetEventGroupReader.kt#L53)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Is this actually needed? The r2dbc-postgresql documentation seems to imply that the Java `String` type gets mapped to `text` by default.
</blockquote></details>

This covers the case when the String happens to be all digits.


<!-- Sent from Reviewable.io -->

2022-06-10 23:59 UTC, tristanvuong2021 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/578)* status: 4 of 16 files reviewed, 3 unresolved discussions (waiting on @duliomatos1, @SanjayVas, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/ReportingSetReader.kt` line 96 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/578#-N4EYYKy9kpz9gWXY2f3:-N4F2Wij3jJQf_D9kb24:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0d56636dee8c3fd39a974f3ebfd9a71dacfc5665/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/ReportingSetReader.kt#L96)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This should be in a `finally` block so it gets closed even if there's an error.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-06-11 00:40 UTC, SanjayVas requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/578)* status: 4 of 16 files reviewed, 3 unresolved discussions (waiting on @duliomatos1, @SanjayVas, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/ReportingSetEventGroupReader.kt` line 53 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/578#-N4Ds4U2Ch_fD3vypUMA:-N4FAVuT0Q4QVLHlPZs9:bdh8oml) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2dee9cb2a58cdac03df2e3babd1d32615557c89f/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/ReportingSetEventGroupReader.kt#L53)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

This covers the case when the String happens to be all digits.
</blockquote></details>

Wait, seriously? The fact that we're binding with a String type should handle this to make sure that the bound value doesn't get interpreted as a different type. This feels like a bug in postgresql-r2dbc.

Can you add a comment at least indicating why we're doing this, as it seems weird.


<!-- Sent from Reviewable.io -->

2022-06-11 01:30 UTC, tristanvuong2021 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/578)* status: 4 of 16 files reviewed, 2 unresolved discussions (waiting on @duliomatos1, @SanjayVas, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/ReportingSetEventGroupReader.kt` line 53 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/578#-N4Ds4U2Ch_fD3vypUMA:-N4FNSgR4d2wDEnh9Gsy:b-m0b942) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2dee9cb2a58cdac03df2e3babd1d32615557c89f/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/ReportingSetEventGroupReader.kt#L53)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Wait, seriously? The fact that we're binding with a String type should handle this to make sure that the bound value doesn't get interpreted as a different type. This feels like a bug in postgresql-r2dbc.

Can you add a comment at least indicating why we're doing this, as it seems weird.
</blockquote></details>

Huh, I just tested it and I guess r2dbc adds the cast for you. When I was still using jdbc, I had an issue.


<!-- Sent from Reviewable.io -->

2022-06-13 16:22 UTC, tristanvuong2021 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/578)* status: 4 of 16 files reviewed, 2 unresolved discussions (waiting on @duliomatos1 and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/PostgresReader.kt` line 31 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/578#-N4EbhYf2L7F4j_RKkwg:-N4Ss05H3C1cCAK4cjnA:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0d56636dee8c3fd39a974f3ebfd9a71dacfc5665/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/PostgresReader.kt#L31)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The caller shouldn't be able to mess with the statement.

You need to decide on a pattern here: either you have a public `execute` as the *only* method you can use to get results (which forces your response processing through translate), or you basically drop the Reader interface and use ReadContext directly.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-06-13 17:25 UTC, SanjayVas requested changes
This is close. Just minor changes left I think.

> Reviewed 2 of 14 files at r1, 1 of 14 files at r2, 1 of 5 files at r5, 2 of 12 files at r7, 3 of 6 files at r8, 3 of 3 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/578#-:-N4T5IEu7NxJhuYBjlG_:b-xy8lb)* status: all files reviewed, 11 unresolved discussions (waiting on @duliomatos1 and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/ReportingSetEventGroupReader.kt` line 42 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/578#-N4Ssa0IA4e6QKrFP3nL:-N4Ssa0IA4e6QKrFP3nM:b-tx3f1g) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c48adeaf6c3bcd3559d16e46680dc8e093b5da8f/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/ReportingSetEventGroupReader.kt#L42)):*
> ```Kotlin
> 
>   suspend fun listEventGroupKeys(
>     readContext: ReadContext,
> ```

A method that returns a flow should generally not suspend, and instead do all suspending operations within the result flow builder.

I think what you want is something like

```kotlin
emitAll(readContext.executeQuery(builder).consume(::translate))
```



_Code quote:_
```Kotlin
suspend 
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/ReportingSetReader.kt` line 83 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/578#-N4SthFi5-6ljVhdiDHP:-N4SthFi5-6ljVhdiDHQ:bp9g8sf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c48adeaf6c3bcd3559d16e46680dc8e093b5da8f/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/ReportingSetReader.kt#L83)):*
> ```Kotlin
>       val readContext = client.readTransaction()
>       try {
>         readContext.executeQuery(builder).consume(::translate).collect { reportingSetResult ->
> ```

`translate` should be the last step

Since r2dbc-postgresql doesn't support nested row readers, I think you'd need to have `translate` also take in the subquery result.



_Code quote:_
```Kotlin
::translate
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/writers/CreateReportingSet.kt` line 27 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/578#-N4T0nTa5kq5nsMH3tn3:-N4T0nTa5kq5nsMH3tn4:b-7c2gh5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c48adeaf6c3bcd3559d16e46680dc8e093b5da8f/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/writers/CreateReportingSet.kt#L27)):*
> ```Kotlin
> import org.wfanet.measurement.internal.reporting.copy
> 
> class CreateReportingSet(private val reportingSet: ReportingSet) : PostgresWriter<ReportingSet>() {
> ```

nit: I personally prefer calling this `request` to disambiguate from the response, as this is only a partial `ReportingSet`.



_Code quote:_
```Kotlin
reportingSet
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/writers/CreateReportingSet.kt` line 47 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/578#-N4T12v24yVHvtKgOhn6:-N4T12v24yVHvtKgOhn7:ba3tbjf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c48adeaf6c3bcd3559d16e46680dc8e093b5da8f/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/writers/CreateReportingSet.kt#L47)):*
> ```Kotlin
> 
>     transactionContext.run {
>       executeStatement(builder).numRowsUpdated
> ```

You don't need to access `numRowsUpdated` to ensure the statement has executed. `ReadWriteContet.executeStatement` suspends until the statement has been executed by calling `rowsUpdated.awaitFirst()` for you. This `numRowsUpdated` is just a regular property.



_Code quote:_
```Kotlin
.numRowsUpdated
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/writers/CreateReportingSet.kt` line 49 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/578#-N4T1o9u9ozPrPg1WwWI:-N4T1o9u9ozPrPg1WwWJ:bcgq14d) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c48adeaf6c3bcd3559d16e46680dc8e093b5da8f/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/writers/CreateReportingSet.kt#L49)):*
> ```Kotlin
>       executeStatement(builder).numRowsUpdated
>       CoroutineScope(Dispatchers.IO)
>         .launch {
> ```

You don't need `launch` for this, as I believe the only suspending call is already wrapped in `async`.

Just

```
      CoroutineScope(Dispatchers.IO) {
          reportingSet
            .eventGroupKeysList
            .map {
              async {
                executeStatement(createReportingSetEventGroupStatement(it, internalReportingSetId))
                  .numRowsUpdated
              }
            }
            .awaitAll()
      }

```



_Code quote:_
```Kotlin
.launch {
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/writers/CreateReportingSet.kt` line 66 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/578#-N4T4KS4AiZlbkqdJ1d7:-N4T4KS562xOJjgCOdkr:b-whndeq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c48adeaf6c3bcd3559d16e46680dc8e093b5da8f/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/writers/CreateReportingSet.kt#L66)):*
> ```Kotlin
>   }
> 
>   private fun createReportingSetEventGroupStatement(
> ```

nit: I'd personally recommend having this method be `private suspend fun TransactionScope.insertReportingSetEventGroup`.



_Code quote:_
```Kotlin
private fun createReportingSetEventGroupStatement(
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/writers/PostgresWriter.kt` line 34 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/578#-N4Sx8O22TymXbhtZTcX:-N4Sx8O22TymXbhtZTcY:b-rvkf6y) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c48adeaf6c3bcd3559d16e46680dc8e093b5da8f/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/writers/PostgresWriter.kt#L34)):*
> ```Kotlin
>    * Override this to perform the body of the Postgres transaction.
>    *
>    * This runs in the scope of a [TransactionScope], so it has convenient access to the [Connection]
> ```

nit: [ReadWriteContext]



_Code quote:_
```Kotlin
[Connection]
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/ReportingSetsServiceTest.kt` line 17 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/578#-N4T-AvDC_Lp8FEAvXTA:-N4T-AvE-DehKxbjpnNP:b-avogmd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c48adeaf6c3bcd3559d16e46680dc8e093b5da8f/src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/ReportingSetsServiceTest.kt#L17)):*
> ```Kotlin
> package org.wfanet.measurement.reporting.service.internal.testing
> 
> import com.google.common.truth.Truth.assertThat
> ```

Also import the ProtoTruth version of this to make sure proto messages are handled properly.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/ReportingSetsServiceTest.kt` line 79 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/578#-N4SyA2w-gaW9is7zE9x:-N4SyA2w-gaW9is7zE9y:bosjzzn) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c48adeaf6c3bcd3559d16e46680dc8e093b5da8f/src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/ReportingSetsServiceTest.kt#L79)):*
> ```Kotlin
>       assertThat(createdReportingSet.externalReportingSetId).isNotEqualTo(0L)
> 
>       asser [...]

2022-06-13 18:36 UTC, tristanvuong2021 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/578)* status: 11 of 16 files reviewed, 9 unresolved discussions (waiting on @duliomatos1 and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/ReportingSetEventGroupReader.kt` line 42 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/578#-N4Ssa0IA4e6QKrFP3nL:-N4TJKaJDNAck61hWSXg:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c48adeaf6c3bcd3559d16e46680dc8e093b5da8f/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/ReportingSetEventGroupReader.kt#L42)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

A method that returns a flow should generally not suspend, and instead do all suspending operations within the result flow builder.

I think what you want is something like

```kotlin
emitAll(readContext.executeQuery(builder).consume(::translate))
```
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/ReportingSetReader.kt` line 83 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/578#-N4SthFi5-6ljVhdiDHP:-N4TLJHf689Fuv4OUHyk:b-ca7c7c) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c48adeaf6c3bcd3559d16e46680dc8e093b5da8f/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/ReportingSetReader.kt#L83)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

`translate` should be the last step

Since r2dbc-postgresql doesn't support nested row readers, I think you'd need to have `translate` also take in the subquery result.
</blockquote></details>

But I need to map it first to get the reporting set id to get the event groups.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/writers/CreateReportingSet.kt` line 47 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/578#-N4T12v24yVHvtKgOhn6:-N4TAt_q3F2HACqvjQP2:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c48adeaf6c3bcd3559d16e46680dc8e093b5da8f/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/writers/CreateReportingSet.kt#L47)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

You don't need to access `numRowsUpdated` to ensure the statement has executed. `ReadWriteContet.executeStatement` suspends until the statement has been executed by calling `rowsUpdated.awaitFirst()` for you. This `numRowsUpdated` is just a regular property.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/writers/CreateReportingSet.kt` line 49 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/578#-N4T1o9u9ozPrPg1WwWI:-N4TDevGEp4lgJpRsu_C:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c48adeaf6c3bcd3559d16e46680dc8e093b5da8f/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/writers/CreateReportingSet.kt#L49)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

You don't need `launch` for this, as I believe the only suspending call is already wrapped in `async`.

Just

```
      CoroutineScope(Dispatchers.IO) {
          reportingSet
            .eventGroupKeysList
            .map {
              async {
                executeStatement(createReportingSetEventGroupStatement(it, internalReportingSetId))
                  .numRowsUpdated
              }
            }
            .awaitAll()
      }

```

</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/writers/CreateReportingSet.kt` line 66 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/578#-N4T4KS4AiZlbkqdJ1d7:-N4TEU8wCf6MOO12ruBR:b-y9gc9t) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c48adeaf6c3bcd3559d16e46680dc8e093b5da8f/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/writers/CreateReportingSet.kt#L66)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: I'd personally recommend having this method be `private suspend fun TransactionScope.insertReportingSetEventGroup`.
</blockquote></details>

There is no suspend function being called inside the method though.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/ReportingSetsServiceTest.kt` line 17 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/578#-N4T-AvDC_Lp8FEAvXTA:-N4TFA2hCbRSe71DFdWU:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c48adeaf6c3bcd3559d16e46680dc8e093b5da8f/src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/ReportingSetsServiceTest.kt#L17)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Also import the ProtoTruth version of this to make sure proto messages are handled properly.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/ReportingSetsServiceTest.kt` line 79 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/578#-N4SyA2w-gaW9is7zE9x:-N4TFRza21H8JzddtXRH:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c48adeaf6c3bcd3559d16e46680dc8e093b5da8f/src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/ReportingSetsServiceTest.kt#L79)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Why would this be in a test for something succeeding? This should be a separate test

I assume this is verifying that you can't create a reporting set with an existing ID?
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/ReportingSetsServiceTest.kt` line 79 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/578#-N4Syh6C5ooOqJPxKIkj:-N4TFWp7BbASpfxVXDyH:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c48adeaf6c3bcd3559d16e46680dc8e093b5da8f/src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/ReportingSetsServiceTest.kt#L79)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

1. The abstract test base shouldn't check anything that's implementation-specific.
2. A gRPC service should only throw gRPC errors (`StatusRuntimeException`). A gRPC server will automatically wrap any other exception type with code `INTERNAL` which intentionally gives very little info. Therefore, we should be trying to catch every exception that can be mapped to a more accurate status code and rethrow it wrapped in `StatusRuntimeException`.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/ReportingSetsServiceTest.kt` line 125 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/578#-N4T--Az0-oqAUrd3Al1:-N4TG4q71AfYS_KHVvJW:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c48adeaf6c3bcd3559d16e46680dc8e093b5da8f/src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/ReportingSetsServiceTest.kt#L125)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This can be combined more descr [...]

2022-06-13 21:21 UTC, SanjayVas requested changes
> Reviewed 4 of 5 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/578)* status: 15 of 16 files reviewed, 4 unresolved discussions (waiting on @duliomatos1, @SanjayVas, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/writers/CreateReportingSet.kt` line 66 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/578#-N4T4KS4AiZlbkqdJ1d7:-N4TvOg404oNctsGXLrW:b-53f4dc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c48adeaf6c3bcd3559d16e46680dc8e093b5da8f/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/writers/CreateReportingSet.kt#L66)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

There is no suspend function being called inside the method though.
</blockquote></details>

Sorry, the rename implied moving the executeStatement call to inside of this function.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/ReportingSetsServiceTest.kt` line 79 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/578#-N4Syh6C5ooOqJPxKIkj:-N4Tw6nrEO3AbktDFj9r:benujyp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c48adeaf6c3bcd3559d16e46680dc8e093b5da8f/src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/ReportingSetsServiceTest.kt#L79)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't see the separate test that checks for `StatusRuntimeException` with code `ALREADY_EXISTS` (nor the implementation that would throw such an exception).
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/ReportingSetsServiceTest.kt` line 125 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/578#-N4T--Az0-oqAUrd3Al1:-N4TvgoU0QtmM7CmseIK:bkbm6o8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c48adeaf6c3bcd3559d16e46680dc8e093b5da8f/src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/ReportingSetsServiceTest.kt#L125)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

You don't need to check size if you're using `containsExactly`. I was just giving an example of how to do it if you need to check size but not contents.


<!-- Sent from Reviewable.io -->

2022-06-13 21:28 UTC, SanjayVas requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/578)* status: 15 of 16 files reviewed, 4 unresolved discussions (waiting on @duliomatos1, @SanjayVas, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/ReportingSetsServiceTest.kt` line 79 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/578#-N4Syh6C5ooOqJPxKIkj:-N4TxOkEBxlKubdQI4Gd:bapl87e) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c48adeaf6c3bcd3559d16e46680dc8e093b5da8f/src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/ReportingSetsServiceTest.kt#L79)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I don't see the separate test that checks for `StatusRuntimeException` with code `ALREADY_EXISTS` (nor the implementation that would throw such an exception).
</blockquote></details>

`PostgresqlDataIntegrityViolationException` includes an [`ErrorDetails`](https://github.com/pgjdbc/r2dbc-postgresql/blob/v0.9.1.RELEASE/src/main/java/io/r2dbc/postgresql/api/ErrorDetails.java) that gives a Postgres-specific error code that may help with this.

See https://www.postgresql.org/docs/current/errcodes-appendix.html



_Code quote:_
```Kotlin
R2dbcDataIntegrityViolationException
```


<!-- Sent from Reviewable.io -->

2022-06-13 23:57 UTC, tristanvuong2021 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/578)* status: 12 of 20 files reviewed, 4 unresolved discussions (waiting on @duliomatos1 and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/writers/CreateReportingSet.kt` line 66 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/578#-N4T4KS4AiZlbkqdJ1d7:-N4TyMQWEvXPSAE_Qn1y:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c48adeaf6c3bcd3559d16e46680dc8e093b5da8f/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/writers/CreateReportingSet.kt#L66)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Sorry, the rename implied moving the executeStatement call to inside of this function.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/ReportingSetsServiceTest.kt` line 79 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/578#-N4Syh6C5ooOqJPxKIkj:-N4UV6GL5tv6gYSoIJZr:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c48adeaf6c3bcd3559d16e46680dc8e093b5da8f/src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/ReportingSetsServiceTest.kt#L79)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

`PostgresqlDataIntegrityViolationException` includes an [`ErrorDetails`](https://github.com/pgjdbc/r2dbc-postgresql/blob/v0.9.1.RELEASE/src/main/java/io/r2dbc/postgresql/api/ErrorDetails.java) that gives a Postgres-specific error code that may help with this.

See https://www.postgresql.org/docs/current/errcodes-appendix.html
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/ReportingSetsServiceTest.kt` line 125 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/578#-N4T--Az0-oqAUrd3Al1:-N4TyXUYCGc4FLbORmMS:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c48adeaf6c3bcd3559d16e46680dc8e093b5da8f/src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/ReportingSetsServiceTest.kt#L125)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

You don't need to check size if you're using `containsExactly`. I was just giving an example of how to do it if you need to check size but not contents.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-06-14 18:16 UTC, SanjayVas requested changes
> Reviewed 3 of 8 files at r13, 5 of 5 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/578)* status: all files reviewed, 4 unresolved discussions (waiting on @duliomatos1 and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/common/ReportingInternalException.kt` line 15 at r14](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/578#-N4XwY9w82GQP5H0r6My:-N4XwY9w82GQP5H0r6Mz:b-r814av) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2ca64fa2e116bdfec6115da398dd8f64c9a6aa7f/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/common/ReportingInternalException.kt#L15)):*
> ```Kotlin
> // limitations under the License.
> 
> package org.wfanet.measurement.reporting.deploy.postgres.common
> ```

Let's put this in `reporting.service.internal` instead, since it need not be specific to the postgres impl.

I know this is copied from KingdomInternalException, and that's in the wrong place too.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/ReportingSetReader.kt` line 83 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/578#-N4SthFi5-6ljVhdiDHP:-N4XythJE2tD9gI-HZpS:b-4fgq9z) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c48adeaf6c3bcd3559d16e46680dc8e093b5da8f/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/ReportingSetReader.kt#L83)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

But I need to map it first to get the reporting set id to get the event groups.
</blockquote></details>

What I was suggesting was doing that work in the `consume` handler, and make `translate` take in the row data as well as additional data related to the row.

Unfortunately, I realized we can't pass around the `Row` like we would with a Spanner `Struct`. Therefore this approach would mean having to convert the Row into an intermediate representation of the row data.

I guess this way is fine given the limitations, but I'd prefer not having a partial ReportingSet. I was envisioning `translate` as the method that takes any intermediate data and converts it to the final result type.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/writers/CreateReportingSet.kt` line 54 at r14](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/578#-N4YQ6XY04ngdchokxDR:-N4YQ6XY04ngdchokxDS:b-8s3r2w) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2ca64fa2e116bdfec6115da398dd8f64c9a6aa7f/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/writers/CreateReportingSet.kt#L54)):*
> ```Kotlin
>       try {
>         executeStatement(builder)
>       } catch (e: R2dbcDataIntegrityViolationException) {
> ```

nit: maybe check the error code here to make sure, though I suppose already exists is the most likely cause
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/writers/CreateReportingSet.kt` line 67 at r14](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/578#-N4YQJ5T1KgtMwV2bwNR:-N4YQJ5T1KgtMwV2bwNS:bvt9zui) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2ca64fa2e116bdfec6115da398dd8f64c9a6aa7f/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/writers/CreateReportingSet.kt#L67)):*
> ```Kotlin
>   }
> 
>   private suspend fun TransactionScope.insertReportingSetEventGroupStatement(
> ```

nit: drop `Statement`



_Code quote:_
```Kotlin
Statement
```


<!-- Sent from Reviewable.io -->

2022-06-14 18:58 UTC, SanjayVas requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/578)* status: all files reviewed, 2 unresolved discussions (waiting on @duliomatos1 and @tristanvuong2021)



<!-- Sent from Reviewable.io -->

2022-06-14 20:11 UTC, tristanvuong2021 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/578)* status: 15 of 20 files reviewed, 2 unresolved discussions (waiting on @duliomatos1 and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/writers/CreateReportingSet.kt` line 67 at r14](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/578#-N4YQJ5T1KgtMwV2bwNR:-N4Ypsb50Xqsrr_T2znE:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2ca64fa2e116bdfec6115da398dd8f64c9a6aa7f/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/writers/CreateReportingSet.kt#L67)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: drop `Statement`
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/common/ReportingInternalException.kt` line 15 at r14](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/578#-N4XwY9w82GQP5H0r6My:-N4YptNH9QE0H0tzjBeZ:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2ca64fa2e116bdfec6115da398dd8f64c9a6aa7f/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/common/ReportingInternalException.kt#L15)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Let's put this in `reporting.service.internal` instead, since it need not be specific to the postgres impl.

I know this is copied from KingdomInternalException, and that's in the wrong place too.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-06-14 22:11 UTC, SanjayVas approved these changes
> Reviewed 5 of 5 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/578)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @duliomatos1)



<!-- Sent from Reviewable.io -->

2022-06-16 19:32 UTC, merged