Add functionality to check privacy budget would be exceeded without charging.
world-federation-of-advertisers/cross-media-measurement pull request #583
Opened 2022-06-03 02:39 UTC by uakyol

2022-06-03 12:10 UTC, duliomatos1 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/583)* status: 0 of 15 files reviewed, 1 unresolved discussion (waiting on @matthewclegg and @uakyol)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetLedger.kt` line 61 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/583#-N3dS9j02t8fg7S2xoIC:-N3dS9j02t8fg7S2xoID:b-8l3jcj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ec274164de98777f39be2d8d67810d0c0001bd3b/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetLedger.kt#L61)):*
> ```Kotlin
>    * exceed the allowed budget.
>    */
>   fun check(
> ```

nit: a matter of preference, but how about the public function name be the more expressive one? e.g. `checkPrivacyBudgetExceeded()`,
and the private helper function could be renamed. Same for the other `check()` functions


<!-- Sent from Reviewable.io -->

2022-06-03 23:06 UTC, matthewclegg requested changes
> Reviewed 1 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/583)* status: 1 of 15 files reviewed, 6 unresolved discussions (waiting on @duliomatos1, @matthewclegg, and @uakyol)

___
*[`-- commits` line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/583#-N3fnOt-2WZo0JE_OKBL):*
This PR contains 16 changed files.  Looking at the changes, I see they can be divided into the following categories: (1) changes to support implementation of checking privacy budget; (2) refactoring where the VidSamplingInterval occurs in the MeasurementSpec; (3) changing the nomenclature of various functions (e.g., chargePrivacyBudget -> charge); (4) random reformatting changes in other unrelated parts of the codebase.  No need to refactor this PR, but for the future, would it be possible to separate these into separate PRs?
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetLedger.kt` line 58 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/583#-N3fix5UAxc0o-wSLDr1:-N3fix5UAxc0o-wSLDr2:b-twfegv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ec274164de98777f39be2d8d67810d0c0001bd3b/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetLedger.kt#L58)):*
> ```Kotlin
>    * privacy charges to that group would make anyone of them exceed their budget.
>    *
>    * @throws PrivacyBudgetManagerException if the attempt to charge the privacy bucket groups would
> ```

For charging privacy budget, I can see why throwing an error if budget exceeded could make sense.  For checking privacy budget, I would have thought that the function should return a boolean.  Why is throwing an exception the better choice?
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetLedger.kt` line 62 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/583#-N3fiAPFCGoLdidsDWID:-N3fiAPFCGoLdidsDWIE:beivpnh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ec274164de98777f39be2d8d67810d0c0001bd3b/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetLedger.kt#L62)):*
> ```Kotlin
>    */
>   fun check(
>     reference: Reference,
> ```

Why is a reference needed?
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetManager.kt` line 149 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/583#-N3fjdz_9FDqlccyaAw-:-N3fjdz_9FDqlccyaAw0:b-a7090c) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ec274164de98777f39be2d8d67810d0c0001bd3b/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetManager.kt#L149)):*
> ```Kotlin
>    */
>   fun check(
>     reference: Reference,
> ```

Also here, I don't understand the need to include a reference, and I would have it return a boolean value representing whether or not there is available budget for the proposed query.
___
*[`src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2MillTest.kt` line 319 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/583#-N3fkUsl68vLc8g1icn0:-N3fkUsl68vLc8g1icn1:bof9eiy) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ec274164de98777f39be2d8d67810d0c0001bd3b/src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2MillTest.kt#L319)):*
> ```Kotlin
>   nonceHashes += TEST_REQUISITION_3.nonceHash
>   reachAndFrequency = reachAndFrequency {}
>   vidSamplingInterval = vidSamplingInterval { width = 0.5f }
> ```

I don't understand how the changes in this file relate to checking privacy budget.  Could you please explain?


<!-- Sent from Reviewable.io -->

2022-06-03 23:28 UTC, matthewclegg requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/583)* status: 1 of 15 files reviewed, 7 unresolved discussions (waiting on @duliomatos1, @matthewclegg, and @uakyol)

___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetManager.kt` line 150 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/583#-N3fsvp8DIvzdg60mlSJ:-N3fsvp8DIvzdg60mlSK:bd2j59q) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ec274164de98777f39be2d8d67810d0c0001bd3b/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetManager.kt#L150)):*
> ```Kotlin
>   fun check(
>     reference: Reference,
>     requisitionSpec: RequisitionSpec,
> ```

One other thing that I would strongly consider is the idea of allowing the caller to provide a list of <RequisitionSpec, MeasurementSpec> pairs.  This would be useful because I believe it is the case that MC's will be interested in knowing whether they can run an entire report (e.g., for example, all 4K queries in the Comscore report) as opposed to knowing whether they can run just a single query.


<!-- Sent from Reviewable.io -->

2022-06-06 19:19 UTC, uakyol reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/583)* status: 1 of 15 files reviewed, 7 unresolved discussions (waiting on @duliomatos1 and @matthewclegg)

___
*[`-- commits` line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/583#-N3fnOt-2WZo0JE_OKBL):*
> Why is a reference needed?
Thank you Matthew, I agree. Im abandoning this PR, and splitting it. I moved your and @duliomatos1 's comments to the new PR : https://github.com/world-federation-of-advertisers/cross-media-measurement/pull/589
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetLedger.kt` line 58 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/583#-N3fix5UAxc0o-wSLDr1:-N3uRfg8Alnz1AWTasmh:b-40z3tm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ec274164de98777f39be2d8d67810d0c0001bd3b/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetLedger.kt#L58)):*
<details><summary><i>Previously, matthewclegg (Matthew Clegg) wrote…</i></summary><blockquote>

For charging privacy budget, I can see why throwing an error if budget exceeded could make sense.  For checking privacy budget, I would have thought that the function should return a boolean.  Why is throwing an exception the better choice?
</blockquote></details>

moved to :https://github.com/world-federation-of-advertisers/cross-media-measurement/pull/589
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetLedger.kt` line 61 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/583#-N3dS9j02t8fg7S2xoIC:-N3uRh__1OCmVzqRUaef:b-cuvxvf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ec274164de98777f39be2d8d67810d0c0001bd3b/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetLedger.kt#L61)):*
> moved to :https://github.com/world-federation-of-advertisers/cross-media-measurement/pull/589
moved to :https://github.com/world-federation-of-advertisers/cross-media-measurement/pull/589
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetLedger.kt` line 62 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/583#-N3fiAPFCGoLdidsDWID:-N3uRhsx6Y5HdjKjl-_H:b-40z3tm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ec274164de98777f39be2d8d67810d0c0001bd3b/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetLedger.kt#L62)):*
<details><summary><i>Previously, matthewclegg (Matthew Clegg) wrote…</i></summary><blockquote>

Why is a reference needed?
</blockquote></details>

moved to :https://github.com/world-federation-of-advertisers/cross-media-measurement/pull/589
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetManager.kt` line 149 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/583#-N3fjdz_9FDqlccyaAw-:-N3uRj5P2eQ6DatoFjV3:b-40z3tm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ec274164de98777f39be2d8d67810d0c0001bd3b/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetManager.kt#L149)):*
<details><summary><i>Previously, matthewclegg (Matthew Clegg) wrote…</i></summary><blockquote>

Also here, I don't understand the need to include a reference, and I would have it return a boolean value representing whether or not there is available budget for the proposed query.
</blockquote></details>

moved to :https://github.com/world-federation-of-advertisers/cross-media-measurement/pull/589
___
*[`src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetManager.kt` line 150 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/583#-N3fsvp8DIvzdg60mlSJ:-N3uSMNX4C_atcLSOkUB:b-cuvxvf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ec274164de98777f39be2d8d67810d0c0001bd3b/src/main/kotlin/org/wfanet/measurement/eventdataprovider/privacybudgetmanagement/PrivacyBudgetManager.kt#L150)):*
> moved to :https://github.com/world-federation-of-advertisers/cross-media-measurement/pull/589
moved to :https://github.com/world-federation-of-advertisers/cross-media-measurement/pull/589
___
*[`src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2MillTest.kt` line 319 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/583#-N3fkUsl68vLc8g1icn0:-N3uSJFJ8WfAw03b6Vi4:b77jiih) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ec274164de98777f39be2d8d67810d0c0001bd3b/src/test/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2MillTest.kt#L319)):*
<details><summary><i>Previously, matthewclegg (Matthew Clegg) wrote…</i></summary><blockquote>

I don't understand how the changes in this file relate to checking privacy budget.  Could you please explain?
</blockquote></details>

You are right, split the PR.


<!-- Sent from Reviewable.io -->

2022-06-17 17:09 UTC, duliomatos1 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/583)* status: 1 of 15 files reviewed, 7 unresolved discussions (waiting on @duliomatos1 and @matthewclegg)

___
*[`-- commits` line 1 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/583#-N3fnOt-2WZo0JE_OKBL):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

> Why is a reference needed?
Thank you Matthew, I agree. Im abandoning this PR, and splitting it. I moved your and @duliomatos1 's comments to the new PR : https://github.com/world-federation-of-advertisers/cross-media-measurement/pull/589
</blockquote></details>

@uakyol are you abandoning this PR?


<!-- Sent from Reviewable.io -->

2026-05-15 16:12 UTC, closed without merging