Remove infinite loop that occurs when duchies generate exceptions
world-federation-of-advertisers/cross-media-measurement pull request #608
Opened 2022-06-21 19:18 UTC by matthewclegg

There are numerous reasons why exceptions can occur during the processing of a measurement request.  One example is when an invalid value of delta is given, but many others can be found by grepping for 'error' in the code.  When an exception is generated, the Herald enters an infinite loop of continuously retrying the request that generated the exception.  This pull request eliminates this infinite loop.

Unfortunately, this is only part of work that has to be done to correct the way in which exceptions are handled.  It appears that currently, the herald has no way of propagating exceptions back to the kingdom.  Consequently, a failed computation will permanently appear to be in progress and will never progress to the COMPLETED or FAILED state, and the measurement consumer will never learn why their computation failed.  This will take more significant rework, which is deferred to a future PR.

2022-06-21 19:40 UTC, SanjayVas requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/608)* status: all files reviewed, 2 unresolved discussions (waiting on @matthewclegg)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/608#-N56k2T1ArY6lmcNAVN3:-N56k2T21TgXo4iJUnjx:b-z77uoi) (no related file):*
>  the herald has no way of propagating exceptions back to the kingdom

It does, it's just not currently used. See https://github.com/world-federation-of-advertisers/cross-media-measurement/issues/584

___
*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/608#-N56kNZQ-TsrkVhvNK_r:-N56kNZR4xVvnekBIQ19:b-v83qzm) (no related file):*
Is this related to https://github.com/world-federation-of-advertisers/cross-media-measurement/issues/585 ?

___
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt` line 120 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/608#-N56kz5rDAJvMAIOdGTc:-N56kz5rDAJvMAIOdGTd:b-blehsf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/715386660e41013a29f5f6d1c91a9503e9eeece2/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt#L120)):*
> ```Kotlin
>       .catch { e ->
>         logger.log(Level.SEVERE, "Exception:", e)
>         // TODO: Fail the computation and communicate the exception back to the Kingdom.
> ```

Reference https://github.com/world-federation-of-advertisers/cross-media-measurement/issues/584 in the TODO using the format described in [Code Style](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/docs/code-style.md#todos)

Note that the tricky part isn't communicating permanent failure to the Kingdom, but rather figuring out whether the error is indeed permanent vs. retriable at a higher level. I suppose it's better to err on the side of permanent failure than to let a computation get stuck forever?


<!-- Sent from Reviewable.io -->

2022-07-23 19:44 UTC, matthewclegg reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/608)* status: all files reviewed, 2 unresolved discussions (waiting on @SanjayVas)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/608#-N56k2T1ArY6lmcNAVN3:-N7gXuDw6fv9avFSunRq:b-dhpu2v) (no related file):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

>  the herald has no way of propagating exceptions back to the kingdom

It does, it's just not currently used. See https://github.com/world-federation-of-advertisers/cross-media-measurement/issues/584
</blockquote></details>

Yes, I was aware of that, but thanks for pointing it out.  I did not know that an issue had an issue had been filed.

___
*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/608#-N56kNZQ-TsrkVhvNK_r:-N7gYROiAkaFjYjj6slv:bjnbqax) (no related file):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Is this related to https://github.com/world-federation-of-advertisers/cross-media-measurement/issues/585 ?
</blockquote></details>

No, I believe this is different.  The problem that is addressed by this PR is changing the order of the two lines of code at lines 112-113.  In the current implementation, if an exception occurs in the call to processSystemComputationChange, the token will never be updated.  Consequently, the herald will attempt to re-process the response repeatedly, each time re-generating the exception.  By changing the order of these two lines of code, only a single exception will be generated for any given response.

___
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt` line 120 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/608#-N56kz5rDAJvMAIOdGTc:-N7gZTdpC1KJl42jKdeB:bjabo3c) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/715386660e41013a29f5f6d1c91a9503e9eeece2/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt#L120)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Reference https://github.com/world-federation-of-advertisers/cross-media-measurement/issues/584 in the TODO using the format described in [Code Style](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/docs/code-style.md#todos)

Note that the tricky part isn't communicating permanent failure to the Kingdom, but rather figuring out whether the error is indeed permanent vs. retriable at a higher level. I suppose it's better to err on the side of permanent failure than to let a computation get stuck forever?
</blockquote></details>

I would agree.  My opinion is that exceptions that are retriable should be caught at the call site and retried there.  Exceptions making it up to this level should be treated as non-retriable.  However, that is not the point of this PR.  The purpose of this PR is to fix the infinite retry loop that occurs when an exception is generated (see lines 112-113).   I just added these comments to provide some guidance to the next person who works on this code.  If you would like me to remove these comments, let me know.


<!-- Sent from Reviewable.io -->

2022-08-05 11:30 UTC, matthewclegg reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/608)* status: all files reviewed, 2 unresolved discussions (waiting on @SanjayVas)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/608#-N56kNZQ-TsrkVhvNK_r:-N8hlNAa1w9PKgMLM-hY:bb7mm0n) (no related file):*
<details><summary><i>Previously, matthewclegg (Matthew Clegg) wrote…</i></summary><blockquote>

No, I believe this is different.  The problem that is addressed by this PR is changing the order of the two lines of code at lines 112-113.  In the current implementation, if an exception occurs in the call to processSystemComputationChange, the token will never be updated.  Consequently, the herald will attempt to re-process the response repeatedly, each time re-generating the exception.  By changing the order of these two lines of code, only a single exception will be generated for any given response.
</blockquote></details>

ping

___


<!-- Sent from Reviewable.io -->

2022-08-05 21:36 UTC, SanjayVas reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/608)* status: all files reviewed, 2 unresolved discussions (waiting on @matthewclegg and @SanjayVas)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/608#-N56kNZQ-TsrkVhvNK_r:-N8jp1o_Aqr4Ck9xLKUH:bdvbmgx) (no related file):*
Sorry for missing this. I believe that #586 solved the infinite loop within a single running Herald. It changed the exception handling behavior such that the exception will bubble up once the retry limit has been reached.

There is still a "bigger" infinite loop that can occur on subsequent Herald restarts, which is what #584 describes. I don't know enough about the various states to be able to determine when the computation should be cancelled (marked as FAILED) vs. when it's still possible for it to enter a good state where it can proceed. Ideally we wouldn't just treat all errors as eventually recoverable, but I don't know whether it's safe to treat them all as permanent failures either due to the previous comment:

> This will keep the continuation token at the last successfully processed item. A later execution of syncStatuses() may be successful if the state at the kingdom and/or this duchy was updated.

If you are confident that it's okay to just mark these as failed after the current retry attempts fail ,then just have the code call the method that was introduced in #84.

___


<!-- Sent from Reviewable.io -->

2022-08-19 16:40 UTC, matthewclegg reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/608)* status: all files reviewed, 2 unresolved discussions (waiting on @SanjayVas)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/608#-N56kNZQ-TsrkVhvNK_r:-N9qtv1J1h-HhdbRyNdA:bhzto7e) (no related file):*
> #586

Unfortunately, I believe the code in pr #586 is incorrect as written (and merged).  None of the functions in the call stack leading to syncStatuses have any exception handling code, so I believe pr #586 will cause the Herald to crash whenever an exception occurs.  In fact, I believe it will result in crash-looping.  That's because the continuation token for the last processed computation at the Herald never gets updated, so the computation causing the exception will be retried each time the Herald restarts.  Rethrowing the exception and catching it at a higher level unfortunately does not work.  The reason for that is that the continuation token is then lost, and so the task that generated the exception will be re-executed, again resulting in an infinite loop.  

Since this code is part of the Duchy, how about letting me take the lead on fixing these bugs?

___


<!-- Sent from Reviewable.io -->

2022-08-19 16:59 UTC, SanjayVas approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/608)* status: all files reviewed, 2 unresolved discussions (waiting on @matthewclegg)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/608#-N56kNZQ-TsrkVhvNK_r:-N9r08C07wGpKtTorLoh:byw3lnu) (no related file):*
>  I believe pr #586 will cause the Herald to crash whenever an exception occurs. In fact, I believe it will result in crash-looping.

Yes, this is the known behavior after that PR. This is what I mean by "bigger infinite loop". The PR was mainly to address the coroutine handling, with the side effect of bubbling up the exception instead of retrying infinitely.

> Since this code is part of the Duchy, how about letting me take the lead on fixing these bugs?

Sure. Going ahead and approving, though note the caveat that there is a comment indicating why the statements are in the order they are in. I'll leave it to you to determine whether this is safe and/or preferred.

___
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt` line 120 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/608#-N56kz5rDAJvMAIOdGTc:-N9r10TJDMaAfNRLLWD6:b88xw3f) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/715386660e41013a29f5f6d1c91a9503e9eeece2/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt#L120)):*
> My opinion is that exceptions that are retriable should be caught at the call site and retried there.

I agree with this as well. I don't like the retry logic here at all, but was concerned with hitting the race condition mentioned in #585 . I don't know enough about the Duchy to understand the correct retry behavior. As discussed offline, I'll leave this to you. My comment here was just to reference the filed bugs in the TODO and give background on the issue.


<!-- Sent from Reviewable.io -->

2026-05-15 16:18 UTC, closed without merging