Implement internal reports service
world-federation-of-advertisers/cross-media-measurement pull request #611
Opened 2022-06-23 17:39 UTC by tristanvuong2021

2022-06-24 21:56 UTC, SanjayVas requested changes
> Reviewed 5 of 22 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/611)* status: 6 of 22 files reviewed, 4 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/PostgresReportsService.kt` line 67 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/611#-N5MX9zB83MY20EQLMq6:-N5MX9zB83MY20EQLMq7:b-6u7bl3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/54846f2b54d7de4c12d42b6496fb00e9ecc0ccef/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/PostgresReportsService.kt#L67)):*
> ```Kotlin
>   }
> 
>   override suspend fun setReportResult(request: SetReportResultRequest): Report {
> ```

Why do we need a `SetReportResult` method? Shouldn't the report result be computed as part of `SetMeasurementResult` if it happens to be the final succeeded measurement?
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/ReportReader.kt` line 64 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/611#-N5MZ9T79XrbO_bHVBH7:-N5MZ9T79XrbO_bHVBH8:ba104jv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/54846f2b54d7de4c12d42b6496fb00e9ecc0ccef/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/ReportReader.kt#L64)):*
> ```Kotlin
>       ReportIdempotencyKey,
>       CreateTime,
>       (SELECT json_build_object('TimeIntervals', json_agg(
> ```

nit: indent multi-line parenthetical expressions for improved readability

```sql
SELECT
  AuthorId,
  Name,
  ARRAY(
    SELECT json_build_object(
      'bookId', BookId,
      'title', Title
    ) FROM Books WHERE Books.AuthorId = Authors.AuthorId
  )
FROM Authors
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/ReportReader.kt` line 64 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/611#-N5Mfpqj3tl00ueXHnnq:-N5Mfpqj3tl00ueXHnnr:b1trgt1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/54846f2b54d7de4c12d42b6496fb00e9ecc0ccef/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/ReportReader.kt#L64)):*
> ```Kotlin
>       ReportIdempotencyKey,
>       CreateTime,
>       (SELECT json_build_object('TimeIntervals', json_agg(
> ```

Your top-level repeated fields should be SQL arrays.



_Code quote:_
```Kotlin
json_agg
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/ReportReader.kt` line 120 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/611#-N5MYoUi8b8LHdW62tjd:-N5MYoUi8b8LHdW62tje:bdvyx1a) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/54846f2b54d7de4c12d42b6496fb00e9ecc0ccef/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/ReportReader.kt#L120)):*
> ```Kotlin
>                       AND MeasurementCalculations.ReportId = TimeIntervals.ReportId
>                       AND MeasurementCalculations.TimeIntervalId = TimeIntervals.TimeIntervalId
>                   ) TimeInterval,
> ```

nit: prefer including the `AS` keyword for aliases


<!-- Sent from Reviewable.io -->

2022-06-24 22:37 UTC, tristanvuong2021 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/611)* status: 6 of 22 files reviewed, 4 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/PostgresReportsService.kt` line 67 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/611#-N5MX9zB83MY20EQLMq6:-N5Mqx0P1coSWih3jbw_:b-rmyz8q) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/54846f2b54d7de4c12d42b6496fb00e9ecc0ccef/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/PostgresReportsService.kt#L67)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Why do we need a `SetReportResult` method? Shouldn't the report result be computed as part of `SetMeasurementResult` if it happens to be the final succeeded measurement?
</blockquote></details>

I was assuming the measurements would be updated, then the result proto would be created, which would then be stored with this method.


<!-- Sent from Reviewable.io -->

2022-06-25 00:53 UTC, SanjayVas requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/611)* status: 6 of 22 files reviewed, 4 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/PostgresReportsService.kt` line 67 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/611#-N5MX9zB83MY20EQLMq6:-N5NKpyI7y_VlDG1Has4:b-ra4nak) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/54846f2b54d7de4c12d42b6496fb00e9ecc0ccef/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/PostgresReportsService.kt#L67)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

I was assuming the measurements would be updated, then the result proto would be created, which would then be stored with this method.
</blockquote></details>

That should happen as part of SetMeasurementResult so it can be done in the same transaction. Otherwise you could have a state where the Measurements are all completed but there's no Report result.


<!-- Sent from Reviewable.io -->

2022-06-27 16:58 UTC, SanjayVas requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/611)* status: 6 of 22 files reviewed, 4 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/PostgresReportsService.kt` line 67 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/611#-N5MX9zB83MY20EQLMq6:-N5a44vnDGHkrDS96JLH:b-65xu91) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/54846f2b54d7de4c12d42b6496fb00e9ecc0ccef/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/PostgresReportsService.kt#L67)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

That seems okay to me. That just means all the measurements are ready and just the last step of computing the report result is required.
</blockquote></details>

There's no need for that to be a separate process/state though, especially as it's not a state that's directly represented in the Report. . It's clearer from a DB consistency point-of-view to have Report SUCCEEDED <=> all Measurements SUCCEEDED. The main reason not to do that would be e.g. if computing the final result was an intensive operation that needed more time and should therefore be asynchronous. If that were the case, we'd likely want a separate Report state to represent it.


<!-- Sent from Reviewable.io -->

2022-07-02 00:13 UTC, tristanvuong2021 commented
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/PostgresReportsService.kt` line 67 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/611#-N5MX9zB83MY20EQLMq6:-N5wF9Py4KKMsWxhMO9M:b1a272j) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/54846f2b54d7de4c12d42b6496fb00e9ecc0ccef/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/PostgresReportsService.kt#L67)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Changes to set measurement result will be in a separate PR. Too big for one PR.


<!-- Sent from Reviewable.io -->

2022-07-02 01:55 UTC, SanjayVas requested changes
> Reviewed 2 of 22 files at r1, 4 of 15 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/611)* status: 7 of 28 files reviewed, 14 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/ReportingSetReader.kt` line 78 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/611#-N5wI7txB4ys-FV1uYP7:-N5wI7txB4ys-FV1uYP8:b-gznfzl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/344d3da800e456cf1a8e38c565e8fc0575bfd0d1/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/ReportingSetReader.kt#L78)):*
> ```Kotlin
>     limit: Int = 0
>   ): Flow<Result> {
>     val builder =
> ```

nit: rename, since it's a statement and not a builder.



_Code quote:_
```Kotlin
builder
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/ReportReader.kt` line 64 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/611#-N5wIcRP5TY2zvx86r0d:-N5wIcRP5TY2zvx86r0e:b74znwu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/344d3da800e456cf1a8e38c565e8fc0575bfd0d1/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/ReportReader.kt#L64)):*
> ```Kotlin
>       ReportIdempotencyKey,
>       CreateTime,
>       (
> ```

Do you need `array_agg`, or can you just wrap the outside in ARRAY?

e.g.
```sql
SELECT
  AuthorId,
  Name,
  ARRAY(SELECT ROW(BookId, Title) FROM Books WHERE Books.AuthorId = Authors.AuthorId)
FROM Authors
```

but with `json_build_object` instead of `ROW`
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/ReportReader.kt` line 67 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/611#-N5wK3IU1OXkdrz62U5q:-N5wK3IU1OXkdrz62U5r:bdisezp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/344d3da800e456cf1a8e38c565e8fc0575bfd0d1/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/ReportReader.kt#L67)):*
> ```Kotlin
>         SELECT array_agg(
>           json_build_object(
>             'TimeIntervalId', TimeIntervalId,
> ```

super nit: JSON field names are conventionally `lowerCamelCase`



_Code quote:_
```Kotlin
TimeIntervalId
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/ReportReader.kt` line 104 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/611#-N5wJKC11ChvNDb1JnjT:-N5wJKC11ChvNDb1JnjU:bdv1xji) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/344d3da800e456cf1a8e38c565e8fc0575bfd0d1/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/ReportReader.kt#L104)):*
> ```Kotlin
>             MetricDetailsJson,
>             (
>               SELECT json_agg(
> ```

Hmm, we've never had to do a second layer deep of something repeated before.

Up to you on whether this warrants breaking up into a separate query. I assume we're also only doing arrays when cardinality demands it and a join wouldn't be sufficient.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/ReportReader.kt` line 280 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/611#-N5wLLGfDuvk443aV_Sk:-N5wLLGfDuvk443aV_Sl:b-llc4pd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/344d3da800e456cf1a8e38c565e8fc0575bfd0d1/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/ReportReader.kt#L280)):*
> ```Kotlin
>       val readContext = client.readTransaction()
>       try {
>         readContext.executeQuery(statement).consume(::translate).collect { emit(it) }
> ```

nit: can use `emitAll`



_Code quote:_
```Kotlin
.collect { emit(it) }
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/ReportReader.kt` line 294 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/611#-N5wLoST6i43A0soAZji:-N5wLoSUE1RBIHZMSgzU:bszw1xr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/344d3da800e456cf1a8e38c565e8fc0575bfd0d1/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/ReportReader.kt#L294)):*
> ```Kotlin
>       details = row.getProtoMessage("ReportDetails", Report.Details.parser())
>       reportIdempotencyKey = row["ReportIdempotencyKey"]
>       val createTime: Instant = row["CreateTime"]
> ```

Use the `toProtoTime` extension.

e.g.

```kotlin
createTime = row.get<Instant>("CreateTime").toProtoTime()
```



_Code quote:_
```Kotlin
      val createTime: Instant = row["CreateTime"]
      this.createTime = timestamp {
        seconds = createTime.epochSecond
        nanos = createTime.nano
      }
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/ReportReader.kt` line 299 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/611#-N5wNwll5Iz7lTp9c3Sl:-N5wNwll5Iz7lTp9c3Sm:bhkrddl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/344d3da800e456cf1a8e38c565e8fc0575bfd0d1/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/ReportReader.kt#L299)):*
> ```Kotlin
>         nanos = createTime.nano
>       }
>       val periodicTimeInterval: String? = row["PeriodicTimeInterval"]
> ```

Use `io.r2dbc.postgresql.codec.Json` instead. That way we're explicit about expecting a JSON value.

It also may be more efficient in terms of copies to use `mapInputStream` to be able to call `JsonParser.parseReader`.



_Code quote:_
```Kotlin
String
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/ReportReader.kt` line 309 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/611#-N5wR_b08b6LuOHUM1Oz:-N5wR_b08b6LuOHUM1P-:b7dqoh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/344d3da800e456cf1a8e38c565e8fc0575bfd0d1/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/ReportReader.kt#L309)):*
> ```Kotlin
>   }
> 
>   private fun buildPeriodicTimeInterval(jsonString: String): PeriodicTimeInterval {
> ```

nit: prefer doing the parsing outside so that we can pass better types, e.g. `JsonObject`



_Code quote:_
```Kotlin
jsonString: String
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/writers/CreateReport.kt` line 89 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/611#-N5wTpa85TcRpQdEUYkU:-N5wTpa85TcRpQdEUYkV:bt9i3x) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/344d3da800e456cf1a8e38c565e8fc0575bfd0d1/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/writers/CreateReport.kt#L89)):*
> ```Kotlin
>         bind("$3", externalReportId)
>         bind("$4", Report.State.RUNNING_VALUE)
>         bind("$5", report.details.toByteArray())
> ```

Just `report.details`. There's a `bind` overload that handles protobuf messages properly for you.



_Code quote:_
```Kotlin
report.details.toByteArray()
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/writers/CreateReport.kt` line 91 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/611#-N5wUhkT7_gE6xC6ETN0:-N5wUhkT7_gE6xC6ETN1:boa7vig) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/344d3da800e456cf1a8e38c565e8fc0575bfd0d1/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/writers/CreateReport.kt#L91)):*
> ```Kotlin
>         bind("$5", [...]

2022-07-06 00:28 UTC, tristanvuong2021 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/611)* status: 7 of 28 files reviewed, 7 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/ReportReader.kt` line 294 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/611#-N5wLoST6i43A0soAZji:-N6FP-Fe7_w-MRkLEEqh:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/344d3da800e456cf1a8e38c565e8fc0575bfd0d1/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/ReportReader.kt#L294)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Use the `toProtoTime` extension.

e.g.

```kotlin
createTime = row.get<Instant>("CreateTime").toProtoTime()
```
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/ReportReader.kt` line 299 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/611#-N5wNwll5Iz7lTp9c3Sl:-N6Fniab-uwONz8tRzwp:b-m8hait) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/344d3da800e456cf1a8e38c565e8fc0575bfd0d1/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/ReportReader.kt#L299)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Use `io.r2dbc.postgresql.codec.Json` instead. That way we're explicit about expecting a JSON value.

It also may be more efficient in terms of copies to use `mapInputStream` to be able to call `JsonParser.parseReader`.
</blockquote></details>

That type isn't nullable so the get fails when it is null. For the second thing, I could replace the arrays with json arrays in order to do that.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/writers/CreateReport.kt` line 89 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/611#-N5wTpa85TcRpQdEUYkU:-N6FP4Lt-jgT9lqpX2wh:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/344d3da800e456cf1a8e38c565e8fc0575bfd0d1/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/writers/CreateReport.kt#L89)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Just `report.details`. There's a `bind` overload that handles protobuf messages properly for you.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/writers/CreateReport.kt` line 91 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/611#-N5wUhkT7_gE6xC6ETN0:-N6FplW9CVvCckvqlrvh:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/344d3da800e456cf1a8e38c565e8fc0575bfd0d1/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/writers/CreateReport.kt#L91)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Don't we want to use a DB timestamp? e.g. `CURRENT_TIMESTAMP`?

See https://www.postgresql.org/docs/current/functions-datetime.html#FUNCTIONS-DATETIME-CURRENT
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/writers/CreateReport.kt` line 151 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/611#-N5wWTmN54egZChZHM73:-N6Fo9QIBebmCcQcUCQ8:bbcrugp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/344d3da800e456cf1a8e38c565e8fc0575bfd0d1/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/writers/CreateReport.kt#L151)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Ohhh, that's what the `add` method on the underlying `Statement` is for! Leave a TODO here for me so I can add support for that.

I think the syntax would end up something like 

```kotlin
boundStatement("INSERT INTO Measurements (MeasurementConsumerReferenceId, MeasurementReferenceId, State) VALUES ($1, $2, $3)") {
  measurements.forEach {
    add {
      bind("$1", it.measurementConsumerReferenceId)
      bind("$2", it.measurementReferenceId)
      bind("$3", Measurement.State.PENDING_VALUE)
    }
  }
}
```

This already makes me miss Spanner's mutations API.
</blockquote></details>

I am not sure if Statement add does the values list or separate queries
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/writers/CreateReport.kt` line 227 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/611#-N5waipIAT4JkO8G7AVp:-N6FRV_n1PZKHVYTojEq:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/344d3da800e456cf1a8e38c565e8fc0575bfd0d1/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/writers/CreateReport.kt#L227)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Do you need the mutable HashMap implementation specifically? If not, prefer `mutableMapOf()` to create a `MutableMap` which you can return as a `Map` if the caller need not mutate it after the fact.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/writers/CreateReport.kt` line 509 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/611#-N5waIVP1vCsUn3nK_zB:-N6FSLbn3wNHyyQG-hnn:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/344d3da800e456cf1a8e38c565e8fc0575bfd0d1/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/writers/CreateReport.kt#L509)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

What's wrong with the default implementation of these methods on the `TimeInterval` proto message?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-12 21:10 UTC, SanjayVas requested changes
> Reviewed 1 of 1 files at r3, 1 of 13 files at r4, 1 of 2 files at r5, 11 of 15 files at r6, 2 of 7 files at r7, 2 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/611)* status: 21 of 28 files reviewed, 4 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/ReportReader.kt` line 299 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/611#-N5wNwll5Iz7lTp9c3Sl:-N6nzeeHEMBL6RMFa-oQ:b-tvplpz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/344d3da800e456cf1a8e38c565e8fc0575bfd0d1/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/ReportReader.kt#L299)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

That type isn't nullable so the get fails when it is null. For the second thing, I could replace the arrays with json arrays in order to do that.
</blockquote></details>

I'm not sure what you mean. Wouldn't something like this work?

```kotlin
val periodicTimeInterval: Json? = row["PeriodicTimeInterval"]
if (periodicTimeInterval != null) {
  this.periodicTimeInterval = buildPeriodicTimeInterval(periodicTimeInterval.toJsonElement().asJsonObject)
}
```

```kotlin
private fun Json.toJsonElement(): JsonElement {
  return mapInputStream { input -> input.use { JsonParser.parseReader(it.reader()) } }
}
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/ReportReader.kt` line 67 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/611#-N6nsfR61ADyhlpOtRWm:-N6nsfR61ADyhlpOtRWn:b-lizhbl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/770dbb854b3bed1ceb9d146692abf164d8b28b07/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/ReportReader.kt#L67)):*
> ```Kotlin
>       CreateTime,
>       (
>         SELECT ARRAY(
> ```

I think you can leave out this SELECT.

e.g.

```sql
    SELECT
      MeasurementConsumerReferenceId,
      ReportId,
      ExternalReportId,
      State,
      ReportDetails,
      ReportIdempotencyKey,
      CreateTime,
      ARRAY(
        SELECT Bar
        FROM Foos
      ) AS FooBars
```



_Code quote:_
```Kotlin
 SELECT 
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/writers/CreateReport.kt` line 151 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/611#-N5wWTmN54egZChZHM73:-N6o6Mz7CDAITsBXIooT:bg5i5ew) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/344d3da800e456cf1a8e38c565e8fc0575bfd0d1/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/writers/CreateReport.kt#L151)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

I am not sure if Statement add does the values list or separate queries
</blockquote></details>

It's an implementation detail of Statement. We needn't care about it until/unless it creates a performance issue, as long as the rows all get inserted.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/writers/CreateReport.kt` line 284 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/611#-N6oD_ln7xz1xLNFsST7:-N6oD_ln7xz1xLNFsST8:b12nupk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/770dbb854b3bed1ceb9d146692abf164d8b28b07/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/writers/CreateReport.kt#L284)):*
> ```Kotlin
>         bind("$2", reportId)
>         bind("$3", metricId)
>         bind("$4", metric.details.toByteString().base64UrlEncode())
> ```

Just `metric.details`, which will take care of serialization for you.

We want to always use binary proto serialization, not JSON or Base64 or whatever other encoding.



_Code quote:_
```Kotlin
metric.details.toByteString().base64UrlEncode()
```


<!-- Sent from Reviewable.io -->

2022-07-12 21:31 UTC, tristanvuong2021 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/611)* status: 21 of 28 files reviewed, 3 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/writers/CreateReport.kt` line 284 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/611#-N6oD_ln7xz1xLNFsST7:-N6oIsXJ7VgRRPkDc85T:b-dhkarj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/770dbb854b3bed1ceb9d146692abf164d8b28b07/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/writers/CreateReport.kt#L284)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Just `metric.details`, which will take care of serialization for you.

We want to always use binary proto serialization, not JSON or Base64 or whatever other encoding.
</blockquote></details>

But it is read as a json value later.


<!-- Sent from Reviewable.io -->

2022-07-12 22:03 UTC, tristanvuong2021 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/611)* status: 19 of 28 files reviewed, 2 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/ReportReader.kt` line 299 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/611#-N5wNwll5Iz7lTp9c3Sl:-N6oPJ7RBcHAoOA8d7pd:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/344d3da800e456cf1a8e38c565e8fc0575bfd0d1/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/ReportReader.kt#L299)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I'm not sure what you mean. Wouldn't something like this work?

```kotlin
val periodicTimeInterval: Json? = row["PeriodicTimeInterval"]
if (periodicTimeInterval != null) {
  this.periodicTimeInterval = buildPeriodicTimeInterval(periodicTimeInterval.toJsonElement().asJsonObject)
}
```

```kotlin
private fun Json.toJsonElement(): JsonElement {
  return mapInputStream { input -> input.use { JsonParser.parseReader(it.reader()) } }
}
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-12 23:31 UTC, SanjayVas requested changes
> Reviewed 1 of 2 files at r9.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/611)* status: 20 of 28 files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/writers/CreateReport.kt` line 284 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/611#-N6oD_ln7xz1xLNFsST7:-N6ofFkU06EGJLqz58d7:bwapory) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/770dbb854b3bed1ceb9d146692abf164d8b28b07/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/writers/CreateReport.kt#L284)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

But it is read as a json value later.
</blockquote></details>

We still want to store as bytes. You can encode in the query if you need to.

e.g.

```sql
SELECT json_build_object(
  'bookId', BookId,
  'title', Title,
  'barcode', encode(Barcode, 'base64')
)
FROM Books
```


<!-- Sent from Reviewable.io -->

2022-07-13 00:21 UTC, tristanvuong2021 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/611)* status: 18 of 28 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/writers/CreateReport.kt` line 284 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/611#-N6oD_ln7xz1xLNFsST7:-N6ovaWJ0IQLWvKkbEOu:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/770dbb854b3bed1ceb9d146692abf164d8b28b07/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/writers/CreateReport.kt#L284)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

We still want to store as bytes. You can encode in the query if you need to.

e.g.

```sql
SELECT json_build_object(
  'bookId', BookId,
  'title', Title,
  'barcode', encode(Barcode, 'base64')
)
FROM Books
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-13 17:45 UTC, SanjayVas approved these changes
> Reviewed 3 of 22 files at r1, 3 of 7 files at r7, 1 of 2 files at r9, 3 of 3 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/611)* status: all files reviewed, 3 unresolved discussions (waiting on @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/ReportReader.kt` line 82 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/611#-N6sKWFDD0G6tiRoCSfb:-N6sKWFDD0G6tiRoCSfc:bb1ub3e) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4def95e548d19827769942fee96633fb1b63ff58/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/ReportReader.kt#L82)):*
> ```Kotlin
>       ) AS TimeIntervals,
>       (
>         SELECT json_build_object(
> ```

I'd personally avoid JSON where we don't need it, only using it for cardinality reasons. This case looks like there's 0 or 1, meaning you should either have a set of columns that have values or are all `NULL`.

JSON is a poor substitute for a struct type :(
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/ReportReader.kt` line 105 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/611#-N6sMwMm5p_a1ZwIvCyu:-N6sMwMm5p_a1ZwIvCyv:bjxgbbg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4def95e548d19827769942fee96633fb1b63ff58/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/ReportReader.kt#L105)):*
> ```Kotlin
>           SELECT
>             MetricId,
>             encode(MetricDetails, 'base64') AS MetricDetails,
> ```

nit: put the encoding in `json_build_object`, so that it's clear it's only being done so it can fit inside JSON



_Code quote:_
```Kotlin
encode(MetricDetails, 'base64')
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/ReportReader.kt` line 467 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/611#-N6se2Qy5S-YZZ6jcPP8:-N6se2Qy5S-YZZ6jcPP9:b-ayvz5a) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4def95e548d19827769942fee96633fb1b63ff58/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/ReportReader.kt#L467)):*
> ```Kotlin
>   private fun Json.toJsonElement(): JsonElement {
>     return mapInputStream { input -> input.use { JsonParser.parseReader(it.reader()) } }
>       as JsonElement
> ```

Doesn't `parseReader` always return a `JsonElement` already?



_Code quote:_
```Kotlin
      as JsonElement
```


<!-- Sent from Reviewable.io -->

2022-07-13 17:49 UTC, tristanvuong2021 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/611)* status: all files reviewed, 3 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/ReportReader.kt` line 105 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/611#-N6sMwMm5p_a1ZwIvCyu:-N6sf5gS1NxUPT5dX4Tt:bbkiavm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4def95e548d19827769942fee96633fb1b63ff58/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/ReportReader.kt#L105)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: put the encoding in `json_build_object`, so that it's clear it's only being done so it can fit inside JSON
</blockquote></details>

I tried that first, but I couldn't get it to work. encode wasn't being interpreted as a function.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/ReportReader.kt` line 467 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/611#-N6se2Qy5S-YZZ6jcPP8:-N6sfQXb6A2fFpma018P:bxpv707) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4def95e548d19827769942fee96633fb1b63ff58/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/ReportReader.kt#L467)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Doesn't `parseReader` always return a `JsonElement` already?
</blockquote></details>

It returns a JsonElement?.


<!-- Sent from Reviewable.io -->

2022-07-13 19:29 UTC, SanjayVas approved these changes
> Reviewed 3 of 3 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/611)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/ReportReader.kt` line 467 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/611#-N6se2Qy5S-YZZ6jcPP8:-N6snwjc-ASViEAtU5ME:btd2qww) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a3e92749b5cf6d5ba4f15e0d7dc15f809b466f22/src/main/kotlin/org/wfanet/measurement/reporting/deploy/postgres/readers/ReportReader.kt#L467)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

It returns a JsonElement?.
</blockquote></details>

Ah, it's because `mapInputStream` has its return value marked as unconditionally `@Nullable` rather than preserving the nullability of the return value type :(.

What you have is fine since you know `parseReader` won't return null, though writing it like this I think will preserve nullability:

```kotlin
  private inline fun <T> Json.useInputStream(crossinline block: (InputStream) -> T): T {
    return mapInputStream { input -> input.use(block) }
  }

  private fun Json.toJsonElement(): JsonElement {
    return useInputStream { input -> JsonParser.parseReader(input.reader()) }
  }
```


<!-- Sent from Reviewable.io -->

2022-07-14 17:27 UTC, stevenwarejones approved these changes
> Reviewed 5 of 22 files at r1, 5 of 7 files at r7, 2 of 3 files at r10, 3 of 3 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/611)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @duliomatos1)



<!-- Sent from Reviewable.io -->

2022-07-14 17:41 UTC, tristanvuong2021 reviewed
> Reviewed 4 of 4 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/611)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @duliomatos1)



<!-- Sent from Reviewable.io -->

2022-07-14 17:42 UTC, merged