Rieman list reports
world-federation-of-advertisers/cross-media-measurement pull request #613
Opened 2022-06-24 06:56 UTC by riemanli

2022-06-24 06:58 UTC, riemanli commented
@SanjayVas @tristanvuong2021 @renjiezh 
The PR is still WIP, but I would like to get some early feedback from you all.

2022-06-24 20:00 UTC, SanjayVas requested changes
> Reviewed 6 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/613)* status: 6 of 7 files reviewed, 7 unresolved discussions (waiting on @renjiezh, @riemanli, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportKey.kt` line 37 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/613#-N5M8eXj6T5XRFV3XUiz:-N5M8eXj6T5XRFV3XUj-:b-sett95) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8cb501c456d30edb7f65bcc2256c1f72dcda464d/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportKey.kt#L37)):*
> ```Kotlin
>   }
> 
>   companion object {
> ```

nit: extend `ResourceKey.Factory`
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt` line 164 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/613#-N5M9ijV2m6xC2gQ7CEQ:-N5M9ijV2m6xC2gQ7CER:b-hr43n4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8cb501c456d30edb7f65bcc2256c1f72dcda464d/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt#L164)):*
> ```Kotlin
>           .map(InternalReport::toReport)
> 
>       if (results.size > listReportsPageToken.pageSize) {
> ```

nit: reduce the amount of logic inside of DSL builder scope when possible.

e.g. Outside the builder scope:
```kotlin
val nextPageToken: ListReportsPageToken? = // code that builds next page token or null
```

Then inside the builder scope:
```kotlin
if (nextPageToken != null) {
  this.nextPageToken = nextPageToken.toByteString().base64UrlEncode()
}
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt` line 179 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/613#-N5MBqxX8ebgi08HxKF9:-N5MBqxX8ebgi08HxKFA:b-50tww7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8cb501c456d30edb7f65bcc2256c1f72dcda464d/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt#L179)):*
> ```Kotlin
> 
>   /** Update an [InternalReport] and its [InternalMeasurement]s. */
>   private fun InternalReport.updateReport(): InternalReport {
> ```

This use of a receiver method is misleading, as I definitely wouldn't expect a method on a proto message to go off an do backend operations. You probably also want to be clearer about your operations, as `updateReport` in a CRUD service sounds like a method that takes in report message and writes it to a backend.

Perhaps more granular methods like `syncMeasurements`.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt` line 195 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/613#-N5MBI9QEHs8ihuCya4_:-N5MBI9QEHs8ihuCya4a:b-60o9el) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8cb501c456d30edb7f65bcc2256c1f72dcda464d/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt#L195)):*
> ```Kotlin
>     var allMeasurementSucceeded = true
>     var anyMeasurementFailed = false
>     for ((measurementReferenceID, internalMeasurement) in source.measurementsMap) {
> ```

`measurmentReferenceId`

See https://developer.android.com/kotlin/style-guide#camel_case



_Code quote:_
```Kotlin
measurementReferenceID
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt` line 215 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/613#-N5MHAMU7j80IgXcJYfw:-N5MHAMU7j80IgXcJYfx:ba8p70t) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8cb501c456d30edb7f65bcc2256c1f72dcda464d/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt#L215)):*
> ```Kotlin
> 
>     // Update report
>     if (allMeasurementSucceeded) {
> ```

Just to be clear on implementation, I'd expect an update of the internal Report resulting from a measurement state change to happen in the same DB transaction as the internal measurement. That is to say the internal `setMeasurementResult` or `setMeasurementFailure` implementation should be what updates the internal report. You can then just read the internal report after you finish syncing the measurements and return that.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt` line 243 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/613#-N5MCi9Z76dbvLeY1QPe:-N5MCi9_9kVqaxW6XiIo:btmiq34) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8cb501c456d30edb7f65bcc2256c1f72dcda464d/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt#L243)):*
> ```Kotlin
> 
>     val measurement =
>       runBlocking(Dispatchers.IO) {
> ```

Avoid `runBlocking` except when you need to interface with top-level non-coroutine code (e.g. from the `main` function or in a test). Make the function suspending instead.
___
*[`src/main/proto/wfa/measurement/internal/reporting/measurements_service.proto` line 22 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/613#-N5MGut53L0UOYuOw416:-N5MGut53L0UOYuOw417:bw16m53) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8cb501c456d30edb7f65bcc2256c1f72dcda464d/src/main/proto/wfa/measurement/internal/reporting/measurements_service.proto#L22)):*
> ```protobuf
> 
> option java_package = "org.wfanet.measurement.internal.reporting";
> option java_multiple_files = true;
> ```

Changes to the internal service API should be in a separate PR.


<!-- Sent from Reviewable.io -->

2022-06-24 23:07 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/613)* status: 5 of 8 files reviewed, 5 unresolved discussions (waiting on @renjiezh, @SanjayVas, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportKey.kt` line 37 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/613#-N5M8eXj6T5XRFV3XUiz:-N5MZU7S1SruplGFSMjm:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8cb501c456d30edb7f65bcc2256c1f72dcda464d/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportKey.kt#L37)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: extend `ResourceKey.Factory`
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt` line 164 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/613#-N5M9ijV2m6xC2gQ7CEQ:-N5McGKm-WiiItj-alqY:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8cb501c456d30edb7f65bcc2256c1f72dcda464d/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt#L164)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: reduce the amount of logic inside of DSL builder scope when possible.

e.g. Outside the builder scope:
```kotlin
val nextPageToken: ListReportsPageToken? = // code that builds next page token or null
```

Then inside the builder scope:
```kotlin
if (nextPageToken != null) {
  this.nextPageToken = nextPageToken.toByteString().base64UrlEncode()
}
```
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt` line 179 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/613#-N5MBqxX8ebgi08HxKF9:-N5MjE0r2JAsG0rIC6rj:bf7crpf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8cb501c456d30edb7f65bcc2256c1f72dcda464d/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt#L179)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This use of a receiver method is misleading, as I definitely wouldn't expect a method on a proto message to go off an do backend operations. You probably also want to be clearer about your operations, as `updateReport` in a CRUD service sounds like a method that takes in report message and writes it to a backend.

Perhaps more granular methods like `syncMeasurements`.
</blockquote></details>

I think this topic depends on the one you brought up about whether the internal `setMeasurementResult` or `setMeasurementFailure` should update the internal report.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt` line 195 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/613#-N5MBI9QEHs8ihuCya4_:-N5MZcgT5cgo1Jh0lDoH:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8cb501c456d30edb7f65bcc2256c1f72dcda464d/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt#L195)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

`measurmentReferenceId`

See https://developer.android.com/kotlin/style-guide#camel_case
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt` line 215 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/613#-N5MHAMU7j80IgXcJYfw:-N5MiOb904AslVi94Q8F:b4laq7a) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8cb501c456d30edb7f65bcc2256c1f72dcda464d/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt#L215)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Just to be clear on implementation, I'd expect an update of the internal Report resulting from a measurement state change to happen in the same DB transaction as the internal measurement. That is to say the internal `setMeasurementResult` or `setMeasurementFailure` implementation should be what updates the internal report. You can then just read the internal report after you finish syncing the measurements and return that.
</blockquote></details>

Does that mean the internal `setMeasurementResult` can know all measurements required by the report are ready? If that's the case, it will be easier for me. 

+@tristanvuong2021 to the discussion.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt` line 243 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/613#-N5MCi9Z76dbvLeY1QPe:-N5Mfi71-CS6V3gEyRrs:b2eay3w) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8cb501c456d30edb7f65bcc2256c1f72dcda464d/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt#L243)):*
> runBlocking

Thanks for pointing that out. Done.
___
*[`src/main/proto/wfa/measurement/internal/reporting/measurements_service.proto` line 22 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/613#-N5MGut53L0UOYuOw416:-N5M_Szi71oRrSWs_qNH:b-29wton) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8cb501c456d30edb7f65bcc2256c1f72dcda464d/src/main/proto/wfa/measurement/internal/reporting/measurements_service.proto#L22)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Changes to the internal service API should be in a separate PR.
</blockquote></details>

The changes are already in Tristan's PR. I just copied to make the code buildable. This change will disappear once Tristan's PR is merged to the main.


<!-- Sent from Reviewable.io -->

2022-06-27 20:44 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/613)* status: 4 of 9 files reviewed, 10 unresolved discussions (waiting on @renjiezh, @riemanli, @SanjayVas, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt` line 385 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/613#-N5aEvMh2egzoLrTx5rc:-N5agQuY2RPOmNw0lSNc:bad59sg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e85ccd9192de5a12512d55c73f241cb2fd275bd6/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt#L385)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: put the TODO inside the KDoc.
</blockquote></details>

Thanks for the suggestion. Done
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt` line 494 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/613#-N5aF9ws3RRe6OdLY7Y7:-N5agkkVCNwmGo2yri4x:b-2ntx0k) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e85ccd9192de5a12512d55c73f241cb2fd275bd6/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt#L494)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Should be able to do this with arithmetic rather than a loop.

IIUC, it should just be a division and modulus. Something like

```kotlin
val weightedTotalNanos: Long = (TimeUnit.SECONDS.toNanos(value.seconds) + value.nanos) * coefficient
val weightedSeconds: Long = TimeUnit.NANOS.toSeconds(weightedTotalNanos)
val weightedNanos = weightedTotalNanos % TimeUnit.SECONDS.toNanos(1)  // Or use 1_000_000_000 as a constant of NANOS_PER_SECOND
```

You could possibly add this as an extension `times` operator to Duration. See https://kotlinlang.org/docs/operator-overloading.html#arithmetic-operators
</blockquote></details>

That's a good point. Thanks for the suggestion! 
Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt` line 570 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/613#-N5aUx8s9rsMo_azR1OT:-N5am8cD3G4ujuLFsS3i:bad59sg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e85ccd9192de5a12512d55c73f241cb2fd275bd6/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt#L570)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: `toInternal`

Basically make sure everything that's an internal version is labelled as internal, so we can assume if it doesn't have "internal" anywhere that it's for this API.
</blockquote></details>

Thanks for the suggestion. Done
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt` line 622 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/613#-N5aV4W20k9PvMC-srhd:-N5an2lnEj_7TJn1Jcup:bad59sg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e85ccd9192de5a12512d55c73f241cb2fd275bd6/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt#L622)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: `toInternal`
</blockquote></details>

Thanks for the suggestion. Done
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt` line 744 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/613#-N5aXDCV1ieQADND1-TV:-N5anpKy2KO_AxMRN2i8:bzdahor) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e85ccd9192de5a12512d55c73f241cb2fd275bd6/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt#L744)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Don't pass this in just for validation. The fact that it's an LHS operand has no impact on the conversion of the operand itself, only on whether the operation itself is valid. Therefore if you want this validation, it should be on the operation and not the operand.
</blockquote></details>

Thanks for pointing this out. It's a very good suggestion! 
Removed the validation from this function and will add the validation to the operation function when it's implemented.
___
*[`src/main/proto/wfa/measurement/internal/reporting/measurements_service.proto` line 22 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/613#-N5MGut53L0UOYuOw416:-N5aoPGoCQ3hN48bSnvQ:b-4hvi0m) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8cb501c456d30edb7f65bcc2256c1f72dcda464d/src/main/proto/wfa/measurement/internal/reporting/measurements_service.proto#L22)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The way to represent that is to base this PR on the other pending PR branch. That way the diff doesn't misleadingly appear in code review.

A reviewer should be able to assume that any diff they see is from the PR itself.
</blockquote></details>

Got it.


<!-- Sent from Reviewable.io -->

2022-06-27 22:26 UTC, renjiezh reviewed
> Reviewed 1 of 2 files at r3, 3 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/613)* status: 7 of 9 files reviewed, 11 unresolved discussions (waiting on @renjiezh, @riemanli, @SanjayVas, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt` line 163 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/613#-N5audA2BaYpwdNVXR1M:-N5audA2BaYpwdNVXR1N:b1rq9pl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/54324eb7a7a383c57d2ae51847626f7c5c68dff0/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt#L163)):*
> ```Kotlin
>           lastReport = previousPageEnd {
>             measurementConsumerReferenceId =
>               results[results.lastIndex - 1].measurementConsumerReferenceId
> ```

nit: results.last()


<!-- Sent from Reviewable.io -->

2022-06-27 22:43 UTC, SanjayVas requested changes
> Reviewed 3 of 5 files at r4, 1 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/613)* status: 8 of 9 files reviewed, 12 unresolved discussions (waiting on @renjiezh, @riemanli, @SanjayVas, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt` line 215 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/613#-N5MHAMU7j80IgXcJYfw:-N5bCshpCd4e04bTnaLt:b4k1dak) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8cb501c456d30edb7f65bcc2256c1f72dcda464d/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt#L215)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Does that mean the internal `setMeasurementResult` can know all measurements required by the report are ready? If that's the case, it will be easier for me. 

+@tristanvuong2021 to the discussion.
</blockquote></details>

Yes. It should do a read on all other measurements in the Reports its in and see if all of the others have succeeded. If so, it should update the Report.

`setMeasurementFailure` should similarly set the Report to FAILED if it's not already.

This way, we can guarantee that the Report state and Measurement states are consistent with each other at all times, i.e. a Report being SUCCEEDED means all of its Measurements are SUCCEEDED and vice-versa. Similarly, any Measurement being failed means its corresponding Reports are FAILED.

This furthermore means that the only internal service method needed for updating a Report directly would be for cancellation.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt` line 20 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/613#-N5bJ2xJ0tVqgH4n32kw:-N5bJ2xJ0tVqgH4n32kx:b-c69jc2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dd44ba6985ebe6a8171a0694f9257edfc05b1b59/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt#L20)):*
> ```Kotlin
> import com.google.protobuf.duration
> import com.google.protobuf.util.Durations.add as durationsAdd
> import com.google.protobuf.util.Timestamps.add as timestampsAdd
> ```

Just import the enclosing util type and call the method on it, e.g. `Durations.add`.



_Code quote:_
```Kotlin
import com.google.protobuf.util.Durations.add as durationsAdd
import com.google.protobuf.util.Timestamps.add as timestampsAdd
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt` line 385 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/613#-N5bGcyP4urCqXPeejSX:-N5bGcyP4urCqXPeejSY:b7tir1v) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dd44ba6985ebe6a8171a0694f9257edfc05b1b59/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt#L385)):*
> ```Kotlin
>   }
> 
>   /** Convert an [InternalNamedSetOperation] to a [InternalResultColumn] of an [InternalReport] */
> ```

nit: "Converts"

See https://developer.android.com/kotlin/style-guide#summary_fragment



_Code quote:_
```Kotlin
Convert
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt` line 386 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/613#-N5bGycA0_xiCd0QRRhS:-N5bGycA0_xiCd0QRRhT:bxhdchb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dd44ba6985ebe6a8171a0694f9257edfc05b1b59/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt#L386)):*
> ```Kotlin
> 
>   /** Convert an [InternalNamedSetOperation] to a [InternalResultColumn] of an [InternalReport] */
>   private suspend fun InternalNamedSetOperation.toInternalResultColumn(
> ```

Since none of these extension functions should be accessing the state of the ReportsService instance, make them not instance methods of ReportsService. e.g. move them outside of the class or put them in its companion object.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt` line 419 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/613#-N5bI944133KIrjHH-Cm:-N5bI944133KIrjHH-Cn:b7ismm2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dd44ba6985ebe6a8171a0694f9257edfc05b1b59/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt#L419)):*
> ```Kotlin
>           )
> 
>         Pair(measurement, it.coefficient)
> ```

nit: make a data class instead of using Pair



_Code quote:_
```Kotlin
  Pair(measurement, it.coefficient)
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt` line 479 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/613#-N5bJEwd79M0ZuvJYzjg:-N5bJEwd79M0ZuvJYzjh:bm878dx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dd44ba6985ebe6a8171a0694f9257edfc05b1b59/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt#L479)):*
> ```Kotlin
>         measurement.result.watchDuration.value * coefficient
>       }
>       .reduce { sum, element -> durationsAdd(sum, element) }
> ```

Since you've already created a `times` operator, might as well create a `plus` operator so you can just do `sum + element`



_Code quote:_
```Kotlin
durationsAdd(sum, element)
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt` line 487 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/613#-N5bJVfx-j2s6E-NwMX0:-N5bJVfx-j2s6E-NwMX1:b8kun90) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dd44ba6985ebe6a8171a0694f9257edfc05b1b59/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt#L487)):*
> ```Kotlin
>   val source = this
>   return duration {
>     val weightedTotalNanos: Long =
> ```

nit: move this line outside of the DSL builder.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt` line 730 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/613#-N5bK0IS8H4v49HUp_t6:-N5bK0IS8H4v49HUp_t7:b45h) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dd44ba6985ebe6a8171a0694f9257edfc05b1b59/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt#L730)):*
> ```Kotlin
>     this.type = source.type.toType()
>     this.lhs = source.lhs.toOperand()
>     this.rhs = source.lhs.toOperand()
> ```





_Suggestion:_
```Kotlin
rhs
```


<!-- Sent from Reviewable.io -->

2022-06-27 23:04 UTC, tristanvuong2021 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/613)* status: 8 of 9 files reviewed, 12 unresolved discussions (waiting on @renjiezh, @riemanli, and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt` line 215 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/613#-N5MHAMU7j80IgXcJYfw:-N5bP5m-3BSeLgYQFiH8:b4tpo5o) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8cb501c456d30edb7f65bcc2256c1f72dcda464d/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt#L215)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Yes. It should do a read on all other measurements in the Reports its in and see if all of the others have succeeded. If so, it should update the Report.

`setMeasurementFailure` should similarly set the Report to FAILED if it's not already.

This way, we can guarantee that the Report state and Measurement states are consistent with each other at all times, i.e. a Report being SUCCEEDED means all of its Measurements are SUCCEEDED and vice-versa. Similarly, any Measurement being failed means its corresponding Reports are FAILED.

This furthermore means that the only internal service method needed for updating a Report directly would be for cancellation.
</blockquote></details>

I will need to update them both then.


<!-- Sent from Reviewable.io -->

2022-06-28 00:48 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/613)* status: 7 of 9 files reviewed, 11 unresolved discussions (waiting on @renjiezh, @riemanli, and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt` line 179 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/613#-N5MBqxX8ebgi08HxKF9:-N5axHVmBhYcmNdcdCH2:b80mkhj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8cb501c456d30edb7f65bcc2256c1f72dcda464d/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt#L179)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

While it would change the final method, I believe the advice is still applicable w.r.t. receiver/extension methods. When you're using an extension method, you're effectively adding a method to the receiver type's API. That is to say that if a method doesn't belong on a type, neither does an extension method.

In this case, `InternalReport` is a protobuf message meaning a basic data holder. One wouldn't expect it to have methods that interact with a backend service or database[^1]. Therefore, a method persisting it to the DB should be an instance method on the service that takes in an `InternalReport` instead.

[^1]: This would be different if we were using classes with more behavior, such as in the [active record pattern](https://en.wikipedia.org/wiki/Active_record_pattern).
</blockquote></details>

Thank you Sanjay for the great explanation!

Made the function not a receiver/extension function. Also renamed `updateReport` to `syncMeasurements` and `updateMeasurement` to `syncMeasurement`. Note that the code of updating reports is gone.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt` line 215 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/613#-N5MHAMU7j80IgXcJYfw:-N5bajlRA548YLvHglTD:b1wc5yt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8cb501c456d30edb7f65bcc2256c1f72dcda464d/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt#L215)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

I will need to update them both then.
</blockquote></details>

Okay. I removed the code of updating the report.

@tristanvuong2021 you can reuse what I had for computing the report result in your implementation. Note that there are some subtle decision made like the frequency histogram result is in counts instead of percentage.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt` line 520 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/613#-N5aMSll0okZlYguHw3K:-N5bYWLB-OYsCwFeSTFO:b-ch8a7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e85ccd9192de5a12512d55c73f241cb2fd275bd6/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt#L520)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: clearer names and possibly explicit types.

`sum` is confusing since it's a map and not a scalar value. It might actually be clearer overall to use a `fold` operation instead. e.g.

```kotlin
.fold(mutableMapOf().withDefault(0.0)) { aggregatedFrequencyHistogram: MutableMap<Int, Double>, weightedFrequencyHistogram -> 
  for ((frequency, count) in weightedFrequencyHistogram) {
    aggregatedFrequencyHistogram[frequency] = aggregatedFrequencyHistogram.getValue(frequency) + count
  }
}
```
</blockquote></details>

Since we decided to remove the code of updating reports, this function is no longer needed.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt` line 163 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/613#-N5audA2BaYpwdNVXR1M:-N5b_xFA-Do5WjGWc8w5:b-ujzerg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/54324eb7a7a383c57d2ae51847626f7c5c68dff0/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt#L163)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

nit: results.last()
</blockquote></details>

IIUC, `results.last()` returns the last element in the list, but what we want is the second to the last.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt` line 20 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/613#-N5bJ2xJ0tVqgH4n32kw:-N5bZvukCfV5HSLiTSma:b-xu0uci) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dd44ba6985ebe6a8171a0694f9257edfc05b1b59/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt#L20)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Just import the enclosing util type and call the method on it, e.g. `Durations.add`.
</blockquote></details>

Thanks for the suggestion. Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt` line 385 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/613#-N5bGcyP4urCqXPeejSX:-N5beF781wFGGk2rX5L5:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dd44ba6985ebe6a8171a0694f9257edfc05b1b59/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt#L385)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: "Converts"

See https://developer.android.com/kotlin/style-guide#summary_fragment
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt` line 386 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/613#-N5bGycA0_xiCd0QRRhS:-N5bjMgD4Q_RbT2bvX7t:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dd44ba6985ebe6a8171a0694f9257edfc05b1b59/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt#L386)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Since none of these extension functions should be accessing the state of the ReportsService instance, make them not instance methods of ReportsService. e.g. move them outside of the class or put them in its companion object.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt` line 419 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/613#-N5bI944133KIrjHH-Cm:-N5blWXmDeo8QTKy9F46:b-ch8a7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dd44ba6985ebe6a8171a0694f9257edfc05b1b59/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt#L419)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: make a data class instead of using Pair
</blockquote></details>

Since we decided to remove the code of updating reports, this function is no longer needed.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt` line 479 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/613#-N5bJEwd79M0ZuvJYzjg:-N5bkwGEBbIleEzhQ7A-:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dd44ba6985eb [...]

2022-06-28 00:49 UTC, riemanli commented
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt` line 215 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/613#-N5MHAMU7j80IgXcJYfw:-N5bmCAR5-cUT1plDNG0:bako7t6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8cb501c456d30edb7f65bcc2256c1f72dcda464d/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt#L215)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Okay. I removed the code of updating the report.

@tristanvuong2021 you can reuse what I had for computing the report result in your implementation. Note that there are some subtle decision made like the frequency histogram result is in counts instead of percentage.
</blockquote></details>

Since I already removed the code, you can find it in the previous commits.


<!-- Sent from Reviewable.io -->

2022-06-28 00:50 UTC, riemanli commented
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt` line 494 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/613#-N5aF9ws3RRe6OdLY7Y7:-N5bmRJw0OmgeVko2kwb:b-ch8a7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e85ccd9192de5a12512d55c73f241cb2fd275bd6/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt#L494)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

That's a good point. Thanks for the suggestion! 
Done.
</blockquote></details>

Since we decided to remove the code of updating reports, this function is no longer needed.


<!-- Sent from Reviewable.io -->

2022-06-28 22:19 UTC, riemanli commented
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt` line 215 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/613#-N5MHAMU7j80IgXcJYfw:-N5gOR6f7x1Ecq-cTzvz:bsrc2q3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8cb501c456d30edb7f65bcc2256c1f72dcda464d/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt#L215)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Since I already removed the code, you can find it in the previous commits.
</blockquote></details>

For example, this one: https://github.com/world-federation-of-advertisers/cross-media-measurement/pull/613/commits/0a4759ae0e7481761b62aa3eafeec51991ca4f66


<!-- Sent from Reviewable.io -->

2022-06-30 05:26 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/613)* status: 6 of 9 files reviewed, 11 unresolved discussions (waiting on @renjiezh and @SanjayVas)

___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsServiceTest.kt` line 15 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/613#-N5aaVbG24FSV2aniMpX:-N5n3o2c1y4L2VhmGedk:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e85ccd9192de5a12512d55c73f241cb2fd275bd6/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsServiceTest.kt#L15)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Resolve this comment when you've added tests.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-06 20:43 UTC, renjiezh requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/613)* status: 7 of 9 files reviewed, 14 unresolved discussions (waiting on @riemanli, @SanjayVas, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt` line 175 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/613#-N6KCbpZ55weMRkueqLy:-N6KCbpZ55weMRkueqLz:bmd35ij) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ae2ec26e65976bac1fb29d7e9681ecfdd511b208/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt#L175)):*
> ```Kotlin
>         internalReport.state == InternalReport.State.UNRECOGNIZED
>     ) {
>       error(
> ```

Use `failGrpc()` to throw errors


<!-- Sent from Reviewable.io -->

2022-07-06 20:49 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/613)* status: 7 of 9 files reviewed, 14 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt` line 175 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/613#-N6KCbpZ55weMRkueqLy:-N6KFjviCjmYqu00mrxd:b2iin0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ae2ec26e65976bac1fb29d7e9681ecfdd511b208/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt#L175)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

Use `failGrpc()` to throw errors
</blockquote></details>

I was informed by @sanjayvas that system errors should be raised by the Kotlin built-in `error`. @sanjayvas could you please confirm whether using `error` here is correct?
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt` line 182 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/613#-N6Jods51diefkDB282s:-N6JxEGc7UUn_o53C3KB:b-46bhir) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ae2ec26e65976bac1fb29d7e9681ecfdd511b208/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt#L182)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

This looks like a potential spot for coroutines because of the network calls inside syncMeasurement. Could put the whole for loop in a coroutineScope or supervisorScope and each syncMeasurement call inside a launch. Differences between coroutineScope and supervisorScope here: https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/supervisor-scope.html, but essentially supervisorScope doesn't cancel when a child coroutine fails and coroutineScope does.
</blockquote></details>

Thanks for the suggestion and the info about `supervisorScope`.  For synchronizing measurements, I prefer to use `coroutineScope` to stop earlier when there is an error.
___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsServiceTest.kt` line 961 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/613#-N6Jhc6M4jhJpUHWKMbI:-N6JsF_kBXq8Z7sX9gyG:bzapxhy) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ae2ec26e65976bac1fb29d7e9681ecfdd511b208/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsServiceTest.kt#L961)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

nit: should be listReports
</blockquote></details>

Thanks for catching that! Done.


<!-- Sent from Reviewable.io -->

2022-07-06 21:22 UTC, renjiezh reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/613)* status: 7 of 9 files reviewed, 13 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt` line 175 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/613#-N6KCbpZ55weMRkueqLy:-N6KNv1v3sDGm-lTGYrM:bqx6gup) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ae2ec26e65976bac1fb29d7e9681ecfdd511b208/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt#L175)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

I was informed by @sanjayvas that system errors should be raised by the Kotlin built-in `error`. @sanjayvas could you please confirm whether using `error` here is correct?
</blockquote></details>

I see. Yeah, for these types we might not need to throw them as grpc errors


<!-- Sent from Reviewable.io -->

2022-07-06 21:26 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/613)* status: 7 of 9 files reviewed, 13 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt` line 175 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/613#-N6KCbpZ55weMRkueqLy:-N6KOe0vE4UGRK1U5LS9:bcv3ydb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ae2ec26e65976bac1fb29d7e9681ecfdd511b208/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt#L175)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

I see. Yeah, for these types we might not need to throw them as grpc errors
</blockquote></details>

I can modify the error message to make it more clear if that helps clarifying.  Ex: "The measurements cannot be synced because the report state was not set correctly."
Wdyt?


<!-- Sent from Reviewable.io -->

2022-07-06 21:29 UTC, renjiezh reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/613)* status: 7 of 9 files reviewed, 13 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt` line 175 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/613#-N6KCbpZ55weMRkueqLy:-N6KPLgD92eBPTju8MLM:b5d2lqb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ae2ec26e65976bac1fb29d7e9681ecfdd511b208/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt#L175)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

I can modify the error message to make it more clear if that helps clarifying.  Ex: "The measurements cannot be synced because the report state was not set correctly."
Wdyt?
</blockquote></details>

Sounds good to me. 


<!-- Sent from Reviewable.io -->

2022-07-06 21:33 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/613)* status: 7 of 9 files reviewed, 13 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt` line 175 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/613#-N6KCbpZ55weMRkueqLy:-N6KQf4d3n7hm4Nw-qgo:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ae2ec26e65976bac1fb29d7e9681ecfdd511b208/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt#L175)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

Sounds good to me. 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-06 23:08 UTC, renjiezh requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/613)* status: 7 of 9 files reviewed, 14 unresolved discussions (waiting on @riemanli, @SanjayVas, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt` line 309 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/613#-N6Ki7npBuxW6WpkM1H8:-N6Ki7npBuxW6WpkM1H9:bbdagme) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/63f0b61d40e9f7f22b1fe0333285ee3f62949f7e/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt#L309)):*
> ```Kotlin
>   internalResultsList: List<InternalMeasurementResult>
> ): InternalMeasurementResult {
>   return internalResultsList.reduce { aggregatedResult, result ->
> ```

If I understand this reduce operation correctly, within every iteration, it will create a new `internalMeasurementResult` and populate it with updated results. Then this `internalMeasurementResult` will be assigned to`aggregatedResult` and enter the next iteration. While assigning to `aggregatedResult`, the previews value of it is dumped, which is wasting. 
What about we use `fold` instead of `reduce` and do something like
```
val aggregatedResult = internalResultsList{}
return internalResultsList.fold(aggregatedResult) { aggregatedResult, result ->
      if (result.hasReach()) {
        aggregatedResult.value += result.reach.value
      }
      ...
}
```
It will keep updating values of `aggregatedResult`.


<!-- Sent from Reviewable.io -->

2022-07-06 23:14 UTC, renjiezh requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/613)* status: 7 of 9 files reviewed, 14 unresolved discussions (waiting on @riemanli, @SanjayVas, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt` line 309 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/613#-N6Ki7npBuxW6WpkM1H8:-N6KmC6J65ORZ3SyvrqM:blekv94) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/63f0b61d40e9f7f22b1fe0333285ee3f62949f7e/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt#L309)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

If I understand this reduce operation correctly, within every iteration, it will create a new `internalMeasurementResult` and populate it with updated results. Then this `internalMeasurementResult` will be assigned to`aggregatedResult` and enter the next iteration. While assigning to `aggregatedResult`, the previews value of it is dumped, which is wasting. 
What about we use `fold` instead of `reduce` and do something like
```
val aggregatedResult = internalResultsList{}
return internalResultsList.fold(aggregatedResult) { aggregatedResult, result ->
      if (result.hasReach()) {
        aggregatedResult.value += result.reach.value
      }
      ...
}
```
It will keep updating values of `aggregatedResult`.

</blockquote></details>

Another way could be simpler:
```
val aggregatedResult = internalResultsList {}
for (result in internalResultsList) {
    if (result.hasReach()) {
        aggregatedResult.value += result.reach.value
     }
    ...
}
return aggregatedResult
```


<!-- Sent from Reviewable.io -->

2022-07-07 17:54 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/613)* status: 7 of 9 files reviewed, 14 unresolved discussions (waiting on @renjiezh, @SanjayVas, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt` line 309 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/613#-N6Ki7npBuxW6WpkM1H8:-N6OkhptC4BqAPhUsVoj:bpfka49) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/63f0b61d40e9f7f22b1fe0333285ee3f62949f7e/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt#L309)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

Another way could be simpler:
```
val aggregatedResult = internalResultsList {}
for (result in internalResultsList) {
    if (result.hasReach()) {
        aggregatedResult.value += result.reach.value
     }
    ...
}
return aggregatedResult
```
</blockquote></details>

I don't think we can do `aggregatedResult.value += result.reach.value`. I've tried that and got error message `Val cannot be reassigned`, and that's why I created a new object every time.

If the computation is a concern, a possible alternative is to aggregate the values separately. Ex:

``` kotlin
var reachValue = 0L
var impressionValue = 0L
var frequencyDistribution = mutableMapOf<Long, Double>()
var watchDurationValue = duration(seconds = 0, nanos = 0)

for (result in internalResultsList) {
    if (result.hasReach()) {
        reachValue += result.reach.value
    }
    ...
}
``` 

Let me know if that's what you want. Thanks.


<!-- Sent from Reviewable.io -->

2022-07-07 18:41 UTC, renjiezh requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/613)* status: 7 of 9 files reviewed, 14 unresolved discussions (waiting on @riemanli, @SanjayVas, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt` line 309 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/613#-N6Ki7npBuxW6WpkM1H8:-N6OxQ1n3qKm72Y3mI5-:bw5ob34) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/63f0b61d40e9f7f22b1fe0333285ee3f62949f7e/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt#L309)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

I don't think we can do `aggregatedResult.value += result.reach.value`. I've tried that and got error message `Val cannot be reassigned`, and that's why I created a new object every time.

If the computation is a concern, a possible alternative is to aggregate the values separately. Ex:

``` kotlin
var reachValue = 0L
var impressionValue = 0L
var frequencyDistribution = mutableMapOf<Long, Double>()
var watchDurationValue = duration(seconds = 0, nanos = 0)

for (result in internalResultsList) {
    if (result.hasReach()) {
        reachValue += result.reach.value
    }
    ...
}
``` 

Let me know if that's what you want. Thanks.
</blockquote></details>

Oh, that's true. Yeah, I think it is a good idea to have these variables to sum up results, then create the final `internalResultsList` object. The purpose is to avoid creating `internalResultsList` multiple times.


<!-- Sent from Reviewable.io -->

2022-07-07 21:39 UTC, renjiezh approved these changes
> Reviewed 2 of 2 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/613)* status: all files reviewed, 14 unresolved discussions (waiting on @riemanli, @SanjayVas, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt` line 348 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/613#-N6P_sNA88EQn0Kwm0hl:-N6P_sNA88EQn0Kwm0hm:b-jx8j4k) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/99349bdd7ff40f208ad6e5c3725f16757f3c22d4/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt#L348)):*
> ```Kotlin
> 
>   return internalMeasurementResult {
>     if (internalResultsList[0].hasReach()) {
> ```

nit: `internalResultsList.first().hasReach()`


<!-- Sent from Reviewable.io -->

2022-07-07 21:49 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/613)* status: 8 of 9 files reviewed, 13 unresolved discussions (waiting on @renjiezh, @SanjayVas, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt` line 309 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/613#-N6Ki7npBuxW6WpkM1H8:-N6PZqc3A1E8hBWaCsFE:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/63f0b61d40e9f7f22b1fe0333285ee3f62949f7e/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt#L309)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

Oh, that's true. Yeah, I think it is a good idea to have these variables to sum up results, then create the final `internalResultsList` object. The purpose is to avoid creating `internalResultsList` multiple times.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt` line 348 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/613#-N6P_sNA88EQn0Kwm0hl:-N6Pcr4v2FqXJSj1zslH:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/99349bdd7ff40f208ad6e5c3725f16757f3c22d4/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt#L348)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

nit: `internalResultsList.first().hasReach()`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-12 17:25 UTC, renjiezh reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/613#-:-N6nRXrIEqJrDfVap5A9:bnfp4nl)* status: 8 of 9 files reviewed, 13 unresolved discussions (waiting on @renjiezh, @SanjayVas, and @tristanvuong2021)



<!-- Sent from Reviewable.io -->

2022-07-12 22:03 UTC, SanjayVas requested changes
> Reviewed 1 of 3 files at r8, 1 of 2 files at r13, 1 of 1 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/613)* status: all files reviewed, 6 unresolved discussions (waiting on @chipingyeh, @riemanli, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt` line 215 at r14](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/613#-N6oLzZlCncdRGrtmhWO:-N6oLzZlCncdRGrtmhWP:b-v3clqf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0cedc5ba5e3100ce54bd30248698dc8691494932/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt#L215)):*
> ```Kotlin
>     internalMeasurement: InternalMeasurement,
>   ) {
>     // Measurement with SUCCEEDED state is already synced
> ```

nit: move this check outside so we avoid building a new coroutine unnecessarily



_Code quote:_
```Kotlin
    // Measurement with SUCCEEDED state is already synced
    if (internalMeasurement.state == InternalMeasurement.State.SUCCEEDED) return
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt` line 257 at r14](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/613#-N6oNZ_-E2B2DRDVCtSK:-N6oNZ_-E2B2DRDVCtSL:bzbe37d) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0cedc5ba5e3100ce54bd30248698dc8691494932/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt#L257)):*
> ```Kotlin
>     }
> 
>     return
> ```

What is this for?



_Code quote:_
```Kotlin
    return
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt` line 280 at r14](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/613#-N6oOJGB6ymkOP4Lmr0n:-N6oOJGB6ymkOP4Lmr0o:b-pz9m1e) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0cedc5ba5e3100ce54bd30248698dc8691494932/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt#L280)):*
> ```Kotlin
> 
> private operator fun Duration.plus(other: Duration): Duration {
>   val source = this
> ```

nit: inline this variable, since it's only used once



_Code quote:_
```Kotlin
val source = this
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt` line 410 at r14](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/613#-N6oOmIx6xVwjeBPOrES:-N6oOmIx6xVwjeBPOrET:b-fvva3l) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0cedc5ba5e3100ce54bd30248698dc8691494932/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt#L410)):*
> ```Kotlin
>     reportIdempotencyKey = source.reportIdempotencyKey
>     measurementConsumer = measurementConsumerResourceName
>     eventGroupUniverse = eventGroupUniverse { this.eventGroupEntries.addAll(eventGroupEntries) }
> ```

nit: 
```kotlin
this.eventGroupEntries += eventGroupEntries
```



_Code quote:_
```Kotlin
this.eventGroupEntries.addAll(eventGroupEntries)
```


<!-- Sent from Reviewable.io -->

2022-07-12 22:32 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/613)* status: all files reviewed, 4 unresolved discussions (waiting on @chipingyeh, @SanjayVas, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt` line 182 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/613#-N6Jods51diefkDB282s:-N6oXcXb77XdhkDtLs8W:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ae2ec26e65976bac1fb29d7e9681ecfdd511b208/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt#L182)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Thanks for the suggestion and the info about `supervisorScope`.  For synchronizing measurements, I prefer to use `coroutineScope` to stop earlier when there is an error.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt` line 215 at r14](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/613#-N6oLzZlCncdRGrtmhWO:-N6oW_G381-yG8_wW9EO:b-tt766n) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0cedc5ba5e3100ce54bd30248698dc8691494932/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt#L215)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: move this check outside so we avoid building a new coroutine unnecessarily
</blockquote></details>

Great suggestion! Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt` line 257 at r14](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/613#-N6oNZ_-E2B2DRDVCtSK:-N6oTRt10JE1Hc62UmPy:b-ql1fni) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0cedc5ba5e3100ce54bd30248698dc8691494932/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt#L257)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

What is this for?
</blockquote></details>

Should not exist. Removed.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt` line 280 at r14](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/613#-N6oOJGB6ymkOP4Lmr0n:-N6oVCMs7oypRqABW4Bv:bb6un1j) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0cedc5ba5e3100ce54bd30248698dc8691494932/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt#L280)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: inline this variable, since it's only used once
</blockquote></details>

Done
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt` line 410 at r14](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/613#-N6oOmIx6xVwjeBPOrES:-N6oVm4S80TF72LflrFw:b-xu0uci) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0cedc5ba5e3100ce54bd30248698dc8691494932/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt#L410)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: 
```kotlin
this.eventGroupEntries += eventGroupEntries
```
</blockquote></details>

Thanks for the suggestion. Done.


<!-- Sent from Reviewable.io -->

2022-07-12 22:55 UTC, tristanvuong2021 reviewed
> Reviewed 1 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/613)* status: 8 of 9 files reviewed, 3 unresolved discussions (waiting on @chipingyeh and @SanjayVas)



<!-- Sent from Reviewable.io -->

2022-07-12 22:55 UTC, tristanvuong2021 approved these changes
> Reviewed 1 of 1 files at r15.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/613)* status: all files reviewed, 3 unresolved discussions (waiting on @chipingyeh and @SanjayVas)



<!-- Sent from Reviewable.io -->

2022-07-13 17:43 UTC, chipingyeh approved these changes
> Reviewed 3 of 7 files at r1, 1 of 3 files at r2, 1 of 3 files at r8, 1 of 2 files at r13, 1 of 1 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/613)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @riemanli)



<!-- Sent from Reviewable.io -->

2022-07-13 18:08 UTC, merged