initial submission
world-federation-of-advertisers/cross-media-measurement pull request #615
Opened 2022-06-30 18:02 UTC by chipingyeh

2022-07-05 21:50 UTC, chipingyeh reviewed
Still have some checks/tests to add, but I wanted to submit for an initial review of the general business logic. Note that I've injected the MC private key for now since the service isn't built yet.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/615#-:-N6FKfe2AgGjhU8t4yN8:b-o4simj)* status: 0 of 13 files reviewed, all discussions resolved



<!-- Sent from Reviewable.io -->

2022-07-07 21:39 UTC, chipingyeh reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/615)* status: 6 of 13 files reviewed, 1 unresolved discussion (waiting on @SanjayVas, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/crypto/KeyHandle.kt` line 1 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/615#-N6PHOtT9jfIQoNph5Hy:-N6PUHax7Fba0CMeLttV:b-axb7or) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b2a809fe794885f316f1274aa0063b9390fd550d/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/crypto/KeyHandle.kt#L1)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

This and KeyLoading look like files from common-jvm.
</blockquote></details>

Removed. I had initially added them due to this one being restricted to testing-only, but I am only using it in a test here anyway.


<!-- Sent from Reviewable.io -->

2022-07-08 23:37 UTC, tristanvuong2021 requested changes
> Reviewed 2 of 12 files at r2, 5 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/615)* status: 11 of 13 files reviewed, 1 unresolved discussion (waiting on @chipingyeh, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/EventGroupsService.kt` line 100 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/615#-N6VA-qK28kItLNMWILY:-N6VA-qK28kItLNMWILZ:bfkvrx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a0b514896f9b921eeb04c048dc7cafde831ba1a0/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/EventGroupsService.kt#L100)):*
> ```Kotlin
>       )
>     return reportingEventGroup {
>       name = this@toReportingServer.name
> ```

The reporting server event group has a different resource name structure than the CMMS event group


<!-- Sent from Reviewable.io -->

2022-07-12 23:24 UTC, tristanvuong2021 reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/615)* status: 11 of 13 files reviewed, all discussions resolved (waiting on @SanjayVas and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/EventGroupsService.kt` line 100 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/615#-N6VA-qK28kItLNMWILY:-N6oiKhBAprp1wvYASSE:btm90n0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a0b514896f9b921eeb04c048dc7cafde831ba1a0/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/EventGroupsService.kt#L100)):*
<details><summary><i>Previously, chipingyeh wrote…</i></summary><blockquote>

Done.
</blockquote></details>

nit: It does work, but there is a reporting EventGroupKey to form the name.


<!-- Sent from Reviewable.io -->

2022-07-13 23:09 UTC, SanjayVas requested changes
> Reviewed 5 of 12 files at r2, 2 of 7 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/615)* status: all files reviewed, 7 unresolved discussions (waiting on @chipingyeh and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/EventGroupsService.kt` line 31 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/615#-N6thQdn3RVa8PCf5JAt:-N6thQdn3RVa8PCf5JAu:b-pl5rqs) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cfb1ffb1908ea575ff714e34d012cab4778601b4/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/EventGroupsService.kt#L31)):*
> ```Kotlin
> import org.wfanet.measurement.reporting.v1alpha.EventGroup as ReportingEventGroup
> import org.wfanet.measurement.reporting.v1alpha.EventGroupKt.eventTemplate as reportingEventTemplate
> import org.wfanet.measurement.reporting.v1alpha.EventGroupKt.metadata as reportingMetadata
> ```

Does your IntelliJ code completion continue working with these? We tend to avoid aliasing function imports from objects due to https://youtrack.jetbrains.com/issue/KTIJ-16471



_Code quote:_
```Kotlin
import org.wfanet.measurement.reporting.v1alpha.EventGroupKt.eventTemplate as reportingEventTemplate
import org.wfanet.measurement.reporting.v1alpha.EventGroupKt.metadata as reportingMetadata
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/EventGroupsService.kt` line 35 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/615#-N6thoLH8Uh1TMKj8dtF:-N6thoLH8Uh1TMKj8dtG:b-pi9436) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cfb1ffb1908ea575ff714e34d012cab4778601b4/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/EventGroupsService.kt#L35)):*
> ```Kotlin
> import org.wfanet.measurement.reporting.v1alpha.ListEventGroupsRequest
> import org.wfanet.measurement.reporting.v1alpha.ListEventGroupsResponse
> import org.wfanet.measurement.reporting.v1alpha.eventGroup as reportingEventGroup
> ```

nit: Since this is a reporting service implementation, I'd recommend keeping the reporting API versions of things unprefixed since they're basically in the same namespace.



_Code quote:_
```Kotlin
reporting
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/EventGroupsService.kt` line 45 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/615#-N6tiW2TBMqavrONMrvf:-N6tiW2TBMqavrONMrvg:b-eucu26) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cfb1ffb1908ea575ff714e34d012cab4778601b4/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/EventGroupsService.kt#L45)):*
> ```Kotlin
> ) : EventGroupsCoroutineImplBase() {
>   override suspend fun listEventGroups(request: ListEventGroupsRequest): ListEventGroupsResponse {
>     val principal = principalFromCurrentContext
> ```

Specify types explicitly when they're not obvious. Remember that code is read more often than it's written, and often without the benefit of an IDE.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/EventGroupsService.kt` line 69 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/615#-N6tlZQnC2tg2VZhgl5W:-N6tlZQo83kKUWDpSoNe:b-m53dqu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cfb1ffb1908ea575ff714e34d012cab4778601b4/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/EventGroupsService.kt#L69)):*
> ```Kotlin
>           batchGetEventGroupMetadataDescriptorsRequest {
>             parent = request.parent
>             names += eventGroups.map { it.name }
> ```

Doesn't this need to be the name of the EventGroupMetadataDescriptor resource, not the EventGroup resource? You also likely need to deal with the fact that multiple EventGroups can share a descriptor.



_Code quote:_
```Kotlin
eventGroups.map { it.name }
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/EventGroupsService.kt` line 83 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/615#-N6tjn69EHEQ-u7kpUzJ:-N6tjn69EHEQ-u7kpUzK:b49de8k) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cfb1ffb1908ea575ff714e34d012cab4778601b4/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/EventGroupsService.kt#L83)):*
> ```Kotlin
>       val metadataMessage = metadataParser.convertToDynamicMessage(metadata)
>       val program =
>         EventFilters.compileProgram(request.filter, metadataMessage!!.defaultInstanceForType)
> ```

Only use this in cases where it's not possible for something to be null, but the compiler can't figure it out on its own. If it's a programming invariant, consider `checkNotNull` instead. If it's something that can be expected to go wrong (e.g. the MC user is supposed to have set something up, but it could be configured incorrectly) then instead throw a gRPC error (StatusRuntimeException) with the appropriate status code.



_Code quote:_
```Kotlin
!!
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/EventGroupsService.kt` line 94 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/615#-N6tnD_H0YOjnLbsD7Fh:-N6tnD_H0YOjnLbsD7Fi:b-udicn5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cfb1ffb1908ea575ff714e34d012cab4778601b4/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/EventGroupsService.kt#L94)):*
> ```Kotlin
>   }
> 
>   private fun CmmsEventGroup.toReportingServer(): ReportingEventGroup {
> ```

Just `toEventGroup`.



_Code quote:_
```Kotlin
toReportingServer
```
___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/EventGroupsServiceTest.kt` line 162 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/615#-N6tnlflDmro1HJKAmt2:-N6tnlflDmro1HJKAmt3:bckood5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cfb1ffb1908ea575ff714e34d012cab4778601b4/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/EventGroupsServiceTest.kt#L162)):*
> ```Kotlin
>         }
>       }
> ```

Also verify the request that's sent to the CMMS EventGroups service. Look for uses of `verifyProtoArgument` for examples of how to do this.


<!-- Sent from Reviewable.io -->

2022-07-14 17:23 UTC, stevenwarejones approved these changes
> Reviewed 5 of 12 files at r2, 2 of 7 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/615)* status: all files reviewed, 8 unresolved discussions (waiting on @chipingyeh)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/EventGroupsService.kt` line 101 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/615#-N6xirKk7mCoU1C-xg3B:-N6xirKlEpsgfU4dkIdR:b-ki0s6m) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cfb1ffb1908ea575ff714e34d012cab4778601b4/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/EventGroupsService.kt#L101)):*
> ```Kotlin
>     return reportingEventGroup {
>       name = this@toReportingServer.measurementConsumer + "/" + this@toReportingServer.name
>       // dataProvider =
> ```

remote this comment


<!-- Sent from Reviewable.io -->

2022-07-14 20:07 UTC, chipingyeh reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/615)* status: 9 of 13 files reviewed, 6 unresolved discussions (waiting on @SanjayVas, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/EventGroupsService.kt` line 100 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/615#-N6VA-qK28kItLNMWILY:-N6xw4I53qIPjurXPGiI:b86wkq8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a0b514896f9b921eeb04c048dc7cafde831ba1a0/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/EventGroupsService.kt#L100)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

nit: It does work, but there is a reporting EventGroupKey to form the name.
</blockquote></details>

Done -- updated the tests and fields as well since it wasn't assembled exactly the same.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/EventGroupsService.kt` line 31 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/615#-N6thQdn3RVa8PCf5JAt:-N6xhpBs-1wuKWIlDCfO:b-3shf8e) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cfb1ffb1908ea575ff714e34d012cab4778601b4/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/EventGroupsService.kt#L31)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Does your IntelliJ code completion continue working with these? We tend to avoid aliasing function imports from objects due to https://youtrack.jetbrains.com/issue/KTIJ-16471
</blockquote></details>

Unfortunately my Intellij code completion has been broken for a while, so I can't comment much on that. Got rid of aliases as part of comment below, and updated the test file.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/EventGroupsService.kt` line 45 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/615#-N6tiW2TBMqavrONMrvf:-N6xkGra3WjuwpJkki-p:b-18our9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cfb1ffb1908ea575ff714e34d012cab4778601b4/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/EventGroupsService.kt#L45)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Specify types explicitly when they're not obvious. Remember that code is read more often than it's written, and often without the benefit of an IDE.
</blockquote></details>

Although this isn't specified in other files, I've gone ahead and added it here.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/EventGroupsService.kt` line 69 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/615#-N6tlZQnC2tg2VZhgl5W:-N6xn8vq1REZkqVuHpiq:b-f86i8v) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cfb1ffb1908ea575ff714e34d012cab4778601b4/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/EventGroupsService.kt#L69)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Doesn't this need to be the name of the EventGroupMetadataDescriptor resource, not the EventGroup resource? You also likely need to deal with the fact that multiple EventGroups can share a descriptor.
</blockquote></details>

Yes, good point -- updated to use the descriptor name in the metadata field (decrypted), and made it a Set.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/EventGroupsService.kt` line 83 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/615#-N6tjn69EHEQ-u7kpUzJ:-N6y1dX6-_ct2eZsWq2I:bqgvrwr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cfb1ffb1908ea575ff714e34d012cab4778601b4/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/EventGroupsService.kt#L83)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Only use this in cases where it's not possible for something to be null, but the compiler can't figure it out on its own. If it's a programming invariant, consider `checkNotNull` instead. If it's something that can be expected to go wrong (e.g. the MC user is supposed to have set something up, but it could be configured incorrectly) then instead throw a gRPC error (StatusRuntimeException) with the appropriate status code.
</blockquote></details>

Done. Kept the ones in the test file as !! since they're always defined.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/EventGroupsService.kt` line 94 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/615#-N6tnD_H0YOjnLbsD7Fh:-N6xpHI51iMcuAojO34B:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cfb1ffb1908ea575ff714e34d012cab4778601b4/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/EventGroupsService.kt#L94)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Just `toEventGroup`.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/EventGroupsService.kt` line 101 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/615#-N6xirKk7mCoU1C-xg3B:-N6y0R2W5TX5CZINebcQ:b9esrp6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cfb1ffb1908ea575ff714e34d012cab4778601b4/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/EventGroupsService.kt#L101)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

remote this comment
</blockquote></details>

Meant to populate it -- done.
___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/EventGroupsServiceTest.kt` line 162 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/615#-N6tnlflDmro1HJKAmt2:-N6yHO-30HIT4wJJZwwp:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cfb1ffb1908ea575ff714e34d012cab4778601b4/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/EventGroupsServiceTest.kt#L162)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Also verify the request that's sent to the CMMS EventGroups service. Look for uses of `verifyProtoArgument` for examples of how to do this.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-14 22:29 UTC, tristanvuong2021 requested changes
> Reviewed 1 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/615)* status: 10 of 13 files reviewed, 7 unresolved discussions (waiting on @chipingyeh, @SanjayVas, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/EventGroupsService.kt` line 126 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/615#-N6yoC5DAB-Rmt4g3dDE:-N6yoC5DAB-Rmt4g3dDF:bhuk8bu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3b86d8bdfc0fe97526cd290218d3fa1f6671cb0d/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/EventGroupsService.kt#L126)):*
> ```Kotlin
>             measurementConsumerKey.measurementConsumerId,
>             dataProviderReferenceId,
>             this@toEventGroup.eventGroupReferenceId
> ```

The eventGroupReferenceId from the CMMS event group doesn't go here. You already have the CMMSEventGroupKey so you can use both the dataProviderId and the eventGroupId from it to set the values in the reporting EventGroupKey.


<!-- Sent from Reviewable.io -->

2022-07-15 00:49 UTC, SanjayVas requested changes
> Reviewed 2 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/615)* status: 11 of 13 files reviewed, 6 unresolved discussions (waiting on @chipingyeh, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/EventGroupsService.kt` line 45 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/615#-N6tiW2TBMqavrONMrvf:-N6zCuSz9PEDDylljgJF:bz9pvv7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cfb1ffb1908ea575ff714e34d012cab4778601b4/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/EventGroupsService.kt#L45)):*
<details><summary><i>Previously, chipingyeh wrote…</i></summary><blockquote>

Although this isn't specified in other files, I've gone ahead and added it here.
</blockquote></details>

I meant this more generally, not just for this specific line. e.g. 
* `eventGroups` - it's not obvious that it's a list of EventGroup messages from the CMMS API without looking at the signature of `listEventGroups`
* `program` - it's not obvious that this is a `org.projectnessie.cel.Program` without looking at the signature of `compileProgram`

I know existing code isn't the best about following this. I'm trying to be better about remembering to comment on it. Basically types should be specified when they are not obvious, where obvious refers to cases such as when you're assigning from a literal, constructor, or well-known factory function.

Obvious case examples:

```kotlin
const val PI = 3.14
val colors = listOf("Red", "Blue")
val bar = Foo()

fun build() = Foo()
fun buildMessage() = fooMessage {
  foo = "bar"
}
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/EventGroupsService.kt` line 72 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/615#-N6zFtDE-sx-gRqMrRUT:-N6zFtDFCKkuP-UUHbzN:b-ig9x9x) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3b86d8bdfc0fe97526cd290218d3fa1f6671cb0d/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/EventGroupsService.kt#L72)):*
> ```Kotlin
>             parent = request.parent
>             names +=
>               eventGroups
> ```

nit: reduce the amount of work done in DSL builder scopes

e.g. extract the decryption and deserialization of the `CmmsEventGroup.Metadata` message
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/EventGroupsService.kt` line 93 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/615#-N6zGmN15nHy7HoRSUjO:-N6zGmN15nHy7HoRSUjP:b-p56m7g) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3b86d8bdfc0fe97526cd290218d3fa1f6671cb0d/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/EventGroupsService.kt#L93)):*
> ```Kotlin
>       val metadataMessage =
>         grpcRequireNotNull(metadataParser.convertToDynamicMessage(metadata)) {
>           "Event group metadata message is invalid"
> ```

It looks like `convertToDynamicMessage` only returns null when the descriptor isn't in the type registry. Therefore this doesn't necessarily mean that the metadata message is invalid, only that the descriptors we got from the CMMS don't include one for this type URL.

This should also use status code `FAILED_PRECONDITION` rather than `INVALID_ARGUMENT` (what grpcRequireNotNull uses), as the issue isn't that the request to this method is invalid. See https://grpc.github.io/grpc/core/md_doc_statuscodes.html 



_Code quote:_
```Kotlin
"Event group metadata message is invalid"
```
___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/EventGroupsServiceTest.kt` line 162 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/615#-N6tnlflDmro1HJKAmt2:-N6zIOJM-dKRdNlxjcdD:b-t114lo) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cfb1ffb1908ea575ff714e34d012cab4778601b4/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/EventGroupsServiceTest.kt#L162)):*
<details><summary><i>Previously, chipingyeh wrote…</i></summary><blockquote>

Done.
</blockquote></details>

What I meant was to include that verification of the request message for each of the service calls made by the method under test within each test.

You want to verify all of the observable side effects of the method under test. In this case, that means the return value as well as the requests sent to another service.


<!-- Sent from Reviewable.io -->

2022-07-15 21:30 UTC, SanjayVas requested changes
> Reviewed 1 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/615)* status: 11 of 13 files reviewed, 13 unresolved discussions (waiting on @chipingyeh, @SanjayVas, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/EventGroupsService.kt` line 85 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/615#-N72geNqBZEHSvYOqsva:-N72geNqBZEHSvYOqsvb:b-ppsibp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c7903b61fb3959c3145fed0a352574c768f287b7/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/EventGroupsService.kt#L85)):*
> ```Kotlin
>             parent = request.parent
>             names +=
>               eventGroups
> ```

Can't this just be `parsedEventGroupMetadataMap.values` ? Regardless, there's already one event group per map entry so there's no need to touch the `eventGroups` collection again.



_Code quote:_
```Kotlin
              eventGroups
                .map { parsedEventGroupMetadataMap[it.name]!!.eventGroupMetadataDescriptor }
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/EventGroupsService.kt` line 95 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/615#-N72hCoq20bXVZHF6vHl:-N72hCoq20bXVZHF6vHm:b45h) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c7903b61fb3959c3145fed0a352574c768f287b7/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/EventGroupsService.kt#L95)):*
> ```Kotlin
> 
>     for (eventGroup in eventGroups) {
>       val metadata = parsedEventGroupMetadataMap[eventGroup.name]!!
> ```





_Suggestion:_
```Kotlin
parsedEventGroupMetadataMap.getValue(eventGroup.name)
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/EventGroupsService.kt` line 116 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/615#-N72iE4tDIBNNEVT2e0M:-N72iE4tDIBNNEVT2e0N:b-subp63) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c7903b61fb3959c3145fed0a352574c768f287b7/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/EventGroupsService.kt#L116)):*
> ```Kotlin
>     val cmmsMetadata =
>       CmmsEventGroup.Metadata.parseFrom(
>         decryptResult(this@toEventGroup.encryptedMetadata, encryptionPrivateKey).data
> ```

nit: the pattern we tend to follow for cases like this is to put

```kotlin
val source = this
```

at the beginning so we can use that when needed to disambiguate



_Code quote:_
```Kotlin
this@toEventGroup
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/EventGroupsService.kt` line 118 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/615#-N72hqX99oinkuqosD8u:-N72hqX99oinkuqosD8v:b-bcydmk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c7903b61fb3959c3145fed0a352574c768f287b7/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/EventGroupsService.kt#L118)):*
> ```Kotlin
>         decryptResult(this@toEventGroup.encryptedMetadata, encryptionPrivateKey).data
>       )
>     val dataProviderKey =
> ```

Isn't this the event group key, not the data provider key?



_Code quote:_
```Kotlin
dataProviderKey
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/EventGroupsService.kt` line 132 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/615#-N72htmjEIwMVdhTWkRZ:-N72htmjEIwMVdhTWkR_:bnqla0t) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c7903b61fb3959c3145fed0a352574c768f287b7/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/EventGroupsService.kt#L132)):*
> ```Kotlin
>             measurementConsumerKey.measurementConsumerId,
>             dataProviderReferenceId,
>             CmmsEventGroupKey.fromName(this@toEventGroup.name)!!.eventGroupId
> ```

Reuse the `dataProviderKey` variable you already have.



_Code quote:_
```Kotlin
CmmsEventGroupKey.fromName(this@toEventGroup.name)!!
```
___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/EventGroupsServiceTest.kt` line 36 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/615#-N72iapXBzG0gTSzLr80:-N72iapXBzG0gTSzLr81:bluet81) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c7903b61fb3959c3145fed0a352574c768f287b7/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/EventGroupsServiceTest.kt#L36)):*
> ```Kotlin
> import org.mockito.kotlin.any
> import org.wfanet.measurement.api.v2alpha.EventGroupKey
> import org.wfanet.measurement.api.v2alpha.EventGroupKt.metadata as cmmsMetadata
> ```

This is another case that's likely to run afoul of https://youtrack.jetbrains.com/issue/KTIJ-16471.

What you probably want is

```kotlin
import org.wfanet.measurement.api.v2alpha.EventGroupKt as CmmsEventGroups
```

so you can call this as `CmmsEventGroups.metadata`



_Code quote:_
```Kotlin
import org.wfanet.measurement.api.v2alpha.EventGroupKt.metadata as cmmsMetadata
```
___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/EventGroupsServiceTest.kt` line 179 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/615#-N72jKCkDnLEzGeJ-Lrt:-N72jKCkDnLEzGeJ-Lru:b-4sbb2c) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c7903b61fb3959c3145fed0a352574c768f287b7/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/EventGroupsServiceTest.kt#L179)):*
> ```Kotlin
>       )
>   }
>   val cmmsEventGroupsServiceMock2: EventGroupsCoroutineImplBase =
> ```

Don't create a separate set of mocks. Just do your specific stubbing within the test method instead of during initialization.

```kotlin
private val cmmsEventGroupsServiceMock: EventGroupsCoroutineImplBase = mockService()
```

```kotlin
@Test `foo does bar when baz`() {
  cmmsEventGroupsServiceMock.stub {
    onBlocking {
      //...
    }.thenReturn(  /* ... */ )   
  }

  // ...
}
```
___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/EventGroupsServiceTest.kt` line 226 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/615#-N72kcMo-qht70Zjr9P3:-N72kcMo-qht70Zjr9P4:bbnzn2r) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c7903b61fb3959c3145fed0a352574c768f287b7/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/EventGroupsServiceTest.kt#L226)):*
> ```Kotlin
>                 name =
>                   EventGroupKey(
>                       MeasurementConsumerKey.fromName(EVENT_GROUP.measurementConsumer)!!
> ```

This can be a constant



_Code quote:_
```Kotlin
                  EventGroupKey(
                      MeasurementConsumerKey.fromName(EVENT_GROUP.measurementConsumer)!!
                        .measurementConsumerId,
                      DATA_PROVIDER_REFERENCE_ID,
                      EVENT_GROUP_ID
                    )
                    .toName()
```
___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/EventGroupsServiceTest.kt` line 267 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/615#-N72kvXHAbWQ_V6RBpFt:-N72kvXHAbWQ_V6RBpFu:b-7q9mmo) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c7903b61fb3959c3145fed0a352574c768f287b7/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/EventGroupsServiceTest.kt#L267)):*
> ```Kotlin
> 
>     verifyProtoArgument(cmmsE [...]

2022-07-18 19:09 UTC, chipingyeh reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/615)* status: 9 of 13 files reviewed, 12 unresolved discussions (waiting on @SanjayVas, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/EventGroupsService.kt` line 85 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/615#-N72geNqBZEHSvYOqsva:-N7HHMvS12OaKcmGYVjv:byprpa0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c7903b61fb3959c3145fed0a352574c768f287b7/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/EventGroupsService.kt#L85)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Can't this just be `parsedEventGroupMetadataMap.values` ? Regardless, there's already one event group per map entry so there's no need to touch the `eventGroups` collection again.
</blockquote></details>

Yes that's better - done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/EventGroupsService.kt` line 95 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/615#-N72hCoq20bXVZHF6vHl:-N7HHYJk3vD9ddqMcYeA:bo3vl6y) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c7903b61fb3959c3145fed0a352574c768f287b7/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/EventGroupsService.kt#L95)):*
> ```Kotlin
> 
>     for (eventGroup in eventGroups) {
>       val metadata = parsedEventGroupMetadataMap[eventGroup.name]!!
> ```

Thanks, done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/EventGroupsService.kt` line 116 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/615#-N72iE4tDIBNNEVT2e0M:-N7HIfCz6dANqfpIs8Q1:b-g0wsov) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c7903b61fb3959c3145fed0a352574c768f287b7/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/EventGroupsService.kt#L116)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: the pattern we tend to follow for cases like this is to put

```kotlin
val source = this
```

at the beginning so we can use that when needed to disambiguate
</blockquote></details>

Done, although it's not used anywhere currently.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/EventGroupsService.kt` line 118 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/615#-N72hqX99oinkuqosD8u:-N7HPsj6-FPB4mtlC0_r:bko733a) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c7903b61fb3959c3145fed0a352574c768f287b7/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/EventGroupsService.kt#L118)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Isn't this the event group key, not the data provider key?
</blockquote></details>

Yes, good point -- wrapped with DataProviderKey.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/EventGroupsService.kt` line 132 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/615#-N72htmjEIwMVdhTWkRZ:-N7HQPqc0M4Nm6xgixLB:b-shz7pb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c7903b61fb3959c3145fed0a352574c768f287b7/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/EventGroupsService.kt#L132)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Reuse the `dataProviderKey` variable you already have.
</blockquote></details>

Created a new cmmsEventGroupKey and replaced it with that
___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/EventGroupsServiceTest.kt` line 36 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/615#-N72iapXBzG0gTSzLr80:-N7HSHtq3MIOCSy9F-XF:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c7903b61fb3959c3145fed0a352574c768f287b7/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/EventGroupsServiceTest.kt#L36)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This is another case that's likely to run afoul of https://youtrack.jetbrains.com/issue/KTIJ-16471.

What you probably want is

```kotlin
import org.wfanet.measurement.api.v2alpha.EventGroupKt as CmmsEventGroups
```

so you can call this as `CmmsEventGroups.metadata`
</blockquote></details>

Done.
___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/EventGroupsServiceTest.kt` line 179 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/615#-N72jKCkDnLEzGeJ-Lrt:-N7HSkpBC0K4wARIKUB6:b-4unmm1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c7903b61fb3959c3145fed0a352574c768f287b7/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/EventGroupsServiceTest.kt#L179)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Don't create a separate set of mocks. Just do your specific stubbing within the test method instead of during initialization.

```kotlin
private val cmmsEventGroupsServiceMock: EventGroupsCoroutineImplBase = mockService()
```

```kotlin
@Test `foo does bar when baz`() {
  cmmsEventGroupsServiceMock.stub {
    onBlocking {
      //...
    }.thenReturn(  /* ... */ )   
  }

  // ...
}
```


</blockquote></details>

Thanks - done
___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/EventGroupsServiceTest.kt` line 226 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/615#-N72kcMo-qht70Zjr9P3:-N7HW6UT1tNi7cDjvlKL:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c7903b61fb3959c3145fed0a352574c768f287b7/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/EventGroupsServiceTest.kt#L226)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This can be a constant
</blockquote></details>

Done.
___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/EventGroupsServiceTest.kt` line 267 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/615#-N72kvXHAbWQ_V6RBpFt:-N7HWi4L0_knmZ_J_noA:b-ehaknl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c7903b61fb3959c3145fed0a352574c768f287b7/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/EventGroupsServiceTest.kt#L267)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Why do you need this?

We should be confirming that the request contains exactly what we expect and nothing else.
</blockquote></details>

Good point - removed.


<!-- Sent from Reviewable.io -->

2022-07-18 21:40 UTC, SanjayVas requested changes
> Reviewed 1 of 2 files at r8, 1 of 2 files at r9, 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/615)* status: all files reviewed, 9 unresolved discussions (waiting on @chipingyeh, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/EventGroupsService.kt` line 116 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/615#-N72iE4tDIBNNEVT2e0M:-N7ICPte2JraXvDhAjBZ:b-lrh0dc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c7903b61fb3959c3145fed0a352574c768f287b7/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/EventGroupsService.kt#L116)):*
<details><summary><i>Previously, chipingyeh wrote…</i></summary><blockquote>

Done, although it's not used anywhere currently.
</blockquote></details>

The implication was to use `source` instead of `this@toEventGroup`
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/EventGroupsService.kt` line 69 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/615#-N7IBVIAB1vDXBfLmo8C:-N7IBVIAB1vDXBfLmo8D:b-5n7a67) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dd7677420d8ed45a1c08c5071c7ad420571a1d56/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/EventGroupsService.kt#L69)):*
> ```Kotlin
>         .eventGroupsList
>     if (request.filter.isEmpty())
>       return listEventGroupsResponse { this.eventGroups += eventGroups.map { it.toEventGroup() } }
> ```

Doesn't this need to handle page size/token?
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/EventGroupsService.kt` line 72 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/615#-N7IC1deAHod0XzvD8o8:-N7IC1deAHod0XzvD8o9:bedvqyj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dd7677420d8ed45a1c08c5071c7ad420571a1d56/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/EventGroupsService.kt#L72)):*
> ```Kotlin
>     val parsedEventGroupMetadataMap: Map<String, CmmsEventGroup.Metadata> =
>       eventGroups
>         .map {
> ```

nit: `associate` instead of `map` + `toMap`
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/EventGroupsService.kt` line 107 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/615#-N7IB_hhCd4AJm7snKae:-N7IB_hhCd4AJm7snKaf:b-5n7a67) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dd7677420d8ed45a1c08c5071c7ad420571a1d56/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/EventGroupsService.kt#L107)):*
> ```Kotlin
> 
>     return listEventGroupsResponse {
>       this.eventGroups += filteredEventGroups.map { it.toEventGroup() }
> ```

Doesn't this need to handle page size/token?
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/EventGroupsService.kt` line 121 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/615#-N7IDEUBDg1NRfrdMD0f:-N7IDEUBDg1NRfrdMD0g:b-njptuz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dd7677420d8ed45a1c08c5071c7ad420571a1d56/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/EventGroupsService.kt#L121)):*
> ```Kotlin
>         "Event group name is missing"
>       }
>     val dataProviderKey = DataProviderKey(cmmsEventGroupKey.dataProviderId)
> ```

nit: inline this since it only needs to be used once to get the DataProvider resource name (use `cmmsEventGroupKey` ti access the CMMS data provider ID)
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/EventGroupsService.kt` line 122 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/615#-N7ID8Ns7Io5V4zrfERw:-N7ID8Ns7Io5V4zrfERx:b-jweewb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dd7677420d8ed45a1c08c5071c7ad420571a1d56/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/EventGroupsService.kt#L122)):*
> ```Kotlin
>       }
>     val dataProviderKey = DataProviderKey(cmmsEventGroupKey.dataProviderId)
>     val dataProviderReferenceId = dataProviderKey.dataProviderId
> ```

nit: inline this since it's only used once and having a separate variable doesn't add anything
___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/EventGroupsServiceTest.kt` line 130 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/615#-N7IE6bLA27KQE-zBCLh:-N7IE6bLA27KQE-zBCLi:b-cw8mcq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dd7677420d8ed45a1c08c5071c7ad420571a1d56/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/EventGroupsServiceTest.kt#L130)):*
> ```Kotlin
>     )
> }
> private val RETURNED_EVENT_GROUP = eventGroup {
> ```

nit: this isn't actually returned by anything. I assume this is just your constant for a Reporting API event group instance.

Perhaps just prefix your other event group constants with `CMMS_` and then this can just be `EVENT_GROUP`.



_Code quote:_
```Kotlin
RETURNED_EVENT_GROUP
```


<!-- Sent from Reviewable.io -->

2022-07-20 03:42 UTC, chipingyeh reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/615)* status: 9 of 14 files reviewed, 4 unresolved discussions (waiting on @SanjayVas, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/EventGroupsService.kt` line 116 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/615#-N72iE4tDIBNNEVT2e0M:-N7MnqfN4f-t4OMEYZUG:bgc5lps) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c7903b61fb3959c3145fed0a352574c768f287b7/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/EventGroupsService.kt#L116)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The implication was to use `source` instead of `this@toEventGroup`
</blockquote></details>

Ah. I had thought `this` and `this@toEventGroup` were distinct from each other. Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/EventGroupsService.kt` line 69 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/615#-N7IBVIAB1vDXBfLmo8C:-N7OVG6e1HtYwOJCl6Oq:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dd7677420d8ed45a1c08c5071c7ad420571a1d56/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/EventGroupsService.kt#L69)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Doesn't this need to handle page size/token?
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/EventGroupsService.kt` line 107 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/615#-N7IB_hhCd4AJm7snKae:-N7OVGql-8p6kbtr4OHQ:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dd7677420d8ed45a1c08c5071c7ad420571a1d56/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/EventGroupsService.kt#L107)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Doesn't this need to handle page size/token?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-20 17:55 UTC, SanjayVas requested changes
> Reviewed 5 of 5 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/615)* status: all files reviewed, 6 unresolved discussions (waiting on @chipingyeh, @stevenwarejones, and @tristanvuong2021)

___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/EventGroupsServiceTest.kt` line 79 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/615#-N7Rhgbm9727BAYYk3jS:-N7Rhgbm9727BAYYk3jT:buc3kym) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dc433ef6800563d2856a55c8f3f9759adbf619c0/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/EventGroupsServiceTest.kt#L79)):*
> ```Kotlin
>     )
>   )
> val ENCRYPTION_PRIVATE_KEY = loadEncryptionPrivateKey("mc_enc_private.tink")
> ```

private



_Code quote:_
```Kotlin
val ENCRYPTION_PRIVATE_KEY = loadEncryptionPrivateKey("mc_enc_private.tink")
val ENCRYPTION_PUBLIC_KEY = loadEncryptionPublicKey("mc_enc_public.tink")
val EDP_SIGNING_KEY = loadSigningKey("edp1_cs_cert.der", "edp1_cs_private.der")
```
___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/EventGroupsServiceTest.kt` line 82 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/615#-N7RgWqq5Q7unem17MSK:-N7RgWqq5Q7unem17MSL:b-5naj93) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dc433ef6800563d2856a55c8f3f9759adbf619c0/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/EventGroupsServiceTest.kt#L82)):*
> ```Kotlin
> val ENCRYPTION_PUBLIC_KEY = loadEncryptionPublicKey("mc_enc_public.tink")
> val EDP_SIGNING_KEY = loadSigningKey("edp1_cs_cert.der", "edp1_cs_private.der")
> private const val MEASUREMENT_CONSUMER_EXTERNAL_ID = 111L
> ```

Just use an arbitrary string here and drop `MEASUREMENT_CONSUMER_EXTERNAL_ID`.

The fact that the CMMS MC ID is a base64url-encoded 64-bit integer is an implementation detail of the Kingdom, and should not be assumed in Reporting server code.



_Code quote:_
```Kotlin
private const val MEASUREMENT_CONSUMER_EXTERNAL_ID = 111L
private val MEASUREMENT_CONSUMER_REFERENCE_ID = externalIdToApiId(MEASUREMENT_CONSUMER_EXTERNAL_ID)
```
___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/EventGroupsServiceTest.kt` line 133 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/615#-N7RgI7OEnV3_QFSuq_s:-N7RgI7OEnV3_QFSuq_t:b2vbopn) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dc433ef6800563d2856a55c8f3f9759adbf619c0/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/EventGroupsServiceTest.kt#L133)):*
> ```Kotlin
>   name =
>     EventGroupKey(
>         MeasurementConsumerKey.fromName(CMMS_EVENT_GROUP.measurementConsumer)!!
> ```

Isn't this already a constant as `MEASUREMENT_CONSUMER_REFERENCE_ID`?



_Code quote:_
```Kotlin
        MeasurementConsumerKey.fromName(CMMS_EVENT_GROUP.measurementConsumer)!!
          .measurementConsumerId,
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/EventGroupsService.kt` line 113 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/615#-N7RfO-NBPPLnJR61vdb:-N7RfO-NBPPLnJR61vdc:btuxes3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dc433ef6800563d2856a55c8f3f9759adbf619c0/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/EventGroupsService.kt#L113)):*
> ```Kotlin
>   }
> 
>   private fun CmmsEventGroup.toEventGroup(): EventGroup {
> ```

nit: if this doesn't use any instance state, then it should be "static" (declared either in a companion object or outside of the class)
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/EventGroupsService.kt` line 117 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/615#-N7ReruL52f6DeKswRUv:-N7ReruL52f6DeKswRUw:b-1x10v2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dc433ef6800563d2856a55c8f3f9759adbf619c0/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/EventGroupsService.kt#L117)):*
> ```Kotlin
>     val cmmsMetadata =
>       CmmsEventGroup.Metadata.parseFrom(
>         decryptResult(source.encryptedMetadata, encryptionPrivateKey).data
> ```

nit: no need qualify with `source` or `this` in the top-level scope of a receiver function, since you can just rely on ["implicit `this`"](https://kotlinlang.org/docs/this-expressions.html#implicit-this)



_Code quote:_
```Kotlin
source.
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/EventGroupsService.kt` line 116 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/615#-N72iE4tDIBNNEVT2e0M:-N7RdHLL-je42G-Y4fnq:b-967zni) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c7903b61fb3959c3145fed0a352574c768f287b7/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/EventGroupsService.kt#L116)):*
<details><summary><i>Previously, chipingyeh wrote…</i></summary><blockquote>

Ah. I had thought `this` and `this@toEventGroup` were distinct from each other. Done.
</blockquote></details>

They are different once inside of another [scope function](https://kotlinlang.org/docs/scope-functions.html) such as a DSL builder. Hence why we do `val source = this` in the function scope, so we don't have to use ["qualified `this`"](https://kotlinlang.org/docs/this-expressions.html#qualified-this) in order to disambiguate inside of the builder scope.


<!-- Sent from Reviewable.io -->

2022-07-20 19:10 UTC, chipingyeh reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/615)* status: 12 of 14 files reviewed, 4 unresolved discussions (waiting on @SanjayVas, @stevenwarejones, and @tristanvuong2021)

___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/EventGroupsServiceTest.kt` line 79 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/615#-N7Rhgbm9727BAYYk3jS:-N7RyPyV0FE6WbuwMlfH:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dc433ef6800563d2856a55c8f3f9759adbf619c0/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/EventGroupsServiceTest.kt#L79)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

private
</blockquote></details>

Done.
___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/EventGroupsServiceTest.kt` line 82 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/615#-N7RgWqq5Q7unem17MSK:-N7RybD73ilKemT2rjiT:bple607) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dc433ef6800563d2856a55c8f3f9759adbf619c0/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/EventGroupsServiceTest.kt#L82)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Just use an arbitrary string here and drop `MEASUREMENT_CONSUMER_EXTERNAL_ID`.

The fact that the CMMS MC ID is a base64url-encoded 64-bit integer is an implementation detail of the Kingdom, and should not be assumed in Reporting server code.
</blockquote></details>

Makes sense - done.
___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/EventGroupsServiceTest.kt` line 133 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/615#-N7RgI7OEnV3_QFSuq_s:-N7RzKFa6o46_FjB5klf:b-t9862u) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dc433ef6800563d2856a55c8f3f9759adbf619c0/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/EventGroupsServiceTest.kt#L133)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Isn't this already a constant as `MEASUREMENT_CONSUMER_REFERENCE_ID`?
</blockquote></details>

Yes; updated.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/EventGroupsService.kt` line 113 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/615#-N7RfO-NBPPLnJR61vdb:-N7Rw3he0pj48qFguQNZ:bf46qz6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dc433ef6800563d2856a55c8f3f9759adbf619c0/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/EventGroupsService.kt#L113)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: if this doesn't use any instance state, then it should be "static" (declared either in a companion object or outside of the class)
</blockquote></details>

In this case encryptionPrivateKey is injected into the instance, so I'd need to keep it here until it's updated
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/EventGroupsService.kt` line 116 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/615#-N72iE4tDIBNNEVT2e0M:-N7RwMw60pJeiRZNUW2S:b-xdyrf8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c7903b61fb3959c3145fed0a352574c768f287b7/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/EventGroupsService.kt#L116)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

They are different once inside of another [scope function](https://kotlinlang.org/docs/scope-functions.html) such as a DSL builder. Hence why we do `val source = this` in the function scope, so we don't have to use ["qualified `this`"](https://kotlinlang.org/docs/this-expressions.html#qualified-this) in order to disambiguate inside of the builder scope.
</blockquote></details>

Got it, so I didn't actually need to use this@toEventGroup outside of the builder before -- I see you addressed that in the below comment.


<!-- Sent from Reviewable.io -->

2022-07-20 20:59 UTC, SanjayVas approved these changes
> Reviewed 2 of 2 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/615)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/EventGroupsService.kt` line 113 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/615#-N7RfO-NBPPLnJR61vdb:-N7SOvQTEZBz85130S02:b-clty2x) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dc433ef6800563d2856a55c8f3f9759adbf619c0/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/EventGroupsService.kt#L113)):*
<details><summary><i>Previously, chipingyeh wrote…</i></summary><blockquote>

In this case encryptionPrivateKey is injected into the instance, so I'd need to keep it here until it's updated
</blockquote></details>

Well, you could take that one item in as a parameter. No big deal either way, I just like to reduce the amount of things that could be `this`.


<!-- Sent from Reviewable.io -->

2022-07-21 14:37 UTC, chipingyeh reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/615)* status: 13 of 14 files reviewed, 1 unresolved discussion (waiting on @SanjayVas, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/EventGroupsService.kt` line 113 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/615#-N7RfO-NBPPLnJR61vdb:-N7W6v6B9pgnNVVpuz_u:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dc433ef6800563d2856a55c8f3f9759adbf619c0/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/EventGroupsService.kt#L113)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Well, you could take that one item in as a parameter. No big deal either way, I just like to reduce the amount of things that could be `this`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-21 14:37 UTC, chipingyeh reviewed
> Reviewed 5 of 12 files at r2, 2 of 5 files at r11, 1 of 2 files at r12, 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/615)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas, @stevenwarejones, and @tristanvuong2021)



<!-- Sent from Reviewable.io -->

2022-07-21 18:21 UTC, SanjayVas approved these changes
> Reviewed 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/615)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones and @tristanvuong2021)



<!-- Sent from Reviewable.io -->

2022-07-21 18:29 UTC, chipingyeh reviewed
> Dismissed @stevenwarejones from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/615)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones and @tristanvuong2021)



<!-- Sent from Reviewable.io -->

2022-07-21 19:26 UTC, tristanvuong2021 approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/615)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)



<!-- Sent from Reviewable.io -->

2022-07-21 19:27 UTC, merged