Change simulator tests to run process method
world-federation-of-advertisers/cross-media-measurement pull request #620
Opened 2022-07-06 22:07 UTC by jcorilla

2022-07-12 19:47 UTC, iverson52000 approved these changes
> Reviewed 2 of 5 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/620)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @duliomatos1, @SanjayVas, and @uakyol)



<!-- Sent from Reviewable.io -->

2022-07-13 15:26 UTC, uakyol reviewed
Overall looks good. Couple of points to address.

2022-07-13 15:26 UTC, uakyol commented on src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt
> +      delay(1000)
Sorry to write here, something weird is going on, I can't review on reviewable. Lets do here for now.

This delay and cancelAndJoin pattern seems fragile. Did you see this somewhere in the codebase?

2022-07-13 15:26 UTC, uakyol commented on src/test/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulatorImplTest.kt
>  import org.junit.runner.RunWith
Lets change the file name to FrontendSimulatorTest.kt . The Impl there was wrong naming

2022-07-13 15:26 UTC, uakyol commented on src/test/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulatorImplTest.kt
> +  name = "rf measurement"
maybe rfMeasurement ? Spaces in names scare me :)

2022-07-14 01:33 UTC, SanjayVas requested changes
> Reviewed 1 of 5 files at r1, 1 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/620)* status: all files reviewed, 5 unresolved discussions (waiting on @duliomatos1, @jcorilla, and @uakyol)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/620#-N6uGnreBKGKWNw1A48S:-N6uGnreBKGKWNw1A48T:b-fnfkb) (no related file):*
Just so I better understand what's happening with this change, it seems like the intent is to have EdpSimulatorTest run the EdpSimulator daemon in a parallel coroutine? Can you explain why we'd want to do this?

My assumption is that we have no need to test the daemonization of the simulator, but rather individual runs of its event loop. What I would recommend doing is making `generateSketch` private since that shouldn't really be part of the public API, and instead expose `createEventGroup` and `executeRequisitionFulfillingWorkflow`.

Testing a daemon reliably is otherwise quite tricky, as you need to observe and wait for state changes.

___
___
*[`src/test/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/EventFiltersTest.kt` line 50 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/620#-N6uGP4n91w0qReqw8o_:-N6uGP4n91w0qReqw8oa:b-1f5d64) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/52fbaf3c43cdbe8431b5d67d7a9825521989c38a/src/test/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/EventFiltersTest.kt#L50)):*
> ```Kotlin
>   @Test
>   fun `filters even when condition does not match`() {
>     val program = EventFilters.compileProgram(" video_ad.age.value != 1", testEvent {})
> ```

Using getDefaultInstance() is better as it may return a singleton rather than constructing a new object.



_Code quote:_
```Kotlin
testEvent {}
```
___
*[`src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt` line 372 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/620#-N6KYQPsVignbCg-sjzJ-r2-372:-N6uJbGqBcDG0_bHkU6e:bldhcbj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/52fbaf3c43cdbe8431b5d67d7a9825521989c38a/src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt#L372)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

This delay and cancelAndJoin pattern seems fragile. Did you see this somewhere in the codebase?
</blockquote></details>

+1. Definitely should not have a test that just waits for an arbitrary amount of time and hopes some background process will complete during that period.

Testing a daemon reliably is difficult, as you need to wait for the appropriate observable state changes. e.g. by having your requisition fulfillment service mock signal on some shared awaitable object (such as `CompletableJob` or `SharedFlow`) when it's called.


<!-- Sent from Reviewable.io -->

2022-07-19 22:28 UTC, jcorilla reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/620)* status: 0 of 77 files reviewed, 5 unresolved discussions (waiting on @duliomatos1, @iverson52000, @SanjayVas, and @uakyol)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/620#-N6uGnreBKGKWNw1A48S:-N7NYvdvAAwxDWV8Dxuu:b-yj9oru) (no related file):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Just so I better understand what's happening with this change, it seems like the intent is to have EdpSimulatorTest run the EdpSimulator daemon in a parallel coroutine? Can you explain why we'd want to do this?

My assumption is that we have no need to test the daemonization of the simulator, but rather individual runs of its event loop. What I would recommend doing is making `generateSketch` private since that shouldn't really be part of the public API, and instead expose `createEventGroup` and `executeRequisitionFulfillingWorkflow`.

Testing a daemon reliably is otherwise quite tricky, as you need to observe and wait for state changes.
</blockquote></details>

Following your recommendation to test using createEventGroup and executeRequisitionFulfillingWorkflow. The intent was to test a run through the event loop - I agree with not using the coroutine

___
___
*[`src/test/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/EventFiltersTest.kt` line 50 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/620#-N6uGP4n91w0qReqw8o_:-N7NYlF89MqTIILSEpwx:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/52fbaf3c43cdbe8431b5d67d7a9825521989c38a/src/test/kotlin/org/wfanet/measurement/eventdataprovider/eventfiltration/EventFiltersTest.kt#L50)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Using getDefaultInstance() is better as it may return a singleton rather than constructing a new object.
</blockquote></details>

Done.
___
*[`src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt` line 372 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/620#-N6KYQPsVignbCg-sjzJ-r2-372:-N7NZOsy0p5gZvh4fkWQ:b-i4hu5g) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/52fbaf3c43cdbe8431b5d67d7a9825521989c38a/src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt#L372)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

+1. Definitely should not have a test that just waits for an arbitrary amount of time and hopes some background process will complete during that period.

Testing a daemon reliably is difficult, as you need to wait for the appropriate observable state changes. e.g. by having your requisition fulfillment service mock signal on some shared awaitable object (such as `CompletableJob` or `SharedFlow`) when it's called.
</blockquote></details>

Exposing the recommended methods instead now
___
*[`src/test/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulatorImplTest.kt` line 24 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/620#-N6KYQPsVignbCg-sjzL-r2-24:-N7NYu-s5aYFJtW4g-xv:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/52fbaf3c43cdbe8431b5d67d7a9825521989c38a/src/test/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulatorImplTest.kt#L24)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

Lets change the file name to FrontendSimulatorTest.kt . The Impl there was wrong naming
</blockquote></details>

Done.
___
*[`src/test/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulatorImplTest.kt` line 142 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/620#-N6KYQPsVignbCg-sjzL-r2-142:-N7NYut3DtcVwadwGfuZ:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/52fbaf3c43cdbe8431b5d67d7a9825521989c38a/src/test/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulatorImplTest.kt#L142)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

maybe rfMeasurement ? Spaces in names scare me :)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-20 19:52 UTC, uakyol approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/620)* status: 0 of 77 files reviewed, 5 unresolved discussions (waiting on @duliomatos1, @iverson52000, @SanjayVas, and @uakyol)



<!-- Sent from Reviewable.io -->

2022-07-20 20:57 UTC, jcorilla reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/620)* status: 0 of 77 files reviewed, 6 unresolved discussions (waiting on @duliomatos1, @iverson52000, @SanjayVas, and @uakyol)

___
*[`src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt` line 188 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/620#-N7SOi8X8W1PmCve8MVG:-N7SOi8X8W1PmCve8MVH:b-pwjpp8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a3fb7a70b5164e49ce701b7e018c37f56cd87255/src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt#L188)):*
> ```Kotlin
> private val CONSENT_SIGNALING_ELGAMAL_PUBLIC_KEY = elGamalPublicKey {
>   ellipticCurveId = 415
>   generator =
> ```

@sanjayvas To pass encoding checks that were previously silently failing I'm setting the generator and element fields for elGamalPublicKey using the example from one of our [encrypter tests from the any sketch repo](https://github.com/world-federation-of-advertisers/any-sketch-java/blob/a63d47ace86d025ec3330f341d1ba4b5573fe756/src/test/java/org/wfanet/anysketch/crypto/SketchJavaEncrypterTest.java#L42). 

But now our [linter fails after it trys to set one value per line for the arrays](https://github.com/world-federation-of-advertisers/cross-media-measurement/runs/7437631228?check_suite_focus=true) 

Do you have any suggestions for the linting issue?


<!-- Sent from Reviewable.io -->

2022-07-21 22:52 UTC, SanjayVas requested changes
> Reviewed 1 of 5 files at r3, 72 of 73 files at r12, 2 of 2 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/620)* status: 75 of 77 files reviewed, 11 unresolved discussions (waiting on @duliomatos1, @iverson52000, @jcorilla, @SanjayVas, and @uakyol)

___
*[`src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt` line 188 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/620#-N7SOi8X8W1PmCve8MVG:-N7XIP6j0vraTxKin8eS:b4uljqw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a3fb7a70b5164e49ce701b7e018c37f56cd87255/src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt#L188)):*
<details><summary><i>Previously, jcorilla wrote…</i></summary><blockquote>

@sanjayvas To pass encoding checks that were previously silently failing I'm setting the generator and element fields for elGamalPublicKey using the example from one of our [encrypter tests from the any sketch repo](https://github.com/world-federation-of-advertisers/any-sketch-java/blob/a63d47ace86d025ec3330f341d1ba4b5573fe756/src/test/java/org/wfanet/anysketch/crypto/SketchJavaEncrypterTest.java#L42). 

But now our [linter fails after it trys to set one value per line for the arrays](https://github.com/world-federation-of-advertisers/cross-media-measurement/runs/7437631228?check_suite_focus=true) 

Do you have any suggestions for the linting issue?
</blockquote></details>

Use whatever `ktftmt` produces unless it breaks something, in which case file a bug on ktfmt and look for a workaround.

If you don't like having these split across as many lines, you can use another encoding. e.g. `org.wfanet.measurement.common.HexString`.
___
*[`src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt` line 189 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/620#-N7XJAk03Hf2FpwYDUo3:-N7XJAk1EmkyTSSWDavy:b-6rhtpf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a3fb7a70b5164e49ce701b7e018c37f56cd87255/src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt#L189)):*
> ```Kotlin
>   ellipticCurveId = 415
>   generator =
>     ByteString.copyFrom(
> ```

`org.wfanet.measurement.common.byteStringOf`



_Code quote:_
```Kotlin
    ByteString.copyFrom(
      byteArrayOf(
```
___
*[`src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt` line 396 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/620#-N7XagvsDfdDVj6etzXX:-N7XagvsDfdDVj6etzXY:b-wiip3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a3fb7a70b5164e49ce701b7e018c37f56cd87255/src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt#L396)):*
> ```Kotlin
>       assertThat(storedSketch).isNotNull()
> 
>       val anySketchesResult = SketchProtos.toAnySketch(Sketch.parseFrom(storedSketch))
> ```

Is this supposed to be plural?



_Code quote:_
```Kotlin
Sketches
```
___
*[`src/test/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulatorImplTest.kt` line 142 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/620#-N6KYQPsVignbCg-sjzL-r2-142:-N7XdbAjCe0rYF1m09ew:bakocp8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/52fbaf3c43cdbe8431b5d67d7a9825521989c38a/src/test/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulatorImplTest.kt#L142)):*
<details><summary><i>Previously, jcorilla wrote…</i></summary><blockquote>

Done.
</blockquote></details>

nit: this should be of the form `measurementConsumers/<MC ID>/measurements/<Measurement ID>` if you want to more closely match a real value

Since you already have a `MEASUREMENT_CONSUMER_NAME` constant, maybe start with that?

```kotlin
name = "$MEASUREMENT_CONSUMER_NAME/measurements/YENiIm1WA94`
```
___
*[`src/test/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulatorTest.kt` line 87 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/620#-N7Xc6FhDmZxoEkfWDlT:-N7Xc6FhDmZxoEkfWDlU:b-z1m93s) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a3fb7a70b5164e49ce701b7e018c37f56cd87255/src/test/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulatorTest.kt#L87)):*
> ```Kotlin
> private val REQUISITION_ONE = requisition { name = "requisition_one" }
> private val REQUISITION_TWO = requisition { name = "requisition_two" }
> private val REQUISITION_LIST = listRequisitionsResponse {
> ```

nit: this is not a `List<Requisition>`, which is the type I would expect from something with this name



_Code quote:_
```Kotlin
REQUISITION_LIST
```
___
*[`src/test/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulatorTest.kt` line 250 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/620#-N7Xw4Tp3se_hhB2MyWo:-N7Xw4Tp3se_hhB2MyWp:bkr1zog) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a3fb7a70b5164e49ce701b7e018c37f56cd87255/src/test/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulatorTest.kt#L250)):*
> ```Kotlin
>       }
>     }
>     assertThat(anySketchesResult)
> ```

As far as I can tell, this doesn't actually test FrontendSimulator at all. The test still passes if you remove the call to `executeReachAndFrequency`.

Despite the name, FrontendSimulator is actually a test runner. You usually don't write tests against those. If you really want to test the estimation code, you could extract it to a separate class and write a test for that. That said, it's mostly just calling the AnySketch library which already has its own tests.
___
*[`src/test/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulatorTest.kt` line 321 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/620#-N7XfFsPAw4u4G_7OnBI:-N7XfFsQ8P8MY3LRt8kd:bihqwnn) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a3fb7a70b5164e49ce701b7e018c37f56cd87255/src/test/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulatorTest.kt#L321)):*
> ```Kotlin
>     }
> 
>     private fun estimateCardinality(
> ```

This looks suspiciously like the same code in FrontendSimulator itself, which what we're trying to test.


<!-- Sent from Reviewable.io -->

2022-07-23 00:41 UTC, jcorilla reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/620)* status: 73 of 77 files reviewed, 8 unresolved discussions (waiting on @duliomatos1, @iverson52000, @SanjayVas, and @uakyol)

___
*[`src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt` line 188 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/620#-N7SOi8X8W1PmCve8MVG:-N7b_Q_Q4PvkeaP_ituM:b-5a9h0y) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a3fb7a70b5164e49ce701b7e018c37f56cd87255/src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt#L188)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Use whatever `ktftmt` produces unless it breaks something, in which case file a bug on ktfmt and look for a workaround.

If you don't like having these split across as many lines, you can use another encoding. e.g. `org.wfanet.measurement.common.HexString`.


</blockquote></details>

Changing encoding to avoid the line split
___
*[`src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt` line 189 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/620#-N7XJAk03Hf2FpwYDUo3:-N7b_CsfD6cZ7u4dPRmp:bm8b9es) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a3fb7a70b5164e49ce701b7e018c37f56cd87255/src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt#L189)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

`org.wfanet.measurement.common.byteStringOf`
</blockquote></details>

Changed encoding
___
*[`src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt` line 396 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/620#-N7XagvsDfdDVj6etzXX:-N7b_Yan0Z6libqBe_Zy:br3l1fn) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a3fb7a70b5164e49ce701b7e018c37f56cd87255/src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt#L396)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Is this supposed to be plural?
</blockquote></details>

Done , changed to singular
___
*[`src/test/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulatorImplTest.kt` line 142 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/620#-N6KYQPsVignbCg-sjzL-r2-142:-N7bbDQEBwGWkVnl8jmz:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/52fbaf3c43cdbe8431b5d67d7a9825521989c38a/src/test/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulatorImplTest.kt#L142)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: this should be of the form `measurementConsumers/<MC ID>/measurements/<Measurement ID>` if you want to more closely match a real value

Since you already have a `MEASUREMENT_CONSUMER_NAME` constant, maybe start with that?

```kotlin
name = "$MEASUREMENT_CONSUMER_NAME/measurements/YENiIm1WA94`
```
</blockquote></details>

Done.
___
*[`src/test/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulatorTest.kt` line 87 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/620#-N7Xc6FhDmZxoEkfWDlT:-N7bax4LDUO-1zgbOfh4:b-hkumto) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a3fb7a70b5164e49ce701b7e018c37f56cd87255/src/test/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulatorTest.kt#L87)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: this is not a `List<Requisition>`, which is the type I would expect from something with this name
</blockquote></details>

Done, only used requisition_list once - replaced the use with listOf
___
*[`src/test/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulatorTest.kt` line 250 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/620#-N7Xw4Tp3se_hhB2MyWo:-N7cOY6h8o1Jey12Lgo9:b-ijjcd0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a3fb7a70b5164e49ce701b7e018c37f56cd87255/src/test/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulatorTest.kt#L250)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

As far as I can tell, this doesn't actually test FrontendSimulator at all. The test still passes if you remove the call to `executeReachAndFrequency`.

Despite the name, FrontendSimulator is actually a test runner. You usually don't write tests against those. If you really want to test the estimation code, you could extract it to a separate class and write a test for that. That said, it's mostly just calling the AnySketch library which already has its own tests.
</blockquote></details>

Good point, perhaps verifying ```executeReachAndFrequency``` leads to ```createMeasurement``` and ```getMeasurement``` calls would be better for checking we looped through expected calls?

Then should we (also) keep the original ```getExpectedResult``` test to verify the estimation part of the code? @uakyol 
___
*[`src/test/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulatorTest.kt` line 321 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/620#-N7XfFsPAw4u4G_7OnBI:-N7cQgmI3Jin70evP4WF:b-leku2l) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a3fb7a70b5164e49ce701b7e018c37f56cd87255/src/test/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulatorTest.kt#L321)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This looks suspiciously like the same code in FrontendSimulator itself, which what we're trying to test.
</blockquote></details>

Intent of the changes was originally to test a run of a loop through FrontEndSimulator in place of the ```getExpectedResult``` test that existed.  

As per the other comment - thinking now it might be better to test a run and separately test/keep the estimation test - it would get rid of the need to have this duplication. Initial discussion with @uakyol led to decision to not make the estimation methods public.


<!-- Sent from Reviewable.io -->

2022-07-26 20:00 UTC, SanjayVas requested changes
> Reviewed 1 of 3 files at r11, 3 of 3 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/620)* status: all files reviewed, 6 unresolved discussions (waiting on @duliomatos1, @SanjayVas, and @uakyol)

___
*[`src/test/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulatorTest.kt` line 250 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/620#-N7Xw4Tp3se_hhB2MyWo:-N7w3Wpq5TVw2qd2QwrP:b-to0xrw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a3fb7a70b5164e49ce701b7e018c37f56cd87255/src/test/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulatorTest.kt#L250)):*
<details><summary><i>Previously, jcorilla wrote…</i></summary><blockquote>

Good point, perhaps verifying ```executeReachAndFrequency``` leads to ```createMeasurement``` and ```getMeasurement``` calls would be better for checking we looped through expected calls?

Then should we (also) keep the original ```getExpectedResult``` test to verify the estimation part of the code? @uakyol 
</blockquote></details>

There are already tests for the underlying Estimators from any-sketch. Any other parts of FrontendSimulator that are considered interesting/complex enough to test should likely be split to separate classes and tested separately. 

FrontendSimulator itself should not be tested. It's basically the test method portion of a test class (where setup and teardown are done manually), so testing it is the equivalent of testing a test class. This is also why I say that FrontendSimulator is probably misnamed.
___
*[`src/test/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulatorTest.kt` line 321 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/620#-N7XfFsPAw4u4G_7OnBI:-N7w3GtSAOm47LBE2Rfk:b-tf9q6p) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a3fb7a70b5164e49ce701b7e018c37f56cd87255/src/test/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulatorTest.kt#L321)):*
<details><summary><i>Previously, jcorilla wrote…</i></summary><blockquote>

Intent of the changes was originally to test a run of a loop through FrontEndSimulator in place of the ```getExpectedResult``` test that existed.  

As per the other comment - thinking now it might be better to test a run and separately test/keep the estimation test - it would get rid of the need to have this duplication. Initial discussion with @uakyol led to decision to not make the estimation methods public.


</blockquote></details>

The problem isn't the duplication, but rather with having your test rely on calling methods of the class being tested to generate the expected result.

It's basically verifying a tautology at that point and not actually testing anything.


<!-- Sent from Reviewable.io -->

2022-07-26 20:33 UTC, uakyol reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/620)* status: all files reviewed, 6 unresolved discussions (waiting on @duliomatos1, @SanjayVas, and @uakyol)

___
*[`src/test/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulatorTest.kt` line 250 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/620#-N7Xw4Tp3se_hhB2MyWo:-N7wCVC-BjvI2YSKKXzU:b-yozjbe) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a3fb7a70b5164e49ce701b7e018c37f56cd87255/src/test/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulatorTest.kt#L250)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

There are already tests for the underlying Estimators from any-sketch. Any other parts of FrontendSimulator that are considered interesting/complex enough to test should likely be split to separate classes and tested separately. 

FrontendSimulator itself should not be tested. It's basically the test method portion of a test class (where setup and teardown are done manually), so testing it is the equivalent of testing a test class. This is also why I say that FrontendSimulator is probably misnamed.
</blockquote></details>

how about just deleting this test then? 


<!-- Sent from Reviewable.io -->

2022-07-26 21:00 UTC, SanjayVas requested changes
> Reviewed 1 of 3 files at r11.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/620)* status: all files reviewed, 6 unresolved discussions (waiting on @duliomatos1, @jcorilla, @SanjayVas, and @uakyol)

___
*[`src/test/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulatorTest.kt` line 250 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/620#-N7Xw4Tp3se_hhB2MyWo:-N7wIlHs5QuOMVdVqQEa:b6gwi9y) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a3fb7a70b5164e49ce701b7e018c37f56cd87255/src/test/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulatorTest.kt#L250)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

how about just deleting this test then? 
</blockquote></details>

Yeah, that's fine for this PR.


<!-- Sent from Reviewable.io -->

2022-07-26 23:53 UTC, jcorilla reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/620)* status: 75 of 77 files reviewed, 6 unresolved discussions (waiting on @duliomatos1, @SanjayVas, and @uakyol)

___
*[`src/test/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulatorTest.kt` line 250 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/620#-N7Xw4Tp3se_hhB2MyWo:-N7wv1tJ1lkj2RUUpxdP:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a3fb7a70b5164e49ce701b7e018c37f56cd87255/src/test/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulatorTest.kt#L250)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Yeah, that's fine for this PR.
</blockquote></details>

Done.
___
*[`src/test/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulatorTest.kt` line 321 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/620#-N7XfFsPAw4u4G_7OnBI:-N7wv3c2-6_grLoWoqw-:b35l4rz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a3fb7a70b5164e49ce701b7e018c37f56cd87255/src/test/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulatorTest.kt#L321)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The problem isn't the duplication, but rather with having your test rely on calling methods of the class being tested to generate the expected result.

It's basically verifying a tautology at that point and not actually testing anything.
</blockquote></details>

Done. That makes sense, removed along with the rest of the test. 


<!-- Sent from Reviewable.io -->

2022-07-27 15:57 UTC, SanjayVas approved these changes
> Reviewed 2 of 2 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/620)* status: all files reviewed, 4 unresolved discussions (waiting on @duliomatos1, @SanjayVas, and @uakyol)



<!-- Sent from Reviewable.io -->

2022-07-28 14:33 UTC, duliomatos1 approved these changes
> Reviewed 2 of 3 files at r14, 2 of 2 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/620)* status: all files reviewed, 4 unresolved discussions (waiting on @SanjayVas and @uakyol)



<!-- Sent from Reviewable.io -->

2022-07-28 20:17 UTC, jcorilla reviewed
> Dismissed @uakyol from 3 discussions.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/620)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @SanjayVas)



<!-- Sent from Reviewable.io -->

2022-07-28 20:25 UTC, jcorilla reviewed
> Reviewed 2 of 3 files at r14, 2 of 2 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/620)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)



<!-- Sent from Reviewable.io -->

2022-07-28 20:27 UTC, merged