Add the implementation of `CreateReport` in `ReportsService`.
world-federation-of-advertisers/cross-media-measurement pull request #630
Opened 2022-07-18 00:00 UTC by riemanli

This adds the implementation of `CreateReport` based on the API design of `ReportsService`. Note that updating report and associated measurements is deferred till `ListReports` and `GetReport` are requested.

This PR depends on the open PRs #624 and #627. The files that contain the extra changes from these two PRs are:
* build/repositories.bzl
* src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/SetOperationCompiler.kt
* src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/SetOperationCompilerTest.kt

which can be ignored.

2022-07-18 18:07 UTC, tristanvuong2021 reviewed
You can base the the PR onto the set operation compiler branch instead of main to just show the changes relevant to this.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630#-:-N7HUKcl9H0wXPTdZM5n:b-qckvec)* status: 0 of 9 files reviewed, all discussions resolved (waiting on @renjiezh and @SanjayVas)



<!-- Sent from Reviewable.io -->

2022-07-18 18:52 UTC, SanjayVas reviewed
> This PR depends on the additional open PRs #627. The file that contains the extra change is build/repositories.bzl, which can be ignored.

> You can base the the PR onto the set operation compiler branch instead of main to just show the changes relevant to this.

You shouldn't ever have other PR changes in your PR. You should stack your PRs to avoid this. This means that you need to either base #627 on #624 or vice-versa, and then base this on whichever of those PRs is based on the other. This will result in a stack of 3 PRs that each only show the changes that they add. Starting at the bottom of the stack, each PR should be merged into `main` individually.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630#-:-N7Hcqcy057_3AHW9iOD:b-jfsyk)* status: 0 of 9 files reviewed, all discussions resolved (waiting on @renjiezh)



<!-- Sent from Reviewable.io -->

2022-07-18 19:04 UTC, riemanli reviewed
#627 is a dependency version update and was created during the development of this PR and #624. Are you suggesting to rebase #624 onto #627 and then rebase this PR onto #624?

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630#-:-N7HfLgMAZzDKu6vLz5t:b-4yyiev)* status: 0 of 9 files reviewed, all discussions resolved (waiting on @renjiezh)



<!-- Sent from Reviewable.io -->

2022-07-18 19:58 UTC, SanjayVas reviewed
Yes

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630#-:-N7Hstub-gJVSED2kHMt:b2nhswy)* status: 0 of 9 files reviewed, all discussions resolved (waiting on @renjiezh and @tristanvuong2021)



<!-- Sent from Reviewable.io -->

2022-07-18 19:59 UTC, SanjayVas reviewed
Or just get one of those two merged first before indicating that this is ready for review.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630#-:-N7Ht1oB8WhbIrGKMtou:b-wc51se)* status: 0 of 9 files reviewed, all discussions resolved (waiting on @renjiezh and @tristanvuong2021)



<!-- Sent from Reviewable.io -->

2022-07-18 22:10 UTC, riemanli reviewed
Right that's what I was trying to do. 

During the discussion, #627 is merged to the main. This PR is now compared to the latest #624 and doesn't have unrelated changes.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630#-:-N7ILlX64e5ZT8KvQF85:b-inn37v)* status: 0 of 9 files reviewed, all discussions resolved (waiting on @renjiezh and @tristanvuong2021)



<!-- Sent from Reviewable.io -->

2022-07-18 22:44 UTC, SanjayVas requested changes
> Reviewed 1 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630)* status: 1 of 9 files reviewed, 1 unresolved discussion (waiting on @renjiezh, @riemanli, and @tristanvuong2021)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630#-N7IToII2Xz53rlwpCVv:-N7IToII2Xz53rlwpCVw:b-vnim94) (no related file):*
Left one comment, but going to wait until others do an initial pass.

___
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt` line 249 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630#-N7ITIoz87KaB8nA65oU:-N7ITIoz87KaB8nA65oV:b-u06m6z) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d82b9e4b7ddd084dbd6f32813dd9c94243581d4d/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt#L249)):*
> ```Kotlin
>   private val apiAuthenticationKey: String,
> ) : ReportsCoroutineImplBase() {
>   private val secureRandom = SecureRandom.getInstance("SHA1PRNG")
> ```

Don't specify a specific algorithm. Just use the default ctor.



_Suggestion:_
```Kotlin
SecureRandom()
```


<!-- Sent from Reviewable.io -->

2022-07-18 23:24 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630)* status: 1 of 9 files reviewed, 1 unresolved discussion (waiting on @renjiezh, @SanjayVas, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt` line 249 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630#-N7ITIoz87KaB8nA65oU:-N7Ic8H26dHyZr9JJmyU:b-xu0uci) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d82b9e4b7ddd084dbd6f32813dd9c94243581d4d/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt#L249)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Don't specify a specific algorithm. Just use the default ctor.
</blockquote></details>

Thanks for the suggestion. Done.


<!-- Sent from Reviewable.io -->

2022-07-19 18:05 UTC, renjiezh submitted a review, later dismissed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630)* status: 1 of 9 files reviewed, 2 unresolved discussions (waiting on @riemanli, @SanjayVas, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt` line 223 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630#-N7MVKWp9o5Yz_MPov4-:-N7MVKWp9o5Yz_MPov40:b-7uu9zy) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/01a7eae113abe0e10a036a91bf593fe7dd5b7dab/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt#L223)):*
> ```Kotlin
> private const val DIFFERENTIAL_PRIVACY_DETLA = 1e-12
> 
> data class ServiceStubs(
> ```

Can we make this private as well as Credential?


<!-- Sent from Reviewable.io -->

2022-07-19 22:52 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630)* status: 1 of 9 files reviewed, 2 unresolved discussions (waiting on @renjiezh, @SanjayVas, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt` line 223 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630#-N7MVKWp9o5Yz_MPov4-:-N7NeD4L3sJf5rdlSv9U:bekme9g) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/01a7eae113abe0e10a036a91bf593fe7dd5b7dab/src/main/kotlin/org/wfanet/measurement/reporting/service/api.v1alpha/ReportsService.kt#L223)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

Can we make this private as well as Credential?
</blockquote></details>

Sure, but just wondering if there is any particular reason for that.


<!-- Sent from Reviewable.io -->

2022-07-20 23:57 UTC, SanjayVas requested changes
> Reviewed 2 of 9 files at r1, 2 of 6 files at r7, 1 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630)* status: 5 of 11 files reviewed, 17 unresolved discussions (waiting on @renjiezh, @riemanli, @SanjayVas, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 111 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630#-N7SQe3v8MJUVx6jJ0KA:-N7SQe3v8MJUVx6jJ0KB:b-i7jc3u) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/65b4478f0d60b20e74173c3b5ad6ef68700f47f4/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L111)):*
> ```Kotlin
> import org.wfanet.measurement.internal.reporting.Metric.SetOperation.Operand as InternalOperand
> import org.wfanet.measurement.internal.reporting.Metric.WatchDurationParams as InternalWatchDurationParams
> import org.wfanet.measurement.internal.reporting.MetricKt.MeasurementCalculationKt.weightedMeasurement as internalWeightedMeasurement
> ```

Does this not trigger https://youtrack.jetbrains.com/issue/KTIJ-16471 and break your IntelliJ code completion?
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 183 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630#-N7SR6AX9n-GzTAh_LwF:-N7SR6AX9n-GzTAh_LwG:bn0jf6m) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/65b4478f0d60b20e74173c3b5ad6ef68700f47f4/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L183)):*
> ```Kotlin
> private const val MAX_PAGE_SIZE = 1000
> 
> private const val REACH_ONLY_VID_SAMPLING_WIDTH = 3.0f / 300.0f
> ```

Is there a reason we want to use single floating point precision explicitly here rather than the default double precision?



_Code quote:_
```Kotlin
3.0f
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 234 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630#-N7SRafR9E7WEhlYCT25:-N7SRafR9E7WEhlYCT26:b-yxfegg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/65b4478f0d60b20e74173c3b5ad6ef68700f47f4/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L234)):*
> ```Kotlin
> )
> 
> private data class Credential(
> ```

This doesn't seem like the right name for this. Of these fields, the only one that's a credential is the API auth key.



_Code quote:_
```Kotlin
Credential
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 258 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630#-N7SS8CW1pxTVLOInvcd:-N7SS8CXCPcSDuKwlwBR:bw5wb97) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/65b4478f0d60b20e74173c3b5ad6ef68700f47f4/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L258)):*
> ```Kotlin
>   private val secureRandom: SecureRandom,
> ) : ReportsCoroutineImplBase() {
>   private val serviceStubs =
> ```

Why not just take in the `ServiceStubs` as an argument to reduce the number of constructor args? I'd commend making `ServiceStubs` a public data class inside of `ReportingService`.

That said, I'm not certain why you'd otherwise want a `ServiceStubs` class if not for the purpose of reducing args. It's not something you should be passing around. If you were to keep it, I'd in fact make it a regular constructor arg and not a property, and instead destruct it into the individual private properties.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 270 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630#-N7SShU63eBGpVrvDUgG:-N7SShU63eBGpVrvDUgH:bolpjmn) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/65b4478f0d60b20e74173c3b5ad6ef68700f47f4/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L270)):*
> ```Kotlin
> 
>   override suspend fun createReport(request: CreateReportRequest): Report {
>     val principal = principalFromCurrentContext
> ```

nit: specify types explicitly except where it's obvious
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 496 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630#-N7Snnr-8PaBE6OorZOu:-N7Snnr-8PaBE6OorZOv:b9gmktc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/65b4478f0d60b20e74173c3b5ad6ef68700f47f4/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L496)):*
> ```Kotlin
> 
>   /** Gets a [SetInternalMeasurementResultRequest]. */
>   private suspend fun getSetInternalMeasurementResultRequest(
> ```

Maybe `build`? `get` implies you're retrieving one from somewhere.



_Code quote:_
```Kotlin
get
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 537 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630#-N7SmGsgEOaZxWdYZXfV:-N7SmGsgEOaZxWdYZXfW:b-r7iku7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/65b4478f0d60b20e74173c3b5ad6ef68700f47f4/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L537)):*
> ```Kotlin
> 
> /** Converts a public [CreateReportRequest] to an [InternalCreateReportRequest]. */
> private suspend fun CreateReportRequest.toInternal(
> ```

A conversion extension method isn't generally expected to go make RPCs. You should do all of the RPCs and checks that you need first, and have this method be a simple non-suspending conversion from one proto to another (potentially passing any supporting data you need).

I feel like I made a similar comment on another PR.



_Code quote:_
```Kotlin
toInternal
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 609 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630#-N7Sr5PjEEpSSN6b5-NE:-N7Sr5PjEEpSSN6b5-NF:b8l8hvk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/65b4478f0d60b20e74173c3b5ad6ef68700f47f4/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L609)):*
> ```Kotlin
> }
> 
> /** Check if the display names of the set operations within the same metric are unique. */
> ```

This doesn't appear to be checking within the same metric, but rather across metrics of the same type. My sequence example below assumes that you mean the latter.



_Code quote:_
```Kotlin
same metric
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 614 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630#-N7SoKgV7AOGvO5mRHpX:-N7SoKgV7AOGvO5mRHpY:boxxuwi) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/65b4478f0d60b20e74173c3b5ad6ef68700f47f4/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L614)):*
> ```Kotlin
>     mutableMapOf<MetricTypeCase, MutableSet<String>>().withDefault { mutableSetOf() }
> 
>   for (metric in metricsList) {
> ```

This is a case where a [Sequence](https://kotlinlang.org/docs/sequences.html) would probably make things easier to read.

```kotlin
val seenDisplayNames = // init your map

metricList.asSequence().flatMap { metric ->
  metric.setOperationsList.asSequence().map {
    // Code that r [...]

2022-07-21 17:29 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630)* status: 3 of 11 files reviewed, 17 unresolved discussions (waiting on @renjiezh, @riemanli, @SanjayVas, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 111 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630#-N7SQe3v8MJUVx6jJ0KA:-N7T3OSD3DXE4NLHdHzJ:b2khxnv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/65b4478f0d60b20e74173c3b5ad6ef68700f47f4/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L111)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Does this not trigger https://youtrack.jetbrains.com/issue/KTIJ-16471 and break your IntelliJ code completion?
</blockquote></details>

Hmm interesting. I didn't get that on my end. 
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 183 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630#-N7SR6AX9n-GzTAh_LwF:-N7T40IM1zg5ZqAPEFR7:b-969nm6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/65b4478f0d60b20e74173c3b5ad6ef68700f47f4/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L183)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Is there a reason we want to use single floating point precision explicitly here rather than the default double precision?
</blockquote></details>

I use Float here because `width` in `VidSamplingInterval` is a Float too.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 258 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630#-N7SS8CW1pxTVLOInvcd:-N7T4k9Y6InBuVNU2mc8:b-zesgat) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/65b4478f0d60b20e74173c3b5ad6ef68700f47f4/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L258)):*
I was having `serviceStubs` as the constructor argument and property but then change my mind. Looks like my first instinct is correct :stuck_out_tongue: 

> It's not something you should be passing around. If you were to keep it, I'd in fact make it a regular constructor arg and not a property, and instead destruct it into the individual private properties.

Sorry I am confused. The main reason to have `ServiceStubs` is to reduce the number of arguments of the functions using stubs. If I understand correctly, the above suggested the opposite way which is passing individual stubs around. Is that right?
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 270 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630#-N7SShU63eBGpVrvDUgG:-N7T8tF8BN-hL0BNZ-c8:b-yge9yw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/65b4478f0d60b20e74173c3b5ad6ef68700f47f4/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L270)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: specify types explicitly except where it's obvious
</blockquote></details>

Would you mind providing an example of specifying types for `principalFromCurrentContext`? I don't see anywhere does it. 
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 496 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630#-N7Snnr-8PaBE6OorZOu:-N7TATEX84xiR1jU-cku:bocayv9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/65b4478f0d60b20e74173c3b5ad6ef68700f47f4/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L496)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Maybe `build`? `get` implies you're retrieving one from somewhere.
</blockquote></details>

Great suggestion!
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 609 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630#-N7Sr5PjEEpSSN6b5-NE:-N7TDy-75ygcSzYjtFLB:bf1jr7q) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/65b4478f0d60b20e74173c3b5ad6ef68700f47f4/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L609)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This doesn't appear to be checking within the same metric, but rather across metrics of the same type. My sequence example below assumes that you mean the latter.
</blockquote></details>

You're right. It's for the same metric type. Good catch!
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 872 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630#-N7SzVgr-lhkmXXs3dLN:-N7UQQmR6J4pmjjzs9zr:b-jkgjy9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/65b4478f0d60b20e74173c3b5ad6ef68700f47f4/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L872)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Check for `NOT_FOUND` status code.
</blockquote></details>

Thanks for catching this! Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 961 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630#-N7T-gtm2qblQ0vVJJDD:-N7UQmdvAGn9x_-YTG1X:bvxhq64) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/65b4478f0d60b20e74173c3b5ad6ef68700f47f4/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L961)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Having this many args is a code smell.

The first of these appear to be members of the ReportsService class. Why isn't this just an instance method of that class?
</blockquote></details>

This is the dilemma I have been facing and thinking a lot. On one hand, making the function to be a member method can reduce the number of arguments. On the other hand, as this method is a downstream call, making it a member method means all its upstream methods have to be member methods as well, which I am not sure if it's appropriate.

Would love to have your thought.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 1170 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630#-N7T0Frw9XRxe7GGuTbl:-N7UStQhDXZYGcMjvvcs:buz6uxy) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/65b4478f0d60b20e74173c3b5ad6ef68700f47f4/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L1170)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This is built entirely from constants. Shouldn't it just be a constant itself?
</blockquote></details>

I made it in case it will have arguments in the future like the other metrics, but now I think making it a constant variable makes more sense and is also more "YAGNI".

Done.
___
*[`src/main/proto/wfa/measurement/reporting/v1alpha/metric.proto` line 111 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-med [...]

2022-07-21 18:28 UTC, riemanli commented
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 614 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630#-N7SoKgV7AOGvO5mRHpX:-N7WzHVdDqRajd0QJWIb:b-5b2wxg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/65b4478f0d60b20e74173c3b5ad6ef68700f47f4/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L614)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This is a case where a [Sequence](https://kotlinlang.org/docs/sequences.html) would probably make things easier to read.

```kotlin
val seenDisplayNames = // init your map

metricList.asSequence().flatMap { metric ->
  metric.setOperationsList.asSequence().map {
    // Code that results in a pair of metric type to display name
  }  
}.forEach { (metricType, displayName) ->
  // if display name has been seen for metric type, throw error
  // else add to seenDisplayNames
}
```
</blockquote></details>

I just realized I can just use `metric.metricTypeCase` as the key... Would this be better? Or the `Sequence` one is still preferred?

```kotlin
for (metric in metricsList) {
    for (setOperation in metric.setOperationsList) {
      grpcRequire(
        !seenDisplayNames.getValue(metric.metricTypeCase).contains(setOperation.displayName)
      ) { "The display names of the set operations within the same metric type should be unique." }
      seenDisplayNames.getOrPut(metric.metricTypeCase, ::mutableSetOf) += setOperation.displayName
    }
  }
```


<!-- Sent from Reviewable.io -->

2022-07-21 19:16 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630)* status: 2 of 11 files reviewed, 17 unresolved discussions (waiting on @renjiezh, @SanjayVas, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 234 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630#-N7SRafR9E7WEhlYCT25:-N7X4_O61d8zreD-Pcon:b-j97x1w) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/65b4478f0d60b20e74173c3b5ad6ef68700f47f4/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L234)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This doesn't seem like the right name for this. Of these fields, the only one that's a credential is the API auth key.
</blockquote></details>

Based on the offline discussion, the conversion extension methods will be refactored to ordinary member methods of `ReportsService`. In this way, many properties in this data class will be accessible, and thus `Credential` is not needed. Will remove it.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 258 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630#-N7SS8CW1pxTVLOInvcd:-N7X9anaCjFTTE_xJ8QY:bojl6fl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/65b4478f0d60b20e74173c3b5ad6ef68700f47f4/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L258)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

I was having `serviceStubs` as the constructor argument and property but then change my mind. Looks like my first instinct is correct :stuck_out_tongue: 

> It's not something you should be passing around. If you were to keep it, I'd in fact make it a regular constructor arg and not a property, and instead destruct it into the individual private properties.

Sorry I am confused. The main reason to have `ServiceStubs` is to reduce the number of arguments of the functions using stubs. If I understand correctly, the above suggested the opposite way which is passing individual stubs around. Is that right?
</blockquote></details>

Based on the offline discussion, the conversion extension methods will be refactored to ordinary member methods of `ReportsService`. In this way, many properties in this data class will be accessible, and thus `ServiceStubs ` is not needed. Will remove it.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 537 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630#-N7SmGsgEOaZxWdYZXfV:-N7X9kn1CRmJG4esprCK:b-4z86zd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/65b4478f0d60b20e74173c3b5ad6ef68700f47f4/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L537)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

A conversion extension method isn't generally expected to go make RPCs. You should do all of the RPCs and checks that you need first, and have this method be a simple non-suspending conversion from one proto to another (potentially passing any supporting data you need).

I feel like I made a similar comment on another PR.
</blockquote></details>

Based on the offline discussion, the conversion extension methods will be refactored to ordinary member methods of `ReportsService`. 
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 671 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630#-N7SvQoyAA5fgX6-E6jx:-N7WneIh2s479ULRDblA:b-hn62oz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/65b4478f0d60b20e74173c3b5ad6ef68700f47f4/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L671)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: drop the `to` on anything that's not actually converting a thing whole, but just collecting some transformed property.

A heuristic for when it's actually a conversion is if you could theoretically convert back to the original type with minimal data loss.

That said, the extensions being called from here don't appear to be used anywhere else and also appear to be just for mapping. You can therefore drop them and save on constructing the intermediate lists.

```kotlin
namedSetOperationsList.asSequence().flatMap { namedSetOperation ->
  namedSetOperation.measurementCalculationsList.asSequence().flatMap { measurementCalculation ->
    measurementCalculation.weightedMeasurementsList.asSequence().map { it.measurementReferenceId }
  }
}.map { measurementConsumerReferenceId -> 
  internalMeasurementKey {
    this.measurementConsumerReferenceId = measurementConsumerReferenceId
    this.measurementReferenceId = measurementReferenceId
  }
}.toList()
```
</blockquote></details>

Thanks for sharing this concept! I always found the boundary blurry when decoupling code to several functions. This concept is really helpful to distinguish the need of a conversion method.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 865 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630#-N7Szs2h7a8suqaMQi28:-N7XA4XRB9UGenUaO2h9:b-45rr5a) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/65b4478f0d60b20e74173c3b5ad6ef68700f47f4/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L865)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Once again, this kind of logic should definitely not be hidden in a conversion method. These should only contain trivial mapping, such that one could easily assume how it's written without having to inspect the method.
</blockquote></details>

Understood. The conversion extension methods will be refactored to ordinary member methods of `ReportsService`. 
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 961 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630#-N7T-gtm2qblQ0vVJJDD:-N7XAGESE6uKUNYtGk5U:bgbxx0q) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/65b4478f0d60b20e74173c3b5ad6ef68700f47f4/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L961)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

This is the dilemma I have been facing and thinking a lot. On one hand, making the function to be a member method can reduce the number of arguments. On the other hand, as this method is a downstream call, making it a member method means all its upstream methods have to be member methods as well, which I am not sure if it's appropriate.

Would love to have your thought.
</blockquote></details>

Based on the offline discussion, the conversion extension methods will be refactored to ordinary member methods of `ReportsService`.  In addition, move the creation of `dataProviderNameToInternalEventGroupEntriesList` outside this function and make it an argument.


<!-- Sent from Reviewable.io -->

2022-07-21 19:40 UTC, SanjayVas requested changes
> Reviewed 1 of 3 files at r10, 2 of 3 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630)* status: 5 of 11 files reviewed, 14 unresolved discussions (waiting on @renjiezh, @riemanli, @SanjayVas, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 68 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630#-N7XBGeX-gQuTRSOAF8e:-N7XBGeX-gQuTRSOAF8f:b-7wl5iu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/65b4478f0d60b20e74173c3b5ad6ef68700f47f4/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L68)):*
> ```Kotlin
> import org.wfanet.measurement.api.v2alpha.measurement
> import org.wfanet.measurement.api.v2alpha.measurementSpec
> import org.wfanet.measurement.api.v2alpha.principalFromCurrentContext
> ```

This is incorrect. It's assuming the principal interceptor from the CMMS public API, which has a different set of principals.

The only valid principal for this API is a measurement consumer. Since the ID comes from a different API, your principal should probably just contain the MC ID from the CMMS API rather than a resource name.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 111 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630#-N7SQe3v8MJUVx6jJ0KA:-N7X-4BS3oqdFI6lpkkA:b-k6tbev) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/65b4478f0d60b20e74173c3b5ad6ef68700f47f4/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L111)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Hmm interesting. I didn't get that on my end. 
</blockquote></details>

Hmm, maybe the bug is fixed then.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 183 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630#-N7SR6AX9n-GzTAh_LwF:-N7X07Jg2xTo4ZF8QEng:b-7m30zn) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/65b4478f0d60b20e74173c3b5ad6ef68700f47f4/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L183)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

I use Float here because `width` in `VidSamplingInterval` is a Float too.
</blockquote></details>

Sorry, what I meant was that even if `REACH_ONLY_VID_SAMPLING_WIDTH` is a Float, you need not use Floats for the operands.

e.g. `private const val REACH_ONLY_VID_SAMPLING_WIDTH: Float = (3.0 / 300.0).toFloat()`

That said, what you have is actually totally fine in this case as your operands are literals so you know that the operation will give the same result on Floats as on Doubles. You could in fact write this as `private const val REACH_ONLY_VID_SAMPLING_WIDTH = 0.01f`, or perhaps extract a constant for the denominator since I assume it has some meaning.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 234 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630#-N7SRafR9E7WEhlYCT25:-N7X92NjC6ag2NhQ2-cX:bxddm4s) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/65b4478f0d60b20e74173c3b5ad6ef68700f47f4/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L234)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This doesn't seem like the right name for this. Of these fields, the only one that's a credential is the API auth key.
</blockquote></details>

To clarify, if you have a hard time naming something like this because there are too many unrelated fields, it's a good indicator that they don't belong together.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 258 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630#-N7SS8CW1pxTVLOInvcd:-N7X8fiFB3HVrs3FrN6M:blok4oz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/65b4478f0d60b20e74173c3b5ad6ef68700f47f4/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L258)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

I was having `serviceStubs` as the constructor argument and property but then change my mind. Looks like my first instinct is correct :stuck_out_tongue: 

> It's not something you should be passing around. If you were to keep it, I'd in fact make it a regular constructor arg and not a property, and instead destruct it into the individual private properties.

Sorry I am confused. The main reason to have `ServiceStubs` is to reduce the number of arguments of the functions using stubs. If I understand correctly, the above suggested the opposite way which is passing individual stubs around. Is that right?
</blockquote></details>

If you follow my suggestion for other functions you pass this to, they will all become instance methods of the class and therefore not need this passed to them.

Combining things into a logical object is normally a way to reduce the number of arguments passed to a function. Most functions should cap out at ~4 arguments. The exception is constructors for dependency-injected classes.

With those above two points combined, you'd likely find that this ServiceStubs class need not exist.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 270 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630#-N7SShU63eBGpVrvDUgG:-N7XB5tnC1iEKWvKUzGf:bt8gp9v) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/65b4478f0d60b20e74173c3b5ad6ef68700f47f4/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L270)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Would you mind providing an example of specifying types for `principalFromCurrentContext`? I don't see anywhere does it. 
</blockquote></details>

The type is `Principal<*>`. That said, I realized this is using the CMMS v2alpha Principal. There should be a separate Principal type for this API.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 614 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630#-N7SoKgV7AOGvO5mRHpX:-N7XCMl4-Am2-KVIRPme:b-lznbyy) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/65b4478f0d60b20e74173c3b5ad6ef68700f47f4/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L614)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

I just realized I can just use `metric.metricTypeCase` as the key... Would this be better? Or the `Sequence` one is still preferred?

```kotlin
for (metric in metricsList) {
    for (setOperation in metric.setOperationsList) {
      grpcRequire(
        !seenDisplayNames.getValue(metric.metricTypeCase).contains(setOperation.displayName)
      ) { "The display names of the set operations within the same metric type should be unique." }
      seenDisplayNames.getOrPut(metric.metricTypeCase, ::mutableSetOf) += setOperation.displayName
    }
  }
```
</blockquote></details>

Your suggestion LGTM.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 906 at r11](https://reviewable.io/reviews/world-federation-of-adver [...]

2022-07-21 22:21 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630)* status: 2 of 12 files reviewed, 13 unresolved discussions (waiting on @renjiezh, @SanjayVas, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 68 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630#-N7XBGeX-gQuTRSOAF8e:-N7XcRXbC6QZOxndNTyX:b-y9t1k9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/65b4478f0d60b20e74173c3b5ad6ef68700f47f4/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L68)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This is incorrect. It's assuming the principal interceptor from the CMMS public API, which has a different set of principals.

The only valid principal for this API is a measurement consumer. Since the ID comes from a different API, your principal should probably just contain the MC ID from the CMMS API rather than a resource name.
</blockquote></details>

Thanks for catching that. Would you please confirm the following points?

1. By reading the code in `Principal.kt` and `PrincipalServerInterceptor.kt` in CMM public API, I think what I am going to do is copying them but only keep the measurement consumer part and create the `MeasurementConsumerKey` with `MeasurementConsumerId`.

2. In addition, as you pointed out `Principal`, I want to check if it's okay to use `MeasurementConsumerKey` from CMM public API.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 183 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630#-N7SR6AX9n-GzTAh_LwF:-N7XnuQa6Scz4zP-gk1p:bea5h1o) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/65b4478f0d60b20e74173c3b5ad6ef68700f47f4/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L183)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Sorry, what I meant was that even if `REACH_ONLY_VID_SAMPLING_WIDTH` is a Float, you need not use Floats for the operands.

e.g. `private const val REACH_ONLY_VID_SAMPLING_WIDTH: Float = (3.0 / 300.0).toFloat()`

That said, what you have is actually totally fine in this case as your operands are literals so you know that the operation will give the same result on Floats as on Doubles. You could in fact write this as `private const val REACH_ONLY_VID_SAMPLING_WIDTH = 0.01f`, or perhaps extract a constant for the denominator since I assume it has some meaning.
</blockquote></details>

That's a good point. I made the denominator a constant variable.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 234 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630#-N7SRafR9E7WEhlYCT25:-N7XpAyS3ccBqW1sATUH:b-uv4ta) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/65b4478f0d60b20e74173c3b5ad6ef68700f47f4/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L234)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

To clarify, if you have a hard time naming something like this because there are too many unrelated fields, it's a good indicator that they don't belong together.
</blockquote></details>

Thanks for the clarification.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 270 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630#-N7SShU63eBGpVrvDUgG:-N7XpUAoB87hag2gY26L:bmtjda1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/65b4478f0d60b20e74173c3b5ad6ef68700f47f4/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L270)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The type is `Principal<*>`. That said, I realized this is using the CMMS v2alpha Principal. There should be a separate Principal type for this API.
</blockquote></details>

Thanks for the example. Please see my response to having a new Principal for this API in other thread.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 614 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630#-N7SoKgV7AOGvO5mRHpX:-N7XV6b61tJi6-3JRVrJ:b-896fja) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/65b4478f0d60b20e74173c3b5ad6ef68700f47f4/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L614)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Your suggestion LGTM.
</blockquote></details>

Done!
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 906 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630#-N7XElIp80oQmR0wKHTu:-N7XXGUuE_Tzzdzqj7ns:b-2lkylg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8bf72880413c02431dd46863c446a1ed59c72fe4/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L906)):*
> throw a wrapped non-status exception

Do you mean like this?

```kotlin
throw Exception(exceptionMessage)
```

> Note that this also means that you must catch all StatusExceptions thrown by other RPCs to prevent them from being surfaced as if they came from this service.

Does that mean all RPCs should be accompanied by `try-catch`?
___
*[`src/main/proto/wfa/measurement/reporting/v1alpha/metric.proto` line 111 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630#-N7T0_cqCV-xRO7v0S-7:-N7Xa19N8rDBZHcBWx41:b44j3et) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/65b4478f0d60b20e74173c3b5ad6ef68700f47f4/src/main/proto/wfa/measurement/reporting/v1alpha/metric.proto#L111)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

SG. Just make sure to update the documentation to better reflect the name. e.g.

```protobuf
// Unique name for `set_operation` across all `Metric`s of the same type in this `Report`.
```
</blockquote></details>

Should we also change the `display_name` in the internal `NamedSetOperation`?  That one isn't really used to generate measurement reference ID or any other purpose, so it doesn't violate https://google.aip.dev/140#display-names. So, it depends on whether we want the field name to be consistent.


<!-- Sent from Reviewable.io -->

2022-07-21 23:15 UTC, SanjayVas requested changes
> Reviewed 2 of 5 files at r12, 1 of 1 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630)* status: 5 of 12 files reviewed, 11 unresolved discussions (waiting on @renjiezh, @riemanli, @SanjayVas, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 68 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630#-N7XBGeX-gQuTRSOAF8e:-N7Y-J8_CM90LdUKQQJd:b-262s2y) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/65b4478f0d60b20e74173c3b5ad6ef68700f47f4/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L68)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Thanks for catching that. Would you please confirm the following points?

1. By reading the code in `Principal.kt` and `PrincipalServerInterceptor.kt` in CMM public API, I think what I am going to do is copying them but only keep the measurement consumer part and create the `MeasurementConsumerKey` with `MeasurementConsumerId`.

2. In addition, as you pointed out `Principal`, I want to check if it's okay to use `MeasurementConsumerKey` from CMM public API.
</blockquote></details>

1. That's alright, since much of it isn't of use to this API. Note that you can probably also use a different non-generic principal type given that the only type of principal you can have currently is an MC.

2. Using `MeasurementConsumerKey` is fine, since you're using it to interact with that API.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 906 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630#-N7XElIp80oQmR0wKHTu:-N7Y1XImEaDmh-MN9_24:bo1xbja) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8bf72880413c02431dd46863c446a1ed59c72fe4/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L906)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

> throw a wrapped non-status exception

Do you mean like this?

```kotlin
throw Exception(exceptionMessage)
```

> Note that this also means that you must catch all StatusExceptions thrown by other RPCs to prevent them from being surfaced as if they came from this service.

Does that mean all RPCs should be accompanied by `try-catch`?
</blockquote></details>

Yes to both.
___
*[`src/main/proto/wfa/measurement/reporting/v1alpha/metric.proto` line 111 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630#-N7T0_cqCV-xRO7v0S-7:-N7Y1eS25uH7oYU3zZh2:bvjglbd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/65b4478f0d60b20e74173c3b5ad6ef68700f47f4/src/main/proto/wfa/measurement/reporting/v1alpha/metric.proto#L111)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Should we also change the `display_name` in the internal `NamedSetOperation`?  That one isn't really used to generate measurement reference ID or any other purpose, so it doesn't violate https://google.aip.dev/140#display-names. So, it depends on whether we want the field name to be consistent.
</blockquote></details>

Not a high priority, but it wouldn't be a bad idea.


<!-- Sent from Reviewable.io -->

2022-07-22 08:24 UTC, riemanli reviewed
@sanjayvas I refactored the code as discussed. I ended up still have a data class `ReportDetails` to wrap some report-related info to reduce the number of function args. Please take a look. Thanks.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630#-:-N7ZwEx20pJ9xiouXhTw:b-e5z5o1)* status: 3 of 16 files reviewed, 11 unresolved discussions (waiting on @renjiezh, @riemanli, @SanjayVas, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 234 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630#-N7SRafR9E7WEhlYCT25:-N7Zvcio3lRUBEYvZ4L-:b-7krt9c) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/65b4478f0d60b20e74173c3b5ad6ef68700f47f4/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L234)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Thanks for the clarification.
</blockquote></details>

Removed `Credential`.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 258 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630#-N7SS8CW1pxTVLOInvcd:-N7Zvki66jq_tldFQrd-:bkxc6mx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/65b4478f0d60b20e74173c3b5ad6ef68700f47f4/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L258)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

If you follow my suggestion for other functions you pass this to, they will all become instance methods of the class and therefore not need this passed to them.

Combining things into a logical object is normally a way to reduce the number of arguments passed to a function. Most functions should cap out at ~4 arguments. The exception is constructors for dependency-injected classes.

With those above two points combined, you'd likely find that this ServiceStubs class need not exist.
</blockquote></details>

Removed `ServiceStubs`.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 537 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630#-N7SmGsgEOaZxWdYZXfV:-N7Zvtq3DAM9MwMw2O8P:byg433c) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/65b4478f0d60b20e74173c3b5ad6ef68700f47f4/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L537)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Based on the offline discussion, the conversion extension methods will be refactored to ordinary member methods of `ReportsService`. 
</blockquote></details>

Refactored.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 671 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630#-N7SvQoyAA5fgX6-E6jx:-N7XxxAEDuJ9KVI4E-n7:byg433c) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/65b4478f0d60b20e74173c3b5ad6ef68700f47f4/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L671)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Thanks for sharing this concept! I always found the boundary blurry when decoupling code to several functions. This concept is really helpful to distinguish the need of a conversion method.
</blockquote></details>

Refactored.



_Code quote:_
```Kotlin
toMeasurementReferenceIds()
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 865 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630#-N7Szs2h7a8suqaMQi28:-N7Zw-Vc3zFgr-5_SkgG:byg433c) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/65b4478f0d60b20e74173c3b5ad6ef68700f47f4/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L865)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Understood. The conversion extension methods will be refactored to ordinary member methods of `ReportsService`. 
</blockquote></details>

Refactored.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 961 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630#-N7T-gtm2qblQ0vVJJDD:-N7Zw2jT9baJLxaxxZQa:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/65b4478f0d60b20e74173c3b5ad6ef68700f47f4/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L961)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Based on the offline discussion, the conversion extension methods will be refactored to ordinary member methods of `ReportsService`.  In addition, move the creation of `dataProviderNameToInternalEventGroupEntriesList` outside this function and make it an argument.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 906 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630#-N7XElIp80oQmR0wKHTu:-N7Zx6db1gjrjPnOm1AD:b-vwi1y6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8bf72880413c02431dd46863c446a1ed59c72fe4/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L906)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Yes to both.
</blockquote></details>

For the second point, I wonder if this is reporting server specific I looked at some services and didn't see they do `try-catch` for RPCs.
___
*[`src/main/proto/wfa/measurement/reporting/v1alpha/metric.proto` line 111 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630#-N7T0_cqCV-xRO7v0S-7:-N7ZIswfDWr9DFJ-E-1s:bazszia) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/65b4478f0d60b20e74173c3b5ad6ef68700f47f4/src/main/proto/wfa/measurement/reporting/v1alpha/metric.proto#L111)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Not a high priority, but it wouldn't be a bad idea.
</blockquote></details>

Got it. 

Done. Only renamed the public one.

@tristanvuong2021 thought you might want to know as well.


<!-- Sent from Reviewable.io -->

2022-07-22 16:18 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630)* status: 3 of 16 files reviewed, 11 unresolved discussions (waiting on @renjiezh, @SanjayVas, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 68 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630#-N7XBGeX-gQuTRSOAF8e:-N7aeKciCyVZuVZGF5sp:bav2eay) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/65b4478f0d60b20e74173c3b5ad6ef68700f47f4/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L68)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

1. That's alright, since much of it isn't of use to this API. Note that you can probably also use a different non-generic principal type given that the only type of principal you can have currently is an MC.

2. Using `MeasurementConsumerKey` is fine, since you're using it to interact with that API.
</blockquote></details>

I wonder if this change should be in another PR.  The change affects not only `ReportsService` but also `ReportingSetsService` and `EventGroupsService`.


<!-- Sent from Reviewable.io -->

2022-07-22 20:32 UTC, SanjayVas requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630)* status: 3 of 16 files reviewed, 8 unresolved discussions (waiting on @renjiezh, @riemanli, @SanjayVas, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 68 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630#-N7XBGeX-gQuTRSOAF8e:-N7bT5092ZIBznxECuoi:bp6zcl3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/65b4478f0d60b20e74173c3b5ad6ef68700f47f4/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L68)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

I wonder if this change should be in another PR.  The change affects not only `ReportsService` but also `ReportingSetsService` and `EventGroupsService`.
</blockquote></details>

SG. Just leave a TODO.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 270 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630#-N7SShU63eBGpVrvDUgG:-N7bV6e74DOkg8XtsJ9a:b-wxecfe) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/65b4478f0d60b20e74173c3b5ad6ef68700f47f4/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L270)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Thanks for the example. Please see my response to having a new Principal for this API in other thread.
</blockquote></details>

FYI this isn't yet resolved as this comment was for specifying explicit types in general.

The general practice is to specify explicit types by default, optionally omitting them in cases where they are obvious (e.g. when assigning from a constructor or known factory function call).
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 906 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630#-N7XElIp80oQmR0wKHTu:-N7b_GQ04omFBb-yFKft:b7geclo) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8bf72880413c02431dd46863c446a1ed59c72fe4/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L906)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

For the second point, I wonder if this is reporting server specific I looked at some services and didn't see they do `try-catch` for RPCs.
</blockquote></details>

That's a bug in those service implementations then.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 260 at r17](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630#-N7bUQM1ALOgw00efuM8:-N7bUQM1ALOgw00efuM9:b5mgnft) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/141abfa0060bcf1bf77ac2849d5ad427f95b6018/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L260)):*
> ```Kotlin
>   private val setOperationCompiler = SetOperationCompiler()
> 
>   private data class ReportDetails(
> ```

nit: maybe a different name to avoid confusing with the internal `Report.Details`.



_Code quote:_
```Kotlin
Details
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 533 at r17](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630#-N7bXwpA-pzJGqRmZa8X:-N7bXwpA-pzJGqRmZa8Y:b4039cr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/141abfa0060bcf1bf77ac2849d5ad427f95b6018/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L533)):*
> ```Kotlin
>     val internalReport: InternalReport =
>       try {
>         internalReportsStub.getReportByIdempotencyKey(
> ```

I'm confused here. Why would we be doing this check inside a function that builds an internal Create request? If the internal report exists, we should just return that to the caller of `CreateReport` and not build an internal request at all. Therefore, the check for an existing report should be outside of this method.

I'd expect something like

```kotlin
val existingInternalReport: InternalReport? = try {
  getReportByIdempotencyKey(/* ... */)
} catch (e: StatusException) {
  if (e.status.code == Status.Code.NOT_FOUND) {
    null
  } else {
    throw Exception(/* message */, e)
  }
}

if (existingInternalReport != null) {
  return existingInternalReport.toReport()
}

// Build the internal create request and call internal create.
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 541 at r17](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630#-N7bXDUj1oAjl9CQqS80:-N7bXDUj1oAjl9CQqS81:bafcdde) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/141abfa0060bcf1bf77ac2849d5ad427f95b6018/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L541)):*
> ```Kotlin
>       } catch (e: StatusException) {
>         if (e.status.code != Status.Code.NOT_FOUND) {
>           throw Exception(
> ```

Pass `e` as the cause to the `Exception` constructor.


<!-- Sent from Reviewable.io -->

2022-07-22 22:32 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630)* status: 3 of 16 files reviewed, 7 unresolved discussions (waiting on @renjiezh, @riemanli, @SanjayVas, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 68 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630#-N7XBGeX-gQuTRSOAF8e:-N7bujL6DFGVd2VFIkZz:b-rls8wh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/65b4478f0d60b20e74173c3b5ad6ef68700f47f4/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L68)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

SG. Just leave a TODO.
</blockquote></details>

Great. Added a TODO.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 270 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630#-N7SShU63eBGpVrvDUgG:-N7buyT41hG8gwtT4Fr9:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/65b4478f0d60b20e74173c3b5ad6ef68700f47f4/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L270)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

FYI this isn't yet resolved as this comment was for specifying explicit types in general.

The general practice is to specify explicit types by default, optionally omitting them in cases where they are obvious (e.g. when assigning from a constructor or known factory function call).
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 260 at r17](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630#-N7bUQM1ALOgw00efuM8:-N7byYam1ZvGrhU12Bar:b-1jza1q) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/141abfa0060bcf1bf77ac2849d5ad427f95b6018/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L260)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: maybe a different name to avoid confusing with the internal `Report.Details`.
</blockquote></details>

How about `ReportAttributes`?
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 533 at r17](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630#-N7bXwpA-pzJGqRmZa8X:-N7bz3yJ4Fseo8YrisXv:b-bjudbj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/141abfa0060bcf1bf77ac2849d5ad427f95b6018/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L533)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I'm confused here. Why would we be doing this check inside a function that builds an internal Create request? If the internal report exists, we should just return that to the caller of `CreateReport` and not build an internal request at all. Therefore, the check for an existing report should be outside of this method.

I'd expect something like

```kotlin
val existingInternalReport: InternalReport? = try {
  getReportByIdempotencyKey(/* ... */)
} catch (e: StatusException) {
  if (e.status.code == Status.Code.NOT_FOUND) {
    null
  } else {
    throw Exception(/* message */, e)
  }
}

if (existingInternalReport != null) {
  return existingInternalReport.toReport()
}

// Build the internal create request and call internal create.
```
</blockquote></details>

Thanks for the suggestion! Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 541 at r17](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630#-N7bXDUj1oAjl9CQqS80:-N7by0A-32gSg6ABF8f7:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/141abfa0060bcf1bf77ac2849d5ad427f95b6018/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L541)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Pass `e` as the cause to the `Exception` constructor.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-22 23:52 UTC, SanjayVas requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630)* status: 3 of 16 files reviewed, 10 unresolved discussions (waiting on @renjiezh, @riemanli, @SanjayVas, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 260 at r17](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630#-N7bUQM1ALOgw00efuM8:-N7c3Wy6Dq2lvTkz_b1g:b2uildw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/141abfa0060bcf1bf77ac2849d5ad427f95b6018/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L260)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

How about `ReportAttributes`?
</blockquote></details>

Sure, or `ReportInfo` or `ParsedReport`. Whichever is fine.

Renaming a private data class is a cheap refactoring, so no need to ask me. Just do the renaming and I'll comment if there's something wrong with it.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 534 at r18](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630#-N7c4bIR1MvGmGuCeEnF:-N7c4bIR1MvGmGuCeEnG:b-j09kp1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ee2848ed3875a4308194529a09e028cc389684a8/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L534)):*
> ```Kotlin
>     encryptionPrivateKeyHandle: PrivateKeyHandle
>   ): Measurement.Result {
>     val certificate =
> ```

nit: Add a TODO to consider caching these, since I assume multiple results will likely use the same cert.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 571 at r18](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630#-N7c5OD31OxUDyHAHo7U:-N7c5OD31OxUDyHAHo7V:boioklq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ee2848ed3875a4308194529a09e028cc389684a8/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L571)):*
> ```Kotlin
> 
>       @Suppress("WHEN_ENUM_CAN_BE_NULL_IN_JAVA") // Proto enum fields are never null.
>       val timeIntervalsList: List<TimeInterval> =
> ```

This looks like a good candidate for a extracting a function.

```kotlin
private fun Report.internalTimeIntervals(): List<InternalTimeInterval>
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 587 at r18](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630#-N7c4vm12ypD_c4vZsIQ:-N7c4vm12ypD_c4vZsIR:by4nps) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ee2848ed3875a4308194529a09e028cc389684a8/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L587)):*
> ```Kotlin
>       coroutineScope {
>         for (metric in request.report.metricsList) {
>           val reportDetails =
> ```

Do this outside of the loop, since these should all be coming from the Report and not the Metric so you don't need to instantiate a new object every loop iteration.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 778 at r18](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630#-N7c9oIwC4Vb-Oo-DgpX:-N7c9oIwC4Vb-Oo-DgpY:b-w2i52x) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ee2848ed3875a4308194529a09e028cc389684a8/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L778)):*
> ```Kotlin
>   }
> 
>   /** Builds an [InternalWeightedMeasurement] from a public [WeightedMeasurement]. */
> ```

What's a public `WeightedMeasurement`? I don't see any message with that name in the public API.



_Code quote:_
```Kotlin
public [WeightedMeasurement]
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 779 at r18](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630#-N7c7rAuAvmB3Tnmj8u5:-N7c7rAuAvmB3Tnmj8u6:b-8wfx7q) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ee2848ed3875a4308194529a09e028cc389684a8/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L779)):*
> ```Kotlin
> 
>   /** Builds an [InternalWeightedMeasurement] from a public [WeightedMeasurement]. */
>   private suspend fun buildInternalWeightedMeasurement(
> ```

This isn't really building an `InternalWeightedMeasurement`. From what I can tell, it seems to be *creating* an internal Measurement and then wrapping that result in an `InternalWeightedMeasurement`.

None of these `build` methods should result in any internal mutations. That logic should be split out, or the methods should be renamed to be more clear as to what they are doing.

For context, I had assumed when you were going from conversion extensions to `build` methods, the RPCs you were doing were just fetches to "fatten" the result with information that's not directly available in the source.

To give my naive understanding, I'd expect CreateReport to go something like:
1. Check if a report exists with that idempotency key, return if so (syncing Measurements with CMMS API).
2. Run the compiler to determine the params for the measurements to create, including idempotency key
3. For each result from the compiler, check if the internal measurement exists.
    a. If not, create the measurement in CMMS API and insert an internal measurement
    b. Keep track of the internal measurement ID so we can associate it with the Report upon creation.
4. Create the internal report (including any other rows that depend on Report ID), in a single transaction (i.e. single call to internal service).
    a. This involves building an internal create report request, which we should be able to do with the info we saved in 3b.



_Code quote:_
```Kotlin
buildInternalWeightedMeasurement
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 787 at r18](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630#-N7c7PMl8YWisbx6-YWd:-N7c7PMl8YWisbx6-YWe:b6et1k) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ee2848ed3875a4308194529a09e028cc389684a8/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L787)):*
> ```Kotlin
>   ): InternalWeightedMeasurement {
>     try {
>       internalMeasurementsStub.getMeasurement(
> ```

This result doesn't seem to be used?


<!-- Sent from Reviewable.io -->

2022-07-23 01:32 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630)* status: 3 of 16 files reviewed, 8 unresolved discussions (waiting on @renjiezh, @riemanli, @SanjayVas, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 260 at r17](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630#-N7bUQM1ALOgw00efuM8:-N7cMS6y4Z8nw5f6Qk8w:b-kih9l6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/141abfa0060bcf1bf77ac2849d5ad427f95b6018/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L260)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Sure, or `ReportInfo` or `ParsedReport`. Whichever is fine.

Renaming a private data class is a cheap refactoring, so no need to ask me. Just do the renaming and I'll comment if there's something wrong with it.
</blockquote></details>

Got it. Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 534 at r18](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630#-N7c4bIR1MvGmGuCeEnF:-N7cNg8a36YRyLy7KwP7:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ee2848ed3875a4308194529a09e028cc389684a8/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L534)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: Add a TODO to consider caching these, since I assume multiple results will likely use the same cert.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 571 at r18](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630#-N7c5OD31OxUDyHAHo7U:-N7cPbRr5FUHYvHa3ufH:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ee2848ed3875a4308194529a09e028cc389684a8/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L571)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This looks like a good candidate for a extracting a function.

```kotlin
private fun Report.internalTimeIntervals(): List<InternalTimeInterval>
```
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 587 at r18](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630#-N7c4vm12ypD_c4vZsIQ:-N7cKdlp5hKZPfa3IXzN:byfu8qz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ee2848ed3875a4308194529a09e028cc389684a8/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L587)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Do this outside of the loop, since these should all be coming from the Report and not the Metric so you don't need to instantiate a new object every loop iteration.
</blockquote></details>

I put `reportInfo` in the loop intentionally as it will be changed in the downstream call `buildInternalMetric`. Note that `timeInterval` in `ReportInfo` is `var`.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 778 at r18](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630#-N7c9oIwC4Vb-Oo-DgpX:-N7cL4_M28BooDNz99kN:b-vc3a6r) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ee2848ed3875a4308194529a09e028cc389684a8/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L778)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

What's a public `WeightedMeasurement`? I don't see any message with that name in the public API.
</blockquote></details>

It's the data class defined in `SetOperationCompiler`. Removed "public" in the docstring.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 779 at r18](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630#-N7c7rAuAvmB3Tnmj8u5:-N7cRPb0C5NfMtf4rI-0:bdxypc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ee2848ed3875a4308194529a09e028cc389684a8/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L779)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This isn't really building an `InternalWeightedMeasurement`. From what I can tell, it seems to be *creating* an internal Measurement and then wrapping that result in an `InternalWeightedMeasurement`.

None of these `build` methods should result in any internal mutations. That logic should be split out, or the methods should be renamed to be more clear as to what they are doing.

For context, I had assumed when you were going from conversion extensions to `build` methods, the RPCs you were doing were just fetches to "fatten" the result with information that's not directly available in the source.

To give my naive understanding, I'd expect CreateReport to go something like:
1. Check if a report exists with that idempotency key, return if so (syncing Measurements with CMMS API).
2. Run the compiler to determine the params for the measurements to create, including idempotency key
3. For each result from the compiler, check if the internal measurement exists.
    a. If not, create the measurement in CMMS API and insert an internal measurement
    b. Keep track of the internal measurement ID so we can associate it with the Report upon creation.
4. Create the internal report (including any other rows that depend on Report ID), in a single transaction (i.e. single call to internal service).
    a. This involves building an internal create report request, which we should be able to do with the info we saved in 3b.
</blockquote></details>

That's not what we decided in the last discussion.  I think what you mentioned above is the other option during the discussion which will need to traverse the nested data structure several times. I understand your point, but it seems a lot of work to redesign and restructure the code. Could renaming the `build` methods suffice to solve the problem without changing the structure?
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 787 at r18](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630#-N7c7PMl8YWisbx6-YWd:-N7cLjIs1uZoCTJqpSrf:b-qcaagg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ee2848ed3875a4308194529a09e028cc389684a8/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L787)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This result doesn't seem to be used?
</blockquote></details>

No it's not used. This is how I check if there is an existing measurement in the reporting database, so it can avoid running the CMM `createMeasurement` and the internal `createMeasurement`.


<!-- Sent from Reviewable.io -->

2022-07-25 17:01 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630)* status: 3 of 16 files reviewed, 8 unresolved discussions (waiting on @renjiezh, @SanjayVas, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 906 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630#-N7XElIp80oQmR0wKHTu:-N7ijsGeBMCGkLPCJ0qH:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8bf72880413c02431dd46863c446a1ed59c72fe4/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L906)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

That's a bug in those service implementations then.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-25 17:34 UTC, SanjayVas requested changes
> Reviewed 1 of 7 files at r15, 1 of 2 files at r20, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630)* status: 5 of 16 files reviewed, 6 unresolved discussions (waiting on @renjiezh, @riemanli, @SanjayVas, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 587 at r18](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630#-N7c4vm12ypD_c4vZsIQ:-N7qDk6K8rofV0MAodFh:b-ypk2ff) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ee2848ed3875a4308194529a09e028cc389684a8/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L587)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

I put `reportInfo` in the loop intentionally as it will be changed in the downstream call `buildInternalMetric`. Note that `timeInterval` in `ReportInfo` is `var`.
</blockquote></details>

Immutability should be the default. If a function has a side effect in terms of mutating an argument, it should be very clear to the caller that the function does this. Often times, this should be the primary thing that the function does.

Make ReportInfo immutable. If you really need time intervals to be a mutable argument, pass it separately and clearly document how it's mutated.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 779 at r18](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630#-N7c7rAuAvmB3Tnmj8u5:-N7qHM7Z9jlZWQEak3da:b-14y5xd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ee2848ed3875a4308194529a09e028cc389684a8/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L779)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

That's not what we decided in the last discussion.  I think what you mentioned above is the other option during the discussion which will need to traverse the nested data structure several times. I understand your point, but it seems a lot of work to redesign and restructure the code. Could renaming the `build` methods suffice to solve the problem without changing the structure?
</blockquote></details>

My recommendation from the previous discussion was based upon the assumption that the RPCs you needed to make were just fetches to fatten the return value.

It's possible that renaming the methods may help, but the main thing is that that each function/method follows the [single-responsibility principle](https://en.wikipedia.org/wiki/Single-responsibility_principle). Hence why a `buildX` method should be expected only to build X and not also insert Y into the DB. If you find yourself being unable to figure out how to name a method that describes the one single thing it's doing, then it should probably not be a single method.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 787 at r18](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630#-N7c7PMl8YWisbx6-YWd:-N7qN54K0m21371eSwdF:b-kzk3hx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ee2848ed3875a4308194529a09e028cc389684a8/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L787)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

No it's not used. This is how I check if there is an existing measurement in the reporting database, so it can avoid running the CMM `createMeasurement` and the internal `createMeasurement`.
</blockquote></details>

This can definitely be rewritten to make that more clear, as well as reduce nesting (getting code outside of that catch block). In fact, we've used a similar pattern before.

```kotlin
fun getInternalMeasurement(measurementConsumerReferenceId: String, measurementReferenceId: String): InternalMeasurement? {
  try {
    return makeRpc()  // Fill in makeRpc
  } catch (e: StatusException) {
    if (e.status.code == Status.Code.NOT_FOUND) {
      return null
    }
    throw Exception(message, e)  // Fill in message
  }
}
```

```kotlin
val existingMeasurement: InternalMeasurement? = getInternalMeasurement(/* ... */)
if (existingMeasurement != null) {
  return someOtherThing
}

// Do whatever else you need to do
```


<!-- Sent from Reviewable.io -->

2022-07-26 17:00 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630)* status: 4 of 16 files reviewed, 4 unresolved discussions (waiting on @renjiezh, @SanjayVas, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 587 at r18](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630#-N7c4vm12ypD_c4vZsIQ:-N7tIab-CpO9n5dUOstZ:b-b7bs8m) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ee2848ed3875a4308194529a09e028cc389684a8/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L587)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Immutability should be the default. If a function has a side effect in terms of mutating an argument, it should be very clear to the caller that the function does this. Often times, this should be the primary thing that the function does.

Make ReportInfo immutable. If you really need time intervals to be a mutable argument, pass it separately and clearly document how it's mutated.
</blockquote></details>

Remove mutable `timeIntervalsList` from `ReportInfo`.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 779 at r18](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630#-N7c7rAuAvmB3Tnmj8u5:-N7tIXIhEXaPF-G5sEP5:b-mqh5jb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ee2848ed3875a4308194529a09e028cc389684a8/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L779)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

My recommendation from the previous discussion was based upon the assumption that the RPCs you needed to make were just fetches to fatten the return value.

It's possible that renaming the methods may help, but the main thing is that that each function/method follows the [single-responsibility principle](https://en.wikipedia.org/wiki/Single-responsibility_principle). Hence why a `buildX` method should be expected only to build X and not also insert Y into the DB. If you find yourself being unable to figure out how to name a method that describes the one single thing it's doing, then it should probably not be a single method.
</blockquote></details>

Modified based on the suggestion.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 787 at r18](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630#-N7c7PMl8YWisbx6-YWd:-N7r-gavDrS7PFC35QZj:b-xu0uci) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ee2848ed3875a4308194529a09e028cc389684a8/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L787)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This can definitely be rewritten to make that more clear, as well as reduce nesting (getting code outside of that catch block). In fact, we've used a similar pattern before.

```kotlin
fun getInternalMeasurement(measurementConsumerReferenceId: String, measurementReferenceId: String): InternalMeasurement? {
  try {
    return makeRpc()  // Fill in makeRpc
  } catch (e: StatusException) {
    if (e.status.code == Status.Code.NOT_FOUND) {
      return null
    }
    throw Exception(message, e)  // Fill in message
  }
}
```

```kotlin
val existingMeasurement: InternalMeasurement? = getInternalMeasurement(/* ... */)
if (existingMeasurement != null) {
  return someOtherThing
}

// Do whatever else you need to do
```
</blockquote></details>

Thanks for the suggestion. Done.


<!-- Sent from Reviewable.io -->

2022-07-26 18:13 UTC, SanjayVas requested changes
> Reviewed 1 of 3 files at r2, 1 of 3 files at r4, 2 of 6 files at r7, 3 of 7 files at r15, 1 of 2 files at r17, 4 of 4 files at r21.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630)* status: 15 of 16 files reviewed, 10 unresolved discussions (waiting on @renjiezh, @riemanli, @SanjayVas, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 779 at r18](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630#-N7c7rAuAvmB3Tnmj8u5:-N7vSS5O3o8Snf2gYkWu:b4fm3e) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ee2848ed3875a4308194529a09e028cc389684a8/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L779)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Modified based on the suggestion.
</blockquote></details>

Much clearer. Thanks!
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 1248 at r21](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630#-N7vSfis91o-kvVrsFn9:-N7vSfis91o-kvVrsFnA:b6kc8bg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d871f1c02e14d9426a7091c991931c6a16a51eb6/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L1248)):*
> ```Kotlin
>     }
> 
>     for (eventGroupKey in internalReportingSet.await().eventGroupKeysList) {
> ```

If you're going to immediately `await()` on it, there's no benefit to doing something in another coroutine scope and using `async`. Just go ahead and call the suspending code.
___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsServiceTest.kt` line 31 at r21](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630#-N7vZsiZ1MUdCqV8PgX_:-N7vZsiZ1MUdCqV8PgXa:b-7lr9o0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d871f1c02e14d9426a7091c991931c6a16a51eb6/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsServiceTest.kt#L31)):*
> ```Kotlin
> import kotlinx.coroutines.flow.flowOf
> import kotlinx.coroutines.runBlocking
> import org.junit.Assert.assertThrows
> ```

Use `assertFailsWith` from kotlin.test instead.
___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsServiceTest.kt` line 201 at r21](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630#-N7va-yB9rOSpqwaMAUH:-N7va-yB9rOSpqwaMAUI:b-oi8owm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d871f1c02e14d9426a7091c991931c6a16a51eb6/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsServiceTest.kt#L201)):*
> ```Kotlin
> private const val MAX_PAGE_SIZE = 1000
> private const val PAGE_SIZE = 3
> ```

nit: this is quite a large number of constants. I doubt they are all needed.

e.g. you can drop `MEASUREMENT_CONSUMER_NAME` and reference it by `MEASUREMENT_CONSUMER.name` without losing any information about the meaning of the value.

Similarly when you have more than a couple of something, you often can just put them in a list and access them by index. That should also make it easier to build correlated lists (assuming you need them after the merges above, instead of just generating the correlated items in the same loop)

```kotlin
INTERNAL_REPORTING_SETS = REPORTING_SET_EXTERNAL_IDS.mapIndexed { i, externalReportingSetId -> 
  internalReportingSet {
    measurementConsumerReferenceId = MEASUREMENT_CONSUMER_REFERENCE_ID
    this.externalReportingSetId = externalReportingSetId
    eventGroupKeys += INTERNAL_EVENT_GROUP_KEYS[i]
    filter = REPORTING_SET_FILTER
    displayName = REPORTING_SET_DISPLAY_NAMES[i]
  }
}
```
___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsServiceTest.kt` line 202 at r21](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630#-N7vTi0q9BGD9RrkUWvb:-N7vTi0q9BGD9RrkUWvc:b-y75bzr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d871f1c02e14d9426a7091c991931c6a16a51eb6/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsServiceTest.kt#L202)):*
> ```Kotlin
> private const val PAGE_SIZE = 3
> 
> private const val REACH_ONLY_VID_SAMPLING_WIDTH = 3.0f / 300.0f
> ```

nit: same comment as other PR about extracting this



_Code quote:_
```Kotlin
300.0f
```
___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsServiceTest.kt` line 487 at r21](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630#-N7vawEc1jEeSC1KzZMH:-N7vawEc1jEeSC1KzZMI:b3nz1np) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d871f1c02e14d9426a7091c991931c6a16a51eb6/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsServiceTest.kt#L487)):*
> ```Kotlin
>     .toName()
> 
> private val EVENT_GROUP_NAMES = listOf(EVENT_GROUP_NAME, EVENT_GROUP_NAME_2, EVENT_GROUP_NAME_3)
> ```

Is this missing `EVENT_GROUP_NAME_4` ?
___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsServiceTest.kt` line 1430 at r21](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630#-N7vemy33FuvHuxN4ytb:-N7vemy33FuvHuxN4ytc:b-h1twgz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d871f1c02e14d9426a7091c991931c6a16a51eb6/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsServiceTest.kt#L1430)):*
> ```Kotlin
>   private val measurementsMock: MeasurementsCoroutineImplBase =
>     mockService() {
>       onBlocking { createMeasurement(any()) }.thenReturn(null)
> ```

Isn't this the default behavior if you don't stub a method?

Note that you don't need to specify any stubbing at all when calling `mockService`. You can just do all your stubbing in the individual test methods. Doing it here is only for convenience when multiple test methods use the same stubbing.
___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsServiceTest.kt` line 1451 at r21](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630#-N7vfLvo5Q8JGQZM-A0V:-N7vfLvo5Q8JGQZM-A0W:b-nautz8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d871f1c02e14d9426a7091c991931c6a16a51eb6/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsServiceTest.kt#L1451)):*
> ```Kotlin
>     mockService() { onBlocking { getCertificate(any()) }.thenReturn(AGGREGATOR_CERTIFICATE) }
> 
>   private val secureRandomMock: SecureRandom = mock()
> ```

nit: it might be simpler to either
1. Use a "real" SecureRandom but specify a specific algorithm and seed for testing, as that should result in a deterministic set of values (this works if you don't have random ordering of calls)
1. Make a subclass that just overrides `fun next(bits: Int): Int`, as all other methods call that. That way you don't need to stub the specific `next` methods.
___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsServiceTest.kt` line 1576 at r21](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630#-N7vUjNP4zpINk4mkEdz:-N7vUjNP4zpINk4mkEe-:bgn9niv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d871f1c02e14d9426a7091c991931c6a16a51eb6/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsServiceTest.kt#L1576)):*
> ```Kotlin
>       .isEqualTo(MEASUREMENT_CONSUMER_CERTIFICATE_NAME)
> 
>     val unsignedMeasurementSpec =
> ```

nit: no need to call t [...]

2022-07-26 18:26 UTC, SanjayVas requested changes
> Reviewed 1 of 3 files at r2, 1 of 3 files at r4, 2 of 6 files at r7, 3 of 7 files at r15, 1 of 2 files at r17, 4 of 4 files at r21, 1 of 1 files at r22, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630)* status: all files reviewed, 10 unresolved discussions (waiting on @renjiezh, @riemanli, and @tristanvuong2021)



<!-- Sent from Reviewable.io -->

2022-07-26 21:45 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630)* status: 14 of 16 files reviewed, 10 unresolved discussions (waiting on @renjiezh, @SanjayVas, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 1248 at r21](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630#-N7vSfis91o-kvVrsFn9:-N7vnIjU-ZeK3ptvskx_:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d871f1c02e14d9426a7091c991931c6a16a51eb6/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L1248)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

If you're going to immediately `await()` on it, there's no benefit to doing something in another coroutine scope and using `async`. Just go ahead and call the suspending code.
</blockquote></details>

Done.
___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsServiceTest.kt` line 31 at r21](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630#-N7vZsiZ1MUdCqV8PgX_:-N7vowwW1kB8Dwcy_EtC:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d871f1c02e14d9426a7091c991931c6a16a51eb6/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsServiceTest.kt#L31)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Use `assertFailsWith` from kotlin.test instead.
</blockquote></details>

Done.
___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsServiceTest.kt` line 201 at r21](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630#-N7va-yB9rOSpqwaMAUH:-N7wM3K7ERYoJD24BLgg:b-lwrl1t) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d871f1c02e14d9426a7091c991931c6a16a51eb6/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsServiceTest.kt#L201)):*
> e.g. you can drop MEASUREMENT_CONSUMER_NAME and reference it by MEASUREMENT_CONSUMER.name without losing any information about the meaning of the value.

That's a good idea. Thanks!

> Similarly when you have more than a couple of something, you often can just put them in a list and access them by index.

Sounds good. I will use this suggestion for generic things like `REPORTING_SET` but keep the things like `<METRIC-TYPE>_REPORT` as I want the information about what type of the metric result the report contains to be clear.
___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsServiceTest.kt` line 202 at r21](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630#-N7vTi0q9BGD9RrkUWvb:-N7vpbHG3SRIUlDZlszP:bzapxhy) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d871f1c02e14d9426a7091c991931c6a16a51eb6/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsServiceTest.kt#L202)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: same comment as other PR about extracting this
</blockquote></details>

Thanks for catching that! Done.
___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsServiceTest.kt` line 487 at r21](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630#-N7vawEc1jEeSC1KzZMH:-N7vq1ffEk905zYoRL7V:bm455le) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d871f1c02e14d9426a7091c991931c6a16a51eb6/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsServiceTest.kt#L487)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Is this missing `EVENT_GROUP_NAME_4` ?
</blockquote></details>

That is intentional. `EVENT_GROUP_NAME_4` is used to test when a reporting set includes an event group outside the event group universe.
___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsServiceTest.kt` line 1430 at r21](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630#-N7vemy33FuvHuxN4ytb:-N7vqZxq02oGWhs2-tfh:b-hi0gz8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d871f1c02e14d9426a7091c991931c6a16a51eb6/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsServiceTest.kt#L1430)):*
> Isn't this the default behavior if you don't stub a method?

Didn't know that. Thanks for pointing it out! Done.

> Doing it here is only for convenience when multiple test methods use the same stubbing.

Yes. Other stubbed methods are created for multiple usages.
___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsServiceTest.kt` line 1451 at r21](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630#-N7vfLvo5Q8JGQZM-A0V:-N7wP3fh3GGsG865taqq:b2txm86) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d871f1c02e14d9426a7091c991931c6a16a51eb6/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsServiceTest.kt#L1451)):*
Thanks for the suggestion. (1) probably won't work as the calls are random.

> Make a subclass that just overrides fun next(bits: Int): Int, as all other methods call that.

I am not sure the exact overriding process, but I feel like it's more work than the current version.
___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsServiceTest.kt` line 1576 at r21](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630#-N7vUjNP4zpINk4mkEdz:-N7wFO6C5KaDlbeDtGbh:b-u9s1kj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d871f1c02e14d9426a7091c991931c6a16a51eb6/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsServiceTest.kt#L1576)):*
Removed `unsigned` in those names. 

> I might refer to one of those as `signedMeasurementSpec` instead since it otherwise may not be clear what's inside the `SignedData`.

Not really understand what it means. Are you suggesting to create variables for signed data instead of the unsigned ones? I have `REACH_ONLY_MEASUREMENT_SPEC` and other unsigned measurement spec constants used to check the parsed `measurementSpec` in the unit tests as "signed" measurement specs can't be directly compared.
___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsServiceTest.kt` line 1592 at r21](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630#-N7vXYa-7pIYC_qEQ82R:-N7wJH9t2KefbUzMaeBX:by8b9ey) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d871f1c02e14d9426a7091c991931c6a16a51eb6/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsServiceTest.kt#L1592)):*
> // Handle the random sequence due to the execution of coroutine.

There are two fields in `Measurement` that needs to be checked separately with the `verify*` methods : `measurementSpec` and `dataProviderEntry.value.encryptedRequisitionSpec`.  There is only one `measurementSpec` in a `measurement`, so it's fine to verify it as you showed above. However, there are multiple `dataProvider`s (two in this unit test) and thus multiple `dataProviderEntry.value.encryptedRequisitionSpec`. Since an additional method `verifyRequisitionSpec` is needed for the check, I am not sure if there is a way to ignore the order.


<!-- Sent from Reviewable.io -->

2022-07-26 22:54 UTC, SanjayVas requested changes
> Reviewed 1 of 2 files at r23, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630)* status: 15 of 16 files reviewed, 4 unresolved discussions (waiting on @renjiezh, @riemanli, @SanjayVas, and @tristanvuong2021)

___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsServiceTest.kt` line 1576 at r21](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630#-N7vUjNP4zpINk4mkEdz:-N7wal6cE0KKrArZMCvC:b7bn06o) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d871f1c02e14d9426a7091c991931c6a16a51eb6/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsServiceTest.kt#L1576)):*
Sorry, I was just saying that prefixing local variables with `unsigned` doesn't make much sense, as opposed to prefixing local variables with type `SignedData` as `signed`. You're in fact already doing this below, e.g. `signedRequisitionSpec`.

>  "signed" measurement specs can't be directly compared.

Technically the `data` fields of `SignedData` objects can be directly compared, assuming that they were serialized from the same build. It's just the signatures that cannot since signatures contain a random component.

Note that there's also a bug in consent-signaling-client (https://github.com/world-federation-of-advertisers/consent-signaling-client/issues/37) where the verify methods should use the serialized `data` rather than the parsed protobuf message. It just happens to work right now since the serialization has happened to be the same from all builds we're using and nobody has used a client library with a different implementation.
___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsServiceTest.kt` line 1592 at r21](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630#-N7vXYa-7pIYC_qEQ82R:-N7wd3sJ1QOknxIaFvu5:bqiohs7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d871f1c02e14d9426a7091c991931c6a16a51eb6/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsServiceTest.kt#L1592)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

> // Handle the random sequence due to the execution of coroutine.

There are two fields in `Measurement` that needs to be checked separately with the `verify*` methods : `measurementSpec` and `dataProviderEntry.value.encryptedRequisitionSpec`.  There is only one `measurementSpec` in a `measurement`, so it's fine to verify it as you showed above. However, there are multiple `dataProvider`s (two in this unit test) and thus multiple `dataProviderEntry.value.encryptedRequisitionSpec`. Since an additional method `verifyRequisitionSpec` is needed for the check, I am not sure if there is a way to ignore the order.
</blockquote></details>

Ah. So you do have to compare the encryptedRequisitionSpec fields separately. To do this, I would still compare the measurement directly, using `ignoringFieldDescriptors` to ignore the `encryptedRequisitionSpec` fields. I would then assert on the list of dataProviders either by

1. Use [IterableSubject.comparingElementsUsing](https://truth.dev/api/latest/com/google/common/truth/IterableSubject.html#comparingElementsUsing(com.google.common.truth.Correspondence)), passing in a [BinaryPredicate](https://truth.dev/api/latest/com/google/common/truth/Correspondence.BinaryPredicate.html) where `E` is a tuple of (expectedRequisitionSpec, expectedMeasurementSpec). This is a type of Correspondence, meaning it should deal with the fact that the order is unknown.
2. Explicitly sort the dataProvidersList by some value. This is similar to what you're doing now, but using a sort is a clearer way to give something a deterministic order.


<!-- Sent from Reviewable.io -->

2022-07-27 15:51 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630)* status: 15 of 16 files reviewed, 2 unresolved discussions (waiting on @renjiezh, @SanjayVas, and @tristanvuong2021)

___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsServiceTest.kt` line 201 at r21](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630#-N7va-yB9rOSpqwaMAUH:-N7yF8Al6uI7slyxaENt:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d871f1c02e14d9426a7091c991931c6a16a51eb6/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsServiceTest.kt#L201)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

> e.g. you can drop MEASUREMENT_CONSUMER_NAME and reference it by MEASUREMENT_CONSUMER.name without losing any information about the meaning of the value.

That's a good idea. Thanks!

> Similarly when you have more than a couple of something, you often can just put them in a list and access them by index.

Sounds good. I will use this suggestion for generic things like `REPORTING_SET` but keep the things like `<METRIC-TYPE>_REPORT` as I want the information about what type of the metric result the report contains to be clear.
</blockquote></details>

Done.
___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsServiceTest.kt` line 1576 at r21](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630#-N7vUjNP4zpINk4mkEdz:-N7yGAaJ49S2qUZw_Ev1:b-p1k4mm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d871f1c02e14d9426a7091c991931c6a16a51eb6/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsServiceTest.kt#L1576)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Sorry, I was just saying that prefixing local variables with `unsigned` doesn't make much sense, as opposed to prefixing local variables with type `SignedData` as `signed`. You're in fact already doing this below, e.g. `signedRequisitionSpec`.

>  "signed" measurement specs can't be directly compared.

Technically the `data` fields of `SignedData` objects can be directly compared, assuming that they were serialized from the same build. It's just the signatures that cannot since signatures contain a random component.

Note that there's also a bug in consent-signaling-client (https://github.com/world-federation-of-advertisers/consent-signaling-client/issues/37) where the verify methods should use the serialized `data` rather than the parsed protobuf message. It just happens to work right now since the serialization has happened to be the same from all builds we're using and nobody has used a client library with a different implementation.
</blockquote></details>

Thanks for the clarification and the info! As there seems no other issue for this thread, I am resolving it.

Done.
___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsServiceTest.kt` line 1592 at r21](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630#-N7vXYa-7pIYC_qEQ82R:-N7yZrn32sHoJKAPrgPS:bsdgde7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d871f1c02e14d9426a7091c991931c6a16a51eb6/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsServiceTest.kt#L1592)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Ah. So you do have to compare the encryptedRequisitionSpec fields separately. To do this, I would still compare the measurement directly, using `ignoringFieldDescriptors` to ignore the `encryptedRequisitionSpec` fields. I would then assert on the list of dataProviders either by

1. Use [IterableSubject.comparingElementsUsing](https://truth.dev/api/latest/com/google/common/truth/IterableSubject.html#comparingElementsUsing(com.google.common.truth.Correspondence)), passing in a [BinaryPredicate](https://truth.dev/api/latest/com/google/common/truth/Correspondence.BinaryPredicate.html) where `E` is a tuple of (expectedRequisitionSpec, expectedMeasurementSpec). This is a type of Correspondence, meaning it should deal with the fact that the order is unknown.
2. Explicitly sort the dataProvidersList by some value. This is similar to what you're doing now, but using a sort is a clearer way to give something a deterministic order.
</blockquote></details>

Used `ignoringFieldDescriptors ` as suggested. In addition, used `ignoringRepeatedFieldOrderOfFields` for ignoring order in sub-fields.
For `encryptedRequisitionSpec`, the second suggestion was taken.


<!-- Sent from Reviewable.io -->

2022-07-27 15:56 UTC, SanjayVas approved these changes
> Reviewed 1 of 1 files at r24, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630)* status: all files reviewed, 2 unresolved discussions (waiting on @renjiezh, @riemanli, and @tristanvuong2021)

___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsServiceTest.kt` line 1409 at r24](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630#-N8-MbwmC4bqKa1shjF2:-N8-MbwmC4bqKa1shjF3:b-15dq4t) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0c8441d1c4f6a04fcde576f78848d320f93d8d30/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsServiceTest.kt#L1409)):*
> ```Kotlin
> 
>     assertThat(capturedMeasurement)
>       .ignoringRepeatedFieldOrder()
> ```

nit: this is more broad than the line below it. You're basically saying "ignore the order of *all* repeated fields" and then giving a specific field to ignore the order of.



_Code quote:_
```Kotlin
.ignoringRepeatedFieldOrder()
```


<!-- Sent from Reviewable.io -->

2022-07-27 16:10 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630)* status: 15 of 16 files reviewed, 2 unresolved discussions (waiting on @renjiezh, @SanjayVas, and @tristanvuong2021)

___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsServiceTest.kt` line 1409 at r24](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630#-N8-MbwmC4bqKa1shjF2:-N8-PmzH5WxVsVuwA-T1:b-8v34w8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0c8441d1c4f6a04fcde576f78848d320f93d8d30/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsServiceTest.kt#L1409)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: this is more broad than the line below it. You're basically saying "ignore the order of *all* repeated fields" and then giving a specific field to ignore the order of.
</blockquote></details>

Got it. I thought `ignoringRepeatedFieldOrder` only handles the top level fields. 

Removed the redundant `ignoringRepeatedFieldOrderOfFields`.


<!-- Sent from Reviewable.io -->

2022-07-27 16:13 UTC, riemanli reviewed
@sanjayvas is there a way to resolve a discussion on behave of someone? @renjiezh left one unresolved discussion before his temporary leave, and it blocks the PR now.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630#-:-N8-QGulDZndm8rn4OSD:b2tocma)* status: 15 of 16 files reviewed, 1 unresolved discussion (waiting on @renjiezh, @SanjayVas, and @tristanvuong2021)



<!-- Sent from Reviewable.io -->

2022-07-27 18:19 UTC, riemanli reviewed
> Dismissed @renjiezh from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630)* status: 15 of 16 files reviewed, all discussions resolved (waiting on @renjiezh, @SanjayVas, and @tristanvuong2021)



<!-- Sent from Reviewable.io -->

2022-07-27 18:19 UTC, riemanli reviewed
> Reviewed 1 of 3 files at r11, 1 of 5 files at r12, 4 of 7 files at r15, 2 of 4 files at r21, 1 of 1 files at r22, 1 of 2 files at r23, 1 of 1 files at r25, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/630)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @renjiezh and @tristanvuong2021)



<!-- Sent from Reviewable.io -->

2022-07-27 18:21 UTC, merged

2022-08-03 19:34 UTC, chipingyeh commented
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>





<!-- Sent from Reviewable.io -->