Add reporting k8s config
world-federation-of-advertisers/cross-media-measurement pull request #633
Opened 2022-07-19 17:38 UTC by tristanvuong2021

2022-07-20 00:05 UTC, SanjayVas requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/633)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @tristanvuong2021)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/633#-N7Nt0Yq0WQV5f5JKf8t:-N7Nt0Yq0WQV5f5JKf8u:b-7zvm7s) (no related file):*
Could you restructure this PR stack to have the binaries/images and K8s config for just running a reporting server first, leaving all the simulator/integration test until later? I think those latter parts need some more design work first in terms of what kind of test we want. In particular, what we want to verify and how we're going to verify it.

___


<!-- Sent from Reviewable.io -->

2022-07-20 23:52 UTC, tristanvuong2021 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/633)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/633#-N7Nt0Yq0WQV5f5JKf8t:-N7T0cXLDFHeWTG4fwxE:b-896fix) (no related file):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Could you restructure this PR stack to have the binaries/images and K8s config for just running a reporting server first, leaving all the simulator/integration test until later? I think those latter parts need some more design work first in terms of what kind of test we want. In particular, what we want to verify and how we're going to verify it.
</blockquote></details>

Done.

___


<!-- Sent from Reviewable.io -->

2022-07-21 18:01 UTC, SanjayVas requested changes
> Reviewed 1 of 8 files at r1, 4 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/633)* status: 5 of 12 files reviewed, 8 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

___
*[`build/repositories.bzl` line 28 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/633#-N7Wpe6m1Sij8sIxBtaV:-N7Wpe6m1Sij8sIxBtaW:b3ym13m) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3ebe26bb936a1fd23d06189f0eaf13081b81e6a7/build/repositories.bzl#L28)):*
> ```Starlark
>         repo = "common-jvm",
>         sha256 = "d192359a3da0a719c79fac8004a37968e24d6cc246a1b193f1992bbc8c5b17fc",
>         #version = "0.39.0",
> ```

Add an explicit DO_NOT_SUBMIT that reference the PR this is waiting for.
___
*[`src/main/k8s/reporting.cue` line 24 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/633#-N7WqQi577_DDiuWkcNM:-N7WqQi577_DDiuWkcNN:b-nvaruf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3ebe26bb936a1fd23d06189f0eaf13081b81e6a7/src/main/k8s/reporting.cue#L24)):*
> ```CUE
> 
> 	_images: [Name=_]: string
> 	_reporting_image_pull_policy: string
> ```

Consistently use lowerCamelCase for properties for field names. Some existing code mixes in snake_case, but we should avoid that in new files.



_Code quote:_
```CUE
_reporting_image_pull_policy
```
___
*[`src/main/k8s/reporting.cue` line 29 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/633#-N7WstKK9GFya1D-Scmc:-N7WstKK9GFya1D-Scmd:b5s3imf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3ebe26bb936a1fd23d06189f0eaf13081b81e6a7/src/main/k8s/reporting.cue#L29)):*
> ```CUE
> 	_resource_configs: [Name=_]: #ResourceConfig
> 
> 	_reporting_tls_cert_file_flag:             "--tls-cert-file=/var/run/secrets/files/kingdom_tls.pem"
> ```

We don't actually need a separate field for each flag. It's fine to just define groups of flags that are reused for more than one deployment. e.g.

```
_tlsArgs: [
  "--tls-cert-file=/var/run/secrets/files/reporting_tls.pem",
  "--tls-key-file=/var/run/secrets/files/reporting_tls.key",
]
```
___
*[`src/main/k8s/reporting.cue` line 29 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/633#-N7WtO9vD5cxzeKcBJxJ:-N7WtO9vD5cxzeKcBJxK:b-60h59y) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3ebe26bb936a1fd23d06189f0eaf13081b81e6a7/src/main/k8s/reporting.cue#L29)):*
> ```CUE
> 	_resource_configs: [Name=_]: #ResourceConfig
> 
> 	_reporting_tls_cert_file_flag:             "--tls-cert-file=/var/run/secrets/files/kingdom_tls.pem"
> ```

Use a separate cert.



_Code quote:_
```CUE
kingdom_tls
```
___
*[`src/main/k8s/reporting.cue` line 33 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/633#-N7Ws2FT7z1KO_NvjPLx:-N7Ws2FT7z1KO_NvjPLy:b-q7ngna) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3ebe26bb936a1fd23d06189f0eaf13081b81e6a7/src/main/k8s/reporting.cue#L33)):*
> ```CUE
> 	_reporting_cert_collection_file_flag:      "--cert-collection-file=/var/run/secrets/files/all_root_certs.pem"
> 	_akid_to_principal_map_file_flag:        "--authority-key-identifier-to-principal-map-file=/etc/\(#AppName)/config-files/authority_key_identifier_to_principal_map.textproto"
> 	_measurement_consumer_to_api_key_map_file_flag: "--measurement-consumer-to-api-key-map-file=/etc/\(#AppName)/config-files/authority_key_identifier_to_principal_map.textproto"
> ```

There are two mapping config options that both point to the same file?
___
*[`src/main/k8s/reporting.cue` line 58 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/633#-N7WrO7ADM45vS2W6-H7:-N7WrO7ADM45vS2W6-H8:bmx8hs3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3ebe26bb936a1fd23d06189f0eaf13081b81e6a7/src/main/k8s/reporting.cue#L58)):*
> ```CUE
> 		_system:                "reporting"
> 		_image:                 _images[_name]
> 		_imagePullPolicy:       _reporting_image_pull_policy
> ```

Don't add a `reporting` prefix to everything unnecessarily. Some existing code does this to avoid field name conflicts, but these can easily be resolved with aliases.

e.g. `#Reporting: Reporting={` at the definition so you can do `Reporting._imagePullPolicy` within a child struct.



_Code quote:_
```CUE
_reporting_image_pull_policy
```
___
*[`src/main/k8s/reporting.cue` line 59 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/633#-N7WuE4E2XrkE3fX5aiP:-N7WuE4E2XrkE3fX5aiQ:bc9xh6i) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3ebe26bb936a1fd23d06189f0eaf13081b81e6a7/src/main/k8s/reporting.cue#L59)):*
> ```CUE
> 		_image:                 _images[_name]
> 		_imagePullPolicy:       _reporting_image_pull_policy
> 		_replicas:              _resource_configs[_name].replicas
> ```

FYI this pattern is all changed in #610. I'll ping to try to get that submitted.
___
*[`src/main/k8s/reporting.cue` line 66 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/633#-N7WsVLA2omW5rEr4y1Q:-N7WsVLA2omW5rEr4y1R:br6d9h1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3ebe26bb936a1fd23d06189f0eaf13081b81e6a7/src/main/k8s/reporting.cue#L66)):*
> ```CUE
> 	}
> 	deployments: {
> 		//"postgres-reporting-data-server": Deployment={
> ```

Clean up commented-out sections. The schema update initContainer is necessary.
___
*[`src/main/k8s/local/postgres_database.cue` line 38 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/633#-N7WuXAO2pqme7oH2EDZ:-N7WuXAO2pqme7oH2ED_:b-k36yn2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3ebe26bb936a1fd23d06189f0eaf13081b81e6a7/src/main/k8s/local/postgres_database.cue#L38)):*
> ```CUE
> 			selector: app: "postgres-app"
> 			ports: [{
> 				name:       "grpc"
> ```

Postgres uses a single TCP port, I think. 5432 is the default.


<!-- Sent from Reviewable.io -->

2022-07-25 22:09 UTC, tristanvuong2021 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/633)* status: 1 of 21 files reviewed, 8 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/k8s/reporting.cue` line 24 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/633#-N7WqQi577_DDiuWkcNM:-N7rOzqz1aEWFudpcFYF:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3ebe26bb936a1fd23d06189f0eaf13081b81e6a7/src/main/k8s/reporting.cue#L24)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Consistently use lowerCamelCase for properties for field names. Some existing code mixes in snake_case, but we should avoid that in new files.
</blockquote></details>

Done.
___
*[`src/main/k8s/reporting.cue` line 29 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/633#-N7WstKK9GFya1D-Scmc:-N7rP-L61s_dtZA7Xva_:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3ebe26bb936a1fd23d06189f0eaf13081b81e6a7/src/main/k8s/reporting.cue#L29)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

We don't actually need a separate field for each flag. It's fine to just define groups of flags that are reused for more than one deployment. e.g.

```
_tlsArgs: [
  "--tls-cert-file=/var/run/secrets/files/reporting_tls.pem",
  "--tls-key-file=/var/run/secrets/files/reporting_tls.key",
]
```
</blockquote></details>

Done.
___
*[`src/main/k8s/reporting.cue` line 29 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/633#-N7WtO9vD5cxzeKcBJxJ:-N7rP-hhBJHMLRl8YcPb:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3ebe26bb936a1fd23d06189f0eaf13081b81e6a7/src/main/k8s/reporting.cue#L29)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Use a separate cert.
</blockquote></details>

Done.
___
*[`src/main/k8s/reporting.cue` line 33 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/633#-N7Ws2FT7z1KO_NvjPLx:-N7rP0Hw2Y-Y9Aqljjux:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3ebe26bb936a1fd23d06189f0eaf13081b81e6a7/src/main/k8s/reporting.cue#L33)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

There are two mapping config options that both point to the same file?
</blockquote></details>

Done.
___
*[`src/main/k8s/reporting.cue` line 58 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/633#-N7WrO7ADM45vS2W6-H7:-N7rP0fL1JIYPurhqLR3:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3ebe26bb936a1fd23d06189f0eaf13081b81e6a7/src/main/k8s/reporting.cue#L58)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Don't add a `reporting` prefix to everything unnecessarily. Some existing code does this to avoid field name conflicts, but these can easily be resolved with aliases.

e.g. `#Reporting: Reporting={` at the definition so you can do `Reporting._imagePullPolicy` within a child struct.
</blockquote></details>

Done.
___
*[`src/main/k8s/reporting.cue` line 66 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/633#-N7WsVLA2omW5rEr4y1Q:-N7rP2b-DkY4mWWWSm_-:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3ebe26bb936a1fd23d06189f0eaf13081b81e6a7/src/main/k8s/reporting.cue#L66)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Clean up commented-out sections. The schema update initContainer is necessary.
</blockquote></details>

Done.
___
*[`src/main/k8s/local/postgres_database.cue` line 38 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/633#-N7WuXAO2pqme7oH2EDZ:-N7rP3Cr9YwpodFpenJe:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3ebe26bb936a1fd23d06189f0eaf13081b81e6a7/src/main/k8s/local/postgres_database.cue#L38)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Postgres uses a single TCP port, I think. 5432 is the default.
</blockquote></details>

Done.
___
*[`build/repositories.bzl` line 28 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/633#-N7Wpe6m1Sij8sIxBtaV:-N7rP5cY93GK9utriYex:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3ebe26bb936a1fd23d06189f0eaf13081b81e6a7/build/repositories.bzl#L28)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Add an explicit DO_NOT_SUBMIT that reference the PR this is waiting for.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-26 00:05 UTC, SanjayVas requested changes
> Reviewed 2 of 10 files at r2, 21 of 21 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/633)* status: all files reviewed, 8 unresolved discussions (waiting on @tristanvuong2021)

___
*[`src/main/k8s/base.cue` line 57 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/633#-N7rfZ4C3l3WdVJbd8UU:-N7rfZ4C3l3WdVJbd8UV:b-3zpga5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e84437af981dc0c9da3255165b0ba8759dcd92cc/src/main/k8s/base.cue#L57)):*
> ```CUE
> 	host: "$(" + _caps + "_SERVICE_HOST)"
> 	port: "$(" + _caps + "_SERVICE_PORT)"
> 	target: host + ":" + port
> ```

Nice change!
___
*[`src/main/k8s/postgres.cue` line 18 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/633#-N7rfnMDE255mSxxRSIq:-N7rfnMDE255mSxxRSIr:b-cwd609) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e84437af981dc0c9da3255165b0ba8759dcd92cc/src/main/k8s/postgres.cue#L18)):*
> ```CUE
> 
> #PostgresConfig: {
>   cloudSqlInstance?: string
> ```

Aren't `cloudSqlInstance` and `host`/`port` mutually exclusive?

You could theoretically use a [disjunction of structs](https://cuelang.org/docs/tutorials/tour/types/sumstruct/) to implement that.

```cue
#PostgresConfig: {
    _flags: [_=string]: string
  
    user: string
    password: string
    database?: string
    flags: [ for name, value in _flags {"\(name)=\(value)"}]
    
    _flags: {
        "--postgres-user": user
        "--postgres-password": password
        if database != _|_ {"--postgres-database": database}
    }
}

#PostgresConfig: {
    host: string
    port: uint
    
    _flags: {
        "--postgres-host": host
        "--postgres-port": "\(port)"
    }
} | {
    cloudSqlInstance: string
    
    _flags: {
      "--postgres-cloud-sql-instance": cloudSqlInstance
    }
}
```

See https://cuelang.org/play/?id=yn1ItEzunOJ#cue@export@yaml
___
*[`src/main/k8s/dev/config.cue` line 22 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/633#-N7rl0L66gLzpmIxRSWf:-N7rl0L66gLzpmIxRSWg:b-mkeap7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e84437af981dc0c9da3255165b0ba8759dcd92cc/src/main/k8s/dev/config.cue#L22)):*
> ```CUE
> #ContainerRegistry:  "gcr.io"
> #SpannerInstance:    "dev-instance"
> // TODO(tristanvuong2021): replace with region and instance
> ```

nit: `TODO(@tristanvuong2021)` for GitHub username TODO format
___
*[`src/main/k8s/dev/reporting_gke.cue` line 35 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/633#-N7rlwKP2pBcmaavAeUg:-N7rlwKP2pBcmaavAeUh:b-ugr9bt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e84437af981dc0c9da3255165b0ba8759dcd92cc/src/main/k8s/dev/reporting_gke.cue#L35)):*
> ```CUE
> _imageSuffixes: {
> 	"update-reporting-schema":         "/reporting/postgres-update-schema"
> 	"postgres-reporting-data-server":  "reporting/data-server"
> ```

Shouldn't this also start with a `/`? Also, wouldn't this image name also be prefixed with `postgres`?



_Code quote:_
```CUE
"reporting/data-server"
```
___
*[`src/main/k8s/local/postgres_database.cue` line 18 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/633#-N7rn8V017wQzRNPRFc2:-N7rn8V017wQzRNPRFc3:blurar0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e84437af981dc0c9da3255165b0ba8759dcd92cc/src/main/k8s/local/postgres_database.cue#L18)):*
> ```CUE
> 
> _secret_name: string @tag("secret_name")
> _reporting_db_user: string @tag("reporting_db_user")
> ```

nit: camelCase
___
*[`src/main/k8s/local/postgres_database.cue` line 40 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/633#-N7rmKAcCJv-6pFWbEGM:-N7rmKAcCJv-6pFWbEGN:b-umir3f) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e84437af981dc0c9da3255165b0ba8759dcd92cc/src/main/k8s/local/postgres_database.cue#L40)):*
> ```CUE
> 			selector: app: "postgres-app"
> 			ports: [{
> 				name:       "http"
> ```

Inaccurate name. Perhaps "postgresql", as that's the service name registered for that port with the IANA. See https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml?search=5432



_Code quote:_
```CUE
http
```
___
*[`src/main/k8s/local/postgres_database.cue` line 64 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/633#-N7rmuGF9nAdD1zQYDMk:-N7rmuGF9nAdD1zQYDMl:b-nkva3a) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e84437af981dc0c9da3255165b0ba8759dcd92cc/src/main/k8s/local/postgres_database.cue#L64)):*
> ```CUE
> 			name:  "postgres"
> 			image: "docker.io/postgres:14.4-bullseye"
>       env: [{
> ```

nit: the `alpine` one is smaller



_Code quote:_
```CUE
bullseye
```
___
*[`src/main/k8s/local/README.md` line 85 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/633#-N7rnOspEopeuihBGbY-:-N7rnOspEopeuihBGbY0:b-uyyxki) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e84437af981dc0c9da3255165b0ba8759dcd92cc/src/main/k8s/local/README.md#L85)):*
> ```Markdown
> the EDP certificates in [secretfiles](../testing/secretfiles).
> 
> To create one for the reporting server, create the file 
> ```

The file content below doesn't have any MC AKIDs.

You can just set this up to use the same file and just add an entry for the MC, i.e. make the reporting server also use `authority_key_identifier_to_principal_map.textproto`.
___
*[`src/main/k8s/local/README.md` line 140 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/633#-N7roHfV16OgbNDv2Zzl:-N7roHfV16OgbNDv2Zzm:bhst117) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e84437af981dc0c9da3255165b0ba8759dcd92cc/src/main/k8s/local/README.md#L140)):*
> ```Markdown
> 
> Create the file `measurement_consumer_config.textproto` with the
> content below, substituting the appropriate resource name and api key.
> ```

nit `API key`



_Code quote:_
```Markdown
api key
```


<!-- Sent from Reviewable.io -->

2022-07-26 22:06 UTC, tristanvuong2021 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/633)* status: 12 of 26 files reviewed, 4 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/k8s/postgres.cue` line 18 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/633#-N7rfnMDE255mSxxRSIq:-N7wPpYp-LkSv9Zx9dip:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e84437af981dc0c9da3255165b0ba8759dcd92cc/src/main/k8s/postgres.cue#L18)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Aren't `cloudSqlInstance` and `host`/`port` mutually exclusive?

You could theoretically use a [disjunction of structs](https://cuelang.org/docs/tutorials/tour/types/sumstruct/) to implement that.

```cue
#PostgresConfig: {
    _flags: [_=string]: string
  
    user: string
    password: string
    database?: string
    flags: [ for name, value in _flags {"\(name)=\(value)"}]
    
    _flags: {
        "--postgres-user": user
        "--postgres-password": password
        if database != _|_ {"--postgres-database": database}
    }
}

#PostgresConfig: {
    host: string
    port: uint
    
    _flags: {
        "--postgres-host": host
        "--postgres-port": "\(port)"
    }
} | {
    cloudSqlInstance: string
    
    _flags: {
      "--postgres-cloud-sql-instance": cloudSqlInstance
    }
}
```

See https://cuelang.org/play/?id=yn1ItEzunOJ#cue@export@yaml
</blockquote></details>

Done.
___
*[`src/main/k8s/dev/reporting_gke.cue` line 35 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/633#-N7rlwKP2pBcmaavAeUg:-N7wPskn1nV7ioZJdM_t:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e84437af981dc0c9da3255165b0ba8759dcd92cc/src/main/k8s/dev/reporting_gke.cue#L35)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Shouldn't this also start with a `/`? Also, wouldn't this image name also be prefixed with `postgres`?
</blockquote></details>

Done.
___
*[`src/main/k8s/local/postgres_database.cue` line 40 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/633#-N7rmKAcCJv-6pFWbEGM:-N7wPtjF5HJ4cXJYc_ZD:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e84437af981dc0c9da3255165b0ba8759dcd92cc/src/main/k8s/local/postgres_database.cue#L40)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Inaccurate name. Perhaps "postgresql", as that's the service name registered for that port with the IANA. See https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml?search=5432
</blockquote></details>

Done.
___
*[`src/main/k8s/local/README.md` line 85 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/633#-N7rnOspEopeuihBGbY-:-N7wQJhs0LBdZ7Z4Jl7m:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e84437af981dc0c9da3255165b0ba8759dcd92cc/src/main/k8s/local/README.md#L85)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The file content below doesn't have any MC AKIDs.

You can just set this up to use the same file and just add an entry for the MC, i.e. make the reporting server also use `authority_key_identifier_to_principal_map.textproto`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-26 22:22 UTC, tristanvuong2021 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/633)* status: 12 of 26 files reviewed, 4 unresolved discussions (waiting on @SanjayVas)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/633#-N7Nt0Yq0WQV5f5JKf8t:-N7waZIZE7LKhJ1p4ECz:b-x5jh42) (no related file):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

@sanjayvas I switched to using secrets for the postgres db credentials

___


<!-- Sent from Reviewable.io -->

2022-07-26 23:47 UTC, SanjayVas requested changes
> Reviewed 14 of 14 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/633)* status: all files reviewed, 5 unresolved discussions (waiting on @tristanvuong2021)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/633#-N7Nt0Yq0WQV5f5JKf8t:-N7wuBU67djtqiv67pzG:b-5jksfb) (no related file):*
> I switched to using secrets for the postgres db credentials

Good call.

___
___
*[`src/main/k8s/base.cue` line 150 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/633#-N7wq8Bb11S9fysmBaGr:-N7wq8Bb11S9fysmBaGs:b-4zzwql) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f83694c868a3a488930548b7cc6bbb657b6702ed/src/main/k8s/base.cue#L150)):*
> ```CUE
> }
> 
> #SecretEnvVar: SecretEnvVar={
> ```

Just add an `#EnvVar` definition that has what we use from the [K8s API](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#environment-variables) and use that for `#Container._envVars`.
___
*[`src/main/k8s/base.cue` line 212 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/633#-N7wiFlXDQ2udeKD8dcx:-N7wiFlXDQ2udeKD8dcy:b-oqgsn8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f83694c868a3a488930548b7cc6bbb657b6702ed/src/main/k8s/base.cue#L212)):*
> ```CUE
> 				value: "-Xms\(_resourceConfig.jvmHeapSize) -Xmx\(_resourceConfig.jvmHeapSize)"
> 			}
> 			_container: _secretEnvVars: Deployment._secretEnvVars
> ```

This probably shouldn't be in the `_resourceConfig.jvmHeapSize` conditional.
___
*[`src/main/k8s/postgres.cue` line 34 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/633#-N7wrg9T7Wi4jf_-T4Ys:-N7wrg9T7Wi4jf_-T4Yt:b-bcweu2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f83694c868a3a488930548b7cc6bbb657b6702ed/src/main/k8s/postgres.cue#L34)):*
> ```CUE
> #PostgresConfig: {
>     host: string
>     port: string
> ```

nit: `uint32 | string` to match `port` in network policy.



_Code quote:_
```CUE
string
```
___
*[`src/main/k8s/local/postgres_database.cue` line 40 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/633#-N7rmKAcCJv-6pFWbEGM:-N7wsQMh9C8ut7QjAZP3:b-omb81p) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e84437af981dc0c9da3255165b0ba8759dcd92cc/src/main/k8s/local/postgres_database.cue#L40)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I was referring to the port name, which should not be `http`.
___
*[`src/main/k8s/testing/secretfiles/BUILD.bazel` line 117 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/633#-N7wsmes9y4oV7ewXWfn:-N7wsmes9y4oV7ewXWfo:b-uik7rm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f83694c868a3a488930548b7cc6bbb657b6702ed/src/main/k8s/testing/secretfiles/BUILD.bazel#L117)):*
> ```Starlark
>     "reporting_tls.key",
>     "reporting_tls.pem",
>     "reporting_postgres_db_user.txt",
> ```

Use a separate [`kubernetes.io/basic-auth`](https://kubernetes.io/docs/concepts/configuration/secret/#basic-authentication-secret) secret instead, as that's more explicit. Perhaps named `db-auth`?


<!-- Sent from Reviewable.io -->

2022-07-27 18:50 UTC, tristanvuong2021 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/633)* status: 22 of 26 files reviewed, 4 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/k8s/base.cue` line 150 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/633#-N7wq8Bb11S9fysmBaGr:-N7yVG_PDodIjuCE-9eD:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f83694c868a3a488930548b7cc6bbb657b6702ed/src/main/k8s/base.cue#L150)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Just add an `#EnvVar` definition that has what we use from the [K8s API](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#environment-variables) and use that for `#Container._envVars`.
</blockquote></details>

Done.
___
*[`src/main/k8s/base.cue` line 212 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/633#-N7wiFlXDQ2udeKD8dcx:-N7yQt0dBqFCNToULoRQ:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f83694c868a3a488930548b7cc6bbb657b6702ed/src/main/k8s/base.cue#L212)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This probably shouldn't be in the `_resourceConfig.jvmHeapSize` conditional.
</blockquote></details>

Done.
___
*[`src/main/k8s/local/postgres_database.cue` line 40 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/633#-N7rmKAcCJv-6pFWbEGM:-N7yR7Xo0s2zWzlr2IhK:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e84437af981dc0c9da3255165b0ba8759dcd92cc/src/main/k8s/local/postgres_database.cue#L40)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I was referring to the port name, which should not be `http`.
</blockquote></details>

Done.
___
*[`src/main/k8s/testing/secretfiles/BUILD.bazel` line 117 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/633#-N7wsmes9y4oV7ewXWfn:-N8-zQEeCbd_xYCBUIYo:b-6oak01) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f83694c868a3a488930548b7cc6bbb657b6702ed/src/main/k8s/testing/secretfiles/BUILD.bazel#L117)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Use a separate [`kubernetes.io/basic-auth`](https://kubernetes.io/docs/concepts/configuration/secret/#basic-authentication-secret) secret instead, as that's more explicit. Perhaps named `db-auth`?
</blockquote></details>

Can I just add a new apply line to the apply kustomization script that targets db_auth.yaml or something that calls apply for every yaml file


<!-- Sent from Reviewable.io -->

2022-07-27 22:05 UTC, SanjayVas requested changes
> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/633)* status: all files reviewed, 4 unresolved discussions (waiting on @tristanvuong2021)

___
*[`src/main/k8s/base.cue` line 164 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/633#-N80Tv7fB3DLAEFgeZAb:-N80Tv7fB3DLAEFgeZAc:b-dlqrth) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f83694c868a3a488930548b7cc6bbb657b6702ed/src/main/k8s/base.cue#L164)):*
> ```CUE
> 	_secretMounts: [...#SecretMount]
> 	_configMapMounts: [...#ConfigMapMount]
> 	_envVars: [Name=string]: {
> ```

You'll want to keep the _envVars map. Since order doesn't matter, you can't append lists by unioning. The pattern to allow extending a list is to actually make a struct that you convert to a list.

You just want to redefine it as

```cue
_envVars: [Name=string]: #EnvVar & {
  name: Name
}
```
___
*[`src/main/k8s/base.cue` line 205 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/633#-N80TStP0Z3c7ZLTQL5b:-N80TStP0Z3c7ZLTQL5c:b-fxf0t0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b8ea84ac4b0038d4074b68b00645afd13adae5e2/src/main/k8s/base.cue#L205)):*
> ```CUE
> 		_dependencies:    Deployment._dependencies
> 
>     _tempEnvVars: [...#EnvVar]
> ```

No need to use a temp here if you keep the `_envVars` struct in the `#Container`. All fields with the same name in the same scope just get unioned. Therefore, you should just be able to do

```cue
_envVars: [Name=string]: #EnvVar & { name: Name }

_podSpec: {
  _container: {
    _envVars: Deployment._envVars
    if _resourceConfig.jvmHeapSize != _|_ {
      _envVars: {
        "JAVA_TOOL_OPTIONS": {
          value: "-Xms\(_resourceConfig.jvmHeapSize) -Xmx\(_resourceConfig.jvmHeapSize)"
        }
      }
    }
  }
}
```

See https://cuelang.org/play/?id=sgAKgdueKli#cue@export@yaml
___
*[`src/main/k8s/postgres.cue` line 38 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/633#-N80Y5xkB32j-egqcAp2:-N80Y5xkB32j-egqcAp3:bauns7i) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b8ea84ac4b0038d4074b68b00645afd13adae5e2/src/main/k8s/postgres.cue#L38)):*
> ```CUE
>   _flags: {
>       "--postgres-host": host
>       "--postgres-port": port
> ```

I think this needs to be `"\(port)"` in case port isn't a string



_Code quote:_
```CUE
port
```
___
*[`src/main/k8s/testing/secretfiles/BUILD.bazel` line 117 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/633#-N7wsmes9y4oV7ewXWfn:-N80YXye7o5XYmM7VI8k:bnjomgd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f83694c868a3a488930548b7cc6bbb657b6702ed/src/main/k8s/testing/secretfiles/BUILD.bazel#L117)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Can I just add a new apply line to the apply kustomization script that targets db_auth.yaml or something that calls apply for every yaml file
</blockquote></details>

I think there are two separate issues:
1.   What kind of secret the auth creds should be in.
      * `kubernetes.io/basic-auth`

1.   How to make it easy to generate the secret.
      Just add a separate command.

      ```shell
      kubectl create secret generic db-auth --type='kubernetes.io/basic-auth' --append-hash --from-file=password=/tmp/db-pw --from-literal=username=db-user
      ```

  


<!-- Sent from Reviewable.io -->

2022-07-28 17:05 UTC, tristanvuong2021 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/633)* status: 13 of 26 files reviewed, 4 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/k8s/base.cue` line 164 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/633#-N80Tv7fB3DLAEFgeZAb:-N80lYuA6JWbGj1nmK1X:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f83694c868a3a488930548b7cc6bbb657b6702ed/src/main/k8s/base.cue#L164)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

You'll want to keep the _envVars map. Since order doesn't matter, you can't append lists by unioning. The pattern to allow extending a list is to actually make a struct that you convert to a list.

You just want to redefine it as

```cue
_envVars: [Name=string]: #EnvVar & {
  name: Name
}
```
</blockquote></details>

Done.
___
*[`src/main/k8s/base.cue` line 205 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/633#-N80TStP0Z3c7ZLTQL5b:-N80lasB-EVgp1-k8kZ5:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b8ea84ac4b0038d4074b68b00645afd13adae5e2/src/main/k8s/base.cue#L205)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

No need to use a temp here if you keep the `_envVars` struct in the `#Container`. All fields with the same name in the same scope just get unioned. Therefore, you should just be able to do

```cue
_envVars: [Name=string]: #EnvVar & { name: Name }

_podSpec: {
  _container: {
    _envVars: Deployment._envVars
    if _resourceConfig.jvmHeapSize != _|_ {
      _envVars: {
        "JAVA_TOOL_OPTIONS": {
          value: "-Xms\(_resourceConfig.jvmHeapSize) -Xmx\(_resourceConfig.jvmHeapSize)"
        }
      }
    }
  }
}
```

See https://cuelang.org/play/?id=sgAKgdueKli#cue@export@yaml

</blockquote></details>

Done.
___
*[`src/main/k8s/postgres.cue` line 38 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/633#-N80Y5xkB32j-egqcAp2:-N80lbig6dymESnL_0nA:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b8ea84ac4b0038d4074b68b00645afd13adae5e2/src/main/k8s/postgres.cue#L38)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I think this needs to be `"\(port)"` in case port isn't a string
</blockquote></details>

Done.
___
*[`src/main/k8s/testing/secretfiles/BUILD.bazel` line 117 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/633#-N7wsmes9y4oV7ewXWfn:-N7yRzmT7KuEiVs_irhH:b-miepzk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f83694c868a3a488930548b7cc6bbb657b6702ed/src/main/k8s/testing/secretfiles/BUILD.bazel#L117)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I think there are two separate issues:
1.   What kind of secret the auth creds should be in.
      * `kubernetes.io/basic-auth`

1.   How to make it easy to generate the secret.
      Just add a separate command.

      ```shell
      kubectl create secret generic db-auth --type='kubernetes.io/basic-auth' --append-hash --from-file=password=/tmp/db-pw --from-literal=username=db-user
      ```

  
</blockquote></details>

Done and also made the mc config map a secret too.


<!-- Sent from Reviewable.io -->

2022-07-28 18:25 UTC, SanjayVas requested changes
> Reviewed 13 of 13 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/633)* status: all files reviewed, 4 unresolved discussions (waiting on @tristanvuong2021)

___
*[`build/variables.bzl` line 81 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/633#-N84sjs34__t8AK-RU4n:-N84oySX32eeZiy3iMR3:bmfc2ei) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/60e98f31edf1f1a9d8bfa3f527d3bf21286173e1/build/variables.bzl#L81)):*
> ```Starlark
> REPORTING_K8S_SETTINGS = struct(
>     secret_name = "$(k8s_reporting_secret_name)",
>     db_secret_name = "${k8s_reporting_db_secret_name}",
> ```

I was thinking we'd only use this secret for cases where we're not deploying to GKE (i.e. just local).

We can just assume a specific user in the `dev` config since the DB user has the project-specific part of the service account email stripped off. We can stick it in config.cue just in case someone needs to override it.
___
*[`build/variables.bzl` line 82 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/633#-N84oi5_D0mU-DnDLLza:-N84oi5_D0mU-DnDLLzb:b-ux8158) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/60e98f31edf1f1a9d8bfa3f527d3bf21286173e1/build/variables.bzl#L82)):*
> ```Starlark
>     secret_name = "$(k8s_reporting_secret_name)",
>     db_secret_name = "${k8s_reporting_db_secret_name}",
>     mc_config_secret_name = "$(k8s_reporting_mc_config_secret_name)",
> ```

I had assumed we'd just fold this into the main secret since it's the same type. No big deal.
___
*[`src/main/k8s/reporting.cue` line 103 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/633#-N84rfMKE1LhV_u8yiiv:-N84rfMKE1LhV_u8yiiw:b1pzssd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/60e98f31edf1f1a9d8bfa3f527d3bf21286173e1/src/main/k8s/reporting.cue#L103)):*
> ```CUE
> 			}]
> 
> 			_envVars: "MC_CONFIG_FILE": {
> ```

This should be a volume mount rather than an env var.
___
*[`src/main/k8s/local/README.md` line 217 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/633#-N84xK7732xVW1yQYOHC:-N84xK7732xVW1yQYOHD:b-jtr5pw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/60e98f31edf1f1a9d8bfa3f527d3bf21286173e1/src/main/k8s/local/README.md#L217)):*
> ```Markdown
> ## Create Secret for Reporting Server Postgres Database
> Create a file with a password called `/tmp/db-pw` by using
> ```shell
> ```

If you're going to do this, you might as well use --from-literal. The main point of using the file is to avoid having the password be in your shell history. I realized that you can use stdin instead.



_Suggestion:_
```Markdown
You can use `kubectl` to create the `db-auth` secret. To reduce the likelihood of leaking your password, we read it in from STDIN.

Tip: Ctrl+D is the usual key combination for closing the input stream.

Assuming the database username is `db-user`, run:

```shell
kubectl create secret generic db-auth --type='kubernetes.io/basic/auth' \
  --append-hash \
  --from-literal=username=db-user \
  --from-file=password=/dev/stdin
```

Record the secret name for later steps.
```


<!-- Sent from Reviewable.io -->

2022-07-28 21:24 UTC, tristanvuong2021 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/633)* status: 20 of 26 files reviewed, 3 unresolved discussions (waiting on @SanjayVas)

___
*[`build/variables.bzl` line 81 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/633#-N84sjs34__t8AK-RU4n:-N85gSNkD0WcYyE9vUM1:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/60e98f31edf1f1a9d8bfa3f527d3bf21286173e1/build/variables.bzl#L81)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I was thinking we'd only use this secret for cases where we're not deploying to GKE (i.e. just local).

We can just assume a specific user in the `dev` config since the DB user has the project-specific part of the service account email stripped off. We can stick it in config.cue just in case someone needs to override it.
</blockquote></details>

Done.
___
*[`src/main/k8s/reporting.cue` line 103 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/633#-N84rfMKE1LhV_u8yiiv:-N85gT2nBZMWnzE9EInc:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/60e98f31edf1f1a9d8bfa3f527d3bf21286173e1/src/main/k8s/reporting.cue#L103)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This should be a volume mount rather than an env var.
</blockquote></details>

Done.
___
*[`src/main/k8s/local/README.md` line 217 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/633#-N84xK7732xVW1yQYOHC:-N85gQlp8AhDAONL9ZM-:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/60e98f31edf1f1a9d8bfa3f527d3bf21286173e1/src/main/k8s/local/README.md#L217)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

If you're going to do this, you might as well use --from-literal. The main point of using the file is to avoid having the password be in your shell history. I realized that you can use stdin instead.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-28 21:29 UTC, SanjayVas approved these changes
> Reviewed 6 of 6 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/633)* status: all files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)

___
*[`src/main/k8s/dev/config.cue` line 69 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/633#-N85hWIN3Nr2_SOyCJ08:-N85hWIN3Nr2_SOyCJ09:borsu7x) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/68d44408dbaa5a3e6f38ebb22e39955031a5f87d/src/main/k8s/dev/config.cue#L69)):*
> ```CUE
> 	cloudSqlInstance:  #PostgresCloudSqlInstance
> 	// Replace with actual user email
> 	user:              "user@email.com"
> ```

`"reporting-internal@\(#GCloudProject).iam"`



_Code quote:_
```CUE
	// Replace with actual user email
	user:              "user@email.com"
```


<!-- Sent from Reviewable.io -->

2022-07-28 23:16 UTC, tristanvuong2021 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/633)* status: 25 of 26 files reviewed, 1 unresolved discussion (waiting on @duliomatos1, @SanjayVas, and @stevenwarejones)

___
*[`src/main/k8s/dev/config.cue` line 69 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/633#-N85hWIN3Nr2_SOyCJ08:-N8655v0EoUUe8qMkLyt:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/68d44408dbaa5a3e6f38ebb22e39955031a5f87d/src/main/k8s/dev/config.cue#L69)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

`"reporting-internal@\(#GCloudProject).iam"`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-29 19:28 UTC, SanjayVas approved these changes
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/633)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @duliomatos1 and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2022-07-29 19:32 UTC, stevenwarejones approved these changes
> Reviewed 1 of 10 files at r2, 5 of 21 files at r3, 6 of 13 files at r6, 5 of 6 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/633)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @duliomatos1)



<!-- Sent from Reviewable.io -->

2022-07-30 04:35 UTC, tristanvuong2021 reviewed
> Reviewed 18 of 24 files at r9.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/633)* status: 20 of 44 files reviewed, all discussions resolved (waiting on @duliomatos1, @SanjayVas, @stevenwarejones, and @tristanvuong2021)



<!-- Sent from Reviewable.io -->

2022-07-30 04:40 UTC, tristanvuong2021 reviewed
> Reviewed 3 of 24 files at r9, 21 of 21 files at r10, 4 of 4 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/633)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @duliomatos1)



<!-- Sent from Reviewable.io -->

2022-07-30 04:43 UTC, tristanvuong2021 reviewed
> Reviewed 2 of 2 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/633)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @duliomatos1)



<!-- Sent from Reviewable.io -->

2022-07-30 04:46 UTC, tristanvuong2021 reviewed
> Reviewed 1 of 13 files at r6, 1 of 6 files at r7.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/633)* status: 43 of 44 files reviewed, all discussions resolved (waiting on @duliomatos1, @SanjayVas, and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2022-07-30 04:46 UTC, tristanvuong2021 reviewed
> Reviewed 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/633)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @duliomatos1)



<!-- Sent from Reviewable.io -->

2022-07-30 05:12 UTC, merged