Refactor resource configuration for K8s.
world-federation-of-advertisers/cross-media-measurement pull request #659
Opened 2022-08-09 22:13 UTC by SanjayVas

* Specify defaults at the cluster namespace level.
* Refactor definitions to be closer to K8s API.
* Rely on JVM container support for heap sizing (`XX:UseContainerSupport`).
* Adjust resource requirements based upon observed usage during correctness test (will likely need further tweaking).

This also avoids an observed issue with Spanner servers by increasing the ready timeout.

2022-08-09 23:51 UTC, SanjayVas commented
This replaces #658.

2022-08-19 02:48 UTC, matthewclegg requested changes
> Reviewed 30 of 30 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/659)* status: all files reviewed, 6 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/k8s/base.cue` line 131 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/659#-N9nvKXsBG1tN3t_zBhb:-N9nvKXsBG1tN3t_zBhc:br8k6he) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fcf0d30651f3d7e02010cf1d4a96bb7958d796e1/src/main/k8s/base.cue#L131)):*
> ```CUE
> }
> 
> #ObjectMeta: {
> ```

ObjectMeta is a little bit of an obscure name.  Could you add a comment explaining the purpose of this definition and suggesting when/why someone might want to make changes to it?
___
*[`src/main/k8s/base.cue` line 256 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/659#-N9nvxpp99ym7r5eGCZX:-N9nvxpp99ym7r5eGCZY:buws82m) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fcf0d30651f3d7e02010cf1d4a96bb7958d796e1/src/main/k8s/base.cue#L256)):*
> ```CUE
> 
> #Container: {
> 	_secretMounts: [Name=string]:    #SecretMount & {name:    Name}
> ```

Could you add a comment explaining what are secretMounts?  
___
*[`src/main/k8s/dev/duchy_gke.cue` line 31 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/659#-N9nszJS-LUfBqXxZKw5:-N9nszJS-LUfBqXxZKw6:bhyf4bk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9241aed31839da726355f0cdd91b72d9983f4b44/src/main/k8s/dev/duchy_gke.cue#L31)):*
> ```CUE
> }
> #MillResourceConfig: #DefaultResourceConfig & {
> 	replicas: 1
> ```

How will the number of replicas be specified?  BTW, I tried setting this to a value greater than 1 using the existing cue files, and there was no effect, so it looks like the existing cue configuration files are buggy.
___
*[`src/main/k8s/local/duchies.cue` line 24 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/659#-N9ntF440ZEBTMP93PZ3:-N9ntF440ZEBTMP93PZ4:b-ltt6ew) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fcf0d30651f3d7e02010cf1d4a96bb7958d796e1/src/main/k8s/local/duchies.cue#L24)):*
> ```CUE
> #KingdomSystemApiTarget:   (#Target & {name: "system-api-server"}).target
> #SpannerEmulatorHost:      (#Target & {name: "spanner-emulator"}).target
> #MillResourceRequirements: #ResourceRequirements & {
> ```

Could you please sync up with Albert regarding the resource requirements that he is using for the various components in a local configuration?  We might as well use the best information that we currently have about the proper resource requirements.  See PR 669.
___
*[`src/main/k8s/local/README.md` line 10 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/659#-N9ntnyt3QG-Qg9uP42J:-N9ntnyt3QG-Qg9uP42K:bjaqs0k) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fcf0d30651f3d7e02010cf1d4a96bb7958d796e1/src/main/k8s/local/README.md#L10)):*
> ```Markdown
> `kubectl`.
> 
> Minimum Version Required: - KiND: v0.13.0 - kubernetes server: v1.24.0 -
> ```

Just curious, why the reformatting?  I thought the prior formatting was more clear.
___
*[`src/main/k8s/local/README.md` line 38 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/659#-N9nzrZC84RK5MjfDTP4:-N9nzrZC84RK5MjfDTP5:bon2ve8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fcf0d30651f3d7e02010cf1d4a96bb7958d796e1/src/main/k8s/local/README.md#L38)):*
> ```Markdown
>     default:
>       cpu: 100m
>       memory: 256Mi
> ```

How was 256Mi chosen?



_Code quote (from docs/gke/cluster-config.md):_
```Markdown
https://kubernetes.io/docs/tasks/administer-cluster/manage-resources/memory-default-namespace/
```


<!-- Sent from Reviewable.io -->

2022-08-19 02:49 UTC, matthewclegg reviewed
I've done a little bit of cue-hacking over the last month or so but I am by no means a cue (or yaml) expert.  You might want to consider adding another reviewer with stronger expertise in these areas.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/659#-:-N9o-D_m200wLAT5Qt9e:b-yr0y0f)* status: all files reviewed, 6 unresolved discussions (waiting on @SanjayVas)



<!-- Sent from Reviewable.io -->

2022-08-19 17:45 UTC, SanjayVas reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/659)* status: all files reviewed, 6 unresolved discussions (waiting on @matthewclegg and @SanjayVas)

___
*[`src/main/k8s/base.cue` line 131 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/659#-N9nvKXsBG1tN3t_zBhb:-N9r6gpGCpMYEFB5a4cx:b-fw0dol) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fcf0d30651f3d7e02010cf1d4a96bb7958d796e1/src/main/k8s/base.cue#L131)):*
<details><summary><i>Previously, matthewclegg (Matthew Clegg) wrote…</i></summary><blockquote>

ObjectMeta is a little bit of an obscure name.  Could you add a comment explaining the purpose of this definition and suggesting when/why someone might want to make changes to it?
</blockquote></details>

This name comes directly from the Kubernetes API, as many of the definition names do. See https://kubernetes.io/docs/reference/kubernetes-api/common-definitions/object-meta/#ObjectMeta.

We use CUE just to help avoid repetition when interacting with the K8s API via manifests.
___
*[`src/main/k8s/dev/duchy_gke.cue` line 31 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/659#-N9nszJS-LUfBqXxZKw5:-N9r6uNlAhzZMFPXhK_e:b-tg8s9j) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9241aed31839da726355f0cdd91b72d9983f4b44/src/main/k8s/dev/duchy_gke.cue#L31)):*
<details><summary><i>Previously, matthewclegg (Matthew Clegg) wrote…</i></summary><blockquote>

How will the number of replicas be specified?  BTW, I tried setting this to a value greater than 1 using the existing cue files, and there was no effect, so it looks like the existing cue configuration files are buggy.
</blockquote></details>

Hmm, setting replicas should have worked prior to this PR by copying it from the resource config. 

It's a field in the [DeploymentSpec](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/deployment-v1/#DeploymentSpec). e.g. to specify it for the Mill deployment for dev, one would modify the `duchy.deployments["liquid-legions-v2-mill-daemon-deployment"].spec` CUE struct.
___
*[`src/main/k8s/local/duchies.cue` line 24 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/659#-N9ntF440ZEBTMP93PZ3:-N9r93Ou6El0mSLitIuo:bhpzu6y) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fcf0d30651f3d7e02010cf1d4a96bb7958d796e1/src/main/k8s/local/duchies.cue#L24)):*
<details><summary><i>Previously, matthewclegg (Matthew Clegg) wrote…</i></summary><blockquote>

Could you please sync up with Albert regarding the resource requirements that he is using for the various components in a local configuration?  We might as well use the best information that we currently have about the proper resource requirements.  See PR 669.
</blockquote></details>

Will do. Note that these are targeting the correctness test. It's expected that production use cases will need to adjust these based on expected load and desired performance, and that benchmarking will want to use the same.
___
*[`src/main/k8s/local/README.md` line 10 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/659#-N9ntnyt3QG-Qg9uP42J:-N9rA6js9WymuqhJcAqs:bwx7dmo) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fcf0d30651f3d7e02010cf1d4a96bb7958d796e1/src/main/k8s/local/README.md#L10)):*
<details><summary><i>Previously, matthewclegg (Matthew Clegg) wrote…</i></summary><blockquote>

Just curious, why the reformatting?  I thought the prior formatting was more clear.
</blockquote></details>

This was the result of running Google's internal Markdown formatter. The existing list wasn't using the correct spacing, so it got incorrectly formatted to not being a list. I'll fix it.
___
*[`src/main/k8s/local/README.md` line 38 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/659#-N9nzrZC84RK5MjfDTP4:-N9rAYhP82ZPqHpfY-Jd:bvzj9v1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fcf0d30651f3d7e02010cf1d4a96bb7958d796e1/src/main/k8s/local/README.md#L38)):*
<details><summary><i>Previously, matthewclegg (Matthew Clegg) wrote…</i></summary><blockquote>

How was 256Mi chosen?
</blockquote></details>

As the PR description indicates, these values were chosen from observed usage in GKE when running the correctness test.

Note that actual memory usage is tricky to measure when it comes to JVM images, as you're generally trying to tune the JVM to take up as much of the container memory as it can without getting OOM killed. This was just the lowest value I could use with the default JVM heap settings w/UseContainerSupport on without getting OOM killed when running the correctness test. I observed the Spanner tasks as needing more, I assume due to higher native memory overhead. I left the Mill memory as-is as I believe that was determined from expected sketch sizes.

My hope is that it's possible to run the correctness test in KinD without huge CPU and memory requirements on the development machine.


<!-- Sent from Reviewable.io -->

2022-08-22 21:16 UTC, SanjayVas reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/659)* status: 27 of 30 files reviewed, 6 unresolved discussions (waiting on @matthewclegg and @SanjayVas)

___
*[`src/main/k8s/base.cue` line 256 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/659#-N9nvxpp99ym7r5eGCZX:-NA6O2-CBIWM9S7P5FeT:b-4sb0ch) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fcf0d30651f3d7e02010cf1d4a96bb7958d796e1/src/main/k8s/base.cue#L256)):*
<details><summary><i>Previously, matthewclegg (Matthew Clegg) wrote…</i></summary><blockquote>

Could you add a comment explaining what are secretMounts?  
</blockquote></details>

Done (documented the definitions).
___
*[`src/main/k8s/local/README.md` line 10 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/659#-N9ntnyt3QG-Qg9uP42J:-NA6P4HmBXpWJI2cCBrt:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fcf0d30651f3d7e02010cf1d4a96bb7958d796e1/src/main/k8s/local/README.md#L10)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This was the result of running Google's internal Markdown formatter. The existing list wasn't using the correct spacing, so it got incorrectly formatted to not being a list. I'll fix it.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-22 23:47 UTC, SanjayVas reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/659)* status: 27 of 30 files reviewed, 6 unresolved discussions (waiting on @matthewclegg)

___
*[`src/main/k8s/local/duchies.cue` line 24 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/659#-N9ntF440ZEBTMP93PZ3:-NA6wNDg4utQ82tehAG5:btm32gr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fcf0d30651f3d7e02010cf1d4a96bb7958d796e1/src/main/k8s/local/duchies.cue#L24)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Will do. Note that these are targeting the correctness test. It's expected that production use cases will need to adjust these based on expected load and desired performance, and that benchmarking will want to use the same.
</blockquote></details>

I chatted with Albert and read through #669. I think that it would be best to just merge this as-is due to how it significantly changes JVM options w.r.t. memory. That is to say that the observed memory usage with these options are likely to be different and aren't really comparable.

Whichever PR is merged first, the other should adapt and re-measure usage.


<!-- Sent from Reviewable.io -->

2022-08-23 20:05 UTC, matthewclegg requested changes
> Reviewed 1 of 2 files at r2, 1 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/659)* status: 28 of 31 files reviewed, 3 unresolved discussions (waiting on @matthewclegg and @SanjayVas)

___
*[`src/main/k8s/base.cue` line 131 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/659#-N9nvKXsBG1tN3t_zBhb:-NABHh-n47RJQZvzQNUq:b-ouc1ix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fcf0d30651f3d7e02010cf1d4a96bb7958d796e1/src/main/k8s/base.cue#L131)):*
> https://kubernetes.io/docs/reference/kubernetes-api/common-definitions/object-meta/#ObjectMeta

Thanks for the explanation.  Could you add the following comment before this definition?

```
// See https://kubernetes.io/docs/reference/kubernetes-api/common-definitions/object-meta/#ObjectMeta.
```
___
*[`src/main/k8s/dev/duchy_gke.cue` line 31 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/659#-N9nszJS-LUfBqXxZKw5:-NABIP8I8eXdx2LuSqSK:bw9lz88) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9241aed31839da726355f0cdd91b72d9983f4b44/src/main/k8s/dev/duchy_gke.cue#L31)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Hmm, setting replicas should have worked prior to this PR by copying it from the resource config. 

It's a field in the [DeploymentSpec](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/deployment-v1/#DeploymentSpec). e.g. to specify it for the Mill deployment for dev, one would modify the `duchy.deployments["liquid-legions-v2-mill-daemon-deployment"].spec` CUE struct.
</blockquote></details>

I think that it's important that we make this simple.  It appears that the Duchies will need to run with multiple mill replicas, and we need to be able to easily communicate with our partners the change that they need to make.
___
*[`src/main/k8s/local/README.md` line 38 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/659#-N9nzrZC84RK5MjfDTP4:-NABIk-M5hD2DcbAuzdL:b-mfdiir) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fcf0d30651f3d7e02010cf1d4a96bb7958d796e1/src/main/k8s/local/README.md#L38)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

As the PR description indicates, these values were chosen from observed usage in GKE when running the correctness test.

Note that actual memory usage is tricky to measure when it comes to JVM images, as you're generally trying to tune the JVM to take up as much of the container memory as it can without getting OOM killed. This was just the lowest value I could use with the default JVM heap settings w/UseContainerSupport on without getting OOM killed when running the correctness test. I observed the Spanner tasks as needing more, I assume due to higher native memory overhead. I left the Mill memory as-is as I believe that was determined from expected sketch sizes.

My hope is that it's possible to run the correctness test in KinD without huge CPU and memory requirements on the development machine.
</blockquote></details>

Thanks for the explanation.


<!-- Sent from Reviewable.io -->

2022-08-23 21:57 UTC, SanjayVas reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/659)* status: 28 of 31 files reviewed, 3 unresolved discussions (waiting on @matthewclegg)

___
*[`src/main/k8s/base.cue` line 131 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/659#-N9nvKXsBG1tN3t_zBhb:-NABeB3qC-Qd7Jry7vDk:b-lbk9z) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fcf0d30651f3d7e02010cf1d4a96bb7958d796e1/src/main/k8s/base.cue#L131)):*
<details><summary><i>Previously, matthewclegg (Matthew Clegg) wrote…</i></summary><blockquote>

> https://kubernetes.io/docs/reference/kubernetes-api/common-definitions/object-meta/#ObjectMeta

Thanks for the explanation.  Could you add the following comment before this definition?

```
// See https://kubernetes.io/docs/reference/kubernetes-api/common-definitions/object-meta/#ObjectMeta.
```

</blockquote></details>

Mentioned which CUE definitions come from which K8s API objects, with a link to the API reference in the README.
___
*[`src/main/k8s/dev/duchy_gke.cue` line 31 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/659#-N9nszJS-LUfBqXxZKw5:-NABYdTF9E-LjHJBrlzJ:bwemb1r) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9241aed31839da726355f0cdd91b72d9983f4b44/src/main/k8s/dev/duchy_gke.cue#L31)):*
Anyone deploying this in production should have a deep understanding of Kubernetes and its API, such that they could write their own K8s manifests from scratch. The CUE files in the repo are just for development/testing. Our [deployment guides](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/docs/gke/duchy-deployment.md#step-8-create-the-k8s-manifest) only state that they may use our `dev` configuration as a starting point:

> Deploying the Duchy to the cluster is generally done by applying a K8s manifest. You can use the `dev` configuration as a base to get started. The `dev` manifest is a YAML file that is generated from files written in [CUE](https://cuelang.org/) using Bazel rules.

While we mention that users *can* make local edits to the CUE files, that is not a requirement. Doing so assumes you understand both the K8s API *and* the CUE language.
___
*[`src/main/k8s/local/README.md` line 38 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/659#-N9nzrZC84RK5MjfDTP4:-NABaR4T9VYBIzCb85H-:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fcf0d30651f3d7e02010cf1d4a96bb7958d796e1/src/main/k8s/local/README.md#L38)):*
<details><summary><i>Previously, matthewclegg (Matthew Clegg) wrote…</i></summary><blockquote>

Thanks for the explanation.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-23 22:10 UTC, matthewclegg reviewed
> Reviewed 1 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/659)* status: 29 of 32 files reviewed, 1 unresolved discussion (waiting on @matthewclegg)



<!-- Sent from Reviewable.io -->

2022-08-24 22:12 UTC, matthewclegg requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/659)* status: 26 of 32 files reviewed, 1 unresolved discussion (waiting on @matthewclegg and @SanjayVas)

___
*[`src/main/k8s/dev/duchy_gke.cue` line 31 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/659#-N9nszJS-LUfBqXxZKw5:-NAGsjRT8xt4X9ojVnNo:b-47m8rm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9241aed31839da726355f0cdd91b72d9983f4b44/src/main/k8s/dev/duchy_gke.cue#L31)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Anyone deploying this in production should have a deep understanding of Kubernetes and its API, such that they could write their own K8s manifests from scratch. The CUE files in the repo are just for development/testing. Our [deployment guides](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/docs/gke/duchy-deployment.md#step-8-create-the-k8s-manifest) only state that they may use our `dev` configuration as a starting point:

> Deploying the Duchy to the cluster is generally done by applying a K8s manifest. You can use the `dev` configuration as a base to get started. The `dev` manifest is a YAML file that is generated from files written in [CUE](https://cuelang.org/) using Bazel rules.

While we mention that users *can* make local edits to the CUE files, that is not a requirement. Doing so assumes you understand both the K8s API *and* the CUE language.
</blockquote></details>

Not everyone is as capable as you, so I fear you may be overestimating the abilities of the people who will be creating deployments.  In my case, I had to stumble around in the dark for a couple hours before I hit upon the magic incantation needed to increase the number of replicas of the Mill.  Multiply this by the number of people who will be creating duchy deployments over the lifetime of this project, and there's a significant potential for reducing human suffering by adding a couple lines of code to this PR.


<!-- Sent from Reviewable.io -->

2022-08-24 22:35 UTC, SanjayVas reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/659)* status: 26 of 32 files reviewed, 1 unresolved discussion (waiting on @matthewclegg)

___
*[`src/main/k8s/dev/duchy_gke.cue` line 31 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/659#-N9nszJS-LUfBqXxZKw5:-NAGwOiF9ucVtZDNRixi:bszh7h3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9241aed31839da726355f0cdd91b72d9983f4b44/src/main/k8s/dev/duchy_gke.cue#L31)):*
<details><summary><i>Previously, matthewclegg (Matthew Clegg) wrote…</i></summary><blockquote>

Not everyone is as capable as you, so I fear you may be overestimating the abilities of the people who will be creating deployments.  In my case, I had to stumble around in the dark for a couple hours before I hit upon the magic incantation needed to increase the number of replicas of the Mill.  Multiply this by the number of people who will be creating duchy deployments over the lifetime of this project, and there's a significant potential for reducing human suffering by adding a couple lines of code to this PR.
</blockquote></details>

That's not an underestimation, but rather an expectation that we haven't been sufficiently enforcing. We explicitly state in our deployment guides that operators should configure their deployments for expected usage rather than using the dev defaults. This requires knowledge of what can be configured and how to do so.

Note that there are easy ways to change the number of replicas for a running Deployment in GKE:

1.  Via command-line using `kubectl scale deployment`
2.  Via the Cloud Console, via the "Edit replicas" action

    ![image.png](https://files.reviewableusercontent.io/images/reviewable/1747892/VeP4TSCDzFocIYMHT1FxwYqt/image.png)

That said, if there are particular items that we want to make it easy to adjust, I can add those as definitions at the top of the relevant file. e.g. adding `#MillReplicas` in `duchy_gke.cue`.


<!-- Sent from Reviewable.io -->

2022-08-24 23:00 UTC, matthewclegg requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/659)* status: 26 of 32 files reviewed, 1 unresolved discussion (waiting on @matthewclegg and @SanjayVas)

___
*[`src/main/k8s/dev/duchy_gke.cue` line 31 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/659#-N9nszJS-LUfBqXxZKw5:-NAH4-R8CZHwJvOT-SgW:b-mw42y2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9241aed31839da726355f0cdd91b72d9983f4b44/src/main/k8s/dev/duchy_gke.cue#L31)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

That's not an underestimation, but rather an expectation that we haven't been sufficiently enforcing. We explicitly state in our deployment guides that operators should configure their deployments for expected usage rather than using the dev defaults. This requires knowledge of what can be configured and how to do so.

Note that there are easy ways to change the number of replicas for a running Deployment in GKE:

1.  Via command-line using `kubectl scale deployment`
2.  Via the Cloud Console, via the "Edit replicas" action

    ![image.png](https://files.reviewableusercontent.io/images/reviewable/1747892/VeP4TSCDzFocIYMHT1FxwYqt/image.png)

That said, if there are particular items that we want to make it easy to adjust, I can add those as definitions at the top of the relevant file. e.g. adding `#MillReplicas` in `duchy_gke.cue`.
</blockquote></details>

That would be great.  Thank you!  Also, thanks for the info about `kubectl scale deployment`.  I wasn't aware of that.


<!-- Sent from Reviewable.io -->

2022-08-24 23:16 UTC, SanjayVas reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/659)* status: 26 of 32 files reviewed, 1 unresolved discussion (waiting on @matthewclegg)

___
*[`src/main/k8s/dev/duchy_gke.cue` line 31 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/659#-N9nszJS-LUfBqXxZKw5:-NAH7yUC1gTqNkUkNijr:b-tr85pb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9241aed31839da726355f0cdd91b72d9983f4b44/src/main/k8s/dev/duchy_gke.cue#L31)):*
<details><summary><i>Previously, matthewclegg (Matthew Clegg) wrote…</i></summary><blockquote>

That would be great.  Thank you!  Also, thanks for the info about `kubectl scale deployment`.  I wasn't aware of that.
</blockquote></details>

Added `#MillReplicas`


<!-- Sent from Reviewable.io -->

2022-08-24 23:34 UTC, matthewclegg approved these changes
> Reviewed 1 of 3 files at r4, 1 of 2 files at r5, 4 of 4 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/659)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)



<!-- Sent from Reviewable.io -->

2022-08-26 14:35 UTC, stevenwarejones approved these changes
> Reviewed 22 of 30 files at r1, 1 of 2 files at r2, 3 of 3 files at r4, 1 of 2 files at r5, 4 of 4 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/659)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/k8s/dev/config.cue` line 30 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/659#-NAPZ_0S3dqUstqK4Oe0:-NAPZ_0T9PmcHhMppBcQ:bpeee0t) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/127660c82f0c2c55de295fedb73e0b9632cf888b/src/main/k8s/dev/config.cue#L30)):*
> ```CUE
> 	project:      #GCloudProject
> 	instance:     #SpannerInstance
> 	readyTimeout: "30s"
> ```

is that long of a ready timeout really needed?


<!-- Sent from Reviewable.io -->

2022-08-29 18:54 UTC, SanjayVas reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/659)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[`src/main/k8s/dev/config.cue` line 30 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/659#-NAPZ_0S3dqUstqK4Oe0:-NAewFf-37fN1QJM_BuT:b-4opp4d) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/127660c82f0c2c55de295fedb73e0b9632cf888b/src/main/k8s/dev/config.cue#L30)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

is that long of a ready timeout really needed?
</blockquote></details>

Yes, at least I was having issues getting pods that connect to Spanner to start without increasing this. That said, I'm not sure why this is popping up now and I hadn't encountered it before.


<!-- Sent from Reviewable.io -->

2022-08-30 19:41 UTC, stevenwarejones approved these changes
> Reviewed 4 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/659)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)



<!-- Sent from Reviewable.io -->

2022-08-30 23:09 UTC, SanjayVas reviewed
> Dismissed @stevenwarejones from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/659)* status: 30 of 32 files reviewed, all discussions resolved (waiting on @matthewclegg and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2022-08-30 23:09 UTC, SanjayVas reviewed
> Reviewed 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/659)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @matthewclegg and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2022-08-31 00:40 UTC, merged