Update setMeasurementResult calls to be sequential
world-federation-of-advertisers/cross-media-measurement pull request #663
Opened 2022-08-11 22:55 UTC by tristanvuong2021

The calls cannot actually be async due to what setMeasurementResult does. Errors occur due to transaction conflicts. Added a TODO to make setMeasurementResult a method that takes in a list in order to do asynchrous inserts there.

2022-08-11 23:56 UTC, SanjayVas approved these changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/663)* status: all files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/663#-N9EHNqA1pG8U2sSsY79:-N9EHNqA1pG8U2sSsY7A:b-l4mx19) (no related file):*
Approving for now, but I am concerned with the need to do this.

The system should be able to handle a decent amount of concurrent operations (e.g. multiple simultaneous SetMeasurementResult requests). Additionally, we should be able to have n > 1 instances of any of our Deployments. 

Some amount of failures are expected (i.e. when two writes really do conflict), but we want to make sure those are only happening when there is a real conflict. Usually this kind of problem comes about when you read unrelated data during a write transaction, as changes to that data in another transaction will make yours invalid.

___


<!-- Sent from Reviewable.io -->

2022-08-12 00:00 UTC, SanjayVas approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/663)* status: all files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/663#-N9EHNqA1pG8U2sSsY79:-N9ELKtD3gj0pqK9jx6A:bebqepf) (no related file):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Approving for now, but I am concerned with the need to do this.

The system should be able to handle a decent amount of concurrent operations (e.g. multiple simultaneous SetMeasurementResult requests). Additionally, we should be able to have n > 1 instances of any of our Deployments. 

Some amount of failures are expected (i.e. when two writes really do conflict), but we want to make sure those are only happening when there is a real conflict. Usually this kind of problem comes about when you read unrelated data during a write transaction, as changes to that data in another transaction will make yours invalid.
</blockquote></details>

More information on how Postgres handles serializable transaction isolation: https://www.postgresql.org/docs/current/transaction-iso.html#XACT-SERIALIZABLE

___


<!-- Sent from Reviewable.io -->

2022-08-12 20:16 UTC, chipingyeh approved these changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/663)* status: all files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)



<!-- Sent from Reviewable.io -->

2022-08-15 19:48 UTC, SanjayVas requested changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/663)* status: all files reviewed, 4 unresolved discussions (waiting on @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 94 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/663#-N9Y05zQ6F1RaRG1fN1d:-N9Y05zQ6F1RaRG1fN1e:b-bb2z7x) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3b6a49ee9c34063fbd1f853483c54fa01c49e5a3/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L94)):*
> ```Kotlin
> import org.wfanet.measurement.internal.reporting.CreateReportRequest as InternalCreateReportRequest
> import org.wfanet.measurement.internal.reporting.CreateReportRequest.MeasurementKey as InternalMeasurementKey
> import org.wfanet.measurement.internal.reporting.CreateReportRequestKt.measurementKey as internalMeasurementKey
> ```

Avoid this import style due to https://youtrack.jetbrains.com/issue/KTIJ-16471/

Here's a patch you can apply for this file:

```
diff --git src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt
--- src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt
+++ src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt
@@ -46,18 +46,16 @@ import org.wfanet.measurement.api.v2alph
 import org.wfanet.measurement.api.v2alpha.MeasurementConsumerKey
 import org.wfanet.measurement.api.v2alpha.MeasurementConsumersGrpcKt.MeasurementConsumersCoroutineStub
 import org.wfanet.measurement.api.v2alpha.MeasurementKey
-import org.wfanet.measurement.api.v2alpha.MeasurementKt.DataProviderEntryKt.value as dataProviderEntryValue
+import org.wfanet.measurement.api.v2alpha.MeasurementKt.DataProviderEntryKt as DataProviderEntries
 import org.wfanet.measurement.api.v2alpha.MeasurementKt.dataProviderEntry
 import org.wfanet.measurement.api.v2alpha.MeasurementSpec
 import org.wfanet.measurement.api.v2alpha.MeasurementSpec.VidSamplingInterval
-import org.wfanet.measurement.api.v2alpha.MeasurementSpecKt.duration as measurementSpecDuration
-import org.wfanet.measurement.api.v2alpha.MeasurementSpecKt.impression as measurementSpecImpression
-import org.wfanet.measurement.api.v2alpha.MeasurementSpecKt.reachAndFrequency as measurementSpecReachAndFrequency
+import org.wfanet.measurement.api.v2alpha.MeasurementSpecKt as MeasurementSpecs
 import org.wfanet.measurement.api.v2alpha.MeasurementSpecKt.vidSamplingInterval
 import org.wfanet.measurement.api.v2alpha.MeasurementsGrpcKt.MeasurementsCoroutineStub
 import org.wfanet.measurement.api.v2alpha.RequisitionSpec.EventGroupEntry
-import org.wfanet.measurement.api.v2alpha.RequisitionSpecKt.EventGroupEntryKt.value as eventGroupEntryValue
-import org.wfanet.measurement.api.v2alpha.RequisitionSpecKt.eventFilter as requisitionSpecEventFilter
+import org.wfanet.measurement.api.v2alpha.RequisitionSpecKt as RequisitionSpecs
+import org.wfanet.measurement.api.v2alpha.RequisitionSpecKt.EventGroupEntryKt as EventGroupEntries
 import org.wfanet.measurement.api.v2alpha.RequisitionSpecKt.eventGroupEntry
 import org.wfanet.measurement.api.v2alpha.TimeInterval as MeasurementTimeInterval
 import org.wfanet.measurement.api.v2alpha.createMeasurementRequest
@@ -91,15 +89,11 @@ import org.wfanet.measurement.consent.cl
 import org.wfanet.measurement.consent.client.measurementconsumer.verifyResult
 import org.wfanet.measurement.internal.reporting.CreateReportRequest as InternalCreateReportRequest
 import org.wfanet.measurement.internal.reporting.CreateReportRequest.MeasurementKey as InternalMeasurementKey
-import org.wfanet.measurement.internal.reporting.CreateReportRequestKt.measurementKey as internalMeasurementKey
+import org.wfanet.measurement.internal.reporting.CreateReportRequestKt as InternalCreateReportRequests
 import org.wfanet.measurement.internal.reporting.Measurement as InternalMeasurement
 import org.wfanet.measurement.internal.reporting.Measurement.Result as InternalMeasurementResult
-import org.wfanet.measurement.internal.reporting.MeasurementKt.ResultKt.frequency as internalFrequency
-import org.wfanet.measurement.internal.reporting.MeasurementKt.ResultKt.impression as internalImpression
-import org.wfanet.measurement.internal.reporting.MeasurementKt.ResultKt.reach as internalReach
-import org.wfanet.measurement.internal.reporting.MeasurementKt.ResultKt.watchDuration as internalWatchDuration
-import org.wfanet.measurement.internal.reporting.MeasurementKt.failure as internalFailure
-import org.wfanet.measurement.internal.reporting.MeasurementKt.result as internalMeasurementResult
+import org.wfanet.measurement.internal.reporting.MeasurementKt as InternalMeasurments
+import org.wfanet.measurement.internal.reporting.MeasurementKt.ResultKt as InternalResults
 import org.wfanet.measurement.internal.reporting.MeasurementsGrpcKt.MeasurementsCoroutineStub as InternalMeasurementsCoroutineStub
 import org.wfanet.measurement.internal.reporting.Metric as InternalMetric
 import org.wfanet.measurement.internal.reporting.Metric.Details as InternalMetricDetails
@@ -111,20 +105,13 @@ import org.wfanet.measurement.internal.r
 import org.wfanet.measurement.internal.reporting.Metric.SetOperation as InternalSetOperation
 import org.wfanet.measurement.internal.reporting.Metric.SetOperation.Operand as InternalOperand
 import org.wfanet.measurement.internal.reporting.Metric.WatchDurationParams as InternalWatchDurationParams
-import org.wfanet.measurement.internal.reporting.MetricKt.MeasurementCalculationKt.weightedMeasurement as internalWeightedMeasurement
-import org.wfanet.measurement.internal.reporting.MetricKt.SetOperationKt.operand as internalOperand
+import org.wfanet.measurement.internal.reporting.MetricKt as InternalMetrics
+import org.wfanet.measurement.internal.reporting.MetricKt.MeasurementCalculationKt as InternalMeasurementCalculations
+import org.wfanet.measurement.internal.reporting.MetricKt.SetOperationKt as InternalSetOperations
 import org.wfanet.measurement.internal.reporting.MetricKt.SetOperationKt.reportingSetKey
-import org.wfanet.measurement.internal.reporting.MetricKt.details as internalMetricDetails
-import org.wfanet.measurement.internal.reporting.MetricKt.frequencyHistogramParams as internalFrequencyHistogramParams
-import org.wfanet.measurement.internal.reporting.MetricKt.impressionCountParams as internalImpressionCountParams
-import org.wfanet.measurement.internal.reporting.MetricKt.measurementCalculation as internalMeasurementCalculation
-import org.wfanet.measurement.internal.reporting.MetricKt.namedSetOperation as internalNamedSetOperation
-import org.wfanet.measurement.internal.reporting.MetricKt.reachParams as internalReachParams
-import org.wfanet.measurement.internal.reporting.MetricKt.setOperation as internalSetOperation
-import org.wfanet.measurement.internal.reporting.MetricKt.watchDurationParams as internalWatchDurationParams
 import org.wfanet.measurement.internal.reporting.PeriodicTimeInterval as InternalPeriodicTimeInterval
 import org.wfanet.measurement.internal.reporting.Report as InternalReport
-import org.wfanet.measurement.internal.reporting.ReportKt.details as internalReportDetails
+import org.wfanet.measurement.internal.reporting.ReportKt as InternalReports
 import org.wfanet.measurement.internal.reporting.ReportingSet as InternalReportingSet
 import org.wfanet.measurement.internal.reporting.ReportingSetsGrpcKt.ReportingSetsCoroutineStub as InternalReportingSetsCoroutineStub
 import org.wfanet.measurement.internal.reporting.ReportsGrpcKt.ReportsCoroutineStub as InternalReportsCoroutineStub
@@ -169,7 +156,7 @@ import org.wfanet.measurement.reporting.
 import org.wfanet.measurement.reporting.v1a [...]

2022-08-15 23:38 UTC, tristanvuong2021 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/663)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 94 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/663#-N9Y05zQ6F1RaRG1fN1d:-N9YmX9m-yNFzZA-MsHN:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3b6a49ee9c34063fbd1f853483c54fa01c49e5a3/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L94)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Avoid this import style due to https://youtrack.jetbrains.com/issue/KTIJ-16471/

Here's a patch you can apply for this file:

```
diff --git src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt
--- src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt
+++ src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt
@@ -46,18 +46,16 @@ import org.wfanet.measurement.api.v2alph
 import org.wfanet.measurement.api.v2alpha.MeasurementConsumerKey
 import org.wfanet.measurement.api.v2alpha.MeasurementConsumersGrpcKt.MeasurementConsumersCoroutineStub
 import org.wfanet.measurement.api.v2alpha.MeasurementKey
-import org.wfanet.measurement.api.v2alpha.MeasurementKt.DataProviderEntryKt.value as dataProviderEntryValue
+import org.wfanet.measurement.api.v2alpha.MeasurementKt.DataProviderEntryKt as DataProviderEntries
 import org.wfanet.measurement.api.v2alpha.MeasurementKt.dataProviderEntry
 import org.wfanet.measurement.api.v2alpha.MeasurementSpec
 import org.wfanet.measurement.api.v2alpha.MeasurementSpec.VidSamplingInterval
-import org.wfanet.measurement.api.v2alpha.MeasurementSpecKt.duration as measurementSpecDuration
-import org.wfanet.measurement.api.v2alpha.MeasurementSpecKt.impression as measurementSpecImpression
-import org.wfanet.measurement.api.v2alpha.MeasurementSpecKt.reachAndFrequency as measurementSpecReachAndFrequency
+import org.wfanet.measurement.api.v2alpha.MeasurementSpecKt as MeasurementSpecs
 import org.wfanet.measurement.api.v2alpha.MeasurementSpecKt.vidSamplingInterval
 import org.wfanet.measurement.api.v2alpha.MeasurementsGrpcKt.MeasurementsCoroutineStub
 import org.wfanet.measurement.api.v2alpha.RequisitionSpec.EventGroupEntry
-import org.wfanet.measurement.api.v2alpha.RequisitionSpecKt.EventGroupEntryKt.value as eventGroupEntryValue
-import org.wfanet.measurement.api.v2alpha.RequisitionSpecKt.eventFilter as requisitionSpecEventFilter
+import org.wfanet.measurement.api.v2alpha.RequisitionSpecKt as RequisitionSpecs
+import org.wfanet.measurement.api.v2alpha.RequisitionSpecKt.EventGroupEntryKt as EventGroupEntries
 import org.wfanet.measurement.api.v2alpha.RequisitionSpecKt.eventGroupEntry
 import org.wfanet.measurement.api.v2alpha.TimeInterval as MeasurementTimeInterval
 import org.wfanet.measurement.api.v2alpha.createMeasurementRequest
@@ -91,15 +89,11 @@ import org.wfanet.measurement.consent.cl
 import org.wfanet.measurement.consent.client.measurementconsumer.verifyResult
 import org.wfanet.measurement.internal.reporting.CreateReportRequest as InternalCreateReportRequest
 import org.wfanet.measurement.internal.reporting.CreateReportRequest.MeasurementKey as InternalMeasurementKey
-import org.wfanet.measurement.internal.reporting.CreateReportRequestKt.measurementKey as internalMeasurementKey
+import org.wfanet.measurement.internal.reporting.CreateReportRequestKt as InternalCreateReportRequests
 import org.wfanet.measurement.internal.reporting.Measurement as InternalMeasurement
 import org.wfanet.measurement.internal.reporting.Measurement.Result as InternalMeasurementResult
-import org.wfanet.measurement.internal.reporting.MeasurementKt.ResultKt.frequency as internalFrequency
-import org.wfanet.measurement.internal.reporting.MeasurementKt.ResultKt.impression as internalImpression
-import org.wfanet.measurement.internal.reporting.MeasurementKt.ResultKt.reach as internalReach
-import org.wfanet.measurement.internal.reporting.MeasurementKt.ResultKt.watchDuration as internalWatchDuration
-import org.wfanet.measurement.internal.reporting.MeasurementKt.failure as internalFailure
-import org.wfanet.measurement.internal.reporting.MeasurementKt.result as internalMeasurementResult
+import org.wfanet.measurement.internal.reporting.MeasurementKt as InternalMeasurments
+import org.wfanet.measurement.internal.reporting.MeasurementKt.ResultKt as InternalResults
 import org.wfanet.measurement.internal.reporting.MeasurementsGrpcKt.MeasurementsCoroutineStub as InternalMeasurementsCoroutineStub
 import org.wfanet.measurement.internal.reporting.Metric as InternalMetric
 import org.wfanet.measurement.internal.reporting.Metric.Details as InternalMetricDetails
@@ -111,20 +105,13 @@ import org.wfanet.measurement.internal.r
 import org.wfanet.measurement.internal.reporting.Metric.SetOperation as InternalSetOperation
 import org.wfanet.measurement.internal.reporting.Metric.SetOperation.Operand as InternalOperand
 import org.wfanet.measurement.internal.reporting.Metric.WatchDurationParams as InternalWatchDurationParams
-import org.wfanet.measurement.internal.reporting.MetricKt.MeasurementCalculationKt.weightedMeasurement as internalWeightedMeasurement
-import org.wfanet.measurement.internal.reporting.MetricKt.SetOperationKt.operand as internalOperand
+import org.wfanet.measurement.internal.reporting.MetricKt as InternalMetrics
+import org.wfanet.measurement.internal.reporting.MetricKt.MeasurementCalculationKt as InternalMeasurementCalculations
+import org.wfanet.measurement.internal.reporting.MetricKt.SetOperationKt as InternalSetOperations
 import org.wfanet.measurement.internal.reporting.MetricKt.SetOperationKt.reportingSetKey
-import org.wfanet.measurement.internal.reporting.MetricKt.details as internalMetricDetails
-import org.wfanet.measurement.internal.reporting.MetricKt.frequencyHistogramParams as internalFrequencyHistogramParams
-import org.wfanet.measurement.internal.reporting.MetricKt.impressionCountParams as internalImpressionCountParams
-import org.wfanet.measurement.internal.reporting.MetricKt.measurementCalculation as internalMeasurementCalculation
-import org.wfanet.measurement.internal.reporting.MetricKt.namedSetOperation as internalNamedSetOperation
-import org.wfanet.measurement.internal.reporting.MetricKt.reachParams as internalReachParams
-import org.wfanet.measurement.internal.reporting.MetricKt.setOperation as internalSetOperation
-import org.wfanet.measurement.internal.reporting.MetricKt.watchDurationParams as internalWatchDurationParams
 import org.wfanet.measurement.internal.reporting.PeriodicTimeInterval as InternalPeriodicTimeInterval
 import org.wfanet.measurement.internal.reporting.Report as InternalReport
-import org.wfanet.measurement.internal.reporting.ReportKt.details as internalReportDetails
+import org.wfanet.measurement.internal.reporting.ReportKt as InternalReports
 import org.wfanet.measurement.internal.reporting.ReportingSet as InternalReportingSet
 import org.wfanet.measurement.internal.reporting.ReportingSetsGrpcKt.ReportingSetsCoroutineStub as InternalReportingSetsCoroutineStub
 import org.wfanet.measurement.internal.reporting.ReportsGrpcKt.ReportsCoroutineStub as InternalReportsCoroutineStub
@@ -169,7 +156,7 @@ import org.wfanet.measurement.reporting.
 import org.wfanet.measurement.reporting.v1alpha.PeriodicTimeInterval
 import org.wfanet.measurement.reporting.v1alpha.Report
 import org.wfanet.measurement.reporting.v1alpha.Report.Result
-import org.wfanet.measurement.reporting.v1alpha.ReportKt.EventGroupUniverseKt.eventGroupEntry as eventGroupUniverseEntry
+import org.wfanet.measurement.reporting [...]

2022-08-18 22:35 UTC, SanjayVas approved these changes
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/663)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)



<!-- Sent from Reviewable.io -->

2022-08-24 15:20 UTC, stevenwarejones approved these changes
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/663)* status: all files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt` line 795 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/663#-NAFR0f924uuq5bt0mAO:-NAFR0f924uuq5bt0mAP:bsh4amw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dd974ac7ddf6adc192052344597a3c3265d5096b/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v1alpha/ReportsService.kt#L795)):*
> ```Kotlin
>         }
>       }
>       .awaitAll()
> ```

can you add a comment here about why you are awating all?


<!-- Sent from Reviewable.io -->

2023-05-31 01:34 UTC, closed without merging