Create CsvEventQuery to query and filter VIDs from CSV file in KiND
world-federation-of-advertisers/cross-media-measurement pull request #669
Opened 2022-08-17 17:59 UTC by iverson52000

Create CsvEventQuery to query event data from a CSV file, create event template, use eventFilter to filter events, and output the filtered VIDs. The CsvEventQuery is used with KiND deployment. Some local k8s resource configs are modified to run with large CSV file.

This PR is co-authored with jcorilla by merging https://github.com/world-federation-of-advertisers/cross-media-measurement/pull/650

2022-08-17 19:35 UTC, jcorilla reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669)* status: 0 of 30 files reviewed, 1 unresolved discussion (waiting on @duliomatos1, @iverson52000, @matthewclegg, @riemanli, @SanjayVas, and @uakyol)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/CsvEventQuery.kt` line 1 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669#-N9hGoBU1entAOpLXEf8:-N9hGoBU1entAOpLXEf9:bhjq2hd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6f073f6d8f2a1f3b1681c71fde368b3050901615/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/CsvEventQuery.kt#L1)):*
> ```Kotlin
> // Copyright 2021 The Cross-Media Measurement Authors
> ```

Nit: The copyright message should be in the same format as the one for CsvEventQueryTest.kt


<!-- Sent from Reviewable.io -->

2022-08-18 18:45 UTC, duliomatos1 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 10 of 15 files at r1, 5 of 9 files at r2, 7 of 12 files at r3, 1 of 2 files at r4, 5 of 6 files at r5, 1 of 1 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669#-:-N9mGayY1dOiwrBRgMST:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @matthewclegg, @riemanli, @SanjayVas, and @uakyol)



<!-- Sent from Reviewable.io -->

2022-08-19 02:50 UTC, matthewclegg requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669)* status: all files reviewed, 8 unresolved discussions (waiting on @iverson52000, @riemanli, @SanjayVas, and @uakyol)

___
*[`build/repositories.bzl` line 28 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669#-N9naLhq7VN9lt5Adn41:-N9naLhq7VN9lt5Adn42:b-daw0q2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ac847d1b211e5b417c5fe8b5150b7eff83622b25/build/repositories.bzl#L28)):*
> ```Starlark
>         repo = "common-jvm",
>         sha256 = None,
>         # DO_NOT_SUBMIT
> ```

Just curious, why does this say DO_NOT_SUBMIT?  Also, why is the version number lower than the previous version?
___
*[`src/main/k8s/local/duchies.cue` line 105 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669#-N9nahnh8EEcuHeDIf6x:-N9nahnh8EEcuHeDIf6y:bjbxpsw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ac847d1b211e5b417c5fe8b5150b7eff83622b25/src/main/k8s/local/duchies.cue#L105)):*
> ```CUE
> 			"liquid-legions-v2-mill-daemon":    #MillResourceConfig
> 			"requisition-fulfillment-server":   #DuchyServerResourceConfig & {
> 				resources: {
> ```

Perhaps it would be a good idea to have a separate PR just for the purpose of updating the resource requirements?  I see Sanjay has been working on some changes that might conflict with these (see PR #659).  Could you please sync up with him about that?
___
*[`src/main/k8s/local/README.md` line 10 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669#-N9naxPKDOo0VWBzkfJo:-N9naxPKDOo0VWBzkfJp:b-xqxuwq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ac847d1b211e5b417c5fe8b5150b7eff83622b25/src/main/k8s/local/README.md#L10)):*
> ```Markdown
> `kubectl`.
> 
> Minimum Version Required: - KiND: v0.13.0 - kubernetes server: v1.24.0 -
> ```

To me, the previous formatting seemed a little more readable.  Why the change?
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/CsvEventQuery.kt` line 154 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669#-N9nonnMCs3qO0P4vuIo:-N9nonnMCs3qO0P4vuIp:b-q0euzp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ac847d1b211e5b417c5fe8b5150b7eff83622b25/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/CsvEventQuery.kt#L154)):*
> ```Kotlin
>   }
> 
>   /** This function is to simulate reading CSV data in the unit test */
> ```

One possible way to avoid needing this function would be to modify the constructor of this class so that it accepts a Reader as an input argument.  The Reader would represent the file containing the CSV data.  In the unit tests, you could pass a StringReader in place.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/ForwardStorageEdpSimulatorRunner.kt` line 33 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669#-N9nd6A_-OOTmmiPzlJy:-N9nd6A_-OOTmmiPzlJz:b-y0nhvu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ac847d1b211e5b417c5fe8b5150b7eff83622b25/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/ForwardStorageEdpSimulatorRunner.kt#L33)):*
> ```Kotlin
> 
>   @CommandLine.Option(
>     names = ["--event-query"],
> ```

Another alternative would be to define this as follows:

```
  @CommandLine.Option(
    names = ["--event-data-source"],
    description = ["A CSV file specifying the event data that will be returned by this simulator"],
    required=false,
  )
  lateinit var eventDataSourceFlag: String
    private set
```

If `event-data-source` is omitted, then `RandomEventQuery` would be used to generate the events.  If `event-data-source` is specified, then it indicates the name of a file from which the event data will be read.

There are two reasons why I prefer this design.  First, it is backwards compatible with the previous design.  In other words, if the user omits the `event-data-source` parameter, then the behavior is the same as before.  This means that there are fewer opportunities for unexpected breakages.  Second, I think it is better to allow the user to specify the filename than to hard-code the filename.  Otherwise, the user has to manually copy the event data file to the proper location, which adds steps to the deployment process and creates opportunities for human error.

What do you think?
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/data/synthetic-labelled-events.csv` line 0 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669#-N9nggAm55reKHlWt1zJ:-N9nggAm55reKHlWt1zK:b-1atuqr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ac847d1b211e5b417c5fe8b5150b7eff83622b25/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/data/synthetic-labelled-events.csv#L0)):*
Is this the same as the file cross-media-measurement/src/main/k8s/testing/data/synthetic-labelled-events.csv?  Just curious, why move it?
___
*[`src/main/proto/wfa/measurement/api/v2alpha/event_templates/testing/test_banner_template.proto` line 37 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669#-N9nfaQOCcTm1RiQIqQ9:-N9nfaQOCcTm1RiQIqQA:b-x0xfiq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ac847d1b211e5b417c5fe8b5150b7eff83622b25/src/main/proto/wfa/measurement/api/v2alpha/event_templates/testing/test_banner_template.proto#L37)):*
> ```protobuf
> 
>     enum Value {
>       GENDER_UNSPECIFIED = 0;
> ```

These changes seem like they should also be in a separate PR.
___
*[`src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/CsvEventQueryTest.kt` line 73 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669#-N9nhX-135N_zbq4sKEL:-N9nhX-135N_zbq4sKEM:b-iw28rj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ac847d1b211e5b417c5fe8b5150b7eff83622b25/src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/CsvEventQueryTest.kt#L73)):*
> ```Kotlin
>     val eventQuery = CsvEventQuery("edp1")
>     eventQuery.readCSVData(EVENTS)
>     val userVids = eventQuery.getUserVirtualIds(MATCHING_EVENT_FILTER)
> ```

Could you add another test to check the case when the event filter is not specified in the measurement request?


<!-- Sent from Reviewable.io -->

2022-08-19 17:11 UTC, uakyol reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669)* status: all files reviewed, 8 unresolved discussions (waiting on @iverson52000, @matthewclegg, @riemanli, and @SanjayVas)

___
*[`src/main/k8s/local/duchies.cue` line 105 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669#-N9nahnh8EEcuHeDIf6x:-N9r4TTnAf88s7z9X81T:b32v57) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ac847d1b211e5b417c5fe8b5150b7eff83622b25/src/main/k8s/local/duchies.cue#L105)):*
<details><summary><i>Previously, matthewclegg (Matthew Clegg) wrote…</i></summary><blockquote>

Perhaps it would be a good idea to have a separate PR just for the purpose of updating the resource requirements?  I see Sanjay has been working on some changes that might conflict with these (see PR #659).  Could you please sync up with him about that?
</blockquote></details>

+1


<!-- Sent from Reviewable.io -->

2022-08-21 19:16 UTC, uakyol requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669)* status: all files reviewed, 10 unresolved discussions (waiting on @iverson52000, @matthewclegg, @riemanli, and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/CsvEventQuery.kt` line 54 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669#-NA0oIN09Yu-SQvvfl2j:-NA0oIN09Yu-SQvvfl2k:b-hx8s7f) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ac847d1b211e5b417c5fe8b5150b7eff83622b25/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/CsvEventQuery.kt#L54)):*
> ```Kotlin
>   /** Import VIDs from CSV file and creates events list. */
>   init {
>     // Place CSV files in //src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/data
> ```

This is not really 'placing' anything right? If so can you please update this comment to something like "get path for CSV files in //src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/data" because it may cause the reader to think that you are copying data here.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/CsvEventQuery.kt` line 68 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669#-NA0odkqBSmxFqvxRFK9:-NA0odkqBSmxFqvxRFKA:b-q380ln) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ac847d1b211e5b417c5fe8b5150b7eff83622b25/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/CsvEventQuery.kt#L68)):*
> ```Kotlin
>         "data",
>       )
>     // Update fileName to the name of the CSV file you want to use.
> ```

If you want, you can get rid of this comment
___
*[`src/main/proto/wfa/measurement/api/v2alpha/event_templates/testing/test_banner_template.proto` line 37 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669#-N9nfaQOCcTm1RiQIqQ9:-NA0p3ck-78mtdyz3bOO:b32v57) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ac847d1b211e5b417c5fe8b5150b7eff83622b25/src/main/proto/wfa/measurement/api/v2alpha/event_templates/testing/test_banner_template.proto#L37)):*
<details><summary><i>Previously, matthewclegg (Matthew Clegg) wrote…</i></summary><blockquote>

These changes seem like they should also be in a separate PR.
</blockquote></details>

+1


<!-- Sent from Reviewable.io -->

2022-08-22 17:32 UTC, SanjayVas requested changes
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669)* status: all files reviewed, 11 unresolved discussions (waiting on @iverson52000, @matthewclegg, and @riemanli)

___
*[`build/repositories.bzl` line 28 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669#-N9naLhq7VN9lt5Adn41:-NA5XhQR1gT3SHrEYnjU:beip8tb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ac847d1b211e5b417c5fe8b5150b7eff83622b25/build/repositories.bzl#L28)):*
<details><summary><i>Previously, matthewclegg (Matthew Clegg) wrote…</i></summary><blockquote>

Just curious, why does this say DO_NOT_SUBMIT?  Also, why is the version number lower than the previous version?
</blockquote></details>

The DO_NOT_SUBMIT comment is to indicate that we don't want to submit without replacing this commit with a released version. The preferred form is the same as TODOs, e.g. `DO_NOT_SUBMIT(world-federation-of-advertisers/common-jvm#156): Replace with version once released from main.`, which would offer more context.

I imagine that the commented-out version number is just what was there when this PR was created, and it has since been updated.
___
*[`build/variables.bzl` line 50 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669#-NA5Z9zhDiO_T4i-eBqc:-NA5Z9zhDiO_T4i-eBqd:b-uh95d5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ac847d1b211e5b417c5fe8b5150b7eff83622b25/build/variables.bzl#L50)):*
> ```Starlark
>     db_secret_name = "$(k8s_db_secret_name)",
>     mc_config_secret_name = "$(k8s_mc_config_secret_name)",
>     event_query = "$(event_query)",
> ```

The main use case for "Make variable" substitution is when we need to provide something that isn't known until runtime. Is this actually the case here? e.g. for our local targets, do we want this flexibility or do we have a fixed set of options that could be multiple defined targets?



_Code quote:_
```Starlark
"$(event_query)",
```
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/ForwardStorageEdpSimulatorRunner.kt` line 33 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669#-N9nd6A_-OOTmmiPzlJy:-NA5ZnJSCX8Oj5rBVICH:b-90dkcb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ac847d1b211e5b417c5fe8b5150b7eff83622b25/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/ForwardStorageEdpSimulatorRunner.kt#L33)):*
+1 on using an explicit option with a known type, rather than a "stringly-typed" option where the actual type depends on the string value. The option to specify a CSV event data source should be of type `File`, which has built-in parsing from a filesystem path string.

> Second, I think it is better to allow the user to specify the filename than to hard-code the filename. Otherwise, the user has to manually copy the event data file to the proper location, which adds steps to the deployment process and creates opportunities for human error.

The catch with this is the system would then need to know the folder which to read these files from, meaning you'd have another option for that. Given that we only need one file as opposed to multiple files from the same folder, having a single option for the file path would be simpler.


<!-- Sent from Reviewable.io -->

2022-08-22 17:33 UTC, SanjayVas requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669)* status: all files reviewed, 11 unresolved discussions (waiting on @iverson52000, @matthewclegg, and @riemanli)



<!-- Sent from Reviewable.io -->

2022-08-22 20:13 UTC, iverson52000 commented
*[`build/repositories.bzl` line 28 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669#-N9naLhq7VN9lt5Adn41:-NA6AwQa44MGaXsD9Y0A:b-b1w7i4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ac847d1b211e5b417c5fe8b5150b7eff83622b25/build/repositories.bzl#L28)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The DO_NOT_SUBMIT comment is to indicate that we don't want to submit without replacing this commit with a released version. The preferred form is the same as TODOs, e.g. `DO_NOT_SUBMIT(world-federation-of-advertisers/common-jvm#156): Replace with version once released from main.`, which would offer more context.

I imagine that the commented-out version number is just what was there when this PR was created, and it has since been updated.


</blockquote></details>

Done. Update to common-jvm release version number


<!-- Sent from Reviewable.io -->

2022-08-22 20:27 UTC, iverson52000 commented
*[`src/main/k8s/local/README.md` line 10 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669#-N9naxPKDOo0VWBzkfJo:-NA6E8Dk4sAzrkvE1280:bs86eld) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ac847d1b211e5b417c5fe8b5150b7eff83622b25/src/main/k8s/local/README.md#L10)):*
<details><summary><i>Previously, matthewclegg (Matthew Clegg) wrote…</i></summary><blockquote>

To me, the previous formatting seemed a little more readable.  Why the change?
</blockquote></details>

It's formatted with Google mdformat? https://g3doc.corp.google.com/devtools/markdown/mdformat/g3doc/index.md?cl=head


<!-- Sent from Reviewable.io -->

2022-08-22 23:26 UTC, SanjayVas requested changes
> Reviewed 1 of 15 files at r1, 1 of 9 files at r2, 1 of 12 files at r3, 2 of 6 files at r5, 1 of 2 files at r8.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669)* status: 29 of 30 files reviewed, 13 unresolved discussions (waiting on @duliomatos1, @iverson52000, @matthewclegg, and @riemanli)

___
*[`src/main/k8s/local/README.md` line 10 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669#-N9naxPKDOo0VWBzkfJo:-NA6l6si6lS2rUzJ10NY:b2zpmmo) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ac847d1b211e5b417c5fe8b5150b7eff83622b25/src/main/k8s/local/README.md#L10)):*
<details><summary><i>Previously, iverson52000 (Albert Hsu) wrote…</i></summary><blockquote>

It's formatted with Google mdformat? https://g3doc.corp.google.com/devtools/markdown/mdformat/g3doc/index.md?cl=head
</blockquote></details>

I had the same problem in my PR. mdformat requires lists after a paragraph to have a blank line between, which is consistent with original Markdown implementations. Therefore the formatter saw what was intended to be a list as part of the paragraph before it.

The "correct" formatting for the above section is:

```markdown
Minimum Version Required:

-   KiND: v0.13.0
-   kubernetes server: v1.24.0
-   kubectl: compatible with kubernetes server
```
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/BUILD.bazel` line 28 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669#-NA6q-Ns-H-3xNis3vrp:-NA6q-Ns-H-3xNis3vrq:bhgonkp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5ef6dbdabdbe8255594274cb632c470d21b21066/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/BUILD.bazel#L28)):*
> ```Starlark
>         "RandomEventQuery.kt",
>     ],
>     data = [
> ```

This forces these files to be read from Runfiles. I assume we want the simulator to support arbitrary CSVs, and we just happen to include some fixed ones in the repo for convenience.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/CsvEventQuery.kt` line 70 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669#-NA6qDGb02OHxYVZ_C50:-NA6qDGb02OHxYVZ_C51:b-8zb366) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5ef6dbdabdbe8255594274cb632c470d21b21066/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/CsvEventQuery.kt#L70)):*
> ```Kotlin
>     // Update fileName to the name of the CSV file you want to use.
>     val fileName = "synthetic-labelled-events.csv"
>     val fileRuntimePath = getRuntimePath(directoryPath.resolve(fileName)).toString()
> ```

Don't load the CSV file from Runfiles, as that forces them to be referenceable by Bazel. We should either support reading the file from an arbitrary filesystem path location, or from blob storage.

If using filesystem, this means that you need to have the file accessible via a K8s `Volume` or `PersistentVolume`. How you do this may differ depending on whether you're in a real cloud environment such as GKE or using KinD.


<!-- Sent from Reviewable.io -->

2022-08-22 23:28 UTC, SanjayVas requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669)* status: 29 of 30 files reviewed, 13 unresolved discussions (waiting on @duliomatos1, @iverson52000, @matthewclegg, and @riemanli)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/CsvEventQuery.kt` line 70 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669#-NA6qDGb02OHxYVZ_C50:-NA6sKnkD009sA_v9LcN:b-xcg4fi) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5ef6dbdabdbe8255594274cb632c470d21b21066/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/CsvEventQuery.kt#L70)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Don't load the CSV file from Runfiles, as that forces them to be referenceable by Bazel. We should either support reading the file from an arbitrary filesystem path location, or from blob storage.

If using filesystem, this means that you need to have the file accessible via a K8s `Volume` or `PersistentVolume`. How you do this may differ depending on whether you're in a real cloud environment such as GKE or using KinD.
</blockquote></details>

Note that you *can* load from runfiles in a test, just not from the actual EDP simulator.


<!-- Sent from Reviewable.io -->

2022-08-23 20:30 UTC, iverson52000 commented
*[`src/main/k8s/local/README.md` line 10 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669#-N9naxPKDOo0VWBzkfJo:-NABObUt5PJjamop0zhX:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ac847d1b211e5b417c5fe8b5150b7eff83622b25/src/main/k8s/local/README.md#L10)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I had the same problem in my PR. mdformat requires lists after a paragraph to have a blank line between, which is consistent with original Markdown implementations. Therefore the formatter saw what was intended to be a list as part of the paragraph before it.

The "correct" formatting for the above section is:

```markdown
Minimum Version Required:

-   KiND: v0.13.0
-   kubernetes server: v1.24.0
-   kubectl: compatible with kubernetes server
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-23 20:39 UTC, iverson52000 commented
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/data/synthetic-labelled-events.csv` line  at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669#-N9nggAm55reKHlWt1zJ:-NABPyxf-uDzKv_g23mc:b-jrf26l) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ac847d1b211e5b417c5fe8b5150b7eff83622b25/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/data/synthetic-labelled-events.csv#L)):*
<details><summary><i>Previously, matthewclegg (Matthew Clegg) wrote…</i></summary><blockquote>

Is this the same as the file cross-media-measurement/src/main/k8s/testing/data/synthetic-labelled-events.csv?  Just curious, why move it?
</blockquote></details>

I copy the file to this directory and use it as a sample file for CsvEventQuery. I feel it makes more sense to put the CSV file under the same directory with CsvEventQuery?


<!-- Sent from Reviewable.io -->

2022-08-23 21:14 UTC, SanjayVas reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669)* status: 29 of 30 files reviewed, 13 unresolved discussions (waiting on @duliomatos1, @iverson52000, @matthewclegg, and @riemanli)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/data/synthetic-labelled-events.csv` line  at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669#-N9nggAm55reKHlWt1zJ:-NABYLRvBPMgSZ4N7hoM:b-g5rw3v) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ac847d1b211e5b417c5fe8b5150b7eff83622b25/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/data/synthetic-labelled-events.csv#L)):*
<details><summary><i>Previously, iverson52000 (Albert Hsu) wrote…</i></summary><blockquote>

I copy the file to this directory and use it as a sample file for CsvEventQuery. I feel it makes more sense to put the CSV file under the same directory with CsvEventQuery?
</blockquote></details>

We generally don't want more than one copy of the same file in the repo. It should be in a location that makes sense for all usages.


<!-- Sent from Reviewable.io -->

2022-08-23 22:21 UTC, iverson52000 commented
*[`src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/CsvEventQueryTest.kt` line 73 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669#-N9nhX-135N_zbq4sKEL:-NABmr1WAW1fJUbZ2rZ-:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ac847d1b211e5b417c5fe8b5150b7eff83622b25/src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/CsvEventQueryTest.kt#L73)):*
<details><summary><i>Previously, matthewclegg (Matthew Clegg) wrote…</i></summary><blockquote>

Could you add another test to check the case when the event filter is not specified in the measurement request?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-24 22:57 UTC, matthewclegg requested changes
> Reviewed 4 of 9 files at r2, 4 of 12 files at r3, 2 of 6 files at r5, 1 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669)* status: 28 of 30 files reviewed, 10 unresolved discussions (waiting on @duliomatos1, @iverson52000, @matthewclegg, @riemanli, and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/ForwardStorageEdpSimulatorRunner.kt` line 33 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669#-N9nd6A_-OOTmmiPzlJy:-NAH32UsEA3sCs_rWSOf:b-ijtbg0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ac847d1b211e5b417c5fe8b5150b7eff83622b25/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/ForwardStorageEdpSimulatorRunner.kt#L33)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

+1 on using an explicit option with a known type, rather than a "stringly-typed" option where the actual type depends on the string value. The option to specify a CSV event data source should be of type `File`, which has built-in parsing from a filesystem path string.

> Second, I think it is better to allow the user to specify the filename than to hard-code the filename. Otherwise, the user has to manually copy the event data file to the proper location, which adds steps to the deployment process and creates opportunities for human error.

The catch with this is the system would then need to know the folder which to read these files from, meaning you'd have another option for that. Given that we only need one file as opposed to multiple files from the same folder, having a single option for the file path would be simpler.
</blockquote></details>

I agree with you that it would be better to have a single option for the file path.  This is what I had intended, I was just a little loose with my language.  Thank you for pointing that out.


<!-- Sent from Reviewable.io -->

2022-09-07 21:28 UTC, iverson52000 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669)* status: 1 of 32 files reviewed, 10 unresolved discussions (waiting on @duliomatos1, @iverson52000, @matthewclegg, @riemanli, @SanjayVas, and @uakyol)

___
*[`build/variables.bzl` line 50 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669#-NA5Z9zhDiO_T4i-eBqc:-NBOpNai-3slfvzFnsD0:b-9ms6pc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ac847d1b211e5b417c5fe8b5150b7eff83622b25/build/variables.bzl#L50)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The main use case for "Make variable" substitution is when we need to provide something that isn't known until runtime. Is this actually the case here? e.g. for our local targets, do we want this flexibility or do we have a fixed set of options that could be multiple defined targets?
</blockquote></details>

Created a new target `edp_simulators_kind_csv` instead of appending make variable to existing target `edp_simulators_kind`
___
*[`src/main/k8s/local/duchies.cue` line 105 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669#-N9nahnh8EEcuHeDIf6x:-NBOpwyh1T1k6sMdpa80:bp3yud5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ac847d1b211e5b417c5fe8b5150b7eff83622b25/src/main/k8s/local/duchies.cue#L105)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

+1
</blockquote></details>

Yes the resource config changes is for @riemanli to run the benchmarking program in Kind. Will open a new PR to merge them separately
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/CsvEventQuery.kt` line 54 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669#-NA0oIN09Yu-SQvvfl2j:-NBOogQr-ESK4Zgq1Ids:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ac847d1b211e5b417c5fe8b5150b7eff83622b25/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/CsvEventQuery.kt#L54)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

This is not really 'placing' anything right? If so can you please update this comment to something like "get path for CSV files in //src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/data" because it may cause the reader to think that you are copying data here.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/CsvEventQuery.kt` line 68 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669#-NA0odkqBSmxFqvxRFK9:-NBOohN9AnQIN8GrmDug:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ac847d1b211e5b417c5fe8b5150b7eff83622b25/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/CsvEventQuery.kt#L68)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

If you want, you can get rid of this comment
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/data/synthetic-labelled-events.csv` line  at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669#-N9nggAm55reKHlWt1zJ:-NBOooxUAeiX-khL8nU3:b-pe1fag) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ac847d1b211e5b417c5fe8b5150b7eff83622b25/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/data/synthetic-labelled-events.csv#L)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

We generally don't want more than one copy of the same file in the repo. It should be in a location that makes sense for all usages.
</blockquote></details>

Change to using single folder location for CSV testing file
___
*[`src/main/proto/wfa/measurement/api/v2alpha/event_templates/testing/test_banner_template.proto` line 37 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669#-N9nfaQOCcTm1RiQIqQ9:-NBOowWLD60pxz3f4LJw:bbj9zex) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ac847d1b211e5b417c5fe8b5150b7eff83622b25/src/main/proto/wfa/measurement/api/v2alpha/event_templates/testing/test_banner_template.proto#L37)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

+1
</blockquote></details>

The correctness of event filtering in CsvEventQuery may be affected by this so I suggest to do it here?


<!-- Sent from Reviewable.io -->

2022-09-09 02:00 UTC, SanjayVas reviewed
> Reviewed 2 of 17 files at r20.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669)* status: 3 of 32 files reviewed, 9 unresolved discussions (waiting on @duliomatos1, @iverson52000, @matthewclegg, @riemanli, @SanjayVas, and @uakyol)



<!-- Sent from Reviewable.io -->

2022-09-13 17:18 UTC, renjiezh requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669)* status: 3 of 32 files reviewed, 10 unresolved discussions (waiting on @duliomatos1, @iverson52000, @matthewclegg, @riemanli, @SanjayVas, and @uakyol)

___
*[`src/main/k8s/testing/secretfiles/resource_requirements_kind.yaml` line 1 at r20](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669#-NBrr-NTEN9YSMs4KhdU:-NBrr-NUDAZbN5HGjd1q:b-1li2u7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6217687b951ed92169e9782486b2ca06f11ef3f0/src/main/k8s/testing/secretfiles/resource_requirements_kind.yaml#L1)):*
> ```YAML
> # Copyright 2022 The Cross-Media Measurement Authors
> ```

Do we want to move this file to `k8s/local/`?


<!-- Sent from Reviewable.io -->

2022-09-15 17:48 UTC, iverson52000 commented
*[`src/main/k8s/testing/secretfiles/resource_requirements_kind.yaml` line 1 at r20](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669#-NBrr-NTEN9YSMs4KhdU:-NC1FlaQ96S89K5fEPNV:bp25ydo) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6217687b951ed92169e9782486b2ca06f11ef3f0/src/main/k8s/testing/secretfiles/resource_requirements_kind.yaml#L1)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

Do we want to move this file to `k8s/local/`?
</blockquote></details>

I don't have a preference and now I just put it in the same folder as `resource_requirements.yaml`


<!-- Sent from Reviewable.io -->

2022-09-15 17:53 UTC, renjiezh reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669)* status: 2 of 32 files reviewed, 10 unresolved discussions (waiting on @duliomatos1, @iverson52000, @matthewclegg, @riemanli, @SanjayVas, and @uakyol)

___
*[`src/main/k8s/testing/secretfiles/resource_requirements_kind.yaml` line 1 at r20](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669#-NBrr-NTEN9YSMs4KhdU:-NC1GQsi3xZfuGwVjb6k:b-am9bgs) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6217687b951ed92169e9782486b2ca06f11ef3f0/src/main/k8s/testing/secretfiles/resource_requirements_kind.yaml#L1)):*
<details><summary><i>Previously, iverson52000 (Albert Hsu) wrote…</i></summary><blockquote>

I don't have a preference and now I just put it in the same folder as `resource_requirements.yaml`
</blockquote></details>

According to the my experiment, if we don't apply this requirement to Kind K8s, pods will crash frequently. Thus it seems necessary when deploy locally. Eventually, we need to migrate the content of this .yaml to .cue settings thus apply it automatically without an extra step of `kubectl apply'. 
I will leave this as a nit.


<!-- Sent from Reviewable.io -->

2022-09-19 17:36 UTC, iverson52000 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669)* status: 2 of 33 files reviewed, 9 unresolved discussions (waiting on @duliomatos1, @iverson52000, @matthewclegg, @riemanli, @SanjayVas, and @uakyol)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/BUILD.bazel` line 28 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669#-NA6q-Ns-H-3xNis3vrp:-NCLoMQaBuzrgktsNHsn:bjfw4rl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5ef6dbdabdbe8255594274cb632c470d21b21066/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/BUILD.bazel#L28)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This forces these files to be read from Runfiles. I assume we want the simulator to support arbitrary CSVs, and we just happen to include some fixed ones in the repo for convenience.
</blockquote></details>

Change to use k8s volume emptyDir to load CSV files
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/CsvEventQuery.kt` line 70 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669#-NA6qDGb02OHxYVZ_C50:-NCLoWyl1YCZR6yEyJMi:bjfw4rl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5ef6dbdabdbe8255594274cb632c470d21b21066/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/CsvEventQuery.kt#L70)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Note that you *can* load from runfiles in a test, just not from the actual EDP simulator.
</blockquote></details>

Change to use k8s volume emptyDir to load CSV files


<!-- Sent from Reviewable.io -->

2022-09-19 17:40 UTC, iverson52000 commented
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/ForwardStorageEdpSimulatorRunner.kt` line 33 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669#-N9nd6A_-OOTmmiPzlJy:-NCLp4mV4Qk_RBuOxk-f:bvox3cl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ac847d1b211e5b417c5fe8b5150b7eff83622b25/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/ForwardStorageEdpSimulatorRunner.kt#L33)):*
<details><summary><i>Previously, matthewclegg (Matthew Clegg) wrote…</i></summary><blockquote>

I agree with you that it would be better to have a single option for the file path.  This is what I had intended, I was just a little loose with my language.  Thank you for pointing that out.
</blockquote></details>

Now use a separate bazel target `edp_simulators_kind_csv` and specify the local CSV filepath in the `kubectl cp` command


<!-- Sent from Reviewable.io -->

2022-09-19 17:40 UTC, iverson52000 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669)* status: 2 of 33 files reviewed, 9 unresolved discussions (waiting on @duliomatos1, @matthewclegg, @riemanli, @SanjayVas, and @uakyol)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/CsvEventQuery.kt` line 154 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669#-N9nonnMCs3qO0P4vuIo:-NCLoxQK2KfVsO4BpLRz:bz8d3g3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ac847d1b211e5b417c5fe8b5150b7eff83622b25/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/CsvEventQuery.kt#L154)):*
<details><summary><i>Previously, matthewclegg (Matthew Clegg) wrote…</i></summary><blockquote>

One possible way to avoid needing this function would be to modify the constructor of this class so that it accepts a Reader as an input argument.  The Reader would represent the file containing the CSV data.  In the unit tests, you could pass a StringReader in place.
</blockquote></details>

Discussed with Matt and leave it the way it is for now


<!-- Sent from Reviewable.io -->

2022-09-19 21:13 UTC, SanjayVas requested changes
> Reviewed 1 of 15 files at r1, 1 of 18 files at r11, 1 of 3 files at r14, 1 of 18 files at r20, 4 of 9 files at r28, 5 of 10 files at r29, 10 of 16 files at r31, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669)* status: 24 of 33 files reviewed, 8 unresolved discussions (waiting on @duliomatos1, @iverson52000, @matthewclegg, @riemanli, @SanjayVas, and @uakyol)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/BUILD.bazel` line 93 at r31](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669#-NCM_B7y16965329G3w8:-NCM_B7y16965329G3w9:b-te54vv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/350cd2485ffa2eee4558dc0aa0dfa6793bf352d8/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/BUILD.bazel#L93)):*
> ```Starlark
> )
> 
> #Use java_debug_image_base which has TAR binary to run kubectl cp
> ```

nit: move this comment to above the line where `base` attribute is set
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/ForwardStorageEdpSimulatorRunner.kt` line 33 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669#-N9nd6A_-OOTmmiPzlJy:-NCM_V_TCm_CDbCiRZkC:b-1inybm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ac847d1b211e5b417c5fe8b5150b7eff83622b25/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/ForwardStorageEdpSimulatorRunner.kt#L33)):*
<details><summary><i>Previously, iverson52000 (Albert Hsu) wrote…</i></summary><blockquote>

Now use a separate bazel target `edp_simulators_kind_csv` and specify the local CSV filepath in the `kubectl cp` command
</blockquote></details>

The actual file path should still be controlled by a flag rather than being hard-coded.

The fact that we're using an emptyDir volume and `kubectl cp` should be decoupled from the implementation of the simulator itself. It should just allow a CSV file path to be provided.


<!-- Sent from Reviewable.io -->

2022-09-19 21:16 UTC, uakyol approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669)* status: 24 of 33 files reviewed, 8 unresolved discussions (waiting on @duliomatos1, @iverson52000, @matthewclegg, @riemanli, @SanjayVas, and @uakyol)



<!-- Sent from Reviewable.io -->

2022-09-19 21:16 UTC, uakyol approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669)* status: 24 of 33 files reviewed, 6 unresolved discussions (waiting on @duliomatos1, @iverson52000, @matthewclegg, @riemanli, and @SanjayVas)



<!-- Sent from Reviewable.io -->

2022-09-20 19:14 UTC, SanjayVas requested changes
> Reviewed 1 of 9 files at r28, 1 of 10 files at r29, 2 of 16 files at r31, 8 of 8 files at r32, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669)* status: all files reviewed, 10 unresolved discussions (waiting on @duliomatos1, @iverson52000, @matthewclegg, and @riemanli)

___
*[`src/main/k8s/local/BUILD.bazel` line 267 at r32](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669#-NCRE2UOBaB4BmnT8vcb:-NCRE2UOBaB4BmnT8vcc:botn628) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a60caaa69e553a7443ec10ba518c38605133242f/src/main/k8s/local/BUILD.bazel#L267)):*
> ```Starlark
> 
> k8s_apply(
>     name = "edp_simulators_kind_csv",
> ```

nit: `csv_kind`. the `kind` should go at the end



_Code quote:_
```Starlark
kind_csv
```
___
*[`src/main/k8s/local/edp_simulators.cue` line 47 at r32](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669#-NCRJ4HH8fxtEsI9jkXU:-NCRJ4HH8fxtEsI9jkXV:b-t4jbs0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a60caaa69e553a7443ec10ba518c38605133242f/src/main/k8s/local/edp_simulators.cue#L47)):*
> ```CUE
> 			_edp_secret_name:           _secret_name
> 			_mc_resource_name:          _mc_name
> 			_event_data_source:         "randomEventQuery"
> ```

New code should use consistent lowerCamelCase naming for these.

I'm not sure when snake_case names started being introduced, and now we unfortunately have a mix.



_Code quote:_
```CUE
_event_data_source
```
___
*[`src/main/k8s/local/edp_simulators_csv.cue` line 1 at r32](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669#-NCRJIZWD7dUs3QUDyZI:-NCRI24T-ZHumECx67Fo:b-ek9pkx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a60caaa69e553a7443ec10ba518c38605133242f/src/main/k8s/local/edp_simulators_csv.cue#L1)):*
> ```CUE
> // Copyright 2021 The Cross-Media Measurement Authors
> ```

Rather than having a whole separate copy of the file, utilize CUE's union capabilities. Create a cue_library for the local edp_simulators.cue and depend on that, just overriding the field that triggers CSV.
___
*[`src/main/k8s/testing/secretfiles/resource_requirements_kind.yaml` line 23 at r32](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669#-NCRIVArCw5l5myIYTFs:-NCRIVArCw5l5myIYTFt:b-rvfkyh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a60caaa69e553a7443ec10ba518c38605133242f/src/main/k8s/testing/secretfiles/resource_requirements_kind.yaml#L23)):*
> ```YAML
>   - type: Container
>     default:
>       memory: 1024Mi
> ```

This is setting the default for any container without resource requirements specified. This shouldn't need to be different for KinD vs. on cloud. If any specific container needs different requirements, it should have them specified in the relevant CUE file for that environment.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/CsvEventQuery.kt` line 51 at r32](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669#-NCRFCj6Axq7AkivcHI5:-NCRFCj73WeRh6aeyd12:balxxv4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a60caaa69e553a7443ec10ba518c38605133242f/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/CsvEventQuery.kt#L51)):*
> ```Kotlin
> 
>   /** Import VIDs from CSV file and creates events list. */
>   init {
> ```

Rather than doing this on class init, read it in using a lazy delegated property instead. That way we won't initialize until the first call to `getUserVirtualIds`, which should give time to copy the CSV file into the volume without needing retry logic here.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/ForwardStorageEdpSimulatorRunner.kt` line 33 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669#-N9nd6A_-OOTmmiPzlJy:-NCRGwaJ8gSId_pllw9C:b-weto7u) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ac847d1b211e5b417c5fe8b5150b7eff83622b25/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/ForwardStorageEdpSimulatorRunner.kt#L33)):*
<details><summary><i>Previously, iverson52000 (Albert Hsu) wrote…</i></summary><blockquote>

Update flag name to `--event-data-source`. Change to specify `filePath` in `edp_simulators_csv.cue` instead of hard-coded in Kotlin
</blockquote></details>

The comments above are still relevant. This should be a property of type `File?` and not be a stringly-typed File-or-magic-sentinel-string. I'd name it something like "--events-csv" so it's clear that specifying it is what triggers use of a CSV file.


<!-- Sent from Reviewable.io -->

2022-09-21 20:00 UTC, iverson52000 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669)* status: 7 of 33 files reviewed, 9 unresolved discussions (waiting on @duliomatos1, @iverson52000, @matthewclegg, @riemanli, and @SanjayVas)

___
*[`src/main/k8s/local/edp_simulators.cue` line 47 at r32](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669#-NCRJ4HH8fxtEsI9jkXU:-NCWbavG8U9exfKIYPJi:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a60caaa69e553a7443ec10ba518c38605133242f/src/main/k8s/local/edp_simulators.cue#L47)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

New code should use consistent lowerCamelCase naming for these.

I'm not sure when snake_case names started being introduced, and now we unfortunately have a mix.
</blockquote></details>

Done.
___
*[`src/main/k8s/testing/secretfiles/resource_requirements_kind.yaml` line 23 at r32](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669#-NCRIVArCw5l5myIYTFs:-NCWbxC-EhNVtEEbEqv5:b-2efbnu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a60caaa69e553a7443ec10ba518c38605133242f/src/main/k8s/testing/secretfiles/resource_requirements_kind.yaml#L23)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This is setting the default for any container without resource requirements specified. This shouldn't need to be different for KinD vs. on cloud. If any specific container needs different requirements, it should have them specified in the relevant CUE file for that environment.
</blockquote></details>

The reason why I created this is that other people also have memory issues when deploying KinD in the current configs. I can remove it for now and tackle it in a separate PR
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/CsvEventQuery.kt` line 51 at r32](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669#-NCRFCj6Axq7AkivcHI5:-NCWbe7R3hqT9Yw8U-6q:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a60caaa69e553a7443ec10ba518c38605133242f/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/CsvEventQuery.kt#L51)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Rather than doing this on class init, read it in using a lazy delegated property instead. That way we won't initialize until the first call to `getUserVirtualIds`, which should give time to copy the CSV file into the volume without needing retry logic here.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/ForwardStorageEdpSimulatorRunner.kt` line 33 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669#-N9nd6A_-OOTmmiPzlJy:-NCWbg4oBclv-q0FL0AQ:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ac847d1b211e5b417c5fe8b5150b7eff83622b25/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/ForwardStorageEdpSimulatorRunner.kt#L33)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The comments above are still relevant. This should be a property of type `File?` and not be a stringly-typed File-or-magic-sentinel-string. I'd name it something like "--events-csv" so it's clear that specifying it is what triggers use of a CSV file.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-09-22 17:49 UTC, SanjayVas requested changes
> Reviewed 5 of 9 files at r34, 6 of 10 files at r35, 14 of 15 files at r37, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669)* status: 32 of 33 files reviewed, 9 unresolved discussions (waiting on @duliomatos1, @iverson52000, @matthewclegg, @riemanli, and @SanjayVas)

___
*[`src/main/k8s/local/README.md` line 224 at r32](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669#-NCaGiiO8Ltm8dLLOE0P:-NCaGiiP4wM1fzGIS6pO:bfhq870) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a60caaa69e553a7443ec10ba518c38605133242f/src/main/k8s/local/README.md#L224)):*
> ```Markdown
> Executing requisitionFulfillingWorkflow...` to show up which indicates it's
> ready to accept requests
> ```

nit: technically the EDP simulator doesn't "accept requests", as it doesn't contain a server. It just polls for requisitions.



_Code quote:_
```Markdown
accept requests
```
___
*[`src/main/k8s/testing/secretfiles/resource_requirements_kind.yaml` line 23 at r32](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669#-NCRIVArCw5l5myIYTFs:-NCaGsWfAEyFO_jRIxoH:bd6lwq4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a60caaa69e553a7443ec10ba518c38605133242f/src/main/k8s/testing/secretfiles/resource_requirements_kind.yaml#L23)):*
> I can remove it for now and tackle it in a separate PR

That would be preferred, as it may be indicative of other issues. Everything is running fine for me (albeit with my latest fixes that haven't been merged) with 256Mi default, 384Mi on Duchy spanner servers, 512Mi on Kingdom spanner server, and 2Gi on Mill. I would expect that only the EDP simulator should need more memory to deal with large CSV files, unless this is also leading to sketches that the Mill would need more memory to handle.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/ForwardStorageEdpSimulatorRunner.kt` line 33 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669#-N9nd6A_-OOTmmiPzlJy:-NCaIDglADMS2UkHFYa4:bdyna00) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ac847d1b211e5b417c5fe8b5150b7eff83622b25/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/ForwardStorageEdpSimulatorRunner.kt#L33)):*
<details><summary><i>Previously, iverson52000 (Albert Hsu) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

The **only** thing that eventsCsv should contain is the File path to an actual CSV file. There should not be any magic/sentinel values in it to control other behavior.

Therefore the option should be optional to control whether the CSV file is used. (This is assuming you don't want to just split the binaries again so you have one that depends on CsvEventQuery and requires a CSV file, and another that depends on RandomEventQuery and doesn't have that option).

```kotlin
  @CommandLine.Option(
    names = ["--events-csv"],
    description =
      [
        "A filepath to a CSV file specifying the event data that will be returned by this simulator"
      ],
  )
  var eventsCsv: File? = null
    private set
```


<!-- Sent from Reviewable.io -->

2022-09-23 17:29 UTC, iverson52000 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669)* status: 6 of 33 files reviewed, 8 unresolved discussions (waiting on @duliomatos1, @matthewclegg, @riemanli, and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/ForwardStorageEdpSimulatorRunner.kt` line 33 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669#-N9nd6A_-OOTmmiPzlJy:-NCfNWQp3TefOdLcUKrX:b-fitt1r) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ac847d1b211e5b417c5fe8b5150b7eff83622b25/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/ForwardStorageEdpSimulatorRunner.kt#L33)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The **only** thing that eventsCsv should contain is the File path to an actual CSV file. There should not be any magic/sentinel values in it to control other behavior.

Therefore the option should be optional to control whether the CSV file is used. (This is assuming you don't want to just split the binaries again so you have one that depends on CsvEventQuery and requires a CSV file, and another that depends on RandomEventQuery and doesn't have that option).

```kotlin
  @CommandLine.Option(
    names = ["--events-csv"],
    description =
      [
        "A filepath to a CSV file specifying the event data that will be returned by this simulator"
      ],
  )
  var eventsCsv: File? = null
    private set
```
</blockquote></details>

Change to use optional `--events-csv` flag
___
*[`src/main/k8s/local/edp_simulators_csv.cue` line 1 at r32](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669#-NCRJIZWD7dUs3QUDyZI:-NCfO6HU8xTlu3AJ_dOW:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a60caaa69e553a7443ec10ba518c38605133242f/src/main/k8s/local/edp_simulators_csv.cue#L1)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Rather than having a whole separate copy of the file, utilize CUE's union capabilities. Create a cue_library for the local edp_simulators.cue and depend on that, just overriding the field that triggers CSV.
</blockquote></details>

Done.
___
*[`src/main/k8s/testing/secretfiles/resource_requirements_kind.yaml` line 23 at r32](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669#-NCRIVArCw5l5myIYTFs:-NCfO7Ix5rfxclWBQ7Eq:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a60caaa69e553a7443ec10ba518c38605133242f/src/main/k8s/testing/secretfiles/resource_requirements_kind.yaml#L23)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> I can remove it for now and tackle it in a separate PR

That would be preferred, as it may be indicative of other issues. Everything is running fine for me (albeit with my latest fixes that haven't been merged) with 256Mi default, 384Mi on Duchy spanner servers, 512Mi on Kingdom spanner server, and 2Gi on Mill. I would expect that only the EDP simulator should need more memory to deal with large CSV files, unless this is also leading to sketches that the Mill would need more memory to handle.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-09-26 19:54 UTC, SanjayVas requested changes
> Reviewed 2 of 16 files at r42, 4 of 9 files at r44, 5 of 10 files at r45, 13 of 14 files at r47, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669)* status: 30 of 33 files reviewed, 12 unresolved discussions (waiting on @duliomatos1, @iverson52000, @matthewclegg, @riemanli, and @SanjayVas)

___
*[`src/main/k8s/local/BUILD.bazel` line 82 at r47](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669#-NCvFrpHBU-wLDQh7aFR:-NCvFrpHBU-wLDQh7aFS:b-x7br5s) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/15a03a24e5d4020080b0655897e022f185563bcb/src/main/k8s/local/BUILD.bazel#L82)):*
> ```Starlark
> cue_dump(
>     name = "edp_simulators",
>     srcs = None,
> ```

nit: you can just leave out the `srcs` attr rather than explicitly setting to `None`



_Code quote:_
```Starlark
 srcs = None,
```
___
*[`src/main/k8s/local/edp_simulators.cue` line 15 at r47](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669#-NCvGOuU7RsD5loTLAac:-NCvGOuVEbDNO0EJ0Y-z:bni94oc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/15a03a24e5d4020080b0655897e022f185563bcb/src/main/k8s/local/edp_simulators.cue#L15)):*
> ```CUE
> // limitations under the License.
> 
> package k8s
> ```

I think there may be some confusion re: my previous comment.

What I had intended was to still have two separate CUE files, just that the CSV one would depend on the base one and only override the parts that it needed to. That way, things like the increased memory requirement wouldn't be applied to the non-CSV version.
___
*[`src/main/k8s/local/edp_simulators.cue` line 60 at r47](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669#-NCvHM864QvjdTzGdTKR:-NCvHM864QvjdTzGdTKS:b4p3h8i) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/15a03a24e5d4020080b0655897e022f185563bcb/src/main/k8s/local/edp_simulators.cue#L60)):*
> ```CUE
> 			]
> 			_additional_args: [...string]
> 			if _eventsCsvPath != _|_ {
> ```

`null`

This won't ever be bottom (`_|_`) because the field isn't optional, and instead was specified to be either `null` or a tagged string. Though if you follow the comment above, you can have this be non-optional.



_Code quote:_
```CUE
_|_
```
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/CsvEventQuery.kt` line 54 at r47](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669#-NCvI6reD4VSOSx6DkUi:-NCvI6rfE85NAuTQwsp8:bb5jew3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/15a03a24e5d4020080b0655897e022f185563bcb/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/CsvEventQuery.kt#L54)):*
> ```Kotlin
> 
>     logger.info("Reading data from CSV file $file...")
>     val fileReader = FileReader(file.toString())
> ```

See https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.io/java.io.-file/reader.html



_Suggestion:_
```Kotlin
    file.reader().use { fileReader ->
```
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/CsvEventQuery.kt` line 76 at r47](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669#-NCvIZa7-5ePtQmisaG_:-NCvIZa7-5ePtQmisaGa:b-haduo4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/15a03a24e5d4020080b0655897e022f185563bcb/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/CsvEventQuery.kt#L76)):*
> ```Kotlin
>   /** Generates Ids by applying filter on events */
>   override fun getUserVirtualIds(eventFilter: EventFilter): Sequence<Long> {
>     if (edpDisplayName != "testing" && !this::vidsList.isInitialized) readCsvFile()
> ```

No magic strings!

Everything should be tested using the public API. If you need different behavior, it should be controlled by e.g. swapping in a different test dependency. That said, I don't know why you'd need to here. You can easily stick your test file as a data dependency and read it from Runfiles in the test.



_Code quote:_
```Kotlin
edpDisplayName != "testing"
```
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/ForwardStorageEdpSimulatorRunner.kt` line 37 at r47](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669#-NCvLSkT9c-Zgf8f9H5W:-NCvLSkT9c-Zgf8f9H5X:b-6uenzb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/15a03a24e5d4020080b0655897e022f185563bcb/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/ForwardStorageEdpSimulatorRunner.kt#L37)):*
> ```Kotlin
>     description =
>       [
>         "A filepath to a CSV file specifying the event data that will be returned by this simulator"
> ```

nit: add a line here that if it isn't specified, random values will be used instead.


<!-- Sent from Reviewable.io -->

2022-09-28 16:41 UTC, iverson52000 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669)* status: 7 of 34 files reviewed, 11 unresolved discussions (waiting on @duliomatos1, @iverson52000, @matthewclegg, @riemanli, and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/CsvEventQuery.kt` line 54 at r47](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669#-NCvI6reD4VSOSx6DkUi:-ND3xDpSBjOOGQdjt6mb:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/15a03a24e5d4020080b0655897e022f185563bcb/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/CsvEventQuery.kt#L54)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

See https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.io/java.io.-file/reader.html
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/CsvEventQuery.kt` line 76 at r47](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669#-NCvIZa7-5ePtQmisaG_:-ND3xPJuEVzjLp-3SDvK:b5o2h2z) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/15a03a24e5d4020080b0655897e022f185563bcb/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/CsvEventQuery.kt#L76)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

No magic strings!

Everything should be tested using the public API. If you need different behavior, it should be controlled by e.g. swapping in a different test dependency. That said, I don't know why you'd need to here. You can easily stick your test file as a data dependency and read it from Runfiles in the test.
</blockquote></details>

Change to use a testing CSV file in unit test
___
*[`src/main/k8s/local/edp_simulators.cue` line 15 at r47](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669#-NCvGOuU7RsD5loTLAac:-ND3xL870-k6NmnpI_vX:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/15a03a24e5d4020080b0655897e022f185563bcb/src/main/k8s/local/edp_simulators.cue#L15)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I think there may be some confusion re: my previous comment.

What I had intended was to still have two separate CUE files, just that the CSV one would depend on the base one and only override the parts that it needed to. That way, things like the increased memory requirement wouldn't be applied to the non-CSV version.
</blockquote></details>

Done.
___
*[`src/main/k8s/local/edp_simulators.cue` line 60 at r47](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669#-NCvHM864QvjdTzGdTKR:-ND3xMoG4ckH9y9Pn4kQ:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/15a03a24e5d4020080b0655897e022f185563bcb/src/main/k8s/local/edp_simulators.cue#L60)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

`null`

This won't ever be bottom (`_|_`) because the field isn't optional, and instead was specified to be either `null` or a tagged string. Though if you follow the comment above, you can have this be non-optional.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-09-28 17:24 UTC, SanjayVas requested changes
> Reviewed 4 of 9 files at r49, 6 of 10 files at r50, 17 of 17 files at r52, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669)* status: all files reviewed, 18 unresolved discussions (waiting on @duliomatos1, @iverson52000, @matthewclegg, @riemanli, and @SanjayVas)

___
*[`src/main/k8s/local/README.md` line 239 at r52](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669#-ND43GRY84G51lFkj95O:-ND43C7a-UW41ugX0kEX:bq8bpr8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/08b5b223a3f15ab3e4ed263a4f7703d75a1f5bba/src/main/k8s/local/README.md#L239)):*
> First, update `_eventsCsv` in`//src/main/k8s/local/edp_simulators_csv.cue`.

One shouldn't need to do this unless they want to point to a different file. Instead of having this line, modify the copy command to use the hard-coded filename for the destination.
___
*[`src/main/k8s/local/README.md` line 240 at r52](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669#-ND43eSS9PxTV5kC5gpq:-ND43eSS9PxTV5kC5gpr:b-rchdty) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/08b5b223a3f15ab3e4ed263a4f7703d75a1f5bba/src/main/k8s/local/README.md#L240)):*
> bazel command

Which command? `build`? `run`?
___
*[`src/main/k8s/local/README.md` line 240 at r52](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669#-ND444JIByNDsLEeE_Fc:-ND444JIByNDsLEeE_Fd:bq2l51o) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/08b5b223a3f15ab3e4ed263a4f7703d75a1f5bba/src/main/k8s/local/README.md#L240)):*
> ```Markdown
> To use `CsvEventQuery`, you need to copy the CSV files you want to use from your
> local machine to the edp containers. First, update `_eventsCsv` in
> `//src/main/k8s/local/edp_simulators_csv.cue`. Then after running the bazel
> ```

This isn't how we reference files. You can instead use a Markdown relative link.



_Code quote:_
```Markdown
`//src/main/k8s/local/edp_simulators_csv.cue`
```
___
*[`src/main/k8s/local/README.md` line 241 at r52](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669#-ND43lOP11RK7EWoguRU:-ND43lOQ4tkFTorpgiJ4:b-8n00ub) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/08b5b223a3f15ab3e4ed263a4f7703d75a1f5bba/src/main/k8s/local/README.md#L241)):*
> all six edp deployments

This isn't strictly necessary. You can copy the file for each simulator pod as soon as it's running. You need not wait for them all.



_Code quote:_
```Markdown
all six edp deployments
```
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/ForwardStorageEdpSimulatorRunner.kt` line 67 at r52](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669#-ND44u35Cjv4Las0JvA8:-ND44u35Cjv4Las0JvA9:bxuylnu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/08b5b223a3f15ab3e4ed263a4f7703d75a1f5bba/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/ForwardStorageEdpSimulatorRunner.kt#L67)):*
> ```Kotlin
>         )
>       } else {
>         CsvEventQuery(flags.dataProviderDisplayName, eventsCsv!!)
> ```

nit: Smart casting should take care of this for you. You may need to copy the eventsCsv property to a local `val` and use that so that the compiler knows it cannot change after the check.



_Code quote:_
```Kotlin
eventsCsv!!
```
___
*[`src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/CsvEventQueryTest.kt` line 42 at r52](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669#-ND45Jns3ARjzVBeBjhx:-ND45Jns3ARjzVBeBjhy:buc3kym) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/08b5b223a3f15ab3e4ed263a4f7703d75a1f5bba/src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/CsvEventQueryTest.kt#L42)):*
> ```Kotlin
>     "dataprovider",
>   )
> const val fileName = "CsvEventQueryTestEvents.csv"
> ```

private
___
*[`src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/CsvEventQueryTest.kt` line 42 at r52](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669#-ND45MzLABzGNvNpk7vy:-ND45MzLABzGNvNpk7vz:b-ry54dq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/08b5b223a3f15ab3e4ed263a4f7703d75a1f5bba/src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/CsvEventQueryTest.kt#L42)):*
> ```Kotlin
>     "dataprovider",
>   )
> const val fileName = "CsvEventQueryTestEvents.csv"
> ```

const case



_Suggestion:_
```Kotlin
 FILE_NAME
```
___
*[`src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/CsvEventQueryTest.kt` line 45 at r52](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669#-ND45WJQ2NphfS8wY12u:-ND45WJR9_dOvq-61DLG:b-qoloro) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/08b5b223a3f15ab3e4ed263a4f7703d75a1f5bba/src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/CsvEventQueryTest.kt#L45)):*
> ```Kotlin
> private val FILE: File = File(getRuntimePath(directoryPath.resolve(fileName)).toString())
> 
> private const val EDP1 = "edp1"
> ```

nit: maybe EDP1_DISPLAY_NAME or `EDP_DISPLAY_NAME`



_Code quote:_
```Kotlin
EDP1
```
___
*[`src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/CsvEventQueryTest.kt` line 63 at r52](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669#-ND45hHz89sfn3iZ72l4:-ND45hHz89sfn3iZ72l5:b-dvmup6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/08b5b223a3f15ab3e4ed263a4f7703d75a1f5bba/src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/CsvEventQueryTest.kt#L63)):*
> ```Kotlin
> class CsvEventQueryTest {
>   companion object {
>     @JvmStatic private val eventQuery = CsvEventQuery(EDP1, FILE)
> ```

Shouldn't need this annotation unless you're using `@BeforeClass`



_Code quote:_
```Kotlin
@JvmStatic 
```
___
*[`src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/CsvEventQueryTest.kt` line 68 at r52](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669#-ND46YTp9vni77Gc8sSi:-ND46YTp9vni77Gc8sSj:b15lui7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/08b5b223a3f15ab3e4ed263a4f7703d75a1f5bba/src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/CsvEventQueryTest.kt#L68)):*
> ```Kotlin
>   @Test
>   fun `filters when no matching conditions`() {
>     val userVids = eventQuery.getUserVirtualIds(NONMATCHING_EVENT_FILTER)
> ```

nit: explicit types where not obvious.  I had to look up that this is `Sequence<Long>`
___
*[`src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/CsvEventQueryTest.kt` line 77 at r52](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669#-ND464xR8ozX5FLfxW3a:-ND464xR8ozX5FLfxW3b:b-fzcmzh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/08b5b223a3f15ab3e4ed263a4f7703d75a1f5bba/src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/CsvEventQueryTest.kt#L77)):*
> ```Kotlin
>     val userVids = eventQuery.getUserVirtualIds(MATCHING_EVENT_FILTER)
>     assertThat(userVids.toList().sorted()).isEqualTo(matchingVids.sorted())
>   }
> ```

Make use of `IterableSubject`



_Suggestion:_
```Kotlin
assertThat(userVids.toList()).containsExactlyElementsIn(matchingVids)
```


<!-- Sent from Reviewable.io -->

2022-09-28 22:26 UTC, iverson52000 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669)* status: all files reviewed, 18 unresolved discussions (waiting on @duliomatos1, @iverson52000, @matthewclegg, @riemanli, and @SanjayVas)

___
*[`src/main/k8s/local/README.md` line 239 at r52](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669#-ND43GRY84G51lFkj95O:-ND5AmFA0tpNRAS2pJMM:bhkpxso) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/08b5b223a3f15ab3e4ed263a4f7703d75a1f5bba/src/main/k8s/local/README.md#L239)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> First, update `_eventsCsv` in`//src/main/k8s/local/edp_simulators_csv.cue`.

One shouldn't need to do this unless they want to point to a different file. Instead of having this line, modify the copy command to use the hard-coded filename for the destination.
</blockquote></details>

Do you mean the CSV file name the user wants to use should be set to `synthetic-labelled-events.csv` first so `_eventsCsv` doesn't have to be changed?
Then in the instruction of kubectl cp command, I can change to
```
kubectl cp </path/to/your/csvfiles/synthetic-labelled-events.csv> <edp-podname>:/data/csvfiles
```


<!-- Sent from Reviewable.io -->

2022-09-28 22:53 UTC, SanjayVas requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669)* status: all files reviewed, 18 unresolved discussions (waiting on @duliomatos1, @iverson52000, @matthewclegg, @riemanli, and @SanjayVas)

___
*[`src/main/k8s/local/README.md` line 239 at r52](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669#-ND43GRY84G51lFkj95O:-ND5HooE7vTnWzOoPe-N:bls6ws2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/08b5b223a3f15ab3e4ed263a4f7703d75a1f5bba/src/main/k8s/local/README.md#L239)):*
<details><summary><i>Previously, iverson52000 (Albert Hsu) wrote…</i></summary><blockquote>

Do you mean the CSV file name the user wants to use should be set to `synthetic-labelled-events.csv` first so `_eventsCsv` doesn't have to be changed?
Then in the instruction of kubectl cp command, I can change to
```
kubectl cp </path/to/your/csvfiles/synthetic-labelled-events.csv> <edp-podname>:/data/csvfiles
```

</blockquote></details>

Close. I assume `kubectl cp` should work similarly to `cp` in that you can specify the destination file name. If you do that, then it doesn't matter what your local file is named.

```shell
kubectl cp </path/to/your/file.csv> <edp-podname>:/data/csvfiles/synthetic-labelled-events.csv
```


<!-- Sent from Reviewable.io -->

2022-09-29 17:11 UTC, iverson52000 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669)* status: 7 of 34 files reviewed, 14 unresolved discussions (waiting on @duliomatos1, @iverson52000, @matthewclegg, @riemanli, and @SanjayVas)

___
*[`src/main/k8s/local/README.md` line 239 at r52](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669#-ND43GRY84G51lFkj95O:-ND9Chkj4wAoVQMJGOG9:b-pwiey) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/08b5b223a3f15ab3e4ed263a4f7703d75a1f5bba/src/main/k8s/local/README.md#L239)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Close. I assume `kubectl cp` should work similarly to `cp` in that you can specify the destination file name. If you do that, then it doesn't matter what your local file is named.

```shell
kubectl cp </path/to/your/file.csv> <edp-podname>:/data/csvfiles/synthetic-labelled-events.csv
```

</blockquote></details>

Oh! This is a more robust way to do it. Thanks!
___
*[`src/main/k8s/local/README.md` line 240 at r52](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669#-ND43eSS9PxTV5kC5gpq:-ND9CtahAci46uLxNvam:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/08b5b223a3f15ab3e4ed263a4f7703d75a1f5bba/src/main/k8s/local/README.md#L240)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> bazel command

Which command? `build`? `run`?
</blockquote></details>

Done.
___
*[`src/main/k8s/local/README.md` line 241 at r52](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669#-ND43lOP11RK7EWoguRU:-ND9CwVaAAyHwGMgNgaQ:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/08b5b223a3f15ab3e4ed263a4f7703d75a1f5bba/src/main/k8s/local/README.md#L241)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> all six edp deployments

This isn't strictly necessary. You can copy the file for each simulator pod as soon as it's running. You need not wait for them all.
</blockquote></details>

Done.
___
*[`src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/CsvEventQueryTest.kt` line 42 at r52](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669#-ND45Jns3ARjzVBeBjhx:-ND9CUvn1SfwIC_9_7SA:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/08b5b223a3f15ab3e4ed263a4f7703d75a1f5bba/src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/CsvEventQueryTest.kt#L42)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

private
</blockquote></details>

Done.
___
*[`src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/CsvEventQueryTest.kt` line 42 at r52](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669#-ND45MzLABzGNvNpk7vy:-ND9CzT3A-sXv1_qZB4Y:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/08b5b223a3f15ab3e4ed263a4f7703d75a1f5bba/src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/CsvEventQueryTest.kt#L42)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

const case
</blockquote></details>

Done.
___
*[`src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/CsvEventQueryTest.kt` line 63 at r52](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669#-ND45hHz89sfn3iZ72l4:-ND9CeEg2RHi_1motPIQ:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/08b5b223a3f15ab3e4ed263a4f7703d75a1f5bba/src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/CsvEventQueryTest.kt#L63)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Shouldn't need this annotation unless you're using `@BeforeClass`
</blockquote></details>

Done.
___
*[`src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/CsvEventQueryTest.kt` line 77 at r52](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669#-ND464xR8ozX5FLfxW3a:-ND9CelQ-0hXtzp4Vwuw:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/08b5b223a3f15ab3e4ed263a4f7703d75a1f5bba/src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/CsvEventQueryTest.kt#L77)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Make use of `IterableSubject`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-09-29 19:51 UTC, SanjayVas requested changes
> Reviewed 4 of 9 files at r54, 6 of 10 files at r55, 14 of 17 files at r57, 4 of 4 files at r58, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669)* status: all files reviewed, 10 unresolved discussions (waiting on @duliomatos1, @iverson52000, @matthewclegg, and @riemanli)

___
*[`src/main/k8s/local/BUILD.bazel` line 72 at r58](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669#-ND9gK1kAcy_0JkL8_JT:-ND9gK1lCFpgTS7UdpYu:b-t5uvb6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/795486ac5b9eabb24b24940f77f2d53c9213c22a/src/main/k8s/local/BUILD.bazel#L72)):*
> ```Starlark
> 
> cue_library(
>     name = "edp_simulators_library",
> ```

nit: `edp_simulators_cue` would parallel conventions for other language-specific libraries (e.g. `proto_library` targets use the `_proto` suffix by convention)

That said, no big deal since we don't have a convention established (meaning we have existing cue_library targets that don't follow this convention). This is the first case where we've had the same name for both the library and the export.



_Code quote:_
```Starlark
edp_simulators_library
```
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/CsvEventQuery.kt` line 59 at r58](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669#-ND9jpM89oOUNotclTsP:-ND9jpM89oOUNotclTsQ:bwlamlb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/795486ac5b9eabb24b24940f77f2d53c9213c22a/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/CsvEventQuery.kt#L59)):*
> ```Kotlin
>         var row = reader.readNext()
>         while (row != null) {
>           if (row[edpIdIndex] == edpDisplayName.last().toString()) {
> ```

Don't try to parse this from the display name. There's no guarantee that display names follow any naming convention.

This should be a separate command-line option. See the `--publisher-id` option in `GcsEdpSimulatorRunner.kt`. You might be able to use [argument groups](https://picocli.info/#_argument_groups) to make this option required iff `--events-csv` is specified.

Alternatively, have the CSV file contain the EDP display name rather than a "publisher ID"/"EDP number". (This is distinct from the DataProvider ID, which is a string that will be different for each run).



_Code quote:_
```Kotlin
edpDisplayName.last()
```
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/ForwardStorageEdpSimulatorRunner.kt` line 61 at r58](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669#-ND9ijgwARr-RCREPE5M:-ND9ijgwARr-RCREPE5N:b-kbt06s) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/795486ac5b9eabb24b24940f77f2d53c9213c22a/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/ForwardStorageEdpSimulatorRunner.kt#L61)):*
> ```Kotlin
> 
>   override fun run() {
>     val eventsCsv = eventsCsv
> ```

nit: explicit type
___
*[`src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/CsvEventQueryTest.kt` line 43 at r58](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669#-ND9jBee3LwCf4yQDmEL:-ND9jBee3LwCf4yQDmEM:undefined) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/795486ac5b9eabb24b24940f77f2d53c9213c22a/src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/CsvEventQueryTest.kt#L43)):*
> ```Kotlin
>   )
> private const val FILE_NAME = "CsvEventQueryTestEvents.csv"
> private val FILE: File = File(getRuntimePath(directoryPath.resolve(FILE_NAME)).toString())
> ```





_Suggestion:_
```Kotlin
getRuntimePath(directoryPath.resolve(FILE_NAME)).toFile()
```


<!-- Sent from Reviewable.io -->

2022-10-03 16:38 UTC, iverson52000 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669)* status: all files reviewed, 10 unresolved discussions (waiting on @duliomatos1, @iverson52000, @matthewclegg, @riemanli, and @SanjayVas)

___
*[`src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/CsvEventQueryTest.kt` line 43 at r58](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669#-ND9jBee3LwCf4yQDmEL:-NDTgwSEDr3Ir95bmdcm:bukp20y) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/795486ac5b9eabb24b24940f77f2d53c9213c22a/src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/CsvEventQueryTest.kt#L43)):*
> ```Kotlin
>   )
> private const val FILE_NAME = "CsvEventQueryTestEvents.csv"
> private val FILE: File = File(getRuntimePath(directoryPath.resolve(FILE_NAME)).toString())
> ```

If I try to do this then compiler complains `Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type Path?`. (getRuntimePath returns Path?). 
I have to do `getRuntimePath(directoryPath.resolve(FILE_NAME))!!.toFile()` Is that OK?


<!-- Sent from Reviewable.io -->

2022-10-03 17:54 UTC, SanjayVas requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669)* status: all files reviewed, 10 unresolved discussions (waiting on @duliomatos1, @iverson52000, @matthewclegg, and @riemanli)

___
*[`src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/CsvEventQueryTest.kt` line 43 at r58](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669#-ND9jBee3LwCf4yQDmEL:-NDTyhlG6kEQIoQ_HUzK:b7gyn4n) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/795486ac5b9eabb24b24940f77f2d53c9213c22a/src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/CsvEventQueryTest.kt#L43)):*
<details><summary><i>Previously, iverson52000 (Albert Hsu) wrote…</i></summary><blockquote>

If I try to do this then compiler complains `Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type Path?`. (getRuntimePath returns Path?). 
I have to do `getRuntimePath(directoryPath.resolve(FILE_NAME))!!.toFile()` Is that OK?
</blockquote></details>

That's fine. The main point was using `toFile()` rather than the `File` constructor w/toString.


<!-- Sent from Reviewable.io -->

2022-10-03 19:48 UTC, iverson52000 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669)* status: 7 of 34 files reviewed, 9 unresolved discussions (waiting on @duliomatos1, @iverson52000, @matthewclegg, @riemanli, and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/CsvEventQuery.kt` line 59 at r58](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669#-ND9jpM89oOUNotclTsP:-NDUNgUMEbgFd-sJBuqr:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/795486ac5b9eabb24b24940f77f2d53c9213c22a/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/CsvEventQuery.kt#L59)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Don't try to parse this from the display name. There's no guarantee that display names follow any naming convention.

This should be a separate command-line option. See the `--publisher-id` option in `GcsEdpSimulatorRunner.kt`. You might be able to use [argument groups](https://picocli.info/#_argument_groups) to make this option required iff `--events-csv` is specified.

Alternatively, have the CSV file contain the EDP display name rather than a "publisher ID"/"EDP number". (This is distinct from the DataProvider ID, which is a string that will be different for each run).
</blockquote></details>

Done.
___
*[`src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/CsvEventQueryTest.kt` line 43 at r58](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669#-ND9jBee3LwCf4yQDmEL:-NDUNiwy6-KMJqI0JgMD:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/795486ac5b9eabb24b24940f77f2d53c9213c22a/src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/CsvEventQueryTest.kt#L43)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

That's fine. The main point was using `toFile()` rather than the `File` constructor w/toString.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-10-03 21:34 UTC, SanjayVas requested changes
> Reviewed 4 of 9 files at r60, 6 of 10 files at r61, 17 of 17 files at r63, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669)* status: all files reviewed, 14 unresolved discussions (waiting on @duliomatos1, @iverson52000, @matthewclegg, and @riemanli)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/CsvEventQuery.kt` line 41 at r63](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669#-NDUgf01Els_fc0klmb9:-NDUgf01Els_fc0klmbA:b-tonafj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/669122b5c76006f24be419b3d3ad656cad7ba864/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/CsvEventQuery.kt#L41)):*
> ```Kotlin
> class CsvEventQuery(private val publisherId: Int, private val file: File) : EventQuery() {
>   private val edpIdIndex = 0
>   private val sexIndex = 2
> ```

These should be constants.



_Code quote:_
```Kotlin
  private val edpIdIndex = 0
  private val sexIndex = 2
  private val ageGroupIndex = 3
  private val vidIndex = 7
```
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/CsvEventQuery.kt` line 48 at r63](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669#-NDUkI7S9MQj--FUtHak:-NDUkI7S9MQj--FUtHal:b-slseay) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/669122b5c76006f24be419b3d3ad656cad7ba864/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/CsvEventQuery.kt#L48)):*
> ```Kotlin
>   private lateinit var eventsList: MutableList<TestEvent>
> 
>   private fun readCsvFile() {
> ```

nit: annotate this with `@Throws(IOException::class)` or `@Blocking` so it's clear to callers that this method does blocking file I/O. (Kotlin uses this as a signal for the "inappropriate blocking method call" warning).
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/CsvEventQuery.kt` line 57 at r63](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669#-NDUgTxyAMZdytal58Nz:-NDUgTxyAMZdytal58O-:b-82iqrd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/669122b5c76006f24be419b3d3ad656cad7ba864/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/CsvEventQuery.kt#L57)):*
> ```Kotlin
>       val csvReader = CSVReaderBuilder(fileReader).withSkipLines(1).build()
>       csvReader.use { reader ->
>         var row = reader.readNext()
> ```

nit: CsvReader implements `Iterable`, so you can just use a for-each loop.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/CsvEventQuery.kt` line 59 at r63](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669#-NDUfFAyDQkwyUMoAMYb:-NDUfFAyDQkwyUMoAMYc:bu56cq4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/669122b5c76006f24be419b3d3ad656cad7ba864/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/CsvEventQuery.kt#L59)):*
> ```Kotlin
>         var row = reader.readNext()
>         while (row != null) {
>           if (row[edpIdIndex] == publisherId.toString()) {
> ```

Parse the string value to an int rather than comparing strings. There's more than one way to represent a number as a string. e.g. the string "005" in CSV should still equal the integer `5`.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/CsvEventQuery.kt` line 73 at r63](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669#-NDUjEu01mR8eoKjVfOu:-NDUjEu01mR8eoKjVfOv:bog2cta) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/669122b5c76006f24be419b3d3ad656cad7ba864/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/CsvEventQuery.kt#L73)):*
> ```Kotlin
> 
>   /** Generates Ids by applying filter on events */
>   override fun getUserVirtualIds(eventFilter: EventFilter): Sequence<Long> {
> ```

This can be cleaned up in a separate PR, but this really should return `Flow` instead of `Sequence`. Since we use coroutines everywhere, that return type would allow implementations of this method to call suspending/async code. We'd then wrap the file system I/O in a `CoroutineContext` that satisfies `@BlockingExecutor`. See [`FileSystemStorageClient`](https://github.com/world-federation-of-advertisers/common-jvm/blob/main/src/main/kotlin/org/wfanet/measurement/storage/filesystem/FileSystemStorageClient.kt) for an example.



_Code quote:_
```Kotlin
Sequence<Long>
```
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/CsvEventQuery.kt` line 74 at r63](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669#-NDUiAu56_xVkgSL6ZB9:-NDUiAu56_xVkgSL6ZBA:bha106a) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/669122b5c76006f24be419b3d3ad656cad7ba864/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/CsvEventQuery.kt#L74)):*
> ```Kotlin
>   /** Generates Ids by applying filter on events */
>   override fun getUserVirtualIds(eventFilter: EventFilter): Sequence<Long> {
>     if (!this::vidsList.isInitialized) readCsvFile()
> ```

This isn't thread-safe. If we wanted to parallelize requisition fulfillment, then this could cause problems.

The simplest way to solve this would be to have a single data structure that holds both lists as a lazy property which calls readCsvFile to return that list. This is because the lazy initializer is itself thread-safe.



_Code quote:_
```Kotlin
if (!this::vidsList.isInitialized) readCsvFile()
```
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/ForwardStorageEdpSimulatorRunner.kt` line 48 at r63](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669#-NDUelsz6vmbBuJylfjr:-NDUelsz6vmbBuJylfjs:b-vj9c1v) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/669122b5c76006f24be419b3d3ad656cad7ba864/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/ForwardStorageEdpSimulatorRunner.kt#L48)):*
> ```Kotlin
>     description = ["ID of the publisher within the test dataset"],
>   )
>   var publisherId by Delegates.notNull<Int>()
> ```

This is incorrect. This field is optional and therefore should be nullable. This is why I was suggesting using an argument group to make it conditionally required. See https://picocli.info/#_mutually_dependent_options



_Code quote:_
```Kotlin
Delegates.notNull<Int>()
```


<!-- Sent from Reviewable.io -->

2022-10-04 16:50 UTC, iverson52000 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669)* status: 32 of 34 files reviewed, 12 unresolved discussions (waiting on @duliomatos1, @iverson52000, @matthewclegg, @riemanli, and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/CsvEventQuery.kt` line 41 at r63](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669#-NDUgf01Els_fc0klmb9:-NDYtj7jCttRJWA1cQR1:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/669122b5c76006f24be419b3d3ad656cad7ba864/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/CsvEventQuery.kt#L41)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

These should be constants.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/CsvEventQuery.kt` line 59 at r63](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669#-NDUfFAyDQkwyUMoAMYb:-NDYtmBd99vXrTvLZrte:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/669122b5c76006f24be419b3d3ad656cad7ba864/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/CsvEventQuery.kt#L59)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Parse the string value to an int rather than comparing strings. There's more than one way to represent a number as a string. e.g. the string "005" in CSV should still equal the integer `5`.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/CsvEventQuery.kt` line 73 at r63](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669#-NDUjEu01mR8eoKjVfOu:-NDYszen04xYCrQqm4Jh:bbxrlfk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/669122b5c76006f24be419b3d3ad656cad7ba864/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/CsvEventQuery.kt#L73)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This can be cleaned up in a separate PR, but this really should return `Flow` instead of `Sequence`. Since we use coroutines everywhere, that return type would allow implementations of this method to call suspending/async code. We'd then wrap the file system I/O in a `CoroutineContext` that satisfies `@BlockingExecutor`. See [`FileSystemStorageClient`](https://github.com/world-federation-of-advertisers/common-jvm/blob/main/src/main/kotlin/org/wfanet/measurement/storage/filesystem/FileSystemStorageClient.kt) for an example.
</blockquote></details>

Agree this should be tackled in a different PR
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/CsvEventQuery.kt` line 74 at r63](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669#-NDUiAu56_xVkgSL6ZB9:-NDYtFie7SBV4a1_NvrR:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/669122b5c76006f24be419b3d3ad656cad7ba864/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/CsvEventQuery.kt#L74)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This isn't thread-safe. If we wanted to parallelize requisition fulfillment, then this could cause problems.

The simplest way to solve this would be to have a single data structure that holds both lists as a lazy property which calls readCsvFile to return that list. This is because the lazy initializer is itself thread-safe.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/ForwardStorageEdpSimulatorRunner.kt` line 48 at r63](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669#-NDUelsz6vmbBuJylfjr:-NDYtGnhDJ4FovLFB-wJ:b9t08ea) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/669122b5c76006f24be419b3d3ad656cad7ba864/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/ForwardStorageEdpSimulatorRunner.kt#L48)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This is incorrect. This field is optional and therefore should be nullable. This is why I was suggesting using an argument group to make it conditionally required. See https://picocli.info/#_mutually_dependent_options
</blockquote></details>

I did try `ArgGroup` and thought it's a bit cumbersome so didn't implement it. But what you said make sense. Added the ArgGroup implementation for CsvEventQuery


<!-- Sent from Reviewable.io -->

2022-10-04 17:51 UTC, SanjayVas requested changes
> Reviewed 2 of 2 files at r64, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669)* status: all files reviewed, 10 unresolved discussions (waiting on @duliomatos1, @iverson52000, @matthewclegg, @riemanli, and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/CsvEventQuery.kt` line 81 at r64](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669#-NDZ4tuS0amIOAHrJtAh:-NDZ4tuS0amIOAHrJtAi:bxof3vn) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5de1ecc3cb9c566a0a78c0995ba50849f61cda8f/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/CsvEventQuery.kt#L81)):*
> ```Kotlin
>     return sequence {
>       vidAndEventList.forEach { vidAndEvent ->
>         if (EventFilters.matches(vidAndEvent.event as Message, program)) {
> ```

nit: unnecessary cast



_Code quote:_
```Kotlin
 as Message
```
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/ForwardStorageEdpSimulatorRunner.kt` line 48 at r63](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669#-NDUelsz6vmbBuJylfjr:-NDZ5Oxx7Wtuh6wnwpc1:bdin5le) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/669122b5c76006f24be419b3d3ad656cad7ba864/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/ForwardStorageEdpSimulatorRunner.kt#L48)):*
<details><summary><i>Previously, iverson52000 (Albert Hsu) wrote…</i></summary><blockquote>

I did try `ArgGroup` and thought it's a bit cumbersome so didn't implement it. But what you said make sense. Added the ArgGroup implementation for CsvEventQuery
</blockquote></details>

It's still not quite implemented correctly. When you use mutually-dependent options, the ArgGroup field itself becomes optional. It should therefore be

```kotlin
var csvDependent: CsvDependent? = null
  private set
```

The options then become required within that ArgGroup:

```kotlin
    @CommandLine.Option(
      names = ["--events-csv"],
      description =
        [
          "A filepath to a CSV file specifying the event data that will be returned by this simulator." +
            "If not specified, RandomEventQuery will be used"
        ],
      required = true,
    )
    lateinit var eventsCsv: File
      private set

    @set:CommandLine.Option(
      names = ["--publisher-id"],
      description = ["ID of the publisher within the test dataset. Required when --events-csv is set."],
      required = true,
    )
    var publisherId by Delegates.notNull<Int>()
      private set
```


<!-- Sent from Reviewable.io -->

2022-10-04 20:25 UTC, iverson52000 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669)* status: 32 of 34 files reviewed, 9 unresolved discussions (waiting on @duliomatos1, @iverson52000, @matthewclegg, @riemanli, and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/ForwardStorageEdpSimulatorRunner.kt` line 48 at r63](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669#-NDUelsz6vmbBuJylfjr:-NDZePec-Wkgj4u004Rb:be862bp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/669122b5c76006f24be419b3d3ad656cad7ba864/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/ForwardStorageEdpSimulatorRunner.kt#L48)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

It's still not quite implemented correctly. When you use mutually-dependent options, the ArgGroup field itself becomes optional. It should therefore be

```kotlin
var csvDependent: CsvDependent? = null
  private set
```

The options then become required within that ArgGroup:

```kotlin
    @CommandLine.Option(
      names = ["--events-csv"],
      description =
        [
          "A filepath to a CSV file specifying the event data that will be returned by this simulator." +
            "If not specified, RandomEventQuery will be used"
        ],
      required = true,
    )
    lateinit var eventsCsv: File
      private set

    @set:CommandLine.Option(
      names = ["--publisher-id"],
      description = ["ID of the publisher within the test dataset. Required when --events-csv is set."],
      required = true,
    )
    var publisherId by Delegates.notNull<Int>()
      private set
```
</blockquote></details>

Done. Just curious what does `@set` do? I see some `CommandLine.Option` has this prefix and some don't. Looked up the doc and didn't see a clear answer


<!-- Sent from Reviewable.io -->

2022-10-04 21:10 UTC, SanjayVas approved these changes
> Reviewed 2 of 2 files at r65, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669)* status: all files reviewed, 7 unresolved discussions (waiting on @duliomatos1, @iverson52000, @matthewclegg, and @riemanli)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/ForwardStorageEdpSimulatorRunner.kt` line 48 at r63](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/669#-NDUelsz6vmbBuJylfjr:-NDZoOhZ1_9tXbcsA40a:b-4uo3xi) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/669122b5c76006f24be419b3d3ad656cad7ba864/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/ForwardStorageEdpSimulatorRunner.kt#L48)):*
<details><summary><i>Previously, iverson52000 (Albert Hsu) wrote…</i></summary><blockquote>

Done. Just curious what does `@set` do? I see some `CommandLine.Option` has this prefix and some don't. Looked up the doc and didn't see a clear answer
</blockquote></details>

It has to do with how Kotlin properties are sometimes implemented in Java bytecode as a pair of getter and setter methods instead of a member field. When using the `notNull` property delegate, we need `@set:` so the annotation properly gets applied to the generated setter method.


<!-- Sent from Reviewable.io -->

2022-10-05 19:45 UTC, merged