Compute direct reach and frequency in EDP simulator
world-federation-of-advertisers/cross-media-measurement pull request #672
Opened 2022-08-23 20:15 UTC by iverson52000

2022-08-23 22:05 UTC, matthewclegg requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/672)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @iverson52000, @SanjayVas, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 564 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/672#-NABfggZ5pMCh3mhMDAV:-NABfggZ5pMCh3mhMDAW:bas53oo) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/04a643356c1d81700ddf8dd2f13ff37c85da4742/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L564)):*
> ```Kotlin
> 
>       vidList.forEach { vid -> frequency.addValue(vid) }
>       vidSet.forEach { vid ->
> ```

I wonder if something like the following would work:

```
val reachValue = vidList.toSet().size.toLong()
val frequencyMap = mutableMapOf<Long, Double>().withDefault(0.0)
vidList.groupingBy {it}.eachCount().forEach { (_, frequency) ->
  frequencyMap[frequency] += 1.0 / reachValue.toDouble()
}
return Pair(reachValue, frequencyMap)
```

https://kotlinlang.org/docs/collection-grouping.html
https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/each-count.html#
https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/with-default.html
___
*[`src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt` line 619 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/672#-NABiq_K7fIPdnLmR8FT:-NABiq_K7fIPdnLmR8FU:b-vwyrd5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/04a643356c1d81700ddf8dd2f13ff37c85da4742/src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt#L619)):*
> ```Kotlin
>       }
>     }
>   }
> ```

Please add a unit test for fullfillDirectReachAndFrequencyMeasurement.


<!-- Sent from Reviewable.io -->

2022-08-23 22:27 UTC, SanjayVas requested changes
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/672)* status: all files reviewed, 6 unresolved discussions (waiting on @iverson52000, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 432 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/672#-NABixaN816djbKcGuwq:-NABixaO1SEzU1YhFSjM:b-h12y73) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/04a643356c1d81700ddf8dd2f13ff37c85da4742/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L432)):*
> ```Kotlin
>     measurementSpec: MeasurementSpec
>   ) {
>     val vidList: MutableList<Long> = mutableListOf()
> ```

Do you need a separate mutable list? Can't you just change the expression below to return the resulting list using `flatMap`? e.g.


```kotlin
    val vidList: List<Long> =
      requisitionSpec.eventGroupsList.flatMap { eventGroup ->
        eventQuery.getUserVirtualIds(eventGroup.value.filter).filter { vid ->
          VidSampler(VID_SAMPLER_HASH_FUNCTION)
            .vidIsInSamplingBucket(
              vid,
              measurementSpec.vidSamplingInterval.start,
              measurementSpec.vidSamplingInterval.width
            )
        }
      }
```
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 438 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/672#-NABkrq30MoJFqgXmlSt:-NABkrq30MoJFqgXmlSu:b-9xgcjh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/04a643356c1d81700ddf8dd2f13ff37c85da4742/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L438)):*
> ```Kotlin
>         .getUserVirtualIds(eventGroup.value.filter)
>         .filter { vid ->
>           VidSampler(VID_SAMPLER_HASH_FUNCTION)
> ```

Does this need to be instantiated every loop, or can we have a single instance?



_Code quote:_
```Kotlin
VidSampler(VID_SAMPLER_HASH_FUNCTION)
```
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 557 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/672#-NABlPg16nAUa3ygxUHx:-NABlPg16nAUa3ygxUHy:b-kep923) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/04a643356c1d81700ddf8dd2f13ff37c85da4742/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L557)):*
> ```Kotlin
> 
>     fun calculateDirectReachAndFrequency(
>       vidList: MutableList<Long>
> ```

Avoid mutability where not needed. In general, don't overspecify the type of a collection param. e.g. if all you need to do is iterate, have your param type be `Iterable`. If you additionally need the size, use `Collection`.

If the param type is mutable, the assumption is that it's because the function is intended to mutate it and for the caller to observe the result of that mutation.



_Code quote:_
```Kotlin
MutableList<Long>
```
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 558 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/672#-NABmDH_DgNfVX51TB4f:-NABmDH_DgNfVX51TB4g:b-nxu05q) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/04a643356c1d81700ddf8dd2f13ff37c85da4742/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L558)):*
> ```Kotlin
>     fun calculateDirectReachAndFrequency(
>       vidList: MutableList<Long>
>     ): Pair<Long, Map<Long, Double>> {
> ```

nit: consider a more explicit type than pair

See go/kotlin/practices/pair (Google internal)



_Code quote:_
```Kotlin
Pair
```


<!-- Sent from Reviewable.io -->

2022-08-24 16:50 UTC, iverson52000 commented
*[`src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt` line 612 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/672#-NAF9IAUAXfruMGxU2z_:-NAFjNVf0D5epp-t62Ph:b-ctf2km) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/04a643356c1d81700ddf8dd2f13ff37c85da4742/src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt#L612)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

are the frequencies for 4L and 5L not expected to be included?
</blockquote></details>

Yes 4L and 5L are being reached one time so they are included in 1 reach?



_Code snippet:_
```Kotlin
// 1 reach -> 0.6(3/5)(VID 3L, 4L, 5L), 2 reach -> 0.2(1/5)(VID 2L), 3 reach -> 0.2(1/5)(VID 1L)
```


<!-- Sent from Reviewable.io -->

2022-08-24 17:21 UTC, stevenwarejones reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/672)* status: all files reviewed, 7 unresolved discussions (waiting on @iverson52000 and @tristanvuong2021)



<!-- Sent from Reviewable.io -->

2022-08-24 19:51 UTC, iverson52000 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/672)* status: 1 of 3 files reviewed, 7 unresolved discussions (waiting on @iverson52000, @matthewclegg, @SanjayVas, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 432 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/672#-NABixaN816djbKcGuwq:-NAGOrQz734cJF0vxQNd:b2p1bq8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/04a643356c1d81700ddf8dd2f13ff37c85da4742/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L432)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Do you need a separate mutable list? Can't you just change the expression below to return the resulting list using `flatMap`? e.g.


```kotlin
    val vidList: List<Long> =
      requisitionSpec.eventGroupsList.flatMap { eventGroup ->
        eventQuery.getUserVirtualIds(eventGroup.value.filter).filter { vid ->
          VidSampler(VID_SAMPLER_HASH_FUNCTION)
            .vidIsInSamplingBucket(
              vid,
              measurementSpec.vidSamplingInterval.start,
              measurementSpec.vidSamplingInterval.width
            )
        }
      }
```


</blockquote></details>

Modified the code based on SWJ's comment below
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 435 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/672#-NAF8mgf3p4boITr0SZm:-NAGOCGl-FEGe25v5zo9:b1ra9td) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/04a643356c1d81700ddf8dd2f13ff37c85da4742/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L435)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

what if the eventGroups overlap in some way? It would be better to get back a list of (eventId, virtualId), deduplicate that list and then merge
</blockquote></details>

So you mean we should check if there's duplicate `eventGroup.key` right? How about this change?
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 438 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/672#-NABkrq30MoJFqgXmlSt:-NAGO21X9ezvqCvbHGCV:blyumi2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/04a643356c1d81700ddf8dd2f13ff37c85da4742/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L438)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Does this need to be instantiated every loop, or can we have a single instance?
</blockquote></details>

No it should be single instance. Thanks for catching it
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 557 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/672#-NABlPg16nAUa3ygxUHx:-NAGOSKd5fusWodjjPNk:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/04a643356c1d81700ddf8dd2f13ff37c85da4742/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L557)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Avoid mutability where not needed. In general, don't overspecify the type of a collection param. e.g. if all you need to do is iterate, have your param type be `Iterable`. If you additionally need the size, use `Collection`.

If the param type is mutable, the assumption is that it's because the function is intended to mutate it and for the caller to observe the result of that mutation.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 564 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/672#-NABfggZ5pMCh3mhMDAV:-NAGOTmj5Tsq7sQ23Xqt:bfqg06v) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/04a643356c1d81700ddf8dd2f13ff37c85da4742/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L564)):*
<details><summary><i>Previously, matthewclegg (Matthew Clegg) wrote…</i></summary><blockquote>

I wonder if something like the following would work:

```
val reachValue = vidList.toSet().size.toLong()
val frequencyMap = mutableMapOf<Long, Double>().withDefault(0.0)
vidList.groupingBy {it}.eachCount().forEach { (_, frequency) ->
  frequencyMap[frequency] += 1.0 / reachValue.toDouble()
}
return Pair(reachValue, frequencyMap)
```

https://kotlinlang.org/docs/collection-grouping.html
https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/each-count.html#
https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/with-default.html
</blockquote></details>

It works with some modification. Thanks


<!-- Sent from Reviewable.io -->

2022-08-24 21:15 UTC, iverson52000 commented
*[`src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt` line 619 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/672#-NABiq_K7fIPdnLmR8FT:-NAGh3hL2TDmC3xdnT--:bf64kas) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/04a643356c1d81700ddf8dd2f13ff37c85da4742/src/test/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulatorTest.kt#L619)):*
<details><summary><i>Previously, matthewclegg (Matthew Clegg) wrote…</i></summary><blockquote>

Please add a unit test for fullfillDirectReachAndFrequencyMeasurement.
</blockquote></details>

Test is updated in `FrontendSimulator.kt`


<!-- Sent from Reviewable.io -->

2022-08-24 23:32 UTC, matthewclegg approved these changes
> Reviewed 1 of 2 files at r2, 3 of 4 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/672)* status: all files reviewed, 7 unresolved discussions (waiting on @iverson52000, @SanjayVas, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 432 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/672#-NABixaN816djbKcGuwq:-NAH8M8S9NGCVZHUS5Qf:bdsm6b7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/04a643356c1d81700ddf8dd2f13ff37c85da4742/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L432)):*
<details><summary><i>Previously, iverson52000 (Albert Hsu) wrote…</i></summary><blockquote>

Modified the code based on SWJ's comment below
</blockquote></details>

A possible suggestion, riffing on Sanjay's and SWJ's comments.  Something like the following might be more compact:

```
val vidList: List<Long> =
      requisitionSpec.eventGroupsList.flatMap { eventGroup ->
        eventQuery.getUserVirtualIds(eventGroup.value.filter).filter { vid ->
          VidSampler(VID_SAMPLER_HASH_FUNCTION)
            .vidIsInSamplingBucket(
              vid,
              measurementSpec.vidSamplingInterval.start,
              measurementSpec.vidSamplingInterval.width
            )
        }.map { vid -> Pair(eventGroup.key, vid)
      }.distinct().map { p -> p.secon}
```
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 560 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/672#-NAHAqsr55QF2p7l3zIl:-NAH9hXx56GJ-OmZ_RET:bwe7kiq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/70db9ced399cd4e41d31e836214d8138819c6ec8/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L560)):*
> ```Kotlin
>     }
> 
>     fun calculateDirectReachAndFrequency(vidList: List<Long>): Pair<Long, Map<Long, Double>> {
> ```

Consider changing the return type to Pair<Long, Map<Int, Double>>.  This results in a slight code simplification.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 568 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/672#-NAHB1R1-KAGm5qw7vdt:-NAH9tFB5lFLZEnEh-it:b-ak1t5g) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/70db9ced399cd4e41d31e836214d8138819c6ec8/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L568)):*
> ```Kotlin
>         .eachCount()
>         .forEach { (_, frequency) ->
>           frequencyMap[frequency.toLong()] = frequencyMap.getValue(frequency.toLong()) + 1.0
> ```

Consider changing this line as follows.  This would allow you to delete the for loop in the next three lines.

```
  frequencyMap[frequency] = (frequencyMap.getValue(frequency) + 1.0) / reachValue.toDouble()
```


<!-- Sent from Reviewable.io -->

2022-08-24 23:33 UTC, SanjayVas requested changes
> Reviewed 1 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/672)* status: all files reviewed, 5 unresolved discussions (waiting on @iverson52000, @matthewclegg, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 432 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/672#-NABixaN816djbKcGuwq:-NAH9KeL093BgKwuwj6s:b-dfjsho) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/04a643356c1d81700ddf8dd2f13ff37c85da4742/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L432)):*
<details><summary><i>Previously, matthewclegg (Matthew Clegg) wrote…</i></summary><blockquote>

A possible suggestion, riffing on Sanjay's and SWJ's comments.  Something like the following might be more compact:

```
val vidList: List<Long> =
      requisitionSpec.eventGroupsList.flatMap { eventGroup ->
        eventQuery.getUserVirtualIds(eventGroup.value.filter).filter { vid ->
          VidSampler(VID_SAMPLER_HASH_FUNCTION)
            .vidIsInSamplingBucket(
              vid,
              measurementSpec.vidSamplingInterval.start,
              measurementSpec.vidSamplingInterval.width
            )
        }.map { vid -> Pair(eventGroup.key, vid)
      }.distinct().map { p -> p.secon}
```

</blockquote></details>

I think there's still room to improve this to avoid the mutable collections.

```kotlin
    val vidList: List<Long> =
      requisitionSpec.eventGroupsList
        .asSequence()
        .distinctBy { eventGroup -> eventGroup.key }
        .flatMap { eventGroup -> eventQuery.getUserVirtualIds(eventGroup.value.filter) }
        .filter { vid ->
          vidSampler.vidIsInSamplingBucket(
            vid,
            measurementSpec.vidSamplingInterval.start,
            measurementSpec.vidSamplingInterval.width
          )
        }
        .toList()
```


<!-- Sent from Reviewable.io -->

2022-08-24 23:39 UTC, SanjayVas requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/672)* status: all files reviewed, 5 unresolved discussions (waiting on @iverson52000, @matthewclegg, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 432 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/672#-NABixaN816djbKcGuwq:-NAHDKCdBn1cgzK_HwcW:b-66k487) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/04a643356c1d81700ddf8dd2f13ff37c85da4742/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L432)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I think there's still room to improve this to avoid the mutable collections.

```kotlin
    val vidList: List<Long> =
      requisitionSpec.eventGroupsList
        .asSequence()
        .distinctBy { eventGroup -> eventGroup.key }
        .flatMap { eventGroup -> eventQuery.getUserVirtualIds(eventGroup.value.filter) }
        .filter { vid ->
          vidSampler.vidIsInSamplingBucket(
            vid,
            measurementSpec.vidSamplingInterval.start,
            measurementSpec.vidSamplingInterval.width
          )
        }
        .toList()
```
</blockquote></details>

Sorry, you probably should drop the `asSequence` and `asList` in my sample, as `distinctBy` is a stateful operation.


<!-- Sent from Reviewable.io -->

2022-08-24 23:53 UTC, matthewclegg reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/672)* status: all files reviewed, 5 unresolved discussions (waiting on @iverson52000, @SanjayVas, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 432 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/672#-NABixaN816djbKcGuwq:-NAHEPHL7dIsQGiYdT4H:bw0chrx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/04a643356c1d81700ddf8dd2f13ff37c85da4742/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L432)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Sorry, you probably should drop the `asSequence` and `asList` in my sample, as `distinctBy` is a stateful operation.
</blockquote></details>

I spoke too soon as well.  Each event needs to be labeled by its eventId, not by its eventGroupKey in the formulation I gave.  Suppose we have two publishers A and B, and each event is represented by a pair (e, v), where e is the event ID and v is the VID.  Example data might be as follows:

A: (1, 1), (2, 2), (3, 3), (4, 1), (5, 2)
B: (1, 1), (6, 3), (7, 4)

Then, the pipeline should proceed as follows:
  (1, 1), (2, 2), (3, 3), (4, 1), (5, 2), (1, 1), (6, 3), (7, 4) ->
  (1, 1), (2, 2), (3, 3), (4, 1), (5, 2), (6, 3), (7, 4) ->
  1, 2, 3, 1, 2, 3, 4


<!-- Sent from Reviewable.io -->

2022-08-25 16:57 UTC, iverson52000 commented
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 432 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/672#-NABixaN816djbKcGuwq:-NAKvFGa92OHjpXjrYke:brmcxlo) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/04a643356c1d81700ddf8dd2f13ff37c85da4742/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L432)):*
<details><summary><i>Previously, matthewclegg (Matthew Clegg) wrote…</i></summary><blockquote>

I spoke too soon as well.  Each event needs to be labeled by its eventId, not by its eventGroupKey in the formulation I gave.  Suppose we have two publishers A and B, and each event is represented by a pair (e, v), where e is the event ID and v is the VID.  Example data might be as follows:

A: (1, 1), (2, 2), (3, 3), (4, 1), (5, 2)
B: (1, 1), (6, 3), (7, 4)

Then, the pipeline should proceed as follows:
  (1, 1), (2, 2), (3, 3), (4, 1), (5, 2), (1, 1), (6, 3), (7, 4) ->
  (1, 1), (2, 2), (3, 3), (4, 1), (5, 2), (6, 3), (7, 4) ->
  1, 2, 3, 1, 2, 3, 4

</blockquote></details>

@matthewclegg Where do we get eventId from? The `eventGroupList` looks like this:



_Code snippet:_
```Kotlin
[key: "dataProviders/BNKDQy5gCHs/eventGroups/RDHoadGf-Ig"
value {
  collection_interval {
    start_time {
      seconds: 1661212800
    }
    end_time {
      seconds: 1661299200
    }
  }
  filter {
    expression: "video_ad.age.value == 1 && privacy_budget.gender.value == 1"
  }
}
]
```


<!-- Sent from Reviewable.io -->

2022-08-25 17:18 UTC, iverson52000 commented
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 432 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/672#-NABixaN816djbKcGuwq:-NAKySBj5SxHazYf4fot:b-d8vagl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/04a643356c1d81700ddf8dd2f13ff37c85da4742/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L432)):*
<details><summary><i>Previously, iverson52000 (Albert Hsu) wrote…</i></summary><blockquote>

@matthewclegg Where do we get eventId from? The `eventGroupList` looks like this:
</blockquote></details>

Actually I checked the synthetic dataset and there's a column of event id. So we should be getting event id from eventQuery. I can put a TODO here to implement that later


<!-- Sent from Reviewable.io -->

2022-08-25 17:44 UTC, iverson52000 commented
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 432 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/672#-NABixaN816djbKcGuwq:-NAL5TtMABu_Gqf6NP9J:b-pwjpz8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/04a643356c1d81700ddf8dd2f13ff37c85da4742/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L432)):*
<details><summary><i>Previously, iverson52000 (Albert Hsu) wrote…</i></summary><blockquote>

Actually I checked the synthetic dataset and there's a column of event id. So we should be getting event id from eventQuery. I can put a TODO here to implement that later
</blockquote></details>

Update the code based on @sanjayvas suggestion


<!-- Sent from Reviewable.io -->

2022-08-26 00:32 UTC, SanjayVas approved these changes
Approved from a code style point of view. Will leave others to check correctness.

> Reviewed 1 of 2 files at r2, 1 of 1 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/672#-:-NAMZ9EV1RA4ixQFK0C9:b-rg6i8r)* status: all files reviewed, 4 unresolved discussions (waiting on @iverson52000, @stevenwarejones, and @tristanvuong2021)



<!-- Sent from Reviewable.io -->

2022-08-26 14:49 UTC, stevenwarejones approved these changes
> Reviewed 1 of 2 files at r2, 1 of 4 files at r3, 1 of 1 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/672)* status: all files reviewed, 3 unresolved discussions (waiting on @iverson52000 and @tristanvuong2021)



<!-- Sent from Reviewable.io -->

2022-08-26 15:57 UTC, stevenwarejones requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/672)* status: all files reviewed, 4 unresolved discussions (waiting on @iverson52000 and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 554 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/672#-NAPrcTS6GKqFRH-NxzC:-NAPrcTS6GKqFRH-NxzD:b-wv6cc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3cba41aa234d0683055057b47a1339bafddf1a03/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L554)):*
> ```Kotlin
>     }
> 
>     fun calculateDirectReachAndFrequency(vidList: List<Long>): Pair<Long, Map<Long, Double>> {
> ```

right now, edps are calculating sketches... is it possible to just pass in a sketch here instead instead of a list of Long?


<!-- Sent from Reviewable.io -->

2022-08-26 17:24 UTC, iverson52000 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/672)* status: all files reviewed, 4 unresolved discussions (waiting on @iverson52000, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 554 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/672#-NAPrcTS6GKqFRH-NxzC:-NAQAcDI9EJ5pTDyx7bK:b74lsqh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3cba41aa234d0683055057b47a1339bafddf1a03/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L554)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

right now, edps are calculating sketches... is it possible to just pass in a sketch here instead instead of a list of Long?
</blockquote></details>

Let me take a look


<!-- Sent from Reviewable.io -->

2022-08-29 17:52 UTC, SanjayVas reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/672)* status: 4 of 5 files reviewed, 4 unresolved discussions (waiting on @iverson52000, @matthewclegg, @SanjayVas, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 554 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/672#-NAPrcTS6GKqFRH-NxzC:-NAeiG9N-v-Tp85qhhh5:b-jeksu8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3cba41aa234d0683055057b47a1339bafddf1a03/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L554)):*
<details><summary><i>Previously, iverson52000 (Albert Hsu) wrote…</i></summary><blockquote>

Let me take a look
</blockquote></details>

Note that this is just the simulator for testing and not necessarily code that EDPs should be calling directly. It's up to EDPs to decide whether they are going to go through sketches as an intermediate step. IIUC, there's no need for sketches at all when doing direct measurement fulfillment. That is to say that one would do this direct computation *instead* of creating a sketch.


<!-- Sent from Reviewable.io -->

2022-08-29 18:40 UTC, iverson52000 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/672)* status: 4 of 5 files reviewed, 4 unresolved discussions (waiting on @iverson52000, @matthewclegg, @SanjayVas, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 554 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/672#-NAPrcTS6GKqFRH-NxzC:-NAeta7cCyHlqSXvG3d0:b-j7833u) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3cba41aa234d0683055057b47a1339bafddf1a03/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L554)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Note that this is just the simulator for testing and not necessarily code that EDPs should be calling directly. It's up to EDPs to decide whether they are going to go through sketches as an intermediate step. IIUC, there's no need for sketches at all when doing direct measurement fulfillment. That is to say that one would do this direct computation *instead* of creating a sketch.
</blockquote></details>

Thanks for the input Sanjay. I also think sketch may not be needed for direct reach and frequency measurement since MPC and Duchy are not involved? And calculating reach and frequency from VID List for single EDP case is very straightforward and we can verify the result easily. I recommend keep the current implementation


<!-- Sent from Reviewable.io -->

2022-08-30 16:42 UTC, iverson52000 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/672)* status: 3 of 5 files reviewed, 4 unresolved discussions (waiting on @iverson52000, @matthewclegg, @SanjayVas, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 554 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/672#-NAPrcTS6GKqFRH-NxzC:-NAjcMYv1OEmXXcRiaSC:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3cba41aa234d0683055057b47a1339bafddf1a03/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L554)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

okay - can you add a comment summarizing that there are two different methods for an edp to calculate a sketch: 1. summing vids directly 2. creating a sketch
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-30 18:31 UTC, stevenwarejones requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/672)* status: 3 of 5 files reviewed, 4 unresolved discussions (waiting on @iverson52000, @matthewclegg, @SanjayVas, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 554 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/672#-NAPrcTS6GKqFRH-NxzC:-NAk0Ihr4KZWQnt_UNf9:b-8ursy2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3cba41aa234d0683055057b47a1339bafddf1a03/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L554)):*
<details><summary><i>Previously, iverson52000 (Albert Hsu) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

i don't see any changes


<!-- Sent from Reviewable.io -->

2022-08-30 19:30 UTC, iverson52000 commented
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 554 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/672#-NAPrcTS6GKqFRH-NxzC:-NAkDdXc1ESrafqMR_uR:bfpm772) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3cba41aa234d0683055057b47a1339bafddf1a03/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L554)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

i don't see any changes
</blockquote></details>

Here's the commit. I add comments in several places
https://github.com/world-federation-of-advertisers/cross-media-measurement/pull/672/commits/ff38336341ab12ea7b1b71a12676a0bbc8da7d46


<!-- Sent from Reviewable.io -->

2022-08-30 19:37 UTC, stevenwarejones approved these changes
> Reviewed 1 of 1 files at r6, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/672)* status: all files reviewed, 3 unresolved discussions (waiting on @iverson52000, @matthewclegg, @SanjayVas, and @tristanvuong2021)



<!-- Sent from Reviewable.io -->

2022-08-30 19:39 UTC, iverson52000 reviewed
> Reviewed 1 of 4 files at r3, 1 of 1 files at r4, 1 of 2 files at r5, 1 of 1 files at r6, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/672)* status: all files reviewed, 3 unresolved discussions (waiting on @iverson52000, @matthewclegg, @SanjayVas, and @tristanvuong2021)



<!-- Sent from Reviewable.io -->

2022-08-30 19:41 UTC, iverson52000 reviewed
> Dismissed @SanjayVas and @matthewclegg from 3 discussions.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/672)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @matthewclegg, @SanjayVas, and @tristanvuong2021)



<!-- Sent from Reviewable.io -->

2022-08-30 19:45 UTC, merged