Suppress exceptions inside syncStatuses
world-federation-of-advertisers/cross-media-measurement pull request #674
Opened 2022-08-24 20:48 UTC by renjiezh

2022-08-24 22:25 UTC, matthewclegg requested changes
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/674)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @matthewclegg and @renjiezh)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt` line 97 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/674#-NAGxFIB-HzJ0huCAqqu:-NAGxFIB-HzJ0huCAqqv:b-gxtp8s) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9788f3cc0c3af94501032b879ad5afa7f853bdc4/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt#L97)):*
> ```Kotlin
>     var lastProcessedContinuationToken = continuationToken
>     logger.info("Reading stream of active computations since $continuationToken.")
>     logAndSuppressExceptionSuspend {
> ```

This looks good, but what is your plan for propagating errors back to the Kingdom?


<!-- Sent from Reviewable.io -->

2022-08-25 19:22 UTC, renjiezh commented on src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt
> +      //  failComputationAtKingdom
New withRetriesOnEach() 
https://github.com/world-federation-of-advertisers/common-jvm/pull/161

2022-08-26 17:04 UTC, matthewclegg requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/674)* status: 1 of 3 files reviewed, 3 unresolved discussions (waiting on @matthewclegg and @renjiezh)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt` line 128 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/674#-NAPsP0y9EavQX7koWmd:-NAPsP0y9EavQX7koWme:b-cm5mbt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b96c17eb5247747c8c161166e4424edcc40e8d9e/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt#L128)):*
> ```Kotlin
>             )
>           }
>           throw ex
> ```

Thank you, this looks like a great start, but I don't think it is quite what we want.  If `ex` is a non-transient error, then re-throwing it will cause the Herald to crash because there are no higher level exception handlers.   On the other hand, if `ex` is a transient error and `maxAttempts` is exceeded, then the Herald will again crash.

I think that the desired behavior should be as follows.  If `ex` is a transient error and the allowed number of retries has not been exceeded, then a brief error message should be logged and the exception should be ignored.  Otherwise, the computation should be failed both at the Duchy and at the Kingdom.


<!-- Sent from Reviewable.io -->

2022-08-26 17:13 UTC, renjiezh reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/674)* status: 1 of 3 files reviewed, 3 unresolved discussions (waiting on @matthewclegg and @renjiezh)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt` line 128 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/674#-NAPsP0y9EavQX7koWmd:-NAQ6ZJt9KHcpcjdrvXN:bmqg6ve) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b96c17eb5247747c8c161166e4424edcc40e8d9e/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt#L128)):*
<details><summary><i>Previously, matthewclegg (Matthew Clegg) wrote…</i></summary><blockquote>

Thank you, this looks like a great start, but I don't think it is quite what we want.  If `ex` is a non-transient error, then re-throwing it will cause the Herald to crash because there are no higher level exception handlers.   On the other hand, if `ex` is a transient error and `maxAttempts` is exceeded, then the Herald will again crash.

I think that the desired behavior should be as follows.  If `ex` is a transient error and the allowed number of retries has not been exceeded, then a brief error message should be logged and the exception should be ignored.  Otherwise, the computation should be failed both at the Duchy and at the Kingdom.

</blockquote></details>

At the upper layer we have `logAndSuppressExceptionSuspend` (line 91) to catch and log errors. So the Herald will not crash. 
Once I applied the new version of `withRetriesOnEach`, the additional finally block with handle attempts exhausted errors. Thus the desired behavior accomplished. 
Btw, do we need additional actions to fail at duchy? Seems I only fail at Kingdom for exceptions.


<!-- Sent from Reviewable.io -->

2022-08-26 18:07 UTC, matthewclegg requested changes
> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/674)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @matthewclegg and @renjiezh)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt` line 128 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/674#-NAPsP0y9EavQX7koWmd:-NAQHkET5sqF_2H1xMcT:b-9g55qa) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b96c17eb5247747c8c161166e4424edcc40e8d9e/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt#L128)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

At the upper layer we have `logAndSuppressExceptionSuspend` (line 91) to catch and log errors. So the Herald will not crash. 
Once I applied the new version of `withRetriesOnEach`, the additional finally block with handle attempts exhausted errors. Thus the desired behavior accomplished. 
Btw, do we need additional actions to fail at duchy? Seems I only fail at Kingdom for exceptions.
</blockquote></details>

Yes, I think you probably also need to fail the computation at the duchy as well.

If I am reading your code correctly, even taking into account the code at line 91, it looks to me like there is still a bug.  If there are too many transient exceptions, the exception is re-thrown to `continuallySyncStatuses` and no error is propagated to the kingdom.  Is this correct?

To me, it seems like the code would be easier to understand if all of the exception handling occurs in `syncStatuses`.

Could you please add unit tests to InProcessLifeOfAMeasurement showing:

(1) if there is a non-transient error, then it is properly propagated back to the measurement consumer;
(2) if there are multiple transient errors that exceed `maxAttempts`, then the error is properly propagated back to the measurement consumer

https://source.corp.google.com/lancelot/cross-media-measurement/src/main/kotlin/org/wfanet/measurement/integration/common/InProcessLifeOfAMeasurementIntegrationTest.kt


<!-- Sent from Reviewable.io -->

2022-08-26 18:13 UTC, renjiezh reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/674)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @matthewclegg and @renjiezh)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt` line 128 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/674#-NAPsP0y9EavQX7koWmd:-NAQLQiRD0k3uUe9NVXW:b-syas8g) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b96c17eb5247747c8c161166e4424edcc40e8d9e/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt#L128)):*
<details><summary><i>Previously, matthewclegg (Matthew Clegg) wrote…</i></summary><blockquote>

Yes, I think you probably also need to fail the computation at the duchy as well.

If I am reading your code correctly, even taking into account the code at line 91, it looks to me like there is still a bug.  If there are too many transient exceptions, the exception is re-thrown to `continuallySyncStatuses` and no error is propagated to the kingdom.  Is this correct?

To me, it seems like the code would be easier to understand if all of the exception handling occurs in `syncStatuses`.

Could you please add unit tests to InProcessLifeOfAMeasurement showing:

(1) if there is a non-transient error, then it is properly propagated back to the measurement consumer;
(2) if there are multiple transient errors that exceed `maxAttempts`, then the error is properly propagated back to the measurement consumer

https://source.corp.google.com/lancelot/cross-media-measurement/src/main/kotlin/org/wfanet/measurement/integration/common/InProcessLifeOfAMeasurementIntegrationTest.kt
</blockquote></details>

Thank you for the reply. Yeah, let me apply the updated `common-jvm` to solve the TODO, which will catch the attempts-exhausted exception. 
Also, I will add logic to fail at Duchy and complete the test code.


<!-- Sent from Reviewable.io -->

2022-08-28 22:52 UTC, renjiezh reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/674)* status: 1 of 7 files reviewed, 2 unresolved discussions (waiting on @matthewclegg)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt` line 97 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/674#-NAGxFIB-HzJ0huCAqqu:-NAadThd0u2gHntZDVji:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9788f3cc0c3af94501032b879ad5afa7f853bdc4/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt#L97)):*
<details><summary><i>Previously, matthewclegg (Matthew Clegg) wrote…</i></summary><blockquote>

This looks good, but what is your plan for propagating errors back to the Kingdom?
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt` line 128 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/674#-NAPsP0y9EavQX7koWmd:-NAadUQZB1zk2kYzDOWH:b-nkbniv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b96c17eb5247747c8c161166e4424edcc40e8d9e/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt#L128)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

Thank you for the reply. Yeah, let me apply the updated `common-jvm` to solve the TODO, which will catch the attempts-exhausted exception. 
Also, I will add logic to fail at Duchy and complete the test code.
</blockquote></details>

Done. Added unit tests for these two cases.
Still trying to figure out how to report to Duchy. Will do that in a following PR if needed.


<!-- Sent from Reviewable.io -->

2022-09-02 20:27 UTC, matthewclegg requested changes
> Reviewed 4 of 6 files at r4, 2 of 2 files at r5, 2 of 3 files at r6, 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/674)* status: all files reviewed, 2 unresolved discussions (waiting on @renjiezh)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt` line 128 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/674#-NAPsP0y9EavQX7koWmd:-NAzm8l4DypR3JFhAuGu:bna4bn1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b96c17eb5247747c8c161166e4424edcc40e8d9e/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt#L128)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

Done. Added unit tests for these two cases.
Still trying to figure out how to report to Duchy. Will do that in a following PR if needed.

</blockquote></details>

Hi Renjie, 

Thank you for adding the integration tests.  Overall, the code looks good.

However, I'm still not convinced that this code is as simple as possible.  To me, it seems the exception handling is spread across multiple functions:  syncStatuses, continuallySyncStatuses, handleException, withRetriesOnEachErrorHandler.  I think this could be made simpler, which would make it easier to reason about and less error prone.  

There is another concern that I have, which is really a problem with the prior code.  If a request is causing transient errors, it can block the handling of any other requests that may be pending.

I would propose a structure like the following:

// Same as original code
suspend fun continuallySyncStatuses(pollingThrottler: Throttler) {
    logger.info("Starting...")
    // Token signifying the last computation in an active state at the kingdom that was processed by
    // this job. When empty, all active computations at the kingdom will be streamed in the
    // response. The first execution of the loop will then compare all active computations at
    // the kingdom with all active computations locally.
    var lastProcessedContinuationToken = ""

    pollingThrottler.loopOnReady {
      lastProcessedContinuationToken = syncStatuses(lastProcessedContinuationToken)
    }
  }

// Exception handling removed from original code, processing launched asynchronously
suspend fun syncStatuses(continuationToken: String): String {
    var lastProcessedContinuationToken = continuationToken
    logger.info("Reading stream of active computations since $continuationToken.")
  
    // Question:  Can streamActiveComputations generate an exception?
    systemComputationsClient
      .streamActiveComputations(
        StreamActiveComputationsRequest.newBuilder().setContinuationToken(continuationToken).build()
      ).map
     { response ->
        launch { processSystemComputationChangeWithoutExceptions (response) }
        lastProcessedContinuationToken = response.continuationToken
      }
      .collect()

    return lastProcessedContinuationToken
  }

// New function dedicated solely to handling exceptions when processing computations
// No exceptions will propagate beyond this function.
private suspend fun processSystemComputationWithoutExceptions(response: StreamActiveComputationsResponse) {
    var nTries = 0
   while (true) {
     nTries++
     try {
       processSystemComputation(response)
       return
    } catch (ex:  Throwable) {
       if (!mayBeTransientGrpcError(ex) || nTries > maxAllowedTries) {
         failComputationAtKingdom(...)
         failComputationAtDuchy(...)
         return
      }
    }
   }
}
___
*[`src/test/kotlin/org/wfanet/measurement/duchy/daemon/herald/HeraldTest.kt` line 668 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/674#-NAz_UZ27C3yHHDADXpb:-NAz_UZ30tMO-WSESnWQ:b-ob0nbs) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/11b28ca9953482672f5758098d1dc77efdb90e6e/src/test/kotlin/org/wfanet/measurement/duchy/daemon/herald/HeraldTest.kt#L668)):*
> ```Kotlin
> 
>   @Test
>   fun `syncStatuses fails computation for attempts-axhausted error`() = runTest {
> ```

change 'axhausted' to 'exhausted'


<!-- Sent from Reviewable.io -->

2022-09-02 21:07 UTC, renjiezh reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/674)* status: all files reviewed, 2 unresolved discussions (waiting on @matthewclegg and @renjiezh)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt` line 128 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/674#-NAPsP0y9EavQX7koWmd:-NB-0ipF7pFb8u0R0iF0:b3h04lj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b96c17eb5247747c8c161166e4424edcc40e8d9e/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt#L128)):*
<details><summary><i>Previously, matthewclegg (Matthew Clegg) wrote…</i></summary><blockquote>

Hi Renjie, 

Thank you for adding the integration tests.  Overall, the code looks good.

However, I'm still not convinced that this code is as simple as possible.  To me, it seems the exception handling is spread across multiple functions:  syncStatuses, continuallySyncStatuses, handleException, withRetriesOnEachErrorHandler.  I think this could be made simpler, which would make it easier to reason about and less error prone.  

There is another concern that I have, which is really a problem with the prior code.  If a request is causing transient errors, it can block the handling of any other requests that may be pending.

I would propose a structure like the following:

// Same as original code
suspend fun continuallySyncStatuses(pollingThrottler: Throttler) {
    logger.info("Starting...")
    // Token signifying the last computation in an active state at the kingdom that was processed by
    // this job. When empty, all active computations at the kingdom will be streamed in the
    // response. The first execution of the loop will then compare all active computations at
    // the kingdom with all active computations locally.
    var lastProcessedContinuationToken = ""

    pollingThrottler.loopOnReady {
      lastProcessedContinuationToken = syncStatuses(lastProcessedContinuationToken)
    }
  }

// Exception handling removed from original code, processing launched asynchronously
suspend fun syncStatuses(continuationToken: String): String {
    var lastProcessedContinuationToken = continuationToken
    logger.info("Reading stream of active computations since $continuationToken.")
  
    // Question:  Can streamActiveComputations generate an exception?
    systemComputationsClient
      .streamActiveComputations(
        StreamActiveComputationsRequest.newBuilder().setContinuationToken(continuationToken).build()
      ).map
     { response ->
        launch { processSystemComputationChangeWithoutExceptions (response) }
        lastProcessedContinuationToken = response.continuationToken
      }
      .collect()

    return lastProcessedContinuationToken
  }

// New function dedicated solely to handling exceptions when processing computations
// No exceptions will propagate beyond this function.
private suspend fun processSystemComputationWithoutExceptions(response: StreamActiveComputationsResponse) {
    var nTries = 0
   while (true) {
     nTries++
     try {
       processSystemComputation(response)
       return
    } catch (ex:  Throwable) {
       if (!mayBeTransientGrpcError(ex) || nTries > maxAllowedTries) {
         failComputationAtKingdom(...)
         failComputationAtDuchy(...)
         return
      }
    }
   }
}

</blockquote></details>

Thank you matt. I like the idea of using `launch`. Let me apply it to the code.


<!-- Sent from Reviewable.io -->

2022-09-08 21:11 UTC, renjiezh reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/674)* status: 6 of 15 files reviewed, 2 unresolved discussions (waiting on @matthewclegg)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt` line 128 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/674#-NAPsP0y9EavQX7koWmd:-NBTwM6G3NrdpxQdSmGc:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b96c17eb5247747c8c161166e4424edcc40e8d9e/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt#L128)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

Thank you matt. I like the idea of using `launch`. Let me apply it to the code.
</blockquote></details>

Done.
___
*[`src/test/kotlin/org/wfanet/measurement/duchy/daemon/herald/HeraldTest.kt` line 668 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/674#-NAz_UZ27C3yHHDADXpb:-NBTwKjA57CWcSP6fqik:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/11b28ca9953482672f5758098d1dc77efdb90e6e/src/test/kotlin/org/wfanet/measurement/duchy/daemon/herald/HeraldTest.kt#L668)):*
<details><summary><i>Previously, matthewclegg (Matthew Clegg) wrote…</i></summary><blockquote>

change 'axhausted' to 'exhausted'
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-09-09 22:24 UTC, matthewclegg requested changes
The code looks very good.  I tried it out!  I just have a couple small requests given below, but otherwise it looks good.  Thanks for doing this!

> Reviewed 4 of 8 files at r8, 5 of 5 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/674#-:-NBZLRMl2iQuz_5SBnT-:b-f9xl0d)* status: all files reviewed, 6 unresolved discussions (waiting on @matthewclegg and @renjiezh)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt` line 117 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/674#-NBZFbNR-j2YY6oTkGOy:-NBZFbNR-j2YY6oTkGOz:b8xtdsw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/724e61f12f0d6f75172bf8c1e2185eec0e69f8c6/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt#L117)):*
> ```Kotlin
>       .streamActiveComputations(streamRequest)
>       .onEach { response ->
>         launch { processSystemComputationWithoutExceptions(response.computation, 3) }
> ```

How about defining a constant to represent the maximum number of allowed attempts?
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt` line 274 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/674#-NBZHr7K0TUwD6-6mVL8:-NBZHr7K0TUwD6-6mVL9:b-20887e) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/724e61f12f0d6f75172bf8c1e2185eec0e69f8c6/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt#L274)):*
> ```Kotlin
>       systemComputationParticipantClient.failComputationParticipant(request)
>     } catch (ex: Throwable) {
>       logger.warning("[id=$globalId]: Error when failComputationAtKingdom.")
> ```

Could you log the exception?  To my knowledge, we should never get an exception at this point, so if we do, it would be helpful to have enough information to debug it.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt` line 300 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/674#-NBZI3KAD3XTIP7s2jRs:-NBZI3KAD3XTIP7s2jRt:b4z9kld) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/724e61f12f0d6f75172bf8c1e2185eec0e69f8c6/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt#L300)):*
> ```Kotlin
>       internalComputationsClient.finishComputation(finishRequest)
>     } catch (ex: Throwable) {
>       logger.warning("[id=$globalId]: Error when failComputationAtDuchy.")
> ```

Log the exception here too.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/SetParticipantRequisitionParams.kt` line 149 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/674#-NBZGW1iBQ3_c-JKB_Kd:-NBZGW1iBQ3_c-JKB_Ke:bs2dogg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/724e61f12f0d6f75172bf8c1e2185eec0e69f8c6/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/SetParticipantRequisitionParams.kt#L149)):*
> ```Kotlin
>       )
>     ) {
>       println("SetParticipantRequisitionParams!!!")
> ```

Delete
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/UpdateMeasurementState.kt` line 31 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/674#-NBZG_jD3UDXNSIdDhPx:-NBZG_jD3UDXNSIdDhPy:bs2dogg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/724e61f12f0d6f75172bf8c1e2185eec0e69f8c6/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/UpdateMeasurementState.kt#L31)):*
> ```Kotlin
>   details: Measurement.Details? = null,
> ) {
>   println("Measurement state changed to ${state.name}")
> ```

Delete


<!-- Sent from Reviewable.io -->

2022-09-09 23:01 UTC, renjiezh reviewed
Thank you so much!

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/674#-:-NBZU9vk8ukG5w1Bz9sN:b-fudnmc)* status: all files reviewed, 6 unresolved discussions (waiting on @matthewclegg)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt` line 117 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/674#-NBZFbNR-j2YY6oTkGOy:-NBZSHF040uBS_2uGE5D:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/724e61f12f0d6f75172bf8c1e2185eec0e69f8c6/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt#L117)):*
<details><summary><i>Previously, matthewclegg (Matthew Clegg) wrote…</i></summary><blockquote>

How about defining a constant to represent the maximum number of allowed attempts?
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt` line 274 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/674#-NBZHr7K0TUwD6-6mVL8:-NBZSe_pDztuBQP07lQ2:bpyr9cz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/724e61f12f0d6f75172bf8c1e2185eec0e69f8c6/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt#L274)):*
<details><summary><i>Previously, matthewclegg (Matthew Clegg) wrote…</i></summary><blockquote>

Could you log the exception?  To my knowledge, we should never get an exception at this point, so if we do, it would be helpful to have enough information to debug it.
</blockquote></details>

Done.
I thought any API call could raise exceptions. This one is not critical so just suppress it with a warning log.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt` line 300 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/674#-NBZI3KAD3XTIP7s2jRs:-NBZSj5l5kiS1DVByLxC:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/724e61f12f0d6f75172bf8c1e2185eec0e69f8c6/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt#L300)):*
<details><summary><i>Previously, matthewclegg (Matthew Clegg) wrote…</i></summary><blockquote>

Log the exception here too.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/SetParticipantRequisitionParams.kt` line 149 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/674#-NBZGW1iBQ3_c-JKB_Kd:-NBZSwAEEwWrHgRAALqo:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/724e61f12f0d6f75172bf8c1e2185eec0e69f8c6/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/SetParticipantRequisitionParams.kt#L149)):*
<details><summary><i>Previously, matthewclegg (Matthew Clegg) wrote…</i></summary><blockquote>

Delete
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/UpdateMeasurementState.kt` line 31 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/674#-NBZG_jD3UDXNSIdDhPx:-NBZTYDs0OKZ0_ulLWma:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/724e61f12f0d6f75172bf8c1e2185eec0e69f8c6/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/UpdateMeasurementState.kt#L31)):*
<details><summary><i>Previously, matthewclegg (Matthew Clegg) wrote…</i></summary><blockquote>

Delete
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-09-10 19:19 UTC, matthewclegg requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/674)* status: all files reviewed, 3 unresolved discussions (waiting on @matthewclegg and @renjiezh)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt` line 117 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/674#-NBZFbNR-j2YY6oTkGOy:-NBcmCbOB8Lz5HkDlgEZ:b35hbji) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/724e61f12f0d6f75172bf8c1e2185eec0e69f8c6/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt#L117)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Hi Renjie,

I don't see the change.  Did you forget to push it?  Also, I have been thinking about things, and it might be a good idea to limit the number of tasks that are launched concurrently.  One way to do this would be to use a semaphore. 

https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.sync/-semaphore.html


<!-- Sent from Reviewable.io -->

2022-09-12 16:59 UTC, renjiezh reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/674)* status: 11 of 15 files reviewed, 3 unresolved discussions (waiting on @matthewclegg)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt` line 117 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/674#-NBZFbNR-j2YY6oTkGOy:-NBmcrd269WWUXRm0vn7:b94y6ch) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/724e61f12f0d6f75172bf8c1e2185eec0e69f8c6/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt#L117)):*
<details><summary><i>Previously, matthewclegg (Matthew Clegg) wrote…</i></summary><blockquote>

Hi Renjie,

I don't see the change.  Did you forget to push it?  Also, I have been thinking about things, and it might be a good idea to limit the number of tasks that are launched concurrently.  One way to do this would be to use a semaphore. 

https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines.sync/-semaphore.html

</blockquote></details>

Added semaphore.
Thank you for the idea. 


<!-- Sent from Reviewable.io -->

2022-09-13 21:21 UTC, matthewclegg approved these changes
> Reviewed 2 of 3 files at r10, 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/674)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @renjiezh)



<!-- Sent from Reviewable.io -->

2022-09-14 17:52 UTC, stevenwarejones requested changes
> Reviewed 1 of 2 files at r2, 3 of 6 files at r4, 1 of 2 files at r5, 1 of 3 files at r7, 1 of 8 files at r8, 4 of 5 files at r9, 2 of 3 files at r10, 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/674)* status: all files reviewed, 2 unresolved discussions (waiting on @renjiezh)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt` line 50 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/674#-NBx6mMU-DFcul1gUTYD:-NBx6mMU-DFcul1gUTYE:b-s7m47f) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7a62aaaeefa3b2546b69cc7ff9b940e43bbb3d81/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt#L50)):*
> ```Kotlin
> import org.wfanet.measurement.system.v1alpha.streamActiveComputationsRequest
> 
> private const val MAX_ATTEMPTS = 3
> ```

maxAttempts is passed into the constructor. What's the difference?
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/herald/HeraldDaemon.kt` line 112 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/674#-NBx7-DY6raNKfcawD-b:-NBx7-DZ-b0LJCnLL6Zw:b-829kl6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7a62aaaeefa3b2546b69cc7ff9b940e43bbb3d81/src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/herald/HeraldDaemon.kt#L112)):*
> ```Kotlin
> 
>   // This will be the name of the pod when deployed to Kubernetes.
>   val heraldId = System.getenv("HOSTNAME")
> ```

do we need to update the cue files with this?


<!-- Sent from Reviewable.io -->

2022-09-14 18:15 UTC, renjiezh reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/674)* status: all files reviewed, 2 unresolved discussions (waiting on @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt` line 50 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/674#-NBx6mMU-DFcul1gUTYD:-NBxAsL2AV9StZnpVYrr:bmnt3rz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7a62aaaeefa3b2546b69cc7ff9b940e43bbb3d81/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt#L50)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

maxAttempts is passed into the constructor. What's the difference?
</blockquote></details>

Good question. So far we have two layers of retries. `MAX_ATTEMPTS` is not the one in the constructor.
The top layer is used to retry for cases like ComputationService unavailable. It uses this MAX_ATTEMPTS as the limit.
The sub-layer is using exponential backoff for potential race condition(https://github.com/world-federation-of-advertisers/cross-media-measurement/issues/585). The limit is from the constructor.
Sorry for the confusion. But in a long term, we will re-consider the retry mechanism to make it better.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/herald/HeraldDaemon.kt` line 112 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/674#-NBx7-DY6raNKfcawD-b:-NBxAkM85_9XIlZMju4Y:b-3tl8c8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7a62aaaeefa3b2546b69cc7ff9b940e43bbb3d81/src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/herald/HeraldDaemon.kt#L112)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

do we need to update the cue files with this?
</blockquote></details>

This is set by kubernetes.No change needed in cue files. Mill is already using it.


<!-- Sent from Reviewable.io -->

2022-09-15 20:23 UTC, stevenwarejones approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/674)* status: all files reviewed, 1 unresolved discussion (waiting on @renjiezh)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt` line 50 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/674#-NBx6mMU-DFcul1gUTYD:-NC1oQJ35zM1EamViUbV:b-oz2k97) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7a62aaaeefa3b2546b69cc7ff9b940e43bbb3d81/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt#L50)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

Good question. So far we have two layers of retries. `MAX_ATTEMPTS` is not the one in the constructor.
The top layer is used to retry for cases like ComputationService unavailable. It uses this MAX_ATTEMPTS as the limit.
The sub-layer is using exponential backoff for potential race condition(https://github.com/world-federation-of-advertisers/cross-media-measurement/issues/585). The limit is from the constructor.
Sorry for the confusion. But in a long term, we will re-consider the retry mechanism to make it better.
</blockquote></details>

can you add some comments around the difference?


<!-- Sent from Reviewable.io -->

2022-09-16 00:38 UTC, renjiezh reviewed
> Reviewed 1 of 2 files at r2, 3 of 6 files at r4, 1 of 2 files at r5, 1 of 3 files at r7, 1 of 8 files at r8, 3 of 5 files at r9, 1 of 2 files at r11, 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/674)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wangyaopw)



<!-- Sent from Reviewable.io -->

2022-09-16 00:49 UTC, merged

2022-09-16 21:16 UTC, SanjayVas reviewed
> Reviewed 1 of 6 files at r4.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/674)* status: all files reviewed, 1 unresolved discussion

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/herald/HeraldDaemon.kt` line 112 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/674#-NC78xLk4cyoIysioveW:-NC78xLl7AHArRs_j7yp:b-kqz3te) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e66bf2c6708f18afd07f777fa7b6462a52ef49ea/src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/herald/HeraldDaemon.kt#L112)):*
> ```Kotlin
> 
>   // This will be the name of the pod when deployed to Kubernetes.
>   val heraldId = System.getenv("HOSTNAME")
> ```

Our code should never access K8s environment variables directly. Instead, it should have a @CommandLine.Option that's set using the environment variable in the K8s manifest.


<!-- Sent from Reviewable.io -->