Update duchy to handle reach-only requests
world-federation-of-advertisers/cross-media-measurement pull request #676
Opened 2022-08-31 02:36 UTC by matthewclegg

If reach_and_frequency.maximum_frequency_per_user is set to 1 in the MeasurementSpec for a ReachAndFrequency request, then an alternative path is followed for handling the request.  This alternative path differs from the standard path in the following ways:

1. The Duchy sets the key for each register to "destroyed" and sets the count to a random value.
2. Frequency-related noise registers are not added to the sketch.
3. After the reach value has been computed, the protocol terminates early and returns just this value.

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/676)

2022-09-02 16:11 UTC, pasin30055 reviewed
Thanks Matt. This looks good overall; I left a few (mostly minor) comments.

2022-09-02 16:11 UTC, pasin30055 commented on src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/liquid_legions_v2_encryption_utility.cc
> +  // destroyed.  In either case, no information should leak about the number of
I'm not sure what this second case means. I.e. when do we omit noise parameters?

2022-09-02 16:11 UTC, pasin30055 commented on src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/liquid_legions_v2_encryption_utility.cc
> +    std::string random_count = absl::StrCat(
Is this `random_count` string used anywhere?

2022-09-02 16:11 UTC, pasin30055 commented on src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/liquid_legions_v2_encryption_utility.cc
> +    ASSIGN_OR_RETURN(std::string random_encrypted_count,
Actually, now that I think about it more it seems like we don't need to randomize the count. The reason is that when SameKeyAggregator is run, it is capped at `maximum_frequency` anyway, so if `maximum_frequency = 1`, then no information will be leaked (because every single register will have count at least one). Is this correct? If so, then maybe we can skip randomizing the counts. Wdyt?

2022-09-02 16:11 UTC, pasin30055 commented on src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/liquid_legions_v2_encryption_utility.cc
> +    ASSIGN_OR_RETURN(std::string random_encrypted_count,
(Also I guess we don't even fully run SKA, so there shouldn't be any problem with not randomizing the count, right?)

2022-09-02 16:11 UTC, pasin30055 commented on src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2Mill.kt
> +      sendResultToKingdom(token, reach, emptyMap<Long, Double>())
Would it make more sense to output a map from 1 to 1 (i.e. 100% has frequency >= 1) here?

2022-09-02 16:11 UTC, pasin30055 commented on src/test/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/liquid_legions_v2_encryption_utility_test.cc
Would it make sense to also add a unit test for `DestroyKeysAndCounts`?

2022-09-02 18:18 UTC, renjiezh reviewed
> Reviewed 3 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/676)* status: 3 of 8 files reviewed, 9 unresolved discussions (waiting on @matthewclegg, @pasin30055, and @renjiezh)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2Mill.kt` line 592 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/676#-NAzKboo31LE5Os2e3B4:-NAzKboo31LE5Os2e3B5:b-t4emii) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/505f7ca22a969fd1da049baded1a1d2ebab01c37/src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2Mill.kt#L592)):*
> ```Kotlin
>             curveId = llv2Parameters.ellipticCurveId.toLong()
>             flagCountTuples = readAndCombineAllInputBlobs(token, 1)
>             maximumFrequency = getMaximumRequestedFrequency(token)
> ```

nit: getMaximumRequestedFrequency() is called several times. It might be better to extract it to a variable `maximumRequestedFreqency = getMaximumRequestedFrequency(token)`
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2Mill.kt` line 645 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/676#-NAlkU8LX3KHjyLT5CwH-r1-645:-NAzOk-XCnLZVGsQVyR1:b32v57) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/505f7ca22a969fd1da049baded1a1d2ebab01c37/src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2Mill.kt#L645)):*
<details><summary><i>Previously, pasin30055 (Pasin Manurangsi) wrote…</i></summary><blockquote>

Would it make more sense to output a map from 1 to 1 (i.e. 100% has frequency >= 1) here?
</blockquote></details>

+1
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2Mill.kt` line 846 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/676#-NAzC1fQ-UWeGJQ4Pxrj:-NAzC1fQ-UWeGJQ4Pxrk:bspfv9m) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/505f7ca22a969fd1da049baded1a1d2ebab01c37/src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2Mill.kt#L846)):*
> ```Kotlin
>   ): CompleteSetupPhaseRequest {
>     val noiseConfig = llv2Details.parameters.noise
>     val requestBuilder = CompleteSetupPhaseRequest.newBuilder().setCombinedRegisterVector(this)
> ```

nit: Use Dsl
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulator.kt` line 217 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/676#-NAz6zjx7MrRS3dkh6Ub:-NAz6zjx7MrRS3dkh6Uc:b-lf8ayh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/505f7ca22a969fd1da049baded1a1d2ebab01c37/src/main/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulator.kt#L217)):*
> ```Kotlin
>     var reachOnlyResult = getReachAndFrequencyResult(createdReachOnlyMeasurement.name)
>     var nAttempts = 0
>     while (reachOnlyResult == null && (nAttempts < 4)) {
> ```

I saw other cases did not add the limit of attempts. Will this bring risk to break the test?
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulator.kt` line 223 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/676#-NAz80TT8bzjjx3qcBVD:-NAz80TT8bzjjx3qcBVE:b-96v2lr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/505f7ca22a969fd1da049baded1a1d2ebab01c37/src/main/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulator.kt#L223)):*
> ```Kotlin
>       reachOnlyResult = getReachAndFrequencyResult(createdReachOnlyMeasurement.name)
>     }
>     if (reachOnlyResult == null) {
> ```

nit: when assertion fails, we will have information of the failure. Guess logger does not necessarily need to print a message. Thus `assertThat(reachOnlyResult).isNotNull()` might suffice.


<!-- Sent from Reviewable.io -->

2022-09-03 18:58 UTC, matthewclegg reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/676)* status: 2 of 8 files reviewed, 8 unresolved discussions (waiting on @pasin30055 and @renjiezh)

___
*[`src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/liquid_legions_v2_encryption_utility.cc` line 583 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/676#-NAlkU8LX3KHjyLT5CwG-r1-583:-NB3EVpV0-sUrKmruZTr:bebp470) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/505f7ca22a969fd1da049baded1a1d2ebab01c37/src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/liquid_legions_v2_encryption_utility.cc#L583)):*
<details><summary><i>Previously, pasin30055 (Pasin Manurangsi) wrote…</i></summary><blockquote>

I'm not sure what this second case means. I.e. when do we omit noise parameters?
</blockquote></details>

As far as I can tell, the noise parameters are only omitted in debugging.  In production, these parameters are always included.  I have added a comment to that effect.
___
*[`src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/liquid_legions_v2_encryption_utility.cc` line 628 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/676#-NAlkU8LX3KHjyLT5CwG-r1-628:-NB3Em905ouH42hljSLs:b-af5dko) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/505f7ca22a969fd1da049baded1a1d2ebab01c37/src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/liquid_legions_v2_encryption_utility.cc#L628)):*
<details><summary><i>Previously, pasin30055 (Pasin Manurangsi) wrote…</i></summary><blockquote>

Is this `random_count` string used anywhere?
</blockquote></details>

Ah, thanks for finding that.  I meant to use 'random_count' in place of 'register_id' in line 631.
___
*[`src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/liquid_legions_v2_encryption_utility.cc` line 630 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/676#-NAlkU8LX3KHjyLT5CwG-r1-630:-NB3F4ATBo75x3xpYvYO:b-ovahg3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/505f7ca22a969fd1da049baded1a1d2ebab01c37/src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/liquid_legions_v2_encryption_utility.cc#L630)):*
<details><summary><i>Previously, pasin30055 (Pasin Manurangsi) wrote…</i></summary><blockquote>

(Also I guess we don't even fully run SKA, so there shouldn't be any problem with not randomizing the count, right?)
</blockquote></details>

I suppose that if we are bypassing SKA, then there is probably no danger of leaking the number of publishers that contributed to a given register.  On the other hand, if we randomize the register counts, it seems to give an extra level of assurance.  Do you think there could be a problem with this?
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2Mill.kt` line 645 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/676#-NAlkU8LX3KHjyLT5CwH-r1-645:-NB3INTu6V-uqL5yFKGc:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/505f7ca22a969fd1da049baded1a1d2ebab01c37/src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2Mill.kt#L645)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2Mill.kt` line 846 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/676#-NAzC1fQ-UWeGJQ4Pxrj:-NB3Qkqk7fZC9kFh1WtX:bhyryhu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/505f7ca22a969fd1da049baded1a1d2ebab01c37/src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2Mill.kt#L846)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

nit: Use Dsl
</blockquote></details>

This is part of the legacy code, so I hope you don't mind if I leave it as is.  In any event, and please correct me if I am wrong, but I don't think that DSL will work in this case.  In this context `this` refers to the receiver argument of the function.  I think if you were to try to switch to DSL, `this` would refer to the enclosing Builder object.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulator.kt` line 217 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/676#-NAz6zjx7MrRS3dkh6Ub:-NB3KTW565A6Lg4Amn6S:b-658c22) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/505f7ca22a969fd1da049baded1a1d2ebab01c37/src/main/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulator.kt#L217)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

I saw other cases did not add the limit of attempts. Will this bring risk to break the test?
</blockquote></details>

In my view, it's the other tests that are broken. ;). If the number of attempts is not limited, then there is a potential for an infinite loop.  This could happen if there is a bug in the Duchy code.  In that case, the unit test would never complete.  A better behavior is that the unit test should eventually time out and generate a failure.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulator.kt` line 223 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/676#-NAz80TT8bzjjx3qcBVD:-NB3RxqHC6Tjs83uakxf:bcb8a5f) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/505f7ca22a969fd1da049baded1a1d2ebab01c37/src/main/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulator.kt#L223)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

nit: when assertion fails, we will have information of the failure. Guess logger does not necessarily need to print a message. Thus `assertThat(reachOnlyResult).isNotNull()` might suffice.
</blockquote></details>

Thanks, I have changed the assertion as you have suggested.  I also kept the enclosing if { ... }.  The reason for this is to allow Kotlin to infer that reachOnlyResult cannot be null in the call to `assertDpResultsEqual()` later in this function.
___
*[`src/test/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/liquid_legions_v2_encryption_utility_test.cc` line 689 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/676#-NAlkU8LX3KHjyLT5CwL-r1-689:-NB3MMbw3bASCqX57Eru:b-nwch3l) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/505f7ca22a969fd1da049baded1a1d2ebab01c37/src/test/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/liquid_legions_v2_encryption_utility_test.cc#L689)):*
<details><summary><i>Previously, pasin30055 (Pasin Manurangsi) wrote…</i></summary><blockquote>

Would it make sense to also add a unit test for `DestroyKeysAndCounts`?
</blockquote></details>

That is essentially what is tested in `FrequencyOneWorksAsExpectedWithoutNoise` and `FrequencyOneWorksAsExpectedWithNoise`.  If you think there are other things that should be tested, please let me know.


<!-- Sent from Reviewable.io -->

2022-09-03 22:42 UTC, renjiezh approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 8 files at r1, 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/676#-:-NB4W9-s-Ubi7-60AXLb:bnfp4nl)* status: 4 of 8 files reviewed, 6 unresolved discussions (waiting on @matthewclegg, @pasin30055, and @renjiezh)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulator.kt` line 223 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/676#-NAz80TT8bzjjx3qcBVD:-NB4VqE_DM2BDYYHwKEB:b2p8shw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/505f7ca22a969fd1da049baded1a1d2ebab01c37/src/main/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulator.kt#L223)):*
<details><summary><i>Previously, matthewclegg (Matthew Clegg) wrote…</i></summary><blockquote>

Thanks, I have changed the assertion as you have suggested.  I also kept the enclosing if { ... }.  The reason for this is to allow Kotlin to infer that reachOnlyResult cannot be null in the call to `assertDpResultsEqual()` later in this function.
</blockquote></details>

One alternative is to use `reachOnlyResult!!`afterwards. But I think the choice is from you.


<!-- Sent from Reviewable.io -->

2022-09-04 19:44 UTC, pasin30055 requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/676)* status: 4 of 8 files reviewed, 2 unresolved discussions (waiting on @matthewclegg, @pasin30055, and @renjiezh)

___
*[`src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/liquid_legions_v2_encryption_utility.cc` line 583 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/676#-NAlkU8LX3KHjyLT5CwG-r1-583:-NB9--Kf15_Wt4G_HhR9:b753b8h) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/505f7ca22a969fd1da049baded1a1d2ebab01c37/src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/liquid_legions_v2_encryption_utility.cc#L583)):*
<details><summary><i>Previously, matthewclegg (Matthew Clegg) wrote…</i></summary><blockquote>

As far as I can tell, the noise parameters are only omitted in debugging.  In production, these parameters are always included.  I have added a comment to that effect.
</blockquote></details>

I see. Thanks for the clarification. This is fine then.
___
*[`src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/liquid_legions_v2_encryption_utility.cc` line 628 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/676#-NAlkU8LX3KHjyLT5CwG-r1-628:-NB9-g-B4ICquyHVsvfM:b-nl2bop) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/505f7ca22a969fd1da049baded1a1d2ebab01c37/src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/liquid_legions_v2_encryption_utility.cc#L628)):*
<details><summary><i>Previously, matthewclegg (Matthew Clegg) wrote…</i></summary><blockquote>

Ah, thanks for finding that.  I meant to use 'random_count' in place of 'register_id' in line 631.
</blockquote></details>

LGTM now. Thanks!
___
*[`src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/liquid_legions_v2_encryption_utility.cc` line 630 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/676#-NAlkU8LX3KHjyLT5CwG-r1-630:-NB9-N2x71Wva9_e3zui:b-dyakug) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/505f7ca22a969fd1da049baded1a1d2ebab01c37/src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/liquid_legions_v2_encryption_utility.cc#L630)):*
<details><summary><i>Previously, matthewclegg (Matthew Clegg) wrote…</i></summary><blockquote>

I suppose that if we are bypassing SKA, then there is probably no danger of leaking the number of publishers that contributed to a given register.  On the other hand, if we randomize the register counts, it seems to give an extra level of assurance.  Do you think there could be a problem with this?
</blockquote></details>

No, I don't think there is any problem with randomizing both, so the current code is fine.
___
*[`src/test/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/liquid_legions_v2_encryption_utility_test.cc` line 689 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/676#-NAlkU8LX3KHjyLT5CwL-r1-689:-NB90cFd1pu1zw3Lnfzy:b-hlqskb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/505f7ca22a969fd1da049baded1a1d2ebab01c37/src/test/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/liquid_legions_v2_encryption_utility_test.cc#L689)):*
<details><summary><i>Previously, matthewclegg (Matthew Clegg) wrote…</i></summary><blockquote>

That is essentially what is tested in `FrequencyOneWorksAsExpectedWithoutNoise` and `FrequencyOneWorksAsExpectedWithNoise`.  If you think there are other things that should be tested, please let me know.
</blockquote></details>

The current tests LGTM. Thanks.


<!-- Sent from Reviewable.io -->

2022-09-04 19:45 UTC, pasin30055 approved these changes

2022-09-09 17:00 UTC, wangyaopw reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/676)* status: 4 of 8 files reviewed, 7 unresolved discussions (waiting on @benjaminkreuter, @duliomatos1, @matthewclegg, and @renjiezh)

___
*[`src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/liquid_legions_v2_encryption_utility.cc` line 564 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/676#-NBY8Eai8cFDYzlwRjup:-NBY8Eai8cFDYzlwRjuq:b-lmfwtc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6029678bb4bb187b65f7d17439076be80a3c682c/src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/liquid_legions_v2_encryption_utility.cc#L564)):*
> ```cpp
> 
> // Copies encrypted registers, replacing all keys with
> // the destroyed register flag and all counts with random values.
> ```

I feel this is not necessary.

The count doesn't need to be destroyed since it is not used anywhere at all and we are not leaking anything if we don't destroy it.

For the keys, we are still adding noise for the reach. If we are fine with the current LLV2 protocol, there is nothing extra we need to hide for the reach only protocol.



_Code quote:_
```cpp
DestroyKeysAndCounts(
```
___
*[`src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/liquid_legions_v2_encryption_utility.cc` line 573 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/676#-NBY0IoL83POKfU93LIg:-NBY0IoL83POKfU93LIh:bhc1qpv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6029678bb4bb187b65f7d17439076be80a3c682c/src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/liquid_legions_v2_encryption_utility.cc#L573)):*
> ```cpp
> 
>   if (register_count == 0) {
>     return dest;
> ```

nit: just move this check after `  std::string source = request.combined_register_vector();` and check if source is empty.



_Code quote:_
```cpp
  if (register_count == 0) {
    return dest;
  }
```
___
*[`src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/liquid_legions_v2_encryption_utility.cc` line 831 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/676#-NBYBTby9vZUr6kebaoL:-NBYBTby9vZUr6kebaoM:b-6h561c) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6029678bb4bb187b65f7d17439076be80a3c682c/src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/liquid_legions_v2_encryption_utility.cc#L831)):*
> ```cpp
>   // Add noise (flag_a, flag_b, flag_c, count) tuples if configured to.
>   if (request.has_noise_parameters()) {
>     RETURN_IF_ERROR(AddAllFrequencyNoise(*protocol_cryptor, request.curve_id(),
> ```

You are still adding frequency noise when the maximum_frequency is set to 1.

But we can not just simply stop adding this noise here, since when we compensate for frequency noise when estimating reach at the aggregator. If we modify here, we need to adjust the code for reach estimate too.
___
*[`src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/liquid_legions_v2_encryption_utility.cc` line 884 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/676#-NBYB1_9DmS7ujt-bm0w:-NBYB1_9DmS7ujt-bm0x:b-6h561c) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6029678bb4bb187b65f7d17439076be80a3c682c/src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/liquid_legions_v2_encryption_utility.cc#L884)):*
> ```cpp
>   // Add noise (flag_a, flag_b, flag_c, count) tuples if configured to.
>   if (request.has_noise_parameters()) {
>     RETURN_IF_ERROR(AddAllFrequencyNoise(*protocol_cryptor, request.curve_id(),
> ```

You are still adding frequency noise when the maximum_frequency is set to 1.

But we can not just simply stop adding this noise here, since when we compensate for frequency noise when estimating reach at the aggregator. If we modify here, we need to adjust the code for reach estimate too.



_Code quote:_
```cpp
AddAllFrequencyNoise
```
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2Mill.kt` line 722 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/676#-NBY1pSm1vK_NvzE1_jZ:-NBY1pSm1vK_NvzE1_j_:b-uahua4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6029678bb4bb187b65f7d17439076be80a3c682c/src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2Mill.kt#L722)):*
> ```Kotlin
>   }
> 
>   private suspend fun sendResultToKingdom(
> ```

nit: move this function to the bottom, so all `completeExecutionPhaseXAtY()` methods are together



_Code quote:_
```Kotlin
  private suspend fun sendResultToKingdom(
```


<!-- Sent from Reviewable.io -->

2022-09-09 21:32 UTC, benjaminkreuter commented on src/main/cc/wfa/measurement/common/crypto/constants.h
> +// Elliptic curve to be used when none is specified.
We should indicate what curve this is (the name of the curve), right now it is just a magic number.

2022-09-09 21:51 UTC, kungfucraig reviewed
> Reviewed 3 of 8 files at r1, 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/676)* status: 3 of 8 files reviewed, 10 unresolved discussions (waiting on @duliomatos1, @kungfucraig, @matthewclegg, @renjiezh, and @wangyaopw)

___
*[`src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/liquid_legions_v2_encryption_utility.cc` line 564 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/676#-NBY8Eai8cFDYzlwRjup:-NBYHIFR9YPkmeRw810h:bpk17z9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6029678bb4bb187b65f7d17439076be80a3c682c/src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/liquid_legions_v2_encryption_utility.cc#L564)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

I feel this is not necessary.

The count doesn't need to be destroyed since it is not used anywhere at all and we are not leaking anything if we don't destroy it.

For the keys, we are still adding noise for the reach. If we are fine with the current LLV2 protocol, there is nothing extra we need to hide for the reach only protocol.
</blockquote></details>

I think the reason to do this would be to be able to guarantee frequency is not revealed, even to a worker.
___
*[`src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/liquid_legions_v2_encryption_utility.cc` line 671 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/676#-NBZDV8a2wEM9ftZKQq5:-NBZDV8a2wEM9ftZKQq6:bucui6e) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6029678bb4bb187b65f7d17439076be80a3c682c/src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/liquid_legions_v2_encryption_utility.cc#L671)):*
> ```cpp
> 
>   if (request.maximum_frequency() == 1) {
>     *response_crv = *DestroyKeysAndCounts(request);
> ```

Why not just strip them when the protocol starts (i.e. setup phase) and you can stop carrying them around? I appreciate this may be a much more disruptive change and that it may not be desirable if you're trying to get this done as quick as possible. 
___
*[`src/main/proto/wfa/measurement/internal/duchy/protocol/liquid_legions_v2_encryption_methods.proto` line 115 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/676#-NBZCh9J44k7wv5Z0-q9:-NBZCh9J44k7wv5Z0-qA:b-zgxexd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6029678bb4bb187b65f7d17439076be80a3c682c/src/main/proto/wfa/measurement/internal/duchy/protocol/liquid_legions_v2_encryption_methods.proto#L115)):*
> ```protobuf
>   // The maximum frequency that should be computed.
>   // If set to 1, then no frequency histogram is returned.
>   int32 maximum_frequency = 3;
> ```

Using in band signaling, in this case measurement frequency, to indicate fundamentally different behavior is generally undesirable. It's better to be explicit. A field called "compute_reach_only" would make more sense. That said, setting a maximum frequency has its own usefulness.

https://www.atlasobscura.com/articles/capn-crunch-whistle :)


<!-- Sent from Reviewable.io -->

2022-09-09 21:53 UTC, kungfucraig reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/676)* status: 3 of 8 files reviewed, 10 unresolved discussions (waiting on @duliomatos1, @kungfucraig, @matthewclegg, @renjiezh, and @wangyaopw)

___
*[`src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/liquid_legions_v2_encryption_utility.cc` line 564 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/676#-NBY8Eai8cFDYzlwRjup:-NBZEHhm2S2xH34YtHqN:bku3207) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6029678bb4bb187b65f7d17439076be80a3c682c/src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/liquid_legions_v2_encryption_utility.cc#L564)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

I think the reason to do this would be to be able to guarantee frequency is not revealed, even to a worker.
</blockquote></details>

Consider computing frequency at some later time from the residue of the reach calculation. Virtual "shredding" of the counts and keys precludes this.


<!-- Sent from Reviewable.io -->

2022-09-09 22:14 UTC, wangyaopw reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/676)* status: 2 of 8 files reviewed, 10 unresolved discussions (waiting on @duliomatos1, @kungfucraig, @matthewclegg, and @renjiezh)

___
*[`src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/liquid_legions_v2_encryption_utility.cc` line 564 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/676#-NBY8Eai8cFDYzlwRjup:-NBZIEOl5q0G2lG_34L2:b-jdqyk9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6029678bb4bb187b65f7d17439076be80a3c682c/src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/liquid_legions_v2_encryption_utility.cc#L564)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Consider computing frequency at some later time from the residue of the reach calculation. Virtual "shredding" of the counts and keys precludes this.
</blockquote></details>

For reach only measurement, all workers will mark the computation COMPLETED after phase two. Unless all workers collude (a case we don't consider), we don't need to worry about any worker can learn the frequency.

As a temporary solution, I feel there is no need to add such precaution.


<!-- Sent from Reviewable.io -->

2022-09-09 22:19 UTC, matthewclegg reviewed
> Dismissed @pasin30055 from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/676)* status: 2 of 8 files reviewed, 8 unresolved discussions (waiting on @benjaminkreuter, @duliomatos1, @kungfucraig, @renjiezh, and @wangyaopw)

___
*[`src/main/cc/wfa/measurement/common/crypto/constants.h` line 59 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/676#-NAlkU8LX3KHjyLT5CwF-r3-59:-NBZKSCU1038w4cI10Jq:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0ebc78c2d6691562a4109125d89555f336f1da0a/src/main/cc/wfa/measurement/common/crypto/constants.h#L59)):*
<details><summary><i>Previously, benjaminkreuter wrote…</i></summary><blockquote>

We should indicate what curve this is (the name of the curve), right now it is just a magic number.
</blockquote></details>

Done.
___
*[`src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/liquid_legions_v2_encryption_utility.cc` line 564 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/676#-NBY8Eai8cFDYzlwRjup:-NBYzL70--wJaHBwvf6M:b2u5zeo) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6029678bb4bb187b65f7d17439076be80a3c682c/src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/liquid_legions_v2_encryption_utility.cc#L564)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

I feel this is not necessary.

The count doesn't need to be destroyed since it is not used anywhere at all and we are not leaking anything if we don't destroy it.

For the keys, we are still adding noise for the reach. If we are fine with the current LLV2 protocol, there is nothing extra we need to hide for the reach only protocol.
</blockquote></details>

To me it seemed like randomizing the counts added an extra level of safety to the code.  After this function returns, one can be mathematically certain that there is no danger of information about the counts being leaked by subsequent operations, even if there are bugs in the code or someone in the future accidentally changes the code.  Nonetheless, you are the second person to make this comment.  If you feel strongly about this, let me know and I will remove the code that randomizes the counts.
___
*[`src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/liquid_legions_v2_encryption_utility.cc` line 573 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/676#-NBY0IoL83POKfU93LIg:-NBZ-rTh9VRU2GHqybLR:b6j42ih) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6029678bb4bb187b65f7d17439076be80a3c682c/src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/liquid_legions_v2_encryption_utility.cc#L573)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

nit: just move this check after `  std::string source = request.combined_register_vector();` and check if source is empty.
</blockquote></details>

I made this change, but I am just wondering, could you explain how this improves the code?
___
*[`src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/liquid_legions_v2_encryption_utility.cc` line 671 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/676#-NBZDV8a2wEM9ftZKQq5:-NBZJPeL9GrNn_dZagPT:bro1boo) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6029678bb4bb187b65f7d17439076be80a3c682c/src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/liquid_legions_v2_encryption_utility.cc#L671)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Why not just strip them when the protocol starts (i.e. setup phase) and you can stop carrying them around? I appreciate this may be a much more disruptive change and that it may not be desirable if you're trying to get this done as quick as possible. 
</blockquote></details>

Agreed, that would be a much better long-term solution.  But if you are going to do that, one might as well take the extra step of actually creating a separate reach-only protocol.
___
*[`src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/liquid_legions_v2_encryption_utility.cc` line 831 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/676#-NBYBTby9vZUr6kebaoL:-NBZ0R3T1FEIdGD1NOz2:b-2nwm77) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6029678bb4bb187b65f7d17439076be80a3c682c/src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/liquid_legions_v2_encryption_utility.cc#L831)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

You are still adding frequency noise when the maximum_frequency is set to 1.

But we can not just simply stop adding this noise here, since when we compensate for frequency noise when estimating reach at the aggregator. If we modify here, we need to adjust the code for reach estimate too.
</blockquote></details>

If the frequency is 1, then `completeExecutePhaseOneAtAggregator` in `LiquidLegionsV2Mill.kt` will not set the `noise_parameters` field.  Hence, the test at line 830 will be false and line 831 will not be executed.  See line 501 of `LiquidLegionsV2Mill.kt`.

The reach estimate is adjusted at line 945 in this file.  Lines 944-945 now read:

```
    if (flags[0] && !flags[1] && !flags[2] &&
        (request.maximum_frequency() > 1)) {
```

Note that the code is now checking that the `maximum_frequency` is greater than 1.
___
*[`src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/liquid_legions_v2_encryption_utility.cc` line 884 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/676#-NBYB1_9DmS7ujt-bm0w:-NBZ1rVP5T443Ze9za3p:bx8jl71) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6029678bb4bb187b65f7d17439076be80a3c682c/src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/liquid_legions_v2_encryption_utility.cc#L884)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

You are still adding frequency noise when the maximum_frequency is set to 1.

But we can not just simply stop adding this noise here, since when we compensate for frequency noise when estimating reach at the aggregator. If we modify here, we need to adjust the code for reach estimate too.
</blockquote></details>

If the `maximum_frequency` is 1, then `completeExecutionPhaseTwoAtNonAggregator` will not set the noise parameters in the `CompleteExecutionPhaseTwoRequest` proto message.  See line 687 of `LiquidLegionsV2Mill.kt`.  Consequently, the test at line 883 will fail and line 884 will not be executed.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulator.kt` line 223 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/676#-NAz80TT8bzjjx3qcBVD:-NBYyMbP9otVqXrsD-Tf:b-7h37jh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/505f7ca22a969fd1da049baded1a1d2ebab01c37/src/main/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulator.kt#L223)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

One alternative is to use `reachOnlyResult!!`afterwards. But I think the choice is from you.
</blockquote></details>

The !! operator is unsafe and I think its use is discouraged in Kotlin.

https://kotlinlang.org/docs/null-safety.html
___
*[`src/main/proto/wfa/measurement/internal/duchy/protocol/liquid_legions_v2_encryption_methods.proto` line 115 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement [...]

2022-09-09 22:31 UTC, matthewclegg reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/676)* status: 2 of 8 files reviewed, 8 unresolved discussions (waiting on @benjaminkreuter, @duliomatos1, @kungfucraig, @renjiezh, and @wangyaopw)

___
*[`src/main/proto/wfa/measurement/internal/duchy/protocol/liquid_legions_v2_encryption_methods.proto` line 115 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/676#-NBZCh9J44k7wv5Z0-q9:-NBZMf7fBvb7sGfwT40k:bjf79wa) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6029678bb4bb187b65f7d17439076be80a3c682c/src/main/proto/wfa/measurement/internal/duchy/protocol/liquid_legions_v2_encryption_methods.proto#L115)):*
<details><summary><i>Previously, matthewclegg (Matthew Clegg) wrote…</i></summary><blockquote>

I love the Cap'n Crunch example (do they still make that?), but I think I would respectfully beg to disagree on this point.  In my view, the contract is defined by the MeasurementSpec proto.  I am not changing the contract or adding hidden functionality.  I am optimizing the implementation of one particular execution path.  
</blockquote></details>

Maybe there is a larger point here, though.  The reason for this PR is that I discovered that an MC could submit a measurement request that causes the Duchies to perform arbitrarily long computations.  This could be the basis of a denial of service attack, and perhaps there should be some hardening built into the system to safeguard against that.

In a separate PR, of course!


<!-- Sent from Reviewable.io -->

2022-09-09 22:55 UTC, wangyaopw approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/676)* status: 2 of 8 files reviewed, 7 unresolved discussions (waiting on @benjaminkreuter, @duliomatos1, @kungfucraig, @matthewclegg, and @renjiezh)

___
*[`src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/liquid_legions_v2_encryption_utility.cc` line 564 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/676#-NBY8Eai8cFDYzlwRjup:-NBZSPCi7jzXVIYq0anM:br02ali) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6029678bb4bb187b65f7d17439076be80a3c682c/src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/liquid_legions_v2_encryption_utility.cc#L564)):*
<details><summary><i>Previously, matthewclegg (Matthew Clegg) wrote…</i></summary><blockquote>

To me it seemed like randomizing the counts added an extra level of safety to the code.  After this function returns, one can be mathematically certain that there is no danger of information about the counts being leaked by subsequent operations, even if there are bugs in the code or someone in the future accidentally changes the code.  Nonetheless, you are the second person to make this comment.  If you feel strongly about this, let me know and I will remove the code that randomizes the counts.
</blockquote></details>

It doesn't matter if we are going to replace this with a real reach-only protocol in the future.

up to you to keep this or not
___
*[`src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/liquid_legions_v2_encryption_utility.cc` line 573 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/676#-NBY0IoL83POKfU93LIg:-NBZRRTQBLoBzJj0KsLl:b-bi2ja5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6029678bb4bb187b65f7d17439076be80a3c682c/src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/liquid_legions_v2_encryption_utility.cc#L573)):*
<details><summary><i>Previously, matthewclegg (Matthew Clegg) wrote…</i></summary><blockquote>

I made this change, but I am just wondering, could you explain how this improves the code?
</blockquote></details>

No big difference. 

If `source` is empty, there is no need to call `GetNumberOfBlocks()` to know the result

:smile: 



_Code quote:_
```cpp
GetNumberOfBlocks
```
___
*[`src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/liquid_legions_v2_encryption_utility.cc` line 831 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/676#-NBYBTby9vZUr6kebaoL:-NBZRsG-5D6ekJ4ydDmo:bsv1uu9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6029678bb4bb187b65f7d17439076be80a3c682c/src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/liquid_legions_v2_encryption_utility.cc#L831)):*
<details><summary><i>Previously, matthewclegg (Matthew Clegg) wrote…</i></summary><blockquote>

If the frequency is 1, then `completeExecutePhaseOneAtAggregator` in `LiquidLegionsV2Mill.kt` will not set the `noise_parameters` field.  Hence, the test at line 830 will be false and line 831 will not be executed.  See line 501 of `LiquidLegionsV2Mill.kt`.

The reach estimate is adjusted at line 945 in this file.  Lines 944-945 now read:

```
    if (flags[0] && !flags[1] && !flags[2] &&
        (request.maximum_frequency() > 1)) {
```

Note that the code is now checking that the `maximum_frequency` is greater than 1.


</blockquote></details>

I see. That works. Nice


<!-- Sent from Reviewable.io -->

2022-09-09 23:18 UTC, wangyaopw reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/676)* status: 2 of 8 files reviewed, 4 unresolved discussions (waiting on @benjaminkreuter, @duliomatos1, @kungfucraig, and @renjiezh)

___
*[`src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/liquid_legions_v2_encryption_utility.cc` line 564 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/676#-NBY8Eai8cFDYzlwRjup:-NBZXRQ92ijNz1IxY5HA:bumpu9o) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6029678bb4bb187b65f7d17439076be80a3c682c/src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/liquid_legions_v2_encryption_utility.cc#L564)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

It doesn't matter if we are going to replace this with a real reach-only protocol in the future.

up to you to keep this or not
</blockquote></details>

An even better solution is to update the sketch encryptor used by the publishers to use random numbers for key and count if the measurement is REACH_ONLY.  then we can preclude the issue from the source.


<!-- Sent from Reviewable.io -->

2022-09-16 15:08 UTC, duliomatos1 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/676)* status: 2 of 8 files reviewed, 4 unresolved discussions (waiting on @benjaminkreuter, @duliomatos1, @kungfucraig, @matthewclegg, @pasin30055, @renjiezh, and @wangyaopw)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulator.kt` line 223 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/676#-NAz80TT8bzjjx3qcBVD:-NC5mM0F8pBL9vSpwIBS:bw8pula) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/505f7ca22a969fd1da049baded1a1d2ebab01c37/src/main/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulator.kt#L223)):*
<details><summary><i>Previously, matthewclegg (Matthew Clegg) wrote…</i></summary><blockquote>

The !! operator is unsafe and I think its use is discouraged in Kotlin.

https://kotlinlang.org/docs/null-safety.html
</blockquote></details>

we' ve been using `checkNotNull()` for these checks (It throws `IllegalStateException`), and you can pass a block with a message e.g.

RequisitionReader.kt:
```
163:          checkNotNull(DuchyIds.getExternalId(duchyId)) {
164-            "Duchy with internal ID $duchyId not found"
165-          }
```


`requireNotNull()` is similar, semantically would be used for confirming function inputs contracts (throws IllegalArgumentException)


<!-- Sent from Reviewable.io -->

2022-09-16 17:18 UTC, benjaminkreuter approved these changes
> Reviewed 4 of 8 files at r1, 1 of 3 files at r2, 2 of 2 files at r3, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/676)* status: all files reviewed, 4 unresolved discussions (waiting on @benjaminkreuter, @kungfucraig, @matthewclegg, and @renjiezh)



<!-- Sent from Reviewable.io -->

2022-09-16 18:21 UTC, duliomatos1 requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/676)* status: all files reviewed, 4 unresolved discussions (waiting on @benjaminkreuter, @kungfucraig, @matthewclegg, and @renjiezh)



<!-- Sent from Reviewable.io -->

2022-09-16 19:51 UTC, matthewclegg reviewed
> Reviewed 1 of 8 files at r1, 1 of 3 files at r2, 1 of 2 files at r3, 1 of 1 files at r5, 2 of 2 files at r6, all commit messages.
> Dismissed @kungfucraig from 2 discussions.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/676)* status: all files reviewed, 2 unresolved discussions (waiting on @benjaminkreuter and @duliomatos1)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulator.kt` line 223 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/676#-NAz80TT8bzjjx3qcBVD:-NC6qhmO1easAuPqS4rf:b-h5rv17) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/505f7ca22a969fd1da049baded1a1d2ebab01c37/src/main/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulator.kt#L223)):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

we' ve been using `checkNotNull()` for these checks (It throws `IllegalStateException`), and you can pass a block with a message e.g.

RequisitionReader.kt:
```
163:          checkNotNull(DuchyIds.getExternalId(duchyId)) {
164-            "Duchy with internal ID $duchyId not found"
165-          }
```


`requireNotNull()` is similar, semantically would be used for confirming function inputs contracts (throws IllegalArgumentException)
</blockquote></details>

Thanks for the suggestion!


<!-- Sent from Reviewable.io -->

2022-09-23 16:34 UTC, matthewclegg reviewed
> Reviewed 2 of 8 files at r1, 1 of 2 files at r3.
> Dismissed @benjaminkreuter from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/676)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @matthewclegg)



<!-- Sent from Reviewable.io -->

2022-09-23 16:34 UTC, merged