Separate key pairs in EncryptionKeyPairStore by principal
world-federation-of-advertisers/cross-media-measurement pull request #700
Opened 2022-09-23 03:14 UTC by duliomatos1

Enable multi tenancy for the reporting server by making `EncryptionKeyPairStore` handles private key pairs by principal.
* Consumers of the key pair store now pass the principal along with the public key in order to retrieve the private key
* Configuration using textproto for `EncryptionKeyPairConfig` message is updated to define key pairs by principal 
* Doesn't change the current way of obtaining the key pairs by by loading from each key file path

2022-09-23 03:37 UTC, renjiezh requested changes
Thanks for the work. Looks good to me. I left some nitpicks

> Reviewed 10 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/700#-:-NCcOvP75ah9oIiB9Buw:bft3ohi)* status: 10 of 11 files reviewed, 3 unresolved discussions (waiting on @duliomatos1, @riemanli, and @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/config/reporting/encryption_key_pair_config.proto` line 31 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/700#-NCcLTw7-qrWgDpXaAuj:-NCcLTw8BDxefa7bRIPA:behmgn6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dab4e4e423c4a634443ba4ff2260aa86e6550f99/src/main/proto/wfa/measurement/config/reporting/encryption_key_pair_config.proto#L31)):*
> ```protobuf
>   message PrincipalKeyPairs {
>     string principal = 1;
>     repeated KeyPair keyPair = 2;
> ```

nit: could name as keyPairs.
___
*[`src/main/proto/wfa/measurement/config/reporting/encryption_key_pair_config.proto` line 33 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/700#-NCcLgsJ3Xbojcys2WLK:-NCcLgsJ3Xbojcys2WLL:b72pk5h) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dab4e4e423c4a634443ba4ff2260aa86e6550f99/src/main/proto/wfa/measurement/config/reporting/encryption_key_pair_config.proto#L33)):*
> ```protobuf
>     repeated KeyPair keyPair = 2;
>   }
>   repeated PrincipalKeyPairs keyPairsForPrincipal = 1;
> ```

nit: could rename.
https://cloud.google.com/apis/design/naming_convention#field_names
___
*[`src/test/kotlin/org/wfanet/measurement/reporting/deploy/common/key_pair_map.textproto` line 4 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/700#-NCcOR0m9JYb1H0Ymfi-:-NCcOR0m9JYb1H0Ymfi0:b-ej94nt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dab4e4e423c4a634443ba4ff2260aa86e6550f99/src/test/kotlin/org/wfanet/measurement/reporting/deploy/common/key_pair_map.textproto#L4)):*
> ```
> # proto-message: EncryptionKeyPairConfig
> 
> keyPairsForPrincipal {
> ```

Can we have more than one `keyPairsForPrincipal` entries in this example/test file?


<!-- Sent from Reviewable.io -->

2022-09-23 13:34 UTC, duliomatos1 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/700)* status: 10 of 11 files reviewed, 3 unresolved discussions (waiting on @renjiezh, @riemanli, and @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/config/reporting/encryption_key_pair_config.proto` line 31 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/700#-NCcLTw7-qrWgDpXaAuj:-NCeYBAH1rZvqmJZpRlt:bb7oryy) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dab4e4e423c4a634443ba4ff2260aa86e6550f99/src/main/proto/wfa/measurement/config/reporting/encryption_key_pair_config.proto#L31)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

nit: could name as keyPairs.
</blockquote></details>

sure
___
*[`src/main/proto/wfa/measurement/config/reporting/encryption_key_pair_config.proto` line 33 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/700#-NCcLgsJ3Xbojcys2WLK:-NCeYCuQ4SOjhbfap6Ks:bjsyhxz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dab4e4e423c4a634443ba4ff2260aa86e6550f99/src/main/proto/wfa/measurement/config/reporting/encryption_key_pair_config.proto#L33)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

nit: could rename.
https://cloud.google.com/apis/design/naming_convention#field_names
</blockquote></details>

thanks, will do
___
*[`src/test/kotlin/org/wfanet/measurement/reporting/deploy/common/key_pair_map.textproto` line 4 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/700#-NCcOR0m9JYb1H0Ymfi-:-NCeYG2606GGoEj9aWsW:bb7oryy) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dab4e4e423c4a634443ba4ff2260aa86e6550f99/src/test/kotlin/org/wfanet/measurement/reporting/deploy/common/key_pair_map.textproto#L4)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

Can we have more than one `keyPairsForPrincipal` entries in this example/test file?
</blockquote></details>

sure


<!-- Sent from Reviewable.io -->

2022-09-23 20:18 UTC, duliomatos1 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/700)* status: 6 of 11 files reviewed, 1 unresolved discussion (waiting on @renjiezh, @riemanli, and @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/config/reporting/encryption_key_pair_config.proto` line 31 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/700#-NCcLTw7-qrWgDpXaAuj:-NCfxfL8CsyQTxttHW75:b-7rl0jd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dab4e4e423c4a634443ba4ff2260aa86e6550f99/src/main/proto/wfa/measurement/config/reporting/encryption_key_pair_config.proto#L31)):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

sure
</blockquote></details>

done.
___
*[`src/main/proto/wfa/measurement/config/reporting/encryption_key_pair_config.proto` line 33 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/700#-NCcLgsJ3Xbojcys2WLK:-NCfxotVBIj-7mtW6eeS:b-q7jqg8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dab4e4e423c4a634443ba4ff2260aa86e6550f99/src/main/proto/wfa/measurement/config/reporting/encryption_key_pair_config.proto#L33)):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

thanks, will do
</blockquote></details>

done. Also changed fields to snake_case as stated in the guide
___
*[`src/test/kotlin/org/wfanet/measurement/reporting/deploy/common/key_pair_map.textproto` line 4 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/700#-NCcOR0m9JYb1H0Ymfi-:-NCfxsHA3H1yJZ_dA7gk:b-b7il3o) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dab4e4e423c4a634443ba4ff2260aa86e6550f99/src/test/kotlin/org/wfanet/measurement/reporting/deploy/common/key_pair_map.textproto#L4)):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

sure
</blockquote></details>

done. Also made test use this new entry


<!-- Sent from Reviewable.io -->

2022-09-23 20:19 UTC, renjiezh approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/700#-:-NCg-P4s4GvRVQF10Iik:bnfp4nl)* status: 6 of 11 files reviewed, all discussions resolved (waiting on @renjiezh, @riemanli, and @tristanvuong2021)



<!-- Sent from Reviewable.io -->

2022-09-23 20:48 UTC, tristanvuong2021 requested changes
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/700)* status: all files reviewed, 1 unresolved discussion (waiting on @duliomatos1 and @riemanli)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/700#-NCg5VVpA4k7vJn-hvtg:-NCg5VVpA4k7vJn-hvth:b-jhzo1w) (no related file):*
There is also this section: https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b4e047a20d1b07f23b5c2b9cfce5ee171384259e/src/main/k8s/local/README.md?plain=1#L268

___


<!-- Sent from Reviewable.io -->

2022-09-26 12:07 UTC, duliomatos1 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/700)* status: all files reviewed, 1 unresolved discussion (waiting on @riemanli and @tristanvuong2021)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/700#-NCg5VVpA4k7vJn-hvtg:-NCtgKjy8E8D3xn27spE:bll1jkg) (no related file):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

There is also this section: https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b4e047a20d1b07f23b5c2b9cfce5ee171384259e/src/main/k8s/local/README.md?plain=1#L268
</blockquote></details>

thx @tristanvuong2021, I'll update the doc as well

___


<!-- Sent from Reviewable.io -->

2022-09-26 22:11 UTC, duliomatos1 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/700)* status: 11 of 12 files reviewed, 1 unresolved discussion (waiting on @riemanli and @tristanvuong2021)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/700#-NCg5VVpA4k7vJn-hvtg:-NCvqk3B8PIGGyNjZZL_:b-896fix) (no related file):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

thx @tristanvuong2021, I'll update the doc as well
</blockquote></details>

Done.

___


<!-- Sent from Reviewable.io -->

2022-09-26 22:42 UTC, tristanvuong2021 approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/700)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @riemanli)



<!-- Sent from Reviewable.io -->

2022-09-27 21:54 UTC, riemanli reviewed
Hi Dulio. The changes look good to me. The only concern I have is the test failure from Github action. Could you please resolve the issue?

> Reviewed 6 of 11 files at r1, 5 of 5 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/700#-:-ND-vzmg-Niy4vdb14Kv:b20z1t9)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @duliomatos1)



<!-- Sent from Reviewable.io -->

2022-09-27 22:41 UTC, riemanli approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/700#-:-ND06F400GzjiFWQDpIz:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @duliomatos1)



<!-- Sent from Reviewable.io -->

2022-09-27 22:47 UTC, duliomatos1 reviewed
yeah, I've rebased and it now looks good :-)

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/700#-:-ND07JsI6FlvJ_EkO_Yv:bai5rce)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @duliomatos1)



<!-- Sent from Reviewable.io -->

2022-09-27 22:47 UTC, merged