Use withWaitForReady in Mill
world-federation-of-advertisers/cross-media-measurement pull request #705
Opened 2022-09-27 02:05 UTC by renjiezh

2022-09-27 16:29 UTC, SanjayVas requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/705)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @renjiezh and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/MillBase.kt` line 131 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/705#-NCzgXIgCiucmnnD8g3O:-NCzgXIgCiucmnnD8g3P:b-2doy1b) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/33cee5fdc88b3b17c08782748b5439683a939c3e/src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/MillBase.kt#L131)):*
> ```Kotlin
>       ClaimWorkRequest.newBuilder().setComputationType(computationType).setOwner(millId).build()
>     val claimWorkResponse =
>       withWaitForReady("ComputationServer not ready") {
> ```

What I was referring to was the `withWaitForReady` method on the stub. See https://grpc.github.io/grpc-java/javadoc/io/grpc/stub/AbstractStub.html#withWaitForReady--

This is built-in gRPC behavior which waits until the channel is ready (i.e. doesn't return UNAVAILABLE) rather than exposing that error, which is basically what the code here does.


<!-- Sent from Reviewable.io -->

2022-09-27 17:16 UTC, renjiezh reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/705)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/MillBase.kt` line 131 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/705#-NCzgXIgCiucmnnD8g3O:-NCzwcvX5vr0-t3TKFpH:b-t2h6am) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/33cee5fdc88b3b17c08782748b5439683a939c3e/src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/MillBase.kt#L131)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

What I was referring to was the `withWaitForReady` method on the stub. See https://grpc.github.io/grpc-java/javadoc/io/grpc/stub/AbstractStub.html#withWaitForReady--

This is built-in gRPC behavior which waits until the channel is ready (i.e. doesn't return UNAVAILABLE) rather than exposing that error, which is basically what the code here does.
</blockquote></details>

Done.
Thanks for the suggestion. Now the UNAVAILABLE exceptions are correctly suppressed.


<!-- Sent from Reviewable.io -->

2022-09-27 17:29 UTC, SanjayVas requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/705)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @renjiezh and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/MillBase.kt` line 131 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/705#-NCzgXIgCiucmnnD8g3O:-NCzzfZo2oAaDJtgyJ9V:b5dz9a) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/33cee5fdc88b3b17c08782748b5439683a939c3e/src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/MillBase.kt#L131)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

Done.
Thanks for the suggestion. Now the UNAVAILABLE exceptions are correctly suppressed.
</blockquote></details>

Not seeing a new revision yet. Did you forget to push?


<!-- Sent from Reviewable.io -->

2022-09-27 17:30 UTC, renjiezh reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/705)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/MillBase.kt` line 131 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/705#-NCzgXIgCiucmnnD8g3O:-NCzzyTl0EcGVPnVkXGW:bs2blxs) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/33cee5fdc88b3b17c08782748b5439683a939c3e/src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/MillBase.kt#L131)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Not seeing a new revision yet. Did you forget to push?
</blockquote></details>

Sorry. I am still running some test against it. Will push it after that.


<!-- Sent from Reviewable.io -->

2022-09-27 18:23 UTC, renjiezh reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/705)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/MillBase.kt` line 131 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/705#-NCzgXIgCiucmnnD8g3O:-ND-BCObCUu0lrPUjhgI:bxzudge) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/33cee5fdc88b3b17c08782748b5439683a939c3e/src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/MillBase.kt#L131)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

Sorry. I am still running some test against it. Will push it after that.
</blockquote></details>

Pushed


<!-- Sent from Reviewable.io -->

2022-09-27 18:35 UTC, SanjayVas approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/705)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @renjiezh)



<!-- Sent from Reviewable.io -->

2022-09-27 22:45 UTC, duliomatos1 approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/705)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)



<!-- Sent from Reviewable.io -->

2022-09-28 19:39 UTC, stevenwarejones approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/705)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @renjiezh)



<!-- Sent from Reviewable.io -->

2022-10-04 21:58 UTC, stevenwarejones approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/705)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @renjiezh)



<!-- Sent from Reviewable.io -->

2026-05-07 18:06 UTC, TNATALI commented
No longer a valid PR

2026-05-07 18:06 UTC, closed without merging