Add ContinuationTokenManager to fetch and store tokens
world-federation-of-advertisers/cross-media-measurement pull request #721
Opened 2022-10-06 23:04 UTC by renjiezh

2022-10-06 23:06 UTC, renjiezh commented
@SanjayVas @matthewclegg The draft has the basic structure of the code change (without test yet). Please leave your feedback if you have time to take a look. Appreciate it!

2022-10-07 20:05 UTC, SanjayVas requested changes
> Reviewed 4 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/721)* status: 4 of 6 files reviewed, 5 unresolved discussions (waiting on @renjiezh and @SanjayVas)

___
*[`src/main/k8s/duchy.cue` line 102 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/721#-NDnxPE32Hxfdzq6LozK:-NDnxPE32Hxfdzq6LozL:b6zrrk4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/927eb409c788bedd5b24526d21f4201dcee731cb/src/main/k8s/duchy.cue#L102)):*
> ```CUE
> 			] + _spannerConfig.flags
> 			spec: template: spec: _dependencies: [
> 				"\(_name)-spanner-computations-server",
> ```

Good catch!
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ContinuationTokenManager.kt` line 19 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/721#-NDnz_Qh11Wq3n4NmDGY:-NDnz_Qh11Wq3n4NmDGZ:b-qoe93s) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/927eb409c788bedd5b24526d21f4201dcee731cb/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ContinuationTokenManager.kt#L19)):*
> ```Kotlin
> import java.util.Collections
> 
> interface ContinuationTokenStore {
> ```

Ensure public symbols have KDoc.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ContinuationTokenManager.kt` line 29 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/721#-NDnxg6y73DMf0bbfgg9:-NDnxg6y73DMf0bbfggA:b-vdhuda) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/927eb409c788bedd5b24526d21f4201dcee731cb/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ContinuationTokenManager.kt#L29)):*
> ```Kotlin
>   private val continuationTokenStore: ContinuationTokenStore
> ) {
>   // Items are in Pairs of (continuationToken: String, processed: Boolean).
> ```

nit: either use a custom data class rather than a Pair, or use a LinkedHashMap<String, Boolean> as that preserves insertion order.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ContinuationTokenManager.kt` line 37 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/721#-NDnzS4Q6PbIIMwCly50:-NDnzS4Q6PbIIMwCly51:bg6oayc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/927eb409c788bedd5b24526d21f4201dcee731cb/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ContinuationTokenManager.kt#L37)):*
> ```Kotlin
>   }
> 
>   suspend fun syncContinuationToken(continueToken: String, block: suspend () -> Unit) {
> ```

nit: prefer more descriptive names than `block` when possible. In this case, `process` may be better.



_Code quote:_
```Kotlin
block
```
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ContinuationTokenManager.kt` line 40 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/721#-NDo-FWB-u6PGE3b_sTz:-NDo-FWB-u6PGE3b_sU-:b-8c58ar) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/927eb409c788bedd5b24526d21f4201dcee731cb/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ContinuationTokenManager.kt#L40)):*
> ```Kotlin
>     val seqNumber = continuationTokenList.size
> 
>     continuationTokenList += Pair(continueToken, false)
> ```

It looks like you're calling this method from a `launch` block, so it's not guaranteed that calls to this method will be in sequence order.

You may want a separate method called outside the `launch` block that adds a token to the manager.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ContinuationTokenManager.kt` line 53 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/721#-NDo20dq2L6iOjcdvI1h:-NDnypen41C65vnqbQB9:bmk4947) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/927eb409c788bedd5b24526d21f4201dcee731cb/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ContinuationTokenManager.kt#L53)):*
> ```Kotlin
>     if (lastProcessedIndex >= 0) {
>       val lastProcessedToken = continuationTokenList[lastProcessedIndex].first
>       continuationTokenStore.writeContinuationToken(lastProcessedToken)
> ```

When do tokens get cleared from the manager?


<!-- Sent from Reviewable.io -->

2022-10-07 20:07 UTC, SanjayVas requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/721)* status: 4 of 6 files reviewed, 6 unresolved discussions (waiting on @renjiezh and @SanjayVas)

___
*[`src/main/resources/duchy/spanner/create-computations-schema.sql` line 334 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/721#-NDo2Ot7DI4mhuezB-ig:-NDo2Ot7DI4mhuezB-ih:btf6x9e) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/927eb409c788bedd5b24526d21f4201dcee731cb/src/main/resources/duchy/spanner/create-computations-schema.sql#L334)):*
> ```TSQL
>   INTERLEAVE IN PARENT ComputationStageAttempts ON DELETE CASCADE;
> 
> CREATe TABLE HeraldContinuationTokens (
> ```

Each schema file should be considered frozen. New schema update entries can be added to changelog.yaml.


<!-- Sent from Reviewable.io -->

2022-11-16 23:01 UTC, renjiezh reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/721)* status: 0 of 43 files reviewed, 4 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ContinuationTokenManager.kt` line 19 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/721#-NDnz_Qh11Wq3n4NmDGY:-NH1ewMO7Qm44-e_PDjx:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/927eb409c788bedd5b24526d21f4201dcee731cb/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ContinuationTokenManager.kt#L19)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Ensure public symbols have KDoc.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ContinuationTokenManager.kt` line 40 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/721#-NDo-FWB-u6PGE3b_sTz:-NH1eyNP9SZC6eQ-PTan:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/927eb409c788bedd5b24526d21f4201dcee731cb/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ContinuationTokenManager.kt#L40)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

It looks like you're calling this method from a `launch` block, so it's not guaranteed that calls to this method will be in sequence order.

You may want a separate method called outside the `launch` block that adds a token to the manager.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ContinuationTokenManager.kt` line 53 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/721#-NDo20dq2L6iOjcdvI1h:-NDo2iumDKBM9bpj6w2Z:bj60puv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/927eb409c788bedd5b24526d21f4201dcee731cb/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ContinuationTokenManager.kt#L53)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

When do tokens get cleared from the manager?
</blockquote></details>

When herald reads the latest token, it clear the list to preparing for the streaming.
___
*[`src/main/resources/duchy/spanner/create-computations-schema.sql` line 334 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/721#-NDo2Ot7DI4mhuezB-ig:-NH1fB6C5GASNmcvGERp:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/927eb409c788bedd5b24526d21f4201dcee731cb/src/main/resources/duchy/spanner/create-computations-schema.sql#L334)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Each schema file should be considered frozen. New schema update entries can be added to changelog.yaml.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-11-17 02:05 UTC, SanjayVas requested changes
> Reviewed 12 of 43 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/721)* status: 12 of 43 files reviewed, 10 unresolved discussions (waiting on @kungfucraig, @matthewclegg, and @renjiezh)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ContinuationTokenManager.kt` line 19 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/721#-NDnz_Qh11Wq3n4NmDGY:-NH28qtA1BuspByYktEZ:berckbz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/927eb409c788bedd5b24526d21f4201dcee731cb/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ContinuationTokenManager.kt#L19)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

Done.
</blockquote></details>

1. I see regular comments, not KDoc.
2. The class itself doesn't have KDoc.

See https://developer.android.com/kotlin/style-guide#documentation
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ContinuationTokenManager.kt` line 33 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/721#-NH29nDVEqfanKqlul-H:-NH29nDVEqfanKqlul-I:b-4k35py) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b834b603705944ef1a3740ea9ae464c2a0febdd6/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ContinuationTokenManager.kt#L33)):*
> ```Kotlin
>   }
> 
>   // Items are in Pairs of (continuationToken: String, processed: Boolean).
> ```

nit: out-of-date comment



_Code quote:_
```Kotlin
Items are in Pairs of (continuationToken: String, processed: Boolean).
```
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/db/continuationtoken/ContinuationTokens.kt` line 18 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/721#-NH2GNec--BmvflmIlGJ:-NH2GNec--BmvflmIlGK:bxjowe2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b834b603705944ef1a3740ea9ae464c2a0febdd6/src/main/kotlin/org/wfanet/measurement/duchy/db/continuationtoken/ContinuationTokens.kt#L18)):*
> ```Kotlin
> 
> /** Stores the latest continuation token. Support read and write operation */
> interface ContinuationTokens {
> ```

No need for a separate interface. The pattern we follow now for DB services is that the internal service definition is the interface, where there's a separate implementation for each DBMS library (i.e. Spanner).

As we've discussed before, the Duchy follows an old pattern for its DB abstraction (see `ComputationsDatabaseReader`, `ComputationsDatabaseTransactor`). Note that you're not following that pattern here either, so might as well follow the new pattern. See //src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner:services for examples.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/herald/BUILD.bazel` line 13 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/721#-NH2InU31q2HmQGpysZC:-NH2InU48zQ007NnFCyQ:b-63mlt0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d85919b12bc389f57797ecb7a06921fbe69371f0/src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/herald/BUILD.bazel#L13)):*
> ```Starlark
>         "//src/main/kotlin/org/wfanet/measurement/duchy/deploy/common:flags",
>         "//src/main/proto/wfa/measurement/internal/duchy:computations_service_kt_jvm_grpc_proto",
>         "//src/main/proto/wfa/measurement/system/v1alpha:computation_participants_service_kt_jvm_grpc_proto",
> ```

Why drop this? HeraldDaemon still appears to reference `ComputationParticipantsCoroutineStub`
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/herald/BUILD.bazel` line 13 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/721#-NH2Iubt0JGyMDfkspY4:-NH2IiQ61q8iHfSdU3a9:b-65264s) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b834b603705944ef1a3740ea9ae464c2a0febdd6/src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/herald/BUILD.bazel#L13)):*
> ```Starlark
>         "//src/main/kotlin/org/wfanet/measurement/duchy/deploy/common:flags",
>         "//src/main/proto/wfa/measurement/internal/duchy:computations_service_kt_jvm_grpc_proto",
>         "//src/main/proto/wfa/measurement/system/v1alpha:computations_service_kt_jvm_grpc_proto",
> ```

Shouldn't there be a dependency on `continuation_tokens_service_kt_jvm_grpc_proto` to get access to `ContinuationTokensCoroutineStub`?

Note that our policy is to follow strict deps, i.e. have a direct dependency on everything you use and not rely on transitive deps. This will eventually be enforced once enforcement is working in rules_kotlin. See https://github.com/bazelbuild/rules_kotlin/issues/520
___
*[`src/main/proto/wfa/measurement/internal/duchy/continuation_tokens_service.proto` line 22 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/721#-NH2B_zu11LKCGKbcj2E:-NH2B_zu11LKCGKbcj2F:b-ccbp36) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b834b603705944ef1a3740ea9ae464c2a0febdd6/src/main/proto/wfa/measurement/internal/duchy/continuation_tokens_service.proto#L22)):*
> ```protobuf
> option java_multiple_files = true;
> 
> // Service to get and update continuation token by a Herald.
> ```

nit: remove all the Herald references here, as that's an implementation detail at this layer and not relevant to the service design. (The service doesn't care that this is called by the Herald and only cares that there is at most one token per Duchy).



_Code quote:_
```protobuf
 by a Herald.
```
___
*[`src/main/resources/duchy/spanner/changelog.yaml` line 22 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/721#-NH2AQBd0PPk8TLfw8va:-NH2AQBd0PPk8TLfw8vb:b-dmnvln) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b834b603705944ef1a3740ea9ae464c2a0febdd6/src/main/resources/duchy/spanner/changelog.yaml#L22)):*
> ```YAML
>     relativeToChangeLogFile: true
> - include:
>     file: create-herald-continuation-tokens-schema.sql
> ```

nit: `table`

This is adding a table to the schema of the computations DB.



_Code quote:_
```YAML
schema
```
___
*[`src/main/resources/duchy/spanner/create-herald-continuation-tokens-schema.sql` line 20 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/721#-NH2Cw0iAofCuRs8Jh_4:-NH2Cw0iAofCuRs8Jh_5:b-zdhc9g) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b834b603705944ef1a3740ea9ae464c2a0febdd6/src/main/resources/duchy/spanner/create-herald-continuation-tokens-schema.sql#L20)):*
> ```TSQL
> -- preconditions onFail:MARK_RAN onError:HALT
> -- precondition-sql-check expectedResult:0 SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'HeraldContinuationTokens'
> ```

The precondition and batch were artifacts of converting the original separate DDL statements into a single batch for efficiency. That's not needed here. Just


```sql
-- changeset renjiez:2:dbms:cloudspanner
```

right above the `CREATE TABLE` statement



_Code quote:_
```TSQL
-- changeset renjiez:1 dbms:cloudspanner
-- preconditions onFail:MARK_RAN onError:HALT
-- precondition-sql-check expectedResult:0 SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'HeraldContinuationTokens'

START BATCH DDL;
```
___
*[`src/main/resources/duchy/spanner/create-herald-continuation-tokens-schema.sql` line 23 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/721#-NH2Ajsi7E4dLzabWZ8y:-NH2Ajsi7E4dLzabWZ8z:btqajtl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measur [...]

2022-11-17 21:20 UTC, renjiezh reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/721)* status: 3 of 46 files reviewed, 6 unresolved discussions (waiting on @kungfucraig, @matthewclegg, and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ContinuationTokenManager.kt` line 19 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/721#-NDnz_Qh11Wq3n4NmDGY:-NH5l7U2D16mgDzYi74f:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/927eb409c788bedd5b24526d21f4201dcee731cb/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ContinuationTokenManager.kt#L19)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

1. I see regular comments, not KDoc.
2. The class itself doesn't have KDoc.

See https://developer.android.com/kotlin/style-guide#documentation
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/herald/BUILD.bazel` line 13 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/721#-NH2InU31q2HmQGpysZC:-NH5lx-H9SakL2oiZ9az:bok2blg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d85919b12bc389f57797ecb7a06921fbe69371f0/src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/herald/BUILD.bazel#L13)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Why drop this? HeraldDaemon still appears to reference `ComputationParticipantsCoroutineStub`
</blockquote></details>

Done.
Add it back.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/herald/BUILD.bazel` line 13 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/721#-NH2Iubt0JGyMDfkspY4:-NH5mCMY7W3xpGtyfU3r:b-atalsf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b834b603705944ef1a3740ea9ae464c2a0febdd6/src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/herald/BUILD.bazel#L13)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Shouldn't there be a dependency on `continuation_tokens_service_kt_jvm_grpc_proto` to get access to `ContinuationTokensCoroutineStub`?

Note that our policy is to follow strict deps, i.e. have a direct dependency on everything you use and not rely on transitive deps. This will eventually be enforced once enforcement is working in rules_kotlin. See https://github.com/bazelbuild/rules_kotlin/issues/520
</blockquote></details>

Done.
Thanks for the catch. Do we have any way to force this requirement among building? It is hard to find out whether containing any indirect dependencies.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/db/continuationtoken/ContinuationTokens.kt` line 18 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/721#-NH2GNec--BmvflmIlGJ:-NH6SQuA991b2Zg226vc:b4zwt5z) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b834b603705944ef1a3740ea9ae464c2a0febdd6/src/main/kotlin/org/wfanet/measurement/duchy/db/continuationtoken/ContinuationTokens.kt#L18)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

No need for a separate interface. The pattern we follow now for DB services is that the internal service definition is the interface, where there's a separate implementation for each DBMS library (i.e. Spanner).

As we've discussed before, the Duchy follows an old pattern for its DB abstraction (see `ComputationsDatabaseReader`, `ComputationsDatabaseTransactor`). Note that you're not following that pattern here either, so might as well follow the new pattern. See //src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner:services for examples.
</blockquote></details>

Done.
Please let me if it is good now.
___
*[`src/main/resources/duchy/spanner/create-herald-continuation-tokens-schema.sql` line 20 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/721#-NH2Cw0iAofCuRs8Jh_4:-NH5nEVB-EEzpdJ82ba_:b78b3gr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b834b603705944ef1a3740ea9ae464c2a0febdd6/src/main/resources/duchy/spanner/create-herald-continuation-tokens-schema.sql#L20)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The precondition and batch were artifacts of converting the original separate DDL statements into a single batch for efficiency. That's not needed here. Just


```sql
-- changeset renjiez:2:dbms:cloudspanner
```

right above the `CREATE TABLE` statement
</blockquote></details>

What is the number `1` or `2` for?
___
*[`src/main/resources/duchy/spanner/create-herald-continuation-tokens-schema.sql` line 41 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/721#-NH2D_DQ5MJ1MX5LhOQM:-NH6SUqV72UYcryspf0h:b49l4fo) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b834b603705944ef1a3740ea9ae464c2a0febdd6/src/main/resources/duchy/spanner/create-herald-continuation-tokens-schema.sql#L41)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This is misleading as the entire DB is for a single Duchy. What you really want to represent is a table that will have at most one row. Perhaps something like this:

```sql
CREATE TABLE HeraldContinuationTokens (
  Presence BOOL NOT NULL,
  -- ...
  CONSTRAINT presence_set CHECK(Presence),
) PRIMARY KEY (Presence);
```

The idea is that your primary key is just a boolean that is constrained to be `TRUE`, therefore ensuring that at most one row exists in this table.
</blockquote></details>

Done.
Great idea!


<!-- Sent from Reviewable.io -->

2022-11-18 00:56 UTC, SanjayVas requested changes
> Reviewed 10 of 43 files at r2, 28 of 31 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/721)* status: 41 of 46 files reviewed, 12 unresolved discussions (waiting on @kungfucraig, @matthewclegg, and @renjiezh)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ContinuationTokenManager.kt` line 23 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/721#-NH6zm9U1mFJ_TDtSWOQ:-NH6zm9U1mFJ_TDtSWOR:b5em30w) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9daa21c391d47c5b7ac27b3ad70f5e54be9fc901/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ContinuationTokenManager.kt#L23)):*
Follow style guide for documentation (https://developer.android.com/kotlin/style-guide#documentation).

> Each KDoc block begins with a brief summary fragment. This fragment is very important: it is the only part of the text that appears in certain contexts such as class and method indexes.
> 
> This is a fragment–a noun phrase or verb phrase, not a complete sentence. It does not begin with "A `Foo` is a...",

Classes should have noun phrases and functions should have verb phrases. The summary fragment shouldn't start with the name of the item. It should be instead something like "Manager for continuation tokens".



_Code quote:_
```Kotlin
ContinuationTokenManager stores
```
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ContinuationTokenManager.kt` line 40 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/721#-NH708EMDQ6_5w-3eWY4:-NH708EMDQ6_5w-3eWY5:bw40sm5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9daa21c391d47c5b7ac27b3ad70f5e54be9fc901/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ContinuationTokenManager.kt#L40)):*
> ```Kotlin
>     Collections.synchronizedList(mutableListOf())
> 
>   // Get the latest continuation token to stream computations. Note: Also clear the
> ```

This still isn't in KDoc format following the style guide. Documentation for any class, field, or function should use KDoc format rather than regular comments.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ContinuationTokenManager.kt` line 47 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/721#-NH7D_NJDtUSKtLah2c7:-NH7D_NJDtUSKtLah2c8:b-xmjdqg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9daa21c391d47c5b7ac27b3ad70f5e54be9fc901/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ContinuationTokenManager.kt#L47)):*
> ```Kotlin
>     return continuationTokenClient
>       .withWaitForReady()
>       .getContinuationToken(getContinuationTokenRequest {})
> ```

You should only need to make this RPC once at Herald startup. After that, the Herald should be able to keep track of the last sequential token that it has marked as processed without needing to call the Kingdom again.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ContinuationTokenManager.kt` line 75 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/721#-NH72HQ1CHhj_i37aVax:-NH72HQ1CHhj_i37aVay:b4atfi9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9daa21c391d47c5b7ac27b3ad70f5e54be9fc901/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ContinuationTokenManager.kt#L75)):*
> ```Kotlin
>       val lastProcessedToken = continuationTokenList[lastProcessedIndex].token
>       continuationTokenClient.updateContinuationToken(
>         updateContinuationTokenRequest { token = lastProcessedToken }
> ```

Optional: This will result in `n` RPCs/writes where `n` is the number of tokens processed in sequence. Wondering if it's worth batching these instead.

Batching should be safe, as Herald processing already must be idempotent (e.g. if a Herald processes a token but then dies right before it can mark it as processed, then it will end up seeing that same token again for processing).
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt` line 158 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/721#-NH7DF9_BofoDbzR7YZC:-NH7DF9_BofoDbzR7YZD:bl7hrgm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9daa21c391d47c5b7ac27b3ad70f5e54be9fc901/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt#L158)):*
> ```Kotlin
>             processSystemComputationAndSuppressException(response.computation, MAX_ATTEMPTS)
>             continuationTokenManager.updateContinuationToken(index)
>             semaphore.release()
> ```

This should be in a `finally` so the semaphore is always released even if processing throws an exception.



_Code quote:_
```Kotlin
semaphore.release()
```
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/herald/BUILD.bazel` line 13 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/721#-NH2Iubt0JGyMDfkspY4:-NH7DtG46v14PboDGhcB:b5e7asq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b834b603705944ef1a3740ea9ae464c2a0febdd6/src/main/kotlin/org/wfanet/measurement/duchy/deploy/common/daemon/herald/BUILD.bazel#L13)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

Done.
Thanks for the catch. Do we have any way to force this requirement among building? It is hard to find out whether containing any indirect dependencies.
</blockquote></details>

Unfortunately no. That's precisely what strict deps enforcement in rules_kotlin would do.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/deploy/gcloud/spanner/continuationtoken/SpannerContinuationTokensService.kt` line 33 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/721#-NH6wxVg5wkuQyYcmxxL:-NH6wxVg5wkuQyYcmxxM:b9l4nht) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9daa21c391d47c5b7ac27b3ad70f5e54be9fc901/src/main/kotlin/org/wfanet/measurement/duchy/deploy/gcloud/spanner/continuationtoken/SpannerContinuationTokensService.kt#L33)):*
> ```Kotlin
>     request: GetContinuationTokenRequest
>   ): GetContinuationTokenResponse {
>     val continuationToken =
> ```

nit: can be slightly more efficient in terms of object allocation by using default instance here too. This is because the default instance has all fields set to their defaults, which for `string` fields is empty string.

e.g.

```kotlin
val result: ContinuationTokenReaderResult? = ContinuationTokenReader().execute(client).singleOrNull()
if (result == null) {
  return GetContinuationTokenResponse.getDefaultInstance()
}

return getContinuationTokenResponse { token = result.continuationToken }
```
___
*[`src/main/proto/wfa/measurement/internal/duchy/continuation_tokens_service.proto` line 29 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/721#-NH6wIZD33y1fapBbvrN:-NH6wIZD33y1fapBbvrO:b-3rswli) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9daa21c391d47c5b7ac27b3ad70f5e54be9fc901/src/main/proto/wfa/measurement/internal/duchy/continuation_tokens_service.proto#L29)):*
> ```protobuf
> 
>   // Update the latest continuation token.
>   rpc updateContinuationToken(UpdateContinuationTokenRequest)
> ```

nit: maybe `set` instead of `update`?

Not a big deal, but seems clearer to me.



_Code quote:_
```protobuf
update
```
___
*[`src/test/kotlin/org/wfanet/measurement/duchy/deploy/gcloud/spanner/continuationtoken/SpannerContinuationTokensServiceTest.kt` line 31 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/721#-NH6yViT6em0rwAZZ3Sw:-NH [...]

2022-11-18 14:52 UTC, kungfucraig commented
I removed myself from the reviewers list. I don't think I'll add much value over Sanjay's review.

2022-11-19 01:14 UTC, renjiezh reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/721)* status: 32 of 48 files reviewed, 8 unresolved discussions (waiting on @matthewclegg and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ContinuationTokenManager.kt` line 23 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/721#-NH6zm9U1mFJ_TDtSWOQ:-NHBBvr3-5PqPk1qVkab:bphzi65) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9daa21c391d47c5b7ac27b3ad70f5e54be9fc901/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ContinuationTokenManager.kt#L23)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Follow style guide for documentation (https://developer.android.com/kotlin/style-guide#documentation).

> Each KDoc block begins with a brief summary fragment. This fragment is very important: it is the only part of the text that appears in certain contexts such as class and method indexes.
> 
> This is a fragment–a noun phrase or verb phrase, not a complete sentence. It does not begin with "A `Foo` is a...",

Classes should have noun phrases and functions should have verb phrases. The summary fragment shouldn't start with the name of the item. It should be instead something like "Manager for continuation tokens".
</blockquote></details>

Done.
Thanks. I think I finally understood the KDoc for classes and functions now.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ContinuationTokenManager.kt` line 40 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/721#-NH708EMDQ6_5w-3eWY4:-NHBC30A1ytglyOBNFvx:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9daa21c391d47c5b7ac27b3ad70f5e54be9fc901/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ContinuationTokenManager.kt#L40)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This still isn't in KDoc format following the style guide. Documentation for any class, field, or function should use KDoc format rather than regular comments.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ContinuationTokenManager.kt` line 47 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/721#-NH7D_NJDtUSKtLah2c7:-NHBLPne0p5SGkcAW4Tl:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9daa21c391d47c5b7ac27b3ad70f5e54be9fc901/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ContinuationTokenManager.kt#L47)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

You should only need to make this RPC once at Herald startup. After that, the Herald should be able to keep track of the last sequential token that it has marked as processed without needing to call the Kingdom again.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ContinuationTokenManager.kt` line 75 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/721#-NH72HQ1CHhj_i37aVax:-NHBD_7d0tID3lQY_LNA:bxlor6m) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9daa21c391d47c5b7ac27b3ad70f5e54be9fc901/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ContinuationTokenManager.kt#L75)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Optional: This will result in `n` RPCs/writes where `n` is the number of tokens processed in sequence. Wondering if it's worth batching these instead.

Batching should be safe, as Herald processing already must be idempotent (e.g. if a Herald processes a token but then dies right before it can mark it as processed, then it will end up seeing that same token again for processing).
</blockquote></details>

This is what I am also concerned about. Thanks for bringing it up.
 To make the batch implementation simple, the herald only updates the token when all Computations in that stream finished. Does it sound good to you? We can afford to receive some of the processed Computations when restart as long as not all Computations processed since epoch . 
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt` line 158 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/721#-NH7DF9_BofoDbzR7YZC:-NHBf93q4B85WgROy7Sy:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9daa21c391d47c5b7ac27b3ad70f5e54be9fc901/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt#L158)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This should be in a `finally` so the semaphore is always released even if processing throws an exception.
</blockquote></details>

Done.
___
*[`src/test/kotlin/org/wfanet/measurement/duchy/deploy/gcloud/spanner/continuationtoken/SpannerContinuationTokensServiceTest.kt` line 31 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/721#-NH6yViT6em0rwAZZ3Sw:-NHCOfr23pv-iMZJTh-X:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9daa21c391d47c5b7ac27b3ad70f5e54be9fc901/src/test/kotlin/org/wfanet/measurement/duchy/deploy/gcloud/spanner/continuationtoken/SpannerContinuationTokensServiceTest.kt#L31)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The pattern we'd want to follow is to have an abstract version of the test that exercises the service API only, Subclasses will then initialize the concrete version of the service. This way, you can use the same base test for all implementations (including your in-memory one) which ensures they all behave the same way.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/deploy/gcloud/spanner/continuationtoken/UpdateContinuationToken.kt` line 24 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/721#-NH6vST-52CBr-uDGbRW:-NHBWVL50hiAU_EU3am6:b-qj8bd5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9daa21c391d47c5b7ac27b3ad70f5e54be9fc901/src/main/kotlin/org/wfanet/measurement/duchy/deploy/gcloud/spanner/continuationtoken/UpdateContinuationToken.kt#L24)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: use DSL builder. e.g.

```kotlin
val mutation = insertOrUpdateMutation("HeraldContinuationTokens") {
  set("Presence").to(true)
  // ...
}
```
</blockquote></details>

Done.
Good to know that
___
*[`src/main/resources/duchy/spanner/create-herald-continuation-tokens-schema.sql` line 20 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/721#-NH2Cw0iAofCuRs8Jh_4:-NHBb3eY-_01UdcOJNDS:b-ucfkn4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b834b603705944ef1a3740ea9ae464c2a0febdd6/src/main/resources/duchy/spanner/create-herald-continuation-tokens-schema.sql#L20)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

It's an ID for the changeset. Easiest is to use incrementing values. The one in the previous changeset is 1, so it makes sense for this one to be 2. Hence

```sql
-- changeset renjiez:2 dbms:cloudspanner
```

(I accidentally put a colon instead of a space in my previous example)

See https://docs.liquibase.com/concepts/changelogs/sql-format.html
</blockquote></details>

Thanks.
___
*[`src/main/resources/duchy/spanner/create-herald-continuation-tokens-table.sql` line 39 at r4](https://reviewable. [...]

2022-11-19 01:55 UTC, SanjayVas requested changes
> Reviewed 4 of 14 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/721)* status: 36 of 48 files reviewed, 8 unresolved discussions (waiting on @matthewclegg and @renjiezh)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ContinuationTokenManager.kt` line 75 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/721#-NH72HQ1CHhj_i37aVax:-NHCUZ4O8sNedTTHHfcE:bqu7wnb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9daa21c391d47c5b7ac27b3ad70f5e54be9fc901/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ContinuationTokenManager.kt#L75)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

This is what I am also concerned about. Thanks for bringing it up.
 To make the batch implementation simple, the herald only updates the token when all Computations in that stream finished. Does it sound good to you? We can afford to receive some of the processed Computations when restart as long as not all Computations processed since epoch . 
</blockquote></details>

Seems fine as long as we're okay with the fact that a single stream might last up to 10 minutes (see the streaming timeout in org.wfanet.measurement.kingdom.service.system.v1alpha.ComputationsService). That means that we could get up to 10 minutes worth of tokens to re-process on restart.

An alternative approach would be to throttle the calls, e.g. to make sure the actual RPC doesn't happen unless X time has passed since the last call. I'm actually starting to wonder if this is just premature optimization and we should see how much of an issue this is in practice, so maybe just add a TODO here to consider throttling the calls.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ContinuationTokenManager.kt` line 54 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/721#-NHCYCjL1Fm9FwhFcdmH:-NHCYCjL1Fm9FwhFcdmI:brfxwqk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/88747d94f32cc7d2ee98cab02466b165db72e70c/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ContinuationTokenManager.kt#L54)):*
> ```Kotlin
>   }
> 
>   /** Add an UNPROCESSED continuation token entry into the list. */
> ```

Document what the return value is, though note it's a little odd that this class has a leaky abstraction: it encapsulates the list, but then lets the caller know about the list and its indices.

Maybe it was better to follow the alternative path of using a LinkedHashMap so that the caller can just use the token itself to mark that it's processed.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ContinuationTokenManager.kt` line 56 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/721#-NHCTGYS80PXH_CDu4om:-NHCTGYS80PXH_CDu4on:b-1fvpqr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/88747d94f32cc7d2ee98cab02466b165db72e70c/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ContinuationTokenManager.kt#L56)):*
> ```Kotlin
>   /** Add an UNPROCESSED continuation token entry into the list. */
>   fun addContinuationToken(continuationToken: String): Int {
>     latestContinuationToken = continuationToken
> ```

Isn't this var intended to track the latest *processed* continuation token?

Does it matter if this is called with out-of-order tokens (e.g. with a later token before an earlier one)? If so, that needs to be either checked for or documented.

Finally, does access to `latestContinuationToken` need to be thread-safe?
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ContinuationTokenManager.kt` line 63 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/721#-NHCZ0X92SYkBY-OAA61:-NHCZ0X92SYkBY-OAA62:bqct86z) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/88747d94f32cc7d2ee98cab02466b165db72e70c/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ContinuationTokenManager.kt#L63)):*
> ```Kotlin
> 
>   /** Set the latest continuation token when a computation task finished by the herald. */
>   suspend fun setContinuationToken(index: Int) {
> ```

nit: method naming and docs are unclear

Perhaps include state info to make it more obvious what each method is doing. e.g. `addPendingToken`, `getLatestProcessedToken`, `markTokenProcessed`.

You probably also need to separate the logic of marking the token as processed locally from setting the latest processed token in the DB, assuming that you want the caller to determine when to do the latter for batching.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt` line 158 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/721#-NH7DF9_BofoDbzR7YZC:-NHCVRU09kA1n4wcS3e4:b-n0k7pq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9daa21c391d47c5b7ac27b3ad70f5e54be9fc901/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt#L158)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

Done.
</blockquote></details>

The `try` needs to encompass everything between the acquisition and the release to be safe. I get that the other call suppresses most exceptions, but it is weird to leave it out. It also can't suppress them all (see other comment re: coroutine cancellation).
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt` line 176 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/721#-NHCWOi72p8aO3BDsGvM:-NHCWOi72p8aO3BDsGvN:bzbm7pw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/88747d94f32cc7d2ee98cab02466b165db72e70c/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt#L176)):*
Coroutine cancellation should not be suppressed. That's why the catch block was added here. Note the comment: 
> `// Ensure that coroutine cancellation bubbles up immediately.`

Coroutine cancellation is the mechanism by which the Herald gets stopped. See `InProcessDuchy.stopHerald`.



_Code quote:_
```Kotlin
        return
```


<!-- Sent from Reviewable.io -->

2022-11-20 02:47 UTC, renjiezh reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/721)* status: 34 of 48 files reviewed, 7 unresolved discussions (waiting on @matthewclegg and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ContinuationTokenManager.kt` line 54 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/721#-NHCYCjL1Fm9FwhFcdmH:-NHHcA_F-Kh_jdNkfa9A:b-mpe9we) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/88747d94f32cc7d2ee98cab02466b165db72e70c/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ContinuationTokenManager.kt#L54)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Document what the return value is, though note it's a little odd that this class has a leaky abstraction: it encapsulates the list, but then lets the caller know about the list and its indices.

Maybe it was better to follow the alternative path of using a LinkedHashMap so that the caller can just use the token itself to mark that it's processed.
</blockquote></details>

Done.
Changed to use LinkedHashMap.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ContinuationTokenManager.kt` line 56 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/721#-NHCTGYS80PXH_CDu4om:-NHHcEFj9r7B7ofg3DHd:b-9ldwal) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/88747d94f32cc7d2ee98cab02466b165db72e70c/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ContinuationTokenManager.kt#L56)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Isn't this var intended to track the latest *processed* continuation token?

Does it matter if this is called with out-of-order tokens (e.g. with a later token before an earlier one)? If so, that needs to be either checked for or documented.

Finally, does access to `latestContinuationToken` need to be thread-safe?
</blockquote></details>

As LinkedHashMap is not thread-safe, I added a lock to guard both the map and the `latestContinuationToken`. 
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ContinuationTokenManager.kt` line 63 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/721#-NHCZ0X92SYkBY-OAA61:-NHHcv9fB75ip44wCxMI:b8te9by) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/88747d94f32cc7d2ee98cab02466b165db72e70c/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ContinuationTokenManager.kt#L63)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: method naming and docs are unclear

Perhaps include state info to make it more obvious what each method is doing. e.g. `addPendingToken`, `getLatestProcessedToken`, `markTokenProcessed`.

You probably also need to separate the logic of marking the token as processed locally from setting the latest processed token in the DB, assuming that you want the caller to determine when to do the latter for batching.
</blockquote></details>

Renamed. 
However, I added a lock to guard updating tokens and iterating the collection. In order to reduce the occupation time of the lock, it is not easy to separate the logic for now. Do you see any way?
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt` line 176 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/721#-NHCWOi72p8aO3BDsGvM:-NHHvQvVEgBa7i-ShDcZ:bgyrsom) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/88747d94f32cc7d2ee98cab02466b165db72e70c/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt#L176)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Coroutine cancellation should not be suppressed. That's why the catch block was added here. Note the comment: 
> `// Ensure that coroutine cancellation bubbles up immediately.`

Coroutine cancellation is the mechanism by which the Herald gets stopped. See `InProcessDuchy.stopHerald`.
</blockquote></details>

I run the integration test, and saw the herald stopped as expected.


<!-- Sent from Reviewable.io -->

2022-11-21 19:58 UTC, SanjayVas requested changes
> Reviewed 2 of 3 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/721)* status: 36 of 48 files reviewed, 10 unresolved discussions (waiting on @matthewclegg and @renjiezh)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ContinuationTokenManager.kt` line 63 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/721#-NHCZ0X92SYkBY-OAA61:-NHQfa8qAl66ZcLIe1NA:b-v7n519) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/88747d94f32cc7d2ee98cab02466b165db72e70c/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ContinuationTokenManager.kt#L63)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

Renamed. 
However, I added a lock to guard updating tokens and iterating the collection. In order to reduce the occupation time of the lock, it is not easy to separate the logic for now. Do you see any way?
</blockquote></details>

The logic separation is only needed if you want the caller to control when the RPC happens. Since that was dropped and the future implementation might just be a throttle, it isn't necessary to separate.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ContinuationTokenManager.kt` line 32 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/721#-NHQeCreBU2XdgBuOHWk:-NHQeCreBU2XdgBuOHWl:b-ubkbyi) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0b4e9c95a8ebf8140bd22e597998e0ade36e615e/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ContinuationTokenManager.kt#L32)):*
> ```Kotlin
>   }
> 
>   // Lock to synchronize continuationTokens and latestContinuationToken
> ```

nit: KDoc, since this is a property rather than a local variable
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ContinuationTokenManager.kt` line 33 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/721#-NHQhsWpDfY02fIgFgdW:-NHQhsWpDfY02fIgFgdX:b96wo5d) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0b4e9c95a8ebf8140bd22e597998e0ade36e615e/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ContinuationTokenManager.kt#L33)):*
> ```Kotlin
> 
>   // Lock to synchronize continuationTokens and latestContinuationToken
>   private val lock = ReentrantLock()
> ```

I don't believe this code is using any of `ReentrantLock`'s features, so you can just use `synchronized` instead with the object itself as the lock. i.e. `synchronized(this)`



_Code quote:_
```Kotlin
ReentrantLock
```
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ContinuationTokenManager.kt` line 38 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/721#-NHQiLHf24iZo2XttGJ8:-NHQiLHf24iZo2XttGJ9:bi0mwg5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0b4e9c95a8ebf8140bd22e597998e0ade36e615e/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ContinuationTokenManager.kt#L38)):*
> ```Kotlin
>   private var latestContinuationToken = ""
> 
>   var queried = false
> ```

I don't think you need this if you change `latestContinuationToken` to be the latest *processed* continuation token, as you can just check whether it's been set.



_Code quote:_
```Kotlin
queried
```
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ContinuationTokenManager.kt` line 65 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/721#-NHQenYr28pAWemIxMar:-NHQenYr28pAWemIxMas:b-snapi3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0b4e9c95a8ebf8140bd22e597998e0ade36e615e/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ContinuationTokenManager.kt#L65)):*
> ```Kotlin
>   /**
>    * Add an UNPROCESSED continuation token entry into the list. The caller is responsible to
>    * guarantee the order of insertion.
> ```

This doesn't say anything about what that order should be.

This also still isn't following the [style guide](https://developer.android.com/kotlin/style-guide#documentation) for KDoc: the first line should be a summary fragment. Following lines should be in paragraphs. e.g.

```kotlin
/**
 * Frobbles the [Widget].
 *
 * The [Widget] must not already be frobbled.
 * 
 * @return the resulting [Frobulation]
 */
```



_Code quote:_
```Kotlin
guarantee the order of insertion.
```
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ContinuationTokenManager.kt` line 69 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/721#-NHQfz4Z5rvsQM7F7ItN:-NHQfz4Z5rvsQM7F7ItO:by2rka5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0b4e9c95a8ebf8140bd22e597998e0ade36e615e/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ContinuationTokenManager.kt#L69)):*
> ```Kotlin
>   fun addPendingToken(continuationToken: String) {
>     lock.withLock {
>       latestContinuationToken = continuationToken
> ```

Re-asking from other comment: shouldn't this be the last *processed* token, i.e. set during `markTokenProcessed` instead of here? I thought this was just supposed to be a local cache of the same token that would be written to DB.



_Code quote:_
```Kotlin
latestContinuationToken
```
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt` line 176 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/721#-NHCWOi72p8aO3BDsGvM:-NHQj7aVE6DPCvpzjbg6:b-boxshj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/88747d94f32cc7d2ee98cab02466b165db72e70c/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt#L176)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

I run the integration test, and saw the herald stopped as expected.
</blockquote></details>

How that works depends on where the Herald is in its execution loop. The fact that it's the mechanism used for `stopHerald` is just a concrete example of one of the places where it can matter. The point stands regardless: coroutine cancellation shouldn't be suppressed unless you have a very particular need to do so (e.g. running some cleanup code that must not be interrupted). In those cases, one would explicitly use [`NonCancellable`](https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/-non-cancellable/) (note the warnings around its use).
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt` line 155 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/721#-NHQkqpdE0XaDCC4BCaT:-NHQkqpdE0XaDCC4BCaU:bpi1ygb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0b4e9c95a8ebf8140bd22e597998e0ade36e615e/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt#L155)):*
> ```Kotlin
>               continuationTokenManager.markTokenProcessed(response.continuationToken)
>             } catch (e: Exception) {
>               logger.log(Level.SEVERE, "Failed to set continuation token. $e")
> ```

Handle this at a lower level. If you need to bubble it up to be handled here, use a more specific exception type to avoid unintentionally catching other exceptions.



_Code quote:_
```Kotlin
            } catch (e: Exception) {
              logger.log(Level.SEVERE, "Failed to set continuation token. $e")
```


<!-- Sent from Reviewable.io -->

2022-11-21 21:37 UTC, renjiezh reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/721)* status: 34 of 48 files reviewed, 10 unresolved discussions (waiting on @matthewclegg and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ContinuationTokenManager.kt` line 32 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/721#-NHQeCreBU2XdgBuOHWk:-NHR5lwz-175v9gRq96Q:b-w4v36g) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0b4e9c95a8ebf8140bd22e597998e0ade36e615e/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ContinuationTokenManager.kt#L32)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: KDoc, since this is a property rather than a local variable
</blockquote></details>

Deleted the lock.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ContinuationTokenManager.kt` line 33 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/721#-NHQhsWpDfY02fIgFgdW:-NHQqmka9kbBqpPo6JiD:b-o4alz3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0b4e9c95a8ebf8140bd22e597998e0ade36e615e/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ContinuationTokenManager.kt#L33)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I don't believe this code is using any of `ReentrantLock`'s features, so you can just use `synchronized` instead with the object itself as the lock. i.e. `synchronized(this)`
</blockquote></details>

Removed the lock and used synchronized.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ContinuationTokenManager.kt` line 38 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/721#-NHQiLHf24iZo2XttGJ8:-NHQpDAm6xYCqPt7aRob:bnma68f) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0b4e9c95a8ebf8140bd22e597998e0ade36e615e/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ContinuationTokenManager.kt#L38)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I don't think you need this if you change `latestContinuationToken` to be the latest *processed* continuation token, as you can just check whether it's been set.
</blockquote></details>

Sounds good!
Done.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ContinuationTokenManager.kt` line 65 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/721#-NHQenYr28pAWemIxMar:-NHQyXTP7if4UG2HI5hT:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0b4e9c95a8ebf8140bd22e597998e0ade36e615e/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ContinuationTokenManager.kt#L65)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This doesn't say anything about what that order should be.

This also still isn't following the [style guide](https://developer.android.com/kotlin/style-guide#documentation) for KDoc: the first line should be a summary fragment. Following lines should be in paragraphs. e.g.

```kotlin
/**
 * Frobbles the [Widget].
 *
 * The [Widget] must not already be frobbled.
 * 
 * @return the resulting [Frobulation]
 */
```
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ContinuationTokenManager.kt` line 69 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/721#-NHQfz4Z5rvsQM7F7ItN:-NHQp_Lf1FTcBSjlNg01:b-qvx4yk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0b4e9c95a8ebf8140bd22e597998e0ade36e615e/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ContinuationTokenManager.kt#L69)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Re-asking from other comment: shouldn't this be the last *processed* token, i.e. set during `markTokenProcessed` instead of here? I thought this was just supposed to be a local cache of the same token that would be written to DB.
</blockquote></details>

You are right.
Changed it back.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt` line 176 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/721#-NHCWOi72p8aO3BDsGvM:-NHR5ZIjBZV1v--9cEIK:b-5nrd9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/88747d94f32cc7d2ee98cab02466b165db72e70c/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt#L176)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

How that works depends on where the Herald is in its execution loop. The fact that it's the mechanism used for `stopHerald` is just a concrete example of one of the places where it can matter. The point stands regardless: coroutine cancellation shouldn't be suppressed unless you have a very particular need to do so (e.g. running some cleanup code that must not be interrupted). In those cases, one would explicitly use [`NonCancellable`](https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/-non-cancellable/) (note the warnings around its use).
</blockquote></details>

Regarding that `processSystemComputationAndSuppressException`was designed to throw no exception, do you have suggestion to solve this?
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt` line 155 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/721#-NHQkqpdE0XaDCC4BCaT:-NHR5Ag87hAxd203TMSZ:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0b4e9c95a8ebf8140bd22e597998e0ade36e615e/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt#L155)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Handle this at a lower level. If you need to bubble it up to be handled here, use a more specific exception type to avoid unintentionally catching other exceptions.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-11-21 23:43 UTC, SanjayVas requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/721)* status: 34 of 48 files reviewed, 12 unresolved discussions (waiting on @matthewclegg and @renjiezh)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ContinuationTokenManager.kt` line 25 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/721#-NHRYsYd33UAniOU6ifm:-NHRYsYd33UAniOU6ifn:b-dncg2d) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/014567dd7ad04eb893928517789339b62b640032/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ContinuationTokenManager.kt#L25)):*
> ```Kotlin
>   private val continuationTokenClient: ContinuationTokensCoroutineStub
> ) {
>   enum class State {
> ```

This can be private (and therefore shouldn't be mentioned in public method docs).
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ContinuationTokenManager.kt` line 35 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/721#-NHRY7wu9Ans-b0i-DK6:-NHRY7wu9Ans-b0i-DK7:bdvwtsh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/014567dd7ad04eb893928517789339b62b640032/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ContinuationTokenManager.kt#L35)):*
> ```Kotlin
>   /**
>    * Get the latest continuation token to stream computations and clear the [continuationTokens] for
>    * the incoming stream.
> ```

nit: This inner class has no knowledge of incoming streams, etc. All documentation for this class should be in terms of its public API.



_Code quote:_
```Kotlin
the incoming stream.
```
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ContinuationTokenManager.kt` line 41 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/721#-NHRYKGfEDIgz9LeC4pH:-NHRYKGfEDIgz9LeC4pI:bstyh7w) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/014567dd7ad04eb893928517789339b62b640032/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ContinuationTokenManager.kt#L41)):*
> ```Kotlin
>   suspend fun getLatestContinuationToken(): String {
>     synchronized(this) {
>       continuationTokens.clear()
> ```

Is this the right place to be doing this? Seems odd that a `get` would clear state. Shouldn't we instead be clearing all previous tokens when we are updating the last processed one?

e.g. if tokens 1-4 and 6-10 are processed and we mark 5 as processed, then we update the latest processed to 10 and delete 1-10 from our map.



_Code quote:_
```Kotlin
continuationTokens.clear()
```
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ContinuationTokenManager.kt` line 53 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/721#-NHRWT__A4wVXUPz5iQQ:-NHRWT__A4wVXUPz5iQR:b-wp3ypl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/014567dd7ad04eb893928517789339b62b640032/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ContinuationTokenManager.kt#L53)):*
> ```Kotlin
> 
>     synchronized(this) {
>       latestContinuationToken = response.token
> ```

Technically should check that `latestContinuationToken` is still not set here, as another thread could have executed the section above or called `markTokenProcessed`
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ContinuationTokenManager.kt` line 65 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/721#-NHRX-6Z1seH4HHp5yLO:-NHRX-6Z1seH4HHp5yLP:b-fahhmr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/014567dd7ad04eb893928517789339b62b640032/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ContinuationTokenManager.kt#L65)):*
> ```Kotlin
>    */
>   fun addPendingToken(continuationToken: String) {
>     synchronized(this) { continuationTokens[continuationToken] = State.PENDING }
> ```

nit: when a whole method body is synchronized on the parent object, you can just annotate the method with `@Synchronized` instead.



_Code quote:_
```Kotlin
synchronized(this)
```
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ContinuationTokenManager.kt` line 69 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/721#-NHRXLeO212U2JqZKlWy:-NHRXLeO212U2JqZKlWz:boq6ya) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/014567dd7ad04eb893928517789339b62b640032/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ContinuationTokenManager.kt#L69)):*
> ```Kotlin
> 
>   /**
>    * Mark a continuation token as [State.PROCESSED]. Update the latest continuation token to
> ```

nit: KDoc style



_Suggestion:_
```Kotlin
  /**
   * Marks [token] as processed.
   
   * This will update the token returned by [getLatestContinuationToken] when all prior tokens in sequence have been processed.
   */
```


<!-- Sent from Reviewable.io -->

2022-11-21 23:47 UTC, SanjayVas requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/721)* status: 34 of 48 files reviewed, 10 unresolved discussions (waiting on @matthewclegg and @renjiezh)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt` line 151 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/721#-NHRZyez3lpk17GcfPX_:-NHRZyf-5sh_VmckJCxi:b181gvw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/88747d94f32cc7d2ee98cab02466b165db72e70c/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt#L151)):*
> ```Kotlin
>           semaphore.acquire()
>           launch {
>             processSystemComputationAndSuppressException(response.computation, MAX_ATTEMPTS)
> ```

Why did this get moved out of the `try` block again? The semaphore must be released, as we cannot guarantee that nothing is thrown by `processSystemComputationAndSuppressException`. Even if we could, it's safer to just keep it in the try in case the method changes.



_Code quote:_
```Kotlin
           processSystemComputationAndSuppressException(response.computation, MAX_ATTEMPTS)
```
___
*[`src/main/resources/duchy/spanner/create-herald-continuation-tokens-table.sql` line 39 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/721#-NH6w_IS6jWWccewIwK2:-NHR_Zm77Dkg1Ul32oGq:bapml3v) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9daa21c391d47c5b7ac27b3ad70f5e54be9fc901/src/main/resources/duchy/spanner/create-herald-continuation-tokens-table.sql#L39)):*
>  Is it a good idea to just delete CreationTime as we don't really care about it?

Yeah


<!-- Sent from Reviewable.io -->

2022-11-22 03:33 UTC, renjiezh reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/721)* status: 33 of 48 files reviewed, 7 unresolved discussions (waiting on @matthewclegg and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ContinuationTokenManager.kt` line 41 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/721#-NHRYKGfEDIgz9LeC4pH:-NHSKkyd3xnEy7nchpuf:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/014567dd7ad04eb893928517789339b62b640032/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ContinuationTokenManager.kt#L41)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Is this the right place to be doing this? Seems odd that a `get` would clear state. Shouldn't we instead be clearing all previous tokens when we are updating the last processed one?

e.g. if tokens 1-4 and 6-10 are processed and we mark 5 as processed, then we update the latest processed to 10 and delete 1-10 from our map.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ContinuationTokenManager.kt` line 53 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/721#-NHRWT__A4wVXUPz5iQQ:-NHSKzla1ffdML54WZQO:b-lkcnoj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/014567dd7ad04eb893928517789339b62b640032/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ContinuationTokenManager.kt#L53)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Technically should check that `latestContinuationToken` is still not set here, as another thread could have executed the section above or called `markTokenProcessed`
</blockquote></details>

True.
Done.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt` line 151 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/721#-NHRZyez3lpk17GcfPX_:-NHSLwJ739nWh-xbTbFH:brmx3se) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/88747d94f32cc7d2ee98cab02466b165db72e70c/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt#L151)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Why did this get moved out of the `try` block again? The semaphore must be released, as we cannot guarantee that nothing is thrown by `processSystemComputationAndSuppressException`. Even if we could, it's safer to just keep it in the try in case the method changes.
</blockquote></details>

Sorry I didn't get this one. `processSystemComputationAndSuppressException` is still in the try block. Btw, I renamed it to allow it throw cancellation error.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt` line 176 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/721#-NHCWOi72p8aO3BDsGvM:-NHSMefu1_-dVpeX6S8F:bs7wumb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/88747d94f32cc7d2ee98cab02466b165db72e70c/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt#L176)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Short answer: Don't ever try to suppress *all* exceptions.

Long answer: I get that what you're trying to do is ensure the Herald stays running, since our restart policy means that the Herald will simply restart if the Herald dies and that's a waste.

The thing is that there are some cases where the Herald *should* just die. For example, unrecoverable errors such as OOM (which is why we catch `Exception` and not `Throwable`). Suspending functions should almost always be allowed to throw `CancellationException`, as cancellation is cooperative. There is no way to recover from cancellation here, as the parent coroutine scope that this function runs in is the same one as `continuallySyncStatuses`[^1].

[^1]: Except in tests when `syncStatuses` may be called directly
</blockquote></details>

Done.
___
*[`src/main/resources/duchy/spanner/create-herald-continuation-tokens-table.sql` line 39 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/721#-NH6w_IS6jWWccewIwK2:-NHSMs-36pV8fYeemILR:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9daa21c391d47c5b7ac27b3ad70f5e54be9fc901/src/main/resources/duchy/spanner/create-herald-continuation-tokens-table.sql#L39)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

>  Is it a good idea to just delete CreationTime as we don't really care about it?

Yeah
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-11-22 19:02 UTC, SanjayVas requested changes
> Reviewed 2 of 43 files at r2, 8 of 14 files at r5, 1 of 3 files at r7, 4 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/721)* status: all files reviewed, 4 unresolved discussions (waiting on @matthewclegg and @renjiezh)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ContinuationTokenManager.kt` line 59 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/721#-NHVfl-Y7nT5MCbOHF_B:-NHVfl-Y7nT5MCbOHF_C:brspej) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3d1ba86fcd80ecf79549309ea261d2b7a4a8aee0/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ContinuationTokenManager.kt#L59)):*
> ```Kotlin
> 
>   /**
>    * Add a continuationToken of [State.PENDING] into [continuationTokens].
> ```

nit: State is private, so shouldn't be referenced in public method documentation.



_Code quote:_
```Kotlin
[State.PENDING]
```
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ContinuationTokenManager.kt` line 83 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/721#-NHVg3W4-oh30siQwewe:-NHVg3W4-oh30siQwewf:b-78rw7p) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3d1ba86fcd80ecf79549309ea261d2b7a4a8aee0/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ContinuationTokenManager.kt#L83)):*
> ```Kotlin
> 
>       for (item in continuationTokens) {
>         if (item.value == State.PENDING) {
> ```

I don't think this logic is correct. From my example above: Suppose tokens 1-4 and 6-10 are processed, 5 and 11-15 are not. If you mark 5 as processed, then the result should be that the last processed token becomes 10 and 1-10 are cleared from the map.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt` line 151 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/721#-NHRZyez3lpk17GcfPX_:-NHVgmmr0SQ4ECNoj-yG:b-5sokh8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/88747d94f32cc7d2ee98cab02466b165db72e70c/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/Herald.kt#L151)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

Sorry I didn't get this one. `processSystemComputationAndSuppressException` is still in the try block. Btw, I renamed it to allow it throw cancellation error.
</blockquote></details>

Sorry, looked at an old diff.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/service/internal/testing/ContinuationTokensServiceTest.kt` line 46 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/721#-NHVh6Q294lscJsof0kZ:-NHVh6Q294lscJsof0k_:b-2uiwyx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3d1ba86fcd80ecf79549309ea261d2b7a4a8aee0/src/main/kotlin/org/wfanet/measurement/duchy/service/internal/testing/ContinuationTokensServiceTest.kt#L46)):*
> ```Kotlin
>       val response = service.getContinuationToken(getContinuationTokenRequest {})
> 
>       assertThat(response).isEqualTo(getContinuationTokenResponse { token = "" })
> ```

Use ProtoTruth extension for assertions on protobuf message subjects. (Just add an import for `com.google.common.truth.extensions.proto.ProtoTruth.assertThat`)



_Code quote:_
```Kotlin
assertThat
```


<!-- Sent from Reviewable.io -->

2022-11-23 18:54 UTC, renjiezh reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/721)* status: 44 of 48 files reviewed, 3 unresolved discussions (waiting on @matthewclegg and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ContinuationTokenManager.kt` line 83 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/721#-NHVg3W4-oh30siQwewe:-NH_paBAACrdhkk_-JOI:b-kpudp8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3d1ba86fcd80ecf79549309ea261d2b7a4a8aee0/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ContinuationTokenManager.kt#L83)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I don't think this logic is correct. From my example above: Suppose tokens 1-4 and 6-10 are processed, 5 and 11-15 are not. If you mark 5 as processed, then the result should be that the last processed token becomes 10 and 1-10 are cleared from the map.
</blockquote></details>

Modified the logic of clearing old processed tokens.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/service/internal/testing/ContinuationTokensServiceTest.kt` line 46 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/721#-NHVh6Q294lscJsof0kZ:-NH_duLQ22kJwWL8YtKS:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3d1ba86fcd80ecf79549309ea261d2b7a4a8aee0/src/main/kotlin/org/wfanet/measurement/duchy/service/internal/testing/ContinuationTokensServiceTest.kt#L46)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Use ProtoTruth extension for assertions on protobuf message subjects. (Just add an import for `com.google.common.truth.extensions.proto.ProtoTruth.assertThat`)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-11-23 19:51 UTC, SanjayVas requested changes
> Reviewed 4 of 4 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/721)* status: all files reviewed, 1 unresolved discussion (waiting on @matthewclegg and @renjiezh)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ContinuationTokenManager.kt` line 88 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/721#-NH_w36M9W-mHCcr6Vsx:-NH_w36M9W-mHCcr6Vsy:b-y8phuw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c534dc1a84ac16a0f51b415bcbee2d465fef4594/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ContinuationTokenManager.kt#L88)):*
> ```Kotlin
>         lastProcessedTokenInSequence = item.key
>       }
>       removableTokens.add(lastProcessedTokenInSequence)
> ```

Can't `lastProcessedTokenInSequence` still be empty here, e.g. when the first token is still pending?

I imagine a simpler implementation of removing the processed tokens would be to use `takeWhile`. e.g. something like

```kotlin
val removableTokens: List<String> = continuationTokens.values.takeWhile { (_, state) ->
  state == State.PROCESSED
}.map { it.key }
```

The returned list may be empty. The last item in the list would be the `lastProcessedTokenInSequence`.


<!-- Sent from Reviewable.io -->

2022-11-23 20:59 UTC, renjiezh reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/721)* status: 46 of 48 files reviewed, 1 unresolved discussion (waiting on @matthewclegg and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ContinuationTokenManager.kt` line 88 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/721#-NH_w36M9W-mHCcr6Vsx:-NHaHUDv51hXd7p8iu8A:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c534dc1a84ac16a0f51b415bcbee2d465fef4594/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ContinuationTokenManager.kt#L88)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Can't `lastProcessedTokenInSequence` still be empty here, e.g. when the first token is still pending?

I imagine a simpler implementation of removing the processed tokens would be to use `takeWhile`. e.g. something like

```kotlin
val removableTokens: List<String> = continuationTokens.values.takeWhile { (_, state) ->
  state == State.PROCESSED
}.map { it.key }
```

The returned list may be empty. The last item in the list would be the `lastProcessedTokenInSequence`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-11-23 22:24 UTC, SanjayVas requested changes
> Reviewed 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/721)* status: all files reviewed, 2 unresolved discussions (waiting on @matthewclegg and @renjiezh)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ContinuationTokenManager.kt` line 76 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/721#-NHa_S6qCyhXeN9B-arl:-NHa_S6qCyhXeN9B-arm:b-4ka3kx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a0cbe77e9f04cc4482bd8becd51fe1410ff722de/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ContinuationTokenManager.kt#L76)):*
> ```Kotlin
>    */
>   suspend fun markTokenProcessed(continuationToken: String) {
>     var updatedLatestContinuationToken = ""
> ```

I don't think you need this var, as it will just be equal to `latestContinuationToken` immediately after being set.



_Code quote:_
```Kotlin
updatedLatestContinuationToken
```


<!-- Sent from Reviewable.io -->

2022-11-23 22:27 UTC, renjiezh reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/721)* status: all files reviewed, 2 unresolved discussions (waiting on @matthewclegg and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ContinuationTokenManager.kt` line 76 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/721#-NHa_S6qCyhXeN9B-arl:-NHaaHro3RmqwgeSv4DD:b-1olgfo) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a0cbe77e9f04cc4482bd8becd51fe1410ff722de/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ContinuationTokenManager.kt#L76)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I don't think you need this var, as it will just be equal to `latestContinuationToken` immediately after being set.
</blockquote></details>

This is only used to call api `setContinuationToken` without peaking the `latestContinuationToken`, which is not thread-safe after exiting synchronized block. Do you have idea to avoid that or this is not concerning?


<!-- Sent from Reviewable.io -->

2022-11-28 20:28 UTC, SanjayVas requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/721)* status: all files reviewed, 1 unresolved discussion (waiting on @matthewclegg and @renjiezh)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ContinuationTokenManager.kt` line 76 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/721#-NHa_S6qCyhXeN9B-arl:-NHztiwhCoz7VsKm7rN8:b-18ynwk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a0cbe77e9f04cc4482bd8becd51fe1410ff722de/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ContinuationTokenManager.kt#L76)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

This is only used to call api `setContinuationToken` without peaking the `latestContinuationToken`, which is not thread-safe after exiting synchronized block. Do you have idea to avoid that or this is not concerning?
</blockquote></details>

Yes. Utilize the fact that the `synchronized` function returns a value in order to set a `val` rather than using `var`. You could even build the request inside the block so it's clear what it's for. e.g. 

```kotlin
val setTokenRequest = synchronized(this) {
  // ...
  setContinuationTokenRequest { token = latestContinuationToken }
}
```


<!-- Sent from Reviewable.io -->

2022-11-28 22:33 UTC, renjiezh reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/721)* status: 47 of 48 files reviewed, 1 unresolved discussion (waiting on @matthewclegg and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ContinuationTokenManager.kt` line 76 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/721#-NHa_S6qCyhXeN9B-arl:-NI-DewLEpP2N1yPEZgP:bt8vlpp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a0cbe77e9f04cc4482bd8becd51fe1410ff722de/src/main/kotlin/org/wfanet/measurement/duchy/daemon/herald/ContinuationTokenManager.kt#L76)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Yes. Utilize the fact that the `synchronized` function returns a value in order to set a `val` rather than using `var`. You could even build the request inside the block so it's clear what it's for. e.g. 

```kotlin
val setTokenRequest = synchronized(this) {
  // ...
  setContinuationTokenRequest { token = latestContinuationToken }
}
```
</blockquote></details>

Done.
Brilliant!


<!-- Sent from Reviewable.io -->

2022-11-28 23:48 UTC, SanjayVas approved these changes
> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/721)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @matthewclegg)



<!-- Sent from Reviewable.io -->

2022-11-29 22:40 UTC, stevenwarejones reviewed
> Reviewed 1 of 43 files at r2, 1 of 31 files at r4, 2 of 14 files at r5, 1 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/721)* status: all files reviewed, 1 unresolved discussion (waiting on @duliomatos1, @mariolamassaavedra, @matthewclegg, and @renjiezh)

___
*[`src/test/kotlin/org/wfanet/measurement/duchy/daemon/herald/ContinuationTokenManagerTest.kt` line 77 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/721#-NI4XugfCKhtq-TSrWs8:-NI4XugfCKhtq-TSrWs9:b9ieqgk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/98e6bc79e0bf0dc16c0cdcb5756a1f77df45fdb9/src/test/kotlin/org/wfanet/measurement/duchy/daemon/herald/ContinuationTokenManagerTest.kt#L77)):*
> ```Kotlin
> 
>   @Test
>   fun `getLatestContinuationToken returns token when the last token is marked as parocessed`() =
> ```

nit: processed


<!-- Sent from Reviewable.io -->

2022-12-01 13:59 UTC, duliomatos1 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/721#-:-NICz-AuDl4TRjJR5J7V:bnfp4nl)* status: 47 of 48 files reviewed, all discussions resolved (waiting on @mariolamassaavedra, @matthewclegg, @SanjayVas, and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2022-12-01 17:08 UTC, stevenwarejones reviewed
not planning to review unless you need me to

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/721#-:-NIDeNhp1UgmC4-nFD5r:bfhtsl0)* status: 47 of 48 files reviewed, all discussions resolved (waiting on @mariolamassaavedra, @matthewclegg, and @SanjayVas)



<!-- Sent from Reviewable.io -->

2022-12-02 17:47 UTC, renjiezh reviewed
> Reviewed 10 of 43 files at r2, 10 of 31 files at r4, 7 of 14 files at r5, 3 of 4 files at r8, 2 of 4 files at r9, 1 of 1 files at r11, 1 of 1 files at r12, 6 of 6 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/721)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @mariolamassaavedra and @matthewclegg)



<!-- Sent from Reviewable.io -->

2022-12-02 17:48 UTC, merged