Allow dev Mill and Herald to run on GKE Spot VMs.
world-federation-of-advertisers/cross-media-measurement pull request #725
Opened 2022-10-07 22:01 UTC by SanjayVas

This configures those Deployments to tolerate node pools with a `NoSchedule` taint for `cloud.google.com/gke-spot`.

See http://cloud/kubernetes-engine/docs/how-to/spot-vms#use_taints_and_tolerations_for

2022-10-07 22:10 UTC, SanjayVas reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/725)* status: 0 of 6 files reviewed, all discussions resolved (waiting on @matthewclegg)

___
*[`src/main/k8s/dev/duchy_gke.cue` line 30 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/725#-NDoUlAeDinlHIQtyITL:-NDoUlAeDinlHIQtyITM:b-9f6bji) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c5d45a7d048e74351a2956d37e6f70002040c2f2/src/main/k8s/dev/duchy_gke.cue#L30)):*
I had asked @wangyaopw about where the original 4 GiB value came from. His response:

> During the load test, we ran some computations with 20 giant sketches and lots of noises. 4GB is fine to support those cases. For a normal computation, possibly 2 GB is fine.



_Code quote:_
```CUE
"2Gi"
```


<!-- Sent from Reviewable.io -->

2022-10-11 20:08 UTC, matthewclegg requested changes
> Reviewed 4 of 6 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/725)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`docs/gke/duchy-deployment.md` line 152 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/725#-NE7YB1xEcMU9jvGkjEO:-NE7YB1yEYKSxbwrtxiF:b-wboyvg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9e35d5f75c94ab65020ea065b361de41ac2f1b8c/docs/gke/duchy-deployment.md#L152)):*
> ```Markdown
>   --service-account="gke-cluster@halo-worker1-demo.iam.gserviceaccount.com" \
>   --database-encryption-key=projects/halo-worker1-demo/locations/us-central1/keyRings/test-key-ring/cryptoKeys/k8s-secret \
>   --num-nodes=2 --enable-autoscaling --min-nodes=2 --max-nodes=4 \
> ```

This seems like a really useful PR.  Thank you for creating it.

I am guessing that your intention is that the user would create a second node pool of compute instances.  If that is correct, I would suggest that you modify this doc as follows:

(1) Add a new section explaining the benefits of using node pools, with links to the relevant GKE docs.
(2) Add an example `clusters create` command, which I assume would include the `--spot` parameter.
(3) Add an example `gcloud container node-pools create` command.

Also, I wanted to raise another issue for your consideration.  Our job as members of the Halo team is to provide a high quality software product.  I think we are trying to draw the line at deployment.  Other teams will be responsible for deployments of Halo.  Given this, beyond giving a basic working deployment configuration, should we be continuing to embellish our deployment scripts?


<!-- Sent from Reviewable.io -->

2022-10-11 22:35 UTC, SanjayVas reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/725)* status: all files reviewed, 1 unresolved discussion (waiting on @matthewclegg)

___
*[`docs/gke/duchy-deployment.md` line 152 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/725#-NE7YB1xEcMU9jvGkjEO:-NE88Xq5Axak8egrvQCP:b-1nhobp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9e35d5f75c94ab65020ea065b361de41ac2f1b8c/docs/gke/duchy-deployment.md#L152)):*
<details><summary><i>Previously, matthewclegg (Matthew Clegg) wrote…</i></summary><blockquote>

This seems like a really useful PR.  Thank you for creating it.

I am guessing that your intention is that the user would create a second node pool of compute instances.  If that is correct, I would suggest that you modify this doc as follows:

(1) Add a new section explaining the benefits of using node pools, with links to the relevant GKE docs.
(2) Add an example `clusters create` command, which I assume would include the `--spot` parameter.
(3) Add an example `gcloud container node-pools create` command.

Also, I wanted to raise another issue for your consideration.  Our job as members of the Halo team is to provide a high quality software product.  I think we are trying to draw the line at deployment.  Other teams will be responsible for deployments of Halo.  Given this, beyond giving a basic working deployment configuration, should we be continuing to embellish our deployment scripts?

</blockquote></details>

I had only considered this PR as covering the minimum needed to allow scheduling on Spot VMs, since that needs to be done in the K8s object configuration. It's entirely optional to use, and only comes into effect if one decided to use Spot VMs with a node taint.

As for the deployment guide itself, we're just giving the bare minimum to get things working and advising operators to adjust based on their own needs.

The context for this PR is that we're using spot VMS in the QA environment to keep costs down there, but I didn't want to complicate the deployment guide with explaining how and why to set that up since it's not strictly necessary.


<!-- Sent from Reviewable.io -->

2022-10-13 14:52 UTC, matthewclegg requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/725)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`docs/gke/duchy-deployment.md` line 152 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/725#-NE7YB1xEcMU9jvGkjEO:-NE8Js5330YLhwONXWbb:b13uqwt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9e35d5f75c94ab65020ea065b361de41ac2f1b8c/docs/gke/duchy-deployment.md#L152)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I had only considered this PR as covering the minimum needed to allow scheduling on Spot VMs, since that needs to be done in the K8s object configuration. It's entirely optional to use, and only comes into effect if one decided to use Spot VMs with a node taint.

As for the deployment guide itself, we're just giving the bare minimum to get things working and advising operators to adjust based on their own needs.

The context for this PR is that we're using spot VMS in the QA environment to keep costs down there, but I didn't want to complicate the deployment guide with explaining how and why to set that up since it's not strictly necessary.
</blockquote></details>


If these modifications are just intended for personal use, we should not be submitting changes to the public codebase.  On the other hand, if these changes are intended to be useful to others, then they should be properly documented.  Please update the doc.


<!-- Sent from Reviewable.io -->

2022-10-13 17:37 UTC, SanjayVas reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/725)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @matthewclegg)

___
*[`docs/gke/duchy-deployment.md` line 152 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/725#-NE7YB1xEcMU9jvGkjEO:-NEHLqPz2HESIX8Zr1_m:b1qiszh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9e35d5f75c94ab65020ea065b361de41ac2f1b8c/docs/gke/duchy-deployment.md#L152)):*
<details><summary><i>Previously, matthewclegg (Matthew Clegg) wrote…</i></summary><blockquote>

If these modifications are just intended for personal use, we should not be submitting changes to the public codebase.  On the other hand, if these changes are intended to be useful to others, then they should be properly documented.  Please update the doc.
</blockquote></details>

Done. Added a note mentioning what our default config supports, linking to the relevant GKE docs.

This is not for personal use. It's enabling advanced users to do something in their cluster setup. This doc intentionally does not go into detail on such advanced use cases, and instead covers the bare minimum to get the system working.


<!-- Sent from Reviewable.io -->

2022-10-14 17:04 UTC, matthewclegg requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/725)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`docs/gke/duchy-deployment.md` line 152 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/725#-NE7YB1xEcMU9jvGkjEO:-NEMRlryCkjJk18QO2ji:b-edawbf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9e35d5f75c94ab65020ea065b361de41ac2f1b8c/docs/gke/duchy-deployment.md#L152)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Done. Added a note mentioning what our default config supports, linking to the relevant GKE docs.

This is not for personal use. It's enabling advanced users to do something in their cluster setup. This doc intentionally does not go into detail on such advanced use cases, and instead covers the bare minimum to get the system working.
</blockquote></details>

Thank you for adding this.  I think that is helpful.  But I still feel that you should give an explicit example.


<!-- Sent from Reviewable.io -->

2022-10-14 17:24 UTC, SanjayVas reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/725)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @matthewclegg)

___
*[`docs/gke/duchy-deployment.md` line 152 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/725#-NE7YB1xEcMU9jvGkjEO:-NEMUlLm4Xiy7XoNmnuj:b-6wcd3a) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9e35d5f75c94ab65020ea065b361de41ac2f1b8c/docs/gke/duchy-deployment.md#L152)):*
<details><summary><i>Previously, matthewclegg (Matthew Clegg) wrote…</i></summary><blockquote>

Thank you for adding this.  I think that is helpful.  But I still feel that you should give an explicit example.
</blockquote></details>

As stated above, leaving out an explicit example is highly intentional (and frankly not our job as Halo engineers). The goal if this document is to cover the bare minimum to get things working and not go into the details of different ways one should configure their node pools. 

The official GKE docs should cover this sufficiently. There are many ways to configure a cluster and different features that can be used, with tradeoffs for all of them. As such, I expect a proper cluster configuration to be bespoke for each operator to meet their goals w.r.t. cost, performance, availability, maintenance, etc.


<!-- Sent from Reviewable.io -->

2022-10-17 16:39 UTC, matthewclegg approved these changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/725)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`docs/gke/duchy-deployment.md` line 152 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/725#-NE7YB1xEcMU9jvGkjEO:-NEanhlsAO3nrNm1CwUu:b7ink7c) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9e35d5f75c94ab65020ea065b361de41ac2f1b8c/docs/gke/duchy-deployment.md#L152)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

As stated above, leaving out an explicit example is highly intentional (and frankly not our job as Halo engineers). The goal if this document is to cover the bare minimum to get things working and not go into the details of different ways one should configure their node pools. 

The official GKE docs should cover this sufficiently. There are many ways to configure a cluster and different features that can be used, with tradeoffs for all of them. As such, I expect a proper cluster configuration to be bespoke for each operator to meet their goals w.r.t. cost, performance, availability, maintenance, etc.
</blockquote></details>

I disagree with this approach, but not so much that I am willing to continue blocking this PR.


<!-- Sent from Reviewable.io -->

2022-10-18 16:24 UTC, SanjayVas reviewed
> Dismissed @matthewclegg from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/725)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)



<!-- Sent from Reviewable.io -->

2022-10-19 17:05 UTC, stevenwarejones approved these changes
> Reviewed 4 of 6 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/725)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

___
*[`src/main/k8s/dev/duchy_gke.cue` line 30 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/725#-NDoUlAeDinlHIQtyITL:-NElCEbT1vl_wPhoGqIT:b1bc01q) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c5d45a7d048e74351a2956d37e6f70002040c2f2/src/main/k8s/dev/duchy_gke.cue#L30)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I had asked @wangyaopw about where the original 4 GiB value came from. His response:

> During the load test, we ran some computations with 20 giant sketches and lots of noises. 4GB is fine to support those cases. For a normal computation, possibly 2 GB is fine.
</blockquote></details>

should that note from Yao make it into a doc somewhere?


<!-- Sent from Reviewable.io -->

2022-10-28 21:11 UTC, SanjayVas reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/725)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)

___
*[`src/main/k8s/dev/duchy_gke.cue` line 30 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/725#-NDoUlAeDinlHIQtyITL:-NFVQb_P3cLgRmjD1ju8:b-o06aze) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c5d45a7d048e74351a2956d37e6f70002040c2f2/src/main/k8s/dev/duchy_gke.cue#L30)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

should that note from Yao make it into a doc somewhere?
</blockquote></details>

The limits in all of these files are already from observed usage with documentation that they should be adjusted. This note was just to indicate why I changed it.


<!-- Sent from Reviewable.io -->

2022-10-28 21:12 UTC, merged