Define Certificate message type for Kingdom internal services.
world-federation-of-advertisers/cross-media-measurement pull request #78
Opened 2021-05-25 19:41 UTC by SanjayVas

This includes some fields denormalized from the X.509 certificate so they can be queried.

For issue #52.

2021-05-25 22:31 UTC, efoxepstein requested changes
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/78)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[src/main/proto/wfa/measurement/internal/kingdom/certificate.proto, line 43 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/78#-Ma_dQFc6qfMGcvib6Hs:-Ma_dQFd4CI-QYuY3M52:b-ho4f2f) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5ef5ad2927b959f1bcaec8aa0449296cf9114672/src/main/proto/wfa/measurement/internal/kingdom/certificate.proto#L43)):*
> ```protobuf
>   // RFC 5280 revocation state.
>   enum RevocationState {
>     REVOCATION_STATE_UNSPECIFIED = 0;
> ```

How are valid Certs represented? Using `REVOCATION_STATE_UNSPECIFIED`? Is it worthwhile to add a specific state for this?


<!-- Sent from Reviewable.io -->

2021-05-25 23:32 UTC, SanjayVas reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/78)* status: all files reviewed, 1 unresolved discussion (waiting on @efoxepstein)

___
*[src/main/proto/wfa/measurement/internal/kingdom/certificate.proto, line 43 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/78#-Ma_dQFc6qfMGcvib6Hs:-Ma_lu4v-mxP8tI0mLk4:bpxl4q7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5ef5ad2927b959f1bcaec8aa0449296cf9114672/src/main/proto/wfa/measurement/internal/kingdom/certificate.proto#L43)):*
<details><summary><i>Previously, efoxepstein (Eli Fox-Epstein) wrote…</i></summary><blockquote>

How are valid Certs represented? Using `REVOCATION_STATE_UNSPECIFIED`? Is it worthwhile to add a specific state for this?
</blockquote></details>

A valid cert is one that has both no revocation state specified **and** the current time is within its validity period.

If this enum was representing the overall certificate state, we'd indeed want to require that a state value is specified and the `_UNSPECIFIED` value would be considered an error. This is instead something that provides details about revocation from RFC 5280.


<!-- Sent from Reviewable.io -->

2021-05-26 16:09 UTC, efoxepstein approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/78)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)



<!-- Sent from Reviewable.io -->

2021-05-26 16:28 UTC, kungfucraig approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/78)* status: all files reviewed, 1 unresolved discussion (waiting on @corbantek, @oliver-amzn, @SanjayVas, and @zachcwc)

___
*[src/main/proto/wfa/measurement/internal/kingdom/certificate.proto, line 25 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/78#-MadVI5vB2YRoA3anKg_:-MadVI5vB2YRoA3anKga:bjf4fzu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5ef5ad2927b959f1bcaec8aa0449296cf9114672/src/main/proto/wfa/measurement/internal/kingdom/certificate.proto#L25)):*
> ```protobuf
> 
> message Certificate {
>   oneof parent {
> ```

You'll move to strings later?


<!-- Sent from Reviewable.io -->

2021-05-26 19:11 UTC, SanjayVas reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/78)* status: all files reviewed, 1 unresolved discussion (waiting on @corbantek, @kungfucraig, @oliver-amzn, and @zachcwc)

___
*[src/main/proto/wfa/measurement/internal/kingdom/certificate.proto, line 25 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/78#-MadVI5vB2YRoA3anKg_:-Mae3T0x5jMFaPjbDtG_:bs74jku) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5ef5ad2927b959f1bcaec8aa0449296cf9114672/src/main/proto/wfa/measurement/internal/kingdom/certificate.proto#L25)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

You'll move to strings later?
</blockquote></details>

You're thinking of the switch to resource names in the public API. This PR is for internal services where we don't need to be quite so generic.


<!-- Sent from Reviewable.io -->

2021-05-26 19:13 UTC, SanjayVas reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/78)* status: all files reviewed, 1 unresolved discussion (waiting on @corbantek, @kungfucraig, @oliver-amzn, and @zachcwc)

___
*[src/main/proto/wfa/measurement/internal/kingdom/certificate.proto, line 25 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/78#-MadVI5vB2YRoA3anKg_:-Mae4qscBsFy2ers9x4E:b-pq0uly) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5ef5ad2927b959f1bcaec8aa0449296cf9114672/src/main/proto/wfa/measurement/internal/kingdom/certificate.proto#L25)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

You're thinking of the switch to resource names in the public API. This PR is for internal services where we don't need to be quite so generic.
</blockquote></details>

For reference, the other change I mentioned is being handled in WIP PR world-federation-of-advertisers/cross-media-measurement-api#39.


<!-- Sent from Reviewable.io -->

2021-05-26 19:16 UTC, corbantek approved these changes
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/78)* status: all files reviewed, 1 unresolved discussion (waiting on @kungfucraig, @oliver-amzn, and @zachcwc)



<!-- Sent from Reviewable.io -->

2021-05-27 00:25 UTC, merged