Reporting v2alpha proto
world-federation-of-advertisers/cross-media-measurement pull request #812
Opened 2023-01-13 23:06 UTC by riemanli

2023-01-19 16:51 UTC, kungfucraig requested changes
> Reviewed 1 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812)* status: 1 of 7 files reviewed, 13 unresolved discussions (waiting on @riemanli)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto` line 41 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NM9oS9nABoGdymqS-i1:-NM9oS9nABoGdymqS-i2:b-7hmu87) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/957d63cd0848372cd7aa96e74561af6511e0b1df/src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto#L41)):*
> ```protobuf
>   message ImpressionCountParams {
>     // Maximum frequency per user that will be included in this measurement.
>     int32 maximum_frequency_per_user = 1;
> ```

We should note that this is only enforced on a per EDP basis.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto` line 44 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NM9oYJV5F-wkDPrtv1I:-NM9oYJV5F-wkDPrtv1J:b-zb9owg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/957d63cd0848372cd7aa96e74561af6511e0b1df/src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto#L44)):*
> ```protobuf
>   }
>   // Parameters that are used to generate `Watch Duration` metric.
>   message WatchDurationParams {
> ```

Similar here. These can only be enforced per EDP at the moment.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto` line 53 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NM9ohvM1RkYsa4koSNC:-NM9ohvM1RkYsa4koSND:b-wxj55y) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/957d63cd0848372cd7aa96e74561af6511e0b1df/src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto#L53)):*
> ```protobuf
> 
>   // Types of metric with parameters.
>   oneof metric_type {
> ```

nit: just "type" would be adequate here,
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto` line 70 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NM9pD5h9uHOXgXahtz0:-NM9pD5h9uHOXgXahtz1:b-2gvao5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/957d63cd0848372cd7aa96e74561af6511e0b1df/src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto#L70)):*
> ```protobuf
> // The calculation result of a metric
> message MetricResult {
>   // The metric result in scalar type. Ex: reach, impression count.
> ```

The comments above both this and HistogramResult have some grammar issues. Can you fix them?

Do you mean to say "The metric result is a scalar type."?
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto` line 99 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NM9pZDL1vcz0ut8rr9f:-NM9pZDL1vcz0ut8rr9g:bpeutiu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/957d63cd0848372cd7aa96e74561af6511e0b1df/src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto#L99)):*
> ```protobuf
> }
> 
> // Definition of a metric for a `Report` in terms of set operations.
> ```

Can you describe what a metric is?

Something like:

A Metric is a resource that will calculate a particular quantity as defined by the MetricSpec cumulatively over a time interval for the given Reporting. The Metric's value once calculated is stored as a MetricResult.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto` line 100 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NM9w4c52krU576OQ6l8:-NM9w4c52krU576OQ6l9:bx6dbrr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/957d63cd0848372cd7aa96e74561af6511e0b1df/src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto#L100)):*
> ```protobuf
> 
> // Definition of a metric for a `Report` in terms of set operations.
> message Metric {
> ```

I think Metric needs a state. Something like {EVALUATING, READY, EVALUATION_FAILED}
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto` line 111 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NM9r5HeEqGCANhU5iHp:-NM9r5Hf2gbYExINfu_g:b-4snfpt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/957d63cd0848372cd7aa96e74561af6511e0b1df/src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto#L111)):*
> ```protobuf
>   ReportingSet reporting_set = 2 [(google.api.field_behavior) = REQUIRED];
> 
>   // The time over which to calculate the metric.
> ```

Add that this is always cumulative? I know it's implied, but it's best to be explicit about these kind of things.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto` line 123 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NM9pxsV2w3pf_y-oWwy:-NM9pxsV2w3pf_y-oWwz:b-lxb5o7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/957d63cd0848372cd7aa96e74561af6511e0b1df/src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto#L123)):*
> ```protobuf
>   // The user needs to provide a model that can cover all time intervals and all
>   // primitive reporting sets defined in this metric.
>   string model = 5;
> ```

See comment on Apply Model request. I think we should drop this.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric_model.proto` line 40 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NM9snBY1YIc9NoB1J-c:-NM9snBY1YIc9NoB1J-d:b-4yl55d) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/957d63cd0848372cd7aa96e74561af6511e0b1df/src/main/proto/wfa/measurement/reporting/v2alpha/metric_model.proto#L40)):*
> ```protobuf
>   // The specification of the model.
>   message ModelSpec {
>     // The metrics that this model will be estimating. Currently only support
> ```

s/support/suports
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric_model.proto` line 42 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NM9srnp2QxTr178Z4iO:-NM9srnp2QxTr178Z4iP:b-pjmsvn) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/957d63cd0848372cd7aa96e74561af6511e0b1df/src/main/proto/wfa/measurement/reporting/v2alpha/metric_model.proto#L42)):*
> ```protobuf
>     // The metrics that this model will be estimating. Currently only support
>     // reach.
>     repeated MetricSpec metric_specs = 1
> ```

We can drop the repeated until we support more metrics. Unless this would somehow impact the grpc gateway backward compatibility story... @SanjayVas do you know? If not @riemanli can you check?
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric_model.proto` line 45 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NM9tIpC3gsD4VK432L4:-NM9tIpC3gsD4VK432L5:b-umi3rw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/957d63cd0848372cd7aa96e74561af6511e0b1df/src/main/proto/wfa/measurement/reporting/v2alpha/metric_model.proto#L45)):*
> ```protobuf
>         [(google.api.field_behavior) = REQUIRED];
> 
>     // Types of time intervals that the model needs to cover.
> ```

"that the model covers"
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric_model.proto` line 77 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NM9te4wD3M6kOLiPnoo:-NM9te4wD3M6kOLiPnop:b6l6vzw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/957d63cd084 [...]

2023-01-19 19:39 UTC, SanjayVas requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812)* status: 1 of 7 files reviewed, 13 unresolved discussions (waiting on @kungfucraig, @riemanli, and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto` line 123 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NM9pxsV2w3pf_y-oWwy:-NMAXBkB1tGGWNUrjZuJ:bmg2umz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/957d63cd0848372cd7aa96e74561af6511e0b1df/src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto#L123)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

See comment on Apply Model request. I think we should drop this.
</blockquote></details>

The Metrics service *never* does model evaluation. It's what wraps Kingdom measurements.

Model is referenced from Report, not Metric.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric_model.proto` line 42 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NM9srnp2QxTr178Z4iO:-NMAWC7E2u3cnqve10a-:b-layshw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/957d63cd0848372cd7aa96e74561af6511e0b1df/src/main/proto/wfa/measurement/reporting/v2alpha/metric_model.proto#L42)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

We can drop the repeated until we support more metrics. Unless this would somehow impact the grpc gateway backward compatibility story... @SanjayVas do you know? If not @riemanli can you check?
</blockquote></details>

Making a singular field repeated is only allowed in certain situations.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric_models_service.proto` line 139 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NM9uYDM2L6EVeVzyLQ2:-NMAWSt44tAkjvyP4J8D:b-16ho22) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/957d63cd0848372cd7aa96e74561af6511e0b1df/src/main/proto/wfa/measurement/reporting/v2alpha/metric_models_service.proto#L139)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

We should specify the model and unwrap other metric fields here. The reason for this is we don't want ApplyModel to have to deal with named Metrics, and we don't want to create named Metrics each time we evaluate a model.
</blockquote></details>

More strictly, a message for a resource type should never be included in any other message.

The conceptual "Metric" used by the Model service is decomposed across model creation and application: we specify the MetricSpec at creation and the other params of Metric for application.


<!-- Sent from Reviewable.io -->

2023-01-19 19:40 UTC, SanjayVas reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812)* status: 1 of 7 files reviewed, 13 unresolved discussions (waiting on @kungfucraig and @riemanli)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric_model.proto` line 42 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NM9srnp2QxTr178Z4iO:-NMAXhOOBJ7_d_x2kdrp:bwlqpwm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/957d63cd0848372cd7aa96e74561af6511e0b1df/src/main/proto/wfa/measurement/reporting/v2alpha/metric_model.proto#L42)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Making a singular field repeated is only allowed in certain situations.
</blockquote></details>

Sorry, hit publish too soon. The main thing is that repeated field names are plural, and changing a field name is not backwards-compatible when serializing to anything that uses field names such as JSON.


<!-- Sent from Reviewable.io -->

2023-01-19 19:46 UTC, SanjayVas requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812)* status: 1 of 7 files reviewed, 13 unresolved discussions (waiting on @kungfucraig and @riemanli)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto` line 100 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NM9w4c52krU576OQ6l8:-NMAZJPf0S9GZdlMi2XJ:b284kfv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/957d63cd0848372cd7aa96e74561af6511e0b1df/src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto#L100)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

I think Metric needs a state. Something like {EVALUATING, READY, EVALUATION_FAILED}
</blockquote></details>

https://google.aip.dev/216#appendix-common-states

Maybe RUNNING, SUCCEEDED, FAILED?


<!-- Sent from Reviewable.io -->

2023-01-19 23:50 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812)* status: 0 of 7 files reviewed, 13 unresolved discussions (waiting on @kungfucraig and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto` line 41 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NM9oS9nABoGdymqS-i1:-NMA90fI5Lqmg7Qn7j30:b-w7xrgp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/957d63cd0848372cd7aa96e74561af6511e0b1df/src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto#L41)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

We should note that this is only enforced on a per EDP basis.
</blockquote></details>

I am not sure if I understand what "per EDP basis" means. Do you mean some EDPs might not accept this parameter?
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto` line 44 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NM9oYJV5F-wkDPrtv1I:-NMAg8FOBcRB2AQSrcE7:bkxxhh3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/957d63cd0848372cd7aa96e74561af6511e0b1df/src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto#L44)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Similar here. These can only be enforced per EDP at the moment.
</blockquote></details>

I wonder if `FrequencyHistogramParams` is the same.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto` line 53 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NM9ohvM1RkYsa4koSNC:-NMA7bLg9MyhTj9ZuKgj:bb6un1j) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/957d63cd0848372cd7aa96e74561af6511e0b1df/src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto#L53)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

nit: just "type" would be adequate here,
</blockquote></details>

Done
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto` line 70 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NM9pD5h9uHOXgXahtz0:-NMA8sQf91mgSG4VZqNW:bfo8imh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/957d63cd0848372cd7aa96e74561af6511e0b1df/src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto#L70)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

The comments above both this and HistogramResult have some grammar issues. Can you fix them?

Do you mean to say "The metric result is a scalar type."?
</blockquote></details>

Changed to "Scalar metric result" and "Histogram metric result".
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto` line 99 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NM9pZDL1vcz0ut8rr9f:-NMAD0b3AXm4LKEAzpGH:bb6un1j) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/957d63cd0848372cd7aa96e74561af6511e0b1df/src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto#L99)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Can you describe what a metric is?

Something like:

A Metric is a resource that will calculate a particular quantity as defined by the MetricSpec cumulatively over a time interval for the given Reporting. The Metric's value once calculated is stored as a MetricResult.
</blockquote></details>

Done
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto` line 100 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NM9w4c52krU576OQ6l8:-NMAdLl61swcyZbBzzaa:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/957d63cd0848372cd7aa96e74561af6511e0b1df/src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto#L100)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

https://google.aip.dev/216#appendix-common-states

Maybe RUNNING, SUCCEEDED, FAILED?
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto` line 111 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NM9r5HeEqGCANhU5iHp:-NMAKD2jEvhDSPkYRcrh:bb6un1j) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/957d63cd0848372cd7aa96e74561af6511e0b1df/src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto#L111)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Add that this is always cumulative? I know it's implied, but it's best to be explicit about these kind of things.
</blockquote></details>

Done
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto` line 123 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NM9pxsV2w3pf_y-oWwy:-NMAdWJBBmwEjbt2HnWS:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/957d63cd0848372cd7aa96e74561af6511e0b1df/src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto#L123)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The Metrics service *never* does model evaluation. It's what wraps Kingdom measurements.

Model is referenced from Report, not Metric.
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric_model.proto` line 40 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NM9snBY1YIc9NoB1J-c:-NMALVJpDzZpFCmlnZv9:b9ilyf1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/957d63cd0848372cd7aa96e74561af6511e0b1df/src/main/proto/wfa/measurement/reporting/v2alpha/metric_model.proto#L40)):*
> s/support/suports

Sorry could you elaborate more? Do I have a typo here?
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric_model.proto` line 45 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NM9tIpC3gsD4VK432L4:-NMANrQKE-D1FjODhuDK:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/957d63cd0848372cd7aa96e74561af6511e0b1df/src/main/proto/wfa/measurement/reporting/v2alpha/metric_model.proto#L45)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

"that the model covers"
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric_model.proto` line 77 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NM9te4wD3M6kOLiPnoo:-NMAODzi4zDewrgQS3tR:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/957d63cd0848372cd7aa96e74561af6511e0b1df/src/main/proto/wfa/measurement/reporting/v2alpha/metric_model.proto#L77)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

TRAINING_FAILED ?
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric_models_service.proto` line 139 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NM9uYDM2L6EVeVzyLQ2:-NMAg4VQ0ByIlR8mJww1:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/957d63cd0848372cd7aa96e74561af6511e0b1df/src/main/proto/wfa/measurement/reporting/v2alpha/metric_models_service.proto#L139)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) [...]

2023-01-25 23:36 UTC, kungfucraig requested changes
> Reviewed 3 of 7 files at r2, 1 of 4 files at r3, 2 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812)* status: all files reviewed, 8 unresolved discussions (waiting on @riemanli and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto` line 41 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NM9oS9nABoGdymqS-i1:-NMfDqu6AQAL0t-ICMIJ:b-28ewyl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/957d63cd0848372cd7aa96e74561af6511e0b1df/src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto#L41)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

I am not sure if I understand what "per EDP basis" means. Do you mean some EDPs might not accept this parameter?
</blockquote></details>

If you request impression counts from multiple EDPs in the same Measurement the "frequency per user" will be per EDP not across EDPs. 

In contrast if you ask for a frequency histogram across EDPs max frequency will be enforced globally.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto` line 44 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NM9oYJV5F-wkDPrtv1I:-NMfEyIQA86QebNiM4ml:bai2vda) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/957d63cd0848372cd7aa96e74561af6511e0b1df/src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto#L44)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

I wonder if `FrequencyHistogramParams` is the same.
</blockquote></details>

It's not. Since histograms are combined via MPC the frequency threshold can be enforced globally.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric_model.proto` line 40 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NM9snBY1YIc9NoB1J-c:-NMfFR0I25VfHBZaQSYV:b-abzsgk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/957d63cd0848372cd7aa96e74561af6511e0b1df/src/main/proto/wfa/measurement/reporting/v2alpha/metric_model.proto#L40)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

> s/support/suports

Sorry could you elaborate more? Do I have a typo here?
</blockquote></details>

Yes it's a type. You should use the plural of support. 

s/<string>/<string> is how you do find and replace in the vi editor. :)
https://linuxize.com/post/vim-find-replace/
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric_model.proto` line 77 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NM9te4wD3M6kOLiPnoo:-NMfFsp47NmPp3vIFJah:bi3yovr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/957d63cd0848372cd7aa96e74561af6511e0b1df/src/main/proto/wfa/measurement/reporting/v2alpha/metric_model.proto#L77)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Just use "FAILED" to be consistent with the State in Metric. Sorry for the confusion.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/report.proto` line 78 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NMBOc_gCCKi4whLv8lC:-NMfGVrGA782i84TotOP:b-i3vxtm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2b28565896ffd91fd668498f09e817f086be1006/src/main/proto/wfa/measurement/reporting/v2alpha/report.proto#L78)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

@kungfucraig @SanjayVas  One discussion in the design review is that putting the `model` indication in `ReportingMetricSpec` causes limitation of getting different metrics for the same reporting set because only reach model is supported now. Ex: say we want to get average impression = impression count / reach using the model. Since only reach model is supported, the impression count should be computed using kingdom measurements. However, because `ReportingMetricCalculation` is a map and the `model` field is in `ReportingMetricSpec`, we need to request two reports to get impression count metric and estimated reach separately for the same reporting set.
As a result, I put `model` one level lower, so inside `ReportingMetricSpec`, we can have impression count without a model and reach with a model.

Please let me know what you think about the change.
</blockquote></details>

We could keep the old structure and say, if you specify a model it will be used for all metrics unless the model doesn't support those metrics in which case the Kingdom will be queried. Having all relevant metrics for a reporting set in one MetricCalculationSpec will make it much easier to deal with derived metrics (e.g. avg frequency).

Or we do what you have here.  :)


<!-- Sent from Reviewable.io -->

2023-01-25 23:58 UTC, kungfucraig requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812)* status: all files reviewed, 9 unresolved discussions (waiting on @riemanli and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/report.proto` line 95 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NMfL-6uE1lUq8DZWcNG:-NMfL-6uE1lUq8DZWcNH:b-gjb599) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5896804bc2fcede578fa562aff52f10b900f729f/src/main/proto/wfa/measurement/reporting/v2alpha/report.proto#L95)):*
> ```protobuf
>     message ReportingMetricEntry {
>       // Key of the map entry.
>       ReportingSet key = 1 [(google.api.field_behavior) = REQUIRED];
> ```

@SanjayVas @riemanli 

I think I'm seeing an issue with reporting set. If you want to create a report template that includes some slicing criteria you'll need to point to a reporting set, but because you can only specify a single reporting set in a report metric calculation the reporting set being pointed to would also have to specify the event groups.

So what if we made the key here  a pair of reporting sets?

Then the first reporting set is basically a set of filters and set operations where the leaf nodes are still composite reporting sets. Think "multi-level set expression with no event groups". The second reporting set is the set of event groups to apply the first thing in the pair to such that the second element is a virtual child of every leaf node in the parent.

I admit this is very similar to the original design, but with multiple levels of composition/filtering.


<!-- Sent from Reviewable.io -->

2023-01-26 00:08 UTC, SanjayVas reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812)* status: all files reviewed, 9 unresolved discussions (waiting on @kungfucraig and @riemanli)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/report.proto` line 78 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NMBOc_gCCKi4whLv8lC:-NMfORoD95T9QKUhFwjU:bey8lyf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2b28565896ffd91fd668498f09e817f086be1006/src/main/proto/wfa/measurement/reporting/v2alpha/report.proto#L78)):*
>  if you specify a model it will be used for all metrics unless the model doesn't support those metrics in which case the Kingdom will be queried.

Key principles should include predictability and explicitness. If you specify the model, it will be used and the Kingdom won't be called. If you don't, then Kingdom will be called. If you specify a model and it's incompatible, an error is returned.


<!-- Sent from Reviewable.io -->

2023-01-26 00:32 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812)* status: all files reviewed, 9 unresolved discussions (waiting on @kungfucraig and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto` line 41 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NM9oS9nABoGdymqS-i1:-NMfMGKO2G40Yk_nUUeW:b-a7jufr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/957d63cd0848372cd7aa96e74561af6511e0b1df/src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto#L41)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

If you request impression counts from multiple EDPs in the same Measurement the "frequency per user" will be per EDP not across EDPs. 

In contrast if you ask for a frequency histogram across EDPs max frequency will be enforced globally.
</blockquote></details>

I see. Thanks for the explanation.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto` line 44 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NM9oYJV5F-wkDPrtv1I:-NMfStMwEThmUVbBZgfs:bof87bp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/957d63cd0848372cd7aa96e74561af6511e0b1df/src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto#L44)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

It's not. Since histograms are combined via MPC the frequency threshold can be enforced globally.
</blockquote></details>

Got it. 
Another question about `maximum_frequency_per_user` in WatchDuration. Do you what it's for and how we use this parameter in the MPC?
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric_model.proto` line 40 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NM9snBY1YIc9NoB1J-c:-NMfLdJtCT_lZhOFm8Rh:b-xjpvj9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/957d63cd0848372cd7aa96e74561af6511e0b1df/src/main/proto/wfa/measurement/reporting/v2alpha/metric_model.proto#L40)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Yes it's a type. You should use the plural of support. 

s/<string>/<string> is how you do find and replace in the vi editor. :)
https://linuxize.com/post/vim-find-replace/
</blockquote></details>

I see. I am spoiled and couldn't understand the meaning of that vi syntax :P

Done
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric_model.proto` line 77 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NM9te4wD3M6kOLiPnoo:-NMfMBTI3NZ01war8s6G:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/957d63cd0848372cd7aa96e74561af6511e0b1df/src/main/proto/wfa/measurement/reporting/v2alpha/metric_model.proto#L77)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Just use "FAILED" to be consistent with the State in Metric. Sorry for the confusion.
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/report.proto` line 95 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NMfL-6uE1lUq8DZWcNG:-NMfRwODC1t1HPdCCigy:bdggwez) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5896804bc2fcede578fa562aff52f10b900f729f/src/main/proto/wfa/measurement/reporting/v2alpha/report.proto#L95)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

@SanjayVas @riemanli 

I think I'm seeing an issue with reporting set. If you want to create a report template that includes some slicing criteria you'll need to point to a reporting set, but because you can only specify a single reporting set in a report metric calculation the reporting set being pointed to would also have to specify the event groups.

So what if we made the key here  a pair of reporting sets?

Then the first reporting set is basically a set of filters and set operations where the leaf nodes are still composite reporting sets. Think "multi-level set expression with no event groups". The second reporting set is the set of event groups to apply the first thing in the pair to such that the second element is a virtual child of every leaf node in the parent.

I admit this is very similar to the original design, but with multiple levels of composition/filtering.
</blockquote></details>

I don't think I understand the issue. What do you mean "slicing criteria"? Could you provide an example of the issue?


<!-- Sent from Reviewable.io -->

2023-01-26 16:43 UTC, kungfucraig requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812)* status: 5 of 7 files reviewed, 7 unresolved discussions (waiting on @riemanli and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto` line 44 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NM9oYJV5F-wkDPrtv1I:-NMixBNXDLUmoX4lJISQ:baxbqzu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/957d63cd0848372cd7aa96e74561af6511e0b1df/src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto#L44)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Got it. 
Another question about `maximum_frequency_per_user` in WatchDuration. Do you what it's for and how we use this parameter in the MPC?
</blockquote></details>

Sorry, I don't understand the question.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/report.proto` line 78 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NMBOc_gCCKi4whLv8lC:-NMixNM43vARgXarUUIh:b-6dbeph) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2b28565896ffd91fd668498f09e817f086be1006/src/main/proto/wfa/measurement/reporting/v2alpha/report.proto#L78)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

>  if you specify a model it will be used for all metrics unless the model doesn't support those metrics in which case the Kingdom will be queried.

Key principles should include predictability and explicitness. If you specify the model, it will be used and the Kingdom won't be called. If you don't, then Kingdom will be called. If you specify a model and it's incompatible, an error is returned.
</blockquote></details>

I agree. I wasn't feeling too good about making that suggestion.

I really don't like that the ability to compute derived metrics will be split across ReportMetrics.


<!-- Sent from Reviewable.io -->

2023-01-26 17:59 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812)* status: 5 of 7 files reviewed, 7 unresolved discussions (waiting on @kungfucraig and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto` line 44 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NM9oYJV5F-wkDPrtv1I:-NMjCQlK3Zzt-IjvA8fC:bq16q58) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/957d63cd0848372cd7aa96e74561af6511e0b1df/src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto#L44)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Sorry, I don't understand the question.
</blockquote></details>

This `WatchDurationParams` mimics the setup in the CMMs [measurement_spec](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/main/src/main/proto/wfa/measurement/api/v2alpha/measurement_spec.proto#L73). I asked Jiayu about the usage of `maximum_frequency_per_user` in WatchDuration. It seems like we don't need this parameter to compute watch duration. Do you know if there is a specific reason why we have this parameter?


<!-- Sent from Reviewable.io -->

2023-01-26 19:27 UTC, kungfucraig requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812)* status: 5 of 7 files reviewed, 7 unresolved discussions (waiting on @riemanli and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto` line 44 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NM9oYJV5F-wkDPrtv1I:-NMjY0fZB2LKhsEURzjV:b-eyyvid) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/957d63cd0848372cd7aa96e74561af6511e0b1df/src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto#L44)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

This `WatchDurationParams` mimics the setup in the CMMs [measurement_spec](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/main/src/main/proto/wfa/measurement/api/v2alpha/measurement_spec.proto#L73). I asked Jiayu about the usage of `maximum_frequency_per_user` in WatchDuration. It seems like we don't need this parameter to compute watch duration. Do you know if there is a specific reason why we have this parameter?
</blockquote></details>

Just to close the loop, we discussed this offline and concluded that max freq per user doesn't make sense for duration.


<!-- Sent from Reviewable.io -->

2023-01-26 23:01 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812)* status: 4 of 7 files reviewed, 7 unresolved discussions (waiting on @kungfucraig and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto` line 44 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NM9oYJV5F-wkDPrtv1I:-NMkIXu61m-NbKN2Y9Sd:brnvge3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/957d63cd0848372cd7aa96e74561af6511e0b1df/src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto#L44)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Just to close the loop, we discussed this offline and concluded that max freq per user doesn't make sense for duration.
</blockquote></details>

Will remove this one and the one in CMMs `measurement_spec` in the next PR.


<!-- Sent from Reviewable.io -->

2023-01-30 18:18 UTC, tristanvuong2021 requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812)* status: 4 of 7 files reviewed, 10 unresolved discussions (waiting on @kungfucraig, @riemanli, and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto` line 126 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NN2tJPt7ujkQrbvCU-Z:-NN2tJPt7ujkQrbvCU-_:bqr954c) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e05f64d0a3ad80d2cefaf9f734ec4736cd4f6571/src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto#L126)):*
> ```protobuf
> 
>   // The resource name of the reporting set to calculate the metric on.
>   ReportingSet reporting_set = 2 [(google.api.field_behavior) = REQUIRED];
> ```

Should this be a string?
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric_models_service.proto` line 147 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NN2tQWRCud9NSvs-gTc:-NN2tQWRCud9NSvs-gTd:bt6ebap) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e05f64d0a3ad80d2cefaf9f734ec4736cd4f6571/src/main/proto/wfa/measurement/reporting/v2alpha/metric_models_service.proto#L147)):*
> ```protobuf
>   // The resource name of the reporting set that the model estimates the metric
>   // on.
>   ReportingSet reporting_set = 2 [(google.api.field_behavior) = REQUIRED];
> ```

Should this also be a string?
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/report.proto` line 146 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NN2t_p2CXt47GXJsSKq:-NN2t_p2CXt47GXJsSKr:bdvw8ud) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e05f64d0a3ad80d2cefaf9f734ec4736cd4f6571/src/main/proto/wfa/measurement/reporting/v2alpha/report.proto#L146)):*
> ```protobuf
> 
>     // The reporting set associated with this `MetricCalculationSpec`.
>     ReportingSet reporting_set = 2;
> ```

What about here?


<!-- Sent from Reviewable.io -->

2023-01-30 19:09 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812)* status: 4 of 7 files reviewed, 10 unresolved discussions (waiting on @kungfucraig, @SanjayVas, and @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto` line 126 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NN2tJPt7ujkQrbvCU-Z:-NN33zUp6xoTgzzOj0_O:blezr80) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e05f64d0a3ad80d2cefaf9f734ec4736cd4f6571/src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto#L126)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Should this be a string?
</blockquote></details>

`ReportingSet` is a oneof two strings defined in `reporting_set.proto`. If it's redundant, I can make it just string.


<!-- Sent from Reviewable.io -->

2023-01-30 19:32 UTC, kungfucraig requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812)* status: 4 of 7 files reviewed, 8 unresolved discussions (waiting on @riemanli and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto` line 104 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NN38dXg6Km3IppKmQZK:-NN38dXg6Km3IppKmQZL:ba131ot) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e05f64d0a3ad80d2cefaf9f734ec4736cd4f6571/src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto#L104)):*
> ```protobuf
>   oneof result {
>     // Reach value.
>     int64 reach = 3;
> ```

Can we use 

"Integer" and "Double" message types with a single value inside of them. We're going to have to introduce error bars pretty soon and that'll give us a place to put them.

Or we could do:

message ScalarResult {
   oneof value {
     int64 int_value;
     double double_value;
   }
}

But I think 

message IntegerResult {
  int64 value;
}
etc.

will be less cumbersome.

It also makes me wonder if we could call Histogram HistogramResult, again thinking about accommodating error bars.

cc: @SanjayVas 
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto` line 126 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NN2tJPt7ujkQrbvCU-Z:-NN39R6P1FJQqSUKwXCS:bvix28z) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e05f64d0a3ad80d2cefaf9f734ec4736cd4f6571/src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto#L126)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

`ReportingSet` is a oneof two strings defined in `reporting_set.proto`. If it's redundant, I can make it just string.
</blockquote></details>

I recall needing this structure for some reason, but the reason escapes me at the moment.


<!-- Sent from Reviewable.io -->

2023-01-31 00:25 UTC, SanjayVas requested changes
> Reviewed 1 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812)* status: 5 of 7 files reviewed, 10 unresolved discussions (waiting on @kungfucraig and @riemanli)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto` line 104 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NN38dXg6Km3IppKmQZK:-NN46Ymr0d9-UWVJskIH:bxduye2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e05f64d0a3ad80d2cefaf9f734ec4736cd4f6571/src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto#L104)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Can we use 

"Integer" and "Double" message types with a single value inside of them. We're going to have to introduce error bars pretty soon and that'll give us a place to put them.

Or we could do:

message ScalarResult {
   oneof value {
     int64 int_value;
     double double_value;
   }
}

But I think 

message IntegerResult {
  int64 value;
}
etc.

will be less cumbersome.

It also makes me wonder if we could call Histogram HistogramResult, again thinking about accommodating error bars.

cc: @SanjayVas 
</blockquote></details>

What's the structure of error bars? e.g. is it always some range of `double`s? Do histograms have a separate error range for each bin?

If the latter is true, then it means we need a different structure for histograms vs. scalars. I'd lean towards a separate wrapper message per data type in that case so it's explicit in the API what data type you're getting. Otherwise you would have to know that e.g. `impression_count` is always an int.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric_model.proto` line 29 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NN49IIh-h0UNEBbB-L6:-NN49IIh-h0UNEBbB-L7:b-jkwpwd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e05f64d0a3ad80d2cefaf9f734ec4736cd4f6571/src/main/proto/wfa/measurement/reporting/v2alpha/metric_model.proto#L29)):*
> ```protobuf
> 
> // A model for estimating metrics
> message MetricModel {
> ```

Remind me how we ended up with `MetricModel` instead of just `Model`. Are we expecting another type of model within the reporting API?



_Code quote:_
```protobuf
MetricModel
```
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric_model.proto` line 58 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NN4A0Yq9F9FHo93jmqS:-NN4A0Yq9F9FHo93jmqT:boitvdb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e05f64d0a3ad80d2cefaf9f734ec4736cd4f6571/src/main/proto/wfa/measurement/reporting/v2alpha/metric_model.proto#L58)):*
> ```protobuf
>     bool cumulative = 4;
> 
>     // Specifies the list of primitive reporting sets as the bases of the model.
> ```

nit: Format field documentation as a summary fragment followed optionally by paragraphs with more information, similar to [how we would write it if this were KDoc](https://developer.android.com/kotlin/style-guide#summary_fragment).
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/report.proto` line 69 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NN4C5O254uFZcvOzaWl:-NN4C5O254uFZcvOzaWm:bs90rot) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e05f64d0a3ad80d2cefaf9f734ec4736cd4f6571/src/main/proto/wfa/measurement/reporting/v2alpha/report.proto#L69)):*
> ```protobuf
> 
>     // A collection of metrics.
>     repeated MetricSpec metric_specs = 2
> ```

Add the IMMUTABLE field behavior here and elsewhere (there are multiple places missing it that should have it). For example, all fields in *Spec messages should be immutable, as well as any *Spec field.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/report.proto` line 115 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NN4BWhfCMHWKBjLVWBZ:-NN4BWhfCMHWKBjLVWB_:b-klpcqn) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e05f64d0a3ad80d2cefaf9f734ec4736cd4f6571/src/main/proto/wfa/measurement/reporting/v2alpha/report.proto#L115)):*
> ```protobuf
> 
>   // Types of time intervals for metric aggregation.
>   // REQUIRED
> ```

You can annotate the `oneof`, it's just that it doesn't use the trailing syntax. See https://github.com/protocolbuffers/protobuf/issues/2953#issuecomment-292631289



_Code quote:_
```protobuf
  // REQUIRED
```


<!-- Sent from Reviewable.io -->

2023-01-31 00:31 UTC, SanjayVas requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812)* status: 5 of 7 files reviewed, 10 unresolved discussions (waiting on @kungfucraig and @riemanli)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric_models_service.proto` line 156 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NN4DTes-prDFsAnU8GQ:-NN4DTes-prDFsAnU8GR:b3dig2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e05f64d0a3ad80d2cefaf9f734ec4736cd4f6571/src/main/proto/wfa/measurement/reporting/v2alpha/metric_models_service.proto#L156)):*
Fields in response messages are assumed to be OUTPUT_ONLY. See https://google.aip.dev/203#output-only:

> Notably, fields in response messages (a message which only ever acts as a return value to an RPC, usually ending in `Response`) *should not* be described as output only because this is already implied.



_Code quote:_
```protobuf
[(google.api.field_behavior) = OUTPUT_ONLY]
```
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/reporting_set.proto` line 121 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NN4D7DyAEukVikaZchP:-NN4D7DyAEukVikaZchQ:b-dzad4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e05f64d0a3ad80d2cefaf9f734ec4736cd4f6571/src/main/proto/wfa/measurement/reporting/v2alpha/reporting_set.proto#L121)):*
> ```protobuf
>   oneof type {
>     // The resource name of a primitive reporting set.
>     string primitive_reporting_set = 1;
> ```

If we're keeping the separate resource types, this needs a resource reference annotation.


<!-- Sent from Reviewable.io -->

2023-01-31 06:28 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812)* status: 5 of 7 files reviewed, 9 unresolved discussions (waiting on @kungfucraig and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto` line 104 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NN38dXg6Km3IppKmQZK:-NN5OZBxChGzIHTijmUM:bcsd7k6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e05f64d0a3ad80d2cefaf9f734ec4736cd4f6571/src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto#L104)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

What's the structure of error bars? e.g. is it always some range of `double`s? Do histograms have a separate error range for each bin?

If the latter is true, then it means we need a different structure for histograms vs. scalars. I'd lean towards a separate wrapper message per data type in that case so it's explicit in the API what data type you're getting. Otherwise you would have to know that e.g. `impression_count` is always an int.
</blockquote></details>

An error bar for scalar results aka confidence interval should at least have an upper bound and a lower bound. In addition, it should indicate the confidence level. 
For multi-dimensional case like histogram, confidence region is an option, but I am not sure if it's feasible to do. We should ask Jiayu if he already has some idea in mind. 
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric_model.proto` line 29 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NN49IIh-h0UNEBbB-L6:-NN4JF9QAxujZqYpSkKI:bg1fih8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e05f64d0a3ad80d2cefaf9f734ec4736cd4f6571/src/main/proto/wfa/measurement/reporting/v2alpha/metric_model.proto#L29)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Remind me how we ended up with `MetricModel` instead of just `Model`. Are we expecting another type of model within the reporting API?
</blockquote></details>

I was thinking to separate the model that estimates metrics and the model that does counterfactual planning. MetricModel is for the former one.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric_model.proto` line 58 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NN4A0Yq9F9FHo93jmqS:-NN57YkJ6vQ-kinLR5jh:bb6un1j) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e05f64d0a3ad80d2cefaf9f734ec4736cd4f6571/src/main/proto/wfa/measurement/reporting/v2alpha/metric_model.proto#L58)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: Format field documentation as a summary fragment followed optionally by paragraphs with more information, similar to [how we would write it if this were KDoc](https://developer.android.com/kotlin/style-guide#summary_fragment).
</blockquote></details>

Done
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric_models_service.proto` line 156 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NN4DTes-prDFsAnU8GQ:-NN57t4J886sbK6XCfPs:b-fq0cct) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e05f64d0a3ad80d2cefaf9f734ec4736cd4f6571/src/main/proto/wfa/measurement/reporting/v2alpha/metric_models_service.proto#L156)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Fields in response messages are assumed to be OUTPUT_ONLY. See https://google.aip.dev/203#output-only:

> Notably, fields in response messages (a message which only ever acts as a return value to an RPC, usually ending in `Response`) *should not* be described as output only because this is already implied.
</blockquote></details>

Thanks for pointing that out! Done.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/report.proto` line 69 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NN4C5O254uFZcvOzaWl:-NN5DSg5Dy77mwlkXRxc:b-ualgbp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e05f64d0a3ad80d2cefaf9f734ec4736cd4f6571/src/main/proto/wfa/measurement/reporting/v2alpha/report.proto#L69)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Add the IMMUTABLE field behavior here and elsewhere (there are multiple places missing it that should have it). For example, all fields in *Spec messages should be immutable, as well as any *Spec field.
</blockquote></details>

Thanks for pointing that out! Done
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/report.proto` line 115 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NN4BWhfCMHWKBjLVWBZ:-NN5Jz1z6slGoVqTg2Vs:b-36adpa) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e05f64d0a3ad80d2cefaf9f734ec4736cd4f6571/src/main/proto/wfa/measurement/reporting/v2alpha/report.proto#L115)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

You can annotate the `oneof`, it's just that it doesn't use the trailing syntax. See https://github.com/protocolbuffers/protobuf/issues/2953#issuecomment-292631289
</blockquote></details>

Thanks for sharing that! In order to reuse the option in different protos, I have to extend the option in time_interval.proto. Please let me know if that's a problem.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/reporting_set.proto` line 121 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NN4D7DyAEukVikaZchP:-NN5NJgm-rtssbuFos9Q:bb6un1j) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e05f64d0a3ad80d2cefaf9f734ec4736cd4f6571/src/main/proto/wfa/measurement/reporting/v2alpha/reporting_set.proto#L121)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

If we're keeping the separate resource types, this needs a resource reference annotation.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-01-31 07:26 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812)* status: 1 of 9 files reviewed, 10 unresolved discussions (waiting on @kungfucraig and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/report.proto` line 37 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NN5hq3P41NXDLeCOWgL:-NN5hq3P41NXDLeCOWgM:bz3fltz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e05f64d0a3ad80d2cefaf9f734ec4736cd4f6571/src/main/proto/wfa/measurement/reporting/v2alpha/report.proto#L37)):*
> ```protobuf
> 
>   // Resource name.
>   string name = 1 [(google.api.field_behavior) = REQUIRED];
> ```

@SanjayVas do we need this field to be required? It's not in v1alpha, so I am not sure if my change is needed.


<!-- Sent from Reviewable.io -->

2023-01-31 20:06 UTC, SanjayVas reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812)* status: 1 of 9 files reviewed, 10 unresolved discussions (waiting on @kungfucraig)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/report.proto` line 95 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NMfL-6uE1lUq8DZWcNG:-NN8N_uf6dF6GHaLQmLP:b-xkrufp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5896804bc2fcede578fa562aff52f10b900f729f/src/main/proto/wfa/measurement/reporting/v2alpha/report.proto#L95)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

I don't think I understand the issue. What do you mean "slicing criteria"? Could you provide an example of the issue?
</blockquote></details>

This was discussed offline. The basic issue being called out here is that we have reuse of concrete reporting sets, but no way to reuse the structure of set expressions swapping in different event groups. This is basically a design tradeoff, where trying to support this would be quite complicated.

The upshot of the current design is thus: a reporting set describes both a venn diagram and the section of that venn diagram that we're interested in. Anything you want to do with the same venn diagram section should be possible by reusing the same reporting set. If you want to use a different venn diagram or section (e.g. by changing which event groups are described by which circle), you'll need to use a different reporting set.

I think this is fine for now, but we can do some exploration of trying to form the requests for some useful charts.


<!-- Sent from Reviewable.io -->

2023-01-31 22:21 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812)* status: 1 of 9 files reviewed, 10 unresolved discussions (waiting on @kungfucraig and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto` line 104 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NN38dXg6Km3IppKmQZK:-NN8qWKR3xq0mOeFLDvr:b-piniio) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e05f64d0a3ad80d2cefaf9f734ec4736cd4f6571/src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto#L104)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

An error bar for scalar results aka confidence interval should at least have an upper bound and a lower bound. In addition, it should indicate the confidence level. 
For multi-dimensional case like histogram, confidence region is an option, but I am not sure if it's feasible to do. We should ask Jiayu if he already has some idea in mind. 
</blockquote></details>

Modified the metric result. Please let me know if there is anything else that needs modification.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto` line 126 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NN2tJPt7ujkQrbvCU-Z:-NN8uPkDAn_iCKzTH0g3:bgs6jpd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e05f64d0a3ad80d2cefaf9f734ec4736cd4f6571/src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto#L126)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

I recall needing this structure for some reason, but the reason escapes me at the moment.
</blockquote></details>

Based on the discussion offline, it should be string. Done.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric_models_service.proto` line 147 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NN2tQWRCud9NSvs-gTc:-NN8u7C932JNzyVFobWX:bgs6jpd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e05f64d0a3ad80d2cefaf9f734ec4736cd4f6571/src/main/proto/wfa/measurement/reporting/v2alpha/metric_models_service.proto#L147)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Should this also be a string?
</blockquote></details>

Based on the discussion offline, it should be string. Done.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/report.proto` line 146 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NN2t_p2CXt47GXJsSKq:-NN8uIty2YjZU8sg2D9e:bgs6jpd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e05f64d0a3ad80d2cefaf9f734ec4736cd4f6571/src/main/proto/wfa/measurement/reporting/v2alpha/report.proto#L146)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

What about here?
</blockquote></details>

Based on the discussion offline, it should be string. Done.


<!-- Sent from Reviewable.io -->

2023-02-06 22:34 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812)* status: 1 of 11 files reviewed, 9 unresolved discussions (waiting on @kungfucraig, @SanjayVas, and @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/report.proto` line 95 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NMfL-6uE1lUq8DZWcNG:-NNcrM5B78V7hn1LQoRB:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5896804bc2fcede578fa562aff52f10b900f729f/src/main/proto/wfa/measurement/reporting/v2alpha/report.proto#L95)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This was discussed offline. The basic issue being called out here is that we have reuse of concrete reporting sets, but no way to reuse the structure of set expressions swapping in different event groups. This is basically a design tradeoff, where trying to support this would be quite complicated.

The upshot of the current design is thus: a reporting set describes both a venn diagram and the section of that venn diagram that we're interested in. Anything you want to do with the same venn diagram section should be possible by reusing the same reporting set. If you want to use a different venn diagram or section (e.g. by changing which event groups are described by which circle), you'll need to use a different reporting set.

I think this is fine for now, but we can do some exploration of trying to form the requests for some useful charts.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-02-07 01:09 UTC, SanjayVas requested changes
> Reviewed 1 of 7 files at r2, 2 of 8 files at r10, 3 of 6 files at r11, 2 of 3 files at r12, 3 of 3 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812)* status: all files reviewed, 20 unresolved discussions (waiting on @kungfucraig, @riemanli, and @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto` line 44 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NM9oYJV5F-wkDPrtv1I:-NNdGZbhD3efBxzp1fYn:b7vmiqg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/957d63cd0848372cd7aa96e74561af6511e0b1df/src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto#L44)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Will remove this one and the one in CMMs `measurement_spec` in the next PR.
</blockquote></details>

Why not remove this one in this PR, since it's a new API? We can remove the one in the CMMS API in parallel, since it'll take awhile to get this one implemented anyway.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto` line 143 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NNdHwLz3j9yJMiN-DZk:-NNdHwLz3j9yJMiN-DZl:b-8aelw9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3ce569b7f8cd6802fece90a6aa48468a951b0db3/src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto#L143)):*
> ```protobuf
>   };
>   // Resource name
>   string name = 1 [(google.api.field_behavior) = REQUIRED];
> ```

The `name` field of a resource message type cannot be REQUIRED in our API as it's not set on Create requests.



_Code quote:_
```protobuf
 [(google.api.field_behavior) = REQUIRED]
```
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto` line 147 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NNdIEcN2ZpKhngvDN1N:-NNdIEcN2ZpKhngvDN1O:bl3bdm6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3ce569b7f8cd6802fece90a6aa48468a951b0db3/src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto#L147)):*
> ```protobuf
>   // The resource name of the reporting set to calculate the metric on.
>   string reporting_set = 2 [
>     (google.api.field_behavior) = REQUIRED,
> ```

Also IMMUTABLE
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto` line 148 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NNdHhNz1DWdhHqsJvgf:-NNdHhNz1DWdhHqsJvgg:b-jikbho) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3ce569b7f8cd6802fece90a6aa48468a951b0db3/src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto#L148)):*
> ```protobuf
>   string reporting_set = 2 [
>     (google.api.field_behavior) = REQUIRED,
>     (google.api.resource_reference) = { type: "halo.wfanet.org/ReportingSet" }
> ```

We're using `reporting.halo-cmm.org` for the Reporting API, so this should be `reporting.halo-cmm.org/ReportingSet`



_Code quote:_
```protobuf
halo.wfanet.org/ReportingSet
```
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto` line 152 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NNdIGgZAqdZg4OUF3EG:-NNdIGgZAqdZg4OUF3EH:bl3bdm6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3ce569b7f8cd6802fece90a6aa48468a951b0db3/src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto#L152)):*
> ```protobuf
> 
>   // The time over which to calculate the metric cumulatively.
>   TimeInterval time_interval = 3 [(google.api.field_behavior) = REQUIRED];
> ```

Also IMMUTABLE
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto` line 162 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NNdIHKuEyuVBFxS9CEU:-NNdIHKuEyuVBFxS9CEV:bl3bdm6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3ce569b7f8cd6802fece90a6aa48468a951b0db3/src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto#L162)):*
> ```protobuf
>   // Additional filters that will be combined with AND boolean operation and
>   // applied to the reporting set. If unspecified, evaluates to `true`
>   repeated string filters = 5;
> ```

Also IMMUTABLE
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric_models_service.proto` line 61 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NNdJVZZ0n2uZMWYuzy2:-NNdJVZ_2elsaJRI9D06:burh3q0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3ce569b7f8cd6802fece90a6aa48468a951b0db3/src/main/proto/wfa/measurement/reporting/v2alpha/metric_models_service.proto#L61)):*
> ```protobuf
> 
>   // Applies the metric model to estimate the metric result.
>   // Will return a RPC error if the model hasn't been trained yet.
> ```

Specify the error code



_Suggestion:_
```protobuf
Results in a `FAILED_PRECONDITION` error
```
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/report.proto` line 37 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NN5hq3P41NXDLeCOWgL:-NNdKLCh-_W8rU8mzFsf:bynh7e8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e05f64d0a3ad80d2cefaf9f734ec4736cd4f6571/src/main/proto/wfa/measurement/reporting/v2alpha/report.proto#L37)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

@SanjayVas do we need this field to be required? It's not in v1alpha, so I am not sure if my change is needed.
</blockquote></details>

I noted this in another comment. It *cannot* be required, as it's not set on Create requests.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/report.proto` line 115 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NN4BWhfCMHWKBjLVWBZ:-NNdNDC01HKzkwZi2IHK:bt55dgu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e05f64d0a3ad80d2cefaf9f734ec4736cd4f6571/src/main/proto/wfa/measurement/reporting/v2alpha/report.proto#L115)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Thanks for sharing that! In order to reuse the option in different protos, I have to extend the option in time_interval.proto. Please let me know if that's a problem.
</blockquote></details>

Sorry, I did not intend for you to add a new option. Rather, I had assumed that the above syntax would allow you to apply the existing field_behavior option to `oneof` fields to indicate that exactly one field in the oneof must be specified (rather than at most one).

If this is incorrect (i.e. FieldOptions cannot be applied to `oneof`s), then just drop the option and leave it as a comment.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/report.proto` line 40 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NNdKblO8RQxGe9p8GpG:-NNdKblO8RQxGe9p8GpH:b-j082i4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3ce569b7f8cd6802fece90a6aa48468a951b0db3/src/main/proto/wfa/measurement/reporting/v2alpha/report.proto#L40)):*
> ```protobuf
> 
>   // Representation of a Measurement Consumer entity.
>   string measurement_consumer = 2 [
> ```

We don't need this field. This is just the resource name of the parent, which we can determine from this Report's resource name.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/report.proto` line 49 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NNdL7uK9QPeCJoIiRzR:-NNdL7uK9QPeCJoIiRz [...]

2023-02-07 22:43 UTC, kungfucraig requested changes
> Reviewed 2 of 8 files at r10, 2 of 6 files at r11, 2 of 3 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812)* status: all files reviewed, 29 unresolved discussions (waiting on @riemanli and @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/event_group.proto` line 38 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NNglrWV0IxGjnYLsNHV:-NNglrWV0IxGjnYLsNHW:b-kffgs7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3ce569b7f8cd6802fece90a6aa48468a951b0db3/src/main/proto/wfa/measurement/reporting/v2alpha/event_group.proto#L38)):*
> ```protobuf
>   string name = 1;
> 
>   // Resource name of the `DataProvider` associated with this `EventGroup`.
> ```

Is this a Kingdom resource? If so, can you add that to the comment? The resource reference type makes me think it could be, but I don't know.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/event_group.proto` line 47 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NNgm6DX7s3Oh6DKJZS7:-NNgm6DX7s3Oh6DKJZS8:b-1y9yaf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3ce569b7f8cd6802fece90a6aa48468a951b0db3/src/main/proto/wfa/measurement/reporting/v2alpha/event_group.proto#L47)):*
> ```protobuf
>   // `DataProvider`.
>   //
>   // If set, this value must be unique among `EventGroup`s for the parent
> ```

This is the EDP's ID or the Kingdom's ID?
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/event_group.proto` line 53 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NNgmQi4CpaR5-wuOhVU:-NNgmQi4CpaR5-wuOhVV:bhn6x33) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3ce569b7f8cd6802fece90a6aa48468a951b0db3/src/main/proto/wfa/measurement/reporting/v2alpha/event_group.proto#L53)):*
> ```protobuf
>   // The template that events associated with this `EventGroup` conform to.
>   message EventTemplate {
>     // The type of the Event Template. A fully-qualified protobuf message type.
> ```

These types are expected to be compiled into binaries right? If so, can you put that in the comment? Either way, can you explain where to find the definition of these messages, (in generic terms). I know that it depends in the deployment. You should also say that. :)
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto` line 56 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NNhxHNf0cJE20AccTX1:-NNhxHNf0cJE20AccTX2:b-54egn4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3ce569b7f8cd6802fece90a6aa48468a951b0db3/src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto#L56)):*
> ```protobuf
>   // Parameters that are used to generate `Watch Duration` metric.
>   message WatchDurationParams {
>     // Maximum frequency per user that will be included in this metric. Enforced
> ```

Delete this.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto` line 72 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NNhxV0x1e59M5vj6pn-:-NNhxV0x1e59M5vj6pn0:b-2xxdai) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3ce569b7f8cd6802fece90a6aa48468a951b0db3/src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto#L72)):*
> ```protobuf
>   // Types of metric with parameters.
>   oneof type {
>     option (oneof_time_required_option) = 1111;
> ```

oneof_type_required_option ?
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto` line 151 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NNhzO-BANPfFoIMFoPL:-NNhzO-BANPfFoIMFoPM:b-dq3niz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3ce569b7f8cd6802fece90a6aa48468a951b0db3/src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto#L151)):*
> ```protobuf
>   ];
> 
>   // The time over which to calculate the metric cumulatively.
> ```

Add that the LHS is closed and the RHS is open?
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric_model.proto` line 1 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NNhzo4xCvbE4ZpDsspg:-NNhzo4xCvbE4ZpDssph:bbpmjjk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3ce569b7f8cd6802fece90a6aa48468a951b0db3/src/main/proto/wfa/measurement/reporting/v2alpha/metric_model.proto#L1)):*
> ```protobuf
> // Copyright 2023 The Cross-Media Measurement Authors
> ```

Can you do a separate PR for all of the modeling protos?
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/report.proto` line 29 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NNi-tm9-7RDORqPiFmr:-NNi-tm9-7RDORqPiFms:b-dsfho1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3ce569b7f8cd6802fece90a6aa48468a951b0db3/src/main/proto/wfa/measurement/reporting/v2alpha/report.proto#L29)):*
> ```protobuf
> option java_outer_classname = "ReportProto";
> 
> // Resource representing a report.
> ```

Can you summarize the metric fan out, and how groupings, time, etc. contribute?
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/report.proto` line 73 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NNi-lyZ5oh8JNxJJOll:-NNi-lyZ5oh8JNxJJOlm:bviy4am) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3ce569b7f8cd6802fece90a6aa48468a951b0db3/src/main/proto/wfa/measurement/reporting/v2alpha/report.proto#L73)):*
> ```protobuf
>     // The final set of groups is the Cartesian product of `groupings`. The
>     // final set of groups will fan out multiple metrics per metric spec, i.e.
>     // one metric for one group in the set.
> ```

"one metric per element of the cross product of the groupings"?
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/report.proto` line 86 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NNi07rx9DEVq74CiOIu:-NNi07rx9DEVq74CiOIv:b880a11) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3ce569b7f8cd6802fece90a6aa48468a951b0db3/src/main/proto/wfa/measurement/reporting/v2alpha/report.proto#L86)):*
> ```protobuf
>     // all primitive reporting set bases of the reporting set used for the
>     // metric calculations.
>     string model = 5 [(google.api.field_behavior) = IMMUTABLE];
> ```

Drop this for now.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/report.proto` line 102 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NNi0M297-Ngp73fPUvs:-NNi0M297-Ngp73fPUvt:b-h0gzaa) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3ce569b7f8cd6802fece90a6aa48468a951b0db3/src/main/proto/wfa/measurement/reporting/v2alpha/report.proto#L102)):*
> ```protobuf
>     message ReportingMetricEntry {
>       // Key of the map entry.
>       string key = 1 [
> ```

Should "key" be "reporting_set_name"?
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/reporting_set.proto` line 28 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NNi1-BO2Zu4vSOTCmk_:-NNi1-BO2Zu4vSOTCmka:b-w28h5u) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3ce569b7f8cd6802fece90a6aa48468a951b0db3/src/main/proto/wfa/measurement/reporting/v2alpha/reporting_set.proto#L28)):*
> ```protobuf
> 
> extend google.protobuf.OneofOptions {
>   [...]

2023-02-08 00:07 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812)* status: 5 of 12 files reviewed, 26 unresolved discussions (waiting on @kungfucraig, @SanjayVas, and @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/event_group.proto` line 38 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NNglrWV0IxGjnYLsNHV:-NNi2buU8TJMzvCHc3F1:b-6zgf27) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3ce569b7f8cd6802fece90a6aa48468a951b0db3/src/main/proto/wfa/measurement/reporting/v2alpha/event_group.proto#L38)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Is this a Kingdom resource? If so, can you add that to the comment? The resource reference type makes me think it could be, but I don't know.
</blockquote></details>

Yes it is. Added.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/event_group.proto` line 47 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NNgm6DX7s3Oh6DKJZS7:-NNi3G6B3lBpkJJeT-JO:b-tsmds8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3ce569b7f8cd6802fece90a6aa48468a951b0db3/src/main/proto/wfa/measurement/reporting/v2alpha/event_group.proto#L47)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

This is the EDP's ID or the Kingdom's ID?
</blockquote></details>

Note that this is copied from the v1apha as there is no change on the event groups and that this was written by Chiping who no longer works on the project. 

@SanjayVas do you know which ID is it?
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto` line 44 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NM9oYJV5F-wkDPrtv1I:-NNgpgt-CpufHfz_pIsI:by19uwp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/957d63cd0848372cd7aa96e74561af6511e0b1df/src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto#L44)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Why not remove this one in this PR, since it's a new API? We can remove the one in the CMMS API in parallel, since it'll take awhile to get this one implemented anyway.
</blockquote></details>

Sounds good! Done.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto` line 56 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NNhxHNf0cJE20AccTX1:-NNi4d8n4YQW0s9NRIq0:bb6un1j) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3ce569b7f8cd6802fece90a6aa48468a951b0db3/src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto#L56)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Delete this.
</blockquote></details>

Done
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto` line 72 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NNhxV0x1e59M5vj6pn-:-NNiDExm9WtaIGS9k17q:b8kgwwo) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3ce569b7f8cd6802fece90a6aa48468a951b0db3/src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto#L72)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

oneof_type_required_option ?
</blockquote></details>

I misunderstood Sanjay's previous comment. Removed now.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto` line 143 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NNdHwLz3j9yJMiN-DZk:-NNhK5lI1NtL1mQ9O_Yj:bwgtafn) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3ce569b7f8cd6802fece90a6aa48468a951b0db3/src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto#L143)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The `name` field of a resource message type cannot be REQUIRED in our API as it's not set on Create requests.
</blockquote></details>

Thanks for letting me know. Removed.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto` line 147 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NNdIEcN2ZpKhngvDN1N:-NNhKypk09WmjO9H7AN5:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3ce569b7f8cd6802fece90a6aa48468a951b0db3/src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto#L147)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Also IMMUTABLE
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto` line 148 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NNdHhNz1DWdhHqsJvgf:-NNhL6GuBoBdg79jqkNa:b-a9h8dt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3ce569b7f8cd6802fece90a6aa48468a951b0db3/src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto#L148)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

We're using `reporting.halo-cmm.org` for the Reporting API, so this should be `reporting.halo-cmm.org/ReportingSet`
</blockquote></details>

Thanks for pointing it out! Done. Also fixed the other places.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto` line 151 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NNhzO-BANPfFoIMFoPL:-NNi4n4i-TE6iD-wDKCm:bilk872) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3ce569b7f8cd6802fece90a6aa48468a951b0db3/src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto#L151)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Add that the LHS is closed and the RHS is open?
</blockquote></details>

That is already mentioned in `time_interval.proto`. Is it necessary to mention it again here?
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto` line 152 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NNdIGgZAqdZg4OUF3EG:-NNhMT_j-llPVZ7fxfGv:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3ce569b7f8cd6802fece90a6aa48468a951b0db3/src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto#L152)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Also IMMUTABLE
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto` line 162 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NNdIHKuEyuVBFxS9CEU:-NNhMYTC1RBPn-3HTO9Q:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3ce569b7f8cd6802fece90a6aa48468a951b0db3/src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto#L162)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Also IMMUTABLE
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric_models_service.proto` line 61 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NNdJVZZ0n2uZMWYuzy2:-NNhN86HAguGK6s3nEhr:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3ce569b7f8cd6802fece90a6aa48468a951b0db3/src/main/proto/wfa/measurement/reporting/v2alpha/metric_models_service.proto#L61)):*
<d [...]

2023-02-08 00:13 UTC, tristanvuong2021 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812)* status: 5 of 12 files reviewed, 26 unresolved discussions (waiting on @kungfucraig, @riemanli, and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/event_group.proto` line 47 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NNgm6DX7s3Oh6DKJZS7:-NNiM_E1EsvvTN8DqN4-:b-2zw7m9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3ce569b7f8cd6802fece90a6aa48468a951b0db3/src/main/proto/wfa/measurement/reporting/v2alpha/event_group.proto#L47)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Note that this is copied from the v1apha as there is no change on the event groups and that this was written by Chiping who no longer works on the project. 

@SanjayVas do you know which ID is it?
</blockquote></details>

This is https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/af84c72e3d4a8e2bfa5e821e563ee54fe49343e1/src/main/proto/wfa/measurement/api/v2alpha/event_group.proto#L58


<!-- Sent from Reviewable.io -->

2023-02-08 00:14 UTC, tristanvuong2021 commented
*[`src/main/proto/wfa/measurement/reporting/v2alpha/event_group.proto` line 47 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NNgm6DX7s3Oh6DKJZS7:-NNiMibu-ozIH0TvGSxR:b-e2jo59) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3ce569b7f8cd6802fece90a6aa48468a951b0db3/src/main/proto/wfa/measurement/reporting/v2alpha/event_group.proto#L47)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

This is https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/af84c72e3d4a8e2bfa5e821e563ee54fe49343e1/src/main/proto/wfa/measurement/api/v2alpha/event_group.proto#L58
</blockquote></details>

It is provided on event group creation and would generated on the data provider side.


<!-- Sent from Reviewable.io -->

2023-02-08 00:39 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812)* status: 5 of 12 files reviewed, 26 unresolved discussions (waiting on @kungfucraig, @SanjayVas, and @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/event_group.proto` line 53 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NNgmQi4CpaR5-wuOhVU:-NNiNgGkAc-YXuooKR5W:b-vsurnq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3ce569b7f8cd6802fece90a6aa48468a951b0db3/src/main/proto/wfa/measurement/reporting/v2alpha/event_group.proto#L53)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

These types are expected to be compiled into binaries right? If so, can you put that in the comment? Either way, can you explain where to find the definition of these messages, (in generic terms). I know that it depends in the deployment. You should also say that. :)
</blockquote></details>

1. It's store in the serialized `details` in the database. Is that what you meant by "compiled into binaries"? 
2. There is a README about [Event Filtration](https://github.com/world-federation-of-advertisers/cross-media-measurement/tree/main/src/main/kotlin/org/wfanet/measurement/eventdataprovider#event-filtration). Is that something you were referring for the definitions?

cc: @SanjayVas @tristanvuong2021 
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/report.proto` line 86 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NNi07rx9DEVq74CiOIu:-NNiST8h1L117Y1oPGJt:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3ce569b7f8cd6802fece90a6aa48468a951b0db3/src/main/proto/wfa/measurement/reporting/v2alpha/report.proto#L86)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Drop this for now.
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric_model.proto` line 1 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NNhzo4xCvbE4ZpDsspg:-NNiRzzsATsHEB6f0RXo:bcwh8ll) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3ce569b7f8cd6802fece90a6aa48468a951b0db3/src/main/proto/wfa/measurement/reporting/v2alpha/metric_model.proto#L1)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Can you do a separate PR for all of the modeling protos?
</blockquote></details>

Sure. Removed model related code. Will create another PR for it.

cc: @tristanvuong2021 @SanjayVas 


<!-- Sent from Reviewable.io -->

2023-02-08 01:10 UTC, SanjayVas requested changes
> Reviewed 4 of 7 files at r14, 3 of 3 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812)* status: all files reviewed, 16 unresolved discussions (waiting on @kungfucraig, @riemanli, and @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/event_group.proto` line 53 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NNgmQi4CpaR5-wuOhVU:-NNiWop273aY3K6ApDgw:bh8391g) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3ce569b7f8cd6802fece90a6aa48468a951b0db3/src/main/proto/wfa/measurement/reporting/v2alpha/event_group.proto#L53)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

1. It's store in the serialized `details` in the database. Is that what you meant by "compiled into binaries"? 
2. There is a README about [Event Filtration](https://github.com/world-federation-of-advertisers/cross-media-measurement/tree/main/src/main/kotlin/org/wfanet/measurement/eventdataprovider#event-filtration). Is that something you were referring for the definitions?

cc: @SanjayVas @tristanvuong2021 
</blockquote></details>

I believe what Craig is trying to say is that anyone using this template is expected to have this message type available at runtime. This often means having it as a compile-time dependency, but that's not strictly necessary especially depending on which programming language you're using to read it.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/report.proto` line 40 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NNdKblO8RQxGe9p8GpG:-NNiXdWm44P1dlFVzcz5:b2efpyh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3ce569b7f8cd6802fece90a6aa48468a951b0db3/src/main/proto/wfa/measurement/reporting/v2alpha/report.proto#L40)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

In case you were wondering why we don't need this field but have data_provider on EventGroup, that case is to allow filtering by data_provider in List calls (e.g. to get all event groups from a known strict subset of data providers). In this API, the caller is always an MC so filtering by MC is never useful.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/report.proto` line 102 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NNi0M297-Ngp73fPUvs:-NNiYOnr9WRKu6XsCt3t:b-jjv5gu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3ce569b7f8cd6802fece90a6aa48468a951b0db3/src/main/proto/wfa/measurement/reporting/v2alpha/report.proto#L102)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

This is convention for backward compatibility: https://developers.google.com/protocol-buffers/docs/proto3#backwards_compatibility
</blockquote></details>

For @kungfucraig, we would have used a proto3 Map field here except that there's no way to set field options on the key of a Map. Therefore in order to have the resource reference annotation, we need to decompose the map.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/reporting_set.proto` line 64 at r15](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NNiZ068A0TrFs4O_KlO:-NNiZ068A0TrFs4O_KlP:b4jse4c) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/59c908f172c6ae8bb9268375f030f7938eb6543f/src/main/proto/wfa/measurement/reporting/v2alpha/reporting_set.proto#L64)):*
> ```protobuf
> //
> // It's the minimum building block of a set expression.
> message PrimitiveReportingSet {
> ```

nit: these message definitions can be nested inside of ReportingSet, as they are never referenced outside of that message type. You can then trim the redundant suffix and just have them be Primitive and Composite.



_Code quote:_
```protobuf
message PrimitiveReportingSet
```
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/reporting_set.proto` line 78 at r15](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NNiZJPnEC3cSm35AIZA:-NNiZJPnEC3cSm35AIZB:bfipee2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/59c908f172c6ae8bb9268375f030f7938eb6543f/src/main/proto/wfa/measurement/reporting/v2alpha/reporting_set.proto#L78)):*
> ```protobuf
> message CompositeReportingSet {
>   // A nested expression of binary set expressions.
>   SetExpression expression = 1 [(google.api.field_behavior) = REQUIRED];
> ```

Also IMMUTABLE. We do not allow ReportingSets to be changed.


<!-- Sent from Reviewable.io -->

2023-02-08 01:27 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812)* status: 11 of 12 files reviewed, 16 unresolved discussions (waiting on @kungfucraig, @SanjayVas, and @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/report.proto` line 40 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NNdKblO8RQxGe9p8GpG:-NNi_KSM-LGLABk2Mhbp:b-wsvasg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3ce569b7f8cd6802fece90a6aa48468a951b0db3/src/main/proto/wfa/measurement/reporting/v2alpha/report.proto#L40)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

In case you were wondering why we don't need this field but have data_provider on EventGroup, that case is to allow filtering by data_provider in List calls (e.g. to get all event groups from a known strict subset of data providers). In this API, the caller is always an MC so filtering by MC is never useful.
</blockquote></details>

Thanks for the explanation!
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/report.proto` line 102 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NNi0M297-Ngp73fPUvs:-NNi__UKCR6avni7arGg:b-79tdgz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3ce569b7f8cd6802fece90a6aa48468a951b0db3/src/main/proto/wfa/measurement/reporting/v2alpha/report.proto#L102)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

For @kungfucraig, we would have used a proto3 Map field here except that there's no way to set field options on the key of a Map. Therefore in order to have the resource reference annotation, we need to decompose the map.
</blockquote></details>

Thanks for the explanation Sanjay.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/reporting_set.proto` line 64 at r15](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NNiZ068A0TrFs4O_KlO:-NNiaXSr4swTCl8xkfTG:bvu9xpw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/59c908f172c6ae8bb9268375f030f7938eb6543f/src/main/proto/wfa/measurement/reporting/v2alpha/reporting_set.proto#L64)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: these message definitions can be nested inside of ReportingSet, as they are never referenced outside of that message type. You can then trim the redundant suffix and just have them be Primitive and Composite.
</blockquote></details>

That's a good point. The reason why we have it outside is because model used `PrimitiveReportingSet` in the previous design, but it does not now.
Move `PrimitiveReportingSet` and `CompositeReportingSet`into `ReportingSet`. PTAL.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/reporting_set.proto` line 78 at r15](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NNiZJPnEC3cSm35AIZA:-NNiaO4Y7kj8UkImplir:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/59c908f172c6ae8bb9268375f030f7938eb6543f/src/main/proto/wfa/measurement/reporting/v2alpha/reporting_set.proto#L78)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Also IMMUTABLE. We do not allow ReportingSets to be changed.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-02-08 17:09 UTC, SanjayVas reviewed
> Reviewed 1 of 1 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812)* status: all files reviewed, 15 unresolved discussions (waiting on @kungfucraig, @riemanli, and @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/reporting_set.proto` line 27 at r16](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NNm-5PFCFAK1UMflrRJ:-NNm-5PFCFAK1UMflrRK:b-ul9qbv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0260a116571762990e677614bbbbbb8ef139e41b/src/main/proto/wfa/measurement/reporting/v2alpha/reporting_set.proto#L27)):*
> ```protobuf
> 
> // Represents a binary set expression.
> message SetExpression {
> ```

I believe this can also be moved into ReportingSet.


<!-- Sent from Reviewable.io -->

2023-02-08 17:13 UTC, SanjayVas approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812)* status: all files reviewed, 14 unresolved discussions (waiting on @kungfucraig, @riemanli, and @tristanvuong2021)



<!-- Sent from Reviewable.io -->

2023-02-08 17:20 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812)* status: all files reviewed, 14 unresolved discussions (waiting on @kungfucraig, @SanjayVas, and @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/reporting_set.proto` line 27 at r16](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NNm-5PFCFAK1UMflrRJ:-NNm1Orn80eXV7REz1S9:bvcnhsc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0260a116571762990e677614bbbbbb8ef139e41b/src/main/proto/wfa/measurement/reporting/v2alpha/reporting_set.proto#L27)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I believe this can also be moved into ReportingSet.
</blockquote></details>

I wonder if further moving it into Composite would be better.


<!-- Sent from Reviewable.io -->

2023-02-08 17:48 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812)* status: 9 of 12 files reviewed, 14 unresolved discussions (waiting on @kungfucraig, @SanjayVas, and @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/event_group.proto` line 53 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NNgmQi4CpaR5-wuOhVU:-NNm5jZDDKjPkeBPiQ5E:bfyku80) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3ce569b7f8cd6802fece90a6aa48468a951b0db3/src/main/proto/wfa/measurement/reporting/v2alpha/event_group.proto#L53)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I believe what Craig is trying to say is that anyone using this template is expected to have this message type available at runtime. This often means having it as a compile-time dependency, but that's not strictly necessary especially depending on which programming language you're using to read it.
</blockquote></details>

Maybe I am missing something here. My understanding is that event templates are stored on the EDP's side, so neither the actual template type referenced here nor the definitions of event templates and metadata can be found in the CMM.


<!-- Sent from Reviewable.io -->

2023-02-08 19:46 UTC, tristanvuong2021 reviewed
> Reviewed 1 of 8 files at r10, 1 of 7 files at r14, 2 of 3 files at r15, 1 of 3 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812)* status: 10 of 12 files reviewed, 14 unresolved discussions (waiting on @kungfucraig and @SanjayVas)



<!-- Sent from Reviewable.io -->

2023-02-08 22:36 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812)* status: 10 of 12 files reviewed, 14 unresolved discussions (waiting on @kungfucraig, @SanjayVas, and @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/event_group.proto` line 53 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NNgmQi4CpaR5-wuOhVU:-NNn9q3M5z_Indr6ii7y:b-a4jvs3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3ce569b7f8cd6802fece90a6aa48468a951b0db3/src/main/proto/wfa/measurement/reporting/v2alpha/event_group.proto#L53)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Your understanding is correct in that they're not stored in the CMMS. The are in some shared location that both the EDP and MC can access. Craig's statement is just to let integrators know that they'll need access to the template messages. That is to say that they cannot just use arbitrary types.
</blockquote></details>

Modified. Let me know if there is any info missing.


<!-- Sent from Reviewable.io -->

2023-02-09 01:48 UTC, SanjayVas approved these changes
> Reviewed 2 of 3 files at r17, 1 of 1 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812)* status: all files reviewed, 14 unresolved discussions (waiting on @kungfucraig, @riemanli, and @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/reporting_set.proto` line 27 at r16](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NNm-5PFCFAK1UMflrRJ:-NNnWAcb2Gl1_223O1H6:bcfgfqs) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0260a116571762990e677614bbbbbb8ef139e41b/src/main/proto/wfa/measurement/reporting/v2alpha/reporting_set.proto#L27)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

I wonder if further moving it into Composite would be better.
</blockquote></details>

I don't think we want to get too nested.


<!-- Sent from Reviewable.io -->

2023-02-09 17:23 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812)* status: 11 of 12 files reviewed, 13 unresolved discussions (waiting on @kungfucraig, @SanjayVas, and @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/reporting_set.proto` line 27 at r16](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NNm-5PFCFAK1UMflrRJ:-NNrC-46BlK2hYFy67uz:bb6un1j) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0260a116571762990e677614bbbbbb8ef139e41b/src/main/proto/wfa/measurement/reporting/v2alpha/reporting_set.proto#L27)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I don't think we want to get too nested.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-02-09 17:37 UTC, tristanvuong2021 approved these changes
> Reviewed 1 of 1 files at r20, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812)* status: all files reviewed, 13 unresolved discussions (waiting on @kungfucraig and @SanjayVas)



<!-- Sent from Reviewable.io -->

2023-02-09 22:52 UTC, stevenwarejones requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812)* status: all files reviewed, 4 unresolved discussions (waiting on @kungfucraig, @riemanli, and @SanjayVas)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/event_group.proto` line 29 at r20](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NNsN4dF8f51ndKDKS6m:-NNsN4dG7vJryAlxgVSa:bxj7avb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1ef0edce29e75b1282ffcc782f44d9fded61ec36/src/main/proto/wfa/measurement/reporting/v2alpha/event_group.proto#L29)):*
> ```protobuf
> // A grouping of events defined by a `DataProvider`. For example, a single
> // campaign or creative defined in a publisher's ad system.
> message EventGroup {
> ```

should all this be getting moved to cross-media-measurement-api? Wouldn't it be easier to maintain if these all live together?


<!-- Sent from Reviewable.io -->

2023-02-10 01:14 UTC, SanjayVas requested changes
Noticed a couple more things when cross-referencing with DB schema.

> Reviewed 1 of 1 files at r20, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-:-NNssGBS4LhKKT1th2nu:bjdpl76)* status: all files reviewed, 6 unresolved discussions (waiting on @kungfucraig and @riemanli)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/report.proto` line 80 at r20](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NNsqzGO2adqbeKL804M:-NNsqzGO2adqbeKL804N:b-guzi4z) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1ef0edce29e75b1282ffcc782f44d9fded61ec36/src/main/proto/wfa/measurement/reporting/v2alpha/report.proto#L80)):*
> ```protobuf
>   }
>   // The specification of metric calculation for a reporting set.
>   message ReportingMetricSpec {
> ```

Shouldn't this be `ReportingMetricCalculationSpec`?



_Code quote:_
```protobuf
ReportingMetricSpec
```
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/report.proto` line 110 at r20](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NNsrjNM3aLOqH7qoy_w:-NNsrjNM3aLOqH7qoy_x:bg6l37s) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1ef0edce29e75b1282ffcc782f44d9fded61ec36/src/main/proto/wfa/measurement/reporting/v2alpha/report.proto#L110)):*
> ```protobuf
> 
>   // The calculations defined for specific reporting sets.
>   ReportingMetricCalculation reporting_metric_calculation = 2
> ```

This type is only used here for this singular field. That means we can drop the extra message type and pull `reporting_metric_entries` into Report.



_Code quote:_
```protobuf
ReportingMetricCalculation
```


<!-- Sent from Reviewable.io -->

2023-02-10 15:25 UTC, kungfucraig reviewed
> Reviewed 1 of 7 files at r14.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812)* status: all files reviewed, 5 unresolved discussions (waiting on @riemanli and @SanjayVas)



<!-- Sent from Reviewable.io -->

2023-02-11 00:56 UTC, SanjayVas reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812)* status: all files reviewed, 5 unresolved discussions (waiting on @kungfucraig, @riemanli, and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/event_group.proto` line 29 at r20](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NNsN4dF8f51ndKDKS6m:-NNxy-aYD9ig4N-V7wl1:bz6qbgm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1ef0edce29e75b1282ffcc782f44d9fded61ec36/src/main/proto/wfa/measurement/reporting/v2alpha/event_group.proto#L29)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

should all this be getting moved to cross-media-measurement-api? Wouldn't it be easier to maintain if these all live together?
</blockquote></details>

That repo is for a different API, specifically the CMMS public API. This new revision of the reporting API does not require any changes to that API.

In a monorepo world, that repo would be merged into this one.


<!-- Sent from Reviewable.io -->

2023-02-13 20:26 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812)* status: all files reviewed, 5 unresolved discussions (waiting on @kungfucraig, @SanjayVas, and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/report.proto` line 80 at r20](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NNsqzGO2adqbeKL804M:-NOBRLkX4iGAr07SoOC2:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1ef0edce29e75b1282ffcc782f44d9fded61ec36/src/main/proto/wfa/measurement/reporting/v2alpha/report.proto#L80)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Shouldn't this be `ReportingMetricCalculationSpec`?
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/report.proto` line 110 at r20](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NNsrjNM3aLOqH7qoy_w:-NOBOiCQEFEF86CdqGY2:b-xu0uci) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1ef0edce29e75b1282ffcc782f44d9fded61ec36/src/main/proto/wfa/measurement/reporting/v2alpha/report.proto#L110)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This type is only used here for this singular field. That means we can drop the extra message type and pull `reporting_metric_entries` into Report.
</blockquote></details>

Thanks for the suggestion. Done.


<!-- Sent from Reviewable.io -->

2023-02-14 00:18 UTC, SanjayVas approved these changes
> Reviewed 1 of 1 files at r21, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812)* status: all files reviewed, 4 unresolved discussions (waiting on @kungfucraig, @riemanli, and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/report.proto` line 105 at r21](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NOCHI9GCutEBu9N9Vt0:-NOCHI9GCutEBu9N9Vt1:bwqft9f) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a6332fbc88cc582d2dc0635e31d1b880f0275ad0/src/main/proto/wfa/measurement/reporting/v2alpha/report.proto#L105)):*
> ```protobuf
>   // The calculations defined for specific reporting sets.
>   repeated ReportingMetricEntry reporting_metric_entries = 2
>       [(google.api.field_behavior) = REQUIRED];
> ```

nit: also IMMUTABLE


<!-- Sent from Reviewable.io -->

2023-02-16 19:17 UTC, riemanli reviewed
Hi reviewers, here are some new changes since last review:
* Add a build file.
* Add idempotency key and create time for metric and report.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-:-NOQdvax9cjG9dVZcQo6:b-1b1rq)* status: 8 of 13 files reviewed, 3 unresolved discussions (waiting on @kungfucraig, @SanjayVas, @stevenwarejones, and @tristanvuong2021)



<!-- Sent from Reviewable.io -->

2023-02-17 19:08 UTC, SanjayVas requested changes
> Reviewed 5 of 5 files at r23, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812)* status: all files reviewed, 5 unresolved discussions (waiting on @kungfucraig, @riemanli, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metrics_service.proto` line 159 at r23](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NOVjzIY11onnol3OqFM:-NOVjzIY11onnol3OqFN:b6z3lr3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a848ed9016410e62871a10be928611fcdacbefd6/src/main/proto/wfa/measurement/reporting/v2alpha/metrics_service.proto#L159)):*
> ```protobuf
>   // A unique identifier for this request. Restricted to 36 ASCII characters.
>   // A random UUID is recommended.
>   string metric_id = 3 [(google.api.field_behavior) = REQUIRED];
> ```

Follow [AIP-155](https://google.aip.dev/155) for this. In particular:
1. Name the field `request_id`
2. Do not mark the field as REQUIRED. It in fact should be optional. This means we cannot rely on it being set and need to do something reasonable if it's not specified if our implementation requires some ID (e.g. generating our own UUID)
3. Document that the request will only be idempotent if `request_id` is specified.



_Code quote:_
```protobuf
metric_id
```
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/reports_service.proto` line 117 at r23](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NOVlnHO3SSlRVCzEQZW:-NOVlnHO3SSlRVCzEQZX:bjj4523) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a848ed9016410e62871a10be928611fcdacbefd6/src/main/proto/wfa/measurement/reporting/v2alpha/reports_service.proto#L117)):*
> ```protobuf
>   // A unique identifier for this request. Restricted to 36 ASCII characters.
>   // A random UUID is recommended.
>   string report_id = 3 [(google.api.field_behavior) = REQUIRED];
> ```

Same note here re: https://google.aip.dev/155


<!-- Sent from Reviewable.io -->

2023-02-17 19:40 UTC, stevenwarejones reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812)* status: all files reviewed, 4 unresolved discussions (waiting on @kungfucraig, @riemanli, and @tristanvuong2021)



<!-- Sent from Reviewable.io -->

2023-02-17 19:52 UTC, riemanli commented
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metrics_service.proto` line 159 at r23](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NOVjzIY11onnol3OqFM:-NOVuyYE2Va9GX-Woj-W:bic6fx0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a848ed9016410e62871a10be928611fcdacbefd6/src/main/proto/wfa/measurement/reporting/v2alpha/metrics_service.proto#L159)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Follow [AIP-155](https://google.aip.dev/155) for this. In particular:
1. Name the field `request_id`
2. Do not mark the field as REQUIRED. It in fact should be optional. This means we cannot rely on it being set and need to do something reasonable if it's not specified if our implementation requires some ID (e.g. generating our own UUID)
3. Document that the request will only be idempotent if `request_id` is specified.
</blockquote></details>

I saw that AIP too, but we need the idempotency key for creating unique measurement IDs downstream. Maybe we should put the idempotency key in `Metric` instead of the request message if we have to make it required?


<!-- Sent from Reviewable.io -->

2023-02-17 22:01 UTC, SanjayVas requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812)* status: all files reviewed, 4 unresolved discussions (waiting on @kungfucraig, @riemanli, and @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metrics_service.proto` line 159 at r23](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NOVjzIY11onnol3OqFM:-NOWOG4f9Js9ml0g-ZqE:bpm4hev) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a848ed9016410e62871a10be928611fcdacbefd6/src/main/proto/wfa/measurement/reporting/v2alpha/metrics_service.proto#L159)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

I saw that AIP too, but we need the idempotency key for creating unique measurement IDs downstream. Maybe we should put the idempotency key in `Metric` instead of the request message if we have to make it required?
</blockquote></details>

No, we should follow the AIP and just generate an ID internally if one isn't specified.


<!-- Sent from Reviewable.io -->

2023-02-17 22:04 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812)* status: all files reviewed, 4 unresolved discussions (waiting on @kungfucraig, @SanjayVas, and @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metrics_service.proto` line 159 at r23](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NOVjzIY11onnol3OqFM:-NOWO_OUA2WGM6PCUCFt:bxpebhb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a848ed9016410e62871a10be928611fcdacbefd6/src/main/proto/wfa/measurement/reporting/v2alpha/metrics_service.proto#L159)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

No, we should follow the AIP and just generate an ID internally if one isn't specified.
</blockquote></details>

I see. Will the generated ID then fill in `request_id` for the user to see when they try to the metric?


<!-- Sent from Reviewable.io -->

2023-02-17 22:41 UTC, SanjayVas requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812)* status: all files reviewed, 4 unresolved discussions (waiting on @kungfucraig, @riemanli, and @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metrics_service.proto` line 159 at r23](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NOVjzIY11onnol3OqFM:-NOWXCMr07st_AFgvJKX:b-cmqpl8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a848ed9016410e62871a10be928611fcdacbefd6/src/main/proto/wfa/measurement/reporting/v2alpha/metrics_service.proto#L159)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

I see. Will the generated ID then fill in `request_id` for the user to see when they try to the metric?
</blockquote></details>

Do they need to be able to see it?

This is just a request message field, so it's implicitly INPUT_ONLY. If the user needs to see the ID, we can add an OUTPUT_ONLY `create_request_id` field on the resource message (Metric in this case), but I don't think we have a use case for it.


<!-- Sent from Reviewable.io -->

2023-02-18 01:17 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812)* status: 11 of 13 files reviewed, 4 unresolved discussions (waiting on @kungfucraig, @SanjayVas, and @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metrics_service.proto` line 159 at r23](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NOVjzIY11onnol3OqFM:-NOX44nD5jJMdEZo-BJs:bsapdxl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a848ed9016410e62871a10be928611fcdacbefd6/src/main/proto/wfa/measurement/reporting/v2alpha/metrics_service.proto#L159)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Do they need to be able to see it?

This is just a request message field, so it's implicitly INPUT_ONLY. If the user needs to see the ID, we can add an OUTPUT_ONLY `create_request_id` field on the resource message (Metric in this case), but I don't think we have a use case for it.
</blockquote></details>

Good point. No, they don't. 
Modified as suggested.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/reports_service.proto` line 117 at r23](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NOVlnHO3SSlRVCzEQZW:-NOX5D3RD5BPA0hUqjjx:b-cszsw0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a848ed9016410e62871a10be928611fcdacbefd6/src/main/proto/wfa/measurement/reporting/v2alpha/reports_service.proto#L117)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Same note here re: https://google.aip.dev/155
</blockquote></details>

Modified.


<!-- Sent from Reviewable.io -->

2023-02-21 19:42 UTC, SanjayVas approved these changes
> Reviewed 2 of 2 files at r24, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812)* status: all files reviewed, 2 unresolved discussions (waiting on @kungfucraig and @tristanvuong2021)



<!-- Sent from Reviewable.io -->

2023-02-24 17:13 UTC, kungfucraig reviewed
> Reviewed 3 of 5 files at r23, 2 of 2 files at r24, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812)* status: all files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)



<!-- Sent from Reviewable.io -->

2023-03-02 17:01 UTC, riemanli commented
@stevenwarejones Let me know if you have any questions about the PR. Thanks!

2023-03-02 19:46 UTC, kungfucraig approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones and @tristanvuong2021)



<!-- Sent from Reviewable.io -->

2023-03-13 19:16 UTC, stevenwarejones requested changes
> Reviewed 1 of 8 files at r10, 1 of 3 files at r12, 1 of 7 files at r14, 2 of 3 files at r15, 1 of 3 files at r17, 1 of 1 files at r18, 1 of 1 files at r20, 3 of 5 files at r23, 2 of 2 files at r24, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812)* status: all files reviewed, 8 unresolved discussions (waiting on @riemanli and @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/event_group.proto` line 47 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NNgm6DX7s3Oh6DKJZS7:-NPORWY-BIOM-Voey6DH:b-p0vrxo) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3ce569b7f8cd6802fece90a6aa48468a951b0db3/src/main/proto/wfa/measurement/reporting/v2alpha/event_group.proto#L47)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

It is provided on event group creation and would generated on the data provider side.
</blockquote></details>

its set by the edp as some external reference id they might independently share with the MC out-of-band as I understand it -- https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f28591cdea52a763deb01950717521c305ad688c/docs/code-style.md#L40
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto` line 36 at r24](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NQRJPr78tQJ5u4gvAw2:-NQRJPr78tQJ5u4gvAw3:bfzlmb0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ab508023c21b77b48562dbd19b410d22b3ca334b/src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto#L36)):*
> ```protobuf
>     // Maximum frequency cut-off value in the frequency histogram. Counts with
>     // frequency higher than `max_frequency` will be aggregated together.
>     int32 maximum_frequency_per_user = 1
> ```

I'm thinking this field should just be handled by the reporting server, itself, like the DP params.



_Code quote:_
```protobuf
    // frequency higher than `max_frequency` will be aggregated together.
    int32 maximum_frequency_per_user = 1
```
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto` line 51 at r24](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NQRJYY6-ODrO5x7jnYt:-NQRJYY6-ODrO5x7jnYu:b-7ropln) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ab508023c21b77b48562dbd19b410d22b3ca334b/src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto#L51)):*
> ```protobuf
>     // recommended value for maximum_frequency_per_user = 60 for the case with
>     // over 1M audience size.
>     int32 maximum_frequency_per_user = 1
> ```

ditto
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto` line 62 at r24](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NQRJbkvDzIyra8v0hQ-:-NQRJbkvDzIyra8v0hQ0:b-7ropln) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ab508023c21b77b48562dbd19b410d22b3ca334b/src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto#L62)):*
> ```protobuf
>     // duration of all the impressions of a user = 4000 sec for the case with
>     // over 1M audience size. Enforced on a per EDP basis.
>     int32 maximum_watch_duration_per_user = 1
> ```

ditto
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto` line 109 at r24](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NQRKAix2J2aABzqP1ku:-NQRKAix2J2aABzqP1kv:b-7g8col) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ab508023c21b77b48562dbd19b410d22b3ca334b/src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto#L109)):*
> ```protobuf
>       string label = 1;
>       // The value of the bin.
>       DoubleResult value = 2;
> ```

I'd prefer `BinResult`
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto` line 122 at r24](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NQRJszh4PpOZMIKJc-m:-NQRJszh4PpOZMIKJc-n:b-63ydeg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ab508023c21b77b48562dbd19b410d22b3ca334b/src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto#L122)):*
> ```protobuf
>     HistogramResult frequency_histogram = 4;
>     // Impression counts.
>     IntegerResult impression_count = 5;
> ```

I'd prefer to more specifically type this.... eg `ImpressionResult` *and* `ReachResult` vs `IntegerResult` 
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto` line 163 at r24](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NQRKy4cE2e_qLBGkJ4b:-NQRKy4cE2e_qLBGkJ4c:bslp9l7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ab508023c21b77b48562dbd19b410d22b3ca334b/src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto#L163)):*
> ```protobuf
>   // Additional filters that will be combined with AND boolean operation and
>   // applied to the reporting set. If unspecified, evaluates to `true`
>   repeated string filters = 5 [(google.api.field_behavior) = IMMUTABLE];
> ```

what was the thinking behind making this repeated vs a single filter?
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/report.proto` line 163 at r24](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NQRNw46EVsuzcwz7szV:-NQRNw46EVsuzcwz7szW:b-4s0m34) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ab508023c21b77b48562dbd19b410d22b3ca334b/src/main/proto/wfa/measurement/reporting/v2alpha/report.proto#L163)):*
> ```protobuf
>       // report to the end of this time interval. Otherwise, the result is
>       // calculated cumulatively over this time interval.
>       TimeInterval time_interval = 2;
> ```

is this field on the `ResultsAttribute` level or should it be on the `MetricCalculationResult` level since that's where the cumulative field is?
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/time_interval.proto` line 60 at r24](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NQROXH_7Ppj1FZo_Z3c:-NQROXH_7Ppj1FZo_Z3d:b-8pfpbo) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ab508023c21b77b48562dbd19b410d22b3ca334b/src/main/proto/wfa/measurement/reporting/v2alpha/time_interval.proto#L60)):*
> ```protobuf
> 
>   // Number of intervals.
>   int32 interval_count = 3 [(google.api.field_behavior) = REQUIRED];
> ```

how does this work for a campaign where the end date is in the future unknown? Should interval_count be specified here?


<!-- Sent from Reviewable.io -->

2023-03-13 23:05 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812)* status: all files reviewed, 8 unresolved discussions (waiting on @SanjayVas, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto` line 36 at r24](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NQRJPr78tQJ5u4gvAw2:-NQRlDjqC3Mtxh5hFowJ:b-uon8xy) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ab508023c21b77b48562dbd19b410d22b3ca334b/src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto#L36)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

I'm thinking this field should just be handled by the reporting server, itself, like the DP params.
</blockquote></details>

Thanks for sharing the thought. The idea of having this parameter is to let the user choose their own max number of frequency in the result. If the user wants to see a reach-frequency histogram with max frequency up to K+ reach, they can set it with this parameter. 
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto` line 51 at r24](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NQRJYY6-ODrO5x7jnYt:-NQRmQ9S4cvytWcilnAA:b9pw31j) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ab508023c21b77b48562dbd19b410d22b3ca334b/src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto#L51)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Unlike the one in FrequencyHistogram, this one is mostly for DP. Currently we don't have the ability to accommodate campaigns with small reaches using fixed DP parameters including this one. I would suggest to keep it user-definable in case the user wants to run for small campaign, and once the adaptive strategy Jiayu is working on is ready for implementation, we can remove it from API.
Let me know if that makes to you!
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto` line 62 at r24](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NQRJbkvDzIyra8v0hQ-:-NQRoamjEFsL--3cXUex:b3w7hq0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ab508023c21b77b48562dbd19b410d22b3ca334b/src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto#L62)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

ditto
</blockquote></details>

Please see the comment in the other thread.



_Code quote:_
```protobuf
ImpressionCountParams
```
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto` line 163 at r24](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NQRKy4cE2e_qLBGkJ4b:-NQRvB373865OyvTkBBH:b-z5h1bf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ab508023c21b77b48562dbd19b410d22b3ca334b/src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto#L163)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

what was the thinking behind making this repeated vs a single filter?
</blockquote></details>

This field serves two purposes: 
1. Providing the user a way to add more filters on top of the metric when they use the metrics service. 
2. Store the fan-out grouping filters in `Report` when one uses the reports service. 

The main reason the field is repeated is coming from (2). The fan-out grouping filters are stored separately in `Metrics` and then in `repeated string grouping_predicates` in `ResultAttribute`s. This enables the user to group their metric results by different types of groupings.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/report.proto` line 163 at r24](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NQRNw46EVsuzcwz7szV:-NQSA_-YD0Vsz9TFmNMl:b-28824q) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ab508023c21b77b48562dbd19b410d22b3ca334b/src/main/proto/wfa/measurement/reporting/v2alpha/report.proto#L163)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

is this field on the `ResultsAttribute` level or should it be on the `MetricCalculationResult` level since that's where the cumulative field is?
</blockquote></details>

`MetricCalculationResult` contains metrics across different time intervals, different metric types, and different grouping predicates. One `ResultsAttribute` is one element from the cartesian product of them. You can think of that one `ResultsAttribute` corresponds to one `Metric`.

As for `cumulative`, it's independent of `Metric`, so it's more appropriate to have it at the current level.

Hope that answers your question!
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/time_interval.proto` line 60 at r24](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NQROXH_7Ppj1FZo_Z3c:-NQSBTNN-M1FIndqORVa:bnlwv49) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ab508023c21b77b48562dbd19b410d22b3ca334b/src/main/proto/wfa/measurement/reporting/v2alpha/time_interval.proto#L60)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

how does this work for a campaign where the end date is in the future unknown? Should interval_count be specified here?
</blockquote></details>

That's a great question! I am not sure how the kingdom handles a future end time. @SanjayVas, @tristanvuong2021 do you know about this?


<!-- Sent from Reviewable.io -->

2023-03-13 23:38 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812)* status: all files reviewed, 8 unresolved discussions (waiting on @kungfucraig, @SanjayVas, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto` line 122 at r24](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NQRJszh4PpOZMIKJc-m:-NQSH1DjCn7fGVPKG13a:bv6du9q) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ab508023c21b77b48562dbd19b410d22b3ca334b/src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto#L122)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

I'd prefer to more specifically type this.... eg `ImpressionResult` *and* `ReachResult` vs `IntegerResult` 
</blockquote></details>

Thanks for the suggestion. I can see the advantage of being specifically. 

The original idea of using `IntegerResult` and `DoubleResult` is to be generic. Instead of having different types of metric results, we can divide the scalar results into integers and doubles, and histogram results can be extended from the scalar result by having multiple of them.

I am ok with both designs. @kungfucraig, @SanjayVas, and @tristanvuong2021 do you have any thought about this?


<!-- Sent from Reviewable.io -->

2023-03-14 15:02 UTC, kungfucraig approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812)* status: all files reviewed, 8 unresolved discussions (waiting on @riemanli, @SanjayVas, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto` line 122 at r24](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NQRJszh4PpOZMIKJc-m:-NQVct7BELD-fBZRpWy7:bzdl7lt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ab508023c21b77b48562dbd19b410d22b3ca334b/src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto#L122)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Thanks for the suggestion. I can see the advantage of being specifically. 

The original idea of using `IntegerResult` and `DoubleResult` is to be generic. Instead of having different types of metric results, we can divide the scalar results into integers and doubles, and histogram results can be extended from the scalar result by having multiple of them.

I am ok with both designs. @kungfucraig, @SanjayVas, and @tristanvuong2021 do you have any thought about this?
</blockquote></details>

It doesn't change much and allows us to make result specific changes in the future. I'm not convinced we'll need that flexibility. I'm fine either way.


<!-- Sent from Reviewable.io -->

2023-03-14 20:08 UTC, SanjayVas approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812)* status: all files reviewed, 7 unresolved discussions (waiting on @stevenwarejones and @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto` line 109 at r24](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NQRKAix2J2aABzqP1ku:-NQWfyd8EQKGYo3g1unC:by8xqmw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ab508023c21b77b48562dbd19b410d22b3ca334b/src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto#L109)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

I'd prefer `BinResult`
</blockquote></details>

See the comment below about error bar representation.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto` line 122 at r24](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NQRJszh4PpOZMIKJc-m:-NQWb_VP-27oL_pm0S6T:b-rx3cmj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ab508023c21b77b48562dbd19b410d22b3ca334b/src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto#L122)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

It doesn't change much and allows us to make result specific changes in the future. I'm not convinced we'll need that flexibility. I'm fine either way.
</blockquote></details>

For background, the reason these have wrapper messages is to support the future addition of error bar fields. That is to say that the intent wasn't to add type-specificity. My understanding is that how error bars are represented depends on the data type rather than the metric type. The reason the error bar fields aren't in this PR is that their exactly representation is still TBD.

The idea was that we could share error bar representations across wherever that data type is used. Note that this is all predicated on the above assumption holding: that the error bar representation depend purely on the data type and not on the metric type. This means that e.g. histogram bin values are always doubles, and that we'd represent the error bars for each bin value rather than some other holistic representation either for histograms in general or for frequency metric histograms specifically.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/time_interval.proto` line 60 at r24](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NQROXH_7Ppj1FZo_Z3c:-NQWhl_aE9Q_re4dLCbL:b1j3vkg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ab508023c21b77b48562dbd19b410d22b3ca334b/src/main/proto/wfa/measurement/reporting/v2alpha/time_interval.proto#L60)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

That's a great question! I am not sure how the kingdom handles a future end time. @SanjayVas, @tristanvuong2021 do you know about this?
</blockquote></details>

This API and the Kingdom API only support measurements for events in the past (i.e. where the data is already available). Features such as scheduling can be done in another layer that creates new Reports/Metrics once the data should be available.


<!-- Sent from Reviewable.io -->

2023-03-14 21:51 UTC, stevenwarejones requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812)* status: all files reviewed, 6 unresolved discussions (waiting on @riemanli and @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto` line 51 at r24](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NQRJYY6-ODrO5x7jnYt:-NQX3lOHCJccP3xPYOnR:bd220y8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ab508023c21b77b48562dbd19b410d22b3ca334b/src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto#L51)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Unlike the one in FrequencyHistogram, this one is mostly for DP. Currently we don't have the ability to accommodate campaigns with small reaches using fixed DP parameters including this one. I would suggest to keep it user-definable in case the user wants to run for small campaign, and once the adaptive strategy Jiayu is working on is ready for implementation, we can remove it from API.
Let me know if that makes to you!
</blockquote></details>

we discussed this today. I think we should either include all the DP params here or not include them at all.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto` line 122 at r24](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NQRJszh4PpOZMIKJc-m:-NQX4FO57c_142x7NqBH:bbffdkk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ab508023c21b77b48562dbd19b410d22b3ca334b/src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto#L122)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

For background, the reason these have wrapper messages is to support the future addition of error bar fields. That is to say that the intent wasn't to add type-specificity. My understanding is that how error bars are represented depends on the data type rather than the metric type. The reason the error bar fields aren't in this PR is that their exactly representation is still TBD.

The idea was that we could share error bar representations across wherever that data type is used. Note that this is all predicated on the above assumption holding: that the error bar representation depend purely on the data type and not on the metric type. This means that e.g. histogram bin values are always doubles, and that we'd represent the error bars for each bin value rather than some other holistic representation either for histograms in general or for frequency metric histograms specifically.
</blockquote></details>

i think we could still share a future ErrorBarResult field inside `ImpressionResult` and `ReachResult` etc. `IntegerResult` feels like a poor name to me too tightly tied to a type. It is unlikely, but ImpressionResult gives us more flexibility in the future in case for some reason we want to deprecate the integer field and expose some other type instead.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/report.proto` line 163 at r24](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NQRNw46EVsuzcwz7szV:-NQX56Pm2VVpt-u85god:b-o7pg5k) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ab508023c21b77b48562dbd19b410d22b3ca334b/src/main/proto/wfa/measurement/reporting/v2alpha/report.proto#L163)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

`MetricCalculationResult` contains metrics across different time intervals, different metric types, and different grouping predicates. One `ResultsAttribute` is one element from the cartesian product of them. You can think of that one `ResultsAttribute` corresponds to one `Metric`.

As for `cumulative`, it's independent of `Metric`, so it's more appropriate to have it at the current level.

Hope that answers your question!
</blockquote></details>

in what use case would `MetricCalculationResult` contain metrics from different time_intervals where it couldn't be handled by cumulative?


<!-- Sent from Reviewable.io -->

2023-03-14 22:13 UTC, SanjayVas approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812)* status: all files reviewed, 6 unresolved discussions (waiting on @riemanli, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/time_interval.proto` line 60 at r24](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NQROXH_7Ppj1FZo_Z3c:-NQWvUbYCWGkLhobhb0V:b-qk3iw7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ab508023c21b77b48562dbd19b410d22b3ca334b/src/main/proto/wfa/measurement/reporting/v2alpha/time_interval.proto#L60)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This API and the Kingdom API only support measurements for events in the past (i.e. where the data is already available). Features such as scheduling can be done in another layer that creates new Reports/Metrics once the data should be available.
</blockquote></details>

This was discussed on another thread, but to clarify what is meant by the above statement:
* If an EDP sees a Requisition with a TimeInterval for which it does not and should not have data available, it should refuse the Requisition with ` SPECIFICATION_INVALID`
* If an EDP sees a Requisition with a TimeInterval for which it does not but should have data available, it should refuse the Requisition with ` UNFULFILLABLE`
* The EDP should **not** just hold off on fulfilling the Requisition under the assumption that the data will become available eventually.

Whether the EDP *should* have the data available depends on the SLAs/contract for the market.


<!-- Sent from Reviewable.io -->

2023-03-14 23:41 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812)* status: all files reviewed, 6 unresolved discussions (waiting on @stevenwarejones and @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto` line 51 at r24](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NQRJYY6-ODrO5x7jnYt:-NQXE6g-13ojTHtibR_6:bdjoj5u) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ab508023c21b77b48562dbd19b410d22b3ca334b/src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto#L51)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

we discussed this today. I think we should either include all the DP params here or not include them at all.
</blockquote></details>

As we discussed offline, we will add all DP params to the API. The default values will be stored in a proto config and will be read into the metrics service.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto` line 122 at r24](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NQRJszh4PpOZMIKJc-m:-NQXTXWE0laqpGtRy2VB:b-ur8n7l) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ab508023c21b77b48562dbd19b410d22b3ca334b/src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto#L122)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

i think we could still share a future ErrorBarResult field inside `ImpressionResult` and `ReachResult` etc. `IntegerResult` feels like a poor name to me too tightly tied to a type. It is unlikely, but ImpressionResult gives us more flexibility in the future in case for some reason we want to deprecate the integer field and expose some other type instead.
</blockquote></details>

Offline discussion: Considering that there might be some metric type specific outputs in the future and that the suggested change can serve the same purpose for adding error bar, I will make the change as suggested.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/report.proto` line 163 at r24](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NQRNw46EVsuzcwz7szV:-NQXACl27N9IpsqBtufE:b-rfluy9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ab508023c21b77b48562dbd19b410d22b3ca334b/src/main/proto/wfa/measurement/reporting/v2alpha/report.proto#L163)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

in what use case would `MetricCalculationResult` contain metrics from different time_intervals where it couldn't be handled by cumulative?
</blockquote></details>

`Metric` is a bit different in v2 than the one in v1. `Metric` in v2 contains **single time interval**. For example, if a user defines the report with the `metricCalculationSpec` and the `time` like below, the reports service will generate 6 metrics --- 3 reach metrics for 03/01->03/01, 03/01->03/02, and 03/01->03/03 respectively and the other 3 watch duration metrics for 03/01->03/01, 03/01->03/02, and 03/01->03/03 respectively. 

For a `MetricCalculationResult`, it will then contain 6 `ResultAttribute`s, one for each metric from above.

```textproto
time {
  time_intervals {
    time_intervals {
      start_time: "2021-03-01T00:00:00.01Z"
      end_time: "2021-03-01T23:59:59.99Z"
    }
    time_intervals {
      start_time: "2021-03-02T00:00:00.01Z"
      end_time: "2021-03-02T23:59:59.99Z"
    }
    time_intervals {
      start_time: "2021-03-03T00:00:00.01Z"
      end_time: "2021-03-03T23:59:59.99Z"
    }
  }
}

metric_calculation_specs {
  display_name: "incremental_metrics"
  metric_spec {
    type {
      reach {}
    }
  }
  metric_spec {
    type {
      watch_duration {}
    }
  }
  cumulative: true
}
```
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/time_interval.proto` line 60 at r24](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NQROXH_7Ppj1FZo_Z3c:-NQWwp0D7aL5ruGVIrE9:b-9t03tw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ab508023c21b77b48562dbd19b410d22b3ca334b/src/main/proto/wfa/measurement/reporting/v2alpha/time_interval.proto#L60)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This was discussed on another thread, but to clarify what is meant by the above statement:
* If an EDP sees a Requisition with a TimeInterval for which it does not and should not have data available, it should refuse the Requisition with ` SPECIFICATION_INVALID`
* If an EDP sees a Requisition with a TimeInterval for which it does not but should have data available, it should refuse the Requisition with ` UNFULFILLABLE`
* The EDP should **not** just hold off on fulfilling the Requisition under the assumption that the data will become available eventually.

Whether the EDP *should* have the data available depends on the SLAs/contract for the market.
</blockquote></details>

If I understand correctly, this means the reporting server doesn't need to do anything when a future time is specified. The error will be captured by the EDP and will be shown when the corresponding kingdom measurement comes back.


<!-- Sent from Reviewable.io -->

2023-03-15 16:59 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812)* status: 12 of 13 files reviewed, 6 unresolved discussions (waiting on @kungfucraig, @SanjayVas, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto` line 51 at r24](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NQRJYY6-ODrO5x7jnYt:-NQaCWqg8hgzO70qPouC:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ab508023c21b77b48562dbd19b410d22b3ca334b/src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto#L51)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

As we discussed offline, we will add all DP params to the API. The default values will be stored in a proto config and will be read into the metrics service.
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto` line 109 at r24](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NQRKAix2J2aABzqP1ku:-NQa4_Wg1g4hKyFTpY58:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ab508023c21b77b48562dbd19b410d22b3ca334b/src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto#L109)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

See the comment below about error bar representation.
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto` line 122 at r24](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NQRJszh4PpOZMIKJc-m:-NQa5WtL1xWK39uLIod-:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ab508023c21b77b48562dbd19b410d22b3ca334b/src/main/proto/wfa/measurement/reporting/v2alpha/metric.proto#L122)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Offline discussion: Considering that there might be some metric type specific outputs in the future and that the suggested change can serve the same purpose for adding error bar, I will make the change as suggested.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-03-15 18:17 UTC, SanjayVas approved these changes
> Reviewed 1 of 1 files at r25, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812)* status: all files reviewed, 6 unresolved discussions (waiting on @kungfucraig, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/time_interval.proto` line 60 at r24](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NQROXH_7Ppj1FZo_Z3c:-NQaTepk-4T0vPEwxhIN:b-dbpbqm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ab508023c21b77b48562dbd19b410d22b3ca334b/src/main/proto/wfa/measurement/reporting/v2alpha/time_interval.proto#L60)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

If I understand correctly, this means the reporting server doesn't need to do anything when a future time is specified. The error will be captured by the EDP and will be shown when the corresponding kingdom measurement comes back.
</blockquote></details>

The fact that this field is listed as REQUIRED in this API is fine. Like all field behaviors, we should make sure this is enforced (e.g. throw an `INVALID_ARGUMENT` error if it's not specified in a request).


<!-- Sent from Reviewable.io -->

2023-03-15 19:49 UTC, stevenwarejones approved these changes
> Reviewed 1 of 1 files at r25, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kungfucraig and @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/reporting/v2alpha/report.proto` line 163 at r24](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812#-NQRNw46EVsuzcwz7szV:-NQaoQvA93ZQ5sodyBv7:by4bx31) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ab508023c21b77b48562dbd19b410d22b3ca334b/src/main/proto/wfa/measurement/reporting/v2alpha/report.proto#L163)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

`Metric` is a bit different in v2 than the one in v1. `Metric` in v2 contains **single time interval**. For example, if a user defines the report with the `metricCalculationSpec` and the `time` like below, the reports service will generate 6 metrics --- 3 reach metrics for 03/01->03/01, 03/01->03/02, and 03/01->03/03 respectively and the other 3 watch duration metrics for 03/01->03/01, 03/01->03/02, and 03/01->03/03 respectively. 

For a `MetricCalculationResult`, it will then contain 6 `ResultAttribute`s, one for each metric from above.

```textproto
time {
  time_intervals {
    time_intervals {
      start_time: "2021-03-01T00:00:00.01Z"
      end_time: "2021-03-01T23:59:59.99Z"
    }
    time_intervals {
      start_time: "2021-03-02T00:00:00.01Z"
      end_time: "2021-03-02T23:59:59.99Z"
    }
    time_intervals {
      start_time: "2021-03-03T00:00:00.01Z"
      end_time: "2021-03-03T23:59:59.99Z"
    }
  }
}

metric_calculation_specs {
  display_name: "incremental_metrics"
  metric_spec {
    type {
      reach {}
    }
  }
  metric_spec {
    type {
      watch_duration {}
    }
  }
  cumulative: true
}
```


</blockquote></details>

thx for the clarification


<!-- Sent from Reviewable.io -->

2023-03-15 21:50 UTC, riemanli reviewed
> Reviewed 1 of 8 files at r10, 1 of 3 files at r12, 1 of 7 files at r14, 2 of 3 files at r15, 1 of 3 files at r17, 1 of 1 files at r18, 1 of 1 files at r20, 2 of 5 files at r23, 2 of 2 files at r24, 1 of 1 files at r25, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/812)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @kungfucraig and @tristanvuong2021)



<!-- Sent from Reviewable.io -->

2023-03-15 21:52 UTC, merged