Correct noised reach calculation in fulfillDirectReachAndFrequencyMeasurement in EDP simulator
world-federation-of-advertisers/cross-media-measurement pull request #814
Opened 2023-01-17 21:18 UTC by iverson52000

This PR should fix https://github.com/world-federation-of-advertisers/cross-media-measurement/issues/808

2023-01-18 00:33 UTC, riemanli approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/814)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @iverson52000, @kungfucraig, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 835 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/814#-NM1HeDT7SRW52OthCmb:-NM1HeDT7SRW52OthCmc:barkul0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8ed87de92b35aadd34fe2f7af0c0d38f12b0d4fe/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L835)):*
> ```Kotlin
>      * @return Pair of noised reach value and frequency map
>      */
>     fun addPublisherNoise(
> ```

I wonder if it's necessary to have this function public. 


<!-- Sent from Reviewable.io -->

2023-01-18 20:41 UTC, iverson52000 commented
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 835 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/814#-NM1HeDT7SRW52OthCmb:-NM5bLnG2eHBInJofNmv:b-53c61q) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8ed87de92b35aadd34fe2f7af0c0d38f12b0d4fe/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L835)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

I wonder if it's necessary to have this function public. 
</blockquote></details>

I think so since it needs to be unit tested?


<!-- Sent from Reviewable.io -->

2023-01-19 17:59 UTC, SanjayVas requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/814)* status: all files reviewed, 1 unresolved discussion (waiting on @riemanli and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 835 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/814#-NM1HeDT7SRW52OthCmb:-NMAAcvL8WEMjTvrw3Te:b-g903n2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8ed87de92b35aadd34fe2f7af0c0d38f12b0d4fe/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L835)):*
> I think so since it needs to be unit tested?

This is backwards. Functions don't get exposed so they can be tested. Testing should be done against the public API.


<!-- Sent from Reviewable.io -->

2023-01-23 16:39 UTC, SanjayVas requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/814)* status: all files reviewed, 1 unresolved discussion (waiting on @riemanli)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 835 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/814#-NM1HeDT7SRW52OthCmb:-NMUQjW3AlLZ1XdHxN_6:bujee6w) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8ed87de92b35aadd34fe2f7af0c0d38f12b0d4fe/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L835)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

I would argue this belongs in a public function but not in this class. It should be accessible by anyone setting up their own EDP. What about offering this as an interface of something like a `Noiser` and add this as an initial impl.
</blockquote></details>

Addressing these as two separate concerns:
1. It is certainly a valid strategy to split functionality out into different components which could then be tested independently. The consideration is whether this functionality should be considered an [implementation detail](https://testing.googleblog.com/2015/01/testing-on-toilet-prefer-testing-public.html) of the EDP simulator. This may indeed be something that we want more expansive testing on, which warrants splitting it out. This would mean that EDP simulator test could use a test double (e.g. mock) for this if desired.
2. We technically do not yet offer an official EDP library. Code from this repo hasn't been designed to be depended on externally[^*]. The EDP libraries we do offer are in separate repositories (e.g. consent-signaling-client, any-sketch). If we want to provide functionality from this repo as a separate library, we should have a separate design covering that which identifies everything that should be included.

[^*]: Aside from gRPC APIs, namely the Reporting API.


<!-- Sent from Reviewable.io -->

2023-01-23 20:50 UTC, kungfucraig reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/814)* status: all files reviewed, 1 unresolved discussion (waiting on @riemanli and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 835 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/814#-NM1HeDT7SRW52OthCmb:-NMVNDdjAiFzDXaoPELm:bz44j0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8ed87de92b35aadd34fe2f7af0c0d38f12b0d4fe/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L835)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Addressing these as two separate concerns:
1. It is certainly a valid strategy to split functionality out into different components which could then be tested independently. The consideration is whether this functionality should be considered an [implementation detail](https://testing.googleblog.com/2015/01/testing-on-toilet-prefer-testing-public.html) of the EDP simulator. This may indeed be something that we want more expansive testing on, which warrants splitting it out. This would mean that EDP simulator test could use a test double (e.g. mock) for this if desired.
2. We technically do not yet offer an official EDP library. Code from this repo hasn't been designed to be depended on externally[^*]. The EDP libraries we do offer are in separate repositories (e.g. consent-signaling-client, any-sketch). If we want to provide functionality from this repo as a separate library, we should have a separate design covering that which identifies everything that should be included.

[^*]: Aside from gRPC APIs, namely the Reporting API.
</blockquote></details>

My sense is that we should start moving these kinds of things into the main repo under some "EDP integration util" category. Eventually moving anysketch, the PBM, and similar things into that would also make sense.

However, I don't think it's a good use of time at the moment as we have more urgent things to concern ourselves with. Perhaps we can take this up after we get some of our more urgent items sorted out, and think about this more broadly in the context of the monorepo work.


<!-- Sent from Reviewable.io -->

2023-01-24 20:44 UTC, stevenwarejones approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/814)* status: all files reviewed, 1 unresolved discussion (waiting on @riemanli and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 835 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/814#-NM1HeDT7SRW52OthCmb:-NM_WViF49-p8_QNEal1:b-99jyq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8ed87de92b35aadd34fe2f7af0c0d38f12b0d4fe/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L835)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

My sense is that we should start moving these kinds of things into the main repo under some "EDP integration util" category. Eventually moving anysketch, the PBM, and similar things into that would also make sense.

However, I don't think it's a good use of time at the moment as we have more urgent things to concern ourselves with. Perhaps we can take this up after we get some of our more urgent items sorted out, and think about this more broadly in the context of the monorepo work.
</blockquote></details>

I'm fine with leaving it as-is, but I'd prefer the function keep a test with the idea that in the future, it won't be private.


<!-- Sent from Reviewable.io -->

2023-01-24 22:03 UTC, kungfucraig reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/814)* status: all files reviewed, 1 unresolved discussion (waiting on @riemanli and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 835 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/814#-NM1HeDT7SRW52OthCmb:-NM_ncXG2Johgkb2_jWG:bhwxdv7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8ed87de92b35aadd34fe2f7af0c0d38f12b0d4fe/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L835)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

I'm fine with leaving it as-is, but I'd prefer the function keep a test with the idea that in the future, it won't be private.
</blockquote></details>

@stevenwarejones that makes sense to me


<!-- Sent from Reviewable.io -->

2023-01-25 17:57 UTC, iverson52000 commented
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 835 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/814#-NM1HeDT7SRW52OthCmb:-NMe3PGD1B4Fbd4Fk--t:baf0ra0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8ed87de92b35aadd34fe2f7af0c0d38f12b0d4fe/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L835)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

@stevenwarejones that makes sense to me
</blockquote></details>

Thanks for your feedback Steven! I discussed with the team yesterday and there’s a need to support adding Gaussian noise in the future. In that case, it will make sense to create an interface to support different types of noise distributions. I would like to handle that in a separate PR since the main purpose of this PR is to fix the calculation of noised reach value. For this PR, I will keep this function private for now and test the changes with public API in EDP simulator as Sanjay suggested.


<!-- Sent from Reviewable.io -->

2023-01-25 17:58 UTC, iverson52000 commented
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 835 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/814#-NM1HeDT7SRW52OthCmb:-NMe3yfCDlmy2Bexc1Wb:bb6un1j) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8ed87de92b35aadd34fe2f7af0c0d38f12b0d4fe/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L835)):*
<details><summary><i>Previously, iverson52000 (Albert Hsu) wrote…</i></summary><blockquote>

Thanks for your feedback Steven! I discussed with the team yesterday and there’s a need to support adding Gaussian noise in the future. In that case, it will make sense to create an interface to support different types of noise distributions. I would like to handle that in a separate PR since the main purpose of this PR is to fix the calculation of noised reach value. For this PR, I will keep this function private for now and test the changes with public API in EDP simulator as Sanjay suggested.
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-01-25 20:33 UTC, stevenwarejones requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/814)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @kungfucraig, @riemanli, and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 835 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/814#-NM1HeDT7SRW52OthCmb:-NMecQAk-BVm4a2UKnnd:b-tt8nvm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8ed87de92b35aadd34fe2f7af0c0d38f12b0d4fe/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L835)):*
<details><summary><i>Previously, iverson52000 (Albert Hsu) wrote…</i></summary><blockquote>

Done
</blockquote></details>

I agree we will need to add different types of noise -- Laplace, Gaussian etc and an interface makes sense.

Sorry - I realize I wasn't clear - I'd like to keep the tests that exercise this function. Please make this function not private so it can be tested. I'm fine with internal for now.... with a TODO to move it into its own class.


<!-- Sent from Reviewable.io -->

2023-01-25 20:44 UTC, SanjayVas requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/814)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @kungfucraig, @riemanli, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 835 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/814#-NM1HeDT7SRW52OthCmb:-NMeeqohELOu_nzFLBen:b-e3jv6x) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8ed87de92b35aadd34fe2f7af0c0d38f12b0d4fe/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L835)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

I agree we will need to add different types of noise -- Laplace, Gaussian etc and an interface makes sense.

Sorry - I realize I wasn't clear - I'd like to keep the tests that exercise this function. Please make this function not private so it can be tested. I'm fine with internal for now.... with a TODO to move it into its own class.
</blockquote></details>

I disagree with the above comment. Keep it private for now. Tests against that method would be added if/when it gets moved to another class.

Methods should not be exposed just so they can be tested directly at any time. Always test via public API.


<!-- Sent from Reviewable.io -->

2023-01-25 21:32 UTC, stevenwarejones requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/814)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @iverson52000, @kungfucraig, and @riemanli)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 856 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/814#-NMepKioA9CWWWwq_hQs:-NMepKip1pqXLLG-OP6U:bmitqh5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b70ed326ef6f4c1fde4a57a1e7de288ca31de003/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L856)):*
> ```Kotlin
>       // Differentially private reach value is calculated by reach_dp = (reach + noise) /
>       // sampling_rate.
>       val noisedReachValue =
> ```

it feels a little weird to be upscaling the value inside of `addPublisherNoise. I think the upscaling should be done outside this function. Even if a publisher chooses not to add noise, they still need to upscale.


<!-- Sent from Reviewable.io -->

2023-01-25 22:25 UTC, iverson52000 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/814)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @kungfucraig, @riemanli, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 856 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/814#-NMepKioA9CWWWwq_hQs:-NMf17dN9wZ_msjHG1Rt:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b70ed326ef6f4c1fde4a57a1e7de288ca31de003/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L856)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

it feels a little weird to be upscaling the value inside of `addPublisherNoise. I think the upscaling should be done outside this function. Even if a publisher chooses not to add noise, they still need to upscale.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-01-26 00:13 UTC, stevenwarejones approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/814)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @iverson52000, @kungfucraig, and @riemanli)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 682 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/814#-NMfPsjD9un_C_Eni-5X:-NMfPsjD9un_C_Eni-5Y:bh9pebo) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/35b375986afd3822bbfc596e2d56f3cb3320b60e/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L682)):*
> ```Kotlin
>   ) {
>     logger.info("Calculating direct reach and frequency...")
>     val vidSampler = VidSampler(VID_SAMPLER_HASH_FUNCTION)
> ```

```
require(samplingRate > 0 && samplingRate <= 1.0) { "Invalid samplingRate $samplingRate" }
```



<!-- Sent from Reviewable.io -->

2023-01-26 00:13 UTC, stevenwarejones approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/814)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @iverson52000, @kungfucraig, and @riemanli)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 682 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/814#-NMfPsjD9un_C_Eni-5X:-NMfPzXT3Ex_x3TDqX1a:b-s8ydzr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/35b375986afd3822bbfc596e2d56f3cb3320b60e/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L682)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

```
require(samplingRate > 0 && samplingRate <= 1.0) { "Invalid samplingRate $samplingRate" }
```

</blockquote></details>

for `vidSamplingIntervalWidth` I mean



_Code quote:_
```Kotlin
vidSamplingIntervalWidth
```


<!-- Sent from Reviewable.io -->

2023-01-26 16:56 UTC, kungfucraig requested changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/814)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @iverson52000, @riemanli, @stevenwarejones, and @VisibleForTesting)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 835 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/814#-NM1HeDT7SRW52OthCmb:-NMizMpL4TXvdgUptwXG:bp0j9xj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8ed87de92b35aadd34fe2f7af0c0d38f12b0d4fe/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L835)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I disagree with the above comment. Keep it private for now. Tests against that method would be added if/when it gets moved to another class.

Methods should not be exposed just so they can be tested directly at any time. Always test via public API.
</blockquote></details>

This is a fairly fundamental bit of functionality, and kind of a pain to test indirectly. In pure Java land I'd annotate it @VisibleForTesting and test the heck out of it. 

Similarly the scaling method.

We've already agreed they belong in a library, but for sake of expediency we are not moving them right now, so making them public and writing tests doesn't really hurt much even if it's breaking a typically useful convention.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 682 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/814#-NMfPsjD9un_C_Eni-5X:-NMiyNqa5KNv6Y5UcGwm:btczhte) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/35b375986afd3822bbfc596e2d56f3cb3320b60e/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L682)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

for `vidSamplingIntervalWidth` I mean
</blockquote></details>

I think you want (start < 1 && start >=0 && width >0 && width+start < 1)
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 851 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/814#-NMj-JIADnVCygW74Wc0:-NMj-JIBBufhEpadIc3o:bmmdf1v) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/35b375986afd3822bbfc596e2d56f3cb3320b60e/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L851)):*
> ```Kotlin
>       val laplaceForFrequency =
>         LaplaceDistribution(0.0, 1 / reachAndFrequency.frequencyPrivacyParams.epsilon)
>       laplaceForFrequency.reseedRandomGenerator(1)
> ```

Please leave a comment in the code indicating why we are reseeding the RNG.


<!-- Sent from Reviewable.io -->

2023-01-26 19:54 UTC, stevenwarejones requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/814)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @iverson52000, @kungfucraig, @riemanli, and @VisibleForTesting)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 682 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/814#-NMfPsjD9un_C_Eni-5X:-NMjdCC-CakZCMyqs1E2:bhwgqwj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/35b375986afd3822bbfc596e2d56f3cb3320b60e/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L682)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

I think you want (start < 1 && start >=0 && width >0 && width+start < 1)
</blockquote></details>

yeah - both those with separate requires would be great


<!-- Sent from Reviewable.io -->

2023-01-26 20:01 UTC, iverson52000 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/814)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @kungfucraig, @riemanli, @stevenwarejones, and @VisibleForTesting)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 682 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/814#-NMfPsjD9un_C_Eni-5X:-NMjeQA09qntkfM6Z3Be:bhawgjh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/35b375986afd3822bbfc596e2d56f3cb3320b60e/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L682)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

yeah - both those with separate requires would be great
</blockquote></details>

Sure. I will add both. In Craig's require, `width+start <= 1` since width can be 1.0f?


<!-- Sent from Reviewable.io -->

2023-01-26 21:01 UTC, stevenwarejones reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/814)* status: 2 of 3 files reviewed, 5 unresolved discussions (waiting on @iverson52000, @kungfucraig, @riemanli, and @VisibleForTesting)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 693 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/814#-NMjsWwI0LGHxE1-UYAn:-NMjsWwI0LGHxE1-UYAo:buhiphi) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/35b375986afd3822bbfc596e2d56f3cb3320b60e/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L693)):*
> ```Kotlin
>           vidSampler.vidIsInSamplingBucket(vid, vidSamplingIntervalStart, vidSamplingIntervalWidth)
>         }
>     val (reachValue, frequencyMap) = calculateDirectReachAndFrequency(vidList)
> ```

maybe call this `sampledReachValue`
```
val (sampledReachValue, frequencyMap) = 
```




_Code quote:_
```Kotlin
val (reachValue, frequencyMap)
```
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 696 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/814#-NMjsh4DEfQJAo3biYQ0:-NMjsh4DEfQJAo3biYQ1:bjsf7nv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/35b375986afd3822bbfc596e2d56f3cb3320b60e/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L696)):*
> ```Kotlin
> 
>     logger.info("Adding publisher noise to direct reach and frequency...")
>     val (noisedReachValue, noisedFrequencyMap) =
> ```

ditto maybe `sampledNoisedReachValue`


<!-- Sent from Reviewable.io -->

2023-01-26 21:25 UTC, kungfucraig approved these changes
> Reviewed 1 of 2 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/814)* status: all files reviewed, 4 unresolved discussions (waiting on @iverson52000, @riemanli, @stevenwarejones, and @VisibleForTesting)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 851 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/814#-NMj-JIADnVCygW74Wc0:-NMjxtO66dtjb6jlFEVh:bb7k0qh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/35b375986afd3822bbfc596e2d56f3cb3320b60e/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L851)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Please leave a comment in the code indicating why we are reseeding the RNG.
</blockquote></details>

lgtm


<!-- Sent from Reviewable.io -->

2023-01-26 21:26 UTC, iverson52000 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/814)* status: all files reviewed, 4 unresolved discussions (waiting on @riemanli, @stevenwarejones, and @VisibleForTesting)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 835 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/814#-NM1HeDT7SRW52OthCmb:-NMjy8wuB5A5AnKfztXu:b-3ekzzv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8ed87de92b35aadd34fe2f7af0c0d38f12b0d4fe/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L835)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

This is a fairly fundamental bit of functionality, and kind of a pain to test indirectly. In pure Java land I'd annotate it @VisibleForTesting and test the heck out of it. 

Similarly the scaling method.

We've already agreed they belong in a library, but for sake of expediency we are not moving them right now, so making them public and writing tests doesn't really hurt much even if it's breaking a typically useful convention.
</blockquote></details>

Discussed with Sanjay and Steven yesterday and will leave the function private for now. The desired behavior, noised reach value should be scaled by sampling rate, is tested through public API `executeRequisitionFulfillingWorkflow`
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 693 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/814#-NMjsWwI0LGHxE1-UYAn:-NMjwj3u07pmn81o0jlM:btornf7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/35b375986afd3822bbfc596e2d56f3cb3320b60e/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L693)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

maybe call this `sampledReachValue`
```
val (sampledReachValue, frequencyMap) = 
```

</blockquote></details>

Sure it's more explicit with this name
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 696 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/814#-NMjsh4DEfQJAo3biYQ0:-NMjwwNU-gmNIuZKEIuk:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/35b375986afd3822bbfc596e2d56f3cb3320b60e/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L696)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

ditto maybe `sampledNoisedReachValue`
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 851 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/814#-NMj-JIADnVCygW74Wc0:-NMjx-WpCyu3091i-ag5:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/35b375986afd3822bbfc596e2d56f3cb3320b60e/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L851)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Please leave a comment in the code indicating why we are reseeding the RNG.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-01-26 21:26 UTC, iverson52000 commented
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 693 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/814#-NMjsWwI0LGHxE1-UYAn:-NMjyPW43brEp3iMcyFI:bb6un1j) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/35b375986afd3822bbfc596e2d56f3cb3320b60e/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L693)):*
<details><summary><i>Previously, iverson52000 (Albert Hsu) wrote…</i></summary><blockquote>

Sure it's more explicit with this name
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2023-01-26 22:50 UTC, stevenwarejones approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/814)* status: all files reviewed, 2 unresolved discussions (waiting on @riemanli and @VisibleForTesting)



<!-- Sent from Reviewable.io -->

2023-01-27 18:30 UTC, riemanli approved these changes
> Reviewed 1 of 3 files at r1, 1 of 2 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/814)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)



<!-- Sent from Reviewable.io -->

2023-01-30 16:20 UTC, stevenwarejones approved these changes
> Reviewed 1 of 2 files at r2, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/814)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @iverson52000)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 859 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/814#-NN2TQ640NFfzNKImP0_:-NN2TQ65BLs4SBceV4Rh:bvsar4l) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f88ecdad914df944f13da2adc30d175efadf2ce4/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L859)):*
> ```Kotlin
>         LaplaceDistribution(0.0, 1 / reachAndFrequency.reachPrivacyParams.epsilon)
>       // Reseed random number generator so the results can be verified in tests.
>       // TODO(alberthsuu): make reandomSeed an input once create noiser class
> ```

`make randomSeed`


<!-- Sent from Reviewable.io -->

2023-01-30 16:22 UTC, SanjayVas approved these changes
> Reviewed 1 of 3 files at r1, 1 of 2 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/814)* status: all files reviewed, 1 unresolved discussion (waiting on @iverson52000)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 843 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/814#-NN2Tp3c34NYiLbKnW4C:-NN2TaSq1BRjtj-VuOsN:bmcmgzz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f88ecdad914df944f13da2adc30d175efadf2ce4/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L843)):*
> ```Kotlin
>     }
> 
>     // TODO(alberthsuu): Create a noiser class for this function when we need to add Gaussian noise
> ```

nit: move the TODO inside of the KDoc block rather than having a separate comment

Also follow TODO format described in code style doc: https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/docs/code-style.md#format


<!-- Sent from Reviewable.io -->

2023-01-30 18:26 UTC, stevenwarejones approved these changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/814)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @iverson52000)



<!-- Sent from Reviewable.io -->

2023-01-30 18:40 UTC, merged