v2alpha database schema
world-federation-of-advertisers/cross-media-measurement pull request #835
Opened 2023-01-27 18:08 UTC by riemanli

2023-01-27 18:14 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 19 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NMoQTcT0A22JVn-l8AF:-NMoQTcT0A22JVn-l8AG:bkrnyx1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ee0a2141b705a1c25ca5ea2ad1ff8da6e76caa90/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L19)):*
> ```TSQL
> -- Postgres database schema for the Reporting server.
> --
> -- Table hierarchy:
> ```

Please take this with a grain of salt. I am not sure if I mapped this correct.
___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 118 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NMoQ6f92q2g_SXGFqWO:-NMoQ6f92q2g_SXGFqWP:bx8ylx1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ee0a2141b705a1c25ca5ea2ad1ff8da6e76caa90/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L118)):*
> ```TSQL
>   ON CompositeReportingSets(MeasurementConsumerId, ExternalReportingSetId);
> 
> CREATE TABLE SetExpressions (
> ```

`SetExpressions` and `CompositeReportingSet` have circular relationship. Is that ok?


<!-- Sent from Reviewable.io -->

2023-01-27 20:25 UTC, tristanvuong2021 requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @riemanli and @SanjayVas)

___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 3 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NMou-bD9wNfTuW5x9Ek:-NMou-bD9wNfTuW5x9El:bu0alzg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ee0a2141b705a1c25ca5ea2ad1ff8da6e76caa90/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L3)):*
> ```TSQL
> -- liquibase formatted sql
> 
> -- Copyright 2022 The Cross-Media Measurement Authors
> ```

This should be 2023
___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 495 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NMotvfj1t-b7YUZs0Q4:-NMotvfj1t-b7YUZs0Q5:blxw394) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ee0a2141b705a1c25ca5ea2ad1ff8da6e76caa90/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L495)):*
> ```TSQL
> 
> 
> CREATE TABLE Metrics (
> ```

This section looks like a leftover from copying


<!-- Sent from Reviewable.io -->

2023-01-27 20:35 UTC, tristanvuong2021 requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @riemanli and @SanjayVas)

___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 94 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NMovwo00lSkHY1ugK0k:-NMovwo00lSkHY1ugK0l:b-1bwdtt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ee0a2141b705a1c25ca5ea2ad1ff8da6e76caa90/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L94)):*
> ```TSQL
> );
> 
> CREATE INDEX TimeIntervalsByStartEndExclusive
> ```

I made a mistake in the first version, but doing CREATE UNIQUE INDEX here and doing away with the UNIQUE above saves space. This also applies to the other CREATE INDEX statements.


<!-- Sent from Reviewable.io -->

2023-01-27 20:52 UTC, tristanvuong2021 requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835)* status: 0 of 1 files reviewed, 12 unresolved discussions (waiting on @riemanli and @SanjayVas)

___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 122 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NMozn7WANj17q1vFGx7:-NMozn7WANj17q1vFGx8:b-7zp84g) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ee0a2141b705a1c25ca5ea2ad1ff8da6e76caa90/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L122)):*
> ```TSQL
>   SetExpressionId bigint NOT NULL,
> 
>   -- org.wfanet.measurement.internal.reporting.SetOperation.Operation
> ```

Will the path in this comment still be valid here.
___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 126 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NMp-13a1KMCr4Mn0DX1:-NMp-13a1KMCr4Mn0DX2:b-5c2ydc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ee0a2141b705a1c25ca5ea2ad1ff8da6e76caa90/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L126)):*
> ```TSQL
>   Operation smallint NOT NULL,
> 
>   LeftHandSetOperationId bigint,
> ```

Leftover
___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 129 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NMp-4gfB4U5aCfSn4cs:-NMp-4gfB4U5aCfSn4ct:b-5c2ydc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ee0a2141b705a1c25ca5ea2ad1ff8da6e76caa90/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L129)):*
> ```TSQL
>   LeftHandCompositeReportingSetId bigint,
>   LeftHandPrimitiveReportingSetId bigint,
>   RightHandSetOperationId bigint,
> ```

Leftover
___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 308 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NMoxCXq7iWXHLe-zKYp:-NMoxCXq7iWXHLe-zKYq:b2xrsu5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ee0a2141b705a1c25ca5ea2ad1ff8da6e76caa90/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L308)):*
> ```TSQL
>   MetricId bigint NOT NULL,
> 
>   PRIMARY KEY(MeasurementConsumerId, MetricId, MeasurementId),
> ```

MeasurementId  is not the right column here for the primary key.
___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 322 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NMoxtWR4aNYwtBF4A5i:-NMoxtWR4aNYwtBF4A5j:b7tslw2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ee0a2141b705a1c25ca5ea2ad1ff8da6e76caa90/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L322)):*
> ```TSQL
>   MetricSpecId bigint NOT NULL,
> 
>   PRIMARY KEY(MeasurementConsumerId, MetricId, MeasurementId),
> ```

MeasurementId and MetricId  are not the right columns here for the primary key.
___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 336 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NMoy-4S7RywyATkFhS2:-NMoy-4T2SE51ZUeSARu:b7tslw2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ee0a2141b705a1c25ca5ea2ad1ff8da6e76caa90/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L336)):*
> ```TSQL
>   TimeIntervalId bigint NOT NULL,
> 
>   PRIMARY KEY(MeasurementConsumerId, MetricId, MeasurementId),
> ```

MeasurementId and MetricId  are not the right columns here for the primary key.
___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 350 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NMoy2B4CUTjtc7CQReq:-NMoy2B4CUTjtc7CQRer:b7tslw2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ee0a2141b705a1c25ca5ea2ad1ff8da6e76caa90/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L350)):*
> ```TSQL
>   ReportingSetId bigint NOT NULL,
> 
>   PRIMARY KEY(MeasurementConsumerId, MetricId, MeasurementId),
> ```

MeasurementId and MetricId  are not the right columns here for the primary key.


<!-- Sent from Reviewable.io -->

2023-01-27 21:45 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835)* status: 0 of 1 files reviewed, 12 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 3 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NMou-bD9wNfTuW5x9Ek:-NMp6PG6-XREq-C3fJS6:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ee0a2141b705a1c25ca5ea2ad1ff8da6e76caa90/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L3)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

This should be 2023
</blockquote></details>

Done.
___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 94 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NMovwo00lSkHY1ugK0k:-NMp9-lcB4tg3fuQ3ZmJ:b-b2k374) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ee0a2141b705a1c25ca5ea2ad1ff8da6e76caa90/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L94)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

I made a mistake in the first version, but doing CREATE UNIQUE INDEX here and doing away with the UNIQUE above saves space. This also applies to the other CREATE INDEX statements.
</blockquote></details>

Thanks for letting me know!
Done.



_Code quote:_
```TSQL
CREATE INDEX
```
___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 122 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NMozn7WANj17q1vFGx7:-NMp9ATn-U3-EUhF9DzJ:b-9jc41h) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ee0a2141b705a1c25ca5ea2ad1ff8da6e76caa90/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L122)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Will the path in this comment still be valid here.
</blockquote></details>

Thanks for pointing it out. Should be `SetExpression`. 
follow-up question: If the message `SetExpression` is defined in `reporting_set.proto` and parallel to `ReportingSet`, is the above the right path?
___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 126 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NMp-13a1KMCr4Mn0DX1:-NMpAP9wEk6dpjgnQRbP:b-k4dzbl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ee0a2141b705a1c25ca5ea2ad1ff8da6e76caa90/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L126)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Leftover
</blockquote></details>

Thanks for catching it. Done
___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 129 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NMp-4gfB4U5aCfSn4cs:-NMpASut3a6a8vjsKG2O:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ee0a2141b705a1c25ca5ea2ad1ff8da6e76caa90/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L129)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Leftover
</blockquote></details>

Done.
___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 308 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NMoxCXq7iWXHLe-zKYp:-NMpAayS6KlgZsWt-PX6:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ee0a2141b705a1c25ca5ea2ad1ff8da6e76caa90/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L308)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

MeasurementId  is not the right column here for the primary key.
</blockquote></details>

Done.
___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 322 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NMoxtWR4aNYwtBF4A5i:-NMpAmdZ9t7UgN58CfhZ:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ee0a2141b705a1c25ca5ea2ad1ff8da6e76caa90/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L322)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

MeasurementId and MetricId  are not the right columns here for the primary key.
</blockquote></details>

Done.
___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 336 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NMoy-4S7RywyATkFhS2:-NMpAtEaBAZJ1xXhIFNw:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ee0a2141b705a1c25ca5ea2ad1ff8da6e76caa90/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L336)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

MeasurementId and MetricId  are not the right columns here for the primary key.
</blockquote></details>

Done.
___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 350 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NMoy2B4CUTjtc7CQReq:-NMpAu6JDTb8ViRKJP-x:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ee0a2141b705a1c25ca5ea2ad1ff8da6e76caa90/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L350)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

MeasurementId and MetricId  are not the right columns here for the primary key.
</blockquote></details>

Done.
___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 495 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NMotvfj1t-b7YUZs0Q4:-NMpAwvs4npmKuOrP_ha:b-kdg7u4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ee0a2141b705a1c25ca5ea2ad1ff8da6e76caa90/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L495)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

This section looks like a leftover from copying
</blockquote></details>

Yes... Thanks for pointing it out!


<!-- Sent from Reviewable.io -->

2023-01-28 01:28 UTC, tristanvuong2021 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 122 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NMozn7WANj17q1vFGx7:-NMpyzly-VfU0m6r0z-_:beb79hc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ee0a2141b705a1c25ca5ea2ad1ff8da6e76caa90/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L122)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Thanks for pointing it out. Should be `SetExpression`. 
follow-up question: If the message `SetExpression` is defined in `reporting_set.proto` and parallel to `ReportingSet`, is the above the right path?
</blockquote></details>

Yeah, that would be the right path. The v1alpha version should have Metric in the path actually.


<!-- Sent from Reviewable.io -->

2023-01-28 01:31 UTC, tristanvuong2021 requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @riemanli and @SanjayVas)

___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 380 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NMpzteo6253F7sKSj6v:-NMpzteo6253F7sKSj6w:baovail) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/999c4fa02dcbb2a7524275d1f35d0953b4c30eea/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L380)):*
> ```TSQL
> );
> 
> CREATE INDEX ReportsByExternalReportId
> ```

There is this index too that can be UNIQUE in place of the UNIQUE constraint above.


<!-- Sent from Reviewable.io -->

2023-01-28 02:08 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 118 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NMoQ6f92q2g_SXGFqWO:-NMq7PyA-3Hz3e3of9ZP:b-93wl4e) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ee0a2141b705a1c25ca5ea2ad1ff8da6e76caa90/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L118)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

`SetExpressions` and `CompositeReportingSet` have circular relationship. Is that ok?
</blockquote></details>

@tristanvuong2021 could you confirm the circular relationship is handled correctly here? Thanks!
___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 380 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NMpzteo6253F7sKSj6v:-NMq7IJQ0O7EmQIjrxuI:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/999c4fa02dcbb2a7524275d1f35d0953b4c30eea/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L380)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

There is this index too that can be UNIQUE in place of the UNIQUE constraint above.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-01-30 18:22 UTC, tristanvuong2021 requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @riemanli and @SanjayVas)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NN2sTfi4gGPrRXxHuOA:-NN2sTfjEeVLjNXalnyF:bfydvjs) (no related file):*
The foreign keys also need to be on delete cascade. See https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/main/resources/reporting/postgres/alter-foreign-key-constraints-to-be-on-delete-cascade.sql

___
___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 118 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NMoQ6f92q2g_SXGFqWO:-NN2shZa1aeF0T8i137o:b-ut1qs) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ee0a2141b705a1c25ca5ea2ad1ff8da6e76caa90/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L118)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

@tristanvuong2021 could you confirm the circular relationship is handled correctly here? Thanks!
</blockquote></details>

Looks good, although it is possible to add two more foreign keys for LeftHandSetExpressionId and RightHandSetExpressionId.
___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 148 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NN2uC0h6u4GHnsrRC5c:-NN2uC0h6u4GHnsrRC5d:b-a80z1w) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/54a204cb804317134d7b8a651df573e2b4457736/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L148)):*
> ```TSQL
>   PrimitiveReportingSetId bigint NOT NULL,
> 
>   ExternalReportingSetId bigint NOT NULL,
> ```

Is this ExternalReportingSetId and the one in CompositeReportingSets the id used for the reporting set name in the public api. If so, it is possible for the same id to be in both PrimitiveReportingSets and CompositeReportingSets and it should be in ReportingSets instead.


<!-- Sent from Reviewable.io -->

2023-01-30 22:21 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NN2sTfi4gGPrRXxHuOA:-NN3l5949eNrLsxggQPl:bc1ry7e) (no related file):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

The foreign keys also need to be on delete cascade. See https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/main/resources/reporting/postgres/alter-foreign-key-constraints-to-be-on-delete-cascade.sql
</blockquote></details>

Would you mind explaining what this .sql file is for?

___
___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 118 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NMoQ6f92q2g_SXGFqWO:-NN367RN1CtdV21ecl7L:bhb0j78) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ee0a2141b705a1c25ca5ea2ad1ff8da6e76caa90/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L118)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Looks good, although it is possible to add two more foreign keys for LeftHandSetExpressionId and RightHandSetExpressionId.
</blockquote></details>

Thanks for confirming. Is it ok for `SetExpressions` to have foreign keys to its own table? I didn't see you did the same for `SetOperations`. Any reason?


<!-- Sent from Reviewable.io -->

2023-01-30 22:24 UTC, tristanvuong2021 requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @riemanli and @SanjayVas)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NN2sTfi4gGPrRXxHuOA:-NN3lrVSBTXbY_tcOzbg:b-9cewlu) (no related file):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Would you mind explaining what this .sql file is for?
</blockquote></details>

It is an example of foreign keys with on delete cascade.

___
___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 118 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NMoQ6f92q2g_SXGFqWO:-NN3llKo1rUApMz5bj6Y:bbnzzvp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ee0a2141b705a1c25ca5ea2ad1ff8da6e76caa90/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L118)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Thanks for confirming. Is it ok for `SetExpressions` to have foreign keys to its own table? I didn't see you did the same for `SetOperations`. Any reason?
</blockquote></details>

It is okay. I should have done the same there.


<!-- Sent from Reviewable.io -->

2023-01-31 01:42 UTC, SanjayVas requested changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835)* status: all files reviewed, 10 unresolved discussions (waiting on @riemanli and @tristanvuong2021)

___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 49 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NN4LPjFDJQmH0b6-M-b:-NN4LPjFDJQmH0b6-M-c:b-26emuw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/54a204cb804317134d7b8a651df573e2b4457736/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L49)):*
> ```TSQL
> -- changeset riemanli:create-v2alpha-reports-table dbms:postgresql
> CREATE TABLE MeasurementConsumers (
>   MeasurementConsumerId text NOT NULL,
> ```

Internal IDs should be UUID, or can be`bigint` if we want to reuse the InternalId wrapper class.



_Code quote:_
```TSQL
text
```
___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 122 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NN4MZQZ7pgoQoK5_Z6g:-NN4MZQZ7pgoQoK5_Z6h:bydgvwx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/54a204cb804317134d7b8a651df573e2b4457736/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L122)):*
From [Postgres docs](https://www.postgresql.org/docs/current/datatype-numeric.html#DATATYPE-INT):
> The `smallint` type is generally only used if disk space is at a premium.



_Code quote:_
```TSQL
smallint
```
___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 126 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NN4TrTP25ThokgAyZSx:-NN4TrTP25ThokgAyZSy:b-b63e5s) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/54a204cb804317134d7b8a651df573e2b4457736/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L126)):*
> ```TSQL
>   LeftHandSetExpressionId bigint,
>   LeftHandCompositeReportingSetId bigint,
>   LeftHandPrimitiveReportingSetId bigint,
> ```

Document the oneof-like nature of the IDs, including the fact that *exactly* one of the lhs fields **must** be non-NULL whereas for the rhs fields it's that *at most* one of the fields must be non-NULL



_Code quote:_
```TSQL
  LeftHandSetExpressionId bigint,
  LeftHandCompositeReportingSetId bigint,
  LeftHandPrimitiveReportingSetId bigint,
  RightHandSetExpressionId bigint,
  RightHandCompositeReportingSetId bigint,
  RightHandPrimitiveReportingSetId bigint,
```
___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 150 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NN4QKZW00cT1YiMjBrC:-NN4QKZW00cT1YiMjBrD:bo5nncq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/54a204cb804317134d7b8a651df573e2b4457736/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L150)):*
> ```TSQL
>   ExternalReportingSetId bigint NOT NULL,
> 
>   Filter text NOT NULL,
> ```

Isn't the filter optional?



_Code quote:_
```TSQL
NOT NULL
```
___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 182 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NN4SmxaDy8qBeUGLMrU:-NN4SmxaDy8qBeUGLMrV:ba3j7o) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/54a204cb804317134d7b8a651df573e2b4457736/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L182)):*
> ```TSQL
>   ReportingSetId bigint NOT NULL,
> 
>   -- it's either CompositeReportingSet or PrimitiveReportingSet
> ```

nit: this could be clearer



_Suggestion:_
```TSQL
  -- Exactly one of (CompositeReportingSet, PrimitiveReportingSet) must be non-null
```
___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 203 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NN4T3TK6yXjcJXqfG2c:-NN4T3TK6yXjcJXqfG2d:b-889l6h) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/54a204cb804317134d7b8a651df573e2b4457736/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L203)):*
> ```TSQL
>   MetricType smallint NOT NULL,
> 
>   -- Depending on what metric type is used, the parameters can be null.
> ```

nit: be more specific here. e.g. "must not be NULL if MetricType is X, Y, or Z"
___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 288 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NN4RST94cAeS5qL1QOw:-NN4RST94cAeS5qL1QOx:bw5m2ma) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/54a204cb804317134d7b8a651df573e2b4457736/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L288)):*
> ```TSQL
>   MeasurementConsumerId text NOT NULL,
>   ModelId bigint NOT NULL,
> ```

Don't we need an ExternalModelId here?


<!-- Sent from Reviewable.io -->

2023-01-31 06:54 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835)* status: all files reviewed, 7 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 118 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NMoQ6f92q2g_SXGFqWO:-NN3numE73NLlvac5Pm_:bb6un1j) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ee0a2141b705a1c25ca5ea2ad1ff8da6e76caa90/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L118)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

It is okay. I should have done the same there.
</blockquote></details>

Done
___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 49 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NN4LPjFDJQmH0b6-M-b:-NN5Wqe91z-DncBhYoEE:b-w1w4tx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/54a204cb804317134d7b8a651df573e2b4457736/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L49)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Internal IDs should be UUID, or can be`bigint` if we want to reuse the InternalId wrapper class.
</blockquote></details>

Changed internal IDs to be `bigint`.
___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 122 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NN4MZQZ7pgoQoK5_Z6g:-NN5XET_85sIJcjuGiiM:b-tbmahy) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/54a204cb804317134d7b8a651df573e2b4457736/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L122)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

From [Postgres docs](https://www.postgresql.org/docs/current/datatype-numeric.html#DATATYPE-INT):
> The `smallint` type is generally only used if disk space is at a premium.
</blockquote></details>

Changed `smallint` to `integer`.
___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 126 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NN4TrTP25ThokgAyZSx:-NN5YQPKBMZ9_KvN8udZ:b-rav7tl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/54a204cb804317134d7b8a651df573e2b4457736/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L126)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Document the oneof-like nature of the IDs, including the fact that *exactly* one of the lhs fields **must** be non-NULL whereas for the rhs fields it's that *at most* one of the fields must be non-NULL
</blockquote></details>

Add comments for lhs and rhs. Please take a look. Thanks!
___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 148 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NN2uC0h6u4GHnsrRC5c:-NN5YZKeCJF0kJyVOYtV:by6bddx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/54a204cb804317134d7b8a651df573e2b4457736/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L148)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Is this ExternalReportingSetId and the one in CompositeReportingSets the id used for the reporting set name in the public api. If so, it is possible for the same id to be in both PrimitiveReportingSets and CompositeReportingSets and it should be in ReportingSets instead.
</blockquote></details>

The design is pending. Will modify this part later once it's determined. 
___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 150 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NN4QKZW00cT1YiMjBrC:-NN5YyDKDvwvVo9wE5hw:b7523te) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/54a204cb804317134d7b8a651df573e2b4457736/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L150)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Isn't the filter optional?
</blockquote></details>

@tristanvuong2021  please correct me if I am wrong. We use empty string for no filter instead of NULL. 
___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 182 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NN4SmxaDy8qBeUGLMrU:-NN5ZJwr8ceUP8BZQhRU:b-bjudbj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/54a204cb804317134d7b8a651df573e2b4457736/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L182)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: this could be clearer
</blockquote></details>

Thanks for the suggestion! Done.
___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 203 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NN4T3TK6yXjcJXqfG2c:-NN5Zxqs8fPNgjKiIoc9:b-bjudbj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/54a204cb804317134d7b8a651df573e2b4457736/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L203)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: be more specific here. e.g. "must not be NULL if MetricType is X, Y, or Z"
</blockquote></details>

Thanks for the suggestion! Done.
___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 288 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NN4RST94cAeS5qL1QOw:-NN5_4AF7XoPSTblkXxM:b4gu3rr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/54a204cb804317134d7b8a651df573e2b4457736/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L288)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Don't we need an ExternalModelId here?
</blockquote></details>

Good point. Added one in `bigint` and create a unique index for it.


<!-- Sent from Reviewable.io -->

2023-01-31 17:05 UTC, tristanvuong2021 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835)* status: 0 of 1 files reviewed, 7 unresolved discussions (waiting on @riemanli and @SanjayVas)

___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 150 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NN4QKZW00cT1YiMjBrC:-NN7mJwV1vUs2W8vK46I:bkg1gei) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/54a204cb804317134d7b8a651df573e2b4457736/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L150)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

@tristanvuong2021  please correct me if I am wrong. We use empty string for no filter instead of NULL. 
</blockquote></details>

Thinking about it, NULL would actually be better in this case for empty string since it takes up no space, but empty text still takes up space.


<!-- Sent from Reviewable.io -->

2023-01-31 22:38 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835)* status: 0 of 1 files reviewed, 7 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NN2sTfi4gGPrRXxHuOA:-NN8yML26BB4qf_ZwYlW:bui3f3e) (no related file):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

It is an example of foreign keys with on delete cascade.
</blockquote></details>

Got it. I will do it. 
One question about schema.sql and on-delete-cascade.sql: should I modify the existing .sql files or make new ones like what I did in this PR?

___
___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 148 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NN2uC0h6u4GHnsrRC5c:-NN8y8Dy1CmDxkhzrv12:b-un2qx6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/54a204cb804317134d7b8a651df573e2b4457736/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L148)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

The design is pending. Will modify this part later once it's determined. 
</blockquote></details>

Change the reporting set tables according to the new change in the proto design. Now ReportingSets table is the only one that has `ExternalReportingSetId`.
___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 150 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NN4QKZW00cT1YiMjBrC:-NN88iO5BGVEqRlATKzS:b-hqecwp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/54a204cb804317134d7b8a651df573e2b4457736/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L150)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Thinking about it, NULL would actually be better in this case for empty string since it takes up no space, but empty text still takes up space.
</blockquote></details>

Got it. Change `Filter` to optional.


<!-- Sent from Reviewable.io -->

2023-02-01 01:50 UTC, tristanvuong2021 requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835)* status: 0 of 1 files reviewed, 7 unresolved discussions (waiting on @riemanli and @SanjayVas)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NN2sTfi4gGPrRXxHuOA:-NN9d_GeEmfqVmMf1-4p:b-c73vy7) (no related file):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Got it. I will do it. 
One question about schema.sql and on-delete-cascade.sql: should I modify the existing .sql files or make new ones like what I did in this PR?
</blockquote></details>

You don't need another file to add cascading deletes. That was because I forgot to add it. Since this hasn't been deployed yet, the foreign keys here can be directly modified.

___


<!-- Sent from Reviewable.io -->

2023-02-01 06:00 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835)* status: 0 of 1 files reviewed, 8 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 450 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NNAYqC7033NWau8gNdn:-NNAYqC7033NWau8gNdo:bnit3m5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/63c8f807d39ec3c022fd0b938dc8ffae607a245f/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L450)):*
> ```TSQL
> );
> 
> CREATE TABLE WeightedPrimitiveReportingSetBases (
> ```

TODO: this is not right. Missing one layer.


<!-- Sent from Reviewable.io -->

2023-02-01 06:14 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835)* status: 0 of 1 files reviewed, 9 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 468 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NNAb0eQ3uYh6rTFhgM1:-NNAb0eQ3uYh6rTFhgM2:b-qphd8m) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/63c8f807d39ec3c022fd0b938dc8ffae607a245f/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L468)):*
> ```TSQL
> );
> 
> CREATE TABLE ModelInferenceCalculationModelSpecs (
> ```

TODO: This should be `ModelInferenceCalculationMetricSpecs` instead.


<!-- Sent from Reviewable.io -->

2023-02-06 22:22 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835)* status: 0 of 1 files reviewed, 7 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NN2sTfi4gGPrRXxHuOA:-NNcoax5-uyWae02iYYB:b-4xk44g) (no related file):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

You don't need another file to add cascading deletes. That was because I forgot to add it. Since this hasn't been deployed yet, the foreign keys here can be directly modified.
</blockquote></details>

Done. PTAL thanks!

___


<!-- Sent from Reviewable.io -->

2023-02-07 01:58 UTC, SanjayVas requested changes
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835)* status: all files reviewed, 5 unresolved discussions (waiting on @riemanli and @tristanvuong2021)

___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 150 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NN4QKZW00cT1YiMjBrC:-NNdXLv6BIaIbqSIMG8H:b-y051l0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/54a204cb804317134d7b8a651df573e2b4457736/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L150)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Got it. Change `Filter` to optional.
</blockquote></details>

I tend to prefer NULL in general as it's more explicit. It happens to be that NULL and empty string are equivalent for some fields in our proto3 API, but that fact is isolated from the DB layer.
___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 69 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NNdVPju1B9w2Vc_enoC:-NNdVPju1B9w2Vc_enoD:bbs9v3j) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e8eef356b3f3762000a25ecff780992f1799db54/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L69)):*
> ```TSQL
> 
> -- changeset riemanli:create-measurement-consumer-data-providers-table dbms:postgresql
> CREATE TABLE MeasurementConsumerDataProviders (
> ```

Can this and `MeasurementConsumerEventGroups` be folded into `EventGroups` instead of being a separate tables? Each EventGroup is owned by exactly one MeasurementConsumer and exactly one DataProvider.



_Code quote:_
```TSQL
CREATE TABLE MeasurementConsumerDataProviders (
```
___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 165 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NNdWx9j3N-iHqzj2Vee:-NNdWx9j3N-iHqzj2Vef:b-5fbjti) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e8eef356b3f3762000a25ecff780992f1799db54/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L165)):*
> ```TSQL
> 
>   PRIMARY KEY(MeasurementConsumerId, PrimitiveReportingSetId, DataProviderId, EventGroupId),
>   FOREIGN KEY(MeasurementConsumerId)
> ```

You don't need a separate foreign key for MeasurementConsumers, as that's already handled transitively from the foreign key reference for the parent table (PrimitiveReportingSets).



_Code quote:_
```TSQL
  FOREIGN KEY(MeasurementConsumerId)
    REFERENCES MeasurementConsumers(MeasurementConsumerId)
    ON DELETE CASCADE,
```
___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 192 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NNd_BCb7cKGcG-QFC4c:-NNd_BCb7cKGcG-QFC4d:b-nnxvwg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e8eef356b3f3762000a25ecff780992f1799db54/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L192)):*
> ```TSQL
>   ExternalReportingSetId bigint NOT NULL,
> 
>   DisplayName text NOT NULL,
> ```

Isn't display_name is optional in the public API?



_Code quote:_
```TSQL
NOT NULL
```


<!-- Sent from Reviewable.io -->

2023-02-08 21:30 UTC, riemanli commented
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 69 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NNdVPju1B9w2Vc_enoC:-NNmm4el2Y5ne2EsGt1k:b-m70kgz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e8eef356b3f3762000a25ecff780992f1799db54/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L69)):*
> Each EventGroup is owned by exactly one MeasurementConsumer and exactly one DataProvider.


Is that true for the system being multi-tenant? Could multiple MC own the same event group?


<!-- Sent from Reviewable.io -->

2023-02-08 21:37 UTC, riemanli commented
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 165 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NNdWx9j3N-iHqzj2Vee:-NNmmZfl6qHwpsN8hxMA:br96bq8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e8eef356b3f3762000a25ecff780992f1799db54/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L165)):*
> as that's already handled transitively from the foreign key reference for the parent table

Thanks for pointing that out. Does this apply to all kinds of relationships as long as the foreign key can be found in other foreign tables?


<!-- Sent from Reviewable.io -->

2023-02-08 21:57 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 192 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NNd_BCb7cKGcG-QFC4c:-NNmmuJBAxMW0aLp0oQ0:b-3hz2h7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e8eef356b3f3762000a25ecff780992f1799db54/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L192)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Isn't display_name is optional in the public API?
</blockquote></details>

You're right! Fixed.


<!-- Sent from Reviewable.io -->

2023-02-08 21:59 UTC, SanjayVas requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @riemanli and @tristanvuong2021)

___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 69 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NNdVPju1B9w2Vc_enoC:-NNn1GFr3ZBM8JIwnZCX:bbwyj57) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e8eef356b3f3762000a25ecff780992f1799db54/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L69)):*
> Could multiple MC own the same event group?
No.

> Is that true for the system being multi-tenant?
This is unrelated. We're already set up for the system being multi-tenant by the fact that everything is parented by MeasurementConsumer. A single-tenant system would assume the MC and not need to store it in any tables.


<!-- Sent from Reviewable.io -->

2023-02-08 22:09 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 69 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NNdVPju1B9w2Vc_enoC:-NNn3rkB6NkiXfB-_WcU:b1rp7ft) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e8eef356b3f3762000a25ecff780992f1799db54/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L69)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> Could multiple MC own the same event group?
No.

> Is that true for the system being multi-tenant?
This is unrelated. We're already set up for the system being multi-tenant by the fact that everything is parented by MeasurementConsumer. A single-tenant system would assume the MC and not need to store it in any tables.
</blockquote></details>

Got it! Done.


<!-- Sent from Reviewable.io -->

2023-02-09 21:52 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 165 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NNdWx9j3N-iHqzj2Vee:-NNs9C7s-MZaXCDsWwDl:b7qkeil) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e8eef356b3f3762000a25ecff780992f1799db54/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L165)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

> as that's already handled transitively from the foreign key reference for the parent table

Thanks for pointing that out. Does this apply to all kinds of relationships as long as the foreign key can be found in other foreign tables?
</blockquote></details>

Removed redundant foreign keys based on offline discussion.


<!-- Sent from Reviewable.io -->

2023-02-10 00:13 UTC, tristanvuong2021 reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @SanjayVas)



<!-- Sent from Reviewable.io -->

2023-02-10 00:40 UTC, tristanvuong2021 requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @riemanli and @SanjayVas)

___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 508 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NNsiUpeB3Te0h68ZNzn:-NNsgUCaCiWrHT4y5Qk-:bt9wv6f) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f884457b6812112d623bbdc68cf7d79f69bb61cd/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L508)):*
> ```TSQL
>   MetricId bigint NOT NULL,
> 
>   -- Serialized org.wfanet.measurement.internal.reporting.Report.MetricCalculation.Details
> ```

What is this details for?
___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 513 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NNsfPJaAFD0atFwHDvK:-NNsfPJaAFD0atFwHDvL:b5qroiz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f884457b6812112d623bbdc68cf7d79f69bb61cd/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L513)):*
> ```TSQL
> 
>   PRIMARY KEY(MeasurementConsumerId, MetricCalculationId, MetricId),
>   FOREIGN KEY(MeasurementConsumerId, MetricCalculationId)
> ```

ReportId is missing here. It is part of the primary key in MetricCalculations, but not in the foreign key here.
___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 552 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NNsf64UBstmit3Os5co:-NNsf64UBstmit3Os5cp:by08kkr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f884457b6812112d623bbdc68cf7d79f69bb61cd/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L552)):*
> ```TSQL
> 
>   PRIMARY KEY(MeasurementConsumerId, ModelInferenceCalculationId, MetricSpecId),
>   FOREIGN KEY(MeasurementConsumerId, ModelInferenceCalculationId)
> ```

ReportId is missing here. It is part of the primary key in ModelInferenceCalculations, but not in the foreign key here.


<!-- Sent from Reviewable.io -->

2023-02-10 01:27 UTC, SanjayVas requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835)* status: 0 of 1 files reviewed, 10 unresolved discussions (waiting on @riemanli)

___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 76 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NNshJeA7PuhiRni4min:-NNshJeA7PuhiRni4mio:byuzswn) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f884457b6812112d623bbdc68cf7d79f69bb61cd/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L76)):*
> ```TSQL
> 
>   PRIMARY KEY(MeasurementConsumerId, DataProviderId, EventGroupId),
>   UNIQUE (MeasurementConsumerId, DataProviderId, CmmsEventGroupId),
> ```

EventGroup is multi-parented with exactly one parent of each type. Therefore you can pick one to be the canonical parent and the other as just a reference.

Furthermore, each CmmsEventGroupId is only unique for a given CmmsDataProviderId.

```sql
  PRIMARY KEY(MeasurementConsumerId, EventGroupId),
  UNIQUE (DataProviderId, EventGroupId),
  UNIQUE (DataProviderId, CmmsEventGroupId),
```

That said, I'm wondering if we need a separate DataProviders table at all. It should be sufficient to have an EventGroups table that looks like this:

```sql
  MeasurementConsumerId bigint NOT NULL,
  EventGroupId bigint NOT NULL,
  CmmsDataProviderId text NOT NULL,
  CmmsEventGroupId text NOT NULL,

  PRIMARY KEY (MeasurementConsumerId, EventGroupId),
  UNIQUE (CmmsDataProviderId, CmmsEventGroupId),
  FOREIGN KEY(MeasurementConsumerId)
    REFERENCES MeasurementConsumers(MeasurementConsumerId)
    ON DELETE CASCADE
```



_Code quote:_
```TSQL
  PRIMARY KEY(MeasurementConsumerId, DataProviderId, EventGroupId),
  UNIQUE (MeasurementConsumerId, DataProviderId, CmmsEventGroupId),
```
___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 86 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NNsszux01fMHB4oZAr7:-NNsszux01fMHB4oZAr8:b-gboujt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f884457b6812112d623bbdc68cf7d79f69bb61cd/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L86)):*
> ```TSQL
> 
> -- changeset riemanli:create-time-intervals-table dbms:postgresql
> CREATE TABLE TimeIntervals (
> ```

Remind me why we have a separate TimeIntervals table again? A time interval just feels like pair of fields that you would duplicate wherever you need it.

This may make insertions clunky, as you have to look up whether a given time interval already exists and the only insert a new one if it doesn't.
___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 176 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NNsig7z9y-y4To-MP_4:-NNsig7z9y-y4To-MP_5:undefined) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f884457b6812112d623bbdc68cf7d79f69bb61cd/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L176)):*
> ```TSQL
>   WeightedSubsetUnionId bigint NOT NULL,
> 
>   weight bigint NOT NULL,
> ```





_Suggestion:_
```TSQL
Weight
```
___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 185 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NNsjomi17zB7TadAMDI:-NNsjnzs1GmsYUNWgIxm:bacjawj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f884457b6812112d623bbdc68cf7d79f69bb61cd/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L185)):*
> ```TSQL
> 
> -- changeset riemanli:create-primitive-reporting-set-bases-table dbms:postgresql
> CREATE TABLE PrimitiveReportingSetBases (
> ```

Just to make sure I have this right: WeightedSubsetUnions has a PK of (MeasurementConsumerId, ReportingSetId, WeightedSubsetUnionId), but this table uses PrimitiveReportingSetId. I imagine the reason is that this table is going to have one row per PrimitiveReportingSet referenced by the ReportingSet in WeightedSubsetUnions? Perhaps document that since it's not obvious.
___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 188 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NNsjrkJBk3mNCvkyc-z:-NNsjrkJBk3mNCvkyc0-:b-sp1r18) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f884457b6812112d623bbdc68cf7d79f69bb61cd/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L188)):*
> ```TSQL
>   MeasurementConsumerId bigint NOT NULL,
>   WeightedSubsetUnionId bigint NOT NULL,
>   PrimitiveReportingSetId bigint NOT NULL,
> ```

Since the keys in this PK contain the keys of the PK of PrimitiveReportingSets, you may wish to have arrange the keys so that the other table's PK is a proper prefix of this PK. Ignore this suggestion if you are more likely to look up all of these rows for a given (MeasurementConsumerId, WeightedSubsetUnionId) pair.



_Suggestion:_
```TSQL
  MeasurementConsumerId bigint NOT NULL,
  PrimitiveReportingSetId bigint NOT NULL,
  WeightedSubsetUnionId bigint NOT NULL,

  PRIMARY KEY(MeasurementConsumerId, PrimitiveReportingSetId, WeightedSubsetUnionId),
```
___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 192 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NNslhLmAjgSX5E_SnzC:-NNslhLmAjgSX5E_SnzD:ba30qk7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f884457b6812112d623bbdc68cf7d79f69bb61cd/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L192)):*
> ```TSQL
>   PRIMARY KEY(MeasurementConsumerId, WeightedSubsetUnionId, PrimitiveReportingSetId),
>   FOREIGN KEY(MeasurementConsumerId, WeightedSubsetUnionId)
>     REFERENCES WeightedSubsetUnions(MeasurementConsumerId, WeightedSubsetUnionId)
> ```

The PK of WeightedSubsetUnions is (MeasurementConsumerId, ReportingSetId, WeightedSubsetUnionId). This means that there can be more than one WeightedSubsetUnion row per (MeasurementConsumerId, WeightedSubsetUnionId) pair, as WeightedSubsetUnionId is only guaranteed to be unique for a (MeasurementConsumerId, ReportingSetId) pair.

You can avoid this problem in two ways:
* Add a UNIQUE constraint for (MeasurementConsumerId, WeightedSubsetUnionId) in WeightedSubsetUnions.
   * This would be unusual, but technically work.
* Have ReportingId as part of this table's PK, which then allows you to reference the full PK of WeightedSubsetUnions.
   *  This would be the more common option. Basically, all of your foreign key references should be by the full primary key of the row your referencing.
 
In either case, there's a subtle implication: since ReportingSetId is included in the WeightedSubsetUnions PK, it means that you could have separate entries in this table for the same PrimitiveReportingSet (e.g. if the same PrimitiveReportingSet is referenced by more than one ReportingSet). That may be intentional, but I just wanted to call it out.

Note that the same applies for PrimitiveReportingSetBasisFilters



_Code quote:_
```TSQL
WeightedSubsetUnions(MeasurementConsumerId, WeightedSubsetUnionId)
```
___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 251 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NNspPTH-RKFmTXSQd-A:-NNspPTH-RKFmTXSQd-B:b367525) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f884457b6812112d623bbdc68cf7d79f69bb61cd/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L251)):*
> ```TSQL
 [...]

2023-02-14 01:05 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835)* status: 0 of 1 files reviewed, 10 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 76 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NNshJeA7PuhiRni4min:-NOC5ojZB_YWJZcSfcYn:b2vpc1h) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f884457b6812112d623bbdc68cf7d79f69bb61cd/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L76)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

EventGroup is multi-parented with exactly one parent of each type. Therefore you can pick one to be the canonical parent and the other as just a reference.

Furthermore, each CmmsEventGroupId is only unique for a given CmmsDataProviderId.

```sql
  PRIMARY KEY(MeasurementConsumerId, EventGroupId),
  UNIQUE (DataProviderId, EventGroupId),
  UNIQUE (DataProviderId, CmmsEventGroupId),
```

That said, I'm wondering if we need a separate DataProviders table at all. It should be sufficient to have an EventGroups table that looks like this:

```sql
  MeasurementConsumerId bigint NOT NULL,
  EventGroupId bigint NOT NULL,
  CmmsDataProviderId text NOT NULL,
  CmmsEventGroupId text NOT NULL,

  PRIMARY KEY (MeasurementConsumerId, EventGroupId),
  UNIQUE (CmmsDataProviderId, CmmsEventGroupId),
  FOREIGN KEY(MeasurementConsumerId)
    REFERENCES MeasurementConsumers(MeasurementConsumerId)
    ON DELETE CASCADE
```
</blockquote></details>

What a suggestion! I love it. I wonder if `UNIQUE (MeasurementConsumerId, CmmsEventGroupId)` is also needed.
___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 86 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NNsszux01fMHB4oZAr7:-NOC7rPc-9zXk1PaLsZs:bz75w69) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f884457b6812112d623bbdc68cf7d79f69bb61cd/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L86)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Remind me why we have a separate TimeIntervals table again? A time interval just feels like pair of fields that you would duplicate wherever you need it.

This may make insertions clunky, as you have to look up whether a given time interval already exists and the only insert a new one if it doesn't.
</blockquote></details>

I was thinking not to duplicate the same data in many places as time intervals are used in models, reports, measurements, and etc., to save DB space. But I didn't realize this will make the insertion very difficult. I can remove TimeIntervals table if that's better. 
___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 176 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NNsig7z9y-y4To-MP_4:-NOC9z_j9VFnhQrcKkZm:bfhz2u7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f884457b6812112d623bbdc68cf7d79f69bb61cd/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L176)):*
> ```TSQL
>   WeightedSubsetUnionId bigint NOT NULL,
> 
>   weight bigint NOT NULL,
> ```

Thanks for catching it. Done.
___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 185 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NNsjomi17zB7TadAMDI:-NOCA_ebDzEDWmILKVRz:bhe5yn2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f884457b6812112d623bbdc68cf7d79f69bb61cd/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L185)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Just to make sure I have this right: WeightedSubsetUnions has a PK of (MeasurementConsumerId, ReportingSetId, WeightedSubsetUnionId), but this table uses PrimitiveReportingSetId. I imagine the reason is that this table is going to have one row per PrimitiveReportingSet referenced by the ReportingSet in WeightedSubsetUnions? Perhaps document that since it's not obvious.
</blockquote></details>

Thanks for the question. I think I missed an intermediate table between `WeightedSubsetUnion` and `PrimitiveReportingSetBasis` as they are many-to-many...

A `WeightedSubsetUnion` can be formulated as

```
WeightedSubsetUnions = C * Union(PrimitiveReportingSetBasis1, ..., PrimitiveReportingSetBasisN) 
```

As a result, for one `WeightedSubsetUnion`, it has multiple `PrimitiveReportingSetBases` and so multiple `PrimitiveReportingSet`. In addition, ideally one `PrimitiveReportingSetBasis` can be used in multiple `WeightedSubsetUnion`s and multiple `Measurement`s. The relationship can be seen in the diagram below.


![v2alpha DB dependency.png](https://files.reviewableusercontent.io/images/reviewable/19837081/m_jpPYH4A6jrvydsq0foOtPr/v2alpha%20DB%20dependency.png)
___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 188 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NNsjrkJBk3mNCvkyc-z:-NOCEP9q7U6e_FLu2K6l:b5ei5pk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f884457b6812112d623bbdc68cf7d79f69bb61cd/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L188)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Since the keys in this PK contain the keys of the PK of PrimitiveReportingSets, you may wish to have arrange the keys so that the other table's PK is a proper prefix of this PK. Ignore this suggestion if you are more likely to look up all of these rows for a given (MeasurementConsumerId, WeightedSubsetUnionId) pair.
</blockquote></details>

I think the sequence is ok. Please see the diagram in the other comment.
___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 192 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NNslhLmAjgSX5E_SnzC:-NOCJ01y1s3lY2YTbNCY:bu8dbjz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f884457b6812112d623bbdc68cf7d79f69bb61cd/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L192)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The PK of WeightedSubsetUnions is (MeasurementConsumerId, ReportingSetId, WeightedSubsetUnionId). This means that there can be more than one WeightedSubsetUnion row per (MeasurementConsumerId, WeightedSubsetUnionId) pair, as WeightedSubsetUnionId is only guaranteed to be unique for a (MeasurementConsumerId, ReportingSetId) pair.

You can avoid this problem in two ways:
* Add a UNIQUE constraint for (MeasurementConsumerId, WeightedSubsetUnionId) in WeightedSubsetUnions.
   * This would be unusual, but technically work.
* Have ReportingId as part of this table's PK, which then allows you to reference the full PK of WeightedSubsetUnions.
   *  This would be the more common option. Basically, all of your foreign key references should be by the full primary key of the row your referencing.
 
In either case, there's a subtle implication: since ReportingSetId is included in the WeightedSubsetUnions PK, it means that you could have separate entries in this table for the same PrimitiveReportingSet (e.g. if the same PrimitiveReportingSet is referenced by more than one ReportingSet). That may be intentional, but I just wanted to call it out.

Note that the same applies for PrimitiveReportingSetBasisFilters
</blockquot [...]

2023-02-14 22:22 UTC, SanjayVas requested changes
> Reviewed 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835)* status: all files reviewed, 10 unresolved discussions (waiting on @riemanli and @tristanvuong2021)

___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 76 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NNshJeA7PuhiRni4min:-NOGV91OEJzrsPUfixoB:be4vqs6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f884457b6812112d623bbdc68cf7d79f69bb61cd/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L76)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

What a suggestion! I love it. I wonder if `UNIQUE (MeasurementConsumerId, CmmsEventGroupId)` is also needed.
</blockquote></details>

I don't think it is. Basically what you're doing here is representing a single EventGroup in the CMMS API identified by the (CmmsDataProviderId, CmmsEventGroupId) pair with a single EventGroupId which is unique to a MeasurementConsumer. The CMMS API guarantees that each EventGroup belongs to exactly one MC.
___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 86 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NNsszux01fMHB4oZAr7:-NOGZ0EU2jQEXGE-9y9Z:b5nsyc0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f884457b6812112d623bbdc68cf7d79f69bb61cd/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L86)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

I was thinking not to duplicate the same data in many places as time intervals are used in models, reports, measurements, and etc., to save DB space. But I didn't realize this will make the insertion very difficult. I can remove TimeIntervals table if that's better. 
</blockquote></details>

Yeah, we should remove it if there's not a reason why it needs to have an ID (i.e. if it's not important that it's the same DB row). The space isn't a big concern.
___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 251 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NNspPTH-RKFmTXSQd-A:-NOGjCGT4VasXfmV8Fmf:bd2sfse) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f884457b6812112d623bbdc68cf7d79f69bb61cd/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L251)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

The reason is same as having `TimeIntervals` table. In addition, I was thinking this would be easier for later when we compare measurements which have `MetricSpec`. Please let me know if that's not correct!
</blockquote></details>

The only way I think this could help with comparison is if two equivalent `MetricSpec` messages were guaranteed to map to the same row such that you could compare their IDs as a proxy for comparing their values. To provide this guarantee, we would have the same insertion complexity as mentioned for `TimeIntervals`.
___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 176 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NOGf4mA3JzT7LuDWJpD:-NOGf4mA3JzT7LuDWJpE:b-y776zj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/db9fe46368c6033ed8d0d3ae16bd0521532647dc/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L176)):*
> ```TSQL
> 
> -- changeset riemanli:create-primitive-reporting-set-bases-table dbms:postgresql
> CREATE TABLE PrimitiveReportingSetBases (
> ```

I only now realized this is intended as the plural for "basis" (pronounced /ˈbeɪsiːz/) rather than the plural for "base" (pronounced /ˈbeɪsɪz/). Their plurals are heteronyms, both spelled "bases".



_Code quote:_
```TSQL
Bases
```
___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 191 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NOGheqP5oyEr_u1P8Gm:-NOGheqP5oyEr_u1P8Gn:bvnmnsp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/db9fe46368c6033ed8d0d3ae16bd0521532647dc/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L191)):*
> ```TSQL
>   MeasurementConsumerId bigint NOT NULL,
>   ReportingSetId bigint NOT NULL,
>   -- A WeightedSubsetUnion is a weighted union of a subset of
> ```

nit: maybe this comment belongs as on the `WeightedSubsetUnions` table, since it's describing what a row of that table represents.



_Code quote:_
```TSQL
  -- A WeightedSubsetUnion is a weighted union of a subset of
  -- PrimitiveReportingSetBases. That is, one WeightedSubsetUnion has at least
  -- one PrimitiveReportingSetBasis.
```
___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 202 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NOGid9S0rp4yEarkVXi:-NOGid9S0rp4yEarkVXj:bln2dw2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/db9fe46368c6033ed8d0d3ae16bd0521532647dc/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L202)):*
> ```TSQL
>     ON DELETE CASCADE,
>   FOREIGN KEY(MeasurementConsumerId, WeightedSubsetUnionId, PrimitiveReportingSetBasisId)
>     REFERENCES PrimitiveReportingSetBases(MeasurementConsumerId, WeightedSubsetUnionId, PrimitiveReportingSetBasisId)
> ```

I don't think `PrimitiveReportingSetBases` has this column. This is the table that defines the relationship between `WeightedSubsetUnions` and `PrimitiveReportingSetBases`.

I assume you meant to use `(MeasurementConsumerId, PrimitiveReportingSetBasisId)` (i.e. the primary key of `PrimitiveReportingSetBases`) instead?



_Code quote:_
```TSQL
WeightedSubsetUnionId
```
___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 310 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NOH-P2f2Hqk1STl92ci:-NOH-P2f2Hqk1STl92cj:b7pt4og) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/db9fe46368c6033ed8d0d3ae16bd0521532647dc/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L310)):*
> ```TSQL
>   CmmsMeasurementId text,
>   TimeIntervalId bigint NOT NULL,
>   MetricSpecId bigint NOT NULL,
> ```

Can't we get the MetricSpec from a Metric that the Measurement is associated with? (I assume all of the Metrics associated with a given Measurement will have equivalent MetricSpecs)



_Code quote:_
```TSQL
  MetricSpecId bigint NOT NULL,
```


<!-- Sent from Reviewable.io -->

2023-02-14 23:23 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835)* status: all files reviewed, 8 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 76 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NNshJeA7PuhiRni4min:-NOH3WYqEJKqxsb8fDaJ:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f884457b6812112d623bbdc68cf7d79f69bb61cd/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L76)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I don't think it is. Basically what you're doing here is representing a single EventGroup in the CMMS API identified by the (CmmsDataProviderId, CmmsEventGroupId) pair with a single EventGroupId which is unique to a MeasurementConsumer. The CMMS API guarantees that each EventGroup belongs to exactly one MC.
</blockquote></details>

Done.
___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 86 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NNsszux01fMHB4oZAr7:-NOHA2tW33bPjF3MuRTT:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f884457b6812112d623bbdc68cf7d79f69bb61cd/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L86)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Yeah, we should remove it if there's not a reason why it needs to have an ID (i.e. if it's not important that it's the same DB row). The space isn't a big concern.
</blockquote></details>

Done.
___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 251 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NNspPTH-RKFmTXSQd-A:-NOHAKjxAz6PjXn9IMtZ:bgrxk5o) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f884457b6812112d623bbdc68cf7d79f69bb61cd/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L251)):*
> compare their IDs as a proxy for comparing their values.

Yes. That's what I am thinking.

I am not sure if I should remove this one. Unlike `TimeIntervals`, `MetricSpecs` has nullable fields and can be frequently changed when we need to add more metric types or metric parameters. Having a single place for it might be easier for future modification. 

But I am not sure if the advantages outweigh the disadvantages. Would love to have your opinion Sanjay.
___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 191 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NOGheqP5oyEr_u1P8Gm:-NOH44jYDxf5O3Q95MzK:b-kih9l6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/db9fe46368c6033ed8d0d3ae16bd0521532647dc/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L191)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: maybe this comment belongs as on the `WeightedSubsetUnions` table, since it's describing what a row of that table represents.
</blockquote></details>

Got it. Done.
___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 202 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NOGid9S0rp4yEarkVXi:-NOH4LXC8_ifB02MUlkA:byp1l78) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/db9fe46368c6033ed8d0d3ae16bd0521532647dc/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L202)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I don't think `PrimitiveReportingSetBases` has this column. This is the table that defines the relationship between `WeightedSubsetUnions` and `PrimitiveReportingSetBases`.

I assume you meant to use `(MeasurementConsumerId, PrimitiveReportingSetBasisId)` (i.e. the primary key of `PrimitiveReportingSetBases`) instead?
</blockquote></details>

Yes! Sorry for the leftover code. Fixed.
___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 310 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NOH-P2f2Hqk1STl92ci:-NOH59Ry4Npb7MOkEe2W:b-2g9g1a) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/db9fe46368c6033ed8d0d3ae16bd0521532647dc/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L310)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Can't we get the MetricSpec from a Metric that the Measurement is associated with? (I assume all of the Metrics associated with a given Measurement will have equivalent MetricSpecs)
</blockquote></details>

You're right! Measurements in the reporting server are associated to at least one metric. Although measurements and metrics are many-to-many, measurements can only be associated to the metrics that are in the same metric type.
Fixed.


<!-- Sent from Reviewable.io -->

2023-02-15 00:27 UTC, SanjayVas requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @riemanli and @tristanvuong2021)

___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 251 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NNspPTH-RKFmTXSQd-A:-NOHPRuL-Bbfj4NFTBNP:b-z38j72) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f884457b6812112d623bbdc68cf7d79f69bb61cd/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L251)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

> compare their IDs as a proxy for comparing their values.

Yes. That's what I am thinking.

I am not sure if I should remove this one. Unlike `TimeIntervals`, `MetricSpecs` has nullable fields and can be frequently changed when we need to add more metric types or metric parameters. Having a single place for it might be easier for future modification. 

But I am not sure if the advantages outweigh the disadvantages. Would love to have your opinion Sanjay.
</blockquote></details>

I certainly wouldn't want to try to do the proxy equality thing, as it would mean implementing uniqueness enforcement in our application code (meaning it's even messier than the TimeIntervals case w.r.t. insertions).

As far as keeping these fields in one place, splitting out a separate table isn't really the equivalent of e.g. grouping fields into a shared message in protobuf. Having another table has other implications, for example the extra tables we then end up needing to handle relationships that have "many" on the MetricSpec end.


<!-- Sent from Reviewable.io -->

2023-02-15 19:30 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 251 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NNspPTH-RKFmTXSQd-A:-NOLK3vP22I7SvFu5TB4:b-mreqga) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f884457b6812112d623bbdc68cf7d79f69bb61cd/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L251)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I certainly wouldn't want to try to do the proxy equality thing, as it would mean implementing uniqueness enforcement in our application code (meaning it's even messier than the TimeIntervals case w.r.t. insertions).

As far as keeping these fields in one place, splitting out a separate table isn't really the equivalent of e.g. grouping fields into a shared message in protobuf. Having another table has other implications, for example the extra tables we then end up needing to handle relationships that have "many" on the MetricSpec end.
</blockquote></details>

Got it. Removed `MetricSpecs`. Please let me know if the modification for `ModelMetricSpecs` and `ModelInferenceCalculationMetricSpecs` is correct.


<!-- Sent from Reviewable.io -->

2023-02-15 20:30 UTC, SanjayVas requested changes
> Reviewed 1 of 1 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835)* status: all files reviewed, 7 unresolved discussions (waiting on @riemanli and @tristanvuong2021)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NOLibeQERWRKJsDGg5A:-NOLibeQERWRKJsDGg5B:bx2mfrz) (no related file):*
Where do we reference the actual underlying model (e.g. some saved model blob key)?

___
___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 101 at r14](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NOLjT1k5v_3rEb5dCD_:-NOLjT1k5v_3rEb5dCDa:b-nveu20) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/790e4ce9c172a661da3fc0313286fa8681256bcf/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L101)):*
> ```TSQL
> CREATE TABLE PrimitiveReportingSetEventGroups(
>   MeasurementConsumerId bigint NOT NULL,
>   EventGroupId bigint NOT NULL,
> ```

nit: arrange these columns in the order they appear in the primary key



_Code quote:_
```TSQL
  MeasurementConsumerId bigint NOT NULL,
  EventGroupId bigint NOT NULL,
  PrimitiveReportingSetId bigint NOT NULL,
```
___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 123 at r14](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NOLkM8WBBSd77TSC2-e:-NOLkM8WBBSd77TSC2-f:bidm88y) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/790e4ce9c172a661da3fc0313286fa8681256bcf/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L123)):*
> ```TSQL
>   Filter text,
> 
>   -- Exactly one of (CompositeReportingSet, PrimitiveReportingSet) must be
> ```

I'm actually thinking we don't need separate CompositeReportingSets and PrimitiveReportingSets tables. Instead just have an optional SetExpressionId here. Each ReportingSets row would *either* have a SetExpressionId *or* have rows in the `ReportingSetEventGroups` table.



_Code quote:_
```TSQL
  -- Exactly one of (CompositeReportingSet, PrimitiveReportingSet) must be
  -- non-null
  CompositeReportingSetId bigint,
  PrimitiveReportingSetId bigint,
```
___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 517 at r14](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NOLfHyg6zRkaTW86NUS:-NOLfHyg6zRkaTW86NUT:bru31xu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/790e4ce9c172a661da3fc0313286fa8681256bcf/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L517)):*
> ```TSQL
>   ModelInferenceCalculationMetricSpecId bigint NOT NULL,
> 
>   -- org.wfanet.measurement.internal.reporting.MetricSpec.MetricType
> ```

Shouldn't this have a reference to a `ModelMetricSpecs` row instead? I assumed what we're trying to do is link the ModelInferenceCalculation to the appropriate item under the Model.

This would mean moving the `ModelId` column here from `ModelInferenceCalculations` so that you can have a foreign key reference. I think you could even then drop `ModelInferenceCalculationMetricSpecId` and make the PK the combination of the `ModelInferenceCalculations` PK and the `ModelMetricSpecs` PK, assuming that each ModelMetricSpec is only referenced once per ModelInferenceCalculation.



_Code quote:_
```TSQL
  -- org.wfanet.measurement.internal.reporting.MetricSpec.MetricType
  -- protobuf enum encoded as an integer.
  MetricType integer NOT NULL,

  -- Must not be NULL if MetricType is FREQUENCY_HISTOGRAM or IMPRESSION_COUNT
  MaximumFrequencyPerUser bigint,
  -- Must not be NULL if MetricType is WATCH_DURATION
  MaximumWatchDurationPerUser bigint,
```


<!-- Sent from Reviewable.io -->

2023-02-15 22:07 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835)* status: all files reviewed, 6 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NOLibeQERWRKJsDGg5A:-NOLxY8d6OizfH09LDsC:b-wyhxiw) (no related file):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Where do we reference the actual underlying model (e.g. some saved model blob key)?
</blockquote></details>

That's a good question. My thought is store the actual models under `Details` in the model row. I am not sure what blob key is. Maybe it's better.

___
___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 123 at r14](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NOLkM8WBBSd77TSC2-e:-NOLvDJ9-dIZ8Ycvn9Uh:b-wdfzen) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/790e4ce9c172a661da3fc0313286fa8681256bcf/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L123)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I'm actually thinking we don't need separate CompositeReportingSets and PrimitiveReportingSets tables. Instead just have an optional SetExpressionId here. Each ReportingSets row would *either* have a SetExpressionId *or* have rows in the `ReportingSetEventGroups` table.
</blockquote></details>

That's a good idea! I'll keep `PrimitiveReportingSetBases` but make its foreign key be `ReportingSet`.
___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 517 at r14](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NOLfHyg6zRkaTW86NUS:-NOM60juEkrP8DPdHzgL:b3g3kdu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/790e4ce9c172a661da3fc0313286fa8681256bcf/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L517)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Shouldn't this have a reference to a `ModelMetricSpecs` row instead? I assumed what we're trying to do is link the ModelInferenceCalculation to the appropriate item under the Model.

This would mean moving the `ModelId` column here from `ModelInferenceCalculations` so that you can have a foreign key reference. I think you could even then drop `ModelInferenceCalculationMetricSpecId` and make the PK the combination of the `ModelInferenceCalculations` PK and the `ModelMetricSpecs` PK, assuming that each ModelMetricSpec is only referenced once per ModelInferenceCalculation.
</blockquote></details>

That's neat! Like how you trim the schema. 
Modified.


<!-- Sent from Reviewable.io -->

2023-02-15 23:28 UTC, SanjayVas requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835)* status: 0 of 1 files reviewed, 7 unresolved discussions (waiting on @riemanli and @tristanvuong2021)

___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 210 at r15](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NOMOjLaD7mi9EFHPsbr:-NOMOjLaD7mi9EFHPsbs:b-xhkgt3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1996d48bdf715fb362d901c058ec0d5c3ff427c9/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L210)):*
> ```TSQL
>   ReportingSetId bigint NOT NULL,
> 
>   TimeIntervalStart TIMESTAMP NOT NULL,
> ```

We might need to use `TIMESTAMP WITH TIME ZONE`. We map protobuf Timestamps to Java Instants. Postgres R2DBC maps Instant to `timestamp with time zone`.

See https://github.com/pgjdbc/r2dbc-postgresql#data-type-mapping



_Code quote:_
```TSQL
TIMESTAMP
```


<!-- Sent from Reviewable.io -->

2023-02-16 03:35 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835)* status: 0 of 1 files reviewed, 7 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 210 at r15](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NOMOjLaD7mi9EFHPsbr:-NOMi2NmAzlsjpktg2Gd:by2ivt6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1996d48bdf715fb362d901c058ec0d5c3ff427c9/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L210)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

We might need to use `TIMESTAMP WITH TIME ZONE`. We map protobuf Timestamps to Java Instants. Postgres R2DBC maps Instant to `timestamp with time zone`.

See https://github.com/pgjdbc/r2dbc-postgresql#data-type-mapping
</blockquote></details>

Got it. Thanks for pointing that out! 


<!-- Sent from Reviewable.io -->

2023-02-17 20:06 UTC, SanjayVas requested changes
> Reviewed 1 of 1 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835)* status: all files reviewed, 7 unresolved discussions (waiting on @riemanli and @tristanvuong2021)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NOLibeQERWRKJsDGg5A:-NOVwkhs5_o6xKTe1g46:b-7v7shm) (no related file):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

That's a good question. My thought is store the actual models under `Details` in the model row. I am not sure what blob key is. Maybe it's better.
</blockquote></details>

It basically depends on how big the models are. If they are reasonably large, then we will want to put them in blob storage. We would therefore just store the blob key in the DB.

The main point of my question is that I was trying to figure out which table would hold the model. I thought you explained that in truth there would be one model per time interval and per metric spec, and the Model rows in this table actually represent sets of models. Therefore I expected some table that references the Model, metric spec, and time interval.

___
___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 79 at r16](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NOVux-REws-DriROIz0:-NOVux-REws-DriROIz1:b35m5i9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e55f54c7dcc12d28d81e6af865fc2110ff4ef9f8/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L79)):*
> ```TSQL
>   Filter text,
> 
>   -- Must be set when the reporting set is composite.
> ```

nit: we can be more clear here on the implications



_Suggestion:_
```TSQL
If not NULL then the ReportingSet is a composite one, and will therefore have no corresponding rows in ReportingSetEventGroups.
```
___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 462 at r16](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NOVvqf9D1iUU6CUOgSZ:-NOVvqf9D1iUU6CUOgS_:b-eiq3ku) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e55f54c7dcc12d28d81e6af865fc2110ff4ef9f8/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L462)):*
> ```TSQL
>   ModelInferenceCalculationId bigint NOT NULL,
>   ReportingSetId bigint NOT NULL,
>   ModelId bigint NOT NULL,
> ```

Drop this column since it's now in all of the child `ModelInferenceCalculationModelMetricSpecs` rows.



_Code quote:_
```TSQL
  ModelId bigint NOT NULL,
```
___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 485 at r16](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NOVwOo70Xo_4mTdR0UB:-NOVwOo70Xo_4mTdR0UC:bs2nd22) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e55f54c7dcc12d28d81e6af865fc2110ff4ef9f8/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L485)):*
> ```TSQL
>   ReportId bigint NOT NULL,
>   ModelInferenceCalculationId bigint NOT NULL,
>   ModelId bigint NOT NULL,
> ```

nit: Maybe add a note here that ModelId will be the same for all rows with the same (MeasurementConsumerId, ReportId, ModelInferenceCalculationId)


<!-- Sent from Reviewable.io -->

2023-02-17 23:28 UTC, SanjayVas requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835)* status: all files reviewed, 8 unresolved discussions (waiting on @riemanli and @tristanvuong2021)

___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 132 at r16](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NOWh6XD11q6q5_dOt_Z:-NOWh6XD11q6q5_dOt__:bqwk1w) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e55f54c7dcc12d28d81e6af865fc2110ff4ef9f8/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L132)):*
> ```TSQL
>   ReportingSetId bigint NOT NULL,
> 
>   PRIMARY KEY(MeasurementConsumerId, PrimitiveReportingSetBasisId),
> ```

Why is this not `(MeasurementConsumerId, ReportingSetId, PrimitiveReportingSetBasisId)`?



_Code quote:_
```TSQL
(MeasurementConsumerId, PrimitiveReportingSetBasisId)
```


<!-- Sent from Reviewable.io -->

2023-02-18 01:12 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835)* status: 0 of 1 files reviewed, 7 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NOLibeQERWRKJsDGg5A:-NOWPdsC95WWLiyqKQuH:b2z87c8) (no related file):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

It basically depends on how big the models are. If they are reasonably large, then we will want to put them in blob storage. We would therefore just store the blob key in the DB.

The main point of my question is that I was trying to figure out which table would hold the model. I thought you explained that in truth there would be one model per time interval and per metric spec, and the Model rows in this table actually represent sets of models. Therefore I expected some table that references the Model, metric spec, and time interval.
</blockquote></details>

I think you're right, I added another table for sub-models. 

With that new table, I wonder if we could get rid of `ModelMetricSpecs` table and `ModelTimeIntervals` table. The reason I am not sure is that given a model ID, there are multiple duplicate `MetricSpecs` and multiple duplicate `TimeIntervals`. It will make querying what time intervals a model covers difficult, right?

___
___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 79 at r16](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NOVux-REws-DriROIz0:-NOWRagE7VPFGvu0i_xZ:b-yewsqm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e55f54c7dcc12d28d81e6af865fc2110ff4ef9f8/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L79)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: we can be more clear here on the implications
</blockquote></details>

Thanks for adding to clarify it. Done.
___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 132 at r16](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NOWh6XD11q6q5_dOt_Z:-NOWuIfRC-tWn7ncz4PZ:be7nw9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e55f54c7dcc12d28d81e6af865fc2110ff4ef9f8/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L132)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Why is this not `(MeasurementConsumerId, ReportingSetId, PrimitiveReportingSetBasisId)`?
</blockquote></details>

After rethinking about it, I kind of want to kind the current way because `ReportingSetId` here is not the parent of `PrimitiveReportingSetBasis`. The relationship is:
* ReportingSet --> multiple PrimitiveReportingSetBases. 
* PrimitiveReportingSetBasis --> ReportingSet(PrimitiveReportingSet) + Filters.

I think I should rename `ReportingSet` to `PrimitiveReportingSetId` to make it less confusing.
___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 462 at r16](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NOVvqf9D1iUU6CUOgSZ:-NOWSI00AItyJ_P7w1ox:boj1qgt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e55f54c7dcc12d28d81e6af865fc2110ff4ef9f8/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L462)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Drop this column since it's now in all of the child `ModelInferenceCalculationModelMetricSpecs` rows.
</blockquote></details>

Good catch. Done.


<!-- Sent from Reviewable.io -->

2023-02-21 19:12 UTC, SanjayVas requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @riemanli and @tristanvuong2021)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NOLibeQERWRKJsDGg5A:-NOpCCnr7_CVPXGxnwOu:b54ofal) (no related file):*
> given a model ID, there are multiple duplicate `MetricSpecs` and multiple duplicate `TimeIntervals`.

Assuming that for a single row in Models, you need *n* X *m* `ModelSubsets` rows where *n* is the number of MetricSpecs and *m* is the number of TimeIntervals. Would that not mean that for a single row in Models, each `MetricSpecs` row and each `ModelTimeIntervals` row would be distinct?

Now given that `ModelSubsets` is just forming the cross-product between MetricSpecs and TimeIntervals, you can certainly drop one of the corresponding tables (`ModelTimeIntervals`) and fold its data into `ModelSubsets`. Indeed you could do that with both tables. The question I have is whether `ModelMetricSpecs` has any additional value w.r.t. `ModelInferenceCalculations`. Right now you have a `ModelInferenceCalculationModelMetricSpecs` table. Assuming that's the right cardinality and you wouldn't rather reference `ModelSubsets` (i.e. you don't need a separate row per TimeInterval), then it may be worth keeping `ModelMetricSpecs`.

___
___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 132 at r16](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NOWh6XD11q6q5_dOt_Z:-NOpI7VM-MaasGdCx2Fg:b-xl8prx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e55f54c7dcc12d28d81e6af865fc2110ff4ef9f8/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L132)):*
I'm confused on the rename. If your table introduces a new ID column, it should use the name of a singular table row. Therefore if the table is `PrimitiveReportingSetBases`, then the ID column should be `PrimitiveReportingSetBasisId`.

> ReportingSet --> multiple PrimitiveReportingSetBases.

This still sounds like a `PrimitiveReportingSetBases` row is a child of a `ReportingSets` row.

If I understand the relationships correctly, what you're effectively trying to describe is a traversal from a root (possibly composite) `ReportingSets` row to leaf (primitive) `ReportingSets` row. This is something that can be derived from the `ReportingSets`table, but you need separate tables so you can associate traversals with weights. The `ReportingSets` row that would be the parent of a given `PrimitiveReportingSetBases` row is the root, not the leaf.


<!-- Sent from Reviewable.io -->

2023-02-22 18:41 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NOLibeQERWRKJsDGg5A:-NOpUwjM-hMqPLJcTihE:b-rrpklb) (no related file):*
> Would that not mean that for a single row in Models, each `MetricSpecs` row and each `ModelTimeIntervals` row would be distinct?

`ModelMetricSpecs` rows for the same modelId would be distinct. Same for `ModelTimeIntervals`. But they are not distinct in `ModelSubsets` for the same modelId. Ex:

```
modelId1 modelMetricSpecId1 modelTimeIntervalId1
modelId1 modelMetricSpecId1 modelTimeIntervalId2
                                  ...
modelId1 modelMetricSpecId1 modelTimeIntervalIdM
modelId1 modelMetricSpecId2 modelTimeIntervalId1
                                  ...
modelId1 modelMetricSpecId2 modelTimeIntervalIdM
                                  ...
modelId1 modelMetricSpecIdN modelTimeIntervalIdM
```

> You can certainly drop one of the corresponding tables (`ModelTimeIntervals`) and fold its data into `ModelSubsets`. Indeed you could do that with both tables. 

Good point. I will drop `ModelTimeIntervals`.

> you wouldn't rather reference `ModelSubsets` (i.e. you don't need a separate row per `TimeInterval`)

That's right. A `ModelInferenceCalculations` row contains all time intervals defined in the corresponding row of `Report`.

___
___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 132 at r16](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NOWh6XD11q6q5_dOt_Z:-NOpSVBe1WUEm1YrKA3r:b-4osxta) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e55f54c7dcc12d28d81e6af865fc2110ff4ef9f8/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L132)):*
> If your table introduces a new ID column, it should use the name of a singular table row.

But we use `LeftHandSetExpressionId` and `LeftHandReportingSetId` for more meaningful names. Does that mean we should not do that also?

Sorry let me show the exact traversal:

Root `ReportingSet` --> multiple rows in `WeightedSubsetUnions`, and for each row --> multiple rows in `PrimitiveReportingSetBases`, and for each row --> one row of leaf (primitive) `ReportingSets` + multiple rows in `PrimitiveReportingSetBasisFilters`.

So, a row of `WeightedSubsetUnions` is the parent of a `PrimitiveReportingSetBases` row, which is already captured by `WeightedSubsetUnionPrimitiveReportingSetBases`. On the other hand, for the relationship between a `PrimitiveReportingSetBases` row and a row of leaf (primitive) `ReportingSets`, I represent it by adding `PrimitiveReportingSetId` field to `PrimitiveReportingSetBases`.


<!-- Sent from Reviewable.io -->

2023-02-22 20:19 UTC, SanjayVas requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @riemanli and @tristanvuong2021)

___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 132 at r16](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NOWh6XD11q6q5_dOt_Z:-NOuZONL9X5hpGEgQlaQ:bvkwz21) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e55f54c7dcc12d28d81e6af865fc2110ff4ef9f8/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L132)):*
> > If your table introduces a new ID column, it should use the name of a singular table row.
>
> But we use `LeftHandSetExpressionId` and `LeftHandReportingSetId` for more meaningful names. Does that mean we should not do that also?

By "introduces a new ID column", I meant for the primary key of the table specifically. When you have a parent-child relationship, the prefix of the primary key of the child is the primary key of the parent. It sounds like the ReportingSet ID you are referencing is the leaf rather than the root, so it is not a parent.

> So, a row of `WeightedSubsetUnions` is the parent of a `PrimitiveReportingSetBases` row, which is already captured by `WeightedSubsetUnionPrimitiveReportingSetBases`.

When you have a parent-child relationship, it means that each child row belongs to exactly one parent row. If that were the case, then you wouldn't need the `WeightedSubsetUnionPrimitiveReportingSetBases` table and could instead have the PK prefix of `PrimitiveReportingSetBases` be the PK of `WeightedSubsetUnions`.


<!-- Sent from Reviewable.io -->

2023-02-22 21:38 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 132 at r16](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NOWh6XD11q6q5_dOt_Z:-NOv22Hj44YFHllvq3Vb:b-rjihok) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e55f54c7dcc12d28d81e6af865fc2110ff4ef9f8/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L132)):*
> It sounds like the ReportingSet ID you are referencing is the leaf rather than the root, so it is not a parent.

Right. And I think it's same for `PrimitiveReportingSetId` in `PrimitiveReportingSetBases` because it's not a parent, and so we don't need it in the PK. Does that make sense to you?

> When you have a parent-child relationship, it means that each child row belongs to exactly one parent row.

I see. Then it's not a parent-child but a many-to-many relationship for `WeightedSubsetUnions` and `PrimitiveReportingSetBases`. Sorry for the confusion!


<!-- Sent from Reviewable.io -->

2023-02-22 23:57 UTC, SanjayVas requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @riemanli and @tristanvuong2021)

___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 132 at r16](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NOWh6XD11q6q5_dOt_Z:-NOvWdew1NrAuxsWWgMl:bizdnlm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e55f54c7dcc12d28d81e6af865fc2110ff4ef9f8/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L132)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

> It sounds like the ReportingSet ID you are referencing is the leaf rather than the root, so it is not a parent.

Right. And I think it's same for `PrimitiveReportingSetId` in `PrimitiveReportingSetBases` because it's not a parent, and so we don't need it in the PK. Does that make sense to you?

> When you have a parent-child relationship, it means that each child row belongs to exactly one parent row.

I see. Then it's not a parent-child but a many-to-many relationship for `WeightedSubsetUnions` and `PrimitiveReportingSetBases`. Sorry for the confusion!
</blockquote></details>

So just to make sure my understanding is correct, `PrimitiveReportingSetBases` are traversals of root to leaf (primitive) ReportingSets. A `WeightedSubsetUnions` row indicates the root `ReportingSets` row and the weight associated with the traversal. The `WeightedSubsetUnionPrimitiveReportingSetBases` table lists the traversals for each root/weight. The `PrimitiveReportingSetBasisFilters` table is the result of the traversal, i.e. the collection of filters that result from that traversal of root to leaf.

If that's true, then this structure is fine. We just might want to at minimum document this in terms of ReportingSet traversals (paths?). Possibly even changing the table names, though that depends on whether the concepts of subset unions and bases are referenced elsewhere (e.g. if they come from the set expression compilation algorithm).


<!-- Sent from Reviewable.io -->

2023-02-23 00:52 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 132 at r16](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NOWh6XD11q6q5_dOt_Z:-NOvgxdTDpD15DMlicl2:b-hskd4k) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e55f54c7dcc12d28d81e6af865fc2110ff4ef9f8/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L132)):*
> So just to make sure my understanding is correct, PrimitiveReportingSetBases are traversals of root to leaf (primitive) ReportingSets. A WeightedSubsetUnions row indicates the root ReportingSets row and the weight associated with the traversal. The WeightedSubsetUnionPrimitiveReportingSetBases table lists the traversals for each root/weight. The PrimitiveReportingSetBasisFilters table is the result of the traversal, i.e. the collection of filters that result from that traversal of root to leaf.

That is correct.

Subset unions is from set expression compilation, and primitive reporting set bases is from set expression expansion. They both are referenced in a few other places.

Add some comments to explain the traversals. 


<!-- Sent from Reviewable.io -->

2023-02-23 01:28 UTC, SanjayVas requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @riemanli and @tristanvuong2021)

___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 72 at r19](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NOvlEvgBSWYR_pzQV_H:-NOvlEvgBSWYR_pzQV_I:b-m5jl92) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3a1a806386089257693525f950315e3aa6930c5e/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L72)):*
> ```TSQL
> -- The traversal of a reporting set from the root:
> -- row in ReportingSets --> multiple rows in WeightedSubsetUnions, and for each
> -- row --> multiple rows in PrimitiveReportingSetBases, and for each row --> one
> ```

This can be made clearer.

The points to note are that:
* ReportingSets rows which have NULL SetExpressionId are referred to as "primitive", and those that have a non-NULL SetExpressionId are referred to as "complex".
* Each row in the ReportingSets table is a vertex of a directed graph, where the SetExpressions table describes the edges.
* Primitive ReportingSets rows are leaf vertices, i.e. they have no outgoing edges.
* A WeightedSubsetUnions row indicates the ReportingSets row vertex that is the start of a graph path.
* A PrimitiveReportingSetBases row indicates a primitive ReportingSets row vertex that is the end of a graph path. Note that the path may have zero edges, in which case the WeightedSubsetUnions row and the PrimitiveReportingSetBases row indicate the same vertex.
* The PrimitiveReportingSetBasisFilters table contains the collection of filters formed by visiting each vertex on the graph path.

Note that I am slightly confused about one thing: there are multiple paths that end at a given leaf vertex. I'm not certain how this is captured via PrimitiveReportingSetBasisFilters, as it only references the end of the path and not the start. Furthermore, do you need to account for the possibility of having multiple paths from a given start vertex to the same end vertex?



_Code quote:_
```TSQL
-- The traversal of a reporting set from the root:
-- row in ReportingSets --> multiple rows in WeightedSubsetUnions, and for each
-- row --> multiple rows in PrimitiveReportingSetBases, and for each row --> one
-- row of leaf (primitive) ReportingSets + multiple rows in
-- PrimitiveReportingSetBasisFilters.
```


<!-- Sent from Reviewable.io -->

2023-02-23 21:37 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 72 at r19](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NOvlEvgBSWYR_pzQV_H:-NP-CFD07L1upoLKOVEu:b52nuvh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3a1a806386089257693525f950315e3aa6930c5e/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L72)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> Note that I am slightly confused about one thing: there are multiple paths that end at a given leaf vertex. I'm not certain how this is captured via PrimitiveReportingSetBasisFilters, as it only references the end of the path and not the start. Furthermore, do you need to account for the possibility of having multiple paths from a given start vertex to the same end vertex?

I realized my mistake. You can have multiple PrimitiveReportingSetBases rows for a given leaf vertex, such that you have a PrimitiveReportingSetBases row per graph path.
</blockquote></details>

Thanks for the summary Sanjay!


<!-- Sent from Reviewable.io -->

2023-02-24 00:52 UTC, SanjayVas requested changes
> Reviewed 1 of 1 files at r20, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835)* status: all files reviewed, 4 unresolved discussions (waiting on @riemanli and @tristanvuong2021)

___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 260 at r20](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NP-tB1T-hHwrPuUipW1:-NP-tB1T-hHwrPuUipW2:bojjfav) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/41d07b64780b24d4db3d45e51106c4b5208e99e5/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L260)):*
> ```TSQL
>   MeasurementConsumerId bigint NOT NULL,
>   MeasurementId bigint NOT NULL,
>   CmmsCreateMeasurementRequestId text NOT NULL,
> ```

This should be unique. Postgres has a `uuid` data type which we may want to use.


<!-- Sent from Reviewable.io -->

2023-02-24 05:23 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835)* status: all files reviewed, 4 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 260 at r20](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NP-tB1T-hHwrPuUipW1:-NP0rco22cbFlmgzTwrN:b-bjudbj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/41d07b64780b24d4db3d45e51106c4b5208e99e5/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L260)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This should be unique. Postgres has a `uuid` data type which we may want to use.
</blockquote></details>

Thanks for the suggestion! Done.



_Code quote:_
```TSQL
CmmsCreateMeasurementRequestId
```


<!-- Sent from Reviewable.io -->

2023-02-25 00:11 UTC, SanjayVas approved these changes
> Reviewed 1 of 1 files at r21, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835)* status: all files reviewed, 3 unresolved discussions (waiting on @tristanvuong2021)



<!-- Sent from Reviewable.io -->

2023-03-07 20:19 UTC, tristanvuong2021 requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @riemanli, @SanjayVas, and @stevenwarejones)

___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 136 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NPxiZCzClLb8QVJD7Bj:-NPxiZCzClLb8QVJD7Bk:b-rs7h8w) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/db9fe46368c6033ed8d0d3ae16bd0521532647dc/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L136)):*
> ```TSQL
>   ReportingSetId bigint NOT NULL,
> 
>   ExternalReportingSetId bigint NOT NULL,
> ```

Should have an index on (MeasurementConsumerId, ExternalReportingSetID) for searching by external id.
___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 277 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NPxiDFu6BoF07BaniJI:-NPxiDFu6BoF07BaniJJ:bdgk0hp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/db9fe46368c6033ed8d0d3ae16bd0521532647dc/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L277)):*
> ```TSQL
> 
> -- changeset riemanli:create-metrics-table dbms:postgresql
> CREATE TABLE Metrics (
> ```

Metrics is missing the ExternalMetricId. Should also have an index on (MeasurementConsumerId, ExternalMetricID) for searching by external id.


<!-- Sent from Reviewable.io -->

2023-03-07 20:25 UTC, tristanvuong2021 commented
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 136 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NPxiZCzClLb8QVJD7Bj:-NPxk1WlAMhWp4fYughz:b5bg6ff) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/db9fe46368c6033ed8d0d3ae16bd0521532647dc/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L136)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Should have an index on (MeasurementConsumerId, ExternalReportingSetID) for searching by external id.
</blockquote></details>

Nevermind, forgot about the UNIQUE.


<!-- Sent from Reviewable.io -->

2023-03-07 20:45 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @SanjayVas, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 277 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NPxiDFu6BoF07BaniJI:-NPxoTKE5u4idiNLDllw:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/db9fe46368c6033ed8d0d3ae16bd0521532647dc/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L277)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Metrics is missing the ExternalMetricId. Should also have an index on (MeasurementConsumerId, ExternalMetricID) for searching by external id.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-03-09 00:27 UTC, SanjayVas requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @riemanli, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 220 at r23](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NQ2l1haEk7Pr8sOBHYV:-NQ2l1haEk7Pr8sOBHYW:undefined) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4321c0ef6e60b76c1762ee9d82b1c1daa3ca2707/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L220)):*
> ```TSQL
>   ReportingSetId bigint NOT NULL,
> 
>   externalMetricId bigint NOT NULL,
> ```





_Suggestion:_
```TSQL
ExternalMetricId
```


<!-- Sent from Reviewable.io -->

2023-03-09 00:41 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @SanjayVas, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 220 at r23](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NQ2l1haEk7Pr8sOBHYV:-NQ2oCzhDySDRTYBaxVO:bfhz2u7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4321c0ef6e60b76c1762ee9d82b1c1daa3ca2707/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L220)):*
> ```TSQL
>   ReportingSetId bigint NOT NULL,
> 
>   externalMetricId bigint NOT NULL,
> ```

Thanks for catching it. Done.


<!-- Sent from Reviewable.io -->

2023-03-09 01:15 UTC, SanjayVas approved these changes
> Reviewed 1 of 1 files at r24, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835)* status: all files reviewed, 2 unresolved discussions (waiting on @riemanli, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 217 at r24](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NQ2vnIJ9MsFbJzuAP1E:-NQ2vnIJ9MsFbJzuAP1F:balgajk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ddae9e7d1038b056f3d20020bfb5e34a624bf21c/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L217)):*
> ```TSQL
>   MeasurementConsumerId bigint NOT NULL,
>   MetricId bigint NOT NULL,
>   MetricIdempotencyKey text NOT NULL,
> ```

nit: do we want to restrict the create request ID to be a UUID in the public API? If so, then we can change this to the `uuid` type.



_Code quote:_
```TSQL
text
```


<!-- Sent from Reviewable.io -->

2023-03-09 01:20 UTC, SanjayVas approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones and @tristanvuong2021)

___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 217 at r24](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NQ2vnIJ9MsFbJzuAP1E:-NQ2wqKp5dhVTF2PF86z:bvh1n35) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ddae9e7d1038b056f3d20020bfb5e34a624bf21c/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L217)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: do we want to restrict the create request ID to be a UUID in the public API? If so, then we can change this to the `uuid` type.
</blockquote></details>

Actually let's not restrict it. There are useful reasons to allow other types. e.g. in the CMMS API, our EDP simulator uses the type URL as the request ID when creating metadata descriptors.


<!-- Sent from Reviewable.io -->

2023-03-09 01:30 UTC, SanjayVas requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835)* status: all files reviewed, 2 unresolved discussions (waiting on @riemanli, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 217 at r24](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NQ2z7XKBS1zwyM74A57:-NQ2z7XKBS1zwyM74A58:bosbfiz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ddae9e7d1038b056f3d20020bfb5e34a624bf21c/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L217)):*
> ```TSQL
>   MeasurementConsumerId bigint NOT NULL,
>   MetricId bigint NOT NULL,
>   MetricIdempotencyKey text NOT NULL,
> ```

Let's rename this to be more explicit. I know it it's the choice I made in world-federation-of-advertisers/cross-media-measurement#785, but I think it will be clearer this way. For example, if we end up having to support idempotent requests for methods other than Create, we'll need to persist those IDs too.



_Suggestion:_
```TSQL
CreateMetricRequestId
```


<!-- Sent from Reviewable.io -->

2023-03-09 04:20 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @SanjayVas, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 217 at r24](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NQ2z7XKBS1zwyM74A57:-NQ3a9SLBo5hRmhuz5K_:b-a9hy1e) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ddae9e7d1038b056f3d20020bfb5e34a624bf21c/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L217)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Let's rename this to be more explicit. I know it it's the choice I made in world-federation-of-advertisers/cross-media-measurement#785, but I think it will be clearer this way. For example, if we end up having to support idempotent requests for methods other than Create, we'll need to persist those IDs too.
</blockquote></details>

cc: @tristanvuong2021 

Done.


<!-- Sent from Reviewable.io -->

2023-03-16 17:46 UTC, SanjayVas approved these changes
> Reviewed 1 of 1 files at r27, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones and @tristanvuong2021)



<!-- Sent from Reviewable.io -->

2023-03-16 18:02 UTC, tristanvuong2021 requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835)* status: all files reviewed, 1 unresolved discussion (waiting on @riemanli and @stevenwarejones)

___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 462 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NQf_Nof6zKQcTfg24ki:-NQf_Nof6zKQcTfg24kj:b-wapg0b) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/db9fe46368c6033ed8d0d3ae16bd0521532647dc/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L462)):*
> ```TSQL
>   -- Serialized org.wfanet.measurement.internal.reporting.Report.Details
>   -- protobuf message.
>   ReportDetails bytea NOT NULL,
> ```

As of right now, there is no details message so this can be removed. We can always add a new column later if there ends up being a details message.


<!-- Sent from Reviewable.io -->

2023-03-16 20:05 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @SanjayVas, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 462 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NQf_Nof6zKQcTfg24ki:-NQg0itI1wF3d31gEry2:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/db9fe46368c6033ed8d0d3ae16bd0521532647dc/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L462)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

As of right now, there is no details message so this can be removed. We can always add a new column later if there ends up being a details message.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-03-17 15:18 UTC, stevenwarejones requested changes
> Reviewed 1 of 1 files at r28.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835)* status: all files reviewed (commit messages unreviewed), 4 unresolved discussions (waiting on @riemanli and @tristanvuong2021)

___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 248 at r28](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NQk8-P9D-e63a4zALKl:-NQk8-P9D-e63a4zALKm:b-lj1od) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c4a70f8f17e71a72d3bd130a03479f57ed6b98d7/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L248)):*
> ```TSQL
>   -- Serialized org.wfanet.measurement.internal.reporting.Metric.Details
>   -- protobuf message.
>   MetricDetails bytea NOT NULL,
> ```

wdyt about storing json versions for easy debugging?
___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 278 at r28](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NQk7v-v-tTCu3_CfWw_:-NQk7v-w2IGhVYobRga4:b-m8zqnk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c4a70f8f17e71a72d3bd130a03479f57ed6b98d7/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L278)):*
> ```TSQL
>   -- Serialized org.wfanet.measurement.internal.reporting.Measurement.Result
>   -- protobuf message.
>   Result bytea,
> ```

ditto on storing json
___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 360 at r28](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NQk8_kxBfzcBEW5k9f7:-NQk8_kxBfzcBEW5k9f8:b2t7o3y) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c4a70f8f17e71a72d3bd130a03479f57ed6b98d7/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L360)):*
> ```TSQL
>   -- Serialized org.wfanet.measurement.internal.reporting.Report.MetricCalculation.Details
>   -- protobuf message.
>   MetricCalculationDetails bytea NOT NULL,
> ```

ditto on json


<!-- Sent from Reviewable.io -->

2023-03-17 23:56 UTC, SanjayVas reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835)* status: all files reviewed (commit messages unreviewed), 4 unresolved discussions (waiting on @riemanli, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 248 at r28](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NQk8-P9D-e63a4zALKl:-NQlyhs6EwfqAqxcCtPq:b-5g12yz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c4a70f8f17e71a72d3bd130a03479f57ed6b98d7/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L248)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

wdyt about storing json versions for easy debugging?
</blockquote></details>

To clarify @stevenwarejones's comment, this is something we do in the Kingdom DB. We have separate binary and JSON columns, where the binary one is canonical and the JSON one is just a copy of the binary one with JSON serialization. We do this to make it easier to do debugging via querying the database directly.

The reason we keep the binary one as canonical is that deserializing that format is more efficient, standardized, and allows us more flexibility in message evolution (e.g. being able to rename fields). If space becomes an issue, we can simply drop all of the JSON copies.

It seems reasonable to follow the same approach here.


<!-- Sent from Reviewable.io -->

2023-03-20 17:53 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @stevenwarejones and @tristanvuong2021)

___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 248 at r28](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NQk8-P9D-e63a4zALKl:-NR-8vhS3Zw45_sNYQDN:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c4a70f8f17e71a72d3bd130a03479f57ed6b98d7/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L248)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

To clarify @stevenwarejones's comment, this is something we do in the Kingdom DB. We have separate binary and JSON columns, where the binary one is canonical and the JSON one is just a copy of the binary one with JSON serialization. We do this to make it easier to do debugging via querying the database directly.

The reason we keep the binary one as canonical is that deserializing that format is more efficient, standardized, and allows us more flexibility in message evolution (e.g. being able to rename fields). If space becomes an issue, we can simply drop all of the JSON copies.

It seems reasonable to follow the same approach here.
</blockquote></details>

Done.
___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 278 at r28](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NQk7v-v-tTCu3_CfWw_:-NR-8wAp0vYR9uGqI4Dk:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c4a70f8f17e71a72d3bd130a03479f57ed6b98d7/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L278)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

ditto on storing json
</blockquote></details>

Done.
___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 360 at r28](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NQk8_kxBfzcBEW5k9f7:-NR-8wa00rcaSTpV51M9:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c4a70f8f17e71a72d3bd130a03479f57ed6b98d7/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L360)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

ditto on json
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-03-21 16:37 UTC, tristanvuong2021 reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @stevenwarejones)



<!-- Sent from Reviewable.io -->

2023-03-22 22:22 UTC, tristanvuong2021 requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @riemanli and @stevenwarejones)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NRAPLI83bYKSATSKQna:-NRAPLIAD9b86iCct1vH:b-uzqjtz) (no related file):*
The JSON serialization needs to be in addition to the byte string serialization, not replace it.

___


<!-- Sent from Reviewable.io -->

2023-03-22 23:52 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @stevenwarejones and @tristanvuong2021)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NRAPLI83bYKSATSKQna:-NRAgp8q10yywaJupLlv:b-jfllsk) (no related file):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

The JSON serialization needs to be in addition to the byte string serialization, not replace it.
</blockquote></details>

Thanks for letting me know! Fixed.

___


<!-- Sent from Reviewable.io -->

2023-03-23 16:37 UTC, tristanvuong2021 requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @riemanli and @stevenwarejones)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NRAPLI83bYKSATSKQna:-NREKIaj5FxNNcMcBmM-:b-n96hko) (no related file):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Thanks for letting me know! Fixed.
</blockquote></details>

Type is bytea, not bytes.

___


<!-- Sent from Reviewable.io -->

2023-03-23 17:29 UTC, SanjayVas requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @riemanli, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 255 at r31](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NREVKaq1121vBDIvuWN:-NREVKaq1121vBDIvuWO:b-pcf0tk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0da90a5f7008d7b515e14ef70ab8937c587723da/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L255)):*
> ```TSQL
>   -- Serialized JSON string of a proto3 protobuf with details about the
>   -- metric which do not need to be indexed by the database.
>   --
> ```

Document that this is a human-readable copy of for debugging purposes only, here and elsewhere.

We want to make sure that nothing is relying on the JSON copies. The binary serialization is the canonical one. The fact that we use JSON is just for convenience.



_Suggestion:_
```TSQL
  -- Human-readable copy of the MetricDetails column solely for debugging purposes.
```


<!-- Sent from Reviewable.io -->

2023-03-23 17:45 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @SanjayVas, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql` line 255 at r31](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NREVKaq1121vBDIvuWN:-NREZn-Q6LEsHwZdfZ9a:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0da90a5f7008d7b515e14ef70ab8937c587723da/src/main/resources/reporting/postgres/create-v2alpha-reporting-schema.sql#L255)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Document that this is a human-readable copy of for debugging purposes only, here and elsewhere.

We want to make sure that nothing is relying on the JSON copies. The binary serialization is the canonical one. The fact that we use JSON is just for convenience.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-03-23 17:58 UTC, SanjayVas approved these changes
> Reviewed 1 of 1 files at r32, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835)* status: all files reviewed, 4 unresolved discussions (waiting on @stevenwarejones and @tristanvuong2021)



<!-- Sent from Reviewable.io -->

2023-03-23 18:21 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @SanjayVas, @stevenwarejones, and @tristanvuong2021)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835#-NRAPLI83bYKSATSKQna:-NREh5Rf5dBuxVxAtEqI:bpu5if0) (no related file):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Looks like you copied it from the Spanner schemas. In Postgres, it is just bytea and text, no (max). And the comment is just byte string, not bytea string.
</blockquote></details>

Thanks for pointing it out. Done.

___


<!-- Sent from Reviewable.io -->

2023-03-24 19:45 UTC, stevenwarejones approved these changes
> Reviewed 1 of 1 files at r33, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @riemanli)



<!-- Sent from Reviewable.io -->

2023-03-24 20:46 UTC, riemanli reviewed
> Reviewed 1 of 1 files at r29.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @riemanli)



<!-- Sent from Reviewable.io -->

2023-03-24 20:46 UTC, riemanli reviewed
> Reviewed 1 of 1 files at r33, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/835)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @riemanli)



<!-- Sent from Reviewable.io -->

2023-03-24 20:47 UTC, merged