Log MeasurementStateTrancition into the DB
world-federation-of-advertisers/cross-media-measurement pull request #841
Opened 2023-02-02 08:50 UTC by Marco-Premier

The existing createDuchyMeasurementLogEntry spanner only receives messages from the Duchies.
However the state of a measurement can change due to actions also taken by DPs and MCs. In order to intercept all of this requests in one place, I've only be updating the [updateMeasurementState](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/UpdateMeasurementState.kt) function.

This PR also contains the change for crete-measurement-schema

What it DOES NOT include:

- **update the existing CreateDuchyMeasurementLogEntry Service in order to bundle together the duchy measurement log with state transition log in case of failure**

2023-02-02 08:59 UTC, Marco-Premier reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841)* status: 0 of 10 files reviewed, 3 unresolved discussions (waiting on @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt` line 377 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NNGKzawDYgt-qAuJlbF:-NNGKzawDYgt-qAuJlbG:blpws6i) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bbec27f14d4be0a18e1794d59618cfe03083e794/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt#L377)):*
> ```Kotlin
>         "PriorMeasurementState",
>         Measurement.State::forNumber
>       ) ?: Measurement.State.STATE_UNSPECIFIED
> ```

Since we store -1L as default value for the initial state, "::forNumber" function would return NULL. Here I convert back the -1L to Measurement.State.STATE_UNSPECIFIED
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurementStateTransitionLogEntry.kt` line 16 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NNGJi1l75i24gtjLpsO:-NNGJi1l75i24gtjLpsP:b-8hvk3m) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bbec27f14d4be0a18e1794d59618cfe03083e794/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurementStateTransitionLogEntry.kt#L16)):*
> ```Kotlin
> import org.wfanet.measurement.internal.kingdom.MeasurementLogEntry.Details
> 
> private val DEFAULT_INITIAL_STATE by lazy { InternalId(-1L) }
> ```

InternalId does not support 0 as value so I couldn't set Measurement.State.STATE_UNSPECIFIED as default value
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt` line 1236 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NNGK7-iEKyA9g92kaEW:-NNGK7-iEKyA9g92kaEX:b-x8qvcz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bbec27f14d4be0a18e1794d59618cfe03083e794/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt#L1236)):*
> ```Kotlin
> 
>   @Test
>   fun `measurementState is consistent when creating and cancelling a Measurement`(): Unit = runBlocking {
> ```

Repeated actions (i.e. cancel a measurement twice) is NOT possible due to spanners validation logic. That's why I'm not checking that multiple identical requests don't produce multiple state logging rows into the DB


<!-- Sent from Reviewable.io -->

2023-02-02 14:11 UTC, stevenwarejones requested changes
Can you add some TODOs to the MillBase to combine the grpc calls for sendStatusToKingdom when it is failing the computation?

> Reviewed 9 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-:-NNHSH3N-UheMo2XogPi:bk6yknc)* status: 9 of 10 files reviewed, 4 unresolved discussions (waiting on @Marco-Premier)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementsService.kt` line 44 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NNHPEf27BPWcbI52fpW:-NNHPEf27BPWcbI52fpX:bzi081s) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bbec27f14d4be0a18e1794d59618cfe03083e794/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementsService.kt#L44)):*
> ```Kotlin
> import org.wfanet.measurement.kingdom.deploy.gcloud.spanner.readers.MeasurementReader
> import org.wfanet.measurement.kingdom.deploy.gcloud.spanner.writers.CancelMeasurement
> import org.wfanet.measurement.kingdom.deploy.gcloud.spanner.writers.CreateDuchyMeasurementLogEntry
> ```

is this import needed?
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt` line 1236 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NNGK7-iEKyA9g92kaEW:-NNHSkP8DJchkjK-RYbp:b-8xpvqk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bbec27f14d4be0a18e1794d59618cfe03083e794/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt#L1236)):*
<details><summary><i>Previously, Marco-Premier (marcopremier) wrote…</i></summary><blockquote>

Repeated actions (i.e. cancel a measurement twice) is NOT possible due to spanners validation logic. That's why I'm not checking that multiple identical requests don't produce multiple state logging rows into the DB
</blockquote></details>

does it also throw exceptions if you run updateMeasurementState 2x with the same state?


<!-- Sent from Reviewable.io -->

2023-02-03 13:46 UTC, Marco-Premier reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841)* status: 3 of 11 files reviewed, 4 unresolved discussions (waiting on @SanjayVas and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt` line 1236 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NNGK7-iEKyA9g92kaEW:-NNMUG5k8nZ2bY9MCix0:bv7w03j) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bbec27f14d4be0a18e1794d59618cfe03083e794/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt#L1236)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

does it also throw exceptions if you run updateMeasurementState 2x with the same state?
</blockquote></details>

yes, all spanners raised Status.FAILED_PRECONDITION if the state doesn't meet the requested precondition. I.E. double updates will fail for all measurement state changes
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementsService.kt` line 44 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NNHPEf27BPWcbI52fpW:-NNI6sWmC9Ccl8hAvVQS:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bbec27f14d4be0a18e1794d59618cfe03083e794/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementsService.kt#L44)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

is this import needed?
</blockquote></details>

Done.



_Code quote:_
```Kotlin
CreateDuchyMeasurementLogEntry
```


<!-- Sent from Reviewable.io -->

2023-02-03 14:06 UTC, stevenwarejones approved these changes
> Reviewed 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841)* status: all files reviewed, 2 unresolved discussions (waiting on @SanjayVas)



<!-- Sent from Reviewable.io -->

2023-02-03 21:05 UTC, SanjayVas requested changes
> Reviewed 1 of 10 files at r1, 1 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841)* status: all files reviewed, 9 unresolved discussions (waiting on @Marco-Premier)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NNO-Qjk7HhXjAAmTRuC:-NNO-Qjk7HhXjAAmTRuD:b-6ww2r4) (no related file):*
> What it DOES NOT include:
> 
> update the existing CreateDuchyMeasurementLogEntry Service in order to bundle together the duchy measurement log with state transition log in case of failure

Do you mean FailComputationParticipant? CreateDuchyMeasurementLogEntry is only used for adding log entries that do not result in the Measurement state transitioning to FAILED (i.e. transient errors).

Regardless, state transition log entries **must** *only* be added in the transaction that results in the state transition.

___
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/MillBase.kt` line 221 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NNNxqt84xwdxhwooiYc:-NNNxqt84xwdxhwooiYd:bdonlo5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/adc902c92262bc1e9a79a3e02fded64cd5418d97/src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/MillBase.kt#L221)):*
> ```Kotlin
>         // Treat all other errors as transient.
>         logger.log(Level.WARNING, "$globalId@$millId: TRANSIENT error", e)
>         // TODO log the failure only when token.attempt < maximumAttempts
> ```

Follow our [TODO format](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/docs/code-style.md#format)
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt` line 377 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NNGKzawDYgt-qAuJlbF:-NNNyowHCJ9Sm3T08ZKm:b-fois2u) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bbec27f14d4be0a18e1794d59618cfe03083e794/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt#L377)):*
<details><summary><i>Previously, Marco-Premier (marcopremier) wrote…</i></summary><blockquote>

Since we store -1L as default value for the initial state, "::forNumber" function would return NULL. Here I convert back the -1L to Measurement.State.STATE_UNSPECIFIED
</blockquote></details>

We do we use -1 as default value? We generally avoid sentinel values.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt` line 21 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NNNyA-A3V03E11ASRu3:-NNNyA-A3V03E11ASRu4:b-a9zszp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/adc902c92262bc1e9a79a3e02fded64cd5418d97/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt#L21)):*
> ```Kotlin
> import org.wfanet.measurement.common.identity.ExternalId
> import org.wfanet.measurement.common.identity.InternalId
> import org.wfanet.measurement.gcloud.spanner.*
> ```

Wildcard imports are not allowed.[^1] Import each symbol separately.

[^1]: https://developer.android.com/kotlin/style-guide#import_statements



_Code quote:_
```Kotlin
import org.wfanet.measurement.gcloud.spanner.*
```
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurementStateTransitionLogEntry.kt` line 16 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NNGJi1l75i24gtjLpsO:-NNNyh58AOI5ywU9kDa-:b8is3x4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bbec27f14d4be0a18e1794d59618cfe03083e794/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurementStateTransitionLogEntry.kt#L16)):*
<details><summary><i>Previously, Marco-Premier (marcopremier) wrote…</i></summary><blockquote>

InternalId does not support 0 as value so I couldn't set Measurement.State.STATE_UNSPECIFIED as default value
</blockquote></details>

`InternalId` is only used for internal ID columns. Use the state enum instead, encoding/decoding to integer only at the edges. Our functions for reading/binding Spanner columns has handling for protobuf enums to take care of this encoding/decoding for you.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurementStateTransitionLogEntry.kt` line 97 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NNO36cMATbx7Zu_mPY_:-NNO36cMATbx7Zu_mPYa:bdea66q) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/adc902c92262bc1e9a79a3e02fded64cd5418d97/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurementStateTransitionLogEntry.kt#L97)):*
> ```Kotlin
>   )
> 
> private suspend fun SpannerWriter.TransactionScope.getPreviousState(
> ```

Depending on the condition when the log entry is added, you should either
1. Already know the "previous" state since you've read the Measurement row OR
2. Be able to read the "previous" state that's about to be overwritten from the Measurements table, as we do all our writes by buffering mutations so they haven't been applied until the transaction is committed.

It might even be true that (1) is the only condition, as I'm guessing that all writes that result in a Measurement state change will have read the Measurement row to ensure that it's in a legal state for the transition.



_Code quote:_
```Kotlin
getPreviousState
```
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurementStateTransitionLogEntry.kt` line 109 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NNO246--f-srwJuONHf:-NNO246--f-srwJuONHg:b-uclkop) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/adc902c92262bc1e9a79a3e02fded64cd5418d97/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurementStateTransitionLogEntry.kt#L109)):*
> ```Kotlin
>           StateTransitionMeasurementLogEntries.CurrentMeasurementState,
>         FROM StateTransitionMeasurementLogEntries
>         WHERE StateTransitionMeasurementLogEntries.MeasurementConsumerId = ${measurementConsumerId.value}
> ```

Never use String interpolation for SQL. Use param binding instead.

This is done to avoid any chance at SQL injection.



_Code quote:_
```Kotlin
${measurementConsumerId.value}
```
___
*[`src/main/proto/wfa/measurement/internal/kingdom/measurement.proto` line 158 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NNO0rd427UkdMIGqS_Z:-NNO0rd427UkdMIGqS__:b-9v8y1c) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/adc902c92262bc1e9a79a3e02fded64cd5418d97/src/main/proto/wfa/measurement/internal/kingdom/measurement.proto#L158)):*
> ```protobuf
>   //
>   // Only set for COMPUTATION view.
>   repeated MeasurementStateLogEntry measurement_state_log_entry = 14;
> ```

Why does the Duchy need to see these log entries? (That's the only reason for adding something that's only set in the COMPUTATION view)

More broadly, if we want to plumb through log entries in the public API it should probably be in a separate sub-resource under the Measurement (i.e. a separate method call from GetMeasurement). Regardless, plumbing through to the public API is not necessary in this PR and would be a separate future feature.
___
*[`src/main/resources/kingdom/spanner/create-measurement-schema.sql` line 409 at r2](https://reviewable.io/reviews/world-federation-of-a [...]

2023-02-06 18:23 UTC, Marco-Premier reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841)* status: all files reviewed, 9 unresolved discussions (waiting on @SanjayVas)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NNO-Qjk7HhXjAAmTRuC:-NN_zoez3SMqGCmAN-Ib:blyagxa) (no related file):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> What it DOES NOT include:
> 
> update the existing CreateDuchyMeasurementLogEntry Service in order to bundle together the duchy measurement log with state transition log in case of failure

Do you mean FailComputationParticipant? CreateDuchyMeasurementLogEntry is only used for adding log entries that do not result in the Measurement state transitioning to FAILED (i.e. transient errors).

Regardless, state transition log entries **must** *only* be added in the transaction that results in the state transition.
</blockquote></details>

https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/MillBase.kt#L225

if the number of failures reaches the maximumAttempts "failComputationAtKingdom" is invoke which translate in a stateUpdate and consequently into a new state transition log entry.

The TODOs I've added have the goal to bundle the duchy measurement log entry together with the state transition log entry (i.e. in the same DB transaction) in order to debug the cause of the failure. If that's not needed @SanjayVas , I can remove the TODOs .

___
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/MillBase.kt` line 221 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NNNxqt84xwdxhwooiYc:-NNbEcvt6zJiDHw5xh1n:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/adc902c92262bc1e9a79a3e02fded64cd5418d97/src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/MillBase.kt#L221)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Follow our [TODO format](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/docs/code-style.md#format)
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt` line 377 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NNGKzawDYgt-qAuJlbF:-NNa7IqG6Lmm8WiEgUQn:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bbec27f14d4be0a18e1794d59618cfe03083e794/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt#L377)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

We do we use -1 as default value? We generally avoid sentinel values.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt` line 21 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NNNyA-A3V03E11ASRu3:-NNa2kD_5PwYXP4ufB01:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/adc902c92262bc1e9a79a3e02fded64cd5418d97/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt#L21)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Wildcard imports are not allowed.[^1] Import each symbol separately.

[^1]: https://developer.android.com/kotlin/style-guide#import_statements
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurementStateTransitionLogEntry.kt` line 16 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NNGJi1l75i24gtjLpsO:-NNa7GwC-xqMn2Qy1QAO:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/bbec27f14d4be0a18e1794d59618cfe03083e794/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurementStateTransitionLogEntry.kt#L16)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

`InternalId` is only used for internal ID columns. Use the state enum instead, encoding/decoding to integer only at the edges. Our functions for reading/binding Spanner columns has handling for protobuf enums to take care of this encoding/decoding for you.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurementStateTransitionLogEntry.kt` line 97 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NNO36cMATbx7Zu_mPY_:-NNbE2oB-l5YIcfrqPos:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/adc902c92262bc1e9a79a3e02fded64cd5418d97/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurementStateTransitionLogEntry.kt#L97)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Depending on the condition when the log entry is added, you should either
1. Already know the "previous" state since you've read the Measurement row OR
2. Be able to read the "previous" state that's about to be overwritten from the Measurements table, as we do all our writes by buffering mutations so they haven't been applied until the transaction is committed.

It might even be true that (1) is the only condition, as I'm guessing that all writes that result in a Measurement state change will have read the Measurement row to ensure that it's in a legal state for the transition.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurementStateTransitionLogEntry.kt` line 109 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NNO246--f-srwJuONHf:-NNbE24j7jN3qVjrbcUd:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/adc902c92262bc1e9a79a3e02fded64cd5418d97/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurementStateTransitionLogEntry.kt#L109)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Never use String interpolation for SQL. Use param binding instead.

This is done to avoid any chance at SQL injection.
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/internal/kingdom/measurement.proto` line 158 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NNO0rd427UkdMIGqS_Z:-NNbEkWWEJO9Rd20ZL7q:b-s3jo6v) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/adc902c92262bc1e9a79a3e02fded64cd5418d97/src/main/proto/wfa/measurement/internal/kingdom/measurement.proto#L158)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Why does the Duchy need to see these log entries? (That's the only reason for adding something that's only set in the COMPUTATION view)

More broadly, if we want to plumb through log entries in the public API it should probably be in a separate sub-resource under the Measurement (i.e. a separate method call from GetMeasurement). Regardless, plumbing through to the public API is not necessary in this PR and would be a separate future feature.
</blockquote></details>

You are right @SanjayVas . I don't think there's need for Duchy to know measurement state log entries. Can you please advise whether I shall remove the reader changes entirely and leave it for another PR or just move  [...]

2023-02-06 19:27 UTC, SanjayVas requested changes
> Reviewed 1 of 10 files at r1, 8 of 12 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841)* status: 14 of 18 files reviewed, 7 unresolved discussions (waiting on @Marco-Premier and @stevenwarejones)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NNO-Qjk7HhXjAAmTRuC:-NNc0y-C5e5SqK3rBJ34:b-psvgvb) (no related file):*
<details><summary><i>Previously, Marco-Premier (marcopremier) wrote…</i></summary><blockquote>

https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/MillBase.kt#L225

if the number of failures reaches the maximumAttempts "failComputationAtKingdom" is invoke which translate in a stateUpdate and consequently into a new state transition log entry.

The TODOs I've added have the goal to bundle the duchy measurement log entry together with the state transition log entry (i.e. in the same DB transaction) in order to debug the cause of the failure. If that's not needed @SanjayVas , I can remove the TODOs .
</blockquote></details>

Them being in the same transaction is a hard requirement. I believe this PR handles that, as FailComputationParticipant calls `updateMeasurementState` which adds the log entry.

___
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/MillBase.kt` line 226 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NNc3pQv9c9U8CZRDql9:-NNc3pQv9c9U8CZRDqlA:bcvogod) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f00fda6fad3b9281808e630dd78109d52921c5b5/src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/MillBase.kt#L226)):*
> ```Kotlin
>           val errorMessage = "Failing computation due to too many failed attempts."
>           logger.log(Level.SEVERE, "$globalId@$millId: $errorMessage")
>           // TODO(@marcopremier) forward the errorMessage through failComputationAtKingdom to bundle
> ```

I'm not sure what this TODO is saying. This call already passes the error message in the RPC.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurement.kt` line 23 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NNc7hvp2bLfzUeFZeRK:-NNc7hvp2bLfzUeFZeRL:b-awcpf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f00fda6fad3b9281808e630dd78109d52921c5b5/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurement.kt#L23)):*
> ```Kotlin
> import org.wfanet.measurement.common.identity.ExternalId
> import org.wfanet.measurement.common.identity.InternalId
> import org.wfanet.measurement.gcloud.spanner.*
> ```

Same here re:wildcards



_Code quote:_
```Kotlin
import org.wfanet.measurement.gcloud.spanner.*
import org.wfanet.measurement.internal.kingdom.*










import org.wfanet.measurement.kingdom.deploy.common.DuchyIds
import org.wfanet.measurement.kingdom.deploy.gcloud.spanner.common.*
```
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurementStateTransitionLogEntry.kt` line 27 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NNcAaS6E0O_ZH8BNMxc:-NNcAaS6E0O_ZH8BNMxd:b-60930p) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f00fda6fad3b9281808e630dd78109d52921c5b5/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurementStateTransitionLogEntry.kt#L27)):*
> ```Kotlin
> private val MEASUREMENT_LOG_DETAILS by lazy { Details.getDefaultInstance() }
> 
> internal suspend fun SpannerWriter.TransactionScope.createMeasurementStateTransitionLogEntry(
> ```

Does this still need to be a `suspend` function? It looks like it only buffers mutations.

The same would be applied to its callers if any were changed to a `suspend` function in order to call this.



_Code quote:_
```Kotlin
suspend 
```
___
*[`src/main/proto/wfa/measurement/internal/kingdom/measurement.proto` line 158 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NNO0rd427UkdMIGqS_Z:-NNc4X6Z5CnexmtHGYZO:b-yz6qxi) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/adc902c92262bc1e9a79a3e02fded64cd5418d97/src/main/proto/wfa/measurement/internal/kingdom/measurement.proto#L158)):*
<details><summary><i>Previously, Marco-Premier (marcopremier) wrote…</i></summary><blockquote>

You are right @SanjayVas . I don't think there's need for Duchy to know measurement state log entries. Can you please advise whether I shall remove the reader changes entirely and leave it for another PR or just move it into DEFAULT view?
</blockquote></details>

My suggestion is to leave this field out of this message entirely, which I believe will result in the Measurement reader being unchanged by this PR.
___
*[`src/main/resources/kingdom/spanner/create-measurement-schema.sql` line 403 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NNc4DOP0sXfadwRpA9s:-NNc4DOQ-AYjVYIiZuw1:b-w02m7j) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f00fda6fad3b9281808e630dd78109d52921c5b5/src/main/resources/kingdom/spanner/create-measurement-schema.sql#L403)):*
> ```TSQL
>   INTERLEAVE IN PARENT Measurements ON DELETE CASCADE;
> 
> -- Child table used for logging measurement state transitions.
> ```

Note that this file should never be changed. Schema updates need to be added as new changelog entries, i.e. adding a new entry to changelog.yaml.
___
*[`src/main/resources/kingdom/spanner/create-measurement-schema.sql` line 409 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NNc9xq9Ej8e5t_DbUT6:-NNc9xq9Ej8e5t_DbUT7:b7x34x7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f00fda6fad3b9281808e630dd78109d52921c5b5/src/main/resources/kingdom/spanner/create-measurement-schema.sql#L409)):*
> ```TSQL
>   MeasurementId INT64 NOT NULL,
>   CreateTime TIMESTAMP NOT NULL OPTIONS (allow_commit_timestamp = true),
>   PriorMeasurementState INT64 NOT NULL,
> ```

nit: "Previous" is a more common pairing with "Current"



_Code quote:_
```TSQL
Prior
```


<!-- Sent from Reviewable.io -->

2023-02-07 14:32 UTC, Marco-Premier reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841)* status: 3 of 20 files reviewed, 10 unresolved discussions (waiting on @SanjayVas and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt` line 377 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NNc7ekv7mNSoocE8Q1D:-NNg1PxRCsev2zdNdUYK:b-6x4bhr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/adc902c92262bc1e9a79a3e02fded64cd5418d97/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt#L377)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

shouldn't we return STATE_UNSPECIFIED if none is found?
</blockquote></details>

Shouldn't be necessary since it's initialized to STATE_UNSPECIFIED if no previous state is specified. I've added it as null safety check
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurement.kt` line 23 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NNc7hvp2bLfzUeFZeRK:-NNf4sYL35uvAPpImoP2:bpctrk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f00fda6fad3b9281808e630dd78109d52921c5b5/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurement.kt#L23)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Same here re:wildcards
</blockquote></details>

My bad, missconfigured import rules on intellij
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurementStateTransitionLogEntry.kt` line 27 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NNcAaS6E0O_ZH8BNMxc:-NNf5gvS4sxZt_AU12mg:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f00fda6fad3b9281808e630dd78109d52921c5b5/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurementStateTransitionLogEntry.kt#L27)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Does this still need to be a `suspend` function? It looks like it only buffers mutations.

The same would be applied to its callers if any were changed to a `suspend` function in order to call this.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FailComputationParticipant.kt` line 113 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NNc850F-W4uzUIj60Kw:-NNg7bE68KYocb8wnzlc:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f00fda6fad3b9281808e630dd78109d52921c5b5/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FailComputationParticipant.kt#L113)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

i'd prefer you name these variables you are passing in
```
  measurementId = measurementId,
  measurementConsumerId = measurementConsumerId,
  priorMeasurementState = measurementState,
  currentMeasurementState = Measurement.State.FAILED
```

</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/RevokeCertificate.kt` line 226 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NNcD2rr2E4Gtosv6gpD:-NNfBdA8-S2DS-40Ch2p:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f00fda6fad3b9281808e630dd78109d52921c5b5/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/RevokeCertificate.kt#L226)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

`.single()`
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/UpdateMeasurementState.kt` line 45 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NNc9VCd38KN3mDGNuSp:-NNg6mbpB1_7oxNDpY4_:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f00fda6fad3b9281808e630dd78109d52921c5b5/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/UpdateMeasurementState.kt#L45)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

ditto on naming arguments
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/internal/kingdom/measurement.proto` line 158 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NNO0rd427UkdMIGqS_Z:-NNg8ZhA1p0asF6z3F4w:b-z3lcw7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/adc902c92262bc1e9a79a3e02fded64cd5418d97/src/main/proto/wfa/measurement/internal/kingdom/measurement.proto#L158)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

My suggestion is to leave this field out of this message entirely, which I believe will result in the Measurement reader being unchanged by this PR.
</blockquote></details>

I moved the measurement log into the DEFAULT view since I need to read it for testing purposes (```MeasurementServiceTest```). In future release we can either create another custom view specific for logging
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/MillBase.kt` line 226 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NNc3pQv9c9U8CZRDql9:-NNg1xmQ0wN1AJMcfXby:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f00fda6fad3b9281808e630dd78109d52921c5b5/src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/MillBase.kt#L226)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I'm not sure what this TODO is saying. This call already passes the error message in the RPC.
</blockquote></details>

Done.
___
*[`src/main/resources/kingdom/spanner/create-measurement-schema.sql` line 409 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NNNzOu-1JLXvwY35uxO:-NNgBGIu3sfEsVrmf5aV:b-bzggxo) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/adc902c92262bc1e9a79a3e02fded64cd5418d97/src/main/resources/kingdom/spanner/create-measurement-schema.sql#L409)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

I thought we would just set the priorMeasurementState to STATE_UNDEFINED for when its created.
</blockquote></details>

Indeed I followed this rule: for newly created measurement, the previous state is ```STATE_UNDEFINED```
___
*[`src/main/resources/kingdom/spanner/create-measurement-schema.sql` line 403 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NNc4DOP0sXfadwRpA9s:-NNfFsra4e4SaCKj3Z3K:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f00fda6fad3b9281808e630dd78109d52921c5b5/src/main/resources/kingdom/spanner/create-measurement-schema.sql#L403)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Note that this file should never be changed. Schema updates need to be added as new changelog entries, i.e. adding a new entry to changelog.yaml.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-02-07 17:08 UTC, stevenwarejones approved these changes
> Reviewed 1 of 12 files at r3, 17 of 17 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841)* status: all files reviewed, 6 unresolved discussions (waiting on @SanjayVas)



<!-- Sent from Reviewable.io -->

2023-02-08 00:56 UTC, SanjayVas requested changes
> Reviewed 2 of 17 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841)* status: all files reviewed, 2 unresolved discussions (waiting on @Marco-Premier and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/internal/kingdom/measurement.proto` line 158 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NNO0rd427UkdMIGqS_Z:-NNiRBx_BGeK31nT82vW:b7r37vd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/adc902c92262bc1e9a79a3e02fded64cd5418d97/src/main/proto/wfa/measurement/internal/kingdom/measurement.proto#L158)):*
Do we really want the log entries to be included with every Measurement read? @stevenwarejones jones WDYT? I had assumed any kind of history logging would live on its own with separate APIs to access it as-needed.

> since I need to read it for testing purposes 

This is not a good enough reason on its own to add log entries to the Measurement message in the internal API. You may need a method to read log entries on the internal API in this PR.
___
*[`src/main/resources/kingdom/spanner/create-measurement-schema.sql` line 409 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NNNzOu-1JLXvwY35uxO:-NNiSjON6UxtT1AqtHUu:bpf5g53) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/adc902c92262bc1e9a79a3e02fded64cd5418d97/src/main/resources/kingdom/spanner/create-measurement-schema.sql#L409)):*
<details><summary><i>Previously, Marco-Premier (marcopremier) wrote…</i></summary><blockquote>

Indeed I followed this rule: for newly created measurement, the previous state is ```STATE_UNDEFINED```
</blockquote></details>

The default UNSPECIFIED value for protobuf enum is generally never written. That is to say that writing an UNSPECIFIED should be considered an error. It's only used to provide a readable default in proto messages when it's not set, as proto APIs don't tend to return nulls. (e.g. in the proto3 wire format, an enum field set to the default 0/UNSPECIFIED value will not be included in the encoding).

In DB columns, we want to be explicit when something may not be set. If this were a string column, we would similarly not use empty string and would explicitly use NULL.


<!-- Sent from Reviewable.io -->

2023-02-08 10:42 UTC, Marco-Premier reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841)* status: 15 of 24 files reviewed, 2 unresolved discussions (waiting on @SanjayVas and @stevenwarejones)

___
*[`src/main/proto/wfa/measurement/internal/kingdom/measurement.proto` line 158 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NNO0rd427UkdMIGqS_Z:-NNkaH8h9dR8IcWKvRh1:b3cumz2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/adc902c92262bc1e9a79a3e02fded64cd5418d97/src/main/proto/wfa/measurement/internal/kingdom/measurement.proto#L158)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Do we really want the log entries to be included with every Measurement read? @stevenwarejones jones WDYT? I had assumed any kind of history logging would live on its own with separate APIs to access it as-needed.

> since I need to read it for testing purposes 

This is not a good enough reason on its own to add log entries to the Measurement message in the internal API. You may need a method to read log entries on the internal API in this PR.
</blockquote></details>

I entirely removed the state transition log entry from the ```MeasurementReader``` and added a new method into the ```SpannerMeasurementLogEntriesService``` so that state logs are only return through internal API (for testing) and not expose to any public facing api
___
*[`src/main/resources/kingdom/spanner/create-measurement-schema.sql` line 409 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NNNzOu-1JLXvwY35uxO:-NNk2mIb753ZcPWQnnt6:b-xuyt2b) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/adc902c92262bc1e9a79a3e02fded64cd5418d97/src/main/resources/kingdom/spanner/create-measurement-schema.sql#L409)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The default UNSPECIFIED value for protobuf enum is generally never written. That is to say that writing an UNSPECIFIED should be considered an error. It's only used to provide a readable default in proto messages when it's not set, as proto APIs don't tend to return nulls. (e.g. in the proto3 wire format, an enum field set to the default 0/UNSPECIFIED value will not be included in the encoding).

In DB columns, we want to be explicit when something may not be set. If this were a string column, we would similarly not use empty string and would explicitly use NULL.
</blockquote></details>

thank you for the context @SanjayVas . Replaced with null when the previous state is not available (i.e. at creation time)


<!-- Sent from Reviewable.io -->

2023-02-08 16:12 UTC, stevenwarejones requested changes
Following up on this... @SanjayVas  - I was thinking that the transition state log entry needs to get bundled with the computationLogEntry (same commit timestamp) -- https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/MillBase.kt#L221

> Reviewed 5 of 9 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-:-NNlmwOk851vvSdwnRXY:b-akcimn)* status: 20 of 24 files reviewed, 5 unresolved discussions (waiting on @Marco-Premier and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt` line 98 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NNlkht_3kM64RJXp858:-NNlkht_3kM64RJXp859:brv78za) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4c90a927307db458ef7ad90fb87f79fc5c0790c0/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt#L98)):*
> ```Kotlin
>   private fun buildMeasurement(struct: Struct): Measurement {
>     return measurement {
>       return measurement {
> ```

i think this was accidentally added
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurementStateTransitionLogEntry.kt` line 70 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NNllbS9CCGuHtTF-9I7:-NNllbS9CCGuHtTF-9I8:buuafuh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4c90a927307db458ef7ad90fb87f79fc5c0790c0/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurementStateTransitionLogEntry.kt#L70)):*
> ```Kotlin
>     set("CreateTime" to Value.COMMIT_TIMESTAMP)
>     set("CurrentMeasurementState" to currentMeasurementState)
>     if (previousMeasurementState != null) {
> ```

i don't think we need this if -- its fine to set it to null
___
*[`src/main/proto/wfa/measurement/internal/kingdom/measurement.proto` line 158 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NNO0rd427UkdMIGqS_Z:-NNlkqKpE0gfpGTcg8ZK:b-ib0umr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/adc902c92262bc1e9a79a3e02fded64cd5418d97/src/main/proto/wfa/measurement/internal/kingdom/measurement.proto#L158)):*
<details><summary><i>Previously, Marco-Premier (marcopremier) wrote…</i></summary><blockquote>

I entirely removed the state transition log entry from the ```MeasurementReader``` and added a new method into the ```SpannerMeasurementLogEntriesService``` so that state logs are only return through internal API (for testing) and not expose to any public facing api
</blockquote></details>

I agree. The only places to include it would be in there was a call to get a Measurement *and* all the log entries associated with it (duchy + transition state)
___
*[`src/main/proto/wfa/measurement/internal/kingdom/measurement_log_entries_service.proto` line 34 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NNlkOFOCb0yWUB1rE0h:-NNlkOFOCb0yWUB1rE0i:b-y0upii) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4c90a927307db458ef7ad90fb87f79fc5c0790c0/src/main/proto/wfa/measurement/internal/kingdom/measurement_log_entries_service.proto#L34)):*
> ```protobuf
>       returns (DuchyMeasurementLogEntry);
> 
>   // Retriece all measurement state transition log entries for a given measurement
> ```

nit: retrieve


<!-- Sent from Reviewable.io -->

2023-02-08 19:07 UTC, SanjayVas requested changes
> Reviewed 11 of 17 files at r4, 6 of 9 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841)* status: 23 of 24 files reviewed, 11 unresolved discussions (waiting on @Marco-Premier and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurement.kt` line 22 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NNmKwhB9KAd9PceoJ2y:-NNmKwhB9KAd9PceoJ2z:b2fyn7k) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4c90a927307db458ef7ad90fb87f79fc5c0790c0/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurement.kt#L22)):*
> ```Kotlin
> import org.wfanet.measurement.kingdom.deploy.gcloud.spanner.readers.MeasurementReader
> 
> class StreamMeasurement(
> ```

I don't think you need this anymore.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurementStateTransitionLogEntry.kt` line 54 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NNmLZxhCC_n0qeJ0GTU:-NNmLZxhCC_n0qeJ0GTV:b-yri1jk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4c90a927307db458ef7ad90fb87f79fc5c0790c0/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurementStateTransitionLogEntry.kt#L54)):*
> ```Kotlin
>     set("MeasurementId" to measurementId)
>     set("CreateTime" to Value.COMMIT_TIMESTAMP)
>     set("MeasurementLogDetails" to MEASUREMENT_LOG_DETAILS)
> ```

This should be a populated Details, not an empty static one. e.g. if the state is transitioning to the FAILED state, the ErrorDetails need to be filled in. The log message should be set to something useful.



_Code quote:_
```Kotlin
MEASUREMENT_LOG_DETAILS
```
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurementStateTransitionLogEntry.kt` line 70 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NNllbS9CCGuHtTF-9I7:-NNmIep-9EIxojUEw6xE:be3zwnx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4c90a927307db458ef7ad90fb87f79fc5c0790c0/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurementStateTransitionLogEntry.kt#L70)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

i don't think we need this if -- its fine to set it to null
</blockquote></details>

I double-checked and it looks like we don't have a nullable overload for protobuf enums, therefore this check *is* necessary.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FailComputationParticipant.kt` line 113 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NNmOe8k3ws3yR_IAl57:-NNmOe8k3ws3yR_IAl58:bvsordk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4c90a927307db458ef7ad90fb87f79fc5c0790c0/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FailComputationParticipant.kt#L113)):*
> ```Kotlin
>             }
>         }
>       updateMeasurementState(
> ```

I think I see where some of the confusion may have come from re: DuchyMeasurementLogEntries. It looks like we have a bug here, as FailComputationParticipant should result in a DuchyMeasurementLogEntries row being inserted.

Can you add a TODO here to fix that? In that case, we'll need to have a single MeasurementLogEntries row with two children: a StateTransitionMeasurementLogEntries row and a DuchyMeasurementLogEntries row.
___
*[`src/main/proto/wfa/measurement/internal/kingdom/measurement.proto` line 158 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NNO0rd427UkdMIGqS_Z:-NNmPIILADMuFtO0ttef:b-g7pxlx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/adc902c92262bc1e9a79a3e02fded64cd5418d97/src/main/proto/wfa/measurement/internal/kingdom/measurement.proto#L158)):*
What I mean is that this field should not be added to Measurement at all in this PR.

> The only places to include it would be in [sic: I assume this should be "if"] there was a call to get a Measurement and all the log entries associated with it (duchy + transition state)

To clarify, this call does not yet exist and we don't expect to add it in this PR.
___
*[`src/main/proto/wfa/measurement/internal/kingdom/measurement.proto` line 292 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NNmPx6oAsKiLD84y5JY:-NNmPx6oAsKiLD84y5JZ:bt47a2s) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4c90a927307db458ef7ad90fb87f79fc5c0790c0/src/main/proto/wfa/measurement/internal/kingdom/measurement.proto#L292)):*
> ```protobuf
> }
> 
> message MeasurementStateLogEntry {
> ```

Move this to `measurement_log_entry.proto` and rename it to `StateTransitionMeasurementLogEntry`.
___
*[`src/main/proto/wfa/measurement/internal/kingdom/measurement_log_entries_service.proto` line 35 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NNmJZRW7CaX-l46V5_D:-NNmJZRW7CaX-l46V5_E:b45h) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4c90a927307db458ef7ad90fb87f79fc5c0790c0/src/main/proto/wfa/measurement/internal/kingdom/measurement_log_entries_service.proto#L35)):*
> ```protobuf
> 
>   // Retriece all measurement state transition log entries for a given measurement
>   rpc GetMeasurementStateLogEntries(GetMeasurementStateTransitionLogEntryRequest) returns (Measurement);
> ```





_Suggestion:_
```protobuf
stream StateTransitionMeasurementLogEntry
```
___
*[`src/main/proto/wfa/measurement/internal/kingdom/measurement_log_entries_service.proto` line 35 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NNmJmHi5r5jZcbiIhCi:-NNmJmHi5r5jZcbiIhCj:baxi62e) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4c90a927307db458ef7ad90fb87f79fc5c0790c0/src/main/proto/wfa/measurement/internal/kingdom/measurement_log_entries_service.proto#L35)):*
> ```protobuf
> 
>   // Retriece all measurement state transition log entries for a given measurement
>   rpc GetMeasurementStateLogEntries(GetMeasurementStateTransitionLogEntryRequest) returns (Measurement);
> ```

"Get" is for single values. From the internal API we use streaming RPCs for multiple values.



_Suggestion:_
```protobuf
StreamStateTransitionMeasurementLogEntries
```
___
*[`src/main/resources/kingdom/spanner/create-state-transition-measurement-log-entry-schema.sql` line 18 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NNmG0Fp5HJn7socFHFi:-NNmG0Fp5HJn7socFHFj:b-o6n7f3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4c90a927307db458ef7ad90fb87f79fc5c0790c0/src/main/resources/kingdom/spanner/create-state-transition-measurement-log-entry-schema.sql#L18)):*
> ```TSQL
> 
> -- changeset marcopremier:5 dbms:cloudspanner
> START BATCH DDL;
> ```

nit: You don't need the START BATCH and RUN BATCH when it's just a single DDL statement.



_Code quote:_
```TSQL
START BATCH DDL;
```


<!-- Sent from Reviewable.io -->

2023-02-09 18:31 UTC, Marco-Premier reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841)* status: 22 of 24 files reviewed, 8 unresolved discussions (waiting on @Marco-Premier, @SanjayVas, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurement.kt` line 22 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NNmKwhB9KAd9PceoJ2y:-NNqZeTbCjzyWCVjcwEr:bu87a7c) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4c90a927307db458ef7ad90fb87f79fc5c0790c0/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurement.kt#L22)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I don't think you need this anymore.
</blockquote></details>

I still use this in ```RevokeCertificate``` to know the previous measurement state since it's not always available
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt` line 98 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NNlkht_3kM64RJXp858:-NNmPiBEBTcK2oaznGVl:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4c90a927307db458ef7ad90fb87f79fc5c0790c0/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementReader.kt#L98)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

i think this was accidentally added
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurementStateTransitionLogEntry.kt` line 54 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NNmLZxhCC_n0qeJ0GTU:-NNqQxBW48VlfoYyybAK:bcv978n) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4c90a927307db458ef7ad90fb87f79fc5c0790c0/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurementStateTransitionLogEntry.kt#L54)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This should be a populated Details, not an empty static one. e.g. if the state is transitioning to the FAILED state, the ErrorDetails need to be filled in. The log message should be set to something useful.
</blockquote></details>

@SanjayVas just to clarify: I don't think there's the need to add details for all state transitions, since the only one that can be caused for different reasons is FAILED.


Regarding FAILED, we should (as you noticed in the bug in the other comment) bundle together ``` DuchyMeasurementLog```  with ``` StateTransitionLog``` .

My question is: shall I leave this fix in the TODO as well or we rather want to add a message even if the FAILURE comes from ``` RefuseRequisition```  or ``` RevokeCertificate```  to better understand why it failed?
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurementStateTransitionLogEntry.kt` line 70 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NNllbS9CCGuHtTF-9I7:-NNmQ0lJ8qILmY_P2CSu:b7j5y2x) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4c90a927307db458ef7ad90fb87f79fc5c0790c0/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurementStateTransitionLogEntry.kt#L70)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

i don't think we need this if -- its fine to set it to null
</blockquote></details>

it's actually needed as the set method checks for notNull value and it raises an error otherwise
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FailComputationParticipant.kt` line 113 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NNmOe8k3ws3yR_IAl57:-NNqXP1P5vKgPozf98ot:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4c90a927307db458ef7ad90fb87f79fc5c0790c0/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FailComputationParticipant.kt#L113)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I think I see where some of the confusion may have come from re: DuchyMeasurementLogEntries. It looks like we have a bug here, as FailComputationParticipant should result in a DuchyMeasurementLogEntries row being inserted.

Can you add a TODO here to fix that? In that case, we'll need to have a single MeasurementLogEntries row with two children: a StateTransitionMeasurementLogEntries row and a DuchyMeasurementLogEntries row.
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/internal/kingdom/measurement.proto` line 292 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NNmPx6oAsKiLD84y5JY:-NNrOAJx2ABborEccPQ1:b-2yihgb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4c90a927307db458ef7ad90fb87f79fc5c0790c0/src/main/proto/wfa/measurement/internal/kingdom/measurement.proto#L292)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Move this to `measurement_log_entry.proto` and rename it to `StateTransitionMeasurementLogEntry`.
</blockquote></details>

I tried doing it but bazel fails while building proto messages due to a "proto cycle dependency" since:
measurement.proto imports computation_participant.proto that imports measurement_log_entry.proto that imports again measurement.proto and it creates a cycle

The easiest solution I see is to change ```StateTransitionMeasurementLogEntry.previous_state``` and ```StateTransitionMeasurementLogEntry.current_state``` to string (so that I don't have to import measurement.proto)

Otherwise I'm not sure how to easily solve this cycle dependency.
Do you have better ideas @SanjayVas ? thank you


<!-- Sent from Reviewable.io -->

2023-02-09 20:22 UTC, SanjayVas requested changes
> Reviewed 1 of 1 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841)* status: all files reviewed, 7 unresolved discussions (waiting on @Marco-Premier)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurement.kt` line 22 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NNmKwhB9KAd9PceoJ2y:-NNro_F44CyUN4yqIdOF:bi91jnx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4c90a927307db458ef7ad90fb87f79fc5c0790c0/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurement.kt#L22)):*
<details><summary><i>Previously, Marco-Premier (marcopremier) wrote…</i></summary><blockquote>

I still use this in ```RevokeCertificate``` to know the previous measurement state since it's not always available
</blockquote></details>

`failMeausurement` is called as a result of a Measurements read. You should already have the measurement state and don't need to read the Measurement again.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurementStateTransitionLogEntry.kt` line 54 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NNmLZxhCC_n0qeJ0GTU:-NNrorNj8zLgsdO_o9bI:bkjcdvz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4c90a927307db458ef7ad90fb87f79fc5c0790c0/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurementStateTransitionLogEntry.kt#L54)):*
> I don't think there's the need to add details for all state transitions, since the only one that can be caused for different reasons is FAILED.

The human-readable log message should always be populated, even if it's something that could be derived from the state changes. e.g. "All requisitions fulfilled"
___
*[`src/main/proto/wfa/measurement/internal/kingdom/measurement.proto` line 292 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NNmPx6oAsKiLD84y5JY:-NNrnoSo6lGAvylYCPH-:bpcj6nx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4c90a927307db458ef7ad90fb87f79fc5c0790c0/src/main/proto/wfa/measurement/internal/kingdom/measurement.proto#L292)):*
<details><summary><i>Previously, Marco-Premier (marcopremier) wrote…</i></summary><blockquote>

I tried doing it but bazel fails while building proto messages due to a "proto cycle dependency" since:
measurement.proto imports computation_participant.proto that imports measurement_log_entry.proto that imports again measurement.proto and it creates a cycle

The easiest solution I see is to change ```StateTransitionMeasurementLogEntry.previous_state``` and ```StateTransitionMeasurementLogEntry.current_state``` to string (so that I don't have to import measurement.proto)

Otherwise I'm not sure how to easily solve this cycle dependency.
Do you have better ideas @SanjayVas ? thank you
</blockquote></details>

If you see the above comment, it's that Measurement should not have a log entry field. Therefore `measurement.proto` should not depend on `measurement_log_entry.proto`


<!-- Sent from Reviewable.io -->

2023-02-10 09:31 UTC, Marco-Premier reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841)* status: 11 of 24 files reviewed, 6 unresolved discussions (waiting on @SanjayVas and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurement.kt` line 22 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NNmKwhB9KAd9PceoJ2y:-NNuL_1r9jQ8Pt7dw6-h:bo3whdy) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4c90a927307db458ef7ad90fb87f79fc5c0790c0/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurement.kt#L22)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

`failMeausurement` is called as a result of a Measurements read. You should already have the measurement state and don't need to read the Measurement again.
</blockquote></details>

Actually 2 out of 3 cases where ```failMeasurement``` is called

1) https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/RevokeCertificate.kt#L169

2) https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/RevokeCertificate.kt#L188

only read the MeasurementDetails through ```MeasurementDetailsReader``` which in turn returns the following result:

https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementDetailsReader.kt#L25

**There's no state inside that.** So unless I add the state into ```MeasurementDetailsReader.Result``` I still think ```StreamMeasurement``` is needed to get the state of the measurement in those 2 cases.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurementStateTransitionLogEntry.kt` line 54 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NNmLZxhCC_n0qeJ0GTU:-NNuaUFi0asMFNp1ivAz:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4c90a927307db458ef7ad90fb87f79fc5c0790c0/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurementStateTransitionLogEntry.kt#L54)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> I don't think there's the need to add details for all state transitions, since the only one that can be caused for different reasons is FAILED.

The human-readable log message should always be populated, even if it's something that could be derived from the state changes. e.g. "All requisitions fulfilled"
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/internal/kingdom/measurement.proto` line 292 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NNmPx6oAsKiLD84y5JY:-NNucdS57wcIu3n6inJ8:b-vl2h39) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4c90a927307db458ef7ad90fb87f79fc5c0790c0/src/main/proto/wfa/measurement/internal/kingdom/measurement.proto#L292)):*
> I tried doing it

meaning I tried to remove the log entry field from ```measurement.proto``` and put it in ```measurement_log_entry.proto``` as per your request and the cycle dependency came up. Please see the image below

![Screenshot from 2023-02-09 15-56-47.png](https://files.reviewableusercontent.io/images/reviewable/1636171/yMJ6qkLHNd1D0JjFhbV8HrHl/Screenshot%20from%202023-02-09%2015-56-47.png)

first 3 rows are already part of the codebase.
I added row 4 since I needed to import the Measurement.State (for previous & current fileds) and the loop was created.
___
*[`src/main/proto/wfa/measurement/internal/kingdom/measurement_log_entries_service.proto` line 35 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NNmJmHi5r5jZcbiIhCi:-NNucGDp05uLa6DJOMux:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4c90a927307db458ef7ad90fb87f79fc5c0790c0/src/main/proto/wfa/measurement/internal/kingdom/measurement_log_entries_service.proto#L35)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

"Get" is for single values. From the internal API we use streaming RPCs for multiple values.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-02-10 23:27 UTC, SanjayVas requested changes
> Reviewed 2 of 9 files at r5, 1 of 1 files at r6, 12 of 13 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841)* status: 23 of 24 files reviewed, 15 unresolved discussions (waiting on @Marco-Premier and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurement.kt` line 22 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NNmKwhB9KAd9PceoJ2y:-NNxNMQj8HU2a7gJYCys:bvk2n6h) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4c90a927307db458ef7ad90fb87f79fc5c0790c0/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurement.kt#L22)):*
<details><summary><i>Previously, Marco-Premier (marcopremier) wrote…</i></summary><blockquote>

Actually 2 out of 3 cases where ```failMeasurement``` is called

1) https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/RevokeCertificate.kt#L169

2) https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/RevokeCertificate.kt#L188

only read the MeasurementDetails through ```MeasurementDetailsReader``` which in turn returns the following result:

https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementDetailsReader.kt#L25

**There's no state inside that.** So unless I add the state into ```MeasurementDetailsReader.Result``` I still think ```StreamMeasurement``` is needed to get the state of the measurement in those 2 cases.
</blockquote></details>

Ah, sorry I missed that.

If you need to read the state for a single Measurement, implementing a new SpannerQuery is not the way to do it. SpannerQuery (and the reason it does streaming) is meant for cases where you are reading multiple things. There's no point in streaming when it's just one item.

What I would recommend doing is adding a public function to the companion object of MeasurementReader that just reads the state. Reading an entire Measurement just to get the state is wasteful (there are other places that read entire messages when they shouldn't as well). The reason I'm suggesting adding it to MeasurementReader is to try to keep SQL for reading the Measurements table in one place. You can use the `readRow` method to do this efficiently, as it looks like you're reading via primary key.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementLogEntryReader.kt` line 29 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NNxWuRODTj5UGyGFybM:-NNxWuRODTj5UGyGFybN:bcyvqce) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f2e61d27c9d5b2e7d34685c8656b27f0262e9ab9/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/MeasurementLogEntryReader.kt#L29)):*
> ```Kotlin
> import org.wfanet.measurement.internal.kingdom.measurementStateLogEntry
> 
> class MeasurementLogEntryReader : SpannerReader<MeasurementLogEntryReader.Result>() {
> ```

nit: Maybe `StateTransitionMeasurementLogEntryReader` since this only returns results for which there are `StateTransitionMeasurementLogEntries` rows, judging by the `baseSql`.



_Code quote:_
```Kotlin
MeasurementLogEntryReader
```
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurementStateTransitionLogEntry.kt` line 25 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NNxbiUc4XNxMTggiIAm:-NNxbiUc4XNxMTggiIAn:bvi9klt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f2e61d27c9d5b2e7d34685c8656b27f0262e9ab9/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurementStateTransitionLogEntry.kt#L25)):*
> ```Kotlin
> import org.wfanet.measurement.internal.kingdom.MeasurementLogEntry.Details
> 
> internal fun SpannerWriter.TransactionScope.createMeasurementStateTransitionLogEntry(
> ```

nit: The "create" name has been used for SpannerWriter implementations that are called from their respective "create" service methods. My instinct is to call this file "MeasurementLogEntries.kt" since it just contains functions relating to that. You could then move `insertDuchyMeasurementLogEntry` here from `CreateDuchyMeasurementLogEntry`.

As for the name of this function, maybe it's actually better to drop it and have callers use both `insertMeasurementLogEntry` and `insertMeasurementStateTransitionLogEntry`.

These changes together will make it easier to handle the case for adding all 3 log entry rows when the state transition is caused by a Duchy failure.



_Code quote:_
```Kotlin
create
```
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurementStateTransitionLogEntry.kt` line 30 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NNxSMYe1TAMBA6S33TL:-NNxSMYe1TAMBA6S33TM:br1qjsi) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f2e61d27c9d5b2e7d34685c8656b27f0262e9ab9/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurementStateTransitionLogEntry.kt#L30)):*
> ```Kotlin
>   nextMeasurementState: Measurement.State,
>   previousMeasurementState: Measurement.State? = null,
>   logDetails: Details
> ```

Optional params (those with defaults) go after required params.

That said, I'm really thinking a lot of trouble will be saved by simple not having a log entry for when the measurement is first created. I don't think it adds any value given that Measurements have a `create_time` field. This way you can make this non-nullable and make the column `NOT NULL`.



_Code quote:_
```Kotlin
  previousMeasurementState: Measurement.State? = null,
  logDetails: Details
```
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurementStateTransitionLogEntry.kt` line 31 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NNx_WHUCQNXgEQOKxLS:-NNx_WHVEZ7Cq5sPNsxJ:brtu7r) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f2e61d27c9d5b2e7d34685c8656b27f0262e9ab9/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurementStateTransitionLogEntry.kt#L31)):*
> ```Kotlin
>   previousMeasurementState: Measurement.State? = null,
>   logDetails: Details
> ) {
> ```

Add some `require` precondition checks just to make sure that we've covered our bases.

* `logDetails.logMessage` must be set (non-empty)
* If `nextMeasurementState` is FAILED, then `logDetails.hasErrorDetails` must be true.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurementStateTransitionLogEntry.kt` line 32 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NNxZlf7823u6ieADWo7:-NNxZlf7823u6ieADWo8:b-kt8blg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f2e61d27c9d5b2e7d34685c8656b27f0262e9ab9/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurementStateTransitionLogEntry.kt#L32)):*
> ```Kotlin
>   logDetails: Details
> ) {
>   if (previousMeasurementState != nextMeasurementState) {
> ```

Use a `require` call to check this as a precondition, since the states being equal should be an error rather than something that silently fails.



_Code quote:_
```Kotlin
previousMeasurementState != nextMeasurementState
``` [...]

2023-02-13 13:04 UTC, Marco-Premier reviewed
> Reviewed 1 of 12 files at r3, 1 of 9 files at r5, 2 of 13 files at r9.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841)* status: 8 of 32 files reviewed, 13 unresolved discussions (waiting on @SanjayVas and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/UpdateMeasurementState.kt` line 30 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NNxTT6Z19AHzvzkvJSt:-NO97jWv7Wez7eXAv8XK:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f2e61d27c9d5b2e7d34685c8656b27f0262e9ab9/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/UpdateMeasurementState.kt#L30)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Drop the default. updateMeasurementState is only called when there's a current state (i.e. it's not called on Create).
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/UpdateMeasurementState.kt` line 32 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NNxU-gy3Mr4JnL3tKRo:-NO97k7K5-ePPzr9ezZ_:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f2e61d27c9d5b2e7d34685c8656b27f0262e9ab9/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/UpdateMeasurementState.kt#L32)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Drop the default, since this should always be explicitly populated as we're always adding a log entry.
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/internal/kingdom/BUILD.bazel` line 320 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NNxZA7aA5VI393KneoZ:-NO9r9DH0xHhOyWXzVGP:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f2e61d27c9d5b2e7d34685c8656b27f0262e9ab9/src/main/proto/wfa/measurement/internal/kingdom/BUILD.bazel#L320)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Drop this dependency. See the comment for line 156 of measurement.proto
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/internal/kingdom/measurement.proto` line 292 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NNmPx6oAsKiLD84y5JY:-NO9e7YR-TueZBByWw-S:b-tvb1xr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4c90a927307db458ef7ad90fb87f79fc5c0790c0/src/main/proto/wfa/measurement/internal/kingdom/measurement.proto#L292)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The problem is that you added a dependency from measurement_proto to measurement_log_entry_proto which didn't exist before. You do not need this dependency if you drop the `measurement_state_log_entry` field from `Measurement`, which is what the comment on line 156 is saying to do.
</blockquote></details>

that is correct.  I did all the changes you suggested @SanjayVas,  however the problem was still there:

measurement.proto depends on computation_participant.proto that depends on measurement_log_entry.proto that depends once again to measurement.proto (for the Measurement.State fields)

I did explode the file (measurement_log_entry.proto) into 3 different ones in order to remove the cycle dependency.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurement.kt` line 22 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NNmKwhB9KAd9PceoJ2y:-NO95ueDD_Lx2YzqILw0:b-b4tcva) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4c90a927307db458ef7ad90fb87f79fc5c0790c0/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamMeasurement.kt#L22)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Ah, sorry I missed that.

If you need to read the state for a single Measurement, implementing a new SpannerQuery is not the way to do it. SpannerQuery (and the reason it does streaming) is meant for cases where you are reading multiple things. There's no point in streaming when it's just one item.

What I would recommend doing is adding a public function to the companion object of MeasurementReader that just reads the state. Reading an entire Measurement just to get the state is wasteful (there are other places that read entire messages when they shouldn't as well). The reason I'm suggesting adding it to MeasurementReader is to try to keep SQL for reading the Measurements table in one place. You can use the `readRow` method to do this efficiently, as it looks like you're reading via primary key.
</blockquote></details>

thanks for this!
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurementStateTransitionLogEntry.kt` line 30 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NNxSMYe1TAMBA6S33TL:-NO9EeK31At-mMhi9kK-:bsqbis0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f2e61d27c9d5b2e7d34685c8656b27f0262e9ab9/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurementStateTransitionLogEntry.kt#L30)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Optional params (those with defaults) go after required params.

That said, I'm really thinking a lot of trouble will be saved by simple not having a log entry for when the measurement is first created. I don't think it adds any value given that Measurements have a `create_time` field. This way you can make this non-nullable and make the column `NOT NULL`.
</blockquote></details>

I see your point. If reading the creation time from the measurement itself for logging purposes is not a problem, then definitely makes life easier.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurementStateTransitionLogEntry.kt` line 31 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NNx_WHUCQNXgEQOKxLS:-NO9OYaO3zXe3yoJ2Qb-:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f2e61d27c9d5b2e7d34685c8656b27f0262e9ab9/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurementStateTransitionLogEntry.kt#L31)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Add some `require` precondition checks just to make sure that we've covered our bases.

* `logDetails.logMessage` must be set (non-empty)
* If `nextMeasurementState` is FAILED, then `logDetails.hasErrorDetails` must be true.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurementStateTransitionLogEntry.kt` line 32 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NNxZlf7823u6ieADWo7:-NO9Gh7h8bzaTMQW9doC:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f2e61d27c9d5b2e7d34685c8656b27f0262e9ab9/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurementStateTransitionLogEntry.kt#L32)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Use a `require` call to check this as a precondition, since the states being equal should be an error rather than something that silently fails.
</blockquote></details>

D [...]

2023-02-13 19:59 UTC, SanjayVas requested changes
They are in separate DBs, so we cannot guarantee the same commit timestamp. What would be clearer though is if the error time send in the log entry details used the commit timestamp of the change in the Duchy DB. That would require swapping the call order to fail the computation locally in the DB before notifying the Kingdom, so we'd have to make sure that doesn't have other implications.

Feel free to add a TODO, but this would be a lower-priority item to help facilitate debugging (correlating Kingdom and Duchy logs).

> Reviewed 22 of 24 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-:-NOBHSst-z0sxP2v_Lxc:bw1mr0y)* status: 30 of 32 files reviewed, 8 unresolved discussions (waiting on @Marco-Premier and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementLogEntriesService.kt` line 63 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NOBDyqDBnTfK4A_5eLx:-NOBDyqDBnTfK4A_5eLy:b-ixbmr4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/37cf67f2ef45ecb774a1e22fb418201cb597ac76/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementLogEntriesService.kt#L63)):*
> ```Kotlin
>   override suspend fun streamStateTransitionMeasurementLogEntry(
>     request: StreamStateTransitionMeasurementLogEntriesRequest
>   ): MeasurementStateLogEntryList {
> ```

This should be returning `Flow<StateTransitionMeasurementLogEntry>`. See my comment on the service method definition.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FailComputationParticipant.kt` line 124 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NOBIgcpCmPu5TJ_9NiS:-NOBIL3kAZ3ODqSKgbuY:b-ft2ew2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/37cf67f2ef45ecb774a1e22fb418201cb597ac76/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FailComputationParticipant.kt#L124)):*
> ```Kotlin
>             MeasurementLogEntryKt.errorDetails {
>               this.type = MeasurementLogEntry.ErrorDetails.Type.PERMANENT
>               this.errorTime = Clock.systemUTC().protoTimestamp()
> ```

nit: Add a TODO here to plumb in a separate clock instance so we're not hard-coding the system one.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FailComputationParticipant.kt` line 124 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NOBJyoj1Xvv6thh4EoV:-NOBJyoj1Xvv6thh4EoW:b5kjlb6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/37cf67f2ef45ecb774a1e22fb418201cb597ac76/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FailComputationParticipant.kt#L124)):*
> ```Kotlin
>             MeasurementLogEntryKt.errorDetails {
>               this.type = MeasurementLogEntry.ErrorDetails.Type.PERMANENT
>               this.errorTime = Clock.systemUTC().protoTimestamp()
> ```

As an aside, I believe the original intent of this separate time in ErrorDetails was to get the time from the system that triggered the failure (e.g. for Duchy log entries, this is the time at the Duchy). I'm not entirely certain we need it, as we don't defer error logging. We couldn't even possibly defer for permanent errors since the log entry gets added in the same transaction.

You don't need to do anything about this now, I'm just recording info/musings.



_Code quote:_
```Kotlin
this.errorTime
```
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/MeasurementLogEntries.kt` line 44 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NOBGadq3OQRZLoOliKz:-NOBGadq3OQRZLoOliL-:b2ni8l0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/37cf67f2ef45ecb774a1e22fb418201cb597ac76/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/MeasurementLogEntries.kt#L44)):*
> ```Kotlin
> }
> 
> internal fun SpannerWriter.TransactionScope.insertMeasurementStateTransitionLogEntry(
> ```

nit



_Suggestion:_
```Kotlin
insertStateTransitionMeasurementLogEntry
```
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/RefuseRequisition.kt` line 83 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NOBKDZo8T2UA-POyIwA:-NOBKDZp8oFvleYUu6r3:bkk1qum) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/37cf67f2ef45ecb774a1e22fb418201cb597ac76/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/RefuseRequisition.kt#L83)):*
> ```Kotlin
>           MeasurementLogEntryKt.errorDetails {
>             this.type = MeasurementLogEntry.ErrorDetails.Type.PERMANENT
>             this.errorTime = Clock.systemUTC().protoTimestamp()
> ```

nit: Same here re:TODO for plumbing in a `Clock` instance dependency.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/RevokeCertificate.kt` line 242 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NOBKQoX8Kw8ZgAAxHcl:-NOBKQoX8Kw8ZgAAxHcm:bkk1qum) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/37cf67f2ef45ecb774a1e22fb418201cb597ac76/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/RevokeCertificate.kt#L242)):*
> ```Kotlin
>           MeasurementLogEntryKt.errorDetails {
>             this.type = MeasurementLogEntry.ErrorDetails.Type.PERMANENT
>             this.errorTime = Clock.systemUTC().protoTimestamp()
> ```

nit: Same here re:TODO for plumbing in a `Clock` instance dependency.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/StateTransitionMeasurementLogEntryReader.kt` line 92 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NOBFChRAQfXTknUhuyE:-NOBFChRAQfXTknUhuyF:b-p07ysj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/37cf67f2ef45ecb774a1e22fb418201cb597ac76/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/StateTransitionMeasurementLogEntryReader.kt#L92)):*
> ```Kotlin
>           stateTransitionMeasurementStruct.getProtoEnum(
>             "CurrentMeasurementState",
>             org.wfanet.measurement.internal.kingdom.Measurement.State::forNumber
> ```

This is already an imported symbol. No need to fully qualify.



_Code quote:_
```Kotlin
org.wfanet.measurement.internal.kingdom.Measurement
```


<!-- Sent from Reviewable.io -->

2023-02-13 22:52 UTC, stevenwarejones approved these changes
> Reviewed 4 of 13 files at r9, 24 of 24 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841)* status: all files reviewed, 9 unresolved discussions (waiting on @Marco-Premier)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/UpdateMeasurementState.kt` line 48 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NOBy25CAyGpjtMhX_QT:-NOBy25CAyGpjtMhX_QU:b6uz5bm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/37cf67f2ef45ecb774a1e22fb418201cb597ac76/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/UpdateMeasurementState.kt#L48)):*
> ```Kotlin
> 
>   if (nextState == Measurement.State.FAILED) {
>     require(logDetails.hasError())
> ```

maybe  little more descriptive?
```
require(logDetails.hasError()) {
  "$logDetails must have an error when state is FAILED." 
}
```



<!-- Sent from Reviewable.io -->

2023-02-14 22:25 UTC, stevenwarejones approved these changes
> Reviewed 13 of 13 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841)* status: all files reviewed, 4 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FailComputationParticipant.kt` line 124 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NOBJyoj1Xvv6thh4EoV:-NOH0o4sCIqawVXgMgzd:bay9a5c) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/37cf67f2ef45ecb774a1e22fb418201cb597ac76/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FailComputationParticipant.kt#L124)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

As an aside, I believe the original intent of this separate time in ErrorDetails was to get the time from the system that triggered the failure (e.g. for Duchy log entries, this is the time at the Duchy). I'm not entirely certain we need it, as we don't defer error logging. We couldn't even possibly defer for permanent errors since the log entry gets added in the same transaction.

You don't need to do anything about this now, I'm just recording info/musings.
</blockquote></details>

yeah - i agree - it should be the duchy time. It actually is misleading to use the kingdom clock.


<!-- Sent from Reviewable.io -->

2023-02-14 22:43 UTC, SanjayVas requested changes
> Reviewed 12 of 13 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841)* status: all files reviewed, 12 unresolved discussions (waiting on @Marco-Premier)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementLogEntriesService.kt` line 44 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NOH3B9yD-lmhFp9dIHp:-NOH3B9yD-lmhFp9dIHq:bj84zoo) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b3af7ed4161f31077eaafb6cfddc58dd1ad956f0/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerMeasurementLogEntriesService.kt#L44)):*
> ```Kotlin
>       }
>     }
> ```

nit: unrelated whitespace changes
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamStateTransitionMeasurementLogEntries.kt` line 28 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NOH1pOfAtKohnAs9Md4:-NOH1pOfAtKohnAs9Md5:b2yw9r7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3d56ebf2b7cc5e49756dc24a228c5caa9d53a80c/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamStateTransitionMeasurementLogEntries.kt#L28)):*
> ```Kotlin
>       appendClause(
>         """
>         WHERE Measurements.ExternalMeasurementId = @externalMeasurementId
> ```

ExternalMeasurementId alone is insufficient to uniquely identify a Measurement.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurement.kt` line 1 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NOH4nljCvVBqiU45dG8:-NOH4nljCvVBqiU45dG9:b-9h9z1x) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3d56ebf2b7cc5e49756dc24a228c5caa9d53a80c/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurement.kt#L1)):*
> ```Kotlin
> // Copyright 2021 The Cross-Media Measurement Authors
> ```

Shouldn't this file be unchanged by this PR now?
___
*[`src/main/proto/wfa/measurement/internal/kingdom/measurement_log_entries_service.proto` line 36 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NOH152u39UmTUduDkPh:-NOH152u39UmTUduDkPi:undefined) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3d56ebf2b7cc5e49756dc24a228c5caa9d53a80c/src/main/proto/wfa/measurement/internal/kingdom/measurement_log_entries_service.proto#L36)):*
> ```protobuf
> 
>   // Retrieve all measurement state transition log entries for a given measurement
>   rpc StreamStateTransitionMeasurementLogEntry(StreamStateTransitionMeasurementLogEntriesRequest) returns (stream StateTransitionMeasurementLogEntry);
> ```





_Suggestion:_
```protobuf
StreamStateTransitionMeasurementLogEntries
```
___
*[`src/main/proto/wfa/measurement/internal/kingdom/measurement_log_entries_service.proto` line 48 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NOH19Tl2Y-EcvDedox5:-NOH19Tl2Y-EcvDedox6:bt8korl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3d56ebf2b7cc5e49756dc24a228c5caa9d53a80c/src/main/proto/wfa/measurement/internal/kingdom/measurement_log_entries_service.proto#L48)):*
> ```protobuf
> 
> message StreamStateTransitionMeasurementLogEntriesRequest {
>   fixed64 external_measurement_id = 1;
> ```

Why was `external_measurement_consumer_id` dropped? Measurement IDs are only guaranteed to be unique for a given MeasurementConsumer, meaning you need both IDs to uniquely identify a Measurement.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/StateTransitionMeasurementLogEntryReader.kt` line 36 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NOH40z3ERzKnHbixYl8:-NOH40z46fIOjhKNV_jT:b-5ygk4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3d56ebf2b7cc5e49756dc24a228c5caa9d53a80c/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/StateTransitionMeasurementLogEntryReader.kt#L36)):*
> ```Kotlin
>       StateTransitionMeasurementLogEntries.CurrentMeasurementState,
>       StateTransitionMeasurementLogEntries.MeasurementConsumerId,
>       StateTransitionMeasurementLogEntries.MeasurementId
> ```

Don't you need to select columns from MeasurementLogEntries in order to populate the `log_entry` field of `StateTransitionMeasurementLogEntry`?
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/StateTransitionMeasurementLogEntryReader.kt` line 47 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NOH3ZMf7As7iSH0ivpk:-NOH3ZMf7As7iSH0ivpl:bg2sh03) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3d56ebf2b7cc5e49756dc24a228c5caa9d53a80c/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/StateTransitionMeasurementLogEntryReader.kt#L47)):*
> ```Kotlin
>     Result(fillStateTransitionLogView(struct))
> 
>   private fun fillStateTransitionLogView(struct: Struct): StateTransitionMeasurementLogEntry {
> ```

 There are no views involved here.



_Code quote:_
```Kotlin
View
```
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/StateTransitionMeasurementLogEntryReader.kt` line 49 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NOH2NUO7cWwyLOEk9Gt:-NOH2NUO7cWwyLOEk9Gu:bhj90zv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3d56ebf2b7cc5e49756dc24a228c5caa9d53a80c/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/StateTransitionMeasurementLogEntryReader.kt#L49)):*
> ```Kotlin
>   private fun fillStateTransitionLogView(struct: Struct): StateTransitionMeasurementLogEntry {
>     return stateTransitionMeasurementLogEntry {
>       this.currentState =
> ```

nit: unnecessary qualification



_Code quote:_
```Kotlin
this.
```
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/StateTransitionMeasurementLogEntryReader.kt` line 52 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NOH2iGH9dM4WIqKJx0R:-NOH2iGH9dM4WIqKJx0S:b-im5v8m) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3d56ebf2b7cc5e49756dc24a228c5caa9d53a80c/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/StateTransitionMeasurementLogEntryReader.kt#L52)):*
> ```Kotlin
>         struct.getProtoEnum("CurrentMeasurementState", Measurement.State::forNumber)
>       this.previousState =
>         if (struct.isNull("PreviousMeasurementState")) Measurement.State.STATE_UNSPECIFIED
> ```

This column is `NOT NULL` now.

Also we generally prefer not explicitly setting to default values and instead just not setting the field.



_Code quote:_
```Kotlin
if (struct.isNull("PreviousMeasurementState"))
```
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/StateTransitionMeasurementLogEntryReader.kt` line 56 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NOH4XSC0fj7U8f_zbr1:-NOH4XSC0fj7U8f_zbr2:b45h) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3d56ebf2b7cc5e49756dc24a228c5caa9d53a80c/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/StateTransitionMeasurementLogEntryReader.kt#L56)):*
> ```Kotlin
>       this.logEntry = measurementLogEntry {
>         this.createTime = struct.getTimestamp("Cre [...]

2023-02-15 12:38 UTC, Marco-Premier reviewed
> Reviewed 2 of 13 files at r11.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841)* status: all files reviewed, 10 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamStateTransitionMeasurementLogEntries.kt` line 28 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NOH1pOfAtKohnAs9Md4:-NOJHWUH58I3e_AP1Ubn:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3d56ebf2b7cc5e49756dc24a228c5caa9d53a80c/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamStateTransitionMeasurementLogEntries.kt#L28)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

ExternalMeasurementId alone is insufficient to uniquely identify a Measurement.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurement.kt` line 1 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NOH4nljCvVBqiU45dG8:-NOK49-l7cJXq1N3_wa_:bjqlquf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3d56ebf2b7cc5e49756dc24a228c5caa9d53a80c/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateMeasurement.kt#L1)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Shouldn't this file be unchanged by this PR now?
</blockquote></details>

reverted to its original state
___
*[`src/main/proto/wfa/measurement/internal/kingdom/measurement_log_entries_service.proto` line 36 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NOH152u39UmTUduDkPh:-NOJGqRD9kvbOossnCDD:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3d56ebf2b7cc5e49756dc24a228c5caa9d53a80c/src/main/proto/wfa/measurement/internal/kingdom/measurement_log_entries_service.proto#L36)):*
> ```protobuf
> 
>   // Retrieve all measurement state transition log entries for a given measurement
>   rpc StreamStateTransitionMeasurementLogEntry(StreamStateTransitionMeasurementLogEntriesRequest) returns (stream StateTransitionMeasurementLogEntry);
> ```

Done.
___
*[`src/main/proto/wfa/measurement/internal/kingdom/measurement_log_entries_service.proto` line 48 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NOH19Tl2Y-EcvDedox5:-NOJEoAV6ykGMj8WHBlI:b3r0m0f) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3d56ebf2b7cc5e49756dc24a228c5caa9d53a80c/src/main/proto/wfa/measurement/internal/kingdom/measurement_log_entries_service.proto#L48)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Why was `external_measurement_consumer_id` dropped? Measurement IDs are only guaranteed to be unique for a given MeasurementConsumer, meaning you need both IDs to uniquely identify a Measurement.
</blockquote></details>

I thought that measurement id was unique across all the measurement consumers. Adding back the measurement consumer id
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/StateTransitionMeasurementLogEntryReader.kt` line 36 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NOH40z3ERzKnHbixYl8:-NOJKF6L6qQHHsVz8hwO:b8d9xm6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3d56ebf2b7cc5e49756dc24a228c5caa9d53a80c/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/StateTransitionMeasurementLogEntryReader.kt#L36)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Don't you need to select columns from MeasurementLogEntries in order to populate the `log_entry` field of `StateTransitionMeasurementLogEntry`?
</blockquote></details>

Yes, I fetched only required fields needed for testing but I agree: this reader should know nothing about tests and return the whole message.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/StateTransitionMeasurementLogEntryReader.kt` line 47 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NOH3ZMf7As7iSH0ivpk:-NOJIChh0URzmFAH1lBf:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3d56ebf2b7cc5e49756dc24a228c5caa9d53a80c/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/StateTransitionMeasurementLogEntryReader.kt#L47)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

 There are no views involved here.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/StateTransitionMeasurementLogEntryReader.kt` line 52 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NOH2iGH9dM4WIqKJx0R:-NOJIYYY3gK8btP2P99C:b-ybp2yh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3d56ebf2b7cc5e49756dc24a228c5caa9d53a80c/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/StateTransitionMeasurementLogEntryReader.kt#L52)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This column is `NOT NULL` now.

Also we generally prefer not explicitly setting to default values and instead just not setting the field.
</blockquote></details>

Missed that
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/StateTransitionMeasurementLogEntryReader.kt` line 56 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NOH4XSC0fj7U8f_zbr1:-NOJKChH1gaXiuM_KMdu:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3d56ebf2b7cc5e49756dc24a228c5caa9d53a80c/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/StateTransitionMeasurementLogEntryReader.kt#L56)):*
> ```Kotlin
>       this.logEntry = measurementLogEntry {
>         this.createTime = struct.getTimestamp("CreateTime").toProto()
>         this.externalMeasurementId = struct.getLong("MeasurementId")
> ```

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/StateTransitionMeasurementLogEntryReader.kt` line 57 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NOH4_dx7XPEwv4svWO8:-NOJNh7B3DyaP4wQAEsC:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3d56ebf2b7cc5e49756dc24a228c5caa9d53a80c/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/StateTransitionMeasurementLogEntryReader.kt#L57)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This appears to be missing the log entry details.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-02-15 19:15 UTC, SanjayVas requested changes
> Reviewed 1 of 24 files at r10, 6 of 6 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841)* status: all files reviewed, 4 unresolved discussions (waiting on @Marco-Premier)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementLogEntriesServiceTest.kt` line 87 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NOLV-B_59Pa-oVL0J-f:-NOLV-B_59Pa-oVL0J-g:b-709r1y) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7bbae3576e3ee169d08c633765623a5ffc6a32a1/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementLogEntriesServiceTest.kt#L87)):*
> ```Kotlin
>   protected abstract fun newServices(idGenerator: IdGenerator): Services<T>
> 
>   private fun readMeasurementStateLog(
> ```

Same note here re: extracting this function hurting readability of the test, as it's hiding the call to the subject under test (SUT).
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementLogEntriesServiceTest.kt` line 310 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NOLLRudDUZ5Cl1xe7Wi:-NOLLRudDUZ5Cl1xe7Wj:b-3afoy1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7bbae3576e3ee169d08c633765623a5ffc6a32a1/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementLogEntriesServiceTest.kt#L310)):*
> ```Kotlin
>         )
> 
>       assertThat(
> ```

I don't think this assertion is necessary. We're already confirming at the end that there's exactly one entry from PENDING_REQUISITION_PARAMS to CANCELLED.

As a future tip, make use of Truth's support for collections. e.g.
```kotlin
assertThat(readLog().toList()).isEmpty()
```
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt` line 128 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NOLOYGh-IAcKHEMHnXP:-NOLOYGh-IAcKHEMHnXQ:b-lsosxg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7bbae3576e3ee169d08c633765623a5ffc6a32a1/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt#L128)):*
> ```Kotlin
>   protected abstract fun newServices(idGenerator: IdGenerator): Services<T>
> 
>   private suspend fun readMeasurementByComputationId(externalComputationId: Long): Measurement {
> ```

I think factoring these out actually made readability worse for this test. The reason being that this is testing the Measurements service, meaning we want it to be clear in each test method what service method we're calling and what the request is.
___
*[`src/main/proto/wfa/measurement/internal/kingdom/measurement_log_entries_service.proto` line 48 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NOH19Tl2Y-EcvDedox5:-NOLT0snAQpnNpJTz4YY:b-p4fect) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3d56ebf2b7cc5e49756dc24a228c5caa9d53a80c/src/main/proto/wfa/measurement/internal/kingdom/measurement_log_entries_service.proto#L48)):*
> I thought that measurement id was unique across all the measurement consumers.

For future reference, you can determine this by looking at the [API definition](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/main/src/main/proto/wfa/measurement/api/v2alpha/measurement.proto). The Measurement resource has the pattern `measurementConsumers/{measurement_consumer}/measurements/{measurement}`. The items in curly braces are the ID segments. This shows that you need both IDs to form a unique resource reference, as the measurements resource collection is a child of a MeasurementConsumer resource.

In the internal API, those ID segments are mapped to external ID fields.


<!-- Sent from Reviewable.io -->

2023-02-17 08:16 UTC, Marco-Premier reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841)* status: all files reviewed, 4 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementLogEntriesServiceTest.kt` line 87 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NOLV-B_59Pa-oVL0J-f:-NOPVU4L7m0LHT4Nx5YV:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7bbae3576e3ee169d08c633765623a5ffc6a32a1/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementLogEntriesServiceTest.kt#L87)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Same note here re: extracting this function hurting readability of the test, as it's hiding the call to the subject under test (SUT).
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementLogEntriesServiceTest.kt` line 310 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NOLLRudDUZ5Cl1xe7Wi:-NOPTanPEU2_COwbDRoW:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7bbae3576e3ee169d08c633765623a5ffc6a32a1/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementLogEntriesServiceTest.kt#L310)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I don't think this assertion is necessary. We're already confirming at the end that there's exactly one entry from PENDING_REQUISITION_PARAMS to CANCELLED.

As a future tip, make use of Truth's support for collections. e.g.
```kotlin
assertThat(readLog().toList()).isEmpty()
```
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt` line 128 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NOLOYGh-IAcKHEMHnXP:-NOPUtJn3zoE1Trsl3GF:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7bbae3576e3ee169d08c633765623a5ffc6a32a1/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementsServiceTest.kt#L128)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I think factoring these out actually made readability worse for this test. The reason being that this is testing the Measurements service, meaning we want it to be clear in each test method what service method we're calling and what the request is.
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/internal/kingdom/measurement_log_entries_service.proto` line 48 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NOH19Tl2Y-EcvDedox5:-NOPVhEF7CElleJuhN4S:bz0ndtk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3d56ebf2b7cc5e49756dc24a228c5caa9d53a80c/src/main/proto/wfa/measurement/internal/kingdom/measurement_log_entries_service.proto#L48)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> I thought that measurement id was unique across all the measurement consumers.

For future reference, you can determine this by looking at the [API definition](https://github.com/world-federation-of-advertisers/cross-media-measurement-api/blob/main/src/main/proto/wfa/measurement/api/v2alpha/measurement.proto). The Measurement resource has the pattern `measurementConsumers/{measurement_consumer}/measurements/{measurement}`. The items in curly braces are the ID segments. This shows that you need both IDs to form a unique resource reference, as the measurements resource collection is a child of a MeasurementConsumer resource.

In the internal API, those ID segments are mapped to external ID fields.
</blockquote></details>

thanks for clarifying that @SanjayVas 


<!-- Sent from Reviewable.io -->

2023-02-17 17:34 UTC, SanjayVas requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841)* status: all files reviewed, 4 unresolved discussions (waiting on @Marco-Premier)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FailComputationParticipant.kt` line 119 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NOVQU-h47ewlptu3K74:-NOVQU-i9VRQhvoFupOR:b-kliy3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7bbae3576e3ee169d08c633765623a5ffc6a32a1/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FailComputationParticipant.kt#L119)):*
> ```Kotlin
> 
>       val measurementLogEntryDetails =
>         MeasurementLogEntryKt.details {
> ```

`FailComputationParticipantRequest` includes a `MeasurementLogEntry.Details` message. Use that rather than building a new one.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementLogEntriesServiceTest.kt` line 87 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NOLV-B_59Pa-oVL0J-f:-NOVR9Cx274LevQLHKFu:b-lqhjmj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7bbae3576e3ee169d08c633765623a5ffc6a32a1/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementLogEntriesServiceTest.kt#L87)):*
<details><summary><i>Previously, Marco-Premier (marcopremier) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

This appears unchanged. Did you forget to push your changes?


<!-- Sent from Reviewable.io -->

2023-02-20 09:08 UTC, Marco-Premier reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841)* status: 30 of 33 files reviewed, 4 unresolved discussions (waiting on @SanjayVas and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FailComputationParticipant.kt` line 119 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NOVQU-h47ewlptu3K74:-NOi0Wzq7QqaD5LN_07c:btjme7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7bbae3576e3ee169d08c633765623a5ffc6a32a1/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FailComputationParticipant.kt#L119)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

`FailComputationParticipantRequest` includes a `MeasurementLogEntry.Details` message. Use that rather than building a new one.
</blockquote></details>

nice, thanks
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementLogEntriesServiceTest.kt` line 87 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NOLV-B_59Pa-oVL0J-f:-NOi-frB1ayTwKxqnAIj:bhrgf9k) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7bbae3576e3ee169d08c633765623a5ffc6a32a1/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementLogEntriesServiceTest.kt#L87)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This appears unchanged. Did you forget to push your changes?
</blockquote></details>

not sure tbh. Refreshed the code fixing this.



_Code quote:_
```Kotlin
readMeasurementStateLog
```


<!-- Sent from Reviewable.io -->

2023-02-21 20:06 UTC, SanjayVas requested changes
> Reviewed 3 of 3 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841)* status: all files reviewed, 4 unresolved discussions (waiting on @Marco-Premier)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FailComputationParticipant.kt` line 82 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NOpVw4c0aBVb5FHNaU0:-NOpVw4c0aBVb5FHNaU1:b-369v0z) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9f79f706c0096b2f1ab28a25543975212a792847/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FailComputationParticipant.kt#L82)):*
> ```Kotlin
>       Measurement.State.PENDING_PARTICIPANT_CONFIRMATION,
>       Measurement.State.PENDING_COMPUTATION,
>       Measurement.State.FAILED, -> {}
> ```

I know this wasn't changed in this PR, but this value should also result in a `MeasurementStateIllegalException` as you shouldn't be able to mutate a Measurement that's already in a terminal state. If you move it to the other case, then you can drop the `measurementState != Measurement.State.FAILED` check later in this function.



_Code quote:_
```Kotlin
Measurement.State.FAILED, -> {}
```
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FailComputationParticipant.kt` line 117 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NOpVP8HD1ktxuMQ_nnQ:-NOpVP8HD1ktxuMQ_nnR:byr7g12) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9f79f706c0096b2f1ab28a25543975212a792847/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FailComputationParticipant.kt#L117)):*
> ```Kotlin
>       val measurementLogEntryDetails =
>         MeasurementLogEntryKt.details {
>           logMessage = "Measurement failed due to a failing computation participant"
> ```

Use the `error_message` field from `FailComputationParticipantRequest`.



_Code quote:_
```Kotlin
logMessage = "Measurement failed due to a failing computation participant"
```
___
*[`src/main/proto/wfa/measurement/internal/kingdom/measurement.proto` line 130 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NOpZ2y28TC2tghdB99W:-NOpZ2y28TC2tghdB99X:bf405ae) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9f79f706c0096b2f1ab28a25543975212a792847/src/main/proto/wfa/measurement/internal/kingdom/measurement.proto#L130)):*
> ```protobuf
> 
>     // Set when the state is set to FAILED.
>     Failure failure = 8;
> ```

Would you mind adding a TODO here to mark this field as deprecated, reading any Failure information from the corresponding MeasurementLogEntries row instead? You can feel free to put my username as the context.

With this PR, we'll always have a MeasurementLogEntries row that corresponds to the state change to FAILED, making this field redundant. We might need to record the Failure reason in the MeasurementLogEntries table in order to do this.
___
*[`src/main/proto/wfa/measurement/internal/kingdom/measurement.proto` line 153 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NOpYslUA6XPeYsygGLv:-NOpYslUA6XPeYsygGLw:bj84zoo) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9f79f706c0096b2f1ab28a25543975212a792847/src/main/proto/wfa/measurement/internal/kingdom/measurement.proto#L153)):*
> ```protobuf
>   // Only set for COMPUTATION view.
>   repeated ComputationParticipant computation_participants = 13;
> ```

nit: unrelated whitespace changes


<!-- Sent from Reviewable.io -->

2023-02-22 08:38 UTC, Marco-Premier reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841)* status: 30 of 33 files reviewed, 2 unresolved discussions (waiting on @SanjayVas and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FailComputationParticipant.kt` line 82 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NOpVw4c0aBVb5FHNaU0:-NOsAe976ysf1M4BgF-Z:b-8lfzf7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9f79f706c0096b2f1ab28a25543975212a792847/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FailComputationParticipant.kt#L82)):*
> measurementState != Measurement.State.FAILED
nice, agree
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FailComputationParticipant.kt` line 117 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-NOpVP8HD1ktxuMQ_nnQ:-NOsBNDY7EOevwOohNdl:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9f79f706c0096b2f1ab28a25543975212a792847/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/FailComputationParticipant.kt#L117)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Use the `error_message` field from `FailComputationParticipantRequest`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-02-22 18:26 UTC, SanjayVas approved these changes
> Reviewed 3 of 3 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Marco-Premier)



<!-- Sent from Reviewable.io -->

2023-02-24 12:44 UTC, Marco-Premier reviewed
Branch keeps becoming outdated. Just rebased it against main

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-:-NP2RpKI5Mq_EmDLmMBA:b-ik1osc)* status: 24 of 33 files reviewed, all discussions resolved (waiting on @SanjayVas and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2023-02-25 00:09 UTC, SanjayVas approved these changes
Just FYI, you don't need to comment on rebasing the branch as that's a normal expected thing given that we require linear history. If you've already gotten approval and haven't made any significant changes (e.g. adding new files), you can just mark all the files as reviewed yourself to satisfy the Reviewable check.

I'm seeing if we can eventually get Reviewable to [ignore base changes](https://changelog.reviewable.io/base-changes-only-247444)

> Reviewed 9 of 9 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841#-:-NP4t83A-oWKnq2_HmvR:b-mg5y6y)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Marco-Premier)



<!-- Sent from Reviewable.io -->

2023-02-27 08:48 UTC, Marco-Premier reviewed
> Reviewed 1 of 8 files at r2, 2 of 17 files at r4, 9 of 24 files at r10, 3 of 13 files at r11, 4 of 6 files at r12, 2 of 3 files at r13, 2 of 3 files at r14, 9 of 9 files at r15, 1 of 1 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Marco-Premier)



<!-- Sent from Reviewable.io -->

2023-02-27 09:16 UTC, Marco-Premier reviewed
> Reviewed 3 of 3 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/841)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Marco-Premier)



<!-- Sent from Reviewable.io -->

2023-02-27 09:45 UTC, merged