Implementation of Internal spanner eventgroup deletion
world-federation-of-advertisers/cross-media-measurement pull request #852
Opened 2023-02-10 17:02 UTC by jcorilla

2023-02-13 18:35 UTC, SanjayVas commented
Adding @tristanvuong2021 for first pass.

2023-02-13 19:46 UTC, tristanvuong2021 requested changes
> Reviewed 7 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/852)* status: 7 of 13 files reviewed, 5 unresolved discussions (waiting on @jcorilla, @kungfucraig, and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateEventGroup.kt` line 109 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/852#-NOBDCn79Pw5ZwrlNUUo:-NOBDCn79Pw5ZwrlNUUp:b-y4aabe) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/49ce0dcbfd67de7de11a4bcc10eeca1294759ab1/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateEventGroup.kt#L109)):*
> ```Kotlin
>       .toBuilder()
>       .setExternalEventGroupId(externalEventGroupId.value)
>       .setState(EventGroup.State.ACTIVE)
> ```

Since you are changing this, might as well use copy instead of builder.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/DeleteEventGroup.kt` line 33 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/852#-NOBDMAHBY8SwKjFSWhU:-NOBDMAHBY8SwKjFSWhV:b-7c60ua) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/49ce0dcbfd67de7de11a4bcc10eeca1294759ab1/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/DeleteEventGroup.kt#L33)):*
> ```Kotlin
>  * Throws a subclass of [KingdomInternalException] on [execute].
>  * @throws [EventGroupNotFoundException] EventGroup not found
>  * @throws [EventGroupInvalidArgsException] DataProvider ids mismatch
> ```

I don't see EventGroupInvalidArgsException being thrown.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/DeleteEventGroup.kt` line 67 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/852#-NOBDUHy-xukGU2zZqxA:-NOBDUHy-xukGU2zZqxB:bvlytg3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/49ce0dcbfd67de7de11a4bcc10eeca1294759ab1/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/DeleteEventGroup.kt#L67)):*
> ```Kotlin
> 
>     return internalEventGroupResult.eventGroup
>       .toBuilder()
> ```

Use copy
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt` line 308 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/852#-NOBJ2tOE4GTC3wP5yf7:-NOBJ2tOE4GTC3wP5yf8:bmze22z) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/49ce0dcbfd67de7de11a4bcc10eeca1294759ab1/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/EventGroupsService.kt#L308)):*
> ```Kotlin
>             listEventGroupsPageToken
>               .toStreamEventGroupsRequest()
>               .toBuilder()
> ```

The page token needs to be updated to include showDeleted.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt` line 849 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/852#-NOBItJ61ffbD2e8T5ZQ:-NOBItJ61ffbD2e8T5ZR:bvlytg3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/49ce0dcbfd67de7de11a4bcc10eeca1294759ab1/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt#L849)):*
> ```Kotlin
>       .isEqualTo(
>         createdEventGroup
>           .toBuilder()
> ```

Use copy


<!-- Sent from Reviewable.io -->

2023-02-14 19:58 UTC, jcorilla reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/852)* status: 10 of 14 files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/DeleteEventGroup.kt` line 33 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/852#-NOBDMAHBY8SwKjFSWhU:-NOGVNQo3OCqfMNnr914:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/49ce0dcbfd67de7de11a4bcc10eeca1294759ab1/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/DeleteEventGroup.kt#L33)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Catch block was removed, but comment is still there
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-02-15 03:29 UTC, tristanvuong2021 requested changes
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/852)* status: 10 of 14 files reviewed, 1 unresolved discussion (waiting on @jcorilla and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerEventGroupsService.kt` line 116 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/852#-NOI69SLCYtkryW0Ekur:-NOI69SLCYtkryW0Ekus:b-6cc3ap) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a5186d3087f4d891426e7681c0df3d2e44d5a4b8/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerEventGroupsService.kt#L116)):*
> ```Kotlin
> 
>     val eventGroup =
>       EventGroup.newBuilder()
> ```

Use the Kotlin builder instead of newBuilder


<!-- Sent from Reviewable.io -->

2023-02-15 22:42 UTC, tristanvuong2021 reviewed
> Reviewed 1 of 13 files at r1, 2 of 8 files at r2, 1 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/852)* status: 13 of 14 files reviewed, 1 unresolved discussion (waiting on @jcorilla and @SanjayVas)



<!-- Sent from Reviewable.io -->

2023-02-15 22:49 UTC, tristanvuong2021 requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/852)* status: 13 of 14 files reviewed, 1 unresolved discussion (waiting on @jcorilla and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerEventGroupsService.kt` line 123 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/852#-NOMFj6F4G2yZbX0aXa3:-NOMFj6F4G2yZbX0aXa4:bpstws3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b618f15e10942c020d3563d6ec5346b5bfaecbc6/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerEventGroupsService.kt#L123)):*
> ```Kotlin
>     try {
>       return DeleteEventGroup(eventGroup).execute(client, idGenerator)
>     } catch (e: DataProviderNotFoundException) {
> ```

Is DataProviderNotFoundException expected? I don't see where it is thrown.


<!-- Sent from Reviewable.io -->

2023-02-16 19:31 UTC, jcorilla reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/852)* status: 13 of 14 files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerEventGroupsService.kt` line 116 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/852#-NOI69SLCYtkryW0Ekur:-NOQet_37UzW4JTFflik:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a5186d3087f4d891426e7681c0df3d2e44d5a4b8/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerEventGroupsService.kt#L116)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Use the Kotlin builder instead of newBuilder
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerEventGroupsService.kt` line 123 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/852#-NOMFj6F4G2yZbX0aXa3:-NOQevxcEVtLQVoRs6DR:bu08sas) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b618f15e10942c020d3563d6ec5346b5bfaecbc6/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerEventGroupsService.kt#L123)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Is DataProviderNotFoundException expected? I don't see where it is thrown.
</blockquote></details>

You're right, removing the exception since it's not expected. The check for the dataProvider being valid is done when reading the eventGroup/checking if it exists - similar to updateEventGroup. So the exception thrown is the eventgroup not found exception


<!-- Sent from Reviewable.io -->

2023-02-16 19:33 UTC, tristanvuong2021 reviewed
> Reviewed 1 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/852)* status: 13 of 14 files reviewed, all discussions resolved (waiting on @SanjayVas)



<!-- Sent from Reviewable.io -->

2023-02-16 19:33 UTC, tristanvuong2021 reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/852)* status: 13 of 14 files reviewed, all discussions resolved (waiting on @SanjayVas)



<!-- Sent from Reviewable.io -->

2023-02-16 19:34 UTC, tristanvuong2021 approved these changes
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/852)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)



<!-- Sent from Reviewable.io -->

2023-02-17 19:41 UTC, SanjayVas requested changes
> Reviewed 6 of 13 files at r1, 6 of 8 files at r2, 1 of 2 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/852)* status: all files reviewed, 9 unresolved discussions (waiting on @jcorilla)

___
*[`build/repositories.bzl` line 41 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/852#-NOVlvAL7e0DpDsHZbCt:-NOVlvAL7e0DpDsHZbCu:bon6krz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5cddec8f74715db33c2081e5bb2bb1eab7c48006/build/repositories.bzl#L41)):*
> ```Starlark
>         name = "wfa_measurement_proto",
>         repo = "cross-media-measurement-api",
>         #       ToDo: revert before merging
> ```

Use our documented [TODO format](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/docs/code-style.md#todos)



_Code quote:_
```Starlark
ToDo
```
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamEventGroups.kt` line 62 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/852#-NOVn4gV2fIrWvI7tX-H:-NOVn4gV2fIrWvI7tX-I:b-luxodi) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5cddec8f74715db33c2081e5bb2bb1eab7c48006/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamEventGroups.kt#L62)):*
> ```Kotlin
> 
>     if (!filter.showDeleted) {
>       conjuncts.add("State != $DELETED_STATE")
> ```

You can use other types directly with Kotlin string templates. `toString()` will be called for you if needed.



_Suggestion:_
```Kotlin
${EventGroup.State.DELETED}
```
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/DeleteEventGroup.kt` line 35 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/852#-NOVneXD2hNDEvptqnU5:-NOVneXD2hNDEvptqnU6:b-z3xw0a) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5cddec8f74715db33c2081e5bb2bb1eab7c48006/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/DeleteEventGroup.kt#L35)):*
> ```Kotlin
>  * Throws a subclass of [KingdomInternalException] on [execute].
>  *
>  * @throws [EventGroupNotFoundException] EventGroup not found
> ```

This `@throws` doesn't belong here, since the constructor doesn't throw this exception. This is why we have a comment indicating what it throws on `execute`.

Instead group this with the comment above comment to document *which* subclasses get thrown. See `CreateRecurringExchange` as an example.

Unfortunately, it looks like a number of our SpannerWriter implementations do this incorrectly.



_Code quote:_
```Kotlin
@throws [EventGroupNotFoundException] EventGroup not found
```
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt` line 522 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/852#-NOVqBg874B8kNWX6iBx:-NOVqBg874B8kNWX6iBy:bj15xpb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5cddec8f74715db33c2081e5bb2bb1eab7c48006/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt#L522)):*
> ```Kotlin
>   return when (this) {
>     InternalEventGroup.State.STATE_UNSPECIFIED,
>     InternalEventGroup.State.UNRECOGNIZED -> EventGroup.State.STATE_UNSPECIFIED
> ```

UNRECOGNIZED is an error



_Code quote:_
```Kotlin
EventGroup.State.STATE_UNSPECIFIED
```
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt` line 114 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/852#-NOVqkUi2LpUwEHWQTvb:-NOVqkUi2LpUwEHWQTvc:b5z1f8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5cddec8f74715db33c2081e5bb2bb1eab7c48006/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt#L114)):*
> ```Kotlin
> 
>     assertThat(exception.status.code).isEqualTo(Status.Code.NOT_FOUND)
>     assertThat(exception).hasMessageThat().contains("EventGroup not found")
> ```

nit: can just check that it contains "EventGroup" since the code is already NOT_FOUND

Basically everything we verify in this test constrains implementations, but we don't want them free to use different messages. We just expect that the message should mention "EventGroup" as a way to distinguish from other possible things that could not be found.



_Code quote:_
```Kotlin
EventGroup not found
```
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt` line 234 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/852#-NOVrNleA0rJn1gxhpbb:-NOVrNleA0rJn1gxhpbc:b-74j8zh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5cddec8f74715db33c2081e5bb2bb1eab7c48006/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt#L234)):*
> ```Kotlin
>         EventGroup.CREATE_TIME_FIELD_NUMBER,
>         EventGroup.UPDATE_TIME_FIELD_NUMBER,
>         EventGroup.STATE_FIELD_NUMBER
> ```

Just change the state in the expected message.

We only use `ignoringFields` for the fields that cannot be compared to a static value
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt` line 940 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/852#-NOVsj-HBcdrFcNyoXU_:-NOVsj-HBcdrFcNyoXUa:bjsqx5v) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5cddec8f74715db33c2081e5bb2bb1eab7c48006/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt#L940)):*
> ```Kotlin
> 
>   @Test
>   fun `getEventGroup succeeds for deleted eventGroup when is_deleted is true`() = runBlocking {
> ```

nit: consistent casing. The EventGroup message/resource type is always `EventGroup`.



_Suggestion:_
```Kotlin
EventGroup
```
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt` line 1035 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/852#-NOVs0RB7fnTkT2otabI:-NOVs0RB7fnTkT2otabJ:b-vs9qtm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5cddec8f74715db33c2081e5bb2bb1eab7c48006/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt#L1035)):*
> ```Kotlin
> 
>     assertThat(eventGroups).hasSize(2)
>     assertThat(eventGroups).contains(deletedEventGroup1)
> ```

Use Truth's support for collections. `containsExactly` will verify that it contains the exact elements in any order, unless you additionally specify `inOrder`



_Suggestion:_
```Kotlin
    assertThat(eventGroups).containsExactly(deletedEventGroup1, deletedEventGroup2)
```
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt` line 1040 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/852#-NOVssJX3m0tyRIvbGKR:-NOVssJX3m0tyRIvbGKS:b-7vlndr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5cddec8f74715db33c2081e5bb2bb1eab7c48006/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt#L1040)):*
> ```Kotlin
> 
>   @Test
>   fun `getEventGroup fails for deleted eventGroup when show_deleted is False`() = runBlocking {
> ```

nit: consistent casing



_Suggestion:_
```Kotlin
false
```


<!-- Sent from Reviewable.io -->

2023-02-23 02:50 UTC, jcorilla reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/852)* status: 7 of 14 files reviewed, 6 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

___
*[`build/repositories.bzl` line 41 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/852#-NOVlvAL7e0DpDsHZbCt:-NOvTAy94u0RsUrYMGdR:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5cddec8f74715db33c2081e5bb2bb1eab7c48006/build/repositories.bzl#L41)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Use our documented [TODO format](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/docs/code-style.md#todos)
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamEventGroups.kt` line 62 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/852#-NOVn4gV2fIrWvI7tX-H:-NOvUCKZ4UppEvZOxMPF:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5cddec8f74715db33c2081e5bb2bb1eab7c48006/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamEventGroups.kt#L62)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

You can use other types directly with Kotlin string templates. `toString()` will be called for you if needed.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/DeleteEventGroup.kt` line 35 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/852#-NOVneXD2hNDEvptqnU5:-NOv__IxChn45rLdIopI:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5cddec8f74715db33c2081e5bb2bb1eab7c48006/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/DeleteEventGroup.kt#L35)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This `@throws` doesn't belong here, since the constructor doesn't throw this exception. This is why we have a comment indicating what it throws on `execute`.

Instead group this with the comment above comment to document *which* subclasses get thrown. See `CreateRecurringExchange` as an example.

Unfortunately, it looks like a number of our SpannerWriter implementations do this incorrectly.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt` line 522 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/852#-NOVqBg874B8kNWX6iBx:-NOvfyyD2jkl1ewfXXnc:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5cddec8f74715db33c2081e5bb2bb1eab7c48006/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt#L522)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

UNRECOGNIZED is an error
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt` line 234 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/852#-NOVrNleA0rJn1gxhpbb:-NOw11553cgA0PQl4HP0:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5cddec8f74715db33c2081e5bb2bb1eab7c48006/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt#L234)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Just change the state in the expected message.

We only use `ignoringFields` for the fields that cannot be compared to a static value
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt` line 1035 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/852#-NOVs0RB7fnTkT2otabI:-NOvy4YQAwuAr-icz45d:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5cddec8f74715db33c2081e5bb2bb1eab7c48006/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/EventGroupsServiceTest.kt#L1035)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Use Truth's support for collections. `containsExactly` will verify that it contains the exact elements in any order, unless you additionally specify `inOrder`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-02-23 17:41 UTC, SanjayVas approved these changes
> Reviewed 7 of 7 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/852)* status: all files reviewed, 1 unresolved discussion (waiting on @jcorilla)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamEventGroups.kt` line 62 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/852#-NOVn4gV2fIrWvI7tX-H:-NOzLdw155fv3zhafQRo:b-elxrxo) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5cddec8f74715db33c2081e5bb2bb1eab7c48006/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamEventGroups.kt#L62)):*
<details><summary><i>Previously, jcorilla wrote…</i></summary><blockquote>

Done.
</blockquote></details>

`DELETED_VALUE` is the underlying integer. What you want is `DELETED`, which is the enum value.


<!-- Sent from Reviewable.io -->

2023-02-23 23:35 UTC, jcorilla reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/852)* status: 12 of 14 files reviewed, 1 unresolved discussion (waiting on @Marco-Premier and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamEventGroups.kt` line 62 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/852#-NOVn4gV2fIrWvI7tX-H:-NOzciFX4ifdngLP55tg:b-v86h52) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5cddec8f74715db33c2081e5bb2bb1eab7c48006/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamEventGroups.kt#L62)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

`DELETED_VALUE` is the underlying integer. What you want is `DELETED`, which is the enum value.
</blockquote></details>

Adding binding per offline conversation and using DELETED.numberAsLong, over DELETED_VALUE.toLong()


<!-- Sent from Reviewable.io -->

2023-02-24 00:55 UTC, SanjayVas requested changes
> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/852)* status: all files reviewed, 1 unresolved discussion (waiting on @jcorilla and @Marco-Premier)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamEventGroups.kt` line 64 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/852#-NP-uaf59i5RtDfZ9t71:-NP-uaf59i5RtDfZ9t72:undefined) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b8ffd6c87df5b4d21f92bb66033c1af2843adb7c/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamEventGroups.kt#L64)):*
> ```Kotlin
>     if (!filter.showDeleted) {
>       conjuncts.add("State != @$DELETED_STATE")
>       bind(DELETED_STATE).to(EventGroup.State.DELETED.numberAsLong)
> ```





_Suggestion:_
```Kotlin
bind(DELETED_STATE).toProtoEnum(EventGroup.State.DELETED)
```


<!-- Sent from Reviewable.io -->

2023-02-24 01:38 UTC, jcorilla reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/852)* status: 13 of 14 files reviewed, 1 unresolved discussion (waiting on @Marco-Premier and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamEventGroups.kt` line 64 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/852#-NP-uaf59i5RtDfZ9t71:-NP03dIH6XpL9-5M6XV5:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b8ffd6c87df5b4d21f92bb66033c1af2843adb7c/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/queries/StreamEventGroups.kt#L64)):*
> ```Kotlin
>     if (!filter.showDeleted) {
>       conjuncts.add("State != @$DELETED_STATE")
>       bind(DELETED_STATE).to(EventGroup.State.DELETED.numberAsLong)
> ```

Done.


<!-- Sent from Reviewable.io -->

2023-02-24 09:35 UTC, Marco-Premier reviewed
> Reviewed 4 of 13 files at r1, 2 of 8 files at r2, 1 of 1 files at r6, 5 of 7 files at r7, 1 of 2 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/852)* status: all files reviewed, 3 unresolved discussions (waiting on @jcorilla and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/DeleteEventGroup.kt` line 52 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/852#-NP1jxUh7hiwgmxZ6em5:-NP1jxUh7hiwgmxZ6em6:bnvcv24) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b6994d6d3d390673e487e5e63d2e23a44b0736d0/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/DeleteEventGroup.kt#L52)):*
> ```Kotlin
>         )
>     if (internalEventGroupResult.eventGroup.state == EventGroup.State.DELETED) {
>       throw EventGroupNotFoundException(
> ```

Shouldn't this be ```EventGroupStateIllegalException```?



_Code quote:_
```Kotlin
throw EventGroupNotFoundException
```
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/UpdateEventGroup.kt` line 51 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/852#-NP1lDJh-aXe9C1kNUoI:-NP1lDJh-aXe9C1kNUoJ:b-6vumu5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b6994d6d3d390673e487e5e63d2e23a44b0736d0/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/UpdateEventGroup.kt#L51)):*
> ```Kotlin
>         )
>     if (internalEventGroupResult.eventGroup.state == EventGroup.State.DELETED) {
>       throw EventGroupNotFoundException(
> ```

Same as above comment



_Code quote:_
```Kotlin
throw EventGroupNotFoundException
```


<!-- Sent from Reviewable.io -->

2023-02-24 09:37 UTC, Marco-Premier approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/852)* status: all files reviewed, 3 unresolved discussions (waiting on @jcorilla and @SanjayVas)



<!-- Sent from Reviewable.io -->

2023-02-24 20:01 UTC, jcorilla reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/852)* status: 10 of 17 files reviewed, 2 unresolved discussions (waiting on @Marco-Premier, @SanjayVas, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/DeleteEventGroup.kt` line 52 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/852#-NP1jxUh7hiwgmxZ6em5:-NP4-2o172bP7CkW7744:b-e78vvo) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b6994d6d3d390673e487e5e63d2e23a44b0736d0/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/DeleteEventGroup.kt#L52)):*
<details><summary><i>Previously, Marco-Premier (marcopremier) wrote…</i></summary><blockquote>

Shouldn't this be ```EventGroupStateIllegalException```?
</blockquote></details>

I agree, adding new exception following the pattern for Measurements IllegalStateException


<!-- Sent from Reviewable.io -->

2023-02-24 20:16 UTC, SanjayVas reviewed
> Reviewed 1 of 1 files at r9, 5 of 7 files at r10, 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/852)* status: 16 of 17 files reviewed, 1 unresolved discussion (waiting on @jcorilla, @Marco-Premier, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/DeleteEventGroup.kt` line 52 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/852#-NP1jxUh7hiwgmxZ6em5:-NP428p_2gkJGBvtIHXn:ba7w0kq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b6994d6d3d390673e487e5e63d2e23a44b0736d0/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/DeleteEventGroup.kt#L52)):*
<details><summary><i>Previously, jcorilla wrote…</i></summary><blockquote>

I agree, adding new exception following the pattern for Measurements IllegalStateException
</blockquote></details>

Note that in the public API, I believe this should result in a `NOT_FOUND` error. See https://google.aip.dev/164#errors


<!-- Sent from Reviewable.io -->

2023-02-24 21:23 UTC, jcorilla reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/852)* status: 14 of 17 files reviewed, 1 unresolved discussion (waiting on @Marco-Premier, @SanjayVas, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/DeleteEventGroup.kt` line 52 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/852#-NP1jxUh7hiwgmxZ6em5:-NP4Igjg5GhMGpTpKv8j:bmuhdpp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b6994d6d3d390673e487e5e63d2e23a44b0736d0/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/DeleteEventGroup.kt#L52)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Note that in the public API, I believe this should result in a `NOT_FOUND` error. See https://google.aip.dev/164#errors
</blockquote></details>

Switching status code to NOT_FOUND


<!-- Sent from Reviewable.io -->

2023-02-24 23:51 UTC, SanjayVas requested changes
> Reviewed 1 of 7 files at r10, 2 of 2 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/852)* status: all files reviewed, 3 unresolved discussions (waiting on @jcorilla, @Marco-Premier, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerEventGroupsService.kt` line 108 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/852#-NP4mtdl60pKTlqGHzZY:-NP4mtdl60pKTlqGHzZZ:b-qbed1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6c08140cc6b6893d0218327e8a749aa715c43852/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerEventGroupsService.kt#L108)):*
Apparently my previous reading of the AIP was incorrect and `Get` shouldn't actually have a `show_deleted` field[^1]:

> `Get` (AIP-131) requests for soft-deleted resources **should** return the resource (rather than a `NOT_FOUND` error).

Drop the field from the Get request.

[^1]: https://google.aip.dev/164#list-and-get



_Code quote:_
```Kotlin
    if (eventGroup.state == EventGroup.State.DELETED && !request.showDeleted) {
      failGrpc(Status.NOT_FOUND) { "EventGroup not found" }
    }
```
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerEventGroupsService.kt` line 109 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/852#-NP4pJPa3k-Zh3I3xuBw:-NP4pJPa3k-Zh3I3xuBx:bzgkuzj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6c08140cc6b6893d0218327e8a749aa715c43852/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerEventGroupsService.kt#L109)):*
> ```Kotlin
>         ?: failGrpc(Status.NOT_FOUND) { "EventGroup not found" }
>     if (eventGroup.state == EventGroup.State.DELETED && !request.showDeleted) {
>       failGrpc(Status.NOT_FOUND) { "EventGroup not found" }
> ```

nit: Give a clearer message in this case so we can spot it in logs



_Suggestion:_
```Kotlin
"EventGroup state is DELETED"
```
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerEventGroupsService.kt` line 129 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/852#-NP4lssF606wcChvHgmO:-NP4lssF606wcChvHgmP:b-qlb2qo) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6c08140cc6b6893d0218327e8a749aa715c43852/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerEventGroupsService.kt#L129)):*
> ```Kotlin
>       e.throwStatusRuntimeException(Status.NOT_FOUND) { "EventGroup not found." }
>     } catch (e: EventGroupStateIllegalException) {
>       e.throwStatusRuntimeException(Status.NOT_FOUND) { "EventGroup state illegal." }
> ```

You technically don't know if this should be NOT_FOUND in the public API unless you know that the state is DELETED. It's true that DELETED is the only state where this error is thrown, but that's an implementation detail of DeleteEventGroup and not something we can assume here.

Also note that my statements only apply to the public API. The internal API status need not match the public API status (though it tends to be easier if it does). I recommend explicitly checking the state is DELETED here so you can return NOT_FOUND, mentioning in the message that the EventGroup has been deleted.

The other option would be returning FAILED_PRECONDITION here and checking the error details in the public API to figure out that it was caused by it being deleted. Of course to be consistent, you'd then need to do the same thing for `Get`.


<!-- Sent from Reviewable.io -->

2023-02-27 22:03 UTC, jcorilla reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/852)* status: all files reviewed, 2 unresolved discussions (waiting on @Marco-Premier, @SanjayVas, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerEventGroupsService.kt` line 108 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/852#-NP4mtdl60pKTlqGHzZY:-NPJr3_J8XVhkFO8wDv2:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6c08140cc6b6893d0218327e8a749aa715c43852/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerEventGroupsService.kt#L108)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Apparently my previous reading of the AIP was incorrect and `Get` shouldn't actually have a `show_deleted` field[^1]:

> `Get` (AIP-131) requests for soft-deleted resources **should** return the resource (rather than a `NOT_FOUND` error).

Drop the field from the Get request.

[^1]: https://google.aip.dev/164#list-and-get
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerEventGroupsService.kt` line 129 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/852#-NP4lssF606wcChvHgmO:-NPJr7SN7T5UMUrB0NF4:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/6c08140cc6b6893d0218327e8a749aa715c43852/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerEventGroupsService.kt#L129)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

You technically don't know if this should be NOT_FOUND in the public API unless you know that the state is DELETED. It's true that DELETED is the only state where this error is thrown, but that's an implementation detail of DeleteEventGroup and not something we can assume here.

Also note that my statements only apply to the public API. The internal API status need not match the public API status (though it tends to be easier if it does). I recommend explicitly checking the state is DELETED here so you can return NOT_FOUND, mentioning in the message that the EventGroup has been deleted.

The other option would be returning FAILED_PRECONDITION here and checking the error details in the public API to figure out that it was caused by it being deleted. Of course to be consistent, you'd then need to do the same thing for `Get`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-02-27 23:57 UTC, SanjayVas approved these changes
> Reviewed 4 of 4 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/852)* status: all files reviewed, 1 unresolved discussion (waiting on @jcorilla, @Marco-Premier, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerEventGroupsService.kt` line 92 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/852#-NPKI-sDBPioKtwOPXts:-NPKI-sDBPioKtwOPXtt:b69q4s9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f7176470254327fa72900307302301b9671551ad/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerEventGroupsService.kt#L92)):*
> ```Kotlin
>       e.throwStatusRuntimeException(Status.NOT_FOUND) { "EventGroup not found." }
>     } catch (e: EventGroupStateIllegalException) {
>       when (e.state) {
> ```

nit: prefer exhaustive `when`s when using enum values.

An exhaustive `when` is one which covers all possible values without an `else` branch. Using them has the benefit that the compiler will raise an error if a new value is introduced which has no corresponding branch. This prevents new values from being unintentionally unhandled.


<!-- Sent from Reviewable.io -->

2023-03-01 17:31 UTC, jcorilla reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/852)* status: 15 of 18 files reviewed, 1 unresolved discussion (waiting on @Marco-Premier, @SanjayVas, and @tristanvuong2021)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/852#-NPTDNUA4Xx-jIkcMPkp:-NPTDNUA4Xx-jIkcMPkq:bt5dpnb) (no related file):*
@tristanvuong2021 @Marco-Premier Would you giving the pr another look after the addition of EventGroupStateIllegalException? Thank you

___


<!-- Sent from Reviewable.io -->

2023-03-03 17:49 UTC, Marco-Premier approved these changes
> Reviewed 4 of 7 files at r10, 1 of 1 files at r11, 3 of 4 files at r13, 3 of 3 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/852)* status: all files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)



<!-- Sent from Reviewable.io -->

2023-03-03 19:51 UTC, tristanvuong2021 approved these changes
> Reviewed 2 of 7 files at r7, 1 of 1 files at r9, 4 of 7 files at r10, 1 of 1 files at r11, 3 of 4 files at r13, 3 of 3 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/852)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)



<!-- Sent from Reviewable.io -->

2023-03-03 21:34 UTC, jcorilla reviewed
> Reviewed 3 of 13 files at r1, 1 of 8 files at r2, 2 of 7 files at r7, 1 of 1 files at r9, 4 of 7 files at r10, 1 of 1 files at r11, 2 of 4 files at r13, 2 of 3 files at r14, 2 of 2 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/852)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jcorilla)



<!-- Sent from Reviewable.io -->

2023-03-03 21:35 UTC, merged