Update DB schema / add logic for reading-writing duchy-include-list /…
world-federation-of-advertisers/cross-media-measurement pull request #856
Opened 2023-02-13 16:51 UTC by Marco-Premier

[TA567](https://rally1.rallydev.com/#/604612930531d/iterationstatus?detail=%2Ftask%2F685508089433)

Scope of this PR:

- update DB in order to include (1:many) duchy include list
- update CreateResource picocli command to create a data provider
- update spanners readers / writers for data provider resource

2023-02-13 16:51 UTC, SanjayVas commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/856)
<!-- Reviewable:end -->

2023-02-13 17:44 UTC, stevenwarejones requested changes
> Reviewed 14 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/856)* status: all files reviewed, 3 unresolved discussions (waiting on @Marco-Premier and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerDataProvidersService.kt` line 41 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/856#-NOAqWVf6BPvv81Fzw8J:-NOAqWVf6BPvv81Fzw8K:b-7agtxq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/edd625b331d9dd81952750bc6e5ab57c19a90916/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/SpannerDataProvidersService.kt#L41)):*
> ```Kotlin
>       "Details field of DataProvider is missing fields."
>     }
>     grpcRequire(request.externalDuchyIdCount > 0) { "ExternalDuchyId list is empty" }
> ```

we don't need this requirement. the list can be empty and then no rows inserted into the table
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/DataProviderReader.kt` line 89 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/856#-NOArKi_3IV2rcmHqzFi:-NOArKi_3IV2rcmHqzFj:b-m9awe3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/edd625b331d9dd81952750bc6e5ab57c19a90916/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/DataProviderReader.kt#L89)):*
> ```Kotlin
>   private fun buildExternalDuchyIdList(struct: Struct): MutableList<Long> {
>     val duchiesExternalIdList = mutableListOf<Long>()
>     for (duchyIncludeListValue in struct.getStructList("DataProviderDuchyIncludeList")) {
> ```

```
return struct.getStructList("DataProviderDuchyIncludeList").map{ 
   it..getLong("ExternalDuchyId")
}
```

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateDataProvider.kt` line 24 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/856#-NOAs3qd3Zm_m4GcGN0V:-NOAs3qd3Zm_m4GcGN0W:b-lp4qu0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/edd625b331d9dd81952750bc6e5ab57c19a90916/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateDataProvider.kt#L24)):*
> ```Kotlin
> import org.wfanet.measurement.internal.kingdom.copy
> 
> class CreateDataProvider(private val dataProvider: DataProvider) :
> ```

is there a separate write for editing a data provider?


<!-- Sent from Reviewable.io -->

2023-02-14 00:12 UTC, SanjayVas requested changes
> Reviewed 5 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/856)* status: all files reviewed, 6 unresolved discussions (waiting on @Marco-Premier and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateDataProvider.kt` line 24 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/856#-NOAs3qd3Zm_m4GcGN0V:-NOCF2Eq4psnZamX-ju9:b-yv8mgm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/edd625b331d9dd81952750bc6e5ab57c19a90916/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateDataProvider.kt#L24)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

is there a separate write for editing a data provider?
</blockquote></details>

There's currently no Update method for DataProviders in the public API. Probably something that needs to be added so EDPs can update their lists of required Duchies.
___
*[`src/main/proto/wfa/measurement/internal/kingdom/data_provider.proto` line 43 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/856#-NOCDu3C1zolYkDWb9dD:-NOCDu3DB_oupNiS4zMJ:b-7rvtve) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/edd625b331d9dd81952750bc6e5ab57c19a90916/src/main/proto/wfa/measurement/internal/kingdom/data_provider.proto#L43)):*
> ```protobuf
> 
>   // The list of duchies that must be included in all computations involving the DataProvider
>   repeated int64 external_duchy_id = 4;
> ```

 Maybe name this `required_external_duchy_ids`? I assume we'd call the public API field something like `required_duchies` so the purpose is clear.

Regardless, the names of repeated fields should be plural.



_Code quote:_
```protobuf
external_duchy_id
```
___
*[`src/main/resources/kingdom/spanner/create-duchy-include-list-schema.sql` line 18 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/856#-NOCED089f1cj42OQVFr:-NOCED089f1cj42OQVFs:be5gby5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/edd625b331d9dd81952750bc6e5ab57c19a90916/src/main/resources/kingdom/spanner/create-duchy-include-list-schema.sql#L18)):*
> ```TSQL
> 
> -- changeset marcopremier:6 dbms:cloudspanner
> CREATE TABLE DataProviderDuchyIncludeList (
> ```

Maybe `DataProviderRequiredDuchies`? Table names should be plural.

Also in general not a fan of "include list":
1. It's not a list, it's a set (i.e. order doesn't matter and there are expected to be no duplicates)
2. It's not just what to include, but what is required (**must** be included)



_Code quote:_
```TSQL
DataProviderDuchyIncludeList
```
___
*[`src/main/resources/kingdom/spanner/create-duchy-include-list-schema.sql` line 20 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/856#-NOCEVZnAtOf6YIc8NqU:-NOCEVZnAtOf6YIc8NqV:b-xstt2f) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/edd625b331d9dd81952750bc6e5ab57c19a90916/src/main/resources/kingdom/spanner/create-duchy-include-list-schema.sql#L20)):*
> ```TSQL
> CREATE TABLE DataProviderDuchyIncludeList (
>     DataProviderId INT64 NOT NULL,
>     -- Duchy external id that must be included in every computation that involves this DP id.
> ```

All references should use internal IDs. We can join with the corresponding table (or in the case of Duchy IDs, use the config) for external ID lookups.



_Code quote:_
```TSQL
    -- Duchy external id that must be included in every computation that involves this DP id.
    ExternalDuchyId INT64 NOT NULL,
```


<!-- Sent from Reviewable.io -->

2023-02-14 22:23 UTC, stevenwarejones requested changes
> Reviewed 21 of 21 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/856)* status: all files reviewed, 5 unresolved discussions (waiting on @Marco-Premier and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/DataProviderReader.kt` line 92 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/856#-NOGzfBq2N4Dpr40tGrb:-NOGzfBq2N4Dpr40tGrc:b-3f301l) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/69606747d7d9bcaebe08723936c36fb0cc519b65/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/DataProviderReader.kt#L92)):*
> ```Kotlin
>       .getStructList("DataProviderRequiredDuchies")
>       .map {
>         checkNotNull(DuchyIds.getExternalId(it.getLong("DuchyId"))) {
> ```

I don't think you want to throw an error, right? you should filter out null 
```
.filterNotNull
```

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateDataProvider.kt` line 24 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/856#-NOAs3qd3Zm_m4GcGN0V:-NOGzvJS2sOcDQY_r-Wa:b-2p61jw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/edd625b331d9dd81952750bc6e5ab57c19a90916/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateDataProvider.kt#L24)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

There's currently no Update method for DataProviders in the public API. Probably something that needs to be added so EDPs can update their lists of required Duchies.
</blockquote></details>

can you add a TODO for that @Marco-Premier ?


<!-- Sent from Reviewable.io -->

2023-02-15 00:10 UTC, SanjayVas requested changes
> Reviewed 1 of 14 files at r1, 21 of 21 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/856)* status: all files reviewed, 17 unresolved discussions (waiting on @Marco-Premier and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/DataProviderReader.kt` line 88 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/856#-NOHDcna3B9j04S9vV9w:-NOHDcna3B9j04S9vV9x:undefined) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/69606747d7d9bcaebe08723936c36fb0cc519b65/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/DataProviderReader.kt#L88)):*
> ```Kotlin
>       .build()
> 
>   private fun buildExternalDuchyIdList(struct: Struct): Iterable<String?> {
> ```





_Suggestion:_
```Kotlin
String
```
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/DataProviderReader.kt` line 88 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/856#-NOHDjM92nQgKKoMDb6y:-NOHDjM92nQgKKoMDb6z:b-qoqyyk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/69606747d7d9bcaebe08723936c36fb0cc519b65/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/DataProviderReader.kt#L88)):*
> ```Kotlin
>       .build()
> 
>   private fun buildExternalDuchyIdList(struct: Struct): Iterable<String?> {
> ```

nit: You have method called buildXXXList which returns an `Iterable` not a `List`



_Code quote:_
```Kotlin
List
```
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/DataProviderReader.kt` line 92 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/856#-NOGzfBq2N4Dpr40tGrb:-NOHBd7uAqCoxW1JK3bq:b-9ka7ve) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/69606747d7d9bcaebe08723936c36fb0cc519b65/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/DataProviderReader.kt#L92)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

I don't think you want to throw an error, right? you should filter out null 
```
.filterNotNull
```

</blockquote></details>

Throwing an error seems correct. We shouldn't just silently drop entries that have an invalid ID. If we get a `null` from the lookup, it means something is wrong as an invariant was violated. From the design doc/discussion, Duchies shouldn't get deleted but may be marked inactive.

If we did want to support hard deletion of Duchies we would want to have cascading deletion behavior. Since Duchies is a config file rather than a real table, this behavior would have to be implemented manually.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/DataProviderReader.kt` line 96 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/856#-NOHDNlSATDbEe4H5q5S:-NOHDNlSATDbEe4H5q5T:b-cxvdng) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/69606747d7d9bcaebe08723936c36fb0cc519b65/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/DataProviderReader.kt#L96)):*
> ```Kotlin
>         }
>       }
>       .asIterable()
> ```

I believe `map` returns a `List` in this case, which already implements `Iterable`.



_Code quote:_
```Kotlin
      .asIterable()
```
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateDataProvider.kt` line 45 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/856#-NOHG-QUDj3Oc-siToCh:-NOHG-QVDP9rkmBHBh4B:b-gkutlf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/69606747d7d9bcaebe08723936c36fb0cc519b65/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateDataProvider.kt#L45)):*
> ```Kotlin
>     }
> 
>     // This takes O(n*m) where n is the list of duchies and m the list of required ones. Expected
> ```

This comment doesn't belong here as it is referring to an implementation detail of `DuchyIds.getInternalId`.

(`DuchyIds.getInternalId` also shouldn't have the note about being implemented as a linear scan in its public documentation, or should at least make it clear that it is not part of the contract and may change in the future.)



_Code quote:_
```Kotlin
    // This takes O(n*m) where n is the list of duchies and m the list of required ones. Expected
    // number of duchies should quite small (~5) and the required <= 2
```
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt` line 152 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/856#-NOH5udVEEOnmVLqdLGC:-NOH5udVEEOnmVLqdLGD:b45h) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/69606747d7d9bcaebe08723936c36fb0cc519b65/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt#L152)):*
> ```Kotlin
>     required = false,
>   )
>   private lateinit var requiredDuchies: Array<String>
> ```





_Suggestion:_
```Kotlin
List
```
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt` line 164 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/856#-NOH5hmY5-S80pxPzI-W:-NOH5hmZ5n-_mZmbRw50:undefined) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/69606747d7d9bcaebe08723936c36fb0cc519b65/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt#L164)):*
> ```Kotlin
>         }
> 
>       for (duchyExternalId in requiredDuchies) {
> ```





_Suggestion:_
```Kotlin
      requiredExternalDuchyIds += requiredDuchies
```
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ComputationParticipantsServiceTest.kt` line 64 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/856#-NOHHwE60zpVUbacqtUG:-NOH6IJ35651gfFJYMDY:b-ho2fwi) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/69606747d7d9bcaebe08723936c36fb0cc519b65/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ComputationParticipantsServiceTest.kt#L64)):*
> ```Kotlin
> private const val RANDOM_SEED = 1
> private const val PROVIDED_MEASUREMENT_ID = "measurement"
> private val EXTERNAL_DUCHY_IDS = listOf("worker1", "worker2")
> ```

Why change this? This file appears to be otherwise untouched by this PR.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/DataProvidersServiceTest.kt` line 123 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/856#-NOH6Q6Y80e1VSl4hZ88:-NOH6Q6Y80e1VSl4hZ89:undefined) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/69606747d7d9bcaebe08723936c36fb0cc519b65/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/DataProvidersServiceTest.kt#L123)):*
> ```Kotlin
>             publicKeySignature = PUBLIC_KEY_SIGNATURE
>           }
>           addAllRequiredExternalDuchyIds(mutableListOf("worker1", "worker2"))
> ```





_Suggestion:_
```Kotlin
listOf
```
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/DataProvidersServiceTest.kt` line 192 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/856#-NOHAXnQCkGcuPju1kQo:-NOHAXnQCkGcuPju1kQp:undefined) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/69606747d7d9bcaebe08723936c36fb0cc519b65/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/DataProviders [...]

2023-02-15 15:38 UTC, Marco-Premier reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/856)* status: all files reviewed, 16 unresolved discussions (waiting on @SanjayVas and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/DataProviderReader.kt` line 88 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/856#-NOHDcna3B9j04S9vV9w:-NOKPoAg51cMGrsDd6MG:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/69606747d7d9bcaebe08723936c36fb0cc519b65/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/DataProviderReader.kt#L88)):*
> ```Kotlin
>       .build()
> 
>   private fun buildExternalDuchyIdList(struct: Struct): Iterable<String?> {
> ```

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/DataProviderReader.kt` line 92 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/856#-NOGzfBq2N4Dpr40tGrb:-NOKQFU1E3cfpzvzN279:bo96yka) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/69606747d7d9bcaebe08723936c36fb0cc519b65/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/DataProviderReader.kt#L92)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Throwing an error seems correct. We shouldn't just silently drop entries that have an invalid ID. If we get a `null` from the lookup, it means something is wrong as an invariant was violated. From the design doc/discussion, Duchies shouldn't get deleted but may be marked inactive.

If we did want to support hard deletion of Duchies we would want to have cascading deletion behavior. Since Duchies is a config file rather than a real table, this behavior would have to be implemented manually.
</blockquote></details>

I thought that if for some reason the lookup fails it would be better to throw an exception since the DP has an invalid "required" duchy. Furthermore I think that the exception would make eventual debugging easier
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/DataProviderReader.kt` line 96 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/856#-NOHDNlSATDbEe4H5q5S:-NOKQ7AhAK1LTj_NxW12:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/69606747d7d9bcaebe08723936c36fb0cc519b65/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/readers/DataProviderReader.kt#L96)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I believe `map` returns a `List` in this case, which already implements `Iterable`.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateDataProvider.kt` line 24 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/856#-NOAs3qd3Zm_m4GcGN0V:-NOKS6Qu7ewd6l7guGI5:b-n62xyi) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/edd625b331d9dd81952750bc6e5ab57c19a90916/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateDataProvider.kt#L24)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

can you add a TODO for that @Marco-Premier ?
</blockquote></details>

sure, added it to the SpannerDataProviderService
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateDataProvider.kt` line 45 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/856#-NOHG-QUDj3Oc-siToCh:-NOK5fBn2qnhnTuYEuJe:b-mnt1pt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/69606747d7d9bcaebe08723936c36fb0cc519b65/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/gcloud/spanner/writers/CreateDataProvider.kt#L45)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This comment doesn't belong here as it is referring to an implementation detail of `DuchyIds.getInternalId`.

(`DuchyIds.getInternalId` also shouldn't have the note about being implemented as a linear scan in its public documentation, or should at least make it clear that it is not part of the contract and may change in the future.)
</blockquote></details>

I see. So no this kind of mentions. I'm going to remove it
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt` line 152 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/856#-NOH5udVEEOnmVLqdLGC:-NOKSRro0OWz4HtcwtsS:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/69606747d7d9bcaebe08723936c36fb0cc519b65/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt#L152)):*
> ```Kotlin
>     required = false,
>   )
>   private lateinit var requiredDuchies: Array<String>
> ```

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt` line 164 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/856#-NOH5hmY5-S80pxPzI-W:-NOKS_Ld5sFsO-f7UMmQ:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/69606747d7d9bcaebe08723936c36fb0cc519b65/src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt#L164)):*
> ```Kotlin
>         }
> 
>       for (duchyExternalId in requiredDuchies) {
> ```

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ComputationParticipantsServiceTest.kt` line 64 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/856#-NOHHwE60zpVUbacqtUG:-NOKSp0H2xGUwbSkPu3Q:b-d4zhr1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/69606747d7d9bcaebe08723936c36fb0cc519b65/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ComputationParticipantsServiceTest.kt#L64)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Why change this? This file appears to be otherwise untouched by this PR.
</blockquote></details>

please see comment below on refactor using shared variables
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/DataProvidersServiceTest.kt` line 123 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/856#-NOH6Q6Y80e1VSl4hZ88:-NOKTx7e0ZdxhH4lfb_r:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/69606747d7d9bcaebe08723936c36fb0cc519b65/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/DataProvidersServiceTest.kt#L123)):*
> ```Kotlin
>             publicKeySignature = PUBLIC_KEY_SIGNATURE
>           }
>           addAllRequiredExternalDuchyIds(mutableListOf("worker1", "worker2"))
> ```

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/DataProvidersServiceTest.kt` line 192 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/856#-NOHAXnQCkGcuPju1kQo:-NOKU1G_60wWZwCCM6yU:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/69606747d7d9bcaebe08723936c36fb0cc519b65/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/DataProvidersServiceTest.kt#L192)):*
> ```Kotlin
>             publicKeySignature = PUBLIC_KEY_SIGNATURE
>           }
>           addAllRequiredExternalDuchyIds(mutableListOf("worker1", "worker2"))
> ```

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/MeasurementLogEnt [...]

2023-02-15 17:06 UTC, stevenwarejones approved these changes
> Reviewed 25 of 25 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/856)* status: all files reviewed, 15 unresolved discussions (waiting on @SanjayVas)



<!-- Sent from Reviewable.io -->

2023-02-15 19:58 UTC, SanjayVas requested changes
> Reviewed 25 of 25 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/856)* status: all files reviewed, 4 unresolved discussions (waiting on @Marco-Premier)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ComputationParticipantsServiceTest.kt` line 64 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/856#-NOHHwE60zpVUbacqtUG:-NOLaM_Z-ykJgucxDYkw:bg002ha) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/69606747d7d9bcaebe08723936c36fb0cc519b65/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/ComputationParticipantsServiceTest.kt#L64)):*
<details><summary><i>Previously, Marco-Premier (marcopremier) wrote…</i></summary><blockquote>

please see comment below on refactor using shared variables
</blockquote></details>

Sorry, meant to drop this comment when I realized the change to Population.
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/Population.kt` line 74 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/856#-NOLa2yNExX9syxUioZX:-NOLa2yNExX9syxUioZY:bouqbrl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4ff5d3df04a33d80984b9d34f37f5b741ce85c08/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/Population.kt#L74)):*
> ```Kotlin
>     const val WORKER2_DUCHY_EXTERNAL_ID = "worker2"
>     const val AGGREGATOR_DUCHY_EXTERNAL_ID = "aggregator"
>     val EXTERNAL_DUCHY_IDS: List<String> by lazy {
> ```

nit: can just make this a list. This is only for testing and the memory overhead of always having this is low. We may not even actually be saving anything by doing this as lazy initialization has some of its own overhead.



_Code quote:_
```Kotlin
by lazy
```
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/RequisitionsServiceTest.kt` line 68 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/856#-NOHL6xv20eCyVv7TuMZ:-NOLalQE1SSCNfruonzG:bj4rc0k) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/69606747d7d9bcaebe08723936c36fb0cc519b65/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/RequisitionsServiceTest.kt#L68)):*
> I replaced Buck / Rippon / Shoaks with shared constants too

I figured that might end up happening. RIP my easter egg reference to [The Six Duchies](https://robinhobbelderlings.fandom.com/wiki/The_Six_Duchies) (I was reading this book series when I wrote the tests :P )
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/RequisitionsServiceTest.kt` line 703 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/856#-NOLbVDRDQKNvmubfJxD:-NOLbVDRDQKNvmubfJxE:blezd23) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4ff5d3df04a33d80984b9d34f37f5b741ce85c08/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/RequisitionsServiceTest.kt#L703)):*
> ```Kotlin
>           computedParams = computedRequisitionParams {
>             externalComputationId = measurement.externalComputationId
>             externalFulfillingDuchyId = Population.AGGREGATOR_DUCHY_EXTERNAL_ID
> ```

nit: requisitions would never be fulfilled at the aggregator Duchy, so this might be misleading to someone trying to understand the system via tests. Use one of the workers for `externalFulfillingDuchyId` instead.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetupFlags.kt` line 127 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/856#-NOLcuGbC_7cz9jA6Vg9:-NOLcuGbC_7cz9jA6VgA:b-pbnijo) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4ff5d3df04a33d80984b9d34f37f5b741ce85c08/src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetupFlags.kt#L127)):*
> ```Kotlin
> 
>   @CommandLine.Option(
>     names = ["--required-duchies"],
> ```

We use repeated options when there multiple values, so it's clearer for the option name to be singular even though the resulting property is a collection and is therefore plural.



_Suggestion:_
```Kotlin
--required-duchy
```
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetupFlags.kt` line 130 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/856#-NOLcz-d62yUQJ4ZHoq_:-NOLcz-d62yUQJ4ZHoqa:bqkptqa) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4ff5d3df04a33d80984b9d34f37f5b741ce85c08/src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetupFlags.kt#L130)):*
> ```Kotlin
>     description =
>       [
>         "The set of duchies externals IDS that must be included in all computations involving this DataProvider."
> ```

nit: ResourceSetup creates 6 DataProviders, so the original comment is a bit inaccurate. Also, we only talk about internal vs. external IDs when referencing the internal API. "Computation" is the Duchy view of a Measurement, so we should reference "Measurement" here instead. Finally, we want to be clear that this is a repeated option.



_Suggestion:_
```Kotlin
      [
        "Duchy ID that must be included in all Measurements for the created DataProvider resources.",
        "This option may be specified multiple times."
      ],
```


<!-- Sent from Reviewable.io -->

2023-02-16 14:57 UTC, stevenwarejones approved these changes
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/856)* status: all files reviewed, 4 unresolved discussions (waiting on @Marco-Premier)



<!-- Sent from Reviewable.io -->

2023-02-17 08:16 UTC, Marco-Premier reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/856)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/RequisitionsServiceTest.kt` line 68 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/856#-NOHL6xv20eCyVv7TuMZ:-NOPOxA27LoWDs0_wlhx:bxp1zgn) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/69606747d7d9bcaebe08723936c36fb0cc519b65/src/main/kotlin/org/wfanet/measurement/kingdom/service/internal/testing/RequisitionsServiceTest.kt#L68)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> I replaced Buck / Rippon / Shoaks with shared constants too

I figured that might end up happening. RIP my easter egg reference to [The Six Duchies](https://robinhobbelderlings.fandom.com/wiki/The_Six_Duchies) (I was reading this book series when I wrote the tests :P )
</blockquote></details>

:) I might end up reading it too
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetupFlags.kt` line 127 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/856#-NOLcuGbC_7cz9jA6Vg9:-NOPQ8AH5LI0JuMq0cjC:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/4ff5d3df04a33d80984b9d34f37f5b741ce85c08/src/main/kotlin/org/wfanet/measurement/loadtest/resourcesetup/ResourceSetupFlags.kt#L127)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

We use repeated options when there multiple values, so it's clearer for the option name to be singular even though the resulting property is a collection and is therefore plural.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-02-17 19:44 UTC, SanjayVas approved these changes
> Reviewed 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/856)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Marco-Premier)



<!-- Sent from Reviewable.io -->

2023-02-21 20:07 UTC, SanjayVas approved these changes
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/856)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Marco-Premier)



<!-- Sent from Reviewable.io -->

2023-02-22 08:34 UTC, Marco-Premier reviewed
Git was unable to merge the branch as it became out dated. I've automatically merged main into this branch using git

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/856#-:-NOsFNokC1nYplasre7j:b-r7to1q)* status: 25 of 26 files reviewed, all discussions resolved (waiting on @SanjayVas and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2023-02-24 12:44 UTC, Marco-Premier reviewed
branch became outdated. I rebased it against main

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/856#-:-NP2S-6pEDa6dk3Emr47:b-ialxiq)* status: 25 of 26 files reviewed, all discussions resolved (waiting on @SanjayVas and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2023-02-25 00:10 UTC, SanjayVas approved these changes
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/856)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Marco-Premier)



<!-- Sent from Reviewable.io -->

2023-02-27 09:06 UTC, merged

2023-02-28 23:11 UTC, renjiezh commented on src/main/kotlin/org/wfanet/measurement/kingdom/deploy/tools/CreateResource.kt
> +  private lateinit var requiredDuchies: List<String>
This option was noted as optional, thus a default value is required. It raises runtime error "lateinit var not initialized". Could you please fix it? @Marco-Premier