Stop inserting ComputationParticipants rows for single-EDP R/F Measurements.
world-federation-of-advertisers/cross-media-measurement pull request #868
Opened 2023-02-24 20:45 UTC by SanjayVas

This also stops populating the liquid_legions_v2 field in Measurement.Details.protocol_config for these Measurements. As a result, the deprecated liquid_legions_v2 field in the ProtocolConfig message of the public API will no longer be populated.

This was missed in #861.

2023-02-24 20:45 UTC, wfa-reviewable commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/868)
<!-- Reviewable:end -->

2023-02-27 19:09 UTC, SanjayVas reviewed
I mean that it can no longer be populated for new single-EDP R/F measurements. Since it's a deprecated field that was intended to be removed, it's just never populated at all anymore. For multi-EDP R/F measurements, the LLv2 protocol config can be found in the `protocols` field.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/868#-:-NPJGDQf1tHHil3vvwB8:bjnk31k)* status: 1 of 5 files reviewed, all discussions resolved (waiting on @iverson52000)



<!-- Sent from Reviewable.io -->

2023-02-27 19:58 UTC, stevenwarejones requested changes
> Reviewed 2 of 2 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/868)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt` line 183 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/868#-NPJPo8QBwO20s1XB4xK:-NPJPo8QBwO20s1XB4xL:bg6rica) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/73231d3e77f5c9d15bd32065208858dbce40fe22/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt#L183)):*
> ```Kotlin
>           }
>         }
>         if (dataProviderCount == 1) {
> ```

i think the code reads slightly easier to move this up and make it an `if else`.
```
if (dataProviderCount == 1) {
   protocols += protocol { direct = direct {} }
} else {
    when (source.protocolCase) {     
       LIQUID_LEGIONS_V2 -> {
             ....
        } 
        else -> error("Invalid Protocol")
   }
}
```



<!-- Sent from Reviewable.io -->

2023-02-27 20:51 UTC, SanjayVas reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/868)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt` line 183 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/868#-NPJPo8QBwO20s1XB4xK:-NPJd8tI2oFvc9ZI3Zx0:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/73231d3e77f5c9d15bd32065208858dbce40fe22/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/ProtoConversions.kt#L183)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

i think the code reads slightly easier to move this up and make it an `if else`.
```
if (dataProviderCount == 1) {
   protocols += protocol { direct = direct {} }
} else {
    when (source.protocolCase) {     
       LIQUID_LEGIONS_V2 -> {
             ....
        } 
        else -> error("Invalid Protocol")
   }
}
```

</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-03-06 17:05 UTC, stevenwarejones approved these changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/868)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)



<!-- Sent from Reviewable.io -->

2023-03-06 18:07 UTC, SanjayVas reviewed
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/868)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)



<!-- Sent from Reviewable.io -->

2023-03-06 18:10 UTC, merged