Initial Kingdom code
world-federation-of-advertisers/cross-media-measurement pull request #877
Opened 2023-03-03 08:26 UTC by wfa-mdharmalingam

Hello All,

We have add the following

2023-03-03 08:26 UTC, wfa-reviewable commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/877)
<!-- Reviewable:end -->

2023-03-03 17:15 UTC, duliomatos1 requested changes
Thanks for breaking down into smaller PRs

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/877#-:-NPcTAg1CTzzqEVCpX76:b23vjm7)* status: 0 of 8 files reviewed, 4 unresolved discussions (waiting on @bdomen-ggl, @kungfucraig, @SanjayVas, @TNATALI, @wfa-mdharmalingam, and @wfa-siyengar)

___
*[`src/main/terraform/kingdom/gcloud/service-account.tf` line 19 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/877#-NPcSje-0NPMktIwCACT:-NPcSje-0NPMktIwCACU:b895x10) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/202926781a001e893688ac584f3ba5e2fb2d4709/src/main/terraform/kingdom/gcloud/service-account.tf#L19)):*
> ```HCL
> # Create service account for accessing Cloud Spanner
> resource "google_service_account" "spanner_service_account" {
> account_id   = "spanner-access-sa"
> ```

It seems this most of this file is missing indentation, at least when I check here in reviewable
___
*[`src/main/terraform/kingdom/gcloud/variables.tf` line 15 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/877#-NPcR3_wD6tjjpeX_kVW:-NPcR3_wD6tjjpeX_kVX:b-zemkg2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/202926781a001e893688ac584f3ba5e2fb2d4709/src/main/terraform/kingdom/gcloud/variables.tf#L15)):*
> ```HCL
> # limitations under the License.
> /*
> ```

  nit: this comment seems to be unused



_Code quote:_
```HCL
/*

*/
```
___
*[`src/main/terraform/kingdom/gcloud/variables.tf` line 34 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/877#-NPcSAkO-58WOmvASA_K:-NPcSAkO-58WOmvASA_L:bf9ewu5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/202926781a001e893688ac584f3ba5e2fb2d4709/src/main/terraform/kingdom/gcloud/variables.tf#L34)):*
`node_version` seems to be less than `min_master_version`, seems it should be the same or unset:
> The Kubernetes version on the nodes. Must either be unset or set to the same value as min_master_version on create.

https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster#node_version
___
*[`src/main/terraform/kingdom/gcloud/variables.tf` line 100 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/877#-NPcRJ2324gxguDqWaTK:-NPcRJ2324gxguDqWaTL:b-dbxc7j) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/202926781a001e893688ac584f3ba5e2fb2d4709/src/main/terraform/kingdom/gcloud/variables.tf#L100)):*
> ```HCL
>   description = "Key ring location "
> }
> ```

nit: can remove extra blank lines


<!-- Sent from Reviewable.io -->

2023-03-03 21:58 UTC, bdomen-ggl reviewed
> Reviewed 3 of 8 files at r2, 4 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/877)* status: 4 of 8 files reviewed, 21 unresolved discussions (waiting on @duliomatos1, @kungfucraig, @SanjayVas, @TNATALI, @wfa-mdharmalingam, and @wfa-siyengar)

___
*[`src/main/terraform/kingdom/gcloud/db.tf` line 19 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/877#-NPcwbM7A0DoqmoD14gk:-NPcwbM7A0DoqmoD14gl:b-x6f7tw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1431895f198616b02e3c16aa2fbe320f9f47e2d5/src/main/terraform/kingdom/gcloud/db.tf#L19)):*
> ```HCL
> resource "google_spanner_instance" "halo_spanner_db" {
>   config       = "regional-${var.region}"
>   display_name = "spanner_instance"
> ```

Feel like we want a more specific name, but right now we have `dev-instance` so I guess `qa-instance` works for now.
___
*[`src/main/terraform/kingdom/gcloud/db.tf` line 25 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/877#-NPd2bHU96AbGM3ni_Hv:-NPcweU_DynfGsOjY8Wh:b-56hf1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1431895f198616b02e3c16aa2fbe320f9f47e2d5/src/main/terraform/kingdom/gcloud/db.tf#L25)):*
> ```HCL
> resource "google_spanner_database" "database" {
>   instance = google_spanner_instance.halo_spanner_db.name
>   name     = "spanner_database"
> ```

Feel like we want a more specific name, but right now we have `kingdom` so I guess that works for now.
___
*[`src/main/terraform/kingdom/gcloud/db.tf` line 29 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/877#-NPcwgcV6gJ5PmIWNtHq:-NPcwgcV6gJ5PmIWNtHr:b-2zcx2q) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1431895f198616b02e3c16aa2fbe320f9f47e2d5/src/main/terraform/kingdom/gcloud/db.tf#L29)):*
> ```HCL
>   deletion_protection = false
> 
>   depends_on = [google_spanner_instance.halo_spanner_db]
> ```

Nice idea, but since the instance references `google_spanner_isntance.halo_spanner_db` already, there's an implicit dependency. In other words, you don't need this unless there's some indirect dependency.

As a nitpick, this usually goes at or near the top to make it easy to track resource meta items.
___
*[`src/main/terraform/kingdom/gcloud/external_ip.tf` line 17 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/877#-NPd3HiO-s6DubefZDhO:-NPd3HiO-s6DubefZDhP:b-qzn9r) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1431895f198616b02e3c16aa2fbe320f9f47e2d5/src/main/terraform/kingdom/gcloud/external_ip.tf#L17)):*
> ```HCL
> # This is step 10a as per the document https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/docs/gke/kingdom-deployment.md
> 
> resource "google_compute_address" "v2alpha-public-api-server-ip" {
> ```

NOTE: Looks good for now, but I'm not familiar with using these. May have to work out the details during integration and end to end testing.
___
*[`src/main/terraform/kingdom/gcloud/gke.tf` line 19 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/877#-NPd3ZxD8uZ5OhuKqxq6:-NPd3ZxD8uZ5OhuKqxq7:bec6se7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1431895f198616b02e3c16aa2fbe320f9f47e2d5/src/main/terraform/kingdom/gcloud/gke.tf#L19)):*
> ```HCL
> # Create a GKE cluster with 3 node pools
> resource "google_container_cluster" "cluster" {
>   name     = "kingdom-cluster"
> ```

The current name is `halo-cmm-kingdom-demo-cluster`, so we could name this something like `halo-cmm-kingdom-qa-cluster` (or maybe even use the same name as the existing one)
___
*[`src/main/terraform/kingdom/gcloud/gke.tf` line 25 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/877#-NPd7Qaq5u5wRhJTMXMV:-NPd7Qaq5u5wRhJTMXMW:b7c4bsr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1431895f198616b02e3c16aa2fbe320f9f47e2d5/src/main/terraform/kingdom/gcloud/gke.tf#L25)):*
> ```HCL
>   initial_node_count = 1
> 
>   # Add three node pools
> ```

@SanjayVas Do we deploy with three node pools? I only see one (default). Maybe the confusion is that we create multiple services and deployments in a single node pool? Or maybe I missed something and we are supposed to have multiple node pools?
___
*[`src/main/terraform/kingdom/gcloud/gke.tf` line 26 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/877#-NPd7Tz3A0Ymdn-9Evbv:-NPd7Tz3A0Ymdn-9Evbw:buwxn92) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1431895f198616b02e3c16aa2fbe320f9f47e2d5/src/main/terraform/kingdom/gcloud/gke.tf#L26)):*
> ```HCL
> 
>   # Add three node pools
>   node_pool {
> ```

It's recommended NOT to use the inline `node_pool` attribute unless you're 100% positive these are the node pools you'll want for the lifetime of the cluster. If changed (updated, added or removed), the cluster will be destroyed and re-created. The Terraform recommendation is to use the `google_conatiner_node_pool` resource instead.

Comment on `node_pool` parameter
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster#node_pool

Node Pool resource
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_node_pool
___
*[`src/main/terraform/kingdom/gcloud/gke.tf` line 29 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/877#-NPd7d6V5J1_kKx4I99t:-NPd7d6V5J1_kKx4I99u:bqpf25z) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1431895f198616b02e3c16aa2fbe320f9f47e2d5/src/main/terraform/kingdom/gcloud/gke.tf#L29)):*
> ```HCL
>     name = "gcp-kingdom-data-server"
>     node_count = 1
>     node_config {
> ```

We should include the `autoscaling` attribute (3 to 6) and likewise set node_count to 3.

I didn't look into this in detail, but it looks like adding this to the node_config is recommended too. Maybe we don't need it though.
```
    # Google recommends custom service accounts that have cloud-platform scope and permissions granted via IAM Roles.
    service_account = google_service_account.default.email
    oauth_scopes = [
      "https://www.googleapis.com/auth/cloud-platform"
    ]
```
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_node_pool

Also according to the command in the doc, we are looking to use machine type `e2-highcpu-2` not `n1-standard-1`
___
*[`src/main/terraform/kingdom/gcloud/kms.tf` line 36 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/877#-NPctU-oC45-K4-dr2FW:-NPctU-oC45-K4-dr2FX:boxwndg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/202926781a001e893688ac584f3ba5e2fb2d4709/src/main/terraform/kingdom/gcloud/kms.tf#L36)):*
> ```HCL
>   binding {
>     members = [
>       "serviceAccount:service-1049178966878@compute-system.iam.gserviceaccount.com"
> ```

NOTE: Can leave this for now, but we'll want to de-hardcode things like project ids, project names, and regions/locations. Looks like you started doing that in other files.
___
*[`src/main/terraform/kingdom/gcloud/kms.tf` line 23 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/877#-NPd8i7F7KkGcPHZ3Rdt:-NPd8i7F7KkGcPHZ3Rdu:b-5ay6f5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1431895f198616b02e3c16aa2fbe320f9f47e2d5/src/main/terraform/kingdom/gcloud/kms.tf#L23)):*
> ```HCL
> 
> 
> data "google_kms_key_ring" "m [...]

2023-03-04 10:41 UTC, wfa-siyengar approved these changes

2023-03-04 10:41 UTC, wfa-siyengar commented on src/main/terraform/kingdom/gcloud/db.tf
> +
Request you to mention the reference of the document and specify that this is the step 1 from the doc.

2023-03-04 10:41 UTC, wfa-siyengar approved these changes
> Reviewed 3 of 8 files at r2, 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/877)* status: all files reviewed, 21 unresolved discussions (waiting on @bdomen-ggl, @duliomatos1, @kungfucraig, @SanjayVas, @TNATALI, and @wfa-mdharmalingam)

___
*[`src/main/terraform/kingdom/gcloud/db.tf` line 19 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/877#-NPcwbM7A0DoqmoD14gk:-NPeUTXM-2CUHK6-Xedz:bygvgtc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cbd50dc0f84ff429eedd4d4f0ec5e894ba32de15/src/main/terraform/kingdom/gcloud/db.tf#L19)):*
<details><summary><i>Previously, bdomen-ggl wrote…</i></summary><blockquote>

Feel like we want a more specific name, but right now we have `dev-instance` so I guess `qa-instance` works for now.
</blockquote></details>

I have variablized the environment here. Thanks for the suggestion.
Also removed the hard coding of other configurations in the database.
___
*[`src/main/terraform/kingdom/gcloud/db.tf` line 25 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/877#-NPd2bHU96AbGM3ni_Hv:-NPfbfjlCIoMUxu7LCH1:bv2xqv5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cbd50dc0f84ff429eedd4d4f0ec5e894ba32de15/src/main/terraform/kingdom/gcloud/db.tf#L25)):*
<details><summary><i>Previously, bdomen-ggl wrote…</i></summary><blockquote>

Feel like we want a more specific name, but right now we have `kingdom` so I guess that works for now.
</blockquote></details>

We have variablized the naming annormalized and made names variable controled.
___
*[`src/main/terraform/kingdom/gcloud/db.tf` line 29 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/877#-NPcwgcV6gJ5PmIWNtHq:-NPeTC5cEkAAB6_mPEv9:b-k609j5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cbd50dc0f84ff429eedd4d4f0ec5e894ba32de15/src/main/terraform/kingdom/gcloud/db.tf#L29)):*
<details><summary><i>Previously, bdomen-ggl wrote…</i></summary><blockquote>

Nice idea, but since the instance references `google_spanner_isntance.halo_spanner_db` already, there's an implicit dependency. In other words, you don't need this unless there's some indirect dependency.

As a nitpick, this usually goes at or near the top to make it easy to track resource meta items.
</blockquote></details>

Actually speaking the implicit dependency works fine. We can remove this. You are right!
___
*[`src/main/terraform/kingdom/gcloud/external_ip.tf` line 17 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/877#-NPd3HiO-s6DubefZDhO:-NPeYpc_BiucEQZ16Ho0:be4tfgt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cbd50dc0f84ff429eedd4d4f0ec5e894ba32de15/src/main/terraform/kingdom/gcloud/external_ip.tf#L17)):*
<details><summary><i>Previously, bdomen-ggl wrote…</i></summary><blockquote>

NOTE: Looks good for now, but I'm not familiar with using these. May have to work out the details during integration and end to end testing.
</blockquote></details>

Great, yes the code will evolve and get better as we go.
Keeping the names as requested. NOT ATTACHING PREFIXES
___
*[`src/main/terraform/kingdom/gcloud/gke.tf` line 19 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/877#-NPd3ZxD8uZ5OhuKqxq6:-NPeYy-g96QQNYosRJ7i:b-xguhr1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cbd50dc0f84ff429eedd4d4f0ec5e894ba32de15/src/main/terraform/kingdom/gcloud/gke.tf#L19)):*
<details><summary><i>Previously, bdomen-ggl wrote…</i></summary><blockquote>

The current name is `halo-cmm-kingdom-demo-cluster`, so we could name this something like `halo-cmm-kingdom-qa-cluster` (or maybe even use the same name as the existing one)
</blockquote></details>

I have given a more normalized naming convention, please check if it suits.



_Code snippet:_
```HCL
locals {
  env = var.env
  project = var.project
  component = var.component

  # e.g. Prefix will look like dev-halo-kingdom
  prefix = "${local.env}-${local.project}=${local.component}"
}

variable env {
  type = string
  default = "dev"
  description = "Represents the environment used."
}

variable "project" {
  type = string
  default = "halo"
  description = "This will be the project name used across."
}

variable "component" {
  type = string
  default = "kingdom"
  description = "The component that we are developing."
}
```
___
*[`src/main/terraform/kingdom/gcloud/gke.tf` line 25 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/877#-NPd7Qaq5u5wRhJTMXMV:-NPe_1j42Llo0m580pTe:b-uutv4h) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cbd50dc0f84ff429eedd4d4f0ec5e894ba32de15/src/main/terraform/kingdom/gcloud/gke.tf#L25)):*
<details><summary><i>Previously, bdomen-ggl wrote…</i></summary><blockquote>

@SanjayVas Do we deploy with three node pools? I only see one (default). Maybe the confusion is that we create multiple services and deployments in a single node pool? Or maybe I missed something and we are supposed to have multiple node pools?
</blockquote></details>

Hope there is no action on the code for us.
Even if it need to undergo a change, the hard coding is removed and all moved to variables.tf
___
*[`src/main/terraform/kingdom/gcloud/gke.tf` line 26 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/877#-NPd7Tz3A0Ymdn-9Evbv:-NPeZYgN1Zz_UOVs4xpV:b-gjodex) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cbd50dc0f84ff429eedd4d4f0ec5e894ba32de15/src/main/terraform/kingdom/gcloud/gke.tf#L26)):*
<details><summary><i>Previously, bdomen-ggl wrote…</i></summary><blockquote>

It's recommended NOT to use the inline `node_pool` attribute unless you're 100% positive these are the node pools you'll want for the lifetime of the cluster. If changed (updated, added or removed), the cluster will be destroyed and re-created. The Terraform recommendation is to use the `google_conatiner_node_pool` resource instead.

Comment on `node_pool` parameter
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_cluster#node_pool

Node Pool resource
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_node_pool
</blockquote></details>

Thanks brandon, quite a valueable one. moved the resources to google_conatiner_node_pool.
___
*[`src/main/terraform/kingdom/gcloud/gke.tf` line 29 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/877#-NPd7d6V5J1_kKx4I99t:-NPeahwDCewAPmXmqMzK:b2tv5dy) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cbd50dc0f84ff429eedd4d4f0ec5e894ba32de15/src/main/terraform/kingdom/gcloud/gke.tf#L29)):*
<details><summary><i>Previously, bdomen-ggl wrote…</i></summary><blockquote>

We should include the `autoscaling` attribute (3 to 6) and likewise set node_count to 3.

I didn't look into this in detail, but it looks like adding this to the node_config is recommended too. Maybe we don't need it though.
```
    # Google recommends custom service accounts that have cloud-platform scope and permissions granted via IAM Roles.
    service_account = google_service_account.default.email
    oauth_scopes = [
      "https://www.googleapis.com/auth/cloud-platform"
    ]
```
https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/container_node_pool

Also according to the command in the doc, we are looking to use machine type `e2-highcpu-2` not `n1-standard-1`
</blockquote></details>

Autoscaling enabled for node pools
Removed the disk type and disk [...]

2023-03-06 13:08 UTC, kungfucraig reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/877)* status: 1 of 8 files reviewed, 22 unresolved discussions (waiting on @bdomen-ggl, @duliomatos1, @SanjayVas, @TNATALI, @wfa-mdharmalingam, and @wfa-siyengar)

___
*[`src/main/terraform/kingdom/gcloud/db.tf` line 1 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/877#-NPr1Fh-9tPgvtzmrurD:-NPr1Fh-9tPgvtzmrurE:b-9x369k) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/19f803cd1c1f1243c43d8af2db71799d98cc826b/src/main/terraform/kingdom/gcloud/db.tf#L1)):*
> ```HCL
> # Copyright 2020 The Cross-Media Measurement Authors
> ```

Update dates on all files please.


<!-- Sent from Reviewable.io -->

2023-03-06 13:36 UTC, duliomatos1 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/877)* status: 1 of 8 files reviewed, 18 unresolved discussions (waiting on @bdomen-ggl, @SanjayVas, @TNATALI, @wfa-mdharmalingam, and @wfa-siyengar)

___
*[`src/main/terraform/kingdom/gcloud/variables.tf` line 100 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/877#-NPcRJ2324gxguDqWaTK:-NPr7rHW37CxcgKPG_hR:b-knh0qd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/202926781a001e893688ac584f3ba5e2fb2d4709/src/main/terraform/kingdom/gcloud/variables.tf#L100)):*
<details><summary><i>Previously, wfa-siyengar wrote…</i></summary><blockquote>

last line is needed, linter throws an error without that.
</blockquote></details>

yeah, looks good now


<!-- Sent from Reviewable.io -->

2023-03-06 18:19 UTC, wfa-siyengar approved these changes
> Reviewed 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/877)* status: all files reviewed, 18 unresolved discussions (waiting on @bdomen-ggl, @SanjayVas, @TNATALI, and @wfa-mdharmalingam)



<!-- Sent from Reviewable.io -->

2023-03-06 18:20 UTC, wfa-siyengar approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/877#-:-NPs8hZbCNpwg9Bnc-yH:bnfp4nl)* status: all files reviewed, 18 unresolved discussions (waiting on @bdomen-ggl, @SanjayVas, @TNATALI, and @wfa-mdharmalingam)



<!-- Sent from Reviewable.io -->

2023-03-06 19:26 UTC, duliomatos1 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/877)* status: all files reviewed, 18 unresolved discussions (waiting on @bdomen-ggl, @kungfucraig, @SanjayVas, @TNATALI, and @wfa-mdharmalingam)

___
*[`src/main/terraform/kingdom/gcloud/db.tf` line 1 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/877#-NPr1Fh-9tPgvtzmrurD:-NPsIaQs2MMF4pq4aP2d:bauvw2f) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/19f803cd1c1f1243c43d8af2db71799d98cc826b/src/main/terraform/kingdom/gcloud/db.tf#L1)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Update dates on all files please.
</blockquote></details>

just the year, right?
`# Copyright 2023 The Cross-Media Measurement Authors`



_Code quote:_
```HCL
# Copyright 2020 The Cross-Media Measurement Authors
```


<!-- Sent from Reviewable.io -->

2023-03-07 11:24 UTC, wfa-mdharmalingam reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/877)* status: 1 of 9 files reviewed, 18 unresolved discussions (waiting on @bdomen-ggl, @kungfucraig, @SanjayVas, @TNATALI, and @wfa-siyengar)

___
*[`src/main/terraform/kingdom/gcloud/db.tf` line 1 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/877#-NPr1Fh-9tPgvtzmrurD:-NPvnH1QE2CTN5syV5rH:b-pg2yu6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/19f803cd1c1f1243c43d8af2db71799d98cc826b/src/main/terraform/kingdom/gcloud/db.tf#L1)):*
<details><summary><i>Previously, duliomatos1 (Dulio Matos) wrote…</i></summary><blockquote>

just the year, right?
`# Copyright 2023 The Cross-Media Measurement Authors`
</blockquote></details>

Copyright date has been changed to 2023 
___
*[`src/main/terraform/kingdom/gcloud/gke.tf` line 25 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/877#-NPd7Qaq5u5wRhJTMXMV:-NPvnSJkAXpJ-Nd31kQZ:b-e3lt8b) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cbd50dc0f84ff429eedd4d4f0ec5e894ba32de15/src/main/terraform/kingdom/gcloud/gke.tf#L25)):*
<details><summary><i>Previously, wfa-siyengar wrote…</i></summary><blockquote>

Hope there is no action on the code for us.
Even if it need to undergo a change, the hard coding is removed and all moved to variables.tf
</blockquote></details>

Node pool count has been reduced from 3 to 1 


<!-- Sent from Reviewable.io -->

2023-03-07 13:07 UTC, kungfucraig reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/877)* status: 1 of 9 files reviewed, 17 unresolved discussions (waiting on @bdomen-ggl, @SanjayVas, @TNATALI, @wfa-mdharmalingam, and @wfa-siyengar)



<!-- Sent from Reviewable.io -->

2023-03-07 13:12 UTC, kungfucraig requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/877)* status: 1 of 9 files reviewed, 18 unresolved discussions (waiting on @bdomen-ggl, @SanjayVas, @TNATALI, @wfa-mdharmalingam, and @wfa-siyengar)

___
*[`src/main/terraform/kingdom/gcloud/kms.tf` line 34 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/877#-NPwBt5i7y8o6b8KkLZr:-NPwBt5i7y8o6b8KkLZs:bjsf9k) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3f854a9a295f6e1b09ab90a607f812562d1b04cd/src/main/terraform/kingdom/gcloud/kms.tf#L34)):*
> ```HCL
>   }
> }
> */
> ```

Make sure all files end with a newline.


<!-- Sent from Reviewable.io -->

2023-03-07 13:15 UTC, kungfucraig requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/877)* status: 1 of 9 files reviewed, 19 unresolved discussions (waiting on @bdomen-ggl, @SanjayVas, @TNATALI, @wfa-mdharmalingam, and @wfa-siyengar)

___
*[`src/main/terraform/kingdom/gcloud/kms.tf` line 17 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/877#-NPwCN3f-UK6TqluTbBT:-NPwCN3f-UK6TqluTbBU:b-7pco65) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3f854a9a295f6e1b09ab90a607f812562d1b04cd/src/main/terraform/kingdom/gcloud/kms.tf#L17)):*
> ```HCL
> # This is step 3 as per the document
> # https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/docs/gke/kingdom-deployment.md
> /*
> ```

Per discussion:

We will set up keys outside of TF and create variables here to reference them, but leave the vars in the vars file. 

Delete this file.


<!-- Sent from Reviewable.io -->

2023-03-07 13:18 UTC, bdomen-ggl reviewed
> Reviewed 2 of 8 files at r2, 1 of 6 files at r3, 5 of 7 files at r4, 6 of 8 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/877)* status: all files reviewed, 4 unresolved discussions (waiting on @SanjayVas, @TNATALI, and @wfa-mdharmalingam)



<!-- Sent from Reviewable.io -->

2023-03-07 13:29 UTC, duliomatos1 approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>
given @bdomen-ggl's comments are resolved

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/877#-:-NPwAG_U-hOqSzTo2HPP:bfs7tuw)* status: 8 of 9 files reviewed, 4 unresolved discussions (waiting on @bdomen-ggl, @SanjayVas, @TNATALI, and @wfa-mdharmalingam)



<!-- Sent from Reviewable.io -->

2023-03-07 13:37 UTC, bdomen-ggl approved these changes
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/877)* status: all files reviewed, 4 unresolved discussions (waiting on @SanjayVas, @TNATALI, and @wfa-mdharmalingam)



<!-- Sent from Reviewable.io -->

2023-03-07 16:22 UTC, kungfucraig reviewed
> Reviewed 1 of 8 files at r2, 6 of 8 files at r5, 2 of 2 files at r6, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/877)* status: all files reviewed, 4 unresolved discussions (waiting on @SanjayVas, @TNATALI, and @wfa-mdharmalingam)



<!-- Sent from Reviewable.io -->

2023-03-07 16:22 UTC, kungfucraig approved these changes

2023-03-08 16:22 UTC, wfa-siyengar approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/877)* status: all files reviewed, 1 unresolved discussion (waiting on @kungfucraig, @SanjayVas, and @TNATALI)

___
*[`src/main/terraform/kingdom/gcloud/kms.tf` line 17 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/877#-NPwCN3f-UK6TqluTbBT:-NQ10SoHAhXELDCOdr4m:brbuew1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/3f854a9a295f6e1b09ab90a607f812562d1b04cd/src/main/terraform/kingdom/gcloud/kms.tf#L17)):*
<details><summary><i>Previously, wfa-siyengar wrote…</i></summary><blockquote>

Agreed on the Keys outside TF, we may still need the Data resources, that is what we have in this file. With a crypto Key.
</blockquote></details>

@kungfucraig the KMS key is managed as a outside resource only, the kms.tf is having code only to query that resource.


<!-- Sent from Reviewable.io -->

2023-03-08 16:50 UTC, wfa-siyengar approved these changes
> Dismissed @kungfucraig from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/877)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas and @TNATALI)



<!-- Sent from Reviewable.io -->

2023-03-08 16:57 UTC, merged