Include lock expiration in ComputationToken.
world-federation-of-advertisers/cross-media-measurement pull request #910
Opened 2023-03-22 23:23 UTC by SanjayVas

This will allow a Mill to time out processing as soon as the lock expires, rather than wasting time on an operation that can no longer succeed.

2023-03-22 23:24 UTC, wfa-reviewable commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/910)
<!-- Reviewable:end -->

2023-03-22 23:24 UTC, SanjayVas commented
Depends on #906.
CC @renjiezh

2023-03-23 15:22 UTC, YuhongWang-Amazon approved these changes
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/910)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)



<!-- Sent from Reviewable.io -->

2023-03-29 21:05 UTC, SanjayVas reviewed
> Reviewed 4 of 5 files at r5, 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/910)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)



<!-- Sent from Reviewable.io -->

2023-04-05 21:21 UTC, SanjayVas commented
@renjiezh PTAL. I had to change some behavior w.r.t. LockExpirationTime.

2023-04-05 22:18 UTC, renjiezh requested changes
> Reviewed 3 of 5 files at r5, 4 of 4 files at r6, 4 of 4 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/910)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/deploy/gcloud/spanner/computation/UnclaimedTasksQuery.kt` line 40 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/910#-NSIStbkEWLF3spypLY2:-NSIStbkEWLF3spypLY3:b-dft07l) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2f844dac81bb050c157197dfc48d3db4a939ea3c/src/main/kotlin/org/wfanet/measurement/duchy/deploy/gcloud/spanner/computation/UnclaimedTasksQuery.kt#L40)):*
> ```Kotlin
>       JOIN ComputationStages AS cs USING(ComputationId, ComputationStage)
>       WHERE c.Protocol = @protocol
>         AND (c.LockExpirationTime IS NULL OR c.LockExpirationTime <= @current_time)
> ```

Duchy relies on the LockExpirationTime to determine if a Computation is in a claimable stage. (As it is not using a stage filter.) See [computation_service.proto](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/main/proto/wfa/measurement/internal/duchy/computations_service.proto#L188-L204) and [mutationToChangeStage](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/main/proto/wfa/measurement/internal/duchy/computations_service.proto#L188-L204).
Seems this change will lead mill to claims computations in unavailable stages.
The same issue for the creation change.


<!-- Sent from Reviewable.io -->

2023-04-05 22:43 UTC, renjiezh requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/910)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/deploy/gcloud/spanner/computation/UnclaimedTasksQuery.kt` line 40 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/910#-NSIStbkEWLF3spypLY2:-NSIYrqzDC_XJ6jZAxVo:b-nm9rj8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2f844dac81bb050c157197dfc48d3db4a939ea3c/src/main/kotlin/org/wfanet/measurement/duchy/deploy/gcloud/spanner/computation/UnclaimedTasksQuery.kt#L40)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Is the issue that some methods (endComputation) clear the LockExpirationTime? Is that the only thing that makes such Computations no longer claimable?
</blockquote></details>

We have 13 stages. Only part of them should be claimed by mill. When changing the stage, the request should specify whether the stage is claimable using the enum `AfterTransition`. Thus the claimable computations have null as lockOwner and non-null expirationtime in database.
All operations changing stage should take care of `AfterTransition`.
I know this is a little bit tricky. 


<!-- Sent from Reviewable.io -->

2023-04-05 23:17 UTC, SanjayVas reviewed
> Reviewed 1 of 4 files at r7, 1 of 6 files at r9.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/910)* status: 7 of 12 files reviewed, 1 unresolved discussion (waiting on @renjiezh)

___
*[`src/main/kotlin/org/wfanet/measurement/duchy/deploy/gcloud/spanner/computation/UnclaimedTasksQuery.kt` line 40 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/910#-NSIStbkEWLF3spypLY2:-NSIYeXT-_6jDzLVjEjS:b-6y10hc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/2f844dac81bb050c157197dfc48d3db4a939ea3c/src/main/kotlin/org/wfanet/measurement/duchy/deploy/gcloud/spanner/computation/UnclaimedTasksQuery.kt#L40)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

We have 13 stages. Only part of them should be claimed by mill. When changing the stage, the request should specify whether the stage is claimable using the enum `AfterTransition`. Thus the claimable computations have null as lockOwner and non-null expirationtime in database.
All operations changing stage should take care of `AfterTransition`.
I know this is a little bit tricky. 
</blockquote></details>

Okay, I reverted that change and updated the test. Added some documentation to make the interaction between LockExpirationTime and eligibility to be claimed clear.


<!-- Sent from Reviewable.io -->

2023-04-06 07:13 UTC, renjiezh approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 5 of 6 files at r9, 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/910#-:-NSKPBRBEEXFxcdutxT2:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)



<!-- Sent from Reviewable.io -->

2023-04-06 07:13 UTC, merged