Implement reach measurement type
world-federation-of-advertisers/cross-media-measurement pull request #911
Opened 2023-03-23 01:35 UTC by riemanli

Implement reach-only measurements without breaking the current usage in upstream services.

2023-03-23 01:35 UTC, wfa-reviewable commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/911)
<!-- Reviewable:end -->

2023-03-23 17:33 UTC, SanjayVas requested changes
> Reviewed 6 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/911)* status: 6 of 7 files reviewed, 2 unresolved discussions (waiting on @riemanli)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/911#-NREWnqH1TMWU6JVV007:-NREWnqI6Mwrg-c77uWv:b-71h13o) (no related file):*
Where are we ensuring that `Measurement.Result` has no `frequency` value set when the measurement type is `REACH`?

___
___
*[`build/repositories.bzl` line 40 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/911#-NREWKNQ0JRxEviZkM-I:-NREWKNQ0JRxEviZkM-J:b-wmyxk2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0ad502bac2217458cedc914abb7a419f8c334c37/build/repositories.bzl#L40)):*
> ```Starlark
>     wfa_repo_archive(
>         name = "wfa_measurement_proto",
>         commit = "265e1ac06d4d793f6debfdfec84201b59f11642b",
> ```

Add a DO_NOT_SUBMIT comment in TODO format to switch this to version.


<!-- Sent from Reviewable.io -->

2023-03-23 18:35 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/911)* status: 6 of 7 files reviewed, 2 unresolved discussions (waiting on @SanjayVas)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/911#-NREWnqH1TMWU6JVV007:-NREjVew8f9cwMnB4a4V:b-xqzfho) (no related file):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Where are we ensuring that `Measurement.Result` has no `frequency` value set when the measurement type is `REACH`?
</blockquote></details>

That is a great question. Currently, even it's reach-only, the [LLV2 Mill](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2Mill.kt#L720) still sends the result with a frequency map of size "1". We could either follow this or put additional logic to `sendResultToKingdom` function to enforce no `frequency`.

___
___
*[`build/repositories.bzl` line 40 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/911#-NREWKNQ0JRxEviZkM-I:-NREhmcW9WF2c5pUjkCH:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0ad502bac2217458cedc914abb7a419f8c334c37/build/repositories.bzl#L40)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Add a DO_NOT_SUBMIT comment in TODO format to switch this to version.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-03-23 18:48 UTC, SanjayVas requested changes
> Reviewed 1 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/911)* status: 6 of 9 files reviewed, 2 unresolved discussions (waiting on @riemanli)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/911#-NREWnqH1TMWU6JVV007:-NREmUfSE_SB5CoU8dMF:befkxv8) (no related file):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

That is a great question. Currently, even it's reach-only, the [LLV2 Mill](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2Mill.kt#L720) still sends the result with a frequency map of size "1". We could either follow this or put additional logic to `sendResultToKingdom` function to enforce no `frequency`.
</blockquote></details>

The idea is that this is intended to eventually replace the hack of using R/F with max frequency of 1 and just ignoring the result frequency. We still need to support that behavior, but the point of the `REACH` type is being explicit that the result will not include a frequency. The fact that we're doing R/F LLv2 with max frequency of 1 under the hood is an implementation detail.

___
___
*[`build/repositories.bzl` line 40 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/911#-NREWKNQ0JRxEviZkM-I:-NREm7P963wViuiMQpBp:b-5npwuh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0ad502bac2217458cedc914abb7a419f8c334c37/build/repositories.bzl#L40)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

What I meant by using TODO format is

```
# DO_NOT_SUBMIT(world-federation-of-advertisers/cross-media-measurement-api#126): Use version once released.
```


<!-- Sent from Reviewable.io -->

2023-03-30 20:58 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/911)* status: 3 of 15 files reviewed, 2 unresolved discussions (waiting on @SanjayVas)

___
*[`build/repositories.bzl` line 40 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/911#-NREWKNQ0JRxEviZkM-I:-NRigQCc-2klF4yfphUC:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0ad502bac2217458cedc914abb7a419f8c334c37/build/repositories.bzl#L40)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

What I meant by using TODO format is

```
# DO_NOT_SUBMIT(world-federation-of-advertisers/cross-media-measurement-api#126): Use version once released.
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-03-31 20:38 UTC, tristanvuong2021 requested changes
> Reviewed 3 of 7 files at r1, 1 of 3 files at r2, 9 of 10 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/911)* status: 16 of 17 files reviewed, 4 unresolved discussions (waiting on @iverson52000, @renjiezh, @riemanli, @SanjayVas, and @uakyol)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt` line 272 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/911#-NRtO30r0FAfD8uKG0wP:-NRtO30r0FAfD8uKG0wQ:b-ju7zt7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/989c3fce69c6e3632d546775a61c8a7cb504a2c6/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt#L272)):*
> ```Kotlin
>       }
> 
>       val vidSamplingInterval = vidSamplingInterval
> ```

This is unnecessary. Should fix it below too.
___
*[`src/test/kotlin/org/wfanet/measurement/duchy/daemon/herald/HeraldTest.kt` line 155 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/911#-NRtMUGKC_BxXfDt9QUU:-NRtM14zEI5LdsHhztN-:b91hp2t) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/989c3fce69c6e3632d546775a61c8a7cb504a2c6/src/test/kotlin/org/wfanet/measurement/duchy/daemon/herald/HeraldTest.kt#L155)):*
> ```Kotlin
> private val PUBLIC_API_REACH_ONLY_MEASUREMENT_SPEC =
>   MeasurementSpec.newBuilder()
>     .apply {
> ```

Use the other builder instead of builder/apply in new code.


<!-- Sent from Reviewable.io -->

2023-03-31 21:51 UTC, renjiezh approved these changes
> Reviewed 3 of 7 files at r1, 2 of 3 files at r2, 9 of 10 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/911)* status: all files reviewed, 6 unresolved discussions (waiting on @iverson52000, @riemanli, @SanjayVas, @tristanvuong2021, and @uakyol)

___
*[`build/repositories.bzl` line 42 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/911#-NRsZL6k4IWxfn7YmsHo:-NRsZL6k4IWxfn7YmsHp:b-4j6axn) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/989c3fce69c6e3632d546775a61c8a7cb504a2c6/build/repositories.bzl#L42)):*
> ```Starlark
>         repo = "cross-media-measurement-api",
>         sha256 = "cfde44921d11ccc04e22d4dd7a99b45751a3c3eb53e0cb3ba454100ffa616d27",
>         version = "0.28.0",
> ```

nip: 0.28.1 has been released if you want to keep this the latest. It should require no change to your code.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/utils/ComputationConversions.kt` line 275 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/911#-NRtVATSAJrpk7NuNAuN:-NRtVATSAJrpk7NuNAuO:bkrapj2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/989c3fce69c6e3632d546775a61c8a7cb504a2c6/src/main/kotlin/org/wfanet/measurement/duchy/daemon/utils/ComputationConversions.kt#L275)):*
> ```Kotlin
> }
> 
> data class Reach(val reach: Long) : ComputationResult {
> ```

nit: What about renaming it to `ReachResult`?  As well as `ReachAndFrequencyResult`.
___
*[`src/test/kotlin/org/wfanet/measurement/duchy/daemon/herald/HeraldTest.kt` line 155 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/911#-NRtMUGKC_BxXfDt9QUU:-NRt_jva4Wo8R8nKCIP0:bbfceuj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/989c3fce69c6e3632d546775a61c8a7cb504a2c6/src/test/kotlin/org/wfanet/measurement/duchy/daemon/herald/HeraldTest.kt#L155)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Use the other builder instead of builder/apply in new code.
</blockquote></details>

Yeah. Please replace old code by DSL as you can. Appreciate it!


<!-- Sent from Reviewable.io -->

2023-04-01 00:29 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/911)* status: 13 of 17 files reviewed, 4 unresolved discussions (waiting on @iverson52000, @renjiezh, @SanjayVas, @tristanvuong2021, and @uakyol)

___
*[`build/repositories.bzl` line 42 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/911#-NRsZL6k4IWxfn7YmsHo:-NRu7K-j7sgq_HOolk2N:belsklq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/989c3fce69c6e3632d546775a61c8a7cb504a2c6/build/repositories.bzl#L42)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

nip: 0.28.1 has been released if you want to keep this the latest. It should require no change to your code.
</blockquote></details>

Thanks for letting me know!
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/utils/ComputationConversions.kt` line 275 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/911#-NRtVATSAJrpk7NuNAuN:-NRu9jx49XzlhfZVckSN:bad59sg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/989c3fce69c6e3632d546775a61c8a7cb504a2c6/src/main/kotlin/org/wfanet/measurement/duchy/daemon/utils/ComputationConversions.kt#L275)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

nit: What about renaming it to `ReachResult`?  As well as `ReachAndFrequencyResult`.
</blockquote></details>

Thanks for the suggestion. Done
___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt` line 272 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/911#-NRtO30r0FAfD8uKG0wP:-NRuApq17347kKJkboV5:bfhz2u7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/989c3fce69c6e3632d546775a61c8a7cb504a2c6/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt#L272)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

This is unnecessary. Should fix it below too.
</blockquote></details>

Thanks for catching it. Done.
___
*[`src/test/kotlin/org/wfanet/measurement/duchy/daemon/herald/HeraldTest.kt` line 155 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/911#-NRtMUGKC_BxXfDt9QUU:-NRuAx654j10W1RL_fXn:b-ugd4pq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/989c3fce69c6e3632d546775a61c8a7cb504a2c6/src/test/kotlin/org/wfanet/measurement/duchy/daemon/herald/HeraldTest.kt#L155)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

Yeah. Please replace old code by DSL as you can. Appreciate it!
</blockquote></details>

Thanks for bringing this up. I will modify the one added by me and try my best to update the existing ones.


<!-- Sent from Reviewable.io -->

2023-04-01 02:08 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/911)* status: 10 of 17 files reviewed, 4 unresolved discussions (waiting on @iverson52000, @renjiezh, @SanjayVas, @tristanvuong2021, and @uakyol)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/911#-NREWnqH1TMWU6JVV007:-NRuZd8G5mmCdUmxpqB0:b-896fix) (no related file):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The idea is that this is intended to eventually replace the hack of using R/F with max frequency of 1 and just ignoring the result frequency. We still need to support that behavior, but the point of the `REACH` type is being explicit that the result will not include a frequency. The fact that we're doing R/F LLv2 with max frequency of 1 under the hood is an implementation detail.
</blockquote></details>

Done.

___


<!-- Sent from Reviewable.io -->

2023-04-03 18:42 UTC, SanjayVas requested changes
> Reviewed 5 of 10 files at r3, 2 of 3 files at r4, 4 of 4 files at r5, 2 of 3 files at r6, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/911)* status: all files reviewed, 5 unresolved discussions (waiting on @iverson52000, @riemanli, and @uakyol)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 739 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/911#-NS7LYl50SYxVvbthy7y:-NS7LYl50SYxVvbthy7z:b-4oiagi) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5e6ba9c003ef739bb2e3068ae662efb5753830ed/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L739)):*
> ```Kotlin
> 
>     logger.info("Generating publisher noise for direct reach and frequency...")
>     val publisherNoise = generatePublisherNoise(measurementSpec, frequencyMap.keys.toList())
> ```

Does the function need to take in a `List`, or would e.g. an `Iterable` be sufficient such that we could avoid this conversion?



_Code quote:_
```Kotlin
frequencyMap.keys.toList()
```
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 909 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/911#-NS7Mzpp4QBHxtliLGWJ:-NS7MzpqCVsUefEHXvZi:b-fr50l) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5e6ba9c003ef739bb2e3068ae662efb5753830ed/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L909)):*
> ```Kotlin
>             // Reseed random number generator so the results can be verified in tests.
>             // TODO(@iverson52000): make randomSeed an input once create noiser class.
>             laplaceForReach.reseedRandomGenerator(1)
> ```

You'll likely need to reconcile this with #904, as that changes how we handle seeding the RNG.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulator.kt` line 63 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/911#-NS7NT_Y9eSr87v-l890:-NS7NT_Y9eSr87v-l891:b-xztp1h) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5e6ba9c003ef739bb2e3068ae662efb5753830ed/src/main/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulator.kt#L63)):*
> ```Kotlin
> import org.wfanet.measurement.api.v2alpha.MeasurementSpecKt.duration
> import org.wfanet.measurement.api.v2alpha.MeasurementSpecKt.impression
> import org.wfanet.measurement.api.v2alpha.MeasurementSpecKt.reach as reachSpec
> ```

This could trigger https://youtrack.jetbrains.com/issue/KTIJ-16471/

Avoid import aliases for functions on objects/classes. If you want to add an import alias, do so for the enclosing type.



_Suggestion:_
```Kotlin
import org.wfanet.measurement.api.v2alpha.MeasurementSpecKt as MeasurementSpecs
```
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulator.kt` line 426 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/911#-NS7O7arDRhxO_DvSfHw:-NS7O7arDRhxO_DvSfHx:b-wuxyew) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5e6ba9c003ef739bb2e3068ae662efb5753830ed/src/main/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulator.kt#L426)):*
> ```Kotlin
>   private suspend fun getReachResult(measurementName: String): Result? {
>     val measurement = getMeasurement(measurementName)
>     logger.info("Current Measurement state is: " + measurement.state)
> ```

Extract this block, as it's repeated multiple times in this file. Maybe move the "current state" logging into `getMeasurement` and add a `checkMeasurementNotFailed` function?



_Code quote:_
```Kotlin
    val measurement = getMeasurement(measurementName)
    logger.info("Current Measurement state is: " + measurement.state)
    if (measurement.state == Measurement.State.FAILED) {
      val failure: Failure = measurement.failure
      throw Exception("Measurement failed with reason ${failure.reason}: ${failure.message}")
    }
```
___
*[`src/test/kotlin/org/wfanet/measurement/duchy/daemon/herald/HeraldTest.kt` line 450 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/911#-NS7Pfa13QxpugxIpkL-:-NS7Pfa13QxpugxIpkL0:b-k2cw16) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5e6ba9c003ef739bb2e3068ae662efb5753830ed/src/test/kotlin/org/wfanet/measurement/duchy/daemon/herald/HeraldTest.kt#L450)):*
> ```Kotlin
>         }
>       )
>   }
> ```

nit: blank line between function definitions


<!-- Sent from Reviewable.io -->

2023-04-03 21:20 UTC, uakyol requested changes
> Reviewed 3 of 7 files at r1, 3 of 10 files at r3, 1 of 3 files at r4, 4 of 4 files at r5, 2 of 3 files at r6, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/911)* status: all files reviewed, 7 unresolved discussions (waiting on @iverson52000 and @riemanli)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt` line 276 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/911#-NS7ogFt52iRzkprknlb:-NS7ogFt52iRzkprknlc:b-p0ltxp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/de0c8df34d21704b98fb371f209fd9aac4ac1083/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt#L276)):*
> ```Kotlin
>       }
> 
>       val vidSamplingInterval = vidSamplingInterval
> ```

what happened to this val? Was it not being used?
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 140 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/911#-NS7xUFS9kv5fh2noS5B:-NS7xUFS9kv5fh2noS5C:b-e9gypw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5e6ba9c003ef739bb2e3068ae662efb5753830ed/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L140)):*
> ```Kotlin
> )
> 
> data class PublisherNoise(
> ```

IIUC, you are using this only during populating the Measurement Result. While this data class might be useful if the objects were passed around and thus results  of calculations were passed around I see couple reasons to just extract the c

1) Member variables are not always all populated and when not used (like duration) are defaulted. This is confusing and not a good practice to operate on objects with fields that have not meaningful fields
2) As stated above, noising is not redone and thus not saving anything
3) In fact, after noising for frequency you iterate one more time over the map which can be avoided.

I would prefer to just extract functions to calculate the measurement result and put the noising logic in them. Wdyt? I might be missing something. 


<!-- Sent from Reviewable.io -->

2023-04-03 21:50 UTC, uakyol reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/911)* status: all files reviewed, 6 unresolved discussions (waiting on @iverson52000 and @riemanli)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 140 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/911#-NS7xUFS9kv5fh2noS5B:-NS8533iATbs1nqUxJiV:bvx3thd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5e6ba9c003ef739bb2e3068ae662efb5753830ed/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L140)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

IIUC, you are using this only during populating the Measurement Result. While this data class might be useful if the objects were passed around and thus results  of calculations were passed around I see couple reasons to just extract the c

1) Member variables are not always all populated and when not used (like duration) are defaulted. This is confusing and not a good practice to operate on objects with fields that have not meaningful fields
2) As stated above, noising is not redone and thus not saving anything
3) In fact, after noising for frequency you iterate one more time over the map which can be avoided.

I would prefer to just extract functions to calculate the measurement result and put the noising logic in them. Wdyt? I might be missing something. 
</blockquote></details>

Sorry, something went wrong editing the above comment it seems, here is the correct version :  

IIUC, you are using this only during populating the Measurement Result. While this data class might be useful if the objects were passed around and thus results of calculations were cached,  I see couple reasons to just extract it in to couple of functions: 

1. Member variables are not always all populated and when not used (like duration) are defaulted. This is confusing and not a good practice to operate on objects with fields that have not meaningful fields
2. As stated above, noising is not redone and thus not saving anything
3. In fact, after noising for frequency you iterate one more time over the map which can be avoided.

I would prefer to just extract functions to calculate the measurement result and put the noising logic in them. Wdyt? I might be missing something.


<!-- Sent from Reviewable.io -->

2023-04-03 22:01 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/911)* status: all files reviewed, 5 unresolved discussions (waiting on @iverson52000, @SanjayVas, and @uakyol)

___
*[`src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt` line 276 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/911#-NS7ogFt52iRzkprknlb:-NS80Q634jEjS-rAcbmq:b-nqw123) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/de0c8df34d21704b98fb371f209fd9aac4ac1083/src/main/kotlin/org/wfanet/measurement/kingdom/service/api/v2alpha/MeasurementsService.kt#L276)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

what happened to this val? Was it not being used?
</blockquote></details>

Yes. The only place it was used is

``` kotlin
grpcRequire(vidSamplingInterval.width > 0) { "Vid sampling interval is unspecified" }
```

which doesn't need to create a variable for doing it.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 739 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/911#-NS7LYl50SYxVvbthy7y:-NS7mXZq6HcwDLBoPVtb:brydz6g) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5e6ba9c003ef739bb2e3068ae662efb5753830ed/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L739)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Does the function need to take in a `List`, or would e.g. an `Iterable` be sufficient such that we could avoid this conversion?
</blockquote></details>

Good point! Changed to `Iterable`.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 909 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/911#-NS7Mzpp4QBHxtliLGWJ:-NS7o-k96rn4Flky4H6W:b-p6uno3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5e6ba9c003ef739bb2e3068ae662efb5753830ed/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L909)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

You'll likely need to reconcile this with #904, as that changes how we handle seeding the RNG.
</blockquote></details>

Thanks for bringing this up. I synced up with @iverson52000 for this issue. We decided to let #904 merged, and I will resolve the conflicts.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulator.kt` line 63 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/911#-NS7NT_Y9eSr87v-l890:-NS8-cu62zYtJHgjGA4Q:bmqwo8h) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5e6ba9c003ef739bb2e3068ae662efb5753830ed/src/main/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulator.kt#L63)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This could trigger https://youtrack.jetbrains.com/issue/KTIJ-16471/

Avoid import aliases for functions on objects/classes. If you want to add an import alias, do so for the enclosing type.
</blockquote></details>

That's good to know! Modified.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulator.kt` line 426 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/911#-NS7O7arDRhxO_DvSfHw:-NS848ewDglZ_VTBo9oW:b-obdf53) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5e6ba9c003ef739bb2e3068ae662efb5753830ed/src/main/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulator.kt#L426)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Extract this block, as it's repeated multiple times in this file. Maybe move the "current state" logging into `getMeasurement` and add a `checkMeasurementNotFailed` function?
</blockquote></details>

I kept `getMeasurement` as what it is but create another function `getNotFailedMeasurement` to include the code block as `getFailure` needs to get a failed `Measurement`.
___
*[`src/test/kotlin/org/wfanet/measurement/duchy/daemon/herald/HeraldTest.kt` line 450 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/911#-NS7Pfa13QxpugxIpkL-:-NS84PVl5Oj95FLcZNrp:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5e6ba9c003ef739bb2e3068ae662efb5753830ed/src/test/kotlin/org/wfanet/measurement/duchy/daemon/herald/HeraldTest.kt#L450)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: blank line between function definitions
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-04-03 22:30 UTC, SanjayVas requested changes
> Reviewed 3 of 3 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/911)* status: all files reviewed, 2 unresolved discussions (waiting on @iverson52000, @riemanli, and @uakyol)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulator.kt` line 426 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/911#-NS7O7arDRhxO_DvSfHw:-NS8D6jO2XmI8-KzfS19:b-44xsbo) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5e6ba9c003ef739bb2e3068ae662efb5753830ed/src/main/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulator.kt#L426)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

I kept `getMeasurement` as what it is but create another function `getNotFailedMeasurement` to include the code block as `getFailure` needs to get a failed `Measurement`.
</blockquote></details>

The reason I suggested moving the logging for current state is that I believe every call to `getMeasurement` is followed by logging the current state. I had meant the check to be a separate function that's called on the result of `getMeasurement`.

e.g.

```kotlin
private fun checkNotFailed(measurement: Measurement): Measurement {
  check(state != Measurement.State.FAILED) {
    val failure: Failure = measurement.failure
    "Measurement failed with reason ${failure.reason}: ${failure.message}"
  }
  return measurement
}
```

```kotlin
val measurement = checkNotFailed(getMeasurement(measurementName))
```


<!-- Sent from Reviewable.io -->

2023-04-03 22:39 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/911)* status: all files reviewed, 2 unresolved discussions (waiting on @iverson52000 and @uakyol)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 140 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/911#-NS7xUFS9kv5fh2noS5B:-NS89uh8DmyHSxu8br7o:b-vivxga) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5e6ba9c003ef739bb2e3068ae662efb5753830ed/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L140)):*
Thanks for the feedback! The main reason I had this modification is because the function `addPublisherNoise` is specifically for `reachAndFrequency` only, which is not compatible if we have impression or duration in the future. In addition, we already had `fulfill*Measurement` those measurement-type specific functions for each measurement type. Using measurement-type specific functions also for generating noise seems a bit too much for me.

> Member variables are not always all populated and when not used (like duration) are defaulted. This is confusing and not a good practice to operate on objects with fields that have not meaningful fields

I can create an interface `PublisherNoise` and create child noise classes for each measurement type. This way there is no default values for unused noises.

If you insist, I can also fall back to the original design. Let me know what you think. Thanks!


<!-- Sent from Reviewable.io -->

2023-04-03 23:49 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/911)* status: 16 of 17 files reviewed, 2 unresolved discussions (waiting on @iverson52000, @SanjayVas, and @uakyol)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulator.kt` line 426 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/911#-NS7O7arDRhxO_DvSfHw:-NS8IJFB2R5GZj9wZWNx:b73p2f7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5e6ba9c003ef739bb2e3068ae662efb5753830ed/src/main/kotlin/org/wfanet/measurement/loadtest/frontend/FrontendSimulator.kt#L426)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The reason I suggested moving the logging for current state is that I believe every call to `getMeasurement` is followed by logging the current state. I had meant the check to be a separate function that's called on the result of `getMeasurement`.

e.g.

```kotlin
private fun checkNotFailed(measurement: Measurement): Measurement {
  check(state != Measurement.State.FAILED) {
    val failure: Failure = measurement.failure
    "Measurement failed with reason ${failure.reason}: ${failure.message}"
  }
  return measurement
}
```

```kotlin
val measurement = checkNotFailed(getMeasurement(measurementName))
```
</blockquote></details>

Got it. Thanks for correcting. Modified.


<!-- Sent from Reviewable.io -->

2023-04-04 17:47 UTC, SanjayVas approved these changes
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/911)* status: all files reviewed, 1 unresolved discussion (waiting on @iverson52000 and @uakyol)



<!-- Sent from Reviewable.io -->

2023-04-04 21:01 UTC, uakyol reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/911)* status: all files reviewed, 1 unresolved discussion (waiting on @iverson52000)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 140 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/911#-NS7xUFS9kv5fh2noS5B:-NS9OY0W4o9cHroLRid_:b-7eo5gi) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5e6ba9c003ef739bb2e3068ae662efb5753830ed/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L140)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Thanks for the feedback! The main reason I had this modification is because the function `addPublisherNoise` is specifically for `reachAndFrequency` only, which is not compatible if we have impression or duration in the future. In addition, we already had `fulfill*Measurement` those measurement-type specific functions for each measurement type. Using measurement-type specific functions also for generating noise seems a bit too much for me.

> Member variables are not always all populated and when not used (like duration) are defaulted. This is confusing and not a good practice to operate on objects with fields that have not meaningful fields

I can create an interface `PublisherNoise` and create child noise classes for each measurement type. This way there is no default values for unused noises.

If you insist, I can also fall back to the original design. Let me know what you think. Thanks!
</blockquote></details>

 Thanks Rieman.

If you can make it work with the interface + child noise classes it would be great but I think you will have to type cast after you return based on measurement type, which again is not good. 
I think the clean way to do this is actually creating treating each type differently  with helper functions and they can share code. Here is what I am thinking :  



_Code snippet:_
```Kotlin
val requisitionData = 
when (measurementSpec.measurementTypeCase) {
          MeasurementSpec.MeasurementTypeCase.REACH_AND_FREQUENCY -> {
          val (sampledReachValue, frequencyMap) = calculateDirectReachAndFrequency(vidList)
          // addReachAndFreqPublisherNoise is the same as addPublisherNoise from before, just passing in 2 epsilons rather than the 
          // reachAndFrequency message for code sharing
          val (sampledNoisedReachValue, noisedFrequencyMap) = addReachAndFreqPublisherNoise(sampledReachValue, frequencyMap, measurementSpec.reachAndFrequency.reach.epsilon, measurementSpec.reachAndFrequency frequency.epsiloon )
          val scaledNoisedReachValue = (sampledNoisedReachValue / vidSamplingIntervalWidth).toLong()
           MeasurementKt.result {
              reach = reach { value = scaledNoisedReachValue }
              frequency = frequency { relativeFrequencyDistribution.putAll(noisedFrequencyMap) }
            }
          }
          MeasurementSpec.MeasurementTypeCase.IMPRESSION,
          MeasurementSpec.MeasurementTypeCase.DURATION -> {
             error("Measurement type not supported.")
          }
          MeasurementSpec.MeasurementTypeCase.REACH -> {
            MeasurementKt.result {
              reach = reach {
              // addReachPublisherNoise is a new function since we pass in epsilon, we can code share with addReachAndFreqPublisherNoise function.
                val sampledNoisedReachValue = addReachPublisherNoise(sampledReachValue, frequencyMap, measurementSpec.reach.epsilon)
                val scaledNoisedReachValue = (sampledNoisedReachValue / vidSamplingIntervalWidth).toLong()
                value = scaledNoisedReachValue
              }
            }
          }
          MeasurementSpec.MeasurementTypeCase.MEASUREMENTTYPE_NOT_SET -> {
            error("Measurement type not set.")
          }
        }
```


<!-- Sent from Reviewable.io -->

2023-04-05 01:17 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/911)* status: 16 of 17 files reviewed, 1 unresolved discussion (waiting on @iverson52000, @SanjayVas, and @uakyol)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 140 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/911#-NS7xUFS9kv5fh2noS5B:-NSDtPKx5FEX_BVPduq6:b-1znw5r) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5e6ba9c003ef739bb2e3068ae662efb5753830ed/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L140)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

 Thanks Rieman.

If you can make it work with the interface + child noise classes it would be great but I think you will have to type cast after you return based on measurement type, which again is not good. 
I think the clean way to do this is actually creating treating each type differently  with helper functions and they can share code. Here is what I am thinking :  
</blockquote></details>

Thanks for the suggestion! I incorporated your idea and made the changes. Please take a look and let me know what you think. Thanks!

cc: @iverson52000 for #904.


<!-- Sent from Reviewable.io -->

2023-04-05 01:59 UTC, uakyol requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/911)* status: 16 of 17 files reviewed, 1 unresolved discussion (waiting on @iverson52000, @riemanli, and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 140 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/911#-NS7xUFS9kv5fh2noS5B:-NSE7GesApI8ZYqFAzBY:bcwjqvl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5e6ba9c003ef739bb2e3068ae662efb5753830ed/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L140)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Thanks for the suggestion! I incorporated your idea and made the changes. Please take a look and let me know what you think. Thanks!

cc: @iverson52000 for #904.
</blockquote></details>

looks great Rieman!
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 749 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/911#-NSE7ROH4Sjv1kvFgAYt:-NSE7ROH4Sjv1kvFgAYu:bmolyve) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0191a64498e1614a600d5dc1f293072ab188721e/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L749)):*
> ```Kotlin
>     return when (measurementSpec.measurementTypeCase) {
>       MeasurementSpec.MeasurementTypeCase.REACH_AND_FREQUENCY -> {
>         val (sampledReachValue, frequencyMap) = calculateDirectReachAndFrequency(vidList)
> ```

would you consider splitting calculateDirectReachAndFrequency function to `calculateDirectReach` and  `calculateFrequency` functions? It seems they can be completely separated without any computational cost. 

this way you don't have to unnecessarily calculate and then  ignore the frequencyMap value in the reach only case below.


<!-- Sent from Reviewable.io -->

2023-04-05 02:00 UTC, uakyol commented
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 749 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/911#-NSE7ROH4Sjv1kvFgAYt:-NSE83EJ1bdVI6SYHvju:b-bxeybd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0191a64498e1614a600d5dc1f293072ab188721e/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L749)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

would you consider splitting calculateDirectReachAndFrequency function to `calculateDirectReach` and  `calculateFrequency` functions? It seems they can be completely separated without any computational cost. 

this way you don't have to unnecessarily calculate and then  ignore the frequencyMap value in the reach only case below.

</blockquote></details>

sorry, I meant `calculateDirectFrequency`


<!-- Sent from Reviewable.io -->

2023-04-05 02:01 UTC, uakyol commented
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 740 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/911#-NSE8IMIC-hTTs4L4jge:-NSE8IMIC-hTTs4L4jgf:b-n9lr0a) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0191a64498e1614a600d5dc1f293072ab188721e/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L740)):*
> ```Kotlin
>    * @param measurementSpec Measurement spec.
>    * @param vidList List of VIDs.
>    * @return Noised reach value.
> ```

can you change this to. @return MeasurementResult. 


<!-- Sent from Reviewable.io -->

2023-04-05 02:03 UTC, uakyol requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/911)* status: 16 of 17 files reviewed, 4 unresolved discussions (waiting on @iverson52000, @riemanli, and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 730 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/911#-NSE8W_p5bHPG8yFHjr0:-NSE8W_p5bHPG8yFHjr1:b-scc6tl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0191a64498e1614a600d5dc1f293072ab188721e/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L730)):*
> ```Kotlin
>         }
> 
>     val requisitionData = buildMeasurementResult(measurementSpec, vidList)
> ```

lets rename this val to measurementResult here and in other places?
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 831 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/911#-NSE8hkW9wQAQpBcPaVV:-NSE8hkW9wQAQpBcPaVW:b91fo7j) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0191a64498e1614a600d5dc1f293072ab188721e/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L831)):*
> ```Kotlin
>     requisitionSpec: RequisitionSpec,
>     measurementSpec: MeasurementSpec,
>     requisitionData: Measurement.Result
> ```

while we are here, would you mind changing this input name to measurementResult?


<!-- Sent from Reviewable.io -->

2023-04-05 07:53 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/911)* status: 16 of 17 files reviewed, 4 unresolved discussions (waiting on @iverson52000, @return, @SanjayVas, and @uakyol)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 140 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/911#-NS7xUFS9kv5fh2noS5B:-NSE9bDP0hheo1IEhlwO:by84cxh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5e6ba9c003ef739bb2e3068ae662efb5753830ed/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L140)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

looks great Rieman!
</blockquote></details>

Great. Thanks Ugur!
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 730 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/911#-NSE8W_p5bHPG8yFHjr0:-NSE9iyY0l0gg6hLpc6t:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0191a64498e1614a600d5dc1f293072ab188721e/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L730)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

lets rename this val to measurementResult here and in other places?
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 740 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/911#-NSE8IMIC-hTTs4L4jge:-NSE95xsAKOl40mEw6Pr:b-x8yi3y) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0191a64498e1614a600d5dc1f293072ab188721e/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L740)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

can you change this to. @return MeasurementResult. 
</blockquote></details>

Thanks for catching it! Done.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 749 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/911#-NSE7ROH4Sjv1kvFgAYt:-NSFN-c854HgpawE1rgT:bkx3jeh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0191a64498e1614a600d5dc1f293072ab188721e/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L749)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

sorry, I meant `calculateDirectFrequency`
</blockquote></details>

Sure. Modified.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 831 at r11](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/911#-NSE8hkW9wQAQpBcPaVV:-NSE9ZoF4emD4NYhAaF3:brgq1k0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0191a64498e1614a600d5dc1f293072ab188721e/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L831)):*
<details><summary><i>Previously, uakyol wrote…</i></summary><blockquote>

while we are here, would you mind changing this input name to measurementResult?
</blockquote></details>

Sure. Done.


<!-- Sent from Reviewable.io -->

2023-04-05 17:37 UTC, iverson52000 requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/911)* status: 16 of 17 files reviewed, 1 unresolved discussion (waiting on @riemanli and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 742 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/911#-NSHU9Nj5DNnS-NZDf8J:-NSHU9Nj5DNnS-NZDf8K:b3zka27) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f8ed91d000222d0ec437053ac19faed420bcc11b/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L742)):*
> ```Kotlin
>    * @return [Measurement.Result].
>    */
>   private fun buildMeasurementResult(
> ```

Name this `buildDirectMeasurementResult`?


<!-- Sent from Reviewable.io -->

2023-04-05 18:38 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/911)* status: 16 of 17 files reviewed, 1 unresolved discussion (waiting on @iverson52000 and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 742 at r12](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/911#-NSHU9Nj5DNnS-NZDf8J:-NSHhe7t92xSmEKXTgfE:b-xu0uci) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f8ed91d000222d0ec437053ac19faed420bcc11b/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L742)):*
<details><summary><i>Previously, iverson52000 (Albert Hsu) wrote…</i></summary><blockquote>

Name this `buildDirectMeasurementResult`?
</blockquote></details>

Thanks for the suggestion. Done.


<!-- Sent from Reviewable.io -->

2023-04-05 19:10 UTC, SanjayVas approved these changes
> Reviewed 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/911)* status: all files reviewed, 1 unresolved discussion (waiting on @iverson52000 and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2023-04-06 17:16 UTC, iverson52000 approved these changes
> Reviewed 3 of 7 files at r1, 4 of 10 files at r3, 1 of 3 files at r4, 4 of 4 files at r5, 1 of 3 files at r6, 1 of 1 files at r8, 1 of 3 files at r9, 1 of 1 files at r10, 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/911)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)



<!-- Sent from Reviewable.io -->

2023-04-07 19:31 UTC, Marco-Premier approved these changes
> Reviewed 3 of 7 files at r1, 4 of 10 files at r3, 1 of 3 files at r4, 4 of 4 files at r5, 1 of 3 files at r6, 1 of 1 files at r8, 1 of 3 files at r9, 1 of 1 files at r10, 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/911)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones)



<!-- Sent from Reviewable.io -->

2023-04-10 20:42 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/911)* status: 13 of 17 files reviewed, 1 unresolved discussion (waiting on @iverson52000, @Marco-Premier, @renjiezh, @SanjayVas, @stevenwarejones, @tristanvuong2021, and @uakyol)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/911#-NSgtQWGEEBfDbQcwiJt:-NSgtQWGEEBfDbQcwiJu:bwa26cu) (no related file):*
@uakyol @iverson52000 @Marco-Premier would you please review the new changes in EdpSimulator.kt? I made some small changes to adopt the latest main. Should be fairly easy to review. Thanks!

___


<!-- Sent from Reviewable.io -->

2023-04-10 21:36 UTC, iverson52000 requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/911)* status: 13 of 17 files reviewed, 3 unresolved discussions (waiting on @Marco-Premier, @renjiezh, @riemanli, @SanjayVas, @stevenwarejones, @tristanvuong2021, and @uakyol)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 750 at r15](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/911#-NSh3I5V-GilG1NR5Hg0:-NSh3I5V-GilG1NR5Hg1:b-35h7dz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b4fc28ad9640930b1116e6a97916b510bd6e15db/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L750)):*
> ```Kotlin
> 
>   /**
>    * Add Laplace publisher noise to calculated direct reach.
> ```

Update comment: Add publisher noise to calculated direct reach.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 770 at r15](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/911#-NSh3Wt26O56uIYsGPYw:-NSh3Wt26O56uIYsGPYx:bhpixzf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b4fc28ad9640930b1116e6a97916b510bd6e15db/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L770)):*
> ```Kotlin
> 
>   /**
>    * Add Laplace publisher noise to calculated direct reach and frequency.
> ```

Update comment: Add publisher noise to calculated frequency.


<!-- Sent from Reviewable.io -->

2023-04-10 21:38 UTC, iverson52000 requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/911)* status: 13 of 17 files reviewed, 3 unresolved discussions (waiting on @Marco-Premier, @renjiezh, @riemanli, @SanjayVas, @stevenwarejones, @tristanvuong2021, and @uakyol)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 770 at r15](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/911#-NSh3Wt26O56uIYsGPYw:-NSh5cyh2CiVismoTnFH:b-yvuzzb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b4fc28ad9640930b1116e6a97916b510bd6e15db/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L770)):*
> calculated frequency.
Sorry. calculated direct frequency.


<!-- Sent from Reviewable.io -->

2023-04-10 21:40 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/911)* status: 13 of 17 files reviewed, 3 unresolved discussions (waiting on @iverson52000, @Marco-Premier, @renjiezh, @SanjayVas, @stevenwarejones, @tristanvuong2021, and @uakyol)

___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 750 at r15](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/911#-NSh3I5V-GilG1NR5Hg0:-NSh5f5wALCFHVzq976z:b-x8yi3y) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b4fc28ad9640930b1116e6a97916b510bd6e15db/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L750)):*
<details><summary><i>Previously, iverson52000 (Albert Hsu) wrote…</i></summary><blockquote>

Update comment: Add publisher noise to calculated direct reach.
</blockquote></details>

Thanks for catching it! Done.
___
*[`src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt` line 770 at r15](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/911#-NSh3Wt26O56uIYsGPYw:-NSh62Ez5FkIyUlkdGOH:b-mws2j5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b4fc28ad9640930b1116e6a97916b510bd6e15db/src/main/kotlin/org/wfanet/measurement/loadtest/dataprovider/EdpSimulator.kt#L770)):*
<details><summary><i>Previously, iverson52000 (Albert Hsu) wrote…</i></summary><blockquote>

> calculated frequency.
Sorry. calculated direct frequency.
</blockquote></details>

Thanks for pointing it out! Done.


<!-- Sent from Reviewable.io -->

2023-04-10 21:44 UTC, iverson52000 approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/911)* status: 13 of 17 files reviewed, 1 unresolved discussion (waiting on @Marco-Premier, @renjiezh, @SanjayVas, @stevenwarejones, @tristanvuong2021, and @uakyol)



<!-- Sent from Reviewable.io -->

2023-04-10 22:11 UTC, SanjayVas approved these changes
> Reviewed 1 of 1 files at r14, 2 of 3 files at r15, 1 of 1 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/911)* status: all files reviewed, 1 unresolved discussion (waiting on @Marco-Premier, @stevenwarejones, and @uakyol)



<!-- Sent from Reviewable.io -->

2023-04-11 07:58 UTC, Marco-Premier approved these changes
> Reviewed 1 of 1 files at r14, 2 of 3 files at r15, 1 of 1 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/911)* status: all files reviewed, 1 unresolved discussion (waiting on @stevenwarejones and @uakyol)



<!-- Sent from Reviewable.io -->

2023-04-11 15:56 UTC, riemanli reviewed
> Reviewed 3 of 7 files at r1, 2 of 10 files at r3, 1 of 3 files at r4, 4 of 4 files at r5, 1 of 3 files at r6, 1 of 1 files at r8, 1 of 3 files at r9, 1 of 1 files at r14, 2 of 3 files at r15, 1 of 1 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/911)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones and @uakyol)



<!-- Sent from Reviewable.io -->

2023-04-11 16:27 UTC, riemanli reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/911)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @stevenwarejones and @uakyol)



<!-- Sent from Reviewable.io -->

2023-04-11 16:27 UTC, merged