Apply discrete Gaussian noise into llv2.
world-federation-of-advertisers/cross-media-measurement pull request #917
Opened 2023-03-29 20:20 UTC by renjiezh

2023-03-29 20:21 UTC, wfa-reviewable commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/917)
<!-- Reviewable:end -->

2023-03-31 17:02 UTC, jiayu-google approved these changes
Thanks Renjie!

I confirm that `ComputeMuDiscreteGaussian`, `GetDiscreteGaussianNoiseOptions` and their corresponding tests are correct.

2023-03-31 17:03 UTC, renjiezh commented
> Thanks Renjie!
> 
> I confirm that `ComputeMuDiscreteGaussian`, `GetDiscreteGaussianNoiseOptions` and their corresponding tests are correct.
Appreciate it!

2023-04-03 17:55 UTC, SanjayVas requested changes
> Reviewed 7 of 20 files at r1, 3 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/917)* status: 10 of 23 files reviewed, 2 unresolved discussions (waiting on @iverson52000, @kungfucraig, and @renjiezh)

___
*[`src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/noise_parameters_computation.cc` line 44 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/917#-NS79JY5-5xlW-kMWJbl:-NS79JY5-5xlW-kMWJbm:bi3isyz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8e99bdc7e6be52fe835e4e94c359177c57e27045/src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/noise_parameters_computation.cc#L44)):*
> ```cpp
>   int offset = ComputateMuPolya(params.epsilon(), params.delta(),
>                                 publisher_count, contributor_count);
>   return std::make_unique<math::DistributedGeometricNoiseComponentOptions>(
> ```

Why does this return a pointer? I believe this is a case where there would be no copy due to RVO[^1].

[^1]: https://abseil.io/tips/11



_Code quote:_
```cpp
make_unique
```
___
*[`src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/noise_parameters_computation.cc` line 120 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/917#-NS7CUgu8Vd18Iulb8ht:-NS7CUgu8Vd18Iulb8hu:bswpvrt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8e99bdc7e6be52fe835e4e94c359177c57e27045/src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/noise_parameters_computation.cc#L120)):*
> ```cpp
>     // noise_mechanism == LiquidLegionsV2NoiseConfig::DISCRETE_GAUSSIAN
>     auto noiseOptions =
>         GetDiscreteGaussianNoiseOptions(params, uncorrupted_party_count);
> ```

Since this appears to be using a designated initializer[^1], I believe you can initialize it without any copies being made i.e. not need the struct elements to be pointers in order to avoid copies. See the related https://abseil.io/tips/173 as well.

As an aside, this means our Options types should also probably be `struct`s to be able to take advantage of this feature.

That said, it seems odd to have a struct to keep the options and the noiser together. If you need the options for more than just initializing a Noiser, then just have the Noiser own the options and provide an accessor. Something like:

```c++
// Initialize.
auto noiser = math::DistributedDiscreteGaussianNoiser(BuildDiscreteGaussianNoiseOptions(params, count));

// Use const accessor for options.
auto foo = noiser.options();
```

[^1]: https://abseil.io/tips/172



_Suggestion:_
```cpp
    auto noiseOptions =
        GetDiscreteGaussianNoiseOptions(params, uncorrupted_party_count);
    return {.noiseOptions = noiseOptions, .noiser = math::DistributedDiscreteGaussianNoiser(noiseOptions)};
```


<!-- Sent from Reviewable.io -->

2023-04-03 19:15 UTC, kungfucraig requested changes
> Reviewed 17 of 20 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/917)* status: all files reviewed, 17 unresolved discussions (waiting on @iverson52000, @renjiezh, and @SanjayVas)

___
*[`src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/liquid_legions_v2_encryption_utility.cc` line 559 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/917#-NS7Q_rpCOOEq110TK1x:-NS7Q_rpCOOEq110TK1y:bwzqdv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8e99bdc7e6be52fe835e4e94c359177c57e27045/src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/liquid_legions_v2_encryption_utility.cc#L559)):*
> ```cpp
>                total_noise_tuples_count * kBytesPerFlagsCountTuple);
>   ASSIGN_OR_RETURN(int frequency_dp_noise_tuples_count,
>                    AddFrequencyDpNoise(protocol_cryptor,
> ```

Please revert the whitespace only change.
___
*[`src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/liquid_legions_v2_encryption_utility.cc` line 563 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/917#-NS7QgUkDweJq2ldIP3r:-NS7QgUkDweJq2ldIP3s:b-k00pny) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8e99bdc7e6be52fe835e4e94c359177c57e27045/src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/liquid_legions_v2_encryption_utility.cc#L563)):*
> ```cpp
>                                        curve_id, *noiser, data));
>   ASSIGN_OR_RETURN(int destroyed_noise_tuples_count,
>                    AddDestroyedFrequencyNoise(protocol_cryptor, *noiser, data));
> ```

Revert whitespace change.
___
*[`src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/noise_parameters_computation.cc` line 17 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/917#-NS7TNJJ77_Q1axWXSYy:-NS7TNJJ77_Q1axWXSYz:b67gujq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8e99bdc7e6be52fe835e4e94c359177c57e27045/src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/noise_parameters_computation.cc#L17)):*
> ```cpp
> #include "wfa/measurement/internal/duchy/protocol/liquid_legions_v2/noise_parameters_computation.h"
> 
> #include <utility>
> ```

@jiayu-google @pasin30055 can you both please look at this file?
___
*[`src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/noise_parameters_computation.cc` line 37 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/917#-NS7VQw48AQ2hh1FlJ3E:-NS7VQw48AQ2hh1FlJ3F:b-bbkycb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8e99bdc7e6be52fe835e4e94c359177c57e27045/src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/noise_parameters_computation.cc#L37)):*
> ```cpp
> 
> std::unique_ptr<math::DistributedGeometricNoiseComponentOptions>
> GetGeometricsNoiseOptions(
> ```

s/Geometrics/Geometric
___
*[`src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/noise_parameters_computation.cc` line 39 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/917#-NS7VW4u2frN0ThRVZhQ:-NS7VW4v0aWlBvNlBZoP:b68b56t) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8e99bdc7e6be52fe835e4e94c359177c57e27045/src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/noise_parameters_computation.cc#L39)):*
> ```cpp
> GetGeometricsNoiseOptions(
>     const wfa::measurement::internal::duchy::DifferentialPrivacyParams& params,
>     int publisher_count, int contributor_count) {
> ```

s/contributor_count/uncorrupted_party_count
___
*[`src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/noise_parameters_computation.cc` line 44 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/917#-NS79JY5-5xlW-kMWJbl:-NS7SbzqByj9sGIoKnAy:b32v57) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8e99bdc7e6be52fe835e4e94c359177c57e27045/src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/noise_parameters_computation.cc#L44)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Why does this return a pointer? I believe this is a case where there would be no copy due to RVO[^1].

[^1]: https://abseil.io/tips/11
</blockquote></details>

+1
___
*[`src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/noise_parameters_computation.cc` line 120 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/917#-NS7CUgu8Vd18Iulb8ht:-NS7UJ8B3H6aSQuavlAN:bhgg5jp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8e99bdc7e6be52fe835e4e94c359177c57e27045/src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/noise_parameters_computation.cc#L120)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Since this appears to be using a designated initializer[^1], I believe you can initialize it without any copies being made i.e. not need the struct elements to be pointers in order to avoid copies. See the related https://abseil.io/tips/173 as well.

As an aside, this means our Options types should also probably be `struct`s to be able to take advantage of this feature.

That said, it seems odd to have a struct to keep the options and the noiser together. If you need the options for more than just initializing a Noiser, then just have the Noiser own the options and provide an accessor. Something like:

```c++
// Initialize.
auto noiser = math::DistributedDiscreteGaussianNoiser(BuildDiscreteGaussianNoiseOptions(params, count));

// Use const accessor for options.
auto foo = noiser.options();
```

[^1]: https://abseil.io/tips/172
</blockquote></details>

I agree. Having the noiser hold a copy of the options makes a lot of sense. No harm in it remembering how it was built. 
___
*[`src/main/k8s/testing/secretfiles/llv2_protocol_config_config.textproto` line 15 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/917#-NS7VxHv2r91uAuiBzQ_:-NS7VxHv2r91uAuiBzQa:b-n5um35) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8e99bdc7e6be52fe835e4e94c359177c57e27045/src/main/k8s/testing/secretfiles/llv2_protocol_config_config.textproto#L15)):*
> ```
>   elliptic_curve_id: 415
>   maximum_frequency: 10
>   noise_mechanism: DISCRETE_GAUSSIAN
> ```

GEOMETRIC? Let's keep the old behavior until this can be tested in a live cluster.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2Mill.kt` line 563 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/917#-NS7Qw-u3VQHrHc96-Tj:-NS7Qw-u3VQHrHc96-Tk:b-heqahy) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8e99bdc7e6be52fe835e4e94c359177c57e27045/src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2Mill.kt#L563)):*
> ```Kotlin
>           combinedRegisterVector = readAndCombineAllInputBlobs(token, 1)
>           totalSketchesCount = token.requisitionsCount
>           noiseMechanise = llv2Details.parameters.noise.noiseMechanism
> ```

s/Mechanise/Mechanism
___
*[`src/main/proto/wfa/measurement/internal/duchy/protocol/liquid_legions_v2_encryption_methods.proto` line 118 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/917#-NS7R-Jx-nnZMGSee8ak:-NS7R-Jx-nnZMGSee8al:bz0gex4) ([raw file](https://github.com/world-federation-of-advertise [...]

2023-04-03 20:23 UTC, iverson52000 reviewed
Are we ready to use Gaussian noiser yet? If not, the main purpose and a more accurate title of this PR should be something like: “Use NoiseMechanism in ProtocolConfig.LiquidLegionsV2 to switch between discrete Geometric and Gaussian noiser”

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/917#-:-NS7l0Ak3T0VYRhdHvHO:b-1b528j)* status: all files reviewed, 17 unresolved discussions (waiting on @jiayu-google, @pasin30055, @renjiezh, and @SanjayVas)

___
*[`src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/noise_parameters_computation.cc` line 17 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/917#-NS7TNJJ77_Q1axWXSYy:-NS7lfPj--W8O3g7ZxJp:b-jwv4dm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8e99bdc7e6be52fe835e4e94c359177c57e27045/src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/noise_parameters_computation.cc#L17)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

@jiayu-google @pasin30055 can you both please look at this file?
</blockquote></details>

This is reference from the implementation in this PR in any-sketch: https://github.com/world-federation-of-advertisers/any-sketch/commit/c7eb1c403f5519ff84c5f1f2a59d283bea7b8992#diff-390d1392db0636dab8b184c14d5c1556921e6dc0f448710c97fc2fcc766b62ecR14


<!-- Sent from Reviewable.io -->

2023-04-05 00:45 UTC, jiayu-google requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/917)* status: all files reviewed, 20 unresolved discussions (waiting on @pasin30055, @renjiezh, and @SanjayVas)

___
*[`src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/noise_parameters_computation.cc` line 17 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/917#-NS7TNJJ77_Q1axWXSYy:-NSBpX6DCpcvgaN2atcp:b-2k3d2j) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8e99bdc7e6be52fe835e4e94c359177c57e27045/src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/noise_parameters_computation.cc#L17)):*
<details><summary><i>Previously, iverson52000 (Albert Hsu) wrote…</i></summary><blockquote>

This is reference from the implementation in this PR in any-sketch: https://github.com/world-federation-of-advertisers/any-sketch/commit/c7eb1c403f5519ff84c5f1f2a59d283bea7b8992#diff-390d1392db0636dab8b184c14d5c1556921e6dc0f448710c97fc2fcc766b62ecR14
</blockquote></details>

+1. I have reviewed this file.
___
*[`src/test/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/liquid_legions_v2_encryption_utility_test.cc` line 640 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/917#-NS7X-aY0_23ILMTisHf:-NSDrVpR6OqXTDl5uYzf:b-a7kubd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8e99bdc7e6be52fe835e4e94c359177c57e27045/src/test/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/liquid_legions_v2_encryption_utility_test.cc#L640)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

@jiayu-google and @pasin30055 can you take a look at this as well?
</blockquote></details>

I had a discussion with Renjie and Albert. The following tests lgtm. Renjie will explain more to you when he meets you.

@pasin30055 sorry that you weren't in the meeting since I can't find a slot. Will sync with you in our meeting tmr.


<!-- Sent from Reviewable.io -->

2023-04-06 22:01 UTC, jiayu-google approved these changes

2023-04-11 23:00 UTC, renjiezh reviewed
Per @kungfucraig 's suggestion, an new integration test will be added in following PRs. The details are under discussion(thank you @jiayu-google ). The basic idea is to run `lifeOfMeasurement` test given a fixed input for multiple times and check if results with noise converge into the expected value. This test might take a long time to run so it will be exclude from presubmit test.
Besides, albert has added a converge test for noiser in any_sketch so we are good there. (thank you @iverson52000 )

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/917#-:-NSmWdXp0vEEqJ6wO3kP:b-ssnjl6)* status: 5 of 24 files reviewed, 15 unresolved discussions (waiting on @iverson52000, @jiayu-google, @kungfucraig, @pasin30055, @SanjayVas, and @stevenwarejones)

___
*[`src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/liquid_legions_v2_encryption_utility.cc` line 559 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/917#-NS7Q_rpCOOEq110TK1x:-NSmW1LrAdhLNxWklhwT:bzd061x) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8e99bdc7e6be52fe835e4e94c359177c57e27045/src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/liquid_legions_v2_encryption_utility.cc#L559)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Please revert the whitespace only change.
</blockquote></details>

Hey craig, not sure if I fully understand your comment. These whitespaces are managed by `clang-format`.  Guess I have to blindly follow it to pass the lint check?
___
*[`src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/liquid_legions_v2_encryption_utility.cc` line 563 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/917#-NS7QgUkDweJq2ldIP3r:-NSmWNhE3_zXBfgPnE_W:b-rqxvo7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8e99bdc7e6be52fe835e4e94c359177c57e27045/src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/liquid_legions_v2_encryption_utility.cc#L563)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Revert whitespace change.
</blockquote></details>

ditto.
___
*[`src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/noise_parameters_computation.cc` line 17 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/917#-NS7TNJJ77_Q1axWXSYy:-NSmU4YV0B_OUZQOkAQu:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8e99bdc7e6be52fe835e4e94c359177c57e27045/src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/noise_parameters_computation.cc#L17)):*
<details><summary><i>Previously, jiayu-google wrote…</i></summary><blockquote>

+1. I have reviewed this file.
</blockquote></details>

Done.
___
*[`src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/noise_parameters_computation.cc` line 37 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/917#-NS7VQw48AQ2hh1FlJ3E:-NSmU8ZF8jZnTHMbuW0l:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8e99bdc7e6be52fe835e4e94c359177c57e27045/src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/noise_parameters_computation.cc#L37)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

s/Geometrics/Geometric
</blockquote></details>

Done.
___
*[`src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/noise_parameters_computation.cc` line 39 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/917#-NS7VW4u2frN0ThRVZhQ:-NSmWSR7EOgdu5PWS0aB:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8e99bdc7e6be52fe835e4e94c359177c57e27045/src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/noise_parameters_computation.cc#L39)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

s/contributor_count/uncorrupted_party_count
</blockquote></details>

Done.
___
*[`src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/noise_parameters_computation.cc` line 44 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/917#-NS79JY5-5xlW-kMWJbl:-NSmUmae8wg5cgPIpAoh:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8e99bdc7e6be52fe835e4e94c359177c57e27045/src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/noise_parameters_computation.cc#L44)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.
___
*[`src/main/k8s/testing/secretfiles/llv2_protocol_config_config.textproto` line 15 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/917#-NS7VxHv2r91uAuiBzQ_:-NSmWUs99uHxtXeDl-83:bed80dm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8e99bdc7e6be52fe835e4e94c359177c57e27045/src/main/k8s/testing/secretfiles/llv2_protocol_config_config.textproto#L15)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

GEOMETRIC? Let's keep the old behavior until this can be tested in a live cluster.
</blockquote></details>

Will revert it before submit. Just for test purpose to keep it as DISCRETE_GAUSSIAN.
___
*[`src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2Mill.kt` line 563 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/917#-NS7Qw-u3VQHrHc96-Tj:-NSmVBNSENr46S_lqTkC:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8e99bdc7e6be52fe835e4e94c359177c57e27045/src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2Mill.kt#L563)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

s/Mechanise/Mechanism
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/internal/duchy/protocol/liquid_legions_v2_noise_config.proto` line 52 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/917#-NS7udV76gNQiEoCE6Hb:-NSmVEiOBym9v2xfGxuV:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8e99bdc7e6be52fe835e4e94c359177c57e27045/src/main/proto/wfa/measurement/internal/duchy/protocol/liquid_legions_v2_noise_config.proto#L52)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

delete blank line
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/internal/duchy/protocol/liquid_legions_v2_noise_config.proto` line 57 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/917#-NS7RBpwDejjOQbIzmsf:-NSmVIiV0-b0ztk3gbPk:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8e99bdc7e6be52fe835e4e94c359177c57e27045/src/main/proto/wfa/measurement/internal/duchy/protocol/liquid_legions_v2_noise_config.proto#L57)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Please add a newline
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/internal/kingdom/protocol_config.proto` line 35 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/917#-NS7uim27W7Ihe9gWkFV:-NSmVJYL24AT-AQgm58D:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8e99bdc7e6be52fe835e4e94c359177c57e27045/src/main/ [...]

2023-04-12 18:54 UTC, SanjayVas requested changes
> Reviewed 2 of 20 files at r1, 5 of 11 files at r3, 8 of 14 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/917)* status: 18 of 24 files reviewed, 15 unresolved discussions (waiting on @kungfucraig, @pasin30055, @renjiezh, and @stevenwarejones)

___
*[`src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/noise_parameters_computation.h` line 28 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/917#-NSqnAyo5pYK_u3MpXoX:-NSqnAyo5pYK_u3MpXoY:bi93b4y) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dc0e6c2392dd7947de4c98944dfba532674f67f4/src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/noise_parameters_computation.h#L28)):*
Do these need to be allocated on the heap? I believe the noisers are pretty small.

From https://abseil.io/tips/123:
> Prefer bare object, if it works for your case. Otherwise, try absl::optional. As a last resort, use std::unique_ptr.

Again, RVO should avoid any unnecessary copies.



_Code quote:_
```objc
std::unique_ptr<math::DistributedNoiser>
```
___
*[`src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/noise_parameters_computation.cc` line 44 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/917#-NS79JY5-5xlW-kMWJbl:-NSqlybo8NuCw25Cls-8:b-6qmtog) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8e99bdc7e6be52fe835e4e94c359177c57e27045/src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/noise_parameters_computation.cc#L44)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

Done.
</blockquote></details>

This still appears to be returning a pointer. It should just return a `math::DistributedGeometricNoiseComponentOptions` by value. The same is true for all of the functions which build noise options.


<!-- Sent from Reviewable.io -->

2023-04-12 20:32 UTC, renjiezh reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/917)* status: 23 of 24 files reviewed, 7 unresolved discussions (waiting on @kungfucraig, @pasin30055, @SanjayVas, and @stevenwarejones)

___
*[`src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/noise_parameters_computation.h` line 28 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/917#-NSqnAyo5pYK_u3MpXoX:-NSr9RxA5KnQ40K1XNEB:b4rj0x2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dc0e6c2392dd7947de4c98944dfba532674f67f4/src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/noise_parameters_computation.h#L28)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Thank you sanjay for sharing this tip.

Bare object won't work because the return type is the base class `DistributedNoiser`, which is a abstract class. It is not allowed to return a abstract class.
I am about to use absl::optional, it seems work with abstract class. Does sound good to you?


<!-- Sent from Reviewable.io -->

2023-04-12 20:42 UTC, kungfucraig reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/917)* status: 23 of 24 files reviewed, 7 unresolved discussions (waiting on @pasin30055, @renjiezh, @SanjayVas, and @stevenwarejones)

___
*[`src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/noise_parameters_computation.h` line 28 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/917#-NSqnAyo5pYK_u3MpXoX:-NSrC3TR-v9KyU38aLkV:b9lo4nn) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/dc0e6c2392dd7947de4c98944dfba532674f67f4/src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/noise_parameters_computation.h#L28)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

Thank you sanjay for sharing this tip.

Bare object won't work because the return type is the base class `DistributedNoiser`, which is a abstract class. It is not allowed to return a abstract class.
I am about to use absl::optional, it seems work with abstract class. Does sound good to you?
</blockquote></details>

May as well stick with unique_ptr and save the effort.


<!-- Sent from Reviewable.io -->

2023-04-12 22:22 UTC, renjiezh reviewed
Reverted to make Geometric as the default.

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/917#-:-NSrYvHjAo0m57otD3Bs:b-qnwpui)* status: 22 of 24 files reviewed, 7 unresolved discussions (waiting on @kungfucraig, @pasin30055, @SanjayVas, and @stevenwarejones)

___
*[`src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/noise_parameters_computation.h` line 28 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/917#-NSqnAyo5pYK_u3MpXoX:-NSrYXe34wEH65mL5P68:b-jhyysx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5c8a763c9192d75e43b07ea7d3f8cb370f4eed5b/src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/noise_parameters_computation.h#L28)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

May as well stick with unique_ptr and save the effort.
</blockquote></details>

Got it. Thanks.
___
*[`src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/noise_parameters_computation.cc` line 44 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/917#-NS79JY5-5xlW-kMWJbl:-NSrY_2uACr2AbsgW-6d:b-delxqr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8e99bdc7e6be52fe835e4e94c359177c57e27045/src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/noise_parameters_computation.cc#L44)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This still appears to be returning a pointer. It should just return a `math::DistributedGeometricNoiseComponentOptions` by value. The same is true for all of the functions which build noise options.
</blockquote></details>

Per craig's comment, as we cannot avoid using unique_ptr, seems we should keep this part as is.
___
*[`src/main/k8s/testing/secretfiles/llv2_protocol_config_config.textproto` line 15 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/917#-NS7VxHv2r91uAuiBzQ_:-NSrYtXE3PWYYDpg83yq:bp3aow6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8e99bdc7e6be52fe835e4e94c359177c57e27045/src/main/k8s/testing/secretfiles/llv2_protocol_config_config.textproto#L15)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Please resolve this comment when it's reverted.
</blockquote></details>

Reverted.


<!-- Sent from Reviewable.io -->

2023-04-13 17:35 UTC, SanjayVas requested changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/917)* status: 23 of 24 files reviewed, 6 unresolved discussions (waiting on @kungfucraig, @pasin30055, and @stevenwarejones)

___
*[`src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/noise_parameters_computation.h` line 28 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/917#-NSqnAyo5pYK_u3MpXoX:-NSvegOm4TsVsbwFIP9_:b-gbrqjw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5c8a763c9192d75e43b07ea7d3f8cb370f4eed5b/src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/noise_parameters_computation.h#L28)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

Got it. Thanks.
</blockquote></details>

Ah sorry, didn't spot that the return type was the abstract base class.
___
*[`src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/noise_parameters_computation.cc` line 44 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/917#-NS79JY5-5xlW-kMWJbl:-NSvfQc-BpZwbdoj21ZD:b-ew9gre) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8e99bdc7e6be52fe835e4e94c359177c57e27045/src/main/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/noise_parameters_computation.cc#L44)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

Per craig's comment, as we cannot avoid using unique_ptr, seems we should keep this part as is.
</blockquote></details>

I don't believe that applies here as unlike with the DistributedNoiser factory functions, these return the concrete type rather than an abstract base class.


<!-- Sent from Reviewable.io -->

2023-04-13 19:29 UTC, SanjayVas requested changes
> Reviewed 1 of 14 files at r4, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/917)* status: 23 of 24 files reviewed, 6 unresolved discussions (waiting on @kungfucraig, @pasin30055, @renjiezh, and @stevenwarejones)

___
*[`src/test/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/noise_parameters_computation_test.cc` line 41 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/917#-NSw40ZdEZcUvenNBhQd:-NSw40ZdEZcUvenNBhQe:b1i0sp8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f0d5e3ba6e0a2764ac32c6c78460751de3991a7c/src/test/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/noise_parameters_computation_test.cc#L41)):*
> ```cpp
>   EXPECT_EQ(options.shift_offset, 291);
>   EXPECT_EQ(options.truncate_threshold, 291);
>   auto geometricNoiser =
> ```

If we care about the specific Noiser impl type, why do the factory functions use the abstract base type? Wouldn't it make more sense to just return the specific type in each case? You should be able to assign to a variable of the base type if you need a variable that can hold any noiser.


<!-- Sent from Reviewable.io -->

2023-04-13 20:05 UTC, renjiezh reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/917)* status: 23 of 24 files reviewed, 6 unresolved discussions (waiting on @kungfucraig, @pasin30055, @SanjayVas, and @stevenwarejones)

___
*[`src/test/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/noise_parameters_computation_test.cc` line 41 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/917#-NSw40ZdEZcUvenNBhQd:-NSwCZTq8p5-vjH7Smvu:b-48zfen) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f0d5e3ba6e0a2764ac32c6c78460751de3991a7c/src/test/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/noise_parameters_computation_test.cc#L41)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

If we care about the specific Noiser impl type, why do the factory functions use the abstract base type? Wouldn't it make more sense to just return the specific type in each case? You should be able to assign to a variable of the base type if you need a variable that can hold any noiser.
</blockquote></details>

We don't care about the specific Noiser implementation. The caller should not be aware of that. Guess I should delete this part of verification to be consistent with our test philosophy. 


<!-- Sent from Reviewable.io -->

2023-04-13 20:07 UTC, renjiezh reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/917)* status: 22 of 24 files reviewed, 6 unresolved discussions (waiting on @kungfucraig, @pasin30055, @SanjayVas, and @stevenwarejones)

___
*[`src/test/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/noise_parameters_computation_test.cc` line 41 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/917#-NSw40ZdEZcUvenNBhQd:-NSwDmOI-COEnY8Dnj3o:b-am2rv6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f0d5e3ba6e0a2764ac32c6c78460751de3991a7c/src/test/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/noise_parameters_computation_test.cc#L41)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

We don't care about the specific Noiser implementation. The caller should not be aware of that. Guess I should delete this part of verification to be consistent with our test philosophy. 
</blockquote></details>

Done. Deleted.


<!-- Sent from Reviewable.io -->

2023-04-13 23:12 UTC, SanjayVas approved these changes
> Reviewed 1 of 20 files at r1, 4 of 14 files at r4, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/917)* status: all files reviewed, 5 unresolved discussions (waiting on @kungfucraig, @pasin30055, and @stevenwarejones)

___
*[`src/test/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/noise_parameters_computation_test.cc` line 41 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/917#-NSw40ZdEZcUvenNBhQd:-NSwqOcG099O9XU9uqJ0:b6dw79e) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f0d5e3ba6e0a2764ac32c6c78460751de3991a7c/src/test/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/noise_parameters_computation_test.cc#L41)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

Done. Deleted.
</blockquote></details>

I see that the factory functions may conditionally return a different Noiser type, so I suppose the caller not only *shouldn't* care about the specific type, they cannot really reliably do so.

That said, it would be nice to be able we got the right noise behavior. Is there any way to test that from the public API, e.g. determining that we got the right Noiser by calling `sample()`?


<!-- Sent from Reviewable.io -->

2023-04-14 02:35 UTC, kungfucraig approved these changes
> Reviewed 1 of 14 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/917)* status: all files reviewed, 4 unresolved discussions (waiting on @pasin30055 and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2023-04-14 16:29 UTC, renjiezh reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/917)* status: all files reviewed, 4 unresolved discussions (waiting on @pasin30055 and @stevenwarejones)

___
*[`src/test/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/noise_parameters_computation_test.cc` line 41 at r6](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/917#-NSw40ZdEZcUvenNBhQd:-NT-_hOQATB623U4TFMs:b-bdiwll) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f0d5e3ba6e0a2764ac32c6c78460751de3991a7c/src/test/cc/wfa/measurement/internal/duchy/protocol/liquid_legions_v2/noise_parameters_computation_test.cc#L41)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I see that the factory functions may conditionally return a different Noiser type, so I suppose the caller not only *shouldn't* care about the specific type, they cannot really reliably do so.

That said, it would be nice to be able we got the right noise behavior. Is there any way to test that from the public API, e.g. determining that we got the right Noiser by calling `sample()`?
</blockquote></details>

Hi sanjay, maybe I didn't quite follow your point here. 
The factory functions returns either Geometric or Gaussian noiser only relying on the param of NoiseMechanism. After that, the caller should not be aware of the specific noise type. Given different noise type having different derived class, there won't be mismatch regarding noiser type or noise option type. 


<!-- Sent from Reviewable.io -->

2023-04-14 17:04 UTC, iverson52000 approved these changes
> Reviewed 5 of 20 files at r1, 5 of 11 files at r3, 11 of 14 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/917)* status: all files reviewed, 4 unresolved discussions (waiting on @pasin30055 and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2023-04-17 14:45 UTC, stevenwarejones approved these changes
> Reviewed 2 of 20 files at r1, 6 of 11 files at r3, 11 of 14 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/917)* status: all files reviewed, 2 unresolved discussions (waiting on @Marco-Premier, @pasin30055, and @renjiezh)

___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/InProcessLifeOfAMeasurementIntegrationTest.kt` line 275 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/917#-NTEf-hlB4BP45IyaiRb:-NTEf-hlB4BP45IyaiRc:b-ylbozj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b3021b83139951a356ef8aa2b9b350b393f7077a/src/main/kotlin/org/wfanet/measurement/integration/common/InProcessLifeOfAMeasurementIntegrationTest.kt#L275)):*
> ```Kotlin
>     }
> 
>   // TODO(@renjiez): Add Multi-round test given the same input to verify correctness.
> ```

nit: I think its cleaner to create the test with the name you have here in the todo but leave it blank with a TODO to do it later.


<!-- Sent from Reviewable.io -->

2023-04-17 16:08 UTC, renjiezh reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/917)* status: all files reviewed, 2 unresolved discussions (waiting on @Marco-Premier, @pasin30055, and @stevenwarejones)

___
*[`src/main/kotlin/org/wfanet/measurement/integration/common/InProcessLifeOfAMeasurementIntegrationTest.kt` line 275 at r7](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/917#-NTEf-hlB4BP45IyaiRb:-NTExjaF8GdnmM4afQfq:b63i94b) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b3021b83139951a356ef8aa2b9b350b393f7077a/src/main/kotlin/org/wfanet/measurement/integration/common/InProcessLifeOfAMeasurementIntegrationTest.kt#L275)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

nit: I think its cleaner to create the test with the name you have here in the todo but leave it blank with a TODO to do it later.
</blockquote></details>

Thank you steven. After discussion, we decide to add this test in another file otherwise it will be a presubmit test automatically. Considering the multi-round test might take a long time, we will not add it here as another unit. So I just left a TODO to track the work.


<!-- Sent from Reviewable.io -->

2023-04-17 18:23 UTC, renjiezh reviewed
> Reviewed 5 of 20 files at r1, 5 of 11 files at r3, 11 of 14 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/917)* status: all files reviewed, 1 unresolved discussion (waiting on @Marco-Premier and @pasin30055)



<!-- Sent from Reviewable.io -->

2023-04-17 18:24 UTC, renjiezh reviewed
> Dismissed @kungfucraig from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/917)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Marco-Premier and @pasin30055)



<!-- Sent from Reviewable.io -->

2023-04-17 18:24 UTC, merged