Create CMM Images and push to GitHub Packages.
world-federation-of-advertisers/cross-media-measurement pull request #925
Opened 2023-04-01 14:33 UTC by wfa-siyengar

Changed the ".sh" to executable.

<img width="300" alt="image" src="https://user-images.githubusercontent.com/122861793/229258706-67aa0bd1-7803-4aa0-8448-340cb06e60a0.png">

<img width="577" alt="image" src="https://user-images.githubusercontent.com/122861793/229259024-3cb7097f-d4d2-4718-bb63-0c43adea8e51.png">

<img width="458" alt="image" src="https://user-images.githubusercontent.com/122861793/229175002-25116c51-f249-40e7-83a5-f476fd6d2714.png">

2023-04-01 14:33 UTC, wfa-reviewable commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/925)
<!-- Reviewable:end -->

2023-04-03 18:57 UTC, SanjayVas requested changes
I renamed the PR description to be more accurate.

> Reviewed 17 of 24 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/925#-:-NS7RgZq1AjFTRtpRdOL:b1re71g)* status: 18 of 24 files reviewed, 4 unresolved discussions (waiting on @bdomen-ggl and @wfa-siyengar)

___
*[`.github/workflows/create-and-push-image.yml` line 12 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/925#-NS7Rjn69JJb9rWMild8:-NS7Rjn69JJb9rWMild9:b-yeo43h) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/145d83eaf039a0c554ac0aca92a036702b8e8d80/.github/workflows/create-and-push-image.yml#L12)):*
> ```YAML
> # distributed under the License is distributed on an "AS IS" BASIS,
> # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
> # See the License for the specific language governing permissions and
> ```

The changes to this file should be in a separate PR.
___
*[`.github/workflows/export-image-tag.sh` line 1 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/925#-NS7SBCNBkIEwsYDZKP9:-NS7SBCNBkIEwsYDZKPA:b-yeo43h) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/145d83eaf039a0c554ac0aca92a036702b8e8d80/.github/workflows/export-image-tag.sh#L1)):*
> ```Shell
> #!/usr/bin/env bash
> ```

The changes to this file should be in a separate PR.
___
*[`src/main/terraform/gcloud/vraibles.tf` line 1 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/925#-NS7SGNm5AHEW-22nd6z:-NS7SGNm5AHEW-22nd7-:b6gwik7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/145d83eaf039a0c554ac0aca92a036702b8e8d80/src/main/terraform/gcloud/vraibles.tf#L1)):*
> ```HCL
> # Copyright 2023 The Cross-Media Measurement Authors
> ```

File name typo: `variables.tf`
___
*[`src/main/terraform/gcloud/kingdom/kms.tf` line 17 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/925#-NS7SM3A4xZTGd5pJYnc:-NS7SM3A4xZTGd5pJYnd:bxbhsfk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/145d83eaf039a0c554ac0aca92a036702b8e8d80/src/main/terraform/gcloud/kingdom/kms.tf#L17)):*
> ```HCL
> # This is step 3 as per the document
> # https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/docs/gke/kingdom-deployment.md
> //data "google_kms_key_ring" "my_key_ring" {
> ```

Don't leave chunks of commented-out code behind.

I know there's an issue with KeyRing mutability. IIUC, we're able to leave this here as long as the key ring creation was done by Terraform. I assume you can just manually delete the key ring in the project first if there's an issue with the fact that this file got renamed. @bdomen-ggl correct me if I'm wrong here.


<!-- Sent from Reviewable.io -->

2023-04-07 15:28 UTC, bdomen-ggl reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/925)* status: 14 of 24 files reviewed, 6 unresolved discussions (waiting on @SanjayVas and @wfa-siyengar)

___
*[`src/main/terraform/gcloud/main.tf` line 41 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/925#-NSGsyiB5ccr4YS7WHcS:-NSGsyiB5ccr4YS7WHcT:bj297cb) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a0905c18c3a65e46f1cebcb92a2027f55ef931fa/src/main/terraform/gcloud/main.tf#L41)):*
> ```HCL
> }
> 
> module "worker-3" {
> ```

copypasta? Think this should be `worker-2`
___
*[`src/main/terraform/gcloud/duchy/main.tf` line 19 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/925#-NSGv0QQBgEKw8_xxl1n:-NSGv0QQBgEKw8_xxl1o:bst32kc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7c7b32d8968017b1d413cd9f5d7b38d369c3f9bf/src/main/terraform/gcloud/duchy/main.tf#L19)):*
> ```HCL
> }
> 
> terraform {
> ```

We should have a remote state managed somewhere. Was this moved or exist somewhere and I missed it?
___
*[`src/main/terraform/gcloud/kingdom/kms.tf` line 17 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/925#-NS7SM3A4xZTGd5pJYnc:-NSGtUJEBBstAb6sHftk:bi6a1lm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/145d83eaf039a0c554ac0aca92a036702b8e8d80/src/main/terraform/gcloud/kingdom/kms.tf#L17)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Don't leave chunks of commented-out code behind.

I know there's an issue with KeyRing mutability. IIUC, we're able to leave this here as long as the key ring creation was done by Terraform. I assume you can just manually delete the key ring in the project first if there's an issue with the fact that this file got renamed. @bdomen-ggl correct me if I'm wrong here.
</blockquote></details>

So `data` blocks aren't actually managed by Terraform. You can use them to identify an existing resource managed outside of terraform (eg. manually managed). The benefit of this is that we can manually create a key ring and then use Terraform to manage the crypto keys, but still use info on the key ring for other things (like the parent for the crypto key).
Or in other cases you can use `data` to define some blocks of data used by the resources you create like an IAM permission (data) that you can attach to an IAM policy (resource).

Yes we can leave the key ring as a data block since it's not managed by Terraform, but we would have to ensure it's created beforehand. If we want to change it to a `resource` (managed by Terraform), then we'd have to leave it. Terraform will create the key ring, but if we remove the resource, Terraform will then try to delete the key ring and fail.


<!-- Sent from Reviewable.io -->

2023-04-07 17:55 UTC, SanjayVas requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/925)* status: 14 of 24 files reviewed, 6 unresolved discussions (waiting on @bdomen-ggl and @wfa-siyengar)

___
*[`src/main/terraform/gcloud/kingdom/kms.tf` line 17 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/925#-NS7SM3A4xZTGd5pJYnc:-NSRqtVx9T48_7ltCLOq:b-dlpsqk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/145d83eaf039a0c554ac0aca92a036702b8e8d80/src/main/terraform/gcloud/kingdom/kms.tf#L17)):*
<details><summary><i>Previously, bdomen-ggl wrote…</i></summary><blockquote>

So `data` blocks aren't actually managed by Terraform. You can use them to identify an existing resource managed outside of terraform (eg. manually managed). The benefit of this is that we can manually create a key ring and then use Terraform to manage the crypto keys, but still use info on the key ring for other things (like the parent for the crypto key).
Or in other cases you can use `data` to define some blocks of data used by the resources you create like an IAM permission (data) that you can attach to an IAM policy (resource).

Yes we can leave the key ring as a data block since it's not managed by Terraform, but we would have to ensure it's created beforehand. If we want to change it to a `resource` (managed by Terraform), then we'd have to leave it. Terraform will create the key ring, but if we remove the resource, Terraform will then try to delete the key ring and fail.
</blockquote></details>

A `data` block seems fine then, but it certainly shouldn't be commented-out.


<!-- Sent from Reviewable.io -->

2023-04-08 01:29 UTC, wfa-siyengar reviewed
> Reviewed 17 of 24 files at r3, 1 of 1 files at r4, 4 of 4 files at r5, 2 of 2 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/925)* status: all files reviewed, 6 unresolved discussions (waiting on @bdomen-ggl and @SanjayVas)

___
*[`src/main/terraform/gcloud/main.tf` line 41 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/925#-NSGsyiB5ccr4YS7WHcS:-NSTREFb2qpg-ZVLqFRG:b-s6bxz0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a0905c18c3a65e46f1cebcb92a2027f55ef931fa/src/main/terraform/gcloud/main.tf#L41)):*
<details><summary><i>Previously, bdomen-ggl wrote…</i></summary><blockquote>

copypasta? Think this should be `worker-2`
</blockquote></details>

Corrected, You really have a Hawkeye. 

Thanks Sanjay the PR review experience so far was so frustrating but experienced great learning. You really have some patience man. Appreciate it.
___
*[`src/main/terraform/gcloud/vraibles.tf` line 1 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/925#-NS7SGNm5AHEW-22nd6z:-NSTQIMXB11fOB68TeTJ:b-hi8g3j) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/145d83eaf039a0c554ac0aca92a036702b8e8d80/src/main/terraform/gcloud/vraibles.tf#L1)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

File name typo: `variables.tf`
</blockquote></details>

Thanks, will correct it.
___
*[`.github/workflows/export-image-tag.sh` line 1 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/925#-NS7SBCNBkIEwsYDZKP9:-NSTOnla2iGxtkwScPj0:bdk7es6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/145d83eaf039a0c554ac0aca92a036702b8e8d80/.github/workflows/export-image-tag.sh#L1)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The changes to this file should be in a separate PR.
</blockquote></details>

Agreed, its not done here.
___
*[`src/main/terraform/gcloud/duchy/main.tf` line 19 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/925#-NSGv0QQBgEKw8_xxl1n:-NSTQ26JAdxJ5Xdd-sXU:b-gcef02) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/7c7b32d8968017b1d413cd9f5d7b38d369c3f9bf/src/main/terraform/gcloud/duchy/main.tf#L19)):*
<details><summary><i>Previously, bdomen-ggl wrote…</i></summary><blockquote>

We should have a remote state managed somewhere. Was this moved or exist somewhere and I missed it?
</blockquote></details>

The State is managed in the Storage bucket and that code is one level above the modules. The backend definition is in src/main/terraform/gcloud/main.tf
___
*[`src/main/terraform/gcloud/kingdom/kms.tf` line 17 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/925#-NS7SM3A4xZTGd5pJYnc:-NSTPFkICDRt8UHBrIT5:bkyoypn) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/145d83eaf039a0c554ac0aca92a036702b8e8d80/src/main/terraform/gcloud/kingdom/kms.tf#L17)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

A `data` block seems fine then, but it certainly shouldn't be commented-out.
</blockquote></details>

@SanjayVas i have removed the code for now. We may add it in a separate PR if needed.


<!-- Sent from Reviewable.io -->

2023-04-08 01:38 UTC, wfa-siyengar reviewed
Thanks

> Reviewed 5 of 5 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/925#-:-NSTVbxVBTdwblX8au55:b-zcjvte)* status: all files reviewed, 6 unresolved discussions (waiting on @bdomen-ggl and @SanjayVas)

___
*[`.github/workflows/create-and-push-image.yml` line 12 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/925#-NS7Rjn69JJb9rWMild8:-NSTVeDk0wE542QgUH3D:b-3ph92r) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/145d83eaf039a0c554ac0aca92a036702b8e8d80/.github/workflows/create-and-push-image.yml#L12)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The changes to this file should be in a separate PR.
</blockquote></details>

The main PR will have it all.


<!-- Sent from Reviewable.io -->

2023-04-08 06:15 UTC, wfa-siyengar reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/925)* status: all files reviewed, 6 unresolved discussions (waiting on @bdomen-ggl and @SanjayVas)

___
*[`src/main/terraform/gcloud/vraibles.tf` line 1 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/925#-NS7SGNm5AHEW-22nd6z:-NSUFxCF7pxbIFe-LlPp:b-4for5i) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/145d83eaf039a0c554ac0aca92a036702b8e8d80/src/main/terraform/gcloud/vraibles.tf#L1)):*
<details><summary><i>Previously, wfa-siyengar wrote…</i></summary><blockquote>

Thanks, will correct it.
</blockquote></details>

corrected.


<!-- Sent from Reviewable.io -->

2023-04-10 15:05 UTC, bdomen-ggl approved these changes
> Reviewed 14 of 24 files at r3, 4 of 4 files at r5, 1 of 1 files at r7, 5 of 5 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/925)* status: all files reviewed, 4 unresolved discussions (waiting on @SanjayVas)



<!-- Sent from Reviewable.io -->

2023-04-10 17:15 UTC, SanjayVas requested changes
> Reviewed 3 of 24 files at r3, 3 of 4 files at r5, 1 of 1 files at r7, 5 of 5 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/925)* status: all files reviewed, 7 unresolved discussions (waiting on @wfa-siyengar)

___
*[`.github/workflows/create-cmm-infra.yml` line 42 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/925#-NSg44LdA5CmwB_OV8nI:-NSg44LdA5CmwB_OV8nJ:btvfhb2) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c03db77b503a384fb3d76cce86e77bff17e6de24/.github/workflows/create-cmm-infra.yml#L42)):*
> ```YAML
> env:
>   ROOT_PATH: '${{ github.workspace }}/src/main/terraform/gcloud'
>   ENVIRONMENT: 'qa'
> ```

Shouldn't we be using the `environment` input above?



_Code quote:_
```YAML
ENVIRONMENT: 'qa'
```
___
*[`src/main/terraform/gcloud/main.tf` line 48 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/925#-NSg4MjG4nqh9Z6fa9sX:-NSg4MjG4nqh9Z6fa9sY:b9g42ye) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c03db77b503a384fb3d76cce86e77bff17e6de24/src/main/terraform/gcloud/main.tf#L48)):*
> ```HCL
> }
> 
> module "worker-3" {
> ```

There is no worker3. The three Duchies are `worker1`, `worker2`, and `aggregator`.
___
*[`src/main/terraform/gcloud/kingdom/gke.tf` line 54 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/925#-NSg5an0AixOzuMD6yik:-NSg5an0AixOzuMD6yil:bho0ptt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c03db77b503a384fb3d76cce86e77bff17e6de24/src/main/terraform/gcloud/kingdom/gke.tf#L54)):*
> ```HCL
> 
>   # the name will look like dev-halo-duchy-data-server
>   name       = "${local.prefix}-data-server"
> ```

Why does the cluster name have "data-server" in it? That's the suffix of one of the K8s Deployments within the cluster.
___
*[`src/main/terraform/gcloud/kingdom/service_account.tf` line 21 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/925#-NSg732y6YpzPYQYPpDd:-NSg732y6YpzPYQYPpDe:bkx3y4b) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c03db77b503a384fb3d76cce86e77bff17e6de24/src/main/terraform/gcloud/kingdom/service_account.tf#L21)):*
> ```HCL
> # Grant Cloud Spanner database access to the service account for the considered Project ID
> # Bind service-account <------> project_id <----------> spanner_db
> resource "google_service_account" "spanner_service_account" {
> ```

Name this `kingdom-internal`. The fact that it allows access to the Kingdom Spanner DB is not the salient point, but rather the fact that it's the service account used by the Kingdom internal API server.



_Code quote:_
```HCL
resource "google_service_account" "spanner_service_account" {
  account_id   = "spanner-access-sa"
  display_name = "Spanner Access Service Account"
}
```
___
*[`src/main/terraform/gcloud/kingdom/service_account.tf` line 27 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/925#-NSg8g58EEoyJt-iWRqs:-NSg8g58EEoyJt-iWRqt:b-xrud0z) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c03db77b503a384fb3d76cce86e77bff17e6de24/src/main/terraform/gcloud/kingdom/service_account.tf#L27)):*
> ```HCL
> resource "google_project_iam_member" "spanner_access" {
>   project = local.project
>   role    = "roles/spanner.databaseUser"
> ```

Is this granting the `spanner.databaseUser` role at the project level? It should only be granted at the Database level to the Kingdom database, which it looks like you're doing in the section below.

As a reminder, the overall Spanner layout for the QA/nightly environments is:
* Shared Spanner instance for the environment
   * Kingdom DB
   * worker1 Duchy DB
   * worker2 Duchy DB
   * aggregator Duchy DB



_Code quote:_
```HCL
resource "google_project_iam_member" "spanner_access" {
  project = local.project
  role    = "roles/spanner.databaseUser"
  member  = "serviceAccount:${google_service_account.spanner_service_account.email}"
}
```
___
*[`src/main/terraform/gcloud/kingdom/service_account.tf` line 41 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/925#-NSg5s8iAjmERNF5nnlb:-NSg5MgV36nIqeqhBJoa:b-getbvk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c03db77b503a384fb3d76cce86e77bff17e6de24/src/main/terraform/gcloud/kingdom/service_account.tf#L41)):*
> ```HCL
> # Create GKE service account for workload identity
> # Bind IAM role to GKE service account
> resource "google_service_account" "gke_sa" {
> ```

If this is meant to be the least privilege service account for the cluster[^1], then it should be shared across the Kingdom and Duchies like how the Spanner instance is. I don't think it should be defined in the Kingdom module.

[^1]: https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/docs/gke/cluster-config.md#cluster-service-account


<!-- Sent from Reviewable.io -->

2023-04-11 03:07 UTC, wfa-siyengar reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/925)* status: all files reviewed, 7 unresolved discussions (waiting on @SanjayVas)

___
*[`.github/workflows/create-cmm-infra.yml` line 42 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/925#-NSg44LdA5CmwB_OV8nI:-NSiGilx5RIeMu8evJv4:b-ejtqwo) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a95864f79fe6b0521769b73a476ee98e2802cff7/.github/workflows/create-cmm-infra.yml#L42)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Shouldn't we be using the `environment` input above?
</blockquote></details>

There will be more Changes that will be made as per the orchestrator above this one. All of these hard coding will be gone. For now each of these files have to be complete within itself.


<!-- Sent from Reviewable.io -->

2023-04-11 03:30 UTC, wfa-siyengar reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/925)* status: all files reviewed, 7 unresolved discussions (waiting on @SanjayVas, @wfa-hkawalkar, and @wfa-mdharmalingam)

___
*[`src/main/terraform/gcloud/main.tf` line 48 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/925#-NSg4MjG4nqh9Z6fa9sX:-NSiI9oz2u3ZGQpzznWO:b-uwawvw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a95864f79fe6b0521769b73a476ee98e2802cff7/src/main/terraform/gcloud/main.tf#L48)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

There is no worker3. The three Duchies are `worker1`, `worker2`, and `aggregator`.
</blockquote></details>

Changed it to aggregator.
___
*[`src/main/terraform/gcloud/kingdom/gke.tf` line 54 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/925#-NSg5an0AixOzuMD6yik:-NSiIRup6cYxVyqMSwrb:b460b9n) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a95864f79fe6b0521769b73a476ee98e2802cff7/src/main/terraform/gcloud/kingdom/gke.tf#L54)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Why does the cluster name have "data-server" in it? That's the suffix of one of the K8s Deployments within the cluster.
</blockquote></details>

@SanjayVas, request you to provide some suggestion. I have named "duchy_node_pool" and "kingdom_node_pool" for now.
___
*[`src/main/terraform/gcloud/kingdom/service_account.tf` line 21 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/925#-NSg732y6YpzPYQYPpDd:-NSiJwnN6zDVzSY8Si2e:baelngq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a95864f79fe6b0521769b73a476ee98e2802cff7/src/main/terraform/gcloud/kingdom/service_account.tf#L21)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Name this `kingdom-internal`. The fact that it allows access to the Kingdom Spanner DB is not the salient point, but rather the fact that it's the service account used by the Kingdom internal API server.
</blockquote></details>

thanks, Done.
___
*[`src/main/terraform/gcloud/kingdom/service_account.tf` line 27 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/925#-NSg8g58EEoyJt-iWRqs:-NSiKjJgBN2kDZrkN-zw:b-gbqihr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a95864f79fe6b0521769b73a476ee98e2802cff7/src/main/terraform/gcloud/kingdom/service_account.tf#L27)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Is this granting the `spanner.databaseUser` role at the project level? It should only be granted at the Database level to the Kingdom database, which it looks like you're doing in the section below.

As a reminder, the overall Spanner layout for the QA/nightly environments is:
* Shared Spanner instance for the environment
   * Kingdom DB
   * worker1 Duchy DB
   * worker2 Duchy DB
   * aggregator Duchy DB
</blockquote></details>

I am unsure, what it will break. I would suggest we establish the straight path.
And then do the necessary fine tuning.
___
*[`src/main/terraform/gcloud/kingdom/service_account.tf` line 41 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/925#-NSg5s8iAjmERNF5nnlb:-NSiLIr-41GG2SW-wp-B:b-ndc5xj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a95864f79fe6b0521769b73a476ee98e2802cff7/src/main/terraform/gcloud/kingdom/service_account.tf#L41)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

If this is meant to be the least privilege service account for the cluster[^1], then it should be shared across the Kingdom and Duchies like how the Spanner instance is. I don't think it should be defined in the Kingdom module.

[^1]: https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/docs/gke/cluster-config.md#cluster-service-account
</blockquote></details>

@wfa-mdharmalingam @wfa-hkawalkar please check and align. I think Sanjay is right here.

@SanjayVas if i can suggest, can we move this to main and establish a working code and then we chip off and continue optimisations with the working code. It would be easy to test and we will be more confident about the changes.



_Code quote:_
```HCL
resource "google_service_account" "gke_sa" {
```


<!-- Sent from Reviewable.io -->

2023-04-11 03:31 UTC, wfa-siyengar reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/925)* status: all files reviewed, 7 unresolved discussions (waiting on @SanjayVas, @wfa-hkawalkar, and @wfa-mdharmalingam)

___
*[`src/main/terraform/gcloud/kingdom/service_account.tf` line 27 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/925#-NSg8g58EEoyJt-iWRqs:-NSiMRiU3NnBvxooTrS4:bdply8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a95864f79fe6b0521769b73a476ee98e2802cff7/src/main/terraform/gcloud/kingdom/service_account.tf#L27)):*
<details><summary><i>Previously, wfa-siyengar wrote…</i></summary><blockquote>

I am unsure, what it will break. I would suggest we establish the straight path.
And then do the necessary fine tuning.
</blockquote></details>

If its not impacting the cost or the project adversely. @wfa-mdharmalingam @wfa-hkawalkar please take a look and correct it.


<!-- Sent from Reviewable.io -->

2023-04-11 07:09 UTC, wfa-siyengar reviewed
> Reviewed 4 of 4 files at r9, 3 of 3 files at r10, 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/925)* status: all files reviewed, 7 unresolved discussions (waiting on @SanjayVas, @wfa-hkawalkar, and @wfa-mdharmalingam)

___
*[`.github/workflows/create-cmm-infra.yml` line 42 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/925#-NSg44LdA5CmwB_OV8nI:-NSj1YzkB0DZAk4JYIer:bj3dph5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a95864f79fe6b0521769b73a476ee98e2802cff7/.github/workflows/create-cmm-infra.yml#L42)):*
<details><summary><i>Previously, wfa-siyengar wrote…</i></summary><blockquote>

There will be more Changes that will be made as per the orchestrator above this one. All of these hard coding will be gone. For now each of these files have to be complete within itself.
</blockquote></details>

This variable was not even used. Removed it.
___
*[`src/main/terraform/gcloud/kingdom/service_account.tf` line 27 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/925#-NSg8g58EEoyJt-iWRqs:-NSj8A1l7pXJVVXGUq3w:b6wagc9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a95864f79fe6b0521769b73a476ee98e2802cff7/src/main/terraform/gcloud/kingdom/service_account.tf#L27)):*
<details><summary><i>Previously, wfa-siyengar wrote…</i></summary><blockquote>

If its not impacting the cost or the project adversely. @wfa-mdharmalingam @wfa-hkawalkar please take a look and correct it.
</blockquote></details>

Awaiting Comments from @wfa-hkawalkar @wfa-mdharmalingam 
___
*[`src/main/terraform/gcloud/kingdom/service_account.tf` line 41 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/925#-NSg5s8iAjmERNF5nnlb:-NSj5NyC1Cogf2YXi2Rt:b-xhet12) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a95864f79fe6b0521769b73a476ee98e2802cff7/src/main/terraform/gcloud/kingdom/service_account.tf#L41)):*
<details><summary><i>Previously, wfa-siyengar wrote…</i></summary><blockquote>

@wfa-mdharmalingam @wfa-hkawalkar please check and align. I think Sanjay is right here.

@SanjayVas if i can suggest, can we move this to main and establish a working code and then we chip off and continue optimisations with the working code. It would be easy to test and we will be more confident about the changes.
</blockquote></details>

The Spanner db exists on Kingdom and not on Duchy. 

"I don't think it should be defined in the Kingdom module."

May be you meant duchy. If yes, the changes have been made accordingly.


<!-- Sent from Reviewable.io -->

2023-04-11 10:46 UTC, wfa-hkawalkar reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/925)* status: all files reviewed, 7 unresolved discussions (waiting on @SanjayVas and @wfa-mdharmalingam)

___
*[`src/main/terraform/gcloud/kingdom/service_account.tf` line 27 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/925#-NSg8g58EEoyJt-iWRqs:-NSjuorh5XHwIH9Lk4Qo:bknkia4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a95864f79fe6b0521769b73a476ee98e2802cff7/src/main/terraform/gcloud/kingdom/service_account.tf#L27)):*
<details><summary><i>Previously, wfa-siyengar wrote…</i></summary><blockquote>

Awaiting Comments from @wfa-hkawalkar @wfa-mdharmalingam 
</blockquote></details>

The above code is granting access at database level as the role specifies.


<!-- Sent from Reviewable.io -->

2023-04-12 00:04 UTC, SanjayVas requested changes
> Reviewed 3 of 3 files at r10, 2 of 2 files at r11, 2 of 2 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/925)* status: all files reviewed, 2 unresolved discussions (waiting on @wfa-mdharmalingam and @wfa-siyengar)

___
*[`src/main/terraform/gcloud/kingdom/gke.tf` line 54 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/925#-NSg5an0AixOzuMD6yik:-NSmk_4f5PZL1hiXmAAd:b-1q86gf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a95864f79fe6b0521769b73a476ee98e2802cff7/src/main/terraform/gcloud/kingdom/gke.tf#L54)):*
<details><summary><i>Previously, wfa-siyengar wrote…</i></summary><blockquote>

@SanjayVas, request you to provide some suggestion. I have named "duchy_node_pool" and "kingdom_node_pool" for now.
</blockquote></details>

That's fine. You could even just use a hard-coded name, since the node pool name is scoped to the cluster. GKE calls its default node pool `default-pool` by default.
___
*[`src/main/terraform/gcloud/kingdom/service_account.tf` line 21 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/925#-NSg732y6YpzPYQYPpDd:-NSml3Nv5YS11N-eRB5W:bev0sdh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a95864f79fe6b0521769b73a476ee98e2802cff7/src/main/terraform/gcloud/kingdom/service_account.tf#L21)):*
<details><summary><i>Previously, wfa-siyengar wrote…</i></summary><blockquote>

thanks, Done.
</blockquote></details>

`account_id` is the part that I wanted to be `kingdom-internal`. The resource name should follow the established naming convention, e.g. `kingdom_internal`.
___
*[`src/main/terraform/gcloud/kingdom/service_account.tf` line 27 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/925#-NSg8g58EEoyJt-iWRqs:-NSmlSFD-3IIHKVKj7sD:bz0yk9y) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a95864f79fe6b0521769b73a476ee98e2802cff7/src/main/terraform/gcloud/kingdom/service_account.tf#L27)):*
<details><summary><i>Previously, wfa-hkawalkar wrote…</i></summary><blockquote>

The above code is granting access at database level as the role specifies.
</blockquote></details>

As discussed offline, it's the latter `google_spanner_database_iam_binding` resource that appears to be assigning the role for the specific DB. `google_project_iam_member` looks like it's additionally assigning the role at the project level.
___
*[`src/main/terraform/gcloud/kingdom/service_account.tf` line 41 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/925#-NSg5s8iAjmERNF5nnlb:-NSmljY41Mq4UkNmX2Qb:b812tui) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a95864f79fe6b0521769b73a476ee98e2802cff7/src/main/terraform/gcloud/kingdom/service_account.tf#L41)):*
<details><summary><i>Previously, wfa-siyengar wrote…</i></summary><blockquote>

The Spanner db exists on Kingdom and not on Duchy. 

"I don't think it should be defined in the Kingdom module."

May be you meant duchy. If yes, the changes have been made accordingly.
</blockquote></details>

Resolved as per TODO.


<!-- Sent from Reviewable.io -->

2023-04-12 11:54 UTC, wfa-mdharmalingam reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/925)* status: 23 of 24 files reviewed, 2 unresolved discussions (waiting on @SanjayVas and @wfa-siyengar)

___
*[`src/main/terraform/gcloud/kingdom/service_account.tf` line 27 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/925#-NSg8g58EEoyJt-iWRqs:-NSpIjWEE93rsSY7UGnL:bljk55e) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a95864f79fe6b0521769b73a476ee98e2802cff7/src/main/terraform/gcloud/kingdom/service_account.tf#L27)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

As discussed offline, it's the latter `google_spanner_database_iam_binding` resource that appears to be assigning the role for the specific DB. `google_project_iam_member` looks like it's additionally assigning the role at the project level.
</blockquote></details>

We made a change so that access to the Spanner DB is now provided at the database level, rather than the project level, for service accounts.


<!-- Sent from Reviewable.io -->

2023-04-12 18:20 UTC, SanjayVas requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/925)* status: 23 of 24 files reviewed, 2 unresolved discussions (waiting on @wfa-mdharmalingam and @wfa-siyengar)

___
*[`src/main/terraform/gcloud/kingdom/service_account.tf` line 27 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/925#-NSg8g58EEoyJt-iWRqs:-NSqfrCd9O2KI0emMzW6:b-78zz8u) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a95864f79fe6b0521769b73a476ee98e2802cff7/src/main/terraform/gcloud/kingdom/service_account.tf#L27)):*
<details><summary><i>Previously, wfa-mdharmalingam wrote…</i></summary><blockquote>

We made a change so that access to the Spanner DB is now provided at the database level, rather than the project level, for service accounts.
</blockquote></details>

I think you only want the `google_spanner_database_iam_member` and not the `google_spanner_database_iam_binding`. IIUC, the former adds the member alongside existing members. The latter replaces the entire member list.

See https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/spanner_database_iam.html


<!-- Sent from Reviewable.io -->

2023-04-13 04:15 UTC, wfa-hkawalkar reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/925)* status: 23 of 24 files reviewed, 2 unresolved discussions (waiting on @SanjayVas and @wfa-mdharmalingam)

___
*[`src/main/terraform/gcloud/kingdom/service_account.tf` line 21 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/925#-NSg732y6YpzPYQYPpDd:-NSsoi2b4FHCRmNPL-qn:bom7rzv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a95864f79fe6b0521769b73a476ee98e2802cff7/src/main/terraform/gcloud/kingdom/service_account.tf#L21)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

`account_id` is the part that I wanted to be `kingdom-internal`. The resource name should follow the established naming convention, e.g. `kingdom_internal`.
</blockquote></details>

Done. the changes has been made to account_id and the name.


<!-- Sent from Reviewable.io -->

2023-04-13 05:24 UTC, wfa-mdharmalingam reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/925)* status: 23 of 24 files reviewed, 2 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/terraform/gcloud/kingdom/service_account.tf` line 27 at r8](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/925#-NSg8g58EEoyJt-iWRqs:-NSt3RaAEzTgoJbeKHTM:b-32ol45) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a95864f79fe6b0521769b73a476ee98e2802cff7/src/main/terraform/gcloud/kingdom/service_account.tf#L27)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I think you only want the `google_spanner_database_iam_member` and not the `google_spanner_database_iam_binding`. IIUC, the former adds the member alongside existing members. The latter replaces the entire member list.

See https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/spanner_database_iam.html
</blockquote></details>

We removed the "database_iam_binding" as requested. now it only assign the roles.  


<!-- Sent from Reviewable.io -->

2023-04-13 16:23 UTC, SanjayVas requested changes
> Reviewed 1 of 1 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/925)* status: all files reviewed, 1 unresolved discussion (waiting on @wfa-siyengar)

___
*[`src/main/terraform/gcloud/kingdom/service_account.tf` line 46 at r15](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/925#-NSvQ8D41SI3Ia6MLrNi:-NSvQ8D5BxzhAGODeG9L:bpq8f11) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f9ae658250e5e73d4d88a5d86885c55f1dbf555e/src/main/terraform/gcloud/kingdom/service_account.tf#L46)):*
> ```HCL
>   ]
> }
> ```

We need a `kubernetes_service_account` linked to the IAM service account. This corresponds to [Step 5](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/docs/gke/kingdom-deployment.md#step-5-create-k8s-service-account) in the deployment doc.

Feel free to leave a TODO for a followup PR.


<!-- Sent from Reviewable.io -->

2023-04-13 19:36 UTC, wfa-hkawalkar reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/925)* status: 23 of 24 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/terraform/gcloud/kingdom/service_account.tf` line 46 at r15](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/925#-NSvQ8D41SI3Ia6MLrNi:-NSw6awg6CPW1AHs-dvQ:bb3rw2o) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f9ae658250e5e73d4d88a5d86885c55f1dbf555e/src/main/terraform/gcloud/kingdom/service_account.tf#L46)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

The `google_service_account`resource is already declared above. What we need here is a matching `kubernetes_service_account`. See https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/service_account

This K8s service account needs to be bound to the Google IAM service account by an annotation as well as an IAM policy binding as described in the deployment guide.
</blockquote></details>

We have added a Kubernetes service account as requested.


<!-- Sent from Reviewable.io -->

2023-04-13 19:56 UTC, SanjayVas requested changes
> Reviewed 1 of 1 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/925)* status: all files reviewed, 1 unresolved discussion (waiting on @wfa-hkawalkar)

___
*[`src/main/terraform/gcloud/kingdom/service_account.tf` line 46 at r15](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/925#-NSvQ8D41SI3Ia6MLrNi:-NSw1PMz5el8K7f9Y689:bjv3f4p) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f9ae658250e5e73d4d88a5d86885c55f1dbf555e/src/main/terraform/gcloud/kingdom/service_account.tf#L46)):*
<details><summary><i>Previously, wfa-hkawalkar wrote…</i></summary><blockquote>

We have added a Kubernetes service account as requested.
</blockquote></details>

I don't see the binding between the IAM service account and the K8s service account. Again, see [Step 5](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/docs/gke/kingdom-deployment.md#step-5-create-k8s-service-account) in the deployment guide.


<!-- Sent from Reviewable.io -->

2023-04-14 12:06 UTC, wfa-mdharmalingam reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/925)* status: 16 of 24 files reviewed, 1 unresolved discussion (waiting on @bdomen-ggl, @SanjayVas, @wfa-hkawalkar, and @wfa-siyengar)

___
*[`src/main/terraform/gcloud/kingdom/service_account.tf` line 46 at r15](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/925#-NSvQ8D41SI3Ia6MLrNi:-NSzdxpD-baO-DFsUpif:b-k3v3hr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f9ae658250e5e73d4d88a5d86885c55f1dbf555e/src/main/terraform/gcloud/kingdom/service_account.tf#L46)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I don't see the binding between the IAM service account and the K8s service account. Again, see [Step 5](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/docs/gke/kingdom-deployment.md#step-5-create-k8s-service-account) in the deployment guide.
</blockquote></details>

We have added the binding for K8s service 


<!-- Sent from Reviewable.io -->

2023-04-15 09:18 UTC, wfa-siyengar reviewed
> Reviewed 1 of 2 files at r16, 1 of 1 files at r19, 1 of 2 files at r22, 1 of 2 files at r28, 1 of 2 files at r31, 1 of 1 files at r38, 1 of 1 files at r40, 2 of 2 files at r41, 1 of 1 files at r42, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/925)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @wfa-hkawalkar)



<!-- Sent from Reviewable.io -->

2023-04-18 07:13 UTC, wfa-hkawalkar reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/925)* status: 23 of 24 files reviewed, 1 unresolved discussion (waiting on @SanjayVas, @wfa-mdharmalingam, and @wfa-siyengar)

___
*[`src/main/terraform/gcloud/kingdom/service_account.tf` line 46 at r15](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/925#-NSvQ8D41SI3Ia6MLrNi:-NTICGYG0xv0HDnypTM3:bg4n891) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f9ae658250e5e73d4d88a5d86885c55f1dbf555e/src/main/terraform/gcloud/kingdom/service_account.tf#L46)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This is still not correct. I just see a second set of roles for the IAM service account (`google_service_account`) now. What we instead need is the mapping from the K8s service account (`kubernetes_service_account`) to the IAM service account. Again, see the section in the linked guide above.
</blockquote></details>

We have made the changes to K8s service account as per the deployment guide and the terraform registry link.


<!-- Sent from Reviewable.io -->

2023-04-19 18:19 UTC, SanjayVas requested changes
> Reviewed 1 of 1 files at r44, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/925)* status: all files reviewed, 4 unresolved discussions (waiting on @wfa-mdharmalingam and @wfa-siyengar)

___
*[`src/main/terraform/gcloud/duchy/service_account.tf` line 22 at r43](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/925#-NTL_ERU5t8ZWMKqLuzf:-NTPjQPK2vbpx7vFxi5v:b-mthffh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fa9e994fdfc2e0f570991ac88bd51a942beb9928/src/main/terraform/gcloud/duchy/service_account.tf#L22)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Duchies need additional service accounts for Spanner DB and GCS bucket access.

For a whole CMMS you need 7 IAM service accounts, 6 of which are managed by Terraform:
1. The account used by Terraform. I believe this is referenced in variables.tf.
2. The least-privilege cluster service account (I believe you have this as `gke-cluster-sa`)
3. A service account for the Kingdom internal server to grant access to the `kingdom` DB
4. A service account for access to the worker1 Duchy DB
5. A service account for access to the worker2 Duchy DB
6. A service account for access to the aggregator Duchy DB
7. A service account for access to the GCS bucket (there's one shared bucket for all three Duchies)

This means there will be one K8s service account in the Kingdom cluster and two K8s service accounts in each Duchy cluster.
</blockquote></details>

Missing the K8s service accounts and the configurations to allow them to impersonate the IAM service accounts.
___
*[`src/main/terraform/gcloud/duchy/service_account.tf` line 44 at r44](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/925#-NTPiMWEEcev_E2y2N_c:-NTPiMWEEcev_E2y2N_d:b-v7yefh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a71ed3d8d77c1f149bd498bd8a6927c22140f28c/src/main/terraform/gcloud/duchy/service_account.tf#L44)):*
> ```HCL
> # Create the service account for worker1 Duchy DB
> resource "google_service_account" "worker1_db" {
>   account_id   = "worker1-db-sa"
> ```

nit: Don't suffix service account names in "sa". Better would be to match the existing names in the halo-cmm-dev environment



_Suggestion:_
```HCL
worker1-duchy-internal
```
___
*[`src/main/terraform/gcloud/duchy/service_account.tf` line 92 at r44](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/925#-NTPim8Z5iE1h2H30-na:-NTPim8Z5iE1h2H30-nb:b-fcdt9h) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a71ed3d8d77c1f149bd498bd8a6927c22140f28c/src/main/terraform/gcloud/duchy/service_account.tf#L92)):*
> ```HCL
> # Create the service account for GCS bucket access
> resource "google_service_account" "gcs_access" {
>   account_id   = "gcs-access-sa"
> ```

nit: Match names in halo-cmm-dev environment



_Suggestion:_
```HCL
duchy-storage
```
___
*[`src/main/terraform/gcloud/kingdom/service_account.tf` line 46 at r15](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/925#-NSvQ8D41SI3Ia6MLrNi:-NTPj-ZgE5NrVrEllZV9:b-ynpybv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f9ae658250e5e73d4d88a5d86885c55f1dbf555e/src/main/terraform/gcloud/kingdom/service_account.tf#L46)):*
I think you meant to reply to the other comment about Duchy service accounts. This comment is still unresolved as the Kubernetes service account is not configured to impersonate the IAM service account.

> Also we will keep the Kingdom SA for testing,

What testing is this needed for?


<!-- Sent from Reviewable.io -->

2023-04-20 12:35 UTC, wfa-mdharmalingam reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/925)* status: 23 of 24 files reviewed, 4 unresolved discussions (waiting on @SanjayVas and @wfa-siyengar)

___
*[`src/main/terraform/gcloud/duchy/service_account.tf` line 22 at r43](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/925#-NTL_ERU5t8ZWMKqLuzf:-NTTdmFkCSzJ84CtBrlq:b-i158u0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fa9e994fdfc2e0f570991ac88bd51a942beb9928/src/main/terraform/gcloud/duchy/service_account.tf#L22)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Missing the K8s service accounts and the configurations to allow them to impersonate the IAM service accounts.
</blockquote></details>

We have added service accounts for Duchy
___
*[`src/main/terraform/gcloud/kingdom/service_account.tf` line 46 at r15](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/925#-NSvQ8D41SI3Ia6MLrNi:-NTTeC7C9zUDdCy0cYFB:b9e5pta) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f9ae658250e5e73d4d88a5d86885c55f1dbf555e/src/main/terraform/gcloud/kingdom/service_account.tf#L46)):*
> You also have extraneous google_project_iam_member and google_spanner_database_iam_binding resources that need to be removed.

As requested we have removed the above resources.  


<!-- Sent from Reviewable.io -->

2023-04-20 16:06 UTC, SanjayVas requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/925)* status: 23 of 24 files reviewed, 4 unresolved discussions (waiting on @wfa-mdharmalingam and @wfa-siyengar)

___
*[`src/main/terraform/gcloud/kingdom/service_account.tf` line 46 at r15](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/925#-NSvQ8D41SI3Ia6MLrNi:-NTUPSBs7qSMADaRr2MV:b-7ypqb9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f9ae658250e5e73d4d88a5d86885c55f1dbf555e/src/main/terraform/gcloud/kingdom/service_account.tf#L46)):*
<details><summary><i>Previously, wfa-mdharmalingam wrote…</i></summary><blockquote>

> You also have extraneous google_project_iam_member and google_spanner_database_iam_binding resources that need to be removed.

As requested we have removed the above resources.  
</blockquote></details>

This is still not correct. What we need is the K8s service account to be able to impersonate the IAM service account.


<!-- Sent from Reviewable.io -->

2023-04-20 17:48 UTC, wfa-mdharmalingam reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/925)* status: 23 of 24 files reviewed, 4 unresolved discussions (waiting on @SanjayVas and @wfa-siyengar)

___
*[`src/main/terraform/gcloud/kingdom/service_account.tf` line 46 at r15](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/925#-NSvQ8D41SI3Ia6MLrNi:-NTUlnai2ksXUjOS9Qen:bwt563y) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/f9ae658250e5e73d4d88a5d86885c55f1dbf555e/src/main/terraform/gcloud/kingdom/service_account.tf#L46)):*
> Grant the K8s service account permissions to impersonate the IAM service account. It corresponds to the following sample command from the guide:

We have added a new SA for this. 


<!-- Sent from Reviewable.io -->

2023-05-03 23:31 UTC, closed without merging