Add ForwardedStorageCorrectnessTest.
world-federation-of-advertisers/cross-media-measurement pull request #936
Opened 2023-04-07 21:32 UTC by SanjayVas

This allows running the K8s correctness test against a running CMMS instance, with the following conditions:
* The instance uses the testing certificates/keys from the codebase.
* The EDP simulator sketches are accessible via a server which implements the ForwardedStorage service.

2023-04-07 21:32 UTC, wfa-reviewable commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/936)
<!-- Reviewable:end -->

2023-04-07 21:32 UTC, SanjayVas commented
Depends on #923.

2023-04-14 15:51 UTC, tristanvuong2021 requested changes
> Reviewed 7 of 8 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/936)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/k8s/local/README.md` line 282 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/936#-NT-SH8C8doir8PC3GWa:-NT-SH8C8doir8PC3GWb:brfffkp) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e95c83fc7a2b54f8bc0eab607a3ac118d8264ac8/src/main/k8s/local/README.md#L282)):*
> ```Markdown
> 
> ```shell
> bazel test //src/test/kotlin/org/wfanet/measurement/integration/k8s:ForwardedStorageCorrectnessTest
> ```

This test needs a longer timeout. I hit the timeout at 8 minutes. The time taken for the correctness test has always varied. 8 minutes is enough sometimes, but not all the time.


<!-- Sent from Reviewable.io -->

2023-04-17 15:44 UTC, SanjayVas reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/936)* status: all files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)

___
*[`src/main/k8s/local/README.md` line 282 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/936#-NT-SH8C8doir8PC3GWa:-NTErcA_6cUEmQGZDSNL:bjbhhg8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e95c83fc7a2b54f8bc0eab607a3ac118d8264ac8/src/main/k8s/local/README.md#L282)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

This test needs a longer timeout. I hit the timeout at 8 minutes. The time taken for the correctness test has always varied. 8 minutes is enough sometimes, but not all the time.
</blockquote></details>

I've yet to see it hit the timeout when something else hadn't gone wrong, i.e. where increasing the timeout would get the test to pass. These timeouts are enough for even the GitHub Actions runner, which is quite slow. The entire test tends to complete in <5 min on my workstation.

What's the rough ratio of timeout failures vs. passes you're getting?


<!-- Sent from Reviewable.io -->

2023-04-18 14:05 UTC, YuhongWang-Amazon approved these changes
> Reviewed 7 of 8 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/936)* status: all files reviewed, 2 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

___
*[`src/main/k8s/local/README.md` line 287 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/936#-NTJf94I-MB9gNAuscg6:-NTJf94I-MB9gNAuscg7:bpha70r) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e95c83fc7a2b54f8bc0eab607a3ac118d8264ac8/src/main/k8s/local/README.md#L287)):*
> ```Markdown
>   --define=forwarded_storage_api_target=localhost:7443 \
>   --define=mc_name=measurementConsumers/Rcn7fKd25C8 \
>   --define=mc_api_key=W9q4zad246g
> ```

The `mc_name` and `mc_api_key` seem to be randomly generated. Are there any instructions on how to retrieve it from the existing CMMS 


<!-- Sent from Reviewable.io -->

2023-04-18 18:47 UTC, tristanvuong2021 requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/936)* status: all files reviewed, 2 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/k8s/local/README.md` line 282 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/936#-NT-SH8C8doir8PC3GWa:-NTKg9eA-4nrc70kzpVZ:b-cdzk7p) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e95c83fc7a2b54f8bc0eab607a3ac118d8264ac8/src/main/k8s/local/README.md#L282)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I've yet to see it hit the timeout when something else hadn't gone wrong, i.e. where increasing the timeout would get the test to pass. These timeouts are enough for even the GitHub Actions runner, which is quite slow. The entire test tends to complete in <5 min on my workstation.

What's the rough ratio of timeout failures vs. passes you're getting?
</blockquote></details>

It was failing consistently for me with the 480s timeout. I increased the timeout and it passed in 540.1s.


<!-- Sent from Reviewable.io -->

2023-04-19 17:54 UTC, tristanvuong2021 reviewed
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/936)* status: all files reviewed, 2 unresolved discussions (waiting on @SanjayVas)



<!-- Sent from Reviewable.io -->

2023-04-19 22:02 UTC, SanjayVas reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/936)* status: 10 of 11 files reviewed, 2 unresolved discussions (waiting on @tristanvuong2021 and @YuhongWang-Amazon)

___
*[`src/main/k8s/local/README.md` line 282 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/936#-NT-SH8C8doir8PC3GWa:-NTQW8JV1dy3Xw5SCw-W:bnrmskt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e95c83fc7a2b54f8bc0eab607a3ac118d8264ac8/src/main/k8s/local/README.md#L282)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

It was failing consistently for me with the 480s timeout. I increased the timeout and it passed in 540.1s.
</blockquote></details>

Very surprising given that 8 mins is fine on GHA. Regardless, I went ahead and bumped the timeout.
___
*[`src/main/k8s/local/README.md` line 287 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/936#-NTJf94I-MB9gNAuscg6:-NTQWSZMAvaCE0F6C2o-:b-pzjd05) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/e95c83fc7a2b54f8bc0eab607a3ac118d8264ac8/src/main/k8s/local/README.md#L287)):*
<details><summary><i>Previously, YuhongWang-Amazon wrote…</i></summary><blockquote>

The `mc_name` and `mc_api_key` seem to be randomly generated. Are there any instructions on how to retrieve it from the existing CMMS 
</blockquote></details>

The values come from ResourceSetup. You need to record those values and save them for the life of a Kingdom DB.

Technically you can figure them out by either having access to gRPC request/response logs from when the resources were created or read them directly from the Kingdom DB (and then encode them since the DB stores them as 64-bit integers), but that's not the expected usage.


<!-- Sent from Reviewable.io -->

2023-04-19 22:21 UTC, tristanvuong2021 approved these changes
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/936)* status: all files reviewed, 1 unresolved discussion (waiting on @YuhongWang-Amazon)



<!-- Sent from Reviewable.io -->

2023-04-19 22:26 UTC, YuhongWang-Amazon approved these changes
> Reviewed 2 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/936)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @SanjayVas)



<!-- Sent from Reviewable.io -->

2023-04-19 22:39 UTC, merged