Implement Internal Reporting V2 Reporting Sets Service Create Method
world-federation-of-advertisers/cross-media-measurement pull request #937
Opened 2023-04-10 19:08 UTC by tristanvuong2021

2023-04-10 19:08 UTC, wfa-reviewable commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/937)
<!-- Reviewable:end -->

2023-04-11 15:35 UTC, tristanvuong2021 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/937)* status: 5 of 29 files reviewed, 7 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/ReportingSetReader.kt` line 23 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/937#-NSh2zAJ98RW4qMFU1mm:-NSkxEUn6DZqYKb_nuGN:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b171a9afe8779ecefed9b74293aef738bb266748/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/ReportingSetReader.kt#L23)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Maybe `PrimaryKey` and `readPrimaryKey`?
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/ReportingSetReader.kt` line 29 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/937#-NSgzC8T1gOjLUWxaaqF:-NSkxF665Sa7fXKqJZKm:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b171a9afe8779ecefed9b74293aef738bb266748/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/ReportingSetReader.kt#L29)):*
> ```Kotlin
> 
>   suspend fun readId(
>     measurementConsumerId: Long,
> ```

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/ReportingSetReader.kt` line 30 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/937#-NSgzES-1GSRmxG49BaM:-NSkxFM572KF55_4mBRK:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b171a9afe8779ecefed9b74293aef738bb266748/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/ReportingSetReader.kt#L30)):*
> ```Kotlin
>   suspend fun readId(
>     measurementConsumerId: Long,
>     externalReportingSetId: Long,
> ```

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateMeasurementConsumer.kt` line 22 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/937#-NSh-AEr6qzyfjfJp9kR:-NSkxGLe4ngRUxcxZQCU:bdg753o) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b171a9afe8779ecefed9b74293aef738bb266748/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateMeasurementConsumer.kt#L22)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Do we use this just to populate the DB from the config file on startup?
</blockquote></details>

That is the plan.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateMeasurementConsumer.kt` line 32 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/937#-NSgzzJQ-wUQo76K2G34:-NSkxJFU3Oo33r52Pd3k:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b171a9afe8779ecefed9b74293aef738bb266748/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateMeasurementConsumer.kt#L32)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Should result in an ALREADY_EXISTS error. The only time we get idempotent behavior should be when we use a request ID.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateReportingSet.kt` line 75 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/937#-NSh0LPf8vVu7JMuIqwA:-NSkxJzT3-3iq800RzSb:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b171a9afe8779ecefed9b74293aef738bb266748/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateReportingSet.kt#L75)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Use an exhaustive `when`.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateReportingSet.kt` line 105 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/937#-NShAnol9SG_TTPNfdK0:-NSkxKEk002XaVUVYMgT:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b171a9afe8779ecefed9b74293aef738bb266748/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateReportingSet.kt#L105)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Rather than building a collection of binding lambdas, why not extract a function for the body of the loop that takes in the BoundStatement.Builders? The builder API wasn't really meant to be used this way. I believe it just means that all of your `xxBinders.add` calls become `xxInsertBuilder.addBinding`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-04-11 18:08 UTC, SanjayVas requested changes
> Reviewed 2 of 25 files at r1, 6 of 14 files at r3, 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/937)* status: 15 of 29 files reviewed, 4 unresolved discussions (waiting on @tristanvuong2021)

___
*[`src/main/resources/reporting/postgres/create-v2-reporting-schema.sql` line 62 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/937#-NSlT2C4EgfbXDe_vNZ1:-NSlT2C4EgfbXDe_vNZ2:b-f3tfrq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c6b6ca7e009bc684750759b12679b2647cbe49f7/src/main/resources/reporting/postgres/create-v2-reporting-schema.sql#L62)):*
> ```TSQL
> );
> 
> -- changeset riemanli:create-reporting-sets-table dbms:postgresql
> ```

Normally Liquibase changesets must be immutable (including comments), but it appears that this is safe as it wasn't referenced by any changelog file until this PR.
___
*[`src/main/resources/reporting/postgres/create-v2-reporting-schema.sql` line 173 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/937#-NSlTbZ7BVz_jsrg_CUX:-NSlTbZ7BVz_jsrg_CUY:bfyzpka) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c6b6ca7e009bc684750759b12679b2647cbe49f7/src/main/resources/reporting/postgres/create-v2-reporting-schema.sql#L173)):*
> ```TSQL
> CREATE TABLE SetExpressions (
>   MeasurementConsumerId bigint NOT NULL,
>   ReportingSetId bigint NOT NULL,
> ```

I thought that a SetExpressions row can belong to more than one ReportingSets row, and furthermore that there is not necessarily a single root for each expression. @riemanli 

e.g.  You could have one ReportingSet that references `A` in the tree of SetExpressions below, and another that references `D`.

```mermaid
flowchart TD
    A --> B
    A --> C
    D --> A
    D --> F
```
___
*[`src/main/resources/reporting/postgres/create-v2-reporting-schema.sql` line 183 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/937#-NSlTQDU1MIykH0xBE2J:-NSlTQDU1MIykH0xBE2K:bb7phvt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c6b6ca7e009bc684750759b12679b2647cbe49f7/src/main/resources/reporting/postgres/create-v2-reporting-schema.sql#L183)):*
> ```TSQL
> 
>   -- The left-hand-side (lhs) operand in a binary set expression. Exactly
>   -- one lhs field   1has to be non-NULL.
> ```

typo



_Suggestion:_
```TSQL
lhs field has
```


<!-- Sent from Reviewable.io -->

2023-04-11 18:10 UTC, SanjayVas requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/937)* status: 15 of 29 files reviewed, 4 unresolved discussions (waiting on @tristanvuong2021)

___
*[`src/main/resources/reporting/postgres/create-v2-reporting-schema.sql` line 173 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/937#-NSlTbZ7BVz_jsrg_CUX:-NSlVlxC0S0w6adlODG9:b-otgiqa) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c6b6ca7e009bc684750759b12679b2647cbe49f7/src/main/resources/reporting/postgres/create-v2-reporting-schema.sql#L173)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I thought that a SetExpressions row can belong to more than one ReportingSets row, and furthermore that there is not necessarily a single root for each expression. @riemanli 

e.g.  You could have one ReportingSet that references `A` in the tree of SetExpressions below, and another that references `D`.

```mermaid
flowchart TD
    A --> B
    A --> C
    D --> A
    D --> F
```

</blockquote></details>

Image of generated diagram for convenience:

![image.png](https://files.reviewableusercontent.io/images/reviewable/1747892/vtqJHR6MqCOIY1ukV8aEaXcL/image.png)


<!-- Sent from Reviewable.io -->

2023-04-11 18:33 UTC, tristanvuong2021 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/937)* status: 15 of 29 files reviewed, 4 unresolved discussions (waiting on @riemanli and @SanjayVas)

___
*[`src/main/resources/reporting/postgres/create-v2-reporting-schema.sql` line 173 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/937#-NSlTbZ7BVz_jsrg_CUX:-NSl_jR19mUT77I3n_Zv:b-a62nsv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c6b6ca7e009bc684750759b12679b2647cbe49f7/src/main/resources/reporting/postgres/create-v2-reporting-schema.sql#L173)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Image of generated diagram for convenience:

![image.png](https://files.reviewableusercontent.io/images/reviewable/1747892/vtqJHR6MqCOIY1ukV8aEaXcL/image.png)

</blockquote></details>

I was deciding between this and a third table, ReportingSetSetExpressions. If this is the case, I will make a 3rd table.


<!-- Sent from Reviewable.io -->

2023-04-11 18:40 UTC, tristanvuong2021 commented
*[`src/main/resources/reporting/postgres/create-v2-reporting-schema.sql` line 173 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/937#-NSlTbZ7BVz_jsrg_CUX:-NSlbWIY6c3GI7fNNICn:b4nzw4j) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c6b6ca7e009bc684750759b12679b2647cbe49f7/src/main/resources/reporting/postgres/create-v2-reporting-schema.sql#L173)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

I was deciding between this and a third table, ReportingSetSetExpressions. If this is the case, I will make a 3rd table.
</blockquote></details>

Alternatively, I could leave it the way it was before, but add the foreign key constraint to ReportingSets after both ReportingSets and SetExpressions are created.


<!-- Sent from Reviewable.io -->

2023-04-11 20:25 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/937)* status: 6 of 29 files reviewed, 4 unresolved discussions (waiting on @SanjayVas)

___
*[`src/main/resources/reporting/postgres/create-v2-reporting-schema.sql` line 173 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/937#-NSlTbZ7BVz_jsrg_CUX:-NSlv9-DDykhdrARCQaq:bm7q2cw) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c6b6ca7e009bc684750759b12679b2647cbe49f7/src/main/resources/reporting/postgres/create-v2-reporting-schema.sql#L173)):*
> I thought that a SetExpressions row can belong to more than one ReportingSets row, and furthermore that there is not necessarily a single root for each expression. @riemanli
> e.g.  You could have one ReportingSet that references A in the tree of SetExpressions below, and another that references D.

Trying to understand the issue here, but my thought is that SetExpressions are not resources, so they can't be referenced directly. From the user's point of view, a set expression can be reused in different reporting sets only by referencing its composite reporting set. So all the nodes in the generated diagram above are ReportingSets.

That being said, I am not sure if a SetExpressions row needs to be referenced by multiple ReportingSets rows.


<!-- Sent from Reviewable.io -->

2023-04-11 21:27 UTC, SanjayVas requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/937)* status: 6 of 29 files reviewed, 4 unresolved discussions (waiting on @riemanli and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateReportingSet.kt` line 105 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/937#-NShAnol9SG_TTPNfdK0:-NSmCO0a4FVwKynpBmJH:bjyze3z) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b171a9afe8779ecefed9b74293aef738bb266748/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateReportingSet.kt#L105)):*
<details><summary><i>Previously, tristanvuong2021 (Tristan Vuong) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

This isn't really what I meant. You intentionally cannot create a new builder directly. Instead, you need to call the method that takes in a builder from within the `boundStatement` lambda.


<!-- Sent from Reviewable.io -->

2023-04-13 06:03 UTC, riemanli reviewed
> Reviewed 4 of 25 files at r1, 7 of 14 files at r3, 1 of 1 files at r5, 1 of 1 files at r6, 1 of 1 files at r7, 14 of 14 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/937)* status: all files reviewed, 6 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateReportingSet.kt` line 89 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/937#-NSt2WKXBmLr3UxWhn11:-NSt2WKXBmLr3UxWhn12:b-6sayr8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fa4b450bcaa40a2954a2e2aaf7cadde75338b344/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateReportingSet.kt#L89)):*
> ```Kotlin
>             }
>           })
>         )
> ```

I remember you mentioned that we don't need to store primitive reporting set basis for primitive reporting set. Is that still the case?
I am not against what you're doing here. In fact, I think doing this way is conservative and good IMO. Just want to see if your thought has changed since last time we talked.



_Code quote:_
```Kotlin
        insertWeightedSubsetUnions(
          measurementConsumerId,
          reportingSetId,
          listOf(ReportingSetKt.weightedSubsetUnion {
            weight = 1
            primitiveReportingSetBases += ReportingSetKt.primitiveReportingSetBasis {
              this.externalReportingSetId = externalReportingSetId.value
              filters += reportingSet.filter
            }
          })
        )
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateReportingSet.kt` line 218 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/937#-NSt6Iib6kzCAIa052rk:-NSt6Iic8IC9tXHI9fJD:b-eqwuz9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fa4b450bcaa40a2954a2e2aaf7cadde75338b344/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateReportingSet.kt#L218)):*
> ```Kotlin
>         leftHandSetExpressionId = null
>         leftHandReportingSetId = null
>       }
> ```

There must be one field set for `lhs`. There will be a check in the service implementation, but I wonder if we should raise an error here as well. WDYT?



_Code quote:_
```Kotlin
      SetExpression.Operand.OperandCase.OPERAND_NOT_SET -> {
        leftHandSetExpressionId = null
        leftHandReportingSetId = null
      }
```


<!-- Sent from Reviewable.io -->

2023-04-17 04:34 UTC, riemanli requested changes
> Reviewed 7 of 11 files at r12, 57 of 57 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/937)* status: all files reviewed, 7 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateReportingSet.kt` line 210 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/937#-NTCNsQ3Dk0-XiBP7RXo:-NTCNsQ3Dk0-XiBP7RXp:b-5iq8o1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/10863a27c2e7defc23c96e062601135d3bc4a4dc/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateReportingSet.kt#L210)):*
> ```Kotlin
>   private fun createExternalReportingSetIdsSet(reportingSet: ReportingSet): Set<Long> {
>     val externalReportingIds = mutableSetOf<Long>()
>     reportingSet.composite.getExternalReportingSetIds()
> ```

Should this be

``` Kotlin
externalReportingIds.addAll( reportingSet.composite.getExternalReportingSetIds() )
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/v2/ReportingSetsServiceTest.kt` line 83 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/937#-NTCQw1WBArJLwGTXAiJ:-NTCQw1WBArJLwGTXAiK:b-c4jtzc) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/10863a27c2e7defc23c96e062601135d3bc4a4dc/src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/v2/ReportingSetsServiceTest.kt#L83)):*
> ```Kotlin
>               cmmsDataProviderId = "1235"
>               cmmsEventGroupId = "1236"
>             }
> ```

This one is same as the one below. Is that on purpose?



_Code quote:_
```Kotlin
          eventGroupKeys +=
            ReportingSetKt.PrimitiveKt.eventGroupKey {
              cmmsMeasurementConsumerId = CMMS_MEASUREMENT_CONSUMER_ID
              cmmsDataProviderId = "1235"
              cmmsEventGroupId = "1236"
            }
```


<!-- Sent from Reviewable.io -->

2023-04-17 17:43 UTC, tristanvuong2021 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/937)* status: 80 of 82 files reviewed, 7 unresolved discussions (waiting on @riemanli and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateReportingSet.kt` line 105 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/937#-NShAnol9SG_TTPNfdK0:-NTF1wIh26emfowRfNE4:boy25yl) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b171a9afe8779ecefed9b74293aef738bb266748/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateReportingSet.kt#L105)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This isn't really what I meant. You intentionally cannot create a new builder directly. Instead, you need to call the method that takes in a builder from within the `boundStatement` lambda.
</blockquote></details>

Decided to go back to a list of binders. Couldn't figure out how to do it all from boundStatement without doing a similar thing.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateReportingSet.kt` line 89 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/937#-NSt2WKXBmLr3UxWhn11:-NTFEQuK3YE-YBN-BEIX:bpyjoeu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fa4b450bcaa40a2954a2e2aaf7cadde75338b344/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateReportingSet.kt#L89)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

I remember you mentioned that we don't need to store primitive reporting set basis for primitive reporting set. Is that still the case?
I am not against what you're doing here. In fact, I think doing this way is conservative and good IMO. Just want to see if your thought has changed since last time we talked.
</blockquote></details>

After working on implementing the read methods, I will just generate it instead of store it. Not storing doesn't make reading it back harder.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateReportingSet.kt` line 218 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/937#-NSt6Iib6kzCAIa052rk:-NTFDP2X69dVJmQz3QxB:brp6r14) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fa4b450bcaa40a2954a2e2aaf7cadde75338b344/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateReportingSet.kt#L218)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

There must be one field set for `lhs`. There will be a check in the service implementation, but I wonder if we should raise an error here as well. WDYT?
</blockquote></details>

I added a check for it anyways, although it doesn't go here.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateReportingSet.kt` line 210 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/937#-NTCNsQ3Dk0-XiBP7RXo:-NTF24dD4uv-vch__hL_:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/10863a27c2e7defc23c96e062601135d3bc4a4dc/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateReportingSet.kt#L210)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Should this be

``` Kotlin
externalReportingIds.addAll( reportingSet.composite.getExternalReportingSetIds() )
```
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/v2/ReportingSetsServiceTest.kt` line 83 at r13](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/937#-NTCQw1WBArJLwGTXAiJ:-NTFJ9WF8E3QppFbXR7X:b-hwxz47) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/10863a27c2e7defc23c96e062601135d3bc4a4dc/src/main/kotlin/org/wfanet/measurement/reporting/service/internal/testing/v2/ReportingSetsServiceTest.kt#L83)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

This one is same as the one below. Is that on purpose?
</blockquote></details>

It was on purpose, but I moved it to its own test to make it more clear
___
*[`src/main/resources/reporting/postgres/create-v2-reporting-schema.sql` line 173 at r5](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/937#-NSlTbZ7BVz_jsrg_CUX:-NTFEBfJDgOLfZV-9dE6:bwpbkvu) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c6b6ca7e009bc684750759b12679b2647cbe49f7/src/main/resources/reporting/postgres/create-v2-reporting-schema.sql#L173)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

> I thought that a SetExpressions row can belong to more than one ReportingSets row, and furthermore that there is not necessarily a single root for each expression. @riemanli
> e.g.  You could have one ReportingSet that references A in the tree of SetExpressions below, and another that references D.

Trying to understand the issue here, but my thought is that SetExpressions are not resources, so they can't be referenced directly. From the user's point of view, a set expression can be reused in different reporting sets only by referencing its composite reporting set. So all the nodes in the generated diagram above are ReportingSets.

That being said, I am not sure if a SetExpressions row needs to be referenced by multiple ReportingSets rows.
</blockquote></details>

I ended up keeping the original design and adding the foreign key constraint later. See https://github.com/world-federation-of-advertisers/cross-media-measurement/pull/940


<!-- Sent from Reviewable.io -->

2023-04-17 21:48 UTC, riemanli approved these changes
> Reviewed 1 of 2 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/937)* status: 81 of 82 files reviewed, 3 unresolved discussions (waiting on @SanjayVas)



<!-- Sent from Reviewable.io -->

2023-04-18 22:35 UTC, tristanvuong2021 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/937)* status: 74 of 82 files reviewed, 11 unresolved discussions (waiting on @riemanli and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/EventGroupReader.kt` line 34 at r14](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/937#-NTGVtPA4NYel0ND2Lmy:-NTLHtviBo3KLW0gTSlq:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/65826632cbfd617036e72655bc9260e25c6f0bd0/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/EventGroupReader.kt#L34)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Rename to avoid plural. This is really a CMMS EventGroup key.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/EventGroupReader.kt` line 59 at r14](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/937#-NTGQ7To1UbbIRshTiHz:-NTLHuco-SUvEuJiuRYj:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/65826632cbfd617036e72655bc9260e25c6f0bd0/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/EventGroupReader.kt#L59)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

It looks like you don't use the random-access properties of List, so use a more general type.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/ReportingSetReader.kt` line 36 at r14](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/937#-NTGHFMn0-QDSQb46b4u:-NTLI8qY30_aouLqIXfx:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/65826632cbfd617036e72655bc9260e25c6f0bd0/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/readers/ReportingSetReader.kt#L36)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Use specific types for as long as possible, converting only to primitives at the last possible point.

`BoundStatement.Binder` has a `bind` overload for `ExternalId`
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateReportingSet.kt` line 105 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/937#-NShAnol9SG_TTPNfdK0:-NTLMPE45gZeijVVY_Nm:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b171a9afe8779ecefed9b74293aef738bb266748/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateReportingSet.kt#L105)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Just don't try to generate the bindings for all the event groups and the reporting sets in the same loop.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateReportingSet.kt` line 97 at r14](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/937#-NTG_HxX5BV0LXYBf5xg:-NTLNKHc5s1Ms2RVRx5m:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/65826632cbfd617036e72655bc9260e25c6f0bd0/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateReportingSet.kt#L97)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This condition looks like it can be determined purely from the request. This should be pre-checked in the service layer. If you want to check it in the Reader, throw an IllegalArgumentException from the constructor.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateReportingSet.kt` line 124 at r14](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/937#-NTG_WMz5zwo4EyLOB6N:-NTLNKte997PFfWCAy_o:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/65826632cbfd617036e72655bc9260e25c6f0bd0/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateReportingSet.kt#L124)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Ditto
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateReportingSet.kt` line 150 at r14](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/937#-NTGWo6r4oseb-bwK6Xk:-NTLNHWZ7D4mTPhUIsDP:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/65826632cbfd617036e72655bc9260e25c6f0bd0/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateReportingSet.kt#L150)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Avoid having a reference to the mutable state by using transformation operators.

```kotlin
val eventGroupCmmsKeys: List<EventGroupReader.CmmsKey> = eventGroups.distinct().map { it.toCmmsKey() }
```
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateReportingSet.kt` line 227 at r14](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/937#-NTGZdtf7ElbDzzE2qp0:-NTLJR7s33xSQYmTg0Rc:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/65826632cbfd617036e72655bc9260e25c6f0bd0/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateReportingSet.kt#L227)):*
> ```Kotlin
>   }
> 
>   private fun createExternalReportingSetIdsSet(reportingSet: ReportingSet): Set<Long> {
> ```

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateReportingSet.kt` line 236 at r14](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/937#-NTGZGdADFGyDMixLwNa:-NTLItNz0VR-lUZR51T9:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/65826632cbfd617036e72655bc9260e25c6f0bd0/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateReportingSet.kt#L236)):*
> ```Kotlin
>   }
> 
>   private fun SetExpression.getExternalReportingSetIds(): Set<Long> {
> ```

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateReportingSet.kt` line 264 at r14](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/937#-NTGZK3u78cquirjGUP6:-NTLIt8U-FGsI-UiNHi-:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/65826632cbfd617036e72655bc9260e25c6f0bd0/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateReportingSet.kt#L264)):*
> ```Kotlin
>   }
> 
>   private fun WeightedSubsetUnion.getExternalReportingSetIds(): Set<Long> {
> ```

Done.


<!-- Sent from Reviewable.io -->

2023-04-19 21:32 UTC, SanjayVas requested changes
> Reviewed 1 of 14 files at r3, 1 of 1 files at r7, 11 of 14 files at r8, 2 of 11 files at r12, 57 of 57 files at r13, 7 of 8 files at r15, 2 of 2 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/937)* status: all files reviewed, 6 unresolved discussions (waiting on @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/PostgresReportingSetsService.kt` line 46 at r16](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/937#-NTQOMAW8kE7Rs__sUUP:-NTQOMAW8kE7Rs__sUUQ:b47o08c) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8e0c72ea6ec2038939d02df04320607ab172dbf7/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/PostgresReportingSetsService.kt#L46)):*
> ```Kotlin
>             ReportingSet.SetExpression.Operand.OperandCase.OPERAND_NOT_SET
>         ) {
>           failGrpc(Status.INVALID_ARGUMENT) { "Reporting Set invalid" }
> ```

nit: be more specific since we know more here



_Suggestion:_
```Kotlin
"lhs operand not specified"
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateReportingSet.kt` line 133 at r16](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/937#-NTQOpME6_GX7NE4gI7O:-NTQOpME6_GX7NE4gI7P:bff9hpj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8e0c72ea6ec2038939d02df04320607ab172dbf7/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateReportingSet.kt#L133)):*
> ```Kotlin
>       }
>       ReportingSet.ValueCase.VALUE_NOT_SET -> {
>         // Already checked in the service that calls this.
> ```

nit: You can throw an IllegalArgumentException here since it indicates a programming error
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateReportingSet.kt` line 170 at r16](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/937#-NTQP4zkAcdPl_DmVkKZ:-NTQP4zkAcdPl_DmVkK_:bsxj72v) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8e0c72ea6ec2038939d02df04320607ab172dbf7/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateReportingSet.kt#L170)):*
> ```Kotlin
> 
>     EventGroupReader(transactionContext)
>       .getByCmmsEventGroupKey(cmmsEventGroupKeys.toList())
> ```

Since the param type is now `Collection`, you shouldn't need to call `toList()`



_Code quote:_
```Kotlin
.toList()
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateReportingSet.kt` line 260 at r16](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/937#-NTQQHoA97Tbwi6BFoHX:-NTQQHoA97Tbwi6BFoHY:b-mhf6a5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8e0c72ea6ec2038939d02df04320607ab172dbf7/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateReportingSet.kt#L260)):*
> ```Kotlin
>     when (source.lhs.operandCase) {
>       SetExpression.Operand.OperandCase.EXPRESSION -> {
>         source.lhs.expression.getExternalReportingSetIds()
> ```

Shouldn't this also be adding to the collection rather than just being an expression where the return value is unused?



_Code quote:_
```Kotlin
source.lhs.expression.getExternalReportingSetIds()
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateReportingSet.kt` line 271 at r16](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/937#-NTQQQGiED3WF04Ehf1E:-NTQQQGiED3WF04Ehf1F:brhumzt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/8e0c72ea6ec2038939d02df04320607ab172dbf7/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateReportingSet.kt#L271)):*
> ```Kotlin
>     when (this.rhs.operandCase) {
>       SetExpression.Operand.OperandCase.EXPRESSION -> {
>         source.rhs.expression.getExternalReportingSetIds()
> ```

Same here.



_Code quote:_
```Kotlin
source.rhs.expression.getExternalReportingSetIds()
```


<!-- Sent from Reviewable.io -->

2023-04-19 23:45 UTC, tristanvuong2021 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/937)* status: 78 of 83 files reviewed, 4 unresolved discussions (waiting on @riemanli and @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateReportingSet.kt` line 170 at r16](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/937#-NTQP4zkAcdPl_DmVkKZ:-NTQuEkW-7BZ1fG3rOYH:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b9f503a405bd2f425d487dd138cf5d6eaeec85c5/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateReportingSet.kt#L170)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Since the param type is now `Collection`, you shouldn't need to call `toList()`
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateReportingSet.kt` line 260 at r16](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/937#-NTQQHoA97Tbwi6BFoHX:-NTQuF7ODMt1818z_RxP:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b9f503a405bd2f425d487dd138cf5d6eaeec85c5/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateReportingSet.kt#L260)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Shouldn't this also be adding to the collection rather than just being an expression where the return value is unused?
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateReportingSet.kt` line 271 at r16](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/937#-NTQQQGiED3WF04Ehf1E:-NTQuFP5ABU9RHiAIepB:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/b9f503a405bd2f425d487dd138cf5d6eaeec85c5/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateReportingSet.kt#L271)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Same here.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-04-19 23:49 UTC, SanjayVas requested changes
> Reviewed 5 of 5 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/937)* status: all files reviewed, 1 unresolved discussion (waiting on @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateReportingSet.kt` line 225 at r17](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/937#-NTQudrmA7-gpJU3iYQs:-NTQudrmA7-gpJU3iYQt:b-yvjrmt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0ffecb92c7dadc2434b069ef87b3200cf5650bec/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateReportingSet.kt#L225)):*
> ```Kotlin
>       ) {
>         cmmsEventGroupKeys.forEach {
>           val eventGroupId: InternalId? =
> ```

Shouldn't this be non-null now? (Can use `Map.getValue`)



_Suggestion:_
```Kotlin
InternalId
```


<!-- Sent from Reviewable.io -->

2023-04-20 00:45 UTC, tristanvuong2021 reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/937)* status: 82 of 83 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateReportingSet.kt` line 225 at r17](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/937#-NTQudrmA7-gpJU3iYQs:-NTR6m_X512tZGp0Qlqk:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/0ffecb92c7dadc2434b069ef87b3200cf5650bec/src/main/kotlin/org/wfanet/measurement/reporting/deploy/v2/postgres/writers/CreateReportingSet.kt#L225)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Shouldn't this be non-null now? (Can use `Map.getValue`)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-04-20 01:13 UTC, riemanli reviewed
> Reviewed 7 of 8 files at r15, 2 of 2 files at r16, 4 of 5 files at r17, 1 of 1 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/937)* status: all files reviewed, 1 unresolved discussion (waiting on @SanjayVas)



<!-- Sent from Reviewable.io -->

2023-04-20 16:36 UTC, SanjayVas approved these changes
> Reviewed 1 of 1 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/937)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)



<!-- Sent from Reviewable.io -->

2023-04-21 15:52 UTC, stevenwarejones approved these changes
> Reviewed 2 of 25 files at r1, 1 of 14 files at r3, 1 of 1 files at r7, 5 of 14 files at r8, 2 of 11 files at r12, 47 of 57 files at r13, 3 of 8 files at r15, 3 of 5 files at r17, 1 of 1 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/937)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)



<!-- Sent from Reviewable.io -->

2023-04-21 16:59 UTC, merged