v2alpha metrics service -- ListMetrics
world-federation-of-advertisers/cross-media-measurement pull request #951
Opened 2023-04-17 00:27 UTC by riemanli

2023-04-17 00:27 UTC, wfa-reviewable commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/951)
<!-- Reviewable:end -->

2023-04-18 00:27 UTC, SanjayVas requested changes
> Reviewed 1 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/951)* status: 1 of 5 files reviewed, 6 unresolved discussions (waiting on @riemanli and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 601 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/951#-NTGcbDIEMuYx3GHpQ4c:-NTGcbDIEMuYx3GHpQ4d:bbe9pp1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fdadc158497ca49432e68bad5a43898a1aa14ba7/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L601)):*
> ```Kotlin
>         when (newState) {
>           Measurement.State.SUCCEEDED -> {
>             if (measurementsList.isEmpty()) continue
> ```

Is this case possible given that you're using `groupBy`? I believe you'll only get a map entry if there's at least one measurement with that state.



_Code quote:_
```Kotlin
measurementsList.isEmpty()
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 642 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/951#-NTGbw_z3dldwXEK_NHz:-NTGbwa-0Zgtin49z9Nx:b-u5y8so) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fdadc158497ca49432e68bad5a43898a1aa14ba7/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L642)):*
> ```Kotlin
>           .measurementsList
> 
>       if (internalMeasurementsList.size < failedMeasurementsList.size) {
> ```

Batch methods must be atomic, i.e. all or nothing. Therefore this will never be true.



_Code quote:_
```Kotlin
if (internalMeasurementsList.size < failedMeasurementsList.size) {
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 715 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/951#-NTGaPXh9Mc_qHQHM0Hl:-NTGaPXh9Mc_qHQHM0Hm:bylqfzs) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fdadc158497ca49432e68bad5a43898a1aa14ba7/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L715)):*
> ```Kotlin
> 
>     /** Gets a map of [Measurement.State] to a list of [Measurement]s. */
>     private suspend fun getCmmsMeasurementsByState(
> ```

nit: just return the list and do the grouping at the single call site. The method name makes it look like this is querying with a state predicate rather than grouping the result by state, which can be done trivially after the RPC.



_Code quote:_
```Kotlin
ByState
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 758 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/951#-NTGe0ElAwNqz2hDI2DT:-NTGe0ElAwNqz2hDI2DU:b-ea9w39) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fdadc158497ca49432e68bad5a43898a1aa14ba7/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L758)):*
> ```Kotlin
>           EncryptionPublicKey.parseFrom(measurementSpec.measurementPublicKey).data
>         )
>           ?: failGrpc(Status.PERMISSION_DENIED) { "Encryption private key not found" }
> ```

This error code implies that the credentials are incorrect for this request. Really this is a server misconfiguration, as this call could succeed if the server's key store had the matching private key.



_Suggestion:_
```Kotlin
FAILED_PRECONDITION
```
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 758 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/951#-NTGemwA1OoUJn2LX4Rl:-NTGemwA1OoUJn2LX4Rm:bxob65v) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fdadc158497ca49432e68bad5a43898a1aa14ba7/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L758)):*
> ```Kotlin
>           EncryptionPublicKey.parseFrom(measurementSpec.measurementPublicKey).data
>         )
>           ?: failGrpc(Status.PERMISSION_DENIED) { "Encryption private key not found" }
> ```

nit: maybe include more context, such as the measurement resource name
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 926 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/951#-NTGhtg24D6Un2cnFsFa:-NTGhtg24D6Un2cnFsFb:be8pjwg) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fdadc158497ca49432e68bad5a43898a1aa14ba7/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L926)):*
> ```Kotlin
> 
>     return listMetricsResponse {
>       metrics +=
> ```

Since you stated that the intent is to compute the result here, you should be able to skip the second read.

The flow should be:
1. Read internal metrics
2. Sync measurements, noting new states.
3. Determine which pending metrics need state updates (e.g. all Measurements were already SUCCEEDED or have just all become SUCCEEDED from step 2 or have any Measurements that are FAILED, etc.)
4. Transition internal metric states, adding results/failures.
5. Convert internal metrics to public metrics, merging in changes from step 4.


<!-- Sent from Reviewable.io -->

2023-04-18 00:50 UTC, SanjayVas requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/951)* status: 1 of 5 files reviewed, 8 unresolved discussions (waiting on @riemanli and @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/page_token.proto` line 23 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/951#-NTGnaNj8OqbEnEzm9B1:-NTGnaNj8OqbEnEzm9B2:b45h) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fdadc158497ca49432e68bad5a43898a1aa14ba7/src/main/proto/wfa/measurement/api/v2alpha/page_token.proto#L23)):*
> ```protobuf
> import "wfa/measurement/api/v2alpha/requisition.proto";
> 
> option java_package = "org.wfanet.measurement.api.v2.alpha";
> ```





_Suggestion:_
```protobuf
v2alpha
```
___
*[`src/main/proto/wfa/measurement/api/v2alpha/page_token.proto` line 88 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/951#-NTGnov_8Oo7HQ3NpR8O:-NTGnov_8Oo7HQ3NpR8P:b-47wrw9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fdadc158497ca49432e68bad5a43898a1aa14ba7/src/main/proto/wfa/measurement/api/v2alpha/page_token.proto#L88)):*
> ```protobuf
>   message PreviousPageEnd {
>     string external_measurement_consumer_id = 1;
>     fixed64 external_metric_id = 2;
> ```

This should be whatever fields are used to create the total ordering of Metrics from an internal StreamMetrics call. Is this what StreamMetric orders by?

We should also document the ordering on the internal API definition.



_Code quote:_
```protobuf
    string external_measurement_consumer_id = 1;
    fixed64 external_metric_id = 2;
```


<!-- Sent from Reviewable.io -->

2023-04-18 21:55 UTC, riemanli commented
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 926 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/951#-NTGhtg24D6Un2cnFsFa:-NTL54xj5YnI3Rs-Rord:b-rpxhzz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fdadc158497ca49432e68bad5a43898a1aa14ba7/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L926)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Since you stated that the intent is to compute the result here, you should be able to skip the second read.

The flow should be:
1. Read internal metrics
2. Sync measurements, noting new states.
3. Determine which pending metrics need state updates (e.g. all Measurements were already SUCCEEDED or have just all become SUCCEEDED from step 2 or have any Measurements that are FAILED, etc.)
4. Transition internal metric states, adding results/failures.
5. Convert internal metrics to public metrics, merging in changes from step 4.
</blockquote></details>

I think (2) and (3) involves some bookkeeping and sounds a bit complicated, especially if we need to keep the order of the metrics in the output of `StreamMetrics`.

I wonder if the following flow is ok too:

1. Read the internal metrics
2. Sync measurements, noting new states.
3. Read the internal metrics again
4. For the metrics that are already in the terminal states, save to the result list directly; for the running metrics, if not all measurements are ready, save to the result list too. If all measurements are ready -> set result. If any measurement is failed -> set failure.
5. Convert internal metrics to public metrics.


<!-- Sent from Reviewable.io -->

2023-04-18 22:02 UTC, riemanli commented
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 926 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/951#-NTGhtg24D6Un2cnFsFa:-NTLNbZG9G4yD5EfLoNk:bf7q976) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fdadc158497ca49432e68bad5a43898a1aa14ba7/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L926)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

I think (2) and (3) involves some bookkeeping and sounds a bit complicated, especially if we need to keep the order of the metrics in the output of `StreamMetrics`.

I wonder if the following flow is ok too:

1. Read the internal metrics
2. Sync measurements, noting new states.
3. Read the internal metrics again
4. For the metrics that are already in the terminal states, save to the result list directly; for the running metrics, if not all measurements are ready, save to the result list too. If all measurements are ready -> set result. If any measurement is failed -> set failure.
5. Convert internal metrics to public metrics.
</blockquote></details>

Actually (4) in my proposal also needs a map to keep the order.


<!-- Sent from Reviewable.io -->

2023-04-18 22:17 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/951)* status: 1 of 6 files reviewed, 6 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 601 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/951#-NTGcbDIEMuYx3GHpQ4c:-NTKg_qoEnJoazZTw9Yx:btmxo9p) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fdadc158497ca49432e68bad5a43898a1aa14ba7/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L601)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Is this case possible given that you're using `groupBy`? I believe you'll only get a map entry if there's at least one measurement with that state.
</blockquote></details>

That's a good point! Removed redundant checks.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 642 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/951#-NTGbw_z3dldwXEK_NHz:-NTKhR43B91BgqNS165e:b-ao9n27) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fdadc158497ca49432e68bad5a43898a1aa14ba7/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L642)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Batch methods must be atomic, i.e. all or nothing. Therefore this will never be true.
</blockquote></details>

Great to know! Removed all the size checks after batch methods.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 715 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/951#-NTGaPXh9Mc_qHQHM0Hl:-NTKOSRCBxF1m2h6sUS7:bdi1gae) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fdadc158497ca49432e68bad5a43898a1aa14ba7/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L715)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: just return the list and do the grouping at the single call site. The method name makes it look like this is querying with a state predicate rather than grouping the result by state, which can be done trivially after the RPC.
</blockquote></details>

Thanks for the suggestions! Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 758 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/951#-NTGe0ElAwNqz2hDI2DT:-NTKXwsL61c4-y2RylgX:b-x8yi3y) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fdadc158497ca49432e68bad5a43898a1aa14ba7/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L758)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This error code implies that the credentials are incorrect for this request. Really this is a server misconfiguration, as this call could succeed if the server's key store had the matching private key.
</blockquote></details>

Thanks for catching it! Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 758 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/951#-NTGemwA1OoUJn2LX4Rl:-NTKY-TiD03Ogy-uUij1:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fdadc158497ca49432e68bad5a43898a1aa14ba7/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L758)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: maybe include more context, such as the measurement resource name
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 926 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/951#-NTGhtg24D6Un2cnFsFa:-NTLRCqs2-zAn8fbM7Dp:bjgkeh9) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fdadc158497ca49432e68bad5a43898a1aa14ba7/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L926)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Actually (4) in my proposal also needs a map to keep the order.
</blockquote></details>

I implemented the proposal. Let me know what you think!
___
*[`src/main/proto/wfa/measurement/api/v2alpha/page_token.proto` line 23 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/951#-NTGnaNj8OqbEnEzm9B1:-NTKebIY3tJzFwNPmkd5:bolzov0) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fdadc158497ca49432e68bad5a43898a1aa14ba7/src/main/proto/wfa/measurement/api/v2alpha/page_token.proto#L23)):*
> ```protobuf
> import "wfa/measurement/api/v2alpha/requisition.proto";
> 
> option java_package = "org.wfanet.measurement.api.v2.alpha";
> ```

Could we fix this later in another PR? It needs to fix relevant imports in many files.
___
*[`src/main/proto/wfa/measurement/api/v2alpha/page_token.proto` line 88 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/951#-NTGnov_8Oo7HQ3NpR8O:-NTKgNkUD2OehllS9qxd:b-v3kiyi) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fdadc158497ca49432e68bad5a43898a1aa14ba7/src/main/proto/wfa/measurement/api/v2alpha/page_token.proto#L88)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

This should be whatever fields are used to create the total ordering of Metrics from an internal StreamMetrics call. Is this what StreamMetric orders by?

We should also document the ordering on the internal API definition.
</blockquote></details>

Yeah I think so. The `StreamMetricRequest` looks like this:

```protobuf
message StreamMetricsRequest {
  message Filter {
    // `MeasurementConsumer` ID from the CMMS public API.
    string cmms_measurement_consumer_id = 1;
    // Skips to results with an external id greater than this.
    fixed64 external_metric_id_after = 2;
  }
  Filter filter = 1;

  int32 limit = 2;
}
```


<!-- Sent from Reviewable.io -->

2023-04-19 22:08 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/951)* status: 4 of 6 files reviewed, 9 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 906 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/951#-NTQ-Kvd21-pnC_aQzBP:-NTQPzs-3GJue2gtmiCb:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d4b8618898478d26759baf9f1e3836fcbf509079/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L906)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Extract this to a variable as you do it more than once.
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 923 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/951#-NTPy81c-0igNW5RKhQO:-NTQRfoHAETwDQnITZF3:b-hpavcm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d4b8618898478d26759baf9f1e3836fcbf509079/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L923)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I wouldn't call this `sync`, as it's a very different operation than `syncInternalMeasurements`. The other operation is syncing our local cache of Measurements with the updated results from the Kingdom. This is transitioning Metric states based on our local cache of Measurements.
</blockquote></details>

Renamed it to `refreshInternalMetrics`.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 992 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/951#-NTQK7BHAt1hp0KbRRBu:-NTQSB4l7C16kIYq4W4s:b-896fja) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d4b8618898478d26759baf9f1e3836fcbf509079/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L992)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: maybe "build" as that's a more common term
</blockquote></details>

Done!
___
*[`src/main/proto/wfa/measurement/api/v2alpha/page_token.proto` line 23 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/951#-NTGnaNj8OqbEnEzm9B1:-NTQSkTqBOszF2BjQHpw:bqmjwcz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fdadc158497ca49432e68bad5a43898a1aa14ba7/src/main/proto/wfa/measurement/api/v2alpha/page_token.proto#L23)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Sure, add a TODO.
</blockquote></details>

Added.


<!-- Sent from Reviewable.io -->

2023-04-19 23:24 UTC, SanjayVas reviewed
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/951)* status: all files reviewed, 6 unresolved discussions (waiting on @riemanli and @tristanvuong2021)



<!-- Sent from Reviewable.io -->

2023-04-20 01:00 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/951)* status: 1 of 6 files reviewed, 6 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/api/v2alpha/page_token.proto` line 88 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/951#-NTGnov_8Oo7HQ3NpR8O:-NTQv7h51zibQcxKedSL:b1icyg7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/fdadc158497ca49432e68bad5a43898a1aa14ba7/src/main/proto/wfa/measurement/api/v2alpha/page_token.proto#L88)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

What matters here is what the ORDER BY is in the underlying query. Hence why I said we should document the StreamMetrics method to mention that it's ordered by `(cmms_measurement_consumer_id, external_metric_id)`.

I think you need to change `external_measurement_consumer_id` to `cmms_measurement_consumer_id`.

</blockquote></details>

I see. `StreamMetrics` hasn't be implemented yet. I added a comment about the order to its rpc method.

Renamed to `cmms_measurement_consumer_id`.


<!-- Sent from Reviewable.io -->

2023-04-20 06:54 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/951)* status: 1 of 6 files reviewed, 5 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 690 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/951#-NTQ0RXrDJN71xglF9hv:-NTRE8jf-9KYSnlltNT4:b-x8yi3y) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d4b8618898478d26759baf9f1e3836fcbf509079/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L690)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Update method description
</blockquote></details>

Thanks for catching it! Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 884 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/951#-NTQ1OhFBgMc1hFl86LG:-NTREfNuErPbOzFAA5kZ:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d4b8618898478d26759baf9f1e3836fcbf509079/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L884)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

nit: use brackets here since you're using them in the above condition in the same expression
</blockquote></details>

Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 904 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/951#-NTQ1z3YEx_4HY-lX3Yk:-NTRFQue0LjVc0oHRblt:b-j3ht3a) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d4b8618898478d26759baf9f1e3836fcbf509079/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L904)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

As an optional optimization, you can skip the re-read if nothing changed from syncing Measurements. You still need to update any pending Metrics, but you can do that based upon the original list.
</blockquote></details>

I wonder if we even don't need to update pending metrics as no measurements are changed.
___
*[`src/main/proto/wfa/measurement/internal/reporting/v2/metrics_service.proto` line 89 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/951#-NTQN0e99Z4Av3QVLVR4:-NTSGjGnBkPOIBOB-7M9:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d4b8618898478d26759baf9f1e3836fcbf509079/src/main/proto/wfa/measurement/internal/reporting/v2/metrics_service.proto#L89)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Don't nest this message in case we end up adding a singular version of the method.
</blockquote></details>

Done.
___
*[`src/main/proto/wfa/measurement/internal/reporting/v2/metrics_service.proto` line 99 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/951#-NTQNRVZAnYmo5xFeJYS:-NTSME7U3ietPoQ188Zg:b-xu0uci) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d4b8618898478d26759baf9f1e3836fcbf509079/src/main/proto/wfa/measurement/internal/reporting/v2/metrics_service.proto#L99)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

If there's no `failure` field that we're setting, I think calling these (Batch)`Succeed` and (Batch)`Fail` would be more accurate. The `Succeed` request can still have a required result.
</blockquote></details>

Thanks for the suggestion. Done.


<!-- Sent from Reviewable.io -->

2023-04-20 16:35 UTC, SanjayVas approved these changes
> Reviewed 2 of 5 files at r6, 3 of 3 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/951)* status: all files reviewed, 1 unresolved discussion (waiting on @riemanli and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 904 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/951#-NTQ1z3YEx_4HY-lX3Yk:-NTUVw-6AzUwMz8VXF-M:b-8r0my6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d4b8618898478d26759baf9f1e3836fcbf509079/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L904)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

I wonder if we even don't need to update pending metrics as no measurements are changed.
</blockquote></details>

You'd still need to do that, as Measurements may have been changed by a separate run. e.g. the Measurement sync happened but the Get/List didn't complete, or with Measurement reuse that the relevant Measurements were synced for a different Report.


<!-- Sent from Reviewable.io -->

2023-04-20 22:31 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/951)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 904 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/951#-NTQ1z3YEx_4HY-lX3Yk:-NTVlkcy5T6LIlyjD9sJ:b-896fja) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/d4b8618898478d26759baf9f1e3836fcbf509079/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L904)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

You'd still need to do that, as Measurements may have been changed by a separate run. e.g. the Measurement sync happened but the Get/List didn't complete, or with Measurement reuse that the relevant Measurements were synced for a different Report.
</blockquote></details>

Done!


<!-- Sent from Reviewable.io -->

2023-04-20 23:32 UTC, riemanli commented
Current dependencies on/for this PR:
* main
  * **PR #951** <a href="https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/951" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈
    * **PR #959** <a href="https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/959" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/951?utm_source=stack-comment).

2023-04-21 12:54 UTC, Marco-Premier approved these changes
> Reviewed 1 of 5 files at r1, 2 of 5 files at r6, 1 of 3 files at r7, 1 of 2 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/951)* status: all files reviewed, 1 unresolved discussion (waiting on @riemanli, @SanjayVas, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/proto/wfa/measurement/internal/reporting/v2/metrics_service.proto` line 111 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/951#-NTYs2cODNCnXgLWKJ2L:-NTYs2cODNCnXgLWKJ2M:b-atcqg5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9e445a6d5174cd3909f53861a38baa895407fecf/src/main/proto/wfa/measurement/internal/reporting/v2/metrics_service.proto#L111)):*
> ```protobuf
> message BatchSetMetricFailResponse {
>   repeated Metric metrics = 1;
> }
> ```

I think files need to end with new line


<!-- Sent from Reviewable.io -->

2023-04-21 15:50 UTC, stevenwarejones requested changes
> Reviewed 1 of 5 files at r1, 2 of 5 files at r6, 1 of 3 files at r7, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/951)* status: all files reviewed, 4 unresolved discussions (waiting on @riemanli, @SanjayVas, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 702 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/951#-NTZUVnd7dVAWtmwY0BO:-NTZUVnd7dVAWtmwY0BP:b-n5dfvh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9e445a6d5174cd3909f53861a38baa895407fecf/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L702)):*
> ```Kotlin
>       principal: MeasurementConsumerPrincipal,
>     ): List<Measurement> = coroutineScope {
>       val deferred = mutableListOf<Deferred<Measurement>>()
> ```

why not just map these and ovoid the mutableList
```
val deferred = internalMeasurements.map{
          val measurementResourceName =
          MeasurementKey(
              principal.resourceKey.measurementConsumerId,
              internalMeasurement.cmmsMeasurementId
            )
            .toName()

        deferred.add(
          async {
            try {
              measurementsStub
                .withAuthenticationKey(apiAuthenticationKey)
                .getMeasurement(getMeasurementRequest { name = measurementResourceName })
            } catch (e: StatusException) {
              throw Exception("Unable to retrieve the measurement [$measurementResourceName].", e)
            }
          }
        )


}
```

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 900 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/951#-NTZUE7gAhOhkM667c1B:-NTZUE7gAhOhkM667c1C:b-gdyc0p) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9e445a6d5174cd3909f53861a38baa895407fecf/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L900)):*
> ```Kotlin
>     val toBeSyncedInternalMeasurements: List<InternalMeasurement> =
>       subResults
>         .filter { internalMetric -> internalMetric.state == InternalMetric.State.RUNNING }
> ```

We want everything not in a terminal state, right?
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 1546 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/951#-NTZVFJq0DINRscMnK8J:-NTZVFJq0DINRscMnK8K:b-2i3uo8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9e445a6d5174cd3909f53861a38baa895407fecf/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L1546)):*
> ```Kotlin
> }
> 
> private operator fun Duration.times(coefficient: Int): Duration {
> ```

are these only used for testing? If so, can you move them to `testing`?


<!-- Sent from Reviewable.io -->

2023-04-21 16:29 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/951)* status: 4 of 6 files reviewed, 4 unresolved discussions (waiting on @Marco-Premier, @SanjayVas, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 702 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/951#-NTZUVnd7dVAWtmwY0BO:-NTZasDMCZke5Fq6muST:b-bjudbj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9e445a6d5174cd3909f53861a38baa895407fecf/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L702)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

why not just map these and ovoid the mutableList
```
val deferred = internalMeasurements.map{
          val measurementResourceName =
          MeasurementKey(
              principal.resourceKey.measurementConsumerId,
              internalMeasurement.cmmsMeasurementId
            )
            .toName()

        deferred.add(
          async {
            try {
              measurementsStub
                .withAuthenticationKey(apiAuthenticationKey)
                .getMeasurement(getMeasurementRequest { name = measurementResourceName })
            } catch (e: StatusException) {
              throw Exception("Unable to retrieve the measurement [$measurementResourceName].", e)
            }
          }
        )


}
```

</blockquote></details>

Thanks for the suggestion! Done.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 900 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/951#-NTZUE7gAhOhkM667c1B:-NTZb1WA5HxrXsAULz7l:b-hyg2jx) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9e445a6d5174cd3909f53861a38baa895407fecf/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L900)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

We want everything not in a terminal state, right?
</blockquote></details>

Yes. Right now, except the invalid states `STATE_UNSPECIFIED` and `UNRECOGNIZED`, `RUNNING` is the only state that is not a terminal state.
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 1546 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/951#-NTZVFJq0DINRscMnK8J:-NTZbj5O2kjtb3QViMoh:bogarmi) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9e445a6d5174cd3909f53861a38baa895407fecf/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L1546)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

are these only used for testing? If so, can you move them to `testing`?
</blockquote></details>

No. It's used implicitly with `*` in `calculateWatchDurationResults`.
___
*[`src/main/proto/wfa/measurement/internal/reporting/v2/metrics_service.proto` line 111 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/951#-NTYs2cODNCnXgLWKJ2L:-NTZbvl-4oVhyFy_vln4:b-x8yi3y) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9e445a6d5174cd3909f53861a38baa895407fecf/src/main/proto/wfa/measurement/internal/reporting/v2/metrics_service.proto#L111)):*
<details><summary><i>Previously, Marco-Premier (marcopremier) wrote…</i></summary><blockquote>

I think files need to end with new line
</blockquote></details>

Thanks for catching it! Done.


<!-- Sent from Reviewable.io -->

2023-04-21 17:37 UTC, SanjayVas requested changes
> Reviewed 1 of 2 files at r8, 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/951)* status: all files reviewed, 5 unresolved discussions (waiting on @Marco-Premier, @riemanli, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 588 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/951#-NTZsafK4ItIze8SParP:-NTZsafK4ItIze8SParQ:bsjoo28) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cec39789ddbb1fe0f9c71fa5668b498a3921f00b/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L588)):*
> ```Kotlin
>     }
> 
>     /** Syncs [InternalMeasurement]s with the CMMS [Measurement]s. */
> ```

Document that this returns whether any InternalMeasurement was updated.


<!-- Sent from Reviewable.io -->

2023-04-21 19:12 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/951)* status: 5 of 6 files reviewed, 5 unresolved discussions (waiting on @Marco-Premier, @SanjayVas, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 588 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/951#-NTZsafK4ItIze8SParP:-NT_Dle88X3anjdit5UW:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cec39789ddbb1fe0f9c71fa5668b498a3921f00b/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L588)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Document that this returns whether any InternalMeasurement was updated.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-04-21 21:22 UTC, SanjayVas requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/951)* status: 5 of 6 files reviewed, 5 unresolved discussions (waiting on @Marco-Premier, @riemanli, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 588 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/951#-NTZsafK4ItIze8SParP:-NT_gRKHDBRsoQqStib-:bp0p1bk) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cec39789ddbb1fe0f9c71fa5668b498a3921f00b/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L588)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Use `@return`. See https://kotlinlang.org/docs/kotlin-doc.html#return


<!-- Sent from Reviewable.io -->

2023-04-21 22:09 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/951)* status: 5 of 6 files reviewed, 5 unresolved discussions (waiting on @Marco-Premier, @SanjayVas, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 588 at r10](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/951#-NTZsafK4ItIze8SParP:-NT_qEbKED3nk-wYiJtA:b-6abjtf) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/cec39789ddbb1fe0f9c71fa5668b498a3921f00b/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L588)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

Use `@return`. See https://kotlinlang.org/docs/kotlin-doc.html#return
</blockquote></details>

Thanks for reminding!


<!-- Sent from Reviewable.io -->

2023-04-21 23:31 UTC, SanjayVas approved these changes
> Reviewed 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/951)* status: all files reviewed, 4 unresolved discussions (waiting on @Marco-Premier, @stevenwarejones, and @tristanvuong2021)



<!-- Sent from Reviewable.io -->

2023-04-24 16:08 UTC, stevenwarejones requested changes
> Reviewed 1 of 2 files at r8, 1 of 2 files at r10, 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/951)* status: all files reviewed, 2 unresolved discussions (waiting on @Marco-Premier, @riemanli, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 1546 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/951#-NTZVFJq0DINRscMnK8J:-NTo0Gi76DHidjKuCIe4:b-sxkbj1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9e445a6d5174cd3909f53861a38baa895407fecf/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L1546)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

No. It's used implicitly with `*` in `calculateWatchDurationResults`.
</blockquote></details>

should we call this `weight` or `coefficient`?


<!-- Sent from Reviewable.io -->

2023-04-25 01:00 UTC, stevenwarejones requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/951)* status: all files reviewed, 2 unresolved discussions (waiting on @Marco-Premier, @riemanli, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 1546 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/951#-NTZVFJq0DINRscMnK8J:-NTpvCWe-aZAIGQFSWOa:bfzef04) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9e445a6d5174cd3909f53861a38baa895407fecf/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L1546)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

I am not sure what you meant by that. Could you please elaborate more? 

The operator `*` is overloaded by defining `times`. It is used in the code 

```kotlin
weightedMeasurement.measurement.details.result.watchDuration.value *
  weightedMeasurement.weight
```
</blockquote></details>

 I know. I meant the name of the variable itself. Whether weight or coefficient is more clear
```
private operator fun Duration.times(weight: Int): Duration {
```




_Code quote:_
```Kotlin
private operator fun Duration.times(coefficient: Int): Duration {
```


<!-- Sent from Reviewable.io -->

2023-04-25 01:06 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/951)* status: all files reviewed, 2 unresolved discussions (waiting on @Marco-Premier, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 1546 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/951#-NTZVFJq0DINRscMnK8J:-NTpwEao9XpINxayjfZf:bbn3epe) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9e445a6d5174cd3909f53861a38baa895407fecf/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L1546)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

 I know. I meant the name of the variable itself. Whether weight or coefficient is more clear
```
private operator fun Duration.times(weight: Int): Duration {
```

</blockquote></details>

The name of the variable is `coefficient` already. I am not sure which variable you're referring to.


<!-- Sent from Reviewable.io -->

2023-04-25 13:48 UTC, stevenwarejones requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/951)* status: all files reviewed, 2 unresolved discussions (waiting on @Marco-Premier, @riemanli, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 1546 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/951#-NTZVFJq0DINRscMnK8J:-NTseTAV2_jKxGNIcBj6:b-7a1re1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9e445a6d5174cd3909f53861a38baa895407fecf/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L1546)):*
<details><summary><i>Previously, riemanli (Rieman) wrote…</i></summary><blockquote>

The name of the variable is `coefficient` already. I am not sure which variable you're referring to.
</blockquote></details>

sorry if I'm not being clear -- if you look at my code snippet, you'll see i renamed `coefficient` to `weight`


<!-- Sent from Reviewable.io -->

2023-04-25 16:23 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/951)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @Marco-Premier, @SanjayVas, @stevenwarejones, and @tristanvuong2021)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 1546 at r9](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/951#-NTZVFJq0DINRscMnK8J:-NTt5lr94o7OyFl18pfY:b-pa2qpt) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/9e445a6d5174cd3909f53861a38baa895407fecf/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L1546)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

sorry if I'm not being clear -- if you look at my code snippet, you'll see i renamed `coefficient` to `weight`
</blockquote></details>

I see. Thanks for the explanation. Renamed.


<!-- Sent from Reviewable.io -->

2023-04-25 16:50 UTC, stevenwarejones approved these changes
> Reviewed 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/951)* status: all files reviewed, 1 unresolved discussion (waiting on @Marco-Premier, @SanjayVas, and @tristanvuong2021)



<!-- Sent from Reviewable.io -->

2023-04-25 16:52 UTC, riemanli reviewed
> Reviewed 1 of 5 files at r1, 2 of 5 files at r6, 1 of 2 files at r8, 1 of 2 files at r10, 1 of 1 files at r13, all commit messages.
> Dismissed @Marco-Premier from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/951)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Marco-Premier, @SanjayVas, and @tristanvuong2021)



<!-- Sent from Reviewable.io -->

2023-04-25 16:55 UTC, merged