Create duchy schema in postgres
world-federation-of-advertisers/cross-media-measurement pull request #958
Opened 2023-04-20 17:21 UTC by YuhongWang-Amazon

This adds the sql file that creates the duchy schema in postgres database and the schemata tests.

2023-04-20 17:21 UTC, wfa-reviewable commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/958)
<!-- Reviewable:end -->

2023-04-20 18:47 UTC, SanjayVas commented
Removing self as a reviewer until @renjiezh has had a chance to do a first pass.

2023-04-21 05:06 UTC, renjiezh requested changes
Overall looks good to me. I noticed there are no `NOT NULL` for CreationTime and UpdateTime. I think we need it. But please ignore it if Postgres is not working in this way. 

> Reviewed 4 of 7 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/958#-:-NTXBhqA5i6tI2Z00NXT:b6wgjne)* status: all files reviewed, 17 unresolved discussions (waiting on @YuhongWang-Amazon)

___
*[`src/main/resources/duchy/postgres/create-duchy-schema.sql` line 3 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/958#-NTX4IdZBT-lJ3InMQgH:-NTX4ESmA4QYFMJp_2s4:bxqvv2x) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ad8e813eb6dedb8ef27d1d5231fab27001d768dc/src/main/resources/duchy/postgres/create-duchy-schema.sql#L3)):*
> ```TSQL
> -- liquibase formatted sql
> 
> -- Copyright 2022 The Cross-Media Measurement Authors
> ```

nit: 2023
___
*[`src/main/resources/duchy/postgres/create-duchy-schema.sql` line 99 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/958#-NTX5oeJAaIiiTVwXUYO:-NTX5oeJAaIiiTVwXUYP:bqtzbtj) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ad8e813eb6dedb8ef27d1d5231fab27001d768dc/src/main/resources/duchy/postgres/create-duchy-schema.sql#L99)):*
> ```TSQL
>   -- database.
>   --
>   -- See the wfa.measurement.internal.db.gcp.ComputationDetails Proto
> ```

Could you please update this. It is `wfa.measurement.internal.duchy`.
___
*[`src/main/resources/duchy/postgres/create-duchy-schema.sql` line 106 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/958#-NTX60DF9GAOQVOYCm1I:-NTX60DF9GAOQVOYCm1J:b-rqxvo7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ad8e813eb6dedb8ef27d1d5231fab27001d768dc/src/main/resources/duchy/postgres/create-duchy-schema.sql#L106)):*
> ```TSQL
>   -- database.
>   --
>   -- See the wfa.measurement.internal.db.gcp.ComputationDetails Proto
> ```

ditto.
___
*[`src/main/resources/duchy/postgres/create-duchy-schema.sql` line 110 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/958#-NTUv-Qd5A1yax5eAQ1d:-NTUv-Qd5A1yax5eAQ1e:b93ssuq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ad8e813eb6dedb8ef27d1d5231fab27001d768dc/src/main/resources/duchy/postgres/create-duchy-schema.sql#L110)):*
> ```TSQL
> 
>   -- The time the Computation was created. Due to conflict with default value
>   -- and option `allow_commit_timestamp`, this column has to be nullable. The
> ```

This "nullable" note was used for spanner schema. For postgres we can make it "NOT NULL".
___
*[`src/main/resources/duchy/postgres/create-duchy-schema.sql` line 136 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/958#-NTXA1gKBSVtl39qb7WJ:-NTXA1gKBSVtl39qb7WK:b-4rpx6m) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ad8e813eb6dedb8ef27d1d5231fab27001d768dc/src/main/resources/duchy/postgres/create-duchy-schema.sql#L136)):*
> ```TSQL
> --   If the path is set, the requisition is fulfilled at this duchy. Otherwise,
> --   it is not fulfilled yet or fulfilled at other duchies.
> CREATE TABLE Requisitions (
> ```

Do we need CreationTime and UpdateTime for Requisitions? I know this would make it inconsistent with spanner's impl. But I guess adding new fields would do no harm.
___
*[`src/main/resources/duchy/postgres/create-duchy-schema.sql` line 161 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/958#-NTX8Zp21RBbuhG-H-NL:-NTX8Zp21RBbuhG-H-NM:b-6ezyfd) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ad8e813eb6dedb8ef27d1d5231fab27001d768dc/src/main/resources/duchy/postgres/create-duchy-schema.sql#L161)):*
> ```TSQL
>   --
>   -- See the wfa.measurement.internal.RequisitionDetails Proto
>   RequisitionDetailsJSON text NOT NULL,
> ```

Do we need type `jsonb` here?
___
*[`src/main/resources/duchy/postgres/create-duchy-schema.sql` line 180 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/958#-NTX8sgD6HHAuSVYm-Lq:-NTX8sgD6HHAuSVYm-Lr:bxn5jsq) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ad8e813eb6dedb8ef27d1d5231fab27001d768dc/src/main/resources/duchy/postgres/create-duchy-schema.sql#L180)):*
> ```TSQL
> CREATE TABLE ComputationStages (
>   -- The local identifier of the computation.
>   ComputationId integer NOT NULL,
> ```

bigint.
___
*[`src/main/resources/duchy/postgres/create-duchy-schema.sql` line 190 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/958#-NTX9i68Dc4OrYJSD__C:-NTX9i68Dc4OrYJSD__D:birmniv) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ad8e813eb6dedb8ef27d1d5231fab27001d768dc/src/main/resources/duchy/postgres/create-duchy-schema.sql#L190)):*
> ```TSQL
>   -- less than or equal to the ComputationStageAttempts.BeginTime
>   -- as the stage is created at or before the time of its attempt.
>   CreationTime timestamp,
> ```

Do we need to add `NOT NULL`?
___
*[`src/main/resources/duchy/postgres/create-duchy-schema.sql` line 215 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/958#-NTX9sIY7VrVJZAY2LpL:-NTX9sIY7VrVJZAY2LpM:b-rqxvo7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ad8e813eb6dedb8ef27d1d5231fab27001d768dc/src/main/resources/duchy/postgres/create-duchy-schema.sql#L215)):*
> ```TSQL
>   -- database.
>   --
>   -- See the wfa.measurement.internal.db.gcp.ComputationStageDetails Proto
> ```

ditto.
___
*[`src/main/resources/duchy/postgres/create-duchy-schema.sql` line 222 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/958#-NTX9r_bESzVbEvA9xIZ:-NTX9r_cC0JyMaNyUe-t:b-rqxvo7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ad8e813eb6dedb8ef27d1d5231fab27001d768dc/src/main/resources/duchy/postgres/create-duchy-schema.sql#L222)):*
> ```TSQL
>   -- database.
>   --
>   -- See the wfa.measurement.internal.db.gcp.ComputationStageDetails Proto
> ```

ditto.
___
*[`src/main/resources/duchy/postgres/create-duchy-schema.sql` line 260 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/958#-NTXAcXJ90u3Te2j21Vr:-NTXAcXJ90u3Te2j21Vs:b-rqxvo7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ad8e813eb6dedb8ef27d1d5231fab27001d768dc/src/main/resources/duchy/postgres/create-duchy-schema.sql#L260)):*
> ```TSQL
>   -- is the blob an input to the stage, or is it a required output.
>   --
>   -- See the wfa.measurement.internal.db.gcp.ComputationBlobDependency proto
> ```

ditto.
___
*[`src/main/resources/duchy/postgres/create-duchy-schema.sql` line 261 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/958#-NTXAgd57cgpl27TqOET:-NTXAgd65beFEQLe1Zgi:b-twprz4) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ad8e813eb6dedb8ef27d1d5231fab27001d768dc/src/main/resources/duchy/postgres/create-duchy-schema.sql#L261)):*
> ```TSQL
>   --
>   -- See the wfa.measurement.internal.db.gcp.ComputationBlobDependency proto
>   DependencyType bigint NOT NULL,
> ```

This is a enum. Thus `integer` should be good.
___
*[`src/main/resources/duchy/postgres/create-duchy-schema.sql` line 291 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/958#-NTXB78UDKKVsJN5jM0y:-NTXB78UDKKVsJN5jM0z:b3paa55) ([raw file](https://github.com/world-federation-o [...]

2023-04-21 17:12 UTC, YuhongWang-Amazon reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/958)* status: 5 of 7 files reviewed, 16 unresolved discussions (waiting on @renjiezh)

___
*[`src/main/resources/duchy/postgres/create-duchy-schema.sql` line 99 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/958#-NTX5oeJAaIiiTVwXUYO:-NTZiYIx4WMkLgxq3WLG:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ad8e813eb6dedb8ef27d1d5231fab27001d768dc/src/main/resources/duchy/postgres/create-duchy-schema.sql#L99)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

Could you please update this. It is `wfa.measurement.internal.duchy`.
</blockquote></details>

Done.
___
*[`src/main/resources/duchy/postgres/create-duchy-schema.sql` line 106 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/958#-NTX60DF9GAOQVOYCm1I:-NTZiZ4y33x3c48F4Ss-:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ad8e813eb6dedb8ef27d1d5231fab27001d768dc/src/main/resources/duchy/postgres/create-duchy-schema.sql#L106)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

ditto.
</blockquote></details>

Done.
___
*[`src/main/resources/duchy/postgres/create-duchy-schema.sql` line 110 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/958#-NTUv-Qd5A1yax5eAQ1d:-NTZi_Nn-tjgpaRFVyrh:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ad8e813eb6dedb8ef27d1d5231fab27001d768dc/src/main/resources/duchy/postgres/create-duchy-schema.sql#L110)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

This "nullable" note was used for spanner schema. For postgres we can make it "NOT NULL".
</blockquote></details>

Done.
___
*[`src/main/resources/duchy/postgres/create-duchy-schema.sql` line 136 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/958#-NTXA1gKBSVtl39qb7WJ:-NTZie3-C-CWO3622ugK:b8ju151) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ad8e813eb6dedb8ef27d1d5231fab27001d768dc/src/main/resources/duchy/postgres/create-duchy-schema.sql#L136)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

Do we need CreationTime and UpdateTime for Requisitions? I know this would make it inconsistent with spanner's impl. But I guess adding new fields would do no harm.
</blockquote></details>

Agree, and Added!
___
*[`src/main/resources/duchy/postgres/create-duchy-schema.sql` line 161 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/958#-NTX8Zp21RBbuhG-H-NL:-NTZij1xCwDhhvfCwOuC:b-43ai2f) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ad8e813eb6dedb8ef27d1d5231fab27001d768dc/src/main/resources/duchy/postgres/create-duchy-schema.sql#L161)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

Do we need type `jsonb` here?
</blockquote></details>

Yes, it should be `jsonb`. 
___
*[`src/main/resources/duchy/postgres/create-duchy-schema.sql` line 180 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/958#-NTX8sgD6HHAuSVYm-Lq:-NTZirfD8tEGTzvSWKXP:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ad8e813eb6dedb8ef27d1d5231fab27001d768dc/src/main/resources/duchy/postgres/create-duchy-schema.sql#L180)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

bigint.
</blockquote></details>

Done.
___
*[`src/main/resources/duchy/postgres/create-duchy-schema.sql` line 215 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/958#-NTX9sIY7VrVJZAY2LpL:-NTZm1k689UDHPRbvv0p:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ad8e813eb6dedb8ef27d1d5231fab27001d768dc/src/main/resources/duchy/postgres/create-duchy-schema.sql#L215)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

ditto.
</blockquote></details>

Done.
___
*[`src/main/resources/duchy/postgres/create-duchy-schema.sql` line 222 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/958#-NTX9r_bESzVbEvA9xIZ:-NTZm2VC3rx5RK4UXb0_:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ad8e813eb6dedb8ef27d1d5231fab27001d768dc/src/main/resources/duchy/postgres/create-duchy-schema.sql#L222)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

ditto.
</blockquote></details>

Done.
___
*[`src/main/resources/duchy/postgres/create-duchy-schema.sql` line 260 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/958#-NTXAcXJ90u3Te2j21Vr:-NTZm5_p2yYhEV2pxXVd:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ad8e813eb6dedb8ef27d1d5231fab27001d768dc/src/main/resources/duchy/postgres/create-duchy-schema.sql#L260)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

ditto.
</blockquote></details>

Done.
___
*[`src/main/resources/duchy/postgres/create-duchy-schema.sql` line 261 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/958#-NTXAgd57cgpl27TqOET:-NTZm9zU-aZ8919zOu0D:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ad8e813eb6dedb8ef27d1d5231fab27001d768dc/src/main/resources/duchy/postgres/create-duchy-schema.sql#L261)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

This is a enum. Thus `integer` should be good.
</blockquote></details>

Done.
___
*[`src/main/resources/duchy/postgres/create-duchy-schema.sql` line 291 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/958#-NTXB78UDKKVsJN5jM0y:-NTZmD2D832JBjX_V5zX:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ad8e813eb6dedb8ef27d1d5231fab27001d768dc/src/main/resources/duchy/postgres/create-duchy-schema.sql#L291)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

NOT NULL
</blockquote></details>

Done.
___
*[`src/main/resources/duchy/postgres/create-duchy-schema.sql` line 343 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/958#-NTXBIyG5JAljqKRdnVY:-NTZmHn59h7L3mqPKW8d:btm1c7c) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ad8e813eb6dedb8ef27d1d5231fab27001d768dc/src/main/resources/duchy/postgres/create-duchy-schema.sql#L343)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

NOT NULL.
</blockquote></details>

Added. Also updated this to CreationTime so it is consistent with other tables.
___
*[`src/main/resources/duchy/postgres/create-duchy-schema.sql` line 350 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/958#-NTXBS1BDaVe5o_7s-KE:-NTZmOr2DUvRDXmf7ar_:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ad8e813eb6dedb8ef27d1d5231fab27001d768dc/src/main/resources/duchy/postgres/create-duchy-schema.sql#L350)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

Guess we need `ON DELETE CASCADE`?
</blockquote></details>

Done.
___
*[`src/main/resources/duchy/postgres/create-duchy-schema.sql` line 368 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/958#-NTXB__v8Kv_16_WXlXY:-NTZmR6CCJJEDTbjWnJS:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/b [...]

2023-04-21 17:16 UTC, YuhongWang-Amazon reviewed
Thank @renjiezh for you thorough review.
The postgres do support `NOT NULL` timestamps, I didn't think through that when copying everything from the spanner definitions. 
All comments resolved, please take another look when you got chance. Appreciated!

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/958#-:-NTZngEX9BNLGzmqPFNO:b-7vx70s)* status: 5 of 7 files reviewed, 16 unresolved discussions (waiting on @renjiezh)

___
*[`src/main/resources/duchy/postgres/create-duchy-schema.sql` line 190 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/958#-NTX9i68Dc4OrYJSD__C:-NTZnbEI6SYhykRbrXdW:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/ad8e813eb6dedb8ef27d1d5231fab27001d768dc/src/main/resources/duchy/postgres/create-duchy-schema.sql#L190)):*
<details><summary><i>Previously, renjiezh wrote…</i></summary><blockquote>

Do we need to add `NOT NULL`?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-04-21 18:31 UTC, renjiezh approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/958#-:-NT_4Lq44ej4XJRUB1rp:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @YuhongWang-Amazon)



<!-- Sent from Reviewable.io -->

2023-04-21 23:30 UTC, SanjayVas requested changes
> Reviewed 4 of 7 files at r1, 1 of 3 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/958)* status: all files reviewed, 7 unresolved discussions (waiting on @YuhongWang-Amazon)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/958#-NTa5719-2P65zKgPdLi:-NTa5719-2P65zKgPdLj:bhp24mn) (no related file):*
I know that some of these comments were copied from the original schema, but trying to get them to be clear since they can never be changed (Liquibase changeset checksums include the comments).

Note that you shouldn't just blindly copy the existing Spanner schema. It can be whatever you want as long as the resulting service implementations comply to the documented internal API behavior (as verified by the new tests you wrote).

___
___
*[`src/main/resources/duchy/postgres/create-duchy-schema.sql` line 18 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/958#-NTa1Z2I6qfXynE7Lc8A:-NTa1Z2I6qfXynE7Lc8B:b1irx4e) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/05309f72310dea2eeb07ea48b4b70eb83af9487d/src/main/resources/duchy/postgres/create-duchy-schema.sql#L18)):*
> ```TSQL
> 
> 
> -- changeset yuhongwang:create-duchy-schema dbms:postgresql
> ```

nit: use numbered changeset IDs in new schemata



_Suggestion:_
```TSQL
yuhongwang:1
```
___
*[`src/main/resources/duchy/postgres/create-duchy-schema.sql` line 95 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/958#-NTa4y5CDATyyXDfatfG:-NTa4y5CDATyyXDfatfH:bf3h33n) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/05309f72310dea2eeb07ea48b4b70eb83af9487d/src/main/resources/duchy/postgres/create-duchy-schema.sql#L95)):*
> ```TSQL
>   LockExpirationTime timestamp,
> 
>   -- Serialized bytes of a proto3 protobuf with details about the
> ```

nit: it's sufficient to just state that this is a serialized protobuf message



_Suggestion:_
```TSQL
  -- Serialized wfa.measurement.internal.duchy.ComputationDetails protobuf message.
```
___
*[`src/main/resources/duchy/postgres/create-duchy-schema.sql` line 103 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/958#-NTa4I1IEFAMWypCQigD:-NTa4I1IEFAMWypCQigE:b57nk47) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/05309f72310dea2eeb07ea48b4b70eb83af9487d/src/main/resources/duchy/postgres/create-duchy-schema.sql#L103)):*
> ```TSQL
> 
>   -- Serialized JSON string of a proto3 protobuf with details about the
>   -- ongoing computation which do not need to be indexed by the
> ```

nit: make it clear that this is a human-readable copy of the `ComputationDetails` column that's just for debugging, here and for all of the JSON Details columns

We want to make sure that nothing ever tries to parse this



_Suggestion:_
```TSQL
  -- Human-readable copy of the ComputationDetails column for debugging only.
```
___
*[`src/main/resources/duchy/postgres/create-duchy-schema.sql` line 120 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/958#-NTa6mgz8RKndLlsZByx:-NTa6mgz8RKndLlsZByy:bir1d1i) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/05309f72310dea2eeb07ea48b4b70eb83af9487d/src/main/resources/duchy/postgres/create-duchy-schema.sql#L120)):*
> ```TSQL
> CREATE INDEX ComputationsByLockExpirationTime
>   ON Computations(Protocol, LockExpirationTime ASC, UpdateTime ASC)
>   INCLUDE (ComputationStage, GlobalComputationId)
> ```

I don't think we actually need this. We can always replace the index later if it looks like having this would be useful to avoid reading the original table. I believe the query would need to include CreationTime anyway and therefore hit the original table.



_Code quote:_
```TSQL
  INCLUDE (ComputationStage, GlobalComputationId)
```
___
*[`src/main/resources/duchy/postgres/create-duchy-schema.sql` line 123 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/958#-NTa84vECxIHCnANqguM:-NTa84vECxIHCnANqguN:bw764ls) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/05309f72310dea2eeb07ea48b4b70eb83af9487d/src/main/resources/duchy/postgres/create-duchy-schema.sql#L123)):*
> ```TSQL
>   WHERE LockExpirationTime IS NOT NULL;
> 
> -- Query computations by the owner of the lock.
> ```

I don't think we have a use for this. I can't think of any method that would use this index, nor do I see it used when looking at sample query plans in the Spanner table this was copied from.



_Code quote:_
```TSQL
-- Query computations by the owner of the lock.
CREATE INDEX ComputationsByLockOwner ON Computations(LockOwner);
```
___
*[`src/main/resources/duchy/postgres/create-duchy-schema.sql` line 126 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/958#-NTa6CCb2ZU-SVveZIFx:-NTa6CCb2ZU-SVveZIFy:bx63st1) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/05309f72310dea2eeb07ea48b4b70eb83af9487d/src/main/resources/duchy/postgres/create-duchy-schema.sql#L126)):*
> ```TSQL
> CREATE INDEX ComputationsByLockOwner ON Computations(LockOwner);
> 
> -- Enable querying by global computation id.
> ```

nit: Hit the more salient point to make it clear that this index is for behavior rather than for query optimization.



_Suggestion:_
```TSQL
-- Enforce uniqueness of GlobalComputationId.
```


<!-- Sent from Reviewable.io -->

2023-04-24 14:10 UTC, YuhongWang-Amazon reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/958)* status: 6 of 7 files reviewed, 3 unresolved discussions (waiting on @renjiezh and @SanjayVas)

___
*[`src/main/resources/duchy/postgres/create-duchy-schema.sql` line 120 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/958#-NTa6mgz8RKndLlsZByx:-NTn_IYuAi5cWQMqBV7J:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/05309f72310dea2eeb07ea48b4b70eb83af9487d/src/main/resources/duchy/postgres/create-duchy-schema.sql#L120)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I don't think we actually need this. We can always replace the index later if it looks like having this would be useful to avoid reading the original table. I believe the query would need to include CreationTime anyway and therefore hit the original table.
</blockquote></details>

Done.
___
*[`src/main/resources/duchy/postgres/create-duchy-schema.sql` line 123 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/958#-NTa84vECxIHCnANqguM:-NTnWaEh8bLkdwy3EzPR:b-896fix) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/05309f72310dea2eeb07ea48b4b70eb83af9487d/src/main/resources/duchy/postgres/create-duchy-schema.sql#L123)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I don't think we have a use for this. I can't think of any method that would use this index, nor do I see it used when looking at sample query plans in the Spanner table this was copied from.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-04-24 16:49 UTC, SanjayVas approved these changes
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/958)* status: all files reviewed, 3 unresolved discussions (waiting on @YuhongWang-Amazon)

___
*[`src/main/resources/duchy/postgres/create-duchy-schema.sql` line 166 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/958#-NTo8cc86zxTnIv6gdnD:-NTo8cc86zxTnIv6gdnE:b-pww5er) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5bec4dae0464fcb8e902170aca8b34845e8a8fc1/src/main/resources/duchy/postgres/create-duchy-schema.sql#L166)):*
> ```TSQL
>   ComputationId bigint NOT NULL,
> 
>   -- Serialized wfa.measurement.internal.duchy.ComputationStage protobuf message.
> ```

nit: these aren't protobuf messages, but rather the numeric values of protobuf enums.

Technically ComputationStage isn't an enum but rather a message that contains a oneof field that is of some enum type, but it's close enough to describe it as an enum.



_Suggestion:_
```TSQL
-- Numeric value of a wfa.measurement.internal.duchy.ComputationStage protobuf enum.
```
___
*[`src/main/resources/duchy/postgres/create-duchy-schema.sql` line 227 at r4](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/958#-NTo9nsn2DaUG-mCxGDr:-NTo9nsn2DaUG-mCxGDs:b-eomkt6) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/5bec4dae0464fcb8e902170aca8b34845e8a8fc1/src/main/resources/duchy/postgres/create-duchy-schema.sql#L227)):*
> ```TSQL
>   PathToBlob text,
> 
>   -- Serialized wfa.measurement.internal.duchy.ComputationBlobDependency protobuf message.
> ```

nit: these aren't protobuf messages, but rather the numeric values of protobuf enums.



_Suggestion:_
```TSQL
-- Numeric value of a wfa.measurement.internal.duchy.ComputationBlobDependency protobuf enum.
```


<!-- Sent from Reviewable.io -->

2023-04-26 15:28 UTC, merged