Derive the metric state from the state of its associated measurements. Calculate metric results on the fly.
world-federation-of-advertisers/cross-media-measurement pull request #963
Opened 2023-04-21 21:01 UTC by riemanli

2023-04-21 21:01 UTC, wfa-reviewable commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/963)
<!-- Reviewable:end -->

2023-04-21 21:01 UTC, riemanli commented
Current dependencies on/for this PR:
* main
  * **PR #951** <a href="https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/951" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #963** <a href="https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/963" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈
      * **PR #959** <a href="https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/959" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/963?utm_source=stack-comment).

2023-04-21 21:10 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/963)* status: 0 of 6 files reviewed, all discussions resolved (waiting on @SanjayVas and @tristanvuong2021)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/963#-NT_dM-_DyCQWP7UoZtU:-NT_dM-_DyCQWP7UoZtV:bz1tmpf) (no related file):*
@SanjayVas @tristanvuong2021 If you think the changes should be merged into #951 instead of being in a separate PR, please let me know. 

___


<!-- Sent from Reviewable.io -->

2023-04-21 23:44 UTC, SanjayVas requested changes
> Reviewed 4 of 6 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/963)* status: all files reviewed, 2 unresolved discussions (waiting on @riemanli and @tristanvuong2021)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/963#-NTaC9dN0s7ioMxF3a_s:-NTaC9dN0s7ioMxF3a_t:baomsx1) (no related file):*
I love PRs that mostly delete code :)

___
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 1385 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/963#-NTa9XYm4xcwvnq59jHC:-NTa9XYm4xcwvnq59jHD:b7zh4eo) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/be21292fe6300580c17d983308dbc77e39045ac0/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L1385)):*
> ```Kotlin
> 
> /** Determines the [Metric.State] based on the given [InternalMetric]. */
> private fun determineMetricState(metric: InternalMetric): Metric.State {
> ```

If you want, you can make this an extension property on InternalMetric.

```kotlin
private val InternalMetric.state: Metric.State
  get() {
    // ...
  }
```
___
*[`src/main/proto/wfa/measurement/internal/reporting/v2/metric.proto` line 113 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/963#-NTa9wb93I7ixND40007:-NTa9wb93I7ixND40008:b-2ow9ip) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/be21292fe6300580c17d983308dbc77e39045ac0/src/main/proto/wfa/measurement/internal/reporting/v2/metric.proto#L113)):*
> ```protobuf
>   MetricSpec metric_spec = 6;
> 
>   enum State {
> ```

You shouldn't need this enum anymore, since it's derived. If you only ever need to determine the state in the public service impl, you can just use the public API enum.


<!-- Sent from Reviewable.io -->

2023-04-22 00:16 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/963)* status: 4 of 6 files reviewed, 2 unresolved discussions (waiting on @SanjayVas and @tristanvuong2021)

*[a discussion](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/963#-NTaC9dN0s7ioMxF3a_s:-NTaEpgx2PuikAz2Mu-j:bc52tdo) (no related file):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

I love PRs that mostly delete code :)
</blockquote></details>

:laughing: 

___
___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt` line 1385 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/963#-NTa9XYm4xcwvnq59jHC:-NTaFgvz5_qP0A5LXEBL:b-jasabi) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/be21292fe6300580c17d983308dbc77e39045ac0/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/MetricsService.kt#L1385)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

If you want, you can make this an extension property on InternalMetric.

```kotlin
private val InternalMetric.state: Metric.State
  get() {
    // ...
  }
```
</blockquote></details>

Thanks for the suggestion! I had thought about this, but then I wasn't sure if using `InternalMetric.state` to compare with `Metric.State` is weird. Thanks for letting me know it's ok!
___
*[`src/main/proto/wfa/measurement/internal/reporting/v2/metric.proto` line 113 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/963#-NTa9wb93I7ixND40007:-NTaHiuEAOfZHoNQflr9:b-mws2j5) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/be21292fe6300580c17d983308dbc77e39045ac0/src/main/proto/wfa/measurement/internal/reporting/v2/metric.proto#L113)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

You shouldn't need this enum anymore, since it's derived. If you only ever need to determine the state in the public service impl, you can just use the public API enum.
</blockquote></details>

Thanks for pointing it out! Done.


<!-- Sent from Reviewable.io -->

2023-04-24 16:42 UTC, SanjayVas approved these changes
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/963)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @tristanvuong2021)



<!-- Sent from Reviewable.io -->

2023-04-25 16:52 UTC, stevenwarejones approved these changes
> Reviewed 3 of 6 files at r1, 1 of 2 files at r2, 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/963)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Marco-Premier and @tristanvuong2021)



<!-- Sent from Reviewable.io -->

2023-04-25 16:55 UTC, riemanli commented
[Graphite](https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/963) rebased this pull request as part of a merge.

2023-04-25 17:21 UTC, merged