Add SetExpressionCompiler for reporting v2alpha
world-federation-of-advertisers/cross-media-measurement pull request #968
Opened 2023-04-25 16:21 UTC by riemanli

Difference between v1 and v2:
* Treat the v2 one as a pure algorithm library. 
    * Remove proto dependency.
    * The conversion from `ReportingSet.SetExpression` to `SetExpressionCompiler.SetOperationExpression` is now done by the caller. 
* The reporting set in `setOperationExpression` has to be indexed from 0 to `numReportingSets - 1`.

2023-04-25 16:21 UTC, wfa-reviewable commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/968)
<!-- Reviewable:end -->

2023-04-25 17:34 UTC, riemanli commented
Current dependencies on/for this PR:
* main
  * **PR #951** <a href="https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/951" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #963** <a href="https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/963" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #959** <a href="https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/959" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
        * **PR #968** <a href="https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/968" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/968?utm_source=stack-comment).

2023-04-25 18:29 UTC, SanjayVas requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/968)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @chenweiw and @riemanli)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/SetExpressionCompiler.kt` line 107 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/968#-NTteAF4ER1fwaiz0bM-:-NTteAF4ER1fwaiz0bM0:bfssna8) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c2c41fc749eb353a881d3f50f08465f97b3e4ee1/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/SetExpressionCompiler.kt#L107)):*
> ```Kotlin
>   private val vennDiagramDecompositionCache: VennDiagramDecompositionCache = mutableMapOf()
> 
>   // For unit test only.
> ```

This is a code smell. Do we really need to verify the caching behavior? If it's not observable from the public API then it probably doesn't need to be tested. If the only observable trait is performance then we can pick that up in a performance test.
___
*[`src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/SetExpressionCompilerTest.kt` line 118 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/968#-NTtdpPMBcz7WyvlM0F_:-NTtdpPMBcz7WyvlM0Fa:b-faaohe) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/c2c41fc749eb353a881d3f50f08465f97b3e4ee1/src/test/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/SetExpressionCompilerTest.kt#L118)):*
> ```Kotlin
>     }
> 
>     Truth.assertThat(resultAllUnionButOne)
> ```

nit: import assertThat



_Code quote:_
```Kotlin
Truth.assertThat
```


<!-- Sent from Reviewable.io -->

2023-04-26 17:53 UTC, SanjayVas approved these changes
> Reviewed 2 of 4 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/968)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @chenweiw)



<!-- Sent from Reviewable.io -->

2023-04-26 18:01 UTC, chenweiw commented on src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/SetExpressionCompiler.kt
> +  MutableMap<NumberReportingSets, VennDiagramDecomposition>
I remember we did not have this memory in the alpha version. Is it a new feature we add in w2alpha?

2023-04-26 18:05 UTC, riemanli reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/968)* status: all files reviewed, 1 unresolved discussion (waiting on @chenweiw)

___
*[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/SetExpressionCompiler.kt` line 82 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/968#gh-1178224574:-NTyib6V23NOvOEJOzPZ:b-gpm1nh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1d32ec7f893aaa27631866248ff51097f6b6bd67/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/SetExpressionCompiler.kt#L82)):*
<details><summary><i>Previously, chenweiw wrote…</i></summary><blockquote>

I remember we did not have this memory in the alpha version. Is it a new feature we add in w2alpha?
</blockquote></details>

Yes! I figured that which primitive regions form a reporting set is static and only depending on the number of reporting sets. We can save this 2^(N-1) computation by using a memory cache.


<!-- Sent from Reviewable.io -->

2023-04-26 18:18 UTC, chenweiw reviewed
The algorithm of calculating SetOperation expressions is correct.

2023-04-26 18:23 UTC, chenweiw commented
> > _[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/968)_ status: all files reviewed, 1 unresolved discussion (waiting on @chenweiw)
> 
> _[`src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/SetExpressionCompiler.kt` line 82 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/968#gh-1178224574:-NTyib6V23NOvOEJOzPZ:b-gpm1nh) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/1d32ec7f893aaa27631866248ff51097f6b6bd67/src/main/kotlin/org/wfanet/measurement/reporting/service/api/v2alpha/SetExpressionCompiler.kt#L82)):_
> 
> Previously, chenweiw wrote…
> Yes! I figured that which primitive regions form a reporting set is static and only depending on the number of reporting sets. We can save this 2^(N-1) computation by using a memory cache.

It makes sense. Thank you Rieman.

2023-04-26 18:30 UTC, chenweiw approved these changes
The algorithm implementation of calculating the SetOperation expressions is correct.

2023-04-26 22:01 UTC, stevenwarejones approved these changes
> Reviewed 2 of 4 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/968)* status: all files reviewed, 1 unresolved discussion (waiting on @chenweiw)



<!-- Sent from Reviewable.io -->

2023-05-01 16:20 UTC, riemanli reviewed
> Dismissed @chenweiw from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/968)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @riemanli)



<!-- Sent from Reviewable.io -->

2023-05-01 16:48 UTC, riemanli commented
@riemanli queued this pull request to merge with [Graphite](https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/968).

2023-05-01 16:49 UTC, riemanli commented
[Graphite](https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/968) rebased this pull request as part of a merge.

2023-05-01 16:53 UTC, riemanli commented
The [Graphite](https://app.graphite.dev/github/pr/world-federation-of-advertisers/cross-media-measurement/968) merge of this pull request was cancelled.

2023-05-01 17:11 UTC, riemanli reviewed
> Reviewed 1 of 4 files at r1, 2 of 2 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/968)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @riemanli)



<!-- Sent from Reviewable.io -->

2023-05-01 17:12 UTC, merged