Update the confirmationPhase processor in the llv2 mill.
world-federation-of-advertisers/cross-media-measurement pull request #98
Opened 2021-06-07 23:09 UTC by wangyaopw

Behavior change:
previously, the mill would fetch all local requisitions from the
metricValueService and store the combined sketch locally for the future
processing.
Now, the mill just verify requistions status based on the database information,
no blob read/write is done.

so the output blob number of the INITIALIZATION_PHASE changes from 1 to
0. And there is no input blob for the WAIT_TO_START and
WAIT_SETUP_PHASE_INPUT stages any more.

2021-06-07 23:47 UTC, SanjayVas requested changes
> Reviewed 10 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/98)* status: all files reviewed, 1 unresolved discussion (waiting on @wangyaopw)

___
*[src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2Mill.kt, line 249 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/98#-MbcqOji2pvWUBmZydV0:-MbcqOji2pvWUBmZydV1:b-m77vxr) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a941e1dfc22f6b3a8321233e4c9b50650eac0509/src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2Mill.kt#L249)):*
> ```
>    * Verifies the Edp signature and the local existence of requisitions. Returns an error message if
>    * anything is wrong. Otherwise return an empty string.
> ```
This is a really odd pattern, as it effectively requires inspecting the content of a string to determine whether there was an error.

Given that this is something that's not expected to happen frequently, why not throw an exception? The only benefit to this approach appears to be that it doesn't fail fast and instead collects all the errors, but I'm not sure there's significant value there.

If you really want to do this, it would be clearer to return a collection of error messages (since each method appears to be set up for having multiple error messages). This way, checking errors is just a simple size check and collecting errors can be done by concatenation. Even better would be using an Error data class around the message so it's even clearer that the return value is a collection of errors.


<!-- Sent from Reviewable.io -->

2021-06-08 00:40 UTC, wangyaopw reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/98)* status: 9 of 10 files reviewed, 1 unresolved discussion (waiting on @SanjayVas)

___
*[src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2Mill.kt, line 249 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/98#-MbcqOji2pvWUBmZydV0:-Mbd2k4J94weTTV3QABF:bmgmwnm) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/a941e1dfc22f6b3a8321233e4c9b50650eac0509/src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2Mill.kt#L249)):*
<details><summary><i>Previously, SanjayVas (Sanjay Vasandani) wrote…</i></summary><blockquote>

> ```
>    * Verifies the Edp signature and the local existence of requisitions. Returns an error message if
>    * anything is wrong. Otherwise return an empty string.
> ```
This is a really odd pattern, as it effectively requires inspecting the content of a string to determine whether there was an error.

Given that this is something that's not expected to happen frequently, why not throw an exception? The only benefit to this approach appears to be that it doesn't fail fast and instead collects all the errors, but I'm not sure there's significant value there.

If you really want to do this, it would be clearer to return a collection of error messages (since each method appears to be set up for having multiple error messages). This way, checking errors is just a simple size check and collecting errors can be done by concatenation. Even better would be using an Error data class around the message so it's even clearer that the return value is a collection of errors.
</blockquote></details>

Returning a list of error message sounds good. Done

I do feel returning all errors is helpful in debugging, otherwise it is like fixing one failure and then finding the next one and then the next one.


<!-- Sent from Reviewable.io -->

2021-06-08 00:50 UTC, SanjayVas approved these changes
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/98)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wangyaopw)



<!-- Sent from Reviewable.io -->

2021-06-10 20:59 UTC, zachcwc commented
___
*[src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2Mill.kt, line 270 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/98#-Mbri9BwCXDsFXmpred7:-Mbri9BwCXDsFXmpred8:b-q8tkcz) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/58989e822493336bb40a73ae5f04eb290739eb9e/src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2Mill.kt#L270)):*
> ```Kotlin
>     val errorList = mutableListOf<String>()
>     // TODO(wangyaopw): verify el_gamal_public_key_signature and update errorMessage if necessary.
>     if (!(duchy.duchyId == duchyId || workerStubs.containsKey(duchy.duchyId))) {
> ```

Why does workerStubs.containsKey(duchy.duchyID) being true result in failure?


<!-- Sent from Reviewable.io -->

2021-06-10 22:03 UTC, wangyaopw reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/98)* status: 7 of 14 files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2Mill.kt, line 270 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/98#-Mbri9BwCXDsFXmpred7:-MbrwO8mBjfIqjukfUsm:b-saqao3) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/58989e822493336bb40a73ae5f04eb290739eb9e/src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2Mill.kt#L270)):*
<details><summary><i>Previously, zachcwc wrote…</i></summary><blockquote>

Why does workerStubs.containsKey(duchy.duchyID) being true result in failure?
</blockquote></details>

There is a ! in the beginning.

so
`duchy.duchyId == duchyId` means this duchy is myself
`workerStubs.containsKey(duchy.duchyId)` means this is a duchy I know.

if neither of these two is true, then there is an error.


<!-- Sent from Reviewable.io -->

2021-06-10 22:05 UTC, wangyaopw reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/98)* status: 7 of 14 files reviewed, 1 unresolved discussion (waiting on @SanjayVas and @zachcwc)

___
*[src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2Mill.kt, line 270 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/98#-Mbri9BwCXDsFXmpred7:-MbrxCv71I2yamTeXL7R:br0ewph) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/58989e822493336bb40a73ae5f04eb290739eb9e/src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2Mill.kt#L270)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

There is a ! in the beginning.

so
`duchy.duchyId == duchyId` means this duchy is myself
`workerStubs.containsKey(duchy.duchyId)` means this is a duchy I know.

if neither of these two is true, then there is an error.
</blockquote></details>

maybe I should write 
if ( duchy.duchyId != duchyId && !workerStubs.containsKey(duchy.duchyId))


<!-- Sent from Reviewable.io -->

2021-06-10 22:48 UTC, zachcwc commented
___
*[src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2Mill.kt, line 270 at r3](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/98#-Mbri9BwCXDsFXmpred7:-Mbs69O71C9IADRBatVl:b-p0lbl7) ([raw file](https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/58989e822493336bb40a73ae5f04eb290739eb9e/src/main/kotlin/org/wfanet/measurement/duchy/daemon/mill/liquidlegionsv2/LiquidLegionsV2Mill.kt#L270)):*
<details><summary><i>Previously, wangyaopw (Yao Wang) wrote…</i></summary><blockquote>

maybe I should write 
if ( duchy.duchyId != duchyId && !workerStubs.containsKey(duchy.duchyId))
</blockquote></details>

ohhhh! I missed that both conditions were inside the parens, ok makes sense thanks!


<!-- Sent from Reviewable.io -->

2021-06-10 22:49 UTC, zachcwc approved these changes
> Reviewed 7 of 10 files at r1, 7 of 7 files at r3, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/cross-media-measurement/98)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @wangyaopw)



<!-- Sent from Reviewable.io -->

2021-06-10 23:02 UTC, merged